### ISSUE TITLE
flannel or calico

### ISSUE THREAD

**Issue by sudharsanomprakash** [kubevirt/kubevirt#10010]
I want use both k8-pod network and vlan as secondary interface using multus. 

Currently, I am using calico and running into route issues between pod and vlan network. I believe this is because calico tries to go to the default gateway IP which is 169.254.1.1 and vlan is in 172.18.x.x range. I believe flannel might not have issue because it uses vxlan ( I haven't tried flannel yet)

So, Which is better option for kubevirt calico or flannel? Any recommendation or feedback is appreciated. Thank you

**Comment by EdDev** [comment]
This look to me like a recommendation/question request and not a bug.
I would suggest posting this on the kubevirt-dev mailing list (googlegroup).

Kubevirt has no preference on which network provider to use.
I think both calico and flannel should work fine, although I am not familiar with any of them when referring to secondary interfaces.

Before sending this on the maling list, I would recommend you add the VM and NAD manifests, without it, it is hard to understand what you are doing.
Also, a network diagram of how you expect your network connectivity to be will be useful.

/assign

**Comment by EdDev** [comment]
It has been suggested to ask this on the mailing list. See previous comment from last week.

As no additional input has been seen on this, the issue is being closed.

/close
