### ISSUE TITLE
Failed to create the vm！

### ISSUE THREAD

**Issue by kongyu666** [kubevirt/kubevirt#10014]
- KubeVirt version：v0.59.2
- Kubernetes version：v1.23.12

After the vm is created, the controller reports the following error:

{"component":"virt-controller","level":"info","msg":"re-enqueuing VirtualMachine default/testvm","pos":"vm.go:241","reason":"Operation cannot be fulfilled on virtualmachines.kubevirt.io \"testvm\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2023-06-30T01:29:09.491693Z"}
{"component":"virt-controller","kind":"","level":"error","msg":"Updating api version annotations failed","name":"testvm","namespace":"default","pos":"vm.go:275","reason":"Operation cannot be fulfilled on virtualmachines.kubevirt.io \"testvm\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2023-06-30T01:29:09.515565Z","uid":"713048f7-d4c4-409d-a8a8-f1c57ca6a667"}
![image](https://github.com/kubevirt/kubevirt/assets/84981511/97b7ca41-02f6-4b11-a817-0a75c3424035)

**Comment by vasiliy-ul** [comment]
Hi @kongyu666, please provide the logs of `virt-handler` and `virt-launcher` pods.

**Comment by kongyu666** [comment]
VMS before v0.58.2 can be used normally. However, a vm creation error occurs since v0.59.1. The log is as follows:


virt-launcher:
{"component":"virt-launcher-monitor","level":"error","msg":"failed to run virt-launcher","pos":"virt-launcher-monitor.go:108","reason":"fork/exec /usr/bin/virt-launcher: errno 0","timestamp":"2023-07-07T02:10:29.690662Z"}
{"component":"virt-launcher-monitor","level":"error","msg":"monitoring virt-launcher failed","pos":"virt-launcher-monitor.go:86","reason":"fork/exec /usr/bin/virt-launcher: errno 0","timestamp":"2023-07-07T02:10:37.501429Z"}





virt-handler:
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled | Domain does not exist","name":"vm-centos7.9","namespace":"default","pos":"vm.go:1759","timestamp":"2023-07-07T02:10:30.598337Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","level":"error","msg":"couldn't find the SELinux context for vm-centos7.9","pos":"vm.go:1287","reason":"No command socket found for vmi bac0081a-cb4c-4f9a-a8f9-459329c6cfce","timestamp":"2023-07-07T02:10:30.630373Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"migration is block migration because of containerdisk volume","name":"vm-centos7.9","namespace":"default","pos":"vm.go:2429","timestamp":"2023-07-07T02:10:30.630488Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","kind":"","level":"info","msg":"migration is block migration because of emptydisk volume","name":"vm-centos7.9","namespace":"default","pos":"vm.go:2429","timestamp":"2023-07-07T02:10:30.630522Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","kind":"","level":"info","msg":"migration is block migration because of cloudinitdisk volume","name":"vm-centos7.9","namespace":"default","pos":"vm.go:2429","timestamp":"2023-07-07T02:10:30.630539Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled | Domain does not exist","name":"vm-centos7.9","namespace":"default","pos":"vm.go:1759","timestamp":"2023-07-07T02:10:30.643829Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","level":"error","msg":"couldn't find the SELinux context for vm-centos7.9","pos":"vm.go:1287","reason":"No command socket found for vmi bac0081a-cb4c-4f9a-a8f9-459329c6cfce","timestamp":"2023-07-07T02:10:30.673315Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled | Domain does not exist","name":"vm-centos7.9","namespace":"default","pos":"vm.go:1759","timestamp":"2023-07-07T02:10:31.598684Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","level":"error","msg":"couldn't find the SELinux context for vm-centos7.9","pos":"vm.go:1287","reason":"No command socket found for vmi bac0081a-cb4c-4f9a-a8f9-459329c6cfce","timestamp":"2023-07-07T02:10:31.633755Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled | Domain does not exist","name":"vm-centos7.9","namespace":"default","pos":"vm.go:1759","timestamp":"2023-07-07T02:10:32.600728Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","level":"error","msg":"couldn't find the SELinux context for vm-centos7.9","pos":"vm.go:1287","reason":"No command socket found for vmi bac0081a-cb4c-4f9a-a8f9-459329c6cfce","timestamp":"2023-07-07T02:10:32.633942Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled | Domain does not exist","name":"vm-centos7.9","namespace":"default","pos":"vm.go:1759","timestamp":"2023-07-07T02:10:33.600946Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","level":"error","msg":"couldn't find the SELinux context for vm-centos7.9","pos":"vm.go:1287","reason":"No command socket found for vmi bac0081a-cb4c-4f9a-a8f9-459329c6cfce","timestamp":"2023-07-07T02:10:33.642714Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled | Domain does not exist","name":"vm-centos7.9","namespace":"default","pos":"vm.go:1759","timestamp":"2023-07-07T02:10:34.602904Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","level":"error","msg":"couldn't find the SELinux context for vm-centos7.9","pos":"vm.go:1287","reason":"No command socket found for vmi bac0081a-cb4c-4f9a-a8f9-459329c6cfce","timestamp":"2023-07-07T02:10:34.628639Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled | Domain does not exist","name":"vm-centos7.9","namespace":"default","pos":"vm.go:1759","timestamp":"2023-07-07T02:10:35.603242Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","level":"error","msg":"couldn't find the SELinux context for vm-centos7.9","pos":"vm.go:1287","reason":"No command socket found for vmi bac0081a-cb4c-4f9a-a8f9-459329c6cfce","timestamp":"2023-07-07T02:10:35.642525Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled | Domain does not exist","name":"vm-centos7.9","namespace":"default","pos":"vm.go:1759","timestamp":"2023-07-07T02:10:36.604581Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","level":"error","msg":"couldn't find the SELinux context for vm-centos7.9","pos":"vm.go:1287","reason":"No command socket found for vmi bac0081a-cb4c-4f9a-a8f9-459329c6cfce","timestamp":"2023-07-07T02:10:36.632471Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled | Domain does not exist","name":"vm-centos7.9","namespace":"default","pos":"vm.go:1759","timestamp":"2023-07-07T02:10:37.604900Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","level":"error","msg":"couldn't find the SELinux context for vm-centos7.9","pos":"vm.go:1287","reason":"No command socket found for vmi bac0081a-cb4c-4f9a-a8f9-459329c6cfce","timestamp":"2023-07-07T02:10:37.634338Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled | Domain does not exist","name":"vm-centos7.9","namespace":"default","pos":"vm.go:1759","timestamp":"2023-07-07T02:10:37.664523Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","level":"error","msg":"couldn't find the SELinux context for vm-centos7.9","pos":"vm.go:1287","reason":"No command socket found for vmi bac0081a-cb4c-4f9a-a8f9-459329c6cfce","timestamp":"2023-07-07T02:10:37.702962Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled | Domain does not exist","name":"vm-centos7.9","namespace":"default","pos":"vm.go:1759","timestamp":"2023-07-07T02:10:38.605503Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","level":"error","msg":"couldn't find the SELinux context for vm-centos7.9","pos":"vm.go:1287","reason":"No command socket found for vmi bac0081a-cb4c-4f9a-a8f9-459329c6cfce","timestamp":"2023-07-07T02:10:38.635674Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled | Domain does not exist","name":"vm-centos7.9","namespace":"default","pos":"vm.go:1759","timestamp":"2023-07-07T02:10:39.606016Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","level":"error","msg":"couldn't find the SELinux context for vm-centos7.9","pos":"vm.go:1287","reason":"No command socket found for vmi bac0081a-cb4c-4f9a-a8f9-459329c6cfce","timestamp":"2023-07-07T02:10:39.636242Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled | Domain does not exist","name":"vm-centos7.9","namespace":"default","pos":"vm.go:1759","timestamp":"2023-07-07T02:10:40.607283Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","level":"error","msg":"couldn't find the SELinux context for vm-centos7.9","pos":"vm.go:1287","reason":"No command socket found for vmi bac0081a-cb4c-4f9a-a8f9-459329c6cfce","timestamp":"2023-07-07T02:10:40.638963Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Failed | Domain does not exist","name":"vm-centos7.9","namespace":"default","pos":"vm.go:1759","timestamp":"2023-07-07T02:10:40.655331Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","kind":"","level":"info","msg":"Performing final local cleanup for vmi with uid bac0081a-cb4c-4f9a-a8f9-459329c6cfce","name":"vm-centos7.9","namespace":"default","pos":"vm.go:2023","timestamp":"2023-07-07T02:10:40.655413Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","kind":"","level":"info","msg":"No container disk mount entries found to unmount","name":"vm-centos7.9","namespace":"default","pos":"mount.go:349","timestamp":"2023-07-07T02:10:40.655447Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","kind":"","level":"info","msg":"Cleaning up remaining hotplug volumes","name":"vm-centos7.9","namespace":"default","pos":"mount.go:769","timestamp":"2023-07-07T02:10:40.655463Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Removing domain from cache during final cleanup","name":"vm-centos7.9","namespace":"default","pos":"vm.go:2057","timestamp":"2023-07-07T02:10:40.655509Z","uid":""}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Failed | Domain does not exist","name":"vm-centos7.9","namespace":"default","pos":"vm.go:1759","timestamp":"2023-07-07T02:10:40.661506Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","kind":"","level":"info","msg":"Performing final local cleanup for vmi with uid bac0081a-cb4c-4f9a-a8f9-459329c6cfce","name":"vm-centos7.9","namespace":"default","pos":"vm.go:2023","timestamp":"2023-07-07T02:10:40.661833Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","kind":"","level":"info","msg":"No container disk mount entries found to unmount","name":"vm-centos7.9","namespace":"default","pos":"mount.go:349","timestamp":"2023-07-07T02:10:40.661895Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","kind":"","level":"info","msg":"Cleaning up remaining hotplug volumes","name":"vm-centos7.9","namespace":"default","pos":"mount.go:769","timestamp":"2023-07-07T02:10:40.661918Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Removing domain from cache during final cleanup","name":"vm-centos7.9","namespace":"default","pos":"vm.go:2057","timestamp":"2023-07-07T02:10:40.661967Z","uid":""}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Failed | Domain does not exist","name":"vm-centos7.9","namespace":"default","pos":"vm.go:1759","timestamp":"2023-07-07T02:10:40.683784Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","kind":"","level":"info","msg":"Performing final local cleanup for vmi with uid bac0081a-cb4c-4f9a-a8f9-459329c6cfce","name":"vm-centos7.9","namespace":"default","pos":"vm.go:2023","timestamp":"2023-07-07T02:10:40.683873Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","kind":"","level":"info","msg":"No container disk mount entries found to unmount","name":"vm-centos7.9","namespace":"default","pos":"mount.go:349","timestamp":"2023-07-07T02:10:40.683913Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","kind":"","level":"info","msg":"Cleaning up remaining hotplug volumes","name":"vm-centos7.9","namespace":"default","pos":"mount.go:769","timestamp":"2023-07-07T02:10:40.683929Z","uid":"bac0081a-cb4c-4f9a-a8f9-459329c6cfce"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Removing domain from cache during final cleanup","name":"vm-centos7.9","namespace":"default","pos":"vm.go:2057","timestamp":"2023-07-07T02:10:40.683974Z","uid":""}
{"component":"virt-handler","level":"info","msg":"VMI does not exist | Domain does not exist","pos":"vm.go:1764","timestamp":"2023-07-07T02:10:40.732550Z"}
{"component":"virt-handler","kind":"VirtualMachineInstance","level":"info","msg":"Performing final local cleanup for vmi with uid ","name":"vm-centos7.9","namespace":"default","pos":"vm.go:2023","timestamp":"2023-07-07T02:10:40.732620Z","uid":""}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Removing domain from cache during final cleanup","name":"vm-centos7.9","namespace":"default","pos":"vm.go:2057","timestamp":"2023-07-07T02:10:40.732651Z","uid":""}
{"component":"virt-handler","level":"error","msg":"failed to remove mdev types: failed to read the content of /sys/bus/mdev/devices directory","pos":"mediated_devices_types.go:275","reason":"open /sys/bus/mdev/devices: no such file or directory","timestamp":"2023-07-07T02:11:15.754547Z"}
{"component":"virt-handler","level":"info","msg":"refreshed device plugins for permitted/forbidden host devices","pos":"device_controller.go:345","timestamp":"2023-07-07T02:11:15.754624Z"}
{"component":"virt-handler","level":"info","msg":"enabled device-plugins for: []","pos":"device_controller.go:346","timestamp":"2023-07-07T02:11:15.754641Z"}
{"component":"virt-handler","level":"info","msg":"disabled device-plugins for: []","pos":"device_controller.go:347","timestamp":"2023-07-07T02:11:15.754650Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: resourceName: kvm","pos":"generic_device.go:242","timestamp":"2023-07-07T02:11:33.782079Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: request: [&amp;ContainerAllocateRequest{DevicesIDs:[kvm339],}]","pos":"generic_device.go:243","timestamp":"2023-07-07T02:11:33.782171Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: resourceName: tun","pos":"generic_device.go:242","timestamp":"2023-07-07T02:11:33.782977Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: request: [&amp;ContainerAllocateRequest{DevicesIDs:[tun617],}]","pos":"generic_device.go:243","timestamp":"2023-07-07T02:11:33.783016Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: resourceName: vhost-net","pos":"generic_device.go:242","timestamp":"2023-07-07T02:11:33.784696Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: request: [&amp;ContainerAllocateRequest{DevicesIDs:[vhost-net747],}]","pos":"generic_device.go:243","timestamp":"2023-07-07T02:11:33.784751Z"}





梦一场
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubevirt/kubevirt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月30日(星期五) 下午4:48
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kubevirt/kubevirt] Failed to create the vm！ (Issue #10014)





 
Hi @kongyu666, please provide the logs of virt-handler and virt-launcher pods.

**Comment by vasiliy-ul** [comment]
@kongyu666, what container runtime are you using? Is it docker?

> {"component":"virt-launcher-monitor","level":"error","msg":"failed to run virt-launcher","pos":"virt-launcher-monitor.go:108","reason":"fork/exec /usr/bin/virt-launcher: errno 0","timestamp":"2023-07-07T02:10:29.690662Z"}

This looks similar to https://github.com/kubevirt/kubevirt/issues/9465

**Comment by kongyu666** [comment]
Yes, I already know that I need to use k8s v1.24+ from v0.59, but my k8s is v.1.23.12 and I use docker




梦一场
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubevirt/kubevirt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月7日(星期五) 中午1:49
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kubevirt/kubevirt] Failed to create the vm！ (Issue #10014)





 
@kongyu666, what container runtime are you using? Is it docker?
  
{"component":"virt-launcher-monitor","level":"error","msg":"failed to run virt-launcher","pos":"virt-launcher-monitor.go:108","reason":"fork/exec /usr/bin/virt-launcher: errno 0","timestamp":"2023-07-07T02:10:29.690662Z"}
  
This looks similar to #9465

**Comment by vasiliy-ul** [comment]
There is currently a known issue with docker. Even if you update k8s, it may not help. This needs to be fixed in moby https://github.com/moby/moby/issues/45491

**Comment by vasiliy-ul** [comment]
If it's not for production use, you can enable the `Root` feature gate, and it should work on your setup.

**Comment by kongyu666** [comment]
Is that true, please?






apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
&nbsp; name: kubevirt
&nbsp; namespace: kubevirt
spec:
&nbsp; certificateRotateStrategy: {}
&nbsp; configuration:
&nbsp; &nbsp; developerConfiguration:
&nbsp; &nbsp; &nbsp; featureGates:
&nbsp; &nbsp; &nbsp; - Root
&nbsp; customizeComponents: {}
&nbsp; imagePullPolicy: IfNotPresent
&nbsp; workloadUpdateStrategy: {}





梦一场
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubevirt/kubevirt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月7日(星期五) 中午1:54
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kubevirt/kubevirt] Failed to create the vm！ (Issue #10014)





 
If it's not for production use, you can enable the Root feature gate, and it should work on your setup.

**Comment by vasiliy-ul** [comment]
I think it should work, though, as I mentioned above, it has some security implications:

> Note, that it will make all your VMs run from the root user.

**Comment by kongyu666** [comment]
Good. Thanks for your answer. I got it, too. I don't use this in a production environment



好点，感谢你的回答，我也解决了。我这个不用于生产环境

梦一场
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubevirt/kubevirt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月7日(星期五) 下午2:00
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kubevirt/kubevirt] Failed to create the vm！ (Issue #10014)





 
I think it should work, though, as I mentioned above, it has some security implications:
  
Note, that it will make all your VMs run from the root user.

**Comment by vasiliy-ul** [comment]
Another option might be to switch from docker to smth else. E.g. `containerd` should work.

**Comment by kongyu666** [comment]
Okay, thank you





梦一场
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubevirt/kubevirt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年7月7日(星期五) 下午2:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kubevirt/kubevirt] Failed to create the vm！ (Issue #10014)





 
Another option might be to switch from docker to smth else. E.g. containerd should work.

**Comment by k8scoder192** [comment]
@vasiliy-ul they fixed moby https://github.com/moby/moby/issues/45491 (PR https://github.com/moby/moby/pull/45511)

Any chance this can get pulled into Kubevirt to resolve?

**Comment by vasiliy-ul** [comment]
Answered at https://github.com/kubevirt/kubevirt/issues/9465#issuecomment-1673437332

**Comment by 66545shiwo** [comment]
@vasiliy-ul 
hello,may I ask which version has fixed this bug?  my docker server version is `20.10.24`

**Comment by kongyu666** [comment]
apiVersion:&nbsp;kubevirt.io/v1
kind: KubeVirt
metadata:
&nbsp; name: kubevirt
&nbsp; namespace: kubevirt
spec:
&nbsp; certificateRotateStrategy: {}
&nbsp; configuration:
&nbsp; &nbsp; developerConfiguration:
&nbsp; &nbsp; &nbsp; featureGates:
&nbsp; &nbsp; &nbsp; - Root
&nbsp; customizeComponents: {}
&nbsp; imagePullPolicy: IfNotPresent
&nbsp; workloadUpdateStrategy: {}


梦一场
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "kubevirt/kubevirt"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年9月19日(星期二) 上午9:45
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [kubevirt/kubevirt] Failed to create the vm！ (Issue #10014)





 
@vasiliy-ul
 hello,may I ask which version has fixed this bug?  my docker server version is 20.10.24

**Comment by vasiliy-ul** [comment]
> @vasiliy-ul hello,may I ask which docker version has fixed this bug? my docker server version is `20.10.24`

Hi @66545shiwo. I usually do not use docker, so not sure about the version, unfortunately. After a quick look, I do not see that the commit https://github.com/moby/moby/commit/3aef732e61ec8ae0ea0bd8ad31116194e0fc21a6 has been backported to `20.10.x` branch.

Refer to the comment: https://github.com/moby/moby/pull/45511#issuecomment-1673488655. Apparently there are backports only for 23.x and 24.x.

**Comment by 66545shiwo** [comment]
@vasiliy-ul  
Thank you for your reply. The Docker version `24.0.6` is fine (I have tested it).

However, I have another issue regarding the use of CDI to create a VM (Virtual Machine): https://github.com/kubevirt/kubevirt/issues/10446. It still has some problems with Docker version `24.0.6`.
