### ISSUE TITLE
how to reduce labels of node ?

### ISSUE THREAD

**Issue by rfyiamcool** [kubevirt/kubevirt#10032]
### desc

I found node object contains many labels for kubevirt. Are these necessary? 😅 

<img width="1781" alt="image" src="https://github.com/kubevirt/kubevirt/assets/3785409/264d6fef-a330-41fb-afc9-62f4ce9f3567">

**Comment by simonyangcj** [comment]
as much as i know, most of labels with cpu prefix are used for compare cpu feature between target node and source node when perform a live migration. I don't think there is anything we can do for now :)

**Comment by vasiliy-ul** [comment]
@oshoval, those XMLs are the test data for unit tests. They've been added for the SEV feature. Do you think they cause some issue?

**Comment by vasiliy-ul** [comment]
Those SEV XMLs were grabbed from real machines using `virsh domcapabilities`, and all the usable CPU models are valid there. I assume, it just happens that the machine here has the same (or similar) capabilities.

**Comment by rfyiamcool** [comment]
> production

the node is from production env.

**Comment by oshoval** [comment]
Thanks
It's either what @vasiliy-ul raised or worth investigation then, wdyt ?

**Comment by mspinassi-medallia** [comment]
I know this case is already closed, but I was wondering the same thing as OP. Our current label count for kubevirt is 174
Maybe some can be grouped together? Or advertise features from virt-handler instead of node labels?

**Comment by mspinassi-medallia** [comment]
Hi @xpivarc! Thanks for taking the time to reply here

I understand the reason why they are there and how they are used, and why they are so useful to kubevirt.
My point was more in line with what OP mentioned on being a bit noisy on labels (comparing my non-kubevirt nodes that have about 6 labels vs 170+ on the kubevirt ones).

It does not have any impact on our clusters and I guess it could fall under the "nice to have" category.
