### ISSUE TITLE
After the server is powered off, the virtual machine starts up abnormally.

### ISSUE THREAD

**Issue by rfyiamcool** [kubevirt/kubevirt#10048]
**What happened**:

After the system node is restarted, the virtual machine starts up abnormally，entering the desktop of the windows10 system, it prompts that the memory is unreadable bug.  After waiting for a while, node restarts the system automatically.

![image](https://github.com/kubevirt/kubevirt/assets/3785409/ded9bf29-9753-4dda-b6cf-83687d58e8dc)

**Environment**:

- KubeVirt version (use `virtctl version`):  0.58.0
- Kubernetes version (use `kubectl version`): 1.21.14

**Comment by victortoso** [comment]
Hi, would it be possible to collect the logs from virt-launcher pod? We need to see if libvirt or QEMU shows any information that we can work with. See this [debug session](https://kubevirt.io/user-guide/operations/debug/) of the user-guide.

> After waiting for a while, node restarts the system automatically.

Do you mean that the VM gets restarted or something else?
