### ISSUE TITLE
Virtual machine root directory expansion problem

### ISSUE THREAD

**Issue by am6737** [kubevirt/kubevirt#10045]
**Is your feature request related to a problem? Please describe**:
Virtual machines created using ceph-csi
Expansion of pvc virtual machine hard disk expansion
However, the root directory of the virtual machine is not expanded.
After restarting the virtual machine, the root directory was successfully expanded.

Was this deliberately designed this way?
```
[root@test-vm ~]# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
zram0  251:0    0  915M  0 disk [SWAP]
vda    252:0    0   10G  0 disk 
├─vda1 252:1    0    1M  0 part 
├─vda2 252:2    0 1000M  0 part /boot
├─vda3 252:3    0  100M  0 part /boot/efi
├─vda4 252:4    0    4M  0 part 
└─vda5 252:5    0  8.9G  0 part /home
                                /
vdb    252:16   0    1M  0 disk 
[root@test-vm ~]# [  208.986159] virtio_blk virtio3: [vda] new size: 41943040 512-byte logical blocks (21.5 GB/20.0 GiB)
[  208.988308] vda: detected capacity change from 20971520 to 41943040

[root@test-vm ~]# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
zram0  251:0    0  915M  0 disk [SWAP]
vda    252:0    0   20G  0 disk 
├─vda1 252:1    0    1M  0 part 
├─vda2 252:2    0 1000M  0 part /boot
├─vda3 252:3    0  100M  0 part /boot/efi
├─vda4 252:4    0    4M  0 part 
└─vda5 252:5    0  8.9G  0 part /home
                                /
vdb    252:16   0    1M  0 disk 
```
After the virtual machine is restarted
```
[root@test-vm ~]# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINTS
zram0  251:0    0  915M  0 disk [SWAP]
vda    252:0    0   20G  0 disk 
├─vda1 252:1    0    1M  0 part 
├─vda2 252:2    0 1000M  0 part /boot
├─vda3 252:3    0  100M  0 part /boot/efi
├─vda4 252:4    0    4M  0 part 
└─vda5 252:5    0 18.9G  0 part /home
                                /
vdb    252:16   0    1M  0 disk 
```
**Describe the solution you'd like**:
I hope that after the pvc expansion, the root directory will also be expanded without restarting the virtual machine.

**Describe alternatives you've considered**:

**Additional context**:

**Comment by alicefr** [comment]
@am6737 have you enabled the feature gate for disk expansion? If not please check [this guide](https://github.com/kubevirt/kubevirt/blob/main/docs/disk-expansion.md)

**Comment by am6737** [comment]
> @am6737 have you enabled the feature gate for disk expansion? If not please check [this guide](https://github.com/kubevirt/kubevirt/blob/main/docs/disk-expansion.md)

Yes, I enabled

**Comment by alicefr** [comment]
@am6737 which filesystem do you have on the root partition?

**Comment by alicefr** [comment]
@am6737 have you tried something like this: https://ahelpme.com/linux/online-resize-of-a-root-ext4-file-system-increase-the-space/

I don't think it is possible to resize automatically the filesystem too. Maybe by executing the qemu guest agent exec, but before I'd verify if it works manually.

**Comment by am6737** [comment]
> @am6737 have you tried something like this: https://ahelpme.com/linux/online-resize-of-a-root-ext4-file-system-increase-the-space/
> 
> I don't think it is possible to resize automatically the filesystem too. Maybe by executing the qemu guest agent exec, but before I'd verify if it works manually.

I have tried manually resizing the file system is feasible

**Comment by alicefr** [comment]
Is it good enough for you or would you like some automatic way of achieving it? I don't think there is something like this in KubeVirt yet.

**Comment by am6737** [comment]
> Is it good enough for you or would you like some automatic way of achieving it? I don't think there is something like this in KubeVirt yet.

Thank you for everything you 've done.

Is good enough for me now.

I realized that this was supposed to be my problem, not kubevirt.
