### ISSUE TITLE
Support control of memory guest overhead with InstanceTypes

### ISSUE THREAD

**Issue by mfranczy** [kubevirt/kubevirt#10057]
**Is your feature request related to a problem? Please describe**:
Currently it's not possible to control guest overhead with InstanceTypes.

**Describe the solution you'd like**:
I would like to add fields that allows me to set appropriate QoS class and control the guest overhead. It could be the same as `resources.limits.memory` and `resources.requests.memory` fields with appropriate validation against `memory.guest`.

**Describe alternatives you've considered**:
Currently I can control it by setting memory options directly in the VM spec but we want to use instance types.

**Additional context**:
Sometimes we cannot relay on the automatic calculation of memory guest overhead.
That's the same reasoning as described in here: https://github.com/kubevirt/kubevirt/pull/3162

**Comment by mfranczy** [comment]
@lyarwood what do you think about this?

**Comment by mfranczy** [comment]
From the PR https://github.com/kubevirt/kubevirt/pull/9799 description
>  The virt-launcher pod will request less physical memory by the OvercommitPercent.

@vladikr what about a use case where we need to request more memory for virt-launcher pod than VM?

**Comment by lyarwood** [comment]
/area instancetype

I'd prefer a standalone attribute instead of overloading `OvercommitPercent`, say a mutually exclusive `OverheadRatio` attribute so it maps to `AdditionalGuestMemoryOverheadRatio`?

https://github.com/kubevirt/kubevirt/blob/7c7d8ded67614efc7ca008cbe11102fa9305003c/staging/src/kubevirt.io/api/core/v1/types.go#L2326-L2332

**Comment by mfranczy** [comment]
> I'd prefer a standalone attribute instead of overloading OvercommitPercent

That makes sense.

> say a mutually exclusive OverheadRatio attribute so it maps to AdditionalGuestMemoryOverheadRatio

Sounds good, but `AdditionalGuestMemoryOverheadRatio` doesn't support values less than `1.0`. Meaning you cannot request more memory for pod than VM. Do you want to change this behaviour?

**Comment by mfranczy** [comment]
Please correct me if I am wrong, but my understanding is... If we would add `OverheadRatio then we would have:
* two ways of achieving guest memory overcommit with `OverheadRatio` and `OvercommitPercent`
* one way of achieving guest memory "undercommit" with `OverheadRatio` (and potentially change of `AdditionalGuestMemoryOverheadRatio` that it accepts values < 1.0)

wouldn't this API be a bit confusing?

**Comment by lyarwood** [comment]
> Please correct me if I am wrong, but my understanding is... If we would add `OverheadRatio` then we would have:
>
> * two ways of achieving guest memory overcommit with `OverheadRatio` and `OvercommitPercent`
> * one way of achieving guest memory "undercommit" with `OverheadRatio` (and potentially change of `AdditionalGuestMemoryOverheadRatio` that it accepts values < 1.0)
> 
> wouldn't this API be a bit confusing?

The naming is a little confusing but `AdditionalGuestMemoryOverheadRatio` actually adds memory to the overall pod resource request and not the memory visible to the guest itself. So values > `1.0` result in undercommit as we are now requesting more memory than visible to the guest.

https://github.com/kubevirt/kubevirt/blob/12321889014f2bd889c85995e4b3107b6348e569/pkg/virt-controller/services/template.go#L1350-L1359

https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-controller/services/renderresources.go#L384-L394

https://github.com/kubevirt/kubevirt/blob/12321889014f2bd889c85995e4b3107b6348e569/pkg/virt-controller/services/renderresources.go#L176-L189

> Additionally it would be good if we can over those settings support `Guaranteed` QoS class as well. The same as when you set `resources.memory.limits` equal to `resources.memory.requests` with `memory.guest` lower than the previous.

Yeah wrapping this stuff in policies would provide a nicer UX but I'd also provide users with the ability to tweak things directly to fit their use case.

**Comment by mfranczy** [comment]
> The naming is a little confusing but AdditionalGuestMemoryOverheadRatio actually adds memory to the overall pod resource request and not the memory visible to the guest itself. So values > 1.0 result in undercommit as we are now requesting more memory than visible to the guest.

Oh, my bad, thanks!

> Yeah wrapping this stuff in policies would provide a nicer UX but I'd also provide users with the ability to tweak things directly to fit their use case.

If we could do this that would be great.
