### ISSUE TITLE
`PreferredInterfaceMasquerade` applied to interfaces using `SRIOV` etc

### ISSUE THREAD

**Issue by lyarwood** [kubevirt/kubevirt#10053]
/area instancetype
/sig network

**What happened**:

Our `PreferredInterfaceMasquerade` application code is pretty crude at the moment:

https://github.com/kubevirt/kubevirt/blob/534bda181a078a90215763f849eb4eabcb8d8da2/pkg/instancetype/instancetype.go#L1223-L1225

We really need input from networking folks to ensure this is only applied when valid.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by oshoval** [comment]
Hi @lyarwood 
It looks fine, just missing few unit tests ? (e2e are missing as well, but unit tests are enough here imho)

This is the unit test we have
https://github.com/kubevirt/kubevirt/blob/e25174f3d21ad9202d534cba14bcd4eeb36ca9d6/pkg/instancetype/instancetype_test.go#L1505

and the interesting code is
https://github.com/kubevirt/kubevirt/pull/9761/files#diff-5e2591267ff7e9303f97ccac213986c2157131e3487a04a122b7662d401f7a57R1028-R1030
so can be nice to add a unit test where the condition isn't met, wdyt ?

General note: as this comment says
https://github.com/kubevirt/kubevirt/blob/e25174f3d21ad9202d534cba14bcd4eeb36ca9d6/pkg/instancetype/instancetype_test.go#L1367
it would have been nice to split the code into smaller tests.

Thanks

**Comment by AlonaKaplan** [comment]
@lyarwood you're right. The code [here](https://github.com/kubevirt/kubevirt/blob/534bda181a078a90215763f849eb4eabcb8d8da2/pkg/instancetype/instancetype.go#L1223-L1225) seems wrong.

The masquerade preferences should be applied only on the interface of the pod network and not on all the interfaces of the VM (we don't support masquerade on secondary interfaces). Similar condition can be found [here](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go#L310). 

Also, as you mentioned, before applying masquerade preferences it has to be checked that the interface has no another binding -
`vmiIface.Bridge == nil && vmiIface.Slirp == nil && vmiIface.SRIOV == nil && vmiIface.Macvtap == nil && vmiIface.Passt == nil`
