### ISSUE TITLE
ARM64 Support

### ISSUE THREAD

**Issue by liyang516** [kubevirt/kubevirt#10066]
Which official release or when can support the arm64 architecture?

**Comment by liyang516** [comment]
Release 1.0.0 support arm64？

**Comment by oshoval** [comment]
Hi @zhlhahaha 
Can you please advise ?
Thanks

**Comment by zhlhahaha** [comment]
Ok, @oshoval 
Hi, @liyang516, in release 1.0.0, we will provide multi-arch images (x86_64 and aarch64) and their corresponding binaries. This allows you to deploy KubeVirt on the Arm64 platform in the same way as deploying it on x86_64.

In terms of official releases, we are actively enabling additional end-to-end (e2e) tests on the Arm64 platform. Once these e2e tests run reliably on the Arm64 platform, we will officially declare support for KubeVirt on Arm64. You can track the progress of this process in the issue. https://github.com/kubevirt/kubevirt/issues/9756

**Comment by liyang516** [comment]
@zhlhahaha By the way，for [containerized-data-importer](https://github.com/kubevirt/containerized-data-importer)，when can support the arm64 architecture ，I mean offcifial release，not releasing nightlies.

**Comment by zhlhahaha** [comment]
> @zhlhahaha By the way，for [containerized-data-importer](https://github.com/kubevirt/containerized-data-importer)，when can support the arm64 architecture ，I mean offcifial release，not releasing nightlies.

I'm sorry, but at the moment, I don't have immediate plans to support it on the arm64 architecture. As a result, I'm unable to provide a definitive answer regarding its availability.

**Comment by liyang516** [comment]
> > @zhlhahaha By the way，for [containerized-data-importer](https://github.com/kubevirt/containerized-data-importer)，when can support the arm64 architecture ，I mean offcifial release，not releasing nightlies.
> 
> I'm sorry, but at the moment, I don't have immediate plans to support it on the arm64 architecture. As a result, I'm unable to provide a definitive answer regarding its availability.

tks
