### ISSUE TITLE
Kubevirt VM secondary interface goes down after DHCP lease expiry.

### ISSUE THREAD

**Issue by keepthemomentum** [kubevirt/kubevirt#10062]
Hello

I have been struggling to find a solution for my problem with running kubevirt VM, any help would be much appreciated.
I'm running kubevirt virtual machines and my goal is to add secondary interfaces to the VM's so that it gets the IP address from DHCP server. I have a bridge interface configured and I'm using OVS. VM gets the secondary interface and gets the IP from DHCP, but after the lease expiry the secondary interface stops responding and cannot reach the DHCP server. ARP table entry in the DHCP server shows "incomplete". I even tried static mapping on the interface, but it doesn't work. 
What do i need to do if i want to have:
1. Static mapping on the secondary interface ( i can map the IP and MAC address in my DHCP server). Do i need to use my Virtual machines MAC on the secondary interface? OR
2. Have a new IP address assigned to my interface after the lease expiry. 

Here is my configuration:
Network-attachment:

> apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: ovs-cni.network.kubevirt.io/br1
  creationTimestamp: "2023-06-01T14:51:43Z"
  generation: 1
  name: ovs-dhcp
  namespace: default
  resourceVersion: "4644734"
  uid: 00e5956b-69a2-43c1-9494-e99a8a42698c
spec:
  config: '{ "cniVersion": "0.3.1", "type": "ovs", "bridge": "br1", "ipam": { "type":
    "dhcp" } }'

My VM template:

> kind: VirtualMachine
metadata:
  name: vm1
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: vm1
    spec:
      nodeSelector:
        disktype: ssd1
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: ovs-dhcp
            bridge: {}
          - name: default
            bridge: {}    
        resources:
          requests:
            memory: 2G
      networks:
      - multus:
          networkName: ovs-dhcp
        name: ovs-dhcp
      - name: default
        pod: {}    
      volumes:
        - name: containerdisk
          containerDisk:
            image: tedezed/kubevirt:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              chpasswd:
                list: |
                expire: False
              bootcmd:
                - dhclient enp2s0`

With this configuration, I can run the VM and both the interface IP's are reachable. But, DHCP interface goes down after the lease expiry. I cannot get a new IP when i use 'dhclient', i still get the same IP. I'm using calico as my default CNI and multus for secondary interface. What's wrong with my configuration?

> 1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
2: enp1s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether 0a:58:c0:a8:0a:94 brd ff:ff:ff:ff:ff:ff
    inet 192.168.10.148/24 brd 192.168.10.255 scope global noprefixroute enp1s0
       valid_lft forever preferred_lft forever
    inet6 fe80::858:c0ff:fea8:a94/64 scope link 
       valid_lft forever preferred_lft forever
3: enp2s0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1480 qdisc fq_codel state UP group default qlen 1000
    link/ether e2:78:8a:35:7d:f5 brd ff:ff:ff:ff:ff:ff
    inet 10.46.210.231/32 brd 10.46.210.231 scope global dynamic enp2s0
       valid_lft 86312349sec preferred_lft 86312349sec

**Comment by AlonaKaplan** [comment]
hi @keepthemomentum, with `"ipam": { "type":"dhcp" } }` on the NAD, the VM will always get the same IP (the first given IP). What happens in bridge binding is that we run an internal DHCP server that always gives the guest the first IP that was assigned by the  IPAM. The ovs cni DHCP server is not relevant after the first IP it gives.

If you want an external DHCP server to control the secondary interface IP, you shouldn't use IPAM.

**Comment by keepthemomentum** [comment]
@AlonaKaplan Thank you for your response. Do i need to have my NAD something like this?


   {
  "cniVersion": "0.3.1",
  "name": "dhcp",
  "type": "bridge",
  "bridge": "br1",
  "ipam": {}
}

**Comment by AlonaKaplan** [comment]
I think you can omit the ipam.

{
"cniVersion": "0.3.1",
"name": "dhcp",
"type": "bridge",
"bridge": "br1",
}

**Comment by keepthemomentum** [comment]
Thanks @AlonaKaplan 
I will bridge the interfaces without using "OVS" CNI, omit the IPAM configuration and check. I will update soon with my results.

**Comment by EdDev** [comment]
Due to no further activity on this issue, we are closing it.

Please open a new one if needed.

/close
