### ISSUE TITLE
VM Livemigration failed on beegfs ReadWriteMany  volumn

### ISSUE THREAD

**Issue by xhw2008888** [kubevirt/kubevirt#10094]
**What happened**:
vm can not migrated on beegfs volume

**What you expected to happen**:
I attach a beegfs pv with the vm. The beegfs pv is createed from an readwritemany sc. After I migrate the vm by virtctl cli ,there is no error. After a few seconds, i get the kubeclt event error as below 
"VirtualMachineInstance migration uid 8e772457-f6e8-4e62-b465-844a6d8727a0 failed. reason:Live migration failed error encountered during MigrateToURI3 libvirt api call: virError(Code=81, Domain=10, Message='Unsafe migration: Migration without shared storage is unsafe' "

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.
1.create pvc  csi-beegfs-dyn-pvc

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: csi-beegfs-dyn-pvc
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: csi-beegfs-dyn-sc

2.attach the pv to a vm

apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: win11
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: win11
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - bootOrder: 2
            cdrom:
              bus: sata
            name: cdromiso
          - bootOrder: 1
            disk:
              bus: virtio
            name: harddrive
          - cdrom:
              bus: sata
            name: virtiocontainerdisk
          interfaces:
          - name: default
            model: e1000
            masquerade: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 16G
      networks:
      - name: default
        pod: {}
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: iso-win11
      - name: harddrive
        persistentVolumeClaim:
          claimName: csi-beegfs-dyn-pvc
      - containerDisk:
          image: kubevirt/virtio-container-disk
        name: virtiocontainerdisk
~                                   

3. start the vm
virtctl start win11
4.  install windows with vnc, edit and delte iso in win11 vm .
5. migrate the windows vm.
virtctl migrate win11
linux consonle report hint:
VM win11 was scheduled to migrate
6. After a few seconds, i get the kubeclt event error as below 
"VirtualMachineInstance migration uid 8e772457-f6e8-4e62-b465-844a6d8727a0 failed. reason:Live migration failed error encountered during MigrateToURI3 libvirt api call: virError(Code=81, Domain=10, Message='Unsafe migration: Migration without shared storage is unsafe' "

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A server v0.58.0,client v0.48.1
- Kubernetes version (use `kubectl version`): v1.23.10
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by simonyangcj** [comment]
IIRC this is a libvirt issue looks like beegfs is not marked as a safe shared storage in libvirt. Kubevirt live migration feature is base on it. 

```
# src/qemu/qemu_migration.c
enum {
    VIR_FILE_SHFS_NFS = (1 << 0),
    VIR_FILE_SHFS_GFS2 = (1 << 1), /* Global File System 2 */
    VIR_FILE_SHFS_OCFS = (1 << 2), /* Oracle Cluster FS (2) */
    VIR_FILE_SHFS_AFS = (1 << 3), /* Andrew File System */
    VIR_FILE_SHFS_SMB = (1 << 4), /* Server message block - windows shares */
    VIR_FILE_SHFS_CIFS = (1 << 5), /* Common Internet File System - windows shares */
    VIR_FILE_SHFS_CEPH = (1 << 6),
    VIR_FILE_SHFS_GPFS = (1 << 7), /* General Parallel File System/IBM Spectrum Scale */
    VIR_FILE_SHFS_QB = (1 << 8), /* Quobyte shared filesystem */
    VIR_FILE_SHFS_ACFS = (1 << 9), /* Oracle ASM Cluster File System */
    VIR_FILE_SHFS_GLUSTERFS = (1 << 10), /* gluster's FUSE-based client */
};
```

**Comment by victortoso** [comment]
I think @simonyangcj is correct. Looking at a similar bug [rhbz#1665553](https://bugzilla.redhat.com/show_bug.cgi?id=1665553), but with ceph storage and the [proposed solution](https://listman.redhat.com/archives/libvir-list/2019-January/msg01008.html), it seems like we need libvirt support for this.

@xhw2008888 would you mind opening an issue in [libvirt](https://gitlab.com/libvirt/libvirt/-/issues) tracker and follow up from there?

**Comment by xhw2008888** [comment]
@victortoso @simonyangcj  Thank you very much for support. I've opened an issure in libvirt tracker as link [#508](https://gitlab.com/libvirt/libvirt/-/issues/508)

**Comment by victortoso** [comment]
Amazed by the fact you opened the issue this morning and it is [already solved,](https://gitlab.com/libvirt/libvirt/-/commit/658660681cde6fc9881220990ffc9504da92c194) one day prior to the [libvirt 9.6.0 freeze](https://listman.redhat.com/archives/libvir-list/2023-July/240899.html) :)

So, there you go. If all is good, when kubevirt fetches libvirt 9.6.0 or higher, migration with beegfs should work.

**Comment by xhw2008888** [comment]
@victortoso I just update libvirt 9.6 version on rhel os. The kubevirt vm can not be migrated on beegfs volume still.
[root@node10 ~]# virtctl migrate win10
VM win10 was scheduled to migrate
 [root@node10 ~]# kubectl get vmi -o wide
NAME    AGE     PHASE     IP               NODENAME   READY   LIVE-MIGRATABLE   PAUSED
win10   3m57s   Running   10.244.222.140   node11     True    True              
 [root@node10 ~]# libvirtd -V
libvirtd (libvirt) 9.6.0
Though I can sent the virtctl with migration commad, the vm is alway on the same node on which is started. 
the error as below 
[root@node10 ~]# kubectl describe vmi win10
-------
VirtualMachineInstance migration uid 3335e350-7bc9-406c-8967-6d2cee6b682e failed. reason:Live migration failed error encountered during MigrateToURI3 libvirt api call: virError(Code=81, Domain=10, Message='Unsafe migration: Migration without shared storage is unsafe')

**Comment by xpivarc** [comment]
Hi @xhw2008888 , just to be sure, the libvirt needs to be updated in Kubevirt.

**Comment by xhw2008888** [comment]
@xpivarc how can I update libvirt in kubevir. could you please give me  the upgrade guideline with command line and operation step.
thank you.

**Comment by victortoso** [comment]
```bash
toso@tapioca ~/s/libvirt (master)> git tag --contains 658660681cde6fc9881220990ffc9504da92c194
v9.6.0
v9.6.0-rc1
v9.6.0-rc2
```

Just confirming that the commit is indeed in 9.6.0.

> @xpivarc how can I update libvirt in kubevirt. could you please give me the upgrade guideline with command line and operation step.
> thank you.

The [custom-rpm](https://github.com/kubevirt/kubevirt/blob/main/docs/custom-rpms.md) doc explains it. Note that there is ongoing work to update libvirt with https://github.com/kubevirt/kubevirt/pull/10050 but I'm not sure we will get 9.6.0 with it as we rely on centos stream 9 rpm updates and there was no build for libvirt 9.6.0 yet
