### ISSUE TITLE
Introduce a linter to disallow ginkgo `FDescribe`, `FIt`, `FContext`, etc.

### ISSUE THREAD

**Issue by iholder101** [kubevirt/kubevirt#10120]
**Is your feature request related to a problem? Please describe**:
While developing locally, it's usually valuable to change ginkgo's `It`, `Context`, `Describe` to `FIt`, `FContext`, `FDescribe`, etc. This addition is being used to focus on certain function tests when running the test suite locally.

However, sometimes developers forget to remove the `F` prefix before submitting a PR. This can be discovered during the code-review process (as happened here: https://github.com/kubevirt/kubevirt/pull/10099#discussion_r1263159334), or even worse - the PR can get merged demanding another fix PR to remove the prefix.

**Describe the solution you'd like**:
I'd like to see a linter that would run as a gating presubmit lane on every PR, that would fail such PRs from getting merged.
Possibly the best way to implement such a linter is via `nogo`.

**Describe alternatives you've considered**:
Open to hear if they exist :)

/label good-first-issue

**Comment by nunnatsa** [comment]
@iholder101 - I'm not 100% sure about it. I want to hear additional opinions: https://gophers.slack.com/archives/CQQ50BBNW/p1689585404975049

**Comment by nunnatsa** [comment]
Also, please open the issue here: https://github.com/nunnatsa/ginkgolinter

**Comment by nunnatsa** [comment]
If someone can take a look at the fix, it would be great: https://github.com/nunnatsa/ginkgolinter/pull/97
@lyarwood @iholder101

**Comment by nunnatsa** [comment]
ginkgolinter v0.13.0 was released with this new rule. 

@lyarwood @iholder101 - you can now bump ginkgolinter version to adopt it.

**Comment by lyarwood** [comment]
```
$ cd src/k8s/kubevirt/kubevirt && go get github.com/nunnatsa/ginkgolinter@v0.13.0
go: upgraded github.com/nunnatsa/ginkgolinter v0.12.0 => v0.13.0
go: upgraded golang.org/x/crypto v0.1.0 => v0.11.0
go: upgraded golang.org/x/mod v0.10.0 => v0.12.0
go: upgraded golang.org/x/net v0.9.0 => v0.12.0
go: upgraded golang.org/x/sync v0.1.0 => v0.3.0
go: upgraded golang.org/x/sys v0.7.0 => v0.10.0
go: upgraded golang.org/x/term v0.7.0 => v0.10.0
go: upgraded golang.org/x/text v0.9.0 => v0.11.0
go: upgraded golang.org/x/tools v0.8.0 => v0.11.0
go: downgraded kubevirt.io/containerized-data-importer v1.56.0 => v1.21.0
```

Okay that's a first for me, no idea why it's downgrading CDI?

**Comment by nunnatsa** [comment]
@oshoval - we prefer to fail fast. I'm not sure about the failure in runtime, but even if we get it, I think it's better to get it on build time. Anyway, it's already implemented in the linter - let's just use it

**Comment by oshoval** [comment]
> @oshoval - we prefer to fail fast. I'm not sure about the failure in runtime, but even if we get it, I think it's better to get it on build time. Anyway, it's already implemented in the linter - let's just use it

the job itself should not fail fast because a developer might want to run few tests on a specific lane
the linter job can fail fast for it, but it seems a bit redundant imho, however it is more explicit indeed

**Comment by lyarwood** [comment]
> > @oshoval - we prefer to fail fast. I'm not sure about the failure in runtime, but even if we get it, I think it's better to get it on build time. Anyway, it's already implemented in the linter - let's just use it
> 
> the job itself should not fail fast because a developer might want to run few tests on a specific lane the linter job can fail fast for it, but it seems a bit redundant imho, however it is more explicit indeed

Note that devs can still workaround this by using the `// ginkgo-linter:ignore-focus-container-warning` comment so it's still possible in CI etc.

**Comment by lyarwood** [comment]
Apologies if this is just my sleep deprived new parent brain getting in the way here but I'm stuck trying to pull this version in:

```
$ git rev-parse HEAD
be23dc09cb8cb7759047f1076318ecb2d0d2de97
$ go version
go version go1.19.10 linux/amd64
$ go get github.com/nunnatsa/ginkgolinter@v0.13.0 && go mod tidy
go: upgraded github.com/nunnatsa/ginkgolinter v0.12.0 => v0.13.0
go: upgraded golang.org/x/crypto v0.1.0 => v0.11.0
go: upgraded golang.org/x/mod v0.10.0 => v0.12.0
go: upgraded golang.org/x/net v0.9.0 => v0.12.0
go: upgraded golang.org/x/sync v0.1.0 => v0.3.0
go: upgraded golang.org/x/sys v0.7.0 => v0.10.0
go: upgraded golang.org/x/term v0.7.0 => v0.10.0
go: upgraded golang.org/x/text v0.9.0 => v0.11.0
go: upgraded golang.org/x/tools v0.8.0 => v0.11.0
go: downgraded kubevirt.io/containerized-data-importer v1.56.0 => v1.21.0
```

Even if I manually correct CDI back to `v1.56.0` I then get the following diff stats when I attempt to `vendor`:

```
$ nvim go.mod
[..]
$ go mod tidy && go mod vendor
$ git diff --stat | tail -n1
 942 files changed, 5475 insertions(+), 26105 deletions(-)
```

Weirdly it's mostly `BUILD.bazel` removal?!

```
$ git diff | grep ^diff.*BUILD.bazel | wc -l
837
```

Again apologies in advance if this is PEBKAC.

Also and likely more importantly, doesn't this change now block devs from adding the focus context during local functional test runs without the above comment? I had missed this before and it might block the use of this rule at build time tbh. It's still something I could use in `pre-commit` however so it's not a wasted effort.

**Comment by 0xFelix** [comment]
I'd suggest running `make deps-sync` instead of running `go mod tidy` and `go mod vendor` manually. Can you try it?

**Comment by lyarwood** [comment]
> I'd suggest running `make deps-sync` instead of running `go mod tidy` and `go mod vendor` manually. Can you try it?

Yup thanks, not sure how I missed the script/target for this, it's working.

**Comment by nunnatsa** [comment]
Hi.

So we do have a problem here. If someone want to locally run the tests using bazel, it is legit to use focused containers.

But now we won't support this option anymore. Running unit tests using `go test` will still work, I think.

So I suggest to change the linter configurations in nogo_config.json, to:
```json
  "ginkgolinter": {
    "exclude_files": {
      "vendor/": "vendor doesn't pass vet",
      "external/": "externaldoesn't pass vet"
    },
    "analyzer_flags": {
      "suppress-focus-container": "true"
    }
```

This will actually cancel the whole thing, unfortunately. It will still work in the pre-commit, though.

Do we have another gate we can set? e.g. running golangci-lint in ci?

**Comment by lyarwood** [comment]
> Hi.
> 
> So we do have a problem here. If someone want to locally run the tests using bazel, it is legit to use focused containers.
> 
> But now we won't support this option anymore. Running unit tests using `go test` will still work, I think.
> 
> So I suggest to change the linter configurations in nogo_config.json, to:
> 
> ```json
>   "ginkgolinter": {
>     "exclude_files": {
>       "vendor/": "vendor doesn't pass vet",
>       "external/": "externaldoesn't pass vet"
>     },
>     "analyzer_flags": {
>       "suppress-focus-container": "true"
>     }
> ```
> 
> This will actually cancel the whole thing, unfortunately. It will still work in the pre-commit, though.

ACK as I said above this isn't ideal but it does make the case for pre-commit.

> Do we have another gate we can set? e.g. running golangci-lint in ci?

I think so, even if only to catch focused containers that sneak into commits when devs haven't opted into using pre-commit.

Anyway I posted the `ginkgolinter` bump, even if it doesn't actually introduce any new functionality now. Reviews welcome.

https://github.com/kubevirt/kubevirt/pull/10136
