### ISSUE TITLE
The Disk tagged can't been seen in Config Drive meta.

### ISSUE THREAD

**Issue by ninelinesevduk** [kubevirt/kubevirt#10129]
In My VM.yaml, I tag both disk and interface. And I'm using a cloudInitConfigDrive volume:

![2](https://github.com/kubevirt/kubevirt/assets/3922582/bff07853-6d91-4f0b-afed-4dbc0abfbb77)

Once the virtual machine is started, log in the virtual machine, and mount the disk corresponding to cloudInitConfigDrive (e.g., /dev/vdb) to the ~/conf directory. Then, execute '**cat ~/conf/openstack/latest/meta_data.json**', I can see the interface been tagged, but I can't see the disk been tagged:

![1](https://github.com/kubevirt/kubevirt/assets/3922582/693e9dc0-915f-4201-952d-b6b35358f854)

What's going on here? Any help is valuable.

**Comment by lyarwood** [comment]
/cc @vladikr 
/kind feature

@vladikr when you're back correct me if I'm wrong here but there's no support for disk device role tagging at present right? Only interfaces, host devices and GPUs are currently supported [1][2]. 

[1] https://kubevirt.io/user-guide/virtual_machines/startup_scripts/#device-role-tagging
[2] https://github.com/kubevirt/kubevirt/blob/773d083bc9b095e4f462c1ce96d8239a994fa37d/pkg/virt-launcher/virtwrap/manager.go#L1825-L1917

**Comment by EdDev** [comment]
@lyarwood , the API claims it is supported: https://github.com/kubevirt/kubevirt/blob/99422cce91311e2c71171a00497e9c3ac9f967a3/staging/src/kubevirt.io/api/core/v1/schema.go#L611
