### ISSUE TITLE
Arm Machine Types for QEMU Kubevirt

### ISSUE THREAD

**Issue by Kronusus** [kubevirt/kubevirt#10159]
Hi,

kubevirt seems like an amazing plattform. So thanks for developing it!

But for my use case, there seems to be one feature missing. So any help/guidance/development would be much appreciated. 

**Is your feature request related to a problem? Please describe**:
Kubevirt is based on QEMU which can emulate a wide range of platforms (e.g. lots of embedded arm systems) independent of the host system (meaning running for example an embedded ARM system on a normal X86 system)

However, according to the Kubevirt documentation, today kubvirt only allows to deploy and orchestrate qemu VMs that emulate X86 machine types.

see https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/

**Describe the solution you'd like**:
It would be awesome to be able to use the full emulation scope of qemu when creating a VM.

**Additional context**:
see for example this link for the wide range of possible arm plattforms in qemu
https://wiki.qemu.org/Documentation/Platforms/ARM

**Comment by zhlhahaha** [comment]
Hi, thanks for using KubeVirt. Your suggestion is good, but for now, we only support limited machine types of Arm64. You can get all supported machine types by entering `virt-launcher` pod and run following command.
```
bash-5.1# /usr/libexec/qemu-kvm --M help
Supported machines are:
virt                 RHEL 9.2.0 ARM Virtual Machine (alias of virt-rhel9.2.0)
virt-rhel9.2.0       RHEL 9.2.0 ARM Virtual Machine (default)
virt-rhel9.0.0       RHEL 9.0.0 ARM Virtual Machine
none                 empty machine
```
The qemu-kvm binary comes from rpm package in `http://mirror.stream.centos.org/9-stream/AppStream/aarch64/os/Packages/`. 
But there is a quick bypass for the issue. If you want to have a wilder supported Machine type, you can change the qemu-kvm related binary source in `WORKSPACE` (for example, change the qemu-kvm package source to fedora repository, which provide a wilder machine type), and then build virt-launcher by yourself.

In terms of 32bit Arm system, it may not works on KubeVirt. As the 32bit VM configuration is quit different with 64bit VM configuration, which means the default VM configuration of KubeVirt may not compatible with 32bit VM. There is no quick fix or bypass for this issue, unless you can modify the source code of KubeVirt.

**Comment by Kronusus** [comment]
ah okay that sounds intresting. I will try it as soon as possible. Thanks!
