### ISSUE TITLE
Many cpuset related functions and definitions could be replaced with `k8s.io/utils/cpuset` package

### ISSUE THREAD

**Issue by VirrageS** [kubevirt/kubevirt#10170]
**Is your feature request related to a problem? Please describe**:
Currently to parse cpuset files (with format http://man7.org/linux/man-pages/man7/cpuset.7.html#FORMATS) we use https://github.com/kubevirt/kubevirt/blob/v1.0.0/pkg/util/hardware/hw_utils.go#L42-L73. Exactly the same functionally can be achieved by using https://pkg.go.dev/k8s.io/utils/cpuset#Parse function. This also returns a struct `CPUSet` which we could use to easily manipulate and check various things, right now we pass list of ints (`[]int`).

**Describe the solution you'd like**:
Make use of `k8s.io/utils/cpuset` in places where we manipulate and do things with cpusets/cpulists.

**Additional context**:
https://github.com/kubernetes/utils/pull/267 started to live as separate package in `k8s.io/utils` as it was taken out from `k8s.io/kubernetes/.../kubevirt/.../cpuset`.

**Comment by xpivarc** [comment]
What would be the expected outcome?

**Comment by VirrageS** [comment]
As described, ideally we should rely on the package provided by the k8s.io/utils instead of having the code that does similar thing. Less code to test and maintain 😄.
