### ISSUE TITLE
Leftover mount point from PersistentReservation

### ISSUE THREAD

**Issue by vasiliy-ul** [kubevirt/kubevirt#10172]
**What happened**:
After enabling `PersistentReservation` feature gate, a tmpfs mount point appears on the nodes:
```bash
$ mount | grep daemon
tmpfs on /run/kubevirt/daemons/pr type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
```
It does not disappear if the feature gate is disabled. Also, if `PersistentReservation` is re-enabled once more, multiple mounts are added (and never cleaned-up). 

**What you expected to happen**:
All the resources should be properly cleaned up.

**How to reproduce it (as minimally and precisely as possible)**:
```bash
$ make cluster-up && make cluster-sync
$ ./cluster-up/ssh.sh node01
[vagrant@node01 ~]$ mount | grep daemon # no mounts on the clean install
[vagrant@node01 ~]$ exit
# enable `PersistentReservation` feature gate and wait for re-deployment of KubeVirt
$ kubectl patch -n kubevirt kv kubevirt --type merge -p '{"spec": {"configuration": {"developerConfiguration": {"featureGates": ["PersistentReservation"]}}}}'
$ kubectl -n kubevirt wait kv kubevirt --timeout=100h --for condition=Available
$ ./cluster-up/ssh.sh node01
[vagrant@node01 ~]$ mount | grep daemon # one tmpfs mount appears
tmpfs on /run/kubevirt/daemons/pr type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
[vagrant@node01 ~]$ exit
# disable `PersistentReservation` feature gate and wait for re-deployment of KubeVirt
$ kubectl patch -n kubevirt kv kubevirt --type merge -p '{"spec": {"configuration": {"developerConfiguration": {"featureGates": [""]}}}}'
$ kubectl -n kubevirt wait kv kubevirt --timeout=100h --for condition=Available
$ ./cluster-up/ssh.sh node01
[vagrant@node01 ~]$ mount | grep daemon # the mount is still there
tmpfs on /run/kubevirt/daemons/pr type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
[vagrant@node01 ~]$ exit
# re-enable `PersistentReservation` feature gate and wait for re-deployment of KubeVirt
$ kubectl patch -n kubevirt kv kubevirt --type merge -p '{"spec": {"configuration": {"developerConfiguration": {"featureGates": ["PersistentReservation"]}}}}'
$ kubectl -n kubevirt wait kv kubevirt --timeout=100h --for condition=Available
$ ./cluster-up/ssh.sh node01
[vagrant@node01 ~]$ mount | grep daemon # now several more tmpfs mounts appear
tmpfs on /run/kubevirt/daemons/pr type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
tmpfs on /run/kubevirt/daemons/pr type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
tmpfs on /run/kubevirt/daemons/pr type tmpfs (rw,nosuid,nodev,seclabel,mode=755)
```

**Additional context**:
I tried to debug the problem and have a few findings:
1. The `pr-helper` container does not terminate properly. It errors out with a message:
    ```
    $ k logs -n kubevirt virt-handler-jrtlw -c pr-helper -f
    qemu-pr-helper: Failed to unlink socket /var/run/kubevirt/daemons/pr/pr-helper.sock: Permission denied
    ```
    This happens because we now set the ownership of the `/var/run/kubevirt/daemons/pr` directory to `107:107` while the container is run under a non-root default user `1001` (which does not have write permissions to that directory). It's weird, but somehow `qemu-pr-helper -k /var/run/kubevirt/daemons/pr/pr-helper.sock` manages to create the socket but fails to delete it (I would assume here that the daemon itself can drop some of the capabilities after initialization, thus the deletion would fail). Initially I thought that was the reason of the leftover mount point, but fixing that did not solve the issues. The fix is just to add `runAsUser: 107` to the `pr-helper` container definition.

2. I tried to make a smaller reproducer with a simple pod, but that does not cause tmpfs mount to appear. So I am not sure where it actually comes from and who/what creates it.

**Environment**:
- KubeVirt version (use `virtctl version`): v1.0.0 and also the main branch
- Kubernetes version (use `kubectl version`): 1.25 (`make cluster-up`)
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by vasiliy-ul** [comment]
I am still looking into that issue, but maybe someone has ideas on where exactly the problem might be.

/cc @alicefr

**Comment by vasiliy-ul** [comment]
Sharing some more findings. I've managed to reproduce the issue by creating/deleting the simple pod:

<details>
<summary>test.yaml</summary>

```yaml
apiVersion: v1
kind: Pod
metadata:
  name: test
spec:
  containers:
  - args:
    - infinity
    command:
    - sleep
    image: busybox
    imagePullPolicy: IfNotPresent
    name: test
    securityContext:
      privileged: true
      seLinuxOptions:
        level: s0
    volumeMounts:
    - mountPath: /var/run/kubevirt
      mountPropagation: Bidirectional
      name: virt-share-dir
    - mountPath: /var/run/kubevirt/daemons/dbgpr
      mountPropagation: Bidirectional
      name: dbgvol
  terminationGracePeriodSeconds: 1
  volumes:
  - hostPath:
      path: /var/run/kubevirt
      type: ""
    name: virt-share-dir
  - hostPath:
      path: /var/run/kubevirt/daemons/dbgpr
      type: ""
    name: dbgvol
```

</details>

It turns out that having two host path volumes originating at the same root (e.g. `/var/run/kubevirt` and `/var/run/kubevirt/daemons/pr`) in a pod and bind-mounted with **bidirectional** propagation to containers leads to side effects. That creates additional mount points on the host that are not cleaned up afterward. Not sure, I fully understand the root cause why it happens. Though I think it can be fixed. I will raise a PR shortly.

**Comment by alicefr** [comment]
@vasiliy-ul just returned from vacation. I'll have a look to this asap
