### ISSUE TITLE
Create version resource for virt-api

### ISSUE THREAD

**Issue by SchSeba** [kubevirt/kubevirt#1018]
Continued the follow issue [Add virtcl version command #891](https://github.com/kubevirt/kubevirt/issues/891) I am creating this issue to track the server side.

For the virtctl version command we need to add ldflags on virt-api build, and add the follow struct.

```
type Info struct {
	Major        string `json:"major"`
	Minor        string `json:"minor"`
	GitVersion   string `json:"gitVersion"`
	GitCommit    string `json:"gitCommit"`
	GitTreeState string `json:"gitTreeState"`
	BuildDate    string `json:"buildDate"`
	GoVersion    string `json:"goVersion"`
	Compiler     string `json:"compiler"`
	Platform     string `json:"platform"`
}
```

The second thing we need is to create a new sub resource name version that return this struct to the client.

**Comment by rmohr** [comment]
@SchSeba great that you start working on that. Is there a reason to track the "virtctl version" command separately?

**Comment by rmohr** [comment]
@SchSeba you can add them in `hack/build-go.sh`. There we iterate over all binaries to build. That should be the right location to add the ldflags.

**Comment by SchSeba** [comment]
Can We close this issue? 
The feature was merged  :)
[Pull 1025](https://github.com/kubevirt/kubevirt/pull/1025)
