### ISSUE TITLE
vm failed to run with clientPassthrough on arm64

### ISSUE THREAD

**Issue by ydcool** [kubevirt/kubevirt#10200]
**What happened**:
VM run failed with `clientPassthrough` enabled on arm64.

**What you expected to happen**:
VM run with clientPassthrough enabled.

**How to reproduce it (as minimally and precisely as possible)**:

Create vm with clientPassthrough enabled on arm64 cluster.

**Additional context**:

error logs in virt-launcher:

```
{"component":"virt-launcher","level":"error","msg":"unsupported configuration: USB redirection is not supported by this version of QEMU","pos":"qemuValidateDomainRedirdevDef:2331","subcomponent":"libvirt","thread":"30","timestamp":"2023-07-31T11:46:26.705000Z"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Defining the VirtualMachineInstance failed.","name":"vm-8m2af3si","namespace":"cnp-system","pos":"libvirt_helper.go:136","reason":"virError(Code=67, Domain=10, Message='unsupported configuration: USB redirection is not supported by this version of QEMU')","timestamp":"2023-07-31T11:46:26.705866Z","uid":"28dc82c3-8f50-4cf7-ae0a-4764b4308c1d"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"vm-8m2af3si","namespace":"cnp-system","pos":"server.go:202","reason":"virError(Code=67, Domain=10, Message='unsupported configuration: USB redirection is not supported by this version of QEMU')","timestamp":"2023-07-31T11:46:26.705960Z","uid":"28dc82c3-8f50-4cf7-ae0a-4764b4308c1d"}
```

**Environment**:
- KubeVirt version (use `virtctl version`): v1.0.0
- Kubernetes version (use `kubectl version`): v1.25.4
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): `Linux hci01 4.19.90-25.9.v2101.ky10.aarch64 #1 SMP Wed Dec 1 17:24:28 CST 2021 aarch64 aarch64 aarch64 GNU/Linux`
- Install tools: N/A
- Others: N/A

**Comment by victortoso** [comment]
Hi, happy to know you are interested in this feature. The problem you are facing is related to the lack of `qemu-kvm-device-usb-redirect` rpm for arm. You can see it exists in [x86_64](https://mirror.stream.centos.org/9-stream/AppStream/x86_64/os/Packages/) but not in [aarch64](https://mirror.stream.centos.org/9-stream/AppStream/aarch64/os/Packages/). This rpm is the usbredir driver for QEMU to handle usbredir protocol.

Another alternative in the works is the USB host pass through in https://github.com/kubevirt/kubevirt/pull/10015, with the use case where USB devices are plugged into the Nodes. This one will work on aarch64. Would that be sufficient for you?

**Comment by ydcool** [comment]
Thanks for your quick response. The USB host pass through is great. I look forward to trying it out soon.

**Comment by zhlhahaha** [comment]
Hi, @ydcool 

Just as @victortoso , we do not have the `qemu-kvm-device-usb-redirect` rpm for Arm64, which lead to this issue. The root cause is that the rpm package is missing in the repository https://mirror.stream.centos.org/9-stream/AppStream/aarch64/os/Packages/. I will create an issue on this. Thanks for reporting.
