### ISSUE TITLE
KubeVirt Application readiness and health checks

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1023]
KubeVirt is growing and requires more features and specific configurations in order to work correctly.

Some requirements are soft (i.e. block storage) others are mandatory (i.e. correct security context).

It would be good to have a component to signal me - as an operator - if kubevirt was operating correctly, or if there there is a configuration item which is incorrect or could be set to a better value.

A probably incomplete list of items which can be checked:

## P1
- Cluster level
  - [ ] Check for minimum Kubernetes version
  - [ ] Check for required and not opened feature gates
  - [ ] Check for raw block
  - [ ] Check for CDI availability if DataVolume is enabled
  - [ ] Warn if emulation mode is configured (or any dbug item)
  - [ ] Check that a minimum number of nodes is available (i.e. 2) to have some sanity check that migration will work
- Node level
  - [ ] Check for kmods (char-major-10-200 #1205) on nodes (check nfd labels?)
  - [ ] Soft check nested virt is enabled

## P2
- [ ] Check for relevant features (initializers, …)
- [ ] Check for relevant permissions/roles
- [ ] Check for req webhook admission controller / validating webhook registration
- [ ] check for correct security contexts
- [ ] check for correct service accounts
- [ ] preset presence ?
- [ ] Check that aggregated api registration happened
- [ ] Check for host tuned configuratrtion (long term should go to tempaltes)

Based on these checks, the component can also provide a list of supported features.

**Comment by fabiand** [comment]
@rmohr @davidvossel we should add a list of features that need to be checked.

**Comment by fromanirh** [comment]
@fabiand I volunteered for the now-closed #964 before to get my current assignments. I Will re-evaluate the resources I have to work on this in the current sprint and report ASAP.

**Comment by davidvossel** [comment]
> we should add a list of features that need to be checked.

nested virt is enabled, aggregated api registration, validating webhook registration

those are the only ones that come to mind immediately

**Comment by fabiand** [comment]
@fromanirh ack - #964 was the same as this here, thus I hope it's not stopping you from looking at it :)

**Comment by fabiand** [comment]
https://docs.okd.io/latest/admin_guide/diagnostics_tool.html is somewhat related

**Comment by MarSik** [comment]
@davidvossel I am just curious, why would you require nested virt? No commercial distro actually supports that and it is known to have bugs and limitations on other than intel platforms.

**Comment by fabiand** [comment]
Nested could be a recommendation if we detect to run on a hypervisor.

**Comment by MarSik** [comment]
@fabiand That sentence of yours does not make any sense.. you do not need nested for bare metal hypervisor and you already know you have nested when you find yourself in a VM with virtualization enabled. I really seem to be missing something here.

Nested is useful for CI, development and all that.. but production servers can crash when something goes wrong inside a nested VM. That is why nobody officially supports that even though it might work just fine.

**Comment by lkpdn** [comment]
Hi,

is there any concrete plan for this? As this labeled "help wanted", I want to see if I can volunteer or not.
What I come up with is either or both of:
- (1). implement gRPC health checking protocol (https://github.com/grpc/grpc/blob/master/doc/health-checking.md)
- (2). as noted in https://github.com/kubevirt/kubevirt/issues/1023#issuecomment-420621848, add subcommand to virtctl in a similar way to OKD diagnostics (though removed in https://github.com/openshift/origin/pull/20814)

(1) is assumed to be mainly used for readiness/liveness probe, while (2) is more of cluster admin CLI.
I think we should give high priority to (1) though,

**Comment by fabiand** [comment]
To me this feature is a dedicated pod/service which performns teh necessary checks, or collects them from other pods, and then provides one aggregated status.

It's _not_ only about the liveness check of a single pod itself.

**Comment by lkpdn** [comment]
I see, now I get why you mentioned OKD diagnostics while not for things like gRPC health checking.

**Comment by fabiand** [comment]
It would still be great to see a contribution in this area!
The great thing abotu this issue is thatit can start small, then grow.

**Comment by lkpdn** [comment]
will do! :smiley:
