### ISSUE TITLE
Add API support for sidecars instead of requiring an import of all of kubevirt.io/kubevirt

### ISSUE THREAD

**Issue by hamptonmoore** [kubevirt/kubevirt#10243]
**Is your feature request related to a problem? Please describe**:

Yes, the problem is related to the dependency management when developing sidecar containers for KubeVirt. Currently, developing sidecars requires importing the entire `kubevirt.io/kubevirt` package, which leads to significant dependency issues and requires lot of dependency replacements.

**Describe the solution you'd like**:

We would like to propose exporting the necessary packages for sidecar development within the `kubevirt.io/api` module. Specifically, these packages are:

- `kubevirt.io/kubevirt/pkg/hooks/`
- `kubevirt.io/kubevirt/pkg/virt-launcher/`

Exporting these packages in `kubevirt.io/api` would allow developers to import only what is necessary for creating sidecars, thus reducing dependency issues.

**Describe alternatives you've considered**:

An alternative solution might be to provide a separate module specifically for sidecar development that includes only the necessary packages. However, this approach might introduce additional maintenance overhead.

**Additional context**:

The need for this change is underscored by the current example of a sidecar provided in the KubeVirt project, located [here](https://github.com/kubevirt/kubevirt/blob/main/cmd/example-hook-sidecar/smbios.go). This example imports the entire `kubevirt.io/kubevirt` package, which can cause significant dependency issues for many projects. By providing the necessary packages for sidecar development within `kubevirt.io/api`, we can simplify the process and make it more accessible for developers.

This change would contribute significantly to the extensibility of KubeVirt and would encourage more developers to create custom sidecars for their specific use cases. Currently it's seeming like my only option is to just make another repo for my project just for sidecars which is just a forked kubevirt/kubevirt for building sidecars out of

**Comment by EdDev** [comment]
> This example imports the entire `kubevirt.io/kubevirt` package, which can cause significant dependency issues for many projects.

The referenced example imports`kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/api` which describes the domain configuration. It does have at least two dependencies that should be cleaned up, but these are surely not the entire `kubevirt` project.

It does make sense to move it to a root package and define some build rules to avoid adding dependencies, but I do not think it fits the `kubevirt.io/api` package.

Said all that, I think that the sidecar hook is not currently a formal feature in kubevirt. It is not documented formally in the user guide and examples are provided to allow informal extensions.
Currently, the domain configuration API is not user-facing, it serves the virt-handler and virt-launcher components. Making it formally public will limit its ability to change and increase maintenance significantly.

I guess we should define some softer commitments for this API with its own rules and policies.

**Comment by EdDev** [comment]
Clarification: The API of the sidecar hooks is pretty stable and is not strongly dependent on this domain API.
The hooks accept a stream of bytes that represent a libvirt domain configuration.

Someone who writes logic in the hook can use the structure kubevirt uses, but it can also creates its own.
As it stands now, the libvirt domain spec structures are used internally and have not been exposed as formal API/s.
It is not likely they will break backward compatibility because we need to support old domains running even if an upgrade of the cluster has occurred, but the level of assurance here is not like the one we keep for user-facing API.
