### ISSUE TITLE
Document list of kernel features required/recommended by kubevirt

### ISSUE THREAD

**Issue by theodiem** [kubevirt/kubevirt#10242]
**Is your feature request related to a problem? Please describe**:
I'm trying to use kubevirt on my own kerrnel and I'm getting:
```
{"component":"virt-handler","level":"info","msg":"Created tap device: tap0 in PID: 228362","pos":"common.go:365","timestamp":"2023-08-04T13:32:33.167651Z"}
{"component":"virt-handler","level":"info","msg":"Successfully configured tap device: tap0","pos":"common.go:404","timestamp":"2023-08-04T13:32:33.189725Z"}
{"component":"virt-handler","level":"error","msg":"failed to create ipv4 nat rules for vm error: Couldn't configure ip nat rules","pos":"masquerade.go:145","reason":"Couldn't configure ip nat rules","timestamp":"2023-08-04T13:32:33.199193Z"}
{"component":"virt-handler","level":"error","msg":"failed to configure pod network: default","pos":"configstate.go:108","reason":"Couldn't configure ip nat rules","timestamp":"2023-08-04T13:32:33.199230Z"}
```

**Describe the solution you'd like**:
Would be nice to have a list of recommended/required features that should be present on /proc/config.gz.
It is not so simple to track which features are required (for example xtables/ip_nf matches and targets) among other (nftables) and could save reasonable amount of time when certain kernel feature is not present on the system.

**Describe alternatives you've considered**:
Comparing my /proc/config.gz with a distro that it works and painfully enabling everything that I don't have, until I have it working.

**Additional context**:
None AFAIK.

**Comment by theodiem** [comment]
Or maybe include something similar to `virt-host-validate` (which afaik checks also /proc/config.gz)

**Comment by alicefr** [comment]
`virt-host-validate` definitely helps, in fact, we do suggest using it, but it might not be easy to install on the host. Have you encountered any issues using your distribution?

**Comment by prady0t** [comment]
Is there a way to view kernel config files on MacOS since `/proc/config.gz` does not work.
