### ISSUE TITLE
`ps` doesn't work reliably when executed inside pods by the e2e test suite

### ISSUE THREAD

**Issue by jean-edouard** [kubevirt/kubevirt#10240]
**What happened**:
Functional tests that run `ps` inside of virt-handler (and virt-launcher?) tend to get flaky, with `ps` usually finding the right information but then failing with error 1.
Some past investigation seemed to identify SIGURG as causing issues, but trapping it didn't seem to make a difference:
https://github.com/kubevirt/kubevirt/commit/13a7e4c82ea0fa600a17512fa4addda3ccbf1205
https://github.com/kubevirt/kubevirt/pull/8600/files

As a result, we usually end up replacing `ps` calls to other tools like `pidof` or `pgrep` that do not seem to suffer the same problem. Examples:
https://github.com/kubevirt/kubevirt/pull/6734
https://github.com/kubevirt/kubevirt/pull/10235

It would be a good idea to create a draft PR with tons of debug around some flaky `ps` call to find the root cause of this, as it could be an important issue with KubeVirt containers...

**Comment by oshoval** [comment]
Maybe the ps bug was fixed and we need to drop the trap of `SIGURG` 

something like that was suggested here
https://www.suse.com/support/update/announcement/2022/suse-ru-20220808-1/

**Comment by jean-edouard** [comment]
> Maybe the ps bug was fixed and we need to drop the trap of `SIGURG`
> 
> something like that was suggested here iiuc https://www.suse.com/support/update/announcement/2022/suse-ru-20220808-1/

Thanks for the pointer! However, we see the issue with and without the URG trap.
The reason I mentioned it is to avoid someone else going down this rabbit hole. Your link further supports the fact that that signal is not the problem.
In fact, right now I don't think any `ps` call in kubevirt tests runs with SIGURG trapped anymore.

**Comment by xpivarc** [comment]
@jean-edouard would you be able to check if we use `ps` anymore?
