### ISSUE TITLE
Current client-go version (v0.26.3) contains possible panic in discovery

### ISSUE THREAD

**Issue by seans3** [kubevirt/kubevirt#10262]
Please update kubevirt to use client-go version to v0.26.4+

Why: Possible panic when using client-go v0.26.0 - v0.26.3 (looks like current client-go is affected: v0.26.3) for discovery.

kubernetes issue: https://github.com/kubernetes/kubernetes/issues/119840

**Comment by xpivarc** [comment]
Thanks @seans3 for reporting the issue. I opened relevant fixes.

**Comment by xpivarc** [comment]
/close
We should be covered now
