### ISSUE TITLE
how to install the old version of kubevirt like v0.52.0 in arm64

### ISSUE THREAD

**Issue by Gohoy** [kubevirt/kubevirt#10281]
**What happened**:
I want to install the v0.52.0 version of kubevirt. But the document only provided the latest version v1.0.
**What you expected to happen**:
I want to get the v0.52.0 version of kubevirt-operator.yaml and kubevirt-cr.yaml
**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.52.0
- Kubernetes version (use `kubectl version`): v1.23.1
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: v1.49
- OS (e.g. from /etc/os-release): openEuler
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by zhlhahaha** [comment]
Hi, you may need to compile the `virtctl` binary by yourself. 
1. Download the source code and checkout to v0.52.0
2. compile the `virtctl`, please refer to https://github.com/kubevirt/kubevirt/issues/3558#issuecomment-878886897

**Comment by Gohoy** [comment]
> 

OK，thanks.
