### ISSUE TITLE
Provide a windows container image

### ISSUE THREAD

**Issue by chenxinlong** [kubevirt/kubevirt#10282]
**Describe the solution you'd like**:
Container image in https://quay.io/organization/containerdisks is super convenient, will the windows container image be supported in the future ?

**Comment by alicefr** [comment]
@chenxinlong I don't think this is possible because you need a license and eventually you need to buy it. But you can follow the guide here to have your own installation: https://kubevirt.io/2022/KubeVirt-installing_Microsoft_Windows_11_from_an_iso.html
