### ISSUE TITLE
VirtualMachineClone's phase should have 'failed' phase 

### ISSUE THREAD

**Issue by Longchuanzheng** [kubevirt/kubevirt#10294]
**Is your feature request related to a problem? Please describe**:

I find VirtualMachineClone's phase only have ’Progressing‘ and ’Succeeded‘ right now, but snapshot could upgrade to 'Failed' phase. I think VirtualMachineClone should also have 'Failed' phase.

**Describe the solution you'd like**:

Adding ’Failed‘ phase to VirtualMachineClone's ConditionType and updating VirtualMachineClone's phase use VirtualMachinesnapshot Phase.

**Describe alternatives you've considered**:
None

**Additional context**:

**Comment by xpivarc** [comment]
Hi @Longchuanzheng , Please describe what you did and what happened in order for us to be able to look at this.

**Comment by Longchuanzheng** [comment]
> Hi @Longchuanzheng , Please describe what you did and what happened in order for us to be able to look at this.

I just read the documentation and source code. I think when VirtualMachineSnapshot has become 'Failed' phase the VirtualMachineClone will still in 'Progressing' phase.

**Comment by Longchuanzheng** [comment]
I got it wrong before, VirtualMachineClone have more phase than I assume.
* SnapshotInProgress
* CreatingTargetVM
* RestoreInProgress
* Succeeded
* Failed
* Unknown
