### ISSUE TITLE
vm stopped unexpectedly "CrashLoopBackOff "but  "Normal  SuccessfulDelete" 

### ISSUE THREAD

**Issue by Gohoy** [kubevirt/kubevirt#10290]
**What happened**:
I tried to the test vm like kubectl apply -f https://kubevirt.io/labs/manifests/vm.yaml ,and I got this issue

**What you expected to happen**:
The vm start successfully

**How to reproduce it (as minimally and precisely as possible)**:
For me, just start a vm

**Additional context**:
I use the openEuler arm64 . I want to know if this issue is related to the os or the arch

**Environment**:
- KubeVirt version (use `virtctl version`): 1.0
- Kubernetes version (use `kubectl version`): 1.23.1
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): openEuler 22.04LTS
- Kernel (e.g. `uname -a`):  Linux master 5.10.0-60.52.0.80.oe2203.aarch64 #1 SMP Wed Aug 24 16:53:43 UTC 2022 aarch64 aarch64 aarch64 GNU/Linux
- Install tools: 
- Others: cdi v1.49

**Comment by Gohoy** [comment]
kubectl describe vm testvm


Name:         testvm
Namespace:    default
Labels:       <none>
Annotations:  kubevirt.io/latest-observed-api-version: v1
              kubevirt.io/storage-observed-api-version: v1
API Version:  kubevirt.io/v1
Kind:         VirtualMachine
Metadata:
  Creation Timestamp:  2023-08-14T15:42:23Z
  Finalizers:
    kubevirt.io/virtualMachineControllerFinalize
  Generation:  2
  Managed Fields:
    API Version:  kubevirt.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:template:
          .:
          f:metadata:
            .:
            f:labels:
              .:
              f:kubevirt.io/domain:
              f:kubevirt.io/size:
          f:spec:
            .:
            f:domain:
              .:
              f:devices:
                .:
                f:disks:
                f:interfaces:
              f:resources:
                .:
                f:requests:
                  .:
                  f:memory:
            f:networks:
            f:volumes:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2023-08-14T15:42:23Z
    API Version:  kubevirt.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubevirt.io/latest-observed-api-version:
          f:kubevirt.io/storage-observed-api-version:
        f:finalizers:
          .:
          v:"kubevirt.io/virtualMachineControllerFinalize":
      f:spec:
        f:running:
    Manager:      Go-http-client
    Operation:    Update
    Time:         2023-08-14T15:43:08Z
    API Version:  kubevirt.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        .:
        f:conditions:
        f:desiredGeneration:
        f:observedGeneration:
        f:printableStatus:
        f:startFailure:
          .:
          f:consecutiveFailCount:
          f:lastFailedVMIUID:
          f:retryAfterTimestamp:
        f:volumeSnapshotStatuses:
    Manager:         Go-http-client
    Operation:       Update
    Subresource:     status
    Time:            2023-08-14T15:48:22Z
  Resource Version:  140688
  UID:               e6890855-13ce-45f0-97dd-42da44deecac
Spec:
  Running:  true
  Template:
    Metadata:
      Creation Timestamp:  <nil>
      Labels:
        kubevirt.io/domain:  testvm
        kubevirt.io/size:    small
    Spec:
      Architecture:  arm64
      Domain:
        Devices:
          Disks:
            Disk:
              Bus:  virtio
            Name:   containerdisk
            Disk:
              Bus:  virtio
            Name:   cloudinitdisk
          Interfaces:
            Masquerade:
            Name:  default
        Machine:
          Type:  virt
        Resources:
          Requests:
            Memory:  64M
      Networks:
        Name:  default
        Pod:
      Volumes:
        Container Disk:
          Image:  quay.io/kubevirt/cirros-container-disk-demo
        Name:     containerdisk
        Cloud Init No Cloud:
          userDataBase64:  SGkuXG4=
        Name:              cloudinitdisk
Status:
  Conditions:
    Last Probe Time:       2023-08-14T15:48:22Z
    Last Transition Time:  2023-08-14T15:48:22Z
    Message:               VMI does not exist
    Reason:                VMINotExists
    Status:                False
    Type:                  Ready
  Desired Generation:      2
  Observed Generation:     2
  Printable Status:        CrashLoopBackOff
  Start Failure:
    Consecutive Fail Count:  4
    Last Failed VMIUID:      5fde2756-8f75-4de2-a8b0-be0190cda22c
    Retry After Timestamp:   2023-08-14T15:52:14Z
  Volume Snapshot Statuses:
    Enabled:  false
    Name:     containerdisk
    Reason:   Snapshot is not supported for this volumeSource type [containerdisk]
    Enabled:  false
    Name:     cloudinitdisk
    Reason:   Snapshot is not supported for this volumeSource type [cloudinitdisk]
Events:
  Type    Reason            Age                    From                       Message
  ----    ------            ----                   ----                       -------
  Normal  SuccessfulDelete  8m25s                  virtualmachine-controller  Stopped the virtual machine by deleting the virtual machine instance 9a5bb790-1cd6-4b4e-9ba2-802cc7d450df
  Normal  SuccessfulDelete  7m28s                  virtualmachine-controller  Stopped the virtual machine by deleting the virtual machine instance c7bc79ba-9646-45e0-86fd-79f464fed6ae
  Normal  SuccessfulDelete  6m9s                   virtualmachine-controller  Stopped the virtual machine by deleting the virtual machine instance 7f218ae0-9bc5-4dfb-8695-4ec9667e480f
  Normal  SuccessfulCreate  4m13s (x4 over 8m52s)  virtualmachine-controller  Started the virtual machine by creating the new virtual machine instance testvm
  Normal  SuccessfulDelete  3m42s                  virtualmachine-controller  Stopped the virtual machine by deleting the virtual machine instance 5fde2756-8f75-4de2-a8b0-be0190cda22c

**Comment by xpivarc** [comment]
Hi @Gohoy 
Please share a `virt-launcher` logs.

**Comment by Gohoy** [comment]
virt-launcher goes through the init and then error phase after VM creation, and then automatically deletes and rebuilds. This is the log for the error part 
{"component":"virt-launcher-monitor","level":"error","msg":"failed to run virt-launcher","pos":"virt-launcher-monitor.go:108","reason":"fork/exec /usr/bin/virt-launcher: errno 0","timestamp":"2023-08-15T00:40:44.658973Z"}
{"component":"virt-launcher-monitor","level":"error","msg":"monitoring virt-launcher failed","pos":"virt-launcher-monitor.go:86","reason":"fork/exec /usr/bin/virt-launcher: errno 0","timestamp":"2023-08-15T00:40:52.466320Z"}

**Comment by Gohoy** [comment]
> Hi @Gohoy Please share a `virt-launcher` logs.

The virt-launcher will go through init and then error after the vm is created, then automatically delete and rebuild. This is the log of init and error

//init part
Error from server (BadRequest): container "compute" in pod "virt-launcher-testvm-zkdfs" is waiting to start: PodInitializing
{"component":"virt-launcher-monitor","level":"error","msg":"failed to run virt-launcher","pos":"virt-launcher-

//error part
monitor.go:108","reason":"fork/exec /usr/bin/virt-launcher: errno 0","timestamp":"2023-08-15T01:33:38.986123Z"}
{"component":"virt-launcher-monitor","level":"error","msg":"monitoring virt-launcher failed","pos":"virt-launcher-monitor.go:86","reason":"fork/exec /usr/bin/virt-launcher: errno 0","timestamp":"2023-08-15T01:33:46.794634Z"}

**Comment by Gohoy** [comment]
> > Hi @Gohoy Please share a `virt-launcher` logs.
> 
> The virt-launcher will go through init and then error after the vm is created, then automatically delete and rebuild. This is the log of init and error
> 
> //init part Error from server (BadRequest): container "compute" in pod "virt-launcher-testvm-zkdfs" is waiting to start: PodInitializing {"component":"virt-launcher-monitor","level":"error","msg":"failed to run virt-launcher","pos":"virt-launcher-
> 
> //error part monitor.go:108","reason":"fork/exec /usr/bin/virt-launcher: errno 0","timestamp":"2023-08-15T01:33:38.986123Z"} {"component":"virt-launcher-monitor","level":"error","msg":"monitoring virt-launcher failed","pos":"virt-launcher-monitor.go:86","reason":"fork/exec /usr/bin/virt-launcher: errno 0","timestamp":"2023-08-15T01:33:46.794634Z"}

And I ls  /usr/bin/virt-launcher got not found. Should I install some package?

**Comment by xpivarc** [comment]
Are you using Docker,  if so then this is the issue https://github.com/kubevirt/kubevirt/issues/9465#issuecomment-1673437332

**Comment by Gohoy** [comment]
> Are you using Docker, if so then this is the issue [#9465 (comment)](https://github.com/kubevirt/kubevirt/issues/9465#issuecomment-1673437332)

Yes，I am using docker. I think this is the same issue. Thanks.
