### ISSUE TITLE
internal error: unable to execute QEMU command 'cont': Resetting the Virtual Machine is required

### ISSUE THREAD

**Issue by yuntianfeijing** [kubevirt/kubevirt#10319]
**What happened**:
Failed to sync vmi with Rocky Linux 8.8 (Green Obsidian)

**What you expected to happen**:
kubectl apply -f https://kubevirt.io/labs/manifests/vm.yaml
virtctl start testvm
kubectl describe vmi testvm
I get the Event:
Warning  SyncFailed        2m18s (x20 over 7m46s)  virt-handler               server error. command SyncVMI failed: "LibvirtError(Code=1, Domain=10, Message='internal error: unable to execute QEMU command 'cont': Resetting the Virtual Machine is required')"

**How to reproduce it (as minimally and precisely as possible)**:
kubectl apply -f https://kubevirt.io/labs/manifests/vm.yaml
virtctl start testvm
kubectl describe vm testvm
I get the Event:
Warning  SyncFailed        2m18s (x20 over 7m46s)  virt-handler               server error. command SyncVMI failed: "LibvirtError(Code=1, Domain=10, Message='internal error: unable to execute QEMU command 'cont': Resetting the Virtual Machine is required')"

**Additional context**:
the vm is ok in the same k8s cluster node of centos7.9

virt-launcher error log:
{"component":"virt-launcher","level":"error","msg":"internal error: unable to execute QEMU command 'cont': Resetting the Virtual Machine is required","pos":"qemuMonitorJSONCheckErrorFull:366","subcomponent":"libvirt","thread":"26","timestamp":"2023-08-22T10:06:25.087000Z"}
{"component":"virt-launcher","kind":"","level":"error","msg":"unpausing the VirtualMachineInstance failed.","name":"testvm","namespace":"default","pos":"manager.go:1038","reason":"virError(Code=1, Domain=10, Message='internal error: unable to execute QEMU command 'cont': Resetting the Virtual Machine is required')","timestamp":"2023-08-22T10:06:25.087573Z","uid":"2d87ecc5-8b39-4dc5-898f-14e6a3f8dd44"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"testvm","namespace":"default","pos":"server.go:202","reason":"virError(Code=1, Domain=10, Message='internal error: unable to execute QEMU command 'cont': Resetting the Virtual Machine is required')","timestamp":"2023-08-22T10:06:25.087628Z","uid":"2d87ecc5-8b39-4dc5-898f-14e6a3f8dd44"}

virt-handler error log:
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Running | Domain status: Paused, reason: Unknown","name":"testvm","namespace":"default","pos":"vm.go:1757","timestamp":"2023-08-22T09:58:56.612701Z","uid":"2d87ecc5-8b39-4dc5-898f-14e6a3f8dd44"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"testvm","namespace":"default","pos":"vm.go:1905","reason":"server error. command SyncVMI failed: \"LibvirtError(Code=1, Domain=10, Message='internal error: unable to execute QEMU command 'cont': Resetting the Virtual Machine is required')\"","timestamp":"2023-08-22T09:58:56.615079Z","uid":"2d87ecc5-8b39-4dc5-898f-14e6a3f8dd44"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/testvm","pos":"vm.go:1549","reason":"server error. command SyncVMI failed: \"LibvirtError(Code=1, Domain=10, Message='internal error: unable to execute QEMU command 'cont': Resetting the Virtual Machine is required')\"","timestamp":"2023-08-22T09:58:56.638788Z"}

**Environment**:
- KubeVirt version (use `virtctl version`): v1.0.0
- Kubernetes version (use `kubectl version`): v1.26.6
- VM or VMI specifications: https://kubevirt.io/labs/manifests/vm.yaml
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Rocky Linux 8.8 (Green Obsidian)
- Kernel (e.g. `uname -a`): 4.18.0-477.13.1.el8_8.x86_64
- Install tools: kubevirt-operator
- Others: N/A

**Comment by victortoso** [comment]
>  Failed to sync vmi with Rocky Linux 8.8 (Green Obsidian)

and

>  the vm is ok in the same k8s cluster node of centos7.9

Is there any reason you think this bug is specific to KubeVirt? If it works on centos7.9 node but not in rocky linux 8.8 node, it would seem a host OS bug. Which kernel version do you have in both and would it be possible to get full logs from libvirt? it might show other hints to the issue.

**Comment by yuntianfeijing** [comment]
> Hi @yuntianfeijing , do you modify Kubevirt in any way?
I have not modified any components, the image is official
