### ISSUE TITLE
Error following the deployment steps on the official website

### ISSUE THREAD

**Issue by yule-sun** [kubevirt/kubevirt#10318]
**Description**:
I deployed kubevirt v1.0.0 offline in my cluster according to the documentation on the official website https://kubevirt.io/quickstart_cloud/.
The number of resources generated after deployment is wrong, and there is an error in the pod log
![image](https://github.com/kubevirt/kubevirt/assets/37107125/735e9823-8aba-4e39-801a-90172d212e6c)
Like the picture above, I have only 2 pods, 1 deployment.apps and 1 replicaset.apps

![image](https://github.com/kubevirt/kubevirt/assets/37107125/ffbe2bf4-4cd9-41cf-9a2d-e1f143263647)
 
Then use the yaml file in https://kubevirt.io/labs/kubernetes/lab1 to create a virtual machine and prompt such an error
error: unable to recognize "kubevirt/vm.yaml": no matches for kind "VirtualMachine" in version "kubevirt.io/v1"

**What you expected**:
1. Does kubevirt have a version requirement for kubernetes? Can it be specified in the document?
2. What resources are included in the installation result, can you provide a screenshot for reference
3. During the execution of kubectl create -f kubevirt-operator.yaml, is it necessary to connect to the Internet to generate resources of other types?

**URL**:
[Provide a link to the documentation.](https://kubevirt.io/quickstart_cloud/)

**Additional context**:
kubernetes cluster version V1.20.12

**Comment by xpivarc** [comment]
/close
Hi @yule-sun, Release 1.0 supports Kubernetes 1.26 & 1.27 & 1.28

**Comment by yule-sun** [comment]
> 
Thank you very much for your reply. I have also tested and installed the v0.55.0 version, and it is the same error. In addition, where can I find the kubernetes version information supported by kubevirt?

**Comment by xpivarc** [comment]
@yule-sun Unfortunately we do not maintain a support matrix as of now. We are working on it. Do you really need to use Kubernetes 1.20? As far as I can say it is out of support for at least a year. Kubevirt version would be something between v0.40-v0.50. Please note that we are unable to help with any issues if any occur on these old versions.
