### ISSUE TITLE
 Is there a minimum kernel version to use masquerade in version 0.58.1?

### ISSUE THREAD

**Issue by mzzgaopeng** [kubevirt/kubevirt#10325]
Is there a minimum kernel version to use masquerade in version 0.58.1?

**Comment by xpivarc** [comment]
@EdDev Would you know?

**Comment by EdDev** [comment]
> @EdDev Would you know?
 We use nftables to co configure the kernel.
Base on https://wiki.nftables.org/wiki-nftables/index.php/Performing_Network_Address_Translation_(NAT), the minimum is 3.18 and in some cases even 4.18.

We do not perform tests to confirm this, so take that into account.

**Comment by mzzgaopeng** [comment]
> > @EdDev Would you know?
> 
> We use nftables to configure the kernel. Base on https://wiki.nftables.org/wiki-nftables/index.php/Performing_Network_Address_Translation_(NAT), the minimum is 3.18 and in some cases even 4.18.
> 
> We do not perform tests to confirm this, so take that into account.

Thanks
