### ISSUE TITLE
Error from server (InternalError): error when creating "./vm.yaml": Internal error occurred: failed calling webhook "virtualmachines-mutator.kubevirt.io": Post "https://virt-api.kubevirt.svc:443/virtualmachines-mutate?timeout=10s": context deadline exceeded

### ISSUE THREAD

**Issue by kyungminchoi** [kubevirt/kubevirt#10332]
I installed KubeVirt and virtctl by following the official documentation.
But I failed to create VM.

Environment : 
virtctl  v1.0.0-beta.0
kubectl  v1.21.0
CNI - flannel
CRI - containerd
kubernetes v1.21.0
3 master nodes - Ubuntu Server 20.04 LTS, 5.4.0-131-generic, m2.c4m8 (4Core, 8GB), disk 50GB
3 worker nodes - Ubuntu Server 20.04 LTS, 5.4.0-131-generic, m2.c8m16 (8Core, 16GB), disk 100GB

Error: 
<img width="1095" alt="image" src="https://github.com/kubevirt/kubevirt/assets/26079764/0209219d-65bf-4566-9c45-726cb35e11d3">

Command I ran :

- install KubeVirt
`export VERSION=$(curl -s https://api.github.com/repos/kubevirt/kubevirt/releases | grep tag_name | grep -v -- '-rc' | sort -r | head -1 | awk -F': ' '{print $2}' | sed 's/,//' | xargs)`
`echo $VERSION` 
`kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/kubevirt-operator.yaml`
`kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/kubevirt-cr.yaml`

- install virtctl
`VERSION=$(kubectl get kubevirt.kubevirt.io/kubevirt -n kubevirt -o=jsonpath="{.status.observedKubeVirtVersion}")`
`ARCH=$(uname -s | tr A-Z a-z)-$(uname -m | sed 's/x86_64/amd64/') || windows-amd64.exe`
`echo ${ARCH}`
`curl -L -o virtctl https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/virtctl-${VERSION}-${ARCH}`
`chmod +x virtctl`
`sudo install virtctl /usr/local/bin`

- create vm
`kubectl apply -f https://kubevirt.io/labs/manifests/vm.yaml`  <<- error occurred with this line.

**Comment by xpivarc** [comment]
It seems to me you are installing Kubevirt version 1.0 on top of Kubernetes 1.21. This is not a supported combination. Please update your Kubernetes to >= 1.26.

**Comment by victortoso** [comment]
@xpivarc interesting, if that's the case isn't there a way to throw an incompatible version error of some sort?

**Comment by kyungminchoi** [comment]
> It seems to me you are installing Kubevirt version 1.0 on top of Kubernetes 1.21. This is not a supported combination. Please update your Kubernetes to >= 1.26.

I can't upgrade my k8s version because my cluster is running multiple services and is sensitive to changes. Is there any resolution for this issue other than changing the version?

**Comment by xpivarc** [comment]
Hi @kyungminchoi ,
You could give it a try with Kubevirt 0.45-0.54. Please note Kubernetes 1.21 is EOL and that is more or less true for Kubevirt.

**Comment by kyungminchoi** [comment]
Hello @xpivarc , Thank you for your quick reply.
I took your advice and adjusted the version of KubeVirt to v0.54.0, still the same issue...

**Comment by simonyangcj** [comment]
@kyungminchoi looks like you virt-api unable to access mutating webhook api service address, you can simple run a pod with `curl` tool on the same node that virt-api runs and kubectl exec into pod  run `curl http://virtualmahcines-mutator.kubevirt.io` if unable to curl that might be your network setup issue

**Comment by kyungminchoi** [comment]
> url http://virtualmahcines-mutator.kubevirt.io

As you said, I can't curl it with 'Could not resolve host' DNS error message.

**Comment by kyungminchoi** [comment]
> @kyungminchoi looks like you virt-api unable to access mutating webhook api service address, you can simple run a pod with `curl` tool on the same node that virt-api runs and kubectl exec into pod run `curl http://virtualmahcines-mutator.kubevirt.io` if unable to curl that might be your network setup issue

As you said, I couldn't curl with the "Could not resolve host" error.
If you know, can you tell me what network setup issue it is?

**Comment by kyungminchoi** [comment]
I solved the issue. It's CRI proxy configuration issue. 

`sudo mkdir /etc/systemd/system/containerd.service.d
sudo vi /etc/systemd/system/containerd.service.d/http-proxy.conf

#http-proxy.conf file content 
[Service]
Environment="HTTP_PROXY=http://YOUR_PROXY_IP:PORT"
Environment="HTTPS_PROXY=http://YOUR_PROXY_IP:PORT"
Environment="NO_PROXY=.svc,localhost,127.0.0.1,127.0.0.0,127.0.1.1,127.0.1.1,local.home,YOUR_MASTER_NODE_IP,YOUR_WORKER_NODE_IP,YOUR_POD_CIDR,YOUR_SERVICE_CIDR"

#restart containerd
sudo systemctl daemon-reload
sudo systemctl restart containerd`
