### ISSUE TITLE
Unable to upload window image

### ISSUE THREAD

**Issue by moyunnie** [kubevirt/kubevirt#10341]
**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

[root@master data]# ./virtctl-v1.0.0-linux-amd64 image-upload pvc win11cd-pvc --size 6Gi --image-path=/nfs/data/cn_windows_7_professional_with_sp1_x86_dvd_u_677162.iso --insecure
PVC default/win11cd-pvc not found 
PersistentVolumeClaim default/win11cd-pvc created
Waiting for PVC win11cd-pvc upload pod to be ready...
timed out waiting for the condition

**Comment by matthewei** [comment]
could you share more info?

**Comment by aburdenthehand** [comment]
@moyunnie To add to matthew's request, can you please fill in the details in the bug template (What happened, what you expected to happen, how to reproduce, environment details, etc). It is very difficult to provide assistance without this information. Thank you.

**Comment by moyunnie** [comment]
[root@master ~]# kubectl get pod -A
NAMESPACE          NAME                                       READY   STATUS    RESTARTS         AGE
calico-apiserver   calico-apiserver-77c88dbc78-49bs2          1/1     Running   5 (4m12s ago)    9d
calico-apiserver   calico-apiserver-77c88dbc78-rkmpq          1/1     Running   5 (4m19s ago)    9d
calico-system      calico-kube-controllers-6dd9d868c9-kb8ll   1/1     Running   4 (4m42s ago)    9d
calico-system      calico-node-56td4                          1/1     Running   4 (4m12s ago)    9d
calico-system      calico-node-7t2b9                          1/1     Running   4 (4m42s ago)    9d
calico-system      calico-node-t7dbn                          1/1     Running   4 (4m19s ago)    9d
calico-system      calico-typha-54ff88bd77-4z259              1/1     Running   5 (4m19s ago)    9d
calico-system      calico-typha-54ff88bd77-n6bw5              1/1     Running   5 (4m12s ago)    9d
calico-system      csi-node-driver-8ntkx                      2/2     Running   8 (4m42s ago)    9d
calico-system      csi-node-driver-jsljv                      2/2     Running   8 (4m12s ago)    9d
calico-system      csi-node-driver-vc92f                      2/2     Running   8 (4m19s ago)    9d
cdi                cdi-apiserver-6fd47b9fbc-k2nnz             1/1     Running   4 (4m12s ago)    9d
cdi                cdi-deployment-6bbbb86599-wr9bd            1/1     Running   10 (4m12s ago)   9d
cdi                cdi-operator-686f8954f9-vdgjp              1/1     Running   10 (4m12s ago)   9d
cdi                cdi-uploadproxy-7cdf94cb7f-m4cq4           1/1     Running   4 (4m19s ago)    9d
cert-manager       cert-manager-cainjector-646bf69b85-7wdjg   1/1     Running   4 (4m12s ago)    9d
cert-manager       cert-manager-fd68f5467-swz6q               1/1     Running   4 (4m12s ago)    9d
cert-manager       cert-manager-webhook-796478777-nj9t5       1/1     Running   4 (4m19s ago)    9d
default            nfs-client-provisioner-856bb75589-j7j4k    1/1     Running   6 (4m19s ago)    6d22h
default            virt-launcher-testvm-6ktbc                 2/2     Running   0                22s
kube-system        coredns-6d8c4cb4d-mfw8q                    1/1     Running   4 (4m42s ago)    9d
kube-system        coredns-6d8c4cb4d-vqpc4                    1/1     Running   4 (4m42s ago)    9d
kube-system        etcd-master                                1/1     Running   4 (4m42s ago)    9d
kube-system        kube-apiserver-master                      1/1     Running   5 (4m42s ago)    9d
kube-system        kube-controller-manager-master             1/1     Running   4 (4m42s ago)    9d
kube-system        kube-proxy-dpwjw                           1/1     Running   4 (4m12s ago)    9d
kube-system        kube-proxy-kcjrw                           1/1     Running   4 (4m19s ago)    9d
kube-system        kube-proxy-spnng                           1/1     Running   4 (4m42s ago)    9d
kube-system        kube-scheduler-master                      1/1     Running   4 (4m42s ago)    9d
kubevirt           virt-api-64d9c98d6b-668xr                  1/1     Running   5 (4m12s ago)    9d
kubevirt           virt-api-64d9c98d6b-bnxln                  1/1     Running   5 (4m19s ago)    9d
kubevirt           virt-controller-59c786895f-vrfqd           1/1     Running   7 (4m12s ago)    9d
kubevirt           virt-controller-59c786895f-wgfqh           1/1     Running   6 (4m19s ago)    9d
kubevirt           virt-handler-qtqns                         1/1     Running   4 (4m19s ago)    9d
kubevirt           virt-handler-r7kgw                         1/1     Running   4 (4m12s ago)    9d
kubevirt           virt-operator-75b5795c77-dtkvg             1/1     Running   5 (4m19s ago)    9d
kubevirt           virt-operator-75b5795c77-f77dh             1/1     Running   6 (4m12s ago)    9d
kubevirt           virtvnc-548df7b7cd-5w88m                   1/1     Running   4 (4m42s ago)    9d
tigera-operator    tigera-operator-59b69c49dc-qbxd7           1/1     Running   12 (3m22s ago)   9d
[root@master ~]# kubectl get svc -A
NAMESPACE          NAME                              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
calico-apiserver   calico-api                        ClusterIP   10.105.126.162   <none>        443/TCP                  9d
calico-system      calico-kube-controllers-metrics   ClusterIP   None             <none>        9094/TCP                 9d
calico-system      calico-typha                      ClusterIP   10.99.42.19      <none>        5473/TCP                 9d
cdi                cdi-api                           ClusterIP   10.96.240.113    <none>        443/TCP                  9d
cdi                cdi-prometheus-metrics            ClusterIP   10.110.78.251    <none>        8080/TCP                 9d
cdi                cdi-uploadproxy                   ClusterIP   10.106.235.230   <none>        443/TCP                  9d
cert-manager       cert-manager                      ClusterIP   10.99.131.139    <none>        9402/TCP                 9d
cert-manager       cert-manager-webhook              ClusterIP   10.99.231.171    <none>        443/TCP                  9d
default            kubernetes                        ClusterIP   10.96.0.1        <none>        443/TCP                  9d
kube-system        kube-dns                          ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP   9d
kubevirt           kubevirt-operator-webhook         ClusterIP   10.103.208.63    <none>        443/TCP                  9d
kubevirt           kubevirt-prometheus-metrics       ClusterIP   None             <none>        443/TCP                  9d
kubevirt           virt-api                          ClusterIP   10.98.79.210     <none>        443/TCP                  9d
kubevirt           virt-exportproxy                  ClusterIP   10.97.191.107    <none>        443/TCP                  9d
kubevirt           virtvnc                           NodePort    10.100.9.91      <none>        8001:30090/TCP           9d

[root@master ~]# kubectl get pvc  -A
NAMESPACE   NAME              STATUS    VOLUME           CAPACITY   ACCESS MODES   STORAGECLASS   AGE
default     c7-pvc            Pending                                                             9d
default     cirros-vm-disk    Pending                                                             6d16h
default     cirros-vm-disk1   Pending   disk-windows     0                                        6d16h
default     disk-windows      Bound     task-pv-volume   15Gi       RWO            hostpath       6d23h
default     disk-windows1     Pending                                                             6d22h
default     iso-centos7       Pending                                                             6d16h
default     iso-win10         Pending                                                             9d
default     nfs-plugins       Bound     nfs-plugins      50Gi       RWX                           6d16h
default     nfs-pv            Pending                                                             6d16h
default     nfs-pvc           Bound     nfs              10Gi       RWX            nfs            9d
default     vm-pvc            Pending                                                             9d
default     win11cd-pvc       Pending                                                             9d
default     win7pv234c        Pending                                              nfs-storage    6d22h
default     win7pvc           Pending                                                             6d22h
[root@master ~]# cat win.yaml 
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-windows1
  name: vmi-windows1
spec:
  domain:
    clock:
      timer:
        hpet:
          present: false
        hyperv: {}
        pit:
          tickPolicy: delay
        rtc:
          tickPolicy: catchup
      utc: {}
    cpu:
      cores: 2
    devices:
      disks:
        - cdrom:
            bus: sata
          name: winiso
      interfaces:
        - masquerade: {}
          model: e1000
          name: default
      tpm: {}
    features:
      acpi: {}
      apic: {}
      hyperv:
        relaxed: {}
        spinlocks:
          spinlocks: 8191
        vapic: {}
      smm: {}
    firmware:
      bootloader:
        efi:
          secureBoot: true
      uuid: 5d307ca9-b3ef-428c-8861-06e72d69f223
    resources:
      requests:
        memory: 4Gi
  networks:
    - name: default
      pod: {}
  terminationGracePeriodSeconds: 0
  volumes:
    - name: winiso
      persistentVolumeClaim:
        claimName: nfs-pvc
[root@master ~]# kubectl get vmis
NAME           AGE     PHASE     IP                NODENAME    READY
testvm         65s     Running   192.168.36.123    k8s-node1   True
vmi-windows1   3m32s   Running   192.168.169.187   k8s-node2   True


window1 vnc Display after VNC link passes guest has not initalizerd the diplay(SET)

**Comment by moyunnie** [comment]
Uploading always times out when using this /virtctl-v1.0.0-linux-amd64 image-upload pvc win11cd-pvc --size 6Gi --image-path=/nfs/data/cn_windows_7_professional_with_sp1_x86_dvd_u_677162.iso --insecure

**Comment by moyunnie** [comment]
[root@master ~]# kubectl get vmis
NAME           AGE     PHASE     IP                NODENAME    READY
testvm         18m     Running   192.168.36.123    k8s-node1   True
vmi-windows1   2m50s   Running   192.168.169.129   k8s-node2   True
[root@master ~]# vi xin.yaml
[root@master ~]# kubectl apply -f xin.yaml 
serviceaccount/nfs-provisioner created
clusterrole.rbac.authorization.k8s.io/nfs-provisioner-runner created
clusterrolebinding.rbac.authorization.k8s.io/run-nfs-provisioner created
deployment.apps/nfs-client-provisioner configured
[root@master ~]# vi stoarg.yaml
[root@master ~]# kubectl apply -f stoarg.yaml 
storageclass.storage.k8s.io/storage-nfs created
[root@master ~]# kubectl get storageclass
NAME           PROVISIONER                                   RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
hostpath-csi   kubevirt.io.hostpath-provisioner              Delete          WaitForFirstConsumer   false                  6d22h
nfs-client     k8s-sigs.io/nfs-subdir-external-provisioner   Delete          Immediate              false                  6d22h
nfs-storage    kubernetes.io/nfs                             Delete          Immediate              false                  6d23h
storage-nfs    storage.pri/nfs                               Delete          Immediate              true                   11s
[root@master ~]# kubectl patch storageclass storage-nfs -p '{"metadata": {"annotations":{"storageclass.kubernetes.io/is-default-class":"true"}}}'
storageclass.storage.k8s.io/storage-nfs patched
[root@master ~]# vi pvcc.yaml
[root@master ~]# kubectl apply -f pvcc.yaml 
persistentvolumeclaim/pvc-claim-01 created
[root@master ~]# kubectl get pvc
NAME              STATUS    VOLUME           CAPACITY   ACCESS MODES   STORAGECLASS   AGE
c7-pvc            Pending                                                             9d
cirros-vm-disk    Pending                                                             6d17h
cirros-vm-disk1   Pending   disk-windows     0                                        6d16h
disk-windows      Bound     task-pv-volume   15Gi       RWO            hostpath       6d23h
disk-windows1     Pending                                                             6d23h
iso-centos7       Pending                                                             6d17h
iso-win10         Pending                                                             9d
nfs-plugins       Bound     nfs-plugins      50Gi       RWX                           6d16h
nfs-pv            Pending                                                             6d16h
nfs-pvc           Bound     nfs              10Gi       RWX            nfs            9d
pvc-claim-01      Pending                                              storage-nfs    4s
vm-pvc            Pending                                                             9d
win11cd-pvc       Pending                                                             9d
win7pv234c        Pending                                              nfs-storage    6d23h
win7pvc           Pending                                                             6d23h
[root@master ~]# kubectl get pvc
NAME              STATUS    VOLUME           CAPACITY   ACCESS MODES   STORAGECLASS   AGE
c7-pvc            Pending                                                             9d
cirros-vm-disk    Pending                                                             6d17h
cirros-vm-disk1   Pending   disk-windows     0                                        6d16h
disk-windows      Bound     task-pv-volume   15Gi       RWO            hostpath       6d23h
disk-windows1     Pending                                                             6d23h
iso-centos7       Pending                                                             6d17h
iso-win10         Pending                                                             9d
nfs-plugins       Bound     nfs-plugins      50Gi       RWX                           6d16h
nfs-pv            Pending                                                             6d16h
nfs-pvc           Bound     nfs              10Gi       RWX            nfs            9d
pvc-claim-01      Pending                                              storage-nfs    25s
vm-pvc            Pending                                                             9d
win11cd-pvc       Pending                                                             9d
win7pv234c        Pending                                              nfs-storage    6d23h
win7pvc           Pending                                                             6d23h
[root@master ~]# kubectl get pvc
NAME              STATUS    VOLUME           CAPACITY   ACCESS MODES   STORAGECLASS   AGE
c7-pvc            Pending                                                             9d
cirros-vm-disk    Pending                                                             6d17h
cirros-vm-disk1   Pending   disk-windows     0                                        6d16h
disk-windows      Bound     task-pv-volume   15Gi       RWO            hostpath       6d23h
disk-windows1     Pending                                                             6d23h
iso-centos7       Pending                                                             6d17h
iso-win10         Pending                                                             9d
nfs-plugins       Bound     nfs-plugins      50Gi       RWX                           6d16h
nfs-pv            Pending                                                             6d16h
nfs-pvc           Bound     nfs              10Gi       RWX            nfs            9d
pvc-claim-01      Pending                                              storage-nfs    26s
vm-pvc            Pending                                                             9d
win11cd-pvc       Pending                                                             9d
win7pv234c        Pending                                              nfs-storage    6d23h
win7pvc           Pending                                                             6d23h
[root@master ~]# vi textpod.yaml
[root@master ~]# kubectl apply -f textpod.yaml 
pod/test-pod created
[root@master ~]# kubectl get 
You must specify the type of resource to get. Use "kubectl api-resources" for a complete list of supported resources.

error: Required resource not specified.
Use "kubectl explain <resource>" for a detailed description of that resource (e.g. kubectl explain pods).
See 'kubectl get -h' for help and examples
[root@master ~]# ls
1.yaml  2.yaml  anaconda-ks.cfg  Desktop  Documents  Downloads  enabledisk.yaml  guanpv.yaml  k8s.yaml  Music  original-ks.cfg  Pictures  Public  pvcc.yaml  pvc.yaml  pv.yaml  stoarg.yaml  Templates  textpod.yaml  Videos  win7.c.yaml  win.yaml  xin.yaml
[root@master ~]# cd /opt/
[root@master opt]# cd /nfs/data/
[root@master data]# ls
1.yaml  class.yaml                                               datavolue.yaml  disk.img    kk.yaml             localstoage.yaml  nfs.yaml  pv.yaml    storageclass.yaml
3.yaml  cn_windows_7_professional_with_sp1_x86_dvd_u_677162.iso  datavol.yaml    Dockerfile  kustomization.yaml  newpvc.yaml       pvc.yaml  stao.yaml  virtctl-v1.0.0-linux-amd64
[root@master data]# kubectl get svc -A
NAMESPACE          NAME                              TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
calico-apiserver   calico-api                        ClusterIP   10.105.126.162   <none>        443/TCP                  9d
calico-system      calico-kube-controllers-metrics   ClusterIP   None             <none>        9094/TCP                 9d
calico-system      calico-typha                      ClusterIP   10.99.42.19      <none>        5473/TCP                 9d
cdi                cdi-api                           ClusterIP   10.96.240.113    <none>        443/TCP                  9d
cdi                cdi-prometheus-metrics            ClusterIP   10.110.78.251    <none>        8080/TCP                 9d
cdi                cdi-uploadproxy                   ClusterIP   10.106.235.230   <none>        443/TCP                  9d
cert-manager       cert-manager                      ClusterIP   10.99.131.139    <none>        9402/TCP                 9d
cert-manager       cert-manager-webhook              ClusterIP   10.99.231.171    <none>        443/TCP                  9d
default            kubernetes                        ClusterIP   10.96.0.1        <none>        443/TCP                  9d
kube-system        kube-dns                          ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP   9d
kubevirt           kubevirt-operator-webhook         ClusterIP   10.103.208.63    <none>        443/TCP                  9d
kubevirt           kubevirt-prometheus-metrics       ClusterIP   None             <none>        443/TCP                  9d
kubevirt           virt-api                          ClusterIP   10.98.79.210     <none>        443/TCP                  9d
kubevirt           virt-exportproxy                  ClusterIP   10.97.191.107    <none>        443/TCP                  9d
kubevirt           virtvnc                           NodePort    10.100.9.91      <none>        8001:30090/TCP           9d
[root@master data]# ./virtctl-v1.0.0-linux-amd64 image-upload --image-path /nfs/data/
1.yaml                                                   datavol.yaml                                             localstoage.yaml                                         stao.yaml
3.yaml                                                   disk.img                                                 newpvc.yaml                                              storageclass.yaml
class.yaml                                               Dockerfile                                               nfs.yaml                                                 virtctl-v1.0.0-linux-amd64
cn_windows_7_professional_with_sp1_x86_dvd_u_677162.iso  kk.yaml                                                  pvc.yaml                                                 
datavolue.yaml                                           kustomization.yaml                                       pv.yaml                                                  
[root@master data]# ./virtctl-v1.0.0-linux-amd64 image-upload --image-path /nfs/data/cn_windows_7_professional_with_sp1_x86_dvd_u_677162.iso --pvc-name=iso-win10 --pvc-size=7G --uploadproxy-url=https://10.106.235.230  --insecure --wait-secs=240
Flag --pvc-name has been deprecated, specify the name as the second argument instead.
Flag --pvc-size has been deprecated, use --size instead.
Using existing PVC default/iso-win10
Waiting for PVC iso-win10 upload pod to be ready...

**Comment by hanqingwu** [comment]
@moyunnie ， maybe you should check why  pvc   win11cd-pvc  stuck  in  pending  ?
---- your logs ----- 
 win11cd-pvc Pending 9d

**Comment by dvaldivia** [comment]
I'm running into the same issue, the `PVC` is stuck with the event
```
Normal  WaitForFirstConsumer  2m13s (x26 over 8m19s)  persistentvolume-controller  waiting for first consumer to be created before binding
```

but I don't see any pod coming online to start the copying @hanqingwu

**Comment by dvaldivia** [comment]
Additional information, I'm using `kubevirt v1.1.0` and `CDI v1.57.0`, and while `virtctl` is trying to upload the image, the `PVC` created looks like this

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    cdi.kubevirt.io/storage.contentType: kubevirt
    cdi.kubevirt.io/storage.upload.target: ""
  creationTimestamp: "2023-11-15T21:40:18Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: win11cd-pvc
  namespace: default
  resourceVersion: "2254700"
  uid: 65a43841-8f3a-4723-bbfd-d7a5b208658d
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 7Gi
  storageClassName: standard
  volumeMode: Filesystem
status:
  phase: Pending
```

now, the `cdi-deployment` shows the following logs regarding the `win11cd-pvc`

```
{"level":"debug","ts":"2023-11-15T21:43:51Z","logger":"controller.import-controller","msg":"PVC annotation not found, skipping pvc","PVC":"default/win11cd-pvc","annotation":"cdi.kubevirt.io/storage.import.source"}
{"level":"debug","ts":"2023-11-15T21:43:51Z","logger":"controller.import-controller","msg":"PVC not bound, skipping pvc","PVC":"default/win11cd-pvc","Phase":"Pending"}
{"level":"debug","ts":"2023-11-15T21:43:51Z","logger":"controller.clone-controller","msg":"reconciling Clone PVCs","PVC":"default/win11cd-pvc"}
{"level":"debug","ts":"2023-11-15T21:43:51Z","logger":"controller.clone-controller","msg":"PVC annotation not found, skipping pvc","PVC":"default/win11cd-pvc","annotation":"k8s.io/CloneRequest"}
{"level":"debug","ts":"2023-11-15T21:43:51Z","logger":"controller.clone-controller","msg":"PVC annotation not found, skipping pvc","PVC":"default/win11cd-pvc","annotation":"k8s.io/CloneRequest"}
{"level":"debug","ts":"2023-11-15T21:43:51Z","logger":"controller.clone-controller","msg":"PVC not bound, skipping pvc","PVC":"default/win11cd-pvc","Phase":"Pending"}
{"level":"debug","ts":"2023-11-15T21:43:51Z","logger":"controller.clone-controller","msg":"Should not reconcile this PVC","PVC":"default/win11cd-pvc","checkPVC(AnnCloneRequest)":false,"NOT has annotation(AnnCloneOf)":true,"isBound":false,"has finalizer?":false}
```

what gets my attention is `PVC annotation not found, skipping pvc`, but you can see in the created `PVC` that there's no source, only an empty target

Any idea what could be missing? 

I'm testing on Kubernets `1.28` and `kind`

**Comment by hanqingwu** [comment]
can you check your vm status , cdi  has a  featureGates  HonorWaitForFirstConsumer , sometime  you need start vm first , then pvc start bound .

https://github.com/kubevirt/containerized-data-importer/blob/main/doc/waitforfirstconsumer-storage-handling.md
