### ISSUE TITLE
uploadproxy-url connection timed out

### ISSUE THREAD

**Issue by kyungminchoi** [kubevirt/kubevirt#10352]
I tried to start Windows VM 

command I ran : 

- download win2016.iso image
`wget -O win2016.iso 'https://go.microsoft.com/fwlink/p/?LinkID=2195174&clcid=0x409&culture=en-us&country=US'`

- virtctl image-upload
`virtctl image-upload \
--image-path=/home1/irteamsu/kubevirt/win2016.iso \
--pvc-name=iso-win2016 \
--access-mode=ReadWriteOnce \
--pvc-size=7G \
--uploadproxy-url=https://10.244.4.187:8443 \
--insecure \
--wait-secs=240 \
--storage-class=nfs-client-security`

but the following error occurred.
![image](https://github.com/kubevirt/kubevirt/assets/26079764/80d3084f-a40d-467e-a10b-41b4f3b5422a)

My cdi uploadproxy pod ip is as follows, and the issue is the same even if I change it to nodeport service.
![image](https://github.com/kubevirt/kubevirt/assets/26079764/5897ed40-990d-47a3-9966-97a375eeeb40)

**Comment by matthewei** [comment]
I want to solve this issue.
@kyungminchoi when you upload this image, please execute "kubectl get pod" to find the upload pod. then please execute "kubectl logs -f --tail 200 <pod>".

**Comment by kyungminchoi** [comment]
@matthewei you mean cdi-upload-iso-win2016 pod? or cdi-uploadproxy-xxx pod? 
But neither log is logged.

**Comment by matthewei** [comment]
> @matthewei you mean cdi-upload-iso-win2016 pod? or cdi-uploadproxy-xxx pod? But neither log is logged.

the pod "cdi-upload-iso-win2016"

**Comment by kyungminchoi** [comment]
@matthewei 
<img width="622" alt="image" src="https://github.com/kubevirt/kubevirt/assets/26079764/29c1ac46-7032-4e56-9190-be83435341c0">
Other than this one line, no other logs were recorded.

**Comment by matthewei** [comment]
@kyungminchoi 
the resulet is expected.
could you share you the service of cdi-uploadproxy?

**Comment by matthewei** [comment]
I think you should use NotePort svc to upload the image.
