### ISSUE TITLE
Make it possible to specify VNC password for a VM

### ISSUE THREAD

**Issue by RomanKisilenko** [kubevirt/kubevirt#10372]
**Is your feature request related to a problem? Please describe**:
A clear and concise description of what the problem is.
We would like to develop an app which will proxy VNC connections using kubevirt. virtctl will be used on the server-side and the user will be able to connect to a proxied VNC port. Thus we need VNC connections to be password-protected.

**Describe the solution you'd like**:
libvirt natively supports a password to be specified for a VNC connection. You can do so using `--graphics vnc,listen=localhost,password=xxx` argument of virt-install and it is then passed to a VM manifest:
```
    <graphics type='vnc' port='-1' autoport='yes' listen='localhost' passwd='xxx'>
      <listen type='address' address='localhost'/>
    </graphics>
```
Thus it is a standard feature of libvirt and it would be great to also have a setting in a VM manifest to specify VNC password.

**Describe alternatives you've considered**:
No alternatives works for us.

**Additional context**:
N/A

**Comment by xpivarc** [comment]
@akrejcir was working on some kind of proxy as well, maybe it can be useful here as well

**Comment by akrejcir** [comment]
The "proxy" that I was working on was changed and does not do any proxying now. It would not be useful in this case.

**Comment by xpivarc** [comment]
> @xpivarc I can not agree that the feature is useless. Think of vps hosting use case. In this use case you want each vps to be accessible via its own VNC password. 

Yes, but you can implement it your way. For example, if you just expose Kubernetes API, each user would need to have access to the namespace in order to view vnc. Otherwise, you probably build some kind of proxy/broker that can enforce the password as well.

>Since the feature is natively available in an underlying library it should not be really difficult to add it for someone who understands how kubevirt defines the VM with underlying host OS.

Correct, there are a lot of features that Libvirt provides but we make conscious decisions on which of these features are worth 99% of use cases and/or can't be achieved outside of Kubevirt. This also helps to keep the project maintainable.

Note: You can use the sidecar mechanism in order to use passwords for VNC without modifying Kubevirt.

**Comment by xrei** [comment]
@xpivarc 
Hello,

I'm working on adding a feature and have successfully updated the spec to transfer the passwd attribute from YAML to XML. However, something later alters the XML, removing the passwd attribute.

Please see the first log entry in the attached [logs.txt](https://github.com/kubevirt/kubevirt/files/13439629/logs.txt), where the passwd attr is present. But the second XML string, following the line "DomainLifecycle event Domain event=\"defined\" detail=\"added\" with event id 0 reason 0 received", lacks the passwd attribute and includes additional changes. I suspect a Libvirt hook might be causing this, but I'm not certain. Could you point me in the right direction to resolve this issue?

[Here is my repo if needed](https://github.com/xrei/kubevirt/tree/feat/vnc-passwd)
