### ISSUE TITLE
failed to deploy kubevirt operator on k3s(VM)

### ISSUE THREAD

**Issue by mmuto118** [kubevirt/kubevirt#10378]
**What happened**:
I failed to deploy kubevirt operator on k3s(VM).

**What you expected to happen**:
I success to deploy kubevirt operator on k3s.
1) kubectl get all -n kubevirt 
2) kubevirt operator pods are in the status of "running".

**How to reproduce it (as minimally and precisely as possible)**:
1) deploy kubevirt operator
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
export VERSION=$(curl -s https://api.github.com/repos/kubevirt/kubevirt/releases | grep tag_name | grep -v -- '-rc' | sort -r | head -1 | awk -F': ' '{print $2}' | sed 's/,//' | xargs)
echo $VERSION
kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/kubevirt-operator.yaml

2) deploy custom resource definition
kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/kubevirt-cr.yaml

3) enable KubeVirt emulation
kubectl -n kubevirt patch kubevirt kubevirt --type=merge --patch '{"spec":{"configuration":{"developerConfiguration":{"useEmulation":true}}}}'

**Additional context**:
I am running VM(Ubuntu20.04) on proxmox.
I try to deploy kubevirt operator on k3s(VM).

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s1", GitCommit:"acad8ef8402021d6a78405c0b4fe420982e5ad1e", GitTreeState:"clean", BuildDate:"2021-09-20T17:40:35Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5+k3s1", GitCommit:"acad8ef8402021d6a78405c0b4fe420982e5ad1e", GitTreeState:"clean", BuildDate:"2021-09-20T17:40:35Z", GoVersion:"go1.16.8", Compiler:"gc", Platform:"linux/amd64"
- VM or VMI specifications: VM(Ubuntu 20.04) on Proxmox.  This is "Nested Virtualization" environment.
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): VERSION="20.04.4 LTS (Focal Fossa)"
- Kernel (e.g. `uname -a`): Linux k3s-ha2-master1 5.4.0-148-generic #165-Ubuntu SMP Tue Apr 18 08:53:12 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: N/A
- Others: N/A

**kubevirt operator pod log**
<html>
<body>

runtime/cgo: pthread_create failed: Operation not permitted
--
Tue, Sep 5 2023 4:13:36 pm | SIGABRT: abort
Tue, Sep 5 2023 4:13:36 pm | PC=0x198d66c m=0 sigcode=18446744073709551610
Tue, Sep 5 2023 4:13:36 pm |  
Tue, Sep 5 2023 4:13:36 pm | goroutine 0 [idle]:
Tue, Sep 5 2023 4:13:36 pm | runtime: g 0: unknown pc 0x198d66c
Tue, Sep 5 2023 4:13:36 pm | stack: frame={sp:0x7fff51347740, fp:0x0} stack=[0x7fff50b48cc0,0x7fff51347cd0)
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347640: 0x000000000041a2d9 <runtime.sysMapOS+0x0000000000000039> 0x0000000000000000
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347650: 0x00007f8965768000 0x000000000041a265 <runtime.sysHugePageOS+0x0000000000000065>
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347660: 0x00007f8967a00000 0x0000000000200000
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347670: 0x000000000000000e 0x00007f8900000000
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347680: 0x00007fff513476b0 0x000000000191899c
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347690: 0x00007f8967979000 0x000000000046c95e <runtime.callCgoMmap+0x000000000000003e>
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513476a0: 0x00007fff513476a8 0x00007f8967979000
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513476b0: 0x00007fff51347720 0x000000000191899c
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513476c0: 0x000000000040528f <runtime.mmap.func1+0x000000000000004f> 0x000000000046c95e <runtime.callCgoMmap+0x000000000000003e>
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513476d0: 0x00007fff513476d8 0x0000000000000007
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513476e0: 0x00007fff513477a0 0x000000000042c5cd <runtime.(*pageAlloc).update+0x00000000000003ad>
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513476f0: 0x00007f898c9f9c00 0x000000000191899c
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347700: 0x0000000000010000 0x000000000046c95e <runtime.callCgoMmap+0x000000000000003e>
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347710: 0x000000000198c9b0 0x000000001c000004
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347720: 0x000000000191b790 0x0000000000000000
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347730: 0x00007fff51347998 0x000000000198d65e
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347740: <0x0000000003520cd0 0x0000000000000000
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347750: 0x0000000000000010 0x0000000000000000
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347760: 0x0000000000000120 0x0000000000000110
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347770: 0x0000000000000004 0x0000000000000012
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347780: 0x0000000000000000 0x00000000019540d1
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347790: 0x00007f8965647640 0x00007fff51347a50
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513477a0: 0x00007fff513478be 0x00007fff513478bf
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513477b0: 0x00007f8965647640 0x0000000001925fa5
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513477c0: 0x000000000042fc65 <runtime.(*pallocData).allocRange+0x0000000000000045> 0x553c241bb9e61600
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513477d0: 0x0000000003c0d3c0 0x0000000000000006
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513477e0: 0x0000000003c0e650 0x0000000000000178
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513477f0: 0x0000000003506fc0 0x000000000197dfd6
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347800: 0x0000000003538000 0x00000000004011d8
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347810: 0x0000000000000020 0x0000000000000000
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347820: 0x0000000000000000 0x553c241bb9e61600
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347830: 0x00007fff51347900 0x00007f8965647640
Tue, Sep 5 2023 4:13:36 pm | runtime: g 0: unknown pc 0x198d66c
Tue, Sep 5 2023 4:13:36 pm | stack: frame={sp:0x7fff51347740, fp:0x0} stack=[0x7fff50b48cc0,0x7fff51347cd0)
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347640: 0x000000000041a2d9 <runtime.sysMapOS+0x0000000000000039> 0x0000000000000000
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347650: 0x00007f8965768000 0x000000000041a265 <runtime.sysHugePageOS+0x0000000000000065>
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347660: 0x00007f8967a00000 0x0000000000200000
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347670: 0x000000000000000e 0x00007f8900000000
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347680: 0x00007fff513476b0 0x000000000191899c
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347690: 0x00007f8967979000 0x000000000046c95e <runtime.callCgoMmap+0x000000000000003e>
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513476a0: 0x00007fff513476a8 0x00007f8967979000
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513476b0: 0x00007fff51347720 0x000000000191899c
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513476c0: 0x000000000040528f <runtime.mmap.func1+0x000000000000004f> 0x000000000046c95e <runtime.callCgoMmap+0x000000000000003e>
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513476d0: 0x00007fff513476d8 0x0000000000000007
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513476e0: 0x00007fff513477a0 0x000000000042c5cd <runtime.(*pageAlloc).update+0x00000000000003ad>
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513476f0: 0x00007f898c9f9c00 0x000000000191899c
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347700: 0x0000000000010000 0x000000000046c95e <runtime.callCgoMmap+0x000000000000003e>
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347710: 0x000000000198c9b0 0x000000001c000004
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347720: 0x000000000191b790 0x0000000000000000
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347730: 0x00007fff51347998 0x000000000198d65e
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347740: <0x0000000003520cd0 0x0000000000000000
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347750: 0x0000000000000010 0x0000000000000000
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347760: 0x0000000000000120 0x0000000000000110
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347770: 0x0000000000000004 0x0000000000000012
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347780: 0x0000000000000000 0x00000000019540d1
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347790: 0x00007f8965647640 0x00007fff51347a50
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513477a0: 0x00007fff513478be 0x00007fff513478bf
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513477b0: 0x00007f8965647640 0x0000000001925fa5
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513477c0: 0x000000000042fc65 <runtime.(*pallocData).allocRange+0x0000000000000045> 0x553c241bb9e61600
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513477d0: 0x0000000003c0d3c0 0x0000000000000006
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513477e0: 0x0000000003c0e650 0x0000000000000178
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff513477f0: 0x0000000003506fc0 0x000000000197dfd6
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347800: 0x0000000003538000 0x00000000004011d8
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347810: 0x0000000000000020 0x0000000000000000
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347820: 0x0000000000000000 0x553c241bb9e61600
Tue, Sep 5 2023 4:13:36 pm | 0x00007fff51347830: 0x00007fff51347900 0x00007f8965647640
Tue, Sep 5 2023 4:13:36 pm |  
Tue, Sep 5 2023 4:13:36 pm | goroutine 1 [running]:
Tue, Sep 5 2023 4:13:36 pm | runtime.systemstack_switch()
Tue, Sep 5 2023 4:13:36 pm | GOROOT/src/runtime/asm_amd64.s:459 fp=0xc000076780 sp=0xc000076778 pc=0x468940
Tue, Sep 5 2023 4:13:36 pm | runtime.main()
Tue, Sep 5 2023 4:13:36 pm | GOROOT/src/runtime/proc.go:170 +0x6d fp=0xc0000767e0 sp=0xc000076780 pc=0x43bb2d
Tue, Sep 5 2023 4:13:36 pm | runtime.goexit()
Tue, Sep 5 2023 4:13:36 pm | GOROOT/src/runtime/asm_amd64.s:1594 +0x1 fp=0xc0000767e8 sp=0xc0000767e0 pc=0x46ab61
Tue, Sep 5 2023 4:13:36 pm |  
Tue, Sep 5 2023 4:13:36 pm | rax 0x0
Tue, Sep 5 2023 4:13:36 pm | rbx 0x3c0d3c0
Tue, Sep 5 2023 4:13:36 pm | rcx 0x198d66c
Tue, Sep 5 2023 4:13:36 pm | rdx 0x6
Tue, Sep 5 2023 4:13:36 pm | rdi 0x1
Tue, Sep 5 2023 4:13:36 pm | rsi 0x1
Tue, Sep 5 2023 4:13:36 pm | rbp 0x1
Tue, Sep 5 2023 4:13:36 pm | rsp 0x7fff51347740
Tue, Sep 5 2023 4:13:36 pm | r8 0x7fff51347810
Tue, Sep 5 2023 4:13:36 pm | r9 0x33a9960
Tue, Sep 5 2023 4:13:36 pm | r10 0x8
Tue, Sep 5 2023 4:13:36 pm | r11 0x246
Tue, Sep 5 2023 4:13:36 pm | r12 0x6
Tue, Sep 5 2023 4:13:36 pm | r13 0x178
Tue, Sep 5 2023 4:13:36 pm | r14 0x3506fc0
Tue, Sep 5 2023 4:13:36 pm | r15 0x7f896576835b
Tue, Sep 5 2023 4:13:36 pm | rip 0x198d66c
Tue, Sep 5 2023 4:13:36 pm | rflags 0x246
Tue, Sep 5 2023 4:13:36 pm | cs 0x33

</body>
</html>

**Comment by mmuto118** [comment]
@vasiliy-ul 
Thank you for reply.
I will check the thead.
I understand v1.21.5+k3s1 is EOF and then try to deploy kubevirt operator in newer k3s version.

**Comment by oshoval** [comment]
This might be the reason
https://github.com/containers/skopeo/issues/1501#issuecomment-969235713

**Comment by oshoval** [comment]
https://github.com/oshoval/k3d_kubevirt
this uses k3d (which is based on k3s) to run kubevirt, in case it helps
