### ISSUE TITLE
How to graceful shutdown a vm?

### ISSUE THREAD

**Issue by Longchuanzheng** [kubevirt/kubevirt#10384]
**Is your feature request related to a problem? Please describe**:
We can use `virtctl soft-reboot` to reboot the vm instead of use `virtctl restart `. 
I also want to soft stop vm instead of `virtctl stop` which just delete vmi and pod.
I also find code like:
```
func (c *VirtLauncherClient) ShutdownVirtualMachine(vmi *v1.VirtualMachineInstance) error {
	return c.genericSendVMICmd("Shutdown", c.v1client.ShutdownVirtualMachine, vmi, &cmdv1.VirtualMachineOptions{})
}
```
in kubevirt.
But I am not sure weather we already have methods to graceful shutdown a vm.

**Describe the solution you'd like**:
I find docs https://github.com/kubevirt/kubevirt/blob/main/docs/graceful-shutdown.md

**Describe alternatives you've considered**:

**Additional context**:

**Comment by matthewei** [comment]
in fact that virt stop is a soft-shutdown command and you can set `terminationGragePeriodSeconds` depend on your vm.
but if you want to hard-stop the vm you can use the following cmd
`virtctl stop <vm> --grace-period=0 --force=true`
