### ISSUE TITLE
Fix COPYRIGHT

### ISSUE THREAD

**Issue by ahmetb** [kubevirt/kubevirt#104]
https://github.com/kubevirt/kubevirt/blob/edde6b4e27234197b235e88a9e06d28682a3d481/LICENSE#L190

this line should be updated.

**Comment by rmohr** [comment]
If I am not mistaken, this is only there to describe what you have to add to a file to properly mark it as apache licensed, right?

That reminds me that we need to add these headers to all our files. Thanks :+1:

**Comment by ahmetb** [comment]
Many projects just update that line instead of adding it to header of all files.

**Comment by fabiand** [comment]
True that not all projects are populating it. But I'll still provide a PR to fix it to have sane defaults.

**Comment by rmohr** [comment]
Merged. Thanks :cake:
