### ISSUE TITLE
MacOSX M1 Max compile kubevirt failed

### ISSUE THREAD

**Issue by aresnasa** [kubevirt/kubevirt#10403]
**What happened**:
docker login
mac has connected to gcr,
INFO: Build option --platforms has changed, discarding analysis cache.
ERROR: /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/io_bazel_rules_go/BUILD.bazel:86:17: While resolving toolchains for target @io_bazel_rules_go//:cgo_context_data: No matching toolchains found for types @bazel_tools//tools/cpp:toolchain_type. Maybe --incompatible_use_cc_configure_from_rules_cc has been flipped and there is no default C++ toolchain added in the WORKSPACE file? See https://github.com/bazelbuild/bazel/issues/10134 for details and migration instructions.
ERROR: Analysis of target '//:build-virtctl' failed; build aborted:
INFO: Elapsed time: 0.493s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 3131 targets configured)
FAILED: Build did NOT complete successfully (0 packages loaded, 3131 targets configured)
make: *** [bazel-build] Error 1
but bazel could not find cc toolchain

**What you expected to happen**:
on amd64 cpu arch got not problem

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): release-1.0
- Kubernetes version (use `kubectl version`): 1.27.2
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`):  22.6.0 Darwin Kernel Version 22.6.0: Wed Jul  5 22:22:05 PDT 2023; root:xnu-8796.141.3~6/RELEASE_ARM64_T6000 arm64
- Install tools: make gcc xcode-cli etc.
- Others: N/A

**Comment by zhlhahaha** [comment]
Sorry, we have not verified the build process on MacOS, and it is not in my recent plan. It would be good if you can have a native linux on Arm64 platform (Raspberry Pi 4 with ubuntu OS should work.)

**Comment by aresnasa** [comment]
ok,thanks,close issue

**Comment by zhlhahaha** [comment]
> ok,thanks,close issue

By the way, if you do not have a Arm64 platform, you can cross build Arm64 images and binaries on x86_64 platform.
```
export BUILD_ARCH=crossbuild-aarch64
export DOCKER_PREFIX=your_docker_repository
make bazel-build-images
make bazel-push-iamges
```
