### ISSUE TITLE
root device cgroup was writed with unexpect device

### ISSUE THREAD

**Issue by wangjihai** [kubevirt/kubevirt#10409]
Hi, I test vms with hotplug block disk, power on and off vms many times. some time later, vm cannot start, and reports "error setting cgroup config for procHooks process: failed to write \"b *:* m\"".   
![image](https://github.com/kubevirt/kubevirt/assets/30250443/c2eab36a-6963-4d15-818d-5db6942b5a0a)

debug and find virt-handler write "b 253:29 rwm" to /sys/fs/cgroup/devices/devices.deny, so it should deny pod of new vm write \"b *:* m\" to /sys/fs/cgroup/devices/.../devices.allow. 
![image](https://github.com/kubevirt/kubevirt/assets/30250443/1197f75b-bba6-4e90-9f82-925bbcf72aa6)

![image](https://github.com/kubevirt/kubevirt/assets/30250443/d2643aa8-828f-4b58-9295-4407d12ccb0f)

In-depth debugging, then find the libvirtd become zombie process  along with devices.deny error, and libvirtd escape to host.

from code view,  unmountBlockHotplugVolumes() func search pid of libvirtd according libvirt sock, then get cgroup path of pid of libvirtd.  when libvirtd escape to host, function return the root cgroup path, and not virt-launcher cgroup, so unmountBlockHotplugVolumes() change devices.deny file of the root cgroup.

My confusion is how libvirtd escape, my test env is kubevirt version 0.48, and cgroup version V1,  and  i guess kubevirt v1.0 maybe have the same issue, because the main mechanism looks consistent

**Environment**:
- KubeVirt version (use `virtctl version`): v0.48
- Kubernetes version (use `kubectl version`): v1.25.8
- VM or VMI specifications:  vm with hotplug block disk
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by awels** [comment]
So for KubeVirt 1.0 we are using cgroups v2, and there have been a bunch of fixes to disk hotplug. To do the allow/deny, we use chroot so maybe that is how it escapes?

**Comment by wangjihai** [comment]
libvirtd not escaped, but goto into zombie state.  zombie thread's cgroup is released, and thread cgroup is set with root cgroup.
