### ISSUE TITLE
ParallelMigrationsPerCluster have incorrect implementation logic

### ISSUE THREAD

**Issue by BugMosquito** [kubevirt/kubevirt#10415]
**What happened**:
parallelMigrationsPerCluster is described as follow(staging/src/kubevirt.io/api/core/v1/types_swagger_generated.go):

"parallelMigrationsPerCluster":      "ParallelMigrationsPerCluster is the total number of concurrent live migrations\nallowed cluster-wide. Defaults to 5",

 But i can migrate  virtualmachines less than 5 at the same time.  Actually, the total number of concurrent live migrations is 4 when parallelMigrationsPerCluster = 5,  The code is as follows：

![image](https://github.com/kubevirt/kubevirt/assets/16114525/560d2cb8-045d-49c6-ba23-baab863e23c5)

 
**What you expected to happen**:
I can migrate  5 virtualmachines   at the same time. 

**How to reproduce it (as minimally and precisely as possible)**:
migrate  virtualmachines numbers  more than 5 at the same time

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): latest
- Kubernetes version (use `kubectl version`): k3s version v1.25.7+k3s-e7fe07fd
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): centos7
- Kernel (e.g. `uname -a`): 5.10.167
- Install tools: N/A
- Others: N/A

**Comment by jean-edouard** [comment]
Does setting `parallelMigrationsPerCluster` to 1 allow 0 migration then? Should be easy to test.
The code looks correct to me though, unless the current migration attempt is counted as a running migration, which it shouldn't.
@vladikr FYI

**Comment by BugMosquito** [comment]
> Does setting `parallelMigrationsPerCluster` to 1 allow 0 migration then? Should be easy to test. The code looks correct to me though, unless the current migration attempt is counted as a running migration, which it shouldn't. @vladikr FYI

Yes，When I configured it to 1, the migration was stuck all the time。 so i think this is a problem。

“findRunningMigrations" get the number of migrations based on the virtv1.VirtualMachineInstanceMigration, which includes the ones to be migrated at this time.

**Comment by BugMosquito** [comment]
ParallelOutboundMigrationsPerNode are also such issues too

**Comment by acardace** [comment]
@BugMosquito I've checked the code and `findRunningMigrations()` correctly ignores migrations in pending state, I'm trying to test this as well.

**Comment by acardace** [comment]
@BugMosquito I tested KubeVirt main (59d9d7755dc406f4bd92f9e5dfb8ef64b7b1c149) and didn't experience this bug.

I set my KubeVirt like this:
```
spec:
  certificateRotateStrategy: {}
  configuration:
    migrations:
      parallelMigrationsPerCluster: 1
```
and I was able to migrate 1 VM at a time.

Can you re-check this and in case collect logs and relevant manifests?
