### ISSUE TITLE
Example yamls are not validated for correctness

### ISSUE THREAD

**Issue by booxter** [kubevirt/kubevirt#1041]
This is a follow-up to https://github.com/kubevirt/kubevirt/pull/1040 that fixes alpine machine template. To make sure there are no other issues in generated templates, we should make examples validation part of 'make generate' as well as CI. Specifically, we should validate that the generated example would pass corresponding API validators which are defined in https://github.com/kubevirt/kubevirt/tree/master/pkg/virt-api/validating-webhook

**Comment by fabiand** [comment]
Closing in favor of #955

**Comment by rmohr** [comment]
@fabiand this issue is about semantical correctness.

**Comment by fabiand** [comment]
Right.

@rmohr @booxter could you please add some more details to the issue description to specify what exactly should be validated.

**Comment by booxter** [comment]
Updated the description to specifically refer to API validation layer and code to leverage.

**Comment by rmohr** [comment]
@booxter we now have all examples in go structs (including the templates) and generate yaml. As a final step writing tests should now pretty easy.

**Comment by booxter** [comment]
@rmohr since you envisioned a more elaborate validation of examples via integration tests, should we reopen this issue, or should we create a new one for your suggested approach?

**Comment by rmohr** [comment]
@booxter I think we can reopen when we break them again. :+1:
