### ISSUE TITLE
use mactap get Cannot spawn a message bus without a machine-id

### ISSUE THREAD

**Issue by sunnoy** [kubevirt/kubevirt#10410]
**What happened**:

Follow the documentation https://kubevirt.io/user-guide/virtual_machines/interfaces_and_networks/#macvtap Error with mactap

```bash
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get session bus connection: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory","pos":"virGDBusGetSessionBus:126","subcomponent":"libvirt","thread":"34","timestamp":"2023-09-12T08:20:46.795000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get system bus connection: Could not connect: No such file or directory","pos":"virGDBusGetSystemBus:99","subcomponent":"libvirt","thread":"34","timestamp":"2023-09-12T08:20:46.795000Z"}
```

**What you expected to happen**:

vm runing

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`):   
- virtctl version
Client Version: version.Info{GitVersion:"v1.0.0", GitCommit:"579bb66545630d93b29d0399219aaa51c3f0a00b", GitTreeState:"clean", BuildDate:"2023-07-06T17:46:07Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v1.0.0", GitCommit:"579bb66545630d93b29d0399219aaa51c3f0a00b", GitTreeState:"clean", BuildDate:"2023-07-06T18:46:13Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes version (use `kubectl version`): N/A
- kubectl version
WARNING: This version information is deprecated and will be replaced with the output from kubectl version --short.  Use --output=yaml|json to get the full version.
Client Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4+k3s1", GitCommit:"36645e7311e9bdbbf2adb79ecd8bd68556bc86f6", GitTreeState:"clean", BuildDate:"2023-07-28T01:30:27Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v5.0.1
Server Version: version.Info{Major:"1", Minor:"27", GitVersion:"v1.27.4+k3s1", GitCommit:"36645e7311e9bdbbf2adb79ecd8bd68556bc86f6", GitTreeState:"clean", BuildDate:"2023-07-28T01:30:27Z", GoVersion:"go1.20.6", Compiler:"gc", Platform:"linux/amd64"}
- VM or VMI specifications: 
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- cat /etc/os-release
NAME="Anolis OS"
VERSION="8.8"
ID="anolis"
ID_LIKE="rhel fedora centos"
VERSION_ID="8.8"
PLATFORM_ID="platform:an8"
PRETTY_NAME="Anolis OS 8.8"
ANSI_COLOR="0;31"
HOME_URL="https://openanolis.cn/"
- Kernel (e.g. `uname -a`): N/A
- uname -a
Linux node2 5.10.134-13.an8.x86_64 #1 SMP Mon Jan 9 10:39:46 CST 2023 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: N/A
- Others: N/A

**Comment by BAMSHK** [comment]
![image](https://github.com/kubevirt/kubevirt/assets/40750078/7a592e91-85b5-45b3-a819-97f2bbd0d70a)

**Comment by xpivarc** [comment]
/close
This error can be safely ignored. It should be visible in any configuration.

**Comment by sunnoy** [comment]
Problem solved Because I'm using k3s and using the default flannle install, I should disable the default flannle install then the official flannle install method
kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml
