### ISSUE TITLE
Feature Request: option to disable Velero hook annotations

### ISSUE THREAD

**Issue by haslersn** [kubevirt/kubevirt#10422]
KubeVirt unconditionally adds the following two annotations to virt-launcher Pods:

```
post.hook.backup.velero.io/command: '["/usr/bin/virt-freezer", "--unfreeze",
        "--name", "dns01", "--namespace", "powerdns"]'
pre.hook.backup.velero.io/command: '["/usr/bin/virt-freezer", "--freeze", "--name",
        "dns01", "--namespace", "powerdns"]'
```

These are pre and post hooks for Velero backups. However, they are only required when taking a backup using file system backup. When using CSI snapshots instead, they might be required depending on the consistency guarantees of the storage backend. When taking no volume backups at all, then these hooks are absolutely not required (why would you wanna freeze writes to disk if the disk doesn't get backed up?).

We have some VMs where we don't take any volume backups, but Velero nonetheless runs these hooks, because Velero's pre and post hooks are independent of volume backups.

**Describe the solution you'd like**:

There should be a VMI option (and perhaps also a global option) to disable these annotations.

**Comment by mhenriks** [comment]
CSI snapshots have no consistency guarantees.  These backups help improve the situation when the VM is running the qemu guest agent.  If your VM is not running a guest agent they have no effect.

The hooks work by flushing all dirty buffers to disk and blocking all subsequent writes.  Read more about the process here [1].  The VM itself is not paused.  Only writes to disk.  The hooks also provide a way for the user to execute a pre/post freeze script.

If you are not snapshotting VM PVCs then the effect of invoking these hooks should be minimal.  But I can understand it may be undesirable to block I/O at all for certain workloads.

[1] https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.1/html/version_3_rest_api_guide/qemu_guest_agent_overview

**Comment by haslersn** [comment]
> CSI snapshots have no consistency guarantees.

Depending on the CSI driver there might be consistency guarantees. For instance, rook uses CephFS snapshots and they are crash-consistent.

**Comment by mhenriks** [comment]
> > CSI snapshots have no consistency guarantees.
> 
> Depending on the CSI driver there might be consistency guarantees. For instance, rook uses CephFS snapshots and they are crash-consistent.

I'm suspect there are backend config settings and mount options could give you a corrupted disk.  But maybe @nixpanic can guarantee that ceph csi snapshots are in fact bullet proof.

Nevertheless, even if csi snapshots are crash consistent, integrating with the guest agent allows for application consistent snapshots
