### ISSUE TITLE
ParaKubeVirtualization API

### ISSUE THREAD

**Issue by connorkuehl** [kubevirt/kubevirt#10427]
**Is your feature request related to a problem? Please describe**:

I have a use-case where an API that allows a KubeVirt VM to discover details about itself could be quite useful. In my case, the KubeVirt VMs can talk directly to the KubeVirt API for things like device hotplug. For that to happen, the guest needs to know its VMI name and the k8s namespace that it's in.

I noticed KubeVirt adds this information as the cloud-init `instance-id` (where it's in the form `vmi-name.namespace` -- `sudo cloud-init query v1`). However, that requires my guest OS to include and support cloud-init. So for guests that can't or won't support cloud-init, I'm not sure there's any programmatic way for the guest to discover this information about itself (without adding some additional automation somewhere in the cluster or the guest or both).

**Describe the solution you'd like**:

It would be cool if there was a "ParaKubeVirtualization" API, for example my KubeVirt VM could hit like a `whoami` endpoint, which could return the VMI yaml or a more reduced set of information including the VMI name and namespaces.

**Comment by alicefr** [comment]
@connorkuehl I'm not sure if a generic API is a good idea. What I mean is that we might not want to expose this kind of information to the VM.

Would be acceptable for you to generate a configmap together with the VM specification and use this? This could be something built on top of KubeVirt.

Another way could be that the qemu-guest-agent generate a file with the needed information. However, this approach has the same drawback as cloud-init that you need to install an additional tool inside the VM.

**Comment by xpivarc** [comment]
@connorkuehl @alicefr We do support a downwardAPI volume, you can have a look at an example test https://github.com/kubevirt/kubevirt/blob/main/tests/virtiofs/config.go#L232-L265

**Comment by connorkuehl** [comment]
Thanks! That looks fascinating but I don't think I can depend on every guest OS having a kernel with virtioFS support.

**Comment by xpivarc** [comment]
@connorkuehl It works with disk as well.
