### ISSUE TITLE
Move to quay for hosting images

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1044]
For a number of reasons I'm proposing to move to quay for image hosting:

- connection issues to dockerhub now and then
- connection speed issues to dockerhub now and then
- automatic server side cleanup of unused images

**Comment by fabiand** [comment]
`Failed to pull image "docker.io/kubevirt/virt-launcher:v0.9.3": rpc error: code = Unknown desc = Error response from daemon: received unexpected HTTP status: 503 Service Unavailable`

**Comment by fabiand** [comment]
Do we want to target this for the close future? Aka next release?

**Comment by rmohr** [comment]
Would be fine for me.
