### ISSUE TITLE
VMs definition under cluster/examples use images with devel tag and kubevirt prefix

### ISSUE THREAD

**Issue by cynepco3hahue** [kubevirt/kubevirt#1045]
We already had a discussion about `devel` tag, but if we want to leave `devel` tag we also need to change the prefix to `registry:5000/kubevirt/...` otherwise, it will not work.

**Comment by yuvalif** [comment]
i need this fix for PR #962. So, it was fixed in a commit: https://github.com/kubevirt/kubevirt/pull/962/commits/c81bacc894f7cba7f03cbaf19b4e41b5ea7f5e0e
note that both the generator and generated files were modified and checked in.

**Comment by cynepco3hahue** [comment]
@yuvalif I do not sure it correct approach, I believe we just must add `registry` under docker registries as part of CI pre-backed images

**Comment by fabiand** [comment]
Q: What's actually the problem? Why was this issue filed?

Then: CRIO is somewhat strict. Thus I am suggesting that we _always_ use the `<server>[:port]/<namespace>/<image>[:<tag>]` scheme.

IIUIC it should also help with this issue right?

@cynepco3hahue ?

**Comment by fabiand** [comment]
CRIO is somewhat strict. Thus I am suggesting that we _always_ use the `<server>[:port]/<namespace>/<image>[:<tag>]` scheme.

IIUIC it should also help with this issue right?

@cynepco3hahue ?

**Comment by cynepco3hahue** [comment]
Because currently under our examples we do not specify the server
```
- name: registryvolume
        registryDisk:
          image: kubevirt/cirros-registry-disk-demo:devel
```
@yuvalif added `registry:5000` to examples code generator

**Comment by fabiand** [comment]
So the issue is about looking in the correct registry in the dev flow, thanks.

**Comment by cynepco3hahue** [comment]
Fixed by https://github.com/kubevirt/kubevirt/pull/1108
