### ISSUE TITLE
Firmware.uuid will not be patched to remove if the targe vm is cloned from running vm

### ISSUE THREAD

**Issue by Longchuanzheng** [kubevirt/kubevirt#10467]
**What happened**:
When we clone a vm from a running vm, the target vm will get Spec.Template.Spec.Domain.Firmware.uuid from vmi no mater the Spec.Template.Spec.Domain.Firmware.uuid feild in source vm is setted. While when we clone a vm clone form a stop vm, no mater the source vm have setted Spec.Template.Spec.Domain.Firmware.uuid field the clone controller will patch to remove Firmware.uuid fielld for target vm.

**What you expected to happen**:
We need to be consistent about whether to retain source vm's uuid. I think our FirmwareUUIDPatches should generate to avoid target vm get source vm's uuid.

**How to reproduce it (as minimally and precisely as possible)**:
Clone a vm from a source vm at shutdown or startup.

**Additional context**:
I think this pr can solve this https://github.com/kubevirt/kubevirt/pull/10411.

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by matthewei** [comment]
so do you mean if you clone from a shutdown vm. we still need remove Firmware.uuid?

**Comment by Longchuanzheng** [comment]
@matthewei 
Hi, thank you for your attention, right now we have 4 cases:

case1: If we clone from a shutdown vm, source vm Spec.Template.Spec.Domain.Firmware.uuid is setted, we will remove it with generateFirmwareUUIDPatches. 
case2: If we clone from a shutdown vm,  source vm Spec.Template.Spec.Domain.Firmware.uuid is not setted. we will needn'tremove Firmware.uuid. 

So target vm will not get uuid from a shotdown source vm.

case3: If we clone from a running vm, source vm Spec.Template.Spec.Domain.Firmware.uuid is not setted. target vm will get uuid from source vmi (snapshotcontent will get Spec.Template.Spec from vmi in snapshot controller) and generateFirmwareUUIDPatches will not work because it generate patch with source vm right now. 
case4: If we clone from a running vm, Source vm have been setted Spec.Template.Spec.Domain.Firmware.uuid, generateFirmwareUUIDPatches will work and patch will remove Firmware.uuid for target vm.

So target vm will not remove uuid when clone from a running vm with Spec.Template.Spec.Domain.Firmware.uuid setted.

**Comment by Longchuanzheng** [comment]
This pr https://github.com/kubevirt/kubevirt/pull/10515 may solve the issue.
