### ISSUE TITLE
Export pod should create with defaultLimit and defaultRequest 

### ISSUE THREAD

**Issue by Longchuanzheng** [kubevirt/kubevirt#10468]
**Is your feature request related to a problem? Please describe**:
Export pod should create with defaultLimit and defaultRequest just like cdi upload pod.

**Describe the solution you'd like**:
Solution1: We can just set Limit and Requset when we create export pod.
Solution2: We can create a config like cdiconfig and get defaultLimit and defaultRequest when we create export pod.
**Describe alternatives you've considered**:

**Additional context**:

**Comment by Longchuanzheng** [comment]
I would like to be assigned to this issue.

**Comment by awels** [comment]
This is already done https://github.com/kubevirt/kubevirt/pull/10391
