### ISSUE TITLE
Document how to build and update the bazel builder container

### ISSUE THREAD

**Issue by cfilleke** [kubevirt/kubevirt#10494]
**Description**:
A developer may have need to re-build the bazel builder container image

**What you expected**:
There needs to be a document describing how to build the builder container for different architectures, discussing how to prepare the builder container build toolchain, how to modify the build scripts for different registry providers, how to update the dependencies in the builder, and how to publish it to a registry for further development use. 

**URL**:
There is no documentation for this; that's the problem. I would suggest a new markdown file in `kubevirt/docs/build-the-builder.md`.

**Additional context**:
Keeping the builder build toolchain, dependencies and container up to date, and ultimately making that build a part of the test-and-release process for KubeVirt is a way to avoid incorporating security vulnerabilities in the final KubeVirt product.

The current KubeVirt builder images need to ultimately be multi-arched to include s390x and ppc64le images built with consistent dependencies, addressed in a future issue.

**Comment by cfilleke** [comment]
One aspect that makes this documentation simpler is the fact that the build-the-builder scripts have now been parameterized in https://github.com/kubevirt/kubevirt/commit/965babf0a3cfaf300ce827ead36bfcbcac7e1fdb

**Comment by cfilleke** [comment]
@acardace and @EdDev have been assigned to review https://github.com/kubevirt/kubevirt/pull/10526 to solve this issue.

**Comment by EdDev** [comment]
I see the document was added already. Why is this issue still open?

**Comment by cfilleke** [comment]
Oh I'm sorry @EdDev -- we still have to document the CDI build container build, I had them conflated.  You're absolutely right!  /close
