### ISSUE TITLE
A mechinism to customize virt-launcher pod

### ISSUE THREAD

**Issue by hujun-open** [kubevirt/kubevirt#10502]
**Is your feature request related to a problem? Please describe**:
I have need to make some changes to VM guest's file system before VM is fully running, however the guest OS in my case doesn't support any of startup mechanism that kubevirt currently supports (Cloud-init,Ignition,Sysprep), in fact the guest OS is not even linux or windows.
so another approach would be using the hook sidecar container, but it seems sidecar container is not designed for such purpose and has no access to the compute container's filesystem. 

**Describe the solution you'd like**:
I hope kubevirt could have a mechanism to let user customize the virt-launcher pod, e.g. a yaml template, so that user could define any sidecar or init container. 

**Describe alternatives you've considered**:

**Additional context**:

**Comment by alicefr** [comment]
@hujun-open guestfs-tools might be a solution for you if you rely on PVCs, you could start experimenting with [virtctl guestfs](https://github.com/kubevirt/kubevirt/blob/main/docs/guestfs.md) command or [KubeVirt tekton tasks](https://github.com/kubevirt/kubevirt-tekton-tasks#examples)

**Comment by hujun-open** [comment]
> @hujun-open guestfs-tools might be a solution for you if you rely on PVCs, you could start experimenting with [virtctl guestfs](https://github.com/kubevirt/kubevirt/blob/main/docs/guestfs.md) command or [KubeVirt tekton tasks](https://github.com/kubevirt/kubevirt-tekton-tasks#examples)

I am aware guestfs-tools. and also there is qemu-nbd to mount/modify qcow2 image file, that is not an issue; the issue is I need to make changes to files on  ephemeral volume inside virt-launcher pod **before** VM is running. which is only available after virt-launcher pod is created; essentially a flow like following:
1. a VMI/virt-laucher pod is created
2. a script make some changes for files inside the qcow2 (the local COW image) file on  the ephemeral volume via guestfs-tools
3. the actual qemu VM starts, the guess OS uses the updated files on the ephemeral volume

I took a look at the Kubvirt tekton, but can't find which task could be executed at step-2 above

**Comment by alicefr** [comment]
> > @hujun-open guestfs-tools might be a solution for you if you rely on PVCs, you could start experimenting with [virtctl guestfs](https://github.com/kubevirt/kubevirt/blob/main/docs/guestfs.md) command or [KubeVirt tekton tasks](https://github.com/kubevirt/kubevirt-tekton-tasks#examples)
> 
> I am aware guestfs-tools. and also there is qemu-nbd to mount/modify qcow2 image file, that is not an issue; the issue is I need to make changes to files on ephemeral volume inside virt-launcher pod **before** VM is running. which is only available after virt-launcher pod is created; essentially a flow like following:
> 

Could you please be more precise about what you need to modify and which information you need? Generally, I don't think it is a good practice to modify the virt-launcher container. Maybe there is a way to work around your need, for example using config maps. 

> 3. the actual qemu VM starts, the guess OS uses the updated files on the ephemeral volume

What are here the ephemeral volumes? Are they private virt-launcher volumes?

> I took a look at the Kubvirt tekton, but can't find which task could be executed at step-2 above

Well, the tekton tasks are executed before the VM creation, so, AFAIU, this won't help you.

**Comment by hujun-open** [comment]
> Could you please be more precise about what you need to modify and which information you need? Generally, I don't think it is a good practice to modify the virt-launcher container. Maybe there is a way to work around your need, for example using config maps.

The guest OS in my case is a proprietary OS (not linux), I need to run many VM with this OS at the same time, when the OS boots up, it reads a config file under the root file system (e.g. /config.conf), and I need to customize that file for each VM; one setting that need to write to the config file is the pod's IP, which is only known after virt-launcher pod is created, that's why I have to customize the file at step2. and also I  can't use static assigned IP for the pod, that's just not feasible in some environment. 

I also checked kubevirt configmap support, however it seems to require guest OS support virtiofs which my guest OS doesn't, and I can't install any new application on it.  also it seems kubevirt configmap support can't project configmap to a file.


> 
> > 3. the actual qemu VM starts, the guess OS uses the updated files on the ephemeral volume
> 
> What are here the ephemeral volumes? Are they private virt-launcher volumes?


it is the mypvcdisk in following example:
```
metadata:
  name: testvmi-ephemeral-pvc
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
spec:
  domain:
    resources:
      requests:
        memory: 64M
    devices:
      disks:
      - name: mypvcdisk
        lun: {}
  volumes:
    - name: mypvcdisk
      ephemeral:
        persistentVolumeClaim:
          claimName: mypvc
```

**Comment by alicefr** [comment]
> The guest OS in my case is a proprietary OS (not linux), I need to run many VM with this OS at the same time, when the OS boots up, it reads a config file under the root file system (e.g. /config.conf), and I need to customize that file for each VM; one setting that need to write to the config file is the pod's IP, which is only known after virt-launcher pod is created, that's why I have to customize the file at step2. and also I can't use static assigned IP for the pod, that's just not feasible in some environment.
> 

Please, also check the support for [downwards metrics](https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#downwardmetrics)

> I also checked kubevirt configmap support, however it seems to require guest OS support virtiofs which my guest OS doesn't, and I can't install any new application on it. also it seems kubevirt configmap support can't project configmap to a file.
> 

We added the support for configmaps using virtiofs, but I think we still support the old behavior where kubevirt creates an ISO file with the configmaps exactly for the reason that not all the guest OSes support virtiofs. Would you mind checking it again?

**Comment by hujun-open** [comment]
> Please, also check the support for [downwards metrics](https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#downwardmetrics)
I did, it seems downward metrics are presented to VM in two ways, one as raw disk or as serial port, neither works for my case, since the guestOS only read config from /config.cfg, and I can't make OS read from anything else. 
 
> We added the support for configmaps using virtiofs, but I think we still support the old behavior where kubevirt creates an ISO file with the configmaps exactly for the reason that not all the guest OSes support virtiofs. Would you mind checking it again?

again, doesn't work since guest OS boot loader only read /config.cfg on the same disk of boot loader, it can't read another file on different disk 

I guess I am out of luck here, I know my case is a niche case, however allowing user to customize the pod would be a "last-resort" mechanism to cover such niche cases. 

Thanks anyway even though it didn't workout, at least I learned some other kubevirt mechanisms

**Comment by alicefr** [comment]
> > Please, also check the support for [downwards metrics](https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#downwardmetrics)
> 
> I did, it seems downward metrics are presented to VM in two ways, one as raw disk or as serial port, neither works for my case, since the guestOS only read config from /config.cfg, and I can't make OS read from anything else.
> 

Ok, maybe a possible solution would be to use [QEMU firmware configuration ](https://www.qemu.org/docs/master/specs/fw_cfg.html)  plus a configmap that will mount as a file inside the pod. However, this would probably require some changes in KubeVirt, out of my mind, I don't think we support this option.

> > We added the support for configmaps using virtiofs, but I think we still support the old behavior where kubevirt creates an ISO file with the configmaps exactly for the reason that not all the guest OSes support virtiofs. Would you mind checking it again?
> 
> again, doesn't work since guest OS boot loader only read /config.cfg on the same disk of boot loader, it can't read another file on different disk
> 
> I guess I am out of luck here, I know my case is a niche case, however allowing user to customize the pod would be a "last-resort" mechanism to cover such niche cases.
> 

I still think there is another solution :)

> Thanks anyway even though it didn't workout, at least I learned some other kubevirt mechanisms

**Comment by hujun-open** [comment]
> Otherwise, there is this unmerged PR #6935 from @jean-edouard that does something similar to what you are asking

Thanks for the tip, will check that out

**Comment by galbeniluz** [comment]
Hi @hujun-open, did you find a solution? we have similar requirements and looking for a solution

**Comment by hujun-open** [comment]
> Hi @hujun-open, did you find a solution? we have similar requirements and looking for a solution

no, I worked around the issue by  static IP assignment  + creating qcow2 file with correct config file; however this workaround is quite limited...
