### ISSUE TITLE
Cannot power off a VM in phase: failed

### ISSUE THREAD

**Issue by vatsalparekh** [kubevirt/kubevirt#1052]
If a VM is powered on, but in `phase: failed` (which means not actually powered on?), and currently as we see it as Powered On in ManageIQ, if we try to Power it off from manageiq, it just stays there as Powered on in ManageIQ, and in `vms` on openshift.

@pkliczewski suggests this is on kubevirt side

**Comment by rmohr** [comment]
@vatsalparekh can you please posed the corresponding VirtualMachine and OfflineVirtualMachine objects?

**Comment by rmohr** [comment]
Also which version of KubeVirt are you using?

**Comment by vatsalparekh** [comment]
@rmohr 
This VM's scheduling failed was mainly when openshift node was down, and make the cluster up again

```
[fedora@vparekh-automation-provider ~]$ oc get vms test -n default -o yaml
apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachine
metadata:
  annotations:
    presets.virtualmachines.kubevirt.io/presets-applied: kubevirt.io/v1alpha1
  clusterName: ""
  creationTimestamp: 2018-05-21T11:45:38Z
  deletionGracePeriodSeconds: 0
  deletionTimestamp: 2018-05-22T06:23:34Z
  finalizers:
  - foregroundDeleteVirtualMachine
  generateName: test
  generation: 0
  labels:
    kubevirt.io/nodeName: localhost
  name: test
  namespace: default
  ownerReferences:
  - apiVersion: kubevirt.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: OfflineVirtualMachine
    name: test
    uid: 073661be-58e7-11e8-9971-fa163ed3a8d3
  resourceVersion: "82050"
  selfLink: /apis/kubevirt.io/v1alpha1/namespaces/default/virtualmachines/test
  uid: 7afe1ec5-5cec-11e8-9128-fa163ed3a8d3
spec:
  domain:
    cpu:
      cores: 4
    devices:
      disks:
      - disk: {}
        name: registrydisk
        volumeName: registryvolume
      - disk: {}
        name: cloudinitdisk
        volumeName: cloudinitvolume
    firmware:
      uuid: feec480d-31a1-59fa-9199-a330c83aa404
    machine:
      type: q35
    resources:
      requests:
        memory: 1Gi
  volumes:
  - name: registryvolume
    registryDisk:
      image: kubevirt/fedora-cloud-registry-disk-demo:latest
  - cloudInitNoCloud:
      userDataBase64: I2Nsb3VkLWNvbmZpZwpwYXNzd29yZDogYXRvbWljCnNzaF9wd2F1dGg6IFRydWUKY2hwYXNzd2Q6IHsgZXhwaXJlOiBGYWxzZSB9Cg==
    name: cloudinitvolume
status:
  interfaces:
  - ipAddress: 172.17.0.10
  nodeName: localhost
  phase: Failed
```
```
[fedora@vparekh-automation-provider ~]$ oc get ovms test -n default -o yaml
apiVersion: kubevirt.io/v1alpha1
kind: OfflineVirtualMachine
metadata:
  clusterName: ""
  creationTimestamp: 2018-05-16T08:56:31Z
  generation: 0
  labels:
    kubevirt.io/os: rhel-7
  name: test
  namespace: default
  resourceVersion: "80579"
  selfLink: /apis/kubevirt.io/v1alpha1/namespaces/default/offlinevirtualmachines/test
  uid: 073661be-58e7-11e8-9971-fa163ed3a8d3
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - disk: {}
            name: registrydisk
            volumeName: registryvolume
          - disk: {}
            name: cloudinitdisk
            volumeName: cloudinitvolume
        machine:
          type: q35
        resources:
          requests:
            memory: 1Gi
      volumes:
      - name: registryvolume
        registryDisk:
          image: kubevirt/fedora-cloud-registry-disk-demo:latest
      - cloudInitNoCloud:
          userDataBase64: I2Nsb3VkLWNvbmZpZwpwYXNzd29yZDogYXRvbWljCnNzaF9wd2F1dGg6IFRydWUKY2hwYXNzd2Q6IHsgZXhwaXJlOiBGYWxzZSB9Cg==
        name: cloudinitvolume
status:
  created: true
```
kubevirt version was v0.5.0

**Comment by rmohr** [comment]
@vatsalparekh the OfflineVirtualMachine shows that the VirtualMachine exists (`spec.created=true`). It does not show it as ready (`spec.ready=true` would need to be set). That means If a node goes down, the pod where the vm runs in goes to "unknown" state. That means that the system does not know 100% if the vm is down or not. That blocks the deletion of  the VirtualMachine (as you can see OfflineVirtualMachine already marked the VirtualMachine for deletion: `deletionTimestamp: 2018-05-22T06:23:34Z`). So as soon as you remove the pod in unknown state, the deletion of the virtual machine is unblocked and OfflineVirtualMachine will create a new instance of VirtualMachine.

We need to work on propagating the Pod state in a more user-friendly way to the vm state so that it is easier to see why things are not proceeding (e.g. registry disk image not found, node down, ...) but at least the implemented parts behave like expected.

**Comment by fabiand** [comment]
@rmohr could you please file two bugs:
- propagating the pod state
- documenting this behavior in the user-guide

Should there actually be another hint to tell the user what to do, or how to find more information sbaout these situations?

**Comment by fabiand** [comment]
The implication is actually as follows:

- VMI will not be removed
- VM can thus not be started anymore

**Comment by fabiand** [comment]
@rmohr is this still an issue?
