### ISSUE TITLE
seccompProfile and AppArmor issue with kubevirt on a private cluster

### ISSUE THREAD

**Issue by wexmaster** [kubevirt/kubevirt#10528]
Hi, I am trying to use kubervit but it is very difficult for me to solve the AppArmor part in Ubuntu in my Kubernete Cluster and I can only start the services if I edit kubevirt-operator.yaml and change RuntimeDefault to Unconfined and then do the same
kubectl edit deploy virt-controller -n kubevirt
kubectl edit deploy virt-api -n kubevirt
and I change RuntimeDefault to Unconfined and so I can start kubevirt

some of the PODs do not start and have an error

```
kubectl get pod -n kubevirt
NAME                               READY   STATUS             RESTARTS        AGE
virt-api-684c89d79f-f69j8          0/1     CrashLoopBackOff   13 (59s ago)    42m
virt-api-7cdb555ff-2pmcc           1/1     Running            0               43m
virt-api-7cdb555ff-xf4pb           1/1     Running            0               44m
virt-controller-597c8f4d67-vp867   0/1     CrashLoopBackOff   17 (3m ago)     65m
virt-controller-77bd655888-htv9d   0/1     CrashLoopBackOff   9 (4m11s ago)   25m
virt-controller-78b65db596-n5vjb   1/1     Running            0               65m
virt-handler-rtzxj                 1/1     Running            0               67m
virt-operator-588bf785d4-qwswg     1/1     Running            0               66m
virt-operator-588bf785d4-vc2hp     1/1     Running            0               67m
```

The known POD error does not have permissions:

```
runtime/cgo: pthread_create failed: Operation not permitted
SIGABRT: abort
PC=0x1b16e4c m=0 sigcode=18446744073709551610

goroutine 0 [idle]:
runtime: g 0: unknown pc 0x1b16e4c
stack: frame={sp:0x7ffe69a9ed40, fp:0x0} stack=[0x7ffe692a02c0,0x7ffe69a9f2d0)
0x00007ffe69a9ec40: 0x000000000041a439 <runtime.sysMapOS+0x0000000000000039> 0x0000000000000000
0x00007ffe69a9ec50: 0x00007f9b759e1000 0x000000000041a3c5 <runtime.sysHugePageOS+0x0000000000000065>
0x00007ffe69a9ec60: 0x00007f9b77c00000 0x0000000000200000
0x00007ffe69a9ec70: 0x000000000000000e 0x00007f9b00000000
0x00007ffe69a9ec80: 0x00007ffe69a9ecb0 0x0000000001aa223c
0x00007ffe69a9ec90: 0x00007f9b77bf2000 0x000000000046ea7e <runtime.callCgoMmap+0x000000000000003e>
0x00007ffe69a9eca0: 0x00007ffe69a9eca8 0x00007f9b77bf2000...
....
...
```

I have followed the guide https://kubevirt.io/user-guide/operations/installation/ although my Kubernete cluster is private

```
NAME        STATUS   ROLES           AGE    VERSION   INTERNAL-IP    EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
arg012xxx   Ready    <none>          255d   v1.25.4   x.x.x.x   <none>        Ubuntu 20.04.2 LTS   5.4.0-146-generic   containerd://1.6.22
arg012xxx   Ready    <none>          255d   v1.25.4   x.x.x.x   <none>        Ubuntu 20.04.2 LTS   5.4.0-162-generic   containerd://1.2.13
arg012xxx   Ready    <none>          219d   v1.25.4   x.x.x.x   <none>        Ubuntu 20.04.2 LTS   5.4.0-149-generic   containerd://1.2.13
arg012xxx   Ready    <none>          15d    v1.25.4   x.x.x.x   <none>        Ubuntu 20.04.6 LTS   5.4.0-164-generic   containerd://1.2.13
arg012xxx   Ready    <none>          17d    v1.25.4   x.x.x.x   <none>        Ubuntu 20.04.6 LTS   5.4.0-144-generic   containerd://1.2.13
arg042xxx   Ready    <none>          244d   v1.25.4   x.x.x.x    <none>        Ubuntu 20.04.5 LTS   5.4.0-162-generic   containerd://1.6.8
arg042xxx   Ready    control-plane   255d   v1.25.4   x.x.x.x   <none>        Ubuntu 20.04.2 LTS   5.4.0-163-generic   containerd://1.6.24
```

My question is simple: how can I make kubevirt work without editing the Deploynment that it generates by default with
```
seccompProfile:
              type: RuntimeDefault
```

and may it always be

```
seccompProfile:
              type: Unconfined

```

Or what happened I can continue and researched enough but I can't find a simple solution so I would like to know if this is feasible using it in a private cluster.

**Comment by alicefr** [comment]
@wexmaster do you know which syscall is causing the troubles? I think if you describe the pod you should be able to see it. We could either add it to the kubevirt seccomp profile or you could create your own and use it for kubevirt (see: https://github.com/kubevirt/kubevirt/pull/8917).

/cc @xpivarc

**Comment by wexmaster** [comment]
Hello, it is a similar problem to the issues you share but creating a profile in apparmo but it does not indicate which profile is recommended or how to implement it. I am going to study the issuses that you share but this also happens with other tools like https://github.com/kubevirt/containerized-data-importer/blob/main/README.md the ISO cannot be imported due to the same seccomp problem and permissions

**Comment by alicefr** [comment]
@wexmaster are you using docker? If so can, you upgrade as suggested in the issue (https://github.com/kubevirt/kubevirt/issues/9540#issuecomment-1491346745)?

**Comment by wexmaster** [comment]
Yes @alicefr Docker 19.03.11 containerd 1.6.24 Kubernet v1.25.4, OK I read!

**Comment by wexmaster** [comment]
The solution:

Update Docker 19.03.11 to 24.0.6-1 **Now Working!** Thanks @alicefr

**Comment by wexmaster** [comment]
The proyect working Centos and Centreon in Kubectl!! 

<img width="1543" alt="image" src="https://github.com/kubevirt/kubevirt/assets/70749863/e4f61943-ef7f-4c03-9ce1-6228c515f478">
