### ISSUE TITLE
Qemu-Guest-Agent service can not start on windows7 vm

### ISSUE THREAD

**Issue by liyang516** [kubevirt/kubevirt#10548]
**What happened**:
I make a windows7 qcow2 image, and install virtio & qga inside，then use this qcow2 image file， create a vm.
When the vm start， I found the qga service can not autostart，and when I start the service ，it start failed and occur a error.

![image](https://github.com/kubevirt/kubevirt/assets/35557835/e43f77cf-6b16-4dbb-b028-ec87cc6922aa)

**What you expected to happen**:
Qemu-Guest-Agent could autostart on windows7 vm

**Environment**:
- KubeVirt version : v0.59.0
- Kubernetes version :  v1.22.6+rke2r1
- VM or VMI specifications: N/A
```shell
apiVersion: kubevirt.io/v1
kind: VirtualMachine
  name: xxq
  namespace: xcloud-default
spec:
  dataVolumeTemplates:
  - metadata:
      name: xxq-rootdisk
      namespace: xcloud-default
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 30Gi
        storageClassName: csi-rbd-sc
        volumeMode: Block
      source:
        pvc:
          name: windows7
          namespace: xcloud
  runStrategy: Always
  template:
    spec:
      dnsConfig:
        nameservers:
        - 8.8.8.8
      dnsPolicy: None
      domain:
        cpu:
          cores: 4
          sockets: 1
          threads: 1
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: scsi
            name: rootdisk
          interfaces:
          - bridge: {}
            macAddress: fa:16:5d:b7:1b:36
            name: eth0
        machine:
          type: q35
        memory:
          guest: 8Gi
        resources: {}
      networks:
      - multus:
          default: true
          networkName: xcloud-default/xxq-nad-net1-eth0
        name: eth0
      nodeSelector:
        kubernetes.io/arch: amd64
      terminationGracePeriodSeconds: 0
      volumes:
      - dataVolume:
          name: xxq-rootdisk
        name: rootdisk
      - cloudInitConfigDrive:
          userData: '#cloud-config'
        name: cloudinitvolume
``` 
- OS : Ubuntu 22.04 LTS
- Kernel: 5.15.0-84-generic
- Install tools: N/A

**Other test**:
1、I use the same qcow2 file, launch a vm on OpenStack(Train) platform，vm qga agent could autostart
2、I create a windows10 qcow2 image，and create a vm on my kubevirt env，this vm qga service could autostart
So I don't know what the problem is. Here is my guess：
- qemu versoin：kubevirt use  7.2.0，openstack use 2.12.0
- xml field：kubevirt use q35 machine type，openstack use pc-i440fx-rhel7.6.0 machine type
- os system：windows7 os not support some xml config，but I don't know exactly what it is

**Comment by dhiller** [comment]
@liyang516 could you translate the error message for us so that we know what is happening there?

**Comment by liyang516** [comment]
> translate the error message for us so that we
@dhiller 
Error message means:
Windows cannot start QEMU Guest Agent Service on this computer.
Error 1067: Process terminated unexpectedly

**Comment by liyang516** [comment]
![image](https://github.com/kubevirt/kubevirt/assets/35557835/62884e12-94c1-42f5-94d0-a2c4155a0b1a)

**Comment by xpivarc** [comment]
Do I understand you correctly that this same Windows image works for you on Openstack?

Is there any log for the failed service?
