### ISSUE TITLE
Virtual machines cannot be meshed with Linkerd

### ISSUE THREAD

**Issue by bc185174** [kubevirt/kubevirt#10556]
**What happened**:

Currently, virtual machines (and cdi importer pods) cannot be meshed with Linkerd. The problem is the life cycle of sidecar containers and is something [Kubernetes is looking to address](https://kubernetes.io/blog/2023/08/25/native-sidecar-containers/). It is currently feature gated and not GA. AFAIK, Istio suffers the same problem, because a k8s `Job` is not considered complete until all containers have stopped running. 

For the CDI pods, the pods will continue to run indefinitely once the `importer` container has completed.

```
linkerd-proxy:
...
    State:          Running
      Started:      Mon, 02 Oct 2023 11:27:55 +0000
    Ready:          True
...
```

As for the `virt-launcher`, the pods terminates almost immediately and becomes `NotReady`.

```
NAME                               READY   STATUS     RESTARTS   AGE
virt-launcher-windows-vm-1-nmbhc   2/3     NotReady   0          54s
```

```
Containers:
  linkerd-proxy:
...
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Mon, 02 Oct 2023 10:37:27 +0000
      Finished:     Mon, 02 Oct 2023 10:38:02 +0000
...
```

**What you expected to happen**:

The linkerd-proxy side car container should not be shutdown unless the `virt-launcher` container is brought down.

Any k8s Jobs should call `curl -X POST http://localhost:4191/shutdown` on completion of the main container (if the `linkerd-proxy` container is present).

**How to reproduce it (as minimally and precisely as possible)**:

Deploy Linkerd as per https://linkerd.io/2.14/tasks/install-helm/ and attempt to mesh a basic VM that downloads the disk image through a container image (CDI).

To replicate the issue with the virt-launcher pod, I'd suggest unmeshing the VM and allow the importer to download and unpack the disk image to the PVC. Following this, mesh the VM again, and start it back up.

**Additional context**:

I can raise an issue on cdi project but just interested to hear how this is handled with `Istio` (if an issue). One way to address this in the interim is for the importer pod to call `curl -X POST http://localhost:4191/shutdown` on completion (as per the [docs](https://linkerd.io/2.14/tasks/graceful-shutdown/#graceful-shutdown-of-job-and-cronjob-resources)).

For the `virt-launcher` pod, the `linkerd-proxy` is receiving a SIGTERM. It is unclear what is causing the shutdown but all other meshed pods are running as expected. This suggests something under the hood with KubeVirt is triggering the SIGTERM on the linkerd proxy but any explanation on this would be appreciated.

```
{"timestamp":"[    31.929443s]","level":"INFO","fields":{"message":"received SIGTERM, starting shutdown"},"target":"linkerd_proxy::signal","threadId":"ThreadId(1)"}
{"timestamp":"[    31.929486s]","level":"INFO","fields":{"message":"Received shutdown signal"},"target":"linkerd2_proxy","threadId":"ThreadId(1)"}
```

**Environment**:
- KubeVirt version (use `virtctl version`): v1.0.0
- Kubernetes version (use `kubectl version`): v1.26.7
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by EdDev** [comment]
For KubeVirt (and not CDI), the virt-launcher pod lifecycle is controlled by the VMI controller (created, mutated and eventually deleted).
Therefore, I am unclear how this problem can ever be relevant to kubevirt pods.

I am not familiar with the CDI import pods, it may be more efficient to raise it on their project directly.
I do know that in many scenarios we find ourself needing for a garbage collection controller, be in native k8s or a custom one created for a specific cleaning task. Native k8s solutions with gc are usually utilizing ownership relations between components.

**Comment by bc185174** [comment]
Created separate issue on CDI project for that pod.

As for the `virt-launcher` pod and meshing it, I nailed it down to the liveness probe failing on linkerd-proxy:

```
  Warning  Unhealthy       17m                kubelet            Readiness probe failed: Get "http://100.127.87.100:4191/ready": dial tcp 100.127.87.100:4191: connect: no route to host
  Warning  Unhealthy       17m                kubelet            Liveness probe failed: Get "http://100.127.87.100:4191/live": dial tcp 100.127.87.100:4191: connect: no route to host
  Warning  Unhealthy       17m                kubelet            Liveness probe failed: Get "http://100.127.87.100:4191/live": context deadline exceeded (Client.Timeout exceeded while awaiting headers)
  Warning  Unhealthy       17m                kubelet            Liveness probe failed: Get "http://100.127.87.100:4191/live": dial tcp 100.127.87.100:4191: i/o timeout (Client.Timeout exceeded while awaiting headers)
  Normal   Killing         17m                kubelet            Container linkerd-proxy failed liveness probe
```

Restarted the VM and tried exec'ing into the pod and see similar behaviour:

```bash
k exec -ti -n windows-vm virt-launcher-windows-vm-8-njv56 -- curl localhost:4191/ready
curl: (7) Failed to connect to localhost port 4191: No route to host
command terminated with exit code 7
k exec -ti -n windows-vm virt-launcher-windows-vm-8-njv56 -- curl localhost:4191/ready
curl: (7) Failed to connect to localhost port 4191: Connection refused
```

Not clear why this is the case. Any ideas on where to look next?

**Comment by bc185174** [comment]
Adding the annotation `sidecar.istio.io/inject: "true"` as per https://kubevirt.io/user-guide/virtual_machines/istio_service_mesh/#istio-sidecar-is-not-ready has resolved the issue. 

Further testing, the interface on the guest was down and couldn't connect to the WAN. The traffic was being dropped by linkerd since the client IP was that of the bridge interface `10.0.2.1` and not the pod IP. The only way around this was to add `config.linkerd.io/skip-subnets: 10.0.2.0/24` annotation to the VM; however, this means that the VM can only ever be an unauthenticated client. I added an SNAT rule to change the source IP of the traffic outbound from the `k6t-eth0` interface but still hit the same problem.

@EdDev was this problem ever found with istio?

**Comment by fabiand** [comment]
@alonakaplan @EdDev would this be addressed with the passt binding?

On Wednesday, February 21, 2024, kubevirt-bot ***@***.***>
wrote:
> Issues go stale after 90d of inactivity.
> Mark the issue as fresh with /remove-lifecycle stale.
> Stale issues rot after an additional 30d of inactivity and eventually
close.
>
> If this issue is safe to close now please do so with /close.
>
> /lifecycle stale
>
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you are subscribed to this thread.<
https://ci4.googleusercontent.com/proxy/I_xH2KkOLaYghBEInE4EQf3zMFn3K2Zt7Drydc51PTJ0RrKekC4gH0IyyUzR2CtUOx6nPtQg8jHQ0uZ4cbktIhGcHrliXXjfVY_YROJVNMfS39rzm7cJg4UQcKgpK7mP3gGZWQD6euEMf9ul4sAH5czVV8pEbljEl1dof766BWW_vOvI-h8aQ140qyFMi0_E8He0WbpbvEoAVB2MvwYpwcRwdw7JM0o6SH-SVSiEqbLUz1hVgQ=s0-d-e1-ft#https://github.com/notifications/beacon/AAAUMAH4ZQGHARHYJFSG7YTYUYBFBA5CNFSM6AAAAAA54KMSSCWGG33NNVSW45C7OR4XAZNMJFZXG5LFINXW23LFNZ2KUY3PNVWWK3TUL5UWJTTUUJHS4.gif>Message
ID: ***@***.***>

**Comment by bc185174** [comment]
It does get resolved with Passt interface; however, there is no current support for live migration or afaik multiple interfaces. Is that correct?

**Comment by EdDev** [comment]
> Further testing, the interface on the guest was down and couldn't connect to the WAN. The traffic was being dropped by linkerd since the client IP was that of the bridge interface `10.0.2.1` and not the pod IP. The only way around this was to add `config.linkerd.io/skip-subnets: 10.0.2.0/24` annotation to the VM; however, this means that the VM can only ever be an unauthenticated client. I added an SNAT rule to change the source IP of the traffic outbound from the `k6t-eth0` interface but still hit the same problem.
> 
> @EdDev was this problem ever found with istio?

We add istio nftable rules and it works fine.
The traffic coming from the guest is redirected to the pod stack, i.e. istio and from there it is transmitted out through the masquerade rules.

You can review the exact rules we add for istio here: https://github.com/kubevirt/kubevirt/blob/main/pkg/network/setup/netpod/masquerade/masquerade_test.go#L342

This is relevant only for masquerade binding at the moment.

**Comment by EdDev** [comment]
@AlonaKaplan , do we need to add istio support for Passt in the same manner?

**Comment by AlonaKaplan** [comment]
> @AlonaKaplan , do we need to add istio support for Passt in the same manner?

It should work for passt out of the box.
Unlike masquerade, passt doesn't touch the virt-launcher pod networking.
There is no extra bridge and the nftables are untouched.
There traffic is sent to and from the guest via the passt process. So it should be "native" for service mesh sidecars.

**Comment by bc185174** [comment]
I've tested and verified passt works with linkerd mesh. Since `passt` will have migration support in `v1.2`, happy to close this issue as resolved.

**Comment by bc185174** [comment]
I do have a question about the `virt-handler` pod. It creates a TCP connection over unix sockets to facilitate the migration proxy right? And that traffic originates from the source VM, to the destination VM?

AFAIK, the port which that traffic is served on is random, how do you mesh this traffic with istio/linkerd? Since the port is undefined (not defined as `containerPort`), you cannot create policies to allow this traffic over the mesh?

**Comment by EdDev** [comment]
> I do have a question about the `virt-handler` pod. It creates a TCP connection over unix sockets to facilitate the migration proxy right? And that traffic originates from the source VM `virt-handler`, to the destination VM `virt-handler` pods?
> 
> AFAIK, the port which that traffic is served on is random, how do you mesh this traffic with istio/linkerd? Since the port is undefined (not defined as `containerPort`), you cannot create policies to allow this traffic over the mesh?

Between the virt-launcher pod to the virt-hander pod it is UNIX sockets, then it goes through TCP sockets between the virt-handlers.
I am not sure how mesh works there, if at all. But perhaps @jean-edouard can add some insights on it.
