### ISSUE TITLE
How to passthrough all physical functions of a GPU into vm ? 

### ISSUE THREAD

**Issue by chenxinlong** [kubevirt/kubevirt#10565]
Hi team, I have a GPU as below(`lspci`) : 
```
86:00.0 VGA compatible controller: NVIDIA Corporation TU104 [GeForce RTX 2060] (rev a1)
86:00.1 Audio device: NVIDIA Corporation TU104 HD Audio Controller (rev a1)
86:00.2 USB controller: NVIDIA Corporation TU104 USB 3.1 Host Controller (rev a1)
86:00.3 Serial bus controller [0c80]: NVIDIA Corporation TU104 USB Type-C UCSI Controller (rev a1)
```

Currently I can assign the VGA compatible controller (`86:00.0`) to vm by construct the related environment to virt-launcher pod (using device plugin) like below : 
```
PCI_RESOURCE_<GPU_NAME>=0000:86:00.0
```

But how should I passthrough all physical functions of this GPU(`86:00.0` ~ `86:00.3`) into vm ?

**Comment by matthewei** [comment]
is there any progress for that?

**Comment by chenxinlong** [comment]
> is there any progress for that?

@matthewei Currently I'm using the hooksidecar to manipulating the domain xml as workaround.

**Comment by chenxinlong** [comment]
Hi, any progress here?
