### ISSUE TITLE
MIG backed vGPU

### ISSUE THREAD

**Issue by pomodorox** [kubevirt/kubevirt#10575]
Hello, I recently learnt from the [Nvidia doc](https://docs.nvidia.com/datacenter/cloud-native/gpu-operator/latest/gpu-operator-kubevirt.html#assumptions-constraints-and-dependencies) that MIG-backed vGPU is not supported by Kubevirt. I was wondering if you could share some context why it's not supported. Thank you.

**Comment by xpivarc** [comment]
@rthallisey can you shed some light here

**Comment by rthallisey** [comment]
Right it's not currently supported.   However it's something that we can look to support in the future.

I haven't tested it but it's possible MIG mode may already work with the device plugin.  If you follow the docs in https://docs.nvidia.com/datacenter/tesla/mig-user-guide/index.html#enable-mig-mode to setup a MIG device, the device plugin might play along.  Try it and let us know :).

**Comment by rthallisey** [comment]
Also @pomodorox, please file an issue under https://github.com/NVIDIA/kubevirt-gpu-device-plugin/issues and we can look into this.

**Comment by pomodorox** [comment]
Hi @rthallisey, thanks for the update. I have tried the Nvidia K8s device plugin and the MIG manager and it works -- I was able to create MIG devices using MIG manager and create GPU workloads consuming the MIG devices. I guess the thing unclear to me is why we do not support vGPU over MIG for Kubevirt. Was that a limitation from Kubevirt or Nvidia?

**Comment by rthallisey** [comment]
I think the only barrier was that it hadn't been tested/validated on kubevirt.  File an issue in the kubevirt gpu device plugin and I can look into getting this addressed.
