### ISSUE TITLE
VM boot breaks by selinux relable 

### ISSUE THREAD

**Issue by Viste** [kubevirt/kubevirt#10572]
**What happened**:
All VMs terminates after run because of can't start tap0:
`{"component":"virt-handler","level":"info","msg":"Generic Allocate: resourceName: tun","pos":"generic_device.go:242","timestamp":"2023-10-16T11:53:30.119235Z"} {"component":"virt-handler","level":"info","msg":"Generic Allocate: request: [&ContainerAllocateRequest{DevicesIDs:[tun391],}]","pos":"generic_device.go:243","timestamp":"2023-10-16T11:53:30.119333Z"} {"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled | Domain does not exist","name":"core-build-win01","namespace":"default","pos":"vm.go:1759","timestamp":"2023-10-16T11:53:32.560467Z","uid":"09415d56-18bd-4c4b-ab1e-da693a96630f"} {"component":"virt-handler","kind":"","level":"info","msg":"mounting kernel artifacts","name":"core-build-win01","namespace":"default","pos":"mount.go:405","timestamp":"2023-10-16T11:53:32.563206Z","uid":"09415d56-18bd-4c4b-ab1e-da693a96630f"} {"component":"virt-handler","kind":"","level":"info","msg":"kernel boot not defined - nothing to mount","name":"core-build-win01","namespace":"default","pos":"mount.go:408","timestamp":"2023-10-16T11:53:32.563263Z","uid":"09415d56-18bd-4c4b-ab1e-da693a96630f"} {"component":"virt-handler","level":"error","msg":"failed to create tap device named tap0","pos":"bridge.go:142","reason":"could not retrieve pid 1514629 selinux label: operation not supported","timestamp":"2023-10-16T11:53:32.686078Z"} {"component":"virt-handler","level":"error","msg":"failed to configure pod network: default","pos":"configstate.go:108","reason":"could not retrieve pid 1514629 selinux label: operation not supported","timestamp":"2023-10-16T11:53:32.686138Z"} {"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"core-build-win01","namespace":"default","pos":"vm.go:1905","reason":"failed to configure vmi network: setup failed, err: failed setup pod network phase1: Critical network error: could not retrieve pid 1514629 selinux label: operation not supported","timestamp":"2023-10-16T11:53:32.686215Z","uid":"09415d56-18bd-4c4b-ab1e-da693a96630f"} {"component":"virt-handler","level":"error","msg":"couldn't find the SELinux context for core-build-win01","pos":"vm.go:1287","reason":"no data available","timestamp":"2023-10-16T11:53:32.707734Z"} {"component":"virt-handler","level":"error","msg":"virt-launcher crashed due to a network error. Updating VMI core-build-win01 status to Failed","pos":"vm.go:1317","timestamp":"2023-10-16T11:53:32.707809Z"} {"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/core-build-win01","pos":"vm.go:1549","reason":"failed to configure vmi network: setup failed, err: failed setup pod network phase1: Critical network error: could not retrieve pid 1514629 selinux label: operation not supported","timestamp":"2023-10-16T11:53:32.749288Z"}`

**What you expected to happen**:
want to run vm

**How to reproduce it (as minimally and precisely as possible)**:
install debian 12 on BM, disable AA(apparmor), run k8s -> try to run VM

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): 1.0.0
- Kubernetes version (use `kubectl version`): v1.27.5
- VM or VMI specifications: Win10/linux/etc all
- Cloud provider or hardware configuration: k8s on BM
- OS (e.g. from /etc/os-release): Debian 12
- Kernel (e.g. `uname -a`): 6.1.0-12
- Install tools: N/A
- Others: N/A

**Comment by wenchao5211** [comment]
Any progress on this?

**Comment by wenchao5211** [comment]
my log， https://github.com/kubevirt/kubevirt/issues/10344#issuecomment-1780297488

**Comment by Viste** [comment]
lol just ignored :D

**Comment by xpivarc** [comment]
/reopen
/remove-lifecycle rotten
@aburdenthehand  maybe we need to track the issues until acked
@vasiliy-ul we probably want to not fail if permissive mode is used

**Comment by Viste** [comment]
lol
