### ISSUE TITLE
Add support for cpu cache passthrough configuration

### ISSUE THREAD

**Issue by Mlekow** [kubevirt/kubevirt#10578]
**Is your feature request related to a problem? Please describe**:
There is no way to configure cpu cache now. It may lead to low performance guest.
By default when `hypervisor` cpu feature is enabled, guest OS can't discover any cpu cache.
When `hypervisor` feature is disabled, guest OS may have wrong cpu cache configuration, which maybe larger than physical cpu capacity.

**Describe the solution you'd like**:
Provide an extra option in xml configuration, like
```xml
    spec:
      domain:
        cpu:
          cores: 15
          cache: passthrough
```

**Additional context**:
See `cache` part of this link.
https://libvirt.org/formatdomain.html#cpu-model-and-topology
And maybe `cachetune` part of this:
https://libvirt.org/formatdomain.html#id11

**Comment by xpivarc** [comment]
Hey, 
Would be able to elaborate on how this should work in your opinion and what is the use case here?
