### ISSUE TITLE
Why don't we define the values for vm.labels and vm.annotations in the function NewRandomVirtualMachine? VM-Clone E2E-Test-Case

### ISSUE THREAD

**Issue by matthewei** [kubevirt/kubevirt#10580]
**What happened**:
When I expand the VM-Clone E2E-Test-Case i found that we repeated assignment argument for vm.labels and vm.annotations

```golang
createVM := func(options ...libvmi.Option) (vm *virtv1.VirtualMachine) {
		vmi := libvmi.NewCirros(options...)
		vmi.Namespace = testsuite.GetTestNamespace(nil)
		vm = NewRandomVirtualMachine(vmi, false)
		vm.Annotations = vmi.Annotations
		vm.Labels = vmi.Labels
```
we create a new vm through vmi.
```golang
func NewRandomVirtualMachine(vmi *v1.VirtualMachineInstance, running bool) *v1.VirtualMachine {
	name := vmi.Name
	namespace := vmi.Namespace
	vmLabels := map[string]string{"name": name}
	for k, v := range vmi.Labels {
		vmLabels[k] = v
	}
	vm := &v1.VirtualMachine{
		ObjectMeta: metav1.ObjectMeta{
			Name:      name,
			Namespace: namespace,
		},
		Spec: v1.VirtualMachineSpec{
			Running: &running,
			Template: &v1.VirtualMachineInstanceTemplateSpec{
				ObjectMeta: metav1.ObjectMeta{
					Labels:      vmLabels,
					Name:        name + "makeitinteresting", // this name should have no effect
					Namespace:   namespace,
					Annotations: vmi.ObjectMeta.Annotations,
				},
				Spec: vmi.Spec,
			},
		},
	}
	vm.SetGroupVersionKind(schema.GroupVersionKind{Group: v1.GroupVersion.Group, Kind: "VirtualMachine", Version: v1.GroupVersion.Version})
	return vm
}
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by matthewei** [comment]
@iholder101, could you give me some comments about it? many thanks.

**Comment by matthewei** [comment]
I think we can set "vm.Annotations and vm.Labels" value directly  in  function of  "NewRandomVirtualMachine(vmi *v1.VirtualMachineInstance, running bool) "

**Comment by EdDev** [comment]
Usually code related improvements are suggested through PRs.
I would recommend sending a PR with a concrete suggestion and closing this one.

This issue is not a bug.

**Comment by matthewei** [comment]
> Usually code related improvements are suggested through PRs. I would recommend sending a PR with a concrete suggestion and closing this one.
> 
> This issue is not a bug.

get, I would like to do it.

**Comment by EdDev** [comment]
@matthewei , we would like to close this issue. Please feedback if there are reasons to keep this open.
