### ISSUE TITLE
Windows10 vm paused after running for a while

### ISSUE THREAD

**Issue by liyang516** [kubevirt/kubevirt#10590]
**What happened**:
I make a windows10 qcow2 image, and launched a vm. After win10 vm running for a while, for example 30mins or 60mins，this vm status become pause. And the vm virt-launcher pod log shows  "kubevirt domain status: Paused(3) IOError(5)".
![image](https://github.com/kubevirt/kubevirt/assets/35557835/c410339f-402c-405e-a183-96f2b3b9da43)

But my other os qcow2 images vm is normal, for example : centos7/ubuntu/redhat/windows7.

**What you expected to happen**:
windows10 vm should not pause，always running.

**Environment**:
- KubeVirt version : 0.59.0
- Kubernetes version : v1.22.6-rke2
- VM OS: windows10
- Physical Machine OS : Ubuntu 22.04 LTS
- Kernel: 5.15.0-84-generic
- storage-class: csi-rbd-sc

**VM info**:
```shell
# kubectl describe vmi -n xcloud-default win10-test01  | tail -n 20
  Virtual Machine Revision Name:  revision-start-vm-0d496e3e-8bc2-4588-bb7c-d47cfa2ad594-1
  Volume Status:
    Name:    cloudinitvolume
    Size:    1048576
    Target:  sdb
    Name:    rootdisk
    Persistent Volume Claim Info:
      Access Modes:
        ReadWriteMany
      Capacity:
        Storage:            30Gi
      Filesystem Overhead:  0
      Requests:
        Storage:    30Gi
      Volume Mode:  Block
    Target:         sda
Events:
  Type     Reason   Age                  From          Message
  ----     ------   ----                 ----          -------
  Warning  IOerror  2m6s (x24 over 58m)  virt-handler  VM Paused due to IO error at the volume: cloudinitvolume

```

**Comment by liyang516** [comment]
My vm yaml like this：

**Comment by xpivarc** [comment]
It seems like your local disk might have some problems.

**Comment by liyang516** [comment]
> It seems like your local disk might have some problems.

But I don't know the reason

**Comment by alicefr** [comment]
@liyang516 try to have a look at storage driver you are using for the PVC. It might experience some networking issues for example, which CSI driver are you using?

**Comment by alicefr** [comment]
@liyang516 there is something weird in your VM definition, you should have 2 disks and you only have the `rootdisk`. Aren't you missing the `cloudinitvolume` under disks?

**Comment by xpivarc** [comment]
> @liyang516 there is something weird in your VM definition, you should have 2 disks and you only have the `rootdisk`. Aren't you missing the `cloudinitvolume` under disks?

This is now valid in Kubevirt afaik.

Btw the error is on `IO error at the volume: cloudinitvolume`

**Comment by bxhandhxb** [comment]
excuse me
i met the same question. have you solved the problem?
