### ISSUE TITLE
Make kubevirt compatible with centralized monitoring setups

### ISSUE THREAD

**Issue by sjentzsch** [kubevirt/kubevirt#10617]
**Is your feature request related to a problem? Please describe**:

In centralized monitoring setups, you collect metrics from multiple sources (or: clusters, agents), push them to a centralized Prometheus-API-compatible sink, and analyze/process/visualize them further over there.

Concretely, in our case, we have a setup of say 3 agent clusters, each of them has KubeVirt installed. Those clusters do push (remote-write) metrics to our centralized cluster. Any evaluation of rules (PrometheusRules, e.g. recording or alerting rules) happens on the centralized cluster. Over there is also a Grafana in which we visualize all data/components across our agent clusters.

This is a typical setup of centralized observability, and not supported by KubeVirt unfortunately, as there are multiple problems with KubeVIrt's architecture in this regard:

- Deployment of PrometheusRules containing recording and alerting rules is done as part of the KubeVirt operator lifecycle. However, neither do we evaluate the rules on agent clusters, nor do we want to run KubeVirt on the centralized monitoring cluster.
- The recording and alerting rules expressions need to aggregate upon external labels that distinguish the agent clusters, e.g. `sum by(pod, container, namespace) (...)` should become `sum by(cluster, pod, container, namespace) (...)`. While the external label(s) are of course depending on each cluster architecture, having the `cluster` label for this purpose is the most used one out there (looking at other CNCF projects).
- The Grafana Dashboard (see https://github.com/kubevirt/monitoring/tree/main/dashboards/grafana) needs to be able to have the same drop-down variable (`cluster` label etc.), and needs to enhance all expressions with this filter label.

**Describe the solution you'd like**:

For this, Prometheus alerts and dashboards are typically bundled as part of a [Monitoring mixin](https://monitoring.mixins.dev/), instead of being deployed as part of the operator/app itsels, so the user can configure it further and separate deployment of the app and deployment of monitoring artifacts. I would wish for exactly that :)

**Describe alternatives you've considered**:

Alternative would be to make all the above mentioned aspects configurable as part of the kubevirt operator. This however would still mean, that the user would need to install the operator on the centralized monitoring cluster. And this does not solve the dashboard configuration.

**Comment by fabiand** [comment]
@sradco any insights on this?

/sig monitoring

/remove-lifecycle stale

**Comment by sradco** [comment]
Hi, Unfortunately adding Mixins is not part of our scope for Kubevirt monitoring.
But while remote_write does not directly send the recording rule configurations, it does send the resulting time series data generated by these rules. So, if you have recording rules that create new aggregated or calculated metrics, the outcomes of these rules (i.e., the resulting metrics) can be sent to a remote storage via remote_write.

For alerts you can configure Alertmanager to send firing alerts to external monitoring systems, tools, or services. Alertmanager, which handles alerts sent by Prometheus server instances, can be configured to forward alerts to a wide array of endpoints including email, Slack, PagerDuty, webhooks, and many others. Using webhooks is a common method to integrate with external monitoring systems that might not have direct support or a pre-built integration with Alertmanager.
