### ISSUE TITLE
failed to run virt-launcher;monitoring virt-launcher failed

### ISSUE THREAD

**Issue by ZhangSetSail** [kubevirt/kubevirt#10619]
**What happened**:

I followed the quick start example on the official website，The virtual machine I created is not operational.

**What you expected to happen**:

I hope he can run normally

**How to reproduce it (as minimally and precisely as possible)**:

1. opened a bare metal server in Alibaba Cloud
2. Deploy according to the [deployment documentation](https://kubevirt.io/quickstart_cloud)
3. Reference [use documentation](https://kubevirt.io/labs/kubernetes/lab1.html)

**Additional context**:
kubevirt running
<img width="682" alt="image" src="https://github.com/kubevirt/kubevirt/assets/101104760/5684e4f2-a587-4814-97c1-1493c6c4b337">

I created and started the VM resource following the usage documentation
```
kubectl apply -f https://kubevirt.io/labs/manifests/vm.yaml
virtctl start testvm
```
The VM's pod reports an error and is deleted two or three seconds after it is created.

log:
<img width="927" alt="image" src="https://github.com/kubevirt/kubevirt/assets/101104760/d69bddc4-f3c2-4b77-8889-108fa55ccc7e">

VM event:
<img width="942" alt="image" src="https://github.com/kubevirt/kubevirt/assets/101104760/6f2230d7-8feb-41a9-81a7-6f4ae48f47f7">

**Environment**:
- KubeVirt version (use `virtctl version`): v1.1.0-alpha.0
- Kubernetes version (use `kubectl version`): v1.23.10
- VM or VMI specifications:  https://kubevirt.io/labs/manifests/vm.yaml
- Cloud provider or hardware configuration: alicloud
- OS (e.g. from /etc/os-release): centos 7.9
- Kernel (e.g. `uname -a`): 3.10.0
- Install tools: kubectl yaml
- Others: N/A

**Comment by vasiliy-ul** [comment]
@ZhangSetSail, are you using Docker in your cluster? If so, please refer to the issue https://github.com/kubevirt/kubevirt/issues/9465#issuecomment-1673437332. You might need to update it to a more recent version.

**Comment by ZhangSetSail** [comment]
upgrading the docker version directly to 24.0.6 solved my problem, thank you so much
