### ISSUE TITLE
Error from server (NotFound): persistentvolumeclaims "fedora" not found

### ISSUE THREAD

**Issue by manas-suleman** [kubevirt/kubevirt#10618]
**Description**:
I have Kubernetes installed on local cluster and I've just installed KubeVirt. I'm going through the labs in order to get familiarity with it. I followed through lab one. But for lab 2, I while I can create a data volume,
`$ kubectl apply -f dv_fedora.yml`
> datavolume.cdi.kubevirt.io/fedora created

I'm supposed to get the PVC in the next step but I get the following instead:
`$ kubectl get pvc fedora -o yaml`
> Error from server (NotFound): persistentvolumeclaims "fedora" not found

These are the pods running currently:

> NAMESPACE      NAME                                           READY   STATUS    RESTARTS       AGE
> cdi            cdi-apiserver-####                 1/1     Running   0              3d6h
> cdi            cdi-deployment-####                1/1     Running   0              3d6h
> cdi            cdi-operator-####                   1/1     Running   0              3d6h
> cdi            cdi-uploadproxy-####               1/1     Running   0              3d6h
> default        virt-launcher-testvm-####                     2/2     Running   0              3d9h
> kube-flannel   kube-flannel-ds-####                          1/1     Running   0              5d9h
> kube-flannel   kube-flannel-ds-####                          1/1     Running   0              5d5h
> kube-system    coredns-####                       1/1     Running   0              5d5h
> kube-system    coredns-####                       1/1     Running   0              5d5h
> kube-system    etcd-server1                      1/1     Running   0              5d9h
> kube-system    kube-apiserver-server1            1/1     Running   0              5d9h
> kube-system    kube-controller-manager-server1   1/1     Running   0              5d9h
> kube-system    kube-proxy-####                               1/1     Running   0              5d9h
> kube-system    kube-proxy-####                               1/1     Running   0              5d5h
> kube-system    kube-scheduler-####            1/1     Running   0              5d9h
> kubevirt       virt-api-####                      1/1     Running   1 (3d6h ago)   5d5h
> kubevirt       virt-api-####                      1/1     Running   1 (3d6h ago)   5d5h
> kubevirt       virt-controller-####               1/1     Running   1 (3d6h ago)   5d5h
> kubevirt       virt-controller-####               1/1     Running   1 (3d6h ago)   5d5h
> kubevirt       virt-handler-####                             1/1     Running   0              5d5h
> kubevirt       virt-operator-####                 1/1     Running   0              5d5h
> kubevirt       virt-operator-####                 1/1     Running   0              5d5h

The only errors I could find were in virt-controller pods and I'm not sure if they are relevant:

> {"component":"virt-operator","level":"error","msg":"reenqueuing KubeVirt kubevirt/kubevirt","pos":"kubevirt.go:683","reason":"Internal error occurred: failed calling webhook \"kubevirt-update-validator.kubevirt.io\": failed to call webhook: Post \"https://kubevirt-operator-webhook.kubevirt.svc:443/kubevirt-validate-update?timeout=10s\": context deadline exceeded","timestamp":"2023-10-20T11:04:09.172811Z"}
> {"component":"virt-controller","level":"error","msg":"failed to load the certificate /etc/virt-controller/certificates/tls.crt and /etc/virt-controller/certificates/tls.key","pos":"cert-manager.go:189","reason":"failed to load certificate: tls: private key does not match public key\n","timestamp":"2023-10-21T01:11:00.247059Z"}

These errors were logged before the datavolume was created so could they be irrelevant to the issue?

Kubernetes Version:

> 
> Client Version: v1.28.2
> Kustomize Version: v5.0.4-0.####
> Server Version: v1.28.2

KubeVirt Version: v1.0.0
CDI version: v1.57.0

Rocky Linux 8.8

**What you expected**:
Details of persistent volume claim named "fedora".

**URL**:
https://kubevirt.io/labs/kubernetes/lab2

**Additional context**:
I'm not sure what further info I can provide but please let me know what else I should provide.

Thanks,

**Comment by alicefr** [comment]
Sorry, it isn't clear to me if you have already created a VM? It possible that the PVC get created when there is a pod using it, for example, when you start the VM. Have you tried it?

**Comment by manas-suleman** [comment]
Hi, apologies, there were some formatting issues that made the original comment unclear. I've edited it now. Please let me explain in detail. I did create a VM in lab1 but it has no connection with this lab (which is lab2, link shared in original comment). I am only following the steps in this lab. For lab2, I am supposed to,
install CDI:
`export VERSION=$(basename $(curl -s -w %{redirect_url} https://github.com/kubevirt/containerized-data-importer/releases/latest))
kubectl create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-operator.yaml
kubectl create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-cr.yaml
`
use CDI to import a disk image:
`cat <<EOF > dv_fedora.yml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: "fedora"
spec:
  storage:
    resources:
      requests:
        storage: 5Gi
  source:
    http:
      url: "https://download.fedoraproject.org/pub/fedora/linux/releases/37/Cloud/x86_64/images/Fedora-Cloud-Base-37-1.7.x86_64.raw.xz"
EOF

kubectl create -f dv_fedora.yml
`

and then, get the persistent volume claim with command:
`kubectl get pvc fedora -o yaml`
to which I get the error:

> Error from server (NotFound): persistentvolumeclaims "fedora" not found

And that's the issue I have. Hope this explains it.

**Comment by vasiliy-ul** [comment]
@manas-suleman, could you check your default storage class whether it has `WaitForFirstConsumer` binding mode? `kubectl get sc`?

If it is the case, you can force immediate binding by adding annotation: `cdi.kubevirt.io/storage.bind.immediate.requested` (ref: https://github.com/kubevirt/containerized-data-importer/blob/main/doc/waitforfirstconsumer-storage-handling.md#forcing-immediate-binding) or as mentioned by @alicefr, you would need a pod (or a VMI) to reference that PVC before it gets created.

**Comment by vasiliy-ul** [comment]
Seems that https://kubevirt.io/labs/kubernetes/lab2 does not mention WFFC. So it might be confusing if going through the steps in such an environment.

**Comment by manas-suleman** [comment]
@vasiliy-ul thank you for the suggestion.
`kubectl get sc`
returns,
> No resources found
But I still tried using the annotation: `cdi.kubevirt.io/storage.bind.immediate.requested` because why not. But got the same error, i.e.
`$ kubectl get pvc fedora -o yaml`
> Error from server (NotFound): persistentvolumeclaims "fedora" not found
Now, onto your second suggestion by @alicefr and you, "you would need a pod (or a VMI) to reference that PVC before it gets created", I'm very new to KubeVirt so if you could please share a reference document or documentation link that lists the steps for this, that would be great. Thanks,

**Comment by vasiliy-ul** [comment]
> kubectl get sc
returns,

> No resources found

That is actually the problem. You do not have any storage class configured in your cluster. You probably need to install a provisioner which will automatically allocate volumes (if you do not have one already). If your goal is to just experiment with KubeVirt locally, you may try smth simple, e.g. https://github.com/rancher/local-path-provisioner. The installation is pretty straightforward: `kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/v0.0.24/deploy/local-path-storage.yaml`.

**Comment by vasiliy-ul** [comment]
One more thing: if installing the provisioner does not help, please provide the output of `kubectl describe dv`

**Comment by alicefr** [comment]
> @vasiliy-ul my assumption was kubevirt would work "out-of-the-box" and I should be fine just following the labs to have a basic and initial exposure to it. I understand now that is probably not the case. I do not intend to just experiment. I want to explore it, learn it and see if it's suitable for our use-case. If it is, I'd like to deploy and use it in production cluster. Some questions,
> 
> 1. Since I don't want to just experiment, should I still move ahead with the installation of local-path-provisioner?
> 2. If labs are not the best way to gain familiarity with KubeVirt, is the full kubevirt documentation the way to go?
> 
 @aburdenthehand, maybe this is a good feedback about the lab. Can you please point us to the most recent documentation?

**Comment by vasiliy-ul** [comment]
Maybe a small correction: actually, for certain scenarios you can use `local-path-provisioner` on prod environments. Again, that depends on your specific requirements and use-case.

**Comment by manas-suleman** [comment]
@vasiliy-ul my setup is indeed different from the one that the labs expected. That's something overlooked on my part. For now, I think you folks have pointed me to the right direction. Thanks for that. Really appreciate it.
