### ISSUE TITLE
Increase code coverage by 10%

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1063]
We are tracking code coverage using goverage (shown here https://coveralls.io/github/kubevirt/kubevirt).

This issue is about adding tests to increase the code coverage.

**Comment by yuvalif** [comment]
this is great initiative! as we are at ~65%, getting to 80% line coverage would be awesome.

would recommend 2 things here:

1. provide some guidance and documentation around mocking (mock kubecli, mock http server etc.), what exist, and how to use it, as this is the main barrier (at least for me...) for writing unit tests
2. follow the ["boy (or girl) scout rule"](http://programmer.97things.oreilly.com/wiki/index.php/The_Boy_Scout_Rule) rather then treating it as a standalone issue - every time you enhance/fix some code, add more testing around the existing code as well

**Comment by fabiand** [comment]
1. Is great - do you have a few pointers we can leave her to give new comers a good start? @yuvalif 

For 2. + absolutely - tihs issue is basically an initiative to lift the base level :)

**Comment by fabiand** [comment]
Can we take functional tests into account for code covergae - how?

**Comment by yuvalif** [comment]
@fabiand think this is not possible using the standard tools (see here: https://blog.golang.org/cover). Since the package code is generated with the coverage hooks, it is not possible to get coverage to binaries that were already generated and running.
they do mention that gcov may work, as this does dynamic coverage on the binary itself, it may give coverage results for the integration tests.
this would require building the binaries in way that gcov could run interact with them using gccgo.

**Comment by yuvalif** [comment]
generated files should be excluded from coverage report: https://stackoverflow.com/questions/50065448/how-to-ignore-generated-files-from-go-test-coverage

this will be a low hanging fruit for increasing coverage in significant numbers (thanks @SchSeba for the idea!)

**Comment by rmohr** [comment]
@yuvalif I fear that most are already excluded. The only ones included are the defaulter and deepcopy files. They are tested with some fuzzing and have almost 100% coverage (another question is if it is really necessary since k8s would probably detect immediately if their generators are broken but it was just easy to do).

**Comment by rmohr** [comment]
@yuvalif FYI: https://github.com/kubevirt/kubevirt/blob/master/hack/goveralls.sh

**Comment by yuvalif** [comment]
@rmohr the zz_generated... files are still pretty low, probably better to exclude them.

@stu-gott I have written a post on general guidelines http://kubevirt.io/2018/Unit-Test-Howto.html on unit testing in our project.
will try to identify and list areas of focus and will add here.

**Comment by yuvalif** [comment]
looked at files that were recently modified as part of bug fixes, and has low coverage (=indication that adding coverage will find bugs):
- pkg/virt-api/rest/subresource.go
- pkg/virt-handler/device-manager/generic_device.go
- pkg/virt-handler/device-manager/device_controller.go
- pkg/virt-launcher/virtwrap/cli/libvirt.go

another files that probably be on the list:
- pkg/virt-api/api.go

if you feel that the list above is a good focus, will try to write-up some guidance per file as for how to do the testing.

**Comment by stu-gott** [comment]
@yuvalif that sounds like a plan. thanks!

**Comment by yuvalif** [comment]
- **pkg/virt-api/rest/subresource.go**
subresource_test.go already exists, however, the actual logic is not tested. to test it, the calls from the test code should be calling into the request handler (ideally via the public APIs). most of the work there would be around mocking of websocker, upgrader and io.
 - **pkg/virt-api/api.go**
api_test.go already exists, covering mainly certification code . should add coverage to: composeSubresources() (or even better to the Compose() public interface). mocking of http server will be needed.
- **pkg/virt-launcher/virtwrap/cli/libvirt.g**
according to this: https://github.com/libvirt/libvirt-go#testing there is a test driver, unrelated to libvirt running on OS. should investigate if this can be used. current test file exists, but does not cover only failure to open a new connection

**Comment by qinqon** [comment]
Trying to help here, I think I will have PR soon at least for subresource.

**Comment by cynepco3hahue** [comment]
@qinqon Great to hear it, you can comment with `/remove-lifecycle stale` if you want to work on it and also you can run `/assign @qinqon`.

**Comment by fabiand** [comment]
Adding you as a member, @qinqon

**Comment by qinqon** [comment]
@fabiand thanks, will try to do my best here!

/assign @qinqon

**Comment by qinqon** [comment]
Added some subresource coverage, websockets and SPDY stuff:
https://github.com/qinqon/kubevirt/commit/dd7c82e9c29e49c0c4f76bf66e5c84449825d6d9

Now virt-api/rest has a coverage of 54.6%

It's good enough to create a PR with just that or better to add more coverage elsewhere ?

**Comment by cynepco3hahue** [comment]
@qinqon cool, I think it is enough for the first PR.

**Comment by fabiand** [comment]
Sound cool!

**Comment by qinqon** [comment]
Ok, so I have around 60% of coverage of pkg/virt-api/api.go [here](https://github.com/qinqon/kubevirt/tree/increase_virt_api_coverage) this would be good enough for another PR ? also I have to fix some issues local running is working but timing out at travis.

**Comment by cynepco3hahue** [comment]
@qinqon I can feel free to create additional PR :smile:

**Comment by qinqon** [comment]
@cynepco3hahue here we are with the PR, maybe it's too big.
