### ISSUE TITLE
Allow block live migration of PVCs that do not support ReadWriteMany access mode

### ISSUE THREAD

**Issue by aarguello** [kubevirt/kubevirt#10642]
**Is your feature request related to a problem? Please describe**:

Yes. There is a significant performance degradation when using file based disk images compared to block based disk images. I'm running workloads that rely on local NVMe disks for certain operations and the difference was noticeable when moving towards Kubevirt VMs. I ran some `fio` benchmarks to compare the random write IOPS under three distinct scenarios:

 \- | AVG | STD | MIN | MAX
---|---|---|---|---
Bare-metal host | 310k | 39k | 91k | 393k
QEMU VM with raw block volume | 276k | 13k | 246k | 313k 
Kubevirt VM with emptyDisk | 132k | 14k | 63k | 142k

I do not expect to match bare-metal performance, but at least the performance I would obtain by using QEMU+libvirt directly.

**Describe the solution you'd like**:

I'd like for PVCs to support block migration just like emptyDisk volumes, instead of the current situation that requires PVCs to support ReadWriteMany access mode. This would allow me to use a CSI driver for LVM volumes on the host and then rely on Kubevirt's existing block PVC support to offer this LVM volume as a block device to the virt-launcher.

However, I have some questions:

1. Is this something that the Kubevirt community would be interested in supporting?
2. Is there any work in progress around this use case? The closest thing I found is https://github.com/kubevirt/kubevirt/pull/10536, though it seems to be a much broader feature and involves different PVCs.
3. Does the scope of the change warrant a desing proposal? Or should attempt an implementation and send a PR for it?

**Describe alternatives you've considered**:

- Initially, I considered proposing support for raw block devices via emptyDisk. But I reckon this is not possible because, unlike files, the virt-launcher container cannot provision a block volume out of thin air.
- I also tried to solve the performance degradation by other means like using blockMultiQueue and IOThreads, but saw no improvements.

**Additional context**:

The command used for benchmarking:

```
fio --ioengine=libaio \
  --direct=1 \
  --verify=0 \
  --time_based \
  --bandwidth-log \
  --runtime=60s \
  --ramp_time=2s \
  --size=1G \
  --group_reporting=1 \
  --directory=/fio \
  --name="random_write" \
  --numjobs=1  \
  --bs=4K \
  --rw=randwrite  \
  --iodepth=256 \
  --iodepth_batch_submit=256  \
  --iodepth_batch_complete_max=256
```

**Comment by alicefr** [comment]
> * Is this something that the Kubevirt community would be interested in supporting?
> * Is there any work in progress around this use case? The closest thing I found is [WIP: Storage migration #10536](https://github.com/kubevirt/kubevirt/pull/10536), though it seems to be a much broader feature and involves different PVCs.
> * Does the scope of the change warrant a desing proposal? Or should attempt an implementation and send a PR for it?

Please, check the design proposal about [storage migration](https://github.com/kubevirt/community/pull/245). Once, we agree on the API, I'll continue the PR you are referring to.

However, this proposal doesn't explicitly cover VM live migration with local disks, but rather it focuses on changing the storage class type. In the end, this triggers the VM migration as explained in detail in the proposal.

The challenge of using RWO PVCs and local storage is that you need a copy and a second PVC that replaces the original one. This is what the proposal and WIP PR aim to achieve. 

One of the feedback I received during the review was that the scope of the [first proposal](https://github.com/kubevirt/community/pull/240) was too broad. But potentially what you ask could be done a follow up work.

/cc @fabiand
