### ISSUE TITLE
virt-launcher securityContext.Selinux.level is not picked by what is set in project(namespace) scc.mcs 

### ISSUE THREAD

**Issue by vsundarraj-px** [kubevirt/kubevirt#10687]
**What happened**:

On OCP with kubevirt version v1.0.0, the virt-launcher pod assigns new selinuxcontext everytime it starts. This voids the RWO accessMode policy of k8s. 

Al thought it seems a security feature, but ti causes the VM to go in to paused state if any other pods mounts the same PVC.
The only way to recover from the paused state is restart the VM or reset the securitylevls that VMI was using. However, this workflow causes disruption to VM.

Please note, RWO accessMode allows multiple pods to access the volume from same node. So kubevirt seem to deviating from this k8s behaviour and causes disruption to itself if another pod launched while the VM is running, and disrupts the other container APP if VM was started while the container App is running. 

Why we need other containers to access the VM volumes? well there are many reasons, auditlogs, sidecars, backup/restore etc to name a few. 

**What you expected to happen**:
The virt-launcher pod should set selinuxcontext that is specified for the namespace. 

**How to reproduce it (as minimally and precisely as possible)**:
On OCP with Selinux enforced cluster, run the VM.. Stop and start the vm and notice the  .status.selinuxContext

```
> k get vmi testvm-data  -n inplace -o json | jq .status.selinuxContext
"system_u:object_r:container_file_t:s0:c603,c752"
> v stop testvm-data -n inplace
VM testvm-data was scheduled to stop
> k get vm -n inplace
NAME          AGE   STATUS    READY
testvm-data   38d   Stopped   False
> v start testvm-data -n inplace
VM testvm-data was scheduled to start
> k get vmi testvm-data  -n inplace -o json | jq .status.selinuxContext
"system_u:object_r:container_file_t:s0:c172,c536"

```
**Additional context**:
This will reset selinux levels in the mounted volumes. When any other pods mounts the volume, then the security context changes to the default scc.mcs set on the namespace. This causes the VM to go into indefinite paused state. 
**Environment**: OCP 4.12 Running on RHEL8.6 
- KubeVirt version (use `virtctl version`): v1.0.0
- Kubernetes version (use `kubectl version`): 1.27.2
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: RWO Volumes
- OS (e.g. from /etc/os-release): 
- NAME="Red Hat Enterprise Linux CoreOS"
ID="rhcos"
ID_LIKE="rhel fedora"
VERSION="412.86.202309101149-0"
VERSION_ID="4.12"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 412.86.202309101149-0 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::coreos"
HOME_URL="https://www.redhat.com/"
DOCUMENTATION_URL="https://docs.openshift.com/container-platform/4.12/"
BUG_REPORT_URL="https://access.redhat.com/labs/rhir/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.12"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.12"
OPENSHIFT_VERSION="4.12"
RHEL_VERSION="8.6"
OSTREE_VERSION="412.86.202309101149-0"
- Kernel (e.g. `uname -a`): 4.18.0-372.71.1.el8_6.x86_64
- Install tools: N/A
- Others: N/A

**Comment by vsundarraj-px** [comment]
`k get project inplace -o json | jq .metadata.annotations
{
  "openshift.io/sa.scc.mcs": "s0:c26,c20",
  "openshift.io/sa.scc.supplemental-groups": "1000690000/10000",
  "openshift.io/sa.scc.uid-range": "1000690000/10000"
}`

**Comment by jean-edouard** [comment]
Hi @vsundarraj-px !
Assigning random MCS to every new pods is standard k8s (well CRI) behavior.
KubeVirt does not support the OpenShift-specific namespace annotation mentioned above.
Please feel free to open a PR to add support for that annotation.
Considering the important security implications however, I would consider using an explicit flag or feature gate to enable it.
When all the VMIs/pods of a given namespace run under the same MCS, SELinux just stops protecting the resources of those pods from each other, and a VM/container escape gives an attacker full access to the entire namespace.

**Comment by vsundarraj-px** [comment]
@jean-edouard are you saying this is protection other pods in the namespace from rogue VM/Container ? Or the other way round? Either ways the current behaviour is neither protecting the pods nor the VM. VM start causes the existing pods to loose access to the Volumes(disruption) and vise-e-versa too Pod start causes existing VMs to indefinite pause. I dont see any protection in play. Unless I'm missing something.

But, for hotplug volumes, we read from the selinuxContext set in the VMI and apply the same. 
I'm not very equipped to understand the CRI in depth, but what I notice is, all pods on the same namespace gets the mcs from the namespace assigned selinuxLevels. And a pod from a different namespace has different levels. So essentially protecting cross namespace violation(if such a thing is possible). But how is that virt-launcher is behaving differently than the other native apps? 
I tried deployment and job, and both gets selinuxContext from namespaec scc.mcs.. 

Just wondering is this incomplete here?
https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-controller/services/template.go#L1261

**Comment by jean-edouard** [comment]
In recent versions, KubeVirt sets SELinux options on virt-launcher only when specific SELinux options are set in the KubeVirt CR (`selinuxType` or the `dockerSELinuxMCSWorkaround` feature gate). In all other cases, we do not touch the pods `SELinuxOptions` and let the CRI do its thing.
We do however, as you noticed, force the same categories as virt-launcher on disk-hotplug pods, to allow communication between the two (if k8s supported dynamically adding containers to pods, the disk-hotplug container would definitely be created under virt-launcher).

I am unfortunately not familiar with the OpenShift annotation you mentioned, nor its implementation, so I'm not sure why it has no effect on virt-launcher...
It'd probably be best to reach out to the maintainers of said annotation and ask them about this.

**Comment by xpivarc** [comment]
Hi, this is not Kubevirt problem per se. The Openshift does fill this value according to the annotation when a `MustRunAs` is specified by the SCC but we do specify `RunAsAny`.

**Comment by vsundarraj-px** [comment]
@xpivarc can elaborate more? I am unable to find why virt-launcher is not honouring the openshift webhook for setting the mcs. Instead of levels set on the namespace, the virt-launcher pod gets random labels on every restart. Whats the reason for that? Is it done at kubevirt level or at openshift level? I doubt its at openshift, unless kubevirt is sending some marker to bypass the default behaviour.

**Comment by xpivarc** [comment]
It depends on `SCC` used by Pod. In our case, we define an `SCC` with `SelinuxContext = RunAsAny`, In this case, Openshift does not use the namespace defined mcs.

**Comment by aglitke** [comment]
I don't see any quick workaround possible.  I think we'd need a kubevirt design proposal to introduce this new security mode.  I suspect this would need to be off by default (to preserve the current VM isolation semantics) and controlled by either a feature gate or configuration option on the kubevirt CR.  If you are looking for a general change in the semantics I don't think it's realistic at this time.  If you want to address some specific use cases then we should look at them individually.
