### ISSUE TITLE
server error. command Launcher.Sync failed: virError

### ISSUE THREAD

**Issue by vatsalparekh** [kubevirt/kubevirt#1068]
Deployed a VM from [working template](https://github.com/ManageIQ/manageiq-providers-kubevirt/blob/master/manifests/working-template.yml), and in status I see the following
```
[root@cnv-executor-vparekhmiq-master1 ~]# oc get vms vparekh.test-432001 -n default -o yaml
apiVersion: kubevirt.io/v1alpha1
kind: VirtualMachine
metadata:
  annotations:
    presets.virtualmachines.kubevirt.io/presets-applied: kubevirt.io/v1alpha1
  clusterName: ""
  creationTimestamp: 2018-05-23T12:29:38Z
  finalizers:
  - foregroundDeleteVirtualMachine
  generateName: vparekh.test-432001
  generation: 1
  labels:
    kubevirt.io/nodeName: cnv-executor-vparekhmiq-master1.example.com
  name: vparekh.test-432001
  namespace: default
  ownerReferences:
  - apiVersion: kubevirt.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: OfflineVirtualMachine
    name: vparekh.test-432001
    uid: 55d8b7ac-5e81-11e8-b92b-fa163e5e0d6b
  resourceVersion: "34131"
  selfLink: /apis/kubevirt.io/v1alpha1/namespaces/default/virtualmachines/vparekh.test-432001
  uid: f58db24d-5e84-11e8-b92b-fa163e5e0d6b
spec:
  domain:
    cpu:
      cores: 1
    devices:
      disks:
      - disk: {}
        name: registrydisk
        volumeName: registryvolume
      - disk: {}
        name: cloudinitdisk
        volumeName: cloudinitvolume
    firmware:
      uuid: 10e10d24-8fc9-51c0-bb00-2d1787c1c656
    machine:
      type: q35
    resources:
      requests:
        memory: 1Gi
  volumes:
  - name: registryvolume
    registryDisk:
      image: kubevirt/fedora-cloud-registry-disk-demo:latest
  - cloudInitNoCloud:
      userDataBase64: I2Nsb3VkLWNvbmZpZwpwYXNzd29yZDogYXRvbWljCnNzaF9wd2F1dGg6IFRydWUKY2hwYXNzd2Q6IHsgZXhwaXJlOiBGYWxzZSB9Cg==
    name: cloudinitvolume
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-05-23T12:29:53Z
    message: 'server error. command Launcher.Sync failed: virError(Code=20, Domain=20,
      Message=''missing target information for device /var/run/libvirt/kubevirt-ephemeral-disk/registry-disk-data/default/vparekh.test-432001/disk_registryvolume/disk-image.qcow2'')'
    reason: Synchronizing with the Domain failed.
    status: "False"
    type: Synchronized
  interfaces:
  - ipAddress: x.x.x.x
  nodeName: cnv-executor-vparekhmiq-master1.example.com
  phase: Scheduled
```

**Comment by vatsalparekh** [comment]
@rmohr

**Comment by cynepco3hahue** [comment]
@vatsalparekh Hi, can you also show logs of the virt-launcher pod?

**Comment by cynepco3hahue** [comment]
Ok I check @vatsalparekh environment and looks like bus parameter not passed correctly
```bash
# oc edit ovm vparekh.test003
...
spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - disk: {}
            name: registrydisk
            volumeName: registryvolume
          - disk: {}
            name: cloudinitdisk
            volumeName: cloudinitvolume
...
```
I tried to edit it manually to
```
        devices:
          disks:
          - disk:
              bus: virtio
            name: registrydisk
            volumeName: registryvolume
          - disk:
              bus: virtio
            name: cloudinitdisk
            volumeName: cloudinitvolume
```
and looks like it solved the problem with `missing target information for device` message.
I do not sure why it had empty bus section, IIRC we set it by default as `virtio`, but will need to check the code.

**Comment by fabiand** [comment]
@slintes please take a look at this bug

**Comment by vatsalparekh** [comment]
@slintes @fabiand checked this today on `v0.5.1-alpha.2` also, able to reproduce.

**Comment by slintes** [comment]
I'm looking at his right now. The default bus (when applied) will be `sata` for`q35` machine type, not `virtio`, see https://github.com/kubevirt/kubevirt/blob/master/pkg/api/v1/defaults.go#L158. Is that ok?

**Comment by fabiand** [comment]
@slintes `sata` is the correct default.

**Comment by fabiand** [comment]
Please make sure to add a test case for this bug.

**Comment by slintes** [comment]
This isn't as easy as it looked. I added the `RegisterDefaults` [1] function the `Schemebuilder` [2], but it has no effect. So I tried to find out how defaulting should work, but only found that **validation** is possible with either openapi in the CRD definition [3], or with a ValidatingAdmissionWebhook [4], which we already use. But **defaulting** only with a MutatingAdmissionWebhook [5], or directly in the controller. Or do I miss something?

@rmohr @davidvossel 

[1] https://github.com/kubevirt/kubevirt/blob/master/pkg/api/v1/zz_generated.defaults.go#L30
[2] https://github.com/kubevirt/kubevirt/blob/master/pkg/api/v1/types.go#L93
[3] https://kubernetes.io/docs/tasks/access-kubernetes-api/extend-api-custom-resource-definitions/#advanced-topics
[4] https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#validatingadmissionwebhook-alpha-in-1-8-beta-in-1-9
[5] https://kubernetes.io/docs/reference/access-authn-authz/admission-controllers/#mutatingadmissionwebhook-beta-in-1-9

**Comment by rmohr** [comment]
So, in Theorie und wenn will need the mutating webhook which does all modifications. Richtig now, until we switch, web can invoke the defaulter on the vm in the preset controller. At the Same location where we add the Procedere/initialized annotation to the vm.

**Comment by slintes** [comment]
check, will have a look
