### ISSUE TITLE
kubevirt virt handler： CPU does not support x86-64-v2

### ISSUE THREAD

**Issue by scydas** [kubevirt/kubevirt#10713]
**What happened**:
Install kubevirt v1.0.0 , virt-handler logs error: 

kubevirt -n kubevirt logs -f virt-handlerxxx virt-launcher
Fatal glibc error: CPU does not support x86-64-v2

**What you expected to happen**:
kubevirt can up and running

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

kubectl apply -f kubevirt-operator.yaml
kubectl apply -f kubevirt-cr.yaml

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v1.0.0
- Kubernetes version (use `kubectl version`): 1.26.7
- OS (e.g. from /etc/os-release): centos
- Kernel (e.g. `uname -a`): 3.10.0-1160.71.1.el7.x86_64
- cpu info：
<img width="569" alt="WeChatWorkScreenshot_483aff53-f8ae-4503-b9f9-5fbb7632ba96" src="https://github.com/kubevirt/kubevirt/assets/22952515/547fc48b-2afb-4f00-bbd7-bc19b7a92341">

**Comment by vasiliy-ul** [comment]
Is it a nested host or bare-metal? A similar issue was reported here https://github.com/kubevirt/containerized-data-importer/issues/2652. Perhaps it has some helpful info for your case.

**Comment by scydas** [comment]
> Is it a nested host or bare-metal? A similar issue was reported here [kubevirt/containerized-data-importer#2652](https://github.com/kubevirt/containerized-data-importer/issues/2652). Perhaps it has some helpful info for your case.

is bare-metal

**Comment by vasiliy-ul** [comment]
@scydas, could you run `/lib64/ld-linux-x86-64.so.2 --help` on your machine?

My understanding is that the packages used in the containers (based on centos) require `x86-64-v2`. If your host does not support that, there is not that much to do on the KubeVirt side... in such case probably you can take a look at alternative builds though.

**Comment by scydas** [comment]
@vasiliy-ul 
glibc version is 2.17，The command does not have a `--help` parameter.
Get the cpu instruction set from the [link](https://unix.stackexchange.com/questions/631217/how-do-i-check-if-my-cpu-supports-x86-64-v2) 
![image](https://github.com/kubevirt/kubevirt/assets/22952515/5b1a4a79-4d89-4053-b21a-4db71cc08bbc)
So I should build my own hanlder image?

**Comment by vasiliy-ul** [comment]
Well, KubeVirt images are currently based on `CentOS 9 Stream`, which, AFAIK, requires CPUs with support of `x86_64 v2+`. Therefore, you will probably need to either use a host with a more recent CPU or rebuild KubeVirt, so it does not link against libraries that need `x86_64 v2`.

If you are fine with building your own KubeVirt, I can suggest trying to build statically the affected binaries. As noted in the CDI issue which I mentioned earlier, this is already done, e.g. for `virt-operator`: https://github.com/kubevirt/kubevirt/blob/b371fd0c3765a28036782e34439b5ae6ea92a95e/cmd/virt-operator/BUILD.bazel#L21 You probably need to do the same for other binaries that do not work on your host (I assume `virt-handler`, and `virt-launcher`). However, I think there will be one more issue: likely qemu and libvirt will also need to be rebuilt for your CPU (as well as their deps). If that is the case, you will need to build a custom `virt-launcher` image like it is described here: https://github.com/kubevirt/kubevirt/blob/main/docs/custom-rpms.md. Unfortunately, not an easy solution.

**Comment by vasiliy-ul** [comment]
@scydas, one more thing to try: you can potentially use custom KubeVirt builds provided by other projects. E.g. you can take a look at Harvester. It uses KubeVirt under the hood and the images should not require x86_64 v2. Perhaps you can take a look at the Helm charts and install only KubeVirt https://github.com/harvester/harvester/tree/master/deploy/charts

**Comment by scydas** [comment]
> @scydas, one more thing to try: you can potentially use custom KubeVirt builds provided by other projects. E.g. you can take a look at Harvester. It uses KubeVirt under the hood and the images should not require x86_64 v2. Perhaps you can take a look at the Helm charts and install only KubeVirt https://github.com/harvester/harvester/tree/master/deploy/charts

Thanks for the serious answer, I'll go read the harverster code
