### ISSUE TITLE
VirtualMachinePool instance snapshot restore

### ISSUE THREAD

**Issue by Muyan0828** [kubevirt/kubevirt#10718]
**What happened**:
After the VM pool instance does snapshot restore, the volumes of the instance will replace the name to restore-xxxx, and then if increase VM pool's replicas,  the volumes that have been snapshot restored of the instance will be lost.

**What you expected to happen**:
restored volumes not lost after increasing the VM pool's replicas

**How to reproduce it (as minimally and precisely as possible)**:
1. create a VM pool with 1 replicas 
2. make a snapshot of VM pool instance
3. do a snapshot restore
4. Scale VM pool replicas to 2

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v1.0.0
- Kubernetes version (use `kubectl version`): v1.27.7
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by matthewei** [comment]
I thank that this phenomenon is expected. Because the restoreVM has labels which can be managed by vmpool. So you can remore the restore vm's labels.

**Comment by matthewei** [comment]
the vmpool controller find the number of virtual machines exceeds the set value. So.......

**Comment by matthewei** [comment]
@Muyan0828  any progress for that?

**Comment by xpivarc** [comment]
I think in order to achieve what you want Kubevirt needs to support snapshot of VMPool.
