### ISSUE TITLE
virtctl image-upload failed

### ISSUE THREAD

**Issue by cyent** [kubevirt/kubevirt#10719]
**What happened**:
When I use `virtctl image-upload` command to upload qcow2 to ceph rbd(block mode), it failed:

```
# virtctl image-upload dv cirros-dv1 --size=1Gi  --volume-mode=block --storage-class=csi-rbd-sc --image-path=/root/image/cirros-container-disk-demo.qcow2 --uploadproxy-url=https://10.107.169.25 --insecure
PVC default/cirros-dv2 not found 
DataVolume default/cirros-dv2 created
Waiting for PVC cirros-dv2 upload pod to be ready...
Pod now ready
Uploading data to https://10.107.169.25

 12.13 MiB / 12.13 MiB [=========================================================================================================================================================================================] 100.00% 0s

unexpected return value 400, Saving stream failed: Virtual image size 46137344 is larger than the reported available storage -1. A larger PVC is required.
```

**Environment**:
- KubeVirt version (use `virtctl version`): 1.1.0
- CDI version: 1.57.0
- Kubernetes version (use `kubectl version`): 1.28.2
- Cloud provider or hardware configuration: Dell PowerEdge R620
- OS (e.g. from /etc/os-release): ubuntu22.04.3 x86_64
- Kernel (e.g. `uname -a`): 5.15.0-88-generic x86_64
- CSI: ceph-csi rbd 3.9.0
- ceph-cluster version: 15.2.2 octopus

**Comment by liyang516** [comment]
/var/lib/rancher/rke2/agent/etc/containerd/config.toml.tmpl， add this config，then restart rke2-server and retry

```shell
[plugins.cri]
  device_ownership_from_security_context = true
```

**Comment by cyent** [comment]
Thanks, It works
