### ISSUE TITLE
Expose VM Live Migration Progress As Percentage

### ISSUE THREAD

**Issue by rabin-io** [kubevirt/kubevirt#10722]
I would like to reveal the progress of the migration in a simple numerical form, for example in percentages, in order to allow UI support to indicate the rate of migration progress.

**Describe the solution you'd like**:
I want to see the percentage of progress, and the data transfer rate (MB\sec)

**Describe alternatives you've considered**:
AFAIK, there is none

**Additional context**:

Something like, 
```sh
virsh migrate --verbose --live
```

**Comment by ashutosh7i** [comment]
can i work on this issue?

**Comment by fabiand** [comment]
The UX problem which prevents this feature from being solved is:
Let's assume we want to feed a progress bar, the progressbar is showing completion in %.
In a naive approach (N of M MB remaining), the progressbar can run backwards.

**Comment by rabin-io** [comment]
True, it's a bit confusing, but very legitimate when you understand the reason. And it is in extreme cases that the machine is very "noisy" and sometimes requires manual help to make the transition cleanly.

In such cases that the machine fails to converge several times, and the progress goes back each time, it is possible to alert the user with a message about the reason, and options on how to deal with the problem.

But just because of the case that the progress can go back, not putting a progress bar, I don't think its a problem.

And while we're at it, I think the TRANSFER RATE (MB/s) of the synchronization should be added to the information, as this can help to surface bottlenecks in the live migration progess.
