### ISSUE TITLE
Use official CRD generator

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1073]
Today we have our own CRD generator, onc eit lands, then it makes sense to us ethe official one.

**Comment by rmohr** [comment]
> Today we have our own CRD generator, onc eit lands, then it makes sense to us ethe official one.

What does that mean?

**Comment by rmohr** [comment]
Apart from creating the CRD manifest itself (filling structs and marshalling to yaml), we use the k8s generators. Could you explain what exactly you mean?

**Comment by fabiand** [comment]
This relates to https://github.com/kubernetes/kubernetes/issues/59154
