### ISSUE TITLE
[SIG-Scale] v1.2 and v1.3 planning

### ISSUE THREAD

**Issue by rthallisey** [kubevirt/kubevirt#10737]
v1.2
- [ ] Simulate kubevirt's control-plane performance with kwok
  - [x] https://github.com/kubevirt/kubevirt/issues/11128
  - [ ] https://github.com/kubevirt/kubevirt/issues/11129

v1.3
- [ ] Add metrics for kubevirt control-plane mem/cpu usage
- [ ] Report after each release kubevirt's control-plane mem/cpu usage
- [ ] Add metrics to virt-launcher mem and cpu usage
- [ ] Report after each release kubevirt's mem/cpu overhead
- [ ] Reduce virt-launcher memory overhead

**Comment by matthewei** [comment]
can i do something for it?

**Comment by rthallisey** [comment]
@matthewei, yes.  This list captures our goals at a high-level.  If you want to work on one of these, create and issue outlining your approach and tag SIG-scale.  We'll discuss in our weekly SIG-scale meetings the design and progress - https://calendar.google.com/calendar/u/0/embed?src=kubevirt@cncf.io
