### ISSUE TITLE
Kubevirt 1.1.0 can not create VM

### ISSUE THREAD

**Issue by sawchen** [kubevirt/kubevirt#10754]
**What happened**:

once  I finished install kubevirt-operator and kubevirt-cr, I used the demo yaml to create vm，like this:
wget https://kubevirt.io/labs/manifests/vm.yaml
kubectl apply -f https://kubevirt.io/labs/manifests/vm.yaml
and use command：virtctl start testvm
but it can not start
[root@m1 kubevirt]# kubectl get vms
NAME      AGE     STATUS               READY
testvm    27m     ErrorUnschedulable   False

**What you expected to happen**:
create a VM，and it can be connected

**How to reproduce it (as minimally and precisely as possible)**:

-------------------------step1-----------------------------
$ export RELEASE=v1.1.0
$ kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-operator.yaml
$ kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-cr.yaml

--------------------------step2------------------------------
change kubevirt-cr.yaml  like this,and aplly it:
---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
        - DataVolumes
        - LiveMigration
        - HostDisk
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}

------------step3--------------------
Containerized Data Importer（CDI）

kubectl create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-operator.yaml
kubectl create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-cr.yaml

-------------step4------------------------
wget https://kubevirt.io/labs/manifests/vm.yaml
kubectl apply -f https://kubevirt.io/labs/manifests/vm.yaml

---------------step5--------------------

[root@m1 kubevirt]# virtctl start testvm
VM testvm was scheduled to start

[root@m1 kubevirt]# kubectl get vms
NAME      AGE     STATUS               READY
testvm    27m     ErrorUnschedulable   False

[root@m1 kubevirt]# kubectl get pod 
NAME                         READY   STATUS    RESTARTS   AGE
virt-launcher-testvm-k4slm   0/3     Pending   0          27m

[root@m1 kubevirt]# kubectl describe pod virt-launcher-testvm-k4slm
Name:             virt-launcher-testvm-k4slm
Namespace:        default
Priority:         0
Service Account:  default
Node:             <none>
Labels:           kubevirt.io=virt-launcher
                  kubevirt.io/created-by=be2eb106-1aaf-454b-adad-fc0bd5455b86
                  kubevirt.io/domain=testvm
                  kubevirt.io/size=small
                  vm.kubevirt.io/name=testvm
Annotations:      kubectl.kubernetes.io/default-container: compute
                  kubevirt.io/domain: testvm
                  kubevirt.io/migrationTransportUnix: true
                  kubevirt.io/vm-generation: 4
                  post.hook.backup.velero.io/command: ["/usr/bin/virt-freezer", "--unfreeze", "--name", "testvm", "--namespace", "default"]
                  post.hook.backup.velero.io/container: compute
                  pre.hook.backup.velero.io/command: ["/usr/bin/virt-freezer", "--freeze", "--name", "testvm", "--namespace", "default"]
                  pre.hook.backup.velero.io/container: compute
                  traffic.sidecar.istio.io/kubevirtInterfaces: k6t-eth0
Status:           Pending
IP:               
IPs:              <none>
Controlled By:    VirtualMachineInstance/testvm
Init Containers:
  container-disk-binary:
    Image:      10.30.60.148/kubevirt/virt-launcher:v1.1.0
    Port:       <none>
    Host Port:  <none>
    Command:
      /usr/bin/cp
      /usr/bin/container-disk
      /init/usr/bin/container-disk
    Limits:
      cpu:     100m
      memory:  40M
    Requests:
      cpu:     10m
      memory:  1M
    Environment:
      XDG_CACHE_HOME:   /var/run/kubevirt-private
      XDG_CONFIG_HOME:  /var/run/kubevirt-private
      XDG_RUNTIME_DIR:  /var/run
    Mounts:
      /init/usr/bin from virt-bin-share-dir (rw)
  volumecontainerdisk-init:
    Image:      quay.io/kubevirt/cirros-container-disk-demo
    Port:       <none>
    Host Port:  <none>
    Command:
      /usr/bin/container-disk
    Args:
      --no-op
    Limits:
      cpu:     10m
      memory:  40M
    Requests:
      cpu:                1m
      ephemeral-storage:  50M
      memory:             1M
    Environment:          <none>
    Mounts:
      /usr/bin from virt-bin-share-dir (rw)
      /var/run/kubevirt-ephemeral-disks/container-disk-data/be2eb106-1aaf-454b-adad-fc0bd5455b86 from container-disks (rw)
Containers:
  compute:
    Image:      10.30.60.148/kubevirt/virt-launcher:v1.1.0
    Port:       <none>
    Host Port:  <none>
    Command:
      /usr/bin/virt-launcher-monitor
      --qemu-timeout
      258s
      --name
      testvm
      --uid
      be2eb106-1aaf-454b-adad-fc0bd5455b86
      --namespace
      default
      --kubevirt-share-dir
      /var/run/kubevirt
      --ephemeral-disk-dir
      /var/run/kubevirt-ephemeral-disks
      --container-disk-dir
      /var/run/kubevirt/container-disks
      --grace-period-seconds
      45
      --hook-sidecars
      0
      --ovmf-path
      /usr/share/OVMF
      --run-as-nonroot
    Limits:
      devices.kubevirt.io/kvm:        1
      devices.kubevirt.io/tun:        1
      devices.kubevirt.io/vhost-net:  1
    Requests:
      cpu:                            100m
      devices.kubevirt.io/kvm:        1
      devices.kubevirt.io/tun:        1
      devices.kubevirt.io/vhost-net:  1
      ephemeral-storage:              50M
      memory:                         317880392
    Environment:
      XDG_CACHE_HOME:   /var/run/kubevirt-private
      XDG_CONFIG_HOME:  /var/run/kubevirt-private
      XDG_RUNTIME_DIR:  /var/run
      POD_NAME:         virt-launcher-testvm-k4slm (v1:metadata.name)
    Mounts:
      /var/run/kubevirt from public (rw)
      /var/run/kubevirt-ephemeral-disks from ephemeral-disks (rw)
      /var/run/kubevirt-private from private (rw)
      /var/run/kubevirt/container-disks from container-disks (rw)
      /var/run/kubevirt/hotplug-disks from hotplug-disks (rw)
      /var/run/kubevirt/sockets from sockets (rw)
      /var/run/libvirt from libvirt-runtime (rw)
  volumecontainerdisk:
    Image:      quay.io/kubevirt/cirros-container-disk-demo
    Port:       <none>
    Host Port:  <none>
    Command:
      /usr/bin/container-disk
    Args:
      --copy-path
      /var/run/kubevirt-ephemeral-disks/container-disk-data/be2eb106-1aaf-454b-adad-fc0bd5455b86/disk_0
    Limits:
      cpu:     10m
      memory:  40M
    Requests:
      cpu:                1m
      ephemeral-storage:  50M
      memory:             1M
    Environment:          <none>
    Mounts:
      /usr/bin from virt-bin-share-dir (rw)
      /var/run/kubevirt-ephemeral-disks/container-disk-data/be2eb106-1aaf-454b-adad-fc0bd5455b86 from container-disks (rw)
  guest-console-log:
    Image:      10.30.60.148/kubevirt/virt-launcher:v1.1.0
    Port:       <none>
    Host Port:  <none>
    Command:
      /usr/bin/virt-tail
    Args:
      --logfile
      /var/run/kubevirt-private/be2eb106-1aaf-454b-adad-fc0bd5455b86/virt-serial0-log
    Limits:
      cpu:     15m
      memory:  60M
    Requests:
      cpu:     5m
      memory:  35M
    Environment:
      VIRT_LAUNCHER_LOG_VERBOSITY:  2
    Mounts:
      /var/run/kubevirt-private from private (ro)
Readiness Gates:
  Type                                   Status
  kubevirt.io/virtual-machine-unpaused   True 
Conditions:
  Type                                   Status
  PodScheduled                           False 
  kubevirt.io/virtual-machine-unpaused   True 
Volumes:
  private:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  public:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  sockets:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  virt-bin-share-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  libvirt-runtime:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  ephemeral-disks:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  container-disks:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  hotplug-disks:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:      
    SizeLimit:   <unset>
QoS Class:       Burstable
Node-Selectors:  kubernetes.io/arch=amd64
                 kubevirt.io/schedulable=true
Tolerations:     node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                 node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:
  Type     Reason            Age    From               Message
  ----     ------            ----   ----               -------
  Warning  FailedScheduling  2m59s  default-scheduler  0/4 nodes are available: 4 Insufficient devices.kubevirt.io/kvm. preemption: 0/4 nodes are available: 4 No preemption victims found for incoming pod..

[root@m1 kubevirt]#kubectl get all -n kubevirt
Warning: kubevirt.io/v1 VirtualMachineInstancePresets is now deprecated and will be removed in v2.
NAME                                   READY   STATUS    RESTARTS   AGE
pod/virt-api-84b79979c8-5klpf          1/1     Running   0          2d16h
pod/virt-api-84b79979c8-72ml2          1/1     Running   0          2d16h
pod/virt-controller-76c94699d9-4l9lt   1/1     Running   0          2d16h
pod/virt-controller-76c94699d9-p7csh   1/1     Running   0          2d16h
pod/virt-handler-74rwp                 1/1     Running   0          2d16h
pod/virt-handler-8tphv                 1/1     Running   0          2d16h
pod/virt-handler-bcrfc                 1/1     Running   0          2d16h
pod/virt-handler-ggntt                 1/1     Running   0          2d16h
pod/virt-operator-5fcbc76b84-nnc69     1/1     Running   0          2d16h
pod/virt-operator-5fcbc76b84-w4jd7     1/1     Running   0          2d16h

NAME                                  TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/kubevirt-operator-webhook     ClusterIP   10.110.93.198    <none>        443/TCP   2d16h
service/kubevirt-prometheus-metrics   ClusterIP   None             <none>        443/TCP   2d16h
service/virt-api                      ClusterIP   10.109.136.139   <none>        443/TCP   2d16h
service/virt-exportproxy              ClusterIP   10.111.85.21     <none>        443/TCP   2d16h

NAME                          DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
daemonset.apps/virt-handler   4         4         4       4            4           kubernetes.io/os=linux   2d16h

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/virt-api          2/2     2            2           2d16h
deployment.apps/virt-controller   2/2     2            2           2d16h
deployment.apps/virt-operator     2/2     2            2           2d16h

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/virt-api-84b79979c8          2         2         2       2d16h
replicaset.apps/virt-controller-76c94699d9   2         2         2       2d16h
replicaset.apps/virt-operator-5fcbc76b84     2         2         2       2d16h

NAME                            AGE     PHASE
kubevirt.kubevirt.io/kubevirt   2d16h   Deployed

**What you expected to happen**:
create a VM，and it can be connected

**Environment**:
- KubeVirt version (use `virtctl version`): v1.1.0
- Kubernetes version (use `kubectl version`): 1.27.6
- VM or VMI specifications: https://kubevirt.io/labs/manifests/vm.yaml
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Anolis OS 8.8
- Kernel (e.g. `uname -a`): 5.10.134-13.an8.x86_64
- Install tools: N/A
- Others: N/A

**Comment by vasiliy-ul** [comment]
> Warning FailedScheduling 2m59s default-scheduler 0/4 nodes are available: 4 Insufficient devices.kubevirt.io/kvm. preemption: 0/4 nodes are available: 4 No preemption victims found for incoming pod..

This message suggests that your nodes do not have kvm support. Is it a bare-metal cluster or a set of virtual machines? You can run `virt-host-validate` to check what is supported and enable the missing pieces.

Alternatively, you can try to run in emulation mode https://github.com/kubevirt/kubevirt/blob/main/docs/software-emulation.md. Though, I would recommend to use hardware virtualization.

**Comment by feitnomore** [comment]
My guess is that you don't have KVM enabled on your nodes according to the following statement:
```
Warning FailedScheduling 2m59s default-scheduler 0/4 nodes are available: 4 Insufficient devices.kubevirt.io/kvm. preemption: 0/4 nodes are available: 4 No preemption victims found for incoming pod..
```
