### ISSUE TITLE
Can I keep domain shutoff without exiting virt-launcher pod?

### ISSUE THREAD

**Issue by AmazingPangWei** [kubevirt/kubevirt#10760]
**Is your feature request related to a problem? Please describe**:
Currently, virt-launcher pod will exit if domain shutoff, which is a very good design, but sometimes it really bothers me. And here are some of my usage scenarios:

1. I just want a temporary shutdown, but which causes my virt-launcher pod recreation.
2. I usually debug domain xml to solve the problem of vm image adaptation, which means I need to shutdown a vm and edit domain xml frequently.
3. I need memory snapshot as mentioned before https://github.com/kubevirt/kubevirt/issues/10609, but no one replies. So I wanna do this manually. Vm will shutdown if `save` is executed, which also causes my virt-launcher pod recreation.

**Describe the solution you'd like**:
 I wanna know is there a way to keep domain shutoff without exiting virt-launcher pod.

**Comment by victortoso** [comment]
Have you tried the alive-after-failure annotation?

```yaml
metadata:
  annotations:
    kubevirt.io/keep-launcher-alive-after-failure: "true"
```

**Comment by AmazingPangWei** [comment]
@victortoso Thank you for your reply.

I've tried the alive-after-failure annotation, but it doesn't work because virt-launcher will exit normally(exit code is 0) if QEMU process exits after I  `shutdown` or `save` a domain.

**Comment by xpivarc** [comment]
Hi @AmazingPangWei , if you pause the VM, the Pod stays around.

**Comment by matthewei** [comment]
> Hi @AmazingPangWei , if you pause the VM, the Pod stays around.

from his description, he want to edit vm's xml.

**Comment by matthewei** [comment]
@AmazingPangWei This is expected.

**Comment by wolfXHH** [comment]
We have the same question, can someone explain why the virt-launcher must exit after the operation vm shutdown?
