### ISSUE TITLE
 Whether bootOrder can automatically switch

### ISSUE THREAD

**Issue by ZhangSetSail** [kubevirt/kubevirt#10764]
**Is your feature request related to a problem? Please describe**:
I deployed a centos image virtual machine. After the image boot, I installed the operating system step by step. After the installation was completed, I was prompted to restart. After restarting, the server entered the operating system installation boot again.

<img width="1483" alt="image" src="https://github.com/kubevirt/kubevirt/assets/101104760/6ee12b86-17fc-49e3-84d1-afa21836f010">

The key reason is bootOrder

<img width="429" alt="image" src="https://github.com/kubevirt/kubevirt/assets/101104760/5e97fb7b-694b-41ab-ad46-cad70384b87d">

**Describe the solution you'd like**:

I hope there is some way he can automatically switch the startup sequence

**Describe alternatives you've considered**:
manual operation

**Additional context**:

**Comment by vasiliy-ul** [comment]
Shouldn't it work as you need if you put `harddrive` first (i.e. with `bootOrder 1`)? On boot, if there is no OS installed, it will switch to the next device `cdromiso`.

**Comment by ZhangSetSail** [comment]
Sorry, this seems to be my problem. It has been verified that the above method is OK.

**Comment by vasiliy-ul** [comment]
It’s okay, no worries. Feel free to raise questions either in the github issue tracker or in slack if you face any troubles.
