### ISSUE TITLE
virtctl: line 1: Not: command not found

### ISSUE THREAD

**Issue by ishankhare07** [kubevirt/kubevirt#10761]
**What happened**:
Fresh installation of virtctl does not work

**What you expected to happen**:
virtctl should print help commands or other output

**How to reproduce it (as minimally and precisely as possible)**:
Install virtctl either through the installation script or through assets under release

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): macOS 14.1.1 | arch arm64 (M1)
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by ZhangSetSail** [comment]
I have encountered this problem before. It may be related to the namespace in which you deploy kubevirt, or it may be related to your network. You can directly use.

This is the virtctl address I downloaded today, you can refer to it
https://github.com/kubevirt/kubevirt/releases/download/v1.1.0-alpha.0/virtctl-v1.1.0-alpha.0-linux-amd64

**Comment by zhlhahaha** [comment]
I see you are using Mac, can you give the following binary a try:
https://github.com/kubevirt/kubevirt/releases/download/v1.1.0/virtctl-v1.1.0-darwin-arm64

By the way, we have not verified KubeVirt on Mac OS.

**Comment by pbarker** [comment]
tried https://github.com/kubevirt/kubevirt/releases/download/v1.1.0/virtctl-v1.1.0-darwin-arm64 and that doesn't work on m1 for me
