### ISSUE TITLE
VM can not access myself by Pod IP when use masquerade mode.

### ISSUE THREAD

**Issue by a180285** [kubevirt/kubevirt#10772]
**What happened**:
I use kubevirt to start a VM. And network is masquerade mode.
Let's say my pod IP is 10.0.0.10, my VM IP is 192.168.2.2
When I run `ssh 10.0.0.10` in VM bash. I cannot access myself(VM). But I can run `ssh 10.0.0.10` from other pod to access the VM.

**What you expected to happen**:
I expect that ssh POD IP from VM can access myself.

**How to reproduce it (as minimally and precisely as possible)**:
Run a VM with masquerade mode. And try access POD ip in VM.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.59.1
- Kubernetes version (use `kubectl version`): 1.26.11
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: Local PC
- OS (e.g. from /etc/os-release): Ubuntu "22.04.2 LTS (Jammy Jellyfish)"
- Kernel (e.g. `uname -a`): `Linux  5.15.0-71-generic #78-Ubuntu SMP Tue Apr 18 09:00:29 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux`

**Comment by a180285** [comment]
I found that I can solve it by this PR: https://github.com/kubevirt/kubevirt/pull/10751 

But after more testing on different nodes. I found that. above fix only works for `br_netfilter` not loaded. or disabled by `sysctl -w  net.bridge.bridge-nf-call-iptables=0`

If `br_netfilter` is enabled the above fix is failed. And I try many rules by `nft` rules. also fails. E.g. specific the input/output interface in nft rules also doesn't work.

So at this point I just disabled the `br_netfilter` in my own cluster.

I have no idea now. Why that happens.

**Comment by EdDev** [comment]
This sounds like a very unique edge case.
Access "self" through the exposed IP is not currently supported and there needs to be a very good reason to do so.

Usually, a guest that needs to access "self" will just resolve to its localhost loopback address (127.0.0.1).
Trying to tweak the pod nftable rules may end up colliding with other scenarios (e.g. istio) and break flows.

Why can't you resolve this at the guest level? Teach it to resolve to its loopback address.

If nothing fits your need, then you could take advantage of the new network binding plugin solution. It allows you to create your own network binding by creating a CNI plugin and a sidecar container. In your case, you will need a CNI plugin that teaks the nftable of the pod per your needs.

**Comment by a180285** [comment]
Yes, I think it's also a edge case.
I was meet this issue, when I want to setup a k8s cluster by kubevirt VMs. Which requires by kubeadm config. I notice that the first node of k8s can not access self.

BTW, I found another method which can also fix, but a little hack
```bash
nft add table netdev filter;
nft add chain netdev filter tap0 { type filter hook ingress device "tap0" priority 1\; policy accept\; };
nft insert rule netdev filter tap0 ip saddr 192.168.2.2 ip daddr 10.0.0.10 ip saddr set 10.0.0.10 ip daddr set 192.168.2.2 accept
```

which reverse the src and dst of the packet. Just in case some one to dive deep to this issue. As I think the current fixs is hard to merge back.

**Comment by caijian76** [comment]
You may  set VM interface NOT use masquerade mode , you VM IP is the pod IP

**Comment by EdDev** [comment]
I think this issue can be closed for now.
If further discussion is requested, it can be re-open or discussed through a new issue.

/close
