### ISSUE TITLE
When CDI support arm64 platform

### ISSUE THREAD

**Issue by liyang516** [kubevirt/kubevirt#10778]
When cdi can support the arm64 architecture？

**Comment by liyang516** [comment]
Only kubevirt support arm64 now，we need cdi too

**Comment by xpivarc** [comment]
@zhlhahaha @mhenriks

**Comment by zhlhahaha** [comment]
Sorry, I am busy these days. I am unable to provide a definite schedule.

**Comment by liyang516** [comment]
> Sorry, I am busy these days. I am unable to provide a definite schedule.

Hope to support as soon as possible
