### ISSUE TITLE
Failed to get \"write\" lock\nIs another process using the image [/var/run/kubevirt-private/vmi-disks/manual37/disk.img]

### ISSUE THREAD

**Issue by ZhangSetSail** [kubevirt/kubevirt#10785]
**What happened**:
virtual machine cannot start after adding a disk

**What you expected to happen**:
normal start

**How to reproduce it (as minimally and precisely as possible)**:
this is my vm yaml
<img width="693" alt="image" src="https://github.com/kubevirt/kubevirt/assets/101104760/b2255caa-3729-4d6e-8ce2-25e047958b17">

**Additional context**:
<img width="1511" alt="image" src="https://github.com/kubevirt/kubevirt/assets/101104760/6fe134d5-05e7-494a-9e36-8ecb4128a412">

**Environment**:
- KubeVirt version (use `virtctl version`): v1.1.0-alpha.0
- Kubernetes version (use `kubectl version`): 23
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by matthewei** [comment]
could you give us  more info? such as virt-launcher-pod's log?

**Comment by xpivarc** [comment]
Are you sharing the PVC with another Pod or VM?

**Comment by ZhangSetSail** [comment]
Sorry for the late reply due to illness in the past two days. I will sort it out in a moment.

**Comment by ZhangSetSail** [comment]
<img width="1713" alt="image" src="https://github.com/kubevirt/kubevirt/assets/101104760/03b30874-dacf-4895-95fe-54b0b39dcff0">

**Comment by ZhangSetSail** [comment]
The root cause of the problem was found. As mentioned above, the sc I bound was created by ourselves and indeed shared pvc with other pods.
