### ISSUE TITLE
vmi crash , can not work

### ISSUE THREAD

**Issue by reckless-huang** [kubevirt/kubevirt#10798]
### log:
`{"component":"virt-handler","level":"info","msg":"Successfully configured tap device: tap0","pos":"common.go:513","timestamp":"2023-11-28T08:36:09.794670Z"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"win10","namespace":"default","pos":"vm.go:1444","reason":"unknown error encountered sending command SyncVMI: rpc error: code = Unavailable desc = transport is closing","timestamp":"2023-11-28T08:36:09.936615Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/win10","pos":"vm.go:1052","reason":"unknown error encountered sending command SyncVMI: rpc error: code = Unavailable desc = transport is closing","timestamp":"2023-11-28T08:36:09.966434Z"}
{"component":"virt-handler","level":"info","msg":"Processing event default/win10","pos":"vm.go:1305","timestamp":"2023-11-28T08:36:09.966645Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled\n","name":"win10","namespace":"default","pos":"vm.go:1307","timestamp":"2023-11-28T08:36:09.966709Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","level":"info","msg":"Domain does not exist","pos":"vm.go:1314","timestamp":"2023-11-28T08:36:09.966753Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"Processing vmi update","name":"win10","namespace":"default","pos":"vm.go:1436","timestamp":"2023-11-28T08:36:09.966902Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","kind":"","level":"info","msg":"containerdisk virtiocontainerdisk not yet ready","name":"win10","namespace":"default","pos":"mount.go:359","timestamp":"2023-11-28T08:36:09.971698Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","kind":"","level":"info","msg":"Synchronization loop succeeded.","name":"win10","namespace":"default","pos":"vm.go:1460","timestamp":"2023-11-28T08:36:10.001313Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","level":"info","msg":"processed VirtualMachineInstance default/win10","pos":"vm.go:1055","timestamp":"2023-11-28T08:36:10.001418Z"}
{"component":"virt-handler","level":"info","msg":"Processing event default/win10","pos":"vm.go:1305","timestamp":"2023-11-28T08:36:10.001472Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled\n","name":"win10","namespace":"default","pos":"vm.go:1307","timestamp":"2023-11-28T08:36:10.001508Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","level":"info","msg":"Domain does not exist","pos":"vm.go:1314","timestamp":"2023-11-28T08:36:10.001541Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"Processing vmi update","name":"win10","namespace":"default","pos":"vm.go:1436","timestamp":"2023-11-28T08:36:10.001679Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","kind":"","level":"info","msg":"containerdisk virtiocontainerdisk not yet ready","name":"win10","namespace":"default","pos":"mount.go:359","timestamp":"2023-11-28T08:36:10.006587Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","kind":"","level":"info","msg":"Synchronization loop succeeded.","name":"win10","namespace":"default","pos":"vm.go:1460","timestamp":"2023-11-28T08:36:10.013471Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","level":"info","msg":"processed VirtualMachineInstance default/win10","pos":"vm.go:1055","timestamp":"2023-11-28T08:36:10.013548Z"}
{"component":"virt-handler","level":"info","msg":"Processing event default/win10","pos":"vm.go:1305","timestamp":"2023-11-28T08:36:10.971949Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled\n","name":"win10","namespace":"default","pos":"vm.go:1307","timestamp":"2023-11-28T08:36:10.972077Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","level":"info","msg":"Domain does not exist","pos":"vm.go:1314","timestamp":"2023-11-28T08:36:10.972124Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"No update processing required","name":"win10","namespace":"default","pos":"vm.go:1439","timestamp":"2023-11-28T08:36:10.972311Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","kind":"","level":"info","msg":"Synchronization loop succeeded.","name":"win10","namespace":"default","pos":"vm.go:1460","timestamp":"2023-11-28T08:36:11.002866Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","level":"info","msg":"processed VirtualMachineInstance default/win10","pos":"vm.go:1055","timestamp":"2023-11-28T08:36:11.002962Z"}
{"component":"virt-handler","level":"info","msg":"Processing event default/win10","pos":"vm.go:1305","timestamp":"2023-11-28T08:36:11.004050Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Failed\n","name":"win10","namespace":"default","pos":"vm.go:1307","timestamp":"2023-11-28T08:36:11.004126Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","level":"info","msg":"Domain does not exist","pos":"vm.go:1314","timestamp":"2023-11-28T08:36:11.004165Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"Cleaning up local data for finalized vmi.","name":"win10","namespace":"default","pos":"vm.go:1378","timestamp":"2023-11-28T08:36:11.004306Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","kind":"","level":"info","msg":"Processing local ephemeral data cleanup for shutdown domain.","name":"win10","namespace":"default","pos":"vm.go:1433","timestamp":"2023-11-28T08:36:11.004369Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","kind":"","level":"info","msg":"Performing final local cleanup for vmi with uid 0b9a7e06-5b93-479b-8485-03abb19c93fb","name":"win10","namespace":"default","pos":"vm.go:1564","timestamp":"2023-11-28T08:36:11.004428Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","kind":"","level":"info","msg":"Found container disk mount entries","name":"win10","namespace":"default","pos":"mount.go:330","timestamp":"2023-11-28T08:36:11.004525Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","kind":"","level":"info","msg":"Looking to see if containerdisk is mounted at path /var/lib/kubelet/pods/6d6332f3-f1a7-4f77-8afd-b20bd9b8222a/volumes/kubernetes.io~empty-dir/container-disks/disk_2.img","name":"win10","namespace":"default","pos":"mount.go:333","timestamp":"2023-11-28T08:36:11.004570Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","kind":"","level":"info","msg":"unmounting container disk at path /var/lib/kubelet/pods/6d6332f3-f1a7-4f77-8afd-b20bd9b8222a/volumes/kubernetes.io~empty-dir/container-disks/disk_2.img","name":"win10","namespace":"default","pos":"mount.go:337","timestamp":"2023-11-28T08:36:11.008254Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","kind":"","level":"info","msg":"Cleaning up remaining hotplug volumes","name":"win10","namespace":"default","pos":"mount.go:671","timestamp":"2023-11-28T08:36:11.022415Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","level":"info","msg":"Remove watchdog file /var/run/kubevirt/watchdog-files/default_win10","pos":"watchdog.go:67","timestamp":"2023-11-28T08:36:11.022665Z"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Removing domain from cache during final cleanup","name":"win10","namespace":"default","pos":"vm.go:1596","timestamp":"2023-11-28T08:36:11.022751Z","uid":""}
{"component":"virt-handler","kind":"","level":"info","msg":"Synchronization loop succeeded.","name":"win10","namespace":"default","pos":"vm.go:1460","timestamp":"2023-11-28T08:36:11.022852Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","level":"info","msg":"processed VirtualMachineInstance default/win10","pos":"vm.go:1055","timestamp":"2023-11-28T08:36:11.022899Z"}
{"component":"virt-handler","level":"info","msg":"Processing event default/win10","pos":"vm.go:1305","timestamp":"2023-11-28T08:36:11.022942Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Failed\n","name":"win10","namespace":"default","pos":"vm.go:1307","timestamp":"2023-11-28T08:36:11.022978Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","level":"info","msg":"Domain does not exist","pos":"vm.go:1314","timestamp":"2023-11-28T08:36:11.023011Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"Cleaning up local data for finalized vmi.","name":"win10","namespace":"default","pos":"vm.go:1378","timestamp":"2023-11-28T08:36:11.023093Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","kind":"","level":"info","msg":"Processing local ephemeral data cleanup for shutdown domain.","name":"win10","namespace":"default","pos":"vm.go:1433","timestamp":"2023-11-28T08:36:11.023150Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","kind":"","level":"info","msg":"Performing final local cleanup for vmi with uid 0b9a7e06-5b93-479b-8485-03abb19c93fb","name":"win10","namespace":"default","pos":"vm.go:1564","timestamp":"2023-11-28T08:36:11.023214Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","kind":"","level":"info","msg":"No container disk mount entries found to unmount","name":"win10","namespace":"default","pos":"mount.go:326","timestamp":"2023-11-28T08:36:11.023320Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","kind":"","level":"info","msg":"Cleaning up remaining hotplug volumes","name":"win10","namespace":"default","pos":"mount.go:671","timestamp":"2023-11-28T08:36:11.023369Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","level":"info","msg":"Remove watchdog file /var/run/kubevirt/watchdog-files/default_win10","pos":"watchdog.go:67","timestamp":"2023-11-28T08:36:11.023439Z"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Removing domain from cache during final cleanup","name":"win10","namespace":"default","pos":"vm.go:1596","timestamp":"2023-11-28T08:36:11.023488Z","uid":""}
{"component":"virt-handler","kind":"","level":"info","msg":"Synchronization loop succeeded.","name":"win10","namespace":"default","pos":"vm.go:1460","timestamp":"2023-11-28T08:36:11.023546Z","uid":"0b9a7e06-5b93-479b-8485-03abb19c93fb"}
{"component":"virt-handler","level":"info","msg":"processed VirtualMachineInstance default/win10","pos":"vm.go:1055","timestamp":"2023-11-28T08:36:11.023588Z"}
{"component":"virt-handler","level":"info","msg":"Processing event default/win10","pos":"vm.go:1305","timestamp":"2023-11-28T08:36:11.064595Z"}
{"component":"virt-handler","level":"info","msg":"VMI does not exist","pos":"vm.go:1309","timestamp":"2023-11-28T08:36:11.064664Z"}
{"component":"virt-handler","level":"info","msg":"Domain does not exist","pos":"vm.go:1314","timestamp":"2023-11-28T08:36:11.064733Z"}
{"component":"virt-handler","kind":"VirtualMachineInstance","level":"info","msg":"Processing local ephemeral data cleanup for shutdown domain.","name":"win10","namespace":"default","pos":"vm.go:1433","timestamp":"2023-11-28T08:36:11.064820Z","uid":""}
{"component":"virt-handler","kind":"VirtualMachineInstance","level":"info","msg":"Performing final local cleanup for vmi with uid ","name":"win10","namespace":"default","pos":"vm.go:1564","timestamp":"2023-11-28T08:36:11.064922Z","uid":""}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Removing domain from cache during final cleanup","name":"win10","namespace":"default","pos":"vm.go:1596","timestamp":"2023-11-28T08:36:11.065023Z","uid":""}
{"component":"virt-handler","kind":"VirtualMachineInstance","level":"info","msg":"Synchronization loop succeeded.","name":"win10","namespace":"default","pos":"vm.go:1460","timestamp":"2023-11-28T08:36:11.065115Z","uid":""}
{"component":"virt-handler","level":"info","msg":"processed VirtualMachineInstance default/win10","pos":"vm.go:1055","timestamp":"2023-11-28T08:36:11.065189Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.609097786\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.351399Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.609097786\": WRITE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.351479Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.609097786\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.351392Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.609097786\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.351392Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.609097786\": WRITE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.351520Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.609097786\": WRITE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.351534Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.609097786\": RENAME","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.352040Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/kubelet_internal_checkpoint\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.352093Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.609097786\": RENAME","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.352070Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/kubelet_internal_checkpoint\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.352144Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.609097786\": RENAME","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.352104Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/kubelet_internal_checkpoint\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.352223Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.411154001\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.352506Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.411154001\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.352512Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.411154001\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.352524Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.411154001\": WRITE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.352552Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.411154001\": WRITE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.352564Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.411154001\": WRITE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.352567Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.411154001\": RENAME","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.352815Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.411154001\": RENAME","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.352818Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/kubelet_internal_checkpoint\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.352854Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.411154001\": RENAME","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.352839Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/kubelet_internal_checkpoint\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.352871Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/kubelet_internal_checkpoint\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.352900Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: resourceName: tun","pos":"generic_device.go:255","timestamp":"2023-11-28T08:36:11.353360Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: request: [\u0026ContainerAllocateRequest{DevicesIDs:[tun54],}]","pos":"generic_device.go:256","timestamp":"2023-11-28T08:36:11.353453Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: resourceName: kvm","pos":"generic_device.go:255","timestamp":"2023-11-28T08:36:11.353982Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: request: [\u0026ContainerAllocateRequest{DevicesIDs:[kvm98],}]","pos":"generic_device.go:256","timestamp":"2023-11-28T08:36:11.354044Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.527606140\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.354600Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.527606140\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.354603Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.527606140\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.354606Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.527606140\": WRITE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.354675Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.527606140\": WRITE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.354711Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.527606140\": WRITE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.354715Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.527606140\": RENAME","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.354990Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.527606140\": RENAME","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.354991Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.527606140\": RENAME","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.355004Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/kubelet_internal_checkpoint\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.355029Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/kubelet_internal_checkpoint\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.355036Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/kubelet_internal_checkpoint\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.355042Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.394772651\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.355504Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.394772651\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.355507Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.394772651\": WRITE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.355564Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.394772651\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.355497Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.394772651\": WRITE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.355587Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.394772651\": WRITE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.355602Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.394772651\": RENAME","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.355901Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.394772651\": RENAME","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.355912Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/.394772651\": RENAME","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.355923Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/kubelet_internal_checkpoint\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.355982Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/kubelet_internal_checkpoint\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.355971Z"}
{"component":"virt-handler","level":"info","msg":"health Event: \"/var/lib/kubelet/device-plugins/kubelet_internal_checkpoint\": CREATE","pos":"generic_device.go:338","timestamp":"2023-11-28T08:36:11.355993Z"}
{"component":"virt-handler","level":"info","msg":"Processing event default/win10","pos":"vm.go:1305","timestamp":"2023-11-28T08:36:17.005040Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled\n","name":"win10","namespace":"default","pos":"vm.go:1307","timestamp":"2023-11-28T08:36:17.005163Z","uid":"85842fb0-5026-4e79-9a98-dd468c1bd266"}
{"component":"virt-handler","level":"info","msg":"Domain does not exist","pos":"vm.go:1314","timestamp":"2023-11-28T08:36:17.005274Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"Processing vmi update","name":"win10","namespace":"default","pos":"vm.go:1436","timestamp":"2023-11-28T08:36:17.005535Z","uid":"85842fb0-5026-4e79-9a98-dd468c1bd266"}
{"component":"virt-handler","kind":"","level":"info","msg":"all containerdisks are ready","name":"win10","namespace":"default","pos":"mount.go:367","timestamp":"2023-11-28T08:36:17.015974Z","uid":"85842fb0-5026-4e79-9a98-dd468c1bd266"}
{"component":"virt-handler","kind":"","level":"info","msg":"Bind mounting container disk at /data/docker/overlay2/e3a533ceeb4941cfda764d8d59a5072f56ad4640f18652054b93c3a549a0765a/merged/disk/downloaded to /var/lib/kubelet/pods/23856d72-7f69-4872-b436-ebaa12c8e759/volumes/kubernetes.io~empty-dir/container-disks/disk_2.img","name":"win10","namespace":"default","pos":"mount.go:249","timestamp":"2023-11-28T08:36:17.020285Z","uid":"85842fb0-5026-4e79-9a98-dd468c1bd266"}
{"component":"virt-handler","level":"info","msg":"Created tap device: tap0 in PID: 40766","pos":"common.go:410","timestamp":"2023-11-28T08:36:17.060281Z"}
{"component":"virt-handler","level":"info","msg":"Looking for tap device: tap0","pos":"common.go:494","timestamp":"2023-11-28T08:36:17.060560Z"}
{"component":"virt-handler","level":"info","msg":"Successfully configured tap device: tap0","pos":"common.go:513","timestamp":"2023-11-28T08:36:17.061380Z"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"win10","namespace":"default","pos":"vm.go:1444","reason":"unknown error encountered sending command SyncVMI: rpc error: code = Unavailable desc = transport is closing","timestamp":"2023-11-28T08:36:17.122375Z","uid":"85842fb0-5026-4e79-9a98-dd468c1bd266"}`
### system info:
`Client Version: version.Info{GitVersion:"v0.37.2", GitCommit:"0e63b5f9d5debd68e5247c5fb83f285d66d618a3", GitTreeState:"clean", BuildDate:"2021-01-27T21:35:58Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.37.2-dirty", GitCommit:"0e63b5f9d5debd68e5247c5fb83f285d66d618a3", GitTreeState:"dirty", BuildDate:"2021-01-27T21:57:07Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
`
### k8s:
`Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.16", GitCommit:"e37e4ab4cc8dcda84f1344dda47a97bb1927d074", GitTreeState:"clean", BuildDate:"2021-10-27T16:25:59Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.16", GitCommit:"e37e4ab4cc8dcda84f1344dda47a97bb1927d074", GitTreeState:"clean", BuildDate:"2021-10-27T16:20:18Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}`
CNI cilium 

### kernel:
`5.4.194-1.el7.elrepo.x86_64
centos7`

vmi crash , can not work

### my yaml:
`apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: win10
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: win10
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - bootOrder: 1
            cdrom:
              bus: sata
            name: cdromiso
          - disk:
              bus: virtio
            name: harddrive
          - cdrom:
              bus: sata
            name: virtiocontainerdisk
          interfaces:
          - masquerade: {}
            model: e1000 
            name: default
        resources:
          requests:
            memory: 2G
      networks:
      - name: default
        pod: {}
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: iso-winserver2016
      - name: harddrive
        hostDisk:
          capacity: 50Gi
          path: /data/disk.img
          type: DiskOrCreate
      - containerDisk:
          image: kubevirt/virtio-container-disk
        name: virtiocontainerdisk`

 I look forward to hearing from you soon.

**Comment by aburdenthehand** [comment]
Hello,
It looks like you're running KubeVirt v0.37 on Kubernetes v1.19
Both of these are past their end of life. I would recommend upgrading to a stable version of both Kubernetes and KubeVirt. You can see our version support matrix here: https://github.com/kubevirt/sig-release/blob/main/releases/k8s-support-matrix.md
