### ISSUE TITLE
Create a place to document annotations

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1080]
With at least #1047 we have an annotation which is useful atm.

It would be good to have a place where we document annotations - just for developers. Thus not in the user-guide.

**Comment by fabiand** [comment]
@booxter can you find a documetn where this can be added or potential create a new one for it?

**Comment by rmohr** [comment]
FYI here is what kubernetes has: https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/

**Comment by booxter** [comment]
@fabiand do we have any more user visible annotations now that we migrated the interface model to a first class interface field? Is there anything else to document in context of this issue?

There are several "internal" annotations used by components, f.e. for heartbeats; do we want to document those? The original description is not clear about it and suggests to find a place to document "these" ("useful") annotations. Please clarify.

**Comment by fabiand** [comment]
Mkaing this a bug, because we have annotations already.

**Comment by booxter** [comment]
I read the latest comments as a suggestion to document internal annotations too. OK I will post a PR.

**Comment by booxter** [comment]
@fabiand @davidvossel there is an argument in PR that this information should be captured in the code and then it will be easier to maintain its relevance. What do we want to do here - having a dev doc or inline comments?
