### ISSUE TITLE
Provide customized kubeletRootDir in kubeVirt CRD

### ISSUE THREAD

**Issue by panpan0000** [kubevirt/kubevirt#10803]
for some k8s distribution( Rancher/Openshift) , the default kubelet root dir may not be standard `/var/lib/kubelet`
the device plugin requires to mount the hostpath.
in that case, we can provide an optional field in CRD(maybe under `KubeVirtConfiguration`)
https://github.com/kubevirt/kubevirt/blob/main/staging/src/kubevirt.io/api/core/v1/types.go#L1817

**Is your feature request related to a problem? Please describe**:
A clear and concise description of what the problem is.

**Describe the solution you'd like**:

**Describe alternatives you've considered**:

**Additional context**:

**Comment by panpan0000** [comment]
can assign to myself 
/assign @panpan0000

**Comment by matthewei** [comment]
mark
