### ISSUE TITLE
May I graceful shutdown my VM without timeout

### ISSUE THREAD

**Issue by ivandans** [kubevirt/kubevirt#10807]
**Is your feature request related to a problem? Please describe**:
Currently, kubevirt stop api support graceful shutdown my vm. 
Sometimes, I wish kubevirt didn't force the virtual machine to shut down when I shut it down, except when the request parameter gracePeriod is configured to 0. In some scenarios, VMS are stuck in the shutdown process rather than forcibly shut down to avoid disk exceptions.

**Describe the solution you'd like**:
May I graceful shutdown my VM without timeout.

**Comment by xpivarc** [comment]
The `stop` command/API should stop the VM gracefully. Did you observe anything else?

**Comment by matthewei** [comment]
I think you should set `terminationGracePeriodSeconds`

**Comment by matthewei** [comment]
could you have any other question for it?
