### ISSUE TITLE
internal registry not updated when pods are changed

### ISSUE THREAD

**Issue by yuvalif** [kubevirt/kubevirt#1081]
I added a new pod definition under "cmd" together with a binary and a Docker file, and added it to the lists in "hack/config-defaults.sh".
after calling "make cluster-up" for the first time the internal registry is updated with the image, but, in order for consequent updates to the binary to be uploaded into the internal registry, i have to manually delete the image from the outside. calling "docker image remove ..." from the host, and then "make cluster-sync" again.

**Comment by fabiand** [comment]
@yuvalif how often is this situation encountered and how can this be fixed?

**Comment by rmohr** [comment]
@yuvalif I never managed to reproduce it. Did you see this again? Can we close it?

**Comment by yuvalif** [comment]
@rmohr didn't try that for a long while (didn't need to add new pods). OK to close.

**Comment by rmohr** [comment]
> @rmohr didn't try that for a long while (didn't need to add new pods). OK to close.

/close
