### ISSUE TITLE
After sometime that environment with KubeVirt runs virt-controller enter to CrashLoopBackOff

### ISSUE THREAD

**Issue by cynepco3hahue** [kubevirt/kubevirt#1082]
I encountered it few times with openshift cri-o environment:
- `export KUBEVIRT_PROVIDER=os-3.9.0-crio`
- `export KUBEVIRT_NUM_NODES=2`
- `make cluster-up; make cluster-sync`
- leave environment for 1-2 days

```bash
./cluster/kubectl.sh get pods -n kube-system
NAME                               READY     STATUS             RESTARTS   AGE
iscsi-demo-target-tgtd-psbqk       1/1       Running            0          3d
iscsi-demo-target-tgtd-rz45g       1/1       Running            0          3d
virt-api-775dfb9789-tqzvm          1/1       Running            0          3d
virt-controller-5f7c946cc4-8zqpn   0/1       CrashLoopBackOff   55         3d
virt-controller-5f7c946cc4-hlmlt   0/1       CrashLoopBackOff   33         3d
virt-handler-t9c5g                 1/1       Running            0          3d
virt-handler-tcsdv                 1/1       Running            0          3d

./cluster/kubectl.sh -n kube-system logs virt-controller-5f7c946cc4-8zqpn
2018/05/27 08:44:44 invalid configuration: no configuration has been provided
```

**Comment by fabiand** [comment]
@cynepco3hahue do you have an idea where the error message comes from?

**Comment by cynepco3hahue** [comment]
@fabiand I checked the code, and I can see that it is coming from `kubevirt/vendor/k8s.io/client-go/tools/clientcmd/validation.go`, but I did not find any clues why it can be happen :worried:

**Comment by cynepco3hahue** [comment]
I will try to reproduce it with higher verbose under logs, maybe it will reveal something. Also, I want to check if it happens for other providers and not only for OS with CRI-O.

**Comment by fabiand** [comment]
@nellyc is there somebody else who can reproduce this?

**Comment by cynepco3hahue** [comment]
@fabiand Increasing verbose of `virt-controller` did not add much, I think I will wait until we will have 3.10 with CRI-O and will recheck the issue.

**Comment by cynepco3hahue** [comment]
@nellyc If you can run just deploy KubeVirt on OS-3.10 CRI-O environment, leave it for some time, I think 8 hours will be enough and check it after, it will help us :smile:

**Comment by nellyc** [comment]
@fabiand 
Checked multiple environments which have been up for ~3d
Didnt see this issue in any of them

**Comment by fabiand** [comment]
Thanks
