### ISSUE TITLE
Support vm to change password by using QGA

### ISSUE THREAD

**Issue by matthewei** [kubevirt/kubevirt#10827]
**Is your feature request related to a problem? Please describe**:
Sometimes we went to change vm's password and we have to loging the vm to change it. we havn't support a way to change it. As QGA  can change paasword without logging the vm.

**Describe the solution you'd like**:
I want to add a API to change the vm's password

**Describe alternatives you've considered**:
add a api interface to realize it such ad reboot/pause/unpause 

**Additional context**:

**Comment by matthewei** [comment]
WDYT?

**Comment by alicefr** [comment]
@matthewei this is for sure useful. However, it is important to understand where the passwords will be stored and how they are passed to KubeVirt in order to configure the VM. They are sensitive information hence we need to be extra careful.
Otherwise, the mechanism could follow the same approach we use for injecting the ssh keys

**Comment by ashutosh7i** [comment]
Can i work on this issue?

**Comment by alicefr** [comment]
> @alicefr I want to add one API to realize it. just as i described. so we can privide an interfance for admin to change the vm's password. What do you think? Many thinks.

Since the guest agent supports this option, I think it makes sense. However, the security isn't only where we store the password but also the stdin where the password is prompted. The password could be leaked somewhere in KubeVirt code for example. The SSH key injection isn't so problematic because it is only the public key

**Comment by matthewei** [comment]
yes, I know what your concern. As openstack has the same function. we can use encrypt the password. what do others guys think?

**Comment by matthewei** [comment]
> yes, I know what your concern. As openstack has the same function. we can use encrypt the password. what do others guys think?

yes, I know what your concern. As openstack has the same function. we can use encrypt the password. what do others guys think?

**Comment by matthewei** [comment]
> > @alicefr I want to add one API to realize it. just as i described. so we can privide an interfance for admin to change the vm's password. What do you think? Many thinks.
> 
> Since the guest agent supports this option, I think it makes sense. However, the security isn't only where we store the password but also the stdin where the password is prompted. The password could be leaked somewhere in KubeVirt code for example. The SSH key injection isn't so problematic because it is only the public key由于客户机代理支持此选项，我认为这是有道理的。但是，安全性不仅在于我们存储密码的位置，还在于提示密码的 stdin。例如，密码可能会在 KubeVirt 代码中的某个位置泄露。SSH 密钥注入没有那么大的问题，因为它只是公钥

yes, I know what your concern. As openstack has the same function. we can use encrypt the password. what do others guys think?

**Comment by matthewei** [comment]
Hi @ashutosh7i , how about you?

**Comment by matthewei** [comment]
@ashutosh7i  I have finish it. How about you?

**Comment by ashutosh7i** [comment]
yes @matthewei i am mostly done but am occupied, i guess  you should work further.

**Comment by matthewei** [comment]
@EdDev  could you give us some comments for  this feature?

**Comment by mukeshkuiry** [comment]
@matthewei Very much agree with the need for this feature, can I get to know, how you guys are implementing this?

**Comment by matthewei** [comment]
I add a POST virt-api such as `
/apis/subresources.kubevirt.io/v1/namespaces/{namespace}/virtualmachineinstances/{name}/setpassword` to realize it. @ashutosh7i Could you finish this PR?

**Comment by matthewei** [comment]
Can I go on develping it?

**Comment by a516664625** [comment]
Is there any new progress on this feature?
