### ISSUE TITLE
CDI is being tested with high memory limits in kubevirt CI environment

### ISSUE THREAD

**Issue by akalenyu** [kubevirt/kubevirt#10822]
**What happened**:
Following https://github.com/kubevirt/kubevirt/pull/10815 we will have kubevirt ci
setting a very high memory limit for CDI pods. We should instead tackle the real issue and drop this W/A.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by brianmcarey** [comment]
Thanks @akalenyu !

**Comment by akalenyu** [comment]
/reopen
https://gitlab.com/redhat/centos-stream/src/kernel/centos-stream-9/-/merge_requests/4523
waiting for fix

**Comment by akalenyu** [comment]
Fixed in 5.14.0-472.el9, should make it's way to kubevirtci
