### ISSUE TITLE
kubevirt v1.1 Cannot use hostdisk

### ISSUE THREAD

**Issue by QinQiang666** [kubevirt/kubevirt#10843]
**What happened**:
During the process of creating VMI again, use hostdisk and prompt to enable hostdisk
![image](https://github.com/kubevirt/kubevirt/assets/29726716/ee6df131-288a-42eb-9880-c48ac4356487)

Searching for information indicates that the configmap needs to be modified to enable hostdisk, but the kubevirt 1.1 version does not have the kubevirt config configmap
![image](https://github.com/kubevirt/kubevirt/assets/29726716/f145c259-b2ed-4ab9-aa5e-e0ee77a75a33)

**Comment by vasiliy-ul** [comment]
Please refer to the user guide: https://kubevirt.io/user-guide/operations/activating_feature_gates/
You can activate the feature gate by doing:
```
$ kubectl edit kubevirt kubevirt -n kubevirt
    ...
    spec:
      configuration:
        developerConfiguration:
          featureGates:
            - HostDisk
```

**Comment by QinQiang666** [comment]
> Please refer to the user guide: https://kubevirt.io/user-guide/operations/activating_feature_gates/ You can activate the feature gate by doing:
> 
> ```
> $ kubectl edit kubevirt kubevirt -n kubevirt
>     ...
>     spec:
>       configuration:
>         developerConfiguration:
>           featureGates:
>             - HostDisk
> ```

Thank you for your answer
