### ISSUE TITLE
Add virtctl logic for mac viewers

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1084]
On mac we need to try a few viewers, because the stock `screen sharing` app does not support a "fluent connection", as it always requires the user to input credentials.

The script from PR #1076 can be used for reference

**Comment by shiywang** [comment]
I can take a look of this one

**Comment by fabiand** [comment]
That would be awesome!

Feel assigned, @shiywang and let me know if we can give a hand (#kubevirt on freenode and #virtualization on k8s.slack.com)

**Comment by slintes** [comment]
fixed by https://github.com/kubevirt/kubevirt/pull/1216
