### ISSUE TITLE
Compatibility of KubeVirt with Kubernetes Cluster on VMs as Nodes. VM pod pending because of Insufficient devices.kubevirt.io/kvm

### ISSUE THREAD

**Issue by umarfarooq-git** [kubevirt/kubevirt#10851]
**What happened**:
I tried to launch a virtual machine on a k8s cluster itself set up by VMs as nodes. The Virtual Machine object is stuck in scheduling, similar to Bug #4748. Is nested virtualization possible with KubeVirt?

**What you expected to happen**:
The pod for the VM should be scheduled and then started, but it went on Pending. Below is the pod description.

Limits:
  devices.kubevirt.io/kvm:        1
  devices.kubevirt.io/tun:        1
  devices.kubevirt.io/vhost-net:  1 
  memory:                         2292Mi
Requests:
  cpu:                            100m
  devices.kubevirt.io/kvm:        1
  devices.kubevirt.io/tun:        1 
  devices.kubevirt.io/vhost-net:  1 
  ephemeral-storage:              50M 
  memory:                         1268Mi
Limits: 
  cpu:     10m
  memory:  40M 
Requests:
  cpu:                1m
  ephemeral-storage:  50M 
  memory:             1M
Warning: FailedScheduling 20s default-scheduler 0/2 nodes are available: 1 Insufficient memory, 2 Insufficient devices.kubevirt.io/kvm. Preemption: 0/2 nodes are available: 2 No preemption victims found for incoming pod.

**vagrant details**
I have a two-node k8s cluster setup using kubeadm. I provisioned VMs using Vagrant. Below are the details.
NUM_MASTER_NODE = 1
NUM_WORKER_NODE = 1  

IP_NW = "192.168.56."
MASTER_IP_START = 1
NODE_IP_START = 2

Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"
  config.vm.box_check_update = false

  (1..NUM_MASTER_NODE).each do |i|
    config.vm.define "kubemaster" do |node|
      node.vm.provider "virtualbox" do |vb|
        vb.name = "kubemaster"
        vb.memory = 2048
        vb.cpus = 2
        vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
      end
      node.vm.hostname = "kubemaster"
      node.vm.network :private_network, ip: IP_NW + "#{MASTER_IP_START + i}"
      node.vm.network "forwarded_port", guest: 22, host: "#{2710 + i}"
      node.vm.network "private_network", ip: "192.168.56.10", virtualbox__hostonly: true
      node.vm.provision "setup-hosts", :type => "shell", :path => "ubuntu/vagrant/setup-hosts.sh" do |s|
        s.args = ["enp0s8"]
      end
      node.vm.provision "setup-dns", type: "shell", :path => "ubuntu/update-dns.sh"
    end
  end
  (1..NUM_WORKER_NODE).each do |i|
    config.vm.define "kubenode0#{i}" do |node|
      node.vm.provider "virtualbox" do |vb|
        vb.name = "kubenode0#{i}"
        vb.memory = 4096
        vb.cpus = 6
        vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]
      end
      node.vm.hostname = "kubenode0#{i}"
      node.vm.network :private_network, ip: IP_NW + "#{NODE_IP_START + i}"
      node.vm.network "forwarded_port", guest: 22, host: "#{2720 + i}"
      node.vm.network "private_network", ip: "192.168.56.20", virtualbox__hostonly: true
      node.vm.provision "setup-hosts", :type => "shell", :path => "ubuntu/vagrant/setup-hosts.sh" do |s|
        s.args = ["enp0s8"]
      end
      node.vm.provision "setup-dns", type: "shell", :path => "ubuntu/update-dns.sh"
    end
  end
end 

**KubeVirt pods:**
kubectl get pods -n kubevirt
NAME                               READY   STATUS    RESTARTS   AGE 
virt-api-688cc569d4-946sb          1/1     Running   0          2m33s
virt-api-688cc569d4-gh2js          1/1     Running   0          2m33s
virt-controller-58f78787f5-7pmqh   1/1     Running   0          95s
virt-controller-58f78787f5-ntfz8   1/1     Running   0          95s
virt-handler-hgqf6                 1/1     Running   0          95s 
virt-operator-69985b747d-2lhl6     1/1     Running   0          3m57s
virt-operator-69985b747d-jlsxk     1/1     Running   0          3m57s

**How to reproduce it (as minimally and precisely as possible):**

1. Provision VMs using Vagrant.

2. Setup k8s using kubeadm and add flannel as CNI.

4. Install KubeVirt from https://kubevirt.io/user-guide/operations/installation/.

6. Install virtctl as below:
VERSION=$(kubectl get kubevirt.kubevirt.io/kubevirt -n kubevirt -o=jsonpath="{.status.observedKubeVirtVersion}")
if [ "$(uname -s)" == "Windows" ]; then
    ARCH=windows-amd64.exe
else
    ARCH=$(uname -s | tr A-Z a-z)-$(uname -m | sed 's/x86_64/amd64/')
fi
echo ${ARCH}
curl -L -o virtctl https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/virtctl-${VERSION}-${ARCH}
chmod +x virtctl
sudo install virtctl /usr/local/bin

7. Create a virtual machine.
8. Start a virtual machine using the virtctl utility.

**Anything else we need to know?:**
I have enabled nested virtualization in vagrant file specifically while creating VMs using:
vb.customize ["modifyvm", :id, "--nested-hw-virt", "on"]

There are no errors or related logs for control plane static pods.

**Environment:**
kubeadm version: v1.28.4

kubectl version: v1.28.4 

KubeVirt Version: v1.1.0

virtctl version: v1.1.0

**YAML for VM:**
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: fedora-vmi
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: fedora-vmi
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 1Gi
          limits:
            memory: 2Gi
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: kubevirt/fedora-cloud-container-disk-demo:latest
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: fedora
              chpasswd: { expire: False }

**Comment by alicefr** [comment]
Please, refer to our guide: https://kubevirt.io/user-guide/debug_virt_stack/privileged-node-debugging/#validating-the-host-for-virtualization

**Comment by umarfarooq-git** [comment]
virt-host-validate gave me the clue to my problem, which I was facing. From there, I came to know that hardware virtualization is not available on my nodes, and the solution to this problem is available in the installation guide.

Run the following command:
kubectl edit -n kubevirt kubevirt kubevirt

add the following config in the spec section:
spec:
  ...
  configuration:
    developerConfiguration:
      useEmulation: true

This additional configuration resolved my issue, and VM pod is successfully scheduled on the desired worker node.
