### ISSUE TITLE
Update Prometheus Endpoints tests to work on both ipv4 and ipv6 enabled clusters

### ISSUE THREAD

**Issue by kbidarkar** [kubevirt/kubevirt#10864]
For the below tests, they should be adjusted to be able to work on both ipv4 and ipv6.

From, tests/infrastructure/prometheus.go

1. test_id:4136 : Prometheus Endpoints [test_id:4136][flaky] should find one leading virt-controller and two ready
2. test_id:6243 : Prometheus Endpoints should include VMI eviction blocker status for all running VMs [test_id:6243] by IPv6
3. test_id:6241 : Prometheus Endpoints should include VMI infos for a running VM [test_id:6241] by IPv6
4. test_id:6242 : Prometheus Endpoints should include VMI phase metrics for all running VMs [test_id:6242] by IPv6
5. test_id:6244 : Prometheus Endpoints should include kubernetes labels to VMI metrics [test_id:6244] by IPv6
6. test_id:6236 : Prometheus Endpoints should include metrics for a running VM [test_id:6236] network metrics by IPv6
7. test_id:6237 : Prometheus Endpoints should include metrics for a running VM [test_id:6237] memory metrics by IPv6
8. test_id:6238 : Prometheus Endpoints should include metrics for a running VM [test_id:6238] vcpu wait by IPv6
9. test_id:6239 : Prometheus Endpoints should include metrics for a running VM [test_id:6239] vcpu seconds by IPv6
10. test_id:6240 : Prometheus Endpoints should include metrics for a running VM [test_id:6240] vmi unused memory by IPv6
11. test_id:6245 : Prometheus Endpoints should include swap metrics [test_id:6245] by IPv6
12. test_id:6227 : Prometheus Endpoints should include the metrics for a running VM [test_id:6227] by using IPv6
13. test_id:6228 : Prometheus Endpoints should include the storage metrics for a running VM [test_id:6228] storage flush requests metric by using IPv6
14. test_id:6229 : Prometheus Endpoints should include the storage metrics for a running VM [test_id:6229] time (ms) spent on cache flushing metric by using IPv6
15. test_id:6230 : Prometheus Endpoints should include the storage metrics for a running VM [test_id:6230] I/O read operations metric by using IPv6
16. test_id:6231 : Prometheus Endpoints should include the storage metrics for a running VM [test_id:6231] I/O write operations metric by using IPv6
17. test_id:6232 : Prometheus Endpoints should include the storage metrics for a running VM [test_id:6232] storage read operation time metric by using IPv6
18. test_id:6233 : Prometheus Endpoints should include the storage metrics for a running VM [test_id:6233] storage read traffic in bytes metric by using IPv6
19. test_id:6234 : Prometheus Endpoints should include the storage metrics for a running VM [test_id:6234] storage write operation time metric by using IPv6
20. test_id:6235 : Prometheus Endpoints should include the storage metrics for a running VM [test_id:6235] storage write traffic in bytes metric by using IPv6
21. test_id:6226 : Prometheus Endpoints should throttle the Prometheus metrics access [test_id:6226] by using IPv6

**Comment by sradco** [comment]
@kbidarkar is the a kubevirt issue or a Prometheus deployment issue? Is the issue only impacts kubevirt metrics?
