### ISSUE TITLE
Add common labels and annotations to infra and workload parts

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1087]
In this PR https://github.com/kubernetes/website/pull/8703 SIG App is defining a common set of labels to add some sematics to Kubernetes objects in order to allow "tooling" to discover relationships between them and understand what an application is composed of.

KubeVirt should follow this pattern.

Benefits:
- Users who know the pattern will nuderstand KubeVirt better
- UIs which use the pattern will be able to work with KubeVirt
- We gather experience which we can provide as feedback to sig app

**Comment by SchSeba** [comment]
Developer Info:

For this issue we need to work and a couple of different files.
1. Add version to the build-manifests script
    - Add ``` source hack/version.sh ``` to the ``` build-manifests.sh ``` file inside hack folder
    - Run the kubevirt::version::get_version_vars function and add the KUBEVIRT_GIT_VERSION variable to the manifest-templator in line 43 and 50 with a new parameter ```--git-version```

2. Add labels to our manifest
   - Add the follow labels to the yaml's in the manifests folder under dev and release
```
app.kubernetes.io/name: kubevirt
app.kubernetes.io/version: {{.version}}
app.kubernetes.io/managed-by: kubectl
```

3. Add logic to the manifest-templator
   - Add a new flag named ```git-version```
   - Add the new flag to the template struct
   - Split the git-version variable and take everything before the ```+```

4. Add manage-by to the pkg/api/types const section
```
KubernetesManageBy string = "app.kubernetes.io/managed-by"
```
5. Add manage-by label to the pod
   - Add ```pod.label[KubernetesManageBy]: "kubevirt"``` in file pkg/virt-controller/template under line 307

6. Add manage-by and version to vm object
   - Put the manage and version labels inside the pkg/virt-controller/vm inside the updateStatus function
   - ```manage-by: kubevirt```
   - ```version: <user the version package>.GitVersion```

7. Repeat section 6 for vmi replicaset and preset files.

**Comment by SchSeba** [comment]
Hi @tripledes!! :) 

Thanks for helping us make kubevirt amazing.

>  On 2, not sure if all objects should have the labels, for instance, cluster role bindings, services...and on deployments, should the deployment itself have them or should I just add them under `template` ?

I think just add to all the kinds inside our templates.

>  On 6,7, been looking at `updateStatus` and have doubts on how to add `managed-by` and `version`, would it be something like `vm.KubernetesManagedBy = "kubectl"` ?

Just config a const string like this ```const KubernetesManageBy string = "app.kubernetes.io/managed-by" ```

Then just like the pod.label you can add it with vmi.label we are using the same meta data like kubernetes so you should have a label list in the object.

Please replay on the issue if you have any problem or any other question

Thanks again!

**Comment by tripledes** [comment]
@SchSeba Thanks for the tips! I just did a new push to my fork https://github.com/tripledes/kubevirt/commit/bd5455b35c4c96402f6a84f5171372f9009b7255.

Currently it seems to compile (testing as I write), will have a look to the result. If you happen to get some time to review the commit, please do let me know if you see anything wrong.

Regarding unit tests, I haven't had a look yet but I assume I'll have to modify or add some so we make sure the labels are there right?

**Comment by tripledes** [comment]
Hey, I've updated the code, https://github.com/tripledes/kubevirt/commit/94ee3c11b9cc1ecf028c72778dd20a7fbbf88e81

Currently doing the split in `updateStatus()`, but I don't feel like it's the right place as it's an static value so we probably shouldn't be executing split every time `updateStatus()` is called.

So far I've used https://raw.githubusercontent.com/kubevirt/demo/master/manifests/vm.yaml to test and the labels are added:

```shell
➜ kubevirt issue_1087 ✓ cluster/kubectl.sh get vm -o yaml | grep -A 3 labels:           
    labels:
      app.kubernetes.io/managed-by: kubectl
      app.kubernetes.io/version: v0.7.0-25
    name: testvm

➜ kubevirt issue_1087 ✓ cluster/kubectl.sh get vmi -o yaml | grep -A 3 labels           
    labels:
      app.kubernetes.io/managed-by: kubectl
      app.kubernetes.io/version: v0.7.0-25
      guest: testvm
```

**Comment by SchSeba** [comment]
Hey @tripledes good job!

I agree with you the split don't need to be there.

My recommendation is to make the split in the version.sh level.

We want to print the version command just like kubernetes 

Kubernetes version output
```
version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T08:13:03Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```

KubeVirt version output
```
version.Info{GitVersion:"v0.7.0-42+130b88a1abbe6c-dirty", GitCommit:"130b88a1abbe6ceab3f506ddf65fc557310927dc", GitTreeState:"dirty", BuildDate:"2018-07-15T08:49:21Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
``` 

So I think it will be good to remove everything after the `-` character.

@fabiand sounds good?

**Comment by tripledes** [comment]
@SchSeba @fabiand I was checking out how they do it on Kubernetes and found out that the output from last comment is likely from a K8s release, building it from master I get:

```shell
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.0-alpha.0.2410+6764a795869d26", GitCommit:"6764a795869d2631eb75f222f776ec5a80b61e37", GitTreeState:"clean", BuildDate:"2018-07-24T08:03:35Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

I couldn't find anywhere in k8s code where they use the version for labels, so I guess that's why they don't bother.

If we still want to use version as a label and keep `GitVersion` as it is today (for consistency with k8s), a possible solution could be to have another variable, like `KUBEVIRT_RELEASE_VERSION` which would be `KUBEVIRT_GIT_VERSION` but just the `vX.Y.Z` part of it, then add a field to the `version.Info`, like `Release` and use it for `app.kubernetes.io/version`.

How does that sound?

**Comment by fabiand** [comment]
/close

Closing this for now. Will probably be revisited by the operator peeps.

/cc @rthallisey some annotations that the operator might want to add (see the initial link in the description)
