### ISSUE TITLE
Published manifestlist for KubeVirt conformance image is incorrect

### ISSUE THREAD

**Issue by fgiloux** [kubevirt/kubevirt#10881]
**What happened**:
Wanted to run KubeVirt conformance tests. Got
```bash
kubectl logs -n sonobuoy sonobuoy-kubevirt-conformance-job-a34bf7095f8a4ff5 
Defaulted container "plugin" out of: plugin, sonobuoy-worker
exec /usr/bin/conformance: exec format error
``` 
switching from `quay.io/kubevirt/conformance:v1.1.0` to `quay.io/kubevirt/conformance:v1.1.0-amd64` fixed the issue.

**What you expected to happen**:
The right architecture is provided by the manifestlist

**How to reproduce it (as minimally and precisely as possible)**:
See above

**Additional context**:
Looking at the [manifestlist](https://quay.io/repository/kubevirt/conformance/manifest/sha256:7d2017d26df5c7cd71736faf8f03e399b86b22bd4da477e3984adb96c8fb8660) the two targets seem to be for amd64, which is actually not true, the first one [e8e7d99b8e45](https://quay.io/repository///manifest/sha256:e8e7d99b8e45fb9a17981d534d98b894be3bba8e8d4d88791c5e137062fd6a35) is for ARM

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by dhiller** [comment]
Seems to be fixed for at least 1.3.0 and 1.3.1:

![image](https://github.com/user-attachments/assets/6d52ec58-6146-48f7-8901-22c3b467d9d9)
