### ISSUE TITLE
Our Validator does not validate quantities and therefore does not reject wrong ones

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#1089]
If I create a VM with an unsupported unit, e.g. `KiB` instead of `KB` we still accept it and virt-controller is screwed:

```
E0529 07:28:42.472271       1 reflector.go:205] kubevirt.io/kubevirt/pkg/controller/virtinformers.go:105: Failed to list *v1.OfflineVirtualMachine: v1.OfflineVirtualMachineList: Items: []v1.OfflineVirtualMachine: v1.OfflineVirtualMachine: Spec: v1.OfflineVirtualMachineSpec: Template: v1.VMTemplateSpec: Spec: v1.VirtualMachineSpec: TerminationGracePeriodSeconds: Domain: v1.DomainSpec: Resources: v1.ResourceRequirements: Requests: unmarshalerDecoder: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$', parsing 610 ...097152KiB"... at {"apiVersion":"kubevirt.io/v1alpha1","items":[{"apiVersion":"kubevirt.io/v1alpha1","kind":"OfflineVirtualMachine","metadata":{"clusterName":"","creationTimestamp":"2018-05-28T19:32:20Z","generation":0,"name":"test-
```

**Comment by rmohr** [comment]
@vatsalparekh FYI, thx for reporting.

**Comment by cynepco3hahue** [comment]
@rmohr Does this problem actual only for OVM's?
Because when I tried to create regular VM with 
```
    resources:
      requests:
        memory: 64KiB
```
and create the VM I have correct error
```
./cluster/kubectl.sh create -f cluster/examples/vm-ephemeral.yaml 
Error from server: error when creating "cluster/examples/vm-ephemeral.yaml": admission webhook "virtualmachine-validator.kubevirt.io" denied the request: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
```

**Comment by cynepco3hahue** [comment]
I checked OVM creation as well
```
./cluster/kubectl.sh create -f cluster/examples/ovm-cirros.yaml 
Error from server: error when creating "cluster/examples/ovm-cirros.yaml": admission webhook "offlinevirtualmachine-validator.kubevirt.io" denied the request: quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
```

**Comment by rmohr** [comment]
@vatsalparekh can it be that your cluser has the validation webhooks disabled? This page https://www.kubevirt.io/user-guide/#/installation/api-validation?id=kubevirt-api-validation contains information on how to enable them.

**Comment by vatsalparekh** [comment]
@rmohr I patched that OVM, changing it from `KiB` to just `Ki`, it changed the VM object to `Gi` (which is fine I guess) and it worked

**Comment by vatsalparekh** [comment]
@rmohr yes! that doesn't seem to part of our current `openshift-ansible`

**Comment by rmohr** [comment]
Opend https://github.com/kubevirt/kubevirt-ansible/issues/247 to ensure that clusters bootstrapped with kubevirt-ansible will get the right admission plugins enabled. We should probably also come up with something to probe if our required features are enabled and working on the cluster.

**Comment by cynepco3hahue** [comment]
@rmohr I think such check must be part of https://github.com/kubevirt/kubevirt/issues/1023

**Comment by rmohr** [comment]
Great. Thema we can close this one.
