### ISSUE TITLE
/apis/subresources.kubevirt.io/v1 exposes a non-standard apiVersion v1alpha3 APIResourceList

### ISSUE THREAD

**Issue by KarstenB** [kubevirt/kubevirt#10899]
**What happened**:
As I was developing an operator with kube-rs the discovery is crashing because it expects `apiVersion: v1` for the `ApiResourceList`. I could not find any documentation that a historic `v1alpha3` of `ApiResourceList` ever existed and think that this is non standard conforming.

```
❯ curl $KUBE_API/apis/subresources.kubevirt.io/v1 \
        -k  \
        --header "Authorization: Bearer $JWT_TOKEN_DEFAULT_DEFAULT"
{
 "kind": "APIResourceList",
 "apiVersion": "v1alpha3",
 "groupVersion": "subresources.kubevirt.io/v1alpha3",
 "resources": [
  {
...
```

**What you expected to happen**:
The returned ApiResourceList should have v1:
```
{
 "kind": "APIResourceList",
 "apiVersion": "v1",
 "groupVersion": "subresources.kubevirt.io/v1alpha3",
 "resources": [
  {
```

**How to reproduce it (as minimally and precisely as possible)**:
* Install and instantiate KubeVirt Operator (1.1.0)
* 
```
export JWT_TOKEN_DEFAULT_DEFAULT=$(kubectl create token default)
curl $KUBE_API/apis/subresources.kubevirt.io/v1 -k --header "Authorization: Bearer $JWT_TOKEN_DEFAULT_DEFAULT" | jq '.apiVersion'
```
Observe the jq output: v1alpha3

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): ❯ virtctl version
Client Version: version.Info{GitVersion:"v1.1.0", GitCommit:"e8e638edc22587ec7be2cc3d983b61763e33f973", GitTreeState:"clean", BuildDate:"2023-11-06T16:34:32Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"darwin/arm64"}
- Kubernetes version (use `kubectl version`): Client Version: v1.27.3
Kustomize Version: v5.0.1
Server Version: v1.28.4+k3s2
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Debian GNU/Linux 12 (bookworm)
- Kernel (e.g. `uname -a`): Linux ryzen 6.1.0-13-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.55-1 (2023-09-29) x86_64 GNU/Linux
- Install tools: N/A
- Others: N/A

**Comment by KarstenB** [comment]
I think the error might be here https://github.com/kubevirt/kubevirt/blame/e53b1249f073ffab068037973a914303082925c9/pkg/virt-api/api.go#L584C5-L584C37

**Comment by KarstenB** [comment]
Yep, it was there. I did build and test it on my local machine.

**Comment by clux** [comment]
That looks like a good change upstream to me. Thanks for digging into this.

<details><summary>discord info</summary>
<p>
The <a href="https://discord.gg/tokio">tokio discord</a> thread is mostly just someone drive-by noticing the dynamic_watcher example did not work with kubevirt for during discovery and giving a serialization error:

```
  }, Error("invalid value: string \"v1alpha3\", expected v1", line: 3, column: 25)
  Error: Error deserializing response

  Caused by:
      invalid value: string "v1alpha3", expected v1 at line 3 column 25
```
and doing some cross-referencing with `kubectl -v9` without it being too fruitful.
</p>
</details>

**Comment by clux** [comment]
This change makes sense to me (from kube-rs POV). The openapi schemas for `APIResourceList` only supports a v1 here:

```json
      "x-kubernetes-group-version-kind": [
        {
          "group": "",
          "kind": "APIResourceList",
          "version": "v1"
        }
      ]
```

and it's what a discovery query ala `kubectl get --raw /apis` should return.
