### ISSUE TITLE
uninstallation requires additional steps

### ISSUE THREAD

**Issue by ErikEngerd** [kubevirt/kubevirt#10907]
**What happened**:
I installed kubevirt using the instructions
```

wget https://github.com/kubevirt/kubevirt/releases/download/${KUBEVIRT_VERSION}/kubevirt-operator.yaml
kubectl apply -f kubevirt-operator.yaml 

wget https://github.com/kubevirt/kubevirt/releases/download/${KUBEVIRT_VERSION}/kubevirt-cr.yaml
kubectl apply -f kubevirt-cr.yaml 
```

Then I uninstalled it using `kubectl delete -f` of the above yaml files. 

**What you expected to happen**:
kubevirt should be uninstalled. 

**How to reproduce it (as minimally and precisely as possible)**:

Install kubevirt followed by uninstall. 

**Additional context**:

To uninstall, I had to perform the following additional steps: 

```
kubectl delete apiservices.apiregistration.k8s.io v1.subresources.kubevirt.io
kubectl delete apiservices.apiregistration.k8s.io v1alpha3.subresources.kubevirt.io
kubectl delete mutatingwebhookconfigurations.admissionregistration.k8s.io virt-api-mutator
kubectl delete validatingwebhookconfigurations.admissionregistration.k8s.io virt-api-validator
kubectl delete validatingwebhookconfigurations.admissionregistration.k8s.io virt-operator-validator

kubectl edit kubevirt kubevirt # replace finalizer by [] 

```
**Environment**:
- KubeVirt version: v1.1.0
- Kubernetes version: 1.26.11
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration:  Azure AKS
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by vasiliy-ul** [comment]
When you uninstall KubeVirt, you need to do that in reverse order. I.e. first you do `k delete -f kubevirt-cr.yaml` and only after that `k delete -f kubevirt-operator.yaml`. Otherwise, you end up with some of the components being stuck.

This is explicitly mentioned in the user guilde: https://kubevirt.io/user-guide/operations/updating_and_deletion/#deleting-kubevirt
