### ISSUE TITLE
Support cdrom with url

### ISSUE THREAD

**Issue by wavezhang** [kubevirt/kubevirt#10911]
**Is your feature request related to a problem? Please describe**:
Yes, currently in KubeVirt, there is no direct way to specify an ISO image for a VM's CD-ROM using a URL. This limitation hinders the flexibility and automation potential in setting up virtual environments, especially in scenarios where ISO images are frequently updated or stored remotely.

**Describe the solution you'd like**:
I would like KubeVirt to support specifying ISO images for a VM's CD-ROM through URLs. This feature would allow users to directly link to ISO images hosted on remote servers, enabling easier updates and management of the images, and streamlining the deployment process for VMs.

**Describe alternatives you've considered**:
An alternative considered is using DataVolumes to import ISO images. However, this method faces a significant limitation in that it doesn't support the use of the same ISO image across different namespaces, which restricts its usability in multi-namespace environments. This limitation necessitates separate imports of the same ISO image for each namespace, leading to inefficiencies and redundancy.

**Additional context**:

**Comment by alicefr** [comment]
@wavezhang there has been in the past some attempts to introduce something similar. Could you please check [this proposal](https://github.com/kubevirt/community/pull/117) and verify it covers your use-case.
