### ISSUE TITLE
optimize: usbredir

### ISSUE THREAD

**Issue by chenxinlong** [kubevirt/kubevirt#10931]
**Is your feature request related to a problem? Please describe**:
Currently, the implementation of `virtctl usbredir` may like the pic below(correct me if I'm wrong) : 

![image](https://github.com/kubevirt/kubevirt/assets/9261954/a17e3d95-fb5f-4387-8b48-5e7fc0cc5c5e)

Problems it may happen : 

1.  Let say I deploy all kubevirt components in master node,  all data goes through master node, it makes some pressure on master node.
2. When I make a redirection from mass storage usb device to vm,  the performance may deteriorate.

**Describe the solution you'd like**:
Detect if the execution of `virtctl usbredir` and the vm is on the same node, if so, make the connection directly from virtctl to vm other than to virt-api.

**Comment by victortoso** [comment]
Yes, there are lots of possible improvements around remote USB.
- In KubeVirt, as you mention
- In usbredirect and/or QEMU like [this issue](https://gitlab.freedesktop.org/spice/usbredir/-/issues/28)

This tool can be quite powerful but need more people/eyes on it.
If you do write a PR, feel free to tag me.
