### ISSUE TITLE
make cluster-clean or make clean do not remove old builder container and volumes 

### ISSUE THREAD

**Issue by avlitman** [kubevirt/kubevirt#10938]
**What happened**:
I upgraded my cluster and now it fails to sync with:
Regenerating sandbox
FATAL: corrupt installation: file '/root/.cache/bazel/_bazel_root/install/7e78030801a38f836b1891b02e25eaaa/A-server.jar' is missing or modified. Please remove '/root/.cache/bazel/_bazel_root/install/7e78030801a38f836b1891b02e25eaaa' and try again.
make[1]: *** [Makefile:158: cluster-build] Error 1

**What you expected to happen**:
one of this make command will remove old builder container and volumes:
make cluster-down
make cluster-clean
make clean

**How to reproduce it (as minimally and precisely as possible)**:
My steps:
sudo chmod 666 /var/run/docker.sock
docker login
fetch latest kubevirt repo
make cluster-down
make cluster-clean
make clean
source mysetup
export KUBEVIRT_PROVIDER=k8s-1.28  (was 1.25)
export KUBEVIRT_NUM_NODES=3
export KUBEVIRT_DEPLOY_PROMETHEUS=true
export KUBEVIRT_DEPLOY_GRAFANA=true
export KUBEVIRT_STORAGE="rook-ceph-default"
export KUBECONFIG="${PWD}"/_ci-configs/$KUBEVIRT_PROVIDER/.kubeconfig
alias k=kubectl
make cluster-up
make cluster-sync

**Additional context**:

- I needed to manually do this steps to sync the cluster and fix the bug.

docker stop {container-name} && docker rm {container-name}
sudo docker volume prune

-  I remembered that it's the second time it happen for me. I think it's a bug since it's a simple workaround (maybe a simple script can fix it) and I think we should handle it somehow on our end: it's a big error (can't install the cluster) and a simple fix so it looks bad.

* I consulted @brianmcarey before opening this issue.

**Environment**:
- KubeVirt version (use `virtctl version`): latest and before even
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by oshoval** [comment]
Hi
aint `docker rm --force kubevirt-bazel-server` is enough? (one time had it, and this solved it at least for myself)

personally i dont think we should add cleaning of those, it might happen and then the minimal cleaning should be done

**Comment by avlitman** [comment]
I didn’t try but we can discuss the solution later.
But it look and feel like a bug to me. It’s making the cluster-sync fail
one of the most important make commands and an initial step to install the
cluster. If a user see such fail in such early stage it looks very bad in
my opinion and if it was me I would not be a customer… I strongly think
it’s a bug. One of the clean make commands should do it or at least it
should be documented in the main README of the kubevirt project.

Aviv Litman

BI Software Engineer

Red Hat <https://www.redhat.com/>

***@***.***
<https://www.redhat.com/>

**Comment by oshoval** [comment]
I do understand the concerns
as we spoke offline
seems a bazel bug, and removing the server and restarting it solves it
can be seen here
https://github.com/bazelbuild/bazel/issues/14355

if we can find a way to detect such corruption using some sanity check using bazel, then we can delete the server
we can even do something easier, if it happens, detect it, and print a hint to the user, wdyt?

note that per design iiuc, the make clean doesnt delete the server (on the other hand it does `bazel clean --expunge`, so not sure if we cant just delete the server in this case) - this can be the easiest and clean solution
