### ISSUE TITLE
Can't create VM on arm64 (PIOS/K3S) -- PROGRESS .. can create but can't connect

### ISSUE THREAD

**Issue by swheettaos** [kubevirt/kubevirt#10939]
PROGRESS MADE >> Still having problem .. read next comment .. 

Ok.. been trying to get a VM spun up on a K3s cluster running on CM4 cluster.  Went through a bunch of iterations (including without CDI and just trying VMI instead of VM) .. this is what I got so far and the farthest I've been able to get with it.  (I'm using nightly arm64 builds for both the KubeVirt and CDI).. I know this isn't supported but I'd I'm so close.  I feel like I'm missing something..  FYI I'm just using local storage for everything.
Here goes:

What I did (and I tried just about everything .. this is the way I got the furthest)

VM just stuck in (starting now)

    octopi@octopi2:~/repos/turing_ansible$ kubectl get vm
    NAME       AGE     STATUS     READY
    ubuntuvm   7m13s   Starting   False
    octopi@octopi2:~/repos/turing_ansible$

-- Install KubeVirt 
    From arm64 nightly .. tried with just latest normal KubeVirt.. while it installed didn't get this far

    *** Operator

    LATEST=$(curl -L https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/latest-arm64)

    kubectl apply -f [https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/${LATEST}/kubevirt-operator-arm64.yaml](https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/$%7BLATEST%7D/kubevirt-operator-arm64.yaml)

    *** CR for KubeVirt

    kubectl apply -f [https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/${LATEST}/kubevirt-cr-arm64.yaml](https://storage.googleapis.com/kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/$%7BLATEST%7D/kubevirt-cr-arm64.yaml)

--Check if the install succeeded with

    kubectl get kubevirt.kubevirt.io/kubevirt -n kubevirt -o=jsonpath="{.status.phase}"
    kubectl get all -n kubevirt

-- Install virtctl to control KubeVirt VMs. I used the Kubernetes plugin manager Krew.

    Run this command to download and install krew:

    (
    set -x; cd "$(mktemp -d)" &&
    OS="$(uname | tr '[:upper:]' '[:lower:]')" &&
    ARCH="$(uname -m | sed -e 's/x86_64/amd64/' -e 's/\(arm\)\(64\)\?.*/\1\2/' -e 's/aarch64$/arm64/')" &&
    KREW="krew-${OS}_${ARCH}" &&
    curl -fsSLO "[https://github.com/kubernetes-sigs/krew/releases/latest/download/${KREW}.tar.gz](https://github.com/kubernetes-sigs/krew/releases/latest/download/$%7BKREW%7D.tar.gz)" &&
    tar zxvf "${KREW}.tar.gz" &&
    ./"${KREW}" install krew
    )
    Add the $HOME/.krew/bin directory to your PATH environment variable. To do this, update your .bashrc or .zshrc file and append the following line:

    export PATH="${KREW_ROOT:-$HOME/.krew}/bin:$PATH"
    and restart your shell.

    Run kubectl krew to check the installation.

-- Install Containerized-Data-Importer (CDI) to manage your VM disk later on. I used the operator version.

    ******* NOTE THIS WAS TRICKY .. in beta had to get from nightly builds *******

    Goto https://quay.io/repository/kubevirt/cdi-operator?tab=tags&tag=latest where they do night builds and get lastest tag with arm (latest doesn't work)
    it will look like "20231225_f2ad73eba-arm64"

    Then do the following:

    export VERSION=$(curl -s https://api.github.com/repos/kubevirt/containerized-data-importer/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
    export ARM_VERSION=(version you got from quay.io)
    # example: export ARM_VERSION=20231225_f2ad73eba-arm64

    curl -sL https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-operator.yaml | sed "s/$VERSION/$ARM_VERSION/g" | kubectl apply -f -
    kubectl apply -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-cr.yaml

    check status of deployments 

    kubectl get all -n cdi

    ***** NOTE: when you run this you should see something like this:

    service/cdi-uploadproxy          ClusterIP   10.43.233.125   <none>        443/TCP    39m

    *****

--- Now I create a VM .. 
    Get the image you want .. (is should be an image Qcow2 image .. look at docs about other images)
    look here for ubuntu https://cloud-images.ubuntu.com/jammy/current/

*** going to create VM in default namespace -- don't think this is a problem

    kubectl config set-context --current --namespace=default

    kubectl apply -f kubevirt_datavolume.yml

    kubectl logs --follow importer-ubuntu-data-volume (this finishes without errors)

**** Sample
            I1226 22:15:22.862382       1 importer.go:103] Starting importer
            I1226 22:15:22.862486       1 importer.go:176] begin import process
            I1226 22:15:23.822112       1 data-processor.go:356] Calculating available size
            I1226 22:15:23.822201       1 data-processor.go:368] Checking out file system volume size.
            I1226 22:15:23.822240       1 data-processor.go:376] Request image size not empty.
            I1226 22:15:23.822270       1 data-processor.go:381] Target size 3Gi.
            I1226 22:15:23.935695       1 data-processor.go:255] New phase: TransferScratch
            I1226 22:15:23.936702       1 util.go:194] Writing data...
            I1226 22:16:15.393573       1 data-processor.go:255] New phase: Convert
            I1226 22:16:15.393743       1 data-processor.go:261] Validating image
            E1226 22:16:15.549142       1 prlimit.go:155] failed to kill the process; os: process already finished
            I1226 22:16:15.549644       1 qemu.go:126] Running qemu-img with args: [convert -t writeback -p -O raw /scratch/tmpimage /data/disk.img]
            I1226 22:16:15.564906       1 qemu.go:258] 0.00
            I1226 22:16:15.871234       1 qemu.go:258] 1.00
            I1226 22:16:16.176994       1 qemu.go:258] 2.01
            I1226 22:16:16.656785       1 qemu.go:258] 3.01
            I1226 22:16:17.134922       1 qemu.go:258] 4.01
            I1226 22:16:18.043537       1 qemu.go:258] 5.02
            I1226 22:16:18.463168       1 qemu.go:258] 6.02
            I1226 22:16:18.858874       1 qemu.go:258] 7.03
            I1226 22:16:19.759505       1 qemu.go:258] 8.03
            I1226 22:16:20.244383       1 qemu.go:258] 9.03
            I1226 22:16:21.234464       1 qemu.go:258] 10.04
            I1226 22:16:21.656080       1 qemu.go:258] 11.04
            I1226 22:16:22.610983       1 qemu.go:258] 12.04
*****

    kubectl apply -f kubevirt_vm.yml
    kubectl get vm

***** sample

          octopi@octopi2:~/repos/turing_ansible$ kubectl get vm
          NAME       AGE     STATUS     READY
          ubuntuvm   5m22s   Starting   False
          octopi@octopi2:~/repos/turing_ansible$ kubectl get vm
          NAME       AGE     STATUS     READY
          ubuntuvm   5m26s   Starting   False
          octopi@octopi2:~/repos/turing_ansible$ kubectl get vm
          NAME       AGE     STATUS     READY
          ubuntuvm   7m13s   Starting   False
          octopi@octopi2:~/repos/turing_ansible$ kubectl get vm
          NAME       AGE   STATUS     READY
          ubuntuvm   16m   Starting   False
          octopi@octopi2:~/repos/turing_ansible$ 

*****

the importer just fails like before

***** logs
          {"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:581","timestamp":"2023-12-26T22:17:26.899385Z"}
          {"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:563","timestamp":"2023-12-26T22:17:26.932923Z"}
          {"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:75","timestamp":"2023-12-26T22:17:26.934204Z"}
          panic: timed out waiting for domain to be defined
          {"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 12 with status 512","pos":"virt-launcher-monitor.go:198","timestamp":"2023-12-26T22:22:55.947890Z"}
          {"component":"virt-launcher-monitor","level":"error","msg":"dirty virt-launcher shutdown: exit-code 2","pos":"virt-launcher-monitor.go:216","timestamp":"2023-12-26T22:22:55.953528Z"}
*****

kubevirt_vm.yml

      apiVersion: kubevirt.io/v1
      kind: VirtualMachine
      metadata:
        name: ubuntuvm
      spec:
        running: true
        template:
          metadata:
            labels:
              kubevirt.io/size: tiny
              kubevirt.io/domain: ubuntuvm
          spec:
            domain:
              devices:
                disks:
                - disk:
                    bus: virtio
                  name: containerdisk
                - disk:
                    bus: virtio
                  name: cloudinitdisk
                interfaces:
                - name: default
                  bridge: {}
                  model: virtio
              resources:
                requests:
                    memory: 128M
            networks:
            - name: default
              pod: {}
            volumes:
            - name: containerdisk
              dataVolume:
                name: ubuntu-data-volume
            - name: cloudinitdisk
              cloudInitNoCloud:
                userData: |
                  #cloud-config
                  password: passwd
                  chpasswd: { expire: False }
                  ssh_pwauth: False

kubevirt_datavolume.yml

      apiVersion: cdi.kubevirt.io/v1beta1
      kind: DataVolume
      metadata:
        name: "ubuntu-data-volume"
      spec:
        source:
          http:
            url: "https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-arm64.img"    
        pvc:
          accessModes:
          - ReadWriteOnce
          resources:
            requests:
              storage: 3Gi

kubectl get pod -n kubevirt

      NAME                               READY   STATUS    RESTARTS      AGE
      virt-operator-7559747c5-ns2wk      1/1     Running   0             50m
      virt-operator-7559747c5-mjs5l      1/1     Running   0             50m
      virt-handler-k7q26                 1/1     Running   0             46m
      virt-handler-p8jqx                 1/1     Running   0             46m
      virt-handler-w4szv                 1/1     Running   0             46m
      virt-handler-c8c57                 1/1     Running   0             46m
      virt-controller-5d86785f66-5fqtl   1/1     Running   1 (29m ago)   46m
      virt-controller-5d86785f66-nh9q4   1/1     Running   1 (29m ago)   46m
      virt-api-59cbcd94df-tq6ck          1/1     Running   1 (29m ago)   47m
      virt-api-59cbcd94df-dg7bb          1/1     Running   1 (29m ago)   47m

kubectl get all -n kubevirt

      Warning: kubevirt.io/v1 VirtualMachineInstancePresets is now deprecated and will be removed in v2.
      NAME                                   READY   STATUS    RESTARTS      AGE
      pod/virt-operator-7559747c5-ns2wk      1/1     Running   0             51m
      pod/virt-operator-7559747c5-mjs5l      1/1     Running   0             51m
      pod/virt-handler-k7q26                 1/1     Running   0             47m
      pod/virt-handler-p8jqx                 1/1     Running   0             47m
      pod/virt-handler-w4szv                 1/1     Running   0             47m
      pod/virt-handler-c8c57                 1/1     Running   0             47m
      pod/virt-controller-5d86785f66-5fqtl   1/1     Running   1 (30m ago)   47m
      pod/virt-controller-5d86785f66-nh9q4   1/1     Running   1 (30m ago)   47m
      pod/virt-api-59cbcd94df-tq6ck          1/1     Running   1 (30m ago)   47m
      pod/virt-api-59cbcd94df-dg7bb          1/1     Running   1 (30m ago)   47m
      
      NAME                                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
      service/kubevirt-prometheus-metrics   ClusterIP   None            <none>        443/TCP   47m
      service/virt-api                      ClusterIP   10.43.30.106    <none>        443/TCP   47m
      service/kubevirt-operator-webhook     ClusterIP   10.43.37.218    <none>        443/TCP   47m
      service/virt-exportproxy              ClusterIP   10.43.246.144   <none>        443/TCP   47m
      
      NAME                          DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
      daemonset.apps/virt-handler   4         4         4       4            4           kubernetes.io/os=linux   47m
      
      NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
      deployment.apps/virt-operator     2/2     2            2           51m
      deployment.apps/virt-controller   2/2     2            2           47m
      deployment.apps/virt-api          2/2     2            2           47m
      
      NAME                                         DESIRED   CURRENT   READY   AGE
      replicaset.apps/virt-operator-7559747c5      2         2         2       51m
      replicaset.apps/virt-controller-5d86785f66   2         2         2       47m
      replicaset.apps/virt-api-59cbcd94df          2         2         2       47m
      
      NAME                            AGE   PHASE
      kubevirt.kubevirt.io/kubevirt   48m   Deployed

kubectl get all -n cdi

      Warning: kubevirt.io/v1 VirtualMachineInstancePresets is now deprecated and will be removed in v2.
      NAME                                  READY   STATUS    RESTARTS      AGE
      pod/cdi-operator-bcdb694bb-9pf2v      1/1     Running   0             31m
      pod/cdi-apiserver-6fd98b59d5-cz7pg    1/1     Running   2 (30m ago)   30m
      pod/cdi-uploadproxy-b96c94669-kmlkh   1/1     Running   0             30m
      pod/cdi-deployment-f75b45b84-lq4lw    1/1     Running   0             30m
      
      NAME                             TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)    AGE
      service/cdi-api                  ClusterIP   10.43.105.95    <none>        443/TCP    30m
      service/cdi-prometheus-metrics   ClusterIP   10.43.199.20    <none>        8080/TCP   30m
      service/cdi-uploadproxy          ClusterIP   10.43.160.140   <none>        443/TCP    30m
      
      NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
      deployment.apps/cdi-operator      1/1     1            1           31m
      deployment.apps/cdi-apiserver     1/1     1            1           30m
      deployment.apps/cdi-uploadproxy   1/1     1            1           30m
      deployment.apps/cdi-deployment    1/1     1            1           30m
      
      NAME                                        DESIRED   CURRENT   READY   AGE
      replicaset.apps/cdi-operator-bcdb694bb      1         1         1       31m
      replicaset.apps/cdi-apiserver-6fd98b59d5    1         1         1       30m
      replicaset.apps/cdi-uploadproxy-b96c94669   1         1         1       30m
      replicaset.apps/cdi-deployment-f75b45b84    1         1         1       30m

**Environment**:
- KubeVirt version (use `virtctl version`): Client Version: version.Info{GitVersion:"v1.1.0", GitCommit:"e8e638edc22587ec7be2cc3d983b61763e33f973", GitTreeState:"clean", BuildDate:"2023-11-06T16:34:32Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{GitVersion:"v1.1.0-rc.0.413+2c5e56f2cd0fcd", GitCommit:"2c5e56f2cd0fcde341f47a7da0b94bc812c2f43f", GitTreeState:"clean", BuildDate:"2023-12-26T01:09:14Z", GoVersion:"go1.20.12 X:nocoverageredesign", Compiler:"gc", Platform:"linux/arm64"}

- Kubernetes version (use `kubectl version`): Client Version: v1.29.0
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.28.4+k3s2
- VM or VMI specifications: ubuntu jammy arm64 (latest)
- Cloud provider or hardware configuration: home (turing pi 2 CM4 Cluster running K3s Latest)
- OS (e.g. from /etc/os-release): PI OS 64bit latest (bookworm)
- Kernel (e.g. `uname -a`): Linux turingnode1 6.1.0-rpi7-rpi-v8 #1 SMP PREEMPT Debian 1:6.1.63-1+rpt1 (2023-11-24) aarch64 GNU/Linux
- Install tools: KUBECTL, VIRTCTL plugin
- Others: N/A

**Comment by swheettaos** [comment]
OK .. being a NOOB .. I didn't realize that KubeVirt needed IPV6 .. I disabled it in the /boot/cmdline.txt on all my nodes.. I reenabled .. and rebooted.. then I was able to get past that part .. it was provisioned and started.. all looked good in logs (as far as I could tell) .. 

my problem now is that it says the VM is running.. but I can't connect to it via serial console or VNC using virtctl ..
for serial it connects .. but I get nothing back.. for VNC.. it just says "guest has not initialized the display (yet) ..

I was first trying it with kubectl virt plugin but then I read you needed full virtctl to do serial and vnc .. so I I grabbed it for my linux and Mac .. both systems.. same result. 

I'm so close I can taste it..

I also tried doing this with a VMI instead of a VM .. no difference.

Any help?  I didn't see anything really in the logs (thats where I found the error that it could do the IPV6 stuff and was erroring out)

**Comment by swheettaos** [comment]
Ok.. update, so I tried like 25 different configurations on my vm/vmi config.  Tried a ton of different images including the cirros image on quay (quay.io/kubevirt/cirros-container-disk-demo:v1.1.1-arm64) .. thinking that the image is the problem .. in most configs I get the vm showing that it's running and status of ready .. but I can't connect via console (it connects but nothing comes back) .. vnc (get a message that the VM hasn't initalized it's display) and ssh to a load balancer service that forwards port from public ip (metallb forwarding port 22 to a public IP from metal IP pool range) .. I'm completely stumped at this point.  don't know what else to try.  I don't see any errors in the virthandler (only a warning about KSM which I don't have installed) I don't see any other errors in any thing else unless I'm not looking in the right place.   ANY HELP WOULD BE APPREICIEATED ..   I saw someone doing a demo of from 2 years ago (I understand it wasn't with CDI) but I thought I could get it working in some form .. I've tried so many ways to do this and it's just not working.  


FYI: I haven't setup any certs on my K3s cluster but I'm not doing anything with traefik yet .. so it shouldn't need them.

**Comment by swheettaos** [comment]
I'm hoping people have just been off for the holidays and maybe get someone that can throw me a bone.. I'm just so close and I don't know why it's not working.

**Comment by xpivarc** [comment]
Hey. Does a VM without datavolume work for you?

**Comment by swheettaos** [comment]
> Hey. Does a VM without datavolume work for you?

Nope.. I first tired it with that because initailly I didn't see how to do it with CDI (then found the nightly builds after digging) .. so basically I tried it with and without dataVolume both VM and VMI and I can get them all to point where they are "running" and "ready" but when I try to connect via console/ssh/vnc .. nothing works

**Comment by vasiliy-ul** [comment]
For the record: there is a similar issue https://github.com/kubevirt/kubevirt/issues/10635#issuecomment-1882814498. Apparently, VMs on **aarch64** need more memory to run. E.g. for cirros at least `256Mi` is required (while on x86_64 `128Mi` is enough).

**Comment by stephenwheet** [comment]
ok.. so I have since rebuilt my cluster in my lab .. I decided to give this another try. I have upgraded my nodes in my cluster with larger ones (before it they were 2gb nodes, now I have 8gb nodes so I bumped the memory up on the VM.  I installed kubevirt (no CDI at this point).  I first tried from the nightly builds but the vm wouldn't start.. giving me errors .. I removed and tried from just the latest v.1.1.1 and got the same thing.  VMI won't even start.. I'm seeing the following: 

```
{"component":"virt-launcher","level":"error","msg":"unsupported configuration: CPU mode 'host-passthrough' for aarch64 qemu domain on aarch64 host is not supported by hypervisor","pos":"qemuProcessUpdateGuestCPU:6286","subcomponent":"libvirt","thread":"25","timestamp":"2024-01-14T18:22:12.517000Z"}

{"component":"virt-launcher","level":"error","msg":"Unable to open file: /var/run/kubevirt-private/libvirt/qemu/log/default_vmi-fedora.log: No such file or directory","pos":"virNetClientProgramDispatchError:172","subcomponent":"libvirt","thread":"25","timestamp":"2024-01-14T18:22:12.519000Z"}

{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to start VirtualMachineInstance with flags 0.","name":"vmi-fedora","namespace":"default","pos":"manager.go:1101","reason":"virError(Code=67, Domain=10, Message='unsupported configuration: CPU mode 'host-passthrough' for aarch64 qemu domain on aarch64 host is not supported by hypervisor')","timestamp":"2024-01-14T18:22:12.522472Z","uid":"e9b9bcb2-0bb8-4946-b48a-562201bd1093"}

{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"vmi-fedora","namespace":"default","pos":"server.go:202","reason":"virError(Code=67, Domain=10, Message='unsupported configuration: CPU mode 'host-passthrough' for aarch64 qemu domain on aarch64 host is not supported by hypervisor')","timestamp":"2024-01-14T18:22:12.522673Z","uid":"e9b9bcb2-0bb8-4946-b48a-562201bd1093"}

{"component":"virt-launcher","level":"info","msg":"Hardware emulation device '/dev/kvm' not present. Using software emulation.","pos":"converter.go:1353","timestamp":"2024-01-14T18:22:12.745207Z"}

{"component":"virt-launcher","level":"info","msg":"generated nocloud iso file /var/run/kubevirt-ephemeral-disks/cloud-init-data/default/vmi-fedora/noCloud.iso","pos":"cloud-init.go:690","timestamp":"2024-01-14T18:22:12.866483Z"}
```

in the virt-launcher

I have emulation mode enabled

```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1
  creationTimestamp: "2024-01-14T18:16:04Z"
  finalizers:
  - foregroundDeleteKubeVirt
  generation: 3
  name: kubevirt
  namespace: kubevirt
  resourceVersion: "1185944"
  uid: 17fadf3e-ecc5-440d-b72e-a7d2f7450f0a
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      useEmulation: true
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
status:
  conditions:
  - lastProbeTime: "2024-01-14T18:19:28Z"
```

Here is the VMI I'm trying to create:

```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-fedora
  name: vmi-fedora
spec:
  networks:
  - name: default
    pod: {}
  domain:
    devices:
      interfaces:
        - name: default
          bridge: {}
          model: virtio
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      rng: {}
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M 
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: quay.io/kubevirt/fedora-cloud-container-disk-demo:20210811_9fec1f849-arm64
    name: containerdisk
  - cloudInitNoCloud:
      userData: |
        #cloud-config
        hostname: fedora
        password: fedora
        chpasswd: { expire: False }
        disable_root: false
    name: cloudinitdisk

```

**Comment by vasiliy-ul** [comment]
I am not sure about emulation mode, tbh. Have you tried with kvm?

Maybe @zhlhahaha can help with 

> unsupported configuration: CPU mode 'host-passthrough' for aarch64 qemu domain on aarch64 host is not supported by hypervisor

**Comment by vasiliy-ul** [comment]
UPD: apparently emulation mode is not supported on aarch64 ATM https://github.com/kubevirt/kubevirt/issues/3558
