### ISSUE TITLE
Can ReadWriteOnce be supported for backend storage?

### ISSUE THREAD

**Issue by bnabholz** [kubevirt/kubevirt#10940]
**Is your feature request related to a problem? Please describe**:
https://github.com/kubevirt/kubevirt/pull/8156 by @jean-edouard introduced backend storage to support persistent TPM, which is awesome!  But it requires a ReadWriteMany storage class in [backend-storage.go](https://github.com/kubevirt/kubevirt/blob/main/pkg/storage/backend-storage/backend-storage.go#L105), I'm assuming(?) to support live migration.  Regular VM disks can be RWO, and I think there are use cases where it's acceptable for the backend storage to be RWO.

**Describe the solution you'd like**:
I'd like for backend storage to try RWX if available, but fall back to RWO if not available.  It's up to the storage class defined as `vmStateStorageClass` in the config, but it won't be readily apparent which volume access mode is supported until its demanded.

**Describe alternatives you've considered**:
I don't have any RWX storage available, so my alternative is to compile kubevirt on my own with ReadWriteMany changed to ReadWriteOnce.  That would be fine even behind a configuration flag.

Disregarding my custom compilation, and given the nature of the data being stored (TPM, NVRAM), and even if live migration is the goal, I'm not sure about the premise of having multiple writers to such a store.  It might be best for access to be RWO and if a migration happens, to detach and reattach the backend storage to the new node.  I understand this would be a lot of additional work to support.

**Additional context**:
My use case (small / single clusters without any live migration) may not represent the common use case.  But even to support VM migration, I can see a case where the VM storage is detached, then backend storage is detached, and then both are re-attached on the node that is resuming VM execution.

**Comment by helloabhii** [comment]
hello @bnabholz, I want to work on this. Am a newcomer and want to know more about this. Does I have to change the 'ReadWriteMany' to 'ReadWriteOnce' only ?

**Comment by akalenyu** [comment]
Unfortunately, I believe this is a hard requirement at the moment for this feature:
https://github.com/kubevirt/user-guide/blob/84f8b6407888df75c7610e82d676c9f10c5c22ad/docs/virtual_machines/persistent_tpm_and_uefi_state.md?plain=1#L12

https://github.com/kubevirt/community/pull/170/files#diff-02388d082a9acd98303b1858857a485ebd993e2518de159ebce66e342d7b2400R33

/cc @jean-edouard

**Comment by alicefr** [comment]
@bnabholz if you don't require live migration, this could be possible. Possibly, if libvirt can copy the TPM state to a new location, then we could drop the RWX requirement. I'm not sure if this is already possible today to migrate the local state of the TPM.

About multiple writers, QEMU is able to handle the concurrent writes as it is the case for live migrate the VM without TPMs.

**Comment by jean-edouard** [comment]
Please note that the backend storage code does not find a storage class itself, it has to be manually added to the CR.
I don't think anything will stop you from specifying a RWO SC, you should just try it!

**Comment by akalenyu** [comment]
> Please note that the backend storage code does not find a storage class itself, it has to be manually added to the CR. I don't think anything will stop you from specifying a RWO SC, you should just try it!

So the PVC is being created with ReadWriteMany (hardcoded), which means the storage class will be unable to satisfy the request (`Pending` PVC)

**Comment by jean-edouard** [comment]
> > Please note that the backend storage code does not find a storage class itself, it has to be manually added to the CR. I don't think anything will stop you from specifying a RWO SC, you should just try it!
> 
> So the PVC is being created with ReadWriteMany (hardcoded), which means the storage class will be unable to satisfy the request (`Pending` PVC)

Ah, got it, my bad then!
So yes, it should be possible to adjust the code to accept RWO and make the VM un-migratable, but it is not something I plan on working on in the near future.

**Comment by bnabholz** [comment]
Thanks everyone for taking the time to respond.  My original idea of trying RWX first and falling back to RWO would be complicated to implement, since the PVC doesn't immediately fail but is stuck in Pending state.  So I think the access mode needs to be specified by the user.

I propose to add another field to KubeVirtConfiguration called VMStateAccessMode, that defaults to ReadWriteMany if not specified.  I'm reluctant to clutter up configuration any further, but this would be backwards-compatible with the current behavior.  Perhaps these should be relocated to the VM spec at some point?  That would be a breaking API change right now which I want to avoid.

If this sounds like an acceptable design, I am happy to open a PR that implements this.  I have some of the work done, but I need to make sure the functional tests cover this appropriately.

**Comment by jean-edouard** [comment]
> Thanks everyone for taking the time to respond. My original idea of trying RWX first and falling back to RWO would be complicated to implement, since the PVC doesn't immediately fail but is stuck in Pending state. So I think the access mode needs to be specified by the user.
> 
> I propose to add another field to KubeVirtConfiguration called VMStateAccessMode, that defaults to ReadWriteMany if not specified. I'm reluctant to clutter up configuration any further, but this would be backwards-compatible with the current behavior. Perhaps these should be relocated to the VM spec at some point? That would be a breaking API change right now which I want to avoid.
> 
> If this sounds like an acceptable design, I am happy to open a PR that implements this. I have some of the work done, but I need to make sure the functional tests cover this appropriately.

The CR approach sounds good to me!

**Comment by alicefr** [comment]
> Thanks everyone for taking the time to respond. My original idea of trying RWX first and falling back to RWO would be complicated to implement, since the PVC doesn't immediately fail but is stuck in Pending state. So I think the access mode needs to be specified by the user.
> 
> I propose to add another field to KubeVirtConfiguration called VMStateAccessMode, that defaults to ReadWriteMany if not specified. I'm reluctant to clutter up configuration any further, but this would be backwards-compatible with the current behavior. Perhaps these should be relocated to the VM spec at some point? That would be a breaking API change right now which I want to avoid.
> 
> If this sounds like an acceptable design, I am happy to open a PR that implements this. I have some of the work done, but I need to make sure the functional tests cover this appropriately.

@jean-edouard does the user know which storage class will be used by the backend storage? If not, I think this approach isn't properly working

**Comment by jean-edouard** [comment]
> > Thanks everyone for taking the time to respond. My original idea of trying RWX first and falling back to RWO would be complicated to implement, since the PVC doesn't immediately fail but is stuck in Pending state. So I think the access mode needs to be specified by the user.
> > I propose to add another field to KubeVirtConfiguration called VMStateAccessMode, that defaults to ReadWriteMany if not specified. I'm reluctant to clutter up configuration any further, but this would be backwards-compatible with the current behavior. Perhaps these should be relocated to the VM spec at some point? That would be a breaking API change right now which I want to avoid.
> > If this sounds like an acceptable design, I am happy to open a PR that implements this. I have some of the work done, but I need to make sure the functional tests cover this appropriately.
> 
> @jean-edouard does the user know which storage class will be used by the backend storage? If not, I think this approach isn't properly working

Well yeah since it's manually set in the CR... I might be misunderstanding the question though

**Comment by alicefr** [comment]
> > > Thanks everyone for taking the time to respond. My original idea of trying RWX first and falling back to RWO would be complicated to implement, since the PVC doesn't immediately fail but is stuck in Pending state. So I think the access mode needs to be specified by the user.
> > > I propose to add another field to KubeVirtConfiguration called VMStateAccessMode, that defaults to ReadWriteMany if not specified. I'm reluctant to clutter up configuration any further, but this would be backwards-compatible with the current behavior. Perhaps these should be relocated to the VM spec at some point? That would be a breaking API change right now which I want to avoid.
> > > If this sounds like an acceptable design, I am happy to open a PR that implements this. I have some of the work done, but I need to make sure the functional tests cover this appropriately.
> > 
> > 
> > @jean-edouard does the user know which storage class will be used by the backend storage? If not, I think this approach isn't properly working
> 
> Well yeah since it's manually set in the CR... I might be misunderstanding the question though

If it is set in KubeVirt CR, then regular users don't know what is the storage class for the backend.

**Comment by jean-edouard** [comment]
> > > > Thanks everyone for taking the time to respond. My original idea of trying RWX first and falling back to RWO would be complicated to implement, since the PVC doesn't immediately fail but is stuck in Pending state. So I think the access mode needs to be specified by the user.
> > > > I propose to add another field to KubeVirtConfiguration called VMStateAccessMode, that defaults to ReadWriteMany if not specified. I'm reluctant to clutter up configuration any further, but this would be backwards-compatible with the current behavior. Perhaps these should be relocated to the VM spec at some point? That would be a breaking API change right now which I want to avoid.
> > > > If this sounds like an acceptable design, I am happy to open a PR that implements this. I have some of the work done, but I need to make sure the functional tests cover this appropriately.
> > > 
> > > 
> > > @jean-edouard does the user know which storage class will be used by the backend storage? If not, I think this approach isn't properly working
> > 
> > 
> > Well yeah since it's manually set in the CR... I might be misunderstanding the question though
> 
> If it is set in KubeVirt CR, then regular users don't know what is the storage class for the backend.

Oh, right, they would need read access on the CR. Why is this a concern?

**Comment by alicefr** [comment]
> > > > > Thanks everyone for taking the time to respond. My original idea of trying RWX first and falling back to RWO would be complicated to implement, since the PVC doesn't immediately fail but is stuck in Pending state. So I think the access mode needs to be specified by the user.
> > > > > I propose to add another field to KubeVirtConfiguration called VMStateAccessMode, that defaults to ReadWriteMany if not specified. I'm reluctant to clutter up configuration any further, but this would be backwards-compatible with the current behavior. Perhaps these should be relocated to the VM spec at some point? That would be a breaking API change right now which I want to avoid.
> > > > > If this sounds like an acceptable design, I am happy to open a PR that implements this. I have some of the work done, but I need to make sure the functional tests cover this appropriately.
> > > > 
> > > > 
> > > > @jean-edouard does the user know which storage class will be used by the backend storage? If not, I think this approach isn't properly working
> > > 
> > > 
> > > Well yeah since it's manually set in the CR... I might be misunderstanding the question though
> > 
> > 
> > If it is set in KubeVirt CR, then regular users don't know what is the storage class for the backend.
> 
> Oh, right, they would need read access on the CR. Why is this a concern?

My concerns are that we shouldn't put this information into the VMI spoc as it is defined by regular users. The backend storage can be only configured by the cluster-admins. If this is clear then I'm fine with the approach.

**Comment by jean-edouard** [comment]
> > > > > > Thanks everyone for taking the time to respond. My original idea of trying RWX first and falling back to RWO would be complicated to implement, since the PVC doesn't immediately fail but is stuck in Pending state. So I think the access mode needs to be specified by the user.
> > > > > > I propose to add another field to KubeVirtConfiguration called VMStateAccessMode, that defaults to ReadWriteMany if not specified. I'm reluctant to clutter up configuration any further, but this would be backwards-compatible with the current behavior. Perhaps these should be relocated to the VM spec at some point? That would be a breaking API change right now which I want to avoid.
> > > > > > If this sounds like an acceptable design, I am happy to open a PR that implements this. I have some of the work done, but I need to make sure the functional tests cover this appropriately.
> > > > > 
> > > > > 
> > > > > @jean-edouard does the user know which storage class will be used by the backend storage? If not, I think this approach isn't properly working
> > > > 
> > > > 
> > > > Well yeah since it's manually set in the CR... I might be misunderstanding the question though
> > > 
> > > 
> > > If it is set in KubeVirt CR, then regular users don't know what is the storage class for the backend.
> > 
> > 
> > Oh, right, they would need read access on the CR. Why is this a concern?
> 
> My concerns are that we shouldn't put this information into the VMI spec as it is defined by regular users. The backend storage can be only configured by the cluster-admins. If this is clear then I'm fine with the approach.

Yes, I agree backend storage settings should only be in the CR,  thanks for clarifying!

**Comment by bnabholz** [comment]
I did not forget about this, it just took me longer than expected to figure out the functional tests.  But I learned a lot in the process.

For any future travelers who need to support this scenario immediately, a workaround is for the user to manually create the `persistent-state-for-<vm>` volume in the same namespace as the VM, and it will be used instead of attempting to create a new PV.  Of course I did not realize this before I finished my work to support other access modes :)

**Comment by akalenyu** [comment]
One thing that occurred to me when facing this issue with trident:
https://issues.redhat.com/browse/CNV-36913
Is that we may soon end up needing to expose more PVC API fields in the spec.

If that is the case, we may want to explore the idea of embedding a pvcTemplate in the kubevirt CR
and have that take precedence over the single storageClassName field.

Note, as you can see in the comments, we think trident should have "just worked" by giving a larger volume back,
so I am just posting this issue for the sake of the example.

**Comment by akalenyu** [comment]
@bnabholz this is fixed by https://github.com/kubevirt/kubevirt/pull/11773
