### ISSUE TITLE
Reintroduce linters that were removed during a go version update

### ISSUE THREAD

**Issue by brianmcarey** [kubevirt/kubevirt#11006]
The following linters were disabled as part of a Go version update PR[1]:
- ginkgolinter
- ineffassign
- errcheck

Source: https://github.com/kubevirt/kubevirt/commit/2eb07af5fc29a462a0568463857bafd533ce9572

These linters were removed because when they were included gaselle failed to recreate the Build files which was blocking the go version bump from being merged. The go version bump was needed for some important security fixes. 

This issue became evident in the pull-kubevirt-verify-go-mod presubmit which failed consistently with these linters included.
Example: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11004/pull-kubevirt-verify-go-mod/1745409637596794880

This CI job runs the `make deps-sync` target.
```
deps-sync:
	SYNC_VENDOR=true hack/dockerized " ./hack/dep-update.sh --sync-only && ./hack/dep-prune.sh && ./hack/bazel-generate.sh"
```

`./hack/dep-update.sh` runs a `go mod tidy` & `go mod vendor` which results in the previously generated BUILD.bazel files being removed. 

The following step in `./hack/bazel-generate.sh` fails to recreate the BUILD.bazel files when these linters are included:
https://github.com/kubevirt/kubevirt/blob/32c04d08e8c8c8994a28f8c7998dd1b45553f0f4/hack/bazel-generate.sh#L10C1-L13C78

The linters should be reintroduced once this issue has been resolved. 

[1]https://github.com/kubevirt/kubevirt/pull/10879

**Comment by EdDev** [comment]
The `pull-kubevirt-code-lint` is now gating.
