### ISSUE TITLE
certificate validation disabled

### ISSUE THREAD

**Issue by cwguard** [kubevirt/kubevirt#11027]
https://github.com/kubevirt/kubevirt/blob/b171859a412395ef5c4974a037e45aed13bd0dfc/cluster-up/cluster/k8s-provider-common.sh#L175

Disabling TLS certificate validation exposes the Kubernetes cluster to several security risks, including man-in-the-middle attacks, unverified server identities, and compromised data integrity and confidentiality. This vulnerability is particularly concerning given the sensitive nature of the data and operations managed by the cluster.

```
kubectl config set-cluster kubernetes --insecure-skip-tls-verify=true
```

**Comment by brianmcarey** [comment]
Hi @cwguard , thanks for opening this issue. 

Yes disabling TLS certificate validation does expose kubernetes clusters to security risks however this script is just used in the setup of our ephemeral test clusters that are used for running the end-to-end tests. These clusters are generally short-lived test clusters so this is a very low risk. 

Please let me know if you are ok with closing this issue based on this reason.

**Comment by cwguard** [comment]
this makes sense, for ephemeral test clusters this should be fine.

**Comment by cwguard** [comment]
Just to note, even though it's expected to be used for development purposes, the naming convention of 'cluster-up/cluster/k8s-provider-common.sh' suggests that it could be used for production. Could it be made more explicit to avoid confusion?
