### ISSUE TITLE
macvtap err

### ISSUE THREAD

**Issue by caijian76** [kubevirt/kubevirt#11031]
{"component":"virt-launcher","level":"error","msg":"cannot open macvtap tap device /dev/tap46: Permission denied","pos":"virNetDevMacVLanTapOpen:179","subcomponent":"libvirt","thread":"36","timestamp":"2024-01-17T21:00:46.784000Z"}

deploy macvtap use https://kubevirt.io/user-guide/virtual_machines/net_binding_plugins/macvtap/

**Environment**:
- KubeVirt version (use `virtctl version`): v1.1.1
- Kubernetes version (use `kubectl version`): 1.25.9
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by maiqueb** [comment]
Thanks for your interest in KubeVirt and macvtap.

That's an unsupported version of kubernetes (we only support the latest 3 versions).

Furthermore, you do not provide any meaningful info to address this issue; please provide information regarding:
- which nodes (OS and version) you are using
- which macvtap version you are using
- are you using selinux ? if so, please upload the audit logs.

We would require at least that to have any idea of what is happening.
