### ISSUE TITLE
security_groups Unable to change！！！

### ISSUE THREAD

**Issue by wenjunGU** [kubevirt/kubevirt#11055]
kubevirt version：0.58.0

I created two new security groups and created a new vm，but I found that changing the security group of one vm to another did not take effect. The policy is based on the original security group and takes effect only after the vm is restarted。

Is there a good solution to this problem？？

**Comment by alicefr** [comment]
@wenjunGU I think security group are a AWS concept, am I right. If so, do you know how this translate into k8s features? If this is related to the pod, then probably the part is immutable or there isn't an update mechanism and update takes place when the virt-launcher pod is recreated.

More then a bug, I think this is a feature request.

**Comment by wenjunGU** [comment]
@alicefr It seems that I have solved this problem, the solution is that VM, VMI, and POD must be changed together to ensure transactional consistency. This isn't really a BUG, it should be a feature
