### ISSUE TITLE
virtctl image-upload does not start pod

### ISSUE THREAD

**Issue by aep** [kubevirt/kubevirt#11078]
when using kubevirt with longhorn, binding a blockdisk seems to work just fine.
but i cant upload an iso image

```
virtctl image-upload  pvc win10iso --size 10G  --image-path=/vault/iso/Win10_22H2_English_x64v1.iso
PVC default/win10iso not found 
PersistentVolumeClaim default/win10iso created
Waiting for PVC win10iso upload pod to be ready...
```

however, no pod is ever created.
and i cant figure out how enable additional debug information

- KubeVirt version (use `virtctl version`):  v1.1.1
- Kubernetes version (use `kubectl version`):  v1.28.2 
- Cloud provider or hardware configuration: bare metal

**Comment by aep** [comment]
oof, user error, i misunderstood how this works. the relevant logs are in the cdi pods, since thats what creates the upload pod, not in virtctl itself.

**Comment by ss-armada** [comment]
How was this issue resolved ?

**Comment by manas-suleman** [comment]
@aep @ss-armada I have exactly the same issue and don't see any logs in cdi pods as well. did you folks manage to resolve this issue?

**Comment by ss-armada** [comment]
@manas-suleman I wasn’t able to resolve this but found a work around. Before running the command I create a datavolume yaml with source as upload {}. It creates a data volume and pvc awaiting upload. Then you can use inage-upload command and it works fine.

**Comment by notyep** [comment]
the --force-bind option at the end of the virtctl <command> string resolved the issue for me.
