### ISSUE TITLE
VirtualMachineReplicaSet does not delete finished VMs

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#1107]
VirtualMachineReplicaSet quietly assumes that a restartPolicy on the vm restarts failed vms and does not delete failed vms. We don't have policies on VMs. As a consequence the replicaset creates new vm instances, but it does not delete vms in a final state.

How to reproduce:
 * Create a replicaset with e.g. 2 replicas
 * Delete the pods of the vm (will make the vms go to a final state)
 * You will now see 4 vms (two fresh ones and two in a final state)

Expected:
 * The controller should remove the two vms in final state and not just create new instances

**Comment by fabiand** [comment]
@rmohr can you give an estimate how much work it is to fix it?

**Comment by fabiand** [comment]
@rmohr would #413 help us here?

**Comment by rmohr** [comment]
@fabiand Yes #413 would indeed be one solution to the problem.
