### ISSUE TITLE
Should standardize the configuration method of gpu.

### ISSUE THREAD

**Issue by matthewei** [kubevirt/kubevirt#11084]
**Description**:

The Kubevirt official docs tell us to config the GPU

![image](https://github.com/kubevirt/kubevirt/assets/86186853/38b7574c-7233-4053-9033-cd6f232b3a9e)

The Nvidia-Github docs tell us to config the GPU

![image](https://github.com/kubevirt/kubevirt/assets/86186853/b8e9e9b1-2d48-4ea6-b226-13d3c74beef3)

**What you expected**:
I think we should standardize the configuration method of gpu.

**URL**:
Provide a link to the documentation.
1. The Kubevirt URL
https://kubevirt.io/user-guide/virtual_machines/host-devices/
3. The Nvidia kubevirt URL
https://github.com/NVIDIA/kubevirt-gpu-device-plugin

**Additional context**:
Add any other context about the issue here.

**Comment by cloudymax** [comment]
Driverctl can also be used for this purpose and doesn't require the extra reboot: https://manpages.ubuntu.com/manpages/focal/en/man8/driverctl.8.html

I've found it useful for managing hosts with GPUs that are sometimes passthrough and othertime used with vGPU

**Comment by matthewei** [comment]
@vladikr Good morning! Could you help us to solve issue?
