### ISSUE TITLE
virtctl vmexport download removes vmexport even if it was not able to download

### ISSUE THREAD

**Issue by j-zimnowoda** [kubevirt/kubevirt#11080]
**What happened**:
virtctl vmexport download remove export even if it was not able to download

**What you expected to happen**:
Do not remove vmeexport on command failure.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create VMExport
2. Perform `virtctl vmexport download vm30000-export --port-forward --local-port=5410` 
3. Observe that vmexport is removed and them command failure.
```
virtctl vmexport download vm30000-export --port-forward --local-port=5410
service virt-export-vm30000-export is ready for port-forwarding
Forwarding from 127.0.0.1:5410 -> 8443
Forwarding from [::1]:5410 -> 8443
Port forwarding is ready.
VirtualMachineExport 'default/vm30000-export' deleted succesfully
detected more than one downloadable volume in 'default/vm30000-export' VirtualMachineExport: Select the expected volume using the --volume flag
```
**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by akalenyu** [comment]
So we actually discussed this extensively on the sig-storage call:
https://docs.google.com/document/d/1mqJMjzT1biCpImEvi76DCMZxv-DwxGYLiPRLcR6CWpE/edit#heading=h.fqe36hzerfrn

I believe the summary of it is that we're examining not deleting VMExports that weren't created by the virtctl cmd

/cc @alromeros

**Comment by alromeros** [comment]
Yeah, this is expected behavior but we are reconsidering some changes so at least we only delete vmexports that have been created by the command. I opened a Jira card to track this issue https://issues.redhat.com/browse/CNV-37843. I'll link the PR once it's ready and we can continue the discussion there.

**Comment by j-zimnowoda** [comment]
> So we actually discussed this extensively on the sig-storage call:
> 
> https://docs.google.com/document/d/1mqJMjzT1biCpImEvi76DCMZxv-DwxGYLiPRLcR6CWpE/edit#heading=h.fqe36hzerfrn
> 
> 
> 
> I believe the summary of it is that we're examining not deleting VMExports that weren't created by the virtctl cmd
> 
> 
> 
> /cc @alromeros 

Sounds reasonable. Thanks for insights.
