### ISSUE TITLE
There is an error in "Mediated devices and virtual GPUs"

### ISSUE THREAD

**Issue by matthewei** [kubevirt/kubevirt#11083]
**Description**:
Hi team, I think we should recreate a new paragraph.
![image](https://github.com/kubevirt/kubevirt/assets/86186853/8f01c24a-752a-4b99-aaa6-c8c08dcf576d)

**What you expected**:
A clear and concise description of what you expected.
```shell
* Nodes with 2 Tesla T4 cards * Each card can support multiple types: * nvidia-222 * nvidia-223 * nvidia-228 * ... 
* Nodes with 2 Tesla V100 cards * Each card can support multiple types: * nvidia-105 * ... * nvidia-108 * nvidia-217 * nvidia-299 * ...
```
**URL**:
Provide a link to the documentation.
https://kubevirt.io/user-guide/operations/mediated_devices_configuration/
**Additional context**:
Add any other context about the issue here.

**Comment by aburdenthehand** [comment]
@matthewei Thanks for raising this bug. 
I've posted a fix to the user guide and you can read the re-formatted version at this temporary build link: https://deploy-preview-763--kubevirt-user-guide.netlify.app/operations/mediated_devices_configuration/

The '...' used in the lists are to represent that the listed device types are not complete, and the cards support more types than are listed in these examples.

**Comment by matthewei** [comment]
@aburdenthehand Good Job! Thanks your timely reply!
