### ISSUE TITLE
VMs admitter should fail fast when using non-amd64 architectures + live update

### ISSUE THREAD

**Issue by jean-edouard** [kubevirt/kubevirt#11102]
**Is your feature request related to a problem? Please describe**:
The VMs admitter in virt-api rejects the creation of live-update-enabled VMs on architectures that are not amd64.
However, the validation function checks for that last, spending useless time checking the validity of all the live-updatable fields.

**Describe the solution you'd like**:
`if architecture != "amd64" {...}` should be done first and return right away.

**Comment by matthewei** [comment]
I want to develop it. could you assign it to me?

**Comment by fossedihelm** [comment]
ops :slightly_smiling_face:

**Comment by mukeshkuiry** [comment]
Hey @matthewei can we do it collaboratively? I want to just how to start with this.
