### ISSUE TITLE
go version go1.21.6 windows/amd64 Unable to create virtual machine using API

### ISSUE THREAD

**Issue by moyunnie** [kubevirt/kubevirt#11112]
**What happened**:

**What you expected to happen**:
A clear and concise description of wPS C:\Users\Sierting\GolandProjects\awesomeProject17> go mod tidy 
go: finding module for package kubevirt.io/client-go/kubecli
go: finding module for package github.com/spf13/pflag
go: finding module for package k8s.io/apimachinery/pkg/apis/meta/v1
go: found github.com/spf13/pflag in github.com/spf13/pflag v1.0.5
go: found k8s.io/apimachinery/pkg/apis/meta/v1 in k8s.io/apimachinery v0.29.1
go: found kubevirt.io/client-go/kubecli in kubevirt.io/client-go v1.1.1
go: finding module for package k8s.io/client-go/kubernetes/typed/admissionregistration/v1alpha1
go: finding module for package k8s.io/client-go/kubernetes/typed/events/v1
go: finding module for package k8s.io/client-go/kubernetes/typed/certificates/v1
go: finding module for package k8s.io/client-go/kubernetes/typed/discovery/v1
go: finding module for package k8s.io/client-go/kubernetes/typed/discovery/v1beta1
go: finding module for package k8s.io/client-go/kubernetes/typed/apiserverinternal/v1alpha1
go: finding module for package k8s.io/client-go/kubernetes/typed/autoscaling/v2
go: finding module for package k8s.io/client-go/kubernetes/typed/resource/v1alpha1
go: finding module for package k8s.io/api/batch/v2alpha1
go: finding module for package k8s.io/client-go/kubernetes/typed/node/v1
go: finding module for package k8s.io/client-go/kubernetes/typed/policy/v1
go: finding module for package github.com/googleapis/gnostic/OpenAPIv2
go: finding module for package k8s.io/client-go/kubernetes/typed/authentication/v1alpha1
go: finding module for package k8s.io/api/auditregistration/v1alpha1
go: finding module for package k8s.io/client-go/kubernetes/typed/networking/v1alpha1
go: finding module for package k8s.io/client-go/kubernetes/typed/admissionregistration/v1
go: finding module for package k8s.io/client-go/kubernetes/typed/flowcontrol/v1alpha1
go: finding module for package k8s.io/client-go/kubernetes/typed/flowcontrol/v1beta2
go: finding module for package k8s.io/client-go/kubernetes/typed/flowcontrol/v1beta1
go: finding module for package k8s.io/client-go/kubernetes/typed/flowcontrol/v1beta3
go: finding module for package k8s.io/api/settings/v1alpha1
go: finding module for package k8s.io/apimachinery/pkg/util/clock
go: ceshi imports
        kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/typed/admissionregistration/v1: package k8s.io/client-go/kubernetes/typed/admissionregistration/v1 provided by k8s.io/client-go at latest version v0.29.1 but not at required version v12.0.0+incompatible
go: ceshi imports
        kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/typed/admissionregistration/v1alpha1: package k8s.io/client-go/kubernetes/typed/admissionregistration/v1alpha1 provided by k8s.io/client-go at latest version v0.29.1 but not at required version v12.0.0+incompatible
go: ceshi imports
        kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/typed/apiserverinternal/v1alpha1: package k8s.io/client-go/kubernetes/typed/apiserverinternal/v1alpha1 provided by k8s.io/client-go at latest version v0.29.1 but not at required version v12.0.0+incompatible
go: ceshi imports
        kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/typed/authentication/v1alpha1: package k8s.io/client-go/kubernetes/typed/authentication/v1alpha1 provided by k8s.io/client-go at latest version v0.29.1 but not at required version v12.0.0+incompatible
go: ceshi imports
        kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/typed/autoscaling/v2: package k8s.io/client-go/kubernetes/typed/autoscaling/v2 provided by k8s.io/client-go at latest version v0.29.1 but not at required version v12.0.0+incompatible
go: ceshi imports
        kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/typed/certificates/v1: package k8s.io/client-go/kubernetes/typed/certificates/v1 provided by k8s.io/client-go at latest version v0.29.1 but not at required version v12.0.0+incompatible
go: ceshi imports
        kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/typed/discovery/v1: package k8s.io/client-go/kubernetes/typed/discovery/v1 provided by k8s.io/client-go at latest version v0.29.1 but not at required version v12.0.0+incompatible
go: ceshi imports
        kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/typed/discovery/v1beta1: package k8s.io/client-go/kubernetes/typed/discovery/v1beta1 provided by k8s.io/client-go at latest version v0.29.1 but not at required version v12.0.0+incompatible
go: ceshi imports
        kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/typed/events/v1: package k8s.io/client-go/kubernetes/typed/events/v1 provided by k8s.io/client-go at latest version v0.29.1 but not at required version v12.0.0+incompatible
go: ceshi imports
        kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/typed/flowcontrol/v1alpha1: module k8s.io/client-go@latest found (v0.29.1), but does not contain package k8s.io/client-go/kubernetes/typed/flowcontrol/v1alpha1
go: ceshi imports
        kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/typed/flowcontrol/v1beta1: package k8s.io/client-go/kubernetes/typed/flowcontrol/v1beta1 provided by k8s.io/client-go at latest version v0.29.1 but not at required version v12.0.0+incompatible
go: ceshi imports
        kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/typed/flowcontrol/v1beta2: package k8s.io/client-go/kubernetes/typed/flowcontrol/v1beta2 provided by k8s.io/client-go at latest version v0.29.1 but not at required version v12.0.0+incompatible
go: ceshi imports
        kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/typed/flowcontrol/v1beta3: package k8s.io/client-go/kubernetes/typed/flowcontrol/v1beta3 provided by k8s.io/client-go at latest version v0.29.1 but not at required version v12.0.0+incompatible
go: ceshi imports
        kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/typed/networking/v1alpha1: package k8s.io/client-go/kubernetes/typed/networking/v1alpha1 provided by k8s.io/client-go at latest version v0.29.1 but not at required version v12.0.0+incompatible
go: ceshi imports
        kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/typed/node/v1: package k8s.io/client-go/kubernetes/typed/node/v1 provided by k8s.io/client-go at latest version v0.29.1 but not at required version v12.0.0+incompatible
go: ceshi imports
        kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/typed/policy/v1: package k8s.io/client-go/kubernetes/typed/policy/v1 provided by k8s.io/client-go at latest version v0.29.1 but not at required version v12.0.0+incompatible
go: ceshi imports
        kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/typed/resource/v1alpha1: module k8s.io/client-go@latest found (v0.29.1), but does not contain package k8s.io/client-go/kubernetes/typed/resource/v1alpha1
go: ceshi imports
        kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/discovery imports
        github.com/googleapis/gnostic/OpenAPIv2: module github.com/googleapis/gnostic@latest found (v0.7.0), but does not contain package github.com/googleapis/gnostic/OpenAPIv2
go: ceshi imports
        kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/scheme imports
        k8s.io/api/auditregistration/v1alpha1: module k8s.io/api@latest found (v0.29.1), but does not contain package k8s.io/api/auditregistration/v1alpha1
go: ceshi imports
        kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/scheme imports
        k8s.io/api/batch/v2alpha1: module k8s.io/api@latest found (v0.29.1), but does not contain package k8s.io/api/batch/v2alpha1
go: ceshi imports
        kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/scheme imports
        k8s.io/api/settings/v1alpha1: module k8s.io/api@latest found (v0.29.1), but does not contain package k8s.io/api/settings/v1alpha1
go: ceshi imports
        kubevirt.io/client-go/kubecli imports
        k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset imports
        k8s.io/client-go/util/flowcontrol imports
        k8s.io/apimachinery/pkg/util/clock: module k8s.io/apimachinery@latest found (v0.29.1), but does not contain package k8s.io/apimachinery/pkg/util/clock
hat you expected to happen.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by aburdenthehand** [comment]
Hi @moyunnie - thanks for the bug. Can you please fill in the bug description and your environment details?

**Comment by cepaallium** [comment]
I have the same question like you.

**Comment by sirkrypt0** [comment]
We're facing the same issue (which has also happens to affect some others, as described in this issue https://github.com/kubevirt/client-go/issues/28). To provide a bit more context to this issue:

We develop an application in Go which should manage `VirtualMachines` using Kubevirt in Kubernetes. To do so, we want to use the Kubernetes API. We already do some Kubernetes-related things in our application, so we already have the usual set of dependencies, like `k8s.io/api`, `k8s.io/client-go`, etc.
Now, we wanted to add `kubevirt.io/client-go` as well so that we can use the existing generated clients to interface with the API, especially the functionality provided in `kubevirt.io/client-go/kubecli`.

Consider the following simple application:

```
module kubevirt-test

go 1.21.5

require kubevirt.io/client-go v1.1.1 // indirect
```

```go
package main

import (
	"kubevirt.io/client-go/kubecli"
)

func main() {
	kubecli.GetKubevirtClientFromClientConfig(nil)
}
```

If we now want to get the rest of the dependencies using `go get -v -d ./...`, this fails with a bunch of lines similar to what the OP pasted in the issue:

```
go: kubevirt-test imports
        kubevirt.io/client-go/kubecli imports
        k8s.io/client-go/kubernetes/typed/admissionregistration/v1: cannot find module providing package k8s.io/client-go/kubernetes/typed/admissionregistration/v1
```

And finally a line saying:

```
go: warning: k8s.io/client-go@v12.0.0+incompatible: retracted by module author: pre-module versions are obsolete
go: to switch to the latest unretracted version, run:
        go get k8s.io/client-go@latest
```

We can try to do as it says, but then it tries to find a `kubevirt.io/client-go` version with a valid `k8s.io/client-go` dependency:

```shell
$ go get -v k8s.io/client-go@latest
go: kubevirt.io/client-go@v1.1.1 requires k8s.io/client-go@v12.0.0+incompatible, but v0.29.1 is requested
        trying kubevirt.io/client-go@v1.1.0
go: kubevirt.io/client-go@v1.1.0 requires k8s.io/client-go@v12.0.0+incompatible, but v0.29.1 is requested
        trying kubevirt.io/client-go@v1.1.0-rc.1
... And so on and so forth
```

Looking at the `go.mod` file of the `kubevirt.io/client-go` library, this seems reasonable, as it indeed specifies such dependency (which to me, also seems to be the root cause of the bug):

https://github.com/kubevirt/kubevirt/blob/81590657edb40020ad6a628eacc502eb4c701ced/staging/src/kubevirt.io/client-go/go.mod#L21

Now, Go wants to resolve that dependency but `v12.0.0+incompatible` is not a valid `k8s.io/client-go` version.

As a workaround, adding the following `replace` directives seems to make it work:

```
replace (
	k8s.io/api => k8s.io/api v0.26.4
	k8s.io/client-go => k8s.io/client-go v0.26.4
)
```

As it is done in the Kubevirt client:

https://github.com/kubevirt/kubevirt/blob/81590657edb40020ad6a628eacc502eb4c701ced/staging/src/kubevirt.io/client-go/go.mod#L79-L81

But that seems odd and I think shouldn't be that way.

Another solution, as described in the issue referenced above, is to built the client ourselves using `client-gen` and the like. However, if the Kubevirt client is already published, why shouldn't I use that and bother with generating the client code myself? Or is that the direction Kubevirt wants developers to go?

**Comment by cepaallium** [comment]
> We're facing the same issue (which also happens to affect some others, as described in this issue [kubevirt/client-go#28](https://github.com/kubevirt/client-go/issues/28)). To provide a bit more context to this issue:
> 
> We develop an application in Go which should manage `VirtualMachines` using Kubevirt in Kubernetes. To do so, we want to use the Kubernetes API. We already do some Kubernetes-related things in our application, so we already have the usual set of dependencies, like `k8s.io/api`, `k8s.io/client-go`, etc. Now, we wanted to add `kubevirt.io/client-go` as well so that we can use the existing generated clients to interface with the API, especially the functionality provided in `kubevirt.io/client-go/kubecli`, but that doesn't work and fails with a similar trace the OP posted.
> 
> Consider the following simple application:
> 
> ```
> module kubevirt-test
> 
> go 1.21.5
> 
> require kubevirt.io/client-go v1.1.1 // indirect
> ```
> 
> ```go
> package main
> 
> import (
> 	"kubevirt.io/client-go/kubecli"
> )
> 
> func main() {
> 	kubecli.GetKubevirtClientFromClientConfig(nil)
> }
> ```
> 
> If we now want to get the rest of the dependencies using `go get -v -d ./...`, this fails with a bunch of lines similar to what the OP pasted in the issue:
> 
> ```
> go: kubevirt-test imports
>         kubevirt.io/client-go/kubecli imports
>         k8s.io/client-go/kubernetes/typed/admissionregistration/v1: cannot find module providing package k8s.io/client-go/kubernetes/typed/admissionregistration/v1
> ```
> 
> And finally a line saying:
> 
> ```
> go: warning: k8s.io/client-go@v12.0.0+incompatible: retracted by module author: pre-module versions are obsolete
> go: to switch to the latest unretracted version, run:
>         go get k8s.io/client-go@latest
> ```
> 
> We can try to do as it says, but then it tries to find a `kubevirt.io/client-go` version with a valid `k8s.io/client-go` dependency:
> 
> ```shell
> $ go get -v k8s.io/client-go@latest
> go: kubevirt.io/client-go@v1.1.1 requires k8s.io/client-go@v12.0.0+incompatible, but v0.29.1 is requested
>         trying kubevirt.io/client-go@v1.1.0
> go: kubevirt.io/client-go@v1.1.0 requires k8s.io/client-go@v12.0.0+incompatible, but v0.29.1 is requested
>         trying kubevirt.io/client-go@v1.1.0-rc.1
> ... And so on and so forth
> ```
> 
> Looking at the `go.mod` file of the `kubevirt.io/client-go` library, this seems reasonable, as it indeed specifies such dependency (which to me, also seems to be the root cause of the bug):
> 
> https://github.com/kubevirt/kubevirt/blob/81590657edb40020ad6a628eacc502eb4c701ced/staging/src/kubevirt.io/client-go/go.mod#L21
> 
> Now, Go wants to resolve that dependency but `v12.0.0+incompatible` is not a valid `k8s.io/client-go` version.
> 
> As a workaround, adding the following `replace` directives seems to make it work:
> 
> ```
> replace (
> 	k8s.io/api => k8s.io/api v0.26.4
> 	k8s.io/client-go => k8s.io/client-go v0.26.4
> )
> ```
> 
> As it is done in the Kubevirt client:
> 
> https://github.com/kubevirt/kubevirt/blob/81590657edb40020ad6a628eacc502eb4c701ced/staging/src/kubevirt.io/client-go/go.mod#L79-L81
> 
> But that seems odd and I think shouldn't be that way.
> 
> Another solution, as described in the issue referenced above, is to built the client ourselves using `client-gen` and the like. However, if the Kubevirt client is already published, why shouldn't I use that and bother with generating the client code myself? Or is that the direction Kubevirt wants developers to go?

Hello, I did as you describe above. But I found another problem when I run my go project. It has an error which is:
```text
go\pkg\mod\k8s.io\client-go@v0.26.4\applyconfigurations\meta\v1\unstructured.go:64:38: cannot use doc (variable of type *"github.com/google/gnostic/openapiv2".Document) as *"github.com/google/gnostic-models/openapiv2".Document value in argument to proto.NewOpenAPIData
```

do you have the same question?

**Comment by remram44** [comment]
I have the same issue, it would be nice if the kubevirt client package was actually usable. https://github.com/kubevirt/client-go/issues/28 has some workarounds (which are basically: build a whole new client yourself) but this is not ideal for 1.0 software.

**Comment by remram44** [comment]
What does that means for the client-go repository?

**Comment by cepaallium** [comment]
> @cepaallium Sorry, I should have been more clear in my description. The `replace` directives work for the minimal example I provided. Depending on what dependencies your project uses (direct and indirect), you need to pin further dependencies inside `replace`. You can find the required versions in the [go.mod](https://github.com/kubevirt/kubevirt/blob/81590657edb40020ad6a628eacc502eb4c701ced/staging/src/kubevirt.io/client-go/go.mod) of the `client-go` package.
> 
> In your case, I think you are missing `k8s.io/kube-openapi => k8s.io/kube-openapi v0.0.0-20221012153701-172d655c2280` in your `replace` directive. In my project I also replace `k8s.io/apimachinery => k8s.io/apimachinery v0.26.4`, but that really depends on what you actually use in your project.



Hello， My go.mod content is as fellow:
```text
module os-virt

go 1.21

require (
	github.com/gin-gonic/gin v1.9.1
	github.com/google/uuid v1.6.0
	github.com/spf13/pflag v1.0.5
	github.com/spf13/viper v1.18.2
	go.uber.org/zap v1.26.0
	gopkg.in/natefinch/lumberjack.v2 v2.2.1
	k8s.io/api v0.29.1
	k8s.io/apiextensions-apiserver v0.29.1
	k8s.io/apimachinery v0.29.1
	k8s.io/client-go v12.0.0+incompatible
	kubevirt.io/api v0.0.0-20231225121335-9bda1c45015d
	kubevirt.io/client-go v1.1.1
	sigs.k8s.io/controller-runtime v0.17.0
)

require (
	github.com/beorn7/perks v1.0.1 // indirect
	github.com/bytedance/sonic v1.9.1 // indirect
	github.com/cespare/xxhash/v2 v2.2.0 // indirect
	github.com/chenzhuoyu/base64x v0.0.0-20221115062448-fe3a3abad311 // indirect
	github.com/coreos/prometheus-operator v0.38.3 // indirect
	github.com/davecgh/go-spew v1.1.2-0.20180830191138-d8f796af33cc // indirect
	github.com/emicklei/go-restful/v3 v3.11.0 // indirect
	github.com/evanphx/json-patch/v5 v5.8.0 // indirect
	github.com/fsnotify/fsnotify v1.7.0 // indirect
	github.com/gabriel-vasile/mimetype v1.4.2 // indirect
	github.com/gin-contrib/sse v0.1.0 // indirect
	github.com/go-kit/kit v0.10.0 // indirect
	github.com/go-logfmt/logfmt v0.5.1 // indirect
	github.com/go-logr/logr v1.4.1 // indirect
	github.com/go-openapi/jsonpointer v0.19.6 // indirect
	github.com/go-openapi/jsonreference v0.20.2 // indirect
	github.com/go-openapi/swag v0.22.3 // indirect
	github.com/go-playground/locales v0.14.1 // indirect
	github.com/go-playground/universal-translator v0.18.1 // indirect
	github.com/go-playground/validator/v10 v10.14.0 // indirect
	github.com/goccy/go-json v0.10.2 // indirect
	github.com/gogo/protobuf v1.3.2 // indirect
	github.com/golang/glog v1.0.0 // indirect
	github.com/golang/groupcache v0.0.0-20210331224755-41bb18bfe9da // indirect
	github.com/golang/mock v1.6.0 // indirect
	github.com/golang/protobuf v1.5.3 // indirect
	github.com/google/gnostic v0.5.7-v3refs // indirect
	github.com/google/go-cmp v0.6.0 // indirect
	github.com/google/gofuzz v1.2.0 // indirect
	github.com/gorilla/websocket v1.5.0 // indirect
	github.com/hashicorp/hcl v1.0.0 // indirect
	github.com/imdario/mergo v0.3.15 // indirect
	github.com/josharian/intern v1.0.0 // indirect
	github.com/json-iterator/go v1.1.12 // indirect
	github.com/k8snetworkplumbingwg/network-attachment-definition-client v0.0.0-20191119172530-79f836b90111 // indirect
	github.com/klauspost/cpuid/v2 v2.2.4 // indirect
	github.com/kubernetes-csi/external-snapshotter/client/v4 v4.2.0 // indirect
	github.com/leodido/go-urn v1.2.4 // indirect
	github.com/magiconair/properties v1.8.7 // indirect
	github.com/mailru/easyjson v0.7.7 // indirect
	github.com/mattn/go-isatty v0.0.19 // indirect
	github.com/matttproud/golang_protobuf_extensions/v2 v2.0.0 // indirect
	github.com/mitchellh/mapstructure v1.5.0 // indirect
	github.com/modern-go/concurrent v0.0.0-20180306012644-bacd9c7ef1dd // indirect
	github.com/modern-go/reflect2 v1.0.2 // indirect
	github.com/munnerz/goautoneg v0.0.0-20191010083416-a7dc8b61c822 // indirect
	github.com/openshift/api v0.0.0-20230503133300-8bbcb7ca7183 // indirect
	github.com/openshift/client-go v0.0.0-20210112165513-ebc401615f47 // indirect
	github.com/openshift/custom-resource-status v1.1.2 // indirect
	github.com/pborman/uuid v1.2.1 // indirect
	github.com/pelletier/go-toml/v2 v2.1.0 // indirect
	github.com/pkg/errors v0.9.1 // indirect
	github.com/prometheus/client_golang v1.18.0 // indirect
	github.com/prometheus/client_model v0.5.0 // indirect
	github.com/prometheus/common v0.45.0 // indirect
	github.com/prometheus/procfs v0.12.0 // indirect
	github.com/sagikazarmark/locafero v0.4.0 // indirect
	github.com/sagikazarmark/slog-shim v0.1.0 // indirect
	github.com/sourcegraph/conc v0.3.0 // indirect
	github.com/spf13/afero v1.11.0 // indirect
	github.com/spf13/cast v1.6.0 // indirect
	github.com/subosito/gotenv v1.6.0 // indirect
	github.com/twitchyliquid64/golang-asm v0.15.1 // indirect
	github.com/ugorji/go/codec v1.2.11 // indirect
	go.uber.org/multierr v1.11.0 // indirect
	golang.org/x/arch v0.3.0 // indirect
	golang.org/x/crypto v0.16.0 // indirect
	golang.org/x/exp v0.0.0-20230905200255-921286631fa9 // indirect
	golang.org/x/net v0.19.0 // indirect
	golang.org/x/oauth2 v0.15.0 // indirect
	golang.org/x/sys v0.16.0 // indirect
	golang.org/x/term v0.15.0 // indirect
	golang.org/x/text v0.14.0 // indirect
	golang.org/x/time v0.5.0 // indirect
	gomodules.xyz/jsonpatch/v2 v2.4.0 // indirect
	google.golang.org/appengine v1.6.7 // indirect
	google.golang.org/protobuf v1.31.0 // indirect
	gopkg.in/inf.v0 v0.9.1 // indirect
	gopkg.in/ini.v1 v1.67.0 // indirect
	gopkg.in/yaml.v2 v2.4.0 // indirect
	gopkg.in/yaml.v3 v3.0.1 // indirect
	k8s.io/component-base v0.29.1 // indirect
	k8s.io/klog/v2 v2.110.1 // indirect
	k8s.io/kube-openapi v0.0.0-20231010175941-2dd684a91f00 // indirect
	k8s.io/utils v0.0.0-20230726121419-3b25d923346b // indirect
	kubevirt.io/containerized-data-importer-api v1.57.0-alpha1 // indirect
	kubevirt.io/controller-lifecycle-operator-sdk/api v0.0.0-20220329064328-f3cc58c6ed90 // indirect
	sigs.k8s.io/json v0.0.0-20221116044647-bc3834ca7abd // indirect
	sigs.k8s.io/structured-merge-diff/v4 v4.4.1 // indirect
	sigs.k8s.io/yaml v1.4.0 // indirect
)

replace (
	k8s.io/api => k8s.io/api v0.26.4
	k8s.io/apimachinery => k8s.io/apimachinery v0.26.4
	k8s.io/client-go => k8s.io/client-go v0.26.4
	k8s.io/kube-openapi => k8s.io/kube-openapi v0.0.0-20221012153701-172d655c2280
)
```
I run my project after I go mod tidy. It has error like:
```text
"D:\Program Files\go1.21.7.windows-amd64\go\bin\go.exe" build -o C:\Users\1\AppData\Local\JetBrains\GoLand2023.1\tmp\GoLand\___2go_build_os_virt_cmd.exe os-virt/cmd #gosetup
# sigs.k8s.io/controller-runtime/pkg/internal/source
C:\Users\1\go\pkg\mod\sigs.k8s.io\controller-runtime@v0.17.0\pkg\internal\source\kind.go:56:18: undefined: wait.PollUntilContextCancel
# sigs.k8s.io/controller-runtime/pkg/certwatcher
C:\Users\1\go\pkg\mod\sigs.k8s.io\controller-runtime@v0.17.0\pkg\certwatcher\certwatcher.go:98:18: undefined: wait.PollUntilContextTimeout
```

Do you know what is the problems? Thanks very much.

**Comment by IronmanGC** [comment]
Hi Team,
I'm trying to consume kubevirt velero plugin in my repo but facing similar issues mentioned above. My repo consuming latest packages After replacing recommended version 0.26.4 its failing while building source code due signature changes.

Build error :
`pkg/builder/persistent_volume_claim_builder.go
:104:32: cannot use dataSourceRef (variable of type *"k8s.io/api/core/v1".TypedLocalObjectReference) as *"k8s.io/api/core/v1".TypedObjectReference value in assignment
# k8s.io/client-go/applyconfigurations/meta/v1
vendor/k8s.io/client-go/applyconfigurations/meta/v1/unstructured.go
:64:38: cannot use doc (variable of type *"github.com/google/gnostic/openapiv2".Document) as *"github.com/google/gnostic-models/openapiv2".Document value in argument to proto.NewOpenAPIData`
