### ISSUE TITLE
Creating a fresh VM with an empty secret for Access Credentials causes index out of range error and crashes the VM

### ISSUE THREAD

**Issue by ishankhare07** [kubevirt/kubevirt#11116]
**What happened**:
Tried creating a fresh VM with `AccessCredentials` as `sshPublicKey` and `propagationMethod` as `qemuGuestAgent` causes the VM to crash. If the secret is initailly created with dummy keys, and later dummy keys removed from secret (essentially emptying the secret) the running VM keeps running without crashing. This only happens in case of a fresh VM startup. If the VM is already running and all keys are removed from the secret, VM doesn't crash.

**What you expected to happen**:
The VM should be created with crashing and `authorized_keys` should be empty - as is the case if all keys removed from and existing attached secret. 

**How to reproduce it (as minimally and precisely as possible)**:
Create the VM with empty secret attached for SSH access credentials.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by alicefr** [comment]
@ishankhare07 could you please provide virt-launcher logs of the crashed VM?
