### ISSUE TITLE
Make `image` field optional in the `HookSidecar` struct

### ISSUE THREAD

**Issue by dharmit** [kubevirt/kubevirt#11161]
Presently, it's mandatory for a hook sidecar user to provide a container image in the annotations when using the feature. Making this field optional by using an image with digest in virt-operator, much like how it's done in [this commit](https://github.com/kubevirt/kubevirt/pull/9177/commits/88bee3a38e1ab0bbbc3bc5f6fc7605cffc33be4a), would be helpful.

Using an image with digest that is based on some crypto function helps ensure that an image is not tempered with, which could plausibly be the case when using plain tags. This is especially useful in case of disconnected environment where images need to be pulled onto internal registry in advance.

**Comment by dharmit** [comment]
cc @victortoso @tiraboschi

**Comment by dharmit** [comment]
> I think the proposal is fine, but it is a breaking change.

If the code still uses an image provided by the user, would it still be a breaking change? That is, if no image is provided, we use the built-in default. But if the user provides an image, we use that instead. 

I should have mentioned this in the original comment, my bad.

> I think it is reasonable for the next version when we promote hook api to Beta. We should do it early after KubeVirt 1.2.0 is released, I think.

Sure. WDYT is required to make it optional? I think it's about changing:
```go
type HookSidecar struct {
	Image           string           `json:"image"`
```
to
```go
type HookSidecar struct {
	Image           string           `json:"image,omitempty"`
```
and making changes in code to use the default if no image is provided, or use the one provided in annotation.

Am I thinking right?

**Comment by victortoso** [comment]
> If the code still uses an image provided by the user, would it still be a breaking change? That is, if no image is provided, we use the built-in default. But if the user provides an image, we use that instead.

I think so because Today image is mandatory and code would not work without it. With the proposal change, it means a specific image will be used.

It isn't a disruptive change, that is, code that works will keep working. But a scenario that did not work would now work in, perhaps, unexpected ways.

> Am I thinking right?

Yes, I think so but, to be 100% honest, I'm not sure how the definition of the 'default image' is going to look like, but I trust you and @tiraboschi have this figured out.

**Comment by victortoso** [comment]
Have you thought how this will work when updating the KubeVirt version, let's say, from v1.3.0 to v1.4.0 and the `sidecar-shim` introduced some breaking changes?

- Will the sidecar keep using the image from v1.3.0 somehow?
- Should we fail to upgrade or just fail to launch the sidecar, requiring the user to adapt to the changes like in the ConfigMap or others that sidecar-shim might have broke.

**Comment by dharmit** [comment]
> let's say, from v1.3.0 to v1.4.0 and the `sidecar-shim` introduced some breaking changes?
> 
> * Will the sidecar keep using the image from v1.3.0 somehow?
> 
> * Should we fail to upgrade or just fail to launch the sidecar, requiring the user to adapt to the changes like in the ConfigMap or others that sidecar-shim might have broke.



TBH, I don't know a lot about what goes into upgrading from one version to another. But if `virt-operator` is getting updated (which I think does), the sidecar image info will be updated as well. I believe so because once a commit like [this](https://github.com/kubevirt/kubevirt/pull/9177/commits/88bee3a38e1ab0bbbc3bc5f6fc7605cffc33be4a) but for sidecar-shim gets merged into the repo, we will have the image info baked in. Unless the user is using a custom image for it.
