### ISSUE TITLE
Bazel can't push to private repository

### ISSUE THREAD

**Issue by p-alik** [kubevirt/kubevirt#11173]
**What happened**:
Unable to push locally built images to a private docker registry
```
$ git reflog show -1
417acc22ae (HEAD -> main, origin/main, origin/HEAD) HEAD@{0}: pull --rebase: Fast-forward
$ export DOCKER_PREFIX="<REGISTRY>"
$ export DOCKER_TAG=latest
$ make && bazel-build-images && make push
INFO: Build completed successfully, 52 total actions
2024/02/07 09:54:50 Error pushing image to <REGISTRY>/virt-operator:latest: unable to push image to <REGISTRY>/virt-operator:latest: GET https://<REGISTRY>/auth/token?scope=repository%3Avirt-operator%3Apush%2Cpull&service=<REGISTRY>: unsupported status code 401; body: unauthorized
make: *** [Makefile:36: bazel-push-images] Error 1
```

`curl` request to the URL in the error message succeeds
```
$ curl --head --user '<USER>:<PASSWORD>' 'https://<REGISTRY>/auth/token?scope=repository%3Avirt-operator%3Apush%2Cpull&service=<REGISTRY>'
HTTP/2 200 
date: Wed, 07 Feb 2024 10:31:28 GMT
content-type: application/json
content-length: 1659
strict-transport-security: max-age=15724800; includeSubDomains
```

**What you expected to happen**:

`make push` like regular `docker push` to the same `<REGISTRY>` succeeds
```
$ docker push <REGISTRY>/foo:latest
The push refers to repository [<<REGISTRY>/foo]
fb1bd2fc5282: Pushed
```

**How to reproduce it (as minimally and precisely as possible)**:

* clone kubevirt repo
* follow build instruction [I just want it built and run it on my cluster](https://github.com/kubevirt/kubevirt/blob/main/docs/getting-started.md#i-just-want-it-built-and-run-it-on-my-cluster)

**Environment**:
- Kubernetes version (use `kubectl version`):
```
$ kubectl version --client
Client Version: v1.28.4
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
```
- OS (e.g. from /etc/os-release):
```
$ cat /etc/os-release 
BUG_REPORT_URL="https://github.com/NixOS/nixpkgs/issues"
BUILD_ID="23.11.4030.9f2ee8c91ac4"
DOCUMENTATION_URL="https://nixos.org/learn.html"
HOME_URL="https://nixos.org/"
ID=nixos
LOGO="nix-snowflake"
NAME=NixOS
PRETTY_NAME="NixOS 23.11 (Tapir)"
SUPPORT_END="2024-06-30"
SUPPORT_URL="https://nixos.org/community.html"
VERSION="23.11 (Tapir)"
VERSION_CODENAME=tapir
VERSION_ID="23.11"
```
- Kernel (e.g. `uname -a`):
```
$ uname -a
Linux ls03064 6.1.76 #1-NixOS SMP PREEMPT_DYNAMIC Thu Feb  1 00:17:12 UTC 2024 x86_64 GNU/Linux
```

**Comment by akalenyu** [comment]
So there is this gotcha with Bazel that it expects creds to be in `~/.docker/config.json`.
But, kubevirt supposedly has a hack to bypass this:
https://github.com/kubevirt/kubevirt/blob/79e1774e46e1611240f648acca9f3aa6719db6d5/hack/dockerized#L113-L115
I am not sure why this is not working for you.. there's probably some bug in this area

Could you check if your creds are in `${XDG_RUNTIME_DIR}/containers/auth.json`, and that this line is indeed exercised
when you run the make command?

**Comment by p-alik** [comment]
Beside of one exception `make push` succeeded after `make clean` and removal of docker volume and image. So I beg your pardon for troubling you.
For sake of completeness here the error `make push` run into
```
Target //:push-alpine-ext-kernel-boot-demo up-to-date:
  bazel-bin/push-alpine-ext-kernel-boot-demo.digest
  bazel-bin/push-alpine-ext-kernel-boot-demo
INFO: Elapsed time: 0.258s, Critical Path: 0.06s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
2024/02/09 08:13:54 Successfully pushed Docker image to <REGISTRY>/alpine-ext-kernel-boot-demo:latest
INFO: Analyzed target //:push-fedora-with-test-tooling-container-disk (0 packages loaded, 5 targets configured).
INFO: Found 1 target...
Target //:push-fedora-with-test-tooling-container-disk up-to-date:
  bazel-bin/push-fedora-with-test-tooling-container-disk.digest
  bazel-bin/push-fedora-with-test-tooling-container-disk
INFO: Elapsed time: 0.260s, Critical Path: 0.06s
INFO: 1 process: 1 internal.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
2024/02/09 08:15:29 Error pushing image to <REGISTRY>/fedora-with-test-tooling-container-disk:latest: unable to push image to <REGISTRY>/fedora-with-test-tooling-container-disk:latest: PATCH https://<REGISTRY>/v2/fedora-with-test-tooling-container-disk/blobs/uploads/d7a3df7e-5922-470b-97a8-537935c6d351?_state=REDACTED: UNKNOWN: unknown error; SignatureDoesNotMatch: The request signature we calculated does not match the signature you provided. Check your AWS Secret Access Key and signing method. For more information, see REST Authentication and SOAP Authentication for details.
	status code: 403, request id: 2d72e705-4b92-1f85-a56f-1070fd9e6eb6, host id: 
make: *** [Makefile:36: bazel-push-images] Error 1
```

**Comment by p-alik** [comment]
@akalenyu, to your questions
> Could you check if your creds are in `${XDG_RUNTIME_DIR}/containers/auth.json`, and that this line is indeed exercised
when you run the make command?

There is no `${XDG_RUNTIME_DIR}/containers/auth.json` nor the line appeared in the `make` output
``` 
[apastuchov@ls03064 kubevirt (main)]$ ll ${XDG_RUNTIME_DIR}/containers/auth.json
ls: cannot access '/run/user/1000/containers/auth.json': No such file or directory
```

**Comment by akalenyu** [comment]
> @akalenyu, to your questions
> 
> > Could you check if your creds are in `${XDG_RUNTIME_DIR}/containers/auth.json`, and that this line is indeed exercised
> > when you run the make command?
> 
> There is no `${XDG_RUNTIME_DIR}/containers/auth.json` nor the line appeared in the `make` output
> 
> ```
> $ ll ${XDG_RUNTIME_DIR}/containers/auth.json
> ls: cannot access '/run/user/1000/containers/auth.json': No such file or directory
> ```

In this case, I guess you fall into the `else` branch, which should still help solve the issue, not sure what went wrong..
