### ISSUE TITLE
Optimize IsKubeVirtServiceAccount()

### ISSUE THREAD

**Issue by orelmisan** [kubevirt/kubevirt#11177]
**Is your feature request related to a problem? Please describe**:
https://github.com/kubevirt/kubevirt/blob/f081b2bf56f629788e46359c8d2e008fbe7834a7/pkg/virt-api/webhooks/utils.go#L83
`IsKubeVirtServiceAccount` is called from:
- VMI mutating webhook
- VMI creation validating webhook
- VMI update validating webhook

Every time this function is called, it [reads](https://github.com/kubevirt/kubevirt/blob/17517e765488f3dfd0c4272781d56522dc6051f4/staging/src/kubevirt.io/client-go/util/util.go#L13) a static file containing the namespace in which the `virt-api` pod is running.

**Describe the solution you'd like**:
Refactor the code in a way that will read the namespace file only once.

**Describe alternatives you've considered**:

**Additional context**:

**Comment by mukeshkuiry** [comment]
![image](https://github.com/kubevirt/kubevirt/assets/99157367/009d886f-900b-45d4-ba09-c8a179e092a8)
Can we do something like this, @orelmisan?

In this method, it's just calling the components once

**Comment by orelmisan** [comment]
Thank you for looking into it @mukeshkuiry.
The problem described in the issue is related to unnecessary and repeated reads from the file system.
In every pod, there is a file containing the name of the namespace in which the pod resides [1]. 
This name does not change throughout the life-cycle of the pod - yet the code reads its content over and over for no reason.

[1] https://kubernetes.io/docs/tasks/run-application/access-api-from-pod/#directly-accessing-the-rest-api

**Comment by orelmisan** [comment]
PR #12009 introduced additional call to `webhooks.GetNamespace()` in `VMIUpdateAdmitter.Admit()`.

**Comment by orelmisan** [comment]
There are two instances of `webhooks.IsKubeVirtServiceAccount` left in production code:
https://github.com/kubevirt/kubevirt/blob/ee2bc7773d95eb4011d96ee709a9442400066378/pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go#L1222

https://github.com/kubevirt/kubevirt/blob/deb074f8a28a5fe828877b9921c9294fd61174c6/pkg/virt-api/webhooks/validating-webhook/admitters/vmi-update-admitter.go#L371

**Comment by orelmisan** [comment]
Since the implementation details are tested in the unit tests (and not the overall behavior), some refactoring of the unit tests is also required.
