### ISSUE TITLE
Move base images to Fedora:28

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1117]
Today most (all?) images are using Fedora 27.

We should move them to Fedora 28.

**Comment by rmohr** [comment]
For libvirt the goal is to go with centos (from  my point of view), the other containers should go distroless.

**Comment by fabiand** [comment]
Distroless as in "FROM SCRATCH"?

i do think that they need at least a libc.

I'll comment on libvirt separately.

**Comment by rmohr** [comment]
> Distroless as in "FROM SCRATCH"?

Distroless as in [distroless](https://github.com/GoogleContainerTools/distroless). The go base container only contains glibc (I thinkg about 7mb). The k8s container use them. The advantage is their small size and more security. We basically can always use the latest and best distroless base without having to care about the base images which are required for libvirt. That makes upgrading for both much easier since we can handle them independently without disadvantages.

**Comment by rmohr** [comment]
> "distroless" is also a distro, they are building binaries which are consumed. The issue is that there is fe winsights into what binaries are provided, and how they were built.

? It is called distroless. You were implying that nothing is in there. Not me.

**Comment by fabiand** [comment]
@berrange is it a viable approach right now to follow F28 qemu/libvirt to inherit all possibel changes coming up?

**Comment by berrange** [comment]
Not sure what changes you're referring to here ?

Libvirt / QEMU versions are frozen at time of beta release for Fedora. After that point we only do bug fixes to each stable branch. There's a separate "virt preview" add on repo you can use if you want to pull in latest virt stack - it is basically the rawhide packages, but rebuilt for latest stable Fedora branch 

https://fedoraproject.org/wiki/Virtualization_Preview_Repository

**Comment by fabiand** [comment]
> Not sure what changes you're referring to here ?

I heared that a "recent" qemu version is needed in order to be able to indivudally specify IBRS etc CPU flags.
And I wondered if qemu in fedora is recent enough.

I'd assume that if we move to fedora28, that this stream should be fine for now?

**Comment by berrange** [comment]
There are updates issued in Fedora repos with the required CPU fixes / flags. I'm unclear, however, if the docker images ever get rebuild, and if they do, how frequently it happens.

**Comment by fabiand** [comment]
Okay. if Fedora is good, then we "just" need to see that we keep our images updated as well.

I created https://github.com/kubevirt/libvirt/issues/16 to get the base image updated.

**Comment by berrange** [comment]
BTW even with the updated qemu/libvirt RPMS, you can't just blindly assume you can use  IBRS  CPU models / SSBD CPU feature.  The host kernel needs to have been updated and the CPU microcode also updated. For extra fun there is no publically available microcode quite yet for SSBD feature.  Libvirt provides APIs you can use to query whether given CPU models & features are usable for the given host or not.

**Comment by fabiand** [comment]
Yes, good for pointing this out. I just don't worry about the host to much, because it's up to the operator, we just need to see that we do our homework on the container side.

**Comment by berrange** [comment]
Yes, just wanted to make sure you're careful not to make config choices that prevent your ability to launch VMs on certain operators if they've not deployed the corresponding host changes.
