### ISSUE TITLE
e2e: swap-enabled tests are failing on k8s-1.29

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#11201]
virt-launcher get killed due to OOM, even that swap is enabled
and the stress test is failing

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11190/pull-kubevirt-e2e-k8s-1.29-swap-enabled/1755609214228631552

/bug

**Comment by Barakmor1** [comment]
The OOMKiller started working, even though the swap is enabled. The recent changes that caused the tests to fail were expected because these tests were created during the early stages of swap implementation. Therefore, we'll need to update the swap tests to match Kubernetes 1.29.

**Comment by oshoval** [comment]
iirc Barak fixed it, but i am less into the details of it

**Comment by Barakmor1** [comment]
No, this still doesn't work. Swap, OOMKilled, and eviction thresholds have significantly changed since I wrote these tests.
