### ISSUE TITLE
Proposal changes for hook sidecar Beta

### ISSUE THREAD

**Issue by victortoso** [kubevirt/kubevirt#11215]
**Is your feature request related to a problem? Please describe**:
The Alpha version of the hook sidecar has been around for a few years. We have been discussing its promotion to Beta. This issue is to list a few suggestions that we could agree and implement for the Beta release.

**Describe the solution you'd like**:
We will have v1alpha3 released in KubeVirt 1.2.0. I hope we can get the list below implemented to declare the new Beta version for KubeVirt 1.3.0

**Describe alternatives you've considered**:
No alternatives were considered.

**Additional context**:
- [ ] https://github.com/kubevirt/kubevirt/issues/11161 - Make image field optional in the HookSidecar struct
- [ ] Expose supported hook sidecar versions supported - [suggested by Alice](https://github.com/kubevirt/kubevirt/pull/10842#discussion_r1466041563)
- [ ] Option for upgrade support, changing options as needed (e.g: [supporting moving from one image to another](https://github.com/kubevirt/kubevirt/issues/11161#issuecomment-1938424724))

**Comment by victortoso** [comment]
cc @alicefr @dharmit @EdDev @vasiliy-ul

**Comment by EdDev** [comment]
I will like to take this opportunity and raise the following:
- The current API requires the bump of the protocol version each time a new option is added. As we have seen lately, this is problematic as new options are requested frequently and it is unreasonable to support so many versions in parallel.
- The sidecar author needs to implement all options, even if some are not relevant. This may be related to the previous point.

I think we need to resolve the evolution of options in the protocol. We cannot continue and require its bump all the time, it is not realistic. I think this needs to be solved before entering Beta.

**Comment by victortoso** [comment]
We should add the change to use full libvirt xml between hook sidecar and virt-launcher.
- We should expected that the hook sidecar will add changes that are not supported by schema.go
- We should consider that virt-launcher might call the hook (e.g: OnDefineDomain) [more than once](https://github.com/kubevirt/kubevirt/pull/11324#issuecomment-1963766377).

So, proposal:

 - [ ] The communication between hook sidecar and virt-launcher wrt to libvirt's domain should always be the complete libvirt domain xml to keep the consistency in case we have multiple sidecars or they are being called more than once.
In practice, we should be using libvirtxml in virt-launcher (see https://github.com/kubevirt/kubevirt/issues/10844#issuecomment-1954429904)
