### ISSUE TITLE
refactor: simplify reconcileSpec in restore.go

### ISSUE THREAD

**Issue by alicefr** [kubevirt/kubevirt#11262]
The function [`reconcileSpec`](https://github.com/kubevirt/kubevirt/blob/main/pkg/storage/snapshot/restore.go#L414C27-L414C40) is very complex and have a lot of loops and nested if statements. The goal is to split this in multiple functions and to reduce the if statement nesting complexity

This would be a good issue for people willing to get more familiar with the code for GSoC

**Comment by anishbista60** [comment]
anyone woriking in this improvement.
