### ISSUE TITLE
`virtctl vnc vm` fails with 401 permission denied

### ISSUE THREAD

**Issue by alvaroaleman** [kubevirt/kubevirt#1126]
Hello,

Trying out the demo, `virtctl vnc vmname` fails with a `Error encountered: Can't connect to websocket (401): request is not authenticated`.

This error ultimatively comes from the extensions apiserver and is logged as `level=info timestamp=2018-06-09T11:47:20.345809Z pos=filter.go:46 component=virt-api remoteAddress=172.25.0.6 username=- method=GET url=/apis/subresources.kubevirt.io/v1alpha1/namespaces/default/virtualmachines/test-ubuntu-vm/vnc proto=HTTP/1.1 statusCode=401 `

I am not entirely sure how to proceed debugging from there, any hints?

**Comment by fabiand** [comment]
@davidvossel any idea?

**Comment by rmohr** [comment]
@alvaroaleman did you follow the instructions here at the [RBAC documentation](https://kubevirt.io/user-guide/#/authorization?id=extending-kubernetes-default-roles-with-kubevirt-permissions)?
It looks like you did not give your user permissions to use the resource.

You can either add the annotations mentioned there to our roles so that every user gets access in his namespaces, or can create your own binding which suite your own needs.

**Comment by davidvossel** [comment]
@rmohr it's authentication not authorization.

@alvaroaleman that error indicates that client certificates are not being sent. our api server requires TLS with client certs. 

https://github.com/kubevirt/user-guide/pull/83

**Comment by rmohr** [comment]
> @alvaroaleman that error indicates that client certificates are not being sent. our api server requires TLS with client certs.

That would be new to me. It should as well work with e.g. service account tokens.

**Comment by davidvossel** [comment]
@rmohr This is a server side setting. this client certs between k8s api server and kubevirt apiserver. 

users authenticate with k8s api server, then k8s apiserver presents its peer cert during the proxy call to our kubevirt apiserver.

Without the k8s peer cert, kubevirt's apiserver can't trust the connection.

**Comment by rmohr** [comment]
> @rmohr This is a server side setting. this client certs between k8s api server and kubevirt apiserver.

Then we may need to change the working a little bit. From the user-guide update it was not clear to me  that this is not related to the client-authentication. It left the impression to me that I as a user need to authenticate via a certificate.

**Comment by alvaroaleman** [comment]
So the issue is that the kubevirt extension apiserver does not trust the primary api servers cert?

**Comment by davidvossel** [comment]
>So the issue is that the kubevirt extension apiserver does not trust the primary api servers cert?

specifically, the issue is that the k8s apiserver is not providing the kubevirt apiserver with a peer certificate. 

This is the check that is failing on our side to cause the authentication error.  The request is coming from the k8s apiserver. The k8s apiserver is supposed to include a peer cert verifying that the request is originating from a trusted endpoint.  Without that cert, our endpoint can't verify that the request is trusted. 
```
        // Peer cert is required for authentication.
        // If the peer's cert is provided, we are guaranteed
        // it has been validated against our client CA pool
        if req.Request == nil || req.Request.TLS == nil || len(req.Request.TLS.PeerCertificates) == 0 {
                return false
        }
```

**Comment by alvaroaleman** [comment]
Ah, thanks a lot! So for the record, the required flags on the kube-apiserver are:

```
--proxy-client-cert-file=<path to aggregator proxy cert>
--proxy-client-key-file=<path to aggregator proxy key>
```
Where `<path to aggregator proxy cert>` can be just the tls serving cert

**Comment by fabiand** [comment]
@alvaroaleman good to hear it's fixed - just to get a better picture: What kube distro and os where you using?

**Comment by alvaroaleman** [comment]
[Kubermatic](https://www.loodse.com/product) which is a commercial cluster manager offering by my employer that does Kubernetes in Kubernetes

**Comment by pastukhov** [comment]
I faced same issue. 
I have ```--proxy-client-cert-file```, ```--proxy-client-key-file`` and ``extension-apiserver-authentication``` configmap  in ```kube-system``` namespace, 
but i'm getting 
```{"component":"virt-api","contentLength":28,"level":"info","method":"GET","pos":"filter.go:46","proto":"HTTP/1.1","remoteAddress":"10.219.98.129","statusCode":401,"timestamp":"2019-04-12T17:01:32.166110Z","url":"/apis/subresources.kubevirt.io/v1alpha3/namespaces/kubevirt-vm/virtualmachineinstances/123/console","username":"-"}``` 
when try
```virtctl -n kubevirt-vm console testvmi-nocloud```
Any advice, pls.

**Comment by rmohr** [comment]
Hi @pastukhov could you run `virtcl version` and post the result here? Are you using an on-premis cluster, or did you set it up yourself?

**Comment by pastukhov** [comment]
```
Client Version: version.Info{GitVersion:"v0.16.0", GitCommit:"06d91198bededc7a9353ac774221c83580ee3373", GitTreeState:"clean", BuildDate:"2019-04-05T15:24:49Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.16.0-17+052a787abed701", GitCommit:"052a787abed701635ab6b3b54a54532e7ecb4bda", GitTreeState:"clean", BuildDate:"2019-04-11T11:58:44Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
I'm using kubernetes cluster on bare metal bootstrapped with kubespray: 
```
pastukhov@pastukhov-H110M-HD2:~$ kubectl version 
Client Version: version.Info{Major:"", Minor:"", GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"9e4010d067ee4d799330980e62830b06a07296bd", GitTreeState:"clean", BuildDate:"2018-04-26T04:13:21Z", GoVersion:"go1.10.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.11", GitCommit:"637c7e288581ee40ab4ca210618a89a555b6e7e9", GitTreeState:"clean", BuildDate:"2018-11-26T14:25:46Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
I have many other api extensions that working well

**Comment by slintes** [comment]
@pastukhov this issue might be related: https://github.com/kubernetes-sigs/kubespray/issues/2481

Can you please check if in the `extension-apiserver-authentication` configmap, the values of `client-ca-file` and `requestheader-client-ca-file` are different? And it seems the former has to be signed by the latter.
