### ISSUE TITLE
Support podAntiAffinity

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1127]
The guide indicates that VMs support podAffinity (see http://www.kubevirt.io/user-guide/#/workloads/virtual-machines/assigning-vms-to-nodes?id=affinity-and-anti-affinity).

podAffinity will land soon.

But for consistency it would be good so support podAntiAffinity as well.

**Comment by slintes** [comment]
Since it's directly related, I will implement this in the podAffinity PR (https://github.com/kubevirt/kubevirt/issues/1101)
