### ISSUE TITLE
Discussion: Windows+Windows Documentation 

### ISSUE THREAD

**Issue by Neoclassic** [kubevirt/kubevirt#11281]
I assume a lot of people struggle while using kubervirt + Windows. Lets compile a list of question and answers/solutions too to serve the community.

1. Tools to automate windows VM creation, running windows packed with custom application ? [Packer, Bash scripts] [not the basic ISO based installation]
2. virtio vs sata ? What to use ? 
3. The VM fails to boot when sata is changed to virtio.
4. How to launch multiple VMs using a qcow2 image? Is it possible to launch non interferring VM in this way ?
5. How to pass environment variables into the windows VM ?  (Tried secret disk/cloudInit, but they do not appear in disk list)
6. How to expose windows port? (Done it using Service + Windows Firewall rule)
7. Performance tuning with resp to drivers, cpu flags ?

**Comment by fabiand** [comment]
1. The lack of standardized open source tools for reliably creating Windows images is - and made it hard in the past - to provide this tooling. It's simply work an sweat to create a pipeline robust and mature enough to create such images.
2. Virtio - but you need the virtio drivers to be installed. Ask Microsoft to do this by default.
3. Yes. This is known.
4. KubeVirt relies on CSI do provide smart cloning. IOW: Write whatever OS image onto a PVC, then use DataVolumes to automatically clone them for starting new VMs.
5. If done right, then they should appear as ISOs. More details are needed
6. More details are needed
7. Look into https://github.com/kubevirt/common-instancetypes which provides Preferences for Windows.

Generally speaking: You want a Windows guide. We look for contributors to help create such a guide.

**Comment by scydas** [comment]
add ticket
import windows vm from vmware or other
