### ISSUE TITLE
refactor: create common interface for device plugins

### ISSUE THREAD

**Issue by alicefr** [kubevirt/kubevirt#11293]
KubeVirt already supports several kinds of devices which have similar structure and logic like health checking and monitoring of the device or the synchronization mechanism.
The goal of this refactor is finding the  shared functionality,  proposing and creating a standard framework and interfaces for KubeVirt device plugins are the objectives of the project.
This would simplify and eliminate redundant code, enhance testing, and make it easier to add new device plugins in the future.

**Comment by aerosouund** [comment]
I want to try this, please assign it to me

**Comment by anishbista60** [comment]
@alicefr  i wanna work on this issue . please assign it to me

**Comment by anishbista60** [comment]
@sarthaksarthak9  ok thank you
