### ISSUE TITLE
refactor: simplify validateDisks function

### ISSUE THREAD

**Issue by alicefr** [kubevirt/kubevirt#11305]
The function [validateDisks](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go#L2282) is long, complex and contains a lot of nesting levels. It can be split in multiple functions and we could try to reduce the nesting.

This is a good first issue for people interested in GSoC and who want to get familiar with contributing to KubeVirt

**Comment by zakisk** [comment]
@alicefr I want to work on it please assign it.

**Comment by arujjval** [comment]
is someone still working on this?

**Comment by anishbista60** [comment]
I'm working and probably will take 1 week to fix this issue.

**Comment by harsh-vardhan-ande** [comment]
Hi @alicefr. I have raised https://github.com/kubevirt/kubevirt/pull/12060 to fix this.
