### ISSUE TITLE
refector: Replacing deprecated or unsafe packages

### ISSUE THREAD

**Issue by yj-yoo** [kubevirt/kubevirt#11316]
**Is your feature request related to a problem? Please describe**:
Replacing deprecated or unsafe packages
ex) math/rand, rand.Seed() etc...  

**Describe the solution you'd like**:

**Describe alternatives you've considered**:

**Additional context**:

**Comment by alicefr** [comment]
@yj-yoo could you please add a list of the packages and a link that describe the deprecation or why they are unsafe

**Comment by yj-yoo** [comment]
@alicefr
deprecated 
1. rand.Seed()
`
The math/rand package now automatically seeds the global random number generator (used by top-level functions like Float64 and Int) with a random value, and the top-level Seed function has been deprecated. Programs that need a reproducible sequence of random numbers should prefer to allocate their own random source, using rand.New(rand.NewSource(seed)).
`
ref: https://tip.golang.org/doc/go1.20

2. grpc.WithInsecure()
https://stackoverflow.com/questions/70482508/grpc-withinsecure-is-deprecated-use-insecure-newcredentials-instead

3. StreamWithContext()
https://github.com/kubernetes/kubernetes/pull/103177

4. golang.org/x/crypto/ssh/terminal
https://pkg.go.dev/golang.org/x/crypto/ssh/terminal

5. k8s.io/utils/pointer
https://pkg.go.dev/k8s.io/utils/pointer

etc...
1. time.Since() -> time.Now().Sub

2.
`
        query := fmt.Sprintf(resourceRequestCountsByOperation, int(rangeVector.Seconds()), lookBack)
	log.Printf(query)
`
to 
`
	log.Printf(fmt.Sprintf(resourceRequestCountsByOperation, int(rangeVector.Seconds()), lookBack))
`
