### ISSUE TITLE
[help] make test error in pkg/virtctl/version:go_default_test

### ISSUE THREAD

**Issue by yj-yoo** [kubevirt/kubevirt#11343]
**What happened**:
hi.
I'm struggling with two issues, and both seem to produce the same error when I run make test locally.
(Actually, it was my first issue and I thought it would be simple, but there were more changes than I expected and the testing environment was unfamiliar, so I ran into difficulties.😭)
The point is... I need a hint. The error contents are as follows.

pic 1.
<img width="1146" alt="스크린샷 2024-02-24 오전 12 55 24" src="https://github.com/kubevirt/kubevirt/assets/153485739/f895e54c-fd11-4106-99d4-76b2fda852fc">

pic2
<img width="1440" alt="스크린샷 2024-02-24 오전 12 55 10" src="https://github.com/kubevirt/kubevirt/assets/153485739/98665784-1a4a-4d6d-96a4-adab1897b9c6">

For both of the previously mentioned issues, the version package has not been modified and the related packages do not seem to be referenced.
Tested in Docker environment on Mac and Ubuntu 20.04.
Did I miss something? Or is it just a code mistake on my part?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by fossedihelm** [comment]
Hi @yj-yoo! Thanks for reaching us and great to see you start contributing. Can I ask you which command are you executing to get this error?
Anyway, I think that the error is generated from the missing `virtcl` command in your local environment.
If you run `make test` it should not be fired, since the `dockerized` environment install `virtctl`.
Please let me know.
Thank you!
