### ISSUE TITLE
boot-menu example in doc

### ISSUE THREAD

**Issue by coxifred** [kubevirt/kubevirt#11346]
**Description**:

Can't find any examples/doc for boot-menu, need help.

**What you expected**:
When the PR is done with new parametees, update the doc.

**Additional context**:

PR : [#10106][acardace] Add boot-menu wait time when starting the VM as paused.

**Comment by jean-edouard** [comment]
I believe @acardace is referring to the BIOS/UEFI settings screen.
It can usually be accessed by pressing some key (DEL/ESC/...) as soon as the VM start. I believe the PR your are referring to adds an option to give more time to press the key(s).

**Comment by coxifred** [comment]
> I believe @acardace is referring to the BIOS/UEFI settings screen. It can usually be accessed by pressing some key (DEL/ESC/...) as soon as the VM start. I believe the PR your are referring to adds an option to give more time to press the key(s).

Yes its exactly that, i need more time to customize the grub line.
My os is booting too quickly.

**Comment by xpivarc** [comment]
@acardace Would you have time to write small user facing doc?
