### ISSUE TITLE
Where is the corresponding relationship between kubevirt and qume versions?

### ISSUE THREAD

**Issue by CharlesQQ** [kubevirt/kubevirt#11365]
**Description**:

User want to know corresponding relationship between kubevirt and qume versions

**What you expected**:
A clear and concise description of what you expected.

**URL**:
Provide a link to the documentation.

**Additional context**:
Add any other context about the issue here.

**Comment by victortoso** [comment]
Hi,

I did this fish script
```fish
#!/usr/bin/fish
set hackfile "hack/rpm-deps.sh"
set pattern "s/.*:(.*-[^\.]*).*/\1/p"

echo "| tag | qemu | libvirt |"
echo "| :-:| :-: | :-: |"

for tag in (git dated-tag | cut -d' ' -f3)
    git cat-file -e $tag:$hackfile 2> /dev/null
    if test $status -ne 0
        continue
    end
    set qemu (git show $tag:$hackfile | grep -i qemu_version= | sed -E $pattern)
    set libvirt (git show $tag:$hackfile | grep -i libvirt_version= | sed -E $pattern)
    if not string length --quiet $qemu
        continue
    end
    echo "| $tag | $qemu | $libvirt |"
end
```

where `git dated-tag` alias is
```
dated-tag = for-each-ref --sort=*committerdate refs/tags/ --format='%(*committerdate:short)%(committerdate:short)  %(refname:short)'
```

and the result is

| tag | qemu | libvirt |
| :-:| :-: | :-: |
| v0.43.1-rc.1 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.43.1-rc.2 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.38.0 | 5.1.0-18 5.1.0-18 | 6.6.0-13 6.6.0-13 |
| v0.38.0-rc.0 | 5.1.0-18 5.1.0-18 | 6.6.0-13 6.6.0-13 |
| v0.38.0-rc.1 | 5.1.0-18 5.1.0-18 | 6.6.0-13 6.6.0-13 |
| v0.38.1 | 5.1.0-18 5.1.0-18 | 6.6.0-13 6.6.0-13 |
| v0.39.0-rc.0 | 5.1.0-18 5.1.0-18 | 6.6.0-13 6.6.0-13 |
| v0.39.0 | 5.1.0-18 5.1.0-18 | 6.6.0-13 6.6.0-13 |
| v0.39.0-rc.1 | 5.1.0-18 5.1.0-18 | 6.6.0-13 6.6.0-13 |
| v0.39.1 | 5.1.0-18 5.1.0-18 | 6.6.0-13 6.6.0-13 |
| v0.40.0-rc.0 | 5.1.0-18 5.1.0-18 | 6.6.0-13 6.6.0-13 |
| v0.40.0-rc.1 | 5.1.0-18 5.1.0-18 | 6.6.0-13 6.6.0-13 |
| v0.40.0 | 5.1.0-18 5.1.0-18 | 6.6.0-13 6.6.0-13 |
| v0.40.0-rc.2 | 5.1.0-18 5.1.0-18 | 6.6.0-13 6.6.0-13 |
| v0.41.0-rc.0 | 5.1.0-18 5.1.0-18 | 6.6.0-13 6.6.0-13 |
| v0.41.0 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.41.0-rc.1 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.42.0 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.42.0-rc.0 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.42.1 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.41.1 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.43.0-rc.0 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.43.0 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.43.0-rc.1 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.41.2 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.44.0 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.44.0-rc.0 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.41.3 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.44.1 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.45.0 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.45.0-rc.0 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.46.0 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.46.0-rc.0 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.44.2 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.44.3 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.46.1 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.42.2 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.43.1 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.41.4 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.45.1 | 5.2.0-15 5.2.0-15 | 7.0.0-12 7.0.0-12 |
| v0.38.2 | 5.1.0-18 5.1.0-18 | 6.6.0-13 6.6.0-13 |
| v0.40.1 | 5.1.0-18 5.1.0-18 | 6.6.0-13 6.6.0-13 |
| v0.39.2 | 5.1.0-18 5.1.0-18 | 6.6.0-13 6.6.0-13 |
| v0.47.0 | 6.0.0-33 6.0.0-33 | 7.6.0-4 7.6.0-4 |
| v0.47.0-rc.0 | 6.0.0-33 6.0.0-33 | 7.6.0-4 7.6.0-4 |
| v0.47.1 | 6.0.0-33 6.0.0-33 | 7.6.0-4 7.6.0-4 |
| v0.48.0 | 6.0.0-33 6.0.0-33 | 7.6.0-6 7.6.0-6 |
| v0.48.0-rc.0 | 6.0.0-33 6.0.0-33 | 7.6.0-6 7.6.0-6 |
| v0.48.1 | 6.0.0-33 6.0.0-33 | 7.6.0-6 7.6.0-6 |
| v0.49.0 | 6.0.0-33 6.0.0-33 | 7.6.0-6 7.6.0-6 |
| v0.49.0-rc.0 | 6.0.0-33 6.0.0-33 | 7.6.0-6 7.6.0-6 |
| v0.50.0 | 6.0.0-33 6.0.0-33 | 7.6.0-6 7.6.0-6 |
| v0.50.0-rc.0 | 6.0.0-33 6.0.0-33 | 7.6.0-6 7.6.0-6 |
| v0.51.0 | 6.0.0-33 6.0.0-33 | 7.6.0-6 7.6.0-6 |
| v0.51.0-rc.0 | 6.0.0-33 6.0.0-33 | 7.6.0-6 7.6.0-6 |
| v0.52.0 | 6.0.0-33 6.0.0-33 | 7.6.0-6 7.6.0-6 |
| v0.52.0-rc.0 | 6.0.0-33 6.0.0-33 | 7.6.0-6 7.6.0-6 |
| v0.53.0 | 6.2.0-5 6.2.0-5 | 8.0.0-2 8.0.0-2 |
| v0.53.0-rc.0 | 6.2.0-5 6.2.0-5 | 8.0.0-2 8.0.0-2 |
| v0.53.1 | 6.2.0-5 6.2.0-5 | 8.0.0-2 8.0.0-2 |
| v0.54.0 | 6.2.0-5 6.2.0-5 | 8.0.0-2 8.0.0-2 |
| v0.54.0-rc.0 | 6.2.0-5 6.2.0-5 | 8.0.0-2 8.0.0-2 |
| v0.53.2 | 6.2.0-5 6.2.0-5 | 8.0.0-2 8.0.0-2 |
| v0.55.0 | 6.2.0-5 6.2.0-5 | 8.0.0-2 8.0.0-2 |
| v0.55.0-rc.0 | 6.2.0-5 6.2.0-5 | 8.0.0-2 8.0.0-2 |
| v0.56.0-rc.0 | 6.2.0-5 6.2.0-5 | 8.0.0-2 8.0.0-2 |
| v0.55.1 | 6.2.0-5 6.2.0-5 | 8.0.0-2 8.0.0-2 |
| v0.56.0 | 6.2.0-5 6.2.0-5 | 8.0.0-2 8.0.0-2 |
| v0.56.0-rc.1 | 6.2.0-5 6.2.0-5 | 8.0.0-2 8.0.0-2 |
| v0.49.1 | 6.0.0-33 6.0.0-33 | 7.6.0-6 7.6.0-6 |
| v0.57.0 | 6.2.0-5 6.2.0-5 | 8.0.0-2 8.0.0-2 |
| v0.57.0-rc.0 | 6.2.0-5 6.2.0-5 | 8.0.0-2 8.0.0-2 |
| v0.56.1 | 6.2.0-5 6.2.0-5 | 8.0.0-2 8.0.0-2 |
| v0.57.1 | 6.2.0-5 6.2.0-5 | 8.0.0-2 8.0.0-2 |
| v0.55.2 | 6.2.0-5 6.2.0-5 | 8.0.0-2 8.0.0-2 |
| v0.58.0 | 6.2.0-5 6.2.0-5 | 8.0.0-2 8.0.0-2 |
| v0.58.0-rc.0 | 6.2.0-5 6.2.0-5 | 8.0.0-2 8.0.0-2 |
| v0.59.0-alpha.0 | 7.1.0-3 7.1.0-3 | 8.7.0-1 8.7.0-1 |
| v0.59.0-alpha.1 | 7.1.0-3 7.1.0-3 | 8.7.0-1 8.7.0-1 |
| v0.59.0-alpha.2 | 7.1.0-3 7.1.0-3 | 8.7.0-1 8.7.0-1 |
| v0.59.0-rc.0 | 7.1.0-6 7.1.0-6 | 8.10.0-2 8.10.0-2 |
| v0.59.0-rc.1 | 7.1.0-6 7.1.0-6 | 8.10.0-2 8.10.0-2 |
| v0.58.1 | 6.2.0-5 6.2.0-5 | 8.0.0-2 8.0.0-2 |
| v0.59.0 | 7.2.0-6 7.2.0-6 | 9.0.0-3 9.0.0-3 |
| v0.59.0-rc.2 | 7.2.0-6 7.2.0-6 | 9.0.0-3 9.0.0-3 |
| v0.60.0-alpha.0 | 7.2.0-6 7.2.0-6 | 9.0.0-3 9.0.0-3 |
| v1.0.0-alpha.0 | 7.2.0-14 7.2.0-14 | 9.0.0-3 9.0.0-3 |
| v1.0.0-beta.0 | 7.2.0-14 7.2.0-14 | 9.0.0-3 9.0.0-3 |
| v0.58.2 | 6.2.0-5 6.2.0-5 | 8.0.0-2 8.0.0-2 |
| v0.59.1 | 7.2.0-6 7.2.0-6 | 9.0.0-3 9.0.0-3 |
| v1.0.0-rc.0 | 7.2.0-14 7.2.0-14 | 9.0.0-3 9.0.0-3 |
| v0.59.2 | 7.2.0-6 7.2.0-6 | 9.0.0-3 9.0.0-3 |
| v1.0.0 | 7.2.0-14 7.2.0-14 | 9.0.0-3 9.0.0-3 |
| v1.0.0-rc.1 | 7.2.0-14 7.2.0-14 | 9.0.0-3 9.0.0-3 |
| v1.1.0-alpha.0 | 8.0.0-13 8.0.0-13 | 9.5.0-6 9.5.0-6 |
| v1.0.1 | 7.2.0-14 7.2.0-14 | 9.0.0-3 9.0.0-3 |
| v1.1.0-rc.0 | 8.0.0-13 8.0.0-13 | 9.5.0-6 9.5.0-6 |
| tags/v1.1.0 | 8.0.0-13 8.0.0-13 | 9.5.0-6 9.5.0-6 |
| v1.1.0-rc.1 | 8.0.0-13 8.0.0-13 | 9.5.0-6 9.5.0-6 |
| v1.1.1 | 8.0.0-13 8.0.0-13 | 9.5.0-6 9.5.0-6 |
| v1.2.0-alpha.0 | 8.0.0-13 8.0.0-13 | 9.5.0-6 9.5.0-6 |
| v1.2.0-beta.0 | 8.0.0-13 8.0.0-13 | 9.5.0-6 9.5.0-6 |
| v1.2.0-rc.0 | 8.0.0-13 8.0.0-13 | 9.5.0-6 9.5.0-6 |
| v1.2.0-rc.1 | 8.0.0-13 8.0.0-13 | 9.5.0-6 9.5.0-6 |

If that's enough for you, feel free to close the issue ;)

**Comment by victortoso** [comment]
Fixed the typo in the sed pattern, not double anymore.
Cheers
