### ISSUE TITLE
Display opt-out

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1136]
As a user I want to be able to opt out of having a display for my VM.
Mainly to save memory oevrhead which can be dedicated to the instead.

Notes
- This is about disabling to attach any graphical device.

API

```yaml
TBD
```

**Comment by fabiand** [comment]
We still need to sort out how the API should look.

**Comment by fromanirh** [comment]
Hey, I think this issue is solved by https://github.com/kubevirt/kubevirt/pull/1364 - or do we need something more?
