### ISSUE TITLE
Node selector for virt-api

### ISSUE THREAD

**Issue by mohammadkarami2023** [kubevirt/kubevirt#11369]
i can easily set node selector for virt-operator in its yaml file. My problem is that i couldn't do that for other components like virt-api. Could you please help me?

**Comment by matthewei** [comment]
virt-api is managed by virt-operator. I you can found how to change the node for virt-api from https://kubevirt.io/user-guide/operations/installation/
![image](https://github.com/kubevirt/kubevirt/assets/86186853/1b8a8d62-2773-4b5b-a424-a00ef0f8f255)

**Comment by xpivarc** [comment]
/close 
The provided solution should work. Reopen if this does not work
