### ISSUE TITLE
The functions of each subcommand of Makefile are not very clear to new

### ISSUE THREAD

**Issue by Longchuanzheng** [kubevirt/kubevirt#11376]
**Description**:
I am a little puzzeld about each subcommand in Makefile. 
**What you expected**:
Although we can look at the specific scripts file in /hack, while it would be better if we could add some comments in the Makefile or write some documents to guide just like how to compile and how to update dependencies...

**URL**:
Provide a link to the documentation.

**Additional context**:
Add any other context about the issue here.

**Comment by aburdenthehand** [comment]
Hello @Longchuanzheng - we talked about this in the Community Meeting yesterday. In case you haven't seen it, we have some of the common usage documented in our developer getting started guide: https://github.com/kubevirt/kubevirt/blob/main/docs/getting-started.md

From the conversation, it is unlikely anyone will have the bandwidth to document everything, as many or the regular contributors prefer to read the scripts. That said, no one is opposed to documentation and if you or anyone else would find it useful then contributions are welcome!
Were there some subcommands in particular that you were interested in learning more about?

**Comment by Longchuanzheng** [comment]
Hi @aburdenthehand , thank you for your enthusiasm. I hadn't noticed that started guide before. It is realy useful if I try to do some thing on kubevirt first time.
I closed this issue because I think that explaining a Makefile command clearly with a few words is challenging.It would be more appropriate to introduce command in user guide(when should we use which command) just like you mentiond https://github.com/kubevirt/kubevirt/blob/main/docs/getting-started.md, also like  https://github.com/kubevirt/kubevirt/blob/main/docs/update-go-version.md which was shared with me by others yesterday.
By the way, I still interested in command like ‘distclean’, when should we use this command?
