### ISSUE TITLE
make builder-build failed with go: command not found

### ISSUE THREAD

**Issue by Longchuanzheng** [kubevirt/kubevirt#11386]
**What happened**:
When I try to bump golang version refer to this doc: https://github.com/kubevirt/kubevirt/blob/main/docs/update-go-version.md
I change  GIMME_GO_VERSION in hack/builder/Dockerfile and exec `make builder-build`. 
It return 
```
=> ERROR [ 8/17] RUN set -x &&     mkdir -p /go &&     source /etc/profile.d/gimme.sh &&     go install -v golang.org/x/tools/cmd/goimports@d5fe738 &&     go install -v mvdan.cc/sh/v3/cmd/shfmt@v3.1.  0.4s
------
 > [ 8/17] RUN set -x &&     mkdir -p /go &&     source /etc/profile.d/gimme.sh &&     go install -v golang.org/x/tools/cmd/goimports@d5fe738 &&     go install -v mvdan.cc/sh/v3/cmd/shfmt@v3.1.1 &&     go install -v k8s.io/code-generator/cmd/deepcopy-gen@v0.20.2 &&     go install -v k8s.io/code-generator/cmd/defaulter-gen@v0.20.2  &&     go install -v k8s.io/kube-openapi/cmd/openapi-gen@30be4d1 &&     go install -v github.com/golang/protobuf/protoc-gen-go@1643683 &&     go install -v k8s.io/code-generator/cmd/client-gen@v0.20.2 &&     go install -v github.com/securego/gosec/v2/cmd/gosec@0ce48a5 &&     go install -v sigs.k8s.io/controller-tools/cmd/controller-gen@v0.4.0 &&     go clean -cache -modcache:
#0 0.312 + mkdir -p /go
#0 0.315 + source /etc/profile.d/gimme.sh
#0 0.315 + go install -v golang.org/x/tools/cmd/goimports@d5fe738
#0 0.316 /bin/sh: line 1: go: command not found
```

**What you expected to happen**:
`make builder-build` run without err

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:
![image](https://github.com/kubevirt/kubevirt/assets/49519342/4464c34f-3a46-4f33-8055-5fcde80365f3)

**Environment**:
- KubeVirt version (use `virtctl version`): 0.59
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by Longchuanzheng** [comment]
IMO, it means golang haven't installed in base image. How can I do?

**Comment by brianmcarey** [comment]
@Longchuanzheng - what did you change `GIMME_GO_VERSION` to ?

**Comment by Longchuanzheng** [comment]
@brianmcarey Hi, thanks for your attention. I just  refer your pr (https://github.com/kubevirt/kubevirt/pull/10914) and change `GIMME_GO_VERSION` to 1.21.5

**Comment by brianmcarey** [comment]
I changed the following against the `release-0.59` branch and `make builder-build` completed succesfully.
```diff
--- a/hack/builder/Dockerfile
+++ b/hack/builder/Dockerfile
@@ -4,7 +4,7 @@ ARG SONOBUOY_ARCH
 ARG BAZEL_ARCH
 
 ENV BAZEL_VERSION=5.3.1
-ENV GIMME_GO_VERSION=1.19.12
+ENV GIMME_GO_VERSION=1.21.5
 ENV GRADLE_VERSION=6.6
 ENV OPERATOR_COURIER_VERSION=2.1.11
 ENV SONOBUOY_VERSION=0.56.9
```

**Comment by Longchuanzheng** [comment]
Hi, thanks for your assertion. I suspect it is a problem with the base image. I didn't find process in Dockerfile to install golang. While there dosen't have golang in the base image.  
```
# docker run -i quay.io/centos/centos:stream9  /bin/bash
go version
/bin/bash: line 1: go: command not found
```
So it is reasonable to build image failed.

Can you share me which base image dose you use? just like sha256 or tag.

**Comment by brianmcarey** [comment]
The installation of go is handled by `/etc/profile/gimme.sh` which is from here - https://github.com/kubevirt/kubevirt/blob/b3a75fa2d670c540ad2b93f037cc3a71977a2b79/hack/builder/Dockerfile#L71C5-L71C66

Please double check you have the `GIMME_GO_VERSION` variable correctly set - as in no spaces etc.

**Comment by Longchuanzheng** [comment]
Thanks, I set `GIMME_GO_VERSION` like this:
```
diff --git a/hack/builder/Dockerfile b/hack/builder/Dockerfile
index aaf6dcdd8..af07e8226 100644
--- a/hack/builder/Dockerfile
+++ b/hack/builder/Dockerfile
@@ -4,7 +4,7 @@ ARG SONOBUOY_ARCH
 ARG BAZEL_ARCH

 ENV BAZEL_VERSION=5.3.1
-ENV GIMME_GO_VERSION=1.19.2
+ENV GIMME_GO_VERSION=1.21.5
 ENV GRADLE_VERSION=6.6
 ENV OPERATOR_COURIER_VERSION=2.1.11
 ENV SONOBUOY_VERSION=0.56.9
```

**Comment by brianmcarey** [comment]
Ok then I would check the contents of `/etc/profile.d/gimme.sh` during your image build. It may not have downloaded the script correctly.

**Comment by Longchuanzheng** [comment]
We can just download https://raw.githubusercontent.com/travis-ci/gimme/master/gimme  and save it at hack/builder.
And use 
```
COPY gimme /etc/gimme

RUN set -x && \
    bash /etc/gimme >> /etc/profile.d/gimme.sh
```
Instead use crul in Dockerfile.

**Comment by Longchuanzheng** [comment]
@brianmcarey  Hi, what should I do when I generate the builder image?
I follow the https://github.com/kubevirt/kubevirt/blob/main/docs/update-go-version.md.
I use go rules for bazel in https://github.com/kubevirt/kubevirt/pull/8622
```
http_archive(
   name = "io_bazel_rules_go",
    sha256 = "099a9fb96a376ccbbb7d291ed4ecbdfd42f6bc822ab77ae6f1b5cb9e914e94fa",
    urls = [
        "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.35.0/rules_go-v0.35.0.zip",
        "https://github.com/bazelbuild/rules_go/releases/download/v0.35.0/rules_go-v0.35.0.zip",
        "https://storage.googleapis.com/builddeps/099a9fb96a376ccbbb7d291ed4ecbdfd42f6bc822ab77ae6f1b5cb9e914e94fa",
    ],
)
```

After above, I try to `make deps-update` but get err.
![image](https://github.com/kubevirt/kubevirt/assets/49519342/b1c50ceb-2264-4a16-bf9a-4f57d415276e)

**Comment by brianmcarey** [comment]
> @brianmcarey Hi, what should I do when I generate the builder image? I follow the https://github.com/kubevirt/kubevirt/blob/main/docs/update-go-version.md. I use go rules for bazel in #8622
> 
> ```
> http_archive(
>    name = "io_bazel_rules_go",
>     sha256 = "099a9fb96a376ccbbb7d291ed4ecbdfd42f6bc822ab77ae6f1b5cb9e914e94fa",
>     urls = [
>         "https://mirror.bazel.build/github.com/bazelbuild/rules_go/releases/download/v0.35.0/rules_go-v0.35.0.zip",
>         "https://github.com/bazelbuild/rules_go/releases/download/v0.35.0/rules_go-v0.35.0.zip",
>         "https://storage.googleapis.com/builddeps/099a9fb96a376ccbbb7d291ed4ecbdfd42f6bc822ab77ae6f1b5cb9e914e94fa",
>     ],
> )
> ```
> 
> After above, I try to `make deps-update` but get err. 

You will probably need to backport changes from the following PRs to get this working: 
https://github.com/kubevirt/kubevirt/pull/10879
https://github.com/kubevirt/kubevirt/pull/10914

**Comment by Longchuanzheng** [comment]
@brianmcarey thanks, I build image and `make deps-update` succeeded. While I do `make generate` failed.
err is:
```
You introduced new API rule violation
```
![image](https://github.com/kubevirt/kubevirt/assets/49519342/ed853a4d-3fb0-446f-a9f2-a8adaa432128)
I think this err is in hack/generate.sh
```
if cmp ${KUBEVIRT_DIR}/api/api-rule-violations.list ${KUBEVIRT_DIR}/api/api-rule-violations-known.list; then
    echo "openapi generated"
else
    diff -u ${KUBEVIRT_DIR}/api/api-rule-violations-known.list ${KUBEVIRT_DIR}/api/api-rule-violations.list || true
    echo "You introduced new API rule violation"
    diff ${KUBEVIRT_DIR}/api/api-rule-violations.list ${KUBEVIRT_DIR}/api/api-rule-violations-known.list
    exit 2
fi
```
I try to 
``` 
rm api/api-rule-violations-known.list
cp api/api-rule-violations.list api/api-rule-violations-known.list
```
and exec `diff -u api/api-rule-violations-known.list api/api-rule-violations.list` locally without diff.
![image](https://github.com/kubevirt/kubevirt/assets/49519342/84863c69-0182-46e6-b69d-e7135c274ce7)
While I still `make generate` failed with `You introduced new API rule violation`.
I think this may related to https://github.com/kubevirt/kubevirt/issues/9780 
@lyarwood , Hi, can you help me?

**Comment by brianmcarey** [comment]
@Longchuanzheng I am not sure what may be causing this. Just so you know since the release v1.2 - KubeVirt is no longer supporting v0.59. 
https://github.com/kubevirt/sig-release/blob/main/releases/k8s-support-matrix.md
