### ISSUE TITLE
create vm virt-launcher error: guest-console-log and volumecontainerdisk container error

### ISSUE THREAD

**Issue by mansoncui** [kubevirt/kubevirt#11390]
**Environment**:
- KubeVirt version (use `virtctl version`): v1.1.1
- Kubernetes version (use `kubectl version`): v1.23.6 (k8s+containerd+calico)
- VM or VMI specifications: 
- ---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-fedora
  name: vm-fedora
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-fedora
    spec:
      domain:
        resources:
          requests:
            memory: 1Gi
        devices:
          disks:
          - name: containerdisk
            disk:
              bus: virtio
      volumes:
      - name: containerdisk
        containerDisk:
          image: quay.io/kubevirt/cirros-container-disk-demo
          imagePullPolicy: IfNotPresent

- Cloud provider or hardware configuration:  Binary deployment of physical machines in computer rooms
- OS (e.g. from /etc/os-release): ubuntu 18.04
virt-launcher Error Information:
{"component":"virt-launcher-monitor","level":"error","msg":"could not create up serial console term file: /var/run/kubevirt-private/fb3e4db7-dd68-4b07-8449-c285d566156b/virt-serial0-log-sigTerm","pos":"virt-launcher-monitor.go:72","reason":"open /var/run/kubevirt-private/fb3e4db7-dd68-4b07-8449-c285d566156b/virt-serial0-log-sigTerm: no such file or directory","timestamp":"2024-03-01T03:06:44.569093Z"}
{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:86","timestamp":"2024-03-01T03:06:44.619135Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:89","timestamp":"2024-03-01T03:06:44.619215Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:563","timestamp":"2024-03-01T03:06:44.619591Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory')","pos":"libvirt.go:571","timestamp":"2024-03-01T03:06:44.620127Z"}
{"component":"virt-launcher","level":"info","msg":"libvirt version: 9.5.0, package: 6.el9 (builder@centos.org, 2023-08-25-08:53:56, )","subcomponent":"libvirt","thread":"44","timestamp":"2024-03-01T03:06:44.638000Z"}
{"component":"virt-launcher","level":"info","msg":"hostname: vm-fedora","subcomponent":"libvirt","thread":"44","timestamp":"2024-03-01T03:06:44.638000Z"}
{"component":"virt-launcher","level":"error","msg":"Unable to open /dev/kvm: Permission denied","pos":"virHostCPUGetCPUID:1422","subcomponent":"libvirt","thread":"44","timestamp":"2024-03-01T03:06:44.638000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get session bus connection: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory","pos":"virGDBusGetSessionBus:126","subcomponent":"libvirt","thread":"44","timestamp":"2024-03-01T03:06:44.638000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get system bus connection: Could not connect: No such file or directory","pos":"virGDBusGetSystemBus:99","subcomponent":"libvirt","thread":"44","timestamp":"2024-03-01T03:06:44.638000Z"}
{"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:579","timestamp":"2024-03-01T03:06:45.122293Z"}
{"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:562","timestamp":"2024-03-01T03:06:45.124990Z"}
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:75","timestamp":"2024-03-01T03:06:45.125185Z"}
{"component":"virt-launcher","level":"info","msg":"Received signal terminated","pos":"virt-launcher.go:474","timestamp":"2024-03-01T03:06:48.502544Z"}
{"component":"virt-launcher","level":"info","msg":"stopping cmd server","pos":"server.go:611","timestamp":"2024-03-01T03:06:48.502627Z"}
{"component":"virt-launcher","level":"info","msg":"cmd server stopped","pos":"server.go:620","timestamp":"2024-03-01T03:06:48.502811Z"}
{"component":"virt-launcher","level":"info","msg":"Exiting...","pos":"virt-launcher.go:510","timestamp":"2024-03-01T03:06:48.502853Z"}
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 13 with status 0","pos":"virt-launcher-monitor.go:192","timestamp":"2024-03-01T03:06:48.505408Z"}
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 27 with status 9","pos":"virt-launcher-monitor.go:192","timestamp":"2024-03-01T03:06:48.505551Z"}
{"component":"virt-launcher-monitor","level":"error","msg":"failed to open file /var/run/kubevirt/passt.log","pos":"virt-launcher-monitor.go:421","reason":"open /var/run/kubevirt/passt.log: no such file or directory","timestamp":"2024-03-01T03:06:48.505562Z"}

virt-handler  Error Information: 
{"component":"virt-handler","level":"info","msg":"Collecting VM metrics from 0 sources","pos":"collector.go:59","timestamp":"2024-03-01T03:10:31.277218Z"}
{"component":"virt-handler","level":"info","msg":"Collection successful","pos":"collector.go:84","timestamp":"2024-03-01T03:10:31.277283Z"}
{"component":"virt-handler","level":"info","msg":"Processing event default/vm-fedora","pos":"vm.go:1892","timestamp":"2024-03-01T03:10:33.185931Z"}
{"component":"virt-handler","level":"info","msg":"VMI does not exist | Domain does not exist","pos":"vm.go:1902","timestamp":"2024-03-01T03:10:33.185980Z"}
{"component":"virt-handler","kind":"VirtualMachineInstance","level":"info","msg":"Processing local ephemeral data cleanup for shutdown domain.","name":"vm-fedora","namespace":"default","pos":"vm.go:2029","timestamp":"2024-03-01T03:10:33.186021Z","uid":""}
{"component":"virt-handler","kind":"VirtualMachineInstance","level":"info","msg":"Performing final local cleanup for vmi with uid ","name":"vm-fedora","namespace":"default","pos":"vm.go:2161","timestamp":"2024-03-01T03:10:33.186060Z","uid":""}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Removing domain from cache during final cleanup","name":"vm-fedora","namespace":"default","pos":"vm.go:2201","timestamp":"2024-03-01T03:10:33.186109Z","uid":""}
{"component":"virt-handler","kind":"VirtualMachineInstance","level":"info","msg":"Synchronization loop succeeded.","name":"vm-fedora","namespace":"default","pos":"vm.go:2059","timestamp":"2024-03-01T03:10:33.186134Z","uid":""}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: resourceName: kvm","pos":"generic_device.go:237","timestamp":"2024-03-01T03:10:37.236536Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: request: [&ContainerAllocateRequest{DevicesIDs:[kvm262],}]","pos":"generic_device.go:238","timestamp":"2024-03-01T03:10:37.236597Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: resourceName: tun","pos":"generic_device.go:237","timestamp":"2024-03-01T03:10:37.237773Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: request: [&ContainerAllocateRequest{DevicesIDs:[tun97],}]","pos":"generic_device.go:238","timestamp":"2024-03-01T03:10:37.237810Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: resourceName: vhost-net","pos":"generic_device.go:237","timestamp":"2024-03-01T03:10:37.238995Z"}
{"component":"virt-handler","level":"info","msg":"Generic Allocate: request: [&ContainerAllocateRequest{DevicesIDs:[vhost-net947],}]","pos":"generic_device.go:238","timestamp":"2024-03-01T03:10:37.239042Z"}
{"component":"virt-handler","level":"info","msg":"Processing event default/vm-fedora","pos":"vm.go:1892","timestamp":"2024-03-01T03:10:41.193652Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled | Domain does not exist","name":"vm-fedora","namespace":"default","pos":"vm.go:1897","timestamp":"2024-03-01T03:10:41.193710Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","kind":"","level":"info","msg":"No update processing required","name":"vm-fedora","namespace":"default","pos":"vm.go:2035","timestamp":"2024-03-01T03:10:41.193804Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","kind":"","level":"info","msg":"migration is block migration because of containerdisk volume","name":"vm-fedora","namespace":"default","pos":"vm.go:2573","timestamp":"2024-03-01T03:10:41.220207Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","level":"error","msg":"cannot compute checksums as containerdisk/kernelboot containers seem to have been terminated","pos":"vm.go:951","timestamp":"2024-03-01T03:10:41.220284Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"Synchronization loop succeeded.","name":"vm-fedora","namespace":"default","pos":"vm.go:2059","timestamp":"2024-03-01T03:10:41.234006Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","level":"info","msg":"Processing event default/vm-fedora","pos":"vm.go:1892","timestamp":"2024-03-01T03:10:41.234486Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Failed | Domain does not exist","name":"vm-fedora","namespace":"default","pos":"vm.go:1897","timestamp":"2024-03-01T03:10:41.234520Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","kind":"","level":"info","msg":"Cleaning up local data for finalized vmi.","name":"vm-fedora","namespace":"default","pos":"vm.go:1966","timestamp":"2024-03-01T03:10:41.234563Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","kind":"","level":"info","msg":"Processing local ephemeral data cleanup for shutdown domain.","name":"vm-fedora","namespace":"default","pos":"vm.go:2029","timestamp":"2024-03-01T03:10:41.234595Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","kind":"","level":"info","msg":"Performing final local cleanup for vmi with uid e8029c52-eed7-4769-9186-7afb30e63138","name":"vm-fedora","namespace":"default","pos":"vm.go:2161","timestamp":"2024-03-01T03:10:41.234630Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","kind":"","level":"info","msg":"No container disk mount entries found to unmount","name":"vm-fedora","namespace":"default","pos":"mount.go:361","timestamp":"2024-03-01T03:10:41.234673Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","kind":"","level":"info","msg":"Cleaning up remaining hotplug volumes","name":"vm-fedora","namespace":"default","pos":"mount.go:752","timestamp":"2024-03-01T03:10:41.234717Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","level":"info","msg":"Remove watchdog file /var/run/kubevirt/watchdog-files/default_vm-fedora","pos":"watchdog.go:68","timestamp":"2024-03-01T03:10:41.234766Z"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Removing domain from cache during final cleanup","name":"vm-fedora","namespace":"default","pos":"vm.go:2201","timestamp":"2024-03-01T03:10:41.234796Z","uid":""}
{"component":"virt-handler","kind":"","level":"info","msg":"Synchronization loop succeeded.","name":"vm-fedora","namespace":"default","pos":"vm.go:2059","timestamp":"2024-03-01T03:10:41.234819Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","level":"info","msg":"Processing event default/vm-fedora","pos":"vm.go:1892","timestamp":"2024-03-01T03:10:41.241923Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Failed | Domain does not exist","name":"vm-fedora","namespace":"default","pos":"vm.go:1897","timestamp":"2024-03-01T03:10:41.241955Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","kind":"","level":"info","msg":"Cleaning up local data for finalized vmi.","name":"vm-fedora","namespace":"default","pos":"vm.go:1966","timestamp":"2024-03-01T03:10:41.241991Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","kind":"","level":"info","msg":"Processing local ephemeral data cleanup for shutdown domain.","name":"vm-fedora","namespace":"default","pos":"vm.go:2029","timestamp":"2024-03-01T03:10:41.242026Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","kind":"","level":"info","msg":"Performing final local cleanup for vmi with uid e8029c52-eed7-4769-9186-7afb30e63138","name":"vm-fedora","namespace":"default","pos":"vm.go:2161","timestamp":"2024-03-01T03:10:41.242059Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","kind":"","level":"info","msg":"No container disk mount entries found to unmount","name":"vm-fedora","namespace":"default","pos":"mount.go:361","timestamp":"2024-03-01T03:10:41.242095Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","kind":"","level":"info","msg":"Cleaning up remaining hotplug volumes","name":"vm-fedora","namespace":"default","pos":"mount.go:752","timestamp":"2024-03-01T03:10:41.242136Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","level":"info","msg":"Remove watchdog file /var/run/kubevirt/watchdog-files/default_vm-fedora","pos":"watchdog.go:68","timestamp":"2024-03-01T03:10:41.242179Z"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Removing domain from cache during final cleanup","name":"vm-fedora","namespace":"default","pos":"vm.go:2201","timestamp":"2024-03-01T03:10:41.242207Z","uid":""}
{"component":"virt-handler","kind":"","level":"info","msg":"Synchronization loop succeeded.","name":"vm-fedora","namespace":"default","pos":"vm.go:2059","timestamp":"2024-03-01T03:10:41.242230Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","level":"info","msg":"Processing event default/vm-fedora","pos":"vm.go:1892","timestamp":"2024-03-01T03:10:41.263778Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Failed | Domain does not exist","name":"vm-fedora","namespace":"default","pos":"vm.go:1897","timestamp":"2024-03-01T03:10:41.263821Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","kind":"","level":"info","msg":"Cleaning up local data for finalized vmi.","name":"vm-fedora","namespace":"default","pos":"vm.go:1966","timestamp":"2024-03-01T03:10:41.263875Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","kind":"","level":"info","msg":"Processing local ephemeral data cleanup for shutdown domain.","name":"vm-fedora","namespace":"default","pos":"vm.go:2029","timestamp":"2024-03-01T03:10:41.263907Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","kind":"","level":"info","msg":"Performing final local cleanup for vmi with uid e8029c52-eed7-4769-9186-7afb30e63138","name":"vm-fedora","namespace":"default","pos":"vm.go:2161","timestamp":"2024-03-01T03:10:41.263941Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","kind":"","level":"info","msg":"No container disk mount entries found to unmount","name":"vm-fedora","namespace":"default","pos":"mount.go:361","timestamp":"2024-03-01T03:10:41.263983Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","kind":"","level":"info","msg":"Cleaning up remaining hotplug volumes","name":"vm-fedora","namespace":"default","pos":"mount.go:752","timestamp":"2024-03-01T03:10:41.264030Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","level":"info","msg":"Remove watchdog file /var/run/kubevirt/watchdog-files/default_vm-fedora","pos":"watchdog.go:68","timestamp":"2024-03-01T03:10:41.264074Z"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Removing domain from cache during final cleanup","name":"vm-fedora","namespace":"default","pos":"vm.go:2201","timestamp":"2024-03-01T03:10:41.264102Z","uid":""}
{"component":"virt-handler","kind":"","level":"info","msg":"Synchronization loop succeeded.","name":"vm-fedora","namespace":"default","pos":"vm.go:2059","timestamp":"2024-03-01T03:10:41.264126Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","level":"info","msg":"Collecting VM metrics from 0 sources","pos":"collector.go:59","timestamp":"2024-03-01T03:10:41.277421Z"}
{"component":"virt-handler","level":"info","msg":"Collection successful","pos":"collector.go:84","timestamp":"2024-03-01T03:10:41.277473Z"}
{"component":"virt-handler","level":"info","msg":"Processing event default/vm-fedora","pos":"vm.go:1892","timestamp":"2024-03-01T03:10:41.278296Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Failed | Domain does not exist","name":"vm-fedora","namespace":"default","pos":"vm.go:1897","timestamp":"2024-03-01T03:10:41.278328Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","kind":"","level":"info","msg":"Cleaning up local data for finalized vmi.","name":"vm-fedora","namespace":"default","pos":"vm.go:1966","timestamp":"2024-03-01T03:10:41.278370Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","kind":"","level":"info","msg":"Processing local ephemeral data cleanup for shutdown domain.","name":"vm-fedora","namespace":"default","pos":"vm.go:2029","timestamp":"2024-03-01T03:10:41.278402Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","kind":"","level":"info","msg":"Performing final local cleanup for vmi with uid e8029c52-eed7-4769-9186-7afb30e63138","name":"vm-fedora","namespace":"default","pos":"vm.go:2161","timestamp":"2024-03-01T03:10:41.278443Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","kind":"","level":"info","msg":"No container disk mount entries found to unmount","name":"vm-fedora","namespace":"default","pos":"mount.go:361","timestamp":"2024-03-01T03:10:41.278519Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","kind":"","level":"info","msg":"Cleaning up remaining hotplug volumes","name":"vm-fedora","namespace":"default","pos":"mount.go:752","timestamp":"2024-03-01T03:10:41.278587Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","level":"info","msg":"Remove watchdog file /var/run/kubevirt/watchdog-files/default_vm-fedora","pos":"watchdog.go:68","timestamp":"2024-03-01T03:10:41.278660Z"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Removing domain from cache during final cleanup","name":"vm-fedora","namespace":"default","pos":"vm.go:2201","timestamp":"2024-03-01T03:10:41.278712Z","uid":""}
{"component":"virt-handler","kind":"","level":"info","msg":"Synchronization loop succeeded.","name":"vm-fedora","namespace":"default","pos":"vm.go:2059","timestamp":"2024-03-01T03:10:41.278783Z","uid":"e8029c52-eed7-4769-9186-7afb30e63138"}
{"component":"virt-handler","level":"info","msg":"Collecting VM metrics from 0 sources","pos":"collector.go:59","timestamp":"2024-03-01T03:10:46.277623Z"}
{"component":"virt-handler","level":"info","msg":"Collection successful","pos":"collector.go:84","timestamp":"2024-03-01T03:10:46.277694Z"}
{"component":"virt-handler","level":"info","msg":"Collecting VM metrics from 0 sources","pos":"collector.go:59","timestamp":"2024-03-01T03:10:51.276713Z"}
{"component":"virt-handler","level":"info","msg":"Collection successful","pos":"collector.go:84","timestamp":"2024-03-01T03:10:51.276793Z"}
{"component":"virt-handler","level":"info","msg":"Processing event default/vm-fedora","pos":"vm.go:1892","timestamp":"2024-03-01T03:10:52.255215Z"}
{"component":"virt-handler","level":"info","msg":"VMI does not exist | Domain does not exist","pos":"vm.go:1902","timestamp":"2024-03-01T03:10:52.255257Z"}
{"component":"virt-handler","kind":"VirtualMachineInstance","level":"info","msg":"Processing local ephemeral data cleanup for shutdown domain.","name":"vm-fedora","namespace":"default","pos":"vm.go:2029","timestamp":"2024-03-01T03:10:52.255290Z","uid":""}
{"component":"virt-handler","kind":"VirtualMachineInstance","level":"info","msg":"Performing final local cleanup for vmi with uid ","name":"vm-fedora","namespace":"default","pos":"vm.go:2161","timestamp":"2024-03-01T03:10:52.255336Z","uid":""}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Removing domain from cache during final cleanup","name":"vm-fedora","namespace":"default","pos":"vm.go:2201","timestamp":"2024-03-01T03:10:52.255378Z","uid":""}
{"component":"virt-handler","kind":"VirtualMachineInstance","level":"info","msg":"Synchronization loop succeeded.","name":"vm-fedora","namespace":"default","pos":"vm.go:2059","timestamp":"2024-03-01T03:10:52.255402Z","uid":""}

**Comment by aburdenthehand** [comment]
Hello @mansoncui, thanks for raising a bug. Unfortunately we don't support v1.1 with such an old Kubernetes version - the oldest we support is 1.26. You can see our full support matrix here: https://github.com/kubevirt/sig-release/blob/main/releases/k8s-support-matrix.md

If you encounter this problem with a supported version, please update this bug or raise a new one.

**Comment by harshitgupta1337** [comment]
You can set the per-VMI config `.spec.template.spec.domain.devices.logSerialConsole` to `true`.
https://github.com/kubevirt/kubevirt/blob/3766e045c0157db9bc23cbd2698fd8e2809dea4f/staging/src/kubevirt.io/api/core/v1/schema.go#L470

**Comment by chenxinlong** [comment]
> You can set the per-VMI config `.spec.template.spec.domain.devices.logSerialConsole` to `false`.
> 
> https://github.com/kubevirt/kubevirt/blob/3766e045c0157db9bc23cbd2698fd8e2809dea4f/staging/src/kubevirt.io/api/core/v1/schema.go#L470

Thanks, it works like a charm !
