### ISSUE TITLE
Device plugin registers only 1 device when multiple identical devices share an IOMMU group

### ISSUE THREAD

**Issue by dhruvik7** [kubevirt/kubevirt#11412]
**What happened**:
When multiple identical devices share an IOMMU group, the device plugin is able to recognize these devices but it only registers a single host device and passes through only one. 

**What you expected to happen**:
It should register each device individually and allow you to select how many you want (failing if you select something between 0 and N to obey ACS). Right now it's unworkable because there is no way pass all the devices, it makes you bind all the devices to vfio-pci and then leaves the rest unused.

**How to reproduce it (as minimally and precisely as possible)**:
Find a scenario where you have two identical devices in the same group, such as NVLink bridges. Add the entry to the permittedHostDevices and observe that on the node only 1 capacity will be shown for that device.

**Environment**:
- KubeVirt version (use `virtctl version`): v1.2.0-beta.0
- Kubernetes version (use `kubectl version`): v1.26.5
- VM or VMI specifications: 
- Cloud provider or hardware configuration: Bare metal
- OS (e.g. from /etc/os-release): Ubuntu 22.04.3 LTS
- Kernel (e.g. `uname -a`): 5.15.0-97-generic
- Install tools: N/A
- Others: N/A

**Comment by fabiand** [comment]
cc @vladikr

**Comment by henviso** [comment]
Same problem is discussed in [this other github issue]( https://github.com/kubevirt/kubevirt/issues/7755).

We are wondering how hard it is to fix it, we took the initiative to look into the pci_device class and apparently it is presuming that an iommu group is never used by multiple devices, so it has a map from iommuGroup to a single address.

It looks easy to convert that to a slice of multiple addresses so we are experimenting with the change on this PR:

https://github.com/kubevirt/kubevirt/pull/11606
