### ISSUE TITLE
changes to build-go.sh block building rpms outside of git repo

### ISSUE THREAD

**Issue by sreichar** [kubevirt/kubevirt#1141]
When attempting to build the 0.6.0 release based RPM, a failure is seen since version.sh is using git.

RPM builds can not access external systems.

Version.sh is being called in build-go.sh which appears to have changed since previous release.

**Comment by fabiand** [comment]
@sreichar can you please provide a paste of the error an dthe command you used to trigger it?

**Comment by sreichar** [comment]
Here is a pointer to the scratch build I attempted:

http://download-node-02.eng.bos.redhat.com/brewroot/work/tasks/9063/16679063/build.log


Mock Version: 1.1.16
Mock Version: 1.1.16
ENTER do(['bash', '--login', '-c', 'rpmbuild -bs --target x86_64 --nodeps builddir/build/SPECS/kubevirt.spec'], False, '/mnt/build/mock/cnv-1.1-rhel-7-build-4110699-2545021/root/', None, 86400, True, False, 248, 135, None, logger=<mockbuild.trace_decorator.getLog object at 0xa54cd0>)
Executing command: ['bash', '--login', '-c', 'rpmbuild -bs --target x86_64 --nodeps builddir/build/SPECS/kubevirt.spec']
Building target platforms: x86_64
Building for target x86_64
Wrote: /builddir/build/SRPMS/kubevirt-0.6.0-1.git.0.cf13e2b.src.rpm
Child returncode was: 0
LEAVE do --> 

ENTER do(['bash', '--login', '-c', 'rpmbuild -bb --target x86_64 --nodeps builddir/build/SPECS/kubevirt.spec'], False, '/mnt/build/mock/cnv-1.1-rhel-7-build-4110699-2545021/root/', None, 86400, True, False, 248, 135, None, logger=<mockbuild.trace_decorator.getLog object at 0xa54cd0>)
Executing command: ['bash', '--login', '-c', 'rpmbuild -bb --target x86_64 --nodeps builddir/build/SPECS/kubevirt.spec']
Building target platforms: x86_64
Building for target x86_64
Executing(%prep): /bin/sh -e /var/tmp/rpm-tmp.EqCFg6
+ umask 022
+ cd /builddir/build/BUILD
+ cd /builddir/build/BUILD
+ rm -rf kubevirt-0.6.0
+ /usr/bin/gzip -dc /builddir/build/SOURCES/kubevirt-0.6.0-1.git.0.cf13e2b.tar.gz
+ /usr/bin/tar -xf -
+ STATUS=0
+ '[' 0 -ne 0 ']'
+ cd kubevirt-0.6.0
+ /usr/bin/chmod -Rf a+rX,u+w,g-w,o-w .
+ rm -rf ../go
+ mkdir -p ../go/src/kubevirt.io
+ ln -s /builddir/build/BUILD/kubevirt-0.6.0 ../go/src/kubevirt.io/kubevirt
+ exit 0
Executing(%build): /bin/sh -e /var/tmp/rpm-tmp.2slqIv
+ umask 022
+ cd /builddir/build/BUILD
+ cd kubevirt-0.6.0
+ export GOHOME=/builddir/build/BUILD/go
+ GOHOME=/builddir/build/BUILD/go
+ export GOPATH=/builddir/build/BUILD/go
+ GOPATH=/builddir/build/BUILD/go
+ cd /builddir/build/BUILD/go/src/kubevirt.io/kubevirt
+ ./hack/build-go.sh install cmd/virt-controller cmd/virt-launcher cmd/virt-handler cmd/virtctl cmd/virt-api
find: '/builddir/build/BUILD/go/src/kubevirt.io/kubevirt/_out/cmd': No such file or directory
hack/version.sh: line 103: git: command not found
hack/version.sh: line 103: git: command not found
hack/version.sh: line 103: git: command not found
hack/version.sh: line 103: git: command not found
hack/version.sh: line 103: git: command not found
go install runtime/internal/sys: mkdir /usr/lib/golang/pkg/darwin_amd64: permission denied
error: Bad exit status from /var/tmp/rpm-tmp.2slqIv (%build)
RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.2slqIv (%build)
Child returncode was: 1
EXCEPTION: Command failed. See logs for output.
 # ['bash', '--login', '-c', 'rpmbuild -bb --target x86_64 --nodeps builddir/build/SPECS/kubevirt.spec']
Traceback (most recent call last):
  File "/usr/lib/python2.6/site-packages/mockbuild/trace_decorator.py", line 70, in trace
    result = func(*args, **kw)
  File "/usr/lib/python2.6/site-packages/mockbuild/util.py", line 345, in do
    raise mockbuild.exception.Error, ("Command failed. See logs for output.\n # %s" % (command,), child.returncode)
Error: Command failed. See logs for output.
 # ['bash', '--login', '-c', 'rpmbuild -bb --target x86_64 --nodeps builddir/build/SPECS/kubevirt.spec']
LEAVE do --> EXCEPTION RAISED

**Comment by cynepco3hahue** [comment]
@sreichar What do you mean "Downstream builds cannot access external systems."? It can not use git package?

**Comment by fabiand** [comment]
```
+ ./hack/build-go.sh install cmd/virt-controller cmd/virt-launcher cmd/virt-handler cmd/virtctl cmd/virt-api
find: '/builddir/build/BUILD/go/src/kubevirt.io/kubevirt/_out/cmd': No such file or directory
hack/version.sh: line 103: git: command not found
hack/version.sh: line 103: git: command not found
hack/version.sh: line 103: git: command not found
hack/version.sh: line 103: git: command not found
hack/version.sh: line 103: git: command not found
```

Could be a missing pre-req (git command) or a side-effect of #998?

**Comment by fabiand** [comment]
> @sreichar What do you mean "Downstream builds cannot access external systems."? It can not use git package?

the build system can not pull something from the internet

**Comment by cynepco3hahue** [comment]
@fabiand It exactly what I meant, we do not pull anything under `version.sh` script, we just run git commands

**Comment by rmohr** [comment]
The issue is that it is not inside the git tree. It should be enough to fill `KUBEVIRT_GIT_COMMIT`, `KUBEVIRT_GIT_TREE_STATE` and `KUBEVIRT_GIT_VERSION` to not run any git commands. Here the description from [hack/version.sh](https://github.com/kubevirt/kubevirt/blob/master/hack/version.sh):

```
# Version management helpers.  These functions help to set, save and load the
# following variables:
#
#    KUBEVIRT_GIT_COMMIT - The git commit id corresponding to this
#          source code.
#    KUBEVIRT_GIT_TREE_STATE - "clean" indicates no changes since the git commit id
#        "dirty" indicates source code changes after the git commit id
#        "archive" indicates the tree was produced by 'git archive'
#    KUBEVIRT_GIT_VERSION - "vX.Y" used to indicate the last release version.
```

**Comment by SchSeba** [comment]
Maybe we need to add a check if git is installed?

**Comment by rmohr** [comment]
> Maybe we need to add a check if git is installed?

Not necessary. The rpms are not built in a source tree. If git would be present it would fail fail because we would execute git outside of the source tree. Setting the environment variables should be good enough.
