### ISSUE TITLE
Inline functions from test/utils.go

### ISSUE THREAD

**Issue by 0xFelix** [kubevirt/kubevirt#11427]
**Is your feature request related to a problem? Please describe**:

The functions `DeleteConfigMap` and `DeleteSecret` in `tests/utils.go` could be inlined, since the do not provide additional value. Also since this is test code, assertions should be used instead of panicking on errors.

**Describe the solution you'd like**:

Inline `DeleteConfigMap` and `DeleteSecret` into the places where they are used.

**Comment by 0xFelix** [comment]
@anishbista60 Please assign yourself to this issue

**Comment by 0xFelix** [comment]
@pat-glitch Sorry, but @anishbista60 is already working on this.

**Comment by pat-glitch** [comment]
@0xFelix Hi, I don't understand. he hasn't assigned himself to the Issue, and it is still open, so I can work on it right?
@alicefr

**Comment by alicefr** [comment]
@pat-glitch we cannot officially assign to him until he comments on the issue, but Felix created this from a discussion with him.

**Comment by pat-glitch** [comment]
@0xFelix @alicefr Sorry, if I overstepped. I had no intention of 'hijacking' or anything.

**Comment by anishbista60** [comment]
@0xFelix @alicefr could you please check my PR and suggest what improvement is needed ?

**Comment by anishbista60** [comment]
@0xFelix  sorry i accidencly closed the pr  i will again raised pr
