### ISSUE TITLE
refactor: simplify validateDataVolumeTemplate

### ISSUE THREAD

**Issue by alicefr** [kubevirt/kubevirt#11428]
The function [validateDataVolumeTemplate](https://github.com/kubevirt/kubevirt/blob/d8180bafa773816c223cea2cb86d2e378503b261/pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go#L358) contains some nesting levels which can be further simplified.

This is a good first issue for people interested in GSoC and who want to get familiar with contributing to KubeVirt

**Comment by pat-glitch** [comment]
@alicefr how do you want me to proceed? Should I simplify the function by dividing it further into separate smaller functions?

**Comment by alicefr** [comment]
@pat-glitch in this case, I would suggest you to try to reduce the nesting level with the early return technique and see how this looks like. Like flipping the first condition and return earlier.

**Comment by pat-glitch** [comment]
@alicefr, I have made a PR, and have reduced the nesting level by 1, please can you review it?

**Comment by pat-glitch** [comment]
sqaush was behaving oddly, so closed the PR, opening a fresh one with all the corrections.
