### ISSUE TITLE
tests/utils.go: Replace calls to GetRunningPodByVirtualMachineInstance with libpod.GetRunningPodByLabel

### ISSUE THREAD

**Issue by 0xFelix** [kubevirt/kubevirt#11439]
**Is your feature request related to a problem? Please describe**:

The function `GetRunningPodByVirtualMachineInstance` in tests/utils.go could be replaced with direct calls to `libpod.GetRunningPodByLabel`, since it does not provide much additional value. Also since this is test code, assertions should be used instead of panicking on errors.

**Describe the solution you'd like**:

In most places where `GetRunningPodByVirtualMachineInstance` is used the VMI is already available, so instead of layering the call to `libpod.GetRunningPodByLabel` in an additional func that fetches the VMI again, calls to `GetRunningPodByVirtualMachineInstance` should be replaced by direct calls to `libpod.GetRunningPodByLabel`.

`getRunningPodByVirtualMachineInstance` could be then inlined into the remaining place where it is used. (`GetRunningVirtualMachineInstanceDomainXML`)

**Comment by EdDev** [comment]
Resolved by https://github.com/kubevirt/kubevirt/pull/11429

/close
