### ISSUE TITLE
VM snapshot finalizers are being left on VMs after snapshot finishes

### ISSUE THREAD

**Issue by alromeros** [kubevirt/kubevirt#11432]
**What happened**:

This is an issue to track the behavior described in PRs such as https://github.com/kubevirt/kubevirt/pull/10775 and https://github.com/kubevirt/kubevirt/pull/11244.

Basically, we've been experiencing issues with VM snapshot-related finalizers being left when they shouldn't, preventing the deletion of VMs. This is triggering issues in some of our tests. 

A fix is in the works, so this issue should only work as a tracker.

**What you expected to happen**:

Finalizers should be removed after the VM snapshot fails or succeeds.

**How to reproduce it (as minimally and precisely as possible)**:

For example, the test quarantined in https://github.com/kubevirt/kubevirt/pull/11244 could replicate this issue consistently.

**Comment by mhenriks** [comment]
fixed in #11241

**Comment by alromeros** [comment]
Great, thanks Michael. Closing this issue.
