### ISSUE TITLE
tests/utils.go: Drop GetPodByVirtualMachineInstance from utils.go and replace it in all callers to libpod.GetPodByVirtualMachineInstance

### ISSUE THREAD

**Issue by 0xFelix** [kubevirt/kubevirt#11440]
**Is your feature request related to a problem? Please describe**:

The functions `getPodsByLabel` and `GetPodByVirtualMachineInstance` in tests/utils.go should be dropped and replaced by calls to `libpod.GetPodByVirtualMachineInstance`. Also since this is test code, assertions should be used instead of panicking on errors.

**Describe the solution you'd like**:

Drop functions `getPodsByLabel` and `GetPodByVirtualMachineInstance` in tests/utils.go and replace calls to `GetPodByVirtualMachineInstance` with `libpod.GetPodByVirtualMachineInstance`.

**Comment by EdDev** [comment]
The issue should be changed to drop `GetPodByVirtualMachineInstance` from `utils.go` and replace it in all callers to `libpod.GetPodByVirtualMachineInstance` that already exists.
