### ISSUE TITLE
tests/utils.go: Move or inline CopyAlpineWithNonQEMUPermissions to the place where it is used

### ISSUE THREAD

**Issue by 0xFelix** [kubevirt/kubevirt#11441]
**Is your feature request related to a problem? Please describe**:

The function `CopyAlpineWithNonQEMUPermissions` in `tests/utils.go` is only used in a single place, so it could be easily moved there.

**Describe the solution you'd like**:

Move or inline `CopyAlpineWithNonQEMUPermissions` to the place where it is used. (`tests/storage/storage.go`)

**Comment by avlitman** [comment]
This issue is fixed by @dankenigsberg in the pr: https://github.com/kubevirt/kubevirt/pull/11756. 
 
 /close

**Comment by dankenigsberg** [comment]
Sorry, I did not notice this issue.
