### ISSUE TITLE
Create func test for node/pod (anti-)affinity

### ISSUE THREAD

**Issue by slintes** [kubevirt/kubevirt#1144]
see https://github.com/kubevirt/kubevirt/pull/1120#issuecomment-396601667 and following

**Comment by slintes** [comment]
Some context: with the mentioned PR we added pod affinity and anti-affinity to VMs. Since a pod is directly related to the virtual machine, this is basically virtual machine affinity / anti-affinity.
Both node and pod affinity still need a functional test. In order to test this, you can e.g. combine both:
- use 2 nodes
- start 2 pods:
    - pod 1 has node affinity to node 1
    - pod 2 has node affinity to node 1 AND pod anti-affinity to pod 1: this should result in an unschedulable pod.
    - when you remove node affinity of pod 2, it should be scheduled to node 2
    - or when you change pod anti-affinity to affinity, it should be scheduled to node 1

**Comment by yanirq** [comment]
Note to Developer:

Writing functional tests is an important aspect of the ongoing development. 
All tests can be run local without the need of CI. Have a look at the [testing section](https://github.com/kubevirt/kubevirt/blob/master/docs/getting-started.md#testing).

Functional tests are located under `tests` folder in the main src directory. 

To grasp the general idea about affinity and anti-affinity see :
[Pod affinity and anti-affinity](https://kubernetes.io/docs/concepts/configuration/assign-pod-node/#affinity-and-anti-affinity) and [VM affinity and anti-affinity](https://kubevirt.io/user-guide/#/workloads/virtual-machines/assigning-vms-to-nodes?id=affinity-and-anti-affinity). 

The test cases above can be added to tests/vmlifecycle_test.go, setting pod affinity/anti-affinity rules on a VM and ensures that the VM can start (or shouldn't start) and scheduled on the right node. 
Using a node selector could  be beneficial for the test (see [comment](https://github.com/kubevirt/kubevirt/pull/1120#issuecomment-396645563))

[Example of how to add Affinity to a VM instance in tests](https://github.com/kubevirt/kubevirt/blob/73edb2f175fd7b7c7d8595c032696823f47c2dd6/tests/vmi_configuration_test.go#L262)
