### ISSUE TITLE
virtctl image-upload doesn't work

### ISSUE THREAD

**Issue by gserpentino** [kubevirt/kubevirt#11451]
**What happened**:
I try to upload an image in Kubevirt env via CDI.
This is the comand:
virtctl image-upload --pvc-name=cirros --access-mode=ReadWriteOnce --pvc-size=5G --image-path=/root/cirros-0.6.2-aarch64-disk.img --uploadproxy-url=https://192.168.1.210:31001/ --insecure --wait-secs=240 --volume-mode=filesystem

I use this 192.168.1.210:31001 becasue I create a service the speake with cdi-uploadproxy
cdi-uploadproxy-nodeport          NodePort    10.96.8.81      <none>        443:31001/TCP

The answer from the system is:
PVC default/cirros not found
PersistentVolumeClaim default/cirros created
Waiting for PVC cirros upload pod to be ready...

No Pods is created and the import doesn't start

This is my env:
root@kubemaster-ot:~# kubectl get pods -A
NAMESPACE            NAME                                       READY   STATUS    RESTARTS       AGE
calico-apiserver     calico-apiserver-6df9864bd4-w4l6n          1/1     Running   6 (21h ago)    2d2h
calico-apiserver     calico-apiserver-6df9864bd4-zz5bk          1/1     Running   6 (21h ago)    2d2h
calico-system        calico-kube-controllers-685f7c9b88-gsmx9   1/1     Running   6 (21h ago)    2d2h
calico-system        calico-node-gsl2v                          1/1     Running   8 (16h ago)    2d2h
calico-system        calico-node-sg2hf                          1/1     Running   6 (21h ago)    2d2h
calico-system        calico-typha-6cbcf9995-vplmb               1/1     Running   8 (21h ago)    2d2h
calico-system        csi-node-driver-qxm6g                      2/2     Running   12 (21h ago)   2d2h
calico-system        csi-node-driver-trlfc                      2/2     Running   12 (16h ago)   2d2h
cdi                  cdi-apiserver-78d5585c5d-pclmc             1/1     Running   0              17h
cdi                  cdi-deployment-74b786dcc6-v9hm2            1/1     Running   0              17h
cdi                  cdi-operator-75d5789946-kksvw              1/1     Running   0              17h
cdi                  cdi-uploadproxy-5c4d65444d-zw6xq           1/1     Running   0              17h
kube-system          coredns-5dd5756b68-g8445                   1/1     Running   6 (21h ago)    2d3h
kube-system          coredns-5dd5756b68-zcjv9                   1/1     Running   6 (21h ago)    2d3h
kube-system          etcd-kubemaster-ot                         1/1     Running   6 (21h ago)    2d3h
kube-system          kube-apiserver-kubemaster-ot               1/1     Running   6 (21h ago)    2d3h
kube-system          kube-controller-manager-kubemaster-ot      1/1     Running   7 (21h ago)    2d3h
kube-system          kube-proxy-b9962                           1/1     Running   8 (16h ago)    2d2h
kube-system          kube-proxy-jpfwd                           1/1     Running   6 (21h ago)    2d3h
kube-system          kube-scheduler-kubemaster-ot               1/1     Running   6 (21h ago)    2d3h
kubevirt             virt-api-668b69dd4-tlt66                   1/1     Running   0              17h
kubevirt             virt-api-668b69dd4-zhkbs                   1/1     Running   0              17h
kubevirt             virt-controller-7b6686f4ff-bslz7           1/1     Running   0              17h
kubevirt             virt-controller-7b6686f4ff-rg5p5           1/1     Running   0              17h
kubevirt             virt-handler-7pplj                         1/1     Running   4 (16h ago)    47h
kubevirt             virt-operator-656b9658fc-4bmzt             1/1     Running   0              17h
kubevirt             virt-operator-656b9658fc-x6bqc             1/1     Running   0              17h
local-path-storage   local-path-provisioner-6d9d9b57c9-kt66z    1/1     Running   0              17h
tigera-operator      tigera-operator-8547bd6cc6-55cc2           1/1     Running   13 (18h ago)   2d2h
root@kubemaster-ot:~#

root@kubemaster-ot:~# kubectl get service -A
NAMESPACE          NAME                              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)                  AGE
calico-apiserver   calico-api                        ClusterIP   10.99.35.198    <none>        443/TCP                  2d2h
calico-system      calico-kube-controllers-metrics   ClusterIP   None            <none>        9094/TCP                 2d2h
calico-system      calico-typha                      ClusterIP   10.107.98.143   <none>        5473/TCP                 2d2h
cdi                cdi-api                           ClusterIP   10.97.0.87      <none>        443/TCP                  45h
cdi                cdi-prometheus-metrics            ClusterIP   10.107.81.168   <none>        8080/TCP                 45h
cdi                cdi-uploadproxy                   ClusterIP   10.96.36.245    <none>        443/TCP                  45h
cdi                cdi-uploadproxy-nodeport          NodePort    10.96.8.81      <none>        443:31001/TCP            14h
default            kubernetes                        ClusterIP   10.96.0.1       <none>        443/TCP                  2d3h
kube-system        kube-dns                          ClusterIP   10.96.0.10      <none>        53/UDP,53/TCP,9153/TCP   2d3h
kubevirt           kubevirt-operator-webhook         ClusterIP   10.101.146.81   <none>        443/TCP                  47h
kubevirt           kubevirt-prometheus-metrics       ClusterIP   None            <none>        443/TCP                  47h
kubevirt           virt-api                          ClusterIP   10.107.176.50   <none>        443/TCP                  47h
kubevirt           virt-exportproxy                  ClusterIP   10.101.24.106   <none>        443/TCP                  47h
root@kubemaster-ot:~#

I also tried the following example but with no lucky

https://github.com/kubevirt/containerized-data-importer/blob/main/doc/upload.md

I have a kubernets cluster with one master e one worker

This is the SC
root@kubemaster-ot:~# kubectl get sc
NAME                   PROVISIONER             RECLAIMPOLICY   VOLUMEBINDINGMODE      ALLOWVOLUMEEXPANSION   AGE
local-path (default)   rancher.io/local-path   Delete          WaitForFirstConsumer   false                  3h50m
root@kubemaster-ot:~#

Virtctl is the last version

Thsi is the error I found at the end of curl command:

 Mark bundle as not supporting multiuse
< HTTP/1.1 503 Service Unavailable
< Vary: Origin
< Date: Tue, 05 Mar 2024 20:47:39 GMT
< Content-Length: 35
< Content-Type: text/plain; charset=utf-8
< Connection: close

and this is the log from uploadproxy
I0306 10:31:31.611261       1 uploadproxy.go:208] Received valid token: pvc: upload-datavolume, namespace: default
E0306 10:31:41.654293       1 uploadproxy.go:212] timed out waiting for the condition

In addition you can visit/refer to:
https://app.slack.com/client/T09NY5SBT

**What you expected to happen**:
To import the image file

**How to reproduce it (as minimally and precisely as possible)**:
It is necessary to have kubernetes env, kubevirt env, CDI env, and 
rancher local-path-provisioner Up & running and try to execute the command.

My sc is created in this way:
cat << EOF | kubectl apply -f -
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: local-path
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: rancher.io/local-path
volumeBindingMode: WaitForFirstConsumer
EOF

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): 
Client Version: version.Info{GitVersion:"v1.2.0", GitCommit:"f26e45d99ac35743fc33d6a121b629e9a9af6b63", GitTreeState:"clean", BuildDate:"2024-03-05T20:34:24Z", GoVersion:"go1.21.5 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v1.1.1", GitCommit:"689c0e66cc6893f311dd648ff32e247203b6c96a", GitTreeState:"clean", BuildDate:"2023-12-25T11:56:11Z", GoVersion:"go1.19.9", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):
  Client Version: v1.28.7
  Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
  Server Version: v1.28.7

- VM or VMI specifications:
    Two virtual machine under virtualbox Version 7.0.12 r159484 (Qt5.15.3)

- Cloud provider or hardware configuration: N/A

- OS (e.g. from /etc/os-release):
   Ubuntu 22.04

- Kernel (e.g. `uname -a`):
  Linux kubemaster-ot 6.5.0-21-generic #21~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Fri Feb  9 13:32:52 UTC 2 x86_64 
  x86_64 x86_64 GNU/Linux

- Install tools: N/A
- Others: N/A

**Comment by 0xFelix** [comment]
With a `WaitForFirstConsumer` (WFFC) storage class you need to pass `--force-bind` to `virtctl image-upload` as an additional argument.

**Comment by gserpentino** [comment]
Hello 0xFelix thanks a lot, now the import work.
But now works also the reation of a vm taken from https://killercoda.com/kubevirt/scenario/kubevirt-cdi
In origin, some days ago also this example doesn't works.
Recantly I have installe se software https://github.com/rancher/local-path-provisioner to manage the local provisiner.
Done this the creatio of vm doesn't work. Today I have removed and installed agai all teh software part of CDI end now works.
I'm not sure the 100%, I shuold retry  this solution.
