### ISSUE TITLE
VM fails to start with passt network binding in v1.2.0

### ISSUE THREAD

**Issue by bc185174** [kubevirt/kubevirt#11471]
**What happened**:

Deployed a basic windows 10 VM with passt binding configured as per https://kubevirt.io/user-guide/virtual_machines/net_binding_plugins/passt/. 

```
{"component":"virt-launcher","level":"error","msg":"internal error: Child process (/usr/bin/passt --one-off --socket /var/run/libvirt/qemu/run/passt/1-default_w10-vm-ua-passtnet.socket --mac-addr 52:54:00:f8:03:a6 --pid /var/run/libvirt/qemu/run/passt/1-default_w10-vm-ua-passtnet-passt.pid --interface eth0 --log-file /var/run/kubevirt/passt.log --tcp-ports 443) unexpected exit status 1: Template interface: eth0 (IPv4)","pos":"virCommandWait:2750","subcomponent":"libvirt","thread":"31","timestamp":"2024-03-08T12:47:21.060000Z"}
...
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to start VirtualMachineInstance with flags 0.","name":"w10-vm","namespace":"default","pos":"manager.go:1101","reason":"virError(Code=1, Domain=0, Message='internal error: Child process (/usr/bin/passt --one-off --socket /var/run/libvirt/qemu/run/passt/1-default_w10-vm-ua-passtnet.socket --mac-addr 52:54:00:f8:03:a6 --pid /var/run/libvirt/qemu/run/passt/1-default_w10-vm-ua-passtnet-passt.pid --interface eth0 --log-file /var/run/kubevirt/passt.log --tcp-ports 443) unexpected exit status 1: Template interface: eth0 (IPv4)\nMAC:\n    host: 52:54:00:f8:03:a6\nDHCP:\n    assign: 100.127.174.31\n    mask: 255.255.255.255\n    router: 169.254.1.1\nDNS:\n    10.96.0.10\nDNS search list:\n    default.svc.cluster.local\n    svc.cluster.local\n    cluster.local\nUNIX domain socket bound at /var/run/libvirt/qemu/run/passt/1-default_w10-vm-ua-passtnet.socket\n\nYou can now start qemu (>= 7.2, with commit 13c6be96618c):\n    kvm ... -device virtio-net-pci,netdev=s -netdev stream,id=s,server=off,addr.type=unix,addr.path=/var/run/libvirt/qemu/run/passt/1-default_w10-vm-ua-passtnet.socket\nor qrap, for earlier qemu versions:\n    ./qrap 5 kvm ... -net socket,fd=5 -net nic,model=virtio\nmount /: Permission denied\nFailed to sandbox process, exiting\n')","timestamp":"2024-03-08T12:47:21.066549Z","uid":"6e11747c-d7dd-436d-aa83-800065e171ca"}
...
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"w10-vm","namespace":"default","pos":"server.go:202","reason":"virError(Code=1, Domain=0, Message='internal error: Child process (/usr/bin/passt --one-off --socket /var/run/libvirt/qemu/run/passt/1-default_w10-vm-ua-passtnet.socket --mac-addr 52:54:00:f8:03:a6 --pid /var/run/libvirt/qemu/run/passt/1-default_w10-vm-ua-passtnet-passt.pid --interface eth0 --log-file /var/run/kubevirt/passt.log --tcp-ports 443) unexpected exit status 1: Template interface: eth0 (IPv4)\nMAC:\n    host: 52:54:00:f8:03:a6\nDHCP:\n    assign: 100.127.174.31\n    mask: 255.255.255.255\n    router: 169.254.1.1\nDNS:\n    10.96.0.10\nDNS search list:\n    default.svc.cluster.local\n    svc.cluster.local\n    cluster.local\nUNIX domain socket bound at /var/run/libvirt/qemu/run/passt/1-default_w10-vm-ua-passtnet.socket\n\nYou can now start qemu (>= 7.2, with commit 13c6be96618c):\n    kvm ... -device virtio-net-pci,netdev=s -netdev stream,id=s,server=off,addr.type=unix,addr.path=/var/run/libvirt/qemu/run/passt/1-default_w10-vm-ua-passtnet.socket\nor qrap, for earlier qemu versions:\n    ./qrap 5 kvm ... -net socket,fd=5 -net nic,model=virtio\nmount /: Permission denied\nFailed to sandbox process, exiting\n')","timestamp":"2024-03-08T12:47:21.066646Z","uid":"6e11747c-d7dd-436d-aa83-800065e171ca"}
{"component":"virt-launcher","level":"error","msg":"internal error: Child process (/usr/bin/passt --one-off --socket /var/run/libvirt/qemu/run/passt/2-default_w10-vm-ua-passtnet.socket --mac-addr 52:54:00:f8:03:a6 --pid /var/run/libvirt/qemu/run/passt/2-default_w10-vm-ua-passtnet-passt.pid --interface eth0 --log-file /var/run/kubevirt/passt.log --tcp-ports 443) unexpected exit status 1: Template interface: eth0 (IPv4)","pos":"virCommandWait:2750","subcomponent":"libvirt","thread":"34","timestamp":"2024-03-08T12:47:21.389000Z"}
```

**What you expected to happen**:

VM should start up with configured interface (passt).

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

1. Deploy KubeVirt v1.2.0
2. Create a basic windows 10 VM with passt network binding as per https://kubevirt.io/user-guide/virtual_machines/net_binding_plugins/passt/.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v1.2.0
- Kubernetes version (use `kubectl version`): v1.27.7
- VM or VMI specifications: Windows 10 VM
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by bc185174** [comment]
> The relevant issue reported by passt(1) is:
> 
> ```
> mount /: Permission denied
> Failed to sandbox process, exiting
> ```
> 
> and this permission was denied by the container-selinux policy until this [change](https://github.com/containers/container-selinux/pull/196). See also https://github.com/kubevirt/kubevirt/blob/main/docs/getting-started.md#disabling-the-custom-selinux-policy:
> 
> > The side effect is that passt-enabled VMIs will fail to start, but only on nodes that use container-selinux version 2.192.0 or lower.
> 
> What is the version of container-selinux on your node?

They are not selinux nodes. I have just clicked it is a `mount` call which container runtime will deny by default. Just going to test the workaround applying the annotation `container.apparmor.security.beta.kubernetes.io/compute: unconfined`.

**Comment by bc185174** [comment]
Nice, yeah just verified this is the problem. Applying the annotation resolves the problem and the pod is running fine.

**Comment by fabiand** [comment]
@bc185174 quick q: Why are you opting in to use passt?

**Comment by vasiliy-ul** [comment]
> 
> @vasiliy-ul is there any form of AppArmor integration we should take care of?

It is mentioned in the user guide: https://kubevirt.io/user-guide/operations/installation/#integration-with-apparmor

If apparmor is enabled on the host machine, and you install profiles which come with libvirt, then they will be applied to the libvirt instance running in a container. KubeVirt ships containers based on centos packages and those do not support apparmor (they are selinux-oriented instead). Hence, to avoid potential problems it is highly recommended to uninstall libvirt and the profiles from the host machine.

Additionally, there is a known problem with mount call which is likely what happens here:

> The default AppArmor profile used by the container runtimes usually denies mount call for the workloads. That may prevent from running VMs with [VirtIO-FS](https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#virtio-fs). This is a [known issue](https://github.com/kubevirt/kubevirt/issues/4290). The current workaround is to run such a VM as unconfined by adding the following annotation to the VM or VMI object:

>annotations:
> container.apparmor.security.beta.kubernetes.io/compute: unconfined

**Comment by bc185174** [comment]
> @bc185174 quick q: Why are you opting in to use passt?

Its more appealing than `masquerade` and `slirp` - https://github.com/kubevirt/kubevirt/issues/10556.

1. Service mesh out-of-the-box.
2. Support live-migration with new network binding plugins introduced in v1.2.0.
3. Requires less permissions.

I can take a look at https://passt.top/passt/tree/contrib/apparmor/abstractions/passt @sbrivio-rh provided. Are there any plans to resolve/fix the [known issue](https://github.com/kubevirt/kubevirt/issues/4290)?

**Comment by fabiand** [comment]
Great, thanks for this feedback. cc @phoracek @AlonaKaplan

**Comment by sbrivio-rh** [comment]
> > @vasiliy-ul is there any form of AppArmor integration we should take care of?
> 
> It is mentioned in the user guide: https://kubevirt.io/user-guide/operations/installation/#integration-with-apparmor

Ah, thanks for the pointer.

> If apparmor is enabled on the host machine, and you install profiles which come with libvirt, then they will be applied to the libvirt instance running in a container. KubeVirt ships containers based on centos packages and those do not support apparmor (they are selinux-oriented instead). Hence, to avoid potential problems it is highly recommended to uninstall libvirt and the profiles from the host machine.

On (at least) Debian and Ubuntu, passt packages ship with AppArmor abstractions (for usage with libvirt), plus stand-alone profiles including those abstractions (and not much more), so the same reasoning should apply. I guess ensuring the correct AppArmor transition if libvirtd (or passt, or virtiofsd) are started from KubeVirt's containers would be the proper fix, though.

> Additionally, there is a known problem with mount call which is likely what happens here:
> 
> > The default AppArmor profile used by the container runtimes usually denies mount call for the workloads. That may prevent from running VMs with [VirtIO-FS](https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#virtio-fs). This is a [known issue](https://github.com/kubevirt/kubevirt/issues/4290).

Right, yes, passt will hit the very same issue -- upon initialisation, it remounts / from an empty filesystem with a zero-block limit, to make sure it has no access to any actual filesystem.

**Comment by bc185174** [comment]
Closing in favour of https://github.com/kubevirt/kubevirt/issues/4290.
