### ISSUE TITLE
Persistent Device Claims for KubeVirt

### ISSUE THREAD

**Issue by sarthaksarthak9** [kubevirt/kubevirt#11472]
Proposal : https://github.com/kubevirt/community/issues/254 

The proposal mentions two potential solutions:

- Using the Dynamic Resource Allocation (DRA) API
- Implementing custom Persistent Device Claims (PDCs)

The detailed plan focuses on developing PDCs. I understand this might be because DRA is still under development. However, the initial proposal also mentioned DRA as a possibility.

Could you please give some more clarity over approaching the implementation ?

**Comment by alicefr** [comment]
@sarthaksarthak9 please use the issue in the community repository. I'll reply to you there.
