### ISSUE TITLE
write /scratch/tmpimage: cannot allocate memory

### ISSUE THREAD

**Issue by denniedeng** [kubevirt/kubevirt#11490]
**What happened**:
virtctl image-upload   --image-path='/iso-qcow2/qcow2/windows/windows_10.qcow2'     --pvc-name=qcow2-windows10-pvc   --pvc-size=8G   --uploadproxy-url=https://10.43.209.73   --insecure   --wait-secs=3600

error:
Using existing PVC default/qcow2-windows10-pvc
Uploading data to https://10.43.209.73

 1.64 GiB / 6.49 GiB [============================>-----------------------------------------------------------------------------------]  25.24% 29s

unexpected return value 500, Saving stream failed: Unable to transfer source data to scratch space: unable to write to file: write /scratch/tmpimage: cannot allocate memory

**What you expected to happen**:
hope to upload success

**How to reproduce it (as minimally and precisely as possible)**:
if i upload a small file (like fedora or centos img ), it is ok. but when i uploaded a large file ( win10 qcow2-6G), the error occured

**Additional context**:
- message of the cdi-upload-xxxx:
I0312 01:56:51.086943       1 util.go:192] Writing data...
E0312 01:57:19.053386       1 util.go:194] Unable to write file from dataReader: write /scratch/tmpimage: cannot allocate memory
E0312 01:57:20.597104       1 data-processor.go:278] write /scratch/tmpimage: cannot allocate memory
unable to write to file
kubevirt.io/containerized-data-importer/pkg/util.StreamDataToFile
	pkg/util/util.go:196
kubevirt.io/containerized-data-importer/pkg/importer.(*AsyncUploadDataSource).Transfer
	pkg/importer/upload-datasource.go:146
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func2
	pkg/importer/data-processor.go:208
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:275
kubevirt.io/containerized-data-importer/pkg/uploadserver.newAsyncUploadStreamProcessor
	pkg/uploadserver/uploadserver.go:433
kubevirt.io/containerized-data-importer/pkg/uploadserver.(*uploadServerApp).uploadHandlerAsync.func1
	pkg/uploadserver/uploadserver.go:332
net/http.HandlerFunc.ServeHTTP
	GOROOT/src/net/http/server.go:2084
net/http.(*ServeMux).ServeHTTP
	GOROOT/src/net/http/server.go:2462
kubevirt.io/containerized-data-importer/pkg/uploadserver.(*uploadServerApp).ServeHTTP
	pkg/uploadserver/uploadserver.go:261
net/http.serverHandler.ServeHTTP
	GOROOT/src/net/http/server.go:2916
net/http.(*conn).serve
	GOROOT/src/net/http/server.go:1966
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1571
Unable to transfer source data to scratch space
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func2
	pkg/importer/data-processor.go:213
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:275
kubevirt.io/containerized-data-importer/pkg/uploadserver.newAsyncUploadStreamProcessor
	pkg/uploadserver/uploadserver.go:433
kubevirt.io/containerized-data-importer/pkg/uploadserver.(*uploadServerApp).uploadHandlerAsync.func1
	pkg/uploadserver/uploadserver.go:332
net/http.HandlerFunc.ServeHTTP
	GOROOT/src/net/http/server.go:2084
net/http.(*ServeMux).ServeHTTP
	GOROOT/src/net/http/server.go:2462
kubevirt.io/containerized-data-importer/pkg/uploadserver.(*uploadServerApp).ServeHTTP
	pkg/uploadserver/uploadserver.go:261
net/http.serverHandler.ServeHTTP
	GOROOT/src/net/http/server.go:2916
net/http.(*conn).serve
	GOROOT/src/net/http/server.go:1966
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1571
E0312 01:57:20.597359       1 uploadserver.go:337] Saving stream failed: Unable to transfer source data to scratch space: unable to write to file: write /scratch/tmpimage: cannot allocate memory

i knew the error was about memory, but the pod was created automatically， i don't know how to increase the pod memory

- my node memory:
 total        used        free      shared  buff/cache   available
 64265        5300        1133          22       57832       58416

**Environment**:
- KubeVirt version (use `virtctl version`): v0.59.2
- Kubernetes version (use `kubectl version`): v1.26.4+k3s1
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): Linux k3s-master 3.10.0-1160.71.1.el7.x86_64
- Install tools: N/A
- Others: N/A

**Comment by akalenyu** [comment]
So it seems like there is a problem to even transfer your image as-is into the temporary scratch PVC
(which would only later be passed to the target PVC after being prepped for VM usage, by `qemu-img convert`)

It seems like the issue is pod memory, but I don't think we'll ever need more than the default (600M for CDI pods), regardless of the image size (windows in this case)
BTW note that its very unlikely that the virtual size of the Windows image is under 70Gi, so 8Gi will probably not cut it
(that is just the compressed qcow2 size)

You can tweak the CDI pod resources section with 
```bash
# k explain cdi.spec.config.podResourceRequirements
GROUP:      cdi.kubevirt.io
KIND:       CDI
VERSION:    v1beta1

FIELD: podResourceRequirements <Object>

DESCRIPTION:
    ResourceRequirements describes the compute resource requirements.
    
FIELDS:
  claims	<[]Object>
    Claims lists the names of resources, defined in spec.resourceClaims, that
    are used by this container. 
     This is an alpha field and requires enabling the DynamicResourceAllocation
    feature gate. 
     This field is immutable. It can only be set for containers.

  limits	<map[string]Object>
    Limits describes the maximum amount of compute resources allowed. More info:
    https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/

  requests	<map[string]Object>
    Requests describes the minimum amount of compute resources required. If
    Requests is omitted for a container, it defaults to Limits if that is
    explicitly specified, otherwise to an implementation-defined value. Requests
    cannot exceed Limits. More info:
    https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
```

If you could also attach the PVC yamls (both the target and scratch) that would help

**Comment by denniedeng** [comment]
@akalenyu you are right. the qcow2 size is larger than 8Gi. so, i try uploaded iso instead of qcow2.
iso image is 4.6Gi, and pvc size is 10Gi. but the problem is the same.
```
[root@k3s-master windows]# du -sh Windows10.iso 
4.6G	Windows10.iso

[root@k3s-master windows]# virtctl image-upload   --image-path='/home/danny/iso-qcow2/iso/windows/Windows10.iso'   --storage-class local-path   --pvc-name=just-test   --pvc-size=10G   --uploadproxy-url=https://10.43.209.73   --insecure   --wait-secs=240
Flag --pvc-name has been deprecated, specify the name as the second argument instead.
Flag --pvc-size has been deprecated, use --size instead.
PVC default/just-test not found 
PersistentVolumeClaim default/just-test created
Waiting for PVC just-test upload pod to be ready...
Pod now ready
Uploading data to https://10.43.209.73

 569.22 MiB / 4.54 GiB [==============>----------------------------------------------------------------------------------------------------]  12.25% 19s

unexpected return value 500, Saving stream failed: Unable to transfer source data to target file: unable to write to file: write /data/disk.img: cannot allocate memory
```

error logs for cdi pod was same.  and pvc yarm like this

kubectl get pvc just-test-scratch -oyaml:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: k3s-master
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  creationTimestamp: "2024-03-26T02:40:55Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
  name: just-test-scratch
  namespace: default
  ownerReferences:
  - apiVersion: v1
    blockOwnerDeletion: true
    controller: true
    kind: Pod
    name: cdi-upload-just-test
    uid: 417dd99c-6bd7-4c43-b810-78344c4be893
  resourceVersion: "87673278"
  uid: 4b9d683b-0196-40f2-a219-b1e0c51d145b
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pvc-4b9d683b-0196-40f2-a219-b1e0c51d145b
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10G
  phase: Bound
```

kubectl get pvc just-test -oyaml:
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    cdi.kubevirt.io/storage.condition.bound: "true"
    cdi.kubevirt.io/storage.condition.bound.message: ""
    cdi.kubevirt.io/storage.condition.bound.reason: ""
    cdi.kubevirt.io/storage.condition.running: "true"
    cdi.kubevirt.io/storage.condition.running.message: ""
    cdi.kubevirt.io/storage.condition.running.reason: Pod is running
    cdi.kubevirt.io/storage.contentType: kubevirt
    cdi.kubevirt.io/storage.pod.phase: Running
    cdi.kubevirt.io/storage.pod.ready: "true"
    cdi.kubevirt.io/storage.pod.restarts: "0"
    cdi.kubevirt.io/storage.upload.target: ""
    cdi.kubevirt.io/storage.uploadPodName: cdi-upload-just-test
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    volume.beta.kubernetes.io/storage-provisioner: rancher.io/local-path
    volume.kubernetes.io/selected-node: k3s-master
    volume.kubernetes.io/storage-provisioner: rancher.io/local-path
  creationTimestamp: "2024-03-26T02:40:55Z"
  finalizers:
  - kubernetes.io/pvc-protection
  name: just-test
  namespace: default
  resourceVersion: "87673466"
  uid: c6ea4c35-9db8-406a-9a5a-4ac8881a2807
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10G
  storageClassName: local-path
  volumeMode: Filesystem
  volumeName: pvc-c6ea4c35-9db8-406a-9a5a-4ac8881a2807
status:
  accessModes:
  - ReadWriteOnce
  capacity:
    storage: 10G
  phase: Bound
```

**Comment by denniedeng** [comment]
btw, i tried 5-6 times， it could work once or twice

**Comment by denniedeng** [comment]
> * write /scratch/tmpimage: cannot allocate memory

if not enough disk space, i think the error would liked:  "no space left on device" ( by reply from #2214). but in my case, the error was about memory.  
and i tried to upload a iso image(4.6G) to a 10G pvc, meat the same error (sometimes would success).

btw, i also checked my disk, there's enough space left.
```
[root@k3s-master k3s_data]# pwd
/home/danny/k3s/k3s_data
[root@k3s-master k3s_data]# ls
pvc-587be325-f980-4d42-a5a5-49b1273cfb60_danny_grafana-pvc      pvc-6d7a66e6-490a-4480-a0ab-30f6b3555589_default_harddisk-win11
pvc-5d38ea91-fff5-45d5-9294-0c5e3bab41db_default_iso-win11-pvc  pvc-8a25f072-861f-4daa-97f5-f44f311618f0_default_iso-win10-pvc
[root@k3s-master k3s_data]# df -h 
Filesystem                         Size  Used Avail Use% Mounted on
devtmpfs                            32G     0   32G   0% /dev
tmpfs                               32G     0   32G   0% /dev/shm
tmpfs                               32G   36M   32G   1% /run
tmpfs                               32G     0   32G   0% /sys/fs/cgroup
/dev/mapper/centos-root             50G   32G   19G  63% /
/dev/sda3                         1014M  372M  643M  37% /boot
/dev/sda1                          200M   37M  164M  19% /boot/efi
/dev/mapper/centos-home            1.8T  138G  1.6T   8% /home

```
