### ISSUE TITLE
Change core manifests from Pod to Deployment

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#115]
In `manifests/*.yaml.in` we have a few cluster wide services which are currently depoyed as Pod. Changing  them to `Deployments` has the benefit that they survive restarts in our vagrant setup.

Definitions to change are:

 - [x] squid proxy (squid.yaml.in)
 - [x] haproxy (haproxy.yaml.in)
 - [x] virt-api (virt-api.yaml.in)
 - [x] virt-controller (virt-controller.yaml.in)

**Comment by RikTheunis** [comment]
Hey @rmohr, I will take this on me if you agree.

**Comment by rmohr** [comment]
@RikTheunis Of course. Will be happy if you take it.

Make sure to check out the [Getting Started Guide](https://github.com/kubevirt/kubevirt/blob/master/docs/getting-started.md), if you didn't already.

Let me know if you need something.

**Comment by rmohr** [comment]
fixed by #126
