### ISSUE TITLE
device-plugins: Add a new USB selector

### ISSUE THREAD

**Issue by victortoso** [kubevirt/kubevirt#11501]
**Is your feature request related to a problem? Please describe**:
A clear and concise description of what the problem is.

With https://github.com/kubevirt/kubevirt/pull/10015, a cluster admin can define USB devices that are plugged into Nodes to be used by VMI. The only selector available is by `vendor` and `product`. In case we have multiple identical devices plugged into the same Node, we have no way of knowing which device is going to which VM.

**Describe the solution you'd like**:

We should add another selector that makes it straightforward to identify which device is going to which VM. The proposal is to use bus and device number, such as `bus=4` and `device=2` for the example below:

```
> lsusb
Bus 004 Device 002: ID 0781:55ae SanDisk Corp. Extreme 55AE
```

**Describe alternatives you've considered**:

We could use serial number or other metadata but those are not are always present. Using bus and device number should provide the feature we want without worrying about corner cases.

**Additional context**:

The problem is related to devices plugged in the same node. If the user wants a specific device in a specific node, it should use a [node selector](https://kubevirt.io/user-guide/operations/node_assignment/)

**Comment by victortoso** [comment]
@TheRealSibasishBehera, would you like to give it a try?

**Comment by victortoso** [comment]
Git history is your friend:
- 2ced17283d62880e669b47230abb40ee6bf0097d added current vendor/product selector. Remember to run `make generate` afterwards
- a06f27ab95ca6badd329460a13c6dc7b46c6fc52 added functional testing. The PR that implements this should extend the functional testing.

To run a cluster with emulated USB environment, you can:

```
export KUBEVIRT_PROVIDER_EXTRA_ARGS="--usb 20M --usb 40M"
make cluster-up && make cluster-sync
```

And to run functional test related to USB

```
FUNC_TEST_ARGS='-focus-file=usb' make functest
```

**Comment by TheRealSibasishBehera** [comment]
@pat-glitch I have already completed most of the work here and will be making a PR soon.  This is a small-ticket issue, but if you are interested, please join its PR review when its done.
