### ISSUE TITLE
Group sidecar tests together

### ISSUE THREAD

**Issue by victortoso** [kubevirt/kubevirt#11504]
**Is your feature request related to a problem? Please describe**:
A clear and concise description of what the problem is.

This is a step in the same direction as https://github.com/kubevirt/kubevirt/pull/10320

The hook sidecars can be used for a variety of things and we test those in different places. Considering that the sidecar is featured gated and all tests rely on hooks sidecar, we should group this tests together as much as possible.

**Describe the solution you'd like**:

We should have a new `tests/sidecar` folder which splits the tests between core functionality of sidecars and whatever extra we have that is related.

I consider core functionality what tests [HookSidecar struct](https://github.com/kubevirt/kubevirt/blob/main/pkg/hooks/hooks.go#L47) and `sidecar-shim` image. Extra would be testing specific sidecars like networking bindings or [storage/hotplug.go](https://github.com/kubevirt/kubevirt/blob/main/tests/storage/hotplug.go#L1253)

**Describe alternatives you've considered**:

**Additional context**:

**Comment by pat-glitch** [comment]
@victortoso do you want the `test/sidecar` to have tests only related to the core functionality?

**Comment by alicefr** [comment]
@pat-glitch there is already an assignee to this issue

**Comment by victortoso** [comment]
Hi @rootxrishabh, how is it going? Let us know if you have any problems with setup, testing or the issue itself.

**Comment by rootxrishabh** [comment]
Hey, @victortoso I am really sorry but I currently don't have the bandwidth to complete this. @pat-glitch would you like to take this up?

**Comment by nagarjunanettem3** [comment]
Hello @victortoso, I am completed code and test on my local. However, when i am pushing the code it showing i dont have permission to push. Btw, this is first issue which i am working.

**Comment by nagarjunanettem3** [comment]
Hello @victortoso , I can see that there is wrong with bazel version. When I am running it bazel 7.2 it is showing like this.
ERROR: no such package '@@bazel_tools//platforms': BUILD file not found in directory 'platforms' of external repository @@bazel_tools. Add a BUILD file to a directory to mark it as a package.
ERROR: C:/users/nagarjunan/_bazel_nagarjunan/laj3cetw/external/io_bazel_rules_docker/toolchains/docker/BUILD:60:10: no such package '@@bazel_tools//platforms': BUILD file not found in directory 'platforms' of external repository @@bazel_tools. Add a BUILD file to a directory to mark it as a package. and referenced by '@@io_bazel_rules_docker//toolchains/docker:default_osx_toolchain'
ERROR: C:/users/nagarjunan/desktop/myfirstproject/kubevirt/BUILD.bazel:91:8: Analysis failed
ERROR: Analysis of target '//:gazelle' failed; build aborted: Analysis failed
INFO: Elapsed time: 0.802s, Critical Path: 0.06s
INFO: 1 process: 1 internal.
ERROR: Build did NOT complete successfully
ERROR: Build failed. Not running target

can you please confirm me which version are we currently using? This is my first PR and if possible please try help me to push to code. TQ :)
