### ISSUE TITLE
Start using the CRs /status subresource

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#1153]
Since k8s-1.10, CRs have their own /status subresource. This allow sane modelling of the spec/status differentiation like it is done for k8s-internal objects:

 * Non-privileged users/controllers can no longer mutate the status
 * The repsonsible controller can directly mutate the status (much easier to not change the spec by accident).

**Comment by rmohr** [comment]
@fabiand gave this the the `urgent` label. We need this definitely before going stable. Maybe another label is more appropriate to express that.

**Comment by fabiand** [comment]
Is it good enough to target it for v1?

**Comment by rmohr** [comment]
We definitely need this.

/remove-lifecycle stale
