### ISSUE TITLE
Get node name where the guest is running from inside the guest

### ISSUE THREAD

**Issue by jjacobelli** [kubevirt/kubevirt#11535]
Hey,

Is there an easy way to get the node name where the guest is running from inside the guest?

That would be really nice if we could have something similar to what is available on pods: https://kubernetes.io/docs/tasks/inject-data-application/environment-variable-expose-pod-information

I'm open to any suggestion on how to solve this using what is currently available on Kubevirt.

Thank you

**Comment by Neoclassic** [comment]
I am also struggling with same problem, but on windows VM.
This DownwardAPIVolumeFile might help in case of Linux VMs. http://kubevirt.io/api-reference/main/definitions.html
