### ISSUE TITLE
Support for adding env and secret in VM definition just like pod

### ISSUE THREAD

**Issue by Neoclassic** [kubevirt/kubevirt#11531]
Feature Request: To maintain parity with containers there should be support of defining environment variables inline so that a VM can be used in different environments without re baking.

`  

env:        
      - name: SERVICE_PORT
          value: "80"
        - name: SERVICE_IP
          value: "172.17.0.1"

`

**Comment by fabiand** [comment]
http://kubevirt.io/api-reference/main/definitions.html#_v1_downwardapivolumesource is supported in kubevirt.

However, due to technical limitations we can not set env variables inisde the guest.
A benefit of containers.
