### ISSUE TITLE
Kubevirt Build Error

### ISSUE THREAD

**Issue by Tusharjain123** [kubevirt/kubevirt#11549]
**What happened**:
Whenever I am running the `make && make push && make manifests` command it gives the following error
![image](https://github.com/kubevirt/kubevirt/assets/103761473/8c32dc1a-dfa0-4966-b692-746db13d4069)

**What you expected to happen**:
Proper build of manifest 

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.
1. `export DOCKER_PREFIX=index.docker.io/myrepo`
2. `export DOCKER_TAG=mybuild`
3. `make && make push && make manifests`

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): 
         Client Version: v1.29.3
         Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): 
          PRETTY_NAME="Ubuntu 22.04.4 LTS"
          NAME="Ubuntu"
          VERSION_ID="22.04"
          VERSION="22.04.4 LTS (Jammy Jellyfish)"
          VERSION_CODENAME=jammy
          ID=ubuntu
- Kernel (e.g. `uname -a`): 
   Linux tushar-HP-Pavilion 6.5.0-26-generic 26~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Mar 12 10:22:43 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: N/A
- Others: N/A

**Comment by Zaher1307** [comment]
I had the same issue but after tring `export PULLER_TIMEOUT=10000` as @victortoso said and it worked for me
