### ISSUE TITLE
Unknown field "configMap.items"

### ISSUE THREAD

**Issue by cbid71** [kubevirt/kubevirt#11556]
**What happened**:

unknown field "spec.volumes[x].configMap.items

Error from server (BadRequest): error when creating "vmi.yaml": VirtualMachineInstance in version "v1" cannot be handled as a VirtualMachineInstance: strict decoding error: unknown field "spec.volumes[2].configMap.items"

**What you expected to happen**:

Try to mount a configmap item as a file on a virtualmachineinstance

**How to reproduce it (as minimally and precisely as possible)**:

```
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: my-vmi
spec:
  domain:
    cpu:
      cores: 2
    memory:
      guest: "4G"
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: cloudinitdisk
        disk:
          bus: virtio
      filesystems:
        - name: config-volume
          virtiofs: {}
  volumes:
  - name: containerdisk
    containerDisk:
      image: ubuntu:latest
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |-
        #!/bin/bash
        echo hello world
        sudo mount -t virtiofs config-volume /etc/config.conf
  - name: config-volume
    configMap:
      name: config-configmap
      items:
         - key: config.conf
           path: config.conf
      

---

apiVersion: v1
kind: ConfigMap
metadata:
  name: config-configmap
data:
  config.conf: |
    [info]
    log-level-console=debug


```

**Additional context**:

According to the documentation, the declaration of the configmap item as a volume looks good.

[https://kubevirt.io/api-reference/main/definitions.html#_v1_configmapvolumesource](https://kubevirt.io/api-reference/main/definitions.html#_v1_configmapvolumesource)
 

**Environment**:kub
- KubeVirt version (use `virtctl version`): 2024-02-07
- Kubernetes version (use `kubectl version`):  1.28
- VM or VMI specifications: linux ubuntu family

- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by victortoso** [comment]
The error is correct, there is no [items field](https://github.com/kubevirt/kubevirt/blob/main/staging/src/kubevirt.io/api/core/v1/schema.go#L71).

Please, take a look at this documentation and see if it helps:
https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#configmap

**Comment by cbid71** [comment]
Ah thank you, yes I saw this page but I wondered if there was a possible other way to make it work.

Because if I follow this page I will have to mount a directory that will contain a file config.conf but the whole directory will be read-only since it's a configmap and not a proper disk.

Because technically if you have to mount a file, and not a directory you can't really do it, right ?

I though of a workaround to mount the configmap somewhere and move the files in the system using the cloudinitnocloud parameter :

```
    cloudInitNoCloud:
      userData: |-
       sudo mkdir /mnt/configmaps
       sudo mount -f virtio config-configmap /mnt/configmaps
       sudo cp /mnt/configmaps/config.conf /etc/config.conf
       sudo chmod 400 /etc/config.conf

```
Not tested, but it looks like a workaround more than a proper way of working, I wondered if there was a cleaner way of doing the job.

**Comment by cbid71** [comment]
Hey @orelmisan You are absolutely right, and that's my point : in my example there is only one file "config.conf" but in a real life experience I would have love to have maybe three, four, five files in the same configmap and being able to play with mount points in different directories of the VMI.
