### ISSUE TITLE
kubevirt virt-operator:latest was not updated for 3 years

### ISSUE THREAD

**Issue by nirs** [kubevirt/kubevirt#11551]
**What happened**:

Trying to build kubevirt from git, for testing unreleased change:

    DOCKER_PREFIX=quay.io/kubevirt DOCKER_TAG=latest make manifests

After applying the kubevirt-operator.yaml, the virt-operator deployment fail with
this error in the logs:

    $ kubectl logs deploy/virt-operator -n kubevirt
    Found 2 pods, using pod/virt-operator-67f4f4f7c9-8vqb9
    {"component":"virt-operator","level":"info","msg":"empty env var OPERATOR_IMAGE
    for operator image\n","pos":"application.go:131","timestamp":"2024-03-17T19:38:37.274898Z"}

Checking the latest tag show that it was built 3 years ago:
https://quay.io/repository/kubevirt/virt-operator?tab=tags

**What you expected to happen**:

virt-operator working using image created from latest commit
or pulling the image fails since there is not "latest" tag.

**How to reproduce it (as minimally and precisely as possible)**:

1. Build kubevirt using DOCKER_TAG=latest
2. Deploy _out/manifests/release/kubevirt-operator.yhaml
3. Watch kubvirt namespace

**Environment**:
- KubeVirt version (use `virtctl version`): built from git
- Kubernetes version (use `kubectl version`): v1.28.3
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Workaround**

Use an available tag like:

    DOCKER_PREFIX=quay.io/kubevirt DOCKER_TAG=20240319_9c3a52d67 make manifests

**Comment by akalenyu** [comment]
I believe kubevirt doesn't use latest/devel tags, instead, it uses the commit hash
so here https://quay.io/repository/kubevirt/virt-operator?tab=tags `20240319_9c3a52d67` corresponds to https://github.com/kubevirt/kubevirt/commit/9c3a52d67c6782cd48ae0702df5493f5023a04cc

**Comment by nirs** [comment]
This should be an easy fix - if the intent is to never update the latest tag, it should not exit. Someone with the right permissions in quay.io can delete stale the tag.

**Comment by xpivarc** [comment]
> This should be an easy fix - if the intent is to never update the latest tag, it should not exit. Someone with the right permissions in quay.io can delete stale the tag.

Sounds good, @brianmcarey @dhiller can you have a look?

**Comment by brianmcarey** [comment]
> > This should be an easy fix - if the intent is to never update the latest tag, it should not exit. Someone with the right permissions in quay.io can delete stale the tag.
> 
> Sounds good, @brianmcarey @dhiller can you have a look?

Yes sure - I can remove the old tags.

**Comment by brianmcarey** [comment]
The latest tags have been removed from quay - I think we are good to close this issue. 

Thanks for raising this @nirs 

/close
