### ISSUE TITLE
virtctl: use client-go/log

### ISSUE THREAD

**Issue by victortoso** [kubevirt/kubevirt#11568]
**Is your feature request related to a problem? Please describe**:
A clear and concise description of what the problem is.

We have a mix of components in virtctl that are using either `golang/glog` or `kubevirt.io/client-go/log`. 
For consistency, we should use the same logging module and I'd recommend our `client-go/log` as, if we need, we can change it latter to affect all components that use it.

I consider this a sub-task of https://github.com/kubevirt/kubevirt/issues/5932

**Describe the solution you'd like**:
- All `virtctl` modules should be using `client-go/log`
- They should all call `InitializeLogging` as well, to provide a reasonable component name.

**Comment by victortoso** [comment]
Not sure I can label it, let's try.
/label good-first-issue

Possible assignee for the task: Ahmed Zaher (not sure his handle)

**Comment by harsh-vardhan-ande** [comment]
@victortoso @0xFelix I have raised https://github.com/kubevirt/kubevirt/pull/12070 to fix this issue. Requesting your review.
