### ISSUE TITLE
Contribfest - Kubecon 2024 Paris

### ISSUE THREAD

**Issue by xpivarc** [kubevirt/kubevirt#11569]
Menu of the day:

Features:
https://github.com/kubevirt/kubevirt/issues/11566 - Adjust dynamically libvirt and qemu log verbosity - 1+
https://github.com/kubevirt/kubevirt/issues/11571 - virt-handler does not clean up labels added by node-labeller
https://github.com/kubevirt/kubevirtci/issues/1160 - Convert the vm.sh script into a go binary
https://github.com/kubevirt/kubevirt/issues/11576 - Create a sidecar to enable arm emulation

No code: 
https://github.com/kubevirt/kubevirt/issues/11564 - Move libguestfs documentation in the user guide 
https://github.com/kubevirt/kubevirt/issues/9666 - Document KubeVirt building system 
https://github.com/kubevirt/user-guide/issues/775 - Add how to retrieve the version of the hook sidecar shim version from kubevirt cr 
https://github.com/kubevirt/kubevirt.github.io/issues/933 - Lab: LiveMigration out of date
https://github.com/kubevirt/kubevirt.github.io/issues/938 - Updates required for lab1
https://github.com/kubevirt/kubevirt.github.io/issues/939 - Update lab 2
https://github.com/kubevirt/kubevirt.github.io/issues/940 - Update lab 3
Introduce dependabot https://github.com/kubevirt/kubevirt/security/dependabot 
https://github.com/kubevirt/user-guide/issues/776 - Create the documentation for virtcrtl adm
https://github.com/kubevirt/user-guide/issues/701 - User guide contributor guide

Maintainability:
https://github.com/kubevirt/kubevirt/issues/11574 - Corruption of Kubevirt - 3+ people 
https://github.com/kubevirt/kubevirt/issues/11565 - refactor: replace all the deprecated functions with libvmi - 3 +
https://github.com/kubevirt/kubevirt/issues/11570 - Get rid of Informers in controllers - 3+
https://github.com/kubevirt/kubevirt/issues/11572 - Improve testability of virt-handler - 
https://github.com/kubevirt/kubevirt/issues/11573 - Get rid of the mocks - 3+
https://github.com/kubevirt/project-infra/issues/3228 - Bug: dependabot: fails to handle creation of PRs with incompatible go module version updates
https://github.com/kubevirt/kubevirt.github.io/issues/935 - Bug: make build failed

**Comment by alicefr** [comment]
https://github.com/kubevirt/kubevirtci/issues/1160

**Comment by alicefr** [comment]
https://github.com/kubevirt/kubevirt/issues/11576

**Comment by anishbista60** [comment]
@alicefr What is this above menu  of issue?

**Comment by alicefr** [comment]
@anishbista60 this isn't very clear from the description. We had last week a [workshop](https://kccnceu2024.sched.com/event/1YkSg/contribfest-the-prs-must-flow-a-kubevirt-contributor-workshop?iframe=no) for KubeCon. The list of issues there is for this event.

**Comment by xpivarc** [comment]
As the workshop is over, anyone can pick one of these issues.

**Comment by fabiand** [comment]
/close

Done
