### ISSUE TITLE
Improve testability of virt-handler

### ISSUE THREAD

**Issue by xpivarc** [kubevirt/kubevirt#11572]
One of the frequent logic inside virt-handler is handling of communication between the handler and virt-launchers that represent the VMs. Currently we use [FindSocketOnHost](https://github.com/kubevirt/kubevirt/blob/d4112d68b113f3d0ef0e5427c4976a86e78d1983/pkg/virt-handler/cmd-client/client.go#L264) for detecting a socket over which we communicate. 

The problem with this direct approach is that building a well isolated tests is not an easy task. A well defined interface covering all the usage of this function would allow us to use stub for testing, improving and easing the testing.

The suggested approach is to look at the individual usages of this function and propose a good abstraction for it. Another option would be to embed this logic into the [NewClient](https://github.com/kubevirt/kubevirt/blob/d4112d68b113f3d0ef0e5427c4976a86e78d1983/pkg/virt-handler/cmd-client/client.go#L309) function.

**Comment by anishbista60** [comment]
@xpivarc I'm try to find out some good solution and will come with PR . Thanks
/assign
