### ISSUE TITLE
virt-handler does not clean up labels added by node-labeller

### ISSUE THREAD

**Issue by alicefr** [kubevirt/kubevirt#11571]
**Is your feature request related to a problem? Please describe**:
When KubeVirt is uninstalled, the labels added to each node by virt-handler are not cleaned up.

**Describe the solution you'd like**:
 Remove the kubevirt labels during the [kubevirt removal](https://github.com/kubevirt/kubevirt/blob/239d7983ee4d4d049c520ab11edcd0f828b70e0e/pkg/virt-operator/resource/apply/delete.go#L95). This should also include unit tests.

**Comment by anishbista60** [comment]
@alicefr i want to work on this issue
