### ISSUE TITLE
Add cross-architecture emulation support

### ISSUE THREAD

**Issue by CrossStratos** [kubevirt/kubevirt#11578]
**Is your feature request related to a problem? Please describe**:

A major feature of qemu, is it's ability to emulate other architectures ([TCG](https://www.qemu.org/docs/master/devel/index-tcg.html)) 
while running on the hosts architecture. This paired with custom board types allows 
companies to quickly prototype and develop for different architectures and hardware variants.

After looking at the source code and documentation, it appears kubevirt only supports
virtualization (KVM) and emulation (TCG + Feature Gate) of the hosts architecture. 
This limited feature set makes kubevirt a pure virtualization platform, limiting what type
of work loads can be ran.

**Describe the solution you'd like**:

It would be great to have cross architecture emulation using TCG. For example, I want
to be able to run a Xilinx board + cortex-a53 CPU on an x86 node. This opens up a new
use case of kubevirt which is emulated device testing.

**Describe alternatives you've considered**:

One solution is to not use kubevirt, and just use a container that has all the dependencies
needed to run cross architecture emulation. This isn't ideal since all of the niceties of kubevirt
are lost.

**Additional context**:

I am not pretending to know all of the complexities of kubevirt, qemu and libvirt. There may be
technical limitations that I don't know about, so any help feedback would be appreciated. Thank you!

**Comment by fabiand** [comment]
We are open to see designs for this RFE.
Until then I'm closing this, please reopen if necessary.

/close

**Comment by andrew-morris-rgs** [comment]
If I am tracking all of the moving parts so far.
[The emulation device](https://github.com/kubevirt/kubevirt/blob/main/docs/vm-configuration.md#devices) is already exposed in the VM configuation, so it is a matter of the relevant emulator bin being in the container (i.e. /usr/bin/qemu-system-x86_64 or /usr/bin/qemu-system-aarch64, [etc](https://www.qemu.org/docs/master/system/targets.html)), and mapping that field.

Then mapping the os.arch/machine fields to appropriate supported arch and machine type.

My best guess of the yaml format would be:
```
domain:
  type='qemu'
  os:
    ## in the xml example I'm follwing its <type arch='i686' machine='pc'>hvm</type>
    type: 
       name: 'hvm'
       arch: 'i686'
       machine: 'pc'
  devices:
     emulator: /usr/bin/qemu-system-x86_64
```

Though I'm not sure how os.type actually breaks down field wise.

**Comment by bcdurden** [comment]
Would like to reopen this for consideration. Have several industry customers looking for this capability as they leave AMD64 and still need to run legacy VMs that cannot be rebuilt.

**Comment by andrew-morris-rgs** [comment]
Is this https://github.com/kubevirt/kubevirt/issues/13837 related to this ticket being possibly reopened?
