### ISSUE TITLE
update kubernetes version compatibility commitment doc

### ISSUE THREAD

**Issue by zhaorendong** [kubevirt/kubevirt#11587]
**Description**:
This file hasn't been updated with the Kubernetes Version Compatibility Commitment doc for three years.

**What you expected**:
I would like to update the kubernetes version compatibility for each kubevirt version.

**URL**:
[Provide a link to the documentation.](https://github.com/kubevirt/kubevirt/blob/main/docs/kubernetes-compatibility.md)

**Comment by caijian76** [comment]
https://github.com/kubevirt/sig-release/blob/main/releases/k8s-support-matrix.md
