### ISSUE TITLE
Passt plugin binary can't work after v1.1.1

### ISSUE THREAD

**Issue by caijian76** [kubevirt/kubevirt#11586]
report error : /lib64/libc.so.6 version GLIBC 2.34 not found
BYW,release v1.1.1 binary file [kubevirt-passt-binding](https://github.com/kubevirt/kubevirt/releases/download/v1.1.1/kubevirt-passt-binding)
24.1 MB work fine.

**Comment by victortoso** [comment]
> report error : /lib64/libc.so.6 version GLIBC 2.34 not found

Which OS is your node running?

I wonder if this is due 7b27b1d041619b4393ddc74ad18abe0c5d1a1e84
/cc @brianmcarey

**Comment by brianmcarey** [comment]
> > report error : /lib64/libc.so.6 version GLIBC 2.34 not found
> 
> Which OS is your node running?
> 
> I wonder if this is due [7b27b1d](https://github.com/kubevirt/kubevirt/commit/7b27b1d041619b4393ddc74ad18abe0c5d1a1e84) /cc @brianmcarey

Yes it would depend on which OS the node is running. We could go back to building this statically for better compatibility.

**Comment by caijian76** [comment]
Centos8 and (GNU libc) 2.28
