### ISSUE TITLE
`kubevirt-passt-binding` plugin for alternative platforms (i.e. ARM64/aarch64)

### ISSUE THREAD

**Issue by marvkis** [kubevirt/kubevirt#11590]
**Is your feature request related to a problem? Please describe**:
I am trying to use passt on ARM. From the documentation I've learned, I should be using the new CNI binding for passt.
Currently, only a pre-built amd64 binary is available for download as a release asset: https://github.com/kubevirt/kubevirt/releases/tag/v1.2.0

**Describe the solution you'd like**:
It would be great to have pre-build assets of `kubevirt-passt-binding` for all other supported platforms, like there it is for the `virtctl` binary.
Or even better: a 'dropper' container that automatically installs the binary, like it exists for multus ;)

**Describe alternatives you've considered**:
As a first test, I will try to build `kubvirt-passt-binding` for arm64 on my own.

**Additional context**:
None right now....

**Comment by victortoso** [comment]
You can fetch it from quay.io
https://quay.io/repository/kubevirt/network-passt-binding?tab=tags

**Comment by marvkis** [comment]
Hi @victortoso, thanks for your answer.
Does this image also contain the 'CNI' plugin that needs to be installed in the node's `/opt/cni/bin/` folder as described [here](https://kubevirt.io/user-guide/virtual_machines/net_binding_plugins/passt/#passt-cni-deployment-on-nodes)? As I understand it, the container you are referring to is the [sidecar image to kubvirt](https://kubevirt.io/user-guide/virtual_machines/net_binding_plugins/passt/#passt-sidecar-image).
If the CNI is also in this container do you have any hints for me on how to get it extracted and installed on the node?
Thanks!

**Comment by victortoso** [comment]
No, you are right. I pointed you to the sidecar, which has arm builds. It wasn't what you asked. Sorry about it.

**Comment by marvkis** [comment]
No problem ;)

**Comment by marvkis** [comment]
Hi. A quick status update: I was able to compile the CNI driver for ARM and the compute container tried to start up. But qemu failed to start with:
```
[...] Message='internal error: QEMU unexpectedly closed the monitor (vm=...): 
 qemu-kvm: -device {\"driver\":\"virtio-net-pci-non-transitional\",\"netdev\":\"hostua-pod\",\"id\":\"ua-pod\",\"mac\":\"52:54:00:xx:yy:zz\",\"bus\":\"pci.1\",\"addr\":\"0x0\"}: failed
to find romfile \"efi-virtio.rom\"')","timestamp":"2024-03-25T20:56:40.143648Z","uid":"some-uuid`"}
```
After doing some research, I came across this [bug report](https://bugzilla.redhat.com/show_bug.cgi?id=1337510) which states that no rom is needed for ARM platforms. Instead, a `<rom bar='off'/>` statement should be added for Virtio devices .
So I created a [hook sidecar](https://kubevirt.io/user-guide/operations/hook-sidecar/) that patches my interface statements:
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: my-config-map
data:
  my_script.sh: |
    #!/bin/sh
    tempFile=`mktemp --dry-run`
    echo $4 > $tempFile
    sed -i "s|</interface>|<rom bar='off'/></interface>|g" $tempFile
    cat $tempFile
```
Now it works.
So it seems that the qemu config also needs to be properly adapted for the ARM platform....

**Comment by victortoso** [comment]
Many thanks for the info @marvkis, I'll /cc @zhlhahaha as he might be interested in this too!

**Comment by caijian76** [comment]
@marvkis How did you recompile the CNI driver for ARM?

**Comment by marvkis** [comment]
Hi @caijian76,

These are my notes I took during the build session:

* Create a lxc/icinga ubuntu container, install git & docker
* Compile kubvirt-passt-binding
```bash
git clone https://github.com/kubevirt/kubevirt.git
cd kubevirt
make
# make fails
hack/dockerized ". ./hack/common.sh ; bazel run --config=aarch64 :build-cni-passt-binding -- \${CMD_OUT_DIR}/cniplugins/kubevirt-passt-binding"
# binary is now in _out/cmd/cniplugins/kubevirt-passt-binding
```

I just created a (gist)[https://gist.github.com/marvkis/04db1cb0e29fb97a387a7c106b8eea53] where you can find my notes and the binary I built. But only for testing purposes - this is not a validated build ;)

**Comment by caijian76** [comment]
@marvkis THK, VM is up and running, but passt network not working properly. Except for port 22, other ports cannot be used normally. Is it normal for you?

**Comment by sbrivio-rh** [comment]
@caijian76 unless there's an easier answer to this, captures just like you provided at https://github.com/kubevirt/kubevirt/issues/11591#issuecomment-2022040830 would be great to have here, too.

**Comment by caijian76** [comment]
@sbrivio-rh #11591 is x84 platform, and this program is  ARM64 .

In VM:
```
python3 -m http.server &
tcpdump port 8000

23:57:34.135620 IP 192-168-89-107.kubernetes.default.svc.cluster.local.39064 > localhost.localdomain.irdmi: Flags [S], seq 2984553612, win 65535, options [mss 65480,nop,wscale 8], length 0
23:57:44.135685 IP 192-168-89-107.kubernetes.default.svc.cluster.local.39064 > localhost.localdomain.irdmi: Flags [R], seq 2984553613, win 65535, length 0
```
In other host:
```
curl {vm pod IP}:8000
````
wait amoment,return Connection reset by peer.

**Comment by caijian76** [comment]
I'm stupid. There's a firewall on the VM.

**Comment by caijian76** [comment]
@marvkis #11896
