### ISSUE TITLE
virtctl/virt-viewer error messages debug log still not that helpful

### ISSUE THREAD

**Issue by shiywang** [kubevirt/kubevirt#1161]
so I was trying to use the cnv-qe job to build a slave and cluster, vms running, then on my slaves I want to use virtctl to actually login to my vms, so I `yum install virt-viewer` and `wget virtctl` from release page, and then use this command
```
[cnv-qe-jenkins@cnv-executor-shiywang kubevirt-ansible]$ ./virtctl-v0.6.0-linux-amd64 vnc --kubeconfig ~/.kube/config test-vm -v 10
I0614 22:49:30.850320   25152 loader.go:357] Config loaded from file /home/cnv-qe-jenkins/.kube/config
I0614 22:49:30.878340   25152 round_trippers.go:417] curl -k -v -XGET  -H "Authorization: Bearer LMfERfDPRBFwyj0gjxtwz-7Kl0rioCSTcARjpzBNTBo" wss://cnv-executor-shiywang-master1.example.com:8443/apis/subresources.kubevirt.io/v1alpha1/namespaces/golden-images/virtualmachines/test-vm/vnc
E0614 22:49:30.880386   25152 vnc.go:103] remote-viewer execution encountered an error: exit status 1

```
I still don't know what's the problem of virt-viewer... yeah, I mean this maybe not a bug of virtctl/kubevirt, but do you guys know where should I ask for help or some other detailed log about virt-viewer I could check ?

**Comment by rmohr** [comment]
@shiywang You need at least `0.7.0-alpha.0` to get more information.

**Comment by shiywang** [comment]
@rmohr so two questions here:
1. why `0.7.0-alpha.0`'s virtctl version name is still `v0.6.1`
2. after download that virtctl got this error messges, anything wrong here?
```
[cnv-qe-jenkins@cnv-executor-shiywang kubevirt-ansible]$ ./virtctl-v0.6.1-alpha.0-linux-amd64 vnc --kubeconfig ~/.kube/config test-vm -v 10
I0615 07:45:57.358474    1467 loader.go:357] Config loaded from file /home/cnv-qe-jenkins/.kube/config
I0615 07:45:57.360116    1467 round_trippers.go:417] curl -k -v -XGET  -H "Authorization: Bearer LMfERfDPRBFwyj0gjxtwz-7Kl0rioCSTcARjpzBNTBo" wss://cnv-executor-shiywang-master1.example.com:8443/apis/subresources.kubevirt.io/v1alpha2/namespaces/golden-images/virtualmachineinstances/test-vm/vnc
I0615 07:45:57.370907    1467 round_trippers.go:436] GET wss://cnv-executor-shiywang-master1.example.com:8443/apis/subresources.kubevirt.io/v1alpha2/namespaces/golden-images/virtualmachineinstances/test-vm/vnc  in 10 milliseconds
I0615 07:45:57.370920    1467 round_trippers.go:442] Response Headers:
Can't access VMI test-vm: Can't connect to websocket (404): 404 page not found
```

**Comment by rmohr** [comment]
> why 0.7.0-alpha.0's virtctl version name is still v0.6.1

No idea. At least they are built from the same commit, so no issues to expect here.

> after download that virtctl got this error messges, anything wrong here?

Version Everyting after the official 0.6 release is not compatible with later things. You will have to update the whole kubevirt installation for that, not just virtctl.

**Comment by fabiand** [comment]
@shiywang can you recreate a fresh env and retets?

**Comment by petrkotas** [comment]
@shiywang How does the issue look?

**Comment by petrkotas** [comment]
@shiywang do you still encounter this issue after upgrade?
