### ISSUE TITLE
Request to not create DV/PVC if the VM is in `Stopped` and DV is deleted

### ISSUE THREAD

**Issue by viveksinghggits** [kubevirt/kubevirt#11637]
**Is your feature request related to a problem? Please describe**:

When restoring a VirtualMachine in the same namespace it was originally created in, using the upstream `VirtualMachineRestore` API, we see that new DV/PVC pairs are created with new names (diff than what DV/PVC already had) and then the VM is updated to refer to these newly created DV/PVC.
If I (or a backup software) am not using the upstream restore API to restore the VM or don't want the restored DV/PVCs to have diff names and want to restore the DV/PVC by myself; here is what I was planning to do.

1. Stop the VirtualMachine
2. Delete the DV/PVC pairs that are referred by VM
3. Create/Restore new DV/PVC pairs
4. Start the VM

But the problem with above approach is, as soon as the DV/PVC, referred by a VM, is deleted the controller creates new DV which would  result into a new PVC getting created. Which is not desirable because whoever is restoring the VM would want to create DV/PVC with restored data.

For the cases where the DV is not garbage collected, we can just restore the PVC because if the DV has proper annotation it will not create PVC again and it will let me (backup software) restore PVC. But it would not really work the cases where the DV is garbage collected.

**Describe the solution you'd like**:

Would it be a good idea to not start creating the DV and PVC if the VM is in `stopped` state? In other words if the VM is stopped and we delete the DV/PVC, KubeVirt controller should not create DV immediately and wait for it to transition to new state towards `started`, to create the DV.

**Comment by awels** [comment]
So the DVs are just recipes on how to populate a PVC. Once the PVC is populated the DVs really serve no purpose anymore. They are a lot like populators (which are the k8s way of doing population). So in order to stop the VM controller from creating the DVs (from the DVTemplate) don't delete the DVs. You can put annotations on the DVs to tell them to behave differently (like not creating PVCs, but instead 'adopting' PVCs with the appropriate name). This solves the backup/restore issue you are talking above here. The `cdi.kubevirt.io/allowClaimAdoption` annotation should make the behavior different. This is for CDI 1.58 and newer.

**Comment by viveksinghggits** [comment]
> So in order to stop the VM controller from creating the DVs (from the DVTemplate) don't delete the DVs. You can put annotations on the DVs to tell them to behave differently (like not creating PVCs, but instead 'adopting' PVCs with the appropriate name).

yeah, this sounds good and would work for the scenarios where the DV is not garbage collected. In these cases we can just delete the PVC and create/restore it. Things would happen as expected because DV would have proper annotation (`cdi.kubevirt.io/storage.prePopulated`).

But I don't think this resolves the problem for the scenarios where the DV's are garbage collected. In that case if we delete the PVC, a new DV would be created right? Or this (`cdi.kubevirt.io/allowClaimAdoption`) annotation would resolve things for this case?

**Comment by awels** [comment]
If the DVs are garbage collected, it should have modified the VM spec to no use DVs anymore, and just use straight PVCs. We wanted to move forward with not using DVs at all since populators are available, but ran into some issues with the DV garbage collection, so we have turned it off for newer versions. Only one or two older versions do the garbage collecting.

**Comment by viveksinghggits** [comment]
> If the DVs are garbage collected, it should have modified the VM spec to no use DVs anymore, and just use straight PVCs. 

I am not really sure if you meant the VM resource would be updated to not have DV's reference under volumes etc or if you meant PVC's owner would be changed from DV to VM.
If you meant VM doesn't refer to DV anymore, I have experienced/experiencing different behaviour. Even if the DV is garbage collected VM still has reference to DV even though the PVC's owner is changed to DV.

In below example DV is garbage collected

```
k get vm,vmi,dv,pvc,pod -n vm                                                     
NAME                                             AGE   STATUS    READY
virtualmachine.kubevirt.io/rhel7-trusting-shaw   36m   Running   True

NAME                                                     AGE     PHASE     IP            NODENAME                READY
virtualmachineinstance.kubevirt.io/rhel7-trusting-shaw   4m26s   Running   10.244.0.44   viveksdo-pool-1-jmarm   True

NAME                                        STATUS   VOLUME                                     CAPACITY      ACCESS MODES   STORAGECLASS       VOLUMEATTRIBUTESCLASS   AGE
persistentvolumeclaim/rhel7-trusting-shaw   Bound    pvc-5a3ca64d-3141-4f06-9155-83a4205932b7   34087042032   RWO            do-block-storage   <unset>                 13m

NAME                                          READY   STATUS    RESTARTS   AGE
pod/virt-launcher-rhel7-trusting-shaw-6zhq7   1/1     Running   0          4m27s
```

and this is what we see in VM

```
k get vm -n vm rhel7-trusting-shaw -ojsonpath='{.spec.template.spec.volumes[0]}' | jq
{
  "dataVolume": {
    "name": "rhel7-trusting-shaw"
  },
  "name": "rootdisk"
}


k get vm -n vm rhel7-trusting-shaw -ojsonpath='{.spec.dataVolumeTemplates[0]}' | jq
{
  "apiVersion": "cdi.kubevirt.io/v1beta1",
  "kind": "DataVolume",
  "metadata": {
    "creationTimestamp": null,
    "name": "rhel7-trusting-shaw"
  },
  "spec": {
    "source": {
      "http": {
        "url": "https://access.cdn.redhat.com/content/origin/files/sha256/68/68312d7c9f6316921086dc891285fdba41a0f0febee35cc28161d65e6170857f/rhel-8.0-x86_64-kvm.qcow2?user=1c3d31d74bffc7beac07786ebcaca416&_auth_=1712092381_a858edda09672b1a10aea32387e2ce9e"
      }
    },
    "storage": {
      "accessModes": [
        "ReadWriteOnce"
      ],
      "resources": {
        "requests": {
          "storage": "30Gi"
        }
      },
      "volumeMode": "Filesystem"
    }
  }
}

```

**Comment by awels** [comment]
Can you tell me which version of CDI and KubeVirt you are running. I know we wrote specific code in both to do the garbage collecting, and then to modify the VM to no longer reference the DataVolume once it was garbage collected. If you are not seeing that then the KubeVirt version you are running is not updating it.

**Comment by viveksinghggits** [comment]
KubeVirt Version: v1.0.0
CDI Version: v1.56.0

**Comment by viveksinghggits** [comment]
Also, also in the cases where after garbage collection of DV the DV is not referred in VM at all, what would be the behaviour  if the PVC is deleted? Since the VM no longer has reference to the DV resources, I am assuming DV should not be created again to import the things. 

Also, this sounds a bit strange that a  controller would change the VM spec (a kubernetes) to just entirely get rid of something that the users had provided.
