### ISSUE TITLE
The GPU-related metrics data exposed by DCMG-EXPORT does not include the laungcher pod with the GPU bound

### ISSUE THREAD

**Issue by rokkiter** [kubevirt/kubevirt#11660]
**What happened**:

When a VM created with kubevirt is bound to a GPU via passthrough mode, the GPU-related metrics data exposed by DCMG-EXPORT does not include the laungcher-pod with the GPU bound.

With a GPU bound directly to a pod (not created by kubevirt), the DCMG-EXPORT is able to obtain the GPU metrics for that pod.

**What you expected to happen**:

A kubevirt-created launcher bound to a GPU can be captured by DCMG-EXPORT.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

1.  On a cluster with NVIDIA GPU Operator installed
2. Create a VM By VMI and binding GPU
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
...
  devices:
     gpus:
     - deviceName: nvidia.com/xxxx
       name: gpu-x
....
```
3. View GPU-related metrics in prometheus

**Additional context**:

You can see by the following code that DCMG EXPORT filters based on PodResource, the rules are
```resourceName == nvidiaResourceName``` or ```strings.HasPrefix(resourceName, nvidiaMigResourcePrefix)```
The nvidiaResourceName is  **"nvidia.com/gpu"**

https://github.com/NVIDIA/dcgm-exporter/blob/main/pkg/dcgmexporter/kubernetes.go#L142
```
func (p *PodMapper) toDeviceToPod(
	devicePods *podresourcesapi.ListPodResourcesResponse, sysInfo SystemInfo,
) map[string]PodInfo {
	deviceToPodMap := make(map[string]PodInfo)

	for _, pod := range devicePods.GetPodResources() {
		for _, container := range pod.GetContainers() {
			for _, device := range container.GetDevices() {

				resourceName := device.GetResourceName()
				if resourceName != nvidiaResourceName {
					// Mig resources appear differently than GPU resources
					if !strings.HasPrefix(resourceName, nvidiaMigResourcePrefix) {
						continue
					}
				}
				...
			}
		}
	}

	return deviceToPodMap
}
```

But in kubevirt, the GPU-related PodResource Name seems to be ```gpu.DeviceName```.

**Environment**:
- KubeVirt version (use `virtctl version`): 1.0.0
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by machadovilaca** [comment]
Although I don't know in detail how we are handling GPUs in KubeVirt, I think it's clear that we passthrough the device name exactly, and it seems this is related to the NVIDIA metric collector. If you set up your VM requesting a GPU

```
spec:
  domain:
    devices:
      ...
      gpus:
      - deviceName: nvidia.com/SOMETHING
        name: gpu1
```

the resulting `virt-launcher` pod will contain a direct match of that label as expected

```
resources:
  ...
  requests:
    ...
    nvidia.com/SOMETHING: "1"
```

but the NVIDIA exporter, as you mentioned, only cares about resources named exactly `nvidia.com/gpu` or prefixed with `nvidia.com/mig-`. In the "GPU bound directly to a pod" you mentioned it's working, what is the GPU device name you are using?

example:
https://github.com/machadovilaca/kubevirt/blob/test-nvidia-dcgm-exporter/tests/monitoring/gpu.go

**Comment by rokkiter** [comment]
Thanks so much for focusing on this! Here's the yaml for kubevirt binding to the gpu.
```
  Limits:
      ...
      nvidia.com/GP104GL_TESLA_P4:    1
    Requests:
      ...
      nvidia.com/GP104GL_TESLA_P4:    1
```
Yes, kubevirt passes through the device name completely, but this approach creates a conflict with NVIDIA's GPU monitoring, and I'd like to explore if there's a suitable way to resolve this issue.
I can think of two solutions at the moment
1. Push DCMG EXPORT to develop a more compatible specification for pods that need to expose GPU metrics, such as judging navidia.com/gpu-prefix, instead of mandating navidia.com/gpu, of course, in this case, kubevirt needs to be adapted as well, but the GPU device name can be retained.
2. Adjust kubevirt to change the podresource name to nvidia.com/gpu, of course, you need to consider whether there will be any other impacts, I don't know much about this at the moment.

**Comment by rokkiter** [comment]
Thanks so much for focusing on this! Here's the yaml for kubevirt binding to the gpu.
I don't need to specify which GPU card to use when binding the GPU directly to the pod. I only need to focus on the number of GPUs bound to the pod, which will be handled by the GPU Opreator, so I just need to configure it as follows
```
  resources:
          requests:
            ...
            nvidia.com/gpu: 1 
          limits:
            ...
            nvidia.com/gpu: 1 
```
If I set the deviceName to nvidia.com/gpu in kubevirt's passthrough mode I could theoretically achieve monitoring, but that doesn't seem very reasonable. And there's no way for the user to realize that this is needed to make the GPUs bound to the kubevirt luancher pod available for monitoring.
I would prefer that the kubevirt luancher pod set the podResource Name to nvidia.com/gpu if it is bound to a Navid GPU.
Of course, a better solution would be to push DCMG Export to change the policy of forcing matching nvidia.com/gpu to instead match the nvidia.com/gpu-prefix as the policy.

**Comment by machadovilaca** [comment]
Why is it not reasonable? Per my understanding, if you request a specific GPU for the pod, you also won't have NVIDIA monitoring there.

If you ask KubeVirt to request a specific `nvidia.com/SOMETHING` GPU to the VM, I don't think it makes sense for KubeVirt to decide "we don't care which GPU, let's just request `nvidia.com/gpu: 1`".

**Comment by rokkiter** [comment]
I think you're right.
 
it's not practical to try to fix this in kubevirt. I have some GPU cards mounted in my cluster and from ```kubectl describe node``` I can get the following information.

```
Allocated resources:
  (Total limits may be over 100 percent, i.e., overcommitted.)
  Resource                       Requests           Limits
  --------                       --------           ------
  ...
  nvidia.com/GP104GL_TESLA_P4    2                  2
  nvidia.com/GRID_P4-1Q          0                  0
  nvidia.com/GRID_P4-4Q          0                  0
```
if request ``` nvidia.com/gpu: "1"``` , This is not recognized by k8s and the vm can not been created success.

This appears to be because the DCGM Exporter strictly follows the k8s specification for determining GPU resource. refer [k8s device plugin](https://kubernetes.io/zh-cn/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/#device-plugin-registration), 
> The ResourceName it wants to advertise. Here ResourceName needs to follow the [extended resource naming scheme](https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/#extended-resources) as vendor-domain/resourcetype. (For example, an NVIDIA GPU is advertised as nvidia.com/gpu.)

This issue is better suited for upstream discussion, and I'll probably cite this issue as a practical example of what I'm looking for.

Thanks for the help provided!
