### ISSUE TITLE
Talos k8s cluster: Create a VM failed calling webhook "virtualmachines-mutator.kubevirt.io"

### ISSUE THREAD

**Issue by Rammurthy5** [kubevirt/kubevirt#11669]
<img width="501" alt="Screenshot 2024-04-09 at 10 54 32" src="https://github.com/kubevirt/kubevirt/assets/39217224/e81a59ea-3033-4835-82fe-d05b9fbe3836">

**What happened**:
when i try `kubectl apply -f https://kubevirt.io/labs/manifests/vm.yaml`
I get error as below,

Error from server (InternalError): error when creating "https://kubevirt.io/labs/manifests/vm.yaml": Internal error occurred: failed calling webhook "virtualmachines-mutator.kubevirt.io": failed to call webhook: Post "https://virt-api.kubevirt.svc:443/virtualmachines-mutate?timeout=10s": context deadline exceeded

**What you expected to happen**:
virtualmachine.kubevirt.io "testvm" created
  virtualmachineinstancepreset.kubevirt.io "small" created

**How to reproduce it (as minimally and precisely as possible)**:
create a [talos](https://www.talos.dev/v1.6/talos-guides/install/cloud-platforms/aws/#configure-the-load-balancer) cluster with cilium CNI installed and OpenEBS for storage.

**Environment**:
- KubeVirt version (use `virtctl version`): v1.2.0
- Kubernetes version (use `kubectl version`): v1.28.0
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: Talos Linux on AWS ec2
- OS (e.g. from /etc/os-release): Talos Linux v1.5.5
- Kernel (e.g. `uname -a`): Linux
- Install tools: Cilium CNI, OpenEBS for storage
- Others: N/A

**Comment by fabiand** [comment]
@smira @andrewrynhard is there anybody from your side who has an idea?

**Comment by xpivarc** [comment]
> This has nothing to do with Talos or kubevirt most probably, but webhooks don't work, so it should be CNI or networking in general

I agree, this looks like CNI issue. Is any other webhook working?
