### ISSUE TITLE
 Can the vm copy started through VirtualMachinePool have a fixed access method like the sts pod with a headless service? For example xxx-0.headlesssvc.ns.svc.cluster.local

### ISSUE THREAD

**Issue by qzytwway** [kubevirt/kubevirt#11674]
Can the vm copy started through VirtualMachinePool have a fixed access method like the sts pod with a headless service? For example xxx-0.headlesssvc.ns.svc.cluster.local

**Comment by fabiand** [comment]
How do you you create headless services for STS?
Did you try the same for VMPools?
