### ISSUE TITLE
Upgrading the pod of the virtual launcher should not affect the virtual machine

### ISSUE THREAD

**Issue by matthewei** [kubevirt/kubevirt#11679]
**Is your feature request related to a problem? Please describe**:
Now, there are already thousands of virtual machines in our environment. Most of these virtual machines already carry workload.
if we upgraded kubevirt we have to shutdown the vm in order to upgrade the virt-launcer-pod. But in fact that we can't do it.

**Describe the solution you'd like**:
As the title described that if we upgrade the pod of the `virtual launcher pod `should not affect the virtual machine.

**Describe alternatives you've considered**:
We should separate the code that controls the lifecycle of the virtual machine from other code, and use sidecars or other forms of code to reduce the impact of upgrades on the virtual machine

**Additional context**:

**Comment by fabiand** [comment]
Please provide `kubectl get -o yaml vm $THEVM`

In general KubeVirt does not interrupt VMs during upgrades if it can.
Some causes - such as local storage - however prevent a VM from migration in order to upgrade and this will lead to the VM being restarted.

**Comment by matthewei** [comment]
> Please provide `kubectl get -o yaml vm $THEVM`
> 
> In general KubeVirt does not interrupt VMs during upgrades if it can. Some causes - such as local storage - however prevent a VM from migration in order to upgrade and this will lead to the VM being restarted.

I mean the virt-launcher-pod need to be upgraded in order to update it's code. The yaml file is kubevirt's example.

**Comment by fabiand** [comment]
Yes. And the VM yaml defines if a VM can migrate or not.
If the VM can migrate, then kubevirt will update the lanucher pod by migration, if it can not, then it wil update the launcher pod evenually by restarting the vm.

**Comment by matthewei** [comment]
yes, so I think we should separate the code that controls the lifecycle of the virtual machine from other code, and use sidecars or other way to reduce the impact of upgrades on the virtual machine

**Comment by matthewei** [comment]
> yes, so I think we should separate the code that controls the lifecycle of the virtual machine from other code, and use sidecars or other way to reduce the impact of upgrades on the virtual machine

yes, so I think we should separate the code that controls the lifecycle of the virtual machine from other code, and use sidecars or other way to reduce the impact of upgrades on the virtual machine

**Comment by matthewei** [comment]
Such as monitoring the virtual machine's code should be separated from virt-launcher-pod

**Comment by EdDev** [comment]
The VM runs in a Pod. I am not familiar with any existing Kubernetes method that can replace the binary executed by a pod while it is running.

The VM migration is the method we use today to perform such an upgrade without disruption.
Perhaps you should explain why migration is not an option for your setup.

**Comment by matthewei** [comment]
> The VM runs in a Pod. I am not familiar with any existing Kubernetes method that can replace the binary executed by a pod while it is running.
> 
> The VM migration is the method we use today to perform such an upgrade without disruption. Perhaps you should explain why migration is not an option for your setup.

yes, In fact that we can also use live-migragte to update `virt-launcher-pod` 's image.  As the number of VMs grows, live migration is not only more resource intensive, but can also be time consuming.

**Comment by xpivarc** [comment]
/close
Note that you can opt out of automatic updates of the virt-launcher. Closing as we don't see any way around this but we are more than happy to reopen if anyone comes up with any idea.
