### ISSUE TITLE
KubeVirt Delete Virtual Machine returns type `VirtualMachine` not `Status`

### ISSUE THREAD

**Issue by drewmullen** [kubevirt/kubevirt#11686]
**Describe the bug**

The delete vm action response is documented as `"#/definitions/k8s.io.apimachinery.pkg.apis.meta.v1.Status"`

https://github.com/kubevirt/kubevirt/blob/a45511415923f6efa74036d8247fa723502cb965/api/openapi-spec/swagger.json#L6265

However, what comes back from the API is 

```json
{
    "apiVersion": "kubevirt.io/v1",
    "items": [...],
    "kind": "VirtualMachine",
}
```

**Expected behavior**

Docs should match output from the API

Note that `Status` does seem to come back if the delete fails

**Comment by drewmullen** [comment]
@rmohr I see you have at least touched the openapispec generation code... any chance you can confirm this? If you can point me in the right direction i would be open to providing a PR

**Comment by drewmullen** [comment]
@aburdenthehand @vladikr This appears to be a systemic problem with the doc generator. All `delete` APIs reply with status which is not accurate

**Comment by rmohr** [comment]
Hey, is the swagger doc correct for OSS kubernetes where they use CRDs?

**Comment by drewmullen** [comment]
I think the difference is based on the api definition:
- `io.k8s.apimachinery` returns `status`
- `io.k8s.api.core` returns solid types

**Comment by drewmullen** [comment]
I have been able to confirm that at least `configmap` does in fact return `status` (not inaccurate)

```shell
curl -X DELETE \
  https://<>/api/v1/namespaces/default/configmaps/test \
  -H "Authorization: Bearer <>" \
  -H "Accept: application/json" \
  --cacert ./ca.crt
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Success",
  "details": {
    "name": "test",
    "kind": "configmaps",
    "uid": "0da42d82-7b74-41d8-9de8-00e6bf4502d9"
  }
}
```

What would help you confirm @rmohr ? since the k8s/k8s doesnt implement vm its hard for me to know how to confirm this is on their end
