### ISSUE TITLE
conformance multiarch image manifest is broken - amd part points to arm build

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#11702]
**What happened**:
With KubeVirt 1.0+, some of the containers are now built with aarch64 instead of amd64. conformance:v1.0.0 image built from https://github.com/kubevirt/kubevirt/blob/94006f89ac20340566a6a1aa9989f217d38b4e1e/tests/BUILD.bazel#L75 contains aarch64 executable. To get amd64, you need to pull conformance:v1.0.0-amd64 explicitly.

![Screenshot from 2024-04-15 14-42-00](https://github.com/kubevirt/kubevirt/assets/809335/a2e07eda-1841-4d58-bb92-ef4b8eeeb5e1)

**What you expected to happen**:
Conformance multiarch image manifest should be correct, as is the case for i.e. virt-controller+

![image](https://github.com/kubevirt/kubevirt/assets/809335/966a1678-05f3-404e-92ba-0348c70f7469)

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by dhiller** [comment]
@zhlhahaha hey, I remember you were working on that multiarch build, would you have time to look into this?

**Comment by zhlhahaha** [comment]
Hi, Daniel, I have checked the https://quay.io/repository/kubevirt/conformance?tab=tags, and can see there are some issues. I will take a look this issue.
