### ISSUE TITLE
Add the VM CRD to the release artifacts

### ISSUE THREAD

**Issue by ezrasilvera** [kubevirt/kubevirt#11732]
There are cases in which we want to create and manage VM objects on clusters on which KubeVirt is not installed. This is used for example for remote management of KubeVirt clusters. And example of such use case can be seen here: https://medium.com/@ezrasilvera/ca2ee43cb2a0 .

For such scenarios we need an easy way to get the VM CRD. Currently we need to clone the repository and build the CRD 
```
git clone https://github.com/kubevirt/kubevirt 
cd kubevirt
go install sigs.k8s.io/controller-tools/cmd/controller-gen@v0.13.0 
controller-gen crd:allowDangerousTypes=true paths=./staging/src/kubevirt.io/api/core/v1/…
```
**Proposal**
I can suggest two options:
1. Add to the generated CRD to the KubeVirt repo (e.g., under  config/crd/kubevirt.io_virtualmachines.yaml)
2. Add the generated CRD to the release artifacts similar to the KubeVirt operator

**Comment by a180285** [comment]
+1, Other language client will be easy to build k8s client base on the released CRD.
