### ISSUE TITLE
k8s v1.25.16 + kubevirt v1.2.0 start vm with error message "{"component":"virt-launcher-monitor","level":"error","msg":"failed to run virt-launcher","pos":"virt-launcher-monitor.go:181","reason":"fork/exec /usr/bin/virt-launcher: operation not permitted","timestamp":"2024-04-18T12:20:11.433951Z"}"

### ISSUE THREAD

**Issue by wingying** [kubevirt/kubevirt#11747]
**What happened**:
In k8s v1.25.16, install kubevirt v1.2.0, start a simply vm 
https://kubevirt.io/labs/manifests/vm.yaml
get error message, and vm did not run.

**Additional context**:
full error message:
### Logs for virt-launcher-testvm-cbvp4, namespace default, docker container 6a75c49fbc148dd7a7d00021a25db286fdf3f6075d71b463557a3cec279c61b7 ###
**{"component":"virt-launcher-monitor","level":"error","msg":"failed to run virt-launcher","pos":"virt-launcher-monitor.go:181","reason":"fork/exec /usr/bin/virt-launcher: operation not permitted","timestamp":"2024-04-18T12:20:11.433951Z"}**
{"component":"virt-launcher-monitor","level":"error","msg":"could not delete serial console term file","pos":"virt-launcher-monitor.go:107","reason":"open /var/run/kubevirt-private/73072acf-e9c7-42ce-9aaa-646f2ff21887/virt-serial0-log-sigTerm-done: no such file or directory","timestamp":"2024-04-18T12:20:19.236549Z"}
{"component":"virt-launcher-monitor","level":"error","msg":"monitoring virt-launcher failed","pos":"virt-launcher-monitor.go:142","reason":"fork/exec /usr/bin/virt-launcher: operation not permitted","timestamp":"2024-04-18T12:20:19.236599Z"}
### Logs for virt-launcher-testvm-cbvp4, namespace default, docker container d54cee7a406f67ca5f47082af77ba44881ea0dca0c54038b50056e17efed7e9b ###
Thu Apr 18 12:20:19 2024
error: socket /var/run/kubevirt-ephemeral-disks/container-disk-data/73072acf-e9c7-42ce-9aaa-646f2ff21887/disk_0.sock does not exist anymore

**Environment**:
- KubeVirt version (use `virtctl version`): 
Client Version: version.Info{GitVersion:"v1.2.0", GitCommit:"f26e45d99ac35743fc33d6a121b629e9a9af6b63", GitTreeState:"clean", BuildDate:"2024-03-05T20:34:24Z", GoVersion:"go1.21.5 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v1.2.0", GitCommit:"f26e45d99ac35743fc33d6a121b629e9a9af6b63", GitTreeState:"clean", BuildDate:"2024-03-05T21:32:21Z", GoVersion:"go1.21.5 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.16", GitCommit:"c5f43560a4f98f2af3743a59299fb79f07924373", GitTreeState:"clean", BuildDate:"2023-11-15T22:39:12Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}
Kustomize Version: v4.5.7
Server Version: version.Info{Major:"1", Minor:"25", GitVersion:"v1.25.16", GitCommit:"c5f43560a4f98f2af3743a59299fb79f07924373", GitTreeState:"clean", BuildDate:"2023-11-15T22:28:05Z", GoVersion:"go1.20.10", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from /etc/os-release): 
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

- Kernel (e.g. `uname -a`): 
Linux cdp 6.1.0-18-amd64 #1 SMP PREEMPT_DYNAMIC Debian 6.1.76-1 (2024-02-01) x86_64 GNU/Linux

- Others:
virtualized supported.
  QEMU: Checking for hardware virtualization                                 : PASS
  QEMU: Checking if device /dev/kvm exists                                   : PASS
  QEMU: Checking if device /dev/kvm is accessible                            : PASS
  QEMU: Checking if device /dev/vhost-net exists                             : PASS
  QEMU: Checking if device /dev/net/tun exists                               : PASS
  QEMU: Checking for cgroup 'cpu' controller support                         : PASS
  QEMU: Checking for cgroup 'cpuacct' controller support                     : PASS
  QEMU: Checking for cgroup 'cpuset' controller support                      : PASS
  QEMU: Checking for cgroup 'memory' controller support                      : PASS
  QEMU: Checking for cgroup 'devices' controller support                     : PASS
  QEMU: Checking for cgroup 'blkio' controller support                       : PASS
  QEMU: Checking for device assignment IOMMU support                         : PASS
  QEMU: Checking if IOMMU is enabled by kernel                               : PASS
  QEMU: Checking for secure guest support                                    : WARN (Unknown if this platform has Secure Guest support)

**Comment by xpivarc** [comment]
/close
Supported Kubernetes versions are https://github.com/kubevirt/sig-release/blob/main/releases/k8s-support-matrix.md.
Your issue is most likely related to default Seccomp of your runtime. Please upgrade if you are using Docker.

**Comment by wingying** [comment]
@xpivarc I tested kubevirt v1.1.1 on k8s v1.25.16, it works. BTW, we use Docker version is 24.0.7

Could you kindly try to explain why kubevirt v1.1.1 works but  kubevirt v1.2.0 not work?
