### ISSUE TITLE
Add Compatibility matrix

### ISSUE THREAD

**Issue by smyja** [kubevirt/kubevirt#11767]
**Description**:
Add a compatibility matrix showing the minimum and maximum supported kubernetes version for kubevirt, most cncf projects have it.

**Comment by brianmcarey** [comment]
There is a support matrix here: https://github.com/kubevirt/sig-release/blob/main/releases/k8s-support-matrix.md

@aburdenthehand maybe we need to link to it from the main README?

**Comment by smyja** [comment]
Thanks

**Comment by aburdenthehand** [comment]
Good idea. We can also point to the upcoming changes and our release schedule.

**Comment by aburdenthehand** [comment]
With #11769 this content is now linked to in the kubevirt/kubevirt README to be more visible.
Thanks for opening an issue!
