### ISSUE TITLE
virtctl console  hang all the time

### ISSUE THREAD

**Issue by CharlesQQ** [kubevirt/kubevirt#11792]
**What happened**:
After vm running more than 30 days, command  virtctl console hang all the time

![image](https://github.com/kubevirt/kubevirt/assets/18431718/9da21edd-005c-4900-beb4-b06698a75aee)

**What you expected to happen**:
hope virtctl console can login to vm 

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`):  v1.0.1
- Kubernetes version (use `kubectl version`): v1.23.17
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by alicefr** [comment]
@CharlesQQ have you tried to connect to vnc?Like `virtctl vnc <vm>`. Could be that your VM haven't booted correctly

**Comment by CharlesQQ** [comment]
> Could be that your VM haven't booted correctly

But I can login via ssh

**Comment by victortoso** [comment]
Without more information is a hard guess. Could be a problem in virtctl's AttachConsole, in virt-handler's bridge between websocket and unix socket and QEMU itself.

Does it happen consistently after long periods or do you have a simple/quicker way to reproduce it?
It would be lovely to have [kubevirt.io/libvirt-log-filters](https://kubevirt.io/user-guide/debug_virt_stack/logging/) annotation set which would help on host side, but setting now would need long time to reproduce.

Do you happen to have virt-handler logs available?  The interesting part is to see if something shows when console is hanging.

**Comment by phuongl-ampere** [comment]
i have the same issue.
