### ISSUE TITLE
hotplugVolume cannot be created？？？

### ISSUE THREAD

**Issue by wenjunGU** [kubevirt/kubevirt#11801]
The version of kubevirt I installed is 0.58.0，I have enabled HotplugVolumes in kubevirt-cr，After I run virtctl addvolume hot strip volume, check the volume status in vmi as follows:

- hotplugVolume:
      attachPodName: hp-volume-gsbmv
      attachPodUID: 0aef680e-be09-428d-8ccf-c70748b3e32c
    message: Created hotplug attachment pod hp-volume-gsbmv, for volume hp-volume-07
    name: hp-volume-07
    persistentVolumeClaimInfo:
      accessModes:
      - ReadWriteOnce
      capacity:
        storage: 80Gi
      filesystemOverhead: "0.055"
      requests:
        storage: 80Gi
      volumeMode: Filesystem
    phase: AttachedToNode
    reason: SuccessfulCreate
    target: ""

The condition of the pvc is completely normal：

NAME           STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
hp-volume-01   Bound    pvc-b21c1152-17df-4660-8cab-1198128fff30   80Gi       RWO            csi-rbd-sc     54m

When I view the logs of virt-operator, I find the following log content：

{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"d375e247-b55a-4f65-9f39-eb109e9d474c","namespace":"ns-test-tfrt5cf5","pos":"vm.go:1781","reason":"failed to mount filesystem hotplug volume hp-volume-01: lstat /proc/1/root/var/lib/kubelet/plugins/kubernetes.io/csi/pv/pvc-b21c1152-17df-4660-8cab-1198128fff30/globalmount/0001-0024-e088b034-eced-11ee-b566-3ce824817508-0000000000000006-e1c7a9c5-5ede-42b2-809d-035fa9772e4d/disk.img: no such file or directory","timestamp":"2024-04-26T09:12:56.016345Z","uid":"c4a9f539-49ab-4586-9ac8-205b9fea9fa0"}

I found this directory on the associated node, and I found that the newly created pvc directory has the permission drwxr-x--, while the directly created pvc has the permission 777, is this related? In addition, my manual reauthorization to 777 is invalid

drwxr-x--- 3 root root 4096 Apr 26 16:41 pvc-1711ea21-d55c-4a4c-8e05-f8a91859f945

Is this a Bug? How can I fix it

**Comment by aburdenthehand** [comment]
Hi @wenjunGU 
Version 0.58 is quite old now and not supported (you can see our [support matrix here](https://github.com/kubevirt/sig-release/blob/main/releases/k8s-support-matrix.md))
Are you able to update to a supported version of KubeVirt? Also what is the underlying k8s cluster version?

**Comment by wenjunGU** [comment]
@aburdenthehand Thanks, I've already resolved that to use DataVolume instead of PersistentVolumeClaim
