### ISSUE TITLE
sidecar does not build out of tree

### ISSUE THREAD

**Issue by aep** [kubevirt/kubevirt#11817]
the sidecar example https://github.com/kubevirt/kubevirt/blob/main/cmd/sidecars/smbios/smbios.go
does not build when pulled out of tree.

```
go mod tidy
go: finding module for package kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/api
go: found kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/api in kubevirt.io/kubevirt v1.2.0
go: github.com/openshift/api@v0.0.0: reading github.com/openshift/api/go.mod at revision v0.0.0: unknown revision v0.0.0

```

there is a nice https://github.com/kubevirt/api package that would work just fine,
but its missing the `virt-launcher/virtwrap/api`

so currently to implement a sidecar, you need to fork kubevirt itself

**Comment by aep** [comment]
actually the sidecar doesnt even work in tree.
the args in the [example deployment](https://github.com/kubevirt/kubevirt/blob/main/examples/vmi-with-sidecar-hook.yaml)  dont match the pflags in the code.
and the example just dies with `hooksidecar2024/04/29 Bad input vmi=0, domain=0`  presumably because the interface has changed but its undocumented

**Comment by victortoso** [comment]
The current usage of `kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/api` is only related to `schema.go` which means it can be replaced by `libvirtxml`, which is actually preferred. I'm working on doing that from virt-launcher side already too.

somewhat related: https://github.com/kubevirt/kubevirt/issues/10844
/assign
