### ISSUE TITLE
why /usr/bin/virt-launcher-monitor require additional file capability "cap_net_bind_service"?

### ISSUE THREAD

**Issue by wingying** [kubevirt/kubevirt#11812]
Hi,

Could you help explain why /usr/bin/virt-launcher-monitor  require additional file capability "cap_net_bind_service"? I would like to know more details about how /usr/bin/virt-launcher-monitor works.

is it really binding port lower 1024?

Thank you.

**Comment by xpivarc** [comment]
The monitor actually doesn't use the capability nor it has it but the the `virt-launcher` binary does. The uses are dhcp, slirp and maybe others that I don't recall right now.
