### ISSUE TITLE
Report the use of components with vulnerabilities in kubevirt

### ISSUE THREAD

**Issue by HouqiyuA** [kubevirt/kubevirt#11868]
Dear Team Members:
Greetings! Our team is very interested in your project. we performed source code perspective security analysis (SCA) and vulnerability library association analysis on this project and found that components with vulnerabilities are still being used into this project.We would like to report this issue to you,so that you can fix and improve it accordingly. I add the details in json file below. Please confirm whether this problem really exists and confirm with us. Looking forward to hearing from you and discussing more details with us, thank you very much for your time and attention.

Note: Each "affect_components" field in the report represents the vulnerable component introduced by this project. The other is the vulnerability information associated with it.

Qiyu Hou

[kubevirt-main_report.json](https://github.com/kubevirt/kubevirt/files/15246402/kubevirt-main_report.json)

**Comment by HouqiyuA** [comment]
I'm sorry. I don't understand what that means.

aburdenthehand ***@***.***> 于2024年5月8日周三 22:29写道：

**Comment by aburdenthehand** [comment]
@HouqiyuA Sorry, that is just me tagging one of our project maintainers so that they are aware of this issue and can track it. Thank you for raising this!

**Comment by lyarwood** [comment]
Does https://github.com/kubevirt/kubevirt/pull/11840 address this?
