### ISSUE TITLE
virt-launcher pod in crashingbackoff state in kernel versions < 4.11

### ISSUE THREAD

**Issue by Muyan0828** [kubevirt/kubevirt#11886]
**What happened**:
virt-launcher pod crash

**What you expected to happen**:
virt-launcher pod 

**How to reproduce it (as minimally and precisely as possible)**:
create a vm

**Additional context**:
virt-handler log:
```
{"component":"virt-handler","kind":"","level":"info","msg":"mounting kernel artifacts","name":"gpool1-1","namespace":"sy-vg","pos":"mount.go:429","timestamp":"2024-05-09T15:41:11.006779Z","uid":"1f7a2138-c189-44ed-bd6c-edbe65125f62"}
{"component":"virt-handler","kind":"","level":"info","msg":"kernel boot not defined - nothing to mount","name":"gpool1-1","namespace":"sy-vg","pos":"mount.go:432","timestamp":"2024-05-09T15:41:11.006839Z","uid":"1f7a2138-c189-44ed-bd6c-edbe65125f62"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"gpool1-1","namespace":"sy-vg","pos":"vm.go:2002","reason":"failed to configure vmi network: setup failed, err: open /proc/sys/net/ipv4/ip_unprivileged_port_start: no such file or directory","timestamp":"2024-05-09T15:41:11.009452Z","uid":"1f7a2138-c189-44ed-bd6c-edbe65125f62"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance sy-vg/gpool1-1","pos":"vm.go:1673","reason":"failed to configure vmi network: setup failed, err: open /proc/sys/net/ipv4/ip_unprivileged_port_start: no such file or directory","timestamp":"2024-05-09T15:41:11.085940Z"}
```

**Environment**:
- KubeVirt version (use `virtctl version`): v1.2.0
- Kubernetes version (use `kubectl version`): v1.28.8
- VM or VMI specifications: 
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-1160.el7.x86_64 1 SMP Mon Oct 19 16:18:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: N/A
- Others: N/A

**Comment by victortoso** [comment]
jfyi @EdDev

**Comment by EdDev** [comment]
CentOS 7 kernel is way too old, I would be surprised to see this being the only problem.

We use this parameter in one of the supported bindings, therefore I am unsure if we can tolerate it being missing.

I can try and check if we can be more tolerable to such things.

**Comment by victortoso** [comment]
CentOS 7 eol is [just around the corner](https://www.redhat.com/en/topics/linux/centos-linux-eol) as well.

I know KubeVirt tries to work well with different host OSes but do we have some written hard requirements for KubeVirt to function properly? From the [installation](https://kubevirt.io/user-guide/operations/installation/) guide centos 7 might be okay for example, but it isn't the case if components crash due lack of system's capabilities

**Comment by victortoso** [comment]
Perhaps we could have a `kubevirt-validate-host` where we check key features?

**Comment by EdDev** [comment]
In practice, we support only what we test.
Per what I know, we only test CentOS Stream.

Anything else is best-effort.

**Comment by scydas** [comment]
<p dir="auto" style="box-sizing: border-box; margin-top: 0px !important; margin-bottom: var(--base-size-16); color: rgb(31, 35, 40); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">What is the minimum kernel version?<br style="box-sizing: border-box;">At kubevirt 1.2.0 I tested several versions of the kernel<br style="box-sizing: border-box;"></p><div dir="auto" style="box-sizing: border-box; color: rgb(31, 35, 40); font-family: -apple-system, &quot;system-ui&quot;, &quot;Segoe UI&quot;, &quot;Noto Sans&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; white-space: normal; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div dir="auto" style="box-sizing: border-box;"><p dir="auto" style="box-sizing: border-box; margin-top: 0px; margin-bottom: var(--base-size-16);"></p><markdown-accessiblity-table data-catalyst="" style="box-sizing: border-box; display: block;">
kernel | 3.10 | 3.15 | 4.4.5 | 4.14.15 | 4.16.9 | 4.17.14 | 4.18.16 | 5.4.15
-- | -- | -- | -- | -- | -- | -- | -- | --
vm | false | false | false | false | false | true | true | true

</markdown-accessiblity-table></div></div>
