### ISSUE TITLE
The value set by `Filesystem Overhead` does not take effect

### ISSUE THREAD

**Issue by silenceper** [kubevirt/kubevirt#11888]
**What happened**:

<img width="515" alt="image" src="https://github.com/kubevirt/kubevirt/assets/2044558/49782465-2b6e-4d85-b8e8-4d3e1de418ff">

<img width="666" alt="image" src="https://github.com/kubevirt/kubevirt/assets/2044558/28f4a7cd-b308-461e-ba44-568cd42becea">

**What you expected to happen**:
I think the virtual size of this img file should be less than 200G;

In addition, I verified that this overhead parameter will only take effect during resize, and will not take effect for the initial creation.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): 1.1.1
- Kubernetes version (use `kubectl version`): 1.24
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by xpivarc** [comment]
@akalenyu can you have a look?

**Comment by silenceper** [comment]
Please confirm whether this is a bug or a design flaw; if it is confirmed to be a bug, I can submit a PR to fix it.

@xpivarc @akalenyu

**Comment by akalenyu** [comment]
Hey! How are you populating the PVC with a disk image?
If created through the DataVolume resource, [CDI](https://github.com/kubevirt/containerized-data-importer/blob/dcc3921a35a26f348de7c811ff26b0f4a0fe5429/doc/cdi-config.md?plain=1#L15) will orchestrate the overhead reservation

**Comment by silenceper** [comment]
@akalenyu Some empty data disks are not generated through DataVolume

**Comment by akalenyu** [comment]
> @akalenyu Some empty data disks are not generated through DataVolume

Interesting, I see the name for this disk is "datavolumedisk1"

**Comment by silenceper** [comment]
@akalenyu  It's just a name, because he is an ordinary pvc

**Comment by akalenyu** [comment]
> @akalenyu It's just a name, because he is an ordinary pvc

Right so Filesystem overhead is a CDI feature and thus will not take effect without usage
of CDI. What's on this PVC? Have you considered creating a blank disk?
https://github.com/kubevirt/containerized-data-importer/blob/main/doc/datavolumes.md#blank-data-volume
