### ISSUE TITLE
V1.3 is no need passt any more? 

### ISSUE THREAD

**Issue by caijian76** [kubevirt/kubevirt#11896]
ubuntu22.04 x86
k8s v1.28.9 with cilium CNI  AND k8s v1.25.9 with calico CNI 

I found that when I created a VM, without using any network configuration and without open any feature gate(like https://github.com/kubevirt/kubevirt/blob/main/examples/vm-cirros.yaml ), its network behaved as if it had used the passt network configuration, the VM correctly used the same IP address of the pod, and can export VM port to nodeport using k8s service. Is this a new feature? What is the difference with passt?
![image](https://github.com/kubevirt/kubevirt/assets/24736690/205baa16-9d71-4711-91d6-bc9cd76f29ec)
![image](https://github.com/kubevirt/kubevirt/assets/24736690/f253a164-b775-4333-9fa9-b064319bbf2e)

Can pass the test using nc listen and connect in 2 VM with any port.

**Comment by sbrivio-rh** [comment]
@caijian76 thanks for tagging me on #11591 -- please tag me directly on the right issue next time. :) I don't exactly remember how the other bindings (bridge, masquerade) look like. I don't see an IPv6 global unicast address here so, assuming it's available on your setup, it doesn't look like passt to me.

@AlonaKaplan, @EdDev, any pointer?

**Comment by EdDev** [comment]
If no network interfaces are defined and no Kubevirt CR config is specified, bridge binding is used by default. You can examine the VMI manifest to see it.

**Comment by caijian76** [comment]
@EdDev Doesn't look like a bridging network，VM's IP same as pod ,and This IP address can be used to communicate with the virtual machine，The current network is more reminiscent of the passt.

**Comment by EdDev** [comment]
Bridge binding passes the IP from the pod to the guest. I specified how to check it in my prev message.

**Comment by sbrivio-rh** [comment]
@caijian76, see also the table here: https://kubevirt.io/user-guide/virtual_machines/interfaces_and_networks/#passt

**Comment by caijian76** [comment]
@EdDev @sbrivio-rh   ok , get it . THK
