### ISSUE TITLE
HotplugVolumes Specified drive letter？？？

### ISSUE THREAD

**Issue by wenjunGU** [kubevirt/kubevirt#11936]
When I installed wield0.58.0 of kubevirt, I used virtctl addvolume to mount several data drives, and I found that after the vm restarted, the drive letters of these data drives were scrambled, resulting in data confusion. How can I solve this problem? Or specify the drive letter when adding volume?

**Comment by fabiand** [comment]
Assign serial numbers to the drives via the VM definition and rely on them.

**Comment by awels** [comment]
As Fabian said the only reliable mechanism in identifying the virtual disks is assigning a serial id and using that to locate the disk. There is no mechanism for assigning disk letters since that is a windows specific thing.

**Comment by wenjunGU** [comment]
@fabiand @awels In our current business environment, most machines are mounted using drive letters, and uuid usage is rare. If there is really no other way, we may need to change the usage scenario

**Comment by fabiand** [comment]
It is for sure the safest way.

**Comment by fabiand** [comment]
For windows, tools like forklift are required in order to persist drive letters.

For linux, disks should be mounted using /dev/disk-by-uui and similar.
