### ISSUE TITLE
virtctl image-upload doesnt work either for dv or pvc

### ISSUE THREAD

**Issue by kvbhaskar** [kubevirt/kubevirt#11939]
**What happened**:

Trying first time with kubevirt in k8s environment with one node.
Able to create a kubevirt's lab1 vm and finish the exercise as expected
When I tried to do the 2nd lab exercise with fedora things are failing.
the instructions are missing to setup the storage class, while watching the video i see that i need to setup those.
Realized need to install some provisioner and installed rancher's provisioner.

kubectl apply -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/deploy/local-path-storage.yaml

Also experimented with the following yaml files to create the pvc and pod to make sure local-path storage works as expected.
 kubectl create -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/examples/pvc/pvc.yaml
 kubectl create -f https://raw.githubusercontent.com/rancher/local-path-provisioner/master/examples/pod/pod.yaml

after this tried to continue with lab2 experiment.. as part of it installed cdi.

kubectl get cdi cdi -n cdi
NAME   AGE   PHASE
cdi    28h   Deployed

kubectl get pods -n cdi
NAME                               READY   STATUS    RESTARTS   AGE
cdi-apiserver-75bb86c8c4-vzqdl     1/1     Running   0          28h
cdi-deployment-645dc8bc99-zg286    1/1     Running   0          28h
cdi-operator-67d655447d-9wl5k      1/1     Running   0          28h
cdi-uploadproxy-67f586465b-rwd6r   1/1     Running   0          28h

 kubectl create -f dv_fedora.yml
Error from server (InternalError): error when creating "dv_fedora.yml": Internal error occurred: failed calling webhook "datavolume-mutate.cdi.kubevirt.io": failed to call webhook: Post "https://cdi-api.cdi.svc:443/datavolume-mutate?timeout=30s": Service Unavailable

**What you expected to happen**:

upload the fedora image and allow me to continue with next steps.

**How to reproduce it (as minimally and precisely as possible)**:

Follow the steps in the lab2.
BTW, tried same experiment in the Killercoda and it works as expected.
there is something in my environment and getting the "Service Unavailable"

I dont have any network policies as well.

kubectl get networkpolicies -A
No resources found

Also tried with virtctl image upload as well, 
virtctl image-upload pvc fedora --image-path=./disk.img -access-mode=ReadWriteOnce --size=2Gi --insecure  --uploadproxy-url=https://10.107.62.110:443 --no-create --force-bind

Waiting for PVC fedora upload pod to be ready...
the server is currently unable to handle the request
timed out waiting for the condition

BTW the same works in the 
**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v1.2.0
- Kubernetes version (use `kubectl version`): 
         Client Version: v1.29.3
        Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
        Server Version: v1.29.3

- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: 
   Local 
- OS (e.g. from /etc/os-release): 

$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 20.04.6 LTS
Release:	20.04
Codename:	focal

- Kernel (e.g. `uname -a`): N/A
Linux xxxx-lab-aio 5.4.0-177-generic #197 SMP Thu Apr 25 20:12:18 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: N/A
- Others: N/A

**Comment by awels** [comment]
So from the error message it looks like the kubernetes API server cannot communicate with the CDI API server. I am assuming the mutating webhook is registered properly `kubectl get MutatingWebhookConfiguration -n cdi` Can you ssh into the node, and try curling the cdi api endpoint?

**Comment by kvbhaskar** [comment]
I  see the no_proxy was not set correctly to ignore cdi-api.cdi.svc, and the requests were going out.
