### ISSUE TITLE
Can't control the execution order of multiple hook sidecars

### ISSUE THREAD

**Issue by go-bai** [kubevirt/kubevirt#11940]
**What happened**:

I've noticed the **Priority** field in the response of the Info service, which can be used for sorting. However, currently, sortCallbacksPerHookPoint sorts based on the **HookPoint** rather than **callBackClient**.

**What you expected to happen**:
Sort callBackClients based on the Priority field of HookPoint.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v1.2.0
- Kubernetes version (use `kubectl version`): v1.29.3
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by victortoso** [comment]
Sadly, we don't have yet a written design proposal for what the expectations should be for the priority and sorting mechanism that are included there. Would you mind adding a paragraph as a comment to what the expectation should be in https://github.com/kubevirt/community/pull/252? As a comment itself is enough and we can have others to discuss it prior to taking #11941 in.

Thanks!

**Comment by EdDev** [comment]
I do not think we had any contract which allowed to control the hooks execution order.
If that is the case, then this is a request for enhancement and not a bug.

You can provide reasoning for requesting something like this. As a protocol, I find it problematic, mainly because there is more than one client in the project that uses it. Therefore, it will be misleading to a client to assume it can control which sidecar runs first/last.

**Comment by victortoso** [comment]
> Therefore, it will be misleading to a client to assume it can control which sidecar runs first/last.

Not if we come up with a way to do it and document it in the proposal. Hook sidecars are alpha and this request does sound reasonable.

**Comment by EdDev** [comment]
> > Therefore, it will be misleading to a client to assume it can control which sidecar runs first/last.
> 
> Not if we come up with a way to do it and document it in the proposal. Hook sidecars are alpha and this request does sound reasonable.

Sure, an attempt can be made to propose it.
But I do not see at the moment how it can accomplish a classic need.
There are examples for mechanisms that resemble this one which have no execution ordering (e.g. admission controllers webhooks).
