### ISSUE TITLE
VM fails to boot in nested environment with virtio disk (sometimes)

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1199]
In this thread https://groups.google.com/d/msg/kubevirt-dev/Yd4yJafM_9g/l06OHc5ACAAJ it was mentioned that sometimes a VM can not boot in a nested environment if the virtio disk bus type is used.

##### Version
v0.7.0-alpha.2

##### Steps To Reproduce
In a VM:
1. OS Ubuntu
2. Kubernetes 1.10
3. Launch VM with virtio bus

##### Actual Result
Fails to boot

##### Expected Result
Should boot

##### Additional Information
[consider attaching the output of `$ oc get pod/vm/vmi -o json -n <namespace>` command to the issue]
[visit https://kubevirt.io/user-guide/]

**Comment by nertpinx** [comment]
Unless there's more information to base this on, I have no idea where to start. How does it look? What do logs say?

**Comment by fabiand** [comment]
Closing this for now, please reopen if it's still an issue.

/close
