### ISSUE TITLE
How to get unit test coverage locally

### ISSUE THREAD

**Issue by Longchuanzheng** [kubevirt/kubevirt#12010]
**Is your feature request related to a problem? Please describe**:
I find kubevirt have `make coverage` command, while when I run it, I can't get the coverage result.

**Describe the solution you'd like**:
Get unit test coverage locally.

**Describe alternatives you've considered**:

**Additional context**:

**Comment by victortoso** [comment]
Going to a folder and running `go test -coverprofile cover.out` works fine here. So you can get local coverage of the place you want rather quickly.

The `make coverage` runs [coverage.sh](https://github.com/kubevirt/kubevirt/blob/main/hack/coverage.sh) which is a `bazel` command so the output is inside bazel. You can find it with `./hack/dockerized find /root/.cache/bazel -iname "coverage.dat"`

Now, we probably can argue that this should be in `_out` folder instead. I'd agree ;)

**Comment by Longchuanzheng** [comment]
> Going to a folder and running `go test -coverprofile cover.out` works fine here. So you can get local coverage of the place you want rather quickly.
> 
> The `make coverage` runs [coverage.sh](https://github.com/kubevirt/kubevirt/blob/main/hack/coverage.sh) which is a `bazel` command so the output is inside bazel. You can find it with `./hack/dockerized find /root/.cache/bazel -iname "coverage.dat"`
> 
> Now, we probably can argue that this should be in `_out` folder instead. I'd agree ;)

Thanks, I find "coverage.dat" file, while these files are generated respectively according to the package. I find we can use `genhtml`[coverage](https://bazel.build/configure/coverage) to produce a report that can be viewed in a web browser.

**Comment by xpivarc** [comment]
/close 
The issue seems to be resolved, please reopen if you think otherwise
