### ISSUE TITLE
kubevirt v1.1.0 code compile 

### ISSUE THREAD

**Issue by NonoMoh** [kubevirt/kubevirt#12050]
kubevirt v1.1.0
arm  docker 24.09

[root@localhost kubevirt]# make bazel-build-images
hack/dockerized "export BUILD_ARCH= && DOCKER_PREFIX=10.64.8.99:5000 DOCKER_TAG=v1.1.0 DOCKER_TAG_ALT= IMAGE_PREFIX= IMAGE_PREFIX_ALT= ./hack/multi-arch.sh build-images"
go version go1.22.2 linux/arm64

e3f504a6dbcc23560a57b1287e78db944fcbed19d535bd81dfa5b9502cc6f219
go version go1.22.2 linux/arm64
Sandbox is up to date
Another command holds the client lock:
pid=14
owner=client
cwd=/root/go/src/kubevirt.io/kubevirt

ERROR: /root/go/src/kubevirt.io/kubevirt/rpm/BUILD.bazel:209:10: Extracting files failed: (Exit 1): downloaded failed: error executing command external/bazeldnf-linux-arm64/file/downloaded tar2files --file-prefix /usr/lib64 --input bazel-out/aarch64-fastbuild/bin/rpm/libvirt-devel_aarch64.tar ... (remaining 98 arguments skipped)

Use --sandbox_debug to see verbose messages from the sandbox and retain the sandbox build root for debugging
Error: could not convert rpm at bazel-out/aarch64-fastbuild/bin/rpm/libvirt-devel_aarch64.tar: some files could not be found: map[libacl.so.1:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libacl.so.1 libacl.so.1.1.2301:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libacl.so.1.1.2301 libattr.so.1:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libattr.so.1 libattr.so.1.1.2501:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libattr.so.1.1.2501 libaudit.so.1:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libaudit.so.1 libaudit.so.1.0.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libaudit.so.1.0.0 libblkid.so.1:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libblkid.so.1 libblkid.so.1.1.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libblkid.so.1.1.0 libc.so.6:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libc.so.6 libcap-ng.so.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libcap-ng.so.0 libcap-ng.so.0.0.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libcap-ng.so.0.0.0 libcom_err.so.2:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libcom_err.so.2 libcom_err.so.2.1:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libcom_err.so.2.1 libcrypt.so.2:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libcrypt.so.2 libcrypt.so.2.0.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libcrypt.so.2.0.0 libcrypto.so.3:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libcrypto.so.3 libcrypto.so.3.0.7:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libcrypto.so.3.0.7 libcurl.so.4:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libcurl.so.4 libcurl.so.4.7.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libcurl.so.4.7.0 libffi.so.8:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libffi.so.8 libffi.so.8.1.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libffi.so.8.1.0 libgcc_s-11-20230605.so.1:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libgcc_s-11-20230605.so.1 libgcc_s.so.1:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libgcc_s.so.1 libgcrypt.so.20:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libgcrypt.so.20 libgcrypt.so.20.4.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libgcrypt.so.20.4.0 libgio-2.0.so.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libgio-2.0.so.0 libgio-2.0.so.0.6800.4:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libgio-2.0.so.0.6800.4 libglib-2.0.so.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libglib-2.0.so.0 libglib-2.0.so.0.6800.4:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libglib-2.0.so.0.6800.4 libgmodule-2.0.so.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libgmodule-2.0.so.0 libgmodule-2.0.so.0.6800.4:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libgmodule-2.0.so.0.6800.4 libgnutls.so.30:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libgnutls.so.30 libgnutls.so.30.33.1:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libgnutls.so.30.33.1 libgobject-2.0.so.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libgobject-2.0.so.0 libgobject-2.0.so.0.6800.4:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libgobject-2.0.so.0.6800.4 libgpg-error.so.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libgpg-error.so.0 libgpg-error.so.0.32.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libgpg-error.so.0.32.0 libgssapi_krb5.so.2:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libgssapi_krb5.so.2 libgssapi_krb5.so.2.2:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libgssapi_krb5.so.2.2 libhogweed.so.6:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libhogweed.so.6 libhogweed.so.6.5:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libhogweed.so.6.5 libidn2.so.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libidn2.so.0 libidn2.so.0.3.7:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libidn2.so.0.3.7 libk5crypto.so.3:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libk5crypto.so.3 libk5crypto.so.3.1:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libk5crypto.so.3.1 libkeyutils.so.1:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libkeyutils.so.1 libkeyutils.so.1.10:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libkeyutils.so.1.10 libkrb5.so.3:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libkrb5.so.3 libkrb5.so.3.3:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libkrb5.so.3.3 libkrb5support.so.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libkrb5support.so.0 libkrb5support.so.0.1:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libkrb5support.so.0.1 liblz4.so.1:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/liblz4.so.1 liblz4.so.1.9.3:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/liblz4.so.1.9.3 liblzma.so.5:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/liblzma.so.5 liblzma.so.5.2.5:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/liblzma.so.5.2.5 libm.so.6:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libm.so.6 libmount.so.1:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libmount.so.1 libmount.so.1.1.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libmount.so.1.1.0 libnettle.so.8:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libnettle.so.8 libnettle.so.8.5:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libnettle.so.8.5 libnghttp2.so.14:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libnghttp2.so.14 libnghttp2.so.14.20.1:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libnghttp2.so.14.20.1 libnl-3.so.200:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libnl-3.so.200 libnl-3.so.200.26.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libnl-3.so.200.26.0 libnuma.so.1:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libnuma.so.1 libnuma.so.1.0.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libnuma.so.1.0.0 libp11-kit.so.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libp11-kit.so.0 libp11-kit.so.0.3.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libp11-kit.so.0.3.0 libpcre.so.1:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libpcre.so.1 libpcre.so.1.2.12:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libpcre.so.1.2.12 libpcre2-8.so.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libpcre2-8.so.0 libpcre2-8.so.0.11.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libpcre2-8.so.0.11.0 libresolv.so.2:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libresolv.so.2 libsasl2.so.3:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libsasl2.so.3 libsasl2.so.3.0.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libsasl2.so.3.0.0 libselinux.so.1:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libselinux.so.1 libssh.so.4:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libssh.so.4 libssh.so.4.9.4:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libssh.so.4.9.4 libssl.so.3:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libssl.so.3 libssl.so.3.0.7:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libssl.so.3.0.7 libtasn1.so.6:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libtasn1.so.6 libtasn1.so.6.6.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libtasn1.so.6.6.0 libtirpc.so.3:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libtirpc.so.3 libtirpc.so.3.0.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libtirpc.so.3.0.0 libunistring.so.2:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libunistring.so.2 libunistring.so.2.1.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libunistring.so.2.1.0 libvirt-lxc.so.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libvirt-lxc.so.0 libvirt-lxc.so.0.9005.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libvirt-lxc.so.0.9005.0 libvirt-qemu.so.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libvirt-qemu.so.0 libvirt-qemu.so.0.9005.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libvirt-qemu.so.0.9005.0 libvirt.so.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libvirt.so.0 libvirt.so.0.9005.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libvirt.so.0.9005.0 libxml2.so.2:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libxml2.so.2 libxml2.so.2.9.13:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libxml2.so.2.9.13 libyajl.so.2:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libyajl.so.2 libyajl.so.2.1.0:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libyajl.so.2.1.0 libz.so.1:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libz.so.1 libz.so.1.2.11:bazel-out/aarch64-fastbuild/bin/rpm/libvirt-libs_aarch64/libz.so.1.2.11]

How to solve this problem

**Comment by zhlhahaha** [comment]
> /cc @zhlhahaha

Thanks for the remainding. I will take a look.

**Comment by zhlhahaha** [comment]
I encountered a similar issue, which, while not identical to yours, appears to have the same root cause.
```
ERROR: /root/go/src/kubevirt.io/kubevirt/rpm/BUILD.bazel:1508:8: //rpm:sandboxroot_aarch64 depends on @libsss_nss_idmap-0__2.9.2-2.el9.aarch64//rpm:rpm in repository @libsss_nss_idmap-0__2.9.2-2.el9.aarch64 which failed to fetch. no such package '@libsss_nss_idmap-0__2.9.2-2.el9.aarch64//rpm': java.io.IOException: Error downloading [http://mirror.stream.centos.org/9-stream/BaseOS/aarch64/os/Packages/libsss_nss_idmap-2.9.2-2.el9.aarch64.rpm] to /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/libsss_nss_idmap-0__2.9.2-2.el9.aarch64/rpm/downloaded: GET returned 404 Not Found
```
The problem arises because the specific versions of the RPM packages do not exist in the [RPM source](http://mirror.stream.centos.org/) and are not cached in Google storage. For example, this can be seen in the following link: [GitHub link to KubeVirt WORKSPACE](https://github.com/kubevirt/kubevirt/blob/e8e638edc22587ec7be2cc3d983b61763e33f973/WORKSPACE#L4680-L4694). The packages in this repository are continuously updated, and some older versions are removed. This issue is likely independent of CPU architecture and should occur when attempting to build x86_64 images.

To build the v1.1 KubeVirt images, you can switch to the release-1.1 branch and then run `make bazel-build-image`. This should resolve the issue.

**Comment by zhlhahaha** [comment]
Hi, @aburdenthehand @dhiller @xpivarc 
Do you know when the RPM packages will be cached in Google storage? Would it be worthwhile to cache all RPM packages in Google storage before releasing a Git tag?

**Comment by xpivarc** [comment]
> Hi, @aburdenthehand @dhiller @xpivarc Do you know when the RPM packages will be cached in Google storage? Would it be worthwhile to cache all RPM packages in Google storage before releasing a Git tag?

@dhiller @brianmcarey  fyi

There is periodic job that does uploads to storage but afaik only for main

**Comment by dhiller** [comment]
@xpivarc correct, currently there's only the job for main: https://github.com/kubevirt/project-infra/blob/143f5d25e5c656db1b77d9b4a03b6d8d3b29b814/github/ci/prow-deploy/files/jobs/kubevirt/project-infra/project-infra-periodics.yaml#L214

@zhlhahaha running a job _before_ the release sgtm - I would consider cloning the original definition for main, but changing it into a postsubmit job - this way we might reduce the chance that dependencies have gone already.

However, as of now it might be too late for uncached binaries already for older release branches (binaries already gone), in which case we might need to update them.

I would also consider creating a presubmit with --dry-run set for the release branches, so people would know about artifacts missing mirroring - but maybe I am overthinking here... 

@xpivarc @brianmcarey WDYT?
