### ISSUE TITLE
Increase number of sockets supported for client passthrough

### ISSUE THREAD

**Issue by bc185174** [kubevirt/kubevirt#12061]
**Is your feature request related to a problem? Please describe**:

Currently, client passthrough feature supports up to 4 USB devices. This seems limited by the number of sockets available to usbredir within the VM container. 

4 seems quite arbitrary, is there a technical limitation or is it something we can expand upon? 

**Describe the solution you'd like**:

Support for passing through more than 4 USB devices.

**Describe alternatives you've considered**:

N/A

**Additional context**:

**Comment by bc185174** [comment]
> Can you clarify your use case?

We have a use-case where we run a VM on a node but passthrough about 5/6 devices (not always local). 

> We could create configure option.

This would be ideal, defaulting to 4 with option to configure it.

**Comment by xpivarc** [comment]
@bc185174 Would you want to raise a PR for the configuration?

**Comment by bc185174** [comment]
> @bc185174 Would you want to raise a PR for the configuration?

Yeah definitely :100: See if I can get a PR ready.

**Comment by bc185174** [comment]
Try see if I can pick this one up.
