### ISSUE TITLE
Is there a way to pass custom bios to qemu?

### ISSUE THREAD

**Issue by failboat78** [kubevirt/kubevirt#12068]
When trying to run a QNX4 i386 vm I am stuck with this bug: https://bugs.launchpad.net/qemu/+bug/1191326

The fix is to use seabios with CONFIG_ATA_DMA=y. 

After building seabios with this option I can run vm manually via "qemu-system-i386 -bios mybios.bin ...." - it boots fine. But I cannot find a way to do the same thing with kubevirt. 

What is the least janky way to do this? Can I rebuild the virtlauncher container to have my custom seabios.bin somehow? Or can this ATA boot option be passed via other method? 

KubeVirt is working great for me running many vms - just not for QNX4 because of this issue.

Ideally would like to include this seabios.bin along with the disk image in container, and then specify field in YAML to tell qemu to use it.

**Comment by victortoso** [comment]
Hm, you could try doing it with sidecars. Using `OnDefineDomain` you would be able to change/add the command line option for QEMU or with [libvirt itself](https://libvirt.org/formatdomain.html#bios-bootloader). To pass the `mybios.bin` you would need a pvc and put it under `hooks.kubevirt.io/hookSidecars`'s pvc annotation, so the qemu/libvirt would be able to access it. See this [debug](https://kubevirt.io/user-guide/debug_virt_stack/launch-qemu-strace/) example for reference.
