### ISSUE TITLE
Tracker: Quarantined guestlog QOSGuaranteed test

### ISSUE THREAD

**Issue by lyarwood** [kubevirt/kubevirt#12074]
**What happened**:

As discussed on the [kubevirt-dev ML](https://groups.google.com/g/kubevirt-dev/c/c-zMktLPMlo) this test has become flaky again after some seemingly unrelated changes. This bug will track work to bring the test back out of quarantine and will start by tracking the progress of a yet to be raised libvirt bug.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by mlavi** [comment]
@lyarwood and @fossedihelm : could either of you assign yourself to this issue? Thank you. Reviewed in the weekly community meeting.
