### ISSUE TITLE
Make templates part of the release (optional)

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1208]
A few templates should be part of the release, as they are very convenient for users - if they use origin.

/kind enhancement

We have a few templates in the `cluster/examples`.
In order to promote them more we could make them part of a release. To me this has a few requirements:

- [ ] Define which templates (fedora, ubutnu, rhel, centos, windows?)
- [ ] Provide them as an optional (like the demo-content) artifact in the releases directory (i.e. templates.origin.yaml)
- [ ] Commit to doing testing of them - eventually a hard requirement on having (even if it's done internally at your company) CI to validate they work.

Actually with our origin provider we can do the tests in our env as well.

This relates a little to #771 as if #771 is done, then templates could be part of the general release.

**Comment by shiywang** [comment]
dibs 
/assign @shiywang

**Comment by fabiand** [comment]
Thus closing my own request.
