### ISSUE TITLE
memory hotplug doesn't work, guestCurrent not changed.

### ISSUE THREAD

**Issue by fangfenghuang** [kubevirt/kubevirt#12101]
**What happened**:
I try to test memory hotplug according to the https://kubevirt.io/user-guide/compute/memory_hotplug steps, It did trigger a update migration, but after the update migrate, the guestCurrent not changed and the memory not hotplugged.

**What you expected to happen**:
After the hotplug request is processed and the Virtual Machine is live migrated, the new amount of memory should be available to the guest and visible in the VMI object.

**How to reproduce it (as minimally and precisely as possible)**:
1. Enable feature-gate
```bash
kubectl --namespace kubevirt patch kv kubevirt -p='[{"op": "add", "path": "/spec/configuration/developerConfiguration/featureGates", "value": ["VMLiveUpdateFeatures"]}]' --type='json'
kubectl --namespace kubevirt patch kv kubevirt -p='[{"op": "add", "path": "/spec/configuration/vmRolloutStrategy", "value": "LiveUpdate"}]' --type='json'
kubectl --namespace kubevirt patch kv kubevirt -p='[{"op": "add", "path": "/spec/workloadUpdateStrategy/workloadUpdateMethods", "value": ["LiveMigrate"]}]' --type='json'
```

2. create a vm with maxGuest:
```yaml
      domain:
        cpu:
          maxSockets: 64
          cores: 1
          sockets: 1
          threads: 1
        memory:
          maxGuest: 64Gi
          guest: 1Gi
```

3. get status.memory
```bash
[root@hff-k8s-1 ~]# kubectl get vmi hffvm-1 -o json | jq .status.memory
{
  "guestAtBoot": "1Gi",
  "guestCurrent": "1Gi",
  "guestRequested": "1Gi"
}
```

4. patch the VM 
```bash
kubectl patch vm  hffvm-1  -p='[{"op": "replace", "path": "/spec/template/spec/domain/memory/guest", "value": "2Gi"}]' --type='json'
```

6. get status.memory after hotplug
```bash
[root@hff-k8s-1 ~]# kubectl get vmi hffvm-1 -o json | jq .status.memory
{
  "guestAtBoot": "1Gi",
  "guestCurrent": "1Gi",   # not changed
  "guestRequested": "2Gi"
}
```

**Additional context**:
cpu hotplug works well, but memory hotplug doesn't work. 
Is there any dependency or configuration I am missing? 

**Environment**:
- KubeVirt version (use `virtctl version`): 1.2.2
- Kubernetes version (use `kubectl version`): v1.27.13
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): 5.4.230-1.el7.elrepo.x86_64
- Install tools: N/A
- Others: N/A

**Comment by aburdenthehand** [comment]
/cc @acardace 
Hoping you can help as I see you authored the relevant doc. Thanks!

**Comment by acardace** [comment]
Hi @fangfenghuang, unfortunately the guest OS you're using doesn't support memory hotplug.

To successfully use memory hotplug you need a guest using at least Linux 5.16.

If that still doesn't work feel free to re-open this issue, thank you!

**Comment by acardace** [comment]
@aburdenthehand I see that I did not mention it in the user-guide, I definitely need to. I'll push a PR to update the user-guide soon.

**Comment by fangfenghuang** [comment]
> Hi @fangfenghuang, unfortunately the guest OS you're using doesn't support memory hotplug.
> 
> To successfully use memory hotplug you need a guest using at least Linux 5.16.
> 
> If that still doesn't work feel free to re-open this issue, thank you!

After upgrading the guest kernel version to 6.9.4-1.el7.elrepo.x86_64, memory hotplug effective.
