### ISSUE TITLE
Istio doesn't create the ingress traffic configuration

### ISSUE THREAD

**Issue by SchSeba** [kubevirt/kubevirt#1211]
Istio init container looks for the container ports, if no port is configure istio doesn't configure the ingress traffic. [istio-sidecar-injector-configmap](https://github.com/istio/istio/blob/master/install/kubernetes/helm/istio/templates/sidecar-injector-configmap.yaml#L42)

We need to add the ports configured by the slirp to the compute container inside our virt-lancher pod.

**Comment by fabiand** [comment]
That's awesome.

That means we can take the ports we need to define in the VM Spec and use them to define the ports on the pod level.

Not to bad.
