### ISSUE TITLE
Secondary development

### ISSUE THREAD

**Issue by niezhicheng** [kubevirt/kubevirt#12120]
**What happened**:
rpc error: code = Unknown desc = admission webhook "virtualmachinesnapshot-validator.snapshot.kubevirt.io" denied the request: missing apiGroup

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by niezhicheng** [comment]
> 你能提供你的 yaml 吗？或者你是如何创建快照的？那里可能缺少版本。

I used the client's API for secondary development, so I didn't have YAML. Is it because I didn't pass apiersion or something, but the list method is fine

**Comment by xpivarc** [comment]
What is `secondary development`?
