### ISSUE TITLE
Use kubevirt to provide Windows nodes to the cluster

### ISSUE THREAD

**Issue by blackliner** [kubevirt/kubevirt#12138]
I would like to be able to start off with a linux only kubernetes cluster, install kubevirt, spin up a windows VM, and have that windows VM join the cluster.

Has this been done before?
Is it possible at all?
Are there any tools/scripts/ideas available?

**Additional context**:
The goal would be to provide an environment for both production and development of applications that need both platforms. In our specific situation, the first use case would be to have a local kind cluster provide at least one windows and one linux node, which will run remote execution servers for our bazel build system. This way, a single build tree that spans multiple platforms can be realized on a local environment. Long term, the production cluster should be also supporting windows VMs via this approach.

**Comment by blackliner** [comment]
No progress, my plan was to get going once I have a better understanding of kubevirt, and that this issue might boost the knowledge :-)

**Comment by xpivarc** [comment]
I dropped the `kind/enhancement` as I don't see actual request from Kubevirt.
You can use Kubevirt to run Windows VMs, we have blogs and docs, see [example](https://kubevirt.io/2022/KubeVirt-installing_Microsoft_Windows_11_from_an_iso.html). We don't have your use case as example and I never heard of anyone doing this yet. In theory I don't see a problem with your use case. Depending how you setup your cluster, you can use the same tooling to join the Windows VM.
