### ISSUE TITLE
OpenAPI specification is not friendly with go-swagger

### ISSUE THREAD

**Issue by gouyang** [kubevirt/kubevirt#1217]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:
```
# swagger validate api/openapi-spec/swagger.json 

The swagger spec at "api/openapi-spec/swagger.json" is invalid against swagger specification 2.0.
See errors below:
- info.version in body is required
- some references could not be resolved in spec. First found: object has no key "inf.Scale"
- "getAPIGroup" is defined 3 times
- "getAPIResources" is defined 2 times
- path param "{namespace}" has no parameter definition

```

**How to reproduce it (as minimally and precisely as possible)**:
1. go get -u github.com/go-swagger/go-swagger/cmd/swagger
2. swagger validate api/openapi-spec/swagger.json

**Comment by gouyang** [comment]
I'm not sure if it's an issue or it has impact on us, just saw it so report it. Please feel free to close it.

**Comment by lukas-bednar** [comment]
I am taking down these errors one by one ...

@fabiand could you please help me to figured out what should be value for `Version` field ?
I am aware of `pkg/version/version.go` package which provides `Get` function returning `Info` structure.
Is it OK to use `Info.GitVersion` for this field ? If it is not I am open to suggestions.
