### ISSUE TITLE
Properly configure selinux for virt-laucher.

### ISSUE THREAD

**Issue by petrkotas** [kubevirt/kubevirt#1219]
**BUG REPORT**:

/kind bug

**What happened**:
Currently the `virt-handler` selinux policy is set to be super-privileged. This is a future security issue and has to be fixed.

This workaround is introduced in #1214 as a temporary solution.

**What you expected to happen**:
Figure out the right selinux settings and apply it to the virt-launcher.

**Comment by petrkotas** [comment]
Fixed error in component name.

**Comment by fabiand** [comment]
Well, it's good enough atm. CLosing this for now

/close
