### ISSUE TITLE
`make test` Receive a Error

### ISSUE THREAD

**Issue by matthewei** [kubevirt/kubevirt#12190]
**What happened**:
When I git clone the code form the repo and execute the `make test` command. I met the flowing error
![image](https://github.com/kubevirt/kubevirt/assets/86186853/d41e6419-7be3-4019-99b5-b7fd864449f8)

**What you expected to happen**:
when you execute `make test`,  all the test-case can pass 

**How to reproduce it (as minimally and precisely as possible)**:

git clone from repo and execute `make test`

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by jschintag** [comment]
The version in virtctl is being set during compile time. It depends on being able to read the information from git.
Likely there is some problem with git.

Could you post the output of:
```
hack/dockerized ./hack/print-workspace-status.sh
```
and
```
git status
```
