### ISSUE TITLE
Should the permissions to clone a PVC (DV's source) while creating VM, still be checked if the DV and PVC are already created?

### ISSUE THREAD

**Issue by viveksinghggits** [kubevirt/kubevirt#12204]
It's more of a question than a bug. 

**What happened**:
I am trying to create a VM that has datavolume source set to a PVC from different namespace. Let's say [this is](https://gist.github.com/viveksinghggits/92d12aa7dea782cf9f81ea2af0c0e57b) the VM that I have. When I create this VM this is the error that I see

```
The request is invalid: spec.dataVolumeTemplates[0]: Authorization failed, message is: User system:serviceaccount:vmtwo:default has insufficient permissions in clone source namespace vm-source
```

This error message seems logical that the SA is not authz to clone the other namespace, but I was thinking if we should even do this validation if in this particular case the datavolume and respective PVC for the VM are already available in the VM's namespace. Or in other words for this example should we even do this validation if the VM's DV `rhel8-vm-02` and PVC `rhel8-vm-02` are already available in the  `vmtwo` namespace?  

**How to reproduce it (as minimally and precisely as possible)**:
Create the VM mentioned above and we would see an authz related problem.

**Comment by xpivarc** [comment]
@mhenriks @awels @akalenyu

**Comment by mhenriks** [comment]
auth should be skipped if the dataVolume exists and has the `cdi.kubevirt.io/storage.prePopulated` annotation

**Comment by akalenyu** [comment]
> auth should be skipped if the dataVolume exists and has the `cdi.kubevirt.io/storage.prePopulated` annotation

yep https://github.com/kubevirt/kubevirt/blob/3a2b0b04ca06fbfa784c2ba3415f58e6b3ca8421/vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/authorize.go#L104-L106

**Comment by viveksinghggits** [comment]
### Reproducing issue

I just verified this and things don't seem to work. Below are the details. I have a VM that is specifying datavolume named `rhel8-vm-02` in its resource manifest. The datavolume's source is set to a PVC in different namespace

```
spec:
      source:
        pvc:
          name: rhel8-vm-01
          namespace: vm-source
```

The compete VM manifest can be found [here](https://gist.github.com/viveksinghggits/5d93e206e63ffdeca960b4d49976de24).

Now, we can check the referred DataVolume and respective PVC to make sure they are bound to each other and respective annotations are also set. 

Check the annotation on datavolume:

```
k get dv -n vm-target rhel8-vm-02 
NAME          PHASE       PROGRESS   RESTARTS   AGE
rhel8-vm-02   Succeeded   100.0%                15m

k get dv -n vm-target rhel8-vm-02 -ojsonpath='{.metadata.annotations}' | jq
{
  "cdi.kubevirt.io/cloneType": "csi-clone",
  "cdi.kubevirt.io/storage.clone.token": "...",
  "cdi.kubevirt.io/storage.prePopulated": "rhel8-vm-02",
  "cdi.kubevirt.io/storage.usePopulator": "true"
}
``` 

Check the PVC and it's annotation:

```
k get pvc -n vm-target rhel8-vm-02 
NAME          STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS                                 AGE
rhel8-vm-02   Bound    pvc-0d5fe4cf-dfab-4490-8f7d-8dc29bb9994d   32Gi       RWO            ocs-storagecluster-ceph-rbd-virtualization   16m

k get pvc -n vm-target rhel8-vm-02 -ojsonpath='{.metadata.annotations}' | jq
{
  "cdi.kubevirt.io/clonePhase": "Succeeded",
  "cdi.kubevirt.io/cloneType": "csi-clone",
  "cdi.kubevirt.io/createdForDataVolume": "d904ec7d-301d-4d02-9b4b-8ed61c67022d",
  "cdi.kubevirt.io/storage.condition.running": "false",
  "cdi.kubevirt.io/storage.condition.running.message": "Clone Complete",
  "cdi.kubevirt.io/storage.condition.running.reason": "Completed",
  "cdi.kubevirt.io/storage.contentType": "kubevirt",
  "cdi.kubevirt.io/storage.pod.restarts": "0",
  "cdi.kubevirt.io/storage.populatedFor": "rhel8-vm-02",
  "cdi.kubevirt.io/storage.populator.progress": "100.0%",
  "cdi.kubevirt.io/storage.preallocation.requested": "false",
  "cdi.kubevirt.io/storage.usePopulator": "true",
  ...,
  "pv.kubernetes.io/bind-completed": "yes"
}
```

and even after that if I go ahead and create the VM, below is the error that we get into.

```
k create -f vm-02.yaml -n vm-target
The request is invalid: spec.dataVolumeTemplates[0]: Authorization failed, message is: User system:serviceaccount:vm-target:default has insufficient permissions in clone source namespace vm-source
```

### Server versions

I am on OCP version `4.15.5`, so KubeVirt version would be `1.1` and CDI would be `
1.58.0`.

**Comment by akalenyu** [comment]
/assign akalenyu

Just summarizing the findings. The bug is in that we discard these annotations completely in the webhook: https://github.com/kubevirt/kubevirt/blob/3a2b0b04ca06fbfa784c2ba3415f58e6b3ca8421/vendor/kubevirt.io/containerized-data-importer-api/pkg/apis/core/v1beta1/authorize.go#L104-L106 This is because https://github.com/kubevirt/kubevirt/blob/3a2b0b04ca06fbfa784c2ba3415f58e6b3ca8421/pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go#L358-L361 and `dataVolume` is never grabbed from the API server https://github.com/kubevirt/kubevirt/blob/3a2b0b04ca06fbfa784c2ba3415f58e6b3ca8421/pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go#L336

**Comment by mengkai514** [comment]
Does your problem have been solved now? I created a VM in the same way as you and got the same error. @viveksinghggits

**Comment by viveksinghggits** [comment]
> Does your problem have been solved now? I created a VM in the same way as you and got the same error. @viveksinghggits

It looks like the PR that fixes this is merged, but it not part of the KubeVirt release `1.3.1`. So we will have to wait for the next release of KubeVirt. That should have this improvement.
