### ISSUE TITLE
start vm error

### ISSUE THREAD

**Issue by PenphyYang** [kubevirt/kubevirt#12208]
**What happened**:
can not create vm

**Environment**:
- KubeVirt version (use `virtctl version`): V1.1.1
- Kubernetes version (use `kubectl version`): V1.27
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): cenos7
- Kernel (e.g. `uname -a`): 3.10.0-1160.31.1.el7.x86_64
- Install tools: N/A
- Others: N/A

**vm yml**:
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  labels:
    kubevirt.io/size: small
    kubevirt.io/domain: testvm
    debugLogs: "true"
    logVerbosity: "6"
  name: testvm
  namespace: kubevirt
  annotations:
    kubevirt.io/keep-launcher-alive-after-failure: "true"
spec:
  domain:
    devices:
      disks:
        - name: containerdisk
          disk:
            bus: virtio
      interfaces:
      - name: default
        masquerade: {}
    resources:
      requests:
        memory: 64M
  networks:
  - name: default
    pod: {}
  volumes:
    - name: containerdisk
      containerDisk:
        image: docker.io/kubevirt/cirros-registry-disk-demo

**launcher log error**:
Please see the attachment
[virt-launcher-testvm-cxrnt.log](https://github.com/user-attachments/files/15966235/virt-launcher-testvm-cxrnt.log)

**Comment by scydas** [comment]
upgrade Kernel version >= 3.15

**Comment by tiraboschi** [comment]
the real root error is:
```
{"component":"virt-launcher-monitor","level":"error","msg":"failed to run virt-launcher","pos":"virt-launcher-monitor.go:175","reason":"fork/exec /usr/bin/virt-launcher: errno 0","timestamp":"2024-06-25T06:29:35.037308Z"}
```
everything else about
```
{"component":"virt-launcher-monitor","level":"error","msg":"could not create up serial console term file: /var/run/kubevirt-private/bc132fc2-00fd-46f3-a822-673513fd8214/virt-serial0-log-sigTerm","pos":"virt-launcher-monitor.go:72","reason":"open /var/run/kubevirt-private/bc132fc2-00fd-46f3-a822-673513fd8214/virt-serial0-log-sigTerm: no such file or directory","timestamp":"2024-06-25T06:29:35.138102Z"}
```
is basically just noise but absolutely not relevant:
`/var/run/kubevirt-private/<uuid>` is asyncornously initialized by `virt-launcher` process, not by `virt-launcher-monitor`, see: https://github.com/kubevirt/kubevirt/blob/a46841cbbac1da33a4eb74a298e64eaa64a74894/cmd/virt-launcher/virt-launcher.go#L158-L167

if `virt-launcher` process crashed really early in the game as in this case, nothing created `/var/run/kubevirt-private/bc132fc2-00fd-46f3-a822-673513fd8214` and so `virt-launcher-monitor` cannot create `/var/run/kubevirt-private/bc132fc2-00fd-46f3-a822-673513fd8214/virt-serial0-log-sigTerm` because its containing folder is still not there.

@xpivarc what about moving `initializeDirs` from `virt-launcher` to `virt-launcher-monitor` so that we are always sure that the required dirs are there?

**Comment by xpivarc** [comment]
@tiraboschi Good eyes! I completely missed it.

>@xpivarc what about moving initializeDirs from virt-launcher to virt-launcher-monitor so that we are always sure that the required dirs are there?

The binary is on purpose left half empty to be small as possible. I think moving this would increase it significantly but I am just guessing here.

@PenphyYang Please check following: 1. audit for SELinux or Apparmor complains 2. Your container runtime and seccomp version

**Comment by PenphyYang** [comment]
1selinux is disable
2.docker
Server: Docker Engine - Community
 Engine:
  Version:          20.10.24
  API version:      1.41 (minimum version 1.12)
  Go version:       go1.19.7
  Git commit:       5d6db84
  Built:            Tue Apr  4 18:21:02 2023
  OS/Arch:          linux/amd64
  Experimental:     false
 containerd:
  Version:          1.6.20
  GitCommit:        2806fc1057397dbaeefbea0e4e17bddfbd388f38
 runc:
  Version:          1.1.5
  GitCommit:        v1.1.5-0-gf19387a
 docker-init:
  Version:          0.19.0
  GitCommit:        de40ad0

**Comment by PenphyYang** [comment]
> @tiraboschi Good eyes! I completely missed it.
> 
> > @xpivarc what about moving initializeDirs from virt-launcher to virt-launcher-monitor so that we are always sure that the required dirs are there?
> 
> The binary is on purpose left half empty to be small as possible. I think moving this would increase it significantly but I am just guessing here.
> 
> @PenphyYang Please check following: 1. audit for SELinux or Apparmor complains 2. Your container runtime and seccomp version

1selinux is disable
2.docker
Server: Docker Engine - Community
Engine:
Version: 20.10.24
API version: 1.41 (minimum version 1.12)
Go version: go1.19.7
Git commit: 5d6db84
Built: Tue Apr 4 18:21:02 2023
OS/Arch: linux/amd64
Experimental: false
containerd:
Version: 1.6.20
GitCommit: 2806fc1057397dbaeefbea0e4e17bddfbd388f38
runc:
Version: 1.1.5
GitCommit: v1.1.5-0-gf19387a
docker-init:
Version: 0.19.0
GitCommit: de40ad0
