### ISSUE TITLE
kubevirt支持qcow2格式镜像文件启动吗？为啥使用cdi总是默认转为img格式的镜像文件才能启动

### ISSUE THREAD

**Issue by zhenliangliang** [kubevirt/kubevirt#12220]
**Is your feature request related to a problem? Please describe**:
A clear and concise description of what the problem is.

**Describe the solution you'd like**:

**Describe alternatives you've considered**:

**Additional context**:

**Comment by zhlhahaha** [comment]
I think kubevirt support qcow2 image, as you can see in the following document.
https://kubevirt.io/user-guide/storage/disks_and_volumes/#containerdisk-workflow-example
You can give it a try.

**Comment by alicefr** [comment]
@zhenliangliang can you please translate the title and provide a short description of the issue?

**Comment by zhenliangliang** [comment]
> @zhenliangliang can you please translate the title and provide a short description of the issue?

ok， Can kubevirt support launching qcow2 format image files? Why does using CDI always default to converting to img format image files to be able to launch?

**Comment by zhenliangliang** [comment]
> I think kubevirt support qcow2 image, as you can see in the following document. https://kubevirt.io/user-guide/storage/disks_and_volumes/#containerdisk-workflow-example You can give it a try.

I see, Using the scratch image to build the qcow2 image file will also be converted to img. Like cdi, cdi is also converted using the scratch image.

**Comment by awels** [comment]
Because qcow2 images come with a lot of capabilities that we leverage from kubernetes. It is much simpler to work with RAW images instead. This is why CDI always converts to RAW images on PVCs. I think technically KubeVirt can work with qcow2 images on a PVC, but we don't really test that flow. Why do you want to directly use qcow2 images?
