### ISSUE TITLE
Unit test become unstable

### ISSUE THREAD

**Issue by zhlhahaha** [kubevirt/kubevirt#12264]
**What happened**:
The pull-kubevirt-unit-test-arm64 job has started failing frequently after June 18th, as seen in the job history: [Prow Job History](https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-unit-test-arm64). Most of the failures originate from the same test: //pkg/storage/export/virt-exportserver:go_default_test.
```
exec ${PAGER:-/usr/bin/less} "$0" || exit 1
Executing tests from //pkg/storage/export/virt-exportserver:go_default_test
-----------------------------------------------------------------------------
Running Suite: //pkg/storage/export/virt-exportserver:go_default_test - /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/sandbox/processwrapper-sandbox/2676/execroot/kubevirt/bazel-out/aarch64-fastbuild/bin/pkg/storage/export/virt-exportserver/go_default_test_/go_default_test.runfiles/kubevirt/pkg/storage/export/virt-exportserver
==========================================================================================================================================================================================================================================================================================================================================================
Random Seed: [1m1719839762[0m

Will run 46of46specs
••••••• •2024/07/01 13:16:02 unable to manipulate /tmp's contents, exiting
```

**Additional context**:
This issue also appears in the pull-kubevirt-unit-test job, but it occurs less frequently. This discrepancy might be due to the pull-kubevirt-unit-test having a Bazel cache, whereas pull-kubevirt-unit-test-arm64 does not. For example, see this instance: [Prow Job View](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11991/pull-kubevirt-unit-test/1802993002335965184).

I suspect this issue is related to PR 392a8c5b1af36eff340d83d9eec123bf8438bd00. https://github.com/kubevirt/kubevirt/pull/11911 
However, I have not been able to reproduce it in my local environment.

**Comment by zhlhahaha** [comment]
Thanks @alromeros @brianmcarey

**Comment by alromeros** [comment]
I've opened a PR to address this issue https://github.com/kubevirt/kubevirt/pull/12283.

**Comment by xpivarc** [comment]
https://github.com/kubevirt/kubevirt/pull/12283 is merged
