### ISSUE TITLE
ssh: connect to host xxx port xxx: Network is unreachable

### ISSUE THREAD

**Issue by tk-aria** [kubevirt/kubevirt#12266]
**What happened**:
When stopping and restarting a VM, attempting to connect from an SSH client results in a "Network is unreachable" message.

**What you expected to happen**:
expected to be able to connect using an SSH client with the network being reachable.

**Additional context**:
- checked that the connection was working properly before the reboot.
- After rebooting, I can still connect via SSH on localhost.

**How to reproduce it (as minimally and precisely as possible)**:
1. install kubevirt and cdi
2. create a DataVolume after then VirtualMachine
3. run `virtctl stop <vm_name>`
4.  run `virtctl start <vm_name>`
5.  run `ssh ubuntu@${VMI_IP}` on  Pods.

ex) 

```bash
kubectl apply -f - <<EOF
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: ubuntu22-vm-disk
spec:
  source:
    http:
      url: https://cloud-images.ubuntu.com/jammy/current/jammy-server-cloudimg-amd64.img
  storage:
    storageClassName: local-path
    accessModes:
    - ReadWriteOnce
    resources:
      requests:
        storage: 16Gi
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: ubuntu22
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: ubuntu22
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
            - name: containervolume
              disk:
                bus: virtio
            - name: cloudinitvolume
              cdrom:
                bus: sata
                readonly: true
        resources:
          requests:
            memory: 4096M
      volumes:
        - name: containervolume
          dataVolume:
            name: ubuntu22-vm-disk
        - name: cloudinitvolume
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              chpasswd:
                list: |
                  ubuntu:ubuntu
                expire: False
EOF
```

**Environment**:
- KubeVirt version (use `virtctl version`): v1.2.0
- CDI version: v1.59.0
- Kubernetes version (use `kubectl version`): Client Version: v1.28.4 / Server Version: v1.28.4+k0s
- VM or VMI specifications:  show above manifest code.
- Cloud provider or hardware configuration: k0s / Ubuntu Focal / x86_64
- OS (e.g. from /etc/os-release): Ubuntu 20.04.6 LTS
- Kernel (e.g. `uname -a`):  Linux xxx 5.15.0-113-generic #123~20.04.1-Ubuntu SMP Wed Jun 12 17:33:13 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: N/A
- Others: N/A

**Comment by EdDev** [comment]
Seems I missed this issue :/

The IP or a VM (or a pod) is not guaranteed to persist after a stop/start sequence. The primary pod network IP is assigned by Kubernetes default IPAM plugin and not controlled by Kebevirt.

I suggest you use a service to implement this or to use an IPAM that can re-assign the same IP to pods (there are some d/s solutions that target this goal).

**Comment by tk-aria** [comment]
@EdDev 
Thank you for your response.

Does this mean that if the IP changes, it will no longer be possible to connect via SSH?
Also, why does this issue occur?
If there’s anything we can help with regarding unexpected problems, please let us know.

do you have any recommended CNI plugins for configuring IAPM?

**Comment by EdDev** [comment]
> Does this mean that if the IP changes, it will no longer be possible to connect via SSH?

It means you will need to do one of these:
- Read the IP from the VMI status and use it.
- Use a Kubernetes Service to track a VM IP.
- Use a secondary interface network and define its IP using cloud-init.
- Use some 3rd party or a D/S project/product that provides sticky IPs to pods/vms.

Also, why does this issue occur? If there’s anything we can help with regarding unexpected problems, please let us know.

It is a pod characteristic. Kubevirt runs VMs in pods. When you stop a VM, it disappears with its pod.

> do you have any recommended CNI plugins for configuring IAPM?

You could explore https://github.com/kubevirt/ipam-extensions .
But I’m not sure how easy it can be to use it, there are a lot of moving parts.
