### ISSUE TITLE
Completely switch to openapi-gen from k8s

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#1227]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:

Right now we still use `https://github.com/rmohr/go-swagger-utils` to generate go-restful structs for swagger.

**What you expected to happen**:

 Instead of that, we can now completely switch to `https://github.com/kubernetes/code-generator/tree/master/cmd/openapi-gen`.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

In order to make this work, do:

1) Use `builder.BuildOpenAPISpec` to build the spec based on go-restful (part of apimachinery)
2) this function requires a config. This config needs to contain the object definitions of our types (they are already generated with openapi-gen).
3) During code-generation, dump the resulting spec as json
4) Install the generated docs to a go-restful endpoint (wiring code exists in vendoring too)

**Comment by pkliczewski** [comment]
@rmohr @fabiand Can we give it a bit of priority it blocks https://github.com/candlepin/virt-who/pull/155 with this [issue](https://github.com/kubevirt/client-python/issues/23)?

**Comment by lukas-bednar** [comment]
@rmohr  I started to looking into this, but don't have anything in my hands right now.
Feel free to take it ...

**Comment by pkliczewski** [comment]
@lukas-bednar @rmohr any updates?

**Comment by pkliczewski** [comment]
@lukas-bednar @rmohr @stu-gott This blocks delivery of [this](https://trello.com/c/ciaOT94o/127-13-demo-of-entitlement-system) card. When can we have it fixed?

**Comment by pkliczewski** [comment]
@fabiand when can we expect this?

**Comment by rmohr** [comment]
I can't work on that right now. Maybe someone else can handle it.

**Comment by cynepco3hahue** [comment]
@lukas-bednar Do you have time to work on it, if no I can start to look on it.

**Comment by lukas-bednar** [comment]
@cynepco3hahue Unfortunately I don't ... but please talk to @pkliczewski, I was giving him some info how client generation works, so I believe that he has already started work on that.

**Comment by cynepco3hahue** [comment]
@lukas-bednar Thanks will ask him.

**Comment by cynepco3hahue** [comment]
I tried to change our `pkg/tools/openapispec.go` to use `BuildOpenAPISpec`, but I receive an error when I run it
```
go version go1.10 linux/amd64
2018/08/07 14:33:01 cannot find model definition for k8s.io/apimachinery/pkg/apis/meta/v1.ObjectMeta. If you added a new type, you may need to add +k8s:openapi-gen=true to the package or type and run code-gen again
make: *** [Makefile:7: generate] Error **1**
```
@rmohr @lukas-bednar Do you have an idea what it can be?
You can see the code under https://github.com/cynepco3hahue/kubevirt/commit/acf5900fb1eeeaf013cc82f9ad6842c856844127

**Comment by cynepco3hahue** [comment]
The problem that our generated `GetOpenAPIDefinitions` does not include a lot of types that we are using, I will try to figure how can I add it.

**Comment by rmohr** [comment]
> The problem that our generated GetOpenAPIDefinitions does not include a lot of types that we are using, I will try to figure how can I add it.

But if we use `openapi-gen`, it should produce them, right?

**Comment by cynepco3hahue** [comment]
Changing `go:generate` line under `scheme.go` and `types.go` to 
```
//go:generate openapi-gen -i .,k8s.io/apimachinery/pkg/apis/meta/v1,k8s.io/apimachinery/pkg/runtime,k8s.io/apimachinery/pkg/api/resource,k8s.io/api/core/v1 --output-package=kubevirt.io/kubevirt/pkg/api/v1  --go-header-file ../../../hack/boilerplate/boilerplate.go.txt
```
solved this problem, but created other problems.
We use `resource.Quantity` that defined as
```
// +protobuf=true
// +protobuf.embed=string
// +protobuf.options.marshal=false
// +protobuf.options.(gogoproto.goproto_stringer)=false
// +k8s:deepcopy-gen=true
// +k8s:openapi-gen=true
type Quantity struct {
	// i is the quantity in int64 scaled form, if d.Dec == nil
	i int64Amount
	// d is the quantity in inf.Dec form if d.Dec != nil
	d infDecAmount
	// s is the generated value of this quantity to avoid recalculation
	s string

	// Change Format at will. See the comment for Canonicalize for
	// more details.
	Format
}
```
so `openapi-gen` tries to generate definitions also for `infDecAmount` and `int64Amount` which one does not have `// +k8s:openapi-gen=true` comment, and I do not know how to solve it on our side(I think I will need to open issue to `apimachinery` repository to add  `// +k8s:openapi-gen=false` on this two fields).
@rmohr Any thoughts?

**Comment by rmohr** [comment]
@cynepco3hahue e.g. `Qunatity` contains a function called `OpenAPISchemaType`. Maybe if you find out where exactly that function is used, you can identify why it is not converted into a `string` type.

**Comment by cynepco3hahue** [comment]
@rmohr I see thanks for the info.

**Comment by cynepco3hahue** [comment]
@rmohr From what I can see, it just must work without any additional stuff, but it not :worried:

**Comment by cynepco3hahue** [comment]
Ok it works, but does not really help(it does not work for composition case), `openapi-gen` generated
```
"k8s.io/apimachinery/pkg/api/resource.Quantity": {
			Schema: spec.Schema{
				SchemaProps: spec.SchemaProps{
					Description: "Quantity is a fixed-point representation of a number. It provides convenient marshaling/unmarshaling in JSON and YAML, in addition to String() and Int64() accessors.\n\nThe serialization format is:\n\n<quantity>        ::= <signedNumber><suffix>\n  (Note that <suffix> may be empty, from the \"\" case in <decimalSI>.)\n<digit>           ::= 0 | 1 | ... | 9 <digits>          ::= <digit> | <digit><digits> <number>          ::= <digits> | <digits>.<digits> | <digits>. | .<digits> <sign>            ::= \"+\" | \"-\" <signedNumber>    ::= <number> | <sign><number> <suffix>          ::= <binarySI> | <decimalExponent> | <decimalSI> <binarySI>        ::= Ki | Mi | Gi | Ti | Pi | Ei\n  (International System of units; See: http://physics.nist.gov/cuu/Units/binary.html)\n<decimalSI>       ::= m | \"\" | k | M | G | T | P | E\n  (Note that 1024 = 1Ki but 1000 = 1k; I didn't choose the capitalization.)\n<decimalExponent> ::= \"e\" <signedNumber> | \"E\" <signedNumber>\n\nNo matter which of the three exponent forms is used, no quantity may represent a number greater than 2^63-1 in magnitude, nor may it have more than 3 decimal places. Numbers larger or more precise will be capped or rounded up. (E.g.: 0.1m will rounded up to 1m.) This may be extended in the future if we require larger or smaller quantities.\n\nWhen a Quantity is parsed from a string, it will remember the type of suffix it had, and will use the same type again when it is serialized.\n\nBefore serializing, Quantity will be put in \"canonical form\". This means that Exponent/suffix will be adjusted up or down (with a corresponding increase or decrease in Mantissa) such that:\n  a. No precision is lost\n  b. No fractional digits will be emitted\n  c. The exponent (or suffix) is as large as possible.\nThe sign will be omitted unless the number is negative.\n\nExamples:\n  1.5 will be serialized as \"1500m\"\n  1.5Gi will be serialized as \"1536Mi\"\n\nNOTE: We reserve the right to amend this canonical format, perhaps to\n  allow 1.5 to be canonical.\n  or after March 2015.\n\nNote that the quantity will NEVER be internally represented by a floating point number. That is the whole point of this exercise.\n\nNon-canonical values will still parse as long as they are well formed, but will be re-emitted in their canonical form. (So always use canonical form, or don't diff.)\n\nThis format is intended to make it difficult to use these numbers without writing some sort of special handling code in the hopes that that will cause implementors to also use a fixed point implementation.",
					Properties: map[string]spec.Schema{
						"i": {
							SchemaProps: spec.SchemaProps{
								Description: "i is the quantity in int64 scaled form, if d.Dec == nil",
								Ref:         ref("k8s.io/apimachinery/pkg/api/resource.int64Amount"),
							},
						},
						"d": {
							SchemaProps: spec.SchemaProps{
								Description: "d is the quantity in inf.Dec form if d.Dec != nil",
								Ref:         ref("k8s.io/apimachinery/pkg/api/resource.infDecAmount"),
							},
						},
						"s": {
							SchemaProps: spec.SchemaProps{
								Description: "s is the generated value of this quantity to avoid recalculation",
								Type:        []string{"string"},
								Format:      "",
							},
						},
						"Format": {
							SchemaProps: spec.SchemaProps{
								Description: "Change Format at will. See the comment for Canonicalize for more details.",
								Type:        []string{"string"},
								Format:      "",
							},
						},
					},
					Required: []string{"i", "d", "s", "Format"},
				},
			}
```
So I can see that indeed `s` and `Format` have expected scheme type and format, but two additional structs no.

**Comment by cynepco3hahue** [comment]
I currently blocked by https://github.com/kubernetes/apimachinery/issues/48
