### ISSUE TITLE
 Which is the best cni plugin to use with kubevirt? Is kube-ovn the best match, because the virtual machine network needs to use underlay mode?

### ISSUE THREAD

**Issue by zhenliangliang** [kubevirt/kubevirt#12286]
与kubevirt搭配使用最好的cni插件是哪个，kube-ovn是不是最佳搭配，因为虚拟机网络需要采用underlay模式

**Comment by aburdenthehand** [comment]
@maiqueb can you help with this one?

**Comment by aburdenthehand** [comment]
@zhenliangliang sorry for the delay. I followed up offline with someone in SIG-network and they suggested you try cni-bridge. This will connect you to the underlay with or without a vlan. Please note, the bridge must be configured before you use it.
