### ISSUE TITLE
public key injections breaks the host ssh access

### ISSUE THREAD

**Issue by karmab** [kubevirt/kubevirt#1228]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
password is required for ssh access to the host, although pub keys are there

**What you expected to happen**:
access the host the vm is running on without issue

**How to reproduce it (as minimally and precisely as possible)**:
launch a vm and inject a ssh key

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@karmab do I understand that correctly? You inject an ssh-key via e.g. cloud-init or ssh-copy-id into the **vm** and then you can't log into the **host** anymore?

**Comment by karmab** [comment]
my bad, turns out the following command snippet was 
```
docker run -it --rm -v /root/.kube:/root/.kube:Z -v /root/.ssh:/root/.ssh:Z ...
```
was screwing up my selinux labels....
