### ISSUE TITLE
Abort of workload updates is missbehaiving.

### ISSUE THREAD

**Issue by xpivarc** [kubevirt/kubevirt#12297]
**What happened**:
Running hotplug tests, a wild error appears
```
[FAILED] Timed out after 240.000s.
  migration should succeed after 240 s
  Unexpected error:
      <*errors.StatusError | 0xc0009006e0>: 
      virtualmachineinstancemigrations.kubevirt.io "kubevirt-workload-update-nzvbs" not found
      {
          ErrStatus: {
              TypeMeta: {Kind: "", APIVersion: ""},
              ListMeta: {
                  SelfLink: "",
                  ResourceVersion: "",
                  Continue: "",
                  RemainingItemCount: nil,
              },
              Status: "Failure",
              Message: "virtualmachineinstancemigrations.kubevirt.io \"kubevirt-workload-update-nzvbs\" not found",
              Reason: "NotFound",
              Details: {
                  Name: "kubevirt-workload-update-nzvbs",
                  Group: "kubevirt.io",
                  Kind: "virtualmachineinstancemigrations",
                  UID: "",
                  Causes: nil,
                  RetryAfterSeconds: 0,
              },
              Code: 404,
          },
      }
  occurred
  In [It] at: tests/libmigration/migration.go:63 @ 07/08/24 10:50:30.315

  Full Stack Trace
    kubevirt.io/kubevirt/tests/libmigration.ExpectMigrationToSucceedWithDefaultTimeout(...)
    	tests/libmigration/migration.go:63
    kubevirt.io/kubevirt/tests/hotplug.init.func4.2.7()
    	tests/hotplug/memory.go:346 +0xb3e
```

Upon closer look it appears https://github.com/xpivarc/kubevirt/commit/be31f56df104aa999f3dbff95ec4dd13328fc472 is not handling all cases correctly because A) Migration can be finished B) Hotplug might be done

**What you expected to happen**:
Keep a successful migration around.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by alicefr** [comment]
@xpivarc do you have a link of a CI failure?

**Comment by alicefr** [comment]
If the vmim was deleted because of the migration cancellation, then we should see in virt-controller log the line: `Delete migration kubevirt-workload-update-nzvbs  due to an update change abortion`
