### ISSUE TITLE
Allow setting CPU models

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1229]
As a user caring about performance I want to set my (v)CPU model to a specific CPU family or host pass-through in order to get best performance.

/kind enhancement

**Comment by cynepco3hahue** [comment]
It can be easily implemented, but do we want to pin VM to the specific node before allowing it because if we have nodes with different CPU features and the application under the VM expect to some specific set of features we can have a problem?

**Comment by michalskrivanek** [comment]
indeed - it doesn't make sense before we have proper capability reporting from nodes

**Comment by rmohr** [comment]
Well, I think @fabiand has a good point here and that we can simply allow it. Migrations, which we do not have right now may not work, and some vms/applications may have issues after restarts if vms start on different machines.

But shouldn't Linux (which I expect to be used mostly for good performance) be able to cope with that without problems and be always faster then?

**Comment by michalskrivanek** [comment]
we shouldn't encourage using host model passthrough. it will prevent the live migration and it will indeed cause that the guest will look differently on each host
But yeah, nothing against allowing to configure a specific CPU

...reading the original description, i think i commented on a wrong issue initially:-D

**Comment by j-griffith** [comment]
Personally I think there's a lot of value in having this option.  Again, it's an option so we won't be forcing anyone to use it.  My experience has been to always use pass-through mode for a number of reasons:

1.  Better performance (maybe this is urban legend?)
2.  Consistency in my environment (I want my VM's to look/behave like my bare metal)
3.  Moving my C++ builds to a VM and finding that without pass-through I couldn't compile because of a stupid time library that was relying on CPU features :)

If nothing else it seems like an important thing to make available, it's not expensive from a development or support point of view, and it's pretty valuable to those that need it.

@cynepco3hahue 
> It can be easily implemented, but do we want to pin VM to the specific node before allowing it because if we have nodes with different CPU features and the application under the VM expect to some specific set of features we can have a problem?

Is your concern here that perhaps a user wants to schedule the pod on a node with a specific CPU model?  I think if we get into that level of detail there's going to be some admins/users that will have much more intimate knowledge to make that sort of thing possible (labels and/or affinity?).  In other words, "here's the tools to do it, now it's up to you (the cluster-admin and end-user) to determine how to use it most effectively for you're specific needs.

**Comment by michalskrivanek** [comment]
> Personally I think there's a lot of value in having this option. Again, it's an option so we won't be forcing anyone to use it. My experience has been to always use pass-through mode for a number of reasons:
> 
>     Better performance (maybe this is urban legend?)
>     Consistency in my environment (I want my VM's to look/behave like my bare metal)

that's the exact opposite. With "bare metal" you're always get the exact bare metal you happen to run your VM on. In a diverse hw environment you get the exact opposite of consistency

>     Moving my C++ builds to a VM and finding that without pass-through I couldn't compile because of a stupid time library that was relying on CPU features :)

if you choose wrong features that's what you get, sure. A good enough management system chooses the optimal thing for you

> If nothing else it seems like an important thing to make available, it's not expensive from a development or support point of view, and it's pretty valuable to those that need it.

sure, it's a valuable option for some cases

> @cynepco3hahue
> 
>     It can be easily implemented, but do we want to pin VM to the specific node before allowing it because if we have nodes with different CPU features and the application under the VM expect to some specific set of features we can have a problem?
> 
> Is your concern here that perhaps a user wants to schedule the pod on a node with a specific CPU model? 

yes

I think if we get into that level of detail there's going to be some admins/users that will have much more intimate knowledge to make that sort of thing possible (labels and/or affinity?). In other words, "here's the tools to do it, now it's up to you (the cluster-admin and end-user) to determine how to use it most effectively for you're specific needs.

it's not really a detail, it's important when you care about consistency. And live migration which we do want to cover.

**Comment by vladikr** [comment]
Perhaps we can simply report the host cpu model (via label or crd?) and let the users request a specific model. If a user doesn't provide anything, we will set a default. We can also let the user set a host-passthrough if he wants.

We can then set a baseline cpu features in a domain and store it in a vm spec for stateful vms.
That should address the consistency issue. When such a vm starts we will compare the cpu features with the host and fail in case it doesn't match, but that should be rare unless it is a "host-passthough".
In the case of a "host-passthough" we can just document the implications.

Overall, at this stage, I'm not too worried if we would just let the users request a host-passthrough and handle the scheduling part later.

**Comment by fabiand** [comment]
For simplicity let's take passthrough out of the picture for now. Then I recommend the following:

1. In this issue: Add an VM API field to set the CPU family  (`virsh cpu-models x86_64`) to one of the known ones by libvirt. If it is not supported by a node, then we fail there. End of story.
2. In the next step expose the CPU families per node as labels
3. Modify the controller to set the correct selector to schedule VMs with a specific family only on nodes which support this family.

2. and 3. can be one or two additional issues.

42. Add passs-through support with 42 pages of warnings and documentation.

**Comment by fabiand** [comment]
For the record: Right now we use some Qemu CPU. This leads to really bad CPU performance. And this is actually affecting us in a relevant environment.

Thus as outlined in the previous comment we can limit this to set it to a know/supported CPU model.

Due to the impact on our environment and because of it's ease I'm also proposing this for release-0.6.

**Comment by berrange** [comment]
Note that given recently published hardware flaws, CPU model choice is now considered a **security critical** part of guest configuration. 

Long term plans are slightly in flux, but for now this patch provides our best guidance on what apps should be doing:

  https://lists.gnu.org/archive/html/qemu-devel/2018-06/msg08024.html

Apologies for the horrible texinfo markup there. Once its merged there'll be a pretty HTML doc published to read.

**Comment by fabiand** [comment]
It is a horrible text markup :)

Thanks for raising this.

Can you tell which haswell and broadwell configurations would be safe to take?

Side note could you comment on https://github.com/kubevirt/kubevirt/issues/1117 if it's the best approach right now to follow F28 qemu/libvirt to inherit all possibel changes coming up?

**Comment by berrange** [comment]
There's no right answer about which named model to use, as it depends what hardware you are running on.  Per that document I link to, you should either pick host passthrough/host model, or pick a named CPU model that matches your host.   host model & named CPU model both allow for live migration, though the latter is slightly more relaxed if you have heterogeneous hardware across the cluster. Also bear in mind there are both AMD and Intel models and so you must pick the right vendor model for your host

**Comment by berrange** [comment]
I republished the content in a blog for easier reading, since it may be a while before it gets published in QEMU docs properly https://www.berrange.com/posts/2018/06/29/cpu-model-configuration-for-qemu-kvm-on-x86-hosts/

**Comment by fabiand** [comment]
Btw I created https://github.com/kubevirt/kubevirt/issues/1247 to track further work.
