### ISSUE TITLE
Limit machine type to q35

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1230]
Today we can set the machine type.

In order to strive for stability and avoid complexity we should limit ourselfs to a future proof (ha! q35 is sooo odl, but still the most recent ..) machine type

/kind enhancement

In order to achieve this we should ~either remove the field from the API or~ limit it to a single value (in order to still give visibility of the machine type in the API)

**Comment by cynepco3hahue** [comment]
I think we must remove it, I did not see any usage of the machine type under Ovirt and OpenStack.

To achieve it you must:
- remove any reference to `Machine` under `pkg/api/v1/schema.go`
- set machine type to `q35` under `pkg/virt-launcher/virtwrap/api/converter.go`
- make sure that unittests passed
- make sure that functional tests passed

**Comment by michalskrivanek** [comment]
why would you want to remove the one thing which makes sure that guest ABI stays the same across Kubevirt and/or libvirt/qemu upgrades? 
I consider "futureproof" to be guest stability, not random changes to guest hw.

**Comment by cynepco3hahue** [comment]
@michalskrivanek I want to remove it only from VM specification because we do have any real use for it, but libvirt domain still will receive machine type `q35`

**Comment by michalskrivanek** [comment]
what do you mean, that the current parameter is not propagated to the actual VM definition?

**Comment by cynepco3hahue** [comment]
@michalskrivanek We propagate, but from @fabiand description, looks like we want to support only `q35` machine type, so it can be set by default and no need to have additional spec field for it.

**Comment by michalskrivanek** [comment]
right, so that's what i dispute. It shouldn't be removed

**Comment by stu-gott** [comment]
@michalskrivanek If I understand what you're saying, you're opting for "option number 2" from @fabiand's original proposition: "don't take machine type out of the KubeVirt API, but limit it to a single value"

What @fabiand is saying is that *for now* there's no possibility to specify anything besides q35, so why ask the user that question? It just adds complexity (and no known downstream project needs it anyways). If and when other machine types do become supported, the default will still be q35, thus existing machines will remain stable between reboots/upgrades. As @cynepco3hahue pointed out, we're still sending an explicit directive to libvirt.

To re-emphasize: the communication between KubeVirt and libvirt is and always will be explicit. the machine type will always be in the libvirt dom xml. this is strictly about whether the user should be asked a (currently) pointless question at the KubeVirt API level.

I just want to make sure we're not talking past each other. :)

**Comment by michalskrivanek** [comment]
@fabiand @stu-gott not really - what I'm saying is that while "q35" is a good enough type for now to start with, it's not the one you want to use long term in stable environment. It's not a pointless knob, it's a fundamental knob for ABI stability. 
Again in other words, if you want existing machines to be stable  between upgrades you want to __not__ use q35, but a more concrete versioned type. "q35" (as well as "pc") is always the latest hw in each qemu version. I.e. on upgrade you get a different ABI

**Comment by cynepco3hahue** [comment]
@michalskrivanek What machine type do you recommend to use?

**Comment by michalskrivanek** [comment]
I think we're still at a stage where guest ABI stability doesn't matter much (we're missing stable addresses now anyway) - then "q35" is a good default, even though upgrading infrastructure will change VMs ABI.
Once we have facilities (and thoughts) around cluster upgrade and notion of compatibility levels for upgrades (and stable addresses) we should switch to a fixed type as a default and maintain it consciously

My point wasn't about using a different one right now, I was just trying to make sure we're not removing the capability of keeping stable VMs from users who care about it already. A user can already choose a concrete machine type today and it will give him at least a partial VM stability

My suggestion for now - q35 a default when not specified, still keep it exposed and configurable

**Comment by danielBelenky** [comment]
@michalskrivanek from what I've undersood, the default is already set to 'q35'

`pkg/api/v1/defaults.go:         obj.Spec.Domain.Machine.Type = "q35"`

**Comment by evol262** [comment]
A suggestion was made to add a validator to ensure that this is true, but it's already the default in most places.

Is the purpose of this issue to remove the type selection from a generated UI (from the Spec), or to ensure it's the default?

Where it is the default:
https://github.com/kubevirt/kubevirt/blob/master/pkg/api/v1/defaults.go#L128

Where it is not (but easily changed):
https://github.com/kubevirt/kubevirt/blob/master/tests/vmi_configuration_test.go#L345

It seems that the original request (to remove it from the API for now) is probably correct

**Comment by evol262** [comment]
A suggestion was made to add a validator to ensure that this is true, but it's already the default in most places.

Where it is the default:
https://github.com/kubevirt/kubevirt/blob/master/pkg/api/v1/defaults.go#L128

Where it is not (but easily changed):
https://github.com/kubevirt/kubevirt/blob/master/tests/vmi_configuration_test.go#L345

It seems that the original request (to remove it from the API for now) is probably correct, if this is desired, but existing behavior matches @michalskrivanek's suggestion

Instead, why not remove this from the API (swagger and OpenAPI)? Swagger is easy, but I don't see a flag for openapi-gen to ignore a nested value.

**Comment by fabiand** [comment]
Thanks for the discussion. For now I'd then suggest to go with limiting it to one value (q35).

**Comment by fabiand** [comment]
Follow up - We probably do not have to limit to q35 strict, but rather to the q35 family.

**Comment by lpgc** [comment]
I would note that recently qemu-system-x86_64 has added a new machine type 'microvm' which is intended to support small/fast VM r/t environments, due to this restriction it is not possible to configure a VMI to use this latest machine type.

**Comment by T0MASD** [comment]
@fabiand does this remove ability to run aarch64, armv8 or any machine type that is available to qemu system emulator (dnf search qemu-system)?
