### ISSUE TITLE
sig-operator lane: clustered failure occured

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#12312]
**What happened**:

We observed a clustered failure (47 test failures including AfterSuite) [1] on a test run, where clearly no involvement of the code changes was responsible.

Initial error log:

```
Tests Suite: [Serial][sig-operator]Operator [rfe_id:2291][crit:high][vendor:cnv-qe@redhat.com][level:component]should update kubevirt [release-blocker][test_id:3145]from previous release to target tested release by updating virt-operator expand_less	4m37s

{ Failure tests/operator/operator.go:1418
Error from server (InternalError): error when creating "/tmp/ginkgo103783789/vm-v1.yaml": Internal error occurred: failed calling webhook "virtualmachines-mutator.kubevirt.io": failed to call webhook: Post "https://virt-api.kubevirt.svc:443/virtualmachines-mutate?timeout=10s": context deadline exceeded

Unexpected error:
    <*errors.errorString | 0xc0066c4b90>: 
    command failed: cannot run command "/home/prow/go/src/github.com/kubevirt/kubevirt/_ci-configs/k8s-1.28/.kubectl -n kubevirt-test-default1 create -f /tmp/ginkgo103783789/vm-v1.yaml --cache-dir /tmp/ginkgo103783789/oldclient": exit status 1
    {
        s: "command failed: cannot run command \"/home/prow/go/src/github.com/kubevirt/kubevirt/_ci-configs/k8s-1.28/.kubectl -n kubevirt-test-default1 create -f /tmp/ginkgo103783789/vm-v1.yaml --cache-dir /tmp/ginkgo103783789/oldclient\": exit status 1",
    }
occurred
tests/operator/operator.go:1223}
```

Remaining tests failed with timeout, except one failing for a missing snapshot that was expected to be there for deletion.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:
/kind flake
/sig ci

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

[1]: https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12230/pull-kubevirt-e2e-k8s-1.28-sig-operator/1807325086819028992

**Comment by dhiller** [comment]
We saw a similar occurrence of this last Monday on the sig-ci meeting: https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/11857/pull-kubevirt-e2e-k8s-1.30-sig-operator/1797702598988402688

**Comment by dhiller** [comment]
Has been observed again: https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12315/pull-kubevirt-e2e-k8s-1.30-sig-operator/1811301262184943616

Related PR was this: https://github.com/kubevirt/kubevirt/pull/12315

**Comment by dhiller** [comment]
Another clustered failure from today's SIG CI meeting:
https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/pr-logs/pull/batch/pull-kubevirt-e2e-k8s-1.29-sig-operator/1838774597382574080

**Comment by xpivarc** [comment]
> @xpivarc @jean-edouard do you happen to know whether someone has been investigating this failure?

I am not aware of anyone looking into this.

Looking at the latest entry, the upgrade tests fails (and that messes up the cluster...). 
The problem seems to be deployment of `virt-handler` that shows 
``` 
{
     "type": "Initialized",
      "status": "False",
      "lastProbeTime": null,
      "lastTransitionTime": "2024-09-25T03:45:37Z",
      "reason": "ContainersNotInitialized",
      "message": "containers with incomplete status: [virt-launcher]"
},`
```
Unfortunately I can't say why this happens because we don't collect the node logs... We should change this (opt-in scrape)

**Comment by dhiller** [comment]
Seems like a control runtime issue, this time the node didn't run in the vm, so we didn't get the logs.

There's no reason for this to happen.

Let's create a low prio issue on the node collection.

Other than that we didn't see this one, is a low prio flake.

/close

So this is a special case where no vmi is running on the node, in which case the node logs aren't collected. We should change this 

Apparently a change by Maya, which we might think about rolling back. We should scrape all nodes in case we need it, this should be controlled by an env parameter that the k8s collector respects.
