### ISSUE TITLE
periodic sig-compute-migrations: clustered failures occurred

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#12316]
**What happened**:

/kind flake
/sig ci

From the flakefinder report of Monday [1] we observed two clustered failures on the periodic migration lane for 1.30 [2] [3]
The latter also contains a CPU hotplug failure which is a different issue, but failures on both runs look largely the same.

Notable observations:

Test log on test showed `Synchronizing with the Domain failed.`:

```
Tests Suite: [rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system][sig-compute] VM Live Migration Starting a VirtualMachineInstance with a Fedora shared NFS PVC (using nfs ipv4 address), cloud init and service account [test_id:2653] should be migrated successfully, using guest agent on VM with default migration configuration expand_less	12m35s
{ Failure tests/migration/migration.go:1159
Timed out after 720.001s.
Expected
    <[]interface {} | len:4, cap:4>: [
        <map[string]interface {} | len:4>{
            "lastTransitionTime": <string>"2024-07-08T15:28:51Z",
            "type": <string>"Ready",
            "status": <string>"True",
            "lastProbeTime": nil,
        },
        <map[string]interface {} | len:6>{
            "lastProbeTime": nil,
            "lastTransitionTime": nil,
            "reason": <string>"AllDVsReady",
            "message": <string>"All of the VMI's DVs are bound and not running",
            "type": <string>"DataVolumesReady",
            "status": <string>"True",
        },
        <map[string]interface {} | len:4>{
            "type": <string>"LiveMigratable",
            "status": <string>"True",
            "lastProbeTime": nil,
            "lastTransitionTime": nil,
        },
        <map[string]interface {} | len:6>{
            "message": <string>"unknown error encountered sending command SyncVMI: rpc error: code = DeadlineExceeded desc = context deadline exceeded",
            "type": <string>"Synchronized",
            "status": <string>"False",
            "lastProbeTime": nil,
            "lastTransitionTime": <string>"2024-07-08T15:33:22Z",
            "reason": <string>"Synchronizing with the Domain failed.",
        },
    ]
expected condition of type 'AgentConnected' was not found
tests/migration/postcopy.go:347}
```

Some VolumeFailedDelete events in the event log [4]

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

[1]: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2024-07-08-024h.html
[2]: https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.30-sig-compute-migrations/1810209708108156928
[3]: https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.30-sig-compute-migrations/1810330508979081216
[4]: https://storage.googleapis.com/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.30-sig-compute-migrations/1810330508979081216/artifacts/k8s-reporter-parallel/1/1_events.log

**Comment by akalenyu** [comment]
There are issues in the NFS CSI driver to `mount` volumes, so that results in PVCs never converging
https://storage.googleapis.com/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.30-sig-compute-migrations/1810209708108156928/artifacts/k8s-reporter/pods/2_nfs-csi_csi-nfs-controller-5bb5f5dd7c-hvth8-nfs.log
The exit status seems pretty generic and I don't see anything interesting in the node logs.. but I think at that point and onwards NFS CSI is broken

**Comment by dhiller** [comment]
@xpivarc @fossedihelm would you be able to find someone who could look into this? 

Flake-stats reports a high number of failures on the presubmit lane now also: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flake-stats-14days-2024-10-09.html

Latest clustered failure is this one: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.31-sig-compute-migrations/1843744638159032320

**Comment by dhiller** [comment]
Strange thing that I am seeing here is this:

```
Message: "nodes is forbidden: User \"kubernetes-admin\" cannot list resource \"nodes\" in API group \"\" at the cluster scope",
            Reason: "Forbidden",
            Details: {Name: "", Group: "", Kind: "nodes", UID: "", Causes: nil, RetryAfterSeconds: 0},
            Code: 403,
```

**Comment by dhiller** [comment]
Sounds like a kubevirt resource issue to me.

**Comment by xpivarc** [comment]
Looks like API went down...

**Comment by iholder101** [comment]
/close
(as per https://github.com/kubevirt/kubevirt/issues/12316#issuecomment-2459055958)
