### ISSUE TITLE
Consider renaming kubevirt finalizers

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#12342]
**What happened**:
When creating a VMI we see this warning
```
2024-07-11T15:56:52+03:00	INFO	KubeAPIWarningLogger	metadata.finalizers: "foregroundDeleteVirtualMachine": prefer a domain-qualified finalizer name to avoid accidental conflicts with other finalizer writers
```

**What you expected to happen**:
We should do as the warning says, and rename the finalizer.
i.e `kubevirt.io/foregroundDeleteVirtualMachine`

**How to reproduce it (as minimally and precisely as possible)**:
Create a VMI, and check logs.
During standalone VMI creation, it will be shown directly as part of kubectl command output.

**Additional context**:
Found at at least this two finalizers that should be renamed.
```
pkg/virt-operator/util/client.go:	KubeVirtFinalizer string = "foregroundDeleteKubeVirt"
staging/src/kubevirt.io/api/core/v1/types.go:	VirtualMachineInstanceFinalizer string = "foregroundDeleteVirtualMachine"
```

Need to create backward compatible code, that can remove those finalizers from old running machines.

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by dankenigsberg** [comment]
When addressing this issue, please remember to consider the upgrade path. VMs created with the old finalizer name should shut down properly after kubevirt upgrade, at least for a while.

**Comment by lerrigatto** [comment]
This is still a warning on k8s 1.31 and kubevirt 1.5.0

**Comment by dankenigsberg** [comment]
PR #15096 addressed the `foregroundDeleteVirtualMachine` bit; I think that `foregroundDeleteKubeVirt` is still unqualified.

/reopen
