### ISSUE TITLE
kubevirt nightly build not working

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#12351]
**What happened**:
Since last Friday the nightly build from main is not working any more - example build:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-push-nightly-build-main/1812291541721419776

Probably related: there was a golang image update for the job happening right before the first failure of this kind.

**What you expected to happen**:
Job should build the nightly stuff.

**How to reproduce it (as minimally and precisely as possible)**:
We are going to run the job with the older image version and see whether it is reproducible with it.

**Additional context**:
-

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

/sig ci
/assign @brianmcarey

**Comment by brianmcarey** [comment]
This looks an issue related to a recent bump of the prow job images[1] - running with the previous image does not hit this issue - https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-push-nightly-build-main/1812800958204219392

[1] https://github.com/kubevirt/project-infra/pull/3491

**Comment by iholder101** [comment]
Can this one be closed?

**Comment by dhiller** [comment]
As of https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/logs/periodic-kubevirt-push-nightly-build-main we are seeing that the job has been fixed with https://github.com/kubevirt/project-infra/pull/3769
