### ISSUE TITLE
Can we make it so that even if the "virt-launcher" Pod" dies, the virtual machine remains unaffected, like OpenStack?

### ISSUE THREAD

**Issue by xianlubird** [kubevirt/kubevirt#12352]
If the virt-launcher Pod is deleted or restarted for various reasons, is there any way we can keep the virtual machine running without being affected? OpenStack does this very well. Even if the control fails, the virtual machine on the worker can still run normally.

**Comment by lyarwood** [comment]
@xianlubird  IMHO this isn't a valid comparison, the controller services of OpenStack are not the same as the `virt-launcher` `pod` within KubeVirt.

There's actually no relevant comparison of `virt-launcher` within vanilla OpenStack, the only valid one I can think of is the compute container downstream in RDO and Red Hat OpenStack <= 17 but even then that container mapped virtual machines to the host process namespace thus allowing it to be killed but the VMs to continue running. Architecturally we can't and likely don't want to do anything resembling that within KubeVirt anyway.

FWIW you should be able to kill `virt-handler` and the rest of the control plane services within KubeVirt and still have a running `VirtualMachine` within the `virt-launcher` pod.

**Comment by xianlubird** [comment]
When I kill `virt-launcher` pod, the vm(`VirtualMachine `) inside the pod will also down。

Like the issue #12290 #11662 ，There are various reasons that may cause the `virt-launcher pod ` to crash. 

How can we ensure that even if the pod crashes, the VM can still run normally, and then the new `virt-launcher pod` can continue to take over the VM after it is started? Just like Docker or containerd `live-restore`, decoupling the strong binding relationship between Pod and VM.

Could you please give me some suggestions or ideas? Thanks

**Comment by 0xFelix** [comment]
Hi, that's not possible because the VM runs inside that Pod. If you kill the virt-launcher Pod, then the container running the VM is also killed.

**Comment by iholder101** [comment]
Thank you @lyarwood and @0xFelix for your answers.
As said above, the guest and hypervisor both run inside the virt-launcher pod, so this is an expected behavior that I'm not sure could ever be changed due to Kubevirt's core architecture.

/close
