### ISSUE TITLE
Don't rely on the qemu binary name for detecting its PID

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#1236]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

In our builds we know the name of the qemu binary which will be selected by libvirt and we use this knowledge to find the qemu pid based on the qemu binary name. We assue mit is called `qemu-system-*`. That is not necessarily the case when kubevirt is rebuilt and uses a different base OS.

**What you expected to happen**:

Since libvirt is now inside the container too, like @michalskrivanek suggested, we can look up the qemu pid directly in `/var/run/libvirt/qemu/[NAME].pid` and do not have to guess based on binary names.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by davidvossel** [comment]
> FWIW, if you ever do need the binary name, you can query the libvirt capabilities XML before starting a guest to determine what QEMU binary path libvirt will use by default. Alternatively you can get the binary name out of the domain XML after defining it, but before starting it.

That's a good point. Unfortunately it doesn't reflect the name of the binary associated with the pid necessarily.

For example, the binary on my domain is set to /usr/bin/qemu-kvm, but that binary is a bash script that calls ```exec /usr/bin/qemu-system-x86_64 $opts "$@"```. When we do a ps -aux, we're going to see qemu-system-x86_64 instead of qemu-kvm.
