### ISSUE TITLE
`virtctl expand --file` should accept `-` (STDIN)

### ISSUE THREAD

**Issue by lyarwood** [kubevirt/kubevirt#12376]
/area instancetype

**Is your feature request related to a problem? Please describe**:
$subject, at present this fails with the following:

```
$ ./cluster-up/kubectl.sh apply -k https://github.com/kubevirt/common-instancetypes.git
[..]
$ ./cluster-up/virtctl.sh create vm --instancetype u1.medium --preference fedora --volume-containerdisk src:quay.io/containerdisks/fedora:40 | ./cluster-up/virtctl.sh expand --file -
error reading file open -: no such file or directory
```

**Describe the solution you'd like**:
Support for `-f -` as with other `kubectl` commands.

**Describe alternatives you've considered**:
N/A

**Additional context**:
N/A

**Comment by aliamerj** [comment]
Hi, @lyarwood 

I would like to work on this issue. Could you please provide more details about it?

1. How can I reproduce the issue?
2. Which file(s) should I update to implement this feature?
3. Should the solution support all arguments, or just the -f (file) argument?

**Comment by lyarwood** [comment]
> Hi, @lyarwood
> 
> I would like to work on this issue. Could you please provide more details about it?

Excellent!

/assign @aliamerj

> 1. How can I reproduce the issue?

See the description, using a kubevirtci based env it's pretty simple.

> 2. Which file(s) should I update to implement this feature?

kubevirt/pkg/virtctl/vm/expand.go
kubevirt/pkg/virtctl/vm/expand_test.go

> 3. Should the solution support all arguments, or just the -f (file) argument?

`--file` and `-f` is already supported we just lack support for passing `-` to represent standard input:

https://github.com/kubevirt/kubevirt/blob/e24f3bbce8e7beec9afdcfa61fbbdda7d335e820/pkg/virtctl/vm/expand.go#L133-L147

Hope this helps and thanks for taking this on!

**Comment by aliamerj** [comment]
I spent a lot of time trying to execute this command:

```bash
./cluster-up/kubectl.sh apply -k https://github.com/kubevirt/common-instancetypes.git
```
but I got the following error:
```bash
error: hit 27s timeout running '/usr/bin/git fetch --depth=1 https://github.com/kubevirt/common-instancetypes.git HEAD'
```
I tried to fetch the common-instancetypes first:
```bash
cd common-instancetypes
sudo ../cluster-up/kubectl.sh apply -k .
```
i got other error
```bash
selecting docker as container runtime
resource mapping not found for name: "cx1.2xlarge" namespace: "" from ".": no matches for kind "VirtualMachineClusterInstancetype" in version "instancetype.kubevirt.io/v1beta1"
ensure CRDs are installed first
resource mapping not found for name: "cx1.4xlarge" namespace: "" from ".": no matches for kind "VirtualMachineClusterInstancetype" in version "instancetype.kubevirt.io/v1beta1"
ensure CRDs are installed first
resource mapping not found for name: "cx1.8xlarge" namespace: "" from ".": no matches for kind "VirtualMachineClusterInstancetype" in version "instancetype.kubevirt.io/v1beta1"
ensure CRDs are installed first
resource mapping not found for name: "cx1.large" namespace: "" from ".": no matches for kind "VirtualMachineClusterInstancetype" in version "instancetype.kubevirt.io/v1beta1"
ensure CRDs are installed first
resource mapping not found for name: "cx1.medium" namespace: "" from ".": no matches for kind "VirtualMachineClusterInstancetype" in version "instancetype.kubevirt.io/v1beta1"
ensure CRDs are installed first
.....
```
I also tried running `make cluster-up`, but it's still not working.

**Comment by aliamerj** [comment]
i also tried to increase the timeout with
```bash
sudo ./cluster-up/kubectl.sh apply --timeout=500 -k https://github.com/kubevirt/common-instancetypes.git
```
 but it did not increased
still get this error
```
error: hit 27s timeout running '/usr/bin/git fetch --depth=1 https://github.com/kubevirt/common-instancetypes.git HEAD'
```

**Comment by lyarwood** [comment]
@aliamerj did you run `make cluster-sync` to deploy `KubeVirt`? The following works for me:

```
$ env | grep KUBEVIRT
KUBEVIRT_PROVIDER=k8s-1.30
KUBEVIRT_MEMORY_SIZE=16384
$ make cluster-updown && make cluster-up && make cluster-sync
[..]
$ time ./cluster-up/kubectl.sh apply -k https://github.com/kubevirt/common-instancetypes.git
[..]
real    0m4.587s
user    0m4.917s
sys     0m0.567s
```

Alternatively you can also get `virt-operator` to deploy `common-instancetypes` for you with the following command:

```
/cluster-up/kubectl.sh patch kv/kubevirt -n kubevirt --type merge -p '{"spec":{"configuration":{"developerConfiguration":{"featureGates": ["CommonInstancetypesDeploymentGate"]}}}}'
```

**Comment by aliamerj** [comment]
okay, I'll try it out

**Comment by aliamerj** [comment]
it did not work 
i even delete docker and reinstall it and still get the error
i am using Ubuntu 22.04.4 LTS 
this the error i am getting when i run make cluster-sync
```bash
Error pushing image to localhost:32840/kubevirt/virt-operator:devel: unable to push image to localhost:32840/kubevirt/virt-operator:devel: Get "http://localhost:32840/v2/": dial tcp 127.0.0.1:32840: connect: connection refused
make[1]: *** [Makefile:159: cluster-build] Error 1
make[1]: Leaving directory '/home/ali/Projects/kubevirt'
make: *** [Makefile:168: cluster-sync] Error 2
```
maybe there is some libraries or docker images are missing
