### ISSUE TITLE
discussion: check-tests-for-flakes-lane should not run on release branches

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#12393]
The lane `pull-kubevirt-check-tests-for-flakes` is currently defined for branches main and the release branches [1]. I'm opening the discussion since I have seen the lane run here [2].

The main goal for this lane is to find flaky tests by running changed tests five times, each time in random order. This shows order dependencies in tests and reveals 88% of flaky tests. It has proven to be very effective in revealing problems in PRs where tests have been introduced or changed.

This lane is one of the heavier lanes resource-wise, since it requires the same resources as other e2e lanes, probably averaging similar to a sig-storage lane with three nodes. Runtime varies, since it depends on the amount of tests changes, averaging around 30 mins I guess [5].

However, advancing development happens only in the main branch, while release branches only receive backports of fixes. Fixing tests should happen in main branch first and foremost, since it will be carried over into all new development and then eventually backported to older branches. If the above lane runs on release branches, it merely checks again what has already been checked in the main branch. Possibly it might reveal a backport missing, but these cases should be rare.

Since the capacity on KubeVirt CI is reached every day as the graph `prowjobs in queue` shows [4], we might ask ourselves whether having this is worth the cost - admittedly this is only run per backport PR of which we don't have that many. 

Proposal is to remove the lane definition for all release branches [1] and remove the annotation that leads to forking the job definition for release branches [3].

@brianmcarey @jean-edouard @xpivarc WDYT?

_EDIT: adding the cost of the lane_

[1]: https://github.com/search?q=repo%3Akubevirt%2Fproject-infra+pull-kubevirt-check-tests-for-flakes+path%3A%2F%5Egithub%5C%2Fci%5C%2Fprow-deploy%5C%2Ffiles%5C%2Fjobs%5C%2Fkubevirt%5C%2Fkubevirt%5C%2F%2F&type=code
[2]: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/12389/pull-kubevirt-check-tests-for-flakes-1.3/1813712214830354432
[3]: https://github.com/kubevirt/project-infra/blob/38c9143d30ec44821961d99dd32a7015e4d17e51/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml#L261
[4]: https://grafana.ci.kubevirt.io/d/asdfare79we8r/prow-job-load-1h-resolution?orgId=1&from=now-30d&to=now&refresh=1d&viewPanel=3
[5]: https://prow.ci.kubevirt.io/?repo=kubevirt%2Fkubevirt&job=*check-tests-for-flakes*

**Comment by jean-edouard** [comment]
If it were free we would definitely want to keep it. It's a loss/gain tradeoff, and I feel like you only touched on the loss part. What's the gain? Do we need the capacity to do something else?
If the company that owns the test clusters just wants to reduce costs, then I agree this is a good place to start.

**Comment by dhiller** [comment]
Actually we are reaching max capacity of jobs to run every day: https://grafana.ci.kubevirt.io/d/asdfare79we8r/prow-job-load-1h-resolution?orgId=1&refresh=1d

the topmost graph shows whenever jobs are waiting for execution.

**Comment by dhiller** [comment]
As said in the meeting, since this is only one lane of many it might not make much sense to shave it.

**Comment by dhiller** [comment]
> If it were free we would definitely want to keep it. It's a loss/gain tradeoff, and I feel like you only touched on the loss part. What's the gain? Do we need the capacity to do something else? If the company that owns the test clusters just wants to reduce costs, then I agree this is a good place to start.

@jean-edouard I've updated the issue with some more data and context, hope that explains it better.

**Comment by xpivarc** [comment]
The question is, do we look actively on the backports? The lane is not required so the chance of spotting the failures is low. I am not sure about the cost but I am pretty sure we can have a quick look how this lane performs for release branches(# of failures in the past) and see the benefits of keeping it.

**Comment by dhiller** [comment]
/close

since we don't seem to be up to this. Reopen if you think otherwise.
