### ISSUE TITLE
v1.3.0 - node(s) didn't match Pod's node affinity/selector

### ISSUE THREAD

**Issue by ianb-mp** [kubevirt/kubevirt#12390]
**What happened**:

Installation of Kubevirt v1.3.0 fails with this error in the 'kubevirt' operator deploy job pod:
```
2 node(s) didn't match Pod's node affinity/selector. preemption: 0/2 nodes are available: 2 Preemption is not helpful for scheduling.
```

Installing v1.2.2 installs without error (on the same hardware/software stack). I looked for notes about upgrading, but couldn't see anything on the release page that looks relevant.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

My k8s cluster is running k0s with 2 worker nodes:
```
$ kubectl get nodes
NAME            STATUS   ROLES    AGE   VERSION
bne-lab-srv-6   Ready    worker   11m   v1.30.2+k0s
bne-lab-srv-7   Ready    worker   11m   v1.30.2+k0s
```
Metadata for each node:
<details>
<summary>bne-lab-srv-6</summary>

```yaml
metadata:
  annotations:
    csi.volume.kubernetes.io/nodeid: '{"zfs.csi.openebs.io":"bne-lab-srv-6"}'
    node.alpha.kubernetes.io/ttl: "0"
    projectcalico.org/IPv4Address: 192.168.2.6/30
    projectcalico.org/IPv4VXLANTunnelAddr: 10.244.140.134
    sriovnetwork.openshift.io/current-state: Idle
    sriovnetwork.openshift.io/state: Idle
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2024-07-17T23:55:37Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    feature.node.kubernetes.io/network-sriov.capable: "true"
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: bne-lab-srv-6
    kubernetes.io/os: linux
    node-role.kubernetes.io/worker: ""
    openebs.io/nodeid: bne-lab-srv-6
    openebs.io/nodename: bne-lab-srv-6
    openebs.io/zfs: "true"
  name: bne-lab-srv-6
  resourceVersion: "2076309"
  uid: a90bc7ab-8f5b-4707-9cba-a8d8236d5d00
```
</details>
<details>
<summary>bne-lab-srv-7</summary>

```yaml
metadata:
  annotations:
    csi.volume.kubernetes.io/nodeid: '{"zfs.csi.openebs.io":"bne-lab-srv-7"}'
    node.alpha.kubernetes.io/ttl: "0"
    projectcalico.org/IPv4Address: 192.168.2.10/30
    projectcalico.org/IPv4VXLANTunnelAddr: 10.244.20.128
    sriovnetwork.openshift.io/current-state: Idle
    sriovnetwork.openshift.io/state: Idle
    volumes.kubernetes.io/controller-managed-attach-detach: "true"
  creationTimestamp: "2024-07-17T23:55:41Z"
  labels:
    beta.kubernetes.io/arch: amd64
    beta.kubernetes.io/os: linux
    feature.node.kubernetes.io/network-sriov.capable: "true"
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: bne-lab-srv-7
    kubernetes.io/os: linux
    node-role.kubernetes.io/worker: ""
    openebs.io/nodeid: bne-lab-srv-7
    openebs.io/nodename: bne-lab-srv-7
    openebs.io/zfs: "true"
  name: bne-lab-srv-7
  resourceVersion: "2076590"
  uid: 6ccee137-f463-4653-af24-9b8344e8ed79
spec:
```
</details>

**Environment**:
- KubeVirt version (use `virtctl version`): v1.3.0
- Kubernetes version (use `kubectl version`): v1.30.2+k0s
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: bare metal intel x86_64
- OS (e.g. from /etc/os-release): Rocky Linux 9.4
- Kernel (e.g. `uname -a`): 5.14.0-427.24.1.el9_4.x86_64
- Install tools: k0sctl
- Others: N/A

**Comment by fossedihelm** [comment]
Hey, from what I see there are no control-plane nodes in your cluster.
Starting from v.1.3, for security reasons, KubeVirt components pods, like `virt-opertator`, `virt-api`, `virt-controller`, require to be scheduled onto control plane nodes; refs:
- https://github.com/kubevirt/kubevirt/pull/11659
- https://github.com/kubevirt/kubevirt/pull/11969
- https://github.com/kubevirt/kubevirt/pull/12014

Maybe you missed it but it is mentioned in the [release-1.3 notable changes](https://github.com/kubevirt/kubevirt/releases/tag/v1.3.0).
You should have at least one control-plane node in your cluster.
Thank you

**Comment by ianb-mp** [comment]
Ah, ok - that makes sense. 

I'm using k0s which by default deploys the control-plane without kubelet and so no way to run workloads on them: https://docs.k0sproject.io/stable/FAQ/#why-doesnt-kubectl-get-nodes-list-the-k0s-controllers

I will raise an issue with the k0s project.

**Comment by fossedihelm** [comment]
@ianb-mp Consider that you can also define a custom node placement in your KubeVirt CR, that will override the default configuration.
https://kubevirt.io/user-guide/cluster_admin/installation/#restricting-kubevirt-components-node-placement

**Comment by ianb-mp** [comment]
> @ianb-mp Consider that you can also define a custom node placement in your KubeVirt CR, that will override the default configuration. https://kubevirt.io/user-guide/cluster_admin/installation/#restricting-kubevirt-components-node-placement

Thankyou, that's very helpful.

**Comment by kalmufti** [comment]
Facing the same issue, though I have a controller node, and everything runs on bare-metal. Any help appreciated.

```bash
  Warning  FailedScheduling  2m11s (x6 over 27m)  default-scheduler  0/4 nodes are available: 1 node(s) had untolerated taint {node-role.kubernetes.io/controller: }, 3 node(s) didn't match Pod's node affinity/selector. preemption: 0/4 nodes are available: 4 Preemption is not helpful for scheduling.
```

All servers reports ```kvm``` support:
```bash
lsmod | grep -i kvm
kvm_intel             401408  0
kvm                  1294336  1 kvm_intel
irqbypass              12288  1 kvm
```

**Comment by xpivarc** [comment]
> ```shell
> 1 node(s) had untolerated taint {node-role.kubernetes.io/controller:
> ```

The important part is `1 node(s) had untolerated taint {node-role.kubernetes.io/controller:`.

**Comment by waldner** [comment]
I don't seem to be able to overcome this limitation, I've set the following in my kubevirt CR:

```
  infra:
    nodePlacement:
      affinity: {}
      nodeSelector: {}
  workloads:
    nodePlacement:
      affinity: {}
      nodeSelector: {}
```

Yet there's still a pod that gets created with the wrong affinity:

```
$ kubectl get pods -n kubevirt kubevirt-80252be4d865df289d97324e2124b7e869e4df78-jobp9xh28jcr7 -o yaml
...
spec:
  affinity:
    nodeAffinity:
      preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
          - key: node-role.kubernetes.io/worker
            operator: DoesNotExist
        weight: 100
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: node-role.kubernetes.io/control-plane
            operator: Exists
        - matchExpressions:
          - key: node-role.kubernetes.io/master
            operator: Exists
```

Am I doing something wrong?

**Comment by waldner** [comment]
This block also don't make the pod schedule:

```
  infra:
    nodePlacement:
      nodeSelector:
        kubernetes.io/os: linux
  workloads:
    nodePlacement:
      nodeSelector:
        kubernetes.io/os: linux
```

**Comment by depach** [comment]
I found this issue after experiencing this problem while following https://kubevirt.io/quickstart_cloud/

I am using AWS EKS , and as far as I understand, you only control the worker nodes?

I think a note about this should be added on the above url

**Comment by depach** [comment]
If anyone else is struggling on AWS EKS , this comment on the Azure/AKS helped me

https://github.com/Azure/AKS/issues/4613#issuecomment-2449313693

I tried applying the config detailed in https://kubevirt.io/user-guide/cluster_admin/installation/#restricting-kubevirt-components-node-placement but I still had the error

**Comment by kalmufti** [comment]
If it helps this is how I solved my issue:

```yaml
---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates: []
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
  infra:
    nodePlacement:
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
```
