### ISSUE TITLE
about instance type create error

### ISSUE THREAD

**Issue by zhujunxing123** [kubevirt/kubevirt#12391]
May I consult with experts? When I use the instance type feature of kubevirt manager to create a new cluster instance type, it prompts' undefined '. Then, when I check netwokr in the browser, I find a 404 error. What is the general reason for this error?
The kubevirt version is 0.59 and the manager version is 1.4

**Comment by zhujunxing123** [comment]
![image](https://github.com/user-attachments/assets/112b3dee-dece-428d-a51b-6bda97a47332)

**Comment by zhujunxing123** [comment]
![image](https://github.com/user-attachments/assets/f2bad460-3986-4f96-9dc6-3b724cc075eb)

**Comment by aburdenthehand** [comment]
@feitnomore I believe you are the best person for this. 
(Please ping lyarwood if it is something to do with the underlying instancetypes)

**Comment by feitnomore** [comment]
This is a cross-post from [kubevirt-manager #68](https://github.com/kubevirt-manager/kubevirt-manager/issues/68).
Some workarounds were already suggested over there, @zhujunxing123 never answered back.
This has to do with the fact that the API provably got deprecated and moved from v1alpha1 to v1.

**Comment by 0xFelix** [comment]
@zhujunxing123 Not able to reproduce this with KubeVirt `0.59.0`, `0.59.2` or `1.3.0` and https://github.com/kubevirt-manager/kubevirt-manager/commit/e07c994cee5c055f25ef5fada1abc7607c346806. Perhaps this is an issue with permissions on your side?

@feitnomore kubevirt-manager should be updated to use `v1beta1` of the instancetypes api because `v1alpha1` has been deprecated for quite some time now.

**Comment by 0xFelix** [comment]
That's a good question. There is a table of instancetype api versions in the [user guide](https://kubevirt.io/user-guide/user_workloads/instancetypes/#instance-types-and-preferences) and the changes should have also been mentioned in the KubeVirt release notes. There is no roadmap document for removal of the old api versions though.

**Comment by zhujunxing123** [comment]
> Contributor

![image](https://github.com/user-attachments/assets/f52727e2-c33e-49e2-9cb0-bee7360030ee)

**Comment by zhujunxing123** [comment]
Thank you to all the experts for their answers. After replacing kubevirt with version 1.1, the issue was resolved

**Comment by 0xFelix** [comment]
/close

Thanks for the update.
