### ISSUE TITLE
List all reasons why LiveMigration is not possible in appropriate condition

### ISSUE THREAD

**Issue by awels** [kubevirt/kubevirt#12404]
**Is your feature request related to a problem? Please describe**:
My problem is that I want to be able to tell my users why live migration is not possible before I attempt a live migration. In particular I want to do a storage live migration. The issue I am having is that only the first issue is listed in the condition on the VM, and not any other issues. This means the user fixes one issue. Then still cannot live migrate and has to check again, fix the next, etc.

**Describe the solution you'd like**:
I would love for the condition to list ALL the issues we have detected instead of just one. This has two benefits. One the user sees all the issues in one place and can attempt to remedy them all at once if possible. Second in my case I am using storage live migration which allows migration of RWO volumes, and if there are other issues my users will never see those issue because the RWO message is the first one shown.

**Describe alternatives you've considered**:
Maybe move the storage conditions to the bottom of the list so it doesn't always show up first.

**Additional context**:
NONE

**Comment by mhenriks** [comment]
How about a new "ready for storage migration" condition?

**Comment by alicefr** [comment]
> How about a new "ready for storage migration" condition?

Yes, we discussed the solution proposed in https://github.com/kubevirt/kubevirt/pull/12438 and one of the option was to create a new condition.

**Comment by alicefr** [comment]
Solved by https://github.com/kubevirt/kubevirt/pull/12395
