### ISSUE TITLE
Missing route entries in virt-launcher pods when using the OVS CNI. Issue observed with Kubevirt ver 1.1.x and later releases.

### ISSUE THREAD

**Issue by vinoddiamanti** [kubevirt/kubevirt#12413]
**What happened**:
The virt-launcher pod is inaccessible when using OVS CNI.
There was an observed issue with missing route entries in virt-launcher pods when using the OVS CNI. 
This problem has been identified in kubevirt versions 1.1.x and later releases.
Initially, the eth0 interface in the pod had 4 route entries configured. However, after virt-handler created the virt-launcher pod, only 3 route entries remained for eth0.
The missing route entry is "172.30.0.0      0.0.0.0         255.255.0.0     U     100    0        0  eth0"

In Case 1, the scenario functions correctly with kubevirt version 1.0.0. 
[root@vinod-centos ~]# ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1446
        inet 172.30.4.4  netmask 255.255.252.0  broadcast 172.30.7.255
        inet6 fe80::8fc4:4ba9:a542:ef7d  prefixlen 64  scopeid 0x20<link>
        ether 02:98:90:9e:b0:75  txqueuelen 1000  (Ethernet)
        RX packets 399  bytes 37116 (36.2 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 379  bytes 32016 (31.2 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.122.1  netmask 255.255.255.0  broadcast 192.168.122.255
        ether 52:54:00:be:d2:1c  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[root@vinod-centos ~]# 
[root@vinod-centos ~]# route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.30.4.1      0.0.0.0         UG    100    0        0 eth0
10.0.0.0        172.30.4.1      255.255.255.0   UG    100    0        0 eth0
172.30.0.0      0.0.0.0         255.255.0.0     U     100    0        0 eth0
172.30.4.0      0.0.0.0         255.255.252.0   U     100    0        0 eth0
192.168.122.0   0.0.0.0         255.255.255.0   U     0      0        0 virbr0
[root@vinod-centos ~]# 
[root@vinod-centos ~]# ping 172.30.0.2 -c 1
PING 172.30.0.2 (172.30.0.2) 56(84) bytes of data.
64 bytes from 172.30.0.2: icmp_seq=1 ttl=64 time=0.762 ms

--- 172.30.0.2 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 0.762/0.762/0.762/0.000 ms
[root@vinod-centos ~]# 

----------

In Case 2, the scenario does not work as expected with kubevirt versions >= 1.1.x.
diamanti@test-centos-1 ~]$ ifconfig
eth0: flags=4163<UP,BROADCAST,RUNNING,MULTICAST>  mtu 1446
        inet 172.30.8.7  netmask 255.255.252.0  broadcast 172.30.11.255
        inet6 fe80::7664:2ae9:d8e2:221e  prefixlen 64  scopeid 0x20<link>
        ether 76:e8:88:d4:3f:0a  txqueuelen 1000  (Ethernet)
        RX packets 910  bytes 331801 (324.0 KiB)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 1068  bytes 81304 (79.3 KiB)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

lo: flags=73<UP,LOOPBACK,RUNNING>  mtu 65536
        inet 127.0.0.1  netmask 255.0.0.0
        inet6 ::1  prefixlen 128  scopeid 0x10<host>
        loop  txqueuelen 1000  (Local Loopback)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

virbr0: flags=4099<UP,BROADCAST,MULTICAST>  mtu 1500
        inet 192.168.122.1  netmask 255.255.255.0  broadcast 192.168.122.255
        ether 52:54:00:be:d2:1c  txqueuelen 1000  (Ethernet)
        RX packets 0  bytes 0 (0.0 B)
        RX errors 0  dropped 0  overruns 0  frame 0
        TX packets 0  bytes 0 (0.0 B)
        TX errors 0  dropped 0 overruns 0  carrier 0  collisions 0

[diamanti@test-centos-1 ~]$
[diamanti@test-centos-1 ~]$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         172.30.8.1      0.0.0.0         UG    100    0        0 eth0
10.0.0.0        172.30.8.1      255.255.255.0   UG    100    0        0 eth0
172.30.8.0      0.0.0.0         255.255.252.0   U     100    0        0 eth0
192.168.122.0   0.0.0.0         255.255.255.0   U     0      0        0 virbr0
[diamanti@test-centos-1 ~]$ ping 172.30.4.5 -c 1
PING 172.30.4.5 (172.30.4.5) 56(84) bytes of data.

--- 172.30.4.5 ping statistics ---
1 packets transmitted, 0 received, 100% packet loss, time 0ms

**What you expected to happen**:
We expect the same route entry in the virt-launcher pod as was present in the pod container before. Upon reviewing the kubevirt code, we identified an issue in the function 'filterRoutesByNonLocalDestination', which eliminates local route entries.

**How to reproduce it (as minimally and precisely as possible)**:
You can use any OVS cni binaries OR you can use Diamanti cluster.

**Additional context**:
I have attached the virt-handler log file 'virt-handler-1.0.0.log' from a working kubevirt version 1.0.0, and the log file 'virt-handler-1.2.0.log' from a non-working kubevirt version 1.2.0.

Case-1 Working virt-handler-1.0.0.log
----
{"component":"virt-handler","level":"info","msg":"got to add 4 routes to the DhcpConfig","pos":"bridge.go:93","timestamp":"2024-07-19T14:19:19.995872Z"}
{"component":"virt-handler","level":"info","msg":"the default route is: {Ifindex: 3 Dst: <nil> Src: <nil> Gw: 172.30.4.1 Flags: [] Table: 254}","pos":"bridge.go:179","timestamp":"2024-07-19T14:19:19.995915Z"}
{"component":"virt-handler","level":"info","msg":"route: {Ifindex: 3 Dst: <nil> Src: <nil> Gw: 172.30.4.1 Flags: [] Table: 254}","pos":"address.go:127","timestamp":"2024-07-19T14:19:19.995933Z"}
{"component":"virt-handler","level":"info","msg":"route: {Ifindex: 3 Dst: 10.0.0.0/24 Src: <nil> Gw: 172.30.4.1 Flags: [] Table: 254}","pos":"address.go:127","timestamp":"2024-07-19T14:19:19.995948Z"}
{"component":"virt-handler","level":"info","msg":"route: {Ifindex: 3 Dst: 172.30.0.0/16 Src: <nil> Gw: <nil> Flags: [] Table: 254}","pos":"address.go:127","timestamp":"2024-07-19T14:19:19.995964Z"}
{"component":"virt-handler","level":"info","msg":"route: {Ifindex: 3 Dst: 172.30.4.0/22 Src: 172.30.4.4 Gw: <nil> Flags: [] Table: 254}","pos":"address.go:127","timestamp":"2024-07-19T14:19:19.995980Z"}
{"component":"virt-handler","level":"info","msg":"The generated dhcpConfig: DHCPConfig: { Name: , IPv4: 172.30.4.4/22 eth0, IPv6: <nil>, MAC: 02:98:90:9e:b0:75, AdvertisingIPAddr: <nil>, MTU: 0, Gateway: 172.30.4.1, IPAMDisabled: false}","pos":"podnic.go:199","timestamp":"2024-07-19T14:19:19.996003Z"}
{"component":"virt-handler","level":"info","msg":"The generated libvirt domain interface: {Address:<nil> Type: TrustGuestRxFilters: Source:{Network: Device: Bridge: Mode: Address:<nil>} Target:<nil> Model:<nil> MAC:0xc00190d290 MTU:<nil> BandWidth:<nil> BootOrder:<nil> LinkState:<nil> FilterRef:<nil> Alias:<nil> Driver:<nil> Rom:<nil> ACPI:<nil>}","pos":"podnic.go:208","timestamp":"2024-07-19T14:19:19.996425Z"}
----

Case-2: Not working virt-handler-1.2.0.log
-----
{"component":"virt-handler","level":"info","msg":"Current pod network: {\"interfaces\":[{\"name\":\"lo\",\"index\":1,\"type\":\"device\",\"state\":\"unknown\",\"mtu\":65536,\"ethtool\":{\"feature\":{\"tx-checksum\":true}},\"IPv4\":{\"enabled\":true,\"address\":[{\"IP\":\"127.0.0.1\",\"prefix-length\":8}]},\"IPv6\":{\"enabled\":true,\"address\":[{\"IP\":\"::1\",\"prefix-length\":128}]},\"linux-stack\":{\"ip4-route-local-net\":false,\"port-learning\":false},\"Metadata\":null},{\"name\":\"mgmt0\",\"index\":2,\"type\":\"veth\",\"state\":\"up\",\"mac-address\":\"92:31:67:ee:c2:f3\",\"mtu\":1500,\"ethtool\":{\"feature\":{\"tx-checksum\":true}},\"IPv4\":{\"enabled\":true,\"address\":[{\"IP\":\"172.20.0.18\",\"prefix-length\":24}]},\"IPv6\":{\"enabled\":true,\"address\":[{\"IP\":\"fe80::9031:67ff:feee:c2f3\",\"prefix-length\":64}]},\"linux-stack\":{\"ip4-route-local-net\":false,\"port-learning\":false},\"Metadata\":null},{\"name\":\"eth0\",\"index\":3,\"type\":\"veth\",\"state\":\"up\",\"mac-address\":\"76:e8:88:d4:3f:0a\",\"mtu\":1446,\"ethtool\":{\"feature\":{\"tx-checksum\":true}},\"IPv4\":{\"enabled\":true,\"address\":[{\"IP\":\"172.30.8.7\",\"prefix-length\":22}]},\"IPv6\":{\"enabled\":true,\"address\":[{\"IP\":\"fe80::74e8:88ff:fed4:3f0a\",\"prefix-length\":64}]},\"linux-stack\":{\"ip4-route-local-net\":false,\"port-learning\":false},\"Metadata\":null}],\"routes\":{\"running\":[{\"destination\":\"0.0.0.0/0\",\"next-hop-interface\":\"eth0\",\"next-hop-address\":\"172.30.8.1\",\"table-id\":254},{\"destination\":\"0.0.0.0/0\",\"next-hop-interface\":\"mgmt0\",\"next-hop-address\":\"172.20.0.1\",\"table-id\":254},{\"destination\":\"10.0.0.0/24\",\"next-hop-interface\":\"eth0\",\"next-hop-address\":\"172.30.8.1\",\"table-id\":254},{\"destination\":\"172.20.0.0/24\",\"next-hop-interface\":\"mgmt0\",\"table-id\":254},{\"destination\":\"172.30.0.0/16\",\"next-hop-interface\":\"eth0\",\"table-id\":254},{\"destination\":\"172.30.8.0/22\",\"next-hop-interface\":\"eth0\",\"table-id\":254},{\"destination\":\"fe80::/64\",\"next-hop-interface\":\"mgmt0\",\"table-id\":254},{\"destination\":\"fe80::/64\",\"next-hop-interface\":\"eth0\",\"table-id\":254}]},\"linux-stack\":{\"ipv4\":{\"arp-ignore\":0,\"forwarding\":true,\"ping-group-range\":[1,0],\"unprivileged-port-start\":1024},\"ipv6\":{\"forwarding\":false}}}","pos":"netpod.go:159","timestamp":"2024-07-19T14:29:23.062384Z"}
{"component":"virt-handler","level":"info","msg":"The generated dhcpConfig: DHCPConfig: { Name: , IPv4: 172.30.8.7/22, IPv6: <nil>, MAC: 76:e8:88:d4:3f:0a, AdvertisingIPAddr: <nil>, MTU: 0, Gateway: 172.30.8.1, IPAMDisabled: false, Routes: &[{Ifindex: 0 Dst: <nil> Src: <nil> Gw: 172.30.8.1 Flags: [] Table: 0} {Ifindex: 0 Dst: 10.0.0.0/24 Src: <nil> Gw: 172.30.8.1 Flags: [] Table: 0}]}\nRoutes: &[{Ifindex: 0 Dst: <nil> Src: <nil> Gw: 172.30.8.1 Flags: [] Table: 0} {Ifindex: 0 Dst: 10.0.0.0/24 Src: <nil> Gw: 172.30.8.1 Flags: [] Table: 0}]","pos":"discoverbridge.go:76","timestamp":"2024-07-19T14:29:23.062729Z"}
{"component":"virt-handler","level":"info","msg":"The generated domain interface data: mac = 76:e8:88:d4:3f:0a","pos":"discoverbridge.go:92","timestamp":"2024-07-19T14:29:23.063080Z"}
------
[virt-handler-1.0.0.log](https://github.com/user-attachments/files/16314595/virt-handler-1.0.0.log)
[virt-handler-1.2.0.log](https://github.com/user-attachments/files/16314602/virt-handler-1.2.0.log)
[virt-handler-1.2.0.log](https://github.com/user-attachments/files/16314614/virt-handler-1.2.0.log)
[virt-handler-1.0.0.log](https://github.com/user-attachments/files/16314615/virt-handler-1.0.0.log)

**Environment**:
- KubeVirt version (use `virtctl version`): v1.2.0
- Kubernetes version (use `kubectl version`): v1.28.9
- VM or VMI specifications: 
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: test-centos-1
  namespace: default
spec:
  running: false
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: test-centos-1
      annotations:
        diamanti.com/endpoint0: '{"network":"red","perfTier":"high"}'
    spec:
      architecture: amd64
      domain:
        cpu:
          cores: 10
        devices:
          blockMultiQueue: true
          disks:
          - disk:
              bus: virtio
            name: test-centos-1-os-disk
          - dedicatedIOThread: true
            disk:
              bus: virtio
            name: test-centos-1-data
        ioThreadsPolicy: auto
        machine:
          type: q35
        resources:
          requests:
            memory: 10Gi
      volumes:
      - name: test-centos-1-os-disk
        persistentVolumeClaim:
          claimName: test-centos-1-os
      - name: test-centos-1-data
        persistentVolumeClaim:
          claimName: test-centos-1-data

- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by vinoddiamanti** [comment]
Below is a proposed code snippet for filtering out local routes:

// filterRoutesByNonLocalDestination filters out local routes (the destination is of the local link).
// Default routes should not be filter out.
func filterRoutesByNonLocalDestination(linkRoutes []nmstate.Route, addr *vishnetlink.Addr) ([]nmstate.Route, error) {
	var otherRoutes []nmstate.Route
	for _, route := range linkRoutes {
		_, dstIPNet, perr := net.ParseCIDR(route.Destination)
		if perr != nil {
			return nil, perr
		}
		isDefaultRoute := route.Destination == nmstate.DefaultDestinationRoute(vishnetlink.FAMILY_V4).String()
                // Old logic
		//localDestination := !isDefaultRoute && dstIPNet.Contains(addr.IP)

               //New logic
              //localDestination := !isDefaultRoute && (dstIPNet.String() == addr.IPNet.String())

               localDestination := !isDefaultRoute &&
		if !localDestination {
			otherRoutes = append(otherRoutes, route)
		}
	}
	return otherRoutes, nil
}


With this proposed solution, it will function correctly across all Container Network Interfaces (CNIs). 
Below are the input and output results for dhcpconfig:

INPUT:
0.0.0.0 172.30.4.1 0.0.0.0 UG 100 0 0 eth0
10.0.0.0 172.30.4.1 255.255.255.0 UG 100 0 0 eth0
172.30.0.0 0.0.0.0 255.255.0.0 U 100 0 0 eth0
172.30.4.0 0.0.0.0 255.255.252.0 U 100 0 0 eth0


OUTPUT for dhcpconfig
Case1: With old logic
0.0.0.0 172.30.4.1 0.0.0.0 UG 100 0 0 eth0
10.0.0.0 172.30.4.1 255.255.255.0 UG 100 0 0 eth0

Case2: With proposed logic
0.0.0.0 172.30.4.1 0.0.0.0 UG 100 0 0 eth0
10.0.0.0 172.30.4.1 255.255.255.0 UG 100 0 0 eth0
172.30.0.0 0.0.0.0 255.255.0.0 U 100 0 0 eth0

**Comment by orelmisan** [comment]
Thank you for reporting this issue @vinoddiamanti 
We will have a look.

/sig network

**Comment by vinoddiamanti** [comment]
Hi,

Do you have any updates on this?

**Comment by orelmisan** [comment]
Hi @vinoddiamanti, I've been quite busy lately and will be able to look into it next week.

Thank you for your understanding.

**Comment by vinoddiamanti** [comment]
Please let me know the version in which the fix will be available and when it will be released.

**Comment by orelmisan** [comment]
Hi @vinoddiamanti, @EdDev and myself have looked into this issue, and we think we understand what the problem is.
In order for us to be sure, could you please provide the output of `ip link` [1], `ip addr` [2] and `ip route` [3] from within the `virt-launcher` pod's `compute` container and the running VM?

```shell
$ kubectl exec -n <namespace> -it virt-launcher-<name> sh
```

Thank you for the analysis, it helped us understand the problem faster.

> Please let me know the version in which the fix will be available and when it will be released.

The issue was added to our work queue, but we would be happy to accept code contributions in case you are interested.

[1] https://man7.org/linux/man-pages/man8/ip-link.8.html
[2] https://man7.org/linux/man-pages/man8/ip-address.8.html
[3] https://man7.org/linux/man-pages/man8/ip-route.8.html
[4] https://access.redhat.com/sites/default/files/attachments/rh_ip_command_cheatsheet_1214_jcs_print.pdf

**Comment by vinoddiamanti** [comment]
Hi @orelmisan ,

Please find the below output from Pod virt-launcher-test-centos-1-vfnxq 
`[diamanti@appserv76 ~]$ kubectl exec -ti virt-launcher-test-centos-1-vfnxq -- sh
sh-5.1$ ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: mgmt0@if178: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP mode DEFAULT group default 
    link/ether a6:13:ed:5d:25:7b brd ff:ff:ff:ff:ff:ff link-netnsid 0
3: eth0-nic@if179: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1446 qdisc noqueue master k6t-eth0 state UP mode DEFAULT group default 
    link/ether 2e:69:d3:5f:f8:9b brd ff:ff:ff:ff:ff:ff link-netnsid 0
4: k6t-eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1446 qdisc noqueue state UP mode DEFAULT group default qlen 1000
    link/ether 2e:69:d3:5f:f8:9b brd ff:ff:ff:ff:ff:ff
5: tap0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1446 qdisc fq_codel master k6t-eth0 state UP mode DEFAULT group default qlen 1000
    link/ether ee:5f:9e:37:91:c3 brd ff:ff:ff:ff:ff:ff
6: eth0: <BROADCAST,NOARP> mtu 1446 qdisc noop state DOWN mode DEFAULT group default qlen 1000
    link/ether ea:65:d5:ff:7f:64 brd ff:ff:ff:ff:ff:ff
sh-5.1$ 
sh-5.1$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: mgmt0@if178: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default 
    link/ether a6:13:ed:5d:25:7b brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.20.0.85/24 brd 172.20.0.255 scope global mgmt0
       valid_lft forever preferred_lft forever
    inet6 fe80::a413:edff:fe5d:257b/64 scope link 
       valid_lft forever preferred_lft forever
3: eth0-nic@if179: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1446 qdisc noqueue master k6t-eth0 state UP group default 
    link/ether 2e:69:d3:5f:f8:9b brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::2c69:d3ff:fe5f:f89b/64 scope link 
       valid_lft forever preferred_lft forever
4: k6t-eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1446 qdisc noqueue state UP group default qlen 1000
    link/ether 2e:69:d3:5f:f8:9b brd ff:ff:ff:ff:ff:ff
    inet 169.254.75.10/32 scope global k6t-eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::2c69:d3ff:fe5f:f89b/64 scope link 
       valid_lft forever preferred_lft forever
5: tap0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1446 qdisc fq_codel master k6t-eth0 state UP group default qlen 1000
    link/ether ee:5f:9e:37:91:c3 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::ec5f:9eff:fe37:91c3/64 scope link 
       valid_lft forever preferred_lft forever
6: eth0: <BROADCAST,NOARP> mtu 1446 qdisc noop state DOWN group default qlen 1000
    link/ether ea:65:d5:ff:7f:64 brd ff:ff:ff:ff:ff:ff
    inet 172.30.8.10/22 brd 172.30.11.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::e865:d5ff:feff:7f64/64 scope link 
       valid_lft forever preferred_lft forever
sh-5.1$ 
sh-5.1$ ip route
default via 172.20.0.1 dev mgmt0 metric 1000 
172.20.0.0/24 dev mgmt0 proto kernel scope link src 172.20.0.85 
sh-5.1$ 
`

And below output from running VM
`ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN mode DEFAULT group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1446 qdisc pfifo_fast state UP mode DEFAULT group default qlen 1000
    link/ether ea:65:d5:ff:7f:64 brd ff:ff:ff:ff:ff:ff
3: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN mode DEFAULT group default qlen 1000
    link/ether 52:54:00:be:d2:1c brd ff:ff:ff:ff:ff:ff
4: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast master virbr0 state DOWN mode DEFAULT group default qlen 1000
    link/ether 52:54:00:be:d2:1c brd ff:ff:ff:ff:ff:ff

ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1446 qdisc pfifo_fast state UP group default qlen 1000
    link/ether ea:65:d5:ff:7f:64 brd ff:ff:ff:ff:ff:ff
    inet 172.30.8.10/22 brd 172.30.11.255 scope global noprefixroute dynamic eth0
       valid_lft 86243587sec preferred_lft 86243587sec
    inet6 fe80::e1c1:a316:b3b9:8f53/64 scope link noprefixroute
       valid_lft forever preferred_lft forever
3: virbr0: <NO-CARRIER,BROADCAST,MULTICAST,UP> mtu 1500 qdisc noqueue state DOWN group default qlen 1000
    link/ether 52:54:00:be:d2:1c brd ff:ff:ff:ff:ff:ff
    inet 192.168.122.1/24 brd 192.168.122.255 scope global virbr0
       valid_lft forever preferred_lft forever
4: virbr0-nic: <BROADCAST,MULTICAST> mtu 1500 qdisc pfifo_fast master virbr0 state DOWN group default qlen 1000
    link/ether 52:54:00:be:d2:1c brd ff:ff:ff:ff:ff:ff

ip route
default via 172.30.8.1 dev eth0 proto dhcp metric 100
10.0.0.0/24 via 172.30.8.1 dev eth0 proto dhcp metric 100
172.30.8.0/22 dev eth0 proto kernel scope link src 172.30.8.10 metric 100
192.168.122.0/24 dev virbr0 proto kernel scope link src 192.168.122.1
`

**Comment by vinoddiamanti** [comment]
Hi @orelmisan ,

I created busybox pod which is not VM.
Below is the output from busybox container. That will help you to figure our that why route of eth0 not reflected in VM

[diamanti@appserv78 ~]$ kubectl exec -ti busybox-deployment1-7df48b6fcc-7tdh4 -- sh
/ # ip link
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
2: mgmt0@if176: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue 
    link/ether a2:61:8a:34:80:1f brd ff:ff:ff:ff:ff:ff
3: eth0@if177: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1446 qdisc noqueue 
    link/ether 5e:3b:b7:37:c1:08 brd ff:ff:ff:ff:ff:ff
/ # 
/ # ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: mgmt0@if176: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1500 qdisc noqueue 
    link/ether a2:61:8a:34:80:1f brd ff:ff:ff:ff:ff:ff
    inet 172.20.0.84/24 brd 172.20.0.255 scope global mgmt0
       valid_lft forever preferred_lft forever
    inet6 fe80::a061:8aff:fe34:801f/64 scope link 
       valid_lft forever preferred_lft forever
3: eth0@if177: <BROADCAST,MULTICAST,UP,LOWER_UP,M-DOWN> mtu 1446 qdisc noqueue 
    link/ether 5e:3b:b7:37:c1:08 brd ff:ff:ff:ff:ff:ff
    inet 172.30.8.9/22 brd 172.30.11.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5c3b:b7ff:fe37:c108/64 scope link 
       valid_lft forever preferred_lft forever
/ # 
/ # ip route
default via 172.30.8.1 dev eth0 
default via 172.20.0.1 dev mgmt0  metric 1000 
10.0.0.0/24 via 172.30.8.1 dev eth0 
172.20.0.0/24 dev mgmt0 scope link  src 172.20.0.84 
172.30.0.0/16 dev eth0 
172.30.8.0/22 dev eth0 scope link  src 172.30.8.9 
/ #

**Comment by orelmisan** [comment]
@vinoddiamanti Thank you for providing the information.

**Comment by vinoddiamanti** [comment]
Hi @orelmisan 

Do you have any updates on this?

**Comment by vinoddiamanti** [comment]
Hi @orelmisan ,

Thank you for looking into this issue. 
Could you please let me know which release version will include this fix?

**Comment by orelmisan** [comment]
> Hi @orelmisan ,
> 
> Thank you for looking into this issue. Could you please let me know which release version will include this fix?

If the PR will be approved in the next month or so, it will be included in v1.4.0.

**Comment by vinoddiamanti** [comment]
Hi @orelmisan ,

Thank you for the update. Please let me know once the release version with this fix is available, so I can test it on my cluster.

**Comment by orelmisan** [comment]
@vinoddiamanti, The v1.4.0 release schedule is available [here](https://github.com/kubevirt/sig-release/blob/main/releases/v1.4/schedule.md).

The fix was also [backported](https://github.com/kubevirt/kubevirt/pull/12702) to release-1.3. 
If there will be a v1.3.2, it will be there as well.

**Comment by vinoddiamanti** [comment]
Hi @orelmisan ,

Thanks for the update. I validated the fix with the v1.4.0-alpha release, and it’s working now.

Since the issue originated from KubeVirt version v1.1.0, are you planning to address it in all versions and release a new version for each?

**Comment by orelmisan** [comment]
Hi @vinoddiamanti, thank you for verifying the fix.

Since this issue is dependent on a specific CNI being used and since I don't know when (or if) there will be patch versions for `release-1.3`, `release-1.2` and `release-1.1`, I currently don't see a reason to further backport the fix.

In case you are interested, please feel free to raise it on KubeVirt's [community meeting](https://kubevirt.io/community/).
