### ISSUE TITLE
about api question

### ISSUE THREAD

**Issue by zhujunxing123** [kubevirt/kubevirt#12453]
Excuse me, experts. I used the local openai/v2 interface to build the Swagger service, but it seems that I have found an interface for creating virtual machines. Which specific interface is used for creating virtual machines?
Another issue is that most interfaces will report a 401 error. Where does the authentication here come from? Get token from k8s? Is there any other way? Can you give me a specific way? Thank you very much.

**Comment by am6737** [comment]
> Excuse me, experts. I used the local openai/v2 interface to build the Swagger service, but it seems that I have found an interface for creating virtual machines. Which specific interface is used for creating virtual machines? Another issue is that most interfaces will report a 401 error. Where does the authentication here come from? Get token from k8s? Is there any other way? Can you give me a specific way? Thank you very much.


Hi @zhujunxing123 

The essence of creating a virtual machine is creating the corresponding custom resource. The Kubernetes documentation on Custom Resources can be found [here](https://kubernetes.io/docs/reference/kubernetes-api/extend-resources/custom-resource-definition-v1/).

To create a virtual machine, you should use the following API path: `/apis/kubevirt.io/v1/namespaces/default/virtualmachines`. 

For authentication issues, you can either create a `ServiceAccount` to get a token or use the certificate from `~/.kube/config`.

For simplicity, I use `kubectl proxy` to handle authentication and create the virtual machine using curl. Here is an example:

1. Start the kubectl proxy:
```bash
kubectl proxy --port 8080
```

2. Use curl to send a POST request:

```bash
curl -X POST http://127.0.0.1:8080/apis/kubevirt.io/v1/namespaces/default/virtualmachines \
-H "Content-Type: application/yaml" \
--data-binary @vm.yaml
```

**Comment by zhujunxing123** [comment]
Thank you for your answer. I know how to proceed with the work now
