### ISSUE TITLE
Question: How to advertise public IP given to KubeVirt VM Service to the external world

### ISSUE THREAD

**Issue by anjuls** [kubevirt/kubevirt#12479]
I have assigned a public IP to a service attached to the KubeVirt VM. When I connect with the Internet from the VM, it exposes the gateway IP. Instead, I want to expose my public IP attached to the VM service.  Cilium is used as CNI and it is also doing IPAM and we use IPVS.

**Comment by sbrivio-rh** [comment]
If your pod sees the public IP address (I'm not sure how it works with Cilium), then with the [passt binding](https://kubevirt.io/user-guide/network/net_binding_plugins/passt/) you should get your public IP address propagated all the way into the guest (see "Pod IP in guest" in the page I linked).

**Comment by brianmcarey** [comment]
@anjuls are you happy to close this issue?

**Comment by anjuls** [comment]
Thanks for the pointer I will close it for now.
