### ISSUE TITLE
Rocky Linux VM not booting

### ISSUE THREAD

**Issue by ryebridge** [kubevirt/kubevirt#12517]
**What happened**:

VM is not booting, just showing a transparent screen when I type:

./virtctl-v1.3.0-linux-amd64 console rocky

![Rocky](https://github.com/user-attachments/assets/45e5e70c-ffb8-477a-ade9-695bdbdfbcaa)

**What you expected to happen**:

Should see Rocky linux VM and log in...

**How to reproduce it (as minimally and precisely as possible)**:

Steps to reproduce the behavior.

export VERSION=$(curl -s https://api.github.com/repos/kubevirt/containerized-data-importer/releases/latest | grep '"tag_name":' | sed -E 's/.*"([^"]+)".*/\1/')
kubectl create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-operator.yaml
kubectl create -f https://github.com/kubevirt/containerized-data-importer/releases/download/$VERSION/cdi-cr.yaml

kubectl port-forward -n cdi service/cdi-uploadproxy 18443:443

./virtctl-v1.3.0-linux-amd64 image-upload --image-path=/var/Rocky-9.4-x86_64-dvd.iso --pvc-name=rockyisohd  --namespace=kubevirt --size=10Gi --storage-class=nfs-client --uploadproxy-url=https://127.0.0.1:18443  --insecure --wait-secs=240

./virtctl-v1.3.0-linux-amd64 image-upload \
  --image-path=/kubevirt/Rocky-9.4-x86_64-boot.iso \
  --pvc-name=rockyisohd \
  --namespace=kubevirt \
  --size=10Gi \
  --storage-class=nfs-client \
  --uploadproxy-url=https://127.0.0.1:18443 \
  --insecure \
  --wait-secs=240

kubectl apply -f - <<EOF
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: linhd
  namespace: kubevirt
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 20Gi
  storageClassName: nfs-client
EOF

apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  generation: 1
  labels:
    kubevirt.io/os: linux
  name: rocky
  namespace: kubevirt
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm1
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - bootOrder: 2
            cdrom:
              bus: sata
            name: cdromiso
          - disk:
              bus: virtio
            name: harddrive
            bootOrder: 1
          - cdrom:
              bus: sata
              readonly: true
            name: virtio-drivers
        machine:
          type: q35
        resources:
          requests:
            memory: 4096M
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: rockyisohd
      - name: harddrive
        persistentVolumeClaim:
          claimName: linhd
      - name:  virtio-drivers
        containerDisk:
          image: kubevirt/virtio-container-disk

kubectl get vm

NAME    AGE   STATUS    READY

rocky   19h   Running   True

kubectl get po

irt-operator-79b9c8869b-qpd42     1/1     Running   0            3d19h
virt-operator-79b9c8869b-8nf4h     1/1     Running   0            3d19h
virt-handler-fhvth                 1/1     Running   0            3d18h
virt-handler-2dbqs                 1/1     Running   0            3d18h
virt-handler-7f27r                 1/1     Running   0            3d18h
virt-handler-n58k5                 1/1     Running   0            3d18h
virt-controller-57d94799c9-825nn   1/1     Running   1 (3d ago)   3d18h
virt-controller-57d94799c9-2tj9v   1/1     Running   1 (3d ago)   3d18h
virt-api-647b745d96-4xrmt          1/1     Running   1 (3d ago)   3d18h
virt-api-647b745d96-z9nc2          1/1     Running   1 (3d ago)   3d18h
virt-launcher-rocky-68cb5          3/3     Running   0            19h

**Comment by alicefr** [comment]
Can you please to use vnc instead of the console, like `virtctl vnc <vm>`

**Comment by alicefr** [comment]
A closer look to your VM, it is a bit weird:
1. Why are you using the virtio-container-disk? This is required for Window not for Linux. See: https://kubevirt.io/user-guide/user_workloads/windows_virtio_drivers/
2. You are booting from the empty disk linhd not the iso

In generall, this standard from from the iso to the disk doesn't work for kubevirt, because the second time you boot you need to switch from the iso to the disk where the OS was installed.

**Comment by alicefr** [comment]
It is a similar issue as this: https://github.com/kubevirt/kubevirt/issues/7365
