### ISSUE TITLE
cpumanager not detected when enabled

### ISSUE THREAD

**Issue by dhruvik7** [kubevirt/kubevirt#12520]
**What happened**:
I enabled CPUManager feature gate and enabled it in the kubelet of one node, and verified that /proc/1/root/var/lib/kubelet/cpu_manager_state contains {"policyName":"static",... } after restarting the kubelet. However, the virt-handler keeps reporting "failed to set a cpu manager label on host host","pos":"heartbeat.go:174","reason":"no cpumanager policy file found"

**What you expected to happen**:
The cpumanager state file that exists is found and the cpumanager label is set to true

**How to reproduce it (as minimally and precisely as possible)**:
Enable CPUManager feature gate, enable CPU manager in kubelet of one node.

**Additional context**:
I tried rebooting the node, restarting kubelet, restarting virt-handler, didn't seem to change anything.

**Environment**:
- KubeVirt version (use `virtctl version`): v1.2.0-beta.0
- Kubernetes version (use `kubectl version`): v1.23.7
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Ubuntu 22.04
- Kernel (e.g. `uname -a`): 5.15.0-117-generic
- Install tools: N/A
- Others: N/A

**Comment by jean-edouard** [comment]
@dhruvik7 the error "no cpumanager policy file found" only happens when the virt-handler of a given node can't `stat /proc/1/root/var/lib/kubelet/cpu_manager_state`.
Are you sure you looked at the right virt-handler? (i.e. the one that runs on the node that has CPU manager enabled)
A couple notes on your environment:
- KubeVirt v.1.2.0 has been released a few months ago, it would probably be best to move away from the beta. KubeVirt v1.3.0 was also recently released.
- KubeVirt v.1.2.0 is tested against K8s v1.27 to v.1.30. I don't think 1.23 is supported.

**Comment by dhruvik7** [comment]
HI @jean-edouard thanks for getting back to me. I realized the issue was my kubelet dir is symlinked on my host so it wasn't mounted in the virt-handler and therefore this file was missing. I was able to resolve this issue by modifying the NewHandlerDaemonSet func in pkg/virt-operator/resource/generate/components/daemonsets.go to include my mount and rebuilding

**Comment by AllenXu93** [comment]
Meet same problem.
I found when `/var/lib/kubelet` have setted symlinked, in container `/proc/1/root/var/lib/kubelet` miss some files.
In container:

```
bash-5.1# ls -al  /proc/1/root/var/lib/kubelet/
total 4
drwxr-xr-x  4 root root   52 Nov  7 07:50 .
drwxr-xr-x  3 root root   29 Nov  7 07:50 ..
drwxr-xr-x  2 root root  175 Nov  7 07:51 device-plugins
drwxr-x--- 14 root root 4096 Nov  7 08:14 pods
```

But in host, actually the `cpu_manager_state` file exist:

```
root@yj-kubevirtwork-001 ~ # ls -al  /proc/1/root/var/lib/kubelet/
total 20
drwxr-xr-x  8 root root  208 Nov  7 15:52 .
drwxr-xr-x  5 root root   55 Oct 28 11:28 ..
-rw-r--r--  1 root root 1895 Oct 28 20:49 config.yaml
-rw-------  1 root root  171 Nov  7 15:51 cpu_manager_state
drwxr-xr-x  2 root root  175 Nov  7 15:51 device-plugins
-rw-r--r--  1 root root  170 Oct 28 20:49 kubeadm-flags.env
-rw-------  1 root root 1098 Nov  7 15:52 memory_manager_state
drwxr-xr-x  2 root root  166 Oct 28 21:06 pki
drwxr-x---  5 root root   87 Nov  5 17:56 plugins
drwxr-x---  2 root root    6 Oct 28 20:49 plugins_registry
drwxr-x---  2 root root   26 Nov  7 15:00 pod-resources
drwxr-x--- 14 root root 4096 Nov  7 16:14 pods
```

I think I better way to check cpuManager is to mount `/var/lib/kubelet` to container and check checkpoint file

**Comment by jean-edouard** [comment]
@dhruvik7 @AllenXu93 did `/var/lib/kubelet` come as a symlink out of the box in your Linux distro? (Ubuntu, right?) Or is it a symlink you created yourself?
If having it as a symlink is standard practice then we should probably support that.

**Comment by AllenXu93** [comment]
> @dhruvik7 @AllenXu93 did `/var/lib/kubelet` come as a symlink out of the box in your Linux distro? (Ubuntu, right?) Or is it a symlink you created yourself? If having it as a symlink is standard practice then we should probably support that.

I think set `/var/lib/kubelet` symlink is a common practice, to set pod's ephemeral dir in another disk, not system's disk.
