### ISSUE TITLE
Incomplete list of domain state reasons

### ISSUE THREAD

**Issue by slintes** [kubevirt/kubevirt#1261]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:
virt-handler logs domain states and reasons. The reason is "unknown" quite often, e.g. on a start of a vm:
`level=info timestamp=2018-07-03T08:59:40.296751Z pos=vm.go:685 component=virt-handler namespace=default name=testvm1 kind=Domain uid=555ebc1c-7e9f-11e8-ab18-525500d15501 msg="Domain is in state Paused reason Unknown"`

**What you expected to happen**:
Log the real reason, e.g. `Domain is in state Paused reason Starting Up`

**How to reproduce it (as minimally and precisely as possible)**:
Start a vm, check virt-handler logs

**Anything else we need to know?**:
All available libvirt states and reasons can be found in `vendor/github.com/libvirt/libvirt-go/domain.go`, look for `Domain<State>Reason`.
On kubevirt side, reasons need to be added to `pkg/virt-launcher/virtwrap/api/schema.go`, and mappings to `pkg/virt-launcher/virtwrap/util/libvirt-helper.go`.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.7.0-alpha.5.22+0674670de02b63-dirty

**Comment by rmohr** [comment]
Fixed in #1304
