### ISSUE TITLE
Connecting to libvirt daemon failed:  /var/run/libvirt/virtqemud-soc

### ISSUE THREAD

**Issue by web3creator** [kubevirt/kubevirt#12611]
**What happened**:
 {"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:88","timestamp":"2024-08-17T11:55:00.775925Z"}

 {"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:91","timestamp":"2024-08-17T11:55:00.775975Z"}

 {"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:565","timestamp":"2024-08-17T11:55:00.776199Z"}

 {"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory')","pos":"libvirt.go:573","timestamp":"2024-08-17T11:55:00.776583Z"}

 {"component":"virt-launcher","level":"info","msg":"libvirt version: 9.5.0, package: 6.el9 (builder@centos.org, 2023-08-25-08:53:56, )","subcomponent":"libvirt","thread":"43","timestamp":"2024-08-17T11:55:00.809000Z"}

 {"component":"virt-launcher","level":"info","msg":"hostname: win10-test","subcomponent":"libvirt","thread":"43","timestamp":"2024-08-17T11:55:00.809000Z"}

 {"component":"virt-launcher","level":"error","msg":"Unable to open /dev/kvm: Permission denied","pos":"virHostCPUGetCPUID:1422","subcomponent":"libvirt","thread":"43","timestamp":"2024-08-17T11:55:00.809000Z"}

 {"component":"virt-launcher","level":"error","msg":"internal error: Unable to get session bus connection: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory","pos":"virGDBusGetSessionBus:126","subcomponent":"libvirt","thread":"43","timestamp":"2024-08-17T11:55:00.809000Z"}

 {"component":"virt-launcher","level":"error","msg":"internal error: Unable to get system bus connection: Could not connect: No such file or directory","pos":"virGDBusGetSystemBus:99","subcomponent":"libvirt","thread":"43","timestamp":"2024-08-17T11:55:00.809000Z"}

 {"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:581","timestamp":"2024-08-17T11:55:01.278418Z"}

 {"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:563","timestamp":"2024-08-17T11:55:01.281830Z"}

 {"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:75","timestamp":"2024-08-17T11:55:01.281959Z"}

 {"component":"virt-launcher","kind":"","level":"info","msg":"Executing PreStartHook on VMI pod environment","name":"win10-test","namespace":"default","pos":"manager.go:684","timestamp":"2024-08-17T11:55:03.825948Z","uid":"c6ec80cb-06f0-41a1-bfc1-f08ae58002f8"}

 {"component":"virt-launcher","kind":"","level":"info","msg":"Starting PreCloudInitIso hook","name":"win10-test","namespace":"default","pos":"manager.go:705","timestamp":"2024-08-17T11:55:03.825984Z","uid":"c6ec80cb-06f0-41a1-bfc1-f08ae58002f8"}

 {"component":"virt-launcher","level":"info","msg":"Found nameservers in /etc/resolv.conf: \ufffd\ufffd\u0019\n","pos":"network.go:171","timestamp":"2024-08-17T11:55:03.826660Z"}

 {"component":"virt-launcher","level":"info","msg":"Found search domains in /etc/resolv.conf: default.svc.cluster.local svc.cluster.local cluster.local 114.114.114.114","pos":"network.go:172","timestamp":"2024-08-17T11:55:03.826678Z"}

 {"component":"virt-launcher","level":"info","msg":"Starting SingleClientDHCPServer","pos":"server.go:65","timestamp":"2024-08-17T11:55:03.826719Z"}

 {"component":"virt-launcher","level":"error","msg":"failed to run DHCP Server: Search domain is not valid: '114.114.114.114'","pos":"common.go:192","timestamp":"2024-08-17T11:55:03.826789Z"}

 panic: Search domain is not valid: '114.114.114.114'

 {"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 12 with status 512","pos":"virt-launcher-monitor.go:198","timestamp":"2024-08-17T11:55:03.831925Z"}

 {"component":"virt-launcher-monitor","level":"error","msg":"dirty virt-launcher shutdown: exit-code 2","pos":"virt-launcher-monitor.go:216","timestamp":"2024-08-17T11:55:03.832069Z"}

 {"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:88","timestamp":"2024-08-17T11:55:00.775925Z"}

 {"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:91","timestamp":"2024-08-17T11:55:00.775975Z"}

 {"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:565","timestamp":"2024-08-17T11:55:00.776199Z"}

 {"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory')","pos":"libvirt.go:573","timestamp":"2024-08-17T11:55:00.776583Z"}

 {"component":"virt-launcher","level":"info","msg":"libvirt version: 9.5.0, package: 6.el9 (builder@centos.org, 2023-08-25-08:53:56, )","subcomponent":"libvirt","thread":"43","timestamp":"2024-08-17T11:55:00.809000Z"}

 {"component":"virt-launcher","level":"info","msg":"hostname: win10-test","subcomponent":"libvirt","thread":"43","timestamp":"2024-08-17T11:55:00.809000Z"}

 {"component":"virt-launcher","level":"error","msg":"Unable to open /dev/kvm: Permission denied","pos":"virHostCPUGetCPUID:1422","subcomponent":"libvirt","thread":"43","timestamp":"2024-08-17T11:55:00.809000Z"}

 {"component":"virt-launcher","level":"error","msg":"internal error: Unable to get session bus connection: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory","pos":"virGDBusGetSessionBus:126","subcomponent":"libvirt","thread":"43","timestamp":"2024-08-17T11:55:00.809000Z"}

 {"component":"virt-launcher","level":"error","msg":"internal error: Unable to get system bus connection: Could not connect: No such file or directory","pos":"virGDBusGetSystemBus:99","subcomponent":"libvirt","thread":"43","timestamp":"2024-08-17T11:55:00.809000Z"}

 {"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:581","timestamp":"2024-08-17T11:55:01.278418Z"}

 {"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:563","timestamp":"2024-08-17T11:55:01.281830Z"}

 {"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:75","timestamp":"2024-08-17T11:55:01.281959Z"}

 {"component":"virt-launcher","kind":"","level":"info","msg":"Executing PreStartHook on VMI pod environment","name":"win10-test","namespace":"default","pos":"manager.go:684","timestamp":"2024-08-17T11:55:03.825948Z","uid":"c6ec80cb-06f0-41a1-bfc1-f08ae58002f8"}

 {"component":"virt-launcher","kind":"","level":"info","msg":"Starting PreCloudInitIso hook","name":"win10-test","namespace":"default","pos":"manager.go:705","timestamp":"2024-08-17T11:55:03.825984Z","uid":"c6ec80cb-06f0-41a1-bfc1-f08ae58002f8"}

 {"component":"virt-launcher","level":"info","msg":"Found nameservers in /etc/resolv.conf: \ufffd\ufffd\u0019\n","pos":"network.go:171","timestamp":"2024-08-17T11:55:03.826660Z"}

 {"component":"virt-launcher","level":"info","msg":"Found search domains in /etc/resolv.conf: default.svc.cluster.local svc.cluster.local cluster.local 114.114.114.114","pos":"network.go:172","timestamp":"2024-08-17T11:55:03.826678Z"}

 {"component":"virt-launcher","level":"info","msg":"Starting SingleClientDHCPServer","pos":"server.go:65","timestamp":"2024-08-17T11:55:03.826719Z"}

 {"component":"virt-launcher","level":"error","msg":"failed to run DHCP Server: Search domain is not valid: '114.114.114.114'","pos":"common.go:192","timestamp":"2024-08-17T11:55:03.826789Z"}

 panic: Search domain is not valid: '114.114.114.114'

 {"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 12 with status 512","pos":"virt-launcher-monitor.go:198","timestamp":"2024-08-17T11:55:03.831925Z"}

 {"component":"virt-launcher-monitor","level":"error","msg":"dirty virt-launcher shutdown: exit-code 2","pos":"virt-launcher-monitor.go:216","timestamp":"2024-08-17T11:55:03.832069Z"}

**Environment**:
- KubeVirt version (use `virtctl version`): 1.2.2
- Kubernetes version (use `kubectl version`): 1.26.10
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): ubuntu 22.04
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by web3creator** [comment]
:"failed to detect VMI pod: dial unix //pods/5a09a32f-6c04-4542-ac96-a72ad644020f/volumes/kubernetes.io~empty-dir/sockets/launcher-sock: connect: connection refused","timestamp":"2024-08-17T15:31:59.305779Z","uid":"2c755b20-2e90-4a5c-9dfe-da4e85c7642c"}
{"component":"virt-handler","kind":"","level":"error","msg":"Could not get owner Pid of socket //pods/5a09a32f-6c04-4542-ac96-a72ad644020f/volumes/kubernetes.io~empty-dir/sockets/launcher-sock","name":"vm-cirros","namespace":"default","pos":"detector.go:93","reason":"dial unix //pods/5a09a32f-6c04-4542-ac96-a72ad644020f/volumes/kubernetes.io~empty-dir/sockets/launcher-sock: connect: connection refused","timestamp":"2024-08-17T15:31:59.975257Z","uid":"2c755b20-2e90-4a5c-9dfe-da4e85c7642c"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"vm-cirros","namespace":"default","pos":"vm.go:1940","reason":"failed to detect VMI pod: dial unix //pods/5a09a32f-6c04-4542-ac96-a72ad644020f/volumes/kubernetes.io~empty-dir/sockets/launcher-sock: connect: connection refused","timestamp":"2024-08-17T15:31:59.975345Z","uid":"2c755b20-2e90-4a5c-9dfe-da4e85c7642c"}
{"component":"virt-handler","kind":"","level":"error","msg":"Could not get owner Pid of socket //pods/5a09a32f-6c04-4542-ac96-a72ad644020f/volumes/kubernetes.io~empty-dir/sockets/launcher-sock","name":"vm-cirros","namespace":"default","pos":"detector.go:93","reason":"dial unix //pods/5a09a32f-6c04-4542-ac96-a72ad644020f/volumes/kubernetes.io~empty-dir/sockets/launcher-sock: connect: connection refused","timestamp":"2024-08-17T15:32:01.287079Z","uid":"2c755b20-2e90-4a5c-9dfe-da4e85c7642c"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"vm-cirros","namespace":"default","pos":"vm.go:1940","reason":"failed to detect VMI pod: dial unix //pods/5a09a32f-6c04-4542-ac96-a72ad644020f/volumes/kubernetes.io~empty-dir/sockets/launcher-sock: connect: connection refused","timestamp":"2024-08-17T15:32:01.287164Z","uid":"2c755b20-2e90-4a5c-9dfe-da4e85c7642c"}
{"component":"virt-handler","kind":"","level":"error","msg":"Could not get owner Pid of socket //pods/5a09a32f-6c04-4542-ac96-a72ad644020f/volumes/kubernetes.io~empty-dir/sockets/launcher-sock","name":"vm-cirros","namespace":"default","pos":"detector.go:93","reason":"dial unix //pods/5a09a32f-6c04-4542-ac96-a72ad644020f/volumes/kubernetes.io~empty-dir/sockets/launcher-sock: connect: connection refused","timestamp":"2024-08-17T15:32:03.879148Z","uid":"2c755b20-2e90-4a5c-9dfe-da4e85c7642c"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"vm-cirros","namespace":"default","pos":"vm.go:1940","reason":"failed to detect VMI pod: dial unix //pods/5a09a32f-6c04-4542-ac96-a72ad644020f/volumes/kubernetes.io~empty-dir/sockets/launcher-sock: connect: connection refused","timestamp":"2024-08-17T15:32:03.879224Z","uid":"2c755b20-2e90-4a5c-9dfe-da4e85c7642c"}

**Comment by dhiller** [comment]
Actually this looks like a configuration issue, see https://github.com/kubevirt/kubevirt/issues/3187

/close

Please reopen if you disagree.
