### ISSUE TITLE
failed to run DHCP: Search domain is not valid: '114.114.114.114'","

### ISSUE THREAD

**Issue by web3creator** [kubevirt/kubevirt#12615]
**What happened**:
{"component":"virt-launcher","level":"info","msg":"conn=0x7fd860013190, name=kubevirt_testvm1","pos":"virDomainLookupByName:449","subcomponent":"libvirt","thread":"28","timestamp":"2024-08-18T12:37:29.098000Z"}
{"component":"virt-launcher","level":"info","msg":"Domain not found: no domain with matching name 'kubevirt_testvm1'","pos":"qemuDomainLookupByName:1453","subcomponent":"libvirt","thread":"28","timestamp":"2024-08-18T12:37:29.098000Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Executing PreStartHook on VMI pod environment","name":"testvm1","namespace":"kubevirt","pos":"manager.go:671","timestamp":"2024-08-18T12:37:29.098315Z","uid":"2f4858b5-8f53-456e-bce2-8a4463b9c427"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Starting PreCloudInitIso hook","name":"testvm1","namespace":"kubevirt","pos":"manager.go:692","timestamp":"2024-08-18T12:37:29.098351Z","uid":"2f4858b5-8f53-456e-bce2-8a4463b9c427"}
{"component":"virt-launcher","level":"info","msg":"The imported dhcpConfig: DHCPConfig: { Name: eth0, IPv4: 10.0.2.2/24, IPv6: <nil>, MAC: , AdvertisingIPAddr: 10.0.2.1, MTU: 1480, Gateway: 10.0.2.1, IPAMDisabled: false, Routes: <nil>}","pos":"podnic.go:104","timestamp":"2024-08-18T12:37:29.098914Z"}
{"component":"virt-launcher","level":"info","msg":"StartDHCP network Nic: DHCPConfig: { Name: eth0, IPv4: 10.0.2.2/24, IPv6: <nil>, MAC: , AdvertisingIPAddr: 10.0.2.1, MTU: 1480, Gateway: 10.0.2.1, IPAMDisabled: false, Routes: <nil>}","pos":"common.go:164","timestamp":"2024-08-18T12:37:29.098952Z"}
{"component":"virt-launcher","level":"info","msg":"Found nameservers in /etc/resolv.conf: \ufffd\ufffd\u0019\n","pos":"network.go:185","timestamp":"2024-08-18T12:37:29.099044Z"}
{"component":"virt-launcher","level":"info","msg":"Found search domains in /etc/resolv.conf: kubevirt.svc.cluster.local svc.cluster.local cluster.local 114.114.114.114","pos":"network.go:186","timestamp":"2024-08-18T12:37:29.099057Z"}
{"component":"virt-launcher","level":"info","msg":"Starting SingleClientDHCPServer","pos":"server.go:65","timestamp":"2024-08-18T12:37:29.099144Z"}
{"component":"virt-launcher","level":"error","msg":"failed to run DHCP: Search domain is not valid: '114.114.114.114'","pos":"common.go:192","timestamp":"2024-08-18T12:37:29.099258Z"}
panic: Search domain is not valid: '114.114.114.114'

goroutine 134 [running]:
kubevirt.io/kubevirt/pkg/network/driver.(*NetworkUtilsHandler).StartDHCP.func1()
        pkg/network/driver/common.go:193 +0x3db
created by kubevirt.io/kubevirt/pkg/network/driver.(*NetworkUtilsHandler).StartDHCP
        pkg/network/driver/common.go:178 +0x545
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 12 with status 512","pos":"virt-launcher-monitor.go:192","timestamp":"2024-08-18T12:37:29.105847Z"}
{"component":"virt-launcher-monitor","level":"error","msg":"dirty virt-launcher shutdown: exit-code 2","pos":"virt-launcher-monitor.go:210","timestamp":"2024-08-18T12:37:29.105965Z"}
{"component":"virt-launcher-monitor","level":"error","msg":"failed to open file /var/run/kubevirt/passt.log","pos":"virt-launcher-monitor.go:421","reason":"open /var/run/kubevirt/passt.log: no such file or directory","timestamp":"2024-08-18T12:37:29.105994Z"}
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 50 with status 0","pos":"virt-launcher-monitor.go:192","timestamp":"2024-08-18T12:37:29.108637Z"}
{"component":"virt-launcher-monitor","level":"info","msg":"error when checking for istio-proxy presence","pos":"virt-launcher-monitor.go:360","reason":"Get \"http://localhost:15021/healthz/ready\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)","timestamp":"2024-08-18T12:37:31.108925Z"}
{"component":"virt-launcher-monitor","level":"info","msg":"serial console term file deleted: /var/run/kubevirt-private/2f4858b5-8f53-456e-bce2-8a4463b9c427/virt-serial0-log-sigTerm","pos":"virt-launcher-monitor.go:100","timestamp":"2024-08-18T12:37:31.109210Z"}
{"component":"virt-launcher-monitor","level":"info","msg":"serial console term file created: /var/run/kubevirt-private/2f4858b5-8f53-456e-bce2-8a4463b9c427/virt-serial0-log-sigTerm-done","pos":"virt-launcher-monitor.go:79","timestamp":"2024-08-18T12:37:31.109279Z"}

**Environment**:
- KubeVirt version (use `virtctl version`): 1.1.1
- Kubernetes version (use `kubectl version`): 1.26.5
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): ubuntu22.04
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by ah8ad3** [comment]
This is the regex that validates search domain:
```
// simple domain validation regex. Put it here to avoid compiling each time.
// Note this requires that unicode domains be presented in their ASCII format
var searchDomainValidationRegex = regexp.MustCompile(`^(?:[_a-z0-9](?:[_a-z0-9-]{0,61}[a-z0-9])?\.)*(?:[a-z](?:[a-z0-9-]{0,61}[a-z0-9])?)?$`)

```
On my vm this value is set to
`search .`

Can you edit the `/etc/resolv.conf` and either remove search or replace it with some domain and check to see if the problem exists?

**Comment by ah8ad3** [comment]
Also i think this issue is the same https://github.com/kubevirt/kubevirt/issues/12611

**Comment by dhiller** [comment]
Actually this looks like a configuration issue, see https://github.com/kubevirt/kubevirt/issues/3187

/close

Please reopen if you disagree.
