### ISSUE TITLE
Service "kubevirt-operator-webhook" not found

### ISSUE THREAD

**Issue by b1zzu** [kubevirt/kubevirt#12644]
**What happened**:
I've installed kubevirt following this tutorial on AKS: https://kubevirt.io/user-guide//cluster_admin/installation/#installing-kubevirt-on-kubernetes

but when I try to apply the KubeVirt CR it fails with the following error:

```
Error from server (InternalError): Internal error occurred: failed calling webhook "kubevirt-update-validator.kubevirt.io": failed to call webhook: Post "https://kubevirt-operator-webhook.kubevirt.svc:443/kubevirt-validate-update?timeout=10s": service "kubevirt-operator-webhook" not found
```

**What you expected to happen**:
To work

**How to reproduce it (as minimally and precisely as possible)**:
Follow the https://kubevirt.io/user-guide//cluster_admin/installation/#installing-kubevirt-on-kubernetes tutorial

**Additional context**:
I can't even find where and how should the kubevirt-operator-webhook service being created.

**Environment**:
- KubeVirt version (use `virtctl version`): v1.3.0
- Kubernetes version (use `kubectl version`): v1.28.9
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by xpivarc** [comment]
Please share manifests you have applied

**Comment by b1zzu** [comment]
I found out that a old version of kubevirt had obsolete webhooks which conflicted with the new version, I found such wehbooks and I've deleted them manually, if somone else has the same issue I can add more details.

**Comment by FranciscoOchoa94** [comment]
@b1zzu how you find the old webhooks?

**Comment by b1zzu** [comment]
@FranciscoOchoa94 

```
kubectl get validatingwebhookconfigurations,mutatingwebhookconfigurations
```

although I can't remember now if it was a mutation or a validation webhook
