### ISSUE TITLE
linter: Cover instancetypes source files using the 'mnd' linter

### ISSUE THREAD

**Issue by EdDev** [kubevirt/kubevirt#12662]
**Is your feature request related to a problem? Please describe**:

As part of golang-ci linters update in https://github.com/kubevirt/kubevirt/pull/12600, there was a need to exclude some instancetype source files for the 'mnd' linter.

**Describe the solution you'd like**:

Remove the instancetype source files from the 'mnd' ignored files by solving the errors they produce.

**Describe alternatives you've considered**:

**Additional context**:

**Comment by anishbista60** [comment]
@EdDev i'll work here . 
/assign
