### ISSUE TITLE
Error: container create failed: pivot_root: Invalid argument - virt-handler

### ISSUE THREAD

**Issue by K1ckMan** [kubevirt/kubevirt#12672]
**What happened**:
virt-handler - cannot start - Error: container create failed: pivot_root: Invalid argument

**Additional context**:

Aug 26 13:02:44 cluster kubelet[1402]: E0826 13:02:44.594406    1402 remote_runtime.go:319] "CreateContainer in sandbox from runtime service failed" err=<
Aug 26 13:02:44 cluster kubelet[1402]:         rpc error: code = Unknown desc = container create failed: pivot_root: Invalid argument
Aug 26 13:02:44 cluster kubelet[1402]:  > podSandboxID="3c93005d9e352e78d246e062b3b3d9c6f9fa642599820c325b102df31a9965fb"
Aug 26 13:02:44 cluster kubelet[1402]: E0826 13:02:44.594606    1402 kuberuntime_manager.go:1272] container &Container{Name:virt-handler,Image:quay.io/kubevirt/virt-handler:v1.3.1,Command:[virt-handler],Args:[--port 8443 --hostname-override $(NODE_NAME) --pod-ip-address $(MY_POD_IP) --max-metric-requests 3 --console-server-port 8186 --graceful-shutdown-seconds 315 -v 2],WorkingDir:,Ports:[]ContainerPort{ContainerPort{Name:metrics,HostPort:0,ContainerPort:8443,Protocol:TCP,HostIP:,},},Env:[]EnvVar{EnvVar{Name:NODE_NAME,Value:,ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:spec.nodeName,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,},},EnvVar{Name:MY_POD_IP,Value:,ValueFrom:&EnvVarSource{FieldRef:&ObjectFieldSelector{APIVersion:v1,FieldPath:status.podIP,},ResourceFieldRef:nil,ConfigMapKeyRef:nil,SecretKeyRef:nil,},},},Resources:ResourceRequirements{Limits:ResourceList{},Requests:ResourceList{cpu: {{10 -3} {<nil>} 10m DecimalSI},memory: {{374341632 0} {<nil>} 357Mi BinarySI},},Claims:[]ResourceClaim{},},VolumeMounts:[]VolumeMount{VolumeMount{Name:kubevirt-virt-handler-certs,ReadOnly:true,MountPath:/etc/virt-handler/clientcertificates,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:kubevirt-virt-handler-server-certs,ReadOnly:true,MountPath:/etc/virt-handler/servercertificates,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:profile-data,ReadOnly:false,MountPath:/profile-data,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:libvirt-runtimes,ReadOnly:false,MountPath:/var/run/kubevirt-libvirt-runtimes,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:virt-share-dir,ReadOnly:false,MountPath:/var/run/kubevirt,SubPath:,MountPropagation:*Bidirectional,SubPathExpr:,},VolumeMount{Name:virt-lib-dir,ReadOnly:false,MountPath:/var/lib/kubevirt,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:virt-private-dir,ReadOnly:false,MountPath:/var/run/kubevirt-private,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:device-plugin,ReadOnly:false,MountPath:/var/lib/kubelet/device-plugins,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:kubelet-pods-shortened,ReadOnly:false,MountPath:/pods,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:kubelet-pods,ReadOnly:false,MountPath:/var/lib/kubelet/pods,SubPath:,MountPropagation:*Bidirectional,SubPathExpr:,},VolumeMount{Name:node-labeller,ReadOnly:false,MountPath:/var/lib/kubevirt-node-labeller,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:podinfo,ReadOnly:false,MountPath:/etc/podinfo,SubPath:,MountPropagation:nil,SubPathExpr:,},VolumeMount{Name:kube-api-access-87szk,ReadOnly:true,MountPath:/var/run/secrets/kubernetes.io/serviceaccount,SubPath:,MountPropagation:nil,SubPathExpr:,},},LivenessProbe:&Probe{ProbeHandler:ProbeHandler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/healthz,Port:{0 8443 },Host:,Scheme:HTTPS,HTTPHeaders:[]HTTPHeader{},},TCPSocket:nil,GRPC:nil,},InitialDelaySeconds:15,TimeoutSeconds:10,PeriodSeconds:45,SuccessThreshold:1,FailureThreshold:3,TerminationGracePeriodSeconds:nil,},ReadinessProbe:&Probe{ProbeHandler:ProbeHandler{Exec:nil,HTTPGet:&HTTPGetAction{Path:/healthz,Port:{0 8443 },Host:,Scheme:HTTPS,HTTPHeaders:[]HTTPHeader{},},TCPSocket:nil,GRPC:nil,},InitialDelaySeconds:15,TimeoutSeconds:10,PeriodSeconds:20,SuccessThreshold:1,FailureThreshold:3,TerminationGracePeriodSeconds:nil,},Lifecycle:nil,TerminationMessagePath:/dev/termination-log,ImagePullPolicy:IfNotPresent,SecurityContext:&SecurityContext{Capabilities:nil,Privileged:*true,SELinuxOptions:&SELinuxOptions{User:,Role:,Type:,Level:s0,},RunAsUser:nil,RunAsNonRoot:nil,ReadOnlyRootFilesystem:nil,AllowPrivilegeEscalation:nil,RunAsGroup:nil,ProcMount:nil,WindowsOptions:nil,SeccompProfile:nil,},Stdin:false,StdinOnce:false,TTY:false,EnvFrom:[]EnvFromSource{},TerminationMessagePolicy:File,VolumeDevices:[]VolumeDevice{},StartupProbe:nil,ResizePolicy:[]ContainerResizePolicy{},RestartPolicy:nil,} start failed in pod virt-handler-kkhv8_kubevirt(12875654-cc33-4ec9-b002-55a9c5c81eb3): CreateContainerError: container create failed: pivot_root: Invalid argument
Aug 26 13:02:44 cluster kubelet[1402]: E0826 13:02:44.594659    1402 pod_workers.go:1298] "Error syncing pod, skipping" err="failed to \"StartContainer\" for \"virt-handler\" with CreateContainerError: \"container create failed: pivot_root: Invalid argument\\n\"" pod="kubevirt/virt-handler-kkhv8" podUID="12875654-cc33-4ec9-b002-55a9c5c81eb3"

**Environment**:
- KubeVirt version (use `virtctl version`): Client Version: version.Info{GitVersion:"v1.3.0", GitCommit:"6a4481910c353dc43be36fd1c9a4444ad701d0b7", GitTreeState:"clean", BuildDate:"2024-07-17T15:19:15Z", GoVersion:"go1.22.2 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v1.3.1", GitCommit:"ed1e7ae8548d319fa7aacf315ad198f7241287c5", GitTreeState:"clean", BuildDate:"2024-08-22T10:09:02Z", GoVersion:"go1.22.2 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`): Client Version: v1.29.7
Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
Server Version: v1.29.7

- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: Mac Mini i5 Intel
- OS (e.g. from /etc/os-release):
- 
PRETTY_NAME="Ubuntu 22.04.4 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.4 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

- Kernel (e.g. `uname -a`): Linux cluster 5.15.0-119-generic #129-Ubuntu SMP Fri Aug 2 19:25:20 UTC 2024 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: N/A
- Others: N/A

**Comment by alicefr** [comment]
@K1ckMan if you describe the pod do you see any meaningful error message?

**Comment by K1ckMan** [comment]
@alicefr any update?

**Comment by K1ckMan** [comment]
It was necessary to clean up the pod limits that were going into overprovisioning.
