### ISSUE TITLE
virtctl: Log verbosity cannot be set anymore

### ISSUE THREAD

**Issue by 0xFelix** [kubevirt/kubevirt#12779]
**What happened**:

Since https://github.com/kubevirt/kubevirt/pull/12070 was merged it is no longer possible to set the log verbosity in virtctl by providing the `-v` flag.

**What you expected to happen**:

The log verbosity in virtctl can be set by providing the `-v` flag.

**How to reproduce it (as minimally and precisely as possible)**:

Run virtctl with `-v` flag and observe the following error: `unknown shorthand flag: 'v' in -v`

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by vladikr** [comment]
@0xFelix do you think it's due to this change? https://github.com/kubevirt/kubevirt/pull/12070/files#diff-6244d6ac08888df9467f94d99e2c5a8f1d1c9528c04df82ac7f3e1ebc13efb72L80

**Comment by 0xFelix** [comment]
@vladikr Yes, most likely. This added the `-v` flag previously.
