### ISSUE TITLE
Generate a nice HTTP report for functional tests on CI

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#128]
The Jenkins logs are very cluttered. We can create a nice http report by

 * Fetching logs from the containers and integrate them
 * Register our own reporter in Ginkgo

Then we can finally let Jenkins set the link to this report instead of the job itself (the Jenkins PR plugin allows that).

Here is how the kuberntes results look like: https://k8s-gubernator.appspot.com/

**Comment by fabiand** [comment]
@nellyc something you want to own?

**Comment by fabiand** [comment]
Sounds cool. thanks. I'd still assign it to you until you share your suggestion :)

**Comment by rmohr** [comment]
With the move to standardci there is right now nothing we want to do.

/close
