### ISSUE TITLE
virtctl socks proxy

### ISSUE THREAD

**Issue by kfox1111** [kubevirt/kubevirt#12808]
You can add something like:
```
  proxy-url: socks5://localhost:10001
```
to your kubeconfig to reach a k8s on the other side of a socks proxy.

virtctl console/vnc just hangs with such a kubeconfig file.

**Comment by kfox1111** [comment]
kubectl get nodes works fine, so the socks setting in the kubeconfig is working fine.

Another issue, for some reason -v 4 doesn't work:
```
$ virtctl vnc -n kfox-test test5 -v 4
unknown shorthand flag: 'v' in -v
```

client version: v1.3.1

**Comment by kfox1111** [comment]
the adm log-verbosity flags only affect the servers, not the client.

looks like if I download the exact version of the client matching the server, it will take the -v 4 flag.

But, it still doesn't output anything and just hangs.

**Comment by kfox1111** [comment]
Stracing shows it trying to tcp connect to the server specified in the kubeconfig file directly, rather then going through the proxy, and just hanging on the connect indefinitely. So, yes, seems to be ignoring the proxy-url kubeconfig setting.

**Comment by 0xFelix** [comment]
Setting the log verbosity in virtctl is broken atm, see https://github.com/kubevirt/kubevirt/issues/12779

**Comment by 0xFelix** [comment]
Thanks for confirming. I'll see what I can do.
