### ISSUE TITLE
volume migration: migrating from a block PVC to a filesystem one fails

### ISSUE THREAD

**Issue by alicefr** [kubevirt/kubevirt#12823]
**What happened**:
Migrate the storage from a block PVC/DV and update it using a PVC/DV with filesstem mode fails with error:
```
{"component":"virt-launcher","kind":"","level":"error","msg":"Live migration failed.","name":"vm-dv","namespace":"default","pos":"live-migration-source.go:625","reason":"error encountered during MigrateToURI3 libvirt api call: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2024-09-12T14:29:08.246483Z qemu-kvm: -blockdev {\"driver\":\"file\",\"filename\":\"/var/run/kubevirt-private/vmi-disks/datavolumedisk1\",\"aio\":\"native\",\"node-name\":\"libvirt-1-storage\",\"auto-read-only\":true,\"discard\":\"unmap\",\"cache\":{\"direct\":true,\"no-flush\":false}}: Could not open '/var/run/kubevirt-private/vmi-disks/datavolumedisk1': filesystem does not support O_DIRECT')","timestamp":"2024-09-12T14:29:08.904808Z","uid":"7ade9eae-0fbc-4a89-9b52-f4fded9d846d"}
```

**What you expected to happen**:
Be able to migrate

**How to reproduce it (as minimally and precisely as possible)**:
Use as source a block PVC/DV and update it using a PVC/DV with filesstem mode

**Additional context**:
Maybe this option isn't possible at all.

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by alicefr** [comment]
@akalenyu I'm not sure, but might be that we apply some defaults for block that aren't valid for filesystems on the image. That's my guess, but I could be wrong.

**Comment by akalenyu** [comment]
> @akalenyu the sc is `local`. I'm not sure, but might be that we apply some defaults for block that aren't valid for filesystems on the image. That's my guess, but I could be wrong.

Just tried with local, it does O_DIRECT :open_mouth: 
```
$ dd if=/dev/urandom of=/disk/2G.bin bs=32K count=65536 status=progress oflag=direct
1976598528 bytes (2.0 GB, 1.8 GiB) copied, 8 s, 247 MB/s
65536+0 records in
65536+0 records out
2147483648 bytes (2.1 GB, 2.0 GiB) copied, 8.46427 s, 254 MB/s
```
The error is very weird because this is already a Filesystem PVC, however, the actual storage I think depends
on your dev environment so if your kubevirtci slices those PVs with some tmpfs or something (doubt it)
```
Could not open '/var/run/kubevirt-private/vmi-disks/datavolumedisk1': filesystem does not support O_DIRECT
```

**Comment by alicefr** [comment]
> > @akalenyu the sc is `local`. I'm not sure, but might be that we apply some defaults for block that aren't valid for filesystems on the image. That's my guess, but I could be wrong.
> 
> Just tried with local, it does O_DIRECT 😮
> 
> ```
> $ dd if=/dev/urandom of=/disk/2G.bin bs=32K count=65536 status=progress oflag=direct
> 1976598528 bytes (2.0 GB, 1.8 GiB) copied, 8 s, 247 MB/s
> 65536+0 records in
> 65536+0 records out
> 2147483648 bytes (2.1 GB, 2.0 GiB) copied, 8.46427 s, 254 MB/s
> ```
> 
> The error is very weird because this is already a Filesystem PVC, however, the actual storage I think depends on your dev environment so if your kubevirtci slices those PVs with some tmpfs or something (doubt it)
> 
> ```
> Could not open '/var/run/kubevirt-private/vmi-disks/datavolumedisk1': filesystem does not support O_DIRECT
> ```

Interesting, but FS to FS migration works. This is happening block to FS, so I'm really wondering if there is some wrong setup somewhere

**Comment by akalenyu** [comment]
maybe it's the `open` against the source volume that errors? which block storage class is this?

**Comment by alicefr** [comment]
I used the annotation `kubevirt.io/func-test-block-migration-target-preparation: "true"` which keeps the target pod running and I don't have issues in opening and writing on the PVC.

**Comment by vladikr** [comment]
@alicefr could be that we don't set the right cache mode when we transition from block to filesystem?

**Comment by alicefr** [comment]
@vladikr no, I found the problem. It was a stupid mistake from my side. When we replace block with fs, the path is truncate to the pvc directory and we are missing the `disk.img`. I'll write a test and then I can publish a PR

**Comment by alicefr** [comment]
Fix: https://github.com/kubevirt/kubevirt/pull/12851

**Comment by alicefr** [comment]
This has been solved
