### ISSUE TITLE
Missing reference / list of VirtualMachineInstanceCondition managed by kubevirt

### ISSUE THREAD

**Issue by VannTen** [kubevirt/kubevirt#12830]
**Description**:
When checking kubevirt docs or the api reference, I'm unable to find a list of possible conditions for VirtualMachineInstance resources.

**What you expected**:
A list of the possible conditions and their meaning. 

**URL**: https://kubevirt.io/api-reference/main/definitions.html#_v1_virtualmachineinstancecondition

**Additional context**:
For contrast, kubernetes docs provide [the list of Pod conditions](https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-conditions)

(I was originally trying to see if there was a VirtualMachineInstance which could let me know if it has an IP,  but it seems to me documenting the set of possible conditions is a more general answer to that particular question)

Thanks for your work on Kubevirt :+1: (it makes our CI much easier :) )

**Comment by VannTen** [comment]
Well, that answers my question, thanks.
Maybe that should go somewhere in the docs, but I'll leave you to decide that.

**Comment by iholder101** [comment]
Thank you @dosu! great job!
FYI @vladikr @dhiller :)

@VannTen glad you found what you were looking for! :ok_hand: 
/close

Adding these to our docs sounds like a valuable idea!

**Comment by dhiller** [comment]
> ```go
> Provisioning
> ```

@iholder101 not completely sure about this, but maybe there's a correlation with the controller status mentioned here [1] ? Do we need to update that page as well? 

[1]: https://kubevirt.io/user-guide/architecture/#controller-status
