### ISSUE TITLE
some tags in the 1.4 alpha release default to s390x on x86 hosts

### ISSUE THREAD

**Issue by akalenyu** [kubevirt/kubevirt#12843]
**What happened**:
it seems like the newly created alpha images for kubevirt point to s390x by default
```
# docker pull quay.io/kubevirt/virt-exportproxy:v1.4.0-alpha.0
...
Digest: sha256:6997b5c464965939179f3a0636f5a28499d6c286b0865032673120593c9b111f
Status: Downloaded newer image for quay.io/kubevirt/virt-exportproxy:v1.4.0-alpha.0
quay.io/kubevirt/virt-exportproxy:v1.4.0-alpha.0
# docker images | grep exportproxy
quay.io/kubevirt/virt-exportproxy                                                                       v1.4.0-alpha.0              a7ed475a0554   54 years ago    71.7MB
# TAG=$(docker create a7ed475a0554)
# docker cp $TAG:/usr/bin/virt-exportproxy .
# file virt-exportproxy 
virt-exportproxy: ELF 64-bit MSB executable, IBM S/390, version 1 (SYSV), statically linked, BuildID[sha1]=3886f3dc9ff0405009ffeab476ccd08f2560a5c0, for GNU/Linux 3.2.0, stripped
```
(this is done on an x86 machine)

**What you expected to happen**:
default tags are x86 / at least default to x86 if the host is

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:
this is causing consumers of 1.4 to fail
https://gcsweb-ci.apps.ci.l2s4.p1.openshiftapps.com/gcs/test-platform-results/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/3099/pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-operator-sdk-gcp/1834458255884029952/artifacts/hco-e2e-operator-sdk-gcp/deploy-cr/artifacts/kubevirt-must-gather/quay-io-kubevirt-must-gather-sha256-290c9cb1ccd736c5f87cbea9400dea2870cbfccedd0a92900a4fa28876d90888/namespaces/kubevirt-hyperconverged/pods/virt-exportproxy-f5b4789f-n2wgr/exportproxy/exportproxy/logs/current.log

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by akalenyu** [comment]
> The newly created alpha images for KubeVirt default to s390x on x86 hosts instead of x86 because of the addition of support for building and running KubeVirt on s390x, as indicated by the following pull request:
> 
> * [[PR [Enable building and running kubevirt on s390x #10490](https://github.com/kubevirt/kubevirt/pull/10490)]]([Enable building and running kubevirt on s390x #10490](https://github.com/kubevirt/kubevirt/pull/10490)) [jschintag] Add support for building and running kubevirt on s390x [[1]](https://kubevirt.io/user-guide/release_notes).
> 
> To address this issue, ensure that the correct image for your architecture is pulled by specifying the platform explicitly when using the container runtime interface (CRI). For example, you can use the `--platform` flag with `docker` or `podman`:
> 
> ```shell
> docker pull --platform=linux/amd64 quay.io/kubevirt/virt-exportproxy:v1.4.0-alpha.0
> ```
> 
> This will ensure that the image for the x86 architecture is pulled on x86 hosts.
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

I believe this is actually pointing at the underlying issue. `docker pull --platform=linux/amd64 quay.io/kubevirt/virt-exportproxy:v1.4.0-alpha.0` return the s390x variant.

**Comment by jschintag** [comment]
Yes, running an inspect on the image, it is claiming to be x86. So docker is pulling the correct manifest, though i'm puzzled why the binary is s390x, since the virt-exportproxy is currently not even enabled for s390x. It shouldn't build it at all for s390x...

**Comment by jschintag** [comment]
I think from what i can gather, the following happened to cause this:
1. The release builds all arches, in order: s390x, aarch64, x86_64
2. It compiled the s390x virt-exportproxy binary and then defaulted to put it into the x86_64 image
3. It compiled aarch64 normally
4. Bazel build x86_64 and noticed the virt-exportproxy image was already present (build by s390x target with s390x binary and x86_64 image)

I think a possible solution would be to change the order here to build the default x86_64 target first.

**Comment by akalenyu** [comment]
@jschintag thank you for looking into this!
sidebar questions.
we noticed the s390x image still works for some of us locally, while it doesn't for others.
how come docker is able to run this binary for me, even though I am on x86?

**Comment by oshoval** [comment]
> sidebar question;
> we noticed the s390x image still works for some of us locally, while it doesn't for others.
> how come docker is able to run this binary for me, even though I am on x86?

qemu emulation i guess
https://github.com/simonw/til/blob/main/docker/emulate-s390x-with-qemu.md

**Comment by oshoval** [comment]
> I think from what i can gather, the following happened to cause this:
> 
> 1. The release builds all arches, in order: s390x, aarch64, x86_64
> 2. It compiled the s390x virt-exportproxy binary and then defaulted to put it into the x86_64 image
> 3. It compiled aarch64 normally
> 4. Bazel build x86_64 and noticed the virt-exportproxy image was already present (build by s390x target with s390x binary and x86_64 image)
> 
> I think a possible solution would be to change the order here to build the default x86_64 target first.

or maybe to enforce with some flag what is the default, instead of order ?

**Comment by jschintag** [comment]
>or maybe to enforce with some flag what is the default, instead of order ?

@oshoval The default in bazel is already x86_64. The problem is more that i think bazel is not checking if the image input (the binary) would need to be rebuilt. But i'm still investigating and at least yesterday enabling the 2 images [(see PR)](https://github.com/kubevirt/kubevirt/pull/12844) did not actually solve it for me. Though i need to re-check again with empty bazel cache.

**Comment by jschintag** [comment]
I did some diggin while the build is running, and it seems there are 2 amd64 images being generated:
```
$ podman manifest inspect quay.io/kubevirt/virt-exportproxy:v1.4.0-alpha.0
{
    "schemaVersion": 2,
    "mediaType": "application/vnd.docker.distribution.manifest.list.v2+json",
    "manifests": [
        {
            "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
            "size": 2846,
            "digest": "sha256:9a0bde40dc90c81439f2cbf79a749cc5598380ec54895080909591e65450dc83",
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            }
        },
        {
            "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
            "size": 2846,
            "digest": "sha256:89a56775d64a5e8f9a7a923839a0f9484b107b12e75db91bd68c0349fae0838a",
            "platform": {
                "architecture": "arm64",
                "os": "linux"
            }
        },
        {
            "mediaType": "application/vnd.docker.distribution.manifest.v2+json",
            "size": 2846,
            "digest": "sha256:6c050c1f795e4cefffaf75b6e79c7451eb92f7d1c635237b1a7bce6ef440a561",
            "platform": {
                "architecture": "amd64",
                "os": "linux"
            }
        }
    ]
}
```
So i don't think changing the order would be a good solution anymore. Better to find out if there is some kind of no-op option for bazel to tell it to just ignore the target when the arch is not wanted.

**Comment by oshoval** [comment]
nice thanks
maybe worth to check if same happens when docker CRI is used?

**Comment by brianmcarey** [comment]
> nice thanks maybe worth to check if same original bug happens when docker CRI is used for building ?

these images are built with bazel.

**Comment by oshoval** [comment]
> these images are built with bazel.

then maybe worth to ask via an issue on bazel / search if one exists?

**Comment by jschintag** [comment]
Testing my PR again today confirms it fixes the issue for exportserver and exportproxy.
No idea if the problems yesterday was bazel cache or i was just tired.

**Comment by brianmcarey** [comment]
@jschintag - I think we need to set a subset of PUSH_TARGETS for s390x here - https://github.com/kubevirt/kubevirt/blob/main/hack/bazel-push-images.sh

I can see other images that have two amd64 images like `network-passt-binding` - https://quay.io/repository/kubevirt/network-passt-binding?tab=tags

**Comment by jschintag** [comment]
Looking at the build targets, we can/must do it the bazel way and select the target images using the already existing bazel target `build-other-images` which seems to contain a lot of the non-core images. However it is also a bit inconsistent at least to me what is added via the bazel target and what is added by the bash script.
That of course disregards the bazel-push-images targets.

**Comment by oshoval** [comment]
> I can see other images that have two amd64 images like `network-passt-binding` - https://quay.io/repository/kubevirt/network-passt-binding?tab=tags

cc @EdDev (about passt) fyi please

**Comment by jschintag** [comment]
I have opened #12844 to properly fix this issue by ensuring images for each architecture are only built if they are actually enabled.
Please note that for testing the PR, you need to ensure you do not have any old manifests lying around by deleting the bazel cache with `podman volume rm kubevirt`.
