### ISSUE TITLE
add unit and functional test to the cloner controller

### ISSUE THREAD

**Issue by jeffvance** [kubevirt/kubevirt#1284]
This important piece was intentionally omitted due to schedule pressure but needs to be done as the next pr for the cloner. However, there is a dependency on a unit test/make pr which has not yet been started -- see @copejon 
@zvikorn @screeley44

**Comment by jeffvance** [comment]
Scott, do you have time to work with Tzvi on this issue?

**Comment by rmohr** [comment]
@jeffvance can it be that this issue belongs to https://github.com/kubevirt/containerized-data-importer?

**Comment by jeffvance** [comment]
Yes it does. Moved it. Sorry.
