### ISSUE TITLE
Storage live migration appears to allocate zeros during live migration

### ISSUE THREAD

**Issue by awels** [kubevirt/kubevirt#12876]
**What happened**:
While observing the actual storage in use in my ceph cluster, I noticed the following scenario happen. I created a 30Gi centos9 VM from a template. Together with some other storage in use, the ceph tools are reporting 110Gi of actual space in use.
If I do an offline storage migration using konveyor, it creates a new PVC and then copies over the bytes to the new PVC, and it takes empty block into account. After it completed migrating the space in use was 115Gi. Which is about right. The original disk was using about 1.5Gi of actual space. And since I have replica 3 in ceph it uses 3x that much space.

Now I remove the new PVC, and my storage is back to 110Gi. But this time I do a storage live migration by modifying the VM spec appropriately. During the migration I can see the real space in use on my ceph cluster continue to spike. Once the migration is done, the actual space in use is 200Gi. Which makes sense if all the 0s are written out. 3x30=90 So 110 + 90 = 200.

**What you expected to happen**:
A storage live migration knows it can skip writing 0s and thus won't allocate the space on the storage.

**How to reproduce it (as minimally and precisely as possible)**:
See steps above

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): main
- Kubernetes version (use `kubectl version`): 1.30
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by awels** [comment]
@alicefr Can you please take a look. I am unable to test file-system based storage live migration due to #12875

**Comment by alicefr** [comment]
@awels After talking with my collegues from virtualization, qemu might not be able to see the zero from the block device. This will require some small modification in libvirt in order to read the zero from the source image. I'll open the RFC asap.
