### ISSUE TITLE
some virtctl unit tests are coupled to local kubeconfig

### ISSUE THREAD

**Issue by akalenyu** [kubevirt/kubevirt#12891]
**What happened**:
having a ~/.kube/config messes up virtctl unit tests
since the namespace gets picked up from there.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
for example, login into a remote cluster using local kubectl and then run vmexport unit tests using
`go test`

**Additional context**:
```
• [FAILED] [0.001 seconds]
vmexport VMExport succeeds [It] Succesfully create VirtualMachineExport with TTL
/home.../kubevirt/pkg/virtctl/vmexport/vmexport_test.go:540

  [FAILED] Unexpected call to *kubecli.MockKubevirtClient.VirtualMachineExport([akalenyu]) at /.../kubevirt/pkg/virtctl/vmexport/vmexport.go:428 because: 
  expected call at /.../kubevirt/vendor/kubevirt.io/client-go/kubecli/generated_mock_kubevirt.go:217 doesn't match the argument at index 0.
  Got: akalenyu (string)
  Want: is equal to default (string)
```

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by akalenyu** [comment]
> To prevent `virtctl` unit tests from being affected by the local `kubeconfig`, specifically the namespace configuration, you can set the `KUBEVIRT_TEST_NAMESPACE` environment variable to a specific namespace for the tests. This ensures that the tests use the specified namespace instead of the one configured in the local `kubeconfig`.
> 
> Here is an example of how you can set this environment variable in your test setup:
> 
> ```go
> import (
>     "os"
>     "testing"
> )
> 
> func TestMain(m *testing.M) {
>     // Set the KUBEVIRT_TEST_NAMESPACE environment variable
>     os.Setenv("KUBEVIRT_TEST_NAMESPACE", "kubevirt-test-default")
> 
>     // Run the tests
>     code := m.Run()
> 
>     // Clean up
>     os.Unsetenv("KUBEVIRT_TEST_NAMESPACE")
> 
>     // Exit with the test code
>     os.Exit(code)
> }
> ```
> 
> By setting the `KUBEVIRT_TEST_NAMESPACE` environment variable, you ensure that the tests use the `kubevirt-test-default` namespace, regardless of the namespace configured in the local `kubeconfig` [[1]](https://github.com/kubevirt/kubevirt/blob/main/tests/testsuite/namespace.go).
> 
> _To continue talking to [Dosu](https://dosu.dev), mention @dosu._

I don't think that environment variable ever gets respected in the client libraries

**Comment by iholder101** [comment]
> > To prevent `virtctl` unit tests from being affected by the local `kubeconfig`, specifically the namespace configuration, you can set the `KUBEVIRT_TEST_NAMESPACE` environment variable to a specific namespace for the tests. This ensures that the tests use the specified namespace instead of the one configured in the local `kubeconfig`.
> > Here is an example of how you can set this environment variable in your test setup:
> > ```go
> > import (
> >     "os"
> >     "testing"
> > )
> > 
> > func TestMain(m *testing.M) {
> >     // Set the KUBEVIRT_TEST_NAMESPACE environment variable
> >     os.Setenv("KUBEVIRT_TEST_NAMESPACE", "kubevirt-test-default")
> > 
> >     // Run the tests
> >     code := m.Run()
> > 
> >     // Clean up
> >     os.Unsetenv("KUBEVIRT_TEST_NAMESPACE")
> > 
> >     // Exit with the test code
> >     os.Exit(code)
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > By setting the `KUBEVIRT_TEST_NAMESPACE` environment variable, you ensure that the tests use the `kubevirt-test-default` namespace, regardless of the namespace configured in the local `kubeconfig` [[1]](https://github.com/kubevirt/kubevirt/blob/main/tests/testsuite/namespace.go?rgh-link-date=2024-09-22T12%3A54%3A54Z).
> > _To continue talking to [Dosu](https://dosu.dev), mention @dosu._
> 
> I don't think that environment variable ever gets respected in the client libraries

I think you should `@dosu` for it to listen :)

**Comment by akalenyu** [comment]
> +1 I noticed that as well recently. Are you working on a fix?

Hey, no, do you have some ideas in mind?
