### ISSUE TITLE
k/kubevirt,e2e: don't run e2e tests on OWNERS(_ALIASES) file changes

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#12929]
We should as well not run e2e tests on pure OWNERS and/or OWNERS_ALIASES file changes -as we do for other files already [1] . 

              @dhiller off-topic: I remember having some rules defined to situations where we can skip running the test lanes. I think this is one of them :)

_Originally posted by @iholder101 in https://github.com/kubevirt/kubevirt/issues/12909#issuecomment-2370743844_

FYI @iholder101
            

[1]: https://github.com/kubevirt/kubevirt/blob/4917afe9e2576a430e34ae4051f8c7ca84214027/automation/test.sh#L33

**Comment by dhiller** [comment]
There might be a bug lurking here, since the pattern has already been added.

/kind bug

**Comment by dhiller** [comment]
After checking the PR history I see that everything is working as expected: the lanes all report less than 1m execution time.

FYI @iholder101 

/close

**Comment by iholder101** [comment]
> After checking the PR history I see that everything is working as expected: the lanes all report less than 1m execution time.
> 
> FYI @iholder101
> 
> /close

Awesome that it's working! Sorry for the noise.
Thank you @dhiller!
