### ISSUE TITLE
Flaky tests detected: `VSOCK communicating with VMI via VSOCK should succeed`

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#12930]
# What happened

Flaky test detected: `VSOCK communicating with VMI via VSOCK should succeed` [1] 

Tests: `VSOCK communicating with VMI via VSOCK should succeed` have shown impact around 2% during the last couple days [2] 

Flakefinder report entries:
* https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flake-stats-14days-2024-09-25.html#%5bsig-compute%5dVSOCK%20communicating%20with%20VMI%20via%20VSOCK%20should%20succeed%20with%20TLS%20on%20both%20sides
* https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flake-stats-14days-2024-09-25.html#%5bsig-compute%5dVSOCK%20communicating%20with%20VMI%20via%20VSOCK%20should%20succeed%20without%20TLS%20on%20both%20sides
* https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2024-10-08-024h.html#row17

/kind flake
/priority critical-urgent

/sig compute

[1]: https://github.com/kubevirt/kubevirt/blob/da98fe25735475d49beb55b5ee5e636c5e2505fb/tests/vmi_vsock_test.go#L174
[2]: https://search.ci.kubevirt.io/?search=VSOCK+communicating+with+VMI+via+VSOCK+should+succeed&maxAge=336h&context=1&type=junit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

## Additional context
Initial [quarantine PR](https://github.com/kubevirt/kubevirt/pull/12901) was closed due to tests not being eligible for quarantine.

# Flake Action Plan

**As the assignee**, **thoroughly review the issue** and put the resulting report as comment into this issue.

### **The flake is a bug**

* Add label commenting `/triage accepted`
* **Create a PR to fix the bug**
* Reference this issue in the PR
* Keep this issue open until the testcase does not fail anymore

### **The flake is non-critical or an issue that is hard to fix**
* **Quarantine the test** by creating a pull request assigning [QUARANTINE] tag to test name and [Quarantine decorator](https://github.com/kubevirt/kubevirt/blob/f85a8117b8a90fd913ec0719faae9506866d1525/tests/decorators/decorators.go#L7) to the test
* Reference this issue on the PR

### There was an infrastructure issue

An infra issue is anything "below" the testcase

* Add label commenting `/triage infra-issue`
* Close the issue, adding a comment with details about the infrastructure issue.

After the flake has been fixed, document the learning from it inside the fix PR

**Comment by dhiller** [comment]
@dosu I don't see any relation to the issue you mentioned here. Can you elaborate?

**Comment by dhiller** [comment]
@dosu yes, please provide details on how the VSOCK communication test is implemented and any known dependencies or configurations that might affect its stability.

**Comment by dhiller** [comment]
Flaky test spotted again: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2024-10-08-024h.html#row17

**Comment by dhiller** [comment]
Flakyness spotted again, #5 on current flake stats report: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flake-stats-14days-2024-10-23.html#%5bsig-compute%5dVSOCK%20communicating%20with%20VMI%20via%20VSOCK%20should%20succeed%20without%20TLS%20on%20both%20sides

**Comment by dhiller** [comment]
@acardace @fossedihelm do you happen to know whether someone is working on this one?

**Comment by acardace** [comment]
@dhiller not that I'm aware unfortunately.

**Comment by fossedihelm** [comment]
@dhiller me neither

**Comment by xpivarc** [comment]
/cc @zhuchenwang @rmohr 
Would you have some time to have a look?

**Comment by zhuchenwang** [comment]
I checked several failures. They all had the following symptom. 

```
{ Failure tests/vmi_vsock_test.go:236
Expected success, but got an error:
    <expect.TimeoutError>: 
    expect: timer expired after 60 seconds
    60000000000
tests/vmi_vsock_test.go:194}
```

Seems like the VMI didn't launch within the time https://github.com/kubevirt/kubevirt/blob/main/tests/vmi_vsock_test.go#L176C18-L176C39

**Comment by xpivarc** [comment]
@zhuchenwang 
The failure is actually here https://github.com/kubevirt/kubevirt/blob/main/tests/vmi_vsock_test.go#L186

```
{"component":"portforward","kind":"VirtualMachineInstance","level":"info","msg":"[{1 chmod +x /usr/bin/example-guest-agent\r\n[root@testvmi-scsjx fedora]#  [#  # ]} {3 echo $?\r\n0\r\n[root@testvmi-scsjx fedora]#  [\n0\r\n[root@testvmi-scsjx fedora]#  # ]} {5 /usr/bin/example-guest-agent --port 1234 --use-tls 2>&1 &\r\n[2] 752\r\n[root@testvmi-scsjx fedora]#  [#  # ]} {7 bash: /usr/bin/example-guest-agent: Text file busy\r\necho $?\r\n0\r\n[2]-  Exit 126                /usr/bin/example-guest-agent --port 1234 --use-tls 2>&1\r\n[root@testvmi-scsjx fedora]#  []}]","name":"testvmi-scsjx","namespace":"kubevirt-test-default1","pos":"console.go:73","timestamp":"2024-10-23T12:45:28.450055Z","uid":"31628afc-b2a6-44f7-acfb-488d1de899b3"}
```

I did not get to decode this...

**Comment by zhuchenwang** [comment]
> @zhuchenwang The failure is actually here https://github.com/kubevirt/kubevirt/blob/main/tests/vmi_vsock_test.go#L186
> 
> ```
> {"component":"portforward","kind":"VirtualMachineInstance","level":"info","msg":"[{1 chmod +x /usr/bin/example-guest-agent\r\n[root@testvmi-scsjx fedora]#  [#  # ]} {3 echo $?\r\n0\r\n[root@testvmi-scsjx fedora]#  [\n0\r\n[root@testvmi-scsjx fedora]#  # ]} {5 /usr/bin/example-guest-agent --port 1234 --use-tls 2>&1 &\r\n[2] 752\r\n[root@testvmi-scsjx fedora]#  [#  # ]} {7 bash: /usr/bin/example-guest-agent: Text file busy\r\necho $?\r\n0\r\n[2]-  Exit 126                /usr/bin/example-guest-agent --port 1234 --use-tls 2>&1\r\n[root@testvmi-scsjx fedora]#  []}]","name":"testvmi-scsjx","namespace":"kubevirt-test-default1","pos":"console.go:73","timestamp":"2024-10-23T12:45:28.450055Z","uid":"31628afc-b2a6-44f7-acfb-488d1de899b3"}
> ```
> 
> I did not get to decode this...

This might be the failure `7 bash: /usr/bin/example-guest-agent: Text file busy\r\necho $?\r\n0\r\n[2]-  Exit 126`.

It seems that the something was trying to update the executable during it was running.

**Comment by xpivarc** [comment]
That seems like the problem. I wonder why it is busy... I see that we execute the binary in background and that makes it pass the `echo $?`... Will you have time to look into possible fix?

**Comment by zhuchenwang** [comment]
I will spend some time to take a look. But to be honest, this is not related to the VSOCK logic, I just call the functions to launch a sample service and expect it to do the right thing.

**Comment by dhiller** [comment]
seen again today on sig-ci tests quarantine meeting: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2024-10-29-024h.html#row5

**Comment by zhuchenwang** [comment]
May I know how is the test executed? Is there any parallel execution configured?

**Comment by zhuchenwang** [comment]
Created PR #13149 to gather more debug information.

**Comment by dhiller** [comment]
seen again on this week's test quarantine meeting: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flake-stats-14days-2024-11-06.html#%5bsig-compute%5dVSOCK%20communicating%20with%20VMI%20via%20VSOCK%20should%20succeed%20without%20TLS%20on%20both%20sides

**Comment by dhiller** [comment]
@fossedihelm checked this test and confirmed that it's not running in parallel.

**Comment by zhuchenwang** [comment]
Can we run the same tests on the PR #13149 ?

**Comment by 0xFelix** [comment]
I might have introduce this flake while changing this test from using `virtctl ssh` to `netcat` for transferring the example VSOCK guest agent to the VM.

https://github.com/kubevirt/kubevirt/blob/4e874a67dc40629fc71977d451a55426c023bee4/tests/vmi_vsock_test.go#L291

Maybe the error is in here? This should wait for `netcat` to exit, only then the binary can be executed.

**Comment by zhuchenwang** [comment]
@0xFelix  Maybe dump the output of `lsof /usr/bin/example-guest-agent`?

**Comment by dhiller** [comment]
@0xFelix can you elaborate whether and how we need to fix this?

**Comment by akalenyu** [comment]
Think I figured it out https://github.com/kubevirt/kubevirt/pull/13330
