### ISSUE TITLE
Replace "k8s.io/utils/pointer" with "kubevirt.io/kubevirt/pkg/pointer"

### ISSUE THREAD

**Issue by alicefr** [kubevirt/kubevirt#12949]
**Is your feature request related to a problem? Please describe**:
In the code we used  `k8s.io/utils/pointer` package but this is has been replaced with the kubevirt package `kubevirt.io/kubevirt/pkg/pointer`. As a reference, you can see the best-practice in [kubevirt coding conventions](https://github.com/kubevirt/kubevirt/blob/main/docs/coding-conventions.md#short-coding-conventions-tldr)

**Describe the solution you'd like**:
Replace all the leftover  `k8s.io/utils/pointer` with `kubevirt.io/kubevirt/pkg/pointer` functions

**Describe alternatives you've considered**:
Keep the code messy and with multiple libraries which do the same thing

**Additional context**:
Good first issue for new contributors

**Comment by anishbista60** [comment]
@alicefr there are so many file to change. Should i make changes to single PR or split into multiple one ?

**Comment by alicefr** [comment]
@anishbista60 maybe try to split per directory, the `BUILD.bazel` files they will be updated automatically once you do `make`

**Comment by anishbista60** [comment]
@alicefr ok , but going to per directory will result into more no. of PR . SO, IMO i will try to make a PR with changes in 10 files. would it be fine ?

**Comment by alicefr** [comment]
> @alicefr ok , but going to per directory will result into more no. of PR . SO, IMO i will try to make a PR with changes in 10 files. would it be fine ?

Sure, you can try also to see by components and directory like `pkg/virt-launcher`, `pkg/virt-controller`... Even if the PR is large, it should be relatively simple to review. The only issue if you change multiple file together in the same PR is that rebases might occur more frequently.

**Comment by anishbista60** [comment]
> > @alicefr ok , but going to per directory will result into more no. of PR . SO, IMO i will try to make a PR with changes in 10 files. would it be fine ?
> 
> Sure, you can try also to see by components and directory like `pkg/virt-launcher`, `pkg/virt-controller`... Even if the PR is large, it should be relatively simple to review. The only issue if you change multiple files together in the same PR is that rebases might occur more frequently.

yeah, Agreed . Would be problem with rebasing . Then i will go with directory wise. Thank you .

**Comment by anishbista60** [comment]
please look into all of this PR .

**Comment by orelmisan** [comment]
@alicefr could you please add the reason for this change in the issue's description?

**Comment by alicefr** [comment]
> @alicefr could you please add the reason for this change in the issue's description?

@orelmisan well, there is already, we should favor the kubevirt library over the k8s's one. I also linked the document with the kubevirt code-convetion where this is suggested. What should I add on top of this?

**Comment by anishbista60** [comment]
@alicefr Based on today community call. could you please label this issue as `hacktoberfest`?

**Comment by anishbista60** [comment]
Now, this is the last PR which closes the issue. please take a look. 
Thank you every one for your kind review.

**Comment by dhiller** [comment]
> /sig code-quality

/kind cleanup

@alicefr the rename finally landed
