### ISSUE TITLE
Use kubectl context instead of custom config file

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1295]
Today we copy the kubeconfig from the developer environment to the build host in order to give convenient access to the developer environment.

Instead of this we can use the `kubectl context` functionality.

**Comment by scollier** [comment]
@fabiand actually, after walking through the rest of the guide and wrapping my head around how you interact with the instance, personally, I'm ok with the current flow.  I was able to complete everything listed on the page.

**Comment by slintes** [comment]
My (hacky?) approach to this is adding this to the shell config:
`export KUBECONFIG=~/.kube/config:~/go/src/kubevirt.io/kubevirt/cluster/k8s-1.10.3/.kubeconfig`

Also have a look at https://github.com/ahmetb/kubectx :)

**Comment by fabiand** [comment]
> @fabiand actually, after walking through the rest of the guide and wrapping my head around how you interact with the instance, personally, I'm ok with the current flow

Right, that's cool. My reason for this issue is mainly to converge back with how ctxts are managed in kubectl - how others are doing it.

**Comment by fabiand** [comment]
@slintes yeah, that works as well :)

I was just wondering if using kubectl context/cluster etc will just strengthen what is there.

**Comment by rmohr** [comment]
I would not want to do that. It just increases the chance that we mess something up. We also copy over `oc` and `kubectl` btw. Everything neatly separated. It just adds burden to everyone.

**Comment by fabiand** [comment]
I see.
