### ISSUE TITLE
periodic-sig-compute: clustered failure

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#12964]
# What happened

Flaky test lane detected: periodic-kubevirt-e2e-k8s-1.30-sig-compute [1]

/kind flake
/priority critical-urgent

/sig compute

[1]: https://prow.ci.kubevirt.io/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.30-sig-compute/1838823286897643520

## Additional context
Lots of failures around not matching resource versions:
```
Unexpected error:
    <*errors.errorString | 0xc001091290>: 
    resource & config versions (60496 and  respectively) are not as expected. component: "virt-handler", pod: "virt-handler-vfbjp" 
    {
        s: "resource & config versions (60496 and  respectively) are not as expected. component: \"virt-handler\", pod: \"virt-handler-vfbjp\" ",
    }

```

# Flake Action Plan

**As the assignee**, **thoroughly review the issue** and put the resulting report as comment into this issue.

### **The flake is a bug**

* Add label commenting `/triage accepted`
* **Create a PR to fix the bug**
* Reference this issue in the PR
* Keep this issue open until the testcase does not fail anymore

### **The flake is non-critical or an issue that is hard to fix**
* **Quarantine the test** by creating a pull request assigning [QUARANTINE] tag to test name and [Quarantine decorator](https://github.com/kubevirt/kubevirt/blob/f85a8117b8a90fd913ec0719faae9506866d1525/tests/decorators/decorators.go#L7) to the test
* Reference this issue on the PR

### There was an infrastructure issue

An infra issue is anything "below" the testcase

* Add label commenting `/triage infra-issue`
* Close the issue, adding a comment with details about the infrastructure issue.

After the flake has been fixed, document the learning from it inside the fix PR

**Comment by xpivarc** [comment]
/close
I see few `etcdserver: request timed out` and the highlighted error suggests that our components are failing to receive new version of KV for the config. Therefore I am quit sure this is infra issue, please reopen if this is not isolated incident.
