### ISSUE TITLE
Making the Live Migration being-aware of the exisiting copy-on-write pages merged by KSM

### ISSUE THREAD

**Issue by Roja-Eswaran** [kubevirt/kubevirt#13022]
Kubevirt uses KSM to merge multiple shared pages into a single Copy-on-write (COW) Page.  The problem with the current live migration of Kubvirt VM using both pre-copy and post-copy is that it's unaware of the pages merged by KSM; as a result, the pre-existing page sharing is not preserved when migrating VMs to a common destination machine. Consequently, each shared page is replicated at the destination multiple times as if they were separate pages. This expansion of the memory footprint of VMs during migration can lead to problems such as migration failure, increased network traffic, and longer migration times. I propose Sharing-aware Live Migration (SLM), which preserves pre-existing COW page sharing within and across VMs that are migrated to a common destination machine. The key idea is to identify guest pages that are mapped to the same physical page at the source machine and to map them to the same physical page at the destination. I present the SLM technique for both pre-copy and post-copy live migration of multiple VMs and describe its implementation on the KVM/QEMU virtualization platform. My evaluations show that SLM successfully preserves pre-existing COW page sharing during migration, eliminates the risk of migration failure due to memory expansion, and reduces total migration time and network traffic overhead.

The above feature implementation detail can be found here: https://kartikgopalan.github.io/publications/ccgrid24.pdf
If the Kubevirt community is interested in this feature, I would like to discuss further about the implementation. Looking forward to ii.

**Comment by iholder101** [comment]
@Roja-Eswaran If you're working on this from the libvirt/QEMU side, it'd be appreciated if you can link your PRs here.

p.s. with such approach there will be need to validate that the target node has KSM enabled.
