### ISSUE TITLE
Unable to write virtiofs filesystem without sudo

### ISSUE THREAD

**Issue by t-eldeeb** [kubevirt/kubevirt#13028]
**What happened**:
I am mounting a PVC-based filesystem in my VM, using non-privileged mode.
The PVC is provisioned dynamically using [this](https://docs.weka.io/appendices/weka-csi-plugin) CSI plugin, with the ownership set to uid/gid of 107 and permissions set to 0777.
Everything works fine, except I am unable to write to the mount directory (e.g. create new files) without sudo, despite the mount point in the VM also having drwxrwsrwx. We are *not* using SELinux

Example, we get the following error:

> touch foo.txt
> touch: setting times of 'foo.txt': No such file or directory

If I create a user and assign it the UID 107, I can use that user to write without sudo. Unfortunately, it's not straightforward for us to use that user and would prefer to be able to use normal user id 1000.

**What you expected to happen**:
Able to create files without the above error

**How to reproduce it (as minimally and precisely as possible)**:
Create VM with PVC file share, mount the file share, attempt to create a file in the mount directory as non-root.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): 

> Client Version: version.Info{GitVersion:"v1.3.1", GitCommit:"ed1e7ae8548d319fa7aacf315ad198f7241287c5", GitTreeState:"clean", BuildDate:"2024-08-22T08:52:25Z", GoVersion:"go1.22.2 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}
> Server Version: version.Info{GitVersion:"", GitCommit:"72e5758bd265de51ecf67a107c9e9279d0ed7b11", GitTreeState:"clean", BuildDate:"2024-03-26T22:37:46Z", GoVersion:"go1.21.5 X:nocoverageredesign", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):

> kubectl version
> Client Version: v1.30.3
> Kustomize Version: v5.0.4-0.20230601165947-6ce0bf390ce3
> Server Version: v1.30.5

- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by xpivarc** [comment]
Hi @t-eldeeb , just to confirm you are using `filesystems` / virtiofs, right?

**Comment by t-eldeeb** [comment]
Hi @xpivarc and @alicefr. Thanks for your response. Yes we are using filesystems and virtiofs.

So to understand more about the limitations, this is expected with non-privileged mode and we need to enable the ExperimentalVirtiofsSupport feature gate and run in privileged mode for this to work properly?

**Comment by alicefr** [comment]
> Hi @xpivarc and @alicefr. Thanks for your response. Yes we are using filesystems and virtiofs.
> 
> So to understand more about the limitations, this is expected with non-privileged mode and we need to enable the ExperimentalVirtiofsSupport feature gate and run in privileged mode for this to work properly?

Yes, then virtiofs should run in a root container and then PVCs should work. This design proposal illustrates how this should change in the future: https://github.com/kubevirt/community/pull/313

**Comment by t-eldeeb** [comment]
Thanks for confirming @alicefr. I am going to keep an eye on the design proposal you linked.

Follow up question: is it possible to configure the QEMU UID/GID when running the VM pods, or is it hard coded to be 107 always?

**Comment by alicefr** [comment]
> Thanks for confirming @alicefr. I am going to keep an eye on the design proposal you linked.
> 
> Follow up question: is it possible to configure the QEMU UID/GID when running the VM pods, or is it hard coded to be 107 always?
> 

Yes, we have harcoded  in the code (I already answered you in slack, but repeating here the answer). Why would you like to change the QEMU uid/gid? To be clear, the uid/gid that virtiofs needs to change are the ones inside the guest and the fs, not the one for running QEMU.

> Also, does using ExperimentalVirtiofsSupport only run the virtiofs in a root container, or the whole Virt launcher as well?

Only virtiofs, but the virt-launcher pod has a root container in it (virtiofs).
