### ISSUE TITLE
virtual image size 46137344 is larger than the reported available storage -1. A larger PVC is required

### ISSUE THREAD

**Issue by mengkai514** [kubevirt/kubevirt#13049]
**What happened**:
When uploading a very small image (cirros-0.4.0-x86_64-disk.img 12M) I always get this error :

**unexpected return value 400, Saving stream failed: Virtual image size 46137344 is larger than the reported available storage -1. A larger PVC is required.**

**The upload-pod logs:**
`
E1011 01:54:00.722615       1 uploadserver.go:452] Saving stream failed: Unable to convert source data to target format: virtual image size 46137344 is larger than the reported available storage -1. A larger PVC is required
I1011 01:54:28.142993       1 uploadserver.go:377] Content type header is ""
I1011 01:54:28.143018       1 data-processor.go:348] Calculating available size
E1011 01:54:28.143818       1 data-processor.go:352] exit status 1, blockdev: cannot open /dev/cdi-block-volume: Permission denied
I1011 01:54:28.143832       1 data-processor.go:360] Checking out file system volume size.
E1011 01:54:28.143842       1 data-processor.go:363] no such file or directory
I1011 01:54:28.143850       1 data-processor.go:368] Request image size not empty.
I1011 01:54:28.143866       1 data-processor.go:373] Target size -1.
I1011 01:54:28.144118       1 data-processor.go:247] New phase: TransferScratch
I1011 01:54:28.146764       1 util.go:96] Writing data...
I1011 01:54:28.254634       1 data-processor.go:247] New phase: ValidatePause
I1011 01:54:28.254678       1 data-processor.go:253] Validating image
E1011 01:54:28.260125       1 prlimit.go:156] failed to kill the process; os: process already finished
E1011 01:54:28.260224       1 data-processor.go:243] virtual image size 46137344 is larger than the reported available storage -1. A larger PVC is required
E1011 01:54:28.260238       1 uploadserver.go:390] Saving stream failed: virtual image size 46137344 is larger than the reported available storage -1. A larger PVC is required`

**And I have modified the configuration of containerd**
`device_ownership_from_security_context = true`

**What you expected to happen**:
500 Gi should be enough for this small image actually even less.

**How to reproduce it (as minimally and precisely as possible)**:
`wget https://download.cirros-cloud.net/0.4.0/cirros-0.4.0-x86_64-disk.img`

**Additional context**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.21.5
- CDI version (use kubectl get deployments cdi-deployment -o yaml): v1.60.3
- Containerd version: 1.5.7

**Comment by awels** [comment]
CDI has its own issue tracker, but the pertinent error appears to be `blockdev: cannot open /dev/cdi-block-volume` which indicates to me that containerd is not configured properly. Look at https://github.com/kubevirt/containerized-data-importer/blob/main/doc/block_cri_ownership_config.md on how to configured containerd to allow the user access to the block device.

**Comment by mengkai514** [comment]
`device_ownership_from_security_context = true`
This configuration is only **valid in Containerd v1.6.0 and above**
