### ISSUE TITLE
 Unable to convert source data to target format: Conversion to Raw failed: could not convert image to raw: qemu-img execution failed

### ISSUE THREAD

**Issue by mengkai514** [kubevirt/kubevirt#13089]
**What happened**:
**I encountered this error when I uploaded the image using upload populator. And I use hostpath-provisioner. This is a permissions issue, but I have already set：**
`[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
    device_ownership_from_security_context = true`

I1018 06:18:17.013696       1 uploadserver.go:438] Content type header is ""
I1018 06:18:17.013733       1 data-processor.go:348] Calculating available size
I1018 06:18:17.013758       1 data-processor.go:360] Checking out file system volume size.
I1018 06:18:17.013766       1 data-processor.go:368] Request image size not empty.
I1018 06:18:17.013774       1 data-processor.go:373] Target size 1Gi.
I1018 06:18:17.013942       1 data-processor.go:247] New phase: TransferScratch
I1018 06:18:17.017266       1 util.go:96] Writing data...
I1018 06:18:17.082097       1 data-processor.go:247] New phase: Convert
I1018 06:18:17.082149       1 data-processor.go:253] Validating image
E1018 06:18:17.107708       1 prlimit.go:156] failed to kill the process; os: process already finished
I1018 06:18:17.109531       1 qemu.go:115] Running qemu-img with args: [convert -t writeback -p -O raw /scratch/tmpimage /data/disk.img]
E1018 06:18:17.116176       1 prlimit.go:178] qemu-img failed output is:
E1018 06:18:17.116279       1 prlimit.go:179]     (0.00/100%)

E1018 06:18:17.116320       1 prlimit.go:180] qemu-img: /data/disk.img: error while converting raw: Could not create '/data/disk.img': Permission denied

E1018 06:18:17.116527       1 prlimit.go:156] failed to kill the process; os: process already finished
E1018 06:18:17.116898       1 data-processor.go:243] exit status 1
qemu-img execution failed
kubevirt.io/containerized-data-importer/pkg/system.executeWithLimits
        pkg/system/prlimit.go:182
kubevirt.io/containerized-data-importer/pkg/system.ExecWithLimits
        pkg/system/prlimit.go:112
kubevirt.io/containerized-data-importer/pkg/image.convertToRaw
        pkg/image/qemu.go:116
kubevirt.io/containerized-data-importer/pkg/image.(*qemuOperations).ConvertToRawStream
        pkg/image/qemu.go:161
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
        pkg/importer/data-processor.go:272
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func6
        pkg/importer/data-processor.go:205
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
        pkg/importer/data-processor.go:240
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
        pkg/importer/data-processor.go:149
kubevirt.io/containerized-data-importer/pkg/uploadserver.newUploadStreamProcessor
        pkg/uploadserver/uploadserver.go:500
kubevirt.io/containerized-data-importer/pkg/uploadserver.(*uploadServerApp).processUpload
        pkg/uploadserver/uploadserver.go:445
kubevirt.io/containerized-data-importer/pkg/uploadserver.NewUploadServer.(*uploadServerApp).uploadHandler.func1
        pkg/uploadserver/uploadserver.go:471
net/http.HandlerFunc.ServeHTTP
        GOROOT/src/net/http/server.go:2166
net/http.(*ServeMux).ServeHTTP
        GOROOT/src/net/http/server.go:2683
kubevirt.io/containerized-data-importer/pkg/uploadserver.(*uploadServerApp).ServeHTTP
        pkg/uploadserver/uploadserver.go:311
net/http.serverHandler.ServeHTTP
        GOROOT/src/net/http/server.go:3137
net/http.(*conn).serve
        GOROOT/src/net/http/server.go:2039
runtime.goexit
        src/runtime/asm_amd64.s:1695
could not convert image to raw
kubevirt.io/containerized-data-importer/pkg/image.convertToRaw
        pkg/image/qemu.go:124
kubevirt.io/containerized-data-importer/pkg/image.(*qemuOperations).ConvertToRawStream
        pkg/image/qemu.go:161
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
        pkg/importer/data-processor.go:272
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func6
        pkg/importer/data-processor.go:205
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
        pkg/importer/data-processor.go:240
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
        pkg/importer/data-processor.go:149
kubevirt.io/containerized-data-importer/pkg/uploadserver.newUploadStreamProcessor
        pkg/uploadserver/uploadserver.go:500
kubevirt.io/containerized-data-importer/pkg/uploadserver.(*uploadServerApp).processUpload
        pkg/uploadserver/uploadserver.go:445
kubevirt.io/containerized-data-importer/pkg/uploadserver.NewUploadServer.(*uploadServerApp).uploadHandler.func1
        pkg/uploadserver/uploadserver.go:471
net/http.HandlerFunc.ServeHTTP
        GOROOT/src/net/http/server.go:2166
net/http.(*ServeMux).ServeHTTP
        GOROOT/src/net/http/server.go:2683
kubevirt.io/containerized-data-importer/pkg/uploadserver.(*uploadServerApp).ServeHTTP
        pkg/uploadserver/uploadserver.go:311
net/http.serverHandler.ServeHTTP
        GOROOT/src/net/http/server.go:3137
net/http.(*conn).serve
        GOROOT/src/net/http/server.go:2039
runtime.goexit
        src/runtime/asm_amd64.s:1695
Conversion to Raw failed
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).convert
        pkg/importer/data-processor.go:274
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func6
        pkg/importer/data-processor.go:205
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
        pkg/importer/data-processor.go:240
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
        pkg/importer/data-processor.go:149
kubevirt.io/containerized-data-importer/pkg/uploadserver.newUploadStreamProcessor
        pkg/uploadserver/uploadserver.go:500
kubevirt.io/containerized-data-importer/pkg/uploadserver.(*uploadServerApp).processUpload
        pkg/uploadserver/uploadserver.go:445
kubevirt.io/containerized-data-importer/pkg/uploadserver.NewUploadServer.(*uploadServerApp).uploadHandler.func1
        pkg/uploadserver/uploadserver.go:471
net/http.HandlerFunc.ServeHTTP
        GOROOT/src/net/http/server.go:2166
net/http.(*ServeMux).ServeHTTP
        GOROOT/src/net/http/server.go:2683
kubevirt.io/containerized-data-importer/pkg/uploadserver.(*uploadServerApp).ServeHTTP
        pkg/uploadserver/uploadserver.go:311
net/http.serverHandler.ServeHTTP
        GOROOT/src/net/http/server.go:3137
net/http.(*conn).serve
        GOROOT/src/net/http/server.go:2039
runtime.goexit
        src/runtime/asm_amd64.s:1695
Unable to convert source data to target format
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).initDefaultPhases.func6
        pkg/importer/data-processor.go:207
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
        pkg/importer/data-processor.go:240
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
        pkg/importer/data-processor.go:149
kubevirt.io/containerized-data-importer/pkg/uploadserver.newUploadStreamProcessor
        pkg/uploadserver/uploadserver.go:500
kubevirt.io/containerized-data-importer/pkg/uploadserver.(*uploadServerApp).processUpload
        pkg/uploadserver/uploadserver.go:445
kubevirt.io/containerized-data-importer/pkg/uploadserver.NewUploadServer.(*uploadServerApp).uploadHandler.func1
        pkg/uploadserver/uploadserver.go:471
net/http.HandlerFunc.ServeHTTP
        GOROOT/src/net/http/server.go:2166
net/http.(*ServeMux).ServeHTTP
        GOROOT/src/net/http/server.go:2683
kubevirt.io/containerized-data-importer/pkg/uploadserver.(*uploadServerApp).ServeHTTP
        pkg/uploadserver/uploadserver.go:311
net/http.serverHandler.ServeHTTP
        GOROOT/src/net/http/server.go:3137
net/http.(*conn).serve
        GOROOT/src/net/http/server.go:2039
runtime.goexit
        src/runtime/asm_amd64.s:1695
E1018 06:18:17.117078       1 uploadserver.go:452] Saving stream failed: Unable to convert source data to target format: Conversion to Raw failed: could not convert image to raw: qemu-img execution failed: exit status 1

**What you expected to happen**:
Image upload successful！

**How to reproduce it (as minimally and precisely as possible)**:
The hostpath-provisioner ：https://github.com/akalenyu/hostpath-provisioner-operator/blob/main/README.md

> root@k8s-master:/home/mengkai/Desktop/cdi-yaml# sudo kubectl get svc -A
NAMESPACE              NAME                                                    TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)                  AGE
cdi                    cdi-api                                                 ClusterIP   10.96.236.77     <none>        443/TCP                  21h
cdi                    cdi-prometheus-metrics                                  ClusterIP   10.109.191.222   <none>        8080/TCP                 21h
cdi                    cdi-uploadproxy                                         ClusterIP   10.110.94.25     <none>        443/TCP                  21h
cert-manager           cert-manager                                            ClusterIP   10.103.226.221   <none>        9402/TCP                 4h20m
cert-manager           cert-manager-webhook                                    ClusterIP   10.111.226.199   <none>        443/TCP                  4h20m
default                cdi-upload-prime-a10e241f-d040-415b-8bd1-39fd5ab82304   ClusterIP   10.108.68.221    <none>        443/TCP                  13m
default                kubernetes                                              ClusterIP   10.96.0.1        <none>        443/TCP                  24h
hostpath-provisioner   hostpath-provisioner-operator-webhook-service           ClusterIP   10.106.114.245   <none>        443/TCP                  4h11m
kube-system            kube-dns                                                ClusterIP   10.96.0.10       <none>        53/UDP,53/TCP,9153/TCP   24h

**curl -v --insecure -H "Authorization: Bearer $TOKEN" --data-binary @/home/mengkai/Desktop/cdi-yaml/cirros-0.4.0-x86_64-disk.img https://10.110.94.25:443/v1beta1/upload**

**Additional context**:

**Environment**:
- Kubernetes version (use `kubectl version`): 1.25.0
- CDI version：1.60.3
- containerd version：1.6.8

**Comment by awels** [comment]
When you say you use hostpath provisioner, is it the kubevirt hostpath provisioner? Or another hostpath provisioner (there are several, just making sure which one)

**Comment by mengkai514** [comment]
kubevirt hostpath provisioner
https://github.com/kubevirt/hostpath-provisioner-operator/

**Comment by awels** [comment]
Okay can you show me the hpp CR you used? There should not be any permission issues if you installed the csi version.

**Comment by mengkai514** [comment]
@awels 

> apiVersion: hostpathprovisioner.kubevirt.io/v1beta1
kind: HostPathProvisioner
metadata:
  name: hostpath-provisioner
spec:
  imagePullPolicy: IfNotPresent
  storagePools:
    - name: "local"
      pvcTemplate:
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
      path: "/home/nfs"
  workload:
    nodeSelector:
      kubernetes.io/os: linux

**Comment by mengkai514** [comment]
I found the reason. The issue was caused by the difference in accessModes between the Storage Class and the PVC.

**Comment by awels** [comment]
Okay so it had likely something to do with the permissions on the nfs share. Glad you found the issue though.
