### ISSUE TITLE
Not able to debug libvirt issues if launcher crashes

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1310]
**What happened**:
A VM fails to start, the pod logs hint that it's a libvirt issues:

```
level=info timestamp=2018-07-13T09:22:14.125248Z pos=libvirt.go:256 component=virt-launcher msg="Connecting to libvirt daemon: qemu:///system"

level=error timestamp=2018-07-13T09:22:14.207290Z pos=libvirt_helper.go:146 component=virt-launcher msg="libvirtd exited, restarting"

level=error timestamp=2018-07-13T09:22:15.244135Z pos=libvirt_helper.go:146 component=virt-launcher msg="libvirtd exited, restarting"

level=error timestamp=2018-07-13T09:22:16.280373Z pos=libvirt_helper.go:146 component=virt-launcher msg="libvirtd exited, restarting"
…
panic: failed to connect to libvirtd: cannot connect to libvirt daemon: timed out waiting for the condition

goroutine 1 [running]:

main.createLibvirtConnection(0xc4200b4d80, 0x11f4c80)

    /root/go/src/kubevirt.io/kubevirt/cmd/virt-launcher/virt-launcher.go:111 +0x125

main.main()

    /root/go/src/kubevirt.io/kubevirt/cmd/virt-launcher/virt-launcher.go:253 +0x440

virt-launcher exited with code 2
```

When trying to exec into the compute pod, this fails, because the container continues to crash.

**What you expected to happen**:
Either get the libvirt logs on the pod logs. Or ability to log into the pod to debug libvirt

**How to reproduce it (as minimally and precisely as possible)**:
Make virt-launcher crash and try to debug libvirt

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.7.0-alpha.2
- Kubernetes version (use `kubectl version`): 1.11
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cynepco3hahue** [comment]
In general, we can enable libvirt logs to write to `/var/log/libvirt` and to add the possibility to add PVC that will be mounted to this directory. @fabiand Will it be good enough?

**Comment by fabiand** [comment]
Logs are written afaik.

The issue is that the container is restarting to fast to get them.
Adding a PVC could help. But if we use the PVC approach, then we should see that it fits in with other log aggregation.

What I want to say: libvirt logs are important for for debugging, thus these logs must land in the log aggregation system of the cluster.
Thus here to me it would be important to understand if it's a common pattern (and I heared that it was thought of) to use PVCs for log writing, and then also for log collection.

**Comment by rmohr** [comment]
From my point of view the `virt-launcher` process which also starts and monitors libvirt should also collect the logs and write them to stdout. If we change the architecture on how we use libvirt we can change that again. Right now that seems to be the most logical solution ...

**Comment by fabiand** [comment]
That looks straight forward.

Although we could also add a fluentd side-car as described in https://kubernetes.io/docs/concepts/cluster-administration/logging/#sidecar-container-with-a-logging-agent

**Comment by slintes** [comment]
@rmohr would configuration of libvirt to use stderr for all logs be a good solution?
https://libvirt.org/logging.html

**Comment by rmohr** [comment]
> @rmohr would configuration of libvirt to use stderr for all logs be a good solution?
> https://libvirt.org/logging.html

If that works then great. As far as I remember the qemu logs are sent to `virtlogd`. So not sure if we would see these logs then too.

**Comment by cynepco3hahue** [comment]
@slintes Just take in account that libvirt debug log is huge, so it ok for me if you want to send only errors messages to stderr, but you still will have cases when you will need whole debug log.
