### ISSUE TITLE
VMs **sometimes** (maybe 30% chance) get stuck in NotReady state due to macvtap errors: /dev/tapXXX - Permission denied. 

### ISSUE THREAD

**Issue by Dakror** [kubevirt/kubevirt#13169]
**What happened**:

VMs **sometimes** (maybe 30% chance) get stuck in NotReady state due to macvtap errors: /dev/tapXXX - Permission denied. I've not found a log entry of the system or anything regarding SELinux that would explain the flaky behavior

**What you expected to happen**:

The VM should start up normally every time

**How to reproduce it (as minimally and precisely as possible)**:

Running on a microk8s cluster, created VM via API.

**Additional context**:

For both working and non-working tap devices, i can see them created under /dev on the host, with root being the device owner.

**Environment**:
- KubeVirt version (use `virtctl version`): 1.2.2
- Kubernetes version (use `kubectl version`): 1.29.7
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: microk8s on bare metal
- OS (e.g. from /etc/os-release): Fedora 40
- Kernel (e.g. `uname -a`): Linux epyc050 6.10.12-200.fc40.x86_64 #1 SMP PREEMPT_DYNAMIC Mon Sep 30 21:38:25 UTC 2024 x86_64 GNU/Linux
- Install tools: N/A
- Others: macvtap-cni latest

**Comment by EdDev** [comment]
Basic information is missing, including relevant VM/VMI and NAD manifests, logs showing the errors and some context about what is common/special in those 30% cases when it happens.

FYI @maiqueb

**Comment by Dakror** [comment]
More information:

I'm always creating a VM via the API with only exchanging base images and optionally attaching the tap device if selected by the user, the rest of the setup stays the same. 

The "hardware" NAD for macvtap is a single global NAD in the namespace. I create, i think irrelevant to the issue, a separate VPC using kube-ovn for each VM and its corresponding other services in my cluster. This has worked flawlessly. The flaky startup has only started appearing due to the macvtap network attachments.

VM pods are always created on the same single node via nodeSelector. It is running Fedora 40 on an AMD EPYC 7513 32-Core

[nad.yaml.txt](https://github.com/user-attachments/files/17628234/nad.yaml.txt)

[vm-working.yaml.txt](https://github.com/user-attachments/files/17628219/vm-working.yaml.txt)
[vmi-working.yaml.txt](https://github.com/user-attachments/files/17628231/vmi-working.yaml.txt)
[virt-launcher-working.log](https://github.com/user-attachments/files/17628226/virt-launcher-working.log)

[vm-stuck.yaml.txt](https://github.com/user-attachments/files/17628224/vm-stuck.yaml.txt)
[vmi-stuck.yaml.txt](https://github.com/user-attachments/files/17628238/vmi-stuck.yaml.txt)
[virt-launcher-stuck.log](https://github.com/user-attachments/files/17628227/virt-launcher-stuck.log)

Cluster CRD has patches applied for microk8s ubuntu snap paths
[kubevirt-cr.yaml.txt](https://github.com/user-attachments/files/17628278/kubevirt-cr.yaml.txt)

**Comment by maiqueb** [comment]
I am literally clueless on how microk8s implements the nodes, thus I can't say I fully understand what the following sentence actually means:
> For both working and non-working tap devices, i can see them created under /dev on the host, with root being the device owner.

If the tap device is owned by root (I assume it has R/W permissions for the user), and available in the root file-system, how can this fail with `Permission denied` ?

**Comment by Dakror** [comment]
I on the other hand don't know what is supposed to happen.

What i can see on the host is tap devices being created with owner root and RW perms for root. But what might be the issue is that perhaps the user inside the container is not root on the host and so gets the error. Doesn't explain the flakiness though

**Comment by maiqueb** [comment]
> I on the other hand don't know what is supposed to happen.
> 
> What i can see on the host is tap devices being created with owner root and RW perms for root. But what might be the issue is that perhaps the user inside the container is not root on the host and so gets the error. Doesn't explain the flakiness though

The thing is macvtap's CNI is in fact two things: a CNI plugin, and a device plugin. 

The device plugin goes first and creates the macvtap (macvlan + char device  i.e. `/dev/tapXYZ`). Being a device plugin, it makes the device available to the container.

The CNI plugin goes afterwards (after creating the pod's sandbox, and before the container is ready) and just moves the macvlan interface to the pod's netns. The character device was already set with R/W access in the container by the device plugin the the previous step.

**Comment by Dakror** [comment]
Is there any additional logging i can activate or investigate? the macvtap pods don't log anything related as far as i can tell:

```
I1106 09:30:18.323132   83227 manager.go:42] Starting device plugin manager
I1106 09:30:18.323220   83227 manager.go:46] Registering for system signal notifications
I1106 09:30:18.323444   83227 manager.go:52] Registering for notifications of filesystem changes in device plugin directory
I1106 09:30:18.323589   83227 manager.go:60] Starting Discovery on new plugins
I1106 09:30:18.323603   83227 manager.go:66] Handling incoming signals
I1106 09:30:18.323788   83227 lister.go:67] Read configuration map[hardware:{Name:hardware LowerDevice:enp98s0f0 Mode:bridge Capacity:50}]
I1106 09:30:18.323833   83227 manager.go:71] Received new list of plugins: [hardware]
I1106 09:30:18.323859   83227 manager.go:110] Adding a new plugin "hardware"
I1106 09:30:18.323879   83227 lister.go:167] Creating device plugin with config {Name:hardware LowerDevice:enp98s0f0 Mode:bridge Capacity:50}
I1106 09:30:18.323925   83227 plugin.go:64] hardware: Starting plugin server
I1106 09:30:18.323933   83227 plugin.go:94] hardware: Starting the DPI gRPC server
I1106 09:30:18.324408   83227 plugin.go:112] hardware: Serving requests...
I1106 09:30:28.325336   83227 plugin.go:128] hardware: Registering the DPI with Kubelet
I1106 09:30:28.325884   83227 plugin.go:140] hardware: Registration for endpoint macvtap.network.kubevirt.io_hardware
I1106 09:30:28.330053   83227 plugin.go:72] LowerDevice exists, sending ListAndWatch response with available devices
```

**Comment by Dakror** [comment]
I've circumvented the issue by switching to a bridge device together with the bridge CNI plugin. All i initially needed was L2 network access in the VM, which works with the bridge setup aswell.
