### ISSUE TITLE
Check qcow2 before converting it to raw to prohibit DOS

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#1318]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

It is possible to constract qcow2 images which will cause `qemu-img` to consume incredible amounts of cpu and memory. See 
 * https://groups.google.com/d/msg/kubevirt-dev/4h7R8fPq0eU/fyL2IaiSBAAJ
 * https://bugs.launchpad.net/ossa/+bug/1449062

for details. @berrange thx for the hint.

We have at least one place with registry-disks where we do a conversion from `qcow2` to `raw`.

**What you expected to happen**:

It seems like we can prevent that by doing some sanity checks by analyzing `qemu-img info` output and see if it contains reasonable values. Another option is to drop `qcow2`.

**How to reproduce it (as minimally and precisely as possible)**:

See https://groups.google.com/d/msg/kubevirt-dev/4h7R8fPq0eU/fyL2IaiSBAAJ on how to construct such an image. Then use it as a `registryDisk` source.

We also use `qcow2` as `emptyDir` backend. However, there we construct the image. Still we may need to limit the maximum size of `emptyDir`.

**Comment by simon3z** [comment]
cc @aglitke @copejon

**Comment by kfox1111** [comment]
Does the conversion happen under the users quota?

**Comment by rmohr** [comment]
Yes just user quota.

**Comment by fabiand** [comment]
qcows are not handled in kubevirt.
the only input format we support is raw.

Along these lines CDI is the component which does transofrmation, thus this is something you probably want to own @aglitke

**Comment by rmohr** [comment]
> qcows are not handled in kubevirt.
> the only input format we support is raw.

We use it also in this code-base in the mentioned situations in the issue description: https://github.com/kubevirt/kubevirt/search?q=qemu-img&unscoped_q=qemu-img

**Comment by fabiand** [comment]
@aglitke any ETA?

**Comment by zvikorn** [comment]
https://github.com/kubevirt/kubevirt/pull/1664

**Comment by zvikorn** [comment]
Hi @rmohr 
I'm a bit confused while reading the code in cmd/registry-disk-v1alpha/entry_point.sh:
echo $IMAGE_NAME | grep -q -e "raw" -e "qcow2"
if [ $? -ne 0 ]; then
...
else
...
fi
What is the logic here?

if the image file suffix is either "raw" or "qcow2" we just copy the file to a new file ending with ".raw", and if not, we convert it to "raw" file? so does it mean that the original image can be vmdk and we convert it? 
But the bug/enhancement here is to validate that the file format is qcow2 before we convert it to raw.
According to the code, we do not convert qcow2 files. we convert other formats. if it's qcow2, we just copy it to a new file with raw extension.
Could you please let me know what do you think?
Thanks!

**Comment by rmohr** [comment]
@zvikorn almost. If it ends with `.raw` or `.qcow2`, it is just copied and the suffix of the file will be kept as is.  Otherwise we attempt to convert it to `.raw`.

> But the bug/enhancement here is to validate that the file format is qcow2 before we convert it to raw.

Yes you are right. I was wrong, we just take it as is. So in order do fix the security issues here, I would suggest the following:

 * let's validate that the image is not malicious by calling `qemu-img info` (what you started to do in the PR)
 * Since `qemu-img info` calls can already lead to DOS, we need to limit cpu and memory on the pod
 * If qemu-img detects a disk type which is not raw or qcow2, don't attempt a conversion.

Here is what Daniel Berrange recommended, regarding to resource limits: https://groups.google.com/d/msg/kubevirt-dev/4h7R8fPq0eU/fyL2IaiSBAAJ

What do you think?

**Comment by rmohr** [comment]
Independent of sanity checking, we also have #1565, which tries to eliminate the need the copy step too (where we want to get finally).

**Comment by rmohr** [comment]
> The only issue for me is how do you limit the cpu time and address space in bash script?

I think that you will have to limit the whole container. We already do that, if dedicated cpus are used: https://github.com/kubevirt/kubevirt/blob/master/pkg/registry-disk/registry-disk.go#L115. We just have to limit it always.

There is however a follow-up problem. The registryDisk container right now continues running, even after  it copied the file successfully. I think that we will have to do a breaking change here and change on how the registry disk container should behave (it should exit after it successfully copied the file with a 0 exit code).

Let's first fix the security part on the PR and then let's discuss on how we proceed with the container behaviour change ...

**Comment by zvikorn** [comment]
On Tue, Nov 6, 2018 at 2:32 PM Roman Mohr <notifications@github.com> wrote:

> The only issue for me is how do you limit the cpu time and address space
> in bash script?
>
> I think that you will have to limit the whole container. We already do
> that, if dedicated cpus are used:
> https://github.com/kubevirt/kubevirt/blob/master/pkg/registry-disk/registry-disk.go#L115.
> We just have to limit it always.
>
Is this done by removing 'if vmi.IsCPUDedicated() {'  ?

**Comment by rmohr** [comment]
> Is this done by removing 'if vmi.IsCPUDedicated() {' ?

Pretty much. Yes.

**Comment by rmohr** [comment]
/close

Fixed as part of #2395
