### ISSUE TITLE
Add option to disable built-in DHCP server in bridge networking mode

### ISSUE THREAD

**Issue by fanzy618** [kubevirt/kubevirt#13201]
**Is your feature request related to a problem? Please describe**:
Currently, KubeVirt's bridge networking mode includes a built-in DHCP server that cannot be disabled. This built-in DHCP server lacks IPv6 and dual-stack support, which creates limitations for users requiring IPv6 functionality in their virtual machine networking setup. In our environment, we use Kube-OVN CNI which already provides comprehensive DHCP capabilities including IPv6 support. However, we cannot leverage Kube-OVN's DHCP functionality due to potential conflicts with KubeVirt's built-in DHCP server.

**Describe the solution you'd like**:
We propose adding a configuration option that allows users to disable KubeVirt's built-in DHCP server in bridge networking mode. This could be implemented as:
1. A new configuration flag in the VMI spec (e.g., `disableBridgeDHCP: true`)
2. A global configuration option in the KubeVirt operator
This would give users the flexibility to use alternative DHCP solutions that better suit their networking requirements, such as CNI-provided DHCP servers with IPv6 support.

**Describe alternatives you've considered**:
1. Using different networking modes (such as multus), but this would require significant architecture changes in our existing setup
2. Implementing IPv6 support in KubeVirt's DHCP server, but this would be a more complex undertaking and wouldn't address the immediate need for integration with CNI-provided DHCP services

**Additional context**:
Our use case specifically involves integration with Kube-OVN (https://github.com/kubeovn/kube-ovn), which provides comprehensive DHCP capabilities including IPv6 support. This feature would enable better integration between KubeVirt and various CNI solutions that provide their own DHCP services, making KubeVirt more flexible in different networking environments.

**Comment by EdDev** [comment]
The new `managedTap` option should provide the needed functionality.

ref: https://github.com/kubevirt/community/blob/main/design-proposals/primary_network_binding_for_seamless_migration.md#as-a-bridge-domainattachmenttype

**Comment by fanzy618** [comment]
Thank you for the detailed response!
I appreciate you pointing me to the documentation. I will try it out. I'll follow up if I encounter any issues or need further clarification.

Thanks again for your help!
