### ISSUE TITLE
Hotplug disk to VM adds RestartRequired condition

### ISSUE THREAD

**Issue by mhenriks** [kubevirt/kubevirt#13222]
**What happened**:

Hotplugging a disk to a running VM via `virtctl addvolume --persist` adds `RestartRequired` condition to VM. However, restart is not necessary, so this could confuse users.

**What you expected to happen**:

`RestartRequired` condition will not be added

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

1. Create running VM
2. Hotplug volume by running `virtctl addvolume --persist`
3. Observe `RestartRequired` condition

**Additional context**:

Must be careful in implementing this fix to make sure that if a user directly edits a VM (not via virtctl) to include `hotpluggable` volumes, the condition is still added.

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by mhenriks** [comment]
cc @alicefr

**Comment by alicefr** [comment]
Interesting, this bug is hit when we don't set the workloadUpdateStrategy in kubevirt CR:
```yaml
workloadUpdateStrategy:
    workloadUpdateMethods:
    - LiveMigrate
``

**Comment by mhenriks** [comment]
> @mhenriks do we want to backport this?

Sure, I think only 1.4 is required?

**Comment by alicefr** [comment]
> > @mhenriks do we want to backport this?
> 
> Sure, I think only 1.4 is required?

1.3 as well
