### ISSUE TITLE
[tracker] Add necessary fields for performance tuning

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1327]
> As a user and operator I expect that KubeVirt allows me to tune my VMs in order to meet the performance of other KVM based hypervisors.

Requirements:

- [ ] Update requirements based on references below

References
- https://www.ovirt.org/develop/release-management/features/virt/high-performance-vm/
- https://www.ovirt.org/blog/2017/10/introducing-high-performance-vms/
- https://access.redhat.com/documentation/en-us/red_hat_virtualization/4.2/html-single/virtual_machine_management_guide/#Configuring_High_Performance_Virtual_Machines_Templates_and_Pools (paywalled)

**Comment by cynepco3hahue** [comment]
I created the list of things that we need to enable or disable:
- Enable L3 cache - what downsides this feature has, why does not enable it by default
The best performance increasement will have a VM that uses cores from the same socket
- Enable Headless Mode - we need to disable graphical and video devices
- Disable USB devices
- Disable Smart Card device - IIRC we do not have this device so nothing need to do from our side.
- Enable Virtio serial console 
- Enable CPU passthrough
- Disable memory balloon device
- Enable usage of IO threads - what downsides this feature has, why does not set it by default to 1.
- CPU pinning and NUMA pinning - currently not supported by us, but I hope in the near future we will have CPU pinning
- some additional work on a disk device - set cache to none, set io to threads
- enable virtio-rng device - we have the separate issue for it
- disable watchdog device

For the most part of things that I specified above we do not have API on the frontend side, so we can not specify it under VM preset.
@fabiand @rmohr @michalskrivanek Do we want to introduce API for each small feature or maybe do we want to introduce something similar to Ovirt VM profile to set only relevant profile and under the hood we will set all small features for the VM?

**Comment by fromanirh** [comment]
@cynepco3hahue I'm volunteering to help implementing this feature if you want

**Comment by fromanirh** [comment]
my 2c about the implementation: IMHumbleO all of the above should be hidden behind a single tunable setting (AFAIK kubevirt already has ways to do most of the relevant settings) like the ovirt vm profiles, to be later moved in the virtuned/libvirt-profiles.

**Comment by rmohr** [comment]
> Enable Headless Mode - we need to disable graphical and video devices

We can add a autoattachGraphicsDevice boolean field. Maybe starting with an annotation to gather feedback. That might be something more users care about, to save ram without going for full performance.

> Disable USB devices
> Disable Smart Card device - IIRC we do not have this device so nothing need to do from our side.
> Enable Virtio serial console
> Enable CPU passthrough
> Disable memory balloon device

Do we have that by default? We don't have ballooning right now. I would make sure it is not added by default at this moment.

> Enable usage of IO threads - what downsides this feature has, why does not set it by default to 1.
> CPU pinning and NUMA pinning - currently not supported by us, but I hope in the near future we will have CPU pinning
> some additional work on a disk device - set cache to none, set io to threads

I guess that we want to expose the cache directly? Afaik it depends on a huge amount of factors from your host if "none" is the fastest?

> enable virtio-rng device - we have the separate issue for it

Yes, we can definitely do that always as far as I remember.

> disable watchdog device

Not there by default, so not an issue.

**Comment by rmohr** [comment]
> Disable USB devices

We could do that right now and thinking about adding them the right way once we support attaching stuff to them.

> Disable Smart Card device - IIRC we do not have this device so nothing need to do from our side.
> Enable Virtio serial console

Hm, that depends on the fact if the guest supports virtio or not. Is that even important? Does having a compatible console attached slowing down the vm already?

> Enable CPU passthrough

Here I still wonder if host-model makes any sense at all and if we should not just use passthrough. According to e.g. https://wiki.openstack.org/wiki/LibvirtXMLCPUModel, it does neither guarantee a sane cpu configuration, nor migratability.

**Comment by cynepco3hahue** [comment]
@fromanirh Hi, and thanks for the proposal. IMHO I do not have much to do here, because
- @stu-gott works on IO threads
- @vladikr works on CPU pinning
- @petrkotas works on virtio-rng

So here we just need to decide what approach we prefer, to use profiles or create separate API fields for every needed feature(it more customizable than profile). Ovirt has profiles, but still, you have the API for each separate feature(except L3 cache IIRC). Also, we need to decide if we want to enable part of the features for the regular VM's as well:
- L3 cache
- IO threads 1

**Comment by fromanirh** [comment]
@cynepco3hahue ack

**Comment by cynepco3hahue** [comment]
> We can add autoattachGraphicsDevice boolean field. Maybe starting with an annotation to gather feedback. That might be something more users care about, to save ram without going for full performance.

Do you mean to use annotation instead of API field?

> Do we have that by default? We don't have ballooning right now. I would make sure it is not added by default at this moment.

Yes we have it by default, I think if you do not specify model to be `none`, libvirt set it by default to `virtio`
```
<memballoon model='virtio'>
      <alias name='balloon0'/>
      <address type='pci' domain='0x0000' bus='0x04' slot='0x00' function='0x0'/>
    </memballoon>
```

> I guess that we want to expose the cache directly? Afaik it depends on a huge amount of factors from your host if "none" is the fastest?

I checked Ovirt disk parameters(`none` means that it does not caching on the host), so it possible that it does not suite good for all cases, @aglitke maybe do you know which option is best from performance perspective, will `<driver name="qemu" type="raw" io="threads" cache="none"/>` suite well for most cases?

> Not there by default, so not an issue.

Good for us :smile: 

> We could do that right now and thinking about adding them the right way once we support attaching stuff to them.

Will create a PR to disable all not used devices.

> Hm, that depends on the fact if the guest supports virtio or not. Is that even important? Does having a compatible console attached slowing down the vm already?

@fromanirh Maybe you can answer it, I do not sure what performance impact it will have.

> Here I still wonder if host-model makes any sense at all and if we should not just use passthrough. According to e.g. https://wiki.openstack.org/wiki/LibvirtXMLCPUModel, it does neither guarantee a sane cpu configuration, nor migratability.

I think when a user does not specify host-passthrough or specific CPU model, it just means that he does not really care about CPU flags, so when libvirt will mask part of features after the migration, it also does not matter for him.
IMHO because of it `host-model` still the best option for the default value, from one side it provides a pretty good approximation to host CPU and from another side, it does not prevent migration.

**Comment by fromanirh** [comment]
> >  Hm, that depends on the fact if the guest supports virtio or not. Is that even important?
> > Does having a compatible console attached slowing down the vm already?
> @fromanirh Maybe you can answer it, I do not sure what performance impact it will have.
AFAIK the footprint in terms of CPU and memoru of a console device, either serial or virtio, is negligible, and we need it anyway to offer *a* mean to connect to the VM :)

for console devices, virtio is the default, but as rmohr pointed out, requires drivers from the guest. For Linux should be no issue, for windows we need it. For the maximum compatibility we should use the serial emulation.

**Comment by cynepco3hahue** [comment]
@fromanirh Thanks for the information, will use serial emulation.

**Comment by cynepco3hahue** [comment]
@fromanirh I see that we anyway do not use virtio console
```
    <serial type='unix'>
      <source mode='bind' path='/var/run/ovirt-vmconsole-console/40195fba-1894-4641-9033-3ac9b99287d2.sock'/>
      <target type='isa-serial' port='0'>
        <model name='isa-serial'/>
      </target>
      <alias name='serial0'/>
    </serial>
    <console type='unix'>
      <source mode='bind' path='/var/run/ovirt-vmconsole-console/40195fba-1894-4641-9033-3ac9b99287d2.sock'/>
      <target type='serial' port='0'/>
      <alias name='serial0'/>
    </console>
```
so no need to change it.

We can consider to expose two consoles one serial emulation and another one virtio serial console.

**Comment by fromanirh** [comment]
@cynepco3hahue indeed, it seems you are OK already. I think two consoles are overkill - if memory serves well we never encountered a case on which it was worth adding two, in oVirt.
IOW, I think that the "console" item is pretty much OK already, no extra work seems to be needed.

**Comment by michalskrivanek** [comment]
the only drawback of serial was that it's buggy:) for OSes where we have drivers(like Linux) we should go with virtio. For random stuff, BSD, Windows (if someone finds that useful at all) "serial" could be good enough
As for two consoles - I do not see a reason why to limit it to one at spec level really. It can be useful to define more, albeit rarely.

**Comment by cynepco3hahue** [comment]
@michalskrivanek Do you have some examples of buggy behavior, because currently all our VM's uses the serial console and I did not see any problems with it.

**Comment by fabiand** [comment]
Everything except for numa has been merged. Thus resolving this issue as DONE.

NUMA will be tracked separately.
