### ISSUE TITLE
Sanitize Network API

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1330]
Today the network API provides a lot of flexibility (connections/bindings).
This was intentional in order to allow developers and users to develop and test the networking capabilities.

At some point the flexibility should be removed in order to provide a more streamlined API.

This should probably take place before v1.

**Comment by fabiand** [comment]
@dankenigsberg how shall we proceed here?

**Comment by dankenigsberg** [comment]
@fabiand, I don't have a clear vision how a clear API should look like. IMHO, UI should be thin and clear, APIs should be powerful.

Would you lay out more details for the criteria for a clear API? Could you give examples?

**Comment by fabiand** [comment]
We plan to clean up the API for KubeVirt v1.

Please think about which things you want to eventually remove from the api
to not slip into v1.
