### ISSUE TITLE
`virtctl create vm` doesn't validate that name can be used as part of disk name

### ISSUE THREAD

**Issue by lyarwood** [kubevirt/kubevirt#13340]
/cc @0xFelix 

**What happened**:
```
$ virtctl create vm --instancetype cx1.medium --volume-containerdisk src:quay.io/containerdisks/fedora:latest --name fedora-cx1.medium  
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: null
  name: fedora-cx1.medium
spec:
  instancetype:
    name: cx1.medium
  runStrategy: Always
  template:
    metadata:
      creationTimestamp: null
    spec:
      domain:
        devices: {}
        resources: {}
      terminationGracePeriodSeconds: 180
      volumes:
      - containerDisk:
          image: quay.io/containerdisks/fedora:latest
        name: fedora-cx1.medium-containerdisk-0
status: {}
$ virtctl create vm --instancetype cx1.medium --volume-containerdisk src:quay.io/containerdisks/fedora:latest --name fedora-cx1.medium  | kubectl apply -f -
The request is invalid: spec.template.spec.domain.devices.disks.domain.devices.disks[0].name: must not contain dots
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by SWITCHin2** [comment]
@lyarwood despite adding the validation in the admiter( like `validateDiskNameAsContainerName` as the dosubot suggested), can we add a validation for vm names in the createVM() function itself?

**Comment by SWITCHin2** [comment]
@dosu what are the validation rules that can be applied for the same?

**Comment by 0xFelix** [comment]
@SWITCHin2 If you want to address this, this is the right place to add the validation:

https://github.com/kubevirt/kubevirt/blob/be188de70b4466b9f1c74de0eef37d95ed998531/pkg/virtctl/create/vm/vm.go#L522

**Comment by SWITCHin2** [comment]
Ohkay. thank you @0xFelix

**Comment by 0xFelix** [comment]
@SWITCHin2 Do you want to work on this? If so please `/assign` this issue to you.

**Comment by SWITCHin2** [comment]
@0xFelix sure, i have made changes in the code but I m unable to build it I have followed the developer guide but my build is failing for some issues, I have posted in the community but no responded, any resource where I can found resources to debug

NOTE: I m using mac

**Comment by 0xFelix** [comment]
Sorry, can't help you with Mac. @codingben might be able to give some advice.

**Comment by SWITCHin2** [comment]
No problem, hey @codingben can you help me with building the code base in mac the error I m encountering is 
`ERROR: /root/go/src/[kubevirt.io/kubevirt/BUILD.bazel:173:16](http://kubevirt.io/kubevirt/BUILD.bazel:173:16): //:passwd-image depends on @go_image_base_aarch64//image:image in repository @go_image_base_aarch64 which failed to fetch. no such package '@go_image_base_aarch64//image': Pull command failed: 2024/12/01 17:02:30 Running the Image Puller to pull images from a Docker Registry...
2024/12/01 17:02:30 Image pull was unsuccessful: reading image "[gcr.io/distroless/base-debian12@sha256:198302a46cd40ab2e24ee54d39ba0919a431e59289fd7b87f798b62e2076c62a](http://gcr.io/distroless/base-debian12@sha256:198302a46cd40ab2e24ee54d39ba0919a431e59289fd7b87f798b62e2076c62a)": /root/.docker/config.json: open /root/.docker/config.json: no such file or directory`

**Comment by codingben** [comment]
Hi @SWITCHin2, building `kubevirt/kubevirt` using MacBook arm64 never worked on my end. In other smaller projects, e.g. `kubevirt/ssp-operator`, simple commands like `go build` might work, but not here.

I'd suggest to use GitHub Codespaces, it spawns Linux VMs (amd64) that allows you to open the project, but you might run out of space to build `kubevirt/kubevirt`. Another possible option is to create DigitalOcean storage-optimized [1] and try to connect via VS Code Remote [2].

The best advice I can give you is to buy a cheap Linux laptop with enough storage that will allow you to develop open source projects like `kubevirt/kubevirt`. This is what I do as a developer and it's absolutely recommended.

[1] https://www.digitalocean.com/pricing/droplets#storage-optimized
[2] https://code.visualstudio.com/docs/remote/remote-overview

**Comment by SWITCHin2** [comment]
Thanks @codingben , this was really helpful, I will try to build it with one of the linux machine if works out well and good else will try other workarounds you have mentioned.
