### ISSUE TITLE
The virtual machine was created and the card was used, but the number of available allocations is still 1

### ISSUE THREAD

**Issue by xrwang8** [kubevirt/kubevirt#13359]
**What happened**:

I have a t4 card in my node, and a virtual machine has been started to occupy it, but the node shows that the number of allocable cards is still 1
![image](https://github.com/user-attachments/assets/b78c7ef1-693f-4d35-bc79-647a39bad094)
**What you expected to happen**:

![image](https://github.com/user-attachments/assets/0a7e290d-bf58-4df2-bc57-a19e925e5f48)

allocateable:
nvidia.com/TU104GL_TESLA T4:  0

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): 1.2
- Kubernetes version (use `kubectl version`): 1.28.1+k3s
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by iholder101** [comment]
Hey @RonaldFletcher!

It's indeed kind of confusing, but `Allocatable` does not represent the amount of resources that are free to use, but rather the amount of resources that are available to use by pods, hence are not reserved for non-Kubernetes process (i.e. system daemons).

As the docs say [[1](https://kubernetes.io/docs/tasks/administer-cluster/reserve-compute-resources/)]:
> 'Allocatable' on a Kubernetes node is defined as the amount of compute resources that are available for pods.

It's also consistent with CPU/memory. If you'll create more pods that request more memory for example, the Allocatable memory would remain the same.

**Comment by iholder101** [comment]
maybe @alaypatel07 @rthallisey would be able to help here?

**Comment by vladikr** [comment]
@RonaldFletcher Hi, is the virt-launcher pod associated with this vmi running now? can you please share its spec?
Could you please share what device plugin are you using?
