### ISSUE TITLE
vNIC model not recognized

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1337]
/bug

**What happened**:
Defined a VM with a e1000 vNIC model, see https://github.com/kubevirt/kubevirt/pull/1321/files#diff-22351c6f93523dd42005da85f6e7bf02

But the VM got a virtio model

**What you expected to happen**:
VM would get a e1000 vNIC

**How to reproduce it (as minimally and precisely as possible)**:
1. Define VM according to VM link above
2. Start VM
3. Check VMI - the vNIC model is droped, it get's a virtio

**Anything else we need to know?**:
It looks like a configuraition issue as I am usre that we have tests

**Environment**:
- KubeVirt version (use `virtctl version`): 0.7.0-alpha.2 also on 0.7.0
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by michalskrivanek** [comment]
Why do we still have/use e1000? didnt' we change it to e1000e since anyway the only chipset we support is q35?

**Comment by rmohr** [comment]
Independend from @michalskrivanek's comment if we should have e1000 at all, I could set the model on `v0.7.0` and on `master`. It was kept on the object, visible on the domain xml and was reported inside the vm.

**Comment by rmohr** [comment]
@fabiand could you do `virtctl version` and ensure that you have at least `v0.7.0` or `v0.7.0-alpha.5`? For instance `v0.7.0-alpha.2` only supports setting the model via an annotation.

**Comment by booxter** [comment]
@michalskrivanek there were some networking issues with e1000e with either cirros or alpine that I don't remember of the top of my head right now.

**Comment by fabiand** [comment]
This issue is not about the model itself.

This issue is about the ability to specify it.

**Comment by rmohr** [comment]
@fabiand in case you missed the message above, I can't reproduce your issue.

**Comment by fabiand** [comment]
But with cpu mode

**Comment by fabiand** [comment]
So, I clenaed my env and setup 0.7.0 and everything works:

```
kubectl apply     -f https://github.com/kubevirt/kubevirt/releases/download/v0.7.0/kubevirt.yaml
kubectl apply -f https://raw.githubusercontent.com/fabiand/kubevirt/0ca38184519b317500549bd84ac7dfd10e480c7c/cluster/examples/vm-windows2012r2.yaml -f https://raw.githubusercontent.com/fabiand/kubevirt/0ca38184519b317500549bd84ac7dfd10e480c7c/manifests/release/demo-content.yaml.in
virtctl start windows
kubectl get -o yaml vmi windows | grep -C3 e1000
        volumeName: pvcvolume
      interfaces:
      - bridge: {}
        model: e1000
        name: default
    features:
      acpi:
```

Not sure what went wrong.
