### ISSUE TITLE
Unable to set a cpu mode for a VM

### ISSUE THREAD

**Issue by dcritch** [kubevirt/kubevirt#1340]
**Is this a BUG REPORT or FEATURE REQUEST?**:

kind bug

**What happened**:
Attempted to set a VM to use host-passthrough for the CPU mode in the template, as per https://kubevirt.io/user-guide/#/workloads/virtual-machines/virtualized-hardware-configuration?id=mode

I can successful edit the VM template:

~~~
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachine
<...snip...>
    spec:
      domain:
        cpu: 
          mode: host-passthrough
<...snip...>
~~~
But upon starting the VM, the cpu property gets reset to {}:
~~~
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachine
<...snip...>
    spec:
      domain:
        cpu: {}
<...snip...>
~~~
**What you expected to happen**:
That the CPU property would be honoured and the VM would boot in host-passthrough mode.

**How to reproduce it (as minimally and precisely as possible)**:
Create a VM and attempt to set the CPU property to 'host-passthrough' as above.

**Anything else we need to know?**:

**Environment**:
$ virtctl version
Client Version: version.Info{GitVersion:"v0.6.2", GitCommit:"467db5c8ce17c5ca8e851809af1d890cf8dd900d", GitTreeState:"clean", BuildDate:"2018-07-18T11:24:15Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: &version.Info{GitVersion:"v0.6.2", GitCommit:"467db5c8ce17c5ca8e851809af1d890cf8dd900d", GitTreeState:"clean", BuildDate:"2018-07-06T21:23:23Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b81c8f8", GitCommit:"b81c8f8", GitTreeState:"clean", BuildDate:"2018-06-25T19:44:16Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b81c8f8", GitCommit:"b81c8f8", GitTreeState:"clean", BuildDate:"2018-07-03T22:26:30Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications:
~~~
- apiVersion: kubevirt.io/v1alpha2
  kind: VirtualMachine
  metadata:
    creationTimestamp: null
    labels:
      kubevirt-vm: ${NAME}-vm
    name: ${NAME}
  spec:
    running: true
    template:
      metadata:
        creationTimestamp: null
        labels:
          kubevirt-vm: ${NAME}-vm
      spec:
        domain:
          cpu:
            mode: host-passthrough
          devices:
            disks:
            - disk:
                bus: virtio
              name: disk0
              volumeName: ${NAME}-pvc
            - cdrom:
                bus: sata
                readonly: true
              name: cloudinitdisk
              volumeName: cloudinitvolume
          machine:
            type: q35
          resources:
            requests:
              memory: 8192Mi
        terminationGracePeriodSeconds: 0
        nodeSelector:
          kubernetes.io/hostname: computenode0.example.com
        volumes:
        - name: ${NAME}-pvc
          persistentVolumeClaim:
            claimName: ${NAME}-pvc
        - name: cloudinitvolume
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: ${PASSWORD}
              disable_root: false
              chpasswd: { expire: False }
              ssh_authorized_keys:
              - ${KEY}
~~~
- Cloud provider or hardware configuration:
Dell PowerEdge R930

- OS (e.g. from /etc/os-release):
NAME="Red Hat Enterprise Linux Server"
VERSION="7.5 (Maipo)"
ID="rhel"
ID_LIKE="fedora"
VARIANT="Server"
VARIANT_ID="server"
VERSION_ID="7.5"
PRETTY_NAME="Red Hat Enterprise Linux Server 7.5 (Maipo)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:7.5:GA:server"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 7"
REDHAT_BUGZILLA_PRODUCT_VERSION=7.5
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="7.5"

- Kernel (e.g. `uname -a`):
Linux master.example.com 3.10.0-862.el7.x86_64 #1 SMP Wed Mar 21 18:14:51 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rmohr** [comment]
@dcritch can you check if it works if you use `model` instead of `mode`?

**Comment by dcritch** [comment]
@rmohr yup, model works. I switched to Conroe to test/as per example and it was effective

**Comment by rmohr** [comment]
Ok. So it looks like the user-guide is messed up. We don't have a `mode` field right now. Just `model`. If you don't set `model` it should use `host-passthrough`. Otherwise it would use the specified `model`. @dcritch in your case you should actually not have to set anything.

**Comment by dcritch** [comment]
I don't get host-passthough, I get `<cpu mode='custom' match='exact' check='full'>` if I don't set anything

**Comment by dcritch** [comment]
Actually I don't know what I get....

In the virt-controller pod, if I do a virsh dumpxml VM, I get:
`  <cpu mode='custom' match='exact' check='full'>`
but if I cat the xml on the filesystem I get:
~~~
# cat /etc/libvirt/qemu/goldmanperf_goldman01.xml | grep 'cpu mode'
  <cpu mode='host-model' check='partial'>
~~~

**Comment by rmohr** [comment]
Opened https://github.com/kubevirt/user-guide/pull/107. This aligns what we currently have in the code with the user-guide. We don't have the `mode` field. We only have `model`. If you don't set a `model`, your host cpu will be examined and the closest matching cpu model known by qemu/libvirt will be selected, aka `host-model`.

So right now `host-passthrough` can't be selected on the API.

**Comment by dcritch** [comment]
Is selecting it in the works? I was under the impression from @fabiand that it already was there

**Comment by cynepco3hahue** [comment]
@dcritch Will push the PR today.
@fabiand @rmohr @dcritch From API perspective do we want to introduce `mode` field or adding boolean `passthrough` to CPU section can be enough?

**Comment by rmohr** [comment]
@cynepco3hahue we could also add special `model` types: `host-passthrough` and `host-model`. Not sure if we need/want extra fields for that.

**Comment by rmohr** [comment]
> @cynepco3hahue we could also add special model types: host-passthrough and host-model. Not sure if we need/want extra fields for that.

@michalskrivanek do you have some thoughts?

**Comment by cynepco3hahue** [comment]
@rmohr mm `model: host-passthrough` looks a little bit strange, but if everyone agrees I can do it this way.

**Comment by michalskrivanek** [comment]
@rmohr,
we do not need to mirror the exact libvirt syntax here. We do want to use named models, add(maybe remove/forbid, though I haven't really seen a use for it in real deployments) individual flags, and host-model, host-passthrough as special cases.
With host-(model|passthrough) it would be great to get the resulting CPU details somewhere (in status?) as that information is going to be useful(well, mandatory really) for scheduling, user display, etc.

so, I think we're good with "model: (libvirt named model|host-passthrough|host-model)", and need to figure out how to do flags (usually a list of +-flag, again maybe we're fine just with an implied "add") and how to get the result back to the user. That's all fine as a followup of course

**Comment by michalskrivanek** [comment]
oh, and also need to figure out how we want to express the secured variants. currently it's with additional flags, but it may make sense to use a separate field (secure: yes|no). I think that's the only way how to keep it user friendly/understandable and it doesn't explode in too many named types either (I like the recent "AMD EPYC IBPB SSBD" in oVirt:-D)

**Comment by rmohr** [comment]
> oh, and also need to figure out how we want to express the secured variants. currently it's with additional flags, but it may make sense to use a separate field (secure: yes|no)

I like the `secure` boolean solution.

**Comment by fabiand** [comment]
maybe it's to early to add secure?

For this specific issue I wonder if we can do an opt-in for pastshrough, as it's a pretty special case (i.e. influences migration).

`usePassthrough: true` would be something for this specific case.

Then it's also easily validateable i.e. when we get live migration.

**Comment by rmohr** [comment]
Why would it be easier validatable? You would have to check two fields then, since the model does not have any meaning and would not be allowed to be set.
