### ISSUE TITLE
Reject VMs with resources requests larger than namespace limits

### ISSUE THREAD

**Issue by vladikr** [kubevirt/kubevirt#1348]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
This is a follow up to #970, which copied namespace limits to the vm spec, so it will be visible for the users. However, we don't reject the VM spec and are letting the pod be created which later will be rejected by k8s. We could save the additional steps of the pod creation.

**What you expected to happen**:
We should find a way to reject VMs with resources requests higher than the namespace limits, before creating a pod.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@vladikr @slintes any idea why this is still open? Are we missing something?

**Comment by slintes** [comment]
@rmohr  I understand that the referenced PR is not about this issue, but about a related one, and this is a unresolved follow up? Fabian asked me to have a look a while ago, but tbh I just forgot about it while being busy with other tasks.
