### ISSUE TITLE
Uniqueness of VM "friendly-name"

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1350]
It was recently discussed that it might make sense to separate identifier and a "friendly-name" of a VM. The friendly name should be an annotation to have fewer restrictions on charset and length.

The identifier (NAME in kubernetes entities) will be used to reference the entitiy, and is the "primary key", implicitly unique.

The friendly name can not directly be used for referencing objects in the API, but it can - or should - still be unique, in order to avoid confusion.

**Comment by petrkotas** [comment]
@fabiand What is the use case for this naming? How it would be used and by whom? Thanks for the reply.

**Comment by yanirq** [comment]
The general idea was to add another annotation for user friendly name in addition to the existing vm name
for the purpose of restricting the original vm name to comply with labels/sockets/dns length restrictions in code.

The fix #1320 might be able to tackle all of  these restrictions and if accepted it will remove the need of another annotation for a friendly name.

**Comment by yanirq** [comment]
@fabiand  now that PR #1320  was merged, there is no immediate need for a user friendly VM name. 
Current VM name now behaves as pod name. 
We still hold the VM name under an annotation : `"kubevirt.io/domain"`  , which i now contemplate if its really needed.  

A side note here, with our current template form we still might have an issue when passing a long name to a template as a parameter (see https://github.com/kubevirt/kubevirt/pull/1320#issuecomment-410993580)

**Comment by fabiand** [comment]
Yes, I think it is good enough for now.
I also think that the annotation can go away.

The template issue is a separate one.
