### ISSUE TITLE
DNS lookup fail from dev cluster

### ISSUE THREAD

**Issue by yuvalif** [kubevirt/kubevirt#1358]
/kind bug

**What happened**: trying to pull a device plugin image from quay.io

**What you expected to happen**: image would be pulled

**How to reproduce it (as minimally and precisely as possible)**:
[vagrant@node01 ~]$ sudo docker pull quay.io/kubevirt/device-plugin-network-bridge:latest

**Anything else we need to know?**:

**Environment**: N/A
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@yuvalif which cluster, aka `KUBEVIRT_PROVIDER`?

**Comment by rmohr** [comment]
hm, works for me on a fresh `make cluster-up`. Are you using your notebook and wifi? I can confirm that there are sometimes, for me not yet reproducible, issues regarding to network connectivity for the vms if you put your notebook repeatedly to sleep in combination with wifi.

**Comment by yuvalif** [comment]
currently I added the image that i need under "images" directory and into the "config-defaults.sh" script. this was to workaround the issue, but also to allow caching of the image. is this an acceptable solution?
(see: https://github.com/kubevirt/kubevirt/pull/1342/files#diff-20c5ebb40cc5ceaf45efe96e7bbc1a5c from the PR)

**Comment by rmohr** [comment]
> currently I added the image that i need under "images" directory and into the "config-defaults.sh" script. this was to workaround the issue, but also to allow caching of the image. is this an acceptable solution?

Are you going to use it to test kubevirt-integration with it only, or also to test the plugin? In general adding it via `images` directory is correct. While we do have network access in the test vms, it is not meant to pull in test-relevant dependencies at test-time.

I am a little concerned about this device plugin. Is it going to be shipped as part of core-kubevirt? If yes, then I would prefer if the whole plugin would be part of virt-handler and not a separate thing, to keep things simple. I would then prefer to have more users and be more mature before providing external usable apis and start complicating our overall architecture.

**Comment by yuvalif** [comment]
This is the PR for that work is here: https://github.com/kubevirt/kubevirt/pull/1342
The plugin is not kubevirt specific - it exposes an L2 network to a pod, and can work with other applications.
Also, the kubevirt code does not need this [specific plugin](https://github.com/kubevirt/kubernetes-device-plugins/tree/master/cmd/network/bridge), any plugin that follows the env var based API, would work. 
Don't think we want to lock ourselves to a specific plugin (at least not at the current point in time).

**Comment by rmohr** [comment]
Can you confirm that you also can't reach the internet if you start a fresh cluster? If not, can you close the issue?

**Comment by yuvalif** [comment]
working after restart
