### ISSUE TITLE
Conflict between kubevirt and kubernetes types when used in third party projects

### ISSUE THREAD

**Issue by fromanirh** [kubevirt/kubevirt#1395]
/kind bug

**What happened**:
Context: I'm experimenting with an out-of-tree implementation of virt-profiles for kubevirt (see https://github.com/kubevirt/kubevirt/issues/1375), but this applies to anyone which want to use kubevirt 
types out of tree.

KubeVirt vendors the dependencies from kubernetes, most notably `api` and `apimachinery` packages. This may lead to issues when a third party tries to use the KubeVirt `api` pkg in its own code, like the following example

```
package virtprofiles

import (
	k8sv1 "k8s.io/api/core/v1"

	k6tv1 "kubevirt.io/kubevirt/pkg/api/v1"
)

func mergeDomainSpec(presetSpec *k6tv1.DomainPresetSpec, vmiSpec *k6tv1.DomainSpec) bool {
	applied := false

	if len(presetSpec.Resources.Requests) > 0 {
		if vmiSpec.Resources.Requests == nil {
			vmiSpec.Resources.Requests = k8sv1.ResourceList{}
		}

		for key, val := range presetSpec.Resources.Requests {
			current := vmiSpec.Resources.Requests[key]
			// request exceeds current setting
			if val.Cmp(current) == 1 {
				vmiSpec.Resources.Requests[key] = val
				applied = true
			}
		}
	}
	return applied
}
```

the above code fails to compile with

```
go build -v k6tpresets.go 
command-line-arguments
# command-line-arguments
./k6tpresets.go:14:31: cannot use "k8s.io/api/core/v1".ResourceList literal (type "k8s.io/api/core/v1".ResourceList) as type "kubevirt.io/kubevirt/vendor/k8s.io/api/core/v1".ResourceList in assignment
```

Turns out this kind of issues was seen before in other projects:
https://github.com/prometheus/prometheus/issues/1720

**What you expected to happen**:
Third parties should be able to use kubevirt types in their own code

**How to reproduce it (as minimally and precisely as possible)**:
See the above snippet

**Anything else we need to know?**:
Seems that vendoring stable packages is discouraged: see
https://twitter.com/fatih/status/740883554264096772
https://github.com/kubernetes/client-go/issues/83

**Comment by fromanirh** [comment]
Edited the title to reflect the issue rather than the (possible) solution

**Comment by slintes** [comment]
I think one solution is to remove nested vendor directories. If you're using glide in your project, that can be done by adding the `-v` flag to `glide up` / `glide install`.

**Comment by fromanirh** [comment]
@slintes 
> I think one solution is to remove nested vendor directories. If you're using glide in your project, 
> that can be done by adding the -v flag to glide up / glide install.

Please note I'm _not_ vendoring yet kubevirt dependencies. I'm just using them from GOPATH.
I can vendor them, so your suggestion could indeed work for me.

But does that mean that a third-party projects _needs_ to vendor kubevirt dependencies?

**Comment by rmohr** [comment]
Yes vendoring, flattening and trying to find a common working version of `apimachinery`, ... is currently the only solution for go projects which are working on k8s, as far as I know.

**Comment by fromanirh** [comment]
@rmohr ok, good to know. I'll go this way, I consider this issue closed.
