### ISSUE TITLE
"Import Virtual Machine" apb does not allow a VM name with capital letters

### ISSUE THREAD

**Issue by grafuls** [kubevirt/kubevirt#1413]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When using the "Import Virtual Machine" APB from the catalog, if the name of the VM is specified with capital letters, the "Provision PVC" task fails with:

fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["oc", "create", "-f", "/tmp/pvc.yml"], "delta": "0:00:00.434773", "end": "2018-08-07 11:35:47.418035", "msg": "non-zero return code", "rc": 1, "start": "2018-08-07 11:35:46.983262", "stderr": "The PersistentVolumeClaim \"vm-RHEL75-disk-01\" is invalid: metadata.name: Invalid value: \"vm-RHEL75-disk-01\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')", "stderr_lines": ["The PersistentVolumeClaim \"vm-RHEL75-disk-01\" is invalid: metadata.name: Invalid value: \"vm-RHEL75-disk-01\": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')"], "stdout": "", "stdout_lines": []}

**What you expected to happen**:
I expect to get a warning on the UI to use lower case or the system to lower the case automatically before the PVC provisioning.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the "Import Virtual Machine" APB wizard from the catalog and under "Virtual Machine Name" field input a name with capital letters.

**Environment**:
- KubeVirt version (use `virtctl version`): 
Client Version: version.Info{GitVersion:"v0.7.0", GitCommit:"b5b91243f540739eb5db61af89b2f1e5ba449dfa", GitTreeState:"clean", BuildDate:"2018-07-04T14:16:40Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: &version.Info{GitVersion:"v0.7.0", GitCommit:"b5b91243f540739eb5db61af89b2f1e5ba449dfa", GitTreeState:"clean", BuildDate:"2018-07-04T14:16:40Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b81c8f8", GitCommit:"b81c8f8", GitTreeState:"clean", BuildDate:"2018-07-10T22:32:34Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b81c8f8", GitCommit:"b81c8f8", GitTreeState:"clean", BuildDate:"2018-07-10T22:32:34Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}

**Comment by fabiand** [comment]
Well, it's a true error.
Isn't this error about an incorrect PVC name?

I think this is a usual Kubernetes "limitation".

**Comment by grafuls** [comment]
The PVC name is composed by the VM name and created dynamically.

from: https://github.com/ansibleplaybookbundle/import-vm-apb/blob/master/templates/windows-template.j2#L59

`claimName: vm-${NAME}-disk-01`

@fabiand I don't believe this issue should be closed.

**Comment by cynepco3hahue** [comment]
@grafuls Can you create a PVC with such name?

**Comment by nellyc** [comment]
the problem is indeed on APB/CDI side
we have a bug for the APB to do some verification on the passed vm name to avoid that

**Comment by gouyang** [comment]
It think it's a kubernetes limitation as well, easy to hit the same error via:
```
# oc process -f vm-template-fedora.yaml -p NAME=Fedora  | oc create -f -
The VirtualMachine "Fedora" is invalid: metadata.name: Invalid value: "Fedora": a DNS-1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')
```
