### ISSUE TITLE
Enable virt-preview repos via "dnf copr enable"

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#1425]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

We are referencing in our docker builder a `.repo` file at https://fedorapeople.org/groups/virt/virt-preview/ which is no longer there. As a consequence installing libvirt packages fails in the container.

**What you expected to happen**:

That we now use 

```
dnf copr enable @virtmaint-sig/virt-preview
```

**How to reproduce it (as minimally and precisely as possible)**:

Running `make` on any code before the workaround #1422 was merged (did not know back then about the copr way).

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@fabiand because of that issue that release can't succeed building: https://github.com/kubevirt/kubevirt/releases/tag/v0.8.0-alpha.0

**Comment by fabiand** [comment]
We can also use the updated url which is also named here:

https://github.com/oVirt/ovirt-release/blob/master/ovirt-f28-deps.repo.in#L11

**Comment by rmohr** [comment]
I have been told on the libvirt mailing list that all updates will land in the mentioned copr repo. So I guess using it makes sense?

**Comment by rmohr** [comment]
Fixed in #1743
