### ISSUE TITLE
Enable healthz check for KubeVirt

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt/kubevirt#1442]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:
```
[root@cnv-executor-lbednar-master1 ~]# curl -X GET -H "Authorization: Bearer $(oc whoami -t)" -k https://localhost:8443/apis/subresources.kubevirt.io/v1alpha2/healthz
unknown api endpoint /apis/subresources.kubevirt.io/v1alpha2/healthz
```

**What you expected to happen**:

```
[root@cnv-executor-lbednar-master1 ~]# curl -X GET -H "Authorization: Bearer $(oc whoami -t)" -k https://localhost:8443/apis/subresources.kubevirt.io/v1alpha2/healthz
KubeVirt is ready!
```

**How to reproduce it (as minimally and precisely as possible)**:
Deploy KubeVirt.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
```
[root@cnv-executor-lbednar-master1 ~]# virtctl version 
Client Version: version.Info{GitVersion:"v0.6.3", GitCommit:"9d48bd14f93db30a226667d809818ad44be68af7", GitTreeState:"clean", BuildDate:"2018-07-30T16:47:25Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: &version.Info{GitVersion:"v0.6.3", GitCommit:"9d48bd14f93db30a226667d809818ad44be68af7", GitTreeState:"clean", BuildDate:"2018-07-30T16:47:25Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
[root@cnv-executor-lbednar-master1 ~]# oc version 
oc v3.10.27
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://cnv-executor-lbednar-master1:8443
openshift v3.10.27
kubernetes v1.10.0+b81c8f8

- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
Fixed in #1836
