### ISSUE TITLE
RFE: Allow specifying the desired size of a vms root disk

### ISSUE THREAD

**Issue by alvaroaleman** [kubevirt/kubevirt#1444]
/kind enhancement

**What happened**:

Currently it is not possible to specify the size of a virtual machines root disk at runtime, the only way to get that done is by pre-baking different `RegistryDiskSource` images/PVCs.

**What you expected to happen**:

It would be awesome if it was possible to specify the desired size of a VMs root disk on the `RegistryDiskSource` or PVC and then just have the `virt-launcher` run a `qemu-img resize $image +$(desired_size  - actual_size)` prior to starting the VMI or error out if `desired_size < actual_size`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by aglitke** [comment]
Could you explain the use case(s) for this?

**Comment by alvaroaleman** [comment]
a) Needing a varying amount of ephemeral storage on a vm: This currently requires multiple docker images than only differ in the virtual size of the `qcow2` in them or using an `emptyDisk`, but the latter is less flexible and rather cumbersome as it has to be configured via `cloud-init`

b) Getting to the point where the size of a persistent root disk is not sufficient anymore. [PVC expansion is now beta](https://kubernetes.io/blog/2018/07/12/resizing-persistent-volumes-using-kubernetes/) so it would be cool to use that feature for a Kubevirt-managed instance.

**Comment by alvaroaleman** [comment]
> WRT a) - Could you desribe this use-case more? It sounds as if an empty disk is not enough for you (i.e. emptyDisk).

Say I have a set of physical machines on which I spawn VMs via kubevirt. I do not care too much about the individual instances so I use a `registryDisk` instead of a PVC for their root volume. I want the option to specify the virtual size of the root disk, thought.

Currently I have to do that by creating multiple `registryDisks` that only differ in the virtual size of the contained QCOW2.

This virtual size should definitely not be seeded by the size of the underlying available storage, as that is an `emptyDir` .

**Comment by alvaroaleman** [comment]
The PVC template inside the VM sounds like an awesome idea, is there some issue that tracks the progress on that? Potentially I could spend some time on it if no one is working on it yet.

I do btw not have permissions to access the linked google docs document.

**Comment by fabiand** [comment]
I don't think that there is an issue for having a registryDisk as a
template for PVCs.

**Comment by alvaroaleman** [comment]
> I don't think that there is an issue for having a registryDisk as a
template for PVCs.

Thats not what I meant, my comment was regarding the `volumeClaimTemplate` inside the `VirtualMachine` definition. But judging from the comments on that doc it seems to me that this will instead by done by defining a `DataVolume` as part of a VM spec, right?

**Comment by fabiand** [comment]
Right, thanks for clarification.

I'd not be to opposed against plain claimTemplates, as dataVolumes will
have additional dependencies (and additional features), claimTeplates would
work out of the box - thus a win as well.

**Comment by fabiand** [comment]
To be clear:

For local storage this request makes sense, we also have this with local ephemeral storage in kubernetes: https://kubernetes.io/docs/concepts/configuration/manage-compute-resources-container/#local-ephemeral-storage
