### ISSUE TITLE
RFE: Provide image-distribution mechanism

### ISSUE THREAD

**Issue by alvaroaleman** [kubevirt/kubevirt#1445]
/kind enhancement

**What happened**:

Currently, kubevirt takes a vmis rootimage either from `RegistryDisk` or from a PVC. In both cases, it is assumed that the image is already there. This means that images are not really discoverable as end user and in the case of the PVC there are even manual steps required in order to prepare it.

**What you expected to happen**:

It would be awesome if there was some image-distribution mechanism that allows for discovery of existing images and provisioning of PVCs.

**Anything else we need to know?**:

Options to implement this could e.G. be to extend the `VirtualMachineInstancePresetSpec` or to create a dedicated CRD for this. At the end of the day there should be an URL (And maybe optional parameters for auth) present somewhere and the `virt-launcher` would simply download the image from the given url if there is no image present yet.

This option would have to be mutually exclusive with `registryDisk`. Theoretically it would even be possible to use `registryDisk` as alternate source to the URL.

**Environment**:
- KubeVirt version (use `virtctl version`): `v0.7.0`

**Comment by cynepco3hahue** [comment]
It looks like `DataVolume` support that @davidvossel introduced, can you check documentation https://github.com/kubevirt/user-guide/pull/100 and say if it fits good for you use case?

**Comment by alvaroaleman** [comment]
It does not really solve the use-case and feels a little like a half-baked solution. It does not solve the problem of discoverability at all (as in: As an administrator, I want to give a set of pre-defined images to my users) and it only works when using a PV as backing store for the root disk.

It would be nice to have a generic solution for this, that works with any kind of backing store for the root disk. If there was a dedicated CRD for this it would also be possible to delegate the role of an "image-creator" by just using standard kube RBAC.

**Comment by alvaroaleman** [comment]
And just to ensure this does not come off wrong: I would like to contribute on this, but I assumed this could result in some controversy and I do not know what the process for adding new features is and if there is a way other than an issue to get design feedback prior to implementing something.

**Comment by davidvossel** [comment]
> As an administrator, I want to give a set of pre-defined images to my users) and it only works when using a PV as backing store for the root disk.

so, essentially you're asking for a CRD that represents a virtual machine image in the same way AWS has AMI objects?

**Comment by alvaroaleman** [comment]
Yes, that would be perfect

**Comment by davidvossel** [comment]
@aglitke What was the plan here? Were we going to recommend people create a separate namespace for their DataVolume immutable images?

**Comment by fabiand** [comment]
To me this sounds like some magic (incolving CDI) around DataVolumes to provide a set of disks based on definitions - aka a `FedoraImage` definition, would create a `Fedora` DataVolume for the consumption in a VMI.

**Comment by alvaroaleman** [comment]
> aka a FedoraImage definition, would create a Fedora DataVolume for the consumption in a VMI.

Yes, that is exactly what I am looking for

**Comment by fabiand** [comment]
/remove-lifecycle rotten

Alvaro, this sounds pretty much like an abstraction mechanism.
I.e. an image would abstract the volume parts - it could be a datavolume, or pv, or containerDisk?

Whereas a datavolume Image would have the provisioning capabilities. e.g:
```
kind: DiskImage
metadata:
  name: Fedora
spec:
  dataVolumeTemplate:
    metadata:
      name: fedoradv
    spec:
      pvc:
        accessModes:
        - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi
        storageClassName: local
      source:
        http:
          url: http://cdi-http-import-server.kubevirt/images/fedora.iso
```

Something like this?
