### ISSUE TITLE
virt-handler do not clean socket files from /var/run/kubevirt/sockets

### ISSUE THREAD

**Issue by cynepco3hahue** [kubevirt/kubevirt#1448]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
virt-handler does not clean socket file after VMI deletion
```
# ll /var/run/kubevirt/sockets/
total 0
srwxr-xr-x. 1 root root 0 Aug 14 11:37 69d5aac7-9fb6-11e8-acc9-525500d15501_sock
```
```
./cluster/kubectl.sh get vmis --all-namespaces
No resources found.
```

**What you expected to happen**:
`/var/run/kubevirt/sockets/` must be empty, if no VMI exist

**How to reproduce it (as minimally and precisely as possible)**:
- Create a VMI
- Delete a VMI
- Check `/var/run/kubevirt/sockets/` directory on the node where VMI ran

**Anything else we need to know?**:
The problem that when we came to cleanup phase, the VMI already does not have UUID
So from `sockFile := cmdclient.SocketFromUID(d.virtShareDir, string(vmi.GetUID()))` we get `/var/run/kubevirt/sockets/_sock` and we do not have such socket under `d.launcherClients[sockFile]`

**Environment**:
- KubeVirt version (use `virtctl version`): master

**Comment by davidvossel** [comment]
I wouldn't expect the UUID to ever be dropped. 

What's likely happening is the VMI key is getting re-enqueued after the VMI is deleted for some reason. when that occurs, there's logic to create an empty vmi to represent the deleted vmi.

```
vmi = v1.NewVMIReferenceFromNameWithNS(namespace, name)
```

that object get's passed around in the execute() function if the vmi doesn't actually exist. 

Likely all we have to do here is guarantee that the finalizer isn't removed from the VMI until we've performed cleanup.

**Comment by cynepco3hahue** [comment]
@davidvossel Thanks for the info, I missed this part where we create dummy VMI(if it does not exist), for each domain in the cache.

**Comment by cynepco3hahue** [comment]
@davidvossel But it means that `virt-handler` crashed on some stage, and was restarted because code fills it only on the start.

**Comment by cynepco3hahue** [comment]
Looks like I solved only part of the problem:
- domain exists, VMI does not exist

But we still have a case when
- domain and VMI do not exist

So I will reopen the issue.

**Comment by cynepco3hahue** [comment]
I think the issue is still relevant.
/remove-lifecycle stale
