### ISSUE TITLE
Failed to create virtual machine pod on v0.8.0-alpha.1

### ISSUE THREAD

**Issue by gouyang** [kubevirt/kubevirt#1469]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
`# oc create -f ./cluster/examples/vmi-ephemeral.yaml`
```
# oc get vmi -o yaml
....
....
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: 2018-08-22T07:57:52Z
    message: 'failed to create virtual machine pod: pods "virt-launcher-vmi-ephemeral-"
      is forbidden: unable to validate against any security context constraint: [provider
      restricted: .spec.securityContext.seLinuxOptions.level: Invalid value: "": must
      be s0:c14,c9 provider restricted: .spec.securityContext.seLinuxOptions.type:
      Invalid value: "spc_t": must be  spec.volumes[0]: Invalid value: "hostPath":
      hostPath volumes are not allowed to be used spec.containers[0].securityContext.securityContext.runAsUser:
      Invalid value: 0: must be in the ranges: [1000200000, 1000209999] spec.containers[0].securityContext.seLinuxOptions.level:
      Invalid value: "": must be s0:c14,c9 spec.containers[0].securityContext.seLinuxOptions.type:
      Invalid value: "spc_t": must be  spec.containers[1].securityContext.securityContext.runAsUser:
      Invalid value: 0: must be in the ranges: [1000200000, 1000209999] spec.containers[1].securityContext.seLinuxOptions.level:
      Invalid value: "": must be s0:c14,c9 spec.containers[1].securityContext.seLinuxOptions.type:
      Invalid value: "spc_t": must be  capabilities.add: Invalid value: "NET_ADMIN":
      capability may not be added]'
    reason: FailedCreate
    status: "False"
    type: Synchronized
  phase: Pending
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. oc create -f https://github.com/kubevirt/kubevirt/releases/download/v0.8.0-alpha.1/kubevirt.yaml
2. oc create -f ./cluster/examples/vmi-ephemeral.yaml

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by gouyang** [comment]
I'm suspecting it's an env issue, I'm retesting it.

**Comment by gouyang** [comment]
Retest hit the same error.

```
# oc version
oc v3.10.27
kubernetes v1.10.0+b81c8f8
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://cnv-executor-gouyang-master1:8443
openshift v3.10.27
kubernetes v1.10.0+b81c8f8

# virtctl version
Client Version: version.Info{GitVersion:"v0.6.3", GitCommit:"9d48bd14f93db30a226667d809818ad44be68af7", GitTreeState:"clean", BuildDate:"2018-07-30T16:47:25Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: &version.Info{GitVersion:"v0.8.0-alpha.1", GitCommit:"6136939f92c3332ca7433543e73098e4dcc7824a", GitTreeState:"clean", BuildDate:"2018-08-15T21:09:50Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by fabiand** [comment]
Hm.

Can you please check if the kubevirt-privileged service account exists?

https://github.com/kubevirt/kubevirt/blob/master/manifests/release/kubevirt.yaml.in#L276-L282

**Comment by gouyang** [comment]
The kubevirt-privileged service account is existed.
```
$ oc get serviceaccount -n kube-system kubevirt-privileged -o yaml
apiVersion: v1
imagePullSecrets:
- name: kubevirt-privileged-dockercfg-ph9cs
kind: ServiceAccount
metadata:
  creationTimestamp: 2018-08-29T02:14:25Z
  labels:
    kubevirt.io: ""
  name: kubevirt-privileged
  namespace: kube-system
  resourceVersion: "260575"
  selfLink: /api/v1/namespaces/kube-system/serviceaccounts/kubevirt-privileged
  uid: 401a7e96-ab31-11e8-9433-fa163ea5622d
secrets:
- name: kubevirt-privileged-dockercfg-ph9cs
- name: kubevirt-privileged-token-zsmw8
```

**Comment by fabiand** [comment]
This then look slike a deployment issue.

How did you deploy kubevirt?

**Comment by gouyang** [comment]
Firstly, I deploy the cluster via a d/s job which is deploying kubevirt via apb.
And then I delete the serviceinstance kubevirt which delete the RBAC as well.
Then, deploy the kubevirt 0.8.0 via `oc create -f https://github.com/kubevirt/kubevirt/releases/download/v0.8.0-alpha.1/kubevirt.yaml`.  VMI pod cannot be started.

On v0.7.0, it works even without this RBAC.

Should I close the issue now?

**Comment by fabiand** [comment]
0.8.0a1 should also contain RBAC elements, thus I am not sure where
the problem lies.

What happens if you deploy 0.8.0a1 cleanly without the 0.7 bits?

**Comment by gouyang** [comment]
Deploy the 0.8.0a1 cleanly just will hit this issue. The difference is:
On 0.8.0a1,  it need to apply `oc adm policy add-scc-to-user privileged system:serviceaccount:kube-system:kubevirt-controller`.
On 0.7.0, it does not need to apply this policy.

It should be some changes in v0.8.0a1.

**Comment by fabiand** [comment]
I see that c3198857c63436d5ec857464cdc5f4d568f63a4b did this, and recall that there was a cluster annotation to automate some parts.

@davidvossel do you recall the details?

**Comment by gouyang** [comment]
@davidvossel thanks for the explanation.

**Comment by fabiand** [comment]
I think this is a bug.
Originally the SA was granted privileged mode, because we did not look into defining the fine grained privileges.

The removal should have been accompanied by providing the fine grained policies. But not only RBAC; but also custom SCC, PodSecurityContexts and alike.

IOW this is a bug, because we dropped privileges (which is good) without providing an adequate profile to permit KubeVirt to operate.

Have we seen this issue in our CI?

**Comment by fabiand** [comment]
Raising this to critical urgent, as the deployment of KubeVirt is broken.

**Comment by rmohr** [comment]
> IOW this is a bug, because we dropped privileges (which is good) without providing an adequate profile to permit KubeVirt to operate.

That the privileges are needed is documented in the [installation guide](https://kubevirt.io/user-guide/#/installation/README?id=using-command-line-interface).
 
> Have we seen this issue in our CI?

We also set the security context when deploying kubevirt in CI.

> Raising this to critical urgent, as the deployment of KubeVirt is broken.

I agree that it is nice if we codify and include the SCC as yaml (now that this is possible in openshift), but I am surprised that this now immediately becomes a critical issue. Some SCCs had to be set before 0.8 and some still need to be set right now.

@gouyang does it work for you if you follow the installation instructions like documented in the installation guide](https://kubevirt.io/user-guide/#/installation/README?id=using-command-line-interface)?

**Comment by gouyang** [comment]
@rmohr The answer is in above comments. It work for me if run `oc adm policy add-scc-to-user privileged system:serviceaccount:kube-system:kubevirt-controller`

**Comment by fabiand** [comment]
@gouyang I think we just want to be clear that the user guide documentaiton is correct. Does it work with the command from the user-guide? (`oc adm policy add-scc-to-user privileged -n kube-system -z kubevirt-controller`)?

@rmohr critial urgent might be a bit exaggerating. However, otoh hand it was argued that privileged is to privileged, and therefor we removed it from the yamls. But you still do it manually.

Either we can do something (less privileged, still enough) automatically, then we should do it.

However, I agree that considering the guide it was no change.

**Comment by rmohr** [comment]
@gouyang great thanks. Closing this and created #1487 to track the possible enhancement.
