### ISSUE TITLE
Add test for detecting go version bump

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1470]
/kind enhancement

**What happened**:
A PR introduced a dependency on go-1.10

**What you expected to happen**:
Automation detects the bump of go-1.10 and raise flag as it's a major change

**Comment by cynepco3hahue** [comment]
We changed our containerized build to 1.10 time ago, I was never aware that we have some restrictions on go version.

**Comment by fabiand** [comment]
Switching a runtime is something notable.

To me it look slike a good habit to give head's up (like it was done in the past i.e. https://groups.google.com/d/msg/kubevirt-dev/0eKOvMxfA6w/lip_j6q0BAAJ).

This issue is about enforcing this pattern.
