### ISSUE TITLE
In openshift 3.10 it is possible to express SCCs as yaml

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#1487]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind enhancement

**What happened**:

Right now, in order to run on openshift, one first deploys `kubevirt.yaml` and then runs a few SCC updates (taken from version 0.8.0):

```
oc adm policy add-scc-to-user privileged -n kube-system -z kubevirt-privileged
oc adm policy add-scc-to-user privileged -n kube-system -z kubevirt-controller
oc adm policy add-scc-to-user privileged -n kube-system -z kubevirt-apiserver
```

**What you expected to happen**:

Depending on what comes first, we can either add the SCCs in a 3.10 `kubevirt-openshift.yaml` and let openshift users install that one, or the operator work will come first and the operator can do it. The operator itself will then also require an SCC itself.

Follow up of #1469.

**Comment by fabiand** [comment]
Do you have a link of how this can be expressed in yamls?

**Comment by rmohr** [comment]
@fabiand didn't you yourself close the PR which started expressing it as yaml a few days ago? #732
