### ISSUE TITLE
MAC address starting with reserved value 0xFE

### ISSUE THREAD

**Issue by SchSeba** [kubevirt/kubevirt#1494]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
qemu process fails to start.
Error: unsupported configuration: Unable to use MAC address starting with reserved value 0xFE

Pod interface MAC address starting with reserved value 0xFE.

**What you expected to happen**:
the vm start.

**How to reproduce it (as minimally and precisely as possible)**:
Create a vm multiple times.

**Anything else we need to know?**:
https://www.redhat.com/archives/libvirt-users/2015-April/msg00148.html

When you create a bridge device it initially has a MAC address of all zeros,
and when you add NIC devices to the bridge, its MAC address gets update to
the numerically lowest MAC address of all the NICs. The problem is that
when the kernel assigns MAC addresses randomly, one of these random MAC
address might be numerically lower than the bridge's current MAC address.
So the effect is that when you start/stop guests, and their TAP devices
get added/removed from the bridge, the bridge's own MAC address will
occassionally change which is a bad thing.

So deal with this, libvirt will set all guest TAP devices so that they
have a MAC address with 0xFE as the first byte. The real physical NIC
added to the bridge is thus guaranteed to have a smaller MAC address,
and so the bridge will permanently use the MAC address of the physical
NIC, which is what we want.

For bridges which do not have any physical NIC, libvirt will create a
dummy TAP device, not connected to any guest, and give it a small MAC
address. This ensures again ensures the bridge MAC address won't change
when guests start/stop.

**Comment by SchSeba** [comment]
@mkletzander @berrange @dankenigsberg @rmohr

**Comment by rmohr** [comment]
@SchSeba it might make sense to add that the issue is that CNI plugins may happily create MAC addresses which fall into this range (randomly generated). In order to stay connected with the provided network, in may cases we pass the mac address to the guest and remove it from tho CNI-created interface.

In that case we are not able to start the VMI because we get

```
server error. command Launcher.Sync failed: virError(Code=67, Domain=0, Message='unsupported configuration: Unable to use MAC address starting with reserved value 0xFE - 'fe:99:49:64:7c:27' - '
```

**Comment by dankenigsberg** [comment]
@SchSeba do you know who allocated the illegal MAC address? Was it a CNI plugin, or KubeVirt?

**Comment by SchSeba** [comment]
@dankenigsberg The cni plugin creates the interface and we try to take this mac address from the pod interface and give it to the vm.

**Comment by berrange** [comment]
Note also that the MAC address actually used/seen inside the VM by the guest OS must *not* be the same as the MAC address on the TAP device in the host. If they match then it can result in network errors from the kernel ""received packet on vnetX with own address as source address". So because libvirt uses 0xFE on the host TAP device, we must forbid use of 0xFE in the guest exposed MAC address. Essentially whatever MAC address is given in the XML will have its first byte toggle to 0xFE for the MAC in the host.

**Comment by dankenigsberg** [comment]
Si the bottom line is: we can delegate MAC address only from cni plugins
that would allocate valid ones, or explicit addresses.

Coincidentally, I've recently filed an rfe that would make ovn-cni be such
a plugin https://bugzilla.redhat.com/show_bug.cgi?id=1623260

Adding Petr to block fe* MACs in ovs-cni, too.

**Comment by rmohr** [comment]
> So the bottom line is: we can delegate MAC address only from cni plugins
> that would allocate valid ones, or explicit addresses.

Yes and no. For as long as we don't start hot-plugging networks, we could easily set mac addresses which are not colliding with the allocated ones on the tap device. At least if libvirt would allow us disabling the extra check and if we create the tap for libvirt.

**Comment by SchSeba** [comment]
@rmohr, @dankenigsberg  
> Yes and no. For as long as we don't start hot-plugging networks, we could easily set mac addresses which are not colliding with the allocated ones on the tap device. At least if libvirt would allow us disabling the extra check and if we create the tap for libvirt.

The problem of setting a specific mac on the vm interface and not taking it from the eth0 interface of the pod is that network plugins that implement mac filter functionality like openshift-sdn will block the vm traffic.

**Comment by rmohr** [comment]
> The problem of setting a specific mac on the vm interface and not taking it from the eth0 interface of the pod is that network plugins that implement mac filter functionality like openshift-sdn will block the vm traffic.

Agreed. Re-reading my previous message, I actually meant: We can easily set mac addresses on the tap devices which are not colliding with the ones which are provided by cni plugins.

**Comment by phoracek** [comment]
@rmohr do I understand it correctly that we need to set MAC out of this range on pod nic that is later connected to the bridge (and connects it to the outside)? If so, we have a problem: when the MAC is out of the range, it fails with `RTNETLINK answers: Cannot assign requested address`.

```
➜  ovs-cni git:(mac-range) ✗ sudo ip link add dev veth0 type veth peer name veth1
➜  ovs-cni git:(mac-range) ✗ sudo ip link set veth0 address 67:4f:16:3f:5f:0f
RTNETLINK answers: Cannot assign requested address
➜  ovs-cni git:(mac-range) ✗ sudo ip link set veth0 address fe:4f:16:3f:5f:0f
```

**Comment by dankenigsberg** [comment]
Petr, I bet your problem is the lsb of your 0x67, it means multicast.

As long as ovs-cni does not have a MAC pool, I'd ask you to choose only
locally-administered unicast addresses that doesn't start with fe.

**Comment by phoracek** [comment]
@dankenigsberg you are right, pushed a PR that should resolve the problem https://github.com/kubevirt/ovs-cni/pull/19

**Comment by woopstar** [comment]
We are seeing this issue on a kube-virt (0.11.1) deployment to a default Kubespray cluster with default calico

**Comment by dankenigsberg** [comment]
> We are seeing this issue on a kube-virt (0.11.1) deployment to a default Kubespray cluster with default calico

@woopstar, currently KubeVirt does not support setting the MAC address of the default (primary) network. It is chosen by the CNI (calico in your case) and obtained by the VM (if it has the default network connected to it). Some CNIs (e.g. OpenShift-SDN, OVN) can be very opinionated about the MAC, and would not allow traffic if it uses another address.

We solved our problem is ovs-cni. I believe that you should take this bug to calico, and that this specific bug should be closed. @phoracek, shouldn't it?

We do plan to allow setting the MAC address on the primary network for CNIs that support it, yet there is no code for this yet, and I don't know if it would work with Calico.

**Comment by crobinso** [comment]
This issue is referenced in a couple comments in kubevirt.git code. In case anyone else ends up here in the future, libvirt no longer rejects these 0xFE mac addresses since v5.7.0 released Sep 2019. kubevirt has been using libvirt 6.0.0+ since May 2020 via f3df3d1099c0c7950ce5d00b238b6963106bbc7c but I believe earlier libvirt builds had the patch backported too

* libvirt bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1743349
* libvirt commit: https://github.com/libvirt/libvirt/commit/a60ee914009aa7f1a27fc0563337ded08b09247f
