### ISSUE TITLE
running a coreos vm

### ISSUE THREAD

**Issue by karmab** [kubevirt/kubevirt#1498]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST?

> Uncomment only one, leave it on its own line:>

/kind enhancement

**What happened**:
deploy a coreos vm and try to access with a ssh public key

**What you expected to happen**:
able to access it

**How to reproduce it (as minimally and precisely as possible)**:
import a pvc with coreos production image code
create a yaml with cloudinit and ssh public key and try to access the 

FEATURE REQUEST?

**Anything else we need to know?**:
coreos uses a small subset of cloudinit but this doesnt seem to work
coreos rather uses ignition so maybe we want to implement it within libvirt as a cloud-init alternative

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by karmab** [comment]
xml extra information
--
<qemu:commandline><qemu:arg value='-fw_cfg'/><qemu:arg value='name=opt/com.coreos/config,file=/tmp/ignition'/></qemu:commandline>

**Comment by rmohr** [comment]
@karmab nothing against ignition in general, but what subset of cloud-init does it support? Does it not even   allow executing a bash-script?

**Comment by rmohr** [comment]
Also this may be helpful: https://kubevirt.io/user-guide/#/workloads/virtual-machines/startup-scripts?id=inject-ssh-key-using-a-custom-shell-script (you can also use the clear-text `userData` field instead of `userDataBase64` if you like).

**Comment by karmab** [comment]
@rmohr indeed 
- ignition doesnt directly support bash scripts, but it does support injecting files, so what i did in my tooling was to create oneshot systemd files which points to my script. maybe we could do something similar in kubevirt to give user this feature
reason for going with ignition was also because coreos-cloudinit, a fork of cloudinit, didnt work for me (neither on libvirt nor on kubevirt).

**Comment by karmab** [comment]
proposed https://github.com/kubevirt/kubevirt/pull/1657 as a fix

**Comment by SchSeba** [comment]
This is still relevant

/lifecycle rotten

**Comment by karmab** [comment]
available since 0.15.0 so closing
