### ISSUE TITLE
subresources api definition not correct

### ISSUE THREAD

**Issue by pkliczewski** [kubevirt/kubevirt#1500]
I started to experiment with openshift dynamic [client](https://github.com/openshift/openshift-restclient-python) and noticed that is failing during discovery.
`subresources.kubevirt.io/v1alpha2` endpoint  is returned when calling `https://127.0.0.1:32775/apis/` but discovery of `https://127.0.0.1:32775/apis/subresources.kubevirt.io/v1alpha2` fails due to empty response:
```json
{
  "kind": "APIResourceList",
  "apiVersion": "v1alpha2",
  "groupVersion": "subresources.kubevirt.io/v1alpha2",
  "resources": null
 }
```
Kube-apiserver is complaining about it in logs:

> I0907 14:15:29.478321       1 controller.go:105] OpenAPI AggregationController: Processing item v1alpha2.subresources.kubevirt.io
> E0907 14:15:29.480519       1 controller.go:111] loading OpenAPI spec for "v1alpha2.subresources.kubevirt.io" failed with: OpenAPI spec does not exists
> I0907 14:15:29.480544       1 controller.go:119] OpenAPI AggregationController: action for item v1alpha2.subresources.kubevirt.io: Rate Limited Requeue.

`https://127.0.0.1:32775/apis/subresources.kubevirt.io` is ok and returns correct information.

**Expected result**
Endpoint should return correct json containing resource description

**Comment by pkliczewski** [comment]
[Here](https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-api/api.go#L264) is wrong the api definition. @davidvossel your comment gives explanation why it is ok but it seems to be not correct.

**Comment by davidvossel** [comment]
> Here is wrong the api definition. @davidvossel your comment gives explanation why it is ok but it seems to be not correct.

I'm not sure what we can do about the resource list being empty. We don't want to advertise that the aggregated api endpoint serves any resources because that would conflict with our registered CRDs

**Comment by rmohr** [comment]
@pkliczewski if we would return a definition here, would we have a way to tell the client about our subresources? If not, we should really return nothing here. I would not want that we are generating CRUD operations for a non-existing object.

**Comment by pkliczewski** [comment]
@rmohr @davidvossel I pushed a PR which return empty array instead of `null`. It seems to be valid endpoint description - no description.

**Comment by davidvossel** [comment]
thanks @pkliczewski !
