### ISSUE TITLE
Replace custom controller code with Kubernetes controller-runtime library

### ISSUE THREAD

**Issue by rthallisey** [kubevirt/kubevirt#1505]
/kind enhancement

Since April, the Kubernetes community has been developing a library for controller called [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) that is being consumed by other major projects like knative, all new kubebuilder projects, and relatively soon, the operator-sdk.

KubeVirt maintains it's own controller code using informers when it can consume the [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime) library instead.  The advantage of using controller-runtime is that KubeVirt will no longer have to maintain Kubernetes controller primitives in it's code base.  This will allow for KubeVirt to get controller-runtime features and enhancements free from the community, which will significantly reduce kubevirt's controller code to only it's customizations and extensions on top of the controller-runtime interfaces.

There are some negatives:
  - Dependency on [controller-runtime](https://github.com/kubernetes-sigs/controller-runtime)
  - Moving away from the custom controller will be a major development effort in order consume a new kubernetes library. 

On the bright side, all the controllers in KubeVirt follow the same controller pattern.  So migrating the first controller to controller-runtime will be significantly harder than doing the remaining controllers who can copy paste.

KubeVirt's Controllers:
- [ ] VirtualMachineInstance
- [ ] VirtualMachineInstanceReplicasets
- [ ] VirtualMachineInstancePresets
- [ ] VirtualMachines

**Comment by cynepco3hahue** [comment]
@rthallisey Does k8s also uses it?

**Comment by rmohr** [comment]
The library looks interesting. Here a few notes:

 * It looks like it could be successful and useful for simple controllers where you are monitoring a single resource type (e.g. just Pods, just a CRD).
 * It looks right now a little bit oversimplified to allow abstractions. We had something similar in the beginning in kubevirt.
 * I never saw the k8s primitives which we use as very complicated. We are just stitching together all components provided by k8s to form our controller. I see it more as configuration-in-code than as a lot of boilerplate
 * Most complexity and boilerplate right now is in the informer callbacks. One of the main reasons is our expectation management, which I don't see addressed right now in the library.

I would give the library some time to see how complex it will become, once it will be capable of handling more challenging scenarios. If the complexity will then still be less than what we have right now with pure k8s primitives, a switch may make sense.

**Comment by rthallisey** [comment]
> @rthallisey Does k8s also uses it?
>
Currently, it's used by controllers and extensions with the goal of eventually be adopted by core k8s controllers.

**Comment by rthallisey** [comment]
/close

We can revisit at a later time.
