### ISSUE TITLE
virtctl vnc is barely usable over a slow link

### ISSUE THREAD

**Issue by karmab** [kubevirt/kubevirt#1520]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
i tried to use virtcl vnc on a relatively slow link. i never saw the console

**What you expected to happen**:
see a console

**How to reproduce it (as minimally and precisely as possible)**:
when accessing through a vpn for instance, virtcl vnc is not able to display anything

**Anything else we need to know?**:
it seems to be related to the use of a socket for the vnc connection, since the following ugly hack, which basically consists of switching live the xml definition of my vm to use a tcp port for vnc, allows  me to get the vnc console

```
NAMESPACE=$(oc project -q)
VM=$1
POD=`oc get pod -o name | grep $VM | cut -d'/' -f2`
oc exec -c compute ${POD} -i -t -- virsh qemu-monitor-command ${NAMESPACE}_${VM} --hmp "change vnc :2"
oc port-forward ${POD} 5902:5902
```

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by slintes** [comment]
Hey @karmab, just to be sure: what do you mean with "I never saw the console"? Did remote-viewer show "waiting for display 1"? If so, and if you're using Openshift CRI-O, it's fixed by https://github.com/kubevirt/kubevirt/pull/1516

**Comment by karmab** [comment]
@slintes this is indeed exactly my issue
