### ISSUE TITLE
ConfigMap (and Secret) Volume is not usable (b/c not accepted by webhook adm controller)

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1542]
/kind bug

**What happened**:
Posted and started a VM with ConfigMap disk:
```
        - configMap:
            name: app-config
          name: configmapvolume
```
This failed with:
```
default   0s        5m        25        node-1.155796da7e12852c   VirtualMachine             Warning   FailedCreate   virtualmachine-controller   Error creating virtual machine: admission webhook "virtualmachineinstances-validator.kubevirt.io" denied the request:  spec.volumes[2] must have exactly one source type set
```

**What you expected to happen**:
VM could be started.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
The webhook adm controller does probably not know about the new disk type, see: https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-api/webhooks/validating-webhook/validating-webhook.go#L219-L238

**Environment**:
- KubeVirt version (use `virtctl version`): v0.8.0
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mfranczy** [comment]
The webhook adm controller knows about the new disk type, https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-api/webhooks/validating-webhook/validating-webhook.go#L257

I am checking what's wrong...

**Comment by fabiand** [comment]
True. I wonder what I missed when I lokoed at the source.

**Comment by mfranczy** [comment]
Can you provide spec which you used? I would like to see what other volumes you had there.

**Comment by mfranczy** [comment]
Ok I see what's the problem, https://github.com/kubevirt/kubevirt/tree/release-0.8/pkg there is no config pkg which provides ```configMap``` and ```secret``` feature.

**Comment by fabiand** [comment]
Obviously!

It's not in 0.8.0.

My bad
