### ISSUE TITLE
VMI console with unprintable characters and echoing commands back to terminal

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#1547]
/kind bug

**What happened**:

virtctl console <vmi name> now results in terminal access echoing back everything I type in the terminal twice.

Example. 

```
 cluster/virtctl.sh console myvm
Successfully connected to myvm console. The escape sequence is ^]


localhost:~# ^[[47;14Recho "hi"
echo "hi"
hi
localhost:~# ^[[47;14R
```

The console shouldn't be printing back what I write twice like that. 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

create an alpine or cirros vmi. connect to the console using virtctl.

**Comment by davidvossel** [comment]
@slintes I think this might be related to the recent changes you made to fix vnc for crio.

**Comment by slintes** [comment]
yep, will have a look
