### ISSUE TITLE
/dev/kvm is sometimes not present

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#1551]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

**One** out of many tests in https://jenkins.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/2017//artifact/check-patch.k8s-1.11.0-release.el7.x86_64/mock_logs/script/stdout_stderr.log shows 

```
level=info timestamp=2018-09-26T08:05:04.025557Z pos=client.go:166 component=virt-launcher msg="Libvirt event 0 with reason 0 received"
level=error timestamp=2018-09-26T08:05:04.031602Z pos=manager.go:209 component=virt-launcher namespace=kubevirt-test-default name=testvmih5ghqf7v9ltq2tlm2whvsh7hqkpqjpprmwmslhv5wjrt5ndl kind= uid=d6e4efc4-c162-11e8-904a-525500d15501 reason="virError(Code=67, Domain=10, Message='unsupported configuration: Domain requires KVM, but it is not available. Check that virtualization is enabled in the host BIOS, and host configuration is setup to load the kvm modules.')" msg="Starting the VirtualMachineInstance failed."
level=error timestamp=2018-09-26T08:05:04.031802Z pos=server.go:68 component=virt-launcher namespace=kubevirt-test-default name=testvmih5ghqf7v9ltq2tlm2whvsh7hqkpqjpprmwmslhv5wjrt5ndl kind= uid=d6e4efc4-c162-11e8-904a-525500d15501 reason="virError(Code=67, Domain=10, Message='unsupported configuration: Domain requires KVM, but it is not available. Check that virtualization is enabled in the host BIOS, and host configuration is setup to load the kvm modules.')" msg="Failed to sync vmi"
level=info timestamp=2018-09-26T08:05:04.034210Z pos=client.go:123 component=virt-launcher msg="kubevirt domain status: Shutoff (5):Unknown (0)"
2018-09-26 08:05:04.030+0000: 30: error : qemuProcessStartValidate:4949 : unsupported configuration: Domain requires KVM, but it is not available. Check that virtualization is enabled in the host BIOS, and host configuration is setup to load the kvm modules.
level=info timestamp=2018-09-26T08:05:04.039725Z pos=client.go:161 component=virt-launcher msg="processed event"
```

so `/dev/kvm` is there in general. Looks like this is an issue on our side.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by nertpinx** [comment]
Did any sleep help? I mean in case it's a race condition, then there might be something like "sleep 1; libvirtd" that would show the problem, although it's very unlikely the case. Since there is no reproducer there's not much more we can find out about it. Any other info from the VM?
