### ISSUE TITLE
Meanigful error message when disk.img is not present on PV

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1552]
/kind enhancement

**What happened**:
A PV without a disk.img was attached to a VM.
And a libvirt error message was shown, including some praivte launcher paths.

**What you expected to happen**:
A _meaningful_ error should be show in the VM status telling that the disk.img is not present.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
We should provide a meaningful message which is also suitable for higher level UIs - i.e. "A PVC was attached, but disk.img is missing."

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@fabiand could you add the version and the message? At least master should just initialize the PV behind the scenes.

**Comment by fabiand** [comment]
Indeed. It was v0.8.0. I don#t recall the message but will provide it.

**Comment by fabiand** [comment]
Fixed with #1349
