### ISSUE TITLE
Move components to dedicated namespace

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1553]
/kind enhancement

This issue is about discussing to move the kubevirt infra components to their own namespace.
Compared to the current approach (all living in kube-system) this logical grouping of namespaced components  has a few advantages:

- Easier to identify relevant KubeVrt components
- Easier to retrieve logs from infra components (as the components are easier to identify)
- Avoiding to clobber kube-system
- Easier (to be validated) cleanup

In the past we had to stick to kube-system as certain features (pod priorities?) were hard-coded on this namespace, but this is not the case anymore.

**Comment by mlsorensen** [comment]
Previously we had been running the components (virt-api, virt-controller, virt-handler) in their own namespace by setting a namespace in "hack/config-local.sh" when generating manifests. It's possible that we simply weren't using the features that would have had a problem with this, but it seemed to work fine.

I noticed recently with 0.8.0 that I had to add some RBAC to keep this working, which indicated to me that perhaps this deployment method was not being tested, but after making the change I was still able to get the components up and create VMs.

If I'm understanding the intent, a good place to start might be to try switching to a new namespace in the tests and seeing/fixing what breaks. I might be able to find some cycles to work on this.

**Comment by rmohr** [comment]
> I noticed recently with 0.8.0 that I had to add some RBAC to keep this working

Yes we don't test it currently. I think what you saw is that our components were trying to access the kubevirt config-map which is currently hardcoded  to `kube-system`.

**Comment by fabiand** [comment]
@mlsorensen just curious: What was your reason to have KubeVirt in it's dedicated namespace?

**Comment by mlsorensen** [comment]
> @mlsorensen just curious: What was your reason to have KubeVirt in it's dedicated namespace?

We have many 'additions' to our cluster and by convention we put each in its own namespace rather than dump everything into kube-system. Just helps us track what is what and add monitors for it.

**Comment by fabiand** [comment]
Thanks for the insights, @mlsorensen

**Comment by fabiand** [comment]
#1691 was just merged a little bit to late for 0.11.

The following pre-release can be used to deploy kubevirt in the new namespace:
https://github.com/kubevirt/kubevirt/releases/tag/v0.12.0-alpha.0

**Comment by fabiand** [comment]
Fixed in #1691
