### ISSUE TITLE
Several tests fail on the k8s multus cluster

### ISSUE THREAD

**Issue by slintes** [kubevirt/kubevirt#1569]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

For every PR several tests on the k8s multus cluster fail. See e.g. http://jenkins.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/2036//artifact/check-patch.k8s-multus-1.11.1-release.el7.x86_64/mock_logs/script/stdout_stderr.log

**What you expected to happen**:

Successful tests

**How to reproduce it (as minimally and precisely as possible)**:

Create a PR

**Anything else we need to know?**:

With https://github.com/kubevirt/kubevirt/pull/1563 I confirmed that this wasn't introduced with the latest CI cluster image update

**Comment by fabiand** [comment]
@SchSeba @dankenigsberg please take a look with higher priority. As failing CI affects everybody.

**Comment by SchSeba** [comment]
I am looking into that.
