### ISSUE TITLE
VirtualMachineInstancePresets contain much more fields than are actually considered when merging

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#1584]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

The `VirtualMachineInstancePreset` contains a full `DomainSpec`, which indicates that it is possible to preset arbitrary elements. In reality it is only possible to set certain sections in the spec. The rest is simply ignored.

**What you expected to happen**:

Create a `DomainPresetSpec` which only contains structs and fields which are considered. Then step-by-step whitelist more elements if needed.

**How to reproduce it (as minimally and precisely as possible)**:

Crep a VirtualMachineInstance preset which contains a disk or a volume. It will be created, the entries stay on the CR, but it is never applied and no conflicts are reported.

**Comment by stu-gott** [comment]
While it is true that not all fields are merged, I wonder if this is just an oversight when a new field is created in the DomainSpec. Are there really any fields that specifically should not be merged?

**Comment by rmohr** [comment]
Until explicitly requested, I would for instance not allow setting the UUID in the preset.

**Comment by rmohr** [comment]
test

/lifecycle stale

**Comment by mmazur** [comment]
So… any chance for the webhook to refuse unsupported definitions?  (Or start supporting them.)

And btw, this has an interesting implication – he admission webhook does not allow not specifying spec.domain in a VMI definition. But whether that's actually correct depends heavily on what VMIPresets end up supporting:
1. If I should be able to define basically anything I want in a preset (disks, memory), then not having a spec.domain in a vmi is perfectly valid and should Just Work.
2. If for some reason e.g. disks will never work with presets (will they?), then the webhook is correct.
3. Maybe the webhook should enforce specifying an empty spec.domain to make sure the operator knows what he's doing and didn't just make a syntax error on accident.
