### ISSUE TITLE
Multiple VNC/Console

### ISSUE THREAD

**Issue by gageorsburn** [kubevirt/kubevirt#1589]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

We sometimes work with appliances that have multiple console or vnc ports. It would be nice to be able to configure multiple consoles in the vmi spec.

**Comment by fabiand** [comment]
There used to be a way to select from multiple consoles. It seems this was
lost.
