### ISSUE TITLE
[feature] enhancing "virtctl expose" to support secondary networks

### ISSUE THREAD

**Issue by yuvalif** [kubevirt/kubevirt#1601]
This [blogpost PR](https://github.com/kubevirt/kubevirt.github.io/pull/140) demonstrate how this could be done. Currently the pod selection in ```virtctl expose``` is just using the main pod network, but there could be value from automating the process described in the above blogpost.

**Comment by rmohr** [comment]
Yep could work for some case. If we have the IP of the VMI reported. We could couple it with the qemu-guest-agent which can report it.

A side-note: For manually connecting services across interfaces [externalIPs](https://kubernetes.io/docs/concepts/services-networking/service/#external-ips)- or [externalName](https://kubernetes.io/docs/concepts/services-networking/service/#externalname)-Services may be better suited. For controllers it would be better to add and remove endpoints behind the facing service, if it is expected that the dns names or ips can change.

One caveat is that we don't  know if the other networks are reachable from pods or VMIs which are not explicitly connected to the extra network (that's kind of the assumption with services pointing to external resources).

**Comment by fabiand** [comment]
I'd vote to just solve this in upstream for kubectl.
