### ISSUE TITLE
CPU count specified via spec.domain.resources.requests.cpu does not honour the value

### ISSUE THREAD

**Issue by kbidarkar** [kubevirt/kubevirt#1602]
**Is this a BUG REPORT or FEATURE REQUEST?**:  

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
Creating a VM with 2 cpus, gets created with only 1 cpu.

**What you expected to happen**:
Creation of the VM with 2 cpus, when checked vi `nproc` or `cat /proc/cpuinfo`.

**How to reproduce it (as minimally and precisely as possible)**:
When trying to create a VM with cpu-manager enabled as per the 2nd option, https://github.com/kubevirt/user-guide/blob/master/workloads/virtual-machines/dedicated-cpu.md#requesting-dedicated-cpu-resources

The below format does not result in 2 cpus.
I used this YAML format, which causes the issue.
```
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachineInstance
spec:
  domain:
    cpu:
      dedicatedCpuPlacement: true
    resources:
      limits:
        cpu: 2
        memory: 2Gi
```

**Anything else we need to know?**:
I had enabled and configured my setup with cpu-manager feature-gates.

**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.9.1", GitCommit:"93e8226fa15325a0eaea2b693de82824a8b98270", GitTreeState:"clean", BuildDate:"2018-10-05T07:01:51Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.9.1", GitCommit:"93e8226fa15325a0eaea2b693de82824a8b98270", GitTreeState:"clean", BuildDate:"2018-10-05T07:01:51Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-09-20T23:17:43Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-09-20T23:17:43Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications: VM specification.
- Cloud provider or hardware configuration: VM

- OS (e.g. from /etc/os-release):
```
oc version cat /etc/os-release 
oc v3.11.12
kubernetes v1.11.0+d4cacc0
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server https://cnv-executor-kbidarka-master1.example.com:8443
openshift v3.11.12
kubernetes v1.11.0+d4cacc0
```
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mlsorensen** [comment]
My impression was that the physical CPU count was handled by:

`spec:
    domain:
      cpu:
        cores: 2
`

While the actual resource utilization on the node (pod limit) was gated with:

`
spec:
    domain:
      resources:
        limits:
          cpu: "1"
`

In this way, one could theoretically create say an 8 CPU VM that can't really use more than 1 core worth of CPU on the host. Going the other way, one could create a 1 CPU VM, but set a 2 CPU limit for the pod, perhaps to reserve overhead for IO threads or sidecars. 

Has there been discussion that this should change or be simplified somehow?

**Comment by mlsorensen** [comment]
Ah, I see reading through the 'dedicated CPU' guide linked that this is a bug specific to trying to use the CPU Manager feature. The documentation for that feature says you can specify either domain.cpu.cores or domain.resources.limits.cpu, but not both.

As of Kubevirt 0.8.0 what I describe above still seems to be the standard behavior as I can specify both and I get the expected cpu.cores in the VM and the differing limits.cpu on the pod.

**Comment by kbidarkar** [comment]
Yes, it works fine and we can see the count as "2" via `nproc` or `cat /proc/cpuinfo`, when specifying via `domain.cpu.cores`.

**Comment by vladikr** [comment]
> Does the pod also replicate back to its limits from that, or does it simply get default pod limits?

Yes, of course. When `domain.cpu.cores` is set together with the `dedicatedCpuPlacement` we will update the pod cpu limits with this number to make the pod get the `Guaranteed` QOS level.

I have a fix for this issue as part of another PR I'm working on. I'll post it later when I'll have all the tests written.
