### ISSUE TITLE
Live Migration Progress Tracking

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#1609]
/kind enhancement

We need to be calling "jobStatus()" to periodically verify that the live migration is still making progress. This lets us detect hung migrations and it should also allow us to export metrics related to the progress of the migration.

related to #1550

**Comment by davidvossel** [comment]
from https://github.com/kubevirt/kubevirt/pull/1550#issuecomment-429360868 
> One thing I didn't see is that we are not checking the migration is actually progressing by calling jobStatus() on migrating domain. This is not important for this iteration but something we should consider for the next one.
Both vdsm[1] and nova[2] has a similar functionality to prevent the VMs from getting stuck in a migration forever.
[1] https://github.com/oVirt/vdsm/blob/master/lib/vdsm/virt/migration.py#L782
[2] https://github.com/openstack/nova/blob/master/nova/virt/libvirt/driver.py#L7279

**Comment by fabiand** [comment]
@nertpinx could libvirt actually provide some mechanism to detect hung migrations more easily?

OpenStack, oVirt and now KubeVirt is inventing stuff to detect if a migration is still going.

**Comment by nertpinx** [comment]
@fabiand Define hung migrations. From my point of view this is very difficult to grasp. Isn't keepalive enough?

**Comment by michalskrivanek** [comment]
there's not really any good solution other than keep watching the progress and implement a behavior(or set of behaviors). oVirt has couple of "policies" and watch watermark and iterations and tweak settings(we settled for downtime after all) to converge.

**Comment by nertpinx** [comment]
@fromanirh had some of that implemented in https://github.com/fromanirh/vmmi if that's what you're looking for.

**Comment by fromanirh** [comment]
@nertpinx yeah. The main metric we use for precopy is the migration iteration. We compute it manually considering the amount of (total) data migrated, IIRC libvirt should provide the counter explicitely somehow. The project you mentioned is indeed a repack + rewrite of what we have in Vdsm.

**Comment by fabiand** [comment]
Closed by #1845
