### ISSUE TITLE
glog shadow breaks transitive builds. 

### ISSUE THREAD

**Issue by senior7515** [kubevirt/kubevirt#1612]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
the glog build shadowing glog -> ../../../pkg/staging/glog//

breaks transitive builds, if they have libs that actually depend on glog. 

The whole dependency closure doesn't work. 

```
vendor/kubevirt.io/kubevirt/pkg/log/log.go:58:24: undefined: glog.LogLevel
vendor/kubevirt.io/kubevirt/pkg/log/log.go:59:24: undefined: glog.LogLevel
Makefile:39: recipe for target 'vet' failed

```

**What you expected to happen**:

For kubevirt to not shadow glog.

**How to reproduce it (as minimally and precisely as possible)**:

Copy the  cmd/example-hook-sidecar folder into an empty folder. 

copy this Gopkg.toml 

https://gist.github.com/43f0fddf5876eb26f510d16c71923ead

and try building 

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):

Latest head as of today - see Gopkg.toml for reference

**Comment by rmohr** [comment]
@senior7515 let me remove the additional public functions and fields. That should make it work again. Then we should be able to have both: Transitive builds and structured logging for kubevirt. Thanks!

**Comment by rmohr** [comment]
Keeping the issue open until @senior7515 verified that it works.

**Comment by senior7515** [comment]
verifying today. will do in a couple hours.

**Comment by senior7515** [comment]
Works! thanks!
