### ISSUE TITLE
Secure Migrations via TLS

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#1632]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind enhancement

Related to #1550 

The migration proxy used to tunnel migration connections between libvirts running in separate VMIs is not secure. We need to generate a tls CA bundle used for this migration proxy to ensure that only virt-handler's can talk to one another and that the traffic is encrypted.

**Comment by rmohr** [comment]
Assigned this to me. Have a WIP PR for other reasons which provides valid certificates to our components.
May take a few days before I can continue it. If others want to take over, happy to share the code upfront.

**Comment by rmohr** [comment]
/rmove-lifecycle rotten

Will be fixe in #2027 .
