### ISSUE TITLE
Live Migration with Network Failover

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#1633]
> /kind enhancement

Related to #1550 

Traditionally, live migrations have been accompanied by a network solution that allows the VM to migrate without disrupting guest connections.  For KubeVirt, this means determining a way to assign VMs internal  IP addresses that follow the VMs during live migration while also preserving guest connections.

cc @yuvalif @SchSeba @fabiand @vladikr @rmohr

**Comment by SchSeba** [comment]
cc @dankenigsberg also

**Comment by dankenigsberg** [comment]
In hubnly sense that this is a doomed cause. The primary network address of Pod is strongly tied to its Node (for most metwork plugins). If we provide an in-VM service listening on this address, we are unlikely to be able to keep client connections when the VMs moves to another Pod on another Node.

Thus, I believe that we can have *either* L2 network and a stable L3 address and live migration, *or* in-guest K8s address. Not both. I'd block migration for VMs that asks to bind to the K8s network.

**Comment by yuvalif** [comment]
Agree with @dankenigsberg , however, not sure we should block such migrations. If an L2 network exists, and probably used for the main function of the VM, we may still guarantee live migration on that interface, while requiring reconnects on the k8s networks (e.g. dropping ssh connections).

**Comment by fabiand** [comment]
I'm close to @yuvalif  position:

1. Any interface bound to the pod backend (regardless how) has no guarantees for live migration.
2. There should be some interface types which do support to also migrate an IP.

This issue is about 2. which can be some additional interface, but must not be the primary one.

**Comment by davidvossel** [comment]
> owever, not sure we should block such migrations.

agreed, I don't think we should block. Each interface assigned to a VM should come with expectations with regards to what happens during live migration. The user should be given the information to make the right decision based on what their internal VM workload is.

**Comment by davidvossel** [comment]
>  this is not so much about user but rather system itself. Scheduler/balancer need to be aware of the difference. If we disrupt a service on live migration it's not really the same guarantee. It still may make sense to migrate such VMs but it needs to be clear from the start (using some label?) that it won't really migrate seamlessly.

The "user" I'm referring to is someone creating VM/VMI specs for a virtualized workload, not a guest user of the VMI.

The user should be provided a set of expectations for how their VMI/VM network interfaces will perform during live migration so when they construct their VMI spec for a workload, they know it will provide the network consistency their application needs. Some applications can handle dropped connections fine, others can't. The point I was trying to make is we should leave it up to the user to make that decision when they construct the spec and not assume anything on their behalf by blocking certain configurations.

**Comment by michalskrivanek** [comment]
Not blocking it is fine, but how do you suggest the user will understand the expectations? Not the guest user, but even the user of the VMI is not always the same person as the one originally creating it or maintaining infrastructure. My point is - when you are presented with a spec how can you tell if that VM will migrate seamlessly or not.

I suppose you take the easy way out and say that the user should label it accordingly. I guess that's ok

**Comment by fabiand** [comment]
I'm not sure if such an example exists, but a condition could be one option to signal if a VM is migratable or note.
I.e.
```
kind: VM
status:
  conditions:
    - type: Migratable
      status: "True"
      lastProbeTime: null
      lastTransitionTime: 2018-01-01T00:00:00Z
```

**Comment by dankenigsberg** [comment]
@davidvossel suggests that `migratable` also depends on the in-VM application, and as such, cannot be computed by KubeVirt. We'd need a user-supplied hint about the application.

How about adding a user-contrallable `migratable` annotation? KubeVirt should set it to False if a Pod IP address is delegated to the VM. This would provide a sane default behavior, while providing the flexibility that @davidvossel is looking for.

**Comment by SchSeba** [comment]
> IMO the default interface should never block a migration. My assumption is that it just cause reconnects during migration.

We can say that all the connection makes via a k8s service will need to reconnect. (same ip on the service but the backend will be a new pod). 

I think we need to document it and let the user decide if the application allows reconnection or not.

About the default value of this parameter I am not sure. need to get some feedback from users

**Comment by fabiand** [comment]
> We can say that all the connection makes via a k8s service will need to reconnect. (same ip on the service but the backend will be a new pod).

Yes. Because that is how it also behaves for normal pod backed Services.

IOW The primary pod interface must not provide strong guarantees about an IP address or connection states, as it rather behaves like starting a new pod, which implies also getting a new IP and connections will break as well.

**Comment by davidvossel** [comment]
> How about adding a user-contrallable migratable annotation? KubeVirt should set it to False if a Pod IP address is delegated to the VM. This would provide a sane default behavior, while providing the flexibility that @davidvossel is looking for.

I agree there's value in letting the user explicitly define whether or not a VMI should be migratable or not. I don't necessarily think that's something we can accurately predict for the user based on the type of network in use.

There are more factors involved for whether or not a user wants to allow migrations outside of network configurations. For example, someone with a realtime cpu latency sensitive application may prefer for the application to perform a graceful shutdown rather than disrupt real time performance during the migration. 

My suggestion is that we opt-out of live migrations entirely by default and force the user to explicitly opt-in by toggling a boolean on the VMI's spec. The driving factor behind suggesting opt-out by default is that opting-out offers the least amount of surprise for users. In addition to this migratable toggle, our documentation should accurately reflect the behavior of each network configuration after a migration.

At that point we're giving the user creating the VMs the power and information necessary to make the right decision for their specific workload.

**Comment by dankenigsberg** [comment]
I agree that a `migratable` lever makes sense, but remember that the foremost customer of kubevirt is not the VM operator, but the cluster admin.

It should be very clear that `migratable` is just a request. Kubevirt and the cluster admin may be unable to comply (e.g host cpu is to hot, have to evacuate all workloads). A cluster admin may even charge more for non-migratable VMs since they are more picky.

Hence I disagree with you about the default value. But it's too early to argue about it.

**Comment by davidvossel** [comment]
> It should be very clear that migratable is just a request. Kubevirt and the cluster admin may be unable to comply (e.g host cpu is to hot, have to evacuate all workloads). A cluster admin may even charge more for non-migratable VMs since they are more picky.

yeah, i agree that enabling the option is just a request that comes with no guarantees. The cluster-admin is the one that would be fulfilling the migration guarantee. Setting migratable=false should offer a strict guarantee to the vm operator though. 

> Hence I disagree with you about the default value. But it's too early to argue about it.

given it's just a request for migration, are you thinking it makes more sense to make the migratable option default to true?

My thought was even though the VM operator isn't invoking the migration, if we force them to explicitly set migratable=true (with default still being false) then we can perform validation on the VM to ensure it's actually migratable before persisting the object. Essentially we'd be able to reject a VM spec with migratable=true if there's something in the spec that makes it ineligible for migration. The user would get immediate feedback that their request for migration can not be fulfilled on a technical level.

**Comment by dankenigsberg** [comment]
Regardless of the default, if the key is spelled out it should be validated as you suggest.

**Comment by michalskrivanek** [comment]
> My thought was even though the VM operator isn't invoking the migration, if we force them to explicitly set migratable=true (with default still being false) then we can perform validation on the VM to ensure it's actually migratable before persisting the object. Essentially we'd be able to reject a VM spec with migratable=true if there's something in the spec that makes it ineligible for migration. The user would get immediate feedback that their request for migration can not be fulfilled on a technical level.

makes sense, but then we're talking about potentially different aspects we want to express. One is the VMs technical capability to migrate (e.g. limited by device passthrough), user's preference based on workload, admin's decision to override user's request.
