### ISSUE TITLE
Draining nodes using Migrations

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#1634]
> /kind enhancement

Related to: #1550 

When draining a node, VMI's that are migratable should migrate instead of shutting down.

**Comment by SchSeba** [comment]
This is still an important feature 

/remove-lifecycle rotten

**Comment by fabiand** [comment]
@rmohr could you link this issue to your PR?

**Comment by rmohr** [comment]
Done.

**Comment by fabiand** [comment]
This is described here: https://github.com/kubevirt/user-guide/blob/master/administration/node-eviction.adoc
