### ISSUE TITLE
Missing required test infrastructure for tests in some external provider cases

### ISSUE THREAD

**Issue by j-griffith** [kubevirt/kubevirt#1644]
/kind enhancement

**What happened**:
When using the external provider option, we loose control of our testing environment.  In some cases a user can set things up appropriately for everything to work, but in other cases the cluster may already be deployed or it may be something like a standard GKE cluster where things can't be added/modified.

**What you expected to happen**:
When setting `KUBEVIRT_PROVIDER=external` and using a standard GKE cluster I expect to run `make cluster-up and make cluster-sync` and have my KubeVirt build deployed on my GKE cluster ready to use.

What actually happens however is that we fail cluster-sync when attempting to deploy the tests manifest.  This fails because we already created a kubevirt configmap to enable emulation mode, then the tests deploy attemtps to  create a kubevirt configmap again and fails.  Even if we changed this to patch or add to the existing configmap, we'll be missing some components expected by the functional tests.

**How to reproduce it (as minimally and precisely as possible)**:
Configure a standard GKE cluster using the latest version avaialble.
Set up a configmap to use emulation
export KUBEVIRT_PROVIDER=external
run make cluster-up && make cluster-sync

The sync will fail when attempting to deploy tests.

**Comment by rmohr** [comment]
@j-griffith could you highlight which infrastructure does not work after you patch the config-map? I don't see anything we do which would require special privileges.

**Comment by cynepco3hahue** [comment]
All our testing infrastructure must run inside containers, so it must not be related on any internal state of the cluster.

**Comment by j-griffith** [comment]
@rmohr @cynepco3hahue You're right, on GKE I have to set up a configmap to specify emulation.  The issue then is when the test deploy tries to set the configmap it fails because there's already a kubevirt configmap.  After that I ran into some issues with missing test config.

I didn't think about patching the configmap with emulation until *after* the deployment, but that seems to work well.  I'm not sure where the message I saw previously regarding "invalid test-infrastructure" came from.  Perhaps I had something else configured incorrectly.

Let me see if I can find a more correct solution to this, maybe it's not a problem after all.

By the way, here's the trace when trying to run the functests:

> Compiling tests...
    compiled tests.test
hack/functests.sh
panic: invalid configuration: no configuration has been provided

> goroutine 1 [running]:
> kubevirt.io/kubevirt/tests.PanicOnError(0x157c740, 0xc4205c03c0)
> 	/root/go/src/kubevirt.io/kubevirt/tests/utils.go:878 +0x4a
> kubevirt.io/kubevirt/tests_test.glob..func2.2.1()
> 	/root/go/src/kubevirt.io/kubevirt/tests/config_test.go:52 +0x85
> kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/suite.(*Suite).PushContainerNode(0xc4200b4370, 0x145d04a, 0x14, 0x14ec080, 0x0, 0x1d3dc4c, 0x36, 0x2d, 0xc4203a1600, 0x1e4)
> 	/root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/suite/suite.go:144 +0x16f
> kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo.Context(0x145d04a, 0x14, 0x14ec080, 0xc420369dc0)
> 	/root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:318 +0xbf
> kubevirt.io/kubevirt/tests_test.glob..func2.2()
> 	/root/go/src/kubevirt.io/kubevirt/tests/config_test.go:45 +0x42
> kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/suite.(*Suite).PushContainerNode(0xc4200b4370, 0x1461e64, 0x18, 0x14ec090, 0x0, 0x1d3dc4c, 0x36, 0x2b, 0xc4200dc2d0, 0xec)
> 	/root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/suite/suite.go:144 +0x16f
> kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo.Context(0x1461e64, 0x18, 0x14ec090, 0x0)
> 	/root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:318 +0xbf
> kubevirt.io/kubevirt/tests_test.glob..func2()
> 	/root/go/src/kubevirt.io/kubevirt/tests/config_test.go:43 +0x78
> kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/suite.(*Suite).PushContainerNode(0xc4200b4370, 0x144ac3f, 0x6, 0x14ec180, 0x0, 0x1d3dc4c, 0x36, 0x23, 0x0, 0x0)
> 	/root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/suite/suite.go:144 +0x16f
> kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo.Describe(0x144ac3f, 0x6, 0x14ec180, 0x1)
> 	/root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:289 +0xbf
> make: *** [Makefile:26: functest] Error 2

**Comment by cynepco3hahue** [comment]
@j-griffith It means that you use incorrect `kubeconfig` to run functional tests if you will check `functests.sh`  you can see that it runs with `-kubeconfig=${kubeconfig}` flag and if you do not provide `provider` env variable it will be equal to `cluster/k8s-1.10.4/.kubeconfig`. So you can just change `${kubeconfig}` under `functests.sh` to use config from your external cluster.

**Comment by rmohr** [comment]
I would suggest to set sane defaults here: https://github.com/kubevirt/kubevirt/blob/master/cluster/external/provider.sh#L12

Something like:

```
kubeconfig=${KUBECONFIG:-$HOME/.kube/config}
kubectl=kubectl
```

Then the functests should work for external providers like for all others too.

**Comment by j-griffith** [comment]
Thanks for the input on this!  So given that just patching the configmap after deploy addresses the main issue here I'm going to close this.    The provider.sh config settings get me to the next hurdle so I'll head that direction and see if we can config external/provider.sh to "just work" for functest.
