### ISSUE TITLE
No IP address in VM after pod deletion

### ISSUE THREAD

**Issue by gites** [kubevirt/kubevirt#1646]
/kind bug

**What happened**:
Pod deleted via `kubectl delete pod <name>` don't have an IP address assigned inside VM after recreation. 

**What you expected to happen**:
The pod should have an IP address

**How to reproduce it (as minimally and precisely as possible)**:
1. Create VM using official Fedora 28 or Ubuntu Bionic Cloud images.
2. Delete pod
3. Try to connect to VM via a network.

**Anything else we need to know?**:
The same behavior can be observed after running `shutdown -t now 0` inside VM.
Network connectivity can be restored by running `dhclient` inside VM.

Logs from VM start (Fedora:)
```
[  OK  ] Started Initial cloud-init job (pre-networking).
[  OK  ] Reached target Network (Pre).
         Starting LSB: Bring up/down networking...
[FAILED] Failed to start LSB: Bring up/down networking.
See 'systemctl status network.service' for details.
         Starting Initial cloud-init job (metadata service crawler)...
[  OK  ] Reached target Network.
[    6.849526] cloud-init[605]: Cloud-init v. 17.1 running 'init' at Tue, 23 Oct 2018 11:35:40 +0000. Up 6.39 seconds.
[    6.852607] cloud-init[605]: ci-info: +++++++++++++++++++++++++++Net device info++++++++++++++++++++++++++++
[    6.855608] cloud-init[605]: ci-info: +--------+-------+-----------+-----------+-------+-------------------+
[    6.858439] cloud-init[605]: ci-info: | Device |   Up  |  Address  |    Mask   | Scope |     Hw-Address    |
[    6.861914] cloud-init[605]: ci-info: +--------+-------+-----------+-----------+-------+-------------------+
[    6.865078] cloud-init[605]: ci-info: | eth0:  | False |     .     |     .     |   .   | 0a:58:0a:cc:00:c6 |
[    6.868568] cloud-init[605]: ci-info: |  lo:   |  True | 127.0.0.1 | 255.0.0.0 |   .   |         .         |
[    6.872274] cloud-init[605]: ci-info: |  lo:   |  True |     .     |     .     |   d   |         .         |
[    6.875737] cloud-init[605]: ci-info: +--------+-------+-----------+-----------+-------+-------------------+
[  OK  ] Started Initial cloud-init job (metadata service crawler).
```

```
● network.service - LSB: Bring up/down networking
   Loaded: loaded (/etc/rc.d/init.d/network; generated)
   Active: failed (Result: exit-code) since Tue 2018-10-23 11:35:40 UTC; 3min 45s ago
     Docs: man:systemd-sysv-generator(8)
  Process: 462 ExecStart=/etc/rc.d/init.d/network start (code=exited, status=1/FAILURE)

Oct 23 11:35:39 fedoravm7-f28 systemd[1]: Starting LSB: Bring up/down networking...
Oct 23 11:35:40 fedoravm7-f28 network[462]: Bringing up loopback interface:  [  OK  ]
Oct 23 11:35:40 fedoravm7-f28 network[462]: Bringing up interface eth0:  ERROR     : [/etc/sysconfig/network-scripts/ifup-eth] Device eth0 has different MAC address than expected, ignoring.
Oct 23 11:35:40 fedoravm7-f28 /etc/sysconfig/network-scripts/ifup-eth[588]: Device eth0 has different MAC address than expected, ignoring.
Oct 23 11:35:40 fedoravm7-f28 network[462]: [FAILED]
Oct 23 11:35:40 fedoravm7-f28 systemd[1]: network.service: Control process exited, code=exited status=1
Oct 23 11:35:40 fedoravm7-f28 systemd[1]: network.service: Failed with result 'exit-code'.
Oct 23 11:35:40 fedoravm7-f28 systemd[1]: Failed to start LSB: Bring up/down networking.
```

**Environment**:
- KubeVirt version (use `virtctl version`):
```Client Version: version.Info{GitVersion:"v0.9.1", GitCommit:"93e8226fa15325a0eaea2b693de82824a8b98270", GitTreeState:"clean", BuildDate:"2018-10-05T07:01:51Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.9.1", GitCommit:"93e8226fa15325a0eaea2b693de82824a8b98270", GitTreeState:"clean", BuildDate:"2018-10-05T07:01:51Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes version (use `kubectl version`):
```Client Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:53:20Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11", GitVersion:"v1.11.1", GitCommit:"b1b29978270dc22fecc592ac55d903350454310a", GitTreeState:"clean", BuildDate:"2018-07-17T18:43:26Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"linux/amd64"}
```

- VM or VMI specifications:
```
---
apiVersion: kubevirt.io/v1alpha2
kind: VirtualMachine
metadata:
  name: fedoravm7-f28
spec:
  running: true
  selector:
    matchLabels:
      guest: fedoravm7-f28
  template:
    metadata:
      labels:
        guest: fedoravm7-f28
        kubevirt.io/size: medium
    spec:
      domain:
        devices:
          disks:
            - name: fedoravm7-f28-datavolume1
              volumeName: fedoravm7-f28-datavolume1
              disk:
                bus: virtio
            - name: cloudinitdisk
              volumeName: cloudinitvolume
              disk:
                bus: virtio
      volumes:
        - dataVolume:
            name: fedoravm7-f28-datavolume1-def
          name: fedoravm7-f28-datavolume1
        - name: cloudinitvolume
          cloudInitNoCloud:
            userData: |-
              #cloud-config
              password: root
```
- Cloud provider or hardware configuration:

On prem K8s,  Intel(R) Xeon(R) CPU E5-2667 0 @ 2.90GHz, 128G RAM, 10G LAN

- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="18.04.1 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.1 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

- Kernel (e.g. `uname -a`):
```
Linux dev-wac-s1 4.15.0-30-generic #32-Ubuntu SMP Thu Jul 26 17:42:43 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:

- Others:

K8s network based on `kube-router`

**Comment by rmohr** [comment]
> K8s network based on `kube-router`

Hm, we don't test against `kube-router`. I don't know that much about this network provider, but I guess we somehow confuse it with our changes inside the pod on the provided interface.

/cc @SchSeba @yuvalif @booxter

**Comment by rmohr** [comment]
> The same behavior can be observed after running `shutdown -t now 0` inside VM.
> Network connectivity can be restored by running `dhclient` inside VM.

Oh wait, it can also be related to the OS configuration in the VM. We had similar reports where the default settings in the OS image assumed IP addresses or specific mac addresses after a first dhcp request. @karmab didn't you report something like that?

**Comment by gites** [comment]
@rmohr Indeed, the mac address is different after VM restart, and both Fedora and Ubuntu have a previous mac address specified in network settings. At that point, I'm not sure if this is still a bug.
Definitely, this kind of behavior should be described in some FAQ or documentation.

**Comment by karmab** [comment]
> > The same behavior can be observed after running `shutdown -t now 0` inside VM.
> > Network connectivity can be restored by running `dhclient` inside VM.
> 
> Oh wait, it can also be related to the OS configuration in the VM. We had similar reports where the default settings in the OS image assumed IP addresses or specific mac addresses after a first dhcp request. @karmab didn't you report something like that?

i didnt :)

**Comment by rmohr** [comment]
> Definitely, this kind of behavior should be described in some FAQ or documentation.

Sounds like a plan. I guess the most simple solution is to put  a `dhclient` call directly into the cloud-init script?

**Comment by gites** [comment]
I would rather go for creating a proper network config file. For Ubuntu it can be done like this:
```
              #cloud-config
              write_files:
              -   encoding: b64
                  content: bmV0d29yazoKICB2ZXJzaW9uOiAyCiAgZXRoZXJuZXRzOgogICAgaWQwOgogICAgICBkaGNwNDogdHJ1ZQogICAgICBtYXRjaDoKICAgICAgICBuYW1lOiBlbnAqCg==
                  owner: root:root
                  path: /etc/netplan/99-net-fix.yaml
                  permissions: '0644'
```
and that will create a netplan file `/etc/netplan/99-net-fix.yaml` with contet:
```
 network:
  version: 2
  ethernets:
    id0:
      dhcp4: true
      match:
        name: enp*
```
So on any NIC that have name starting `enp` will be counfigured via dhcp. 



IMHO, the proper fix for that should allow a user to set cloud-init meta-dataand hence for using native cloud-init network configuration options (https://cloudinit.readthedocs.io/en/latest/topics/network-config.html). Currently, meta-data are created like that: https://github.com/kubevirt/kubevirt/blob/master/pkg/cloud-init/cloud-init.go#L206

**Comment by fabiand** [comment]
IIUIC this is about a changing mac addr between boots.

But didn't we fix this by setting a mac addr during VM creation, just like we do with VM firmware uuid? @rmohr

**Comment by rmohr** [comment]
> IIUIC this is about a changing mac addr between boots.

@fabiand yes that may work. I never used kube-router so I can't tell for this provider. For instance ovn blocks the traffic if we use a custom mac, but for others (e.g. flannel) we know that it works.

**Comment by rmohr** [comment]
@gites I am a little hesitant to allow users directly modifying the meta-data. Normally (as far as I understand it) it should automatically provide the content which is needed to properly connect to the provider.

Would it make sense to pass in additional metadata in the ec2 format (https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/ec2-instance-metadata.html#instancedata-data-categories)?

Something like this:

```json
   "hostname": "ip-10-41-41-95.us-east-2.compute.internal",
   "instance-id": "i-075f088c72ad3271c",
   "local-hostname": "ip-10-41-41-95.us-east-2.compute.internal",
   "local-ipv4": "10.41.41.95",
   "mac": "06:74:8f:39:cd:a6",
   "network": {
    "interfaces": {
     "macs": {
      "06:74:8f:39:cd:a6": {
       "device-number": "0",
       "interface-id": "eni-052058bbd7831eaae",
       "local-hostname": "ip-10-41-41-95.us-east-2.compute.internal",
       "local-ipv4s": "10.41.41.95",
       "mac": "06:74:8f:39:cd:a6",
      }
     }
    }
   },
```

We would have to test which fields are exactly required to make it work for the different distributions ...

**Comment by rmohr** [comment]
What about https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v2.html#network-config-v2 and/or https://cloudinit.readthedocs.io/en/latest/topics/network-config-format-v1.html#network-config-v1 ? Maybe these can help? We can try to provide the right config for our dhcp server this way too.

**Comment by gites** [comment]
@rmohr  Sorry for answering so late. I was on holidays.
First of you need to detect what flavor of Linux user is running (not every distro supports every work-config format/version) and that can be a nightmare ;)
Second, you would force a user to have a predefined network configuration recreated on every boot. That can be bad from elasticity point of view and force users to create some kind of "hack-fixes" to have what the wanted. 

In my case, the mac address is changed after a reboot, so the problem occurs. I will test my deployment with a newer version of Kubevirt and share my findings. (currently, I'm running 0.9.1)

**Comment by fabiand** [comment]
@dankenigsberg @SchSeba @phoracek ping?

**Comment by rmohr** [comment]
@greg-bock added cloud-init metadata support in #1923, that probably solves at least half of the issue. One would still have to specify the metadata per VMI, which might not be preferable.

**Comment by SchSeba** [comment]
I think the combination of https://github.com/SchSeba/kubemacpool and @booxter PR https://github.com/kubevirt/kubevirt/pull/2115 can help here

**Comment by booxter** [comment]
@SchSeba the issue talks about IP address being different. Even if we retain MAC address, I think IP will still (potentially) change (unless CNI plugin makes MAC-to-IP mapping sticky).

**Comment by SchSeba** [comment]
Hi @booxter my comment was related to 
> On v0.10.0 the behavior is the same. After pod deletion/ vm shutdown mac address is different.

For Ip address @gites can you try to use masquerade interface it should give you the same ip inside the vm every time.
the ip address of the pod will be different but if you have a service pointing to the vm it will be updated with the new pod.
