### ISSUE TITLE
Defaulting to require vhost-net

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1661]
/kind bug

**What happened**:
Launching a VM on minikube using 0.9.2.

It failed to schedule, because `devices.kubevirt.io/vhost-net` was not available on nodes.

This is because the `vhost-net` module is not available on minikube.

The underlying issue is that wedefault to virtio, and if virtio is used, then vhost-net is expected (aka a sched requirement).

I'd recommend to keep defaulting to virtio, but have a soft requirement to need vhost-net.

Maybe using affinity, or by only requiring vhost-net if it's set as a field somewhere.

**What you expected to happen**:
The VM could start without an issue.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by vladikr** [comment]
@fabiand , perhaps this is something that the admin can disable in the config (kubevirt-config) - because this is likely to be a cluster-wide issue. I don't expect such mixed nodes...
Otherwise, how would the user specifically ask for vhost (it's not just vhost-net, it can be any vhost (blk, scsi))?
Another way is to let the user specify vhost-net instead of virtio on the interface API or introduce a driver section there.

I'd prefer to disable vhost in kubevirt-config

**Comment by fabiand** [comment]
Sounds good using the cluster wide config.

**Comment by vladikr** [comment]
> Sounds good using the cluster wide config.

@fabiand I'll get it fixed then.

**Comment by rmohr** [comment]
@vladikr well we agreed on the PR that one can set emulation in the config-map https://github.com/kubevirt/kubevirt/pull/1567#issuecomment-426320536. Basically saying that if you want to do serious virtualization it has to be present (except if you  explicitly don't want virtio on the interface). For demoing purposes it got explicitly tied to the emulation setting in the kubevirt config-map. So at least it works as expected.

**Comment by vladikr** [comment]
What are your expectations here @fabiand ?
Currently, by setting the `useEmulation` flag in the config map users can avoid using the vhost driver. (as @rmohr  mentioned above)
From my point of view, it should be sufficient.

**Comment by fabiand** [comment]
Hm.

Fair enough.

The issue is that minikube supports nesting, but has no vhost-net support.
Thus here we'd be bound to use emulation even if nesting is available.
The escape hatch is to always use something else than vhost-net.

Good enough for the moment I guess. Thus closing ti.

/close
