### ISSUE TITLE
virt-handler is consuming quite some memory

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1662]
/kind bug

**What happened**:
Running kubevirt with a VM using a PVC and ephemeral source, I see:
```
  PID USER      PR  NI    VIRT    RES  %CPU  %MEM     TIME+ S COMMAND  
…
 4407 root      20   0 1704.8m   3.3m   9.5   0.0   0:06.35 S              `- virt-handler -v 3 --port 8443 --hostname-override minikube --pod-ip-address 172.17.0.7
```
At some point it is getting killed with OOM.

**What you expected to happen**:
Runnign smoothly.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fabiand** [comment]
@rmohr I wonder why handler should consume that much memory.

**Comment by rmohr** [comment]
@fabiand which app is producing that output? `top`? Just asking so that I can really intepret it correctly.

It looks to me, like the process just uses 3.3 MB which seems to be less tan `0.1%` of the overall available memory. Maybe your node got under memory pressure. Our components still don't use the right QoS class and don't set a pod priority, so my guess would be that either k8s or the OOM killer simply evict our pods.

**Comment by itamarh** [comment]
but why would it get to 1.7GB virtual memory?

**Comment by fabiand** [comment]
Yes, it was top. And I think my snippet does not provide enough informations.

I was running a large launcher which might have brought the node under memory pressure. Which is odd, because there was still free RAM. And at some point the handler got killed.
And I agree - I even know as I saw it - that the pod was evicted. I think even without the details here, we know we should and the QoS class and priorities to the pods.

I actually thought back then that the critical pod annotation ´scheduler.alpha.kubernetes.io/critical-pod` would be sufficient. Obviously not.

**Comment by rmohr** [comment]
> Which is odd, because there was still free RAM. And at some point the handler got killed.

My guess would be that it got evicted because of disk pressure #1663 and not memory pressure. Virtual memory is not considered when evicting pods because of memory pressure.

**Comment by rmohr** [comment]
> but why would it get to 1.7GB virtual memory?

Golang does its own memory management and it works different than for usual c applications. It works a lot with thread-local storage and asks for huge memory blocks. `etcd` for instance has in our CI clusters a virtual memory size of more than 10GB. The virtual memory size of `virt-handler` is comparable with the virtual memory size of  the `kubelet`.

For as long as we don't see permanent growth in some areas (leaks), that looks normal.

**Comment by michalskrivanek** [comment]
yep, python's 30G+ virtual size on larger machines is also infamous.
3.3MB RSS looks fine. 
Close?

**Comment by fabiand** [comment]
Yes, I tend to agree that it's rather #1663
<https://github.com/kubevirt/kubevirt/issues/1663>which I was seeing.
