### ISSUE TITLE
Wrong node memory size, when windows TARGET env variable is set

### ISSUE THREAD

**Issue by ksimon1** [kubevirt/kubevirt#1677]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:

when user starts kubevirt cluster with command 
`make cluster-up`
and sets env variable:
`export TARGET="windows2016"` 
it creates node with only 4GB memory. But according to this [code](https://github.com/kubevirt/kubevirt/blob/master/cluster/ephemeral-provider-common.sh#L34), it should creates node with 8GB of memory.

**What you expected to happen**:
It should creates node with 8GB memory
**How to reproduce it (as minimally and precisely as possible)**:
set env variable:
`export TARGET="windows2016"`
make cluster-up
cluster/kubectl.sh describe nodes
see wrong memory size

**Comment by rmohr** [comment]
@ksimon1 looks like here: https://github.com/kubevirt/kubevirt/blob/master/cluster/ephemeral-provider-common.sh#L32 we set --memory two times instead of replacing it.
