### ISSUE TITLE
"ImageUpload Upload an image and start a VMI Should succeed" fails often

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1689]
/kind bug

**What happened**:
CI fails:

```
 (root).Tests Suite.Invoking jobs / check-patch.k8s-1.11.0-dev.el7.x86_64 / ImageUpload Upload an image and start a VMI Should succeed
4
2471, 2469, 2467, 2466
(root).Tests Suite.Invoking jobs / check-patch.k8s-genie-1.11.1-release.el7.x86_64 / ImageUpload Upload an image and start a VMI Should succeed
3
2471, 2469, 2467
(root).Tests Suite.Invoking jobs / check-patch.k8s-multus-1.11.1-release.el7.x86_64 / ImageUpload Upload an image and start a VMI Should succeed
3
2472, 2469, 2466
(root).Tests Suite.Invoking jobs / check-patch.openshift-3.10-crio-release.el7.x86_64 / ImageUpload Upload an image and start a VMI Should succeed
3
2471, 2469, 2467
```

https://jenkins.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/test_results_analyzer/

**What you expected to happen**:
CI completes.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mhenriks** [comment]
@fabiand @rmohr looks like we've got a lot of dups on this, see also #1659 and #1679.

**Comment by mhenriks** [comment]
making progress on this in #1682

**Comment by fabiand** [comment]
#1682 is fixing it - eventually.
