### ISSUE TITLE
"VirtualMachineInstance definition with 3 CPU cores should map cores to virtio net queues" fails

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1690]
/kind bug

**What happened**:
CI fails on:
```
 (root).Tests Suite.Invoking jobs / check-patch.k8s-multus-1.11.1-release.el7.x86_64 / Configurations VirtualMachineInstance definition with 3 CPU cores should map cores to virtio block queues
5
2472, 2471, 2469, 2467, 2466
(root).Tests Suite.Invoking jobs / check-patch.k8s-multus-1.11.1-release.el7.x86_64 / Configurations VirtualMachineInstance definition with 3 CPU cores should map cores to virtio net queues
```

https://jenkins.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/test_results_analyzer/

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by vladikr** [comment]
I'll take a look

**Comment by cynepco3hahue** [comment]
I believe this PR https://github.com/kubevirt/kubevirt/pull/1688 will fix the problem :smile:
