### ISSUE TITLE
"Migrations Starting a VirtualMachineInstance with an Alpine read only disk should be successfully migrated multiple times" fails

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1699]
/kind bug

**What happened**:
CI fails

**What you expected to happen**:
CI passes

**How to reproduce it (as minimally and precisely as possible)**:
See http://jenkins.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/2494/testReport/(root)/Tests
and https://jenkins.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/test_results_analyzer/

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fabiand** [comment]
@vladikr fyi ..

**Comment by vladikr** [comment]
@fabiand @rmohr I think that our move to libvirt 4.9.0 is what triggered this issue.
This change: https://github.com/kubevirt/kubevirt/pull/1743

Libvirt is constantly failing on the destination pod with:
`End of file while reading data: Input/output error","pos":"virNetSocketReadWire:1805`

**Comment by rmohr** [comment]
@vladikr It is unrelated to that change. We see this test failing for weeks already. The most frequent failing test actually.

**Comment by vladikr** [comment]
@rmohr You're right, that's not it.  But its something that started to happen around that time and breaks live migration.

**Comment by cynepco3hahue** [comment]
It not the only error that I can see
```
{"component":"virt-launcher","kind":"","level":"error","msg":"Live migration failed.","name":"testvmigf7rp8bjxkfzrwpgccqkfj9m5s8tfwcvcm475mbqwvrlbbff","namespace":"kubevirt-test-default","pos":"manager.go:242","reason":"virError(Code=9, Domain=10, Message='operation failed: Lost connection to destination host')","timestamp":"2018-11-27T12:55:15.661138Z","uid":"8e4dc5c6-f243-11e8-a884-525500d15501"}
{"component":"virt-launcher","level":"error","msg":"proxy unix socket listener returned error.","pos":"migration-proxy.go:313","reason":"accept tcp 127.0.0.1:22222: use of closed network connection","timestamp":"2018-11-27T12:55:15.668460Z"}
```
looks like we have some problem in the migration proxy.

**Comment by vladikr** [comment]
> looks like we have some problem in the migration proxy.

@cynepco3hahue Yea.. I think that we see that because of the destination pod exits, for some reason, and then the proxy loses the connection too.
But I'm not sure...

**Comment by cynepco3hahue** [comment]
@vladikr Can we try to increase `keepalive timeout` https://bugs.launchpad.net/ubuntu/+source/libvirt/+bug/1730051/comments/1 and to see if it will help?

**Comment by vladikr** [comment]
@cynepco3hahue Thanks, cool. I can try that.

Adding a `VIR_MIGRATE_PERSIST_DEST` flag to the migration resolve the keepalive timeouts and enables querying the metadata.

With this, the VMI migrates successfully, however, the migrationStatus doesn't chance to `completed` for some reason.

**Comment by vladikr** [comment]
After the addition of `VIR_MIGRATE_PERSIST_DEST` flag, the migration completes.
However, the test still fails, because `vmi.Status.MigrationState.Completed` isn't being set to `true` [1]

I've added some debug messages and I see that it is being set on the source virt-handler[2]
`{"component":"virt-handler","level":"info","msg":"Domain status: Shutoff, reason: Migrated\n","pos":"vm.go:673","timestamp":"2018-11-28T16:58:54.778026Z"}
...
{"component":"virt-handler","level":"info","msg":"update migration, set Completed = true","pos":"vm.go:360","timestamp":"2018-11-28T16:58:54.778768Z"}                                                            

[1] https://github.com/kubevirt/kubevirt/blob/master/tests/migration_test.go#L80
[2] https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-handler/vm.go#L348
`

**Comment by fabiand** [comment]
So the system fails to propagate this status (`completed: true`) to the
resource?

**Comment by vladikr** [comment]
@fabiand It seems that way. I've double check that the update doesn't return any errors and is being sent.

**Comment by fabiand** [comment]
Hm. Some way to check if the update lands and is eventually overwritten
again?

**Comment by vladikr** [comment]
The main issue is, as described in [1], that querying domain metadata is not allowed for non-persistent domains.
Persisting the domain on the destination with `VIR_MIGRATE_PERSIST_DEST` flag fixes the metadata issue, but also persists the metadata of the source on the destination and the destination virt-handler overwrites the `Completed` status of the migration in [2] :)
There is a way to deal with it, but this solution looks suboptimal.

The other option is not to persist the domain spec on the destination but to handle the metadata querying error and to update the domain spec. This resolves the issue. I've suggested this solution in #1733 

@rmohr previously to move away from fetching from the domain and store the metadata in the virt-launcher. This seems like the best option. One problem is that we will need to synchronize it with the virt-handler as the domain metadata is being used there as well. 

[1] https://github.com/kubevirt/kubevirt/issues/1699#issuecomment-442306318
[2] https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-handler/vm.go#L291
