### ISSUE TITLE
Windows 10 does not run out-of-the-box

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#170]
Installing Windows 10 (evaluation) on KubeVirt does not work. It hangs during boot. Or shows a kernel oops.

Some items:
- [ ] VM API needs to expose all features which windows needs to have configured
  - [ ] SMBIOS UUID
  - [x] Machine type features https://github.com/kubevirt/kubevirt/pull/606
  - [x] CPU features https://github.com/kubevirt/kubevirt/pull/606
  - [x] Clock things https://github.com/kubevirt/kubevirt/pull/606
- [ ] Optional: Presets for grouping config options https://github.com/kubevirt/kubevirt/pull/652

**Comment by rmohr** [comment]
@fabiand could you post a domain xml which works for you when using libvirt directly?

**Comment by fabiand** [comment]
The following domains allows to boot Win10 (eval):

```
<domain type='kvm'>
  <name>win10eval2</name>
  <uuid>85fb7d31-dae4-482d-889e-d35d5a91a7ba</uuid>
  <memory unit='KiB'>2097152</memory>
  <currentMemory unit='KiB'>2097152</currentMemory>
  <vcpu placement='static'>2</vcpu>
  <os>
    <type arch='x86_64' machine='pc-i440fx-2.7'>hvm</type>
    <boot dev='hd'/>
  </os>
  <features>
    <acpi/>
    <apic/>
    <vmport state='off'/>
  </features>
  <cpu mode='custom' match='exact'>
    <model fallback='allow'>Haswell</model>
  </cpu>
  <clock offset='utc'>
    <timer name='rtc' tickpolicy='catchup'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='no'/>
  </clock>
  <on_poweroff>destroy</on_poweroff>
  <on_reboot>restart</on_reboot>
  <on_crash>restart</on_crash>
  <pm>
    <suspend-to-mem enabled='no'/>
    <suspend-to-disk enabled='no'/>
  </pm>
  <devices>
    <emulator>/usr/bin/qemu-kvm</emulator>
    <disk type='file' device='disk'>
      <driver name='qemu' type='qcow2'/>
      <source file='/…/images/win10eval2.qcow2'/>
      <target dev='hda' bus='ide'/>
      <address type='drive' controller='0' bus='0' target='0' unit='0'/>
    </disk>
    <disk type='file' device='cdrom'>
      <driver name='qemu' type='raw'/>
      <source file='/…/virtio-win/virtio-win.iso'/>
      <target dev='hdb' bus='ide'/>
      <readonly/>
      <address type='drive' controller='0' bus='0' target='0' unit='1'/>
    </disk>
    <controller type='usb' index='0' model='ich9-ehci1'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x7'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci1'>
      <master startport='0'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0' multifunction='on'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci2'>
      <master startport='2'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x1'/>
    </controller>
    <controller type='usb' index='0' model='ich9-uhci3'>
      <master startport='4'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x2'/>
    </controller>
    <controller type='pci' index='0' model='pci-root'/>
    <controller type='ide' index='0'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x1'/>
    </controller>
    <controller type='virtio-serial' index='0'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x04' function='0x0'/>
    </controller>
    <interface type='user'>
      <mac address='52:54:00:f8:7d:26'/>
      <model type='rtl8139'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
    </interface>
    <serial type='pty'>
      <target port='0'/>
    </serial>
    <console type='pty'>
      <target type='serial' port='0'/>
    </console>
    <channel type='spicevmc'>
      <target type='virtio' name='com.redhat.spice.0'/>
      <address type='virtio-serial' controller='0' bus='0' port='1'/>
    </channel>
    <input type='mouse' bus='ps2'/>
    <input type='keyboard' bus='ps2'/>
    <graphics type='spice' autoport='yes'>
      <listen type='address'/>
      <image compression='off'/>
    </graphics>
    <video>
      <model type='qxl' ram='65536' vram='65536' vgamem='16384' heads='1' primary='yes'/>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x02' function='0x0'/>
    </video>
    <redirdev bus='usb' type='spicevmc'>
      <address type='usb' bus='0' port='1'/>
    </redirdev>
    <redirdev bus='usb' type='spicevmc'>
      <address type='usb' bus='0' port='2'/>
    </redirdev>
    <memballoon model='virtio'>
      <address type='pci' domain='0x0000' bus='0x00' slot='0x06' function='0x0'/>
    </memballoon>
  </devices>
</domain>
```

**Comment by fabiand** [comment]
@admiyo once your mapping work is done, then it probably makes sense to have a testcase for such a domxml.

**Comment by mpolednik** [comment]
@fabiand 
Why emulated (IDE) disk?
What about apic? hyperv features? vmport?
Emulated nic?
As for the USB, it makes sense to use piix3-uhci due to virtualization compatibility.

We should try to test virtualization friendly domains, not heavily emulated ones (unless we're aiming for full emulation test).

**Comment by michalskrivanek** [comment]
@fabiand - this is a task for the GUI/backend to come up with the right xml. I suppose you created it in virt-manager, then it's kind of on you to get it right

**Comment by fabiand** [comment]
@mpolednik :) It was just the stock domain I created using virt-manager.

@michalskrivanek yes, it is the resposibility of the UI to come up with the correct XML.

The purpose of this ticket is that even this domain xml above, regardless how good it is, can be used with libvirtd but not with kubevirt to lanuch a VM, because KubeVirt is missing support for some fields.

**Comment by michalskrivanek** [comment]
@fabiand - which fields? I mean...you didn't use any specific kubevirt GUI but a relatively low-level tool, either way the XML does support and contain whatever is needed to run Windows 10, then what's actually the gap?

I mean, sure, the VM spec is not complete, but I guess that is known and needs a _proper_ general solution anyway

**Comment by fabiand** [comment]
The gap is that KubeVirt did not map the whole VM spec to the domxml used on the host to launch the domain.

The VM Spec does not automatically translate 1:1 to a domxml, instead there are mappings for each element.
The assumption for thelong run is actually that the VM Spec will be similar to the domxml, but will hide some but add additional fields.

**Comment by michalskrivanek** [comment]
ack on first part.

so, to me this sounds more like an argument for 1:1 domxml;-) I mean feature wise. Why do you expect to hide additional fields? In GUI, sure, but at backend logic there is not much to hide.

**Comment by rmohr** [comment]
> so, to me this sounds more like an argument for 1:1 domxml;-) I mean feature wise. Why do you expect to hide additional fields? In GUI, sure, but at backend logic there is not much to hide.

I assume that it is probably more about "disabling" than hiding. Not all features make sense when a VM runs in kubevirt. For instance spice has to be wired up in a special way, whenever you start messing around with that, it will not work, so disabling all fields which you are not allowed to set makes sense ...

**Comment by michalskrivanek** [comment]
@rmohr, hm, but why, actually. I think(just think, I didn't look at it deeply) that your current issues with SPICE is just a result of not doing things the right way if you're speaking about migration.
Not sure what other features wouldn't work _and_ at the same time we wouldn't want it to ever work _and_ it wouldn't be taken care of by a UI/backend logic

Sure, there are things kubevirt would never use simply because it's not interesting(even though you can argue eventually someone somewhere will eventually use them) but that's typically about certain sub-options and specific settings, all the "feature" level stuff is eventually useful. Hence my expectation is it's better to go for 1:1 rather than creating something what looks simple initially, but evolves into 90%+ similarity over time

**Comment by rmohr** [comment]
@michalskrivanek, we have no issues with spice afaik. You either have to set the spice IP to 0.0.0.0 or the pod IP. There are no other choices which will work, since the VM runs in the network namespace of the pod (which is intended).

We are going for 1:1, but if it clearly does not work we will not have it. But I agree that almost everything will work.

**Comment by michalskrivanek** [comment]
cool
@rmohr, it might be better to use pod IP since then the lower layers are aware of it, most importantly the port, and then there is no need to do anything elsewhere. 
Though...I guess this would need some RFEs here and there to make it simple

**Comment by rmohr** [comment]
@fabiand, sent the xml through the converter from #189, to allow easy diffing:

```xml
<domain type="kvm">
  <name>win10eval2</name>
  <uuid>85fb7d31-dae4-482d-889e-d35d5a91a7ba</uuid>
  <memory unit="KiB">2097152</memory>
  <os>
    <type arch="x86_64" machine="pc-i440fx-2.7">hvm</type>
    <boot dev="hd"></boot>
  </os>
  <devices>
    <emulator>/usr/bin/qemu-kvm</emulator>
    <interface type="user">
      <address type="pci" domain="0x0000" bus="0x00" slot="0x03" function="0x0"></address>
      <source></source>
      <model type="rtl8139"></model>
      <mac address="52:54:00:f8:7d:26"></mac>
    </interface>
    <channel type="spicevmc">
      <source mode="" path=""></source>
      <target name="com.redhat.spice.0" type="virtio"></target>
    </channel>
    <video>
      <model type="qxl" heads="1" ram="65536" vram="65536" vgamem="16384"></model>
    </video>
    <graphics type="spice">
      <listen type="address"></listen>
    </graphics>
    <memballoon model="virtio"></memballoon>
    <disk device="disk" type="file">
      <source file="/…/images/win10eval2.qcow2"></source>
      <target bus="ide" dev="hda"></target>
      <driver name="qemu" type="qcow2"></driver>
    </disk>
    <disk device="cdrom" type="file">
      <source file="/…/virtio-win/virtio-win.iso"></source>
      <target bus="ide" dev="hdb"></target>
      <driver name="qemu" type="raw"></driver>
    </disk>
    <serial type="pty">
      <target port="0"></target>
    </serial>
    <console type="pty">
      <target type="serial" port="0"></target>
    </console>
  </devices>
</domain>
```

**Comment by fabiand** [comment]
Really nice, @rmohr iiuic this should show us the unmapped fields?

**Comment by fabiand** [comment]
This issue has several sides. At the lowest level it is about the ability to create the correct domxml.
Issue #244 goes into the direction of adding support for more fields to the VM spec.

Then it is that we probably do not want to specify this specific domxml (or rather vm spec) whenever we create a windows vm, we'd rather like to tell the system, that this specific vm should get the defaults which atre compatible with Windows.
The issues #281 and #287 go into this direction.

**Comment by rmohr** [comment]
We now support 

```
  <features>
    <acpi/>
    <apic/>
  </features>
  <cpu mode='custom' match='exact'>
    <model fallback='allow'>Haswell</model>
  </cpu>
  <clock offset='utc'>
    <timer name='rtc' tickpolicy='catchup'/>
    <timer name='pit' tickpolicy='delay'/>
    <timer name='hpet' present='no'/>
  </clock>
```

I wonder if we still miss anything for basic win 10 support.

**Comment by michalskrivanek** [comment]
@rmohr do we have the <hyperv> stuff (e.g. from http://blog.wikichoon.com/2014/07/enabling-hyper-v-enlightenments-with-kvm.html) ?

**Comment by mykaul** [comment]
<hyperv>
    <relaxed state='on'/>
    <vapic state='on'/>
    <spinlocks state='on' retries='4096'/>
    <vpindex state='on'/>
    <runtime state='on'/>
    <synic state='on'/>
    <reset state='on'/>
    <vendor_id state='on' value='KVM Hv'/>
  </hyperv>

**Comment by michalskrivanek** [comment]
ah we do, sorry:) yeah, that should be it!

**Comment by rmohr** [comment]
> ah we do, sorry:) yeah, that should be it!

Yes they are :) https://github.com/kubevirt/kubevirt/blob/master/cluster/windows-demo.yaml

**Comment by rmohr** [comment]
Here the full list: https://kubevirt-incubator.github.io/api-reference/content/definitions.html#_v1_featurehyperv

**Comment by michalskrivanek** [comment]
@rmohr awesome! that's a level of detail wasn't even hoping for! :-)))

**Comment by xsgordon** [comment]
@fabiand @rmohr 

This is great, but I'd like to add an additional foible since this is still open. In the current example we expose all of the knobs from the Libvirt XML directly to the user in the YAML. This will be fine for a management application like oVirt or OpenStack trying to use KubeVirt, but for a user interacting with KubeVirt directly it's potentially a little too granular.

Would it be possible to allow for an alternative where the user simply specifies the OS variant (e.g libosinfo style) and we set the options appropriately for them based on that?

**Comment by fabiand** [comment]
@xsgordon Yep - That's the role of VirtualMachinePresets: A mechanism to group common VM ABI configurations and apply them to VMs, see this draft user guide chapter: https://github.com/kubevirt/user-guide/pull/11

**Comment by xsgordon** [comment]
@fabiand gotcha, thanks.

**Comment by simon3z** [comment]
@fabiand is this addressed? Should we close it?

**Comment by fabiand** [comment]
This is actually now addressed by using the provided presets.
