### ISSUE TITLE
" Templates Creating VM from Template with RHEL Template when the VirtualMachine was created should succeed to start the VirtualMachine via oc command" fails

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1700]
/kind bug

**What happened**:
CI fails

**What you expected to happen**:
CI passes

**How to reproduce it (as minimally and precisely as possible)**:
http://jenkins.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/2494/testReport/(root)/Tests
and https://jenkins.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/test_results_analyzer/

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fabiand** [comment]
@gszasz thoughts?

**Comment by gszasz** [comment]
```
{ [{PodScheduled False 0001-01-01 00:00:00 +0000 UTC 2018-11-21 23:45:24 +0000 UTC Unschedulable 0/2 nodes are available: 1 Insufficient memory, 1 node(s) didn't find available persistent volumes to bind.}] Scheduling [] <nil>}}
```

It seems that the PV with an RHEL image is either not created, or does not have proper label. I've checked contents of the `automation/test.sh` where PV is being created, as well as the code in `tests/utils.go` that creates complementary PVC. Everything seems to be okay.

**Comment by fabiand** [comment]
Thus what is the root cause for this problem?

**Comment by fabiand** [comment]
ping?

**Comment by gszasz** [comment]
@fabiand I need access to the CI environment to figure out why the PV is not available at the time of test execution. @gbenhaim could keep the environment running, and he can give me an access, but I do not see him online yet.

**Comment by fabiand** [comment]
Are you able to reproduce this issue locally

**Comment by cynepco3hahue** [comment]
This one already fixed.
