### ISSUE TITLE
"DataVolume Integration Starting a VirtualMachineInstance with a DataVolume as a volume source using Alpine import should be successfully started and stopped multiple times" fails

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1701]
/kind bug

**What happened**:
CI fails

**What you expected to happen**:
CI passes

**How to reproduce it (as minimally and precisely as possible)**:
http://jenkins.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/2494/testReport/
and https://jenkins.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/test_results_analyzer/

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fabiand** [comment]
@aglitke any idea?

**Comment by aglitke** [comment]
Not really.  The provided link is already broken.  Can you attach a bit more pinpointed information directly to the issue?

**Comment by fabiand** [comment]
The link was broken, fixed: https://jenkins.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/2494/testReport/

**Comment by fabiand** [comment]
Closing this for now, let's see if it comes up again.
