### ISSUE TITLE
virtctl vnc on Windows

### ISSUE THREAD

**Issue by slintes** [kubevirt/kubevirt#1713]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What happened**:
After merging https://github.com/kubevirt/kubevirt/pull/1673, `virtctl vnc` won't even try anymore to open `remote-viewer` on Windows. According to https://github.com/kubevirt/kubevirt/pull/1694, there is a viewer on Windows which works.

**What you expected to happen**:
The Windows vnc viewer mentioned in the PR above should work with `virtctl vnc`

**Comment by mlsorensen** [comment]
It should be straight forward to add a "windows" case, we just need someone who can put it in and try it.  

If the goal is just to execute something called "remote-viewer" on windows you can try something like:

```
-               case "linux":
+               case "linux", "windows":
```

If it's "virt-viewer" or some other name, copy the "linux" case to a new "windows" one, add a new constant, and adjust.
