### ISSUE TITLE
Unable to create vm because validation returns connection refused

### ISSUE THREAD

**Issue by rwsu** [kubevirt/kubevirt#1714]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
Creating a VM using the demo manifest fails because validation returns connection refused. 
```
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872] fatal: [ec2-34-204-190-124.compute-1.amazonaws.com]: FAILED! => {
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]     "changed": true,
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]     "cmd": [
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]         "kubectl",
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]         "apply",
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]         "-f",
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]         "https://raw.githubusercontent.com/kubevirt/demo/master/manifests/vm.yaml"
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]     ],
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]     "delta": "0:00:02.052229",
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]     "end": "2018-11-16 03:31:30.192172",
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]     "invocation": {
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]         "module_args": {
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]             "_raw_params": "kubectl apply -f https://raw.githubusercontent.com/kubevirt/demo/master/manifests/vm.yaml",
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]             "_uses_shell": false,
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]             "argv": null,
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]             "chdir": null,
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]             "creates": null,
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]             "executable": null,
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]             "removes": null,
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]             "stdin": null,
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]             "warn": true
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]         }
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]     },
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]     "msg": "non-zero return code",
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]     "rc": 1,
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]     "start": "2018-11-16 03:31:28.139943",
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]     "stderr": "Error from server (InternalError): error when creating \"https://raw.githubusercontent.com/kubevirt/demo/master/manifests/vm.yaml\": Internal error occurred: failed calling admission webhook \"virtualmachine-validator.kubevirt.io\": Post https://virt-api.kube-system.svc:443/virtualmachines-validate?timeout=30s: dial tcp 10.99.102.90:443: connect: connection refused",
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]     "stderr_lines": [
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]         "Error from server (InternalError): error when creating \"https://raw.githubusercontent.com/kubevirt/demo/master/manifests/vm.yaml\": Internal error occurred: failed calling admission webhook \"virtualmachine-validator.kubevirt.io\": Post https://virt-api.kube-system.svc:443/virtualmachines-validate?timeout=30s: dial tcp 10.99.102.90:443: connect: connection refused"
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]     ],
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]     "stdout": "",
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872]     "stdout_lines": []
[aws-centos-12afade1-16ae-4b6f-ba29-1b9dee90c872] }
```
We captured this error in our push button tests. We first create a kubernetes cluster and then install kubevirt. Before creating the vm, the virt-handler, virt-api, and virt-controller pods were verified to be running, and the virt-api service was present.

This issue doesn't always happen, so appears to be some sort of race condition. After some time, we can create the vm.

What could be causing this issue?

**What you expected to happen**:
VM creation should not fail on validation. Validation should not return connection refused.

**How to reproduce it (as minimally and precisely as possible)**:
Install upstream kubernetes, install kubevirt, and then create demo vm.

**Anything else we need to know?**:
Full log from our CI: https://jenkins-kubevirt.apps.ci.centos.org/blue/rest/organizations/jenkins/pipelines/cloud-image-builder/branches/release-0.10/runs/3/log/?start=0
Search for log entries with aws-centos.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.10.0
Client Version: version.Info{GitVersion:"v0.10.0", GitCommit:"6ddf4f4e2db4924ac0725676db72bb78acc6cca2", GitTreeState:"clean", BuildDate:"2018-11-08T13:47:51Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.10.0", GitCommit:"6ddf4f4e2db4924ac0725676db72bb78acc6cca2", GitTreeState:"clean", BuildDate:"2018-11-08T13:47:51Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`): v1.12.2
- VM or VMI specifications: https://raw.githubusercontent.com/kubevirt/demo/master/manifests/vm.yaml
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):  CentOS 7.5.1804 Core
- Kernel (e.g. `uname -a`): Linux ip-172-30-0-5.ec2.internal 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by kunalkushwaha** [comment]
I am also facing this issue.

Is there a way to query what all webhooks are installed?

**Comment by rwsu** [comment]
After further investigation, this appears to be a timing issue. The virt-api service port 443 was not open or was not available when I had attempted to create the VM. My test script had tried to create a VM right after installing KubeVirt, so it appears the KubeVirt pods and/or service may have been in the middle of starting up when the request to create a VM was issued.

I was able to resolve this issue by waiting for port 443 to be open for the virt-api service before creating the VM. See: https://github.com/kubevirt/cloud-image-builder/blob/master/tests/pretest-checks.yml#L41

**Comment by rwsu** [comment]
@kunalkushwaha does my comment above regarding waiting for port 443 to be available help you in your situation?

**Comment by rwsu** [comment]
@kunalkushwaha It is unclear to me which change you are attempting to test. Could you provide more details?

From the mailing list discussion, it looks like you are having trouble reaching 10.96.0.1 which you showed to be the kubernetes service. I think that is a different from this issue.

**Comment by fabiand** [comment]
If this is still an issue please reopen.

/close
