### ISSUE TITLE
Do we want a Crashed event?

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#173]
Follow up on https://github.com/kubevirt/kubevirt/pull/171#discussion_r108626510 if we want to distinguish on the event level between shutdown and crash. At the moment we only have a Stopped event.

**Comment by mpolednik** [comment]
Thinking about that, I'm not sure. It may be slightly beneficial to know what has really happened to a VM, but it could be the case of 'Stopped' event being extremely generic - VM is stopped when it crashes, stops, is shutdown, migrates etc. Yet duplicating LifeCycles sounds redundant.

If you agree, I'd keep this open for a bit longer as we may find that we want such event later on.

**Comment by rmohr** [comment]
Sure. Let's keep it open. Good summary of the situation.

**Comment by rgolangh** [comment]
If the event can contain some payload, and to stress out the `reason` it is stopped, than it might be enough for consumers of such events. e.g a RestartVmController would be able to consume a single event type and match against the `reason` to take action. 
If we can't add that then another type would be good, but it all comes down to who are the consumers and what do they need, and I'm quite new to the project and can't really tell.

**Comment by fabiand** [comment]
@rmohr do we still want this?

I suppose we do want.
Question is if we can reliably detect crashes?

**Comment by rmohr** [comment]
We can detect them to some degree. There are some qemu/libvirt events which report the reason crashed. Right now both, crash and shutdown, trigger a `Stopped` event, but one at `Warning` level and the other one at `Normal` level. Also the reason string describes the details:

```
5s        5s        1         vm-nocloud.1535d36644198099                       VirtualMachine                                           Warning   Stopped              virt-handler, node01        The VM crashed.
5s        5s        1         vm-nocloud.1535d36644198099                       VirtualMachine                                           Normal   Stopped              virt-handler, node01        The VM was shut down.

```

**Comment by fabiand** [comment]
@rmohr do we already expose the crash informations to the degree that
libvirt provides them?

**Comment by fabiand** [comment]
If we can detect it then it makes sense.
