### ISSUE TITLE
"Configurations New VirtualMachineInstance with all supported drives should have all the device nodes" failed 1 times

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1741]
/kind bug

What happened:
This test failed 1 times in the most recent 8 jobs with:

STDOUT:
```
{"component":"tests","kind":"VirtualMachineInstance","level":"info","msg":"Created virtual machine pod virt-launcher-testvmiks575z7t9dckks27lxrsqszhnx762zvkp9zd4v2kgt","name":"testvmiks575z7t9dckks27lxrsqszhnx762zvkp9zd4r6rgwmn2z4q","namespace":"kubevirt-test-default","pos":"utils.go:263","timestamp":"2018-11-15T18:21:21.474927Z","uid":"409d7e51-e903-11e8-995e-525500d15501"}
{"component":"tests","kind":"VirtualMachineInstance","level":"info","msg":"Pod ownership transferred to the node node02","name":"testvmiks575z7t9dckks27lxrsqszhnx762zvkp9zd4r6rgwmn2z4q","namespace":"kubevirt-test-default","pos":"utils.go:263","timestamp":"2018-11-15T18:21:37.661974Z","uid":"409d7e51-e903-11e8-995e-525500d15501"}
{"component":"tests","kind":"VirtualMachineInstance","level":"info","msg":"VirtualMachineInstance defined.","name":"testvmiks575z7t9dckks27lxrsqszhnx762zvkp9zd4r6rgwmn2z4q","namespace":"kubevirt-test-default","pos":"utils.go:263","timestamp":"2018-11-15T18:21:38.301696Z","uid":"409d7e51-e903-11e8-995e-525500d15501"}
{"component":"tests","kind":"VirtualMachineInstance","level":"info","msg":"VirtualMachineInstance started.","name":"testvmiks575z7t9dckks27lxrsqszhnx762zvkp9zd4r6rgwmn2z4q","namespace":"kubevirt-test-default","pos":"utils.go:263","timestamp":"2018-11-15T18:21:38.327008Z","uid":"409d7e51-e903-11e8-995e-525500d15501"}
{"component":"tests","kind":"VirtualMachineInstance","level":"info","msg":"Login: [{2  []}]","name":"testvmiks575z7t9dckks27lxrsqszhnx762zvkp9zd4r6rgwmn2z4q","namespace":"kubevirt-test-default","pos":"utils.go:1707","timestamp":"2018-11-15T18:24:48.398542Z","uid":"409d7e51-e903-11e8-995e-525500d15501"}

```

TRACE:
```
/root/go/src/kubevirt.io/kubevirt/tests/vmi_configuration_test.go:741
Expected error:
    <expect.TimeoutError>: 180000000000
    expect: timer expired after 180 seconds
not to have occurred
/root/go/src/kubevirt.io/kubevirt/tests/vmi_configuration_test.go:747
```

What you expected to happen:
Test passes

How to reproduce it (as minimally and precisely as possible):
Take a look at the failures in:
- https://jenkins.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/2524/testReport/

Anything else we need to know?:
This was automatically filed, because it was one of the TOP 8 failing tests.

**Comment by fabiand** [comment]
@fromanirh can you take a look at this? `git blame` named you to have been looking at this line in the past

**Comment by fromanirh** [comment]
@fabiand sure! At first glance it seems a timeout, we didn't get far enough to actually verify the device nodes. I've visited https://jenkins.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/2524/testReport/ but I can't find more detailed logs, where I can get them?

**Comment by fabiand** [comment]
Right. Thanks for checking so quickly.

The whole output is available here:
https://jenkins.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/2524/consoleText

If there is also not enough in there, then you might need to add some more output.

**Comment by fromanirh** [comment]
@fabiand this helps, thanks. This line looks suspicious:

check-patch.openshift-3.11-crio-release.el7.x86_64] {"component":"tests","kind":"VirtualMachineInstance","level":"info","msg":"Login: [{2  []}]","name":"testvmiks575z7t9dckks27lxrsqszhnx762zvkp9zd4r6rgwmn2z4q","namespace":"kubevirt-test-default","pos":"utils.go:1707","timestamp":"2018-11-15T18:24:48.398542Z","uid":"409d7e51-e903-11e8-995e-525500d15501"}

I'm approaching the edge od my knowledge, but it seems that this expectations failed:

  LoggedInCirrosExpecter

maybe the Cirros image changed in some unexpected way?
Maybe this could explain also the other failures.

**Comment by fabiand** [comment]
I suspect you speak about #1689 ... We try to get hold of the flaky tests.

**Comment by fabiand** [comment]
Side note: This was a timeout, maybe this was related to high infrastructure load.

**Comment by fabiand** [comment]
Closing as a dupe of #1768
