### ISSUE TITLE
virt-handle should register on the apiserver

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#176]
At the moment, when proxying VM connections, we have no way to know the virt-handler port for sure. virt-handler should register itself somewhere, so that we can look up the connection details.

Maybe adding something to the tains section of the node it is running on is good enough.

**Comment by fabiand** [comment]
@rmohr do we want to keep this rfe?

**Comment by rmohr** [comment]
It's not relevant right now. We can close it. Thanks for the ping.
