### ISSUE TITLE
Kubernetes in KubeVirt VMs

### ISSUE THREAD

**Issue by d-kononov** [kubevirt/kubevirt#1777]
Do you an example of how to launch k8s cluster in VM? Maybe you already have VM with the pre-installed k8s cluster, but I missed it.

I want to launch k8s in k8s with using kubevirt. 

BTW you did a great job and awesome add-on!

**Comment by gageorsburn** [comment]
I was actually thinking about this today. Not sure if anyone has attempted yet, someone probably has, but I'll give this a shot.

**Comment by cynepco3hahue** [comment]
We have a bunch of images that includes VM disks with different pre-installed clusters, you can check https://github.com/kubevirt/kubevirtci

**Comment by fabiand** [comment]
On Thu, Nov 29, 2018 at 8:58 AM Gage Orsburn <notifications@github.com>
wrote:

> I was actually thinking about this today. Not sure if anyone has attempted
> yet, someone probably has, but I'll give this a shot.
>

So, I did this here:
https://github.com/fabiand/cluster-templates

If you got sufficient ram 12GB+ then you can easily bring up a 3node
cluster in ~5min
I didn't test it with 0.10, but back then it looked alright.
There are some updates I'd like to do to this repo, but it willt ake some
time until I get to it.

I know that others are also working on stuff like this.

**Comment by fabiand** [comment]
So, I did this here:
https://github.com/fabiand/cluster-templates

Trigger by

```
$ oc process --local -f kubeadm.yaml PVCNAME=centos7 | kubectl apply -f -
statefulset.apps/cluster created
virtualmachine.kubevirt.io/kubenode created
secret/kubenode-bootstrap-for-cluster-kubernetes created
```

And details:

```
$ oc process --local -f kubeadm.yaml --parameters
NAME                DESCRIPTION                             GENERATOR           VALUE
VMNAME              Name of the new VM _template_                               kubenode
PVCNAME             Name of the PVC with the disk image                         
CLUSTERNAME         Name of the cluster to create or join                       kubernetes
SSH_PUBKEY          Public key to grant access to   
```

If you got sufficient ram 12GB+ then you can easily bring up a 3node
cluster in ~5min
I didn't test it with 0.10, but back then it looked alright.
There are some updates I'd like to do to this repo, but it willt ake some
time until I get to it.

I know that others are also working on stuff like this.

**Comment by gonzolino** [comment]
We are also looking into this topic. At the moment we are installing the clusters with kubeadm on top of  KubeVirt VMs and we are orchestrating this with Ansible playbooks.
To manage Nodes in the cluster and to support services of type LoadBalancer we started developing a cloud-provider interface for Kubevirt to use with the [CCM](https://kubernetes.io/docs/concepts/architecture/cloud-controller/): https://github.com/gonzolino/cloud-provider-kubevirt (still WIP, but in general it is already working)

**Comment by fabiand** [comment]
Yeah, cluster api would be nice as well.

**Comment by gonzolino** [comment]
Isn't there already a repository for a cluster-api implementation: https://github.com/kubevirt/cluster-api-provider-external ?

**Comment by kfox1111** [comment]
hehe. awesome. thanks for the link. :)

**Comment by fabiand** [comment]
> Isn't there already a repository for a cluster-api implementation: https://github.com/kubevirt/cluster-api-provider-external ?

This is actualy a Cluster API for interacting with bare metal nodes. We should rename it.

**Comment by alvaroaleman** [comment]
@kfox1111 @d-kononov In case you are interested, we've just added support for kubevirt as a provider for our cluster-api-based machine-controller which we use to manager Kubernetes worker nodes: https://github.com/kubermatic/machine-controller#deploy-the-machine-controller / https://github.com/kubermatic/machine-controller/blob/master/docs/kubevirt.md

**Comment by kfox1111** [comment]
Nice. I'll take a look. Thanks. :)

**Comment by kfox1111** [comment]
Noticed this was mentioned in the toc meeting. :)
