### ISSUE TITLE
SR-IOV network attachment grants privileged=true mode to virt-launcher

### ISSUE THREAD

**Issue by booxter** [kubevirt/kubevirt#1784]
/kind bug

**What happened**: when a VMI is attached to a sriov multus network, its virt-launcher is started with privileged=true. It was needed before when SR-IOV DP was not allocating necessary /dev/vfio/<NUM> device nodes to containers, but now that it does, we should move away from the practice. This means we will need to register (or instruct admins to) devices with vfio subsystem before SR-IOV DP up; remove privileged=true; perhaps also cleaning up some hostMounts added to launcher pod to facilitate vfio registration by libvirt; and finally, making sure libvirtd correctly handles the allocated vfio device (which means 1. it doesn't crash and 2. it doesn't unregister vfio device on exit).

**What you expected to happen**: launcher pod should not grant privileged=true to user.

**How to reproduce it (as minimally and precisely as possible)**: create a VMI attached to sriov multus network. The virt-launcher pod is started with privileged=true.

**Anything else we need to know?**: SR-IOV is an experimental feature and is hidden behind a feature gate.
**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by booxter** [comment]
The step 0 here really is merging support for the latest SR-IOV DP: https://github.com/kubevirt/kubevirt/pull/1692 I will then push more patches on top of it.

**Comment by SchSeba** [comment]
still very important issue
