### ISSUE TITLE
Move the client into a dedicated package to make consumption easier

### ISSUE THREAD

**Issue by alvaroaleman** [kubevirt/kubevirt#1793]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:

As a downstream consumer of the kubevirt API and lazy person I would like to import  a client from kubevirt. This is possible by importing the `kubevirt.io/kubevirt/pkg/kubecli` package, however that package defines some flags and if the same flags are defined elsewhere, the resulting app panics on startup.

**What you expected to happen**:

The client to be in a package that does not define any flags

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
Makes a lot of sense.

**Comment by alvaroaleman** [comment]
Sidenote for future passersby: Instead of changing the client here we started to use the [dynamic client from controller-runtime](https://godoc.org/github.com/kubernetes-sigs/controller-runtime/pkg/client#Client) that can work on any kind of resource, hence getting rid of the need of importing a typed client in the first place
