### ISSUE TITLE
Move all verbs to `virtctl`

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#181]
PR https://github.com/kubevirt/kubevirt/pull/178 adds a `virtctl` command.

This will be used in future as a kubectl plugin, to enable this we should already move all verbs from `cluster/kubectl.sh` to `virtctl`.

**Comment by rmohr** [comment]
Currently we have one thing which needs to be moved.

```bash
if [ "x$1" == "xspice" ]; then
        viewer=${SPICE_VIEWER:-remote\-viewer}
        if [ "x$3" == "x--details" ]; then
            curl -sS http://${master_ip}:8184/apis/kubevirt.io/v1alpha1/namespaces/default/vms/$2/spice  -H"Accept:text/plain"
        else
            curl -sS http://${master_ip}:8184/apis/kubevirt.io/v1alpha1/namespaces/default/vms/$2/spice > ${KUBEVIRT_PATH}cluster/.console.vv  -H"Accept:text/plain"
            echo $viewer
            $viewer ${KUBEVIRT_PATH}cluster/.console.vv
        fi
        exit
fi
```

The content in this if statement in `cluster/kubectl.sh` should go into a go file in `pkg/virtctl/spice`.
