### ISSUE TITLE
CII Best Practices badge in CNCF Landscape

### ISSUE THREAD

**Issue by xsgordon** [kubevirt/kubevirt#1823]
**Edit:** Current status: [![CII Best Practices](https://bestpractices.coreinfrastructure.org/projects/2805/badge)](https://bestpractices.coreinfrastructure.org/projects/2805)

KubeVirt is shown in the CNCF landscape: https://landscape.cncf.io/format=landscape&selected=kube-virt

It does not have the currently have the CII Best Practices badge. It is not a requirement for the project today but is a general indicator of good practices.

More details at https://bestpractices.coreinfrastructure.org/en/

**Comment by fabiand** [comment]
/remove-lifecycle stale

I made some progress but still need to finish it.

**Comment by rmohr** [comment]
Superseeded by #2679.
