### ISSUE TITLE
Make virtctl vnc wait for VMI to become ready

### ISSUE THREAD

**Issue by qmfrederik** [kubevirt/kubevirt#1837]
**Is this a BUG REPORT or FEATURE REQUEST?**: 
/kind enhancement

**What happened**:
#1001 made `virtctl console` wait for the console/VMI to become ready. This is super handy when you want to connect to a VM as soon as it is ready.

`virtctl vnc` doesn't implement the same behavior, and fails with a message similar to:
> Can't access VMI android-x86: Can't connect to websocket (400): Unable to connect to VirtualMachineInstance because phase is Scheduling instead of Running

**What you expected to happen**:
`virtctl vnc` to have the same behavior as `virtctl console`, and wait for the VMI/VNC connection to become available (possibly with a timeout)

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a new VMI
2. Run `virtctl vnc <VMI>`

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.12.0-alpha.0
- Kubernetes version (use `kubectl version`): 1.13.0
- VM or VMI specifications: android-x86 VM
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release): Ubuntu 18.04
- Kernel (e.g. `uname -a`): Linux qm-playground 4.17.0-18-kubedroid-host #1 SMP Mon Dec 10 14:36:16 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by rmohr** [comment]
I have a feeling that we should not have introduced this "wait" feature. Also "kubectl exec" does not wait until the pod is running. I personally find it confusing. I would prefer to not wait for both commands, but if most people find this "wait" behaviour useful we should definitely make it consistent across "console" and "vnc" and wait in both cases.

**Comment by fabiand** [comment]
Do we already have a ready condition? Wouldn't in that case `kubectl wait --for=condition=Ready … && virtctl vnc …` work?

**Comment by rmohr** [comment]
@fabiand I like this. This allows going back to the `kubectl exec` behaviour. @booxter you were the main driving force for the wait. What do you think?

**Comment by booxter** [comment]
@rmohr I didn't know about ```kubectl wait``` back then. If I did, I would probably not suggest to reimplement it in ```virtctl``` (best code is no code). I dunno if it's ok to rip off the feature now though.

**Comment by fabiand** [comment]
It's not nice, but we are still an unstable project, thus I'm at least
fine in ripping it out. And maybe have a warning message for a couple
of releases to use kubectl wait for blocking mode.

**Comment by booxter** [comment]
@fabiand giving a useful message may be a good idea not just for several releases. We already dump an error in the console, so adding something that can actually be useful would be good too. (And it doesn't complicate the logic of the tool; comparing to pretty elaborate waiting mechanism that the current implementation has.)

**Comment by fabiand** [comment]
True (not just for several releases).

Recommeding to "VM is not up yet.\nUse kubectl wait --for condition=Ready
in order to wait for the VM to come up." or something along those lines.
