### ISSUE TITLE
virtctl image-upload fails when a trailing slash is added to the upload proxy URL

### ISSUE THREAD

**Issue by tripledes** [kubevirt/kubevirt#1863]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

    $ virtctl image-upload --uploadproxy-url=https://cdi-uploadproxy-kube-system.apps.10.19.138.91.nip.io/ --pvc-name=upload-fedora-pvc4 --pvc-size=5Gi --image-path=tmp/Fedora-Cloud-Base-29-1.2.x86_64.qcow2 --insecure

Fails with:

Unexpected return value 500                                                       

Also:

    $ virtctl image-upload --uploadproxy-url=https://cdi-uploadproxy-kube-system.apps.10.19.138.91.nip.io/v1alpha/upload --pvc-name=upload-fedora-pvc4 --pvc-size=5Gi --image-path=tmp/Fedora-Cloud-Base-29-1.2.x86_64.qcow2 --insecure

Fails with:

Unexpected return value 404

**What you expected to happen**:

The URL with its path to be properly parsed and dealt with.

**How to reproduce it (as minimally and precisely as possible)**:

Execute the above commands.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):

Client Version: version.Info{GitVersion:"v0.9.6", GitCommit:"4badea07eb02458d4c64395f234fd2b77d74057e", GitTreeState:"clean", BuildDate:"2018-11-26T13:36:46Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{GitVersion:"v1.3.0-13-2-g377460b", GitCommit:"4badea07eb02458d4c64395f234fd2b77d74057e", GitTreeState:"clean", BuildDate:"2018-11-26T14:36:46Z", GoVersion:"go1.9.4", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`): Running on OpenShift 3.11

**Comment by annastopel** [comment]
fixed in https://github.com/kubevirt/kubevirt/pull/1981
