### ISSUE TITLE
VMI's IP and MAC addresses are not logged in virt-launcher pod 

### ISSUE THREAD

**Issue by rwsu** [kubevirt/kubevirt#1867]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:
The IP and MAC addresses are shown in "kubectl describe vmi".

I was analyzing the logs from Kibana and saw that the virt-launcher pod logs didn't show a VMI's IP or MAC address. I think logging those addresses would be useful for debugging or auditing especially when the VMI or pod is no longer alive and one is looking through the logs to triage an issue.

Is this possible? 

**What you expected to happen**:
If possible, to be able to see IP and/or MAC addresses in virt-launcher pod compute container log. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.11.0
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by qinqon** [comment]
Added a PR that print them just before starting the DHCP server.
