### ISSUE TITLE
Can not assign second IP address using Multus

### ISSUE THREAD

**Issue by msdmso** [kubevirt/kubevirt#1868]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Can not assign second IP address using Multus.

```
[root@fedora-vmi ~]# ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc fq_codel state UP group default qlen 1000
    link/ether c6:71:f4:06:25:f8 brd ff:ff:ff:ff:ff:ff
    inet 10.233.102.140/32 brd 10.233.102.140 scope global dynamic eth0
       valid_lft 86313069sec preferred_lft 86313069sec
    inet6 fe80::c471:f4ff:fe06:25f8/64 scope link
       valid_lft forever preferred_lft forever
3: eth1: <BROADCAST,MULTICAST> mtu 1500 qdisc noop state DOWN group default qlen 1000
    link/ether ae:62:70:12:3d:31 brd ff:ff:ff:ff:ff:ff

[root@kubehost1 ~]# kubectl describe pods virt-launcher-fedora-vmi-tvg6k
Name:               virt-launcher-fedora-vmi-tvg6k
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               node1/192.168.0.101
Start Time:         Thu, 20 Dec 2018 19:20:34 +0000
Labels:             kubevirt.io=virt-launcher
                    kubevirt.io/created-by=531b01fb-048c-11e9-a631-4201c0a80065
Annotations:        k8s.v1.cni.cncf.io/networks: macvlan-conf
                    k8s.v1.cni.cncf.io/networks-status:
                      [{
                          "name": "cni0",
                          "ips": [
                              "10.233.102.140"
                          ],
                          "default": true,
                          "dns": {}
                      },{
                          "name": "macvlan-conf",
                          "interface": "net1",
                          "ips": [
                              "192.168.1.204"
                          ],
                          "mac": "ae:62:70:12:3d:31",
                          "dns": {}
                      }]
                    kubevirt.io/domain: fedora-vmi
                    kubevirt.io/owned-by: virt-handler
...
```

**What you expected to happen**:

Assign second IP address to VM

**How to reproduce it (as minimally and precisely as possible)**:

1. Build Kubernetes cluster on GCP using kubespray (kube_network_plugin_multus: true).
2. Install KubeVirt 0.10.0
3. Apply macvlan-conf.yaml
4. Apply fedora-vmi.yaml based on https://kubevirt.io/2018/attaching-to-multiple-networks.html.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.10.0
- Kubernetes version (use `kubectl version`): 1.13.0
- VM or VMI specifications: 
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): CentOS Linux release 7.5.1804 (Core)
- Kernel (e.g. `uname -a`): Linux kubehost1 3.10.0-862.14.4.el7.x86_64 #1 SMP Wed Sep 26 15:12:11 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: Kubespray
- Others:

**Comment by SchSeba** [comment]
Hi @msdmso Thanks for pointing this out.

After a closer look I think I know what can be the problem.
The default fedora cloud image enable the dhcp only on the eth0 interface so if you what to enable dhcp and the eth1 you can do it using the cloud init configuration.

Something like this should work
```yaml
  - cloudInitNoCloud:
      userData: |
        #!/bin/bash
        echo "fedora" | passwd fedora --stdin
        dhclient eth1
    name: cloudinitvolume
```

Can you please apply this yaml file and tell me if it fix your issue?

I also saw that you are using the macvlan configuration I will try to check it in my own environment and update you.

**Comment by msdmso** [comment]
Hi @SchSeba Thanks for your help!

I can assign the second IP address using the following config.

```
  - cloudInitNoCloud:
      userData: |
        #!/bin/bash
        echo "fedora" | passwd fedora --stdin
        dhclient eth0 eth1
    name: cloudinitvolume
```

**Comment by SchSeba** [comment]
@msdmso Good!

Can we close this issue?

**Comment by msdmso** [comment]
@SchSeba Yes. Thanks!
