### ISSUE TITLE
runV support

### ISSUE THREAD

**Issue by Gnep** [kubevirt/kubevirt#187]
Hi,

I'm one of the maintainers of Hyper container and runV: github.com/hyperhq/runv.

Does kubevirt plan to support full-blown VM only, or include virtualized container like runV in the future?

Thanks.

**Comment by fabiand** [comment]
Hey Gnep,

the primary purpose of kubevirt is to support full-blown VMs - from an API POV.
We are not trying to solve virtualized containers.

But because VMs are involved in both approaches, to me it is still an open question if the implementations for the two use-cases could align - in one way or the other - over time.

**Comment by mykaul** [comment]
I would assume it should be fairly easy to run a VM that specializes in running containers, such as https://getfedora.org/en/atomic/

**Comment by fabiand** [comment]
es, running atomic, or boot2docker are options. But also running a kubelet within the vm (like minikube).
In that case a VM could become another node of the cluster (self hosted), and you get the vm isolation for all the pods within that node.

**Comment by rmohr** [comment]
Pretty late to the discussion. 

@Gnep do you have something specific in mind? Afaik, hyper is  built in a way, that it is transparent to kubernetes, right?

**Comment by Gnep** [comment]
@rmohr 

Yes, we have a project to integrate Hyper to K8s via CRI: github.com/kubernetes/frakti. It would be great to support kubevirt in frakti too.

Also we just submitted Stackube https://review.openstack.org/#/c/462453/. The idea is to mix Container (Hyper) and VM to the same class of cabin, and share the implementation of Cinder/Neutron, etc.

**Comment by fabiand** [comment]
By now it's clear that we go with an Operator approach which provides the VM runtime as pods.

And we are using CRDs to define the VM entities.
