### ISSUE TITLE
Creating a VMI with sidecar hook with an image that does not exists fails with no error message

### ISSUE THREAD

**Issue by kbidarkar** [kubevirt/kubevirt#1874]
**Is this a BUG REPORT or FEATURE REQUEST?**: 

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**: Creating a VMI with sidecar hook fails , with Libvirt Error, but no proper error message.

**What you expected to happen**: There should be a proper error message when it fails.

**How to reproduce it (as minimally and precisely as possible)**: Create a VMI With sidecard hook , using `0.12-alpha.2`

**Anything else we need to know?**:  Creation of sidecar error works, with the below image:
`hooks.kubevirt.io/hookSidecars: '[{"image": "kubevirt/example-hook-sidecar:v0.12.0-alpha.2"}]'`

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kbidarkar** [comment]
The error message that we see is the below,

```
Warning  SyncFailed        10m (x12 over 10m)  virt-handler, cnv-executor-kbidarka-node2.example.com  server error. command Launcher.Sync failed: "LibvirtError(Code=1, Domain=20, Message='internal error: Unknown source mode ''')"
```

**Comment by cynepco3hahue** [comment]
@kbidarkar I think you need to add `Creating a VMI with sidecar hook with an image that does not exist, fails with no error message`
