### ISSUE TITLE
Extend information returned by kubectl get

### ISSUE THREAD

**Issue by tylerauerbeck** [kubevirt/kubevirt#1894]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:
Would like to see additional fields returned when doing `kubectl get vmi`. Currently the only thing returned is the name and when it was created. 

```
NAME      CREATED AT
testvm    3m
```

**What you expected to happen**:
It would be useful (at a minimum) to see at least the status (whether something is still being scheduled or if it's actually ready for connections). Currently the instructions say to look at things via `kubectl describe ...`, however this can become tedious (especially when looking at multiple VM's)

```NAME      CREATED AT    STATUS
testvm1   3m    Scheduling
testvm2   3m    Running
```

**How to reproduce it (as minimally and precisely as possible)**:
* Create VM
* Start VM
* kubectl get vmi

**Anything else we need to know?**:
N\A

**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.11.0", GitCommit:"dfcd29f3b145db8691fa3190f713d4bdc067e659", GitTreeState:"clean", BuildDate:"2018-12-05T14:08:12Z", GoVersion:"go1.10", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{GitVersion:"v0.11.0", GitCommit:"dfcd29f3b145db8691fa3190f713d4bdc067e659", GitTreeState:"clean", BuildDate:"2018-12-05T14:08:12Z", GoVersion:"go1.10", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-10T16:38:01Z", GoVersion:"go1.10.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.0", GitCommit:"fc32d2f3698e36b93322a3465f63a14e9f0eaead", GitTreeState:"clean", BuildDate:"2018-03-26T16:44:10Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications: `https://raw.githubusercontent.com/kubevirt/demo/master/manifests/vm.yaml`
- Cloud provider or hardware configuration: `minikube`
- OS (e.g. from /etc/os-release):
```
NAME=Buildroot
VERSION=2018.05
ID=buildroot
VERSION_ID=2018.05
PRETTY_NAME="Buildroot 2018.05"
```
- Kernel (e.g. `uname -a`): `Linux minikube 4.15.0 #1 SMP Sat Dec 8 00:26:02 UTC 2018 x86_64 GNU/Linux`
- Install tools: `N/A`
- Others: `N/A`

**Comment by slintes** [comment]
Hi, we already have this, see https://github.com/kubevirt/kubevirt/pull/1654.
But you need to run k8s >= 1.11 in order to get this working. Looks like you're on k8s 1.10. For minikube, you should be able to switch to newer version with `minikube start --kubernetes-version v1.yy.z`. Can you please retry with this?

**Comment by tylerauerbeck** [comment]
@slintes Yepp, just saw this on a fresh install this morning. Going to go ahead and close this issue.
