### ISSUE TITLE
No identifier for a VM that can be used by the guest

### ISSUE THREAD

**Issue by ahadas** [kubevirt/kubevirt#1906]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
We currently have two identifiers for a VM in its metadata - UID and Name. UID is auto-generated by k8s and Name is provided by the user and cannot be updated.
This creates the following problem: assuming I want to each VM to be assigned with a unique serial number (PR #1897 allows to assign a custom serial number). Neither the UUID nor the Name of the VM can be used because in order to rename this VM I need to re-create the VirtualMachine entity with a new name and it will get a new UUID. I would like the serial number of the VM to remain the same when the VM is renamed.

**What you expected to happen**:
I would expect the VM to maintain some identifier that remains the same when the VM is renamed (and later, possibly when it's cloned).

**Anything else we need to know?**:
I think the way we can achieve this is by relying on the Firmware.UUID field.
When a VM is created:
- If it is set with Firmware.UUID we will use it.
- Otherwise, we will generate a new UUID.

That way, when the VM is renamed/cloned, this UUID will be copied to the new instance. When the serial number is set to a unique value per-VM, we will use the value of this field.

**Comment by rmohr** [comment]
> I think the way we can achieve this is by replying on the Firmware.UUID field.
> When a VM is created:
> 
> * If it is set with Firmware.UUID we will use it.
> * Otherwise, we will generate a new UUID.
> 
> That way, when the VM is renamed/cloned, this UUID will be copied to the new instance. When the serial number is set to a unique value per-VM, we will use the value of this field.

Hm, at least for something like a VirtualMachineInstanceStatefulSet it is preferrable that the uuid is bound to the name, in order to allow easy delcarative flows. Aso for a VM, it has the advantage that we can recreate the same vmi configuration from the yaml of a VM which lies for instance in a git repo.

**Comment by rmohr** [comment]
We might also see 'kubectl apply' issues if we just fill in values in the spec for users on objects which are not pods or vmis.

**Comment by ahadas** [comment]
@rmohr , 
1. Honestly, I didn't think about VirtualMachineInstanceStatefulSet. Is it also derived from VMs?
2. Not sure I understand the VM part - I think it would behave the same. If the yaml of the VM includes a Firmware.UUID then the VMI will be set with that value in both cases, and otherwise, a new UUID is generated in both cases, no?
3. That's good that kubevirt allows to provide a value for Firmware.UUID - that covers the ability to provide the VM UUID which was added to oVirt not that long ago. But I believe the Firmware.UUID of a VM should be static even when it is not provided by the user.

**Comment by rmohr** [comment]
> * Honestly, I didn't think about VirtualMachineInstanceStatefulSet. Is it also derived from VMs?

Oh, we don't have it yet. It was hypothetical.

> * Not sure I understand the VM part - I think it would behave the same. If the yaml of the VM includes a Firmware.UUID then the VMI will be set with that value in both cases, and otherwise, a new UUID is generated in both cases, no?

Yes, but the uuid will be constant if the name stays constant and you will see the uuid on the VMI which will be created by the VM.

> * That's good that kubevirt allows to provide a value for Firmware.UUID - that seems to cover the ability to provide the VM UUID which was added to oVirt not that long ago. But I believe the Firmware.UUID of a VM should be static even when it is not provided by the user.

I am not sure. We know how the uuid is calculated (based on the name), so we could set it on the cloned VM explicitly if you care about the uuid.

**Comment by rmohr** [comment]
> We were actually wondering about this part yesterday - so is there a reason for not having a mutating-webhook for a VM? Can you please point to a relevant explanation?

https://github.com/kubernetes/enhancements/issues/555 and https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/0006-apply.md.

Once we have the "apply" logic on the server and can intercept it with proper webhooks for custom resources we could add defaulting which changes the spec visibly. Otherwise we will not be able to calculate diffs properly and properly handle spec generations properly.

**Comment by ahadas** [comment]
> > * Honestly, I didn't think about VirtualMachineInstanceStatefulSet. Is it also derived from VMs?
> 
> Oh, we don't have it yet. It was hypothetical.

Ah, ok.
My two cents on this is that if it would be possible to create a VM pool that is derived from a VM (which is not possible in oVirt, btw) and the serial policy number is set to "per-VM" (rather than to a custom value) then we'll need to generate a new Firmware.UUID for each VM in the pool.

> 
> > * Not sure I understand the VM part - I think it would behave the same. If the yaml of the VM includes a Firmware.UUID then the VMI will be set with that value in both cases, and otherwise, a new UUID is generated in both cases, no?
> 
> Yes, but the uuid will be constant if the name stays constant and you will see the uuid on the VMI which will be created by the VM.

Right, if you mean that both approaches will behave the same as long as the name stays constant - I agree. The thing is that I don't think it's a practical assumption - users would expect to be able to rename VMs, especially when moving VMs between different environments.

> 
> > * That's good that kubevirt allows to provide a value for Firmware.UUID - that seems to cover the ability to provide the VM UUID which was added to oVirt not that long ago. But I believe the Firmware.UUID of a VM should be static even when it is not provided by the user.
> 
> I am not sure. We know how the uuid is calculated (based on the name), so we could set it on the cloned VM explicitly if you care about the uuid.

Right, but then it becomes harder to manage.
Imagine the following case:
1. Create a VM with name=my-vm and no Firmware.UUID set
2. Export that VM
3. Import that VM to another setup and set it with a different name 'my-vm-from-previous-env'.

So in order to make the guest see the same information in SMBIOS, I guess we'll need some logic like: if the VM is renamed (via regular-rename/clone/import-with-a-different-name/etc) then before renaming it, calculate the UUID based on the previous name and store it.

**Comment by ahadas** [comment]
> > We were actually wondering about this part yesterday - so is there a reason for not having a mutating-webhook for a VM? Can you please point to a relevant explanation?
> 
> [kubernetes/enhancements#555](https://github.com/kubernetes/enhancements/issues/555) and https://github.com/kubernetes/enhancements/blob/master/keps/sig-api-machinery/0006-apply.md.
> 
> Once we have the "apply" logic on the server and can intercept it with proper webhooks for custom resources we could add defaulting which changes the spec visibly. Otherwise we will not be able to calculate diffs properly and properly handle spec generations properly.
> 
> As it is right now, we must not modify the spec the user provides to make apply work reliably. For VMIs that is not a problem because right now the spec can't be modified at all.

Thanks, ok, now it's clear.

**Comment by rmohr** [comment]
@ahadas from our discussion it is not clear to me, if the initial request of having static UUIDs is sufficient with the api field or if you still want something different. Is it now mostly about cloning or do you still want some change on the current VM behaviour?

**Comment by ahadas** [comment]
@rmohr this discussion made me realize the difficulty to achieve what I had in mind :) but yeah, it's about renaming or cloning a VM. if I need to write it as a user story than I would say:
1. The user creates a VM with serial-number-policy=per-VM and does not provide Firmware.UUID
2. The user starts the VM - the VMI is assigned with serial-number=X (derived from its name)
3. The user renames the VM/clone it
4. The user starts the renamed/cloned VM
=> The VMI should be assigned with serial-number=X while in practice it would be assigned with a different value derived from its new name.

Maybe it's ok to require clients to generate Firmware.UUID in this case.
Also, maybe it's ok to generate Firmware.UUID when cloning/renaming the VM as users are less likely to use the `kubectl apply` functionality on the cloned/renamed VM, I think.
