### ISSUE TITLE
KubeVirt VM and another host support in the same subnets.

### ISSUE THREAD

**Issue by kenzhaoyihui** [kubevirt/kubevirt#191]
Hi,
   I have a question. From my point of view, KubeVirt wants to launch the VM, like VM is running on pods.
I want to know how about the network between the VM and the container . And if another host want to ssh on the VM, does it support or does it keep them in the same subnets?

Thanks!

**Comment by rmohr** [comment]
@kenzhaoyihui At the moment, the VMs are not connected to the container network. @sungwonh is working on that in #160 . You can however connect your VMs to any libvirt network you like. It will work as usual. Just define them upfront in libvirt and then refernce them in your vm spec. So if another VM or host can reach the libvirt network you can ssh into them from there.

**Comment by fabiand** [comment]
With #279 a proposal was merged which is explaining how VM networks will be (initially) integrated with Pod networks.

Hopefully this integration will be even nicer (i.e. NetworkPolicies can also be applied) when multiple networks per pod are official supported.
