### ISSUE TITLE
vmi-fedora does not boot, mac address keep changing

### ISSUE THREAD

**Issue by petrkotas** [kubevirt/kubevirt#1917]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
Fedora virtual machine does not start properly. Goes through the lifecycle: scheduling -> running -> failed. The mac address keep changing constantly as shown in ![output](https://user-images.githubusercontent.com/8687113/50835261-84583800-1356-11e9-94fc-6dccf31975f4.gif)

Also when trying to connect to console the request end with error: serial console not ready.

Attaching logs:

[virt-launcher.log](https://github.com/kubevirt/kubevirt/files/2737159/virt-launcher.log)
[virt-handler.log](https://github.com/kubevirt/kubevirt/files/2737163/virt-handler.log)
[virt-controller-1.log](https://github.com/kubevirt/kubevirt/files/2737165/virt-controller-1.log)

**What you expected to happen**:
Fedora virtual machine to boot normally with console allowing me to connect.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy development setup on current master (make cluster-up, make cluster-sync) and deploy vmi-fedora from examples.

**Anything else we need to know?**:
The culprit is most likely damaged fedora image in fedora container disk.

**Environment**:
- KubeVirt version (use `virtctl version`): current master
- Kubernetes version (use `kubectl version`): current master
- VM or VMI specifications: /cluster/examples/vmi-fedora.yaml
- Cloud provider or hardware configuration: kubevirt ci
- OS (e.g. from /etc/os-release): host fedora 29, inside centos 7 (from kubevirt ci)
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by davidvossel** [comment]
fedora 29 seems to be working fine. I don't know what you're experiencing. We use fedora29 container disk image in CI and those tests pass as well.

**Comment by rmohr** [comment]
> The mac address keep changing constantly as shown in

Your VM is restarted when it fails. That means that a new pod with new ip/mac is created. That's necessary to tie the VM into the pod network, since k8s does not have the concept of static mac/ip.

> The culprit is most likely damaged fedora image in fedora container disk.

@petrkotas can't reproduce this either. My guess is that your locally built image is corrupt. Try cleaning you docker cache and rebuild and the issue should go away.

**Comment by fabiand** [comment]
@petrkotas if this is still an issue please open this issue.

/close
