### ISSUE TITLE
Make sure all the necessary HyperV enlightements can be configured

### ISSUE THREAD

**Issue by MarSik** [kubevirt/kubevirt#1919]
/kind enhancement

Windows guest's performance depends on the configuration of the HyperV enlightements. There are quite a few that might need to be or not to be enabled for different Windows versions to perform properly.

Kubevirt API exposes those using the `VM.spec.template.spec.domain.features.hyperv` dictionary.

You can get the idea from couple of Red Hat bugs like:

- https://bugzilla.redhat.com/show_bug.cgi?id=1663162
- https://bugzilla.redhat.com/show_bug.cgi?id=1610461

To make this easier to read, the current list of qemu names for the englightements are:

```
 hv-relaxed - windows activates it automatically when hypervisor CPU flag is present.
 hv-vapic - should speed things up in general (IRQs)
 hv-time - should speed things up significantly
 hv-crash - can we capture this info?
 hv-reset - rather redundant
 hv-vpindex - required for PV TLB flush/IPSs
 hv-runtime - for stats
 hv-synic - required for stimer
 hv-stimer - speed things up, especially with the latest Win10 update
 hv-frequencies - needed for Hyper-V on KVM (tsc page clocksource
 hv-reenlightenment - also needed for Hyper-V on KVM (tsc page clocksource)
 hv-tlbflush - speed things up in overcommited environments
```

Please note some of those can only be enabled when the qemu + libvirt + host kernel provide the necessary support or the guest VM will not start (synic, stimer are such example).

Also it might be a good idea to make this a bit more generic to allow adding new ones in an easy way.

**Comment by MarSik** [comment]
@davidvossel @rmohr @vladikr Guys, do you have any recommendation about what to do about englightements that need to be part of the API, but are not yet supported by our qemu/libvirt? We need to expose those in common templates, but we must not put them to libvirt XML until all the nodes are updated to recent enough versions of kernel / qemu / libvirt. Otherwise we would compromise the ability to start or migrate VMs.

oVirt has a ["feature gate" for synic](https://github.com/oVirt/ovirt-engine/blob/f380b737699fa10c808579bf2785bc6be46165c9/backend/manager/modules/vdsbroker/src/main/java/org/ovirt/engine/core/vdsbroker/builder/vminfo/LibvirtVmXmlBuilder.java#L732) for example.

Or we could use Node feature discovery approach and expose the supported features on nodes. The launcher would then use proper nodeSelector to make sure the VM will never end up on a node that does not support the necessary flags.

Would one or both approaches combined be acceptable for kubevirt?

**Comment by michalskrivanek** [comment]
NFD approach sounds good to me, though I wouldn't do it just yet for this particular case, we still do not have to bother much with upgrades. But in general yeah, NFD-like discovery of capabilities of kubevirt/libvirt/qemu sounds like a reasonable idea. I would eventually suggest to use some sort of grouping (likein oVirt case the cluster levels) to not have too many of them. It might be a good idea to expose "kubevirt_1.4" or something like that and implement a similar feature gate using that single label

**Comment by davidvossel** [comment]
> do you have any recommendation about what to do about englightements that need to be part of the API, but are not yet supported by our qemu/libvirt?

We control what version of qemu and libvirt we ship.  We shouldn't be in a situation where we add something to our API that isn't supported by our version of qemu/libvirt. So from a qemu/libvirt perspective, I don't see a problem. The API updates will be coupled with the qemu/libvirt update.

The only thing I'd be concerned about detecting is node level kernel features that are required for these features to work. Thats where NFD makes sense to me.

**Comment by michalskrivanek** [comment]
not on upgrades. In upgraded environments you will have VMs running with older images. They should keep running (i.e. stop/start, suspend/resume) with guest ABI being preserved - with older qemu/libvirt image - until VMs are explicitly "upgraded" to new version by admin/user.
We really need to have a proper upgrade discussion eventually:)

**Comment by MarSik** [comment]
@davidvossel Michal already mentioned the issue with long running older VMs. But there is another issue as well. You might not have enough nodes with the proper kernel version to be able to get the  synic support for the VMs you want to start. In that case you should be able to disable the feature to be able to start the VMs everywhere even though some optimization would be off.

Also the templates in general do not know which version of kubevirt is used and whether the feature is or is not supported by the node. So I would prefer if we could consider some of those flags (not just hyperv btw) a soft requests - meaning supported by API, but used only when all components align properly.

**Comment by michalskrivanek** [comment]
>  If the VM's offline config is changed to use the new features, then when the VM is restarted, the new container/scheduling that supports the api is used from the update.

right, that is something which needs to be done in a controlled way, separately from the time of kubevirt infra upgrade. I guess it's rather a problem for templates and how/when they are applied than kubevirt core.

**Comment by x8091** [comment]
@MarSik : I want to hide HyperV from kubevirt VM, how can I achieve that?

To do so, in libvirt XML I would add something like:

```
<kvm>
<hidden state='on'/>
</kvm>
```

For QEMU the option is `-cpu kvm=off ` 
So basically we need to pass this option to QEMU inside **virt-launcher**.

Is it supported by kubevirt features yet?

**Comment by rmohr** [comment]
@x8091 right now you can use a side-car to manipulate the resulting domain xml. We have an example which modifies the domain XML here: https://github.com/kubevirt/kubevirt/tree/master/cmd/example-hook-sidecar.

In order to have a more "supportable" solution, we would need to add it to kubevirt. Why exactly do you need this?

**Comment by x8091** [comment]
Thank you very much @rmohr.

So I'm testing GPU passthrough feature using kubevirt, the GPU is visible to the VM (using `lspci`) but Nvidia driver (`nvidia-smi `command) refuses to cooperate since it detects that it's running on a VM, to fix that we have to hide hypervisor to guest OS by passing `-cpu kvm=off `to QEMU.

I have verified the solution by using **virt-manager** and **virsh** tool to edit domain XML.

Back to this, besides side-car you mentioned do we have another way/trick to pass this parameter to QEMU inside virt-launcher? I would like to verify if it works first before going to a complete solution.

Thanks again.

**Comment by rmohr** [comment]
> Back to this, besides side-car you mentioned do we have another way/trick to pass this parameter to QEMU inside virt-launcher? I would like to verify if it works first before going to a complete solution.

I fear that this is our "quick" way. You can just checkout this repo, change the portion of the code which modifies the domain XML, push the sidecar to a container registry and use it when starting the VM.

**Comment by x8091** [comment]
Thanks for confirming. I'm going to try that now to see if it help.

**Comment by x8091** [comment]
This is the first time I try Sidecar feature-gate, I have problem create a sample VMI
```
kubectl logs -f pod/virt-launcher-vmi-with-sidecar-hook-czfsx   -c compute
{"component":"virt-launcher","level":"info","msg":"Failed to process sidecar socket: smbios.sock","pos":"manager.go:105","reason":"Hook sidecar does not expose a supported version. Exposed versions: [], supported versions: [v1alpha v1alpha2]","timestamp":"2019-10-24T10:38:35.372917Z"}
panic: Hook sidecar does not expose a supported version. Exposed versions: [], supported versions: [v1alpha v1alpha2]

goroutine 1 [running]:
main.main()
	cmd/virt-launcher/virt-launcher.go:340 +0x11c7
{"component":"virt-launcher","level":"error","msg":"dirty virt-launcher shutdown","pos":"virt-launcher.go:510","reason":"exit status 2","timestamp":"2019-10-24T10:38:35.376808Z"}
{"component":"virt-launcher","level":"error","msg":"Failed to reap process -1","pos":"virt-launcher.go:475","reason":"no child processes","timestamp":"2019-10-24T10:38:35.376861Z"}
```

Here is VMI yaml file
```
cat examples/vmi-with-sidecar-hook.yaml 
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  annotations:
    hooks.kubevirt.io/hookSidecars: '[{"image": "kubevirt/example-hook-sidecar:latest"}]'
    smbios.vm.kubevirt.io/baseBoardManufacturer: "HHKB Apple 22"
  labels:
    special: vmi-with-sidecar-hook
  name: vmi-with-sidecar-hook
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      rng: {}
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: kubevirt/fedora-cloud-container-disk-demo:latest
    name: containerdisk
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
    name: cloudinitdisk
```

I have tried with different version of docker images but got the same issue. What am I doing wrong here? I enabled Sidecar feature gate already.

Assuming this sample works, for my case, I need to write my own sidecar-hook container image to modify domain XML file, is that correct?

**Comment by slintes** [comment]
We currently have 2 API versions of the hook, `v1alpha1` and `v1alpha2`. The example implements both, but you need to specify in the annotation which version to use. E.g.:

`hooks.kubevirt.io/hookSidecars: '[{"image": "kubevirt/example-hook-sidecar:latest", "args": ["--version", "v1alpha2"]}]`

> Assuming this sample works, for my case, I need to write my own sidecar-hook container image to modify domain XML file, is that correct?

yes

**Comment by x8091** [comment]
Perfect @slintes. It works nicely now. Thanks a lot.

**Comment by shawnU96** [comment]
testing NVIDIA GPU passthrough , driver error code 43 .  
https://www.reddit.com/r/VFIO/comments/8pl48l/code_43_with_nvidia_passthrough_even_after/
kubevirt not support set 

<kvm>
<hidden state='on'/>
</kvm>

**Comment by shawnU96** [comment]
kubevirt not support set  **features.kvm.hidden = on**

**Comment by salanki** [comment]
Any chance we can get `features.kvm.hidden = on` added properly to kubevirt?
