### ISSUE TITLE
/var/run issue when running on Ubuntu host

### ISSUE THREAD

**Issue by rbradford** [kubevirt/kubevirt#192]
I was trying to deploy kubevirt to my existing k8s cluster running with Ubuntu 16.04 workers and discovered that virt-handler could not talk to libvirtd. The problem was that the socket was not available on the host.

This is is because /var/run is a symlink to /run (whereas on Fedora it is a symlink to ../run) this means that the socket does not get into the host OS.

**Comment by stu-gott** [comment]
Thanks for reporting this. It's unclear to me why the distinction between an absolute vs. relative symlink would cause this issue.

Within the context of the KubeVirt k8s manifest files, the path to the libvirt runtime directory is only ever referred to as /var/run/libvirt. So in either case, the symlink must be followed. Is there a context where an absolute reference to /run would be incorrect?

**Comment by rbradford** [comment]
On fedora the ../run would point to /host/run (so still on the host fs) but if it is a relative path then it would point to /run which is the "container" rootfs.

**Comment by stu-gott** [comment]
After conferring on IRC, the source of this issue was that the libvirt container on master is not yet fully functional, but that's not clear from the git tree.

**Comment by rmohr** [comment]
Sadly it is not very easy at the moment to set up libvirt the reight way when not running it from within our vagrant environment. https://github.com/kubevirt/community/pull/2 will give us the easy solution. For now you have to do the follwing things

 * Configure libvirt like we did here: https://github.com/kubevirt/kubevirt/blob/master/cluster/vagrant/setup_kubernetes_common.sh#L82
 * place our libvirt emulator script `cmd/virt-launcher/qemu-kube` at `/usr/local/bin/qemu-x86_64` on the host (qemu-x86_64 is the script name)
 * install the emulator script dependencies (sudo, nsenter, cgclassify)
 * give the script sudo privileges: https://github.com/kubevirt/kubevirt/blob/master/cluster/vagrant/setup_kubernetes_common.sh#L101

We should start working on https://github.com/kubevirt/community/pull/2 soon.

**Comment by fabiand** [comment]
With eb5e9ef443a84ec64f94c3a877d47c82cd0911a9 libvirt moved into a container, which should prevent this issue.

Please reopen if necessary.
