### ISSUE TITLE
no PHASE after create vm with kubevirt

### ISSUE THREAD

**Issue by majorinche** [kubevirt/kubevirt#1928]
we installed kubevirt successfully, and run vm ok at first
after a while, maybe 2hours, we can not deploy any vm
our example is coming from official(https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/intro.html)

check the status, find no status shows up under 'PHASE'
[root@infra1 ~]# oc get vmi
NAME      AGE       PHASE     IP        NODENAME
f2        2s                            

my question is, how to debug this problem, why no status show up in PHASE?

basic information:
env: openshift 3.11
kubevirt version: v0.10.0

thank you very much
majorin

**Comment by slintes** [comment]
Hi, it looks like the VMI you're looking at is only 2 seconds old, and so just didn't get a phase yet.
In order to debug further, please provide the logs of virt-api, virt-controller and virt-handler, and of virt-launcher of the relevant VMI. Thanks!

**Comment by fabiand** [comment]
@majorinche any updte?

**Comment by majorinche** [comment]
uninstall kubevirt, and reinstall version 0.11.1 fix the problem

**Comment by fabiand** [comment]
Awesome, thanks.

Let us know if there is anything else

/close
