### ISSUE TITLE
Check if VM to sync has the right UUID in virt-handler

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#193]
Virt-handler reacts to changes. Currently, if you delete a VM with name "testvm" and then immediately recreate it, virt-handler might not process the delete event and instead immediately see the new "testvm" object.

Therefore, in `DomainManager.SyncVM()` in virt-handler, check if the UUIDs match. If they don't, first delete the already defined domain via `DomainManager.KillVM()`.

**Comment by fabiand** [comment]
I think this is fixed by now, please reopen otherwise.
