### ISSUE TITLE
Introduce "virtctl migrate"

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1957]
/kind enhancement

Convenience verb to trigger a live migration

```
$ virtctl migrate myvmi (OR VM?)
```

**Comment by fabiand** [comment]
This should probably be a separate endpoint, as a convenient way to trigger migrations

**Comment by fromanirh** [comment]
I'd love to work on this, was this issue already assigned?

**Comment by fabiand** [comment]
No, nobody assigned so far.

Please note that (at least imho) this should involve a server side
subresource which creates the migration object (the <namespace/name> pair
thebn returned by the virtctl migrate command).

**Comment by fromanirh** [comment]
got it @fabiand , thanks

**Comment by fabiand** [comment]
/remove-lifecycle stale

@fromanirh ain't ou working on this?

>

**Comment by fromanirh** [comment]
> /remove-lifecycle stale @fromanirh ain't ou working on this?
> […](#)

sadly I am not. Releasing this task, if someone else can pick it up, feel free.

**Comment by slintes** [comment]
This is done already :)
https://github.com/kubevirt/kubevirt/pull/2645

/close
