### ISSUE TITLE
Improve the operator to support upgrades

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#1963]
/kind enhancement

We have an operator to perform delpoyment (#1122), the next step is to perform not major version, but minor version and below updates.

**Comment by davidvossel** [comment]
There's a pr #2033 related to this here. it's part 1/3 to getting proper updates supported

**Comment by fabiand** [comment]
With 0.17 a good part has been addressed. There will be more future enhancements to also cover i.e API breaking changes
