### ISSUE TITLE
Let the operator handle the KubeVirt configuration ConfigMap

### ISSUE THREAD

**Issue by slintes** [kubevirt/kubevirt#1973]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:
Currently users need to create KubeVirt´s configuration ConfigMap before they deploy KubeVirt. Creation or modification of the ConfigMap after deployment will not be picked up by KubeVirt without manual restart of the virt components. 

**What you expected to happen**:
Let the KubeVirt operator handle the ConfigMap and the restart of the virt components.
Properties of the ConfigMap could be part of the KubeVirt custom resource.

**Comment by fabiand** [comment]
Just noting that it's not strictly necessary that the operator is performing this work (IIUIC).

**Comment by MarSik** [comment]
@fabiand It is not necessary but it makes sense. The operator really could make the deployment and configuration atomic. And even handle changes by restarting the right controllers for example.

**Comment by phoracek** [comment]
@slintes ahead of his time!
