### ISSUE TITLE
Sometime virt-controller crashes

### ISSUE THREAD

**Issue by cynepco3hahue** [kubevirt/kubevirt#1984]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Under the job https://jenkins.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/3351//artifact/check-patch.openshift-3.11-crio.el7.x86_64/mock_logs/script/stdout_stderr.log I can see that `virt-controller` failse with the Traceback(the problem that it cut to 15 lines)
```
	/root/go/src/kubevirt.io/kubevirt/pkg/virt-controller/watch/vm.go:225 +0x92a
kubevirt.io/kubevirt/pkg/virt-controller/watch.(*VMController).Execute(0xc000137b20, 0xc00014b100)
	/root/go/src/kubevirt.io/kubevirt/pkg/virt-controller/watch/vm.go:132 +0x10e
kubevirt.io/kubevirt/pkg/virt-controller/watch.(*VMController).runWorker(0xc000137b20)
	/root/go/src/kubevirt.io/kubevirt/pkg/virt-controller/watch/vm.go:122 +0x2b
kubevirt.io/kubevirt/pkg/virt-controller/watch.(*VMController).runWorker-fm()
	/root/go/src/kubevirt.io/kubevirt/pkg/virt-controller/watch/vm.go:114 +0x2a
kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc000d50920)
	/root/go/src/kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:133 +0x54
kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc000d50920, 0x3b9aca00, 0x0, 0x1, 0xc0000a05a0)
	/root/go/src/kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:134 +0xbe
kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc000d50920, 0x3b9aca00, 0xc0000a05a0)
	/root/go/src/kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by kubevirt.io/kubevirt/pkg/virt-controller/watch.(*VMController).Run
	/root/go/src/kubevirt.io/kubevirt/pkg/virt-controller/watch/vm.go:114 +0x204
```

**What you expected to happen**:
`virt-controller` runs without any exceptions

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I will create a PR to increase the number of log lines and will try to catch this issue again.
Because of it test 
```
[Fail] Infrastructure Prometheus Endpoints [It] should be exposed and registered on the metrics endpoint 
/root/go/src/kubevirt.io/kubevirt/tests/infra_test.go:69
```
fails(number of kubevirt system pods do not equal to the number of endpoints under the Prometheus endpoint)

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cynepco3hahue** [comment]
This bug can be related to the problem https://bugzilla.redhat.com/show_bug.cgi?id=1671322

**Comment by fabiand** [comment]
That bug is fixed, closing this issue as well for now.

/close
