### ISSUE TITLE
VM Metric aggregator container

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#2011]
/kind enhancement

#1840 Is introducing a VMI aggregated collector into the virt-handler process. I think the aggregated collector belongs in the virt-handler Pod, but it's possible we should consider moving the aggregator to a separate container within that pod. This would isolate the virt-handler VMI launch flow, migrations, shutdowns, etc... from the aggregated metrics collection. 

The pros of splitting the aggregator out is that it gives us stronger guarantees that metric collection won't impact the rest of our infrastructure.

The cons are that a new container image adds more complexity. It's yet another thing for us to ship which may or may not offer any tangible benefit. 

thoughts?

**Comment by fromanirh** [comment]
I think that the pros in splitting the aggregator in a separate container outweights the costs, and I volunteer for the implementation once PR#1840 is merged.

It is true we add some complexity, but OTOH once we set up properly the pod, the maintenance costs of the separate container are expected to be low (IOW, changes are expected to happen rarely)

**Comment by fromanirh** [comment]
Do we still want this? I can find some capacity to work here, but I think we will need some design
