### ISSUE TITLE
VM Metric aggregator http rate-limiting

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#2012]
/kind enhancement

#1840 introduces an aggregated VMI metrics collector endpoint into the virt-handler component. This endpoint involves reaching into each of the guest's pods to retrieve information from the guest's corresponding libvirt processes. Depending on how many VMIs are running on a node, this isn't an action we'd want to be performing often. 

We need some basic form of project that ensures an external collector (or collectors) can't inadvertently abuse this collection endpoint by making too frequent of calls. This also protects us from anyone who may attempt to profile the VMS using this collection endpoint at too frequent of an interval.

**Comment by rmohr** [comment]
I am not sure I want to see this rate-limiting in the handler. Setting up prometheus properly based on the expected workload is pretty common. People start with fast cycles and then lower the scrape period based on the monitoring results. If we add it it needs to be something like `x requests withing windows y`, to allow parallel scraping for prometheus HA.

**Comment by davidvossel** [comment]
> I am not sure I want to see this rate-limiting in the handler. Setting up prometheus properly based on the expected workload is pretty common. People start with fast cycles and then lower the scrape period based on the monitoring results. 

we shouldn't depend on people to do the right thing here. If we open an interface, we should be defensive and protect it from abuse. 

>If we add it it needs to be something like `x requests withing windows y`, to allow parallel scraping for prometheus HA.

or a response cache that expire after a few seconds

**Comment by rmohr** [comment]
> we shouldn't depend on people to do the right thing here. If we open an interface, we should be defensive and protect it from abuse.

Probably. I think we can just make `MaxRequestsInFlight` and `Timeout` configurable: https://github.com/prometheus/client_golang/blob/cf7da0f4960ed3141a9b02fe3dae2d9d3e8f5641/prometheus/promhttp/http.go#L271 and set sane defaults and should be done.

> or a response cache that expire after a few seconds

That is against the general expectation of prometheus metric endpoints. See also for instance here: https://prometheus.io/docs/instrumenting/writing_exporters/#scheduling

**Comment by fromanirh** [comment]
> > we shouldn't depend on people to do the right thing here. If we open an interface, we should be defensive and protect it from abuse.
> 
> You are right. I think we can just make `MaxRequestsInFlight` configurable: https://github.com/prometheus/client_golang/blob/cf7da0f4960ed3141a9b02fe3dae2d9d3e8f5641/prometheus/promhttp/http.go#L271 and set sane defaults and we should be done.

Sounds like a good idea. How do you want this to be exposed? A command line option?
I volunteer to fix this.

**Comment by davidvossel** [comment]
env var with a default of 1 request a second? @rmohr thoughts?

**Comment by rmohr** [comment]
Can we use a default of 3? env var which sets a command line parameter? We have multiple of those, e.g. pod name, node name, node IP.

**Comment by davidvossel** [comment]
sure, 3 is fine for now. 

> env var which sets a command line parameter? We have multiple of those, e.g. pod name, node name, node IP.

i was thinking we'd avoid the cli arg all together. i really don't care either way though

**Comment by rmohr** [comment]
I just find it easier to track what is configurable to look on defined flags, instead of grepping the code for os.env calls.

**Comment by fromanirh** [comment]
Fine for me. Will start work on this as soon as possible.
