### ISSUE TITLE
AggregationController failed with: ERROR $root is missing required properties: info, swagger

### ISSUE THREAD

**Issue by mlsorensen** [kubevirt/kubevirt#2013]
When running tests with 'make cluster-up' I'm seeing the kubernetes API server continuously requeuing v1alpha3.subresources.kubevirt.io because the response is missing info and swagger properties:

```
I0207 20:03:18.979898       1 controller.go:105] OpenAPI AggregationController: Processing item v1alpha3.subresources.kubevirt.io
I0207 20:03:18.981091       1 controller.go:116] OpenAPI AggregationController: action for item v1alpha3.subresources.kubevirt.io: Requeue.
E0207 20:04:08.320152       1 controller.go:165] updating "v1alpha3.subresources.kubevirt.io" to AggregationController failed with: ERROR $root is missing required properties: info, swagger
```

This doesn't seem to cause any functional issues, but causes unnecessary work for the API server and can be a red herring for troubleshooters when there are cluster issues.

**Comment by davidvossel** [comment]
@mlsorensen what version of kubevirt is this? 

@rmohr wasn't https://github.com/kubevirt/kubevirt/pull/1930 supposed to fix this?

**Comment by rmohr** [comment]
@davidvossel yep it should have. I introduced a new issue where the spec was only served the first time, so after the apiserver was running for some time and tried to re-load the spec it could not get it anymore.
