### ISSUE TITLE
Not all references are valid in the API spec

### ISSUE THREAD

**Issue by sreichar** [kubevirt/kubevirt#2036]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
In the interfaces section of the 13.3 API (not sure about other versions) there are links to following which do not resolve.
- v1.interfaceBrdige
- v1.interfaceMasquerade
- v1.interfaceSlirp
- v1.interfaceSRIOV 

**What you expected to happen**:

Learn about the object types definitions.

**How to reproduce it (as minimally and precisely as possible)**:

Go to https://kubevirt.io/api-reference/v0.13.3/definitions.html#_v1_interface then select any of the 4 mentioned links.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.13.2
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by slintes** [comment]
I think this is caused by empty structs, which result in models without properties in swagger.json, which are ignored by `convertSwagger2markup`. Didn't find a way to fix this yet...

/remove-lifecycle stale

**Comment by Divya063** [comment]
@slintes I would like to work on this.

**Comment by slintes** [comment]
@Divya063 nice, thanks, please coordinate with @rmohr 

/remove-lifecycle stale

**Comment by rmohr** [comment]
That is fixed now with #3357. However, the entries will still looks strange, because they are basically empty structs (https://kubevirt.io/api-reference/master/definitions.html#_v1_interfacebridge). We can in the future add properties to it, but right now, you can selecte them basically by writing something like `bridge: {}`.

**Comment by rmohr** [comment]
/close

Feel free to reopen if you think that this is not fixed.
