### ISSUE TITLE
Some unit tests fail if they are run via bazel

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#2039]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Follow of #1884. If I run the golang unit tests via `bazel test $(bazel query 'kind("go_test rule", //pkg/...)')`, the imageupload tests are failing.

**What you expected to happen**:

That I can run all unit tests via bazel.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cynepco3hahue** [comment]
Hm problem that under the test we use
`imagePath    = "../../../vendor/kubevirt.io/containerized-data-importer/tests/images/cirros-qcow2.img"`
that does not exist under the bazel sandbox, I will need to check the way to pass additional data to the test.
