### ISSUE TITLE
Functional tests fail when a cluster doesn't have a node called "node01"

### ISSUE THREAD

**Issue by dollierp** [kubevirt/kubevirt#2048]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind enhancement

**What happened**:

Ran the KubeVirt test suite (i.e: tests from tests/ folder in kubevirt repository) on a kubevirt cluster, providing a kubeconfig customized for it.

Several tests fail because they try to connect to a node called "node01" (hardcoded in `utils.go` and `vmi_configuration_test.go`) whereas the tested cluster nodes have other hostnames.

**What you expected to happen**:

We need a way to modify the "node01" hostname. Either programmatically by getting the hostnames of the nodes of the cluster, or by providing a command line flag allowing to override value.

**How to reproduce it (as minimally and precisely as possible)**:

Run KubeVirt test suite providing a kubeconfig pointing to a cluster having no nodes called "node01".

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.13.3
- Kubernetes version (use `kubectl version`): v1.11.1
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tareqalayan** [comment]
https://github.com/kubevirt/kubevirt/pull/2054

@fabiand can u assign it to me

**Comment by cynepco3hahue** [comment]
@tareqalayan I think you can use
/assign tareqalayan
