### ISSUE TITLE
Add sync mechanism for sidecars

### ISSUE THREAD

**Issue by mkoderer** [kubevirt/kubevirt#2053]
**FEATURE REQUEST**:

/kind enhancement

**What happened**:
Sidecar are not informed for annotation updates. E.g. the smbios example could react on annotation changes and change the libvirt xml accordingly.

**What you expected to happen**:

Enhance the hooks interface.

**Comment by fabiand** [comment]
@mkoderer thanks for the RFE is this something you - or somebody you know - could take care of?

**Comment by mkoderer** [comment]
@fabiand you can assigned it to me. I am already working on it.

**Comment by fabiand** [comment]
@mkoderer can you try to comment with /assign to self-assign?
