### ISSUE TITLE
Kubevirt won't run on current minikube: Missing /dev/vhost-net driver

### ISSUE THREAD

**Issue by markllama** [kubevirt/kubevirt#2056]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug
> /kind enhancement

**What happened**:

Attempting to run kubevirt on minikube
Starting a VM results in the VM hanging in the "Scheduling" state with the condition note:
    0/1 nodes are available: 1 Insufficient devices.kubevirt.io/vhost-net.

**What you expected to happen**:

testvm schedules and runs

**How to reproduce it (as minimally and precisely as possible)**:

download minikube 0.34.1, docker-machine-driver-kvm2 0.31.0 (avoids bugs in later kvm2 drivers)

minikube start --vm-driver kvm2 --network-plugin cni --enable-default-cni

kubectl create \
    -f https://github.com/kubevirt/kubevirt/releases/download/v0.14.0/kubevirt.yaml

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):

````
Client Version: version.Info{GitVersion:"v0.14.0", GitCommit:"99129b309dae399061d38924744ded0ec0ea72c9", GitTreeState:"clean", BuildDate:"2019-02-04T13:49:57Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.14.0", GitCommit:"99129b309dae399061d38924744ded0ec0ea72c9", GitTreeState:"clean", BuildDate:"2019-02-04T13:49:57Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
````

- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications: bare metal

- Cloud provider or hardware configuration: bare metal

- OS (e.g. from /etc/os-release):

NAME="Red Hat Enterprise Linux Server"
VERSION="7.6 (Maipo)"

- Kernel (e.g. `uname -a`):

Linux hp-blade15.cloud.lab.eng.bos.redhat.com 3.10.0-957.1.3.el7.x86_64 #1 SMP Thu Nov 15 17:36:42 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by karmab** [comment]
the minikube vm which is used as node actually lacks the vhost-net module, which appears to have become a hard requirement now

**Comment by lkpdn** [comment]
IMHO it's not much harm adding `vhost-net` to minikube iso, at least with respect to iso size. The difference should be less than 100KB, while the size of minikube-v0.34.0.iso is about 185MB.
```diff
diff --git a/deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig b/deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig
index 311e798f68d4..067bf6a59776 100644                                                                                                                                              
--- a/deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig
+++ b/deploy/iso/minikube-iso/board/coreos/minikube/linux_defconfig
@@ -326,6 +326,7 @@ CONFIG_IPVLAN=m
 CONFIG_VXLAN=y
 CONFIG_NETCONSOLE=y
 CONFIG_TUN=y
+CONFIG_TAP=y
 CONFIG_VETH=y
 CONFIG_VIRTIO_NET=y
 CONFIG_AMD8111_ETH=m
@@ -487,4 +488,6 @@ CONFIG_CRYPTO_USER_API_HASH=y
 CONFIG_KVM=m
 CONFIG_KVM_INTEL=m
 CONFIG_KVM_AMD=m
+CONFIG_VHOST_NET=m
+CONFIG_VHOST=m
 CONFIG_VHOST_VSOCK=m
```

Just curious but what makes it a hard requirement?
In any case, setting `useEmulation` to true might be the quickest workaround.

**Comment by karmab** [comment]
you re right, with useEmulation, the vm boots fine.
opened https://github.com/kubernetes/minikube/pull/3758 with the proposed change in minikube iso

**Comment by lkpdn** [comment]
thanks!

**Comment by lkpdn** [comment]
@mareklibra seems that we can close this ;)
