### ISSUE TITLE
Unable to push images anywhere but localhost:5000 with bazel-push-images

### ISSUE THREAD

**Issue by j-griffith** [kubevirt/kubevirt#2087]
/kind bug

**What happened**:

I was trying to spin up the latest kubevirt to test live-migration against my multi-node cluster with a CSI backend.  I ran into some problems:
1. The environment variables have changed from DOCKER_PREFIX and DOCKER_TAG to CONTAINER_PREFIX and CONTAINER_TAG (I have not problem there, and am happy to update docs)
2. My images stored in Dockerhub were not being updated, so when I tried to deploy kubevirt the containers were failing, turns out the new tag I built and pushed (or thought I pushed) never actually made it to my registry

**What you expected to happen**:
Images should build, be pushed to my specified registry and make cluster-deploy/sync should work, resulting in a usable kubevirt deployment.

**How to reproduce it (as minimally and precisely as possible)**:
You can go direct to the problem and try to build/push images using the Makefile to see the problem:
```
CONTAINER_PREFIX=quay.io<repo-name> CONTAINER_TAG=latest make bazel-push-images
```

This may or may not run for a very long time, and it creates all the empty repos for us in quay.io, but eventually (approximately 90 minutes in my case) it errors out:

```
Starting local Bazel server and connecting to it...
INFO: Invocation ID: cadfa533-d46c-42b1-90a4-62e08d52e18e
DEBUG: /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/bazel_skylib/skylark_library.bzl:23:1: WARNING: skylark_library.bzl is deprecated and will go away in the future, please use bzl_library.bzl instead.
INFO: Analysed target //:push-images (543 packages loaded, 13139 targets configured).
INFO: Found 1 target...
Target //:push-images up-to-date:
  bazel-bin/push-images
INFO: Elapsed time: 56.819s, Critical Path: 15.59s
INFO: 0 processes.
INFO: Build completed successfully, 18 total actions
INFO: Build completed successfully, 18 total actions
E0305 21:05:34.742296     234 docker_session_.py:329] Error during upload of: quay.io/jgriffith/virt-operator:latest
F0305 21:05:34.743083     234 fast_pusher_.py:186] Error publishing quay.io/jgriffith/virt-operator:latest: response: {'status': '415', 'content-length': '131', 'server': 'nginx/1.14.2', 'connection': 'keep-alive', 'date': 'Tue, 05 Mar 2019 21:05:34 GMT', 'content-type': 'application/json'}
manifest invalid: {u'message': u'manifest schema version not supported'}
E0305 21:06:41.509612     241 docker_session_.py:329] Error during upload of: quay.io/jgriffith/cdi-http-import-server:latest
F0305 21:06:41.510391     241 fast_pusher_.py:186] Error publishing quay.io/jgriffith/cdi-http-import-server:latest: response: {'status': '415', 'content-length': '131', 'server': 'nginx/1.14.2', 'connection': 'keep-alive', 'date': 'Tue, 05 Mar 2019 21:06:41 GMT', 'content-type': 'application/json'}
manifest invalid: {u'message': u'manifest schema version not supported'}
E0305 21:07:44.320727     239 docker_session_.py:329] Error during upload of: quay.io/jgriffith/example-hook-sidecar:latest
F0305 21:07:44.322066     239 fast_pusher_.py:186] Error publishing quay.io/jgriffith/example-hook-sidecar:latest: response: {'status': '415', 'content-length': '131', 'server': 'nginx/1.14.2', 'connection': 'keep-alive', 'date': 'Tue, 05 Mar 2019 21:07:44 GMT', 'content-type': 'application/json'}
manifest invalid: {u'message': u'manifest schema version not supported'}
E0305 21:09:28.605422     227 docker_session_.py:329] Error during upload of: quay.io/jgriffith/subresource-access-test:latest
F0305 21:09:28.606499     227 fast_pusher_.py:186] Error publishing quay.io/jgriffith/subresource-access-test:latest: response: {'status': '415', 'content-length': '131', 'server': 'nginx/1.14.2', 'connection': 'keep-alive', 'date': 'Tue, 05 Mar 2019 21:09:28 GMT', 'content-type': 'application/json'}
manifest invalid: {u'message': u'manifest schema version not supported'}
E0305 21:09:38.217972     238 docker_session_.py:329] Error during upload of: quay.io/jgriffith/vm-killer:latest
F0305 21:09:38.218991     238 fast_pusher_.py:186] Error publishing quay.io/jgriffith/vm-killer:latest: response: {'status': '415', 'content-length': '131', 'server': 'nginx/1.14.2', 'connection': 'keep-alive', 'date': 'Tue, 05 Mar 2019 21:09:38 GMT', 'content-type': 'application/json'}
manifest invalid: {u'message': u'manifest schema version not supported'}
E0305 21:09:58.948254     235 docker_session_.py:329] Error during upload of: quay.io/jgriffith/virt-api:latest
F0305 21:09:58.949028     235 fast_pusher_.py:186] Error publishing quay.io/jgriffith/virt-api:latest: response: {'status': '415', 'content-length': '131', 'server': 'nginx/1.14.2', 'connection': 'keep-alive', 'date': 'Tue, 05 Mar 2019 21:09:58 GMT', 'content-type': 'application/json'}
manifest invalid: {u'message': u'manifest schema version not supported'}
E0305 21:10:14.150182     226 docker_session_.py:329] Error during upload of: quay.io/jgriffith/cirros-container-disk-demo:latest
F0305 21:10:14.151818     226 fast_pusher_.py:186] Error publishing quay.io/jgriffith/cirros-container-disk-demo:latest: response: {'status': '415', 'content-length': '131', 'server': 'nginx/1.14.2', 'connection': 'keep-alive', 'date': 'Tue, 05 Mar 2019 21:10:14 GMT', 'content-type': 'application/json'}
manifest invalid: {u'message': u'manifest schema version not supported'}
E0305 21:10:29.285768     240 docker_session_.py:329] Error during upload of: quay.io/jgriffith/alpine-container-disk-demo:latest
F0305 21:10:29.286844     240 fast_pusher_.py:186] Error publishing quay.io/jgriffith/alpine-container-disk-demo:latest: response: {'status': '415', 'content-length': '131', 'server': 'nginx/1.14.2', 'connection': 'keep-alive', 'date': 'Tue, 05 Mar 2019 21:10:29 GMT', 'content-type': 'application/json'}
manifest invalid: {u'message': u'manifest schema version not supported'}
E0305 21:10:37.210177     228 docker_session_.py:329] Error during upload of: quay.io/jgriffith/container-disk-v1alpha:latest
F0305 21:10:37.211122     228 fast_pusher_.py:186] Error publishing quay.io/jgriffith/container-disk-v1alpha:latest: response: {'status': '415', 'content-length': '131', 'server': 'nginx/1.14.2', 'connection': 'keep-alive', 'date': 'Tue, 05 Mar 2019 21:10:37 GMT', 'content-type': 'application/json'}
manifest invalid: {u'message': u'manifest schema version not supported'}
make: *** [Makefile:16: bazel-push-images] Error 1
```

I'm not sure what to specify here for Dockerhub, using just the repo name like we used to won't work, because bazel needs a domain, I've tried a number of docker domains here (dockerhub.com) but honestly I have no idea which one I should actually use here and they all seem to result in various errors including retries followed by publish errors (no error codes).

Finally, the other option (and my preferred option) is to use a private registry; but when using a private registry with self-signed certs the build container doesn't have access or know about my `/etc/docker/certs.d` directory, so that doesn't work.

**Anything else we need to know?**:
I think I can probably work around this by just pushing to a locahost:5000 repo, then pull, tag and push to my repo via a script.  I also plan to try setting up a public repo with valid certs to see if the behavior is any different.

**Environment**:
- KubeVirt version (use `virtctl version`):
current master

- Kubernetes version (use `kubectl version`):

- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
NAME=Fedora
VERSION="29 (Workstation Edition)"
ID=fedora
VERSION_ID=29
VERSION_CODENAME=""
PLATFORM_ID="platform:f29"
PRETTY_NAME="Fedora 29 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:29"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f29/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=29
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=29
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation

- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cynepco3hahue** [comment]
@j-griffith So do push to docker you need for example use format
`CONTAINER_PREFIX=index.docker.io/you_repository CONTAINER_TAG=latest make bazel-push-images`
And please be sure that you have credentials to do it, `builder` container mount the directory `$HOME/.docker`, so this directory must exist and should have `config.json` file with all relevant credentials.

You can try to push to quay with hacking BUILD file(I will create PR to provide relevant targets for quay)
```
load(
    "@io_bazel_rules_docker//contrib:push-all.bzl",
    "docker_push",
    "oci_push",
)

oci_push(
    name = "push-images",
    bundle = ":build-images",
)
```
and after run ``CONTAINER_PREFIX=quay.io/you_repository CONTAINER_TAG=latest make bazel-push-images``

**Comment by cynepco3hahue** [comment]
@j-griffith Ok update, with OCI pushing to the quay still does not work with the same error
```
...
E0306 07:43:34.972882    1606 docker_session_.py:329] Error during upload of: quay.io/alukiano/container-disk-v1alpha:latest
F0306 07:43:34.973196    1606 fast_pusher_.py:186] Error publishing quay.io/alukiano/container-disk-v1alpha:latest: response: {'status': '415', 'content-length': '131', 'server': 'nginx/1.14.2', 'connection': 'keep-alive', 'date': 'Wed, 06 Mar 2019 07:43:34 GMT', 'content-type': 'application/json'}
manifest invalid: {u'message': u'manifest schema version not supported'}
make: *** [Makefile:24: bazel-push-images] Error 1
...
```
Looks like quay still does not suport OCI version 2.

**Comment by j-griffith** [comment]
@cynepco3hahue 
> @j-griffith So do push to docker you need for example use format
> `CONTAINER_PREFIX=index.docker.io/you_repository CONTAINER_TAG=latest make bazel-push-images`
 
Unfortunately I tried that, the result is:

```
hack/dockerized "bazel run \
	--platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 \
	--workspace_status_command=./hack/print-workspace-status.sh \
	--define container_prefix=index.docker.io/jgriffith \
	--define container_tag=latest \
	//:push-images"
Sending build context to Docker daemon  3.584kB
Step 1/7 : FROM kubevirt/builder@sha256:cd662847df816a0c5cf1a99dcb905301d305befe93d50bee8d00fdd5c74beb19
 ---> 75f2ffedcf24
Step 2/7 : ENV GIMME_GO_VERSION=1.11.5
 ---> Using cache
 ---> ef4e8903d484
Step 3/7 : ENV GOPATH="/go" GOBIN="/usr/bin"
 ---> Using cache
 ---> d15b3e0c80cb
Step 4/7 : RUN     mkdir -p /go &&     source /etc/profile.d/gimme.sh &&     go get github.com/mattn/goveralls &&     go get -u github.com/Masterminds/glide &&     go get -u github.com/golang/mock/gomock &&     go get -u github.com/rmohr/mock/mockgen &&     go get -u github.com/rmohr/go-swagger-utils/swagger-doc &&     go get -u github.com/onsi/ginkgo/ginkgo
 ---> Using cache
 ---> 8b99553740b5
Step 5/7 : RUN pip install j2cli
 ---> Using cache
 ---> 760b7a383965
Step 6/7 : COPY rsyncd.conf /etc/rsyncd.conf
 ---> Using cache
 ---> 7ddd5c68f2b7
Step 7/7 : ENTRYPOINT [ "/entrypoint.sh" ]
 ---> Using cache
 ---> 728500658bb0
Successfully built 728500658bb0
Successfully tagged kubevirt:latest
go version go1.11.5 linux/amd64

JDG RUNNING COMMAND: bazel run 	--platforms=@io_bazel_rules_go//go/toolchain:linux_amd64 	--workspace_status_command=./hack/print-workspace-status.sh 	--define container_prefix=index.docker.io/jgriffith 	--define container_tag=latest 	//:push-images
go version go1.11.5 linux/amd64
Starting local Bazel server and connecting to it...
INFO: Invocation ID: 1ff8e3e1-0756-4b6f-a6d3-a5af37dce6a3
DEBUG: /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/bazel_skylib/skylark_library.bzl:23:1: WARNING: skylark_library.bzl is deprecated and will go away in the future, please use bzl_library.bzl instead.
INFO: Analysed target //:push-images (543 packages loaded, 13139 targets configured).
INFO: Found 1 target...
Target //:push-images up-to-date:
  bazel-bin/push-images
INFO: Elapsed time: 60.066s, Critical Path: 19.47s
INFO: 0 processes.
INFO: Build completed successfully, 18 total actions
INFO: Build completed successfully, 18 total actions
E0306 15:04:39.254957     226 docker_session_.py:329] Error during upload of: index.docker.io/jgriffith/example-hook-sidecar:latest
F0306 15:04:39.255690     226 fast_pusher_.py:186] Error publishing index.docker.io/jgriffith/example-hook-sidecar:latest: Unable to find the server at index.docker.io
```
For reference using `docker.io` also results in errors (301 errors)

```
go version go1.11.5 linux/amd64
Starting local Bazel server and connecting to it...
INFO: Invocation ID: a3ad9cf4-b08e-41e1-8f0b-8c8737a3e01c
DEBUG: /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/bazel_skylib/skylark_library.bzl:23:1: WARNING: skylark_library.bzl is deprecated and will go away in the future, please use bzl_library.bzl instead.
INFO: Analysed target //:push-images (543 packages loaded, 13139 targets configured).
INFO: Found 1 target...
Target //:push-images up-to-date:
  bazel-bin/push-images
INFO: Elapsed time: 50.242s, Critical Path: 17.91s
INFO: 0 processes.
INFO: Build completed successfully, 18 total actions
INFO: Build completed successfully, 18 total actions
E0305 23:02:56.234972     238 docker_session_.py:329] Error during upload of: docker.io/jgriffith/fedora-cloud-container-disk-demo:latest
F0305 23:02:56.235209     238 fast_pusher_.py:186] Error publishing docker.io/jgriffith/fedora-cloud-container-disk-demo:latest: response: {'status': '301', 'content-length': '0', 'location': 'https://www.docker.com/v2/jgriffith/fedora-cloud-container-disk-demo/blobs/uploads/'}
: None
E0305 23:02:56.300276     235 docker_session_.py:329] Error during upload of: docker.io/jgriffith/container-disk-v1alpha:latest
F0305 23:02:56.300498     235 fast_pusher_.py:186] Error publishing docker.io/jgriffith/container-disk-v1alpha:latest: response: {'status': '301', 'content-length': '0', 'location': 'https://www.docker.com/v2/jgriffith/container-disk-v1alpha/blobs/uploads/'}
: None
```

Finally, trying to use my self-signed cert registry, results in SSL errors (as already noted), and I don't know how this could work given the dependency on docker and /etc/docker/certs.d.

In other words, the only thing I can get to work is `localhost:5000`

**Comment by slintes** [comment]
Is there any chance that your attempt with `index.docker.io` was a temporary network hickup only? The error `Unable to find the server at index.docker.io` sounds a bit like it. And we are using `index.docker.io` e.g. on every PR merge on Travis, see https://github.com/kubevirt/kubevirt/blob/master/.travis.yml#L30

**Comment by j-griffith** [comment]
> Is there any chance that your attempt with `index.docker.io` was a temporary network hickup only? The error `Unable to find the server at index.docker.io` sounds a bit like it. And we are using `index.docker.io` e.g. on every PR merge on Travis, see https://github.com/kubevirt/kubevirt/blob/master/.travis.yml#L30

It's certainly possible, although I've run this multiple times at this point without success.  Maybe it's latency on my garbage ISP?  I can try and spin this up in my GCP instance and see what happens there.

**Comment by j-griffith** [comment]
Awesome!  So after @slintes suggestion I moved to a GCP instance and ran from there, it worked perfectly, multiple times.  So, I guess there's some sensitivity to latency or perhaps I completely broke my kubevirt build containers while trying to hack something up for self-signed certs?

Either way, seems like I should close this since there's wip for quay, and perhaps just add an enhancement request for private-registries with self-signed certs?

**Comment by slintes** [comment]
sounds like a plan to me

**Comment by rmohr** [comment]
@j-griffith that seems to be mostly resolved? Is this now an enhancement request for self-signed certs on private registries?

**Comment by j-griffith** [comment]
There have been a lot of really great updates to this flow; it's working great now, reliable and speedy.  Will open an enhancement for self-signed certs.  Thanks @rmohr and everyone!

**Comment by slintes** [comment]
Hey John, did you go on with experiments, using a registry with self signed certs? Asking for #2264 

@j-griffith 
@yu2003w fyi

**Comment by j-griffith** [comment]
@slintes I did experiment with this quite a bit and I did  not have any luck; I never figured out how to get my docker config read in.  I was going to come back to that at some point but never did.  Yes, same issue as #2264 , but once everything else was working this wasn't as critical for me any longer.

**Comment by slintes** [comment]
ack, thx
