### ISSUE TITLE
Kubevirt will appear after deleting apiservice, and it will not be deleted, which will cause kube-service-catalog controller-manager-4fjdb to hang.

### ISSUE THREAD

**Issue by cherishzjx** [kubevirt/kubevirt#2090]
[root@master ~]# oc logs controller-manager-4fjdb -n kube-service-catalog
I0306 07:54:21.272619       1 feature_gate.go:194] feature gates: map[OriginatingIdentity:true]
I0306 07:54:21.272840       1 feature_gate.go:194] feature gates: map[OriginatingIdentity:true AsyncBindingOperations:true]
I0306 07:54:21.272872       1 feature_gate.go:194] feature gates: map[AsyncBindingOperations:true NamespacedServiceBroker:true OriginatingIdentity:true]
I0306 07:54:21.272897       1 hyperkube.go:192] Service Catalog version v3.11.0+58d854a-38;Upstream:v0.1.35 (built 2018-10-19T16:26:14Z)
I0306 07:54:21.278768       1 leaderelection.go:185] attempting to acquire leader lease  kube-service-catalog/service-catalog-controller-manager...
I0306 07:54:21.304165       1 leaderelection.go:194] successfully acquired lease kube-service-catalog/service-catalog-controller-manager
I0306 07:54:21.305160       1 event.go:221] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"kube-service-catalog", Name:"service-catalog-controller-manager", UID:"beb8d7d6-1004-11e9-afce-005056a861b9", APIVersion:"v1", ResourceVersion:"14330337", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' controller-manager-4fjdb-external-service-catalog-controller became leader

which will cause kube-service-catalog controller-manager-4fjdb to hang.
kube-service-catalog                controller-manager-4fjdb                       0/1       CrashLoopBackOff   3695       9d

Kubevirt will appear after deleting apiservice, it can't be deleted.
[root@master ~]# oc delete apiservice v1alpha3.kubevirt.io
apiservice.apiregistration.k8s.io "v1alpha3.kubevirt.io" deleted
[root@master ~]# oc get apiservice |grep kubevirt
v1alpha3.kubevirt.io                   2019-03-06T08:10:09Z

**Comment by cynepco3hahue** [comment]
@cherishzjx Ok I have some remarks
- please use ``` to specify logs, it will make the whole issue more readable for example
```
oc logs controller-manager-4fjdb -n kube-service-catalog
I0306 07:54:21.272619 1 feature_gate.go:194] feature gates: map[OriginatingIdentity:true]
I0306 07:54:21.272840 1 feature_gate.go:194] feature gates: map[OriginatingIdentity:true AsyncBindingOperations:true]
I0306 07:54:21.272872 1 feature_gate.go:194] feature gates: map[AsyncBindingOperations:true NamespacedServiceBroker:true OriginatingIdentity:true]
I0306 07:54:21.272897 1 hyperkube.go:192] Service Catalog version v3.11.0+58d854a-38;Upstream:v0.1.35 (built 2018-10-19T16:26:14Z)
I0306 07:54:21.278768 1 leaderelection.go:185] attempting to acquire leader lease kube-service-catalog/service-catalog-controller-manager...
I0306 07:54:21.304165 1 leaderelection.go:194] successfully acquired lease kube-service-catalog/service-catalog-controller-manager
I0306 07:54:21.305160 1 event.go:221] Event(v1.ObjectReference{Kind:"ConfigMap", Namespace:"kube-service-catalog", Name:"service-catalog-controller-manager", UID:"beb8d7d6-1004-11e9-afce-005056a861b9", APIVersion:"v1", ResourceVersion:"14330337", FieldPath:""}): type: 'Normal' reason: 'LeaderElection' controller-manager-4fjdb-external-service-catalog-controller became leader
```

- I do not see any error message regarding kubevirt under the log
- I believe it recreated because of the operator, so if you want to delete this `apiservice`, you will need to delete the kubevirt operator

**Comment by cherishzjx** [comment]
[root@master kubevirt0.14]# oc delete -f kubevirt-operator.yaml
customresourcedefinition.apiextensions.k8s.io "kubevirts.kubevirt.io" deleted
Error from server (Conflict): error when deleting "kubevirt-operator.yaml": Operation cannot be fulfilled on namespaces "kubevirt": The system is ensuring all content is removed from this namespace.  Upon completion, this namespace will automatically be purged by the system.
Error from server (NotFound): error when deleting "kubevirt-operator.yaml": clusterroles.rbac.authorization.k8s.io "kubevirt.io:operator" not found
Error from server (NotFound): error when deleting "kubevirt-operator.yaml": serviceaccounts "kubevirt-operator" not found
Error from server (NotFound): error when deleting "kubevirt-operator.yaml": clusterrolebindings.rbac.authorization.k8s.io "kubevirt-operator" not found
Error from server (NotFound): error when deleting "kubevirt-operator.yaml": deployments.apps "virt-operator" not found
[root@master kubevirt0.14]# oc delete -f kubevirt-cr.yaml
kubevirt.kubevirt.io "kubevirt" deleted

[root@master ~]# oc get project
NAME                                DISPLAY NAME   STATUS
1111                                               Active
default                                            Active
kube-public                                        Active
kube-service-catalog                               Active
kube-system                                        Active
kubevirt                                           Terminating

how to delete the kubevirt operator as my kubevirt operator pod has been deleted

**Comment by cynepco3hahue** [comment]
@cherishzjx How did you install kubevirt?

**Comment by cherishzjx** [comment]
$ oc adm policy add-scc-to-user privileged -n kubevirt -z kubevirt-operator
$ export VERSION=v0.14.0 
$ kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/$VERSION/kubevirt-operator.yaml 
$ kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/$VERSION/kubevirt-cr.yaml

**Comment by cynepco3hahue** [comment]
@cherishzjx To delete you need to run commands in the reverse order
```
oc delete -f kubevirt-cr.yaml
oc delete -f kubevirt-operator.yaml
```
Let's try to restore your environment, can you show me
```
oc -n kubevirt describe kv kubevirt

**Comment by cherishzjx** [comment]
[root@master kubevirt0.14]# oc -n kubevirt describe kv kubevirt
Name:         kubevirt
Namespace:    kubevirt
Labels:       <none>
Annotations:  kubectl.kubernetes.io/last-applied-configuration={"apiVersion":"kubevirt.io/v1alpha3","kind":"KubeVirt","metadata":{"annotations":{},"name":"kubevirt","namespace":"kubevirt"},"spec":{"imagePullPolicy"...
API Version:  kubevirt.io/v1alpha3
Kind:         KubeVirt
Metadata:
  Creation Timestamp:             2019-02-22T08:51:31Z
  Deletion Grace Period Seconds:  0
  Deletion Timestamp:             2019-03-06T09:29:09Z
  Finalizers:
    foregroundDeleteKubeVirt
  Generation:        2
  Resource Version:  14341470
  Self Link:         /apis/kubevirt.io/v1alpha3/namespaces/kubevirt/kubevirts/kubevirt
  UID:               0ca298f2-367f-11e9-83eb-005056a861b9
Spec:
  Image Pull Policy:  IfNotPresent
Status:
  Conditions:
    Last Probe Time:           2019-02-22T08:52:10Z
    Last Transition Time:      <nil>
    Message:                   All resources were created.
    Reason:                    AllResourcesCreated
    Status:                    True
    Type:                      Created
    Last Probe Time:           2019-02-22T09:04:50Z
    Last Transition Time:      <nil>
    Message:                   All components are ready.
    Reason:                    AllComponentsReady
    Status:                    True
    Type:                      Ready
  Observed Kube Virt Version:  v0.14.0
  Operator Version:            v0.14.0
  Phase:                       Deployed
  Target Kube Virt Version:    v0.14.0
Events:                        <none>

**Comment by cynepco3hahue** [comment]
@cherishzjx Ok can you manually delete finalizer from `kv` resource
`oc edit -n kubevirt kv kubevirt` and delete finalizer related lines, it should help to remove namespace

**Comment by cherishzjx** [comment]
Thank you very much, thank you, you can delete it.

**Comment by cynepco3hahue** [comment]
@cherishzjx Can I close the issue?

**Comment by cherishzjx** [comment]
ok
