### ISSUE TITLE
Pod Network Interface can not assign IPV4 Address

### ISSUE THREAD

**Issue by lxs137** [kubevirt/kubevirt#2092]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
I want to use bridge network with virtio in my vm, my config is:
```yaml
...
interfaces:
- name: default
   model: virtio
   bridge: {}
...
networks:
- name: default
   pod: 
     vmNetworkCIDR: "192.168.100.0/24"
```
when I attach into virt-launcher container, `ip a` command show:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if82: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master k6t-eth0 state UP group default 
    link/ether 0a:58:0a:e5:c7:dc brd ff:ff:ff:ff:ff:ff link-netnsid 0
4: k6t-eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether 0a:58:0a:e5:c7:dc brd ff:ff:ff:ff:ff:ff
    inet 169.254.75.10/32 brd 169.254.75.10 scope global k6t-eth0
       valid_lft forever preferred_lft forever
5: vnet0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc fq_codel master k6t-eth0 state UNKNOWN group default qlen 1000
    link/ether fe:58:0a:f4:00:47 brd ff:ff:ff:ff:ff:ff
```
The `eth0` NIC is created by kubernetes pod network, but I found it hasn't assigned ipv4 address. When I found reason in source code, I found:
https://github.com/kubevirt/kubevirt/blob/6ae065acd7df8e97f52f289d057e8af69e9d2184/pkg/virt-launcher/virtwrap/network/podinterface.go#L235-L238
So is there any `special reason` to delete the address?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.14.0", GitCommit:"99129b309dae399061d38924744ded0ec0ea72c9", GitTreeState:"clean", BuildDate:"2019-02-04T13:49:57Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{GitVersion:"v0.14.0", GitCommit:"99129b309dae399061d38924744ded0ec0ea72c9", GitTreeState:"clean", BuildDate:"2019-02-04T13:49:57Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T15:22:13Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): `Ubuntu 18.04.2 LTS`
- Kernel (e.g. `uname -a`):`4.15.0-45-generic`
- Install tool
- Others:

**Comment by SchSeba** [comment]
Hi @lxs137 `vmNetworkCIDR` works with masquerade network type.

with the bridge interface type the ip from the pod is delegated to the virtual machine.

**Comment by SchSeba** [comment]
you can try to console into the vm using `virtctl console <vm-name>` and the ip address will be there in the `eth0`.

**Comment by lxs137** [comment]
THX. The `masquerade` network type is what I needed. Is this `masquerade` network has the 
 same performance as `bridge` network?

**Comment by SchSeba** [comment]
Hi @lxs137 

> Is this masquerade network has the same performance as bridge network?

so the bridge network is just a l2 connection using a linux bridge and the masquerade user the same linux bridge but makes a nat entry for the communication.

The performance should be almost the same with masquerade.

One more think please take a look on the documents about masquerade. 
For traffic to get into the VM you should configure the relevant ports in the vm spec yaml file.

**Comment by lxs137** [comment]
THX

**Comment by SchSeba** [comment]
@lxs137 no problem :)

If you find any performance issue please open an issue and I will take a look :)
