### ISSUE TITLE
virt-handler metrics do not integrate any k8s VMI properties (labels, names, etc)

### ISSUE THREAD

**Issue by mikejk8s** [kubevirt/kubevirt#2108]
**Is this a BUG REPORT or FEATURE REQUEST?**:

FEATURE REQUEST

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind enhancement

**What happened**:

We're currently working on exposing the VMI metrics (cpu, mem, net, disk) that come from the virt-handler metrics endpoint. Right now these metrics come directly from the virt-handler pods and the only kubernetes identifiable information is "domain=$name-space_$pod-name" which is the libvirt domain information. We were hoping that these metrics would have identifiable information from the kubernetes metrics api, such as pod_labels, etc. 

I spoke with @rmohr  and he mentioned the intention of kubevirt metrics to integrate nicely with the k8s metrics and asked me to open an issue.

**What you expected to happen**:

I had hoped that VMI identifying information might be passed down into the kubevirt_* metrics, such as the VMI name, VMI namespace, VMI labels, and other relevant k8s spec information. 

**How to reproduce it (as minimally and precisely as possible)**:

Access prometheus on a server running kubevirt with the kubevirt serviceMonitor. Query for and kubevirt_* metrics such as; kubevirt_vm_memory_resident_bytes

The output will be similar to the following;

kubevirt_vm_memory_resident_bytes{domain="golden-images_vm-centos-1",endpoint="metrics",instance="10.3.2.1:8443",job="kubevirt-prometheus-metrics",namespace="kubevirt",pod="virt-handler-c5m4b",service="kubevirt-prometheus-metrics"}

**Anything else we need to know?**:

**Environment**:

- KubeVirt version (use `virtctl version`):
Server Version: version.Info{GitVersion:"v0.15.0-alpha.0", GitCommit:"31d08ef5b6c0170b21f5823d351f43902168e2d5", GitTreeState:"clean", BuildDate:"2019-02-21T11:00:06Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.0", GitCommit:"ddf47ac13c1a9483ea035a79cd7c10005ff21a6d", GitTreeState:"clean", BuildDate:"2018-12-03T20:56:12Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
Baremetal

- OS (e.g. from /etc/os-release):

NAME="CentOS Linux"
VERSION="7 (Core)"

- Kernel (e.g. `uname -a`):

4.13.10-1.el7.elrepo.x86_64

- Install tools:
- Others:

**Comment by fabiand** [comment]
@fromanirh something for you?

**Comment by fromanirh** [comment]
ack! will check this ASAP.

**Comment by rmohr** [comment]
One side-note: We should not add the VMI labels to the prometheus labels. That would not be good for prometheus. Instead, clearly expose `node`, `name` and `namespace` (maybe `uid`). This would allow connecting the dots directly from prometheus. To integrate in the custom metrics api, this info can then be used to back-connect the metrics to the custom metrics api endpoint of the pod, so that it can be used by the autoscalers, ...

**Comment by rmohr** [comment]
@fromanirh do you know if you will get some time to work on this? I think this is a very important limitation right now.

**Comment by fromanirh** [comment]
@rmohr I'll try to squeeze in the upcoming sprint.

**Comment by fromanirh** [comment]
OK, the first step will be to implement what @rmohr proposed in https://github.com/kubevirt/kubevirt/issues/2108#issuecomment-471966831 . I aim to have such a PR posted within this week.

**Comment by rmohr** [comment]
/reopen

@mikejk8s we finally have `name`, `namespace`, and `node`. How desperately do you need labels? @fromanirh do we know if `kubelet` metrics expose pod labels too?

**Comment by rmohr** [comment]
I guess labels are great to monitor distributed or scaleable apps or VMs.

**Comment by fromanirh** [comment]
> /reopen
> 
> @mikejk8s we finally have `name`, `namespace`, and `node`. How desperately do you need labels? @fromanirh do we know if `kubelet` metrics expose pod labels too?

(sorry for late answer) I need to check about kubelet. Do we want to go and add the labels?

**Comment by rmohr** [comment]
/remove-lifecycle rotten

@fromanirh any news?
