### ISSUE TITLE
Document v1.VM and v1.DomainSpec

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#212]
By adding comments to the structs `v1.VM` and `v1.DomainSpec`, the swagger documentation is updated. We miss documentation almost everywhere. This is important, so that we can automatically generate documentation in different formats later on.

**Comment by rmohr** [comment]
Hints on the meaning of the fields can be found here:

https://libvirt.org/formatdomain.html

**Comment by mpolednik** [comment]
The PR #347 mostly documented v1.VM. Given that https://github.com/libvirt/libvirt-go-xml exists and we may eventually switch to it, I think the issue could be reduced to v1.VM documentation. Documenting api.DomainSpec could be wasted, easily outsourced (to the other project) effort.

**Comment by rmohr** [comment]
The field documentation improved a lot for the 0.2.0 release. See https://github.com/kubevirt/kubevirt/blob/master/api/openapi-spec/swagger.json, https://github.com/kubevirt/kubevirt/blob/master/pkg/api/v1/schema.go and https://kubevirt-incubator.github.io/api-reference/content/index.html.
