### ISSUE TITLE
Bazel downloads artifacts too often when switching branches

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#2125]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:

If I switch branches or only minmal changes are switched in the WORKSPACE file, it redownloads a lot. We can prevent that: https://groups.google.com/forum/#!topic/bazel-discuss/_otGfLuHN_Y.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
https://docs.bazel.build/versions/master/remote-caching.html#disk-cache

**Comment by cynepco3hahue** [comment]
@rmohr I think we mostly interested in
- https://docs.bazel.build/versions/master/command-line-reference.html#flag--repository_cache
