### ISSUE TITLE
kubevirt-test test job for kubevirt v0.15.0 on openshift4 failed during [BeforeSuite] 

### ISSUE THREAD

**Issue by pavolbrilla** [kubevirt/kubevirt#2129]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug

**What happened**:
kubevirt-tests failed to be deployed on ocp4 ( libvirt )

**What you expected to happen**:
Tests to be deployed and run.

**How to reproduce it (as minimally and precisely as possible)**:
Create ocp4 cluster ( openshift/installer v0.14.0 ) libvirt
Try to make and run tests

**Anything else we need to know?**:
In fact deployment is failing for manifest: https://github.com/kubevirt/kubevirt/blob/master/manifests/testing/local-block-storage.yaml.in 

node01 is hard-coded there, and in ocp4 nodes are using generated names
we need to be able to inject name of node to test suit

**Environment**:
- KubeVirt version (use `virtctl version`): NA
- Kubernetes version (# kubectl version use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-12-06T18:30:39Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.4+0f8e04e", GitCommit:"0f8e04e", GitTreeState:"clean", BuildDate:"2019-03-04T15:33:19Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
- VM or VMI specifications: none
- Cloud provider or hardware configuration: Baremetal
- OS (e.g. from /etc/os-release): Fedora 29 
- Kernel (e.g. `uname -a`): Linux $HOSTNAME 4.20.14-200.fc29.x86_64 #1 SMP Tue Mar 5 19:55:32 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

ERROR: Can not apply {map[kind:PersistentVolume metadata:map[labels:map[kubevirt.io: blockstorage:cirros] name:local-block-storage-cirros] spec:map[volumeMode:Block accessModes:[ReadWriteOnce] capacity:map[storage:1Gi] local:map[path:/mnt/local-storage/cirros-block-device] nodeAffinity:map[required:map[nodeSelectorTerms:[map[matchExpressions:[map[key:kubernetes.io/hostname operator:In values:[node01]]]]]]] persistentVolumeReclaimPolicy:Retain storageClassName:local-block] apiVersion:v1]}

**Comment by rmohr** [comment]
Hi @pavolbrilla yep, openshift 4 does not support local PVs. I think that's one of the reasons why @dollierp started adding support for reading different configs for our tests in #2116, so that the PVs can be replaced with PVs of a configured storage provider.
