### ISSUE TITLE
Blocked when delete vmi by kubectl

### ISSUE THREAD

**Issue by lxs137** [kubevirt/kubevirt#2138]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug

**What happened**:
I want to delete a vmi by `kubectl delete vmi/<vmi-name>`, but this command has blocked. I found that virt-launcher pod has been deleted successfully, but the vmi's state is `Scheduled` and the vmi can never be deleted.

I check the logs of `kube-apiserver`, I found:
```
rejected by webhook "virtualmachineinstances-update-validator.kubevirt.io": 
&errors.StatusError{ErrStatus:v1.Status{
TypeMeta:v1.TypeMeta{Kind:"", APIVersion:""}, 
ListMeta:v1.ListMeta{SelfLink:"", ResourceVersion:"", Continue:""}, 
Status:"", 
Message:"admission webhook \"virtualmachineinstances-update-validator.kubevirt.io\" denied the request: update of VMI object is restricted", 
Reason:"Invalid", 
Details:(*v1.StatusDetails)(0xc00cd244e0), Code:422}}
```
I found the code in https://github.com/kubevirt/kubevirt/blob/b2e09e8e6c2696daaef428f900ec50005aae1960/pkg/virt-api/webhooks/validating-webhook/validating-webhook.go#L1553-L1561
It seems like to prevent the vmi spec update when vm is already running, should this check work when delete vmi?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.14.0", GitCommit:"99129b309dae399061d38924744ded0ec0ea72c9", GitTreeState:"clean", BuildDate:"2019-02-04T13:49:57Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{GitVersion:"v0.14.0", GitCommit:"99129b309dae399061d38924744ded0ec0ea72c9", GitTreeState:"clean", BuildDate:"2019-02-04T13:49:57Z", GoVersion:"go1.11.2", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"10", GitVersion:"v1.10.4", GitCommit:"5ca598b4ba5abb89bb773071ce452e33fb66339d", GitTreeState:"clean", BuildDate:"2018-06-06T15:22:13Z", GoVersion:"go1.9.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):`Ubuntu 18.04.2 LTS`
- Kernel (e.g. `uname -a`): `4.15.0-45-generic`
- Install tools:
- Others:

**Comment by petrkotas** [comment]
Hi, can you please also post logs from virt-api, virt-handler and virt-launcher?
Which vmi did you run / What OS did you run in the VM? Have you been able to log in to the VM before deleting it? What was the state of the cluster (kubectl get pods --all-namespaces)? 

Thanks for the feedback.

**Comment by lxs137** [comment]
@petrkotas 
To solve this problem temporarily, I have to delete all pods in `kubevirt` namespace. Unfortunately, this bug is hard to reproduce, If I meet the bug next time, I will provide logs from virt-api, virt-handler and virt-launcher.

My VM is [android-x86](http://www.android-x86.org/), it is based on standard linux kernel, actually it works well when vm managed by ibvirt directly.

My android-x86 vm works always well on kubevirt, so I guess the bug is because of some data racing problem?

**Comment by petrkotas** [comment]
Thanks @lxs137 for keeping an eye on this.

**Comment by rmohr** [comment]
@lxs137 did you have running VMIs and updated from e.g. kubevirt 1.13 to 1.14? If yes, we right now  don't support updates with running VMIs. Maybe you had a newer virt-controller and an older virt-api running?

> It seems like to prevent the vmi spec update when vm is already running, should this check work when delete vmi?

Yes that should work for as long as all kubevirt components are on the same version.

**Comment by yonyossef** [comment]
> @petrkotas To solve this problem temporarily, I have to delete all pods in `kubevirt` namespace. Unfortunately, this bug is hard to reproduce, If I meet the bug next time, I will provide logs from virt-api, virt-handler and virt-launcher.
> 
> My VM is [android-x86](http://www.android-x86.org/), it is based on standard linux kernel, actually it works well when vm managed by ibvirt directly.
> 
> My android-x86 vm works always well on kubevirt, so I guess the bug is because of some data racing problem?

Hi, I delete all pods in kubevirt namespace but the vmi still hangs, cannot be deleted. Can you describe how exactly did you kill the vmi?

**Comment by ehudyonasi** [comment]
> > @petrkotas To solve this problem temporarily, I have to delete all pods in `kubevirt` namespace. Unfortunately, this bug is hard to reproduce, If I meet the bug next time, I will provide logs from virt-api, virt-handler and virt-launcher.
> > My VM is [android-x86](http://www.android-x86.org/), it is based on standard linux kernel, actually it works well when vm managed by ibvirt directly.
> > My android-x86 vm works always well on kubevirt, so I guess the bug is because of some data racing problem?
> 
> Hi, I delete all pods in kubevirt namespace but the vmi still hangs, cannot be deleted. Can you describe how exactly did you kill the vmi?

You can always delete the finalizers in the VMI, this will delete it.
