### ISSUE TITLE
Copy vm serial buffer to container console buffer

### ISSUE THREAD

**Issue by jtaleric** [kubevirt/kubevirt#2155]
Feature request

/kind enhancement

**What happened**:
Copy VM serial console output to Container console. 

**What you expected to happen**:

`$ kubectl logs <container>`

This would allow users to simply use `kubectl` to capture log output sent to the vm serial console.

**Comment by booxter** [comment]
One thing to consider here is whether it's always safe to dump guest console to kube logs. It may be that there are secrets in guest console; and that copying them to kube logs exposes them to previously unauthorized users. Secrets may be part of expected boot logs; but they may also belong to interactive getty session running on serial console.

**Comment by kfox1111** [comment]
not without risk, yeah. But in general I think very beneficial.

**Comment by jtaleric** [comment]
> One thing to consider here is whether it's always safe to dump guest console to kube logs. It may be that there are secrets in guest console; and that copying them to kube logs exposes them to previously unauthorized users. Secrets may be part of expected boot logs; but they may also belong to interactive getty session running on serial console.

Could this be mitigated by looking for keywords and ignoring those lines? 

The user can access the container running the VM, but not the VM itself? Not sure how RBAC works in kube that well, but that would seem like a gap -- Allowing a user who cannot access the VM, access the container (in any capacity) running the VM.

**Comment by booxter** [comment]
> > One thing to consider here is whether it's always safe to dump guest console to kube logs. It may be that there are secrets in guest console; and that copying them to kube logs exposes them to previously unauthorized users. Secrets may be part of expected boot logs; but they may also belong to interactive getty session running on serial console.
> 
> Could this be mitigated by looking for keywords and ignoring those lines?
> 

This is prone to errors, isn't it? Your filters are guest specific and could break at any minor change in output. And I would be very hesitant to copy interactive session I/O to logs (for security reasons but also because the amount of the output may be unexpectedly large, depending on the guest.) Is there any need to see console output that is NOT boot messages?

> The user can access the container running the VM, but not the VM itself? Not sure how RBAC works in kube that well, but that would seem like a gap -- Allowing a user who cannot access the VM, access the container (in any capacity) running the VM.

You may be right. I don't know either, so it's something to check. But I can imagine that someone may ask to provide logs of a pod to debug an issue; or one may have a log harvesting solution that could expose the logs to undesired readers.

**Comment by jtaleric** [comment]
> > > One thing to consider here is whether it's always safe to dump guest console to kube logs. It may be that there are secrets in guest console; and that copying them to kube logs exposes them to previously unauthorized users. Secrets may be part of expected boot logs; but they may also belong to interactive getty session running on serial console.
> > 
> > 
> > Could this be mitigated by looking for keywords and ignoring those lines?
> 
> This is prone to errors, isn't it? Your filters are guest specific and could break at any minor change in output. And I would be very hesitant to copy interactive session I/O to logs (for security reasons but also because the amount of the output may be unexpectedly large, depending on the guest.) Is there any need to see console output that is NOT boot messages?

By boot messages, this would include cloudinit output? If so, I think that should suffice... 

> 
> > The user can access the container running the VM, but not the VM itself? Not sure how RBAC works in kube that well, but that would seem like a gap -- Allowing a user who cannot access the VM, access the container (in any capacity) running the VM.
> 
> You may be right. I don't know either, so it's something to check. But I can imagine that someone may ask to provide logs of a pod to debug an issue; or one may have a log harvesting solution that could expose the logs to undesired readers.

**Comment by booxter** [comment]
Yes I mean everything till getty is started.
