### ISSUE TITLE
Kubevirt operator CSV file missing few required fields.

### ISSUE THREAD

**Issue by aneeshkp** [kubevirt/kubevirt#2191]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind enhancement

**What happened**:
I ran operator-courier to verify OLM bundle and the validation failed for missing required fields in CSV file.
```
WARNING:operatorcourier.validate:csv metadata.annotations.containerImage not defined
WARNING:operatorcourier.validate:csv metadata.annotations.createdAt not defined
WARNING:operatorcourier.validate:csv metadata.annotations.support not defined
WARNING:operatorcourier.validate:csv metadata.annotations.certified not defined.
WARNING:operatorcourier.validate:csv metadata.annotations.repository not defined.Without this field, the link to the operator source code will not be displayed in the UI.
WARNING:operatorcourier.validate:csv metadata.annotations.createdAt not defined.Without this field, the time stamp at which the operator was created will not be displayed in the UI.
ERROR:operatorcourier.validate:csv metadata.annotations.containerImage not defined. Without this field, the link to the operator image will not be displayed in the UI.
ERROR:operatorcourier.validate:UI validation failed to verify required fields for operatorhub.io exist.
ERROR:operatorcourier.api:Bundle failed validation.
```
Resulting bundle is invalid, input yaml is improperly defined.

**What you expected to happen**:
operator-courier to verify and pass all the validation resulting valid OLM bundle.

**How to reproduce it (as minimally and precisely as possible)**:
run operator-courier on OLM bundle files
```
operator-courier verify --ui_validate_io _out/
```
**Anything else we need to know?**:
Reference to required  fields document.
https://github.com/operator-framework/community-operators/blob/0a60d5097aea0c669ff57ea2d85304dad76a90d8/docs/required-fields.md
(Note: I have forked community-operator repo and copied  generated kubvirt-operator CSV, package and crd files to the forked repo, and  executed  operator-courier to verify  on the community-operators/kubevirt folder. )
https://github.com/redhat-nfvpe/community-operators/tree/kubevirt-operator/community-operators/kubevirt

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
 pip3 install operator-courier
(https://github.com/operator-framework/operator-courier)
- Others:

**Comment by slintes** [comment]
Thanks @aneeshkp, I wasn't aware of the `--ui_validate_io` flag of `operator-courier verify`. Will provide a fix asap.
