### ISSUE TITLE
Kubevirt and IBM Cloud Private Community Edition 3.1.2 - cannot bring up a test vm 

### ISSUE THREAD

**Issue by ramanavakka** [kubevirt/kubevirt#2205]
**Is this a BUG REPORT or FEATURE REQUEST?**:
At this point - it appears to be a bug

> /kind bug

**What happened**:

Installed IBM Cloud Private 3.1.2 on a 3 node cluster and tried to bring up testvm as per sample in Kubevirt quick start.  The failure points to the following error while creating the VM Instance:

'0/3 nodes are available: 3 Insufficient devices.kubevirt.io/kvm, 3 Insufficient
      devices.kubevirt.io/tun, 3 Insufficient devices.kubevirt.io/vhost-net, 3 node(s)
      didn''t match node selector.'

**What you expected to happen**:
Expected it create a VM. 

**How to reproduce it (as minimally and precisely as possible)**:
Install ICP 3.1.2 Community Edition - https://www.ibm.com/support/knowledgecenter/SSBS6K_3.1.2/installing/install.html?view=kc

Ensure KVM is installed as per direction on the Ubuntu website for 16.04.

Install Kubevirt operator as per quickstart

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
user@ubuntu102:~/icp-312$ ./virtctl version
Client Version: version.Info{GitVersion:"v0.15.0", GitCommit:"432f91f3a2bdb3c2624377ad327270c9e146d845", GitTreeState:"clean", BuildDate:"2019-03-05T08:21:47Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.16.0", GitCommit:"06d91198bededc7a9353ac774221c83580ee3373", GitTreeState:"clean", BuildDate:"2019-04-05T21:41:13Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):

- VM or VMI specifications:

user@ubuntu102:~/icp-312$ kubectl version
Client Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4+icp", GitCommit:"3f5277fa129f05fea532de48284b8b01e3d1ab4e", GitTreeState:"clean", BuildDate:"2019-01-17T13:41:02Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12", GitVersion:"v1.12.4+icp", GitCommit:"3f5277fa129f05fea532de48284b8b01e3d1ab4e", GitTreeState:"clean", BuildDate:"2019-01-17T13:41:02Z", GoVersion:"go1.10.4", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
HW Configuration - 
Xeon D Based System with 3 servers (D15xx) processors.
64 Gig memory 
10G network interface
- OS (e.g. from /etc/os-release):
x86_64 x86_64 GNU/Linux
/etc/os-release
user@ubuntu102:~/icp-312$ cat /etc/os-release
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):
user@ubuntu102:~/icp-312$ uname -a
Linux ubuntu102 4.4.0-142-generic #168-Ubuntu SMP Wed Jan 16 21:00:45 UTC 2019 x86_64 - 

Install tools:
- Others:

**Comment by rmohr** [comment]
@ramanavakka thanks for creating the usse. Could you post the logs of one `virt-handler` pod? Since you already verified that the kernel modules are present, could you also ensure that DevicePlugins are not somehow disabled on the `kubelet` level? It is enabled by default on your version in upstream, but maybe ICP disables them by default.

**Comment by ramanavakka** [comment]
Hi Roman,
Noticed that virt-handler pod is not even running and DevicePlugins are enabled because nvidia plugins are running;

user@ubuntu102:~$ kubectl get pods --all-namespaces | grep virt
cert-manager   virt-launcher-testvm-9g4wv                                     0/2     Pending     0          15h
kubevirt       virt-api-5cf68b8686-ffd4g                                      1/1     Running     0          15h
kubevirt       virt-api-5cf68b8686-q7n29                                      1/1     Running     0          15h
kubevirt       virt-controller-76d69fb979-lbh6h                               1/1     Running     0          15h
kubevirt       virt-controller-76d69fb979-pr2qj                               1/1     Running     0          15h
kubevirt       virt-operator-7b86b457df-g4w7r                                 1/1     Running     0          15h

user@ubuntu102:~$ kubectl get pods --all-namespaces | grep plug
kube-system    k8s-kmsplugin-192.168.20.102                                   1/1     Running     0          16h
kube-system    nvidia-device-plugin-488xz                                     1/1     Running     0          16h
kube-system    nvidia-device-plugin-d2p8b                                     1/1     Running     0          16h
kube-system    nvidia-device-plugin-qj5v7                                     1/1     Running     0          16h

**Comment by ramanavakka** [comment]
Here are the commands to load the kubevirt operator:

export KUBEVIRT_VERSION="v0.16.0"
kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${KUBEVIRT_VERSION}/kubevirt-operator.yaml
kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${KUBEVIRT_VERSION}/kubevirt-cr.yaml

kubectl apply -f https://raw.githubusercontent.com/kubevirt/kubevirt.github.io/master/labs/manifests/vm.yaml

**Comment by rmohr** [comment]
@ramanavakka could you do `kubectl describe -n kubevirt daemonsets`? And if the daemonset does not exist, also `kubectl logs -n kubevirt virt-operator-7b86b457df-g4w7r`?

**Comment by rmohr** [comment]
@davidvossel FYI

**Comment by ramanavakka** [comment]
Hi Roman,

Here is the summary at the end of kubectl describe -n kubevirt daemonsets

Events:
  Type     Reason        Age                      From                  Message
  ----     ------        ----                     ----                  -------
  Warning  FailedCreate  2m36s (x121 over 6h38m)  daemonset-controller  Error creating: pods "virt-handler-" is forbidden: unable to validate against any pod security policy: [spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used spec.volumes[0]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[2]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.volumes[3]: Invalid value: "hostPath": hostPath volumes are not allowed to be used spec.containers[0].securityContext.privileged: Invalid value: true: Privileged containers are not allowed]

===============================
As an experiment, I create a k8s cluster with kubeadm with 2 nodes and tried to do the same:
In this case, I am getting the following error for the command:
kubectl describe pods --all-namespaces

Events:
  Type     Reason     Age                   From                Message
  ----     ------     ----                  ----                -------
  Normal   Scheduled  3m7s                  default-scheduler   Successfully assigned kubevirt/virt-operator-6b7967b5c5-zxzs7 to ubuntu112
  Warning  BackOff    64s (x3 over 2m4s)    kubelet, ubuntu112  Back-off restarting failed container
  Normal   Pulled     52s (x4 over 3m6s)    kubelet, ubuntu112  Container image "index.docker.io/kubevirt/virt-operator:v0.16.0" already present on machine
  Normal   Created    52s (x4 over 3m6s)    kubelet, ubuntu112  Created container virt-operator
  Normal   Started    52s (x4 over 3m6s)    kubelet, ubuntu112  Started container virt-operator
  Warning  Unhealthy  37s (x10 over 2m57s)  kubelet, ubuntu112  Readiness probe failed: Get https://192.168.1.8:8443/metrics: dial tcp 192.168.1.8:8443: connect: connection refused
user@ubuntu114:~$ kubectl

On this setup, I was able to run the nginx deployment and it's working.

**Comment by ramanavakka** [comment]
And to your question about logs:

user@ubuntu102:/opt/ibm-cloud-private-3.1.2/cluster$ kubectl logs -n kubevirt virt-launcher-testvm-mrhq5
Error from server (NotFound): pods "virt-launcher-testvm-mrhq5" not found

However, I do see the pod description:

user@ubuntu102:/opt/ibm-cloud-private-3.1.2/cluster$ kubectl describe pods virt-launcher-testvm-mrhq5         Name:               virt-launcher-testvm-mrhq5
….
Events:
  Type     Reason            Age                  From               Message
  ----     ------            ----                 ----               -------
  Warning  FailedScheduling  48m (x13 over 3h4m)  default-scheduler  0/2 nodes are available: 2 Insufficient devices.kubevirt.io/kvm, 2 Insufficient devices.kubevirt.io/tun, 2 Insufficient devices.kubevirt.io/vhost-net, 2 node(s) didn't match node selector.

**Comment by rmohr** [comment]
@ramanavakka, thanks for all the info. That helps a lot. So I think I can pin down the issues now. The one on the IBM cluster: The PodSecurityPolicy admission controller is enabled there. Our Operator can't handle that right now. We need to add it. You can work around this by allowing the `kubevirt-operator` and `kubevirt-controller` service accounts via a PodSecurityPolicy to create pods with the following criterias:

 * privileged containers allowed
 * hostPath allowed
 * hostPID allowed

Depending on the exact kubevirt setup and VMI spec, it might be necessary to grant additional privileges to `kubevirt-controller`, so that it can create the VMI pod.

@davidvossel, @slintes  we need to add support for PodSecurityPolicy to the operator.

**Comment by slintes** [comment]
Interesting. I never used PSPs before, so I'm just reading about it. Do I understand correctly:

- the operator needs to create PSPs for each component which allows them to do what they need
- and RBAC rules allowing the components to `use` their PSP
- and the operator deployment needs a PSP allowing everything needed by other components (I guess else it won't be able to create the other PSPs)
- and a RBAC rule to `use` that PSP
- and a RBAC rule to `create/update/delete` new PSPs

Does that make sense?

**Comment by rmohr** [comment]
@slintes yes, I think so.

> * and the operator deployment needs a PSP allowing everything needed by other components (I guess else it won't be able to create the other PSPs)

I think here it is **enough** if it can also `use` the PSPs for its component. Although it has the same effect.

**Comment by slintes** [comment]
> @slintes yes, I think so.
> 
> > * and the operator deployment needs a PSP allowing everything needed by other components (I guess else it won't be able to create the other PSPs)
> 
> I think here it is _enough_ if it can also `use` the PSPs for its component. Although it has the same effect.

mh, but those PSPs will be created by the operator when deploying KubeVirt, they are not part of the operator deployment.
Maybe the operator even needs a "(almost) everything allowed" PSP, in order to be able to potentially update to a new KubeVirt version, which  needs more permissions than before.
Mh, we will find out  how this works in detail.

**Comment by kfox1111** [comment]
serviceaccounts need the use property pointing to a podsecuritypolicy that has the permissions needed to do whats needed. basically any pod launched by that serviceaccount needs a podsecurity policy matching the parts of the pod api being used. Think of it kind of like a pod spec filter.

This tripped me up when I implemented them too. For example, Daemonset/Deployment uses the service account listed in the templated pod spec to apply the podsecuritypolicies. not the users permissions that created the daemonset/deployment.

No, I think your confusing rbac and psp's a bit. PodSecurityPolicy covers what features of a pod a pod spec can use. rbac controls what api objects and how that a service account can touch. podspec is much finer grained then rbac but only for pod specs. you use rbac to bind serviceaccounts to allowed psp's.

Thanks,
Kevin
________________________________

**Comment by ramanavakka** [comment]
> @ramanavakka, thanks for all the info. That helps a lot. So I think I can pin down the issues now. The one on the IBM cluster: The PodSecurityPolicy admission controller is enabled there. Our Operator can't handle that right now. We need to add it. You can work around this by allowing the kubevirt-operator and kubevirt-controller service accounts via a PodSecurityPolicy to create pods with the following criterias:
> 
> privileged containers allowed
> hostPath allowed
> hostPID allowed
> 
> Depending on the exact kubevirt setup and VMI spec, it might be necessary to grant additional privileges to kubevirt-controller, so that it can create the VMI pod.
> @davidvossel, @slintes  we need to add support for PodSecurityPolicy to the operator.

IBM Cloud Private 3.1.2 includes default PSPs as part of installation. It has several - two are relevant here:
user@ubuntu102:~/icp-312$ kubectl get psp
NAME   PRIV    CAPS    SELINUX    RUNASUSER          FSGROUP     SUPGROUP    READONLYROOTFS   VOLUMES
ibm-anyuid-hostpath-psp     false    SETPCAP,AUDIT_WRITE,CHOWN,NET_RAW,DAC_OVERRIDE,FOWNER,FSETID,KILL,SETUID,SETGID,NET_BIND_SERVICE,SYS_CHROOT,SETFCAP   RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *
ibm-privileged-psp          true    *     RunAsAny   RunAsAny           RunAsAny    RunAsAny    false            *

By default virt-* uses the ibm-anyuid-hostpath-psp as shown below:

Name:               virt-controller-76d69fb979-26vpn
Annotations:        kubernetes.io/psp: ibm-anyuid-hostpath-psp

So, my question is how to enable ibm-privileged-psp on the kubevirt operartor 

I tried to apply the ibm-privileged-psp via sample given in the kubernetes PSP description. But unable to do so. Maybe I don't understand this enough.. 

Do I need to create kubevirt operators with a newly updated kubevirt-operator.yaml or can I change the psp of kubevirt-controller dynamically?

thanks
--ramana

**Comment by kfox1111** [comment]
I haven't tried it with kubevirt, but you should be able to create a cluster role / role binding with a permission to use your ibm-privileged-psp and bound to the service accounts kubevirt uses.

Thanks,
Kevin
________________________________

**Comment by ramanavakka** [comment]
> @ramanavakka, thanks for all the info. That helps a lot. So I think I can pin down the issues now. The one on the IBM cluster: The PodSecurityPolicy admission controller is enabled there. Our Operator can't handle that right now. We need to add it. You can work around this by allowing the kubevirt-operator and kubevirt-controller service accounts via a PodSecurityPolicy to create pods with the following criterias:
> 
> privileged containers allowed
> hostPath allowed
> hostPID allowed
> 
> Depending on the exact kubevirt setup and VMI spec, it might be necessary to grant additional privileges to kubevirt-controller, so that it can create the VMI pod.
> @davidvossel, @slintes  we need to add support for PodSecurityPolicy to the operator.

Hi Roman,

I started to look into how to add

**Comment by ramanavakka** [comment]
All:

I have been able to run a testvm with the following sequence on ICP 3.1.2 

1. ICP - installed by changing the image_security_enforcement to false in the cluster.yaml configuration option. ICP provides several PSP by default in this release 3.1.2 - we need ibm-privileged-psp.
2. Once it is installed, create the kubevirt namespace first
3. kubectl -n kubevirt create rolebinding ibm-privileged-rolebinding --clusterrole=ibm-privileged-clusterrole --group=system:serviceaccounts:kubevirt
4. Now apply the kubevirt-operator.yaml - it will complain about the namespace already being present
5.  Then apply the kubevirt-cr.yaml 
6. Now do the normal creation of testvm creation and running it. 
Enclosing the commands of what is done for reference. 
[icp-kubevirt-works-commands.txt](https://github.com/kubevirt/kubevirt/files/3129011/icp-kubevirt-works-commands.txt)

Thanks for all your help..
--ramana

**Comment by cynepco3hahue** [comment]
@ramanavakka Do you have to create a PR that will document in details how to W/A this problem on the ICP I believe it can help if someone will encounter the same problem

**Comment by rmohr** [comment]
@ramanavakka thanks for the update. I created #2221, so that we don't forget  to add PSP support.
