### ISSUE TITLE
virtctl just hangs when trying to connect to vm

### ISSUE THREAD

**Issue by bharatnc** [kubevirt/kubevirt#2209]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:

I did `virtctl console testvm` to interact with my vm.

**What you expected to happen**:

To drop down into the login shell. Instead it just got stuck in this: 
Successfully connected to 131m9 console. The escape sequence is ^]
Despite pressing enter it doesn't get past this.

I verified the VM worked as I was able to do `virtctl vnc testvm` and was able to interact with VM just fine. Am I missing to expose some tty port while building my custom VM ISO using linuxkit?

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
```
./virtctl version
Client Version: version.Info{GitVersion:"v0.16.0", GitCommit:"06d91198bededc7a9353ac774221c83580ee3373", GitTreeState:"clean", BuildDate:"2019-04-05T15:24:49Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.15.0-alpha.0", GitCommit:"31d08ef5b6c0170b21f5823d351f43902168e2d5", GitTreeState:"clean", BuildDate:"2019-02-21T11:00:06Z", GoVersion:"go1.11.4", Compiler:"gc", Platform:"linux/amd64"}

```

**Comment by petrkotas** [comment]
Hi @bharatnc what VM are you running? Can you please share your VM, VMI specification and
how did you created the virtual machine?

As you can connect via VNC, my guess is, that when creating custom virtual machine, the TTY was not properly configured for use with KubeVirt. KubeVirt exposes the TTY via unix socket, which is a different configuration than exposing as TTY directly. We will see after some more information.

**Comment by bharatnc** [comment]
thanks @petrkotas  you confirmed my initial intuition about the serial tty port. Looks like virtctl uses ttyS0 for console, which wasn't enabled by default for my VM. I enabled it and it started working! I will close this ticket now!

**Comment by mbhatnagar11** [comment]
Hi @bharatnc , how did you enable ttyS0 for your VM ? I am facing the same issue

**Comment by bharatnc** [comment]
@mbhatnagar11  you should be able to specify it in the grub config file (that is what I did).

Example: https://www.tldp.org/HOWTO/Remote-Serial-Console-HOWTO/configure-kernel-grub.html
