### ISSUE TITLE
virtctl image-upload - error Unexpected return value 500

### ISSUE THREAD

**Issue by pbedadham** [kubevirt/kubevirt#2214]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
virtctl image-upload is failing with Unexpected return value 500 after sometime of image upload to PVC. This is working fine for small images but failing for windows as it is large

**What you expected to happen**: upload the image successfully to PVC

**How to reproduce it (as minimally and precisely as possible)**: 
irtctl image-upload --uploadproxy-url=https://k8s-node:30195 --pvc-name=winqcow2-vm-pvc --pvc-size=100Gi --storage-class=local-storage --image-path=windows_server_2012_r2_standard_eval_kvm_20170321-shrunk.qcow2 --insecure

**Anything else we need to know?**: no

**Environment**:
- KubeVirt version (use `virtctl version`): v0.16.0
- Kubernetes version (use `kubectl version`): v1.13.4
- VM or VMI specifications: 
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): centos
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by petrkotas** [comment]
Hi @pbedadham can you please share state of the cluster (`kubectl get pods --all-namespaces`) and logs from the importer related containers: `cdi-http-import-server-`, `cdi-uploadproxy-`, `cdi-apiserver-`, `cdi-deployment-`, `cdi-operator-`. Also please rerun the upload with -v9 `virtctl image-upload --uploadproxy-url=https://k8s-node:30195 --pvc-name=winqcow2-vm-pvc --pvc-size=100Gi --storage-class=local-storage --image-path=windows_server_2012_r2_standard_eval_kvm_20170321-shrunk.qcow2 --insecure -v9`

Thanks for reporting this issue.

**Comment by fabiand** [comment]
@aglitke ideas?

@pbedadham are you all set?

**Comment by winsopc** [comment]
I hit same issue on my k8s with 3 nodes, 
 kubectl get pods --all-namespaces |grep cdi
cdi              cdi-apiserver-bf7bf7456-x99lf                 1/1     Running     0          2d18h
cdi              cdi-deployment-67cc7d9b59-s7nn8               0/1     Evicted     0          2d18h
cdi              cdi-deployment-67cc7d9b59-s7vxq               1/1     Running     9          2d18h
cdi              cdi-operator-56b6786dd8-6q2nv                 1/1     Running     10         2d18h
cdi              cdi-operator-56b6786dd8-znbpx                 0/1     Evicted     0          2d18h
cdi              cdi-uploadproxy-858b8d55dd-stfnp              1/1     Running     0          2d18h
default          cdi-upload-fc29                               1/1     Running     0          2d17h
default          cdi-upload-ubuntu1804                         1/1     Running     0          3m18s

kubectl port-forward -n cdi svc/cdi-uploadproxy 8000:443
kubectl virt image-upload --image-path /root/vms/bionic-server-cloudimg-amd64.img --pvc-name ubuntu1804  --pvc-size 10Gi --storage-class glusterfs-storage --uploadproxy-url  https://127.0.0.1:8000 --wait-secs 600 --insecure -v9
Using existing PVC default/ubuntu1804
Uploading data to https://127.0.0.1:8000

 329.06 MiB / 329.06 MiB [==========================================================================================] 100.00% 5s

Unexpected return value 500
kubectl:1.5.0
virtctl: 0.16.0

**Comment by aglitke** [comment]
We've also seen this issue and it seems to be a JSON processing issue:

From upload pod log:
I0630 14:35:55.676426       1 data-processor.go:173] Validating image
E0630 14:35:55.691042       1 qemu.go:156] Invalid JSON:

E0630 14:35:55.706343       1 data-processor.go:164] unexpected end of JSON input
Invalid json for image /scratch/tmpimage

We have a report in RH Bugzilla: https://bugzilla.redhat.com/show_bug.cgi?id=1725730

**Comment by DonSchenck** [comment]
/reopen

I get this error every time I attempt to image-upload a large (40GB) .RAW image.

**Comment by jlindholm** [comment]
15g file raw img failing the same way.

**Comment by mhenriks** [comment]
hey @jlindholm, fancy seeing you here!  What versions of KubeVirt/CDI are you running?  And can you check the log of the `cdi-upload-<pvc name>` pod?  The log of the `cdi-uploadproxy` may be helpful as well.

**Comment by jlindholm** [comment]
Ha! Small world @mhenriks. It's been a while! 

Here's the cdi-upload-<pvc name> log: 

`I0603 10:52:44.648574       1 uploadserver.go:63] Upload destination: /data/disk.img
I0603 10:52:44.648810       1 uploadserver.go:65] Running server on 0.0.0.0:8443
I0603 10:52:50.891394       1 uploadserver.go:278] Content type header is ""
I0603 10:52:50.899790       1 data-processor.go:275] Calculating available size
I0603 10:52:50.905988       1 data-processor.go:283] Checking out file system volume size.
I0603 10:52:50.906068       1 data-processor.go:287] Request image size not empty.
I0603 10:52:50.906079       1 data-processor.go:292] Target size 12785491968.
I0603 10:52:50.906257       1 data-processor.go:205] New phase: TransferDataFile
I0603 10:52:50.909693       1 util.go:144] Writing data...
E0603 10:56:42.397404       1 util.go:146] Unable to write file from dataReader: write /data/disk.img: no space left on device
E0603 10:56:43.071258       1 data-processor.go:202] write /data/disk.img: no space left on device
unable to write to file
kubevirt.io/containerized-data-importer/pkg/util.StreamDataToFile
	pkg/util/util.go:148
kubevirt.io/containerized-data-importer/pkg/importer.(*AsyncUploadDataSource).TransferFile
	pkg/importer/upload-datasource.go:136
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:179
kubevirt.io/containerized-data-importer/pkg/uploadserver.newAsyncUploadStreamProcessor
	pkg/uploadserver/uploadserver.go:344
kubevirt.io/containerized-data-importer/pkg/uploadserver.(*uploadServerApp).uploadHandlerAsync
	pkg/uploadserver/uploadserver.go:280
net/http.HandlerFunc.ServeHTTP
	GOROOT/src/net/http/server.go:2007
net/http.(*ServeMux).ServeHTTP
	GOROOT/src/net/http/server.go:2387
kubevirt.io/containerized-data-importer/pkg/uploadserver.(*uploadServerApp).ServeHTTP
	pkg/uploadserver/uploadserver.go:210
net/http.serverHandler.ServeHTTP
	GOROOT/src/net/http/server.go:2802
net/http.(*conn).serve
	GOROOT/src/net/http/server.go:1890
runtime.goexit
	src/runtime/asm_amd64.s:1357
Unable to transfer source data to target file
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:181
kubevirt.io/containerized-data-importer/pkg/uploadserver.newAsyncUploadStreamProcessor
	pkg/uploadserver/uploadserver.go:344
kubevirt.io/containerized-data-importer/pkg/uploadserver.(*uploadServerApp).uploadHandlerAsync
	pkg/uploadserver/uploadserver.go:280
net/http.HandlerFunc.ServeHTTP
	GOROOT/src/net/http/server.go:2007
net/http.(*ServeMux).ServeHTTP
	GOROOT/src/net/http/server.go:2387
kubevirt.io/containerized-data-importer/pkg/uploadserver.(*uploadServerApp).ServeHTTP
	pkg/uploadserver/uploadserver.go:210
net/http.serverHandler.ServeHTTP
	GOROOT/src/net/http/server.go:2802
net/http.(*conn).serve
	GOROOT/src/net/http/server.go:1890
runtime.goexit
	src/runtime/asm_amd64.s:1357
E0603 10:56:43.073983       1 uploadserver.go:285] Saving stream failed: Unable to transfer source data to target file: unable to write to file: write /data/disk.img: no space left on device`

It appears I need to allocate more storage. I'm passing --size=25Gi to the virtctl image-upload command for a 15g file. Do I need to allocate it somewhere else?

**Comment by mhenriks** [comment]
Looks like the target PVC only had 12G free per this log msg:  `Target size 12785491968`.  Are you using a dynamic storage provisioner backed by shared storage? 

A little background on how CDI uploads are handled:

When doing an upload, CDI allocates an additional scratch PVC with size equal to the target PVC.  The uploaded image is first written to the scratch space, then copied to the target PVC.  This allows CDI to convert to raw from whatever format is uploaded.

In your case, it appears to me that the scratch and target pvc may be sharing the same physical storage.
