### ISSUE TITLE
Kubevirt does not work if PSP admission control is enabled

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#2221]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:

Some k8s distributions enable PSP by default. virt-operator and other virt components don't work with it right now. An example is documented in #2205.

**What you expected to happen**:

That we ship PSPs for virt-operator and that the virt-operator creates PSPs for all our components too.

**How to reproduce it (as minimally and precisely as possible)**:

Enable the PSP admission plugin and you can't install kubevirt or run VMIs, if you manage to install it.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yu2003w** [comment]
@rmohr I also met similar problem. 
To fix this problem, executed following procedures,
1, create PodSecurityPolicy required by kubevirt-handler
2, create role with the psp
3, binding role with service account kubevirt-handler
After testing, kubevirt-handler works well.

I would like to fix this problem. 
Could you please assign this issue to me?
