### ISSUE TITLE
wrong format for https://github.com/kubevirt/kubevirt/releases/download/v0.16.0/kubevirt.yaml ?

### ISSUE THREAD

**Issue by olberger** [kubevirt/kubevirt#2225]
Trying to deploy with same instructions as for https://kubevirt.io/user-guide/docs/latest/administration/intro.html#1-stable-flow:
```
kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/v0.16.0/kubevirt.yaml
Warning: kubectl apply should be used on resource created by either kubectl create --save-config or kubectl apply
```
Not sure whether this is worrying...

**Comment by tripledes** [comment]
Hey @olberger just did a quick test and didn't get the warning.

* Did you apply the manifest on a *clean* cluster? (clean as in it didn't have kubevirt deployed before)
* What are the k8s client/server versions? (kubectl version)

**Comment by fabiand** [comment]
@olberger it can be that you did a `kubectl create …` on a previous run, then oyu get the warning if you do a `kubectl apply` later on.

This is normal ..
