### ISSUE TITLE
unable to SSH / RDP in to deployed VM on openshift

### ISSUE THREAD

**Issue by gkgth** [kubevirt/kubevirt#2231]
**BUG REPORT**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
Deployed kubevirt on openshift , created a ubuntu VM and exposed port 22 as  NodePort service  , yet unable to ssh 

```apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: ubu-vm01
  labels:
    special: gkubu
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: pvcdisk
    interfaces:
     - name: default
       bridge: {}
    machine:
      type: ""
    resources:
      requests:
        memory: 2048M
  terminationGracePeriodSeconds: 0
  networks:
  - name: default
    pod: {} # Stock pod network
  volumes:
  - name: pvcdisk
    persistentVolumeClaim:
      claimName: ubu-pvc
status: {} 
```
service yaml is as follows, 

```
apiVersion: v1
kind: Service
metadata:
  name: nodeport
spec:
  externalTrafficPolicy: Cluster
  ports:
  - name: nodeport
    nodePort: 30000
    port: 27017
    protocol: TCP
    targetPort: 22
  selector:
    special: gkubu
  type: NodePort
```

```
 oc get vmis
ubu-vm01   21m       Running   172.17.0.16   localhost

oc get po
virt-launcher-ubu-vm01-7g7m5   1/1       Running   0          23m

```
when ssh is performed to the host IP address and the port defined in the service  from another machine in the same network, connection gets closed immediately.

When the vm is accessed via virtctl console and run ipconfig inside the VM, only loop back network interface is shown, yet every other machine in the network is accessible, also we are able to reach google DNS from with in the VM.

Though the "oc get vmis" > command shows an IP address associated with the VM , there is not interface inside, is this the reason why the SSH is not accessible ? or are we missing something ? please help.

 We also tried exposing RDP for a successfully deployed windows VM (the image was taken after virt-win network drivers installed in kvm virtual machine, however when the same image is deployed in kubevirt , there is no sign of network interface inside it ). that too didn't work.

**What you expected to happen**:
SSH / RDP via nodeport should work.

**How to reproduce it (as minimally and precisely as possible)**:

deploy ubuntu server in the below mentioned environment, expose port 22 and try accessing it from another machine in the same network. 

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.15.0
- Kubernetes version (use `kubectl version`):v1.11.0
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu server 18.04
- Kernel (e.g. `uname -a`): Linux originmaster00 4.15.0-45-generic #48-Ubuntu SMP Tue Jan 29 16:28:13 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: openshift : oc v3.11.0+0cbc58b
- Others:

**Comment by gkgth** [comment]
Update : created windows 10 image (.img) in as a KVM virtual machine (installed virtio scsi driver and Redhat network interface ). Uploaded the same .img (raw image file) on to CDI (1.18) deployed along with kubervirt on the single node openshift environment (details mentioned above). VM attained "running" state, though the network interface was not available. (though the network interface was installed in the image - also if we import the same image as KVM Virtual machine - the network interface is readily available).

 Further, uploaded virtio-win.iso driver image on to CDI and attached to kubevirt Virtualmachine as CD ROM .
However there are no network devices to install the driver.

please help.

**Comment by gkgth** [comment]
sorted the things out, we are able to run windows 10 (installed copy) as container disk, able to RDP it via node port. closing the issue.

**Comment by Woytek-Polnik** [comment]
@gkgth have you managed to solve SSH access? I've found that SSH server is not installed on windows & cannot be installed and updates are disabled
