### ISSUE TITLE
travis uploads many CSVs for a release

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#2248]
/kind bug

**What happened**:
Releasing 0.17.
travis is building artifacts, and then travis uploaded all previous CSVs as release artifacts to github.

**What you expected to happen**:
That at max the 0.17 CSV would be uploaded.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
![Screenshot_2019-05-06 kubevirt kubevirt](https://user-images.githubusercontent.com/83456/57249085-51902900-7044-11e9-8dc3-3935cfdb2e31.png)

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fabiand** [comment]
I'd expect that there is one new (and uploaded) CSV for each kubevirt release.

**Comment by slintes** [comment]
can probably easily be fixed by using $TRAVIS_TAG in the CSV filename pattern
