### ISSUE TITLE
consult about remote-writer

### ISSUE THREAD

**Issue by DeepLJH0001** [kubevirt/kubevirt#2252]
when i execute virtctl vnc testvm 
there has a error told me remote-write was require
so where can i download the remote-writer barinary

**Environment**:
- KubeVirt version (use `virtctl version`): 1.15.0
- Kubernetes version (use `kubectl version`):1.14.0
- VM or VMI specifications: demo testvm
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): minikube
- Kernel (e.g. `uname -a`): linux
- Install tools: minikube
- Others:

**Comment by slintes** [comment]
Hi, you probably mean `remote-viewer`?
It depends on your operating system. For Linux you can install `virt-viewer` using your package manager, or download it from https://virt-manager.org/download/. On the same page you find an installer for Windows, make sure that you add the install path of `remote-viewer.exe` to your `$PATH` variable.
On MacOS we support Tiger VNC, Chicken VNC and Real VNC.
Does that help?

**Comment by DeepLJH0001** [comment]
it's work ,thanks~
