### ISSUE TITLE
Container images are 49y old

### ISSUE THREAD

**Issue by tripledes** [kubevirt/kubevirt#2254]
/kind bug

**What happened**:

Just deployed KubeVirt (using HCO) and the pulled images are 49y old:

```shell
docker.io/kubevirt/virt-operator                       latest              118361cf815d        49 years ago        290 MB
docker.io/kubevirt/virt-controller                     latest              498ef9fb3bba        49 years ago        292 MB
docker.io/kubevirt/virt-api                            latest              5820ae856c0a        49 years ago        293 MB
docker.io/kubevirt/virt-handler                        latest              544efacdcceb        49 years ago        294 MB
```

```shell
$ docker inspect 5820ae856c0a | grep Created

  "Created": "1970-01-01T00:00:00Z",
```
Which is basically the Unix epoch.

**What you expected to happen**:

Images would be weeks/days old.

**How to reproduce it (as minimally and precisely as possible)**:

Just deploy KubeVirt.

**Anything else we need to know?**:

I don't have any Bazel experience myself but this seems to be related to Bazel [0] which would need `stamp = true` on the `container_image` definition to allow the use of workspace status variables. Once enabled,  `creation_time` should be added by default:

`String, optional, default to {BUILD_TIMESTAMP} when stamp = True, otherwise 0`

[0] https://github.com/bazelbuild/rules_docker/issues/52

**Environment**:
- KubeVirt version (use `virtctl version`): 
  Client Version: version.Info{GitVersion:"v0.17.0", GitCommit:"c0f960702dce718419a767f3913669f539229ff0", GitTreeState:"clean", BuildDate:"2019-05-05T08:09:14Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

  Server Version: version.Info{GitVersion:"v0.17.0-2+9c982f0cb214fd", GitCommit:"9c982f0cb214fdcf040edf674115826b01fc263f", GitTreeState
:"clean", BuildDate:"2019-05-06T16:46:44Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):
  Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:11:31Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.1", GitCommit:"b7394102d6ef778017f2ca4046abbaa23b88c290", GitTreeState:"clean", BuildDate:"2019-04-08T17:02:58Z", GoVersion:"go1.12.1", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
We can set a `BUILD_TIMESTAMP` in the `--workspace_status_command` file. `stamp` is no needed anymore.
