### ISSUE TITLE
make push failed with SSL: CERTIFICATE_VERIFY_FAILED

### ISSUE THREAD

**Issue by yu2003w** [kubevirt/kubevirt#2264]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind enhancement

**What happened**:
Run "make" succeeded.
Then run "make push" and encountered errors as below,
INFO: Analysed target //:push-images (104 packages loaded, 13519 targets configured).
INFO: Found 1 target...
Target //:push-images up-to-date:
  bazel-bin/push-images
INFO: Elapsed time: 26.705s, Critical Path: 23.52s
INFO: 16 processes: 16 processwrapper-sandbox.
INFO: Build completed successfully, 26 total actions
INFO: Build completed successfully, 26 total actions
F0509 12:49:10.359796   29034 fast_pusher_.py:194] Error publishing k8stest:8500/virtrepo/virt-handler:0508: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
F0509 12:49:10.368978   29035 fast_pusher_.py:194] Error publishing k8stest:8500/virtrepo/fedora30-cloud-container-disk-demo:0508: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
F0509 12:49:10.374887   29040 fast_pusher_.py:194] Error publishing k8stest:8500/virtrepo/virtio-container-disk:0508: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
F0509 12:49:10.400033   29030 fast_pusher_.py:194] Error publishing k8stest:8500/virtrepo/alpine-container-disk-demo:0508: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
F0509 12:49:10.405060   29041 fast_pusher_.py:194] Error publishing k8stest:8500/virtrepo/disks-images-provider:0508: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
F0509 12:49:10.427361   29029 fast_pusher_.py:194] Error publishing k8stest:8500/virtrepo/virt-launcher:0508: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
F0509 12:49:10.435517   29038 fast_pusher_.py:194] Error publishing k8stest:8500/virtrepo/example-hook-sidecar:0508: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
F0509 12:49:10.441883   29039 fast_pusher_.py:194] Error publishing k8stest:8500/virtrepo/vm-killer:0508: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
F0509 12:49:10.479532   29032 fast_pusher_.py:194] Error publishing k8stest:8500/virtrepo/subresource-access-test:0508: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
F0509 12:49:10.485501   29036 fast_pusher_.py:194] Error publishing k8stest:8500/virtrepo/cdi-http-import-server:0508: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
F0509 12:49:10.485774   29033 fast_pusher_.py:194] Error publishing k8stest:8500/virtrepo/virt-controller:0508: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
F0509 12:49:10.497201   29037 fast_pusher_.py:194] Error publishing k8stest:8500/virtrepo/winrmcli:0508: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
F0509 12:49:10.497987   29025 fast_pusher_.py:194] Error publishing k8stest:8500/virtrepo/virt-api:0508: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
F0509 12:49:10.500349   29022 fast_pusher_.py:194] Error publishing k8stest:8500/virtrepo/cirros-container-disk-demo:0508: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
F0509 12:49:10.504436   29020 fast_pusher_.py:194] Error publishing k8stest:8500/virtrepo/example-cloudinit-hook-sidecar:0508: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
F0509 12:49:10.504312   29021 fast_pusher_.py:194] Error publishing k8stest:8500/virtrepo/container-disk-v1alpha:0508: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
F0509 12:49:10.508882   29042 fast_pusher_.py:194] Error publishing k8stest:8500/virtrepo/fedora-cloud-container-disk-demo:0508: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
F0509 12:49:10.509044   29031 fast_pusher_.py:194] Error publishing k8stest:8500/virtrepo/virt-operator:0508: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)
Makefile:21: recipe for target 'bazel-push-images' failed
make: *** [bazel-push-images] Error 1

Actually, docker login succeeded for private registry k8stest:8500. And $HOME/.docker/config.json was updated as below,
root@filmy1:/mnt/data/gowork/src/github.com/yu2003w/kubevirt# cat ~/.docker/config.json 
{
	"auths": {
		"k8stest:8500": {
			"auth": "YWRtaW46YWRtaW4="
		}
	},
	"HttpHeaders": {
		"User-Agent": "Docker-Client/18.03.1-ce (linux)"
	}
}

**What you expected to happen**:
make push could be run successfully and images could be pushed to private registry.

**How to reproduce it (as minimally and precisely as possible)**:
git clone master branch on Ubuntu 18.04.
Run make
make push

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
- Kernel (e.g. `uname -a`):
Linux  4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by yu2003w** [comment]
@slintes Yes, registry supports SSL and self signed certificate is used.
We followed the configuration method in [1].
Do you mean currently master branch doesn't support push images to registry with SSL enabled?

Using username/password or configuration via [1] could authenticated successfully with registry.
Is that possible to authenticate with registry via username/password?

I tried k8stest.local:8500, it indicated unknown server name as real registry server address is k8stest:8500.

[1] https://docs.docker.com/engine/security/certificates/.

**Comment by slintes** [comment]
the docker container which is used with the make targets doesn't see the /etc/docker/certs.d/ directory. Can you try calling the relevant script directly?
`./hack/bazel-push-images.sh`

**Comment by j-griffith** [comment]
When I last looked at this I was poking around this:  https://github.com/bazelbuild/rules_docker/pull/686 but got pulled away on some other things.  I might be able to take a look again

**Comment by yu2003w** [comment]
Run bazel-push-images.sh directly on the host, I got the following error,

INFO: From Generating Descriptor Set proto_library @com_google_protobuf//:api_proto:
external/com_google_protobuf: warning: directory does not exist.
ERROR: /mnt/data/gowork/src/github.com/yu2003w/kubevirt/BUILD.bazel:87:1: Executing genrule //:libvirt-devel-headers failed (Exit 127) bash failed: error executing command /bin/bash -c ... (remaining 1 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
/bin/bash: rpm2archive: command not found
Target //:push-images failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 5.789s, Critical Path: 2.33s
INFO: 31 processes: 31 linux-sandbox.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully

I never used bazel before, it's a little difficult to resolve such issues quickly.

**Comment by yu2003w** [comment]
@slintes Could /etc/docker/certs.d/ be mounted into bazel server container as /root/.docker/config.json?

**Comment by cynepco3hahue** [comment]
@yu2003w I believe it should be mounted as /etc/docker/certs.d/ under the container, so can you try to modify `hack/dockerizied` script and modify the line
before 
```bash
# append .docker directory as volume
mkdir -p "${HOME}/.docker"
volumes="$volumes -v ${HOME}/.docker:/root/.docker:ro,z"
```

after 
```bash
# append .docker directory as volume
mkdir -p "${HOME}/.docker"
volumes="$volumes -v ${HOME}/.docker:/root/.docker:ro,z"

# append /etc/docker directory
volumes="$volumes -v /etc/docker:/etc/docker:ro,z"
```

it will mount the certificate directory and I hope it will be enough for the bazel

**Comment by yu2003w** [comment]
@cynepco3hahue Updated hack/dockerized and mount /etc/docker into container, then ran "make push". It still failed and indicated that "[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:726)".
Pushing images is done by contrib:push-all.bzl which is provided by bazelbuild/rules_docker.
It seemed that currently bazelbuild/rules_docker did not support to authenticate registry with certs located in /etc/docker.
I also updated WORKSPACE to customized docker authentication documented in [1]. However , it still did not work.
It seems this issue is caused by [google/containerregistry#issue150](https://github.com/google/containerregistry/issues/150) as rules_docker depend on google/containerregistry.

[1] https://github.com/bazelbuild/rules_docker#container_push-custom-client-configuration

@slintes @j-griffith  For the issues caused by dependent libraries, do we just wait for fixing patch from the libraries? Or could we consider adopting other solutions?
