### ISSUE TITLE
creating a KubeVirt CR in a different namespace than the operator fails

### ISSUE THREAD

**Issue by slintes** [kubevirt/kubevirt#2275]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
- Installed kubevirt operator on OKD using marketplace (with the kubevirt operatorsource), which results in the operator being installed in the `openshift-operators` namespace.
- Created a `kubevirt` namespace and a KubeVirt CR in it.
- KubeVirt is not installed, becaue the `kubevirt-xxxx` job in the `kubevirt` namespace can't use the `virt-operator` service account in the `openshift-operators` ns: `Error creating: pods "kubevirt-jobptr99-" is forbidden: error looking up service account kubevirt/kubevirt-operator: serviceaccount "kubevirt-operator" not found`

**What you expected to happen**:
Job running in the operator ns, or using another sa

**How to reproduce it (as minimally and precisely as possible)**:
Create the KubeVirt CR in a different ns than the operator

**Environment**:
- KubeVirt version (use `virtctl version`): 0.17.0

**Comment by fabiand** [comment]
I see.
So far our - at least  my - assumption was that the operator will always live in the same namespace as the CR. Which is not the case as it seems.

**Comment by davidvossel** [comment]
> So far our - at least my - assumption was that the operator will always live in the same namespace as the CR. Which is not the case as it seems.

maybe the KubeVirt CRD shouldn't be namespaced. Do we have a use case for installing KubeVirt outside of the operator's namespace.?

**Comment by davidvossel** [comment]
fyi, i'm working on this. I should have a PR posted in the next day or so

**Comment by fabiand** [comment]
@davidvossel @stu-gott was this fixed and can we close this issue?

**Comment by davidvossel** [comment]
pr #2284 is still open
