### ISSUE TITLE
virtctl vnc Windows VM Failed

### ISSUE THREAD

**Issue by Apokleos** [kubevirt/kubevirt#2307]
**Difficult to use vnc or console to connect to WIndows-VM**
> Uncomment only one, leave it on its own line:
>
> /kind bug?

**What happened**:
Virtctl vnc/console Windows VM Failed!!!
Message As Below:
```bash
[root@host-10-3-9-7 Kubevirt]# virtctl console vmi-windows
Successfully connected to vmi-windows console. The escape sequence is ^]
    Virtual Machine's /var/run/kubevirt-private/23e667d2-7c41-11e9-b602-fa163e744925/virt-serial0 socket is currently unavailable
websocket: close 1006 (abnormal closure): unexpected EOF

[root@host-10-3-9-7 Kubevirt]# virtctl vnc vmi-windows --v=9
{"component":"virtctl","level":"info","msg":"Config loaded from file/root/.kube/config","pos":"loader.go:359","timestamp":"2019-05-22T11:29:10.772451Z"}
{"component":"virtctl","level":"info","msg":"curl -k -v -XGET  -H \"User-Agent: virtctl/v0.0.0 (linux/amd64) kubernetes/$Format\" 'wss://10.3.9.7:6443/apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/vmi-windows/vnc'","pos":"round_trippers.go:386","timestamp":"2019-05-22T11:29:10.774653Z"}
{"component":"virtctl","level":"info","msg":"connection timeout: 1m0s","pos":"vnc.go:137","timestamp":"2019-05-22T11:29:10.820752Z"}
{"component":"virtctl","level":"info","msg":"Executing commandline: 'remote-viewer [vnc://127.0.0.1:37053 --debug]'","pos":"vnc.go:225","timestamp":"2019-05-22T11:29:10.821302Z"}
{"component":"virtctl","level":"error","msg":"remote-viewer execution failed: exit status 1, output: \n(remote-viewer:25851): Gtk-WARNING **: 11:29:10.877: cannot open display: \n","pos":"vnc.go:230","timestamp":"2019-05-22T11:29:10.882211Z"}
[root@host-10-3-9-7 Kubevirt]#
```
**What you expected to happen**:
(1) How to resolve it ?
(2) The VNC connect to VM's work flow?
**How to reproduce it (as minimally and precisely as possible)**:
(1) VMI-WIndows and Pod related to it are both OK
```bash
[root@host-10-3-9-7 Kubevirt]# kubectl get vmi
NAME          AGE   PHASE     IP                NODENAME
testvm        16h   Running   192.168.238.208   host-10-3-9-7
vmi-windows   8s    Running   192.168.238.213   host-10-3-9-7
[root@host-10-3-9-7 Kubevirt]# kubectl get po
NAME                              READY   STATUS    RESTARTS   AGE
virt-launcher-testvm-ww4kp        2/2     Running   0          16h
virt-launcher-vmi-windows-9nndk   1/1     Running   0          77s
```
(2) Login vmi-windows with VNC or Console

```bash
[root@host-10-3-9-7 Kubevirt]# virtctl console vmi-windows
Successfully connected to vmi-windows console. The escape sequence is ^]
    Virtual Machine's /var/run/kubevirt-private/23e667d2-7c41-11e9-b602-fa163e744925/virt-serial0 socket is currently unavailable
websocket: close 1006 (abnormal closure): unexpected EOF

[root@host-10-3-9-7 Kubevirt]# virtctl vnc vmi-windows --v=9
{"component":"virtctl","level":"info","msg":"Config loaded from file/root/.kube/config","pos":"loader.go:359","timestamp":"2019-05-22T11:29:10.772451Z"}
{"component":"virtctl","level":"info","msg":"curl -k -v -XGET  -H \"User-Agent: virtctl/v0.0.0 (linux/amd64) kubernetes/$Format\" 'wss://10.3.9.7:6443/apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/vmi-windows/vnc'","pos":"round_trippers.go:386","timestamp":"2019-05-22T11:29:10.774653Z"}
{"component":"virtctl","level":"info","msg":"connection timeout: 1m0s","pos":"vnc.go:137","timestamp":"2019-05-22T11:29:10.820752Z"}
{"component":"virtctl","level":"info","msg":"Executing commandline: 'remote-viewer [vnc://127.0.0.1:37053 --debug]'","pos":"vnc.go:225","timestamp":"2019-05-22T11:29:10.821302Z"}
{"component":"virtctl","level":"error","msg":"remote-viewer execution failed: exit status 1, output: \n(remote-viewer:25851): Gtk-WARNING **: 11:29:10.877: cannot open display: \n","pos":"vnc.go:230","timestamp":"2019-05-22T11:29:10.882211Z"}
[root@host-10-3-9-7 Kubevirt]#
```

(3) After a While, VMI-WIndows PHASE turns to failed, virt-launcher-vmi-windows-9nndk Completed
```bash
[root@host-10-3-9-7 Kubevirt]# kubectl get vmis
NAME          AGE     PHASE     IP                NODENAME
testvm        16h     Running   192.168.238.208   host-10-3-9-7
vmi-windows   6m36s   Failed    192.168.238.213   host-10-3-9-7
[root@host-10-3-9-7 Messages]# kubectl get po
NAME                              READY   STATUS      RESTARTS   AGE
virt-launcher-testvm-ww4kp        2/2     Running     0          16h
virt-launcher-vmi-windows-9nndk   0/1     Completed   0          8m58s

```
(4) Related Messages as Below:
**Environment**:
- KubeVirt version (use `virtctl version`):
Client Version: version.Info{GitVersion:"v0.17.0", GitCommit:"c0f960702dce718419a767f3913669f539229ff0", GitTreeState:"clean", BuildDate:"2019-05-05T08:09:14Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.17.0", GitCommit:"a067696ed6c25b0eab9dfcd01bbdc045f500f8ca", GitTreeState:"clean", BuildDate:"2019-05-06T14:58:11Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCom                                               mit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:                                               "2019-05-16T16:23:09Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd                                               64"}
Server Version: version.Info{Major:"1", Minor:"14", GitVersion:"v1.14.2", GitCom                                               mit:"66049e3b21efe110454d67df4fa62b08ea79a19b", GitTreeState:"clean", BuildDate:                                               "2019-05-16T16:14:56Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd                                               64"}

- VM or VMI specifications:
```bash
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-windows
  name: vmi-windows
spec:
  domain:
    clock:
      timer:
        hpet:
          present: false
        hyperv: {}
        pit:
          tickPolicy: delay
        rtc:
          tickPolicy: catchup
      utc: {}
    cpu:
      cores: 2
    devices:
      disks:
      - disk:
          bus: sata
        name: pvcdisk
      interfaces:
      - bridge: {}
        model: e1000
        name: default
    features:
      acpi: {}
      apic: {}
      hyperv:
        relaxed: {}
        spinlocks:
          spinlocks: 8191
        vapic: {}
    firmware:
      uuid: 5d307ca9-b3ef-428c-8861-06e72d69f223
    machine:
      type: q35
    resources:
      requests:
        memory: 2Gi
  networks:
  - name: default
    pod: {}
  terminationGracePeriodSeconds: 0
  volumes:
  - name: pvcdisk
    persistentVolumeClaim:
      claimName: windows-pvc
```
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
uname -msr
Linux 3.10.0-862.11.6.el7.x86_64 x86_64
- Install tools:
- Others:

**Comment by petrkotas** [comment]
Hi @Apokleos this is interesting. What Windows version are you using? 
The failed state on the Windows VM signals, problem in the VM (The VNC does not affect internals of the VM).

Does the VM fails either way? How is the VM installed? Can you also post state of the cluster and logs from the kubevirt components?

Thanks for reporting this!

Petr

**Comment by Apokleos** [comment]
Hi Petr@petrkotas Thanks for your reply.

I not clear about the windows's edition, I just create NFS storage PV/PVC and then use the [Example](https://github.com/kubevirt/kubevirt/blob/master/cluster/examples/vmi-windows.yaml) with my PVC: windows-pvc.
After "kubectl apply -f vmi-windows.yaml" , it will be successfully running, and a disk.img appears in my NFS storage like this:
[root@node1 kubenfs]# ls -l
total 4
-rw-r--r-- 1 nfsnobody nfsnobody 32212254720 May 22 06:53 disk.img

I want to know where the image comes from?

**Comment by fabiand** [comment]
```output: \n(remote-viewer:25851): Gtk-WARNING **: 11:29:10.877: cannot open display```

This indicates that you tried to run remoteviewer on the console.

`virtctl vnc` is required to be run in a graphical environment on the client.
No specific vm or guests Support ist required.

Can you please try vnc from gnome, kde or alike?

**Comment by fabiand** [comment]
@apokleos

**Comment by slintes** [comment]
> I not clear about the windows's edition, I just create NFS storage PV/PVC and then use the Example with my PVC: windows-pvc.

This sounds like a misunderstanding to me: the PV has to contain the windows disk image already, KubeVirt does not provide it.
And IIRC when KubeVirt doesn't find a disk image, it creates an empty one with the size of the PV. Since it's empty, the VM can't boot, so no concole, and no vnc.
Does that make sense?

**Comment by petrkotas** [comment]
@Apokleos, as @slintes noted. Judging by the information. My guess is, your VM is emty. Therefore it fails after some time. 

To test Windows VM, it is up to you to create the VM with the right disk. To do this, you basically have three options: 

1. Create new VM outside of the Kubevirt on QEMU/KVM based virtualization. Than import it to the Kubevirt using [CDI](https://kubevirt.io/2018/CDI-DataVolumes.html).
2. Install VM directly under the Kubevirt. You will have to create new empty VM with three disks and install Windows from these.
   a) PVC for install
   b) DVD rom with windows install
   c) Container disk providing [virtio drivers](https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/virtio-win.html)
3. Try [Cloudbase](https://cloudbase.it/windows-cloud-images/#download) cloud windows image.

I hope this helps.

**Comment by Apokleos** [comment]
@slintes Thanks for your explanation, I get it.
@petrkotas Thanks for your Getting tired of answering, I have tried to make a windows based container disk by myself, and it works now, regardless of,  some new problems occur.

> `output: \n(remote-viewer:25851): Gtk-WARNING **: 11:29:10.877: cannot open display`
> 
> This indicates that you tried to run remoteviewer on the console.
> 
> `virtctl vnc` is required to be run in a graphical environment on the client.
> No specific vm or guests Support ist required.
> 
> Can you please try vnc from gnome, kde or alike?

Thank you!@fabiand I have installed X window and GNOME Desktop, and then It does work.
It works well with linux vm (testvm), both vnc and console are ok. 
To Windows VM, but Some new problem occurs. and it is same to the [Issue](https://github.com/kubevirt/kubevirt/issues/2201)

**Comment by Apokleos** [comment]
> @Apokleos, as @slintes noted. Judging by the information. My guess is, your VM is emty. Therefore it fails after some time.
> 
> To test Windows VM, it is up to you to create the VM with the right disk. To do this, you basically have three options:
> 
> 1. Create new VM outside of the Kubevirt on QEMU/KVM based virtualization. Than import it to the Kubevirt using [CDI](https://kubevirt.io/2018/CDI-DataVolumes.html).
> 2. Install VM directly under the Kubevirt. You will have to create new empty VM with three disks and install Windows from these.
>    a) PVC for install
>    b) DVD rom with windows install
>    c) Container disk providing [virtio drivers](https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/virtio-win.html)
> 3. Try [Cloudbase](https://cloudbase.it/windows-cloud-images/#download) cloud windows image.
> 
> I hope this helps.
@petrkotas Thanks for your trying to answering.
I have made a windows image based container disk, and I can vnc to connect the vmi created with the container disk. Next, I will try to make your suggestion in practice.

**Comment by Apokleos** [comment]
> > I not clear about the windows's edition, I just create NFS storage PV/PVC and then use the Example with my PVC: windows-pvc.
> 
> This sounds like a misunderstanding to me: the PV has to contain the windows disk image already, KubeVirt does not provide it.
> And IIRC when KubeVirt doesn't find a disk image, it creates an empty one with the size of the PV. Since it's empty, the VM can't boot, so no concole, and no vnc.
> Does that make sense?

Thanks @slintes I get it.

**Comment by fabiand** [comment]
@Apokleos please open new issues for anything that is topping you. (What is the new issue?)

Closing this one for now as it has been solved.

**Comment by bugrahanceran** [comment]
@Apokleos can you please share windows image based container disk link?
