### ISSUE TITLE
macos vm

### ISSUE THREAD

**Issue by tlawrie** [kubevirt/kubevirt#2312]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind enhancement

**Anything else we need to know?**: 

Would like to create a macos vm that runs and is managed by kubevirt

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications: macos
- Cloud provider or hardware configuration: Mac hardware, potentially wiped to baremetal. For legal reason we eventually need to run the mac vm on mac hardware.
- OS (e.g. from /etc/os-release): macos
- Kernel (e.g. `uname -a`): Darwin 18.2.0
- Install tools:
- Others:

**Comment by fabiand** [comment]
Hm. That might be possible. Wasn't there a similar issue already ...

**Comment by marcus-sa** [comment]
What's the progress and thoughts on this?
I would love to utilize KubeVirt for an open source continuous integration platform, but for that I really need the ability to use MacOS VMs.

**Comment by slintes** [comment]
Hey @marcus-sa, did you already try to run a MacOS VM? Do you know what are the missing parts in KubeVirt are?

/remove-lifecycle stale

**Comment by marcus-sa** [comment]
Nope not yet @slintes, just discovered KubeVirt a few days ago.
I'll try to give it a go.

**Comment by tlawrie** [comment]
@fabiand do you know if anyone else has attempted getting a MacOS VM to work with Kubevirt?

**Comment by fabiand** [comment]
IIRC there were attempts to run MacOS on KubeVirt, but I do not know how
they went.
Despite that I'm also not sure about the licensing situation for running
MacOS inside a VM

**Comment by tlawrie** [comment]
I think you can as long as it runs on licensed Mac hardware. But dont quote me.

Hopefully the others have had more luck as I would like to kick start an attempt at it again...

**Comment by lxs137** [comment]
@fabiand I think it's legal because macOS can run on [Parallels](https://www.parallels.com/products/desktop/#compare). http://www.contrib.andrew.cmu.edu/~somlo/OSXKVM/#sec_4

**Comment by lxs137** [comment]
@tlawrie I have already ran macOS on kubevirt with some workarounds, so I want to add some features to kubevirt. See my [comment](https://github.com/kubevirt/kubevirt/issues/2763#issuecomment-536444094) here.
