### ISSUE TITLE
vm-cirros failed to start with error "KVM: entry failed, hardware error 0x0"

### ISSUE THREAD

**Issue by yu2003w** [kubevirt/kubevirt#2318]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind enhancement

**What happened**:
vm-cirros failed to start when issuing following commands,
_kubectl create -f cluster/examples/vm-cirros.yaml
_out/cmd/virtctl/virtctl start vm-cirros__

VM was created and VMI was successfully scheduled. However, vmi was failed to startup.
root@filmy1:/mnt/data/gowork/src/github.com/yu2003w/kubevirt# kubectl get vm --all-namespaces
NAMESPACE   NAME        AGE   RUNNING   VOLUME
vmtest      vm-cirros   2h    true      
root@filmy1:/mnt/data/gowork/src/github.com/yu2003w/kubevirt# kubectl get vmi --all-namespaces
NAMESPACE   NAME         AGE   PHASE     IP            NODENAME
vmtest      vm-cirros    2h    Running   10.1.60.183   172.16.17.35

VM vm-cirros is always paused and couldn't be started.

/var/log/libvirt/qemu/vmtest_vm-cirros.log indicated error "KVM: entry failed, hardware error 0x0".

virt handler indicated error as below,
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"vm-cirros","namespace":"vmtest","pos":"vm.go:871","reason":"server error. command SyncVMI failed: \"LibvirtError(Code=1, Domain=10, Message='internal error: unable to execute QEMU command 'cont': Resetting the Virtual Machine is required')\"","timestamp":"2019-05-24T06:21:08.843458Z","uid":"12a3cb05-7dd4-11e9-963e-0016ac101123"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance vmtest/vm-cirros","pos":"vm.go:547","reason":"server error. command SyncVMI failed: \"LibvirtError(Code=1, Domain=10, Message='internal error: unable to execute QEMU command 'cont': Resetting the Virtual Machine is required')\"","timestamp":"2019-05-24T06:21:08.846499Z"}

[vmtest_vm-cirros.log](https://github.com/kubevirt/kubevirt/files/3215454/vmtest_vm-cirros.log)

**What you expected to happen**:
vm-cirros could be started.
**How to reproduce it (as minimally and precisely as possible)**:
1, deploy kubevirt on k8s cluster installed on ubuntu
2, kubectl create -f cluster/examples/vm-cirros.yaml
3, _out/cmd/virtctl/virtctl start vm-cirros

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
Client Version: version.Info{GitVersion:"v0.17.0-110+e115bd5bd1b381-dirty", GitCommit:"e115bd5bd1b3816c92864a0c42048ad20f5b11cc", GitTreeState:"dirty", BuildDate:"2019-05-24T02:08:06Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.17.0-110+e115bd5bd1b381-dirty", GitCommit:"e115bd5bd1b3816c92864a0c42048ad20f5b11cc", GitTreeState:"dirty", BuildDate:"2019-05-24T02:12:37Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes version (use `kubectl version`):
1.12.4
- VM or VMI specifications:
cluster/examples/vm-cirros.yaml
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="18.04.2 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.2 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
- Kernel (e.g. `uname -a`):
Linux filmy1.fyre.ibm.com 4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by rmohr** [comment]
@yu2003w do you run kubevirt in a nested environment or on bare metal? I see a lot of reports where such an error is related to nested kvm.

**Comment by yu2003w** [comment]
Kubevirt run in nested environment.
I tried to set spec.template.spec.domain.cpu.model to Conroe, host-model, host-passthrough and Broadwell-IBRS. None of them worked and caught the same error.

host node cpu info is as below,
Architecture:        x86_64
CPU op-mode(s):      32-bit, 64-bit
Byte Order:          Little Endian
CPU(s):              8
On-line CPU(s) list: 0-7
Thread(s) per core:  1
Core(s) per socket:  1
Socket(s):           8
NUMA node(s):        1
Vendor ID:           GenuineIntel
CPU family:          6
Model:               61
Model name:          Intel Core Processor (Broadwell, IBRS)
Stepping:            2
CPU MHz:             2299.998
BogoMIPS:            4599.99
Virtualization:      VT-x
Hypervisor vendor:   KVM
Virtualization type: full
L1d cache:           32K
L1i cache:           32K
L2 cache:            4096K
NUMA node0 CPU(s):   0-7
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc rep_good nopl cpuid pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 3dnowprefetch invpcid_single pti ssbd ibrs ibpb tpr_shadow vnmi flexpriority ept vpid fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm mpx avx512f rdseed adx smap avx512cd xsaveopt

**Comment by cynepco3hahue** [comment]
Hm, I believe the nested virtualization is enabled, otherwise, we will miss the KVM devices under nodes and `vmx` flag also exists under the CPU configuration.
@yu2003w Just to be sure can you show the output of the command `cat /sys/module/kvm_intel/parameters/nested` from the cluster worker node?

**Comment by yu2003w** [comment]
@cynepco3hahue The output is 'Y'
root@filmy1:~# cat /sys/module/kvm_intel/parameters/nested 
Y

**Comment by Apokleos** [comment]
@yu2003w Hi, Could you give the pod description of virt-launcher-vm-cirros-xxx related to VM vm-cirros ?  You can exec amd like this: kubectl describe po virt-launcher-vm-cirros-xxx -n ns

**Comment by yu2003w** [comment]
@Apokleos  The detailed info as below,
```
root@filmy1:~# kubectl describe pods/virt-launcher-vm-cirros-v89js 
Name:               virt-launcher-vm-cirros-v89js
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               172.16.17.35/172.16.17.35
Start Time:         Tue, 28 May 2019 20:29:26 -0700
Labels:             kubevirt.io=virt-launcher
                    kubevirt.io/created-by=f5f09b37-81c1-11e9-ba23-0016ac101123
                    kubevirt.io/vm=vm-cirros
Annotations:        kubernetes.io/psp: ibm-privileged-psp
                    kubevirt.io/domain: vm-cirros
Status:             Running
IP:                 10.1.60.184
Controlled By:      VirtualMachineInstance/vm-cirros
Containers:
  volumecontainerdisk:
    Container ID:  docker://c9b7bbdaacc0dc7546316918517ccbb3d4e985790b9e41b8af071354ee08e7ad
    Image:         icpdev.icp:8500/kubevirtimg/cirros-container-disk-demo:1.3.0
    Image ID:      docker-pullable://icpdev.icp:8500/kubevirtimg/cirros-container-disk-demo@sha256:92e39d8b1c2a38afc0c2225d3983e85743ba79b5a8f80f8c4f1a1ccd4f1ea704
    Port:          <none>
    Host Port:     <none>
    Command:
      /entry-point.sh
    State:          Running
      Started:      Tue, 28 May 2019 20:29:28 -0700
    Ready:          True
    Restart Count:  0
    Readiness:      exec [cat /tmp/healthy] delay=2s timeout=5s period=5s #success=2 #failure=5
    Environment:
      COPY_PATH:  /var/run/kubevirt-ephemeral-disks/container-disk-data/default/vm-cirros/disk_containerdisk/disk-image
    Mounts:
      /var/run/kubevirt-ephemeral-disks from ephemeral-disks (rw)
  compute:
    Container ID:  docker://8c340785f142959ad77dcd27968beb0bbb55a78125081817931813c9d97caff7
    Image:         icpdev.icp:8500/kubevirtimg/virt-launcher:1.3.0
    Image ID:      docker-pullable://icpdev.icp:8500/kubevirtimg/virt-launcher@sha256:dc0f56a80fbc5bdd238f69c477823c4369ecd5a0b56a120db4fdbb94cb6c81b2
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/virt-launcher
      --qemu-timeout
      5m
      --name
      vm-cirros
      --uid
      f5f09b37-81c1-11e9-ba23-0016ac101123
      --namespace
      default
      --kubevirt-share-dir
      /var/run/kubevirt
      --ephemeral-disk-dir
      /var/run/kubevirt-ephemeral-disks
      --readiness-file
      /var/run/kubevirt-infra/healthy
      --grace-period-seconds
      15
      --hook-sidecars
      0
      --less-pvc-space-toleration
      10
    State:          Running
      Started:      Tue, 28 May 2019 20:29:28 -0700
    Ready:          True
    Restart Count:  0
    Limits:
      devices.kubevirt.io/kvm:        1
      devices.kubevirt.io/tun:        1
      devices.kubevirt.io/vhost-net:  1
    Requests:
      cpu:                            100m
      devices.kubevirt.io/kvm:        1
      devices.kubevirt.io/tun:        1
      devices.kubevirt.io/vhost-net:  1
      memory:                         1187554432
    Readiness:                        exec [cat /var/run/kubevirt-infra/healthy] delay=2s timeout=5s period=2s #success=1 #failure=5
    Environment:                      <none>
    Mounts:
      /var/run/kubevirt from virt-share-dir (rw)
      /var/run/kubevirt-ephemeral-disks from ephemeral-disks (rw)
      /var/run/kubevirt-infra from infra-ready-mount (rw)
      /var/run/libvirt from libvirt-runtime (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  infra-ready-mount:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  virt-share-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/kubevirt
    HostPathType:  
  libvirt-runtime:
    Type:    EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:  
  ephemeral-disks:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:      
QoS Class:       Burstable
Node-Selectors:  kubevirt.io/schedulable=true
Tolerations:     node.kubernetes.io/memory-pressure:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From                   Message
  ----     ------     ----                   ----                   -------
  Normal   Scheduled  2m49s                  default-scheduler      Successfully assigned default/virt-launcher-vm-cirros-v89js to 172.16.17.35
  Normal   Pulled     2m48s                  kubelet, 172.16.17.35  Container image "icpdev.icp:8500/kubevirtimg/cirros-container-disk-demo:1.3.0" already present on machine
  Normal   Created    2m48s                  kubelet, 172.16.17.35  Created container
  Normal   Started    2m47s                  kubelet, 172.16.17.35  Started container
  Normal   Pulled     2m47s                  kubelet, 172.16.17.35  Container image "icpdev.icp:8500/kubevirtimg/virt-launcher:1.3.0" already present on machine
  Normal   Created    2m47s                  kubelet, 172.16.17.35  Created container
  Normal   Started    2m47s                  kubelet, 172.16.17.35  Started container
  Warning  Unhealthy  2m42s (x2 over 2m44s)  kubelet, 172.16.17.35  Readiness probe failed: cat: /var/run/kubevirt-infra/healthy: No such file or directory
```

**Comment by cynepco3hahue** [comment]
@yu2003w What exactly version of the virt-launcher do you use? Because I can see it uses `icpdev.icp:8500/kubevirtimg/virt-launcher:1.3.0`, on top of what tag did you use it?
Worth to try to deploy KubeVirt with the latest release manifests from the GitHub and retry to start the VMI.

**Comment by yu2003w** [comment]
@cynepco3hahue  I checked out code from master branch and built with tag 1.3.0.
My dev environment consists of 3 nodes installed same version of ubuntu.(18.04)
When vm is scheduled into one machine, it failed to start. If it's scheduled to the other two nodes, it works well.
I didn't find out any difference between the machines.
Any advice?

**Comment by cynepco3hahue** [comment]
@yu2003w Thanks for the answer, now that you specified that two machines succeeded to start the VMI, the only thought that I have is different in the hardware and maybe some BIOS options are missing :confused:

**Comment by yu2003w** [comment]
@cynepco3hahue I also ran Virt-host-validate on all of my VMs and got the same output.
```
virt-host-validate qemu
  QEMU: Checking for hardware virtualization                                 : PASS
  QEMU: Checking if device /dev/kvm exists                                   : PASS
  QEMU: Checking if device /dev/kvm is accessible                            : PASS
  QEMU: Checking if device /dev/vhost-net exists                             : PASS
  QEMU: Checking if device /dev/net/tun exists                               : PASS
  QEMU: Checking for cgroup 'memory' controller support                      : PASS
  QEMU: Checking for cgroup 'memory' controller mount-point                  : PASS
  QEMU: Checking for cgroup 'cpu' controller support                         : PASS
  QEMU: Checking for cgroup 'cpu' controller mount-point                     : PASS
  QEMU: Checking for cgroup 'cpuacct' controller support                     : PASS
  QEMU: Checking for cgroup 'cpuacct' controller mount-point                 : PASS
  QEMU: Checking for cgroup 'cpuset' controller support                      : PASS
  QEMU: Checking for cgroup 'cpuset' controller mount-point                  : PASS
  QEMU: Checking for cgroup 'devices' controller support                     : PASS
  QEMU: Checking for cgroup 'devices' controller mount-point                 : PASS
  QEMU: Checking for cgroup 'blkio' controller support                       : PASS
  QEMU: Checking for cgroup 'blkio' controller mount-point                   : PASS
  QEMU: Checking for device assignment IOMMU support                         : WARN (No ACPI DMAR table found, IOMMU either disabled in BIOS or not supported by this hardware platform)
```
VMs in my dev environments are provisioned by IaaS. It seemed that it's a little difficult to determine the root cause for the issue.

**Comment by yu2003w** [comment]
@cynepco3hahue   I deployed two vmi-fedora on different nodes again, one worked and the other did not.
From /var/log/libvirt/qemu/{ns}vmi-fedora.log, there is some difference.
For the worked vmi, log is as below,
```
-object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-1-vmtest_vmi-fedora/master-key.aes \
-machine pc-q35-3.1,accel=kvm,usb=off,dump-guest-core=off \
-cpu Broadwell-IBRS,vme=on,ss=on,f16c=on,rdrand=on,hypervisor=on,arat=on,tsc_adjust=on,ssbd=on,xsaveopt=on,abm=on,invpcid=off \
-m 977 \
-realtime mlock=off \
```

For the failed VMI, the logs is as follow,
```
-object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-1-default_vmi-fedora/master-key.aes \
-machine pc-q35-3.1,accel=kvm,usb=off,dump-guest-core=off \
-cpu Broadwell-IBRS,vme=on,ss=on,vmx=on,f16c=on,rdrand=on,hypervisor=on,arat=on,tsc_adjust=on,mpx=on,avx512f=on,avx512cd=on,ssbd=on,xsaveopt=on,abm=on,invpcid=off \
-m 977 \
-realtime mlock=off \
```
Comparing the logs, failed VMI had additional parameters "vmx=on,mpx=on,avx512f=on,avx512cd=on".
Is it possibly the cause for this problem? How could I disable mpx, avx512f and avx512cd to try again?

**Comment by cynepco3hahue** [comment]
@yu2003w Do these two hosts CPU also have different flags? You can try to specific CPU features via https://github.com/kubevirt/kubevirt/blob/master/pkg/api/v1/schema.go#L214, so try to specify only features that are existing under the working VM.

**Comment by cynepco3hahue** [comment]
An additional thought, that it can be a problem with kernel versions.

**Comment by yu2003w** [comment]
@cynepco3hahue Yes, the two hosts have different flags.
Output of 'lscpu' from failed hosts as below,
```
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov 
pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc 
rep_good nopl cpuid pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic 
movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 
3dnowprefetch invpcid_single pti ssbd ibrs ibpb tpr_shadow vnmi flexpriority ept vpid 
fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm 
mpx avx512f rdseed adx smap avx512cd xsaveopt
```
Output from worked host as below,
```
Flags:               fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov 
pat pse36 clflush mmx fxsr sse sse2 ss syscall nx pdpe1gb rdtscp lm constant_tsc 
rep_good nopl cpuid pni pclmulqdq vmx ssse3 fma cx16 pcid sse4_1 sse4_2 x2apic 
movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand hypervisor lahf_lm abm 
3dnowprefetch invpcid_single pti ssbd ibrs ibpb tpr_shadow vnmi flexpriority ept vpid 
fsgsbase bmi1 hle avx2 smep bmi2 erms invpcid rtm 
rdseed adx smap xsaveopt
```
'uname -a' from both worker nodes is the same as below,
```
4.15.0-47-generic #50-Ubuntu SMP Wed Mar 13 10:44:52 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
The two vms are most likely provisioned from different bare metal by IaaS. 
I will try to specify cpu features as your advice.

**Comment by yu2003w** [comment]
@cynepco3hahue  I tried to disable cpu features in vmi-fedora.yaml as below,
```
cpu:
      features:
      - name: "mpx"
        policy: disable
      - name: "avx512f"
        policy: disable
      - name: "avx512cd"
        policy: disable
```
Then ran the test again, however, it still failed with following log,
```
-cpu Broadwell-IBRS,vme=on,ss=on,f16c=on,rdrand=on,hypervisor=on,arat=on,tsc_adjust=on,
mpx=off,avx512f=off,avx512cd=off,ssbd=on,xsaveopt=on,abm=on,invpcid=off \
```
Worked VMI log is as below,
```
-cpu Broadwell-IBRS,vme=on,ss=on,f16c=on,rdrand=on,hypervisor=on,arat=on,tsc_adjust=on,
ssbd=on,xsaveopt=on,abm=on,invpcid=off \
```
It looks like the problem is not caused by cpu flags.
And now I don't have any ideas about this issue.

**Comment by rmohr** [comment]
On Fri, May 31, 2019 at 8:12 AM Jared <notifications@github.com> wrote:

> @cynepco3hahue <https://github.com/cynepco3hahue> I tried to disable cpu
> features in vmi-fedora.yaml as below,
>
> cpu:
>       features:
>       - name: "mpx"
>         policy: disable
>       - name: "avx512f"
>         policy: disable
>       - name: "avx512cd"
>         policy: disable
>
> Then ran the test again, however, it still failed with following log,
>
> -cpu Broadwell-IBRS,vme=on,ss=on,f16c=on,rdrand=on,hypervisor=on,arat=on,tsc_adjust=on,
> mpx=off,avx512f=off,avx512cd=off,ssbd=on,xsaveopt=on,abm=on,invpcid=off \
>
> Worked VMI log is as below,
>
> -cpu Broadwell-IBRS,vme=on,ss=on,f16c=on,rdrand=on,hypervisor=on,arat=on,tsc_adjust=on,
> ssbd=on,xsaveopt=on,abm=on,invpcid=off \
>
> It looks like the problem is not caused by cpu flags.
> And now I don't have any ideas about this issue.
>

Really hard to tell. I guess the best would be to open a bugzilla ticket (
bigzilla.redhat.com) and directly ask the qemu/kvm guys there for help.

**Comment by yu2003w** [comment]
@rmohr  I will open bugzilla ticket. Now I closed this issue.
Thanks all your guys for helping me a lot.

**Comment by cynepco3hahue** [comment]
@yu2003w Can you add the link on the BZ? I am really curious what the reason after this failure.

**Comment by yu2003w** [comment]
https://bugs.launchpad.net/qemu/+bug/1833204
@rmohr @cynepco3hahue  Issue opened against Ubuntu/qemu
