### ISSUE TITLE
Shared cluster storage for scalable local images

### ISSUE THREAD

**Issue by Bashorsselenberg** [kubevirt/kubevirt#2320]
FEATURE REQUEST:

Currently using a single node Kubernetes Kubeadm cluster, using local (windows 10) images in a pvc on a hostpath. When a node fails, the vm's are not accesible (ofcourse).
I was wondering if there are possibilities (like using rook.io) for cluster storage, in order to get windows 10 virtual machines scalable on the cluster, and having the benefits of high availability. Couldn't find solutions for this specific use case yet.

Thanks in advance.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cynepco3hahue** [comment]
@Bashorsselenberg We have the possibility to configure `restartPolicy` on the VM, that will restart the VM in case of failure, but it will not help in cases when the node unresponsive, in this case, we follow the k8s flow.
But you can find some automatic solutions to remove the unhealthy node from the environment or if you run on top of cloud provider it can remove and add a new one.
You can find more information under the https://github.com/openshift/machine-api-operator

**Comment by fabiand** [comment]
Resolving an unknown node state requires user intervention, just like it is the case for pods.
Now, once that is resolved, then your VM should start again.

And Yes. You can use rook with kubevirt.
@igoihman @aglitke @j-griffith any pointers for this?

Let me note that for the bare metal case some kind of node fencing is needed to avoid data corruption.
Take also a look at @metal3-io which is looking at bm deployment

**Comment by j-griffith** [comment]
> And Yes. You can use rook with kubevirt.
> @igoihman @aglitke @j-griffith any pointers for this?
> 
Hi @Bashorsselenberg as @fabiand mentioned you can in fact use Rook here, you can even set it up in a single node model if you need to.  Feel free to reach out if you need anything on this; like I said I use it quite a bit.
