### ISSUE TITLE
kubevirt - VM creation failed on OCP4.1 rc5 

### ISSUE THREAD

**Issue by DirectedSoul1** [kubevirt/kubevirt#2336]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Bug Report

**What happened**:
After installing kubevirt CR on OCP4.1 rc5 , `virt-handler`, `virt-api` and `virt-controller` not coming up which in turn fails the VM deployment.

**What you expected to happen**:
All the `virt-*` pods should be up and running after kubevirt CR is installed and creation of VM should be successful.

**How to reproduce it (as minimally and precisely as possible)**:
Follow the steps 
-> Enable nested Virtualization
-> Install a kubevirt Operator
-> Install kubevirt CR
-> deploy and test a sample VM.

**Anything else we need to know?**:
```
kubevirt version 0.17.0
```
**Environment**:
- KubeVirt version (use `virtctl version`):
```
./virtctl version
Client Version: version.Info{GitVersion:"v0.17.0", GitCommit:"c0f960702dce718419a767f3913669f539229ff0", GitTreeState:"clean", BuildDate:"2019-05-05T08:09:14Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
the server could not find the requested resource
```
- Kubernetes version (use `kubectl version`):
```
oc version
Client Version: version.Info{Major:"4", Minor:"1+", GitVersion:"v4.1.0", GitCommit:"2793c3316", GitTreeState:"", BuildDate:"2019-04-23T07:46:06Z", GoVersion:"", Compiler:"", Platform:""}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+f2cc675", GitCommit:"f2cc675", GitTreeState:"clean", BuildDate:"2019-05-18T00:35:43Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications:
```
oc apply -f https://raw.githubusercontent.com/kubevirt/kubevirt.github.io/master/labs/manifests/vm.yaml
```
- Cloud provider or hardware configuration:
```
OCP4.1 on AWS 
```
- OS (e.g. from /etc/os-release):
```
cat /etc/os-release 
NAME=Fedora
VERSION="29 (Workstation Edition)"
ID=fedora
VERSION_ID=29
VERSION_CODENAME=""
PLATFORM_ID="platform:f29"
PRETTY_NAME="Fedora 29 (Workstation Edition)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:29"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f29/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=29
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=29
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"
VARIANT="Workstation Edition"
VARIANT_ID=workstation
```
- Kernel (e.g. `uname -a`):
```
uname -a
Linux localhost.localdomain 5.0.9-200.fc29.x86_64 #1 SMP Mon Apr 22 00:55:30 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
```
oc get all -n kubevirt
NAME                                READY   STATUS    RESTARTS   AGE
pod/virt-operator-87cf8d97b-h5hc9   1/1     Running   0          70m
pod/virt-operator-87cf8d97b-lsq9v   1/1     Running   0          70m

NAME                                  TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
service/kubevirt-prometheus-metrics   ClusterIP   172.30.121.203   <none>        443/TCP   58m
service/virt-api                      ClusterIP   172.30.21.11     <none>        443/TCP   58m

NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/virt-operator   2/2     2            2           70m

NAME                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/virt-operator-87cf8d97b   2         2         2       70m
```
- Others:
Error observed 
```
oc apply -f https://raw.githubusercontent.com/kubevirt/kubevirt.github.io/master/labs/manifests/vm.yaml
Error from server (InternalError): error when creating "https://raw.githubusercontent.com/kubevirt/kubevirt.github.io/master/labs/manifests/vm.yaml": Internal error occurred: failed calling webhook "virtualmachines.kubevirt.io-tmp-validator": Post https://fake-validation-service.kubevirt.svc:443/fake-path/virtualmachines.kubevirt.io?timeout=30s: service "fake-validation-service" not found
```

**Comment by SchSeba** [comment]
Hi @DirectedSoul1 thank for reporting this can you please show the logs from both operators?

**Comment by cynepco3hahue** [comment]
@DirectedSoul1 I can be related to the issue https://github.com/kubevirt/kubevirt/pull/2285, can you try to deploy from the master?

**Comment by DirectedSoul1** [comment]
so the latest will be 0.17.1-alpha ?

**Comment by DirectedSoul1** [comment]
Im following this doc https://kubevirt.io//quickstart_minikube/#deploy-kubevirt and for 
```export KUBEVIRT_VERSION="v0.17.1-alpha.0"``` and Im getting an error
```
kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${KUBEVIRT_VERSION}/kubevirt-operator.yaml
error: unable to read URL "https://github.com/kubevirt/kubevirt/releases/download/v0.17.1-alpha.0/kubevirt-operator.yaml", server reported 404 Not Found, status code=404
```

**Comment by DirectedSoul1** [comment]
> Hi @DirectedSoul1 thank for reporting this can you please show the logs from both operators?

```
oc logs pods/virt-operator-87cf8d97b-nmr5w -n kubevirt
ERROR: logging before flag.Parse: W0603 18:51:21.650434       1 client_config.go:548] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"component":"virt-operator","level":"info","msg":"we are on openshift","pos":"application.go:160","timestamp":"2019-06-03T18:51:21.680584Z"}
{"component":"virt-operator","level":"info","msg":"Operator image: index.docker.io/kubevirt/virt-operator:v0.17.0","pos":"application.go:176","timestamp":"2019-06-03T18:51:21.680923Z"}
{"component":"virt-operator","level":"info","msg":"Attempting to aquire leader status","pos":"application.go:253","timestamp":"2019-06-03T18:51:22.417382Z"}
ERROR: logging before flag.Parse: I0603 18:51:22.417455       1 leaderelection.go:205] attempting to acquire leader lease  kubevirt/virt-operator...
```

**Comment by slintes** [comment]
@DirectedSoul1 there should be 2 operator pods, one of them is leader and doing the work, the other one is backup and trying to get leader. You posted logs of the backup. Can you please post logs of the other one?

**Comment by slintes** [comment]
> Im following this doc https://kubevirt.io//quickstart_minikube/#deploy-kubevirt and for
> `export KUBEVIRT_VERSION="v0.17.1-alpha.0"` and Im getting an error
> 
> ```
> kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${KUBEVIRT_VERSION}/kubevirt-operator.yaml
> error: unable to read URL "https://github.com/kubevirt/kubevirt/releases/download/v0.17.1-alpha.0/kubevirt-operator.yaml", server reported 404 Not Found, status code=404
> ```

seems the release for that tag failed, will have a look

**Comment by slintes** [comment]
> > Im following this doc https://kubevirt.io//quickstart_minikube/#deploy-kubevirt and for
> > `export KUBEVIRT_VERSION="v0.17.1-alpha.0"` and Im getting an error
> 
> seems the release for that tag failed, will have a look

the build failed because of a failed download, cause by a version update of a dependency. Was fixed in the meanwhile, but that means no release artifacts for 0.17.1-alpha.0. But AFAIK we will have a 0.18.0 build very soon.

**Comment by DirectedSoul1** [comment]
> @DirectedSoul1 there should be 2 operator pods, one of them is leader and doing the work, the other one is backup and trying to get leader. You posted logs of the backup. Can you please post logs of the other one?

The logs of the leader pod
```
{"component":"virt-operator","level":"info","msg":"serviceaccount kubevirt-controller already exists and is up-to-date","pos":"create.go:1106","timestamp":"2019-06-04T12:45:15.053165Z"}
{"component":"virt-operator","level":"info","msg":"serviceaccount kubevirt-handler already exists and is up-to-date","pos":"create.go:1106","timestamp":"2019-06-04T12:45:15.053194Z"}
{"component":"virt-operator","kind":"KubeVirt","level":"error","msg":"Failed to create all resources: unable to patch scc: the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json","name":"kubevirt","namespace":"kubevirt","pos":"kubevirt.go:858","timestamp":"2019-06-04T12:45:15.054599Z","uid":"d702fe01-8630-11e9-8006-0a9e29790642"}
{"component":"virt-operator","level":"info","msg":"reenqueuing KubeVirt kubevirt/kubevirt","pos":"kubevirt.go:419","reason":"unable to patch scc: the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json","timestamp":"2019-06-04T12:45:15.054655Z"}
ERROR: logging before flag.Parse: W0604 12:45:34.987956       1 reflector.go:270] pkg/controller/virtinformers.go:191: watch of *v1.ConfigMap ended with: too old resource version: 358628 (360054)
ERROR: logging before flag.Parse: W0604 12:51:10.992714       1 reflector.go:270] pkg/controller/virtinformers.go:191: watch of *v1.ConfigMap ended with: too old resource version: 360204 (361582)
```

**Comment by DirectedSoul1** [comment]
> > @DirectedSoul1 there should be 2 operator pods, one of them is leader and doing the work, the other one is backup and trying to get leader. You posted logs of the backup. Can you please post logs of the other one?
> 
> The logs of the leader pod
> 
> ```
> {"component":"virt-operator","level":"info","msg":"serviceaccount kubevirt-controller already exists and is up-to-date","pos":"create.go:1106","timestamp":"2019-06-04T12:45:15.053165Z"}
> {"component":"virt-operator","level":"info","msg":"serviceaccount kubevirt-handler already exists and is up-to-date","pos":"create.go:1106","timestamp":"2019-06-04T12:45:15.053194Z"}
> {"component":"virt-operator","kind":"KubeVirt","level":"error","msg":"Failed to create all resources: unable to patch scc: the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json","name":"kubevirt","namespace":"kubevirt","pos":"kubevirt.go:858","timestamp":"2019-06-04T12:45:15.054599Z","uid":"d702fe01-8630-11e9-8006-0a9e29790642"}
> {"component":"virt-operator","level":"info","msg":"reenqueuing KubeVirt kubevirt/kubevirt","pos":"kubevirt.go:419","reason":"unable to patch scc: the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json","timestamp":"2019-06-04T12:45:15.054655Z"}
> ERROR: logging before flag.Parse: W0604 12:45:34.987956       1 reflector.go:270] pkg/controller/virtinformers.go:191: watch of *v1.ConfigMap ended with: too old resource version: 358628 (360054)
> ERROR: logging before flag.Parse: W0604 12:51:10.992714       1 reflector.go:270] pkg/controller/virtinformers.go:191: watch of *v1.ConfigMap ended with: too old resource version: 360204 (361582)
> ```

Again the configMap APi version seems to be too old , can that be an issue? 
Following the configMap creation part of this link
https://kubevirt.io//quickstart_minikube/#deploy-kubevirt

**Comment by cynepco3hahue** [comment]
@DirectedSoul1 It exactly the issue that I specified above
```
{"component":"virt-operator","kind":"KubeVirt","level":"error","msg":"Failed to create all resources: unable to patch scc: the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json","name":"kubevirt","namespace":"kubevirt","pos":"kubevirt.go:858","timestamp":"2019-06-04T12:45:15.054599Z","uid":"d702fe01-8630-11e9-8006-0a9e29790642"}
{"component":"virt-operator","level":"info","msg":"reenqueuing KubeVirt kubevirt/kubevirt","pos":"kubevirt.go:419","reason":"unable to patch scc: the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json","timestamp":"2019-06-04T12:45:15.054655Z"}
```
It should be fixed in the next release

**Comment by DirectedSoul1** [comment]
Thanks for the info @cynepco3hahue , will that be v0.18.0 release tag?

**Comment by cynepco3hahue** [comment]
@DirectedSoul1  Yep, it should be, because we did not backport the fix to release-0.17

**Comment by DirectedSoul1** [comment]
Tested the VM creation using the 0.17.1 and clearly this succeeds. 

```
kubectl get vmis
NAME     AGE    PHASE     IP            NODENAME
testvm   104s   Running   10.128.2.20   ip-10-0-132-147.us-east-2.compute.internal
```
And this can now be closed.

**Comment by slintes** [comment]
great :+1: 
/close
