### ISSUE TITLE
how to expand vm's / directory

### ISSUE THREAD

**Issue by yu-yang2** [kubevirt/kubevirt#2362]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
I want to expand / directory under device /dev/vda1, but I can't find a way in document. where is the /dev/vda1 mount in the host? I don't know how to configure this.
```
[fedora@testvmi-nocloud ~]$ df -hl
Filesystem      Size  Used Avail Use% Mounted on
devtmpfs        454M     0  454M   0% /dev
tmpfs           468M     0  468M   0% /dev/shm
tmpfs           468M  512K  467M   1% /run
tmpfs           468M     0  468M   0% /sys/fs/cgroup
/dev/vda1       3.9G  1.1G  2.7G  29% /
tmpfs            94M     0   94M   0% /run/user/1000
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.18.0
- Kubernetes version (use `kubectl version`):  1.14.2
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): centos7
- Kernel (e.g. `uname -a`):  Linux k8s-master 4.4.140-1.el7.elrepo.x86_64 #1 SMP Wed Jul 11 15:57:14 EDT 2018 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by cynepco3hahue** [comment]
@yu-yang2 Can you please show the spec of the VMI?

**Comment by yu-yang2** [comment]
@cynepco3hahue here is the yaml
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: testvmi-nocloud
spec:
  terminationGracePeriodSeconds: 30
  domain:
    resources:
      requests:
        memory: 1024M
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - disk:
          bus: virtio
        name: cloudinitdisk
  volumes:
  - name: containerdisk
    containerDisk:
      image: test.harbor.domain/library/fedora30:latest
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
``

**Comment by petrkotas** [comment]
Hi @yu-yang2, do you mean expanding as in adding more space? If yes, this is not possible for containerdisk, since it is designed to be ephemeral.

If you want expanding disk, mount the volume via PVC from some persistent volume you have configured in your cluster.

**Comment by yu-yang2** [comment]
@petrkotas but where is my vm's `/dev/vda1` disk mount on my server? It takes me about `3.9G` disk space.

**Comment by petrkotas** [comment]
@yu-yang2 it is a container dist. That means it is stored in container registry as we have described in the [user guide](https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/disks-and-volumes.html#containerdisk). The idea of container disk, is to distribute ephemeral VM image as simple as possible and allow for easy multi machine deployment.

The mechanism of how it gets into the VM is as follows:

1) Volume container is added to the virt-launcher pod. The volume container contains the packaged VM disk. The disk image is directly ready to be used by QEMU.
2) The disk image from volume container is shared trough the shared mount from volume container to the compute container.
3) QEMU uses the VM disk image provided from shared mount from volume container.

When the VM is terminated, the volume is thrown away, no changes will survive.

**Comment by yu-yang2** [comment]
@petrkotas  Does this mean that the contents of the virtual machine will be cleaned up when the container is deleted? Is there a way to mount the vm's root directory ("/") to the physical machine's host directory to avoid container crash?

**Comment by petrkotas** [comment]
@yu-yang2 as I have already answered. You have to use different disk. You can use [PVC](https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/disks-and-volumes.html#persistentvolumeclaim) and mount your VM from there. 
For this you have to prepare the VM image yourself.

**Comment by yu-yang2** [comment]
@petrkotas thank you for your patience, I think I know how to do it.

**Comment by keepthemomentum** [comment]
@yangyuw Were you able to add space for /dev/vda1. Appreciate if you could share some info on how to do?
