### ISSUE TITLE
cluster-up/virtctl.sh not working

### ISSUE THREAD

**Issue by fedepaol** [kubevirt/kubevirt#2367]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
Can't run cluster-up/virtctl.sh :
```
cluster-up/virtctl.sh: line 40: /home/fedepaol/go/src/kubevirt.io/kubevirt/cluster-up//_out/cmd/virtctl/virtctl: No such file or directory
```

The virtctl cmd is deployed under `kubevirt/_out/cmd/virtctl` while the script looks for it into 
```
${KUBEVIRTCI_PATH}/_out/cmd/virtctl/virtctl
``` 
which get resolved into 
```
/cluster-up//_out/cmd/virtctl/virtctl
```

(there is also an extra `/` )

From https://github.com/kubevirt/kubevirt/blob/master/cluster-up/virtctl.sh#L40

**What you expected to happen**:

Being able to run cluster-up/virtctl.sh 

**How to reproduce it (as minimally and precisely as possible)**:
From a checkout, 
* `make` (in order to have the virtctl binary ready)
* make cluster-sync
* exec `cluster-up/virtctl.sh`

**Comment by mfranczy** [comment]
thanks for pointing that!

**Comment by fedepaol** [comment]
@mfranczy no problem!

I would have submitted a pr too but I wasn't sure about how to do it since the spirit of @davidvossel 's pr seemed to decouple the cluster-up thing from the hosting repo (`KUBEVIRT_PATH`), but for `virtctl` we still depend on the executable generated by the underlying project, which is not the case for `kubectl`.
