### ISSUE TITLE
Setting node selector on virt-handler daemonset

### ISSUE THREAD

**Issue by jeremyrogers** [kubevirt/kubevirt#2377]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

Is there a way to set a nodeSelector on the virt-handler DaemonSet object? I'm upgrading from kubevirt v0.15 to v0.18, and I used to add a nodeSelector to the DaemonSet manually when installing. Now that kubevirt is deployed with an operator, I'd like to keep that functionality somehow. I do have `kubevirt.io/schedulable=true` labels on the nodes that I want to select, but the virt-handler daemonset still tries to deploy on every node in the cluster. Thanks in advance.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.18.0
- Kubernetes version (use `kubectl version`): 
openshift v3.11.0+06cfa24-67
kubernetes v1.11.0+d4cacc0

**Comment by fabiand** [comment]
Heya. Yeah, that's an issue.

Did you try to patch the handler daemonset after deployment using a `kubectl patch`?

Its just a workaround but might help right now ..

**Comment by slintes** [comment]
Hi, a bit unrelated, but please use another label name for this. `kubevirt.io/schedulable=true` is used *BY* virt-handler in order to mark nodes which technically can deal with VMs. If you use it too, it ca happen that VMs are scheduled on nodes which can't deal with it.

**Comment by jeremyrogers** [comment]
Patching the daemonset worked; I was thinking the operator might overwrite changes, if it was declaratively managing the daemonset object. Thanks!

**Comment by fabiand** [comment]
Cool.
And yes - if the operator was stricter that would have happened ... we'll
probably encounter this in future again until we sort out how to do these
c(k)ustom things)

Do you mind adding a section to the kubevirt user guide i.e. here
https://github.com/kubevirt/user-guide/blob/master/administration/intro.adoc#cluster-side-add-on-deployment
with the titlte "Limiting KubeVirt to a sub-set of nodes" or alike ..

**Comment by jeremyrogers** [comment]
Here you go!
https://github.com/kubevirt/user-guide/pull/261

**Comment by fabiand** [comment]
That's awesome, thank you!
