### ISSUE TITLE
cluster-sync only works the first time

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#2380]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind enhancement

**What happened**:

When we started to source `clustser-up` in #2335, the image synchronization in https://github.com/kubevirt/kubevirt/blob/release-0.17/cluster/ephemeral-provider-common.sh#L44 got lost. Now `cluster-sync` only pushes the images to the registry, but if images with this name are already on the nodes, they are not pulled down. As a result we still see the code from the initial sync running.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by davidvossel** [comment]
I noticed this too yesterday.

I'll look into it. Something probably happened with the factoring out of cluster-up

**Comment by rmohr** [comment]
@cynepco3hahue you are already looking into this right? He thinks he removed it with the okd provider integration.
