### ISSUE TITLE
VM pods can only run in  Default Namespace

### ISSUE THREAD

**Issue by admiyo** [kubevirt/kubevirt#239]
Most code to select objects loos something like this:

restClient.Get().Resource(vmResource).Namespace(api.NamespaceDefault).Do()

Which means that Pods. VMs, etc all need to be created and maintained in the default namespace.

**Comment by rmohr** [comment]
Right. That is a current limitation of KubeVirt. I think we need to do the following thing, to change that:

1) Give the virt-controllers access to all namespaces
2) Make sure our controllers are doing queries based on the Document the controller loop is currently operating on.
3) The same for virt-handler

Also let's check if cross references of namespaces in the kubernetes resources like Deployments, RCs, ... are possible.

**Comment by rmohr** [comment]
@davidvossel maybe that is a nice task for you? But maybe you are already working on something?
