### ISSUE TITLE
Support different serial console types

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#2393]
/kind enhancement

**What happened**:
Today we use a virtio serial console IIRC.
This often works with guests, but some don't support a virtio serial console, or expect a different device (as in kubevirt/common-templates#5)

**What you expected to happen**:
The user has the ability to define a different serial console type (i.e. non-virtio)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fromanirh** [comment]
Looking at the code (master branch @052ade384 it seems to me it is the other way around: the only supported console device is "serial":  https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-launcher/virtwrap/api/converter.go#L926

AFAIK, emulated serial consoles are the most compatible, so this is a good default.
Do we want to add support for VirtIO consoles?

**Comment by fabiand** [comment]
Interesting, thanks for checking.
We have a few guests (OpenSUSE iirc) which have issues with the serial console. Maybe you can check what they expect and then we see if we need to adjust our code.

**Comment by fromanirh** [comment]
> Interesting, thanks for checking.
> We have a few guests (OpenSUSE iirc) which have issues with the serial console. Maybe you can check what they expect and then we see if we need to adjust our code in order to suppotr them.
> 
> (And there was a second guest where we had issues ....)

Sure, will have a look at our SUSE guests a soon as possible. Can't make promises about when, though.

**Comment by andreabolognani** [comment]
> We have a few guests (OpenSUSE iirc) which have issues with the serial console. Maybe you can check what they expect and then we see if we need to adjust our code in order to suppotr them.

What kind of issues are you talking about? No output showing up on the serial console, or something different?

In my experience the inability to use the serial console is almost always caused by the guest OS not being configured to do so: Fedora and RHEL are pretty good at enabling it automatically, Debian for example not so much.

In general, you want to make sure `console=ttys0` is present on the kernel command line and the `serial-getty@ttyS0.service` systemd unit is enabled. (This is for x86, of course, other architectures use slightly different names).

**Comment by fabiand** [comment]
Yes, I agree. It's porbably a guest configuraiton issue. But OTOH the opensuse cloud image is also able to run on OpenStack and there it's is likely providing serial console output.

IOW I'think we should have the ability to configure the VM (ABI) to macth what the gest expectecs.

For Fedora and RHEL serial console works (Yey), for OpenSUSE we might need something else ... Let#s see, thanks Francesco.
