### ISSUE TITLE
https://github.com/kubevirt/kubevirt/releases/download MISSING

### ISSUE THREAD

**Issue by jagusztinl** [kubevirt/kubevirt#2417]
Directory https://github.com/kubevirt/kubevirt/releases/download is disappeared!

**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind enhancement

**What happened**:
Tried to download kubevirt

**What you expected to happen**:
https://github.com/kubevirt/kubevirt/releases/download missing

**How to reproduce it (as minimally and precisely as possible)**:

Check it

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by petrkotas** [comment]
Hi @jagusztinl, it might have been that the directories changed. The current releases are located at https://github.com/kubevirt/kubevirt/releases. The most feature full release is v0.18.1.

Would you please share, where did you get the link, so we can fix it? Thank you.

**Comment by rmohr** [comment]
This https://github.com/kubevirt/kubevirt/releases was always the entrypoint to all releases. However if you download you have urls like https://github.com/kubevirt/kubevirt/releases/download/v0.18.1/kubevirt-operator.yaml
