### ISSUE TITLE
Deleting kv opeator fails

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#2427]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Installed KubeVirt with operator + CR, then removed CR, then tried to remove the operator using

```
kubectl delete -f https://github.com/kubevirt/kubevirt/releases/download/v0.18.1/kubevirt-operator.yaml
```

This command hang.

Upcon the next creation I get the following error:
```
$ kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/v0.18.1/kubevirt-operator.yaml
namespace/kubevirt unchanged
customresourcedefinition.apiextensions.k8s.io/kubevirts.kubevirt.io created
clusterrole.rbac.authorization.k8s.io/kubevirt.io:operator created
clusterrole.rbac.authorization.k8s.io/kubevirt-operator created
clusterrolebinding.rbac.authorization.k8s.io/kubevirt-operator created
Error from server (Forbidden): error when creating "https://github.com/kubevirt/kubevirt/releases/download/v0.18.1/kubevirt-operator.yaml": serviceaccounts "kubevirt-operator" is forbidden: unable to create new content in namespace kubevirt because it is being terminated
Error from server (Forbidden): error when creating "https://github.com/kubevirt/kubevirt/releases/download/v0.18.1/kubevirt-operator.yaml": deployments.apps "virt-operator" is forbidden: unable to create new content in namespace kubevirt because it is being terminated
```

**What you expected to happen**:
KubeVirt to be deleted

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yu2003w** [comment]
I also met similar problem when I tried kubevirt first time.
It seemed that crd kv was not deleted as expectedly.
