### ISSUE TITLE
Rescheduling issue with VM/Pod

### ISSUE THREAD

**Issue by x8091** [kubevirt/kubevirt#2443]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**: When the worker node (which hosts the VM/pod) became Not Ready state (by poweroff for example), the VM didn't get rescheduling to another nodes, it just keep staying in Terminating state.

**What you expected to happen**: The VM terminate successfully and re-create on another node.

**How to reproduce it (as minimally and precisely as possible)**: A cluster with 3 worker nodes, all of them can create VMs by kubevirt (tested by using node selector).

**Anything else we need to know?**: When testing with regular pods, rescheduling works fine.

**Environment**:
- KubeVirt version (use `virtctl version`): 0.18.1
- Kubernetes version (use `kubectl version`): 1.14.2
- VM or VMI specifications: 
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu 18.04.2 LTS
- Kernel (e.g. `uname -a`): 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by cynepco3hahue** [comment]
In general, we can not know if it was the poweroff issue, or maybe kubelet crashed, so it possible situation when the node has `NotReady` state, but the VM that runs on this node still continue to write on the storage. In this case similar to k8s we do not restart the VM on the other node until an admin will remove it to avoid data corruption.
We have some solutions to make this process automate, but it depends on the cluster-api, see https://github.com/openshift/machine-api-operator for more details.
