### ISSUE TITLE
add Dockerfile

### ISSUE THREAD

**Issue by lurenjia528** [kubevirt/kubevirt#2448]
on some other machine ,such as arm64, dockerhub don't have image, and in China ,the network problem, so need go build and docker build  Manually, so suggest recovery the Dockerfile (virt-api  virt-controller  virt-handler  virt-launcher  virt-operator)(include kubevirt/libvirt)

**Comment by slintes** [comment]
Hi @lurenjia528, we are using bazel in the meanwhile for building the images. Maybe you can use that too?
There is a similar ongoing effort for ppc64le, see https://github.com/kubevirt/kubevirt/pull/2145. I'm sure about its status, but it might help you.

**Comment by lurenjia528** [comment]
thanks, but no effort ,I accord to the Dockerfile from version v0.14.0 ,and build the image on arm64,
can you please see #2457 ? Thanks
