### ISSUE TITLE
virt-handler image is missing qemu binary

### ISSUE THREAD

**Issue by admiyo** [kubevirt/kubevirt#246]
on openshift origin

creating a VM fails.  The following is from kubectl logs  -n kube-system virt-handler-{id}

evel=error timestamp=2017-06-08T01:23:54.789387Z pos=vm.go:152 component=virt-handler name=testvm kind=VM uid=d65d7b5b-4bab-11e7-a126-1c666d8b0614 reason="virError(Code=38, Domain=10, Message='Cannot check QEMU binary /usr/local/bin/qemu-x86_64: No such file or directory')" msg="Synchronizing the VM failed."

**Comment by rmohr** [comment]
@admiyo Could you check if you are running the right libvirt image? 

This is note virt-handler who does not find the binary (which is by the way the emulator script when I look at the path), it is libvirt reporting to virt-handler, when virt-handler tries to start a VM.

**Comment by fabiand** [comment]
Looks like this got fixed.
