### ISSUE TITLE
SyncVMI sometimes fails with "context deadline exceeded" (not only) during migrations

### ISSUE THREAD

**Issue by slintes** [kubevirt/kubevirt#2471]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Mostly during migrations, but also on other tests (see 1st comment), SyncVMI sometimes fails with "context deadline exceeded". During our CI tests this results in a test failure, because this triggers an unexpected warning event. However, if you ignore this warning, SyncVMI succeeds on the next try.

e.g.:
```
[rfe_id:393][crit:high[vendor:cnv-qe@redhat.com][level:system] VM Live Migration Starting a VirtualMachineInstance with auto converge enabled should complete a migration expand_less | 6m7s
-- | --
/root/go/src/kubevirt.io/kubevirt/tests/migration_test.go:431 Unexpected Warning event received: testvmid6j2tfjm72qrwn5wsnsn6p4g2rbt9ft9mdnp9h9n55ln5gnw,a9419b63-a29a-11e9-b527-525500d15501: unknown error encountered sending command SyncVMI: rpc error: code = DeadlineExceeded desc = context deadline exceeded Expected     <string>: Warning not to equal     <string>: Warning /root/go/src/kubevirt.io/kubevirt/tests/utils.go:348
```

**What you expected to happen**:
No SyncVMI failures, no warning events during migrations

**How to reproduce it (as minimally and precisely as possible)**:
not 100% reproducable
see e.g. cri-o CI test lane on this PR, there it happened several times: https://prow.apps.ovirt.org/pr-history/?org=kubevirt&repo=kubevirt&pr=2459
I also experienced this regularly while working on the NFS migration test.

**Comment by slintes** [comment]
saw the same error on a non migration test:
```
[rfe_id:694][crit:medium][vendor:cnv-qe@redhat.com][level:component]Networking VirtualMachineInstance with TX offload disabled [test_id:1781]should get turned off for interfaces that serve dhcp

/root/go/src/kubevirt.io/kubevirt/tests/vmi_networking_test.go:769
Unexpected Warning event received: testvmibvjv45b4jw4chlzfzr5r24p2lt9mjlzpgkvvgmxb4v95pt4x,d400e7df-a382-11e9-9b17-525500d15501: unknown error encountered sending command SyncVMI: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Expected
<string>: Warning
not to equal
<string>: Warning
/root/go/src/kubevirt.io/kubevirt/tests/utils.go:348
```

**Comment by slintes** [comment]
and another one, not on migration...
```/root/go/src/kubevirt.io/kubevirt/tests/operator_test.go:479
Unexpected Warning event received: testvmighbtflbg2s4hsfsj2vr4v6jbswz2ndqln2jglqnq9rj755kk,c5f8fa3f-a88b-11e9-95cb-525500d15501: unknown error encountered sending command SyncVMI: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Expected
    <string>: Warning
not to equal
    <string>: Warning
/root/go/src/kubevirt.io/kubevirt/tests/utils.go:348```

**Comment by slintes** [comment]
another one:
```
/root/go/src/kubevirt.io/kubevirt/tests/config_test.go:324
Unexpected Warning event received: testvmivsld2tf647lsmcb2h4qzhpjvf6tc5kgp5zw2btlr2kkhkqxv,d9a8c38e-ab59-11e9-808b-525500d15501: unknown error encountered sending command SyncVMI: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Expected
    <string>: Warning
not to equal
    <string>: Warning
/root/go/src/kubevirt.io/kubevirt/tests/utils.go:350
```

**Comment by slintes** [comment]
```
/root/go/src/kubevirt.io/kubevirt/tests/vmi_networking_test.go:613
Unexpected Warning event received: testvmis2gfk2bbjbz6flqn8h8j6w8zpctnx78wt8h2pgngvgpv69jm,0a5a13ac-abc9-11e9-85a6-525500d15501: unknown error encountered sending command SyncVMI: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Expected
    <string>: Warning
not to equal
    <string>: Warning
/root/go/src/kubevirt.io/kubevirt/tests/utils.go:350
```

**Comment by fedepaol** [comment]
Just happened to me:

```
/root/go/src/kubevirt.io/kubevirt/tests/vmi_multus_test.go:675
Unexpected Warning event received: testvmim4xrqg9gzdx2rmhrljgx9txxxqdrmnb9dq8hwlwm69t2mj69,724975d1-ad4c-11e9-93f0-0242ac110002: unknown error encountered sending command SyncVMI: rpc error: code = DeadlineExceeded desc = context deadline exceeded
Expected
    <string>: Warning
not to equal
    <string>: Warning
/root/go/src/kubevirt.io/kubevirt/tests/utils.go:350
```

**Comment by vladikr** [comment]
I think that in all of these examples we also must look at the virt-launcher log.
The `DeadlineExceeded` error just means that virt-launcher didn't respond on time.
In the case of NFS, we know that libvirt create command is blocking and it never returned, leaving the virt-launcher stuck.
As for the other cases, we need at least to look at the virt-launcher logs.

**Comment by fedepaol** [comment]
In my case I think the guest just takes more than 5 seconds for be activated.

The following happened on three consecutive runs of the CI lane I am trying to setup, now it's not happening anymore.

On the virt-handler logs I see:
```
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"testvmibcp9mkt6zh897jbg6fhcwfjgqj85jv6tjt2pz4w88q5mvph4","namespace":"kubevirt-test-default","pos":"vm.go:883","reason":"unknown error encountered sending command SyncVMI: rpc error: code = DeadlineExceeded desc = context deadline exceeded","timestamp":"2019-07-23T16:47:25.855636Z","uid":"69eebad8-ad69-11e9-bab5-0242ac110002"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance kubevirt-test-default/testvmibcp9mkt6zh897jbg6fhcwfjgqj85jv6tjt2pz4w88q5mvph4","pos":"vm.go:559","reason":"unknown error encountered sending command SyncVMI: rpc error: code = DeadlineExceeded desc = context deadline exceeded","timestamp":"2019-07-23T16:47:26.568953Z"}
```

So the call must have started at ~ 16:47:20

On the virt launcher I see 
```
{"component":"virt-launcher","kind":"","level":"info","msg":"Domain defined.","name":"testvmibcp9mkt6zh897jbg6fhcwfjgqj85jv6tjt2pz4w88q5mvph4","namespace":"kubevirt-test-default","pos":"manager.go:893","timestamp":"2019-07-23T16:47:22.004576Z","uid":"69eebad8-ad69-11e9-bab5-0242ac110002"}
...
{"component":"virt-launcher","kind":"","level":"info","msg":"Domain started.","name":"testvmibcp9mkt6zh897jbg6fhcwfjgqj85jv6tjt2pz4w88q5mvph4","namespace":"kubevirt-test-default","pos":"manager.go:924","timestamp":"2019-07-23T16:47:36.388656Z","uid":"69eebad8-ad69-11e9-bab5-0242ac110002"}
```

Which should be the activation of the guest, which took roughly 14 seconds to happen.
If I understood correctly, the handler tries again in case of failure:

```
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance kubevirt-test-default/testvmibcp9mkt6zh897jbg6fhcwfjgqj85jv6tjt2pz4w88q5mvph4","pos":"vm.go:559","reason":"unknown error encountered sending command SyncVMI: rpc error: code = DeadlineExceeded desc = context deadline exceeded","timestamp":"2019-07-23T16:47:26.568953Z"}
```
until it's satisfied.


This is also confirmed by what I see on the launcher. There are three of these:
```
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"testvmibcp9mkt6zh897jbg6fhcwfjgqj85jv6tjt2pz4w88q5mvph4","namespace":"kubevirt-test-default","pos":"server.go:166","timestamp":"2019-07-23T16:47:36.391049Z","uid":"69eebad8-ad69-11e9-bab5-0242ac110002"}
```
My understanding is that the 3 calls where blocked on the mutex, and once the first call returned (the domain got activated), the others got in and took a lot less since there was no need for activation.

The whole logs can be found here https://paste.fedoraproject.org/paste/c~IBHyZIxCTbwHUyEMa84w


Now my question is, what should we do on a testing point of view from this scenario? 
Where my test is failing is on [waitForVMIPhase](https://github.com/kubevirt/kubevirt/blob/8db8d9e8eda82da7decc2a14b684c0ebe0ac7dd6/tests/utils.go#L2153)  where the watcher is interested for `Started` events and "incidentally" traps any warning passing by and fails with that.

If there were real problems, I _think_ the guest would never reach the started phase and so the test would have failed even if we ignored that specific errors so probably the test would fail anyway with timeout.

**Comment by fromanirh** [comment]
It seems it boils down to this: the VM starts succesfully, but it is just too slow and the timeout triggers.
I wonder what's the proper solution here, since this can very much happen on production environment as well - plenty of cases from oVirt experience. Maybe we can start relaxing the timeout only on CI?

**Comment by fedepaol** [comment]
> I wonder what's the proper solution here, since this can very much happen on production 

And, I add, it won't even get noticed since it gets recovered by the retries.

**Comment by slintes** [comment]
tbh, the 5 seconds timeout was a quite random value chosen by me when refactoring the handler-launcher communication to GRPC a while ago. Would it make sense to increase it? What would be a good value? How long can a call to libvirt take?
For CI: the `waitForVMIPhase` func has a `ignoreWarnings` flag. I'm only a bit afraid that using this for "fixing" all the test where this warning occured might hide real, not time related issues, even though they are "self healing" by just retrying `SyncVMI` until it succeeds.

**Comment by fedepaol** [comment]
Yes I wasn't sure about what the _proper_ solution was. Ignoring all the warnings seems a bit too extreme to me. 

Maybe allow the watcher to filter not interesting warnings could be a way to do that (i.e. filtering out SyncVMI timeouts but still failing for all the other kind of warnings) but I don't have a strong opinion on that. Every solution we pick is a compromise, I'm afraid.

**Comment by cynepco3hahue** [comment]
IMHO we should just to ignore this specific warning because we have retry logic anyway.

**Comment by slintes** [comment]
Oh, with `might hide real, not time related issues` I also meant this timeout warning, because it might also be caused by other things than just "it takes longer than expected". E.g., for the NFS migration Vladik mentioned above, I increased the timeout to several minutes, didn't help. But the 2nd call always succeeded, also with a short timeout.
However, I agree that on the other hand this works the kubernetes way and as expected: in case of an error retry.
So, yes, (optionally?) ignoring this specific warning in the tests might be a good idea. Maybe with a limit of 3 times or so.

**Comment by fedepaol** [comment]
@slintes agree, but let's try with (at least) 5 attempts. My test took 14 seconds to spin the vm up so it would be a little on the edge.

I'll send a PR for this soon.

**Comment by oshoval** [comment]
/cc @xpivarc 

FYI, see please a previous research about the related warning, the findings and the discussion
