### ISSUE TITLE
Virtctl stuck at "The escape sequence is ^]"

### ISSUE THREAD

**Issue by mbhatnagar11** [kubevirt/kubevirt#2474]
- KubeVirt version = v0.15.0

I have created a vm using rest api : /apis/kubevirt.io/v1alpha3/namespaces/default/virtualmachines

Below is the json configuration passed to the rest api :

{"apiVersion":"kubevirt.io/v1alpha3","kind":"VirtualMachine","metadata":{"name":"vmwanoptimizer3"},"spec":{"running":true,"template":{"metadata":{"labels":{"kubevirt.io/size":"389a95f7-d272-4955-94bd-63c3bd46a471","kubevirt.io/domain":"vmwanoptimizer3"}},"spec":{"domain":{"resources":{"requests":{"memory":"2048"}},"devices":{"disks":[{"name":"rootfs","disk":{"bus":"virtio"}},{"name":"cloudinit","disk":{"bus":"virtio"}}],"interfaces":[{"name":"default","bridge":{}},{"name":"enp2s0","bridge":{}},{"name":"enp3s0","bridge":{}}]}},"terminationGracePeriodSeconds":0,"volumes":[{"containerDisk":{"image":"kubevirt/ubuntu-firewall"},"name":"rootfs"},{"cloudInitNoCloud":{"userData":"#!/bin/bash\nip a add 1.1.1.1/24 dev enp2s0\nip a add 2.2.2.2/24 dev enp3s0\nip link set dev enp2s0 up\nip link set dev enp3s0 up\nethtool --offload enp2s0 rx off tx off\nethtool -K enp2s0 gso off\nethtool --offload enp3s0 rx off tx off\nethtool -K enp3s0 gso off\nsysctl -w net.ipv4.conf.all.forwarding\u003d1\nip route add 1.1.1.0/24 via 4.4.4.1"},"name":"cloudinit"}],"networks":[{"name":"default","pod":{}},{"multus":{"networkName":"ovs-conf"},"name":"enp2s0"},{"multus":{"networkName":"ovs-conf-2"},"name":"enp3s0"}]}}}}

"kubectl get vms" command shows vm is in running state

"kubectl describe vms vmwanoptimizer3" command shows below output

Name:         vmwanoptimizer3
Namespace:    default
Labels:       <none>
Annotations:  <none>
API Version:  kubevirt.io/v1alpha3
Kind:         VirtualMachine
Metadata:
  Creation Timestamp:  2019-07-11T12:21:06Z
  Generation:          3
  Resource Version:    2630522
  Self Link:           /apis/kubevirt.io/v1alpha3/namespaces/default/virtualmachines/vmwanoptimizer3
  UID:                 5baf7ee6-a3d6-11e9-84a4-d4bed9eb3325
Spec:
  Running:  true
  Template:
    Metadata:
      Creation Timestamp:  <nil>
      Labels:
        Kubevirt . Io / Domain:  vmwanoptimizer3
        Kubevirt . Io / Size:    389a95f7-d272-4955-94bd-63c3bd46a471
    Spec:
      Domain:
        Devices:
          Disks:
            Disk:
              Bus:  virtio
            Name:   rootfs
            Disk:
              Bus:  virtio
            Name:   cloudinit
          Interfaces:
            Bridge:
            Name:  default
            Bridge:
            Name:  enp2s0
            Bridge:
            Name:  enp3s0
        Machine:
          Type:
        Resources:
          Requests:
            Memory:  2048
      Networks:
        Name:  default
        Pod:
        Multus:
          Network Name:  ovs-conf
        Name:            enp2s0
        Multus:
          Network Name:                  ovs-conf-2
        Name:                            enp3s0
      Termination Grace Period Seconds:  0
      Volumes:
        Container Disk:
          Image:  kubevirt/ubuntu-firewall
        Name:     rootfs
        Cloud Init No Cloud:
          User Data:  #!/bin/bash
ip a add 1.1.1.1/24 dev enp2s0
ip a add 2.2.2.2/24 dev enp3s0
ip link set dev enp2s0 up
ip link set dev enp3s0 up
ethtool --offload enp2s0 rx off tx off
ethtool -K enp2s0 gso off
ethtool --offload enp3s0 rx off tx off
ethtool -K enp3s0 gso off
sysctl -w net.ipv4.conf.all.forwarding=1
ip route add 1.1.1.0/24 via 4.4.4.1
        Name:  cloudinit
Status:
  Created:  true
  Ready:    true
Events:
  Type    Reason            Age   From                       Message
  ----    ------            ----  ----                       -------
  Normal  SuccessfulCreate  21m   virtualmachine-controller  Created virtual machine: vmwanoptimizer3

But when i use " ./virtctl console vmwanoptimizer3 " , it just hangs at 'Successfully connected to vmwanoptimizer3 console. The escape sequence is ^] '

**Comment by slintes** [comment]
Hi @mbhatnagar11,

where is your rootfs containerdisk `kubevirt/ubuntu-firewall` coming from, I don't see it on our docker hub account? Can you please provide logs of the VM's virt-launcher pod? And `kubectl describe virt-launcher-...` 

And please format the logs etc as code (surround them with backticks, or use the editor UI), that makes it much more readable :slightly_smiling_face: 

Last but not least: maybe you can also use a newer version of KubeVirt (latest is v0.19.0, see [0])? There have been many bugfixes since 0.15.

[0] https://github.com/kubevirt/kubevirt/releases

**Comment by mbhatnagar11** [comment]
- `kubevirt/ubuntu-firewall` is a custom image that I've created . 
- output for kubectl describe pod virt-launcher-vmwanoptimizer3-b78cz : 

`Name:               virt-launcher-vmwanoptimizer3-b78cz
Namespace:          default
Priority:           0
PriorityClassName:  <none>
Node:               ubuntu/172.19.63.21
Start Time:         Thu, 11 Jul 2019 17:51:07 +0530
Labels:             kubevirt.io=virt-launcher
                    kubevirt.io/created-by=5bb0ee9d-a3d6-11e9-84a4-d4bed9eb3325
                    kubevirt.io/domain=vmwanoptimizer3
                    kubevirt.io/size=389a95f7-d272-4955-94bd-63c3bd46a471
Annotations:        k8s.v1.cni.cncf.io/networks: ovs-conf,ovs-conf-2
                    k8s.v1.cni.cncf.io/networks-status:
                      [{
                          "name": "cbr0",
                          "ips": [
                              "10.244.0.13"
                          ],
                          "default": true,
                          "dns": {}
                      },{
                          "name": "ovs-conf",
                          "interface": "net1",
                          "mac": "02:00:00:c8:f9:f2",
                          "dns": {}
                      },{
                          "name": "ovs-conf-2",
                          "interface": "net2",
                          "mac": "02:00:00:25:47:25",
                          "dns": {}
                      }]
                    kubevirt.io/domain: vmwanoptimizer3
Status:             Running
IP:                 10.244.0.13
Controlled By:      VirtualMachineInstance/vmwanoptimizer3
Containers:
  volumerootfs:
    Container ID:  docker://ed3b7ef5644a1c77bbf1f91a2ce2f9cce7fcedced311ac71cacb96cd33510d85
    Image:         kubevirt/ubuntu-firewall
    Image ID:      docker://sha256:54ebb44fb48f25eeaeae6cf3021030254834b0f53fd2102e2255bf0a61b6c5c9
    Port:          <none>
    Host Port:     <none>
    Command:
      /entry-point.sh
    State:          Running
      Started:      Thu, 11 Jul 2019 17:51:16 +0530
    Ready:          True
    Restart Count:  0
    Readiness:      exec [cat /tmp/healthy] delay=2s timeout=5s period=5s #success=2 #failure=5
    Environment:
      COPY_PATH:  /var/run/kubevirt-ephemeral-disks/container-disk-data/default/vmwanoptimizer3/disk_rootfs/disk-image
    Mounts:
      /var/run/kubevirt-ephemeral-disks from ephemeral-disks (rw)
  compute:
    Container ID:  docker://f5b0ac749197e1dd96a2e35335c2d50092655500eb7406abeeb073702e5d72fe
    Image:         docker.io/kubevirt/virt-launcher:v0.15.0
    Image ID:      docker-pullable://kubevirt/virt-launcher@sha256:db18e2c332366807d30b518f3478b025e137e762cb9cac79c07c271bb260ae86
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/virt-launcher
      --qemu-timeout
      5m
      --name
      vmwanoptimizer3
      --uid
      5bb0ee9d-a3d6-11e9-84a4-d4bed9eb3325
      --namespace
      default
      --kubevirt-share-dir
      /var/run/kubevirt
      --ephemeral-disk-dir
      /var/run/kubevirt-ephemeral-disks
      --readiness-file
      /var/run/kubevirt-infra/healthy
      --grace-period-seconds
      15
      --hook-sidecars
      0
      --less-pvc-space-toleration
      10
    State:          Running
      Started:      Thu, 11 Jul 2019 17:51:17 +0530
    Ready:          True
    Restart Count:  0
    Limits:
      devices.kubevirt.io/kvm:        1
      devices.kubevirt.io/tun:        1
      devices.kubevirt.io/vhost-net:  1
    Requests:
      devices.kubevirt.io/kvm:        1
      devices.kubevirt.io/tun:        1
      devices.kubevirt.io/vhost-net:  1
      memory:                         161556485
    Readiness:                        exec [cat /var/run/kubevirt-infra/healthy] delay=2s timeout=5s period=2s #success=1 #failure=5
    Environment:
      KUBEVIRT_RESOURCE_NAME_enp2s0:
      KUBEVIRT_RESOURCE_NAME_enp3s0:
    Mounts:
      /var/run/kubevirt from virt-share-dir (rw)
      /var/run/kubevirt-ephemeral-disks from ephemeral-disks (rw)
      /var/run/kubevirt-infra from infra-ready-mount (rw)
      /var/run/libvirt from libvirt-runtime (rw)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  infra-ready-mount:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  virt-share-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/kubevirt
    HostPathType:
  libvirt-runtime:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:  <unset>
  ephemeral-disks:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:
    SizeLimit:   <unset>
QoS Class:       Burstable
Node-Selectors:  kubevirt.io/schedulable=true
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s

                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
`

- Attached the zip file for logs of the VM's virt-launcher pod
[default_virt-launcher-vmwanoptimizer3-b78cz_5bcc8fd3-a3d6-11e9-84a4-d4bed9eb3325.zip](https://github.com/kubevirt/kubevirt/files/3381214/default_virt-launcher-vmwanoptimizer3-b78cz_5bcc8fd3-a3d6-11e9-84a4-d4bed9eb3325.zip)

**Comment by SchSeba** [comment]
Hi @mbhatnagar11 can you please try to run `virtctl vnc <vm-name>` if there is a problem with the operating system you will be able to see it there.

**Comment by petrkotas** [comment]
@mbhatnagar11 my guess it is definitely the issue within the operating system. I have already seen similar issue. The problem was within wrongly configured TTY. This can happen when you create VM in virtmanager and let the TTY configured to be proxied as TTY. Kubevirt, however, redirects TTY into the socket. Both devices are different in the means of output devices and OS does not send the TTY to the right one.

To solve this, I create the VM pointing to the socket.

I hope this helps.

**Comment by petrkotas** [comment]
@mbhatnagar11 moreover, I am referencing the similar issue: https://github.com/kubevirt/kubevirt/issues

Since you are using ubuntu, here is the guide to enable ttyS0: https://help.ubuntu.com/community/SerialConsoleHowto

**Comment by moadqassem** [comment]
I have actually encountered the same issue and there are couple of things you need to  make sure about: 
1- make sure that the VM has booted up and running without any issues(describing the VM might give you some insights, `kubectl get vm` is not enough due to the absence of the events. 
2- if the VM is booted then give it some time to connect.

**Comment by rmohr** [comment]
@moadqassem could you connect via `vnc` and confirm from within the guest that the tty was indeed used for the console by the kernel?

**Comment by moadqassem** [comment]
@rmohr As far as I can see yes: 

`Ubuntu 18.04.2 LTS ubuntu-1-15-0-kubevirt-6b9***** tty1`

**Comment by brianberzins** [comment]
I had what sounded like a similar problem and it turned out to be blocked by entropy.
This may not be it, but it should be fairly easy to test out!

https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/virtualized-hardware-configuration.html#random-number-generator-rng

**Comment by rmohr** [comment]
@mbhatnagar11 did you get the issue resolved? Chances are not that high that it is related, but we fixed some issues in VNC and console streaming in the current release (0.24).
