### ISSUE TITLE
[flaky test] [rfe_id:253][crit:medium][vendor:cnv-qe@redhat.com][level:component]Expose Expose UDP service on a VMI Expose NodePort UDP service [test_id:1536]Should expose a NodePort service on a VMI and connect to it

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#2479]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

This test fails on various lanes from time to time:

Lanes: | pull-kubevirt-e2e-k8s-1.13.3 | pull-kubevirt-e2e-k8s-multus-1.13.3 | pull-kubevirt-e2e-os-3.11.0-crio | pull-kubevirt-e2e-k8s-genie-1.11.1 | pull-kubevirt-e2e-k8s-1.11.0 | pull-kubevirt-e2e-os-3.11.0-multus | pull-kubevirt-e2e-os-3.11.0
-- | -- | -- | -- | -- | -- | -- | --
[rfe_id:253][crit:medium][vendor:cnv-qe@redhat.com][level:component]Expose Expose UDP service on a VMI Expose NodePort UDP service [test_id:1536]Should expose a NodePort service on a VMI and connect to it | 2/25/0 | 1/25/0 | 1/20/0 | 4/23/0 | 0/26/0 | 0/30/0 | 0/25/0
-- | -- | -- | -- | -- | -- | -- | --

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
I looked a little bit deeper into the logs. It looks like the issue is coming from the attempt to ping the VMI over a nodePort. This seems to fail very  often. The initial ping over the cluster IP always succeeds.

**Comment by rmohr** [comment]
@SchSeba FYI

**Comment by rmohr** [comment]
Here the monthly report: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/flakefinder-2019-09-12-672h.html

which shows that the failures are almost exclusively happening on the `pull-kubevirt-e2e-k8s-multus-1.13.3` lane.

**Comment by SchSeba** [comment]
Hi @rmohr thanks for the report.

I think @fedepaol already take a look on that.

https://github.com/kubevirt/kubevirt/pull/2714

can we close this issue?

**Comment by rmohr** [comment]
/close

Yes did not fail anymore after we merged #2714.
