### ISSUE TITLE
virtctl image-upload error message for missing pvc size is confusing

### ISSUE THREAD

**Issue by codificat** [kubevirt/kubevirt#2496]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:

When you invoke `virtctl image-upload` without specifying a `--pvc-size` you get an error message that is not clear enough about the nature of the problem:

```
$ virtctl image-upload --pvc-name=cirros --image-path=images/cirros-0.4.0-x86_64-disk.img.gz
quantities must match the regular expression '^([+-]?[0-9.]+)([eEinumkKMGTP]*[-+]?[0-9]*)$'
```

**What you expected to happen**:

It should say something like:

    Missing --pvc-size

or similar.

**How to reproduce it (as minimally and precisely as possible)**:

See above

**Anything else we need to know?**:

Additionally, mabye the help text could highlight which flags are mandatory.

**Environment**:
- KubeVirt version (use `virtctl version`):

```
Client Version: version.Info{GitVersion:"v0.17.4", GitCommit:"adfdb8c07830b99fc79d2fd1d004e862ef70979e", GitTreeState:"clean", BuildDate:"2019-06-27T14:07:33Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.17.4", GitCommit:"adfdb8c07830b99fc79d2fd1d004e862ef70979e", GitTreeState:"clean", BuildDate:"2019-06-27T14:08:17Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+4910781", GitCommit:"4910781", GitTreeState:"clean", BuildDate:"2019-05-09T19:19:42Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13+", GitVersion:"v1.13.4+c62ce01", GitCommit:"c62ce01", GitTreeState:"clean", BuildDate:"2019-06-27T18:14:14Z", GoVersion:"go1.11.6", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by jichenjc** [comment]
/assign

brand new to this project, try to learn from work..

**Comment by mfranczy** [comment]
@jichenjc I don't think that making the `pvc-size` mandatory is a way to solve the issue, consider that the PVC may already exist or someone doesn't want to attempt to create a new one ([--no-create flag](https://kubevirt.io/user-guide/docs/latest/administration/image-upload.html)). My guess is that we try to validate the pvc-size param even if it is not passed and that's why we have the regex message.

**Comment by mfranczy** [comment]
the error comes from https://github.com/kubevirt/kubevirt/blob/master/pkg/virtctl/imageupload/imageupload.go#L349 (look at [link](https://play.golang.org/p/Qq9t8cfhjGb)) we can check there if the `size` is empty and return an appropriate message or make `pvc-size` mandatory only when `no-create` flag is not passed.

Regardless the solution to solve it, I think it's worth to improve error mesage, we could change
```
quantity, err := resource.ParseQuantity(size)
	if err != nil {
		return nil, err
	}
```
to 
```
quantity, err := resource.ParseQuantity(size)
	if err != nil {
		return nil, fmt.Errorf("Validation failed for --pvc-size=%s: %s", size, err)
	}
```

/cc @mhenriks

**Comment by jichenjc** [comment]
ok, I will modify my PR, thanks for the info 

BTW: brand new to here, so need time to warm up the whole stuffs :)

**Comment by mfranczy** [comment]
@jichenjc sorry for my lack of response in the PR, I was on vacations.

**Comment by jichenjc** [comment]
that's fine, Thanks a lot for your help :) @mfranczy
