### ISSUE TITLE
Add missing TARGET variable for CI.

### ISSUE THREAD

**Issue by petrkotas** [kubevirt/kubevirt#2505]
/kind bug

**What happened**:
CI is missing the `TARGET` variable specifying which environment is running in the CI suite. Due to this misconfiguration, the `oc` tests for OCP cluster are not run and are skipped.

**What you expected to happen**:
`oc` tests are not skipped and are run normally as other tests.

**How to reproduce it (as minimally and precisely as possible)**:
Open any PR and look at skipped tests. Any skipped test for templates is skipped due to missing `oc` command.

**Comment by slintes** [comment]
the TARGET is set by Prow, see e.g. https://github.com/kubevirt/project-infra/blob/master/github/ci/prow/files/jobs/kubevirt/kubevirt-presubmits.yaml#L136 ...? The problem must be somewhere else.

**Comment by petrkotas** [comment]
This issue turns out to be irrelevant.  Also symptoms are resolved via #2500. Closing this as being deprecated.
