### ISSUE TITLE
Access Kubevirt vm's file system from host machine

### ISSUE THREAD

**Issue by mbhatnagar11** [kubevirt/kubevirt#2508]
Kubevirt version = v0.15.0

Is there any way we can access kubevirt vm's file system through host machine ?

**Comment by petrkotas** [comment]
Hi @mbhatnagar11 currently there is no feature enabling you to do it directly.
Kubevirt stores the filesystem as raw disk in the storage domain. If you can access that domain directly
and the machine is not running you can access the dist directly by mounting the raw image to you system. The tip how to do it is e.g. here http://blog.siphos.be/2016/09/mounting-qemu-images/

**Comment by lxs137** [comment]
I have a workaround to handle this situation:
* mount a block device in VM's pod, VM use this device as disk directly
* this block device can also be mounted on host

**Comment by mbhatnagar11** [comment]
Hi @lxs137 

Can you please post the yaml file you used for creating VM with mounted block device and also share the procedure .

**Comment by lxs137** [comment]
It is nothing special about `virtualmachine.yaml`, I just use a `PVC`, which is bound to a Block `PV`. (When `Pod` spec has a Block `PVC`, `kubelet` will create the container with the Block `PVC` as a device, so you can access the device by `/dev/sdx`):

```
...
domain:
  devices:
    disks:
    - name: blockdisk
       disk: {}
...
volumes:
  - name: blockdisk
     persistentVolumeClaim:
       claimName: mypvc
```

In VM guestOS, you can access that device, and store your data on it.

In hostOS, `kubelet` will create the Block Volume as a device, and mount device into container, how to access the Block Volume is depend on Volume Plugin, you can get more detail from [official introduction](https://kubernetes.io/blog/2019/03/07/raw-block-volume-support-to-beta/)
