### ISSUE TITLE
Allow adding annotations to a VM's pod

### ISSUE THREAD

**Issue by hsychla** [kubevirt/kubevirt#2527]
/kind enhancement

**What happened**:
I want/need to give the Pod interface of the VM a static calico IP but can not find a way to add the needed annotation `cni.projectcalico.org/ipAddrs:` to the VM's pod.

**What you expected to happen**:
Find a way to add the annotation to the pod.

**How to reproduce it (as minimally and precisely as possible)**:
**Anything else we need to know?**:
**Environment**:
- KubeVirt version (use `virtctl version`): v0.18.1
- Kubernetes version (use `kubectl version`): v1.14.3
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by petrkotas** [comment]
Hi @hsychla, thanks for reporting this issue. We do support some level of cni annotations.
Would this https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/interfaces-and-networks.html be helpful to you?

Otherwise, I am sure @SchSeba or @phoracek would be able to provide more help.

**Comment by SchSeba** [comment]
Hi @hsychla can you please give as more details about your use case?
Thanks!

**Comment by mlsorensen** [comment]
I just ran across the same use case.

Basically we just want to see the VMI annotations copied to the pod, for any arbitrary use case that might come along. In this instance, Calico supports specifying the pod IP for its IPAM selection, via pod annotation.

**Comment by petrkotas** [comment]
Hi @mlsorensen, passing arbitrary annotations makes sense and should be straightforward as we already copy labels.

Will create the PR for this.

**Comment by petrkotas** [comment]
@mlsorensen, @hsychla with the PR #2627 being merged, annotations are now carried from the VM down to the POD. 

If you find it useful and it works for you, would you please come back to us and share your experience? Thanks a lot.
