### ISSUE TITLE
description and properties are missing in swagger JSON

### ISSUE THREAD

**Issue by suomiy** [kubevirt/kubevirt#2530]
/kind bug

**What happened**:

`description` and `properties` of `VirtualMachine`, `VirtualMachineInstance`, etc. are missing in swagger JSON

Only this info is available for `VirtualMachine`

```json
"io.kubevirt.v1alpha3.VirtualMachine": {
  "type": "object",
  "x-kubernetes-group-version-kind": [
    {
      "group": "kubevirt.io",
      "kind": "VirtualMachine",
      "version": "v1alpha3"
    }
  ]
},
```

compared to `VirtualMachineList`

```json
"io.kubevirt.v1alpha3.VirtualMachineList": {
  "description": "VirtualMachineList is a list of VirtualMachine",
  "required": [
    "items"
  ],
  "properties": {
    "apiVersion": {
      "description": "APIVersion defines the versioned schema of this representation of an object. Servers should convert recognized schemas to the latest interna       l value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/api-conventions.md#resources",
      "type": "string"
```

**What you expected to happen**:

Properties and description should be available.

**How to reproduce it (as minimally and precisely as possible)**:
```
curl localhost:8001/openapi/v2
```

**Anything else we need to know?**:

affects openshift/kubevirt UI: https://bugzilla.redhat.com/show_bug.cgi?id=1732329

**Environment**:
- KubeVirt version (use `virtctl version`):

```
Client Version: version.Info{GitVersion:"v0.17.4", GitCommit:"adfdb8c07830b99fc79d2fd1d004e862ef70979e", GitTreeState:"clean", BuildDate:"2019-06-27T14:07:33Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.17.4", GitCommit:"adfdb8c07830b99fc79d2fd1d004e862ef70979e", GitTreeState:"clean", BuildDate:"2019-06-27T14:08:17Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.4+509916ce1", GitCommit:"509916ce1", GitTreeState:"clean", BuildDate:"2019-03-28T17:17:29Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"12+", GitVersion:"v1.12.4+0ba401e", GitCommit:"0ba401e", GitTreeState:"clean", BuildDate:"2019-03-31T22:28:12Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by gabrielecerami** [comment]
Hi, trying to solve as a first bug, if you deem this bug too urgent to be fixed by me, please tell me.

**Comment by slintes** [comment]
Hey, I'm looking already into this, but since I didn't find the cause of this yet, and I'm on PTO next Monday and Tuesday, help is welcome.
What I found out so far:
- there is a pattern: every singular resource (e.g. VirtualMachine) is missing description etc., every list (e.g. VirtualMachineList) is ok
- our generated swagger.json looks good for both (see https://github.com/kubevirt/kubevirt/blob/master/api/openapi-spec/swagger.json#L5836)
- you can get the openapi json from our CI cluster with `curl -k https://127.0.0.1:<port>/openapi/v2 | jq . > openapi.json`, you find the port in `_ci-configs/<provider>/.kubeconfig` `server` after `make cluster-up`

**Comment by slintes** [comment]
Hey @gabrielecerami, did you have a chance to look into this?

**Comment by gabrielecerami** [comment]
Sorry, I am and will be very slow as I'm trying to get familiar with the code. Had some time to check also openapi generated files and generic proxies, they look ok, I was starting to check if the operationIds "read.*" and "list.*" are treated in some different way by a filter during the GET.

**Comment by slintes** [comment]
> Sorry, I am and will be very slow as I'm trying to get familiar with the code. 

No problem, we all know that it takes a while to get familiar with the code :slightly_smiling_face: 

I went on with this today because there is some urgency, and fixed it... even though I don't know exactly yet how :thinking: 
So I am afraid to need to pick another issue, sorry.

**Comment by slintes** [comment]
that was a false positive yesterday, but I found out what is causing this:

a) we don't have a openapi validation schema on our CRDs (wasn't needed until now, validation is done by our apiserver/webhook)
b) even if we have, this is a feature gated alpha feature in k8s 1.14, see https://github.com/kubernetes/enhancements/issues/692

**Comment by rmohr** [comment]
> a) we don't have a openapi validation schema on our CRDs (wasn't needed until now, validation is done by our apiserver/webhook)

Also CRD validation via published openapi spec is sadly very limited, so we will continue using our own webhooks, but there will come more and more CRD features which will also require us to add the schema on the CRD. We can do that as soon as we think we are ready for it (if someone finds the time :) ).

> b) even if we have, this is a feature gated alpha feature in k8s 1.14, see [kubernetes/enhancements#692](https://github.com/kubernetes/enhancements/issues/692)

Yep, but there are features for CRD planned which will need the schema there. We should provide it sooner or later.

**Comment by slintes** [comment]
> Also CRD validation via published openapi spec is sadly very limited, so we will continue using our own webhooks

Sure. In the context of this issue the name "validation scheme" is a bit misleading, but that's the field name of the scheme on the CRD :man_shrugging: So for this issue we "just" need the descriptions in the scheme, no actual validation.
Mh, well, maybe validation is also used in the UI?

**Comment by slintes** [comment]
this still is an issue
and since the related feature is GA in k8s 1.16, it is getting more interesting to finally implement this

/remove-lifecycle stale

**Comment by uma-sethuraman** [comment]
Hello, my group members and I are students at the University of Texas at Austin. One of the projects in our Virtualization course is to contribute to an open-source repository. We are interested in contributing to KubeVirt. Would this be a suitable first issue for us to work on?

**Comment by suomiy** [comment]
@uma-sethuraman it seems this issue is getting fixed by https://github.com/kubevirt/kubevirt/pull/3257

**Comment by phoracek** [comment]
@xpivarc could you confirm? Can we close this issue now?

@uma-sethuraman if you are still interested in contributing, please let me know.

**Comment by uma-sethuraman** [comment]
@suomiy @phoracek Thanks for letting me know! If this issue is being closed, then no worries. We will let you know if there are any other issues we would like to work on in the future.

**Comment by xpivarc** [comment]
/close
Sorry for the late reply. @phoracek I can confirm that this issue is gone.
