### ISSUE TITLE
Is there any way to change the image of a deployed VM

### ISSUE THREAD

**Issue by mbhatnagar11** [kubevirt/kubevirt#2560]
Kubevirt verison  - v0.15.0

I need to upgrade the image of a VM , that VM is already deployed with an image of prior version.
Is there any api provided in Kubevirt for this?

**Comment by petrkotas** [comment]
Hi @mbhatnagar11 would you please share more information regarding your use case?
Please provide a full yaml file for your VM. What do you want to change?
The answer depends on how your VM looks like.

**Comment by mbhatnagar11** [comment]
Hi @petrkotas 

Basically what I want to do is , deploy a VM using an image . After deployment , I want to change or upgrade the image which that deployed VM was using. Below is the yaml file I am using for creating the VM :

`apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata: 
  name: wanoptimizer
spec: 
  running: true
  template: 
    metadata: 
      labels: 
        kubevirt.io/domain: dwanoptimizer3
        kubevirt.io/size: small
    spec: 
      domain: 
        devices: 
          disks: 
            - 
              disk: 
                bus: virtio
              name: rootfs
            - 
              disk: 
                bus: virtio
              name: cloudinit
          interfaces: 
            - 
              bridge: {}
              name: default
            - 
              bridge: {}
              name: enp2s0
            - 
              bridge: {}
              name: enp3s0
        resources: 
          requests: 
            memory: 2048M
      networks: 
        - 
          name: default
          pod: {}
        - 
          multus: 
            networkName: ovs-conf
          name: enp2s0
        - 
          multus: 
            networkName: ovs-conf
          name: enp3s0
      volumes: 
        - 
          containerDisk: 
            image: kubevirt/ubuntu-firewall
          name: rootfs
        - 
          cloudInitNoCloud: 
            userData: |-
                #!/bin/bash
                ip a add 4.4.4.2/24 dev enp2s0
                ip a add 2.2.2.1/24 dev enp3s0
                ip link set dev enp2s0 up
                ip link set dev enp3s0 up
                ethtool --offload enp2s0 rx off tx off
                ethtool -K enp2s0 gso off
                ethtool --offload enp3s0 rx off tx off
                ethtool -K enp3s0 gso off
                sysctl -w net.ipv4.conf.all.forwarding=1
                ip route add 1.1.1.0/24 via 4.4.4.1
                route del default gw 10.244.0.1
                route add default gw 2.2.2.2
                iptables -t nat -A POSTROUTING -o enp3s0 -j MASQUERADE
          name: cloudinit`

**Comment by petrkotas** [comment]
If you are OK with downtime, you can change the YAML specification to point to new image and than reboot the VM. The new VM will pick up the new image.

For the scenario without downtime, I am not aware of any current solution KubeVirt can offer. We have [`VirtualMachineReplicaSets`](https://kubevirt.io/user-guide/docs/latest/using-virtual-machines/virtual-machine-replica-set.html), which unfortunately without a deployment controller does not support updates. And we do not have deployment controller currently available.

I hope I helped at least partially.

**Comment by mbhatnagar11** [comment]
Hi @petrkotas 

Yes , we are okay with the down time. Thanks for the solution . Can you please tell me the procedure to update yaml of a running vm , is there any test api for doing the same?

**Comment by petrkotas** [comment]
The update is done the same as for any other K8s object.

If you have created the VM via `kubectl apply` you can easily change the yaml file and do the `kubectl apply -f yamlfile.yaml` again and the object will be updated.

Otherwise you can call `kubectl patch` passing the changed part of the yaml. It will merge the changes to existing object. The documentation and examples are shown here https://kubernetes.io/docs/reference/kubectl/cheatsheet/#patching-resources 

Finally you can just do `virtctl wanoptimizer stop` and `virtctl wanoptimizer start`. And you are good to go.

**Comment by mbhatnagar11** [comment]
Hi @petrkotas ,

I have been using `kubectl patch virtualmachine vm5 --type=merge -p '{"spec":{"image":"kubevirt/ubuntu-firewall"}}'` , but running into below error :

`The  "" is invalid: : spec.image in body is a forbidden property`

**Comment by petrkotas** [comment]
Hi @mbhatnagar11 happy Monday :).

Let me help you with that, it is a simply typo. The `image` is actually actually part of a volume, not `spec`. Than the `spec` is inside the `template` inside the `spec`. Also the particular `volume` is part of an array.

The actual command should look like this:

```yaml
kubectl patch virtualmachine vm5 -p '{"spec":{"template":{"spec":{"volumes:[{"name":"rootfs", "containerDisk":{"image":"kubevirt/ubuntu-firewall-newimage"}}]}}}}'
```

To help with the structure here is the patch formatted:

```yaml
{
  "spec":{
    "template":{
      "spec":{
        "volumes:[
          {
            "name":"rootfs", 
            "containerDisk":{
              "image":"kubevirt/ubuntu-firewall-newimage"
            }
          }
        ]
      }
    }
  }
}
```

When patching the array, the name is a merge key, therefore it have to be present.
Example is according to the documentation: http://manpages.org/kubectl-patch

**Comment by mbhatnagar11** [comment]
Hi @petrkotas 

Thanks for your help . After running the command that you have provided , I am running into below error : 
`Error from server (UnsupportedMediaType): the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json`

**Comment by mbhatnagar11** [comment]
Hi @petrkotas 

I was able to patch the vm using this command : `kubectl patch virtualmachine vm5 --type=merge -p '{"spec": {"template": {"spec": {"volumes": [{"name": "rootfs","containerDisk": {"image": "kubevirt/ubuntu-firewall-newimage"}},{"name": "cloudinit","cloudInitNoCloud": {"userData": "ip a add 10.0.0.10/24 dev enp2s0\nip a add 10.0.0.20/24 dev enp3s0\nip link set dev enp2s0 up\nip link set dev enp3s0 up\n"}}]}}}}'` 

But why do I have to pass cloudInitNoCloud parameter and user data even when I do not want to change that.

**Comment by petrkotas** [comment]
Hi @mbhatnagar11 it is due to the fact that the patch does not know how to merge which item in an positional array is going to be replaced. Therefore it needs the whole array.

**Comment by rmohr** [comment]
@mbhatnagar11 in case you are not interested in the patch, for automation purposes, consider 

```
kubectl edit virtualmachine vm5
```

You can then modify the image with your favourite text editor. Like you can on all other k8s resources.

**Comment by mbhatnagar11** [comment]
Hi @petrkotas 

Thanks for the reply . I just wanted to  ask , is there any way we can assign IP address to the interfaces created inside VM . Right now I pass commands in user data for assigning ip addresses to the interfaces . Is there any other work around but I don't want to go inside the VM using virtctl to assign ip addresses.

Actually I am running this command from java code : `kubectl patch virtualmachine vmwanoptimizer3 --type=merge -p '{"spec": {"template": {"spec": {"volumes": [{"name": "rootfs","containerDisk": {"image":"vmdisks/ubuntu-test-firewall"}},{"name": "cloudinit","cloudInitNoCloud": {"userData": "#!/bin/bash\nip a add 1.1.1.1/24 dev enp2s0\nip a add 2.2.2.2/24 dev enp3s0\nip link set dev enp2s0 up\nip link set dev enp3s0 up\nethtool --offload enp2s0 rx off tx off\nethtool -K enp2s0 gso off\nethtool --offload enp3s0 rx off tx off\n
ethtool -K enp3s0 gso off\nsysctl -w net.ipv4.conf.all.forwarding=1\nip route add 1.1.1.0/24 via 4.4.4.1"}}]}}}}'`     from java code  , but the line separators are creating a problem in this.

**Comment by rmohr** [comment]
> Thanks for the reply . I just wanted to ask , is there any way we can assign IP address to the interfaces created inside VM . Right now I pass commands in user data for assigning ip addresses to the interfaces . Is there any other work around but I don't want to go inside the VM using virtctl to assign ip addresses.

For the pod network and additional multus networks, we provide the IPs via DHCP. If you configure in cloud-init the VMI to use dhcp for all interfaces,  you should get the right data offered (uncluding mtu and such).

**Comment by SchSeba** [comment]
@mbhatnagar11 can you share the network attachment definition for the additional networks?

**Comment by mbhatnagar11** [comment]
Hi @SchSeba 

Below is the yaml file I am using : 

`apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: vm5
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm3
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootfs
          - disk:
              bus: virtio
            name: cloudinit
          interfaces:
          - name: default
            bridge: {}
          - name: enp2s0
            bridge: {}
          - name: enp3s0
            bridge: {}
        resources:
          requests:
            memory: 1024M
      networks:
      - name: default
        pod: {}
      - name: enp2s0
        multus:
          networkName: ovs-conf
      - name: enp3s0
        multus:
          networkName: ovs-conf-2
      volumes:
        - name: rootfs
          containerDisk:
            image: vmdisks/ubuntu-test-firewall
        - name: cloudinit
          cloudInitNoCloud:
`

**Comment by SchSeba** [comment]
Hi @mbhatnagar11 please run `kubectl get network-attachment-definitions.k8s.cni.cncf.io -o yaml`

and share the output.
Thanks!

**Comment by mbhatnagar11** [comment]
Hi @SchSeba 

Below is the output :

`- apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    creationTimestamp: "2019-08-02T14:32:58Z"
    generation: 1
    name: ovs-conf
    namespace: default
    resourceVersion: "5961262"
    selfLink: /apis/k8s.cni.cncf.io/v1/namespaces/default/network-attachment-definitions/ovs-conf
    uid: 6cabb972-b532-11e9-bf8c-d4bed9eb3325
  spec:
    config: '{ "cniVersion": "0.3.1", "type": "ovs", "bridge": "br1" }'
- apiVersion: k8s.cni.cncf.io/v1
  kind: NetworkAttachmentDefinition
  metadata:
    creationTimestamp: "2019-08-02T14:32:14Z"
    generation: 1
    name: ovs-conf-2
    namespace: default
    resourceVersion: "5961183"
    selfLink: /apis/k8s.cni.cncf.io/v1/namespaces/default/network-attachment-definitions/ovs-conf-2
    uid: 527b7b68-b532-11e9-bf8c-d4bed9eb3325
  spec:
    config: '{ "cniVersion": "0.3.1", "type": "ovs", "bridge": "br1" }'
`

**Comment by SchSeba** [comment]
@mbhatnagar11 thanks!

with this configure you connect the br1 using some interface on the host to the physical network?

If yes you can configure a dhcp server on that network and in the cloud-init just run dhclient on the interfaces to get ip from the dhcp server on the network.

**Comment by mbhatnagar11** [comment]
Hi @SchSeba 

Yes, I am using this to connect interfaces on the vm to physical network . I cannot use DHCP server here as I want to assign user given IPs to these interfaces. I already have a set of IPs which I  want to assign.

**Comment by SchSeba** [comment]
@mbhatnagar11 for user assign ips I can't think on another solution.

I think you need to configure the ips statically in the cloud init data.
