### ISSUE TITLE
[flaky test] No permission to open /dev/null

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#2566]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind enhancement

**What happened**:

There is sometimes a weird error in CI which makes tests randomly fail.

virt-launcher logs: https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2565/pull-kubevirt-e2e-os-3.11.0/1158359492350447616/artifacts/pods/1_kubevirt-test-default_virt-launcher-testvmirmdd8lx8lz2nk6w8dc85lqjgw42b5km9754br5vdfb-compute.log

job: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2565/pull-kubevirt-e2e-os-3.11.0/1158359492350447616

The relevant section:

```json
{"component":"virt-launcher","level":"error","msg":"failed to create nat rules for vm error: open /dev/null: operation not permitted","pos":"podinterface.go:435","timestamp":"2019-08-05T14:56:09.240886Z"}
{"component":"virt-launcher","level":"fatal","msg":"failed to prepared pod networking","pos":"podinterface.go:88","reason":"open /dev/null: operation not permitted","timestamp":"2019-08-05T14:56:09.241074Z"}
panic: open /dev/null: operation not permitted
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@cynepco3hahue @SchSeba @slintes @fedepaol FYI

**Comment by rmohr** [comment]
Edit: removed `/dev/mem/` error from here because that is always there.

**Comment by cynepco3hahue** [comment]
Some additional test that failed because of it:
```
/root/go/src/kubevirt.io/kubevirt/tests/vmi_cloudinit_hook_sidecar_test.go:119
Unexpected Warning event received: testvmipfr8gh4k2gt5fmn9f5jrbrlsp2cx95np8qwj6kjmzxb4wkc8,93cb88ca-b7ef-11e9-9b6c-525500d15501: server error. command SyncVMI failed: "generating local cloud-init data failed: open /dev/null: operation not permitted"
Expected
    <string>: Warning
not to equal
    <string>: Warning
```

**Comment by rmohr** [comment]
another one: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2717/pull-kubevirt-e2e-os-3.11.0/1175919830482554880, log: https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2717/pull-kubevirt-e2e-os-3.11.0/1175919830482554880/artifacts/pods/1_kubevirt-test-default_virt-launcher-testvmi8qd729cq4s8xlcf74w7j78m9jvrlvp72n2vbd5bhls-compute.log

**Comment by SchSeba** [comment]
another one: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2649/pull-kubevirt-e2e-os-3.11.0-multus/1176139398991843328, log: https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2649/pull-kubevirt-e2e-os-3.11.0-multus/1176139398991843328/artifacts/pods/1_kubevirt-test-default_virt-launcher-testvmisv9c52pjm7lvh9trgc6wnn2xbft6q6grqm9dsxrbkt-compute.log

**Comment by vladikr** [comment]
Is it only happening on openshift lanes? Perhaps it has to do with our selinux profile.

**Comment by rmohr** [comment]
Could be. It is just strange, because it looks like it "normally" works.

**Comment by rmohr** [comment]
/reopen
/remove-lifecycel rotten

Still a (seldom and strange) issue.

**Comment by rmohr** [comment]
/assign @qinqon

FYI we had  this issue before already when we were testing openshift 3.11 inside a VM. It looks like the bare-metal machines (which run openshift) in combination with kind seems to run into this issue too.

**Comment by qinqon** [comment]
Another one https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3684/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1278456503107325953

I have prepare a simplistic "reproducer" here https://github.com/kubevirt/kubevirt/pull/3724 running `tee /dev/null` inside a pod using virt-launcher container but looks like it's fine after running several times.

**Comment by qinqon** [comment]
Added some stuff to the kubernetes reporter to list files at pods with type and permissions https://github.com/kubevirt/kubevirt/pull/3724/commits/8dae06373317973ea3f0c6d5b90b0108af8852c0

**Comment by qinqon** [comment]
Maybe related https://github.com/kubernetes-sigs/kind/issues/717

**Comment by qinqon** [comment]
Checking one of the nodes at running kind I think the number of openfiles done by root is over the ulimit

```bash
[root@ibm-srv04 ~]# lsof -u root | tail -n +2 | awk {'print $9'} | wc -l;
7427
[root@ibm-srv04 ~]# ulimit -n
1024

```

**Comment by jean-edouard** [comment]
Seen on 1.18 today: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3869/pull-kubevirt-e2e-k8s-1.18/1285947809471664128

**Comment by maiqueb** [comment]
Hit this today on kind-ipv6: 
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3794/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1286734977844645888

Test: `Configurations [rfe_id:2926][crit:medium][vendor:cnv-qe@redhat.com][level:component]Check Chassis value [test_id:2927]Test Chassis value in a newly created VM`

**Comment by jean-edouard** [comment]
Got the same with a different devnode! (urandom)
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3905/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1289160100287614977

Tried debugging this, failed but found that:
- It’s not SELinux (happened before it was enforced, also happens in kind, no denials in the logs even with dontaudit -> deny)
- If /dev/null is removed before starting libvirtd, the error is different (`"failed to start libvirtd","pos":"libvirt_helper.go:210","reason":"open /dev/null: no such file or directory"`)
- Replacing libvirtd with `ls -l /dev` shows /dev/null is there right away. However it also shows /dev/mqueue starts with categories which get removed later. That means docker can still be messing with /dev after libvirtd has started.

**Comment by oshoval** [comment]
Happens today on 1.17
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4140/pull-kubevirt-check-tests-for-flakes/1303990361718263808

```
• Failure in Spec Setup (BeforeEach) [32.502 seconds]
Infrastructure [rfe_id:3187][crit:medium][vendor:cnv-qe@redhat.com][level:component]Prometheus Endpoints [BeforeEach] [test_id:4137]should find one leading virt-operator and two ready 
/root/go/src/kubevirt.io/kubevirt/tests/infra_test.go:570

  Unexpected Warning event received: testvmirxthdbrrr4mhh7kdwfxcfql2nkrkdp6trxbd2xth8r9gjfdh,8f1c1b5a-5e9f-4e2f-aaff-dc071ef4ef35: server error. command SyncVMI failed: "preparing ephemeral container disk images failed: qemu-img failed with output '': open /dev/null: operation not permitted"
  Expected
      <string>: Warning
  not to equal
      <string>: Warning

  /root/go/src/kubevirt.io/kubevirt/tests/utils.go:356
```

**Comment by Fefer-Ivan** [comment]
We had a similar issue with our CI running in Kubernetes (without KubeVirt): sometimes random tests would fail with `panic: open /dev/null: operation not permitted`

In our case the problem was fixed by removing --cpu-manager-policy=static (https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/) from our kubelet.

Hope it helps.

**Comment by dhiller** [comment]
```
tests/network/services.go:236
Unexpected Warning event received: testvmi4fq45cqbjcjjzfspbnnvx7bl8gpktk88rnm9ncn86928n5vk,222bacbf-fe25-45bd-8c40-6577f7a747d8: server error. command SyncVMI failed: 
"LibvirtError(Code=38, Domain=0, Message='cannot open /dev/null: Operation not permitted')"
Expected
    <string>: Warning
not to equal
    <string>: Warning
tests/utils.go:360
```

Seen here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4297/pull-kubevirt-e2e-k8s-1.16/1312384420702851072

**Comment by rmohr** [comment]
> In our case the problem was fixed by removing --cpu-manager-policy=static (https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/) from our kubelet.

That is indeed a nice hint. We don't use the cpu-manager right now, but I guess it makes it more clear that this is related to the kubelet and the CRI. @Fefer-Ivan did you open an issue in kubernetes/kubernetes already?

**Comment by oshoval** [comment]
> > In our case the problem was fixed by removing --cpu-manager-policy=static (https://kubernetes.io/docs/tasks/administer-cluster/cpu-management-policies/) from our kubelet.
> 
> That is indeed a nice hint. We don't use the cpu-manager right now, but I guess it makes it more clear that this is related to the kubelet and the CRI. @Fefer-Ivan did you open an issue in kubernetes/kubernetes already?

I think we might do ? see please
cluster-provision/k8s/1.18/nodes.sh
"--cpu-manager-policy=static"

**Comment by rmohr** [comment]
> I think we might do ? see please
> cluster-provision/k8s/1.18/nodes.sh
> "--cpu-manager-policy=static"

Oh right, that can be it. Our containerized clusters add some nodes with the cpumanager. Just thought about the bare-metal node below. So this could indeed also be our issue.
