### ISSUE TITLE
Virt launcher for VM restarts every 6 minutes

### ISSUE THREAD

**Issue by nimanjun** [kubevirt/kubevirt#2589]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
Virthandler pod restarts every 6 min pod creation,  restarting vm instances as well.

**What you expected to happen**:
Virthandler pod up and running , virtual instance up and running

**How to reproduce it (as minimally and precisely as possible)**:
Deployed below yaml on kubevirt v0.19.0:

apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm1
  name: vm1
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm1
    spec:
      domain:
        cpu:
          cores: 6
        devices:
          disks:
          - name: disk0
            disk:
              bus: sata
          interfaces:
          - bridge: {}
            name: default
          - bridge: {}
            name: eth0
          - bridge: {}
            name: eth1
          - bridge: {}
            name: eth2
        machine:
          type: q35
        resources:
          requests:
            memory: 16535M
      networks:
      - name: default
        pod: {}
      - name: eth0
        multus:
          networkName: macvlan0
      - name: eth1
        multus:
          networkName: macvlan1
      - name: eth2
        multus:
          networkName: macvlan2
      volumes:
      - hostDisk:
          capacity: 50Gi
          path: /root/vmd/cdi/iso/centosdisk.iso
          type: DiskOrCreate
        name: disk0

**Anything else we need to know?**:
This is running with multus with multi network support

**Environment**:
- KubeVirt version (use `virtctl version`): v0.19.0
- Kubernetes version (use `kubectl version`): 1.15.1
- VM or VMI specifications: centos based iso (Non cloud)
- Cloud provider or hardware configuration:   Baremetal
- OS (e.g. from /etc/os-release):    CentOS Linux release 7.6.1810
- Kernel (e.g. `uname -a`):   3.10.0-957.21.3.el7.x86_64
- Others: Multus plugin installed

Any help on the issue very much appreciated.

**Comment by cynepco3hahue** [comment]
It looks like QEMU process fails to start, can you provide relevant virt-handler logs?

**Comment by SchSeba** [comment]
Please add also the virt-launcher logs.

`kubectl logs -f <virt-launcher> -c compute`

Thanks!

**Comment by nimanjun** [comment]
**Compute logs:**

kubectl logs -f virt-launcher-vm3-f4ll8 -c compute

{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:68","timestamp":"2019-08-12T16:34:09.289046Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:71","timestamp":"2019-08-12T16:34:09.289209Z"}
{"component":"virt-launcher","level":"info","msg":"Watchdog file created at /var/run/kubevirt/watchdog-files/default_vm3","pos":"virt-launcher.go:143","timestamp":"2019-08-12T16:34:09.291527Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu:///system","pos":"libvirt.go:348","timestamp":"2019-08-12T16:34:09.320225Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory')","pos":"libvirt.go:356","timestamp":"2019-08-12T16:34:09.320880Z"}
{"component":"virt-launcher","level":"info","msg":"libvirt version: 5.0.0, package: 1.fc28 (Unknown, 2019-01-22-08:04:34, 64723eea657e48d296e6beb0b1be9c4c)","subcomponent":"libvirt","thread":"79","timestamp":"2019-08-12T16:34:09.461000Z"}
{"component":"virt-launcher","level":"info","msg":"hostname: vm3","subcomponent":"libvirt","thread":"79","timestamp":"2019-08-12T16:34:09.461000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get DBus system bus connection: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory","pos":"virDBusGetSystemBus:110","subcomponent":"libvirt","thread":"79","timestamp":"2019-08-12T16:34:09.461000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get DBus system bus connection: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory","pos":"virDBusGetSystemBus:110","subcomponent":"libvirt","thread":"79","timestamp":"2019-08-12T16:34:11.290000Z"}
{"component":"virt-launcher","level":"warning","msg":"DBus not available, disabling firewalld support in bridge_network_driver: internal error: Unable to get DBus system bus connection: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory","pos":"networkStateInitialize:762","subcomponent":"libvirt","thread":"79","timestamp":"2019-08-12T16:34:11.290000Z"}
{"component":"virt-launcher","level":"error","msg":"Failed to open config space file '/sys/bus/pci/devices/0000:00:00.0/config': Read-only file system","pos":"virPCIDeviceConfigOpen:300","subcomponent":"libvirt","thread":"88","timestamp":"2019-08-12T16:34:11.482000Z"}
…
… < Removed repeated logs>

{"component":"virt-launcher","level":"error","msg":"Failed to open config space file '/sys/bus/pci/devices/0000:ff:13.5/config': Read-only file system","pos":"virPCIDeviceConfigOpen:300","subcomponent":"libvirt","thread":"88","timestamp":"2019-08-12T16:34:11.581000Z"}
{"component":"virt-launcher","level":"error","msg":"Failed to open config space file '/sys/bus/pci/devices/0000:ff:13.6/config': Read-only file system","pos":"virPCIDeviceConfigOpen:300","subcomponent":"libvirt","thread":"88","timestamp":"2019-08-12T16:34:11.581000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Child process (/usr/sbin/dmidecode -q -t 0,1,2,3,4,17) unexpected exit status 1: /dev/mem: No such file or directory","pos":"virCommandWait:2613","subcomponent":"libvirt","thread":"79","timestamp":"2019-08-12T16:34:15.828000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Cannot probe for supported suspend types","pos":"virNodeSuspendSupportsTarget:336","subcomponent":"libvirt","thread":"79","timestamp":"2019-08-12T16:34:15.882000Z"}
{"component":"virt-launcher","level":"warning","msg":"Failed to get host power management capabilities","pos":"virQEMUCapsInit:926","subcomponent":"libvirt","thread":"79","timestamp":"2019-08-12T16:34:15.882000Z"}
{"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:364","timestamp":"2019-08-12T16:34:20.519662Z"}
{"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:283","timestamp":"2019-08-12T16:34:20.528489Z"}
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:73","timestamp":"2019-08-12T16:34:20.529204Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Executing PreStartHook on VMI pod environment","name":"vm3","namespace":"default","pos":"manager.go:692","timestamp":"2019-08-12T16:34:21.368006Z","uid":"43f1a5d7-2287-4440-8cb0-242173ca03aa"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Starting PreCloudInitIso hook","name":"vm3","namespace":"default","pos":"manager.go:706","timestamp":"2019-08-12T16:34:21.368158Z","uid":"43f1a5d7-2287-4440-8cb0-242173ca03aa"}
{"component":"virt-launcher","level":"info","msg":"updated MAC for eth0 interface: old: e6:60:0d:93:52:fe -\u003e new: e6:60:0d:83:00:b6","pos":"common.go:203","timestamp":"2019-08-12T16:34:21.381599Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"bridge pod interface: VIF: { Name: eth0, IP: 10.233.0.15, Mask: ffffff00, MAC: e6:60:0d:93:52:fe, Gateway: 10.233.0.1, MTU: 1450}","name":"vm3","namespace":"default","pos":"podinterface.go:258","timestamp":"2019-08-12T16:34:21.394110Z","uid":"43f1a5d7-2287-4440-8cb0-242173ca03aa"}
{"component":"virt-launcher","level":"info","msg":"Found nameservers in /etc/resolv.conf: \n`\u0000\n","pos":"converter.go:1397","timestamp":"2019-08-12T16:34:21.394381Z"}
{"component":"virt-launcher","level":"info","msg":"Found search domains in /etc/resolv.conf: default.svc.cluster.local svc.cluster.local cluster.local","pos":"converter.go:1398","timestamp":"2019-08-12T16:34:21.394425Z"}
{"component":"virt-launcher","level":"info","msg":"Starting SingleClientDHCPServer","pos":"dhcp.go:64","timestamp":"2019-08-12T16:34:21.394612Z"}
{"component":"virt-launcher","level":"info","msg":"updated MAC for net1 interface: old: 66:73:1e:d3:f4:01 -\u003e new: 66:73:1e:4b:0d:69","pos":"common.go:203","timestamp":"2019-08-12T16:34:21.420307Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"bridge pod interface: VIF: { Name: net1, IP: 192.168.2.103, Mask: ffffff00, MAC: 66:73:1e:d3:f4:01, Gateway: \u003cnil\u003e, MTU: 1500}","name":"vm3","namespace":"default","pos":"podinterface.go:258","timestamp":"2019-08-12T16:34:21.434419Z","uid":"43f1a5d7-2287-4440-8cb0-242173ca03aa"}
{"component":"virt-launcher","level":"info","msg":"Found nameservers in /etc/resolv.conf: \n`\u0000\n","pos":"converter.go:1397","timestamp":"2019-08-12T16:34:21.434795Z"}
{"component":"virt-launcher","level":"info","msg":"Found search domains in /etc/resolv.conf: default.svc.cluster.local svc.cluster.local cluster.local","pos":"converter.go:1398","timestamp":"2019-08-12T16:34:21.434863Z"}
{"component":"virt-launcher","level":"info","msg":"Starting SingleClientDHCPServer","pos":"dhcp.go:64","timestamp":"2019-08-12T16:34:21.435045Z"}
{"component":"virt-launcher","level":"info","msg":"updated MAC for net2 interface: old: 16:12:55:82:2a:0f -\u003e new: 16:12:55:f8:be:e4","pos":"common.go:203","timestamp":"2019-08-12T16:34:21.459048Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"bridge pod interface: VIF: { Name: net2, IP: 192.168.3.103, Mask: ffffff00, MAC: 16:12:55:82:2a:0f, Gateway: \u003cnil\u003e, MTU: 1500}","name":"vm3","namespace":"default","pos":"podinterface.go:258","timestamp":"2019-08-12T16:34:21.472998Z","uid":"43f1a5d7-2287-4440-8cb0-242173ca03aa"}
{"component":"virt-launcher","level":"info","msg":"Found nameservers in /etc/resolv.conf: \n`\u0000\n","pos":"converter.go:1397","timestamp":"2019-08-12T16:34:21.473182Z"}
{"component":"virt-launcher","level":"info","msg":"Found search domains in /etc/resolv.conf: default.svc.cluster.local svc.cluster.local cluster.local","pos":"converter.go:1398","timestamp":"2019-08-12T16:34:21.473222Z"}
{"component":"virt-launcher","level":"info","msg":"Starting SingleClientDHCPServer","pos":"dhcp.go:64","timestamp":"2019-08-12T16:34:21.473315Z"}
{"component":"virt-launcher","level":"info","msg":"updated MAC for net3 interface: old: aa:3a:f8:7e:e0:80 -\u003e new: aa:3a:f8:5f:05:36","pos":"common.go:203","timestamp":"2019-08-12T16:34:21.492485Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"bridge pod interface: VIF: { Name: net3, IP: 192.168.4.103, Mask: ffffff00, MAC: aa:3a:f8:7e:e0:80, Gateway: \u003cnil\u003e, MTU: 1500}","name":"vm3","namespace":"default","pos":"podinterface.go:258","timestamp":"2019-08-12T16:34:21.504221Z","uid":"43f1a5d7-2287-4440-8cb0-242173ca03aa"}
{"component":"virt-launcher","level":"info","msg":"Found nameservers in /etc/resolv.conf: \n`\u0000\n","pos":"converter.go:1397","timestamp":"2019-08-12T16:34:21.504358Z"}
{"component":"virt-launcher","level":"info","msg":"Found search domains in /etc/resolv.conf: default.svc.cluster.local svc.cluster.local cluster.local","pos":"converter.go:1398","timestamp":"2019-08-12T16:34:21.504400Z"}
{"component":"virt-launcher","level":"info","msg":"Starting SingleClientDHCPServer","pos":"dhcp.go:64","timestamp":"2019-08-12T16:34:21.504552Z"}
{"component":"virt-launcher","level":"info","msg":"Driver cache mode for /root/vmd/cdi/dcnm-iso/dcnm-va.dcnmNG-65.ova set to none","pos":"converter.go:166","timestamp":"2019-08-12T16:34:21.505008Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Domain defined.","name":"vm3","namespace":"default","pos":"manager.go:893","timestamp":"2019-08-12T16:34:21.529689Z","uid":"43f1a5d7-2287-4440-8cb0-242173ca03aa"}
{"component":"virt-launcher","level":"info","msg":"DomainLifecycle event 0 with reason 0 received","pos":"client.go:248","timestamp":"2019-08-12T16:34:21.529972Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get DBus system bus connection: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory","pos":"virDBusGetSystemBus:110","subcomponent":"libvirt","thread":"64","timestamp":"2019-08-12T16:34:21.534000Z"}
{"component":"virt-launcher","level":"error","msg":"At least one cgroup controller is required: No such device or address","pos":"virCgroupDetect:394","subcomponent":"libvirt","thread":"64","timestamp":"2019-08-12T16:34:22.506000Z"}
{"component":"virt-launcher","level":"info","msg":"kubevirt domain status: Paused(3):StartingUp(11)","pos":"client.go:179","timestamp":"2019-08-12T16:34:22.517416Z"}
{"component":"virt-launcher","level":"info","msg":"Detected domain with UUID 4c347157-b95c-5314-9f07-e1be3cc59fb3","pos":"virt-launcher.go:233","timestamp":"2019-08-12T16:34:22.521691Z"}
{"component":"virt-launcher","level":"info","msg":"Monitoring loop: rate 1s start timeout 5m0s","pos":"monitor.go:251","timestamp":"2019-08-12T16:34:22.521967Z"}
{"component":"virt-launcher","level":"info","msg":"processed event","pos":"client.go:235","timestamp":"2019-08-12T16:34:22.523178Z"}
{"component":"virt-launcher","level":"error","msg":"Unable to read from monitor: Connection reset by peer","pos":"qemuMonitorIORead:607","subcomponent":"libvirt","thread":"63","timestamp":"2019-08-12T16:34:22.589000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: qemu unexpectedly closed the monitor: 2019-08-12T16:34:22.588377Z qemu-system-x86_64: -drive file=/root/vmd/cdi/dcnm-iso/dcnm-va.dcnmNG-65.ova,format=raw,if=none,id=drive-ua-disk0,cache=none: Could not open '/root/vmd/cdi/dcnm-iso/dcnm-va.dcnmNG-65.ova': Permission denied","pos":"qemuProcessReportLogError:1994","subcomponent":"libvirt","thread":"63","timestamp":"2019-08-12T16:34:22.590000Z"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Starting the VirtualMachineInstance failed.","name":"vm3","namespace":"default","pos":"manager.go:921","reason":"virError(Code=1, Domain=10, Message='internal error: qemu unexpectedly closed the monitor: 2019-08-12T16:34:22.588377Z qemu-system-x86_64: -drive file=/root/vmd/cdi/dcnm-iso/dcnm-va.dcnmNG-65.ova,format=raw,if=none,id=drive-ua-disk0,cache=none: Could not open '/root/vmd/cdi/dcnm-iso/dcnm-va.dcnmNG-65.ova': Permission denied')","timestamp":"2019-08-12T16:34:22.793780Z","uid":"43f1a5d7-2287-4440-8cb0-242173ca03aa"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"vm3","namespace":"default","pos":"server.go:160","reason":"virError(Code=1, Domain=10, Message='internal error: qemu unexpectedly closed the monitor: 2019-08-12T16:34:22.588377Z qemu-system-x86_64: -drive file=/root/vmd/cdi/dcnm-iso/dcnm-va.dcnmNG-65.ova,format=raw,if=none,id=drive-ua-disk0,cache=none: Could not open '/root/vmd/cdi/dcnm-iso/dcnm-va.dcnmNG-65.ova': Permission denied')","timestamp":"2019-08-12T16:34:22.793979Z","uid":"43f1a5d7-2287-4440-8cb0-242173ca03aa"}
{"component":"virt-launcher","level":"info","msg":"DomainLifecycle event 0 with reason 1 received","pos":"client.go:248","timestamp":"2019-08-12T16:34:23.014593Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"vm3","namespace":"default","pos":"server.go:166","timestamp":"2019-08-12T16:34:23.015992Z","uid":"43f1a5d7-2287-4440-8cb0-242173ca03aa"}
{"component":"virt-launcher","level":"info","msg":"kubevirt domain status: Shutoff(5):Failed(6)","pos":"client.go:179","timestamp":"2019-08-12T16:34:23.019662Z"}
{"component":"virt-launcher","level":"info","msg":"processed event","pos":"client.go:235","timestamp":"2019-08-12T16:34:23.021438Z"}
{"component":"virt-launcher","level":"info","msg":"DomainLifecycle event 0 with reason 1 received","pos":"client.go:248","timestamp":"2019-08-12T16:34:23.038648Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"vm3","namespace":"default","pos":"server.go:166","timestamp":"2019-08-12T16:34:23.039951Z","uid":"43f1a5d7-2287-4440-8cb0-242173ca03aa"}
{"component":"virt-launcher","level":"info","msg":"kubevirt domain status: Shutoff(5):Failed(6)","pos":"client.go:179","timestamp":"2019-08-12T16:34:23.041156Z"}
{"component":"virt-launcher","level":"info","msg":"processed event","pos":"client.go:235","timestamp":"2019-08-12T16:34:23.042387Z"}
{"component":"virt-launcher","level":"info","msg":"DomainLifecycle event 0 with reason 1 received","pos":"client.go:248","timestamp":"2019-08-12T16:34:23.068673Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"vm3","namespace":"default","pos":"server.go:166","timestamp":"2019-08-12T16:34:23.070196Z","uid":"43f1a5d7-2287-4440-8cb0-242173ca03aa"}
{"component":"virt-launcher","level":"info","msg":"kubevirt domain status: Shutoff(5):Failed(6)","pos":"client.go:179","timestamp":"2019-08-12T16:34:23.071533Z"}
{"component":"virt-launcher","level":"info","msg":"processed event","pos":"client.go:235","timestamp":"2019-08-12T16:34:23.072819Z"}
{"component":"virt-launcher","level":"info","msg":"DomainLifecycle event 0 with

**Comment by cynepco3hahue** [comment]
Ok the relevant error is
```
{"component":"virt-launcher","level":"error","msg":"Unable to read from monitor: Connection reset by peer","pos":"qemuMonitorIORead:607","subcomponent":"libvirt","thread":"63","timestamp":"2019-08-12T16:34:22.589000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: qemu unexpectedly closed the monitor: 2019-08-12T16:34:22.588377Z qemu-system-x86_64: -drive file=/root/vmd/cdi/dcnm-iso/dcnm-va.dcnmNG-65.ova,format=raw,if=none,id=drive-ua-disk0,cache=none: Could not open '/root/vmd/cdi/dcnm-iso/dcnm-va.dcnmNG-65.ova': Permission denied","pos":"qemuProcessReportLogError:1994","subcomponent":"libvirt","thread":"63","timestamp":"2019-08-12T16:34:22.590000Z"}
```
I just do not sure from where this file is comming, looks like CDI creates it with wrong permissions.
@awels Can you please take a look?

**Comment by awels** [comment]
@cynepco3hahue CDI did not create that file, I am seeing the VMI yaml that they are creating an ephemeral hostDisk in /root/vmd/cdi/ could that be what is creating the disk. CDI will only create disk.img files on a PV.

**Comment by cynepco3hahue** [comment]
@awels ok thanks for the clarification, cdi directory mislead me

**Comment by nimanjun** [comment]
@cynepco3hahue , good catch, yes issue with permissions and/or storage settings. Its resolved now. VM instance up and running without restarts. Closing issue.
