### ISSUE TITLE
vhost-user capability inside VM

### ISSUE THREAD

**Issue by nmsnitin** [kubevirt/kubevirt#2596]
**What happened**:
We are trying to use Kubevirt to create VM that can use the vhost-user capability. As a platform on host, we have “OVS+DPDK” along with MULTUS.
I can use the vhost-user capability for the POD that has container using “UserSpace CNI” but unable to do the same on the Kubevirt.

**What you expected to happen**:
I want the capability of the vhost-user in VM.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.15.0
- Kubernetes version (use `kubectl version`): v1.15.2
- VM or VMI specifications: 
- Cloud provider or hardware configuration:  OVS-DPDK,
- OS (e.g. from /etc/os-release):Ubuntu 16.04
- Kernel (e.g. `uname -a`): Linux ubuntu 4.4.0-62-generic
- Install tools:
- Others:

When I use the Bus as vhost-user or vhost-net , I can see the VM in running statue but there is no corresponding qemu process on host and unable to open console of the VM. 
          Disks:
            Disk:
              Bus:  vhost-user
            Name:   rootfs
            Disk:
              Bus:  vhost-user

**Qemu error**:
root     28227 28199  0 23:04 ?        00:00:00 /usr/bin/virt-launcher --qemu-timeout 5m --name vm-vhost --uid e9221803-d703-4cfa-ba79-5d99d50a              fbea --namespace default --kubevirt-share-dir /var/run/kubevirt --ephemeral-disk-dir /var/run/kubevirt-ephemeral-disks --readiness-file /var/ru              n/kubevirt-infra/healthy --grace-period-seconds 45 --hook-sidecars 0 --less-pvc-space-toleration 10
root     28276 28227  2 23:04 ?        00:00:00 /usr/bin/virt-launcher --qemu-timeout 5m --name vm-vhost --uid e9221803-d703-4cfa-ba79-5d99d50a              fbea --namespace default --kubevirt-share-dir /var/run/kubevirt --ephemeral-disk-dir /var/run/kubevirt-ephemeral-disks --readiness-file /var/ru              n/kubevirt-infra/healthy --grace-period-seconds 45 --hook-sidecars 0 --less-pvc-space-toleration 10 --no-fork true

**###### VM yaml#############**
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: vm-vhost
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: dvmvhsot
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: vhost-user
            name: rootfs
          - disk:
              bus: vhost-user
            name: cloudinit
          interfaces:
          - name: default
            bridge: {}
          - name: enp2s0
            bridge: {}
          - name: enp3s0
            bridge: {}
        resources:
          requests:
            memory: 1024M
      networks:
      - name: default
        pod: {}
      - name: enp2s0
        multus:
          networkName: userspace-networkobj
      - name: enp3s0
        multus:
          networkName: userspace-networkobj
      volumes:
        - name: rootfs
          containerDisk:
            image: kubevirt/ubuntu-firewall
        - name: cloudinit
          cloudInitNoCloud:
            userData: |
              #!/bin/bash
              sysctl -w net.ipv4.conf.all.forwarding=1

**############### User space CNI #####**
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: userspace-networkobj
spec:
  config: '{
    "cniVersion": "0.3.0",
    "type": "userspace",
    "host": {
      "engine": "ovs-dpdk",
      "iftype": "vhostuser"
    }
  }'

**Comment by SchSeba** [comment]
Hi @nmsnitin can you explain the environment a bit more how the cni plugin works?

**Comment by nmsnitin** [comment]
Hi @SchSeba, we are using [userspace-cni-network-plugin](https://github.com/intel/userspace-cni-network-plugin) to create the network objects that implement networking in the user space rather than Kernel Space.
We have OVS with DPDK as the platform in userspace.

**Comment by booxter** [comment]
@nmsnitin I don't think anyone tried the "userspace" CNI plugin with KubeVirt before.

Could you please share:
- kubelet logs;
- `kubectl describe pod` for launcher pod;
- `kubectl logs -c compute` for launcher pod?

I imagine there should be an error either in CNI plugin/Multus logs or in libvirtd that makes the guest fail.

**Comment by SchSeba** [comment]
@nmsnitin can you please also share:

* `kubectl exec -it <virt-launcher-pod> -c compute ip a`
* the network attachment definition `userspace-networkobj`

Thanks!

**Comment by nmsnitin** [comment]
@booxter @SchSeba 
Here are the requested logs

```
root@ubuntu:/opt/nitin/ovs-dpdk# kubectl exec -it virt-launcher-vm-vhost-bs8gh -c compute ip a
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if62148: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master k6t-eth0 state UP group default
    link/ether f6:46:8e:5b:15:2c brd ff:ff:ff:ff:ff:ff link-netnsid 0
4: k6t-eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default
    link/ether f6:46:8e:5b:15:2c brd ff:ff:ff:ff:ff:ff
    inet 169.254.75.10/32 brd 169.254.75.10 scope global k6t-eth0
       valid_lft forever preferred_lft forever
```


###########userspace-networkobj####
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
name: userspace-networkobj
spec:
config: '{
"cniVersion": "0.3.0",
"type": "userspace",
"host": {
"engine": "ovs-dpdk",
"iftype": "vhostuser"
}
}'
```
#################################



[Temp.zip](https://github.com/kubevirt/kubevirt/files/3515411/Temp.zip)

**Comment by nmsnitin** [comment]
@booxter @SchSeba
Here are the kubelet logs
[kubelet-logs-new.zip](https://github.com/kubevirt/kubevirt/files/3515442/kubelet-logs-new.zip)

**Comment by SchSeba** [comment]
Hi @nmsnitin thanks for the logs.

From the kubelet logs looks like you have some issues with the cluster maybe?

Related to the vhost-user I will need to read more about it. if you create an interface from the vhost-user so you will not have an iplink interface (this is way we don't see it in the `ip a` command output) you know where the socket is been created inside the pod?

**Comment by nmsnitin** [comment]
@SchSeba, @booxter   Sorry for a long pause.  
We have created a new setup to deploy a VM using Kubevirt and OVS-DPDK running on the host., We have created some ports of type vHost on Host using OVS-DPDK. 
In the case of Kubernetes container, we use UserSpace Multus CNI (Same as OVS CNI) that itself creates those vHost Ports and attach them with the container, but it is not working in the case of Kubevirt. It shows VM is running  but corresponding Qemu process showing time out.

-Is there any way in Kubevirt, to consume those ports as vhost interfaces in VM using Multus or directly? 


**Snippet of the yaml is below, where we are using vHost Multus CNI object similar to the Kubernetes**
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: vm-vhost
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: dvmvhsot
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootfs
          - disk:
              bus: virtio
            name: cloudinit
          interfaces:
          - name: default
            bridge: {}
          - name: enp2s0
            bridge: {}
          - name: enp3s0
            bridge: {}
        resources:
          requests:
            memory: 1024M
      networks:
      - name: default
        pod: {}
      - name: enp2s0
        **multus:
          networkName: userspace-networkobj**
      **- name: enp3s0
        multus:
          networkName: userspace-networkobj**
      volumes:
        - name: rootfs
          containerDisk:
            image: kubevirt/ubuntu-firewall
        - name: cloudinit
          cloudInitNoCloud:
            userData: |

**Comment by nmsnitin** [comment]
-Is there any way in Kubevirt, to consume those ports as vhost interfaces in VM using Multus or directly?
Can you please provide some direction that will help us to integrate VM(Kubevirt) with OVS+DPDK.

**Comment by nilanjan-samajdar** [comment]
> Hi @nmsnitin thanks for the logs.
> 
> From the kubelet logs looks like you have some issues with the cluster maybe?
> 
> Related to the vhost-user I will need to read more about it. if you create an interface from the vhost-user so you will not have an iplink interface (this is way we don't see it in the `ip a` command output) you know where the socket is been created inside the pod?

@SchSeba 
To answer your query above, the client-socket is created on the OVS/DPDK bridge as follows - 
```
$ VHOST_USER_SOCKET_PATH=/path/to/socket
$ ovs-vsctl add-port br0 vhost-client-1 \
    -- set Interface vhost-client-1 type=dpdkvhostuserclient \
         options:vhost-server-path=$VHOST_USER_SOCKET_PATH
```
Then, when creating the VM using QEMU, the Client-Socket Path is provided as a parameter - 
```
-chardev socket,id=char1,path=$VHOST_USER_SOCKET_PATH,server
-netdev type=vhost-user,id=mynet1,chardev=char1,vhostforce
-device virtio-net-pci,mac=00:00:00:00:00:01,netdev=mynet1
```
If KubeVirt can support the above parameters in the Virt-Launcher and VMI YAML, then we should be able to use OVS/DPDK Vhost-user user-land interfaces in the VM

Please let us know if this is possible

**Comment by nmsnitin** [comment]
I am getting below errors in the VM's log. Can you please help me to understand those error log

**compute** 
`{"log":"{\"component\":\"virt-launcher\",\"level\":\"info\",\"msg\":\"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory')\",\"pos\":\"libvirt.go:362\",\"timestamp\":\"2019-12-11T19:18:44.191856Z\"}\n","stream":"stderr","time":"2019-12-11T19:18:44.191916949Z"}
`

`{"log":"{\"component\":\"virt-launcher\",\"level\":\"error\",\"msg\":\"internal error: Unable to get DBus system bus connection: Failed to connect to socket /run/dbus/system_bus_socket: No such file or directory\",\"pos\":\"virDBusGetSystemBus:108\",\"subcomponent\":\"libvirt\",\"thread\":\"42\",\"timestamp\":\"2019-12-11T19:18:44.240000Z\"}\n","stream":"stderr","time":"2019-12-11T19:18:44.241136712Z"}`

**Comment by fabiand** [comment]
Is this what you were looking for:
https://github.com/kubevirt/kubevirt/pull/3208 @nmsnitin ?
