### ISSUE TITLE
Support for Ignite MicroVMs in Kubevirt

### ISSUE THREAD

**Issue by afritzler** [kubevirt/kubevirt#2601]
I just stumbled upon Ignite[0] from weaveworks which allows you to spawn Firecraker based microVMs from docker images. Would it be a good idea to look into Ignite as an alternative to Qemu to spin up VMs within KubeVirt? Any thoughts on that? Maybe somebody already had this idea before.

/kind enhancement

[0] https://github.com/weaveworks/ignite

**Comment by petrkotas** [comment]
Hi @afritzler, thank you for sharing the idea. If I remember correctly there were already few discussion around this topic. It always boiled to the different use cases between virtualization providers.

The KubeVirt is designed around QEMU to provide a full virtualization in an traditional sense. Think oVirt for instance, but running in the Kubernetes. This means KubeVirt have to provide devices like sriov, vGPU, VNC, multiple networks, ...

In contrast Firecracker is heavily optimized for computing, which is orthogonal to KubeVirts purpose, taken from their [website](https://firecracker-microvm.github.io/#faq):

> Firecracker is a cloud-native alternative to QEMU that is purpose-built for running containers safely and efficiently, and nothing more. Firecracker provides a minimal required device model to the guest operating system while excluding non-essential functionality (there are only 4 emulated devices: virtio-net, virtio-block, serial console, and a 1-button keyboard controller used only to stop the microVM).

Anyway, is there any particular use case, for which you would like to see this feature?

**Comment by Dishwasha** [comment]
I'm not sure what the etiquette is for commenting on a closed and rotten issue is.  The MicroVM concept is useful to reduce VM resource footprints to container equivalents, reduce spin-up times to microseconds, and allow for over-subscription of resources to fit significantly more workloads in the same node configuration.

Although firecracker itself is probably not a good fit for kubevirt, QEMU already supports microVMs https://github.com/qemu/qemu/blob/master/docs/microvm.rst.  Initially this would simply require a different transformer between k8s specs and qemu.   This could fit very nicely in to the kubevirt ecosystem.

The cons of QEMU MicroVMs is you would not be able to pass-through PCIE or SR-IOV resources directly in to the VM, or likely other advanced networking.  Constraints would need to be put in place so those incompatible CNI plugins are prevented from attempting to allocate resources for these VM types.

**Comment by petrkotas** [comment]
@Dishwasha thanks for giving more background. @fabiand what do you make out of this? Would this be a fit?

**Comment by fabiand** [comment]
@Dishwasha Heya. I think that it is surely soemthing that KuebVirt should investigate, to understand how we could work with other (especially qemu based) runtimes.

Would you mind to prepare a basic PR in order to sue a different runtime?

**Comment by Dishwasha** [comment]
@fabiand I've never done Go before, but I assume it can't be that much different from C/C++/C#...  I'll try to find some time for this over the next few weeks, but will be happy to whip up something even if it's a bit rough around the edges.

**Comment by fabiand** [comment]
Would be great!
