### ISSUE TITLE
namespace stuck in terminating

### ISSUE THREAD

**Issue by mjschmidt** [kubevirt/kubevirt#2605]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
installed kubevirt using https://kubevirt.io/user-guide/docs/latest/administration/intro.html
then tried to delete the yaml files by replacing all apply commands with delete. Namespace is now stuck in terminating
**What you expected to happen**:
all k8s objects to clean up
**How to reproduce it (as minimally and precisely as possible)**:
install and uninstall

**Anything else we need to know?**:
The docs should probably be updated to the lastest version of 0.20.1
**Environment**:
- KubeVirt version (use `virtctl version`):N/A
- Kubernetes version (use `kubectl version`):1.13.9-rancher
- VM or VMI specifications:software based deploy with config map
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Centos7.5
- Kernel (e.g. `uname -a`):Linux ip-10-113-78-138 3.10.0-957.5.1.el7.x86_64 #1 SMP Fri Feb 1 14:54:57 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:kubectl
- Others:

**Comment by mjschmidt** [comment]
This is probably simular to this issue, but I am pretty sure I did clean up all the crds so I am not sure what else kubevirt could be holding the ns back from terminating

https://github.com/kubernetes/kubernetes/issues/60807

**Comment by mjschmidt** [comment]
Playing around with the cluster I was able to get it to delete, I cannot reporduce. I really hope the fix the Namespace issues in Kubernetes this has been a problem for a year. We can close, but just know there might be a problem here in the future for kubevirt...

**Comment by slintes** [comment]
Hey @mjschmidt, thanks for reporting this. The issue probably was that after deleting the CustomResource, and before deleting the operator (as described here [0]), you need to wait until KubeVirt was undeployed. If you don't do that, the operator can't finish cleanup, especially removing finalizers. We should improve this in the user-guide.

[0] https://kubevirt.io/user-guide/docs/latest/administration/intro.html#delete
