### ISSUE TITLE
virtctl not working, configuration location not documented in how to guide

### ISSUE THREAD

**Issue by mjschmidt** [kubevirt/kubevirt#2608]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG
 Uncomment only one, leave it on its own line:
 /kind bug

**What happened**:
Followed the install guide, was able to successfully install and start a vm, but only using the kubectl apply and patch commands. The virtctl tool does not work regardless of whether i install with crew or just use the amd linux command line tool.

**What you expected to happen**:
kubectl virt version should return the server version from the kubevirt ns (I tried having default k8s context be kubevirt and default with no luck)

```
# Start the virtual machine:
kubectl patch virtualmachine myvm --type merge -p \
    '{"spec":{"running":true}}'
```

```
./virtctl stop testvm
Error stopping VirtualMachine the server could not find the requested resource
```

**How to reproduce it (as minimally and precisely as possible)**:
Follow the create your kubevirt vm guide found [here](https://kubevirt.io/labs/kubernetes/lab1)

**Anything else we need to know?**:
I also tried to change the service of the server/api to a NodePort. That also failed, I am not sure how or where configuration for kubevirt cli is normally set.

```
NAME                                   READY   STATUS    RESTARTS   AGE
pod/virt-api-788f97c65b-qrt4l          1/1     Running   0          68m
pod/virt-api-788f97c65b-wt8bb          1/1     Running   0          68m
pod/virt-controller-6f6695b47c-nphml   1/1     Running   0          67m
pod/virt-controller-6f6695b47c-r59t9   1/1     Running   0          67m
pod/virt-handler-7dhvs                 1/1     Running   0          67m
pod/virt-handler-vm9cd                 1/1     Running   0          67m
pod/virt-handler-x9gsq                 1/1     Running   0          67m
pod/virt-launcher-testvm-qpkcl         2/2     Running   0          46m
pod/virt-operator-688dddf777-492zc     1/1     Running   0          69m
pod/virt-operator-688dddf777-z5sl2     1/1     Running   0          69m

NAME                                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)         AGE
service/kubevirt-prometheus-metrics   ClusterIP   10.43.147.227   <none>        443/TCP         68m
service/virt-api                      NodePort    10.43.168.200   <none>        443:32179/TCP   68m

NAME                          DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR   AGE
daemonset.apps/virt-handler   3         3         3       3            3           <none>          67m

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/virt-api          2/2     2            2           68m
deployment.apps/virt-controller   2/2     2            2           67m
deployment.apps/virt-operator     2/2     2            2           69m

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/virt-api-788f97c65b          2         2         2       68m
replicaset.apps/virt-controller-6f6695b47c   2         2         2       67m
replicaset.apps/virt-operator-688dddf777     2         2         2       69m

NAME                            AGE   PHASE
kubevirt.kubevirt.io/kubevirt   1h    Deployed

NAME                                        AGE   PHASE     IP           NODENAME
virtualmachineinstance.kubevirt.io/testvm   46m   Running   10.42.2.19   ip-omitted

NAME                                AGE   RUNNING   VOLUME
virtualmachine.kubevirt.io/testvm   48m   true

```

**Environment**:
- KubeVirt version (use `virtctl version`): "v0.20.1"
- Kubernetes version (use `kubectl version`): "v1.13.4"
- VM or VMI specifications: The test vm
- Cloud provider or hardware configuration: Hardware / Rancher Cluster
- OS (e.g. from /etc/os-release): CentOS 7.5+
- Kernel (e.g. `uname -a`): N/A
- Install tools: https://kubevirt.io/user-guide/docs/latest/administration/intro.html
- Others:

**Comment by SchSeba** [comment]
Hi @mjschmidt 

can you try to run this command `virtctl start <vm-name> -v 10` and share the output please

**Comment by slintes** [comment]
`virtctl` should use the same config as `kubectl`. If that does not work, it's a bug indeed. For verifying, can you please try setting the location manually with the `--kubeconfig` flag? Find more flags etc with `virtctl help` and `virtctl options`.

**Comment by mjschmidt** [comment]
@slintes same error. I wonder if it is because 
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <omitted>
    server: https://<omitted>/k8s/clusters/<omitted>
  name: michaelcloud
contexts:
- context:
    cluster: michaelcloud
    namespace: kubevirt
    user: user-9thkk
  name: michaelcloud
current-context: michaelcloud
kind: Config
preferences: {}
users:
- name: user-9thkk
  user:
    token: kubeconfig-user-9thkk:<omitted>
```

This seems like a bug to me? To reproduce you can run a quick docker run command to get a rancher server up and running in literally and then use rancher to deploy a quick 3 node cluster or something.
I have run a lot of other services on rancher created k8s clusters and never had an issue. If you want me to pull more info just let me know what commands you need me to run.

1) The run command:
sudo docker run -d --restart=unless-stopped -p 80:80 -p 443:443 rancher/rancher

2) To access the Rancher server UI, open a browser and go to the hostname or address where the container was installed. You will be guided through setting up your first cluster.

3) From there making a cluster becomes super easy.

@SchSeba same error, I would assume there is no verbose message if it can't get any logs from server.
```
virtctl start testvm -v 10
Error starting VirtualMachine the server could not find the requested resource
```

**Comment by mjschmidt** [comment]
This is the kubeconfig used to start and stop the vm with patch
```
kubectl get vm
NAME     AGE   RUNNING   VOLUME
testvm   1d    true
```

then stopping
```
kubectl patch virtualmachine testvm --type merge -p     '{"spec":{"running":false}}'
virtualmachine.kubevirt.io/testvm patched
kubectl get vm
NAME     AGE   RUNNING   VOLUME
testvm   1d    false
```

**Comment by mjschmidt** [comment]
Was this helpful? Is there some sort of ticket made to handle this? Are you guys still looking into it? Anything else I can do on my end to provide more info or investigate further?

**Comment by slintes** [comment]
Hey, sorry, just didn't have time yet to have a further look into this. Thanks for providing steps to reproduce! Will give it a try asap.

**Comment by mjschmidt** [comment]
Okay thank you @slintes! And again if you have any questions I am here!

**Comment by mjschmidt** [comment]
By the way, I don't think this has anything to do with the deployment, but emulation is turned on for this.

**Comment by slintes** [comment]
> kubectl commands first go to the rancher server, and then are forwarded to the cluster

That's an interesting detail indeed. virtctl uses custom endpoints, which are provided by our virt-api container, and are registered as "aggregated api" at the k8s api-server. Maybe rancher recognize this and blocks requests to such aggregated api severs? Then the next thing is, that for virtctl console/vnc we upgrade the http connection to websocket, curious how the rancher server deals with it once the first issue is resolved.
I'm planning to give the rancher setup at try later today.
Thanks for the valueable feedback!

**Comment by slintes** [comment]
just gave it a quick try and can't even install kubevirt, because virt-operator can't reach the k8s apiserver. This is a really weird setup with Rancher. Can you give some more details about your setup please? Do you use a cloud provider, or the local setup where you start "nodes" with docker? Which network provider?

**Comment by slintes** [comment]
oh, and no, ingress isn't an alternative imho, virtctl should work the same way as kubectl does

**Comment by natemoseman** [comment]
As a sort of work around...

In the kubeconfig that is generated by rancher they setup a bunch of different 'clusters' and 'contexts' in there.  There is a context setup for each node in the cluster.

If you change your context in ~/.kube/conf to one of those other contexts so the api calls don't go through the rancher API proxy thingy then virtctl starts working.

**Comment by slintes** [comment]
Thx @natemoseman! That kind of proves my assumption that rancher does not work well with aggregated apiservers.

**Comment by mjschmidt** [comment]
I will try this out and let you guys know how it goes! Thanks for the advisement!

**Comment by mjschmidt** [comment]
@natemoseman sorry can you provide an example of doing such a work around? I am not seeing any contexts in my rancher kubeconfig that would allow me to talk directly to the cluster?

```
apiVersion: v1
kind: Config
clusters:
- name: "testquickstart"
  cluster:
    server: "https://<domain to rancher server>/k8s/clusters/c-9d6mp"
    api-version: v1
    certificate-authority-data: <omitted>
    <cert-data>
    <cert-data>
    <cert-data>
    <cert-data>
    <cert-data>
    <cert-data>
    <cert-data>

users:
- name: "user-9thkk"
  user:
    token: "<omitted>"

contexts:
- name: "testquickstart"
  context:
    user: "user-9thkk"
    cluster: "testquickstart"

current-context: "testquickstart"
```

**Comment by mjschmidt** [comment]
When I tried to point the server directly at a master node for a cluster I get a x509 because the certificate auth is for the rancher server not my work station.

**Comment by mjschmidt** [comment]
Disregard for now, I updated to a new rancher version and provisioned a newer cluster from that updated rancher. I now see the seperate kubeconfig to talk directly to my cluster. Going to redeploy and test virctl wit that kubeconfig.

**Comment by mjschmidt** [comment]
Can confirm, kubevirt works when a direct endpoint to the cluster is used over port 6443. So this is a feature request to support virtctl via a proxy server rather than a bug request  and should probably just be captured as a pre req section that you must have direct connection to your cluster.

**Comment by mjschmidt** [comment]
Can confirm, kubevirt works when a direct endpoint to the cluster is used over port 6443. So this is a feature request to support virtctl via a proxy server rather than a bug request  and should probably just be captured as a pre req section that you must have direct connection to your cluster. Thanks for the help everyone! Kubevirt looks like a great project I'm excited to dig in more.

**Comment by slintes** [comment]
> Can confirm, kubevirt works when a direct endpoint to the cluster is used over port 6443

nice!

> So this is a feature request to support virtctl via a proxy server

well, I don't see what we can do here, this looks like a result of the "interesting" default setup of Rancher, and their default "api server" or proxy or whatever it is does not work as expected.

> Kubevirt looks like a great project I'm excited to dig in more.

Thanks and enjoy! :slightly_smiling_face:

**Comment by mjschmidt** [comment]
So being able to point virtctl at an ingress would be nice and having kubevirt support an ingress controller. Then you could point at the ingress without having to point at master node at 6443 (:

**Comment by mjschmidt** [comment]
Still an awesome project so far, making lots of progress.

**Comment by slintes** [comment]
> So being able to point virtctl at an ingress would be nice and having kubevirt support an ingress controller. Then you could point at the ingress without having to point at master node at 6443 (:

I don't see a real usecase for this. virtctl is supposed to work similar to kubectl, so it needs access to the apiserver. With krew [0][1] you can even install and use it as a kubectl plugin.

@fabiand wdyt?

[0] https://github.com/kubernetes-sigs/krew
[1] https://github.com/kubernetes-sigs/krew-index/blob/master/plugins.md

**Comment by mjschmidt** [comment]
Hi I was out for a week. My exact setup is using the ha rancher deploy and then creating a cluster from those rancher servers using the "custom" option, which on the back end just uses rke to create a cluster.

We may need to ask the rancher folks how kubectl commands are forwarded to the cluster...

**Comment by mjschmidt** [comment]
Again, rancher gives direct access to the kubernetes api now, so when I use that context it works fine.

**Comment by mjschmidt** [comment]
Closing issue since this works for me.

**Comment by ajith29** [comment]
If someone like me is coming to find out how to make virtctl work on rancher in prem
This is how I got virtctl to work with rancher on prem
Using this link gave me an hint that we can pull the api-server kubeconfig and talk to it directly https://github.com/rancherlabs/support-tools/tree/master/how-to-retrieve-kubeconfig-from-custom-cluster
then ssh into the contral-plane node and performed the steps that got the kubeconfig
Then changed the server in the kubeconfig to the ip of the control-plane since it had 127. This kubeconfig has to used from my dektop so had to do this.
kubectl --kubeconfig=./kubeconfig_admin.yaml get nodes
failed "Unable to connect to the server: x509: certificate is valid for servers localhost, kubernetes, kubernetes.default, kubernetes.default.svc, kubernetes.default.svc.cluster.local, "
so this link gave https://ahmet.im/blog/mastering-kubeconfig/ a hint to run the command
kubectl --kubeconfig=./kubeconfig_admin.yaml get nodes --insecure-skip-tls-verify
this worked so used it with virtctl hope this helps.
