### ISSUE TITLE
PROPOSAL|PROVOKING: kubevirt as expedited containernet(network emulator)

### ISSUE THREAD

**Issue by cherusk** [kubevirt/kubevirt#2609]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST/Proposal

> Uncomment only one, leave it on its own line:
>
> /kind enhancement

As kubevirt comes with container-disks, that makes it an ideal candidate to swiftly and concisely spin up network emulation instance. Moreover, that's in a far more sophisticated way than containernet is meant to be capable so far, when one spun it far enough. Harsh part seems to be down to tuggin together network instances with micro-VMs, especially in larger scale emulations, where the emulated network would have to be scaled and orchestrated consistently to the intended scenarios etc. istio/mixer seems to allow for some baseline srvc network qualitiy setup, presume it's not expedited to qualify for a comprehensive network compartments emulation fabric. Could it be enhanced to do so. Should container-net open-flow fabric be leveraged to become such a network emulation core? Any other approaches thinkable?

**Anything else we need to know?**:

Stemming from, connected to: https://github.com/karmab/kcli/issues/154

**Environment**:
- KubeVirt version (use `virtctl version`): latest

**Comment by cynepco3hahue** [comment]
I do not really familiar with the subject, maybe you can explain what features are lacking under the KubeVirt and we can discuss if it possible(worth) to implement it under the KubeVirt?

**Comment by cherusk** [comment]
Think I've specified most relevant. Couldn't you also look up also what is behind **containernet** and draw the parallels.

Conceptionally, not much is "lacking", all the bricks are, but for an emulator, certainly the "virtual" network quality specification|configurability, say latency,throughput, jitter needs to be enable.

Clearer? Might other media?

**Comment by petrkotas** [comment]
@cherusk this is actually quite interesting proposal. Would you mind specifying the use-case you are looking for? It helps us to determine priorities.

**Comment by cherusk** [comment]
@petrkotas - I'd say there's no "confined" use case as such, such an emulation capability should be generic enough from my perspective. It's only the current emulators, including container-net hardly ever covered the full spectrum of emulation needs thinkable, e.g. including local node specifics, which containers can be too non-representative at times, e.g. for lacking virtual NIC etc., you call it.

Nigh, much started here, also involving containernet creators:
https://github.com/karmab/kcli/issues/154

kcli abstracts fledging micro-vm technologies, amongst others. It'd be harder to do it with other enveloped than kubevirt I believe.

Certainly more to it ... have to process also. :)

**Comment by petrkotas** [comment]
@cherusk thanks for your feedback. From my perspective we are slowly approaching such functionality. IT will take some time to enable full feature set, especially the network part.

But we will get there. If you need specific functionality to be enabled, please specify it preferably with the reason for it. This allows us to set priorities and do a roadmap.

Thank you for you input!

**Comment by cherusk** [comment]
@petrkotas pardon, almost repeated initial statement, not brightest moment.

Let me attempt:
- having network specifics cnfg as to network quality exposed as paramters. That a starting point

Might close as doc from here.
