### ISSUE TITLE
Connect virtual machines to cluster network - allow them to reach pods

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#261]
> As a user I want to be able to reach any pod on the cluster from my virtual machine

So far we've got no networking, but to start this, we should start with something simple
In the K8s context a simple network request is, that  any virtual machine will be able to speak to any pod.

At best - before implementing something - we should gather an overview over possible implementations, to understand each of their pros and cons.

Now that the mission statement is clarified, it is now clear that we want to consume K8s infrastructure if possible, networking is such an infrastructure.
Thus a solution to launch VMs should build on this, and leverage libvirtd without breaking it's boundaries.

**Comment by dcbw** [comment]
@fabiand we've discussed VM-based networking in the CNI maintainer meetings many times, but we're not clear yet on how most VM-based/hypervisor-based solutions prefer to do networking.  Could we have a chat some time about that?  We tried to build in some hypervisor stuff into CNI 0.3.0 spec but didn't have any consumers so we're not sure what the gaps are.

But the ideal world is that a VM/hypervisor CNI networking plugin should be doable and work as smoothly as the existing plugins do.

**Comment by fabiand** [comment]
@dcbw I'd be happy to join that conversation. Let me catch you off list and we take it from there.

**Comment by fabiand** [comment]
Depends on #663

**Comment by simon3z** [comment]
@fabiand should we close this?

**Comment by fabiand** [comment]
Yes.
