### ISSUE TITLE
Create a kubevirt compatible image from an iso image

### ISSUE THREAD

**Issue by mbhatnagar11** [kubevirt/kubevirt#2633]
I am trying to create a Kubevirt compatible image using an iso file . I am using `kubevirt/cirros-registry-disk-demo` as the base image and adding my iso on top of it . Below are the contents of my Docker file : 

`FROM kubevirt/cirros-registry-disk-demo
ADD VYOS.img /disk
`

I am able to create an image using this docker file but when I create a VM using this image , effects of the iso image are not seen in the created VM .

**Comment by cynepco3hahue** [comment]
@mbhatnagar11 Can you please share virt-launcher and virt-handler logs?
