### ISSUE TITLE
Avoid more than 1 ongoing live migrations

### ISSUE THREAD

**Issue by ahadas** [kubevirt/kubevirt#2652]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
It is possible to initiate two live migrations for the same VMI at the same time

**What you expected to happen**:
The system should have blocked me from initiating an additional live-migration until the first migration is completed (successfully or with failure)

**How to reproduce it (as minimally and precisely as possible)**:
1. Create VMI
2. Post one migration job for the VMI
3. Post another migration job for the VMI before the previous migration is completed

**Anything else we need to know?**:
The second migration attempt would probably be rejected by libvirt, but it would be better to block it earlier at the apiserver level

**Comment by jichenjc** [comment]
seems a logic prevent this ..

```
 // Don't allow new migration jobs to be introduced when previous migration jobs
        // are already in flight.
        if vmi.Status.MigrationState != nil &&
                string(vmi.Status.MigrationState.MigrationUID) != "" &&
                !vmi.Status.MigrationState.Completed &&
                !vmi.Status.MigrationState.Failed {

                return webhooks.ToAdmissionResponseError(fmt.Errorf("in-flight migration detected. Active migration job (%s) is currently already in progress for VMI %s.", string(vmi.Status.MigrationState.MigrationUID), vmi.Name))
        }
```
