### ISSUE TITLE
Support stock Kubernetes file-system volume claims as virtual disks

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#266]
> As an admin I want to be able to use my file-system based storage for vm disks

KubeVirt currently has one good way to support volume claims which are backed by qemu supported network block storage (qemu, cpeh, gluster).

But as an admin, I'd expect that KubeVirt supports the default Kubernetes volumes regardless of their backing storage type.
I.e. I'd expect that I can use my NFS shares to hosts disks for VMs.

- [x] Design
- [ ] Implementation

**Comment by dyaniv** [comment]
I would suggest two approaches here:
- Short term easy win solution of having the volume claim host a single qcow file per VM.

- Taking the virtfs (via NFS + virtio-vsock) approach of passing the file system to the VM directly. 
This is an ongoing work that is being done in upstream: https://bugzilla.redhat.com/show_bug.cgi?id=1294884
This will include Windows support as well: https://bugzilla.redhat.com/show_bug.cgi?id=1378137

I do not think we should support several disks per volume and maintain a 1:1 volume claim to disk use.
