### ISSUE TITLE
failed to pull kubevirt/cdi-operator:v1.10.1 images

### ISSUE THREAD

**Issue by jichenjc** [kubevirt/kubevirt#2667]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
k8s1.15.1 env

```
root@jj-virt:~/go/src/github.com/kubevirt/kubevirt# ./cluster-up/kubectl.sh get pods --all-namespaces
NAMESPACE     NAME                                      READY   STATUS             RESTARTS   AGE
cdi           cdi-operator-5db567b486-grtk9             0/1     ImagePullBackOff   0          42m


Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  42m                    default-scheduler  Successfully assigned cdi/cdi-operator-5db567b486-grtk9 to node01
  Normal   Pulling    38m (x4 over 42m)      kubelet, node01    Pulling image "kubevirt/cdi-operator:v1.10.1"
  Warning  Failed     37m (x4 over 41m)      kubelet, node01    Error: ErrImagePull
  Warning  Failed     22m (x57 over 41m)     kubelet, node01    Error: ImagePullBackOff
  Warning  Failed     12m (x9 over 41m)      kubelet, node01    Failed to pull image "kubevirt/cdi-operator:v1.10.1": rpc error: code = Unknown desc = context canceled
  Normal   BackOff    2m25s (x133 over 41m)  kubelet, node01    Back-off pulling image "kubevirt/cdi-operator:v1.10.1"
```
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by slintes** [comment]
hm, works on my machine...
```
$ docker pull kubevirt/cdi-operator:v1.10.1
v1.10.1: Pulling from kubevirt/cdi-operator
6dbefcee4a4b: Pull complete
520330dd34bf: Pull complete
88b1f18d9fa9: Pull complete
d21d8c54868c: Pull complete
719f91d56543: Pull complete
Digest: sha256:bd107a597c3c6311d38efb2a5b486556e3db6711d3b041b158e846994f7b1aa3
Status: Downloaded newer image for kubevirt/cdi-operator:v1.10.1
docker.io/kubevirt/cdi-operator:v1.10.1
```
Is it reproducable? Maybe just a temporary network hickup? Do other pods start?

**Comment by jichenjc** [comment]
tried 3 times, same issue and reproducable
and ,the other images can be pulled correctly...

I will try again tomorrow and see whether it works or not
thanks for try

**Comment by SchSeba** [comment]
@zvikorn can you please take a look on this?

**Comment by cynepco3hahue** [comment]
@jichenjc Probably it some problem with our kubevirtci cluster, can you ssh to the VM and try to pull image manually, sometimes when you change network(ethernet to wi-fi), cluster stop to get the traffic.

**Comment by jichenjc** [comment]
werid... I can pull from my host, but vargent VM can't ... I can curl means http is ok..not sure what happened, 

```
root@jj-virt:~/go/src/github.com/kubevirt/kubevirt# ./cluster-up/ssh.sh node01
2019/09/05 07:20:18 Waiting for host: 192.168.66.101:22
2019/09/05 07:20:18 Connected to tcp://192.168.66.101:22
[vagrant@node01 ~]$

[root@node01 ~]# docker pull nginx
Using default tag: latest
Trying to pull repository docker.io/library/nginx ...
^C
[root@node01 ~]# curl www.sina.com.cn
<html>
<head><title>302 Found</title></head>
<body bgcolor="white">
<center><h1>302 Found</h1></center>
<hr><center>nginx</center>
</body>
</html>


```

**Comment by jichenjc** [comment]
ok, I can't pull the image in container but I can pull from my host.. don't know the reason

**Comment by rmohr** [comment]
@jichenjc a very common issue is a `mtu` mismatch between your host ethernet device and the docker bridge (`docker0`). On many occasions I have seen `1500` on `docker0` and `eth0` had `1450`. Then some things work and some things behave strange.

**Comment by jichenjc** [comment]
ok, appreciate the info, I will check this soon :) thanks!

**Comment by jichenjc** [comment]
[vagrant@node01 ~]$ sudo ip link set dev eth0 mtu 1450
[root@node01 ~]# docker -D pull kubevirt/cdi-operator:v1.10.1
Trying to pull repository docker.io/kubevirt/cdi-operator ...
v1.10.1: Pulling from docker.io/kubevirt/cdi-operator
6dbefcee4a4b: Downloading   403 kB/40.3 MB
520330dd34bf: Download complete
88b1f18d9fa9: Downloading 669.4 kB/3.121 MB

**Comment by jichenjc** [comment]
The MTU helped me ,I will open a PR to add some doc update..

**Comment by rmohr** [comment]
@jichenjc great that it helped. However, changing this inside the VM will not be permanent. The next time you do cluster-down and cluster-up the change will be lost again. In your case it seems like docker on your server/notebook/pc is not configured correctly. Your notebook probably hase MTU 1450 and the docker bridge probably has 1500. I would recommend to fix the docker setup (something like restart the docker daemon and adding `--mtu 1450` should solve that). Our development setup just shows you the symptom.

**Comment by rwmjones** [comment]
Can someone describe what the actual fix is for this?  Where exactly should `--mtu 1450` be placed?
