### ISSUE TITLE
Flaky tests: domain is started but the vmi is still scheduled

### ISSUE THREAD

**Issue by fedepaol** [kubevirt/kubevirt#2672]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

While looking at this https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2576/pull-kubevirt-e2e-os-3.11.0-crio/1159042117620731904 flaky test report (test [rfe_id:694][crit:medium][vendor:cnv-qe@redhat.com][level:component]Networking Multiple virtual machines connectivity using bridge binding interface should be able to reach [test_id:1539]the Inbound VirtualMachineInstance), I found the following situation:

We have four vmis started, the launcher seems to be ok but the state of the vmi never reaches the running state.

Now, after spending a lot of time on this I feel I am hitting a wall, probably because of my ignorance of some of the parts involved.
I'll try to add as much value as I can from what I think I understood.

I'll focus on the logs of two out of the four vmis.

#### VMI testvmiw8s5wlv9zrkh857x4llpqrv728qbgld92t2q4qfpkpkxm8vs:
`Status.Phase == Failed`

Looking at [the launcher logs](https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2576/pull-kubevirt-e2e-os-3.11.0-crio/1159042117620731904/artifacts/pods/2_kubevirt-test-default_virt-launcher-testvmiw8s5wlv9zrkh857x4llpqrv728qbgld92t2q4bkw5m-compute.log), everything seems fine.
The domain is started, and probably the event is passed to the handler.
```
{"component":"virt-launcher","level":"info","msg":"kubevirt domain status: Running(1):Unknown(1)","pos":"client.go:179","timestamp":"2019-08-07T15:09:50.918967Z"}
```

[In the handler](https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2576/pull-kubevirt-e2e-os-3.11.0-crio/1159042117620731904/artifacts/pods/2_kubevirt_virt-handler-dmvz7-virt-handler.log) the running event is received, and it's the last dumped state of the domain in the handler:
```
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Domain is in state Running reason Unknown","name":"testvmiw8s5wlv9zrkh857x4llpqrv728qbgld92t2q4qfpkpkxm8vs","namespace":"kubevirt-test-default","pos":"vm.go:1534","timestamp":"2019-08-07T15:09:50.916083Z","uid":"5e791057-b925-11e9-8485-525500d15501"}
```

The vm managed to reach the running state. I can see an event on the event log "VirtualMachineInstance started."

Events: https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2576/pull-kubevirt-e2e-os-3.11.0-crio/1159042117620731904/artifacts/2_events.log

So I don't understand why the vm is in failed state.

Reasons for having the phase in Failed:
- migration related (excluded, the migration labels are not there)
- expiration of the watchdog file while scheduling the vm (or not having the file anymore). https://github.com/kubevirt/kubevirt/blob/560eaa35adde9663cde334dc5af190fe0ed07f95/pkg/virt-handler/vm.go#L1454  
- having the domain in state api.Shutoff, api.Crashed. (excluded, I would have seen an event in the handlers logs) https://github.com/kubevirt/kubevirt/blob/560eaa35adde9663cde334dc5af190fe0ed07f95/pkg/virt-handler/vm.go#L1466

#### VMI testvmi22qn2qqthvgqbjrj6fmfk7v2f5rv5wxcdchhqhtj7bpfxd5f

Again, [the launcher is living the dream](https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2576/pull-kubevirt-e2e-os-3.11.0-crio/1159042117620731904/artifacts/pods/2_kubevirt-test-default_virt-launcher-testvmi22qn2qqthvgqbjrj6fmfk7v2f5rv5wxcdchhqmrdf8-compute.log).

```
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"testvmi22qn2qqthvgqbjrj6fmfk7v2f5rv5wxcdchhqhtj7bpfxd5f","namespace":"kubevirt-test-default","pos":"server.go:167","timestamp":"2019-08-07T15:09:51.348130Z","uid":"5e980e87-b925-11e9-8485-525500d15501"}
{"component":"virt-launcher","level":"info","msg":"processed event","pos":"client.go:235","timestamp":"2019-08-07T15:09:51.379696Z"}
{"component":"virt-launcher","level":"info","msg":"kubevirt domain status: Running(1):Unknown(1)","pos":"client.go:179","timestamp":"2019-08-07T15:09:51.392459Z"}
```

[On the handler]((https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2576/pull-kubevirt-e2e-os-3.11.0-crio/1159042117620731904/artifacts/pods/2_kubevirt_virt-handler-dmvz7-virt-handler.log)) the state change is received:
```
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Domain is in state Running reason Unknown","name":"testvmi22qn2qqthvgqbjrj6fmfk7v2f5rv5wxcdchhqhtj7bpfxd5f","namespace":"kubevirt-test-default","pos":"vm.go:1534","timestamp":"2019-08-07T15:09:51.366694Z","uid":"5e980e87-b925-11e9-8485-525500d15501"}
```

But the vmi never reaches the running state. No running event is recorded.
Events: https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2576/pull-kubevirt-e2e-os-3.11.0-crio/1159042117620731904/artifacts/2_events.log

That running event should be recorded in the shared informer's cache. They are produced by the same goroutine invoking `eventCallback`, and the state of the domain is fetched every time an event is sent, so I think it's unlikely that an older status reached the handler later than the running status.
The events are written on the channel that feeds the shared informer, which update the cache and throw an event.

The event is then written in the queue, which is read by 10 workers. 
Here I think _it could be_ that a running event is received and handled while the creation of the vmi is still in progress, but if it was the case the running event would have been generated.

Other cases where the worker can silently drop the running event:

https://github.com/kubevirt/kubevirt/blob/560eaa35adde9663cde334dc5af190fe0ed07f95/pkg/virt-handler/vm.go#L937 
Don't think this is the case, since the domain is created using the vmi uid.

https://github.com/kubevirt/kubevirt/blob/560eaa35adde9663cde334dc5af190fe0ed07f95/pkg/virt-handler/vm.go#L330
Which is not the case, looking at the vm labels

https://github.com/kubevirt/kubevirt/blob/560eaa35adde9663cde334dc5af190fe0ed07f95/pkg/virt-handler/vm.go#L501
old status is the status recorded in the cache, can't be running otherwise I would see an event stating that.

So I think it's either one of these three cases or for some reason the running event was overwritten in the cache before getting consumed.

#### Another strange thing here is:

After a while there are these events in the handler:

```
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Domain deleted","name":"testvmi22qn2qqthvgqbjrj6fmfk7v2f5rv5wxcdchhqhtj7bpfxd5f","namespace":"kubevirt-test-default","pos":"vm.go:1524","timestamp":"2019-08-07T15:10:20.710922Z","uid":""}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Domain deleted","name":"testvmiskbt2fj6mzj6dbvgb7pctldrxlgdtp52zff9tq72qt8jf8bg","namespace":"kubevirt-test-default","pos":"vm.go:1524","timestamp":"2019-08-07T15:10:22.499662Z","uid":""}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Domain deleted","name":"testvmiw8s5wlv9zrkh857x4llpqrv728qbgld92t2q4qfpkpkxm8vs","namespace":"kubevirt-test-default","pos":"vm.go:1524","timestamp":"2019-08-07T15:10:22.499956Z","uid":""}
```

They don't have the associated log log.Log.Infof("Received Domain Event of type %s", request.EventType), and there is another (two cases) where it could happen:
https://github.com/kubevirt/kubevirt/blob/db76f4acc187e35541b7cff8e6c3e99073fef329/pkg/virt-handler/cache/cache.go#L106
https://github.com/kubevirt/kubevirt/blob/db76f4acc187e35541b7cff8e6c3e99073fef329/pkg/inotify-informer/inotify.go#L86

Which again, means that the watchdog files are not getting updated or the dir was removed.

### Some parts that probably deserve better logs :

- The watchdog expiration. Since it's an exceptional event with relevant results, I would log it.
- Whenever an update is processed by the worker, the state of the vmi and of the domain (and if they are there)
- I would extend the logs of type "Received Domain Event of type MODIFIED" with the name of the domain

**Comment by slintes** [comment]
Thanks a lot for taking the time for investigating flaky tests :+1: 
I only had a quick look at the first vmi you investigated, for it there also is a k8s event "The VirtualMachineInstance crashed". So I assume something went wrong with virtual machine itself. Hard to tell what. 
Is this somewhat reproducable? Maybe worth enabling libvirt debug logs (see https://github.com/kubevirt/kubevirt/pull/2571). But please not on more VMs than needed, I heard debug logs are huge :wink:

**Comment by fedepaol** [comment]
I think the crashed event is related to the first case I analyzed (testvmiw8s5wlv9zrkh857x4llpqrv728qbgld92t2q4qfpkpkxm8vs). 

Again, from the launcher point of view everything is fine, the state is written by the handler that then generates that event here:
https://github.com/kubevirt/kubevirt/blob/560eaa35adde9663cde334dc5af190fe0ed07f95/pkg/virt-handler/vm.go#L507

I tried to find possible explanations to that, since no failure state is produced by the launcher nor received by the handler, and I have the gut feeling that that is related to the watchdog as I wrote in my (very long) description

**Comment by fedepaol** [comment]
(and of corse I did not manage to reproduce it)
