### ISSUE TITLE
How to realize the initialization system is windows

### ISSUE THREAD

**Issue by linqingping** [kubevirt/kubevirt#2677]
I can use nocloud to initialize the Linux system，but I can‘t use nocloud to initialize the Windows system！Is there any relevant information or case available?

**Comment by cynepco3hahue** [comment]
Currently, we do not have one, it possible to add Sysprep file, but I do not aware if do we have it on the road map.

**Comment by petrkotas** [comment]
The support for sysprep is currently discussed. Please stay put.
