### ISSUE TITLE
Enable DCO

### ISSUE THREAD

**Issue by caniszczyk** [kubevirt/kubevirt#2678]
Ensure DCO checking is enabled for all repos

https://github.com/apps/dco

cc: @fabiand

**Comment by fabiand** [comment]
@dhiller can oyu please take a look at this?

/cc @rmohr

**Comment by dhiller** [comment]
Will do.

**Comment by dhiller** [comment]
@fabiand In order to enable this I need access to the repository settings. I need to enable the status check within the [branch protection settings](https://github.com/probot/dco/blob/master/docs/required-statuses.md) for the Sign Off check done by DCO to be enforced.

**Comment by fabiand** [comment]
Ok, I can grant you those.
Before enforcing the DCO: Please send out an email explaining why we are doing this, why it's now needed.

**Comment by dhiller** [comment]
I've sent the DCO installation request. Now someone needs to ACK that within the organization settings under _Installed GitHub Apps_ .

**Comment by dhiller** [comment]
@fabiand ^^

**Comment by fabiand** [comment]
@dhiller you should have all needed permissions now

**Comment by rmohr** [comment]
/close

We have dco enabled across all repos.

**Comment by fabiand** [comment]
@dhiller I think this is done, not?
