### ISSUE TITLE
Get a passing score for CII Best Practices Badge

### ISSUE THREAD

**Issue by caniszczyk** [kubevirt/kubevirt#2679]
This is a requirement for CNCF:

https://bestpractices.coreinfrastructure.org/en

**Comment by fabiand** [comment]
Yeah - We started on it and should actually finish it.

**Comment by rmohr** [comment]
Badge is now there. We currently have 77%. Improving it should be simple, just minor gaps. The main point is that we also need some kind of dynamic code analysis (fuzzing), and I am not sure how other tools are solving that.

**Comment by rmohr** [comment]
@caniszczyk what are other golang projects using for dynamic code analysis? I see that many have 100% on the badge, but I don't see what they do in this area.
