### ISSUE TITLE
Add FOSSA license scanning

### ISSUE THREAD

**Issue by caniszczyk** [kubevirt/kubevirt#2680]
Add FOSSA license scanning to the build: https://fossa.io

CNCF has a license.

**Comment by fabiand** [comment]
@dhiller I suppose this is also something for you

**Comment by dhiller** [comment]
@caniszczyk hm, OK, I thought I was supposed to enable this for all repos under the KubeVirt org, like it was requested to enable DCO?

I have imported the kubevirt/kubevirt already, will be starting to sort out the issues there soon.

**Comment by dhiller** [comment]
FIxed with kubevirt/kubevirt#2698
