### ISSUE TITLE
Issue with LVM during boot

### ISSUE THREAD

**Issue by nmsnitin** [kubevirt/kubevirt#2685]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
We are trying to create a VM using Kubevirt but that VM stuck in the booting process for a while and showing "Volume group "system" not found" on boot prompt.  It seems issue with LVMs. We need some LVMs snipped it attached in last.
While we are able to create the same using Qemu commands successfully.
(qemu-system-x86_64 -m 4092 -smp 2 -hda stn-vmfx2-disk1.qcow2 -enable-kvm -name qemu-vm-vmdk)
**What you expected to happen**:
 
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
The image is based on OpenSuse.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.15.0
- Kubernetes version (use `kubectl version`):v1.15.3
- VM or VMI specifications:
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): Ubuntu 16.04.2 LTS
- Kernel (e.g. `uname -a`):Linux ubuntu 4.4.0-62-generic #83-Ubuntu SMP Wed Jan 18 14:10:15 UTC 2017 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Error Snippet of booting process**
Creating device nodes with udev
[    1.762129] udev[93]: starting version 166
mount: devpts already mounted or /dev/pts busy
mount: according to mtab, devpts is already mounted on /dev/pts
Boot logging started on /dev/ttyS0(/dev/console) at Tue Sep 10 16:55:09 2019
[    1.956515] md: linear personality registered for level -1
  Volume group "system" not found
  Volume group "system" not found
  Volume group "system" not found
  Volume group "system" not found
Waiting for device /dev/system/root to appear:   Reading all physical volumes.  This may take a while...
  No volume groups found
  Volume group "system" not found
  Volume group "system" not found
  Volume group "system" not found
  Reading all physical volumes.  This may take a while...
  No volume groups found
  Volume group "system" not found
  Volume group "system" not found
  Volume group "system" not found
  Reading all physical volumes.  This may take a while...
  No volume groups found
  Volume group "system" not found
  Volume group "system" not found
  Volume group "system" not found
  Reading all physical volumes.  This may take a while...
  No volume groups found

#####
**Required volumes on the VMs**
_lvm> pvdisplay
  --- Physical volume ---
  PV Name               /dev/sda2
  VG Name               system
  PV Size               12.39 GiB / not usable 2.81 MiB
  Allocatable           yes
  PE Size               4.00 MiB
  Total PE              3170
  Free PE               74
  Allocated PE          3096
  PV UUID               qarO39-B8jv-2DIM-J2bw-HAnI-8Kgv-4opDTd

  --- Physical volume ---
  PV Name               /dev/sda3
  VG Name               fx
  PV Size               106.36 GiB / not usable 1.34 MiB
  Allocatable           yes (but full)
  PE Size               4.00 MiB
  Total PE              27228
  Free PE               0
  Allocated PE          27228
  PV UUID               azuadc-QYGf-n3N4-HxRm-kjCi-oIdm-iLZRWc

lvm> lvdisplay
  --- Logical volume ---
  LV Name                /dev/system/home
  VG Name                system
  LV UUID                zIOLIn-soiL-54GR-msCe-EXHC-ihTV-eiCTlt
  LV Write Access        read/write
  LV Status              available
  

**POD Yaml**
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: vm-fx2
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: dfx2
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: rootfs
          - disk:
              bus: virtio
            name: cloudinit
          interfaces:
          - name: default
            bridge: {}
        resources:
          requests:
            memory: 4048M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: rootfs
          containerDisk:
            image: stn-vmfx2-disk1-vmdk
        - name: cloudinit
          cloudInitNoCloud:
            userData: |
              #!/bin/bash

####
**Pod and VM in the running state.**
**Kubectl describe VM <vmname>  output**
Status:
  Created:  true
  Ready:    true
Events:
  Type    Reason            Age   From                       Message
  ----    ------            ----  ----                       -------
  Normal  SuccessfulCreate  25m   virtualmachine-controller  Created virtual machine: vm-fx2

**Comment by cynepco3hahue** [comment]
@nmsnitin I can see you are using `containerDisk` does it on purpose because it looks like you want to use `persistentVolumeClaim`?

**Comment by nmsnitin** [comment]
@cynepco3hahue ,  I have a qcow2 image on my host machine. How can I use same image to boot the VM using PVC.

**Comment by nmsnitin** [comment]
@cynepco3hahue, 
I have tried PV and PVC to resolve the issue but the issue is the same with our image that required LVM.

I have a small query here, my application VM requires two physical disk  **/dev/sda2 and /dev/sda3**
to create the Volume Groups (VGs) and Logical Volume (LVs) over it as part of LVM.  I tried HostDisk, emptydisk and PVC as well to provide disks to the VM but it attaches as  **vda**. Is there any way that those will be attached as **/dev/sda2 and /dev/sda3**.

**Comment by cynepco3hahue** [comment]
IIRC you need to change the bus type
```
...
domain:
        devices:
          disks:
          - disk:
              bus: virtio-scsi
            name: pvcdisk1
...
```
but to be honest I can not find any example with it, so I just it will work for you

**Comment by nmsnitin** [comment]
@cynepco3hahue ,  Thanks.. Yes I can see the the sda as a disk in the VM, but it is not mounted anywhere. I need to create a partition like /dev/sda1.  Can I provide such information using VM yaml.

root@vm13:~# lsblk
NAME   MAJ:MIN RM  SIZE RO TYPE MOUNTPOINT
**sda      8:0    0   10G  0 disk**
vda    253:0    0  2.2G  0 disk
`-vda1 253:1    0  2.2G  0 part /
vdb    253:16   0  366K  0 disk

root@vm13:~# df -h
Filesystem      Size  Used Avail Use% Mounted on
udev            945M     0  945M   0% /dev
tmpfs           191M  3.0M  188M   2% /run
/dev/vda1       2.1G  862M  1.3G  42% /
tmpfs           954M     0  954M   0% /dev/shm
tmpfs           5.0M     0  5.0M   0% /run/lock
tmpfs           954M     0  954M   0% /sys/fs/cgroup
tmpfs           191M     0  191M   0% /run/user/0

**Comment by cynepco3hahue** [comment]
Can you please describe what are you trying to achieve? IIUC you have some pre-provisioned image `stn-vmfx2-disk1.qcow2` that do you want to use for the VMI start, do you want to run it as stateless or stateful VM?

**Comment by nmsnitin** [comment]
Actually my application running inside VM is looking for a partition mounted on **/dev/sda1.** 
I am just trying to provide an emptyDisk or PVC that mounted as /dev/sda1.

**Comment by cynepco3hahue** [comment]
@nmsnitin Thanks for the explanation, you can try to configure mounts via cloud-init, in general, you can pass any bash script that you want to it - https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/startup-scripts.html.

**Comment by nmsnitin** [comment]
@cynepco3hahue Thanks for the help. One last question is there any impact on the performance if I use bus as "sata" instead of the "virtio" for the containerDisk (rootfs).

**Comment by nmsnitin** [comment]
@cynepco3hahue  .. Thanks a lot for your great help. I am able to solve the issue.
I am closing this issue.

**Comment by cynepco3hahue** [comment]
@nmsnitin If it does not hard, can you specify in two words how did you solved it?
Just in case if we will have similar case in the future:)

**Comment by nmsnitin** [comment]
We have an application image that required a full virtualized environment at OS level, it's OS looking for **/dev/sda** to create and mount the root and the other file system.
While we are using **virtio driver** to launch the VM that is creating a paravirtualization environment by creating /dev/vda disk.
As suggested we have changed the driver to the **sata** type that has created required /dev/sda disk and it has resolved the issue.

**Comment by cynepco3hahue** [comment]
Great, thanks!
