### ISSUE TITLE
V0.21.0 breaks with non open shift deployment

### ISSUE THREAD

**Issue by mjschmidt** [kubevirt/kubevirt#2688]
**Is this a BUG REPORT or FEATURE REQUEST?**:
There needs to be a way for the operator to not break if the openshift metrics ns isn't there. Maybe making metrics a configurable yaml file element would be a good idea? 
> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cynepco3hahue** [comment]
Can you please provide logs from the `virt-operator`?

**Comment by mjschmidt** [comment]
Tomorrow I can spin up a quick minikube and get you some logs. Its complaining about looking for openshift metrics namespace.

**Comment by slintes** [comment]
Artyom Lukianov <notifications@github.com> schrieb am Do., 12. Sept. 2019,
13:37:

> How we will know the ns, under the OpenShift we can now that it under the
> specific ns, in case of user-configured environment it can be problematic,
> we can expose some variable under the KubeVirt config, the question if we
> want to do it?
>

There is a property on the KubeVirt CRD already

**Comment by rmohr** [comment]
Maybe we should fall just fall back to the install namespace if we are not on openshift?

**Comment by slintes** [comment]
Not sure what the common setup of Prometheus is. If it usually looks in all
namespaces for ServiceMonitor CRs, it might make sense. If not, probably
not. IMHO we are fine already if we just give a warning in case the
default/configured ns doesn't exist, instead of failing the deployment.

Roman Mohr <notifications@github.com> schrieb am Fr., 13. Sept. 2019, 09:43:

**Comment by mjschmidt** [comment]
Agreed, throwing a warning would work fine as the shortest possible way forward.

Creating a namespace in my opinion would go down the road of causing all types of problems for non OCP users

**Comment by mjschmidt** [comment]
Thanks for working to make the fix by the way!

**Comment by mjschmidt** [comment]
Thanks all!
