### ISSUE TITLE
haproxy fails to forward to virt-api in some cases

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#27]
There are currently two scenarios where haproxy stops forwarding to virt-api:

 * virt-api pod not yet up (and service not ready) and you want to access it
 * kubernetes dns server is not reachable when we first try to access virt-api

If one of these situations happens you will get a "503" from haproxy and it will not retry.
We should probably take this to the haproxy mailing list too. I would expect haproxy to retry later on instead of stopping to work forever.

**Comment by fabiand** [comment]
Could we add a little wrapper which retries our important urls - and if it fails, then the container fails, then kubelet will restart it.

Thoughts?

**Comment by rmohr** [comment]
http://discourse.haproxy.org/t/resolvers-inside-kubernetes/916

**Comment by rmohr** [comment]
@fabiand we can also do something like this: https://github.com/kubernetes/contrib/blob/master/ingress/controllers/README.md

with our haproxy. Basically when virt-api-server gets redeployed we restart haproxy ....

**Comment by rmohr** [comment]
It does not seem to happen anymore. Closing it.
