### ISSUE TITLE
Domain gets tainted due to custom guest agent command

### ISSUE THREAD

**Issue by ahadas** [kubevirt/kubevirt#2704]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Noticed the following error in the log:
`Domain id=1 name='kubevirt-test-default_testvmixbcjc6f7szp4s6xq9vc987pqtz5s79gvsrfdts4gspzt4fgf' uuid=273534ef-9541-4036-a019-bd2b177926c1 is tainted: custom-ga-command`
It happened several time during migration tests, e.g., [here](https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2682/pull-kubevirt-e2e-k8s-1.14.6/1171728963605630976/artifacts/pods/2_kubevirt-test-default_virt-launcher-testvmixbcjc6f7szp4s6xq9vc987pqtz5s79gvsrfdtgtz8n-compute.log).

/kind bug

**What happened**:
Migration failed

**What you expected to happen**:
Migration to succees

**How to reproduce it (as minimally and precisely as possible)**:
Rarely

**Anything else we need to know?**:
Not sure this issue is the reason for the migration to fail. The error of writing the log that follows the aforementioned error was fixed in upstream qemu.

**Comment by rmohr** [comment]
@ahadas It only says "Warning". Is this really the cause for the failed migration?

**Comment by ahadas** [comment]
> @ahadas It only says "Warning". Is this really the cause for the failed migration?

As far as I remember every time that log appeared the migration failed, so I assumed it is related but I don't really know.
