### ISSUE TITLE
Support qcow2 for hostDisk

### ISSUE THREAD

**Issue by rudicio** [kubevirt/kubevirt#2705]
Kubevirt does not support qcow2 when loading a hostDisk (always shows in qemu as format=raw)

This actually looks like a much bigger bug - I cannot get a hostDisk to load as a SATA device either.

**Comment by rmohr** [comment]
> Kubevirt does not support qcow2 when loading a hostDisk (always shows in qemu as format=raw)

Yes that is right now not supported.

> This actually looks like a much bigger bug - I cannot get a hostDisk to load as a SATA device either.

/cc @petrkotas could you have a look?

Maybe we can untangle the issue into two separate ones, @rudicio? A bug report and an enhancement.

**Comment by petrkotas** [comment]
Hi @rmohr and @rudicio.

@rudicio please, I second Roman with splitting the issue. It will be much easier to plan and work on, when we know what is the issue you are bugged and what feature you would like to use.

**Comment by petrkotas** [comment]
Hi @rudicio I have checked the functionality and it seems to work. Would you please provide more information about your setup?
We need:

1. cluster state: `kubectl get pods --all-namespaces`
2. logs for virt-launcher, virt-handler, virt-controller
3. logs for any failed pods related to kubevirt namespace

Thank you for reporting an issue.
