### ISSUE TITLE
[question] does kubevirt has plan to support baremetal? 

### ISSUE THREAD

**Issue by jichenjc** [kubevirt/kubevirt#2709]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
To my understanding, kubevirt is a thing that interact with libvirt to boot vms, do we have a roadmap that we will use something like baremetal such as openstack Ironic to manage baremetal ? Thanks
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cynepco3hahue** [comment]
@jichenjc Can you please describe your use case?
In general, KubeVirt should only manage VM's and not bare metal nodes, for this purpose we have metal3 repository, see https://github.com/metal3-io/metal3-docs/pull/48/files for more information.

**Comment by jichenjc** [comment]
yes, that's my understanding by now, we need be sure on the scope of kubevirt and out-of scope of kubevirt, so just to confirm, the metal 3 and kubevirt are different repo and no interaction technically ,correct? @cynepco3hahue 

by the way, do we have any document that describe whether other hypervirsor such as vmware/xen/ etc will be a to do item?

**Comment by rmohr** [comment]
> yes, that's my understanding by now, we need be sure on the scope of kubevirt and out-of scope of kubevirt, so just to confirm, the metal 3 and kubevirt are different repo and no interaction technically ,correct? @cynepco3hahue

Yes, they are independent. You can "somehow" (via metal3, kubeadm, ...) install a kubernetes cluster on bare-metal. Once you have the cluster, you can deploy kubevirt. Depending on your cluster-version kubevirt may require some beta features (so should be enabled by default already) from kubernetes itself.

> 
> by the way, do we have any document that describe whether other hypervirsor such as vmware/xen/ etc will be a to do item?

There are currently no plans to support other hypervisors.

**Comment by jichenjc** [comment]
thanks for the information, let's close this , appreciate :)
