### ISSUE TITLE
Kubevirt Operator fails to determine cluster type - kubeadm 1.15

### ISSUE THREAD

**Issue by j-griffith** [kubevirt/kubevirt#2720]
/kind bug

**What happened**:

Attempted to build and deploy latest kubevirt to an external cluster (KUBEVIRT_PROVIDER=externa; DOCKER_PREFIX=xxxx) and when the operator is deployed it starts up but then errors out , failing to determine cluster type:

`ERROR: logging before flag.Parse: I0921 14:33:17.102400       1 application.go:164] Error determining cluster type: Get https://10.96.0.1:443/api?timeout=32s: dial tcp 10.96.0.1:443: i/o timeout`

I've also tried just using the latest release (v0.21.0) and i'm seeing the same error.

**What you expected to happen**:

Operator to run and deploy a functional kubevirt 

**How to reproduce it (as minimally and precisely as possible)**:

Create an external kubeadm cluster (currently using 1.15); and attempt to deploy kubevirt v0.21.0 using the following commands:

```
export KUBEVIRT_VERSION=$(curl -s https://api.github.com/repos/kubevirt/kubevirt/releases|grep tag_name|sort -V | tail -1 | awk -F':' '{print $2}' | sed 's/,//' | xargs | cut -d'-' -f1)
  
echo $KUBEVIRT_VERSION

kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${KUBEVIRT_VERSION}/kubevirt-operator.yaml

```
**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
Tried building from master as well as v0.21.0

- Kubernetes version (use `kubectl version`):
Kubeadm 1.15

- VM or VMI specifications:
Didn't make it that far

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
Linux buster-1 4.19.0-6-amd64 #1 SMP Debian 4.19.67-2 (2019-08-28) x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by SchSeba** [comment]
Hi @j-griffith can you please run `kubectl get po --all-namespaces` ?

**Comment by j-griffith** [comment]
@SchSeba sure, here's the output

```
jdg@buster-1:~$ kubectl get po -A
NAMESPACE     NAME                               READY   STATUS             RESTARTS   AGE
kube-system   coredns-5c98db65d4-7wmkg           1/1     Running            3          5d20h
kube-system   coredns-5c98db65d4-rnndw           1/1     Running            3          5d20h
kube-system   etcd-buster-1                      1/1     Running            1          5d20h
kube-system   kube-apiserver-buster-1            1/1     Running            2          5d20h
kube-system   kube-controller-manager-buster-1   1/1     Running            1          5d20h
kube-system   kube-flannel-ds-amd64-9bddm        1/1     Running            1          5d20h
kube-system   kube-flannel-ds-amd64-wqkxj        1/1     Running            1          5d20h
kube-system   kube-flannel-ds-amd64-ztncj        1/1     Running            1          5d20h
kube-system   kube-proxy-4z65w                   1/1     Running            1          5d20h
kube-system   kube-proxy-7d4ws                   1/1     Running            1          5d20h
kube-system   kube-proxy-p7b2z                   1/1     Running            1          5d20h
kube-system   kube-scheduler-buster-1            1/1     Running            1          5d20h
kubevirt      virt-operator-5757956476-4zl8h     0/1     CrashLoopBackOff   41         24h
kubevirt      virt-operator-5757956476-fddgv     0/1     CrashLoopBackOff   44         24h
```

**Comment by j-griffith** [comment]
@SchSeba it looks like @stu-gott may have already fixed this here:  https://github.com/kubevirt/kubevirt/commits/master/pkg/virt-operator/util/client.go

I'll build a new version and test is today and update here accordingly.

**Comment by j-griffith** [comment]
Gahh, this is a config issue on my side with DNS.  Sorry for the noise.
