### ISSUE TITLE
Not able to access K8S pod service(nginx) from VM able to ping pod network and nginx pod

### ISSUE THREAD

**Issue by chandrajr** [kubevirt/kubevirt#2721]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
Not able to access K8S service from kubevirt VM 

**What you expected to happen**:
Should be able to access nginx pod service 
$ curl 10.98.102.246:32100
<!DOCTYPE html>
<html>
<head>
<title>Welcome to nginx!</title>
<style>
    body {
        width: 35em;
        margin: 0 auto;
        font-family: Tahoma, Verdana, Arial, sans-serif;
    }
</style>
</head>
<body>
<h1>Welcome to nginx!</h1>
<p>If you see this page, the nginx web server is successfully installed and
working. Further configuration is required.</p>

<p>For online documentation and support please refer to
<a href="http://nginx.org/">nginx.org</a>.<br/>
Commercial support is available at
<a href="http://nginx.com/">nginx.com</a>.</p>

<p><em>Thank you for using nginx.</em></p>
</body>
</html>
$ 

**How to reproduce it (as minimally and precisely as possible)**:

curl nginx service from VM
# curl 10.98.102.246:32100
curl: (7) Couldn't connect to server

ping nginx pod from VM 
# ping -c 1 10.244.1.65
PING 10.244.1.65 (10.244.1.65) 56(84) bytes of data.
64 bytes from 10.244.1.65: icmp_seq=1 ttl=255 time=0.298 ms 
--- 10.244.1.65 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms

**Anything else we need to know?**:
$ kubectl get svc | grep nginx
nginx                              NodePort    10.98.102.246   <none>        32100:30699/TCP   3d8h

$ kubectl get pods -o wide | grep nginx
nginx-554b9c67f9-4b59t             1/1     Running   0          6d6h   10.244.1.65   
nginx-554b9c67f9-dbdjp             1/1     Running   0          6d6h   10.244.1.66   
nginx-554b9c67f9-t5hqd             1/1     Running   0          6d6h   10.244.1.67 

**Environment**:
- KubeVirt version (use `virtctl version`):
$ ./virtctl version
Client Version: version.Info{GitVersion:"v0.17.0", GitCommit:"c0f960702dce718419a767f3913669f539229ff0", GitTreeState:"clean", BuildDate:"2019-05-05T08:09:14Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.21.0", GitCommit:"e220f16d7a2aae7295199bbbc3594a5b50b7a3f4", GitTreeState:"clean", BuildDate:"2019-09-09T08:09:15Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.2", GitCommit:"f6278300bebbb750328ac16ee6dd3aa7d3549568", GitTreeState:"clean", BuildDate:"2019-08-05T09:23:26Z", GoVersion:"go1.12.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.3", GitCommit:"2d3c76f9091b6bec110a5e63777c332469e0cba2", GitTreeState:"clean", BuildDate:"2019-08-19T11:05:50Z", GoVersion:"go1.12.9", Compiler:"gc", Platform:"linux/amd64"}
- VM or VMI specifications:
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: myvm-new
spec:
  domain:
    resources:
      limits:
        memory: "4096Mi"
        cpu: "2"
      requests:
        memory: "4096Mi"
        cpu: "2"
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      interfaces:
      - name: mngmt
        bridge: {}
      - name: external
        bridge: {}
      - name: default
        bridge: {}
  volumes:
  - name: containerdisk
    containerDisk:
      image: vmidisks/myvm:14.1.0.3
  networks:
  - name: mngmt
    multus:
      networkName: myvm-mgmt
  - name: external
    multus:
      networkName: myvm-external
  - name: default
    pod: {}

- Cloud provider or hardware configuration:
Baremetal INTEL VMX
- OS (e.g. from /etc/os-release):
CentOS Linux release 7.6.1810
- Kernel (e.g. `uname -a`):
uname -a
Linux my-machine.com 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by SchSeba** [comment]
Hi @chandrajr thanks for reporting this.

can you please run `ip route` from inside the vm and paste the output here?

**Comment by chandrajr** [comment]
This issue resolved .
Issue with Networking where i was using multus 
As it expects default network for pod subnet

**Comment by slintes** [comment]
Thanks for the follow up! :slightly_smiling_face: 

/close
