### ISSUE TITLE
Starting a domain is sometimes slow due to not being able to send an "audit message"

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#2722]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind enhancement

**What happened**:

This message occurs over and over again:

```
{"component":"virt-launcher","level":"warning","msg":"Failed to send audit message virt=kvm resrc=vcpu reason=start vm=\"kubevirt-test-default_testvmipz5tv2j7gzc78tvcq7wfk2zzxk8rkj4jxb9b8b77rxqjmn4r\" uuid=8d7a4ace-3751-438c-b7e9-4c4370630cf9 old-vcpu=0 new-vcpu=1: Permission denied","pos":"virAuditSend:141","subcomponent":"libvirt","thread":"30","timestamp":"2019-09-23T03:53:50.738000Z"}
```

Finally sending the audit message works and the VMI is started. However tests are likely failing then because of timeouts.

Job: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2717/pull-kubevirt-e2e-os-3.11.0/1175919830482554880
Log: https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2717/pull-kubevirt-e2e-os-3.11.0/1175919830482554880/artifacts/pods/2_kubevirt-test-default_virt-launcher-testvmipz5tv2j7gzc78tvcq7wfk2zzxk8rkj4jxb9b8n728v-compute.log

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
Related to #2566

**Comment by mlsorensen** [comment]
I'm playing around with version 0.21.0 in a lab and seeing the same.

```
{"component":"virt-launcher","level":"warning","msg":"Failed to send audit message virt=kvm resrc=chardev reason=start vm=\"973531624_vm-cirros\" uuid=0d2a2043-41c0-59c3-9b17-025022203668 old-chardev=\"?\" new-chardev=\"/var/run/kubevirt-private/465ff778-e16d-11e9-bfa8-040973e15fcc/virt-serial0\": Permission denied","pos":"virAuditSend:141","subcomponent":"libvirt","thread":"74","timestamp":"2019-09-27T21:25:32.416000Z"}
```

```
> Client Version: version.Info{GitVersion:"v0.21.0", GitCommit:"e220f16d7a2aae7295199bbbc3594a5b50b7a3f4", GitTreeState:"clean", BuildDate:"2019-09-07T07:33:17Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"darwin/amd64"}
> Server Version: version.Info{GitVersion:"v0.21.0", GitCommit:"e220f16d7a2aae7295199bbbc3594a5b50b7a3f4", GitTreeState:"clean", BuildDate:"2019-09-09T08:09:15Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```

I'm also unable to get t console, not sure if that's related. Both console and vnc just sort of hang as though they're connected but getting no data. Still looking into it.

 ```
virtctl vnc vm-cirros
{"component":"virtctl","level":"info","msg":"connection timeout: 1m0s","pos":"vnc.go:137","timestamp":"2019-09-27T15:25:45.799369Z"}
{"component":"virtctl","level":"info","msg":"remote-viewer connected in 95.919718ms","pos":"vnc.go:148","timestamp":"2019-09-27T15:25:45.895291Z"}
```

```
./virtctl console vm-cirros -v4
Successfully connected to vm-cirros console. The escape sequence is ^]

You were disconnected from the console. This has one of the following reasons:
 - another user connected to the console of the target vm
 - network issues
websocket: close 1006 (abnormal closure): unexpected EOF
```

**Comment by rmohr** [comment]
> I'm also unable to get t console, not sure if that's related. Both console and vnc just sort of hang as though they're connected but getting no data. Still looking into it.

@mlsorensen that looks similar to https://bugzilla.redhat.com/show_bug.cgi?id=1753606. However, I was never able to reproduce it with `virtctl`, only through the openshift console.

@ahadas that looks now very much like #2519 introduced an issue. We should probably open a github issue here too and investigate. Can you do that?

**Comment by rmohr** [comment]
> I'm playing around with version 0.21.0 in a lab and seeing the same.

@nertpinx @andreabolognani do you have any idea what could cause this? @mlsorensen do you have `selinux` enabled or permissive?

**Comment by rmohr** [comment]
@mlsorensen btw. Which vnc viewer do you use?

**Comment by andreabolognani** [comment]
> @nertpinx @andreabolognani do you have any idea what could cause this?

Doesn't ring any bells, sorry :(

**Comment by nertpinx** [comment]
On Mon, Sep 30, 2019 at 03:40:05AM -0700, Andrea Bolognani wrote:
>> @nertpinx @andreabolognani do you have any idea what could cause this?
>
>Doesn't ring any bells, sorry :(
>

Neither with me, I'm not familiar with libaudit at all.

**Comment by mlsorensen** [comment]
I've used all three VNC options for MacOS, Normally I use TigerVNC but I've also got the others intalled and tried them as well.

I do have selinux enforcing in this environment.

**Comment by rmohr** [comment]
Asked on libvirt-users if someone has an idea: https://www.redhat.com/archives/libvirt-users/2019-October/msg00029.html

**Comment by rmohr** [comment]
Here some a job which collected the audit log of nodes: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2869/pull-kubevirt-e2e-os-3.11.0-crio/1192000670023028736

There the second failed test can't use `/dev/tun`, and then libvirt wants to write to the audit log and is gets a "permission denied". I can't see anything stringe in https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2869/pull-kubevirt-e2e-os-3.11.0-crio/1192000670023028736/artifacts/nodes/2_auditlog_node02.log. 

So it looks a little bit  like it is not selinux related.
