### ISSUE TITLE
I want to add public ip and internal ip for the vm by cni . what should i do  ?whether kubevirt support  cni?Is there any Introduction?

### ISSUE THREAD

**Issue by zhipengzuo** [kubevirt/kubevirt#2730]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
Hi @zhipengzuo, we have our user-docs here: https://kubevirt.io/user-guide/docs/latest/welcome/index.html. By default any VMI which you create is connected (via CNI) to the pod network. The IP which we get assigned from CNI is offered to the VMI via DHCP. So as long as you configure your interfaces inside the VMI to use DHCP (either default anyway, or use cloud-init), you will see inside your VMI the correct IP.

We also support multus, where different CNI plugins can provide multiple IPs, which are then all offered to the VMI via DHCP. See for instance here: https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/interfaces-and-networks.html#multus.

**Comment by zhipengzuo** [comment]
> Hi @zhipengzuo, we have our user-docs here: https://kubevirt.io/user-guide/docs/latest/welcome/index.html. By default any VMI which you create is connected (via CNI) to the pod network. The IP which we get assigned from CNI is offered to the VMI via DHCP. So as long as you configure your interfaces inside the VMI to use DHCP (either default anyway, or use cloud-init), you will see inside your VMI the correct IP.
> 
> We also support multus, where different CNI plugins can provide multiple IPs, which are then all offered to the VMI via DHCP. See for instance here: https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/interfaces-and-networks.html#multus.

thanks for you reply .I also want to know  whether kubevirt support containerd .I found that kubevirt supports docker and runv .I want to know more about kubevirt containerd .

When I apply kubevirt-operator.yaml with containerd ,some error like
 Error: failed to create containerd container: error unpacking image: wrong diff id calculated on extraction "sha256:c72e9cb60a9daecfd6504f500a73292ed469e575efc1587e938fd614295adcd1"

**Comment by rmohr** [comment]
We have no code in kubevirt which depends on a specific container runtime. This looks like a containerd issue.

**Comment by zhipengzuo** [comment]
thanks
