### ISSUE TITLE
Add kernel provision through command line

### ISSUE THREAD

**Issue by xprxprx** [kubevirt/kubevirt#2741]
FEATURE REQUEST

/kind enhancement

We are testing kubevirt and it seems to be great, however, we miss the feature of pass a kernel parameter to provide by command line a different kernel than it has in the image.

As an example in the case of kvm the command line will be:

qemu-system-x86_64 -kernel "custom_kernel_provided".

Thank you very much.
Xavi.

**Comment by fabiand** [comment]
@xprxprx how would you expect to provide the kernel?
Should it be on a PVC in a containerDIsk or somewhere else?
How would you expect to specify the initrd/cmdline?

**Comment by xprxprx** [comment]
Hi @fabiand,

maybe I can expose a bit deeper what are we trying to get with this feature. We are partners of the European Project [Unicore](http://unicore-project.eu/). In this project we are developing the unikraft tool which makes easier to create a Unikernel from a typical application. Also we want to integrate unikernels on the most popular orquestrator like OpenNebula, OpenStack and Kubernetes. As unikernels will use kvm to run, we thought Kubevirt fits the best on what we want to do to run them on Kubernetes. By now we achieved to run unikernels with OpeNebula just by providing the -kernel parameter without a disk, because the unikernel has built with all modules and libraries needed to run. So by now we just need to boot the kernel from kubernetes via Kubevirt without initrd nor disk. 

Regarding on how we expect to provide the kernel, we are open and we don't have restrictions on this. Maybe the easiest way is to embed the kernel inside a qcow2 file.

**Comment by sresthas** [comment]
I would love to work on this project as a part of communitybridge mentorship. I have worked with virtualisation in GNOME Boxes. How do I contact the mentor for a quick chat?

**Comment by Dhiraj240** [comment]
@xprxprx   I have applied on community bridge and messaged you on slack for more information. You can check my portfolio here at https://dhiraj240.github.io/

**Comment by lucheng0127** [comment]
@xprxprx I got the same situation, I wish to launch a kernel without disk, just add -kernel when launch by qemu-kvm.
have you been slove it in kubevirt?

**Comment by xpivarc** [comment]
https://kubevirt.io/user-guide/virtual_machines/boot_from_external_source/

**Comment by lucheng0127** [comment]
> https://kubevirt.io/user-guide/virtual_machines/boot_from_external_source/

Thx for reply, i saw this guide, but this something confuse me about how to launch it
if i want to launch a vm from a kernel binary file, without initramfs and disk,
then i just place my kernel binary file into physical hyper, then set kernelPath to kernel file
without initrdPath, and just a empty volumecontainerdisk image? Im not sure about it
@xpivarc could you got my confuse, thx for reply

**Comment by lucheng0127** [comment]
> https://kubevirt.io/user-guide/virtual_machines/boot_from_external_source/

THX, it works

**Comment by xpivarc** [comment]
> > https://kubevirt.io/user-guide/virtual_machines/boot_from_external_source/
> 
> THX, it works

Glad to hear that.
