### ISSUE TITLE
Make controller threads configurable on the operator CR

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#2746]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind enhancement

**What happened**:

Some users fine-tune the controller thread count. See #2648. Using manifests is already deprecated. We should not forget to move these options  to the operator install.

**What you expected to happen**:

That I can either set these specific options on the CR, or that we introduce a generic mapping between component commandline arguments and the CR, so that we don't have to map each one individually.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@visheshtanksale @shengnuo FYI
/cc @slintes @vladikr

**Comment by ashleyschuett** [comment]
I'm picking this issue up to work on. I'm assuming that if the flag is set as well as having the same configuration value set on the CR the value in the CR should take precedence?

**Comment by fabiand** [comment]
@ashleyschuett +1

Please self-assign by using simply commenting with /assign
