### ISSUE TITLE
Could  kubevirt offer image build by Dockefile ? containerd may not support images build by bazel.

### ISSUE THREAD

**Issue by zhipengzuo** [kubevirt/kubevirt#2748]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
crictl pull index.docker.io/kubevirt/virt-handler@sha256:74463ee0d468203d7319099650d8590bbbb8af4ab67315f7a27b205a2885e8c2
FATA[0015] pulling image failed: rpc error: code = Unknown desc = failed to pull and unpack image "docker.io/kubevirt/virt-handler@sha256:74463ee0d468203d7319099650d8590bbbb8af4ab67315f7a27b205a2885e8c2": failed to unpack image on snapshotter devmapper: wrong diff id calculated on extraction "sha256:556b5e866fb438fb624f21d7f1f9587227c580cdc45b633095111ad8cdb05fd8"
**What you expected to happen**:
when i use docker pull ,it's ok
docker pull index.docker.io/kubevirt/virt-handler@sha256:74463ee0d468203d7319099650d8590bbbb8af4ab67315f7a27b205a2885e8c2
sha256:74463ee0d468203d7319099650d8590bbbb8af4ab67315f7a27b205a2885e8c2: Pulling from kubevirt/virt-handler
Digest: sha256:74463ee0d468203d7319099650d8590bbbb8af4ab67315f7a27b205a2885e8c2
Status: Image is up to date for kubevirt/virt-handler@sha256:74463ee0d468203d7319099650d8590bbbb8af4ab67315f7a27b205a2885e8c2
docker.io/kubevirt/virt-handler@sha256:74463ee0d468203d7319099650d8590bbbb8af4ab67315f7a27b205a2885e8c2
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cynepco3hahue** [comment]
@zhipengzuo hm it works for `podman` and `docker`, did you try to open an issue under the https://github.com/kubernetes-sigs/cri-tools?

**Comment by zhipengzuo** [comment]
> @zhipengzuo hm it works for `podman` and `docker`, did you try to open an issue under the https://github.com/kubernetes-sigs/cri-tools?

thanks . I am going to try to translate the bazel format to Dockfile

**Comment by cynepco3hahue** [comment]
if you will check the history you can find that we used Dockerfile before, but it will include a lot of changes.
Do understand why crictl fails to pull the image?

**Comment by zhipengzuo** [comment]
> if you will check the history you can find that we used Dockerfile before, but it will include a lot of changes.
> Do understand why crictl fails to pull the image?

i think the containerd will calculated the id and compare with image's sha256. different way to build may 
produce different  file 。so the diff id is different. 

I am reading the BUILD.bazel. i want to know can i build it in my env ? can i get  all the dependent file from the internet ?thanks

**Comment by rmohr** [comment]
@zhipengzuo we right now produce docker v2.2 images. I would be surprised if containerd can't read docker own v2.2 format. Can you ensure that your containerd is up-to-date and if it is, open an issue on the containerd project?

**Comment by zhipengzuo** [comment]
> @zhipengzuo we right now produce docker v2.2 images. I would be surprised if containerd can't read docker own v2.2 format. Can you ensure that your containerd is up-to-date and if it is, open an issue on the containerd project?

i will try . thanks

**Comment by rmohr** [comment]
Oh wait, now I see that you use `cri-tools`. That only support OCI containers, not v2.2. You can configure bazel to produce OCI images instead of v2.2 (we build v2.2 because it is in most cases still more broadly adopted), let me look that up.

**Comment by rmohr** [comment]
Checking this, it looks like you would only have to exchange the `container_push` rules with `oci_push` ruiles in the root BUILD.bazel: https://github.com/bazelbuild/rules_docker#basic-rules

**Comment by zhipengzuo** [comment]
> container_push
thank you so much for your kindly reply. i will try .thanks.
