### ISSUE TITLE
panic: ValidatingAdmissionWebhook [virt-api-validator] is already registered using services endpoints in a different namespace. Existing webhook registration must be deleted before virt-api can proceed.

### ISSUE THREAD

**Issue by zhipengzuo** [kubevirt/kubevirt#2749]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
when i create virt-api ,that's the log .it seems something that are not cleaned up.how can i clean it . By  the way  i also want to know how to get root password for a vm.thanks.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by zhipengzuo** [comment]
error: unable to retrieve the complete list of server APIs: subresources.kubevirt.io/v1alpha2: the server is currently unable to handle the request, subresources.kubevirt.io/v1alpha3: the server is currently unable to handle the request

**Comment by slintes** [comment]
Hey. Let's try to sort things out...

1. > when i create virt-api

What exactly are you trying to do?

2. >  something that are not cleaned up

Did you uninstall KubeVirt? How? What version?

3. > how to get root password for a vm

Which VM?

4. >  list of server APIs: subresources.kubevirt.io/v1alpha2

v1alpha2 is really old... Can you provide some more context on your env please?

**Comment by zhipengzuo** [comment]
> Hey. Let's try to sort things out...
> 
> 1. > when i create virt-api
> 
> What exactly are you trying to do?
> 
> 1. > something that are not cleaned up
> 
> Did you uninstall KubeVirt? How? What version?
> 
> 1. > how to get root password for a vm
> 
> Which VM?
> 
> 1. > list of server APIs: subresources.kubevirt.io/v1alpha2
> 
> v1alpha2 is really old... Can you provide some more context on your env please?

sorry,i will  be careful next time .thanks for your reply.some env list:
k8s 1.3.4
centos 7.3
kubevirt 0.14

**Comment by slintes** [comment]
Oh wow, that's all quite old. I'm tempted to recommend to set up a new server :wink: 
However, we have a PR open for the user guide with a script which should remove everything. I hope this helps :slightly_smiling_face: 

https://github.com/kubevirt/user-guide/pull/287/files

**Comment by zhipengzuo** [comment]
> Oh wow, that's all quite old. I'm tempted to recommend to set up a new server 😉
> However, we have a PR open for the user guide with a script which should remove everything. I hope this helps 🙂
> 
> https://github.com/kubevirt/user-guide/pull/287/files

thanks.hope you all good .
