### ISSUE TITLE
Support launching a VM via the Pod API

### ISSUE THREAD

**Issue by admiyo** [kubevirt/kubevirt#276]
Without breaking the existing VM api for launching VMs, Kubevirt should support the ability to launch a VM by specifying only a Pod.  The steps would roughly be:

1. User crafts a pod spec.
2.  User launches a pod with e.g.  kubectl create -f newvmpod.yaml
3.  Pod launches and runs.
4.  Pod contacts the local virt-handler to indicate it is to become a  new VM.
5. virt-handler evaluates the pod to see if it is a viable VM.  If so, posts the new VM object to the API server.
6.  Current VM launch process proceeds, but instead of creating a new pod, the virt-controller:execute function identifies the existing pod as the virt-launcher instances to use for the VM.

Migration would still kill the original pod and leave the VM definition in place.

The rational for launching via pods as opposed to the VM api is that most other Kubernetes absrtactions  (replica sets and deployments for example) know only about pods, and not TPRs or other resources.

**Comment by davidvossel** [comment]
It seems like it would be possible for us to leverage k8s abstractions (like replica sets) without needing the ability to support launching a VM by only specifying a POD.

For example. We could create a TPR called VMGroup that contains both a VM spec along with other VMGroup specific values (like the desired instance count). Behind the scenes virt-controller could just map the VMGroup to a replicaset with virt-launcher pods if we wanted. At that point it would be business as usual.

**Comment by admiyo** [comment]
So you are saying that instead of reusing the K8S abstractions as the user facing interface, we would always provide a Kubevirt equivalent instead?
Anything that manages Kuberenetes based deployments/pods etc will not know about our abstractions; we're working at cross purposes with the ecosystem. I'm trying to reverse that here.

 We could use Config maps as a way to store the VM specific data ahead of time. Saying that you need to create a config map prior to deploying a pod is a common requirement

**Comment by fabiand** [comment]
> Behind the scenes virt-controller could just map the VMGroup to a replicaset with virt-launcher pods if we wanted. At that point it would be business as usual.

I'm not sure if this will work today. First is that a VM object currently represents a single VM - in a VMGroup you can have several. And second the handler watches the VM object to be scheduled, then it watches for a pod with a specific name - this name can no be predicted in a RS.

A first step is to decouple the configuration of a VM from the instance data of a VM, as discussed in #272.

**Comment by davidvossel** [comment]
I think we can close this issue now. Our design choices have effectively ruled out the possibility of driving VM creation using a POD. I don't think we want this functionality at this point.

**Comment by rmohr** [comment]
Agreed.
