### ISSUE TITLE
Serval enhancement to port macOS VM to kubevirt

### ISSUE THREAD

**Issue by lxs137** [kubevirt/kubevirt#2763]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:

I want to create a macOS VM that runs and is managed by kubevirt (related issue #2312). I follow the guide on [OSX-KVM](https://github.com/kholia/OSX-KVM).

But I found we miss some `libvirt` fields to define macOS VM with **release-0.21** `VirtualMachineInstanceSpec`. 

I handle this by adding serval `OnDefineDomain` hook-sidecars, finally my macOS libvirt-xml looks like https://gist.github.com/lxs137/cbebea860902f79ad198fa00038e0eff, I don't like this manual workaround, I would like to extend the `VirtualMachineInstanceSpec`:

1. macOS VM need custom `BootLoader` and `NVRam`, cur version just use a fixed path EFI, **I want to import EFI from a custom Volume**: https://github.com/kubevirt/kubevirt/blob/e220f16d7a2aae7295199bbbc3594a5b50b7a3f4/pkg/virt-launcher/virtwrap/api/converter.go#L680-L693

2. macOS VM cannot detect `raw` format disk.img, but cur version just fix the driverType to `raw`, **I want to custom disk driverType**: https://github.com/kubevirt/kubevirt/blob/e220f16d7a2aae7295199bbbc3594a5b50b7a3f4/pkg/virt-launcher/virtwrap/api/converter.go#L312-L317

3. macOS VM can only detect `e1000-82545em` or `vmxnet3` nic model, but cur version cannot support, **I want to add more supported nic model**:
https://github.com/kubevirt/kubevirt/blob/e220f16d7a2aae7295199bbbc3594a5b50b7a3f4/pkg/virt-api/webhooks/validating-webhook/admitters/vmi-create-admitter.go#L62

4. macOS cannot support `PS/2` input device, only `USB` input device can work, but cur version just support tablet input device, **I want to define keyboard `USB` input device**:
https://github.com/kubevirt/kubevirt/blob/e220f16d7a2aae7295199bbbc3594a5b50b7a3f4/staging/src/kubevirt.io/client-go/api/v1/schema.go#L348-L357
Also I find implied libvirt `USB` controller not work, I must explicit define `USB` controller in my libvirt xml (Probably implied `USB` controller works on some macOS version, I am not sure):
```
<controller type='usb' index='0' model='piix3-uhci'/>
```

I am not familiar with qemu and libvirt, maybe some changes is not required to port macOS to kubevirt, please give me some advise. 

**And I am glad to do some `PR` on these enhancement. :) THX**

**Comment by marcus-sa** [comment]
Take a look at this https://github.com/foxlet/macOS-Simple-KVM

**Comment by lxs137** [comment]
> Take a look at this https://github.com/foxlet/macOS-Simple-KVM
> 
> Seems like it might be possible to integrate the steps required for that to work in KubeVirt.

Yes, macOS can work in kubevirt now in my situation. But it need some dirty work, such as miscellaneous hook sidecars and an extended [MutationWebhook](https://github.com/lxs137/k8s-sidecar-injector).

**Comment by lxs137** [comment]
@fabiand What do you think about these four features? I have no idea how to impl feature-1, is it suitable to load `EFI` data from [volumes](https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/disks-and-volumes.html#volumes)?

**Comment by fabiand** [comment]
I could imagine that we could support pointing to a different EFI loader by using an annotation, just like it's done in Kubernetes for alpha/try-out features.

I.e. you'd add an annotation to the VM/VMI definition to specify the loader to use. Which could i.e. reside on a PV/C or containerDisk

But I am just on voice.

**Comment by lucatk** [comment]
@lxs137 Could you share your resource file for getting either [OSX-KVM](https://github.com/kholia/OSX-KVM) or [macOS-Simple-KVM](https://github.com/foxlet/macOS-Simple-KVM) running on Kubevirt?

**Comment by tlawrie** [comment]
@lucatk @lxs137 any chance you could share instructions on how to do this?

**Comment by lxs137** [comment]
> @lucatk @lxs137 any chance you could share instructions on how to do this?

@lucatk @tlawrie

**Comment by cszixin** [comment]
> > @lucatk @lxs137 any chance you could share instructions on how to do this?
> 
> @lucatk @tlawrie Sorry for my late reply.
> 
> I have a README about this: https://github.com/droidvirt/kubevirt-sidecars/blob/master/osx-hook-sidecar/README.md
> 
> It needs [MutatingWebhook](https://github.com/droidvirt/k8s-sidecar-injector) and [kubevirt-hook-sidecar](https://github.com/droidvirt/kubevirt-sidecars/blob/master/osx-hook-sidecar).
> 
> I think it's just a workaround, it will be better if the kubevirt can add some feature to support this.

hi, follow this , now i can run macos on kubevirt, but vnc do not work(use `virtctl vnc` command )
i can not input anything with mouse and keyboard
this is the qemu command
/webhook/macox/qemu/bin/qemu-system-x86_64 -name guest=test3-vir_macox-test,debug-threads=on -S -object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-1-test3-vir_macox-test/master-key.aes -blockdev {"driver":"file","filename":"/webhook/macox/OVMF_CODE.fd","node-name":"libvirt-pflash0-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-pflash0-format","read-only":true,"driver":"raw","file":"libvirt-pflash0-storage"} -blockdev {"driver":"file","filename":"/webhook/macox/OVMF_VARS-1024x768.fd","node-name":"libvirt-pflash1-storage","auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-pflash1-format","read-only":false,"driver":"raw","file":"libvirt-pflash1-storage"} -machine pc-q35-6.2,accel=kvm,usb=off,dump-guest-core=off,pflash0=libvirt-pflash0-format,pflash1=libvirt-pflash1-format -cpu Cascadelake-Server,ss=on,vmx=on,hypervisor=on,tsc-adjust=on,umip=on,pku=on,md-clear=on,stibp=on,arch-capabilities=on,xsaves=on,ibpb=on,amd-stibp=on,amd-ssbd=on,rdctl-no=on,ibrs-all=on,skip-l1dfl-vmentry=on,mds-no=on,pschange-mc-no=on,hle=off,rtm=off -m 4096 -overcommit mem-lock=off -smp 2,sockets=1,dies=1,cores=2,threads=1 -object iothread,id=iothread1 -uuid 63f2b259-3684-5f05-b506-28598ca394e8 -smbios type=1,manufacturer=KubeVirt,product=None,uuid=63f2b259-3684-5f05-b506-28598ca394e8,family=KubeVirt -no-user-config -nodefaults -chardev socket,id=charmonitor,fd=18,server,nowait -mon chardev=charmonitor,id=monitor,mode=control -rtc base=utc -no-shutdown -boot strict=on -device pcie-root-port,port=0x10,chassis=1,id=pci.1,bus=pcie.0,multifunction=on,addr=0x2 -device pcie-root-port,port=0x11,chassis=2,id=pci.2,bus=pcie.0,addr=0x2.0x1 -device pcie-root-port,port=0x12,chassis=3,id=pci.3,bus=pcie.0,addr=0x2.0x2 -device pcie-pci-bridge,id=pci.4,bus=pci.1,addr=0x0 -device pcie-root-port,port=0x13,chassis=5,id=pci.5,bus=pcie.0,addr=0x2.0x3 -device pcie-root-port,port=0x14,chassis=6,id=pci.6,bus=pcie.0,addr=0x2.0x4 -device pcie-root-port,port=0x15,chassis=7,id=pci.7,bus=pcie.0,addr=0x2.0x5 -device pcie-root-port,port=0x16,chassis=8,id=pci.8,bus=pcie.0,addr=0x2.0x6 -device qemu-xhci,id=usb,bus=pci.3,addr=0x0 -device piix3-usb-uhci,id=usb1,bus=pci.4,addr=0x1 -device virtio-scsi-pci,id=scsi0,bus=pci.5,addr=0x0 -device virtio-serial-pci,id=virtio-serial0,bus=pci.6,addr=0x0 -blockdev {"driver":"host_device","filename":"/dev/opencore","aio":"native","node-name":"libvirt-3-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-3-format","read-only":false,"cache":{"direct":true,"no-flush":false},"driver":"raw","file":"libvirt-3-storage"} -device ide-hd,bus=ide.0,drive=libvirt-3-format,id=ua-opencore,bootindex=1,write-cache=on -blockdev {"driver":"host_device","filename":"/dev/baseimage","aio":"native","node-name":"libvirt-2-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-2-format","read-only":false,"cache":{"direct":true,"no-flush":false},"driver":"raw","file":"libvirt-2-storage"} -device ide-hd,bus=ide.1,drive=libvirt-2-format,id=ua-baseimage,bootindex=2,write-cache=on -blockdev {"driver":"host_device","filename":"/dev/macos","aio":"native","node-name":"libvirt-1-storage","cache":{"direct":true,"no-flush":false},"auto-read-only":true,"discard":"unmap"} -blockdev {"node-name":"libvirt-1-format","read-only":false,"cache":{"direct":true,"no-flush":false},"driver":"raw","file":"libvirt-1-storage"} -device ide-hd,bus=ide.2,drive=libvirt-1-format,id=ua-macos,bootindex=3,write-cache=on -netdev tap,fd=20,id=hostua-default,vhost=on,vhostfd=21 -device virtio-net-pci,host_mtu=1450,netdev=hostua-default,id=ua-default,mac=32:68:7d:ad:2d:fd,bus=pci.2,addr=0x0,romfile= -chardev socket,id=charserial0,fd=22,server,nowait -device isa-serial,chardev=charserial0,id=serial0 -chardev socket,id=charchannel0,fd=23,server,nowait -device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=org.qemu.guest_agent.0 -device usb-mouse,id=input1,bus=usb.0,port=1 -device usb-tablet,id=input2,bus=usb.0,port=2 -device usb-kbd,id=input3,bus=usb.0,port=3 -vnc vnc=unix:/var/run/kubevirt-private/50aee78a-fc39-472a-b631-b4fca45604e9/virt-vnc -device VGA,id=video0,vgamem_mb=16,bus=pcie.0,addr=0x1 -device virtio-balloon-pci,id=balloon0,bus=pci.7,addr=0x0 -device isa-applesmc,osk=ourhardworkbythesewordsguardedpleasedontsteal(c)AppleComputerInc -smbios type=2 -usb -device usb-tablet -device usb-kbd -cpu Penryn,kvm=on,vendor=GenuineIntel,+invtsc,vmware-cpuid-freq=on,+ssse3,+sse4.2,+popcnt,+avx,+aes,+xsave,+xsaveopt,check -msg timestamp=on

![image](https://user-images.githubusercontent.com/16910250/204794464-8b360a88-a6c5-4c21-8c32-88e2e7311baf.png)

**Comment by lxs137** [comment]
@cszixin Which OSX version do you use? I have tried this only on OSX Mojave.

**Comment by cszixin** [comment]
> @cszixin Which OSX version do you use? I have tried this only on OSX Mojave.
my version is  High Sierra,   and i also meet the problem with network,  i have no internet,
this is my  interface settings 
![image](https://user-images.githubusercontent.com/16910250/205198770-3754ecc7-005c-438b-9c29-ac880fcfd34c.png)

**Comment by lxs137** [comment]
@cszixin have you tried e1000-82545em network device model?

**Comment by cszixin** [comment]
@lxs137   e1000-82545em does not work 
![image](https://user-images.githubusercontent.com/16910250/205527257-b6bd6828-b43c-48db-a587-ed200daa9159.png)
![image](https://user-images.githubusercontent.com/16910250/205527317-836f465a-c715-4e73-bb42-47050afc98fb.png)
