### ISSUE TITLE
Regarding Kubevirt and AWS/GCP (VMX/SVM)

### ISSUE THREAD

**Issue by hetzbh** [kubevirt/kubevirt#2764]
Hi,

I'm not sure if this classifies as a bug, but the docs are pretty short on this issue:

One thing that is not explained well on the docs, is actually how does Kubevirt runs on AWS or GCP, so you cannot run nested VM's, so how the VM is running on public clouds? soft emulation?

**Comment by slintes** [comment]
Hi,

yes, if nested virt is disabled, software emulation is the only way to go. See here how to enable it: https://kubevirt.io/user-guide/docs/latest/administration/intro.html#software-emulation

Side note: there might be cloud providers with nested virt enabled, e.g at least a few months ago I tested on DigitalOcean successfully, even though it is not documented by them IIRC.

**Comment by fabiand** [comment]
Can we state this more prominently in the user-guide?
Or in the README.

- fabian

**Comment by fabiand** [comment]
Just to follow up here.

Today's take is that KubeVirt can be run on bare-metal instances in the
cloud. This is the recommendation so far for running "production like"
workloads in the cloud.
In addition to this, KubeVirt can also get deployed on i.e. Kubernetes as a
service offerings or in general offerings which have netsing enabled - Like
certain GCP VMs and i.e. Azure AKS. This setup is only recommended for
testing or demo purpose.

**Comment by alexellis** [comment]
Why is nested virt only useful for testing and demos?

**Comment by cjtim** [comment]
I notice that `/dev/kvm` only expose to pod only if server is Intel(vmx). AMD(svm) not working :(

use case is for QEMU build image with Terraform (nested virtualization is needed)

Anyone happen the same?

**Comment by fl64** [comment]
An example would be using VDI with Windows. Where users need to use WSL
