### ISSUE TITLE
Problem in console into VM 

### ISSUE THREAD

**Issue by chinadd** [kubevirt/kubevirt#2801]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
Can't access VM via serial cable
```
[centos@kubernetes-master ~]$ kubectl virt console vmi-centos7-lustre-mds
Successfully connected to vmi-centos7-lustre-mds console. The escape sequence is ^]

CentOS Linux 7 (Core)
Kernel 3.10.0-957.el7_lustre.x86_64 on an x86_64

ct7-mds2 login: centos
Password: 
Login incorrect
```

**What you expected to happen**: I should be able to login

**How to reproduce it (as minimally and precisely as possible)**:
Create a kubernetes cluster, deploy `pv-mds.yaml`, `pvc-mds.yaml` and `centos7-lustre-mds.yaml` sequentially. (https://github.com/chinadd/kubevirt-lustre-new/tree/master/yaml)

**Anything else we need to know?**:
The VMI is starting:
```
Events:
  Type     Reason     Age                    From                       Message
  ----     ------     ----                   ----                       -------
  Normal   Scheduled  <unknown>              default-scheduler          Successfully assigned default/virt-launcher-vmi-centos7-lustre-mds-gnwfj to kubernetes-node1
  Normal   Pulled     3m39s                  kubelet, kubernetes-node1  Container image "dlambrig/centos7-lustre:latest" already present on machine
  Normal   Created    3m39s                  kubelet, kubernetes-node1  Created container volumecontainerdisk
  Normal   Started    3m39s                  kubelet, kubernetes-node1  Started container volumecontainerdisk
  Normal   Pulled     3m39s                  kubelet, kubernetes-node1  Container image "index.docker.io/kubevirt/virt-launcher:v0.17.0" already present on machine
  Normal   Created    3m38s                  kubelet, kubernetes-node1  Created container compute
  Normal   Started    3m38s                  kubelet, kubernetes-node1  Started container compute
  Warning  Unhealthy  3m32s (x2 over 3m36s)  kubelet, kubernetes-node1  Readiness probe failed: cat: /tmp/healthy: No such file or directory
  Warning  Unhealthy  3m24s (x6 over 3m33s)  kubelet, kubernetes-node1  Readiness probe failed: cat: /var/run/kubevirt-infra/healthy: No such file or directory
[centos@kubernetes-master yaml]$ kubectl get vmis
NAME                     AGE     PHASE     IP                  NODENAME
vmi-centos7              38h     Running   192.168.237.6/32    kubernetes-master
vmi-centos7-demo         25h     Running   192.168.237.7/32    kubernetes-master
vmi-centos7-lustre-mds   3m49s   Running   192.168.129.71/32   kubernetes-node1
```

**Environment**:
- KubeVirt version (use `virtctl version`):
```
[centos@kubernetes-master ~]$ kubectl virt version
Client Version: version.Info{GitVersion:"v0.21.0", GitCommit:"e220f16d7a2aae7295199bbbc3594a5b50b7a3f4", GitTreeState:"clean", BuildDate:"2019-09-07T07:33:17Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.17.0", GitCommit:"a067696ed6c25b0eab9dfcd01bbdc045f500f8ca", GitTreeState:"clean", BuildDate:"2019-05-06T14:58:11Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```
[centos@kubernetes-master ~]$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T17:01:15Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.1", GitCommit:"d647ddbd755faf07169599a625faf302ffc34458", GitTreeState:"clean", BuildDate:"2019-10-02T16:51:36Z", GoVersion:"go1.12.10", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications:
see https://github.com/chinadd/kubevirt-lustre-new/blob/master/yaml/centos7-lustre-mds.yaml
- Cloud provider or hardware configuration:

Kubernetes-Node2 | centos-kubernetes-docker | 10.0.0.26 | m1.s2.medium 
Kubernetes-Node1 | centos-kubernetes-docker | 10.0.0.12 | m1.s2.medium 
Kubernetes-master | centos-kubernetes-docker | 10.0.0.10Floating IPs:128.31.24.131 | m1.s2.large 

- OS (e.g. from /etc/os-release):
```
CentOS Linux 7 (Core)
Kernel 3.10.0-957.el7_lustre.x86_64 on an x86_64
```
- Kernel (e.g. `uname -a`):
```
[centos@kubernetes-master ~]$ uname -a
Linux kubernetes-master 3.10.0-1062.1.2.el7.x86_64 #1 SMP Mon Sep 30 14:19:46 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:

**Comment by petrkotas** [comment]
Hi @chinadd I am guessing right now, but it seems to me, that you have created the VM image yourself from centos installation. Is that correct?

If so, to make it work with serial console you have to update GRUB to enable console. Centos does not have it by default.

Please look for instance [here](https://www.hiroom2.com/2016/06/07/centos-7-grub2-and-linux-with-serial-console/) how to do this.

I hope this helps.

**Comment by slintes** [comment]
the console technically works, see
```
ct7-mds2 login: centos
Password: 
Login incorrect
```
So either username or password is incorrect. I see the password is set in cloud init, so that leaves us to the username. I'm not sure if the default user for CentOS is `centos`... did you try `root`?

**Comment by chinadd** [comment]
> Hi @chinadd I am guessing right now, but it seems to me, that you have created the VM image yourself from centos installation. Is that correct?
> 
> If so, to make it work with serial console you have to update GRUB to enable console. Centos does not have it by default.
> 
> Please look for instance [here](https://www.hiroom2.com/2016/06/07/centos-7-grub2-and-linux-with-serial-console/) how to do this.
> 
> I hope this helps.

Thanks! I think GRUB2 is set to serial console here in my Kubernetes node since I get the login prompt. 
I also checked /etc/default/grub
```
[centos@kubernetes-node1 ~]$ cat /etc/default/grub
GRUB_TIMEOUT=1
GRUB_DISTRIBUTOR="$(sed 's, release .*$,,g' /etc/system-release)"
GRUB_DEFAULT=saved
GRUB_DISABLE_SUBMENU=true
GRUB_TERMINAL="serial console"
GRUB_SERIAL_COMMAND="serial --speed=115200"
GRUB_CMDLINE_LINUX="console=tty0 crashkernel=auto console=ttyS0,115200"
GRUB_DISABLE_RECOVERY="true"
```

**Comment by chinadd** [comment]
> the console technically works, see
> 
> ```
> ct7-mds2 login: centos
> Password: 
> Login incorrect
> ```
> 
> So either username or password is incorrect. I see the password is set in cloud init, so that leaves us to the username. I'm not sure if the default user for CentOS is `centos`... did you try `root`?

Yeah, I also wonder about this since I was borrowing other people's code. `root` doesn't work either. The reason I tried `centos` was that this deployment (https://github.com/chinadd/kubevirt-lustre-new/blob/master/yaml/centos7.yaml) was successful, with username & password == `centos`. That one doesn't have a persistent volume though.

**Comment by chinadd** [comment]
> the console technically works, see
> 
> ```
> ct7-mds2 login: centos
> Password: 
> Login incorrect
> ```
> 
> So either username or password is incorrect. I see the password is set in cloud init, so that leaves us to the username. I'm not sure if the default user for CentOS is `centos`... did you try `root`?

Never mind, just change the docker image solves the problem. Username should be defined within it.
