### ISSUE TITLE
Report back guest OS Info obtained from guest agent

### ISSUE THREAD

**Issue by pbudds** [kubevirt/kubevirt#2823]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What happened**:
When a Guest VM is deployed, the VMI status does not report back the Guest OS Information(OS Name,  Kernel version etc).That information would be valuable to have.

**What you expected to happen**:
Expose Guest OS Info  in VMI Status similar to how Interface IP addresses are reported back.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a VM and check VMI status

**Anything else we need to know?**:
If the experts agree this would be useful to the community, I could work on a PR to make this happen.

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by petrkotas** [comment]
Hi @pbudds thanks for submitting this issue. I have a great news. This feature is planned for in one of the next releases.

**Comment by pbudds** [comment]
Thank you @petrkotas. Would you know if anybody started to work on it already? If not, I would be more than happy to pass my changes on to the community for further review.

**Comment by petrkotas** [comment]
Hi @pbudds yes, actually it is me who is working on this.

**Comment by fabiand** [comment]
Would be cool to see your changes, Prashanth

>

**Comment by pbudds** [comment]
@fabiand - Sure. Will send those out in a PR. 

@petrkotas - Do not mean to disrupt your plans, but just check out the changes, at the bare minimum, the tests should be useful to you.
