### ISSUE TITLE
Investigate behavior of daemonized pids in container host pid namespace

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#283]
We need to gain a complete understanding of how docker manages daemonized pids in a container when the host pid namespace is used.  This impacts multiple areas of our architecture.

For libvirt resiliency we'd like to know if it is possible for KVM processes to exist independently of the container they are launched in. For vm cleanup we'd like to know if it's possible to tie a vm process launched in the host pid namespace with the pid cleanup mechanism of another container.

These are the questions we have to answer. 

- what inherits the daemonized pids in a container when host pid namespace is used.
- is it possible for the daemonized pids to persist longer than the container?
- if the pids cannot persist longer than the container when host pid namespace is used, what exact mechanism is preventing that?

**Comment by berrange** [comment]
Ah ha, it turns out that Docker is making use of a Linux specific feature to override normal UNIX reparenting behaviour. Specifically it is calling prctl(PR_SET_CHILD_SUBREAPER)  to set the shim as the "owner" of the children, so even in the host PID namespace, it inherits orphans instead of the original init.

**Comment by fabiand** [comment]
At least CRI-O supports restarting the kubelet (or the CRI-O daemon) without impacting the containers, see kubernetes-incubator/cri-o#756.

**Comment by rmohr** [comment]
@davidvossel found out some time go, that by letting the pod use the host PID namespace, the containers are killed based on cgroups. However, soone qemu will natively run in the Pod.
