### ISSUE TITLE
Provide Ready condition for VM

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#2864]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What happened**:
$ virtctl start testvm
$ kubectl wait --for=condition=Ready vm testvm
No such condition

The condition is just not available today, only a phsae.

**What you expected to happen**:
$ virtctl start testvm
$ kubectl wait --for=condition=Ready vm testvm
# vm running
$ virtctl vnc testvm
# vnc can connect

**How to reproduce it (as minimally and precisely as possible)**:
Just run the lines above

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mprey** [comment]
I am interested in working on this issue.

**Comment by fabiand** [comment]
That would be awesome.
It's a simple thing to copy / keep in sync with VMI, but so helpful for
`kubectl wait`

Do you know how to start or do you need some help here?

>

**Comment by mprey** [comment]
I've been in contact with Stuart Gott and he's gave me some tips on getting started. In the event of getting blocked or general questions, should I ask here, kubevirt-dev group, or maybe somewhere else?

**Comment by fabiand** [comment]
Great!
Stu probably knows all the tricks, and kubevirt-dev is then a good place to
get some additional help.
#virtualization on kubeernetes.slack.com is a good resource as well.

Reminds me that we could ramp up our contributing docs.

>

**Comment by mprey** [comment]
@fabiand a few follow up questions since I am a little lost:

After reading about readiness probes, I saw the operator spec YAML file sets the readiness probe to use the /metrics endpoint through HTTPS. What I see in the code is this endpoint is being served by Prometheus, which as far as I can tell, isn't concerned about the readiness of the VM. Is this where the problem is or am I off-base? Thanks!

**Comment by stu-gott** [comment]
@mprey I think we're being sneaky here. As long as the HTTP(S) endpoint returns an HTML success code, Kubernetes will consider the probe to be successful. In this case /metrics probably *does* return a success code. @rmohr keep me honest here.

To be clear. this "/metrics" endpoint is not served *by* prometheus. Prometheus actually probes that endpoint to collect data.

**Comment by rmohr** [comment]
@mprey @stu-gott we already support readiness probes. You can configure them on the VM on the VMI template. The only task which is remaining, is copying the readyness condition from the vmi-status to the vm, so that people ca use `kubectl wait` in a more convenien way.

**Comment by fabiand** [comment]
Sorry for the dealy. But, yes as Roman and Stu are saying.
