### ISSUE TITLE
Have an event whenever live migration starts for a VM

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#2865]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind enhancement

**What happened**:
$ virtctl migrate testvm
$ kubectl describe vm testvm

No event listed until the new pod was started

**What you expected to happen**:
Event is observal on VM (or VMI?) once the VM is affected by a migration object (thus way before the new pod is ready)
Main reason is to understand that aVM will be migrated soon

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by xpivarc** [comment]
@fabiand can you assign me please?

**Comment by fabiand** [comment]
You can do it yourself by adding a comment with /assign
