### ISSUE TITLE
Use hostDisk and cloudinitDisk to start vm but hang

### ISSUE THREAD

**Issue by xzcccc** [kubevirt/kubevirt#2886]
**What happened**:
I wanna use hostDisk to start the debian vm
**What you expected to happen**:
How to start and initialize vm with hostDisk
**How to reproduce it (as minimally and precisely as possible)**:
vmi-hostdisk-test.yaml
```apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-hostdisk-test
  name: vmi-hostdisk-test
spec:
  nodeSelector:
    kubernetes.io/hostname: k8s-office-03
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: host-disk
      - disk:
          bus: virtio
        name: cloudinitdisk
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  terminationGracePeriodSeconds: 0
  volumes:
  - hostDisk:
      #capacity: 5Gi
      path: /data01/debian-10.1.5-20191015-openstack-amd64.qcow2
      type: Disk
    name: host-disk
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: test
        chpasswd: { expire: False }
status: {}
```

Then
`kubectl create -f vmi-hostdisk-test.yaml`
I can see the vmis is running, but when I run `kubectl virt console vmi-hostdisk-test`, prompt just hangs :
`Successfully connected to vmi-hostdisk-test console. The escape sequence is ^]`

**Anything else we need to know?**:
I wanna know if it is possible to start a vm via hostDisk.
**Environment**:
- KubeVirt version (use `virtctl version`): 0.23.0
- Kubernetes version (use `kubectl version`): 1.13.5
- OS (e.g. from /etc/os-release): debian10
- Kernel (e.g. `uname -a`): Debian 4.19.67-2+deb10u1

Thanks a lot.

**Comment by petrkotas** [comment]
Hi @xzcccc I see you are using qcow2 image. Currently KubeVirt supports only img files. Please convert the image to raw img and try again. Your yaml does look OK.

**Comment by rmohr** [comment]
Yes, we are a little bit inconsistent here. `containerDisk` supports both `qcow2` and `raw`, but hostDisk only supports `raw`. Just to avoid confusions, the name or the ending of the disk does not play a role (if you call it `test.img` or `test.blub` does not matter, we always assume raw images).

**Comment by xzcccc** [comment]
ok, thanks a lot, I will try img files.

**Comment by leyao-daily** [comment]
> ok, thanks a lot, I will try img files.

Hi, have you solved this problem?

**Comment by fabiand** [comment]
Please re-open if this is still an issue.
