### ISSUE TITLE
virt-launcher is missing selinux permission to allocate VFs

### ISSUE THREAD

**Issue by vladikr** [kubevirt/kubevirt#2887]
/kind bug

**What happened**:
Failed to allocate a SRIOV VF to VMI
virt-launcher fails with the following error:
```
{"component":"virt-launcher","level":"error","msg":"Failed to open config space file '/sys/bus/pci/devices/0000:19:02.0/config': Permission denied","pos":"virPCIDeviceConfigOpen:298","subcomponent":"libvirt","thread":"48","timestamp":"2019-11-19T01:09:17.222000Z"}
```
SELinux denial:
 ```
type=AVC msg=audit(1574124446.395:50470): avc:  denied  { write } for  pid=2958378 comm="libvirtd" name="config" dev="sysfs" ino=54459 scontext=system_u:system_r:virt_launcher.process:s0:c559,c957 tcontext=system_u:object_r:sysfs_t:s0 tclass=file permissive=0
```
**Anything else we need to know?**:
This happens on RHEL7.7 running OpenShift 4.3 with kubvirt v0.23.0
Sriov devices are managed with Openshift-sriov-operator

**Comment by vladikr** [comment]
Probably need to add ```

#============= virt_launcher.process ==============
allow virt_launcher.process sysfs_t:file write;
```

to our profile.

**Comment by rmohr** [comment]
@vladikr what confuses me a little: would apps, which use the sriov plugin not also need to have access to this? Is this an error in the sriov plugin?

**Comment by vladikr** [comment]
> @vladikr what confuses me a little: would apps, which use the sriov plugin not also need to have access to this? Is this an error in the sriov plugin?

@rmohr That was my understanding too, that all of these sysfs manipulations should be done in the sriov plugin, but I can see now that it's not for some reason.
Perhaps Openshift 4.3 works differently... we don't have tests for it :(

@fedepaol could you please advise?

**Comment by fedepaol** [comment]
Sorry, I may need a bit more context.

The way it works is that all the heavy lifting done on the device by the sriov plugin is done outside the pod, from the operator, the cni plugin and the device plugin (which probably are privileged and have all the permissions of the case).
Once the virtual function is ready, is passed in the namespace of the virt-launcher, which in turn uses vfio to pass the device through the guest, and this is when I think we get that denial. So, I _think_ it's a matter of how libvirt handle passthrough devices more than how those are handled by the sr-iov plugin.

Now, my question is: is this happening on CI as well? Why this happened only now?

**Comment by rmohr** [comment]
> Now, my question is: is this happening on CI as well? Why this happened only now?

Maybe new selinux policies, or some changes on the device plugin? We don't have CI for 4.3.

**Comment by fedepaol** [comment]
> > Now, my question is: is this happening on CI as well? Why this happened only now?
> 
> Maybe new selinux policies, or some changes on the device plugin? We don't have CI for 4.3.

Sorry, I just realized it was on ocp.
