### ISSUE TITLE
Add support for providing cloud-init data store

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#289]
A common use case for IaaS platforms is to provide the ability to execute a short custom startup script that executes as root within the guest VM on initialization.

startup script functionality as provided AWS and GCE 
https://cloud.google.com/compute/docs/startupscript
http://docs.aws.amazon.com/AWSEC2/latest/UserGuide/user-data.html

Since startup scripts are associated with the VM definition, this appears to be within the scope of what KubeVirt should be capable of managing.  This functionality is one of the fundamental bits people using cloud technology leverage when designing their operational infrastructure.

For example, a common pattern used with cloud infrastructure is for a VM to "phone home" on initialization in a way that triggers a software provisioner (like ansible) to perform some action on the new host. People use generic VM images and bootstrap the process of software provisioning using a small startup script stored in the VM definition.

**Comment by mykaul** [comment]
Is it different than cloud-init payload?

**Comment by fabiand** [comment]
At least the AWS link refers to cloud-init, and the gclodu link sounds much like it.

Sounds reasonable to support this. The difference to the VM Spec is that the VM Spec is so far specifying the 'hull' of a VM, whereas a guest sided script relies on guest support.

We need to move forward with #272 to get a better perspective on where this feature could live.

**Comment by mykaul** [comment]
so cloud-init provides already guest-side scripts, as well as network configuration, SSH keys and more, and is widely used (including in OpenStack and oVirt). Why do we need anything other than cloud-init payload?
(I think the interesting issue is how we deliver the payload - over the network on 169.x network like OpenStack, or via a CD-ROM attached to the VM, like oVirt).

**Comment by fabiand** [comment]
To me it didn't sound like we were considering something else, but rather that we need this functionality. cloud-init sounds - and you provided the reasons - like a good candidate.

**Comment by berrange** [comment]
Renamed this to reflect the broader need here - startup script is just one thing that cloud-init suports, and we want cloud-init suport in general.

**Comment by fabiand** [comment]
Closing this according to the initial cloud-init support in KubeVirt.

A nocloud source can be provided either inline or using a secret, see
https://github.com/kubevirt/kubevirt/blob/master/docs/cloud-init.md
