### ISSUE TITLE
Ensure we're testing migration between different libvirt versions

### ISSUE THREAD

**Issue by iranzo** [kubevirt/kubevirt#2891]
**What you expected to happen**:

In the past (OSP, oVirt), migrations between different versions of libvirt infra caused issues, requiring some libvirt XML changes which allowed VM's to migrate from older to newer but not going back.

Once we support migrations, we should have  tests in place

Some examples of what is supposed to work/not: 
- [RHEL7](https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/7/html/virtualization_deployment_and_administration_guide/sect-KVM_live_migration-Live_migration_and_Red_Hat_Enterprise_Linux_version_compatibility_#tabl-Live_migration_and_Red_Hat_Enterprise_Linux_version_compatibility_-Live_Migration_Compatibility)

**Comment by petrkotas** [comment]
This is a good point, I do believe we do not have a strategy for doing upgrades when the VMs are still running. Thanks @iranzo.
