### ISSUE TITLE
KubeVirt‘s Documents may be updated now

### ISSUE THREAD

**Issue by Apokleos** [kubevirt/kubevirt#2892]
Hi， Maintainer
KubeVirt's Documents maybe out of date, 
such as https://github.com/kubevirt/kubevirt/blob/master/docs/components.md

There is no many resources about Kubevirt but KubeVirt‘s github. So Kubevirt's github maybe the most important resources for People who want to understand  and use it.

May you update the documents, Please?
Thx a lot.

**Comment by liangyuanpeng** [comment]
Yes yes i am confused about doc

**Comment by fabiand** [comment]
Yes, I think you have a point. The docs are outdated.
