### ISSUE TITLE
[FOSSA] Issue with validate - UNLICENSED_DEPENDENCY

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#2898]
### Component URL
https://github.com/markbates/validate

### Affected Projects
- kubevirt

### Issue
This dependency hasn't specified a license. You may need to contact the author to obtain permission to use it.

No licenses found by FOSSA.

---

Generated by [FOSSA](https://fossa.com) on 11/22/2019
Reported by FOSSA user: daniel.hiller.1972@googlemail.com

**Comment by rmohr** [comment]
I see that dependency not in our `vendor` folder. That is probably a transitive dependency on which we do not depend. Since we have all our dependencies in our `vendor` folder, I think we can just close/ignore such dependencies in FOSSA,  if we don't have them in `vendor`.

**Comment by dhiller** [comment]
Transitive dependency not present in our vendor folder.

/close
