### ISSUE TITLE
Support for containerd

### ISSUE THREAD

**Issue by andrewrynhard** [kubevirt/kubevirt#2904]
/kind enhancement

**What happened**:
Noticed that the docs don't mention containerd as being supported.

**What you expected to happen**:
I'd like to run KubeVirt with containerd.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by cynepco3hahue** [comment]
@andrewrynhard I think we support to run on any container runtime as far as it supported by k8s.
Did you try to run kubevirt on top of it?

**Comment by rmohr** [comment]
I think that #2748 will be an issue here. In order to reach a broader audience by default, we build docker v2.2 containers. However, as far as I know, containerd only supports OCI containers. I think pushing OCI would be as simple as replacing all our `container_push` commands in the BUILD files with `oci_push`.

**Comment by andrewrynhard** [comment]
@rmohr i have not tried yet. I just saw in the docs that docket and cri-o are supported but not containerd.

**Comment by andrewrynhard** [comment]
@rmohr Is the pushing of OCI containers planned? In my experience containerd has been able to handle everything I have thrown at it. I'm not familiar with the build process for KubeVirt, so I don't know how different the push is. I can take a look though, and give KubeVirt a try.

**Comment by clarklee92** [comment]
> @cynepco3hahue i have not tried yet. I just saw in the docs that docket and cri-o are supported but not containerd.

`containerd` old version can not use kubevirt container image. now >=1.3.0 works well, I tried and not .

**Comment by andrewrynhard** [comment]
@clarklee92 great news! Need to get aggregation layer enabled come to find out, but good to hear that `containerd` works.

**Comment by rmohr** [comment]
> I tried and without some serious bug.

@clarklee92 even in case that you found just non-serious bugs, make sure that you let us know about  them.

**Comment by clarklee92** [comment]
> > I tried and without some serious bug.
> 
> @clarklee92 even in case that you found just non-serious bugs, make sure that you let us know about them.

It has not yet been determined what the problem is caused by the CRI runtime. And I will synchronize with the community as soon as I find out.

**Comment by rmohr** [comment]
@andrewrynhard did you have success with containerd?

**Comment by andrewrynhard** [comment]
I got it deployed but never tried a VM. I actually plan on testing today.

**Comment by fabiand** [comment]
Pleae reopen if this is still an issue

**Comment by attila123** [comment]
Could somebody please confirm whether kubevirt actually works on top of containerd or not?

**Comment by attila123** [comment]
Meanwhile I heard from a colleague that kubevirt runs fine on Talos (which has containerd, no docker).

**Comment by LarsBingBong** [comment]
@attila123 KubeVirt also runs fine on [Harvester](https://github.com/harvester/harvester). It's an integral part of the Harvester project.

**Comment by eshenayo** [comment]
I had this same question. Yes, KubeVirt can run on a Kubernetes cluster that has containerd as the runtime:

![2-node-cluster-containerd-runtime](https://user-images.githubusercontent.com/8902109/155684631-0de9274c-adfd-4ff4-b519-4aae6a11ece7.png)

Installed KubeVirt, services running:

![kubevirt-svcs](https://user-images.githubusercontent.com/8902109/155684962-1a38ea58-87d0-4a00-b385-8763882fe37e.png)

Deployed a VM using [this lab tutorial](https://kubevirt.io/labs/kubernetes/lab1.html), and successfully deployed:

![kubevirtvm-start](https://user-images.githubusercontent.com/8902109/155685737-13bc9664-e594-4e7f-a90f-fe8860d42f0c.png)

**Comment by jiangxiaobin96** [comment]
I build kubevirt and meet the following error:
```
no working container runtime found. Neither docker nor podman seems to work.
```
My container runtime is containerd
```
$ containerd --version
containerd containerd.io 1.6.28 ae07eda36dd25f8a1b98dfbf587313b99c0190bb
```
How to make and install by containerd?

**Comment by rmohr** [comment]
Hi, I think you are just missing the `docker` binary which can make use of containerd. Once you have it installed, you should be good to go.
