### ISSUE TITLE
Update install documentation RELEASE=v0.17.0 and add a link to release list

### ISSUE THREAD

**Issue by andreaskaris** [kubevirt/kubevirt#2910]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
https://kubevirt.io/user-guide/docs/latest/administration/intro.html

Documentation states $ export RELEASE=v0.17.0 but does not give a link to list of releases nor does it mention what the most recent release is. "Noobs" like me will blindly copy/paste what's in the doc and run into issues later down the road.

**What you expected to happen**:
Update install documentation RELEASE=v0.17.0 and add a link to release list

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Perhaps add a link to https://github.com/kubevirt/kubevirt/releases ?

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mjschmidt** [comment]
I suggest a documentation update proposal here via a pull request:
https://github.com/kubevirt/user-guide
