### ISSUE TITLE
kubevirt build: fails to build on a slow internet connection

### ISSUE THREAD

**Issue by hw-claudio** [kubevirt/kubevirt#2929]
Hi,

this is probably a FEATURE REQUEST, to allow building kubevirt (make) also on a slow internet connection.

https://github.com/kubevirt/kubevirt/blob/master/docs/getting-started.md

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

/kind enhancement

**What happened**:

I tried to build on a slow 1Mbs connection. Errors out with tcp reset while downloading a 400MB layer, on restart it tries to restart downloading from the beginning.

**What you expected to happen**:

I would have expected the build system to already contain all necessary basic components required, without requiring an internet connection at all, but if the connection is necessary I would have expected to be able to slowly download the whole image (got tcp reset instead), or/and being able to resume the downloads.

**How to reproduce it (as minimally and precisely as possible)**:

Use a 1mbps connection,

$ make

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):

commit cbf1c220fd58ebbbeb36e4c902fd6031739efaa2
Date:   Tue Dec 10 09:42:25 2019 +0100

- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):

openSUSE Tumbleweed

- Kernel (e.g. `uname -a`):
Linux localhost.localdomain 5.3.12-1-default #1 SMP Thu Nov 21 07:21:43 UTC 2019 (a6f6081) x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by hw-claudio** [comment]
Work around: I could work around the large downloads and number of layers by using docker daemon options:

DOCKER_OPTS="--max-concurrent-downloads=1 --max-concurrent-uploads=1"

to work around the timeout on pulling the concurrent layers

**Comment by rmohr** [comment]
I am surprised that you did not run into issues when bazel tried to download its dependencies after the docker download.

Just in case you run into issues there too, you can create a `.bazelrc` file with this content:

```
common --remote_max_connections=10
```
