### ISSUE TITLE
How often is expected to update the KubeVirt operator in operatorhub.io?

### ISSUE THREAD

**Issue by alosadagrande** [kubevirt/kubevirt#2932]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind enhancement

I just started to deploy OKD 4.3 with KubeVirt community operator. However, currently the version in operatorhub.io is running KubeVirt 0.18.1 which is quite old. Note that last week version 0.24 of KubeVirt has been released with some new features (pause/unpause, vnc fixes...)

My questions are:

* how often is expected to update the KubeVirt community operator so my OKD KubeVirt installation can be updated (manually or automatically) ?
* is there any other method to update an already deployed KubeVirt community operator in OKD?

**Comment by cynepco3hahue** [comment]
Probably we need to add it to the travis release script and I thought we have one, @slintes do we update it automatically or we need a manual intervention?

**Comment by slintes** [comment]
No, it's not automated. You need to create a PR on the community operator repo for every new version manually.
However, I see that HCO is working on a community operator as well [0]. IMHO it would be confusing to have both. Maybe it makes sense to delete the KubeVirt standalone operator from operator hub, and offer an option to only deploy KubeVirt for the HCO operator?

/cc @fabiand 

[0] https://github.com/kubevirt/hyperconverged-cluster-operator/issues/365#issuecomment-563982712

**Comment by rmohr** [comment]
> However, I see that HCO is working on a community operator as well [0]. IMHO it would be confusing to have both. Maybe it makes sense to delete the KubeVirt standalone operator from operator hub, and offer an option to only deploy KubeVirt for the HCO operator?

Maybe. However I would be against it right now. HCO is not really tested.

**Comment by slintes** [comment]
> > However, I see that HCO is working on a community operator as well [0]. IMHO it would be confusing to have both. Maybe it makes sense to delete the KubeVirt standalone operator from operator hub, and offer an option to only deploy KubeVirt for the HCO operator?
> 
> Maybe. However I would be against it right now. HCO is not really tested.

Sure, not before they are ready for it :)

**Comment by slintes** [comment]
So:
1. Is this the approach we want to go (replacing KV with HCO)?
2. If so, how long does it take for HCO to be ready, and do we want to wait, or publish an update to the KubeVirt operator?
3. If not, publish an update as soon as possible

**Comment by fabiand** [comment]
Yeah, we really should solve the situation on operatorhub.

Help is appreciated to resolve the situation.

**Comment by fabiand** [comment]
One question here is if kubevirt/kubevirt should be published there or rather hco. Today @orenc1 et al just enabled regular publishment of HCO to operatorhub.io - HCO is including KubevIrt and some helpful other projects.

**Comment by orenc1** [comment]
> One question here is if kubevirt/kubevirt should be published there or rather hco. Today @orenc1 et al just enabled regular publishment of HCO to operatorhub.io - HCO is including KubevIrt and some helpful other projects.

Correct.
Kubevirt, along with its supporting operators, are published in operatorhub.io periodically and automatically when a version is tagged in HCO repository.
The last published version is 1.6.0, which contains kubevirt v0.49.0:
https://github.com/kubevirt/hyperconverged-cluster-operator/releases/tag/v1.6.0
https://operatorhub.io/operator/community-kubevirt-hyperconverged

/close
