### ISSUE TITLE
virt-handler has to register it's port on the cluster

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#294]
In order to allow imperative flows, like 

 * console access
 * vnc/spice security setup

and others, we need the possibility to connect from virt-api to virt-handler. The node port for virt-handler, is at the moment hard-coded in virt-api, but not in virt-handler.

The kubelet solves this by adding an entry to `v1.Node.NodeStatus.daemonEndpoints`. However, we can't use this technique our-self, since this is a struct, and not a map. 

In order to allow virt-handler to either run in the host network namespace, or the pod network namespace, it still makes sense to report it at the node. Maybe as an annotation: `kubevirt.io/virtHandlerPort`. Another possibility would be reporting it on the pod.

The flow would be:

1) virt-handler starts
2) virt-handler reads in it's supplied port config
3) virt-handler updates the node/pod

Whenever we want to actively talk to virt-handler, we would look up that annotation.

**Comment by rmohr** [comment]
Currently the one interesting position in virt-api: https://github.com/kubevirt/kubevirt/blob/4bd24e60886cbe6ef87f52249ee837fb77532eb5/pkg/virt-api/rest/console.go#L102

**Comment by berrange** [comment]
> In order to allow virt-handler to either run in the host network namespace, or the pod network namespace, i

The PR that removes use of the separate network namespace will prevent virt-handler running in the host namespace. So it seems it is sufficient to get the IP associated with the virt-handler POD.

**Comment by rmohr** [comment]
> The PR that removes use of the separate network namespace will prevent virt-handler running in the host namespace. So it seems it is sufficient to get the IP associated with the virt-handler POD.

Yes. Can be that we change that back an forth a few more times, with networking coming up ...

If we work with the assumption that virt-handler will only ever be run inside a Pod, then it is probably better to put the annotation on the Pod. Then we have everything we need on the Pod:

 * Pod IP (if in the Pod namesapce)
 * Node IP (if on the Host namespace)
 * Relevant Port

If we go with the annotation on the Port, then it is better to wait with this task until #242 is done.

**Comment by fabiand** [comment]
@rmohr couldn't we rely on DNS SRV lookup sas explained here https://kubernetes.io/docs/concepts/services-networking/service/#dns ?

**Comment by rmohr** [comment]
@fabiand While I also think that kube-dns is just a de-facto part of Kubernetes, although it is optional, I would find it better and easier, to share such information through the API, like Kubernetes itself. I would for instance expect, that you can connect to a console, even if kube-dns is currently down. Thoughts?

**Comment by fabiand** [comment]
To me KubeDNS is an integral part of the system which we can rely on.

I'm not sure tho what approach - DNS or API - is a better fit.
Maybe worth to discuss both.

**Comment by rmohr** [comment]
Would you want to add your own entries, or just use the service as provided by Kubernetes? 

If we use the ones provided by kubernetes, we would have to make sure that pod dns names are enabled, and still query for the actual pod, to get it's IP address, so that we can use the pod dns entry. Another option would be a headless service, but that would involve, that we would have to have an extra controller, which listens for new virt-handler pods, and creates headless services on the fly for them.

But maybe I misunderstand how you would want  to do that.

**Comment by bond95** [comment]
I think better solution is API, cause it's more reliable than services.

**Comment by fabiand** [comment]
My idea is not fully baked, but I thought about the following

1. Create a headless service with named ports for the virt-handler
```yalm
kind: Service
apiVersion: v1
metadata:
  name: virt-handler
spec:
  selector:
    daemon: virt-handler
  ports:
    - name: ctl
      protocol: tcp
      port: 4242
    - name: proxy
      protocol: tcp
      port: 4243
  clusterIP: None   
```

2. Use the fqdn `_ctl._tcp.virt-handler` or `_proxy._tcp.virt-handler` or `virt-handler` in our API server to find all handlers
We already know the ports to connect to, because they were defined in the service.

This works for every DNS client, i.e. `nslookup` in a busybox container running in a pod:
```bash
/ # nslookup _proxy._tcp.virt-handler
Server:    10.0.0.10
Address 1: 10.0.0.10 kube-dns.kube-system.svc.cluster.local

Name:      _proxy._tcp.virt-handler
Address 1: 10.1.0.7 virt-handler   <--- ALL HANDLERS BELOW, STARTING HERE
Address 2: 10.1.0.8
```

Two benefit are that we don't have maintenance costs (any doc to update) and that it integrates well, because DNS is already a pretty much established standard.
Whenever a handler goes away, this will directly be reflected in DNS, because the contents are derived from the API server.

**Comment by rmohr** [comment]
@fabiand  a few questions and thoughts on that:

 1) how would you find out from the myltiple a-records you get, which one is on which host?
 2) For the base infra I would prefer, if the handler port detection does not depend on the port name in the handler yaml. I would prefer a stronger contract, between the handler and the cluster.
 3) Regarding the docs update maintenance cost, I can't follow that argument. Wouldn't I have to also document this dns discovery?
 4) How would you reflect the node name in the dns entries? The daemon set creates the pods, the headless service creates a dns entry based on the pod name, and then?
 5) As said before, I also see the dns addon as a de-facto part of k8s, but still it is a small advantage, to not have to depend on this for basic tasks. It can be down, or (very seldom) not be there. But I don't see that as a killer argument.

**Comment by bond95** [comment]
@rmohr @fabiand Now I try to do it with annotations, write current virt-handler port to all pods annotations.

**Comment by fabiand** [comment]
1. The service implies the exported ports, thus we know the port in advance
2. How is a document stating a port a harder contract than an agreement on a port upfront?
3. Document updates - I mean, if we'd be using (which isn't the case) a separate document to maintain these information si.e. a virthandler object, then we'd need to maintain this object.
4. Not sure about the question. But all handlers would use the same port, thus no need to differentiate between them. However, you can access a specific pod by using `pod-hostname.optional-subdomain.my-ns.svc.cluster.local` - the service however is created without the hostname in the fqdn.
5. Right

Let me note that we now register ports in annotations, even that we have the ability to "register" ports by name in the pod spec, as well as with services.

**Comment by fabiand** [comment]
@bond95 where do you stand with this issue?

**Comment by bond95** [comment]
@fabiand https://github.com/kubevirt/kubevirt/pull/357

**Comment by fabiand** [comment]
Thanks, please make sure to refernce this issue in a commit msg of your PR.

**Comment by cynepco3hahue** [comment]
I think the issue does not actual anymore and we can close it.

**Comment by simon3z** [comment]
@fabiand should we close this one?

**Comment by fabiand** [comment]
Closing this one in favor of #176 - even if it's not a total overlap.
