### ISSUE TITLE
[Question] `virt-operator` for ARM64?

### ISSUE THREAD

**Issue by chendave** [kubevirt/kubevirt#2948]
**Is this a BUG REPORT or FEATURE REQUEST?**:

**What happened**:
Does `kubevirt/virt-operator` currently only available for X86? If yes, where is the `Dockerfile` and source for the image?  or the gaps to build the image for ARM64?

**What you expected to happen**:
kubevirt should be able to use on ARM64 as well.

**How to reproduce it (as minimally and precisely as possible)**:
`kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${KUBEVIRT_VERSION}/kubevirt-operator.yaml` 
and the container crashed,

``` 
kubectl get pods -n kubevirt
NAME                            READY   STATUS             RESTARTS   AGE
virt-operator-bd7d6c76b-4hkl5   0/1     CrashLoopBackOff   16         59m
virt-operator-bd7d6c76b-p9c5f   0/1     CrashLoopBackOff   16         59m

# kubectl logs virt-operator-bd7d6c76b-p9c5f -n kubevirt
standard_init_linux.go:211: exec user process caused "exec format error"
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): latest
- Kubernetes version (use `kubectl version`): latest
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): all
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by slintes** [comment]
Hey,

kubevirt uses bazel as build system, including container images, see e.g. https://github.com/kubevirt/kubevirt/blob/master/cmd/virt-operator/BUILD.bazel#L34. So there are no Dockerfiles.

For ARM64, seems there were some people busy with adding support for it, see https://github.com/kubevirt/kubevirt/issues/1376.

**Comment by zhlhahaha** [comment]
> /cc @zhlhahaha is that image already supported on ARM?

Not yet. Please refer to the patch https://github.com/kubevirt/kubevirt/pull/3415

**Comment by rmohr** [comment]
/close

We made quite some progress lately.
Let's continue tracking the remaining work in #3558.
