### ISSUE TITLE
Evacuate QEMU logs from virt-launcher pod

### ISSUE THREAD

**Issue by enp0s3** [kubevirt/kubevirt#2953]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:
A virt-launcher pod is being deleted because the QEMU crashed. This happens fast and if "spec.running" is True it happens in loops. Currently there is no option to treat the QEMU logs.

**What you expected to happen**:
Print QEMU logs to the STDOUT and evacuate them to virt-handler for bug tracking.

**How to reproduce it (as minimally and precisely as possible)**:
Run Windows 2019 VM and enable kernel debugging via Network
In order to do so run the following commands as administrator from the command prompt:
bcdedit /debug on
bcdedit /dbgsettings net hostip:192.168.0.12 port:50000 key:this.key.isnt.secure

**Comment by slintes** [comment]
Hey, you can enable verbose logs with a `debugLogs: "true"` label on the VMI. Then you can try to get the logs from the *previous* virt-launcher pod with the `-p` flag of `kubectl logs`. Does that help?

**Comment by rmohr** [comment]
Another issue still is that the qemu logs are only written to a file. I think we should configure virtlogd to log to stderr and write it to our logs.

**Comment by fabiand** [comment]
@rmohr could you specify where the logs should be written to?

**Comment by rmohr** [comment]
They should be written to stderr (converted to structured logs, the same way like we do it for libvirt).

**Comment by victortoso** [comment]
Is anyone working on this? If not I'll be trying to fix it this week

**Comment by rmohr** [comment]
I don't think so. Feel free to work on it. :)
