### ISSUE TITLE
Export VM metrics to the cluster

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#296]
> As an admin or privileged user, I want to be able to view the VM metrics like I view Pod metrics, and even integrate them into my visualization tools

There are certain metrics (TBD) which are distinct to VMs.
VM metrics should be collected on the host, and be provided to cluster level facilities for further consumption.

it would be important that the metrics are provided alongside the Pod metrics.

**Comment by michalskrivanek** [comment]
@mojaves has some oVirt code which can grow into this. @fabiand, do you have any more ideas/thoughts/directions about the matter already?

**Comment by fabiand** [comment]
Yes, there are some additional thoughts:

Kubernetes (kubelet) has the ability to provide gather and export application or custom metrics form containers (see https://github.com/google/cadvisor/pull/1018 for some details, still looking for official documentation).

This effectively decouples how we gather the metrics, and it aligns the export process on the kubelet.
Thus we'd have a single point - kubelet - per node, which is used to gather metrics.
This mechanism can be used by other kubernetes ocmponents i.e. the cluster auto-scaler or pod-autocsaler to come up with decisions.

So this would be a valuable first step: A pod collecting custom metrics, and providing them throught the kubelet.

Another big thing is to define the metrics we want to expose, and find good names for them. As the names will be something higher level consumers will be tied to.
This second part should be part of a proposal to have a defined set of virtualization metrics, which consumers can rely on.

**Comment by fabiand** [comment]
Additonal link https://github.com/directxman12/k8s-prometheus-adapter

**Comment by rmohr** [comment]
@fabiand I think you are looking for that link: https://github.com/google/cadvisor/blob/master/docs/application_metrics.md

**Comment by fromanirh** [comment]
I want to work on this, I managed to free enough time to seriously tackle this.

**Comment by fromanirh** [comment]
PS: please use @fromanirh handle to ping me

**Comment by fabiand** [comment]
Cool. Please join us on our weekly meetings (on monday) to sync on the status :)

**Comment by fabiand** [comment]
Two additional links:
- Exporting custom resource metrics: https://github.com/kubernetes-incubator/custom-metrics-apiserver
- Consuming custom resource metrics: https://github.com/kubernetes/metrics

**Comment by fabiand** [comment]
For now we settled with only consuming the pod metrics.

Thus closing this issue for now.

**Comment by fabiand** [comment]
For now we use the pod metrics.

if we want - in future - to expose VM specific metrics, then we can use Kubernetes application Or sutom metrics for this.

Closing this bug for now.
