### ISSUE TITLE
Deletion of Kubevirt CR hangs

### ISSUE THREAD

**Issue by omeryahud** [kubevirt/kubevirt#2961]
/kind bug

**What happened**:
Manually creating Kubevirt CR and deleting it while its status is still `Deploying` hangs 

**What you expected to happen**:
Kubevirt CR to be deleted

**How to reproduce it (as minimally and precisely as possible)**:
- Install Kubevirt on a cluster
- Delete Kubevirt CR
- Create Kubecirt CR
- Delete Kubevirt CR while it is still in the `Deploying` status

**Environment**:
- KubeVirt version (use `virtctl version`):
`Client Version: version.Info{GitVersion:"v0.24.0-33+5cff27bc675c5d-dirty", GitCommit:"5cff27bc675c5d5820f2f7d14c829276c0c9013b", GitTreeState:"dirty", BuildDate:"2020-01-02T15:21:15Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"{gitVersion}", GitCommit:"{gitCommit}", GitTreeState:"{gitTreeState}", BuildDate:"{buildDate}", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}`

- Kubernetes version (use `kubectl version`):
`Client Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:08:12Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"13", GitVersion:"v1.13.3", GitCommit:"721bfa751924da8d1680787490c54b9179b1fed0", GitTreeState:"clean", BuildDate:"2019-02-01T20:00:57Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}`

**Comment by joekhoobyar** [comment]
I have the same issue. 

Is there a workaround for this?  It's been deleting for 12 hours now.

**Comment by joekhoobyar** [comment]
Checking the documentation, I found this, at the end of the [Delete](https://kubevirt.io/user-guide/docs/latest/administration/intro.html#delete) section of the docs:

```
kubectl -n kubevirt patch kv kubevirt --type=json -p '[{ "op": "remove", "path": "/metadata/finalizers" }]'
```

Running the above command worked for me.

@omeryahud - can you try that and see if it works?  If so, we should probably close the bug.

**Comment by mjschmidt** [comment]
I am not sure if a pull request was the right move for this, but I attempted to add documentation for making certain clean up was successful in situations like this. The following script deletes all objects in a given namespace with labels kubevirt uses:
https://github.com/kubevirt/user-guide/pull/287
