### ISSUE TITLE
How can I assign a QAT vf to a Kubevirt vm?

### ISSUE THREAD

**Issue by leyao-daily** [kubevirt/kubevirt#2965]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Feature Request
> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
I want assign a QAT vf to Kubevirt vm 
**What you expected to happen**:
I can see this pci device when i log into the kubevirt vm
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by leyao-daily** [comment]
Is kubevirt support other types of device plugin?
I have qat device plugin and it advertise resource name : qat.intel.com/generic
I add it to spec.containers.resource.requests/limits with value 1
and nothing happened.

**Comment by leyao-daily** [comment]
> Is kubevirt support other types of device plugin?
> I have qat device plugin and it advertise resource name : qat.intel.com/generic
> I add it to spec.containers.resource.requests/limits with value 1
> and nothing happened.

It only assign the vf to the pod but not to the vm managed by libvirt in this pod.
Is there any necessary configuration to enable qat assigned to vm?

**Comment by rmohr** [comment]
@phoracek @qinqon maybe you can help out here?

**Comment by phoracek** [comment]
@leyao-daily I'm not at all familiar with QAT, but I'm affraid there is no way to get it into KubeVirt VMs at the current state.

@rmohr we don't have any support for device passthrough, do we? Are there any plans to do so? I can't say I have a good idea how to do a generic support for DPs. It would probably need similar API to network? Request a DP and then specify how to mount it into the VM.

For SR-IOV, the passthrough is done via a combination of DP and CNI. It can be used in VMI via a specific Interface option https://github.com/visheshtanksale/kubevirt/blob/7dd6e740d184fd27f4c4b1d0b81795db176fbea4/api/openapi-spec/swagger.json#L5042.

For GPU we have also a dedicated field in the VMI https://github.com/visheshtanksale/kubevirt/blob/7dd6e740d184fd27f4c4b1d0b81795db176fbea4/api/openapi-spec/swagger.json#L4466.

**Comment by leyao-daily** [comment]
> @leyao-daily I'm not at all familiar with QAT, but I'm affraid there is no way to get it into KubeVirt VMs at the current state.
> 
> @rmohr we don't have any support for device passthrough, do we? Are there any plans to do so? I can't say I have a good idea how to do a generic support for DPs. It would probably need similar API to network? Request a DP and then specify how to mount it into the VM.
> 
> For SR-IOV, the passthrough is done via a combination of DP and CNI. It can be used in VMI via a specific Interface option https://github.com/visheshtanksale/kubevirt/blob/7dd6e740d184fd27f4c4b1d0b81795db176fbea4/api/openapi-spec/swagger.json#L5042.
> 
> For GPU we have also a dedicated field in the VMI https://github.com/visheshtanksale/kubevirt/blob/7dd6e740d184fd27f4c4b1d0b81795db176fbea4/api/openapi-spec/swagger.json#L4466.

Thanks. If i want kubevirt support qat, I can change the source code and rebuild it? I think it is familliar with the sriov and gpu support. So is there any guide to build from source code? Just run make & make push ?

**Comment by rmohr** [comment]
Almost. You will only also have to point the build system to your container registry. See https://github.com/kubevirt/kubevirt/blob/master/docs/getting-started.md#i-just-want-it-built-and-run-it-on-my-cluster.

**Comment by rmohr** [comment]
This should work now. See https://github.com/kubevirt/kubevirt/pull/2980#issuecomment-808064426 for details.
