### ISSUE TITLE
virt-handler daemonset can GET Secrets in all namespaces making it cluster root

### ISSUE THREAD

**Issue by ericchiang** [kubevirt/kubevirt#2967]
**Is this a BUG REPORT or FEATURE REQUEST?**

/kind enhancement

**What happened**:

The kubevirt operator deploys a handful of manifests to the cluster. Many of the created RBAC rules are powerful, but ideally you could isolate the dangerous ones to dedicated nodes. Unfortunately, the virt-handler DaemonSet's ClusterRole lets it GET Secrets in all namespaces, so it can dump any other ServiceAccountSecret. It doesn't seem possible to deploy kubevirt without this.

https://github.com/kubevirt/kubevirt/blob/v0.24.0/manifests/generated/rbac-kubevirt.authorization.k8s.yaml.in#L309-L315

**What you expected to happen**:

I wouldn't expect a daemonset, deployed to every instance, to have credentials which can root the cluster. This means compromising any node is game-over.

**How to reproduce it (as minimally and precisely as possible)**:

N/A

**Anything else we need to know?**:

Is there a reason that this component needs this power? Could it be contained to a single namespace instead?

**Environment**:

N/A

**Comment by rmohr** [comment]
The only reason as far as I know is  the cloud-init feature. In contrast to our normal `secret` volume support it does not mount the secret on the pod and then create the no-cloud source from it. Instead we directly GET the secret.

We can change that to also just mount the secret and restrict the GET to the specific secret which holds a virt-handler certificate.

Will try to do a PR this week.

Thanks for reporting.

**Comment by ericchiang** [comment]
Great to hear! So virt-api would just render a pod with the secrets mounted and virt-launcher would read them from disk and pass them to the VM?

**Comment by rmohr** [comment]
> Great to hear! So virt-api would just render a pod with the secrets mounted and virt-launcher would read them from disk and pass them to the VM?

Exactly.

**Comment by fabiand** [comment]
@danielBelenky I wonder if this would be interesting for you. Changing the current cloud init implementation to mount the secret instead of creating a disk from it ...

**Comment by fabiand** [comment]
@ericchiang thanks for reporting this, as @rmohr noted it's a bug and we try to get it fixed soon.

**Comment by ericchiang** [comment]
Thanks and no worries on timeline. If you can point me to the right places in the code, I'm happy to try to send a PR too.

**Comment by fabiand** [comment]
Maybe @danielBelenky has already started working on it - did you?
if not then patches are welcome - and/or reviews!

**Comment by danielBelenky** [comment]
I'm starting to work on it today.

**Comment by danielBelenky** [comment]
Hey,
https://github.com/kubevirt/kubevirt/pull/3001 moves the responsibility to read the secret
from virt-handler to virt-launcher. virt-controller renders the launcher pod with corresponding
volume mount.
In the same PR I also revoked the permission to GET secrets from virt-handler .
