### ISSUE TITLE
Cleanup the public Domain spec exposed attributes

### ISSUE THREAD

**Issue by berrange** [kubevirt/kubevirt#297]
The current public domain spec object exposes alot of attributes that would allow a user to takeover the compute host. These needed to be stripped out in accordance with the notes in docs/vm-configuration.md

**Comment by fabiand** [comment]
Isn't this part of the larger patchset around #244?

**Comment by fabiand** [comment]
This bug is now fixed after we change the maping to not do a 1:1 mapping from VM Spec to domxml anymore.

Today all fields in the VM Spec are "whitelsited" or "escaped."
