### ISSUE TITLE
Our build environement still contains python 2.7 traces

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#2985]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind enhancement

**What happened**:

```shell
$ make cluster-sync
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
```

Reported by @oshoval .
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by oshoval** [comment]
hack/kubevirt-builder/Dockerfile:RUN pip install j2cli && pip3 install operator-courier==1.3.0

```
Step 5/7 : RUN pip install j2cli && pip3 install operator-courier==1.3.0
 ---> Running in 8294675fd3ec
DEPRECATION: Python 2.7 will reach the end of its life on January 1st, 2020. Please upgrade your Python as Python 2.7 won't be maintained after that date. A future version of pip will drop support for Python 2.7.
WARNING: Running pip install with root privileges is generally not a good idea. Try `pip install --user` instead.
Collecting j2cli
```
