### ISSUE TITLE
Version to use

### ISSUE THREAD

**Issue by sheetaljoshi** [kubevirt/kubevirt#299]
Which version of kubernetes the master branch compliant to? I am running kubernetes cluster via kubeadm and the steps doesn't work with either stable or latest versions. Now I am back at using Kubernetes 1.5.6 version but virt-controller and virt-handler throws these errors.

kubectl logs -f virt-handler-6793p
E0707 13:42:27.509285       1 reflector.go:201] kubevirt.io/kubevirt/pkg/kubecli/controller.go:167: Failed to list *v1.VM: User "system:serviceaccount:default:default" cannot list vms.kubevirt.io in the namespace "default". (get vms.kubevirt.io)

kubectl logs -f virt-controller-3230119827-jjz1z
E0707 11:58:42.154691       1 reflector.go:201] kubevirt.io/kubevirt/pkg/informers/virtinformers.go:90: Failed to list *v1.VM: User "system:serviceaccount:default:default" cannot list vms.kubevirt.io in the namespace "default". (get vms.kubevirt.io)

virsh list doesn't list any VMs. Althought kubectl get vms show test testvm, but there isn't a pod created.

**Comment by rmohr** [comment]
Hi @sheetaljos,

From the kubernetes perspective, it work starting from 1.6+. I think that in 1.5, Migration will not work, because the anti affinity support changed. The rest should still work.

The errors you see, mean that the service account which your deployment uses for kubevirt does not give the kubevirt components all the privileges they need. Try 

```
# ATTENTION, this gives way too much privileges
kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
kubectl create clusterrolebinding add-on-default-admin --clusterrole=cluster-admin --serviceaccount=default:default
``` 
We need to provide more fine-grained permissions. I will open an issue to track it.

BTW. which host OS are you using?

**Comment by rmohr** [comment]
Created #301

**Comment by sheetaljoshi** [comment]
So essentially I should be able to use kubernetes stable version and kubevirt master branch? And I am testing on CentOS Linux release 7.3.1611 (Core). I have modified version of https://github.com/kubevirt/demo/blob/master/data/bootstrap-kubevirt.sh to bootstrap kubevirt with 1.5.6. I want to run it on ubuntu 16.04 in production, do you maintain install guides for ubuntu some where?

**Comment by berrange** [comment]
Given where we are in the development, our general intention is going to be that git master of kubevirt will target latest k8s release only, and not try to maintain compat with previous releases. Currently it should work with 1.6.x and 1.7.x since 1.7.x only just released, but going forward it'll likely only work with 1.7.x.  We're certainly not intending to keep it working with 1.5.x.

**Comment by rmohr** [comment]
1.6 and 1.7 should currently work. I think it is better if you follow [setup_kubernetes_common.sh](cluster/vagrant/setup_kubernetes_common.sh),  [setup_kubernetes_master.sh](cluster/vagrant/setup_kubernetes_master.sh) and [setup_kubernetes_common.sh](cluster/vagrant/setup_kubernetes_node.sh). It is up to date. But in general this just does what the kubeadm manual says, with small workarounds here and there.

In general you just bootstrap kubernetes with e.g. kubeadm, select a network provider, run `make manifests` and then deploy the manifests. We are trying to not modify the host, so it *could* just work on Ubuntu. However I guess that there is a good chance, that you run into minor issues like https://github.com/kubevirt/libvirt/issues/4. It would be great to hear how it goes.

**Comment by sheetaljoshi** [comment]
I tried to run follow above steps via vagrant up and make vagrant-deploy. But after I ran ./cluster/kubectl.sh delete -f cluster/vm.json all the pods started failing with this error. [root@master kubevirt]# ./cluster/kubectl.sh logs -f ^C
[root@master kubevirt]# ./cluster/kubectl.sh logs -f libvirt-n64gl libvirtd
Error from server: Get https://192.168.121.43:10250/containerLogs/default/libvirt-n64gl/libvirtd?follow=true: dial tcp 192.168.121.43:1
0250: connect: network is unreachable
[root@master kubevirt]#

**Comment by rmohr** [comment]
I don't think that there is a connection between the vm deletion and this error. The error you see here says that you can't reach the apiserver in vagrant. Could you try ssh into a vagrant VM or restart the vagrant VMs ( vagrant halt && vagrant up)?

**Comment by sheetaljoshi** [comment]
So when I tried vagrant halt and vagrant up that issue a new ip and all the pods starts failing because not able to reach kube-api server. I shall post details soon once I have environment running.

**Comment by fabiand** [comment]
Today we can use Kube 1.7 (we actually need it soon).

Can you complete delete the vagrant environment and rebuild it? @sheetaljoshi

**Comment by fabiand** [comment]
You can also take a look at the demo to see how to deploy kubevirt on a stock kubernetes cluster - https://github.com/kubevirt/demo.
