### ISSUE TITLE
Put all cloud admin controlled kubevirt resources in kubevirt namespace

### ISSUE THREAD

**Issue by berrange** [kubevirt/kubevirt#300]
Currently the manifests we include put all resources in the "default" namespace. In an anticipated production like deployment, all the kubevirt resources that are controlled by the cloud admin would want to be in a separate namespace than the tenant user created resources, so they are not visible or accessible to tenants by default. 

This entails updating the yaml.in files in manifests/ to add the 'kubevirt' namespace to them. The exception would be the PersistentVolumeClaim resources which should remain in the default namespace, since they must be accessible to the testvm resource.

**Comment by berrange** [comment]
It might be also worth putting the 'testvm' resource & PVCs in a "demouser" namespace in fact, so that we flush out any code that's mistakenly assuming they are in the default namespace.

**Comment by rmohr** [comment]
Having our own namespace makes sense, we have to wait for #249, which does the preparations for this switch.

I think, regarding the PVCs and the testvm, the key is, to not specify the namespace at all. Then they get created in whatever your kubectl credentials have configured as their default namespace. I would leave them there. For the functional tests, we probably want to make it more explicit which namespaces to use for what, but #249 is preparing the ground.

**Comment by rmohr** [comment]
Ok, so in order to be fully accepted by the k8s system as a core add-on, it seems to be necessary to run our components in `kube-system`. See https://kubernetes.io/docs/tasks/administer-cluster/guaranteed-scheduling-critical-addon-pods/ for more details. @fabiand thx for the link.
