### ISSUE TITLE
Add fine grained service account permissions to the deployments (RBAC)

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#301]
At the moment, we give all kubevirt components admin rights in the Vagrant setup:

```
# TODO better scope the permissions, for now allow the default account everything
kubectl create clusterrolebinding add-on-cluster-admin --clusterrole=cluster-admin --serviceaccount=kube-system:default
kubectl create clusterrolebinding add-on-default-admin --clusterrole=cluster-admin --serviceaccount=default:default
```

Instead of that, we should have different service accounts for the controller, virt-api and virt-handler. Further, the roles and the role bindings should be part of the yaml manifest in the `manifests` folder.

**Comment by fabiand** [comment]
See also #62
