### ISSUE TITLE
OOMKiller shutting down kubevirt-infra sidecar causing VM shutdown

### ISSUE THREAD

**Issue by plwhite** [kubevirt/kubevirt#3029]
**BUG REPORT**:

/kind bug

**What happened**:

Running on Azure, sequence of events was the following.

- kubevirt-infra container died with OOMKiller
- VM running in hypervisor did clean shutdown
- VMI vanished

**What you expected to happen**:

Neither of the first two.

- The OOMKiller is likely because the pod spec for the kubevirt-infra container has slightly too low a limit on memory. Azure appears to be a bit trigger happy enforcing this limit.
- The clean shutdown is rather odd. I'd guess that the underlying logic is that with kubevirt-infra having blown up, the handler decides that the VMI is sick, sends it a shutdown signal and blows it away. That is arguably correct behaviour given the initial error.

**How to reproduce it (as minimally and precisely as possible)**:

The repro scenario appears to be to run on Azure (or somebody else would have noticed it!), and have a readiness probe on some port. The time from VMI creation to stopping is very uneven. I've seen it vary from a few minutes (so VM doesn't even always finish booting) to a few hours. There's some correlation in timing which I think is some Azure artifact.

I'm happy to test a fix or attempt to repro with a debug build.

**Anything else we need to know?**:

I just realised I am not on the latest kubevirt version; will repro on 0.25 today.

If you can tell me at how to change the memory limit on the sidecar, I'd be happy to test if just raising it slightly helps; I'm 90% sure that would make the problem go away.

**Environment**:
- KubeVirt version (use `virtctl version`): 0.22.0
- Kubernetes version (use `kubectl version`): 
- VM or VMI specifications: 
- Cloud provider or hardware configuration: AKS, standard cluster
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by plwhite** [comment]
I've confirmed that the bug happens in exactly the same way on KubeVirt 0.25. I forgot to mention kubernetes version in the original report - `v1.14.8`.

**Comment by slintes** [comment]
sounds familiar, Azure bite use earlier with OOMs: https://github.com/kubevirt/kubevirt/issues/2603

**Comment by plwhite** [comment]
Yes, indeed, and I expect there will be a similar fix. I'm in the process of testing to see if manually pushing up memory in the sidecar just makes the issue go away - will have provisional results for that later today.

**Comment by plwhite** [comment]
Running with an increased limit of 40Mi in the sidecar causes the issue to go away. I can't absolutely guarantee that I haven't just turned it from an issue that happens randomly about every hour or two to an issue that happens every few days - but it seems highly likely that this is the right fix.

~~~
diff --git a/pkg/virt-controller/services/template.go b/pkg/virt-controller/services/template.go
index 3d5231a38..0ea917623 100644
--- a/pkg/virt-controller/services/template.go
+++ b/pkg/virt-controller/services/template.go
@@ -870,7 +870,7 @@ func (t *templateService) RenderLaunchManifest(vmi *v1.VirtualMachineInstance) (
                        Resources: k8sv1.ResourceRequirements{
                                Limits: map[k8sv1.ResourceName]resource.Quantity{
                                        k8sv1.ResourceCPU:    resource.MustParse("1m"),
-                                       k8sv1.ResourceMemory: resource.MustParse("12Mi"), // this is the minimum memory limit for cri-o!
+                                       k8sv1.ResourceMemory: resource.MustParse("40Mi"), // this is the minimum memory limit for cri-o!
                                },
                        },
                        Command:        []string{"/usr/bin/tail", "-f", "/dev/null"},

~~~

**Comment by fabiand** [comment]
@plwhite do you mind opening a PR?

I think it's safe to increase this limit. On th elong run I'd hop ethat we can monitor the memory consumption and identify the real limit ..

**Comment by plwhite** [comment]
https://github.com/kubevirt/kubevirt/pull/3033
