### ISSUE TITLE
Would like to configure sidecars and initContainers for VMIs

### ISSUE THREAD

**Issue by plwhite** [kubevirt/kubevirt#3030]
**FEATURE REQUEST**:

/kind enhancement

**Motivation**:

There are use cases where I would like to run a VMI with a sidecar container or init container. For example, that container might:

- collect SNMP metrics from the VM and export over Prometheus API;
- retrieve and parse configuration that is then placed on a volume to be mounted into the VM;
- provide service mesh support or similar traffic routing function.

It would only be possible for the sidecar to interact with the VMI through a network interface or shared volume, but that's enough to provide quite useful function. If an init container could change the values to be provided to the VMI by interacting with cloud init, that would be a plus, though might be impossible to do.

My implementation idea is that the VMI spec would just allow specification of Kubernetes init containers and sidecars that could be added to the VMI without changing the core function of KubeVirt.

None of these use cases are "must haves" for me - they all just solve problems to which I have workarounds which are ugly to various degrees.

**Comment by plwhite** [comment]
It turns out that you can run sidecars, using the hookSidecar capability. I'm now investigating whether that gives me what I need, but it might be this was opened prematurely.

**Comment by fabiand** [comment]
@plwhite did the hooks provide everything you need?

**Comment by plwhite** [comment]
I moved on to other things before getting this working, but concluded that I probably could use hookSidecars. It would have been more complex than I first thought though, because the API for hookSidecars wasn't trivial.

Net conclusion is that I think making this simpler is still a valid request, but that the workarounds appeared possible.
