### ISSUE TITLE
Support changing scheduler name + allowing live migrations on PVCs with multiple node replicas.

### ISSUE THREAD

**Issue by azaiter** [kubevirt/kubevirt#3041]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind enhancement

**What happened**:
Can't set `schedulerName` for any `virt-launcher` pods from either VM or VMI resource types. Adding the option to do so will allow the usage of some storage-aware schedulers such as stork to only schedule to nodes that has the block replicas of the PVCs, and that gives kubevirt node failover advantage when using portworx as storage provider. Going that route will allow live migrations without needing to have shared PVCs (it's the current condition that triggers live migration flag) as shared PVCs have higher IO overhead than the PVCs node replicas.

**What you expected to happen**:
**How to reproduce it (as minimally and precisely as possible)**:
**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.25.0
- Kubernetes version (use `kubectl version`): v1.16.2
- VM or VMI specifications: both
- Cloud provider or hardware configuration: on prem, portworx as storage provider, stork as scheduler.
- OS (e.g. from /etc/os-release): RancherOS and CentOS
- Kernel (e.g. `uname -a`): 4.12
- Install tools: n/a
- Others: n/a

**Comment by rmohr** [comment]
Allowing to set the scheduler name should not be an issue. We can just add the scheduler field to our VMI spec and pass it through, to the pod.

Allowing live migrations with replicas sounds nice. Is it somehow visible on the PVC that it has node replicas? Could you point us to some documentation?

**Comment by azaiter** [comment]
Great.

As for your replicas question, setting up the replicas would be done in the [storage class that the PVC is created from (`parameters.repl`)](https://kubernetes.io/docs/concepts/storage/storage-classes/#portworx-volume). The PVC has a `spec.storageClassName` key that points to the storage class that has the replicas count.

**Comment by rmohr** [comment]
@azaiter #3258 should add the first step. Regarding to the PVCs. We would end up with PVCs which are readwriteonce, but where the scheduler can schedule pods to different hosts based on the replica count?

**Comment by azaiter** [comment]
@rmohr Let's take a simple 3 storage/compute nodes topology (A, B, and C):
if the PVC that is tied to a storage class has repl value of 2, two of the above nodes will have the volume replicated to them and synced at all times, say A and C.

If you schedule a pod using a scheduler that is aware of the storage state (like stork for example), it will only schedule the VMI pod to either A or C only. And if node A dies, and if the pod happens to be on it, the pod will get recreated to node C, thus preserving the VMI state on both nodes. 

That brings the second part of this issue request: allowing live migrations of PVCs that are created from a storage class that has `repl` value of > 1. So if you taint a node, the re-created pod will be automatically assigned to the second node that has the PVC, and the VMI will run as intended. I've recently tested this manually on about 6 VMIs and it appears to be working as intended (taint the node => delete the VMI pods => the recreated VMI pods on another node work as intended).

Hope that explains it. Thanks for the PR!
