### ISSUE TITLE
testVM stuck in "Scheduling" Phase

### ISSUE THREAD

**Issue by garretholland** [kubevirt/kubevirt#3042]
**Is this a BUG REPORT or FEATURE REQUEST?**:

>
kind bug

**What happened**:
Following your guide here: https://kubevirt.io/labs/kubernetes/lab1 when I get to the point where I want to console into a VM I can't because the VM is perpetually in "Scheduling" phase

**What you expected to happen**:
I'd expect to be able to console into the VM and the VM to be scheduled onto a node.

**How to reproduce it (as minimally and precisely as possible)**:
Follow your guide here: https://kubevirt.io/quickstart_minikube/ 
set the VM driver to hyperkit like so:
**minikube config -p kubevirt set vm-driver hyperkit**

Follow the guide here:
https://kubevirt.io/labs/kubernetes/lab1
run **kubectl get vmis**

My output:

```
NAME     AGE   PHASE        IP    NODENAME
testvm   17m   Scheduling
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
Client Version: version.Info{GitVersion:"v0.25.0", GitCommit:"b755c56f396ed880940821688eaddbd869e33897", GitTreeState:"clean", BuildDate:"2020-01-03T13:13:53Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"darwin/amd64"}

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"clean", BuildDate:"2020-01-23T14:21:36Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"darwin/amd64"}

- VM or VMI specifications:

- Cloud provider or hardware configuration: 
MacBookPro

- OS (e.g. from /etc/os-release):
MACOS Mojave 10.14.6

- Kernel (e.g. `uname -a`):
Darwin ALT02081 18.7.0 Darwin Kernel Version 18.7.0: Sun Dec  1 18:59:03 PST 2019; root:xnu-4903.278.19~1/RELEASE_X86_64 x86_64

- Install tools:
- Others:

**Comment by danielBelenky** [comment]
Hi,

Could you please post here the output of
`kubectl describe vmi testvm` ?

**Comment by garretholland** [comment]
` kubevirt kubectl describe vmi testvm
Name:         testvm
Namespace:    default
Labels:       kubevirt.io/domain=testvm
              kubevirt.io/size=small
Annotations:  kubevirt.io/latest-observed-api-version: v1alpha3
              kubevirt.io/storage-observed-api-version: v1alpha3
API Version:  kubevirt.io/v1alpha3
Kind:         VirtualMachineInstance
Metadata:
  Creation Timestamp:  2020-02-04T14:14:31Z
  Finalizers:
    foregroundDeleteVirtualMachine
  Generate Name:  testvm
  Generation:     4
  Owner References:
    API Version:           kubevirt.io/v1alpha3
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  VirtualMachine
    Name:                  testvm
    UID:                   59a44292-6ca9-449f-b928-e8668b04d885
  Resource Version:        1653
  Self Link:               /apis/kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/testvm
  UID:                     b32ff193-9e5c-4775-b543-1002533235d7
Spec:
  Domain:
    Devices:
      Disks:
        Disk:
          Bus:  virtio
        Name:   containerdisk
        Disk:
          Bus:  virtio
        Name:   cloudinitdisk
      Interfaces:
        Bridge:
        Name:  default
    Features:
      Acpi:
        Enabled:  true
    Firmware:
      Uuid:  5a9fc181-957e-5c32-9e5a-2de5e9673531
    Machine:
      Type:  q35
    Resources:
      Requests:
        Cpu:     100m
        Memory:  64M
  Networks:
    Name:  default
    Pod:
  Volumes:
    Container Disk:
      Image:              kubevirt/cirros-registry-disk-demo
      Image Pull Policy:  Always
    Name:                 containerdisk
    Cloud Init No Cloud:
      userDataBase64:  SGkuXG4=
    Name:              cloudinitdisk
Status:
  Conditions:
    Last Probe Time:       <nil>
    Last Transition Time:  2020-02-04T14:14:31Z
    Message:               0/1 nodes are available: 1 Insufficient devices.kubevirt.io/vhost-net.
    Reason:                Unschedulable
    Status:                False
    Type:                  PodScheduled
  Guest OS Info:
  Phase:      Scheduling
  Qos Class:  Burstable
Events:
  Type    Reason            Age   From                       Message
  ----    ------            ----  ----                       -------
  Normal  SuccessfulCreate  38s   virtualmachine-controller  Created virtual machine pod virt-launcher-testvm-5r9x5
➜  kubevirt`

**Comment by garretholland** [comment]
```
➜  kubevirt kubectl get pods --all-namespaces

NAMESPACE     NAME                               READY   STATUS    RESTARTS   AGE
default       virt-launcher-testvm-5r9x5         0/2     Pending   0          3m41s
kube-system   coredns-6955765f44-b4jnp           1/1     Running   0          10m
kube-system   coredns-6955765f44-l6wjx           1/1     Running   0          10m
kube-system   etcd-minikube                      1/1     Running   0          10m
kube-system   kube-addon-manager-minikube        1/1     Running   0          10m
kube-system   kube-apiserver-minikube            1/1     Running   0          10m
kube-system   kube-controller-manager-minikube   1/1     Running   0          10m
kube-system   kube-proxy-7ltrd                   1/1     Running   0          10m
kube-system   kube-scheduler-minikube            1/1     Running   0          10m
kube-system   storage-provisioner                1/1     Running   0          10m
kubevirt      virt-api-6466c4d445-cjrts          1/1     Running   0          5m51s
kubevirt      virt-api-6466c4d445-fp4r2          1/1     Running   0          5m51s
kubevirt      virt-controller-6888b8b99c-8mcqt   1/1     Running   0          4m57s
kubevirt      virt-controller-6888b8b99c-s996p   1/1     Running   0          4m57s
kubevirt      virt-handler-zcrp7                 1/1     Running   0          4m57s
kubevirt      virt-operator-67f8bb5dd9-58pfp     1/1     Running   0          9m26s
kubevirt      virt-operator-67f8bb5dd9-k9drp     1/1     Running   0          9m26s
```

**Comment by danielBelenky** [comment]
@garretholland thanks, it seems like you're missing the vhost-net device is not present on the node or we can't see it. Could you also provide logs from `virt-handler`?

**Comment by garretholland** [comment]
```
➜  kubevirt kubectl logs virt-handler-zcrp7
Error from server (NotFound): pods "virt-handler-zcrp7" not found
```
@danielBelenky Thank you for your help.

Am I using the correct command?

**Comment by danielBelenky** [comment]
`kubectl -n kubevirt logs virt-handler-zcrp7`

**Comment by garretholland** [comment]
Thanks!

```
➜  kubevirt kubectl -n kubevirt logs virt-handler-zcrp7
{"component":"virt-handler","hostname":"minikube","level":"info","pos":"virt-handler.go:187","timestamp":"2020-02-04T14:14:24.466322Z"}
{"component":"virt-handler","level":"info","msg":"Starting collector: node name=minikube","pos":"prometheus.go:395","timestamp":"2020-02-04T14:14:25.209787Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer vmiInformer","pos":"virtinformers.go:203","timestamp":"2020-02-04T14:14:25.209915Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer configMapInformer","pos":"virtinformers.go:203","timestamp":"2020-02-04T14:14:25.210035Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer CRDInformer","pos":"virtinformers.go:203","timestamp":"2020-02-04T14:14:25.210094Z"}
{"component":"virt-handler","level":"info","msg":"Starting virt-handler controller.","pos":"vm.go:547","timestamp":"2020-02-04T14:14:25.314315Z"}
{"component":"virt-handler","level":"info","msg":"metrics: max concurrent requests=3","pos":"virt-handler.go:350","timestamp":"2020-02-04T14:14:25.315850Z"}
{"component":"virt-handler","level":"info","msg":"Starting device plugin controller","pos":"device_controller.go:92","timestamp":"2020-02-04T14:14:25.415517Z"}
{"component":"virt-handler","level":"info","msg":"vhost-net device plugin started","pos":"generic_device.go:157","timestamp":"2020-02-04T14:14:25.424538Z"}
{"component":"virt-handler","level":"info","msg":"kvm device plugin started","pos":"generic_device.go:157","timestamp":"2020-02-04T14:14:25.432451Z"}
{"component":"virt-handler","level":"info","msg":"tun device plugin started","pos":"generic_device.go:157","timestamp":"2020-02-04T14:14:25.434864Z"}
```

**Comment by danielBelenky** [comment]
@garretholland any chance that you are using `minikube<v0.35.0` ? if so, it lacks the support of vhost-net. A quick workaround, if your goal is to start a VM for playing around is to use emulation. See `Check for the Virtualization Extensions` section of our quickstart doc (https://kubevirt.io/quickstart_minikube/) for more info.

**Comment by garretholland** [comment]
@danielBelenky Thank you. I switched to VirtualBox and am having the same issue. Can you recommend a way I can test this locally on my mac? Is KVM necessary to use as the HV?

**Comment by danielBelenky** [comment]
@garretholland unfortunately I suspect that to support `vhost-net` we need kvm. You can use emulation though... it doesn't require the `vhost-net` device.

**Comment by garretholland** [comment]
Thank you, I think we can consider this issue closed. Thanks for the assist!

**Comment by danielBelenky** [comment]
Thank you.
