### ISSUE TITLE
Unable to launch a windows VM

### ISSUE THREAD

**Issue by abhiniveshjain** [kubevirt/kubevirt#3047]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind enhancement

**What happened**:
I have downloaded windows 2012 based image (.qcow2 format) from https://cloudbase.it/ and then ran below commands on master node to add it to openshift default registry.

oc login -u kubeadmin -p xx-xxxx-xxx

podman login -u kubeadmin -p $(oc whoami -t) image-registry.openshift-image-registry.svc:5000

podman build -t vmidisks/win2k12r2:latest -f ./Dockerfile .
(My Dockerfile has below 2 lines)
FROM scratch
ADD win2k12r2.qcow2 /tmp/

podman tag localhost/vmidisks/win2k12r2 image-registry.openshift-image-registry.svc:5000/openshift/image

podman push image-registry.openshift-image-registry.svc:5000/openshift/image

oc create -f vmi_windows.yaml

details of this file is given in VMI specification

**What you expected to happen**:
windows VM should be provisioned

**How to reproduce it (as minimally and precisely as possible)**:
This is covered in what happened section

**Anything else we need to know?**:
it fails with below message
[root@master-0 tmp]# oc get pod
NAME                              READY   STATUS             RESTARTS   AGE
virt-launcher-vmi-windows-mnk4t   1/2     ImagePullBackOff   0          77s

  Normal   Pulling    <invalid> (x3 over 34s)  kubelet, paeprod-worker-1  Pulling image "image-registry.openshift-image-registry.svc:5000/openshift/image"
  Warning  Failed     <invalid> (x3 over 28s)  kubelet, paeprod-worker-1  Failed to pull image "image-registry.openshift-image-registry.svc:5000/openshift/image": rpc error: code = Unknown desc = pinging docker registry returned: Get https://image-registry.openshift-image-registry.svc:5000/v2/: dial tcp 172.xx.xx.xxx:5000: connect: no route to host
  Warning  Failed     <invalid> (x3 over 28s)  kubelet, paeprod-worker-1  Error: ErrImagePull
  Normal   BackOff    <invalid> (x5 over 27s)  kubelet, paeprod-worker-1  Back-off pulling image "image-registry.openshift-image-registry.svc:5000/openshift/image"
  Warning  Failed     <invalid> (x5 over 27s)  kubelet, paeprod-worker-1  Error: ImagePullBackOff

**Environment**:
- KubeVirt version (use `virtctl version`):
Client Version: version.Info{GitVersion:"v0.25.0", GitCommit:"b755c56f396ed880940821688eaddbd869e33897", GitTreeState:"clean", BuildDate:"2020-01-03T13:13:53Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.20.2", GitCommit:"eb1308c9b403d9d19a9b006e805ca57d014cf40a", GitTreeState:"clean", BuildDate:"2019-08-20T14:10:36Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):

[root@master-0 tmp]# oc version
Client Version: v4.2.13
Server Version: 4.2.14
Kubernetes Version: v1.14.6+b294fe5

- VM or VMI specifications:
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-windows
  name: vmi-windows
spec:
  domain:
    clock:
      timer:
        hpet:
          present: false
        hyperv: {}
        pit:
          tickPolicy: delay
        rtc:
          tickPolicy: catchup
      utc: {}
    cpu:
      cores: 2
    devices:
      disks:
      - disk:
          bus: sata
        name: containerdisk
      interfaces:
      - masquerade: {}
        model: e1000
        name: default
    features:
      acpi: {}
      apic: {}
      hyperv:
        relaxed: {}
        spinlocks:
          spinlocks: 8191
        vapic: {}
    firmware:
      uuid: 5d307ca9-b3ef-428c-8861-06e72d69f223
    machine:
      type: q35
    resources:
      requests:
        memory: 12Gi
  networks:
  - name: default
    pod: {}
  terminationGracePeriodSeconds: 0
  volumes:
    - name: containerdisk
      containerDisk:
        image: image-registry.openshift-image-registry.svc:5000/openshift/image

- Cloud provider or hardware configuration:
Baremetal servers

- OS (e.g. from /etc/os-release):
Master node is running on CoreOS and worker node is running on CentOS 7.
output from master node is as follows
NAME="Red Hat Enterprise Linux CoreOS"
VERSION="42.81.20191223.0"
VERSION_ID="4.2"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 42.81.20191223.0 (Ootpa)"
ID="rhcos"
ID_LIKE="rhel fedora"
ANSI_COLOR="0;31"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.2"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.2"
OSTREE_VERSION=42.81.20191223.0

worker node output is as below
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
Linux master-0 4.18.0-147.3.1.el8_1.x86_64 #1 SMP Wed Nov 27 01:11:44 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
virtctl 

- Others:

**Comment by rmohr** [comment]
@abhiniveshjain in general most things look ok. I think the only issue is that you are placing the disks in `/tmp`:

> podman build -t vmidisks/win2k12r2:latest -f ./Dockerfile .
> (My Dockerfile has below 2 lines)
> FROM scratch
> ADD win2k12r2.qcow2 /tmp/

[They need to be added to](https://kubevirt.io/user-guide/docs/latest/creating-virtual-machines/disks-and-volumes.html#containerdisk) `/disk` to auto-detect it.

An alternative would be to explicitly give the path to the disk in the spec: `path: whatever`.

**Comment by abhiniveshjain** [comment]
Thanks. PODs came up fine after this but VMI is showing in failed state.

[root@master-0 tmp]# oc get vmis
NAME          AGE   PHASE    IP            NODENAME
vmi-windows   45m   Failed   10.x.x.x   worker-0

Following is the error that I am seeing here. Is it /disk that I need to add in DockerFile or /disk/
does one missing "/" at the end causing this? 

  Phase:             Failed
  Qos Class:         Burstable
Events:
  Type     Reason            Age                 From                            Message
  ----     ------            ----                ----                            -------
  Normal   SuccessfulCreate  43m                 virtualmachine-controller       Created virtual machine pod virt-launcher-vmi-windows-bjvxn
  Warning  SyncFailed        41m (x25 over 41m)  virt-handler, worker-0  failed to find a sourceFile in containerDisk containerdisk: Failed to check /proc/1/root/var/lib/containers/storage/overlay/b1fe5bb24174cd52420f02f0653b54899ee22adcc6b4a8c55b2b205ba0c753da/merged/disk for disks: readdirent: not a directory
  Warning  SyncFailed        36m (x5 over 36m)   virt-handler, worker-0  failed to detect socket for containerDisk containerdisk: dial unix /var/run/kubevirt/container-disks/d368bc1f-4841-11ea-bce3-20040fec89f0/disk_0.sock: connect: no such file or directory

**Comment by rmohr** [comment]
> Following is the error that I am seeing here. Is it /disk that I need to add in DockerFile or /disk/
> does one missing "/" at the end causing this?

Ha yes. It has to go into the `/disk` folder. So very likely a missing `/`.

**Comment by abhiniveshjain** [comment]
I have changed it and performed whole exercise again, still getting same error. Please see the logs.
My windows image is in .gz format, hope this is ok?

[root@master-0 win]# cat Dockerfile
FROM scratch
ADD  win2k12r2new.qcow2.gz /disk/

[VMI failure log.txt](https://github.com/kubevirt/kubevirt/files/4159804/VMI.failure.log.txt)

**Comment by rmohr** [comment]
We only support `qcow2` and `raw`.

**Comment by rmohr** [comment]
Also the error said that it still sees a `/disk` directory. You use the image pull policy `IfNotPresent`. So your node may not pull the latest image.

So two things: 1) ensure that you have the image uncompressed, 2) ensure that the image gets pulled (e.g. using Always as pull policy).

**Comment by abhiniveshjain** [comment]
Looks like something is wrong with the image that I am using. Do you have any idea on below error? This started coming after I extracted .gz file and used that.

  Warning  Failed     63s (x2 over 3m50s)            kubelet, worker-0  Failed to pull image "image-registry.openshift-image-registry.svc:5000/default/win2k2012image:latest": rpc error: code = Unknown desc = Error committing the finished image: error adding layer with blob "sha256:d724582939992ef13269b15a70c4f819036dffd4b08a9a89ec9d729aeaef965d": Error processing tar file(exit status 1): unexpected EOF


I have one working .iso image, how can I covert that to .img or .qcow2?

**Comment by iranzo** [comment]
Have you checked https://kubevirt.io/2019/How-To-Import-VM-into-Kubevirt.html ?

**Comment by abhiniveshjain** [comment]
Instead of CDI, I am using Container Registry Disks (https://github.com/kubevirt/kubevirt/blob/master/docs/container-register-disks.md ) method. Is there any issue with this method?

**Comment by rmohr** [comment]
There is nothing wrong with it. The only difference is that in the containerDisk case, you can't write permanently to the image. In the case of CDI you can, since the data is stored in a PVC.

> "sha256:d724582939992ef13269b15a70c4f819036dffd4b08a9a89ec9d729aeaef965d": Error processing tar file(exit status 1): unexpected EOF

This reminds me of a docker bug where it had issues with layers which were bigger than I think 5 GB. Updating docker normally helps.

**Comment by abhiniveshjain** [comment]
Thanks. so Ideally it should work with container disk case also. In place of docker, I am using Podman and it is of below version.

podman version
Version:            1.4.2-stable3
RemoteAPI Version:  1
Go Version:         go1.12.12
OS/Arch:            linux/amd64

**Comment by abhiniveshjain** [comment]
> There is nothing wrong with it. The only difference is that in the containerDisk case, you can't write permanently to the image. In the case of CDI you can, since the data is stored in a PVC.
> 
> > "sha256:d724582939992ef13269b15a70c4f819036dffd4b08a9a89ec9d729aeaef965d": Error processing tar file(exit status 1): unexpected EOF
> 
> This reminds me of a docker bug where it had issues with layers which were bigger than I think 5 GB. Updating docker normally helps.

Do you suggest to use CDI since in practical purposes, we would be required to change the image? e.g. If I install an application on top of the OS then effectively I am changing the image and these changes need to persist after POD/node reboot. Is this correct understanding?

**Comment by fabiand** [comment]
Were you ultimately able to launch the Windows VM?

**Comment by abhiniveshjain** [comment]
Yes I was able to launch it. Thanks for your help.
