### ISSUE TITLE
Better error message for pausing a stopped VM

### ISSUE THREAD

**Issue by slintes** [kubevirt/kubevirt#3061]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:
When trying to pause a stopped VM, the error message is `Error pausing VirtualMachineInstance test-vm: virtualmachineinstance.kubevirt.io "test-vm" not found`.

**What you expected to happen**:
Error message should suggest to check if the VM is running.

**How to reproduce it (as minimally and precisely as possible)**:
Create a not running VM, try to pause it.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.26.0

**Comment by xpivarc** [comment]
I`m taking this...

**Comment by xpivarc** [comment]
During this I find out that in https://kubevirt.io/api-reference/v0.26.0/definitions.html#_v1_virtualmachinerunstrategy is confusing runstrategy which acts like its object but is only string alias. I would suggest to inline this and add k8s like enum of allowed values in this field (see https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.17/#deploymentstrategy-v1-apps).
