### ISSUE TITLE
Don't rely on GOARCH in tests

### ISSUE THREAD

**Issue by murilofv** [kubevirt/kubevirt#3067]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

This is a follow up item from the PR https://github.com/kubevirt/kubevirt/pull/2944 to enable ppc64le in kubevirt and was requested by @rmohr in the following discussion: https://github.com/kubevirt/kubevirt/pull/2944#discussion_r377566566

In it he suggested that we don't depend on GOARCH inside the test and move it to an outer layer and pass in the architecture as a parameter/member for tests that have some specific architecture dependency / condition.

**Comment by rmohr** [comment]
/remove-lifecycle rotten

`runtime.GOARCH` is now only used at a few places with #3054 , but it is still too deep in the stack. It should be passed in from the main functions of the binaries to provide a good unit testing experience.
