### ISSUE TITLE
cannot console to vmi with hostdisk img

### ISSUE THREAD

**Issue by leyao-daily** [kubevirt/kubevirt#3068]
**Is this a BUG REPORT or FEATURE REQUEST?**:
bug
> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
when create a vm with host disk img (ubuntu img), i cannot use '''virtctl console myvm", it will stop and show "Successfully connected to vmi-u console. The escape sequence is ^]" without further action.
I log into the pod, and use 'virsh console myvm', encounter 
"
Connected to domain default_vmi
Escape character is ^]
error: internal error: character device console0 is not using a PTY
"
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
use local host disk image such as ubuntu.img and cirros.img

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):latest
- Kubernetes version (use `kubectl version`):1.15.3
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fabiand** [comment]
This does not look like it's related to the host disk ..

On which OS do you run virtctl? @leyao-daily ?
