### ISSUE TITLE
Unify letter capitalization for VM and VMI

### ISSUE THREAD

**Issue by petrkotas** [kubevirt/kubevirt#3072]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

When returning the stats for VM and VMI, the LIVE-MIGRATABLE field does not have unified capitalization.

For VM it is true | false.
For VMI it is True | False.

The UX should be the same for both cases.

**How to reproduce it (as minimally and precisely as possible)**:

```
./cluster-up/kubectl.sh apply -f ./examples/vm-cirros.yaml
```

Start the vm-cirros.

Result:
```
./cluster-up/kubectl.sh get vm -o wide 
NAME        AGE   RUNNING   VOLUME   CREATED
vm-cirros   81s   true               true

./cluster-up/kubectl.sh git vmi -o wide
NAME         AGE     PHASE     IP            NODENAME   LIVE-MIGRATABLE
vm-cirros    10s     Running   10.244.0.21   node01     False
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): master
- Kubernetes version (use `kubectl version`): all

**Comment by xpivarc** [comment]
ping

**Comment by xpivarc** [comment]
This is a think of kubectl. For CRD we can supply options for printing(but this does not help) but we use Running in VM as bool so there will be always lowercase. As of VMI the LIVE-MIGRATABLE field is PodCondition which is string allowing True/False/Unknown (https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/#pod-conditions) so allways uppercase. Without reworking API or other thinks we can`t resolve this issue.
