### ISSUE TITLE
Specify monitorNamespace not work

### ISSUE THREAD

**Issue by wavezhang** [kubevirt/kubevirt#3086]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

> /kind enhancement

**What happened**:
1. install kubevirt v0.26.0
2. install prometheus operator
3. update kubevirt object using following yaml
```
apiVersion: kubevirt.io/v1alpha3
kind: KubeVirt
metadata:
  name: kubevirt
spec:
  monitorNamespace: monitoring
  monitorAccount: prometheus-k8s
```
servicemonitor not created
**What you expected to happen**:
servicemonitor created under monitoring namespace
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
if i create namespace `openshift-monitoring`， servicemonitor will be created under namespace  `openshift-monitoring`，but what i want is servicemonitor created under namespace `monitoring`
**Environment**:
- KubeVirt version (use `virtctl version`):
v0.26.0
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by petrkotas** [comment]
Hi @wavezhang can you please provide more information about your setup?

What cluster are you running? How did you install the Prometheus? How was Kubevirt installed?

Moreover please paste `kubectl/oc get pods --all-namespaces` choose whichever apply to you.

Thank you for reporting this issue!

**Comment by wavezhang** [comment]
according to lines here,  only `imagePullPolicy` works

https://github.com/kubevirt/kubevirt/blob/2c1969d92afe62ee092a08f2b3ec3e5ad6d6fac5/pkg/virt-operator/util/config.go#L120-L123

**Comment by petrkotas** [comment]
Hi @wavezhang, this is correct. However, from the KubeVirt side, it is tested on most platforms that Prometheus works. Therefore it would be most helpful if you would be able to provide asked information.

It helps to find the precise cause of the failure.

Thank you!

**Comment by wavezhang** [comment]
```
NAMESPACE              NAME                                           READY   STATUS             RESTARTS   AGE
cdi                    cdi-apiserver-78c5cbcb6f-hbq9m                 1/1     Running            0          118m
cdi                    cdi-deployment-856d5f8b8-fnzc9                 1/1     Running            0          118m
cdi                    cdi-operator-7ff7659456-7vbwx                  1/1     Running            0          14m
cdi                    cdi-uploadproxy-9778bdb68-2j74c                1/1     Running            0          118m
kube-system            calico-kube-controllers-79b59cfd5-frt9s        1/1     Running            1          57d
kube-system            calico-node-qss6s                              2/2     Running            0          42d
kube-system            calico-node-rb8ww                              2/2     Running            0          42d
kube-system            calico-node-s6dh7                              2/2     Running            0          42d
kube-system            coredns-9c9d6d675-8r5mb                        1/1     Running            29         134d
kube-system            coredns-9c9d6d675-ppw4q                        1/1     Running            48         65d
kube-system            etcd-master01                                  1/1     Running            9          158d
kube-system            genie-network-admission-controller-zszlr       1/1     Running            8          158d
kube-system            genie-plugin-4wvg2                             1/1     Running            4          158d
kube-system            genie-plugin-clbpw                             1/1     Running            7          158d
kube-system            genie-plugin-d7h7p                             1/1     Running            3          158d
kube-system            genie-policy-controller-5hrb9                  1/1     Running            3          158d
kube-system            genie-policy-controller-msmj6                  1/1     Running            4          158d
kube-system            genie-policy-controller-wd4sk                  1/1     Running            7          158d
kube-system            kube-apiserver-master01                        1/1     Running            0          43d
kube-system            kube-controller-manager-master01               1/1     Running            23         129d
kube-system            kube-proxy-7l8w4                               1/1     Running            0          59d
kube-system            kube-proxy-9fpk5                               1/1     Running            3          59d
kube-system            kube-proxy-glh5g                               1/1     Running            3          59d
kube-system            kube-scheduler-master01                        1/1     Running            25         129d
kubevirt               virt-api-577bb487f9-556d7                      1/1     Running            0          7d23h
kubevirt               virt-api-577bb487f9-rvtqs                      1/1     Running            0          7d23h
kubevirt               virt-controller-86bb4f9df9-8r658               1/1     Running            0          7d23h
kubevirt               virt-controller-86bb4f9df9-vzbmw               1/1     Running            0          7d23h
kubevirt               virt-handler-g2g79                             1/1     Running            0          7d23h
kubevirt               virt-handler-pfqvd                             1/1     Running            0          7d23h
kubevirt               virt-handler-w5pgq                             1/1     Running            0          7d23h
kubevirt               virt-operator-88bd9b947-jh9dk                  1/1     Running            0          8d
kubevirt               virt-operator-88bd9b947-twbg5                  1/1     Running            0          8d
monitoring             alertmanager-main-0                            2/2     Running            0          47h
monitoring             alertmanager-main-1                            2/2     Running            0          47h
monitoring             alertmanager-main-2                            2/2     Running            0          47h
monitoring             grafana-84d696b6bd-6nhvd                       1/1     Running            0          47h
monitoring             kube-state-metrics-59448475c8-l85j7            4/4     Running            0          26h
monitoring             node-exporter-dg2qn                            2/2     Running            4          47h
monitoring             node-exporter-mc4cb                            2/2     Running            433        47h
monitoring             node-exporter-wkgdr                            1/2     CrashLoopBackOff   450        47h
monitoring             prometheus-k8s-0                               3/3     Running            1          47h
monitoring             prometheus-k8s-1                               3/3     Running            1          47h
monitoring             prometheus-operator-759659876d-fp69h           1/1     Running            0          47h
test                  virt-launcher-test-0-zndwv                     1/1     Running            0          7h36m
test                  virt-launcher-test-win-b4cnv                   2/2     Running            0          35d

```

**Comment by petrkotas** [comment]
I see the cluster is working correctly. It may be an issue with the version.
I have checked the documentation and asked around. The KubeVirt should setup monitoring automatically from v0.20+.

Would you mind consulting the documentation https://kubevirt.io/2019/More-about-Kubevirt-metrics.html and also https://gist.github.com/fromanirh/a7f6fa877598da721cc2f2e56153a01a

One more question, is there any ServiceMonitor created automatically by the operator?

Thank you!

**Comment by wavezhang** [comment]
if i create namespace openshift-monitoring， servicemonitor will be created under namespace openshift-monitoring，but what i want is servicemonitor created under namespace monitoring

**Comment by petrkotas** [comment]
I see. For this, you can update the KubeVirt config, which is a ConfigMap created in the KubeVirt namespace with the name `kubevirt-config`.
The item you are looking for is `additionalProperties` which is a map.

Add the `monitorNamespace: YOUR_NAMESPACE` and the ServiceMonitor should land in that namespace.

Hope this helps.

You can see the code here: https://github.com/kubevirt/kubevirt/blob/ac73fc0aef98829e16fbb2d8abdffce81eeaa9b0/pkg/virt-operator/util/config.go#L95

**Comment by wavezhang** [comment]
No, the config was designed from KubeVirt object like following

```
apiVersion: kubevirt.io/v1alpha3
kind: KubeVirt
metadata:
  name: kubevirt
spec:
  monitorNamespace: monitoring
  monitorAccount: prometheus-k8s
```

see code here,
https://github.com/kubevirt/kubevirt/blob/ac73fc0aef98829e16fbb2d8abdffce81eeaa9b0/pkg/virt-operator/util/config.go#L264-L272

**Comment by petrkotas** [comment]
Hey, I spend some more time with the code, not my code originally.
Sorry for confusing you with the config. 

Now I see your problem. I also see that the namespace should already exist, otherwise it defaults to `openshift-monitoring`.

If this is not the case this is a bug and it has to be scheduled for a fix.
Thanks for finding it out.

**Comment by petrkotas** [comment]
Hey @wavezhang it is like I said: https://github.com/kubevirt/kubevirt/blob/8d5ed15ba2f351e568572cf9d903ca4e887a6ee1/pkg/virt-operator/install-strategy/strategy.go#L126

Does the monitoring namespace exist?

**Comment by slintes** [comment]
Hey @wavezhang,

at the code place you mentioned (`GetTargetConfigFromKV()`) the `ImageTag` and `ImageRegistry` are handled individually for historic reasons. `MonitorNamespace` will be handled in the subsequent `getKVMapFromSpec(kv.Spec)` funvtion. You can check if the code picked up the right value by looking at the status of your `KubeVirt` resource. There you find `TargetDeploymentConfig`, which should contain your desired configuration.

For further debugging, can please post your complete KubeVirt resource from the cluster, and logs of the leading virt-operator pod?

Another interesting detail: you wrote `update kubevirt object using following yaml`. Is the problem reproducable when you modify the KubeVirt resource **before** deployment?

**Comment by fabiand** [comment]
@danielBelenky weren't you also active in this area?

**Comment by mlsorensen** [comment]
Does this help reproduce? Maybe in this case it's just not deserializing or not reading TARGET_DEPLOYMENT_CONFIG

```
docker run -e OPERATOR_IMAGE=kubevirt/virt-operator:v0.28.0 \
-e TARGET_INSTALL_NAMESPACE=kubevirt -e TARGET_IMAGE_PULL_POLICY=IfNotPresent \
-e TARGET_DEPLOYMENT_CONFIG='{"id":"foo-test","namespace":"kubevirt","registry":"","kubeVirtVersion":"v0.28.0","additionalProperties":{"ImagePullPolicy":"IfNotPresent","MonitorAccount":"kubevirt","MonitorNamespace":"kubevirt"}}' \
-v /Users/marcus/kube-dev.conf:/kubeconfig kubevirt/virt-operator:v0.28.0 \
--dump-install-strategy --kubeconfig /kubeconfig

{"component":"virt-operator","level":"warning","msg":"failed to create service monitor resources because namespace openshift-monitoring does not exist","pos":"strategy.go:228","timestamp":"2020-05-07T21:33:56.617771Z"}
```

**Comment by cchengleo** [comment]
Hi @wavezhang,

I recently also encounter this issue with minikube. This issue results from a minor bug.

KubeVirt’s virt-operator checks the existence of the `MonitorNamespace` and `MonitorServiceAccount`. KubeVirt will automatically create a ServiceMonitor resource in the monitorNamespace, as well as an appropriate role and rolebinding in KubeVirt’s namespace.

https://github.com/kubevirt/kubevirt/blob/fc076e0166a9556d730e452b6026eb68815257aa/pkg/virt-operator/install-strategy/strategy.go#L130-L131


When deploying on a platform other than openshift, specified `MonitorNamespace` and `MonirotServiceAccount` has to be specified as AdditionalProperties of KubeVirt CR, and extracted with from a JSON string when virt-operator creating the Install Strategy.

https://github.com/kubevirt/kubevirt/blob/fc076e0166a9556d730e452b6026eb68815257aa/pkg/virt-operator/kubevirt.go#L726


More specifically, the `MonitorNamespace` and `MonirotServiceAccount` are extracted from a JSON map:
https://github.com/kubevirt/kubevirt/blob/fc076e0166a9556d730e452b6026eb68815257aa/pkg/virt-operator/util/config.go#L397-L411

And the keys of MonitorNamespace and MonitorServiceAccount are:
https://github.com/kubevirt/kubevirt/blob/fc076e0166a9556d730e452b6026eb68815257aa/pkg/virt-operator/util/config.go#L57-L61

When extracting values from a JSON map, the key name is expected to start with capitalized characters, as mentioned in @mlsorensen 's example.

I'll submit a quick fix.

**Comment by ArthurSens** [comment]
hi @cchengleo 

I was facing that issue for some weeks now. Just curious, how did you manage to debug that? I wanted to fix this, but I didn't even know how to start.

anyways, I'm glad you found the problem

**Comment by cchengleo** [comment]
Hi @ArthurSens ,

I am new to KubeVirt so I am not sure whether my methodology is the best practice. Here is the replay:

1. From what mention by @wavezhang:
> **Anything else we need to know?**:
> if i create namespace `openshift-monitoring`， servicemonitor will be created under namespace `openshift-monitoring`，but what i want is servicemonitor created under namespace `monitoring`

I tried the same practice (i.e., deploy kube-prometheus and create openshit-monitoring in minimum) and noticed that the `kubevirt-install-strategy` configmap was created with valid `MonitorService`.

2. I checked the code and confirmed the logic.

3. I tried to specific `monitorNamespace` and `monitorAccount` in KubeVirt CR following https://kubevirt.io/user-guide/#/installation/monitoring, but no MonitorService was created in `kubevirt-install-strategy` configmap. That led me to the conclusion that virt-operator may have difficulty to find the specified namespace.

4. I instrumented (adding log) to:
https://github.com/kubevirt/kubevirt/blob/fc076e0166a9556d730e452b6026eb68815257aa/pkg/virt-operator/kubevirt.go#L911-L912

And found that all the needed parameters are passed in.

5. However, I noticed the specified namespace was not found at:
https://github.com/kubevirt/kubevirt/blob/fc076e0166a9556d730e452b6026eb68815257aa/pkg/virt-operator/install-strategy/strategy.go#L130-L131

This led me to think the problem raises from https://github.com/kubevirt/kubevirt/blob/fc076e0166a9556d730e452b6026eb68815257aa/pkg/virt-operator/util/config.go#L397:1

6. As I have dumped the JSON map, it's easy to notice the key name mismatching.

Please let me know if you have some better way to triage this. This also took me quite a while. :-(

**Comment by ArthurSens** [comment]
I tried and couldn't find anything wrong with the code... so the way that works is the better way I guess :)
I was just curious about how you approached this, thanks again
