### ISSUE TITLE
make generate leave running container leftovers

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#3087]
/kind bug

**What happened**:
Running make generate leaves a running container when its done

$ docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
3291617f66e7        kubevirt/builder    "/entrypoint.sh hack…"   53 seconds ago      Up 53 seconds                           

**What you expected to happen**:
Its more tidy that it would run it with --rm or stop + rm the container at the end (as a TRAP in case of failure) ?

at the past it didn't left it i think.

**How to reproduce it (as minimally and precisely as possible)**:
run make generate and when it finishes run docker ps

**Comment by rmohr** [comment]
this container will exit after some time. It is the bazel server. We mimic the behaviour which you also have if you just run bazel directly. I think the default idle time is one hour. Having this container running drastically improves the bazel performance.

**Comment by oshoval** [comment]
thanks Roman,
didnt fully understand but why when make generate finish we still need it , bazel finished already isnt it ?

if you suggest, lets close the issue, thanks

**Comment by rmohr** [comment]
most of our make commands run bazel commands. If we would always stop the server after every invocation, the server would have to be started afterwards and some cache results would be lost. That is just how you use bazel. It is posibble to do a `batch` invocation with bazel, where it automatically stops the server afterwards, but that would definitely not be the default option. How would we know if people want to run another command?

Does that make sense?

**Comment by oshoval** [comment]
sure thanks for the explanation
closing
