### ISSUE TITLE
virtctl vnc connection disappears immediately

### ISSUE THREAD

**Issue by abhiniveshjain** [kubevirt/kubevirt#3104]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
I have created windows VM using below blog https://kubevirt.io/2020/KubeVirt-installing_Microsoft_Windows_from_an_iso.html but when I try to launch it using vnc, it is showing below message and it disappears. I can see windows screen for a moment.

root@localhost win2012iso]# ./virtctl vnc win2k12-iso --v=8
{"component":"","level":"info","msg":"connection timeout: 1m0s","pos":"vnc.go:137","timestamp":"2020-02-26T13:05:13.233602Z"}
{"component":"","level":"info","msg":"Executing commandline: 'remote-viewer [vnc://127.0.0.1:41080 --debug]'","pos":"vnc.go:225","timestamp":"2020-02-26T13:05:13.233721Z"}
{"component":"","level":"info","msg":"remote-viewer connected in 643.25739ms","pos":"vnc.go:148","timestamp":"2020-02-26T13:05:13.876851Z"}

**What you expected to happen**:
VNC should connect me to windows 

**How to reproduce it (as minimally and precisely as possible)**:
follow the blog mentioned before.

**Anything else we need to know?**:
I am running it on openshift 4.2.
**Environment**:
- KubeVirt version (use `virtctl version`):
[root@localhost win2012iso]# ./virtctl version
Client Version: version.Info{GitVersion:"v0.24.0", GitCommit:"d63c53391b8e75fc79c74187bcce73024a4e8c24", GitTreeState:"clean", BuildDate:"2019-12-02T13:57:44Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.20.2", GitCommit:"eb1308c9b403d9d19a9b006e805ca57d014cf40a", GitTreeState:"clean", BuildDate:"2019-08-20T14:10:36Z", GoVersion:"go1.11.5", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):
- VM or VMI specifications: Given in blow referred earlier.
- Cloud provider or hardware configuration: on baremetal
- OS (e.g. from /etc/os-release):
-bash: /etc/os-release: Permission denied
[root@localhost win2012iso]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`):
[root@localhost win2012iso]# uname -a
Linux localhost.localdomain 3.10.0-957.27.2.el7.x86_64 #1 SMP Mon Jul 29 17:46:05 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools: 
- Others:

**Comment by petrkotas** [comment]
Hi @abhiniveshjain can you please provide logs from the `virt-launcher` pod, the `virt-api` pod (probably all of them) and from the `virt-handler`?

Also what is you kubevirt state? Can you also paste `kubectl get pods -n kubevirt`? Thank you

**Comment by abhiniveshjain** [comment]
Issue was fixed after upgrading kubevirt to V0.24. earlier I was using V0.20
