### ISSUE TITLE
Windows nodes in Kubernetes cluster get a virt-handler pod too, this is undesirable.

### ISSUE THREAD

**Issue by jiridanek** [kubevirt/kubevirt#3134]
/kind bug

Instance of virt-handler is being scheduled onto my Windows Kubernetes node. The pod is stuck permanently in ImagePullBackOff state.

**What you expected to happen**:

Pods of virt-handler are not scheduled on Windows nodes, or on any nodes other than Linux nodes.

**How to reproduce it (as minimally and precisely as possible)**:

Notice that

```
    spec:
      nodeSelector:
        beta.kubernetes.io/os: linux
```

is not configured for virt-handler. That means joining any non-linux node to the cluster will get me one of these permanently broken virt-handler pods for it.

**Environment**:
- KubeVirt version (use `virtctl version`):
Client Version: version.Info{GitVersion:"v0.26.0", GitCommit:"cc1fd38226718b0c07fc3e567148912110c25ee1", GitTreeState:"clean", BuildDate:"2020-02-05T02:18:58Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"{gitVersion}", GitCommit:"{gitCommit}", GitTreeState:"{gitTreeState}", BuildDate:"{buildDate}", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:14:22Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-11T18:07:13Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
- VM or VMI specifications: n/a
- Cloud provider or hardware configuration: company OpenStack
- OS (e.g. from /etc/os-release): RHEL 8 master and one node, and one Windows Server 1909 node

**Workaround**:
I am looking for a workaround that would put a nodeSelector onto any current and future virt-handler pods I have in my cluster.

**Comment by petrkotas** [comment]
Hi, @jiridanek thanks for reporting this issue.
Indeed this is a serious issue breaking the deployment. 

The KubeVirt will be configured to only schedule on nodes labeled with `kubernetes.io/os=linux`.

**Comment by petrkotas** [comment]
This issue is rather relevant to scheduling. Would you mind taking a look @omeryahud once you have the capacity? Thank you.

**Comment by kwiesmueller** [comment]
@jiridanek I just wanted to update you on this.
There is a PR in the works to fix this: https://github.com/kubevirt/kubevirt/pull/4669
If you need a temporary workaround until then, you should be able to inject the nodeSelector into your `kubevirt` resource.
Like this:
```yaml
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
### add this ###
  infra:
    nodePlacement:
      nodeSelector:
        kubernetes.io/os: linux
  workloads:
    nodePlacement:
      nodeSelector:
        kubernetes.io/os: linux
### add this ###
```
