### ISSUE TITLE
VM refuse to migrate/stop when VMI name is specified

### ISSUE THREAD

**Issue by xpivarc** [kubevirt/kubevirt#3140]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
Using VM yaml which should be able to migrate will produce :
Error migrating VirtualMachine Operation cannot be fulfilled \
on virtualmachine.kubevirt.io "vm-migratable": VM is not running

**What you expected to happen**:

Migration will be scheduled / VMI should stop.

**How to reproduce it (as minimally and precisely as possible)**:
`
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: vm-migratable
spec:
  running: false
  template:
    metadata:
      labels:
        special: vmi-migratable
      name: vmi-migratable
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          interfaces:
          - masquerade: {}
            name: default
        machine:
          type: ""
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - containerDisk:
          image: registry:5000/kubevirt/alpine-container-disk-demo:devel
        name: containerdisk
`
vk start vm-migratable
vk migrate vm-migratable / vk stop vm-migratable

**Anything else we need to know?**:

It`s seems like it`s caused by defined name in VMI.

**Environment**:
- KubeVirt version (use `virtctl version`):
Client Version: version.Info{GitVersion:"v0.26.1-120+62c792cd649321-dirty", GitCommit:"62c792cd649321d4610819a58c6fcc1eede5e389", GitTreeState:"dirty", BuildDate:"2020-03-04T16:05:34Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"{gitVersion}", GitCommit:"{gitCommit}", GitTreeState:"{gitTreeState}", BuildDate:"{buildDate}", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:20:10Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.0", GitCommit:"70132b0f130acc0bed193d9ba59dd186f0e634cf", GitTreeState:"clean", BuildDate:"2019-12-07T21:12:17Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by slintes** [comment]
After starting the VM, did you wait until it is running? It can take a while.

**Comment by xpivarc** [comment]
@slintes Sure think. I can see VM,VMI in true/Running accordingly and I can console to it.
The problem here is that stop/migrate command want VM name. But when I specify name of VMI in yaml, these command won't work...

**Comment by rmohr** [comment]
If the VMI is backed by a VM, the name of the VM and the VMI should match. This sounds strange.

**Comment by xpivarc** [comment]
@rmohr Yes but in my example I override it to vmi-migratable from vm-migratable. So I think there should be validation of this when VM is created/updated or we should handle this in other manner(without assumption of vmi having same name).
