### ISSUE TITLE
Stupid question about nested virtualization.

### ISSUE THREAD

**Issue by cdrage** [kubevirt/kubevirt#317]
So..

I have a cluster.

Well, one SuperMicro server running 5 KVM VM's running Kubernetes within Docker (using Kubeadm).

Using Kubevirt, is there anything special I would need to do in order to successfully deploy nested virtualization?

Another question is what's the *ideal* cluster? I'm assuming a cluster of bare-metal servers running Kubernetes (rather than a group of VM's).

Essentially it's kubevirt launching a VM within Docker within a VM.

**Comment by fabiand** [comment]
No, there is nothing special needed, except for setting up nested virtualization on your hypervisors.

The ideal cluster indeed is a Kubernetes cluster on bare-metal.

**Comment by fabiand** [comment]
Closing this, please reopen if you think there is some bug involved.
