### ISSUE TITLE
Update SECURITY.md away from redhat.com email address

### ISSUE THREAD

**Issue by caniszczyk** [kubevirt/kubevirt#3195]
We should probably create an alias for you on kubevirt.io or you can use a groups.io email address

**Comment by rmohr** [comment]
The domain is owned by cncf already, right? Sounds great if you could do the alias for us.

**Comment by brianmcarey** [comment]
@caniszczyk - looking at the latest version of SECURITY.md - https://github.com/kubevirt/kubevirt/blob/main/SECURITY.md - I think this issue can be closed. 

Please reopen if you still see an issue.

/close
