### ISSUE TITLE
libvirt.NewVirConnectionWithAuth segfaults if user/pass are ""

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#32]
@rmohr libvirt.NewVirConnectionWithAuth does not handle empty user/password gracefully.

I was thinking abut
```
 func NewConnection(uri string, user string, pass string) (Connection, error) {
-       virConn, err := libvirt.NewVirConnectionWithAuth(uri, user, pass)
+       var err
+       if user == "" {
+               virConn, err := libvirt.NewVirConnection(uri)
+       } else {
+               virConn, err := libvirt.NewVirConnectionWithAuth(uri, user, pass)
+       }
        if err != nil {
                return nil, err
        }
```

thoughts?

**Comment by fabiand** [comment]
With qemu+tcp://… this is still the case.

The virt-handler segfaults if they are not given.

Adding `--user` and `--pass` fixes the issue.

**Comment by rmohr** [comment]
Could you share the stacktrace?

**Comment by fabiand** [comment]
Yes, but it needs to wait until monday.

**Comment by fabiand** [comment]
Btw it is easy to reproduce

Have libvirt listen on TCP without authentication and run `virt-handler --libvirt-uri qemu+tcp://ADDR/system` - then retry with --user and --pass.
