### ISSUE TITLE
Support for hot-plugging disks (kubevirt only)

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#320]
> As a user I want to be able to attach an additional disk to my VM at runtime

This issue is limited to disks backed by network storage consumed by in-qemu drivers.
The reason for this is that this allows us to focus on the API semantics.

getting hot-plug right if Kubernets involved opens up a range of other problems.

- [ ] Design API
- [ ] Design implementation

**Comment by fabiand** [comment]
Network part depends on https://github.com/kubevirt/kubevirt/issues/1067

**Comment by fabiand** [comment]
I'm closing this RFE for now, as the ground (direct storga enetwork connections from qemu) are not available in KubeVirt anymore.

**Comment by fabiand** [comment]
This could be re-eneabled by https://github.com/kubernetes/kubernetes/issues/38606

**Comment by fabiand** [comment]
Relates to #952

**Comment by yichengliu58** [comment]
Hi @fabiand , just curious, has there been any updates about this feature? Cuz I'm currently looking for a method to make kubevirt support hot-plug disks, and haven't found any solutions (didn't find any explicit solution in the related issues above...)
libvirt supports hot-plugin devices, but I didn't find any interfaces in kubevirt to support. It would be a bit complex to change kubevirt code to support this. So are there any existing configs supporting this feature? If not maybe this new feature should be discussed...

**Comment by fabiand** [comment]
Hey - Good for getting back.

So - There were _many_ brainstorms by different groups of how to achieve this.

@awels has actually started to look into this.
