### ISSUE TITLE
Mapping rules for mapping libvirt XML to the KubeVirt API cannot map graphics option

### ISSUE THREAD

**Issue by anuraagrijal3138** [kubevirt/kubevirt#3239]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
I tried to set graphics option in VirtualMachine yaml file and In got some error
**What you expected to happen**:
kubectl create displays successful output.
**How to reproduce it (as minimally and precisely as possible)**:
Install kubernetes and kubevirt. Apply the following yaml. I don't know if I am doing this correctly.

apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: ubuntu-test
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: ubuntu
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: harddrive
          - disk:
              bus: virtio
            name: cloudinitdisk
          graphics:
          - type: vnc
            port: -1
            autoPort: yes
            listen: 0.0.0.0
        machine:
          type: q35
        resources:
          requests:
            memory: 1G
      volumes:
      - name: harddrive
        persistentVolumeClaim:
          claimName: ubuntu-hdd
      - name: cloudinitdisk
        cloudInitNoCloud:
          userData: |-
            #cloud-config
            password: ubuntu
            chpasswd: { expire: False }

The output of kubectl create:
The request is invalid: : spec.template.spec.domain.devices.graphics in body is a forbidden property
**Anything else we need to know?**:
References:
https://github.com/kubevirt/kubevirt/blob/fb3564acdf1f5c0275998ba8fafbe5e7da251621/pkg/virt-launcher/virtwrap/api/schema.go
https://github.com/kubevirt/kubevirt/blob/f39a06f7ef46a8ed07b2bfd537fdab573e6427e7/docs/vm-configuration.md
**Environment**:
- KubeVirt version (use `virtctl version`):
Client Version: version.Info{GitVersion:"v0.26.1", GitCommit:"e40ff7965e2aadbf21131626dfa3be85524e3a2c", GitTreeState:"clean", BuildDate:"2020-02-18T13:48:23Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"{gitVersion}", GitCommit:"{gitCommit}", GitTreeState:"{gitTreeState}", BuildDate:"{buildDate}", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.3", GitCommit:"06ad960bfd03b39c8310aaf92d1e7c12ce618213", GitTreeState:"clean", BuildDate:"2020-02-12T13:43:46Z", GoVersion:"go1.13.7", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"15", GitVersion:"v1.15.11", GitCommit:"d94a81c724ea8e1ccc9002d89b7fe81d58f89ede", GitTreeState:"clean", BuildDate:"2020-03-12T21:00:06Z", GoVersion:"go1.12.17", Compiler:"gc", Platform:"linux/amd64"}
- VM or VMI specifications:
- Cloud provider or hardware configuration:
Private machines
- OS (e.g. from /etc/os-release):
ubuntu 18.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
Hi, I fear that you ended up looking at an internal API. You can find the official schema at https://kubevirt.io/api-reference/master/ and the user guide at https://kubevirt.io/user-guide/#/.

We add a graphics device by default and it should be accessible via `virtctl vnc <vmname>`.

I hope that helps.

**Comment by rmohr** [comment]
And here the actual link regarding to graphics: https://kubevirt.io/user-guide/#/creation/devices?id=video-and-graphics-device

**Comment by anuraagrijal3138** [comment]
Thank you for the information.
