### ISSUE TITLE
`make functests` doesn't use KUBECONFIG

### ISSUE THREAD

**Issue by alevitter** [kubevirt/kubevirt#3253]
/kind bug

**What happened**:
I tried running `make functests` with a valid $KUBECONFIG environment variable set but the tests failed with `panic: invalid configuration: no configuration has been provided`

**What you expected to happen**:
When executing the tests, it would use the configuration provided by $KUBECONFIG 

**How to reproduce it (as minimally and precisely as possible)**:
Run `make functests` with $KUBECONFIG set

**Anything else we need to know?**:
The tests are successfully generated. Running `_out/tests/tests.test -kubeconfig=$KUBECONFIG` works fine after the failure.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.28.0
- Kubernetes version (use `kubectl version`): v1.16.2
- OS (e.g. from /etc/os-release): RHEL Workstation 8
- Others: Running Openshift using a Code Ready Container: https://github.com/code-ready/crc

**Comment by oshoval** [comment]
happened also on ocp-4.5 dev-scripts

**Comment by dhiller** [comment]
First of all we need more information. Without the exact error message we can't be sure what to fix. Please try to recreate the issue on your setup, including:
- all of the steps you did to run the tests
- all of the output of the steps.

**Comment by InbarRose** [comment]
> First of all we need more information. Without the exact error message we can't be sure what to fix. Please try to recreate the issue on your setup, including:
> 
> * all of the steps you did to run the tests
> * all of the output of the steps.

I encountered the same issue. It is very simply that the command created tries using `${kubeconfig}` instead of `${KUBECONFIG}` as the OP said. Here is my output after running `hack/functests.sh`

```
panic: invalid configuration: no configuration has been provided

goroutine 1 [running]:
kubevirt.io/kubevirt/tests.PanicOnError(...)
	/root/go/src/kubevirt.io/kubevirt/tests/utils.go:1755
kubevirt.io/kubevirt/tests_test.glob..func2()
	/root/go/src/kubevirt.io/kubevirt/tests/config_test.go:41 +0x2ef
kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/suite.(*Suite).PushContainerNode(0xc000102be0, 0x1d934c5, 0x4a, 0x1dfdc20, 0x0, 0x3e29c2d, 0x36, 0x25, 0xc0008e25b0, 0x70)
	/root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/suite/suite.go:144 +0x15a
kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo.Describe(0x1d934c5, 0x4a, 0x1dfdc20, 0xc0012ffc01)
	/root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:289 +0xad
kubevirt.io/kubevirt/tests_test.init.ializers()
	/root/go/src/kubevirt.io/kubevirt/tests/config_test.go:37 +0x6b
```
