### ISSUE TITLE
Add RHEL kickstart support (ks.cfg)

### ISSUE THREAD

**Issue by oatakan** [kubevirt/kubevirt#3284]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:
Currently the only way to automatically kickstart (ks.cfg) is via PXE or load an ISO as PVC. Similar to the sysprep issue here (https://github.com/kubevirt/kubevirt/issues/2902), you should be able to store ks.cfg file in configMap and load as cdrom. However this doesn't work because kickstart process looks for a removable drive (i.e. cdrom) with volume id 'OEMDRV' .

See: https://access.redhat.com/documentation/en-us/red_hat_enterprise_linux/8/html/performing_an_advanced_rhel_installation/starting-kickstart-installations_installing-rhel-as-an-experienced-user

In the current implementation configmap files are put in an ISO with volume id 'cfgdata'. This can be changed to 'OEMDRV' for all to simply enable this scenario (not sure if there is any downside to this) or allow defining volume id as an option to v1.CDRomTarget and pass onto the defaultCreateIsoImage function.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
I think I would tackle this in two ways:

 1) Allow setting the volume id on the CDRomTarget to have full flexibility, but also
 2) For kickstart and sysprep, add special sources which do the right thing for you by default

**Comment by oatakan** [comment]
@rmohr that sounds good. Perhaps #1 could be implemented first as together with configmap this will provide an immediate generic solution. It would be nice to have a special source to handle kickstart/sysprep and expose this in the documentation.

**Comment by rmohr** [comment]
@oatakan, solution one should be addressed with #3301

**Comment by oatakan** [comment]
@rmohr , that was quick! :) hope it gets merged.
