### ISSUE TITLE
testing NVIDIA GPU passthrough , driver error code 43 . kubevirt not support set features.kvm.hidden = on

### ISSUE THREAD

**Issue by shawnU96** [kubevirt/kubevirt#3285]
testing NVIDIA GPU passthrough , driver error code 43 .
https://www.reddit.com/r/VFIO/comments/8pl48l/code_43_with_nvidia_passthrough_even_after/

**Comment by shawnU96** [comment]
```
type Features struct {
	ACPI   *FeatureEnabled `xml:"acpi,omitempty"`
	APIC   *FeatureEnabled `xml:"apic,omitempty"`
	Hyperv *FeatureHyperv  `xml:"hyperv,omitempty"`
	SMM    *FeatureEnabled `xml:"smm,omitempty"`
}
```

**Comment by cedbossneo** [comment]
i have developed a hook to modify domain:

add theses annotations to you virtualmachineinstance : 

    hooks.kubevirt.io/hookSidecars: '[{"image": "cedbossneo/kubevirt-custom-hook"}]'
    custom.kubevirt.io/domain.features.kvm.hidden.-state: "-state:on"

**Comment by shawnU96** [comment]
> i have developed a hook to modify domain:
I use hookSidecar, run success.   and modify kvm.hidden on
example: /cmd/example-hook-sidecar.

**Comment by rmohr** [comment]
Nice hook. We can definitely also add this feature to our API. Also happy if one of you just adds it. It should not be too hard to do.

**Comment by vladikr** [comment]
I also think that this should be set by us without a hook. I'm not sure if we should just add it to the API.
As this is only relevant for GPU passthrough, perhaps we should allow this to be set as an option in the GPU section? 

```
spec:
  domain:
    devices:
      gpus:
      - deviceName: nvidia.com/GP102GL_Tesla_P40
        name: gpu1
        hideKVM: true
```

**Comment by rmohr** [comment]
Does anyone know why nvidia requires this? I can find a lot of references which tell you to hide kvm, but why is that actually needed?

**Comment by vladikr** [comment]
perhaps they are not certified on kvm and don't allow the driver to load properly... I'm not sure.
I remember Alex added this a while ago : https://www.redhat.com/archives/libvir-list/2014-August/msg00744.html

**Comment by crobinso** [comment]
My understanding is that for some hardware like consumer cards the windows nvidia driver will deliberately fail to load if it detects the presence of KVM. In my GPU passthrough config I need to use `<kvm><hidden state='on'/></kvm>`, as well as setting a non-default `<hyperv><vendor_id value=XXX/></hyperv>`

**Comment by salanki** [comment]
Only GeForce cards require this. Quadro and Tesla don't.
