### ISSUE TITLE
VMI does not have guest agent connected?

### ISSUE THREAD

**Issue by watermelon-brother** [kubevirt/kubevirt#3296]
**What happened**:
I get below message when I requested the guestosinfo`s api .
```js
//request-win7:
https://localhost:8000/k8s/clusters/local/apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/win7/guestosinfo
//response-win7:
Operation cannot be fulfilled on virtualmachineinstance.kubevirt.io "win7": VMI does not have guest agent connected


//request-centos7(qcow2):
https://localhost:8000/k8s/clusters/local/apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/centos7-qcow2/guestosinfo
//response-centos7(qcow2):
{
    "guestAgentVersion": "2.12.0",
    "hostname": "centos7-qcow2",
    "os": {
        "name": "CentOS Linux",
        "kernelRelease": "3.10.0-957.27.2.el7.x86_64",
        "version": "7 (Core)",
        "prettyName": "CentOS Linux 7 (Core)",
        "versionId": "7",
        "kernelVersion": "#1 SMP Mon Jul 29 17:46:05 UTC 2019",
        "machine": "x86_64",
        "id": "centos"
    },
    "timezone": "UTC, 0",
    "userList": [
        {
            "userName": "centos",
            "loginTime": 1586865702.427362
        }
    ],
    "fsInfo": {
        "disks": [
            {
                "diskName": "sda1",
                "mountPoint": "/",
                "fileSystemType": "xfs",
                "usedBytes": 0,
                "totalBytes": 0
            }
        ]
    }
}

```
**What you expected to happen**:
`why centos7 vm is ok,but win7 vm is failed?`

I guest that centos7 vm is installed the guest tool,but win7 vm is not installed.

so, I need to install the guest tool for the win7 vm by my hand.It's right?

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (v0.28.0):
- Kubernetes version (v1.17.2):

**Comment by rmohr** [comment]
> so, I need to install the guest tool for the win7 vm by my hand.It's right?

That is very likely the issue. We offer a `containerDisk` with virtio-win drivers. The container which contains it is called `kubevirt/virtio-container-disk`.

This tutorial, which shows on how to install windows in general on kubevirt also contains details about the guest agent too: https://kubevirt.io/2020/KubeVirt-installing_Microsoft_Windows_from_an_iso.html

Let me know if it does not help.
