### ISSUE TITLE
Support SMBios in VMI spec

### ISSUE THREAD

**Issue by salkin** [kubevirt/kubevirt#3306]
**FEATURE REQUEST?**:

 /kind enhancement

**What happened**:
Smbios settings are global for kubevirt deployment our use case is to simulate different hardware ontop of kubevirt. As detection is done on manufacturer it should be possible to set SMBios options on VMI basis

**Comment by rmohr** [comment]
Sounds useful. I would be happy to review a PR which add support to setting `manufacturer`.
