### ISSUE TITLE
ocp4.4 provider cluster up stuck in infinite wait when using `export KUBEVIRT_NUM_NODES=3`

### ISSUE THREAD

**Issue by RamLavi** [kubevirt/kubevirt#3318]
**Is this a BUG REPORT or FEATURE REQUEST?:**
/kind bug

**What happened**:
following the [ocp4.4 README](https://github.com/kubevirt/kubevirt/blob/master/cluster-up/cluster/ocp-4.4/README.md), I tried in a remote server:
```
export KUBEVIRT_PROVIDER=ocp-4.4
export KUBEVIRT_NUM_NODES=3 # master + two workers
make cluster-up
```

The cluster gets stuck waiting for a second worker. console stdout [attached](http://pastebin.test.redhat.com/857760)

if I unset `KUBEVIRT_NUM_NODES` env then the cluster up spins ok. 

**What you expected to happen**:
the cluster should spin up with no issue

**How to reproduce it (as minimally and precisely as possible)**:
follow the ocp4.4 [README file](https://github.com/kubevirt/kubevirt/blob/master/cluster-up/cluster/ocp-4.4/README.md).

**Anything else we need to know?**:
nope

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by oshoval** [comment]
please move it to kubevirtci imo
thanks

**Comment by oshoval** [comment]
can be closed ocp is removed from kubevirtci
thanks
