### ISSUE TITLE
Deploy kubevirt in an heterogeneous environment

### ISSUE THREAD

**Issue by e-minguez** [kubevirt/kubevirt#3321]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:
I have an OpenShift environment as:
* 3 VMs as masters
* 2 bare metal workers with some CNF features deployed on top of it (including a RT kernel, which doesn't have the KVM module)
* 1 'regular' bare metal worker (no CNF, no RT kernel)

**What you expected to happen**:
If I deploy CNV/Kubevirt via the hyperconverged operator in that kind of heterogeneus cluster, I expect the hco deployment finish successfully and then the VMs are only scheduled to the only worker allowed to run VMs.

**How to reproduce it (as minimally and precisely as possible)**:
When I deploy CNV/Kubevirt using the hyperconverged operator:
* the node-labeller pods were scheduled in all the hosts, including masters, and they were stuck in 'pending' (except the one running on the regular bare metal worker)
* the hco operator pod was stuck in "Running 0/1"... meaning that the operator 'installation' didn't finish successfully

I've tried then to disable this behaviour by labeling the masters and cnf workers as 'kubevirt.io/schedulable=false', but $someone modified that label to true.

**Anything else we need to know?**:

The following commands are my current workaround, labeling the 'regular' workers as 'labeller=true' and modify the labeller DS to fit those labels (and restart the hco pod):

---8<---
```
oc label $(oc get nodes --selector='node-role.kubernetes.io/worker,!node-role.kubernetes.io/worker-cnf' -o name) "kubevirt.io/labeller=true" --overwrite
oc patch ds kubevirt-node-labeller -n openshift-cnv -p '{"spec":{"template":{"spec":{"nodeSelector":{"kubevirt.io/labeller":"true"}}}}}'
oc delete $(oc get po -l name=hyperconverged-cluster-operator -o name -n openshift-cnv) -n openshift-cnv
```
--->8---

**Environment**:
- KubeVirt version (use `virtctl version`): CNV 2.2
- Kubernetes version (use `kubectl version`): OCP4.4
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: Already specified
- OS (e.g. from /etc/os-release): RHCOS
- Kernel (e.g. `uname -a`): N/A
- Install tools: Hyperconverged operator
- Others:

**Comment by e-minguez** [comment]
It seems this PR https://github.com/kubevirt/kubevirt/pull/3133 is related.

**Comment by rmohr** [comment]
@e-minguez thanks for creating the issue. First, no doubt we should make things like `nodeSelector`, `tolerances` and `affinities better configurable.

Second a question:

> * the node-labeller pods were scheduled in all the hosts, including masters, and they were stuck in 'pending' (except the one running on the regular bare metal worker)

What I wonder here: if the node-labeller got scheduled on the master nodes, wouldn't then any other random workload also be potentially scheduled to these nodes? Are the master nodes missing some taints to prevent ordinary workloads? Also do you know why it was stuck in `pending`?

> I've tried then to disable this behaviour by labeling the masters and cnf workers as 'kubevirt.io/schedulable=false', but $someone modified that label to true.

This label is maintained by virt-handler. If you make your master unschedulable for normal workloads, they will despite that label being true not scheduled to the master nodes.

**Comment by e-minguez** [comment]
I tore down the environment and I cannot have it right now (that's why I'm answering here a bit late), so please bear in mind this is from what I remember from yesterday.

> @e-minguez thanks for creating the issue. First, no doubt we should make things like `nodeSelector`, `tolerances` and `affinities better configurable.
> 
> Second a question:
> 
> > * the node-labeller pods were scheduled in all the hosts, including masters, and they were stuck in 'pending' (except the one running on the regular bare metal worker)
> 
> What I wonder here: if the node-labeller got scheduled on the master nodes, wouldn't then any other random workload also be potentially scheduled to these nodes? Are the master nodes missing some taints to prevent ordinary workloads? Also do you know why it was stuck in `pending`?

I _think_ the masters are tainted so you cannot schedule regular workloads on them.
And wrt `pending` status I _think_ they were scheduled but events show there were not enough `device.kubevirt.io/kvm` devices available

> 
> > I've tried then to disable this behaviour by labeling the masters and cnf workers as 'kubevirt.io/schedulable=false', but $someone modified that label to true.
> 
> This label is maintained by virt-handler. If you make your master unschedulable for normal workloads, they will despite that label being true not scheduled to the master nodes.

**Comment by e-minguez** [comment]
> I tore down the environment and I cannot have it right now (that's why I'm answering here a bit late), so please bear in mind this is from what I remember from yesterday.
> 
> > @e-minguez thanks for creating the issue. First, no doubt we should make things like `nodeSelector`, `tolerances` and `affinities better configurable.
> > Second a question:
> > > * the node-labeller pods were scheduled in all the hosts, including masters, and they were stuck in 'pending' (except the one running on the regular bare metal worker)
> > 
> > 
> > What I wonder here: if the node-labeller got scheduled on the master nodes, wouldn't then any other random workload also be potentially scheduled to these nodes? Are the master nodes missing some taints to prevent ordinary workloads? Also do you know why it was stuck in `pending`?
> 
> I _think_ the masters are tainted so you cannot schedule regular workloads on them.
> And wrt `pending` status I _think_ they were scheduled but events show there were not enough `device.kubevirt.io/kvm` devices available
> 

I have now an environment ready so I can answer you properly.

My environment now has 3 masters (virtual machines, deployed like bare metal servers with virtualbmc, etc.), 2 workers that have a RT kernel without kvm and 1 worker with a regular kernel. Everything running with RHCOS and OCP4.4 nightly:

```
$ oc version
Client Version: 4.4.0-0.nightly-2020-04-27-013217
Server Version: 4.4.0-0.nightly-2020-04-27-013217
Kubernetes Version: v1.17.1

$ oc get nodes
NAME                                         STATUS   ROLES               AGE    VERSION
kni1-master-0.cloud.lab.eng.bos.redhat.com   Ready    worker,worker-cnf   56m    v1.17.1
kni1-master-1.cloud.lab.eng.bos.redhat.com   Ready    worker,worker-cnf   55m    v1.17.1
kni1-vmaster-0                               Ready    master,virtual      118m   v1.17.1
kni1-vmaster-1                               Ready    master,virtual      119m   v1.17.1
kni1-vmaster-2                               Ready    master,virtual      118m   v1.17.1
kni1-worker-0.cloud.lab.eng.bos.redhat.com   Ready    worker              88m    v1.17.1
```

The labeller pods are running in the worker and the masters:

```
$ oc get po -o wide |grep labeller
kubevirt-node-labeller-6l9p4                          0/1     Pending   0          6m11s   <none>         <none>                                       <none>           <none>
kubevirt-node-labeller-brflq                          1/1     Running   0          6m11s   10.129.0.33    kni1-vmaster-0                               <none>           <none>
kubevirt-node-labeller-cwmh8                          0/1     Pending   0          6m11s   <none>         <none>                                       <none>           <none>
kubevirt-node-labeller-dgnl9                          1/1     Running   0          6m11s   10.128.0.33    kni1-vmaster-1                               <none>           <none>
kubevirt-node-labeller-m59kp                          1/1     Running   0          6m11s   10.130.0.17    kni1-vmaster-2                               <none>           <none>
kubevirt-node-labeller-zbjz7                          1/1     Running   0          6m11s   10.131.0.26    kni1-worker-0.cloud.lab.eng.bos.redhat.com   <none>           <none>
```

The events show:

```
$ oc get events --sort-by=.metadata.creationTimestamp | grep labeller
...
<unknown>   Warning   FailedScheduling         pod/kubevirt-node-labeller-cwmh8                                      0/6 nodes are available: 2 Insufficient devices.kubevirt.io/kvm, 4 node(s) didn't match node selector.
<unknown>   Warning   FailedScheduling         pod/kubevirt-node-labeller-6l9p4                                      0/6 nodes are available: 2 Insufficient devices.kubevirt.io/kvm, 4 node(s) didn't match node selector.
```

Then the hco installation fails:

```
9m37s       Normal    NeedsReinstall           clusterserviceversion/kubevirt-hyperconverged-operator.v2.2.0         installing: waiting for deployment hco-operator to become ready: Waiting for rollout to finish: 0 of 1 updated replicas are available...
9m37s       Warning   InstallCheckFailed       clusterserviceversion/kubevirt-hyperconverged-operator.v2.2.0         install timeout
4m35s       Warning   InstallCheckFailed       clusterserviceversion/kubevirt-hyperconverged-operator.v2.2.0         install failed: deployment hco-operator not ready before timeout: deployment "hco-operator" exceeded its progress deadline
```

The scheduler says:

```
$ oc get schedulers.config.openshift.io -o yaml
apiVersion: v1
items:
- apiVersion: config.openshift.io/v1
  kind: Scheduler
  metadata:
    name: cluster
    ...
  spec:
    mastersSchedulable: false
    policy:
      name: ""
  status: {}
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

There are no taints at node label but they are all labelled as `kubevirt.io/schedulable=true`

```
$ oc get nodes -o yaml | grep -i taint
$ oc get nodes -o yaml | grep -i sched
      kubevirt.io/schedulable: "true"
      kubevirt.io/schedulable: "true"
      kubevirt.io/schedulable: "true"
      kubevirt.io/schedulable: "true"
      kubevirt.io/schedulable: "true"
      kubevirt.io/schedulable: "true"
```

I guess the labeller pods are running on the masters because they inherit the hypervisor CPU capabilities (so that's fine):

```
$ virsh dumpxml vmaster-0
...
  <cpu mode='custom' match='exact' check='full'>
    <model fallback='forbid'>Haswell-noTSX-IBRS</model>
    <vendor>Intel</vendor>
    <feature policy='require' name='vme'/>
    <feature policy='require' name='ss'/>
    <feature policy='require' name='vmx'/>
    <feature policy='require' name='f16c'/>
    <feature policy='require' name='rdrand'/>
    <feature policy='require' name='hypervisor'/>
    <feature policy='require' name='arat'/>
    <feature policy='require' name='tsc_adjust'/>
    <feature policy='require' name='umip'/>
    <feature policy='require' name='md-clear'/>
    <feature policy='require' name='stibp'/>
    <feature policy='require' name='arch-capabilities'/>
    <feature policy='require' name='ssbd'/>
    <feature policy='require' name='xsaveopt'/>
    <feature policy='require' name='pdpe1gb'/>
    <feature policy='require' name='abm'/>
    <feature policy='require' name='ibpb'/>
    <feature policy='require' name='skip-l1dfl-vmentry'/>
  </cpu>
```

Hope that helps

> > > I've tried then to disable this behaviour by labeling the masters and cnf workers as 'kubevirt.io/schedulable=false', but $someone modified that label to true.
> > 
> > 
> > This label is maintained by virt-handler. If you make your master unschedulable for normal workloads, they will despite that label being true not scheduled to the master nodes.

**Comment by ksimon1** [comment]
Labeller will be in pending state on all nodes, which don't have kvm device available (virt-handler is taking care about propagating availability of kvm device). It is daemon set, so labeller will run on all nodes which are schedulable.

**Comment by e-minguez** [comment]
> Labeller will be in pending state on all nodes, which don't have kvm device available (virt-handler is taking care about propagating availability of kvm device). It is daemon set, so labeller will run on all nodes which are schedulable.

Yes, but that means the deployment will never end because they are not Running. Also daemonsets can use node selectors[1].

[1] https://kubernetes.io/docs/concepts/workloads/controllers/daemonset/#running-pods-on-only-some-nodes

**Comment by rmohr** [comment]
I think we all agree that it is a bug in the node labeler that the pods don't come up. virt-handler always comes up and just reports that some nodes are not able to run VMs. With the effort to integrate the labeler completely into kubevirt,the behavior will be fixed too. If everything goes well that integration will be complete with v0.30.
