### ISSUE TITLE
Test 2227 , IPv6 lane failing, because the stress test isnt sufficent in order to failing the migration

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#3323]
/kind bug

**What happened**:
running test 2227 on ipv6 lane
the test tries to stress by dirty memory pages, 
and expect the migration to fail, which doesnt

i suspect its because its kind and not a provider like k8s with vm nodes.
tried to extend the stressing time to 60 seconds, and the 800M to 900M
it didnt help

**What you expected to happen**:
migration should fail and test pass

**How to reproduce it (as minimally and precisely as possible)**:
run test 2227 on prow with all other ipv6 tests as well (on its own it passes)

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by EdDev** [comment]
> i suspect its because its kind and not a provider like k8s with vm nodes.

AFAIK this test is passing on the ipv4 lane and even passing on the ipv6 one on master.
So I am unclear how this appeared with the introduction of the migration fixes.
It the test faulty?

**Comment by oshoval** [comment]
when i last tried, it didnt pass on ipv6 kind, because the stressing there wasnt enough to make the migration fail, i tried to increase stress timeout and so on, and it didnt help,
once we have a k8s vm based provider, we can try again, maybe stress on container node.as we have on kind, isnt strong enough to cause the migration to fail.

**Comment by EdDev** [comment]
I think it passes, see here: https://github.com/kubevirt/kubevirt/pull/3429/files#diff-d642ef9101fdb0671d818d73a1c3f977L1086

I did a rebase on that PR, lets see the current state.

**Comment by oshoval** [comment]
it passed because you dont have their the migration fix imo,
with the migration fix, the migration pass, and then the test fails because it expect the migration to fail by causing dirty pages which should cause a slow migration, and to fail it

**Comment by EdDev** [comment]
Ohh, you mean it should fail on timeout.

**Comment by oshoval** [comment]
yep
also see here please it started to flake strongly on other lanes
(my PRs arent part of this report, see the pr list at the bottom of the page please)
https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2020-05-20-168h.html

i think the method there isn't deterministic , and it depends on too many factors that can change

**Comment by rmohr** [comment]
/reopen

Config propagation fix is needed.
