### ISSUE TITLE
Node failover function of VM/VMIRS 

### ISSUE THREAD

**Issue by haemyung** [kubevirt/kubevirt#3332]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind enhancement

**What happened**: When the worker node status is not ready(kubelet down or Host down), the VM keep staying in Terminating state

**What you expected to happen**:  The VM terminate successfully and re-create on another node. (if i want to recreate on another node, some specific flag is help to recreate vm automatically)

**How to reproduce it (as minimally and precisely as possible)**:
 - Create VM/VMIRS on the worker node
 - Stop the kubelet (systemctl stop kubelet) or Shutdown the worker node
 - Checking your pods ( kubectl get pods ) -> pods is staying in terminating state

**Anything else we need to know?**:
- In k8s, replicaset guarantees failover in the above situation.
- I think, VM is one of replicaset for vmi 
- Even if it's not, vmirs seems to have to be guaranteed 

**Environment**:
- KubeVirt version (use `virtctl version`):  v0.27.0
- Kubernetes version (use `kubectl version`):  v1.15.3
- VM or VMI specifications: vm & vmirs
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu 18.04.4 LTS
- Kernel (e.g. `uname -a`): 4.15.0-88-generic #88-Ubuntu SMP Tue Feb 11 20:11:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by rmohr** [comment]
> * In k8s, replicaset guarantees failover in the above situation.
> * I think, VM is one of replicaset for vmi
> * Even if it's not, vmirs seems to have to be guaranteed

Agreed. We should do that.

> The VM terminate successfully and re-create on another node. (if i want to recreate on another node, some specific flag is help to recreate vm automatically)

Just a general note on these: If the node goes down the corresponding pods become unknown and we stop processing the VMIs. As soon as an admin delete the pods (active force-delete to tell the system that they are really dead on the node, and that  the node is not just unreachable), they will be moved to Failed and will be cleaned up.

However, as you assessed, we should follow the k8s replicaset example and create new VMIs immediately.

**Comment by haemyung** [comment]
Thank you for answer. 

However,I don't understand few things 

I want to check some:

1. In the case of vmirs, the idea of ​​guaranteeing the number of vmi according to the k8s replicaset flow seems to agree with you. however, In the case of vm, Do you agree to automatically node-failover for VM (not vmirs) when some flag is present? Not manually deleted by the administrator?

2. If you agree, do you have any plans for this? If not, can I commit for this?

**Comment by rmohr** [comment]
I am all with you regarding the VMIRS, but I don't think that we can do this for VMs. There we are restarting a VM on a different node which potentially uses shared storage. We really have to be sure that the VM is down before restarting. Otherwise we risk data corruption. In order to automatically unblock in such cases, you may want to add a node fencing operator to your cluster. As soon as this operator fenced the node and the pods go to a final phase, the VM will automatically restart.
