### ISSUE TITLE
KubeVirt networking README is empty

### ISSUE THREAD

**Issue by maiqueb** [kubevirt/kubevirt#3333]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What happened**:
[KubeVirt's networking README](https://github.com/kubevirt/kubevirt/blob/master/docs/devel/networking.md) is missing.

**What you expected to happen**:
I expect the [KubeVirt's networking README](https://github.com/kubevirt/kubevirt/blob/master/docs/devel/networking.md) to be a developer's guide for contributors.

**Anything else we need to know?**:
I can volunteer to work on this; this issue can also to used to agree on the structure of the document.

The proposed structure of the README is:
- explain the 2 phases of pod networking setup (in virt-handler / in virt-launcher)
- binding mechanism concept (proxy from kubevirt api to libvirt's domxml)
  - explain each binding mechanism
    - conceptually (what's the desired outcome of this connection type)
    - implementation wise (the installed rules for masquerade, etc)
- multus concepts (what it does, how to use, annotating vm's spec w/ network attachment definitions data)

**Comment by phoracek** [comment]
Part of the binding and multus info is probably already covered in the user-guide, but developer deep dive on the implementation details would be much welcomed.
