### ISSUE TITLE
relabell node when KVM is available

### ISSUE THREAD

**Issue by ksimon1** [kubevirt/kubevirt#3354]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind enhancement

**What happened**:
When KVM is not available, node-labeller exits (https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-handler/node-labeller/node_labeller.go#L60) and never run again.
**What you expected to happen**:
After KVM is available, labeller should relabell node with correct labels
//cc @rmohr

**Comment by rmohr** [comment]
/close

This will be interesting when we start a new attempt to merge the node-labeller but is not actionable right now us such.
