### ISSUE TITLE
vmi keeps restarting with "failed to configure vmi network for migration target: Link not found"

### ISSUE THREAD

**Issue by tliron** [kubevirt/kubevirt#3382]
/kind bug

**What happened**:

vmi seems to be running OK for a few minutes, but then it is suddenly restarted. Every restart the event log has ~20 events that look like this:
```
workspace              2s          Warning   SyncFailed                virtualmachineinstance/asterisk-vnf                                   failed to configure vmi network: failed to configure vmi network for migration target: Link not found
```

**Anything else we need to know?**:

Note that this setup is Minikube, so it's nested virtualization (KVM2-Intel).

I have no liveness or readiness probes set up.

**Environment**:

Running on Fedora 32
Kubernetes v1.18.2
Minikube v1.9.2, CRI-O and Multus CNI
KubeVirt v0.29.0

**Comment by rmohr** [comment]
@AlonaKaplan might be related to some network refactoring. Could you have a look?

**Comment by tliron** [comment]
Here is the [spec](https://github.com/tliron/telephony-network-service/blob/master/configuration/kubernetes/asterisk-vnf.yaml) I am using.

**Comment by fabiand** [comment]
@phoracek FYI

**Comment by phoracek** [comment]
@fabiand yeah, we've been discussing this offline. Seems like it is not that simple to reporduce. So we hope to be lucky and collect more logs and data from virt-launcher for debugging the next time this happens.

**Comment by tliron** [comment]
I am unable to reproduce. :( The error was correlated with the disk filling up, which was caused by something else running on the node and which may have been fixed. So maybe the full disk was the cause. I will, for now, close this and thank you for the attention.
