### ISSUE TITLE
Node labeller uses very likely invalid labels

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#3389]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

When I look at nodes right now they have labels like this:

```
                    "feature.node.kubernetes.io/cpu-feature-xgetbv1": "true",
                    "feature.node.kubernetes.io/cpu-feature-xsave": "true",
                    "feature.node.kubernetes.io/cpu-feature-xsavec": "true",
                    "feature.node.kubernetes.io/cpu-feature-xsaveopt": "true",
                    "feature.node.kubernetes.io/cpu-model-Broadwell": "true",
                    "feature.node.kubernetes.io/cpu-model-Broadwell-IBRS": "true",
                    "feature.node.kubernetes.io/cpu-model-Broadwell-noTSX": "true",
                    "feature.node.kubernetes.io/cpu-model-Broadwell-noTSX-IBRS": "true",
                    "feature.node.kubernetes.io/cpu-model-Haswell": "true",
```

**What you expected to happen**:

If `feature.node.kubernetes.io` is not an official prefix which every project should use, then we use it wrong. `*.kubernetes.io` prefixes are normally reserved for kubernetes and addons should use their own prefixes. `feature.node.kubevirt.io` for instance.

Further also a suggestion: It may make sense to clean up the suffix of the keys and move parts of it to the prefix. Instead of `feature.node.kubernetes.io/cpu-feature-xsaveopt` consider `cpu-feature.node.kubevirt.io/xsaveopt` and instead of `feature.node.kubernetes.io/cpu-model-Haswell` consider `cpu-model.node.kubernetes.io/Haswell`

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
/assign @ksimon1

Would you mind having a look?

**Comment by ksimon1** [comment]
The labels `feature.node.kubernetes.io` are used, because node-labeller was developed as a simple replacement for node-feature-discovery (https://github.com/kubernetes-sigs/node-feature-discovery#node-feature-discovery) and NFD is using `feature.node.kubernetes.io` labels. In the beginning of labeller we wanted to stay in complience with official NFD, so we could in the future deprecate labeller and switch back to NFD. I think it is a good time to start discussion if we want new label format, or we will stick with old format, since I started again working on migration of labeller to kubevirt.

**Comment by rmohr** [comment]
Since we provide all this info based on versions which we need, without wanting to depend on updates going into NFD or not, I would suggest our own labels.

**Comment by rmohr** [comment]
Are we in contact with NFD people regarding this?

**Comment by ksimon1** [comment]
No we are not. If we use our own labels, we need to solve the upgrade path, because if kubevirt will remove old labels, the VMs which uses the old format will be unschedulable.

**Comment by rmohr** [comment]
> No we are not. If we use our own labels, we need to solve the upgrade path, because if kubevirt will remove old labels, the VMs which uses the old format will be unschedulable.

We can't conflicth with NFD if we want to combine this. For the upgrade path, node labeller just needs to be uninstalled as the last bit. Our rollout works like this:

 1) virt-handler (it will establish the new labels, so both exist at the same time)
 2) virt-controller (only now it will use the new labels, and they are there  already)
 3) now you can uninstall the node labeller
