### ISSUE TITLE
Need document for monitoring metrics

### ISSUE THREAD

**Issue by DrmagicE** [kubevirt/kubevirt#3400]
/kind enhancement
The kubevirt metrics are not documented. They should be listed in monitoring section or some where else. 
I have few questions about the metrics：
1. What does `kubevirt_vmi_phase_count` mean? 
2. Is `kubevirt_vmi_network_errors_total` including packet dropped？If not, is there any plan to support packet drop metric like `container_network_transmit_packets_dropped_total` in cadvisor? 
3. What does `state="1"` means in `kubevirt_vmi_vcpu_seconds{xxxx,state="1"}` metric? 

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):v0.28.0
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fabiand** [comment]
The goal of this issue would be to add a type and help text for every metric that kubevirt is exporting today.
