### ISSUE TITLE
Ipv6 lane failures after upgrading vm image to fc32

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#3421]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
The fedora image used by the e2e tests was upgraded to fedora32 on PR https://github.com/kubevirt/kubevirt/pull/3372.
This change cause several tests to start failing on ipv6 lane (for example - https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3319/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1260750823483248640)

**What you expected to happen**:
The test should pass

**How to reproduce it (as minimally and precisely as possible)**:
Run ip6 test lane

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by maiqueb** [comment]
@AlonaKaplan can we close this ?

**Comment by AlonaKaplan** [comment]
@maiqueb if you can attach the pr that fixed the issue before closing, it can be great.

**Comment by maiqueb** [comment]
They're already mentioned above:
  - #3454 
  - #3429 

I fail to see a button to close this issue, hence I'm reaching out for you to hit it (I'm assuming closing issues require approver rights).

**Comment by maiqueb** [comment]
/close 

Fixed by #3454 , #3429 .
