### ISSUE TITLE
virt-handler pod directory is hard-coded, no support for custom kubelet root

### ISSUE THREAD

**Issue by mlsorensen** [kubevirt/kubevirt#3426]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

Pods were stuck in 'Terminating' state. Through debugging it was determined that virt-handler was not detecting that the ContainerDisk was mounted, skipping unmount, and letting the pod hang forever.

The root cause of this is that kubelet had it's --root-dir set to an unexpected path, and kubevirt's configuration didn't match. This is important because virt-handler looks at mountinfo from the host's perspective and needs its local mounts to match paths that the host also has.

The first step of working around this was to set virt-handler's "kubelet-pods" volume mount to match the Kubelet's view of the world. This allowed virt-handler to see the ContainerDisk in the mountinfo, and allowed it to unmount and let the pod terminate cleanly.

However, there is another place where the code has hardcoded its view of pod path to "/var/lib/kubelet/pods" - https://github.com/kubevirt/kubevirt/blob/7137c788e5403f1f6c6742dac8ce16e127e399b4/pkg/container-disk/container-disk.go#L41

_*We need to make this configurable.*_

**What you expected to happen**:
Expect to be able to use kubevirt with a custom kubelet --root-dir configuration.

**How to reproduce it (as minimally and precisely as possible)**:

Set up a kubelet with an alternate --root-dir, something not "/var/lib/kubelet"

**Comment by mlsorensen** [comment]
Just for further clarification - when a pod stops, virt-handler looks for e.g.

```
/var/lib/kubelet/pods/63bf09d7-b9c7-40e4-a464-b6526bcfaa0a/volumes/kubernetes.io~empty-dir/container-disks/disk_0.img
```

In the host's mount info, but it is actually at:

```
<kubelet root>/pods/63bf09d7-b9c7-40e4-a464-b6526bcfaa0a/volumes/kubernetes.io~empty-dir/container-disks/disk_0.img
```

**Comment by Dhiraj240** [comment]
@mlsorensen I would like to work on the issue
