### ISSUE TITLE
[Question] Any example using KubeVirt running a real application

### ISSUE THREAD

**Issue by gyliu513** [kubevirt/kubevirt#3451]
I can see most of the guidance for KubeVirt is using KubeVirt to create a VM, but there is no guidance for how to use KubeVirt to create a real VM application. Does there are any guidance or tutorial that I can refer to create a real VM application? Like a simple nginx etc?

**Comment by mazzystr** [comment]
I'm currently writing a blog to be published on the web site.  It will feature a migration of a standalone Win2k19 vm running a dotnet application to a k8s / KubeVirt controlled vm.  I should have it published in a day or two.  No performance testing this time just a raw "can it be done" procedure.

**Comment by gyliu513** [comment]
Great, thanks @mazzystr , look forward to such blog. Can you help link your blog here after it got published and close this issue?

**Comment by mazzystr** [comment]
@gyliu513  Sorry I'm so late ... Blog post is finally posted ... https://kubevirt.io/2020/win_workload_in_k8s.html

**Comment by gyliu513** [comment]
nice, thanks @mazzystr !
