### ISSUE TITLE
Can't seem to get virtctl vnc to work

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt#3472]
/kind bug

**What happened**:
If I start a vm I can't vnc to the vm using virtctl.  

It seems virtctl is passing TigerVNC targets using url format (vnc://1.2.3.4) and it doesn't like it.  If I manually open vncviewer and enter the ip and port it will work.

**What you expected to happen**:
If I execute `virtctl vnc vm` tigervnc should launch and kvm to the host.

**How to reproduce it (as minimally and precisely as possible)**:
Install Fedora 32
Install minikube and run using `minikube start --driver=podman --container-runtime=cri-o`
Install KubeVirt / CDI
Create a Windows vm or Linux graphical desktop
Execute `virtctl vnc vm``

**Anything else we need to know?**:  Screenshot of error is attached. 
![blah](https://user-images.githubusercontent.com/2479463/82962260-9307b500-9f74-11ea-9a60-1dc5dc049180.png)

**Environment**:
- KubeVirt version (use `virtctl version`):
Client Version: version.Info{GitVersion:"v0.29.0", GitCommit:"cbb7eaddb34d38da15868b19d84647f668a6134b", GitTreeState:"clean", BuildDate:"2020-05-05T03:33:18Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"{gitVersion}", GitCommit:"{gitCommit}", GitTreeState:"{gitTreeState}", BuildDate:"{buildDate}", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications:
1 vcpu, 1024M mem, 14 gb vdisk

- Cloud provider or hardware configuration: Metal / HP EliteDesk G2 mini (Intel Core i5 / 8gb)

- OS (e.g. from /etc/os-release): 
$ sudo cat /etc/os-release
NAME=Fedora
VERSION="32 (Thirty Two)"
ID=fedora
VERSION_ID=32
VERSION_CODENAME=""
PLATFORM_ID="platform:f32"
PRETTY_NAME="Fedora 32 (Thirty Two)"
ANSI_COLOR="0;34"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:32"
HOME_URL="https://fedoraproject.org/"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora/f32/system-administrators-guide/"
SUPPORT_URL="https://fedoraproject.org/wiki/Communicating_and_getting_help"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=32
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=32
PRIVACY_POLICY_URL="https://fedoraproject.org/wiki/Legal:PrivacyPolicy"

- Kernel (e.g. `uname -a`):
Linux cube0 5.6.14-300.fc32.x86_64 #1 SMP Wed May 20 20:47:32 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by vatsalparekh** [comment]
Can you try again and paste output with `virtctl vnc -v 4 $vm_name`
This should show more verbose output

**Comment by mazzystr** [comment]
output test attached...
[blah.txt](https://github.com/kubevirt/kubevirt/files/4698662/blah.txt)

**Comment by rmohr** [comment]
@mazzystr do you rin it on linux or mac? We only support  remote-viewer on linux. Maybe you have an alias which points to tigervnc?

**Comment by mazzystr** [comment]
@rmohr I ran that on a fresh install of Fedora32 with minikube, KubeVirt and TigerVNC installed.  There is no alias set.

Fedora32 / TigerVNC installs as so...
```# rpm -ql tigervnc
/usr/bin/vncviewer
/usr/lib/.build-id
/usr/lib/.build-id/2c
/usr/lib/.build-id/2c/8c2553dddfe75961b777f67c54aa2d9d74b69a
/usr/share/applications/vncviewer.desktop
/usr/share/doc/tigervnc
/usr/share/doc/tigervnc/README.rst
/usr/share/locale/bg/LC_MESSAGES/tigervnc.mo
/usr/share/locale/cs/LC_MESSAGES/tigervnc.mo
/usr/share/locale/da/LC_MESSAGES/tigervnc.mo
/usr/share/locale/de/LC_MESSAGES/tigervnc.mo
/usr/share/locale/el/LC_MESSAGES/tigervnc.mo
/usr/share/locale/eo/LC_MESSAGES/tigervnc.mo
/usr/share/locale/es/LC_MESSAGES/tigervnc.mo
/usr/share/locale/fi/LC_MESSAGES/tigervnc.mo
/usr/share/locale/fr/LC_MESSAGES/tigervnc.mo
/usr/share/locale/fur/LC_MESSAGES/tigervnc.mo
/usr/share/locale/hu/LC_MESSAGES/tigervnc.mo
/usr/share/locale/id/LC_MESSAGES/tigervnc.mo
/usr/share/locale/it/LC_MESSAGES/tigervnc.mo
/usr/share/locale/ko/LC_MESSAGES/tigervnc.mo
/usr/share/locale/nl/LC_MESSAGES/tigervnc.mo
/usr/share/locale/pl/LC_MESSAGES/tigervnc.mo
/usr/share/locale/pt_BR/LC_MESSAGES/tigervnc.mo
/usr/share/locale/ru/LC_MESSAGES/tigervnc.mo
/usr/share/locale/sk/LC_MESSAGES/tigervnc.mo
/usr/share/locale/sr/LC_MESSAGES/tigervnc.mo
/usr/share/locale/sv/LC_MESSAGES/tigervnc.mo
/usr/share/locale/tr/LC_MESSAGES/tigervnc.mo
/usr/share/locale/uk/LC_MESSAGES/tigervnc.mo
/usr/share/locale/vi/LC_MESSAGES/tigervnc.mo
/usr/share/locale/zh_CN/LC_MESSAGES/tigervnc.mo
/usr/share/locale/zh_TW/LC_MESSAGES/tigervnc.mo
/usr/share/man/man1/vncviewer.1.gz
```

I don't know where this `remote-viewer` comes from

**Comment by rmohr** [comment]
The rpm `virt-viewer` should provide it. We should probably document that better, or just support more VNC viewers like we actually do on mac.

**Comment by mazzystr** [comment]
Yup! got it figured on on Sat
```
# yum whatprovides virt-viewer
Last metadata expiration check: 1:53:59 ago on Mon 08 Jun 2020 07:05:25 AM PDT.
virt-viewer-8.0-4.fc32.x86_64 : Virtual Machine Viewer
Repo        : fedora
Matched from:
Provide    : virt-viewer = 8.0-4.fc32
```
Installing that makes things work
