### ISSUE TITLE
Mouse out of sync when I used vnc connect to the win10 or win7

### ISSUE THREAD

**Issue by watermelon-brother** [kubevirt/kubevirt#3474]
**What happened**:
Mouse out of sync when I used vnc connect to the win10 or win7
**What you expected to happen**:
Mouse drift, unable to click the desktop designated location

I don't know if I configured it incorrectly for vnc cause above problem?

**How to reproduce it (as minimally and precisely as possible)**:
```js
use novnc

vmVnc() {
     // url params
      const vncUrl = `https://novnc.test/novnc.html?host=novnc.test&port=&path=k8s/clusters/local/apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachineinstances/centos-cloud/vnc&autoconnect=true&resize=scale`;
      window.open(vncUrl,"_blank");
    }
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (0.29.0):
- Kubernetes version (1.17.x)

**Comment by s1267** [comment]
Hi! Could you please tell me how the issue was resolved? Has a solution been found?

**Comment by JSchlarb** [comment]
```yaml
spec:
  domain:
    devices:
      inputs:
      - type: tablet
        bus: virtio
        name: tablet1
```

source https://kubevirt.io/user-guide/compute/virtual_hardware/#input-devices
