### ISSUE TITLE
Change the Windows resolution and restart automatically

### ISSUE THREAD

**Issue by watermelon-brother** [kubevirt/kubevirt#3484]
**What happened**:

**What you expected to happen**:
Change the Windows resolution and restart automatically when I visited the vm connect from the vnc.
**How to reproduce it (as minimally and precisely as possible)**:
After changing the resolution, it reboots automatically for a while, and then reboots all the time.

**Anything else we need to know?**:
kubectl logs vm-pod
```shell
{"component":"virt-launcher","level":"error","msg":"internal error: End of file from qemu monitor","pos":"qemuMonitorIO:712","subcomponent":"libvirt","thread":"19","timestamp":"2020-05-28T08:06:54.016000Z"}
```
**Environment**:
- KubeVirt version (v0.29.0)
- Kubernetes version (1.17.x)
- cdi version (1.17.0)

**Comment by watermelon-brother** [comment]
windows remote desktop is ok. but Change the Windows resolution and restart automatically will happen sometimes when I visited the vm connect from the vnc.
@rmohr

**Comment by rmohr** [comment]
Could you explain that a little bit more? Why does windows restart when you connect via VNC?

**Comment by watermelon-brother** [comment]
I changed the Windows resolution to 2k by the vnc view when the vm start immediately, general，the pod will restart automatically ,but It`s ok sometimes.
@rmohr
