### ISSUE TITLE
New metrics design proposal

### ISSUE THREAD

**Issue by ArthurSens** [kubevirt/kubevirt#3535]
# Add monitoring metrics

## Table of Contents

- [Summary](#summary)
- [Motivation](#motivation)
    - [Multiple issues](#multiple-issues)
  - [Goals](#goals)
- [Proposal](#proposal)
  - [Migration Metrics](#migration-metrics)
    - [Other Alternative](#other-alternative)
  - [Node Heartbeat metrics](#node-heartbeat-metrics)
  - [VMI metrics](#vmi-metrics)
  - [Snapshot metrics](#snapshot-metrics)
- [Design details](#design-details)
- [Implementation History](#implementation-history)

## Summary

Kubevirt is able to create VMs on top of K8s clusters, by adding business logic with its controllers and agents. By doing that, it is possible to run strong VMs to host applications that are not well suited to run as microservices and still have some advantages that Kubernetes provides, like scalability, easy monitoring and distributed computing.

However, KubeVirt lacks monitoring metrics to all its functionalities. If you are a "KubeVirt administrator", being obligated to make requests every now and then to keep track of multiple VMI Migrations and VMI status is quite troublesome. We need an alternative to simplify monitoring a KubeVirt environment.

This doc is an incomplete design proposal, which proposes new metrics to be exposed in a `prometheus-metrics-endpoint`. Prometheus and a third-party graphic tool will be responsible for making monitoring easier.

Any improvement to this proposal is welcome. Please add any new metric that you think is relevant and please comment anything that needs to be changed.

## Motivation

It is already possible to get information about multiple Kubevirts components through APIs. We just need to expose them.

#### Multiple issues

Lack of monitoring metrics is a long discussed topic on several Kubevirt issues

- virt-handler metrics do not integrate any k8s VMI properties (labels, names, etc): [kubevirt/kubevirt#2108](https://github.com/kubevirt/kubevirt/issues/2108)
- Add kubevirt_vmi_memory_total_bytes metric: [kubevirt/kubevirt#3081](https://github.com/kubevirt/kubevirt/issues/3081)
- Add more workload and infrastructure metrics: [kubevirt/kubevirt#3385](https://github.com/kubevirt/kubevirt/issues/3385)

### Goals

- Expose new monitoring metrics related to VMIs workloads
- Expose monitoring metrics related to VMI Migrations
- Expose monitoring metrics related to VMI Snapshots
- Expose monitoring metrics related to Node Heartbeats

### Migration Metrics

| Metric name | Labels | unit | type | Description |
|-|-|-|-|-|
| kubevirt_migration_time_total | `source`, `destination`, `vmi_name`, `vmi_namespace`, `method` | milisecond | counter | Total amount of time spent on VMI migrations |
| kubevirt_migration_errors_total | `source`, `destination`, `vmi_name`, `vmi_namespace`, `method` | n/a | counter | Total amount of errors when migrating VMIs |
| kubevirt_migration_total | `source`, `destination`, `vmi_name`, `vmi_namespace`, `method`, `status` | n/a | counter | Total amount of migrations |
| kubevirt_migration_limits_info | `parallel`, `outbound_parallel`, `timeout_per_GiB`, `bandwidth` | n/a | gauge | General configuration set for migrations. Value is always `1` |

Labels explanation:
* `source` - Source node where the VMI is being migrated from
* `destination` - Destination node where the VMI is being migrated to
* `vmi_name` - Name of the VMI which is being migrated
* `vmi_namespace` - Namespace of the VMI which is being migrated
* `method` - Migration method
* `status` - Migration status
* `parallel` - Number of parallel migrations allowed
* `outbound_parallel` - Number of parallel outbound migrations allowed per node
* `kubevirt_migration_bandwidth_limit` - Migrations bandwidth limit
* `timeout_per_GiB` - Timeout allowed per GiB being migrated

#### Other Alternative

`kubevirt_migration_limits_info` could be split into multiple metrics, as shown below:

| Metric name | Labels | unit | type | Description |
|-|-|-|-|-|
| kubevirt_migration_parallel_limit | n/a  | n/a | gauge | Number of parallel migrations allowed |
| kubevirt_migration_parallel_outbound_limit | `node` | n/a | gauge | Number of parallel outbound migrations allowed per node |
| kubevirt_migration_bandwidth_limit | `node` | bytes | gauge | Migrations bandwidth limit |
| kubevirt_migration_timeout_per_GiB | n/a  | miliseconds | gauge | Timeout allowed per GiB being migrated |

### Node Heartbeat metrics

| Metric name | Labels | unit | type | Description |
|-|-|-|-|-|
| kubevirt_heartbeat_total | `node`, `status` | n/a | counter | Counter of heartbeats per node |
| kubevirt_heartbeat_last | `node`, `status` | milisecond | gauge | Timestamp of last heartbeat  |

Labels explanation:
* `node` - Which node the heartbeat is related to
* `status` - Heartbeat status

### VMI metrics

| Metric name | Labels | unit | type | Description |
|-|-|-|-|-|
| kubevirt_vmi_age_seconds | `vmi_name`, `vmi_namespace` | seconds | gauge | Age of VMI in seconds |

Labels explanation:
* `vmi_name` - Name of the VMI
* `vmi_namespace` - Namespace of the VMI

### Snapshot metrics

> To be discussed

## Design details

> What needs to be done to expose the new metrics

## Implementation History

> To be implemented

**Comment by ArthurSens** [comment]
can be discussed through this [google doc](https://docs.google.com/document/d/1bEwrnZZkVsCtz0PSyzlxOdhupL6GTurkUYcz7TXFM1g/edit?usp=sharing).

**Comment by DanielQujun** [comment]
Is someone working on this? I think we need add `memory_usage_bytes` for VMI metrics.

**Comment by ArthurSens** [comment]
Hi @DanielQujun, yeah... there was a lot of PRs recently that are improving KubeVirt metrics exposure:

#3841 #3785 #3636 #3568 #3887, also another one that will auto-generate documentation about those metrics #3715

But this proposal has changed a lot since the creation of this issue, the [google doc](https://docs.google.com/document/d/1bEwrnZZkVsCtz0PSyzlxOdhupL6GTurkUYcz7TXFM1g/edit?usp=sharing) is being updated more frequently but it does not cover everything that is being done as well

About that memory metric, can you provide us an example where you need it?

**Comment by DanielQujun** [comment]
Hi @ArthurSens, thanks for your great enhancement works~

IIRC, most metrics of VMI we exposed ends with `total`, which means we need to calculate to get resource usage rate,  and about memory, I only found `kubevirt_vmi_memory_resident_bytes`.

IMHO, It's common that the user wants to know the VM's realtime load(e.g. CPU utilization, memory usage), then the user could tell that VM's memory is sufficient or sufficient. I'm not sure it's doable, but I have seen these metrics on other virtual machine platforms, like Virt-manager, OpenStack, XenServer, VMware...

It would be more convenient and clear for user to know the VM's resource usage.

**Comment by ArthurSens** [comment]
> IMHO, It's common that the user wants to know the VM's realtime load(e.g. CPU utilization, memory usage), then the user could tell that VM's memory is sufficient or insufficient.

hi @DanielQujun, once #3927 gets merged, I think it will be possible to do what you are describing
