### ISSUE TITLE
when issuing command on kubevirt/kubevirt openshift ci responds on /test /retest commands that it shouldn't

### ISSUE THREAD

**Issue by phoracek** [kubevirt/kubevirt#3559]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When issuing command on kubevirt/kubevirt openshift ci responds on /test /retest commands that it shouldn’t (because the jobs belong to kubevirt-bot) (example)

This happens for some time now (i.e. around a month).

Reason: the openshift ci bot is connected to the repo, therefore the openshift ci prow also reacts to comment commands.

**What you expected to happen**:

OpenShift bot does not comment on our retests unless there is a real typo. Not commenting at all may be also a viable option.

**Comment by phoracek** [comment]
cc @dhiller

**Comment by vladikr** [comment]
```
/test pull-kubevirt-e2e-k8s-1.16
/test pull-kubevirt-e2e-k8s-1.15-ceph
/test pull-kubevirt-e2e-k8s-1.17
```
```
@openshift-ci-robot
 
Member
openshift-ci-robot commented 33 seconds ago
@vladikr: The specified target(s) for /test were not found.
The following commands are available to trigger jobs:

/test e2e-azure-nested-virt
/test images
Use /test all to run the following jobs:

pull-ci-kubevirt-kubevirt-master-images
```
