### ISSUE TITLE
[flakey test] VM Live Migration Starting a VirtualMachineInstance migration monitor [test_id:2227]should abort a vmi migration without progress

### ISSUE THREAD

**Issue by phoracek** [kubevirt/kubevirt#3560]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Test
```
[rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system] VM Live Migration Starting a VirtualMachineInstance migration monitor [test_id:2227]should abort a vmi migration without progress
```
is blocking merges. See also the flakefinder history:

https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2020-06-14-168h.html#row0

It recently started to fail almost 100% of time, but was flaky before already. There may be a real issue in the config propagation code. https://github.com/kubevirt/kubevirt/pull/3542 tries to consistently wait until the config is distributed, but it still fails on the test.

This test was marked as pending in https://github.com/kubevirt/kubevirt/pull/3557.

**What you expected to happen**:

Issue of this test should be investigated and fixed.

**How to reproduce it (as minimally and precisely as possible)**:

Remove the "skip" and run the test.

**Comment by stu-gott** [comment]
Closing this issue as there are PR's to resolve it
