### ISSUE TITLE
periodic-kubevirt-tutorial-lab-testing fails on LAB003 (CDI?)

### ISSUE THREAD

**Issue by phoracek** [kubevirt/kubevirt#3564]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Periodic job testing our test lab has failed on one of the test cases. It seems like an CDI issue:

```
Starting /home/prow/go/src/kubevirt-tutorial/build/lab003.sh test_lab
#################### SOURCE OF TEST ####################
## LAB003

kubectl apply -f $HOME/kubevirt/kubevirt-operator-manifests/kubevirt-operator.yaml
kubectl config set-context --current --namespace=kubevirt
while ! kubectl get deployment virt-operator -n kubevirt --no-headers && echo 'Looping...'; do sleep 5; done
kubectl wait deployment virt-operator --for=condition=available --timeout=600s -n kubevirt
kubectl apply -f $HOME/kubevirt/kubevirt-operator-manifests/kubevirt-cr.yaml
while ! kubectl get deployment virt-api -n kubevirt --no-headers && echo 'Looping...'; do sleep 5; done
kubectl wait deployment virt-api --for condition=available --timeout=600s -n kubevirt
while ! kubectl get deployment virt-controller -n kubevirt --no-headers && echo 'Looping...'; do sleep 5; done
kubectl wait deployment virt-controller --for condition=available --timeout=600s -n kubevirt
kubectl get all -l kubevirt.io
virtctl version
kubectl apply -f $HOME/kubevirt/cdi-operator-manifests/cdi-operator.yaml
kubectl config set-context --current --namespace=cdi
while ! kubectl get deployment cdi-operator -n cdi --no-headers && echo 'Looping...'; do sleep 5; done
kubectl wait deployment cdi-operator --for condition=available --timeout=600s -n cdi
kubectl apply -f $HOME/kubevirt/cdi-operator-manifests/cdi-operator-cr.yaml

while ! kubectl get deployment cdi-apiserver -n cdi --no-headers && echo 'Looping...'; do sleep 5; done
while ! kubectl get deployment cdi-deployment -n cdi --no-headers && echo 'Looping...'; do sleep 5; done
while ! kubectl get deployment cdi-uploadproxy -n cdi --no-headers && echo 'Looping...'; do sleep 5; done
kubectl wait deployment -l cdi.kubevirt.io --for condition=available --timeout=600s -n cdi
kubectl get all
#################### SOURCE OF TEST ####################

-------
Test Name: lab003
Test Result: ERR
Test Expected Result: PASS
Real Time: 748.941
Retrying Test...
```

Logs: https://storage.googleapis.com/kubevirt-prow/logs/periodic-kubevirt-tutorial-lab-testing/1271405244500152320/build-log.txt?Expires=1592209505&GoogleAccessId=prow-46%40kubevirt-240711.iam.gserviceaccount.com&Signature=S7dv0Y3GBddU93mglfNd9ATQkgP9iny3lUvvX0tr2wcXgP61RfL4OLAQukaGdjCDY2eMTcheZr7QP26OI4Y29V7jRAVn2ZosyTVwBVyumc0RsxAGYhMJgjmXuqgGQYwsFXhD2DTtqbzBSJmnWQeVYuqTwVVpZzvI%2B0pQsLRU6LWluTPJ9JMMWeWMYbkCcPLSLMYjUpuOYFr7XSzqfJYyfOxtLopSXjldSFP0QA0ljhIV4SNZKvZCyRX2G43MeLaZwq9an8jX46NS%2BYYKtSFIvA2n5rZEvTAWcHa%2BHe2qX6YmMExbmQN7JqoL9xoae6rsuG%2FjOsuEz4vkfeJDZj2%2BDQ%3D%3D

CI build: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-tutorial-lab-testing/1271405244500152320

**Comment by maya-r** [comment]
kubectl apply -f $HOME/kubevirt/kubevirt-operator-manifests/kubevirt-operator.yaml
Is this lab expecting a particular filesystem layout? I'm not sure how this file would exist.
Should it be adjusted to point to the latest release on GitHub?

**Comment by phoracek** [comment]
@rmohr who would know details about the lab?

**Comment by dhiller** [comment]
There's a related issue open for some time now: kubevirt/kubevirt-tutorial#114

**Comment by rmohr** [comment]
/close

@phoracek you can see in the project-infra repo, when searching for the job to which repo it belongs.

Tracked in kubevirt/kubevirt-tutorial#114
