### ISSUE TITLE
[flakey test] should log libvirt start and stop lifecycle events of the domain [test_id:1641]

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#3573]
> /kind bug

**What happened**:

Today failing on K8s-1.18
https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2020-06-15-024h.html

last week saw it failing almost every time on the check for flakes lane (k8s-1.18)

locally it runs fun (checking in loops)

**What you expected to happen**:
test should pass

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I believe its matter of timeout, if i reach it, i will try to increase the timeout and run in loops on prow
checking loops of it locally, so far so good (without changes even)

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dhiller** [comment]
In the [weekly report it fails on k8s-1.17 and k8s-1.17-cnao also](https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2020-06-15-168h.html#row3), but not on k8s-1.18

**Comment by dhiller** [comment]
Example failure on k8s-1.17: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3228/pull-kubevirt-e2e-k8s-1.17/1266051356699922432

```
/root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:46
Timed out after 30.001s.
Logs should confirm pod deletion
Expected
    <string>: {"component":"virt-handler","level":"info","msg":"Processing event kubevirt-test-default/testvmiqh9k2lkcv7d6fg9kfbr95b7qq4h7hpqtmcw5scc5q8pwmzxx","pos":"vm.go:1041","timestamp":"2020-05-28T18:21:02.169562Z"}
    {"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled\n","name":"testvmiqh9k2lkcv7d6fg9kfbr95b7qq4h7hpqtmcw5scc5q8pwmzxx","namespace":"kubevirt-test-default","pos":"vm.go:1043","timestamp":"2020-05-28T18:21:02.169940Z","uid":"a3dcf913-eb36-4578-abbb-9c8b76d86e26"}
    {"component":"virt-handler","level":"info","msg":"Domain does not exist","pos":"vm.go:1050","timestamp":"2020-05-28T18:21:02.169980Z"}
    {"component":"virt-handler","level":"info","msg":"Updating cluster config to resource version '32665'","pos":"config-map.go:462","timestamp":"2020-05-28T18:21:02.221148Z"}
```

**Comment by dhiller** [comment]
Test runs where it failed:
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3414/pull-kubevirt-e2e-k8s-1.17/1263814834395287552
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3396/pull-kubevirt-e2e-k8s-1.17/1267950036650561536
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3487/pull-kubevirt-e2e-k8s-1.17/1268751963365838848
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3437/pull-kubevirt-e2e-k8s-1.17/1262348010570911744
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3441/pull-kubevirt-e2e-k8s-1.17/1262955401192673280
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3465/pull-kubevirt-e2e-k8s-1.17/1265897843323834369
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3228/pull-kubevirt-e2e-k8s-1.17/1266051356699922432

**Comment by dhiller** [comment]
@vladikr do you have time and bandwidth to look at this?

**Comment by danielBelenky** [comment]
/assign

I'm looking at this one.
I was finally able to reproduce locally (after 124 runs :rocket:)
It looks like the domain is being destroyed before we get to set the deletion timestamp on it when this occurs.
