### ISSUE TITLE
 SRIOV VirtualMachineInstance with sriov plugin interface [test_id:1755]should create a virtual machine with two sriov interfaces referring the same resource

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#3574]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
[This test](https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2020-06-15-024h.html#row1) failed once on the pull-kubevirt-e2e-kind-k8s-sriov-1.17.0 lane: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3507/pull-kubevirt-e2e-kind-k8s-sriov-1.17.0/1272424338078830592

**What you expected to happen**:

Test shouldn't have failed.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by phoracek** [comment]
We are currently addressing stability of the lane which causes a lot of the runs to fail in https://github.com/kubevirt/kubevirtci/pull/378.

/assign @ormergi

**Comment by maya-r** [comment]
If/when this is fixed, #3747 might be fixed as well.
