### ISSUE TITLE
[flaky CI] [test_id:3466]Should update vmi status with the proper columns using 'kubectl get vmi -w'

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#3578]
> /kind bug

**What happened**:
[rfe_id:3423][crit:high][vendor:cnv-qe@redhat.com][level:component]VmWatch [test_id:3466]Should update vmi status with the proper columns using 'kubectl get vmi -w'

This test is flaky for a long time, each week has it several times.

**What you expected to happen**:
Test should pass (or skipped meanwhile ?)

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by AlonaKaplan** [comment]
link a job with this test failing - https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3502/pull-kubevirt-e2e-k8s-1.16/1275668304685436928

**Comment by AlonaKaplan** [comment]
one more job with the same failure - https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3502/pull-kubevirt-e2e-k8s-1.17/1275668304681242624

**Comment by oshoval** [comment]
https://github.com/kubevirt/kubevirt/pull/3649
