### ISSUE TITLE
Improve image-upload guide to include necessary step to avoid using --insecure

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt#3584]
/kind bug

**What happened**:
* Deploy minikube, kubevirt, cdi, nodePort service for cdi-uploadproxy
* Showing kube config 
```
$ cat .kube/config
apiVersion: v1
clusters:
- cluster:
    certificate-authority: /home/crc/.minikube/ca.crt
    server: https://k8s.octacube.co:8443
  name: minikube
contexts:
- context:
    cluster: minikube
    user: minikube
  name: minikube
current-context: minikube
kind: Config
preferences: {}
users:
- name: minikube
  user:
    client-certificate: /home/crc/.minikube/profiles/minikube/client.crt
    client-key: /home/crc/.minikube/profiles/minikube/client.key
```
* Run virtctl
```
$ virtctl image-upload dv testvm --size=14Gi --image-path=/mnt/usb/testvm.vdi
DataVolume default/testvm created
Waiting for PVC testvm upload pod to be ready...
Pod now ready
Uploading data to https://k8s.octacube.co:30000

 0 B / 10.42 GiB [--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00% 0s

Post https://k8s.octacube.co:30000/v1alpha1/upload: x509: certificate is valid for cdi-uploadproxy, cdi-uploadproxy.cdi, cdi-uploadproxy.cdi.svc, not k8s.octacube.co
```
* Adjust dns then run virtctl
```
$ virtctl image-upload dv testvm --size=14Gi --image-path=/mnt/usb/testvm.vdi
DataVolume default/testvm created
Waiting for PVC testvm upload pod to be ready...
Pod now ready
Uploading data to https://cdi-uploadproxy.cdi.svc:30000

 0 B / 10.42 GiB [--------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00% 0s

Post https://cdi-uploadproxy.cdi.svc:30000/v1alpha1/upload: x509: certificate signed by unknown authority
```

**What you expected to happen**:
I expect...
1) the deployment should call on Kubernetes to create valid certificates (ideally the cdi-uploadproxy service has a cert with a correctly formed X509v3 Subject Alternative Name entry containing the Kubernetes endpoint and/or ip)
or 
2) the docs should contain a procedure to create valid certificates and patch CDI with them

Result:
`virtctl image-upload ...` runs securely at first deployment

**How to reproduce it (as minimally and precisely as possible)**:
* Deploy minikube, kubevirt, cdi, nodePort service for cdi-uploadproxy
* Run `virtctl image-upload dv testvm --size=14Gi --image-path=/path/to/image.qcow2`

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 
Client Version: version.Info{GitVersion:"v0.30.0", GitCommit:"736b4aec6b2e92f2ab09ccfa6c5eb79366e88e5a", GitTreeState:"clean", BuildDate:"2020-06-04T14:50:54Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"{gitVersion}", GitCommit:"{gitCommit}", GitTreeState:"{gitTreeState}", BuildDate:"{buildDate}", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):
$ .minikube/cache/linux/v1.18.3/kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:52:00Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.3", GitCommit:"2e7996e3e2712684bc73f0dec0200d64eec7fe40", GitTreeState:"clean", BuildDate:"2020-05-20T12:43:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications:
None

- Cloud provider or hardware configuration:
None

- OS (e.g. from /etc/os-release):
Fedora 32

- Kernel (e.g. `uname -a`):
$ uname -a
Linux cube0 5.6.6-300.fc32.x86_64 #1 SMP Tue Apr 21 13:44:19 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
$ minikube version
minikube version: v1.11.0
commit: 57e2f55f47effe9ce396cea42a1e0eb4f611ebbd

- Others:
minikube start command:
minikube start --driver=podman --container-runtime=cri-o --disk-size=50g --memory=8096m --apiserver-ips=10.88.0.1,10.88.0.2,10.88.0.3,10.88.0.4,10.88.0.5,10.88.0.6,10.88.0.7,10.88.0.8 --apiserver-name=k8s.octacube.co --apiserver-names=k8s.octacube.co

**Comment by mazzystr** [comment]
I was able to get this to work
```
$ virtctl image-upload dv testvm --size=14Gi --image-path=/mnt/usb/testvm.vdi
Using existing PVC default/testvm
Uploading data to https://k8s.octacube.co:30000

 3.48 GiB / 10.42 GiB [=========================================================>-------------------------------------------------------------------------------------------------------------------]  33.38% 06m42s
```

Obtain a cert from a certificate authority with a CN of Kubernetes dns endpoint (ie k8s.octacube.co)

Manually
* `kubectl edit secret/cdi-uploadproxy-server-cert -n cdi`
* Adjust the value for tls.crt and tls.key
* `kubectl delete pod/cdi-uploadproxy-*`

More automated
* `for i in tls.crt tls.key; do kubectl patch -n cdi secret/cdi-uploadproxy-server-cert -p '{"data": {"'${i}'": "'`echo -n "$(cat ${i})" | base64 | tr -d '\n'`'"}}'; done`
* `kubectl rollout restart deployment.apps/cdi-uploadproxy -n cdi`

**Comment by rmohr** [comment]
/reopen

/assign @codificat 

@codificat this would probably just be a matter of documenting how to do this, or why it is fine to have insecure in a demo environment.

**Comment by codificat** [comment]
> I was able to get this to work

@mazzystr would you be able to contribute the procedure you followed to the documentation?

**Comment by jobbler** [comment]
This should be closed by the following user guide pr.
https://github.com/kubevirt/user-guide/pull/438

**Comment by mazzystr** [comment]
All good here.  Closing.....
