### ISSUE TITLE
make deps-update broken

### ISSUE THREAD

**Issue by mhenriks** [kubevirt/kubevirt#3594]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

`kubevirt.io/client-go` is including `kubevirt.io/pkg` which is causing a dependency cycle.

```
➜  kubevirt git:(master) ✗ make deps-update
SYNC_VENDOR=true hack/dockerized " ./hack/dep-update.sh && ./hack/dep-prune.sh && ./hack/bazel-generate.sh"
go version go1.12.8 linux/amd64

go version go1.12.8 linux/amd64
+ export GO111MODULE=on
+ GO111MODULE=on
+ cd staging/src/kubevirt.io/client-go
+ go get ./...
go: finding kubevirt.io/kubevirt/pkg/handler-launcher-com/cmd latest
go: finding kubevirt.io/kubevirt/pkg/handler-launcher-com latest
go: finding kubevirt.io/kubevirt/pkg latest
go: finding kubevirt.io/client-go v0.0.0-00010101000000-000000000000
go: kubevirt.io/client-go@v0.0.0-00010101000000-000000000000: unknown revision 000000000000
go: error loading module requirements
make: *** [Makefile:78: deps-update] Error 1
```

https://github.com/kubevirt/kubevirt/blob/master/staging/src/kubevirt.io/client-go/api/v1/types.go#L42

Caused by this PR:  https://github.com/kubevirt/kubevirt/pull/3455

**What you expected to happen**:

`make deps-update` should work

**How to reproduce it (as minimally and precisely as possible)**:

run `make deps-update` on latest master 

currently at `82cbf4822c1708472e1dc2819705063125274a93`

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
> https://github.com/kubevirt/kubevirt/blob/master/staging/src/kubevirt.io/client-go/api/v1/types.go#L42
> 
> Caused by this PR: #3455

@ashleyschuett would you mind having a look? Should not be too hard to fix.

**Comment by rmohr** [comment]
@mhenriks thx for investigating,
