### ISSUE TITLE
test lanes are running for more than 7 hours and timeout

### ISSUE THREAD

**Issue by vladikr** [kubevirt/kubevirt#3596]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
k8s test lanes are running for more than 7 hours and fail due to incompletion.
This affects most of the lanes: 1.15-ceph, 1.16, 1.17, 1.18

For example: 
```
Test started today at 3:23 AM failed after 7h5m4s.
```

```
{"component":"entrypoint","file":"prow/entrypoint/run.go:164","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 7h0m0s timeout","time":"2020-06-18T14:32:52Z"}
```
**What you expected to happen**:
Tests should complete on time.
**How to reproduce it (as minimally and precisely as possible)**:

**Comment by rmohr** [comment]
@dhiller created #3609 to at least give us a little bit more hints.

**Comment by rmohr** [comment]
The issue is resolved right now. A greenhouse restart made the issue go away. We failed to identify root causes. Could be a pod network issue, the node where the cache was scheduled or an issue in greenhouse itself.

**Comment by brybacki** [comment]
there are still issues like that 
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3766/pull-kubevirt-e2e-k8s-1.17/1280386915538833408

**Comment by dhiller** [comment]
Not sure how the timetamp addition has been going? @danielBelenky I remember there was an issue with that? Or is that working? Should I revive the simpler #3609?

**Comment by rmohr** [comment]
/close

Timestamps are added and there is now in general a node which only hosts caches to avoid sideeffects from other workloads.
