### ISSUE TITLE
[flakey test] Networking VirtualMachineInstance with custom dns [test_id:1779] should have custom resolv.conf

### ISSUE THREAD

**Issue by vladikr** [kubevirt/kubevirt#3602]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
```
[rfe_id:694][crit:medium][vendor:cnv-qe@redhat.com][level:component]Networking VirtualMachineInstance with custom dns [test_id:1779]should have custom resolv.conf 

/root/go/src/kubevirt.io/kubevirt/tests/vmi_networking_test.go:666
 Unexpected error:
     <expect.TimeoutError>: 15000000000
     expect: timer expired after 15 seconds
 occurred
 /root/go/src/kubevirt.io/kubevirt/tests/vmi_networking_test.go:691
```

**What you expected to happen**:
The k8s-cnao-1.17 lane often fails with the above error

**Comment by AlonaKaplan** [comment]
links to failing jobs - 
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3550/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1274404687931510784
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3406/pull-kubevirt-e2e-k8s-1.18/1274979489599721472

**Comment by oshoval** [comment]
```
				&expect.BExp{R: "nameserver 4.2.2.1"},
				&expect.BExp{R: "\\$"},
```
i would suggest to add sending \n between those two, because i see in the logs the first one "steals" the prompt when the race occurs.
