### ISSUE TITLE
Presubmits jobs are failing due to wrong URL archives.fedoraproject.org

### ISSUE THREAD

**Issue by ksimon1** [kubevirt/kubevirt#3603]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
Presubmits jobs are failing due to wrong URL archives.fedoraproject.org

see here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3521/pull-kubevirt-e2e-k8s-1.15-ceph/1273885003331145729

**Comment by rmohr** [comment]
The issue seems to be that the `dl.fedora.org` is down. All dependencies except  the `which` rpm were mirrored to ur gcs bucket. After the packet was kicket out by greenhouse (the bazel cache), bazel could not fall back to our gcs bucket to add it to the cache again.

**Comment by rmohr** [comment]
I will now also take the time to finish the postsubmit job which will automatically upload the dependencies and create a PR.
