### ISSUE TITLE
OpenShift CI nightly build has failing tests

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#3606]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

Several tests on the KubeVirt nightly build on OpenShift are failing: https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-master-e2e-periodic-azure-nested-virt/1273813341147500544

This is caused in part due to misconfiguration of the nightly (i.e. errors that point to not using shas for images), possibly also the test setup, in other cases the causes need to get investigated.

**What you expected to happen**:

Test lane should be green

**How to reproduce it (as minimally and precisely as possible)**:

Wait for [nightly build](https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/?type=periodic&job=*-ci-kubevirt-kubevirt-*) and look at the failures.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ormergi** [comment]
I notice that on today build job there were only 13 tests, is it ok?
https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-master-e2e-periodic-azure-nested-virt/1275263007852597248

**Comment by dhiller** [comment]
No, normally it should look like this: https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-master-e2e-periodic-azure-nested-virt/1275625426416308224
The test run you were looking at is one where the setup of the test cluster failed. These are the "parent" tests that are related to creating the images, checking infra etc. Normally there should be a number of 500+ tests.

**Comment by dhiller** [comment]
Should be fixed with run tonight: https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/?type=periodic&job=*-ci-kubevirt-kubevirt-*

**Comment by stu-gott** [comment]
@dhiller Is the state of this issue still accurate? Is it still an open issue?

**Comment by dhiller** [comment]
@stu-gott thanks for the reminder, no, we should be good here.

/close
