### ISSUE TITLE
[Flaky test][test_id:1200]Probes for readiness should succeed with working HTTP probe and http server

### ISSUE THREAD

**Issue by ksimon1** [kubevirt/kubevirt#3611]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug

**What happened**:
[ref_id:1182]Probes for readiness should succeed [test_id:1200][posneg:positive]with working HTTP probe and http server test is failing 

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3588/pull-kubevirt-e2e-k8s-1.18/1273368964344320000

**Comment by orenc1** [comment]
recurred again in:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3726/pull-kubevirt-e2e-k8s-1.18/1278299846477877248
