### ISSUE TITLE
[Flaky test][test 3151] should be able to update kubevirt install when operator updates if no custom image tag is set

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#3620]
/kind bug

/label build-officer
**What happened**:

on 13.6 this test fails, it doesnt fail a lot, but when it does it might cause the cluster to become unstable. (see that that runs had lots of problems afterwards, and it cause flake-finder to be spammed with failures).

Its name can imply on it "should be able to update kubevirt install when operator updates if no custom image tag is set", since it updates kubevirt install

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3546/pull-kubevirt-e2e-k8s-1.17/1271647692564467712

Test fails, and it looks like that the cluster become unstable after it fails, (see all the fails after it, and the title of the test 

**What you expected to happen**:
Test should pass, or at least, meanwhile, not spam flake-finder, in case the spamming is due to its failure.
For example if a crucial operation failed. (nice to have, unless just root problem should be focused).

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fgimenez** [comment]
/reopen 

Happened here again https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-latest/1358173799794610177

**Comment by fgimenez** [comment]
Happened again https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev/1361797805819039745 after the error a lot of subsequent tests fail and the build finally times out
