### ISSUE TITLE
[flaky test][test 3245] should not migrate more than two VMIs at the same time from a node

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#3621]
/kind bug
/label build-officer

**What happened**:

Test 3245 failed today, (saw it failed at the past from time to time. around once a week or less)
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3555/pull-kubevirt-e2e-k8s-1.17/1274551910958895104

lane pull-kubevirt-e2e-k8s-1.17

**What you expected to happen**:
Test should pass

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by stu-gott** [comment]
Looking at the specific failure in the prow log, this looks like the migration simply ran out of time. I've seen this test fail where none of the 4 VMIs ever started migrating. In this case two nodes actually did complete a migration in time.

It looks like the test is set to time out after 4 minutes. @vladikr is it reasonable to raise that limit?

**Comment by jean-edouard** [comment]
Duplicated by https://github.com/kubevirt/kubevirt/issues/3990
Though this is the first issue filed, the other one is where the action is happening.
@oshoval, please close.
