### ISSUE TITLE
[Flaky CI] pull-kubevirt-e2e-k8s-1.16-ceph cluster-up fails

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#3622]
/kind bug
/label build-officer

**What happened**:
pull-kubevirt-e2e-k8s-1.16-ceph

cluster-up fails
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3590/pull-kubevirt-e2e-k8s-1.16-ceph/1274679127764373504

```
+ kubectl --kubeconfig /etc/kubernetes/admin.conf create -f /tmp/ceph/csi-rbdplugin-attacher.yaml
service/csi-rbdplugin-attacher created
error: unable to recognize "/tmp/ceph/csi-rbdplugin-attacher.yaml": no matches for kind "StatefulSet" in version "apps/v1beta1"
provisioning Ceph CSI failed
Makefile:96: recipe for target 'cluster-up' failed
make: *** [cluster-up] Error 1
++ collect_debug_logs
```

**What you expected to happen**:
cluster-up should pass

**How to reproduce it (as minimally and precisely as possible)**:
just run it (saw on prow 2/2 times, didnt test locally)
**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by oshoval** [comment]
should we disable the lane until its fixed?
it spams the results + use resources atm

**Comment by dhiller** [comment]
I think we rather should disable reporting and retire the status. @rmohr?

**Comment by dhiller** [comment]
Or just rollback to 1.15-ceph?

**Comment by dhiller** [comment]
So we just disabled reporting on the ceph lane, am now working on failures.

**Comment by dhiller** [comment]
In general `cluster-up` fails on following health check error:

```
2020-06-21 12:28:58.718475 mon.cbebc2a50388 [INF] osd.0 192.168.66.2:6802/470 boot
2020-06-21 12:28:58.720247 mon.cbebc2a50388 [WRN] Health check failed: too few PGs per OSD (24 < min 30) (TOO_FEW_PGS)
2020-06-21 12:28:59.729607 mon.cbebc2a50388 [INF] daemon mds.0 is now active in filesystem cephfs as rank 0
```

**Comment by dhiller** [comment]
Related documentation is this: https://docs.ceph.com/docs/mimic/rados/operations/placement-groups/#choosing-number-of-placement-groups

**Comment by dhiller** [comment]
@awels @mhenriks maybe you can chime in here? Is that easily fixable?

**Comment by rmohr** [comment]
but ceph works right now on -1.15. We use the same containers and start flow. Are you sure it hangs there?

**Comment by awels** [comment]
This is highly likely because the snapshot api went from alpha to beta between 1.15 and 1.17. We have a PR https://github.com/kubevirt/containerized-data-importer/pull/1206 that updates that for CDI

**Comment by oshoval** [comment]
what about this error that appear in the logs ?
```
error: unable to recognize "/tmp/ceph/csi-rbdplugin-attacher.yaml": no matches for kind "StatefulSet" in version "apps/v1beta1"
```

**Comment by awels** [comment]
Have to look up which kind/version stateful sets are now? Maybe apps/v1?

**Comment by dhiller** [comment]
> but ceph works right now on -1.15. We use the same containers and start flow. Are you sure it hangs there?

I reproduced in on kubevirtci locally

**Comment by awels** [comment]
yeah should be apps/v1 I am guessing apps/v1beta1 was deprecrated for a while and got removed in 1.17 or 1.18

**Comment by dhiller** [comment]
So, I can't really think of what makes sense right now? I saw that @mhenriks is already working on a rook-ceph lane for 1.17 for kubevirt, should we wait on this and remove the 1.16-ceph lan entirely? Because 1.15 we are not supporting any more?

**Comment by rmohr** [comment]
> So, I can't really think of what makes sense right now? I saw that @mhenriks is already working on a rook-ceph lane for 1.17 for kubevirt, should we wait on this and remove the 1.16-ceph lan entirely? Because 1.15 we are not supporting any more?

Depends on how long that takes. If it still takes some time, just update the manifests in kubevirtci and reprovision 1.17 and 1.18.

**Comment by rmohr** [comment]
But I think we should efinitely disable the job.
