### ISSUE TITLE
[flaky test][test 1678]should report defined CPU model

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#3623]
/kind bug
/label build-officer

**What happened**:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3566/pull-kubevirt-e2e-k8s-1.17/1274562732359684096

test 1678 failed on 1.17 lane

**What you expected to happen**:
test should pass

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
It runs in a timeout when we wait for the VMI to be deleted:

```
/root/go/src/kubevirt.io/kubevirt/tests/utils.go:3195
Timed out after 30.000s.
Expected
    <bool>: false
to be true
/root/go/src/kubevirt.io/kubevirt/tests/vmi_configuration_test.go:1423
```

I can see in the logs that the VMI gets deleted and that virt-handler ensures that the VMI is shutoff. The VMI also almost immediately reports that it is shutoff, but the pod seems to hang around for some time.

Here when the VMI was shutoff:

```
{"component":"virt-handler","kind":"","level":"info","msg":"Grace period expired, killing deleted VirtualMachineInstance testvminqnl44v69tmmbfl2x7nwtvr7j4tv4cqkvkq4qfc4vbcbn766","name":"testvminqnl44v69tmmbfl2x7nwtvr7j4tv4cqkvkq4qfc4vbcbn766","namespace":"kubevirt-test-default","pos":"vm.go:1495","timestamp":"2020-06-21T06:58:27.761728Z","uid":"afd1caa5-4f9a-4ee5-abdd-afee5b5c9165"}
```

and here when it could finally be moved to a stopped state:

```
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Failed\n","name":"testvmi2fqjhl6nl76wwvstgkcngkwn7cvsrttvjwbdg4d5jfh9l6rg","namespace":"kubevirt-test-default","pos":"vm.go:1035","timestamp":"2020-06-21T06:58:37.316282Z","uid":"4361706c-33f0-40e9-8768-78b1ba3f5dab"}
```

Note that when we finally collected the data, both the VMI and the Pod were already gone. I would suggest the following as individual steps:

 1. Increase the timeout to 60 seconds, to give the kubelet more time (which is known to have a huge variation regarding to pod deletion speed)
 2. Finally collect the kubelet logs to allow us investigating such issues easier.

**Comment by rmohr** [comment]
/assing @enp0s3 

> 1. Increase the timeout to 60 seconds, to give the kubelet more time (which is known to have a huge variation regarding to pod deletion speed)

Igor, would you mind doing a PR?

**Comment by enp0s3** [comment]
> /assign @enp0s3
> 
> > 1. Increase the timeout to 60 seconds, to give the kubelet more time (which is known to have a huge variation regarding to pod deletion speed)
> 
> Igor, would you mind doing a PR?

@rmohr Sure np.

**Comment by enp0s3** [comment]
> /assign @enp0s3
> 
> > 1. Increase the timeout to 60 seconds, to give the kubelet more time (which is known to have a huge variation regarding to pod deletion speed)
> 
> Igor, would you mind doing a PR?

@rmohr PR https://github.com/kubevirt/kubevirt/pull/3632

**Comment by AlonaKaplan** [comment]
@enp0s3 the failure happened [again](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3502/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1275775060711313408).

Seems that is was on a PR that was merged after your.

Please check if the issue should be reopened.

**Comment by oshoval** [comment]
> @enp0s3 the failure happened [again](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3502/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1275775060711313408).
> 
> Seems that is was on a [PR](https://github.com/kubevirt/kubevirt/pull/3502) that was merged after your.
> 
> Please check if the issue should be reopened.

this time its the bug that #3543 fixes, we can see there exactly that it took the 0 from the SND
and that it couldnt add the nameserver (3 bugs affect it and are addressed in the PR)

**Comment by rmohr** [comment]
/reopen

Let's ensure that the failing tests were not triggered before this here was merged.

**Comment by qinqon** [comment]
@rmohr I see test_id 1678 being run at k8s-1.16 and k8s-1.18 lanes and passing at the PR before merge

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3632/pull-kubevirt-e2e-k8s-1.18/1275376117397590016
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3632/pull-kubevirt-e2e-k8s-1.16/1275754656672256000

**Comment by qinqon** [comment]
I don't see this at latest flake finder closing the issue again.

/close
