### ISSUE TITLE
Unable to deploy kubevirt in minikube

### ISSUE THREAD

**Issue by shubhindia** [kubevirt/kubevirt#3624]
/kind bug
I am trying to deploy kubevirt on minikube but getting below error.
{"component":"virt-operator","level":"info","msg":"failed to load the certificate in /etc/virt-operator/certificates","pos":"cert-manager.go:173","reason":"open /etc/virt-operator/certificates/tls.crt: no such file or directory","timestamp":"2020-06-21T17:31:38.578176Z"}
I tried with both driver=none and kvm2 but same result. 

I am using minikube version 1.11.0, k8s version 1.18.3, kubevirt version 0.29.2

**Comment by ashleyschuett** [comment]
Hey! what guide are you following? or how are you trying to set KubeVirt up so?

**Comment by shubhindia** [comment]
Hi.. I am following below document to deploy kubevirt. 
https://kubevirt.io/2018/Hello-KubeVirt-on-Minikube.html

**Comment by ashleyschuett** [comment]
Can you try using this guide instead https://kubevirt.io/quickstart_minikube/ ? it's the updated way to install kubevirt on minikube. 

You can also try downloading the new 1.12 beta version of minikube https://github.com/kubernetes/minikube/releases/tag/v1.12.0-beta.0. KubeVirt has been added as an add on and can be used by running `minikube addon enable kubevirt`.

**Comment by mazzystr** [comment]
@codificat This [blog](https://kubevirt.io/2018/Hello-KubeVirt-on-Minikube.html) post is obsolete and should be removed from the blogs pages.  This gets back to how our discussion on ensuring new users are directed to the correct GEtting Started page.

**Comment by codificat** [comment]
Thanks for the report - the blog post has now been removed as discussed.

There's also work in progress to improve the mentioned [minikube quickstart](https://kubevirt.io/quickstart_minikube/) page to incorporate the kubevirt addon, among other improvements.
