### ISSUE TITLE
[flaky ci] ImageUpload Upload an image and start a VMI with PVC Should succeed

### ISSUE THREAD

**Issue by awels** [kubevirt/kubevirt#3630]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> Uncomment only one, leave it on its own line:
>
/kind bug
/label build-officer
> /kind enhancement

**What happened**:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3555/pull-kubevirt-e2e-k8s-1.17/1274551910958895104

**What you expected to happen**:
test should pass.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mhenriks** [comment]
Let's see how https://github.com/kubevirt/kubevirt/pull/3571 affects this test.  Upload proxy->upload server communication was tightened up a bit.  Also, virtctl now uses the new "async" upload endpoint

**Comment by qinqon** [comment]
Not happening at latest flakefinder closing this issue https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2020-06-26-024h.html
