### ISSUE TITLE
[rfe_id:588] ContainerDisk Starting from custom image location with disk at /custom-disk/downloaded [test_id:1466]should boot normally

### ISSUE THREAD

**Issue by awels** [kubevirt/kubevirt#3631]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> Uncomment only one, leave it on its own line:
>
/kind bug
/label build-officer
> /kind enhancement

**What happened**:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3544/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1274612562545086464

**What you expected to happen**:
test should pass.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by AlonaKaplan** [comment]
Another job with the same issue - https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3502/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1275865685297205248

**Comment by oshoval** [comment]
about the run in the title 

dupe for sure of #3575 
i see all the syndromes
1. kvm is missing
2. virt-handler crashed due to panic (see virt-handler 1_* previous)

**Comment by oshoval** [comment]
we can close it i think, since #3713 was merged.

**Comment by rmohr** [comment]
/close

> we can close it i think, since #3713 was merged.

Yes, the corresponding logs for this show that virt-handler crashed on this test.
