### ISSUE TITLE
Drop qemu-wrapper

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#364]
The wrapper needs to be dropped to use libvirt as intended.

Opening this tracker because it might not happen in one PR but in several steps.

**Comment by warmchang** [comment]
Hi @fabiand  , what is the diffrence between the VMs created by kubevirt and virsh tool?
And the VM created by kubevirtis a really VM or just a logical VM (VM in container similar to the DinD),  it can be managed by virsh or not?

**Comment by fabiand** [comment]
VMs created by KubeVirt will internally be managed by libvirt. Thus if you use virsh, you will see KubeVirt VMs as regular VMs.

And thus, yes, the VMs are really true full fledged VMs (qemu processes, managed by libvirt) - KubeVirt is defining an API to allow you to specifiy them like you could do it with libvirt directly.

Today you can change the VMs using virsh, but the virt-handler will notice and will react to it.

Anyhow, this ticket is about a wrapper we introduced to move VMs into the correct control group.

**Comment by warmchang** [comment]
@fabiand , Thank you for your detailed explanation, I understand.

**Comment by davidvossel** [comment]
While the qemu wrapper does still exist, it's functionality has been greatly reduced. It's effectively invisible to libvirt now.  The wrapper only acts as a way to place the qemu process in the POD's cgroups. The qemu process itself now inherits the wrapper's pid.

**Comment by fabiand** [comment]
Probably fixed with #663

**Comment by rmohr** [comment]
Already gone.

**Comment by rmohr** [comment]
Ups still there.

**Comment by davidvossel** [comment]
#663 removes the wrapper
