### ISSUE TITLE
[flaky test] VM Live Migration with a live-migrate eviction strategy set [ref_id:2293] with a VMI running with an eviction strategy set with node tainted during node drain [test_id:2224] should handle mixture of VMs with different eviction strategies.

### ISSUE THREAD

**Issue by RamLavi** [kubevirt/kubevirt#3644]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
test fails [rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system] VM Live Migration with a live-migrate eviction strategy set [ref_id:2293] with a VMI running with an eviction strategy set with node tainted during node drain [test_id:2224] should handle mixture of VMs with different eviction strategies.

prow logs:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3639/pull-kubevirt-e2e-k8s-1.17/1275544608746508288
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3488/pull-kubevirt-e2e-k8s-1.17/1275378384230158336

**What you expected to happen**:
test should pass.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by AlonaKaplan** [comment]
link to one more failing job with the same error: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3502/pull-kubevirt-e2e-k8s-1.17/1275668304681242624

**Comment by AlonaKaplan** [comment]
Another job with the same failure - https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3502/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1275546119522226176

**Comment by qinqon** [comment]
I don't see it at latest flake finder https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2020-06-26-024h.html

**Comment by ashleyschuett** [comment]
Both these test failures are from when PR https://github.com/kubevirt/kubevirt/pull/3488 was merged. The error ```{"component":"virt-handler","level":"error","msg":"failed to read from cache file: open /var/run/kubevirt-private/network-info-cache/44f1331f-7850-428f-ab46-8da01b40925e/default: no such file or directory","pos":"vm.go:415","reason":"open /var/run/kubevirt-private/network-info-cache/44f1331f-7850-428f-ab46-8da01b40925e/default: no such file or directory","timestamp":"2020-06-23T14:11:00.743780Z"}``` from https://github.com/kubevirt/kubevirt/pull/3488/files#diff-27207346391eaa19190c76760eb8851fR465 this error then re-queuess the vmi until the migration fails. 

This change however was reverted with PR https://github.com/kubevirt/kubevirt/pull/3641 

Since this error has already been removed with reverting this PR I believe we can close this issue.

**Comment by stu-gott** [comment]
This was fixed by #3641

**Comment by danielBelenky** [comment]
Closing as this was fixed with the revert.

**Comment by awels** [comment]
I am seeing this particular test fail here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3946/pull-kubevirt-e2e-k8s-1.16/1292962824393330688 but that might just be the CI being super slow.
