### ISSUE TITLE
[flaky-test] [rfe_id:588][crit:medium][vendor:cnv-qe@redhat.com][level:component]ContainerDisk [rfe_id:4052][crit:high][vendor:cnv-qe@redhat.com][level:component]VMI disk permissions with ephemeral registry disk [test_id:4299]should not have world write permissions

### ISSUE THREAD

**Issue by RamLavi** [kubevirt/kubevirt#3645]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
test failed: [rfe_id:588][crit:medium][vendor:cnv-qe@redhat.com][level:component]ContainerDisk [rfe_id:4052][crit:high][vendor:cnv-qe@redhat.com][level:component]VMI disk permissions with ephemeral registry disk [test_id:4299]should not have world write permissions

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3639/pull-kubevirt-e2e-k8s-1.16/1275544608742313985
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fgimenez** [comment]
/reopen

Same test failing here https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev-prev/1363609743758725121 looks like the reason is different though
