### ISSUE TITLE
[prow] running a postsubmitted test failed with - fatal: Couldn't find remote ref deployment-strategy-recreate

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#3655]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

Running a postsubmitted test failed with - fatal: Couldn't find remote ref deployment-strategy-recreate
The failure happened on nmstate/kubernetes-nmstate repo.

Link to the job - https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/publish-kubernetes-nmstate/1275716907839787008

**What you expected to happen**:
Shoudn't fail.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
/close

Moved to nmstate: https://github.com/nmstate/kubernetes-nmstate/issues/567
