### ISSUE TITLE
postsubmit-kubevirtci-bump-kubevirt job fails with "could not start the process" error

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#3656]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
postsubmit-kubevirtci-bump-kubevirt job fails with error -
"could not start the process: fork/exec hack/autobump-kubevirtci.sh kubevirt-bot /etc/github/oauth kubevirt-bot rmohr+kubebot@redhat.com: no such file or directory"

Link to the failing job - https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/postsubmit-kubevirtci-bump-kubevirt/1276122750972334080

**What you expected to happen**:
Shouldn't fail

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
/close

I was experimenting with this new job. Sorry for the noise.
