### ISSUE TITLE
postsubmit-kubevirtci-bump-kubevirt fails with "/etc/github/oauth: No such file or directory" error

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#3657]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
postsubmit-kubevirtci-bump-kubevirt fails with errors -
fatal: cannot run cat /etc/github/oauth: No such file or directory
fatal: could not read Password for 'https://kubevirt-bot@github.com': No such device or address

Link to the failing job: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/postsubmit-kubevirtci-bump-kubevirt/1276127406909820928

May be relate to: https://github.com/kubevirt/kubevirt/issues/3656

**What you expected to happen**:
Shouldn't fail

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
/close

I was experimenting with this new job. That were just test runs. Sorry for the noise.
