### ISSUE TITLE
[flaky CI] [test_id:2226] VM Live Migration Starting a VirtualMachineInstance live migration cancelation should be able to cancel a migration with ContainerDisk

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#3662]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
kubevirt-e2e-k8s-1.16 lane -

[rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system]  VM Live Migration Starting a VirtualMachineInstance  live migration  cancelation should be able to cancel a migration [test_id:2226]with  ContainerDisk expand_less | 3m0s
-- | --
/root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43 Expected     <v1.VirtualMachineInstanceMigrationPhase>: Failed not to equal     <v1.VirtualMachineInstanceMigrationPhase>: Failed /root/go/src/kubevirt.io/kubevirt/tests/migration_test.go:266

Link to the failing job: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3502/pull-kubevirt-e2e-k8s-1.16/1275550270280962048

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by qinqon** [comment]
This test has being working last 24h I think we can close it.

/close

**Comment by orenc1** [comment]
/reopen
This test case failure recurred today, on `pull-kubevirt-e2e-k8s-1.17` lane:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3708/pull-kubevirt-e2e-k8s-1.17/1278479781469360129

**Comment by oshoval** [comment]
@phoracek i would like to work on this one if possible
thanks

**Comment by phoracek** [comment]
@oshoval if you have a direction, you should record it here.

**Comment by oshoval** [comment]
Its an educated guess, looking on other instances where the error occurred, that might have connection with this one.
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3713/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1277959105457164290

It shows that ipv6 wasn't configured, and it should be configured by cloud init, with the route, and to verify that the guest agent was downloaded
