### ISSUE TITLE
[flaky ci][ipv6 lane] command SyncVMI failed: LibvirtError qemu unexpectedly closed the monitor KVM: Cannot allocate memory

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#3665]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

The error happened on this test, but seems to be unrelated to the test itself -
Networking  VirtualMachineInstance with masquerade binding mechanism  [test_id:1780]should allow regular network connection without a specific  port number

/root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43 Unexpected Warning event received: testvmizbpbhgd8hfqfrkcm8gr2fkfmwzfbpprb9qhj4hcfhlrlvvxx,0a00e945-52d0-4798-817a-5e0190bbb75f: server error. command SyncVMI failed: "LibvirtError(Code=1, Domain=10, Message='internal error: qemu unexpectedly closed the monitor: ioctl(KVM_CREATE_VM) failed: 12 Cannot allocate memory\n2020-06-24T16:25:43.013045Z qemu-kvm: failed to initialize KVM: Cannot allocate memory')" Expected     <string>: Warning not to equal     <string>: Warning /root/go/src/kubevirt.io/kubevirt/tests/utils.go:409

link to the failing job : https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3502/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1275775060711313408

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by AlonaKaplan** [comment]
//kind bug cancel

**Comment by AlonaKaplan** [comment]
Another test with the same error =  


Storage  Starting a VirtualMachineInstance  [rfe_id:2298][crit:medium][vendor:cnv-qe@redhat.com][level:component]  With HostDisk and PVC initialization With a HostDisk defined With  'DiskExistsOrCreate' type Should create a disk image and start  [test_id:3057]with sata driver expand_less | 25s
-- | --
/root/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43 Unexpected Warning event received: testvmi2jtwj2zb8zrdnh959nwlfvwftvltkftwgct7czpl9lrscjtt,6156b2c4-aade-4c73-b7c9-ed8690b3ee07: server error. command SyncVMI failed: "LibvirtError(Code=1, Domain=10, Message='internal error: qemu unexpectedly closed the monitor: ioctl(KVM_CREATE_VM) failed: 12 Cannot allocate memory\n2020-06-24T16:09:22.465889Z qemu-kvm: failed to initialize KVM: Cannot allocate memory')" Expected     <string>: Warning not to equal     <string>: Warning /root/go/src/kubevirt.io/kubevirt/tests/utils.go:409

The job is the same as in the description.

**Comment by AlonaKaplan** [comment]
More tests failing with the same error - https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3641/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1275693251352858624

**Comment by rmohr** [comment]
Seeing Another one: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3681/pull-kubevirt-e2e-k8s-cnao-1.17/1276419455433314305

**Comment by maya-r** [comment]
I am seeing related failures with slightly different failure messages

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3652/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1276487026698358785
VM Live Migration Starting a VirtualMachineInstance migration security [test_id:2303][posneg:negative] should secure migrations with TLS
command SyncVMI failed: "LibvirtError(Code=67, Domain=10, Message='unsupported configuration: Emulator '/usr/libexec/qemu-kvm' does not support virt type 'kvm'')"


https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3598/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1276634749405761536
Prometheus Endpoints [test_id:4137]should find one leading virt-operator and two ready
command SyncVMI failed: "failed to invoke qemu-img: open /dev/null: operation not permitted"

It would be interesting to see whether there's any messages in the dmesg of the host, or maybe kind is introducing a resource limit.

**Comment by rmohr** [comment]
An update on 

```
"LibvirtError(Code=67, Domain=10, Message='unsupported configuration: Emulator '/usr/libexec/qemu-kvm' does not support virt type 'kvm''
```

this one seems to be resolved with some disk io cache changes on the nodes.

The issue regarding to `open /dev/null: operation not permitted` appears to be unrelated.

/assign @qinqon 

Thanks for investigating the /dev/null issue.

**Comment by rmohr** [comment]
/close

cannot allocate memory is gone. If it re-appears on higher load we just have to reserve more memory for spontanous allocation.
