### ISSUE TITLE
[flaky ci] [test_id:3906] Configurations New  VirtualMachineInstance with all supported drives should  configure custom Pci address

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#3671]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

Configurations  [rfe_id:898][crit:medium][vendor:cnv-qe@redhat.com][level:component]New  VirtualMachineInstance with all supported drives [test_id:3906]should  configure custom Pci address

/root/go/src/kubevirt.io/kubevirt/tests/vmi_configuration_test.go:1753 Unexpected error:     <expect.TimeoutError>: 60000000000     expect: timer expired after 60 seconds occurred /root/go/src/kubevirt.io/kubevirt/tests/vmi_configuration_test.go:1759

Failing job- https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3502/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1275865685297205248

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by oshoval** [comment]
#3543 should fix it, saw the error setting of DNS there

**Comment by oshoval** [comment]
please close, #3543 was merged
