### ISSUE TITLE
[flaky ci][test_id:1528]VirtualMachine  A valid VirtualMachine given should survive guest shutdown, multiple times

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#3672]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

[rfe_id:1177][crit:medium][vendor:cnv-qe@redhat.com][level:component]VirtualMachine  A valid VirtualMachine given [test_id:1528]should survive guest  shutdown, multiple times

/root/go/src/kubevirt.io/kubevirt/tests/vm_test.go:679 Unexpected error:     <expect.TimeoutError>: 60000000000     expect: timer expired after 60 seconds occurred /root/go/src/kubevirt.io/kubevirt/tests/vm_test.go:698

Failing job- https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3502/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1275865685297205248

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by oshoval** [comment]
#3543 fixes this
(updating /etc/resolv.conf error is seen)

**Comment by oshoval** [comment]
please close, #3543 was merged
