### ISSUE TITLE
[flaky ci][test_ids:3198]VMIlifecycle Creating a VirtualMachineInstance when virt-handler is responsive device plugins should re-register if the kubelet restarts

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#3673]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

[rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]VMIlifecycle   [rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]Creating  a VirtualMachineInstance when virt-handler is responsive  [test_ids:3198]device plugins should re-register if the kubelet  restarts

/root/go/src/kubevirt.io/kubevirt/tests/vmi_lifecycle_test.go:513 Unexpected Warning event received: testvmivl7zzwz9fv2l2sfx6hs9rl2qt7hzf8cr7xmdlrz78vqcxg9m,3f175e9d-96b1-4cd2-bd86-afef1edb711d: unable to create virt-launcher client connection: dial unix /var/run/kubevirt/domain-notify.sock: connect: no such file or directory Expected     <string>: Warning not to equal     <string>: Warning /root/go/src/kubevirt.io/kubevirt/tests/utils.go:409

Failing job - https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3502/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1275546119522226176

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by oshoval** [comment]
#3598 was merged,
there was a double unlink of this socket, i would suggest to see if it happens again first.

**Comment by ksimon1** [comment]
occured again
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-hyperconverged-cluster-operator-release-4.5-hco-e2e-nightly-bundle-release-4-5-azure4/1295919041008898048

**Comment by oshoval** [comment]
> occured again
> https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-hyperconverged-cluster-operator-release-4.5-hco-e2e-nightly-bundle-release-4-5-azure4/1295919041008898048

```
/root/go/src/kubevirt.io/kubevirt/tests/vmi_lifecycle_test.go:513
Timed out after 360.000s.
Timed out waiting for VMI testvmixx4n7lhqmr9jxtpb6ww5slt6ldczllvl5cbzmjdbn9sj487r to enter [Running] phase(s)
Expected
    <v1.VirtualMachineInstancePhase>: Scheduling
to be an element of
    <[]interface {} | len:1, cap:1>: [["Running"]]
/root/go/src/kubevirt.io/kubevirt/tests/utils.go:2623
```
i would suggest to open a new issue, its not the original issue that is described in the topic, just tne same test number.

**Comment by ksimon1** [comment]
I created a new issue https://github.com/kubevirt/kubevirt/issues/4018
