### ISSUE TITLE
[flaky ci] [test_id:3169] CloudInitHookSidecars VMI definition with CloudInit hook sidecar should have cloud-init user-data from sideca

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#3674]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

CloudInitHookSidecars VMI definition with CloudInit hook sidecar [test_id:3169]should have cloud-init user-data from sideca

/root/go/src/kubevirt.io/kubevirt/tests/vmi_cloudinit_hook_sidecar_test.go:119 Unexpected error:     <expect.TimeoutError>: 15000000000     expect: timer expired after 15 seconds occurred /root/go/src/kubevirt.io/kubevirt/tests/vmi_cloudinit_hook_sidecar_test.go:73

Failing job - https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3502/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1275546119522226176

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by oshoval** [comment]
i would wait first for #3543 to be merged, as expecter that is used here (cirros), could leak characters which will influence the following expecters,
i see in the log the leakage, and saw it before
