### ISSUE TITLE
[flaky ci][test_id:1379]DataVolume  tests Verify DataVolume should succeed creating import dv with  given valid qcow2 url (https) should require scratchspace

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#3675]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

[vendor:cnv-qe@redhat.com][level:component]DataVolume  tests Verify DataVolume should  [rfe_id:1115][crit:high][test_id:1379]succeed creating import dv with  given valid qcow2 url (https) should require scratchspace

/go/src/kubevirt.io/containerized-data-importer/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43 Timed out after 270.000s. Expected     <bool>: false to be true /go/src/kubevirt.io/containerized-data-importer/tests/datavolume_test.go:161

Failing job- https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1256/pull-containerized-data-importer-e2e-os-3.11.0-crio/1275755539334172672

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by maya-r** [comment]
I think cdi's repository is a better place for this issue (the test is in CDI)

**Comment by dhiller** [comment]
Duplicate
