### ISSUE TITLE
[flaky ci][test_id:1368]Upload tests should succeed given a valid token

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#3676]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

[rfe_id:138][crit:high][vendor:cnv-qe@redhat.com][level:component]Upload tests should [test_id:1368]succeed given a valid token

/go/src/kubevirt.io/containerized-data-importer/vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43 Unexpected error:     <*errors.errorString \| 0xc001a6c000>: {         s: "Unexpected return value 502 expected 200, Response: {}",     }     Unexpected return value 502 expected 200, Response: {} occurred /go/src/kubevirt.io/containerized-data-importer/tests/upload_test.go:94

Failing job- https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1252/pull-containerized-data-importer-e2e-k8s-1.17-ceph/1275795973028712449

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dhiller** [comment]
Duplicate
