### ISSUE TITLE
[flaky ci]Block PV Cloner Test Should clone data across namespaces

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#3677]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

Block PV Cloner Test Should clone data across namespaces

/go/src/kubevirt.io/containerized-data-importer/tests/cloner_test.go:560 Unexpected error:     <*errors.errorString \| 0xc000390a00>: {         s: "DataVolume target-dv not in phase Succeeded within 4m30s",     }     DataVolume target-dv not in phase Succeeded within 4m30s occurred /go/src/kubevirt.io/containerized-data-importer/tests/cloner_test.go:586

Failing job - https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1252/pull-containerized-data-importer-e2e-k8s-1.17-ceph/1275795973028712449

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dhiller** [comment]
Duplicate
