### ISSUE TITLE
[flaky ci][test_id:1355]Cloner Test Suite Should clone data across different namespaces

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#3678]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

[rfe_id:1277][crit:high][vendor:cnv-qe@redhat.com][level:component]Cloner  Test Suite [test_id:1355]Should clone data across different namespaces

/go/src/kubevirt.io/containerized-data-importer/tests/cloner_test.go:110 Unexpected error:     <*errors.errorString \| 0xc0002d7340>: {         s: "timed out waiting for the condition",     }     timed out waiting for the condition occurred /go/src/kubevirt.io/containerized-data-importer/tests/cloner_test.go:992

Failing job -https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1252/pull-containerized-data-importer-e2e-k8s-1.17-ceph/1275841397643022336

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by qinqon** [comment]
Another failing jobs: https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1261/pull-containerized-data-importer-e2e-k8s-1.17-ceph/1276320429924945920/build-log.txt

**Comment by dhiller** [comment]
Duplicate
