### ISSUE TITLE
[flaky CI][test_id:1657] VMIlifecycle Killed VirtualMachineInstance should be left alone by virt-handler

### ISSUE THREAD

**Issue by qinqon** [kubevirt/kubevirt#3687]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-officer
> /kind enhancement

**What happened**:
Following test is failing at two different PRs unrelated to the test
```
[rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]VMIlifecycle [rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]Killed VirtualMachineInstance [test_id:1657]should be left alone by virt-handler 
```

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3635/pull-kubevirt-e2e-k8s-1.18/1276418826476457984
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3571/pull-kubevirt-e2e-k8s-1.17/1275897265755525120

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by orenc1** [comment]
observed today as well:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3708/pull-kubevirt-e2e-k8s-cnao-1.17/1278479781469360128

**Comment by danielBelenky** [comment]
/assign

I'll try tackle this one.
