### ISSUE TITLE
[flaky CI][rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system] VM Live Migration Starting a VirtualMachineInstance with a Cirros disk [test_id:1783]should be successfully migrated multiple times with cloud-init disk

### ISSUE THREAD

**Issue by maya-r** [kubevirt/kubevirt#3696]
/kind bug

via [flakefinder](https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/index.html)

The following test is failing (notably, on the k8s-1.18 lane, which is more stable):

````
• Failure [42.313 seconds]
[rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system] VM Live Migration
/root/go/src/kubevirt.io/kubevirt/tests/migration_test.go:63
  Starting a VirtualMachineInstance 
  /root/go/src/kubevirt.io/kubevirt/tests/migration_test.go:346
    with a Cirros disk
    /root/go/src/kubevirt.io/kubevirt/tests/migration_test.go:389
      [test_id:1783]should be successfully migrated multiple times with cloud-init disk [It]
      /root/go/src/kubevirt.io/kubevirt/tests/migration_test.go:432

      Expected
          <v1.VirtualMachineInstanceMigrationPhase>: Failed
      not to equal
          <v1.VirtualMachineInstanceMigrationPhase>: Failed

      /root/go/src/kubevirt.io/kubevirt/tests/migration_test.go:242
````

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3635/pull-kubevirt-e2e-k8s-1.18/1276335275940777984

**Comment by maya-r** [comment]
This looks remarkably similar to #3666 but the ID is different. Perhaps they are the same issue.

**Comment by rmohr** [comment]
https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3635/pull-kubevirt-e2e-k8s-1.18/1276335275940777984/artifacts/pods/1_kubevirt-test-default_virt-launcher-testvmic7ttddvm6k7w8hw49v4nddqdzrkzn2x7q88wjs2lhm-compute.log looks interesting. Especially


```
{"component":"virt-launcher","kind":"","level":"error","msg":"failed to get domain job info","name":"testvmic7ttddvm6k7w8hw49v4nddqdzrkzn2x7q88wjpjs7pp26ff9","namespace":"kubevirt-test-default","pos":"manager.go:636","reason":"virError(Code=55, Domain=20, Message='Requested operation is not valid: domain is not running')","timestamp":"2020-06-26T04:32:48.584999Z","uid":"6af654db-6177-4f88-b426-d66367f87e87"}
```

/assign @vladikr 

would you mind having a look?

**Comment by oshoval** [comment]
Again
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5045/pull-kubevirt-e2e-k8s-1.18/1362429846705147904
Not related to the PR
verified that before the PR it had 64M (so the PR should just increase it)
```
    resources:
      requests:
        cpu: 100m
        memory: 64M
```

/reopen
