### ISSUE TITLE
[flaky CI][test_id:3123]should start a Virtaul Machine with matching features

### ISSUE THREAD

**Issue by maya-r** [kubevirt/kubevirt#3699]
/kind bug
(Also, the typo in the test name)

Via flakefinder.

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3635/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1276428137726480384

````
/root/go/src/kubevirt.io/kubevirt/tests/vmi_configuration_test.go:1499
Unexpected error:
    <expect.TimeoutError>: 60000000000
    expect: timer expired after 60 seconds
occurred
/root/go/src/kubevirt.io/kubevirt/tests/vmi_configuration_test.go:1515
````

**Comment by oshoval** [comment]
#3543 would fix

**Comment by maya-r** [comment]
OK, I'll close it to minimize the noise and ensure the non-duplicate issues get adequate attention.

**Comment by rmohr** [comment]
/reopen

Let's not close issues where the fix is not merged yet.

**Comment by rmohr** [comment]
/close

Ah ok we have an issue for that : #3619
