### ISSUE TITLE
Support cluster level/VM API defaulting

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#370]
There are a number of defaulting features which we'll in KubeVirt.

Goals

- [ ] Stable virtual hardware ABI / frontend  - For persistent VMs
- [ ] Optimized virtual hardware ABI / frontend - Support an easy VM launch process ("just specify the OS")
- [ ] Predictive device enumeration and identifiability - For hot-(un)plugging

Potential pieces to achieve this functionality

- [ ] Frontend validation (based on libosinfo)
- [ ] Mechanism to provide the optimal hardware configuration based on given informations
- [ ] Mechanism to apply and persist VM API modifications

**Comment by mykaul** [comment]
I assume the 2nd item is via libosinfo or something better?

**Comment by fabiand** [comment]
Yes, libosinfo is one piece to gain informations, but there are still gaps. In the context of libosinfo, we know two gaps:

1. libosinfo misses some details which i.e. oVirt has (and needs) (but I need to understand in detail which informations are missing)
2. libosinfo provides a set of compatible hardware configurations, but it does not decide which one to use (this is the bigger gap)

**Comment by fabiand** [comment]
This was actually discussed in a VM vs VMConfig meeting. The conclusion on this topic was, that the defaulting can be done by an admission controller on the cluster level.

There are a number of things to keep in mind, an incomplete list:
- Certain defaults introduce certain requirements on the host, which can be addressed with scheduling requirements (i.e. vhost-scsi add's kernel requirements).
- The defaulting rules could actually be a configurable entity itself
