### ISSUE TITLE
[flaky CI][test_id:1633]should indicate that a node is ready for vmis

### ISSUE THREAD

**Issue by maya-r** [kubevirt/kubevirt#3700]
/kind bug

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3635/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1276428137726480384

````
/root/go/src/kubevirt.io/kubevirt/tests/vmi_lifecycle_test.go:485
Timed out after 120.000s.
Nodes should be schedulable
Expected
    <string>: false
to equal
    <string>: true
/root/go/src/kubevirt.io/kubevirt/tests/vmi_lifecycle_test.go:504
````

**Comment by dhiller** [comment]
Happened again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4471/pull-kubevirt-e2e-k8s-1.19/1323231497523564544

**Comment by maya-r** [comment]
Happened again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4611/pull-kubevirt-e2e-k8s-1.17/1335979484142112769
