### ISSUE TITLE
[Flaky CI] In "Running" instead of "Succeeded": With HostDisk and PVC initialization With a HostDisk defined With 'DiskExistsOrCreate' type Should create a disk image and start [test_id:851]with virtio driver expand_more

### ISSUE THREAD

**Issue by maya-r** [kubevirt/kubevirt#3702]
/kind bug

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3598/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1276634749405761536

````
/root/go/src/kubevirt.io/kubevirt/tests/storage_test.go:398
Timed out after 30.000s.
Expected
    <v1.PodPhase>: Running
to equal
    <v1.PodPhase>: Succeeded
/root/go/src/kubevirt.io/kubevirt/tests/utils.go:3579
````

It's possible it's just a low timeout/slower CI.

**Comment by awels** [comment]
Another instance here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3961/pull-kubevirt-e2e-k8s-1.18/1293065443031912448

**Comment by qinqon** [comment]
Another here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4287/pull-kubevirt-e2e-k8s-1.18/1313621572384198656
