### ISSUE TITLE
[flaky CI]Pausing A long running process [test_id:3090]should be continued after the VMI is unpaused 

### ISSUE THREAD

**Issue by maya-r** [kubevirt/kubevirt#3704]
/kind bug
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3598/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1276726855847645184

````
/root/go/src/kubevirt.io/kubevirt/tests/pausing_test.go:390
Unexpected error:
    <expect.TimeoutError>: 15000000000
    expect: timer expired after 15 seconds
occurred
/root/go/src/kubevirt.io/kubevirt/tests/pausing_test.go:386
````

**Comment by orenc1** [comment]
Another recurrence today:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4082/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1304175203437252608

**Comment by tomob** [comment]
Another one: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4035/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1306409927496962048

**Comment by akrejcir** [comment]
Another: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4216/pull-kubevirt-e2e-k8s-1.17/1307931454021308416
