### ISSUE TITLE
[release-30] [flaky ci] Configurations [rfe_id:904][crit:medium][vendor:cnv-qe@redhat.com][level:component]with driver cache settings and PVC [test_id:1681]should set appropriate cache modes 

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#3707]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug

> /kind enhancement

**What happened**:

The following test failed on the release-0.30 branch:
```
Configurations [rfe_id:904][crit:medium][vendor:cnv-qe@redhat.com][level:component]with driver cache settings and PVC [test_id:1681]should set appropriate cache modes 
```
with
```
Configurations
/root/go/src/kubevirt.io/kubevirt/tests/vmi_configuration_test.go:53
  [rfe_id:904][crit:medium][vendor:cnv-qe@redhat.com][level:component]with driver cache settings and PVC
  /root/go/src/kubevirt.io/kubevirt/tests/vmi_configuration_test.go:1618
    [test_id:1681]should set appropriate cache modes [It]
    /root/go/src/kubevirt.io/kubevirt/tests/vmi_configuration_test.go:1624

    Expected
        <string>: none
    to equal
        <string>: writethrough

    /root/go/src/kubevirt.io/kubevirt/tests/vmi_configuration_test.go:1686
```
Logs: 

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3695/pull-kubevirt-e2e-k8s-1.15-ceph/1277263518088826880
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3695/pull-kubevirt-e2e-k8s-1.16/1277263518088826881
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ormergi** [comment]
On PR #3695 this test failed on two lanes, I noticed that the failed lanes ran on the same node
but different from the node that the passed lanes ran on:
**failed lanes** 1.16 and 1.15 ceph ran on:
`ibm-srv03.ovirt.org / 184.173.57.212` 
passed lanes 1.16-ipv6 and 1.17-cnao ran on:
`ibm-srv06.ovirt.org / 184.173.57.210`
and windos2016 lane ran on:
`ibm-srv05.ovirt.org / 184.173.57.214`

**Comment by jean-edouard** [comment]
New occurrence: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4062/pull-kubevirt-e2e-k8s-1.17/1298838791783452672
