### ISSUE TITLE
[flaky ci] [rfe_id:151][crit:high][vendor:cnv-qe@redhat.com][level:component]CloudInit UserData [rfe_id:151][crit:medium][vendor:cnv-qe@redhat.com][level:component]A new VirtualMachineInstance with cloudInitConfigDrive networkData [test_id:3185]should have cloud-init network-config with NetworkDataBase64 source

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#3711]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

> /kind enhancement

**What happened**:

```
/root/go/src/kubevirt.io/kubevirt/tests/vmi_cloudinit_test.go:469
Unexpected error:
    <expect.TimeoutError>: 15000000000
    expect: timer expired after 15 seconds
occurred
/root/go/src/kubevirt.io/kubevirt/tests/vmi_cloudinit_test.go:93
```

Logs:

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3646/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1277208781377245184

From the expect output it looks to me like most likely the expect expression is a little bit weak. The test is in general very stable, but someone should look into it.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by oshoval** [comment]
i believe #3543 would fix it, but we need to make sure, once its merged
i see leakage of characters from previous SND batch there, that ruin the EXP
