### ISSUE TITLE
Failing periodic job: periodic-ci-kubevirt-hyperconverged-cluster-operator-release-4.5-hco-e2e-nightly-bundle-release-4-5-azure4

### ISSUE THREAD

**Issue by tiraboschi** [kubevirt/kubevirt#3717]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement
/triage build-officer

**What happened**:
Failing periodic job: periodic-ci-kubevirt-hyperconverged-cluster-operator-release-4.5-hco-e2e-nightly-bundle-release-4-5-azure4

https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/?type=periodic&job=periodic-ci-kubevirt-hyperconverged-cluster-operator-release-4.5-hco-e2e-nightly-bundle-release-4-5-azure4

logs: https://storage.googleapis.com/origin-ci-test/logs/periodic-ci-kubevirt-hyperconverged-cluster-operator-release-4.5-hco-e2e-nightly-bundle-release-4-5-azure4/1276350122363457536/build-log.txt

Failing test:

```
[91m[1m[Fail] [0m[90m[rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]VMIlifecycle [0m[0m[rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]Creating a VirtualMachineInstance [0m[90mwhen virt-launcher crashes [0m[91m[1m[It] [test_id:1631]should be stopped and have Failed phase [0m
[37m/go/src/kubevirt.io/kubevirt/tests/utils.go:418[0m

```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

We detected it on HCO periodic job more than once but it's definitively a kubevirt issue.
I'm moving it from: https://github.com/kubevirt/hyperconverged-cluster-operator/issues/661

**Environment**:
- HCO version (use `oc get csv -n kubevirt-hyperconverged`):
- Kubernetes version (use `kubectl version`):
- Cloud provider or hardware configuration:
- Install tools:
- Others:

**Comment by maya-r** [comment]
It's now failing to come up, [example](https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gcs/origin-ci-test/logs/periodic-ci-kubevirt-hyperconverged-cluster-operator-release-4.5-hco-e2e-nightly-bundle-release-4-5-azure4/1279611602332553216)

````
+ echo 'Waiting for HCO to get fully deployed'
+ oc wait -n openshift-cnv hyperconverged kubevirt-hyperconverged --for condition=Available --timeout=15m
Waiting for HCO to get fully deployed
error: timed out waiting for the condition on hyperconvergeds/kubevirt-hyperconverged
````

**Comment by brybacki** [comment]
no it is [deck-build-log](https://deck-ci.apps.ci.l2s4.p1.openshiftapps.com/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-hyperconverged-cluster-operator-release-4.5-hco-e2e-nightly-bundle-release-4-5-azure4/1280336402050977792)
```
evel=error msg="Error: Error Creating/Updating Subnet \"ci-op-pts1nr93-2e55b-b5fr9-worker-subnet\" (Virtual Network \"ci-op-pts1nr93-2e55b-b5fr9-vnet\" / Resource Group \"ci-op-pts1nr93-2e55b-b5fr9-rg\"): network.SubnetsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code=\"AnotherOperationInProgress\" Message=\"Another operation on this or dependent resource is in progress. To retrieve status of the operation use uri: https://management.azure.com/subscriptions/d38f1e38-4bed-438e-b227-833f997adf6a/providers/Microsoft.Network/locations/centralus/operations/831580d6-2557-4650-9a57-3b058673eb2b?api-version=2019-09-01.\" Details=[]"
level=error
level=error msg="  on ../tmp/openshift-install-632375916/vnet/vnet.tf line 22, in resource \"azurerm_subnet\" \"worker_subnet\":"
level=error msg="  22: resource \"azurerm_subnet\" \"worker_subnet\" {"
level=error
level=error
level=fatal msg="failed to fetch Cluster: failed to generate asset \"Cluster\": failed to create cluster: failed to apply Terraform: error(AzureMultiOperationFailure) from Infrastructure Provider: Creating Subnets failed because Azure could not process multiple operations."
```

**Comment by maya-r** [comment]
Currently hitting a [timeout](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-hyperconverged-cluster-operator-release-4.5-hco-e2e-nightly-bundle-release-4-5-azure4/1292295170280132608):
````
2020/08/09 03:21:55 Running pod hco-e2e-nightly-bundle-release-4-5-azure4
{"component":"entrypoint","file":"prow/entrypoint/run.go:165","func":"k8s.io/test-infra/prow/entrypoint.Options.ExecuteProcess","level":"error","msg":"Process did not finish before 4h0m0s timeout","severity":"error","time":"2020-08-09T07:04:07Z"}
time="2020-08-09T07:04:07Z" level=info msg="Received signal." signal=interrupt
2020/08/09 07:04:08 error: Process interrupted with signal interrupt, cancelling execution...
2020/08/09 07:04:08 cleanup: Deleting template hco-e2e-nightly-bundle-release-4-5-azure4
2020/08/09 07:04:08 error: Could not delete template instance: context canceled
2020/08/09 07:04:08 cleanup: Deleting release pod release-latest
time="2020-08-09T07:04:08Z" level=error msg="failed to remove file" error="could not run remote command: pod hco-e2e-nightly-bundle-release-4-5-azure4 does not have a host assigned"
{"component":"entrypoint","file":"prow/entrypoint/run.go:250","func":"k8s.io/test-infra/prow/entrypoint.gracefullyTerminate","level":"error","msg":"Process did not exit before 30m0s grace period","severity":"error","time":"2020-08-09T07:34:07Z"}
````
