### ISSUE TITLE
[rfe_id:253][crit:medium][vendor:cnv-qe@redhat.com][level:component]Expose Expose UDP service on a VMI Expose ClusterIP UDP service [test_id:1535][label:masquerade_binding_connectivity]Should expose a ClusterIP service on a VMI and connect to it

### ISSUE THREAD

**Issue by nunnatsa** [kubevirt/kubevirt#3721]
/kind bug

/triage build-officer

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3628/pull-kubevirt-e2e-k8s-1.16/1277535559622856705

```
[rfe_id:253][crit:medium][vendor:cnv-qe@redhat.com][level:component]Expose
/root/go/src/kubevirt.io/kubevirt/tests/expose_test.go:47
  Expose UDP service on a VMI
  /root/go/src/kubevirt.io/kubevirt/tests/expose_test.go:180
    Expose ClusterIP UDP service
```

**Comment by oshoval** [comment]
@phoracek 
i can take it if need as soon as i have time, thanks

**Comment by dhiller** [comment]
Failed again here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4011/pull-kubevirt-e2e-k8s-1.16/1298418719243898880
