### ISSUE TITLE
[test_id:1754]should create a virtual machine with sriov interface  - SRIOV VirtualMachineInstance with sriov plugin interface

### ISSUE THREAD

**Issue by orenc1** [kubevirt/kubevirt#3742]
/kind bug
/triage build-officer

**What happened**:
[test_id:1754]should create a virtual machine with sriov interface 

**What you expected to happen**:
```
 SRIOV
/root/go/src/kubevirt.io/kubevirt/tests/vmi_multus_test.go:568
  VirtualMachineInstance with sriov plugin interface
  /root/go/src/kubevirt.io/kubevirt/tests/vmi_multus_test.go:623
    [test_id:1754]should create a virtual machine with sriov interface [It]
    /root/go/src/kubevirt.io/kubevirt/tests/vmi_multus_test.go:695
    Unexpected error:
        <*errors.StatusError | 0xc0023dedc0>: {
            ErrStatus: {
                TypeMeta: {Kind: "", APIVersion: ""},
                ListMeta: {
                    SelfLink: "",
                    ResourceVersion: "",
                    Continue: "",
                    RemainingItemCount: nil,
                },
                Status: "Failure",
                Message: "Internal error occurred: failed calling webhook \"virtualmachineinstances-create-validator.kubevirt.io\": Post https://virt-api.kubevirt.svc:443/virtualmachineinstances-validate-create?timeout=30s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)",
                Reason: "InternalError",
                Details: {
                    Name: "",
                    Group: "",
                    Kind: "",
                    UID: "",
                    Causes: [
                        {
                            Type: "",
                            Message: "failed calling webhook \"virtualmachineinstances-create-validator.kubevirt.io\": Post https://virt-api.kubevirt.svc:443/virtualmachineinstances-validate-create?timeout=30s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)",
                            Field: "",
                        },
                    ],
                    RetryAfterSeconds: 0,
                },
                Code: 500,
            },
        }
        Internal error occurred: failed calling webhook "virtualmachineinstances-create-validator.kubevirt.io": Post https://virt-api.kubevirt.svc:443/virtualmachineinstances-validate-create?timeout=30s: context deadline exceeded (Client.Timeout exceeded while awaiting headers)
    occurred 
```
[Prow job log](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3528/pull-kubevirt-e2e-kind-1.17-sriov/1278364397202313217)
**Lane**:
pull-kubevirt-e2e-kind-1.17-sriov

**Comment by oshoval** [comment]
@phoracek 
@ormergi 
https://github.com/kubevirt/kubevirt/issues/3485#issuecomment-636304852

Maybe this comment is interesting ?

**Comment by brybacki** [comment]
again:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2935/pull-kubevirt-e2e-kind-1.17-sriov/1280469208785752065

**Comment by oshoval** [comment]
> /remove-lifecycle rotten

can you please paste the error ? 
is it the webhook (as the issue first thread says) or the etcd timeout ?

**Comment by dhiller** [comment]
the latter

**Comment by oshoval** [comment]
> the latter

There isnt one, but indeed it would be best please to open one, do you want me or you to open it ?
since the webhook that appear in the issue main message is outdated

**Comment by dhiller** [comment]
I think this one is it: https://github.com/kubevirt/kubevirt/issues/3777

**Comment by oshoval** [comment]
> I think this one is it: #3777

This one according most of the links there is during cluster-up, Or is on it 
but please see error like we have here which deserve imo a new issue
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4511/pull-kubevirt-e2e-kind-1.17-sriov/1325727568359329793

**Comment by ormergi** [comment]
@orenc1 @dhiller 
We didnt saw this error for a while now, and there have been huge effort for stabilizing this lane
now all the changes we did are in place.
I think we can close this one.

**Comment by dhiller** [comment]
Agreed, we can reopen it if it occurs again.
