### ISSUE TITLE
Update built qemu/libvirt in Fedora repo to include NVME device 

### ISSUE THREAD

**Issue by daghaian** [kubevirt/kubevirt#3743]
/kind enhancement

**What happened**:
Currently, our workload requires the use of NVME virtualized drives, a feature not currently offered by kubevirt. In the interim, a sidecar based approach is being leveraged in order to attach NVME disks however it would appear that the current qemu-kvm that exists within the virt-launcher container does not have device support for NVME. The version of qemu-kvm is not the issue as I can confirm earlier versions do contain NVME device support but since I am aware that a custom repo is being used for fetching packages inside the container (https://copr.fedorainfracloud.org/coprs/g/virtmaint-sig/for-kubevirt/) I believe that these built versions may not have the nvme device support.

**What you expected to happen**:
I would expect that the qemu-kvm binary that exists within the virt-launcher container to contain device support for NVME

**How to reproduce it (as minimally and precisely as possible)**:
From within the compute container of a running VM deployed via kubevirt, simply run 
`/usr/libexec/qemu-kvm -device help | grep -i nvme` and you will notice no output returned. On another container with version 4.2.0 of qemu-kvm (same as virt-launcher container), you get the appropriate output:

$ qemu-kvm -device help |grep -i nvme
name "nvme", bus PCI, desc "Non-Volatile Memory Express"

$ qemu-kvm -version
QEMU emulator version 4.2.0 (qemu-4.2.0-7.fc32)
Copyright (c) 2003-2019 Fabrice Bellard and the QEMU Project developers

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.30.0
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by daghaian** [comment]
Further investigation (correct me if I'm wrong) reveals that the qemu-kvm inside the actual virt-launcher image appears to just be qemu-system-* binary which must have been compiled with the -enable-kvm and other flags already present at compilation time. It seems odd to me but perhaps I"m not understand a piece of the puzzle. That being said, I'm also confused that if that is indeed how its being handled, how this version of QEMU managed to omit NVME device support as normal qemu-system-x86_64 at the same version includes NVME device support.

**Comment by MarkSpencerTan** [comment]
@daghaian I also need some of our VMs to be able to specify the drive types as NVME drives! If this can be enabled that would be great! @rmohr , would you happen to know what is responsible for building those qemu binaries for kubevirt so we can take a look at what we can do for modifications?

Thanks,
Mark

**Comment by rmohr** [comment]
Do we talk about nvme passthrough or exposing the disk as nvme (emulation for apps inside the vm)?

@vladikr FYI

**Comment by daghaian** [comment]
@rmohr Currently we were exploring the idea of just using QemuCMD line args to attach NVME disks but what I can't understand is how come the qemu-kvm binary thats inside a virt-launcher container does not have NVMe support? Any other installations of qemu/qemu-kvm include NVME support (same version). I noticed Kubevirt is using its own fedora COPR repo?

**Comment by MarkSpencerTan** [comment]
@rmohr, we were thinking more in the lines of exposing the disk as nvme so that the custom kernels in the VMs we're trying to spin up would come up properly. They're expecting NVME drives on boot

**Comment by rmohr** [comment]
I can understand the confusion. We right now we have a special build based on the rhel-av-8.2 branch of the libvirt project. The background is that these versions are tested very well and that we have a special copr for them, so that the rpms we tested against do not just disappear and get replaced with other unknown versions whe we rebuild our container with libvirt/qemu, however they don't contain all features which normal libvirt builds contain.

We are going to move away from this, since the libvirt project recently started to maintain automatically built coprs per release which will improve the situation for us. They should provide enough stability to avoid surprises.

To directly unblock you, you can build your own container the way like described here: https://github.com/kubevirt/libvirt/tree/av-8.2. Then you can replace the libvirt image in the WORKSPACE file and just follow https://github.com/kubevirt/kubevirt/blob/master/docs/getting-started.md#i-just-want-it-built-and-run-it-on-my-cluster.

**Comment by MarkSpencerTan** [comment]
@rmohr, thank you for the response by the way. With that we were able to run an updated qemu on our kubevirt version that supports NVME. 

After that we tried creating a sidecar that would add the extra qemu args to re-add the drives that we wanted to have NVME like below:

```xml
<qemu:commandline>
  <qemu:arg value='-drive'/>
  <qemu:arg value='file=/path/to/nvme1.img,format=raw,if=none,id=NVME1'/>
  <qemu:arg value='-device'/>
  <qemu:arg value='nvme,drive=NVME1,serial=nvme-1'/>
</qemu:commandline>
```

We ended up having to remove the drives/devices that we added in there from the domain spec, however I believe that implementation had caused issues when using DataVolumes for these disks. With containerDisk it was ok, but with persistent storage and DataVolumes I kept getting permission errors:

```
/usr/bin/qemu-system-x86_64 \
-name guest=vr5850mt-persistence_vr5850mt-persistence-nextcs4-unit0,debug-threads=on \
-S \
-object secret,id=masterKey0,format=raw,file=/var/lib/libvirt/qemu/domain-238-vr5850mt-persistence/master-key.aes \
-machine pc-q35-4.1,accel=kvm,usb=off,dump-guest-core=off \
-cpu Cascadelake-Server,ss=on,vmx=on,hypervisor=on,tsc-adjust=on,umip=on,pku=on,md-clear=on,stibp=on,arch-capabilities=on,xsaves=on,ibpb=on,amd-ssbd=on,rdctl-no=on,ibrs-all=on,skip-l1dfl-vmentry=on,mds-no=on \
-m 954 \
-overcommit mem-lock=off \
-smp 2,sockets=2,dies=1,cores=1,threads=1 \
-object iothread,id=iothread1 \
-uuid a7e6d42c-1ccd-525c-870e-908072926c5f \
-smbios type=1,manufacturer=KubeVirt,product=None,uuid=a7e6d42c-1ccd-525c-870e-908072926c5f,family=KubeVirt \
-no-user-config \
-nodefaults \
-chardev socket,id=charmonitor,fd=21,server,nowait \
-mon chardev=charmonitor,id=monitor,mode=control \
-rtc base=utc \
-no-shutdown \
-boot strict=on \
-device pcie-root-port,port=0x10,chassis=1,id=pci.1,bus=pcie.0,multifunction=on,addr=0x2 \
-device pcie-root-port,port=0x11,chassis=2,id=pci.2,bus=pcie.0,addr=0x2.0x1 \
-device pcie-root-port,port=0x12,chassis=3,id=pci.3,bus=pcie.0,addr=0x2.0x2 \
-device pcie-root-port,port=0x13,chassis=4,id=pci.4,bus=pcie.0,addr=0x2.0x3 \
-device pcie-root-port,port=0x14,chassis=5,id=pci.5,bus=pcie.0,addr=0x2.0x4 \
-device virtio-serial-pci,id=virtio-serial0,bus=pci.3,addr=0x0 \
-drive file=/var/run/kubevirt-private/vmi-disks/next-cs4-disk-1/disk.img,format=raw,if=none,id=drive-ua-next-cs4-disk-1 \
-device ide-hd,bus=ide.0,drive=drive-ua-next-cs4-disk-1,id=ua-next-cs4-disk-1 \
-drive file=/var/run/kubevirt-ephemeral-disks/disk-data/next-cs4-bootloader-disk/disk.qcow2,format=qcow2,if=none,id=drive-ua-next-cs4-bootloader-disk \
-device virtio-blk-pci,scsi=off,bus=pci.4,addr=0x0,drive=drive-ua-next-cs4-bootloader-disk,id=ua-next-cs4-bootloader-disk,bootindex=1 \
-netdev tap,fd=23,id=hostua-ife-network1,vhost=on,vhostfd=24 \
-device virtio-net-pci,netdev=hostua-ife-network1,id=ua-ife-network1,mac=52:54:00:9a:42:fe,bus=pci.1,addr=0x0 \
-netdev tap,fd=25,id=hostua-ife-network2,vhost=on,vhostfd=26 \
-device virtio-net-pci,netdev=hostua-ife-network2,id=ua-ife-network2,mac=52:54:00:f3:b9:71,bus=pci.2,addr=0x0 \
-chardev socket,id=charserial0,fd=27,server,nowait \
-device isa-serial,chardev=charserial0,id=serial0 \
-chardev socket,id=charchannel0,fd=28,server,nowait \
-device virtserialport,bus=virtio-serial0.0,nr=1,chardev=charchannel0,id=channel0,name=org.qemu.guest_agent.0 \
-vnc vnc=unix:/var/run/kubevirt-private/738e1312-2948-4fab-b2cb-f6ea6aec9af2/virt-vnc \
-device VGA,id=video0,vgamem_mb=16,bus=pcie.0,addr=0x1 \
-drive file=/var/run/kubevirt-private/vmi-disks/next-cs4-disk-2/disk.img,if=none,id=NVME2 \
-device nvme,drive=NVME2,serial=nvme-2 \
-drive file=/var/run/kubevirt-private/vmi-disks/next-cs4-disk-3/disk.img,if=none,id=NVME3 \
-device nvme,drive=NVME3,serial=nvme-3 \
-sandbox on,obsolete=deny,elevateprivileges=deny,spawn=deny,resourcecontrol=deny \
-msg timestamp=on
2020-12-17 07:30:47.870+0000: Domain id=238 is tainted: custom-argv
2020-12-17T07:30:47.905049Z qemu-system-x86_64: -drive file=/var/run/kubevirt-private/vmi-disks/next-cs4-disk-2/disk.img,if=none,id=NVME2: Could not open '/var/run/kubevirt-private/vmi-disks/next-cs4-disk-2/disk.img': Permission denied
2020-12-17 07:30:48.043+0000: shutting down, reason=failed
```

**Comment by MarkSpencerTan** [comment]
@rmohr is there any chance on supporting nvme as a device option in the newer libvirt images? We've maintained a custom libvirt image from above but I'm not sure how long we can maintain that as newer versions of kubevirt gets released. 

We've noticed that the WORKSPACE file doesn't have the libvirt image there anymore on v0.42.0, is there a new place we can override the libvirt image?

**Comment by BugMosquito** [comment]
You can solve this problem by recompiling QEMU，centos-stream qemu patch don't open the nvme-pci config

**Comment by victortoso** [comment]
nvme device is indeed not present

```
bash-5.1$ /usr/libexec/qemu-kvm -version
QEMU emulator version 8.0.0 (qemu-kvm-8.0.0-13.el9)
Copyright (c) 2003-2022 Fabrice Bellard and the QEMU Project developers

bash-5.1$ /usr/libexec/qemu-kvm -device help | grep -i nvme
```

but virtio-blk is
```
bash-5.1$ /usr/libexec/qemu-kvm -device help | grep -i blk
name "vhost-user-blk", bus virtio-bus
name "vhost-user-blk-pci", bus PCI
name "vhost-user-blk-pci-non-transitional", bus PCI
name "vhost-user-blk-pci-transitional", bus PCI
name "virtio-blk-device", bus virtio-bus
name "virtio-blk-pci", bus PCI, alias "virtio-blk"
name "virtio-blk-pci-non-transitional", bus PCI
name "virtio-blk-pci-transitional", bus PCI
```

Perhaps you can achieve what you want with `virtio-blk` ? The example I saw was moving

```
   -drive file=nvme://0000:06:00.0/1,if=none,id=drive0,format=raw \
   -device nvme,id=image2,drive=drive0 \
```

to this

```
   -drive file=nvme://0000:06:00.0/1,if=none,id=drive0,format=raw \
   -device virtio-blk,drive=drive0 \
```

You should probably test outside kubevirt first.
