### ISSUE TITLE
Add support for custom OVMF

### ISSUE THREAD

**Issue by waveywaves** [kubevirt/kubevirt#3746]
**What happened**:
Not able to use custom OVMF_CODE.fd and OVMF_VARS.fd
In the kubevirt-config configMap we can provide the ovmfPath. But how do we really use it ? 
We would need to mount these on the pod somehow. As a hack I did a https://github.com/waveywaves/kubevirt/commit/1a39f0153f3d4b1e49ed078457b0d8ac0e780d8a to amke this work

**What you expected to happen**:
Be able to mount a volume which contains the OVMF data.

**How to reproduce it (as minimally and precisely as possible)**:
-

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by maya-r** [comment]
Out of curiosity, what was your motivation to use a custom OVMF?

**Comment by rmohr** [comment]
@jean-edouard maybe something you may be able to help with.

**Comment by jean-edouard** [comment]
@waveywaves and I already briefly chatted about this.
`ovmfPath` is indeed intended for use-cases that involve a custom virt-launcher image.
Being able to use a custom OVMF_CODE.fd would allow users to self-sign kernels, which would probably be nice to have for some very specific use-cases, but also a significant security concern.
A custom writeable OVMF_VARS.fd location would allow for the persistence of values like firmware settings.
Like @maya-r, I wonder if the use-case is one of the above or something else, as there could be a simpler and safer solution to it.
For example, most firmware settings could be kept in the VM yaml and injected at boot time.

**Comment by waveywaves** [comment]
@jean-edouard I was using the custom OVMF to run a hackintosh machine when I was testing. I was able to partailly boot it up when I tested this a few months ago, but at the time I was running kubevirt in emulation mode if I am not wrong. I am going to test this without emulation this time to see how well it could work.
