### ISSUE TITLE
[Flaky CI] Failed to start QEMU binary /usr/libexec/qemu-kvm for probing

### ISSUE THREAD

**Issue by maya-r** [kubevirt/kubevirt#3757]
I'm attempting to combine the failures based on the SyncVMI errors, as the kind-IPv6 lane has failures all over the place.

Two failures spotted, [one](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3713/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1279076338828840960), [two](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3517/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1278805176970383360)

In both cases, the output was:
Unexpected Warning event received: testvminhsqq2b977qxzxmdvkcppcfzbq8czxm8pncd5l5pp65tgxvn,b821b0a8-c3c7-4056-aeb6-0f0915db15f1: server error. command SyncVMI failed: "LibvirtError(Code=1, Domain=10, Message='internal error: Failed to start QEMU binary /usr/libexec/qemu-kvm for probing: ')"

/kind bug
/triage build-officer

**Comment by maya-r** [comment]
Seems to be the same as #3748 but I feel like this title is more tempting people to look at the problem

**Comment by jean-edouard** [comment]
New instance spotted, in a different test and on a non-ipv6 lane:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3869/pull-kubevirt-e2e-k8s-1.17/1285947809488441344

**Comment by maiqueb** [comment]
Saw this today, on https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3794/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1286734977844645888

Test case: `IOThreads IOThreads Policies [ref_id:2065] should honor auto ioThreadPolicy [test_id:3096]for four CPUs`
