### ISSUE TITLE
[Flaky CI][kind-ipv6]Unable to open /dev/kvm: Operation not permitted

### ISSUE THREAD

**Issue by maya-r** [kubevirt/kubevirt#3759]
In the following run: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3166/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1278901687255306240

We see a failure from a timeout.

Digging somewhat, the logs from [virt-handler](https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3166/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1278901687255306240/artifacts/pods/1_kubevirt_virt-handler-sd55z-virt-handler.log) say 'Unable to open /dev/kvm: Operation not permitted'

I suspect this message should never appear and its existence suggests the cause, but perhaps I am wrong about this.

/kind bug
/triage build-officer

**Comment by rmohr** [comment]
/close

ipv6 enabled kind is not used anymore.
