### ISSUE TITLE
Find an alternative to parsing the logs in vmi lifecycle tests

### ISSUE THREAD

**Issue by danielBelenky** [kubevirt/kubevirt#3764]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Currently, we are parsing the logs from virt-handler to decide if the communication between
virt-handler and virt-launcher works and check for various domain lifecycle events.
This is risky because parsing logs in unreliable: I can print a line to the log that announces
that I do something but fail to do so in my code and the test will still pass.

**What you expected to happen**:
We should define the overall behaviour that we want to check and assert on it. During e2e
tests we probably shouldn't care about "how" things happened but we want to know that
they happened in general.
I understand that in some cases this can be hard to do during e2e tests and this is what
the actual goal of this ticket: to see if we really need those tests and if we do, try to find
a solution on how to test the behaviour without relying on log parsing.

**Anything else we need to know?**:
Example: https://github.com/kubevirt/kubevirt/blob/master/tests/vmi_lifecycle_test.go#L1084

**Comment by EdDev** [comment]
I would also expect the functional/e2e tests to interact with the API and not with logs. Logs cannot be trusted, they can change (edited, added or removed).

Could we give an example in this issue on what kind of test is expected here?
I could imagine a VMI lifecycle to include the different phases and states it is in, checking that we detect them all in the different paths they can take. Is this the case?

**Comment by victortoso** [comment]
/reopen

It is still an issue.

**Comment by victortoso** [comment]
@xpivarc would `help-wanted` label makes sense here? It isn't a high priority but not necessarily a `good-first-issue`, depending on the work involved... needs discussion.
