### ISSUE TITLE
CDI Image upload timeout

### ISSUE THREAD

**Issue by banksyian** [kubevirt/kubevirt#3776]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
 When creating an upload dataVolume the scratch PVC is not created.

```
apiVersion: cdi.kubevirt.io/v1alpha1
kind: DataVolume
metadata:
  name: upload-datavolume
  labels:
    app: containerized-data-importer
spec:
  source:
      upload: {}
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 10Gi
    storageClassName: fast 
    scratchSpaceStorageClass: fast
```
The cdi-deployment pod shows the following log:
```
"controller-runtime.controller","msg":"Reconciler error","controller":"upload-controller","request":"default/upload-datavolume","error":"admission webhook \"podscheduler.storageos.com\" denied the request: failed to determine if the volume is managed: failed to get PVC: PersistentVolumeClaim \"upload-datavolume-scratch\" not found"
```
There is a default storage class so I believe it should use that to create a scratch volume, however I tried by creating one manually and still get the following error:
```
"controller-runtime.controller","msg":"Reconciler error","controller":"upload-controller","request":"default/upload-datavolume-scratch","error":"cdi-upload-upload-datavolume pod not controlled by pvc upload-datavolume-scratch","errorVerbose":"cdi-upload-upload-datavolume pod not controlled by pvc upload-datavolume-scratch\nkubevirt.io/containerized-data-importer/pkg/controller.
```
The datavolume is stuck in a uploadScheduled state:
```
NAME                                                 PHASE             PROGRESS   RESTARTS   AGE
datavolume.cdi.kubevirt.io/upload-datavolume         UploadScheduled   N/A                   26m
```
The cdi-upload pod is running:
```
NAME                                              READY   STATUS    RESTARTS   AGE
pod/cdi-upload-upload-datavolume                  1/1     Running   0          24m
```
If i try to upload it times out waiting for the pod:
```
Using existing PVC default/upload-datavolume
Waiting for PVC upload-datavolume upload pod to be ready...
timed out waiting for the condition
```
Is there any annotation or anything I should add to the dataVolume/PVC for the cdi-upload to manage it?

**What you expected to happen**:
Create scratch PVC automatically and upload image to PVC

**How to reproduce it (as minimally and precisely as possible)**:

Create upload datavolume as above.
Upload image using virtctl.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
Client Version: version.Info{GitVersion:"v0.29.0", GitCommit:"cbb7eaddb34d38da15868b19d84647f668a6134b", GitTreeState:"clean", BuildDate:"2020-05-05T03:33:18Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"{gitVersion}", GitCommit:"{gitCommit}", GitTreeState:"{gitTreeState}", BuildDate:"{buildDate}", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:16:24Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.6", GitCommit:"d32e40e20d167e103faf894261614c5b45c44198", GitTreeState:"clean", BuildDate:"2020-05-20T13:08:34Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
ubuntu 18.04.4
- Kernel (e.g. `uname -a`):
4.15.0-101-generic
- Install tools:
- Others:

**Comment by awels** [comment]
You can look up what CDI will use for the scratch space storage class by running
```
kubectl get CDIConfig config -o yaml
```
There should be a value in the status field. scratchSpaceStorageClass is not a valid field in a DataVolume.

**Comment by mazzystr** [comment]
Try...
`kubectl patch -n cdi cdiconfig.cdi.kubevirt.io/config --type "json" --patch '[{"op":"replace","path":"scratchSpaceStorageClass","value":"fast" }]'`

**Comment by awels** [comment]
If fast is the default storage class, then that will not be necessary, the way CDI determines the scratch space storage class is the following:
1. Use scratchSpaceStorageClass defined in the CDIConfig object spec.
2. If 1 doesn't exist, use the default storage class in the cluster.
3. If 2 doesn't exist (and thus the scratchSpaceStorageClass in the status of the CDIConfig is blank) it will use the same storage class as the target PVC.
and if no storage classes exist at all, then don't set a storage class on the scratch space PVC.

**Comment by banksyian** [comment]
Thanks for the replies, the scratchSpaceStorageClass does appear to be set correctly on the CDIConfig
```
apiVersion: cdi.kubevirt.io/v1alpha1
kind: CDIConfig
metadata:
  creationTimestamp: "2020-06-30T08:42:55Z"
  generation: 3
  labels:
    app: containerized-data-importer
    cdi.kubevirt.io: ""
  name: config
  ownerReferences:
  - apiVersion: cdi.kubevirt.io/v1alpha1
    blockOwnerDeletion: true
    controller: true
    kind: CDI
    name: cdi
    uid: 80af80e8-7c71-4961-b523-e115c8915464
  resourceVersion: "25334495"
  selfLink: /apis/cdi.kubevirt.io/v1alpha1/cdiconfigs/config
  uid: 157de5da-8906-4f59-98bc-bf293f898d36
spec: {}
status:
  defaultPodResourceRequirements:
    limits:
      cpu: "0"
      memory: "0"
    requests:
      cpu: "0"
      memory: "0"
  scratchSpaceStorageClass: fast
```
The default storage class is also set to "fast", which is the only storage class.
```
NAME             PROVISIONER         RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
fast (default)   csi.storageos.com   Delete          Immediate           true                   9d
```

If I manually create the scratch storage PVC the datavolume does mount it and the cdi-upload pod launches and is in a running state but the logs show ```cdi-upload-upload-datavolume pod not controlled by pvc upload-datavolume-scratch```. Is there some annotation or configuration option I could be missing from the scratch PVC?

**Comment by awels** [comment]
You should not have to worry about scratch space at all, CDI takes care of creating the PVC and setting the owner and everything correctly (when the pod finishes, it will remove the scratch space). However I know storageos has a bug in it when the owner of the PVC is a pod it basically just hangs. Since storageos is closed source I was unable to track down the exact issue. But the combination of the PVC having an owner reference (like the scratch space pvc does) and storageos is the problem.

**Comment by awels** [comment]
You can verify my claim by using for instance the [hostpath provisioner](https://github.com/kubevirt/hostpath-provisioner) together with the [operator](https://github.com/kubevirt/hostpath-provisioner-operator) and repeating the same test. For file system based hostpath storage there is not much difference between that and storageos.

**Comment by banksyian** [comment]
Thanks for the info, I was skeptical that there should be anything wrong with the PVC from a CDI perspective. I will Follow up with StorageOS.

**Comment by banksyian** [comment]
Hi, to help investigate this further with StorageOS are you able to advise what the mechanism for initiating the scratch PVC creation is. Unfortunately I am struggling to find any logs to suggest where it is failing, and this should be able to point StorageOS in the right direction to pinpoint the issue.

**Comment by awels** [comment]
So the scratch PVC is a regular PVC, with one distinct difference from most other PVCs. The ownerRef of the PVC is set to the POD that will use it. This allows us to not worry about manually deleting the PVC after the POD is complete, because the POD will get deleted, and in turn due to the owner being deleted, k8s will automatically delete the PVC as well. You should be able to reproduce the problem in storage OS by creating a pod that uses a pvc, and then creating the PVC with an ownerRef of that pod.
