### ISSUE TITLE
[Flaky CI] Timeout during cluster initialization on pull-kubevirt-e2e-kind-1.17-sriov

### ISSUE THREAD

**Issue by brybacki** [kubevirt/kubevirt#3777]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement
/triage build-officer

**What happened**:
Some tests are failing on timeout during environment initialization on `pull-kubevirt-e2e-kind-1.17-sriov`: 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. [etcdserver: request timed out](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3735/pull-kubevirt-e2e-kind-1.17-sriov/1280325518868090880)
2. [etcdserver: request timed out](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3479/pull-kubevirt-e2e-kind-1.17-sriov/1280445678270550016)
3. [error: timed out waiting for the condition on kubevirts/kubevirt](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3767/pull-kubevirt-e2e-kind-1.17-sriov/1280423410660282369)
4. [error: timed out waiting for the condition on kubevirts/kubevirt](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3479/pull-kubevirt-e2e-kind-1.17-sriov/1280453858899791873)
5. [Failed to create secretetcdserver: request timed out](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3735/pull-kubevirt-e2e-kind-1.17-sriov/1280479023872348162)

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
- LANE: `pull-kubevirt-e2e-kind-1.17-sriov`

**Comment by phoracek** [comment]
/assign @ormergi 

Is this new or related to the watchers issue?

**Comment by ormergi** [comment]
> /assign @ormergi
> 
> Is this new or related to the watchers issue?

Yes it might be.
This is good summary of the problem, responsiveness of kube-api.
Is it likely that kube-api is "exhausted", or taking to many resources, by all the wait_for... functions that keep querying it?

**Comment by phoracek** [comment]
Hard to imagine it would be too much. We have sleeps between retries, so it is one request every 3-10 seconds. At least the code I am aware of.

**Comment by ormergi** [comment]
/close
Should be fixed by #4588
