### ISSUE TITLE
SELinux Tests fail to run properly on kind infra, being used by ipv6 lane

### ISSUE THREAD

**Issue by kbidarkar** [kubevirt/kubevirt#3780]
**Is this a BUG REPORT or FEATURE REQUEST?**: `Test Infra enhancement`

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:   `SELinux Tests fail to run properly on kind infra, being used by ipv6 lane`
```
• Failure [16.345 seconds]
SecurityFeatures
/root/go/src/kubevirt.io/kubevirt/tests/security_features_test.go:41
  Check virt-launcher securityContext
  /root/go/src/kubevirt.io/kubevirt/tests/security_features_test.go:88
    With selinuxLauncherType undefined
    /root/go/src/kubevirt.io/kubevirt/tests/security_features_test.go:93
      [test_id:4297]Make sure qemu processes are MCS constrained [It]
      /root/go/src/kubevirt.io/kubevirt/tests/security_features_test.go:146

      Expected
          <string>: spc_t
      to equal
          <string>: container_t

      /root/go/src/kubevirt.io/kubevirt/tests/security_features_test.go:164
```

```
• Failure [14.820 seconds]
SecurityFeatures
/root/go/src/kubevirt.io/kubevirt/tests/security_features_test.go:41
  Check virt-launcher securityContext
  /root/go/src/kubevirt.io/kubevirt/tests/security_features_test.go:88
    With selinuxLauncherType defined as virt_launcher.process
    /root/go/src/kubevirt.io/kubevirt/tests/security_features_test.go:207
      [test_id:4298]qemu process type is virt_launcher.process, when selinuxLauncherType is virt_launcher.process [It]
      /root/go/src/kubevirt.io/kubevirt/tests/security_features_test.go:209

      Expected
          <string>: spc_t
      to equal
          <string>: virt_launcher.process

      /root/go/src/kubevirt.io/kubevirt/tests/security_features_test.go:240
```

**What you expected to happen**:

We should update the test infra, to be able to work with above `SELinux tests`

**How to reproduce it (as minimally and precisely as possible)**: `Try running tests 4297 and 4298 in ests/security_features_test.go without SkipSELinuxTestIfRunnigOnKindInfra`

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by kbidarkar** [comment]
On a second thought, probably a complete review of SELinux related tests in `tests/security_features_test.go` is needed, when running things on `kind`  based  infra.

**Comment by rmohr** [comment]
@kbidarkar why do you expect the tests to work on kind? I don't think that we can rely on selinux in kind setups. @qinqon any thoughts?
