### ISSUE TITLE
[Flakey CI] [rfe_id:694][crit:medium][vendor:cnv-qe@redhat.com][level:component]Networking VirtualMachineInstance with masquerade binding mechanism [test_id:1780][label:masquerade_binding_connectivity]should allow regular network connection with a specific port number

### ISSUE THREAD

**Issue by omeryahud** [kubevirt/kubevirt#3811]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-officer

**What happened**:
Flakefinder reported a flakey test:
```
[rfe_id:694][crit:medium][vendor:cnv-qe@redhat.com][level:component]Networking VirtualMachineInstance with masquerade binding mechanism [test_id:1780][label:masquerade_binding_connectivity]should allow regular network connection with a specific port number
```
in this Prow job:
- [Timed out](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3735/pull-kubevirt-e2e-k8s-1.17/1280614918751522816) 

**What you expected to happen**:
Test to pass
**How to reproduce it (as minimally and precisely as possible)**:
See Prow job

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by awels** [comment]
Another instance here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3961/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1293065443069661184

**Comment by orenc1** [comment]
Another instance here:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4165/pull-kubevirt-e2e-k8s-1.16/1304654863027671041

**Comment by ormergi** [comment]
Another instance here:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4128/pull-kubevirt-e2e-k8s-1.17/1315959478050361344

**Comment by ormergi** [comment]
Another instance here:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/563/check-provision-k8s-1.19/1375108411544309760

A VM creation timeout
