### ISSUE TITLE
Configurations [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]with CPU spec [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]when CPU model equals to passthrough [test_id:1679]should report exactly the same model as node CPU	

### ISSUE THREAD

**Issue by akrejcir** [kubevirt/kubevirt#3821]
/kind bug
/triage build-officer

**What happened**:
```
/root/go/src/kubevirt.io/kubevirt/tests/vmi_configuration_test.go:1448
Unexpected error:
    <*errors.errorString | 0xc0028aa670>: {
        s: "send to spawned process command reached the timeout 9.972322443s",
    }
    send to spawned process command reached the timeout 9.972322443s
occurred
/root/go/src/kubevirt.io/kubevirt/tests/vmi_configuration_test.go:1460
```

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2694/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1282643157204340737

**Comment by nelsonspbr** [comment]
Reported again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev/1356519903128981504

**Configurations [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]with CPU spec [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]when CPU model equals to passthrough [test_id:1679]should report exactly the same model as node CPU**

```
tests/utils.go:3136
Timed out after 60.000s.
Expected
    <bool>: false
to be true
tests/vmi_configuration_test.go:1501
```

**Comment by fgimenez** [comment]
Happened here again https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-latest/1358536187786039298

**Comment by oshoval** [comment]
I think https://github.com/kubevirt/kubevirt/pull/5019 would fix it, because its an issue of the login,
i saw it once comes with the race condition between the cloud-init which set the password and the Login,
When the login failed the first time, it comes out of sync in the 2nd retry and this is the error that occurs.

The last stdout is 
```
{"component":"tests","kind":"VirtualMachineInstance","level":"info","msg":"Login: []","name":"testvmidw9fkf4cp2bg88sh59n6q7jhnmlvbjgr2z65xdldcn8ln488","namespace":"kubevirt-test-default","pos":"utils.go:2983","timestamp":"2020-07-13T14:03:13.873094Z","uid":""}
```
For some reason it didn't dump the VM starting console.

/cc @davidvossel
