### ISSUE TITLE
upgrade qemu-kvm to 4.1.1

### ISSUE THREAD

**Issue by wavezhang** [kubevirt/kubevirt#3826]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

I‘m facing a bug when use kubevirt ([vhost version](https://github.com/kubevirt/kubevirt/pull/3208)) with ovs-dpdk.
And finally, I find out it a [bug ](https://bugzilla.redhat.com/show_bug.cgi?id=1738768) in qemu-4.1.0 which [fixed ](https://github.com/qemu/qemu/commit/7b404cae7fa2850d476c29258f03b8e77a5b4bd0) in qemu-4.1.1 .

Since there are [lots of bugfix](https://github.com/qemu/qemu/compare/v4.1.0...v4.1.1) in qemu-4.1.1, It is better to do a upgrade.

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@andreabolognani @crobinso let's meet soon and see if we can switch to coprs to provide qemu/libvirt updates more fluently.

**Comment by andreabolognani** [comment]
Yeah, I've been plenty busy with other work but we should definitely try to switch over to the new COPRs soon.

**Comment by andreabolognani** [comment]
This had actually been addressed by https://github.com/kubevirt/kubevirt/pull/3268 a month before this issue was opened, so I guess @wavezhang was running a release instead of master at the time?

Either way, this has long been addressed. Can we just close it?
