### ISSUE TITLE
[Flaky CI] SRIOV VirtualMachineInstance with sriov plugin interface [test_id:3957]should connect to another machine with sriov interface over IPv6

### ISSUE THREAD

**Issue by omeryahud** [kubevirt/kubevirt#3828]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-officer

**What happened**:
Flakefinder reported a flaky test
```
SRIOV VirtualMachineInstance with sriov plugin interface [test_id:3957]should connect to another machine with sriov interface over IPv6
```
in this Prow job:
- [Timeout](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3784/pull-kubevirt-e2e-kind-1.17-sriov/1283282998891909121)

**What you expected to happen**:
Test to pass
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tomob** [comment]
Another: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4617/pull-kubevirt-e2e-kind-1.17-sriov/1336806311739789312
