### ISSUE TITLE
[Flaky CI] [rfe_id:3423][crit:high][vendor:cnv-qe@redhat.com][level:component]VmWatch [test_id:3466]Should update vmi status with the proper columns using 'kubectl get vmi -w'

### ISSUE THREAD

**Issue by omeryahud** [kubevirt/kubevirt#3829]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-officer

**What happened**:
Flakefinder reported a flaky test:
```
[rfe_id:3423][crit:high][vendor:cnv-qe@redhat.com][level:component]VmWatch [test_id:3466]Should update vmi status with the proper columns using 'kubectl get vmi -w'
```
in this Prow job:
- [Timeout](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3784/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1283178938201280512)

**What you expected to happen**:
Test to pass
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@jean-edouard would you mind having a look?

**Comment by jean-edouard** [comment]
This test has quite a flaky history, however the problem here seems to be related to VMI management issues rather than actual test code.
I will look into it more closely and hopefully find something.

**Comment by rmohr** [comment]
Thanks @jean-edouard

**Comment by jean-edouard** [comment]
There are a lot of errors in https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3784/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1283178938201280512/artifacts/k8s-reporter/pods/1_kubevirt_virt-handler-66sf7-virt-handler.log
This one happens a few times:
```
{"component":"virt-handler","kind":"","level":"error","msg":"Updating the VirtualMachineInstance status failed.","name":"testvmitcz59lb99cgfbn67nbhjpnbz8sxzpxv2fndnkdj5fc6f8nwp","namespace":"kubevirt-test-default","pos":"vm.go:1193","reason":"Operation cannot be fulfilled on virtualmachineinstances.kubevirt.io \"testvmitcz59lb99cgfbn67nbhjpnbz8sxzpxv2fndnkdj5fc6f8nwp\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2020-07-15T02:55:11.448255Z","uid":"39eea595-f23d-4c58-86cf-27c2cccab659"}
```
It seems like that could prevent the restart request from going through, which would lead to the exact failure that happened here. (timeout waiting for a new VMI to appear).

**Comment by jean-edouard** [comment]
The above was a red herring...
I think the problem really is the timeout this time. 60 seconds to reboot a cirros VM is pretty tight, especially on an ipv6 system, since part of the boot process involves pinging IPs.
I ran the test with added debug a few times on my non-IPv6 setup, and it already routinely hits 35+ seconds just for the reboot.
I could increase the timeout, but we could also switch to using alpine instead of cirros, since it doesn't ping IPs as part of its boot process.
@rmohr what do you think?

**Comment by rmohr** [comment]
> I ran the test with added debug a few times on my non-IPv6 setup, and it already routinely hits 35+ seconds just for the reboot.
> I could increase the timeout, but we could also switch to using alpine instead of cirros, since it doesn't ping IPs as part of its boot process.

This normally only happens if the cirros VM does not have cloud-init payload attached. Cirros is the fastest booting OS (if the workload is there). I assume that it tries to find a cloud-init source on the network?

**Comment by jean-edouard** [comment]
@rmohr, that's probably the issue! The VM is definitely created without cloud-init. However, I could only find examples of adding cloud-init data to VMIs, not VMs. Is that something that has yet to be implemented? If that's complicated, wouldn't it just be easier to fallback to alpine? Thanks

**Comment by rmohr** [comment]
Something like 

```diff
$ git diff
diff --git a/tests/utils.go b/tests/utils.go
index 76e601caf..752113768 100644
--- a/tests/utils.go
+++ b/tests/utils.go
@@ -1917,6 +1917,13 @@ func NewRandomVMIWithDataVolume(dataVolumeName string) *v1.VirtualMachineInstanc
        return vmi
 }
 
+func NewRandomVMWithEphemeralDiskAndConfigDriveUserdata(containerImage string, userData string) *v1.VirtualMachine {
+       vmi := NewRandomVMIWithEphemeralDiskAndConfigDriveUserdata(containerImage, userData)
+       vm := NewRandomVirtualMachine(vmi, false)
+
+       return vm
+}
+
 func NewRandomVMWithEphemeralDisk(containerImage string) *v1.VirtualMachine {
        vmi := NewRandomVMIWithEphemeralDisk(containerImage)
        vm := NewRandomVirtualMachine(vmi, false)
```

should do the trick.
