### ISSUE TITLE
Remove the "lane-focus" feature from our code to stop reporting failing test lanes

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#3832]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

> /kind enhancement

**What happened**:

With #3431 a focus feature got added to our code-base. It seemed to not hurt at the time but now that it is used sometimes it becomes clear that it pollutes the CI system with failing jobs.

As a replacement the Draft feature for PRs should be used. On Drafts, only test-lanes which are explicitly triggered with a `/test <name>` are run.

**What you expected to happen**:

Let's revert #3431 and use the `Draft PR` feature instead.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
Here is one example: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3797/pull-kubevirt-e2e-k8s-cnao-1.17/1283655830280867840

**Comment by oshoval** [comment]
will do,
just a nit, if desired, we can do that Travis would detect if a focus is enabled, and make the lane `exit 0`
this way it wont create noise, and no need to move to draft

**Comment by rmohr** [comment]
> just a nit, if desired, we can do that Travis would detect if a focus is enabled, and make the lane `exit 0`

Hm, then technically the test would have passed which would make it probably worse :)

**Comment by rmohr** [comment]
> btw Travis still runs also on draft, i guess its known and would stop once it would move to prow

Yes and Yes. We mostly care about our Prow jobs since that accounts against our infra, Travis does not.

**Comment by oshoval** [comment]
> > just a nit, if desired, we can do that Travis would detect if a focus is enabled, and make the lane `exit 0`
> 
> Hm, then technically the test would have passed which would make it probably worse :)

yep but Travis would guard us of course, np just was an idea in case you like it, thx
