### ISSUE TITLE
Implementing sidecar containers

### ISSUE THREAD

**Issue by ams0** [kubevirt/kubevirt#3835]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind bug
/kind enhancement

**What happened**:

We want to explore the use case of using a sidecar container to collect the logs from a VM and ship it to a logging facility. We understand the `hookSidecars` feature can be of help here but it seems to have an hardcoded path for a shared volume with the compute container on `/var/run/kubevirt-hooks`; we would like to be able to specify things like resources and requests independently for the sidecar container and specify an arbitrary number of sidecar containers. We thought about using things like OPA to inject a sidecar into each pod but it will be much much better if we can implement this in the VirtualMachine object and then the controller will create the pod with the right containers.

**What you expected to happen**:

Be able to specify a sidecard container in the VirtualMachine definition and that will create a sidecar in the virt-launcher pod.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by teo-tsou** [comment]
Is there any update on that?

**Comment by daghaian** [comment]
Would like to revisit this option. I'm happy to contribute this feature if Kubevirt thinks it would be worthwhile

@rmohr @rthallisey @mhenriks
