### ISSUE TITLE
[flaky test] SRIOV VirtualMachineInstance with sriov plugin interface [test_id:3985]should create a virtual machine with sriov interface with custom MAC address

### ISSUE THREAD

**Issue by shwetaap** [kubevirt/kubevirt#3840]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-officer

**What happened**:
Flakefinder reported a flaky test:

SRIOV VirtualMachineInstance with sriov plugin interface [test_id:3985]should create a virtual machine with sriov interface with custom MAC address

/root/go/src/kubevirt.io/kubevirt/tests/vmi_multus_test.go:790
MAC "de:ad:00:00:be:ef" was not found in the VMI testvmi87g5m257xp9wd2dpcqkmg8vmfg44zmf8bslqn4557wxt9kp7 within the given timeout
Unexpected error:
    <expect.TimeoutError>: 15000000000
    expect: timer expired after 15 seconds
occurred
/root/go/src/kubevirt.io/kubevirt/tests/vmi_multus_test.go:934

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3784/pull-kubevirt-e2e-kind-1.17-sriov/1281192600501489664

**What you expected to happen**:
Test to pass

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by alonSadan** [comment]
hopefully #4001 will solve it.
/assign @alonSadan
