### ISSUE TITLE
Support ovs port directly

### ISSUE THREAD

**Issue by wavezhang** [kubevirt/kubevirt#3842]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind enhancement

**What happened**:

**What you expected to happen**:
Support start vm with interfaces like following config:
```

<interface type='bridge'>
 <mac address='52:54:00:71:b1:b6'/>
 <source bridge='ovsbr'/>
 <virtualport type='openvswitch'/>
 <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
</interface>
```
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@phoracek could you help out here?

**Comment by phoracek** [comment]
@warmchang the supported and Kubernetes way of attaching to network interfaces, including OVS bridges, is to use CNI. You can install [Multus](https://github.com/intel/multus-cni) (allowing you to connect Pods and VMs to secondary interfaces) and [OVS CNI](https://github.com/kubevirt/ovs-cni) (exposing OVS bridges) using an [operator](https://github.com/kubevirt/cluster-network-addons-operator/) or in any way you prefer.

If you insist on using libvirt XML to do this, you would first need to get the OVS bridge into the virt-launcher Pod and then you'd need to use a KubeVirt hook to adjust the domain XML. I strongly advise to use the supported way of CNI.
