### ISSUE TITLE
Use ingress for inbound cluster access

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#387]
So far our manifests use Services and node ips to give external consumers access to cluster resources. 

This issue is about separating Services from the policies to grant external consumer access to these (internal) services. The Kube primitive to do this are [ingress controllers](https://kubernetes.io/docs/concepts/services-networking/ingress/).

The benefit of moving to ingress controllers should be to have a clean separation between the inner kubevirt layout (which is cluster agnostic), and the exposure of services to the outer world (which is eventually cluster dependent).

The goal of this issue is to
- [ ] write ingress resources for all relevenat services
- [ ] drop NodeIP in Services

Once these goals are reached it should be easier to adopt kubevirt to differnt cluster layouts.

**Comment by rmohr** [comment]
haproxy and virt-api were removed in 0.2.0.
