### ISSUE TITLE
[Flaky CI] qemu-kvm: failed to initialize KVM: Operation not permitted

### ISSUE THREAD

**Issue by jean-edouard** [kubevirt/kubevirt#3872]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-officer

**What happened**:
Flaky test:
```
SecurityFeatures Check virt-launcher securityContext With selinuxLauncherType defined as spc_t [test_id:3787]Should honor custom SELinux type for virt-launcher
```
in this prow job:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3585/pull-kubevirt-e2e-k8s-1.17/1285926381586223104

**What you expected to happen**:
Test to pass

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by maya-r** [comment]
getting "Domain requires KVM, but it is not available." here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4092/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1306486558169239552

**Comment by jean-edouard** [comment]
The cause is `/dev/kvm` being absent: https://github.com/libvirt/libvirt/blob/7143ae1265407e30e35bf0fc34c2dc8ab2d77600/src/qemu/qemu_process.c#L5391
Since I already have a PR open to ensure `/dev/null` and `/dev/urandom` are there, I just added a commit for `/dev/kvm`: https://github.com/kubevirt/kubevirt/pull/4194
Hopefully this is a timing issue, otherwise the fix will just move the error...

**Comment by omeryahud** [comment]
Seeing `Unable to open /dev/kvm: Operation not permitted` here:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4196/pull-kubevirt-e2e-k8s-1.16/1307987326898540544

**Comment by ksimon1** [comment]
Seeing `Unable to open /dev/kvm: Operation not permitted` here:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4100/pull-kubevirt-e2e-k8s-1.18/1308357893736632320

**Comment by shwetaap** [comment]
Seeing Unable to open /dev/kvm: Operation not permitted here:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4236/pull-kubevirt-e2e-k8s-1.16/1309183957853540352

**Comment by dhiller** [comment]
```
tests/network/services.go:236
Unexpected Warning event received: testvmi4fq45cqbjcjjzfspbnnvx7bl8gpktk88rnm9ncn86928n5vk,222bacbf-fe25-45bd-8c40-6577f7a747d8: server error. command SyncVMI failed: 
"LibvirtError(Code=38, Domain=0, Message='cannot open /dev/null: Operation not permitted')"
Expected
    <string>: Warning
not to equal
    <string>: Warning
tests/utils.go:360
```

Seen here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4297/pull-kubevirt-e2e-k8s-1.16/1312384420702851072

@jean-edouard not sure if this is the right place, or should I open another issue?

**Comment by qinqon** [comment]
Another one 
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4287/pull-kubevirt-e2e-k8s-1.18/1313621572384198656
