### ISSUE TITLE
virtctl in Windows 10 throws "Make raw terminal failed: The handle is invalid?" error 

### ISSUE THREAD

**Issue by bryantson** [kubevirt/kubevirt#3876]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
 /kind bug
> /kind enhancement

**What happened**:

Running virtctl CLI command in Microsoft Windows 10 through Cygwin/Mingw64 CLI returns "Make raw terminal failed: The handle is invalid?" error. The work-around solution exists by using "winpty" in front of the command, but the limitation remains.

**What you expected to happen**:

virtctl command works correctly in Microsoft Windows 10

**How to reproduce it (as minimally and precisely as possible)**:

1. Download virtctl CLI for Windows
2. Set the Environment Variable path for virtctl
3. Open Mingw64 CLI/Cygwin. 
4. Connect to Openshift cluster with CLI command. oc get vm or oc get vmi to get the VM to connect to
5. virtctl console VM_NAME
6. Notice the error message "Make raw terminal failed: The handle is invalid?"

**Anything else we need to know?**:

**Environment**: Microsoft Windows 10
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications: OCP 4.4.3 cluster
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): 
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@bryantson thanks for the report. We did not even think about windows when we implemented this and are therefore not testing it. Could you explain on how you are using "winpty  in front of the command"?

**Comment by rmohr** [comment]
/kind enhancement

Marking as enhancement since we did not target windows with `virtctl console` but if we can, it would be great to add.

**Comment by pashok2398** [comment]
Hi @rmohr
We facing same issue with `virtctl ssh` is this expected?

**Comment by rmohr** [comment]
I think there is a similar report here: https://github.com/kubevirt/kubevirt/issues/8094. Looks to me like for both cases `virtctl console` and `virtctl ssh` we have a wrong assumption in our code on how terminals work on windows under certain circumstances ...

@0xFelix FYI
