### ISSUE TITLE
Deploying haproxy and squid for kubevirt is broken on master

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#389]
https://github.com/kubevirt/kubevirt/pull/374 introduced a Dockerfile change, which makes the squid and the haproxy service deployable on openshift and breaks it on native k8s.

```bash
+ kubectl get pods --no-headers
+ cluster/kubectl.sh --core get pods --no-headers
+ grep -v Running
haproxy-1647080590-0r0kj                  0/1       container has runAsNonRoot and image will run as root   0         22m
spice-proxy-226395611-bjq67               0/1       container has runAsNonRoot and image will run as root   0         22m
```

Complete build log: https://rfenkhuber.fedorapeople.org/jenkins/155/console.log

OpenShift has a controller which assigns arbitrary UIDs to containers, if they are not allowed to run as root, whereas k8s only checks if they are allowed to run as root, and does not set a random user before.

**Comment by rmohr** [comment]
@fabiand @admiyo could you have a look?

**Comment by fabiand** [comment]
Fixed this isse, all containers are running again, but we need to workout a consistent way here.
