### ISSUE TITLE
[Flaky CI][rfe_id:1177][crit:medium][vendor:cnv-qe@redhat.com][level:component]VirtualMachine An invalid VirtualMachine given should be rejected when VM template lists a DataVolume, but VM lists PVC VolumeSource [It]

### ISSUE THREAD

**Issue by stu-gott** [kubevirt/kubevirt#3891]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/triage build-officer

**What happened**:

```• Failure [64.536 seconds]
[rfe_id:1177][crit:medium][vendor:cnv-qe@redhat.com][level:component]VirtualMachine
/root/go/src/kubevirt.io/kubevirt/tests/vm_test.go:53
  An invalid VirtualMachine given
  /root/go/src/kubevirt.io/kubevirt/tests/vm_test.go:67
    should be rejected when VM template lists a DataVolume, but VM lists PVC VolumeSource [It]
    /root/go/src/kubevirt.io/kubevirt/tests/vm_test.go:112
    Timed out after 60.000s.

    Timed out waiting for DataVolume to enter Succeeded phase
    Expected
        <v1alpha1.DataVolumePhase>: Pending
    to equal
        <v1alpha1.DataVolumePhase>: Succeeded
    /root/go/src/kubevirt.io/kubevirt/tests/vm_test.go:121
```

Also, probably same issue:

```STEP: Checking that the DataVolume has succeeded
STEP: Deleting the DataVolume
• Failure [62.655 seconds]
[rfe_id:1177][crit:medium][vendor:cnv-qe@redhat.com][level:component]VirtualMachine
/root/go/src/kubevirt.io/kubevirt/tests/vm_test.go:53
  An invalid VirtualMachine given
  /root/go/src/kubevirt.io/kubevirt/tests/vm_test.go:67
    should fail to start when a volume is backed by PVC created by DataVolume instead of the DataVolume itself [It]
    /root/go/src/kubevirt.io/kubevirt/tests/vm_test.go:153
    Timed out after 60.000s.
      
    Timed out waiting for DataVolume to enter Succeeded phase
    Expected
        <v1alpha1.DataVolumePhase>: Pending
    to equal
        <v1alpha1.DataVolumePhase>: Succeeded
    /root/go/src/kubevirt.io/kubevirt/tests/vm_test.go:162 

```

**What you expected to happen**:
Test to pass

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Failed job: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-hyperconverged-cluster-operator-release-4.5-hco-e2e-nightly-bundle-release-4-5-azure4/1286496876157210624

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by nunnatsa** [comment]
[Update - 02-AUG-2020]: failed again:
https://prow.ci.openshift.org/?type=periodic&job=periodic-ci-kubevirt-hyperconverged-cluster-operator-release-4.5-hco-e2e-nightly-bundle-release-4-5-azure4

**Comment by nunnatsa** [comment]
[Update 02-AUG-2020] faile again: https://prow.ci.openshift.org/?type=periodic&job=periodic-ci-kubevirt-hyperconverged-cluster-operator-release-4.5-hco-e2e-nightly-bundle-release-4-5-azure4

**Comment by brybacki** [comment]
again: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-hyperconverged-cluster-operator-release-4.5-hco-e2e-nightly-bundle-release-4-5-azure4/1293382309428334592

**Comment by ksimon1** [comment]
It occurred again https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-hyperconverged-cluster-operator-release-4.5-hco-e2e-nightly-bundle-release-4-5-azure4/1295919041008898048
But since the PR was merged two hours ago, I am not sure if the failing test was testing the old code without fix.
