### ISSUE TITLE
ipv6: Tests that use Fedora + dmidecode fail

### ISSUE THREAD

**Issue by jean-edouard** [kubevirt/kubevirt#3901]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
When running on the ipv6 lane, tests labelled with "[rfe_id:2926]" fail.

**What you expected to happen**:
The tests to pass.

**How to reproduce it (as minimally and precisely as possible)**:
`export KUBEVIRT_PROVIDER=kind-k8s-1.17.0-ipv6 && make cluster-up && make functest`

**Anything else we need to know?**:
For these tests, a dmidecode binary is downloaded first, as it's not included in the Fedora image.
The download silently fails on the ipv6 lane, but since it's written like `curl [...] > dmidecode ; chmod +x dmidecode`, an empty executable is created.
Then when the dmidecode output is grepped in the tests, nothing is found and the tests fail.

**Environment**:
- KubeVirt version (use `virtctl version`): master (0.31)
- Kubernetes version (use `kubectl version`): 1.17.0
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`): 5.7.10-201.fc32.x86_64
- Install tools:
- Others:

**Comment by maiqueb** [comment]
/close

The `kind-k8s-1.17.0-ipv6` lane was removed.
