### ISSUE TITLE
service not routing to VM anymore after changing VM size because of wrong flavor selector

### ISSUE THREAD

**Issue by jchraibi** [kubevirt/kubevirt#3906]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

**What happened**:
I have created a VM of flavor "large" and created a service that routes to that vm. A default selector on the service is created with "flavor=large" among others, and after changing the VM size (RAM, CPU), the selector becomes invalid because the VM is no longer of flavor=large. 

**What you expected to happen**:
The service shouldn't have a selector on the "flavor" of the VM, or it should be updated when the VM resources (ram, cpu) are changed.

**How to reproduce it (as minimally and precisely as possible)**:
I have created a VM of flavor "large" and created a service that routes to that vm. A default selector on the service is created with "flavor=large" among others, and after changing the VM size (RAM, CPU), the selector becomes invalid because the VM is no longer of flavor=large. 

**Environment**:
This is using Container Native Virtualization (Kubervirt) Operator version 2.3 on OpenShift 4.5

**Comment by rmohr** [comment]
@ksimon1 I wonder if the flavour should be a label at all. Maybe it should be an annotation instead?
/assign @ksimon1

**Comment by MarSik** [comment]
It is a label on the Template, because templates need to be searchable according to their flavour. I guess it just got propagated to the VM this way.
