### ISSUE TITLE
test: "start a vm with guest memory different from requested and keed guaranteed qos" is passing due to a bug

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#3910]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

**What you expected to happen**:
The test fails but is marked as passed due to a bug.

Sent: "swapoff -a && dd if=/dev/zero of=/dev/shm/test bs=1k count=118k; echo $?\n"

{"component":"tests","kind":"VirtualMachineInstance","level":"info","msg":"[{1 [ $(free -m | grep Mem: | tr -s ' ' | cut -d' ' -f2) -lt 80 ] \u0026\u0026 echo 'pass [pass]} {3 ' |\r\r\n| echo 'fail'\r\nswapoff -a \u0026\u0026 dd if=/dev/zero of=/dev/shm/test bs=1k count=118k; echo $?\r\npass\r\n$ swapoff -a \u0026\u0026 dd if=/dev/zero of=/dev/shm/test bs=1k count=118k; echo $?\r\n[    9.381602] dd invoked oom-killer: gfp_mask=0x2420848, order=0, oom_score_adj=0\r\n[    9.404287] CPU: 0 PID: 369 Comm: dd Not tainted 4.4.0-28-generic #47-Ubuntu\r\n[    9.408211] Hardware name: KubeVirt None/RHEL-AV, BIOS ?-20190727_073836-buildvm-ppc64le-16.ppc.fedoraproject.org-3.fc31 04/01/2014\r\n[    9.408211]  0000000000000286 00000000ed9282c1 ffff8800023b7538 ffffffff813eb1a3\r\n[    9.408211]  ffff8800023b7730 ffff88000231d280 ffff8800023b75a8 ffffffff812094fe\r\n[    9.408211]  ffffffff81ccd74f 0000000000000000 ffffffff81e66760 0000000000000206\r\n[    9.408211] Call Trace:\r\n[    9.408211]  [\u003cffffffff813eb1a3\u003e] dump_stack+0x63/0x90\r\n[    9.408211]  [\u003cffffffff812094fe\u003e] dump_header+0x5a/0x1c5\r\n[    9.408211]  [\u003cffffffff811913b2\u003e] oom_kill_process+0x202/0x3c0\r\n[    9.408211]  [\u003cffffffff811917d5\u003e] out_of_memory+0x215/0x460\r\n[    9.408211]  [\u003cffffffff8119794e\u003e] __alloc_pages_nodemask+0xafe/0xb60\r\n[    9.408211]  [\u003cffffffff810b267c\u003e] ? __enqueue_entity+0x6c/0x70\r\n[    9.408211]  [\u003cffffffff811e111c\u003e] alloc_pages_current+0x8c/0x110\r\n[    9.408211]  [\u003cffffffff8118dc5b\u003e] __page_cache_alloc+0xab/0xc0\r\n[    9.408211]  [\u003cffffffff8118e614\u003e] pagecache_get_page+0x84/0x1c0\r\n[    9.408211]  [\u003cffffffff8124477c\u003e] __getblk_slow+0xcc/0x2a0\r\n[    9.408211]  [\u003cffffffff8124499f\u003e] __getblk_gfp+0x4f/0x60\r\n[    9.408211]  [\u003cffffffff812d98cc\u003e] ext4_get_branch+0xac/0x130\r\n[    9.408211]  [\u003cffffffff812da3c1\u003e] ext4_ind_map_blocks+0xc1/0xbf0\r\n[    9.408211]  [\u003cffffffff8113e6aa\u003e] ? __delayacct_freepages_end+0x2a/0x30\r\n[    9.408211]  [\u003cffffffff811a56c5\u003e] ? do_try_to_free_pages+0x395/0x430\r\n[    9.408211]  [\u003cffffffff811a582e\u003e] ? try_to_free_pages+0xce/0x180\r\n[    9.408211]  [\u003cffffffff810ca961\u003e] ? __raw_callee_save___pv_queued_spin_unlock+0x11/0x20\r\n[    9.408211]  [\u003cffffffff81200f5e\u003e] ? mem_cgroup_commit_charge+0x6e/0xe0\r\n[    9.408211]  [\u003cffffffff81299acc\u003e] ext4_map_blocks+0x2ac/0x4b0\r\n[    9.408211]  [\u003cffffffff812e46f8\u003e] ext4_mpage_readpages+0x368/0x920\r\n[    9.408211]  [\u003cffffffff811e111c\u003e] ? alloc_pages_current+0x8c/0x110\r\n[    9.408211]  [\u003cffffffff81297606\u003e] ext4_readpages+0x36/0x40\r\n[    9.408211]  [\u003cffffffff8119c5f6\u003e] __do_page_cache_readahead+0x196/0x230\r\n[    9.408211]  [\u003cffffffff8118e5bd\u003e] ? pagecache_get_page+0x2d/0x1c0\r\n[    9.408211]  [\u003cffffffff811900b5\u003e] filemap_fault+0x375/0x3f0\r\n[    9.408211]  [\u003cffffffff811cb801\u003e] ? page_add_file_rmap+0x51/0x60\r\n[    9.408211]  [\u003cffffffff812a07c6\u003e] ext4_filemap_fault+0x36/0x50\r\n[    9.408211]  [\u003cffffffff811bc7d0\u003e] __do_fault+0x50/0xe0\r\n[    9.408211]  [\u003cffffffff811c02db\u003e] handle_mm_fault+0xf8b/0x1820\r\n[    9.408211]  [\u003cffffffff8118fa90\u003e] ? generic_file_write_iter+0xf0/0x1e0\r\n[    9.408211]  [\u003cffffffff8106b537\u003e] __do_page_fault+0x197/0x400\r\n[    9.408211]  [\u003cffffffff8106b807\u003e] trace_do_page_fault+0x37/0xe0\r\n[    9.408211]  [\u003cffffffff81063ed9\u003e] do_async_page_fault+0x19/0x70\r\n[    9.408211]  [\u003cffffffff81829868\u003e] async_page_fault+0x28/0x30\r\n[   10.142034] Mem-Info:\r\n[   10.150634] active_anon:5849 inactive_anon:7 isolated_anon:0\r\n[   10.150634]  active_file:11 inactive_file:14 isolated_file:6\r\n[   10.150634]  unevictable:0 dirty:0 writeback:0 unstable:0\r\n[   10.150634]  slab_reclaimable:1821 slab_unreclaimable:1827\r\n[   10.150634]  mapped:0 shmem:5679 pagetables:67 bounce:0\r\n[   10.150634]  free:215 free_pcp:0 free_cma:0\r\n[   10.240410] Node 0 DMA free:448kB min:328kB low:408kB high:492kB active_anon:7320kB inactive_anon:8kB active_file:40kB inactive_file:44kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:15992kB managed:15908kB mlocked:0kB dirty:0kB writeback:0kB mapped:0kB shmem:7036kB slab_reclaimable:3000kB slab_unreclaimable:2764kB kernel_stack:432kB pagetables:92kB unstable:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB writeback_tmp:0kB pages_scanned:504 all_unreclaimable? yes\r\n[   10.373539] lowmem_reserve[]: 0 20 20 20 20\r\n[   10.399777] Node 0 DMA32 free:568kB min:436kB low:544kB high:652kB active_anon:16076kB inactive_anon:20kB active_file:64kB inactive_file:172kB unevictable:0kB isolated(anon):0kB isolated(file):0kB present:46960kB managed:29472kB mlocked:0kB dirty:0kB writeback:0kB mapped:56kB shmem:15680kB slab_reclaimable:3948kB slab_unreclaimable:4544kB kernel_stack:816kB pagetables:176kB unstable:0kB bounce:0kB free_pcp:0kB local_pcp:0kB free_cma:0kB writeback_tmp:0kB pages_scanned:0 all_unreclaimable? no\r\n[   10.546259] lowmem_reserve[]: 0 0 0 0 0\r\n[   10.567837] Node 0 DMA: 31*4kB (UM) 12*8kB (U) 17*16kB (U) 1*32kB (U) 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 524kB\r\n[   10.631871] Node 0 DMA32: 42*4kB (UE) 34*8kB (UME) 9*16kB (UME) 0*32kB 0*64kB 0*128kB 0*256kB 0*512kB 0*1024kB 0*2048kB 0*4096kB = 584kB\r\n[   10.705938] 5799 total pagecache pages\r\n[   10.718859] 0 pages in swap cache\r\n[   10.730551] Swap cache stats: add 0, delete 0, find 0/0\r\n[   10.747355] Free swap  = 0kB\r\n[   10.758426] Total swap = 0kB\r\n[   10.768419] 15738 pages RAM\r\n[   10.778635] 0 pages HighMem/MovableOnly\r\n[   10.790403] 4393 pages reserved\r\n[   10.800566] 0 pages cma reserved\r\n[   10.811828] 0 pages hwpoisoned\r\n[   10.823208] Out of memory: Kill process 283 (dropbear) score 2 or sacrifice child\r\n[   10.846513] Killed process 283 (dropbear) total-vm:9216kB, anon-rss:84kB, file-rss:0kB\r\ndd: writing '/dev/shm/test': No space left on device\r\n22689+0 records in\r\n22688+0 records out**\r\n1\r\n$**  []}]","name":"testvmi5bbs4brmlwdk24xqmq8nlmxknzpzqpwsw8bffzhqpgg5b7jc","namespace":"kubevirt-test-default","pos":"vmi_configuration_test.go:1968","timestamp":"2020-07-29T08:10:14.463977Z","uid":"5adb8532-028d-4624-a45a-c121b57cb4a9"}
.
As it can be seen here (marked in bold). the result of the `echo $?` is `1` and not `0` as expected (due to out of memory error).
The test passes since the expected `0` is found in the output of the `swapoff -a && dd if=/dev/zero of=/dev/shm/test bs=1k count=118k`.

Sent: "swapoff -a && dd if=/dev/zero of=/dev/shm/test bs=1k count=118k; echo $?\n"
Match for RE: "0" found: ["0"] Buffer: ' |
| echo 'fail'
pass
$ swapoff -a && dd if=/dev/zero of=/dev/shm/test bs=1k count=118k; echo $?
[    9.616**0**

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
PR is skipping the test until the bug is fixed.

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by xpivarc** [comment]
@AlonaKaplan Was this fixed?

**Comment by AlonaKaplan** [comment]
> @AlonaKaplan Was this fixed?

The test is still existing and skipped, so seems it wasn"t addressed.

/remove-lifecycle rotten
/reopen

**Comment by iholder101** [comment]
@AlonaKaplan any news regarding this one?
Is the test still relevant?
