### ISSUE TITLE
virt-launcher and vmi failed to start [panic: timed out waiting for domain to be defined]

### ISSUE THREAD

**Issue by npu21** [kubevirt/kubevirt#3933]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
vmi yaml
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  creationTimestamp: null
  labels:
    special: test-vmi8
  name: test-vmi8
  namespace: kube-system
spec:
  domain:
    devices:
      disks:
        - disk:
            bus: virtio
          name: containerdisk
        - disk:
            bus: virtio
          name: cloudinitvolume
      interfaces:
        - masquerade: {}
          name: default
        - bridge: {}
          name: multus
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  networks:
    - name: default
      pod: {}
    - multus:
        networkName: dataplane
      name: multus
  terminationGracePeriodSeconds: 0
  volumes:
    - name: containerdisk
      containerDisk:
        image: kubevirt/fedora-cloud-registry-disk-demo
        imagePullPolicy: IfNotPresent
    - cloudInitNoCloud:
        userData: |
          #!/bin/bash
          echo "fedora" | passwd fedora --stdin
      name: cloudinitvolume
~                                
```
describe virt launcher pod 
```
Name:               virt-launcher-test-vmi8-ng7d9
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               compute15/172.30.10.81
Start Time:         Tue, 04 Aug 2020 09:02:44 +0800
Labels:             kubevirt.io=virt-launcher
                    kubevirt.io/created-by=34003dba-d5ee-11ea-bfc9-525400a630d9
                    special=test-vmi8
Annotations:        k8s.v1.cni.cncf.io/network-status:
                      [{
                          "name": "cni0",
                          "ips": [
                              "100.101.149.113"
                          ],
                          "default": true,
                          "dns": {}
                      },{
                          "name": "dataplane",
                          "interface": "net1",
                          "mac": "ca:b7:75:c4:b8:19",
                          "dns": {}
                      }]
                    k8s.v1.cni.cncf.io/networks: [{"interface":"net1","name":"dataplane","namespace":"kube-system"}]
                    k8s.v1.cni.cncf.io/networks-status:
                      [{
                          "name": "cni0",
                          "ips": [
                              "100.101.149.113"
                          ],
                          "default": true,
                          "dns": {}
                      },{
                          "name": "dataplane",
                          "interface": "net1",
                          "mac": "ca:b7:75:c4:b8:19",
                          "dns": {}
                      }]
                    kubevirt.io/domain: test-vmi8
                    traffic.sidecar.istio.io/kubevirtInterfaces: k6t-eth0
Status:             Failed
IP:                 100.101.149.113
Controlled By:      VirtualMachineInstance/test-vmi8
Init Containers:
  container-disk-binary:
    Container ID:  docker://72516b1466cfb941bc8435181cc71b05abe58c8473c155ae690a318c1757c593
    Image:         index.docker.io/kubevirt/virt-launcher@sha256:a6f00a7d80c3b86603f679754f0ed9eea4431b630fc253027e54d5a8a2a454ac
    Image ID:      docker-pullable://kubevirt/virt-launcher@sha256:a6f00a7d80c3b86603f679754f0ed9eea4431b630fc253027e54d5a8a2a454ac
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/cp
      /usr/bin/container-disk
      /init/usr/bin/container-disk
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 04 Aug 2020 09:02:48 +0800
      Finished:     Tue, 04 Aug 2020 09:02:48 +0800
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  40M
    Requests:
      cpu:        10m
      memory:     1M
    Environment:  <none>
    Mounts:
      /init/usr/bin from virt-bin-share-dir (rw)
Containers:
  compute:
    Container ID:  docker://98d574dc88b2e4ca6e2ce09adb527cc1528c6bbc4c820915d1c00941acfbdea3
    Image:         index.docker.io/kubevirt/virt-launcher@sha256:a6f00a7d80c3b86603f679754f0ed9eea4431b630fc253027e54d5a8a2a454ac
    Image ID:      docker-pullable://kubevirt/virt-launcher@sha256:a6f00a7d80c3b86603f679754f0ed9eea4431b630fc253027e54d5a8a2a454ac
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/virt-launcher
      --qemu-timeout
      5m
      --name
      test-vmi8
      --uid
      34003dba-d5ee-11ea-bfc9-525400a630d9
      --namespace
      kube-system
      --kubevirt-share-dir
      /var/run/kubevirt
      --ephemeral-disk-dir
      /var/run/kubevirt-ephemeral-disks
      --container-disk-dir
      /var/run/kubevirt/container-disks
      --readiness-file
      /var/run/kubevirt-infra/healthy
      --grace-period-seconds
      15
      --hook-sidecars
      0
      --less-pvc-space-toleration
      10
      --ovmf-path
      /usr/share/OVMF
    State:          Terminated
      Reason:       Error
      Exit Code:    2
      Started:      Tue, 04 Aug 2020 09:02:49 +0800
      Finished:     Tue, 04 Aug 2020 09:07:50 +0800
    Ready:          False
    Restart Count:  0
    Limits:
      devices.kubevirt.io/kvm:                1
      devices.kubevirt.io/tun:                1
      devices.kubevirt.io/vhost-net:          1
      macvtap.network.kubevirt.io/dataplane:  1
    Requests:
      cpu:                                    100m
      devices.kubevirt.io/kvm:                1
      devices.kubevirt.io/tun:                1
      devices.kubevirt.io/vhost-net:          1
      macvtap.network.kubevirt.io/dataplane:  1
      memory:                                 1187554432
    Readiness:                                exec [cat /var/run/kubevirt-infra/healthy] delay=4s timeout=5s period=1s #success=1 #failure=5
    Environment:
      KUBEVIRT_RESOURCE_NAME_multus:  macvtap.network.kubevirt.io/dataplane
    Mounts:
      /var/run/kubevirt-ephemeral-disks from ephemeral-disks (rw)
      /var/run/kubevirt-infra from infra-ready-mount (rw)
      /var/run/kubevirt/container-disks from container-disks (rw)
      /var/run/kubevirt/sockets from sockets (rw)
      /var/run/libvirt from libvirt-runtime (rw)
  volumecontainerdisk:
    Container ID:  docker://ae30ac68bf79f463ee2cd28233bb946f1a06977bc2edf2bf5cbfaf73ab301842
    Image:         kubevirt/fedora-cloud-registry-disk-demo
    Image ID:      docker-pullable://kubevirt/fedora-cloud-registry-disk-demo@sha256:740fa03e40d58efe2196735318dd4e15371c2fc40e399b012b4fe4f92a4a160d
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/container-disk
    Args:
      --copy-path
      /var/run/kubevirt-ephemeral-disks/container-disk-data/34003dba-d5ee-11ea-bfc9-525400a630d9/disk_0
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Tue, 04 Aug 2020 09:02:51 +0800
      Finished:     Tue, 04 Aug 2020 09:07:51 +0800
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  40M
    Requests:
      cpu:        10m
      memory:     1M
    Readiness:    exec [/usr/bin/container-disk --health-check] delay=1s timeout=1s period=1s #success=1 #failure=5
    Environment:  <none>
    Mounts:
      /usr/bin from virt-bin-share-dir (rw)
      /var/run/kubevirt-ephemeral-disks/container-disk-data/34003dba-d5ee-11ea-bfc9-525400a630d9 from container-disks (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  sockets:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  infra-ready-mount:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  virt-bin-share-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  libvirt-runtime:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  ephemeral-disks:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  container-disks:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:      
    SizeLimit:   <unset>
QoS Class:       Burstable
Node-Selectors:  kubevirt.io/schedulable=true
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age   From                Message
  ----     ------     ----  ----                -------
  Normal   Scheduled  23m   default-scheduler   Successfully assigned kube-system/virt-launcher-test-vmi8-ng7d9 to compute15
  Normal   Pulled     23m   kubelet, compute15  Container image "index.docker.io/kubevirt/virt-launcher@sha256:a6f00a7d80c3b86603f679754f0ed9eea4431b630fc253027e54d5a8a2a454ac" already present on machine
  Normal   Created    23m   kubelet, compute15  Created container container-disk-binary
  Normal   Started    23m   kubelet, compute15  Started container container-disk-binary
  Normal   Pulled     23m   kubelet, compute15  Container image "index.docker.io/kubevirt/virt-launcher@sha256:a6f00a7d80c3b86603f679754f0ed9eea4431b630fc253027e54d5a8a2a454ac" already present on machine
  Normal   Created    23m   kubelet, compute15  Created container compute
  Normal   Started    23m   kubelet, compute15  Started container compute
  Normal   Pulled     23m   kubelet, compute15  Container image "kubevirt/fedora-cloud-registry-disk-demo" already present on machine
  Normal   Created    23m   kubelet, compute15  Created container volumecontainerdisk
  Normal   Started    23m   kubelet, compute15  Started container volumecontainerdisk
  Warning  Unhealthy  18m   kubelet, compute15  Readiness probe errored: rpc error: code = Unknown desc = container not running (98d574dc88b2e4ca6e2ce09adb527cc1528c6bbc4c820915d1c00941acfbdea3)
  Warning  Unhealthy  18m   kubelet, compute15  Readiness probe errored: rpc error: code = Unknown desc = container not running (ae30ac68bf79f463ee2cd28233bb946f1a06977bc2edf2bf5cbfaf73ab301842)

```
virt-launcher pod log:

> root@mgt01:/home/test/kubevirt# kubectl logs -n kube-system virt-launcher-test-vmi8-ng7d9
Error from server (BadRequest): a container name must be specified for pod virt-launcher-test-vmi8-ng7d9, choose one of: [compute volumecontainerdisk] or one of the init containers: [container-disk-binary]
root@mgt01:/home/test/kubevirt# kubectl logs -n kube-system virt-launcher-test-vmi8-ng7d9 compute
{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:68","timestamp":"2020-08-04T01:02:50.173340Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:71","timestamp":"2020-08-04T01:02:50.173396Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu:///system","pos":"libvirt.go:356","timestamp":"2020-08-04T01:02:50.190967Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory')","pos":"libvirt.go:364","timestamp":"2020-08-04T01:02:50.191377Z"}
{"component":"virt-launcher","level":"info","msg":"libvirt version: 6.0.0, package: 16.fc31 (Unknown, 2020-04-07-15:55:55, )","subcomponent":"libvirt","thread":"81","timestamp":"2020-08-04T01:02:50.226000Z"}
{"component":"virt-launcher","level":"info","msg":"hostname: test-vmi8","subcomponent":"libvirt","thread":"81","timestamp":"2020-08-04T01:02:50.226000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Child process (/usr/sbin/dmidecode -q -t 0,1,2,3,4,17) unexpected exit status 1: /dev/mem: No such file or directory","pos":"virCommandWait:2709","subcomponent":"libvirt","thread":"81","timestamp":"2020-08-04T01:02:50.226000Z"}
{"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:372","timestamp":"2020-08-04T01:02:50.694141Z"}
{"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:372","timestamp":"2020-08-04T01:02:50.698692Z"}
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:72","timestamp":"2020-08-04T01:02:50.699114Z"}
panic: timed out waiting for domain to be defined
goroutine 1 [running]:
main.waitForDomainUUID(0x45d964b800, 0xc000538fc0, 0xc001af2b40, 0x1a56400, 0xc00062a070, 0xc000538fc0)
	cmd/virt-launcher/virt-launcher.go:209 +0x430
main.main()
	cmd/virt-launcher/virt-launcher.go:429 +0xe9d
{"component":"virt-launcher","level":"error","msg":"dirty virt-launcher shutdown","pos":"virt-launcher.go:510","reason":"exit status 2","timestamp":"2020-08-04T01:07:50.710836Z"}

virt-hanlder log:

> {"component":"virt-handler","level":"info","msg":"Processing event kube-system/test-vmi8","pos":"vm.go:1033","timestamp":"2020-08-04T01:02:53.618653Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled\n","name":"test-vmi8","namespace":"kube-system","pos":"vm.go:1035","timestamp":"2020-08-04T01:02:53.618746Z","uid":"34003dba-d5ee-11ea-bfc9-525400a630d9"}
{"component":"virt-handler","level":"info","msg":"Domain does not exist","pos":"vm.go:1042","timestamp":"2020-08-04T01:02:53.618801Z"}
{"component":"virt-handler","level":"info","msg":"updated MAC for net1 interface: old: ca:b7:75:c4:b8:19 -\u003e new: ca:b7:75:7a:85:f2","pos":"common.go:280","timestamp":"2020-08-04T01:02:53.909589Z"}
{"component":"virt-handler","level":"error","msg":"failed to connect interface net1 to bridge k6t-net1","pos":"podinterface.go:450","reason":"device or resource busy","timestamp":"2020-08-04T01:02:53.910947Z"}
{"component":"virt-handler","level":"fatal","msg":"failed to prepare pod networking","pos":"podinterface.go:110","reason":"device or resource busy","timestamp":"2020-08-04T01:02:53.911016Z"}
panic: failed to prepare pod networking
goroutine 820 [running, locked to thread]:
kubevirt.io/client-go/log.FilteredLogger.Critical(0xc001d20510, 0x1bdbaba, 0xc, 0x0, 0x2, 0x2, 0x2ae1b20, 0xc0019d9b50, 0x1bf909a, 0x20)
	staging/src/kubevirt.io/client-go/log/log.go:336 +0x1af
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/network.(*PodInterface).PlugPhase1(0x3dac080, 0xc0019d2c00, 0xc000287360, 0xc00228d140, 0xc0019d8068, 0x4, 0x1089b, 0xc00228e018, 0xc0019d8060)
	pkg/virt-launcher/virtwrap/network/podinterface.go:110 +0x468
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/network.SetupNetworkInterfacesPhase1(0xc0019d2c00, 0x1089b, 0xc00380b6b0, 0x42d4ff)
	pkg/virt-launcher/virtwrap/network/network.go:105 +0x267
kubevirt.io/kubevirt/pkg/virt-handler.(*VirtualMachineController).setPodNetworkPhase1.func1(0x18, 0xc00380b6c8)
	pkg/virt-handler/vm.go:360 +0x3a
kubevirt.io/kubevirt/pkg/virt-handler/isolation.(*realIsolationResult).DoNetNS.func1(0x2b2a6e0, 0xc001b17930, 0xc001b17950, 0x0)
	pkg/virt-handler/isolation/isolation.go:261 +0x26
kubevirt.io/kubevirt/vendor/github.com/containernetworking/plugins/pkg/ns.(*netNS).Do.func1(0x2b2a6e0, 0xc001b17930, 0x0, 0x0)
	vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go:183 +0x329
kubevirt.io/kubevirt/vendor/github.com/containernetworking/plugins/pkg/ns.(*netNS).Do.func2(0xc001ec90a0, 0xc00228d100, 0x2b2a6e0, 0xc001b17930, 0xc001b17940)
	vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go:200 +0x69
created by kubevirt.io/kubevirt/vendor/github.com/containernetworking/plugins/pkg/ns.(*netNS).Do
	vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go:197 +0x258

after restart

>{"component":"virt-handler","level":"info","msg":"Added ghost record for key kube-system/test-vmi8","pos":"cache.go:133","timestamp":"2020-08-04T01:04:27.405654Z"}
{"component":"virt-handler","level":"info","msg":"Starting collector: node name=compute15","pos":"prometheus.go:395","timestamp":"2020-08-04T01:04:27.406177Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer configMapInformer","pos":"virtinformers.go:233","timestamp":"2020-08-04T01:04:27.406291Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer CRDInformer","pos":"virtinformers.go:233","timestamp":"2020-08-04T01:04:27.406375Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer extensionsKubeVirtCAConfigMapInformer","pos":"virtinformers.go:233","timestamp":"2020-08-04T01:04:27.406424Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer vmiInformer","pos":"virtinformers.go:233","timestamp":"2020-08-04T01:04:27.406468Z"}
{"component":"virt-handler","level":"info","msg":"certificate from /etc/virt-handler/clientcertificates with common name 'kubevirt.io:system:client:virt-handler' retrieved.","pos":"cert-manager.go:182","timestamp":"2020-08-04T01:04:27.407130Z"}
{"component":"virt-handler","level":"info","msg":"certificate from /etc/virt-handler/servercertificates with common name 'kubevirt.io:system:node:virt-handler' retrieved.","pos":"cert-manager.go:182","timestamp":"2020-08-04T01:04:27.407288Z"}
{"component":"virt-handler","level":"info","msg":"Starting virt-handler controller.","pos":"vm.go:725","timestamp":"2020-08-04T01:04:27.506806Z"}
{"component":"virt-handler","level":"info","msg":"metrics: max concurrent requests=3","pos":"virt-handler.go:325","timestamp":"2020-08-04T01:04:27.506879Z"}
{"component":"virt-handler","level":"info","msg":"Starting device plugin controller","pos":"device_controller.go:92","timestamp":"2020-08-04T01:04:27.607068Z"}
{"component":"virt-handler","level":"info","msg":"kvm device plugin started","pos":"generic_device.go:169","timestamp":"2020-08-04T01:04:27.609147Z"}
{"component":"virt-handler","level":"info","msg":"tun device plugin started","pos":"generic_device.go:169","timestamp":"2020-08-04T01:04:27.609582Z"}
{"component":"virt-handler","level":"info","msg":"vhost-net device plugin started","pos":"generic_device.go:169","timestamp":"2020-08-04T01:04:27.632033Z"}
{"component":"virt-handler","level":"info","msg":"Processing event kube-system/test-vmi8","pos":"vm.go:1033","timestamp":"2020-08-04T01:04:27.707357Z"}
{"component":"virt-handler","kind":"VirtualMachineInstance","level":"info","msg":"VMI is in phase: Scheduled\n","name":"test-vmi8","namespace":"kube-system","pos":"vm.go:1035","timestamp":"2020-08-04T01:04:27.707490Z","uid":"34003dba-d5ee-11ea-bfc9-525400a630d9"}
{"component":"virt-handler","level":"info","msg":"Domain does not exist","pos":"vm.go:1042","timestamp":"2020-08-04T01:04:27.707566Z"}
{"component":"virt-handler","level":"info","msg":"updated MAC for net1 interface: old: ca:b7:75:ad:d0:f3 -\u003e new: ca:b7:75:dd:e0:b8","pos":"common.go:280","timestamp":"2020-08-04T01:04:27.827374Z"}
{"component":"virt-handler","level":"error","msg":"failed to create a bridge","pos":"podinterface.go:444","reason":"file exists","timestamp":"2020-08-04T01:04:27.827669Z"}
{"component":"virt-handler","level":"fatal","msg":"failed to prepare pod networking","pos":"podinterface.go:110","reason":"file exists","timestamp":"2020-08-04T01:04:27.827728Z"}
panic: failed to prepare pod networking
goroutine 381 [running, locked to thread]:
kubevirt.io/client-go/log.FilteredLogger.Critical(0xc002228420, 0x1bdbaba, 0xc, 0x0, 0x2, 0x2, 0x2ae1b20, 0xc00124bb20, 0x1bf909a, 0x20)
	staging/src/kubevirt.io/client-go/log/log.go:336 +0x1af
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/network.(*PodInterface).PlugPhase1(0x3dac080, 0xc00361c000, 0xc003247e00, 0xc003a35700, 0xc003abbd28, 0x4, 0x1089b, 0xc00354a698, 0xc003abbd20)
	pkg/virt-launcher/virtwrap/network/podinterface.go:110 +0x468
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/network.SetupNetworkInterfacesPhase1(0xc00361c000, 0x1089b, 0xc0036a36b0, 0x42d4ff)
	pkg/virt-launcher/virtwrap/network/network.go:105 +0x267
kubevirt.io/kubevirt/pkg/virt-handler.(*VirtualMachineController).setPodNetworkPhase1.func1(0x18, 0xc0036a36c8)
	pkg/virt-handler/vm.go:360 +0x3a
kubevirt.io/kubevirt/pkg/virt-handler/isolation.(*realIsolationResult).DoNetNS.func1(0x2b2a6e0, 0xc0039f1410, 0xc0039f1430, 0x0)
	pkg/virt-handler/isolation/isolation.go:261 +0x26
kubevirt.io/kubevirt/vendor/github.com/containernetworking/plugins/pkg/ns.(*netNS).Do.func1(0x2b2a6e0, 0xc0039f1410, 0x0, 0x0)
	vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go:183 +0x329
kubevirt.io/kubevirt/vendor/github.com/containernetworking/plugins/pkg/ns.(*netNS).Do.func2(0xc003abb2d0, 0xc003a356c0, 0x2b2a6e0, 0xc0039f1410, 0xc0039f1420)
	vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go:200 +0x69
created by kubevirt.io/kubevirt/vendor/github.com/containernetworking/plugins/pkg/ns.(*netNS).Do
	vendor/github.com/containernetworking/plugins/pkg/ns/ns_linux.go:197 +0x258

**Environment**:
- KubeVirt version (use `virtctl version`):v0.30.3
- Kubernetes version (use `kubectl version`):v1.14.3

I notice that virt-handler pod log:{"component":"virt-handler","level":"error","msg":"failed to connect interface net1 to bridge k6t-net1","pos":"podinterface.go:450","reason":"device or resource busy","timestamp":"2020-08-04T01:02:53.910947Z"}
{"component":"virt-handler","level":"fatal","msg":"failed to prepare pod networking","pos":"podinterface.go:110","reason":"device or resource busy","timestamp":"2020-08-04T01:02:53.911016Z"}
, but don't know how to resolve it. 
Any help will be appreciated！

**Comment by npu21** [comment]
@phoracek @rmohr Could you pls take a look？Thanks in advance！

**Comment by phoracek** [comment]
Please share the `NetworkAttachmentDefinition` you are referring to in the spec.

**Comment by npu21** [comment]
Sure,
```
root@mgt01:/home/test/kubevirt# kubectl get network-attachment-definitions.k8s.cni.cncf.io -n kube-system dataplane -oyaml
apiVersion: k8s.cni.cncf.io/v1
kind: NetworkAttachmentDefinition
metadata:
  annotations:
    k8s.v1.cni.cncf.io/resourceName: macvtap.network.kubevirt.io/dataplane
  creationTimestamp: "2020-08-03T01:19:49Z"
  generation: 5
  name: dataplane
  namespace: kube-system
  resourceVersion: "110483749"
  selfLink: /apis/k8s.cni.cncf.io/v1/namespaces/kube-system/network-attachment-definitions/dataplane
  uid: 6d187434-d527-11ea-bc0c-eeeeeeeeeeee
spec:
  config: '{ "cniVersion": "0.3.1", "name": "dataplane", "type": "macvtap", "mtu":
    1500 }'

```

```
root@mgt01:/home/test/kubevirt# kubectl get cm -n kube-system macvtap-deviceplugin-config -oyaml
apiVersion: v1
data:
  DP_MACVTAP_CONF: |
    [ {
        "name" : "dataplane",
        "master" : "data",
        "mode": "bridge",
        "capacity" : 50
    } ]
kind: ConfigMap
metadata:
  creationTimestamp: "2020-07-31T07:27:32Z"
  name: macvtap-deviceplugin-config
  namespace: kube-system
  resourceVersion: "110852371"
  selfLink: /api/v1/namespaces/kube-system/configmaps/macvtap-deviceplugin-config
  uid: 4c4c518d-d2ff-11ea-bc0c-eeeeeeeeeeee

```

**Comment by phoracek** [comment]
macvtap-cni won't work with `bridge` binding. You would need to use a special binding that is being developed as a part of https://github.com/kubevirt/kubevirt/pull/2935

**Comment by maiqueb** [comment]
> macvtap-cni won't work with `bridge` binding. You would need to use a special binding that is being developed as a part of #2935

Unfortunately the work to get the macvtap bind mechanism (PR #2935) merged had to be postponed (it's currently failing on 2 functional tests that I need to debug), but I'll resume it ASAP.

**Comment by npu21** [comment]
Thank you both @phoracek @maiqueb ,need it very much

**Comment by npu21** [comment]
I trid calico+macvlan and got this error:

> {"component":"virt-handler","level":"info","msg":"Processing event kube-system/test-vmi8","pos":"vm.go:1033","timestamp":"2020-08-04T11:57:50.989724Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled\n","name":"test-vmi8","namespace":"kube-system","pos":"vm.go:1035","timestamp":"2020-08-04T11:57:50.989866Z","uid":"7b1f3b18-d649-11ea-a182-525400a630d9"}
{"component":"virt-handler","level":"info","msg":"Domain does not exist","pos":"vm.go:1042","timestamp":"2020-08-04T11:57:50.989927Z"}
{"component":"virt-handler","level":"error","msg":"failed to get a link for interface: net1","pos":"podinterface.go:253","reason":"Link not found","timestamp":"2020-08-04T11:57:51.040636Z"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"test-vmi8","namespace":"kube-system","pos":"vm.go:1170","reason":"failed to configure vmi network: failed to configure vmi network for migration target: Link not found","timestamp":"2020-08-04T11:57:51.040975Z","uid":"7b1f3b18-d649-11ea-a182-525400a630d9"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance kube-system/test-vmi8","pos":"vm.go:773","reason":"failed to configure vmi network: failed to configure vmi network for migration target: Link not found","timestamp":"2020-08-04T11:57:51.041301Z"}
{"component":"virt-handler","level":"info","msg":"Processing event kube-system/test-vmi8","pos":"vm.go:1033","timestamp":"2020-08-04T11:59:12.961632Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Scheduled\n","name":"test-vmi8","namespace":"kube-system","pos":"vm.go:1035","timestamp":"2020-08-04T11:59:12.961750Z","uid":"7b1f3b18-d649-11ea-a182-525400a630d9"}
{"component":"virt-handler","level":"info","msg":"Domain does not exist","pos":"vm.go:1042","timestamp":"2020-08-04T11:59:12.961813Z"}
{"component":"virt-handler","level":"error","msg":"failed to get a link for interface: net1","pos":"podinterface.go:253","reason":"Link not found","timestamp":"2020-08-04T11:59:13.025390Z"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"test-vmi8","namespace":"kube-system","pos":"vm.go:1170","reason":"failed to configure vmi network: failed to configure vmi network for migration target: Link not found","timestamp":"2020-08-04T11:59:13.025588Z","uid":"7b1f3b18-d649-11ea-a182-525400a630d9"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance kube-system/test-vmi8","pos":"vm.go:773","reason":"failed to configure vmi network: failed to configure vmi network for migration target: Link not found","timestamp":"2020-08-04T11:59:13.025851Z"}

However,when create pod with the same config, the pod running well

```
 root@mgt01:/home/test/kubevirt# kubectl describe pod -n kube-system samplepod2 
Name:               samplepod2
Namespace:          kube-system
Priority:           0
PriorityClassName:  <none>
Node:               compute15/172.30.10.81
Start Time:         Tue, 04 Aug 2020 18:04:59 +0800
Labels:             <none>
Annotations:        k8s.v1.cni.cncf.io/network-status:
                      [{
                          "name": "cni0",
                          "ips": [
                              "100.101.149.165"
                          ],
                          "default": true,
                          "dns": {}
                      },{
                          "name": "macvlan",
                          "interface": "net1",
                          "ips": [
                              "172.30.16.57"
                          ],
                          "mac": "36:72:2a:0a:69:4d",
                          "dns": {}
                      }]
                    k8s.v1.cni.cncf.io/networks: macvlan
                    k8s.v1.cni.cncf.io/networks-status:
                      [{
                          "name": "cni0",
                          "ips": [
                              "100.101.149.165"
                          ],
                          "default": true,
                          "dns": {}
                      },{
                          "name": "macvlan",
                          "interface": "net1",
                          "ips": [
                              "172.30.16.57"
                          ],
                          "mac": "36:72:2a:0a:69:4d",
                          "dns": {}
                      }]
                    v1.multus-cni.io/default-network: cni0
Status:             Running
IP:                 100.101.149.165
Containers:
  busybox:
    Container ID:  docker://95f5ef8db2905c9dea17f65983733bd908947b8142c4dbb1e446ad61e60abe38
    Image:         busybox
    Image ID:      docker-pullable://busybox@sha256:4f47c01fa91355af2865ac10fef5bf6ec9c7f42ad2321377c21e844427972977
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sleep
      180000
    State:          Running
      Started:      Tue, 04 Aug 2020 18:05:08 +0800
    Ready:          True
    Restart Count:  0
    Environment:    <none>
    Mounts:
      /var/run/secrets/kubernetes.io/serviceaccount from default-token-kzr5c (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  default-token-kzr5c:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  default-token-kzr5c
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:          <none>
```
vmi yaml:

```
 apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  creationTimestamp: null
  labels:
    special: test-vmi8
  name: test-vmi8
  namespace: kube-system
spec:
  domain:
    devices:
      disks:
        - disk:
            bus: virtio
          name: containerdisk
        - disk:
            bus: virtio
          name: cloudinitvolume
      interfaces:
        - bridge: {}
          name: default
        - bridge: {}
          name: multus
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  networks:
    - name: default
      pod: {}
    - multus:
        networkName: macvlan
      name: multus
  terminationGracePeriodSeconds: 0
  volumes:
    - name: containerdisk
      containerDisk:
        image: kubevirt/fedora-cloud-registry-disk-demo
        imagePullPolicy: IfNotPresent
    - cloudInitNoCloud:
        userData: |
          #!/bin/bash
          echo "fedora" | passwd fedora --stdin
      name: cloudinitvolume
```
and macvlan conf:

```
root@compute02:/etc/cni/net.d# cat macvlan.conf 
{
  "cniVersion": "0.3.0",
  "type": "macvlan",
  "name": "macvlan",
  "master": "data",
  "mode": "bridge",
  "isDefaultGateway": true,
  "ipam": {
          "expiredPeriod": 10,
          "type": "host-local",
          "subnet": "172.30.16.0/24",
          "rangeStart": "172.30.16.20",
          "rangeEnd": "172.30.16.200",
          "gateway": "172.30.16.1",
          "routes": [
              { "dst": "0.0.0.0/0", "gw": "172.30.16.1" }
          ]
  }
}

```
I notice the eroor message "failed to get a link for interface: net1", dose it have something to with the fedora image?

**Comment by phoracek** [comment]
The same setup worked for me. The only difference was that I defined the network as NetworkAttachmentDefinition object, not as a file on the disk. Could you try that?

```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: macvlan
  namespace: kube-system
spec:
  config: '{
      "cniVersion": "0.3.0",
      "type": "macvlan",
      "name": "macvlan",
      "master": "enp2s0",
      "mode": "bridge",
      "isDefaultGateway": true,
      "ipam": {
        "expiredPeriod": 10,
        "type": "host-local",
        "subnet": "172.30.16.0/24",
        "rangeStart": "172.30.16.20",
        "rangeEnd": "172.30.16.200",
        "gateway": "172.30.16.1",
        "routes": [
          { "dst": "0.0.0.0/0", "gw": "172.30.16.1" }
        ]
      }
    }'
```
