### ISSUE TITLE
Cannot ssh to running Vm

### ISSUE THREAD

**Issue by birdiesanders** [kubevirt/kubevirt#3934]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
I followed the lab2 tutorial, and cannot get ssh access to the machine.
**What you expected to happen**:
passwordless login via ssh_key
**How to reproduce it (as minimally and precisely as possible)**:
Install according to tutorial, use virtctl to expose the Vm, attempt to connect. 

**Anything else we need to know?**:
CIVO k3s cluster
**Environment**:
- KubeVirt version (use `virtctl version`): 0.9.3
- Kubernetes version (use `kubectl version`): 1.18.6
- VM or VMI specifications: stnadard spec file from the lab 2 tutorial
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu 16.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
/assign @codificat 

@codificat who can help with the tutorials?

**Comment by codificat** [comment]
Oh, apologies I missed that - this came in during pto and it slipped through the return :/

/remove-lifecycle stale

@mazzystr I believe you last looked at the labs, did you see that issue?

I just went through the lab on a quick minikube cluster and I did hit an issue with the image in the sample manifest (kubevirt/kubevirt.github.io#655) but it's unrelated to this, and I could ssh just fine...

**Comment by codificat** [comment]
@birdiesanders are you still having this problem?

If so, please provide details of the ssh command that you are attempting and how it is failing
Thanks

**Comment by lhchang** [comment]
I am having issues with successfully SSH'ing into the fedora machine as well. Using the updated changes by specifying private key instead of public key, but eventually the connection still times out. 

I am using a Minikube environment.
