### ISSUE TITLE
[FEATURE REQUEST] add version subcommand for Kubevirt component

### ISSUE THREAD

**Issue by DanielQujun** [kubevirt/kubevirt#3935]
Hi, guys.

Looks like we do not have a version subcommand, wish we could add it. It would be useful at some usercases~

> /kind enhancement

**Comment by rmohr** [comment]
Did you try `virtctl version`? There is also a rest endpoint to get the information: https://kubevirt.io/api-reference/master/operations.html#_version.

**Comment by DanielQujun** [comment]
> Did you try `virtctl version`? There is also a rest endpoint to get the information: https://kubevirt.io/api-reference/master/operations.html#_version.

sorry, I did not know that. my case is sometimes we need to check the version or git commit ids before we push to the production environment, so it might be convenient if check it offline.

**Comment by rmohr** [comment]
> sorry, I did not know that. my case is sometimes we need to check the version or git commit ids before we push to the production environment, so it might be convenient if check it offline.

you mean running it on the container image binaries?

**Comment by DanielQujun** [comment]
> you mean running it on the container image binaries?
yes~

**Comment by rmohr** [comment]
There should be a `/.version` file in every container which we build. Is that sufficient?
