### ISSUE TITLE
[FEATURE REQUEST] Add list subcommand for virtctl

### ISSUE THREAD

**Issue by DanielQujun** [kubevirt/kubevirt#3936]
Hi, guys.

when I try to operate a VMI, I need to use `kubectl get vmi` to get VMI's Name, It might be convenient if we add list VM subcommand for `virtctl`.

> /kind enhancement

**Comment by rmohr** [comment]
@DanielQujun did you have a look at the krew plugin for virtctl https://github.com/kubevirt/kubectl-virt-plugin?

After you install virtctl with it you can basically do this:

```
kubectl get vmi myvm
kubectl virt console myvm
```

Would that already be a good enough improvement for you?

**Comment by DanielQujun** [comment]
yes, I'll check it.
