### ISSUE TITLE
Resources should have OwnerReferences

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#394]
We should follow the Kube guidelines of adding `OwnerReferences` to objects which are created by our controllers.

An impotant note is:
> OwnerReference contains enough information to let you identify an owning object. Currently, an owning object must be in the same namespace, so there is no namespace field.

This is contradicting a little with the assumption that KubeVirt can be a kube add-on and manage vms in different namespaces (kubernetes/apimachinery#21).

API: https://kubernetes.io/docs/api-reference/v1.7/#ownerreference-v1-meta
Example: https://github.com/kubernetes/autoscaler/pull/271

**Comment by rmohr** [comment]
> This is contradicting a little with the assumption that KubeVirt can be a kube add-on and manage vms in different namespaces (kubernetes/apimachinery#21).

I think you mix up the controller as an owner vs the object as an owner. A VM Object is not owned by the VM controller, for instance. A VM Object or a Pod Object, however, can be owned by another object. A more concrete example: a Pod Object can be owned by a Deployment Object, which is namespaces, but not by the Deployment controller, which operates on all Deployment Objects in all namespaces.

**Comment by fabiand** [comment]
So, the owner reference can actually be both - it can represent another object as an owner or a controller as an owner (if  `controller` is set to true). I.e. a replica pod is owned by it's controller:

```
                "ownerReferences": [
                    {
                        "apiVersion": "extensions/v1beta1",
                        "blockOwnerDeletion": true,
                        "controller": true,
                        "kind": "ReplicaSet",
                        "name": "virt-manifest-3590921033",
                        "uid": "abf9d1bb-8c20-11e7-a714-5254004f04dd"
                    }
                ],
```

But an issue is that we currently don't use this ownership pattern much, and sometimes it's unclear ho wan ownership should look. I.e. a VM instance as a result of a VMConfig - is it owned by the virt-controller or the vmconfig object? And should a VM object be owned by the controller at all?

**Comment by rmohr** [comment]
FYI:

* Here the proposal for OwnerRefs: https://github.com/kubernetes/community/blob/548eb7292d45a4af78e0141d33094130dfe6080a/contributors/design-proposals/garbage-collection.md

* Here the proposal for ControllerRefs: https://github.com/kubernetes/community/blob/31d62c70214d66ca2c21716c02b83d9087fdf3ff/contributors/design-proposals/controller-ref.md

That might help you.

Still, I don't see why we should have there an issue:

> This is contradicting a little with the assumption that KubeVirt can be a kube add-on and manage vms in different namespaces (kubernetes/apimachinery#21).

**Comment by fabiand** [comment]
From the second link:

> A ControllerRef is thus defined as an OwnerReference with Controller=true.

The problem is not here today, as we spawn VMs usually in the same namespace as the controllers.
But if we want to consider to move the controllers/active components to the `kube-system` namespace and manage VMs in other namespaces, *and* we use Owner and ControllerRefs, then we have an issue. Because today, OwnerReferences structs (which is used for both OwnerRefs and ControllerRefs) don't provide a field for the namespace of the owner, but rather work with the assumption that the owner resides in the same namespace. This would be violated in the `kube-system` case.

An except from the first link:

> Currently, an owning object must be in the same namespace as the dependent object, so there is no namespace field.

But as said, maybe this bug is to early, because we are not using OwnerReferences (yet), thus we don't have this issue right now.
At least I hope that the problem is clearer.

**Comment by rmohr** [comment]
> The problem is not here today, as we spawn VMs usually in the same namespace as the controllers.
> But if we want to consider to move the controllers/active components to the kube-system namespace and manage VMs in other namespaces, and we use Owner and ControllerRefs, then we have an issue.

I am sorry, but you still seem to misinterpret something. Controller can live anywhere, also completely outside of k8s. There is no connection between the namespace where you deploy our controllers, and on which namespaces they operate.

> OwnerReferences structs (which is used for both OwnerRefs and ControllerRefs) don't provide a field for the namespace of the owner, but rather work with the assumption that the owner resides in the same namespac of the owner

You only work with that assumption when the owner is *not* a ControllerRef (Controller=false), but another object (OwnerRef). If it would work like described above, then k8s would itself have to deploy all it's controllers in every namespace a user creates, and not just in `kube-system`.

**Comment by fabiand** [comment]
Let's revisit once it comes up.
