### ISSUE TITLE
Multiple virtctl binaries for 64bit Linux

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt#3943]
/kind bug

**What happened**:
While updating the virtctl section of the quickstart page I noticed there are multiple binaries for 64bit Linux... amd64 and x86_64.  Which one is correct?  Which one do we want to advertise?  Can we drop the unnecessary build?

**Anything else we need to know?**:
https://github.com/kubevirt/kubevirt/releases

**Comment by rmohr** [comment]
@mazzystr finally identified and a fix is pending in #3993. The binary is now also on release-0.32. We will drop the x86_64 ending and only release the amd64 one (like it was intended).
