### ISSUE TITLE
Repeating problems with test env provisioning

### ISSUE THREAD

**Issue by tomob** [kubevirt/kubevirt#3951]
Possibly a problem with networking or disk space. Hints:

* Timeout waiting for VM to be up: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/403/check-provision-k8s-1.15/1291708839774654464
* Timeout fetching an external resource (`Curl error (28): Timeout was reached for http://ftp.usf.edu/pub/centos/8.2.2004/BaseOS/x86_64/os/Packages/patch-2.7.6-11.el8.x86_64.rpm [Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds]`): https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/403/check-provision-k8s-1.18/1291714268873363456
* No space for fetching images: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1334/pull-containerized-data-importer-e2e-k8s-1.18-nfs/1291721239387181056

Errors like these repeat throughout the day (Fri Aug 7).

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-officer

> /kind enhancement

**Comment by rmohr** [comment]
> * Timeout waiting for VM to be up: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/403/check-provision-k8s-1.15/1291708839774654464

That should be fixed with moving our CI caches to a dedicated node.

> * Timeout fetching an external resource (`Curl error (28): Timeout was reached for http://ftp.usf.edu/pub/centos/8.2.2004/BaseOS/x86_64/os/Packages/patch-2.7.6-11.el8.x86_64.rpm [Operation too slow. Less than 1000 bytes/sec transferred the last 30 seconds]`): https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/403/check-provision-k8s-1.18/1291714268873363456

THis is basically bad luck. We can't do here much than just retriggering. The provision jobs on kubevirtci are intended to pull in all these resources to avoid issues like that then in repos like kubevirt/kubevirt.

> * No space for fetching images: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_containerized-data-importer/1334/pull-containerized-data-importer-e2e-k8s-1.18-nfs/1291721239387181056

That was due to some core dumps which ate up the whole disk space also fixed.
