### ISSUE TITLE
Networking VirtualMachineInstance with dhcp options [It] [test_id:1778]should offer extra dhcp options to pod iface

### ISSUE THREAD

**Issue by arnongilboa** [kubevirt/kubevirt#3964]
/kind bug
/triage build-officer

**What happened**:
```
[rfe_id:694][crit:medium][vendor:cnv-qe@redhat.com][level:component]Networking VirtualMachineInstance with dhcp options [It] [test_id:1778]should offer extra dhcp options to pod iface 
/root/go/src/kubevirt.io/kubevirt/tests/vmi_networking_test.go:668
```

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3888/pull-kubevirt-e2e-k8s-cnao-1.17/1292723654873845760

Fixed by: #3953

**Comment by AlonaKaplan** [comment]
PR https://github.com/kubevirt/kubevirt/pull/3953 solves the issue.
