### ISSUE TITLE
Control where Kubevirt pulls disk iamges from

### ISSUE THREAD

**Issue by cjreyn** [kubevirt/kubevirt#3983]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**Question**:
Is there a recommended way of restricting/controlling the images that can be used? In my organization we would want to limit images to be deployed from a certain registry only. I noticed there is an admission control webhook. Could this be used or extended? Would Open Policy Agent be preferred?

**Comment by rmohr** [comment]
@cjreyn a pod webhook would probably work. It may look a little bit strange for users, since they would see a successful VMI creation and then see warning events that the image is not accepted when the VMI is scheduled.

What exactly is k8s doing in that area?

**Comment by cjreyn** [comment]
I installed Open Policy Agent to test this. It provides a framework to programmatically define policy based upon the admission control webhooks. I tested it rejecting pods based upon the image name which worked fine. From what I can tell, it would work fine with Custom Resources too.

I believe that OPA wouldn't interfere with the existing admission control webhook that Kubevirt provides, since all webhooks are called so OPA will definitely run. 

For my use case, OPA looks the best bet.

**Comment by rmohr** [comment]
Great. Let us know if there is anything which you would needed changed in kubevirt to make it work seamlessly with Open Policy Agent.

**Comment by rmohr** [comment]
/close

So to summarize, we don't have any preferred ways on how admins block unwanted content. Open Policy Agent is definitely fine from a KubeVirt perspective. @cjreyn if that answer is not good enough for you, feel free to reopen the issue.
