### ISSUE TITLE
Release v0.32.0 dropped virtctl-linux-amd64 binary, determine why it disappeared

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#3984]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

In [kubevirt v0.32.0 release](https://github.com/kubevirt/kubevirt/releases/tag/v0.32.0) the virtctl amd binary was dropped, i.e. `virtctl-v0.32.0-linux-amd64` is missing.

When asking in the community meeting today about whether it would be required I was told that the two linux binaries (`amd64` vs `x86_64`) would be interchangeable. Although it was mentioned that they differ in size one of them should still be redundant.

So concluded path forward is:
Determine why build was present previously, and why it is now gone. Then decide what we might do (i.e. restore the amd and remove the x86)

**What you expected to happen**:

Expected `virtctl-v0.32.0-linux-amd64` to be present.

**How to reproduce it (as minimally and precisely as possible)**:

Look at [v0.32.0](https://github.com/kubevirt/kubevirt/releases/tag/v0.32.0), look at [v0.31.0](https://github.com/kubevirt/kubevirt/releases/tag/v0.31.0)

**Anything else we need to know?**:

There is an [open Github issue](https://github.com/kubevirt/kubevirt/issues/3943) about this state but it has not been closed (so it must have disappeared with another commit).

**Environment**:
- KubeVirt version (use `virtctl version`): v0.32.0
- Kubernetes version (use `kubectl version`): -
- VM or VMI specifications: -
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dhiller** [comment]
Interesting about this is that [goarch list](https://github.com/golang/go/blob/master/src/go/build/syslist.go) does **not** contain the value x86_64.

**Comment by dhiller** [comment]
The `ARCHITECTURE` value that is used is derived here: https://github.com/kubevirt/kubevirt/blob/3567e9feec920e194932727b708f0d175c6cd0c4/hack/common.sh#L19

On local machine this yields `x86_64`.

The change enabling this behaviour was introduced here: https://github.com/kubevirt/kubevirt/commit/220b6f8392cac5550dbe1ac9e97877d4dee888e9#diff-76ed4b9fac47b19f6b81d5c70501de86R51

Still unclear why the recent releases still included the amd binary.

Options:

1. change `s/-${ARCHITECTURE}/-amd64`, manually build the binary and upload it to the release
2. rename all the references to the virtctl amd binary to the x86_64 binary and keep it like this

**Comment by slintes** [comment]
This catched my eyes, because IIRC building and releasing multiple virtctl variants was one of my first PRs for KubeVirt :)
I would add option 3:

3. Revert relevant parts of the change mentioned above: the build (which builds release artifacts) should not depend on the machine the build is running on. If you need additional binaries (and images), either add them to the list with hardcoded arch (and filter the binaries to be released in the Travis config if needed), or add an additional build which builds for the machine it is running on and make sure it will not be released. But either way: don't touch the old linux/darwin/windows builds.

**Comment by rmohr** [comment]
> Still unclear why the recent releases still included the amd binary.

Must have to do something with travis I guess.



> 1. Revert relevant parts of the change mentioned above: the build (which builds release artifacts) should not depend on the machine the build is running on. If you need additional binaries (and images), either add them to the list with hardcoded arch (and filter the binaries to be released in the Travis config if needed), or add an additional build which builds for the machine it is running on and make sure it will not be released. But either way: don't touch the old linux/darwin/windows builds.

Yes, virtctl should not depend  on the architecture. It should just always be built and released for all supported architectures. Let's fix that. THanks @slintes .

**Comment by dhiller** [comment]
> This catched my eyes, because IIRC building and releasing multiple virtctl variants was one of my first PRs for KubeVirt :)
> I would add option 3:
> 
> 1. Revert relevant parts of the change mentioned above: the build (which builds release artifacts) should not depend on the machine the build is running on. If you need additional binaries (and images), either add them to the list with hardcoded arch (and filter the binaries to be released in the Travis config if needed), or add an additional build which builds for the machine it is running on and make sure it will not be released. But either way: don't touch the old linux/darwin/windows builds.

@slintes so you're saying we should build virtctl like before, I understand. But still the issue with the duplicate binary persists, and you are saying we should keep it that way (i.e. build **both** binaries for `x64_64` **and** `amd64` even though they are duplicates?

**Comment by rmohr** [comment]
Created #3993. I think we never intended to release x86_64. I would just go back to what  we intended: releasing -amd64.


FYI the amd64 binary is now present on the 0.32 release.

**Comment by rmohr** [comment]
Note that golang only list `amd64`: https://golang.org/doc/install/source#introduction in general.

**Comment by dhiller** [comment]
Great, thanks!
