### ISSUE TITLE
Design and implement QoS for disk and network devices

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#399]
libvirt has the ability to set certain limits on network and disk devices for iops and bandwidth.

The idea is to have a component which is monitoring the host and adjusting those limits dynamically at runtime according to a given policy, to avoid that the host is getting saturated on these aspects.

To support this, some values need to be reflected in the API - the upper and lower bounds of the iops and bandwith for each device. The boundaries are needed to tell the system in which bounds the VM's iops and bandwith parmeters can be tuned.

- [ ] How should the bounds be reflected in the VM API (need to find a home, as it's not part of domain/domxml)

**Comment by fabiand** [comment]
@xsgordon I'm pretty certain that Kubernetes is looking into providing this functionality for pods as well.
And that makes sense. After all the form factor looks irrelevenat for the answer abou if you want to do QoS or not.

In that sense I am suggesting to close this, and inherit Kubernetes features - or collaborate there.

**Comment by itamarh** [comment]
at the proxy level or a policy up to the CNI to implement?
i.e., what about layer 2 networks?

**Comment by fabiand** [comment]
service meshes like istio will have their own mechanism (I suppose).

then there is this CNI level functionality - which might be configured through a cluste rlevel object at some point I'd guess i.e. a part of a NetworkPolicy.

Layer 2 - Only if CNI is used. Also: That is what we need to solve on the DP side, which is currently still under heavey research and discussion and thus probably a bit premature to discuss how we get QoS there.

My main point is: Because it is at least to a small degree present in Kubernetes, I'm rather looking at consuming it from and growing it there, instead of explicitly providing it in KubeVirt.
