### ISSUE TITLE
[Flakey CI] [rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system] VM Live Migration with a live-migrate eviction strategy set with multiple VMIs with eviction policies set [test_id:3245]should not migrate more than two VMIs at the same time from a node

### ISSUE THREAD

**Issue by omeryahud** [kubevirt/kubevirt#3990]
/kind bug
/triage build-officer

**What happened**:
Flakefinder found this test to be flakey:
```
[rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system] VM Live Migration with a live-migrate eviction strategy set with multiple VMIs with eviction policies set [test_id:3245]should not migrate more than two VMIs at the same time from a node
```
It failed during this job:

- https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3947/pull-kubevirt-e2e-k8s-1.17/1293384254578757632

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
I see in https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3947/pull-kubevirt-e2e-k8s-1.17/1293384254578757632/artifacts/k8s-reporter/pods/1_kubevirt-test-default_virt-launcher-testvmignbrjbfwq6p5br7vzc5rbzw56lrpc47fjx2s2n29bd-compute.log:


```
{"component":"virt-launcher","level":"error","msg":"failed to get domain metadata","pos":"libvirt_helper.go:116","reason":"virError(Code=55, Domain=20, Message='Requested operation is not valid: transient domains do not have any persistent config')","timestamp":"2020-08-12T06:01:02.505562Z"}
```

and over and over

```
{"component":"virt-launcher","kind":"","level":"warning","msg":"failed to set time: QEMU agent unresponsive","name":"testvmignbrjbfwq6p5br7vzc5rbzw56lrpc47fjx2s2f5mqqmcndg6","namespace":"kubevirt-test-default","pos":"manager.go:549","reason":"virError(Code=86, Domain=10, Message='Guest agent is not responding: QEMU guest agent is not connected')","timestamp":"2020-08-12T06:01:47.479858Z","uid":"81cddc0f-0fa5-4dbd-a6ce-cc74a67002dd"}
```

@davidvossel could you have a look?

**Comment by davidvossel** [comment]
sounds like another reason to move the metadata out of the domain

**Comment by davidvossel** [comment]
The issue doesn't have to do with the qemu agent or a failure to get metadata, all of that is transient and/or mostly benign.

Here's the timeline.

- VMI starts on node1
- eviction controller migrates VMI
- migration fails
- time passes
- eviction controller tries to migrate VMI again
- migration fails with "migration job already executed"
- time passes
- eviction controller tries to migrate VMI again
- migration fails with "migration job already executed"

So essentially the first migration fails, and then something on the VMI isn't reset correctly to allow another migration to be attempted.

**Comment by davidvossel** [comment]
This issue goes pretty deep, but here's what I know... A VMI migration fails, and then subsequent attempts to migrate the same VMI continue to fail indefinitely afterwards

This sort of issue has been a sore spot for us for awhile and continues to cause issues.

What we need is a functional test like the disabled [1] that causes a vmi migration to fail, then we need to ensure that subsequent migration attempts after the failure have a shot at succeeding. Without a test that fully exercises this and acts as a reproducer, it's very difficult to track down the root cause.


1. https://github.com/kubevirt/kubevirt/pull/3557

**Comment by davidvossel** [comment]
@rmohr i have a theory... 

https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-handler/cmd-client/client.go#L226

We're using the activePods list to find the command client. When a migration fails, that pod is never removed from the ActivePods list, furthermore the pod can keep going for awhile and remain active i believe. I actually found 4 pods in the ActivePods list for the vmi in question. 

I think when a migration fails, we run a chance of talking to the wrong target pod when doing the client setup.  I have no idea if this is the cause of the issue we're encountering here. But it seems suspicious

**Comment by rmohr** [comment]
@davidvossel sounds like a high-impact issue. Would be great if you can investigate it further and resolve it.

**Comment by davidvossel** [comment]
i have a test that I think will reliably cause a migration to fail.  I was able to confirm that the target pod outlives (and is running) beyond the point where the migration fails. 

I think that's the problem that needs to be solved. We need to signal to virt-launcher to shutdown when the migration fails so that pod doesn't remain active.

**Comment by davidvossel** [comment]
> I think that's the problem that needs to be solved. We need to signal to virt-launcher to shutdown when the migration fails so that pod doesn't remain active.

I take that back... The migration target pod has an anti-affinity rule on it that prevents two pods from being active on the same node. So while the failed migration pod does stay around for awhile until it timesout, a new target pod will stay in the `pending` phase until the old target pod exits.

It's still unclear exactly what's happening in this test failure. 

To give us more confidence in how migration failures are handled, I have a functional test that exercises this that I've posted for review #4023

**Comment by davidvossel** [comment]
@rmohr My functional test might have uncovered something. [[1]]( https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4023/pull-kubevirt-e2e-k8s-1.16/1296190027184738304/artifacts/k8s-reporter/pods/1_kubevirt-test-default_virt-launcher-testvmihmj8dgdhbqrf7r2nj8tfz2xfnccfcpzm6qbwhlcrfp-compute.log)[ [2]](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4023/pull-kubevirt-e2e-k8s-1.16/1296190027184738304)

It looks like the migration flow isn't handling the container disk not being ready yet. or something along those lines. Maybe this is related to the removal of the readiness checks?

```
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:71","timestamp":"2020-08-20T00:16:15.417326Z"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to prepare migration target pod","name":"testvmihmj8dgdhbqrf7r2nj8tfz2xfnccfcpzm6qbwhttqqlfd6q2l","namespace":"kubevirt-test-default","pos":"server.go:142","reason":"no supported file disk found for volume with index 0","timestamp":"2020-08-20T00:16:15.845034Z","uid":"bb9f261e-dbb4-4f64-8dea-65266e3a4ffa"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to prepare migration target pod","name":"testvmihmj8dgdhbqrf7r2nj8tfz2xfnccfcpzm6qbwhttqqlfd6q2l","namespace":"kubevirt-test-default","pos":"server.go:142","reason":"no supported file disk found for volume with index 0","timestamp":"2020-08-20T00:16:15.847936Z","uid":"bb9f261e-dbb4-4f64-8dea-65266e3a4ffa"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to prepare migration target pod","name":"testvmihmj8dgdhbqrf7r2nj8tfz2xfnccfcpzm6qbwhttqqlfd6q2l","namespace":"kubevirt-test-default","pos":"server.go:142","reason":"no supported file disk found for volume with index 0","timestamp":"2020-08-20T00:16:15.852482Z","uid":"bb9f261e-dbb4-4f64-8dea-65266e3a4ffa"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to prepare migration target pod","name":"testvmihmj8dgdhbqrf7r2nj8tfz2xfnccfcpzm6qbwhttqqlfd6q2l","namespace":"kubevirt-test-default","pos":"server.go:142","reason":"no supported file disk found for volume with index 0","timestamp":"2020-08-20T00:16:15.875287Z","uid":"bb9f261e-dbb4-4f64-8dea-65266e3a4ffa"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to prepare migration target pod","name":"testvmihmj8dgdhbqrf7r2nj8tfz2xfnccfcpzm6qbwhttqqlfd6q2l","namespace":"kubevirt-test-default","pos":"server.go:142","reason":"no supported file disk found for volume with index 0","timestamp":"2020-08-20T00:16:15.918323Z","uid":"bb9f261e-dbb4-4f64-8dea-65266e3a4ffa"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to prepare migration target pod","name":"testvmihmj8dgdhbqrf7r2nj8tfz2xfnccfcpzm6qbwhttqqlfd6q2l","namespace":"kubevirt-test-default","pos":"server.go:142","reason":"no supported file disk found for volume with index 0","timestamp":"2020-08-20T00:16:16.014186Z","uid":"bb9f261e-dbb4-4f64-8dea-65266e3a4ffa"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to prepare migration target pod","name":"testvmihmj8dgdhbqrf7r2nj8tfz2xfnccfcpzm6qbwhttqqlfd6q2l","namespace":"kubevirt-test-default","pos":"server.go:142","reason":"no supported file disk found for volume with index 0","timestamp":"2020-08-20T00:16:16.177878Z","uid":"bb9f261e-dbb4-4f64-8dea-65266e3a4ffa"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to prepare migration target pod","name":"testvmihmj8dgdhbqrf7r2nj8tfz2xfnccfcpzm6qbwhttqqlfd6q2l","namespace":"kubevirt-test-default","pos":"server.go:142","reason":"no supported file disk found for volume with index 0","timestamp":"2020-08-20T00:16:16.501623Z","uid":"bb9f261e-dbb4-4f64-8dea-65266e3a4ffa"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to prepare migration target pod","name":"testvmihmj8dgdhbqrf7r2nj8tfz2xfnccfcpzm6qbwhttqqlfd6q2l","namespace":"kubevirt-test-default","pos":"server.go:142","reason":"no supported file disk found for volume with index 0","timestamp":"2020-08-20T00:16:17.145905Z","uid":"bb9f261e-dbb4-4f64-8dea-65266e3a4ffa"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to prepare migration target pod","name":"testvmihmj8dgdhbqrf7r2nj8tfz2xfnccfcpzm6qbwhttqqlfd6q2l","namespace":"kubevirt-test-default","pos":"server.go:142","reason":"no supported file disk found for volume with index 0","timestamp":"2020-08-20T00:16:18.430466Z","uid":"bb9f261e-dbb4-4f64-8dea-65266e3a4ffa"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to prepare migration target pod","name":"testvmihmj8dgdhbqrf7r2nj8tfz2xfnccfcpzm6qbwhttqqlfd6q2l","namespace":"kubevirt-test-default","pos":"server.go:142","reason":"no supported file disk found for volume with index 0","timestamp":"2020-08-20T00:16:21.003754Z","uid":"bb9f261e-dbb4-4f64-8dea-65266e3a4ffa"}
{"component":"virt-launcher","kind":"","level":"error","msg":"Failed to prepare migration target pod","name":"testvmihmj8dgdhbqrf7r2nj8tfz2xfnccfcpzm6qbwhttqqlfd6q2l","namespace":"kubevirt-test-default","pos":"server.go:142","reason":"no supported file disk found for volume with index 0","timestamp":"2020-08-20T00:16:26.128558Z","uid":"bb9f261e-dbb4-4f64-8dea-65266e3a4ffa"}


```



1. https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4023/pull-kubevirt-e2e-k8s-1.16/1296190027184738304/artifacts/k8s-reporter/pods/1_kubevirt-test-default_virt-launcher-testvmihmj8dgdhbqrf7r2nj8tfz2xfnccfcpzm6qbwhlcrfp-compute.log

2. https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4023/pull-kubevirt-e2e-k8s-1.16/1296190027184738304

**Comment by enp0s3** [comment]
Happened again: https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2020-08-24-024h.html

**Comment by ashleyschuett** [comment]
Failed again here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4022/pull-kubevirt-e2e-k8s-1.16/1298039088628109312

**Comment by dhiller** [comment]
Failed again here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4011/pull-kubevirt-e2e-k8s-1.16/1298418719243898880

**Comment by RamLavi** [comment]
Failed again here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4107/pull-kubevirt-e2e-k8s-1.16/1301699767302098945

**Comment by RamLavi** [comment]
@rmohr can you reopen this issue? it's seems that the flakiness is still there.
