### ISSUE TITLE
When switching commits, the old generated binaries are not removed

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#401]
After running `make` four times on different commits I see the following for e.g. `virt-api`:

```
find .
.
./virt-api.go
./virt-api-v0.0.1-alpha.3-463-gae1ff5a-linux-amd64
./virt-api-v0.0.1-alpha.3-461-g3a350b1-linux-amd64
./virt-api-v0.0.1-alpha.3-462-g3728d19-linux-amd64
./virt-api-v0.0.1-alpha.3-465-gb04e806-linux-amd64
./Dockerfile
./virt-api
```

I think we should either not generate full release binaries when we don't do a release, or we should clean up other binaries which are still there.

**Comment by fabiand** [comment]
I'll look at it.

**Comment by fabiand** [comment]
Pls take a look at the fix, it's removing old binaries.

**Comment by rmohr** [comment]
Works for me. Thanks.
