### ISSUE TITLE
some presubmit tests are failing due to: no space left on device

### ISSUE THREAD

**Issue by ksimon1** [kubevirt/kubevirt#4017]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/triage build-officer

**What happened**:
some presubmit tests are failing due to no space left on device. E.g.:
https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3972/pull-kubevirt-e2e-k8s-1.16/1296030638830260224/build-log.txt?Expires=1597835686&GoogleAccessId=prow-46%40kubevirt-240711.iam.gserviceaccount.com&Signature=THo0AEIga%2BxcVqoXManovCKRPpsMpT5%2BKfOjacYFaWYi1ArlDfrOV%2BbNJNJ%2BEwfH8MA8w0oQ0pp7d75mk8vOV85JClzpIY38xwVO9pBg%2FowfXBU%2B%2BEOdgMnvBlKA%2BHgWKPk5wD4XVozQu%2Fa9l3U76%2FG7sdrFVF%2BjQixFwKrnqkqaAHvk6elvnUXUR0pcopWYyq5NqKnNezN3LewvYA0EVeachHc3V641ix9ycwYVZoDyjshOCdagEeUwKfTf%2FdLYCiYkLnAcJ2WRbjj5Eh%2BqaEvQpRZvt6OdX4e9uQDMLUc69nVXxdbpOapBW6lqbr4j0sn96Zfk4Q%2BzcaUJUfcFtw%3D%3D

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3972/pull-kubevirt-e2e-k8s-1.16/1296030638830260224

/cc @rmohr

**Comment by rmohr** [comment]
Thanks, I again manually deleted the coredumps right now. Will ping the infra guys again.
