### ISSUE TITLE
[Flakey CI] kube-admission library Check objects recovery should be able to recover from mutatingWebhookConfiguration caBundle deletion

### ISSUE THREAD

**Issue by ksimon1** [kubevirt/kubevirt#4019]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/triage build-officer

**What happened**:
kube-admission library Check objects recovery should be able to recover from mutatingWebhookConfiguration caBundle deletion

```
/tmp/deploy.kubemacpool.jVbm/github.com/k8snetworkplumbingwg/kubemacpool/tests/certificates_test.go:23
Should successfully get pre test secret
Unexpected error:
    <*errors.StatusError | 0xc000461180>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "secrets \"kubemacpool-service\" not found",
            Reason: "NotFound",
            Details: {
                Name: "kubemacpool-service",
                Group: "",
                Kind: "secrets",
                UID: "",
                Causes: nil,
                RetryAfterSeconds: 0,
            },
            Code: 404,
        },
    }
    secrets "kubemacpool-service" not found
occurred
/tmp/deploy.kubemacpool.jVbm/github.com/k8snetworkplumbingwg/kubemacpool/vendor/github.com/onsi/gomega/internal/assertion/assertion.go:43
```
Failing job: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_cluster-network-addons-operator/509/pull-e2e-cluster-network-addons-operator-kubemacpool-functests/1296049335208775680
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by RamLavi** [comment]
This Issue belongs in [CNAO repo](https://github.com/kubevirt/cluster-network-addons-operator). 
Issue was fixed in this [PR](https://github.com/kubevirt/cluster-network-addons-operator/pull/521), bumping KMP to v0.20.0.
So we can close it now

**Comment by RamLavi** [comment]
FYI @phoracek @qinqon
