### ISSUE TITLE
VirtualMachineInstance started/Running but can't login

### ISSUE THREAD

**Issue by talcoh2x** [kubevirt/kubevirt#4038]
Hi, I upload new disk image (qcow2) 
virtual size: 300G (322122547200 bytes)
disk size: 9.6G

And I'm using the following VMI to run it. my problem is that I can't login  into the VMI or get any kind of messages for debug

![image](https://user-images.githubusercontent.com/34831587/90981478-eb495580-e569-11ea-8780-ae6212a0b64b.png)

![image](https://user-images.githubusercontent.com/34831587/90981484-f603ea80-e569-11ea-80b7-ac76c31e8b3d.png)

![image](https://user-images.githubusercontent.com/34831587/90981489-fdc38f00-e569-11ea-9ec5-673bc7d91b16.png)

![image](https://user-images.githubusercontent.com/34831587/90981498-0ae07e00-e56a-11ea-8863-2e0b8182ed01.png)

![image](https://user-images.githubusercontent.com/34831587/90981524-3ebba380-e56a-11ea-8151-916e95d05218.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by vladikr** [comment]
> @vladikr

Tal, did you try opening a console to the VMI? 
virtctl console [vmi_name] ?

**Comment by talcoh2x** [comment]
@vladikr  Yes, I did it, just stuck.

**Comment by talcoh2x** [comment]
Someone can help, please ?

**Comment by vladikr** [comment]
@talcoh2x Perhaps you didn't assign enough memory for the guest to boot?
Are you sure that 64M is enough for this guest OS? I know that Fedora, for example only boots properly with 512MiB
