### ISSUE TITLE
Limit cloud-init userdata size at api server

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#404]
The api-server needs to enforce a limit on how large we'll allow the cloud-init (and other configuration based data) to be **before** we allow that object to be stored into etcd.

This issue is about limiting the cloud-init payload size within the VM object.

**Comment by fabiand** [comment]
Should be easy to solve once #205 is solved

**Comment by fabiand** [comment]
@rmohr @davidvossel do you have a hint where this check could live and how an implementation could look?

**Comment by davidvossel** [comment]
The check is going to involve intercepting the VirtualMachine object Put/Post requests and validating the CloudInit's userdata field is less than 2k.

cmd/virt-api/virt-api.go is where the http REST endpoint routes are built. pkg/virt-api/rest/kubeproxy.go contains the function used to build the generic http routes for all our objects.

**Comment by fabiand** [comment]
@davidvossel I suppose this is also something to be covered by the webhook admission controler?

**Comment by davidvossel** [comment]
@fabiand yes this will be handled in the webhook.
