### ISSUE TITLE
Openshift CI test failures on Kubevirt nightly run

### ISSUE THREAD

**Issue by enp0s3** [kubevirt/kubevirt#4044]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug
/triage build-officer

**What happened**:
A lot of test failures seen on Openshift CI nightly run of Kubevirt tests. failures are of the same reason - virt-launcher fails to create tap device.
Link: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-master-e2e-periodic-azure-nested-virt/1297731023731167232 

**What you expected to happen**:
Tests to pass

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by maiqueb** [comment]
Proposed fix on #4054 .

Only updates the label of the clone device on the virt-handler namespace (not the node's).
