### ISSUE TITLE
Stuck on "master: Waiting for domain to get an IP address..."

### ISSUE THREAD

**Issue by rancheral** [kubevirt/kubevirt#406]
I'm following the getting started guide.  I'm using fedora25 but tried this on fedora 26 and ubuntu and hit the same problem.  I get to "vagrant up" but it gets stuck at the line

master: Waiting for domain to get an IP address...

Eventually, it retried too many times and times out.  I'm new to kubevirt and vagrant.  I've been googling but I'm not getting anywhere meaningful.

**Comment by fabiand** [comment]
Hm. I'm also on Fedora 25 and am not seeing this issue.

Could you please provide `rpm -qa | egrep "vagrant|libvirt|dnsmasq", @rancheral?

**Comment by rmohr** [comment]
@rancheral did you try another `vagrant destroy`? Also a libvirt restart with another `vagrant destroy` after the restart might help.

**Comment by fabiand** [comment]
Please reopen this issue if you are still experiencing a problem.
