### ISSUE TITLE
Automatically decide which disk I/O mode should be used

### ISSUE THREAD

**Issue by danielBelenky** [kubevirt/kubevirt#4077]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:
KubeVirt supports setting a disk I/O mode for disk devices. This configuration can have great impact on
disk performance but using the wrong configuration can cause negative impact on the performance.

Though `io=native` provides a better performance in many cases (with preallocated disks), it can block the VM
when writing to not fully allocated (sparse) disk. On the other hand, `io=threads` can have negative impact on performance
when we try to use more threads that actual CPU cores. Though advanced users should be able to configure this as they
need, we should have at least some sort of a heuristic to decide on what is the best configuration for each VMI.

A similar approach was taken by the OpenStack team (also includes more details about the problem itself):
https://specs.openstack.org/openstack/nova-specs/specs/mitaka/implemented/libvirt-aio-mode.html

**What you expected to happen**:
We should have a setting on disk devices, something like `io=auto`. When this setting it set, KubeVirt will try
to decide what is the best disk I/O mode for the given disk. This can be done by checking the type of the storage backend
and maybe the number of available cores on the machine on which the VMI will be scheduled on.

**Comment by nsharma1231** [comment]
Good afternoon, my group members and I are students at the University of Texas at Austin. For our Virtualization class, one of our assignments is to contribute to an open source repository, and we are interested in KubeVirt. Would we be able to work on this issue?

**Comment by stu-gott** [comment]
@nsharma1231 Contributions are always welcome. Is your group still interested in taking on this task?

**Comment by ezrasilvera** [comment]
@danielBelenky I'm not sure there is an agreed conclusion on the recommended mode. Do you have concrete data on when `threads` is faster then native?  I looked in the original OpenStack IRC chant and saw that on some cases `native`  was faster then `threads ` even for sparse disks. The only issue I could see is indeed a possible "block" when writing to sparsely allocated files (compared to pre-allocated). However I believe it also depends on several other factors ...
Are you sure it doesn't also depends on the io pattern (size of requests, sequential Vs random, etc..) ?   I also saw indication on dependency on the number of VMs running (impact is larger when you have several VMs running) 
If it does, it will be very hard to decide the "best"  mode for the VMI.
