### ISSUE TITLE
NetworkPolicy Doesnt have the expected effect on kubevirtci kind ipv6

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#4081]
/kind bug

**What happened**:
As part of the effort on
https://github.com/kubevirt/kubevirt/pull/4045
We saw that the NetworkPolicy tests that were skipped Upstream, are not working as expected on Kind ipv6 lane.
A possible approach to try is suggested 
https://github.com/kubevirt/kubevirt/pull/4045#issuecomment-683447157
In order to understand for sure its related to kind only as it seems.

**What you expected to happen**:
We should at least understand its connected to kind only, as it seems so far.
It does pass on both 1.17 single stack and 1.18 dual stack.

**How to reproduce it (as minimally and precisely as possible)**:
Just run on kind ipv6 provider this PR https://github.com/kubevirt/kubevirt/pull/4045 once its merged without the Skip of kind,
that will be add to it (`SkipNetworkPolicyRunningOnKindInfra`).

Since we might choose to drop kind lane soon (unless we choose otherwise in order to support kind as well),
and since there is no regression, but we just advanced, this wont need to block the PR.

/cc @EdDev 
/cc @qinqon

**Comment by RamLavi** [comment]
@oshoval can you fix the title typo `efffect` --> `effect`

**Comment by oshoval** [comment]
@RamLavi done thx
