### ISSUE TITLE
tests, Migration test "Should detect a failed migration" is flaky on kind ipv6

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#4086]
/kind bug

**What happened**:
As Petr raised
The test is really flaky on CI, causing a stall of merging PRs.
See for example
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3871/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1300594483074699264

**What you expected to happen**:
Test should either pass or be skipped.

**How to reproduce it (as minimally and precisely as possible)**:
Run it, it will flake.

**Anything else we need to know?**:
We are going to ditch kind once we adapt kubevirtci proper k8s providers to support dual stack.
For now we are skipping the test.

/cc @phoracek

**Comment by rmohr** [comment]
/assign @davidvossel 

I have also seen it fail on multiple no-yet-merged PRs.

**Comment by rhrazdil** [comment]
/triage build-officer

happened today
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4042/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1300726000866299905

**Comment by phoracek** [comment]
The test is now being skipped on IPv6 kind lane. It will be soon replaced by kubevirtci based one, so we can close this issue.
