### ISSUE TITLE
vm-cirros create failed when selinux is disabled

### ISSUE THREAD

**Issue by wangzh21** [kubevirt/kubevirt#4088]
/kind bug
> /kind enhancement

**What happened**:
If I set selinux to disabled,  kubevirt can not run vm.
Here is the output of "kubectl describe virtualmachineinstance.kubevirt.io/vm-cirros":

Events:
  Type     Reason            Age   From                        Message
  ----     ------            ----  ----                        -------
  Normal   SuccessfulCreate  34s   virtualmachine-controller   Created virtual machine pod virt-launcher-vm-cirros-m8zs9
  Warning  SyncFailed        32s   virt-handler, lk-compute-3  failed to configure vmi network: Critical network error: error creating tap device named tap0; error reading virt-launcher 54015 selinux label
  Warning  Stopped           32s   virt-handler, lk-compute-3  The VirtualMachineInstance crashed.
  Normal   SuccessfulDelete  32s   virtualmachine-controller   Deleted virtual machine pod virt-launcher-vm-cirros-m8zs9
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
When I change the /etc/selinux/config to permissive, it works well.  

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
Yes that is a bug. We don't require selinux. Thanks for reporting.
/assign @maiqueb
/assign @jean-edouard

**Comment by jean-edouard** [comment]
@wangzh21 please ensure your build includes https://github.com/kubevirt/kubevirt/pull/4054
If you still run into the issue with that, then please add some details about your environment so we can reproduce it.
The output of `ausearch -m avc` would also be helpful here.
Thank you!

**Comment by wangzh21** [comment]
> @wangzh21 please ensure your build includes #4054
> If you still run into the issue with that, then please add some details about your environment so we can reproduce it.
> The output of `ausearch -m avc` would also be helpful here.
> Thank you!

Yes, I'm sure it includes https://github.com/kubevirt/kubevirt/pull/4054,  I update my local branch everyday ;).
Here is the output of `ausearch -m avc` : 

1. lk-compute-3

[root@lk-compute-3 ~]# getenforce 
Disabled
[root@lk-compute-3 ~]# ausearch -m avc
<no matches>

2.lk-compute-2
[root@lk-compute-2 ~]# getenforce 
Permissive
[root@lk-compute-2 ~]# ausearch -m avc
[ausearch.log](https://github.com/kubevirt/kubevirt/files/5159723/ausearch.log)

Thanks a lot.

**Comment by jean-edouard** [comment]
All the SELinux denials in your logs are about critical system files being mislabeled, like:
```
/etc/ld.so.cache
/etc/passwd
/usr/bin/bash
/usr/lib64/ld-2.17.so
...
```
You could try running `restorecon -FRv /`, that command will output the list of previously mislabelled files and fix them.
But it's concerning that your system went into that state, there could be something wrong with it...

**Comment by wangzh21** [comment]
> All the SELinux denials in your logs are about critical system files being mislabeled, like:
> 
> ```
> /etc/ld.so.cache
> /etc/passwd
> /usr/bin/bash
> /usr/lib64/ld-2.17.so
> ...
> ```
> 
> You could try running `restorecon -FRv /`, that command will output the list of previously mislabelled files and fix them.
> But it's concerning that your system went into that state, there could be something wrong with it...

I try to run `restorecon -FRv /` on lk-compute-2, there are a lot of output as you said. But it is the node which I can create vm successfully. And the node lk-compute-3, which config selinux disabled, is no output with `ausearch -m avc` and `restorecon -FRv /`.

Also, I'd like to know that can you reproduce "create failed" in your env? 
Plz feel free to ping me if u need more information.

**Comment by jean-edouard** [comment]
Sorry @wangzh21, I initially misread the issue, and then got sidetracked.
I finally got around to looking at this today with @maiqueb and we've managed to reproduce the issue.
We're still investigating, but just looking at the error, the issue was likely introduced recently when we reworked the way network taps are created.
Thank you for submitting this issue, and sorry again for the delay.

**Comment by wangzh21** [comment]
Nothing, I also misread your reply. Thanks again.

**Comment by nkhare** [comment]
Is there any workaround for this issue? We are on Ubuntu and hitting this issue as well.

**Comment by jean-edouard** [comment]
> Is there any workaround for this issue? We are on Ubuntu and hitting this issue as well.

Yes! https://github.com/kubevirt/kubevirt/pull/4163
