### ISSUE TITLE
[Flaky CI] [rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system] VM Live Migration with a live-migrate eviction strategy set [ref_id:2293] with a VMI running with an eviction strategy set with node tainted during node drain [test_id:2222] should migrate a VMI when custom taint key is configured

### ISSUE THREAD

**Issue by rhrazdil** [kubevirt/kubevirt#4090]
/triage build-officer

**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4067/pull-kubevirt-e2e-k8s-1.18/1300469284215984128

**Comment by shwetaap** [comment]
Same failure seen again 
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4236/pull-kubevirt-e2e-k8s-1.18/1309183957866123264
