### ISSUE TITLE
VM is killed every 10 seconds and created immediately

### ISSUE THREAD

**Issue by lixiaobing1** [kubevirt/kubevirt#4094]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
VM is killed every 10 seconds, and created immediately.

virt-controller start Dispatching delete event:

{"component":"virt-controller","level":"info","msg":"reenqueuing VirtualMachineInstance default/testvm","pos":"vmi.go:201","reason":"Operation cannot be fulfilled on virtualmachineinstances.kubevirt.io \"testvm\": the object has been modified; please apply your changes to the latest version and try again","service":"http","timestamp":"2020-09-01T09:22:54.244704Z"}
{"component":"virt-controller","kind":"","level":"info","msg":"Dispatching delete event","name":"testvm","namespace":"default","pos":"vm.go:694","service":"http","timestamp":"2020-09-01T09:23:02.150124Z","uid":"71f94ddc-50c7-4480-aad2-9d42a41cae93"}

{"component":"virt-handler","level":"info","msg":"Processing event default/testvm","pos":"vm.go:1068","timestamp":"2020-09-02T02:13:46.311765Z"}
{"component":"virt-handler","level":"info","msg":"VMI does not exist","pos":"vm.go:1072","timestamp":"2020-09-02T02:13:46.311826Z"}
{"component":"virt-handler","level":"info","msg":"Domain does not exist","pos":"vm.go:1077","timestamp":"2020-09-02T02:13:46.311887Z"}
{"component":"virt-handler","kind":"VirtualMachineInstance","level":"info","msg":"Performing final local cleanup for vmi with uid ","name":"testvm","namespace":"default","pos":"vm.go:1321","timestamp":"2020-09-02T02:13:46.311976Z","uid":""}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Removing domain from cache during final cleanup","name":"testvm","namespace":"default","pos":"vm.go:1351","timestamp":"2020-09-02T02:13:46.312034Z","uid":""}

**What you expected to happen**:
VM is running normally.

**How to reproduce it (as minimally and precisely as possible)**:
no operation.

**Anything else we need to know?**:
no

**Environment**:
- KubeVirt version (use `virtctl version`):
Client Version: version.Info{GitVersion:"v0.30.5", GitCommit:"53b764825eb80321b18eb39a5767c25a77ea470b", GitTreeState:"clean", BuildDate:"2020-07-17T01:17:41Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"{gitVersion}", GitCommit:"{gitCommit}", GitTreeState:"{gitTreeState}", BuildDate:"{buildDate}", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"archive", BuildDate:"2020-08-11T13:11:52Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.9", GitCommit:"59603c6e503c87169aea6106f57b9f242f64df89", GitTreeState:"archive", BuildDate:"2020-08-11T13:08:33Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications:
apiVersion: v1
kind: Pod
metadata:
  annotations:
    k8s.v1.cni.cncf.io/network-status: |-
      [{
          "name": "cbr0",
          "interface": "eth0",
          "ips": [
              "192.169.0.118",
              "1000::ada"
          ],
          "mac": "12:11:9e:82:09:b7",
          "default": true,
          "dns": {}
      }]
    k8s.v1.cni.cncf.io/networks-status: |-
      [{
          "name": "cbr0",
          "interface": "eth0",
          "ips": [
              "192.169.0.118",
              "1000::ada"
          ],
          "mac": "12:11:9e:82:09:b7",
          "default": true,
          "dns": {}
      }]
    kubevirt.io/domain: testvm
    traffic.sidecar.istio.io/kubevirtInterfaces: k6t-eth0
  creationTimestamp: "2020-08-31T08:06:46Z"
  deletionGracePeriodSeconds: 60
  deletionTimestamp: "2020-08-31T08:07:55Z"
  generateName: virt-launcher-testvm-
  labels:
    kubevirt.io: virt-launcher
    kubevirt.io/created-by: 0bf2dd1b-643a-440a-b665-3510914fc598
    kubevirt.io/domain: testvm
    kubevirt.io/size: small
  name: virt-launcher-testvm-rvt68
  namespace: default
  ownerReferences:
  - apiVersion: kubevirt.io/v1alpha3
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachineInstance
    name: testvm
    uid: 0bf2dd1b-643a-440a-b665-3510914fc598
  resourceVersion: "972547"
  selfLink: /api/v1/namespaces/default/pods/virt-launcher-testvm-rvt68
  uid: 619a8efe-156b-45a5-8620-47f12e0f5aea
spec:
  automountServiceAccountToken: false
  containers:
  - command:
    - /usr/bin/virt-launcher
    - --qemu-timeout
    - 5m
    - --name
    - testvm
    - --uid
    - 0bf2dd1b-643a-440a-b665-3510914fc598
    - --namespace
    - default
    - --kubevirt-share-dir
    - /var/run/kubevirt
    - --ephemeral-disk-dir
    - /var/run/kubevirt-ephemeral-disks
    - --container-disk-dir
    - /var/run/kubevirt/container-disks
    - --readiness-file
    - /var/run/kubevirt-infra/healthy
    - --grace-period-seconds
    - "45"
    - --hook-sidecars
    - "0"
    - --less-pvc-space-toleration
    - "10"
    - --ovmf-path
    - /usr/share/OVMF
    image: kubevirt/virt-launcher:latest
    imagePullPolicy: IfNotPresent
    name: compute
    readinessProbe:
      exec:
        command:
        - cat
        - /var/run/kubevirt-infra/healthy
      failureThreshold: 5
      initialDelaySeconds: 4
      periodSeconds: 1
      successThreshold: 1
      timeoutSeconds: 5
    resources:
      limits:
        devices.kubevirt.io/kvm: "1"
        devices.kubevirt.io/tun: "1"
        devices.kubevirt.io/vhost-net: "1"
      requests:
        cpu: 100m
        devices.kubevirt.io/kvm: "1"
        devices.kubevirt.io/tun: "1"
        devices.kubevirt.io/vhost-net: "1"
        memory: "225679432"
    securityContext:
      capabilities:
        add:
        - NET_ADMIN
        - NET_RAW
        - SYS_NICE
      privileged: false
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/kubevirt-ephemeral-disks
      name: ephemeral-disks
    - mountPath: /var/run/kubevirt/container-disks
      mountPropagation: HostToContainer
      name: container-disks
    - mountPath: /var/run/libvirt
      name: libvirt-runtime
    - mountPath: /var/run/kubevirt/sockets
      name: sockets
    - mountPath: /var/run/kubevirt-infra
      name: infra-ready-mount
  - args:
    - --copy-path
    - /var/run/kubevirt-ephemeral-disks/container-disk-data/0bf2dd1b-643a-440a-b665-3510914fc598/disk_0
    command:
    - /usr/bin/container-disk
    image: swr:6666/kubevirt/cirros-registry-disk-demo
    imagePullPolicy: IfNotPresent
    name: volumerootfs
    readinessProbe:
      exec:
        command:
        - /usr/bin/container-disk
        - --health-check
      failureThreshold: 5
      initialDelaySeconds: 1
      periodSeconds: 1
      successThreshold: 1
      timeoutSeconds: 1
    resources:
      limits:
        cpu: 100m
        memory: 40M
      requests:
        cpu: 10m
        memory: 1M
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/kubevirt-ephemeral-disks/container-disk-data/0bf2dd1b-643a-440a-b665-3510914fc598
      name: container-disks
    - mountPath: /usr/bin
      name: virt-bin-share-dir
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  hostname: testvm
  initContainers:
  - command:
    - /usr/bin/cp
    - /usr/bin/container-disk
    - /init/usr/bin/container-disk
    image: kubevirt/virt-launcher:latest
    imagePullPolicy: IfNotPresent
    name: container-disk-binary
    resources:
      limits:
        cpu: 100m
        memory: 40M
      requests:
        cpu: 10m
        memory: 1M
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /init/usr/bin
      name: virt-bin-share-dir
  nodeName: 193.101.3.14
  nodeSelector:
    kubevirt.io/schedulable: "true"
  priority: 0
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    fsGroup: 107
    runAsUser: 0
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 60
  tolerations:
  - effect: NoExecute
    key: node.kubernetes.io/not-ready
    operator: Exists
    tolerationSeconds: 300
  - effect: NoExecute
    key: node.kubernetes.io/unreachable
    operator: Exists
    tolerationSeconds: 300
  volumes:
  - emptyDir: {}
    name: sockets
  - emptyDir: {}
    name: infra-ready-mount
  - emptyDir: {}
    name: virt-bin-share-dir
  - emptyDir: {}
    name: libvirt-runtime
  - emptyDir: {}
    name: ephemeral-disks
  - emptyDir: {}
    name: container-disks
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2020-08-31T08:06:49Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2020-08-31T08:06:55Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2020-08-31T08:06:55Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2020-08-31T08:06:46Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://93ed025236079e3ff00c2f6c5c35fa7e11f3e1deeacf6366e64b3d50c4e4fa0f
    image: kubevirt/virt-launcher:latest
    imageID: docker://sha256:c3ab95e4b66314fe8014c63490b90660344509c1fed78b754b0934a32985b2c9
    lastState: {}
    name: compute
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-08-31T08:06:50Z"
  - containerID: docker://f51c0a1ce39a70205e9347bc60a60f2e7885e2d615c1f90dd6123747bd2c6346
    image: kubevirt/cirros-registry-disk-demo:latest
    imageID: docker-pullable://swr:6666/kubevirt/cirros-registry-disk-demo@sha256:657bfaaea4720e494058da55b35b302065d384576d49fa17be32d10e8ddfe2e7
    lastState: {}
    name: volumerootfs
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2020-08-31T08:06:50Z"
  hostIP: 193.101.3.14
  initContainerStatuses:
  - containerID: docker://5b18bb72f35a6424b16937457903fa648ad0d931c253171eb4f8faff35ed821c
    image: kubevirt/virt-launcher:latest
    imageID: docker://sha256:c3ab95e4b66314fe8014c63490b90660344509c1fed78b754b0934a32985b2c9
    lastState: {}
    name: container-disk-binary
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://5b18bb72f35a6424b16937457903fa648ad0d931c253171eb4f8faff35ed821c
        exitCode: 0
        finishedAt: "2020-08-31T08:06:48Z"
        reason: Completed
        startedAt: "2020-08-31T08:06:48Z"
  phase: Running
  podIP: 192.169.0.118
  podIPs:
  - ip: 192.169.0.118
  - ip: 1000::ada
  qosClass: Burstable
  startTime: "2020-08-31T08:06:46Z"

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
Red Hat 4.8.5-36
- Kernel (e.g. `uname -a`):
Linux version 3.10.0-693.21.1.el7.x86_64 
- Install tools:
- Others:

**Comment by lixiaobing1** [comment]
vm testvm resource version changes immediately:

kubevirt describe vm testvm
Resource Version:    2527242

Resource Version:    2527475

**Comment by davidvossel** [comment]
It looks like the VM is failing to launch, and then being immediately rescheduled. This could be caused by a number of issues.

I'd recommend setting the VM's `vm.spec.runStrategy` to `manual`, then using virtctl to start the VM. This will prevent the VM controller from automatically restarting the VMI right as it fails.

From there, observe why the VMI is failing

Some clues might be visible in this output `kubectl describe vmi <vmi name>`

**Comment by lixiaobing1** [comment]
@davidvossel there is not runStrategy in vm.yaml, should I add it explicitly?

**Comment by davidvossel** [comment]
> @davidvossel there is not runStrategy in vm.yaml, should I add it explicitly?

yes, this `runStrategy: manual` value would be a replacement for `running: true|false`.

**Comment by davidvossel** [comment]
I think there's definitely some usability improvements we can make here.

VMs should fast loop, recreating VMIs constantly when failures occur. There should be a backoff period, and we should provide better tools for determining what is occuring.

**Comment by ThreeFx** [comment]
I am observing the same issues on microk8s and kubevirt v0.33.0. Manual running seems to indicate a misplaced socket: the virt-launcher pod is complaining about not finding the libvirt-sock in /var/run/libvirt/ but an `exec` into the container shows that it is only found under `/run/libvirt`.

**Comment by davidvossel** [comment]
If you can find the failed pod, this should give us some hints as to why it failed.

```kubectl logs -n <namespace> -c compute <pod> ```

**Comment by lixiaobing1** [comment]
kubectl logs -c compute virt-launcher-testvm-ds8ww
Error from server (BadRequest): container "compute" in pod "virt-launcher-testvm-ds8ww" is waiting to start: PodInitializing

**Comment by majst01** [comment]
same here, seems to be related to: https://github.com/kubevirt/kubevirt/issues/1205 because i also see:

```

virt-handler-qwzhd virt-handler {"component":"virt-handler","level":"error","msg":"failed to create tap device named tap0","pos":"podinterface.go:734","reason":"error creating tap device named tap0; error reading virt-launcher 141112 selinux label","timestamp":"2020-09-26T09:59:21.192848Z"}
virt-handler-qwzhd virt-handler {"component":"virt-handler","level":"error","msg":"failed to prepare pod networking","pos":"podinterface.go:201","reason":"error creating tap device named tap0; error reading virt-launcher 141112 selinux label","timestamp":"2020-09-26T09:59:21.192912Z"}
virt-handler-qwzhd virt-handler {"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"testvm","namespace":"default","pos":"vm.go:1328","reason":"failed to configure vmi network: Critical network error: error creating tap device named tap0; error reading virt-launcher 141112 selinux label","timestamp":"2020-09-26T09:59:21.193113Z","uid":"fd641627-93d4-4e2d-95d6-f0140f03267d"}
virt-handler-qwzhd virt-handler {"component":"virt-handler","level":"error","msg":"virt-launcher crashed due to a network error. Updating VMI testvm status to Failed","pos":"vm.go:841","timestamp":"2020-09-26T09:59:21.193465Z"}

```

**Comment by wasd120d** [comment]
Got the same issue when doing the official "First steps with KubeVirt";
Got failed for vmis and using kubectl describe vmis got following message:
****
```
Normal   SuccessfulCreate  19s   virtualmachine-controller   Created virtual machine pod virt-launcher-testvm-pl8wc
  Warning  SyncFailed        15s   virt-handler, controlplane  failed to configure vmi network: Critical network error: error creating tap device named tap0; error reading virt-launcher 16390 selinux label
  Warning  Stopped           15s   virt-handler, controlplane  The VirtualMachineInstance crashed.
  Normal   SuccessfulDelete  15s   virtualmachine-controller   Deleted virtual machine pod virt-launcher-testvm-pl8wc
```
Any idea how to fix this?

**Comment by majst01** [comment]
Have to add that using the latest images which should have this https://github.com/kubevirt/kubevirt/pull/4163 fix applied but still does not work.

**Comment by davidvossel** [comment]
/cc @maiqueb @phoracek 

any idea what might be causing this? Seems related to the network changes recently around tap devices.

**Comment by maiqueb** [comment]
> /cc @maiqueb @phoracek
> 
> any idea what might be causing this? Seems related to the network changes recently around tap devices.

Having `virt-handler` logs to confirm it would be helpful, but we've recently found (in openshift) something similar: since we don't compile with bazel, we were compiling kubevirt without the `selinux` tag, which in turn caused virt-handler to not be able to read the virt-launcher label or effectively change context.

@majst01 / @wasd120d https://github.com/kubevirt/kubevirt/pull/4248 should fix it if you do not use bazel.

**Comment by majst01** [comment]
@maiqueb can you confirm than running all pods with :latest tag uses this ?

**Comment by phoracek** [comment]
@majst01 now it should be available in the latest release for sure. Would you check whether it was fixed for you?

**Comment by todaygood** [comment]
I met the same issue. In my os , selinux is disabled , kubevirt version is 0.33.0

**Comment by majst01** [comment]
Hi @phoracek 
with v0.34.0 creating a vm works ! 
This is on bare-metal, with ubuntu-20.04 host os and k8s 1.18.9
Thanks a lot
