### ISSUE TITLE
[Flaky CI] Configurations VirtualMachineInstance definition with Clock and timezone guest should see timezone 

### ISSUE THREAD

**Issue by qinqon** [kubevirt/kubevirt#4096]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement
/triage build-officer

**What happened**:
The following test is failing at not related PRs.
`Configurations VirtualMachineInstance definition with Clock and timezone guest should see timezone`

prow logs:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4087/pull-kubevirt-e2e-k8s-1.18/1300870049690554368

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by oshoval** [comment]
Again
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3612/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1302605484561272832
