### ISSUE TITLE
cloud-init should support network server as data source

### ISSUE THREAD

**Issue by yichengliu58** [kubevirt/kubevirt#4097]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind enhancement

For now, kubevirt only supports NoCloud and CloudDrive as cloud-init data sources, these methods force users to mount an additional small disk into VM.

In production environment clients don't like this additional disk. Since cloud-init supports a server on the network as its data source, we should implement this feature in kubevirt for users to choose.

**Comment by davidvossel** [comment]
> In production environment clients don't like this additional disk. 

interesting, what kinds of concerns do people have with the cloud-init disks?

**Comment by yichengliu58** [comment]
@davidvossel Hi, sorry for late reply. For a client using cloud virtual machines, they usually use some startup script to format, make partition and initiate all the data disks (usually from vdb). If there is a read-only cloud-init disk (like vdb), this might cause startup script fail to run, which clients are not willing to accept.

Common cloud providers like AWS, Azure, they provide virtual machines without this disk, clients have been used to this design, and it's very hard to persuade them to change their way of use.

From kubevirt side, I think as a fundamental paas platform, it should provide as rich as possible features to users. Cloud-init meta-server is a very common way of use, I think there must be lots of other people needing this.
