### ISSUE TITLE
Publish a getting started guide for users

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#410]
We have a getting started guide which is oriented towards developers, but we should also provide a document which is focused on user flows.
Effectively describing how to use KubeVirt, how to managed VMs.

- [x] Overview
- [x] Deployment (https://github.com/kubevirt/user-guide/pull/12)
- [x] Creating a VM
- [x] Starting & Stoping a VM
- [x] Connecting to a VM
- [x] Migrating a VM
- [x] VM ReplicationController @rmohr 
- [x] Cloud Init @davidvossel (https://github.com/kubevirt/user-guide/pull/10)

**Comment by fabiand** [comment]
I've started to work on a small document here: https://fabiand.gitbooks.io/kubevirt-user-guide/

Currently it's hosted on fabiand/kubevirt-user-guide - but if it has enough content and we like the format, we can move it to the kubevirt org.

**Comment by fabiand** [comment]
How to use gitbook is described here https://toolchain.gitbook.com/

**Comment by rmohr** [comment]
Very nice :+1:

**Comment by fabiand** [comment]
Now hosted at https://github.com/kubevirt/user-guide
Accessible - also - through http://docs.kubevirt.io

I'll close the issue once all tasks are completed.

**Comment by rmohr** [comment]
@fabiand do you have a hing regarding to what we want to see in the Introduction setting to close the last gap mentioned on this issue?

**Comment by fabiand** [comment]
With the notes after the v0.2.0 release the installation/deployment is also covered sufficiently for me.

Thus to me it's good to close this ticket.
