### ISSUE TITLE
tests: extract assertions from helper functions.

### ISSUE THREAD

**Issue by alonSadan** [kubevirt/kubevirt#4101]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind enhancement

**What happened**:
Helper functions for tests make assertions on errors, instead of returning the error. 
**What you expected to happen**:
Assertions on errors should happen only in the test it self. Helpers should, if needed, to create the error and return it. 
One reason it is necessary , for example, is that it makes harder to write negative tests.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
An example  of an helper function that creates an error and assert on that: 
https://github.com/kubevirt/kubevirt/blob/master/tests/vmi_multus_test.go#L1025

**Comment by alonSadan** [comment]
@EdDev  deserves the credit for that one : 
https://github.com/kubevirt/kubevirt/pull/3479#discussion_r468484017

**Comment by oshoval** [comment]
I dont see a problem imo for helper to have assert, i think an helper can check lets say 3 things which are connected and can be encapsulated to one function, and then what it should do if it cant assert?
the assert of Expect is very readable imo.

**Comment by nsharma1231** [comment]
Good evening, I'm a student at the University of Texas at Austin. I'm taking a class in Virtualization and one of our projects is to contribute to an open-source repository. My group and I were interested and KubeVirt and wanted to contribute. Is this an issue that we could potentially work on?

**Comment by phoracek** [comment]
@nsharma1231 sorry for missing your comment. Are you still interested in contributing? If so, I'd be glad to help you arrange some tasks.

**Comment by jmguzik** [comment]
@phoracek I would be interested. I would be more than happy to do entry-level tasks (fixing, refactoring, cleanups, etc). Please let me know if you still have time to arrange something.

**Comment by phoracek** [comment]
@jmguzik awesome! Would you try to identify some places where a helper asserts the error? If you would not be sure about what you found, do let me know.

/assign @jmguzik

**Comment by EdDev** [comment]
Examples:
https://github.com/kubevirt/kubevirt/blob/a750459f172dfccb0200d74e842781b076572eaf/tests/libnet/skips.go#L12
https://github.com/kubevirt/kubevirt/blob/a750459f172dfccb0200d74e842781b076572eaf/tests/vmi_multus_test.go#L1127
https://github.com/kubevirt/kubevirt/blob/a750459f172dfccb0200d74e842781b076572eaf/tests/vmi_multus_test.go#L1226
https://github.com/kubevirt/kubevirt/blob/a750459f172dfccb0200d74e842781b076572eaf/tests/vmi_multus_test.go#L1323

etc...

**Comment by EdDev** [comment]
@jmguzik I added some examples.

Please follow the [To start developing KubeVirt](https://github.com/kubevirt/kubevirt#to-start-developing-kubevirt) section and setup your env.

**Comment by jmguzik** [comment]
@phoracek I pushed the first PR just to see if this is what you pursue. Please note I come from the C++ world and may not be familiar with all go concepts. Feel free to point what should be changed freely. 
@EdDev I have to be honest, after following twice the KubeVirt developer's section I still have an issue with some tests. Unfortunately, also with tests in regards to this commit (vmi_multus_test). Example:

      Unexpected error:
          <*errors.StatusError | 0xc00376e140>: {                                                                                                                                                                                                                              
              ErrStatus: {                                                                                                                                                                                                                                                     
                  TypeMeta: {Kind: "", APIVersion: ""},                                                                                                                                                                                                                        
                  ListMeta: {                                                                                                                                                                                                                                                  
                      SelfLink: "",                                                                                                                                                                                                                                            
                      ResourceVersion: "",                                                                                                                                                                                                                                     
                      Continue: "",                                                                                                                                                                                                                                            
                      RemainingItemCount: nil,                                                                                                                                                                                                                                 
                  },                                                                                                                                                                                                                                                           
                  Status: "Failure",                                                                                                                                                                                                                                           
                  Message: "the server could not find the requested resource",                                                                                                                                                                                                 
                  Reason: "NotFound",                                                                                                                                                                                                                                          
                  Details: {                                                                                                                                                                                                                                                   
                      Name: "",                                                                                                                                                                                                                                                
                      Group: "",                                                                                                                                                                                                                                               
                      Kind: "",                                                                                                                                                                                                                                                
                      UID: "",                                                                                                                                                                                                                                                 
                      Causes: [                                                                                                                                                                                                                                                
                          {                                                                                                                                                                                                                                                    
                              Type: "UnexpectedServerResponse",                                                                                                                                                                                                                
                              Message: "404 page not found",                                                                                                                                                                                                                   
                              Field: "",                                                                                                                                                                                                                                       
                          },                                                                                                                                                                                                                                                   
                      ],                                                                                                                                                                                                                                                       
                      RetryAfterSeconds: 0,                                                                                                                                                                                                                                    
                  },                                                                                                                                                                                                                                                           
                  Code: 404,                                                                                                                                                                                                                                                   
              },                                                                                                                                                                                                                                                               
          }                                                                                                                                                                                                                                                                    
          the server could not find the requested resource                                                                                                                                                                                                                     
      occurred                                                                                                                                                                                                                                                                 

      tests/vmi_multus_test.go:125
------------------------------

Do you have any clue what went wrong here?

**Comment by phoracek** [comment]
@jmguzik your local cluster is missing Multus and other components for advanced networking. To deploy those, do:

```
make cluster-down
export KUBEVIRT_WITH_CNAO=true  # <--- important
make cluster-up
make cluster-sync
```

**Comment by jmguzik** [comment]
@phoracek many thanks, everything works
