### ISSUE TITLE
[Flaky CI] [test_id:1635] VMIlifecycle Creating a VirtualMachineInstance with node tainted the vmi with tolerations should be scheduled

### ISSUE THREAD

**Issue by qinqon** [kubevirt/kubevirt#4103]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-officer
> /kind enhancement

**What happened**:

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4058/pull-kubevirt-e2e-k8s-cnao-1.17/1301099814515118082
```
[rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]VMIlifecycle [rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]Creating a VirtualMachineInstance with node tainted [test_id:1635]the vmi with tolerations should be scheduled expand_less | 1m14s
-- | --
/root/go/src/kubevirt.io/kubevirt/tests/vmi_lifecycle_test.go:696 There should be some compute node Expected     <[]v1.Node \| len:0, cap:0>: [] not to be empty /root/go/src/kubevirt.io/kubevirt/tests/vmi_lifecycle_test.go:698
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by oshoval** [comment]
Again 7 Sept 2020
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3612/pull-kubevirt-e2e-k8s-1.17/1301734243675672577

**Comment by oshoval** [comment]
Time is the best flake solver

**Comment by orenc1** [comment]
Again on Dec.29th:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4714/pull-kubevirt-e2e-k8s-1.17/1343585461200752640

**Comment by fgimenez** [comment]
5 more occurrences in the last 10 days, usually paired with a failure in test_id:1534:
https://prow.k8s.io/view/gcs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.17/1345380679688392704
https://prow.k8s.io/view/gcs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.17/1346076642933477376
https://prow.k8s.io/view/gcs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.17/1348029516081008640
https://prow.k8s.io/view/gcs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.18/1348667971521744897
https://prow.k8s.io/view/gcs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.19/1347849084630732800
