### ISSUE TITLE
tests:  config VMs via cloud-init, not console

### ISSUE THREAD

**Issue by alonSadan** [kubevirt/kubevirt#4104]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind enhancement

**What happened**:
Vms are configured through the console.
**What you expected to happen**:
We should have all the desired configurations in advance,using cloud-init, and not rely on console (and Expecters).
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
An example for a configuration of a vm interface through  the console (and the Expecters validation): 
https://github.com/kubevirt/kubevirt/blob/master/tests/vmi_multus_test.go#L882

**Comment by alonSadan** [comment]
/ credit to @EdDev on this.
https://github.com/kubevirt/kubevirt/pull/3479#discussion_r465514771

**Comment by estherlyoon** [comment]
Hi, myself and my group members are interested in taking on this as our first contribution to this repo; we're university students working on open-source projects for a course we're taking on Virtualization. If this would be a suitable issue for us to tackle, could someone provide more information on what's needed to be done for it?

**Comment by phoracek** [comment]
@qinqon is this now implemented?

**Comment by phoracek** [comment]
@estherlyoon I'm sorry that your messages was not noticed. Are you still looking for a project to contribute to? If so, please feel free to contact me and I'd help you arrange a task in this project.
