### ISSUE TITLE
test: use safe expecter-batcher

### ISSUE THREAD

**Issue by alonSadan** [kubevirt/kubevirt#4105]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

 /kind bug
> /kind enhancement

**What happened**:
Expecters are being used widely in kubevirt tests to run batch scripts.  
**What you expected to happen**:
that only the safe [expecter-batcher](https://github.com/kubevirt/kubevirt/pull/3882) will be used, which is a lot more reliable, less prone to cover for bugs.
**How to reproduce it (as minimally and precisely as possible)**:
**Anything else we need to know?**:
further deatils and issues are described in the expecter-batcher link.

**Comment by alonSadan** [comment]
started some work on that: 
https://github.com/kubevirt/kubevirt/pull/4010

**Comment by MichaelWasher** [comment]
Has this been completed by https://github.com/kubevirt/kubevirt/pull/4010/files ?

I ran `rg ExpectBatch | grep -v WithValidatedSend | less` but didn't turn up much except from a couple instances in `expecter.go` and `login.go`.

Should I unassign?

**Comment by alonSadan** [comment]
Hey @MichaelWasher .I opened a PR open on that : https://github.com/kubevirt/kubevirt/pull/4010
Sorry for not updating. Nothing much for you to do here (though I would love some reviews:) )
Thanks.

**Comment by MichaelWasher** [comment]
You're alright!
Thanks for doing the work! :)

**Comment by phoracek** [comment]
@alonSadan can we close this now?

**Comment by alonSadan** [comment]
> @alonSadan can we close this now?

yes. safe expecter is applied wherever it can
