### ISSUE TITLE
[Flaky CI] [rfe_id:694][crit:medium][vendor:cnv-qe@redhat.com][level:component]Networking VirtualMachineInstance with masquerade binding mechanism when performing migration preserves connectivity

### ISSUE THREAD

**Issue by phoracek** [kubevirt/kubevirt#4114]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

The test failed in Kind IPv6 lane.

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4093/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1301462205975236609

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by RamLavi** [comment]
failing also on k8s lane: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4107/pull-kubevirt-e2e-k8s-1.16/1301485102974373891

**Comment by oshoval** [comment]
Again
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3612/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1302476509641969665
