### ISSUE TITLE
Single libvirtd instance support

### ISSUE THREAD

**Issue by 3d0c** [kubevirt/kubevirt#4117]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind enhancement

**What happened**:
Normally there is a per container instance of `libvirtd`.

**What you expected to happen**:
Wouldn't it better to have a single instance of `libvirtd` on host? Is there any limitations? Why current implementation runs per-container instance?

**Comment by davidvossel** [comment]
> Wouldn't it better to have a single instance of libvirtd on host? Is there any limitations? Why current implementation runs per-container instance?

The idea is we want VM guests scheduled and self contained as Pods. libvirtd simply exists as a shim for starting/stopping the qemu process within our pod.

having a centralized libvirtd per host means a 1:many relationship of libvirtd to VM guest pods. That centralized libvirtd would have to exist outside of the Pod environments on the host level, and then coordinate launching qemu processes within these containerized environments. Practically, we found that to be much more fragile than putting libvirtd within the pod using a 1:1 relationship of libvirtd to VM guests.

**Comment by 3d0c** [comment]
Thanks
