### ISSUE TITLE
Errors on boot VMI using Cirros container disk image 

### ISSUE THREAD

**Issue by ormergi** [kubevirt/kubevirt#4119]
/kind bug

There is a bug with Cirros container-disk causing a 5 minutes delay on boot.
The workaround for it is using cloud-init with any arbitrary userData just to trigger cloud-init make the VMI boot normally.
Cirros container-disk is extensively used all around tests suite, enforces using that workaround making the code look awkward.

Creating cirros VMI and console to it during boot shows that there is a process that tries to connect to `http://169.254.169.254/2009-04-04/instance-id` before the system is ready:
https://paste.centos.org/view/3bc17091 (line 414)
That address is not available causing the process to repeat itself 20 times reaching to about 5 minutes delay.

The workaround of using cloudInit disk skips the described process (I am not sure why)
https://github.com/kubevirt/kubevirt/blob/master/tests/container_disk_test.go#L110

**What happened**:
Using cirros VMI's in tests suite will time out unless using cloudInit disk with any userData.

**What you expected to happen**:
Use cirros container-disk w/o workaround

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by EdDev** [comment]
The address is the default cloud-init server which is used to fetch the configuration instead of the mounted option.
On cloud that is the preferred option as it is centralizing the configuration management.

We could hide in the libvmi this workaround and use this option as the default for cirros.

**Comment by maiqueb** [comment]
> The address is the default cloud-init server which is used to fetch the configuration instead of the mounted option.
> On cloud that is the preferred option as it is centralizing the configuration management.
> 
> We could hide in the libvmi this workaround and use this option as the default for cirros.

https://github.com/kubevirt/kubevirt/pull/4035/commits/886fd42d7b0e80f42c2b57df747850599637cc1b#diff-310823e407ba19baac5e5e3ee718b6bbR56 would address what you're proposing, iiuc. 

I'll watch this issue, closing it if/when the aforementioned PR gets merged.

**Comment by ormergi** [comment]
> [886fd42#diff-310823e407ba19baac5e5e3ee718b6bbR56](https://github.com/kubevirt/kubevirt/commit/886fd42d7b0e80f42c2b57df747850599637cc1b#diff-310823e407ba19baac5e5e3ee718b6bbR56) would address what you're proposing, iiuc.
> 

Actually we can use an empty cloud-init config just to trigger cloud-init no cloud to work inside the VM.

A proper solution would be editing the image with 
`echo 'DATASOURCE_LIST=\"nocloud\"' > /etc/cirros-init/config` 
this will skip that check on boot
https://serverfault.com/questions/646326/how-do-i-disable-the-metadata-lookup-at-cirros-boot

**Comment by EdDev** [comment]
@ormergi , the workaround that @maiqueb mentioned is in place (you can change it to an empty script if it works, just send a PR).
I think that works and solves the issue raised here without asking to test user to know about it (embedded in the factory).

Can this issue be closed now?

**Comment by maiqueb** [comment]
> @ormergi , the workaround that @maiqueb mentioned is in place (you can change it to an empty script if it works, just send a PR).
> I think that works and solves the issue raised here without asking to test user to know about it (embedded in the factory).
> 
> Can this issue be closed now?

I think so; I don't think baking another set of images for cirros deserves the time it takes.

@ormergi , please close the issue if you're OK with the answer.

**Comment by ormergi** [comment]
/close

This workaround is good enough for now, thanks.
