### ISSUE TITLE
Make our controllers HA

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#412]
client-go now contains the leader-election code, which k8s uses. Therefore, we can now use that to make KubeVirt HA.

**Comment by rmohr** [comment]
Here a link to leader election code in the kubernetes scheduler: https://github.com/kubernetes/kubernetes/blob/58aa139f9926afd8d8d067677698a46d72fcb7b2/plugin/cmd/kube-scheduler/app/server.go

**Comment by cynepco3hahue** [comment]
@rmohr I do not sure if we really need leader-election for our service, why we can not use just `ReplicaSet` with replica 1 instead of `Deployment` for our controllers?

**Comment by cynepco3hahue** [comment]
@rmohr or we can mix both, `Deployment` for updates and `ReplicaSet` for HA, what do you think?

**Comment by rmohr** [comment]
@cynepco3hahue the main problem is, that we don't have any guarantee, if the controller instance is really down, when it is not reported as active. We have to be absolutely sure that we don't have two virt-controllers running (all our controller loops work with that assumption).

Deployments and ReplicationSets, don't guarantee that only one instance runs at a time. With the leaderelection code, we really create a lease in etcd, which makes sure, that every other controller is locked out.

**Comment by cynepco3hahue** [comment]
@rmohr From description to `leaderelection` I can see that the also not guaranteed it
`This implementation does not guarantee that only one client is acting as a leader (a.k.a. fencing)`.
Also, disclaimer to do not motivate me to use this package
`DISCLAIMER: this is an alpha API. This library will likely change significantly or even be removed entirely in subsequent releases. Depend on this API at your own risk.`
Maybe better to implement some good liveness and readiness probes and set replica to 1.

**Comment by rmohr** [comment]
True, this library only ensures that only one of the clients owns the lease. So the typical pattern is, to have the following callbacks:

```go
Callbacks: leaderelection.LeaderCallbacks{
	OnStartedLeading: run,
	OnStoppedLeading: func() {
		glog.Fatalf("lost master")
	},
},
```
In case you win the election, you start your app. In case you loose, you panic (glog.Fatalf() involves a panic call). For as long as there is no bug in this code, and the leader election config is sane, it will work. It is also the same code upstream kubernetes uses to achieve HA (client-go extracts code from there).

This means that you basically crash your golang app intentional. Since no one checks if you really crashed your app, you don't have the same guarantee like when you have fencing involved but it is definitely good enough for us.

Good liveness probes are very important too (they are part of a sane strategy to detect not well behaving masters and candidates), but they can't solve this problem. They help you to detect a master which is a leader but does not work as expected, or to detect followers, which should be ready to jump in, but are not, so that k8s can restart them.

Does that convince you?

**Comment by cynepco3hahue** [comment]
Whoa, yes, will continue to dig into the code :smile:

**Comment by michalskrivanek** [comment]
@rmohr looks usable. What kind of timeouts do you suggest?

**Comment by rmohr** [comment]
Short answer: 

I don't know.

Long answer: 

It depends on the latency between hosts and the availability requirements. If you want higher availability, you risk more unnecessary master-switches. I think the header in the implementation gives a pretty good overview: https://github.com/kubernetes/client-go/blob/master/tools/leaderelection/leaderelection.go#L21. Also noteworthy there is the section about the fact that the implementation is tolerant to arbitrary clock skew, but not against differnt clock skew rates.

**Comment by cynepco3hahue** [comment]
@rmohr I believe I finished with the patch, but the problem that `leaderelection` package exists only under the master branch and the last commit that updates the package was commit `684e17ef901e336de70c201fdb94fb55543c2637`, so I tried to update `glide.yaml` to
```
- package: k8s.io/client-go
  version: 684e17ef901e336de70c201fdb94fb55543c2637
```
but after it I start to recieve much more errors :worried: 
```
# kubevirt.io/kubevirt/vendor/k8s.io/client-go/tools/clientcmd/api                                                                                                          
../vendor/k8s.io/client-go/tools/clientcmd/api/zz_generated.deepcopy.go:112: val.DeepCopyObject undefined (type runtime.Object has no field or method DeepCopyObject)       
../vendor/k8s.io/client-go/tools/clientcmd/api/zz_generated.deepcopy.go:167: val.DeepCopyObject undefined (type runtime.Object has no field or method DeepCopyObject) 
...
```
Any ideas how can I avoid this dependency hell?

**Comment by rmohr** [comment]
Hm, can have different reasons. Could also be that broken code was synced to client-go.  Maybe try an older commit? @stu-gott any ideas?

**Comment by cynepco3hahue** [comment]
@rmohr @stu-gott I ran `make distclean` and removed `glide.lock` I redownloaded all packages via `glide update` and ran `make install` I still receive errors but at least the number decreased
```
md5sum glide.lock > .glide.lock.hash
make[1]: Leaving directory '/home/alukiano/go/src/kubevirt.io/kubevirt'
goimports -w -local kubevirt.io cmd/ pkg/ tests/
./hack/build-go.sh vet 
./hack/build-go.sh install 
# kubevirt.io/kubevirt/vendor/k8s.io/client-go/rest
../vendor/k8s.io/client-go/rest/request.go:892: undefined: "kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/api/errors".StatusTooManyRequests
# kubevirt.io/kubevirt/pkg/api/v1
api/v1/types.go:67: cannot use VM literal (type *VM) as type runtime.Object in argument to scheme.AddKnownTypes:
        *VM does not implement runtime.Object (missing DeepCopyObject method)
api/v1/types.go:68: cannot use VMList literal (type *VMList) as type runtime.Object in argument to scheme.AddKnownTypes:
        *VMList does not implement runtime.Object (missing DeepCopyObject method)
api/v1/types.go:71: cannot use Spice literal (type *Spice) as type runtime.Object in argument to scheme.AddKnownTypes:
        *Spice does not implement runtime.Object (missing DeepCopyObject method)
api/v1/types.go:72: cannot use Migration literal (type *Migration) as type runtime.Object in argument to scheme.AddKnownTypes:
        *Migration does not implement runtime.Object (missing DeepCopyObject method)
api/v1/types.go:73: cannot use MigrationList literal (type *MigrationList) as type runtime.Object in argument to scheme.AddKnownTypes:
        *MigrationList does not implement runtime.Object (missing DeepCopyObject method)
api/v1/types.go:85: unknown field 'ImportPrefix' in struct literal of type announced.GroupMetaFactoryArgs
api/v1/types.go:171: cannot use &vl.ListMeta (type *"kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ListMeta) as type "kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".List in return argument
api/v1/types.go:470: cannot use &ml.ListMeta (type *"kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ListMeta) as type "kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".List in return argument
make: *** [Makefile:16: compile] Error 2
```
Maybe it connect to ignore of `k8s.io/apimachinery/pkg/apis/meta/v1alpha1` under `glide.yaml` file.
So will appreciate any help with this ones.

**Comment by rmohr** [comment]
@cynepco3hahue this looks interesting. It looks like the `runtime.Object` interface got changed. Our resources seem to miss the `DeepCopyObject` method, to fulfill the runtime.Object interface. Probably also `DeepCopyInto`. 

Right now the rule is to try to follow client-go, to get the new funcitonalities asap (like leaderelection code). Would be cool if you could come up with an implementation of these methods. I think there was a fallback DeepCopy method in the past. Might also be worth looking into how these methods look for e.g. a Pod. There seems to be also a script in kubernetes itself which is called deepcopy-gen, to generate such copiers.

**Comment by cynepco3hahue** [comment]
@rmohr I will look at it

**Comment by cynepco3hahue** [comment]
@rmohr Please assign it to me.
