### ISSUE TITLE
CDI operator apiservice not available on sriov provider cluster

### ISSUE THREAD

**Issue by ormergi** [kubevirt/kubevirt#4120]
/kind bug

**What happened**:
Following https://github.com/kubevirt/kubevirt/issues/3850
There is a problem when running sriov provider cluster with CDI operator 
on prow causing `AfterSuite` error when trying to delete test namespace due to 
`upload.cdi.kubevirt.io/v1alpha1` ApiService being not unavailable.
The current workaround is to stop deploying CDI operator for sriov lane

I noticed that this problem started since CDI operator bump for tests suite https://github.com/kubevirt/kubevirt/pull/3571
sriov lane job from 06/22/2020, CDI operator version 1.10, no afterSuite errors:
https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3509/pull-kubevirt-e2e-kind-1.17-sriov/1275082043587301376
sriov lane job from 06/29/2020, CDI operator version 1.18, with afterSuite error:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3589/pull-kubevirt-e2e-kind-1.17-sriov/1277516936820822016

I think this should be tracked because there were changes related to certificates handling and api-server in CDI 
between versions 1.10 and 1.18.
And the due to [TLS errors in cdi-apiserver pod](https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3589/pull-kubevirt-e2e-kind-1.17-sriov/1277516936820822016/artifacts/pods/1_cdi_cdi-apiserver-9cc9496b8-85xg9-cdi-apiserver.log) 

**What you expected to happen**:
Be able to run sriov lane job with CDI operator deployed 

**How to reproduce it (as minimally and precisely as possible)**:
Revert https://github.com/kubevirt/kubevirt/pull/3797 and run sriov lane job with draft PR.

**Anything else we need to know?**:
Sriov lane jobs uses `kind-k8s-sriov-1.17.0` provider.
Although there is a workaround for this problem, It might be just luck we did not encounter this in other lanes.

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by enp0s3** [comment]
@ormergi How that this issue has been fixed, can we drop the conditional check for SRIOV lane in [cluster-deploy.sh](https://github.com/kubevirt/kubevirt/blob/5978d81304e164d80a2955b020c2a299acfc3811/hack/cluster-deploy.sh#L36)?
