### ISSUE TITLE
How to create an image from a running vm instance

### ISSUE THREAD

**Issue by yichengliu58** [kubevirt/kubevirt#4133]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind enhancement

**What you expected to happen**:

Suppose I have a running VMI, I've made some changes in the guest OS (installed some software packages and other files), I need to export this instance into an image, for my other VMIs to start.

There is no such function in kubevirt right now, we should support this image export function.

Or is there any solution already?

**Comment by wangzh21** [comment]
It is a useful feature in our cloud scenario. Is there any solution or plan? Also, I'd like to contribute if you need it.

**Comment by yichengliu58** [comment]
That would be very helpful if you could contribute ! looking forward to that !

**Comment by rmohr** [comment]
Hi, that is certainly something which we want to add. Just recently @mhenriks added offline snapshot and restore. Not sure when we will get to online snapshots. @mhenriks would it be with offline snapshots possible to clone the VM right now?

**Comment by yichengliu58** [comment]
@rmohr I think snapshot is slightly different from the issue here. In this issue we just want to export the data from a system disk of a vmi into an image. So we can regard this disk device as a raw image file, and use qemu-img to convert the file into a qcow2 image file, then the image is ready to use. 

As for snapshot, I find the implementation is far more complex than this. I'm not sure if I understand the insights here correctly. So what do you think ?

**Comment by rmohr** [comment]
@yichengliu58 so to clarify, you only want to clone a disk?

@mhenriks @awels FYI.

**Comment by awels** [comment]
If the system disk lives on a PVC, you can just clone the PVC. But if the system disk is some ephemeral type disk like a container disk, then we would need something like online snapshots before we can export it.

**Comment by rmohr** [comment]
> If the system disk lives on a PVC, you can just clone the PVC. But if the system disk is some ephemeral type disk like a container disk, then we would need something like online snapshots before we can export it.

Like described at https://github.com/kubevirt/containerized-data-importer#clone-another-pvc ?

**Comment by yichengliu58** [comment]
I think this quite similar with disk cloning, but after clone has done, the disk data should be converted to an image format (e.g. using qemu-img convert). Because users always want a ready-to-use image instead of a PVC
