### ISSUE TITLE
how kubevirt support sound configurations

### ISSUE THREAD

**Issue by timyinshi** [kubevirt/kubevirt#4137]
/kind bug

**What happened**:
i want to use kubevirt config the vm's sound,how to config?

**What you expected to happen**:
i want to use kubevirt config the vm's sound

**How to reproduce it (as minimally and precisely as possible)**:
the kubevirt code has no sound:
type Devices struct {
	Emulator    string       `xml:"emulator,omitempty"`
	Interfaces  []Interface  `xml:"interface"`
	Channels    []Channel    `xml:"channel"`
	HostDevices []HostDevice `xml:"hostdev,omitempty"`
	Controllers []Controller `xml:"controller,omitempty"`
	Video       []Video      `xml:"video"`
	Graphics    []Graphics   `xml:"graphics"`
	Ballooning  *Ballooning  `xml:"memballoon,omitempty"`
	Disks       []Disk       `xml:"disk"`
	Inputs      []Input      `xml:"input"`
	Serials     []Serial     `xml:"serial"`
	Consoles    []Console    `xml:"console"`
	Watchdog    *Watchdog    `xml:"watchdog,omitempty"`
	Rng         *Rng         `xml:"rng,omitempty"`
}

**Anything else we need to know?**:

**Comment by victortoso** [comment]
Perhaps a kind/enhancement as it does not exist nowadays?

I think the preferred are either ich6, ich9 and ac97, do you mean you would like to pick one of the available [sound devices](https://libvirt.org/formatdomain.html#sound-devices)? Or perhaps you just want to connect with some VNC viewer with audio support? Or even play some audio in the host machine?

**Comment by timyinshi** [comment]
/kind enhancement 
i just want to have my vm with some audio,but i can not do that.i do not know how to config the sound.

**Comment by wangzh21** [comment]
I also need this feature, let me imply it.

**Comment by rmohr** [comment]
> I also need this feature, let me imply it.

@wangzh21 did you mean that you want to implement it? That would be great. Feel free to reach out to us if you need something.

**Comment by wonleing** [comment]
how's this feature going on?
Any official setup doc?

**Comment by rmohr** [comment]
> how's this feature going on?
> Any official setup doc?

@victortoso is that something where your usbredir feature can be used, to e.g. connect my local headphones to the remote VM?

**Comment by wonleing** [comment]
> So, there is some mix expectations that we might need to have well defined.
> 
> 1. Does an user wants to support sound devices in the VM? If yes, why? Also, [Support sound device #4384](https://github.com/kubevirt/kubevirt/pull/4384) seems is going on that direction.

I want to  support sound devices in the VM. And we have our own remote desktop solutions (something like ctrix)
We want to play video inside VM, and remote desktop client connected to that VM can hear the sound
I already tried https://github.com/kubevirt/kubevirt/pull/4384 (merge his patch to newest kubevirt code), compile failed. It is a pitty that master didn't merge that fix after such a long time.

> 2. Does an user wants to play audio from the VM? How?
>    a) VNC with audio (needs qemu config)
>    b) Other remote solution with software emulation soundcard.
> 
> I thought about trying 2a, but I do wish to know/understand what is missing if some user is actually interested in 2b.

As I commented "thin client connect VM with VNC (or other client), playing video inside VM, headphones/speakers on the thin client can hear the sound."
Yes, 2a is the best choice. But how to config it? How to set vm.yaml? Does it need kubevirt code changes?
To me, 2b is just a backup for 2a, unfortunately, I am not an expert on software emulation.

**Comment by victortoso** [comment]
#6650 is now merged, feel free to give it a try in the next release, just add `sound: {}` under devices for ich9 sound card. ac97 is also supported, to configure it, just set the model:
```yaml
(...)
    devices:
      sound:
        model: ac97
```
