### ISSUE TITLE
Documentation confusion

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt#4142]
/kind bug

**What happened**:
I want to add a Getting Started page to `https://kubevirt.io/user-guide/#/`  The `user-guide` uri is served by an app called docsify.

This should be as simple as ...
1) Create the markdown page ... This is done

2) Run a container with docsify app to verify page content ... but this isn't documented.  There is no image in the [KubeVirt](https://hub.docker.com/u/kubevirt) user of docker hub to run the docsify app for local testing.  

3) git commit and create pull request ... but to what repository?  kubevirt/kubevirt?  kubevirt/user-guide?  Kubevirt/kubevirt.github.io?  What is the difference between the content of kubvirt/kubevirt/docs and kubvirt/user-guide?  Seems we have documentation spread across both locations.  There's even some documentation in pages and blogs in kubevirt/kubevirt.github.io

**What do I expect**
I expect a well documented workflow for creating documentation

**Comment by dhiller** [comment]
First of all I think this issue does not belong here, but rather to kubevirt.github.io. Other than that, IIUC the image is used by a verify job you want to create inside kubevirt/project-infra, right? And IIUC you then later want to run docsify somehow? Where would you run it? Or is it generated as a static page and served?

**Comment by mazzystr** [comment]
I updated my issue to try to clarify my line of thought

re First of all ... I absolutely agree but where does _it_ belong?  I put it here to get attention on helping untangle the mess.

re image ... We likely want to use kubevirt/project-infra to create the docsify image.  I don't mind self building one or having one built via project-infra and posted up to docker hub kubevirt.  That would be a CI decision.  

After the above confusion is clarified I think having a local to the laptop server run to verify markdown along with spell check and etc would be prudent before commit / pull req / CI.

**Comment by dhiller** [comment]
@codificat please keep me honest where I am wrong, I guess you know better.

OK, so I read a bit of docsify docs and now I think I understand. So what you are trying to do should be done with a pull request against github.com/kubevirt/user-guide repository, as that is the repo from where the user guide is served. Even though it is hidden below the kubevirt.io url it is server from there IIUC. Also the issue would belong there IMHO.

Other than that, to look at how the website looks can be done by [using npm and installing the docsify-cli there](https://docsify.js.org/#/quickstart). IIRC there also was a preview feature but don't remember if we are using that.

I'm not sure if it is really required to build an image for this. But what I can offer is to assist in setting up a presubmit job to execute the checks that are done via [the user-guide Makefile](https://github.com/kubevirt/user-guide/blob/master/Makefile).

WDYT?

**Comment by codificat** [comment]
@mazzystr I understand that the intention is to raise awareness of an issue that spans beyond the user guide i.e. diverse sources of documentation with not enough guidance / clarity on how to navigate, where to find what, ... the _confusion_ that is mentioned in the title. However, I believe we all agree that the issue itself does not really belong here.

I believe we can handle specific/concrete issues in the repos where they belong, and at the same time we can raise awareness of the wider issue in a wider forum, like e.g. the mailing list and/or the community calls (with links to specific ones as appropriate).

Tooling for the user-guide, for example, should be addressed in the user-guide repo. As a side note though: that repo already has deployment previews integrated, provided by netlify. We do lack some automation though (there's no OWNERS file there to begin with), but that's another thing that we should address directly in that repo.

Any objections in closing this one here?

**Comment by mazzystr** [comment]
ok, let's close this issue and move over to repo user-guide.
