### ISSUE TITLE
generation of swagger.json is nondeterministic

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#4148]
/kind bug

**What happened**:
See https://github.com/kubevirt/kubevirt/pull/4146
Running `pull-kubevirt-generate` several times yield different results each time,
Causing PRs to stall and have false errors

Fail run (first run on the exact same PR was successful)
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4146/pull-kubevirt-generate/1303609223350849536

**What you expected to happen**:
Should be stable.

**How to reproduce it (as minimally and precisely as possible)**:
Run it several times, see times it pass, some it fails, see PR for reference

**Anything else we need to know?**:
https://github.com/kubevirt/kubevirt/pull/4143
Those are WIP that should fix it looks like.

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dhiller** [comment]
As far as I can say, the issue is caused by a non deterministic behaviour of the tool we use to generate the openapi swagger.json file during the build. This manifest itself that it sometimes leaves the file as is but other times it modifies it and the generate fails.

**Comment by dhiller** [comment]
IIUC correctly the openapi generator fails to generate the correct swagger document, it only sometimes updates it to be correct. 

```
diff --git a/api/openapi-spec/swagger.json b/api/openapi-spec/swagger.json
index f6b222941..668a0d55b 100644
--- a/api/openapi-spec/swagger.json
+++ b/api/openapi-spec/swagger.json
@@ -8106,8 +8106,21 @@
     }
    },
    "v1.Patch": {
-    "description": "Patch is provided to give a concrete name and type to the Kubernetes PATCH request body.",
-    "type": "object"
+    "type": "object",
+    "properties": {
+     "patch": {
+      "type": "string"
+     },
+     "resourceName": {
+      "type": "string"
+     },
+     "resourceType": {
+      "type": "string"
+     },
+     "type": {
+      "type": "string"
+     }
+    }
    },
    "v1.PersistentVolumeClaim": {
     "description": "PersistentVolumeClaim is a user's request for and claim to a persistent volume",
```

Might be related to protobuf error messages that are emitted:
```
2020/09/09 12:27:55 WARNING: proto: file "api.proto" is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict

2020/09/09 12:27:55 WARNING: proto: file "api.proto" is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
```

**Comment by dhiller** [comment]
Not sure but our Patch might conflict with this one here: https://github.com/kubevirt/kubevirt/blob/d072d7ffcbba8d862e79db7749fd0effe2ca2f4e/vendor/k8s.io/apimachinery/pkg/apis/meta/v1/generated.proto#L744

**Comment by dhiller** [comment]
Now I'm sure there is a conflict somehow. When repeatedly running the `openapispec` binary about half of the runs it emits the simple variant

```
   "v1.Patch": {
    "description": "Patch is provided to give a concrete name and type to the Kubernetes PATCH request body.",
    "type": "object"
   },
```
which has a matching description with the protobuf mentioned above, the other times it emits the mentioned more specific definition.

**Comment by oshoval** [comment]
https://github.com/kubevirt/kubevirt/pull/4154
Should fix it, closing
Thanks
