### ISSUE TITLE
Improve the logging

### ISSUE THREAD

**Issue by mpolednik** [kubevirt/kubevirt#415]
There are currently 2 issues with logging:

1) Custom logger implementation in pkg/logging that does not seem to bring any value compared to the standard logger (maybe just levels).

2) Lack of logging calls. There is some logging, but to be able to develop new services and debug old ones we need logging in places where there is none, like pkg/virt-api's kubeproxy.

We need to look at available logging frameworks to solve 1) - using something like glog or loggo. For 2), the project lacks some guidelines on what to log and which level to use, so these should be established and enforced to keep the code manageable.

**Comment by rmohr** [comment]
> Custom logger implementation in pkg/logging that does not seem to bring any value compared to the standard logger (maybe just levels).

I can't really follow that observation. We are using a logging implementation from gokit (which is a structured logger). The logging module is a convenience logger on top of it. While glog is nice, I would prefer staying with a structured logger, it is very convenient in a distributed environment.

If you write

```
logging.DefaultLogger().V(3).Info().Object(vm).Msg("Synchronizing the VM succeeded.")
logging.DefaultLogger().Object(vm).Error().Reason(err).Msg("Starting the VM failed.")
```

you get

```
level=info timestamp=2017-09-05T10:03:37.722378Z pos=vm.go:193 component=virt-handler name=testvm89rsh kind=VM uid= msg="Synchronizing the VM succeeded."
level=error timestamp=2017-09-05T10:02:14.922328Z pos=manager.go:243 component=virt-handler name=testvmp6dp5 kind=VM uid=483ac0d0-9221-11e7-95ca-525400376d1d reason="virError(Code=43, Domain=19, Message='Network not found: no network with matching name 'nonexistent'')" msg="Starting the VM failed."

```

> Lack of logging calls. There is some logging, but to be able to develop new services and debug old ones we need logging in places where there is none, like pkg/virt-api's kubeproxy.

+1 However, I would not invest in kubeproxy. It will soon go away.

> the project lacks some guidelines on what to log and which level to use, so these should be established and enforced to keep the code manageable.

Yes definitely. Do you have some initial observations/ideas which verbosity levels make sense for which type of errors? Are you interested in coming up with an initial draft?

**Comment by mpolednik** [comment]
That kind of logging is overly verbose in code (although  nice in output). Using go-kit is somewhat fine, but having additional convenience wrapper on top of it's simple interface (judging from https://github.com/go-kit/kit/tree/master/log) is an overkill.

The kubeproxy was an example, one of the things I really miss is a simple triviality - make sure to log restful paths (aka log.Printf("%v", rest.Paths).

As for the verbosity levels, I'm fine with either drafting a document (although I need to squeeze it in my other work) or just reviewing/contributing to one. We had few nice conventions in VDSM, like logging state changes as INFO, printing out structures that are constructed as DEBUG, errors logged as errors (obviously) and probably many more. The problem was we never formalized them in writing, which leads to delays in patch merges due to nitpicking on those easy things.

**Comment by mz-pdm** [comment]
When considering convenience on top of any kind of standard logging, it'd be great to be able to use something like

    vm.log.Error("Starting the VM failed.", err)

rather than

    logging.DefaultLogger().Object(vm).Error().Reason(err).Msg("Starting the VM failed.")

The latter doesn't make the code pleasant to read. Whatever logger is used (the clarity of output should be definitely strong criteria), we should make its usage convenient in the code.

**Comment by mpolednik** [comment]
Additional point for glog is that it's heavily used by kubernetes (unlike go-kit, which seems to be preferred by legacy application transitions).

**Comment by stu-gott** [comment]
> vm.log.Error("Starting the VM failed.", err)

Ouch! That would imply that every object would need to implement a log action just in case somewhere else in the code we decided to issue a log message. That's taking convenience a little far. :)

As far as the conversation regarding structured vs unstructured logging. Structured logging is extremely helpful as it shows the exact line and context surrounding the log message. I prefer strongly that we keep it.

**Comment by mz-pdm** [comment]
Stu Gott <notifications@github.com> writes:

>> vm.log.Error("Starting the VM failed.", err)
>
> Ouch! That would imply that every object would need to implement a log
> action just in case somewhere else in the code we decided to issue a
> log message.

No, it can be implemented once and embedded into logable structs.  But I
don't insist on the notation above, it was just an example, if anything
else readable is preferable, such as

    log.Error("Starting the VM failed.", err, vm)

> As far as the conversation regarding structured vs unstructured
> logging. Structured logging is extremely helpful as it shows the exact
> line and context surrounding the log message. I prefer strongly that
> we keep it.

I agree.

**Comment by rmohr** [comment]
Should now be much less verbose with #496 merged.
