### ISSUE TITLE
virtctl image-upload ignores specified storage class

### ISSUE THREAD

**Issue by arvin-a** [kubevirt/kubevirt#4166]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
Failed to upload qcow image due to the generated PVCs ommiting the storage class specified by the virtctl command.

**What you expected to happen**:
Upload qcow to existing PV successfully.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create local-storage PV for the DV and DV scratch
2. Attempt to upload image using the following command
virtctl image-upload dv fedora-dv --size=20G --storage-class=local-storage --image-path=Fedora-Cloud-Base-32-1.6.x86_64.qcow2
3. The PVCs generated never binds due to the storage class not being set in the PVC spec.
 

**Anything else we need to know?**:
I reverted to vritctl 0.32.0 and the storage class gets set on the generated PVCs so the upload is successful.

**Environment**:
- KubeVirt version (use `virtctl version`):
Client Version: version.Info{GitVersion:"v0.33.0-rc.0", GitCommit:"c379708c963420585352927d2435135df1fedd07", GitTreeState:"clean", BuildDate:"2020-09-01T19:25:49Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"10+", GitVersion:"v1.10.0+b3b92b2", GitCommit:"b3b92b2", GitTreeState:"clean", BuildDate:"2020-07-15T09:27:21Z", GoVersion:"go1.14.3", Compiler:"gc", Platform:"linux/amd64"}

- OS (e.g. from /etc/os-release):
Fedora 32

- Kernel (e.g. `uname -a`):
Linux t480-rh.local 5.7.14-200.fc32.x86_64 #1 SMP Fri Aug 7 23:16:37 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by rmohr** [comment]
/kind bug

Thanks  for reporting!

Fixed in #4155. Should be in 0.34.
