### ISSUE TITLE
[Flaky CI]  [rfe_id:694][crit:medium][vendor:cnv-qe@redhat.com][level:component]Networking Multiple virtual machines connectivity using bridge binding interface should be able to reach [test_id:1539]the Inbound VirtualMachineInstance ex

### ISSUE THREAD

**Issue by brybacki** [kubevirt/kubevirt#4179]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

/triage build-watcher

**What happened**:
Flakefinder reported a flaky test:
[rfe_id:694][crit:medium][vendor:cnv-qe@redhat.com][level:component]Networking Multiple virtual machines connectivity using bridge binding interface should be able to reach [test_id:1539]the Inbound VirtualMachineInstance ex

prow link:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4155/pull-kubevirt-e2e-k8s-1.18/1304029997006065665

**What you expected to happen**:
Test pass

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Looks like this test was already mentioned in https://github.com/kubevirt/kubevirt/issues/2672

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by omeryahud** [comment]
Happened again here:

- https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4215/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1307929565825339393

- https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4200/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1306898648696623104

**Comment by AlonaKaplan** [comment]
Similar failure - https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4343/pull-kubevirt-e2e-k8s-1.18/1315572804292186112

**Comment by tomob** [comment]
Happened again:

* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4672/pull-kubevirt-e2e-k8s-1.17/1351463459878866944
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4672/pull-kubevirt-e2e-k8s-cnao-1.19/1350574855682002944

**Comment by dhiller** [comment]
/reopen

Seen again here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4960/pull-kubevirt-e2e-k8s-cnao-1.19/1357382337242861568

**Comment by maiqueb** [comment]
I'm looking into this issue; here's my findings so far: 
  - the test creates 4 VMs in a `BeforeAll` block
  - whenever the test flakes, it's because one of those 4 VMs fail to start
  - it then iterates a test table where one of the VMs tests (always the same one) pings one of the remaining 3 VMs (one per test)

My first idea here is that running 4 VMs one each of the tests is not necessary (I'm aware they are CirrOS VMs, quite small); we could refactor the test case to have 2 (1 created in the `BeforeAll`, then one created in each of the 3 tests).

What do you think about this @rmohr / @EdDev ? 

The failed VM crashes for an unknown reason on the `SyncVMI` call, as per [this log](https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4960/pull-kubevirt-e2e-k8s-cnao-1.19/1357382337242861568/artifacts/k8s-reporter/pods/1_kubevirt_virt-handler-4bmxm-virt-handler.log), which I'm pasting below:

```
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.",
"name":"testvmi-2gffm","namespace":"kubevirt-test-default1","pos":"vm.go:1445",
"reason":"unknown error encountered sending command SyncVMI: rpc error: code = Unavailable desc = transport is closing",
"timestamp":"2021-02-04T18:41:54.862823Z","uid":"5b5102f2-7dfe-4bb4-a702-a375dbb1ec36"}

{"component":"virt-handler","level":"info",
"msg":"re-enqueuing VirtualMachineInstance kubevirt-test-default1/testvmi-2gffm","pos":"vm.go:1053",
"reason":"unknown error encountered sending command SyncVMI: rpc error: code = Unavailable desc = transport is closing","timestamp":"2021-02-04T18:41:54.883006Z"}
```

Any idea on how to get a better grasp of what failed on the `SyncVMI` call @rmohr / @vladikr ?

Afterwards, when the request is re-queued, we can see that the container disk is never ready:

```
{"component":"virt-handler","kind":"","level":"info","msg":"containerdisk disk0 not yet ready","name":"testvmi-2gffm","namespace":"kubevirt-test-default1","pos":"mount.go:359","timestamp":"2021-02-04T18:41:54.883692Z","uid":"5b5102f2-7dfe-4bb4-a702-a375dbb1ec36"}
...
{"component":"virt-handler","kind":"","level":"info","msg":"containerdisk disk0 not yet ready","name":"testvmi-2gffm","namespace":"kubevirt-test-default1","pos":"mount.go:359","timestamp":"2021-02-04T18:41:54.944943Z","uid":"5b5102f2-7dfe-4bb4-a702-a375dbb1ec36"}
...
```
Unfortunately, the logs don't say much about why the container disk is not ready; I've pushed https://github.com/kubevirt/kubevirt/pull/5014 to address that; it might shed some light into what's wrong.

**Comment by xpivarc** [comment]
The containerdisk is not ready seems to be also a problem in PDB tests which are flaky right now.

**Comment by maiqueb** [comment]
> The containerdisk is not ready seems to be also a problem in PDB tests which are flaky right now.

Could you elaborate a bit more ? I don't even know what PDB stands for - python debugger ? 0_o :)

**Comment by EdDev** [comment]
> My first idea here is that running 4 VMs one each of the tests is not necessary (I'm aware they are CirrOS VMs, quite small); we could refactor the test case to have 2 (1 created in the BeforeAll, then one created in each of the 3 tests).

I guess the original idea was to save time for running the tests. But we know that using `BeforeAll` is broken due to the missing `AfterAll`. The unfortunate reality is that we cannot use a common resource for a group of tests and adjust to the reality.
ginkgo has plans to add something like this in they next major release, but its development seems frozen for a long time.

Therefore, I would recommend to split it and measure the cost. If the cost is too high, we can re-discuss it.

> Any idea on how to get a better grasp of what failed on the SyncVMI

Nothing on the virt-launcher log or the node journal?

**Comment by xpivarc** [comment]
> > The containerdisk is not ready seems to be also a problem in PDB tests which are flaky right now.
> 
> Could you elaborate a bit more @xpivarc ? I don't even know what PDB stands for - python debugger ? 0_o :)

Sorry :) 
I am referring to [this](https://github.com/kubevirt/kubevirt/issues/4997) flaky test where we can see that containerdisk is not ready(when we look at the launcher`s pod definition -> status section). It is cause for VMI deletion to hit the timeout of the test.

**Comment by rmohr** [comment]
> I am referring to [this](https://github.com/kubevirt/kubevirt/issues/4997) flaky test where we can see that containerdisk is not ready(when we look at the launcher`s pod definition -> status section). It is cause for VMI deletion to hit the timeout of the test.

This looks like issues around deleting a pod fast when init containers are not yet ready. I am not entirely sure if the issue you reference is the same thing. In https://github.com/kubevirt/kubevirt/issues/4997 I could see that the init container was not ready yet when the pod was marked for deletion and it had warnings like this:

```json
            "message": "Error: cannot find volume \"virt-bin-share-dir\" to mount into container \"container-disk-binary\"",
            "source": {
                "component": "kubelet",
                "host": "node01"
            },
            "firstTimestamp": "2021-02-08T06:15:24Z",
            "lastTimestamp": "2021-02-08T06:15:24Z",
            "count": 1,
            "type": "Warning",
            "eventTime": null,
            "reportingComponent": "",
            "reportingInstance": ""
        },
```

Note that we actually deleted the pod before this:

```
                "creationTimestamp": "2021-02-08T06:15:23Z",
                "deletionTimestamp": "2021-02-08T06:15:53Z",
 ```
 
 this somehow delays the deletion of the pod via the kubelet.
 
 
 While here I see in the logs that we are past the container disk init container and they are all in `Completed`.

**Comment by maiqueb** [comment]
> > My first idea here is that running 4 VMs one each of the tests is not necessary (I'm aware they are CirrOS VMs, quite small); we could refactor the test case to have 2 (1 created in the BeforeAll, then one created in each of the 3 tests).
> 
> I guess the original idea was to save time for running the tests. But we know that using `BeforeAll` is broken due to the missing `AfterAll`. The unfortunate reality is that we cannot use a common resource for a group of tests and adjust to it.
> ginkgo has plans to add something like this in they next major release, but its development seems frozen for a long time.
> 
> Therefore, I would recommend to split it and measure the cost. If the cost is too high, we can re-discuss it.
> 
> > Any idea on how to get a better grasp of what failed on the SyncVMI
> 
> Nothing on the virt-launcher log or the node journal?

Nothing on the launcher's logs, but kubelet has these errors on every failed linked failed test available in the issue:
```
Sep 21 10:18:42 node02 kubelet[1749]: W0921 10:18:42.437026    1749 docker_sandbox.go:394] failed to read pod IP from plugin/docker: networkPlugin cni failed on the status hook for pod "virt-launcher-testvmitpcn7wsxl2qbpgdtv6srn6l9wkhqvst5pr22nv6c5z_kubevirt-test-default": unexpected address output
```

I've re-run this locally > 35 times, it never failed, and I *never* got that log in the node's kubelet.

The above log seems to come from https://github.com/kubernetes/kubernetes/blob/0ffe89ed0b06a1355afe0a35e495aca3e6545b19/pkg/kubelet/dockershim/network/plugins.go#L262, but I don't understand how we end up in such a situation.

**Comment by EdDev** [comment]
Looks similar to this one: https://github.com/kubevirt/kubevirt/pull/4552

see the issue it fixed.

**Comment by xpivarc** [comment]
@rmohr You are right. I mixed two things together because I didn't check properly this issue :+1: 

@maiqueb 
Sync error: 
There is libvirt failure which triggers shut down.
```
{"code":"virErrCode(1)","component":"virt-launcher","level":"error","msg":"Connection to libvirt lost.","pos":"libvirt.go:386","reason":"virError(Code=1, Domain=7, Message='internal error: client socket is closed')","timestamp":"2021-02-04T18:41:54.871845Z"}
{"code":"virErrCode(1)","component":"virt-launcher","kind":"","level":"error","msg":"Defining the VirtualMachineInstance failed.","name":"testvmi-2gffm","namespace":"kubevirt-test-default1","pos":"libvirt_helper.go:102","reason":"virError(Code=1, Domain=7, Message='internal error: client socket is closed')","timestamp":"2021-02-04T18:41:54.871882Z","uid":"5b5102f2-7dfe-4bb4-a702-a375dbb1ec36"}
{"code":"virErrCode(1)","component":"virt-launcher","kind":"","level":"error","msg":"Failed to sync vmi","name":"testvmi-2gffm","namespace":"kubevirt-test-default1","pos":"server.go:161","reason":"virError(Code=1, Domain=7, Message='internal error: client socket is closed')","timestamp":"2021-02-04T18:41:54.871916Z","uid":"5b5102f2-7dfe-4bb4-a702-a375dbb1ec36"}
{"code":"virErrCode(1)","component":"virt-launcher","level":"error","msg":"timeout on stopping the cmd server, continuing anyway.","pos":"server.go:459","timestamp":"2021-02-04T18:41:55.862606Z"}
```
Containerdisk not ready:
The Pod is already gone ```name": "volumedisk0",
                        "state": {
                            "terminated": {
                                "exitCode": 0,
                                "reason": "Completed",
                                "startedAt": "2021-02-04T18:41:53Z",
                                "finishedAt": "2021-02-04T18:41:54Z",```
                                
Last but not least, why does the kubelet log has `Sep 21` ?

**Comment by maiqueb** [comment]
> Looks similar to this one: #4552
> 
> see the issue it fixed.

Could very well be; thanks for digging that up @EdDev  - I've ran this locally > 50 times now (I have that PR rebased) and I didn't manage to reproduce it.

@rthallisey , can you think of a way of 'knowing' if your fix #4552 also addresses this issue ? Anything I should be looking for in the logs ?

**Comment by rthallisey** [comment]
This issue looks similar to what was solved in #4552.  #4552 makes it so that the virt-launcher pod ip will now have a dummy interface with the original name and ip.  If there is a kubelet restart, this prevents the CNI from returning an error and the pod VM failing.  I talk about it in more detail in this [comment](https://github.com/kubevirt/kubevirt/pull/4552/files#r565388228).  What CNI are you using in this test?
```
Sep 21 10:18:42 node02 kubelet[1749]: W0921 10:18:42.437026    1749 docker_sandbox.go:394] failed to read pod IP from plugin/docker: networkPlugin cni failed on the status hook for pod "virt-launcher-testvmitpcn7wsxl2qbpgdtv6srn6l9wkhqvst5pr22nv6c5z_kubevirt-test-default": unexpected address output
```

**Comment by maiqueb** [comment]
> This issue looks similar to what was solved in #4552. #4552 makes it so that the virt-launcher pod ip will now have a dummy interface with the original name and ip. If there is a kubelet restart, this prevents the CNI from returning an error and the pod VM failing. I talk about it in more detail in this [comment](https://github.com/kubevirt/kubevirt/pull/4552/files#r565388228). What CNI are you using in this test?

calico

> 
> ```
> Sep 21 10:18:42 node02 kubelet[1749]: W0921 10:18:42.437026    1749 docker_sandbox.go:394] failed to read pod IP from plugin/docker: networkPlugin cni failed on the status hook for pod "virt-launcher-testvmitpcn7wsxl2qbpgdtv6srn6l9wkhqvst5pr22nv6c5z_kubevirt-test-default": unexpected address output
> ```

**Comment by rthallisey** [comment]
Calico doesn't use the `CmdCheck` RPC, so it's something else.

**Comment by maiqueb** [comment]
> Calico doesn't use the `CmdCheck` RPC, so it's something else.

OK, so while I think we're into the right track (kubelet is shutting the containers in the pod, as shown in https://github.com/kubevirt/kubevirt/issues/4179#issuecomment-777643849), we still have no clue as to what triggers it.
