### ISSUE TITLE
[Flaky CI] Windows VirtualMachineInstance [ref_id:139]with winrm connection [test_id:3160]should have the domain set properly

### ISSUE THREAD

**Issue by brybacki** [kubevirt/kubevirt#4180]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-watcher
> /kind enhancement

**What happened**:
Test failed
```
/root/go/src/kubevirt.io/kubevirt/tests/windows_test.go:159
Unexpected Warning event received: testvmi2jp2fr52kqbzdzvbfmnzstlqdpl4bkv6hlstrdtfmks4g9fc,65237b4f-e388-4443-9235-f6d6f7d270cb: server error. command SyncVMI failed: "LibvirtError(Code=38, Domain=0, Message='cannot open /dev/null: Operation not permitted')"
```

prow link:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4155/pull-kubevirt-e2e-windows2016/1305640986470256640

**What you expected to happen**:
Test pass
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
Thanks for reporting. Duplicate of #2566. Sadly an infra issue which we so far can only make happen less often and could not identify the root cause.
