### ISSUE TITLE
KubeVirt VM's DisK I/O performance is low compared to VM running in the host

### ISSUE THREAD

**Issue by avairavan** [kubevirt/kubevirt#4182]
I am measuring the disk I/O performance with KubeVirt VM in K3s cluster using fio. The KubeVirt VM shows only 60% of the performance when compared to the VM in the host. The data is as follows:

KubeVirt VM Disk I/O performance:
![image](https://user-images.githubusercontent.com/16446281/93240783-8d67f200-f752-11ea-987d-2273faab9a61.png)

VM Disk I/O performance in host:
![image](https://user-images.githubusercontent.com/16446281/93241050-dddf4f80-f752-11ea-835c-92ef38755754.png)

I was under the impression that KubeVirt VM provides at least 90% of normal VM's disk I/O performance.  May I know what is impacting the disk performance within the Kube VM 

**How to reproduce it (as minimally and precisely as possible)**:
I used the following commands to measure the disk I/O performance:

fio --minimal --name=seqwrite --time_based --runtime=300 --bs=16k --direct=1 --iodepth=64 --filesize=1M --numjobs=1 --threads1 --group_reporting --ioengine=libaio --rw=write --directory=./.
fio --minimal --name=seqread --time_based --runtime=300 --bs=16k --direct=1 --iodepth=64 --filesize=1M --numjobs=1 --threads= --group_reporting --ioengine=libaio --rw=read --directory=./.
fio --minimal --name=randread --time_based --runtime=300 --bs=16k --direct=1 --iodepth=64 --filesize=1M --numjobs=1 --threads1 --group_reporting --ioengine=libaio --rw=randread --file_service_type=random --directory=./.
fio --minimal --name=rndrw --time_based --runtime=300 --bs=16k --direct=1 --iodepth=64 --filesize=1M --numjobs=1 --threads=1 --group_reporting --ioengine=libaio --rw=randrw:16 --rwmixwrite=40 --file_service_type=random --directory=./.
fio --minimal --name=randwrite --time_based --runtime=300 --bs=16k --direct=1 --iodepth=64 --filesize=10M --numjobs=1 --threads=1 --group_reporting --ioengine=libaio --rw=randwrite:8 --file_service_type=random --directory=./.

**Anything else we need to know?**:
Followed the link to install KubeVirt in K3s: https://kubevirt.io/2019/KubeVirt_k8s_crio_from_scratch_installing_KubeVirt.html
This link to import the VMI: https://kubevirt.io/labs/kubernetes/lab2.html

**Environment**:
- KubeVirt version (use `virtctl version`): '
[root@node0 ~]# ./virtctl version
Client Version: version.Info{GitVersion:"v0.32.0", GitCommit:"44d3011eb09b1488d181439dd0bf54f58ebb148b", GitTreeState:"clean", BuildDate:"2020-08-11T19:31:18Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"{gitVersion}", GitCommit:"{gitCommit}", GitTreeState:"{gitTreeState}", BuildDate:"{buildDate}", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):
[root@node0 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2+k3s1", GitCommit:"cdab19b09a84389ffbf57bebd33871c60b1 d6b28", GitTreeState:"clean", BuildDate:"2020-01-27T18:09:26Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"17", GitVersion:"v1.17.2+k3s1", GitCommit:"cdab19b09a84389ffbf57bebd33871c60b1 d6b28", GitTreeState:"clean", BuildDate:"2020-01-27T18:09:26Z", GoVersion:"go1.13.6", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications:  
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "fedora"
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "https://download.fedoraproject.org/pub/fedora/linux/releases/30/Cloud/x86_64/images/Fedora-Cloud-Base-30-1.2.x86_64.raw.xz"
spec:
  accessModes:
   ReadWriteOnce
  resources:
    requests:
      storage: 4Gi
  storageClassName: hostpath

- Cloud provider or hardware configuration: Bare Metal with 12 cores

- OS (e.g. from /etc/os-release): 
[root@node0 tmp]# cat /etc/os-release
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

- Kernel (e.g. `uname -a`): 
[root@node0 tmp]# uname -a
Linux node0 3.10.0-1062.12.1.el7.x86_64 #1 SMP Tue Feb 4 23:02:59 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by vladikr** [comment]
Could you also please provide the domxml of the VM you are running directly on the host?

**Comment by vladikr** [comment]
Also, could you please run the same, but add `cpu: 2` to requests:

```
  resources:
        requests:
          cpu: 2
          memory: 1024M
```

**Comment by avairavan** [comment]
Apologies for the delayed response. Was running other tests in my setup and couldn't collect these stats. Will do it today. What is the difference between allocating resources -> requests -> cpu: 2 for the pod and allocating cores =2 for the VM.

**Comment by avairavan** [comment]
I ran the performance tests with 

> resources:
        requests:
          cpu: 2
          memory: 1024M

but the performance is still low as shown below:

![image](https://user-images.githubusercontent.com/16446281/93909812-315f1980-fcce-11ea-995e-2d8ddcf44c3a.png)

The domxml of VM is as follows:

[vm1.docx](https://github.com/kubevirt/kubevirt/files/5262903/vm1.docx)

**Comment by vladikr** [comment]
Could you also please post the domxml of the VM you are running on the host, so I could compare, please?

**Comment by avairavan** [comment]
Attached herewith domxml of the host VM.

[hostvm.docx](https://github.com/kubevirt/kubevirt/files/5265014/hostvm.docx)

**Comment by awels** [comment]
Correct me if I am wrong, but I was under the impression that in k3s the node is a VM itself. So if you run a KubeVirt VM on a k3s node, then you are running a VM inside a VM, which will impact performance.

**Comment by avairavan** [comment]
@awels The K3s is a physical machine and is not a VM. The system config is as follows:

> [root@node1 ~]# lshw -short
H/W path           Device        Class          Description
===========================================================
                                 system          Edge (Default string)
/0                               bus            Default string
/0/0                             memory         64KiB BIOS
/0/3a                            memory         32GiB System Memory
/0/3a/0                          memory         16GiB SODIMM DDR4 Synchronous 2400 MHz (0.
/0/3a/1                          memory         [empty]
/0/3a/2                          memory         16GiB SODIMM DDR4 Synchronous 2400 MHz (0.
/0/3a/3                          memory         [empty]
/0/45                            memory         384KiB L1 cache
/0/46                            memory         1536KiB L2 cache
/0/47                            memory         12MiB L3 cache
/0/48                            processor      Intel(R) Core(TM) i7-8700T CPU @ 2.40GHz
/0/100                           bridge         8th Gen Core Processor Host Bridge/DRAM Re
/0/100/1                         bridge         Xeon E3-1200 v5/E3-1500 v5/6th Gen Core Pr
/0/100/2                         display        UHD Graphics 630 (Desktop)
/0/100/8                         generic        Xeon E3-1200 v5/v6 / E3-1500 v5 / 6th/7th
/0/100/12                        generic        Cannon Lake PCH Thermal Controller
/0/100/14                        bus            Cannon Lake PCH USB 3.1 xHCI Host Controll
/0/100/14/0        usb1          bus            xHCI Host Controller
/0/100/14/1        usb2          bus            xHCI Host Controller
/0/100/14.2                      memory         RAM memory
/0/100/16                        communication  Cannon Lake PCH HECI Controller
/0/100/16.3                      communication  Cannon Lake PCH Active Management Technolo
/0/100/17          scsi1         storage        Cannon Lake PCH SATA AHCI Controller
/0/100/17/0.0.0    /dev/sda      disk           1920GB XA1920LE10063
/0/100/17/0.0.0/1                volume         499MiB Windows FAT volume
/0/100/17/0.0.0/2  /dev/sda2     volume         2047MiB data partition
/0/100/17/0.0.0/3  /dev/sda3     volume         2047KiB BIOS Boot partition
/0/100/17/0.0.0/4  /dev/sda4     volume         1786GiB LVM Physical Volume
/0/100/1b                        bridge         Cannon Lake PCH PCI Express Root Port #17
/0/100/1b/0        enp2s0f0      network        Ethernet Controller 10G X550T
/0/100/1b/0.1      enp2s0f1      network        Ethernet Controller 10G X550T
/0/100/1c                        bridge         Cannon Lake PCH PCI Express Root Port #1
/0/100/1c.3                      bridge         Cannon Lake PCH PCI Express Root Port #4
/0/100/1c.3/0      enp4s0        network        I210 Gigabit Network Connection
/0/100/1c.4                      bridge         Cannon Lake PCH PCI Express Root Port #5
/0/100/1c.4/0      enp5s0        network        I210 Gigabit Network Connection
/0/100/1c.5                      bridge         Cannon Lake PCH PCI Express Root Port #6
/0/100/1c.5/0      enp6s0        network        I210 Gigabit Network Connection
/0/100/1c.6                      bridge         Cannon Lake PCH PCI Express Root Port #7
/0/100/1c.6/0      enp7s0        network        I210 Gigabit Network Connection
/0/100/1c.7                      bridge         Cannon Lake PCH PCI Express Root Port #8
/0/100/1c.7/0      enp8s0        network        I210 Gigabit Network Connection
/0/100/1f                        bridge         Q370 Chipset LPC/eSPI Controller
/0/100/1f.3                      multimedia     Cannon Lake PCH cAVS
/0/100/1f.4                      bus            Cannon Lake PCH SMBus Controller
/0/100/1f.5                      bus            Cannon Lake PCH SPI Controller
/0/100/1f.6        eno1          network        Ethernet Connection (7) I219-LM
/1                               power          To Be Filled By O.E.M.
/2                 cni0          network        Ethernet interface
/3                 vethf9cb5f79  network        Ethernet interface
/4                 vethf3c77754  network        Ethernet interface
/5                 vethd26c3a45  network        Ethernet interface
/6                 veth512db095  network        Ethernet interface
/7                 network1      network        Ethernet interface
/8                 veth56406af8  network        Ethernet interface
/9                 vethfe97f1b5  network        Ethernet interface
/a                 veth1dde9dc9  network        Ethernet interface
/b                 veth2b90e164  network        Ethernet interface
/c                 virbr0-nic    network        Ethernet interface
/d                 virbr0        network        Ethernet interface
/e                 veth8a4299b6  network        Ethernet interface

**Comment by mhenriks** [comment]
KubeVirt disk images are initially sparse files.  Is that also the case for your VM?

**Comment by avairavan** [comment]
I used the disk image used in the Host VM on the KubeVirt VM. Even with the same disk image, the performance of KubeVirt VM is low compared with the Host VM

![image](https://user-images.githubusercontent.com/16446281/94148324-79a04800-fe44-11ea-8b4e-593044116549.png)

**Comment by salanki** [comment]
Could this be related to disk cache setting? Ie. if kubevirt defaults to write-through but the vanilla on the host is write-back?

**Comment by talcoh2x** [comment]
someone can update if some special configuration required to improve the performance ??

**Comment by avairavan** [comment]
The issue is because the VM disk image in the raw format lost its sparseness during the file transfer. Hence, the VM's disk image size has grown leading to poor performance. The performance issue got fixed by using the command "virt-sparsify" on the disk image.

**Comment by talcoh2x** [comment]
Hi  @avairavan, this is something that you run before you uploading the image ?
