### ISSUE TITLE
[Flaky CI] Infrastructure [rfe_id:4102][crit:medium][vendor:cnv-qe@redhat.com][level:component]certificates [test_id:4099] should be rotated when a new CA is created + Infrastructure [rfe_id:4102][crit:medium][vendor:cnv-qe@redhat.com][level:component]certificates [test_id:4100] should be valid during the whole rotation process

### ISSUE THREAD

**Issue by tomob** [kubevirt/kubevirt#4198]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-watcher

**What happened**:

Two tests related to certificate rotation failed.

* Infrastructure   [rfe_id:4102][crit:medium][vendor:cnv-qe@redhat.com][level:component]certificates  [test_id:4099] should be rotated when a new CA is created
* Infrastructure   [rfe_id:4102][crit:medium][vendor:cnv-qe@redhat.com][level:component]certificates  [test_id:4100] should be valid during the whole rotation process

Prow link: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4083/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1305845963499245569

**What you expected to happen**:
Tests should pass

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Test lane: pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6

**Comment by maya-r** [comment]
[More occurrences](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4092/pull-kubevirt-e2e-kind-k8s-1.17.0-ipv6/1306953511015026688), interesting that it is on the same lane.

**Comment by maya-r** [comment]
I wonder if this test would be more stable if we changed [this Eventually block](https://github.com/kubevirt/kubevirt/blob/master/tests/infra_test.go#L89-L104) to Get the secret and check that the Data no longer matches the bogus "random": "nonsense" value.

That is, that the flakiness might be occurring since we managed to get the old value before it was deleted.

what do you think, @rmohr?

**Comment by rmohr** [comment]
@maya-r not sure this is the right approach. I think the main issue is that we actually have issues connecting to the VMI. We basically just force a certificate rotation and then check if we can still connect. I know that it recovers later, but there should be the whole time no single point in time where we can't connect to the VM. With or without the new certificate :/

**Comment by omeryahud** [comment]
Failed again here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4216/pull-kubevirt-e2e-k8s-1.17/1307931454021308416

**Comment by dhiller** [comment]
Again here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4444/pull-kubevirt-e2e-k8s-1.17/1325754118735663104

**Comment by rmohr** [comment]
Looks like this may have been solved too with #4522 which I didn't think it would help for this test. Since the PR is merged I only see this test failing  if we run in the the strange unresponsiveness of node02. Still keeping it open for a few more days.

**Comment by ashleyschuett** [comment]
This seems to be an issue again, but seemingly only in the flakey-test-lane 
https://prow.k8s.io/view/gcs/kubevirt-prow/pr-logs/directory/pull-kubevirt-check-tests-for-flakes/1354376788372885504
https://prow.k8s.io/view/gcs/kubevirt-prow/pr-logs/directory/pull-kubevirt-check-tests-for-flakes/1354759555677949952
https://prow.k8s.io/view/gcs/kubevirt-prow/pr-logs/directory/pull-kubevirt-check-tests-for-flakes/1355054874588352512
https://prow.k8s.io/view/gcs/kubevirt-prow/pr-logs/directory/pull-kubevirt-check-tests-for-flakes/1355576813270601728
https://prow.k8s.io/view/gcs/kubevirt-prow/pr-logs/directory/pull-kubevirt-check-tests-for-flakes/1355807080912523264
https://prow.k8s.io/view/gcs/kubevirt-prow/pr-logs/directory/pull-kubevirt-check-tests-for-flakes/1356272398613090304

```
{"component":"virt-operator","level":"info","msg":"Waiting on daemonset virt-handler to roll over to latest version","pos":"reconcile.go:310","timestamp":"2021-01-30T19:52:05.982635Z"}
{"component":"virt-operator","kind":"","level":"info","msg":"Processed deployment for this round","name":"kubevirt","namespace":"kubevirt","pos":"kubevirt.go:1046","timestamp":"2021-01-30T19:52:06.001548Z","uid":"a9dabe84-2d8e-4c75-9f20-19c7ecea8734"}
{"component":"virt-operator","kind":"","level":"info","msg":"Handling KubeVirt resource","name":"kubevirt","namespace":"kubevirt","pos":"kubevirt.go:624","timestamp":"2021-01-30T19:52:21.046665Z","uid":"a9dabe84-2d8e-4c75-9f20-19c7ecea8734"}
{"component":"virt-operator","kind":"","level":"info","msg":"Handling deployment","name":"kubevirt","namespace":"kubevirt","pos":"kubevirt.go:970","timestamp":"2021-01-30T19:52:21.047015Z","uid":"a9dabe84-2d8e-4c75-9f20-19c7ecea8734"}
{"component":"virt-operator","level":"info","msg":"Waiting on daemonset virt-handler to roll over to latest version","pos":"reconcile.go:310","timestamp":"2021-01-30T19:52:21.053040Z"}
{"component":"virt-operator","kind":"","level":"info","msg":"Processed deployment for this round","name":"kubevirt","namespace":"kubevirt","pos":"kubevirt.go:1046","timestamp":"2021-01-30T19:52:21.081215Z","uid":"a9dabe84-2d8e-4c75-9f20-19c7ecea8734"}
{"component":"virt-operator","kind":"","level":"info","msg":"Handling KubeVirt resource","name":"kubevirt","namespace":"kubevirt","pos":"kubevirt.go:624","timestamp":"2021-01-30T19:52:21.081370Z","uid":"a9dabe84-2d8e-4c75-9f20-19c7ecea8734"}
{"component":"virt-operator","kind":"","level":"info","msg":"Handling deployment","name":"kubevirt","namespace":"kubevirt","pos":"kubevirt.go:970","timestamp":"2021-01-30T19:52:21.081493Z","uid":"a9dabe84-2d8e-4c75-9f20-19c7ecea8734"}
{"component":"virt-operator","level":"info","msg":"Waiting on daemonset virt-handler to roll over to latest version","pos":"reconcile.go:310","timestamp":"2021-01-30T19:52:21.086354Z"}
{"component":"virt-operator","kind":"","level":"info","msg":"Processed deployment for this round","name":"kubevirt","namespace":"kubevirt","pos":"kubevirt.go:1046","timestamp":"2021-01-30T19:52:21.108042Z","uid":"a9dabe84-2d8e-4c75-9f20-19c7ecea8734"}
```

when looking at the virt-handler DS for these failed cases one of the container in one of the virt-handler pods will be in an existed state 

```
                        "lastState": {
                            "terminated": {
                                "exitCode": 137,
                                "reason": "ContainerStatusUnknown",
                                "message": "The container could not be located when the pod was deleted.  The container used to be Running",
                                "startedAt": null,
                                "finishedAt": null
                            }
                        },
```
These seems to be an issue only on `node01`

**Comment by dhiller** [comment]
Will look into this, eventually something to do with the prow job setup differing. Maybe we should disable/skip the job for the check-for-flakes lane.

**Comment by phoracek** [comment]
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4985/pull-kubevirt-e2e-k8s-1.19/1358967152656257024

**Comment by fgimenez** [comment]
Happened again here https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev/1359804546922057728

**Comment by ormergi** [comment]
Failed due to a conflict 
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5332/pull-kubevirt-e2e-k8s-1.18/1376449874530144256
