### ISSUE TITLE
cleanup virt-launcher socket directories

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#421]
#337 The directories created for the virt-launcher pods need to be cleaned up after stopping each vm.

**Comment by davidvossel** [comment]
@rmohr I have no idea if this is really a good idea, but we could use a time lease

virt-launcher would heartbeat the folder every 30 seconds by either renaming a file or touching/removing a file.  That changes the directory's last modify time. If the directory hasn't been updated in 'x' amount of time, it could be garbage collected because we can assume the virt-launcher container is gone.

**Comment by michalskrivanek** [comment]
IIUC these are in /var/run/kubevirt/default/[VM name]/ ?
If so then this,mechanism not good enough in case of VM restart on the same host
Is there no other way how to make sure something is called on virt-launcher exit/crash? If not then it needs to be done on next launch (only there, or in addition to the periodic cleanup)

**Comment by fabiand** [comment]
@davidvossel please see if this can be closed in the light of #663

**Comment by davidvossel** [comment]
@fabiand some shared directories are going away with #663 but not all of them. We're depending on a shared directory primarily for the unix sock connections between virt-launcher and virt-handler.

The VM pod that contains virt-launcher doesn't have an IP address because the IP is getting owned by the VM within the Pod. If we figure out a way to both let the Pod and VM in the Pod have separate IP Addresses, then we'll be able to drop all shared directories.

**Comment by rmohr** [comment]
> If we figure out a way to both let the Pod and VM in the Pod have separate IP Addresses, then we'll be able to drop all shared directories.

We might get away with simply execing a small socket-proxy-subprocess via nsenter in the right mount namespace which talks to the socket. Then we can communicate via stdin/stout between the parent and  the child process.

**Comment by davidvossel** [comment]
@rmohr how would virt-handler discover the VM pod's namespaces to do nsenter?
