### ISSUE TITLE
Investigate why pod log streaming works inconsistently in CI environment

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#422]
vmlifecycle tests that require virt-handler pod log streaming do not behave consistently in our JENKINs environment. 

We need to track down why log streaming behaves inconsistently and improve the situation so we can re-enable these tests in JENKINs.

**Comment by davidvossel** [comment]
I'm beginning to think this issue may have something to do with the Regex parsing of the log line

**Comment by fabiand** [comment]
I think this is fixed.

Please reopen if this is still an issue.
