### ISSUE TITLE
k8s-1.19 has some suspicious test failures

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#4229]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

When looking at the failed runs for the new k8s-1.19 lane I had some suspicious test failures that didn't look like flakes:
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4162/pull-kubevirt-e2e-k8s-1.19/1308199092169478144
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3837/pull-kubevirt-e2e-k8s-1.19/1308153040678686720
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4196/pull-kubevirt-e2e-k8s-1.19/1308109881026285568
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3949/pull-kubevirt-e2e-k8s-1.19/1308096291313553408

We might need to investigate these.

/cc @qinqon 

@rmohr maybe you can shed some light on what might be wrong regarding those failures?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

All failures for k8s-1.19: https://prow.apps.ovirt.org/?type=presubmit&job=pull-kubevirt-e2e-k8s-1.19&state=failure

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dhiller** [comment]
These two seem somehow network related: @phoracek do you mind taking a quick look?

* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4196/pull-kubevirt-e2e-k8s-1.19/1308109881026285568
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3949/pull-kubevirt-e2e-k8s-1.19/1308096291313553408

**Comment by dhiller** [comment]
This one looks storage related: @aglitke do you mind taking a quick look, please?

* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3837/pull-kubevirt-e2e-k8s-1.19/1308153040678686720

**Comment by phoracek** [comment]
> These two seem somehow network related: @phoracek do you mind taking a quick look?
> 
>     * https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4196/pull-kubevirt-e2e-k8s-1.19/1308109881026285568
> 
>     * https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3949/pull-kubevirt-e2e-k8s-1.19/1308096291313553408

@qinqon are those related to our new Policy tests?
