### ISSUE TITLE
[Flakey CI] [rfe_id:150][crit:high][vendor:cnv-qe@redhat.com][level:component]Networkpolicy when three cirros VMs with default networking are started and serverVMI start an HTTP server on port 80 and 81 and connectivity between VMI/s is blocked by Default-deny networkpolicy [test_id:1511] should fail to reach serverVMI from clientVMI

### ISSUE THREAD

**Issue by omeryahud** [kubevirt/kubevirt#4239]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-officer

**What happened**:
Flakefinder found this test to be flakey:
```
[rfe_id:150][crit:high][vendor:cnv-qe@redhat.com][level:component]Networkpolicy when three cirros VMs with default networking are started and serverVMI start an HTTP server on port 80 and 81 and connectivity between VMI/s is blocked by Default-deny networkpolicy [test_id:1511] should fail to reach serverVMI from clientVMI
```

Failed in this prowjob due to invalid interface conversion: `Panic: interface conversion: runtime.Object is *v1.Status, not *v1.Event`

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4196/pull-kubevirt-e2e-k8s-1.19/1308109881026285568

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by qinqon** [comment]
I see that at kubevirt we have client-go 0.16.4 but k8s is 1.19 could this be the issue ? openned at bug/question at k8s client-go https://github.com/kubernetes/client-go/issues/869

**Comment by rmohr** [comment]
/reopen

#4246 only helps to debug this problem.
