### ISSUE TITLE
[flaky ci] [Serial]Slirp Networking should be able to VirtualMachineInstance with slirp interface

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#4262]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

The test 

```
[Serial]Slirp Networking should be able to VirtualMachineInstance with slirp interface
```

fails a lot since #4051 got merged with

```
tests/utils.go:3031
Timed out after 10.000s.
Not all kubevirt components picked up the kubevirt config successfully
Expected
    <bool>: false
to be true
tests/vmi_slirp_interface_test.go:51
```

It turns out that the reason are missing readiness probes on virt-handler in combination with a long startup time. We see between the selinux detection and the controller-start in virt-handler sometimes huge delays:

```
{"component":"virt-handler","level":"info","msg":"SELinux is reported as 'enforcing'","pos":"virt-handler.go:342","timestamp":"2020-09-25T02:25:33.675675Z"}
{"component":"virt-handler","level":"info","msg":"Updating cluster config to resource version '47417'","pos":"config-map.go:467","timestamp":"2020-09-25T02:25:43.931728Z"}
{"component":"virt-handler","level":"info","msg":"Starting virt-handler controller.","pos":"vm.go:869","timestamp":"2020-09-25T02:25:56.200917Z"}
```

The things which are happening during this lost time:

 * some selinux relabeling
 * installing a selinux policy
 * waiting for list-watchers to get ready

All three should be reasonably fast, but one of these operations seems to cause issues.

This got visible now with the changed test-order, introduced with #4051, where operator tests are running exactly before this failing test.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/batch/pull-kubevirt-e2e-k8s-1.16/1309294058086076417

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@maiqueb @jean-edouard FYI.

**Comment by jean-edouard** [comment]
That's 23 seconds delay, right?
Installing a .cil SELinux policy takes 17 seconds on my machine, so that delay doesn't surprise me.
What's more surprising is that until very recently (https://github.com/kubevirt/kubevirt/pull/4183), we were installing 2 .cil files, which must have added up to a 30+ seconds delay.
Maybe we're having the opposite problem, and virt-handler being ready earlier revealed a race condition somewhere else?

**Comment by rmohr** [comment]
> That's 23 seconds delay, right?
> Installing a .cil SELinux policy takes 17 seconds on my machine, so that delay doesn't surprise me.
> What's more surprising is that until very recently (#4183), we were installing 2 .cil files, which must have added up to a 30+ seconds delay.
> Maybe we're having the opposite problem, and virt-handler being ready earlier revealed a race condition somewhere else?

If this long period is really ok, then we  are good with #4263. We had not readiness probes on virt-handler, but some tests alrady  wanted to connect to it, because the ready condition was already set while virt-handler was still installing the selinux policy.

**Comment by arnongilboa** [comment]
Again:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5089/pull-kubevirt-e2e-k8s-cnao-1.19/1368526208303632384
