### ISSUE TITLE
Run tests against cri-o too, not only against Docker

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#427]
With #337 merged, we should in theory now be independent of any CRI which is not kvm based, or uses any other kind of real virtualization. Extend our tests, to also test agains cri-o, to make sure we really support it.

**Comment by fabiand** [comment]
Now that we are also testing openshift, we might not need to decide on a specific runtime, but rather focus on the kubernetes distribution.

In other words - we are implicitly testing a different runtmie by testing openshift.

**Comment by cynepco3hahue** [comment]
@rmohr @fabiand does openshift use cri-o?

**Comment by fabiand** [comment]
I'm not sure if they did the switch yet. It could be that its optional.

However…
The original reason for this card was to test the runtime that openshift uses.
Now that we test openshift, we leave it to them to decide what runtime to use.
