### ISSUE TITLE
[Flakey CI] Infrastructure [rfe_id:4126][crit:medium][vendor:cnv-qe@redhat.com][level:component]Taints and toleration CriticalAddonsOnly taint set on a node [test_id:4134] kubevirt components on that node should not evict expand_more

### ISSUE THREAD

**Issue by ashleyschuett** [kubevirt/kubevirt#4286]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
``` Infrastructure [rfe_id:4126][crit:medium][vendor:cnv-qe@redhat.com][level:component]Taints and toleration CriticalAddonsOnly taint set on a node [test_id:4134] kubevirt components on that node should not evict expand_more```

periodically fails, example run: 

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3879/pull-kubevirt-e2e-k8s-1.18/1310942294022557696

**Anything else we need to know?**:

PR https://github.com/kubevirt/kubevirt/pull/4167 may fix the issue but it needs to be further looked into. 

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by oshoval** [comment]
#4167 fixes other issue, here we have a conflict issue

**Comment by oshoval** [comment]
/assign
creating a PR
