### ISSUE TITLE
VM rename has some unwanted side-effects

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#4294]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

The VM rename feature as introduce in https://github.com/kubevirt/kubevirt/pull/3036 has a lot of issues.

Most important the following:

 * It blindly deletes a VM with the new target name. So if you rename a VM A to B and B already exists, it just gets delerted and replaced by a A - clone
 * Deleting VMs which are within a rename process can leave a clone behind without a finished rename process
The process has in general no idea if a VM, which gets discovered during the rename is a clonse of VM A, or if it just existed all the time independent of A.
 * Renames can fail. It would need a way to be cancelled.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by davidvossel** [comment]
@mhenriks I believe snapshots are impacted by rename as well, right? What situations would cause issues with snapshots?
