### ISSUE TITLE
Code owners configuration

### ISSUE THREAD

**Issue by MarSik** [kubevirt/kubevirt#430]
I recently noticed GitHub enabled a feature that allows specifying code owners for different pieces of code:

https://github.com/blog/2392-introducing-code-owners

It should supposedly automatically add the proper reviewers to patches.

Do you think it would make sense to enable it?

**Comment by fabiand** [comment]
I think this is a good thing - once we have seen more contributions for more contributors.

Currently the whole code base would probably be mapped to 1-4 ppl, which might not be to valuable.

**Comment by fabiand** [comment]
Closing this for now, will reopen it if necessary.
