### ISSUE TITLE
add namespace attribute for virtctl ?

### ISSUE THREAD

**Issue by korenlev** [kubevirt/kubevirt#4309]
**FEATURE REQUEST**:

> add namespace attribute for virtctl:
>
> /kind enhancement

**What happened**:
VM/Pod deployed on a chosen namespace

**What you expected to happen**:
virtctl guestosinfo vmi-cirros -n my-chosen-ns

**How to reproduce it (as minimally and precisely as possible)**:
virtctl vnc vmi-cirros
Can't access VMI vmi-cirros: virtualmachineinstance.kubevirt.io "vmi-cirros" not foundo

**Anything else we need to know?**:

**Environment**:
- KubeVirt version: v0.32.0
- Kubernetes version: v1.17.8
- VM or VMI specifications: cirros-demo
- Cloud provider or hardware configuration: on bare-metal
- OS : Red Hat Enterprise Linux 8.2 (Ootpa
- Kernel: 4.18.0-193.14.3.el8_2.x86_64
- Install tools: kubectl
- Others:

**Comment by korenlev** [comment]
kubectl get virtualmachineinstance -n my-chosen-ns -o wide
NAME         AGE    PHASE     IP                NODENAME      LIVE-MIGRATABLE   PAUSED
vmi-cirros   104m   Running   192.168.247.146   korens-3      False

**Comment by rmohr** [comment]
@korenlev `virtctl` does support `-n` or `--namespace` for all of its commands.

This should work for you: `virctl vnc vmi-cirros -n my-chosen-ns`

**Comment by rmohr** [comment]
also check `virtctl options` (same like `kubectl options`) for all global flags for all commands`.

**Comment by korenlev** [comment]
got it , virtctl can list VMs on all namespaces ? (deployed using kubectl)

**Comment by rmohr** [comment]
> got it , virtctl can list VMs on all namespaces ? (deployed using kubectl)

virtctl does not duplicate kubectl functionality. In general we recommend installing virtctl as a plugin (either via krew or just renaming virtctl in your path to `kubectl-virt`.

Then you can do things like this:


```
kubectl get vmis
kubectl get vms
kubectl virt console <vmi>
kubectl virt vnc <vm>
...
```

**Comment by rmohr** [comment]
/close

@korenlev feel free to reopen the issue if my answer does not solve your issue.
