### ISSUE TITLE
test_id:1780 is three tests in reality

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#4310]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

When checking for [test_id:1780](https://github.com/kubevirt/kubevirt/blob/f371b255e9c35dc2dd673313d9c2024c56afa2ce/tests/vmi_networking_test.go#L610) I noticed that this is in fact a test table and there are [three tests](https://github.com/kubevirt/kubevirt/blob/f371b255e9c35dc2dd673313d9c2024c56afa2ce/tests/vmi_networking_test.go#L671-L670) involved.

**What you expected to happen**:

Each of the tests should have it's own `test_id`

For context: this was seen on my shift as build watcher. Our current main identification criteria for recording flaky tests is the test_id marker. Sometimes it makes more sense code wise to split the tests into separate sections (in this case a Ginkgo Table). This then leads to confusion about the actual flaky tests that should be eliminated.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dhiller** [comment]
See the issues marked with test_id but pointing at different tests: https://github.com/kubevirt/kubevirt/issues?q=is%3Aopen+is%3Aissue+test_id%3A1780

**Comment by dhiller** [comment]
https://github.com/kubevirt/kubevirt/issues/3824
https://github.com/kubevirt/kubevirt/issues/3811

**Comment by oshoval** [comment]
Hi Daniel, how one can generate free ids ? 
it must be of Polarion or we can add some custom ids with other label or other value ?
such as
ctest_id:1234
or test_id:c1234

**Comment by dhiller** [comment]
Yes, I think you are correct, test ids are generated in Polarion. Hey @ILpinto, maybe you can help here?

**Comment by ILpinto** [comment]
You need to add the test id in the It section like: [test_id:1234]
