### ISSUE TITLE
[Flaky CI][Serial]VirtualMachineRestore Tests rook-ceph With a more complicated VM should restore a vm that boots from a datavolumetemplate

### ISSUE THREAD

**Issue by qinqon** [kubevirt/kubevirt#4336]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/tirage build-watcher
> /kind enhancement

**What happened**:

```
[Serial]VirtualMachineRestore Tests rook-ceph With a more complicated VM should restore a vm that boots from a datavolumetemplate expand_less 
tests/restore_test.go:547 Unexpected error:     <expect.TimeoutError>: 20000000000     expect: timer expired after 20 seconds occurred tests/restore_test.go:468open stdoutopen_in_new
```

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4330/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1313773071928135680

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by akrejcir** [comment]
Happened again on 28.10.2020
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4437/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1321440068992241665
