### ISSUE TITLE
[Flaky CI][Serial]VirtualMachineRestore Tests rook-ceph With a more complicated VM should restore a vm that boots from a PVC

### ISSUE THREAD

**Issue by maiqueb** [kubevirt/kubevirt#4342]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
/triage build-watcher
> /kind enhancement

**What happened**:

```
tests/restore_test.go:612
Unexpected error:
    <*kubecli.AsyncSubresourceError | 0xc001da4f60>: {
        err: "Can't connect to websocket (500): websocket: bad handshake\n",
        StatusCode: 500,
    }
    Can't connect to websocket (500): websocket: bad handshake
    
occurred
tests/restore_test.go:433
```

Found [here](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4300/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1313218919334416384).

**What you expected to happen**:
Test should pass.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
/close

"Fixed" in #4522. It takes sometimes unusually long until the kubelet updates the certificate secrets.
