### ISSUE TITLE
[Flaky CI] periodic-kubevirt-push-nightly-conformance fails on "[Conformance] preserves connectivity" test

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#4345]
/kind bug

**What happened**:
One test of `periodic-kubevirt-push-nightly-conformance` fails
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-push-nightly-conformance/1314755293896249344
and
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-push-nightly-conformance/1315117428715294720

```
tests/vmi_networking_test.go:735
Timed out after 240.000s.
migration should succeed after 240 s
Expected success, but got an error:
    <*errors.errorString | 0xc000c45380>: {
        s: "Migration is in phase Scheduling",
    }
    Migration is in phase Scheduling
tests/vmi_networking_test.go:732
```

**What you expected to happen**:
periodic-kubevirt-push-nightly-conformance should be stable

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by RamLavi** [comment]
reoccurred [today](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-push-nightly-conformance/1315479815947554816)
