### ISSUE TITLE
[Flaky CI] periodic-kubevirt-push-nightly-build-master fails

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#4346]
/kind bug

**What happened**:

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-push-nightly-build-master/1314733157118906368

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-push-nightly-build-master/1314370759082119168

```
2020/10/10 01:08:05 Error pushing image to kubevirtnightlybuilds/cdi-http-import-server:20201010_63d89b729: unable to push image to kubevirtnightlybuilds/cdi-http-import-server:20201010_63d89b729: Put https://index.docker.io/v2/kubevirtnightlybuilds/cdi-http-import-server/blobs/uploads/60f926bb-9b4f-4f8a-a02e-09df9fe32008?_state=......: EOF
Makefile:31: recipe for target 'bazel-push-images' failed
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
/close

Thanks for reporting. No issues since 10 days. Closing.

**Comment by oshoval** [comment]
/reopen 

Same EOF again
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-push-nightly-build-master/1328503862264336384
