### ISSUE TITLE
[Flaky CI] periodic-ci-kubevirt-kubevirt-release-0.33-e2e-periodic-azure-nested-virt fails to run tests

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#4347]
/kind bug

**What happened**:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-release-0.33-e2e-periodic-azure-nested-virt/1315125533490548736

All tests are failing because `Message: "configmaps \"kubevirt-config\" not found",`

**What you expected to happen**:
Should pass

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by RamLavi** [comment]
reoccurred. prow [link](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-release-0.33-e2e-periodic-azure-nested-virt/1315487924149555200)

**Comment by rmohr** [comment]
/assign @dhiller 

@dhiller this should now with the job rewrite be addressed, right?

**Comment by dhiller** [comment]
Yes, https://github.com/openshift/release/pull/12940 should fix it when ready.

**Comment by dhiller** [comment]
Reason for failing tests was that in the testing infra for master the `kubevirt-config.yaml` was missing which is required for v0.34.0.
