### ISSUE TITLE
[Flaky CI] Kubevirt-io-periodic-link-checker failure (root is not writable according logs)

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#4349]
/kind bug

**What happened**:
Kubevirt-io-periodic-link-checker fails directly after 7 seconds
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/kubevirt-io-periodic-link-checker/1314581145471422464

```
`/` is not writable.
Bundler will use `/tmp/bundler20201009-16-3kuqoq16' as your home directory temporarily.
Fetching source index from https://rubygems.org/
Retrying fetcher due to error (2/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (3/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Retrying fetcher due to error (4/4): Bundler::HTTPError Could not fetch specs from https://rubygems.org/
Could not fetch specs from https://rubygems.org/
```

**What you expected to happen**:
Should pass

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
/close

@oshoval that belongs to https://github.com/kubevirt/kubevirt.github.io. Would you mind opening an issue there?

**Comment by codificat** [comment]
Thanks @rmohr. 

@oshoval I believe this was already fixed and there's no need to open a new issue. Sorry I didn't notice this to close it earlier.
