### ISSUE TITLE
Align our code with go-client master branch

### ISSUE THREAD

**Issue by cynepco3hahue** [kubevirt/kubevirt#435]
Change of go-client version to master under `glide.yaml` will raise errors on the `make` stage.
```
# kubevirt.io/kubevirt/pkg/api/v1
api/v1/types.go:67: cannot use VM literal (type *VM) as type runtime.Object in argument to scheme.AddKnownTypes:
        *VM does not implement runtime.Object (missing DeepCopyObject method)
api/v1/types.go:68: cannot use VMList literal (type *VMList) as type runtime.Object in argument to scheme.AddKnownTypes:
        *VMList does not implement runtime.Object (missing DeepCopyObject method)
api/v1/types.go:71: cannot use Spice literal (type *Spice) as type runtime.Object in argument to scheme.AddKnownTypes:
        *Spice does not implement runtime.Object (missing DeepCopyObject method)
api/v1/types.go:72: cannot use Migration literal (type *Migration) as type runtime.Object in argument to scheme.AddKnownTypes:
        *Migration does not implement runtime.Object (missing DeepCopyObject method)
api/v1/types.go:73: cannot use MigrationList literal (type *MigrationList) as type runtime.Object in argument to scheme.AddKnownTypes:
        *MigrationList does not implement runtime.Object (missing DeepCopyObject method)
api/v1/types.go:85: unknown field 'ImportPrefix' in struct literal of type announced.GroupMetaFactoryArgs
api/v1/types.go:171: cannot use &vl.ListMeta (type *"kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ListMeta) as type "kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".List in return argument
api/v1/types.go:470: cannot use &ml.ListMeta (type *"kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".ListMeta) as type "kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/apis/meta/v1".List in return argument
```

**Comment by cynepco3hahue** [comment]
This issue prevents to use new features from `go-client`, for example, I can not use leader election code.

**Comment by cynepco3hahue** [comment]
I started digging into the code and looks like `kubernetes` uses some sort of code generation to generate deep copy [function](https://github.com/kubernetes/kubernetes/blob/master/staging/src/k8s.io/code-generator/cmd/deepcopy-gen/main.go), I already have some progress with this, but the question if we want to use the same approach as kubernetes does?

**Comment by rmohr** [comment]
@cynepco3hahue would be fine for me if you just use an introspecting cloner. On the long run generated mappers are probably better, since they are fast. Right now, something like that should be sufficient:

```go
func (in *VM) DeepCopyInto(out *VM) {
  out = model.Clone(in)
  return
}

func (in *VM) DeepCopy() *VM {
  out := new(VM)
  in.DeepCopyInto(out)
  return out
}
```

`model.Clone` is from [go-model](https://github.com/jeevatkm/go-model) which is already in use by us.

**Comment by cynepco3hahue** [comment]
@rmohr ok, so I will my code for the future, I already created some `Makefile` for file generation and it worked, but I stacked with `virt-handler/virtwrap/api/scema.go` I needed to add `runtime.NewSchemeBuilder` under the file, but we use our mapper so I had a problem with it.
