### ISSUE TITLE
[Flaky CI] periodic-ci-kubevirt-kubevirt-master-e2e-periodic-azure-nested-virt fails to run any test

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#4350]
/kind bug

**What happened**:

periodic-ci-kubevirt-kubevirt-master-e2e-periodic-azure-nested-virt fails to run any tests when it occurs.
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-master-e2e-periodic-azure-nested-virt/1315125533456994304

```
error: some steps failed:
  * could not run steps: step e2e-periodic-azure-nested-virt failed: template pod "e2e-periodic-azure-nested-virt" failed: the pod ci-op-45w3pjdk/e2e-periodic-azure-nested-virt failed after 1h11m14s (failed containers: test): ContainerFailed one or more containers exited

...

./hack/functests.sh: line 47: _out/tests/ginkgo: No such file or directory
```
and then it cant run tests at all.

**What you expected to happen**:
Should pass.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by RamLavi** [comment]
reoccurred. prow [link](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-master-e2e-periodic-azure-nested-virt/1315487924116000768)

**Comment by AlonaKaplan** [comment]
[same](https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-master-e2e-periodic-azure-nested-virt/1315850322362503168)

**Comment by ormergi** [comment]
Different than yesterday but similar to what this issue describes and[ two days ago](https://github.com/kubevirt/kubevirt/issues/4350#issuecomment-707049628) 
[link] (https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-master-e2e-periodic-azure-nested-virt/1316212634990678016)

**Comment by rmohr** [comment]
/assign @dhiller 

@dhiller this should now with the job rewrite be addressed, right?

**Comment by dhiller** [comment]
Yep, https://github.com/openshift/release/pull/12371 should have fixed it.
