### ISSUE TITLE
vm pod err after 13 minutes

### ISSUE THREAD

**Issue by lixiaobing1** [kubevirt/kubevirt#4358]
Is this a BUG REPORT or FEATURE REQUEST?:
/kind bug

What happened:
VM POD err after deploying 13 minites, virt-handler: failed to bindmount containerDisk containerdisk

{"component":"virt-handler","kind":"","level":"info","msg":"all containerdisks are ready","name":"testvm","namespace":"default","pos":"mount.go:367","timestamp":"2020-10-13T06:25:11.342880Z","uid":"736d8612-3aa8-40d6-8bbd-9ed3e40f4ef0"}
{"component":"virt-handler","kind":"","level":"info","msg":"Bind mounting container disk at /paasdata/docker/overlay2/4e59a66089cb2360266858a2734722beef05681a7eaad1c340ede964fb021acf/merged/disk/cirros.img to /var/lib/kubelet/pods/eb6fa840-1bcf-468e-baf1-4228352fd9c5/volumes/kubernetes.io~empty-dir/container-disks/disk_0.img","name":"testvm","namespace":"default","pos":"mount.go:252","timestamp":"2020-10-13T06:25:11.346301Z","uid":"736d8612-3aa8-40d6-8bbd-9ed3e40f4ef0"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"testvm","namespace":"default","pos":"vm.go:1334","reason":"failed to bindmount containerDisk containerdisk: Error: no such file or directory\nUsage:\n  virt-chroot mount [flags]\n\nFlags:\n  -h, --help             help for mount\n  -o, --options string   comma separated list of mount options\n  -t, --type string      fstype\n\nGlobal Flags:\n      --cpu uint32      cpu time in seconds for the process\n      --memory uint32   memory in megabyte for the process\n      --mount string    mount namespace to use\n      --user string     switch to this targetUser to e.g. drop privileges\n\nno such file or directory\n : exit status 1","timestamp":"2020-10-13T06:25:11.370199Z","uid":"736d8612-3aa8-40d6-8bbd-9ed3e40f4ef0"}

What you expected to happen:
POD running normally.

How to reproduce it (as minimally and precisely as possible):
Deploy with vm.yaml.

Anything else we need to know?:
no.

Environment:

KubeVirt version (use virtctl version): 0.33.0
Kubernetes version (use kubectl version): 1.17.9
VM or VMI specifications:
Cloud provider or hardware configuration:
OS (e.g. from /etc/os-release): centos 7
Kernel (e.g. uname -a): 3.10.0
Install tools:
Others:

**Comment by DanielQujun** [comment]
It might be your kubelet root directory has been changed.

Kubelet's pod root directory need be /var/lib/kubelet,  if it's not, `virt-handler` will complain `no such file or directory`

**Comment by lixiaobing1** [comment]
@DanielQujun, pod root path has been modified according real path.

**Comment by DanielQujun** [comment]
add  ` - --kubelet-pods-dir` in command:
```
      containers:
      - command:
        - virt-handler
        - --port
        - "8443"
        - --hostname-override
        - $(NODE_NAME)
        - --pod-ip-address
        - $(MY_POD_IP)
        - --max-metric-requests
        - "3"
        - --kubelet-pods-dir
        - /data/kubelet/pods  // your kubelet's pod directory
```
mountPath:
```
        - mountPath: /data/kubelet/pods // your kubelet's pod directory
          mountPropagation: Bidirectional
          name: kubelet-pods
```

volumes:
```
      - hostPath:
          path: /data/kubelet/pods // your kubelet's pod directory
          type: ""
        name: kubelet-pods-shortened
      - hostPath:
          path: /data/kubelet/pods // your kubelet's pod directory
          type: ""
        name: kubelet-pods
```

**Comment by lixiaobing1** [comment]
@DanielQujun thx, has been fixed :)
