### ISSUE TITLE
Cann't delete vmi testvm

### ISSUE THREAD

**Issue by lixiaobing1** [kubevirt/kubevirt#4359]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
 I want to delete vm:

$ virtctl stop testvm
$ kubectl delete vm testvm      

but vmis testvm left:

$ kubectl get vm
No resources found in default namespace.
$ kubectl get vmis
NAME     AGE    PHASE       IP    NODENAME
testvm   4h9m   Scheduled         172.20.0.2
$ kubectl get pod
No resources found in default namespace.

I delete with --force, but fail:

$ kubectl delete vmis testvm --force --grace-period=0
warning: Immediate deletion does not wait for confirmation that the running resource has been terminated. The resource may continue to run on the cluster indefinitely.
virtualmachineinstance.kubevirt.io "testvm" force deleted

$ kubectl get vmis
NAME     AGE    PHASE       IP    NODENAME
testvm   4h9m   Scheduled         172.20.0.2

**What you expected to happen**:
Delete vmis testvm.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy with vm.yaml, and stop and delete vm.

**Anything else we need to know?**:
no.

**Environment**:
- KubeVirt version (use `virtctl version`): 0.33.0
- Kubernetes version (use `kubectl version`): 1.17.9
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): centos 7
- Kernel (e.g. `uname -a`): 3.10.0
- Install tools:
- Others:

**Comment by DanielQujun** [comment]
maybe you can paste some `virt-controller`、`kube-controller`'s log, that would be helpful.

**Comment by lixiaobing1** [comment]
cc @DanielQujun

virt-handler: failed to bindmount containerDisk containerdisk

{"component":"virt-handler","kind":"","level":"info","msg":"all containerdisks are ready","name":"testvm","namespace":"default","pos":"mount.go:367","timestamp":"2020-10-13T06:25:11.342880Z","uid":"736d8612-3aa8-40d6-8bbd-9ed3e40f4ef0"}
{"component":"virt-handler","kind":"","level":"info","msg":"Bind mounting container disk at /paasdata/docker/overlay2/4e59a66089cb2360266858a2734722beef05681a7eaad1c340ede964fb021acf/merged/disk/cirros.img to /var/lib/kubelet/pods/eb6fa840-1bcf-468e-baf1-4228352fd9c5/volumes/kubernetes.io~empty-dir/container-disks/disk_0.img","name":"testvm","namespace":"default","pos":"mount.go:252","timestamp":"2020-10-13T06:25:11.346301Z","uid":"736d8612-3aa8-40d6-8bbd-9ed3e40f4ef0"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"testvm","namespace":"default","pos":"vm.go:1334","reason":"failed to bindmount containerDisk containerdisk: Error: no such file or directory\nUsage:\n virt-chroot mount [flags]\n\nFlags:\n -h, --help help for mount\n -o, --options string comma separated list of mount options\n -t, --type string fstype\n\nGlobal Flags:\n --cpu uint32 cpu time in seconds for the process\n --memory uint32 memory in megabyte for the process\n --mount string mount namespace to use\n --user string switch to this targetUser to e.g. drop privileges\n\nno such file or directory\n : exit status 1","timestamp":"2020-10-13T06:25:11.370199Z","uid":"736d8612-3aa8-40d6-8bbd-9ed3e40f4ef0"}

**Comment by lixiaobing1** [comment]
ok，the issue has been fixed with following command:
kubectl -n kubevirt patch kv kubevirt --type=json -p '[{ "op": "remove", "path": "/metadata/finalizers" }]'

**Comment by lixiaobing1** [comment]
ok，the issue has been fixed with following command:
kubectl -n kubevirt patch kv kubevirt --type=json -p '[{ "op": "remove", "path": "/metadata/finalizers" }]'
