### ISSUE TITLE
virt-handler fails to run if built on host with newer libvirt than its base image

### ISSUE THREAD

**Issue by nertpinx** [kubevirt/kubevirt#436]
When virt-handler is built, it's done agains the host's libvirt.so.  In case it is newer on the host than in the base image for virt-handler, the container fails to start with the following message (or similar, of course):

    /virt-handler: /lib64/libvirt.so.0: version `LIBVIRT_3.4.0' not found (required by /virt-handler)

In order to avoid this the virt-handler binary could be built inside the container.

**Comment by nertpinx** [comment]
Actually, we could have one image where everything gets built so that the environment is shared. That image could then be destroyed in order not to have the build time dependencies.

**Comment by rmohr** [comment]
@nertpinx Thanks for reporting that. Yes, building our go-code in a container sounds reasonable. Are you interested in comming up with a PR? 

Before libvirt-go was moved from the community repo https://github.com/rgbkrk/libvirt-go#version-support to the official libvirt repo, there was the possibility to specify via a build tag the compatibiliy you required. Moving back to something like this might also be something to investigate.

**Comment by nertpinx** [comment]
@rmohr I'd love to, but I'm not that familiar with the internals yet, so the research will take me some time. Specifying the tag might be an option, sure.  But that would solve only the libvirt issue, what if there are more similar things that will pop up later?  Also you have to keep the build tags updated manually.  I'll first look into building in a container.

**Comment by nertpinx** [comment]
Some more thoughts on this. We can do this either with docker or vagrant. With vagrant it would be nicer to have that in the global Vagrantfile and maybe a teeny tiny bit nicer to manage. It would be easy to copy files in/out with 9p, but I'm not sure we can require that. With docker it would use the same precise image that's used (without needing to manually synchronize the image name between Dockerfiles and Vagrantfile and easier to copy files in/out without any extra prerequisites. Possible combination would be vagrant with the docker provider which could leverage the good from both worlds, but I've never tried that.  I'll see what I can do when I scrape some free time and report my findings here.  Let me know in the meantime in case there's a better way or if you have some preferences.

**Comment by rmohr** [comment]
Still not completely developer-friendly, since one has to update 2-3 locations in our Dockerfiles to make sure that everything uses the same libvirt version, but we are not using the host libvirt-devel version anymore. CI will catch incompatibilities. Fixed by #647.
