### ISSUE TITLE
spec.domain.devices.interfaces.tftpServerName in body is a forbidden property

### ISSUE THREAD

**Issue by sanzende** [kubevirt/kubevirt#4381]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

**What happened**:
I am trying to PXE boot using the spec 'spec.domain.devices.interfaces.tftpServerName' in the VM yaml file. 

I am trying to use similar to snippet below in my yaml file.  I provide the TFTP server IP address and grubx64.efi file to bootFileName. 
-------------------------------------------------------------------------------------
https://kubevirt.io/user-guide/#/creation/interfaces-and-networks
-------------------------------------------------------------------------------------
    devices:
      interfaces:
        - name: default
          masquerade: {}
          bootFileName: default_image.bin
          tftpServerName: tftp.example.com
          bootOrder: 1   # attempt to boot from an external tftp server
--------------------------------------------------------------------------------------

but I am getting error the spec 'spec.domain.devices.interfaces.tftpServerName' and 'spec.domain.devices.interfaces.bootFileName' 

The request is invalid: 
* : spec.domain.devices.interfaces.tftpServerName in body is a forbidden property
* : spec.domain.devices.interfaces.bootFileName in body is a forbidden property

**What you expected to happen**:

I expected VM to pxe boot using the boot files saved at /var/lib/tftpboot/ on the tftp server.

**How to reproduce it (as minimally and precisely as possible)**:
1) Configure TFTP server to serve OS images and boot file.
2) Add the section in the VM spec file with the appropriate values.
-------------------------------------------------------------------------------------
    devices:
      interfaces:
        - name: default
          masquerade: {}
          bootFileName: default_image.bin
          tftpServerName: tftp.example.com
          bootOrder: 1   # attempt to boot from an external tftp server
--------------------------------------------------------------------------------------
3) Try to apply the spec file. 
    $ kubectl apply -f vm.yaml

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
Not using virctl as PXE booting.
- Kubernetes version (use `kubectl version`):
v1.16.8
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Centos 7.6
- Kernel (e.g. `uname -a`): 3.10.0-957.el7.x86_64
- Install tools:
- Others:

**Comment by rmohr** [comment]
@sanzende thank you for the report. It seems like our user-guide is not accurate here. I think it should look like this:


```
devices:
  interfaces:
    - name: default
      masquerade: {}
      bootOrder: 1   # attempt to boot from an external tftp server
      dhcpOptions:     
        bootFileName: default_image.bin
        tftpServerName: tftp.example.com
```

Note the `dhcpOptions` subsection.

**Comment by sanzende** [comment]
Thanks much Roman. It indeed moved forward and I do not see this forbidden error but in the config setup of ipxe client I can see the bootfilename that I mentioned in the spec file but I do not see the value of tftpservername in the next-server details in the ipxe config.

**Comment by rmohr** [comment]
Could you execute commands similar to what we do in this test to check the dhcp offer from inside your guest: https://github.com/kubevirt/kubevirt/blob/38cacd56078e1946536d5a217c3e624113458d44/tests/vmi_networking_test.go#L554 and check if the tftp server is offered?
