### ISSUE TITLE
JUnit file merging failed

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#4385]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:

The merging of the Junit files failed, seemingly to a test executed multiple times: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4341/pull-kubevirt-e2e-k8s-1.19/1318155069882896384

**What you expected to happen**:

Merging should not fail. Tests should not get executed multiple times. I suppose that the separation of the tests actually works, so maybe this is a hint that there's a bug lurking in the merge logic.

/cc @rmohr 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Looks like this is a new test from PR #4341 https://github.com/kubevirt/kubevirt/pull/4341/files#diff-f2964358d14f79c439288df507310df44dbc0de205c1ec0a02a78f9d4cbe7c13R168

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dhiller** [comment]
Looks like this is a new test from PR #4341 https://github.com/kubevirt/kubevirt/pull/4341/files#diff-f2964358d14f79c439288df507310df44dbc0de205c1ec0a02a78f9d4cbe7c13R168

/cc @alonSadan

**Comment by alonSadan** [comment]
In my case it was because the string I provided for the two cases in the table was identical, so it thought it ran two identical tests.

@dhiller should this remain open?

**Comment by rmohr** [comment]
> In my case it was because the string I provided for the two cases in the table was identical, so it thought it ran two identical tests.
> 
> @dhiller should this remain open?

/close

Perfect. So it worked like expected.
