### ISSUE TITLE
scope and implement Kubevirt extension process

### ISSUE THREAD

**Issue by mpolednik** [kubevirt/kubevirt#440]
Looking over github, meeting notes and emails, the general consensus seems to be that some features are great for kubevirt as `extensions`. These features (most likely controllers, admission controllers, standalone services) will need a place to live - hosting some of these on personal github works, but it also makes sense to have official extensions.

What is currently missing from the idea of extensibility:

1. Documentation. The process of writing an extension, available extension points must be documented (preferably incl. examples). We also need to outline the steps required to make an extension official (under k6t umbrella).
2. Extension points(?). Admission controllers need an easy way to hook into k6t runtime. The build process could allow extension to be built and deployed somehow easily (or keep build separate but `make vagrant-deploy --extend manifest.yaml or similar).
3. Store for official extensions. We want to keep the code out of kubevirt/kubevirt repo, so do we allocate repo for each extension? Or a single repo with all the extensions that can be built and deployed selectively?
4. Terminology. `Addon` or `Extension` - we need to agree on one of the terms to avoid confusion in future.

Any ideas what else we need? Opinions on how to implement various points are welcome, the extension proposal document will be based on feedback in this issue.

**Comment by michalskrivanek** [comment]
Not sure if extension or addon is a good name, I think these are going to be simply "other things" which together form a useful deployment. The current core kubevirt is just a part of that. I wonder if it should have any name vs renaming the current code to kubevirt-core and just create additional sub projects

**Comment by fabiand** [comment]
We don#t go into this formalization process for now.
