### ISSUE TITLE
[Serial]VirtualMachineSnapshot Tests rook-ceph With more complicated VM VM should contain snapshot status for all volumes

### ISSUE THREAD

**Issue by arnongilboa** [kubevirt/kubevirt#4401]
/kind bug
/triage build-watcher

**What happened**:

```
[Serial]VirtualMachineSnapshot Tests rook-ceph With more complicated VM VM should contain snapshot status for all volumes
tests/snapshot_test.go:226
```
Found [here](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/2935/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1319214174789701633)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
/close

@arnongilboa thanks for creating this. All the tests in  this job failed due to the same reason. Consolidating this in one #4406.
