### ISSUE TITLE
[Serial]VirtualMachineRestore Tests rook-ceph With a more complicated VM should restore a vm with containerdisk and blank datavolume

### ISSUE THREAD

**Issue by arnongilboa** [kubevirt/kubevirt#4404]
/kind bug
/triage build-watcher

**What happened**:
```
tests/restore_test.go:682
Timed out after 180.000s.
Expected
    <bool>: false
to be true
tests/restore_test.go:80
```

Found [here](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4396/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1319171768790814720)
 
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
/close

@arnongilboa thanks for creating this. All the tests in  this job failed due to the same reason. Consolidating this in one #4406.
