### ISSUE TITLE
[Metrics] The unit of some block metrics seems not accurate

### ISSUE THREAD

**Issue by DanielQujun** [kubevirt/kubevirt#4411]
I notice the metrics `kubevirt_vmi_storage_times_ms_total ` value is a very big number, then I check the doc of  libvirt.org, find the description which the time unit is `ns`:
```
  "block.<num>.rd.times" - total time (ns) spent on reads as
                           unsigned long long.
```
https://libvirt.org/html/libvirt-libvirt-domain.html#VIR_DOMAIN_STATS_BLOCK

**Comment by DanielQujun** [comment]
@ArthurSens  HI, would you pls take a look?

**Comment by ArthurSens** [comment]
Thanks for finding that, I'll submit a PR changing the metric name.

But I'm wondering if we'd like to follow[ Prometheus best practices](https://prometheus.io/docs/practices/naming/#base-units) about time units, which would be in seconds. Do we really need time metrics to so precise?

WDYT @sradco?
