### ISSUE TITLE
how to reduce size of kubevirt component images?

### ISSUE THREAD

**Issue by lixiaobing1** [kubevirt/kubevirt#4423]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind enhancement

**What happened**:
The size of kubevirt component images is so large:
virt-operator 425M
virt-api 387M
virt-controller 388M
virt-handler 780M
virt-launcher 745M
cirros-registry-disk-demo 202M

there are two problems:
(1) where is the dockerfile of every component, I only find a dockerfile in hack/builder.
(2) how to reduce the size of images?

**What you expected to happen**:
Reduce size of every image to less than 100M.

**How to reproduce it (as minimally and precisely as possible)**:
Docker pull from dockerhub.

**Anything else we need to know?**:
no.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.33.0
- Kubernetes version (use `kubectl version`):1.17.9
- VM or VMI specifications:no
- Cloud provider or hardware configuration:no
- OS (e.g. from /etc/os-release):centos
- Kernel (e.g. `uname -a`):3.10.0
- Install tools:no
- Others:no

**Comment by awels** [comment]
KubeVirt uses bazel to build the images. So you won't find any Dockerfiles, except the Dockerfile for the builder image.

**Comment by davidvossel** [comment]
look at the BUILD.bazel  files for each component. For example, virt-handler's is ````cmd/virt-handler/BUILD.bazel```. the container_image section in there defines how the containers are built with bazel
