### ISSUE TITLE
Update to latest AV-8.2 libvirt version.

### ISSUE THREAD

**Issue by awels** [kubevirt/kubevirt#4431]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
When attempting to manually hotplug a disk I created in the virt-launcher container, I get the following error:
error: Failed to attach disk
error: Unable to get devmapper targets for /tmp/test_disk.img: Success

**What you expected to happen**:
Successfully hotplug the disk into the running VM.

**How to reproduce it (as minimally and precisely as possible)**:
Start a VM with a hotplug capable OS in it, for instance fedora (not really needed to reproduce, but if it work, the disk would show up in the guest)
kubectl apply -f examples/vmi-fedora.yaml
exec into the virt-launcher pod, and run:
qemu-img create -f raw /tmp/disk.img 1G
This will create a 1G disk image in /tmp.
Now run virsh
virsh # attach-disk default_vmi-fedora /tmp/disk.img --target=vdc
error: Failed to attach disk
error: Unable to get devmapper targets for /tmp/disk.img: Operation not permitted

**Anything else we need to know?**:
Supposedly this is fixed in AV-8.2.1, however KubeVirt does not seem to be using this particular version yet.

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by awels** [comment]
@stu-gott Something for you?

**Comment by vladikr** [comment]
Hopefully, https://github.com/kubevirt/kubevirt/pull/4408 will get you to the relevant version.
