### ISSUE TITLE
[Flaky CI] Sriov lane flaky tests 3956, 3957

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#4432]
/kind bug

**What happened**:
Tests 3956, 3957 might flake with the error (one of the those tests use same flow but ipv4)
```
error: ping -6 fc00::2 -c 1 -w 5 failed
```
I investigated it and saw the IP disappers from the VM after around 1 minute,
the reason is how we configure the ips with nmcli.

saw it for example 2 of 3 here.
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4424/pull-kubevirt-e2e-kind-1.17-sriov/1320997424440807424

possible solutions:
1. install NetworkManager-config-server in the VM, preferably by customizing the image.
2. use the right set of nmcli commands.

**What you expected to happen**:
Should be stable, at least the ip in the machine, and afterwards see what is the status.

**How to reproduce it (as minimally and precisely as possible)**:
Wait a bit and the ip would be gone and then try to ping

**Anything else we need to know?**:
Let #4001 be merged first to fix other issue of those tests.

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ormergi** [comment]
Note that this is not a problem with the CI so you can remove `Flacy CI` prefix

**Comment by oshoval** [comment]
> Note that this is not a problem with the CI so you can remove `Flaky CI` prefix

its a lane that will now run on CI, ether manually or automatic, so i think it should be there.

**Comment by ormergi** [comment]
Its a problem in the tests code just saying

**Comment by oshoval** [comment]
> Its a problem in the tests code just saying

check please and see Flaky CI is all about flaky test, either because the tests or the kubevirt core

**Comment by ormergi** [comment]
You can check and see there are issues that stats with "Flaky test"

**Comment by oshoval** [comment]
> You can check and see there are issues that stats with "Flaky test"

Most of the [Flaky CI] use [Flaky CI],
This is the right convention.
As without it the CI would be flaky.

**Comment by ormergi** [comment]
Those are issus that reports tests that are flaky, that this issue describe their possible solution.

**Comment by oshoval** [comment]
> Those issues that I mention just reports tests that are flaky.
> This issue suggests a solution for those tests and this issue should be mentioned there.

No, this issue suggested a solution to other problem , not the 15 seconds.

**Comment by alonSadan** [comment]
> Wait a bit and the ip would be gone and then try to ping

can you elaborate on how long to wait? is it in seconds/minutes ? don't have to be exact...

**Comment by oshoval** [comment]
> > Wait a bit and the ip would be gone and then try to ping
> 
> can you elaborate on how long to wait? is it in seconds/minutes ? don't have to be exact...

It varies around up to minute or 2 lets say,
you can Sleep in the code directly after you set the IP, and console the machine, 
do some "ip address" and you will see it always after this time.
