### ISSUE TITLE
Disk image files are being created for Virtio-FS mounted volumes

### ISSUE THREAD

**Issue by salanki** [kubevirt/kubevirt#4440]
/kind bug

**What happened**:
https://github.com/kubevirt/kubevirt/blob/2ae3155b63d3667bca960c27f2ef55e1cfd715f6/pkg/host-disk/host-disk.go creates a disk image for every mounted disk. When using Virtio-FS and mounting in a PVC to be mapped as a filesystem, a disk image should not be created.

**What you expected to happen**:
No disk image should be created on volumes used as filesystems.

**How to reproduce it (as minimally and precisely as possible)**:
Create a VM as detailed in the Virtio-FS issue: https://github.com/kubevirt/kubevirt/pull/3493

**Anything else we need to know?**:
This fixed it. PR coming: https://github.com/salanki/kubevirt/commit/35d370fc1ef99ee420728716e3977f65735f4d32

**Environment**:
- KubeVirt version (use `virtctl version`): master

**Comment by rmohr** [comment]
/assign @vladikr

I think that this alpha feature only works with configmaps and secrets right now.

**Comment by salanki** [comment]
The fix for this issue that I linked works well. I will PR it as soon as I find some time.

**Comment by vladikr** [comment]
> I think that this alpha feature only works with configmaps and secrets right now.

afaik, it should work well with NFS and we are currently testing this with a data volume.
For host-disk specifically, there is an issue I think...

**Comment by vladikr** [comment]
> The fix for this issue that I linked works well. I will PR it as soon as I find some time.

Thanks! I'll take a look.

**Comment by salanki** [comment]
The issue for me arose with `PersistentVolumeClaims` from CEPH.

**Comment by vladikr** [comment]
> The issue for me arose with `PersistentVolumeClaims` from CEPH.

hmm, ok, I don't seem to follow then. Let me reproduce this.

**Comment by salanki** [comment]
`host-disk.go` assumes that all PVCs mounted into the Pod will be used to mount a Block Volume to the VM. Therefor it converts the PVCs to a `HostDisk` and later on creates a `disk.img` in there. My fix checks to see if the PVC is used in a `Filesystem`. If it is, it does not convert it to a `HostDisk` and no disk image is created.

**Comment by vladikr** [comment]
@salanki thanks, for the reminder. I hope we will get to sort this issue this week.
