### ISSUE TITLE
[featrue] Support VNC share between sessions

### ISSUE THREAD

**Issue by DanielQujun** [kubevirt/kubevirt#4441]
I notice that we only support one VNC connection per VM.

https://github.com/kubevirt/kubevirt/blob/6014b6954e613f5f296c6545487d8a15b1a0faac/pkg/virt-handler/rest/console.go#L103-L110

AFAIK, VM's VNC could share between sessions, it's also the default behavior in Openstack\Proxmox VE. 

Do we concern about the sharing VNC may bring risks or are there some limits that we can't share it?

I modified some code, and add `sharePolicy` for the VNC socket[0], It seems to work fine. If we have a plan to extend the VNC options, I would like hands up to take it.

[0]. https://libvirt.org/formatdomain.html

**Comment by DanielQujun** [comment]
@rmohr Hi, what do you think?

**Comment by rmohr** [comment]
Nice. I don't think that anything speaks against this in general. Just two points:

 1) The connections go through the k8s apiserver, so this can have influence on the apiserver performance
 2) We only have VNC basically as admin/support access, not for remote desktop (therefore also the hardcoded low resolution).

**Comment by rmohr** [comment]
This may actually be helpful for one  feature I would want to add, which is creating screensots of VMs without having VNC clients present. Mostly for debugging purposes to automatically create a screenshot somewhere in e.g. CI systems.

**Comment by DanielQujun** [comment]
you're right, Web VNC is truly not user friendly, right now I'm facing a mouse offset issue even I had added a USB tablet device for the WIN7 VM.  curiously, the same VMI config for Windows 2019 is OK :flushed: 

I'll keep this issue open, in case maybe someone needs it.

**Comment by dimm0** [comment]
Any way to enable shared?

**Comment by rmohr** [comment]
> Any way to enable shared?

No, still no way. What is your use-case?

**Comment by dimm0** [comment]
Need to provide a Windows VM with GPUs to university faculty and students for teaching and research
