### ISSUE TITLE
[Flaky CI] [Serial]SRIOV VirtualMachineInstance with sriov plugin interface - multiple tests

### ISSUE THREAD

**Issue by akrejcir** [kubevirt/kubevirt#4457]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/triage build-watcher

**What happened**:
These 3 tests failed:

- `[Serial]SRIOV VirtualMachineInstance with sriov plugin interface [test_id:3956]should connect to another machine with sriov interface over IPv4`
```
tests/vmi_multus_test.go:869
Expected success, but got an error:
    <*errors.errorString | 0xc000ace0d0>: {
        s: "Failed to ping VMI testvmidht8nwl8wwxn6n5mwbwc6ngcqskhrblsrw2g9vctptclk2wz, error: Failed to run [ping 192.168.1.2 -c 1 -w 5] at VMI testvmidht8nwl8wwxn6n5mwbwc6ngcqskhrblsrw2g9vctptclk2wz, error: ping 192.168.1.2 -c 1 -w 5 failed",
    }
    Failed to ping VMI testvmidht8nwl8wwxn6n5mwbwc6ngcqskhrblsrw2g9vctptclk2wz, error: Failed to run [ping 192.168.1.2 -c 1 -w 5] at VMI testvmidht8nwl8wwxn6n5mwbwc6ngcqskhrblsrw2g9vctptclk2wz, error: ping 192.168.1.2 -c 1 -w 5 failed
tests/vmi_multus_test.go:865
```

- `[Serial]SRIOV VirtualMachineInstance with sriov plugin interface [test_id:3957]should connect to another machine with sriov interface over IPv6`
```
tests/vmi_multus_test.go:873
Expected success, but got an error:
    <*errors.errorString | 0xc0025a5030>: {
        s: "Failed to ping VMI testvmi9lzn66wssfp92nhj95pcnkwmcv25ct6k6fwqpg8f8grq7h26, error: Failed to run [ping -6 fc00::2 -c 1 -w 5] at VMI testvmi9lzn66wssfp92nhj95pcnkwmcv25ct6k6fwqpg8f8grq7h26, error: ping -6 fc00::2 -c 1 -w 5 failed",
    }
    Failed to ping VMI testvmi9lzn66wssfp92nhj95pcnkwmcv25ct6k6fwqpg8f8grq7h26, error: Failed to run [ping -6 fc00::2 -c 1 -w 5] at VMI testvmi9lzn66wssfp92nhj95pcnkwmcv25ct6k6fwqpg8f8grq7h26, error: ping -6 fc00::2 -c 1 -w 5 failed
tests/vmi_multus_test.go:865
```

- `[Serial]SRIOV VirtualMachineInstance with sriov plugin interface [test_id:3985]should create a virtual machine with sriov interface with custom MAC address`
```
tests/vmi_multus_test.go:789
MAC "de:ad:00:00:be:ef" was not found in the VMI testvmiskmw6972j7pzpkq8vzp5h4tms8tmlncd6fdkqmsqts2fwtxn within the given timeout
Unexpected error:
    <expect.TimeoutError>: 15000000000
    expect: timer expired after 15 seconds
occurred
tests/vmi_multus_test.go:1065
```

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4415/pull-kubevirt-e2e-kind-1.17-sriov/1321724193020055552

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4415/pull-kubevirt-e2e-kind-1.17-sriov/1321579487917248512

**Comment by oshoval** [comment]
Thanks, duplicates of https://github.com/kubevirt/kubevirt/issues/4432
and https://github.com/kubevirt/kubevirt/issues/3840
