### ISSUE TITLE
where's the source code of kubevirt/virtio-container-disk

### ISSUE THREAD

**Issue by npu21** [kubevirt/kubevirt#4461]
maybe not the right place, but dose anyone know where's the source code of kubevirt/virtio-container-disk?
Thanks!

**Comment by rmohr** [comment]
We just download the virtio iso for windows with this definition here: https://github.com/kubevirt/kubevirt/blob/master/WORKSPACE#L153 and we put it with the right file permissions into a tar: https://github.com/kubevirt/kubevirt/blob/cf2849c413530fc0bf65886e06ca76a36d717874/containerimages/BUILD.bazel#L106 and this tar is finally an image layer here: https://github.com/kubevirt/kubevirt/blob/cf2849c413530fc0bf65886e06ca76a36d717874/containerimages/BUILD.bazel#L114


You can do something similar with a Dockerfile, following our `containerDisk` example here: https://kubevirt.io/user-guide/#/creation/disks-and-volumes?id=containerdisk-workflow-example

**Comment by npu21** [comment]
Great,thanks!

**Comment by rmohr** [comment]
/close

Feel free to reopen if you have further questions.
