### ISSUE TITLE
how to add my private registry's certificate during build ?

### ISSUE THREAD

**Issue by todaygood** [kubevirt/kubevirt#4467]
> /kind enhancement

**What happened**:
I build kubevirt from source code and push image to my private registry "registry.abc.com", then report an error:
```
2020/11/01 03:24:36 Error pushing image to registry.abc.com/kubevirt/fedora-cloud-container-disk-demo:0.34.0.001: unable to push image to registry.abc.com/kubevirt/fedora-cloud-container-disk-demo:0.34.0.001: Get https://registry.abc.com/v2/: net/http: TLS handshake timeout
2020/11/01 03:24:36 Error pushing image to registry.abc.com/kubevirt/cirros-custom-container-disk-demo:0.34.0.001: unable to push image to registry.abc.com/kubevirt/cirros-custom-container-disk-demo:0.34.0.001: Get https://registry.abc.com/v2/: net/http: TLS handshake timeout
+ finish
+ docker stop e6bd31e51a667feb1aac55e9faa22fde9d9a58bbf002c26e87286cd00439c3a0
make: *** [bazel-push-images] Error 1
+ docker rm -f e6bd31e51a667feb1aac55e9faa22fde9d9a58bbf002c26e87286cd00439c3a0
```
**What you expected to happen**:
no error , I want to know how to add  certificate during build . 

**Environment**:
- KubeVirt version (use `virtctl version`): 0.34
- Kubernetes version (use `kubectl version`): 1.15.4

**Comment by rmohr** [comment]
You can tell our build environment where they are located via an environment variable. I never used it, but here the PR which implemented it: https://github.com/kubevirt/kubevirt/pull/3217.

**Comment by todaygood** [comment]
yes, I have noticed the PR,  first push successfully by use the env variable , but push failed after I changed docker tag enrionment variable. it reported error as following.

```
INFO: Analyzed target //:push-other-images (0 packages loaded, 10856 targets configured).
INFO: Found 1 target...
Target //:push-other-images up-to-date:
  bazel-bin/push-other-images
INFO: Elapsed time: 5.147s, Critical Path: 0.26s
INFO: 0 processes.
INFO: Build completed successfully, 1 total action
INFO: Build completed successfully, 1 total action
2020/11/04 02:52:31 Error pushing image to registry.abc.com/kubevirt/virtio-container-disk:0.34.0.002: unable to push image to registry.abc.com/kubevirt/virtio-container-disk:0.34.0.002: Get https://registry.abc.com/v2/: x509: certificate signed by unknown authority
2020/11/04 02:52:31 Error pushing image to registry.abc.com/kubevirt/disks-images-provider:0.34.0.002: unable to push image to registry.abc.com/kubevirt/disks-images-provider:0.34.0.002: Get https://registry.abc.com/v2/: x509: certificate signed by unknown authority
```

**Comment by todaygood** [comment]
I found the root cause  during the build and push image to registry about above issue.   I think It is a bug.

now usual procession is :
1. make build 
2. make push 

during "make build " , hack/dockerize script run "kubevirt-bazel-server"  container  ,but didn't mount DOCKER_CA_CERT_FILE  volume,then "make push " , kubevirt-bazel-server didn't delete and continue to be used though defined DOCKER_CA_CERT_FILE envionment variable .

**Comment by rmohr** [comment]
> I found the root cause during the build and push image to registry about above issue. I think It is a bug.

That can be. I think we would have to watch for  changes in `DOCKER_CA_CERT_FILE` and restart our bazel server to get the new mounts added.

**Comment by nishyt** [comment]
@rmohr @todaygood. I kind of stumbled upon the similar problem where running `make cluster-sync` gave me the following error:
```
Events:
  Type     Reason     Age                From               Message
  ----     ------     ----               ----               -------
  Normal   Scheduled  83s                default-scheduler  Successfully assigned kubevirt/virt-operator-5bc8f5cf8-kqxj9 to node01
  Normal   BackOff    19s (x4 over 81s)  kubelet            Back-off pulling image "amr-registry.test.com/myrepo/virt-operator@sha256:229db6937c366a554d95e4d99e764c8b7080388868ac93ba71b6ed8ba65c3bf6"
  Warning  Failed     19s (x4 over 81s)  kubelet            Error: ImagePullBackOff
  Normal   Pulling    4s (x4 over 82s)   kubelet            Pulling image "amr-registry.test.com/myrepo/virt-operator@sha256:229db6937c366a554d95e4d99e764c8b7080388868ac93ba71b6ed8ba65c3bf6"
  Warning  Failed     4s (x4 over 82s)   kubelet            Failed to pull image "amr-registry.test.com/myrepo/virt-operator@sha256:229db6937c366a554d95e4d99e764c8b7080388868ac93ba71b6ed8ba65c3bf6": rpc error: code = Unknown desc = error pinging docker registry amr-registry.test.com: Get "https://amr-registry.test.com/v2/": x509: certificate signed by unknown authority
  Warning  Failed     4s (x4 over 82s)   kubelet            Error: ErrImagePull
```

**The way to fix this is to ssh into the node** 
`./cluster-up/ssh.sh node01`

**switch to a root user** 
`sudo -i
`
NOTE: 
```
Docker does have an additional location you can use to trust individual registry server CA. You can place the CA cert inside /etc/docker/certs.d/<docker registry>/ca.crt. Include the port number if you specify that in the image tag, e.g in Linux.
```
**Create additional cert location for docker**
`mkdir -p /etc/docker/certs.d/amr-registry.test.com`

**place your private registry CA cert inside the above created directory. For example**
`/etc/docker/certs.d/amr-registry.test.com/custom-ca.crt`

Now it should start pulling the images from your registry or just simply trigger` make cluster-sync`

Moreover you can also pull all the required images beforehand on the node but for that make sure your custom-ca.cert is available at:  (you might need to create the directory structure)
- /etc/pki/ca-trust/source/anchors/custom-ca.crt
- /usr/local/share/ca-certificates/custom-ca.crt/

and the run` /usr/bin/update-ca-trust`
