### ISSUE TITLE
[Flaky CI] All SRIOV tests fail due to UpdateCDIConfigMap empty resource panic

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#4468]
/kind bug

**What happened**:

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4335/pull-kubevirt-e2e-kind-1.17-sriov/1322813869676040192

Fails also on clean master
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4469/pull-kubevirt-e2e-kind-1.17-sriov/1322844949380599808

All tests failing, panic on 
```
tests/utils.go:3100
Test Panicked
tests/utils.go:1737

Panic: resource name may not be empty

Full stack:
kubevirt.io/kubevirt/tests.PanicOnError(...)
	tests/utils.go:1737
kubevirt.io/kubevirt/tests.UpdateCDIConfigMap(0xc00012d180, 0x0)
	tests/utils.go:4299 +0x6cd
kubevirt.io/kubevirt/tests.resetToDefaultConfig()
	tests/utils.go:4333 +0x77
kubevirt.io/kubevirt/tests.BeforeTestCleanup()
	tests/utils.go:573 +0x77
kubevirt.io/kubevirt/tests_test.glob..func40.1()
	tests/vmi_multus_test.go:586 +0xbe
kubevirt.io/kubevirt/tests.BeforeAll.func1()
	tests/utils.go:3102 +0x40
kubevirt.io/kubevirt/tests_test.TestTests(0xc0038df700)
	tests/tests_suite_test.go:63 +0x2e1
testing.tRunner(0xc0038df700, 0x22c7720)
	GOROOT/src/testing/testing.go:909 +0xc9
created by testing.(*T).Run
	GOROOT/src/testing/testing.go:960 +0x350
```

**What you expected to happen**:
Should be stable

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by oshoval** [comment]
Trying to investigate, maybe just because the InsecureRegistry was removed from SRIOV provider

**Comment by ormergi** [comment]
On SRIOV lane we do not deploy cdi operator at all, the panic occurs on this line https://github.com/kubevirt/kubevirt/blob/master/tests/utils.go#L4299

**Comment by oshoval** [comment]
> On SRIOV lane we do not deploy cdi operator at all, the panic occurs on this line https://github.com/kubevirt/kubevirt/blob/master/tests/utils.go#L4299

Thanks, i know, i already fixed it, see PR above please.
