### ISSUE TITLE
How to identify a VM running pod?

### ISSUE THREAD

**Issue by jniederm** [kubevirt/kubevirt#448]
Please add reliable way to identify pods that are actually running the VMs (i.e. virt-launcher-* pods).

Currently  AFAIK it can only be done by parsing container name or tag `kubevirt.io/app=virt-launcher`.

I general it would be nice to have a way to reliably recognize various parts of KubeVirt (virt-handler, virt-launcher, libvirt, ... pods) on API level for troubleshooting and UI purposes.

**Comment by MarSik** [comment]
Roman mentioned today the kubevirt.io/domain tag that matches the VM name.

**Comment by jniederm** [comment]
Ok. So @rmohr is `kubevirt.io/domain` tag stable enough to by used by other systems? If yes we can close this issue I guess.

**Comment by rmohr** [comment]
@jniederm it is possible that we will rename it to `kubevirt.io/vm`, which I think makes more sense. Apart from that, there will always be such a label.

**Comment by jniederm** [comment]
Thanks.

Just a recap: pod running a VM is identified by tag `kubevirt.io/domain` which is expected to be renamed to `kubevirt.io/vm`.
