### ISSUE TITLE
How to reliably identify pod hosting a VM?

### ISSUE THREAD

**Issue by jniederm** [kubevirt/kubevirt#449]
Please add a reliable way to identify a pod hosting a running VM.

AFAIK it can only be done by examining tag value of `kubevirt.io/nodeName`.

This can be helpful for creating UI allowing to jump from from a VM to related pod / node / containers.

Similar to #448.

**Comment by rmohr** [comment]
@jniederm do you mean how to realiably identify the `node` or the `pod`?

**Comment by rmohr** [comment]
I guess you mean the node. So yes, to watch/filter for VMs which run on a specific node, you can use the `kubevirt.io/nodeName` label. Our controllers also rely on it. The node is also  reflected in the `status.nodeName` field, however, we currently used CustomResourceDefinitions, and they don't support field selectors, so you can only do host-side filtering based on the labels.

**Comment by jniederm** [comment]
I really meant pod. I'd like to use that in UI for user to be able to jump from a VM to related pod, mostly for troubleshooting purposes.

I guess knowing pod -> domainName mapping is not enough since (libvirt) domain name may not always match vm name, right?

**Comment by fabiand** [comment]
That reminds me a tiny little bit of the ownership topic. But also of that we could define a set of labels identifying each component in KubeVirt. And this further brings me to the question how we document this kind of stuff, @rmohr

**Comment by rmohr** [comment]
@jniederm I still don't fully understand what you want to do. Do you want to correlate which Pod belongs to  a VM by comparing it with fetching infos about running VMs from libvirt itself?

**Comment by jniederm** [comment]
Based on IRC conversation with @rmohr: value of `kubevirt.io/domain` (which is going to be renamed to ` kubevirt.io/vm`) corresponds to name of `VM` resource that runs in the pod.
