### ISSUE TITLE
[Flaky CI] [test_id:3985]should create a virtual machine with sriov interface with custom MAC address

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#4490]
/kind bug

**What happened**:

https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4463/pull-kubevirt-e2e-kind-1.17-sriov/1323866556106543104

```
tests/vmi_multus_test.go:789
Unexpected error:
    <*errors.errorString | 0xc002bdef30>: {
        s: "could not get sriov interface by MAC: no interface on VMI testvmihx92cqktrhljjfqppxdppcfmg6khzl8wzkvvx82g9npqdcck with MAC de:ad:00:00:be:ef",
    }
    could not get sriov interface by MAC: no interface on VMI testvmihx92cqktrhljjfqppxdppcfmg6khzl8wzkvvx82g9npqdcck with MAC de:ad:00:00:be:ef
occurred
tests/vmi_multus_test.go:801
```

**What you expected to happen**:
Should pass

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
https://github.com/kubevirt/kubevirt/pull/4511 fixes it.

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by oshoval** [comment]
@ormergi FYI, if you see the error mentioned in the description (i saw it on CI and locally), i fixed it on the mentioned PR.

**Comment by maya-r** [comment]
/triage build-watcher
(sorry for the noise, I just want to make sure it's easy to search for non-flakiness issues)
