### ISSUE TITLE
 virtualmachine-controller  Error creating pod: Pod ,spec.affinity.nodeAffinity error

### ISSUE THREAD

**Issue by piwenzi** [kubevirt/kubevirt#4508]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
when i create vmi
root@miaoyun-node-4:~# kubectl get vmi
NAME       AGE   PHASE     IP    NODENAME
vm-win10   19m   Pending         
root@miaoyun-node-4:~# kubectl describe vmi/vm-win10
Name:         vm-win10
Events:
  Type     Reason        Age               From                       Message
  ----     ------        ----              ----                       -------
  Warning  FailedCreate  19m               virtualmachine-controller  Error creating pod: Pod "virt-launcher-vm-win10-b8lgk" is invalid: spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'
  Warning  FailedCreate  19m               virtualmachine-controller  Error creating pod: Pod "virt-launcher-vm-win10-qvkvh" is invalid: spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'
  Warning  FailedCreate  19m               virtualmachine-controller  Error creating pod: Pod "virt-launcher-vm-win10-ljjzn" is invalid: spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'
  Warning  FailedCreate  19m               virtualmachine-controller  Error creating pod: Pod "virt-launcher-vm-win10-kdjsm" is invalid: spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'
  Warning  FailedCreate  19m               virtualmachine-controller  Error creating pod: Pod "virt-launcher-vm-win10-7qzpx" is invalid: spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'
  Warning  FailedCreate  19m               virtualmachine-controller  Error creating pod: Pod "virt-launcher-vm-win10-xtkc7" is invalid: spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'
  Warning  FailedCreate  19m               virtualmachine-controller  Error creating pod: Pod "virt-launcher-vm-win10-skrts" is invalid: spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'
  Warning  FailedCreate  19m               virtualmachine-controller  Error creating pod: Pod "virt-launcher-vm-win10-94wcc" is invalid: spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'
  Warning  FailedCreate  19m               virtualmachine-controller  Error creating pod: Pod "virt-launcher-vm-win10-x68ft" is invalid: spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'
  Warning  FailedCreate  9m (x9 over 19m)  virtualmachine-controller  (combined from similar events): Error creating pod: Pod "virt-launcher-vm-win10-2wncp" is invalid: spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'
  Warning  FailedCreate  104s              virtualmachine-controller  Error creating pod: Pod "virt-launcher-vm-win10-tbjtn" is invalid: spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'
  Warning  FailedCreate  104s              virtualmachine-controller  Error creating pod: Pod "virt-launcher-vm-win10-svx66" is invalid: spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
./virtctl version
Client Version: version.Info{GitVersion:"v0.28.0", GitCommit:"340a0d45524b2861c14b276ab18bd5fb9b4ed83c", GitTreeState:"clean", BuildDate:"2020-04-02T07:18:44Z", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"{gitVersion}", GitCommit:"{gitCommit}", GitTreeState:"{gitTreeState}", BuildDate:"{buildDate}", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):
kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:56:40Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"clean", BuildDate:"2020-04-16T11:48:36Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications:
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: vm-win10
  name: vm-win10
spec:
  runStrategy: Manual
  template:
    metadata:
      labels:
        kubevirt.io/vm: vm-win10
    spec:
      domain:
        resources:
          requests:
            memory: 4096M
        devices:
          disks:
          - name: containerdisk
            disk:
              bus: virtio
          - name: emptydisk
            disk:
              bus: virtio
      terminationGracePeriodSeconds: 60
      volumes:
      - name: containerdisk
        containerDisk:
          image: 10.221.101.125:5000/vmdisks/win10:latest
      - name: emptydisk
        emptyDisk:
          capacity: "2Gi"

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
NAME="Ubuntu"
VERSION="16.04.6 LTS (Xenial Xerus)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 16.04.6 LTS"
VERSION_ID="16.04"
HOME_URL="http://www.ubuntu.com/"
SUPPORT_URL="http://help.ubuntu.com/"
BUG_REPORT_URL="http://bugs.launchpad.net/ubuntu/"
VERSION_CODENAME=xenial
UBUNTU_CODENAME=xenial

- Kernel (e.g. `uname -a`):
Linux miaoyun-node-4 4.15.0-74-generic #83~16.04.1-Ubuntu SMP Wed Dec 18 04:56:23 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux

- Install tools:
- Others:

**Comment by pujunYang** [comment]
virt-controller  logs
 
{"component":"virt-controller","level":"info","msg":"reenqueuing VirtualMachineInstance default/vm-win10","pos":"vmi.go:204","reason":"failed to create virtual machine pod: Pod \"virt-launcher-vm-win10-fwp8v\" is invalid: spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'","service":"http","timestamp":"2020-11-06T03:04:01.747330Z"}
{"component":"virt-controller","level":"info","msg":"reenqueuing VirtualMachineInstance default/vm-win10","pos":"vmi.go:204","reason":"failed to create virtual machine pod: Pod \"virt-launcher-vm-win10-2kffh\" is invalid: spec.affinity.nodeAffinity.requiredDuringSchedulingIgnoredDuringExecution.nodeSelectorTerms[0].matchExpressions[0].values: Required value: must be specified when `operator` is 'In' or 'NotIn'","service":"http","timestamp":"2020-11-06T03:20:41.849628Z"}
