### ISSUE TITLE
[flakey ci] Configurations Check KVM CPUID advertisement [test_id:5271]test cpuid hidden

### ISSUE THREAD

**Issue by ashleyschuett** [kubevirt/kubevirt#4510]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Configurations Check KVM CPUID advertisement [test_id:5271]test cpuid hidden

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4470/pull-kubevirt-e2e-k8s-1.17/1322893898883796992

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fgimenez** [comment]
There's a kube-apiserver panic in this execution https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4470/pull-kubevirt-e2e-k8s-1.17/1322893898883796992/artifacts/k8s-reporter/2/pods/1_kube-system_kube-apiserver-node01-kube-apiserver.log
