### ISSUE TITLE
Metric kubevirt_info doesn't expose kubevirt version correctly

### ISSUE THREAD

**Issue by ArthurSens** [kubevirt/kubevirt#4515]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
I'm building some dashboards for monitoring KubeVirt components and workloads. Was planning to add KubeVirt version to the dashboard but to my surprise `kubevirt_info` returns `{gitversion}` instead of a valid version.

![image](https://user-images.githubusercontent.com/24193764/98585194-a948c980-22a5-11eb-810a-0ff4144b41c2.png)

**What you expected to happen**:
`kubevirt_info` to return the correct kubevirt version

**How to reproduce it (as minimally and precisely as possible)**:
Install kubevirt into a cluster, expose virt-handler metrics endpoint and curl it.

```
export KUBEVIRT_VERSION=$(curl -s https://api.github.com/repos/kubevirt/kubevirt/releases | grep tag_name | grep -v -- - | sort -V | tail -1 | awk -F':' '{print $2}' | sed 's/,//' | xargs)
kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${KUBEVIRT_VERSION}/kubevirt-operator.yaml
kubectl rollout status -n kubevirt deployment virt-operator
kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${KUBEVIRT_VERSION}/kubevirt-cr.yaml
kubectl rollout status -n kubevirt deployment virt-api
kubectl rollout status -n kubevirt deployment virt-controller
kubectl rollout status -n kubevirt daemonset virt-handler
kubectl port-forward -n kubevirt (kubectl get pod -n kubevirt -l kubevirt.io=virt-handler -o name) 8443:8443
curl localhost:8443/metrics | grep kubevirt_info
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
Nice catch.
