### ISSUE TITLE
[flaky ci] [Serial]Infrastructure [rfe_id:4102][crit:medium][vendor:cnv-qe@redhat.com][level:component]certificates [test_id:4100] should be valid during the whole rotation process

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#4518]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

/triage build-watcher

**What happened**:

Above test `[test_id:4100] should be valid during the whole rotation process` was flaky on #4501 before the PR got merged.

Symptom/Test error:

```
[Serial]Infrastructure [rfe_id:4102][crit:medium][vendor:cnv-qe@redhat.com][level:component]
  certificates [test_id:4100] should be valid during the whole rotation process

tests/infra_test.go:178 
Unexpected error:
     <*kubecli.AsyncSubresourceError \| 0xc0042d63c0>: {
         err: "Can't connect to websocket (500): websocket: bad handshake\n",
         StatusCode: 500,
     }
     Can't connect to websocket (500): websocket: bad handshake

occurred 
tests/infra_test.go:192

```

Flake on k8s-1.17: https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4501/pull-kubevirt-e2e-k8s-1.17/1325742799764590592
Flake on k8s-1.19: https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4501/pull-kubevirt-e2e-k8s-1.19/1325824207493271552

PR history: https://prow.apps.ovirt.org/pr-history/?org=kubevirt&repo=kubevirt&pr=4501

Possibly related to https://github.com/kubevirt/kubevirt/issues/4198

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dhiller** [comment]
Again here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4444/pull-kubevirt-e2e-k8s-1.18/1326006153942929409

**Comment by rmohr** [comment]
Related to #4522. It takes sometimes unusually long until the kubelet updates the certificate secrets. To stabilize this test, we have to expose the resourceVersion of the client and server certificates on all our healthz endpoints of our components, so that this test also knows when the client certificates are definitely rolled out. Right now it can only see if the server certificates were exchanged.

**Comment by fgimenez** [comment]
/reopen

Happened again https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-latest/1361254223462797313

**Comment by fgimenez** [comment]
Happened again https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-latest/1361979001106599936 also on 1.20
