### ISSUE TITLE
[flaky ci] [rfe_id:1177][crit:medium][vendor:cnv-qe@redhat.com][level:component]VirtualMachine An invalid VirtualMachine given [test_id:4643]should NOT be rejected when VM template lists a DataVolume, but VM lists PVC VolumeSource

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#4521]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

/triage build-officer

**What happened**:

Test `[rfe_id:1177][crit:medium][vendor:cnv-qe@redhat.com][level:component]VirtualMachine An invalid VirtualMachine given [test_id:4643]should NOT be rejected when VM template lists a DataVolume, but VM lists PVC VolumeSource` flaked before the PR #4471 got merged.

Offending run: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4471/pull-kubevirt-e2e-k8s-1.19/1324435179392995328

PR History: https://prow.apps.ovirt.org/pr-history/?org=kubevirt&repo=kubevirt&pr=4471

Test stacktrace:
```
tests/vm_test.go:115
Timed out after 240.000s.
Timed out waiting for DataVolume to enter Succeeded phase
Expected
    <v1alpha1.DataVolumePhase>: ImportScheduled
to equal
    <v1alpha1.DataVolumePhase>: Succeeded
tests/vm_test.go:124
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by oshoval** [comment]
Again 
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4435/pull-kubevirt-e2e-k8s-1.17/1326867455137550336
