### ISSUE TITLE
[flaky ci] [Serial]ImageUpload Upload an image and start a VMI with PVC [test_id:4621] Should succeed PVC

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#4527]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

/triage build-watcher

**What happened**:

Test `[Serial]ImageUpload Upload an image and start a VMI with PVC [test_id:4621] Should succeed PVC` failed before PR #4444 got merged.

Offending lane: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4444/pull-kubevirt-e2e-k8s-1.17/1325859564691656704 

PR history: https://prow.apps.ovirt.org/pr-history?org=kubevirt&repo=kubevirt&pr=4444

Test stacktrace: 
```
vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43
Unexpected error:
    <*errors.errorString | 0xc0005259a0>: {
        s: "timed out waiting for the condition",
    }
    timed out waiting for the condition
occurred
tests/imageupload_test.go:147
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tomob** [comment]
And again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4387/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1364692756617760768
And again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4387/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1365237344944263168

/reopen

**Comment by fabiand** [comment]
CLosing b/c referencing PR got merged.
