### ISSUE TITLE
ectd timeouts erros on tests

### ISSUE THREAD

**Issue by ormergi** [kubevirt/kubevirt#4529]
/kind bug

**What happened**:
SRIOV lane jobs fails 50% of the time due to etcd timeout errors.

We encounter those errors for a while now, It happens during tests when creating an object, e.g: Secret, VM.
it seems to happen right after installing `sriov-network-operator` or on the first tests that runs (right after Kubevirt operator deployment).
We get warning messages  `..took to long to execute` over etcd pods logs on every sriov lane job, here are few for example
Right after sriov-operator deployment
[1326381124888301569](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4512/pull-kubevirt-e2e-kind-1.17-sriov/1326381124888301569) [etcd logs](https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4512/pull-kubevirt-e2e-kind-1.17-sriov/1326381124888301569/artifacts/pods/0_kube-system_etcd-sriov-control-plane-etcd.log)
Right after kubevirt-operator deployment, when this error occurs at this time it will affect the first test 
[1326105060454699008](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4435/pull-kubevirt-e2e-kind-1.17-sriov/1326105060454699008) [etcd logs](https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4435/pull-kubevirt-e2e-kind-1.17-sriov/1326105060454699008/artifacts/k8s-reporter/pods/1_kube-system_etcd-sriov-control-plane-etcd.log)

Notes:
- CPU peeks at 30%, Memory peeks at 8G/110 and there is enough storage
- Configure 
```
   fs.inotify.max_user_instances = 8192
   fs.inotify.max_user_watches = 524288
```
- inotify watchers total consumption reach around 4000

related issues:
https://github.com/kubevirt/kubevirt/issues/3777
https://github.com/kubevirt/kubevirt/issues/4519

**What you expected to happen**:
No etcd erros during tests

**How to reproduce it (as minimally and precisely as possible)**:
Run SRIOV lane job look for etcd time error in the build log

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ormergi** [comment]
issue on Kind repo https://github.com/kubernetes-sigs/kind/issues/1922

**Comment by oshoval** [comment]
Ref
Please see here as well the research i did:
https://github.com/kubevirt/kubevirt/issues/4519#issuecomment-724913645
Which talk about ramfs and metrics.

and the research at https://github.com/kubevirt/kubevirtci/pull/473#discussion_r519932789
which talk about the pods that runs together and stress IO.

**Comment by ormergi** [comment]
KinD maintainers suggests to run etcd in memory to improve overall performance and reduce the IOps/disk througput consumption by the DinD with KinD cluster setup on CI.

This should be fixed by https://github.com/kubevirt/kubevirt/pull/4588
Now that all the changes are in place we will monitor SRIOV lanes for another week
and if everything is stabilized this issue can be closed.

**Comment by ormergi** [comment]
/close

Configuring etcd to run on RAM memory solved this issues
