### ISSUE TITLE
[flaky ci] AfterSuite

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#4540]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

/triage build-watcher

**What happened**:

Test `AfterSuite` failed before #4444 got merged.

Offending lane: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4444/pull-kubevirt-e2e-k8s-1.17/1325859564691656704

PR history: https://prow.apps.ovirt.org/pr-history?org=kubevirt&repo=kubevirt&pr=4444

Test stacktrace:
```
tests/tests_suite_test.go:68
Timed out after 240.000s.
should successfuly delete namespace 'kubevirt-test-default1'
Expected an error to have occurred.  Got:
    <nil>: nil
tests/utils.go:564
```

Related: #4244

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rhrazdil** [comment]
Happened again https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4499/pull-kubevirt-e2e-k8s-1.18/1326103044630253569[https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4499/pull-kubevirt-e2e-k8s-1.18/1326103044630253569](url)
