### ISSUE TITLE
[flaky ci] [Serial]Storage Starting a VirtualMachineInstance [rfe_id:2288][crit:high][vendor:cnv-qe@redhat.com][level:component] With Cirros BlockMode PVC [test_id:1015] should be successfully started

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#4543]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

/triage build-watcher

**What happened**:

Test `[Serial]Storage Starting a VirtualMachineInstance [rfe_id:2288][crit:high][vendor:cnv-qe@redhat.com][level:component] With Cirros BlockMode PVC [test_id:1015] should be successfully started` flaked before #4444 got merged.

Offending runs: 
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4444/pull-kubevirt-e2e-k8s-1.18/1326078002827628544
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4444/pull-kubevirt-e2e-k8s-1.19/1321752250875383808

PR history: https://prow.apps.ovirt.org/pr-history?org=kubevirt&repo=kubevirt&pr=4444

Test stacktrace:
```
tests/storage_test.go:874
Cirros login successfully
Unexpected error:
    <*errors.errorString | 0xc0020503c0>: {
        s: "send to spawned process command reached the timeout 9.965397689s",
    }
    send to spawned process command reached the timeout 9.965397689s
occurred
tests/storage_test.go:885
```

Related: #4314 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by maya-r** [comment]
Appeared again. Offending runs: [1](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4611/pull-kubevirt-e2e-k8s-1.17/1335594698722512897), [2](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4546/pull-kubevirt-e2e-k8s-1.17/1336024029668052992)

**Comment by phoracek** [comment]
Failed again, but this time with a different error:

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4676/pull-kubevirt-e2e-k8s-1.18/1340668726604730373

```
    <*kubecli.AsyncSubresourceError | 0xc0039c7000>: {
        err: "Can't connect to websocket (500): websocket: bad handshake\n",
        StatusCode: 500,
    }
    Can't connect to websocket (500): websocket: bad handshake
```
