### ISSUE TITLE
[flaky ci] k8s-1.17 temporary cluster failure

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#4544]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

/triage build-watcher

**What happened**:
 One of the tests broke the cluster, so a couple of tests failed, until the cluster eventually healed and the remaining tests continued as usual.

Example runs:
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4444/pull-kubevirt-e2e-k8s-1.17/1325754118735663104
* https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4522/pull-kubevirt-e2e-k8s-1.17/1326441901062098944

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dhiller** [comment]
Another example of this: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4522/pull-kubevirt-e2e-k8s-1.17/1326441901062098944

**Comment by phoracek** [comment]
Do these look related?

- https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4522/pull-kubevirt-e2e-k8s-1.17/1326441901062098944
- https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4492/pull-kubevirt-e2e-k8s-1.19/1326520795349913600

**Comment by oshoval** [comment]
Maybe related as well
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4435/pull-kubevirt-e2e-k8s-1.19/1328354755927347200

**Comment by tomob** [comment]
Another one?

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4617/pull-kubevirt-e2e-k8s-1.19/1336757737995898880

**Comment by fgimenez** [comment]
Could we identify which tests break the cluster? 

In recent builds where there are a lot of failures after one test breaks the cluster we are getting 7h timeouts and the test output is not parseable by junit, like in this case https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev/1364334520735633408 For this one the first test that failed was `test_id:2221` already reported here https://github.com/kubevirt/kubevirt/issues/4534

**Comment by fgimenez** [comment]
Looking at the kubelet logs in this last case I see a lot of:
```
Feb 24 01:35:05 node01 kubelet[3323]: E0224 01:35:05.896959    3323 kubelet_volumes.go:154] orphaned pod "b89e14d5-5a4c-44f3-ba2e-740a96a00c3b" found, but volume paths are still present on disk : There were a total of 1 errors similar to this. Turn up verbosity to see them.
```
and also:
```
Feb 24 02:08:26 node02 kubelet[2029]: E0224 02:08:26.700526    2029 kubelet.go:1768] skipping pod synchronization - PLEG is not healthy: pleg was last seen active 3m0.553374936s ago; threshold is 3m0s
```

**Comment by fgimenez** [comment]
/reopen

reopening given that we are still getting a lot of failed builds because of this.

**Comment by oshoval** [comment]
7h happened today
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5167/pull-kubevirt-check-tests-for-flakes/1369555863940894720

/reopen

**Comment by oshoval** [comment]
Time is the best cure for flakiness,
even the hardest ones
