### ISSUE TITLE
When I use kubevirt (v0.35.0) and kube-ovn together, virt-controller does not work properly. But the v0.32.0 version can work normally

### ISSUE THREAD

**Issue by ikukaku** [kubevirt/kubevirt#4558]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
goroutine 449 [running]:
kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/util/runtime.logPanic(0x1ac9ac0, 0x32229f0)
        vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:74 +0xa3
kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:48 +0x82
panic(0x1ac9ac0, 0x32229f0)
        GOROOT/src/runtime/panic.go:679 +0x1b2
kubevirt.io/kubevirt/pkg/virt-controller/watch/snapshot.(*VMSnapshotController).getVolumeStorageClassForVolume(0xc001b4a5a0, 0xc001f533a9, 0x7, 0xc000963998, 0x0, 0x3, 0xc0009636d0, 0x2)
        pkg/virt-controller/watch/snapshot/snapshot.go:686 +0x61a
kubevirt.io/kubevirt/pkg/virt-controller/watch/snapshot.(*VMSnapshotController).getVolumeSnapshotStatus(0xc001b4a5a0, 0xc0030ef040, 0xc000963998, 0x0, 0x0, 0x0, 0x0, 0x0)
        pkg/virt-controller/watch/snapshot/snapshot.go:656 +0x81
kubevirt.io/kubevirt/pkg/virt-controller/watch/snapshot.(*VMSnapshotController).updateVolumeSnapshotStatuses(0xc001b4a5a0, 0xc002a6da00, 0x13, 0x1ce9ac0)
        pkg/virt-controller/watch/snapshot/snapshot.go:640 +0x496
kubevirt.io/kubevirt/pkg/virt-controller/watch/snapshot.(*VMSnapshotController).processVMSnapshotStatusWorkItem.func1(0xc00333f980, 0x13, 0xf, 0x0, 0x2)
        pkg/virt-controller/watch/snapshot/snapshot_base.go:302 +0x248
kubevirt.io/kubevirt/pkg/virt-controller/watch/snapshot.processWorkItem.func1(0x22a07c0, 0xc000924540, 0xc003379e18, 0x1a33380, 0xc003342ad0, 0x0, 0x0)
        pkg/virt-controller/watch/snapshot/util.go:108 +0x274
kubevirt.io/kubevirt/pkg/virt-controller/watch/snapshot.processWorkItem(0x22a07c0, 0xc000924540, 0xc003379e18, 0x0)
        pkg/virt-controller/watch/snapshot/util.go:122 +0x72
kubevirt.io/kubevirt/pkg/virt-controller/watch/snapshot.(*VMSnapshotController).processVMSnapshotStatusWorkItem(0xc001b4a5a0, 0xc0021b5920)
        pkg/virt-controller/watch/snapshot/snapshot_base.go:288 +0x61
kubevirt.io/kubevirt/pkg/virt-controller/watch/snapshot.(*VMSnapshotController).vmSnapshotStatusWorker(0xc001b4a5a0)
        pkg/virt-controller/watch/snapshot/snapshot_base.go:211 +0x2b
kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil.func1(0xc003342de0)
        vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:152 +0x5e
kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/util/wait.JitterUntil(0xc003342de0, 0x3b9aca00, 0x0, 0x1, 0xc0029425a0)
        vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:153 +0xf8
kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/util/wait.Until(0xc003342de0, 0x3b9aca00, 0xc0029425a0)
        vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:88 +0x4d
created by kubevirt.io/kubevirt/pkg/virt-controller/watch/snapshot.(*VMSnapshotController).Run
        pkg/virt-controller/watch/snapshot/snapshot_base.go:182 +0x8fa
panic: runtime error: invalid memory address or nil pointer dereference [recovered]
        panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x8 pc=0x18bfdaa]

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
Client Version: version.Info{GitVersion:"v0.35.0", GitCommit:"b77b858ac9345ae6858cf409e1833f4548ec2809", GitTreeState:"clean", BuildDate:"2020-11-09T13:38:36Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"{gitVersion}", GitCommit:"{gitCommit}", GitTreeState:"{gitTreeState}", BuildDate:"{buildDate}", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):
[root@k8s-node-2 ~]# kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3", GitCommit:"1e11e4a2108024935ecfcb2912226cedeafd99df", GitTreeState:"clean", BuildDate:"2020-10-14T12:50:19Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.0", GitCommit:"e19964183377d0ec2052d1f1fa930c4d7575bd50", GitTreeState:"clean", BuildDate:"2020-08-26T14:23:04Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
Linux k8s-node-1 4.18.0-193.19.1.el8_2.x86_64 #1 SMP Mon Sep 14 14:37:00 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by rmohr** [comment]
@ikukaku looking at what you provide, I think that this has something to do with snapshotting. Either we have a bug in that new controller or the cluster is configured in a way which we did not expect. I don't think that it is related  to networking. @mhenriks would you mind having a look?

/assign @mhenriks

**Comment by tomob** [comment]
This should have been fixed with https://github.com/kubevirt/kubevirt/pull/4462.

**Comment by rmohr** [comment]
@ikukaku it should be part of the latest developer builds. Would be greast if you could give it a try: https://kubevirt.io/user-guide/#/installation/installation?id=installing-the-daily-developer-builds.
