### ISSUE TITLE
periodic-ci-kubevirt-kubevirt-master-0.34_4.6-e2e multi test failures due to "configmaps kubevirt-config not found"

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#4562]
/kind bug

**What happened**:
`periodic-ci-kubevirt-kubevirt-master-0.34_4.6-e2e` fails:

https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-master-0.34_4.6-e2e/1328534066990944256
Multiple failures, all or at least most about
`Message: "configmaps \"kubevirt-config\" not found",`

**What you expected to happen**:
Pass and be stable

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dhiller** [comment]
Is related to the testing manifests not available, uploaded them manually. Should be fixed tomorrow.

**Comment by dhiller** [comment]
FTR: the testing manifests are deployed here: https://github.com/kubevirt/kubevirt/blob/master/hack/ci/entrypoint.sh#L32

Currently working on a job that updates these manifests automatically.

**Comment by dhiller** [comment]
FYI @stu-gott @sgarbour
