### ISSUE TITLE
How to debug kubevirt

### ISSUE THREAD

**Issue by adofirst2018** [kubevirt/kubevirt#4567]
We want to develop kubevirt in k3s, I deploy k3s in single node, then

```
export DOCKER_PREFIX=127.0.0.1:5000/test
export DOCKER_TAG=dev
make && make push
kubectl create -f _out/manifests/release/kubevirt-operator.yaml
kubectl create -f _out/manifests/release/kubevirt-cr.yaml
```

kubevirt can run in k3s development environment, But when I modify kubevirt source,  I still need repeat the above steps
```
export DOCKER_PREFIX=127.0.0.1:5000/test
export DOCKER_TAG=dev
make && make push
kubectl create -f _out/manifests/release/kubevirt-operator.yaml
kubectl create -f _out/manifests/release/kubevirt-cr.yaml
```
There's no better way to debug kubevirt?  such as replacing binaries (virt-operator etc) thanks

**Comment by rmohr** [comment]
@adofirst2018 you can also just push the binary to your registry and manually modify the deployments. Also I think we have a pull policy environment variable which you can set to always pull on the deployments. You would then basically make your change, push it and then delete the deployment. Does that help?

**Comment by adofirst2018** [comment]
@rmohr Thank you for your reply,  but I have some questions,

1. I deploy kubevirt by yaml. I don't know how to deploy kubevirt by binary 2. I don't find a pull policy environment variable that can pull the binary to my registry, can you give me some references？

**Comment by rmohr** [comment]
@adofirst2018 I would recommend looking into our external provider: https://github.com/kubevirt/kubevirt/tree/master/cluster-up/cluster/external for development. It is a not-so-much used feature, so I can't guarantee that it works, but in theory you ensure that your `kubectl` is logged into a cluster. Then you can do:

```
export KUBEVIRT_PROVIDER=external
export DOCKER_PREFIX=myregistry:5000/kubevirt
export KUBECONFIG=mycluster.conf
export IMAGE_PULL_POLICY=Always
make cluster-up
```
Then `make cluster-sync` would deploy to the defined registry and deploy the manifest on the cluster where you are logged in.
To then just replace individual binaries which you locally modified, you can do the following:

1. Modify your code
2. `make push`
3. Delete the deployment or daemonset pods you care about
4. your pod will be restarted with the new image

In general I recommend developer flows where you simply change the code and then only do `make cluster-sync`. This is a little bit slower, but guarantees you synchronized installations during development.

**Comment by adofirst2018** [comment]
@rmohr thanks
