### ISSUE TITLE
Can't start demo VM on K3S cluster

### ISSUE THREAD

**Issue by availati** [kubevirt/kubevirt#4568]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind enhancement

**What happened**:
Command ./virtctl start testvm fail
osboxes@osboxes:~$ ./virtctl start testvm
Error starting VirtualMachine Put http://localhost:8080/apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachines/testvm/start: dial tcp 127.0.0.1:8080: connect: connection refused

**What you expected to happen**:
testvm start succesfully

**How to reproduce it (as minimally and precisely as possible)**:
Installed K3S cluster v1.18.9+k3s1 and runned example nginx cluster, to check cluster functionality.
Installed Kubevirt v0.34.1 via istruction: https://kubevirt.io/user-guide/#/installation/installation 
Installed virtctl v0.34.1
Installed and started testvm https://github.com/kubevirt/demo

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):v0.34.1
- Kubernetes version (use `kubectl version`): k3s v1.18.9+k3s1, 
osboxes@osboxes:~$ sudo kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9+k3s1", GitCommit:"630bebf94b9dce6b8cd3d402644ed023b3af8f90", GitTreeState:"clean", BuildDate:"2020-09-17T19:05:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.9+k3s1", GitCommit:"630bebf94b9dce6b8cd3d402644ed023b3af8f90", GitTreeState:"clean", BuildDate:"2020-09-17T19:05:07Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications: testvm
- Cloud provider or hardware configuration: VBox 4vcpu 4GB Ram, VT-x/AMD-v enabled
- OS (e.g. from /etc/os-release): Ubuntu 20.4
- Kernel (e.g. `uname -a`): Linux osboxes 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by duhongyu** [comment]
I know a workaround solution
kubectl proxy --address=0.0.0.0 --accept-hosts='^*$' --port 8080

**Comment by availati** [comment]
Its works thanks a lot.
Do you know if is a bug and its resolution is planned?

**Comment by futuretea** [comment]
```bash
export KUBECONFIG=/etc/rancher/k3s/k3s.yaml
```
or
```bash
cp /etc/rancher/k3s/k3s.yaml ~/.kube/config
```
