### ISSUE TITLE
WaitForFirstCustomer and --image-upload do not work well together

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#4601]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind enhancement

**What happened**:

If I have a storage class with WaitForfirstCustomer, PVC uploads are stuck forever when using `--image-upload`. We should clarify if it is save to use this feature now with the new `WaitForFirstCustomer` CDI support.

All can be fine here, but I don't know the expectations and we don't seem to test the flows for image-upload in this scenario.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by brybacki** [comment]
The PR #4779 solves part of the problem. It informs user about the system state. 

Now I wonder if we can update some documentation (but I cannot find one for virtctl image-upload) or provide a new doc with more info about working with upload and WFFC storage.

**Comment by brybacki** [comment]
The PR  [CDI #1560](https://github.com/kubevirt/containerized-data-importer/pull/1560) adds new annotation "storage.bind.immediate.requested" that might help when one does not care about node selection.
