### ISSUE TITLE
failed to look up user: user: lookup username qemu: invalid argument

### ISSUE THREAD

**Issue by lixiaobing1** [kubevirt/kubevirt#4603]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind enhancement

**What happened**:
When deploy kubevirt, err info occurs in virt-handler:
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/testvm","pos":"vm.go:923","reason":"failed to get image info: failed to invoke qemu-img: exit status 1: 'Error: failed to look up user: user: lookup username qemu: invalid argument\nUsage:\n  virt-chroot exec [flags]\n\nFlags:\n  -h, --help   help for exec\n\nGlobal Flags:\n      --cpu uint32      cpu time in seconds for the process\n      --memory uint32   memory in megabyte for the process\n      --mount string    mount namespace to use\n      --user string     switch to this targetUser to e.g. drop privileges\n\nfailed to look up user: user: lookup username qemu: invalid argument\n'","timestamp":"2020-11-30T06:08:33.650495Z"}

**What you expected to happen**:
Deploy normally.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy kubevirt.

**Anything else we need to know?**:
no

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@lixiaobing1 did you build your own base-image? It seems like you have no `qemu` user inside the container, which can pretty much only then happen. What version do you use?
