### ISSUE TITLE
Document VM API discussion

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#462]
There were some offline discussions relatde to VM API, the conclusion should be documented.

**Comment by michalskrivanek** [comment]
we can either add another section to vm-configuration.md or config-and-instances.md, or create a new one, like detailed-vm-configuration.md or something like that.
Things like "no strict 1:1 mapping", backend/frontend split are already covered, so perhaps just add a section with guidelines and examples to cover the complete libvirt xml expressiveness 
Afterwards it makes sense to revisit the current config-and-instances.md text, as it would likely make sense now to make VMConfig look very similar to VM, reuse the spec.

**Comment by davidvossel** [comment]
I think we've moved past the discussion phase and have a plan for implementation. #532 can be used to track the implementation
