### ISSUE TITLE
[flaky CI][sig-storage] Hotplug [Serial] rook-ceph VMI only should mark VMI not migrateable, if a volume is attached

### ISSUE THREAD

**Issue by maya-r** [kubevirt/kubevirt#4635]
/kind bug
/triage build-watcher

The following run had an unexpected failure in the test: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4546/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1336024029689024512

This indicates that the test is flaky.

**Comment by maya-r** [comment]
cc @awels
quick links for interesting points:
[unable to execute QEMU command 'blockdev-add': Could not open '/var/run/kubevirt/hotplug-disks/testvolume': Operation not permitted')](http://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4546/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1336024029689024512/artifacts/k8s-reporter/1_events.log)
[patching of vmi conditions and activePods failed: the server rejected our request due to an error in our request...](http://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4546/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1336024029689024512/artifacts/k8s-reporter/pods/1_kubevirt_virt-controller-58447d4c87-scfct-virt-controller.log)

It doesn't seem like the reenqueue happened, that is the last message on the pod logs.

**Comment by awels** [comment]
If you look in the virt-handler logs and virt-launcher pod logs you will see it retry many times. But for some reason it cannot read the block device. Its saying permission denied, but that could be because of many different reasons. Unfortunately we don't capture the permissions.

**Comment by awels** [comment]
This appears to be a race condition in adding the block device to the devices.list of the container. In certain conditions something else writes to the file and deletes the allowed block device, which results in the mentioned error. So far have not been able to identify what is overwriting the file

**Comment by awels** [comment]
This is fixed by https://github.com/kubevirt/kubevirt/pull/4761
