### ISSUE TITLE
make tries to read non-existant .glide.lock.hash on fresh checkout

### ISSUE THREAD

**Issue by berrange** [kubevirt/kubevirt#464]
I just cloned a fresh checkout of kubevirt and ran 'make manifests docker'. I noticed that make tried to read a file which did not exist:

$ make manifests docker
./hack/build-manifests.sh
test -f .glide.yaml.hash || md5sum glide.yaml > .glide.yaml.hash
if [ "`md5sum glide.yaml`" != "`cat .glide.yaml.hash`" ]; then \
	glide cc; \
	glide update --strip-vendor; \
	md5sum glide.yaml > .glide.yaml.hash; \
	md5sum glide.lock > .glide.lock.hash; \
elif [ "`md5sum glide.lock`" != "`cat .glide.lock.hash`" ]; then \
	make sync; \
fi
cat: .glide.lock.hash: No such file or directory
....

everything seems to carry on ok after this, so harmless, but might be nice to avoid triggering the error message

**Comment by cynepco3hahue** [comment]
#511 Will fix this one.

**Comment by stu-gott** [comment]
We're not using glide anymore.
