### ISSUE TITLE
SRIOV [test_id:3956]/[test_id:3957] are flaky, ping is failing between two SRIOV vnic/s

### ISSUE THREAD

**Issue by EdDev** [kubevirt/kubevirt#4642]
/kind bug

**What happened**:
e2e Multus/SRIOV tests are flaky.
Ping is rarely failing when checking connectivity between the two SRIOV vnic/s.

**What you expected to happen**:
Test to always pass.

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to run it multiple times on CI.

**Anything else we need to know?**:
Previous flakiness was ref [here](https://github.com/kubevirt/kubevirt/issues/4621), this seems to be a new issue.

The issue has been seen on CI at least once: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4617/pull-kubevirt-e2e-kind-1.17-sriov/1336545341402517504

**Comment by EdDev** [comment]
This may be a duplicate of https://github.com/kubevirt/kubevirt/issues/3828.

**Comment by EdDev** [comment]
Seen 3 times today on IPv4:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/3479/pull-kubevirt-e2e-kind-1.17-sriov/1338800828001030145
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4654/pull-kubevirt-e2e-kind-1.17-sriov/1338781622626947073
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4668/pull-kubevirt-e2e-kind-1.17-sriov/1338661311608786945

Interesting enough, when one IP stack fails, the other does not (in most cases).

**Comment by alonSadan** [comment]
seeing this also in the vlan test, where a ping is also asserted. for example: 
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4708/pull-kubevirt-e2e-kind-1.17-sriov/1344291381077610497

vlan test was xfail in the meanwhile:
https://github.com/kubevirt/kubevirt/pull/4733

**Comment by maiqueb** [comment]
@alonSadan / @ormergi could you sum up your findings up to know in the issue ? 

Thanks in advance for the effort.

**Comment by alonSadan** [comment]
Findings so far: 
From what we have seen so far this happens only on one specific CI node with connectX-5 HW. 

We noticed that the vlan tags and mac addresses stays in tact between different CI jobs.
This means that on this node, they will have this vlan tag on every job, and this could cause one VF to be on different vlan than the other VF, which will lead to connectivity issues.

We noticed as well that once we give vlan tag to a VF, even if we will delete the VFs with:

`VFs by echo 0 > /sys/class/net/ens1f0/device/sriov_numvfs `
 
when we create them again:

`echo 7 > /sys/class/net/ens1f0/device/sriov_numvfs`

they will have the same mac and the same vlan tag.
This seems wrong.

Another check I made is to give all VFs a vlan tag, and create a pod which is connected to a network with no vlan.
In this case the vlan tag was removed from the VF that was assigned to the pod.

**Comment by EdDev** [comment]
> Another check I made is to give all VFs a vlan tag, and create a pod which is connected to a network with no vlan, and the same with vmi.
> In both cases the vlan tag was removed from the VF that was assigned to the pod.

if this is the case, it cannot explain the problem.

**Comment by alonSadan** [comment]
https://github.com/kubevirt/kubevirt/pull/5093 Fixed this issue. All the details are the PR. 
Since the PR got merged the SRIOV job ran 
Therefore this issue can be closed.

**Comment by oshoval** [comment]
Remove than the XFail please?

**Comment by alonSadan** [comment]
> Remove then the XFail please?
> `assert.XFail("suspected cloud-init issue: https://github.com/kubevirt/kubevirt/issues/4642", func() {`

https://github.com/kubevirt/kubevirt/pull/5282
Done.

**Comment by alonSadan** [comment]
https://github.com/kubevirt/kubevirt/pull/5093 solved the issue, so it can be closed.
