### ISSUE TITLE
[Flaky CI] [rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]VMIlifecycle [rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]Creating a VirtualMachineInstance [Serial]when virt-handler is responsive [test_id:1633]should indicate that a node is ready for vmis

### ISSUE THREAD

**Issue by mhenriks** [kubevirt/kubevirt#4650]
/kind bug
/triage build-watcher

**What happened**:

```
tests/vmi_lifecycle_test.go:489
Timed out after 120.000s.
Nodes should be schedulable
Expected
    <string>: false
to equal
    <string>: true
tests/vmi_lifecycle_test.go:508
```

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4633/pull-kubevirt-e2e-k8s-1.19/1336197549484150784

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dhiller** [comment]
Same here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4504/pull-kubevirt-e2e-k8s-1.18/1338804299420930048

**Comment by dhiller** [comment]
And here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4639/pull-kubevirt-e2e-k8s-1.19/1339281077033766912
