### ISSUE TITLE
Issues to generate SDK with swagger-codegen

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt/kubevirt#467]
I am trying to generate PySDK with swagger-codegen. I am using latest release of KubeVirt v0.0.2
I use following command to do that.

```bash
$ java -jar swagger-codegen-cli-2.2.1.jar generate -i "http://192.168.200.2:8183/swaggerapi/apis/kubevirt.io/v1alpha1" -l python -o /tmp/kubevirt-pysdk
```

I noticed that there are several exceptions in log during generation. Please see attached log-file:
[kubevirt-pysdk.log](https://github.com/kubevirt/kubevirt/files/1337132/kubevirt-pysdk.log)

However the sdk gets generated and, auto-generated tests passes as well 😄 
```bash
$ tox
........................................................................................
----------------------------------------------------------------------
Ran 88 tests in 0.211s

OK
```

Observing auto-generated SDK, only two calls were generated as I would expected: `console` & `spice`
Remaining methods were generated with meaning-lees names, like `func1_8` or `func1_10`.

I would expect some meaningful names like `list_vms`, `create_vm`, ...

You can take a look at full result at https://github.com/lukas-bednar/kubevirt-pysdk-generated#documentation-for-api-endpoints
You can also find there log, and json file which was SDK generated from.

I generated SDK from KubeVirt master, and it has same issue, the main change there is about `vms` - > `virtualmachines` .
Feel free to take a look: https://github.com/lukas-bednar/kubevirt-pysdk-generated/tree/kubevirt-master

**Comment by rmohr** [comment]
@lukas-bednar created #475 which will address the function names. Regarding to the errors, we probably don't set a type field or so. Will look into that too. Thanks for reporting!

**Comment by lukas-bednar** [comment]
@rmohr thanks for quick response, it looks good.
If I can help with something, I would be glad to do so ... just point me where to look.
Also I noticed that there are `Doc("testX")` strings or they are missing, for example here:
https://github.com/kubevirt/kubevirt/blob/a0fc1ec3297fd24fc20cbbf2636a309f1e60a6b5/pkg/virt-api/rest/kubeproxy.go#L105-L109
I can fill them up if you don't mind.

**Comment by lukas-bednar** [comment]
I see that Route object has many documentation related attributes.
https://github.com/emicklei/go-restful/blob/7a380bfc22e94bfe4fc605b9a15a7be1347ebe39/route_builder.go#L31
I will take a look at it and see what I can add there.

**Comment by rmohr** [comment]
> I can fill them up if you don't mind.

Yes please!

**Comment by rmohr** [comment]
These errors

```
Error obtaining the datatype from RefProperty:io.swagger.models.properties.RefProperty@e8fe9c77. Datatype default to Object
[main] ERROR io.swagger.codegen.DefaultCodegen - null
```
are interesting. It looks like swagger-codegen tries to dereference the model in the swagger 2.0 way, although we have version 1.2 specified in the document. In 1.2 one can reference entities viea `"$ref": "myobject"` in the `models` section. In 2.0 one would have to write `#/models/myobject`. 

I did not run swagger-codegen, but the [Swagger Editor](https://editor.swagger.io/) reacts that way with our spec.

**Comment by lukas-bednar** [comment]
what do you think about `kube_connection_healthz_func` function, I think it would deserve better name.
https://github.com/lukas-bednar/kubevirt-pysdk-generated/blob/kubevirt-master/docs/ApiskubevirtiovalphaApi.md#kube_connection_healthz_func

Do you have any preference? like health_status / health_page / service_health / health_check

**Comment by lukas-bednar** [comment]
> Yes please!
I submitted it here #476 please comment on it!

**Comment by lukas-bednar** [comment]
> I did not run swagger-codegen, but the Swagger Editor reacts that way with our spec.

I was checking documentation, and current swagger-codegen (2.2.1) should be compatible with 1.2. 
https://swagger.io/docs/swagger-tools/

But apparently no, I will investigate it .

@fabiand in addition I was playing with that swager plugin for GitBook, and it doesn't generate doc well.
https://lukas-bednar.gitbooks.io/kubevirt-api-doc/content/
I think it will be probably from same reason ... strange thing is that GitBook doesn't report any error, everything seems to be OK, just documentation is not rendered.

**Comment by lukas-bednar** [comment]
@rmohr I think I found what causes that errors in code-generation: #480  I am just working on verification.

**Comment by rmohr** [comment]
Yes, that's probably it. Good catch!

**Comment by lukas-bednar** [comment]
I am closing this issue all things which I had problem with, were addressed.
I don't have problem to generate SDK anymore ...
