### ISSUE TITLE
vmi does not support field-selector status.phase

### ISSUE THREAD

**Issue by gouyang** [kubevirt/kubevirt#4673]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:

/kind enhancement

**What happened**:
$ oc get vmi --field-selector status.phase=Running
Error from server (BadRequest): Unable to find "kubevirt.io/v1, Resource=virtualmachineinstances" that match label selector "", field selector "status.phase=Running": field label not supported: status.phase

$ oc get pod --field-selector status.phase=Running
NAME                      READY   STATUS    RESTARTS   AGE
virt-launcher-vm1-6sxxd   2/2     Running   0          149m

**What you expected to happen**:
`oc get vmi --field-selector status.phase=Running` can filter the running VMI.

**How to reproduce it (as minimally and precisely as possible)**:
100%

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
$ virtctl version
Client Version: version.Info{GitVersion:"v0.34.2", GitCommit:"48956f60864ece98118d7894327caf7513c5b942", GitTreeState:"clean", BuildDate:"2020-11-17T13:47:56Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.0.0-master+$Format:%h$", GitCommit:"$Format:%H$", GitTreeState:"", BuildDate:"1970-01-01T00:00:00Z", GoVersion:"go1.14.7", Compiler:"gc", Platform:"linux/amd64"}

-

**Comment by davidvossel** [comment]
I believe we're still waiting on Kubernetes to provide field selector support for CRDs https://github.com/kubernetes/kubernetes/issues/53459

Without that support, I'm not sure how we can do what you're requesting here.
