### ISSUE TITLE
 host a sub community for translate kubevirt

### ISSUE THREAD

**Issue by zxb789** [kubevirt/kubevirt#4677]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind proposal

hi everyone:
      my company has use kubevirt in development or production for some time。i create this issue regarding host a chinese kubeviert community for translate kubevirt or post some use cases in production or organize some meetup 
    i love to hear about any additional suggesting or join us,  Please reply or comment on the issue.
   thanks

**Comment by zxb789** [comment]
kind/proposal

**Comment by gouyang** [comment]
I just have this same idea in the morning and surprised to find this issue here. I would love to help.
In my opinion, the main issue for users in China is Time Zone issue and the communication in English.

My suggestions:
1. Let's have a China community meeting, people can talk in Chinese. And get it translated and post into kubevirt-dev after the meeting.
2. Transmit the main community meeting minutes to sub-community.
3. Look for possible offline meetup.

**Comment by zxb789** [comment]
yes,  your idea is great , can you share youre slack id ？we can chat with it

**Comment by zxb789** [comment]
@gouyang

**Comment by gouyang** [comment]
@fabiand @rmohr @dankenigsberg @davidvossel 
zxb789 and I have a talk about the topic, both of us are interested in run a local community to get more local people's interests in kubevirt. Before we start it, we'd like to hear your voices on this. Is it good or is it bad? 

Thanks,

**Comment by dankenigsberg** [comment]
It would be great to have a Chinese-language community call, and I would be happy to read its summary over kubevirt-dev. Please send the invite to that mailing list so anyone can join.

@zxb789, I'd love to hear more about your company and its use case for KubeVirt. You can provide it as a PR for  https://github.com/kubevirt/kubevirt/blob/master/ADOPTERS.md

**Comment by zxb789** [comment]
@dankenigsberg thanks for your reply , I have provided my team's use case as a PR

**Comment by dankenigsberg** [comment]
@zxb789 can you add a url to your pr? I cannot find it.

**Comment by zxb789** [comment]
@dankenigsberg sorry, has a mistake just now ,following is my pr:  https://github.com/kubevirt/kubevirt/pull/4713, 3ks

**Comment by gouyang** [comment]
> It would be great to have a Chinese-language community call, and I would be happy to read its summary over kubevirt-dev. Please send the invite to that mailing list so anyone can join.

@dankenigsberg Thank you. We will try to run the Chinese-language community call to see how far we can get.

**Comment by imluyuan** [comment]
cool
