### ISSUE TITLE
No response to ARP request for 169.254.75.10 (k6t-eth0) inside VM

### ISSUE THREAD

**Issue by ArthurMelin** [kubevirt/kubevirt#4678]
/kind bug

**What happened**:
In a Windows guest, changing the DNS config to manual makes the network connectivity fail.
The guest loses the gateway address.
Wireshark shows that Windows attempts to contact the DHCP server on 169.254.75.10, but fails when trying to resolve the MAC address (no ARP response).
Here is a screenshot of ipconfig after the DNS config change:
![image](https://user-images.githubusercontent.com/3268661/102336087-fd278c00-3f90-11eb-9baf-6eb12102f0c0.png)
Wireshark log (filter: arp):
![image](https://user-images.githubusercontent.com/3268661/102336195-29430d00-3f91-11eb-84f9-bedc8ade4840.png)

**What you expected to happen**:
The guest should receive an ARP response with the MAC address of the k8t-eth0 interface and proceed with the DHCP lease renewal.

**How to reproduce it (as minimally and precisely as possible)**:
In a Windows (10 / Server 2019) guest, go to Network Connections, go to the ethernet adapter properties, then IPv4 config, set the DNS config to static and input any DNS server (1.1.1.1/1.0.0.1). Apply the modifications and watch the guest lose network connectivity.

**Anything else we need to know?**:
`ip addr` inside the virt-launcher pod:
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if999: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue master k6t-eth0 state UP group default 
    link/ether a6:60:61:3e:0b:f3 brd ff:ff:ff:ff:ff:ff link-netnsid 0
4: k6t-eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether 1e:3c:91:0e:a9:37 brd ff:ff:ff:ff:ff:ff
    inet 169.254.75.10/32 scope global k6t-eth0
       valid_lft forever preferred_lft forever
5: tap0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc fq_codel master k6t-eth0 state UP group default qlen 1000
    link/ether 1e:3c:91:0e:a9:37 brd ff:ff:ff:ff:ff:ff
```

**Environment**:
- KubeVirt version (use `virtctl version`): 
virtctl version is broken, server version is v0.34.0
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"2020-11-25T13:19:56Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"clean", BuildDate:"2020-09-09T11:18:22Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications:
```yaml
# relevant parts only
kind: VirtualMachine
apiVersion: kubevirt.io/v1alpha3
metadata:
  name: test
spec:
  template:
    spec:
      domain:
        devices:
          interfaces:
            - bridge: {}
              name: default
      hostname: test
      networks:
        - name: default
          pod: {}
```
- Cloud provider or hardware configuration:
Self-hosted, AMD EPYC 7502, 256G RAM
- OS (e.g. from /etc/os-release):
```
NAME="Ubuntu"
VERSION="20.04.1 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04.1 LTS"
VERSION_ID="20.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=focal
UBUNTU_CODENAME=focal
```
- Kernel (e.g. `uname -a`):
`Linux test 5.4.0-53-generic #59-Ubuntu SMP Wed Oct 21 09:38:44 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
kubeadm, kubevirt-operator
- Others:
CNI: Flannel

**Comment by Elassyo** [comment]
Hello?
