### ISSUE TITLE
[flaky ci] [rfe_id:253][crit:medium][vendor:cnv-qe@redhat.com][level:component]Expose Expose UDP service on a VMI Expose NodePort UDP service [label:masquerade_binding_connectivity]Should expose a NodePort service on a VMI and connect to it over IPv6 IP family

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#4689]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement
/triage build-watcher

**What happened**:

Test `[rfe_id:253][crit:medium][vendor:cnv-qe@redhat.com][level:component]Expose Expose UDP service on a VMI Expose NodePort UDP service [label:masquerade_binding_connectivity]Should expose a NodePort service on a VMI and connect to it over IPv6 IP family` flaked in PR https://github.com/kubevirt/kubevirt/pull/4671

Run: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4671/pull-kubevirt-e2e-k8s-1.18/1338585039587250176

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

```
vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43
Expected success, but got an error:
    <*errors.errorString | 0xc0019335f0>: {
        s: "Job netcattfkkt timeout reached, status: {Conditions:[] StartTime:2020-12-14 21:38:36 +0000 UTC CompletionTime:<nil> Active:1 Succeeded:0 Failed:0}, err: timed out waiting for the condition",
    }
    Job netcattfkkt timeout reached, status: {Conditions:[] StartTime:2020-12-14 21:38:36 +0000 UTC CompletionTime:<nil> Active:1 Succeeded:0 Failed:0}, err: timed out waiting for the condition
tests/expose_test.go:412
```

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by orenc1** [comment]
Another recurrence - https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4704/pull-kubevirt-e2e-k8s-cnao-1.19/1343579183988609024

**Comment by fgimenez** [comment]
Same on IPv4 IP family https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4581/pull-kubevirt-e2e-k8s-1.18/1346378629180821504

**Comment by fgimenez** [comment]
It is pretty easy to reproduce by executing `test_id:1536` in a loop, after a few executions the jobs that checks the UDP connection gets stuck, its logs look like:
```
+ trap 'kill 0' EXIT
++ head -n 1
+++ echo
+++ nc -ul 32677
+++ nc -up 32677 192.168.66.102 32678 -i 3 -w 3
```
In a successful execution, the logs of the completed job look like:
```
+ trap 'kill 0' EXIT
++ head -n 1
+++ echo
+++ nc -ul 32677
+++ nc -up 32677 192.168.66.101 32678 -i 3 -w 3
+ x='Hello UDP World!'
+ echo 'Hello UDP World!'
+ '[' 'Hello UDP World!' = 'Hello UDP World!' ']'
+ echo succeeded
+ exit 0
+ kill 0
Hello UDP World!
succeeded
```
It seems that the problem comes from the code here https://github.com/kubevirt/kubevirt/blob/master/tests/job.go#L132 in some cases the local UDP listener seems to spin up after the client has make its requests and keeps listening forever, will try to verify.

**Comment by shwetaap** [comment]
Seeing a timeout issue here as well - https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4844/pull-kubevirt-e2e-k8s-1.19/1354528908422156289. Not sure if it is related to the timeout issue here

**Comment by fgimenez** [comment]
/reopen

Indeed, thanks for the heads up @shwetaap looks like there has been a regression. We started observing failures in the daily master executions. I've tried to reproduce but it is not so easy now, will take a look.

**Comment by fgimenez** [comment]
Similar timeout again https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev/1358536187786039296
