### ISSUE TITLE
Feature request: Live-update of VMI labels & annotations

### ISSUE THREAD

**Issue by haslersn** [kubevirt/kubevirt#4711]
/kind enhancement

Since #2627 got merged, annotations get carried from VMs to the VMI and to the launcher Pod. The same is true for labels. But it would be nice to live-update the VMI's labels & annotations.

**What happened**:

I wanted to start backing up one of my VMs' volumes using Velero's Restic integration. This requires adding an annotation to the launcher Pod. I added the required annotation to the `vm.spec.template.metadata.annotations`. However, the annotation **currently only applies to newly created VMIs**, so I had to delete the old VMI, effectively causing a VM reboot.

**What you expected to happen**:

In order to do the above without a VM reboot, it would be nice if KubeVirt did perform a live-update of the VMI's labels & annotations. If you decide to support this, then it's probably preferable (in order to be consistent) to also perform a live-update of the launcher Pod's labels & annotations. (Although, for my use-case, the latter is not required, because I can simply recreate the launcher Pod via `virtctl migrate <vm_name>`.)

**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.33.0", GitCommit:"1ac45c6f119296b1a83550840dada59d2facadaa", GitTreeState:"clean", BuildDate:"2020-09-15T14:54:16Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"{gitVersion}", GitCommit:"{gitCommit}", GitTreeState:"{gitTreeState}", BuildDate:"{buildDate}", GoVersion:"go1.12.8", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.1", GitCommit:"206bcadf021e76c27513500ca24182692aabd17e", GitTreeState:"archive", BuildDate:"1980-01-01T00:00:00Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by davidvossel** [comment]
> I wanted to start backing up one of my VMs' volumes using Velero's Restic integration. This requires adding an annotation to the launcher Pod.

I'm hesitant to add logic that live propagates the VM label/annotations to a running VMI.  The VM is meant to represent the offline config of the VM which can be mutated independently of a currently running VMI.

I wouldn't have an issue with having the VMI labels/annotations propagate to the launcher pod though.

Would this help your use case? It would simply mean updating the annnotation on the VMI rather than the VM.

**Comment by haslersn** [comment]
No, because propagating from the VMI to the launcher pod does never occur if the VMI is immutable.

**Comment by haslersn** [comment]
I guess it's better to not have this feature, because other aspects of the VMI also are not updated.

**Comment by davidvossel** [comment]
> No, this would not help, because propagating from the VMI to the launcher pod does never occur if the VMI is immutable.

The VMI's labels/annotations should be mutable. It's only the VMI's spec that is not allowed to mutate after creation.

**Comment by haslersn** [comment]
Ah, so you were referring to someone manually mutating the labels/annotations via `kubectl patch`. Okay, I don't do such things, because I prefer to have resources that are either fully managed by an operator or fully self-manager (via `kubectl apply` or GitOps etc.). But maybe that's useful for somebody else, so I reopen.

**Comment by haslersn** [comment]
Maybe another approach is to propagate labels/annotations from the VM to the VMI. No, I'm not talking about the `vm.spec.template.metadata.annotations` but rather about the `vm.metadata.annotations`. This way the user could choose:

- label/annotate `vm.spec.template.metadata` -> no live update
- label/annotate `vm.metadata` -> live update

**Comment by phoracek** [comment]
Bug scrub: We want to keep these two label entities separated. Anything that gets propagated to the VMI should be taken from the VMI template defined in the VM.
