### ISSUE TITLE
[flaky ci] Creating a VirtualMachineInstance when virt-handler is not responsive [test_id:1634] - virt-handler not found

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#4715]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-master-4.4-e2e/1341942352272429056

tests/vmi_lifecycle_test.go:581
Should get virthandler client
Unexpected error:
    <*errors.errorString | 0xc002148600>: {
        s: "No virt-handler on node ci-op-xpqg518b-001db-9b4vr-master-0 found",
    }
    No virt-handler on node ci-op-xpqg518b-001db-9b4vr-master-0 found
occurred
tests/vmi_lifecycle_test.go:617

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/triage build-watcher

**Comment by dhiller** [comment]
/reopen

Seen on OpenShift CI here: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-master-4.8-e2e/1347378044184039424

**Comment by dhiller** [comment]
This is no longer a failing test, it fails every time for a while now: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-master-4.8-e2e/1348827553007144960

**Comment by maya-r** [comment]
Failing on kubernetes:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4816/pull-kubevirt-e2e-k8s-1.17/1351033626933858304
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4816/pull-kubevirt-e2e-k8s-1.17/1350792286249684992

**Comment by brybacki** [comment]
again here:
https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-master-4.8-e2e/1351364419715600384

**Comment by dhiller** [comment]
/reopen

still an issue: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-master-4.8-e2e/1356437936719007744

**Comment by dhiller** [comment]
FYI @kwiesmueller
