### ISSUE TITLE
[flaky ci] Creating a VirtualMachineInstance when virt-handler is not responsive [test_id:1634]

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#4720]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4710/pull-kubevirt-e2e-k8s-1.17/1341915356280655873

tests/vmi_lifecycle_test.go:630
Expected
    <string>: 
to equal
    <string>: NodeUnresponsive
tests/vmi_lifecycle_test.go:663

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/triage build-watcher

**Comment by borod108** [comment]
/reopen
Occurred again: 

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4885/pull-kubevirt-e2e-k8s-1.17/1353717697505923072

```
tests/vmi_lifecycle_test.go:632
Expected
    <string>: 
to equal
    <string>: NodeUnresponsive
tests/vmi_lifecycle_test.go:665
```

**Comment by jean-edouard** [comment]
More: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4736/pull-kubevirt-e2e-k8s-1.17/1355102063595360256

**Comment by maiqueb** [comment]
/reopen

I've been able to reproduce this locally sometimes w/ `KUBEVIRT_E2E_FOCUS='test_id:1634' FUNC_TEST_ARGS='-untilItFails -race' make functest`

You can see that the node is marked as unresponsive - in the [events](https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4736/pull-kubevirt-e2e-k8s-1.17/1355102063595360256/artifacts/k8s-reporter/1_events.log) log -  but somehow, the VMIs are not being marked as orphaned (VMI entity exists, but doesn't have a corresponding pod entity):

```json
...
            "involvedObject": {
                "kind": "Node",
                "name": "node01",
                "uid": "fad3514a-d0f8-4d8a-8162-7869e11dee7f",
                "apiVersion": "v1",
                "resourceVersion": "110720"
            },
            "reason": "NodeUnresponsive",
            "message": "virt-handler is not responsive, marking node as unresponsive",
            "source": {
                "component": "node-controller"
            },
...
```

**Comment by RamLavi** [comment]
> You can see that the node is marked as unresponsive - in the [events](https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4736/pull-kubevirt-e2e-k8s-1.17/1355102063595360256/artifacts/k8s-reporter/1_events.log) log - but somehow, the VMIs are not being marked as orphaned (VMI entity exists, but doesn't have a corresponding pod entity):

When I reproduced it locally - I saw that there are no vmis on the node at the time of the node's [watch](https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-controller/watch/node.go#L181), but it was only recreated once.

**Comment by oshoval** [comment]
can it be duped by https://github.com/kubevirt/kubevirt/issues/4958 ?
(which reoccurred after the merge i think)

**Comment by maya-r** [comment]
happened on openshift-ci as well: https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-master-4.8-e2e/1366222299895697408
