### ISSUE TITLE
[api doc] addvolume and removevolume have no body in our api reference

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#4725]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind enhancement

**What happened**:

https://kubevirt.io/api-reference/v0.36.0/operations.html#_vm-addvolume has no body. The generated API doc is incomplete.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by awels** [comment]
@rmohr Does this mean I am just missing a 'consumes' for those? I am not entirely sure what I am missing.
