### ISSUE TITLE
k8s 1.20 fails on IPV6 tests

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#4729]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

A test run of the new 1.20 lane failed with some test failures for IPV6:

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4662/pull-kubevirt-e2e-k8s-1.20/1344200275589599232

/cc @phoracek @qinqon 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dhiller** [comment]
Version bump of kubevirtci done here: kubevirt/kubevirt#4662

**Comment by phoracek** [comment]
The API of services has changed in 1.20. Instead of ipFamily, we have ipFamilies.

https://kubernetes.io/docs/concepts/services-networking/dual-stack/

/assign @maiqueb

**Comment by maiqueb** [comment]
Do we want to take this opportunity to define the preferred IP family to IPv6 ? @phoracek / @AlonaKaplan / @EdDev

**Comment by phoracek** [comment]
Meaning that all services on our CI would go over IPv6 unless said otherwise? I'd imagine that our main audience is still on IPv4 default. I think that keeping IPv4 well tested has higher priority than covering "niche" IPv6.

**Comment by dhiller** [comment]
Please note that the 1.20 lane is available, but does not report to GitHub yet. At the moment the only way to find test runs is via Prow.

Examples:
* https://prow.apps.ovirt.org/?job=pull-kubevirt-e2e-k8s-1.20
* https://prow.apps.ovirt.org/pr-history/?org=kubevirt&repo=kubevirt&pr=4662
