### ISSUE TITLE
Error from server (InternalError): error when creating "vmi.yml": Internal error occurred: failed calling webhook "virtualmachineinstances-create-validator.kubevirt.io": Post https://virt-api.kubevirt.svc:443/virtualmachineinstances-validate-create?timeout=4s: context deadline exceeded  this is with k3s and kube virt together.

### ISSUE THREAD

**Issue by rupeshr9** [kubevirt/kubevirt#4731]
**Is this a BUG REPORT 

We are using sing k3s and kubevirt together to use containerization and virtualization together. and we are geeting this error when we dont have internet connection 

Error from server (InternalError): error when creating "vmi.yml": Internal error occurred: failed calling webhook "virtualmachineinstances-create-validator.kubevirt.io": Post https://virt-api.kubevirt.svc:443/virtualmachineinstances-validate-create?timeout=4s: context deadline exceeded

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dankenigsberg** [comment]
@rupeshr9 would you please share your vmi.yaml as well of the other requested data under "Environment"?

**Comment by phoracek** [comment]
@rupeshr9 could you please verify that connectivity within the cluster works fine?

**Comment by rmohr** [comment]
This could be related: https://github.com/jetstack/cert-manager/issues/2811

**Comment by phoracek** [comment]
There is a workaround described in another k3s issue: https://github.com/kubevirt/kubevirt/issues/4568

**Comment by phoracek** [comment]
@rupeshr9 hello, did you get a chance to try the workaround?
