### ISSUE TITLE
error while creating vmi

### ISSUE THREAD

**Issue by rupeshr9** [kubevirt/kubevirt#4732]
**Is this a BUG REPORT 

We are using sing k3s and kubevirt together to use containerization and virtualization together. and we are geeting this error when we dont have internet connection 

Error from server (InternalError): error when creating "vmi.yml": Internal error occurred: failed calling webhook "virtualmachineinstances-create-validator.kubevirt.io": Post https://virt-api.kubevirt.svc:443/virtualmachineinstances-validate-create?timeout=4s: context deadline exceeded

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by phoracek** [comment]
Duplicates #4731
