### ISSUE TITLE
Automate the setup of TLS between apiservers i.e. using an initcontainer

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#474]
The soon-to-be-published user api server needs to be setup with TLS to communicate with the main api server. This set should be automated.

Today, the client certificate setup is manually, see:
https://github.com/kubevirt/kubevirt/compare/master...stu-gott:virt-apiserver#diff-b2a7383c09f070fdce170a8db48b9d6a

However, it would be interesting to understand if all the steps can be automated using an initContainer:
https://kubernetes.io/docs/concepts/workloads/pods/init-containers/

… except for the final approval.

This step can stay manual:
```kubectl certificate approve virt-apiserver-service.default```

The benefit would be, that the complete (secure, trnasport wise) deployment of KubeVirt would be a two step process:
- deploy yamls
- approve api server

This is much more user friendly than a 5+ step guide.

**Comment by fabiand** [comment]
@jhernand offered to look into this.

@stu-gott @jhernand you probably want to sync on this matter.

**Comment by rmohr** [comment]
Right now our components don't need this.
