### ISSUE TITLE
PVCs for the same VM getting assigned to different nodes

### ISSUE THREAD

**Issue by MarkSpencerTan** [kubevirt/kubevirt#4764]
/kind bug

**What happened**:
After a couple VMs have been deployed in our cluster that's using persistent storage, the VMs got stuck in Scheduled state and pods were reporting "volume node affinity conflict" error messages. We're not yet hitting any sort of cpu/memory restriction yet but we seem to be hitting a limit somewhere since if I were to delete a couple of VMs the VM would deploy as usual without any errors.

Anyone experienced this before?

Thanks

**What you expected to happen**:
VMIs go to Running State and deploy as usual

**How to reproduce it (as minimally and precisely as possible)**:
1) Deploy a couple VMs with Persistent storage enabled

**Anything else we need to know?**:

VM Pod describe logs attached to this gist:
https://gist.github.com/MarkSpencerTan/2bfb3623f719093047c85f4249f0941b
Node Describe:
https://gist.github.com/MarkSpencerTan/7643bd2e3acfd9f05cb8011eed76b534

**Environment**:
- KubeVirt version (use `virtctl version`): v0.32.0
- Kubernetes version (use `kubectl version`): v1.17.13
- OS (e.g. from /etc/os-release): Coreos

**Comment by MarkSpencerTan** [comment]
I noticed that there's some disk image pvcs for the same VM that are assigned in different Nodes for some reason. Is this okay?

For example, for one of the VMs, disk 1' pvc has the `volume.kubernetes.io/selected-node` set to worker node 2, whule disk 2's pvc is for node 4... Is this expected?

**Comment by MarkSpencerTan** [comment]
Seems like that is the issue why the pods are getting stuck is because of the PVCs not being bound to the same node for the same VM. I noticed the new version of kubevirt has a fix for a CDI issue: [PR #4025][brybacki] Adds a special handling for DataVolumes in WaitForFirstConsumer state to support CDI's delayed binding mode.

Can anyone confirm this will fix my issue? Or is it completely unrelated?

**Comment by MarkSpencerTan** [comment]
Deployed version 0.36.0 of kubevirt and the issue still persists

**Comment by MarkSpencerTan** [comment]
found out I had to enable feature gates for CDI to allow for WaitForFirstConsumer:

```yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: CDI
[...]
spec:
  config:
    featureGates:
    - HonorWaitForFirstConsumer
[...]
```

**Comment by yangxiaoliang** [comment]
> ```yaml
> featureGates
> ```

Hi,
I hit the same issue, could you guide me on how to enable the feature gates for cdi to allow for WFFC ?

Thanks very much.

**Comment by yangxiaoliang** [comment]
> > ```yaml
> > featureGates
> > ```
> 
> Hi,
> I hit the same issue, could you guide me on how to enable the feature gates for cdi to allow for WFFC ?
> 
> Thanks very much.

I found the way to enable this feature gate。
