### ISSUE TITLE
Report data from guest agent to VMI status field

### ISSUE THREAD

**Issue by mfranczy** [kubevirt/kubevirt#4767]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What you expected to happen**:
KubeVirt reports all crucial data from guest agent, this is a follow up on the discussion at https://github.com/kubevirt/kubevirt/pull/4217 and https://github.com/kubevirt/kubevirt/pull/4217#issuecomment-707126962

**Comment by mfranczy** [comment]
@rmohr @EdDev @AlonaKaplan would you like to have more fields reported than CIDR? 
Should I create another struct called `GuestAgentInfo` (or something like this)? Let's continue the discussion https://github.com/kubevirt/kubevirt/pull/4217#issuecomment-707126962 here.

**Comment by EdDev** [comment]
Hi @mfranczy , I would like to see the existing structs through which we parse the guest agent data be expose to the VMI status under a guest agent info subtree.

IMO all available data we current handle should be exposed there, but I will be glad to see at the minimum the interfaces ones: https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-launcher/virtwrap/agent-poller/agent_parser.go#L23
This will allow users to examine the inner guest information, especially the interfaces list, their names, actual mac address (not the desired one), IP addresses etc.
