### ISSUE TITLE
CRD REST coverage tool stopped working and artifacts are no longer uploaded

### ISSUE THREAD

**Issue by mfranczy** [kubevirt/kubevirt#4768]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
CRD coverage tool stopped working

**What you expected to happen**:
coverage artifacts are being uploaded after tests again

**Anything else we need to know?**:
after the bugfix we should merge https://github.com/kubevirt/project-infra/pull/726

the main reasons why the tool stopped working are:
* report is not being generated because the tool cannot find api/open-spec/swagger.json file (I think it's related to bazel change, further investiagation required)

* report is not saved because ARTIFACTS env cannot be read from the tests (probably bazel change too, have to take a closer look)

* report is empty because paths of the resources changed, in the past it was 
 `/apis/kubevirt.io/v1alpha3/namespaces/{namespace}/virtualmachineinstancemigrations/{name}`
now it is
`/apis/kubevirt.io/v1alpha3/namespaces/{namespace:[a-z0-9][a-z0-9\-]*}/virtualmachineinstancemigrations/{name:[a-z0-9][a-z0-9\-]*}`

The first two issues are related to KubeVirt, the last one is about the tool which is generating the artifact
https://github.com/mfranczy/crd-rest-coverage

**Comment by mfranczy** [comment]
@dhiller i've fixed the tool and released a new tag https://github.com/mfranczy/crd-rest-coverage/tree/v0.1.1, no I will take care of KubeVirt problems.

**Comment by mfranczy** [comment]
I think I should remove crd-rest-coverage implementation from KubeVirt itself and move it under kubevirt.io/qe-tools and create a rest coverage reporter there.

**Comment by mfranczy** [comment]
@dhiller wdyt?

**Comment by dhiller** [comment]
> I think I should remove crd-rest-coverage implementation from KubeVirt itself and move it under https://github.com/kubevirt/qe-tools and create a rest coverage reporter there.
> 
> In my opinion that makes a lot of sense and it fits reporter approach, wdyt @dhiller?

Makes total sense!

@qinqon FYI

**Comment by dhiller** [comment]
@mfranczy apologies, fell off my list :confused: I didn't find a PR over at qe-tools, do you have an estimate when this will land? I understand your bandwidth is not very high for this, maybe I can help somehow?

**Comment by mfranczy** [comment]
> @mfranczy apologies, fell off my list confused 
no worries, unfortunately it fell of my list too, since I was working on some other KubeVirt related projects.

I spoke with @rmohr a little bit about it, instead of creating a PR to qe-tools it will be better to ship a binary of the tool. Next week I have planned work only for KubeVirt upstream so if everything goes well I will finish this next week.
