### ISSUE TITLE
virtctl image-upload fail using raw images

### ISSUE THREAD

**Issue by arvin-a** [kubevirt/kubevirt#4776]
Is this a BUG REPORT or FEATURE REQUEST?:

/kind bug

**What happened**:
When attempting to upload a raw image using virtctl it always fails complaining about the image size being bigger than the PVC size. Regardless of the size specified the required size is always slightly more.

Example:
└──╼ virtctl image-upload dv fedora-rbd-raw2 --size=40G --storage-class=ocs-storagecluster-ceph-rbd --image-path=fedora.raw --namespace arvin --insecure --block-volume
DataVolume arvin/fedora-rbd-raw2 created
Waiting for PVC fedora-rbd-raw2 upload pod to be ready...
Pod now ready
Uploading data to https://cdi-uploadproxy-openshift-cnv.apps.ocp-infra1.arvhomelab.com

 4.00 GiB / 4.00 GiB [===================================================================================================] 100.00% 4m19s

{"component":"","level":"error","msg":"Error when closing file","pos":"os_helper.go:34","reason":"close fedora.raw: file already closed","timestamp":"2021-01-06T23:35:44.086829Z"}
unexpected return value 400, Saving stream failed: Virtual image size 40802189312 is larger than available size 40000000000. A larger PVC is required.

**What you expected to happen**:
The raw image successfully being uploaded to a PVC

**How to reproduce it (as minimally and precisely as possible)**:
Attempt to upload any raw image. I used fedora raw image from the link below
https://alt.fedoraproject.org/cloud/

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
Client Version: version.Info{GitVersion:"v0.36.0", GitCommit:"398cd404dba9ced6c298824a1bf681d387dd3a1c", GitTreeState:"clean", BuildDate:"2020-12-16T15:01:21Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}

Server Version: version.Info{GitVersion:"v0.34.2", GitCommit:"48956f60864ece98118d7894327caf7513c5b942", GitTreeState:"clean", BuildDate:"2020-12-07T23:39:10Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):
Using OpenShift cli
└──╼ oc version
Client Version: 4.6.9
Server Version: 4.6.9
Kubernetes Version: v1.19.0+7070803

- VM or VMI specifications:
KVM VM running server running RHEL 8.3
- Cloud provider or hardware configuration:
4 core
16GB memeory
60GB HD
- OS (e.g. from /etc/os-release):
NAME="Red Hat Enterprise Linux"
VERSION="8.3 (Ootpa)"
ID="rhel"
ID_LIKE="fedora"
VERSION_ID="8.3"
PLATFORM_ID="platform:el8"
PRETTY_NAME="Red Hat Enterprise Linux 8.3 (Ootpa)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8.3:GA"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"

REDHAT_BUGZILLA_PRODUCT="Red Hat Enterprise Linux 8"
REDHAT_BUGZILLA_PRODUCT_VERSION=8.3
REDHAT_SUPPORT_PRODUCT="Red Hat Enterprise Linux"
REDHAT_SUPPORT_PRODUCT_VERSION="8.3"

- Kernel (e.g. `uname -a`):
- Linux t640.arvhomelab.com 4.18.0-240.1.1.el8_3.x86_64 #1 SMP Fri Oct 16 13:36:46 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by phoracek** [comment]
Looks like a difference between giga bytes and gibibytes, could you  try specifying a bigger PVC?

/assign @mhenriks

**Comment by mhenriks** [comment]
Yeah, try `--size=40Gi`

**Comment by arvin-a** [comment]
That did the trick. Thanks!
