### ISSUE TITLE
Enable discard=unmap in vm xml for reclaiming space when using ceph rbd images.

### ISSUE THREAD

**Issue by ezio-auditore** [kubevirt/kubevirt#4781]
**Is this a BUG REPORT or FEATURE REQUEST?**:

  /kind enhancement

**What happened**:
Ceph-rbd images are thinly provisioned and after mounting in a vm(filesystem or block) they expand accordingly. After deleting files from the images the image size remains the same and thus ends up filling up the storage pool. Fstrim on the mounts also doesn't discard the expanded filesystem.

**What you expected to happen**:

After files are deleted from the images(mounted inside the vm) and on running fstrim the image size should be reclaimed.
**How to reproduce it (as minimally and precisely as possible)**:
1. Add a disk to a vm from ceph rbd storage class
2. Mount it in the vm and create a huge file in it.
3. Check the image size using below command
    ```
    rbd diff <rbd-pool-name>/<volume-name> |
    awk '{ SUM += $2 } END { print SUM/1024/1024/1024 " GB" }' 
    ```
4. Delete the file inside the mount.
5. Repeat step 3.
Detailed steps are in this note: https://hackmd.io/SSUTRWu-QWuj7GDGv27nLw

**Anything else we need to know?**:
The vm xml needs to contain `discard="unmap"` under DiskDriver. Upon testing with the same it works.
Fstrim is able to reclaim the space inside the image.

**Environment**:
- KubeVirt version (use `virtctl version`):
    ```
    Client Version: version.Info{GitVersion:"v0.36.0",         GitCommit:"398cd404dba9ced6c298824a1bf681d387dd3a1c", GitTreeState:"clean", BuildDate:"2020-12-16T15:01:21Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
    Server Version: version.Info{GitVersion:"v0.34.2", GitCommit:"48956f60864ece98118d7894327caf7513c5b942", GitTreeState:"clean", BuildDate:"2020-12-07T23:39:10Z", GoVersion:"go1.13.15", Compiler:"gc", Platform:"linux/amd64"}
    ```
- Kubernetes version (use `kubectl version`):
  Using Openshift CLI
    ```
    oc version
    Client Version: 4.5.6
    Server Version: 4.6.3
    Kubernetes Version: v1.19.0+9f84db3
    ```
- VM or VMI specifications:
    KVM VM running server running Red Hat Enterprise Linux CoreOS 46.82.202010301241-0
- Cloud provider or hardware configuration:
    64 cores
    500 GB memory
    Ceph rbd using OCS as a provisioner
- OS (e.g. from /etc/os-release):
    ```
    NAME="Red Hat Enterprise Linux CoreOS"
    VERSION="46.82.202010301241-0"
    VERSION_ID="4.6"
    OPENSHIFT_VERSION="4.6"
    RHEL_VERSION="8.2"
    PRETTY_NAME="Red Hat Enterprise Linux CoreOS 46.82.202010301241-0 (Ootpa)"
    ID="rhcos"
    ID_LIKE="rhel fedora"
    ANSI_COLOR="0;31"
    CPE_NAME="cpe:/o:redhat:enterprise_linux:8::coreos"
    HOME_URL="https://www.redhat.com/"
    BUG_REPORT_URL="https://bugzilla.redhat.com/"
    REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
    REDHAT_BUGZILLA_PRODUCT_VERSION="4.6"
    REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
    REDHAT_SUPPORT_PRODUCT_VERSION="4.6"
    OSTREE_VERSION='46.82.202010301241-0'
    ```
- Kernel (e.g. `uname -a`):
    Linux host 4.18.0-193.28.1.el8_2.x86_64 #1 SMP Fri Oct 16 13:38:49 EDT 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by phoracek** [comment]
Bug scrub: This is something we'd like to have in KubeVirt.

**Comment by ezio-auditore** [comment]
Hi @phoracek can this be assigned to me? I would like to start contributing to the Kubevirt space.
I have also documented a workaround for the same, let me know your thoughts.
[Workaround for RBD disk reclaim issue](https://hackmd.io/ZHEVaJEWQ0C3Rl-AmtsvEw?view)

**Comment by phoracek** [comment]
Hello! Sure thing, assigning. I can't speak for the workaround though, it's far from my domain.

/assign @ezio-auditore
