### ISSUE TITLE
 make rpm-deps error 

### ISSUE THREAD

**Issue by zhlhahaha** [kubevirt/kubevirt#4782]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind bug

**What happened**:
```
 # make rpm-deps
...
Error: failed to fetch repomd.xml for 32-x86_64-update-repo: Expected sha256 sum e19670947fb3bd2c290dce9b8464613a10cc7d0ff1b68c168decf8711c26430a, but got 85bb2fdb14b11549554e19ed3bc903271ddc740442366f693a53439f80a58162
...
```
**What you expected to happen**:
`make rpm-deps` run success

**How to reproduce it (as minimally and precisely as possible)**:
`make rpm-deps`

**Environment**:
- OS (e.g. from /etc/os-release): Ubuntu 20.04 LTS
- Kernel (e.g. `uname -a`): Linux entos-x86-desktop-03 5.9.0+
- Git commit: 5df851b3cb4611eee39e3fe2ebaa99361e0e5d16

**Comment by zhlhahaha** [comment]
@rmohr

**Comment by zhlhahaha** [comment]
Hi Roman, I found the repomd.xml sha256 is under tag <mm0:alternate> as following image, and bazeldnf only use the first sha256 to verify repomd.xml.
![image](https://user-images.githubusercontent.com/5655282/104282814-8ecfde00-54ea-11eb-84c8-4cddea4e794f.png)

**Comment by rmohr** [comment]
> Hi Roman, I find that, in the metalink file, the correct repomd.xml sha256 is under tag `<mm0:alternate>` as following image, and bazeldnf use the first sha256 to verify repomd.xml.

Thanks. I think this is fine. I intentionally want to use the latest state. The alternative ones represent older states. I think the main issue was that not every mirror url which you get represented necessarily has the latest state mirrored already. I did not properly check the http return code and created the shasum of a 404 response. Instead the code should just go on to the next mirror urls.

**Comment by zhlhahaha** [comment]
> > Hi Roman, I find that, in the metalink file, the correct repomd.xml sha256 is under tag `<mm0:alternate>` as following image, and bazeldnf use the first sha256 to verify repomd.xml.
> 
> Thanks. I think this is fine. I intentionally want to use the latest state. The alternative ones represent older states. I think the main issue was that not every mirror url which you get represented necessarily has the latest state mirrored already. I did not properly check the http return code and created the shasum of a 404 response. Instead the code should just go on to the next mirror url.

Thanks, clear explanation. I will close this issue.
