### ISSUE TITLE
Issue downgrading from v0.36.0

### ISSUE THREAD

**Issue by MarkSpencerTan** [kubevirt/kubevirt#4797]
/kind bug

**What happened**:

I tried to downgrade from v0.36.0 to v0.35.0 by updating the kubevirt-operator.yaml but it only seemed to update the kubevirt-operator pods and not the others. Seemed to have gotten stuck at the kubevirt-cr.

Attaching describe logs from the kubevirt CR:
https://gist.github.com/MarkSpencerTan/676eea2e2f01ae733ff6a9766ab7f68f

**What you expected to happen**:
the kubevirt-operator being updated to the older version should've triggered a new deployment for the virt-api, virt-controller, virt-handler but it didn't.

**How to reproduce it (as minimally and precisely as possible)**:
1. Upgrade to v0.36.0
2. Downgrade to v0.35.0
3. *might have to repeat if necessary, I think it worked once for me one time, but screwed me the other times :)

**Comment by rmohr** [comment]
@davidvossel @ashleyschuett FYI

**Comment by davidvossel** [comment]
If you want to downgrade, the only option that we can reliably make work is for you to continue to use the 0.36.0 operator to downgrade /install the older v0.35.0 version of kubevirt. This would be accomplished by editing the kubevirt CR's `kubectl get kubevirt -n kubevirt kubevirt` image tag to point to v0.36.0.

Example:

```
apiVersion: kubevirt.io/v1alpha3
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  imageTag: v0.35.0
```

The reason for this is that the operator's rbac has to have permissions capable of installing both the current version (v0.36.0) and the desired version (v0.35.0). Only the v0.36.0 operator can do this transition.

**Comment by MarkSpencerTan** [comment]
@davidvossel thank you for your response, I tried adding the imageTag to the kubevirt cr, it deployed a kubevirt pod to the kubevirt namespace, succeeded and exited, however it didn't deploy the new versions to the other kubevirt components.

https://gist.github.com/MarkSpencerTan/accd28d8fce97eed787d757db1e7bafa

**Comment by davidvossel** [comment]
> @davidvossel thank you for your response, I tried adding the imageTag to the kubevirt cr, it deployed a kubevirt pod to the kubevirt namespace, succeeded and exited, however it didn't deploy the new versions to the other kubevirt components.
> https://gist.github.com/MarkSpencerTan/accd28d8fce97eed787d757db1e7bafa

are you positive that the virt-operator installed on your cluster is v0.36.0? This error is what i'd expect with the v0.35.0 operator trying to transition an install from v0.36.0 to v0.35.0

**Comment by MarkSpencerTan** [comment]
@davidvossel ahhh I didn't know the operator had to be v0.36.0! It was still v0.35.0 when I tried to downgrade by updating the kubevirt-operator route.

Was able to get it downgraded by doing the following:
1. upgraded kubevirt-operator to v0.36.0 again
2. added imageTag: v0.35.0 on kubevirt-cr
3. manually downgraded the kubevirt-operator to v0.35.0 (I guess the imageTag doesn't downgrade the operator itself?)

Thank you for the help, I'll be using this method going on forward!
