### ISSUE TITLE
Issue with extra disks behaving differently after v0.36.0 update

### ISSUE THREAD

**Issue by MarkSpencerTan** [kubevirt/kubevirt#4800]
/kind bug

**What happened**:
After I updated Kubevirt from v0.35.0 to v0.36.0, I noticed issues with my VM not able to properly format/mount the primary and secondary disks I've added to the VM. There's a bootloader disk that has the main kernel/os that is responsible for formatting and mounting the said disk and it failed to do so. I was wondering what was a change in v0.36.0 that could have caused this behavior.

To give a general background of the VM's spec, we have 4 disks in total for this particular one in the [example](https://gist.github.com/MarkSpencerTan/c49001b07fa4d1636e826fd8ac501d4f)
 The bootloader disk is the primary boot disk which has the kernel and Grub installed to boot the kernel. is-disk-1 is just an empty primary disk that would get formatted/mounted by the os. is-disk-2 and is-disk-3 are preformatted raid disks that just gets mounted by the os.

I've discussed with @rmohr and he mentioned it might've been due to controller changes in the new versions of qemu/libvirt. I'm attaching the domain logs and qemu arguments as a reference so we can see what was changed:

[v0.35.0 domain XML](https://gist.github.com/MarkSpencerTan/aae3f309a64008250ef94857bb1855f7)
[v0.35.0 Qemu arguments](https://gist.github.com/MarkSpencerTan/1a10e70bd68247d38800cc138935e88c)
[v0.36.0 domain XML](https://gist.github.com/MarkSpencerTan/5b72f5300547b1e58fd2ad2dd75f6c46)
[v0.36.0 Qemu arguments](https://gist.github.com/MarkSpencerTan/5066299810182a9e372dd3a22065c0d5)

**What you expected to happen**:
VM spins up and the kernel/os formats and mounts the disks properly pre v0.36.0

**Anything else we need to know?**:
I've noticed in the libvirt logs a couple warnings in the v0.36.0 version... not sure if it's related to the issue or if it's any concern: [Libvirt warnings](https://gist.github.com/MarkSpencerTan/a13f113717c597975d2cf1d8c7fdfc34)

[Domain XML Diffs](https://www.diffchecker.com/FjYR12J5)
[Qemu Diffs](https://www.diffchecker.com/4YCYiNAt)

**Environment**:
- KubeVirt version (use `virtctl version`): v0.36.0
- Kubernetes version (use `kubectl version`): v1.15.0 & v1.17.0
- VM or VMI specifications: https://gist.github.com/MarkSpencerTan/c49001b07fa4d1636e826fd8ac501d4f

**Comment by MarkSpencerTan** [comment]
Updated v0.32.0 gist to v0.35.0 gists

**Comment by MarkSpencerTan** [comment]
tried to override machine type to: pc-q35-rhel8.2.0 since that was one of the diffs from the domain, but it didn't do anything

**Comment by phoracek** [comment]
@mhenriks could you take a look?

**Comment by MarkSpencerTan** [comment]
updated to v0.37.0 and same issue persists

**Comment by rmohr** [comment]
What I see is that you end up with different pci addresses. You could try setting them on the yaml. The guest operating system could discover then in the order which you need.

**Comment by MarkSpencerTan** [comment]
@rmohr how do I go about adding that on the yaml? is that a new feature that was added recently?

I also noticed this new virtio-scsi block that was added, do you know what might've caused it to appear?:
```bash

<controller type='scsi' index='0' model='virtio-scsi'>
--
  |   |   | <alias name='scsi0'/>
  |   |   | <address type='pci' domain='0x0000' bus='0x06' slot='0x00' function='0x0'/>
  |   |   | </controller>


```

**Comment by rmohr** [comment]
> @rmohr how do I go about adding that on the yaml? is that a new feature that was added recently?

Ah forget it. That are sata disks. We have a field for pci addresses: https://kubevirt.io/api-reference/master/definitions.html#_v1_disktarget but that does not help here, since the pci address which changed is on the sata controller. Controller can't be configured in kubevirt at the moment.

> I also noticed this new virtio-scsi block that was added, do you know what might've caused it to appear?:

That was added for disk hotplug support. You can get rid of by setting `disableHotplug` to `true` in the devices section: https://kubevirt.io/api-reference/master/definitions.html#_v1_devices. Maybe that helps.

**Comment by MarkSpencerTan** [comment]
ahh that was it @rmohr ! Thank you for the help to suggest disabling the Hotplug feature! Yeah with the hotplug stuff disabled, all the controllers and addresses looks the same and the kernel was able to format/mount the additional disks!

**Comment by rmohr** [comment]
/reopen

Great that it helped, my main concern is that we may still break you in the future without any workaround for you. We would have to allow managing controller addresses (and possibly sata addresses), but we wanted to avoid that. I am reopening the issue, since one of our main goals is supporting legacy workloads which you just can't change.

**Comment by MarkSpencerTan** [comment]
Sounds great @rmohr, this would definitely be appreciated for our workloads
