### ISSUE TITLE
Remove the docs directory from PR testing 

### ISSUE THREAD

**Issue by ezrasilvera** [kubevirt/kubevirt#4805]
/kind enhancement

**What happened**:
When changing MD files under docs directory all tests are triggered. 

**What you expected to happen**:
Don't run code/functional test tests on document changes

**Comment by dhiller** [comment]
I have had a look at [Golang RE2 Syntax](https://github.com/google/re2/wiki/Syntax). This unfortunately does not support negative lookahead. So I don't see any easy solution to this (besides moving docs folder into another repo, which we surely do not want).

**Comment by phoracek** [comment]
This would require a lot of work to get the RE going while we don't have that many doc-only PRs coming in.
