### ISSUE TITLE
make bazel-build-images failure

### ISSUE THREAD

**Issue by zhlhahaha** [kubevirt/kubevirt#4811]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
`make bazel-build-images` failed

```
ERROR: /root/go/src/kubevirt.io/kubevirt/BUILD.bazel:151:16: //:passwd-image depends on @go_image_base//image:image in repository @go_image_base which failed to fetch. no such package '@go_image_base//image': Pull command failed: 2021/01/15 02:13:03 Running the Image Puller to pull images from a Docker Registry...
2021/01/15 02:13:03 Image pull was unsuccessful: reading image "gcr.io/distroless/base@sha256:e37cf3289c1332c5123cbf419a1657c8dad0811f2f8572433b668e13747718f8": error getting credentials - err: exec: "docker-credential-gcloud": executable file not found in $PATH, out: ``
 (/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/go_puller_linux/file/downloaded -directory /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/go_image_base/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name gcr.io/distroless/base@sha256:e37cf3289c1332c5123cbf419a1657c8dad0811f2f8572433b668e13747718f8)
ERROR: Analysis of target '//cmd/virt-operator:version-container' failed; build aborted: Analysis failed

```

**What you expected to happen**:
`make bazel-build-images` success

**How to reproduce it (as minimally and precisely as possible)**:
Get the master branch, and run `make bazel-build-images`

**Environment**:
- OS (e.g. from /etc/os-release): ubuntu 18.04
- Kernel (e.g. `uname -a`): 5.9.0+
- Others: master branch (commit: 573bbc639730f45dc033ef87fc0755c388024ee4)

**Comment by zhlhahaha** [comment]
Can be overcame by run following commands
```
rm -rf ~/.docker
```

**Comment by Kate-DONG** [comment]
Do you know how to overcome this mistake when we run `make`?

`ERROR: An error occurred during the fetch of repository 'go_image_base':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/io_bazel_rules_docker/container/pull.bzl", line 189, column 13, in _impl
                fail("Pull command failed: %s (%s)" % (result.stderr, " ".join([str(a) for a in args])))
Error in fail: Pull command failed: Timed out (/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/go_puller_linux_amd64/file/downloaded -directory /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/go_image_base/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name gcr.io/distroless/base@sha256:8d58596f5181f95d908d7f8318f8e27bc394164491bd0aa53c2f284480fd8f8b)
ERROR: /root/go/src/kubevirt.io/kubevirt/BUILD.bazel:158:16: //:passwd-image depends on @go_image_base//image:image in repository @go_image_base which failed to fetch. no such package '@go_image_base//image': Pull command failed: Timed out (/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/go_puller_linux_amd64/file/downloaded -directory /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/go_image_base/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name gcr.io/distroless/base@sha256:8d58596f5181f95d908d7f8318f8e27bc394164491bd0aa53c2f284480fd8f8b)
ERROR: Analysis of target '//cmd/virt-controller:virt-controller-image' failed; build aborted: Analysis failed
INFO: Elapsed time: 601.295s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)`

**Comment by Kate-DONG** [comment]
@zhlhahaha 
Do you know how to overcome this mistake when we run `make`?

`ERROR: An error occurred during the fetch of repository 'go_image_base':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/io_bazel_rules_docker/container/pull.bzl", line 189, column 13, in _impl
                fail("Pull command failed: %s (%s)" % (result.stderr, " ".join([str(a) for a in args])))
Error in fail: Pull command failed: Timed out (/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/go_puller_linux_amd64/file/downloaded -directory /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/go_image_base/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name gcr.io/distroless/base@sha256:8d58596f5181f95d908d7f8318f8e27bc394164491bd0aa53c2f284480fd8f8b)
ERROR: /root/go/src/kubevirt.io/kubevirt/BUILD.bazel:158:16: //:passwd-image depends on @go_image_base//image:image in repository @go_image_base which failed to fetch. no such package '@go_image_base//image': Pull command failed: Timed out (/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/go_puller_linux_amd64/file/downloaded -directory /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/go_image_base/image -os linux -os-version  -os-features  -architecture amd64 -variant  -features  -name gcr.io/distroless/base@sha256:8d58596f5181f95d908d7f8318f8e27bc394164491bd0aa53c2f284480fd8f8b)
ERROR: Analysis of target '//cmd/virt-controller:virt-controller-image' failed; build aborted: Analysis failed
INFO: Elapsed time: 601.295s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (0 packages loaded, 0 targets configured)`

**Comment by zhlhahaha** [comment]
> gcr.io/distroless/base@sha256:8d58596f5181f95d908d7f8318f8e27bc394164491bd0aa53c2f284480fd8f8b) ERROR: /root/go/src/kubevirt.io/kubevirt/BUILD.bazel:158:16: //:passwd-image depends on @go_image_base//image:image in repository @go_image_base which failed to fetch. no such package '@go_image_base//image': Pull command failed: Timed out (/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/go_puller_linux_amd64/file/downloaded -directory /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/go_image_base/image -os linux -os-version -os-features -architecture amd64 -variant -features -name 

It seems that pull "go_image_base" failed. You can find detailed information about the image in `WORKSPACE`. Then you can give it a try to pull the image directly via `docker pull`.

**Comment by Kate-DONG** [comment]
thanks, i'll try it.

**Comment by Kate-DONG** [comment]
@zhlhahaha thanks for your advice.
     well, i has tried pulling the image `gcr.io/distroless/base`  into the address `/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/go_image_base/image`, after running `make`, and pulling the image into docker images, but there is still the mistake, so did i do something wrong?

**Comment by zhlhahaha** [comment]
> @zhlhahaha thanks for your advice.
> well, i has tried pulling the image `gcr.io/distroless/base` into the address `/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/go_image_base/image`, after running `make`, and pulling the image into docker images, but there is still the mistake, so did i do something wrong?

There are two possible reason that may lead to time out.
1. network issue, which means you can not connect to the repository. 
2. the image tag is out of date.
So you can pull the image via `docker pull` right? I just want to make sure there is no network issue that leads to bazel pull image failure. If the network is fine, and the go_image_base exists, I do not know why `TIMEOUT` in `bazel build`. Maybe you can try to run `bazel clean` and then remove all bazel cache (~/.cache/bazel/). And do `bazel build` again.

**Comment by Kate-DONG** [comment]
> > @zhlhahaha thanks for your advice.
> > well, i has tried pulling the image `gcr.io/distroless/base` into the address `/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/go_image_base/image`, after running `make`, and pulling the image into docker images, but there is still the mistake, so did i do something wrong?
> 
> There are two possible reason that may lead to time out.
> 
> 1. network issue, which means you can not connect to the repository.
> 2. the image tag is out of date.
>    So you can pull the image via `docker pull` right? I just want to make sure there is no network issue that leads to bazel pull image failure. If the network is fine, and the go_image_base exists, I do not know why `TIMEOUT` in `bazel build`. Maybe you can try to run `bazel clean` and then remove all bazel cache (~/.cache/bazel/). And do `bazel build` again.

thanks， i'll check it with our parters.

**Comment by zhlhahaha** [comment]
> > @zhlhahaha thanks for your advice.
> > well, i has tried pulling the image `gcr.io/distroless/base` into the address `/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/go_image_base/image`, after running `make`, and pulling the image into docker images, but there is still the mistake, so did i do something wrong?
> 
> There are two possible reason that may lead to time out.
> 
> 1. network issue, which means you can not connect to the repository.
> 2. the image tag is out of date.
>    So you can pull the image via `docker pull` right? I just want to make sure there is no network issue that leads to bazel pull image failure. If the network is fine, and the go_image_base exists, I do not know why `TIMEOUT` in `bazel build`. Maybe you can try to run `bazel clean` and then remove all bazel cache (~/.cache/bazel/). And do `bazel build` again.

I just see you use `make`, so just run `make clean`

**Comment by Kate-DONG** [comment]
> make clean
ok, thanks

**Comment by gitchong** [comment]
I have the same problem, how can I solve it

**Comment by gitchong** [comment]
> I have the same problem, how can I solve it

docker proxy is useless， tag image and push custom registry

modify WOEKSPACE file 
container_pull(
    name = "go_image_base",
    digest = "sha256:f65536ce108fcc41cdcd5cb101006fcb82b9a1527409263feb9e34032f00bda0",
    registry = "docker.io",
    repository = "xxx/base",
)

**Comment by DavidSpek** [comment]
This seems to be related to entries in `~/.docker/config.json` if you've previously setup authentication for GCR. Removing only that file solves the problem or you can simple remove the GCR entry. I simply backed it up and removed it temporarily to run the build.

**Comment by mashail** [comment]
> Can be overcame by run following commands
> 
> ```
> rm -rf ~/.docker
> ```

Very useful thank you
