### ISSUE TITLE
make cluster-up failure

### ISSUE THREAD

**Issue by zhlhahaha** [kubevirt/kubevirt#4813]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
`make cluster-up` get following error
```
# make cluster-up
./cluster-up/up.sh
Download the image docker.io/kubevirtci/k8s-1.18:2101111509-e550ba6
time="2021-01-15T02:34:26Z" level=info msg="Using local image kubevirtci/k8s-1.18:2101111509-e550ba
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x8841d7]

goroutine 1 [running]:
kubevirt.io/kubevirtci/cluster-provision/gocli/cmd.run(0xc000245b80, 0xc0000c10e0, 0x1, 0x11, 0x0,
        /home/prow/go/src/github.com/kubevirt/kubevirtci/cluster-provision/gocli/cmd/run.go:266 +0x
github.com/spf13/cobra.(*Command).execute(0xc000245b80, 0xc0000c0fc0, 0x11, 0x12, 0xc000245b80, 0xc
        /home/prow/go/src/github.com/kubevirt/kubevirtci/cluster-provision/gocli/vendor/github.com/
github.com/spf13/cobra.(*Command).ExecuteC(0xc000245180, 0x881ff6, 0x9a5ab2, 0x12)
        /home/prow/go/src/github.com/kubevirt/kubevirtci/cluster-provision/gocli/vendor/github.com/
github.com/spf13/cobra.(*Command).Execute(...)
        /home/prow/go/src/github.com/kubevirt/kubevirtci/cluster-provision/gocli/vendor/github.com/
kubevirt.io/kubevirtci/cluster-provision/gocli/cmd.Execute()
        /home/prow/go/src/github.com/kubevirt/kubevirtci/cluster-provision/gocli/cmd/root.go:46 +0x
main.main()
        /home/prow/go/src/github.com/kubevirt/kubevirtci/cluster-provision/gocli/cmd/cli/main.go:8
make: *** [Makefile:122: cluster-up] Error 2
```

**What you expected to happen**:
`make cluster-up` run success

**How to reproduce it (as minimally and precisely as possible)**:
pull the master branch, and run `make cluster-up`

**Environment**:
- OS (e.g. from /etc/os-release): ubuntu 18.04
- Kernel (e.g. `uname -a`): Linux entos-x86-desktop-03 5.9.0+ #5 SMP Thu Nov 12 07:40:27 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Others: kubevirt master branch(commit: 573bbc639730f45dc033ef87fc0755c388024ee4)

**Comment by xpivarc** [comment]
@zhlhahaha can you make sure you don't have any running or even leftover containers(`docker ps -a`)?

**Comment by vasiliy-ul** [comment]
I faced similar problem with `SIGSEGV` a couple of times. In my case running `make cluster-down` and then `make cluster-up` solved the issue. Looks like there were some remaining leftovers from my prev cluster session which were preventing to bring up a new one. According to my observations that happens e.g. if you reboot the host machine while the cluster is still running (without shutting it down with `make cluster-down`). The `SIGSEGV` error is liklely to happen when you run `make cluster-up` in that case.

**Comment by zhlhahaha** [comment]
> @zhlhahaha can you make sure you don't have any running or even leftover containers(`docker ps -a`)?

Yes you are right. After I clear up all container. `make cluster-up` works fine now.
