### ISSUE TITLE
Drop libvirt-daemon-driver-storage for libvirt v6.9.0+

### ISSUE THREAD

**Issue by andreabolognani** [kubevirt/kubevirt#4825]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:

As of libvirt 6.9.0, the QEMU driver no longer unnecessarily depends on the storage driver, and so it should be possible to stop including the `libvirt-daemon-driver-storage-core` package in containers once a newer libvirt version is imported.

**Anything else we need to know?**:

Original issue: https://github.com/kubevirt/libvirt/issues/61
libvirt fix: https://gitlab.com/libvirt/libvirt/-/commit/accdc0e7730739f398e392c23bc8380d3574a878

**Comment by phoracek** [comment]
AFAIK we are currently using libvirt 6.6. Keeping this issue as a tracker.

**Comment by andreabolognani** [comment]
> AFAIK we are currently using libvirt 6.6. Keeping this issue as a tracker.

Yup, that was the intention :)
