### ISSUE TITLE
[flaky CI]Storage Starting a VirtualMachineInstance [rfe_id:2298] With HostDisk and PVC initialization With a HostDisk defined With 'DiskExists' type [test_id:2306]Should use existing disk image and start

### ISSUE THREAD

**Issue by maya-r** [kubevirt/kubevirt#4830]
/kind bug
/triage build-watcher

Failed in this run: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4806/pull-kubevirt-e2e-k8s-1.19/1350711756128784384

Unexpected Warning event received: testvmi-ntszw,6955d6a4-8510-4983-82d0-82597fa777d7: server error. command SyncVMI failed: "LibvirtError(Code=38, Domain=18, Message='Cannot access storage file '/var/run/kubevirt-private/vmi-disks/host-disk/disk-aaadbb2d-c58d-4b6f-a029-60d7e21a5a19.img': No such file or directory')"

**Comment by awels** [comment]
Happen again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5126/pull-kubevirt-e2e-k8s-1.18/1366465375138484224

**Comment by fabiand** [comment]
… and again

**Comment by fabiand** [comment]
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5214/pull-kubevirt-e2e-k8s-1.19/1370738271901978624
