### ISSUE TITLE
[flaky CI]HookSidecars [rfe_id:2667][crit:medium][vendor:cnv-qe@redhat.com][level:component] VMI definition with SM BIOS hook sidecar should not start with hook sidecar annotation when the version is not provided

### ISSUE THREAD

**Issue by maya-r** [kubevirt/kubevirt#4834]
/kind bug
/triage build-watcher

Failed here:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4806/pull-kubevirt-e2e-k8s-1.17/1349789116002209792

could not retrieve the VMI pod: <nil>

**Comment by awels** [comment]
/reopen

Happened again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5139/pull-kubevirt-e2e-k8s-1.20/1367373235062050816
