### ISSUE TITLE
[flaky CI][ref_id:1182]Probes for readiness should succeed [test_id:1202][posneg:positive]with working TCP probe and tcp server on ipv4

### ISSUE THREAD

**Issue by maya-r** [kubevirt/kubevirt#4836]
/kind bug
/triage build-watcher

Failed here: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4779/pull-kubevirt-e2e-k8s-1.17/1350742207136534528

**Comment by arnongilboa** [comment]
Looks quite similar:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5128/pull-kubevirt-e2e-k8s-1.18/1368540049833988096

/reopen

**Comment by oshoval** [comment]
Again
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5167/pull-kubevirt-e2e-k8s-1.19/1369075071338942464

@phoracek should we mark it sig network ?

**Comment by phoracek** [comment]
@oshoval what are you asking? Whether to mark test_id:1202 as sig-network too?

test_id is owned by Red Hat QE, they should be the ones deciding about it.

**Comment by oshoval** [comment]
meant either that or if to mark this issue as sig-network
ok thx
