### ISSUE TITLE
v0.37.0 configmap and emulation variable incorrect ? 

### ISSUE THREAD

**Issue by bhkamath** [kubevirt/kubevirt#4843]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

- kubevirt initiated testvm pod was always in pending state.
- virtctl console testvm failed to launch

**What you expected to happen**:

Expected to get console prompt of testvm

**How to reproduce it (as minimally and precisely as possible)**:

Installation of kubevirt 0.37.0; no additional configuration required.  However, the Kubernetes nodes must be a VM

**Anything else we need to know?**:

Referring to earlier similar issue, suspect was with setting up of emulation variable in the configmap file.  The value of useEmulation variable was set to "true".  However, the variable name was incorrect, was debug-useEmulation instead of debug.useEmulation and restarting got it to working.

Changing the variable names in "data:" and "managedFields:" + "fieldsV1:" + "f:data:" got the testvm running.

apiVersion: v1
data:
  **debug.useEmulation**: "true"

  managedFields:
  - apiVersion: v1
    fieldsType: FieldsV1
    fieldsV1:
      f:data:
        .: {}
        f:**debug.useEmulation**: {}
    manager: kubectl

**Environment**:
- KubeVirt version:
        Client Version: version.Info{GitVersion:"v0.37.0",     GitCommit:"e7bb186ff71a565732da0a5ef979016feff51236", GitTreeState:"clean", BuildDate:"2021-01-18T21:20:11Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
        Server Version: version.Info{GitVersion:"v0.37.0-dirty", GitCommit:"e7bb186ff71a565732da0a5ef979016feff51236", GitTreeState:"dirty", BuildDate:"2021-01-18T21:40:27Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version:
        Client Version: v1.18.3
        Server Version: v1.18.15

        Kubernetes master and worker nodes were realized on virtual machines [QEMU] of CentOS 7.

- VM or VMI specifications:
         kubectl get vmi -o wide
NAME     AGE   PHASE     IP            NODENAME       LIVE-MIGRATABLE   PAUSED
testvm   17m   Running   10.244.2.15   k8s-worker-2   False             

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
       cat /etc/os-release 
       NAME="CentOS Linux"
       VERSION="7 (Core)"
       ID="centos"

- Kernel (e.g. `uname -a`):
       Linux k8s-master 3.10.0-1160.11.1.el7.x86_64 #1 SMP Fri Dec 18 16:34:56 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by phoracek** [comment]
@bhkamath do your hosts support nested virtualization? The issue seems to be related to the lack of it.

**Comment by bhkamath** [comment]
I am not certain how I be able to inspect this support.  I have CentOS 7 on my Baremetal system with three virtual machines (also running CentOS 7).  These VM's were created using VMM.  Kubernetes platform was created over these virtual machines.

For experimentation purposes, I had installed kubevirt.  This is a scenario of Kubevirt-VM inside CentOS-7-VMM VM.

On modifying the key name in the said segments, it appears to have solved the issue.  Of course I just worked on testvm with a console interaction.

**Comment by phoracek** [comment]
@bhkamath  I think I understand now. May I ask from where you got the original (wrong) key name? So we could fix the docs.

**Comment by ashleyschuett** [comment]
@bhkamath where you following this guide https://github.com/ContainerCraft/Kargo/blob/main/kubevirt/donor/build.log ?

**Comment by bhkamath** [comment]
It is quite possible that I would have referred to document with statement, "kubectl create configmap kubevirt-config -n kubevirt --from-literal debug-useEmulation=true".  I am unable to spot my specific reference.

Thanks for your follow-up.
