### ISSUE TITLE
Provide online KubeVirt API documentation

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt/kubevirt#485]
After #476 is merged, it would be nice to make a online KubeVirt API documentation.

Story:
How do we publish the API documentation? We could:
Use travis to build the swagger documentation, commit this to a repo, and let this repo be published by gitbook with a plugin.
This could be a good intermediate solution.

So far this is a plan:

- [x] Create repo for [API Reference](https://github.com/kubevirt-incubator/api-reference)
- [x] Add script to travis to generate swagger.json
- [x] Translate swagger.json spec 1.2 to 2.0 using go-restful-openapi
- [x] Push into doc repository

**Comment by lukas-bednar** [comment]
@rmohr I remember that on meeting you were talking about offline generation of `swagger.json` file.
I was searching for some options and I found this one: https://github.com/yvasiyarov/swagger (https://goswagger.io/generate/spec.html)

Is this the path to go? or you had something else in mind ?

**Comment by lukas-bednar** [comment]
On behalf of @davidvossel , Thank you for awesome hint!

> Proposal: test for a json file in travis--generated by “make generate”
Changes to API require re-running

Unfortunately in order to get `openapi.json` I need running KubeVirt,
so I can not do it in TravisCI job, I will have to move to Jenkins job which execute tests.

Then the flow will be like this:
* put current `openapi.json` into repository
* when KubeVirt is running obtain API specification
* compare it with existing `openapi.json` from repository
* if API was changed fail a job -> need to re-generate `openapi.json` and commit it

**Comment by davidvossel** [comment]
@lukas-bednar Is it possible to give the virt-api server a flag that will make it immediately dump the openapi.json file and exit instead of actually starting the http server?

**Comment by lukas-bednar** [comment]
@davidvossel I saw some examples in `go-restful-openapi` repository how to do that:

https://github.com/emicklei/go-restful-openapi/blob/0d037b269a5b53b582789e25dee0d0a0614119e5/examples/user-resource_test.go#L28

I will try to do that, thanks!

**Comment by lukas-bednar** [comment]
@davidvossel  I was able to do it. but in order to execute `virt-api` it requires kubeconfig file.
And I don't have this file available at build time.
You can take a look at patch here #535 .

**Comment by lukas-bednar** [comment]
@fabiand I got this issue into state, where I have everything ready to let GitBook to render it.

I have `api/openapi-spec/swagger.json` in KubeVirt repository.
Now I can let GitBook to render it. I have following patch which adds necessary configuration for gitbook.
https://github.com/lukas-bednar/kubevirt/commit/a8cb189fcd9282ae8fac7cc2a7be30eb9a6ca202

This is how it looks like: https://lukas-bednar.gitbooks.io/kubevirt-api-documentation/content/

I would appreciate some input from you, whether it matches your expectation. Or you want me to do something else. Or make it part of some other document or whatever ...
Thanks.

**Comment by fabiand** [comment]
Great progress.

I was looking at the link, and a few notes:
The links are broken, not sure what is causing it.
I also wonder, if this large api is suited for that way of presentation.

I actually wonder if we can rather use your work to create a reference similar to Kubernetes one, see https://v1-7.docs.kubernetes.io/docs/api-reference/v1.7/

Do you know how this is getting created, @lukas-bednar ?

**Comment by lukas-bednar** [comment]
@fabiand I took advice from @rmohr and I was able to generate html documentation using `swagger2markdown-converter` and `asciidoctor`.

It looks like this:
![kubevirt-api-doc](https://user-images.githubusercontent.com/1505684/32493517-6743e568-c3be-11e7-9f86-d527d068da5f.png)

I didn't get any response from K8S https://groups.google.com/forum/#!topic/kubernetes-users/xGRzQISSxVs

If you are satisfied with `asciidoctor` I can proceed with that ... and I need some details how & wher  are we going to publish this API reference.

**Comment by rmohr** [comment]
looks very similar to the one from k8s. See also https://github.com/kubernetes/kubernetes/blob/8fd414537b5143ab039cb910590237cabf4af783/hack/gen-swagger-doc/gen-swagger-docs.sh for the exact postprocessing, after they have invoked gradle.

**Comment by lukas-bednar** [comment]
@rmohr please take a look at #550 , I adapted K8S post-processing script to generate api reference documentation.

**Comment by rmohr** [comment]
> If you are satisfied with asciidoctor I can proceed with that ... and I need some details how & wher are we going to publish this API reference.

I wonder if we can add it to the user-guide repo (e.g. letting travis do an automatic build and do a commit to the user-guide repo). But I am not sure how we can add such an "external" file to gitbook nicely.

**Comment by lukas-bednar** [comment]
@rmohr `swagger2markup` can generate markdown as well. I can add option to generate *.md instead of *adoc. Then push these *.md files to user-guide repo and add reference these files in user-guide/SUMMARY.md file.
Then gitbook can render such documentation as usually.

What do you think ?

**Comment by fabiand** [comment]
Let's not combine the user-guide and API reference.

Let's compile to API reference and commit it to a separate repo, we can then publish it like the blog (https://kubevirt.github.io/blog/), i.e. at https://kubevirt.github.io/api-reference.

The user-guide can then reference it.

**Comment by lukas-bednar** [comment]
@fabiand OK, thanks for input. Can you please create repository either under `kubevirt` or kubevirt-incubator` organization?
Then I need decision whether we will use that markdown and let github to render it,or somewhere else under kubevirt.io as html or whatever else you prefer ... :-)

**Comment by rmohr** [comment]
@fabiand maybe you can merge your kubevirt.io refactor and then just commit it to the kubevirt.io repository?

**Comment by rmohr** [comment]
> @fabiand maybe you can merge your kubevirt.io refactor and then just commit it to the kubevirt.io repository?

I meant, we could also just commit it automatically into a subdirectory in https://github.com/kubevirt/kubevirt.github.io.

**Comment by fabiand** [comment]
Thanks for reminding me of that.

I'd keep it separate for now,  for the sake of automation and permissions.

**Comment by fabiand** [comment]
@lukas-bednar @gbenhaim and I discussed this and agreed to start with https://github.com/kubevirt-incubator/api-reference.

@lukas-bednar will setup the basic stuff there, once that is done and we have settled with

- API presentation
- Automation

We will revisit where to host it.

This seemed to be the most frictionless way of moving forward.

**Comment by lukas-bednar** [comment]
@fabiand I added some improvements there: https://github.com/kubevirt-incubator/api-reference/pull/4

If there is no comment, I can take a look at process how to keep that reference up to date.

**Comment by lukas-bednar** [comment]
Closing this issue as solved:
API Reference repository: https://github.com/kubevirt-incubator/api-reference
API Reference pages: https://kubevirt-incubator.github.io/api-reference/content/index.html
