### ISSUE TITLE
how to hot add disk in v0.36.0

### ISSUE THREAD

**Issue by mzzgaopeng** [kubevirt/kubevirt#4858]
It is now possible to hotplug DataVolume and PVC volumes into a running Virtual Machine.

How do i dynamically add disks，in this version v0.36.0

**Comment by awels** [comment]
There is currently no cli way to do it. You have to do it programatically. An example of code doing this can be found in the functional tests. https://github.com/kubevirt/kubevirt/blob/master/tests/storage/hotplug.go#L79-L90 I am working on adding a new command to virtctl so you can do something like virtctl addvolume <vm_name> --volume-name=<name> to add it.

Also this currently only works with immediately bound storage that is accessible to all nodes. Also working on make this work with WaitForFirstConsumer storage.

**Comment by mzzgaopeng** [comment]
> There is currently no cli way to do it. You have to do it programatically. An example of code doing this can be found in the functional tests. https://github.com/kubevirt/kubevirt/blob/master/tests/storage/hotplug.go#L79-L90 I am working on adding a new command to virtctl so you can do something like virtctl addvolume <vm_name> --volume-name= to add it.
> 
> Also this currently only works with immediately bound storage that is accessible to all nodes. Also working on make this work with WaitForFirstConsumer storage.

can I use the hostpath pv to hotplug ehis datavolume

**Comment by awels** [comment]
No for two reasons. 1 its WFFC, and 2 there is an issue where for hostpath the location I use to look up the file is not there. I have some ideas on how to solve this, and hopefully I will get to implement that soon, but for now it won't work.

**Comment by mzzgaopeng** [comment]
> No for two reasons. 1 its WFFC, and 2 there is an issue where for hostpath the location I use to look up the file is not there. I have some ideas on how to solve this, and hopefully I will get to implement that soon, but for now it won't work.
I think is that hostpath is a local disk, which must first have pv and pvc, and then mount it to the vm by means of mounting

**Comment by mzzgaopeng** [comment]
> No for two reasons. 1 its WFFC, and 2 there is an issue where for hostpath the location I use to look up the file is not there. I have some ideas on how to solve this, and hopefully I will get to implement that soon, but for now it won't work.


I think is that hostpath is a local disk, which must first have pv and pvc, and then mount it to the vm by means of mounting

**Comment by mzzgaopeng** [comment]
Can I implement the dynamic adding operation by manually calling


edit the crd vm or vmi to path the pvc or hostpath？

**Comment by mzzgaopeng** [comment]
use the api to add hotplugin
