### ISSUE TITLE
cgroups v2 silently breaks kubevirt

### ISSUE THREAD

**Issue by puckipedia** [kubevirt/kubevirt#4861]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
VMIs get stuck on "Scheduled", and the pods backing the VMI keep restarting, with no error message.
The virt-handler errors out with "Could not detect slice of whitelisted controller: [devices]"

**What you expected to happen**:
VMs just work.

**How to reproduce it (as minimally and precisely as possible)**:
Run kubevirt using cri-o on systemd with unified cgroup hierarchy enabled (as is default in multiple distros), and try to run any VM.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.37.0
- Kubernetes version (use `kubectl version`): v1.19.7
- VM or VMI specifications: Any.
- Cloud provider or hardware configuration: almost-plain qemu on AMD. 
- OS (e.g. from /etc/os-release): NixOS 21.03pre-git.
- Kernel (e.g. `uname -a`): 5.4.86
- Install tools: kubeadm, and manual kubectl apply
- Others:

**Comment by rmohr** [comment]
@puckipedia thanks.

**Comment by rmohr** [comment]
@vasiliy-ul would that be something you would be interested to look into?

**Comment by vasiliy-ul** [comment]
@rmohr , frankly speaking I've already briefly looked at the issue :) Fixing the slice detection error is rather simple. Though with cgroups v2 a new files hierarchy is introduced and AFAIK there are several places in Kubevirt that potentially may not work with v2. IMHO its probably worth decoupling cgroups handling into a separate utils package. Additionally I guess it will require adjustments in CI to test with both versions. But supporting v2 in Kubevirt is definitely needed. Sooner or later v1 may be droped.

Anyway, sure, I can look into the issue. I can assign it to myself then...

/assign @vasiliy-ul
