### ISSUE TITLE
pkg/hooks/... uses the same proto file name

### ISSUE THREAD

**Issue by nunnatsa** [kubevirt/kubevirt#4881]
/kind bug
In HCO functional tests, there is a warning:
```
WARNING: proto: file "api.proto" is already registered
A future release will panic on registration conflicts. See:
https://developers.google.com/protocol-buffers/docs/reference/go/faq#namespace-conflict
```

This is because pkg/hooks/info/api.proto, pkg/hooks/v1alpha1/api.proto and pkg/hooks/v1alpha2/api.proto share the same file name, and that is not allowed and going to break the packages at a future release.

**What you expected to happen**:
Let's rename these files.

**Comment by jmguzik** [comment]
@nunnatsa @phoracek I have a fix ready here: https://github.com/kubevirt/kubevirt/compare/master...jmguzik:rename-protofiles-in-pkghooks
Renamed it to api_*.proto [Example api_info.proto]. Wanted to rename directly to eg info.proto but this name is already taken elsewhere so I preserved api_.
Please assign me to this issue.
