### ISSUE TITLE
Consider kubelet CRI?

### ISSUE THREAD

**Issue by feiskyer** [kubevirt/kubevirt#49]
[CRI (Container Runtime Interface)](https://github.com/kubernetes/community/blob/master/contributors/devel/container-runtime-interface.md#design-docs-and-proposals) alpha is added in kubernetes v1.5, have you considered using CRI instead of TPR? e.g.  [virtlet](https://github.com/Mirantis/virtlet) is using CRI to manage VM workloads.

![](https://cl.ly/3I2p0D1V0T26/Image%202016-12-19%20at%2017.13.16.png)

**Comment by vishh** [comment]
that would be useful if these VMs are meant to run pods only. however iiuc, this project can spin up general purpose VMs.

**Comment by fabiand** [comment]
Yes, we considered the virtlet approach, however, we believe that this approach will not allows us to bring up arbitrary VMs and tune them as needed.
We are using TPRs to explicitly represent VMs within Kubernetes, this gives us a much tighter control over them VMs.

Btw, in the end it's just a partial problem of how the VMs will be spawned.

**Comment by jellonek** [comment]
PTAL on https://github.com/Mirantis/virtlet/ which runs general purpose VMs as pods, so they can be orchestrated by kubernetes with same as pods interface.

**Comment by jellonek** [comment]
Could you elaborate more about your VM needs? Maybe they could be passed as annotations?

**Comment by fabiand** [comment]
@jellonek yep - We looked at virtlet, however, the amount of informations we need to express are roughly equivalent to the scpoe of libvirtd's domain specification.
And passing all of these informations in a pod's metadata section does not look right.

Besides that we are are working with a separate resource for VMs, because the assumpotions on Pods and VMs differ - and this should be reflected in Kubernetes by having different entities for them.

**Comment by jellonek** [comment]
Indeed these assumptions differ quite hard sometimes (e.x. volumes as dirs vs block devices, possibility to use host networking, entering/attaching). Will look forward on this separated resources :)

**Comment by feiskyer** [comment]
@fabiand Reasonable. I'm closing this issue.

**Comment by fabiand** [comment]
@jellonek we are already working out KubeVirt proposals to expose disks and networks (based on PVCs and the upcoming multi-network stuff) to VMs. You might want to keep watching - and comment. After all you also got experience and can provide valuable feedback.

@feiskyer alright - Feel free to provide feedback. In the end there might be ways of how KubeVirt is eventually there are places to cooperate.
Btw what's the roadmap for runv/virtlet?
