### ISSUE TITLE
[Flaky CI] [Serial][rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system] VM Live Migration Starting a VirtualMachineInstance rook-ceph live migration cancelation should be able to cancel a migration [test_id:2226] with ContainerDisk

### ISSUE THREAD

**Issue by akrejcir** [kubevirt/kubevirt#4900]
/triage build-watcher
/kind bug

**What happened**:
```
vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43
Timed out after 720.002s.
Should have AgentConnected condition
Expected
    <bool>: false
to be true
tests/utils.go:4374
```

[Prow logs](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4859/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1353705734851792896)

**Comment by brybacki** [comment]
again
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5054/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1366430772151455744
