### ISSUE TITLE
[Flaky CI] Storage Starting a VirtualMachineInstance [rfe_id:3106][crit:medium][vendor:cnv-qe@redhat.com][level:component]With an emptyDisk defined [test_id:3134]should create a writeable emptyDisk with the right capacity

### ISSUE THREAD

**Issue by akrejcir** [kubevirt/kubevirt#4902]
/triage build-watcher
/kind bug

**What happened**:
```
tests/storage_test.go:173
Expected success, but got an error:
    <expect.TimeoutError>: 180000000000
    expect: timer expired after 180 seconds
tests/storage_test.go:195
```

[Prow logs](https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4850/pull-kubevirt-e2e-k8s-1.19/1353660186358714368)

**Comment by phoracek** [comment]
Happened again https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4948/pull-kubevirt-e2e-k8s-1.20/1358859571765972992

**Comment by oshoval** [comment]
About the job in the issue description,
the VM has couple issues, one for example is OOM
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4850/pull-kubevirt-e2e-k8s-1.19/1353660186358714368#1:build-log.txt%3A16984

**Comment by oshoval** [comment]
closing as a PR that should fix it was merged
https://github.com/kubevirt/kubevirt/pull/5039
