### ISSUE TITLE
Use static IP for VM  that  live migration will be reports IP conflict

### ISSUE THREAD

**Issue by ironxyz** [kubevirt/kubevirt#4910]
/kind bug

**What happened**:
kube ovn  solves static IP for VM, but meets a problem while doing VM live migration, if it binds the same IP to the migration pod, it reports IP conflict as the two PODs have the same IP.

**How to reproduce it (as minimally and precisely as possible)**:

##VM.yaml\
```bash
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  creationTimestamp: null
  labels:
    kubevirt.io/vm:  testvm100.example.com
  name: testvm100.example.com
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: testvm100.example.com
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        volumeMode: Block
        resources:
          requests:
            storage: 10G
        storageClassName:  csi-rbd-sc
      source:
        http:
          url: http://192.168.1.100/CentOS-7-x86_64-GenericCloud.qcow2
  running: true
  template:
    metadata:
      annotations:
        **ovn.kubernetes.io/ip_address: 192.16.0.100**  # _static IP_
      labels:
        kubevirt.io/vm: testvm100.example.com
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - disk:
              bus: virtio
            name: datavolumevolume
          - disk:
              bus: virtio
            name: cloudinit
          interfaces:
          - name: default
            masquerade: {}
        machine:
          type: ""
        resources:
          requests:
            memory: 4G
      terminationGracePeriodSeconds: 0
      networks:
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: testvm01
        name: datavolumevolume
      - cloudInitNoCloud:
          userData: |
            #cloud-config
            password: kubevirt
            chpasswd: { expire: False }
            hostname: testvm100.example.com
            ssh_pwauth: True
          networkData: |
            version: 2
            ethernets:
              eth0:
                dhcp4: true
        name: cloudinit
```
#migration-job.yaml
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstanceMigration
metadata:
  name: migration-job
spec:
  vmiName: testvm100.example.com

Action:
kubectl apply -f migration-job.yaml

##
![image](https://user-images.githubusercontent.com/3294496/106005387-250d2200-60ef-11eb-9413-1450f3063b2c.png)

**Anything else we need to know?**: 

**Environment**:
- KubeVirt version (use `virtctl version`): v0.36.0
- Kubernetes version (use `kubectl version`): v1.18.3
- VM or VMI specifications: 2CPU  2G memory 50G DISK
- Cloud provider or hardware configuration:  memory:256GB  CPU processor:40 C   Intel(R) Xeon(R) CPU E5-2630 v4 @ 2.20GHz
- OS (e.g. from /etc/os-release):  CentOS Linux release 7.4.1708 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-957.27.2.el7.x86_64
- Install tools: 
- Others:

**Comment by todaygood** [comment]
I met the similar issue , I think the keypoint is that  vm's IP is come from its mother pod,  Can we modify the  mechanism then  vm's mother pod' IP  is different that vm , or  modify IPAM that IPAM can tolerate to allocate same IP by multi times for the same VM?
