### ISSUE TITLE
permittedHostDevices requires device ID to be in capital letters 

### ISSUE THREAD

**Issue by xphyr** [kubevirt/kubevirt#4925]
/kind bug

**What happened**: While configuring a kubevirt instance to support pci passthrough for NVIDIA GPUs I have found that the pciVendorSelector must be entered with capital letters only.  

For example this does not work:
```
pciHostDevices:
      - pciVendorSelector: "10de:1db4"
```

But this does:
```
pciHostDevices:
      - pciVendorSelector: "10DE:1DB4"
```

If you run an `lspci` all the vendor IDs are output in lower case (such as below)
```
lspci -nnk -d 10de:
09:00.0 3D controller [0302]: NVIDIA Corporation GV100GL [Tesla V100 PCIe 16GB] [10de:1db4] (rev a1)
	Subsystem: NVIDIA Corporation Device [10de:1214]
	Kernel driver in use: vfio-pci
	Kernel modules: nouveau
```

We should support both upper and lowercase letters in the device ID.

**What you expected to happen**:

We should support both upper and lowercase letters in the device ID. If you use lspci to find the device ID it is listed in lower case, for ease of use it would be good to support both upper and lower case in this config area.

**How to reproduce it (as minimally and precisely as possible)**:

Create a configuration that uses lower case letters for the pciVendorSelector. It will not find the device, then use UPPER case and it will,.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):0.37.1
- Kubernetes version (use `kubectl version`): v1.19.0+9c69bdc
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by vladikr** [comment]
This was addressed by #4940
