### ISSUE TITLE
[Flaky CI] [sig-network] [Serial]Services bridge interface binding with a service matching the vmi exposed [test_id:1548] should fail to reach the vmi if an invalid servicename is used

### ISSUE THREAD

**Issue by jean-edouard** [kubevirt/kubevirt#4938]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/triage build-watcher
/kind bug

**What happened**:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/batch/pull-kubevirt-e2e-k8s-1.18/1355038767810875392
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4870/pull-kubevirt-e2e-k8s-1.20/1355087088759869440
```
Job netcat6gl6t timeout reached, status: {Conditions:[] StartTime:2021-01-29 10:41:12 +0000 UTC CompletionTime:<nil> Active:1 Succeeded:0 Failed:0}, err: timed out waiting for the condition
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fgimenez** [comment]
Happened in the periodic e2e from master too https://prow.k8s.io/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-latest/1356361861309665280

It's easy to reproduce executing `test_id:1548` in a loop.

**Comment by ashleyschuett** [comment]
again - https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4941/pull-kubevirt-e2e-k8s-1.20/1357280917537689601

**Comment by fgimenez** [comment]
/reopen

Happened again during AfterEach https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev/1363428550807392257 
```
13:45:36: • Failure in Spec Teardown (AfterEach) [252.117 seconds]
13:45:36: [sig-network] [Serial]Services
13:45:36: tests/network/framework.go:27
13:45:36:   bridge interface binding
13:45:36:   tests/network/services.go:124
13:45:36:     with a service matching the vmi exposed [AfterEach]
13:45:36:     tests/network/services.go:159
13:45:36:       [test_id:1548] should fail to reach the vmi if an invalid servicename is used
13:45:36:       tests/network/services.go:187
13:45:36: 
13:45:36:       Timed out after 120.000s.
13:45:36:       The VMI should be gone within the given timeout
13:45:36:       Expected an error to have occurred.  Got:
13:45:36:           <nil>: nil
13:45:36: 
13:45:36:       tests/network/services.go:85
```
It caused a lot of failures after this error and a final 7h timeout.
