### ISSUE TITLE
[Flaky CI] [rfe_id:1177][crit:medium][vendor:cnv-qe@redhat.com][level:component]VirtualMachine An invalid VirtualMachine given with a PVC from a Datavolume [test_id:4643]should NOT be rejected when VM template lists a DataVolume, but VM lists PVC VolumeSource

### ISSUE THREAD

**Issue by jean-edouard** [kubevirt/kubevirt#4939]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:

/triage build-watcher
/kind bug

**What happened**:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4905/pull-kubevirt-e2e-k8s-1.18/1355102063591165952
```
persistentvolumeclaims \"test-datavolume-t97hjv8wkktn\" not found
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dhiller** [comment]
Seen again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4937/pull-kubevirt-e2e-k8s-1.20/1356988617087520768

**Comment by xpivarc** [comment]
Seen again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev-prev/1359079770846924800

**Comment by fgimenez** [comment]
Happened again https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-latest/1360891835496534016

**Comment by fgimenez** [comment]
Happened again https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-latest/1362160195538522113 also with #4835

**Comment by oshoval** [comment]
Again 
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5045/pull-kubevirt-e2e-k8s-1.17/1363468574340943872

**Comment by arnongilboa** [comment]
Again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev-prev/1368139530867052545

**Comment by brybacki** [comment]
Need to observe the test on new runs. Old logs have the IP `CIDRNotAvailable`
```
I0306 11:09:44.227529       1 event.go:278] Event(v1.ObjectReference{Kind:"Node", Namespace:"", Name:"node02", UID:"a280276c-f28e-460e-89a5-9ea2309d86f5", APIVersion:"v1", ResourceVersion:"", FieldPath:""}): type: 'Normal' reason: 'CIDRNotAvailable' Node node02 status is now: CIDRNotAvailable
I0306 11:10:43.858287       1 event.go:278] Event(v1.ObjectReference{Kind:"PersistentVolumeClaim", Namespace:"kubevirt-test-default3", Name:"test-iscsi-lun2gpr95zl6cv4qf6zp6bshlnjx6cqzmgphn7cszk7p826fqtw", UID:"701b399c-0793-44d4-a568-3a3a3b7c26c1", APIVersion:"v1", ResourceVersion:"38794", FieldPath:""}): type: 'Normal' reason: 'WaitForFirstConsumer' waiting for first consumer to be created before binding
```

**Comment by brybacki** [comment]
What is suspicious this always fail when following test fails:
"Merged Test Suite.Storage Starting a VirtualMachineInstance Run a VMI with VirtIO-FS and a datavolume should be successfully started and virtiofs could be accessed". I have not found a single case where 4643 fails alone.

But that other test fails more often. Maybe the VirtIO-FS does not cleanup correctly? Maybe the problem was because of CIDR?

Also last failure on periodic*prev-prev was on 6th of March (as commented by Arnon), last failure on periodic*latest was on 24th of Feb.

Last failures on lanes kubevirt-1.17 and kubevirt-1.20 were long time ago (before 9 of March, so before merging calico and CIDR fixes).

**Comment by brybacki** [comment]
But I think it is too early to have any meaningful conclusions. I'll try to investigate.
