### ISSUE TITLE
Allow emulating other architectures (e.g. x86_64 machines on arm64 nodes)

### ISSUE THREAD

**Issue by wyyxd2017** [kubevirt/kubevirt#4942]
can add arch to support cross compile

**Comment by phoracek** [comment]
@wyyxd2017 would you please elaborate what exactly do you want?

**Comment by The-Loeki** [comment]
If we had API stanza's for arch|emulator|device-type we could instantiate different HW-emulated VM's through KubeVirt (e.g. a x86_64 machine running an ARM64 build with a different qemu-$machine)

**Comment by rmohr** [comment]
So, this seems to be more about rinning e.g. x86 machines on arm64 nodes, or the other way round and not about cross-compile?

**Comment by rmohr** [comment]
@wyyxd2017 renaming regarding to the requrest description. Feel free to change it back if you think it is not accurate.

**Comment by lee-b** [comment]
I would love this feature.  Seems like it should be relatively easy to allow the other architectures and systems that qemu supports.  It would allow, for example, upgrading to x86 and running a last remaining legacy app that requires sparc or PPC; or emulating legacy systems for computer museum purposes; or experimenting with an old-school Amiga render farm of many 68k lightwave render nodes on modern x86 (or ARM) cloud infrastructure, etc.  Essentially, it would allow truly hyperconverged infrastructure.  Incredibly useful.

What would be involved in making this happen?
