### ISSUE TITLE
Katacoda example is broken with 0.37.2

### ISSUE THREAD

**Issue by bravecobra** [kubevirt/kubevirt#4943]
I tried to run the katacoda getting started example but failed during install.

/kind bug

**What happened**:
I ran the katacoda examplemas advertised on kubevirt.io
**What you expected to happen**:
Katacoda should run without errors
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.37.2
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by phoracek** [comment]
Thanks @bravecobra, I copied this to our katacoda repo: https://github.com/kubevirt/katacoda-scenarios/issues/11

**Comment by bravecobra** [comment]
I don't think the error is in the scenario but more in the compat between katacoda and kibevirt. It may need fixing in another repo.
