### ISSUE TITLE
Update Golang Version

### ISSUE THREAD

**Issue by kwiesmueller** [kubevirt/kubevirt#4945]
Golang 1.13 was released over a year ago and [reached EOL with the release of 1.15 in 2020/08/11](https://golang.org/doc/devel/release.html#policy).
Kubernetes itself is already on 1.15, we should update too.

It might also be worth investigating if we can get automated reminders/updates with new Golang versions.

**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

Sorry if there is already someone working on it or an issue tracking this, I didn't find it.

**Comment by phoracek** [comment]
We indeed should bump the version. I'm not aware of a duplicate Issue neither.

Any volunteers to take this one? @kwiesmueller ;)

**Comment by kwiesmueller** [comment]
I'll give it a take as soon as I can. 
If somebody else is faster, just assign it to yourself so i don't start at the same time.
