### ISSUE TITLE
Tests Suite: [rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]VMIlifecycle [rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]Creating a VirtualMachineInstance [Serial]when virt-handler is not responsive [test_id:1634]the node controller should mark the node as unschedulable when the virt-handler heartbeat has timedout

### ISSUE THREAD

**Issue by nelsonspbr** [kubevirt/kubevirt#4958]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/triage build-watcher
/kind bug

**What happened**:

https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-master-4.8-e2e/1356800216870686720

```
tests/vmi_lifecycle_test.go:582
Should get virthandler client
Unexpected error:
    <*errors.errorString | 0xc0029d29c0>: {
        s: "No virt-handler on node ci-op-131g7tms-37b01-s8rhh-master-0 found",
    }
    No virt-handler on node ci-op-131g7tms-37b01-s8rhh-master-0 found
occurred
tests/vmi_lifecycle_test.go:618
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by nelsonspbr** [comment]
Might be related to some extent: https://github.com/kubevirt/kubevirt/issues/4715

**Comment by phoracek** [comment]
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4552/pull-kubevirt-e2e-k8s-1.17/1357472429475106816

**Comment by fgimenez** [comment]
Happened again https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev/1362703775432708096

**Comment by oshoval** [comment]
Again
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5076/pull-kubevirt-e2e-k8s-1.17/1363869838698614785

**Comment by mhenriks** [comment]
Again:  https://prow.ci.openshift.org/view/gs/origin-ci-test/logs/periodic-ci-kubevirt-kubevirt-master-4.8-e2e/1366584623005437952

**Comment by rmohr** [comment]
@enp0s3 this should be fixed with the PR regarding to config restore if I am not mistaken.

**Comment by rmohr** [comment]
```
tests/vmi_lifecycle_test.go:582
Should get virthandler client
Unexpected error:
    <*errors.errorString | 0xc0029d29c0>: {
        s: "No virt-handler on node ci-op-131g7tms-37b01-s8rhh-master-0 found",
    }
    No virt-handler on node ci-op-131g7tms-37b01-s8rhh-master-0 found
occurred
tests/vmi_lifecycle_test.go:618
```

will fixed as part of https://github.com/kubevirt/kubevirt/pull/5221. The background is that the test first tells virt-operator to evict virt-handler from a node and then tries to get the pod of it. Most of the time it is fast enough, but if there is node pressure it could happen that virt-handler was already gone. It should of course first get the client.

Note that this seems to happen pretty seldom. All reports of re-occurrences were actually reports of #4720.
