### ISSUE TITLE
[Serial][rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system] VM Live Migration Starting a VirtualMachineInstance migration postcopy [test_id:4747] should migrate using cluster level config for postcopy [It] migration should not fail

### ISSUE THREAD

**Issue by nelsonspbr** [kubevirt/kubevirt#4959]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/triage build-watcher
/kind bug

**What happened**:

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev/1356361861309665282#1:build-log.txt%3A7113

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by nelsonspbr** [comment]
Observed here as well: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev-prev/1356538149265739776

```
```

**Comment by dhiller** [comment]
Seen again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4960/pull-kubevirt-e2e-k8s-1.19/1357382337263833088

**Comment by fgimenez** [comment]
Happened again https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev/1359804546922057728 on 1.19
