### ISSUE TITLE
[rfe_id:3064][crit:medium][vendor:cnv-qe@redhat.com][level:component]Pausing A valid VM when paused via virtctl [test_id:3226]should be restarted successfully into unpaused state

### ISSUE THREAD

**Issue by ashleyschuett** [kubevirt/kubevirt#4970]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/triage build-watcher

**What happened**:

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4949/pull-kubevirt-e2e-k8s-1.20/1357001330085859328

```
tests/pausing_test.go:278
Timed out after 60.000s.
The VMI did not disappear
Expected
    <bool>: false
to be true
tests/pausing_test.go:304
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by tomob** [comment]
Another failure: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4387/pull-kubevirt-e2e-k8s-1.20/1366846259251384320

/reopen
