### ISSUE TITLE
[rfe_id:3423][crit:high][vendor:cnv-qe@redhat.com][level:component]VmWatch [test_id:3466]Should update vmi status with the proper columns using 'kubectl get vmi -w' 

### ISSUE THREAD

**Issue by ashleyschuett** [kubevirt/kubevirt#4971]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug
/triage build-watcher

**What happened**:

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4953/pull-kubevirt-e2e-k8s-1.20/1356962067667488768

```
tests/vm_watch_test.go:218
Timed out after 60.000s.
Expected
    <bool>: false
to be true
tests/vm_watch_test.go:334
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dhiller** [comment]
Seen again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4937/pull-kubevirt-e2e-k8s-1.20/1357188180465422336

**Comment by phoracek** [comment]
Happened again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4985/pull-kubevirt-e2e-k8s-1.20/1359089962724626433

**Comment by arnongilboa** [comment]
Happened again: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-latest/1368320598559690752

/reopen
