### ISSUE TITLE
[flaky ci] [sig-storage] Hotplug Offline VM Should add volumes on an offline VM with PersistentVolume

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#4974]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind enhancement

/triage build-watcher

**What happened**:

Test flaked: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4937/pull-kubevirt-e2e-k8s-1.20/1357372396872404992

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

```
vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43
Unexpected error:
    <*errors.StatusError | 0xc00088ae60>: {
        ErrStatus: {
            TypeMeta: {Kind: "", APIVersion: ""},
            ListMeta: {
                SelfLink: "",
                ResourceVersion: "",
                Continue: "",
                RemainingItemCount: nil,
            },
            Status: "Failure",
            Message: "Internal error occurred: unable to patch vm status during volume remove: the server rejected our request due to an error in our request",
            Reason: "InternalError",
            Details: {
                Name: "",
                Group: "",
                Kind: "",
                UID: "",
                Causes: [
                    {
                        Type: "",
                        Message: "unable to patch vm status during volume remove: the server rejected our request due to an error in our request",
                        Field: "",
                    },
                ],
                RetryAfterSeconds: 0,
            },
            Code: 500,
        },
    }
    Internal error occurred: unable to patch vm status during volume remove: the server rejected our request due to an error in our request
occurred
tests/storage/hotplug.go:148
```

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by brybacki** [comment]
happened again here:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5054/pull-kubevirt-e2e-k8s-1.20/1366428003701100544
for 

[sig-storage] Hotplug Offline VM Should add volumes on an offline VM with PersistentVolume 
and 
[sig-storage] Hotplug Offline VM Should add volumes on an offline VM with DataVolume
