### ISSUE TITLE
[flaky ci] [sig-network] [Serial]Services Masquerade interface binding *without* a service matching the vmi exposed should fail to reach the vmi

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#4976]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind enhancement

/triage build-watcher

**What happened**:
Test flaked: https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4960/pull-kubevirt-e2e-k8s-1.20/1357026365903212544

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

```
tests/network/services.go:302
connectivity is *not* expected, since there isn't an exposed service
Unexpected error:
    <*errors.errorString | 0xc0022295a0>: {
        s: "Job netcatsqb9w timeout reached, status: {Conditions:[] StartTime:2021-02-03 21:59:14 +0000 UTC CompletionTime:<nil> Active:1 Succeeded:0 Failed:3}, err: timed out waiting for the condition",
    }
    Job netcatsqb9w timeout reached, status: {Conditions:[] StartTime:2021-02-03 21:59:14 +0000 UTC CompletionTime:<nil> Active:1 Succeeded:0 Failed:3}, err: timed out waiting for the condition
occurred
tests/network/services.go:307
```

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by EdDev** [comment]
@qinqon is this related to #4957 ?

**Comment by qinqon** [comment]
@EdDev yes, I think the PR got merged this is suppose to be fixed.

**Comment by qinqon** [comment]
This is a dup of https://github.com/kubevirt/kubevirt/issues/4938

**Comment by maiqueb** [comment]
/close

Closing since https://github.com/kubevirt/kubevirt/pull/4957 - which allegedly fixes this issue was merged 5 days ago.

Let's re-open if it happens again.
