### ISSUE TITLE
Why HotPlugVolumes feature's validate webhook only support scsi bus?

### ISSUE THREAD

**Issue by threestoneliu** [kubevirt/kubevirt#4980]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Why HotPlugVolumes feature's validate webhook only support scsi bus?

[validateVolumeRequests](https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-api/webhooks/validating-webhook/admitters/vms-admitter.go#L367)

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

/kind question

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by awels** [comment]
There is no technical reason we cannot support virtio for instance, however that comes with a large problem. Each disk hotplugged will use a pci-root port, and there is a maximum of 32 for all devices. So the number of disks we can hotplug is very limited, second you cannot modify the pci configuration after you start the VM, so you need to know ahead of time how many disks you want to hotplug. In contrast virtio-scsi supports millions of disks (well in theory, in practice its somewhere in the 60-70k range) and the performance difference between virtio-scsi and virtio is negligible. So basically to save everyone a lot of headaches we decided to only support virtio-scsi (like oVirt).

**Comment by threestoneliu** [comment]
Ok，i got it. Thank you for your answer!
