### ISSUE TITLE
[Serial][rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system] VM Live Migration with a live-migrate eviction strategy set [ref_id:2293] with a VMI running with an eviction strategy set [It] [test_id:3243]should recreate the PDB if VMIs with similar names are recreated 

### ISSUE THREAD

**Issue by xpivarc** [kubevirt/kubevirt#4997]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind bug
/triage build-watcher

**What happened**:
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4740/pull-kubevirt-e2e-k8s-1.20/1358629426744528896
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
```
tests/migration_test.go:1542
Timed out after 60.000s.
Expected
    <bool>: false
to be true
tests/migration_test.go:1565
```

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fgimenez** [comment]
Happened again https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-latest/1360167059601756160

**Comment by fgimenez** [comment]
Happened again https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-latest/1360348254058844160

**Comment by oshoval** [comment]
/reopen 

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5167/pull-kubevirt-check-tests-for-flakes/1369251488844484608
