### ISSUE TITLE
[flakey] Configurations [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]with CPU spec [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]when CPU model defined [test_id:1678]should report defined CPU model

### ISSUE THREAD

**Issue by phoracek** [kubevirt/kubevirt#5005]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4552/pull-kubevirt-e2e-k8s-1.19/1357413415898845184

**Comment by fgimenez** [comment]
/reopen

Happened again https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-latest/1364334520735633409

**Comment by maya-r** [comment]
/reopen
this failed with: `Can't connect to websocket (500): websocket: bad handshake` in https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-prev-prev/1366146270376235008
fyi @rhrazdil
