### ISSUE TITLE
[flakey] [Serial][rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system] VM Live Migration with a live-migrate eviction strategy set [ref_id:2293] with a VMI running with an eviction strategy set [test_id:3243]should recreate the PDB if VMIs with similar names are recreated

### ISSUE THREAD

**Issue by phoracek** [kubevirt/kubevirt#5007]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4948/pull-kubevirt-e2e-k8s-1.20/1359013207296970752

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4552/pull-kubevirt-e2e-k8s-1.20/1359229757991948288

**Comment by fgimenez** [comment]
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-latest/1359442157471010816 also on 1.20. Happened together with `test_id:3201`

**Comment by xpivarc** [comment]
I think this [PR](https://github.com/kubevirt/kubevirt/pull/5001) could solve this.

**Comment by fgimenez** [comment]
Duplicate of #4997

**Comment by phoracek** [comment]
Oh, sorry, somehow I missed that one
