### ISSUE TITLE
[flakey] [rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]VMIlifecycle [rfe_id:273][crit:high][vendor:cnv-qe@redhat.com][level:component]Creating a VirtualMachineInstance [Serial]with default cpu model [test_id:3201]should not set cpu model when vmi does not have it set and default cpu model is not set

### ISSUE THREAD

**Issue by phoracek** [kubevirt/kubevirt#5008]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4948/pull-kubevirt-e2e-k8s-1.19/1358850387121016832

**Comment by rmohr** [comment]
/reopen

still an issue
