### ISSUE TITLE
Configure disk sector sizes and other disk device fields

### ISSUE THREAD

**Issue by Omar007** [kubevirt/kubevirt#5028]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What happened**:
KubeVirt does not currently seem to allow tweaking/tuning disk configuration. Think of details such as:
- Logical sector size
- Physical sector size
- Minimal I/O size
- Optimal I/O size
- Rotational device or not

**What you expected to happen**:
The VM(I) spec to provide fields to configure these device properties.
Possibly default to at least inherit from the backing devices automatically where possible (see 'Anything else we need to know?' section)

**How to reproduce it (as minimally and precisely as possible)**:
Search https://kubevirt.io/api-reference/master/definitions.html for possible fields to set disk details to find none.

**Anything else we need to know?**:
It also doesn't seem to currently automatically detect optimal values based on the backing storage (e.g. VM getting disks with 512/512 bytes sectors when the backing device has 4096/4096 bytes sectors).
This failure to auto-detect is probably not unique to KubeVirt but I haven't checked that yet as normally I'd just specify these settings in QEMU or libvirt.

**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.38.1", GitCommit:"8c3ba52f8ce7cbb55c29919e9c263617716aa054", GitTreeState:"clean", BuildDate:"2021-02-08T20:04:23Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.38.1-dirty", GitCommit:"8c3ba52f8ce7cbb55c29919e9c263617716aa054", GitTreeState:"dirty", BuildDate:"2021-02-08T20:30:01Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.4", GitCommit:"d360454c9bcd1634cf4cc52d1867af5491dc9c5f", GitTreeState:"archive", BuildDate:"2020-11-25T13:19:56Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.6", GitCommit:"fbf646b339dc52336b55d8ec85c181981b86331a", GitTreeState:"clean", BuildDate:"2020-12-18T12:01:36Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools:  N/A
- Others: N/A

**Comment by phoracek** [comment]
@mhenriks would this be something we want in KubeVirt?

**Comment by Omar007** [comment]
Some extra context/information on the subject;

In libvirt, the sector sizing would be managed with the `blockio` section within the disk configuration.

```
<disk type='block' device='disk'>
  ...
  <blockio logical_block_size='4096' physical_block_size='4096'/>
  ...
</disk>
```
https://libvirt.org/formatdomain.html#hard-drives-floppy-disks-cdroms
> **blockio**
    If present, the blockio element allows to override any of the block device properties listed below. Since 0.10.2 (QEMU and KVM)
    **_logical_block_size_**
        The logical block size the disk will report to the guest OS. For Linux this would be the value returned by the BLKSSZGET ioctl and describes the smallest units for disk I/O.
    **_physical_block_size_**
        The physical block size the disk will report to the guest OS. For Linux this would be the value returned by the BLKPBSZGET ioctl and describes the disk's hardware sector size which can be relevant for the alignment of disk data.

I don't think libvirt exposes other options/sections to configure device option (except for geometry related stuff for rotational devices I suppose). As such it might not even be possible to realize some of the other options in KubeVirt (even though they are technically available with pure QEMU). 
But at the very least the sector sizing can be enabled/exposed (or at least be auto-detected) in KubeVirt from my perspective.

Without being able to specify (or KubeVirt automatically detecting), this is what currently happens when KubeVirt instantiates the VM:

**Host/Source Block Device View**
```
Disk /dev/nvme0n1: 75 GiB, 80534360064 bytes, 19661709 sectors
Units: sectors of 1 * 4096 = 4096 bytes
Sector size (logical/physical): 4096 bytes / 4096 bytes
I/O size (minimum/optimal): 4096 bytes / 4096 bytes
```
**VM View**
```
Disk /dev/vda: 75 GiB, 80534360064 bytes, 157293672 sectors
Units: sectors of 1 * 512 = 512 bytes
Sector size (logical/physical): 512 bytes / 512 bytes
I/O size (minimum/optimal): 512 bytes / 512 bytes
```
