### ISSUE TITLE
Upgrade Cirros image due to ext4 OOM

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#5040]
/kind bug

**What happened**:
Issue https://github.com/kubevirt/kubevirt/issues/4902 shows the is OOM kernel panic

**What you expected to happen**:
Kernel should be stable
so we should update the Cirros image in order to have the new fixes.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by phoracek** [comment]
@oshoval this issue is mixing Cirros version, unstable Kernel and OOM. If the issue is OOM in Cirros, please reflect it in the title.

You also suggest that update of Cirros would fix it. Do you have any BZ supporting that claim? Have you tried updated Cirros to prove that it was fixed?

**Comment by oshoval** [comment]
> @oshoval this issue is mixing Cirros version, unstable Kernel and OOM. If the issue is OOM in Cirros, please reflect it in the title.
> 
> You also suggest that update of Cirros would fix it. Do you have any BZ supporting that claim? Have you tried updated Cirros to prove that it was fixed?

I didn't try, its not out of the box as fedora, (at least that i know of)
I do see scattered reports about oom with ext4, with fixes, for different linux deployments, so i think its well deserved giving it a try.
For example https://patchwork.ozlabs.org/project/linux-ext4/patch/20180510153851.4689-1-jack@suse.cz/
and i see the OOM follows this function `ext4_ind_map_blocks` 
We didn't update the Cirros for a long time, and it will be good to update it / have a method to update it easily imo.

Meanwhile i created a PR that increase the memory from 64MB to 512MB, i think its the right start move.

**Comment by phoracek** [comment]
If the cirros update is simple, let's do that right away instead of trying to avoid the issue by increasing the memory 8 times. Dodging a leak is just deferring the flake.

**Comment by oshoval** [comment]
While trying to upgrade, i see that its not that trivial
Using the new image, the machine doesn't have a console

But look on this please
https://github.com/cirros-dev/cirros/issues/52#issuecomment-595389740
The minimal required memory is indeed 128MB and we are using 64MB before the mentioned PR.
wdyt ?

**Comment by oshoval** [comment]
@phoracek @enp0s3 
Do we want to only bump the memory in this specific test to 512Mi and on the rest of the Cirros to 128Mi
(or some other combination),
or we also want to bump the version ?
According the community bumping the memory and staying with 0.4.0 is sane.
Bumping to 0.5.0+ is a nice to have, i can do it on other PR if needed (almost there hopefully but it will take a bit).

**Comment by oshoval** [comment]
OOM was fixed, the bump is nice to have if desired but not mandatory
closing
