### ISSUE TITLE
virt-handler calls GET "/version" each healthcheck and liveness probe

### ISSUE THREAD

**Issue by mlsorensen** [kubevirt/kubevirt#5058]
/kind bug

**What happened**:

I'm playing with the k8s audit logs and if I'm reading this right, the vast majority of API calls from virt-handler are for "/version". I have a test cluster with a dozen nodes, and over the course of 5 minutes "userAgent: virt-handler/v0.0.0" made 1287 requests, 722 of these were for "/version".

Looking at some other larger clusters, virt-handler accounts for about 12%-40% of all API calls.

**What you expected to happen**:

Should figure out a way to reduce this traffic. I haven't looked into it far enough to determine whether or not this is actually a necessary thing to do each loop.

**How to reproduce it (as minimally and precisely as possible)**:

As far as I'm aware, by simply running virt-handler and collecting Kubernetes API audit logs.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.35.0
- Kubernetes version (use `kubectl version`): v1.18.9

**Comment by davidvossel** [comment]
@mlsorensen for the 744 version requests, if you have ~100 nodes in this cluster running virt-handler then this is likely the virt-handler heart beat. 

heartbeat interval is every 1 minute. so math would be... `5 minutes * 144 nodes = 720 requests`

I'm guessing it's this [line of code,](https://github.com/kubevirt/kubevirt/blob/4b576cb7107fc55dbb60c6fa6f763ec447e7e17c/pkg/virt-handler/vm.go#L2361) where there's a call introspecting the server version to determine it we're on openshift for some reason.

we could definitely cache that info rather than asking every minute.

**Comment by mlsorensen** [comment]
@davidvossel Yeah, I found that! I have a hard time understanding why it would be triggered every minute, isn't the for loop below that the actual heartbeat?  Seems like it's something here though as that is the only way I can get to this:

https://github.com/kubevirt/kubevirt/blob/9f66405f8e445d5ecb5b66f1b724f5251e70d863/pkg/util/cluster/cluster.go#L59

**Comment by davidvossel** [comment]
> Yeah, I found that! I have a hard time understanding why it would be triggered every minute, isn't the for loop below that the actual heartbeat? Seems like it's something here though as that is the only way I can get to this:

oh yeah... you're right. This call is outside of the loop. Weird. You're right that it doesn't look possible. Unless virt-handler is crashing over and over.

**Comment by mlsorensen** [comment]
Yes, I just checked for that. There are one or two that have restarted a few times but the source IP of the APIs is pretty evenly spread among all of the nodes.

**Comment by xpivarc** [comment]
My suspect would be https://github.com/kubevirt/kubevirt/blob/master/cmd/virt-handler/virt-handler.go#L390. 2 request (liveness+readiness probe) each 10 seconds so `5min * 60 / 10 * 2 = 60` request per handler in 5 minutes?

**Comment by mlsorensen** [comment]
Looks right to me... every call to /healthz results in a call to /version.

https://github.com/kubevirt/kubevirt/blob/4b576cb7107fc55dbb60c6fa6f763ec447e7e17c/pkg/healthz/healthz.go#L44

**Comment by davidvossel** [comment]
> Looks right to me... every call to /healthz results in a call to /version.

yep, i think this is it

**Comment by mlsorensen** [comment]
So my example, we have readiness probe of 30 seconds and liveness probe of 30 seconds.  37 pods in the daemonset... 148 calls to /healthz per minute.  Over 5 minutes is 740.

**Comment by davidvossel** [comment]
> So my example, we have readiness probe of 30 seconds and liveness probe of 30 seconds. 37 pods in the daemonset... 148 calls to /healthz per minute. Over 5 minutes is 740.

I doubt it would hurt to loosen up the interval for the liveness check a bit. I #5061 i changed the defaults we're using in the operator to 20 seconds for readiness and 45 for liveness. It was an interval of 10 seconds each

**Comment by xpivarc** [comment]
I would like to raise 2 questions: 
1. Why do we use readiness checks in the first place? I was under the impression it is only good for `services`.
2. What benefit the `/version` API call brings us? Kubelet will also notice if there will be a connectivity issue. We also don't probably want to kill the handler if K8S API goes away, am I missing something?

**Comment by mlsorensen** [comment]
Yeah, in my case I think we will have to bump it to 300 seconds or so to make a meaningful improvement and drop virt-handler down as not the top API consumer.

Do you think it's worthwhile to cache this value? I assume it's meant to ensure the virt-handler is able to reach the API Server, or something like that?  Would the informers be able to tell us if that's an issue?

**Comment by mlsorensen** [comment]
> 2. What benefit the `/version` API call brings us? Kubelet will also notice if there will be a connectivity issue. We also don't probably want to kill the handler if K8S API goes away, am I missing something?

It might be possible that the network policy that virt-handler is operating under may disallow communication to the API but kubelet would be fine. In that case it may be beneficial to ensure there is no regression there during operations.

**Comment by xpivarc** [comment]
Good point, not sure but I think there is a way to use the failing watchers.... @davidvossel wdyt?

**Comment by davidvossel** [comment]
> Good point, not sure but I think there is a way to use the failing watchers.... @davidvossel wdyt?

i think the internal informer cache remains available, but if the list/watch is failing then we won't receive any updates... meaning the handler's reconcile loop won't get popped until connectivity is restored.

**Comment by mlsorensen** [comment]
Maybe we could make this check on a longer interval, cache the result. At a minimum the liveness and readiness could benefit from deduplicating the requests and using the same result.

**Comment by davidvossel** [comment]
> Maybe we could make this check on a longer interval, cache the result. At a minimum the liveness and readiness could benefit from deduplicating the requests and using the same result.

I suppose we could create a custom tunable for the /version polling interval and cache the result. We'd want to be really careful with how that's done though. If we get a failure on the /version endpoint, we'd want to start polling it much quicker in order to determine when connectivity restored

If we don't do that in the event of connectivity failures, it's possible that the liveness probe could report failure multiple times in a row (causing the handler pod to terminate) due to viewing a cached result where the cached result.

**Comment by xpivarc** [comment]
Maybe we can use [SetWatchErrorHandler]( https://pkg.go.dev/k8s.io/client-go/tools/cache#SharedInformer).

**Comment by mlsorensen** [comment]
I spent some time experimenting with SetWatchErrorHandler. I set up a new struct type that the controllers could pass to KubeConnectionHealthzFuncFactory. If the struct was empty, the healthcheck function would fetch `/version` and save it into this, otherwise it would just return what is in the struct. I then added functions to handle SetWatchErrorHandler on the various informers being used by the controllers, to clear the struct when the informers run into errors, which then triggers the healthz function to start polling for a version again.

I exec'd into the virt-handler and added/removed a blackhole route to the apiserver, and generally the model works. I got failed healthchecks while the blackhole route was in place, it would query for `/version` during this period, and it recovered after the route was deleted and only queried `/version` once on recovery. This was the case for virt-api, virt-controller, and virt-handler.

A few things to note:

1) This doesn't immediately start failing health checks when the Kubernetes API goes down, it can take some seconds for the informers to error out, depending on whether they are idle or whether something was being reconciled, resync timing, etc. If the outage is short it may not fail health check at all.

2) I'm not certain this will actually update the contents of the version cache in the event that the API gets upgraded somehow without interrupting the informers. It's not something I've tested but something to think about, if we are actually depending on this output of the Kubernetes API versioning for something. Perhaps a timer could be added in order to refresh this value occasionally even if it is set.

3) In virt-handler's case there is also a patch to the node in a heartbeat function that can fail, and it's not immediately obvious to me how to apply this logic to the failure of that, or if it is even necessary to do so.

**Comment by xpivarc** [comment]
1. I don't see this as a problem. Even with the probe, we have a 10seconds interval and I would expect watch will fail in a similar time.

2. I don't see it being used maybe our test suit will show us otherwise. 

3. You are right, there is also a heartbeat that is patching the node but we don't react to failures in the virt-handler. Virt-controller is responsible for response in case of heartbeat failures. So there is no need to couple this logic.

I see a value in this approach as it reduces the API calls to a minimum.

**Comment by mlsorensen** [comment]
Do you think we need to `SetWatchErrorHandler()` on all of the informers, or just on any one of the watches per virt-api, virt-controller, or virt-handler?

As far as testing - I can easily add a test for the cache itself, but aside from just ensuring the software still works and there are no regressions via functional tests I'm not sure how to exercise this via test suite... something that kills the Kubernetes API, or firewalls it off and then waits for the health checks to fail?  Are there examples of testing the health check functionality to start from?

**Comment by davidvossel** [comment]
> I then added functions to handle SetWatchErrorHandler on the various informers being used by the controllers, to clear the struct when the informers run into errors, which then triggers the healthz function to start polling for a version again.

Okay, so if the informer's persistent connection breaks, then we start polling version again until that connectivity is restored. That keeps us from having to indefinitely poll /version.

I think that makes sense. I assume that the informers are performing some sort of keep-alive mechanism to ensure they can accurately detect when the connection isn't active anymore in order to reconnect. Otherwise we wouldn't be able to depend on informers at all. 

+1 from me

> Do you think we need to SetWatchErrorHandler() on all of the informers, or just on any one of the watches per virt-api, virt-controller, or virt-handler?

It seems like setting SetWatchErrorHandler on one informer woudl do. All the components use an informer to watch the cluster config's ConfigMap. maybe that's a common informer that makes sense to leverage for this.

**Comment by xpivarc** [comment]
Regarding testing, can't you do what you described in the previous comment? `I exec'd into the virt-handler...`

**Comment by mlsorensen** [comment]
> Regarding testing, can't you do what you described in the previous comment? `I exec'd into the virt-handler...`

I'm just not certain what the existing code around testing the health endpoint looks like yet, or anything really about the actual running of the test suite in the kubevirt CI process. It's something to look into...
