### ISSUE TITLE
qemu-kvm: error: failed to set MSR 0x48e

### ISSUE THREAD

**Issue by outbackdingo** [kubevirt/kubevirt#5068]
/kind bug
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/testvm","pos":"vm.go:1053","reason":"server error. command SyncVMI failed: \"LibvirtError(Code=1, Domain=10, Message='internal error: qemu unexpectedly closed the monitor: 2021-02-21T02:17:50.604694Z qemu-kvm: error: failed to set MSR 0x48e to 0xfff9fffe04006172\\nqemu-kvm: /builddir/build/BUILD/qemu-5.1.0/target/i386/kvm.c:2713: kvm_buf_set_msrs: Assertion `ret == cpu-\u003ekvm_msr_buf-\u003enmsrs' failed.')\"","timestamp":"2021-02-21T02:17:50.872841Z"}

virtctl version
Client Version: version.Info{GitVersion:"v0.38.1", GitCommit:"8c3ba52f8ce7cbb55c29919e9c263617716aa054", GitTreeState:"clean", BuildDate:"2021-02-08T20:04:23Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.38.1-dirty", GitCommit:"8c3ba52f8ce7cbb55c29919e9c263617716aa054", GitTreeState:"dirty", BuildDate:"2021-02-08T20:30:01Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}

kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"archive", BuildDate:"2020-10-16T02:19:08Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.1", GitCommit:"7879fc12a63337efff607952a323df90cdc7a335", GitTreeState:"clean", BuildDate:"2020-04-08T17:30:47Z", GoVersion:"go1.13.9", Compiler:"gc", Platform:"linux/amd64"}
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: testvm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            bridge: {}
        resources:
          requests:
            memory: 128M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=

StarlingX 4.0

uname -a
Linux controller-0 4.18.0-147.3.1.el8_1.7.tis.x86_64 #1 SMP PREEMPT Fri Oct 16 02:07:34 UTC 2020 x86_64 x86_64 x86_64 GNU/Linux

**Comment by vasiliy-ul** [comment]
I have a feeling that the error comes because of a more-or-less recent version of qemu `5.1.0` and an old Linux kernel `4.18`. For example a similar problem was discussed here: https://forums.gentoo.org/viewtopic-t-1118670-start-0.html:

> I've seen many those warnings when qemu/libvirt is newer than the kernel, since qemu tries to set sub-features but the kernel doesn't allow that yet.

As a workaround you may try to set the CPU model (or maybe features) explicitly to avoid the 0x48e MSR (which is MSR_IA32_VMX_TRUE_PROCBASED_CTLS I guess). Or update the kernel.
