### ISSUE TITLE
Fix go get kubevirt.io/kubevirt

### ISSUE THREAD

**Issue by petrkotas** [kubevirt/kubevirt#507]
Currently the command 
```bash
go get -d kubevirt.io/kubevirt
```
fails with an error
```bash
package kubevirt.io/kubevirt: unrecognized import path "kubevirt.io/kubevirt" (https fetch: Get https://kubevirt.io/kubevirt?go-get=1: dial tcp 83.169.40.234:443: getsockopt: connection refused)
```
To allow simpler deployment and development of kubevirt add-ons, we need `go get` functionality.

Similarly, the 
```bash
go get -d k8s.io/kubernetes
```
is fully functioning and allows for deployment with standard go tools.

@fabiand can you please take a look at this?

**Comment by fabiand** [comment]
I'm not sure what the requirements are to fully support `go get`, but one of the issues is that kubevirt.io is currently a simepl http redirection to the github page. But there is no https redirect setup - because the hoster does not support it IIUIC. I'll look at least into the https part again.

**Comment by petrkotas** [comment]
Hey, I have figured the solution to this issue. However, it has to be implemented by the [Kubevirt.io](http://kubevirt.io) admin.

The go get command can download go packages from version control. This feature, however, requires the proper information for it to work. 

1) It prefers HTTPS connection. The HTTP is allowed only with flag `go get -insecure http://foo`, this is a discouraged settings.
2) It requires the codes to live in some known version control, such as bitbucket.org, github.com, or launchpad.net

For codes living on other servers, the `go get` has to know which version control is used and where the code actually resides.

This has an elegant official solution in form of making our site `go get` compatible. This requires two steps
1) Make HTTPS work. HTTP is discouraged and complicates the `go get` procedure.
2) Change our site from simple redirect to proper site with `go get` specific `<meta>` tags. Specifically for kubevirt, this will look like:
```
https://kubevirt.io/kubevirt
```
```html
<html>
    <head>
        <meta name="go-import" content="kubevirt.io/kubevirt git https://github.com/kubevirt/kubevirt">
    </head>
    <body>
        Can be anything on this site, as long as <meta> is the first thing on the site. Go html parser is not prepared for complicated css and javascript.
    </body>
</html>
```

This solution will give us the same elegant import path as K8s.io is using and allow kubevirt to be included in dependency control with an elegant path.

As for the
```
https://kubevirt.io
```
I would propose let's go with just a redirect to our GitHub pages.

For further information please head [here](https://golang.org/cmd/go/#hdr-Remote_import_paths).

@fabiand what do you think, can we make it work?

**Comment by petrkotas** [comment]
I have implemented the solution for this issue. The PR is already in place here [15](https://github.com/kubevirt/kubevirt.github.io/pull/15).

Second step is to redirect the CNAME in kubevirt.io so that it does not point dorectly to the github but points to [github pages](https://kubevirt.github.io/).

With this solution we will have the redirection and https in place.

@fabiand can you please review this? Thank you.

**Comment by fabiand** [comment]
The first par is fixed:

```
$ go get -d -insecure kubevirt.io/kubevirt
```

https is the next step.
