### ISSUE TITLE
Kubevirt cluster-sync fails: cdi-insecure-registries config-map not found

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#5071]
/kind bug

**What happened**:

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5060/pull-kubevirt-e2e-k8s-1.17/1363387908672720896#1:build-log.txt%3A5471
Fails due to `cdi-insecure-registries config-map not found`
Happens pretty often

**What you expected to happen**:
Should pass

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

Possible that this change exposed it 
https://github.com/kubevirt/kubevirt/pull/4947
Before that it might happend but the retry worked around it

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by oshoval** [comment]
Again
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5002/pull-kubevirt-e2e-k8s-1.19/1364572716350312448

**Comment by oshoval** [comment]
@maya-r 
this one can be closed?
thanks

**Comment by maya-r** [comment]
go for it
