### ISSUE TITLE
kubevirt-io-periodic-link-checker failure (some links return 404)

### ISSUE THREAD

**Issue by thetechnick** [kubevirt/kubevirt#5104]
/kind bug
/triage build-watcher

`kubevirt-io-periodic-link-checker` is failing since `2021-02-09 20:11:51 UTC` due to an increasing number of links returning 404.

```
- ./_site/2020/KubeVirt-installing_Microsoft_Windows_from_an_iso.html
  *  External link https://kubevirt.io/user-guide/virtual_machines/windows_wirtio_drivers/ failed: 404 No error
  *  External link https://kubevirt.io/user-guide/virtual_machines/windows_wirtio_drivers/#how-to-obtain-virtio-drivers failed: 404 No error
- ./_site/hostpath-provisioner-operator/index.html
  *  External link https://kubevirt.io//hostpath-provisioner-operator/ failed: 404 No error
```
https://prow.apps.ovirt.org/job-history/gs/kubevirt-prow/logs/kubevirt-io-periodic-link-checker

**Comment by mazzystr** [comment]
Links are repaired

- ./_site/2020/KubeVirt-installing_Microsoft_Windows_from_an_iso.html > https://github.com/kubevirt/kubevirt.github.io/pull/699
- ./_site/hostpath-provisioner-operator/index.html > https://github.com/kubevirt/kubevirt.github.io/issues/701

We can close this issue
