### ISSUE TITLE
Not support booting disk when using virtio bus on windows VM

### ISSUE THREAD

**Issue by vqthanh** [kubevirt/kubevirt#5110]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
![8B30EB11-1994-40A9-A816-A2AD5802B6D5](https://user-images.githubusercontent.com/36762946/109371880-715ba580-78d9-11eb-854d-62842bb5cbfd.jpeg)

When use bus: virtio:
after installing driver from container disk, 
The disk appeared but notified “not support booting disk...”
**What you expected to happen**:
Can use virtio driver
**How to reproduce it (as minimally and precisely as possible)**:
![16344F46-C856-4AC0-9F43-81E2C85D9E21](https://user-images.githubusercontent.com/36762946/109371837-44a78e00-78d9-11eb-8c6c-a6bbc3e986ab.jpeg)

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dimm0** [comment]
@vqthanh How did you solve this?

**Comment by htlabc** [comment]
i hava the same problem @vqthanh  How did you solve this

**Comment by vqthanh** [comment]
Sorry, I haven’t solved it, i just think I did something wrong and need learning more

**Comment by futuretea** [comment]
@htlabc @vqthanh I have solved it by add bootOrder to the rootdisk
![image](https://user-images.githubusercontent.com/15064560/113119414-ff151280-9242-11eb-87e9-ea1c61e6534b.png)

**Comment by JamesB41** [comment]
@futuretea I...am at a loss for words at how simple this was relative to how much time I spent troubleshooting it. Thank you so much for posting this.
