### ISSUE TITLE
how to hotplug interface、cpu、memory in the running vm?

### ISSUE THREAD

**Issue by watermelon-brother** [kubevirt/kubevirt#5142]
**What happened**:
I want add/reduce the cpu num or memory or interface  in the running vm ,so,how can do it ?
**What you expected to happen**:
I know that current kubevirt version is not support above function,I want develop it, do you have any idea to me?
**How to reproduce it (as minimally and precisely as possible)**:
nothing...

**Anything else we need to know?**:
I want join the kubevirt development team!
**Environment**:
- KubeVirt version (use `virtctl version`):v0.38
- Kubernetes version (use `kubectl version`):v1.19.1
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by phoracek** [comment]
@watermelon-brother This is definitely something we want to have in KubeVirt. Could you please split this into a separate RFE per each type of device? Then provide specific usecases you want to support. If you want to start working on it, proposing a design on our mailing list.
