### ISSUE TITLE
[Serial][rfe_id:393][crit:high][vendor:cnv-qe@redhat.com][level:system] VM Live Migration Starting a VirtualMachineInstance rook-ceph live migration cancelation [test_id:3241]should be able to cancel a migration right after posting it

### ISSUE THREAD

**Issue by tomob** [kubevirt/kubevirt#5143]
/kind bug
/triage build-watcher

**What happened**:

Test timed out:

```
tests/migration_test.go:1517
Timed out after 180.000s.
Expected
    <bool>: false
to be true
tests/migration_test.go:224
```

**Anything else we need to know?**:

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4387/pull-kubevirt-e2e-k8s-1.17-rook-ceph/1364872943875657728

**Environment**:

Root-ceph storage, k8s-1.17

**Comment by oshoval** [comment]
Again
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5167/pull-kubevirt-check-tests-for-flakes/1369920144674918400

**Comment by qinqon** [comment]
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5207/pull-kubevirt-e2e-k8s-1.18/1370139207158206464
