### ISSUE TITLE
Run windows vm on kubevirt

### ISSUE THREAD

**Issue by sunkai-XDD** [kubevirt/kubevirt#5148]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind question
> /kind enhancement

**What happened**:
I want to create a windows vm on my kubevirt env，but it seems meet some question，i can’t create correctly
**What you expected to happen**:
create a windows vm
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
![image](https://user-images.githubusercontent.com/42962379/109919387-87130580-7cf3-11eb-85ff-77bfc19487fe.png)

![image](https://user-images.githubusercontent.com/42962379/109919358-7cf10700-7cf3-11eb-8109-8550a3b9b175.png)
 here is my yaml file and the env error
**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by yangxiaoliang** [comment]
probably you used a dedicated volume source, please update "registryDisk" to "containerDisk" to see if it works

https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#containerdisk
