### ISSUE TITLE
kubevirt running windows  image not suppot booting disk

### ISSUE THREAD

**Issue by htlabc** [kubevirt/kubevirt#5151]
**What happened**:
![image](https://user-images.githubusercontent.com/20431134/109943421-2645f600-7d10-11eb-9033-502c8b4c6d48.png)

When use bus: virtio:
after installing driver from container disk,
The disk appeared but notified “not support booting disk...”

![image](https://user-images.githubusercontent.com/20431134/109943197-e4b54b00-7d0f-11eb-86be-eb68f91f60da.png)

**Environment**:
- KubeVirt version (use `virtctl version`): 1.30.0
- Kubernetes version (use `kubectl version`): 1.18.6
- VM or VMI specifications:
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release):  Ubuntu 18.04.5 LTS
- Kernel (e.g. `uname -a`): 5.4.0-66-generic
- Install tools:
- Others:
my vm/vmi specifications:

apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: win10
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: win10
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - bootOrder: 1
            cdrom:
              bus: sata
            name: cdromiso
          - disk:
              bus: virtio
            name: harddrive
          - cdrom:
              bus: sata
            name: virtiocontainerdisk
          interfaces:
          - masquerade: {}
            model: e1000
            name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 16G
      networks:
      - name: default
        pod: {}
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: iso-win10
      - name: harddrive
        hostDisk:
          capacity: 30Gi
          path: /data/disk.img
          type: DiskOrCreate
      - containerDisk:
          image: kubevirt/virtio-container-disk
        name: virtiocontainerdisk

**Comment by awels** [comment]
You will need to also attach the virtio drivers disk so you can point windows to it.

**Comment by mazzystr** [comment]
User-guide has some good directions on how to attach virtio driver disk.  Link is [here](https://kubevirt.io/user-guide/virtual_machines/windows_virtio_drivers/#how-to-obtain-virtio-drivers)

You can also d/l the latest/greatest from the virtio-win project.  Link is [here](https://github.com/virtio-win/virtio-win-pkg-scripts/blob/master/README.md)

**Comment by availati** [comment]
Hi @awels  and @mazzystr ,
looking at yaml and problem description, he already has installed virtio-win drivers attaching virtio-container-disk.
The same I did, following w2k12 tutorial https://kubevirt.io/2020/KubeVirt-installing_Microsoft_Windows_from_an_iso.html, and I'm stucked in same point with same error.
A point more is that on same host, if I try install win2k12 with virt-manager, mounting virtio disks, the installation procedure has no problem, disks works and finally vm works well

**Comment by awels** [comment]
Well if you mounted the virtio disk with a container disk, you have to pick load drivers and pick the drive the container disk is in. The container disk cannot be virtio (as it can't be read until the drivers are installed). Once you have loaded the drivers it should be able to use the virtio drive.
