### ISSUE TITLE
Org permissions

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt#5155]
@fabiand  @davidvossel  Can someone check the settings to the KubeVirt org?  I should be a member and maintainer.

I should be able to adjust settings like Branch Protection via the web portal to at least membership, community, kubevirt.github.io, user-guide, demo, katacoda-scenarios, and kubevirt-tutorial repos.  I'm not able to even see the branch protection settings or any of the other advanced settings like GitHub Pages.

I noticed this when I tried to remove the old user-guide release-0.XX branches.  

The really weird thing is I have full access to cloud-image-builder.  I never heard of that one.

A lot of work is coming up where I'll need this access... We have to rename master branch in relation to kind wording initiative, kubevirt.git.io CI is going to get refactored similar to what we did for user-guide, and repos need a Prow job to enforce protected branches.

Thanks,
/Chris Callegari

**Comment by davidvossel** [comment]
@mazzystr i'm working on this

**Comment by davidvossel** [comment]
@mazzystr you're set as a "maintainer" for most of these projects. For user-guide for example, does that not let you adjust branch protection settings? If not i can bump to admin priv
