### ISSUE TITLE
Clean up our Describe/Context/It/By usage in unit tests and functional tests

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#518]
- [ ] Start  using multiple Describe blocks instead of Context
- [ ] Start  using Context really as Context to Describes
- [ ] Start using the `By` function in our tests
- [ ] In general go over all our descriptions and update the descriptions to be a nice narrative

See https://onsi.github.io/ginkgo/#organizing-specs-with-containers-describe-and-context for context.

**Comment by shiywang** [comment]
hi @rmohr 
I'm a new member of cnv-qe, also a part-time kubernetes reviewer/maintianer, I would like to dig on this one if there's no one else.

**Comment by cynepco3hahue** [comment]
@shiywang Do you work on it? Because I just started to play with reporters and some test names looks like abrakadabra
For example
`CloudInit UserData CloudInit Data Source NoCloud should launch ephemeral vm with cloud-init data source NoCloud`

**Comment by shiywang** [comment]
hi, @cynepco3hahue currently I'm not working on it, and also have some jobs assigned by storage team, and I might be a little bit procrastinating on this if I would had started on this since my main responsibility is on storage QE, so feel free to take it : )
