### ISSUE TITLE
[Unit-test] [Flaky] SRIOV HostDevice safe detachment   fails due to a missing event from a sriov device 

### ISSUE THREAD

**Issue by xpivarc** [kubevirt/kubevirt#5201]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Unit test failed in https://github.com/kubevirt/kubevirt/pull/5183 .
See https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5183/pull-kubevirt-unit-test/1369687355304185856

**What you expected to happen**:
Pass
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/assign @EdDev

**Comment by EdDev** [comment]
The issue in hand is basically resolved, the only leftover is to try and change the tested function to allow tests not to depend on the timer (e.g. stub/mock it).
