### ISSUE TITLE
Mdev discover failed

### ISSUE THREAD

**Issue by wangzh21** [kubevirt/kubevirt#5211]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind enhancement

**What happened**:
I'd like to config my intel GPU in kubevirt cluster. Then I follow the doc https://kubevirt.io/user-guide/virtual_machines/host-devices/, but there is no file /sys/bus/pci/devices/SLOT:BUS:DOMAIN.FUNCTION/mdev_supported_types/TYPE/name in my env. And Intel guy said that they do not have the `name` file. Also, I find the same issue in Openstack https://github.com/openstack/nova/blob/cb4c5b5473179cfc46dbdc9de8487006bf2d99e9/nova/virt/libvirt/driver.py#L7431 
attribute `name` is optional, so we should improve kubevirt to compatible with it.
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by vladikr** [comment]
There is a PR that addresses this issue: https://github.com/kubevirt/kubevirt/pull/5215
Thank you for reporting this!
