### ISSUE TITLE
Unit tests results are cached in CI

### ISSUE THREAD

**Issue by vasiliy-ul** [kubevirt/kubevirt#5217]
By default Bazel caches the results of unit tests execution and does not re-run the tests if the corresponding sources have not beed modified. That is also the case for the execution in CI at the moment:

```
//cmd/container-disk-v2alpha:go_default_test                    (cached) PASSED in 0.1s
484
//pkg/certificates:go_default_test                              (cached) PASSED in 0.0s
485
//pkg/certificates/bootstrap:go_default_test                    (cached) PASSED in 0.1s
486
//pkg/cloud-init:go_default_test                                (cached) PASSED in 0.0s
487
//pkg/config:go_default_test                                    (cached) PASSED in 0.1s
488
//pkg/container-disk:go_default_test                            (cached) PASSED in 0.0s
489
//pkg/controller:go_default_test                                (cached) PASSED in 0.0s
490
//pkg/emptydisk:go_default_test                                 (cached) PASSED in 0.1s
491
//pkg/ephemeral-disk:go_default_test                            (cached) PASSED in 0.0s
492
//pkg/ephemeral-disk-utils:go_default_test                      (cached) PASSED in 0.0s
493
//pkg/hooks:go_default_test                                     (cached) PASSED in 0.1s
494
//pkg/host-disk:go_default_test                                 (cached) PASSED in 0.1s
```

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5136/pull-kubevirt-unit-test/1368172498033577987
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/4907/pull-kubevirt-unit-test/1364640663722790912
https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5082/pull-kubevirt-unit-test/1369283066664587264

Is there a specific reason for not re-running all the tests each time? I dont think the unit tests produce big load on CI. I would propose to disable caching in `pull-kubevirt-unit-test` job. That may help to identify flaky tests earlier (e.g. https://github.com/kubevirt/kubevirt/pull/5218). It is possible to disable caching with `--cache_test_results=no` option. Additionally I would also consider specifying `--runs_per_test=n` (n>1).

/kind enhancement

**Comment by rmohr** [comment]
> Is there a specific reason for not re-running all the tests each time? I dont think the unit tests produce big load on CI. I would propose to disable caching in `pull-kubevirt-unit-test` job. That may help to identify flaky tests earlier (e.g. #5218). It is possible to disable caching with `--cache_test_results=no` option. Additionally I would also consider specifying `--runs_per_test=n` (n>1).

In general you are right. As it is right now, where we first pull everything from the cache, just to then not run the tests, does not make much difference. The heavy part is pulling everything, just to then find out that most of the tests do not even need to be executed.

I was working on making use of `--remode_download_minimal`, which would have led to downloading actually nothing, and that makes a drastic difference. 

Your request makes sense but the two goals are slightly contradicting. Any idea on how we can go with full cache advantage but still catch issues faster? Maybe a periodic which runs with  `--cache_test_results=no` and a higher `n` for `--runs_per_test=n` ?

**Comment by rmohr** [comment]
I made up my mind. As you say. It is not too important for CI load. Let's see that we detect flakes early. :+1:

**Comment by vasiliy-ul** [comment]
.. and I already started thinking that a periodic might fit better :) since it will not impact the PRs.

Anyway when I was trying to run locally with `runs_per_test` I noted that there were tests which fail. I think that is because they use some dependencies internally and do not mock them (e.g. a system directory). Apart from that I see that the execution of some tests takes too long (>2min for some cases). IMHO the unit tests shold run very fast. So I was planning to address those issues as a first step. Maybe after that we can decide on how to run that in CI.
