### ISSUE TITLE
virt-handler introduces a "hidden" dependency when it calls virt-chroot with hard-coded "qemu" user

### ISSUE THREAD

**Issue by enp0s3** [kubevirt/kubevirt#5245]
/kind bug

**What happened**:
virt-handler `GetImageInfo` failed because no `qemu` user was defined in the virt-handler container.

**What you expected to happen**:
Either manage the qemu user existence directly from Bazel, or make virt-chroot independent of a specific user.

**How to reproduce it (as minimally and precisely as possible)**:
When building virt-handler, consume RHEL-AV stream for installation of the virt packages. 

**Anything else we need to know?**:
Currently not sure which update package of virt caused the qemu user to dissappear.
Will update the issue later on.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.39.0
- Kubernetes version (use `kubectl version`): 
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
-

**Comment by xpivarc** [comment]
@enp0s3 I think this is still an issue.
