### ISSUE TITLE
failed to configure vmi network: Critical network error: error creating tap device named tap0

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#5260]
/kind bug

**What happened**:

I sometimes see in jobs like this one https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5248/pull-kubevirt-e2e-k8s-1.19/1372457569523601411, the following sync errors:

```
"reason": "SyncFailed",
            "message": "failed to configure vmi network: Critical network error: error creating tap device named tap0; failed to execute command in launcher namespace 31955: exit status 1",
```

I have seen it on different tests, therefore not filing it under a specific one.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@AlonaKaplan @qinqon FYI

**Comment by wenchao5211** [comment]
I have the same problem. Have you solved it yet?
