### ISSUE TITLE
Failed to launch VMI with VirtioFS disk on k8s-1.20 provider

### ISSUE THREAD

**Issue by enp0s3** [kubevirt/kubevirt#5267]
/kind bug

**What happened**:
All VirtioFS related functional tests are failing on k8s-1.20 provider
The error message that comes from QEMU is :
```code
"LibvirtError(Code=1, Domain=10, Message='internal error: qemu unexpectedly closed the monitor: 2021-03-17T23:15:49.330206Z qemu-kvm: -device vhost-user-fs-pci,chardev=chr-vu-fs0,queue-size=1024,tag=disk1,bus=pci.1,addr=0x0: Failed to write msg. Wrote -1 instead of 12.\\n2021-03-17T23:15:49.330252Z qemu-kvm: -device vhost-user-fs-pci,chardev=chr-vu-fs0,queue-size=1024,tag=disk1,bus=pci.1,addr=0x0: vhost_dev_init failed: Operation not permitted')\""
```
**What you expected to happen**:
VMI with virtoFS disks to successfully start and run, as it does with other FS types.

**How to reproduce it (as minimally and precisely as possible)**:
```code
export KUBEVIRT_PROVIDER=k8s-1.20
make cluster-up 
make cluster-sync
# focus the viortfs tests in storage_test
make functest
```

**Anything else we need to know?**:
The issue reproduces also when SELinux is permissive

Will paste here a log from virt-launcher with `debugLogs: true`
[debug.txt](https://github.com/kubevirt/kubevirt/files/6166213/debug.txt)

**Environment**:
```code
[root@node01 ~]# crictl version
Version:  0.1.0
RuntimeName:  cri-o
RuntimeVersion:  1.20.0
RuntimeApiVersion:  v1alpha1

```
- KubeVirt version (use `virtctl version`): latest master
- Kubernetes version (use `kubectl version`): 1.20.4
- VM or VMI specifications:

[virtiofs_domain.txt](https://github.com/kubevirt/kubevirt/files/6166240/virtiofs_domain.txt)

- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by vladikr** [comment]
Is it a specific test that failed or both of them?

**Comment by enp0s3** [comment]
> Is it a specific test that failed or both of them?

@vladikr Hi. Yes, both are failing on K8s 1.20 with same libvirt error.

**Comment by xpivarc** [comment]
/close

[Fix](https://github.com/kubevirt/kubevirt/pull/5305 )
