### ISSUE TITLE
Think about assigning names to devices

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#528]
With https://www.redhat.com/archives/libvir-list/2017-October/msg00993.html merged, it is now possible to give devices names. This greatly simplifies hotplug and synchronization operations on Domains for managment applications.

We could give all our devices names, like Pods have names for containers. We would inherit the same pros.

**Comment by michalskrivanek** [comment]
that's great news!

**Comment by fromanirh** [comment]
awesome!

**Comment by rmohr** [comment]
As outlined in https://github.com/kubevirt/kubevirt/blob/master/docs/vm-configuration.md#device-naming devices will have a mandatory name to make device tracking and hotplug as easy as possible for everyone (kubevirt consumers, kubevirt internal use, libvirt).
