### ISSUE TITLE
[Flaky CI] Unexpected Warning event received ... fatal error: runtime: cannot allocate memory

### ISSUE THREAD

**Issue by oshoval** [kubevirt/kubevirt#5285]
/kind bug

**What happened**:
`[sig-network] [Serial]Services Masquerade interface binding *without* a service matching the vmi exposed should fail to reach the vmi` is flaky

https://prow.apps.ovirt.org/view/gcs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.19-sig-network/1373786699879944192

**What you expected to happen**:
Should be stable

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
I would suggest to increase memory of Cirros, from 128Mi to 512Mi, as 512Mi is the guarantee safe
according Cirros community, and they use 512Mi for their boot tests them self.

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
Looking at the ci search dashboard: https://search.ci.kubevirt.io/?search=failed+to+get+image+info%3A+failed+to+invoke+qemu-img%3A&maxAge=336h&context=1&type=bug%2Bjunit&name=&maxMatches=5&maxBytes=20971520&groupBy=job

I see it occuring the first time 7 days ago on this PR: https://github.com/kubevirt/kubevirt/pull/5102. It then disappeared  in the build logs until work was resumed on this PR and it got merged. Now it appears on many places.

/assign @iholder-redhat 
/assign @enp0s3

**Comment by rmohr** [comment]
I would suggest reverting #5102 and investigate #5102 in a new PR.

**Comment by iholder-redhat** [comment]
> I would suggest reverting #5102 and investigate #5102 in a new PR.

@rmohr Sure, I'm on it.

**Comment by rmohr** [comment]
I see that since this got merged, we only had one single appearance: https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/577/check-provision-k8s-1.19/1374433589126500352 (still one too much but at least CI is happier).

**Comment by iholder-redhat** [comment]
> I see that since this got merged, we only had one single appearance: https://prow.apps.ovirt.org/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirtci/577/check-provision-k8s-1.19/1374433589126500352 (still one too much but at least CI is happier).

I'm trying to think about how to identify where the problem is coming from. Will sync with @dhiller about it. Also will try to `increase memory of Cirros, from 128Mi to 512Mi` as @oshoval suggested above to see if it helps.

**Comment by rmohr** [comment]
> I'm trying to think about how to identify where the problem is coming from. Will sync with @dhiller about it. Also will try to `increase memory of Cirros, from 128Mi to 512Mi` as @oshoval suggested above to see if it helps.

I don't see a connection. `qemu-img` is run from virt-handler and not from virt-launcher. It makes no difference if you give the VM more memory.

**Comment by iholder-redhat** [comment]
This is already fixed as part of this PR: https://github.com/kubevirt/kubevirt/pull/5495

**Comment by rmohr** [comment]
/close

Fixed in https://github.com/kubevirt/kubevirt/pull/5495 in that line: https://github.com/kubevirt/kubevirt/pull/5495/files#diff-1a400d7080998dd966ffced5802774bddef51887b50f04b307e8b7322933d313R20
