### ISSUE TITLE
Disk driver cache not always set

### ISSUE THREAD

**Issue by greg-bock** [kubevirt/kubevirt#5290]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
If a VM fails to start on the first try disk cache settings can be lost. This is due to the fact that setting the disk cache is only done once in _preStartHook_ (manager.go). _SyncVMI_ (and _PrepareMigrationTarget_) calls _Convert_v1_VirtualMachine_To_api_Domain_ which rebuilds the disk objects. Suggested fix is to call SetDriverCacheMode (and SetOptimalIOMode in newer versions of Kubevirt) in SyncVMI and PrepareMigrationTarget instead of preStartHook. 

**What you expected to happen**:
Disk cache should always be set correctly. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Closing #4994 as it isn't getting traction and I don't have the cycles to chase it anymore. 
**Environment**:
- KubeVirt version (use `virtctl version`): All versions appear to be affected. 
- Kubernetes version (use `kubectl version`): NA
- VM or VMI specifications: NA
- Cloud provider or hardware configuration: NA
- OS (e.g. from /etc/os-release): NA
- Kernel (e.g. `uname -a`): NA
- Install tools: NA
- Others: NA

**Comment by greg-bock** [comment]
This issue could lead to data loss when the underlying device is using the wrong cache settings.

**Comment by greg-bock** [comment]
This issue could lead to data loss when the underlying device is using the wrong cache settings.

**Comment by xpivarc** [comment]
/reopen
We should fix this or confirm this is working.

**Comment by greg-bock** [comment]
In the event anyone comes across this issue it was fixed as a byproduct of #8068
