### ISSUE TITLE
Review & update CONTRIBUTING

### ISSUE THREAD

**Issue by mazzystr** [kubevirt/kubevirt#5295]
Review & update CONTRIBUTING.

I suggest we follow very closely to the Kubernetes page so we don't have to maintain multiple wheels
https://github.com/kubernetes/kubernetes/blob/master/CONTRIBUTING.md

**Comment by amino19** [comment]
Or we can just follow the <a href="https://github.com/kubernetes/community/tree/master/contributors/guide"> guide </a> itself. :slightly_smiling_face:
