### ISSUE TITLE
GroupVersionKind not filled when fetching TPRs from apiserver

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#53]
The rest client does not fill the GroupVersionKind of the fetched object, we are working aroung that here:

https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-api/rest/kubeproxy.go#L85.

There seems to be a bug report in the kubernetes sdk alredy: https://github.com/kubernetes/client-go/issues/60.

**Comment by fabiand** [comment]
@stu-gott I guess this should be fixed with the api server migration. Right?

**Comment by fabiand** [comment]
Does this still apply to CRDs?

**Comment by rmohr** [comment]
No, CRDs don't have this. Closing.
