### ISSUE TITLE
Several unit tests are flaky and need to get fixed

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#5313]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:

/kind bug
> /kind enhancement

**What happened**:

With PR we introduced some changes to our testing on CI that a) avoids caching of test results and b) tests multiple times. Now a couple of PRs already have suffered by the unit test lane `pull-kubevirt-unit-test` blocking merges due to flaky unit tests.

The test suites discovered that were flaky are (please add to this list so we have it complete)

*  TestVirtOperator
* TestVirtWrap
* TestMigrationProxy
* TestCache
* TestHeartbeat
* TestComponents

Source PR histories:
* [#5308](https://prow.apps.ovirt.org/pr-history/?org=kubevirt&repo=kubevirt&pr=5308)
* [#5300](https://prow.apps.ovirt.org/pr-history/?org=kubevirt&repo=kubevirt&pr=5300)
* [#5311](https://prow.apps.ovirt.org/pr-history/?org=kubevirt&repo=kubevirt&pr=5311)

Possible candidates (couldn't verify flakiness yet):
* [#5022](https://prow.apps.ovirt.org/pr-history/?org=kubevirt&repo=kubevirt&pr=5022)
 
See #5308, #5312

/cc @rmohr @fgimenez 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by acardace** [comment]
Test `should verify that migration failure is set in the monitor thread` is flaky and managed to catch a stack trace when running it with `hack/dockerized bazel test --repository_cache='' --test_output=all  --features race --cache_test_results=no --runs_per_test=4  //pkg/virt-launcher/virtwrap:go_default_test`

Here's the stack trace:

```
goroutine 13 [running]:
kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
        vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:55 +0x169
panic(0x2552c80, 0x2b54e40)
        GOROOT/src/runtime/panic.go:679 +0x1b2
kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo.Fail(0xc0019e2f00, 0x25, 0xc001c96bd0, 0x1, 0x1)
        vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:267 +0x12f
kubevirt.io/kubevirt/vendor/github.com/onsi/gomega/internal/assertion.(*Assertion).match(0xc0006d93c0, 0x2bae7c0, 0x47c1920, 0x1, 0x0, 0x0, 0x0, 0x26caa80)
        vendor/github.com/onsi/gomega/internal/assertion/assertion.go:79 +0x308
kubevirt.io/kubevirt/vendor/github.com/onsi/gomega/internal/assertion.(*Assertion).To(0xc0006d93c0, 0x2bae7c0, 0x47c1920, 0x0, 0x0, 0x0, 0x2552c80)
        vendor/github.com/onsi/gomega/internal/assertion/assertion.go:38 +0x11c
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap.glob..func2.8.3.2(0xc00020aa80, 0x944, 0x0, 0x0, 0x0, 0x0)
        pkg/virt-launcher/virtwrap/manager_test.go:1067 +0x1e2
reflect.Value.call(0x259fba0, 0xc000535c80, 0x13, 0x2823941, 0x4, 0xc0000e3600, 0x1, 0x1, 0x10, 0x10, ...)
        GOROOT/src/reflect/value.go:460 +0x62b
reflect.Value.Call(0x259fba0, 0xc000535c80, 0x13, 0xc0000e3600, 0x1, 0x1, 0xc0002611a0, 0xc0002611a0, 0x94)
        GOROOT/src/reflect/value.go:321 +0xd4
kubevirt.io/kubevirt/vendor/github.com/golang/mock/gomock.(*Call).DoAndReturn.func1(0xc000261170, 0x1, 0x1, 0xc0000e35e0, 0x2, 0x2)
        vendor/github.com/golang/mock/gomock/call.go:123 +0x4f0
kubevirt.io/kubevirt/vendor/github.com/golang/mock/gomock.(*Controller).Call(0xc0004e2330, 0x2750b00, 0xc000419f00, 0x28336ea, 0xf, 0xc000261170, 0x1, 0x1, 0x0, 0x3, ...)
        vendor/github.com/golang/mock/gomock/controller.go:221 +0x145
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/cli.(*MockConnection).DomainDefineXML(0xc000419f00, 0xc00020aa80, 0x944, 0x0, 0x2, 0x2, 0x0)
        pkg/virt-launcher/virtwrap/cli/generated_mock_libvirt.go:46 +0x128
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/util.SetDomainSpecStr(0x2bff5a0, 0xc000419f00, 0xc00017db00, 0xc00020aa80, 0x944, 0x0, 0x0, 0xc0006d4d50, 0x5275d7)
        pkg/virt-launcher/virtwrap/util/libvirt_helper.go:104 +0x399
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/util.SetDomainSpecStrWithHooks(0x2bff5a0, 0xc000419f00, 0xc00017db00, 0xc000666900, 0x0, 0x0, 0x0, 0xc0001d0000)
        pkg/virt-launcher/virtwrap/util/libvirt_helper.go:120 +0xf7
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap.(*LibvirtDomainManager).setDomainSpecWithHooks(...)
        pkg/virt-launcher/virtwrap/manager.go:1976
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap.(*LibvirtDomainManager).setMigrationResultHelper(0xc0004f42d0, 0xc00017db00, 0x430101, 0xc00004fdc0, 0x38, 0x0, 0x0, 0x0, 0x0)
        pkg/virt-launcher/virtwrap/manager.go:316 +0x7fb
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap.(*LibvirtDomainManager).setMigrationResult.func1(0xc00068d130, 0xc001f7b5a0, 0xc0001d0000)
        pkg/virt-launcher/virtwrap/manager.go:233 +0x81
kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/util/wait.runConditionWithCrashProtection(0xc00068d3c0, 0xc0000f5a00, 0x0, 0x0)
        vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:211 +0x7d
kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/util/wait.pollImmediateInternal(0xc001f7b5a0, 0xc0006d53c0, 0xc001f7b5a0, 0x1)
        vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:445 +0x3d
kubevirt.io/kubevirt/vendor/k8s.io/apimachinery/pkg/util/wait.PollImmediate(0x2540be400, 0xdf8475800, 0xc00068d3c0, 0xc001f7b480, 0xc001bb78f0)
        vendor/k8s.io/apimachinery/pkg/util/wait/wait.go:441 +0x5f
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap.(*LibvirtDomainManager).setMigrationResult(0xc0004f42d0, 0xc00017db00, 0xc00068d701, 0xc00004fdc0, 0x38, 0x0, 0x0, 0x1, 0x0)
        pkg/virt-launcher/virtwrap/manager.go:232 +0x113
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap.(*LibvirtDomainManager).asyncMigrate.func1(0xc0000f5770, 0xc0004f42d0, 0xc00017db00)
        pkg/virt-launcher/virtwrap/manager.go:507 +0x72d
created by kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap.(*LibvirtDomainManager).asyncMigrate
        pkg/virt-launcher/virtwrap/manager.go:486 +0x61
```

Interestingly I managed to get it to fail only when running 4+ runs per test.

**Comment by vasiliy-ul** [comment]
Apart from flakiness because of e.g. timeouts there are also tests that may use some hardcoded common resources, e.g.:
```
{"component":"","level":"error","msg":"failed to create unix socket for proxy service","pos":"migration-proxy.go:365","reason":"listen tcp 0.0.0.0:12345: bind: address already in use","timestamp":"2021-03-24T21:12:15.175468Z"}
```
Probably here the listening port needs to be randomized otherwise the parallel execution will fail.

**Comment by acardace** [comment]
> Apart from flakiness because of e.g. timeouts there are also tests that may use some hardcoded common resources:
> 
> ```
> {"component":"","level":"error","msg":"failed to create unix socket for proxy service","pos":"migration-proxy.go:365","reason":"listen tcp 0.0.0.0:12345: bind: address already in use","timestamp":"2021-03-24T21:12:15.175468Z"}
> ```
> 
> Probably here the listening port needs to be ~randomized~ (actually no, randomization will make it even harder to detect issues) otherwise the parallel execution will fail.

This is exactly what's making `should verify that migration failure is set in the monitor thread` fail, If it makes sense we can just let the OS decide the port so that conflicts will not occur.

**Comment by acardace** [comment]
> > Apart from flakiness because of e.g. timeouts there are also tests that may use some hardcoded common resources:
> > ```
> > {"component":"","level":"error","msg":"failed to create unix socket for proxy service","pos":"migration-proxy.go:365","reason":"listen tcp 0.0.0.0:12345: bind: address already in use","timestamp":"2021-03-24T21:12:15.175468Z"}
> > ```
> > 
> > 
> > Probably here the listening port needs to be ~randomized~ (actually no, randomization will make it even harder to detect issues) otherwise the parallel execution will fail.
> 
> This is exactly what's making `should verify that migration failure is set in the monitor thread` fail, If it makes sense (hence it's not a well-known port in this context) we can just let the OS decide the port so that conflicts will not occur.

Just not possible, the migration proxy uses a pair of known-ports between virt-launcher and virt-handler, either we pass this information somehow (but the pain is probably higher than the gain) or we instruct bazel to not spawn multiple processes running this test in parallel.

**Comment by rmohr** [comment]
> Just not possible, the migration proxy uses a pair of known-ports between virt-launcher and virt-handler, either we pass this information somehow (but the pain is probably higher than the gain) or we instruct bazel to not spawn multiple processes running this test in parallel.

Making not configurable values in production configurable for testing is pretty normal and should be done.

**Comment by acardace** [comment]
> > Just not possible, the migration proxy uses a pair of known-ports between virt-launcher and virt-handler, either we pass this information somehow (but the pain is probably higher than the gain) or we instruct bazel to not spawn multiple processes running this test in parallel.
> 
> Making not configurable values in production configurable for testing is pretty normal and should be done.

Yes, actually this makes a lot of sense, thank you @rmohr. I'll try putting together a PR to fix this test.

**Comment by vasiliy-ul** [comment]
To address the timing issues I think it makes sense to introduce a simple interface:
```go
type TimeSource interface {
	Now() time.Time
}
```
The default implementation will just return `time.Now()`. But in the code all the calls to `time.Now()` need to be repaced with `timeSource.Now()`. Then in the tests it will be easy to mock the call and thus avoid dependencies on real timeouts.

Such change will require some ammount of refactoring across the whole code-base though. Will need to pass the timeSource to all the objects that use current time. Any thoughts or objections?
