### ISSUE TITLE
Support Disk Hot Resize

### ISSUE THREAD

**Issue by wavezhang** [kubevirt/kubevirt#5325]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:
block pvc support hot resize，but when kubevirt vm use block pvc, it donot support hot resize
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by phoracek** [comment]
Could you please share which storage provisioner are you using?

**Comment by wavezhang** [comment]
CSI support hot resize，but block in vm didnot update. Need use virsh blockresize to notify.

**Comment by kvaps** [comment]
/reopen

I use linstor-csi.

I resized pvc, the block device inside the pod updated normally to new size, but inside the vm it wasn't.
To update the vm I forced to run commands manually:

```bash 
# virsh domblklist 1
 Target   Source
--------------------------------------------------------------------------------------------
 vda      /dev/boot
 vdb      /var/run/kubevirt-ephemeral-disks/cloud-init-data/default/frontend-0/noCloud.iso

# virsh blockresize 1 /dev/boot --size 21g
Block device '/dev/boot' is resized
```

**Comment by kvaps** [comment]
the same with filesystem mode

**Comment by kvaps** [comment]
To make hot resize working you just need to enable `ExpandDisks` feature gate.

/close
