### ISSUE TITLE
basic virtual machine health monitoring

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#533]
We need basic support for detecting when a VM is wedged and options for recovering that VM.

As a starting point we should implement watchdog support similar to what libvirt already supports.
https://wiki.openstack.org/wiki/LibvirtWatchdog

It's also possible we could use some other methods, like pinging a qemu guest agent to test responsiveness and checking cpu/memory thresholds.  

Ideally, it would be nice if we could come up with the ability to generically monitor a VM's responsiveness without requiring any special guest functionality.

**Comment by davidvossel** [comment]
This someone ties into #413. We need a way to detect VMs are wedged, and then have recovery options. #413 discusses recovery options while this issue is focused on detecting there's a VM issue that doesn't manifest itself as a qemu crash.

**Comment by michalskrivanek** [comment]
I'd like to consider pvpanic device, it's a bit more generic and doesn't require guest agent to function. It should be added as part of implementing #466 

Performing guest-side health checks is a bit more involved, for that an agent would be needed, but there is no support in qemu-ga for that

**Comment by fabiand** [comment]
@davidvossel so - we do have a watchdog device. But what is missing to resolve this issue?
