### ISSUE TITLE
virt-operator CrashLoopBackOff

### ISSUE THREAD

**Issue by bhkamath** [kubevirt/kubevirt#5339]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
virt-operator is in CrashLoopBackOff state
kubevirt      virt-operator-58644dcfcc-7nn8n      0/1     CrashLoopBackOff   50         4h21m
kubevirt      virt-operator-58644dcfcc-gk9th      0/1     CrashLoopBackOff   50         4h21m

kubectl apply -f https://raw.githubusercontent.com/kubevirt/demo/master/manifests/vm.yaml
error: unable to recognize "https://raw.githubusercontent.com/kubevirt/demo/master/manifests/vm.yaml": no matches for kind "VirtualMachine" in version "kubevirt.io/v1alpha3"

**What you expected to happen**:
Expected to create testvm using the vm.yaml file and be able to operate on virtual machine, testvm

**How to reproduce it (as minimally and precisely as possible)**:
A Kubernetes cluster with a master and three worker nodes.
Kubernetes Master and Worker nodes are Virtual Machines with CentOS 7 on it.

> kubectl get nodes
> NAME          STATUS   ROLES    AGE   VERSION
> kf-master     Ready    master   9h    v1.18.17
> kf-worker-1   Ready    <none>   9h    v1.18.17
> kf-worker-2   Ready    <none>   9h    v1.18.17
> kf-worker-3   Ready    <none>   9h    v1.18.17
> 

> echo $KUBEVIRT_VERSION
> v0.39.0
> 
> kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${KUBEVIRT_VERSION}/kubevirt-operator.yaml
> kubectl create configmap -n kubevirt kubevirt-config --from-literal debug.useEmulation=true
> kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${KUBEVIRT_VERSION}/kubevirt-cr.yaml
> 

> kubectl get pods --all-namespaces
> NAMESPACE     NAME                                READY   STATUS             RESTARTS   AGE
> default       busybox                             0/1     Completed          0          21m
> kube-system   coredns-66bff467f8-8fw2m            1/1     Running            0          9h
> kube-system   coredns-66bff467f8-92hv4            1/1     Running            0          9h
> kube-system   etcd-kf-master                      1/1     Running            0          9h
> kube-system   kube-apiserver-kf-master            1/1     Running            0          9h
> kube-system   kube-controller-manager-kf-master   1/1     Running            0          9h
> kube-system   kube-flannel-ds-2s8ss               1/1     Running            0          9h
> kube-system   kube-flannel-ds-l854t               1/1     Running            2          9h
> kube-system   kube-flannel-ds-lc97p               1/1     Running            0          9h
> kube-system   kube-flannel-ds-pzpzw               1/1     Running            0          9h
> kube-system   kube-proxy-2z9h7                    1/1     Running            0          9h
> kube-system   kube-proxy-btwjp                    1/1     Running            0          9h
> kube-system   kube-proxy-ctvpb                    1/1     Running            0          9h
> kube-system   kube-proxy-zljpx                    1/1     Running            0          9h
> kube-system   kube-scheduler-kf-master            1/1     Running            0          9h
> kubevirt      virt-operator-58644dcfcc-7nn8n      0/1     CrashLoopBackOff   54         4h42m
> kubevirt      virt-operator-58644dcfcc-gk9th      0/1     CrashLoopBackOff   54         4h42m
> 

> kubectl apply -f https://raw.githubusercontent.com/kubevirt/demo/master/manifests/vm.yaml

> virtctl version
> Client Version: version.Info{GitVersion:"v0.39.0", GitCommit:"6493f7130788fc2242f0ebbda2ace06dc12a4ad0", GitTreeState:"clean", BuildDate:"2021-03-10T15:29:59Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
> the server could not find the requested resource
> 

**Anything else we need to know?**:

I had same experience with KubeVirt v0.37.0 (virtctl) as well.

> Pod IP address space is 100.244.x.y

> kubectl logs virt-operator-58644dcfcc-gk9th -n kubevirt
> W0329 16:29:29.210015       1 client_config.go:614] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
> W0329 16:29:29.210325       1 client_config.go:614] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
> {"component":"virt-operator","level":"info","msg":"Error determining cluster type: Get https://10.96.0.1:443/api?timeout=32s: dial tcp 10.96.0.1:443: i/o timeout\n","pos":"application.go:221","timestamp":"2021-03-29T16:29:59.212292Z"}
> 

> kubectl logs virt-operator-58644dcfcc-7nn8n -n kubevirt
> W0329 16:27:16.398048       1 client_config.go:614] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
> W0329 16:27:16.398320       1 client_config.go:614] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
> {"component":"virt-operator","level":"info","msg":"Error determining cluster type: Get https://10.96.0.1:443/api?timeout=32s: dial tcp 10.96.0.1:443: i/o timeout\n","pos":"application.go:221","timestamp":"2021-03-29T16:27:46.400406Z"}
> 

**Environment**:
- KubeVirt version (use `virtctl version`): v0.39.0
- Kubernetes version (use `kubectl version`): Client Version: v1.18.17    Server Version: v1.18.17
- VM or VMI specifications: Centos 7 VMM
- Cloud provider or hardware configuration:  Baremetal
- OS (e.g. from /etc/os-release):  "CentOS Linux 7 (Core)"
- Kernel (e.g. `uname -a`):Linux kf-master 3.10.0-1160.21.1.el7.x86_64 #1 SMP
- Install tools:
- Others:

**Comment by phoracek** [comment]
@bhkamath it seems that the operator pod has issues accessing the API server. Would you please try accessing the API from a regular Pod. `curl --insecure https://10.96.0.1:443/api` may be enough.

**Comment by bhkamath** [comment]
Hi,

I am able to create container pods.  That means my worker nodes can interact with master node.

Yes, I observe failure when interacting with the API server inside the pod. This is not worker node specific.

What may be the cause for this issue?  Any tips to troubleshoot?

Thanks,

**Comment by bhkamath** [comment]
I am suspecting flannel configuration issue when non-default Pod CIDR is assigned.  Hence am closing this issue.
