### ISSUE TITLE
Failed to Pull Operator Image from Quay

### ISSUE THREAD

**Issue by jobbler** [kubevirt/kubevirt#5352]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
Trying to install kubevirt in minikube fails pulling operator from Quay. It appears the kubevirt-operator.yaml file has an incorrect sha in it.
https://github.com/kubevirt/kubevirt/releases/download/v0.39.1/kubevirt-operator.yaml
It lists a sha ending in 0c7f. In #virtualization, I was told it should end in 0e58.

**What you expected to happen**:
The deployment of kubevirt to be successful

**How to reproduce it (as minimally and precisely as possible)**:
Install minikube
Install kubevirt using either of the following methods:
  $ minikube addons enable kubevirt
Or
  $ kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/v0.39.1/kubevirt-operator.yaml

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- 
- Kubernetes version (use `kubectl version`):
-   $ kubectl version
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.2", GitCommit:"52c56ce7a8272c798dbc29846288d7cd9fbae032", GitTreeState:"archive", BuildDate:"2020-07-28T00:00:00Z", GoVersion:"go1.15rc1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.2", GitCommit:"faecb196815e248d3ecfb03c680a4507229c2a56", GitTreeState:"clean", BuildDate:"2021-01-13T13:20:00Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Fedora 33
- 
- Kernel (e.g. `uname -a`): Linux 5.11.10-200.fc33.x86_64 #1 SMP Thu Mar 25 16:51:31 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- 
- Install tools: minikube

- Others:
$ kubectl -n kubevirt describe pod/virt-operator-6d5988c4bf-9b4gx
Name:                 virt-operator-6d5988c4bf-9b4gx
Namespace:            kubevirt
Priority:             1000000000
Priority Class Name:  kubevirt-cluster-critical
Node:                 minikube/192.168.39.80
Start Time:           Tue, 30 Mar 2021 14:35:07 -0500
Labels:               kubevirt.io=virt-operator
                      pod-template-hash=6d5988c4bf
                      prometheus.kubevirt.io=
Annotations:          scheduler.alpha.kubernetes.io/critical-pod: 
Status:               Pending
IP:                   172.17.0.7
IPs:
  IP:           172.17.0.7
Controlled By:  ReplicaSet/virt-operator-6d5988c4bf
Containers:
  virt-operator:
    Container ID:  
    Image:         quay.io/kubevirt/virt-operator@sha256:2429917d5fa837c5b3f7a8ebcc4df6f9574d3bbab8f9d47c45d1a71d150e0c7f
    Image ID:      
    Ports:         8443/TCP, 8444/TCP
    Host Ports:    0/TCP, 0/TCP
    Command:
      virt-operator
      --port
      8443
      -v
      2
    State:          Waiting
      Reason:       ImagePullBackOff
    Ready:          False
    Restart Count:  0
    Readiness:      http-get https://:8443/metrics delay=5s timeout=10s period=10s #success=1 #failure=3
    Environment:
      OPERATOR_IMAGE:          quay.io/kubevirt/virt-operator@sha256:2429917d5fa837c5b3f7a8ebcc4df6f9574d3bbab8f9d47c45d1a71d150e0c7f
      WATCH_NAMESPACE:          (v1:metadata.annotations['olm.targetNamespaces'])
      KUBEVIRT_VERSION:        v0.39.1
      VIRT_API_SHASUM:         sha256:23814ce5ce542013bb3de7459a4e1b5548742ab34ec8f084edd29fc3e4d11a29
      VIRT_CONTROLLER_SHASUM:  sha256:ff6ff916aee1bc7976d9598fcc1d955e139416d55ca87b03c58e52c0bf824495
      VIRT_HANDLER_SHASUM:     sha256:f11831f2cdfe8c5c5ac01b41a5e543ccfb2eaa562fce4eaf2db1d46075407400
      VIRT_LAUNCHER_SHASUM:    sha256:3f84d100e311f3321e39caaf15ab51295f4604d86b6da3870d2c1793e9dba910
    Mounts:
      /etc/virt-operator/certificates from kubevirt-operator-certs (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kubevirt-operator-token-fr4ns (ro)
Conditions:
  Type              Status
  Initialized       True 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kubevirt-operator-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubevirt-operator-certs
    Optional:    true
  kubevirt-operator-token-fr4ns:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubevirt-operator-token-fr4ns
    Optional:    false
QoS Class:       BestEffort
Node-Selectors:  <none>
Tolerations:     CriticalAddonsOnly
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type     Reason     Age                    From               Message
  ----     ------     ----                   ----               -------
  Normal   Scheduled  <unknown>                                 Successfully assigned kubevirt/virt-operator-6d5988c4bf-9b4gx to minikube
  Normal   Pulling    4m57s (x4 over 6m36s)  kubelet, minikube  Pulling image "quay.io/kubevirt/virt-operator@sha256:2429917d5fa837c5b3f7a8ebcc4df6f9574d3bbab8f9d47c45d1a71d150e0c7f"
  Warning  Failed     4m56s (x4 over 6m35s)  kubelet, minikube  Failed to pull image "quay.io/kubevirt/virt-operator@sha256:2429917d5fa837c5b3f7a8ebcc4df6f9574d3bbab8f9d47c45d1a71d150e0c7f": rpc error: code = Unknown desc = Error response from daemon: manifest for quay.io/kubevirt/virt-operator@sha256:2429917d5fa837c5b3f7a8ebcc4df6f9574d3bbab8f9d47c45d1a71d150e0c7f not found: manifest unknown: manifest unknown
  Warning  Failed     4m56s (x4 over 6m35s)  kubelet, minikube  Error: ErrImagePull
  Normal   BackOff    4m41s (x6 over 6m34s)  kubelet, minikube  Back-off pulling image "quay.io/kubevirt/virt-operator@sha256:2429917d5fa837c5b3f7a8ebcc4df6f9574d3bbab8f9d47c45d1a71d150e0c7f"
  Warning  Failed     93s (x20 over 6m34s)   kubelet, minikube  Error: ImagePullBackOff

**Comment by vasiliy-ul** [comment]
Some time back I faced a similar issue with incorrect SHA digest in the manifests. Though I was making a local build with `make && make push` as suggested in https://github.com/kubevirt/kubevirt/blob/master/docs/getting-started.md.

It turned out that even though the default make target included the building of the `manifests`:
https://github.com/kubevirt/kubevirt/blob/4cab16cfd6f31555fd96077e81fa298bda621bec/Makefile#L8-L10

the correct SHA digest was generated during `bazel-push-images` (or just `push`). Therefore doing `make && make push` was leading to wrong sums in the manifests. I thought it was expacted behaviour and suggested a change for the getting started guide to make it more clear: https://github.com/kubevirt/kubevirt/pull/4954 

Now looking at the `automation/release.sh` script I see that it builds everything in the same way with making `push` **after** the `manifests`:
https://github.com/kubevirt/kubevirt/blob/4cab16cfd6f31555fd96077e81fa298bda621bec/automation/release.sh#L31-L43

Might it be the same case now with the released version?
