### ISSUE TITLE
virt-operator in crashback loop in version v0.39.1

### ISSUE THREAD

**Issue by ikandars** [kubevirt/kubevirt#5371]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Try to install version v0.39.1  but got ImagePullBackOff in pod/virt-operator-6d5988c4bf-pmmcs

**What you expected to happen**:

```
kubevirt      pod/virt-operator-6d5988c4bf-pmmcs             1/1     Running   0          18m
```

**How to reproduce it (as minimally and precisely as possible)**:

```
export RELEASE=v0.39.1
kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/${RELEASE}/kubevirt-operator.yaml

kubectl get all -n kubevirt
```

**Anything else we need to know?**:

If we look at `https://github.com/kubevirt/kubevirt/releases/download/v0.39.1/kubevirt-operator.yaml` file, there is some part stated:

```
quay.io/kubevirt/virt-operator@sha256:2429917d5fa837c5b3f7a8ebcc4df6f9574d3bbab8f9d47c45d1a71d150e0c7f
// and
- name: VIRT_API_SHASUM
  value: sha256:23814ce5ce542013bb3de7459a4e1b5548742ab34ec8f084edd29fc3e4d11a29
- name: VIRT_CONTROLLER_SHASUM
   value: sha256:ff6ff916aee1bc7976d9598fcc1d955e139416d55ca87b03c58e52c0bf824495
```

If crosscheck to https://quay.io/repository/kubevirt/virt-operator?tag=latest&tab=tags, the sha256 value for vesion `v0.39.1` should:
```
quay.io/kubevirt/virt-operator@sha256:c0347d5d8d4c6a498fdb45ef3516ea28355e9981419a2d183932577542f70e58
// and
- name: VIRT_API_SHASUM
  value: sha256:dd94c919d04eb15ebc280d40098e3e724760c3ee92fbf539be0f50d82c0c4c04
- name: VIRT_CONTROLLER_SHASUM
   value: sha256:2f4b8ee5f3828810790dc74b39305fe39abd8f964c17a2b64a4ee74e56bdccf2
```

**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.38.1", GitCommit:"8c3ba52f8ce7cbb55c29919e9c263617716aa054", GitTreeState:"clean", BuildDate:"2021-02-08T20:04:23Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
the server is currently unable to handle the reques
```
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.4", GitCommit:"e87da0bd6e03ec3fea7933c4b5263d151aafd07c", GitTreeState:"clean", BuildDate:"2021-02-18T16:12:00Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.5", GitCommit:"6b1d87acf3c8253c123756b9e61dac642678305f", GitTreeState:"clean", BuildDate:"2021-03-18T01:02:01Z", GoVersion:"go1.15.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by davidvossel** [comment]
/cc @dhiller 

this is a known issue. We switched over to new release automation and something incorrectly occurred when publishing release assets

https://groups.google.com/g/kubevirt-dev/c/1yoV88b3HPk

I'm going to remove 0.39.1 from our releases for now so people stop attempting to use this until it is resolved. Due to holidays and PTO, it might be next week before we can address this properly.

**Comment by davidvossel** [comment]
I've deleted the v0.39.1 release to avoid further confusion here until we can get the issue sorted out

**Comment by dhiller** [comment]
@davidvossel we could cherry pick the changes from moving towards prow and rerun the release from there. WDYT?

**Comment by davidvossel** [comment]
I was able to get a v0.39.1  release out with travis. it's unreliable, but it managed to work this time.

https://github.com/kubevirt/kubevirt/releases/tag/v0.39.1
