### ISSUE TITLE
Support choosing VM migration target nodes

### ISSUE THREAD

**Issue by gitlawr** [kubevirt/kubevirt#5374]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:
Currently, we cannot specify a set of nodes as the migration target.

**What you expected to happen**:
It would be nice if we can set node selectors in virtualMachineInstanceMigration specification.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.39.1

**Comment by teo-tsou** [comment]
As I am working on project that requires the preselected target nodes , I am very interested to this feature.

**Comment by teo-tsou** [comment]
There's something from Rancher Harvester Project that might do the work. Kubevirt could merge it.
https://github.com/rancher/harvester/commit/0f960117c906262d534eb5b4c412bf61c5ca21a4
