### ISSUE TITLE
VMI Phase remains same when paused / unpaused

### ISSUE THREAD

**Issue by ansijain** [kubevirt/kubevirt#5393]
VMI Phase is **Running** even if it is paused the VMI 
How will the user know VMI is paused?
We can change the phase to "Paused" when VMI is paused

~$ kubectl get vmi
NAME     AGE     PHASE     IP            NODENAME
testvm   9m13s   Running   172.17.0.16   minikube
~$ virtctl pause vm testvm
VMI testvm was scheduled to pause
~$ kubectl get vmi
NAME     AGE     PHASE     IP            NODENAME
testvm   9m38s   Running   172.17.0.16   minikube

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

/kind question

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by phoracek** [comment]
I believe this was answered on Slack via https://kubernetes.slack.com/archives/C0163DT0R8X/p1618972278155800.

@zcahana (hope you don't mind me quoting you):  there's no VMI phase corresponding with a paused state, see here:
https://github.com/kubevirt/client-go/blob/ba6a204f03fea5d1b1c41eca285e3ac78f558eae/api/v1/types.go#L525However, there is a Paused VMI condition just for that, here:
https://github.com/kubevirt/client-go/blob/ba6a204f03fea5d1b1c41eca285e3ac78f558eae/api/v1/types.go#L328So you can basically do something like kubectl wait vmi <my-vmi> --for=condition=Paused

I'm closing this. Feel free to reopen if it remains unanswered.
