### ISSUE TITLE
Add unknown state to VMs

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#543]
The VM controller needs to check, if e.g. the synchronized condition on the VM is not updated every X seconds, we need to move the VM to state "UNKNOWN", since we don't know what is going on with it.

The situation is easy to reproduce: Schedule a VM on e.g. node0 and kill node0 after the VM entered the Running state. Until the VM comes up again, the VM will be shown as Running.

**Comment by rmohr** [comment]
@mz-pdm that might be an issue which interests you ...

**Comment by mz-pdm** [comment]
@rmohr, definitely, thank you, I'll look at it.

**Comment by mz-pdm** [comment]
@rmohr, could you please clarify what you mean with "synchronized condition"? Do you mean some particular entity already present in KubeVirt or is it just a general term for something to be introduced for the purpose?

**Comment by rmohr** [comment]
@mz-pdm here you see a VM which can't start because the iscsi connection string is wrong. The error is shown in the synchronized condition (type: Synchronized). And the status of the condition is false.

```yaml
apiVersion: v1
items:
- apiVersion: kubevirt.io/v1alpha1
  kind: VirtualMachine
  [...]
  status:
    conditions:
    - lastProbeTime: null
      lastTransitionTime: 2017-11-30T11:27:51Z
      message: |-
        virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2017-11-30T11:27:51.427771Z qemu-system-x86_64: -chardev pty,id=charserial0: char device redirected to /dev/pts/0 (label charserial0)
        2017-11-30T11:27:51.433617Z qemu-system-x86_64: -drive file=iscsi://10.104.6.135:3260/iqn.2017-01.io.kubevirt%3Asn.42/,format=raw,if=none,id=drive-virtio-disk0,cache=none: Failed to parse URL : iscsi://10.104.6.135:3260/iqn.2017-01.io.kubevirt%3Asn.42/')
      reason: Synchronizing with the Domain failed.
      status: "False"
      type: Synchronized
    graphics: []
    nodeName: node0
    phase: Scheduled
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

 Right now we remove the condition, if the error goes away, but we can also keep it, just update the lastProbeTime periodically and toggle it to true if everything is fine from the virt-handler perspective. If lastProbeTime does not get updated for some time, we can assume that something is wrong and let virt-controller change the state of the VM to unknown. If virt-handler then finally recovers, it can change it back to reflect the node state.

**Comment by mz-pdm** [comment]
@rmohr I see, thank you for clarification. OK, let's make Synchronized condition to indicate synchronization status permanently including the last update time. A couple of additional questions:

- Do we want to update the time at each occasion, i.e. every VirtualMachineController.updateVMStatus call, or should we be careful not to disrupt scalability with too many non-critical updates? Is it an issue or non-issue (e.g. should rate limiters take the care)?
- Would it be useful to store the last known state somewhere when switching to Unknown state?

**Comment by fabiand** [comment]
@rmohr didn't you address this in your recent handler changes?

**Comment by rmohr** [comment]
Not entirely. My changes were only covering the internal bits of that. The controllers are now able to detect this and can react under certain conditions, but it is still not easy to see for users.

Right now the node controller detects and handles such situations. What is missing there, is that this controller also modifies the vm itself to inform the user about the issue on the vm itself. So a small but very relevant piece is still missing.

**Comment by fabiand** [comment]
Ack, thanks!
