### ISSUE TITLE
Datavolumes hotplugged to VM do not updated their status to "Running"

### ISSUE THREAD

**Issue by birdiesanders** [kubevirt/kubevirt#5437]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
When passing a datavolume, we have noticed that the attachment occurs and works properly, but has not been updating the datavolume Running status to true. 

**What you expected to happen**:
Status Running == true, Ready == false
**How to reproduce it (as minimally and precisely as possible)**:
Hotplug a datavolume to a vm. 

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): Built from master
- Kubernetes version (use `kubectl version`): 1.21
- VM or VMI specifications: Ubuntu 20.04
- Cloud provider or hardware configuration: Baremetal OCP
- OS (e.g. from /etc/os-release):Ubuntu 20.04
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by awels** [comment]
Running = true means the DV pod that is populating the pod is running. Once the phase is succeeded, running will always be false because the pod completed and is stopped and removed.

**Comment by phoracek** [comment]
@awels could we consider this "not a bug" then?

**Comment by awels** [comment]
Right the DV conditions stop being useful after the DV completes. So this is normal behavior. So not a bug.

**Comment by phoracek** [comment]
Thanks for clarification!

**Comment by birdiesanders** [comment]
Gotcha! Thanks everyone!
