### ISSUE TITLE
virt-handler in crashback loop after upgrade also with v0.40.0-rc.0

### ISSUE THREAD

**Issue by tiraboschi** [kubevirt/kubevirt#5438]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Trying to consume v0.40.0-rc.0
we cannot pass the CI upgrade lanes because on HCO repo because virt-handler is in crashback loop after the upgrade:
we cannot pass the CI upgrade lanes because on HCO repo because virt-handler is in crashback loop after the upgrade:

```
virt-handler-6rkkz                                    0/1     CrashLoopBackOff   6          12m
virt-handler-k8vd9                                    0/1     CrashLoopBackOff   6          14m
virt-handler-tjnwh                                    1/1     Running            0          19m
```
and in virt-handler logs:
```
{"component":"virt-handler","level":"error","msg":"node-labeller could not load cpu info: open /var/lib/kubevirt-node-labeller/cpu_map: no such file or directory","pos":"node_labeller.go:74","timestamp":"2021-03-31T15:31:33.587454Z"}
panic: open /var/lib/kubevirt-node-labeller/cpu_map: no such file or directory

goroutine 1 [running]:
main.(*virtHandlerApp).Run(0xc000001b00)
	cmd/virt-handler/virt-handler.go:356 +0x2968
main.main()
	cmd/virt-handler/virt-handler.go:534 +0x6e
```

**What you expected to happen**:
virt-handler is still working after an upgrade

**How to reproduce it (as minimally and precisely as possible)**:
try to upgrade from 0.39.0 to 0.40.0-rc.0

**Anything else we need to know?**:
is exactly as in https://github.com/kubevirt/kubevirt/issues/5364
we fear that kubevirt/kubevirt#5368 is not part of v0.40.0-rc.0

**Environment**:
- KubeVirt version (use `virtctl version`): v0.40.0-rc.0
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by phoracek** [comment]
@tiraboschi this should be resolved in the next rc via https://github.com/kubevirt/kubevirt/pull/5439.
