### ISSUE TITLE
kubevirt

### ISSUE THREAD

**Issue by garimaanurag** [kubevirt/kubevirt#5466]
Events:
  Type     Reason            Age   From                       Message
  ----     ------            ----  ----                       -------
  Normal   SuccessfulCreate  17s   virtualmachine-controller  Created virtual machine pod virt-launcher-testvm-dckxk
  Warning  SyncFailed        9s    virt-handler               failed to configure vmi network: Critical network error: could not retrieve pid 11642 selinux label: operation not supported
  Warning  Stopped           9s    virt-handler               The VirtualMachineInstance crashed.
  Normal   SuccessfulDelete  9s    virtualmachine-controller  Deleted virtual machine pod virt-launcher-testvm-dckxk

**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by garimaanurag** [comment]
Events:
  Type     Reason            Age   From                       Message
  ----     ------            ----  ----                       -------
  Normal   SuccessfulCreate  17s   virtualmachine-controller  Created virtual machine pod virt-launcher-testvm-dckxk
  Warning  SyncFailed        9s    virt-handler               failed to configure vmi network: Critical network error: could not retrieve pid 11642 selinux label: operation not supported
  Warning  Stopped           9s    virt-handler               The VirtualMachineInstance crashed.
  Normal   SuccessfulDelete  9s    virtualmachine-controller  Deleted virtual machine pod virt-launcher-testvm-dckxk

**Comment by vasiliy-ul** [comment]
This is a known issue and it has been fixed. Unfortunately there is still no release available which includes the fix. You may switch to an older version e.g. 0.38.x. Or probably wait for the next release (hopefully will be available early the next week).

**Comment by phoracek** [comment]
@garimaanurag could you try again with the recent release 0.40?

**Comment by fabiand** [comment]
There should be a release by now with a fix.
