### ISSUE TITLE
According to schema VM.OS.BootOrder is not allowed to be empty, however it is empty

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt/kubevirt#547]
So far I encouraged issue with following objects
* [x] VirtualMachine.OS.BootOrder (#567)
* [x] VirtualMachineReplicaSet.VMReplicaSetStatus.Conditions (#579)
* [ ] APIGroup.ServerAddressByClientCIDRs

According to schema VM.OS.BootOrder is not allowed to be empty
https://github.com/kubevirt/kubevirt/blob/cb49b6784d8593f4417671c6994ac4f20b7d3b4b/pkg/api/v1/schema.go#L210-L215

When listing VMs I can see:
```json
          "os": {
            "type": {
              "os": "hvm"
            },
            "bootOrder": null
          },
```
You can see full output here: [vms-full.json.txt](https://github.com/kubevirt/kubevirt/files/1446963/vms-full.json.txt)

It doesn't cause any issue in KubeVirt itself (AFAIK), but it is failing for me when I am playing with generated PySDK, which does validation of obtained structures.

Following output is error which I am getting from SDK.
```
send: b'GET /apis/kubevirt.io/v1alpha1/namespaces/default/virtualmachines HTTP/1.1\r\nHost: 192.168.200.2:8184\r\nAccept-Encoding: identity\r\nUser-Agent: Swagger-Codegen/1.0.0/python\r\nAccept: application/json\r\nContent-Type: application/json\r\n\r\n'
reply: 'HTTP/1.1 200 OK\r\n'
header: Content-Type header: Date header: Content-Length ---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
.... TRIMMED .....
~/work/kubevirt-org/kubevirt-tests/.tox/python/lib/python3.5/site-packages/kubevirt/models/v1_os.py in boot_order(self, boot_order)
    128         """
    129         if boot_order is None:
--> 130             raise ValueError("Invalid value for `boot_order`, must not be `None`")
    131 
    132         self._boot_order = boot_order

ValueError: Invalid value for `boot_order`, must not be `None`
```
Here you can find full trace-back: [pysdk-failure.txt](https://github.com/kubevirt/kubevirt/files/1446987/pysdk-failure.txt)

Can anybody tell me what is proper solution?
* allow to be empty
* fill with defaults when it is empty

**Comment by lukas-bednar** [comment]
I am getting same issue for different attribute when obtaining APIGroup.
`GET /apis/kubevirt.io`
```
~/work/kubevirt-org/kubevirt-tests/.tox/python/lib/python3.5/site-packages/kubevirt/models/v1_api_group.py in server_address_by_client_cid_rs(self, server_address_by_client_cid_rs)
    186         """
    187         if server_address_by_client_cid_rs is None:
--> 188             raise ValueError("Invalid value for `server_address_by_client_cid_rs`, must not be `None`")
    189 
    190         self._server_address_by_client_cid_rs = server_address_by_client_cid_rs

ValueError: Invalid value for `server_address_by_client_cid_rs`, must not be `None`
```
It is defined by K8S as
```go
type APIGroup struct {
	TypeMeta `json:",inline"`
	// name is the name of the group.
	Name string `json:"name" protobuf:"bytes,1,opt,name=name"`
	// versions are the versions supported in this group.
	Versions []GroupVersionForDiscovery `json:"versions" protobuf:"bytes,2,rep,name=versions"`
	// preferredVersion is the version preferred by the API server, which
	// probably is the storage version.
	// +optional
	PreferredVersion GroupVersionForDiscovery `json:"preferredVersion,omitempty" protobuf:"bytes,3,opt,name=preferredVersion"`
	// a map of client CIDR to server address that is serving this group.
	// This is to help clients reach servers in the most network-efficient way possible.
	// Clients can use the appropriate server address as per the CIDR that they match.
	// In case of multiple matches, clients should use the longest matching CIDR.
	// The server returns only those CIDRs that it thinks that the client can match.
	// For example: the master will return an internal IP CIDR only, if the client reaches the server using an internal IP.
	// Server looks at X-Forwarded-For header or X-Real-Ip header or request.RemoteAddr (in that order) to get the client IP.
	ServerAddressByClientCIDRs []ServerAddressByClientCIDR `json:"serverAddressByClientCIDRs" protobuf:"bytes,4,rep,name=serverAddressByClientCIDRs"`
}
```

**Comment by rmohr** [comment]
We can also do code generation based on a `+optional` in the comments like kubernetes does, or we can use the ````optional="true"```` go tag on every struct field. 

For default values, I don't think that go-restful has support for that right now. We can either do code generation here, or maybe try to extend `SwaggerDoc()` function override provided by go-restful. We use that override right now to add our description based on go comments to the spec.

**Comment by lukas-bednar** [comment]
@rmohr I am sorry, but I don't know what to change.

I understand that these ```
Field int `json:"myName,omitempty"`
``` are used by `encoding/json` module.

What tool is supposed to read these `// +optional` comments?
And how it will help me with deserialization problem of some objects ?

**Comment by rmohr** [comment]
@lukas-bednar there is a good chance that with the 0.2 release the `ServerAddressByClientCIDRs` problem does not exist anymore.

**Comment by lukas-bednar** [comment]
@rmohr I gave a try, and I was able to reproduce same issue with current master.
```
ValueError: Invalid value for `server_address_by_client_cid_rs`, must not be `None`
```

**Comment by rmohr** [comment]
@lukas-bednar could it be that the issue is related to the python client? See

 * https://github.com/kubernetes-client/python/issues/418
 * https://github.com/kubernetes-client/python/issues/394

Either way it does not seem to be a KubeVirt bug. Maybe you can monkey patch it like suggested in one of the issues above?

**Comment by lukas-bednar** [comment]
@rmohr I tried that workaround and it worked,
```
{'api_version': 'v1',
 'kind': 'APIGroup',
 'name': 'kubevirt.io',
 'preferred_version': {'group_version': 'kubevirt.io/v1alpha1',
                       'version': 'v1alpha1'},
 'server_address_by_client_cid_rs': None,
 'versions': [{'group_version': 'kubevirt.io/v1alpha1',
               'version': 'v1alpha1'}]}
```
so your suggestion is to deal with it in the same way as they did in k8s client?

**Comment by rmohr** [comment]
At least I don't see a way on how code changes in this repo could fix that issue.

**Comment by lukas-bednar** [comment]
@rmohr OK, I will close this issue then.
Anyway thank you for all your help regarding to this issue!
