### ISSUE TITLE
Unable to upload image with virtctl

### ISSUE THREAD

**Issue by dsmackie** [kubevirt/kubevirt#5473]
/kind bug

**What happened**:

When attempting to upload an image using `virtctl` the operation times out.

```
user@host:~$ virtctl image-upload pvc win10-pvc --image-path=/home/user/images/Win10_20H2_v2_English_x64.iso --insecure --size=7Gi --uploadproxy-url=https://10.96.201.219:443
PersistentVolumeClaim default/win10-pvc created
Waiting for PVC win10-pvc upload pod to be ready...
Pod now ready
Uploading data to https://10.96.201.219:443

 0 B / 5.79 GiB [-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------]   0.00% 2m11s

Post https://10.96.201.219:443/v1alpha1/upload: dial tcp 10.96.201.219:443: connect: connection timed out
```

Output from the `cdi-upload-win10-pvc` is as follows;

```
I0418 12:19:03.706193       1 uploadserver.go:70] Upload destination: /data/disk.img
I0418 12:19:03.706277       1 uploadserver.go:72] Running server on 0.0.0.0:8443
2021/04/18 12:19:05 http: TLS handshake error from 127.0.0.1:56130: remote error: tls: bad certificate
2021/04/18 12:19:10 http: TLS handshake error from 127.0.0.1:56192: remote error: tls: bad certificate
2021/04/18 12:19:15 http: TLS handshake error from 127.0.0.1:56240: remote error: tls: bad certificate
2021/04/18 12:19:20 http: TLS handshake error from 127.0.0.1:56300: remote error: tls: bad certificate
2021/04/18 12:19:25 http: TLS handshake error from 127.0.0.1:56428: remote error: tls: bad certificate
2021/04/18 12:19:30 http: TLS handshake error from 127.0.0.1:56492: remote error: tls: bad certificate
2021/04/18 12:19:35 http: TLS handshake error from 127.0.0.1:56540: remote error: tls: bad certificate
```

Services listing;
```
user@host:~$ kubectl get services -n cdi
NAME                     TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)   AGE
cdi-api                  ClusterIP   10.111.199.108   <none>        443/TCP   83m
cdi-prometheus-metrics   ClusterIP   10.99.38.215     <none>        443/TCP   83m
cdi-uploadproxy          ClusterIP   10.96.201.219    <none>        443/TCP   83m
```

**What you expected to happen**:

Expected the image to upload and be processed.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.39.0
- Kubernetes version (use `kubectl version`): v1.20.2
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: HomeLab (4CPU/8Gb)
- OS (e.g. from /etc/os-release): Ubuntu 20.04.2 LTS
- Kernel (e.g. `uname -a`): Linux host 5.4.0-72-generic #80-Ubuntu SMP Mon Apr 12 17:35:00 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: N/A
- Others: N/A

**Comment by wuestkamp** [comment]
Same issue, did you solve it?

**Comment by theKloudcoder** [comment]
I also hit the same bug, it was working earlier.

**Comment by wuestkamp** [comment]
created issue over at CDI:
https://github.com/kubevirt/containerized-data-importer/issues/1843

**Comment by Jockey721** [comment]
Same issue, did you solve it???

**Comment by tclxzhengyang-li** [comment]
0.54.3 aslo have this problem, how to slove it?
<img width="1234" alt="image" src="https://github.com/kubevirt/kubevirt/assets/134913390/0bdd3be7-61cd-4672-9b1c-296f655324ab">

**Comment by Ranjeet-Nvidia** [comment]
I am also facing the same problem.
While attempting to upload an image using virtctl the operation times out.

```
virtctl image-upload pvc win11cd-pvc --size 10Gi --image-path=Win11_22H2_English_x64v2.iso --insecure --storage-class=<XXXXX> --uploadproxy-url=<XXXXX> --force-bind
Using existing PVC default/win11cd-pvc
Uploading data to XXXXX

 0 B / 5.44 GiB [------------------------------------------------------------------------------------------------------------------------------]   0.00% 2m13s
```

**Comment by prabhulc** [comment]
Same error here, any update on this ?

2024/03/28 05:40:13 http: TLS handshake error from 10.2.16.103:35044: EOF
2024/03/28 05:42:13 http: TLS handshake error from 10.2.7.126:51700: EOF
2024/03/28 05:44:13 http: TLS handshake error from 10.2.7.126:37906: EOF
2024/03/28 05:45:13 http: TLS handshake error from 10.2.7.126:51904: EOF

**Comment by victortoso** [comment]
Hm, https://github.com/kubevirt/containerized-data-importer/issues/1843 seems to be resolved/clarified.
How easy is to reproduce?

/reopen
/remove-lifecycle rotten
