### ISSUE TITLE
Secondary ip on dual stack service is not working (k8s 1.20)

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#5477]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
Communication to the vm/pod via the secondary address of a dual stack service is not working.

note: I guess the root cause for the non working communication is the fact the endpoint doesn't contain the secondary address (`endpoints.Subsets[0].Addresses`). It contains only the address belongs to the primary ip family of the service.

**What you expected to happen**:
It should work.

**How to reproduce it (as minimally and precisely as possible)**:
1. Start a dual stack cluster
2. Create a vm
3. Expose a service on the vm - `cluster-up/virtctl.sh expose vmi vmi-masquerade2 --name vmi-masquerade2-service-dual --ip-family IPv4,IPv6`.
Note: `--ip-family IPv6,IPv4`, `--ip-family-policy PreferDualStack`, `--ip-family-policy RequireDualStack`have the same bug.
4. Try to connect the vm via the secondary address of the service => it fails. 
[
k8s documentation](https://v1-20.docs.kubernetes.io/docs/concepts/services-networking/dual-stack/) of the dual stack service.

**Anything else we need to know?**:
It is a k8s (1.20) bug. But since dual stack service is in alpha feature state, a kubevirt issue is opened to track it.

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
1.20
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by maiqueb** [comment]
IIUC, there are a bunch of tests currently skipped pointing at this issue.

We should either re-open the issue, or enable the tests back. Does the issue still persist @AlonaKaplan / @phoracek ?

**Comment by EdDev** [comment]
@AlonaKaplan , can this one be closed?

**Comment by AlonaKaplan** [comment]
> @AlonaKaplan , can this one be closed?

yes, it was fixed by PR https://github.com/kubevirt/kubevirt/pull/8597
