### ISSUE TITLE
canout get VMI ipaddress in status.interfaces

### ISSUE THREAD

**Issue by mzzgaopeng** [kubevirt/kubevirt#5487]
When we use the multus network to use the bridge network solution, when creating vms in batches, we will find that the status.interface on some vmi does not have ipaddresses configuration.
![image](https://user-images.githubusercontent.com/22125180/115374138-225a2e80-a1ff-11eb-8bc0-e24c6ab04711.png)

But when I looked at the code, I found that the way to obtain the IP address of the VMI is use this command：
virsh qemu-agent-command 1 --pretty '{"execute":"guest-network-get-interfaces"}'

When my virtual machine is powered on for a long time, can't I get the ip address here?

The parameter time in the following 4 methods is nanoseconds. Is the qemu-agent commond time too short causing this phenomenon

```
	qemuAgentSysInterval := pflag.Duration("qemu-agent-sys-interval", 120, "Interval in seconds between consecutive qemu agent calls for sys commands")
	qemuAgentFileInterval := pflag.Duration("qemu-agent-file-interval", 300, "Interval in seconds between consecutive qemu agent calls for file command")
	qemuAgentUserInterval := pflag.Duration("qemu-agent-user-interval", 10, "Interval in seconds between consecutive qemu agent calls for user command")
	qemuAgentVersionInterval := pflag.Duration("qemu-agent-version-interval", 300, "Interval in seconds between consecutive qemu agent calls for version command")
```

**Comment by phoracek** [comment]
To expose status of secondary network interfaces, you have to have QEMU guest agent installed and running on your guest. Is that the case for you?

**Comment by mzzgaopeng** [comment]
> To expose status of secondary network interfaces, you have to have QEMU guest agent installed and running on your guest. Is that the case for you?


I have installed the agent client in the vm.
 The scenarios for this phenomenon are as follows: 
1. when 3-5 vms are created at the same time
2.  when a single virtual machine is created occasionally

**Comment by mzzgaopeng** [comment]
Is there any number of retries and time intervals when getting the guest-interface-config of vm in the code? I checked the code here and found that the retries are retried in nanoseconds. If the virtual machine is heavier, the boot time is slower , Is it impossible to get the interface information of vm at this time?

**Comment by phoracek** [comment]
The reporting should happen periodically and so even if your VM takes a while to start, the status should eventually pop-up.

You mention two specific scenarios. Does it mean that in other cases the status of secondary interfaces appears?

**Comment by mzzgaopeng** [comment]
> The reporting should happen periodically and so even if your VM takes a while to start, the status should eventually pop-up.
> 
> You mention two specific scenarios. Does it mean that in other cases the status of secondary interfaces appears?

I think there are two situations when updating the vmi resource object:
1. virt-handler will periodically obtain the IP address through the getPodInterfacefromFileCache method to update the status.interface in the vmi resource object.
2. When the vm restarts, virt-launcher uses qemu-agent to obtain the qemu-interface method to update the vmi resource object at startup.


Is it because of the above two situations that an error occurred, causing my IP address to not appear in vmi.status.interface

**Comment by phoracek** [comment]
Would you please help providing a reproducer? Is it that when you have a VM connected to a multus network, after reboot the IP does not appear (while it was reported before the reboot)?

**Comment by mzzgaopeng** [comment]
> Would you please help providing a reproducer? Is it that when you have a VM connected to a multus network, after reboot the IP does not appear (while it was reported before the reboot)?


What information do you need, such as the yaml file of the VM resource object?

**Comment by phoracek** [comment]
Ideally bunch of `kubectl` commands that when copy-pasted into terminal, reproduce the problem. It should describe steps one needs to take to reproduce it and have the VM manifest too.

**Comment by mzzgaopeng** [comment]
> Ideally bunch of `kubectl` commands that when copy-pasted into terminal, reproduce the problem. It should describe steps one needs to take to reproduce it and have the VM manifest too.

I seem to find the point of the problem because the guest-network-get-interfaces is not obtained when the virtual machine is started.

Then I did debug as follows to print this command print with
			log.Log.Infof("interface is : %s", interfaces)

```
func executeAgentCommands(commands []AgentCommand, con cli.Connection, agentStore *AsyncAgentStore, domainName string) {
.....
		switch command {
		case GET_INTERFACES:
			interfaces, err := parseInterfaces(cmdResult)
			if err != nil {
				log.Log.Errorf("Cannot parse guest agent interface %s", err.Error())
			}
			agentStore.Store(GET_INTERFACES, interfaces)
			log.Log.Infof("interface is : %s", interfaces)
```

Then come up with the following screenshot
![image](https://user-images.githubusercontent.com/22125180/116224238-00265a80-a783-11eb-8392-9aa54167270d.png)

I found that the guest-network-get-interfaces command is executed twice with an interval of 10S.

The following problems may occur:
When the vm startup process is slow, the ip address of the vm cannot be obtained


And I found the following problem in the following code
```
func (p *PollerWorker) Poll(execAgentCommands agentCommandsExecutor, closeChan chan struct{}) {
	log.Log.Infof("Polling command: %v", p.AgentCommands)

	// do the first round to fill the cache immediately
	execAgentCommands(p.AgentCommands)

	pollMaxInterval := p.CallTick * time.Second
	pollInterval := pollMaxInterval

	if pollInitialInterval < pollMaxInterval {
		pollInterval = pollInitialInterval
	}
	ticker := time.NewTicker(pollInterval)
```

The default value of pollMaxInterval is 120S, but after the above logic operation, NewTicker is set to a 10-second interval，so the above problem may occur

**Comment by oshoval** [comment]
Can you please try with both those fixes:

https://github.com/kubevirt/kubevirt/pull/5381
https://github.com/kubevirt/kubevirt/pull/5428

The first fix so the exponential backoff will be indeed bound by 120 and not by 120 * very large number,
resulting in updates stopping (see please BZ in the ticket)

The 2nd fix a periodic resync each 300 seconds that cause the report to be gone

**Comment by oshoval** [comment]
Note please that #5428 was reverted and https://github.com/kubevirt/kubevirt/pull/5560 was merged instead
