### ISSUE TITLE
can IPv4 and IPv6 dual-stack support on bridge mode ?

### ISSUE THREAD

**Issue by zhhray** [kubevirt/kubevirt#5499]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind enhancement

**What happened**:
I want to know why IPv4 and IPv6 dual-stack why not support on bridge mode.
Cluster info:
  kubernetes cluaster (v1.19.7)
  kubevirt (v0.36.0)
  vm os version (centos 7.9)
I tried `masquerade` mode double stack on this environment.
But if I switch the network mode to `Bridge` and find that virt-launcher pod only passes IPv4 addresses to VM, but IPv6 addresses do not, I wonder if it is easy to see IPv6 transfers? Are there any current problems?
**What you expected to happen**:
In `Bridge` mode, virt-launcher pod can pass IPv6 to the virtual machine as if it were IPv4
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
There are ipv4 and ipv6 addresses in podIPs
```yaml
 phase: Running
  podIP: 10.100.0.74
  podIPs:
    - ip: 10.100.0.74
    - ip: fd00:10:100::3a
``` 
In `Bridge`mode, the virt-launcher pod interface info is :
```bash
3: tap0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc pfifo_fast master k6t-eth0 state UP group default qlen 1000
    link/ether ca:1b:29:ad:0e:a8 brd ff:ff:ff:ff:ff:ff
    inet6 fe80::c81b:29ff:fead:ea8/64 scope link 
       valid_lft forever preferred_lft forever
489: eth0@if490: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc noqueue master k6t-eth0 state UP group default 
    link/ether 02:00:00:f5:45:b0 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet6 fe80::ff:fef5:45b0/64 scope link 
       valid_lft forever preferred_lft forever
```
the interface defined in vm xml of virt-launcher pod is :
```xml
   <interface type='ethernet'>
      <mac address='00:00:00:0f:87:3e'/>
      <target dev='tap0' managed='no'/>
      <model type='virtio'/>
      <mtu size='1400'/>
      <alias name='ua-default'/>
      <rom enabled='no'/>
      <address type='pci' domain='0x0000' bus='0x01' slot='0x00' function='0x0'/>
    </interface>
```
the ip info of vm is:
```bash
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1400 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:00:00:0f:87:3e brd ff:ff:ff:ff:ff:ff
    inet 10.100.0.74/16 brd 10.100.255.255 scope global dynamic eth0
       valid_lft 86313192sec preferred_lft 86313192sec
    inet6 fe80::200:ff:fe0f:873e/64 scope link
       valid_lft forever preferred_lft forever
```

**Comment by phoracek** [comment]
With IPv4, we have our own DHCP server running in virt-launcher and offering the IP of the pod further to the VM. With IPv6, we don't have this DHCP server and due to the complexity of introducing one, we don't plan to do so today.

This should be doable with masquerade, following https://kubevirt.io/user-guide/virtual_machines/interfaces_and_networks/#masquerade-ipv4-and-ipv6-dual-stack-support. Does that resolve it for you?

**Comment by zhhray** [comment]
> With IPv4, we have our own DHCP server running in virt-launcher and offering the IP of the pod further to the VM. With IPv6, we don't have this DHCP server and due to the complexity of introducing one, we don't plan to do so today.
> 
> This should be doable with masquerade, following https://kubevirt.io/user-guide/virtual_machines/interfaces_and_networks/#masquerade-ipv4-and-ipv6-dual-stack-support. Does that resolve it for you?

Thanks for your answer.I still have two questions here:
1. In Masquerade mode, the IPv6 address needs to be configured by cloud-init or the user manually configures it in the virtual machine. It cannot be automatically configured because of the IPV6 DHCP Server as you mentioned above?
2. Is it possible to improve on this problem in the future, even if it is a bit complicated to implement?

**Comment by phoracek** [comment]
>     1. In Masquerade mode, the IPv6 address needs to be configured by cloud-init or the user manually configures it in the virtual machine. It cannot be automatically configured because of the IPV6 DHCP Server as you mentioned above?

Correct.

> 
>     2. Is it possible to improve on this problem in the future, even if it is a bit complicated to implement?

I theory, yes. However, due to the complexity to implement it and to maintain it it is not on the roadmap now.

**Comment by zhhray** [comment]
So, the problem is not that bridge mode does not support dual-stack, but that IPv6 is not automatically configured to a virtual machine in either Masquerade mode or Bridge mode.
The difference is that in Masquerade mode, the configuration of VM IPv6 is determined, whereas in Bridge mode, the configuration of VM IPv6 is required to follow the virt-launcher pod.

**Comment by zhhray** [comment]
So, the problem is not that bridge mode does not support dual-stack, but that IPv6 is not automatically configured to a virtual machine in either Masquerade mode or Bridge mode.
The difference is that in Masquerade mode, the configuration of VM IPv6 is determined, whereas in Bridge mode, the configuration of VM IPv6 is required to follow the virt-launcher pod.

**Comment by phoracek** [comment]
Precisely, you summarized it well

**Comment by phoracek** [comment]
@zcahana could we close it now or do you have any further questions?

**Comment by zcahana** [comment]
> @zcahana could we close it now or do you have any further questions?

I believe you meant to tag @zhhray :-)

**Comment by zhhray** [comment]
> @zcahana could we close it now or do you have any further questions?

yeah, you can close it. But I hope the feature gets into the roadmap early.
