### ISSUE TITLE
separate ingress services from kubevirt component manifests

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#554]
In an effort to make our development KubeVirt component manifests as generic as possible, we need to separate our vagrant ingress services containing references to externalIPs from the kubevirt components.

Put all ingress services related to vagrant in vagrant-services.yaml. This will move us in the direction of being able to use the kubevirt component manifests in environments outside of vagrant.

**Comment by rmohr** [comment]
> Put all ingress services related to vagrant in vagrant-services.yaml. This will move us in the direction of being able to use the kubevirt component manifests in environments outside of vagrant.

I know it is nitpicking, but also without that separation it is possible to deploy these manifests outside of vagrant. One can either adjust externalIPs to its needs and run `make generate`, or simply plug in our services via any other way (e.g. ingress) and just use different public ports. But moving them into one file, to make it easier to skip them is fine.

**Comment by rmohr** [comment]
Done in #560
