### ISSUE TITLE
setting nodeSelector for virt-handler daemonset does not work

### ISSUE THREAD

**Issue by kraxel** [kubevirt/kubevirt#5546]
/kind bug

**What happened**:

Tried to set the nodeSelector to "kubernetes.io/arch: amd64" for the virt-handler daemonset.
Does not work no matter what way I try (kubectl patch, kubectl edit, kubernetes dashboard).

It does work fine for the deployments (virt-{api,controller,operator}).

**What you expected to happen**:

I can set the nodeSelector according to my needs.
(I have a aarch64 node in the cluster, so I need exclude that because kubevirt is x86_64 only).

**How to reproduce it (as minimally and precisely as possible)**:

kubectl patch ds/virt-handler -n kubevirt -p '{"spec": {"template": {"spec": {"nodeSelector": {"kubernetes.io/arch": "amd64"}}}}}'
kubectl describe ds/virt-handler -n kubevirt | grep Node-Selector

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):

Client Version: version.Info{GitVersion:"v0.40.0", GitCommit:"127736619519e6b914e75930fc467c672e766e42", GitTreeState:"clean", BuildDate:"2021-04-20T08:34:39Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.40.0-dirty", GitCommit:"127736619519e6b914e75930fc467c672e766e42", GitTreeState:"dirty", BuildDate:"2021-04-20T08:57:15Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):

Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:28:42Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6", GitCommit:"8a62859e515889f07e3e3be6a1080413f17cf2c3", GitTreeState:"clean", BuildDate:"2021-04-15T03:19:55Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:

simple kubeadm-deployed cluster.

- OS (e.g. from /etc/os-release):

Fedora 33

- Kernel (e.g. `uname -a`):

5.11.15-200.fc33.x86_64

**Comment by kraxel** [comment]
Oops, no, for the deployments the nodeSelector can't be changed either.
Seems that they all ran on x86_64 nodes was caused by the aarch64 node being offline, not the attempt to patch the nodeSelector.

**Comment by enp0s3** [comment]
@kraxel Hi. I think that it didn't work for you because you have tried to apply the node selector directly on the DS/Deployment resource. Currently the only way to configure pod placement for the virt-handler is via the Kubevirt CR. The same is for the virt-api, virt-controller and virt-operator deployments. The virt-handler falls into the category called `workloads` while the rest of the deployments fall into `infra` category. 
Here is an example snippet of how would a Kubevirt CR look like:

```code
spec:
  infra:
    nodePlacement:
      nodeSelector:
        key1: value1
  worloads:
    nodePlacement:
      nodeSelector:
        key2: value2
```
With that configuration, virt-handler DS will be scheduled on node with `key2: value2` label, while the rest of the deployments will be scheduled on a node with `key1: value1` label.

**Comment by kraxel** [comment]
That works.  https://kubevirt.io/user-guide/operations/installation/ ("Restricting virt-handler DaemonSet" section) needs an update then.

**Comment by phoracek** [comment]
@kraxel thanks for checking. Could you please close this issue then, we would open a follow-up RFE for docs.

**Comment by kraxel** [comment]
ok, closing (adding a comment with a link to the doc RFE would be nice, thanks).
