### ISSUE TITLE
VMs no bootable device

### ISSUE THREAD

**Issue by teo-tsou** [kubevirt/kubevirt#5547]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind enhancement

**What happened**:
The Cirros VM does boot, but others does not. Following the guide : https://kubevirt.io/2019/How-To-Import-VM-into-Kubevirt.html
I have created PV / PVC that bounds to PV , uploaded the image succesfully , pods all running but VM can't start as no boot
able device . Exactly same issue as #2206
**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by phoracek** [comment]
@teo-tsou could you please share logs of the virt-launcher and virt-handler? Is following the linked how-to a reproducer?
