### ISSUE TITLE
Use k8s initializers for CRD admission control, and basic defaulting

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#556]
The short to medium term plan for the KubeVirt api is to continue to use CRDs for management of our cluster objects, and use the aggregated api server for stateless subresources (like Console and Spice).

For admission control and basic defaulting, we'll need to utilize k8s ability to create dynamic admission controllers and initializers.

https://kubernetes.io/docs/admin/extensible-admission-controllers/

Initializers can be used for basic defaulting and admission controllers can be used for cluster object validation.

**Comment by davidvossel** [comment]
as per #606, the initializer needs to perform defaulting by calling the new defaulting function on VM objects as they are posted to the cluster.

This defaulting is currently being done in the vm controller, it needs to be moved to an initializer though. 

move this line in pkg/virt-controller/vm.go to an initalizer.
```
kubev1.SetObjectDefaults_VirtualMachine(vmCopy)
```

**Comment by rmohr** [comment]
We should go with https://kubernetes.io/docs/admin/extensible-admission-controllers/#external-admission-webhooks instead of initializers.

**Comment by davidvossel** [comment]
@rmohr *Unlike initializers or the plugin-style admission controllers, external admission webhooks are not allowed to mutate the admission request in any way.*

It looks like these webhooks are only for validation. Without the ability to manipulate the object, it won't help with presets.

**Comment by rmohr** [comment]
That changed with 1.9. The web hook allows now mutations and is already beta. It overtook the initializes. See also http://blog.kubernetes.io/2018/01/extensible-admission-is-beta.html?m=1

**Comment by davidvossel** [comment]
Interesting.

A webhook that allows mutation then validation before persistence is far superior to what we're doing now. This means users would never be able to introduce an invalid VM spec into the system. 

We'll need to adopt this.  Once we add the validation webhook, both the defaulting and preset logic will need to move to that webhook.

**Comment by fabiand** [comment]
AFAIK there are still some limitations (in metadata), but in general the right approach.

**Comment by cynepco3hahue** [comment]
What plans do we have for admission hooks server, do we want to implement our own or do we want to re-use some code from OpenShift guys(https://github.com/openshift/generic-admission-server)?

**Comment by rmohr** [comment]
@cynepco3hahue Looks useful to me. Let's hope it will not be too much of a pain to keep the `k8s.io/apimachinery` dependencies in sync.

**Comment by davidvossel** [comment]
related webhook validation https://github.com/kubevirt/kubevirt/issues/404

**Comment by fabiand** [comment]
Actually closing this, as with presets and the node level defaulting we are in a good place.
