### ISSUE TITLE
Unexpected behavior when a VM with nodeSelector is migrated

### ISSUE THREAD

**Issue by ormergi** [kubevirt/kubevirt#5565]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
When a VM with `nodeSelector` is live migrated,  the migration job hang on `Scheduling`.
Looking on virt-launcher target and source pod state, shows that the target pod wont schedule 
and stuck on `Pending` phase, with the following error:
```
status:
  phase: Pending
  conditions:
    type: PodScheduled
    status: "False"
    message: '0/3 nodes are available: 1 node(s) didn''t match pod affinity/anti-affinity,
      1 node(s) didn''t match pod anti-affinity rules, 2 node(s) didn''t match Pod''s
      node affinity.'
    reason: Unschedulable
```
When I tried to cancel the migration by deleting the VMIM object it hangs and wont dispose.

From what I understand the target pod failed to schedule because when virt-controller creates the target pod, 
it place affinity rule on the target pod so it will shcedule on different node than the source VM node.
But the pod spec includes `nodeSelector` to the source node.
The target pod ends up to be in a state it has affinity rule that contradicts with its `nodeSelector`.

**What you expected to happen**:
Be able to migrate a VM that includes `nodeSelector`.
Or get informative error its not possible to migrate a VM with `nodeSelector`.

**How to reproduce it (as minimally and precisely as possible)**:
```
export KUBEVIRT_PROVIDER=k8s-1.20
export KUBEVIRT_NUM_NODES=3
make cluster-up cluster-sync

#Enable LiveMigration feature
cat <<END | kubectl apply -f - 
apiVersion: v1
kind: ConfigMap
metadata:
  name: kubevirt-config
  namespace: kubevirt
  labels:
    kubevirt.io: ""
data:
  feature-gates: "LiveMigration"
END

# Create VMI with nodeSelector
sed "/spec:/ a\
\  nodeSelector: \n \
   kubernetes.io/hostname: node02" \
examples/vmi-masquerade.yaml > /tmp/vmi.yaml
kubectl apply -f /tmp/vmi.yaml
kubectl wait vmi vmi-masquerade --for=condition=Ready

# Migrate VM
cat <<END | kubectl apply -f -
 apiVersion: kubevirt.io/v1alpha3
 kind: VirtualMachineInstanceMigration
 metadata:
   name: migrate-vmi-masquerade
   namespace: default
 spec:
   vmiName: vmi-masquerade
END

# Wait for few minutes and try to cancel the migration
kubectl delete vmim migrate-vmi-masquerade
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by phoracek** [comment]
@ormergi is there something broken (suggesting a bug) or should this be an RFE for better validation of a migration?

**Comment by maiqueb** [comment]
> @ormergi is there something broken (suggesting a bug) or should this be an RFE for better validation of a migration?

I agree here; I don't see how a VM you specifically indicate want running on a particular node can be migrated.

IMO, best you can hope for is a the migration request to be rejected.
