### ISSUE TITLE
docker save not working for virt-handler and virt-launcher

### ISSUE THREAD

**Issue by hickersonj** [kubevirt/kubevirt#5571]
**Is this a BUG REPORT or FEATURE REQUEST?**:

kind bug

**What happened**:
Docker save for two images is not working. The other kubevirt images are saving fine.
```
docker save quay.io/kubevirt/virt-handler:v0.40.0 -o virt-handler.tar
Error response from daemon: read /var/lib/docker/overlay2/fa3ef1f16fdee295865b1df57f0839b535768b291e2e56312ab008ed3dc61229/diff/lib64: is a directory
docker save quay.io/kubevirt/virt-launcher:v0.40.0 -o virt-launcher.tar
Error response from daemon: read /var/lib/docker/overlay2/6d336c247c24af7aa839b6e3c94b1da4a7341ea70d277fb87a58ccc0e998d038/diff/lib64: is a directory
```
**What you expected to happen**:
The docker save command should save the image manifests in the tarball.

**How to reproduce it (as minimally and precisely as possible)**:
1. docker pull quay.io/kubevirt/virt-handler:v0.40.0
2. docker save quay.io/kubevirt/virt-handler:v0.40.0 -o virt-handler.tar

**Anything else we need to know?**:
skopeo works, but that is not ideal since it only allows one copy at a time.
`skopeo copy docker://quay.io/kubevirt/virt-launcher:v0.40.0 docker-archive:./virt-launcher.tar`

**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.40.0", GitCommit:"127736619519e6b914e75930fc467c672e766e42", GitTreeState:"clean", BuildDate:"2021-04-20T08:34:39Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.40.0-dirty", GitCommit:"127736619519e6b914e75930fc467c672e766e42", GitTreeState:"dirty", BuildDate:"2021-04-20T08:57:15Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6+k3s1", GitCommit:"8d0432824a9fd9474b67138b7630c33f285d332f", GitTreeState:"clean", BuildDate:"2021-04-27T19:50:39Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.6+k3s1", GitCommit:"8d0432824a9fd9474b67138b7630c33f285d332f", GitTreeState:"clean", BuildDate:"2021-04-27T19:50:39Z", GoVersion:"go1.15.10", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
NAME=Fedora
VERSION="33 (Workstation Edition)"
ID=fedora
VERSION_ID=33
VERSION_CODENAME=""
PLATFORM_ID="platform:f33"
PRETTY_NAME="Fedora 33 (Workstation Edition)"
- Kernel (e.g. `uname -a`):
Linux endor 5.11.11-200.fc33.x86_64 #1 SMP Tue Mar 30 16:53:32 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by phoracek** [comment]
@hickersonj the rumor is you managed to work around this. Is that true and could we close this?

**Comment by lzang** [comment]
This should be already fixed by https://github.com/kubevirt/kubevirt/pull/5533, right? @rmohr

**Comment by rmohr** [comment]
Yes, the fix will be in 0.41 an 0.40.1.

**Comment by rmohr** [comment]
Here the fix: https://github.com/kubevirt/kubevirt/pull/5533

**Comment by hickersonj** [comment]
> @hickersonj the rumor is you managed to work around this. Is that true and could we close this?

Yes I needed to use the skopeo utility mentioned above to create the docker archive.  This of course bloats the overall size when splitting the virt-* images, but it still worked.  

Awesome it has been fixed! I’ll go ahead and test the new version out soon.

**Comment by hickersonj** [comment]
> @hickersonj the rumor is you managed to work around this. Is that true and could we close this?

Yes I needed to use the skopeo utility mentioned above to create the docker archive.  This of course bloats the overall size when splitting the virt-* images, but it still worked.  

Awesome it has been fixed! I’ll go ahead and test the new version out soon.

**Comment by hickersonj** [comment]
I can confirm that v0.41.0-rc.0 fixes this issue.
