### ISSUE TITLE
Change our resources labels to something more unique

### ISSUE THREAD

**Issue by cynepco3hahue** [kubevirt/kubevirt#559]
Currently, we have labels in the form of `app=`for all resources except `DaemonSets` that have labels in the form of `daemon=`, I think we need to make labels more unique and also make it consistent with all resources.
I think it can be something like `kubevirt-app=` for all resources, it will similar to k8s approach `k8s-app=`.

**Comment by rmohr** [comment]
Glad if you rename them. There exists the convetion in k8s that an extension should use its own group name as part of the label: `kubevirt.io/daemon`, `kubevirt.io/app`, ...

**Comment by cynepco3hahue** [comment]
ok, I can change it to `kubevirt.io/app`, but can we have the same style for DaemonSets as well?

**Comment by rmohr** [comment]
I am not sure if I understand the question. You can rename any label following that style, so that they hve the `kubevirt.io` prefix. Or what do you mean?

**Comment by cynepco3hahue** [comment]
@rmohr I want to avoid using different labels like `kubevirt.io/daemon` and `kubevirt.io/app`, it will make possible to look for all KubeVirt resources, just with one command
`kubectl get all -l 'kubevirt.io/app'`

**Comment by rmohr** [comment]
Oh, now I get it. You want to just use one label name. Works for me.
