### ISSUE TITLE
Inconsistent path for node-labeller.sh in virt-handler image

### ISSUE THREAD

**Issue by lzang** [kubevirt/kubevirt#5602]
/kind bug

**What happened**:

node-labeller.sh is packaged into the /usr/bin directory as shown here https://github.com/kubevirt/kubevirt/blob/e286b55c2c51d7dd7afda162722b142103df3968/cmd/virt-launcher/BUILD.bazel#L145

but is referred by /bin/node-labeller.sh when it is being used here https://github.com/kubevirt/kubevirt/blob/e286b55c2c51d7dd7afda162722b142103df3968/pkg/virt-operator/resource/generate/components/daemonsets.go#L83

**What you expected to happen**:

They should be consistent.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.40.0
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by phoracek** [comment]
AFAIK, /usr/bin is a link to /bin, no? Is what you expect just consistent use of the path or is there any functionality issue?

**Comment by lzang** [comment]
Hi Peter, /usr/bin is not always a link to /bin.  Some discussions on this topic is here https://unix.stackexchange.com/questions/5915/difference-between-bin-and-usr-bin. Making this assumption in code may break for a different linux system. In our use case, we packed the executable on top of a different base image, and we couldn't bring up the deployment because of this. From the code, this seems an unnecessary assumption to me. If it is no harm, can we make this path consistent? Thank!

**Comment by vasiliy-ul** [comment]
+1 from my side. We also use different base images and currently need to install node-labeller.sh explicitly in /bin. Its not causing big troubles but having some consistency would be nice indeed.
