### ISSUE TITLE
upgrading to kubevirt v0.41.0-rc.0 with OLM on OKD/OCP 4.8 doesn't work

### ISSUE THREAD

**Issue by tiraboschi** [kubevirt/kubevirt#5608]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
Upgrading (from different older releases) to kubevirt v0.41.0-rc.0 with OLM on OKD/OCP 4.8 doesn't work.

Older versions of kubevirt-operator are writing something like:
```
    {                                
        "group": "admissionregistration.k8s.io", 
        "hash": "",                  
        "lastGeneration": 1,         
        "name": "virt-operator-validator", 
        "namespace": "",             
        "resource": "validatingwebhookconfigurations" 
    },  
```
under status.generations on the kubevirt CR.

Although hash and namespace were supposed to be mandatory fields, for some reason (probably another bug on older OLM versions), in the past this has never been an issue.

Now kubevirt v0.41.0-rc.0 introduces a minor and completely unrelated changes to kubevirt CRD:
```
                 supportedGuestAgentVersions:
+                    description: deprecated
```
due to this,
before really starting the upgrade process, the OLM is going to validate the compatibility of existing CRs with the CRD that it is going to deploy during the upgrade.

And the OLM on OCP/OKD 4.8 is more picky and so it detects that hash and namespace are not filled under status.generations[*] and so it refuses to start the upgrade process with something like:

```
  - lastTransitionTime: "2021-05-05T10:42:26Z"
    lastUpdateTime: "2021-05-05T10:42:26Z"
    message: 'error validating existing CRs against new CRD''s schema: kubevirts.kubevirt.io:
      error validating custom resource against new schema &apiextensions.CustomResourceValidation{OpenAPIV3Schema:(*apiextensions.JSONSchemaProps)(0xc013051600)}:
      [[].status.generations.hash: Invalid value: "null": status.generations.hash
      in body must be of type string: "null", [].status.generations.namespace: Invalid
      value: "null": status.generations.namespace in body must be of type string:
      "null"]'
    reason: InstallComponentFailed
``` 

The easiest solution is probably to fix the schema in the CRD shipped with kubevirt 0.41 declaring hash and namespace on status.generations[] as optional.

**What you expected to happen**:
The OLM on OCP/OKD 4.8 is able to upgrade to kubevirt v0.41.0-rc.0

**How to reproduce it (as minimally and precisely as possible)**:
Try upgrading to kubevirt v0.41.0-rc.0 from v0.40 with OLM on OCP/OKD 4.8 and check the conditions on the relevant installPlan.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.41.0-rc.0 
- Kubernetes version (use `kubectl version`): OCP/OKD 4.8
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
I think merging and backporting https://github.com/kubevirt/kubevirt/pull/5495 will fix this. It will generate the correct api definition, which we would then publish via HCO to OLM and the validation should pass then.

**Comment by rmohr** [comment]
@davidvossel FYI

**Comment by davidvossel** [comment]
we have a potential fix here, https://github.com/kubevirt/kubevirt/pull/5609

**Comment by tiraboschi** [comment]
> Although hash and namespace were supposed to be mandatory fields, for some reason (probably another bug on older OLM versions), in the past this has never been an issue.

There was also a bug in the OLM that was not validating existing CRs against the new version of the CRD if that CRD was owned just by a single CSV (and this is obviously our case!).
This got fixed on the OLM side only 28 days ago and this perfectly explains why we start seeing this issue only now, see:
https://github.com/operator-framework/operator-lifecycle-manager/pull/2090/commits/35271e927752d6b8287400b30c08ff475b774d6f
