### ISSUE TITLE
KubeVirt tag release output on GCS is missing manifests and tests binary

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#5611]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:

When comparing the nightly release output against the tag release output we see the following:

```
$ gsutil ls -R gs://kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/20210507
gs://kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/20210507/:
gs://kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/20210507/commit
gs://kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/20210507/conformance.yaml
gs://kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/20210507/kubevirt-cr.yaml
gs://kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/20210507/kubevirt-operator.yaml

gs://kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/20210507/testing/:
gs://kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/20210507/testing/cdi-v1.31.0.yaml
gs://kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/20210507/testing/disks-images-provider.yaml
gs://kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/20210507/testing/local-block-storage.yaml
gs://kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/20210507/testing/rbac-for-testing.yaml
gs://kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/20210507/testing/tests.test
$ gsutil ls -R gs://kubevirt-prow/devel/release/kubevirt/kubevirt/v0.40.0/
gs://kubevirt-prow/devel/release/kubevirt/kubevirt/v0.40.0/:

gs://kubevirt-prow/devel/release/kubevirt/kubevirt/v0.40.0/manifests/:

gs://kubevirt-prow/devel/release/kubevirt/kubevirt/v0.40.0/manifests/testing/:
gs://kubevirt-prow/devel/release/kubevirt/kubevirt/v0.40.0/manifests/testing/cdi-v1.31.0.yaml
gs://kubevirt-prow/devel/release/kubevirt/kubevirt/v0.40.0/manifests/testing/disks-images-provider.yaml
gs://kubevirt-prow/devel/release/kubevirt/kubevirt/v0.40.0/manifests/testing/local-block-storage.yaml
gs://kubevirt-prow/devel/release/kubevirt/kubevirt/v0.40.0/manifests/testing/rbac-for-testing.yaml
``` 

This means that:
* if we want to consume the tag release we need to download the manifests from the GitHub release, as they are missing in the GCS bucket.
* the `tests.test` binary is missing in the tag release.
* a minor point is that the `devel` in the kubevirt tag release path is misleading.

**What you expected to happen**:

* tag release contains the release manifests as nightly release does
* tag release contains the `tests.test` binary as nightly release does
* tag release path is gs://kubevirt-prow/release/kubevirt/kubevirt/v0.40.0/

**How to reproduce it (as minimally and precisely as possible)**:

```
$ gsutil ls -R gs://kubevirt-prow/devel/nightly/release/kubevirt/kubevirt/20210507
$ gsutil ls -R gs://kubevirt-prow/devel/release/kubevirt/kubevirt/v0.40.0/
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by xpivarc** [comment]
@dhiller 
Was this addressed?
