### ISSUE TITLE
NVIDIA GPU passthrough failed , driver error code 43 . kubevirt features.kvm.hidden = on not working properly in kubevirt 0.40

### ISSUE THREAD

**Issue by KinglyWayne** [kubevirt/kubevirt#5619]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
I am trying to use kubevirt 0.40 to run windows 10 os with NVidia gpu(titan xp) passthrough,
however gpu driver always failed to load with error code 43 in windows guest os.

I have tried to add kvm feature hidden in kubevirt vmi crd config. 
https://github.com/kubevirt/kubevirt/issues/3285

This method used to work with kubevirt 0.30, however as kubevirt updated to 0.40,
qemu-kvm in virt-launcher was updated to 5.0.
As this article(https://mathiashueber.com/fighting-error-43-nvidia-gpu-virtual-machine/) said,
we have to set **_ioapic driver='kvm'_** to make kvm-hidden feature work again.
But I havn't find any way to set  **_ioapic driver='kvm'_** to vmi crd.

**What you expected to happen**:
A way to make nvidia gforce gpu passthrough working properly in windows 10 guest os.

**How to reproduce it (as minimally and precisely as possible)**:
![image](https://user-images.githubusercontent.com/3232817/117640363-8a28e700-b1b7-11eb-9155-58b6a1affc1e.png)

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.40.0
- Kubernetes version (use `kubectl version`): 1.16
- VM or VMI specifications:
`apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
  creationTimestamp: "2021-05-10T09:15:37Z"
  finalizers:
  - foregroundDeleteVirtualMachine
  generation: 9
  labels:
    kubevirt.io/domain: win10-2020
    kubevirt.io/nodeName: node11
  name: win10-2020
  namespace: default
  ownerReferences:
  - apiVersion: kubevirt.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachine
    name: win10-2020
    uid: 3335e63b-f176-446d-9008-e9f8cf3d1897
  resourceVersion: "27264140"
  selfLink: /apis/kubevirt.io/v1/namespaces/default/virtualmachineinstances/win10-2020
  uid: f584f9ae-5052-4a72-b0ec-b938001ae3ea
spec:
  domain:
    cpu:
      cores: 8
      model: Broadwell-noTSX-IBRS
    devices:
      disks:
      - bootOrder: 2
        cdrom:
          bus: sata
          readonly: true
          tray: closed
        name: cdromiso
      - bootOrder: 1
        disk:
          bus: virtio
        name: harddrive
      - bootOrder: 3
        cdrom:
          bus: sata
          readonly: true
          tray: closed
        name: virtiocontainerdisk
      gpus:
      - deviceName: nvidia.com/GP102_TITAN_Xp
        name: gpu1
      interfaces:
      - masquerade: {}
        model: rtl8139
        name: default
    features:
      acpi:
        enabled: true
      apic:
        enabled: true
      hyperv:
        vendorid:
          enabled: true
          vendorid: 13624789t
      kvm:
        hidden: true
    firmware:
      uuid: 83adbc09-7247-55a2-b84a-97434f38d6fc
    machine:
      type: q35
    resources:
      requests:
        cpu: 100m
        memory: 32G
  networks:
  - name: default
    pod: {}
  volumes:
  - name: cdromiso
    persistentVolumeClaim:
      claimName: iso-win10-2020
  - hostDisk:
      capacity: 150Gi
      path: /data/kubevirt-data/hari-ue4.img
      type: DiskOrCreate
    name: harddrive
  - containerDisk:
      image: kubevirt/virtio-container-disk
      imagePullPolicy: Always
    name: virtiocontainerdisk
status:
  activePods:
    33232bf0-f03c-4917-bda8-1dd06e764be0: node11
  conditions:
  - lastProbeTime: null
    lastTransitionTime: null
    message: 'cannot migrate VMI: PVC iso-win10-2020 is not shared, live migration
      requires that all PVCs must be shared (using ReadWriteMany access mode)'
    reason: DisksNotLiveMigratable
    status: "False"
    type: LiveMigratable
  - lastProbeTime: null
    lastTransitionTime: "2021-05-10T09:15:46Z"
    status: "True"
    type: Ready
  guestOSInfo: {}
  interfaces:
  - ipAddress: 192.168.222.175
    ipAddresses:
    - 192.168.222.175
    mac: 52:54:00:38:b4:70
    name: default
  launcherContainerImageVersion: quay.io/kubevirt/virt-launcher:v0.40.0
  migrationMethod: BlockMigration
  nodeName: node11
  phase: Running
  qosClass: Burstable
  volumeStatus:
  - name: cdromiso
    target: sda
  - name: harddrive
    target: vda
  - name: virtiocontainerdisk
    target: sdb`
- Cloud provider or hardware configuration: bare metal with titan xp gpu
- OS (e.g. from /etc/os-release): Ubuntu 18.04.5 LTS
- Kernel (e.g. `uname -a`):Linux node11 5.4.0-73-generic #82~18.04.1-Ubuntu SMP Fri Apr 16 15:10:02 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: offical controller yaml
- Others:

**Comment by davidvossel** [comment]
/cc @vladikr 

maybe you've encountered this?

**Comment by davidvossel** [comment]
maybe we should  automatically set that `ioapic driver='kvm' ` setting when the hidden kvm feature is enabled on our api.

**Comment by KinglyWayne** [comment]
> maybe we should  automatically set that `ioapic driver='kvm' ` setting when the hidden kvm feature is enabled on our api. 

Hi David, is there any workaround for now?  Thanks😊

**Comment by KinglyWayne** [comment]
> Hi @KinglyWayne, do you use the method ([#3285 (comment)](https://github.com/kubevirt/kubevirt/issues/3285#issuecomment-613299783)) with kubevirt v0.30 to add kvm feature hidden in the vmi YAML file?
> 
> Is it possible to add the setting `ioapic driver='kvm'` in the same way?

Hi Justin  I tried the method in https://github.com/kubevirt/kubevirt/issues/3285#issuecomment-613299783 , it does not work.
I can not find that sidecar's code, but I think maybe it's outdated for new version

**Comment by JustinHuang402490** [comment]
> > Hi @KinglyWayne, do you use the method ([#3285 (comment)](https://github.com/kubevirt/kubevirt/issues/3285#issuecomment-613299783)) with kubevirt v0.30 to add kvm feature hidden in the vmi YAML file?
> > Is it possible to add the setting `ioapic driver='kvm'` in the same way?
> 
> Hi Justin I tried the method in [#3285 (comment)](https://github.com/kubevirt/kubevirt/issues/3285#issuecomment-613299783) , it does not work.
> I can not find that sidecar's code, but I think maybe it's outdated for new version

Thanks for the reply. 

How about trying to pass through the GPU card to a VM without kubevirt?
I think there would be other issues that are not related to kubevirt.

**Comment by davidvossel** [comment]
> Hi David, is there any workaround for now? Thanksblush

There are two options here for you. A short term one and medium term.

short term:  Create your own sidecar hook which lets you inject the `ioapic driver='kvm'` into the libvirt domain at the point in time the VMI launches in the pod. here's an example of how a side car can be developed. https://github.com/kubevirt/kubevirt/tree/master/cmd/example-hook-sidecar

medium term: Wait for a kubevirt change that always sets this `ioapic` driver to kvm  when apic is enabled and the hidden kvm feature is used. That requires someone to contribute a patch (maybe you if you're interested ?!), the PR to get merged, and a release to get cut.

**Comment by JustinHuang402490** [comment]
> > > Hi @KinglyWayne, do you use the method ([#3285 (comment)](https://github.com/kubevirt/kubevirt/issues/3285#issuecomment-613299783)) with kubevirt v0.30 to add kvm feature hidden in the vmi YAML file?
> > > Is it possible to add the setting `ioapic driver='kvm'` in the same way?
> > 
> > 
> > Hi Justin I tried the method in [#3285 (comment)](https://github.com/kubevirt/kubevirt/issues/3285#issuecomment-613299783) , it does not work.
> > I can not find that sidecar's code, but I think maybe it's outdated for new version
> 
> Thanks for the reply.
> 
> How about trying to pass through the GPU card to a VM without kubevirt?
> I think there would be other issues that are not related to kubevirt.

After many tests, I successfully pass through the GPU card 1080 Ti **without kubevirt**. There are some important things I found:
1. We need to give the additional modified 1080 Ti ROM file and modify the corresponding configuration in the VM XML file.
![image](https://user-images.githubusercontent.com/41780406/119646101-5bff0480-be51-11eb-8e7f-c7d617e9263e.png)

2. The firmware should be UEFI.
![image](https://user-images.githubusercontent.com/41780406/119646314-9bc5ec00-be51-11eb-8f02-cb86e2c17181.png)

3. Set hidden state on and the vendor id in the VM XML file.
![image](https://user-images.githubusercontent.com/41780406/119646551-e0ea1e00-be51-11eb-9cd3-c8159ede3e2c.png)

Other information:
VM chipset type: q35
kubeveirt version: v0.34.0
libvirt version (use `virsh version`): 4.7.0 
qemu version (use `virsh version`): 2.12.0
How to modify ROM files: https://www.youtube.com/watch?v=1IP-h9IKof0 

---------------------------------------------------
In the next step, there are some things not sufficient if we want to passthrough GPU card 1080 Ti **with kubevirt**:
1. Copy the modified 1080 Ti ROM file into the pod which is created by kubevirt.
2. Modify the corresponding configuration in the VM XML file.

I know that we can modify the VM XML file by using the sidecar hook (https://github.com/kubevirt/kubevirt/tree/master/cmd/example-hook-sidecar). 
However, I have no idea how to copy a file into the pod which is created by kubevirt. 

Does anyone have ideas about it?  Thanks!

Other information: 
We can create a VM with UEFI by setting secureBoot: false. See: https://github.com/kubevirt/kubevirt/issues/4897
We can set hidden state and vendor id in the VM XML file due to #3471.

**Comment by vladikr** [comment]
@KinglyWayne @JustinHuang402490 

Thank you for your interest!

I would like to make a few observations.
First, the issues you are experiencing are related to the NVIDIA driver - this is not directly a KubeVirt issue.
The NVIDIA driver failing when detecting the KVM hypervisor means that NVIDIA does not support this card to be assigned to Virtual Machines running on the KVM hypervisor.
I wouldn't suggest using this configuration for production environments. 

However, in a community version QEMU, libvirt, and consequently KubeVirt, support the QEMU feature which hides the KVM signature. However, I wouldn't recommend adding any additional logic for handling the `ioapic` driver as part of KubeVirt. This can be done in a sidecar hook, as @davidvossel  suggested.

Unfortunately, at the moment we don't have a way of adding a custom rom to host devices, however, we are planning to introduce this.

**Comment by JustinHuang402490** [comment]
Hi Vladik, thank you for your reply. I list three possible ways of adding a custom ROM file to the pod created by KubeVirt.

1. Use a shared file with the localhost.

    I notice that there is one directory called "virt-bin-share-dir". The details are shown below. See pod description.

    I am curious about that **is "virt-bin-share-dir" possible to be used as a shared directory between the localhost and the pod?** Thus, the ROM file can also be seen in the pod.

2. Copy the ROM file to the pod directly.
    
    Steps are shown as follows:
    - Use the command `kubectl cp {source} {destination}` to copy the ROM file to pod directly. 
    - Get the console of the pod by using the command `kubectl exec -it {pod name} bash `
    - Modify the VM XML file manually as I posted above. The location of XML file is `/etc/libvirt/qemu/`.
    - Connect to the VM by using the command `virtctl vnc {VM name}`.
    - Restart the VM.

    However, this way does not work. It seems that the VM only be loaded one time. Therefore, the modified XML configuration does not work. Please tell me if my assumption is wrong.
    
    In addition, I also use the command `virtctl restart {VM name}` to restart the VM, but the pod is replaced by another new pod.

3. Copy the ROM file to the pod before the VMI running.
    
    When creating a VM, I observe that a pod should be in running status firstly comparing with a VMI. 
    
    Therefore, I think it is possible that copy/download the ROM file to the pod after the pod is in running status. Then the VMI can load the ROM file.

    In this way, I would need to develop KubeVirt. **Could you give me some hints or advice on which source files would need to be modified?** Thank you!

Other information:
- Pod description:
```
root@node1:~# kubectl describe po virt-launcher-vm-win10-jchgt 
Name:         virt-launcher-vm-win10-jchgt
Namespace:    default
Priority:     0
Node:         node1/10.172.61.82
Start Time:   Thu, 27 May 2021 10:05:42 +0000
Labels:       kubevirt.io=virt-launcher
              kubevirt.io/created-by=f2172ab1-131e-4a0b-82fe-c18c52caf4a1
              kubevirt.io/domain=pvc-win10vm
              special=key
Annotations:  k8s.v1.cni.cncf.io/networks-status:
                [{
                    "name": "cni0",
                    "ips": [
                        "10.233.90.51"
                    ],
                    "dns": {}
                }]
              kubevirt.io/domain: vm-win10
Status:       Running
IP:           10.233.90.51
IPs:
  IP:           10.233.90.51
Controlled By:  VirtualMachineInstance/vm-win10
Init Containers:
  container-disk-binary:
    Container ID:  docker://0d2c773dc3dad3d09f945c3a277bd2d6dc355ecf6efd4757b882fafd5907c6b5
    Image:         index.docker.io/kubevirt/virt-launcher@sha256:15280b86aa3dbb5ab9648eb8fefc57fa4e6a0f5d521318478ad5c89edd31479b
    Image ID:      docker-pullable://kubevirt/virt-launcher@sha256:15280b86aa3dbb5ab9648eb8fefc57fa4e6a0f5d521318478ad5c89edd31479b
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/cp
      /usr/bin/container-disk
      /init/usr/bin/container-disk
    State:          Terminated
      Reason:       Completed
      Exit Code:    0
      Started:      Thu, 27 May 2021 10:05:49 +0000
      Finished:     Thu, 27 May 2021 10:05:49 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      cpu:     100m
      memory:  40M
    Requests:
      cpu:        10m
      memory:     1M
    Environment:  <none>
    Mounts:
      /init/usr/bin from virt-bin-share-dir (rw)
Containers:
  compute:
    Container ID:  docker://a940b9a729ec38cc4e36cc6618ff55739508b1ef100bef3a993bcd000d74c330
    Image:         index.docker.io/kubevirt/virt-launcher@sha256:15280b86aa3dbb5ab9648eb8fefc57fa4e6a0f5d521318478ad5c89edd31479b
    Image ID:      docker-pullable://kubevirt/virt-launcher@sha256:15280b86aa3dbb5ab9648eb8fefc57fa4e6a0f5d521318478ad5c89edd31479b
    Port:          <none>
    Host Port:     <none>
    Command:
      /usr/bin/virt-launcher
      --qemu-timeout
      5m
      --name
      vm-win10
      --uid
      f2172ab1-131e-4a0b-82fe-c18c52caf4a1
      --namespace
      default
      --kubevirt-share-dir
      /var/run/kubevirt
      --ephemeral-disk-dir
      /var/run/kubevirt-ephemeral-disks
      --container-disk-dir
      /var/run/kubevirt/container-disks
      --grace-period-seconds
      45
      --hook-sidecars
      0
      --less-pvc-space-toleration
      10
      --ovmf-path
      /usr/share/OVMF
    State:          Running
      Started:      Thu, 27 May 2021 10:05:50 +0000
    Ready:          True
    Restart Count:  0
    Limits:
      devices.kubevirt.io/kvm:               1
      devices.kubevirt.io/tun:               1
      devices.kubevirt.io/vhost-net:         1
      nvidia.com/GP102_GeForce_GTX_1080_Ti:  1
    Requests:
      cpu:                                   100m
      devices.kubevirt.io/kvm:               1
      devices.kubevirt.io/tun:               1
      devices.kubevirt.io/vhost-net:         1
      memory:                                5273943040
      nvidia.com/GP102_GeForce_GTX_1080_Ti:  1
    Environment:                             <none>
    Mounts:
      /sys/devices/ from pci-devices (rw)
      /var/run/kubevirt-ephemeral-disks from ephemeral-disks (rw)
      /var/run/kubevirt-private/vmi-disks/disk0 from disk0 (rw)
      /var/run/kubevirt/container-disks from container-disks (rw)
      /var/run/kubevirt/sockets from sockets (rw)
      /var/run/libvirt from libvirt-runtime (rw)
Conditions:
  Type              Status
  Initialized       True 
  Ready             True 
  ContainersReady   True 
  PodScheduled      True 
Volumes:
  sockets:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  pci-devices:
    Type:          HostPath (bare host directory volume)
    Path:          /sys/devices/
    HostPathType:  
  disk0:
    Type:       PersistentVolumeClaim (a reference to a PersistentVolumeClaim in the same namespace)
    ClaimName:  pvc-win10vm
    ReadOnly:   false
  virt-bin-share-dir:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  libvirt-runtime:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  ephemeral-disks:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  container-disks:
    Type:        EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:      
    SizeLimit:   <unset>
QoS Class:       Burstable
Node-Selectors:  kubevirt.io/schedulable=true
Tolerations:     node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason     Age        From               Message
  ----    ------     ----       ----               -------
  Normal  Scheduled  <unknown>  default-scheduler  Successfully assigned default/virt-launcher-vm-win10-jchgt to node1
  Normal  Pulled     14s        kubelet, node1     Container image "index.docker.io/kubevirt/virt-launcher@sha256:15280b86aa3dbb5ab9648eb8fefc57fa4e6a0f5d521318478ad5c89edd31479b" already present on machine
  Normal  Created    14s        kubelet, node1     Created container container-disk-binary
  Normal  Started    14s        kubelet, node1     Started container container-disk-binary
  Normal  Pulled     13s        kubelet, node1     Container image "index.docker.io/kubevirt/virt-launcher@sha256:15280b86aa3dbb5ab9648eb8fefc57fa4e6a0f5d521318478ad5c89edd31479b" already present on machine
  Normal  Created    13s        kubelet, node1     Created container compute
  Normal  Started    13s        kubelet, node1     Started container compute
```
