### ISSUE TITLE
VMs are stuck in scheduling due to 0/7 nodes are available

### ISSUE THREAD

**Issue by soodpr** [kubevirt/kubevirt#5638]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
I tried to create a virtual machine, but it gets stuck in scheduling. Bug is similar to [4748](https://github.com/kubevirt/kubevirt/issues/4748). 

**What you expected to happen**:
The VM to be scheduled and then started. Describing the vmi I can see:
Warning FailedScheduling 4m27s default-scheduler 0/7 nodes are available: 1 node(s) had taint {node.kubernetes.io/unreachable: }, that the pod didn't tolerate, 3 Insufficient devices.kubevirt.io/kvm, 3 Insufficient devices.kubevirt.io/tun, 3 Insufficient devices.kubevirt.io/vhost-net, 3 node(s) didn't match Pod's node affinity.
Warning FailedScheduling 4m27s default-scheduler 0/7 nodes are available: 1 node(s) had taint {node.kubernetes.io/unreachable: }, that the pod didn't tolerate, 3 Insufficient devices.kubevirt.io/kvm, 3 Insufficient devices.kubevirt.io/tun, 3 Insufficient devices.kubevirt.io/vhost-net, 3 node(s) didn't match Pod's node affinity.

we were able to run the kubevirt VM's on the same setup earlier and we did no change on the k3s setup.

**How to reproduce it (as minimally and precisely as possible)**:
1.. Install 1.20.3 k3s+0.34.2 KubeVirt+1.26.1 cdi 
2. Upload a qcow2 image via virtctl image upload command.
3. Create a VM having pvc which got created in second step. Its stuck in scheduling state.

**Anything else we need to know?**:
As a workaround, i deleted all the virt-handler pods, and I was able to create VM's and its in running state. But we need to find out the root cause to avoid this in future. Worker nodes were available with these plugins, then why VM's were not getting scheduled on the worker nodes.

**Environment**:
- KubeVirt version (use `virtctl version`): 0.34.2
- Kubernetes version (use `kubectl version`): 1.20.3k3s
- VM or VMI specifications: 
- Cloud provider or hardware configuration: 3 master(KVM VM's)+4 worker(physical nodes) k3s cluster
- OS (e.g. from /etc/os-release): SUSE SLES OS
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by phoracek** [comment]
@soodpr is your cluster running or bare-metal (or do you have nested virtualization enabled)? If not, you may need to allow emulation (not that that will make you VMs quite slow).

If that is not helpful, could you please provide logs of your virt-handler pods.

**Comment by soodpr** [comment]
@phoracek: we have a k3s cluster running on 4 bare-metal nodes which are worker nodes and 3 kvm VM's on 1st 3 nodes which are master nodes. So, its a 3 master(KVM VM's) +4 worker node(bare metal) cluster. So, hardware virtualization is enabled on the nodes.
As, I have restarted the virt-handler pods, I am not sure if you need current pod logs but i am attaching it for your reference here. Please note 1 worker node is in NotReady state and we are looking into it. So, as of now, only 6 virt-handler pods are running.
[virt-handler1.log](https://github.com/kubevirt/kubevirt/files/6494692/virt-handler1.log)
[virt-handler2.log](https://github.com/kubevirt/kubevirt/files/6494693/virt-handler2.log)
[virt-handler3.log](https://github.com/kubevirt/kubevirt/files/6494694/virt-handler3.log)
[virt-handler4.log](https://github.com/kubevirt/kubevirt/files/6494695/virt-handler4.log)
[virt-handler5.log](https://github.com/kubevirt/kubevirt/files/6494696/virt-handler5.log)
[virt-handler6.log](https://github.com/kubevirt/kubevirt/files/6494697/virt-handler6.log)

Let me know if you need any other info.

**Comment by rmohr** [comment]
@soodpr I found

```
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"gl-gateway-rda-cas-vm2","namespace":"common","pos":"vm.go:1314","reason":"server error. command SyncVMI failed: \"LibvirtError(Code=1, Domain=10, Message='internal error: qemu unexpectedly closed the monitor: 2021-05-11T13:25:17.630675Z qemu-kvm: -device virtio-blk-pci,scsi=off,bus=pci.3,addr=0x0,drive=libvirt-2-format,id=ua-datavolumedisk1,bootindex=1,write-cache=on: Failed to get shared \\\"write\\\" lock\\nIs another process using the image [/var/run/kubevirt-private/vmi-disks/datavolumedisk1/disk.img]?')\"","timestamp":"2021-05-11T13:25:17.848739Z","uid":"971b8a0f-cc9e-487a-bae4-a4670e4fbb8c"}
```

in the logs which is unrelated, but can it be that you are mounting the same PVC to different VMs as writeable at the same time? If not, do you use nfsv3?

Regarding to KVM, the logs only show what I would expect if kvm is present. We would probably need the logs if this happens again. What I find strange is that it seems to have happened on all involved nodes, which may be a hint that kvm may have been loaded and enabled after virt-handler instances were already started (but virt-handler should pick that up dynamically).

**Comment by soodpr** [comment]
@rmohr - we have different pvc/pv for both vm's and .qcow2 images are uploaded to NFS in separate folders via virtctl image-upload command.

**Comment by rmohr** [comment]
> @rmohr - we have different pvc/pv for both vm's and .qcow2 images are uploaded to NFS in separate folders via virtctl image-upload command.

Ok, the error may come from the nfs3 usage (if you use it?). Consider using nfsv4, because nfsv3 does not work properly with qemu. But again, that is not related to your kvm problem.

**Comment by soodpr** [comment]
@rmohr - i have confirm we are using nfsv4.
For the original issue, we are monitoring our enviroment, but we haven't faced this issue yet. So, will update you once we face any issue with the scheduling of the VM's.
