### ISSUE TITLE
Generate predeployed Kuberntes Images based on kubeadm separately

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#564]
Goals are:

 1) Make it simpler to change kubevirt manifests without having to think about cleaning an already deployed version
 2) Decouple k8s deployment errors from KubeVirt errors
 3) Gain a permanent caching benefit by always using preprovisioned k8s images

**Comment by rmohr** [comment]
@cynepco3hahue FYI

**Comment by fabiand** [comment]
@rmohr could you explain this issue a little more? The issue and the solution you have in mind.

**Comment by rmohr** [comment]
Sure. It has its own complexity to deploy k8s. Kubeadm can have an issue, the newest k8s release can have an issue. Further we need to test against different k8s versions, different open shift versions and (probably) different network providers in the future. Therefore having dedicated jobs, which re-create/update base images with k8s periodically and do basic sanity checks, we can make our testing more resilient against external issues and always have the advantage that the images are already ready for KubeVirt. We also don't have to take care about removing our testing traces from the image, since we can just do a vagrant destroy && vagrant up.

**Comment by rmohr** [comment]
For as long as we are using vagrant, we can e.g. do a vagrant up, wait until the provision script succeeds and then upload the result to vagrant cloud with the appropriate version tag. If we move over to do something more like Cockpit does, we can host the images somewhere else.

**Comment by fabiand** [comment]
Thanks for clarifying this.

**Comment by fabiand** [comment]
@rmohr I think this is done,r ight?

**Comment by rmohr** [comment]
Yes done. We only need to officially deprecate vagrant now #844.
