### ISSUE TITLE
Adding a Disk to running VM 

### ISSUE THREAD

**Issue by rancherissue2** [kubevirt/kubevirt#5679]
**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

Hello Guys Please Help me out
Look for the other options that how we can attach the Storage in running VM
                        How to attach the additional disk to the base disk
                         if we need to share the data,media,config etc that exist to the server what are options to expose look that if it we can mount the VM the same way as a container

**Comment by awels** [comment]
With recent version of kubevirt 0.40 or newer, you should be able to do:
```
virtctl addvolume <vm(i) name> --volume-name=<name of dv/pvc>
```
and if you want to remove
```
virtctl removevolume <vm(i) name> --volume-name=<name of dv/pvc>
```
See https://github.com/kubevirt/kubevirt/blob/master/docs/hotplug.md for all the details.

**Comment by fabiand** [comment]
Closing according to the prev comment.
