### ISSUE TITLE
Did kubevirt v0.37.0 support hotplug datavolume ?

### ISSUE THREAD

**Issue by yangxiaoliang** [kubevirt/kubevirt#5688]
**What happened**:
I want add a new datavolume to running vm, but after modified the yaml and execute `kubectl apply -f vm.yaml`, I have to execute `virtctl restart myvm` to make the change works. I wondering if there is a way I can hotplug datavolue without have to restart the vm.

**What you expected to happen**:
The datavolume can be added successfully without have to restart the vm.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.37.0
- Kubernetes version (use `kubectl version`): 1.16
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by phoracek** [comment]
It did not. It should be available as a tech preview in 0.39
