### ISSUE TITLE
 KubeVirt in-depth install VERSION is not latest 

### ISSUE THREAD

**Issue by rajasaur** [kubevirt/kubevirt#5692]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug (in documentation)

**What happened**:
The command given in the Quickstart page at https://kubevirt.io/quickstart_minikube/ points to fetching VERSION using 

`export VERSION=$(curl -s https://api.github.com/repos/kubevirt/kubevirt/releases | grep tag_name | grep -v -- '-rc' | head -1 | awk -F': ' '{print $2}' | sed 's/,//' | xargs)
`

This returns v0.36.3 whereas the latest version is v0.41.0. Its dependent on the order on the github releases but seems unoredered.

**What you expected to happen**:
This should return v0.41.0

**How to reproduce it (as minimally and precisely as possible)**:
Run the script and see the version.

**Anything else we need to know?**:
Changing that to
`export VERSION=$(curl -s https://api.github.com/repos/kubevirt/kubevirt/releases | grep tag_name | grep -v -- '-rc' | sort -r | head -1 | awk -F': ' '{print $2}' | sed 's/,//' | xargs)`
would make it return the latest which is v0.41.0 (Adding the `sort -r`)

**Comment by ansijain** [comment]
@rajasaur Thanks for this issue.
This has been fixed https://github.com/kubevirt/kubevirt.github.io/pull/739
Feel free to close this issue

**Comment by rajasaur** [comment]
Thanks. Realized that it belonged to the website repo after filing and dint have access to move it. Thanks for committing.
