### ISSUE TITLE
Error in Live Migration using virtctl

### ISSUE THREAD

**Issue by ansijain** [kubevirt/kubevirt#5697]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**: I want to live migrate vm using virtctl but I am getting below error
```
 $virtctl migrate virtualmachineinstance.kubevirt.io/vmi-migratable
Error migrating VirtualMachine the server has asked for the client to provide credentials
```
kubectl get pods -n kubevirt
```
$  kubectl get pods -n kubevirt
NAME                              READY   STATUS    RESTARTS   AGE
virt-api-f8cddd7bd-692jw          1/1     Running   0          19d
virt-api-f8cddd7bd-qg8mp          1/1     Running   0          19d
virt-controller-68bc589cf-5jt7f   1/1     Running   0          19d
virt-controller-68bc589cf-z4w5r   1/1     Running   1          19d
virt-handler-ccb2t                1/1     Running   0          19d
virt-handler-st4s5                1/1     Running   0          19d
virt-operator-59997bd4d-kmz82     1/1     Running   1          19d
virt-operator-59997bd4d-l9lj5     1/1     Running   0          19d
virtvnc-5b48f698ff-gxnzz          1/1     Running   0          18d

```

**What you expected to happen**: Vm should successfully migrate

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**: Virtctl binary is located at  /usr/local/bin

**Environment**:
- KubeVirt version (use `virtctl version`): virtctl version
Client Version: version.Info{GitVersion:"v0.40.0", GitCommit:"127736619519e6b914e75930fc467c672e766e42", GitTreeState:"clean", BuildDate:"2021-04-20T08:34:39Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.40.0-dirty", GitCommit:"127736619519e6b914e75930fc467c672e766e42", GitTreeState:"dirty", BuildDate:"2021-04-20T08:57:15Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:31:21Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.0", GitCommit:"cb303e613a121a29364f75cc67d3d580833a7479", GitTreeState:"clean", BuildDate:"2021-04-08T16:25:06Z", GoVersion:"go1.16.1", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications: https://github.com/kubevirt/kubevirt/blob/master/examples/vmi-migratable.yaml
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by phoracek** [comment]
Is there anything special about the way you access your Kubernetes API server? And it would be also helpful if you could provide verbose log of virtctl via `-v9`.

**Comment by ansijain** [comment]
No I don't access API server in any special way.
```
~$ virtctl migrate virtualmachineinstance.kubevirt.io/vmi-migratable -v 9
Error migrating VirtualMachine the server has asked for the client to provide credentials

```

**Comment by ansijain** [comment]
Retried this using migration [lab](https://kubevirt.io/labs/kubernetes/migration.html) 
It was successful 
Closing this issue.
