### ISSUE TITLE
Support GlusterFS PV transformation to VM disk

### ISSUE THREAD

**Issue by humblec** [kubevirt/kubevirt#570]
The plan is to support GlusterFS PV as VM disk in kubevirt. 

Design:
Get GlusterFS PV from PVC.
Tranform that to Qemu libgfapi driver connection to Qemu and present as VM disk.

Thoughts ? 

ps# WIP patch  https://github.com/kubevirt/kubevirt/pull/578

**Comment by simon3z** [comment]
cc @aglitke

**Comment by rmohr** [comment]
Resolved with #734
