### ISSUE TITLE
Create policies for OpenShift

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#573]
Deloyment on OpenShift requires some policies to be adjusted, namely:

- PodPolicy
- ClusterPolicy

This post has more details: http://adam.younglogic.com/2017/08/deploying-kubevirt-on-origin-master/

This card is about identifying what needs to be provided for OCP, and provide the relevant patches.

**Comment by gbenhaim** [comment]
@fabiand Would you like me to add Openshift's `SecurityContextConstraints` manifests to this repo? (it can be added to manifests/openshift)

**Comment by fabiand** [comment]
I think it makes sense, yes.

**Comment by fabiand** [comment]
Done with #1005 and other PRs.
