### ISSUE TITLE
Measure and Export KubeVirt Performance Metrics

### ISSUE THREAD

**Issue by rthallisey** [kubevirt/kubevirt#5732]
In the recent [SIG-scale meeting](https://docs.google.com/document/d/1d_b2o05FfBG37VwlC2Z1ZArnT9-_AEJoQTe7iKaQZ6I/edit#heading=h.50eclt5fctl9), the community shared ideas about how we can measure KubeVirt for performance and gather that measurement data.  Here's the design we came up with:

/kind enhancement

### High Level Design
Create a new pkg in KubeVirt that will hold all the performance measurements.
Use the KubeVirt CR to configure measurement data export
Exporting results will be an interface that can be extended to different data formats.  Start with Prometheus.

#### Metrics
- [x] VM metrics - https://github.com/kubevirt/kubevirt/pull/1840
   - [x] [Sig-Scale] add Grafana dashboard for kubevirt control plane kubevirt/kubevirtci#646
- [x] Work queue metrics - https://github.com/kubevirt/kubevirt/pull/6013
   - [x] Work queue length - https://github.com/kubevirt/kubevirt/pull/1515
   - [x] Event callbacks enqueue time - https://github.com/kubevirt/kubevirt/pull/1515
   - [x] How often work queue keys are called - https://github.com/kubevirt/kubevirt/pull/1515
   - [x] Cache and work queue contents - https://github.com/kubevirt/kubevirt/pull/1515
- [x] Rest client rate limiter latency - https://github.com/kubevirt/kubevirt/pull/5963
- [ ] Breakdown Scheduling to Scheduled transition latency
   - [ ] Latency between all pods being Ready and VMI object transitioning to Scheduled
   - [ ] Latency between virt-launcher pods being assigned a node and creation timestamp
   - [ ] Latency of virt-launcher pods being assigned a network
   - [ ] Latency of virt-launcher pods pvc allocation
   - [x] Kube-scheduler pod e2e schedule time
- [x] Monitor VMIs that are taking a long time to reach Running
    - [x] VMI phase gauge to capture how many VMIs are in each phase - https://github.com/kubevirt/kubevirt/pull/5766 
    - [x] VMIs that take longer than the expected threshold time in a phase
- [x] VMI e2e create time
    - [x] VMI phase transition time - https://github.com/kubevirt/kubevirt/pull/5766 
    - [x] Record the VMI deletion time - https://github.com/kubevirt/kubevirt/pull/6283
- [ ] CPU, Mem usage, open goroutines, GC times
    - [x] general metrics already exposed by Golang to Prometheus
    - [ ] VMI pod metrics
- [x] API calls made (by us)
    - [x] Total number of API lists done by the reflectors
    - [x] How long an API list takes to return and decode for the reflectors
    - [x] How many items an API list returns to the reflectors
    - [x] Total number of API watches done by the reflectors
    - [x] Total number of short API watches done by the reflectors
    - [x] How long an API watch takes to return and decode for the reflectors
    - [x] How many items an API watch returns to the reflectors
    - [x] Kubernetes API calls e.g. latency, count, ect..
        - [x] Metric to monitor Request Counts by Resource and Operation #6186
- [x] API calls made (to us)
 Current situation might not be ideal
 Latency is polluted by long running requests like console/vnc
    - [x] Request latency in seconds. Broken down by verb and URL.
    - [x] Number of HTTP requests, partitioned by status code, method, and host
    - [x] Request latency for VirtualMachineInstances and VirtualMachines (Exclude VNC/console)

#### Tools that are NOT Covered by this Issue (but we're discussed)
GO profiling
Tool to generate load

**Comment by rthallisey** [comment]
requires https://github.com/kubevirt/project-infra/issues/1211

**Comment by marceloamaral** [comment]
This might require [kubevirt/monitoring/dashboards](https://github.com/kubevirt/monitoring/tree/main/dashboards)

**Comment by rthallisey** [comment]
We're discussion with Kubernetes SIG-scale about ways to measure the remaining open items.

**Comment by rthallisey** [comment]
>- [ ] Breakdown Scheduling to Scheduled transition latency
> - [ ] Latency between all pods being Ready and VMI object transitioning to Scheduled
> - [ ] Latency between virt-launcher pods being assigned a node and creation timestamp
> - [ ] Latency of virt-launcher pods being assigned a network
> - [ ] Latency of virt-launcher pods pvc allocation
>
The last remaining item is to measure how Kubernetes can affect e2e vm creation time.  We've had some conversation with Kubernetes Sig-Scale and we have some ideas on how to solve this.   We will follow up with the upstream community.
