### ISSUE TITLE
Flaky heartbeat unit test

### ISSUE THREAD

**Issue by maiqueb** [kubevirt/kubevirt#5753]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

**What happened**:
The "Heartbeat without deviceplugin and becoming ready after a few probes, node should be set to unschedulable immediately and switch earlier than one minute [It]" **unit** test is lately very flaky, as can be seen on [this CI kubevirt search](https://search.ci.kubevirt.io/?search=%2F%2Fpkg%2Fvirt-handler%2Fheartbeat%3Ago_default_test.*FAILED&maxAge=336h&context=1&type=build-log&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job). 

It fails with the following trace:

```
------------------------------
• Failure [1.513 seconds]
Heartbeat
pkg/virt-handler/heartbeat/heartbeat_test.go:26
  without deviceplugin and
  vendor/github.com/onsi/ginkgo/extensions/table/table.go:92
    becoming ready after a few probes, node should be set to unschedulable immediately and switch earlier than one minute [It]
    vendor/github.com/onsi/ginkgo/extensions/table/table_entry.go:43

    Timed out after 1.000s.
    Expected
        <map[string]string | len:2>: {
            "cpumanager": "false",
            "kubevirt.io/schedulable": "false",
        }
    to have {key: value}
        <map[interface {}]interface {} | len:1>: {
            "kubevirt.io/schedulable": "true",
        }

    pkg/virt-handler/heartbeat/heartbeat_test.go:121
------------------------------
{"component":"","level":"info","msg":"Updating cluster config from KubeVirt to resource version 'sgjv7btdcj'","pos":"config-map.go:516","timestamp":"2021-06-01T16:21:40.827643Z"}

JUnit report was created: /tmp/cache/bazel/18316b1300bb8985bc913139d5cc6323/sandbox/linux-sandbox/4153/execroot/__main__/bazel-out/k8-fastbuild/testlogs/pkg/virt-handler/heartbeat/go_default_test/test.xml


Summarizing 1 Failure:

[Fail] Heartbeat without deviceplugin and [It] becoming ready after a few probes, node should be set to unschedulable immediately and switch earlier than one minute 
pkg/virt-handler/heartbeat/heartbeat_test.go:121

Ran 8 of 8 Specs in 2.543 seconds
FAIL! -- 7 Passed | 1 Failed | 0 Pending | 0 Skipped
--- FAIL: TestHeartbeat (2.54s)
FAIL
```

**What you expected to happen**:
The test must be deterministic and consistently pass.

**How to reproduce it (as minimally and precisely as possible)**:
Run unit tests. Odds are it'll blow up on your face.

**Anything else we need to know?**:
Not right now.

**Comment by vasiliy-ul** [comment]
I alsos hit the same test failure a couple of times https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/5872/pull-kubevirt-unit-test/1406611309457313792. I see that someone is already assigned to the issue so maybe my findings may help.

The heartbeat period in the failing test is currently set  to **100 Seconds**: 

https://github.com/kubevirt/kubevirt/blob/7c3b33528ac61ec38e8ae5d54bb025988464e1ea/pkg/virt-handler/heartbeat/heartbeat_test.go#L98

Meaning that likely it will be able to do only one heartbeat probe (the first one) within the test. Though before the actual heartbeat there is a waiting for the device plugin to become initialized which triggers ~100 probes (each 10 Milliseconds for 1 second)

https://github.com/kubevirt/kubevirt/blob/7c3b33528ac61ec38e8ae5d54bb025988464e1ea/pkg/virt-handler/heartbeat/heartbeat_test.go#L95-L96

I think the reason for the flakiness here is that the timers are not precise and there is no guarantee that 100 probes will be hit while waiting for the device plugins (the transition to the initialized state in the test happens after 100 probes).

Therefore I think the hertbeat period needs to be set to at least **100 Millisecond** (or even less) to ensure the proper transiotion after 100 probes. @rmohr , I checked in git history that you did some work on those tests. Maybe you can comment if that sounds reasonable?

**Comment by rmohr** [comment]
> https://github.com/kubevirt/kubevirt/blob/7c3b33528ac61ec38e8ae5d54bb025988464e1ea/pkg/virt-handler/heartbeat/heartbeat_test.go#L95-L96
> 
> I think the reason for the flakiness here is that the timers are not precise and there is no guarantee that 100 probes will be hit while waiting for the device plugins (the transition to the initialized state in the test happens after 100 probes).

Right this here is probably the issue. Setting the `devicePluginWaitTimeout` either increasing the `devicePluginWaitTimeout` or reducing the probe count to e.g. 90 would probably eliminate the issue. My expectation that in `1s` exactly 100 probes with a `10ms` poll interval will happen is too optimistic on loaded systems.
