### ISSUE TITLE
kubemacpool-mac-controller-manager going into CrashLoopBackOff when creating a new HCO deployment

### ISSUE THREAD

**Issue by ezio-auditore** [kubevirt/kubevirt#5773]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
 /kind bug
> /kind enhancement

**What happened**:
 I was trying out the latest hco build kubevirt / hyperconverged-cluster-index:1.5.0-unstable  but something seems to be wrong with the kubemacpool-mac-controller-manager. The pod doesn't come up and stays in CrashLoopBackOff
**What you expected to happen**:
kubemacpool-mac-controller-manager should have been up and the kubervirt hco should be in succeeded state
**How to reproduce it (as minimally and precisely as possible)**:
Have openshift 4.8.0-fc.0 installed on 3 bare metals.
Followed this instruction to install unreleased builds:- https://github.com/kubevirt/hyperconverged-cluster-operator#installing-unreleased-bundle-using-a-custom-catalog-source 1.5.0-unstable
Created the following
 - CatalogSource
 - Namespace
 - OperatorGroup
 - Subscription
Created the Hyperconverged deployment from the openshift console ui.

**Anything else we need to know?**:
Have the following logs from kubemacpool-mac-controller-manager
```
{"level":"error","ts":1622725651.1346638,"logger":"runKubemacpoolManager","msg":"Failed to run the kubemacpool manager","error":"failed to start pool manager routines: failed Init pool manager maps: failed to init MacPoolMap From Cluster: failed to iterate the cluster vm interfaces to recreate the macPoolMap: the server could not find the requested resource","errorVerbose":"the server could not find the requested resource\nfailed to iterate the cluster vm interfaces to recreate the macPoolMap\ngithub.com/k8snetworkplumbingwg/kubemacpool/pkg/pool-manager.(*PoolManager).initMacMapFromCluster\n\t/home/travis/gopath/src/github.com
```
**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.41.0", GitCommit:"b7f322409e310ebaf7edb9f657d9864ad5730ab0", GitTreeState:"clean", BuildDate:"2021-05-12T14:43:31Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
the server could not find the requested resource
```
- Kubernetes version (use `kubectl version`):
Client Version: 4.7.7
Server Version: 4.8.0-fc.0
Kubernetes Version: v1.21.0-rc.0+fde4aa9
- VM or VMI specifications:
 N.A
- Cloud provider or hardware configuration:
3 baremetals
Intel(R) Xeon(R) Gold 6130 CPU @ 2.10GHz
16/16 cores; 32 threads 256 GB memory
- OS (e.g. from /etc/os-release):
```
cat /etc/os-release 
NAME="Red Hat Enterprise Linux CoreOS"
VERSION="48.84.202104151145-0"
VERSION_ID="4.8"
OPENSHIFT_VERSION="4.8"
RHEL_VERSION="8.4"
PRETTY_NAME="Red Hat Enterprise Linux CoreOS 48.84.202104151145-0 (Ootpa)"
ID="rhcos"
ID_LIKE="rhel fedora"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:redhat:enterprise_linux:8::coreos"
HOME_URL="https://www.redhat.com/"
BUG_REPORT_URL="https://bugzilla.redhat.com/"
REDHAT_BUGZILLA_PRODUCT="OpenShift Container Platform"
REDHAT_BUGZILLA_PRODUCT_VERSION="4.8"
REDHAT_SUPPORT_PRODUCT="OpenShift Container Platform"
REDHAT_SUPPORT_PRODUCT_VERSION="4.8"
OSTREE_VERSION='48.84.202104151145-0'
```
- Kernel (e.g. `uname -a`):
Linux ********* 4.18.0-293.el8.x86_64 #1 SMP Mon Mar 1 10:04:09 EST 2021 x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by RamLavi** [comment]
Hey @ezio-auditore , thank you for raising this issue. Can you attach the kubemacpool logs (both `kubemacpool-cert-manager` and `kubemacpool-mac-controller-manager`)?

**Comment by ezio-auditore** [comment]
[kubemacpool-cert-manager-6557fb8648-wj5cc-manager.log](https://github.com/kubevirt/kubevirt/files/6607352/kubemacpool-cert-manager-6557fb8648-wj5cc-manager.log)
[kubemacpool-mac-controller-manager-7df76694f-tg9bb-manager.log](https://github.com/kubevirt/kubevirt/files/6607353/kubemacpool-mac-controller-manager-7df76694f-tg9bb-manager.log)
@RamLavi Uploaded the required logs

**Comment by RamLavi** [comment]
Hey @ezio-auditore thank you for the logs.
I'm missing the HCO CR you were using.
I tried running with this and it worked without issues:
```
oc apply -n kubevirt-hyperconverged -f https://raw.githubusercontent.com/kubevirt/hyperconverged-cluster-operator/main/deploy/hco.cr.yaml
```
Please revisit using this cr and update on this issue.

**Comment by ezio-auditore** [comment]
Hi @RamLavi  I have used the above hco CR you have posted but I am facing the same issue.

**Comment by rmohr** [comment]
@RamLavi @ezio-auditore is this more an HCO issue, a kubemacpool issue or a kubevirt issue?

**Comment by ezio-auditore** [comment]
@rmohr I feel it is more of an kubemacpool issue , but I can only guess since that is the only component which is not working here.

**Comment by rmohr** [comment]
Would it make sense to open an issue at https://github.com/k8snetworkplumbingwg/kubemacpool or https://github.com/kubevirt/hyperconverged-cluster-operator/issues and continue the discussion there?

**Comment by ezio-auditore** [comment]
Added a new issue under kubemacpool to continue discussion there.
https://github.com/k8snetworkplumbingwg/kubemacpool/issues/313#issue-918277787
