### ISSUE TITLE
Add kubevirt_vmi_cpu_cores metric

### ISSUE THREAD

**Issue by sradco** [kubevirt/kubevirt#5774]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:
We would like to introduce a new metric, kubevirt_vmi_cpu_cores, that reports the number of cores allocated to each VMI.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@sradco could you provide some use-cases? Do you want to use it to identify the system load? Did you check if you get enough metrics through default metrics from k8s or node-exporter for your use-case?

**Comment by sradco** [comment]
@rmohr  We want to be able to calculate the total allocated CPUs vs. the total usage.
This is on the VMI level. We dont get that from k8s or node-exporter.
For longer term this will allow the cluster growth.
