### ISSUE TITLE
cloud-init iso fails when kubelet ephemeral dir is on 4k block storage

### ISSUE THREAD

**Issue by mlsorensen** [kubevirt/kubevirt#5785]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
Got error using cloud-init, virt-launcher goes to 'complete' state:
``` Cannot get 'write' permission without 'resize': Image size is not a multiple of request alignment'```

This is thrown by newer Qemu: https://www.mail-archive.com/qemu-devel@nongnu.org/msg723575.html

It seems perhaps the iso file is not created in multiples of 4k, and Qemu doesn't like that because block requests could go off the end of the file. Spot checking the noCloud.iso it seems it is 92.5 blocks long in this case. 

Because it is read-only Qemu can't auto adjust the size, either.

**What you expected to happen**:
VM starts up properly

**How to reproduce it (as minimally and precisely as possible)**:
Move /var/lib/kubelet dir to a device that reports 4k block size. This is a bit involved, but I used 'dd' to create a raw image, then 'losetup -b 4096' to create a 4k loop device, then used this as a PV and put LVM on it because I had trouble mounting a 4k loop device directly.

Then just try to create the examples/vmi-fedora.yaml, which includes cloud-init data.

**Anything else we need to know?**:
I haven't yet tested whether it's sufficient to somehow ensure the iso is created in even 4k chunks, and I'm not immediately certain of how to do that. If that works, it seems reasonable to create 4k-aligned iso files regardless as they'd be backward compatible.  

Would this affect container disk or any other Kubevirt ephemeral based storage?

**Environment**:
- KubeVirt version (use `virtctl version`): v0.41.0
- Kubernetes version (use `kubectl version`): v1.18.17

**Comment by mlsorensen** [comment]
Looks like if I run the cloud init iso through 'dd bs=4096 conv=sync' after it is created with genisoimage in cloud-init.go, that is sufficient to fix the issue. It writes out the rest of the partial block with nulls and makes the resulting iso 368 KiB instead of 366KiB. The VM then comes up properly.

**Comment by rmohr** [comment]
> Looks like if I run the cloud init iso through 'dd bs=4096 conv=sync' after it is created with genisoimage in cloud-init.go, that is sufficient to fix the issue. It writes out the rest of the partial block with nulls and makes the resulting iso 368 KiB instead of 366KiB. The VM then comes up properly.

That sounds like a good quick-fix. Apart from that would it make sense to file a bug against `genisoimage`?

**Comment by mlsorensen** [comment]
> > Looks like if I run the cloud init iso through 'dd bs=4096 conv=sync' after it is created with genisoimage in cloud-init.go, that is sufficient to fix the issue. It writes out the rest of the partial block with nulls and makes the resulting iso 368 KiB instead of 366KiB. The VM then comes up properly.
> 
> That sounds like a good quick-fix. Apart from that would it make sense to file a bug against `genisoimage`?

@rmohr that's a good idea. I researched this and learned a few things - it seems [genisoimage is a fork of mkisofs](https://wiki.debian.org/genisoimage) that may not really be getting much attention in terms of features. In the meantime I guess xorrisofs is a sane alternative that seems to be available on most distros.

The xorrisofs utility seems mkisofs backward compatible. By default it also generates an iso with odd number (185) of 2k sectors:
```
$ xorrisofs -v -J -r -V CIDATA -o test.iso iso/*
xorriso 1.5.2 : RockRidge filesystem manipulator, libburnia project.

Drive current: -outdev 'stdio:test.iso'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data, 22.5g free
Added to ISO image: file '/meta-data'='/home/marcus/go/src/kubevirt.io/kubevirt/iso/meta-data'
xorriso : UPDATE :       1 files added in 1 seconds
Added to ISO image: file '/user-data'='/home/marcus/go/src/kubevirt.io/kubevirt/iso/user-data'
xorriso : UPDATE :       2 files added in 1 seconds
ISO image produced: 185 sectors
Written to medium : 185 sectors at LBA 0
Writing to 'stdio:test.iso' completed successfully.
```

Using xorrisofs, I'm able to create isos that are 4k aligned by requesting cylinder sizes divisible by 4k like so (resulting in 186 2k sectors):

```
xorrisofs -v -J -r -V CIDATA -partition_sec_hd 2 -partition_hd_cyl 4 -partition_cyl_align on -o test.iso iso/*
xorriso 1.5.2 : RockRidge filesystem manipulator, libburnia project.

Drive current: -outdev 'stdio:test.iso'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data, 22.5g free
Added to ISO image: file '/meta-data'='/home/marcus/go/src/kubevirt.io/kubevirt/iso/meta-data'
xorriso : UPDATE :       1 files added in 1 seconds
Added to ISO image: file '/user-data'='/home/marcus/go/src/kubevirt.io/kubevirt/iso/user-data'
xorriso : UPDATE :       2 files added in 1 seconds
libisofs: NOTE : Aligned image size to cylinder size by 1 blocks
ISO image produced: 186 sectors
Written to medium : 186 sectors at LBA 0
Writing to 'stdio:test.iso' completed successfully.
```

This seems to be the way to go. The only caveat is from the way I read the doc `partition_sec_hd * partition_hd_cyl * 512 * 1024` is the max size of the image. Setting the cylinder size to 4k means a 4MB cloud-init volume is the largest we can do.  That seems reasonable for user data size, however if it is too small any 4k multiple for cylinder size should work.

Looks like we limit inline VMI userdata and networdata to 2k each, secrets and configmaps that might be used for these are limited to 1MiB. So 4k cylinders should be fine?

**Comment by mlsorensen** [comment]
It looks like if I try to put > 4MB of data into an iso with 4k cylinders requested, it automatically chooses alternate sizes and still works:

<pre>
$ xorrisofs -v -J -r -V CIDATA -partition_sec_hd 2 -partition_hd_cyl 4 -partition_cyl_align on -o test.iso iso/*
xorriso 1.5.2 : RockRidge filesystem manipulator, libburnia project.

Drive current: -outdev 'stdio:test.iso'
Media current: stdio file, overwriteable
Media status : is blank
Media summary: 0 sessions, 0 data blocks, 0 data, 22.5g free
Added to ISO image: file '/fill'='/home/marcus/go/src/kubevirt.io/kubevirt/iso/fill'
xorriso : UPDATE :       1 files added in 1 seconds
Added to ISO image: file '/meta-data'='/home/marcus/go/src/kubevirt.io/kubevirt/iso/meta-data'
Added to ISO image: file '/user-data'='/home/marcus/go/src/kubevirt.io/kubevirt/iso/user-data'
xorriso : UPDATE :       3 files added in 1 seconds
<b>libisofs: NOTE : Automatically adjusted MBR geometry to 536/1/32</b>
libisofs: NOTE : Aligned image size to cylinder size by 7 blocks
ISO image produced: 4288 sectors
Written to medium : 4288 sectors at LBA 0
Writing to 'stdio:test.iso' completed successfully.
</pre>

**Comment by rmohr** [comment]
> It looks like if I try to put > 4MB of data into an iso with 4k cylinders requested, it automatically chooses alternate sizes and still works:

That sounds great. `xorrisofs` would work for me.
