### ISSUE TITLE
keep virt-launcher pod name unchanged when restart vm

### ISSUE THREAD

**Issue by gojoy** [kubevirt/kubevirt#5786]
> /kind enhancement

**What happened**:
when I do `virtctl restart testvm`  ,the pod virt-launcher-testvm-jmvxn will be deleted and re-created  by virt-controller, 
and virt-launcher pod name change to virt-launcher-testvm-wx8rd

**What you expected to happen**:
the virt-launcher podname keep unchanged when restart vm 

**How to reproduce it (as minimally and precisely as possible)**:
1 start vm 
2 restart it
3 the virt-launcher pod name will be changed

**Anything else we need to know?**:
virt-controller create virt-launcher pod and set the pod name prefix in generateName , so the virt-launcher pod name is generated by k8s server . can virt-controller create pod with name instead of generateName?

**Environment**:
- KubeVirt version (use `virtctl version`): v0.41.0
- Kubernetes version (use `kubectl version`): 1.16

**Comment by rmohr** [comment]
@gojoy are you surprised that the pod gets recreated on a `restart` (restart vs reboot)? Or do you care about the pod name specifically?

**Comment by gojoy** [comment]
@rmohr yes，we allocate IP by pod name in IPAM ,when virt-launcher  pod name changes,VM IP changes too. VM IP changing when restart  is not a good expectation. so is there a way to keep virt-launcher pod name unchanged when restart vm? 
thanks

**Comment by rmohr** [comment]
> @rmohr yes，we allocate IP by pod name in IPAM ,when virt-launcher pod name changes,VM IP changes too. VM IP changing when restart is not a good expectation. so is there a way to keep virt-launcher pod name unchanged when restart vm?
> thanks

We change the IP to by default have on the VMI the same IP like on the pod. This can cause issues if VMs are not stateless. For this case we a different network binding method which uses masquerade: https://kubevirt.io/user-guide/virtual_machines/interfaces_and_networks/#masquerade

The disadvantage is that the VM does not have the same IP internally, which may not work for all use-cases.

**Comment by gojoy** [comment]
> > @rmohr yes，we allocate IP by pod name in IPAM ,when virt-launcher pod name changes,VM IP changes too. VM IP changing when restart is not a good expectation. so is there a way to keep virt-launcher pod name unchanged when restart vm?
> > thanks
> 
> We change the IP to by default have on the VMI the same IP like on the pod. This can cause issues if VMs are not stateless. For this case we a different network binding method which uses masquerade: https://kubevirt.io/user-guide/virtual_machines/interfaces_and_networks/#masquerade
> 
> The disadvantage is that the VM does not have the same IP internally, which may not work for all use-cases.

stateful applications running in VM also need  stable and unique network identifiers. masquerade mode can not provide it because pod IP and pod name can changes when restart.  Is there any potential disadvantage to keep virt-launcher pod name unchanged ?  and are there some concerns when virt-controller create launcher pod with a random name instead of stable name like statefulset controller
thanks

**Comment by rmohr** [comment]
> Is there any potential disadvantage to keep virt-launcher pod name unchanged ?

Let me add here that the pod name has nothing to do with the pod IP. Even if we would keep the name the IP would change every time (also a VM can have more than one pods from time to time, like for instance when migrations are happening).

> stateful applications running in VM also need stable and unique network identifiers.

In general no matter if bridge or pod, I would recommend that you access and announce applications via either clusterIP services (https://kubevirt.io/user-guide/virtual_machines/service_objects/#expose-virtualmachineinstance-as-a-clusterip-service) or headless services (https://kubevirt.io/user-guide/virtual_machines/dns/#dns-records). The first one can provide stable DNS entries AND a stable IP from outside (the clusterIP), the later can provide stable DNS entries for each VM (but not stable IPs from outside).

If you need full persistence (VM IP must not change from inside and outside) you can go with multus and e.g. assign IPs based on mac addresses for these interfaces (https://kubevirt.io/user-guide/virtual_machines/interfaces_and_networks/#multus). @phoracek or @qinqon may be able to provide more information for that.

**Comment by gojoy** [comment]
@rmohr got it,Thanks for you suggestion
