### ISSUE TITLE
gettingstarted: vagrant up  no supported architecture for os type 'hvm'

### ISSUE THREAD

**Issue by KennethNagin** [kubevirt/kubevirt#580]
I'm following your gettingstarted.md, however when trying to do vagrant up I get this error:
Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: internal error: no supported architecture for os type 'hvm'

These are the details:
kubevirt$ sudo vagrant up
Bringing machine 'master' up with 'libvirt' provider...
==> master: Box 'centos7' could not be found. Attempting to find and install...
    master: Box Provider: libvirt
    master: Box Version: >= 0
==> master: Box file was not detected as metadata. Adding it directly...
==> master: Adding box 'centos7' (v0) for provider: libvirt
    master: Downloading: http://cloud.centos.org/centos/7/vagrant/x86_64/images/CentOS-7-x86_64-Vagrant-1608_01.LibVirt.box
==> master: Successfully added box 'centos7' (v0) for 'libvirt'!
==> master: Uploading base box image as volume into libvirt storage...
==> master: Creating image (snapshot of base box volume).
==> master: Creating domain with the following settings...
==> master:  -- Name:              kubevirt_master
==> master:  -- Domain type:       kvm
==> master:  -- Cpus:              2
==> master:  -- Feature:           acpi
==> master:  -- Feature:           apic
==> master:  -- Feature:           pae
==> master:  -- Memory:            3000M
==> master:  -- Management MAC:
==> master:  -- Loader:
==> master:  -- Base box:          centos7
==> master:  -- Storage pool:      default
==> master:  -- Image:             /var/lib/libvirt/images/kubevirt_master.img (41G)
==> master:  -- Volume Cache:      default
==> master:  -- Kernel:
==> master:  -- Initrd:
==> master:  -- Graphics Type:     vnc
==> master:  -- Graphics Port:     5900
==> master:  -- Graphics IP:       127.0.0.1
==> master:  -- Graphics Password: Not defined
==> master:  -- Video Type:        cirrus
==> master:  -- Video VRAM:        9216
==> master:  -- Sound Type:
==> master:  -- Keymap:            en-us
==> master:  -- TPM Path:
==> master:  -- INPUT:             type=mouse, bus=ps2
Error while creating domain: Error saving the server: Call to virDomainDefineXML failed: internal error: no supported architecture for os type 'hvm'

I'm running on a VM with ubuntu trusty 14.04

Any help would be appreciated

**Comment by rmohr** [comment]
@KennethNagin could it be that you don't have nested virtualization enabled? Maybe worth checking that.

**Comment by KennethNagin** [comment]
@rmohr You are correct.  Nested virtualization is not enabled.    Apparently, in this particular VM enabling it is a problem. I will have to look into getting a host that I can enable nested.
I think you can close this one.
Thanks for your prompt response.

**Comment by rmohr** [comment]
If you don't mind that the VMs inside the nested VM are (possliby very) slow, you can also disable `domain.nested` to `false` in the Vagrantfile.
