### ISSUE TITLE
Replace offending language

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#5819]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:

We have several offending terms within the repo and need to fix that.

(Note: please add to this if you find something)
I.e.
* `master`: https://github.com/kubevirt/kubevirt/search?q=master

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by fossedihelm** [comment]
I forgot to mention this issue in the PR [#6814](https://github.com/kubevirt/kubevirt/pull/6814). Sorry about that.

**Comment by dhiller** [comment]
/close

Should be done for this repo.
