### ISSUE TITLE
Implementation of Watch API call is missing

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt/kubevirt#582]
When I work with KubeVirt via API, I would like to be able to listen on events generated by KubeVirt's objects, instead of pooling API for list of objects.
I see that relevant call is pointed to `NotImplementedYet` function
https://github.com/kubevirt/kubevirt/blob/63b774307c2afe6590040423f50e5dbaae734df0/pkg/virt-api/rest/kubeproxy.go#L165-L166

**Comment by lukas-bednar** [comment]
@rmohr I am taking look at Kubernetes API definition, and there is no `watchXYZ` operation.
On other hand I noticed that there are `listXYZ` operations which serves something like streamed `application/json` content, and in addition they have optional boolean parameter `watch`.
```
swagger.json-     "produces": [
swagger.json-      "application/json",
swagger.json-      "application/yaml",
swagger.json-      "application/vnd.kubernetes.protobuf",
swagger.json:      "application/json;stream=watch",
swagger.json:      "application/vnd.kubernetes.protobuf;stream=watch"
swagger.json-     ],
```
```
swagger.json-     {
swagger.json-      "uniqueItems": true,
swagger.json-      "type": "boolean",
swagger.json-      "description": "Watch for changes to the described resources and return them as a stream of add, update, and remove notifications. Specify resourceVersion.",
swagger.json:      "name": "watch",
swagger.json-      "in": "query"
swagger.json-     }
```
That is probably how they provide watch functionality.
Do you want to follow this direction, or do you want to have `watchXYZ` operations ?

**Comment by rmohr** [comment]
@lukas-bednar I think I have read somewhere that the watch resource paths were removed in k8s. 

Regarding to the api-docs, I would definitely want the `stream` parameter to be documented. 

Regarding to implementing it: I think we can rely on the dirct CRD implementation of k8s. We want to directly query the CRD endpoints on the apiserver and use this service only for subresources (registered as aggregated api server). See #556 to get an idea of the plan. So this service would still be responsible for creating the api documentation, and to serve subresources, but watch does not have to be implemented here.

**Comment by lukas-bednar** [comment]
@rmohr If I understand correctly, you say that this `watch` operation is already there by k8s.
I just need to add that `watch` parameter for `listXYZ` operations in order to get it through validation.
Is that correct ?

**Comment by lukas-bednar** [comment]
@rmohr thanks, I was able to move on little bit further with #585 .
I hit issue with reading that stream ... I will try to dive into it.
```
tests/common.py:97: in wait_for_item
    success_condition, failure_condition
tests/common.py:78: in _wait_for_x
    for e in self.watch(request_timeout=step):
tests/common.py:64: in watch
    for e in w.stream(self._event_source, **kw):
.tox/python/lib/python3.5/site-packages/kubernetes/watch/watch.py:118: in stream
    for line in iter_resp_lines(resp):
.tox/python/lib/python3.5/site-packages/kubernetes/watch/watch.py:45: in iter_resp_lines
    for seg in resp.read_chunked(decode_content=False):
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _

self = <urllib3.response.HTTPResponse object at 0x7fad1f3a69b0>, amt = None, decode_content = False

    def read_chunked(self, amt=None, decode_content=None):
        """
            Similar to :meth:`HTTPResponse.read`, but with an additional
            parameter: ``decode_content``.
    
            :param decode_content:
                If True, will attempt to decode the body based on the
                'content-encoding' header.
            """
        self._init_decoder()
        # FIXME: Rewrite this method and make it a class with a better structured logic.
        if not self.chunked:
            raise ResponseNotChunked(
>               "Response is not chunked. "
                "Header 'transfer-encoding: chunked' is missing.")
E           urllib3.exceptions.ResponseNotChunked: Response is not chunked. Header 'transfer-encoding: chunked' is missing.

.tox/python/lib/python3.5/site-packages/urllib3/response.py:584: ResponseNotChunked
```

**Comment by rmohr** [comment]
@lukas-bednar what I actually meant is, that I am not sure, if it is even worth the effort to implement the proxy call (you would simply have to add authorization headers and proxy the whole request data), since we hope to get rid of the proxy for main resources (just subresources would actually reach that proxy, the rest would directly go to the apiserver). @davidvossel is working on implementing that afaik.

What

**Comment by davidvossel** [comment]
>  what I actually meant is, that I am not sure, if it is even worth the effort to implement the proxy call (you would simply have to add authorization headers and proxy the whole request data), since we hope to get rid of the proxy for main resources (just subresources would actually reach that proxy, the rest would directly go to the apiserver). @davidvossel is working on implementing that afaik.

While I'd say there's still a bit of uncertainty around exactly what design we'll end up with for the api server, the one thing we're certain about is our usage of HAproxy (and the current virt-api component) will not remain.

Implementing this logic into the current api design will almost certainly result in it getting replaced by something else shortly.

**Comment by lukas-bednar** [comment]
@rmohr @davidvossel tanks for input, I will leave it aside for now.
Do you have any expectation when I can expect to have this `watch` functionality?
I find it quite essential when working with K8S & KubeVirt via API.

**Comment by rmohr** [comment]
@lukas-bednar you can point your client right now to the normal kubernetes api-server. You don't have validation then, but you can use watches. Maybe you can right now do writes on the proxy and reads from the apiserver. Actually when I think about it, we could do that right now in haproxy, based on the http method.

**Comment by lukas-bednar** [comment]
@rmohr Thanks for hint, it helped me to overcome my issue!

**Comment by lukas-bednar** [comment]
@rmohr I think that in meanwhile I can remove that `watch` operations.
When I consider that we don't plan to implement these anyway, we can just drop them, what do you think ?

**Comment by rmohr** [comment]
Yes, that is a good plan!

**Comment by rmohr** [comment]
@lukas-bednar can this be closed or are we still missing something?

**Comment by lukas-bednar** [comment]
@rmohr yes we can close this one.
