### ISSUE TITLE
Validation error during VM pod creation using kubectl 

### ISSUE THREAD

**Issue by gidde8** [kubevirt/kubevirt#5828]
Hi, 

I am trying to add few parameters to kubevirt yaml specification and adding necessary code changes in kubevirt. 

Added following two parameters into DomainSpec in the file **_staging/src/kubevirt.io/client-go/api/v1/schema.go_**
```
+       // SRIOV flag
+       SRIOV *bool `json:"SRIOV,omitempty"`

+       EnvVars []v1.EnvVar `json:"env,omitempty"`
```

Yaml changes:
```
    spec:
      domain:
        SRIOV: true

        env:
        - name: TMM_DESCSOCK_SVC_ID
          value: '8'
```

With above added changes trying to do launch VM using kubectl. 
```
#kubectl apply -f test.yml
error: error validating "test.yml": error validating data: [ValidationError(VirtualMachine.spec.template.spec.domain): unknown field "SRIOV" in io.kubevirt.v1alpha3.VirtualMachine.spec.template.spec.domain, ValidationError(VirtualMachine.spec.template.spec.domain): unknown field "env" in io.kubevirt.v1alpha3.VirtualMachine.spec.template.spec.domain]; if you choose to ignore these errors, turn validation off with --validate=false
```

- Is it okay to add missing parameters into schema ?
- Highly appreciated if schema path and steps to patch the schema changes are shared.

**Environment**:
```
KubeVirt version used to do these changes: 0.37.2
# kubectl version
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3+k3s-dd12684b-dirty", GitCommit:"dd12684b6f31171dbca928a7d30fe053d93d8fca", GitTreeState:"dirty", BuildDate:"2021-05-10T14:43:51Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.3+k3s-dd12684b-dirty", GitCommit:"dd12684b6f31171dbca928a7d30fe053d93d8fca", GitTreeState:"dirty", BuildDate:"2021-05-10T14:43:51Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by fabiand** [comment]
@phoracek can we help here?

**Comment by xpivarc** [comment]
Hi @gidde8 ,
did you also run `make` and `make generate` ?

**Comment by gidde8** [comment]
Hi @phoracek & @xpivarc, 

Thanks for your replies. 

After going through the virt-operator code i figured out that make and make generate need to be run. We no longer see this validation errors after doing make generate. 

However, have a question related to **api-rule-violations-known.list** and **api-rule-violations.lis**t file. Here make generate was complaining about newly added fields. To make compilation successful i have added newly fields into api-rule-violations-known.list file. After that compilation is fine. However, I just want to know is it right way to do it?

Thanks.

**Comment by xpivarc** [comment]
@gidde8 
It`s nothing major. It`s ensuring API consistency, e.g naming or tags for server-side apply. I would need to see the message to tell you which one it is.

**Comment by gidde8** [comment]
@xpivarc 
Here is the error message:

```
/root/go/src/kubevirt.io/kubevirt/api/api-rule-violations.list /root/go/src/kubevirt.io/kubevirt/api/api-rule-violations-known.list differ: char 22785, line 253
--- /root/go/src/kubevirt.io/kubevirt/api/api-rule-violations-known.list	2021-07-13 14:24:47.265216971 +0000
+++ /root/go/src/kubevirt.io/kubevirt/api/api-rule-violations.list	2021-07-13 14:26:58.548365463 +0000
@@ -250,6 +250,7 @@
 API rule violation: names_match,kubevirt.io/client-go/api/v1,NetworkConfiguration,NetworkInterface
 API rule violation: names_match,kubevirt.io/client-go/api/v1,PITTimer,Enabled
 API rule violation: names_match,kubevirt.io/client-go/api/v1,RTCTimer,Enabled
+API rule violation: names_match,kubevirt.io/client-go/api/v1,VirtualMachineInstance,CPU_ENV
 API rule violation: names_match,kubevirt.io/client-go/api/v1,VirtualMachineInstanceFileSystemInfo,Filesystems
 API rule violation: names_match,kubevirt.io/client-go/api/v1,VirtualMachineInstanceGuestAgentInfo,GAVersion
 API rule violation: names_match,kubevirt.io/client-go/api/v1,VirtualMachineInstanceGuestOSInfo,VersionID
You introduced new API rule violation

```
I had to add following missing field into  api-rule-violations-known.list to make compilation successful.

API rule violation: names_match,kubevirt.io/client-go/api/v1,VirtualMachineInstance,CPU_ENV

Is it okay adding the parameters into api-rule-violations-known.list ??
