### ISSUE TITLE
Patching of DataVolume resource not allowed and Patching of VM resource not reflected on VMI

### ISSUE THREAD

**Issue by k-p-ani** [kubevirt/kubevirt#5829]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
kind bug
> /kind enhancement

**What happened**:
Patching of resource "Data Volume" and "VirtualMachineInstance", not allowed.
Patching of resource "VirtualMachine" is not updating corresponding "VirtualMachineInstance" resource.

**What you expected to happen**:
We are trying to use GitOps (using ArgoCD) to deploy "Data Volume" and "VirtualMachine". When ever a new qcow2 image is released, through pipeline we update s3 URL of existing "Data Volume" yaml, so that old "Data Volume" and corresponding PVC gets deleted and new one gets created and hence other dependent resources like "VirtualMachine" / "VirtualMachineInstance" using this PVC, too get recreated. But this is not working

a work around we thought of is to change the name of existing "Data Volume" every time a new qcow2 image is released and push into git, this is causing old "Data Volume" to be deleted and corresponding "PVC" go into terminating state (but don't terminate as this PVC is still being referred by VMI). Then we update the "PVC" referenced in "VirtualMachine" resource yaml and push it to git, this change get's reflected in the Kubernetes cluster. But the "VirtualMachineInstance" resource is not getting restarted when the "VirtualMachine" is changed. We have to restart "VirtualMachineInstance" manually or first have to push "VirtualMachine" resource yaml with change to **running** property set to **false** "_running: false_", so VMI is deleted then push "VirtualMachine" resource yaml again with changes of PVC referring to new PVC from new DataVolume and property "_running: true_"

**How to reproduce it (as minimally and precisely as possible)**:
1> In any Kubernetes
- create Data Volume 
- create VirtualMachine  and use PVC created by above Data Volume.
- **kubectl edit dv** data-volume-resource-name , change the qcow2 file being referred and save the changes, you will get error

2> In any Kubernetes
- create Data Volume 
- create VirtualMachine (set _running: true_) and use PVC created by above Data Volume.
- create new Data Volume 
- Make sure VMI is still running
- **kubectl edit vm** virtualmachine-resource-name , change the PVC being referred to new PVC created by new DataVolume and save the changes
- Check VMI, it is neither restarted nor the change of VirtualMachine is reflected in the VMI.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.7-gke.1200", GitCommit:"7129f85dad2976728b7a010290adde1c4fb7f0eb", GitTreeState:"clean", BuildDate:"2021-01-29T09:21:41Z", GoVersion:"go1.15.5b5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.7-gke.1200", GitCommit:"7129f85dad2976728b7a010290adde1c4fb7f0eb", GitTreeState:"clean", BuildDate:"2021-01-29T09:20:09Z", GoVersion:"go1.15.5b5", Compiler:"gc", Platform:"linux/amd64"}
root@ip-10-0-0-110:/home/ubuntu/tools/k3skubevirt# virtctl version
Client Version: version.Info{GitVersion:"v0.36.3", GitCommit:"07364ff2b69d626230e36801ef7145168756be6e", GitTreeState:"clean", BuildDate:"2021-05-14T18:25:08Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.41.0-dirty", GitCommit:"b7f322409e310ebaf7edb9f657d9864ad5730ab0", GitTreeState:"dirty", BuildDate:"2021-05-12T15:11:03Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.7-gke.1200", GitCommit:"7129f85dad2976728b7a010290adde1c4fb7f0eb", GitTreeState:"clean", BuildDate:"2021-01-29T09:21:41Z", GoVersion:"go1.15.5b5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19+", GitVersion:"v1.19.7-gke.1200", GitCommit:"7129f85dad2976728b7a010290adde1c4fb7f0eb", GitTreeState:"clean", BuildDate:"2021-01-29T09:20:09Z", GoVersion:"go1.15.5b5", Compiler:"gc", Platform:"linux/amd64"}

- Cloud provider or hardware configuration:
    Bare metal
- OS (e.g. from /etc/os-release):
   Ubuntu 20.04.2 LTS (Focal Fossa)

**Comment by k-p-ani** [comment]
Hello,
Any one, with any updates on this.

**Comment by rmohr** [comment]
@k-p-ani wile I can't speak for the `DataVolume`, that changes on the VM are not immediately reflected is a design decision. You have to restart the VM after you change the spec. The VM behaves like traditional VMs in other virtualization platforms. You reconfigure and on the next restart you get the new config. Here it differs from e.g. a Pod `Deployment`, but also from a `VirtualMachineInstanceReplicaSet`.

I can recommend this flow (via tooling or api):

```
kubectl edit vm myvm
kubectl delete vmi myvm
```

If you have `running: true` it will restart the VM. Maybe we can also consider an enhancement where we add an additional `RunStrategy` which would also restart if the VM gets modified.

**Comment by k-p-ani** [comment]
Hi @rmohr 
   Thanks for your reply. I need one clarification from your reply "**If you have running: true it will restart the VM**" . Did you mean that if in my VM manifest file I have "**running:true**", then on any changes to VM manifest file, the existing running VM instance will get auto restarted and changes applied to VM manifest will get reflected? I tried this, as my VM manifest has "running: true", but still existing running VM instance didn't auto restarted , I had to restart it manually.
   
 Having "RunStrategy" will be great, which allow us to decide whether to auto restart running VM instance when VM manifest file is modified

**Comment by rmohr** [comment]
> Thanks for your reply. I need one clarification from your reply "**If you have running: true it will restart the VM**"

Sorry, I think I lost a **not** in the sentence. It will **not** restart the VM immeidiately. The changes will only be reflected on the next start.

**Comment by k-p-ani** [comment]
@rmohr 
thanks for quick update.
