### ISSUE TITLE
Move testing/demo related entities and testing back to default namespace

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#584]
It's generally good that the runtime components were moved into the `kube-system` namespace with #558.

However, that PR moved _all_ components to the `kube-system` namespace - including the demo and testing related components (i.e. iscsi targets).

But it makes sense to actually keep the demo and testing related components in the `default` namespace and the runtime components  in the `kube-system` namespace, to be closer how deployments are going to work: A user will deploy the add-on to `kube-system`, and then tenants will launch VMs in their respective namespaces.

**Comment by fabiand** [comment]
@cynepco3hahue could you take a look at this?

**Comment by cynepco3hahue** [comment]
@fabiand Sure, we talked about it yesterday, so I need to check that @davidvossel did not start to work on it.

**Comment by rmohr** [comment]
@fabiand default namespace is not a good choice. We can create an extra namespace. However, there is no reason  from the development/testing perspective to assume that there exists an explicit "default" namespace.

**Comment by cynepco3hahue** [comment]
@fabiand @rmohr So like we talked yesterday, something like `storage` namespace will be good enough?

**Comment by rmohr** [comment]
Yes sounds good.

**Comment by fabiand** [comment]
Please note that usually namespaces provide network isolation.

Currently our demo images are shared using the pod network,which means that they follow the namespace limitations.

If storage and vms are launched in different namespaces, then this will probably not work.

**Comment by cynepco3hahue** [comment]
In the end, I moved all demo entities to demo namespace, give me know if you still want to name it storage :smile:
