### ISSUE TITLE
[Conformance][test_id:1780] [It] [outside_connectivity]should be able to reach the outside world [IPv6] fails on k8s 1.17 kubevirtci provider

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#5857]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

/label sig/network

**What happened**:
[[Conformance][test_id:1780] [It] [outside_connectivity]should be able to reach the outside world [IPv6] fails on k8s 1.17 kubevirtci provider](https://github.com/kubevirt/kubevirt/blob/70acb0f2277ea24f7f7b8ec17ae3ccab19ca4de0/tests/network/vmi_networking.go#L804) fails on many runs against the k8s-1.17 provider of kubevirtci, also reproducible when running it locally on kubevirt/kubevirt with `KUBEVIRT_E2E_FOCUS='test_id:1780' make functests`

**What you expected to happen**:

Test should not fail.

**How to reproduce it (as minimally and precisely as possible)**:

On kubevirt/kubevirt local clone:
```
export KUBEVIRT_PROVIDER='k8s-1.17'
make cluster-up
make cluster-sync
KUBEVIRT_E2E_FOCUS='test_id:1780' make functests
```

**Anything else we need to know?**:

I just wanted to note this down as this is currently blocking PRs in kubevirtci: https://search.ci.kubevirt.io/?context=1&excludeName=&groupByJob=job&maxAge=336h0m0s&maxBytes=20971520&maxMatches=5&mode=text&name=%5Echeck-provision-k8s-1%5C.17%24&search=test_id%3A1780&searchType=bug%2Bjunit&wrapLines=false

Also I wanted to propose that we make the check-provision optional as we are planning to deprecate 1.17 soon and due to our policy it's not supported any more anyways.

/cc @rmohr @fgimenez @phoracek 

WDYT?

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
> Also I wanted to propose that we make the check-provision optional as we are planning to deprecate 1.17 soon and due to our policy it's not supported any more anyways.

Are we still blocked on the 1.17 rook lane regarding to dropping?

**Comment by dhiller** [comment]
yes, we agreed to combine the sig-storage with the rook-ceph lane, but on that topic no progress has been made yet.

**Comment by fgimenez** [comment]
SR-IOV lane runs on 1.17 too.

**Comment by phoracek** [comment]
This seems to be happening on on 1.17 while the test passes on all newer versions. I'm not convinced we should invest any time in debugging this on a no longer supported version of Kubernetes. While waiting for the Rook lane to be converted, could we just skip this test?

SR-IOV lane is being converted now. Also, it uses Kind, so it would not be affected if we delete the provider.

**Comment by dhiller** [comment]
By skipping the test you mean removing it in kubevirtci, i.e removing/making optional the `check-cluster-up-1.17` lane?

**Comment by dhiller** [comment]
@enp0s3 FYI

**Comment by dhiller** [comment]
> This seems to be happening on on 1.17 while the test passes on all newer versions. I'm not convinced we should invest any time in debugging this on a no longer supported version of Kubernetes. While waiting for the Rook lane to be converted, could we just skip this test?
> 
> SR-IOV lane is being converted now. Also, it uses Kind, so it would not be affected if we delete the provider.

@phoracek By skipping the test you mean removing it in kubevirtci, i.e removing/making optional the `check-cluster-up-1.17` lane?

**Comment by dhiller** [comment]
See kubevirt/kubevirtci#407

**Comment by dhiller** [comment]
/close

k8s 1.17 is deprecated for a longer while now
