### ISSUE TITLE
Notify server can go to crash-looping and handler functionality will degrade

### ISSUE THREAD

**Issue by xpivarc** [kubevirt/kubevirt#5859]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
While simulating ioerrors I noticed we sent a [error watch event](https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-launcher/notify-client/client.go#L219) that is causing shut down of notify server. This server is serving all VMs on the node and is used to provide domains to our decisions in the sync. 

The ioerror seems to be reported more than once and this will quickly full our queue. This will cause another shut down after the server will restart and the launcher sent another error event from the queue.

I have a suspicion that this also effects life-cycle operations of the VMs.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@xpivarc good catch. This should really not be a watch event error. The error should be visible through the transferred data.
