### ISSUE TITLE
CI continue falling on "Failed to install: hg is not installed"

### ISSUE THREAD

**Issue by cynepco3hahue** [kubevirt/kubevirt#589]
You need to install mercurial to make it works.

**Comment by ifireball** [comment]
Can you link to a failing job? Maybe is a matter of adding what ever is missing in the *.packages file?

**Comment by cynepco3hahue** [comment]
@ifireball http://jenkins.ovirt.org/job/kubevirt_kubevirt_standard-check-pr/138/
