### ISSUE TITLE
virt-launcher pod network card from vnet0 change to tap0 kubevirt_vmi_network_traffic_bytes_total direction not right

### ISSUE THREAD

**Issue by Icedroid** [kubevirt/kubevirt#5909]
After upgrade kubevirt, the virt-launcher pod network card from vnet0 change to tap0, and the metric kubevirt_vmi_network_traffic_bytes_total{type="tx"} == transmit bytes,   
kubevirt_vmi_network_traffic_bytes_total{type="rx"} == send bytes
It is absolutely opposite.

Old VM:
![image](https://user-images.githubusercontent.com/674647/123056109-25f57600-d439-11eb-82ae-405e4a5470bb.png)
![image](https://user-images.githubusercontent.com/674647/123055886-ed559c80-d438-11eb-8c6d-0e68bddff9f8.png)

New VM:
![image](https://user-images.githubusercontent.com/674647/123056411-7a005a80-d439-11eb-9d65-ff1e4db35e50.png)
![image](https://user-images.githubusercontent.com/674647/123056392-74a31000-d439-11eb-8116-99ceb2d14454.png)

**Comment by RamLavi** [comment]
Hey @Icedroid, thanks for reporting this.
Can you mention from which kubevirt version to which version you've upgraded?
