### ISSUE TITLE
Why not keep the virt-launcher pod running after stopping the VM

### ISSUE THREAD

**Issue by LLLLLBJ** [kubevirt/kubevirt#5929]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:
The virt-launcher pod was deleted after the VM stopped.
If the VM binds to a specific node, the VMI will stay in pending after stopping and starting if the node has no enough resources.

**What you expected to happen**:
I just want to know why not keep the virt-launcher pod running. Thank you.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.42.1
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
> The virt-launcher pod was deleted after the VM stopped.
> If the VM binds to a specific node, the VMI will stay in pending after stopping and starting if the node has no enough resources.

@LLLLLBJ thank you for your report. If we would keep the pod running, the resources would not be released. This  would not work very well with k8s. If you to keep your workload on a node but stop the VM temporarily, would it work for you if you just use `virtctl pause` or an in-guest reboot?
