### ISSUE TITLE
HCO Smoke tests constantly fail for v043.0-rc.0

### ISSUE THREAD

**Issue by nunnatsa** [kubevirt/kubevirt#5973]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
HCO Smoke tests are constantly failing when trying to bump to KubeVirt v0.43.0-rc.0

First attempt: https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1419
Second attempt: https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1423

The tests are failing for lack of iso files. For example, here: https://prow.ci.openshift.org/view/gs/origin-ci-test/pr-logs/pull/kubevirt_hyperconverged-cluster-operator/1423/pull-ci-kubevirt-hyperconverged-cluster-operator-main-hco-e2e-kv-smoke-azure/1411387404480155648

> tests/vmi_cloudinit_test.go:160
Unexpected error:
    <*errors.errorString | 0xc002be5ca0>: {
        s: "failed executing command on pod: command terminated with exit code 1: stderr stat: cannot stat '/var/run/libvirt/cloud-init-dir/kubevirt-test-default1/testvmi-222mq/noCloud.iso': No such file or directory\n: stdout: ",
    }
    failed executing command on pod: command terminated with exit code 1: stderr stat: cannot stat '/var/run/libvirt/cloud-init-dir/kubevirt-test-default1/testvmi-222mq/noCloud.iso': No such file or directory
    : stdout: 
occurred
tests/vmi_cloudinit_test.go:147

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by orenc1** [comment]
FYI @stu-gott & @davidvossel

**Comment by davidvossel** [comment]
This appears related to the 4k alignment PR https://github.com/kubevirt/kubevirt/pull/5806 

@rmohr @mlsorensen any ideas here why this might be occurring?

**Comment by rmohr** [comment]
This is for 0.35, but it shows similar symptoms: https://github.com/kubevirt/kubevirt/issues/5969 without #5806. I wonder if we have some ways how we can end up with a started VM but without the disk being created. On first glance I can't identify an error though.

**Comment by rmohr** [comment]
@nunnatsa do you have the chance to get some launcher logs for this?

**Comment by rmohr** [comment]
#5990 will fix this. Note that this is a test-only issue. Cloud-init works.

**Comment by davidvossel** [comment]
i'll generate a new RC once this lands

**Comment by rmohr** [comment]
The backport is merged.

**Comment by nunnatsa** [comment]
@rmohr - great, thanks. Waiting for a new RC, to validate in HCO.

**Comment by orenc1** [comment]
kubevirt v0.43.0-rc.1 has been validated in HCO in https://github.com/kubevirt/hyperconverged-cluster-operator/pull/1434.
thanks for fixing the issue.
