### ISSUE TITLE
In pod DHCP server idempotency is not required

### ISSUE THREAD

**Issue by maiqueb** [kubevirt/kubevirt#5984]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What happened**:
We currently have a [mechanism](https://github.com/kubevirt/kubevirt/blob/595191eec22605f02a7f1c359be8150829f2c648/pkg/network/dhcp/configurator.go#L80) to prevent the in-pod DHCP server (plugged in the IP pod bridge) from being started twice. 

It consists of creating a file in a kubevirt known path - `/var/run/kubevirt-private/dhcp_started-<pod-interface-name>`, and not starting the server if the file already exists. 

This so-called "idempotency" mechanism has two different issues:
1. how can we end up calling the method twice in the life of the same pod ? Unless I'm seriously wrong, since #5400 that cannot happen.
2. the file is never removed when/if the server dies. As a consequence, this does not implement idempotency - it just ensures that you have successfully started the dhcp server **once** in the life of the pod.

**What you expected to happen**:
This broken idempotency mechanism removed from the production code.

**Comment by rmohr** [comment]
Like discussed in the community meeting some kind of idempotency for the dhcp server makes sense since we expect all networking phases to be retried if they fail.

**Comment by maiqueb** [comment]
https://github.com/kubevirt/kubevirt/issues/5984#issuecomment-875658443
