### ISSUE TITLE
The execution process is interrupted inside the container, but there is ok when self-installing bazel is executed outside the container

### ISSUE THREAD

**Issue by Kate-DONG** [kubevirt/kubevirt#5995]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line: bug reports
>
> /kind bug
> /kind enhancement

**What happened**:The execution process is interrupted inside the container, but there is ok when self-installing bazel is executed outside the container.

**What you expected to happen**: We want to the execution process is ok inside the container.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

#There is the Makefile all part:
all:
        hack/dockerized "export BUILD_ARCH=${BUILD_ARCH} && DOCKER_PREFIX=${DOCKER_PREFIX} DOCKER_TAG=${DOCKER_TAG} IMAGE_PULL_POLICY=${IMAGE_PULL_POLICY} VERBOSITY=${VERBOSITY} ./hack/build-manifests.sh && \
            hack/bazel-fmt.sh && hack/bazel-build.sh"

#There is the interruptted area in hack/dockerized code :
## Run the command
test -t 1 && USE_TTY="-it"
if ! $KUBEVIRT_CRI exec ${USE_TTY} ${BUILDER}-bazel-server /entrypoint.sh "$@"; then
    # Copy the build output out of the container, make sure that _out exactly matches the build result
    if [ "$SYNC_OUT" = "true" ]; then
        _rsync --delete "rsync://root@127.0.0.1:${RSYNCD_PORT}/out" ${OUT_DIR}
    fi
    exit 1
fi
**Environment**:
- KubeVirt version (use `virtctl version`): v0.42.1
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@Kate-DONG it is not entirely clear to me what you mean. If `exit 1` is reached, the command `$KUBEVIRT_CRI exec ${USE_TTY} ${BUILDER}-bazel-server /entrypoint.sh "$@"` seems to have failed. Could you share the output you are seeing?

**Comment by Kate-DONG** [comment]
@rmohr ok. When we run the Makefile in kubevirt, the error occurs but it hasn't show the details about the error.  When we check the hack/dockerized code, we find the error happened at the place where the hack/dockerized runs the "run the command".

The output is given by:

[root@k3s-dev kubevirt]# make
hack/dockerized "export BUILD_ARCH= && DOCKER_PREFIX= DOCKER_TAG= IMAGE_PULL_POLICY= VERBOSITY= ./hack/build-manifests.sh && \
    hack/bazel-fmt.sh && hack/bazel-build.sh"
selecting docker as container runtime
WARNING: IPv4 forwarding is disabled. Networking will not work.
go version go1.16.1 linux/amd64
WARNING: IPv4 forwarding is disabled. Networking will not work.

d59464cdbb819a74a0c2ba006e0d490cd876041cf8ded72ec85637f869292c52
go version go1.16.1 linux/amd64
Another command holds the client lock: 
pid=14
owner=client
cwd=/root/go/src/kubevirt.io/kubevirt

Waiting for it to complete...
Another command (pid=14) is running. Waiting for it to complete on the server (server_pid=43)...
Loading: 0 packages loaded
    Fetching @com_github_bazelbuild_buildtools; fetching
make: *** [all] Error 1

**Comment by Kate-DONG** [comment]
@rmohr Additionally, in the "run the command", the code at the "! $KUBEVIRT_CRI exec ${USE_TTY} ${BUILDER}-bazel-server /entrypoint.sh "$@"" is interrupted and after it the code has not been executed.

**Comment by rmohr** [comment]
@Kate-DONG maybe it is related to `WARNING: IPv4 forwarding is disabled. Networking will not work.`? Can you try if it starts working when docker networking is working properly?

**Comment by Kate-DONG** [comment]
@rmohr Thanks, we try it first.

**Comment by Kate-DONG** [comment]
@rmohr Well, we have tried it, but there is similar error.

[root@k3s-dev kubevirt]# echo 1 > /proc/sys/net/ipv4/ip_forward
[root@k3s-dev kubevirt]# cat  /proc/sys/net/ipv4/ip_forward
1
[root@k3s-dev kubevirt]# make
hack/dockerized "export BUILD_ARCH= && DOCKER_PREFIX= DOCKER_TAG= IMAGE_PULL_POLICY= VERBOSITY= ./hack/build-manifests.sh && \
    hack/bazel-fmt.sh && hack/bazel-build.sh"
selecting docker as container runtime
go version go1.16.1 linux/amd64

799f3ae8922ed0bb3922745eb508534c281304ce139f5cdb19391a638d5fc889
go version go1.16.1 linux/amd64
Another command holds the client lock: 
pid=14
owner=client
cwd=/root/go/src/kubevirt.io/kubevirt

Waiting for it to complete...
Another command (pid=14) is running. Waiting for it to complete on the server (server_pid=18)...
Loading: 0 packages loaded
    Fetching @com_github_bazelbuild_buildtools; fetching
make: *** [all] Error 1

**Comment by rmohr** [comment]
@Kate-DONG did you restart docker?

**Comment by Kate-DONG** [comment]
@rmohr we have check the dockerd's twice and the values is different, so the docker does not restart.

[root@k3s-dev kubevirt]# ps aux|grep docker
root      1462  0.0  0.7 1062524 63988 ?       Ssl  Jul05   3:44 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
root      1814  0.0  0.0 364504  7732 ?        Sl   Jul05   0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 5000 -container-ip 172.17.0.2 -container-port 5000
root      1824  0.0  0.0 108712  6992 ?        Sl   Jul05   0:15 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/c3055388d398c48465d86d75d48089bd679dbb5cd7963a4110b7c23965a13605 -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runtime-runc
root      1842  0.0  0.1 123524  9868 pts/0    Ssl+ Jul05   0:36 registry serve /etc/docker/registry/config.yml
root     13708  0.0  0.0 112816   972 pts/6    S+   16:14   0:00 grep --color=auto docker
[root@k3s-dev kubevirt]# 
[root@k3s-dev kubevirt]# make
hack/dockerized "export BUILD_ARCH= && DOCKER_PREFIX= DOCKER_TAG= IMAGE_PULL_POLICY= VERBOSITY= ./hack/build-manifests.sh && \
    hack/bazel-fmt.sh && hack/bazel-build.sh"
selecting docker as container runtime
go version go1.16.1 linux/amd64

cdccd6f8e930c9e5a8d043e6ac8c6e5b11c0d568b7eb22383954edd947dfbf84
go version go1.16.1 linux/amd64
Another command holds the client lock: 
pid=14
owner=client
cwd=/root/go/src/kubevirt.io/kubevirt

Waiting for it to complete...
Another command (pid=14) is running. Waiting for it to complete on the server (server_pid=18)...
Loading: 0 packages loaded
    Fetching @com_github_bazelbuild_buildtools; fetching
make: *** [all] Error 1
[root@k3s-dev kubevirt]# 
[root@k3s-dev kubevirt]# ps aux|grep docker
root      1462  0.0  0.8 1062524 64748 ?       Ssl  Jul05   3:44 /usr/bin/dockerd -H fd:// --containerd=/run/containerd/containerd.sock
root      1814  0.0  0.0 364504  7732 ?        Sl   Jul05   0:00 /usr/bin/docker-proxy -proto tcp -host-ip 0.0.0.0 -host-port 5000 -container-ip 172.17.0.2 -container-port 5000
root      1824  0.0  0.0 108712  6992 ?        Sl   Jul05   0:15 containerd-shim -namespace moby -workdir /var/lib/containerd/io.containerd.runtime.v1.linux/moby/c3055388d398c48465d86d75d48089bd679dbb5cd7963a4110b7c23965a13605 -address /run/containerd/containerd.sock -containerd-binary /usr/bin/containerd -runtime-root /var/run/docker/runtime-runc
root      1842  0.0  0.1 123524  9868 pts/0    Ssl+ Jul05   0:36 registry serve /etc/docker/registry/config.yml
root     17057  0.0  0.0 112816   968 pts/6    S+   16:15   0:00 grep --color=auto docker

**Comment by rmohr** [comment]
@Kate-DONG I am not sure I can follow. I think the issue will go away now with working networking as soon as you restart docker. Something like `systemctl restart docker`.

**Comment by Kate-DONG** [comment]
@rmohr We tried the step "systemctl restart docker", but there still is the similar error. Well, we encounter the error is in kubevirt v0.42.1, and we tried that running the code in kubevirt v0.30.5 is ok.

**Comment by rmohr** [comment]
> @rmohr We tried the step "systemctl restart docker", but there still is the similar error. Well, we encounter the error is in kubevirt v0.42.1, and we tried that running the code in kubevirt v0.30.5 is ok.

Hm, I have no other idea right now. We did not really change anything in the build environment. Does `main` work for you? Maybe try deleting the `kubevirt` docker volume and related images and try again `docker volume rm kubevirt`.

**Comment by Kate-DONG** [comment]
@rmohr thanks，next we will try your suggest，and I want to know if podman can replace docker?

**Comment by rmohr** [comment]
> @rmohr thanks，next we will try your suggest，and I want to know if podman can replace docker?

Yes, you can use podman instead. If you have podman installed and simply disable docker it should choose podman. As an alternative you can `export KUBEVIRT_CRI=podman`.

**Comment by Kate-DONG** [comment]
@rmohr ok, thanks.
