### ISSUE TITLE
Mount function of container-disk may use wrong targetPathFromHostView to call IsMounted and Create

### ISSUE THREAD

**Issue by LLLLLBJ** [kubevirt/kubevirt#5996]
https://github.com/kubevirt/kubevirt/blob/5103668474ebe084f3652b6501a49ab0b6b0f285/pkg/virt-handler/container-disk/mount.go#L224

GetDiskTargetPathFromHostView get the target path from host view, is it equal to kubelet pods dir hostPath?
Then nodeRes.IsMounted(targetFile) and os.Create(targetFile) are executed in handler pod namespace without chroot.
This bug causes kubelet pods dir hostPath must be same with mountPoint in pod, right?

**Comment by rmohr** [comment]
@LLLLLBJ can it be that you are not using the standard kubelet pod dir structure? If so, https://github.com/kubevirt/kubevirt/issues/5913 may be interesting for you.

**Comment by LLLLLBJ** [comment]
@rmohr Yes, it is!  Hope `--kubele-pods-dir` fully support.

**Comment by rmohr** [comment]
@LLLLLBJ maybe you can create a symlink like mentioned in #5913. Closing this as duplicate of #5913. Feel free to reopen if needed.
