### ISSUE TITLE
Check flakefinder: it states there were no merged PRs for the 24h/168h reports

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#6043]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:

/kind bug
> /kind enhancement

**What happened**:
Just noticed that the reports state there were no PRs merged.

Example: 
https://storage.googleapis.com/kubevirt-prow/reports/flakefinder/kubevirt/kubevirt/flakefinder-2021-07-14-168h.html

Possibly a search problem.

/cc @rmohr @fgimenez 

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@dhiller is it still using `master`?

**Comment by dhiller** [comment]
> @dhiller is it still using `master`?

Good point! Will check that!
