### ISSUE TITLE
[SIG-scale] virt controller disruption budget workqueue add rate is very high

### ISSUE THREAD

**Issue by rthallisey** [kubevirt/kubevirt#6054]
### Summary
Create n VMIs, wait until they are all running, delete n VMIs, wait until they are all deleted, sleep 5s, and repeat. Scenarios creating 10, 20, 40, 60, 80, 100, 200, 300 VMIs causes virt controller's disruption budget workqueue add rate to grow exponentially.

### KubeVirt control plane metrics
<img width="468" alt="work-queue-depth-5982" src="https://user-images.githubusercontent.com/6795213/125938765-b3004834-6153-4494-bfd9-73c3a811dca9.png">

### Metrics
| Name | Description | Metric |
|--|---|--|
| work queue add rate | Total number of adds handled by a workqueue | `sum(rate(kubevirt_workqueue_adds_total{job=~".*kubevirt.*"}[5m])) by (instance, name)`|
| work queue depth | Current depth of a workqueue | `sum(rate(kubevirt_workqueue_depth{job=~".*kubevirt.*"}[5m])) by (instance, name)`|

/kind bug

**Comment by rthallisey** [comment]
@marceloamaral can you post the VMI spec?

**Comment by marceloamaral** [comment]
In all experiments, the VMI configuration is:
- a cirros Image with an ephemeral-storage of 50M, 
- 0.1 (100m) of CPU limit and 
- 90Mi of Memory limit, but the VMI has an overhead of 171Mi, then, total of 261Mi

The test was conducted in the environment that we plan to use for the performance tests in the KubeVirt CI/CD. The infrastructure is composed of 6 Bare-metal nodes from IBM Cloud Classic. Each node is composed of Intel Xeon 8260 (Cacade Lake) 48CPUs, 128MEM, 10Gpbs and 1T Disk. 
The kubernetes cluster was created using kubespray with a calico network. We installed  Kubernetes 1.21 with 3 master nodes and 3 worker nodes.
More info [here](https://docs.google.com/document/d/1a_7uEZmWlHH-ibcxQlYlwYyVcnPC10v2HeZj5FrJex0/edit#).

**Comment by marceloamaral** [comment]
With new further investigation, the number of adds in the `virt-controller-disruption-budget` workqueue is similar to the number of adds in `virt-controller-vm` workqueue. 

Which actually sounds reasonable, so @rthallisey I think we can close this issue.

**Comment by rthallisey** [comment]
It would be interesting to know what this looks like in k8s.  That does that sounds reasonable though.
