### ISSUE TITLE
Replace dead "stress" binary with new, maintained "stress-ng" binary

### ISSUE THREAD

**Issue by iholder-redhat** [kubevirt/kubevirt#6061]
**Is this a BUG REPORT or FEATURE REQUEST?**:
FEATURE REQUEST

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:
The following is copied from a mail sent by me to kubevirt-dev:

While trying to stabilize one of our migration tests I figured that the stress binary we're using sometimes crashes, which is installed on "fedora-with-test-tooling" image [1]. I tried to reduce the memory allocation size, but the stress binary seemed to remain very unstable.

Turns out that the stress binary we use is dead - its latest release was 11 years ago [2] and its upstream repo is gone [3]. Turns out there is newer version - stress-ng - which is a "re-write of the original stress tool" [4]. It's also supposed to be fully backwards compatible with the old stress binary.

To have an indication that it's going to be a smooth transition I've deployed a local cluster, pushed a new "fedora-with-test-tooling" image with stress-ng installed to the local cluster's registry, and modified our stress command [5] to use stress-ng. I ran some of the functional migration tests and they all passed.

**What you expected to happen**:
The following steps are needed:

- [X] Create a new `fedora-with-test-tooling` image with `stress-ng` installed instead of `stress` and upload it to quay.io/kubevirtci
  - Done. Find the container [here](https://quay.io/repository/kubevirtci/fedora-with-test-tooling?tab=tags) (tagged `32-1-stress-ng`).
- [x] PR to Kubevirt - use new container & `stress-ng` binary in migration tests.
  - PR: https://github.com/kubevirt/kubevirt/pull/6062
- ~~[ ] PR to KubevirtCI - use new container & `stress-ng` binary in SRIOV lane~~.
  - ~~@ormergi will be in charge of this PR.~~
  - See [this](https://github.com/kubevirt/kubevirt/issues/6061#issuecomment-975353225).

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a local cluster and execute stress binary a bunch of time. The binary is flakie, i.e. sometimes crashes and sometimes finishes successfuly.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ormergi** [comment]
I have published the new image for SRIOV lane it includes `stress-ng`
https://quay.io/repository/omergi/fedora-sriov-lane/manifest/sha256:5939d92c4569ba67fa83490a571889bbd433b4142816c88900c8e9e2a478a261
We will *probably* need it for #5922 e2e tests, though we could end up not using it as we encountered some issues
I will update if we will actually need it or not.

**Comment by iholder-redhat** [comment]
> I have published the new image for SRIOV lane it includes `stress-ng`
> https://quay.io/repository/omergi/fedora-sriov-lane/manifest/sha256:5939d92c4569ba67fa83490a571889bbd433b4142816c88900c8e9e2a478a261
> We will **probably** need it for #5922 e2e tests, though we could end up not using it as we encountered some issues
> I will update if we will actually need it or not.

Are you talking about issues with new `stress-ng`? I would appreciate more info on that.
In general, IMHO, we need a very good reason to not deprecate a dead, old and unmaintained executable. Eventually I expect us to completely get rid of the old stress everywhere.

**Comment by iholder-redhat** [comment]
My PR's for Kubevirt: https://github.com/kubevirt/kubevirt/pull/6062

**Comment by iholder-redhat** [comment]
Hey @ormergi :)
Want to give an update on remaining task? I just don't want this issue to be rotten

**Comment by ormergi** [comment]
@iholder-redhat I think we can call it obsolete since we use the same image also on SRIOV lane :slightly_smiling_face:
https://github.com/kubevirt/kubevirt/pull/6108

**Comment by iholder-redhat** [comment]
> @iholder-redhat I think we can call it obsolete since we use the same image also on SRIOV lane slightly_smiling_face #6108

Sure :) I guess we can close this issue then.
/close
