### ISSUE TITLE
[Sig-scale] enable virt-operator to configure virt-handler to run more than 110 VMs per node

### ISSUE THREAD

**Issue by marceloamaral** [kubevirt/kubevirt#6082]
/kind enhancement

**Motivation**:
In the recent [SIG-scale meeting](https://docs.google.com/document/d/1d_b2o05FfBG37VwlC2Z1ZArnT9-_AEJoQTe7iKaQZ6I/edit#heading=h.50eclt5fctl9), we are discussing to run a scale test with more than 110 VMIs per node. It is trivial to increase the max number of pods per node, but the max number of VMIs is not straightforward. 

**What happened**:
Currently, `virt-handler` already have `max-devices` flag to increase the number of VMs per node
https://github.com/kubevirt/kubevirt/blob/0514a664151863d901d90694feb08c86df0076bb/cmd/virt-handler/virt-handler.go#L527

However, the `virt-handler` configuration is determined by the `virt-operator` that reverts all changes in the `virt-handler` Daemonset during the reconcile (of course, when we deploy it using the operator) .

**What you expected to happen**:
I expect to be able to configure `virt-operator` to create all `virt-handler` with a given max-devices number. Currently, all the `virt-handler` Daemonset options in `virt-operator` are hardcoded:
https://github.com/kubevirt/kubevirt/blob/0514a664151863d901d90694feb08c86df0076bb/pkg/virt-operator/resource/generate/components/daemonsets.go#L105

**Comment by marceloamaral** [comment]
There are some discussion to use [HCO annotation](https://github.com/kubevirt/hyperconverged-cluster-operator/blob/main/docs/cluster-configuration.md#jsonpatch-annotations) to patch the controllers
For example:
```
kubectl annotate --overwrite -n kubevirt hyperconverged kubevirt-hyperconverged kubevirt.kubevirt.io/jsonpatch='[                                                                                                                                                                        {                                                                                            
      "op":"add",
      "path":"/spec/customizeComponents/flags",
      "value": { "handler": { additionalProperties:  "--max-devices 250"} }
]' 
```
However, [kubevirtci](https://github.com/kubevirt/kubevirtci) does use HCO to deploy Kubevirt Operator

**Comment by marceloamaral** [comment]
cc @rmohr @rthallisey @davidvossel @fgimenez
wdyt?

**Comment by rmohr** [comment]
@marceloamaral yes I think we should allow setting this on the `KubeVirt` CR in an easy fashion.

In the meantime: HCO uses a patch mechanisms which is built into `KubeVirt` CR. You can define patches directly in the KubeVirt CR. See this PR for details: https://github.com/kubevirt/kubevirt/pull/3612

It is a slightly hidden feature, but I hope it helps.

**Comment by davidvossel** [comment]
can we easily detect the per node pod limit and use that as our VMI limit?

**Comment by marceloamaral** [comment]
I created the PR #6098 to detect the per node pod limit and use that as our VMI limit
