### ISSUE TITLE
Establish predictable community release and support patterns

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#6087]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind enhancement

Establish predictable community release and support patterns. Release x will receive backports for y weeks/months before requiring to update to release z. Explicitly define why backports happen and what criteria they must meet.

- Define a deprecation policy - we need to be clear about things that might be removed in the future. We could use Kubernetes deprecation policy as an example to build ours.

**Comment by fabiand** [comment]
Reviving this in order to consciously decide how the release schedule can look for v1 and beyond

**Comment by rthallisey** [comment]
I think with https://github.com/kubevirt/kubevirt/issues/6087 we can close.

**Comment by xpivarc** [comment]
> I think with #6087 we can close.

* https://github.com/kubevirt/kubevirt/pull/8366
