### ISSUE TITLE
Templating mechanism for VMs

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#6089]
**Is this a BUG REPORT or FEATURE REQUEST?**:
 /kind enhancement

Templating mechanism for VMs to abstract away API complexities from users. Something similar to what we get OpenShift templating
- Document recommendation VMI specs for common use cases like Windows.

**Comment by phoracek** [comment]
Bug scrub: This needs a bigger discussion. We need to see if we need anything more than existing alternatives (e.g. Helm)

@fabiand would you please join one of the next community calls to defend this?

**Comment by iholder-redhat** [comment]
Discussions are on-going.

/remove-lifecycle stale
