### ISSUE TITLE
Spelling Error in CRD description

### ISSUE THREAD

**Issue by christopherhein** [kubevirt/kubevirt#6125]
**Is this a BUG REPORT or FEATURE REQUEST?**:
Non-major - Bug/spelling

/kind bug

**What happened**:
We noticed while doing some code reviews that there is a spelling error in the types.go that ends up in the CRDs. 
```
// The vendor_id:product_id tupple of the PCI device
```
https://github.com/kubevirt/kubevirt/blob/33727f918b8462c55f0d7340a067f4ebfa351649/staging/src/kubevirt.io/client-go/api/v1/types.go#L1958

You'll notice `tupple` vs `tuple`.

**Comment by christopherhein** [comment]
cc @mlsorensen for visibility.

**Comment by ansijain** [comment]
this issue is fixed in https://github.com/kubevirt/kubevirt/pull/6138 
kindly validate and close the issue
