### ISSUE TITLE
VMI doesn't show IO error when its access to boot disk is blocked. 

### ISSUE THREAD

**Issue by lzang** [kubevirt/kubevirt#6126]
/kind bug

**What happened**:

When a VM cannot access its boot disk, the VMI shows the following without the actual reason of failure, i.e the IO error
```
  Warning  SyncFailed        1s (x16 over 5m2s)  virt-handler               unknown error encountered sending command SyncVMI: rpc error: code = DeadlineExceeded desc = context deadline exceeded
```
**What you expected to happen**:
The VMI is paused with the event indicating the IO error. This is the behavior in v0.40.0.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a VM using a NFS storage for its boot disk. 
2. Create an iptable rule on the nfs server to block the access to the NFS storage from the node where the VM is on. 

**Anything else we need to know?**:

virt-launcher log doesn't show any error. Virt-handler log is filled with the following:
```
{"component":"virt-handler","level":"info","msg":"Processing event default/vm2","pos":"vm.go:1554","timestamp":"2021-07-27T00:46:38.090736Z"}
{"component":"virt-handler","kind":"","level":"info","msg":"VMI is in phase: Running\n","name":"vm2","namespace":"default","pos":"vm.go:1556","timestamp":"2021-07-27T00:46:38.090779Z","uid":"22e0184e-c6c2-4b25-9b4f-3e1fd24994d1"}
{"component":"virt-handler","kind":"Domain","level":"info","msg":"Domain status: Running, reason: Unknown\n","name":"vm2","namespace":"default","pos":"vm.go:1561","timestamp":"2021-07-27T00:46:38.090805Z","uid":""}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"vm2","namespace":"default","pos":"vm.go:1693","reason":"unknown error encountered sending command SyncVMI: rpc error: code = DeadlineExceeded desc = context deadline exceeded","timestamp":"2021-07-27T00:46:58.094210Z","uid":"22e0184e-c6c2-4b25-9b4f-3e1fd24994d1"}
{"component":"virt-handler","level":"info","msg":"re-enqueuing VirtualMachineInstance default/vm2","pos":"vm.go:1350","reason":"unknown error encountered sending command SyncVMI: rpc error: code = DeadlineExceeded desc = context deadline exceeded","timestamp":"2021-07-27T00:46:58.099108Z"}
```

**Environment**:
- KubeVirt version (use `virtctl version`): 0.43.0
- Kubernetes version (use `kubectl version`): v1.20.8
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu 20.04
- Kernel (e.g. `uname -a`): 5.4.0
- Install tools:
- Others:

**Comment by phoracek** [comment]
Bug scrub: It sounds like virt-launcher is stuck trying to connect to NFS. This could/should be probably improved with a timeout and a meaningful error.
