### ISSUE TITLE
VMI Failed for GPU A40: Could not open '/var/run/kubevirt-ephemeral-disks/cloud-init-data/default/vmi-gpu/noCloud.iso': Invalid argument'

### ISSUE THREAD

**Issue by vaibhavraizada-hcl** [kubevirt/kubevirt#6130]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
    /kind bug
> /kind enhancement

**What happened**:
Tried to create a VM Instance but it failed. Output of command `kubectl describe vmi vmi-gpu` is below:

"LibvirtError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2021-07-27T04:19:23.102128Z qemu-kvm: -blockdev {\"driver\":\"file\",\"filename\":\"/var/run/kubevirt-ephemeral-disks/cloud-init-data/default/vmi-gpu/noCloud.iso\",\"node-name\":\"libvirt-1-storage\",\"cache\":{\"direct\":true,\"no-flush\":false},\"auto-read-only\":true,\"discard\":\"unmap\"}: file system may not support O_DIRECT\n2021-07-27T04:19:23.102198Z qemu-kvm: -blockdev {\"driver\":\"file\",\"filename\":\"/var/run/kubevirt-ephemeral-disks/cloud-init-data/default/vmi-gpu/noCloud.iso\",\"node-name\":\"libvirt-1-storage\",\"cache\":{\"direct\":true,\"no-flush\":false},\"auto-read-only\":true,\"discard\":\"unmap\"}: **Could not open '/var/run/kubevirt-ephemeral-disks/cloud-init-data/default/vmi-gpu/noCloud.iso': Invalid argument'**)"

This VM instance needs access to Nvidia GPU Card A40 hence I am using nvidia's kubevirt-gpu-device-plugin.

**What you expected to happen**:

Successful launch of VMI.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install kubevirt v 0.35.0
2. Install nvidia-kubevirt-gpu-plugin v 1.0.1

3. Create a VM instance with below specification:

apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-gpu
  name: vmi-gpu
spec:
  domain:
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      gpus:
      - deviceName: nvidia.com/2235
        name: gpu1
      rng: {}
    machine:
      type: ""
    resources:
      requests:
        memory: 1024M
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: ovaleanu/centos:latest
    name: containerdisk
  - cloudInitNoCloud:
      userData: |-
        #cloud-config
        ssh_pwauth: True
        password: centos
        chpasswd: { expire: False }
    name: cloudinitdisk

4. Run command: `kubectl describe vmi vmi-gpu`.
Above command gives the error. And Status of VMI is failed.

**Anything else we need to know?**:

Host device Nvidia GPU A40.

**Environment**:
- KubeVirt version (use `virtctl version`): 0.35.0
- Kubernetes version (use `kubectl version`): 1.21
- VM or VMI specifications: VM has two Nvidia GPU A40 and two Nvidia GPU Tesla T4.
- Cloud provider or hardware configuration: 
- OS (e.g. from /etc/os-release): Centos 8
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by phoracek** [comment]
@vaibhavraizada-hcl would you please check whether this reproduces without GPU config too? So we can better triage this issue.
