### ISSUE TITLE
Remove serial unix file host shared mount

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#614]
#613 Had to introduce a host shared mount directory to pass the serial console's unix socket from the libvirt container to the VM Pod.

This needs to go away as soon as the libvirt redesign is absorbed by KubeVirt.

**Comment by fabiand** [comment]
@davidvossel does this issue still apply to the current state?

**Comment by davidvossel** [comment]
serial and vnc unix sockets are now private per pod
