### ISSUE TITLE
some methods are missing a namespace parameter in openapi-spec swagger.json file

### ISSUE THREAD

**Issue by aghandoura** [kubevirt/kubevirt#6142]
Using java swagger code gen to generate a java kubevirt client from openapi-spec swagger.json file
The following methods do not have a namespace parameter.
deleteCollectionNamespacedVirtualMachines
deleteCollectionNamespacedVirtualMachinesInstance
deleteCollectionNamespacedVirtualMachinesInstanceMigration
...

shouldn't be a namespace parameter in the swagger.json for these methods?

I see this with kubevirt 0.41

**Comment by phoracek** [comment]
We probably should fix this.
