### ISSUE TITLE
[Sig-scale] KubeVirt modules are using more cpu than requested

### ISSUE THREAD

**Issue by marceloamaral** [kubevirt/kubevirt#6144]
/kind enhancement

**What happened**:
Kubevirt virt-operator has some configured alerts to show if the controllers are using more CPU or Memory than requested.
https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-operator/resource/generate/components/crds.go#L946
https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-operator/resource/generate/components/crds.go#L934

Requests affect how the pods are scheduled in Kubernetes.

In the[ following experiment](https://docs.google.com/document/d/1S38AuKl_J2ZcbuN7H3YH9n9sLr2Az6fvQXikBiKy_SM/edit#heading=h.5x0d5h95i329), I create n VMIs, wait until they are all running, delete n VMIs, wait until they are all deleted, sleep 10mim, and repeat. Scenarios creating 10, 20, 40, 60, 80, 100, 200, 300 VMIs shows an increase mismatch in the CPU request and usage for `virt-api`, `virt-controller` and `virt-handler`.

![image](https://user-images.githubusercontent.com/5133121/127316516-23d7050c-e4f1-4fc5-977a-9e49cd406659.png)

**Comment by phoracek** [comment]
This should be discussed on the SIG Scale community meeting tomorrow.

**Comment by fabiand** [comment]
Cool to see this identified. Are there plans to address this?

**Comment by marceloamaral** [comment]
/remove-lifecycle rotten

We still need to increase the requested resources

**Comment by iholder-redhat** [comment]
/cc

As explain in depth in [this comment](https://github.com/kubevirt/kubevirt/issues/7101#issuecomment-1135609450), I think that the right path forward is scaling, not raising the resources requested by our components.

Also, as explained in the comment linked above, the alert that you're speaking about is very misleading. I've [once claimed it should be removed altogether](https://github.com/kubevirt/kubevirt/pull/6977), but we ended up keeping it. The reason it's misleading is that it is perfectly fine for pods to exceed their cpu request. It _could be_ just a minor indication (that's not always true) that scaling is needed, but it doesn't mean that something's inherently wrong.
