### ISSUE TITLE
Error starting VirtualMachine Unauthorized

### ISSUE THREAD

**Issue by yuchunyun** [kubevirt/kubevirt#6165]
**What happened**:
virtctl start testvm      
Error starting VirtualMachine Unauthorized

**How to reproduce it (as minimally and precisely as possible)**:
kubectl apply -f https://raw.githubusercontent.com/kubevirt/kubevirt.github.io/master/labs/manifests/vm.yaml

[root@rancher-141 vm]# kubectl get VirtualMachine 
NAME     AGE   VOLUME
testvm   12m   
[root@rancher-141 vm]# virtctl start testvm              
Error starting VirtualMachine Unauthorized

**Environment**:
- KubeVirt version (use `virtctl version`): v0.41.2
- Kubernetes version (use `kubectl version`): v1.20.9

**Comment by phoracek** [comment]
@yuchunyun it seems that your user is not inheriting the default RBAC roles. Would you please check http://kubevirt.io/user-guide/operations/authorization/#kubevirt-default-rbac-clusterroles and see if it helps you setting this up?

**Comment by hamidrezash2000** [comment]
I had the same issue, would you please explain how you resolved this issue step by step.
