### ISSUE TITLE
Add RBAC profile

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#62]
By default Kubernetes authorization is pretty open. However, Kubernetes does support RBAC, which is more fine grained.

This issue is about adding a sane set of Roles covering the core KubeVirt objects.

```release-note
A simple RBAC profile got added
```

See https://kubernetes.io/docs/admin/authorization/rbac/

**Comment by rmohr** [comment]
@fabiand I guess you have https://kubernetes.io/docs/admin/authentication/#users-in-kubernetes in mind?

**Comment by fabiand** [comment]
Rather https://kubernetes.io/docs/admin/authorization/

**Comment by fabiand** [comment]
This is also need to run KubeVirt on OpenShift

**Comment by fabiand** [comment]
See also #301
