### ISSUE TITLE
NoReadyVirtOperator alert and VirtOperatorDown alert are the same

### ISSUE THREAD

**Issue by sradco** [kubevirt/kubevirt#6229]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
`NoReadyVirtOperator` alert and `VirtOperatorDown` alert are the same
If there are no Virt operators then both alerts will fire. It will cause duplicate alerts.

**What you expected to happen**:
We should only have one of the alerts

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by davidvossel** [comment]
@sradco Which alert do you think we should keep? Is there one that's more consistent with other component alerts?

**Comment by sradco** [comment]
@davidvossel  We should keep VirtOperatorDown, since its more consistent. 
We use "Down" when we base the alert on the "up" metric. For "Ready" alerts we use dedicated ready metrics. 

I believe we just need to update the "NoReadyVirtOperator" alert with this expression: "kubevirt_virt_operator_ready_total == 0"
