### ISSUE TITLE
is ivshmem device supported in kubevirt 0.37.2?

### ISSUE THREAD

**Issue by gidde8** [kubevirt/kubevirt#6239]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:

We are using kubevirt version 0.37.2 along with k3s. 
Our requirement is to have ivshmem device attached the VM . 
We see that ivshmem is not supported in this version kubevirt. 

<test_pod># libvirtd --version 
libvirtd (libvirt) 6.6.0

<test_pod># /usr/libexec/qemu-kvm  --version 
QEMU emulator version 5.1.0 (qemu-kvm-5.1.0-16.fc32)
Copyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers

<test_pod># /usr/libexec/qemu-kvm -device ivshmem-plain,memdev=hostmem
qemu-kvm: -device ivshmem-plain,memdev=hostmem: 'ivshmem-plain' is not a valid device model name

However, We have downloaded qemu 5.1.0 source code and compiled. Seems ivshmem is enabled there. 

[root@centos-vm2 qemu-5.1.0]# x86_64-softmmu/qemu-system-x86_64 --version
QEMU emulator version 5.1.0
Copyright (c) 2003-2020 Fabrice Bellard and the QEMU Project developers
[root@centos-vm2 qemu-5.1.0]#

[root@centos-vm2 qemu-5.1.0]# x86_64-softmmu/qemu-system-x86_64 -device ivshmem-plain,memdev=hostmem
qemu-system-x86_64: -device ivshmem-plain,memdev=hostmem: Device 'hostmem' not found
[root@centos-vm2 qemu-5.1.0]#

**What you expected to happen**:

ivshmem device support in kubevirt 0.37.2 version. 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Please let us know if any configuration need to be added to enable ivshmem for kubevirt. 

**Environment**:
- KubeVirt version (use `virtctl version`):  [root@appliance-1 ~]# virtctl version
Starting to serve on 127.0.0.1:8080
Client Version: version.Info{GitVersion:"", GitCommit:"d1ca2117f85c795772667101fa8819a2337c032a", GitTreeState:"dirty", BuildDate:"2021-07-13T16:10:43Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"", GitCommit:"d1ca2117f85c795772667101fa8819a2337c032a", GitTreeState:"dirty", BuildDate:"2021-07-13T16:10:43Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
[root@appliance-1 ~]#
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s-cd32b0af-dirty", GitCommit:"cd32b0af2b374d494715b1aed3c65982dcb7d608", GitTreeState:"dirty", BuildDate:"2021-06-23T13:50:
22Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1+k3s-cd32b0af-dirty", GitCommit:"cd32b0af2b374d494715b1aed3c65982dcb7d608", GitTreeState:"dirty", BuildDate:"2021-06-23T13:50:
22Z", GoVersion:"go1.15.2", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`): 
- Install tools: 
- Others:

**Comment by vladikr** [comment]
Hello,

`ivshmem-plain` and `ivshmem-doorbell` are supported in qemu - these are different from the deprecated ivshmem device.
 I wonder what is the use case for enabling this in KubeVirt?

**Comment by CrossainQi** [comment]
> Hello,
> 
> `ivshmem-plain` and `ivshmem-doorbell` are supported in qemu - these are different from the deprecated ivshmem device. I wonder what is the use case for enabling this in KubeVirt?

Have you successfully use ivshmem feather in kubevirt? Can you provide me a use case?
