### ISSUE TITLE
The cluster up script does not sync between kubevirt project and kubevirt ci project

### ISSUE THREAD

**Issue by zhlhahaha** [kubevirt/kubevirt#6246]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind bug

**What happened**:
Recently I am doing migration test on ARM64 server by using kind-k8s-1.17 provider. I found the script are not sync between kubevirt project and kubevirt ci project.
e.g. In kubevirt project, the kind provider uses calico CNI, while in kubevirtci project it uses kind default CNI.

Are there any particular reasons for this?

**Comment by davidvossel** [comment]
there's a daily job that syncs kubevirtci with the kubevirt/kubevirt repo. We use a PR to sync the repo to make sure CI passes with the new cluster-up changes before the changes are committed.

**Comment by zhlhahaha** [comment]
> there's a daily job that syncs kubevirtci with the kubevirt/kubevirt repo. We use a PR to sync the repo to make sure CI passes with the new cluster-up changes before the changes are committed.

Thank
