### ISSUE TITLE
console/vnc libvirt share directory race condition

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#626]
#618 has a race condition that is hit when a VM with the same namespace/name is deleted and recreated immediately.  When this happens, it's possible virt-handler will cleanup a directory the shared between the new VM pod and libvirt. 

The fix for this race condition remove the vnc/console unix sock share directory entirely. This will happen once qemu is launched directly into the VM pod.

**Comment by davidvossel** [comment]
another option for fixing this is to use a finalizer on the VM object and use the VM's UID in the shared directory path.

**Comment by fabiand** [comment]
Is this still relevant, @davidvossel ?

**Comment by davidvossel** [comment]
yep, fixed.
