### ISSUE TITLE
Can emptyDisk be shared with other containers in the VM pod?

### ISSUE THREAD

**Issue by Cerebus** [kubevirt/kubevirt#6264]
Is there a storage driver or other way to share a VMI emptyDisk with another container in the pod?

The general use case is the sidecar pattern.  For example, I could integrate VM logs into my cluster solution:

- VMI with emptyDisk mounted on /var/log
- Sidecar running a log forwarder (filebeat, fluent-bit, etc)

Sidecars are an essential part of k8s flexibility, and the ability to embrace & extend VMs could be very important for migrating traditional services.

**Comment by davidvossel** [comment]
For your use case, would it be reasonable to use a Pod mutation webhook to add the volume mountpoint to the side car container?
