### ISSUE TITLE
Build executables on the same environment used for running

### ISSUE THREAD

**Issue by krsacme** [kubevirt/kubevirt#628]
While building on F27 and deploying, the virt-handler pod fails to start, with below error message

```
/virt-handler: /lib64/libvirt.so.0: version `LIBVIRT_3.7.0' not found (required by /virt-handler)
/virt-handler: /lib64/libvirt.so.0: version `LIBVIRT_3.4.0' not found (required by /virt-handler)
```
Following are the steps used:
On the host F27, execute the following commands
```
cd $GOPATH/src/kubevirt.io/kubevirt
vagrant up
make vagrant-deploy
```
The virt-handler is built using F27 which is referring to higher libvirt-libs version, where as the docker image is built on top of F26 with libvirt-libs-3.2.1-7.fc26 version. 

Modifying the virt-handler Dockerfile to F27 is working fine, but wondering if there is a better solution - to use the same os version to build on which it will be deployed.

**Comment by rmohr** [comment]
@krsacme thanks for the report. You are right we need to finally make that a consistent flow.

To immediately help you out: You can change the base image for cmd/virt-handler/Dockerfile to fedora 27.

**Comment by rmohr** [comment]
> To immediately help you out: You can change the base image for cmd/virt-handler/Dockerfile to fedora 27.

Oh, you did that already. :+1:

**Comment by rmohr** [comment]
We will probably get away with a completely dockerized build where we control the versions. Another thought I carry around with me for some time is to use https://github.com/digitalocean/go-libvirt bindings, which are go-only. Now that the libvirt RPC protocol is considered to be stable, it is a good option to remove pretty much all rpm dependencies from the whole project (except for the libvirt daemon container itself).

**Comment by krsacme** [comment]
> We will probably get away with a completely dockerized build where we control the versions.

Yes, this is something that I was also thinking off of way forward.

> thought I carry around with me for some time is to use https://github.com/digitalocean/go-libvirt bindings, .. it is a good option to remove pretty much all rpm dependencies from the whole project (except for the libvirt daemon container itself).

Looks interesting.
