### ISSUE TITLE
UUID in CloudInitConfigDrive metadata is changed by VMI's uid which may cause cloudinit redo when VMI recreates

### ISSUE THREAD

**Issue by LLLLLBJ** [kubevirt/kubevirt#6305]
https://github.com/kubevirt/kubevirt/blob/f7b8dcf1655e4296d15736da69d6fedda7a77b2d/pkg/cloud-init/cloud-init.go#L130

**Comment by davidvossel** [comment]
> Can UUID in meta-data.json be set to vmi.Spec.Domain.Firmware.UUID

sounds reasonable

> And use vmi name.namespace to generate vmi.Spec.Domain.Firmware.UUID not only vmi name

also sounds reasonable
