### ISSUE TITLE
[Sig-Scale] Continuous Performance Evaluation of KubeVirt Control Plane in the CI/CD System

### ISSUE THREAD

**Issue by marceloamaral** [kubevirt/kubevirt#6309]
## Motivation:
Code changes may affect system performance and scalability. The goal is to design and create performance/scalability tests that can run periodically and on-demand for each PR and each new Release.

## Tests Types:
- [ ] (i) Burst Density test, creating absolute # of VMIs (Showing how system’s behavior during normal operations)
   - Test Scenarios:
      - [x] Small-scale -> creating 100 VMIs (Daily) - https://github.com/kubevirt/kubevirt/pull/6076
      - [ ] Small-scale -> creating 100 VMIs (for each PR)
         - [ ] Replace the previous test to run for each PR instead of daily
         - [ ] Replace the previous test implementation with the PerfScale Load Generator Tool https://github.com/kubevirt/kubevirt/pull/6191
         - [ ] Replace the previous test to run in the dedicated PerfScale cluster
         - [ ] Gather performance metrics and create alerts if the latency is higher than a threshold https://github.com/kubevirt/kubevirt/pull/6035
      - [ ] Medium-scale -> creating 1k VMIs (Daily)
      - [ ] Large-scale -> creating 10k or more VMIs (for each new release)
- [ ] (ii) Steady State Density test, creating constant # of VMI/s (Showing how system’s behavior during under heavy load)
   - TBD

**Comments:**
> Since the goal of the tests here is to stress the KubeVirt control plane, the focus is to create as many VMIs as possible in a Node. To be able to do that, we will use a tiny OS image allocating the minimal resource to create a VMI, but not enough resources to boot the OS. All the components related to the VMI will be created and will generate all the needed requests to the control plane. Finally, Kubernetes follows a similar direction faking the creation of Pods with [Kubemark](https://github.com/kubernetes/community/blob/master/contributors/devel/sig-scalability/kubemark-guide.md).

The implementation of the tests is related to https://github.com/kubevirt/kubevirt/issues/5878.

## Observability
- [x] Prepare infra for collecting metrics from e2e performance tests https://github.com/kubevirt/project-infra/issues/1211
- [ ] Configure infra with [Thanos](https://github.com/thanos-io/thanos) for collecting the aggregated metrics from the tests in a single point
- [ ] Define relevant metrics related to KubeVirt control plane https://github.com/kubevirt/kubevirt/issues/5732
   - [x] Create and document [a set of well-define metrics](https://docs.google.com/document/d/1KopUQkXFTu9_9ljSBVPyhUpInGHmcI9u-XvPC7Gh7Qw/edit?usp=sharing)
   - [x] Create and document [thresholds (i.e., SLOs)]( https://docs.google.com/document/d/1sw4SLduTJ-am6_34bvzUboZMOMWcynmY-_Yj3JPmeZU/edit?usp=sharing) for the control-plane e2e perf tests
- [ ] Create a Grafana Dashboard showing control plane metrics related
- [ ] Set up Grafana dashboards based on Prometheus/Thanos data

## Infrastructure
- [x] Run the perf test in the same cluster the functional tests are running (with nested virtualization using [kubevirtci](https://github.com/kubevirt/kubevirtci)) https://github.com/kubevirt/kubevirt/pull/6076
- [x] Dedicated cluster without nested virtualization and job collocation for performance reasons
   - Kubernetes cluster 1.21 using [kubespray](https://github.com/kubernetes-sigs/kubespray) with [crio](https://github.com/kubernetes-sigs/kubespray/blob/master/docs/cri-o.md) runtime, 3 master and 3 worker nodes
      - [IBM BMs](https://www.ibm.com/cloud/bare-metal-servers) with 48 Intel Xeon 8260 CPUs, 128GB and 10Gbps.

/kind enhancement

Signed-off-by: Marcelo Amaral marceloamaral1@ibm.com

**Comment by rthallisey** [comment]
/close
Closing for now.  We spending a bunch of work on reporting results then we can return to this.
