### ISSUE TITLE
virtctl does not work with kubectl proxy

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#632]
I used `kubectl proxy` to proxy request to a minikube instance.

With the v0.2.0 virtctl I am not able to create a connection:

```
$ ./virtctl console -s http://127.0.0.1:8001 testvm
Escape sequence is ^]unable to upgrade connection: <h3>Unauthorized</h3>
```

I'm seeing the issue with this branch:
https://github.com/kubevirt/demo/pull/30

**Comment by rmohr** [comment]
That is the default behaviour of `kubectl proxy`. Try to run it like this: `kubectl proxy --disable-filter=true`.

**Comment by fabiand** [comment]
Thanks. Disabling the filter leads to:

```
$ ./virtctl-v0.2.0-linux-amd64 console -s http://127.0.0.1:8001 testvm
Escape sequence is ^]Upgrade request required
```

**Comment by fabiand** [comment]
Which is different and might actually be a code issue (not auth anymore)

**Comment by rmohr** [comment]
Looks very similar to: https://github.com/kubernetes/kubernetes/issues/32026. Does `kubectl exec` to an arbitrary pod work? If yes, either our code, or client-go does something wrong.

**Comment by fabiand** [comment]
Yes, and Kubernetes 1.9 fixes it.

**Comment by fabiand** [comment]
Thanks

**Comment by fabiand** [comment]
@davidvossel please add a note to the user-guide documentation feature matrix and increasing the min version to 1.9

**Comment by fabiand** [comment]
Fixed in the user guide in https://github.com/kubevirt/user-guide/commit/fc175954abfac46c567e6632bf5f068418e3eaca
