### ISSUE TITLE
Build a public roadmap and mechanism to maintain it

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#6322]
/kind enhancement

**What happened**: Trying to gain insights into KubeVirt's roadmap

**What you expected to happen**: Have some way to see what is coming up in KubeVirt

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

We want to establish a mechanism to allow users and developers to gain an insight into KubeVirt's roadmap, and at the same time allow developers to participate in building KubeVirt's roadmap.
Until today the collaboration is pretty loosely coupled, and developers are contributing features without much process.

The proposed mechanism to achieve this is
- Open GitHub Issues for high level work items that a contributor plans to work on
- Target the issue by using GitHub Milestones - https://github.com/kubevirt/kubevirt/milestones
- Refer to this GH Issue when working on PRs

With this loose approach, KubeVirt GH Milestones - https://github.com/kubevirt/kubevirt/milestones - will explicitly show the planned content for future but also previous versions.

**Comment by fabiand** [comment]
For example #6085, and #6083

**Comment by vielmetti** [comment]
This would be a welcome addition! 

Milestones can also have dates attached to them, so that any sort of project scheduling that's going to have a release target for a specific date can also be handled.

**Comment by xpivarc** [comment]
I think this will be much easier when we move to longer release cycles.
