### ISSUE TITLE
VM fails to create with SRIOV device

### ISSUE THREAD

**Issue by hem2** [kubevirt/kubevirt#6337]
/kind bug

**What happened**:
VM failed to create with SRIOV device. No issues creating pods with sriov VF (without kubevirt).
Issue is similar to https://github.com/kubevirt/kubevirt/issues/5811.

```{"component":"virt-launcher","level":"info","msg":"SR-IOV PCI device created: 0000:42:12.2","pos":"hostdev.go:67","timestamp":"2021-09-01T17:29:35.474916Z"}
{"component":"virt-launcher","level":"error","msg":"unsupported configuration: host doesn't support passthrough of host PCI devices","pos":"qemuHostdevPreparePCIDevicesCheckSupport:185","subcomponent":"libvirt","thread":"55","timestamp":"2021-09-01T17:29:36.744000Z"}
{"component":"virt-launcher","level":"error","msg":"unsupported configuration: pci backend driver 'default' is not supported","pos":"virHostdevGetPCIHostDevice:251","subcomponent":"libvirt","thread":"55","timestamp":"2021-09-01T17:29:36.747000Z"}
{"component":"virt-launcher","level":"error","msg":"Failed to allocate PCI device list: unsupported configuration: pci backend driver 'default' is not supported","pos":"virHostdevReAttachPCIDevices:1082","subcomponent":"libvirt","thread":"55","timestamp":"2021-09-01T17:29:36.747000Z"}
```

**What you expected to happen**:
VM created successfully

**How to reproduce it (as minimally and precisely as possible)**:
VM definition:
```          interfaces:
          - masquerade: {}
            name: default
          - name: enp66s0f0-intel-sriov-dpdk-device
            sriov: {}
      networks:
      - name: default
        pod: {}
      - multus:
          networkName: enp66s0f0-intel-sriov-dpdk-device
        name: enp66s0f0-intel-sriov-dpdk-device
```
Network attachment definition:
```    {
      "name": "enp66s0f0-sriov-dpdk-network",
      "cniVersion": "0.3.1",
      "type": "sriov",
      "ipam": {
        "type": "host-local",
        "subnet": "10.56.217.0/24",
        "rangeStart": "10.56.217.101",
        "rangeEnd": "10.56.217.200",
        "routes": [
          {
            "dst": "0.0.0.0/0"
          }
        ]
      },
      "gateway": "10.56.217.1"
    }
```
**Environment**:
Ubuntu 18.04, kubevirt v0.44.0, multus/sriov-cni/sriov-network-device-plugin latest from master and Calico v3.20. 
VT/sriov enabled in bios, both iommu and iommu_pt flags set to kernel.
PF is Intel's 82599ES with ixgbe driver. For vf, tried with both ixgbevf and vfio-pci as VF driver.

**Comment by phoracek** [comment]
Hello @hem2. The `sriov: {}` binding must be used with the vfio-pci passthrough mode of the SR-IOV CNI, the example you show would only work with Pods, not VMs. Have you checked [SR-IOV user-guide](https://kubevirt.io/user-guide/virtual_machines/interfaces_and_networks/#sriov)? It would be interesting to see what kind of error do you see when using the vfio mode.

**Comment by hem2** [comment]
@phoracek, I had my VFs bound to vfio_pci. Not sure what caused the issue, I'm unable to reproduce it now. 
Few things changed in my environment are, unbinding/binding the VF to VFIO-PCI again, reset sriov connections at the TOR switch, machine reboot, having just the "vfio-pci" in sriovdp-config.

Thank you for looking into it.

**Comment by lynn901** [comment]
I reproduce this in my environment
