### ISSUE TITLE
[Outreachy] Reduce memory overhead for virt-launcher

### ISSUE THREAD

**Issue by xpivarc** [kubevirt/kubevirt#6348]
**What happened**:
Kubevirt is running VM inside a Pod as any other application in Kubernetes. Other than the VM (the qemu process),  we are running virt-launcher which is responsible for interacting with libvirt, monitoring the qemu process, and also provides API for local virt-handler over GRPC. (More can be found [here](https://github.com/kubevirt/kubevirt/blob/main/docs/architecture.md))

As a side effect, VMs Pod needs additional memory on top of what the user requested (e.g for VM requesting 4G we need to add the small overhead of virt-launcher).

This issue is aiming to identify cases where we can reduce the overhead per each VM. 
One potential issue can be forking of the virt-launcher. Small purposely build binary for this purpose could reduce memory overhead. 
Other issues can be identified by standard tooling of Go(pprof).

/kind enhancement

**Comment by rthallisey** [comment]
Do you want to bring this up for discussion at SIG-scale?  SIG-scale is tracking https://github.com/kubevirt/kubevirt/issues/6368 which is for profiling Kubevirt under heavy load.  This issue has some overlap plus it touches on the topic of mem/cpu footprint, which plays a factor in scale.

**Comment by xpivarc** [comment]
@rthallisey I will try to attend.
