### ISSUE TITLE
Cirros image failed to start when memory is 128M on arm64

### ISSUE THREAD

**Issue by zhlhahaha** [kubevirt/kubevirt#6363]
This issue is used to track this known issues.

**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
When boot cirros on arm64 and set memory to 128M, get following error message:
```
EFI stub: Booting Linux Kernel...
EFI stub: EFI_RNG_PROTOCOL unavailable, no randomness supplied
EFI stub: ERROR: Failed to relocate kernel
EFI stub: ERROR: Failed to relocate kernel
```

**Anything else we need to know?**:
This issue only happens on ARM64 and is not related to kubevirt. Boot cirros VM directly via qemu-kvm on arm64 server would also get this error.

**Comment by mazzystr** [comment]
https://github.com/kubevirt/kubevirt/pull/6639
