### ISSUE TITLE
[SIG-scale] Profile KubeVirt control plane under high load

### ISSUE THREAD

**Issue by rthallisey** [kubevirt/kubevirt#6368]
/kind enhancement

Stress the KubeVirt control plane and profile the virt-api, virt-handler, virt-controller, and virt-launcher code to locate any scale or performance bottlenecks.  Here are the steps to run for each test:
1) Start profiling a component https://github.com/kubevirt/kubevirt/pull/6211
2) Generate load https://github.com/kubevirt/kubevirt/pull/6191
3) Remove load
4) Analyze

### Stress tests
- [ ] VMIs
  - [ ] 300
  - [ ] 500
  - [ ] 1000
- [ ] nodes
  - [ ] 10
  - [ ] 50
  - [ ] 100
  - [ ] 200
  - [ ] infinity*

**Comment by knopt** [comment]
^
