### ISSUE TITLE
Starting a VM fails if IPv6 is disabled on the k8s node/cluster

### ISSUE THREAD

**Issue by fdupont-redhat** [kubevirt/kubevirt#6373]
/kind bug

**What happened**:

In a Kubernetes where IPv6 is disabled, both at the k8s and the nodes level, starting a virtual machine fails with the following error message in the virt-launcher pod.

```
{"component":"virt-launcher","level":"error","msg":"failed to run DHCPv6","pos":"common.go:373","reason":"couldn't create DHCPv6 server: Failed creating connection for dhcpv6 server: cannot get a UDP socket: address family not supported by protocol","timestamp":"2021-09-08T10:33:28.712094Z"}
```

It looks like it's trying to create a DHCPv6 server, even though IPv6 is disabled, and that fails.

**What you expected to happen**:

I would expect virt-launcher to not try to start the DHCPv6 when IPv6 is not enabled on the node where the VM is scheduled.

**How to reproduce it (as minimally and precisely as possible)**:

Disable IPv6 on the nodes, setting the following sysctl:

```
net.ipv6.conf.all.disable_ipv6 = 1
net.ipv6.conf.default.disable_ipv6 = 1
```

Disable IPv6 at the Kubernetes level, by setting the `IPv6DualStack` feature gate to `false`, according to https://kubernetes.io/docs/concepts/services-networking/dual-stack.

Finally, create a VM and try to start it:

```
$ kubectl apply -f https://kubevirt.io/labs/manifests/vm.yaml
$ virtctl start testvm
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.45.0-rc.0-dirty
- Kubernetes version (use `kubectl version`): v1.21.1
- VM or VMI specifications: https://kubevirt.io/labs/manifests/vm.yaml
- Cloud provider or hardware configuration: Bare metal nodes
- OS (e.g. from /etc/os-release): CentOS 8
- Kernel (e.g. `uname -a`): 4.18.0-240.22.1.el8_3.x86_64
- Install tools: kubeadm

**Comment by alonSadan** [comment]
Hi @fdupont-redhat 
I didn't manage to fully recreate your bug on my local env on a minikube cluster. The vmi was succefully created. 
But, I did check the logs and I saw : 
```
 kubectl logs  virt-launcher-testvm-f7hv9 -c compute | grep DHCPv6
{"component":"virt-launcher","level":"info","msg":"Starting SingleClientDHCPv6Server","pos":"serverv6.go:44","timestamp":"2021-09-30T12:36:35.168958Z"}
```
I validated ipv6 is disabled k8s-wise and nodes-wise.
 
It means it did try to create the DHCP6, which is a bug on it's own and I will post a patch later to fix it.

I am still wondering  about the vmi failing to create. Can you recall of there is something else on your env that might have caused  
it to fail?
