### ISSUE TITLE
Cloud not use kubevirt.io/client-go/kubecli - openshift unknown revision v0.0.0

### ISSUE THREAD

**Issue by PendaGTP** [kubevirt/kubevirt#6393]
> /kind bug

**What happened**:
I try to use the go client but I fail to install the kubevirt.io/client-go module : 
```
go get kubevirt.io/client-go/kubecli

go get: kubevirt.io/client-go@none updating to
        kubevirt.io/client-go@v0.45.0 requires
        kubevirt.io/containerized-data-importer@v1.36.0 requires
        github.com/openshift/api@v0.0.0: reading github.com/openshift/api/go.mod at revision v0.0.0: unknown revision v0.0.0
```
I'm a new Go user, sorry if this problem is directly related to my use of Go and not kubevirt.io/client-go. 

**How to reproduce it (as minimally and precisely as possible)**:
```
docker run --rm -it golang:1.16 `go get kubevirt.io/client-go/kubecli` 
```

**Environment**:
- Go : go1.16.8 linux/amd64

**Comment by rmohr** [comment]
It is really difficult right now to use our client-go/kubevirt library with the right dependencies. You will probably have to override some `go.mod` dependencies in your project to make this work.

We just discussed in todays community meeting that we need to improve the flow here.

**Comment by rmohr** [comment]
/kind bug
/kind enhancement
/triage accepted

Adding the bug label here too because it is almost impossible right now to make a proper use of kubevirt/client-go.

**Comment by rmohr** [comment]
Quite some progress was made here. See https://github.com/kubevirt/api#readme.

Could you check if that is siffuicient for you?

**Comment by rmohr** [comment]
/close

Addressed via https://github.com/kubevirt/api
