### ISSUE TITLE
Add possibility to remove monitoring process in `virt-launcher` or reduce its memory footprint

### ISSUE THREAD

**Issue by VirrageS** [kubevirt/kubevirt#6397]
/kind enhancement

Currently, by default, `virt-launcher` starts as monitoring process which then creates actual `virt-launcher` process. The monitoring process watches the subprocess and other subprocesses and reacts if something happens. This monitoring mechanism is controlled by `no-fork` flag - initially it is set to `false` and monitoring process sets it to `true` when starting `virt-launcher` process.

The monitoring process has the same exact code and dependecies as the `virt-launcher`. This results in high memory usage (16M peak) for a simple process that has 1 goroutine and just waits for something to happen. In large scale this 16M is multiplied by the number of `virt-launcher` pods on node what can sum up to pretty significant memory usage on the node.

Therefore, in our case we decided to drop the monitoring process by setting `no-fork` flag to `true`. But this results in incomplete code because we then no longer have implementation that would watch `qemu` processes and acknowledge their exits/failures. And if we don't have this implementation this will result in zombie processes. And in the end this results in regression in VMI deletion time. So to make it work correctly we had to basically add similar implementation as in `ForkAndMonitor` function that would just work in the main `virt-launcher` process. After some time we managed it to work but:
* `no-fork` flag suggests as if setting it to `true` would just eliminate the monitoring process and everything should just work correctly but this is not the case. The flag is just used to tag the non-monitoring process to take a different execution path.
* Overall the monitoring process can take a lot of memory considering how little it does.

I would like to ask for re-evaluation of monitoring process (do we reallyy need this?). And if we do, could we significantly reduce the footprint of the memory it uses? Also the `no-fork` flag requires rewording as far for what it does or the implementation for tagging the non-monitoring process should change (maybe the env variable)?

**Comment by xpivarc** [comment]
I think this relates to https://github.com/kubevirt/kubevirt/issues/6348

**Comment by VirrageS** [comment]
Oh, yes, it is definitely related, I haven't noticed this issue before, thanks! My issue focuses a little bit more on the `virt-launcher` forking itself but I think we are fighting for the same thing :D
