### ISSUE TITLE
kubevirt_vmi_phase_count metric missing "phase" label

### ISSUE THREAD

**Issue by pbxqdown** [kubevirt/kubevirt#6412]
**Is this a BUG REPORT or FEATURE REQUEST?**: 
/kind bug

**What happened**:
Sometimes kubevirt_vmi_phase_count metric doesn't have "phase" label. This causes the vm-phase-count dashboard behaves incorrectly: 
<img width="610" alt="kubevirt-upgrade-lost-running-count" src="https://user-images.githubusercontent.com/6386150/133349520-2819e964-2ce0-474a-a524-a05e52c7bbdb.png">

**What you expected to happen**:
All kubevirt_vmi_phase_count metrics should have phase label included.

**How to reproduce it (as minimally and precisely as possible)**:
The metrics may lose the label after a handler restarts.

**Anything else we need to know?**:
This issue happens on one production environment of NVIDIA datacenter.
@rthallisey for viz

**Environment**:
- KubeVirt version (use `virtctl version`): release-0.35
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by mazzystr** [comment]
@rthallisey `release-0.35` is fairly old.  Can they update?  Or is this something that you can handle?

**Comment by erkanerol** [comment]
cc: @sradco

**Comment by pbxqdown** [comment]
Is this issue observed on latest Kubevirt version? It looks like vm related metrics undergoes large code-refactor since release-0.35. vms/prometheus folder is replaced with vmistats folder.
https://github.com/kubevirt/kubevirt/blob/main/pkg/monitoring/vmistats/collector.go#L100
Not sure whether the issue is fixed during release upgrade.

**Comment by fossedihelm** [comment]
@rthallisey @pbxqdown I tried to reproduce this without success. Are you able to give an update if it persist, and in case how to reproduce it, please? Thanks

**Comment by rthallisey** [comment]
We would see this happens after the virt-controller restarts.  Try deleting the virt-controller while creating and deleting VMIs.

**Comment by fossedihelm** [comment]
Thanks @rthallisey I tried as you suggest but I cannot see missing phase. What I notice is that there are no data while virt-controller is being recreated, but I think this is because there are no metrics sent in that period.
![image](https://user-images.githubusercontent.com/4507192/163179877-b819d226-2df3-4852-a7f3-48892a6aaf50.png)

**Comment by rthallisey** [comment]
I think it's ok to close then @fossedihelm.  If we see it again we can always reopen.  Thanks for having a look
