### ISSUE TITLE
How to run mac vm in kubevirt?

### ISSUE THREAD

**Issue by Animezjy** [kubevirt/kubevirt#6417]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:

> /kind enhancement

**What happened**:
How to run mac vm in kubevirt?

1. According to https://github.com/kholia/OSX-KVM.git
This project completed the installation of macOS in kvm
But when I import the made macOS image to the kubevirt platform, kubevirt cannot start the macOS virtual machine

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.45
- Kubernetes version (use `kubectl version`): 1.19.10
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): ubuntu20.04
- Kernel (e.g. `uname -a`): 5.11.0-34-generic
- Install tools:
- Others:

**Comment by rmohr** [comment]
Hi, we would need more information, like `kubectl describe vmis <vmname>` to see what is going on.

**Comment by Animezjy** [comment]
Name:         osx-1
Namespace:    default
Labels:       injector.droidvirt.io/request=osx-worker-sidecar
              kubevirt.io/nodeName=k8s-ceph-1
              vmName=osx-1
Annotations:  converter.droidvirt.io/type: board,vnc,boot-loader,input-device,nic-model
              hooks.kubevirt.io/hookSidecars: [{"image":"registry.cn-shanghai.aliyuncs.com/droidvirt/hook-sidecar:osx-202010062044"}]
              kubevirt.io/latest-observed-api-version: v1
              kubevirt.io/storage-observed-api-version: v1alpha3
              loader.osx-kvm.io/path: /usr/share/OVMF/OVMF_CODE.fd
              nvram.osx-kvm.io/path: /usr/share/OVMF/OVMF_VARS.fd
              vnc.droidvirt.io/port: 5900
API Version:  kubevirt.io/v1
Kind:         VirtualMachineInstance
Metadata:
  Creation Timestamp:  2021-09-26T04:54:02Z
  Finalizers:
    kubevirt.io/virtualMachineControllerFinalize
    foregroundDeleteVirtualMachine
  Generation:  7
  Managed Fields:
    API Version:  kubevirt.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:converter.droidvirt.io/type:
          f:hooks.kubevirt.io/hookSidecars:
          f:kubevirt.io/latest-observed-api-version:
          f:kubevirt.io/storage-observed-api-version:
          f:loader.osx-kvm.io/path:
          f:nvram.osx-kvm.io/path:
          f:vnc.droidvirt.io/port:
        f:finalizers:
        f:labels:
          .:
          f:injector.droidvirt.io/request:
          f:kubevirt.io/nodeName:
          f:vmName:
        f:ownerReferences:
      f:spec:
        .:
        f:domain:
          .:
          f:cpu:
            .:
            f:cores:
            f:model:
          f:devices:
            .:
            f:autoattachGraphicsDevice:
            f:disks:
            f:interfaces:
          f:firmware:
            .:
            f:uuid:
          f:machine:
            .:
            f:type:
          f:resources:
            .:
            f:requests:
              .:
              f:memory:
        f:hostname:
        f:networks:
        f:terminationGracePeriodSeconds:
        f:volumes:
      f:status:
        .:
        f:activePods:
          .:
          f:68108aa9-f79a-471b-9097-d955f5e6a40f:
        f:conditions:
        f:guestOSInfo:
        f:migrationMethod:
        f:nodeName:
        f:phase:
        f:phaseTransitionTimestamps:
        f:qosClass:
        f:virtualMachineRevisionName:
        f:volumeStatus:
    Manager:    Go-http-client
    Operation:  Update
    Time:       2021-09-26T04:54:16Z
  Owner References:
    API Version:           kubevirt.io/v1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  VirtualMachine
    Name:                  osx-1
    UID:                   94992c9b-33c6-4e9c-9d4a-e6a51999f173
  Resource Version:        6658218
  Self Link:               /apis/kubevirt.io/v1/namespaces/default/virtualmachineinstances/osx-1
  UID:                     de51438d-b020-4174-bf57-fcef4461b7e4
Spec:
  Domain:
    Cpu:
      Cores:  4
      Model:  host-model
    Devices:
      Autoattach Graphics Device:  false
      Disks:
        Boot Order:  1
        Disk:
          Bus:       sata
        Name:        clover
        Boot Order:  2
        Disk:
          Bus:  sata
        Name:   data-disk
      Interfaces:
        Masquerade:
        Model:  e1000
        Name:   default
        Ports:
          Name:  sshd
          Port:  22
    Features:
      Acpi:
        Enabled:  true
    Firmware:
      Uuid:  e523e0e0-31c8-5b82-9d49-66bd2a9b2a2a
    Machine:
      Type:  q35
    Resources:
      Requests:
        Cpu:     100m
        Memory:  4Gi
  Hostname:      osx-1
  Networks:
    Name:  default
    Pod:
      Vm Network CIDR:               192.168.100.0/24
  Termination Grace Period Seconds:  0
  Volumes:
    Ephemeral:
      Persistent Volume Claim:
        Claim Name:  iso-mac
    Name:            clover
    Name:            data-disk
    Persistent Volume Claim:
      Claim Name:  disk-mac
Status:
  Active Pods:
    68108aa9-f79a-471b-9097-d955f5e6a40f:  k8s-ceph-1
  Conditions:
    Last Probe Time:       2021-09-26T04:54:02Z
    Last Transition Time:  2021-09-26T04:54:02Z
    Message:               Guest VM is not reported as running
    Reason:                GuestNotRunning
    Status:                False
    Type:                  Ready
    Last Probe Time:       <nil>
    Last Transition Time:  <nil>
    Status:                True
    Type:                  LiveMigratable
    Last Probe Time:       <nil>
    Last Transition Time:  2021-09-26T04:54:19Z
    Message:               server error. command SyncVMI failed: "LibvirtError(Code=67, Domain=10, Message='unsupported configuration: domain configuration does not support video model 'qxl'')"
    Reason:                Synchronizing with the Domain failed.
    Status:                False
    Type:                  Synchronized
  Guest OS Info:
  Migration Method:  BlockMigration
  Node Name:         k8s-ceph-1
  Phase:             Scheduled
  Phase Transition Timestamps:
    Phase:                        Pending
    Phase Transition Timestamp:   2021-09-26T04:54:02Z
    Phase:                        Scheduling
    Phase Transition Timestamp:   2021-09-26T04:54:02Z
    Phase:                        Scheduled
    Phase Transition Timestamp:   2021-09-26T04:54:16Z
  Qos Class:                      Burstable
  Virtual Machine Revision Name:  revision-start-vm-94992c9b-33c6-4e9c-9d4a-e6a51999f173-2
  Volume Status:
    Name:    clover
    Target:
    Name:    data-disk
    Persistent Volume Claim Info:
      Access Modes:
        ReadWriteMany
      Capacity:
        Storage:    50Gi
      Volume Mode:  Filesystem
    Target:
Events:
  Type     Reason            Age                 From                       Message
  ----     ------            ----                ----                       -------
  Normal   SuccessfulCreate  58s                 virtualmachine-controller  Created virtual machine pod virt-launcher-osx-1-w6h2c
  Warning  SyncFailed        20s (x13 over 41s)  virt-handler               server error. command SyncVMI failed: "LibvirtError(Code=67, Domain=10, Message='unsupported configuration: domain configuration does not support video model 'qxl'')"

**Comment by Animezjy** [comment]
I'm sorry for the slow reply, I tried to use this solution to solve the problem of running mac virtual machine in kubevirt 
Serval enhancement to port macOS VM to kubevirt · Issue #2763 · kubevirt/kubevirt (github.com)
