### ISSUE TITLE
virtctl image upload requires permissions not available to most users

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#6442]
#6367 introduces the requirement for clients to have permissions to list storageclasses and get cdi storage profiles within the cluster, which limits who can upload images.

We need to reconsider how defaults are calculated in virtctl for this feature in order to support users who do not have access to these fields. Perhaps we can transfer this defaulting logic to the backend somehow

**Comment by brybacki** [comment]
It is in progress, and actually the check might be not needed. 

The only thing we loose is a fast fail - with error message about ReadOnly accessmode. But this might be available in DataVolume Condition/Event.
