### ISSUE TITLE
TPM support

### ISSUE THREAD

**Issue by th-2021** [kubevirt/kubevirt#6447]
tpm is mentioned at https://github.com/kubevirt/kubevirt/blob/main/docs/vm-configuration.md
but I couldn't figure out how I have to specify it.

I tried:
...
devices:
...
  tpm:
          - model: tpm-tis
             backend:
                  type: emulator
                  version: "2.0"
...
but I got an error tpm unknown.

If it works, can you give an example?
Thanks

**Comment by th-2021** [comment]
Windows 11 seems to require this also for VMs

**Comment by zakkg3** [comment]
+1 to tpm
What about AMD sev ?
https://libvirt.org/kbase/launch_security_sev.html
some work founded here https://github.com/jimcadden/kubevirt-sev/tree/sev
Mail discussion https://groups.google.com/g/kubevirt-dev/c/a6XlT0qRNAY/m/lhfCz9CCAwAJ

**Comment by xpivarc** [comment]
This will be fixed by https://github.com/kubevirt/kubevirt/pull/7103
