### ISSUE TITLE
image-upload: timed out waiting for the condition

### ISSUE THREAD

**Issue by sured77** [kubevirt/kubevirt#6457]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
When going to upload an windows ISO image, the following happens:

virtctl image-upload \
> --image-path=/root/SW_DVD9_Win_Svr_STD_Core_and_DataCtr_Core_2016_64Bit_English_-2_MLF_X21-22843.ISO \
> --access-mode=ReadWriteOnce \
> --pvc-name=iso-pvc \
> --storage-class=local-storage \
> --no-create \
> --insecure \
> --wait-secs=240 \
> --uploadproxy-url=https://cdi-uploadproxy.my.domain:443

Using existing PVC default/iso-pvc
Waiting for PVC iso-pvc upload pod to be ready...
timed out waiting for the condition
.
.

**What you expected to happen**:
I expect the image upload to complete.

**How to reproduce it (as minimally and precisely as possible)**:
[root]#  kubectl get pods
NAME                                READY   STATUS    RESTARTS   AGE
cdi-upload-iso-pvc                  1/1     Running   0          61m
----------

[root]# kubectl logs -f cdi-upload-iso-pvc
I0923 20:04:58.697022       1 uploadserver.go:69] Upload destination: /data/disk.img
I0923 20:04:58.697141       1 uploadserver.go:71] Running server on 0.0.0.0:8443
--------
[root]# kubectl get pvc |grep iso
iso-pvc                Bound    win-vol           7Gi        RWO            local-storage   64m
iso-pvc-scratch   Bound    win-vol-scratch   7Gi        RWO            local-storage   64m

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`):
Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-12T14:18:45Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications:
- Cloud provider or hardware configuration:
 VMware VM's 4 nodes ( 1 master, 2 Linux , 1 windows)

- OS (e.g. from /etc/os-release):
   NAME="Red Hat Enterprise Linux Server"
   VERSION="7.9 (Maipo)"

- Kernel (e.g. `uname -a`):
  Linux 3.10.0-1160.31.1.el7.x86_64 #1  x86_64 x86_64 x86_64 GNU/Linux
- Install tools:
- Others:

**Comment by mazzystr** [comment]
@mhenriks Can you take a look at this?

**Comment by mhenriks** [comment]
@sured77 kubevirt version reported here does not seem correct.  Can you also add the CDI version?

**Comment by sured77** [comment]
it's v1.39
