### ISSUE TITLE
building kubevirt based on arm64 architecture,but unrecognized import path "golang.org/x/crypto"

### ISSUE THREAD

**Issue by mack1024** [kubevirt/kubevirt#6484]
**

**I'm building kubevirt based on arm64 architecture,I used the make command building kubevirt,but org_golang_x_crypt Cannot download,I have set up an HTTPS proxy and go proxy,it still cannot download.Can you help me?thank you very much.**

**

hack/dockerized "export BUILD_ARCH= && DOCKER_PREFIX= DOCKER_TAG= IMAGE_PULL_POLICY= VERBOSITY= ./hack/build-manifests.sh && \
    hack/bazel-fmt.sh && hack/bazel-build.sh"
selecting docker as container runtime
go version go1.13.14 linux/arm64

a6b827b58768d21873d77c67599c9f20d5f175bafdefe2c973ab57191398b32c
go version go1.13.14 linux/arm64
Another command holds the client lock: 
pid=14
owner=client
cwd=/root/go/src/kubevirt.io/kubevirt

Waiting for it to complete...
Another command (pid=14) is running. Waiting for it to complete on the server (server_pid=18)...
INFO: Analyzed target //:build-manifest-templator (567 packages loaded, 9798 targets configured).
INFO: Found 1 target...
Target //:build-manifest-templator up-to-date:
  bazel-bin/manifest-templator-copier
INFO: Elapsed time: 102.942s, Critical Path: 52.11s
INFO: 544 processes: 2 internal, 542 processwrapper-sandbox.
INFO: Build completed successfully, 544 total actions
INFO: Running command line: bazel-bin/manifest-templator-copier /root/go/src/kubevirt.io/kubevirt/_out/tesINFO: Build completed successfully, 544 total actions
digest files not found: won't use shasums, falling back to tags
INFO: Analyzed target //vendor/mvdan.cc/sh/v3/cmd/shfmt:shfmt (6 packages loaded, 33 targets configured).
INFO: Found 1 target...
Target //vendor/mvdan.cc/sh/v3/cmd/shfmt:shfmt up-to-date:
  bazel-bin/vendor/mvdan.cc/sh/v3/cmd/shfmt/shfmt_/shfmt
INFO: Elapsed time: 2.236s, Critical Path: 1.71s
INFO: 10 processes: 3 internal, 7 processwrapper-sandbox.
INFO: Build completed successfully, 10 total actions
INFO: Running command line: bazel-bin/vendor/mvdan.cc/sh/v3/cmd/shfmt/shfmt_/shfmt -i 4 -w /root/go/src/kuINFO: Build completed successfully, 10 total actions
INFO: Analyzed target //:gazelle (29 packages loaded, 304 targets configured).
INFO: Found 1 target...
Target //:gazelle up-to-date:
  bazel-bin/gazelle-runner.bash
  bazel-bin/gazelle
INFO: Elapsed time: 14.656s, Critical Path: 12.57s
INFO: 83 processes: 12 internal, 71 processwrapper-sandbox.
INFO: Build completed successfully, 83 total actions
INFO: Build completed successfully, 83 total actions
INFO: Analyzed target //:goimports (14 packages loaded, 56 targets configured).
INFO: Found 1 target...
Target //:goimports up-to-date:
  bazel-bin/goimports.bash
INFO: Elapsed time: 2.917s, Critical Path: 2.48s
INFO: 19 processes: 4 internal, 15 processwrapper-sandbox.
INFO: Build completed successfully, 19 total actions
INFO: Build completed successfully, 19 total actions
INFO: Analyzed target //:buildifier (66 packages loaded, 783 targets configured).
INFO: Found 1 target...
INFO: From Compiling com_google_protobuf/src/google/protobuf/generated_message_reflection.cc [for host]:
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc: In member function 'void google::protobuf::Reflection::SwapOneofField(google::protobuf::Message*, google::protobuf::Message*, const google::protobuf::OneofDescriptor*) const':
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:2129:37: warning: 'temp_bool' may be used uninitialized in this function [-Wmaybe-uninitialized]
 2129 |   *MutableRaw<Type>(message, field) = value;
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:496:8: note: 'temp_bool' was declared here
  496 |   bool temp_bool;
      |        ^~~~~~~~~
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:2129:37: warning: 'temp_float' may be used uninitialized in this function [-Wmaybe-uninitialized]
 2129 |   *MutableRaw<Type>(message, field) = value;
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:494:9: note: 'temp_float' was declared here
  494 |   float temp_float;
      |         ^~~~~~~~~~
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:2129:37: warning: 'temp_uint64' may be used uninitialized in this function [-Wmaybe-uninitialized]
 2129 |   *MutableRaw<Type>(message, field) = value;
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:493:10: note: 'temp_uint64' was declared here
  493 |   uint64 temp_uint64;
      |          ^~~~~~~~~~~
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:2129:37: warning: 'temp_uint32' may be used uninitialized in this function [-Wmaybe-uninitialized]
 2129 |   *MutableRaw<Type>(message, field) = value;
      |   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~
external/com_google_protobuf/src/google/protobuf/generated_message_reflection.cc:492:10: note: 'temp_uint32' was declared here
  492 |   uint32 temp_uint32;
      |          ^~~~~~~~~~~
Target //:buildifier up-to-date:
  bazel-bin/buildifier.bash
INFO: Elapsed time: 125.339s, Critical Path: 20.40s
INFO: 278 processes: 14 internal, 264 processwrapper-sandbox.
INFO: Build completed successfully, 278 total actions
INFO: Build completed successfully, 278 total actions
WARNING: /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/remote_java_tools_linux/BUILD:733:11: in hdrs attribute of cc_library rule @remote_java_tools_linux//:combiners: Artifact 'external/remote_java_tools_linux/java_tools/src/tools/singlejar/zip_headers.h' is duplicated (through '@remote_java_tools_linux//:transient_bytes' and '@remote_java_tools_linux//:zip_headers'). Since this rule was created by the macro 'cc_library', the error might have been caused by the macro implementation
INFO: Repository org_golang_x_crypto instantiated at:
  /root/go/src/kubevirt.io/kubevirt/WORKSPACE:308:14: in <toplevel>
Repository rule go_repository defined at:
  /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/bazel_gazelle/internal/go_repository.bzl:193:32: in <toplevel>
ERROR: An error occurred during the fetch of repository 'org_golang_x_crypto':
   Traceback (most recent call last):
        File "/root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/bazel_gazelle/internal/go_repository.bzl", line 128, column 17, in _go_repository_impl
                fail("failed to fetch %s: %s" % (ctx.name, result.stderr))
Error in fail: failed to fetch org_golang_x_crypto: fetch_repo: unrecognized import path "golang.org/x/crypto"
ERROR: /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/bazeldnf/cmd/BUILD.bazel:3:11: @bazeldnf//cmd:cmd_lib depends on @org_golang_x_crypto//openpgp:go_default_library in repository @org_golang_x_crypto which failed to fetch. no such package '@org_golang_x_crypto//openpgp': failed to fetch org_golang_x_crypto: fetch_repo: unrecognized import path "golang.org/x/crypto"
ERROR: Analysis of target '//cmd/virt-launcher:go_default_library' failed; build aborted: Analysis failed
INFO: Elapsed time: 61.548s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (635 packages loaded, 7547 targets configured)
    Fetching @go_image_base_aarch64; fetching 55s
make: *** [Makefile:9：all] 错误 1

**Comment by mazzystr** [comment]
There has been quiet a lot of work to stabilize ARM64 builds.  

Issue filed on Sept 29.  Are you still seeing this issue?  

/triage needs-information

**Comment by mack1024** [comment]
> There has been quiet a lot of work to stabilize ARM64 builds.
> 
> Issue filed on Sept 29. Are you still seeing this issue?
> 
> /triage needs-information

This problem has been solved. Thank you for your reply. If you have any questions, please feel free to communicate.
