### ISSUE TITLE
Recording Rule "kubevirt_vm_container_free_memory_bytes" is not working

### ISSUE THREAD

**Issue by sbulage** [kubevirt/kubevirt#6486]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**: 
When try to execute recording rules: "kubevirt_vm_container_free_memory_bytes" shows "No datapoints found."

I debugged more and found that metrics used in this recording rules expression is changed.

**What you expected to happen**: It should work and show output.

**How to reproduce it (as minimally and precisely as possible)**: 100%

**Anything else we need to know?**: This is the updated expression need to use --> `sum by(pod, container) ( kube_pod_init_container_resource_limits_memory_bytes{pod=~'virt-launcher-.*'} - on(pod,container) container_memory_working_set_bytes{pod=~'virt-launcher-.*'})`

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sbulage** [comment]
@sradco Can you please take a look into it.?

**Comment by sradco** [comment]
It seems that the container is "volumecontainerdisk" and there is no "compute".
We should update the recording rule to kube_pod_container_resource_limits{resource='memory', unit='byte', pod=~'virt-launcher-.*'}

**Comment by sradco** [comment]
New query should be : 
sum by(pod, container) ( kube_pod_container_resource_limits{resource='memory', unit='byte', pod=~'virt-launcher-.*'}
- on(pod,container) container_memory_working_set_bytes{pod=~'virt-launcher-.*'})
