### ISSUE TITLE
Missing runbooks for VirtApiRESTErrorsHigh and VirtApiRESTErrorsBurst alerts

### ISSUE THREAD

**Issue by sradco** [kubevirt/kubevirt#6491]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:

Missing runbooks for new alerts: VirtApiRESTErrorsHigh, VirtApiRESTErrorsBurst

**What you expected to happen**:
All Kubevirt alerts should include a runbook_url annotation and runbooks at https://github.com/kubevirt/monitoring/tree/main/docs/runbooks 

See example:
https://github.com/kubevirt/kubevirt/blob/42a49ae61d3b41a78439acfcf1951507dfa61915/pkg/virt-operator/resource/generate/components/prometheus.go#L102
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sradco** [comment]
@iholder-redhat Can you please handle this issue?

**Comment by iholder-redhat** [comment]
> @iholder-redhat Can you please handle this issue?

Yes, no problem :)

**Comment by iholder-redhat** [comment]
@sradco this issue can be closed
