### ISSUE TITLE
[outreachy] [good-first-issue] Refactor pkg/controllers

### ISSUE THREAD

**Issue by vatsalparekh** [kubevirt/kubevirt#6494]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What happened**:
Sonarcloud has many refactoring observations to reduce the code complexity in `pk/controllers` directory [here](https://sonarcloud.io/project/issues?directories=pkg%2Fcontroller&id=kubevirt_kubevirt&resolved=false) 

**What you expected to happen**:
Refactor the code and break it into more readable and less complex code blocks

**Comment by raphaeljlps** [comment]
is this up for grabs ?
