### ISSUE TITLE
[outreachy] [good-first-issue] Refactor tests

### ISSUE THREAD

**Issue by vatsalparekh** [kubevirt/kubevirt#6495]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What happened**:
Sonarcloud has many refactoring suggestions to reduce code complexity for the `tests` directory [here ](https://sonarcloud.io/project/issues?directories=tests&id=kubevirt_kubevirt&resolved=false)
**What you expected to happen**:

Refactor and break the code into more readable and manageable blocks

**Comment by odra** [comment]
I would like to work on this issue if it is free :-)

**Comment by odra** [comment]
I don' t think I have the perms to do so :)

**Comment by odra** [comment]
thanks!
