### ISSUE TITLE
[outreachy] [good-first-issue] Refactor pkg/virt-handler

### ISSUE THREAD

**Issue by vatsalparekh** [kubevirt/kubevirt#6496]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement

**What happened**:
Sonarcloud has suggestions to reduce code complexity of `pkg/virt-handler` directory [here](https://sonarcloud.io/project/issues?directories=pkg%2Fvirt-handler&id=kubevirt_kubevirt&resolved=false)

**What you expected to happen**:
Refactor and break the code into more readable and manageable blocks

**Comment by Gre8t** [comment]
thank you
