### ISSUE TITLE
golang 1.17 fails to parse IPs with leading zeros

### ISSUE THREAD

**Issue by phoracek** [kubevirt/kubevirt#6498]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

With Golang 1.17, the way `net.ParseIP` and `net.ParseCIDR` changes. While up until now, IPs with leading zeros (e.g. 192.168.001.100) were accepted, they won't be any longer.

**What you expected to happen**:

While the simple fix to this would be to strip leading zeros from each octet, it would be a backwards compatibility breaking change - while some tools (e.g. `ip`) would ignore leading zeros (i.e. treat 192.168.010.100 as 192.168.10.100), others (e.g. iptables) treat IPs with leading zeros as octal (i.e. treat 192.168.010.100 as 192.168.8.100).

To properly fix this, there are two options:

**Option 1 - Fix each usage on per-case basis**

We can go over all places where these two functions are used and consider following:

* Is IP input here passed from the outside or is it internal?
  * If it is internal, do we ever generate IP with leading zeros there?
    * No - this place is fine, no action needed
    * Yes - fix it, use only decimal IPs
  * If it is external, is the parsed IP passed to a destination that treats IPs with leading zeros as octal
    * No - replace the function, possibly with something that simply strips those zeros since they don't matter anyway
    * Yes - replace the function with one that would not fail getting leading zeros

**Option 2 - Replace with Kubernetes' forked `ParseIPSloppy` and `ParseCIDRSloppy` functions**

Kubernetes dealt with this issue by introducing their own "fork" of the old versions of Golang core functions https://github.com/kubernetes/kubernetes/pull/104368. We could vendor their `netutils "k8s.io/utils/net"` module. The problem with that is that it was introduced only with Kubernetes 1.23. KubeVirt's dependencies would need to be bumped to get access to that.

**Comment by orelmisan** [comment]
When creating a new VM, the following input fields are validated using net.ParseIP()

[v1.VirtualMachineInstanceSpec](http://kubevirt.io/api-reference/main/definitions.html#_v1_virtualmachineinstancespec)
- dnsConfig.nameservers [k8s.io.api.core.v1.PodDNSConfig](https://kubevirt.io/api-reference/main/definitions.html#_k8s_io_api_core_v1_poddnsconfig) 
- domain.devices.interfaces.dhcpOptions.ntpServers [v1.DHCPOptions](https://kubevirt.io/api-reference/main/definitions.html#_v1_dhcpoptions)

**Comment by orelmisan** [comment]
The virtctl utility has several options where a user can input an IPv4 address:

$ ./virtctl port-forward --address
$ ./virtctl expose
--cluster-ip
--external-ip
--load-balancer-ip

**Comment by orelmisan** [comment]
There is another problematic field:
v1.VirtualMachineInstanceSpec:
spec.networks[].pod.vmNetworkCIDR [v1.PodNetwork
](http://kubevirt.io/api-reference/v0.48.1/definitions.html#_v1_podnetwork)
