### ISSUE TITLE
[tests] Improve windows DHCP coverage

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#6538]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind enhancement

**What happened**:

We test linux pretty well with our internal DHCP server but we don't do the same for windows. This led to a regression: https://github.com/kubevirt/kubevirt/issues/6462.

**What you expected to happen**:

Let's add a few more windows tests around networking.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by maiqueb** [comment]
@dteplits / @AlonaKaplan can we close this issue, now that https://github.com/kubevirt/kubevirt/pull/6833 was merged ?

**Comment by maiqueb** [comment]
/close

#6833 added the requested tests .
