### ISSUE TITLE
Recording Rules are missing

### ISSUE THREAD

**Issue by sbulage** [kubevirt/kubevirt#6545]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**: 
Following Metrics(recording rules) are missing:

- Kubevirt_virt_controller_ready_total 
- Kubevirt_virt_operator_ready_total
- Kubevirt_virt_operator_leading_total

**What you expected to happen**:
All metrics should be available

**How to reproduce it (as minimally and precisely as possible)**:100%

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sradco** [comment]
This issue is related to https://github.com/kubevirt/kubevirt/issues/5383#issuecomment-938580869

**Comment by sradco** [comment]
Closing since this issue was fixed #6570
