### ISSUE TITLE
Reconcile and enable monitoring even after virt-operator startup

### ISSUE THREAD

**Issue by weihanglo** [kubevirt/kubevirt#6551]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:

virt-operator deteremine whether or not to enable monitoring by checking the existence of sevicemonitor CRD. However it only occurs [during startup]. This is somehow limited since a user may deploy prometheus monitoring stack after virt-operaetor startup.

[during startup]: https://github.com/kubevirt/kubevirt/blob/5a22acb1868e17824df34044a60a5e42b91b9357/pkg/virt-operator/application.go#L239-L268 

**What you expected to happen**:

Whenever a user deploy prometheus monitoring CRD, virt-operator must enable monitoring functionality.

**How to reproduce it (as minimally and precisely as possible)**:

1. Deploy KubeVirt in a cluster
2. Wait a moment
3. Deploy prometheus-operator CRD. Then there is no servicemonitor for KubeVirt being created.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.45.0

**Comment by xpivarc** [comment]
/reopen
Does deleting the operator pod resolve this issue?

**Comment by guangbochen** [comment]
Yes, but we are more looking for a proper solution like a reconciliation check instead of just a manual workaround fix, thanks for the consideration.

**Comment by w13915984028** [comment]
FYI: the workaround in Harvester to recover this issue:

check the virt-operator pod
```
$ kubectl get pods -n harvester-system | grep "virt-operator" | awk '{print $1}' | xargs kubectl get pods -n harvester-system

NAME                             READY   STATUS    RESTARTS   AGE
virt-operator-78b84587c9-zw2cd   1/1     Running   0          4m51s
```

delete the virt-operator pod, and wait a while
```
$ kubectl get pods -n harvester-system | grep "virt-operator" | awk '{print $1}' | xargs kubectl delete pod -n harvester-system
```

verify the newly replaced virt-operator pod log to confirm prometheusrule is defined
```
$ kubectl get pods -n harvester-system | grep "virt-operator" | awk '{print $1}' | xargs kubectl logs -n harvester-system | grep "prometheusrule is defined"

{"component":"virt-operator","level":"info","msg":"prometheusrule is defined","pos":"application.go:262","timestamp":"2022-07-12T15:58:40.080472Z"}
```
The log shows, `virt-operator` assumes `prometheusrule is defined`. It's OK now.

**Comment by xpivarc** [comment]
Most of the time I would expect to have the monitoring stack deployed before Kubevirt therefore I am not sure we need to dynamically watch this. Maybe others will have a different opinions. @davidvossel wdyt?

**Comment by w13915984028** [comment]
I would like to say, unless some software takes care of this, it's diffcult make sure that the monitoring stack is ready before deploy kubevirt.

Or user should add `init pod` to kubevirt to check this kind of dependency.

**Comment by davidvossel** [comment]
we can follow the same pattern we used for cdi in virt-controller.

https://github.com/kubevirt/kubevirt/blob/c568549898a5130fbc32d57b7cc7f3ba7d203920/pkg/virt-controller/watch/application.go#L422

We start the controller, if we see the cdi api comes online during the runtime, then we re-initialize the controller.  We coudl do the same thing for virt-operator. If the prometheus APIs come online after initialization, force a restart.
