### ISSUE TITLE
Kernel image is not prepulled as an initConainer

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#6552]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

> /kind enhancement

**What happened**:

If one specifies a kernel image with a kernel we pull that image and the VM will use the kernel form that image, however we are not prepulling it like we do for containerDisks. As a result, if the pull takes longer virt-launcher will time out.

**What you expected to happen**:

We should prepull the image like containerDisks via an init container.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@iholder-redhat maybe you want to have a look.

**Comment by iholder-redhat** [comment]
PR is created: https://github.com/kubevirt/kubevirt/pull/6589

**Comment by iholder-redhat** [comment]
PR is merged. I guess this can be closed?

**Comment by stu-gott** [comment]
@davidvossel I can't remember, do we wait for the next release before closing, or when the fix PR is merged on main?

**Comment by rmohr** [comment]
/close

fixed in #6589
