### ISSUE TITLE
Allow configuration of `virt-handler` DaemonSet spec

### ISSUE THREAD

**Issue by VirrageS** [kubevirt/kubevirt#6561]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**: After redeploying new version of KubeVirt the `virt-handler`'s DaemonSet has default `.spec.strategy` set. This means that the `.spec.strategy.rollingUpdate.maxUnavailable` is set to `1`. This is problematic for large clusters (with hundreds of nodes) because the full update will take hours. The current fix for this is to patch the code to change the part where the `virt-handler`'s DaemonSet is initialized and change the `.spec.strategy`. The problem with this approach is that it isn't flexible, because every change of the value requires changes in the code.

But this is not constrained to just `.spec.strategy`, other fields are hard-coded as well, for example `securityContext` etc.

**What you expected to happen**: Ideally, I could manipulate the `virt-handler`'s spec in `virt-operator` spec (maybe same for other like deployments like `virt-controller` etc.)

**How to reproduce it (as minimally and precisely as possible)**: Redeploy the `virt-operator` with the new image.

**Comment by rmohr** [comment]
@VirrageS I think there are two things which can help you. 

First we allow adding json patches to the KubeVirt CR to introduce any changes to specs and ensure that they don't get stomped on again: https://github.com/kubevirt/kubevirt/pull/3612

Second there is work going on to address exactly this case: https://github.com/kubevirt/kubevirt/pull/6702

**Comment by acardace** [comment]
This issue is also partly addressed by https://github.com/kubevirt/kubevirt/pull/6524.
