### ISSUE TITLE
virtctl is not working on macOS

### ISSUE THREAD

**Issue by ShubhamTatvamasi** [kubevirt/kubevirt#6578]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:

getting error while running virtctl command on macOS
```
➜  ~ virtctl version
Client Version: version.Info{GitVersion:"v0.46.0", GitCommit:"3ebb0a03fde639ea9afb5ee83ac7ac72dbeb4a9d", GitTreeState:"clean", BuildDate:"2021-10-08T21:20:46Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
invalid character '<' looking for beginning of value
```

**What you expected to happen**:

It's working on my linux box:
```
ubuntu@ubuntu:~$ virtctl version
Client Version: version.Info{GitVersion:"v0.46.0", GitCommit:"3ebb0a03fde639ea9afb5ee83ac7ac72dbeb4a9d", GitTreeState:"clean", BuildDate:"2021-10-08T21:20:46Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.46.0-dirty", GitCommit:"3ebb0a03fde639ea9afb5ee83ac7ac72dbeb4a9d", GitTreeState:"dirty", BuildDate:"2021-10-08T21:39:28Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@ShubhamTatvamasi could you run `virtctl version -v9`?

**Comment by kobi86** [comment]
HI @ShubhamTatvamasi, any update on this?

**Comment by ShubhamTatvamasi** [comment]
> HI @ShubhamTatvamasi, any update on this?

Got same error:
```
➜  ~ virtctl version
Client Version: version.Info{GitVersion:"v0.46.1", GitCommit:"5ed15d782ae5bfb7e1323e65defae6cc84ca8175", GitTreeState:"clean", BuildDate:"2021-10-19T15:50:33Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
invalid character '<' looking for beginning of value
```

**Comment by ShubhamTatvamasi** [comment]
So I found that it was my terminal issue. I was using Lens terminal that's why I was getting this error. After switching to iTerm the issue has been resolved. Thanks, @kobi86 for all your help.
