### ISSUE TITLE
Add Fedora to iSCSI Demo Target

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#659]
Sometimes we need a full blown distro to test functionality

**Comment by rmohr** [comment]
How can this be a bug?

**Comment by rmohr** [comment]
Can you be more specific about what you want to test?

**Comment by fabiand** [comment]
Okay, bug is a bad fit. But it's probably a fix to gain guest support for the devices introduced by the q35 move, which in turn hopefully fixes our CI. Thus it's not a bug, but rather a fix.

**Comment by fabiand** [comment]
See #661

**Comment by davidvossel** [comment]
#685

**Comment by rmohr** [comment]
We have fedora now as a registry disk in qcow with #685 . It might be possible to expand the qcow to raw for iscsi, without ending up with a few gigabyte image, but I think it is sufficient to have it as a registry disk for now. @fabiand thoughts?

**Comment by fabiand** [comment]
RegistryDisk is fine for now.
