### ISSUE TITLE
[monitoring] Virt-operator and virt-controller readiness metrics being calculated inaccurately 

### ISSUE THREAD

**Issue by enp0s3** [kubevirt/kubevirt#6590]
/kind bug

**What happened**:
Virt-operator and virt-controller expose a Gauge metric called `kubevirt_virt_operator_ready` and `kubevirt_virt_controller_ready`. That metric should reflect the readiness of the app.
Currently this metric is not correct. As can be seen in the [handler](https://github.com/kubevirt/kubevirt/blob/099be903803556bfe3a85075a7b55f0a711d9ca7/pkg/healthz/healthz.go#L71) of the `/healthz` endpoint, the `readyGauge` doesn't been updated by the endpoint handler, thus making the metric inconsistent compared to the readiness probe status (The gauge value keeps `1` while the app is unhealthy and thus not ready). As a result of that, the following alerts are being affected:

- LowReadyVirtControllersCount
- NoReadyVirtController
- LowReadyVirtOperatorsCount
- NoReadyVirtOperator

**What you expected to happen**:
The Gauge metric should be set to `0` as soon as the app considered unhealthy, because then it's not ready for the leader election.

**How to reproduce it (as minimally and precisely as possible)**:
Imitate connectivity issue between a virt-controller pod to the Kubernetes API, make the `/healthz` return unhealthy status and observe the `kubevirt_virt_controller_ready`

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): latest
- Kubernetes version (use `kubectl version`): 1.20, 1.21, 1.22
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by sradco** [comment]
@enp0s3 This should still stay open right?

**Comment by enp0s3** [comment]
@sradco Hi, yes.

**Comment by rmohr** [comment]
if we know that this does not solve itself, let's add

/lifecycle frozen

**Comment by enp0s3** [comment]
/close

My understanding of `kubevirt_virt_controller_ready` and `kubevirt_virt_operator_ready` was incorrect. The aim of these metrics is to indicate whether the application is ready to be elected as a leader in the leader election process. It doesn't related to the readiness probes, thus it should not be coupled with the `/healthz` endpoint logic.
