### ISSUE TITLE
VMI is still paused after the storage access is recovered

### ISSUE THREAD

**Issue by xinyanzh97** [kubevirt/kubevirt#6599]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
After the storage access is recovered, the VMI is still paused, and libevirt continues to report IO error.

**What you expected to happen**:
The VMI should be unpaused when the storage is recovered.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a VM using a NFS storage for its boot disk.
2. Create an iptable rule on the nfs server to block the access to the NFS storage from the node where the VM is on.
3. Create an iptable rule on the nfs server to recover the access to the NFS storage from the node where the VM is on.

**Anything else we need to know?**:
both soft mount mode NFS and hard mount mode NFS have this problem

**Environment**:
- KubeVirt version (use `virtctl version`): 0.43.0
- Kubernetes version (use `kubectl version`): v1.21.1
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): Ubuntu 20.04.2
- Kernel (e.g. `uname -a`): 5.4.0
- Install tools:
- Others:

**Comment by xinyanzh97** [comment]
> Hi @xinyanzh97 , I guess this is related to #6599. Would you be able to verify that you can read/write to the volume from virt-launcher?
> 
> The steps would be something like:
> 
> 1. kubectl exec -ti  bash
> 2. cat

Thanks for your suggestion, let me have a try and test.

BTW, "_I guess this is related to #6599_": maybe another bug number?

**Comment by leoryu** [comment]
@xinyanzh97 hi，have you found solution of this isuue? I met the same issue, while my csi is ceph fs.

**Comment by rmohr** [comment]
/remove-lifecycle rotten

Reopening based on a slack discussion. @huxiaoliang do you still experience this?

**Comment by huxiaoliang** [comment]
@rmohr  yes, I will append more details tomorrow, before that,  could you please show me is this expected behavior or a bug? currently, I use "stop/start" vm to recover

**Comment by rmohr** [comment]
> @rmohr yes, I will append more details tomorrow, before that, could you please show me is this expected behavior or a bug? currently, I use "stop/start" vm to recover

The expectation is, that if `virt-handler`, our node-daemon is running successfully on the node, it should trigger an unpause attempt periodically. So the VM should eventually get back to running. Especially NFS and filesystem can be tricky because of posix lock difficulties in NFS, when the NFS server crashes or restarts. The virt-launcher logs would be helpful in this  case.

**Comment by huxiaoliang** [comment]
@rmohr  I can't reproduce this issue anymore base on kubvirt 0.50.0 + ceph-fs

**Comment by pureneelesh** [comment]
@huxiaoliang : did you try NFSv4? We are able to repro this with OCP 4.12/4.13 and NFS 4.0.
