### ISSUE TITLE
Does kubevirt vm support sound card?

### ISSUE THREAD

**Issue by wonleing** [kubevirt/kubevirt#6616]
Ideally, I want to set a soundcard device inside vm creation yaml, and vm can install sound driver with virtio or auto installed.
I search around, there's no official doc about sound card setting. 

I found an unmerged commit: https://github.com/kubevirt/kubevirt/commit/e5cd87be4cb39eb38959cbdf9bc4ac0515c19657 
It requires compile all images and yaml setup doc.
Anyone can provide an easy way?

**Comment by rmohr** [comment]
/close 

fixed in #6650
