### ISSUE TITLE
Kubevirt 0.46 - "status.interface" of SRIOV network is missing 

### ISSUE THREAD

**Issue by talcoh2x** [kubevirt/kubevirt#6668]
on Kubevirt 0.46 status.interface  does not appear and show me only "name": sriov
i can tell you that on release version 0.43 and 0.45.1 all is working fine.

**BUG REPORT**:

> /kind bug

**What happened**:
status.interface is missing and include only "name"

**What you expected to happen**:
I expect to see status.interface info

**How to reproduce it (as minimally and precisely as possible)**:
install Kubevirt 0.46 create VMI + SRIOV network interface and run "describe vmi <XX>"

0.46
![image](https://user-images.githubusercontent.com/34831587/138508109-0f4e6bee-ecbd-41be-b2b0-d05021da3f81.png)

0.45.1
![image](https://user-images.githubusercontent.com/34831587/138508297-241d4425-282d-4926-8952-054143434cf7.png)

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ormergi** [comment]
@talcoh2x I am not sure why it doesnt appear on the system you work with, could you please try with `kubectl get vmi <name> -o yaml`?

**Comment by EdDev** [comment]
@talcoh2x I think that the problem you are seeing originates from the fact that the guest-agent is not active in the guest (or there is a problem with communicating to it).

Currently, SR-IOV interfaces are reported only by the guest-agent.
But work is undergoing to resolve this. See #7050 for more information.

Try to confirm the guest-agent is active and let us know if it got resolved.

**Comment by EdDev** [comment]
@talcoh2x , we are closing this issue. You are welcome to re-open it when you have more info.

/close
