### ISSUE TITLE
VM is not rescheduled if it is on a unhealthy node

### ISSUE THREAD

**Issue by FrankYang0529** [kubevirt/kubevirt#6682]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
A VM on an unhealthy node doesn't automatically move to a healthy node.

```
> ./cluster-up/kubectl.sh get pod -o wide -w
selecting docker as container runtime
NAME                             READY   STATUS    RESTARTS   AGE     IP               NODE     NOMINATED NODE   READINESS GATES
local-volume-provisioner-5rnjv   1/1     Running   0          8m15s   10.244.186.193   node03   <none>           <none>
local-volume-provisioner-86tkv   1/1     Running   0          8m35s   10.244.140.65    node02   <none>           <none>
local-volume-provisioner-89mq8   1/1     Running   0          8m59s   10.244.196.130   node01   <none>           <none>
virt-launcher-vm-cirros-v6mnr    2/2     Running   0          44s     10.244.140.73    node02   <none>           <none>
virt-launcher-vm-cirros-v6mnr    2/2     Running   0          80s     10.244.140.73    node02   <none>           <none>
local-volume-provisioner-86tkv   1/1     Running   0          9m11s   10.244.140.65    node02   <none>           <none>
virt-launcher-vm-cirros-v6mnr    2/2     Terminating   0          6m25s   10.244.140.73    node02   <none>           <none>
^C

# after a few minutes, the pod is still in terminating status and it is not rescheduled to another node

> ./cluster-up/kubectl.sh get pod -o wide
selecting docker as container runtime
NAME                             READY   STATUS        RESTARTS   AGE   IP               NODE     NOMINATED NODE   READINESS GATES
local-volume-provisioner-5rnjv   1/1     Running       0          21m   10.244.186.193   node03   <none>           <none>
local-volume-provisioner-86tkv   1/1     Running       0          21m   10.244.140.65    node02   <none>           <none>
local-volume-provisioner-89mq8   1/1     Running       0          22m   10.244.196.130   node01   <none>           <none>
virt-launcher-vm-cirros-v6mnr    2/2     Terminating   0          14m   10.244.140.73    node02   <none>           <none>
```

**What you expected to happen**:
VM should be moved to a healthy node if the prior Pod is stuck in an unhealthy node.

**How to reproduce it (as minimally and precisely as possible)**:

1. `export KUBEVIRT_NUM_NODES=3`
2. `make cluster-up`
3. `make cluster-sync`
4. `./cluster-up/kubectl.sh apply -f examples/vm-cirros.yaml`
5. `./cluster-up/kubectl.sh virt start vm-cirros`
6. Check the pod of the VM on which node and stop the node.

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.46.0-238+dd4ad889c3555e", GitCommit:"dd4ad889c3555e36416a67082571d7165135b28c", GitTreeState:"clean", BuildDate:"2021-10-27T08:20:29Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.46.0-238+dd4ad889c3555e", GitCommit:"dd4ad889c3555e36416a67082571d7165135b28c", GitTreeState:"clean", BuildDate:"2021-10-27T08:21:09Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):

```
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:21:44Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.11", GitCommit:"27522a29febbcc4badac257763044d0d90c11abd", GitTreeState:"clean", BuildDate:"2021-09-15T19:16:25Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
```

- VM or VMI specifications:
- Cloud provider or hardware configuration: Docker version 20.10.10, build b485636
- OS (e.g. from /etc/os-release): Ubuntu 20.04
- Kernel (e.g. `uname -a`):  `Linux frankyang-linux 5.11.0-37-generic #41~20.04.2-Ubuntu SMP Fri Sep 24 09:06:38 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Others:

**Comment by zhonglin6666** [comment]
If the creation of a VM node is unhealthy and the pod is constantly terminating。

root@master1:~# kubectl get po -owide
NAME                              READY   STATUS        RESTARTS   AGE     IP              NODE      NOMINATED NODE   READINESS GATES
cdi-upload-iso-centos             1/1     Terminating   0          4h48m   10.233.97.195   master1   <none>           <none>
virt-launcher-vm-perf-a-2-hkn6g   1/1     Terminating   0          4h49m   10.233.97.214   master1   <none>           1/1
virtvnc-cfcb6fd76-mmrvq           1/1     Running       0          2d20h   10.233.110.38   worker1   <none>           <none>

Is there any other way or suggestion to solve such matters？
