### ISSUE TITLE
can virt-api be called outside k8s cluster?

### ISSUE THREAD

**Issue by wonleing** [kubevirt/kubevirt#6720]
I want to control kubevirt vm force start/stop/restart via virt-api, from machine outside k8s cluster.

I found there's a API    /apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachines/<vm_name>/restart
but don't know to how to auth and call it. Anyone tried it before?

**Comment by mazzystr** [comment]
@rmohr

**Comment by rmohr** [comment]
@wonleing you can access our endpoints from any location where you can reach the cluster apiserver. So when you have access with `kubectl` to the cluster you can also reach these endpoints. Our `virtctl` uses these endpoints too.

**Comment by wonleing** [comment]
> @wonleing you can access our endpoints from any location where you can reach the cluster apiserver. So when you have access with `kubectl` to the cluster you can also reach these endpoints. Our `virtctl` uses these endpoints too.

Could you give me more detail? The control side doesn't have Kubectl or virtctl installed. Are you suggesting copy kubectl or virtctl binary to control side? And run it with host:port:token parameter? Any doc about it?
Is there any way to call `/apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachines/<vm_name>/restart` API via standard http request, like python urllib2? And where to add the token?

**Comment by rmohr** [comment]
I think https://kubernetes.io/docs/tasks/administer-cluster/access-cluster-api/ may be helpful for you. Our API is part of the k8s API after KubeVirt is installed. You can access our endpoints the same way. Also note that rbac permissions need to be given to the user/serviceaccount from which you will use the bearer token.

**Comment by wonleing** [comment]
Thank you. That doc really helps. I can contol remote vm with curl request now.
But I still have a question. Is it possible to make virtctl binary support remote usage? I want to do some hack to support something like this:
./virtctl --host=x.x.x.x restart <vm_name>

I did some host address modify (hardcode as https://10.10.82.51:6443 for now) and re-compile the binary, I input correct username/password, but it met x509 error
`./virtctl restart win10-test
Please enter Username: admin
Please enter Password: Error restarting VirtualMachine Put "https://10.10.82.51:6443/apis/subresources.kubevirt.io/v1alpha3/namespaces/default/virtualmachines/win10-zpx/restart": x509: certificate signed by unknown authority`

**Comment by rmohr** [comment]
@wonleing you can look at the global options of `virtctl` with `virtctl options` (the same like for `kubectl`). Here the relevant parameters for you:

```bash
$ virtctl options
      --insecure-skip-tls-verify       If true, the server's certificate will not be checked for validity. This will make your HTTPS 
  -s, --server string                  The address and port of the Kubernetes API server
```

**Comment by wonleing** [comment]
That works. Thank you
