### ISSUE TITLE
server error. command SyncVMI failed

### ISSUE THREAD

**Issue by newhuangchuan** [kubevirt/kubevirt#6731]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
By deploying the virtual machine, the pod has been started, but vmi has not been started, `describe vmi` found the following:
```
Status:
  Active Pods:
    3951878e-21c1-42e1-aa86-83e9df56117d:  k8s-master
  Conditions:
    Last Probe Time:       <nil>
    Last Transition Time:  <nil>
    Status:                True
    Type:                  LiveMigratable
    Last Probe Time:       <nil>
    Last Transition Time:  2021-11-04T10:00:54Z
    Message:               server error. command SyncVMI failed: "preparing host-disks failed: chown /var/run/kubevirt-private/vmi-disks/harddrive/disk.img: operation not permitted"
    Reason:                Synchronizing with the Domain failed.
    Status:                False
    Type:                  Synchronized
  Guest OS Info:
  Migration Method:  BlockMigration
  Node Name:         k8s-master
  Phase:             Scheduled
  Qos Class:         Burstable
Events:
  Type     Reason            Age              From                       Message
  ----     ------            ----             ----                       -------
  Normal   SuccessfulCreate  21s              virtualmachine-controller  Created virtual machine pod virt-launcher-windows-nfs-1-pvrnb
  Warning  SyncFailed        1s (x2 over 2s)  virt-handler, k8s-master   server error. command SyncVMI failed: "preparing host-disks failed: chown /var/run/kubevirt-private/vmi-disks/harddrive/disk.img: operation not permitted"
```
**What you expected to happen**:
Both pod and vmi are running, and the virtual machine can be started.
**How to reproduce it (as minimally and precisely as possible)**:

The nfs used in the back-end uses storageClass + provisioner to automatically create and bind PV through PVC.
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: winhd-nfs
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
  storageClassName: nfs
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: windows-nfs-1
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: windows-nfs-1
    spec:
      domain:
        cpu:
          cores: 4
        resources: 
          requests: 
            memory: 8G
          limits: 
            memory: 8G
        devices:
          disks:
          - bootOrder: 1
            cdrom:
              bus: sata
            name: cdromiso
          - bootOrder: 2
            disk:
              bus: virtio
            name: harddrive
          - cdrom:
              bus: sata
            name: virtiocontainerdisk
          interfaces: 
          - name: default 
            masquerade: {}
          rng: {}
        machine:
          type: q35
      networks: 
      - name: default
        pod: {}
      terminationGracePeriodSeconds: 0
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: windows-iso
      - name: harddrive
        persistentVolumeClaim:
          claimName: winhd-nfs
      - containerDisk:
          image: kubevirt/virtio-container-disk
          imagePullPolicy: Never
        name: virtiocontainerdisk
```
**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.41.2", GitCommit:"29ce26e09eeed30f89f3fd5d1ad0598955de9648", GitTreeState:"clean", BuildDate:"2021-07-28T16:23:53Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.41.2-dirty", GitCommit:"29ce26e09eeed30f89f3fd5d1ad0598955de9648", GitTreeState:"dirty", BuildDate:"2021-07-28T16:57:02Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"d5dfb5cb416fcc32ad556b0d253307c9267b1d30", GitTreeState:"", BuildDate:"2021-07-20T15:01:11Z", GoVersion:"go1.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"d5dfb5cb416fcc32ad556b0d253307c9267b1d30", GitTreeState:"", BuildDate:"2020-07-30T01:54:02Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@newhuangchuan I think the error is a little bit misleading, but it looks like the pod the VM is running in does not seem to have write permission: `chown /var/run/kubevirt-private/vmi-disks/harddrive/disk.img: operation not permitted`.

**Comment by newhuangchuan** [comment]
> @newhuangchuan I think the error is a little bit misleading, but it looks like the pod the VM is running in does not seem to have write permission: `chown /var/run/kubevirt-private/vmi-disks/harddrive/disk.img: operation not permitted`.
Hello, in this case, do I need to add an initContainers to the yaml that creates the virtual machine? Write it like this:
```
      serviceAccount: jenkins #Pod 需要使用的服务账号
      initContainers:
      - name: fix-permissions
        image: busybox
        command: ["sh", "-c", "chown -R 1000:1000 /var/run/kubevirt-private/vmi-disks/harddrive/"]
        securityContext:
          privileged: true
```

**Comment by newhuangchuan** [comment]
```
$ kubectl  describe pod virt-launcher-windows-nfs-1-45vt9
Events:
  Type     Reason              Age                  From                     Message
  ----     ------              ----                 ----                     -------
  Normal   Scheduled           <unknown>            default-scheduler        Successfully assigned default/virt-launcher-windows-nfs-1-45vt9 to k8s-master
  Warning  FailedAttachVolume  2m28s                attachdetach-controller  AttachVolume.Attach failed for volume "pvc-ff66be46-2051-4210-8562-82e164cbb92f" : attachdetachment timeout for volume pvc-ff66be46-2051-4210-8562-82e164cbb92f
  Warning  FailedMount         2m25s                kubelet, k8s-master      Unable to attach or mount volumes: unmounted volumes=[cdromiso], unattached volumes=[cdromiso harddrive virt-bin-share-dir container-disks ephemeral-disks hotplug-disks libvirt-runtime sockets]: timed out waiting for the condition
  Warning  FailedAttachVolume  18s (x8 over 2m27s)  attachdetach-controller  AttachVolume.Attach failed for volume "pvc-ff66be46-2051-4210-8562-82e164cbb92f" : rpc error: code = DeadlineExceeded desc = Failed to attach volume pvc-ff66be46-2051-4210-8562-82e164cbb92f to node k8s-master
  Warning  FailedMount         7s                   kubelet, k8s-master      Unable to attach or mount volumes: unmounted volumes=[cdromiso], unattached volumes=[sockets cdromiso harddrive virt-bin-share-dir container-disks ephemeral-disks hotplug-disks libvirt-runtime]: timed out waiting for the condition
```

**Comment by newhuangchuan** [comment]
Hello, I checked the directory of my failed virtual machine pod and found that his user and user group are incorrect, but it seems that the manual modification cannot be successful.
```
Events:
  Type     Reason            Age                       From                         Message
  ----     ------            ----                      ----                         -------
  Normal   SuccessfulCreate  40s                       virtualmachine-controller    Created virtual machine pod virt-launcher-windows-nfs-1-fltdx
  Warning  SyncFailed        <invalid> (x13 over 20s)  virt-handler, huangchuan-pc  server error. command SyncVMI failed: "preparing host-disks failed: chown /var/run/kubevirt-private/vmi-disks/cdromiso/disk.img: operation not permitted"
[uos@k8s-master LiveMigratable]$ kubectl  exec -ti virt-launcher-windows-nfs-1-fltdx bash
kubectl exec [POD] [COMMAND] is DEPRECATED and will be removed in a future version. Use kubectl kubectl exec [POD] -- [COMMAND] instead.
Defaulting container name to compute.
Use 'kubectl describe pod/virt-launcher-windows-nfs-1-fltdx -n default' to see all of the containers in this pod.
bash-5.0# cd /var/run/kubevirt-private/vmi-disks/cdromiso/
bash-5.0# ls
disk.img
bash-5.0# ls -lh
total 5.4G
-rw-rw---- 1 1001 1000 6.2G Nov  5 02:27 disk.img
bash-5.0# chown -R qemu:qemu *
chown: changing ownership of 'disk.img': Operation not permitted
```

Do you have any other suggestions or methods?

**Comment by xpivarc** [comment]
Hi @newhuangchuan 
Are you running `NonRootExperimental` feature? Also, can you check Selinxu|Apparmor just in case?

**Comment by rmohr** [comment]
> Hello, I checked the directory of my failed virtual machine pod and found that his user and user group are incorrect, but it seems that the manual modification cannot be successful.

@newhuangchuan if you have a writable PVC, you will have to ensure that the underlying storage provider provides them writable to the Pod/VM. Seems like the underlying storage does not provide the storage in a correct form.

**Comment by newhuangchuan** [comment]
> > Hello, I checked the directory of my failed virtual machine pod and found that his user and user group are incorrect, but it seems that the manual modification cannot be successful.
> 
> @newhuangchuan if you have a writable PVC, you will have to ensure that the underlying storage provider provides them writable to the Pod/VM. Seems like the underlying storage does not provide the storage in a correct form.

I looked for the reason, the directory `/var/run/kubevirt-private/vmi-disks` in the normal virtual machine, his user and user group are `qemu:qemu`, but the nfs I used is ` 1001: 1000`, maybe this is the reason.
At present, my nfs uses Truenas storage method, his permissions seem to be unable to achieve the `no_root_squash` in nfs, so I uninstalled this shared storage, and then created a nfs storage through other Linux operating systems To support my kubernetes cluster.
For now, my virtual machine can run normally.

**Comment by newhuangchuan** [comment]
> NonRootExperimental

Thank you very much for your help. My firewall and `selinux` are both disabled. May I ask, what is the function of this `NonRootExperimental`? Is he also written in `kubevirt-cr.yaml`?

**Comment by newhuangchuan** [comment]
> 嗨@newhuangchuan 你在运行`NonRootExperimental`功能吗？另外，你能不能看看Selinxu|Apparmor以防万一？

Thank you very much for your help. My firewall and `selinux` are both disabled. May I ask, what is the function of this `NonRootExperimental`? Is he also written in `kubevirt-cr.yaml`?

**Comment by newhuangchuan** [comment]
@rmohr 
Sorry, I have a problem here, that is, in my kubevirt cluster, the shared storage of nfs used by my back-end storage is mounted in all stages of me, then my virtual machine on node1 If you want to migrate to node2 or node3 in real time, it will still copy the memory pages and disk blocks, because it is already shared storage. My idea is that there will be no copying process, but my migration The process still tells me that `block node is read only`, so it cannot be migrated? I don’t know what you can do here?

**Comment by rmohr** [comment]
> @rmohr
> Sorry, I have a problem here, that is, in my kubevirt cluster, the shared storage of nfs used by my back-end storage is mounted in all stages of me, then my virtual machine on node1 If you want to migrate to node2 or node3 in real time, it will still copy the memory pages and disk blocks, because it is already shared storage. My idea is that there will be no copying process, but my migration The process still tells me that `block node is read only`, so it cannot be migrated? I don’t know what you can do here?

@newhuangchuan if you mount the storage on the node yourself, then it looks for kubevirt like local storage. Is that what you do? You will have to mount your NFS share via a PV/PVC, then we detect it correctly as shared storage and do not copy anything.

**Comment by rmohr** [comment]
> it will still copy the memory pages and disk blocks, because it is already shared storage. My idea is that there will be no copying process, but my migration The process still tells me that `block node is read only`, so it cannot be migrated?

I think I don't fully understand the context. Memory always has to be copied always.

**Comment by wonleing** [comment]
> > it will still copy the memory pages and disk blocks, because it is already shared storage. My idea is that there will be no copying process, but my migration The process still tells me that `block node is read only`, so it cannot be migrated?
> 
> I think I don't fully understand the context. Memory always has to be copied always.

newhuangchuan wanted to say: He is using a shared storage (longhorn), Is it really necessary to copy the VM image during VM migration (from one node to another)? Why it complain 'block node is read only'? And how to resolve it?

**Comment by rmohr** [comment]
> newhuangchuan wanted to say: He is using a shared storage (longhorn), Is it really necessary to copy the VM image during VM migration (from one node to another)? Why it complain 'block node is read only'? And how to resolve it?

I am not entirely sure, but it looks like Longhorn would potentially need extra handling in kubevirt. Looping in some storage people: @mhenriks @awels

**Comment by newhuangchuan** [comment]
> > 新黄川想说：他用的是共享存储（longhorn），VM迁移（从一个节点到另一个节点）的时候真的需要复制VM镜像吗？为什么它抱怨“块节点是只读的”？以及如何解决？
> 
> 我不完全确定，但看起来 Longhorn 可能需要在 kubevirt 中进行额外处理。在一些存储人员中循环：@mhenriks @awels

NFS also has this error.
How to detect that it is shared storage?

**Comment by newhuangchuan** [comment]
> > newhuangchuan wanted to say: He is using a shared storage (longhorn), Is it really necessary to copy the VM image during VM migration (from one node to another)? Why it complain 'block node is read only'? And how to resolve it?
> 
> I am not entirely sure, but it looks like Longhorn would potentially need extra handling in kubevirt. Looping in some storage people: @mhenriks @awels

NFS also has this error.
How to detect that it is shared storage?

**Comment by rmohr** [comment]
> NFS also has this error.
> How to detect that it is shared storage?

Can we untangle the two problems? Seems like you report two issues

1. `block node is read only` do you see this on NFS and longhorn?
2. you wrote `it will still copy the [...] disk blocks`. What do you mean by that? How do you see that it copies the PVC?

**Comment by newhuangchuan** [comment]
> > NFS also has this error.
> > How to detect that it is shared storage?
> 
> Can we untangle the two problems? Seems like you report two issues
> 
> 1. `block node is read only` do you see this on NFS and longhorn?
> 2. you wrote `it will still copy the [...] disk blocks`. What do you mean by that? How do you see that it copies the PVC?

The migration is currently carried out in nfs, and the prompts are as follows:
```
Events:
  Type     Reason            Age                    From                         Message
  ----     ------            ----                   ----                         -------
  Normal   SuccessfulCreate  25m                    virtualmachine-controller    Created virtual machine pod virt-launcher-windows-nfs-1-tnknn
  Normal   Started           25m                    virt-handler, huangchuan-pc  VirtualMachineInstance started.
  Normal   SuccessfulCreate  10m                    virtualmachine-controller    Created PodDisruptionBudget kubevirt-migration-pdb-migration-job
  Normal   SuccessfulDelete  10m                    disruptionbudget-controller  Deleted PodDisruptionBudget kubevirt-migration-pdb-migration-job
  Normal   PreparingTarget   8m54s                  virt-handler, wjr-pc         Migration Target is listening at 192.168.1.10, on ports: 38337,39137,35941
  Normal   PreparingTarget   8m54s (x2 over 8m54s)  virt-handler, wjr-pc         VirtualMachineInstance Migration Target Prepared.
  Normal   Migrating         8m52s (x4 over 8m54s)  virt-handler, huangchuan-pc  VirtualMachineInstance is migrating.
  Warning  SyncFailed        8m51s                  virt-handler, huangchuan-pc  server error. command Migrate failed: "migration job already executed"
  Warning  Migrated          8m51s                  virt-handler, huangchuan-pc  VirtualMachineInstance migration uid a558b8fd-258e-498f-8373-a5fb9611fc41 failed. reason:Live migration failed error encountered during MigrateToURI3 libvirt api call: virError(Code=1, Domain=10, Message='internal error: unable to execute QEMU command 'block-export-add': Block node is read-only')
  Normal   Created           3m50s (x15 over 25m)   virt-handler, huangchuan-pc  VirtualMachineInstance defined.
```
About `it will still copy the [...] disk blocks` ，I think so：
It should be displayed only when the disk block is copied. Maybe my idea is wrong, so let's see how you implemented it.

**Comment by rmohr** [comment]
> About `it will still copy the [...] disk blocks` ，I think so：
> It should be displayed only when the disk block is copied. Maybe my idea is wrong, so let's see how you implemented it.

Ok, I think what may not be obvious is that you also defined a disk which is not on shared storage:

```
      - containerDisk:
          image: kubevirt/virtio-container-disk
          imagePullPolicy: Never
```

kubevirt automatically creates an overlay file and will copy it if something gets modified. So I think this may be related to the cdrom drive which is read-only by default. This is probably related to https://github.com/kubevirt/kubevirt/pull/5020. However that fix should be in 0.41 already.

To try out if it is a similar issue, can you make the cdrom writeable by setting `readonly` to false:

```yaml
          - cdrom:
              bus: sata
              readonly: false
            name: virtiocontainerdisk
```

That was a workaround for this bug.

@vladikr FYI

**Comment by newhuangchuan** [comment]
> > About `it will still copy the [...] disk blocks` ，I think so：
> > It should be displayed only when the disk block is copied. Maybe my idea is wrong, so let's see how you implemented it.
> 
> Ok, I think what may not be obvious is that you also defined a disk which is not on shared storage:
> 
> ```
>       - containerDisk:
>           image: kubevirt/virtio-container-disk
>           imagePullPolicy: Never
> ```
> 
> kubevirt automatically creates an overlay file and will copy it if something gets modified. So I think this may be related to the cdrom drive which is read-only by default. This is probably related to #5020. However that fix should be in 0.41 already.
> 
> To try out if it is a similar issue, can you make the cdrom writeable by setting `readonly` to false:
> 
> ```yaml
>           - cdrom:
>               bus: sata
>               readonly: false
>             name: virtiocontainerdisk
> ```
> 
> That was a workaround for this bug.
> 
> @vladikr FYI

Thank you very much, this method is very useful and has been successfully migrated
I tested it while looking at the official document（https://kubevirt.io/user-guide/）, but the document does not seem to mention anything like this. For now, is there any relevant and complete document for reference?

**Comment by rmohr** [comment]
> Thank you very much, this method is very useful and has been successfully migrated
> I tested it while looking at the official document（[https://kubevirt.io/user-guide/）](https://kubevirt.io/user-guide/%EF%BC%89), but the document does not seem to mention anything like this. For now, is there any relevant and complete document for reference?

@newhuangchuan no, there is no documentation reference. Especially since you should not have experienced that issue in `0.41.2`. I wonder why you still see it. @vladikr would be great if you can have a look.

**Comment by newhuangchuan** [comment]
> > Thank you very much, this method is very useful and has been successfully migrated
> > I tested it while looking at the official document（[https://kubevirt.io/user-guide/）](https://kubevirt.io/user-guide/%EF%BC%89), but the document does not seem to mention anything like this. For now, is there any relevant and complete document for reference?
> 
> @newhuangchuan no, there is no documentation reference. Especially since you should not have experienced that issue in `0.41.2`. I wonder why you still see it. @vladikr would be great if you can have a look.

Okay, thank you very much for your help.

**Comment by newhuangchuan** [comment]
> > Thank you very much, this method is very useful and has been successfully migrated
> > I tested it while looking at the official document（[https://kubevirt.io/user-guide/）](https://kubevirt.io/user-guide/%EF%BC%89), but the document does not seem to mention anything like this. For now, is there any relevant and complete document for reference?
> 
> @newhuangchuan no, there is no documentation reference. Especially since you should not have experienced that issue in `0.41.2`. I wonder why you still see it. @vladikr would be great if you can have a look.


Hello, I have a question here. Now when I am performing live migration, I write this `vmim` resource as follows:
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstanceMigration
metadata:
  name: migration-job
spec:
  vmiName: windows-longhorn-1
```
I saw that this content does not seem to specify which node to migrate the virtual machine to. If I migrate in a large cluster, how can I migrate it to the designated node in real time?

**Comment by rmohr** [comment]
> I saw that this content does not seem to specify which node to migrate the virtual machine to. If I migrate in a large cluster, how can I migrate it to the designated node in real time?

The idea is that your VMs have all the necessary requirements configured (node selectors, affinities, ...) and then the k8s scheduler is doing the rest. Like for any other workload on the k8s cluster. Do you have a use-case where VMs need to go to special nodes but Pods do not have to?

**Comment by rmohr** [comment]
You may find the discussion in this thread interesting: https://github.com/kubevirt/kubevirt/pull/6550

**Comment by newhuangchuan** [comment]
> You may find the discussion in this thread interesting: #6550

Hello, I have a question about the storage part. If I use the `kubernetes` cluster's own `local` storage,I found that the created virtual machine itself gives 100G of storage, but performs `du -sh *`in the local directory. It is found that his size is indeed around 60G. Will his capacity increase dynamically with the use of virtual machines?

**Comment by awels** [comment]
> > You may find the discussion in this thread interesting: #6550
> 
> Hello, I have a question about the storage part. If I use the `kubernetes` cluster's own `local` storage,I found that the created virtual machine itself gives 100G of storage, but performs `du -sh *`in the local directory. It is found that his size is indeed around 60G. Will his capacity increase dynamically with the use of virtual machines?

Hi, no the PVs are statically created, and the capacity value doesn't have actually have any meaning with regards to the actual available space. I am guessing you are using minikube in that particular case?

**Comment by newhuangchuan** [comment]
> > > You may find the discussion in this thread interesting: #6550
> > 
> > 
> > Hello, I have a question about the storage part. If I use the `kubernetes` cluster's own `local` storage,I found that the created virtual machine itself gives 100G of storage, but performs `du -sh *`in the local directory. It is found that his size is indeed around 60G. Will his capacity increase dynamically with the use of virtual machines?
> 
> Hi, no the PVs are statically created, and the capacity value doesn't have actually have any meaning with regards to the actual available space. I am guessing you are using minikube in that particular case?

Hello, I am using a regular kubernetes cluster, and then I found the problem after creating pv and pvc.
Can I understand it this way? The pv and the volume created are not a completely fixed value. The part used by the pod can exceed the capacity of the PV. Can I understand it this way?

**Comment by awels** [comment]
> Hello, I am using a regular kubernetes cluster, and then I found the problem after creating pv and pvc. Can I understand it this way? The pv and the volume created are not a completely fixed value. The part used by the pod can exceed the capacity of the PV. Can I understand it this way?

So the answer to that question is a little complex. Kubernetes uses a number of factors when binding a PVC to a PV. It matches on storage class (if used), accessModes, volumeMode, and size. Now assuming storageclass/accessModes/volumeMode between the PVC and PV match, it checks if the capacity value of the PV >= the request size value of the PVC. If that is the case then it can bind the PV and PVC.

Whatever/Whomever creates the PV, can set the capacity to any value it wishes, In general if you have a dynamic provisioner, that dynamically creates some storage (like rook-ceph) it will set the capacity to the actually available space in that volume. But other provisioners that use existing volumes, will set it to the available space on that volume. Take for instance the [kubevirt hostpath provisioner](github.com/kubevirt/hostpath-provisioner) it will point to an existing directory on the host, and any PVs it creates will be of the total size of the space of the volume that directory is on. So lets say that is 100Gi. Now if you request a PVC of size 10Gi, the provisioner will create a PV with size 100Gi (because that is the potential usable space, even if the current available space is less than that), and kubernetes will bind the PVC to the PV. Now whatever pod uses the PVC can write up to the 100Gi even though the PVC only requested 10Gi. For this particular provisioner there is no mechanism limiting what the user of the PVC can write.

Hopefully this wasn't too confusing, it can be hard to explain that you don't always get the exact space you requested in your PVC, sometimes you get more.

**Comment by newhuangchuan** [comment]
alright, thank you very much
