### ISSUE TITLE
Support IPv6 single-stack

### ISSUE THREAD

**Issue by phoracek** [kubevirt/kubevirt#6732]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

#6322 

**What happened**:

KubeVirt is currently tested with IPv4+IPv6 dual-stack where IPv4 is used as the primary addressing for the control plane.

Some cluster may be built with IPv6 addressing only. This use-case should be considered and supported by KubeVirt.

**What you expected to happen**:

* KubeVirt CI should cover IPv6 single-stack clusters
* KubeVirt control plane should support IPv6 addressing
* KubeVirt VMs should communicate through IPv6 single-stack primary CNI

**Anything else we need to know?**:

All PRs related to this effort should link back to this tracker.

The current target date is April 2022.

**Comment by knfoo** [comment]
Is the current target date still April 22 ?
We are planing to deploy clusters in IPv6 single-stack by that time and we are using KubeVirt so it would be super great.

**Comment by AlonaKaplan** [comment]
Relevant PRs-
https://github.com/kubevirt/kubevirt/pull/7158
https://github.com/kubevirt/kubevirt/pull/7435
https://github.com/kubevirt/kubevirt/pull/7520
https://github.com/kubevirt/kubevirt/pull/7431

**Comment by phoracek** [comment]
The user-guide was updated. @knfoo the feature should be a part of https://github.com/kubevirt/kubevirt/releases/tag/v0.52.0, could you give it a shot? https://kubevirt.io/user-guide/virtual_machines/interfaces_and_networks/#masquerade-ipv6-single-stack-support

**Comment by knfoo** [comment]
@phoracek Awesome :rocket: I will give it a go
