### ISSUE TITLE
Support nic hotplug / hot-unplug

### ISSUE THREAD

**Issue by maiqueb** [kubevirt/kubevirt#6733]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind enhancement
#6322

**What happened**:
Hot-plug / hot-unplug (add / remove) nics to running VMs is an industry standard available in multiple platforms, allowing the dynamic attachment of L2 networks. This is useful when the workload (VM) cannot tolerate a restart when attaching / removing networks, of for scenarios where, for instance, the workload is created prior to the network.

This would help bridge the gap between KubeVirt's feature set and what the user base expects from it.

**What you expected to happen**:
- Adding network interfaces to running VMs. 
- Removing networking interfaces from running VMs. 
- A VM can have multiple interfaces connected to the same (secondary) network(s).

**Anything else we need to know?**:
All PRs related to this effort should link back to this tracker.

The current target date is Summer 2022.

Link to (approved) [design document](https://github.com/kubevirt/community/blob/main/design-proposals/nic-hotplug/nic-hotplug.md).

Hot-plugging interfaces into the pod is currently being worked on, in the [multus project](https://github.com/k8snetworkplumbingwg/multus-cni/).

**Comment by maiqueb** [comment]
It is still not yet possible to hotplug interfaces into a pod, which is currently blocked on Blocked waiting for https://github.com/k8snetworkplumbingwg/multus-cni/pull/777 

As such, we should adjust our expectations: it is impossible to have this available in KubeVirt by Summer 2022.

**Comment by chinglinwen** [comment]
I'd say this is a critical feature to have. hope it merged soon.

**Comment by maiqueb** [comment]
> This is a critical feature to have. hope it merged soon.

I've asked the multus maintainers what are their plans for releasing multus v4, and their plans on a timeline for hotplug in multus in this [discussion](https://github.com/k8snetworkplumbingwg/multus-cni/discussions/853). I suggest you track it @chinglinwen .

Depending on the answer there we can plan the KubeVirt part **or** come up with a design alternative for hot-plugging interfaces into the launcher pod that does not involve multus.

**Comment by maiqueb** [comment]
/remove-lifecycle stale

Lately [multus-v4](https://github.com/k8snetworkplumbingwg/multus-cni/pull/893) was merged to master, which enables 3rd party controllers from directly invoking delegate add / delete.

I've kicked up this [controller](https://github.com/maiqueb/multus-dynamic-networks-controller) project (currently in the works) that will enable pod network selection element changes to hot[plug/unplug] into pods.

**Comment by poojaghumre** [comment]
Is this planned for the next kubevirt release?

**Comment by maiqueb** [comment]
We're trying to get it ready. The [code](https://github.com/kubevirt/kubevirt/pull/6852) works, but we're evaluating if the proposed design can be improved / simplified.

**Comment by maiqueb** [comment]
A follow-up to this issue (to provide the **unplug** counterpart) is available in #9383.
