### ISSUE TITLE
dataVolumeTemplates importer permissions

### ISSUE THREAD

**Issue by timbuchwaldt** [kubevirt/kubevirt#6740]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
When running in a cluster with restricted rights the dataVolumeTemplates feature fails due to runAsNonRoot: ` Error: container has runAsNonRoot and image will run as root`. It would be helpful if there would be the possibility to e.g. inject security setting, specify a role to be created or the likes so the CDI can run in contexts where this is necessary.

**What you expected to happen**:
Import of image.

**How to reproduce it (as minimally and precisely as possible)**:
Run a cluster with strict security policy and import an image

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.46.1
- Kubernetes version (use `kubectl version`): 1.21.6
- VM or VMI specifications: na
- Cloud provider or hardware configuration: On-prem kubespray
- OS (e.g. from /etc/os-release): Ubuntu 20.04
- Kernel (e.g. `uname -a`): 5.4.0-80-generic
- Install tools:
- Others:

**Comment by alicefr** [comment]
@timbuchwaldt could you please open the same issue under [CDI](https://github.com/kubevirt/containerized-data-importer) ?
