### ISSUE TITLE
SRIOV lane periodic flakes: VMI failed to start due to missing permissions on /dev/vfio/vfio device

### ISSUE THREAD

**Issue by ormergi** [kubevirt/kubevirt#6771]
**What happened**:
The k8s-1.19 SRIOV lane failed on periodic jobs

Periodic jobs:
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.19-sriov/1453481832623378432
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.19-sriov/1456199571733483520
SearchCI
https://search.ci.kubevirt.io/?search=%2Fdev%2Fvfio%2Fvfio%3A+Permission+denied&maxAge=336h&context=1&type=build-log&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job
TestGrid
https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.19-sriov

**What do we see:**
Test fail with the following error:
```
tests/network/vmi_multus.go:1061
Unexpected Warning event received: testvmi-plpkp,392378b0-8ef6-4241-a066-14d055876c4d: server error. 
command SyncVMI failed: "
    LibvirtError(Code=1, Domain=10, Message='internal error: 
        qemu unexpectedly closed the monitor: 
            2021-11-04T10:57:09.806965Z qemu-kvm: warning: host doesn't support requested feature: CPUID.40000001H:EAX.kvm-asyncpf-int [bit 14]
            2021-11-04T10:57:09.827813Z qemu-kvm: -device vfio-pci,host=0000:af:04.7,id=ua-sriov-sriov-vlan,bus=pci.6,addr=0x0: vfio 0000:af:04.7: failed to setup container for group 106: failed to open /dev/vfio/vfio: Permission denied')"
Expected
    <string>: Warning
not to equal
    <string>: Warning
tests/utils.go:387
```

#### Notes:
- As part of cluster-up we configure `/dev/vfio/vfio` with `chmod 666`, also when loading `vfio` kmodule 
  (or `vfio-pci` that requires it) it changes permissions of `/dev/vfio/vfio` to 666.
  According to the log the `chmod` command did not returned an error and the `vfio` modules are loaded:
  - On artifacts/build-log.txt,  looked for `grep vfio_pci /proc/modules` and `chmod 666 /dev/vfio/vfio` keywords.

- I verified that the VF we attach to the VM is valid; that it actually a VF of the PF we attach to the node that VMI is scheduled on
   On build-log.txt we see the VF PCI address that mentioned at the error message, we should see it configured:
   ```
   10:30:05: ++ docker exec sriov-worker bash -c 'ls -l /sys/class/net/*/device/virtfn*'
   ...
   10:30:05: lrwxrwxrwx. 1 root root 0 Nov  4 10:28 /sys/class/net/eth4/device/virtfn23 -> ../0000:af:04.7
   ```
   Then compare with the failing VMI state on Status.nodeName, it should be the same node as mentioned on the command above - (`sriov-worker`).

- Not sure if the `vfio` device is failed to attach due to the missing feature that is mentioned on the error above.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by ormergi** [comment]
Seen on
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.19-sriov/1463447537674358784
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.19-sriov/1462903912943063040
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.19-sriov/1456199571733483520
https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.19-sriov/1453481832623378432

**Comment by ormergi** [comment]
Verified with virt team, the `qemu-kvm: warning: host doesn't support requested feature: CPUID.40000001H:EAX.kvm-asyncpf-int [bit 14]` log message suggests libvirt passing unsupported feature to qemu.
It doesn't cause the permission error we see next.

**Comment by ormergi** [comment]
The QEMU version that Kubevirt runs seems to include a patch that force enable ` kvm-asyncpf-int` feature for newer  rhelmachine types (e.g RHEL 8.5) while the CI node the failing jobs were scheduled on runs older OS/Kernel versions.

It may explain why we see this on SRIOV lane which runs on a containerized k8s cluster (KinD based provider) in contrast to other sig-lanes which runs with virtualized k8s cluster (QEMU VM based provider), 
the latter runs CentOS Streams which probably have newer binaries than what the CI node have.

**Comment by andreabolognani** [comment]
Yeah, I would say the actual issue is the one with permissions and the CPU feature warning is just a red herring.

You checked that the `chmod` call shows up in the log, but how about adding a call to `ls -l` for good measure?

I'm unclear on why the cluster setup script needs to do this in the first place. In regular deployments, doesn't virt-handler request access to the `/dev/vfio` itself using the device plugin API? Why can't the same thing happen for the CI test lane instead of having custom code for that?

Anyway, the fact that this test flakes rather than failing every single time suggests that there might be a timing issue at play. Maybe the permissions are adjusted and then something else comes around to reset them? Or the attempt to start the VM is kicked off too early for some reason?

**Comment by ormergi** [comment]
> You checked that the `chmod` call shows up in the log, but how about adding a call to `ls -l` for good measure?

Good point, we dont print the its state to the logs, I will do that.

> I'm unclear on why the cluster setup script needs to do this in the first place. In regular deployments, doesn't virt-handler request access to the `/dev/vfio` itself using the device plugin API? Why can't the same thing happen for the CI test lane instead of having custom code for that?
> 
virt-handler device plugin does not handle SRIOV devices, for that we deploy [sriov-device-plugin](https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin) and [sriov-cni](https://github.com/k8snetworkplumbingwg/sriov-cni) in order to provision virt-launcher pods with the SR-IOV VF resource.
Thus we need to some configurations "manually", here are the highlights of what cluster setup script does:
- Move SR-IOV PF to each cluster node network namespace (this is why we use containerized cluster).
- Load `vfio` kernel module (if its not already loaded).
- Chmod /dev/vfio permissions.
- Create the VF's (if they are not exists yet) and bound them to `vfio-pci` driver.

> Anyway, the fact that this test flakes rather than failing every single time suggests that there might be a timing issue at play. Maybe the permissions are adjusted and then something else comes around to reset them? Or the attempt to start the VM is kicked off too early for some reason?

Could be, I will start with printing /dev/vfio permission as first step, and look into this direction

@andreabolognani  Thanks again for looking into this as well and your feedback, I appreciate it :slightly_smiling_face:

**Comment by andreabolognani** [comment]
> virt-handler device plugin does not handle SRIOV devices, for that we deploy [sriov-device-plugin](https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin) and [sriov-cni](https://github.com/k8snetworkplumbingwg/sriov-cni) in order to provision virt-launcher pods with the SR-IOV VF resource.
> Thus we need to some configurations "manually"

I probably got the nomenclature wrong and most of the details simply fly over my head, but my point is: if virt-handler expects SRIOV devices to be set up by external components in a production cluster, can't we get the same external components running in the CI cluster as well?

Having our own implementation of the SRIOV handling logic that's specific to the CI cluster sounds like it's not only additional maintenance work, but more importantly an opportunity for introducing mismatches which result in either CI failures that wouldn't actually show up in a production environment or production failures that aren't caught by CI. In other words we're not testing the real thing, which significantly reduces the value of running the tests in the first place.

I'm sure there's a good reason why this is happening and I'm simply not familiar enough with the problem space to realize it :)
