### ISSUE TITLE
Remove kubevirt-config traces, since the configmap is deprecated for more than one year

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#6779]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind enhancement

**What happened**:

We deprecated kubevirt-config more than a year ago: https://groups.google.com/g/kubevirt-dev/c/_mJP0RilTd4/m/xdrfk1JABgAJ.

As @nunnatsa pointed out, we still have it in the code.

**What you expected to happen**:

Let's remove it for 0.48.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@nunnatsa leaving you the honor of removing it, if you like :)

**Comment by nunnatsa** [comment]
> @nunnatsa leaving you the honor of removing it, if you like :)

Done: https://github.com/kubevirt/kubevirt/pull/6784
