### ISSUE TITLE
Need dedicated KubeVirt operator update lane

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#6785]
Release v0.47.0 caused a regression #6763 which impacted the ability to seamlessly update to and from other releases.

The reason this wasn't detected is because our current update tests only execute transitioning from one release to the next using the latest virt-operator. The update is triggered by changing the release in the KubeVirt CR... So same virt-operator transitioning between two kubevirt releases.

We need a dedicated lane which actually installs the previous virt-operator, and triggers the update by applying the new virt-operator... So different virt-operators used to transition between different kubevirt releases.

**Comment by zcahana** [comment]
I'm not sure a dedicated lane is needed. I've started working on extending the following test[1] to have two table entries, which in one of them it'll perform the upgrade by installing a new operator. I still didn't get all the bits right there, but I hope I can get it to work within the existing lane (while allowing the rest of the tests to continue normally).

[1] https://github.com/kubevirt/kubevirt/blob/ff8ebf3626bf2043f024bcd38377a1a9df4251a3/tests/operator_test.go#L1265
