### ISSUE TITLE
There is a problem with the return value of kubectl, the value of the progress item of the created volume displays as N/A.

### ISSUE THREAD

**Issue by mack1024** [kubevirt/kubevirt#6788]
Starting a new virtual machine from the backup also creates volumes, However, the value of the progress item of the created volume displays N/A, Why is N/A displayed? there is a problem with the return value of kubectl,  I think the display of this value is error.
I analyzed the kubevirt code,  Also, I printed the JSON value of the Progress item , as follows:

{
    "conditions": [
        {
            "error": false, 
            "lastHeartbeatTime": "2021-11-10T11:58:09Z", 
            "lastTransitionTime": "2021-11-10T11:58:09Z", 
            "lastUpdateTime": "2021-11-10T11:58:09Z", 
            "message": "PVC restore-zhguo-host-bak-1ce79a08-3cb7-4075-a31d-67c9a2616036-disk-1 Bound", 
            "reason": "Bound", 
            "status": "True", 
            "transitioning": false, 
            "type": "Bound"
        }, 
        {
            "error": false, 
            "lastHeartbeatTime": "2021-11-10T11:58:09Z", 
            "lastTransitionTime": "2021-11-10T11:58:09Z", 
            "lastUpdateTime": "2021-11-10T11:58:09Z", 
            "status": "True", 
            "transitioning": false, 
            "type": "Ready"
        }, 
        {
            "error": false, 
            "lastHeartbeatTime": "2021-11-10T11:47:40Z", 
            "lastTransitionTime": "2021-11-10T11:47:40Z", 
            "lastUpdateTime": "2021-11-10T11:47:40Z", 
            "status": "False", 
            "transitioning": false, 
            "type": "Running"
        }
    ], 
    "phase": "Succeeded", 
    "progress": "N/A"
}

I want to know where the back-end code of this problem, I think the value of the Progress item should display Running of the last element in the conditions array(Value of type: running), Is this a bug in kubevirt ? Can you help me? thank you.

**Comment by rmohr** [comment]
/assign @zvikorn 

@zvikorn could you have a look if we print already the right information?
