### ISSUE TITLE
Improve documentation around VM and VMI

### ISSUE THREAD

**Issue by VirrageS** [kubevirt/kubevirt#6819]
I'm not sure if I should be creating issue here or in [user-guid repo](https://github.com/kubevirt/user-guide/issues) - let me know!

I was doing some research about VMs and VMIs. But I couldn't find much information about the VM/VMI specification. Also I was searching for some kind of comparison VM vs VMI but I think this is missing as well. I think it would be beneficial to have such documentation to understand which should be used in what situation. It's also very possible that such documentation exists but I couldn't find it - if it does, please let me know and maybe we can move it around for better visibility.

Therefore, I would ask for:
* Add detailed documentation on VM/VMI specs and how each field should be used. Maybe something similar to this: https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.21/#pod-v1-core?
* Add document describing VM and VMI, their differences, similarities, how they relate to each other and explaining what situations should each of them be used. This especially important for `virtctl` I think. I couldn't find a reason why I can do `virtctl pause vm/vmi <xyz>` but I cannot do `virtctl restart vm/vmi <xyz>` (only can `virtctl restart <vm_name>`).
* Describe guarantees for VM and VMI (it's possible to do experiments for those and see what happens but ideally we wouldn't need to create cluster and deploy everything to know such things):
  * What happens when VM restarts? Does IP/name/volumes stay the same?
  * What happens when VMI `compute` container restarts? Is the container restarted and everything stays the same? Or the Pod is marked as failed?

**Comment by rmohr** [comment]
@VirrageS thanks a lot for the detailed description. You may be right that a clear description is indeed missing. You found great questions. By answering them on a core page, like you suggested we would have a great start. I don't know yet who could do that, unless you want to tackle it, but we should definitely do that.

**Comment by mazzystr** [comment]
Hello, We spoke of this req in the community call bug scrub.

Would you be willing to create a new page or modify an existing page in [user-guide](https://github.com/kubevirt/user-guide) with what you would like to see as a starting point?

**Comment by VirrageS** [comment]
KUBE_COVER

**Comment by maiqueb** [comment]
@cwilkers / @aburdenthehand where do you think this clarification should take place ? 

/remove-lifecycle stale

**Comment by aburdenthehand** [comment]
@maiqueb Thanks for taking this on.
I think a standalone md in the 'Virtual Machines' section makes sense. At the top, above `virtual_machine_instances.md`. That way we would start with the concept differentiating the two objects, followed by further information about VMIs, and then creating VMs.

**Comment by cwilkers** [comment]
To clarify, this would be in the user-guide repo. 
(I am at the same time apologetic and relieved I only missed this issue for more than a year because it was filed against kubevirt/kubevirt :-)

**Comment by maiqueb** [comment]
For anyone interested I've pushed this draft PR: https://github.com/kubevirt/user-guide/pull/692

**Comment by maiqueb** [comment]
> As I was starting to review the PR, I started at the top level of our netlify preview site, and found this: https://kubevirt.io/user-guide/architecture/#virtualmachine
> 
> I think it's okay to have both, and it might even be a good idea to reorganize some of the more specific content from the /architecture page to the new /virtualmachines page, and simplify the /architecture page with the high level view you're adding to the /virtualmachines page.
> 
> What do you (all) think?

I'm good with having a single page for it. Especially if it is the first item on the list.
