### ISSUE TITLE
sound device in the VMI yaml has no name

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#6828]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind enhancement

**What happened**:

#6650 introduced sound devices. I made a mistake on the review and did not request for it to get a `name` on the yaml and a corresponding `alias` on the domain xml.

**What you expected to happen**:

There should be a name:

```
spec:
  domain:
    devices:
      sound:
        name: mydevice
```

All configurable devices require names, to be for instance trackable with device role tagging.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
/assign @victortoso 

Sorry I missed this point on your PR.

**Comment by victortoso** [comment]
Aha, sorry that I missed that too. I'll rework this Today (in a few hours).
