### ISSUE TITLE
Insufficient permission for virt-controller service account running on openshift

### ISSUE THREAD

**Issue by lukas-bednar** [kubevirt/kubevirt#684]
When deploying KubeVirt on OpenShift cluster version 3.7.1, I can not create vm because virt-controller doesn't have permission to schedule virt-launcher.

Here is link to script which reproduces my problem (line 30 shouldn't be there in my opinion).
https://gist.github.com/lukas-bednar/7523689241c81a260f77d0302f147a5f

The creation of vm is going to fail on following error.
```
level=error timestamp=2018-01-22T12:45:10.785562Z pos=vm.go:168 component=virt-controller service=http namespace=kube-system name=testvm kind= uid=08c38a32-ff72-11e7-92dc-001a4a16982c reason="pods \"virt-launcher-testvm-----\" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used spec.volumes[0]: Invalid value: \"hostPath\": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: \"hostPath\": hostPath volumes are not allowed to be used provider restricted: .spec.containers[0].securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used]" msg="Defining a target pod for the VM failed."
level=info timestamp=2018-01-22T12:45:10.786499Z pos=vm.go:94 component=virt-controller service=http reason="pods \"virt-launcher-testvm-----\" is forbidden: unable to validate against any security context constraint: [provider restricted: .spec.securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used spec.volumes[0]: Invalid value: \"hostPath\": hostPath volumes are not allowed to be used spec.volumes[1]: Invalid value: \"hostPath\": hostPath volumes are not allowed to be used provider restricted: .spec.containers[0].securityContext.hostPID: Invalid value: true: Host PID is not allowed to be used]" msg="reenqueuing VM kube-system/testvm"
```

When executing following line, the vm is scheduled without error.
```
oc adm policy add-scc-to-user privileged system:serviceaccount:kube-system:kubevirt-controller
```
I remember that you created `kubevirt-privileged` SA to separate pods which requires privileged role from others which doesn't need privileged role, like `kubevirt-controller`.

In addition I am not sure whether iscsi-demo pods needs to be privileged as well.
In order to let vm use iscsi volume I had to make `kubevirt-testing` privileged as well (line 34).

If you need more details please let me know.

**Comment by fabiand** [comment]
Good catch @lukas-bednar .

The
```
oc adm policy add-scc-to-user privileged system:serviceaccount:kube-system:kubevirt-controller
```

command needs to go into the ansible playbooks, or am I missing something?

**Comment by lukas-bednar** [comment]
@fabiand yes, this command solves problem.
But there is still Q, whether this is correct way.
Because there are two accounts:
* kubevirt-privileged
* kubevirt-controller
and if we will make both privileged, then the name of first one is misleading, at least in my opinion.
Other option is: the `kubevirt-controller` SA is redundant and we can assign `kubevirt-priivileged` instead.

**Comment by fabiand** [comment]
Oh - good point.

It's actually funny that the controller needs to be privileged, and I suppose this is because it's not privileged it self, but because it's creating a privileged pod.

+1 of dropping the controller SA then for now, and use privileged.

**Comment by karmab** [comment]
agree too here

**Comment by lukas-bednar** [comment]
@simon3z this issue is being addressed by @gbenhaim  in #732 PR, if I am not mistaken.

**Comment by lukas-bednar** [comment]
@simon3z actually no that is different issue, I am sorry.
This is about that we have two privileged SA.
And I don't know if this was fixed because we make this SA privileged always as a workaround here:
https://github.com/kubevirt/kubevirt-ansible/blob/bc09b0290036b2b76397055f279bcb1e9dedd142/roles/kubevirt/tasks/provision.yml#L20

**Comment by fabiand** [comment]
Closing this issue, because the controller has enough privileges in the current state.

it's an enhacement to make these permissions more fine grained.
