### ISSUE TITLE
virtctl ssh to fedora 35 guests is not working

### ISSUE THREAD

**Issue by dominikholler** [kubevirt/kubevirt#6851]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug
> /kind enhancement

**What happened**:
```
  $ virtctl ssh  fedora@example-fedora-35
  ssh: handshake failed: ssh: unable to authenticate, attempted methods [none publickey], no supported methods remain
```
**What you expected to happen**:
to see a ssh promt

**How to reproduce it (as minimally and precisely as possible)**:
create a fedora 35 VM from cloud image and try to login via `virtctl ssh  `

**Anything else we need to know?**:
`virtctl ssh --local-ssh fedora@example-fedora-35` would work fine.

**Environment**:
If there are any doubts, I would provide all detailed versions.

**Comment by dominikholler** [comment]
Is there a way to default to `virtctl ssh --local-ssh` or even disable the internal ssh client?

**Comment by rmohr** [comment]
There is no way to default to it. For context see https://github.com/kubernetes-sigs/cluster-api-provider-kubevirt/issues/19 where I summarized the situation. It will at some point work again when virtctl is compiled with a new enough go version.

**Comment by rmohr** [comment]
Regarding to defaulting, we have an issue filed but no work started on it: https://github.com/kubevirt/kubevirt/issues/6617

**Comment by rmohr** [comment]
Correction, I can just bump the crypto library. Will do that and cc you when I have thing sready.

**Comment by rmohr** [comment]
@dominikholler have a fix ready. DO you already use a ECDSA private key or do you use an RSA key?

**Comment by dominikholler** [comment]
thanks, I have a ssh-rsa key.

**Comment by rmohr** [comment]
/remove-lifecycle stale

still waiting for the crypto fix. We could use my workaround in #6854 , but since only two or three complaints came in so far, I want to wait for the official fix.
