### ISSUE TITLE
Is there any way to allow VM to acquire ip address  from real DHCP server not the k8s network ?

### ISSUE THREAD

**Issue by yun-ling** [kubevirt/kubevirt#6860]
I want to create  a network bridge between VM and real local area network ,which allows other device not in  k8s network can discover  those VMs . Does  kubevirt support this feature?

**Comment by ruslanloman** [comment]
@yun-ling Hi, yes it's possible. Just create linux bridge using appropriate k8s cni and attach it to the VM.

**Comment by yun-ling** [comment]
> @yun-ling Hi, yes it's possible. Just create linux bridge using appropriate k8s cni and attach it to the VM.

Thanks~Now I’m trying using bridge plugin to build the connection

**Comment by yun-ling** [comment]
Now I‘m trying to use Multus + Calico + brige to create multiple network for k8s pods. The Calico is  the major  CNI aiming to  build internal network  for all pods communication .The second bridge CNI is only for kubevirt to expose itself into real local network. This configuration will keep all  k8s pods  still in the internal k8s network but only the kubevirt pod exposed,which I think it's more safe. 

Besides,tutorial about second network interface  of kubevirt is lacking but  I don't know why. I believe the people who are using kubevirt  are eager to  expose VM into local network  not just inside the  cluster.  I suggest kubevirt project put  an multi-network yaml file  into "example" folder so the user  can simplely expose VM into local network  without more configuration.

I will share the procedures  as soon as I success .

**Comment by maiqueb** [comment]
Does [this blog post](https://kubevirt.io/2020/Multiple-Network-Attachments-with-bridge-CNI.html) help you ?

**Comment by yun-ling** [comment]
> Does [this blog post](https://kubevirt.io/2020/Multiple-Network-Attachments-with-bridge-CNI.html) help you ?

Thanks,I've already succeeded in creating second network for VM

**Comment by maiqueb** [comment]
> > Does [this blog post](https://kubevirt.io/2020/Multiple-Network-Attachments-with-bridge-CNI.html) help you ?
> 
> Thanks,I've already succeeded in creating second network for VM

But did the provided post help out or not ? You complained there was no "tutorial about second network interface of kubevirt" but - imo - that blog post is exactly what you wanted. 

What should we do w/ the issue ? Can we close it @yun-ling ?

**Comment by yun-ling** [comment]
> > > Does [this blog post](https://kubevirt.io/2020/Multiple-Network-Attachments-with-bridge-CNI.html) help you ?
> > 
> > 
> > Thanks,I've already succeeded in creating second network for VM
> 
> But did the provided post help out or not ? You complained there was no "tutorial about second network interface of kubevirt" but - imo - that blog post is exactly what you wanted.
> 
> What should we do w/ the issue ? Can we close it @yun-ling ?

Yes,but I didn't find it before. I only search for tutorial in "https://kubevirt.io/user-guide" . This issue can be closed.

**Comment by maiqueb** [comment]
> > What should we do w/ the issue ? Can we close it @yun-ling ?
> 
> Yes,but I didn't find it before. I only search for tutorial in "https://kubevirt.io/user-guide" . This issue can be closed.

OK, cool. I'm considering linking this blog post from the user guide, but I must first understand if there's a precedence for this. 

For now, I'm closing this bug.
/close
