### ISSUE TITLE
how to attach the nvme device plugged in the PCI Express multi root switch to the virtual machine

### ISSUE THREAD

**Issue by liuminjian** [kubevirt/kubevirt#6868]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:

i want to passthrough some nvme devices to vm but the devices is plugged into the PCI Express multi-root switch.how to separate the devices or passthrough all the devices to vm.

![image](https://user-images.githubusercontent.com/7840869/143570297-7b7e621c-79b7-4ed3-8a24-8941fa2c4fc9.png)

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by alicefr** [comment]
@liuminjian have you already check the documentation at https://github.com/kubevirt/user-guide/blob/master/docs/virtual_machines/host-devices.md . There are some limitation for the pass-through and it isn't possible to select the device by using the bus address
