### ISSUE TITLE
Not able to run VMs in kubevirt

### ISSUE THREAD

**Issue by agantuk** [kubevirt/kubevirt#6898]
/kind bug

**What happened**:

I am trying out the scenario noted in https://www.katacoda.com/kubevirt/scenarios/kubevirt-cdi on a local k8s setup. I have created a k8s cluster with kind, installed kubevirt, installed cdi, and am then trying to run the fedora image as noted in the setup.

**What you expected to happen**:

The Fedora image to be downloaded and run in kubevirt.

**How to reproduce it (as minimally and precisely as possible)**:

Follow the steps in https://www.katacoda.com/kubevirt/scenarios/kubevirt-cdi till creating the pvc using pvc_fedora.yml file as noted there. In short, the steps are -

1. Install kubevirt using the 'kubectl create -f http://<kubevirt.yml>'
2. Install kubevirt.io/hostpath-provisioner from https://raw.githubusercontent.com/kubevirt/hostpath-provisioner/main/deploy/kubevirt-hostpath-provisioner.yaml
3. Install cdi using 'kubectl create -f http://<cdi.yml>'
4. Run a VM with the attached file as noted in the website -

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "fedora"
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "https://mirror.23media.com/fedora/linux/releases/34/Cloud/x86_64/images/Fedora-Cloud-Base-34-1.2.x86_64.raw.xz"
    kubevirt.io/provisionOnNode: node01
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5500Mi

**Anything else we need to know?**:

The importer pod stays in pending state. The pvc is also in pending state. No logs are viewable from the importer pod -

**kubectl get pods**
NAME              READY   STATUS    RESTARTS   AGE
importer-fedora   0/1     Pending   0  

**kubectl logs -f importer-fedora**

**kubectl get pvc**
NAME     STATUS    VOLUME   CAPACITY   ACCESS MODES   STORAGECLASS                    AGE
fedora   Pending                                      kubevirt-hostpath-provisioner   28m

**Environment**:
- KubeVirt version (use `virtctl version`): 'virtctl version' output -

Client Version: version.Info{GitVersion:"v0.47.1", GitCommit:"c34de42a48f5564f4fd2c21b6cbda7b96664c65b", GitTreeState:"clean", BuildDate:"2021-11-11T16:01:45Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.47.1-dirty", GitCommit:"c34de42a48f5564f4fd2c21b6cbda7b96664c65b", GitTreeState:"dirty", BuildDate:"2021-11-11T16:20:45Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`): Output -

Client Version: version.Info{Major:"1", Minor:"22", GitVersion:"v1.22.4", GitCommit:"b695d79d4f967c403a96986f1750a35eb75e75f1", GitTreeState:"clean", BuildDate:"2021-11-17T15:48:33Z", GoVersion:"go1.16.10", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.1", GitCommit:"5e58841cce77d4bc13713ad2b91fa0d961e69192", GitTreeState:"clean", BuildDate:"2021-05-21T23:01:33Z", GoVersion:"go1.16.4", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications:
- Cloud provider or hardware configuration: Standard x86 server
- OS (e.g. from /etc/os-release): Ubuntu 20.04.3 LTS"
- Kernel (e.g. `uname -a`): 
 
Linux ubuntu-kubevirt 5.4.0-90-generic #101-Ubuntu SMP Fri Oct 15 20:00:55 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
 
- Install tools:
- Others:

**Comment by alicefr** [comment]
@agantuk it seems to me that the PVC is not provisioned and for this reason the importer cannot start. Could you please check the state of the PVC and the importer pod?
```bash
$ kubectl describe pvc fedora
$ kubectl describe pod importer-fedora
```

**Comment by kobi86** [comment]
Hey @agantuk, does this environment does have access to the internet? Did you added some NNCP that maybe affecting both NS that the CDI and the VM are trying to be downloaded and created?

**Comment by agantuk** [comment]
@alicefr, @kobi86 

Thank you for your replies. I have been trying a different way to upload images so don't have the setup with me currently but I will get back to you with the data very soon since this is an important point for me.

@kobi86 The environment does have access to the internet. Not sure what is meant by NNCP - some sort of network plugin with it's own namespace which is interfering with the fedora image download? I have a basic k8s cluster created by kind and had not installed anything else on it other than kubevirt, cdi, and the host provisioner.

**Comment by agantuk** [comment]
This issue is solved after a discussion on the #virtualization channel on slack for kubernetes where Alexander Wels pointed me to the steps. A summary -

It appears that the steps in the katacoda environment are for an older version of hostpath-provisioner. I did not have hostpath-provsioner installed/setup properly. If it helps, here are the steps to install hostpath-provisioner v0.11.0 -

1. https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.yaml
2. namespace.yaml
2. operator.yaml (need to install in the hostpath-provisioner namespace so add `-n hostpath-provisioner` to the create/apply command)
3. hostpathprovisioner_cr.yaml
4. storageclass-wffc-csi.yaml
5. webhook.yaml

After this, there should be a few pods and daemonsets, etc. running in the hostpath-provisioner namespace.

A few additional points which I found useful -

1. I had a single k8s node so used Immediate VolumeBindingMode rather than WaitForFirstConsumer. This was done by modifying storageclass-wffc-csi.yaml.
2. There is a gist to quickly check if persistent storage and the provisioner is working at https://gist.github.com/awels/2cd80466d57f1fbd83e57e2dd44ed927
3. 'virtctl image-upload' needs the --storage-class param to point to the new storage class.
4. It appears that the storage profile is missing for some reason. If the 'spec' in 'kubectl get storageprofile -n cdi hostpath-csi -o yaml' is empty, we need to create a spec. I used the following -

spec:
  claimPropertySets: 
  - accessModes:
    - ReadWriteOnce
    volumeMode: 
      Filesystem

**Comment by agantuk** [comment]
Just wanted to note that the correct order of installing (kubectl create/apply -f) is -

1. https://github.com/jetstack/cert-manager/releases/download/v1.6.1/cert-manager.yaml
2. webhook.yaml
3. namespace.yaml
4. operator.yaml (need to install in the hostpath-provisioner namespace so add -n hostpath-provisioner to the create/apply command)
5. hostpathprovisioner_cr.yaml
6. storageclass-wffc-csi.yaml
