### ISSUE TITLE
When I add patches to virt-operator, resourceName always fails verification

### ISSUE THREAD

**Issue by wzy109871** [kubevirt/kubevirt#6899]
When I add patches to virt-operator, resourceName always fails verification
==
Here is the content of my YAML file:
==
---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates: []
  customizeComponents: 
    patches:
    - resourceType: Deployment
      resourceName: virt-controller
      patch: '[{"op": "remove", "path": "/spec/template/spec/containers/0/livenessProbe"}]'
      type: json
    - resourceType: Deployment
      resourecName: virt-controller
      patch: '{"metadata":{"annotations":{"patch": "true"}}}'
      type: strategic
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}

==
When I apply, I get the following prompt:
==
[root@m01 kubevirt]# kubectl apply -f kubevirt-cr.yaml 
error: error validating "kubevirt-cr.yaml": error validating data: [ValidationError(KubeVirt.spec.customizeComponents.patches[1]): unknown field "resourecName" in io.kubevirt.v1.KubeVirt.spec.customizeComponents.patches, ValidationError(KubeVirt.spec.customizeComponents.patches[1]): missing required field "resourceName" in io.kubevirt.v1.KubeVirt.spec.customizeComponents.patches]; if you choose to ignore these errors, turn validation off with --validate=false
[root@m01 kubevirt]# kubectl apply -f kubevirt-cr.yaml --validate=false
The KubeVirt "kubevirt" is invalid: spec.customizeComponents.patches.resourceName: Required value

====
The version OF Kubevirt I use is 0.46.1,  how to solve the above problems

**Comment by wzy109871** [comment]
> # When I add patches to virt-operator, resourceName always fails verification
> Here is the content of my YAML file:
> # apiVersion: kubevirt.io/v1
> kind: KubeVirt
> metadata:
> name: kubevirt
> namespace: kubevirt
> spec:
> certificateRotateStrategy: {}
> configuration:
> developerConfiguration:
> featureGates: []
> customizeComponents:
> patches:
> - resourceType: Deployment
> resourceName: virt-controller
> patch: '[{"op": "remove", "path": "/spec/template/spec/containers/0/livenessProbe"}]'
> type: json
> - resourceType: Deployment
> resourecName: virt-controller
> patch: '{"metadata":{"annotations":{"patch": "true"}}}'
> type: strategic
> imagePullPolicy: IfNotPresent
> workloadUpdateStrategy: {}
> # When I apply, I get the following prompt:
> [root@m01 kubevirt]# kubectl apply -f kubevirt-cr.yaml error: error validating "kubevirt-cr.yaml": error validating data: [ValidationError(KubeVirt.spec.customizeComponents.patches[1]): unknown field "resourecName" in io.kubevirt.v1.KubeVirt.spec.customizeComponents.patches, ValidationError(KubeVirt.spec.customizeComponents.patches[1]): missing required field "resourceName" in io.kubevirt.v1.KubeVirt.spec.customizeComponents.patches]; if you choose to ignore these errors, turn validation off with --validate=false [root@m01 kubevirt]# kubectl apply -f kubevirt-cr.yaml --validate=false The KubeVirt "kubevirt" is invalid: spec.customizeComponents.patches.resourceName: Required value
> 
> ==== The version OF Kubevirt I use is 0.46.1, how to solve the above problems

**Comment by fossedihelm** [comment]
Hi @wzy109871, thanks. As replied in the [group](https://groups.google.com/g/kubevirt-dev/c/qIC3Nvjsm4s/m/o8Jkt40XBAAJ?utm_medium=email&utm_source=footer), there was a typo in the yaml file (resourecName instead resourceName). This PR [#507](https://github.com/kubevirt/user-guide/pull/507) fixed that. Thanks
