### ISSUE TITLE
Import Virtual Machine images for Kubevirt using CDI

### ISSUE THREAD

**Issue by rupipal** [kubevirt/kubevirt#6915]
Hi,
Following https://kubevirt.io/labs/kubernetes/lab2  I am trying to set up the VM on minkube installation minikube v1.23.2 on Debian 11.1 Kubernetes v1.22.2.  The importer pod seems to end with the following errors:

$kubectl logs -f importer-fedora
I1207 09:40:33.240770       1 importer.go:77] Starting importer
I1207 09:40:33.241418       1 importer.go:113] begin import process
I1207 09:40:36.171172       1 data-processor.go:340] Calculating available size
I1207 09:40:36.171223       1 data-processor.go:352] Checking out file system volume size.
I1207 09:40:36.171237       1 data-processor.go:360] Request image size not empty.
I1207 09:40:36.171247       1 data-processor.go:365] Target size 5Gi.
I1207 09:40:36.913332       1 nbdkit.go:269] Waiting for nbdkit PID.
I1207 09:40:37.414105       1 nbdkit.go:290] nbdkit ready.
I1207 09:40:37.414125       1 data-processor.go:243] New phase: Convert
I1207 09:40:37.414137       1 data-processor.go:249] Validating image
E1207 09:41:07.415825       1 prlimit.go:174] qemu-img failed output is:
E1207 09:41:07.415984       1 prlimit.go:175] 
E1207 09:41:07.415990       1 prlimit.go:176] 
E1207 09:41:07.416395       1 data-processor.go:240] , qemu-img execution failed: signal: killed 
Unable to convert source data to target format
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:224
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:172
main.main
	cmd/cdi-importer/importer.go:120
runtime.main
	GOROOT/src/runtime/proc.go:225
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1371
E1207 09:41:07.417084       1 importer.go:123] , qemu-img execution failed: signal: killed 
Unable to convert source data to target format
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessDataWithPause
	pkg/importer/data-processor.go:224
kubevirt.io/containerized-data-importer/pkg/importer.(*DataProcessor).ProcessData
	pkg/importer/data-processor.go:172
main.main
	cmd/cdi-importer/importer.go:120
runtime.main
	GOROOT/src/runtime/proc.go:225
runtime.goexit
	GOROOT/src/runtime/asm_amd64.s:1371

Could somebody suggest what needs to be fixed?

Thanks
Rps

**Comment by alicefr** [comment]
@rupipal please open the issue under https://github.com/kubevirt/containerized-data-importer for better visibility

**Comment by rupipal** [comment]
Thanks @alicefr  Done.  https://github.com/kubevirt/containerized-data-importer/issues/2053
