### ISSUE TITLE
Discovering differencing disk feature in kubevirt project for the purpose of persistent  storage

### ISSUE THREAD

**Issue by yun-ling** [kubevirt/kubevirt#6928]
For a huge VM cluster,differencing disk is a very  effective  way to reduce space usage.Now I'm modifying source code to make differencing disk become persistent .I've already noticed that the  ephemeral volume and containerDisk are using this kind of disk but they are both temporary.

Why don't you provide a feature to make differencing disk persistent ?Is there any historical reason ?

**Comment by rmohr** [comment]
@yun-ling we rely in kubevirt a lot on PVCs from kubernetes and there we expect that a lot of these features are coming from backends like e.g. Ceph. I think this is mostly the reason. The case you mentioned is very nice for e.g. CI use-cases. What exactly is your use-case you want to cover?

/triage needs-information

**Comment by yun-ling** [comment]
> @yun-ling we rely in kubevirt a lot on PVCs from kubernetes and there we expect that a lot of these features are coming from backends like e.g. Ceph. I think this is mostly the reason. The case you mentioned is very nice for e.g. CI use-cases. What exactly is your use-case you want to cover?
> 
> /triage needs-information

I plan to use k8s to manage a huge VM cluster  which has  more than 40 machines.

For most situation,base  image  can  already satisfy the needs of VM instance. But what if the image is a very large  image?

I'm working on creating macos  image ,of which the size is larger than 30 GB. if user want to create 10 macos VM instances,this action  will take  up  300GB   in the cluster that could  run out of space.

So in this case,the differencing disk is the only option for me .

**Comment by yun-ling** [comment]
It's a goddamn big work to fit my requirement. I have almost lost  in a large quantities of code of virt-handler,virt-controller,virt-launcher but I won't give up.

**Comment by rmohr** [comment]
> For most situation,base image can already satisfy the needs of VM instance. But what if the image is a very large image?

I think the advantage of automatic thin provisioning with e.g. ceph is that if the base ever changes, your VMs will still work as expected (with the expected amount of de-duplication). If you use overlay files, you can easily share the root disks, but when you want to update the root disk due to e.g. a new version it is hard to continue using the overlay disks.

I am curious, did you think about a solution for this too?

**Comment by yun-ling** [comment]
> > For most situation,base image can already satisfy the needs of VM instance. But what if the image is a very large image?
> 
> I think the advantage of automatic thin provisioning with e.g. ceph is that if the base ever changes, your VMs will still work as expected (with the expected amount of de-duplication). If you use overlay files, you can easily share the root disks, but when you want to update the root disk due to e.g. a new version it is hard to continue using the overlay disks.
> 
> I am curious, did you think about a solution for this too?

Version control might be a solution but not so perfect.The version of base image must correspond with the overlay disk.Another solution is applying patch to the currently  existing  VM instance which has one or more overlay disks instead of directly upgrading  base image . If the VM instance is gone, next time the deployment will create a completely new overlay disk according to the new baseline.

**Comment by yun-ling** [comment]
Today I  makes some  progress . I use container disk as base image , and then I mount a  node  dir ( placing at "/root/virtual_disk/") into virt-launcher pod  ( placing at  " /overlay-disk/" ) like what hostdisk does . 
  
"CreateBackedImageForVolume"  func will redirect the  ephemeralDisk to "/overlay-disk/"  and  "Convert_v1_ContainerDiskSource_To_api_Disk" func will  get the  correct path of  the persistent dir . 

Now the persistent storage function works. I created a cirros VM and put   "123.txt"  to its root path.After restarted the vm ( "restart" means stop vm and start vm again ),"123.txt"  didn't disappear.  

I think it's the smallest change to the kubevirt .

**Comment by rmohr** [comment]
@yun-ling I appreciate your enthusiasm, but do you think that you could first outline more clearly how your feature should work and for which use-cases, maybe even open a proposal in https://github.com/kubevirt/community, so that we can avoid that you spend a lot of energy on an implementation which we may not be able to take in?

**Comment by yun-ling** [comment]
Thanks for your suggestion.I'm working on  my design document.

**Comment by docvirt** [comment]
@yun-ling  Hi, I have the same problem, have you solved it? @rmohr For this way of storage, how can I start a virtual machine using kubevirt？ubuntu-test.qcow2
```shell
# qemu-img info /home/kvm/images/ubuntu-base.qcow2
image: ubuntu-base.qcow2
file format: qcow2
virtual size: 4.0G (4294967296 bytes)
disk size: 2.4G
cluster_size: 65536
Format specific information:
    compat: 1.1
    lazy refcounts: true
    refcount bits: 16
    corrupt: false

# qemu-img create -b ubuntu-base.qcow2 -f qcow2 ubuntu-test.qcow2
# qemu-img info ubuntu-test.qcow2
image: ubuntu-test.qcow2
file format: qcow2
virtual size: 4.0G (4294967296 bytes)
disk size: 196K
cluster_size: 65536
backing file: ubuntu-base.qcow2
Format specific information:
    compat: 1.1
    lazy refcounts: false
    refcount bits: 16
    corrupt: false

# du -sh *
2.4G	ubuntu-base.qcow2
196K	ubuntu-test.qcow2

# vim /etc/libvirt/qemu/vm-ubuntu-test.xml
<domain type='kvm'>
  <name>vm-ubuntu-base</name>                                  
  <uuid>xxxx</uuid>                                            
  ...
  <devices>                                                                     
     <emulator>/usr/bin/kvm-spice</emulator>                                     
     <disk type='file' device='disk'>                                            
       <driver name='qemu' type='qcow2'/>                                        
       <source file='/home/kvm/images/ubuntu-base.qcow2'/>    
       <target dev='vda' bus='virtio'/>                                          
       <address type='pci' domain='0x0000' bus='0x00' slot='0x05' function='0x0'/>
     </disk>     
     ...
     <interface type='bridge'>                                                   
        <mac address='52:54:00:83:5f:e6'/>                     
        <source bridge='br0'/>                                                    
        <model type='virtio'/>                                                    
        <address type='pci' domain='0x0000' bus='0x00' slot='0x03' function='0x0'/>
     </interface> 
     ....
</domain>
```

**Comment by docvirt** [comment]
> 

@rmohr  hi, The way to modify the source code is more complicated for me, and I expect kubevirt to have a good solution
