### ISSUE TITLE
KubeVirt deployment on a kind cluster

### ISSUE THREAD

**Issue by rupipal** [kubevirt/kubevirt#6939]
Hi,
Following the instructions https://kubevirt.io/quickstart_kind/, I'm trying to install KubeVirt on a kind cluster. I can see all components except virt-handler pod and daemonset virt-handler it seems it depends on. I'm guessing that the pod crashes because it is waiting for the daemonset to start running. With all other components up, it is a bit difficult to suspect anything wrong in my setup. I can see it in Deploying phase even at  102 minutes. Earlier, when I tried it on a minikube cluster, the deployment happened in about 50 minutes. I'm Here are the relevant kubectl outputs:

kubectl get all -n kubevirt
NAME                                   READY   STATUS                  RESTARTS   AGE
pod/virt-api-96b6c9d98-dqqs8           1/1     Running                 0          86m
pod/virt-api-96b6c9d98-fk26r           1/1     Running                 0          86m
pod/virt-controller-5f8487f9f7-5hl4g   1/1     Running                 0          85m
pod/virt-controller-5f8487f9f7-bscrv   1/1     Running                 0          85m
pod/virt-handler-5rf98                 0/1     Init:CrashLoopBackOff   21         85m
pod/virt-operator-7959fcf64c-cd4vp     1/1     Running                 0          124m
pod/virt-operator-7959fcf64c-rrggf     1/1     Running                 0          124m

NAME                                  TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
service/kubevirt-operator-webhook     ClusterIP   10.83.116.199   <none>        443/TCP   86m
service/kubevirt-prometheus-metrics   ClusterIP   10.92.37.154    <none>        443/TCP   86m
service/virt-api                      ClusterIP   10.91.139.1     <none>        443/TCP   86m

NAME                          DESIRED   CURRENT   READY   UP-TO-DATE   AVAILABLE   NODE SELECTOR            AGE
daemonset.apps/virt-handler   1         1         0       1            0           kubernetes.io/os=linux   85m

NAME                              READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/virt-api          2/2     2            2           86m
deployment.apps/virt-controller   2/2     2            2           85m
deployment.apps/virt-operator     2/2     2            2           124m

NAME                                         DESIRED   CURRENT   READY   AGE
replicaset.apps/virt-api-96b6c9d98           2         2         2       86m
replicaset.apps/virt-controller-5f8487f9f7   2         2         2       85m
replicaset.apps/virt-operator-7959fcf64c     2         2         2       124m

NAME                            AGE   PHASE
kubevirt.kubevirt.io/kubevirt   86m   Deploying

kubectl describe pod virt-handler-5rf98 -n kubevirt
Name:                 virt-handler-5rf98
Namespace:            kubevirt
Priority:             1000000000
Priority Class Name:  kubevirt-cluster-critical
Node:                 cluster2-worker/172.18.0.5
Start Time:           Fri, 10 Dec 2021 21:17:55 +0530
Labels:               app.kubernetes.io/component=kubevirt
                      app.kubernetes.io/managed-by=kubevirt-operator
                      app.kubernetes.io/version=v0.48.0
                      controller-revision-hash=79f58b4d4f
                      kubevirt.io=virt-handler
                      pod-template-generation=1
                      prometheus.kubevirt.io=true
Annotations:          kubevirt.io/install-strategy-identifier: f4675a531cdaf0b2fab1a985a1087292fd0c3230
                      kubevirt.io/install-strategy-registry: quay.io/kubevirt
                      kubevirt.io/install-strategy-version: v0.48.0
Status:               Pending
IP:                   10.200.1.26
IPs:
  IP:           10.200.1.26
Controlled By:  DaemonSet/virt-handler
Init Containers:
  virt-launcher:
    Container ID:  containerd://afa438a312adf3fb311054a458fe842148128771609e7aecb151edd6a8377b8a
    Image:         quay.io/kubevirt/virt-launcher:v0.48.0
    Image ID:      quay.io/kubevirt/virt-launcher@sha256:5fbaaa232e199df0bbab78e50a4c0f0117b4f28fcbbef7315298733a7fd65cd9
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
    Args:
      node-labeller.sh
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Fri, 10 Dec 2021 22:45:39 +0530
      Finished:     Fri, 10 Dec 2021 22:45:39 +0530
    Ready:          False
    Restart Count:  22
    Environment:    <none>
    Mounts:
      /var/lib/kubevirt-node-labeller from node-labeller (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fl6wg (ro)
Containers:
  virt-handler:
    Container ID:  
    Image:         quay.io/kubevirt/virt-handler:v0.48.0
    Image ID:      
    Port:          8443/TCP
    Host Port:     0/TCP
    Command:
      virt-handler
      --port
      8443
      --hostname-override
      $(NODE_NAME)
      --pod-ip-address
      $(MY_POD_IP)
      --max-metric-requests
      3
      --console-server-port
      8186
      --graceful-shutdown-seconds
      315
      -v
      2
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      10m
      memory:   230Mi
    Liveness:   http-get https://:8443/healthz delay=15s timeout=10s period=45s #success=1 #failure=3
    Readiness:  http-get https://:8443/healthz delay=15s timeout=10s period=20s #success=1 #failure=3
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
      MY_POD_IP:   (v1:status.podIP)
    Mounts:
      /etc/virt-handler/clientcertificates from kubevirt-virt-handler-certs (ro)
      /etc/virt-handler/servercertificates from kubevirt-virt-handler-server-certs (ro)
      /pods from kubelet-pods-shortened (rw)
      /profile-data from profile-data (rw)
      /var/lib/kubelet/device-plugins from device-plugin (rw)
      /var/lib/kubelet/pods from kubelet-pods (rw)
      /var/lib/kubevirt from virt-lib-dir (rw)
      /var/lib/kubevirt-node-labeller from node-labeller (rw)
      /var/run/kubevirt from virt-share-dir (rw)
      /var/run/kubevirt-libvirt-runtimes from libvirt-runtimes (rw)
      /var/run/kubevirt-private from virt-private-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-fl6wg (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kubevirt-virt-handler-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubevirt-virt-handler-certs
    Optional:    true
  kubevirt-virt-handler-server-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubevirt-virt-handler-server-certs
    Optional:    true
  profile-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  libvirt-runtimes:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/kubevirt-libvirt-runtimes
    HostPathType:  
  virt-share-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/kubevirt
    HostPathType:  
  virt-lib-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubevirt
    HostPathType:  
  virt-private-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/kubevirt-private
    HostPathType:  
  device-plugin:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/device-plugins
    HostPathType:  
  kubelet-pods-shortened:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/pods
    HostPathType:  
  kubelet-pods:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/pods
    HostPathType:  
  node-labeller:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubevirt-node-labeller
    HostPathType:  
  kube-api-access-fl6wg:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 CriticalAddonsOnly op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason   Age                    From     Message
  ----     ------   ----                   ----     -------
  Warning  BackOff  3m33s (x397 over 88m)  kubelet  Back-off restarting failed container

kubectl describe daemonset.apps/virt-handler -n kubevirt
Name:           virt-handler
Selector:       kubevirt.io=virt-handler
Node-Selector:  kubernetes.io/os=linux
Labels:         app.kubernetes.io/component=kubevirt
                app.kubernetes.io/managed-by=kubevirt-operator
                app.kubernetes.io/version=v0.48.0
                kubevirt.io=virt-handler
Annotations:    deprecated.daemonset.template.generation: 1
                kubevirt.io/customizer-identifier: bf21a9e8fbc5a3846fb05b4fa0859e0917b2202f
                kubevirt.io/generation: 2
                kubevirt.io/install-strategy-identifier: f4675a531cdaf0b2fab1a985a1087292fd0c3230
                kubevirt.io/install-strategy-registry: quay.io/kubevirt
                kubevirt.io/install-strategy-version: v0.48.0
Desired Number of Nodes Scheduled: 1
Current Number of Nodes Scheduled: 1
Number of Nodes Scheduled with Up-to-date Pods: 1
Number of Nodes Scheduled with Available Pods: 0
Number of Nodes Misscheduled: 0
Pods Status:  0 Running / 1 Waiting / 0 Succeeded / 0 Failed
Pod Template:
  Labels:           app.kubernetes.io/component=kubevirt
                    app.kubernetes.io/managed-by=kubevirt-operator
                    app.kubernetes.io/version=v0.48.0
                    kubevirt.io=virt-handler
                    prometheus.kubevirt.io=true
  Annotations:      kubevirt.io/install-strategy-identifier: f4675a531cdaf0b2fab1a985a1087292fd0c3230
                    kubevirt.io/install-strategy-registry: quay.io/kubevirt
                    kubevirt.io/install-strategy-version: v0.48.0
  Service Account:  kubevirt-handler
  Init Containers:
   virt-launcher:
    Image:      quay.io/kubevirt/virt-launcher:v0.48.0
    Port:       <none>
    Host Port:  <none>
    Command:
      /bin/sh
      -c
    Args:
      node-labeller.sh
    Environment:  <none>
    Mounts:
      /var/lib/kubevirt-node-labeller from node-labeller (rw)
  Containers:
   virt-handler:
    Image:      quay.io/kubevirt/virt-handler:v0.48.0
    Port:       8443/TCP
    Host Port:  0/TCP
    Command:
      virt-handler
      --port
      8443
      --hostname-override
      $(NODE_NAME)
      --pod-ip-address
      $(MY_POD_IP)
      --max-metric-requests
      3
      --console-server-port
      8186
      --graceful-shutdown-seconds
      315
      -v
      2
    Requests:
      cpu:      10m
      memory:   230Mi
    Liveness:   http-get https://:8443/healthz delay=15s timeout=10s period=45s #success=1 #failure=3
    Readiness:  http-get https://:8443/healthz delay=15s timeout=10s period=20s #success=1 #failure=3
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
      MY_POD_IP:   (v1:status.podIP)
    Mounts:
      /etc/virt-handler/clientcertificates from kubevirt-virt-handler-certs (ro)
      /etc/virt-handler/servercertificates from kubevirt-virt-handler-server-certs (ro)
      /pods from kubelet-pods-shortened (rw)
      /profile-data from profile-data (rw)
      /var/lib/kubelet/device-plugins from device-plugin (rw)
      /var/lib/kubelet/pods from kubelet-pods (rw)
      /var/lib/kubevirt from virt-lib-dir (rw)
      /var/lib/kubevirt-node-labeller from node-labeller (rw)
      /var/run/kubevirt from virt-share-dir (rw)
      /var/run/kubevirt-libvirt-runtimes from libvirt-runtimes (rw)
      /var/run/kubevirt-private from virt-private-dir (rw)
  Volumes:
   kubevirt-virt-handler-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubevirt-virt-handler-certs
    Optional:    true
   kubevirt-virt-handler-server-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubevirt-virt-handler-server-certs
    Optional:    true
   profile-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
   libvirt-runtimes:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/kubevirt-libvirt-runtimes
    HostPathType:  
   virt-share-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/kubevirt
    HostPathType:  
   virt-lib-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubevirt
    HostPathType:  
   virt-private-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/kubevirt-private
    HostPathType:  
   device-plugin:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/device-plugins
    HostPathType:  
   kubelet-pods-shortened:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/pods
    HostPathType:  
   kubelet-pods:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/pods
    HostPathType:  
   node-labeller:
    Type:               HostPath (bare host directory volume)
    Path:               /var/lib/kubevirt-node-labeller
    HostPathType:       
  Priority Class Name:  kubevirt-cluster-critical
Events:                 <none>

regards
rps

**Comment by usrbinkat** [comment]
Thank you for reporting this bug. 

Can you include virt-handler logs so we can see what is happening?

/triage needs-information

**Comment by rupipal** [comment]
Thanks for your reply. Sorry for the delay; I'd deleted the kind cluster and had I promptly recalled what the logs were, though I'd many other things in my hands all at once, I might've got back quicker. Because there were no logs and that is the reason, I think, I used describe.

I re-did on a new cluster and I get the same situation.

$ kubectl get all -n kubevirt
NAME READY STATUS RESTARTS AGE
pod/virt-api-79c76787cb-6b7zg 1/1 Running 0 27m
pod/virt-api-79c76787cb-cqgm5 1/1 Running 0 27m
pod/virt-controller-8486c8d5cb-4mw8w 1/1 Running 0 26m
pod/virt-controller-8486c8d5cb-kjckj 1/1 Running 0 26m
pod/virt-handler-p65f9 0/1 Init:CrashLoopBackOff 9 26m
pod/virt-operator-7d787566d5-kn68l 1/1 Running 0 28m
pod/virt-operator-7d787566d5-mz84d 1/1 Running 0 28m

NAME TYPE CLUSTER-IP EXTERNAL-IP PORT(S) AGE
service/kubevirt-operator-webhook ClusterIP 10.96.26.76 443/TCP 27m
service/kubevirt-prometheus-metrics ClusterIP 10.96.242.131 443/TCP 27m
service/virt-api ClusterIP 10.96.132.129 443/TCP 27m

NAME DESIRED CURRENT READY UP-TO-DATE AVAILABLE NODE SELECTOR AGE
daemonset.apps/virt-handler 1 1 0 1 0 kubernetes.io/os=linux 26m

NAME READY UP-TO-DATE AVAILABLE AGE
deployment.apps/virt-api 2/2 2 2 27m
deployment.apps/virt-controller 2/2 2 2 26m
deployment.apps/virt-operator 2/2 2 2 28m

NAME DESIRED CURRENT READY AGE
replicaset.apps/virt-api-79c76787cb 2 2 2 27m
replicaset.apps/virt-controller-8486c8d5cb 2 2 2 26m
replicaset.apps/virt-operator-7d787566d5 2 2 2 28m

NAME AGE PHASE
kubevirt.kubevirt.io/kubevirt 28m Deploying

$ kubectl logs pod/virt-handler-p65f9
Error from server (NotFound): pods "virt-handler-p65f9" not found

$ kubectl logs daemonset.apps/virt-handler
Error from server (NotFound): daemonsets.apps "virt-handler" not found

**Comment by usrbinkat** [comment]
@rupipal I'm unable to re-create this issue. I just ran a kind deploy to create [this gist](https://gist.github.com/usrbinkat/a457c96a50e325200fd59ed681a0242d) and it worked a few times in a row.

I'm un-sure if your logs commands are missing a namespace flag eg: `--namespace kubevirt` that might get you further than the 'not-found' errors shared in your last post.

For information's sake, are you running this on a a Mac or what is the host you're using?

**Comment by rupipal** [comment]
Hi Kathryn
Thanks for your reply.  Yes, I missed namespace by slip. Here it is now.

$ kubectl logs pod/virt-handler-p65f9 -n kubevirt
Error from server (BadRequest): container "virt-handler" in pod
"virt-handler-p65f9" is waiting to start: PodInitializing

$ kubectl logs daemonset.apps/virt-handler -n kubevirt
Error from server (BadRequest): container "virt-handler" in pod
"virt-handler-p65f9" is waiting to start: PodInitializing


$ kubectl get pods -A
NAMESPACE            NAME                                             READY
  STATUS                  RESTARTS   AGE
kube-system          coredns-558bd4d5db-6r99z                         1/1
  Running                 4          40h
kube-system          coredns-558bd4d5db-gzqg7                         1/1
  Running                 4          40h
kube-system          etcd-cluster2-control-plane                      1/1
  Running                 0          22m
kube-system          kindnet-k6z2g                                    1/1
  Running                 4          40h
kube-system          kube-apiserver-cluster2-control-plane            1/1
  Running                 0          22m
kube-system          kube-controller-manager-cluster2-control-plane   1/1
  Running                 4          40h
kube-system          kube-proxy-22m8z                                 1/1
  Running                 4          40h
kube-system          kube-scheduler-cluster2-control-plane            1/1
  Running                 4          40h
kubevirt             virt-api-79c76787cb-6b7zg                        1/1
  Running                 4          40h
kubevirt             virt-api-79c76787cb-cqgm5                        1/1
  Running                 5          40h
kubevirt             virt-controller-8486c8d5cb-4mw8w                 1/1
  Running                 4          40h
kubevirt             virt-controller-8486c8d5cb-kjckj                 1/1
  Running                 4          40h
kubevirt             virt-handler-p65f9                               0/1
  Init:CrashLoopBackOff   117        40h
kubevirt             virt-operator-7d787566d5-kn68l                   1/1
  Running                 6          40h
kubevirt             virt-operator-7d787566d5-mz84d                   1/1
  Running                 4          40h
local-path-storage   local-path-provisioner-547f784dff-2nqrm          1/1
  Running                 6          40h

I'm running it on Debian 11. I have recently tested various softwares on
different kind (and even K3d) clusters. I didn't see any issue related to
kind setup vis-a-vis the host.
