### ISSUE TITLE
Remove Virt-Launcher Host Mount Shared Directories

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#696]
The decentralized libvirt PR (#663) still left us with a shared directory between virt-handler and virt-launcher that's used for communication. The shared directory has unix sockets that both components connect to in order to communicate.

However, It's possible for us to remove the shared directory and use nsenter to perform communication. The problem has been how to discover the namespaces of the virt-launcher pod.

We discovered that it is possible to discover the namespaces via the network connection **before** the VM is started. 

* get namespaces by communicating via pod network
* virt-handler nsenters into namespace of virt-launcher to issue commands
* virt-launcher moves IP address from POD to VM during the startup procedure that occurs after virt-handler has already acquired the namespaces.

**Comment by kfox1111** [comment]
using a shared location is very common in k8s. using nsenter is far less common. Is there a reason to try and eliminate it?

**Comment by davidvossel** [comment]
@kfox1111 we're interested in further limiting the privileges required for the VM pod.

**Comment by rmohr** [comment]
Yes. Basically we are creating pods in the namespace of a user, so we want to achieve that security policies applied by the admin to that namespace do not affect KubeVirt functionality. It is for instance common in open shift installations, to not allow host mounts for ordinary users. On the other hand virt-handler runs in the kube-system namespace and it can have all the required privileges to do whatever it needs to do. Therefore the nsenter approach.
