### ISSUE TITLE
Remove xml tags from cluster wide domain representation

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#70]
The `DomainSpec` struct in

https://github.com/kubevirt/kubevirt/blob/master/pkg/api/v1/schema.go

contains xml and json tags. It is only there to map to json and yaml. So the xml tags should be removed.

**Comment by mpolednik** [comment]
Doesn't seem so straightforward:
I believe you wanted to mention v1/schema.go (as there is no xml at all in types) BUT 
kubevirt.io/kubevirt/pkg/virt-handler/virtwrap/manager.go does directly marshal v1.DomainSpec to XML. Working on actually figuring out how the stuff works though.

**Comment by rmohr** [comment]
> I believe you wanted to mention v1/schema.go (as there is no xml at all in types) BUT

Right, updated.



> kubevirt.io/kubevirt/pkg/virt-handler/virtwrap/manager.go does directly marshal v1.DomainSpec to XML.

The LibvirtDomainManager marshals DomainSpec from 

https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-handler/virtwrap/schema.go

At the moment `virtwrap.DomainSpec` (libvirt domain xml) and `v1.DomainSpec` (cluster wide representation) look pretty much the same, but they are separate so that we can evolve them indepdendently. 

The mapping is done here:

https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-handler/virtwrap/manager.go#L143

**Comment by mpolednik** [comment]
It was actually problem of manager_test using wrong DomainSpec, which led to my confusion. PR sent. :)
