### ISSUE TITLE
Livemigration method is only seen 'blockmigration' even if with pvc RWX mode.

### ISSUE THREAD

**Issue by qkfrksvl** [kubevirt/kubevirt#7022]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

****What happened**:**
I have enabled 'LiveMigration' feature but it's only seen the 'blockmigration'
- Checked using RWX PVC access modes.
- the VM doesn't have pod network, only has multus with bridge mode.
- CPU flag is 'Host-model'
- There is no Pass-through device and SRIOV.

**What you expected to happen**:
Migration method appears 'LiveMigration'

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.48.1
- Kubernetes version (use `kubectl version`): 1.23.1
- VM or VMI specifications: attached.
- Cloud provider or hardware configuration: No
- OS (e.g. from /etc/os-release): Rocky  8.5
- Kernel (e.g. `uname -a`): 4.18.0-348.el8.0.2 
- Install tools:
- Others:

**Comment by qkfrksvl** [comment]
------- VMI Information -------
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
  creationTimestamp: "2022-01-03T15:37:17Z"
  finalizers:
  - kubevirt.io/virtualMachineControllerFinalize
  - foregroundDeleteVirtualMachine
  generation: 12
  labels:
    kubevirt.io/nodeName: dc2-hq-node04
  name: vm-dc2-hq-lin03
  namespace: default
  ownerReferences:
  - apiVersion: kubevirt.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachine
    name: vm-dc2-hq-lin03
    uid: 45b3ceee-3ec1-4342-b3fb-07dd68efab28
  resourceVersion: "2549599"
  uid: 4c0a35c5-3ae0-43cd-a9b4-b8bfc44b930d
spec:
  domain:
    cpu:
      cores: 4
      model: host-model
    devices:
      disks:
      - disk:
          bus: virtio
        name: dv-hd01
      - disk:
          bus: virtio
        name: cloudinit
      interfaces:
      - bridge: {}
        name: vlan161
    features:
      acpi:
        enabled: true
    firmware:
      uuid: 6aae064a-7547-5f1a-bf96-729216218341
    machine:
      type: q35
    resources:
      requests:
        memory: 16Gi
  networks:
  - multus:
      networkName: br-vlan161
    name: vlan161
  volumes:
  - dataVolume:
      name: dc2-hq-lin03-hd01
    name: dv-hd01
  - cloudInitNoCloud:
      networkData: "version: 1\nconfig:\n- type: physical\n  name: enp1s0\n  subnets:\n
        \ - type: static\n    address: 172.23.161.113/24\n    gateway: 172.23.161.1\n
        \   dns_nameservers:\n    - 8.8.8.8\n    - 1.1.1.1 \n"
      userData: |
        #cloud-config
        hostname: dc2-hq-lin03
    name: cloudinit
status:
  activePods:
    02640604-a847-431a-ab60-0870c6084450: dc2-hq-node04
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-01-03T15:37:20Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    status: "True"
    type: LiveMigratable
  - lastProbeTime: "2022-01-03T15:37:33Z"
    lastTransitionTime: null
    status: "True"
    type: AgentConnected
  guestOSInfo:
    id: rocky
    kernelRelease: 4.18.0-348.el8.0.2.x86_64
    kernelVersion: '#1 SMP Sun Nov 14 00:51:12 UTC 2021'
    name: Rocky Linux
    prettyName: Rocky Linux 8.5 (Green Obsidian)
    version: "8.5"
    versionId: "8.5"
  interfaces:
  - interfaceName: enp1s0
    ipAddress: 172.23.161.113
    ipAddresses:
    - 172.23.161.113
    - fe80::ac8f:b5ff:fe97:1d43
    mac: ae:8f:b5:97:1d:43
    name: vlan161
  launcherContainerImageVersion: quay.io/kubevirt/virt-launcher:v0.48.1
  migrationMethod: BlockMigration
  migrationTransport: Unix
  nodeName: dc2-hq-node04
  phase: Running
  phaseTransitionTimestamps:
  - phase: Pending
    phaseTransitionTimestamp: "2022-01-03T15:37:17Z"
  - phase: Scheduling
    phaseTransitionTimestamp: "2022-01-03T15:37:17Z"
  - phase: Scheduled
    phaseTransitionTimestamp: "2022-01-03T15:37:20Z"
  - phase: Running
    phaseTransitionTimestamp: "2022-01-03T15:37:22Z"
  qosClass: Burstable
  virtualMachineRevisionName: revision-start-vm-45b3ceee-3ec1-4342-b3fb-07dd68efab28-2
  volumeStatus:
  - name: cloudinit
    size: 1048576
    target: vdb
  - name: dv-hd01
    persistentVolumeClaimInfo:
      accessModes:
      - ReadWriteMany
      capacity:
        storage: 40Gi
      filesystemOverhead: "0"
      volumeMode: Block
    target: vda

**Comment by qkfrksvl** [comment]
![image](https://user-images.githubusercontent.com/86870268/148012686-25106cf4-f4ac-4af2-ae21-2c223484b4f7.png)

**Comment by vladikr** [comment]
Hi @qkfrksvl , thanks for raising this.

KubeVirt uses the `BlockMigration` method when a VMI has at least one local disk that needs to be copied during the migration process.
Network-attached disks/disks that are located on centralized storage are being simply re-connected on the destination and are not being copied. 
Looking at your vmi definition, this vmi has a cloud init disk attached. This disk is locally generated and will need to be copied. 
That is why your see the `LiveMigration` method being set to `BlockMigration`

**Comment by qkfrksvl** [comment]
Big thanks for answer. One question for you, is it possible to config migration with specific destination node?
