### ISSUE TITLE
Query:  System resource requirements for kubevirt cluster for optimal performance.  

### ISSUE THREAD

**Issue by gidde8** [kubevirt/kubevirt#7040]
/kind bug

We are using kubevirt 0.37.2 version with MULTUS CNI and SRIOV. 

Would like to understand what are system resource requirements in terms of  CPU and memory requirements for kubevirt cluster to run. 

[root@appliance-1 ~]# kubectl get pods -n kubevirt 
NAME                               READY   STATUS    RESTARTS   AGE
virt-api-56769d9fc6-tvz6g          1/1     Running   0          33h
virt-api-56769d9fc6-l6fbg          1/1     Running   0          33h
virt-controller-86d8d864bf-x4crz   1/1     Running   0          33h
virt-controller-86d8d864bf-wvpt8   1/1     Running   1          33h
virt-operator-7985f6ccb8-v859c     1/1     Running   0          33h
virt-operator-7985f6ccb8-jsnh5     1/1     Running   1          33h
virt-handler-qppsx                 1/1     Running   0          33h

It is always expected that two pod instances in the kubevirt cluster.  What are the issues if deployment is changed to have single instance?

We are trying to optimise system as part of that understanding these things.

**Comment by dhiller** [comment]
We don't have documentation on what exactly is required, but you can check on the pods what request we are setting. 

Please note that when the cluster scales you would need more resources than the requests say.

**Comment by xpivarc** [comment]
>It is always expected that two pod instances in the kubevirt cluster. What are the issues if deployment is changed to have single instance?

It is mostly a matter of availability(if the leading virt-controller goes down another can take over). Any virt-api can serve requests therefore in the case of virt-api it has also a performance impact. This [issue](https://github.com/kubevirt/kubevirt/issues/7101) describes some measurements and real-world examples. It might help you to optimize your env.
