### ISSUE TITLE
Can it support multiple VNC connected to VM？

### ISSUE THREAD

**Issue by Jchicode** [kubevirt/kubevirt#7041]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> /kind enhancement

**What happened**:Only support one VNC connection per VM.After I tried the second connection, the first connection was automatically disconnected

**What you expected to happen**: Multiple VNC connected to VM.

**Comment by dhiller** [comment]
We do not support multiple VNC connections yet. Please specify a bit more on your use case please, so that we can understand the need.

/triage needs-information

**Comment by Jchicode** [comment]
Hi! 
I just found this when using kubevirt, I want to connect to the same vm with a friend, can I modify this part of the code to support this. 
https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-handler/rest/console.go#L210-L255

**Comment by dhiller** [comment]
If you want to work on this, feel free to go ahead. We are always looking out for additional hands on the project in several areas :)

Maybe you want to read the contribution guidelines and the getting started guides, starting from here: https://github.com/kubevirt/kubevirt/blob/4f0a9a8470d6ef2fec8e75e1d3a7adec25b2ca10/README.md#to-start-developing-kubevirt

Also, if you need any help, just contact others on either the slack channel #kubevirt-dev, mailing list or join the weekly community meeting happening every Wednesday. More details on that here: https://kubevirt.io/community/

**Comment by dhiller** [comment]
@Jchicode but still the question remains, what exactly do you want to achieve?

**Comment by Jchicode** [comment]
@dhiller I created a VM and want to share it with my friends. So want multiple vnc's to connect to it at the same time.
But only one VNC connection is supported per VM.

**Comment by dhiller** [comment]
I haven't looked very close, but from what I understand you would need to work on the virt-handler side to make this work. I see this as a starting point to have a look: 

https://github.com/kubevirt/kubevirt/blob/356ddf402a446d81b1a8c9654149907f8449f995/pkg/virt-handler/rest/console.go#L135

I am guessing that you would need to add the handling of several connections there. But the task is way over my head, so I think you should ask around in one of the channels for some help on how to get started on this.

/remove-area virtctl
/area virt-handler

**Comment by Jchicode** [comment]
> I haven't looked very close, but from what I understand you would need to work on the virt-handler side to make this work. I see this as a starting point to have a look:
> 
> https://github.com/kubevirt/kubevirt/blob/356ddf402a446d81b1a8c9654149907f8449f995/pkg/virt-handler/rest/console.go#L135
> 
> I am guessing that you would need to add the handling of several connections there. But the task is way over my head, so I think you should ask around in one of the channels for some help on how to get started on this.
> 
> /remove-area virtctl /area virt-handler

Yes, I found it from VNCHandler.
I found there is an env setting, does this setting make a difference? https://github.com/kubevirt/kubevirt/blob/main/pkg/virtctl/vnc/vnc.go#L306

**Comment by Jchicode** [comment]
@dhiller Hi! I have one more question, can I copy local text, paste into the VM via vnc? How should I implement this part.

**Comment by dhiller** [comment]
The guide for developers new to the project starts here: https://github.com/kubevirt/kubevirt/#to-start-developing-kubevirt

After you walked through this, I think you should make yourself familiar with the architecture.

However, if you don't see yourself implementing this, you can still help improving this issue in explaining in more detail what exactly you want to be able to do. I.e. something in the lines of:

```
<!-- This form is for bug reports and feature requests ONLY!
Also make sure that you visit our User Guide at https://kubevirt.io/user-guide/
-->

**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement


**What happened**:

I connected to a VM using VNC. After I tried the second connection, the first connection was automatically disconnected.

**What you expected to happen**:

VNC connections from multiple clients to any one VM should succeed.

```

And of course you can go into more detail than what I just did.

**Comment by lynn901** [comment]
hi all, have you solve this problem?
