### ISSUE TITLE
SR-IOV interfaces are not reported correctly when the guest has no guest-agent.

### ISSUE THREAD

**Issue by EdDev** [kubevirt/kubevirt#7050]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

When looking at a VMI status with SR-IOV interfaces and no guest-agent running, the reported interfaces are wrong.
- In cases where only SR-IOV interfaces are defined, it will wrongly show the interfaces with just their network name and without validating that the data is in sync with the domain (e.g. the device may be detached after a migration, but will still be reported in the status).
- In cases where "regular" interfaces exists in addition to the SR-IOV one, the SR-IOV interfaces will not appear in the report. This occurs even though the device can be seen in the domain configuration (as a hostdevice).

**What you expected to happen**:
The SR-IOV interfaces should be reported correctly, based on the domain configuration, even when the guest-agent is not running in the guest.

**How to reproduce it (as minimally and precisely as possible)**:

Unit tests should be enough to show this behavior. See https://github.com/kubevirt/kubevirt/pull/6951

Raise a guest with no guest-agent and at least one SR-IOV interface attached should show the problem.

**Comment by oshoval** [comment]
Worth to update this ticket with what you expect still to be done 
after https://github.com/kubevirt/kubevirt/pull/7051 is merged please
