### ISSUE TITLE
how CNI plugin get the specified macAddress in devices.interfaces

### ISSUE THREAD

**Issue by chestack** [kubevirt/kubevirt#7055]
**Is this a BUG REPORT or FEATURE REQUEST?**:
> /kind enhancement

**What happened**:
with https://github.com/kubevirt/kubevirt/pull/1213, it cloud specify macAddress of VM, a template like
```
          interfaces:
          - bridge: {}
            name: default
            macAddress: "de:ad:00:00:be:af"
```

however,  kube-ovn could not get this mac address(macA) info from virt-launcher pod but allocated another mac address(macB) for VM nic.

clients failed to access VM because that ovn do the arp reply and return the macB instead of VM real macA back.

From the [document](https://kubevirt.io/user-guide/virtual_machines/interfaces_and_networks/#frontend)
> Note: If a specific MAC address is configured for a virtual machine interface, it's passed to the underlying CNI plugin >that is expected to configure the backend to allow for this particular MAC address. Not every plugin has native support >for custom MAC addresses.

So **how CNI plugin cloud get the specified macAddress**, I did not find it.

**What you expected to happen**:
Maybe kubevirt should add this mac info into pod annotation, and CNI plugin will do the correct IPAM with this mac info.

**Environment**:
- KubeVirt version (use `virtctl version`): 0.47.1
- CNI plugin: kube-ovn

**Comment by maiqueb** [comment]
@chestack The documentation is correct; the CNI plugin should be configured with the MAC - the virt-launcher pod's network annotations - the explicit key is `k8s.v1.cni.cncf.io/networks` - will feature the MAC address, as per [this code](https://github.com/kubevirt/kubevirt/blob/8feee088fd9e830a1281f8b093878aae396ed7d7/pkg/virt-controller/services/multus_annotations.go#L95). 

The value for the annotation key `k8s.v1.cni.cncf.io/networks` will be a serialized JSON string with a list of Multus `NetworkSelectionElement`s allowing a `mac` attribute as you can see in the [multus code](https://github.com/k8snetworkplumbingwg/multus-cni/blob/d52f2b6a4539ae6717fbca1af319804de0c333f4/pkg/types/types.go#L130).

Afterwards, it is up to the delegate CNI plugin to understand and apply this MAC request. Are you sure kube-ovn supports specifying the pod's interface MAC address ? 

Keep in mind the process I've described above **only** happens for **Multus non-default networks**. Can you share your `vmi.spec.Networks` configuration ? We might want to update our documentation to make this limitation more explicit. 

Also, please share the virt-launcher pod's annotations - I'd like to make sure the proper annotation is present on your pod.

**Comment by maiqueb** [comment]
@chestack FWIW, I've noticed that `kube-ovn` does **not** feature the MAC address as a parameter to its [configuration](https://github.com/kubeovn/kube-ovn/blob/3f4b0bfd1305ca1791a7b1c7712c9aa1c2931922/cmd/cni/cni.go#L150).

**Comment by maiqueb** [comment]
@chestack feel free to re-open the issue if the [answer](https://github.com/kubevirt/kubevirt/issues/7055#issuecomment-1011196935) is not correct.

**Comment by chestack** [comment]
@maiqueb thanks for your answer.

> Keep in mind the process I've described above **only** happens for **Multus non-default networks**. Can you share your `vmi.spec.Networks` configuration ? We might want to update our documentation to make this limitation more explicit.

I use kube-ovn as multus default network as following, so that's why I didn't  find the annotation in virt-launcher pod's annotation
```
      networks:
      - name: default
        multus: # Multus network as default
          default: true
          networkName: secure-container/kube-ovn
```

Cloud you help to tell more about why **only** happens for **Multus non-default networks** but not for multus default network. Thanks.

**Comment by maiqueb** [comment]
Su

> @maiqueb thanks for your answer.
> 
> > Keep in mind the process I've described above **only** happens for **Multus non-default networks**. Can you share your `vmi.spec.Networks` configuration ? We might want to update our documentation to make this limitation more explicit.
> 
> I use kube-ovn as multus default network as following, so that's why I didn't find the annotation in virt-launcher pod's annotation

That explains it :) 

> 
> ```
>       networks:
>       - name: default
>         multus: # Multus network as default
>           default: true
>           networkName: secure-container/kube-ovn
> ```
> 
> Cloud you help to talk more about why **only** happens for **Multus non-default networks** but not for multus default network. Thanks.

Sure. As you can see in the [multus code](https://github.com/k8snetworkplumbingwg/multus-cni/blob/d52f2b6a4539ae6717fbca1af319804de0c333f4/pkg/k8sclient/k8sclient.go#L599), the "overridden" default network is configured via a separate annotation - its key is `v1.multus-cni.io/default-network`. That's why we don't generate the "general purpose" network annotations for the multus default network.

To achieve your use case - which I see nothing wrong with right now - we'd also have to patch kubevirt code, since [from what I understand](https://github.com/kubevirt/kubevirt/blob/8feee088fd9e830a1281f8b093878aae396ed7d7/pkg/virt-controller/services/template.go#L2150), we are only setting this annotation with a network name, and not with a JSON serialized `NetworkSelectionElement` - where the MAC / IP / ... could be specified.

Finally, keep in mind that the CNI plugin must understand this `MAC` key. I'm not sure the CNI you mentioned - `kube-ovn` - does.

I suggest you file an issue requesting an enhancement to KubeVirt, which would allow setting a `NetworkSelectionElement` in the multus default network annotation rather than just the network name. If you do so, please CC me in it, and I'll ship the idea around my team so we can prioritize it.

**Comment by naiming-zededa** [comment]
Hi @maiqueb, i found this closed issue. We in [EVE open-source](https://github.com/lf-edge/eve) also need to run Kubevirt with Multus and with with user defined Mac Interface address while creating VMI.
I have made some testing changes in the kubevirt, basically added the 'Mac' into the 'MultusNetwork' struct and added
some code in the 'multus_annotations.go' to pass the mac address into the pod-annotation.
here is the sample patch: 
[kubevirt-multus-mac-diff.txt](https://github.com/kubevirt/kubevirt/files/12140278/kubevirt-multus-mac-diff.txt)

but I do not see this 'Mac' address being passed into the code, with this vmi 2nd intf config sent through kube api:

[api-vmi.txt](https://github.com/kubevirt/kubevirt/files/12140297/api-vmi.txt)

I'm not sure what do i miss. I have debugged the virt-handler, virt-controller, and virt-api, and i don't see
the vmi has the network definition of this 'Mac' address attached when applied with above multus config.
I'm wondering what is the code path from api vmi creation request to kubernetes( it's a k3s ) api-server and
into the kubevirt code, any suggestions? thanks.

**Comment by naiming-zededa** [comment]
@maiqueb never mind. I found the problem, it was due to my client side 'MultusNetwork' adding 'Mac' without the json definition. I'll probably submit a PR after some testing.

**Comment by maiqueb** [comment]
> Hi @maiqueb, i found this closed issue. We in [EVE open-source](https://github.com/lf-edge/eve) also need to run Kubevirt with Multus and with with user defined Mac Interface address while creating VMI. I have made some testing changes in the kubevirt, basically added the 'Mac' into the 'MultusNetwork' struct and added some code in the 'multus_annotations.go' to pass the mac address into the pod-annotation. here is the sample patch, (i ran also 'make generate' for generated files): [kubevirt-multus-mac-diff.txt](https://github.com/kubevirt/kubevirt/files/12140278/kubevirt-multus-mac-diff.txt)

Right now you can specify the MAC address of an interface over kubevirt API via the `Interface`:
http://kubevirt.io/api-reference/main/definitions.html#_v1_interface

There's no need to change the code - adding a MAC attribute to the `network` - since an interface **must** be mapped to a network.

Please try to use the existing API. 
@naiming-zededa

> 
> but I do not see this 'Mac' address being passed into the code, with this vmi 2nd intf config sent through kube api:
> 
> [api-vmi.txt](https://github.com/kubevirt/kubevirt/files/12140297/api-vmi.txt)
> 
> I'm not sure what do i miss. I have debugged the virt-handler, virt-controller, and virt-api, and i don't see the vmi has the network definition of this 'Mac' address attached when applied with above multus config. I'm wondering what is the code path from api vmi creation request to kubernetes( it's a k3s ) api-server and into the kubevirt code, any suggestions? thanks.

**Comment by naiming-zededa** [comment]
Cool @maiqueb, good to know.

**Comment by naiming-zededa** [comment]
> Cool @maiqueb, good to know. what is the difference between this api and http://kubevirt.io/api-reference/main/definitions.html#_v1_virtualmachineinstancenetworkinterface, which also has the 'mac' and 'ipaddress'?

ok, that's status part. never mind.
