### ISSUE TITLE
`kubectl get vmi my-vmi `  can not show ip 

### ISSUE THREAD

**Issue by cszixin** [kubevirt/kubevirt#7065]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
I create a vmi ,  It was normal at first，but after a while
when I use ` kubectl get vmi `,  it does not show the IP of vmi , but virt-launcher does,
and ssh to the vmi , eth0 nic shows the ip ,which as the same with   virt-launcher pod

![image](https://user-images.githubusercontent.com/16910250/149298726-c158fac1-6770-4562-820a-49c63a7708fd.png)

![image](https://user-images.githubusercontent.com/16910250/149298813-d3d21405-f7df-4174-b6a6-f5760bf1ab99.png)

**What you expected to happen**:
kubectl get vim shows the IP

**How to reproduce it (as minimally and precisely as possible)**:
just create a vmi 

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): Client Version: version.Info{GitVersion:"v0.39.0", GitCommit:"6493f7130788fc2242f0ebbda2ace06dc12a4ad0", GitTreeState:"clean", BuildDate:"2021-03-10T15:29:59Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.37.1-dirty", GitCommit:"f270b5befe16c20a11c34f22efecf2407f9591bc", GitTreeState:"dirty", BuildDate:"2021-01-21T20:13:15Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
- VM or VMI specifications:
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: test
spec:
  runStrategy: Manual
  template:
    metadata:
      labels:
        kubevirt.io/domain: centos7
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          inputs:
            - bus: usb
              type: tablet
              name: tablet1
          disks:
          - bootOrder: 1
            disk:
              bus: sata
            name: pvcdisk
          - bootOrder: 2
            cdrom:
              bus: sata
            name: cdromiso
        machine:
          type: q35
        resources:
          requests:
            memory: 6G
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
         claimName: iso-linux
      - name: pvcdisk
        persistentVolumeClaim:
         claimName: test-disk
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): centos7 
- Kernel (e.g. `uname -a`): 5.4.125-1.el7.elrepo.x86_64
- Install tools:
- Others:

**Comment by kobi86** [comment]
Hey @cszixin , I would first suggest to upgrade the versions of both ```virtctl``` and ```kubectl``` and see if it solves the problem,Its working for me on this versions:
```
kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.1", GitCommit:"c4d752765b3bbac2237bf87cf0b1c2e307844666", GitTreeState:"clean", BuildDate:"2020-12-18T12:09:25Z", GoVersion:"go1.15.5", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"1", Minor:"22+", GitVersion:"v1.22.0-rc.0+ef241fd", GitCommit:"ef241fded394346e93100d5c1be9bc41e6ed6fcf", GitTreeState:"clean", BuildDate:"2021-10-14T04:46:33Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
```
AND
```
virtctl version
Client Version: version.Info{GitVersion:"v0.46.1", GitCommit:"5ed15d782ae5bfb7e1323e65defae6cc84ca8175", GitTreeState:"clean", BuildDate:"2021-10-19T15:50:33Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{GitVersion:"v0.44.3-52-g3e3e20501", GitCommit:"3e3e20501b01c8c3ffd7f43f2e7b5af76e795055", GitTreeState:"clean", BuildDate:"2022-01-12T23:21:53Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
``` 

Please update us if the issue solved :)
