### ISSUE TITLE
Network section of docs/components.md is outdated

### ISSUE THREAD

**Issue by phoracek** [kubevirt/kubevirt#7066]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:

The [section](https://github.com/kubevirt/kubevirt/blob/main/docs/components.md#networking) shares future plans on how advanced networking should be done in KubeVirt. Since it was written, we have advanced in this area and that should be reflected there.

**What you expected to happen**:

The section should link to the [cluster-network-addons-operator](https://github.com/kubevirt/cluster-network-addons-operator) and describe how we envision advanced network scenarios with KubeVirt.

**Comment by dankenigsberg** [comment]
/remove-lifecycle stale

@phoracek can someone look into it soon?

**Comment by phoracek** [comment]
Sure

/assign @phoracek
