### ISSUE TITLE
virt-launcher, ProcessMonitor: Searching the VM proccess by domain.Spec.UUID is not reliable

### ISSUE THREAD

**Issue by vasiliy-ul** [kubevirt/kubevirt#7067]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

The process monitor in `virt-launcher` uses  `domain.Spec.UUID` in order to find the main VM process (i.e. `qemu`):

https://github.com/kubevirt/kubevirt/blob/49b9e4a71ae09577ad7578932420b3e639d9e440/cmd/virt-launcher/virt-launcher.go#L501

Currently the approach is to search for `domain.Spec.UUID` in `/proc/$pid/cmline`. This is likely to cause conflicts when there are other processes with the same substring in the cmdline and `libvirt` actually spawns such processes in ceratin scenarios.

**What you expected to happen**:

Need to find a better way of matching the qemu process.

**How to reproduce it (as minimally and precisely as possible)**:

I hit that issue with a custom build when looking on how to enable TPM in KubeVirt. For emulating a TPM device libvirt launches a `swtpm` process and one of the arguments `--tpmstatedir=...` contains the UUID of the VM:

```
# cat /proc/130/cmdline 
/usr/bin/swtpm socket --ctrl type=unixio,path=/run/libvirt/qemu/swtpm/1-default_vmi-ephemera-swtpm.sock,mode=0600 --tpmstatedir=/var/lib/libvirt/swtpm/e65c18ed-49b8-4037-a663-8339055fbca1/tpm1.2,mode=0600 --logfile=/var/log/swtpm/libvirt/qemu/default_vmi-ephemeral-swtpm.log --terminate
```

This eventually leads to wrong detected VM process. The corresponding entry in the log:

```
Found PID for e65c18ed-49b8-4037-a663-8339055fbca1: 130
```

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
/triage accepted

#7103 may contain a fix already.
