### ISSUE TITLE
Prometheus rest_client_requests_total metric is missing pod DELETE and CREATE events

### ISSUE THREAD

**Issue by marceloamaral** [kubevirt/kubevirt#7083]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
We identified this issue occurring in our performance test on the CI/CD system. The test deploys kubevirt, creates 100 VMIs, and cleans up the environment. Also, the test runs the [perfscale-audit tool](https://github.com/kubevirt/kubevirt/tree/main/tools/perfscale-audit) to collect some Prometheus metrics and dump the results into the test.

However, the results are very unstable, sometimes the DELETE and CREATE pod event doesn't even appear in the results.

**How to reproduce it (as minimally and precisely as possible)**:
You don't need to run the perfscale-audit tool, just check prometheus.
1. Deploying Kubevirt and immediately running the test that creates and deletes a VMI
** I deployed Kubevirt using `make cluster-sync`, but you can also use `make cluster-deploy`
** Just create and delete a VMI, or run `make perftest`
2. Have Kubevirt already deployed to the system for a while and then run the test. Although CREATE event appears in the metric, the DELETE event takes a while to appear, I have to wait 3 minutes after finishing the test for all events appear.

**Anything else we need to know?**:
I will describe 3 different scenarios to illustrate the problem.

**Scenario 1: Creating 100 VMI just after deploying kubevirt**
kubevirt deployed: 12:52:58
test started: 12:53:01
test stopped: 12:55:16
![image](https://user-images.githubusercontent.com/5133121/149523476-ad969b17-4104-4fff-b59c-3c212c719a87.png)
There are no pod CREATE and DELETE events appearing in the query.

**Scenario 2: Creating 100 VMI just after running the previous test kubevirt (Have Kubevirt already deployed)**
kubevirt deployed: 12:52:58
test started: 13:01:00
test stopped: 13:03:33
![image](https://user-images.githubusercontent.com/5133121/149523861-2b8a13bd-992f-41d5-9456-e40d36e24abe.png)
Both CREATE and DELETE events are appearing in the query.
Also, note that there are many other events appearing in the query than in the previous scenario.
Another interesting factor is that the pod's first DELETE event appeared at 13:04:56 and the last at 13:09:25, long after the test ended at 13:03:33.

**Scenario 3: Deploy Kubevirt, create 1 VMI, wait 30s and create 100 VMIs**
![image](https://user-images.githubusercontent.com/5133121/149523352-5149f545-d852-4dc2-b972-9dd1d0c533f0.png)
kubevirt deployed: 13:21:10
test started: 13:22:39
test stopped: 13:25:00
I'm waiting 30s after "warm up" to let Prometheus scrape the metrics before running the second test.
The pod's first DELETE event appeared at 13:26:29 and the last at 12:31:27, long after the test ended at 13:25:00, as in the previous scenario.

**Workaround**
If I "warm up" the system, such as creating and deleting a VMI, the expected events show up in the prometheus metric.
Also, as a workaround to collect the DELETE metrics from the pod, I need to wait a few minutes after finishing the test to collect the Prometheus metrics.

**Final remarks**
The problem does not seem to be related to waiting for the system to initialize. I tried deploying kubevirt, waiting 15m and then running the test, but it was still missing events. The experiment only behaves as expected when I "warm up" the system.

Although I'm not sure what the root cause is, it only happens when the test is run right after installing Kubevirt. 
To resolve the issue, we need further investigation of the code, verifying which component is responsible for reporting the rest client requests related to pod events.

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rthallisey** [comment]
Summarized the problem and solution in https://github.com/kubevirt/kubevirt/pull/7075#issuecomment-1020242919

**Comment by rmohr** [comment]
/triage accepted

handled in sig-scale.
