### ISSUE TITLE
how to exec qemu-guest-agent command on kubevirt

### ISSUE THREAD

**Issue by cszixin** [kubevirt/kubevirt#7112]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:
i want to use qemu-guest-agent  exec some command, such as set-user-password,  how can i do it?

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

KubeVirt version (use virtctl version): Client Version: version.Info{GitVersion:"v0.39.0", GitCommit:"6493f7130788fc2242f0ebbda2ace06dc12a4ad0", GitTreeState:"clean", BuildDate:"2021-03-10T15:29:59Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.37.1-dirty", GitCommit:"f270b5befe16c20a11c34f22efecf2407f9591bc", GitTreeState:"dirty", BuildDate:"2021-01-21T20:13:15Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}

Kubernetes version (use kubectl version): Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:41:02Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.2", GitCommit:"f5743093fd1c663cb0cbc89748f730662345d44d", GitTreeState:"clean", BuildDate:"2020-09-16T13:32:58Z", GoVersion:"go1.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by rmohr** [comment]
@cszixin I don't think that we have a generic command (e.g. via `virtctl guest-agent-exec`), but @davidvossel implemented a feature to distribute ssh keys through the qemu-guest-agent which may be what you are looking for. @davidvossel will add a link.

/triage needs-information

**Comment by davidvossel** [comment]
here's the pr that allows for using the access credential api for setting a password. https://github.com/kubevirt/kubevirt/pull/4195 

unfortunally i see the user guide is lacking in that area, but the feature does exist and is tested. You can see the e2e functional tests here https://github.com/kubevirt/kubevirt/blob/cf3d7126264e7f17a4bfbc281db729f78ae53654/tests/credentials_test.go#L285
