### ISSUE TITLE
When VirtualMachineInstanceReplicaSet replica service connects through vnc, two vnc clients connect to one vmi replica

### ISSUE THREAD

**Issue by newhuangchuan** [kubevirt/kubevirt#7122]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
kind bug
> /kind enhancement

**What happened**:
Hello, about `VirtualMachineInstanceReplicaSet`, when I create vmirs, the number of replicas is 5. Then create a service. When connecting to serivce through vnc, five copies should be assigned to me by default. However, when I connect to one with vnc, and then connect through service later, the one he assigns to me will sometimes be a new copy. , sometimes my first connection pops up.
**What you expected to happen**:
Excuse me, if it is exposed through the service, can the link be fixed, or the connection will not be interrupted.
**How to reproduce it (as minimally and precisely as possible)**:
inevitable problem

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
```
Client Version: version.Info{GitVersion:"v0.41.2", GitCommit:"29ce26e09eeed30f89f3fd5d1ad0598955de9648", GitTreeState:"clean", BuildDate:"2021-07-28T16:23:53Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.41.2-1+44dafc7cf42a38", GitCommit:"44dafc7cf42a38ac6a416d6b6db615dc23318fc1", GitTreeState:"clean", BuildDate:"2021-12-21T02:07:07Z", GoVersion:"go1.13.14", Compiler:"gc", Platform:"linux/amd64"}
```
- Kubernetes version (use `kubectl version`):
```
Client Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"d5dfb5cb416fcc32ad556b0d253307c9267b1d30", GitTreeState:"", BuildDate:"2021-07-20T15:01:11Z", GoVersion:"go1.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"18", GitVersion:"v1.18.5", GitCommit:"d5dfb5cb416fcc32ad556b0d253307c9267b1d30", GitTreeState:"", BuildDate:"2020-07-30T01:54:02Z", GoVersion:"go1.14.2", Compiler:"gc", Platform:"linux/amd64"}
```
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
```
Linux k8s-master 4.19.0-91.77.18.uelc20.x86_64 #1 SMP Thu Mar 4 09:11:24 CST 2021 x86_64 x86_64 x86_64 GNU/Linux
```
- Install tools:
- Others:

**Comment by rmohr** [comment]
@newhuangchuan can it be that your service is selecting all 5 VMs? In this case k8s will distribute all calls across all selected VMs. If you want one service for each VM you would have to match them based on unique labels. What exactly are you trying to achieve?

/triage needs-information

**Comment by newhuangchuan** [comment]
> @newhuangchuan can it be that your service is selecting all 5 VMs? In this case k8s will distribute all calls across all selected VMs. If you want one service for each VM you would have to match them based on unique labels. What exactly are you trying to achieve?
> 
> /triage needs-information

Hello, thank you very much for your reply, what I want to achieve is when I create a `vmirs` resource, what I want to see is when I load balance the resource pool through svc. It allows users to connect one-to-one through svc.
What exists now is that there will be two people pulling a virtual machine in a resource pool.
