### ISSUE TITLE
[flaky test]  [Serial][sig-compute]MediatedDevices with mediated devices configuration Should successfully passthrough a mediated device with a disabled display

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#7124]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind enhancement

**What happened**:

The test 

```
[Serial][sig-compute]MediatedDevices with mediated devices configuration Should successfully passthrough a mediated device with a disabled display
tests/mdev_configuration_allocation_test.go
```

fails pretty often. One exampl failure: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7119/pull-kubevirt-e2e-kind-1.19-vgpu/1484261728718950400

More reports:

https://search.ci.kubevirt.io/?search=MediatedDevices+with+mediated+devices+configuration+Should+successfully+passthrough+a+mediated+device+with+a+disabled+display&maxAge=168h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job

It seems like the cause is this on the pod:

```
                "phase": "Failed",
                "message": "Pod Allocate failed due to requested number of devices unavailable for nvidia.com/GRID_T4-1B. Requested: 1, Available: 0, which is unexpected",
                "reason": "UnexpectedAdmissionError",
```

With other words, the scheduler seems to think that a resource should be available on the node, the pod gets scheduled but the node then finds out that this is not correct.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by rmohr** [comment]
@vladikr FYI

**Comment by alicefr** [comment]
In the [previous test](https://github.com/kubevirt/kubevirt/blob/main/tests/mdev_configuration_allocation_test.go#L136-L150) shouldn't we delete and wait the previous VM in order to release the resource and be available for the next test?

**Comment by rmohr** [comment]
> In the [previous test](https://github.com/kubevirt/kubevirt/blob/main/tests/mdev_configuration_allocation_test.go#L136-L150) shouldn't we delete and wait the previous VM in order to release the resource and be available for the next test?

That is a good thought, however, we are deleting the previous VM in the general cleanup. What we don't do is waiting for it. But even then, the expectation is that the one GPU device should be "in use" until the VM is finally gone. Only then the scheduler should see that it is usable again, and only then a new VM should go there.

What i believe what we are seeing is that the VM gets scheduled because it looks like it is available already, but then the kubelet finds out that it is not available and immediately rejects the whole pod.

**Comment by vladikr** [comment]
oh... 
@rmohr how many tests can execute on this node?

**Comment by rmohr** [comment]
@vladikr we have set max_concurrency to 1, but that only applies for the same job, so if a release-branch job gets triggered, more than one can run. We can check if we can set a hard anti-affinity, but I am not sure if that is exposed on prow jobs.

**Comment by rmohr** [comment]
@vladikr trying to set an anti-affinity on the prow job to itself would probably be the easiest option, but what I don't understand: I would expect that the device plugin on our CI node would allocate the device to the pod where we are running the e2e tests and that inside that pod we would do the reconfiguration. If we only have one card exposed, how can another job be scheduled there too when it requests a vgpu?
