### ISSUE TITLE
Legacy container image schema1 manifest breaks migration

### ISSUE THREAD

**Issue by vasiliy-ul** [kubevirt/kubevirt#7138]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:

Some container images still use the legacy Docker `schema1` manifest. `containerd` does not resolve `repoDigest` for such images. As a result the `Image ID` field in the pod spec will not expose a unique pullable reference with the digest. Instead it will contain the internal ID of the image used by `containerd`. This breaks the migration flow since an attempt to pull the image on the target node using the ref taken from `Image ID` will fail.

**How to reproduce it (as minimally and precisely as possible)**:

The problem is reproducable on a cluster with `containerd`. The image `quay.io/kubevirt/fedora-with-test-tooling-container-disk:latest` uses the legacy manifest. It should have the digest `sha256:965db9b12b4fa9da2fa421a49747ad978e2593e9d4973ac5dc014a8b4207b69d` 

However with `containerd` it is not resolved:

```
  volumecontainerdisk:
    Container ID:  containerd://5a4a9e953a2bdb30d65cad3b7c105a9e86ddad8f95b49a9910ac0ecd5e822f09
    Image:         quay.io/kubevirt/fedora-with-test-tooling-container-disk:latest
    Image ID:      sha256:e800d84a0968abfc7be833b043038cd14c96c72907d65caa0f1340eb50705284
```
Here `sha256:e800d84a0968abfc7be833b043038cd14c96c72907d65caa0f1340eb50705284` is not the correct digest but the internal ID.

**What you expected to happen**:

The correct results would look like:
```
  volumecontainerdisk:
    Container ID:  containerd://7a526e0ea019f204d1e628082e68b807f688e2d9193b0132494a029161a4be98
    Image:         quay.io/kubevirt/fedora-with-test-tooling-container-disk:latest
    Image ID:      quay.io/kubevirt/fedora-with-test-tooling-container-disk@sha256:965db9b12b4fa9da2fa421a49747ad978e2593e9d4973ac5dc014a8b4207b69d
```

**Anything else we need to know?**:

Apparently that only affects clusters with `containerd`. Also checked with `docker` and `cri-o` (this one is used here in CI if I am not mistaken). Seems that they handle the legacy manifests and resolve the digest correctly. I hit the issue on a `RKE2` cluster which is shipped with `containerd`.

Seems that this is the 'expected' behaviour for containerd since it does a convertion internally from schema1 to a newer OCI spec format: https://github.com/containerd/containerd/issues/6471

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by vasiliy-ul** [comment]
@rmohr FYI

Not sure if the 'legacy' stuff needs to be supported in KubeVirt. Though maybe it makes sense to have it documented somewhere.

Alternatively I think it may work if we add some `Image ID` parsing logic. It seems that when the digest is not resolved it contains just an ID `sha256:e800d84a0968abfc7be833b043038cd14c96c72907d65caa0f1340eb50705284` without the host part (`quay.io/...`). So probably we can fallback to tags if that is the case. WDYT?

**Comment by rmohr** [comment]
/triage accepted

maybe we should ask on kubevirt-dev to see if we need to support this.

**Comment by rmohr** [comment]
As @vasiliy-ul mentioned on the meeting, potentially we can just block migrations on such old images.

**Comment by vasiliy-ul** [comment]
> maybe we should ask on kubevirt-dev to see if we need to support this.

Schema1 seems deprecated https://docs.docker.com/registry/spec/deprecated-schema-v1/ so probably no need to support it. Though I was thinking if it would make sense to have a general fallback with tags if for some reason the reference provided in `Image ID` could not be resolved. There is an open discussion https://github.com/kubernetes/kubernetes/issues/46255 about these image references and seems its not yet closed.

**Comment by rmohr** [comment]
> Schema1 seems deprecated https://docs.docker.com/registry/spec/deprecated-schema-v1/ so probably no need to support it. Though I was thinking if it would make sense to have a general fallback with tags if for some reason the reference provided in `Image ID` could not be resolved. There is an open discussion [kubernetes/kubernetes#46255](https://github.com/kubernetes/kubernetes/issues/46255) about these image references and seems its not yet closed.

Great link! Added our use-case there, just that more people are aware of it. I still wonder if we should  mark the VMI as non-migratable if we can reliably detect a v1 format. I would prefer to not use tags. It is inherently broken to migrate to a pod which has potentially a changed root disk layer.
