### ISSUE TITLE
libvirtd: error while loading shared libraries: libvirt.so.0: cannot stat shared object: Permission denied

### ISSUE THREAD

**Issue by guleng** [kubevirt/kubevirt#7142]
**What happened**:
virt-handler cannot start

log：libvirtd: error while loading shared libraries: libvirt.so.0: cannot stat shared object: Permission denied

**Environment**: 
 k8s：1.21.9    node：ubuntu 16.04   kernel：4.4.0-210-generic
- KubeVirt version (use `virtctl version`): 0.49.0
- Install tools: yml

**Comment by rmohr** [comment]
/triage needs-information

@guleng do you create your own virt-handler containers?

**Comment by guleng** [comment]
@rmohr Yes, there is an error when creating this virt handler and it cannot be started normally

**Comment by guleng** [comment]
Is this related to the system version?

**Comment by rmohr** [comment]
@guleng it is really hard for me to undertand what you are doing without seeing how you are building the container, but  the container which is erroring probably needs `libvirt-libs` installed.
