### ISSUE TITLE
kubevirt/cirros-registry-disk-demo:devel is missing

### ISSUE THREAD

**Issue by gbenhaim** [kubevirt/kubevirt#717]
When trying to run the functional tests I'm getting the following error

```
Failed to pull image "kubevirt/cirros-registry-disk-demo:devel": rpc error: code = 2 desc = Tag devel not found in repository docker.io/kubevirt/cirros-registry-disk-demo
````

Looking at `https://hub.docker.com/r/kubevirt/cirros-registry-disk-demo/tags/`, the image is indeed missing.

**Comment by rmohr** [comment]
Yes only "latest" exists there. We need to make the tag selectable on the test binary, so that it can switch to "latest". To give the context: As an extra precaution, to not accidentally pull in "latest" images from docker-hub, we use the "devel" tag which we directly build for testing in the core repo.

**Comment by rmohr** [comment]
And thanks for reporting.

**Comment by gbenhaim** [comment]
1. Is there a plan to rebuild the images with the `devel` tag?
2. Do you think that a config file for the tests is an appropriate solution for choosing images?

**Comment by rmohr** [comment]
> Is there a plan to rebuild the images with the devel tag?

There are intentionally no "devel" builds for any container on the registry

> Do you think that a config file for the tests is an appropriate solution for choosing images?

We can just add a commandline flag (pflag) to the tests, where to choose between latest and devel. I would then even use "latest" as the default, like we do everywhere else too ...

**Comment by gbenhaim** [comment]
> We can just add a commandline flag (pflag) to the tests, where to choose between latest and devel.

+1

> I would then even use "latest" as the default, like we do everywhere else too ...

It will make the tests not reproducible. Don't you think that we need to use images with a fixed version?
