### ISSUE TITLE
The dump logic around networking seems to have some issues

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#7170]
> Uncomment only one, leave it on its own line:
>

/kind bug

> /kind enhancement

**What happened**:

When a test fails, I often see the following errors when we are gathering debug artifacts:

```
failed to execute command [lspci] on virt-launcher-testvmi-lrr77-xxlpf, stdout: , stderr: time="2022-02-02T12:48:26Z" level=error msg="exec failed: container_linux.go:380: starting container process caused: exec: \"lspci\": executable file not found in $PATH"
, error: command terminated with exit code 1
failed to execute command [[ -e /dev/vfio ] && ls -lsh -Z -St /dev/vfio] on virt-launcher-testvmi-lrr77-xxlpf, stdout: , stderr: [: missing ']'
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dhiller** [comment]
It looks like the sig-performance lane is failing for a couple days on this issue. Is anybody willing to take a look at this?

**Comment by lyarwood** [comment]
> It looks like the sig-performance lane is failing for a couple days on this issue. Is anybody willing to take a look at this?

While this logic is failing I think that job is just timing out right?

```
Test started today at 7:08 AM failed after 1h5m8s. ([more info](https://prow.ci.kubevirt.io/spyglass/lens/metadata/iframe?req=%7B%22artifacts%22%3A%5B%22finished.json%22%2C%22podinfo.json%22%2C%22started.json%22%5D%2C%22index%22%3A0%2C%22src%22%3A%22gs%2Fkubevirt-prow%2Fpr-logs%2Fpull%2Fkubevirt_kubevirt%2F7432%2Fpull-kubevirt-e2e-k8s-1.21-sig-performance%2F1519559085077303296%22%7D&topURL=https%3A//prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7432/pull-kubevirt-e2e-k8s-1.21-sig-performance/1519559085077303296&lensIndex=0#))
```

https://github.com/kubevirt/project-infra/blob/cffefa28d6caf469a47e52718e37e75b3123f5a0/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml#L412

**Comment by lyarwood** [comment]
> > It looks like the sig-performance lane is failing for a couple days on this issue. Is anybody willing to take a look at this?
> 
> While this logic is failing I think that job is just timing out right?
> 
> https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7432/pull-kubevirt-e2e-k8s-1.21-sig-performance/1519559085077303296
> 
> ```
> [..] Test started today at 7:08 AM failed after 1h5m8s. [..]
> ```
> 
> While the job has a 1 hour timeout:
> 
> https://github.com/kubevirt/project-infra/blob/cffefa28d6caf469a47e52718e37e75b3123f5a0/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-presubmits.yaml#L412

https://github.com/kubevirt/project-infra/pull/2059 might help us avoid this issue in the job for now assuming it completes in time.

**Comment by xpivarc** [comment]
@enp0s3 @oshoval @ormergi Would you have a look at this as you were either adding or editing this. Another solution would be to remove this if nobody really wants it functional.

**Comment by lyarwood** [comment]
> [kubevirt/project-infra#2059](https://github.com/kubevirt/project-infra/pull/2059) might help us avoid this issue in the job for now assuming it completes in time.

FWIW this landed and allowed Ginkgo to fail the tests correctly, I've written this up as https://github.com/kubevirt/kubevirt/issues/7658.

**Comment by oshoval** [comment]
Assumption - I think we should disable the reporter there, there are too many machines and when it tries to console to the ones that aren't ready, each try takes 10 seconds (see please end of the log)

**Comment by oshoval** [comment]
I think we can close this issue ?
there were two different issues here, the one in the description and the one in the comments, and both handled by different PRs
(links mentioned above)

**Comment by oshoval** [comment]
Ref https://github.com/kubevirt/kubevirt/issues/7170#issuecomment-1166549757

/close
