### ISSUE TITLE
Failed to compile Kubevirt's functional tests

### ISSUE THREAD

**Issue by gbenhaim** [kubevirt/kubevirt#719]
I'm getting the following error:

```
09:05:47 [check-patch.el7.x86_64] [ERROR]	Error scanning k8s.io/apimachinery/pkg/apis/meta/v1beta1: cannot find package "." in:
09:05:47 [check-patch.el7.x86_64] 	/root/.glide/cache/src/https-k8s.io-apimachinery/pkg/apis/meta/v1beta1
```

Link to the job: http://jenkins.ovirt.org/job/kubevirt_kubevirt-ansible_standard-check-pr/26/consoleFull

**Comment by cynepco3hahue** [comment]
@gbenhaim I had this problem locally, `make distclean` before `make` helped me.

**Comment by rmohr** [comment]
There seems to be an issue in the glide cache. Either delete the build container or run "make distclean".

**Comment by gbenhaim** [comment]
Thanks! I will try it.

**Comment by gbenhaim** [comment]
The suggested advice solved the issue, thanks.
