### ISSUE TITLE
Cannot import kubevirt.io/client-go to a new project

### ISSUE THREAD

**Issue by orelmisan** [kubevirt/kubevirt#7196]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind bug

**What happened**:
I've created a new go project and tried to import `kubevirt.io/client-go`:
```
go get kubevirt.io/client-go@v0.49.0
```

The command fails with the following error:
```
go: downloading kubevirt.io/client-go v0.49.0
go get: kubevirt.io/client-go@v0.33.0 updating to
	kubevirt.io/client-go@v0.49.0 requires
	github.com/openshift/client-go@v0.0.0: reading github.com/openshift/client-go/go.mod at revision v0.0.0: unknown revision v0.0.0
```

**What you expected to happen**:
I expected to be able to import the library.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:
`go version go1.16.9 linux/amd64`

**Comment by xpivarc** [comment]
`I've created a new go` seems misleading as go outputs it is update.
