### ISSUE TITLE
Not meaningful log about disk capacity

### ISSUE THREAD

**Issue by xpivarc** [kubevirt/kubevirt#7215]
**Is this a BUG REPORT or FEATURE REQUEST?**:

 /kind enhancement

**What happened**:

```
{"component":"virt-launcher","level":"error","msg":"No disk capacity","pos":"manager.go:661","timestamp":"2022-02-09T22:18:22.107956Z"}
{"component":"virt-launcher","level":"error","msg":"No disk capacity","pos":"manager.go:661","timestamp":"2022-02-09T22:18:22.109726Z"}
```

**What you expected to happen**:

I would expect to at least know which disk is full and why do we care.

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by xpivarc** [comment]
/reopen
I am not sure this was addressed will have a look this week.

**Comment by PokIsemaine** [comment]
I am interested in fixing this issue. If there is no one working on it can I get assigned?
