### ISSUE TITLE
cannot migrate VMI which does not use masquerade to connect to the pod network

### ISSUE THREAD

**Issue by wavezhang** [kubevirt/kubevirt#7238]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

/kind enhancement

**What happened**:
cannot migrate VMI which does not use masquerade to connect to the pod network
**What you expected to happen**:
can migrate VMI that use bridge to connect to the pod network
**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
Don't allow live migration with a bridge interface #2405
Why ?
**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dhiller** [comment]
This is by design. VMs can't take their IPs with them because it's delivered by CNI. As a consequence VMs would loose connectivity after the migration, so we are blocking the migration.

So we are not planning to implement this currently.

/close

**Comment by dhiller** [comment]
Please see the use-guide here: https://kubevirt.io/user-guide/operations/live_migration/#limitations

/triage unresolved

**Comment by wavezhang** [comment]
Since some cni support this situation，is this possible to allow bridge migration by configuration？

**Comment by xpivarc** [comment]
/open 
As this now seems to be feature request

**Comment by xagent003** [comment]
+1

**Comment by kvaps** [comment]
/reopen

here is
- proposal: https://github.com/kubevirt/community/pull/182
- fix: https://github.com/kubevirt/kubevirt/pull/7768

**Comment by xpivarc** [comment]
/close
https://github.com/kubevirt/kubevirt/pull/9193 partially fixed this.
