### ISSUE TITLE
virtctl console  connection  timeout

### ISSUE THREAD

**Issue by timchenxiaoyu** [kubevirt/kubevirt#7244]
> /kind bug

**What happened**:

apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=

virtctl console timeout

Internal error occurred: dialing virt-handler: dial tcp 10.11.0.11:8186: connect: connection timed out

**Environment**:

# virtctl version
Client Version: version.Info{GitVersion:"v0.50.0", GitCommit:"7e034450c10ad2a879db960b9912be2dff7ed9ce", GitTreeState:"clean", BuildDate:"2022-02-10T13:39:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.50.0", GitCommit:"7e034450c10ad2a879db960b9912be2dff7ed9ce", GitTreeState:"clean", BuildDate:"2022-02-10T13:39:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

# kubectl version
Client Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:27:39Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"20", GitVersion:"v1.20.15", GitCommit:"8f1e5bf0b9729a899b8df86249b56e2c74aebc55", GitTreeState:"clean", BuildDate:"2022-01-19T17:23:01Z", GoVersion:"go1.15.15", Compiler:"gc", Platform:"linux/amd64"}

**Comment by timchenxiaoyu** [comment]
into lancher container:

error: internal error: character device console0 is not using a PTY

**Comment by dhiller** [comment]
@rmohr to follow up here

**Comment by rmohr** [comment]
Can you check if your VM is runnig with `kubectl get vmis --all-namespaces`?

The message 

```
Internal error occurred: dialing virt-handler: dial tcp 10.11.0.11:8186: connect: connection timed out
```

sounds to me like `virtctl` can't reach the node where the VM is running. So you may also want to check the apiserver logs to see if everything is fine.

**Comment by timchenxiaoyu** [comment]
# kubectl get vmis --all-namespaces
NAMESPACE   NAME     AGE     PHASE     IP           NODENAME   READY
default     testvm   6d23h   Running   10.11.0.14   weixian    True

**Comment by timchenxiaoyu** [comment]
kubectl get pods -owide
NAME                         READY   STATUS    RESTARTS   AGE     IP           NODE      NOMINATED NODE   READINESS GATES
virt-launcher-testvm-2rx64   2/2     Running   0          6d23h   10.11.0.14   weixian   <none>           1/1
