### ISSUE TITLE
guest has not initialized the display (yet)

### ISSUE THREAD

**Issue by luckyuuuu** [kubevirt/kubevirt#7245]
**Is this a BUG REPORT or FEATURE REQUEST?**:

BUG REPORT

**What happened**:
with no vGPU I can run the win10 vm

our gpu does not support disply=on,ramfb=on 
so config as follow：

        devices:
          gpus:
          - deviceName: xxx.com/qs50
            name: gpu
          virtualGPUOptions: 
              display:
                enabled: false

run win 10 vm

virtctl vnc win10vm

then I got :
guest has not initialized the display (yet)
in the k8s work I can run the win10 vm correctly
sudo qemu-system-x86_64 -enable-kvm -smp 2  -device vfio-pci,id=ua-gpu-gpu1,sysfsdev=/sys/bus/mdev/devices/c4f702ca-c69d-4d7d-a526-5fdcf78d3428,display=off ......

**What you expected to happen**:
could see win10 desktop normal

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:
the gpu driver in win10vm can not be install until the vm up, we need Manual installation vGPU driver after startup 

Manual installation after startup
**Environment**:
- KubeVirt version (use `virtctl version`):0.49
- Kubernetes version (use `kubectl version`):1.23
- VM or VMI specifications:win10
- Cloud provider or hardware configuration: x86
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):5.4. ubuntu 20.04
- Install tools:kubeadm
- Others:

**Comment by dhiller** [comment]
@vladikr could you take a look here, please? Thank you!

**Comment by luckyuuuu** [comment]
kubectl logs virt-launcher-win10vm6-bdnjp -c compute

{"component":"virt-launcher","level":"warning","msg":"PCI_RESOURCE_******** not set for resource mthreads.com/S30","pos":"addresspool.go:50","timestamp":"2022-02-25T09:53:20.366455Z"}
{"component":"virt-launcher","level":"info","msg":"host-device created: 56a4c4e2-c81f-4cba-82bf-af46c30ea32d","pos":"hostdev.go:85","timestamp":"2022-02-25T09:53:20.366477Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"win10vm6","namespace":"default","pos":"server.go:190","timestamp":"2022-02-25T09:53:20.367194Z","uid":"7ce7a41d-e1e8-4515-9c22-2e9219d50de5"}

and in the HOST

use
sudo ./qemu-kvm  ****** -device pcie-root-port,port=0x10,chassis=1,id=pci.1,bus=pcie.0,multifunction=on,addr=0x2
the vm can not run properly

sudo ./qemu-kvm  ****** -device pcie-root-port,port=0x10,chassis=1,id=pci.1,bus=pcie.0,multifunction=on,addr=0x3
or
qemu-kvm  ******  -device pcie-root-port,port=0x10,chassis=1,id=pci.1,bus=pcie.0,multifunction=on,addr=0x4
the vm run ok

addr 0X2 is wrong ?

**Comment by luckyuuuu** [comment]
in the host I tested

sudo ./qemu-kvm -name guest=default_win10vm5,debug-threads=on -machine pc-q35-6.0,accel=kvm,usb=off,dump-guest-core=off,memory-backend=pc.ram -cpu Icelake-Server,ss=on,vmx=on,hypervisor=on,tsc-adjust=on,avx512ifma=on,sha-ni=on,rdpid=on,md-clear=on,stibp=on,arch-capabilities=on,xsaves=on,ibpb=on,ibrs=on,amd-stibp=on,amd-ssbd=on,rdctl-no=on,ibrs-all=on,skip-l1dfl-vmentry=on,mds-no=on,pschange-mc-no=on,hle=off,rtm=off,clwb=off,la57=off,wbnoinvd=off,intel-pt=off,hv-time,hv-relaxed,hv-vapic,hv-spinlocks=0x1fff -m 4096 -object '{"qom-type":"memory-backend-ram","id":"pc.ram","size":4294967296}' -overcommit mem-lock=off -smp 2,sockets=2,dies=1,cores=1,threads=1 -object '{"qom-type":"iothread","id":"iothread1"}' -uuid c725ce3c-84a2-54cd-a41d-c2161fc521aa -smbios type=1,manufacturer=KubeVirt,product=None,uuid=c725ce3c-84a2-54cd-a41d-c2161fc521aa,family=KubeVirt -no-user-config -nodefaults  -rtc base=utc,driftfix=slew -global kvm-pit.lost_tick_policy=delay -no-hpet -no-shutdown -boot strict=on \
-device pcie-root-port,port=0x10,chassis=1,id=pci.1,bus=pcie.0,multifunction=on,addr=0x3 \
-device pcie-root-port,port=0x11,chassis=2,id=pci.2,bus=pcie.0,addr=0x3.0x1 \
-device pcie-root-port,port=0x12,chassis=3,id=pci.3,bus=pcie.0,addr=0x3.0x2 \
-device pcie-root-port,port=0x13,chassis=4,id=pci.4,bus=pcie.0,addr=0x3.0x3 \
-device pcie-root-port,port=0x14,chassis=5,id=pci.5,bus=pcie.0,addr=0x3.0x4 \
-device pcie-root-port,port=0x15,chassis=6,id=pci.6,bus=pcie.0,addr=0x3.0x5 \
-device pcie-root-port,port=0x16,chassis=7,id=pci.7,bus=pcie.0,addr=0x3.0x6 \
-device VGA,id=video0,vgamem_mb=16,bus=pcie.0,addr=0x4 \
-device vfio-pci,id=ua-gpu-gpu1,sysfsdev=/sys/bus/mdev/devices/973069b7-2025-406b-b3c9-301016af3150,display=off,bus=0x5 \
-device virtio-balloon-pci-non-transitional,id=balloon0,bus=pci.6,addr=0x0 \
-device qemu-xhci,id=usb,bus=pci.2,addr=0x0 \
-device virtio-serial-pci-non-transitional,id=virtio-serial0,bus=pci.4,addr=0x0 \
-device virtio-scsi-pci-non-transitional,id=scsi0,bus=pci.3,addr=0x0 \
-device usb-tablet,id=ua-tablet,bus=usb.0,port=1 \
-spice port=12222,disable-ticketing=on \
-hda ubuntu.img \
-nic user,hostfwd=tcp::3333-:22 -net nic
the vm can run correctl

but actually kubevirt use 
-device vfio-pci,id=ua-gpu-gpu1,sysfsdev=/sys/bus/mdev/devices/973069b7-2025-406b-b3c9-301016af3150,display=off,bus=pci.5  \

so i think the topology of pci cause this issue, or our gpu is not support this topology.
is there any config in the vm yaml could set the vgpu pci  topology?

**Comment by jean-edouard** [comment]
@luckyuuuu hi, could you please post the `permittedHostDevices` section from your kubevirt CR? Thanks

**Comment by vladikr** [comment]
@luckyuuuu is this device that you are adding is a virtual GPU, such as a mediated device, or is it a PCI device? 
What is the vendor of this device?

Looking at the qemu command line, you are adding a PCI device not MDEV - therefore, this is *not* a virtual GPU. Hence, the `virtualGPU` display will not be enabled for PCI devices and you shouldn't set anything in this API field.

**Comment by luckyuuuu** [comment]
@jean-edouard @vladikr 
our company focus on GPU research and development, like intel & NVIDIA，our Product coming soon，so i am sorry i can not tell you the vendor now.
I reference this to create vGPU and deploy kubevirt to KS8  https://kubevirt.io/2021/intel-vgpu-kubevirt.html#validate-vgpu-detection

create vGPU
`ExecStart=/bin/sh -c "echo '56a4c4e2-c81f-4cba-82bf-af46c30ea32d' > /sys/devices/pci0000:00/0000:00:02.0/mdev_supported_types/xxx/create"
ExecStart=/bin/sh -c "echo '973069b7-2025-406b-b3c9-301016af3150' > /sys/devices/pci0000:00/0000:00:02.0/mdev_supported_types/xxx/create"`
add vGPU by
```
spec:
  configuration:
    developerConfiguration:
      featureGates:
      - GPU
    permittedHostDevices:
      mediatedDevices:
      - mdevNameSelector: "xxxgpu-Standard"
        resourceName: "xxx.com/x30"
```

create vm by
```
        devices:
          gpus:
          - deviceName:xxx.com/x30
            name: gpu1
            virtualGPUOptions:
              display:
                enabled: false
                ramFB:
                enabled: false
          disks:
```
in the virt-launcher pod libvirtd log
![image](https://user-images.githubusercontent.com/25578085/156093224-456d5595-cff6-4055-b655-364dcb19baeb.png)
but i got 
![image](https://user-images.githubusercontent.com/25578085/156093406-b93ddc58-4201-4b00-880a-0ee4e2b7efba.png)

so i try to launch the vm in the host and the qemu command line from the libvirtd log 

I meant to add virtual GPU such as a mediated device, did I do anything wrong at any of the above steps？

**Comment by yeahdongcn** [comment]
@luckyuuuu Hi, have you resolved this issue?
