### ISSUE TITLE
make generate Error

### ISSUE THREAD

**Issue by qpzmtyv** [kubevirt/kubevirt#7256]
**Is this a BUG REPORT or FEATURE REQUEST?**:
BUG REPORT
> Uncomment only one, leave it on its own line:
>
> /kind bug
> /kind enhancement

**What happened**:  I add a list type item to  VirtualMachineStatus in staging/src/kubevirt.io/client-go/api/v1/types.go, and run make generate , it report error:
You introduced new API rule violation
174d173
< API rule violation: list_type_missing,kubevirt.io/client-go/api/v1,VirtualMachineNetworkInterface,Ips
177d175
< API rule violation: list_type_missing,kubevirt.io/client-go/api/v1,VirtualMachineStatus,Interfaces
make: *** [generate] Error 1

**What you expected to happen**: 

**How to reproduce it (as minimally and precisely as possible)**:

**Anything else we need to know?**:

**Environment**: 
- KubeVirt version (use `virtctl version`):  0.42.1
- Kubernetes version (use `kubectl version`):  k8s v1.20.4
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release): centos7.6
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by dhiller** [comment]
as @rmohr suggested, you just have to add the type of the list [1]. For instance `+listType=atomic`.

[1] https://github.com/kubernetes/kube-openapi/blob/master/pkg/idl/doc.go#L21
