### ISSUE TITLE
[sig-network] Support port forwarding over IPv6

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#7276]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug
/kind enhancement

**What happened**:
Port forwarding to a VM over ipv6 is not working.

**What you expected to happen**:
It should work.

**How to reproduce it (as minimally and precisely as possible)**:
1. Run a masquerade fedora vm.
2. Run an http server on the vm `nc -s fd10:0:2::2 -klp 1700 -c 'echo -e "HTTP/1.1 200 OK\nContent-Length: 12\n\nHello World!"'`
3. Run port forwarding on your k8s client - `kubectl port-forward pod/virt-launcher-vmi-name 35000:1700`
4. From your k8s client run `curl [::1]:35000`

**Anything else we need to know?**:
On cri-o 1.20 there is a bug and even pod ipv6 port-forward is not working (::1 is sent to the VM over 127.0.0.1).
On cri-o 1.23 the bug is fixed, and pod ipv6 port-forward is working.

However, even with cri-o update to 1.23 VM ipv6 port forwarding is not working.
The reason is [there is no ipv6 equivalent for net.ipv4.conf.all.route_localnet](https://serverfault.com/questions/975558/nftables-ip6-route-to-localhost-ipv6-nat-to-loopback). So the routing we do using the nft nat OUTPUT and POSTROUTING chains is not working well (the vm reply is dropped once the POSTROUTING chain reverse rule is applied, since [it is not permitted to have localhost dst with non local src](https://datatracker.ietf.org/doc/html/rfc4291#section-2.5.3)). 

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by avlitman** [comment]
Hi @AlonaKaplan I try to clean-up tests, and I see that this issue is mentioned in https://github.com/kubevirt/kubevirt/blob/7ad53bc2b36538d8871c215f385902b0a9b50571/tests/network/port_forward.go#L52, but this issue is closed and the 3 Entry("IPv6", ...) and skipIPv6Message const is still in the code.
can I remove the entries and const?
