### ISSUE TITLE
[sig-scale] performance functional test is failing

### ISSUE THREAD

**Issue by marceloamaral** [kubevirt/kubevirt#7278]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
/kind bug

**What happened**:
Recently,  an optional performance presubmit prow job was added in the project-infra. The job was already running for a while and stable.

However, the job that should be optional is automatically triggering for non-performance related PRs...for example the PR #6180.
In addition, regarding this test, for some reason it is trying to run the `realtime performance` test, but it should only be running the regular `performance` test. Because of this, the job is not setting up the realtime test and then the `realtime performance` test is failing.

**What you expected to happen**:
The `kubevirt-e2e-k8s-1.21-sig-performance` test should be optional.
The `kubevirt-e2e-k8s-1.21-sig-performance` test should not run `realtime performance` test, or configure it before running.

**How to reproduce it (as minimally and precisely as possible)**:
Run it as it is running in CI, for example [here](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/6180/pull-kubevirt-e2e-k8s-1.21-sig-performance/1496837041588015104).

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
- Kubernetes version (use `kubectl version`):
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

/cc @rthallisey @dhiller

**Comment by dhiller** [comment]
@marceloamaral `optional: true` doesn't mean that the job is never triggered, it means that the job is not barring the merging via tide.

I guess what you want then is either 
* `always_run: false` , this would make the job only be triggered by a comment of `/test pull-kubevirt-e2e-k8s-1.21-sig-performance` or
* `run_if_changed: <your-go-path-regex>`, this would trigger when relevant changes for performance occur.

A better description of how to configure triggering your jobs can be found here: https://github.com/kubernetes/test-infra/blob/master/prow/jobs.md#triggering-jobs

Another option would be to set `skip_report: true` if you still want to run the job but don't want the status to appear at the GitHub PR.

**Comment by rthallisey** [comment]
Tracking in project-infra
/close
