### ISSUE TITLE
where to download kubevirt image v0.55.0?

### ISSUE THREAD

**Issue by lixiaobing1** [kubevirt/kubevirt#7286]
Where to download kubevirt image v0.55.0?
There is no this version in hub.docker.com.
Thx :)

**Comment by lixiaobing1** [comment]
Thx again :)

**Comment by xpivarc** [comment]
Hi,
The latest release can be found here https://github.com/kubevirt/kubevirt/releases/tag/v0.50.0 
We push the images to https://quay.io/kubevirt/ as stated on the release.

**Comment by lixiaobing1** [comment]
ok, thx :)

**Comment by xpivarc** [comment]
/close 
@lixiaobing1 feel free to reopen if you find the need
