### ISSUE TITLE
could anyone tell me where to download 0.33.0 code, thx:)

### ISSUE THREAD

**Issue by lixiaobing1** [kubevirt/kubevirt#7291]
could anyone tell me where to download 0.33.0 code?
only 0.34.0 code in github.
thx very much :)

**Comment by lixiaobing1** [comment]
thx very much :)

**Comment by uril** [comment]
Do you mean this: https://github.com/kubevirt/kubevirt/releases/tag/v0.33.0 ?

**Comment by dhiller** [comment]
You can either use the [release-0.33](https://github.com/kubevirt/kubevirt/tree/release-0.33) branch or the v0.33.0 tag

**Comment by dhiller** [comment]
Closing this issue, as it should be resolved by the comments. If not, feel free to reopen for further questions.

/close
