### ISSUE TITLE
virtctl command not working on Arm Mac

### ISSUE THREAD

**Issue by fungiboletus** [kubevirt/kubevirt#7305]
/kind bug

**What happened**:

I followed [the documentation to install virtctl](https://kubevirt.io/quickstart_cloud/).

It suggested to use the following code:

```bash
VERSION=$(kubectl get kubevirt.kubevirt.io/kubevirt -n kubevirt -o=jsonpath="{.status.observedKubeVirtVersion}")
ARCH=$(uname -s | tr A-Z a-z)-$(uname -m | sed 's/x86_64/amd64/') || windows-amd64.exe
echo ${ARCH}
curl -L -o virtctl https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/virtctl-${VERSION}-${ARCH}
chmod +x virtctl
sudo install virtctl /usr/local/bin
```

My arch is `darwin-arm64` because I use a MacBook M1. This architecture is not supported and it downloaded a file containing `Not Found` instead of returning an error.

**What you expected to happen**:

 - An error message like `plugin "virt" does not offer installation for this platform` when you use `krew`. 
 - Support for the darwin-arm64 architecture.

**How to reproduce it (as minimally and precisely as possible)**:

```bash
VERSION=$(kubectl get kubevirt.kubevirt.io/kubevirt -n kubevirt -o=jsonpath="{.status.observedKubeVirtVersion}")
ARCH=unicorn-arm2048
curl -L -o virtctl https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/virtctl-${VERSION}-${ARCH}
file ./virtctl
```

**Anything else we need to know?**:

The following code is a workaround:

```bash
VERSION=$(kubectl get kubevirt.kubevirt.io/kubevirt -n kubevirt -o=jsonpath="{.status.observedKubeVirtVersion}")
# Force AMD64 build and use the emulation
ARCH=darwin-amd64
curl -L -o virtctl https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/virtctl-${VERSION}-${ARCH}
chmod +x virtctl
sudo install virtctl /usr/local/bin
```

**Environment**:
- KubeVirt version (use `virtctl version`): NA
- Kubernetes version (use `kubectl version`): NA
- VM or VMI specifications: NA
- Cloud provider or hardware configuration: NA
- OS (e.g. from /etc/os-release): MacOs ARM
- Kernel (e.g. `uname -a`): `Darwin fungiboletus.local 21.3.0 Darwin Kernel Version 21.3.0: Wed Jan  5 21:37:58 PST 2022; root:xnu-8019.80.24~20/RELEASE_ARM64_T8101 arm64`
- Install tools: NA
- Others: NA

**Comment by fungiboletus** [comment]
I'm afraid I don't know your build system and adding support to this architecture seems like a big task for someone outside of the project. It's not about adding a line in a github action yaml file.

However I could probably do a pull request to update the documentation, so the example script downloads the `darwin-amd64` instead of a 404 error file.

**Comment by haslersn** [comment]
The next NixOS release (22.05) will have virtctl [packaged](https://github.com/NixOS/nixpkgs/commit/1391482b41a65d67fd2a5af3ac670264a0f6b2db) for all platforms.

**Comment by xpivarc** [comment]
/close
Release 1.0 has the support, see https://github.com/kubevirt/kubevirt/releases/download/v1.0.0/virtctl-v1.0.0-darwin-arm64

**Comment by fungiboletus** [comment]
Great to hear! Thanks everyone.
