### ISSUE TITLE
Old version of GO throwing High and Critical CVEs from Twistlock Scans

### ISSUE THREAD

**Issue by David-Krupa** [kubevirt/kubevirt#7306]
**Is this a BUG REPORT or FEATURE REQUEST?**: Bug

> Uncomment only one, leave it on its own line:
/kind bug

**What happened**:
Container scans reveal high and critical CVEs with current golang version:

**What you expected to happen**:

Update go to the newest version which to mitigate the vulnerabilities.

**How to reproduce it (as minimally and precisely as possible)**:
https://go.dev/doc/install

1. Download go v1.17.8 or greater
2. Remove old go version and untar new version
3. Export go to the user PATH
4. Check version to ensure a successful upgrade

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.50.0
- Kubernetes version (use `kubectl version`): 1.21
- VM or VMI specifications:
- Cloud provider or hardware configuration:
- OS (e.g. from /etc/os-release):
- Kernel (e.g. `uname -a`):
- Install tools:
- Others:

**Comment by David-Krupa** [comment]
> /kind enhancement

**Comment by dhiller** [comment]
/triage needs-information

So you are suggesting that we update to go 1.17.8 to get rid of those? Could you elaborate on how exactly you used Twistlock please?

**Comment by David-Krupa** [comment]
Sure,

Without going into too much detail because of the company I work for, we scan all container images that we put in our image repo for any known CVE. These vulnerabilities are provided from various organizations, government or other and have been determined by the DoD organizations to not be acceptable or in need of mitigation. A fellow employee looked into the newer go versions and assessed that they fix some of the vulnerabilities found during the Twistlock scan. Because we intend on using KubeVirt on DoD systems as an in-cluster Kubernetes solution for legacy VMs  we are required to mitigate, fix if we can,  or justify the low to medium CVEs to be able to put Kubevirty into our software factory. We want to put it in the software factory image repo for everyone to use safely and securely. Our base images are locked down so much so I cannot add the upgrade with our restrictions ourselves for instance, in a docker file, because its disconnected from the reaching out and pulling from the internet. Thus, I reached out to the KubeVirt GitHub and created an issue. Thank you for reaching out to me.

V/r,

David Krupa

**Comment by dhiller** [comment]
Hey @David-Krupa, thanks for the heads up!

We do the golang update only now and then when we deem it required.

However, if you want to participate, we have created a guide on how to update the Golang version here: https://github.com/kubevirt/kubevirt/blob/main/docs/update-go-version.md

**Comment by David-Krupa** [comment]
We are working with our team now to determine if this is a feasible option for us and if we are allowed. Otherwise, we would love to get our hands dirty lol.
