### ISSUE TITLE
vmi pending and virt-launcher pod missing

### ISSUE THREAD

**Issue by npu21** [kubevirt/kubevirt#7309]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:
After WaitForFirstConsumer temporary pod virt-launcher  launched and datavolume import successfully，the temporary virt-launcher pod gets killed, I find the formal virtual machine virt-launcher pod missing and the vmi stuck in pending phase
**What you expected to happen**:
The vmi running successfully
**How to reproduce it (as minimally and precisely as possible)**:
We create a batch of vms，some running successfully and others stuck in pending phase
![image](https://user-images.githubusercontent.com/11768607/156725794-7053fd96-2f3f-40e2-8a26-6e582a9d3c16.png)
These vms are the same in base configuration except target nodes as you see in the snapshot. 
They are all WaitForFirstConsumer datavolume. Here's the problematic vmi

And we can see that the datavolumes are imported successfully
![image](https://user-images.githubusercontent.com/11768607/156726707-76ad4c2b-bcf5-4fd6-b1ec-f2a4c916bf43.png)

**Anything else we need to know?**:
we notice that there are scheduler message 0/3 nodes are available: 3 node(s) didn't match Pod's node affinity，but there's only one nodeselector which describes target node that surely satisfied.
After just delete vmi , it created successfully smoothly without any more adjustment.
In virt-controller，we can see errors like this
>{"component":"virt-controller","kind":"","level":"error","msg":"Updating the VirtualMachine status failed.","name":"mgt10","namespace":"cie","pos":"vm.go:303","reason":"Operation cannot be fulfilled on virtualmachines.kubevi                          rt.io \"mgt10\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2022-03-04T02:49:49.834792Z","uid":"6ce59671-33e4-4eda-81f0-27820d937e0b"}
{"component":"virt-controller","level":"info","msg":"re-enqueuing VirtualMachine cie/mgt10","pos":"vm.go:161","reason":"Operation cannot be fulfilled on virtualmachines.kubevirt.io \"mgt10\": the object has been modified; pl                          ease apply your changes to the latest version and try again","timestamp":"2022-03-04T02:49:49.834894Z"}
{"component":"virt-controller","level":"info","msg":"reenqueuing VirtualMachineInstance cie/mgt10","pos":"vmi.go:217","reason":"Operation cannot be fulfilled on virtualmachineinstances.kubevirt.io \"mgt10\": the object has b                          een modified; please apply your changes to the latest version and try again","timestamp":"2022-03-04T02:49:50.038153Z"}
{"component":"virt-controller","kind":"","level":"error","msg":"Updating api version annotations failed","name":"mgt11","namespace":"cie","pos":"vm.go:195","reason":"Operation cannot be fulfilled on virtualmachines.kubevirt.                          io \"mgt11\": the object has been modified; please apply your changes to the latest version and try again","timestamp":"2022-03-04T02:49:50.445784Z","uid":"a5920585-1354-46dd-89f3-96e3c847fe4a"}
{"component":"virt-controller","level":"info","msg":"re-enqueuing VirtualMachine cie/mgt11","pos":"vm.go:161","reason":"Operation cannot be fulfilled on virtualmachines.kubevirt.io \"mgt11\": the object has been modified; pl                          ease apply your changes to the latest version and try again","timestamp":"2022-03-04T02:49:50.445902Z"}

**Environment**:
- KubeVirt version (use `virtctl version`):
- v0.41.0
- Kubernetes version (use `kubectl version`):
- v1.20.13
- VM or VMI specifications:
```Name:         mgt10
Namespace:    cie
Labels:       special=mgt10
Annotations:  kubevirt.io/latest-observed-api-version: v1
              kubevirt.io/storage-observed-api-version: v1alpha3
API Version:  kubevirt.io/v1
Kind:         VirtualMachineInstance
Metadata:
  Creation Timestamp:  2022-03-04T01:32:35Z
  Finalizers:
    foregroundDeleteVirtualMachine
  Generation:  5
  Owner References:
    API Version:           kubevirt.io/v1
    Block Owner Deletion:  true
    Controller:            true
    Kind:                  VirtualMachine
    Name:                  mgt10
    UID:                   68aa2287-fdcf-4bd6-adca-752a6a0e36ca
  Resource Version:        203875
  Self Link:               /apis/kubevirt.io/v1/namespaces/cie/virtualmachineinstances/mgt10
  UID:                     06760a3b-468a-4fd5-a016-7db8a6f07514
Spec:
  Domain:
    Cpu:
      Cores:    1
      Sockets:  16
      Threads:  1
    Devices:
      Disks:
        Disk:
          Bus:  virtio
        Name:   system-disk-ssd-40g-0
        Disk:
          Bus:  virtio
        Name:   data-disk-60g-1
        Disk:
          Bus:  virtio
        Name:   cloudinitdisk
      Interfaces:
        Bridge:
        Model:  virtio
        Name:   default
        Bridge:
        Model:  virtio
        Name:   manage
        Bridge:
        Model:  virtio
        Name:   control
        Bridge:
        Model:  virtio
        Name:   data
        Bridge:
        Model:                       virtio
        Name:                        storage
      Network Interface Multiqueue:  true
    Features:
      Acpi:
        Enabled:  true
    Firmware:
      Serial:  vm-sample-mgt10
      Uuid:    a5e23e5f-bd57-5e48-ba3c-aa56d2b5774f
    Machine:
      Type:  q35
    Memory:
      Guest:  48Gi
    Resources:
      Limits:
        Memory:  51Gi
      Requests:
        Cpu:     100m
        Memory:  48Gi
  Networks:
    Name:  default
    Pod:
    Multus:
      Network Name:  manage
    Name:            manage
    Multus:
      Network Name:  control
    Name:            control
    Multus:
      Network Name:  data
    Name:            data
    Multus:
      Network Name:  storage
    Name:            storage
  Node Selector:
    kubernetes.io/hostname:          mgt01
  Priority Class Name:               system-node-critical
  Termination Grace Period Seconds:  0
  Volumes:
    Data Volume:
      Name:  mgt10-system-disk-ssd-40g-0
    Name:    system-disk-ssd-40g-0
    Data Volume:
      Name:  mgt10-data-disk-60g-1
    Name:    data-disk-60g-1
    Cloud Init No Cloud:
    Name:  cloudinitdisk
Status:
  Conditions:
    Last Probe Time:       <nil>
    Last Transition Time:  <nil>
    Status:                True
    Type:                  Provisioning
    Last Probe Time:       <nil>
    Last Transition Time:  2022-03-04T01:32:38Z
    Message:               0/3 nodes are available: 3 node(s) didn't match Pod's node affinity.
    Reason:                Unschedulable
    Status:                False
    Type:                  PodScheduled
  Guest OS Info:
  Phase:  Pending
Events:   <none>```

**Comment by dhiller** [comment]
/triage needs-information

Can you add a list of all pods in the namespace? Can you also add list of events for all namespaces here? Thank you!
