### ISSUE TITLE
Drop experimental ignition support

### ISSUE THREAD

**Issue by dominikholler** [kubevirt/kubevirt#7310]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:

kubevirt has currently experimental support for igntion.
This was introduced by the PR "Add Ignition Support #1657"
Presented in blog post https://kubevirt.io/2018/ignition-support.html .
Currently,  the ignition data can be injected into kubevirt VMs using openstack ready images using cloud-init config drive like this:

```
...
spec:
  dataVolumeTemplates:
    - metadata:
        name: rhcos-vm0-rootdisk
      spec:
        source:
          registry:
            url: 'docker://quay.io/containerdisks/rhcos:4.9'
...
template:
    spec:
...
      volumes:
        - cloudInitConfigDrive:
            userData: |
              {
                "ignition": {
                  "config": {},
                  "proxy": {},
                  "security": {},
                  "timeouts": {},
                  "version": "3.2.0"
                },
                "passwd": {
                  "users": [
                    {
                      "name": "coreos",
                      "sshAuthorizedKeys": [
                        "ssh-rsa AAAA...Jv me@something"
                      ]
                    }
                  ]
                },
                "storage": {},
                "systemd": {}
              }
          name: cloudinitdisk

```
as documented in https://coreos.github.io/ignition/supported-platforms/ .
So there might be no need anymore to keep the experimental ignition support in kubevirt.

**What you expected to happen**:
The experimental ignition support is being removed from kubevirt code.

**Comment by tacerus** [comment]
Passing the Ignition data in as a Cloud-Init script works? Does Ignition not expect a configuration drive with a `Ignition` volume label and a `/ignition/config.ign` file structure?
