### ISSUE TITLE
The "virt-handler" has a status of "CrashLoopBackOff" due to failure to install SELinux Policy.

### ISSUE THREAD

**Issue by chattytak** [kubevirt/kubevirt#7314]
**Is this a BUG REPORT or FEATURE REQUEST?**:

> Uncomment only one, leave it on its own line:
>
> /kind bug

**What happened**:

```
# kubectl logs -n kubevirt virt-handler-29fxq
{"component":"virt-handler","hostname":"xxxxxxxxxxxxxxxxxx","level":"info","pos":"virt-handler.go:194","timestamp":"2022-03-04T19:22:49.072632Z"}
W0304 19:22:49.073657   61270 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
{"component":"virt-handler","level":"info","msg":"set verbosity to 2","pos":"virt-handler.go:453","timestamp":"2022-03-04T19:22:49.083924Z"}
{"component":"virt-handler","level":"info","msg":"set verbosity to 2","pos":"virt-handler.go:453","timestamp":"2022-03-04T19:22:49.083924Z"}
{"component":"virt-handler","level":"info","msg":"setting rate limiter to 5 QPS and 10 Burst","pos":"virt-handler.go:462","timestamp":"2022-03-04T19:22:49.083994Z"}
{"component":"virt-handler","level":"info","msg":"CPU features of a minimum baseline CPU model: map[apic:true clflush:true cmov:true cx16:true cx8:true de:true fpu:true fxsr:true lahf_lm:true lm:true mca:true mce:true mmx:true msr:true mtrr:true nx:true pae:true pat:true pge:true pni:true pse:true pse36:true sep:true sse:true sse2:true sse4.1:true ssse3:true syscall:true tsc:true]","pos":"cpu_plugin.go:96","timestamp":"2022-03-04T19:22:49.092993Z"}
{"component":"virt-handler","level":"warning","msg":"host model mode is expected to contain only one model","pos":"cpu_plugin.go:103","timestamp":"2022-03-04T19:22:49.093035Z"}
{"component":"virt-handler","level":"error","msg":"something happened during opening kvm file: open /dev/kvm: no such file or directory","pos":"kvm-caps-info-plugin_amd64.go:226","timestamp":"2022-03-04T19:22:49.093540Z"}
{"component":"virt-handler","level":"info","msg":"node-labeller is running","pos":"node_labeller.go:94","timestamp":"2022-03-04T19:22:49.093625Z"}
{"component":"virt-handler","level":"info","msg":"set verbosity to 2","pos":"virt-handler.go:453","timestamp":"2022-03-04T19:22:49.093684Z"}
{"component":"virt-handler","level":"info","msg":"setting rate limiter to 5 QPS and 10 Burst","pos":"virt-handler.go:462","timestamp":"2022-03-04T19:22:49.093700Z"}
{"component":"virt-handler","level":"info","msg":"Starting domain stats collector: node name=sv-k0sworker-01.ad.chattytak.com","pos":"prometheus.go:446","timestamp":"2022-03-04T19:22:49.094139Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer CRDInformer","pos":"virtinformers.go:306","timestamp":"2022-03-04T19:22:49.094203Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer kubeVirtInformer","pos":"virtinformers.go:306","timestamp":"2022-03-04T19:22:49.094217Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer vmiInformer-sources","pos":"virtinformers.go:306","timestamp":"2022-03-04T19:22:49.094225Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer vmiInformer-targets","pos":"virtinformers.go:306","timestamp":"2022-03-04T19:22:49.094232Z"}
{"component":"virt-handler","level":"info","msg":"STARTING informer extensionsKubeVirtCAConfigMapInformer","pos":"virtinformers.go:306","timestamp":"2022-03-04T19:22:49.094237Z"}
{"component":"virt-handler","level":"info","msg":"metrics: max concurrent requests=3","pos":"virt-handler.go:477","timestamp":"2022-03-04T19:22:49.094791Z"}
{"component":"virt-handler","level":"info","msg":"certificate with common name 'kubevirt.io:system:client:virt-handler' retrieved.","pos":"cert-manager.go:198","timestamp":"2022-03-04T19:22:49.095515Z"}
{"component":"virt-handler","level":"info","msg":"certificate with common name 'kubevirt.io:system:node:virt-handler' retrieved.","pos":"cert-manager.go:198","timestamp":"2022-03-04T19:22:49.095685Z"}
{"component":"virt-handler","level":"info","msg":"Updating cluster config from KubeVirt to resource version '18457'","pos":"configuration.go:320","timestamp":"2022-03-04T19:22:49.114333Z"}
{"component":"virt-handler","level":"info","msg":"set verbosity to 2","pos":"virt-handler.go:453","timestamp":"2022-03-04T19:22:49.114388Z"}
{"component":"virt-handler","level":"info","msg":"setting rate limiter to 5 QPS and 10 Burst","pos":"virt-handler.go:462","timestamp":"2022-03-04T19:22:49.114409Z"}
{"component":"virt-handler","level":"info","msg":"SELinux is reported as 'enforcing'","pos":"virt-handler.go:377","timestamp":"2022-03-04T19:22:49.126729Z"}
panic: failed to install virt-launcher selinux policy: failed to install policy /var/run/kubevirt/virt_launcher.cil - out: "Failed to resolve typeattributeset statement at /var/lib/selinux/targeted/tmp/modules/400/virt_launcher/cil:15\n/sbin/semodule:  Failed!\n", error: exit status 1

goroutine 1 [running]:
main.(*virtHandlerApp).Run(0xc000380d80)
        cmd/virt-handler/virt-handler.go:381 +0x2898
main.main()
        cmd/virt-handler/virt-handler.go:595 +0x54

```

**What you expected to happen**:
Successful installation.

**How to reproduce it (as minimally and precisely as possible)**:
- `export VERSION=$(curl -s https://api.github.com/repos/kubevirt/kubevirt/releases | grep tag_name | grep -v -- '-rc' | sort -r | head -1 | awk -F': ' '{print $2}' | sed 's/,//' | xargs)`
- `echo $VERSION`
- `kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/kubevirt-operator.yaml`
- `kubectl create configmap kubevirt-config -n kubevirt --from-literal debug.useEmulation=true`
- `kubectl create -f https://github.com/kubevirt/kubevirt/releases/download/${VERSION}/kubevirt-cr.yaml`
- `kubectl get pod -n kubevirt`

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`):
  - `I am in trouble before that.`
- Kubernetes version (use `kubectl version`): 
  - `Server Version: version.Info{Major:"1", Minor:"23", GitVersion:"v1.23.3+k0s", GitCommit:"4aa55b7164aa739879a769a4e754bf479b8675cf", GitTreeState:"clean", BuildDate:"2022-02-17T17:42:36Z", GoVersion:"go1.17.7", Compiler:"gc", Platform:"linux/amd64"}`
- VM or VMI specifications:
  - `I am in trouble before that.`
- Cloud provider or hardware configuration:
  -  `Bhyve Virtual Machine`
- OS (e.g. from /etc/os-release):
  - `NAME="Rocky Linux"
    VERSION="8.5 (Green Obsidian)"
    ID="rocky"
    ID_LIKE="rhel centos fedora"
    VERSION_ID="8.5"
    PLATFORM_ID="platform:el8"
    PRETTY_NAME="Rocky Linux 8.5 (Green Obsidian)"
    ANSI_COLOR="0;32"
    CPE_NAME="cpe:/o:rocky:rocky:8.5:GA"
    HOME_URL="https://rockylinux.org/"
    BUG_REPORT_URL="https://bugs.rockylinux.org/"
    ROCKY_SUPPORT_PRODUCT="Rocky Linux"
    ROCKY_SUPPORT_PRODUCT_VERSION="8" `
- Kernel (e.g. `uname -a`):
  - `Linux xxxxxxxxxxxxxxxxxx 4.18.0-348.el8.0.2.x86_64 #1 SMP Sun Nov 14 00:51:12 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux`
- Install tools:
- Others:
```
# sestatus
SELinux status:                 enabled
SELinuxfs mount:                /sys/fs/selinux
SELinux root directory:         /etc/selinux
Loaded policy name:             targeted
Current mode:                   enforcing
Mode from config file:          enforcing
Policy MLS status:              enabled
Policy deny_unknown status:     allowed
Memory protection checking:     actual (secure)
Max kernel policy version:      33
```

**Comment by dhiller** [comment]
@xpivarc can you follow up on this one, please? Thank you!

**Comment by xpivarc** [comment]
Hi, can you ensure you have SELinux policies(container_t) installed on the underlying OS? Can you run arbitrary Pod with SELinux enabled?

**Comment by xpivarc** [comment]
Can you check the problematic attribute `seinfo -a | grep container_domain`?

**Comment by chattytak** [comment]
`# seinfo -a | grep container_domain` response was an empty letter.

I additionally typed the following command, but the containerd process was not container_t, so it seems that container_t is not working effectively, assuming it exists.
All the pod processes already running were also unconfined_service_t.

So even if kubevirt detected that the OS setting was Enforce and the failure to add SELinux Policy for container_t was resolved, and the policy was successfully added, I did not think that the policy would be reflected in the actual pod.

```
# ps -Z $(pgrep containerd) | grep 'containerd '
system_u:system_r:unconfined_service_t:s0 1829 ? Sl    12:55 /var/lib/k0s/bin/containerd --root=/var/lib/k0s/containerd --state=/run/k0s/containerd --address=/run/k0s/containerd.sock --log-level=info --config=/etc/k0s/containerd.toml
```
Assuming it was a compatibility problem between the Kubernetes distribution k0s and kubevirt, is this a problem that can be solved by me setting the OS setting to Permissive or Disabled?
Or is it a problem with the logic that determines if virt-handler's SELinux is enabled or not?
As a suggestion, which I cannot judge whether it is feasible or not, wouldn't it be appropriate, for example, to make the logic for determining that SELinux is disabled, besides the OS setting being Permissive or Disabled, to consider SELinux disabled if the type of the virt-handler's own process is unconfined_service_t?

**Comment by chattytak** [comment]
Sorry for the late reply.

I was able to work around the problem by making it Permissive or installing the `container-selinux` package.
However, I am currently setting up my test environment in a BSD-based bhyve virtual environment, so I can't use kvm and can't actually check the VM to deploy it.
I thought `kubectl create configmap kubevirt-config -n kubevirt --from-literal debug.useEmulation=true` would work even in environments where Nested KVM is not available, but that is not the case I have not found the reason for this.

Also, just curious if you know, does this selinux problem not happen with kind or minikube in the examples in the official KubeVirt documentation?
In using kubevirt on k0s, I referred to the procedures for kind and minikube, but I was not aware of any configuration or dependency instructions regarding selinux.

**Comment by xpivarc** [comment]
@chattytak You should configure the emulation on the `Kubevirt` resource(We have deprecated the configmap, I admit it depends on your version of kubevirt). 
>Also, just curious if you know, does this selinux problem not happen with kind or minikube in the examples in the official KubeVirt documentation?
In using kubevirt on k0s, I referred to the procedures for kind and minikube, but I was not aware of any configuration or dependency instructions regarding selinux.

I am not aware of the issues in these two cases. Can you open a new separate issue where you point out this dependency is missing? I am sure someone will pick it up.

**Comment by chattytak** [comment]
New issue on #7453.

I see that the emulation feature has been re-specified but the documentation has not caught up.
I had planned to run KubeVirt on a bare-metal Kubernetes cluster after completing the deployment test in a Bhyve-VM environment, so I quickly migrated to a bare-metal environment and successfully started testvm. Thank you.
