### ISSUE TITLE
compiling problem: staging/src/kubevirt.io/client-go/log/log.go:99:3: undefined: glog.SetLogFile

### ISSUE THREAD

**Issue by lixiaobing1** [kubevirt/kubevirt#7319]
1、in staging/src/kubevirt.io/client-go/log/log.go
"github.com/golang/glog"
glog.SetLogFile(logger)

2、in staging/src/github.com/golang/glog/glog.go
func SetLogFile(l log2.Logger) {
	logger = l
	toStderr = true
}

3、but 
compiling problem: 

make go-all
hack/dockerized "export KUBEVIRT_NO_BAZEL=true && KUBEVIRT_VERSION= ./hack/build-go.sh install  && ./hack/build-copy-artifacts.sh  && DOCKER_PREFIX= DOCKER_TAG= IMAGE_PULL_POLICY= VERBOSITY= ./hack/build-manifests.sh"
go version go1.17.5 linux/amd64

bffc5351f1a607c715d0039482b164317a0a1c500c86c6cd1b17df48bf0cba52
go version go1.17.5 linux/amd64
# kubevirt.io/kubevirt/staging/src/kubevirt.io/client-go/log
staging/src/kubevirt.io/client-go/log/log.go:99:3: undefined: glog.SetLogFile
Makefile:13: recipe for target 'go-all' failed
make: *** [go-all] Error 1

**Comment by lixiaobing1** [comment]
thx:)

**Comment by dhiller** [comment]
/triage needs-information

Can you add the information on what commit it failed like this! Thank you!

**Comment by rmohr** [comment]
I just tried this on latest main:

```
$ make go-all
hack/dockerized "export KUBEVIRT_NO_BAZEL=true && KUBEVIRT_VERSION= ./hack/build-go.sh install  && ./hack/build-copy-artifacts.sh  && DOCKER_PREFIX= DOCKER_TAG= IMAGE_PULL_POLICY= VERBOSITY= ./hack/build-manifests.sh"
go version go1.17.5 linux/amd64

2175e83626f7ee23e7eb6d9ec6b0bc712467db6d005436a10fd901600a829d43
go version go1.17.5 linux/amd64
building static binary container-disk
building dynamic binary virt-operator
building dynamic binary virt-controller
building dynamic binary virt-launcher
building dynamic binary virt-handler
building dynamic binary virtctl
building dynamic binary fake-qemu-process
building dynamic binary virt-api
building dynamic binary subresource-access-test
building dynamic binary example-hook-sidecar
building dynamic binary example-cloudinit-hook-sidecar
building dynamic binary virt-chroot
```

It seems to work for me.

**Comment by lixiaobing1** [comment]
yeah, when gomod11 off, it will search in vendor.
when gomod11 on, why not search in staging ? how to config to search?
thx:)

**Comment by rmohr** [comment]
kubevirt is built around using vendoring. The staging modules are linked into the vendor folder. If you need to build without vendoring, you can "replace" the client-go staging repo in the `go.mod` and point it to the staging folder (https://thewebivore.com/using-replace-in-go-mod-to-point-to-your-local-module/).

**Comment by rmohr** [comment]
We could probably add permanent replace directives in the main `go.mod`. What do you think?
