### ISSUE TITLE
[Feature Request] Allow option in virtctl for persistent VNC connections rather than closing on client disconnect

### ISSUE THREAD

**Issue by emilyastranova** [kubevirt/kubevirt#7323]
**Is this a BUG REPORT or FEATURE REQUEST?**: Feature request

> /kind enhancement

**What happened**: VNC session with virtctl vnc proxy closes automatically

**What you expected to happen**: Would like for the option to have a persistent connection that is still open and listening after disconnect

This is actually mentioned here and never addressed:
> In case `onlyProxy == true`, the `doneChan` will not be closed and the above goroutine would not terminate.
It may be what we want, that the proxy does not terminate when the client disconnects. But in that case, could it support reconnect?
_Originally posted by @akrejcir in https://github.com/kubevirt/kubevirt/pull/3289#discussion_r416704610_

**How to reproduce it (as minimally and precisely as possible)**: Connect using `virtctl vnc --proxy-only vmname` and disconnect the VNC client

**Anything else we need to know?**: N/A

**Environment**: `Any`
- KubeVirt version (use `virtctl version`): `v0.45.0`
- Kubernetes version (use `kubectl version`): `1.21.7+rke2r1`
- VM or VMI specifications: `N/A`
- Cloud provider or hardware configuration: `openSUSE Harvester v1.0.0`
- OS (e.g. from /etc/os-release):
```
NAME="Harvester"
ID="harvester"
ID_LIKE="suse opensuse"
VERSION_ID="20211215"
PRETTY_NAME="Harvester v1.0.0"
```
- Kernel (e.g. `uname -a`): Linux harvester 5.3.18-59.37-default
- Install tools: `N/A`
- Others: `N/A`

**Comment by dhiller** [comment]
/triage accepted

At least having an option to transparently reconnect sounds reasonable.

**Comment by tyleraharrison** [comment]
Would still like to work on this

**Comment by tyleraharrison** [comment]
Oh no

**Comment by xpivarc** [comment]
/reopen
@tyleraharrison  Do you want to be assign on this?

**Comment by tyleraharrison** [comment]
> /reopen
> @tyleraharrison  Do you want to be assign on this?

Unfortunately I'm sort of out of the development cycle for the foreseeable future. We had to drop kubevirt from our stack (Harvester HCI specifically) in favor of Proxmox for various reasons. Love the project, might revisit later, but for now this is better suited for someone else

**Comment by dhiller** [comment]
/area virtctl

@aburdenthehand maybe this could be a hacktoberfest issue

**Comment by patronus-iitr** [comment]
Would like to work on it, please assign

**Comment by itsdarshankumar** [comment]
Interested to work, please assign it to me
