### ISSUE TITLE
failed to look up user qemu: user: unknown user qemu

### ISSUE THREAD

**Issue by lixiaobing1** [kubevirt/kubevirt#7341]
use 0.50.0 to deploy windows, logs following in virt-handler:

{"component":"virt-handler","level":"error","msg":"failed to write pod Interface to ifCache, failed to look up user qemu: user: unknown user qemu","pos":"podnic.go:146","reason":"failed to look up user qemu: user: unknown user qemu","timestamp":"2022-03-10T03:35:37.533582Z"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"win2016","namespace":"admin","pos":"vm.go:1686","reason":"failed to configure vmi network: setup failed, err: failed plugging phase1 at nic 'eth0': failed to look up user qemu: user: unknown user qemu","timestamp":"2022-03-10T03:35:37.533633Z","uid":"cb2ffe22-cfdc-4dbe-bad4-60a7b7c9609f"}

**Comment by lixiaobing1** [comment]
thx:)

**Comment by cryice** [comment]
@lixiaobing1 how to resolve ? could you help me

**Comment by xpivarc** [comment]
@cryice Are you using custom images?
