### ISSUE TITLE
Unknown model type 'virtio-non-transitional'

### ISSUE THREAD

**Issue by lixiaobing1** [kubevirt/kubevirt#7343]
deploy windows with pvc:

{"component":"virt-handler","kind":"","level":"info","msg":"mounting kernel artifacts","name":"win2016","namespace":"admin","pos":"mount.go:407","timestamp":"2022-03-10T06:48:14.519788Z","uid":"6463c51d-aed6-46b3-9c6a-33d76eac349b"}
{"component":"virt-handler","kind":"","level":"info","msg":"kernel boot not defined - nothing to mount","name":"win2016","namespace":"admin","pos":"mount.go:410","timestamp":"2022-03-10T06:48:14.519815Z","uid":"6463c51d-aed6-46b3-9c6a-33d76eac349b"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"win2016","namespace":"admin","pos":"vm.go:1686","reason":"server error. command SyncVMI failed: \"LibvirtError(Code=67, Domain=20, Message='unsupported configuration: Unknown model type 'virtio-non-transitional'')\"","timestamp":"2022-03-10T06:48:14.540535Z","uid":"6463c51d-aed6-46b3-9c6a-33d76eac349b"}

apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: win
  namespace: admin
  labels:
    special: key
  annotations:
spec:
  domain:
    resources:
      requests:
        memory: 8Gi
    devices:
      disks:
      - disk:
          bus: virtio
        name: win
  volumes:
  - name: win
    persistentVolumeClaim:
      claimName: win

**Comment by lixiaobing1** [comment]
when I set useVirtioTransitional: true, errors:
    unsupported configuration: Unknown model type 'virtio-transitional
so what can i set for useVirtioTransitional?

**Comment by rmohr** [comment]
@lixiaobing1 do you use our official builds, or do you build your own virt-launcher containers?

**Comment by lixiaobing1** [comment]
@rmohr yeah, libvirt is old, thx:)
