### ISSUE TITLE
Allow kubervirt to run on minishift and minikube

### ISSUE THREAD

**Issue by gbraad** [kubevirt/kubevirt#736]
Provide add-ons for the usual demo setups:

* [ ] https://github.com/minishift/minishift-addons/issues/28
* [x] https://github.com/kubernetes/minikube/issues/2178

* [x] Enable nesting for minikube https://github.com/kubernetes/minikube/issues/2553
* [ ] Enable nesting for minishift https://github.com/minishift/minishift/issues/2042

**Comment by gbraad** [comment]
@fabiand Minikube already has most (if not all) needed components in the Minikube ISO. Although we can use this ISO for Minishift, we likely need to add something to the CentOS ISO. Would be a good idea to inventorise what is needed here.

**Comment by fabiand** [comment]
Yes. To me the first step is to start playing with it, and see what is needed, then we can enumerate.

I'm just trying to see who is motivated to work on this :)

**Comment by gbraad** [comment]
More than willing to assist 'that person'.

-- 

   Gerard Braad | http://gbraad.nl
   [ Doing Open Source Matters ]

**Comment by simon3z** [comment]
@yuvalif have you been working on part of this?

**Comment by yuvalif** [comment]
For the minikube case, I tried the kubevirt demo, it it works. Also, tried a local CentOS7 VM, with my own PV and PVC, and it worked as well (note that you have to start minikube with the correct features gates fir the local VM case to work).
For the minishift case, there was some privilages issues, I tried adding the following, before trying to install kubvevirt, but could not make it work:
```
$ oc adm policy add-scc-to-user privileged -z kubevirt-controller -n kube-system
$ oc adm policy add-scc-to-user privileged -z kubevirt-testing -n kube-system
$ oc adm policy add-scc-to-user privileged -z kubevirt-privileged -n kube-system
$ oc adm policy add-scc-to-user privileged -z kubevirt-handler -n kube-system 	
```
For the kubevirt installation, I just used "oc" instead of "kubectl":
```
$ oc create -f \
https://github.com/kubevirt/kubevirt/releases/download/v0.3.0/kubevirt.yaml
```

**Comment by gbraad** [comment]
Minishift will surely miss some packages in the CentOS LiveCD we use

**Comment by fabiand** [comment]
I actually think that #732 will fix that you need to run `oc adm policy add-scc-to-user` manually.

**Comment by fabiand** [comment]
Today we are easily able to run on minikube.

We need to validate the state of minishift.

**Comment by gbraad** [comment]
We are dropping support to use the Minikube ISO with Minishift. So we might
have to re-evaluate what is needed on tje CentOS ISO side to make this work.

**Comment by fabiand** [comment]
@gbraad yeah ... To me minishift is really a dedicated bunch of work, as it diverged from minikube so much that it's pretty much the same things over again. (aka backporting nesting, aka kmods for kvm and plugin code)

**Comment by gbraad** [comment]
What is needed on either Fedora or CentOS (from the OS) to make this work?

I would expect libvirt and the kvm modules, but what else?

**Comment by fabiand** [comment]
> What is needed on either Fedora or CentOS (from the OS) to make this work?

It should work on both, nothing special is required from our side.
Actually - if it's a stock centos or fedora, then we probably do not
need any modification as both of them have the modules we need.

> I would expect libvirt and the kvm modules, but what else?

Userspace wise nothing is needed. We bundle all our deps in containers
(including libvirt).

The only requirements are on kmods - The only dependecy I remember is
on the kvm* kmods and associated kernel flags.
