### ISSUE TITLE
Unmanaged PCI device 0000:c3:1b.1 must be manually detached from the host

### ISSUE THREAD

**Issue by lixiaobing1** [kubevirt/kubevirt#7371]
Deploy vm with kubevirt 0.50.0，sriov network，err as following, so how to manually detached from the host?

{"component":"virt-launcher","kind":"","level":"error","msg":
"Failed to start VirtualMachineInstance with flags 0.","name":"win2016",
"namespace":"admin","pos":"manager.go:928","reason":
"virError(Code=55, Domain=0, Message='Requested operation is not valid: Unmanaged PCI device 0000:c3:1b.1 must be manually detached from the host')","timestamp":"2022-03-16T07:08:41.629668Z","uid":"3f45d7ed-da5a-4e1d-a813-d5193fd27763"}

**Comment by lixiaobing1** [comment]
thx:)

**Comment by dhruvik7** [comment]
Hi @lixiaobing1 were you able to resolve this?

**Comment by nightmeng** [comment]
the same issue
