### ISSUE TITLE
failed to hot-plug SR-IOV interfaces

### ISSUE THREAD

**Issue by lixiaobing1** [kubevirt/kubevirt#7409]
kubevirt 0.55.0, deploy ubuntu with sriov:
{"component":"virt-handler","kind":"","level":"error","msg":"failed to hot-plug SR-IOV interfaces: no QEMU process found under process 8141 child processes","name":"ubuntu","namespace":"ubuntu","pos":"vm.go:2542","timestamp":"2022-03-21T02:00:36.890421Z","uid":"094ac1c1-65cd-4ed0-be24-edafcb3d7904"}

**Comment by lixiaobing1** [comment]
thx:)

**Comment by ormergi** [comment]
Hi, this issue lacks info and context please follow the issue template so we could help you.

**Comment by xpivarc** [comment]
Hi, @lixiaobing1 would you be able to provide additional information?
