### ISSUE TITLE
Track kubectl enhancement for better VM service exposure

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#744]
Currently `kubectl expose` does not allow (Bug?) to use a label selector for exposing pods - but this is important for kubevirt.

The flow with a label selector would be:
```bash
kubectl expose pod --selector 'domain=my-vm' …
```
But this leads to an error:

```bash
$ kubectl expose pod --selector "domain=my-vm" …
error: resource(s) were provided, but no name, label selector, or --all flag specified
```

Without the selector the user would need to know the pod name - which is not predictable because it's name is generated:
```
kubectl expose pod virt-launcher-my-vm-x645t …
```

The relevant kubectl bug is https://github.com/kubernetes/kubernetes/issues/59551

**Comment by yuvalif** [comment]
@fabiand is this still needed given that #818 is done?

**Comment by fabiand** [comment]
Yes, I think so ...

It would be convenient if we could select a pod in kubernetes using the selector, then we don't need #818

**Comment by yuvalif** [comment]
not sure that kubectl will cover all needed functionality in "virtctl expose", there is different handling there to the selectors of VMs, VMIs, VM replica sets

**Comment by yuvalif** [comment]
@fabiand can we close this one? did we get feedback that this is needed n top of "virtctl expose"?

**Comment by fabiand** [comment]
Well, I would like to see that kubectl is getting fixed.

So, this is a nice thing to see if it could be fixed in upstream - I had
opened that other issue which is referenced further above.
