### ISSUE TITLE
VMI IP is different with IP in guest OS

### ISSUE THREAD

**Issue by leoryu** [kubevirt/kubevirt#7445]
**What happened**:

I created an vm through kubevirt, bug I found the VMI IP is different with IP in guest OS.

<img width="549" alt="企业微信截图_a67469c1-6f18-4250-b979-8d933d1a1b22" src="https://user-images.githubusercontent.com/34183243/160048548-23d797dd-e427-4dc8-a484-e6236da76b78.png">

<img width="308" alt="企业微信截图_b526598d-3f0a-4d8b-95f0-a0b3308e6c1c" src="https://user-images.githubusercontent.com/34183243/160048640-fcefb8c6-82ad-4003-b094-e05c8a3ccd6f.png">

**What you expected to happen**:

VMI IP should be as same as the IP in guest OS.

**How to reproduce it (as minimally and precisely as possible)**:

I have no idea about it, in my env, some vmi IP is normal, some not.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.50.0
- Kubernetes version (use `kubectl version`): v1.21.4
- VM or VMI specifications: 
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
  creationTimestamp: "2022-03-24T10:39:21Z"
  finalizers:
  - kubevirt.io/virtualMachineControllerFinalize
  - foregroundDeleteVirtualMachine
  generation: 8
  labels:
    kubevirt.io/nodeName: 10.19.0.133
  name: jojo2
  namespace: default
  ownerReferences:
  - apiVersion: kubevirt.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachine
    name: jojo2
    uid: 428058dd-0235-449d-a24d-04284d87a7c1
  resourceVersion: "20532437"
  selfLink: /apis/kubevirt.io/v1/namespaces/default/virtualmachineinstances/jojo2
  uid: 8c707d0b-e884-4b7c-880a-b971a15ec9a6
spec:
  domain:
    cpu:
      cores: 4
      model: host-model
    devices:
      disks:
      - bootOrder: 1
        disk:
          bus: virtio
        name: rootfs
      interfaces:
      - bridge: {}
        model: e1000
        name: default
    features:
      acpi:
        enabled: true
    firmware:
      uuid: 73342ec1-a42f-586d-a4b2-14b5ced54942
    machine:
      type: q35
    resources:
      requests:
        memory: 8G
  networks:
  - name: default
    pod: {}
  volumes:
  - dataVolume:
      name: rootfs.jojo2
    name: rootfs
status:
  activePods:
    5ba219c2-f495-40e2-8a5b-82b00b1d9334: 10.19.0.133
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-03-24T10:39:39Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    message: 'cannot migrate VMI: PVC rootfs.jojo2 is not shared, live migration requires
      that all PVCs must be shared (using ReadWriteMany access mode)'
    reason: DisksNotLiveMigratable
    status: "False"
    type: LiveMigratable
  guestOSInfo: {}
  interfaces:
  - infoSource: domain
    ipAddress: 192.168.1.216
    ipAddresses:
    - 192.168.1.216
    mac: 2e:9c:19:62:2d:d6
    name: default
  launcherContainerImageVersion: quay.io/kubevirt/virt-launcher:v0.50.0
  migrationMethod: BlockMigration
  migrationTransport: Unix
  nodeName: 10.19.0.133
  phase: Running
  phaseTransitionTimestamps:
  - phase: Pending
    phaseTransitionTimestamp: "2022-03-24T10:39:21Z"
  - phase: Scheduling
    phaseTransitionTimestamp: "2022-03-24T10:39:21Z"
  - phase: Scheduled
    phaseTransitionTimestamp: "2022-03-24T10:39:40Z"
  - phase: Running
    phaseTransitionTimestamp: "2022-03-24T10:39:43Z"
  qosClass: Burstable
  virtualMachineRevisionName: revision-start-vm-428058dd-0235-449d-a24d-04284d87a7c1-1
  volumeStatus:
  - name: rootfs
    persistentVolumeClaimInfo:
      accessModes:
      - ReadWriteOnce
      capacity:
        storage: 20Gi
      filesystemOverhead: "0.055"
      requests:
        storage: 20Gi
      volumeMode: Filesystem
    target: vda
```
- Cloud provider or hardware configuration: bare-metal
- OS (e.g. from /etc/os-release): CentOS Linux 7 (Core)
- Kernel (e.g. `uname -a`): 3.10.0-957.10.1.el7.x86_64
- Install tools: N/A
- Others: N/A

**Comment by dhiller** [comment]
/triage needs-information

Can you elaborate a little bit more on what you are expecting vs. what you are seeing, especially where the screenshot originated from? 

Also the cluster default network configuration is important.

**Comment by leoryu** [comment]
When IP of pod is same as the IP inside VM, I can get response from vm through curl pod IP in cluster, but I cannot get response if these IPs are different.

**Comment by leoryu** [comment]
I think this issue is cased by DHCP. When VM is started first time, DHCP server will assign an IP for VM, if VM is rebooted, Pod IP will be changed, but DHCP will not re-assign an new IP for VM, since DHCP doesn't expire.
