### ISSUE TITLE
There is no information about the dependency package (container-selinux) in the documentation.

### ISSUE THREAD

**Issue by chattytak** [kubevirt/kubevirt#7453]
**Description**:

See #1374.
When deploying KubeVirt using a RHEL8-based OS, such as RockyLinux8, the virt-handler container is in a crash loop due to a missing container-selinux package.

The Kubernetes distribution used k0s at this time.
I think part of the reason is that k0s does not require container-selinux packages, but even though KubeVirt also requires container-selinux packages, I could not find any information about them.

Do you think documentation is needed to reduce the number of people having the same problems as me?

**What you expected**:

Document the need for the container-selinux package.

**URL**:

https://kubevirt.io/user-guide/operations/installation/#requirements

**Additional context**:
Add any other context about the issue here.

**Comment by xpivarc** [comment]
https://github.com/kubevirt/kubevirt/pull/8580 should cover this
