### ISSUE TITLE
KubeVirt doesn't seem to be working with kind due to virt-handler fails

### ISSUE THREAD

**Issue by fadams** [kubevirt/kubevirt#7463]
I've been following the instructions in: https://kubevirt.io/quickstart_kind/
My host system is Linux Mint 20.1 (based on Ubuntu 20.04) with working KVM and QEMU
Freshly installed kind deploying images kindest/node:v1.23.4
KubeVirt v0.51.0

My kind cluster stars fine and I successfully deploy the k8s dashboard, which works as expected. Followed the instructions in the quickstart but KubeVirt fails to deploy. Everythng other than the virt-handler daemon set and virt-handler pods seems to be running (green in the dashboard) but virt-handler fails (red in the dashboard).

Running `kubectl --context kind-kvm -n kubevirt logs virt-handler-hnpnv` yields the following:
```
Error from server (BadRequest): container "virt-handler" in pod "virt-handler-hnpnv" is waiting to start: PodInitializing
```
which isn't hugely useful.

Running `kubectl --context kind-kvm -n kubevirt describe pod  virt-handler-hnpnv` yields the following:
```
Name:                 virt-handler-hnpnv
Namespace:            kubevirt
Priority:             1000000000
Priority Class Name:  kubevirt-cluster-critical
Node:                 kvm-worker2/172.18.0.3
Start Time:           Mon, 28 Mar 2022 11:20:19 +0100
Labels:               app.kubernetes.io/component=kubevirt
                      app.kubernetes.io/managed-by=virt-operator
                      app.kubernetes.io/version=v0.51.0
                      controller-revision-hash=7d8cdf9688
                      kubevirt.io=virt-handler
                      pod-template-generation=1
                      prometheus.kubevirt.io=true
Annotations:          kubevirt.io/install-strategy-identifier: bbdcb0420247da747f6f6a7cb65fdeb776df79a6
                      kubevirt.io/install-strategy-registry: quay.io/kubevirt
                      kubevirt.io/install-strategy-version: v0.51.0
Status:               Pending
IP:                   10.244.2.5
IPs:
  IP:           10.244.2.5
Controlled By:  DaemonSet/virt-handler
Init Containers:
  virt-launcher:
    Container ID:  containerd://bcdeeafeacc747ce01b63a8c163b5729bd0cb5d60d0d0824e32f1d0f2bf88122
    Image:         quay.io/kubevirt/virt-launcher:v0.51.0
    Image ID:      quay.io/kubevirt/virt-launcher@sha256:536b11e42c07e0407038b460b52a853c3c5441c7773669950322443d79457de8
    Port:          <none>
    Host Port:     <none>
    Command:
      /bin/sh
      -c
    Args:
      node-labeller.sh
    State:          Waiting
      Reason:       CrashLoopBackOff
    Last State:     Terminated
      Reason:       Error
      Exit Code:    1
      Started:      Mon, 28 Mar 2022 11:29:27 +0100
      Finished:     Mon, 28 Mar 2022 11:29:27 +0100
    Ready:          False
    Restart Count:  6
    Environment:    <none>
    Mounts:
      /var/lib/kubevirt-node-labeller from node-labeller (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-92glz (ro)
Containers:
  virt-handler:
    Container ID:  
    Image:         quay.io/kubevirt/virt-handler:v0.51.0
    Image ID:      
    Port:          8443/TCP
    Host Port:     0/TCP
    Command:
      virt-handler
      --port
      8443
      --hostname-override
      $(NODE_NAME)
      --pod-ip-address
      $(MY_POD_IP)
      --max-metric-requests
      3
      --console-server-port
      8186
      --graceful-shutdown-seconds
      315
      -v
      2
    State:          Waiting
      Reason:       PodInitializing
    Ready:          False
    Restart Count:  0
    Requests:
      cpu:      10m
      memory:   230Mi
    Liveness:   http-get https://:8443/healthz delay=15s timeout=10s period=45s #success=1 #failure=3
    Readiness:  http-get https://:8443/healthz delay=15s timeout=10s period=20s #success=1 #failure=3
    Environment:
      NODE_NAME:   (v1:spec.nodeName)
      MY_POD_IP:   (v1:status.podIP)
    Mounts:
      /etc/podinfo from podinfo (rw)
      /etc/virt-handler/clientcertificates from kubevirt-virt-handler-certs (ro)
      /etc/virt-handler/servercertificates from kubevirt-virt-handler-server-certs (ro)
      /pods from kubelet-pods-shortened (rw)
      /profile-data from profile-data (rw)
      /var/lib/kubelet/device-plugins from device-plugin (rw)
      /var/lib/kubelet/pods from kubelet-pods (rw)
      /var/lib/kubevirt from virt-lib-dir (rw)
      /var/lib/kubevirt-node-labeller from node-labeller (rw)
      /var/run/kubevirt from virt-share-dir (rw)
      /var/run/kubevirt-libvirt-runtimes from libvirt-runtimes (rw)
      /var/run/kubevirt-private from virt-private-dir (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-92glz (ro)
Conditions:
  Type              Status
  Initialized       False 
  Ready             False 
  ContainersReady   False 
  PodScheduled      True 
Volumes:
  kubevirt-virt-handler-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubevirt-virt-handler-certs
    Optional:    true
  kubevirt-virt-handler-server-certs:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  kubevirt-virt-handler-server-certs
    Optional:    true
  profile-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  libvirt-runtimes:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/kubevirt-libvirt-runtimes
    HostPathType:  
  virt-share-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/kubevirt
    HostPathType:  
  virt-lib-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubevirt
    HostPathType:  
  virt-private-dir:
    Type:          HostPath (bare host directory volume)
    Path:          /var/run/kubevirt-private
    HostPathType:  
  device-plugin:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/device-plugins
    HostPathType:  
  kubelet-pods-shortened:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/pods
    HostPathType:  
  kubelet-pods:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubelet/pods
    HostPathType:  
  node-labeller:
    Type:          HostPath (bare host directory volume)
    Path:          /var/lib/kubevirt-node-labeller
    HostPathType:  
  podinfo:
    Type:  DownwardAPI (a volume populated by information about the pod)
    Items:
      metadata.annotations['k8s.v1.cni.cncf.io/network-status'] -> network-status
  kube-api-access-92glz:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 CriticalAddonsOnly op=Exists
                             node.kubernetes.io/disk-pressure:NoSchedule op=Exists
                             node.kubernetes.io/memory-pressure:NoSchedule op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists
                             node.kubernetes.io/pid-pressure:NoSchedule op=Exists
                             node.kubernetes.io/unreachable:NoExecute op=Exists
                             node.kubernetes.io/unschedulable:NoSchedule op=Exists
Events:
  Type     Reason     Age                     From               Message
  ----     ------     ----                    ----               -------
  Normal   Scheduled  12m                     default-scheduler  Successfully assigned kubevirt/virt-handler-hnpnv to kvm-worker2
  Normal   Pulling    12m                     kubelet            Pulling image "quay.io/kubevirt/virt-launcher:v0.51.0"
  Normal   Pulled     9m56s                   kubelet            Successfully pulled image "quay.io/kubevirt/virt-launcher:v0.51.0" in 2m28.676845567s
  Normal   Created    7m29s (x5 over 9m54s)   kubelet            Created container virt-launcher
  Normal   Started    7m29s (x5 over 9m52s)   kubelet            Started container virt-launcher
  Normal   Pulled     7m29s (x4 over 8m54s)   kubelet            Container image "quay.io/kubevirt/virt-launcher:v0.51.0" already present on machine
  Warning  BackOff    2m22s (x30 over 8m51s)  kubelet            Back-off restarting failed container
```
That _seems_ to be suggesting an issue with the virt-launcher init container but I'm not really sure where to go from there.

This issue seems very similar to https://github.com/kubevirt/kubevirt/issues/6939 though there was no resolution to that.

I've also tried following this gist  https://gist.github.com/usrbinkat/a457c96a50e325200fd59ed681a0242d including using the same explicit kind image mentioned there (kindest/node:v1.23.0) and the KubeVirt version mentioned there (v0.48.1) in case my issue was kind/KubeVirt version specific, but I see the same issues when I've tried that too.

**Comment by vasiliy-ul** [comment]
It seems that the init container fails. Could you maybe try to get its logs: `kubectl logs -n kubevirt -c virt-launcher virt-handler-hnpnv` ?

**Comment by fadams** [comment]
Running
`kubectl logs -n kubevirt -c virt-launcher virt-handler-hnpnv` gives

```
error: failed to get emulator capabilities
error: internal error: Failed to start QEMU binary /usr/libexec/qemu-kvm for probing: libvirt:  error : cannot execute binary /usr/libexec/qemu-kvm: Permission denied
```
I do have apparmor enabled that seems to be the default on Ubuntu based distros these days. I don't seem to have a `/var/log/audit/audit.log` however if I do `dmesg | tail` I get:
```
[6118112.834771] audit: type=1400 audit(1648473515.962:1079): apparmor="DENIED" operation="exec" profile="libvirtd" name="/usr/libexec/qemu-kvm" pid=2897911 comm="rpc-worker" requested_mask="x" denied_mask="x" fsuid=107 ouid=0
[6118131.905883] audit: type=1400 audit(1648473535.034:1080): apparmor="DENIED" operation="exec" profile="libvirtd" name="/usr/libexec/qemu-kvm" pid=2898125 comm="rpc-worker" requested_mask="x" denied_mask="x" fsuid=107 ouid=0
[6118397.792993] audit: type=1400 audit(1648473800.909:1081): apparmor="DENIED" operation="exec" profile="libvirtd" name="/usr/libexec/qemu-kvm" pid=2899948 comm="rpc-worker" requested_mask="x" denied_mask="x" fsuid=107 ouid=0
[6118409.736987] audit: type=1400 audit(1648473812.853:1082): apparmor="DENIED" operation="exec" profile="libvirtd" name="/usr/libexec/qemu-kvm" pid=2900257 comm="rpc-worker" requested_mask="x" denied_mask="x" fsuid=107 ouid=0
[6118421.873608] audit: type=1400 audit(1648473824.989:1083): apparmor="DENIED" operation="exec" profile="libvirtd" name="/usr/libexec/qemu-kvm" pid=2900450 comm="rpc-worker" requested_mask="x" denied_mask="x" fsuid=107 ouid=0
[6118437.377707] audit: type=1400 audit(1648473840.492:1084): apparmor="DENIED" operation="exec" profile="libvirtd" name="/usr/libexec/qemu-kvm" pid=2900719 comm="rpc-worker" requested_mask="x" denied_mask="x" fsuid=107 ouid=0
[6118698.781338] audit: type=1400 audit(1648474101.888:1085): apparmor="DENIED" operation="exec" profile="libvirtd" name="/usr/libexec/qemu-kvm" pid=2902514 comm="rpc-worker" requested_mask="x" denied_mask="x" fsuid=107 ouid=0
[6118722.718914] audit: type=1400 audit(1648474125.827:1086): apparmor="DENIED" operation="exec" profile="libvirtd" name="/usr/libexec/qemu-kvm" pid=2902828 comm="rpc-worker" requested_mask="x" denied_mask="x" fsuid=107 ouid=0
[6118729.660580] audit: type=1400 audit(1648474132.771:1087): apparmor="DENIED" operation="exec" profile="libvirtd" name="/usr/libexec/qemu-kvm" pid=2902983 comm="rpc-worker" requested_mask="x" denied_mask="x" fsuid=107 ouid=0
[6118747.024419] audit: type=1400 audit(1648474150.131:1088): apparmor="DENIED" operation="exec" profile="libvirtd" name="/usr/libexec/qemu-kvm" pid=2903348 comm="rpc-worker" requested_mask="x" denied_mask="x" fsuid=107 ouid=0
```
Which does rather suggest that's the culprit.

AppArmor kind of sits in the realm of "the dark arts" for me, I don't suppose you could point me in the direction of a handy way to resolve this?

BTW thanks for the response - and the insight - I don't think I'd have thought to look in that direction given that kvm qemu is actually working on my host under "normal" circumstances.

Ahh I'm wondering - on Ubuntu based systems the qemu executable is `/usr/bin/qemu-system-x86_64` I'm _guessing_ that in the virt-launcher image that's based on a different distro and the package manager for that installs the executable to `/usr/libexec/qemu-kvm` 

In my /etc/apparmor.d I have a usr.lib.libvirt.virt-aa-helper and usr.sbin.libvirtd and in the latter there is a line that starts: `profile libvirtd /usr/sbin/libvirtd flags=(attach_disconnect) {` looking at the dmesg above which includes profile="libvirt" I'm guessing that it's this profile that is causing the deny but I can't even see how that's allowing `/usr/bin/qemu-system-x86_64` given my rather rudimentary AppArmor knowledge.

**Comment by vasiliy-ul** [comment]
The simple way would be just to disable apparmor. Either you can do it completely via e.g. `systemctl stop apparmor` or you can disable the profile: `aa-disable libvirt` (or `aa-complain libvirt`).

Alternatively you can setup the apparmor policy. E.g. on my system I have `/etc/apparmor.d/abstractions/libvirt-qemu` which contains rules to allow the execution of qemu binaries. Adding smth like `/usr/libexec/qemu-kvm rmix,` should do the trick (dont forget to reload apparmor service afterwards).

**Comment by fadams** [comment]
Thanks, yeah I have a `/etc/apparmor.d/abstractions/libvirt-qemu` and that seems to have a section with the comment `# the various binaries` that includes my existing `/usr/bin/qemu-system-x86_64 rmix,`

I think your suggestion Adding smth like /usr/libexec/qemu-kvm rmix, is probably the way to go, I'll have a play. Thanks again - though I might be back :-)

**Comment by fadams** [comment]
I've tried a few things relating to AppArmor now.
Interestingly it appears that stopping the AppArmor service doesn't help - I tried each of:
`sudo systemctl stop apparmor`, `sudo  /etc/init.d/apparmor stop` and `sudo service apparmor stop`, which I think are just different ways of doing the same thing but although according to the status they were marked as inactive afterwards I was still seing "DENIED" though I think that the profile is loaded into the kernel by the service and so doesn't actually need the systemd service once loaded. 

I next tried each of:
`sudo aa-disable /etc/apparmor.d/usr.sbin.libvirtd` and  `sudo aa-complain /etc/apparmor.d/usr.sbin.libvirtd` (doing aa-enforce in between to re-establish the non-working baseline) and both of those appear to allow virt-handler to fully deploy.

With the `aa-complain` the log message I see is:
```
[6180134.577161] audit: type=1400 audit(1648535535.884:3244): apparmor="ALLOWED" operation="exec" profile="libvirtd" name="/usr/libexec/qemu-kvm" pid=3465098 comm="rpc-worker" requested_mask="x" denied_mask="x" fsuid=107 ouid=0 target="libvirtd//null-/usr/libexec/qemu-kvm"
[6180134.577634] audit: type=1400 audit(1648535535.884:3245): apparmor="ALLOWED" operation="file_inherit" profile="libvirtd//null-/usr/libexec/qemu-kvm" name="/dev/null" pid=3465098 comm="qemu-kvm" requested_mask="wr" denied_mask="wr" fsuid=107 ouid=0
[6180134.577653] audit: type=1400 audit(1648535535.884:3246): apparmor="ALLOWED" operation="file_mmap" profile="libvirtd//null-/usr/libexec/qemu-kvm" name="/usr/libexec/qemu-kvm" pid=3465098 comm="qemu-kvm" requested_mask="rm" denied_mask="rm" fsuid=107 ouid=0
[6180134.577686] audit: type=1400 audit(1648535535.884:3247): apparmor="ALLOWED" operation="file_mmap" profile="libvirtd//null-/usr/libexec/qemu-kvm" name="/usr/lib64/ld-2.28.so" pid=3465098 comm="qemu-kvm" requested_mask="rm" denied_mask="rm" fsuid=107 ouid=0
[6180134.577943] audit: type=1400 audit(1648535535.884:3248): apparmor="ALLOWED" operation="open" profile="libvirtd//null-/usr/libexec/qemu-kvm" name="/usr/lib64/liblzo2.so.2.0.0" pid=3465098 comm="qemu-kvm" requested_mask="r" denied_mask="r" fsuid=107 ouid=0
[6180134.577972] audit: type=1400 audit(1648535535.884:3249): apparmor="ALLOWED" operation="file_mmap" profile="libvirtd//null-/usr/libexec/qemu-kvm" name="/usr/lib64/liblzo2.so.2.0.0" pid=3465098 comm="qemu-kvm" requested_mask="rm" denied_mask="rm" fsuid=107 ouid=0
[6180134.578053] audit: type=1400 audit(1648535535.884:3250): apparmor="ALLOWED" operation="open" profile="libvirtd//null-/usr/libexec/qemu-kvm" name="/usr/lib64/libsnappy.so.1.1.8" pid=3465098 comm="qemu-kvm" requested_mask="r" denied_mask="r" fsuid=107 ouid=0
[6180134.578073] audit: type=1400 audit(1648535535.884:3251): apparmor="ALLOWED" operation="file_mmap" profile="libvirtd//null-/usr/libexec/qemu-kvm" name="/usr/lib64/libsnappy.so.1.1.8" pid=3465098 comm="qemu-kvm" requested_mask="rm" denied_mask="rm" fsuid=107 ouid=0
[6180134.578142] audit: type=1400 audit(1648535535.884:3252): apparmor="ALLOWED" operation="open" profile="libvirtd//null-/usr/libexec/qemu-kvm" name="/usr/lib64/libpixman-1.so.0.38.4" pid=3465098 comm="qemu-kvm" requested_mask="r" denied_mask="r" fsuid=107 ouid=0
[6180134.578165] audit: type=1400 audit(1648535535.884:3253): apparmor="ALLOWED" operation="file_mmap" profile="libvirtd//null-/usr/libexec/qemu-kvm" name="/usr/lib64/libpixman-1.so.0.38.4" pid=3465098 comm="qemu-kvm" requested_mask="rm" denied_mask="rm" fsuid=107 ouid=0
```
Which is kind of what I was expecting.
After again re-establishing the (broken) baseline by doing `sudo aa-enforce /etc/apparmor.d/usr.sbin.libvirtd` and restarting my cluster I next tried:
`sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.libvirtd` 
Which removes the profile from the kernel, and again allows virt-handler to reach completion.

However.....
What I can't get working is a fix to an *enabled" profile.

What I've tried is editing `/etc/apparmor.d/abstractions/libvirt-qemu` to add `/usr/libexec/qemu-kvm rmix,` (as you suggested earlier).  That'd seem to make sense given the previous "DENIED" messages and the "ALOWED" ones from aa-complain referring to operation="exec" and name="/usr/libexec/qemu-kvm". There is a section with a comment "# the various binaries" and I added my change after the `/usr/bin/qemu-system-x86_64 rmix,` entry so that section now looks like:
```
...
  /usr/bin/qemu-system-sparc rmix,
  /usr/bin/qemu-system-sparc64 rmix,
  /usr/bin/qemu-system-tricore rmix,
  /usr/bin/qemu-system-unicore32 rmix,
  /usr/bin/qemu-system-x86_64 rmix,
  /usr/libexec/qemu-kvm rmix,
  /usr/bin/qemu-system-xtensa rmix,
  /usr/bin/qemu-system-xtensaeb rmix,
  /usr/bin/qemu-aarch64 rmix,
  /usr/bin/qemu-alpha rmix,
  /usr/bin/qemu-arm rmix,
...
```
I tried reloading the updated profile with `sudo apparmor_parser -r -v -W /etc/apparmor.d/usr.sbin.libvirtd` which reported
```
Replacement succeeded for "qemu_bridge_helper".
Replacement succeeded for "libvirtd".
```
But when I restart my cluster it fails again and the logs report the same "DENIED".

Do you have any suggestions on what I might be doing wrong?

**Comment by vasiliy-ul** [comment]
Interesting, according to https://gitlab.com/apparmor/apparmor/-/wikis/Libvirt , libvirt creates a new profile for each domain basing on the `/etc/apparmor.d/libvirt/TEMPLATE.qemu` (which in turn includes `/etc/apparmor.d/abstractions/libvirt-qemu`). Though before creating such a profile it checks which security driver to use (e.g. Apparmor or SELinux). I have a feeling that libvirt cannot determine the driver when run inside kubevirt container and therefore it does not create the required profile. Though that is just a theory for now... maybe worth taking a look at the libvirt sources.

**Comment by fadams** [comment]
Update:
I'm still not sure why changing `/etc/apparmor.d/abstractions/libvirt-qemu` as above doesn't seem to work and given the comment in there "# the various binaries" that would seem to be the "right" place. Maybe the issue is that the reload doesn't reload these child/abstraction profiles, I dunno, though your observation above that there is some "dynamic magic" seems plausible, as you say it does seem to be the `/etc/apparmor.d/libvirt/TEMPLATE.qemu` that loads the `/etc/apparmor.d/abstractions/libvirt-qemu` but I couldn't really work out what was going on with that nor what the "domain whose UUID matches this file" comment meant. I suspect you are right with your hypothesis "libvirt cannot determine the driver when run inside kubevirt container"

Anyway as an experiment I tried something else. I removed the `/usr/libexec/qemu-kvm rmix,` that I'd added to `/etc/apparmor.d/abstractions/libvirt-qemu` and instead I added it to `/etc/apparmor.d/local/usr.sbin.libvirtd`. TBH I think that the "local" subdir is probably the place to change this stuff.

I then did `sudo apparmor_parser -r -v -W -d -d /etc/apparmor.d/usr.sbin.libvirtd` and the verbose debug from that included `Mode:	rmx:rmx	Name:	(/usr/libexec/qemu-kvm)` which looked promising, and sure enough virt-handler deployed successfully, so that is something of a "win", though it doesn't feel quite right and it's possible that I might see other AppArmor related fails as I actually try to use KubeVirt.

**Comment by vasiliy-ul** [comment]
Well, basically yes, if you add `/usr/libexec/qemu-kvm rmix,` to the main libvirt profile `/etc/apparmor.d/local/usr.sbin.libvirtd` that should also work. Anyway the libvirt version shipped with kubevirt does not detect apparmor so changing (or disabling...) the profile on the host  seems like a valid solution.

**Comment by fadams** [comment]
Out of curiosity do you know if anything about these AppArmor quirks is mentioned anywhere in the KubeVirt docs? TBH in the first instance I basically just followed the https://kubevirt.io/quickstart_kind/ then found myself in this hole and it looks like others might have been similarly bitten - I'd guess anyone using a modern Ubuntu based distro (probably others too) is likely to have this fail.

Should I raise a change request ticket requesting this to be flagged in the docs?

**Comment by vasiliy-ul** [comment]
Not sure if it is mentioned somewhere in the docs. AFAIK KubeVirt 'natively' supports only SELinux. This is not the first time someone is raising Apparmor-related issue. Definitely adding Apparmor related bits would be a good contribution to the project.

E.g. previously it was discussed here: https://kubernetes.slack.com/archives/C8ED7RKFE/p1644226272859289
