### ISSUE TITLE
Please update docs to flag up AppArmor issues on Ubuntu based hosts (and probably others)

### ISSUE THREAD

**Issue by fadams** [kubevirt/kubevirt#7473]
When starting out on KubeVirt it's common practice to begin with the quickstarts as suggested at the start of the user guide https://kubevirt.io/user-guide/#try-it-out

For example I basically just followed the https://kubevirt.io/quickstart_kind/ then found myself in a bit of a hole as virt-handler wouldn't deploy.

It turns out that my issue was due to the libvirtd AppArmor profile deployed when qemu/kvm was installed - just using the regular Ubuntu apt install method.

This thread https://github.com/kubevirt/kubevirt/issues/7463 covers my journey trying to figure out what on earth was going on.

This sort of issue is a little bit opaque/non-obvious particularly given a working qemu/kvm on the host and relates to executable paths in the container being different to those on the host (due to being a different distro) and thus being blocked by AppArmor.

There are a few workarounds:
1. Disable the libvirtd AppArmor profile: `sudo aa-disable /etc/apparmor.d/usr.sbin.libvirtd`
2. Set the profile to complain rather than enforce: `sudo aa-complain /etc/apparmor.d/usr.sbin.libvirtd`
3. Remove the profile from the kernel: `sudo apparmor_parser -R /etc/apparmor.d/usr.sbin.libvirtd`

Those have the disadvantage of stopping the profile completely, so in the end what I did was:
1. Add the line `/usr/libexec/qemu-kvm rmix,` to the file `/etc/apparmor.d/local/usr.sbin.libvirtd`
2. Reload the profile: `sudo apparmor_parser -r -W /etc/apparmor.d/usr.sbin.libvirtd`

There may be better ways, but that at least seems to work.

As it's a fairly non-obvious and quite hard to diagnose problem it would be good if the documentation could be updated to reflect the fact that AppArmor might well cause issues on distros that run AppArmor by default (Ubuntu and its derivatives, and probably others too).

**Comment by dhiller** [comment]
/triage accepted

@fadams would you be willing to work on this?

**Comment by vasiliy-ul** [comment]
https://kubevirt.io/user-guide/operations/installation/#integration-with-apparmor
