### ISSUE TITLE
Live Migration progress metrics

### ISSUE THREAD

**Issue by borod108** [kubevirt/kubevirt#7487]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:

This issue is about adding better track-ability for live migrations, i.e exposing relevant metrics from the VMI so that Prometheus can read and display it. We have identified the following 4 metrics to be exposed to prometheus. The first three metrics are from libvirt and the last one is a derived metric.

The Goal is to provide basis for future work on providing track-ability and estimation for users.

**What you expected to happen**:
We expect the following three metrics to be added:
* DATA_PROCESSED Amount of data that has been processed so far
https://libvirt.org/html/libvirt-libvirt-domain.html#VIR_DOMAIN_JOB_DATA_PROCESSED
* DATA_REMAINING Amount of data that still needs to be transferred
https://libvirt.org/html/libvirt-libvirt-domain.html#VIR_DOMAIN_JOB_DATA_REMAINING
* MEMORY_DIRTY_RATE Rate at which the memory is dirtying
https://libvirt.org/html/libvirt-libvirt-domain.html#VIR_DOMAIN_JOB_MEMORY_DIRTY_RATE

* One Derived Metric
KV_DATA_TRANSFER_RATE Rate at which the transfer is happening

**Comment by usrbinkat** [comment]
This is a work in progress on #7513

**Comment by borod108** [comment]
Closed by:
https://github.com/kubevirt/kubevirt/pull/7474
And later improved by:
https://github.com/kubevirt/kubevirt/pull/7946
