### ISSUE TITLE
Open questions around VirtualMachinePresets

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#749]
Anybody, feel free to add more items

- Should we diverge from PodPresets?
  - In PodPresets, it's all or nothing - and with VMPresets we currently do a mix and match (or: VM dom has precendece has over Preset)
- Should limit presets to "stateless/infrastructure" (cpu, memory, clock, …) and "stateful/application" (disks, …) should not be touched?
- When is a preset applied? If all, some, or even none fields are applied?
- How to handle annotations if a preset matches a VM but is not fully applied. 
- How to order multplie matching presets?
- Can we reintroduce disks?
- How to unset certain values?
- Consider to rename annotations to "processed" instead of applied (in the current (v0.3.0) implementation)

**Comment by simon3z** [comment]
@fabiand are these all still currently open/standing? If any was closed/committed/finalized could strike it from the list?

**Comment by fabiand** [comment]
@stu-gott what's the status here.

Are the presets required to be orthorgonal today?

AKA Do they allow conflicts?
