### ISSUE TITLE
Update VM status when a VM dies or is shutdown

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#75]
virt-handler gets an event from libvirt whenever a Domain is shutdown or killed in [domain.go](https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-handler/domain.go).

If a Domain is shutdown, the VM should enter the phase `Succeeded`. If a VM crashed or was killed, it should enter the phase `Failed`. The field reflecting this is `VMSpec.Status.Phase`. In the watch loop we need to check for the [reason](https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainGetState) of the shutdown and update the Phase.

- [ ] Update the Phase on the VM via the restclient according to the shutdown reason.
- [ ] Write functional tests in `tests/vm_lifecycle.go`
- [ ] If a Domain is stopped or crahes, virt-handler should not try to restart it

**Comment by mpolednik** [comment]
Started working on this, PR coming asap.
