### ISSUE TITLE
VMI is auto tear down in a large vmirs.

### ISSUE THREAD

**Issue by wonleing** [kubevirt/kubevirt#7521]
**What happened**:
VMI is auto tear down and create in a large vmirs scale.

**What you expected to happen**:
vmi and Pod should be stable, no auto tear down and create

**How to reproduce it (as minimally and precisely as possible)**:
Run 200 replicas of vmirs, and keep watching vmi list and kubelet log
vmi and pod was deleted automatically, and then create a new one.

**Additional context**:
Kubelet log, during new pod is being created
![image](https://user-images.githubusercontent.com/105055/161893285-5b2b51a8-c68b-4e5f-8fee-7d32fcdaae4f.png)

**Environment**:
- KubeVirt version (use `virtctl version`): 0.45
- Kubernetes version (use `kubectl version`): 1.21.8
- Kernel (e.g. `uname -a`): 4.19

Any clue for this? Or any setting to prevent this tear down?

**Comment by wonleing** [comment]
I noticed there's a policy that "While meet Orphan Pod, kubelet will clean up it and its directorys (cleanupOrphanedPodDirs)"
seems kubernetes recognize vmi which is not used for a long time as 'orphaned pod'
Any method to prevent vmi not to be Orphan Pod? or disable this policy?

**Comment by wonleing** [comment]
![image](https://user-images.githubusercontent.com/105055/161895394-d3445c2c-4de4-4fbf-abb4-9ca11d5900d8.png)
looks like Eviction manager is doing this.
How to prevent this eviction?

**Comment by rmohr** [comment]
@wonleing maybe your node is under pressure? I don't think that this is related to kubevirt as such. Maybe some automatic node-updates are happening which are evicting workloads prior to that?

**Comment by rmohr** [comment]
Checking your snipped in detail it looks like the node runs out of ephemeral storage.

**Comment by rmohr** [comment]
Could you share your VMI definitions? It would be interesting to see which volumes on the VMI are consuming all the disk space. In case it is a EmptyDisk, you may want to set a capacity, so that explicit ephemeral storage is requested. That should stop the eviction manager from evicting the pod for as long as the usage is below the requested amount.

**Comment by wonleing** [comment]
under pressure? Yes. the upper case is disk is nearly full. Thanks for the hint.
but sometimes not disk pressure (different error). Maybe CPU or memory, since I often start hundreds of replicas at same time.
