### ISSUE TITLE
make failed with some error

### ISSUE THREAD

**Issue by shewensheng** [kubevirt/kubevirt#7526]
Hello all:
  I am new with kubevirt，I run make with main branch on my environment centos7.6, here is my step:
export DOCKER_PREFIX=10.188.188.22:5000
export DOCKER_TAG=sws0406
make

finally，make report error:
[root@k8s-1 kubevirt]# make
./hack/dockerized "hack/bazel-fmt.sh"
go version go1.17.5 linux/amd64

go version go1.17.5 linux/amd64
Regenerating sandbox
INFO: Build option --incompatible_enable_cc_toolchain_resolution has changed, discarding analysis cache.
INFO: Analyzed target //rpm:sandbox_x86_64 (263 packages loaded, 9644 targets configured).
INFO: Found 1 target...
INFO: From Converting sandboxroot_x86_64 to tar:
Flag shorthand -s has been deprecated, use --symlinks instead
Target //rpm:sandbox_x86_64 up-to-date:
  bazel-bin/rpm/sandbox_x86_64.bash
INFO: Elapsed time: 42.444s, Critical Path: 36.14s
INFO: 294 processes: 14 internal, 280 processwrapper-sandbox.
INFO: Build completed successfully, 294 total actions
INFO: Build completed successfully, 294 total actions
INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes.
INFO: Analyzed target //vendor/mvdan.cc/sh/v3/cmd/shfmt:shfmt (75 packages loaded, 8342 targets configured).
INFO: Found 1 target...
ERROR: <builtin>: BazelWorkspaceStatusAction stable-status.txt failed: Failed to determine workspace status: Process exited with status 1
ERROR: Sandbox is not up to date, please run 'hack/bootstrap.sh'
Target //vendor/mvdan.cc/sh/v3/cmd/shfmt:shfmt failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 2.046s, Critical Path: 0.13s
INFO: 5 processes: 5 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
make: *** [format] Error 1

Can anyone one help to to fix this problem?

**Comment by usrbinkat** [comment]
Does the problem still occur if you kill any images using [quay.io/kubevirt/builder](http://quay.io/kubevirt/builder), delete the image, and docker volume rm kubevirt
And try again?

**Comment by shewensheng** [comment]
> Does the problem still occur if you kill any images using [quay.io/kubevirt/builder](http://quay.io/kubevirt/builder), delete the image, and docker volume rm kubevirt And try again?

Thank you, I fix the problem with your suggest, but still make failed, now the error log is:

Waiting for it to complete...
Another command (pid=15) is running. Waiting for it to complete on the server (server_pid=19)...
INFO: Analyzed target //rpm:sandbox_x86_64 (258 packages loaded, 9580 targets configured).
INFO: Found 1 target...
ERROR: /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/external/com_github_sassoftware_go_rpmutils/BUILD.bazel:3:11: GoCompilePkg external/com_github_sassoftware_go_rpmutils/go-rpmutils.a [for host] failed: (Exit 1): builder failed: error executing command bazel-out/host/bin/external/go_sdk/builder compilepkg -sdk external/go_sdk -installsuffix linux_amd64 -tags selinux,selinux -src external/com_github_sassoftware_go_rpmutils/errors.go -src ... (remaining 47 argument(s) skipped)

Use --sandbox_debug to see verbose messages from the sandbox
compilepkg: missing strict dependencies:
        /root/.cache/bazel/_bazel_root/6f347497f91c9a385dcd9294645b76e0/sandbox/processwrapper-sandbox/3/execroot/kubevirt/external/com_github_sassoftware_go_rpmutils/uncompress.go: import of "github.com/klauspost/compress/zstd"
No dependencies were provided.
Check that imports in Go sources match importpath attributes in deps.
Target //rpm:sandbox_x86_64 failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 7.367s, Critical Path: 0.45s
INFO: 23 processes: 23 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
make: *** [format] Error 1

I find a log:go get: module [github.com/klauspost/compress@upgrade](http://github.com/klauspost/compress@upgrade) found (v1.15.1), but does not contain package [github.com/klauspost/compress/zstd](http://github.com/klauspost/compress/zstd):   is it cause the make failed?

**Comment by rmohr** [comment]
@shewensheng we use vendoring. It may be that you are doing changes which reference files which are not included in the vendor folders because they were not referenced before. What then typically happens is that in your UI everything looks great because it just resolved dependencies itself. That can normally be fixed by running `make deps-sync`. Bazel just tries to tell you that you are  referencing unknown dependencies (files).

**Comment by gitchong** [comment]
when I do make deps-sync, prompt me the same error

**Comment by rmohr** [comment]
Just a wild guess, but could it be that you are located in china and that some dependencies are blocked?

**Comment by xwz-ol** [comment]
> Hello all: I am new with kubevirt，I run make with main branch on my environment centos7.6, here is my step: export DOCKER_PREFIX=10.188.188.22:5000 export DOCKER_TAG=sws0406 make
> 
> finally，make report error: [root@k8s-1 kubevirt]# make ./hack/dockerized "hack/bazel-fmt.sh" go version go1.17.5 linux/amd64
> 
> go version go1.17.5 linux/amd64 Regenerating sandbox INFO: Build option --incompatible_enable_cc_toolchain_resolution has changed, discarding analysis cache. INFO: Analyzed target //rpm:sandbox_x86_64 (263 packages loaded, 9644 targets configured). INFO: Found 1 target... INFO: From Converting sandboxroot_x86_64 to tar: Flag shorthand -s has been deprecated, use --symlinks instead Target //rpm:sandbox_x86_64 up-to-date: bazel-bin/rpm/sandbox_x86_64.bash INFO: Elapsed time: 42.444s, Critical Path: 36.14s INFO: 294 processes: 14 internal, 280 processwrapper-sandbox. INFO: Build completed successfully, 294 total actions INFO: Build completed successfully, 294 total actions INFO: Starting clean (this may take a while). Consider using --async if the clean takes more than several minutes. INFO: Analyzed target //vendor/mvdan.cc/sh/v3/cmd/shfmt:shfmt (75 packages loaded, 8342 targets configured). INFO: Found 1 target... ERROR: : BazelWorkspaceStatusAction stable-status.txt failed: Failed to determine workspace status: Process exited with status 1 ERROR: Sandbox is not up to date, please run 'hack/bootstrap.sh' Target //vendor/mvdan.cc/sh/v3/cmd/shfmt:shfmt failed to build Use --verbose_failures to see the command lines of failed build steps. INFO: Elapsed time: 2.046s, Critical Path: 0.13s INFO: 5 processes: 5 internal. FAILED: Build did NOT complete successfully FAILED: Build did NOT complete successfully make: *** [format] Error 1
> 
> Can anyone one help to to fix this problem?

I have encountered the same problem, have you solved it?

**Comment by xwz-ol** [comment]
> > 最后，make report error： [root@k8s-1 kubevirt]# make ./hack/dockerized “hack/bazel-fmt.sh” go version go1.17.5 linux/amd64
> 
> 嘿，这个命令行调用看起来很奇怪。难道是你从字面上打字的？只需键入就足够了。`make ./hack/dockerized "hack/bazel-fmt.sh"``make`


I temporarily circumvented the problem by adding the following code in WORKACE, but I don't think this is a good method

```python
go_repository(
    name = "com_github_compress_zstd",
    commit = "3cfb088132fccad51a8acfb2d238db1fb56583fd",
    importpath = "github.com/klauspost/compress",
)
```



i

**Comment by rmohr** [comment]
I think updating your `main` branch should resolve that. You seem to be on an older state where we had this issue.

**Comment by xwz-ol** [comment]
Our project uses v0.48 branch, but I did not encounter this problem when compiling last Friday
