### ISSUE TITLE
Re-implement cloudinit tests

### ISSUE THREAD

**Issue by xpivarc** [kubevirt/kubevirt#7541]
**What happened**:
I was reviewing tests and I found it interesting we rely on timing in the case of cloudinit tests. What  I mean by this is that we connect to the console after we start the VMI and expect some early messages from boot process. This is not a reliable way to do this.

e.g buffer will overflow or timing issues can occur

**What you expected to happen**:
We connect to the console before the VMI starts.

**How to reproduce it (as minimally and precisely as possible)**:
You can run a few tests and wish to be lucky.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by rmohr** [comment]
I think we are finally in good shape to replace most of the console based tests with ssh. What do you think about this? Initially, years ago the main reason for the console based tests was that we did not have a solution for networking and the VMs did not have network connectivity, but we needed to avoid regressions.

**Comment by rmohr** [comment]
We basically just wait with a timeout that finally the ssh server is available and that the private key is accepted (which is the equivalent of successful cloud init runs).

**Comment by xpivarc** [comment]
/reopen
/remove-lifecycle rotten

>I think we are finally in good shape to replace most of the console based tests with ssh. What do you think about this?

I like the idea. This might be a good first issue

**Comment by jeffreyxie0615** [comment]
Hey! My partner and I are from UT Austin as part of their virtualization class, and we were wondering if it would be possible for us to tackle this issue.

**Comment by xpivarc** [comment]
Hi @jeffreyxie0615 ,
I see we have https://github.com/kubevirt/kubevirt/pull/9242 which will at least partially address this problem. Feel free to look around if you see any other leftovers.
