### ISSUE TITLE
Missing debug data after 12th test fails

### ISSUE THREAD

**Issue by xpivarc** [kubevirt/kubevirt#7542]
**What happened**:
I was reviewing test failures and I couldn't see any data for 12+ failed tests.

**What you expected to happen**:
I expect the debug data to be available.(To be honest, I didn't look if we intentionally cut this...)

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by rmohr** [comment]
> I expect the debug data to be available.(To be honest, I didn't look if we intentionally cut this...)

Yes we intentionally cut it. We collect quite some data and have limited storage budget. At some point it does not make too much sense to continue dumping everything per test. It is questionable if you get more insights when looking at the 20th failing tests in a row than when looking at the first ones. At least that was my rational for this decision. Maybe there are cases where it is useful?

**Comment by xpivarc** [comment]
> > I expect the debug data to be available.(To be honest, I didn't look if we intentionally cut this...)
> 
> Yes we intentionally cut it. We collect quite some data and have limited storage budget. At some point it does not make too much sense to continue dumping everything per test. It is questionable if you get more insights when looking at the 20th failing tests in a row than when looking at the first ones. At least that was my rational for this decision. Maybe there are cases where it is useful?

Thanks @rmohr ! I thought this is the case and I think its totatlly resonable this way. Maybe we could expose a option to increase the threashold but I will try to fight against it in the case where I saw this.
