### ISSUE TITLE
Issue when trying to association a GPU to a VMI

### ISSUE THREAD

**Issue by jbhfenris** [kubevirt/kubevirt#7547]
Hello,

I'm trying to associate an Nvidia Tesla T4 to a Kubevirt VMI but during the scheduling phase, I've got the following message : " Insufficient [nvidia.com/TU104GL_Tesla_T4](http://nvidia.com/TU104GL_Tesla_T4)"

I'm using Kubevirt 0.45
Kubevirt CR contains the following elements :
spec:
    permittedHostDevices:
      pciHostDevices:
      - pciVendorSelector: 10de:1eb8
        resourceName: [nvidia.com/TU104GL_Tesla_T4](http://nvidia.com/TU104GL_Tesla_T4)

The host where I want to deploy the VMI has been configured to manage PCI passthrough  for the T4 GPU :

5e:00.0 3D controller [0302]: NVIDIA Corporation TU104GL [Tesla T4] [10de:1eb8] (rev a1)
    Subsystem: NVIDIA Corporation TU104GL [Tesla T4] [10de:12a2]
    Flags: bus master, fast devsel, latency 0, IRQ 255, NUMA node 0
    Memory at bb000000 (32-bit, non-prefetchable) [size=16M]
    Memory at 38c000000000 (64-bit, prefetchable) [size=256M]
    Memory at 38c110000000 (64-bit, prefetchable) [size=32M]
    Capabilities: <access denied>
    Kernel driver in use: vfio-pci
    Kernel modules: nvidiafb, nouveau

The virtualmachine manifest contains in its spec.domain.devices the following elements :
devices:
            gpus:
            - deviceName: [nvidia.com/TU104GL_Tesla_T4](http://nvidia.com/TU104GL_Tesla_T4)
              name: gpu1

However when I look at the node description, no GPU appears on Capacity or Allocatable entries.

virt-handler pod has been restarted without success (logs attached)
`permittedHostDevices` entry from the KubeVirt CR has been removed and re-added without success

The discussion has started on kubevirt-dev Google Groups : https://groups.google.com/g/kubevirt-dev/c/RvGaAtV22mg

**Environment**:
- KubeVirt version (use `virtctl version`): Client Version: version.Info{GitVersion:"v0.45.0-gke.21", GitCommit:"010d2db44236c1b60eb2e525bd1053fa6bf3278e", GitTreeState:"clean", BuildDate:"2021-11-19T17:50:30Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
- Kubernetes version (use `kubectl version`): Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.5-gke.1200", GitCommit:"90a16981ade07f163a0233adb631b42ac1fc53ff", GitTreeState:"clean", BuildDate:"2021-10-04T09:27:33Z", GoVersion:"go1.16.7b7", Compiler:"gc", Platform:"linux/amd64"}
- OS (e.g. from /etc/os-release): buntu 20.04.4 LTS
- Kernel (e.g. `uname -a`): Linux hostg4 5.4.0-107-generic #121-Ubuntu SMP Thu Mar 24 16:04:27 UTC 2022 x86_64 x86_64 x86_64 GNU/Linux

[virt-handler log.txt](https://github.com/kubevirt/kubevirt/files/8462317/virt-handler.log.txt)

**Comment by xpivarc** [comment]
Hi @jbhfenris,
would you be able to increase the log verbosity and provide the log file again?

**Comment by jbhfenris** [comment]
> Hi @jbhfenris, would you be able to increase the log verbosity and provide the log file again?

Hi @xpivarc, how to activate an higher log level on virt-handler ?

**Comment by jbhfenris** [comment]
It has not effect 

The virt-handler log remain at verbosity 2: 
```
virt-handler {"component":"virt-handler","hostname":"hostg4","level":"info","pos":"virt-handler.go:198","timestamp":"2022-04-11T09:03:19.547422Z"}                             │
│ virt-handler W0411 09:03:19.548952 2006147 client_config.go:614] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.              │
│ virt-handler {"component":"virt-handler","level":"info","msg":"set verbosity to 2","pos":"virt-handler.go:455","timestamp":"2022-04-11T09:03:19.586679Z"}                        │
│ virt-handler {"component":"virt-handler","level":"info","msg":"set verbosity to 2","pos":"virt-handler.go:455","timestamp":"2022-04-11T09:03:19.586678Z"}
```

And in kubevirt object the config has been updated has proposed:
```spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates: []
      logVerbosity:
        virtHandler: 9
    permittedHostDevices:
      pciHostDevices:
      - pciVendorSelector: 10de:1eb8
        resourceName: nvidia.com/TU104GL_Tesla_T4
```

**Comment by alicefr** [comment]
In `virt-handler` log we don't have a device plugin for `nvidia.com/TU104GL_Tesla_T4](http://nvidia.com/TU104GL_Tesla_T4`. We should have a similar log message as for kvm device `Starting a device plugin for device: kvm"`. As already mentioned in kubevirt mailing list. I think it is due to an device plugin initialization issue. 

Do you have the chance to try with a more updated kubevirt version?
Just for confirmation, did you try to restart the virt-handler pod?

**Comment by jbhfenris** [comment]
I've try to restart virt-handler and the node itself but without success.
For the version, as the feature is embedded within Anthos platform (Kubevirt v0.45.0-gke.21) I do not have the hand on it.

**Comment by alicefr** [comment]
@jbhfenris  I tried to install KubeVirt v0.45.0 but for me, the device plugin initialization is working fine. Can you please verify that the GPU has been unbound and attach to vfio. Please, copy paste the output of the following commands `lspci -DD|grep NVIDIA`, `ls /sys/bus/pci/drivers/nvidia/`and `ls /sys/bus/pci/drivers/vfio-pci/` .

**Comment by jbhfenris** [comment]
@alicefr Here are the results of the commands:
`lspci -DD|grep NVIDIA` --> 0000:5e:00.0 3D controller: NVIDIA Corporation TU104GL [Tesla T4] (rev a1)
`ls /sys/bus/pci/drivers/nvidia/`--> ls: cannot access '/sys/bus/pci/drivers/nvidia/': No such file or directory
`ls /sys/bus/pci/drivers/vfio-pci/`--> 0000:5e:00.0  bind  module  new_id  remove_id  uevent  unbind

**Comment by vladikr** [comment]
Interesting.
From the looks of it, it seems to me that any changes to the kubevirt CR are simply not getting applied. 
@jbhfenris could you please check the existence of "kubevirt-config" configmap in your cluster?

**Comment by jbhfenris** [comment]
@vladikr yes there is a "kubevirt-config" configmap in the cluster.
Here is its content:
```
# Please edit the object below. Lines beginning with a '#' will be ignored,
# and an empty file will abort the edit. If an error occurs while saving this file will be
# reopened with the relevant failures.
#
apiVersion: v1
data:
  debug.useEmulation: "false"
  feature-gates: DataVolumes,CPUManager,ExperimentalIgnitionSupport,LiveMigration,CPUNodeDiscovery,HypervStrictCheck,Sidecar,GPU,HostDevices,Snapshot,HostDisk,ExperimentalVirtiofsSupport,Macvtap
kind: ConfigMap
metadata:
  creationTimestamp: "2022-04-08T07:55:23Z"
  name: kubevirt-config
  namespace: kubevirt
  resourceVersion: "1375138"
  uid: 96339d83-af58-42e6-8e9c-11f665303b9a
```

**Comment by jbhfenris** [comment]
Updating to Kubevirt v0.48.1-anthos1.11-gke.2 resolved the issue for me.
The updates on Kubevirt config is now applied correctly. I do a test by changing the log verbosity level and the modification appears automatically on the pod.
The GPU appears now on node capacity and allocatable sections

**Comment by fabiand** [comment]
@jbhfenris where did you find the guidance to use the config map in the first place?

**Comment by jbhfenris** [comment]
> @jbhfenris where did you find the guidance to use the config map in the first place?

I don't not use configmap at all, the config in kubevirt object was sufficient.The problem came from the v0.45.0-gke.21 version (exchange with Google support about it).
