### ISSUE TITLE
Most of the functional tests related to mediated devices are flaky

### ISSUE THREAD

**Issue by enp0s3** [kubevirt/kubevirt#7568]
**What happened**:
Most of the MDEV tests are flaky, more details in #7561 
This may affect the stability of our vGPU support, since most of the tests are quarantined

**What you expected to happen**:
Tests to become stable and make us confident that our releases support GPU in stable manner.

**Comment by enp0s3** [comment]
@xpivarc FYI

**Comment by xpivarc** [comment]
/remove-lifecycle rotten
Few improvements but we still are investing in this:
https://github.com/kubevirt/kubevirt/pull/8301
https://github.com/kubevirt/kubevirt/pull/8123
https://github.com/kubevirt/kubevirt/pull/7802
