### ISSUE TITLE
trying to understand the release cycles of kubevirt 

### ISSUE THREAD

**Issue by vasubabu** [kubevirt/kubevirt#7571]
We are planned to consume kubevirt for production workloads, infront of that, we just trying to understand the release cycle for kubevirt.  Can anybody help us by sharing any documents to understand the release cycles.

**Comment by fabiand** [comment]
Like https://github.com/kubevirt/kubevirt/blob/main/docs/release.md ?

**Comment by fabiand** [comment]
Please let us know if there is anything missing in this file.
