### ISSUE TITLE
FOSSA check failing due to vendored GPL 2.0 dependency from containerized-data-importer 

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#7573]
**What happened**:
A recent investigation of why the [FOSSA check started to fail](https://app.fossa.com/projects/custom%2B13072%2Fgit%40github.com%3Akubevirt%2Fkubevirt.git/refs/branch/main/a116c373d91069dd3750c84439d3e6f23451322d) in kubevirt/kubevirt suggested that the dependency containerized-data-importer in v1.42.0 introduced a [GPL 2.0 dependency](https://github.com/kubevirt/containerized-data-importer/blob/release-v1.42/vendor/github.com/mrnold/go-libnbd/aio_buffer.go#L5). This license was [also seen in v1.43.0](https://github.com/kubevirt/containerized-data-importer/blob/release-v1.43/vendor/github.com/mrnold/go-libnbd/aio_buffer.go#L5), but later versions don't show this dependency any more.

The issue appeared the first time with commit https://github.com/kubevirt/kubevirt/commit/110c61470840dba50f64aa61381f84848b9ce602 which first showed the FOSSA failure. But it was introduced with commit https://github.com/kubevirt/kubevirt/commit/90227f26c79dd9304e1ad63fa670628021fdc151

**What you expected to happen**:
FOSSA check should not fail due to license issues caused by GPL 2.0 dependency.

**How to reproduce it (as minimally and precisely as possible)**:
See https://github.com/kubevirt/kubevirt/#fossa-status

**Additional context**:
n/a

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by dhiller** [comment]
FYI @fossedihelm

**Comment by dhiller** [comment]
Not sure why it only started failing now as the dependency update was merged by end of January: https://github.com/kubevirt/kubevirt/pull/7056

**Comment by EdDev** [comment]
The production code is not suppose to depend on CDI AFAIK. Is this correct?

I am pretty sure the e2e tests do depend on it.

Anyway, this is a major incident and should be handled on CDI side. We can't do much about it from this end.

**Comment by akalenyu** [comment]
Still there IIUC
https://github.com/kubevirt/containerized-data-importer/blob/main/vendor/libguestfs.org/libnbd/aio_buffer.go#L5

**Comment by awels** [comment]
Didn't we around that time split the CDI API into its own separate repo, which would stop the import of the CDI dependencies and that is probably why this is no longer failing

**Comment by EdDev** [comment]
> It changed from GPL to LGPL. But I think it is in a gray area. Ref: https://www.apache.org/legal/resolved.html#category-x

We just need to make sure it is not vendored in, that is it. If the API dependency does not bring in that code, we should be fine.

**Comment by awels** [comment]
CDI is working on getting this sorted. libnbd is good to go according to fossa, and the cronexpr is dual licensed and includes apache 2.0. We are just dealing with runc and docker right now (runc seems to be flagged in kubevirt as well)
