### ISSUE TITLE
Conformace tests in air-gapped environments

### ISSUE THREAD

**Issue by betoredhat** [kubevirt/kubevirt#7598]
**Is your feature request related to a problem? Please describe**:
We are trying to run kubvirt conformance tests in Openshift via sonobuoy, during the VM images creation images like  [quay.io/kubevirt/cirros-container-disk-demo:v0.52.0](http://quay.io/kubevirt/cirros-container-disk-demo:v0.52.0) cannot be pulled on the cluster nodes. At this time I do no see how to override the registry address with the one from our internal registry. 

Configuring Image Content Source policies to point to our mirror is not working because the images quay.io/kubevirt/conformance:v0.52.0 are not been referenced by SHA. 

Is there other recommended option to run the tests in disconnected environments or any plans to add support in future?

**Describe the solution you'd like**:
* Allow to override the registry address of the images used in the /kubevirt/conformance or
* Enable support for disconnected environments via mirroring, that requires using references to images by digest. 

Thanks in advance

**Comment by rmohr** [comment]
That should work by setting `--plugin-env kubevirt-conformance.CONTAINER_PREFIX=` and `--plugin-env kubevirt-conformance.CONTAINER_TAG=` (if necessary). That should redirect all pull requests to your local registry.

**Comment by rmohr** [comment]
> Configuring Image Content Source policies to point to our mirror is not working because the images quay.io/kubevirt/conformance:v0.52.0 are not been referenced by SHA.

Could describe a little bit in detail how your mirror works? Why can't it see tags? We use digest for the actual production images in our operator. We don't do that for the testing images though, as you describe.

**Comment by betoredhat** [comment]
Hello @rmohr 

Yes, setting those env variables did the trick, thanks a lot. We were trying also with this image [index.docker.io/kubevirt/conformance:v0.34.0](http://index.docker.io/kubevirt/conformance:v0.34.0) but seems a bit old and did not support the override. We will stay with [v0.52.0](http://quay.io/kubevirt/cirros-container-disk-demo:v0.52.0)

We run it this way:
```
./sonobuoy run 
--sonobuoy-image registry:4443/sonobuoy/sonobuoy:v0.56.4
--wait 
--mode quick 
--skip-preflight 
--plugin-env kubevirt-conformance.CONTAINER_PREFIX=registry:4443/kubevirt 
--plugin-env kubevirt-conformance.CONTAINER_TAG=v0.52.0 --plugin kubevirt-conformance.yaml

kubevirt-conformance.yaml: 
sonobuoy-config:
  driver: Job
  plugin-name: kubevirt-conformance
  result-format: junit
spec:
  command:
  - /usr/bin/conformance
  image: registry:4443/kubevirt/conformance:v0.52.0
  name: plugin
  resources: {}
  volumeMounts:
  - mountPath: /tmp/results
    name: results
```

Regarding mirror, we use "skopeo" or "oc mirror" (for operator catalogs) to copy images to our local registry, after that we use image content source policies defining as a mirror our local registry. That works fine with your operator, all references to images are using digest. Before knowing about the env variables for sonobuoy I considered image content source policies as an alternative for the kubevirt images pulling from the nodes, but that is not the case with the information that you provided. 

Thanks again.
