### ISSUE TITLE
After I reinstall kubevirt,only virt-operator ,no virt-handler and no 

### ISSUE THREAD

**Issue by FireLv** [kubevirt/kubevirt#7613]
**What happened**:
After I reinstall kubevirt,only virt-operator,no virt-handler and no virt-controller and no virt-api

**What you expected to happen**:
After I resintall kubevirt, virt-operator、virt-handler 、virt-controller、 virt-api can shows out

**How to reproduce it (as minimally and precisely as possible)**:
I remove the kubevirt,and I reinstall it,this issue will be reproduced

**Additional context**:
First time,I install the latest version kubevirt,and then I know the latest version is not support k8s <1.19,so I choose kubevirt v0.42.2

I know the version of k8s is too old,but the k8s server is our prod server, it's to difficult to upgrade the version of k8s.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.42.2
- Kubernetes version (use `kubectl version`): v1.18.4
- VM or VMI specifications: win10
- Cloud provider or hardware configuration: hardware
- OS (e.g. from /etc/os-release): CentOS 
- Kernel (e.g. `uname -a`): 3.10.0-1160.36.2.
- Install tools: N/A
- Others: 
   The result of kubectl get all -n kubevirt:
```
NAME                                READY   STATUS    RESTARTS   AGE
pod/virt-operator-b767c8878-28qf6   1/1     Running   0          41h
pod/virt-operator-b767c8878-jpf56   1/1     Running   0          41h

NAME                                TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
service/kubevirt-operator-webhook   ClusterIP   10.110.18.238   <none>        443/TCP   41h

NAME                            READY   UP-TO-DATE   AVAILABLE   AGE
deployment.apps/virt-operator   2/2     2            2           41h

NAME                                      DESIRED   CURRENT   READY   AGE
replicaset.apps/virt-operator-b767c8878   2         2         2       41h

NAME                            AGE   PHASE
kubevirt.kubevirt.io/kubevirt   41h   
```

**Comment by FireLv** [comment]
Addtion infos:
remove steps :
```
$ kubectl delete -n kubevirt kubevirt kubevirt --wait=true # --wait=true should anyway be default
$ kubectl delete apiservices v1alpha3.subresources.kubevirt.io # this needs to be deleted to avoid stuck terminating namespaces
$ kubectl delete mutatingwebhookconfigurations virt-api-mutator # not blocking but would be left over
$ kubectl delete validatingwebhookconfigurations virt-api-validator # not blocking but would be left over
$ kubectl delete -f https://github.com/kubevirt/kubevirt/releases/download/v0.42.2/kubevirt-operator.yaml --wait=false
```

install steps:
```
$ kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/v0.42.2/kubevirt-operator.yaml
$ kubectl apply -f https://github.com/kubevirt/kubevirt/releases/download/v0.42.2/kubevirt-cr.yaml
```

Now,I want to remove again,when I exec "kubectl delete -n kubevirt kubevirt kubevirt --wait=true",it shows : 
**service 'kubevirt-operator-webhook.kubevirt.svc' not found**
And I get the operator service and  operator serviceaccount yaml files from other server(this server install after I get the right kubevirt version,and all pod is normal ),then I apply them.

I run "kubectl delete -n kubevirt kubevirt kubevirt --wait=true" again,it shows:
```
x509: certificate is valid for fallback, fallback.fallback, fallback.fallback.svc, fallback.fallback.svc.cluster.local, not kubevirt-operator-webhook.kubevirt.svc
```

**I know the reason is no secret of operator-webhook , but how to create the secret ?**

**Comment by yun-ling** [comment]
try use this command after reinstalling kubevirt 
`kubectl delete validatingwebhookconfigurations virt-operator-validator`
That's because everytime you reinstall kubevirt ,the virt-operator will regenerate private key and CA cert,which will be use to sign webhook cert.However ,webhook resource seems not to be cleaned up so  next time you install kubevirt the webhooks still use  old private key and CA cert

**Comment by yun-ling** [comment]
I met this bug many times and the solution works for me

**Comment by yun-ling** [comment]
In fact,ramdom self-signed CA cert causes many issues  for api-server and webhooks .There should be an entry for k8s administrator to manage kubevirt CA cert so that we can keep CA  cert and private key unchangeable

**Comment by FireLv** [comment]
@yun-ling 
Thanks so mush.It works for me too.
At least,I can remove kubevirt now.
I will reinstall kubevirt again

**Comment by FireLv** [comment]
@yun-ling  Sorry to bother you again

**Comment by FireLv** [comment]
@yun-ling  
Sorry to bother you again, after I resintall KubeVirt-CR, I can see the “kubevirt.kubevirt.io/kubevirt”  status is deploying, but I can't see the job ,and there are no virt-handler , no virt-controller and no virt-api pod and rs.
Did you met this issue?

**Comment by yun-ling** [comment]
You can check virt-operator logs via this command
`kubectl logs -f virt-operator-xxx - n kubevirt`
Replace "xxx" with your real pod name then you can see the error information.

**Comment by FireLv** [comment]
@yun-ling 
I checked my pod logs,and I found the reason is: 
# "customresourcedefinitions.apiextensions.k8s.io \"virtualmachineinstances.kubevirt.io\" already exists""
After I remove KubeVirt,I delete all crds for kubevirt,and I resintall KubeVirt,the job appears.

**Comment by yun-ling** [comment]
> @yun-ling I checked my pod logs,and I found the reason is:
> 
> # "customresourcedefinitions.apiextensions.k8s.io "virtualmachineinstances.kubevirt.io" already exists""
> After I remove KubeVirt,I delete all crds for kubevirt,and I resintall KubeVirt,the job appears.

Yes,most of deployment errors can be located via virt-operator logs

**Comment by FireLv** [comment]
CRDs, clusterroles and clusterrolebindings  of KubeVirt were deleted one after another, I finally saw the pods virt-handler 、virt-controller and virt-api.
@yun-ling Thank you so much.
