### ISSUE TITLE
Windows VM memory metric not right

### ISSUE THREAD

**Issue by Icedroid** [kubevirt/kubevirt#7633]
**What happened**:
Windows VM memory metric not right.
kubevirt_vmi_memory_resident_bytes  value is equal vm guest.memory, not real usage of windows vm.
kubevirt_vmi_memory_available_bytes metric is empty.

**What you expected to happen**:
How to get the real memory useage of windows vm

**How to reproduce it (as minimally and precisely as possible)**:
create a windows vm.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): 
v0.49
- Kubernetes version (use `kubectl version`): 
v1.18

**Comment by rootdeep** [comment]
you should install virtio-balloon driver for your windows vm.

**Comment by xpivarc** [comment]
Hi,
as @rootdeep pointed out, you need to install the driver. I am wondering if we documented this somewhere.
