### ISSUE TITLE
Update asciinema demo

### ISSUE THREAD

**Issue by jseguillon** [kubevirt/kubevirt#7652]
Hi, I just noticed the ascinema demo from README is now 5 years old and shows some outdated "VM.v1alpha1.kubevirt.io" Kind. 

I think this demo deserves to be updated with now v1 stable API.

**Comment by usrbinkat** [comment]
That's a great callout. Would you be willing to submit a PR with a new ascinema demo?

**Comment by jseguillon** [comment]
Hi there, 
Here is an updated demo: https://asciinema.org/a/496567 

At first, I hoped I could kubectl create some example coming straight from github but as spotted in #7781 this is not possible yet. 

Also I decided to demo `virctl ssh` because it's probably a basic feature people can be pleased to see it running before giving a try to KubeVirt.

If you have remarks, please tell me here before I open PR.

**Comment by xpivarc** [comment]
> Hi there, Here is an updated demo: https://asciinema.org/a/496567
> 
> At first, I hoped I could kubectl create some example coming straight from github but as spotted in #7781 this is not possible yet.
> 
> Also I decided to demo `virctl ssh` because it's probably a basic feature people can be pleased to see it running before giving a try to KubeVirt.
> 
> If you have remarks, please tell me here before I open PR.

Looks good. Maybe we can use better names for the file & VM.

**Comment by jseguillon** [comment]
Sure. What about calling them both `fedora` ?

**Comment by jseguillon** [comment]
Hi @xpivarc  I recorded this new one : https://asciinema.org/a/497168

Changes: name everything fedora plus use `more` instead of `cat` to view ful definition of VM

**Comment by xpivarc** [comment]
> Hi @xpivarc I recorded this new one : https://asciinema.org/a/497168
> 
> Changes: name everything fedora plus use `more` instead of `cat` to view ful definition of VM

Looks good to me! Thanks
