### ISSUE TITLE
pull-kubevirt-e2e-k8s-1.21-sig-performance failing to launch 100 VMIs within a 300 second timeout

### ISSUE THREAD

**Issue by lyarwood** [kubevirt/kubevirt#7658]
**What happened**:

We increased the overall job timeout to 1h30m in https://github.com/kubevirt/project-infra/pull/2059 and can now see we were hitting it because of slow tests, specifically the `Density test` that is timing out launching 100 VMs in 5 minutes only reaching ~88:

https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7554/pull-kubevirt-e2e-k8s-1.21-sig-performance/1519926879883104256/build-log.txt

``` 
1834 hack/perftests.sh
1835 Performance testing
1836 Preparing directory for artifacts
1837 ARTIFACTS  /logs/artifacts/performance
1838 TESTS_OUT_DIR  /home/prow/go/src/github.com/kubevirt/kubevirt/_out/tests
1839 Running Suite: Tests Suite - /home/prow/go/src/github.com/kubevirt/kubevirt/_out/tests
1840 ======================================================================================

[..]
52551   << End Captured GinkgoWriter Output
52552 
52553   Timed out after 300.004s.
52554   Expected
52555       <int>: 88
52556   to equal
52557       <int>: 100
52558   In [It] at: tests/performance/density.go:198
52559 ------------------------------
52560 SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS      SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS      SSSSSSSSSSSSSSSSSSSSSSSSSSSSSSSS
52561 Waiting for namespace kubevirt-test-default1 to be removed, this can take a while ...
52562 Waiting for namespace kubevirt-test-alternative1 to be removed, this can take a while ...
52563 Waiting for namespace kubevirt-test-operator1 to be removed, this can take a while ...
52564 
52565 JUnit report was created: /logs/artifacts/performance/junit.functest.xml
52566 
52567 
52568 Ran 1 of 1110 Specs in 3588.203 seconds
52569 FAIL! -- 0 Passed | 1 Failed | 3 Pending | 1106 Skipped
52570 --- FAIL: TestTests (3588.64s)
52571 FAIL
52572 
52573 Ginkgo ran 1 suite in 59m51.025894954s 
52574 
52575 Test Suite Failed
52576 make: *** [Makefile:92: perftest] Error 1
```
There are some additional examples listed overnight below:

https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.21-sig-performance

**What you expected to happen**:

The job to pass with the original 5 minutes timeout per batch of 100 VMIs.

**How to reproduce it (as minimally and precisely as possible)**:

https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.21-sig-performance

**Additional context**:

The last successful run was April 22nd and took only 31m57s. The next run was April 24th which failed and took 1h5m4s.

[1518163367217336320](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7432/pull-kubevirt-e2e-k8s-1.21-sig-performance/1518163367217336320)	#7432 ([f8915fb](https://github.com/kubevirt/kubevirt/pull/7432/commits/f8915fb7e2ad4e9fe5fdebd2dd632012a48ef2d9)) by [oshoval](https://github.com/oshoval)	
Apr 24 10:42:28
1h5m4s	FAILURE
[1517595724819206144](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7590/pull-kubevirt-e2e-k8s-1.21-sig-performance/1517595724819206144)	#7590 ([7c15697](https://github.com/kubevirt/kubevirt/pull/7590/commits/7c15697eb389656191efadc53b6c971015c9e4d5)) by [awels](https://github.com/awels)	
Apr 22 21:07:03
31m57s	SUCCESS

**Environment**:

https://prow.ci.kubevirt.io/prowjob?prowjob=c05ad493-c785-11ec-a46b-faba94130593

**Comment by lyarwood** [comment]
Ah ha! I noticed 12 of the VMIs were still scheduling, looking at the logs it's because of memory pressure on the test host :

https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/7554/pull-kubevirt-e2e-k8s-1.21-sig-performance/1519926879883104256/artifacts/performance/k8s-reporter/1_vmis.log

```        {
            "kind": "VirtualMachineInstance",
            "apiVersion": "kubevirt.io/v1alpha3",
            "metadata": {
                "name": "testvmi-28tch",
                "namespace": "kubevirt-test-default1",
                "uid": "3344389e-d53c-4596-88ee-b0890d1c3c14",
                "resourceVersion": "7483",
                "generation": 4,
                "creationTimestamp": "2022-04-29T06:59:36Z",
                "annotations": {
                    "kubevirt.io/latest-observed-api-version": "v1",
                    "kubevirt.io/storage-observed-api-version": "v1alpha3"
                },
[..]
            "status": {
                "conditions": [
                    {
                        "type": "Ready",
                        "status": "False",
                        "lastProbeTime": "2022-04-29T06:59:51Z",
                        "lastTransitionTime": "2022-04-29T06:59:51Z",
                        "reason": "GuestNotRunning",
                        "message": "Guest VM is not reported as running"
                    },
                    {
                        "type": "PodScheduled",
                        "status": "False",
                        "lastProbeTime": null,
                        "lastTransitionTime": "2022-04-29T06:59:46Z",
                        "reason": "Unschedulable",
                        "message": "0/4 nodes are available: 4 Insufficient memory."
                    }
                ],
[..]
```

**Comment by lyarwood** [comment]
And it's still not 100% stable with a few examples where a single VMI isn't able to schedule:

https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/pr-logs/directory/pull-kubevirt-e2e-k8s-1.21-sig-performance

I'm away on PTO until the 14th so someone might want to bump the resources one final time.

/cc xpivarc dhiller rthallisey

**Comment by rthallisey** [comment]
Still seeing 12 vmis with `Unschedulable` even after increasing kubevirt mem from 10G->12G and mem request from 48G->52Gi
