### ISSUE TITLE
Is there a way to run the macox system on kubevirt？

### ISSUE THREAD

**Issue by cszixin** [kubevirt/kubevirt#7679]
I want to run macox on kubevirt, how can do it?

**Comment by vasiliy-ul** [comment]
Seems that previously there were some attempts. You may take a look at https://github.com/kubevirt/kubevirt/issues/2763. The issue lists some prerequisites. Though I am not sure this is currently supported in KbeVirt.

**Comment by usrbinkat** [comment]
With #2763 shared for context, is there anything else we can answer, or would you be interested in helping to formally develop this capability?
