### ISSUE TITLE
Kubevirt VM limits require Namespace to be specified in the manifest when creating

### ISSUE THREAD

**Issue by rhrazdil** [kubevirt/kubevirt#7681]
**What happened**:

The following tests in tests/vmi_configuration_test.go:
- [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]with namespace memory limits lower than VMI required memory
- [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]with namespace cpu limits lower than VMI required cpu
- [rfe_id:140][crit:medium][vendor:cnv-qe@redhat.com][level:component]with namespace limits higher than VMI requests

Require metadata.namespace to be specified when a VM(I) is created, becuse the limits are applied/enforced in webhook.
The webhook needs to know the resource namespace in order to apply/enforce the namespace defaults.

This limitation of the feature became apparent in a PR that substitutes VMI creation with functions from libvmi, which do not specify the Namespace explicitly.
- https://github.com/kubevirt/kubevirt/pull/7545

**What you expected to happen**:
We should consider implementing the feature in a controller, instead of in a webhook, or document the limitation, if
we decide to keep it in webhook.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by xpivarc** [comment]
We need to make sure that we pass namespace here https://github.com/kubevirt/kubevirt/blob/a3aaf1ace40c44c9dafaf2c091851d5cdb829fd7/pkg/virt-api/webhooks/mutating-webhook/mutators/vmi-mutator.go#L82
The namespace can be obtained from the request.
