### ISSUE TITLE
Hotplug volumes incorrectly handles mutating `OnDefineDomain` callback

### ISSUE THREAD

**Issue by VirrageS** [kubevirt/kubevirt#7690]
**What happened**:
When VMI is started together with hook-sidecar that implements `OnDefineDomain` and which changes the specification of the `Disk`, in particular `Source.File` the hotplug volumes implementation seems to incorrectly handle that case.

Here is VMI spec:
```
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  name: vmi-name
spec:
  domain:
    devices:
      disks:
        - name: rootdisk
          disk:
            bus: virtio
      interfaces:
        - bridge: {}
          name: default
  networks:
    - name: default
      pod: {}
  volumes:
    - name: rootdisk
      persistentVolumeClaim:
        claimName: pvc-name
```

When this VMI is being handled by the `virt-launcher` for the first time it goes to https://github.com/kubevirt/kubevirt/blob/b25c30a9e2d9826e053f54c5bf5a7abe50caf3b1/pkg/virt-launcher/virtwrap/manager.go#L820 call. Then fails on https://github.com/kubevirt/kubevirt/blob/b25c30a9e2d9826e053f54c5bf5a7abe50caf3b1/pkg/virt-launcher/virtwrap/manager.go#L842 because the domain is not defined and finally gets to https://github.com/kubevirt/kubevirt/blob/b25c30a9e2d9826e053f54c5bf5a7abe50caf3b1/pkg/virt-launcher/virtwrap/manager.go#L851 which then calls `OnDefineDomain` callback for each sidecar. If then the sidecar changes the disk definition like so:
```
	bootDiskLocation = domainSpec.Devices.Disks[0].Source.File // Get default boot disk location.

	// Update boot disk name to be "tmp_disk.img" in domain xml
	dir := filepath.Dir(bootDiskLocation)
	bootDiskLocation = filepath.Join(dir, "tmp_disk.img")
	domainSpec.Devices.Disks[0].Source.File = bootDiskLocation
```
and sends the changed domain back then this piece of code https://github.com/kubevirt/kubevirt/blob/b25c30a9e2d9826e053f54c5bf5a7abe50caf3b1/pkg/virt-launcher/virtwrap/manager.go#L911-L945 seems to handle it incorrectly. It first detaches the disk (it was never attached in the first place) and then attaches it again. But since the name is the same attaching fails as the detaching may not finished yet. Following logs are present:
```
{"component":"virt-launcher","kind":"","level":"info","msg":"Detaching disk rootdisk, target vda","name":"vmi-januszm-wfl8p-0","namespace":"default","pos":"manager.go:948","timestamp":"2022-04-29T15:14:36.662766Z","uid":"6898cd9d-54e6-43d1-b70c-355fe7dbfd1c"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Attaching disk rootdisk, target vda","name":"vmi-januszm-wfl8p-0","namespace":"default","pos":"manager.go:969","timestamp":"2022-04-29T15:14:41.749287Z","uid":"6898cd9d-54e6-43d1-b70c-355fe7dbfd1c"}
{"component":"virt-launcher","level":"error","msg":"unsupported configuration: non unique alias detected: ua-rootdisk","pos":"virDomainDeviceValidateAliasImpl:1294","subcomponent":"libvirt","thread":"31","timestamp":"2022-04-29T15:14:41.749000Z"}
{"component":"virt-launcher","kind":"","level":"error","msg":"attaching device","name":"vmi-januszm-wfl8p-0","namespace":"default","pos":"manager.go:977","reason":"virError(Code=67, Domain=20, Message='unsupported configuration: non unique alias detected: ua-rootdisk')","timestamp":"2022-04-29T15:14:41.749680Z","uid":"6898cd9d-54e6-43d1-b70c-355fe7dbfd1c"}
```

I think this particular case was missed and it hasn't been included in tests.

**What you expected to happen**: Hotplug should work without errors when `OnDefineDomain` callback changes the source file of the disk.

**How to reproduce it (as minimally and precisely as possible)**: Run aforementioned VMI with `OnDefineDomain` callback which mutates the `.Source.File`.

**Additional context**: None

**Environment**:
- KubeVirt version (use `virtctl version`): v0.50.0
- Kubernetes version (use `kubectl version`): v1.23.0
- VM or VMI specifications: Posted above
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by awels** [comment]
Very interesting. I didn't take side cars that mutate the file(or dev) part of the disk into account, when I wrote that code. I think the cleanest way to fix this is to somehow detect if the domain is running before attempting to run the detach or attach disks code that is causing the problem. This way we know the callback is done before we attempt to run the hotplug logic in any way.

**Comment by VirrageS** [comment]
> somehow detect if the domain is running

I think that the domain is actually running before we perform the `DetachDevice`.

---

I've been looking at the `DetachDevice` and `AttachDevice` documentation and then back at the KubeVirt code. And I think that after all the hotplug code should work, even with this weird case. But I think the bug might be somewhere else.

Notice that in the `DetachDevice` documentation there is such paragraf (https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainDetachDeviceFlags):
> Beware that depending on the hypervisor and device type, detaching a device from a running domain may be asynchronous. That is, calling [virDomainDetachDeviceFlags](https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainDetachDeviceFlags) may just request device removal while the device is actually removed later (in cooperation with a guest OS). Previously, this fact was ignored and the device could have been removed from domain configuration before it was actually removed by the hypervisor causing various failures on subsequent operations. To check whether the device was successfully removed, either recheck domain configuration using [virDomainGetXMLDesc](https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainGetXMLDesc)() or add a handler for the [VIR_DOMAIN_EVENT_ID_DEVICE_REMOVED](https://libvirt.org/html/libvirt-libvirt-domain.html#VIR_DOMAIN_EVENT_ID_DEVICE_REMOVED) event. In case the device is already gone when [virDomainDetachDeviceFlags](https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainDetachDeviceFlags) returns, the event is delivered before this API call ends. To help existing clients work better in most cases, this API will try to transform an asynchronous device removal that finishes shortly after the request into a synchronous removal. In other words, this API may wait a bit for the removal to complete in case it was not synchronous.

So this means that we should either check for the detached device or even register a callback that would inform us about this. And since we don't do that, the `AttachDevice` fails because the device hasn't been removed.

Also not sure if we are attaching/detaching devices with correct flags. Simply doing `DetachDevice` only affects active domain:
> This is an equivalent of [virDomainDetachDeviceFlags](https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainDetachDeviceFlags)() when called with flags parameter set to [VIR_DOMAIN_AFFECT_LIVE](https://libvirt.org/html/libvirt-libvirt-domain.html#VIR_DOMAIN_AFFECT_LIVE).
same goes for `AttachDevice`. I'm not sure what is exactly live domain and persistent domain state, but I feel like we should update both - please correct me if I'm wrong.

**Comment by awels** [comment]
Hey, been digging into hotplug code today, and this might be helpful. In the converter context, we generate a map of 'permanent' volumes from the VMI volume status fields. We can probably use this information in attach/detach to ignore disks that we want to detach if are in that permanent list. This should make it really easy to detect ones we really want to detach/attach

**Comment by VirrageS** [comment]
@saiprashanth173 was working on the patch to simply ignore detach/attach in the `SyncVMI` if the domain is yet defined.  But what you proposed looks also interesting.
