### ISSUE TITLE
Installation does not create CRD

### ISSUE THREAD

**Issue by digiserg** [kubevirt/kubevirt#7693]
**What happened**:
This is the first time I install kubevirt. I followed the [docs](https://kubevirt.io/quickstart_cloud/) on how to install it and tried creating a VM but it did not work.

**What you expected to happen**:
```
error: unable to recognize "vm.yaml": no matches for kind "VirtualMachineInstance" in version "kubevirt.io/v1"
```

**How to reproduce it (as minimally and precisely as possible)**:
Just install it on a brand new Kube cluster.

**Additional context**:

```sh
~$ k get crd | grep kubev
kubevirts.kubevirt.io                                 2022-05-05T11:23:41Z
```

I went back several versions to `0.3x.x` and I've got instead 

```
migrationpolicies.migrations.kubevirt.io              2022-05-05T14:26:27Z
virtualmachineclusterflavors.flavor.kubevirt.io       2022-05-05T14:26:27Z
virtualmachineflavors.flavor.kubevirt.io              2022-05-05T14:26:27Z
virtualmachineinstancemigrations.kubevirt.io          2022-05-05T14:18:18Z
virtualmachineinstancepresets.kubevirt.io             2022-05-05T14:18:18Z
virtualmachineinstancereplicasets.kubevirt.io         2022-05-05T14:18:18Z
virtualmachineinstances.kubevirt.io                   2022-05-05T14:18:18Z
virtualmachinepools.pool.kubevirt.io                  2022-05-05T14:26:27Z
virtualmachinerestores.snapshot.kubevirt.io           2022-05-05T14:18:18Z
virtualmachines.kubevirt.io                           2022-05-05T14:18:18Z
virtualmachinesnapshotcontents.snapshot.kubevirt.io   2022-05-05T14:18:18Z
virtualmachinesnapshots.snapshot.kubevirt.io          2022-05-05T14:18:18Z
```

and managed to create a VM successfully.

Either docs are very out of date and the CRD has changed or it's not being released properly.

**Environment**: on-premises kube
- KubeVirt version (use `virtctl version`): 0.52.0 (probably a lot more versions)
- Kubernetes version (use `kubectl version`): v1.19.x
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by xpivarc** [comment]
Hi @digiserg ,
Did you verify components? `kubectl get all -n kubevirt`

**Comment by digiserg** [comment]
> Hi @digiserg , Did you verify components? `kubectl get all -n kubevirt`

Yes, I did. I have deleted the namespace and tried again and on my third attempt, it did actually work. I'm running now v0.51.0

Not sure why it didn't work initially but I'm closing the ticket for now. Thanks.
