### ISSUE TITLE
Flaky - Migration tests using disableNodeLabeller

### ISSUE THREAD

**Issue by xpivarc** [kubevirt/kubevirt#7703]
Function[ `disableNodeLabeller`]( https://github.com/kubevirt/kubevirt/blob/main/tests/migration_test.go#L3972) should use patch instead of `Update` or be implemented with `Eventually` because it might get updated.

**How to reproduce it (as minimally and precisely as possible)**:
Run `[test_id:7505]when no node is suited for host model` multiple times while making coffee/tea.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by xpivarc** [comment]
@iholder-redhat  Do you want to take this one?

**Comment by iholder-redhat** [comment]
> @iholder-redhat Do you want to take this one?

Sure, I'm on it. Thanks for bringing it to my attention.
/assign @iholder-redhat

**Comment by iholder-redhat** [comment]
PR: https://github.com/kubevirt/kubevirt/pull/7711

**Comment by iholder-redhat** [comment]
PR is merged, I guess we can close this one? @xpivarc

**Comment by xpivarc** [comment]
Please check flakefinder before closing just to be sure.

**Comment by iholder-redhat** [comment]
Test isn't shown on flake finder nor on search.ci.kubevirt.io/. I think it's safe to close.
/close
