### ISSUE TITLE
Enable GDB port

### ISSUE THREAD

**Issue by ahussey-redhat** [kubevirt/kubevirt#7714]
**Is your feature request related to a problem? Please describe**:
Currently in order to attach GDB to a VM the options are; nested virtualization (first VM with KVM installed, sub VM with GDB port exposed, first VM attaches to GDB port of sub VM), or a sidecar container.

**Describe the solution you'd like**:
Enable exposing the GDB port of a VM using annotations.
One annotation to enabled exposing of the GDB port, and a second optional annotation which specifies the port to use.

EG
```yaml
gdb.vm.kubevirt.io/GDBEnabled=true
gdb.vm.kubevirt.io/GDBPort=1235
```

**Describe alternatives you've considered**:
1. sidecar container which uses hooks to modify the domain xml.
2. nested virtualization

**Additional context**:
There are multiple methods to enable exposing GDB, the `-s` flag could be passed through the `virt-launcher`, which exposes GDB on the default port `1234`.
GDB can also be enabled by manipulating the domain xml by adding `qemu:commandline`. This option is more configurable as you can specify the port number.
```xml
  <qemu:commandline>
        <qemu:arg value='-gdb'/>
        <qemu:arg value='tcp::1235'/>
  </qemu:commandline>
```

https://www.kernel.org/doc/html/v4.11/dev-tools/gdb-kernel-debugging.html
https://qemu-project.gitlab.io/qemu/system/gdb.html
https://www.redhat.com/en/blog/debugging-kernel-qemulibvirt

**Comment by ahussey-redhat** [comment]
Added to mailing list https://groups.google.com/g/kubevirt-dev/c/kzDrNo0IYMU

**Comment by maiqueb** [comment]
I tend to favor your second proposed approach (manipulating the VM's dom xml) given its advantages.

I see value in this enhancement proposal.

**Comment by ahussey-redhat** [comment]
This feature request is being monitored downstream.
Unsure if it needs to remain open here or not

**Comment by ahussey-redhat** [comment]
This is also being tracked by https://access.redhat.com/support/cases/#/case/03255000

**Comment by ahussey-redhat** [comment]
Here is the downstream epic https://issues.redhat.com/browse/CNV-19887

**Comment by victortoso** [comment]
Hi, didn't see this ticket open otherwise I'd have added a reference to it at https://github.com/kubevirt/kubevirt/pull/9166
I've basically added `-s` to QEMU command line to test gdb. Adding `-s -S` also works fine. It is documented in the README of that sidecar.

**Comment by ahussey-redhat** [comment]
No worries. It is a fairly old ticket 🙂
