### ISSUE TITLE
Create functional test for template examples

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#772]
With #768 a few template examples got merged. We should add tests for those.

Depends somewhat on #771

**Comment by fabiand** [comment]
This is pretty large but quite isolated, thus maybe a good starting point for a contributor.

**Comment by dyasny** [comment]
@fabiand any idea where to look at examples of similar tasks fulfilled?

**Comment by cynepco3hahue** [comment]
I think Gabriel works on something similar.

**Comment by dyasny** [comment]
@cynepco3hahue just wanted to see where and how in the codebase one would tackle this, as I'm only starting with this stuff

**Comment by fabiand** [comment]
Done: https://travis-ci.com/kubevirt/common-templates/

/close
