### ISSUE TITLE
Missing documentation for new vm snapshot recording rules

### ISSUE THREAD

**Issue by sradco** [kubevirt/kubevirt#7720]
**Description**:
In PR #7533, new recording roles were added, but they are missing from the documentation here https://github.com/kubevirt/kubevirt/blob/main/docs/metrics.md

**What you expected**:
The new recording rules should be added to https://github.com/kubevirt/kubevirt/blob/main/docs/metrics.md.

**URL**:
They should be added to https://github.com/kubevirt/kubevirt/blob/main/docs/metrics.md

**Additional context**:
Add any other context about the issue here.

CC @akalenyu 

Bug-Url: https://bugzilla.redhat.com/show_bug.cgi?id=2143165

**Comment by akalenyu** [comment]
I see we have `tools/doc-generator/doc-generator.go` which was supposed to pick up the newly added metrics, so something must have gone wrong?

**Comment by sradco** [comment]
@akalenyu, I raised this issue now with @machadovilaca. I believe that the tool doesn't check the recording rules, they were added manually.
I believe we should add them also to the test, since the developer shouldn't be expected to remember to add them to the docs.

**Comment by akalenyu** [comment]
> @akalenyu, I raised this issue now with @machadovilaca. I believe that the tool doesn't check the recording rules, they were added manually. I believe we should add them also to the test, since the developer shouldn't be expected to remember to add them to the docs.

do you mean to `make generate`?

**Comment by sradco** [comment]
@akalenyu yes. the make generate. Its running the docs-generator.

**Comment by sradco** [comment]
@machadovilaca Hi, What is the status of this ?
