### ISSUE TITLE
Introduce a Go linter

### ISSUE THREAD

**Issue by acardace** [kubevirt/kubevirt#7727]
The idea is to use a Golang linter that would run on each opened PR for KubeVirt and would post results suggesting changes to improve the code.

Ideally, the linter should be easy to run and use on anyone's workstation.

One candidate might be https://github.com/golangci/golangci-lint.

**Comment by VirrageS** [comment]
I totally support this. There are number of benefits of using linter (especially the mentioned `golangci-lint`):
* Can catch performance issues
* Can catch simple/yet easy to miss bugs - for example variable shadowing, unused variables etc.
* Can improve code style and standardize it across the codebase
* Can restrict usage of specific packages or versions to prevent reintroducing security/logic bugs

`golangci-lint` can be introduce very slowly. There exists `--new` or `--new-from-rev` flag (https://golangci-lint.run/usage/configuration/#command-line-options) which can help with integration by only showing issues introduced in recent commits. Also, we could disable all linters initially and then gradually add them when needed and improve code with each new linter.

I feel like there are a lot of issues/bugs which we could avoid just by running more linters than simple `go fmt`.

**Comment by iholder-redhat** [comment]
Sounds like a blessed goal to me!

IMHO the ability to `make lint` locally is a must-have. This PR is a good start: https://github.com/kubevirt/kubevirt/pull/7804

**Comment by codingben** [comment]
Do you want to use GitHub Actions [1] for it? It's important to give the user instant feedback instead of waiting for a KubeVirt member to comment "ok-to-test" (or will you configure to run that Go linter without having "ok-to-test" comment?).

[1] https://github.com/golangci/golangci-lint-action

**Comment by iholder-redhat** [comment]
> Do you want to use GitHub Actions [1] for it? It's important to give the user instant feedback instead of waiting for a KubeVirt member to comment "ok-to-test" (or will you configure to run that Go linter without having "ok-to-test" comment?).
> 
> [1] https://github.com/golangci/golangci-lint-action
> 
> P.S. I absolutely agree with @VirrageS. It's a basic feature for every project (especially for big project such as KubeVirt).

@dhiller what are your thoughts on github actions?
