### ISSUE TITLE
Update Preset unit-tests in order to align with coding best practice

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#773]
The preset unit-tests need an update, see https://github.com/kubevirt/kubevirt/pull/652#pullrequestreview-99638237

**Comment by fabiand** [comment]
@stu-gott what's the status of this issue?

**Comment by stu-gott** [comment]
@rmohr You mentioned that the VM Preset Unit tests were written "the old way". What specifically is your concern?

**Comment by rmohr** [comment]
> @rmohr You mentioned that the VM Preset Unit tests were written "the old way". What specifically is your concern?

better to keep the tests in a consistent style to make improvements faster. We are not using the ghttp based approach anymore. We have  mocked worker queues which allow "relatively" easy testing of complex scenarios.
