### ISSUE TITLE
Velero Backups fails when no qemu guest agent is running on VM

### ISSUE THREAD

**Issue by QcFe** [kubevirt/kubevirt#7750]
**What happened**:
Velero backups fail partially because of kubevirt when there are VMIs which are not running the qemu guest agent: the Velero pre/post hooks that are set as annotations to the virt-launcher pods try to run the virt-freezer utility, which however fails because no qemu-guest-agent is running inside the VM. As a result, the backup for such resource fails. 

**What you expected to happen**:
The annotation should not be set to virt-launcher pods automatically so that backups can not fail because of kubevirt.
In general, a configurable behavior (for example an annotation on the vmi) could be more desirable.

**How to reproduce it (as minimally and precisely as possible)**:
Create a VMI with no qemu-guest-agent running on the guest OS, then start a velero backup for the vmi resource.

**Additional context**:
PVCs for such VMIs are not set to be backed up by Velero so there should be no need to freeze the VM.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.52.0
- Kubernetes version (use `kubectl version`): v1.23.6
- VM or VMI specifications: no qemu-guest-agent 
- Cloud provider or hardware configuration: bare metal
- OS (e.g. from /etc/os-release): Ubuntu 20.04.4
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by alicefr** [comment]
cc @brybacki

**Comment by brybacki** [comment]
That is right, we should change the behavior so it does not fail without guest agent. Then it can work with or without guest agent. Without guest agent it is best effort, so we cannot guarantee filesystem consistency. 

I think there are at least two solutions to that:
1. Do not return error from virt-freeze hook (so it will continue)
2. Make the hook configurable as you say @QcFe

**Comment by mhenriks** [comment]
> That is right, we should change the behavior so it does not fail without guest agent. Then it can work with or without guest agent. Without guest agent it is best effort, so we cannot guarantee filesystem consistency.
> 
> I think there are at least two solutions to that:
> 
> 1. Do not return error from virt-freeze hook (so the backup will continue, and can be marked as Success)
> 2. Make the hook configurable as you say @QcFe

I think option 1 is preferable in order to eliminate race conditions with virt-controller adding/removing annotations from the virt-launcher pod when guest agent goes offline

**Comment by QcFe** [comment]
Is there any update relatively to this? 😬

**Comment by Shea-D** [comment]
Can VMs be backed up with velero? I'm using velero and restic repository to backup, but partially failed with virt-launcher pod. After restoring from this backup, the VM's DVs were empty. But with the environment I can backup and restore pods with volumes.

**Comment by brybacki** [comment]
> Can VMs be backed up with velero? I'm using velero and restic repository to backup, but partially failed with virt-launcher pod. After restoring from this backup, the VM's DVs were empty. But with the environment I can backup and restore pods with volumes.

 @Shea-D  Yes VMs can be backed up with velero. this plugin helps with some edge cases. Please open a new Issue and describe your setup. CDI/KUBEVIRT version, velero version, restic or csi. That way we can check what is wrong.

**Comment by brybacki** [comment]
Regarding the original issue about the guest agent, the fix https://github.com/kubevirt/kubevirt/pull/8217 was merged and is available in kubevirt versions v0.57.0 and newer.

**Comment by Shea-D** [comment]
> > Can VMs be backed up with velero? I'm using velero and restic repository to backup, but partially failed with virt-launcher pod. After restoring from this backup, the VM's DVs were empty. But with the environment I can backup and restore pods with volumes.
> 
> @Shea-D Yes VMs can be backed up with velero. this plugin helps with some edge cases. Please open a new Issue and describe your setup. CDI/KUBEVIRT version, velero version, restic or csi. That way we can check what is wrong.

thanks for replying! I created a new issue, Is there anything else I need to provide?
