### ISSUE TITLE
virt-handler unknown flag: --maxDevices

### ISSUE THREAD

**Issue by yuntianfeijing** [kubevirt/kubevirt#7751]
**What happened**:
virt-handler unknown flag: --maxDevices when I set CR kubevirt  Configuration VirtualMachineInstancesPerNode

**What you expected to happen**:
when I set CR kubevirt  Configuration VirtualMachineInstancesPerNode, virt-handler not work, unknown flag: --maxDevices
virt-handler param --max_devices

**How to reproduce it (as minimally and precisely as possible)**:
when I set CR kubevirt  Configuration VirtualMachineInstancesPerNode, virt-handler not work, unknown flag: --maxDevices
virt-handler param --max_devices

**Additional context**:
pkg/virt-operator/resource/apply/apps.go
func setMaxDevices  should add  --max_devices ds virt-operator Container Command

**Environment**:
- KubeVirt version (use `virtctl version`):  v0.5x
- Kubernetes version (use `kubectl version`): v1.21.8
- VM or VMI specifications: N
- Cloud provider or hardware configuration: N
- OS (e.g. from /etc/os-release): centos7.9
- Kernel (e.g. `uname -a`): N
- Install tools:  virt-operator
- Others: N

**Comment by dhiller** [comment]
@kvaps do you want to have a look at this? Thanks!

**Comment by xpivarc** [comment]
Ref: https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-operator/resource/apply/apps.go#L331
The correct one is --max-devices
Also, let's add a functional test for this.
