### ISSUE TITLE
Verbose Flag does not affect virtctl console

### ISSUE THREAD

**Issue by tanaypatankar** [kubevirt/kubevirt#7756]
**What happened**:
I wanted to get verbose logging of virtctl console so that I could see the URL and headers it is creating but verbose logging does not work. Adding -v flag also does not enable verbose output for any level.

	ubuntu@tanay-kv-test-4:~$ kubectl virt console testvm -v 8
	Successfully connected to testvm console. The escape sequence is ^]

	$ 

**What you expected to happen**:
The verbose log output of virtctl console. Expected logs like those that are shown when you run `kubectl get pods -v 8`

	ubuntu@tanay-kv-test-4:~$ kubectl virt console testvm -v 8
	<Expected some logs here>
	Successfully connected to testvm console. The escape sequence is ^]

**How to reproduce it (as minimally and precisely as possible)**:
Run virtctl console with the verbose flag, -v 8.

**Additional context**:
NA

**Environment**:
- KubeVirt version (use `virtctl version`): 

		ubuntu@tanay-kv-test-4:~$ kubectl virt version
		Client Version: version.Info{GitVersion:"v0.53.0", GitCommit:"1f95d8c546c476b6120ecc25c43dac4a4c1f7011", GitTreeState:"clean", BuildDate:"2022-05-09T14:10:03Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
		Server Version: version.Info{GitVersion:"v0.45.0-dirty", GitCommit:"c9e87c4cb6292af33ccad8faa5fb9bf269c0fbf4", GitTreeState:"dirty", BuildDate:"2021-09-08T14:30:14Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`): 

		ubuntu@tanay-kv-test-4:~$ kubectl version
		Client Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T21:04:39Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
		Server Version: version.Info{Major:"1", Minor:"21", GitVersion:"v1.21.3", GitCommit:"ca643a4d1f7bfe34773c74f79527be4afd95bf39", GitTreeState:"clean", BuildDate:"2021-07-15T20:59:07Z", GoVersion:"go1.16.6", Compiler:"gc", Platform:"linux/amd64"}
- VM or VMI specifications: 
 
		apiVersion: kubevirt.io/v1
		kind: VirtualMachine
		metadata:
		  name: testvm
		spec:
		  running: true
		  template:
		    metadata:
		      labels:
		        kubevirt.io/size: small
		        kubevirt.io/domain: testvm
		    spec:
		      domain:
		        devices:
		          disks:
		            - name: containerdisk
		              disk:
		                bus: virtio
		            - name: cloudinitdisk
		              disk:
		                bus: virtio
		          interfaces:
		          - name: default
		            masquerade: {}
		        resources:
		          requests:
		            memory: 64M
		      networks:
		      - name: default
		        pod: {}
		      volumes:
		        - name: containerdisk
		          containerDisk:
		            image: quay.io/kubevirt/cirros-container-disk-demo
		        - name: cloudinitdisk
		          cloudInitNoCloud:
		            userDataBase64: SGkuXG4=

- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Ubuntu 18.04.2 LTS 
- Kernel (e.g. `uname -a`): 

		Linux tanay-kv-test-4 4.15.0-51-generic #55-Ubuntu SMP Wed May 15 14:27:21 UTC 2019 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: N/A
- Others: N/A

**Comment by dhiller** [comment]
/triage accepted
/kind enhancement


This could be useful for debugging. Also this could be a good first issue.

**Comment by tanaypatankar** [comment]
> @tanaypatankar, there is a reason you are not seeing any logs in this case. `kubectl` commands are requests against the k8s API, while `virtctl console <vm>` (equivalent of `kubectl virt console <vm>`) is done through channels(pipes), so there no URLs or headers. Is there any particular use case where you need the mentioned logs so I could provide a different solution?

From what I tracked, it calls [https://github.com/kubevirt/kubevirt/blob/main/staging/src/kubevirt.io/client-go/kubecli/async.go#L48](url) this, which is a websocket API call.
