### ISSUE TITLE
Add support for s390x architecture (IBM Z)

### ISSUE THREAD

**Issue by ikandars** [kubevirt/kubevirt#7774]
**Is your feature request related to a problem? Please describe**:
I just try to deploy KubeVirt in Linux One machine but the virt-operator pod fail to run with error message Back-off restarting failed container

**Describe the solution you'd like**:
Base on this discussion, https://kubernetes.slack.com/archives/C8ED7RKFE/p1651707300604989 it seems that KubeVirt doesn't support s390x as yet. Since KVM/Libvirt,  Kubernetes, Containerd, Calico and some other KubeVirt ecosystem already support for s390x machine, it seems it would be great if KubeVirt too.

**Comment by alicefr** [comment]
hi @ikandars, we are generally open to supporting different architectures if there are people willing to help. Do you plan to invest some time on this? It will also be an excellent topic for our community meeting on Wednesday. 

fyi @hbrueckner @borntraeger

**Comment by ikandars** [comment]
@alicefr yes

**Comment by fabiand** [comment]
And just a small disclaimer, an incomplete list of requirements:

1. Maintained cluster for CI and build
2. Maintained infrastructure
3. Capacity to resolve bugs
4. Clarifications with the libvirt/qemu maintainers to ensure we get their support as well
5. At least a single point of contact for any of the above

**Comment by alicefr** [comment]
On top of what Fabian said. 

- KubeVirt images are based on centos stream 8, so you need to verify the support for centos-stream on Z. There wasn't support for Z for centos for example.
- KubeVirt CI is using prow. So, you need to check the support and integration of Z node in prow
