### ISSUE TITLE
extend the dhcpv6 server to support bridge binding

### ISSUE THREAD

**Issue by lynn901** [kubevirt/kubevirt#7775]
**Is your feature request related to a problem? Please describe**:
the bridge type interface does not  support obtaining ipv6 addr throgh dhcpv6 server.

**Describe the solution you'd like**:
In order to achieve this function, we need to solve the following three problems:

1. Get the ipv6 address of the pod of vmi in bridge mode
2. Get the ipv6 gateway of the pod of vmi in bridge mode
3. Extend the dhcpv6 server to support bridge binding

**Describe alternatives you've considered**:

we can filter out non-vm requests by the link-layer address of client indentifier 

**Additional context**:
![image](https://user-images.githubusercontent.com/11764870/169188723-1e7e59ef-b0c7-4fec-9ee3-cf426c8f3740.png)

**Comment by AsGreyWolf** [comment]
Bump
