### ISSUE TITLE
Use quay.io/kubevirt images in examples

### ISSUE THREAD

**Issue by jseguillon** [kubevirt/kubevirt#7781]
**Description**:
examples yaml files refers to a local image registry. When container-disk is available as quay.io/kubevirt,  image should be replaced to ease new users experience. 

Example with [fedora](https://github.com/kubevirt/kubevirt/blob/main/examples/vmi-fedora.yaml#L24) which probably could point to: quay.io/kubevirt/fedora-cloud-container-disk-demo:v0.44.1

Probably the same for alpine and any other online available images.

**Comment by vasiliy-ul** [comment]
I think the example yamls are meant to be used along with the test cluster which you can bring up with `make cluster-up`. This will allso setup a local registry where the images will be pushed when you build from sources e.g. with `make cluster-sync`.

**Comment by jseguillon** [comment]
Hi @vasiliy-ul, I understand this relates to a form of automation but still think its not a real good way to welcome new user. Also notice there is no Readme indicating `cluster-up` should be used. Standard people would then think they can copy-paste raw examples and make things work. 

I'd propose we reverse the pattern for those examples: 
* set image by default to quay.io when available
* add some `sed` or awk to replace quay.io with local registry in the `Makefile`
* maybe add a comment on some few examples with no online container disk available telling: 
```
# This example needs a specific images to be built. Please take a look at cluster up documentation
```
