### ISSUE TITLE
can we add the Affinity proper to migration target ? 

### ISSUE THREAD

**Issue by larryliuqing** [kubevirt/kubevirt#7795]
**Is your feature request related to a problem? Please describe**:
type VirtualMachineInstanceMigrationSpec struct {
	// The name of the VMI to perform the migration on. VMI must exist in the migration objects namespace
	VMIName string `json:"vmiName,omitempty" valid:"required"`
}

I saw the migration define just only one VMI name, can we add the Affinity proper to migration target ?

**Comment by larryliuqing** [comment]
@usrbinkat :
I have a idea, and i want to define resource pool concept for k8s worker nodes based on the k8s Affinity concept, maybe the k8s worker nodes can be split to multiply group based on the different area, then we can migrate the vm from one resource pool to another resource pool with the Affinity migration parameter, can you agree ?

**Comment by Coefu** [comment]
> @usrbinkat : I have a idea, and i want to define resource pool concept for k8s worker nodes based on the k8s Affinity concept, maybe the k8s worker nodes can be split to multiply group based on the different area, then we can migrate the vm from one resource pool to another resource pool with the Affinity migration parameter but not just migrate to other's nodes for now, can you agree ?

I think it's a good idea, and I'm thinking about it.
