### ISSUE TITLE
Start running functional tests in parallel

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#780]
Our tests spend most of the time waiting for VMs to be finally booting. We should start thinking about parallelizing them to some degree.

@cynepco3hahue FYI

**Comment by cynepco3hahue** [comment]
@rmohr I started to look at it and I have some problem to run tests with `ginkgo` command
```
ginkgo -r tests/ -kubeconfig=cluster/vagrant-openshift/.kubeconfig
panic: invalid configuration: no configuration has been provided

goroutine 1 [running]:
kubevirt.io/kubevirt/tests.PanicOnError(0x189c0a0, 0xc4204decc0)
        /home/alukiano/go/src/kubevirt.io/kubevirt/tests/utils.go:547 +0x4a
kubevirt.io/kubevirt/tests_test.glob..func1()
        /home/alukiano/go/src/kubevirt.io/kubevirt/tests/console_test.go:39 +0x56
kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/suite.(*Suite).PushContainerNode(0xc42001e870, 0x119e556, 0x7, 0x1216ff0, 0x1, 0x187a689, 0x40, 0x6b, 0xc4200b6fc0, 0x90)
        /home/alukiano/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/internal/suite/suite.go:144 +0x1c2
kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo.FDescribe(0x119e556, 0x7, 0x1216ff0, 0x28)
        /home/alukiano/go/src/kubevirt.io/kubevirt/vendor/github.com/onsi/ginkgo/ginkgo_dsl.go:288 +0xbf
kubevirt.io/kubevirt/tests_test.init()
        /home/alukiano/go/src/kubevirt.io/kubevirt/tests/console_test.go:107 +0xfc
main.init()
        kubevirt.io/kubevirt/tests/_test/_testmain.go:48 +0x58

Ginkgo ran 1 suite in 2.477684891s
Test Suite Failed
```
I understand it does not happy with `kubeconfig`, but I do not know why, maybe do you have some idea?

**Comment by rmohr** [comment]
Since you are running the tests with ginkgo and not via the compiled binary, could it be that you need to pass `-ginkgo.kubeconfig`?

**Comment by fabiand** [comment]
@rmohr @cynepco3hahue I recall that artyom is actually working on removing parallelism (go routines) - Could you please give an update on this issue?

**Comment by rmohr** [comment]
@fabiand I think you mean #1065. That is not related to running tests in parallel with ginkgo. 

The broader picture for this issue is:
 * separating infra tests (e.g. virt-handler, virt-api, virt-controller recovery) from vm tests
 * introduce unique temporary namespaces per test-suite (not just uniqe namespaces for testing like we have now)
 * Run (all or some) vm tests in parallel

**Comment by cynepco3hahue** [comment]
@rmohr I succeeded to refactoring a code and run 6-7 specs in parallel, it was fast :smile: but to do it under our CI we need to have `ginkgo` CLI, and for this, we need to install `go` on the executioner node.
Any thoughts? Ran tests under container?

**Comment by rmohr** [comment]
> @rmohr I succeeded to refactoring a code and run 6-7 specs in parallel, it was fast  but to do it under our CI we need to have ginkgo CLI, and for this, we need to install go on the executioner node.
> Any thoughts? Ran tests under container?

Hm, best would be if we then run the test binary from a container too.
