### ISSUE TITLE
Rename launcher pod name to just the name of the vm + suffix

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#782]
Today vms are launched in `virtlauncher-DOM-SUF` style pods.

For users i.e. using UIs - it would be nice if the name could directly map to the dom name, i.e. `DOM-SUF`: `windows-654zt`

**Comment by rmohr** [comment]
The name has no connection to the vm. You can select the pod via its labels (which is the only reliable way). Further the name  makes clear that `virt-launcher` is running inside, which is imo ok and useful too for a pure infra-component.

**Comment by rmohr** [comment]
If we want to change the prefix, I would rather add an additional prefix: `kubevirt-`

**Comment by rmohr** [comment]
ok taking it back. Suffix is better. But let's make sure that `kubevirt` or something like that is included.

**Comment by xsgordon** [comment]
I think having the prefix reflect the domain it is responsible for is helpful for an admin/operator trying to inspect it.
