### ISSUE TITLE
Rename kubevirt.yaml to kubevirt-operator.yaml

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#783]
Other project shighlight that they are operators.

I think this makes sense, it directly explains how this .. operates.

See: rook.io.

**Comment by rmohr** [comment]
While I don't have any objection in general against this proposed name, it is just cosmetic and it will just break tooling which relies on that name already and does not really improve anything. So if we would not already have `kubevirt.yaml` I would have been ok to go with the other name too, but I don't really see any difference regarding to clarity.

**Comment by fabiand** [comment]
Yes, it's just a cosmetic thing, but to me it's a paper cut which can be changed in order to make it easier for external people who start with kubevirt, to understand what this specific yaml file delivers.

**Comment by fabiand** [comment]
So - the manifest has more object definitions, no question.

But all of them are required to implement our (rather complex) operator.

The key parts of the operator are the declarative definition of a required state of an entity, which is our VM, OVM, and other entities - and active components involved to get the system into the requested state - controller, handler and launcher are those for us.

Thos - and not more (!) i.e. demo parts, or examples - is part of the manifests, thus the name looks like a good fit to me.

**Comment by rmohr** [comment]
too far fetched for me.
