### ISSUE TITLE
The networking code overrides the default network interface

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#785]
We are assigning the one and only supported network interface in the defaulter (it uses e1000). Later when the VM gets started it gets overwritten with another interface (which uses virtio). 

Right new we did go with e1000 because it has broader out-of-the-box support (especially regarding to windows).

@vladikr could you have a look and resolve this situation by either remove the device from the defaulter, or add the device in the defaulter and only decorate it with the mac later on?

**Comment by rmohr** [comment]
@cynepco3hahue FYI

**Comment by rmohr** [comment]
Relevant places:
 * `pkg/virt-launcher/virtwrap/api/defaults.go`
 * `pkg/virt-launcher/virtwrap/network/network.go`

**Comment by vladikr** [comment]
Yea, you're right. I ignored the default nic model. I'll post a fix.
