### ISSUE TITLE
virt-handler: Reduce start-to-ready time

### ISSUE THREAD

**Issue by andreyod** [kubevirt/kubevirt#7873]
/kind enhancement

**What happened**:
It takes approximately 30 seconds for single virt-handler to become ready.

**What you expected to happen**:
A single virt-handler startup time should be under 10 seconds.

**Additional context**:
According to the profiling: SELinux policy installation is a bottleneck for virt-handler startup time.
SELinux execution time depends on the kernel and hardware profile of the system.
virt-handler startup time without SELinux policy is about 1 second.
Currently this policy is mandatory for libvirt to use Hugepages and virtiofs. Changing the number of rules in the policy probably won't significantly reduce the execution time because policy build and load into kernel is time consuming operations.

**Comment by xpivarc** [comment]
Hi @andreyod 
Any findings?

**Comment by andreyod** [comment]
> Hi @andreyod Any findings?

Hi. I'm not looking into this issue.
