### ISSUE TITLE
Kubevirt VM with Bridge interface is not reachable. ssh failed with timeout. virtctl console hangs with "Successfully connected to vm console. The escape sequence is ^]"

### ISSUE THREAD

**Issue by nvinnakota10** [kubevirt/kubevirt#7889]
**What happened**:
The kubevirt VM with bridge interface is unreachable. The ssh to the VM fails with connection time out. I was not able to debug it as I am unable to connect to the virsh console and virctl console.

The issue happens every time.

The virtcl console vmi hangs with the below message:
"Successfully connected to vm console. The escape sequence is ^]"

I tried hitting enter multiple times, but unable to get the console access.

virsh console throws the below error:
error: internal error: character device console0 is not using a PTY

**What you expected to happen**:
The kubevirt VM created should be reached through the below methods:

1. Direct ssh to VM's IP failed with connection timed out. 
2. virctl console vmi should be successful, giving the console access to the VM.
3. virsh console should allow user to connect to the VM.

**How to reproduce it (as minimally and precisely as possible)**:
1. Install kubevirt in the Kubernetes cluster.
2. Create a VM.
3. Try virtctl console vmi and virsh console domain-Id

**Additional context**:
Unable to modify grub configuration as the VM itself is not reachable from the host.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.48.0
- Kubernetes version (use `kubectl version`): v1.23.5
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Ubuntu 20.04.2 LTS
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

[virt-launcher.log](https://github.com/kubevirt/kubevirt/files/8882645/virt-launcher.log)
[virt-handler.log](https://github.com/kubevirt/kubevirt/files/8882646/virt-handler.log)
[vm.txt](https://github.com/kubevirt/kubevirt/files/8882650/vm.txt)

**Comment by usrbinkat** [comment]
Thank you for opening this issue.

As I understand it, the `virtctl ssh` command performs ssh to the VM over a local `kubectl port-forward` style tunnel. In a bridged scenario, ssh should be accessed by ssh'ing directly to the VM's IP as provided by the bridged interface(s).

This may be something we can better address with documentation if you are interested in opening an issue pursuing documentation enhancement.

As for the tty/serial console access, many VM images do not enable the serial console by default. This can be enabled by either customizing the VM image, or by setting cloud-init commands to configure a serial tty console at deploy time.

Would any those options be sufficient to resolve this issue?

**Comment by nvinnakota10** [comment]
@usrbinkat Thanks for your response. Direct ssh also fails for me. Moreover, I find the same issue when I tried with masquerade interface.

In both the cases I am failing to get into VM using the below:

1. Direct ssh to VM's IP
2. virctl console
3. virsh console

Also, for virsh I tried the below steps to check if I can access the VM:

1. Create a VM image with grub configured for tty0
2. Create a VMI using the image by directly applying a .yaml file.
3. Modify the domain and make the serial and console type to pty
4. Restarting the domain. 

The above steps didn't help me get the virsh console work. 

Can you please point me to on how I can set the cloud-init commands to configure the serial tty console in the VM spec at deploy time.

I updated the description to address the issue.

Thanks

**Comment by nvinnakota10** [comment]
@usrbinkat  

I know the Virt-launcher pod won't allow to run utilities like tcpdump, ping etc. But is there any way we can use these utilities on the launcher pod, as this pod has direct connection to the VM and having such utilities can help debugging any connectivity issue from the VM in an easier way.


Thanks

**Comment by nvinnakota10** [comment]
Using a vm image from ubuntu 20.04 fixed the issue.
