### ISSUE TITLE
when kubelet set param --root-dir=xxx (not /var/lib/kubelet)，kubevirt can't start a vm 

### ISSUE THREAD

**Issue by yuntianfeijing** [kubevirt/kubevirt#7895]
**What happened**:
when kubelet set param --root-dir=xxx (not /var/lib/kubelet)，kubevirt can't start a vm 

**What you expected to happen**:
when kubelet set param --root-dir=xxx (not /var/lib/kubelet)，kubevirt can't start a vm 

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.
 1、set kubelet param --root-dir=xxx (not /var/lib/kubelet)
 2、use virt-operator to deploy all Component
 3、start a vm

**Additional context**:
i think 
https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-operator/resource/generate/components/daemonsets.go#L222
shoud be set by user in virt-operator or DevicePluginPath shoud be set by user in virt-handler

**Environment**:
- KubeVirt version (use `virtctl version`): A
- Kubernetes version (use `kubectl version`): A
- VM or VMI specifications: A
- Cloud provider or hardware configuration: N
- OS (e.g. from /etc/os-release): N
- Kernel (e.g. `uname -a`): N
- Install tools: virt-operator
- Others: N

**Comment by usrbinkat** [comment]
Thank you for opening this issue.

If I am understanding correctly, you are attempting to run on a non-standard kubelet path using the feature enabled in PR [#3427](https://github.com/kubevirt/kubevirt/pull/3427)?

If that is not working, can you provide more details on your environment per the template?
