### ISSUE TITLE
Decide on import order

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#79]
Currently we just have alphabetical import order in our go code.

Let's decide if this is ok, or if we want more grouping there. Very common is an order like:

1) go system packages
2) other vendor dependencies
3) Project packages

If you have an empty line between these blocks, `go fmt` will only sort the blocks.

Since we are in the kubernetes world, I could think of four sections:

1) go system packages
2) other vendor dependencies
4) Kubernetes packages
3) Project packages

Just keeping one sorted list is fine for me too.

**Comment by rmohr** [comment]
To illustrate this:


Multiple blocks:
```golang
import (
	"fmt"
	"net/http"
	"reflect"
	"strings"
	"time"

	"github.com/emicklei/go-restful"
	"github.com/go-kit/kit/endpoint"
	"golang.org/x/net/context"

	"k8s.io/client-go/pkg/api"
	metav1 "k8s.io/client-go/pkg/apis/meta/v1"
	"k8s.io/client-go/pkg/fields"
	"k8s.io/client-go/pkg/labels"
	"k8s.io/client-go/pkg/runtime"
	"k8s.io/client-go/pkg/runtime/schema"
	"k8s.io/client-go/rest"

	"kubevirt.io/kubevirt/pkg/kubecli"
	"kubevirt.io/kubevirt/pkg/middleware"
	mime "kubevirt.io/kubevirt/pkg/rest"
	"kubevirt.io/kubevirt/pkg/rest/endpoints"
)
```

Single block:

```golang
import (
	"fmt"
	"github.com/emicklei/go-restful"
	"github.com/go-kit/kit/endpoint"
	"golang.org/x/net/context"
	"k8s.io/client-go/pkg/api"
	metav1 "k8s.io/client-go/pkg/apis/meta/v1"
	"k8s.io/client-go/pkg/fields"
	"k8s.io/client-go/pkg/labels"
	"k8s.io/client-go/pkg/runtime"
	"k8s.io/client-go/pkg/runtime/schema"
	"k8s.io/client-go/rest"
	"kubevirt.io/kubevirt/pkg/kubecli"
	"kubevirt.io/kubevirt/pkg/middleware"
	mime "kubevirt.io/kubevirt/pkg/rest"
	"kubevirt.io/kubevirt/pkg/rest/endpoints"
	"net/http"
	"reflect"
	"strings"
	"time"
)
```

**Comment by mpolednik** [comment]
For the sake of tooling, I (so far) like [goimports](https://godoc.org/golang.org/x/tools/cmd/goimports). It automatically groups the imports (=> leading to multiple blocks case) to std/vendored sections which I believe is slightly easier on the eyes. It does seem to respect custom groups, but the alphabetical sorting within groups just happens to be fine with kubevirt.

```In [1]: "kubevirt" > "kubernetes"
Out[1]: True```

[Random blog post comparing gofmt & goimports](http://goinbigdata.com/goimports-vs-gofmt/)

**Comment by stu-gott** [comment]
I strongly agree that we should adopt either one of the proposed schemes. Not only is this extremely, common--it is the convention Kubernetes is using. As for the choice between 3 or 4 sections, I don't have a strong opinion. I'll simply note that using only 3 sections might imply to some observers that Kubernetes and Kubevirt are the same project.

**Comment by rmohr** [comment]
goimports looks nice. I would vote for three sections then, since that is what goimports provides and full automation is definitely what I prefer. Created #81, so that we have something concrete for discussion.

**Comment by rmohr** [comment]
> I don't have a strong opinion. I'll simply note that using only 3 sections might imply to some observers that Kubernetes and Kubevirt are the same project.

Right so what I would do with 3 sections, is making kubevirt.io the third section, treating client-go kubernetes stuff as what it is, a third party dependency.

**Comment by admiyo** [comment]
so long as the choice is automated, I do not care
I don't want to have to look up to find where something comes  from
we had that in Python, and it is annoying.   Not sure what it really gains us.  
I kindof like ABC one big block, but not strongly enough to fight for it

**Comment by fabiand** [comment]
Any standard is fine for me.
I personally like the 3 sections approach.

**Comment by sandrobonazzola** [comment]
Be aware of this discussion: https://groups.google.com/forum/#!topic/golang-nuts/eAtUvHC6moQ/discussion

While thinking about the import sorting :-)
