### ISSUE TITLE
make the vm's time and timezone same with host.

### ISSUE THREAD

**Issue by larryliuqing** [kubevirt/kubevirt#7916]
**What happened**:
```
node1:~$ kubectl exec -it  virt-launcher-i-wffqac3e-g8kf4 -- date
Tue Jun 14 14:04:52 UTC 2022
node1:~$ date
Tue 14 Jun 2022 10:05:11 PM CST
node1:~$
```
Base on the above output, i can see the pod virt-lancher timezone is not same with host, then i want to make the pod virt-lancher has same timezone with host, and i got a link https://stackoverflow.com/questions/55089265/kubernetes-timezone-in-pod-with-command-and-argument
Following the method of this link, we can make the pod virt-lancher has same timezone with host. 

Also I got link  https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#timezone, vm support configure the clock to make the vm's time and timezone same with host.

I want to know if the current kubevirt implement support to make the vm's time and timezone same with host?

**What you expected to happen**:
make the vm's time and timezone same with host.

**How to reproduce it (as minimally and precisely as possible)**:
create a vm.

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by larryliuqing** [comment]
@usrbinkat : thanks, I will try cloud-init solution.

**Comment by chenxinlong** [comment]
Is that a way to set libevirt domain xml `clock offset` to  `localtime` by kubevirt vm `spec.domain.clock` ?
