### ISSUE TITLE
Build requires SELinux permissive mode

### ISSUE THREAD

**Issue by yuvalif** [kubevirt/kubevirt#794]
when running "make", SELinux complains about the issues in the attached log.
[mylogfile.txt](https://github.com/kubevirt/kubevirt/files/1789283/mylogfile.txt)

readme should mention this before running "make"

**Comment by rmohr** [comment]
Only some versions of fedora/centos are affected I think. I just see them since I updated to fedora27 and here is a bugzilla regarding to that issue: https://bugzilla.redhat.com/show_bug.cgi?id=1545858

**Comment by rmohr** [comment]
Since the tile implies that you had to disable selinux: Did you just have to put it in permissive mode to not generate the warnings or to make builds succeed at all?

**Comment by yuvalif** [comment]
I moved selinux to permissive mode, now, not getting the selinux errors. however i still get failure in rsync (this probably what was triggering the selinux alarm):
make
hack/dockerized "./hack/check.sh && ./hack/build-go.sh install "
sha256:4be8ad1dac3766a81d3951b6e9751210fdf6e2134176dc68b2907348c053f22d
go version go1.9.2 linux/amd64
rsync: safe_read failed to read 1 bytes [sender]: Connection reset by peer (104)
rsync error: error in rsync protocol data stream (code 12) at io.c(276) [sender=3.1.3]
Waiting for rsyncd to be ready
skipping directory .
go version go1.9.2 linux/amd64
Compiling tests...
    compiled tests.test
7155b6d53e71043cb0aa42138555bf78a6836ad40c6a7d43c0359e73e816643d
7155b6d53e71043cb0aa42138555bf78a6836ad40c6a7d43c0359e73e816643d
hack/dockerized "DOCKER_TAG= ./hack/build-manifests.sh"
sha256:4be8ad1dac3766a81d3951b6e9751210fdf6e2134176dc68b2907348c053f22d
go version go1.9.2 linux/amd64
rsync: safe_read failed to read 1 bytes [sender]: Connection reset by peer (104)
rsync error: error in rsync protocol data stream (code 12) at io.c(276) [sender=3.1.3]
Waiting for rsyncd to be ready
skipping directory .
go version go1.9.2 linux/amd64
2968595f46d14008529e3aada90e4a5daf8524a2f96d514491638e5a26677272
2968595f46d14008529e3aada90e4a5daf8524a2f96d514491638e5a26677272


 

    On Wednesday, March 7, 2018, 4:19:55 PM GMT+2, Roman Mohr <notifications@github.com> wrote:  
 
 
Since the tile implies that you had to disable selinux: Did you just have to put it in permissive mode to not generate the warnings or to make builds succeed at all?

**Comment by rmohr** [comment]
> rsync: safe_read failed to read 1 bytes [sender]: Connection reset by peer (104)
> rsync error: error in rsync protocol data stream (code 12) at io.c(276) [sender=3.1.3]

Oh that error is harmless. It is from our "wait for rsync to become ready to connect connections" check, from what you posted it looks like the build continues without issues. 

We should make sure that these rsync-checks only get printed if it takes unexpectedly long, to not confuse people.

**Comment by rmohr** [comment]
After a build check `$?` to see if the build fails, but it looks like it does fine.

**Comment by nellyc** [comment]
@fabiand where do we stand with this?

**Comment by fabiand** [comment]
@sreichar do you know if this is an issue for you with the downstream builds?

**Comment by sreichar** [comment]
@fabiand we do not use the full make, because of all the dependencies, but use several of the ./hack scripts, including at least one that used rsync (needed to have it added to the build system).   Did not see an issue the last build which was about 2 weeks ago.

**Comment by fabiand** [comment]
Okay, thank you.
