### ISSUE TITLE
unit test flake: there are no expected calls of the method "Freeze" for that receiver

### ISSUE THREAD

**Issue by EdDev** [kubevirt/kubevirt#7940]
**What happened**:

Unit tests flake: ["there are no expected calls of the method "Freeze" for that receiver"](https://search.ci.kubevirt.io/?search=there+are+no+expected+calls+of+the+method+%22Freeze%22+for+that+receiver&maxAge=336h&context=1&type=bug%2Bjunit&name=&excludeName=&maxMatches=5&maxBytes=20971520&groupBy=job)

**How to reproduce it (as minimally and precisely as possible)**:
N/A

**Comment by oshoval** [comment]
Lets add Times.Any as we are doing mostly everywhere ?
Note that in some cases it shows a problem in the tests or so, but it was agreed that we can add Times.Any and
its up to the team that own it to fix it better.
