### ISSUE TITLE
Can i customize SMBIOS information for each VMI

### ISSUE THREAD

**Issue by sofiworker** [kubevirt/kubevirt#7959]
Describe:
i want to customize smbios information for each vmi，but found smbios configuration in KubeVirtConfiguration not VirtualMachineInstance.Is there any way to customize smbios for vmi

**Comment by alicefr** [comment]
The suggested way is to create a custom sidecar. Please check the example in [example-hook-sidecar](https://github.com/kubevirt/kubevirt/tree/main/cmd/example-hook-sidecar) and the [vmi-with-sidecar-hook.yaml](https://github.com/kubevirt/kubevirt/blob/main/examples/vmi-with-sidecar-hook.yaml)

**Comment by sofiworker** [comment]
@alicefr thanks
