### ISSUE TITLE
importer pod unable to complete the process and stuck at final step

### ISSUE THREAD

**Issue by knitanurag** [kubevirt/kubevirt#7970]
Refrence URL : https://kubevirt.io/labs/kubernetes/lab2.html
Setup : kubeadm kubernetes setup
1. Created PV
`apiVersion: v1
kind: PersistentVolume
metadata:
  name: another-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/mnt/data"
`
3. Create PVC
`apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: "fedora"
  labels:
    app: containerized-data-importer
  annotations:
    cdi.kubevirt.io/storage.import.endpoint: "http://<nexusip>:31105/repository/ecfilerepo/fedoracdi/Fedora-Cloud-Base-33-1.2.x86_64.raw.xz"
spec:
  accessModes:
  - ReadWriteOnce
  storageClassName: manual
  resources:
    requests:
      storage: 8Gi
`

**Image :** Fedora-Cloud-Base-33-1.2.x86_64.raw.xz
**Importer logs:**
I0621 15:52:06.070977       1 importer.go:83] Starting importer
I0621 15:52:06.071016       1 importer.go:150] begin import process
I0621 15:52:06.077663       1 data-processor.go:379] Calculating available size
I0621 15:52:06.077689       1 data-processor.go:391] Checking out file system volume size.
I0621 15:52:06.077711       1 data-processor.go:399] Request image size not empty.
I0621 15:52:06.077791       1 data-processor.go:404] Target size 8Gi.
I0621 15:52:06.093016       1 nbdkit.go:294] Waiting for nbdkit PID.
I0621 15:52:06.593705       1 nbdkit.go:315] nbdkit ready.
I0621 15:52:06.593952       1 data-processor.go:282] New phase: TransferScratch
I0621 15:52:06.594084       1 util.go:192] Writing data...
I0621 15:53:13.806357       1 data-processor.go:282] New phase: Convert
I0621 15:53:13.806412       1 data-processor.go:288] Validating image
I0621 15:53:14.055597       1 qemu.go:259] 0.00
I0621 15:53:14.473823       1 qemu.go:259] 1.03
I0621 15:53:15.288432       1 qemu.go:259] 2.05
I0621 15:53:16.043568       1 qemu.go:259] 3.08
I0621 15:53:16.830688       1 qemu.go:259] 4.10
I0621 15:53:17.652198       1 qemu.go:259] 5.13
I0621 15:53:18.372830       1 qemu.go:259] 6.15
I0621 15:53:19.324686       1 qemu.go:259] 7.18
I0621 15:53:20.080998       1 qemu.go:259] 8.20
I0621 15:53:20.841019       1 qemu.go:259] 9.23
I0621 15:53:21.774360       1 qemu.go:259] 10.25
I0621 15:53:22.452105       1 qemu.go:259] 11.28
I0621 15:53:23.165366       1 qemu.go:259] 12.30
I0621 15:53:23.752660       1 qemu.go:259] 13.33
I0621 15:53:24.340823       1 qemu.go:259] 14.36
I0621 15:53:25.073569       1 qemu.go:259] 15.38
I0621 15:53:25.706309       1 qemu.go:259] 16.41
I0621 15:53:26.590803       1 qemu.go:259] 17.43
I0621 15:53:27.320715       1 qemu.go:259] 18.46
I0621 15:53:27.809749       1 qemu.go:259] 19.48
I0621 15:53:28.624864       1 qemu.go:259] 20.51
I0621 15:53:29.214189       1 qemu.go:259] 21.53
I0621 15:53:29.850682       1 qemu.go:259] 22.56
I0621 15:53:30.354508       1 qemu.go:259] 23.58
I0621 15:53:31.038037       1 qemu.go:259] 24.61
I0621 15:53:31.629904       1 qemu.go:259] 25.63
I0621 15:53:32.229383       1 qemu.go:259] 26.66
I0621 15:53:32.645346       1 qemu.go:259] 27.69
I0621 15:53:33.172045       1 qemu.go:259] 28.71
I0621 15:53:33.673069       1 qemu.go:259] 29.74
I0621 15:53:34.092555       1 qemu.go:259] 30.76
I0621 15:53:34.921298       1 qemu.go:259] 31.79
I0621 15:53:35.333784       1 qemu.go:259] 32.81
I0621 15:53:35.739691       1 qemu.go:259] 33.84
I0621 15:53:36.260428       1 qemu.go:259] 34.86
I0621 15:53:36.831942       1 qemu.go:259] 35.89
I0621 15:53:37.323176       1 qemu.go:259] 36.91
I0621 15:53:37.928147       1 qemu.go:259] 37.94
I0621 15:53:38.390240       1 qemu.go:259] 38.96
I0621 15:53:38.986886       1 qemu.go:259] 39.99
I0621 15:53:39.663426       1 qemu.go:259] 41.02
I0621 15:53:40.154210       1 qemu.go:259] 42.04
I0621 15:53:40.705307       1 qemu.go:259] 43.07
I0621 15:53:41.166031       1 qemu.go:259] 44.09
I0621 15:53:41.580152       1 qemu.go:259] 45.12
I0621 15:53:41.951595       1 qemu.go:259] 46.14
I0621 15:53:42.387305       1 qemu.go:259] 47.17
I0621 15:53:43.063419       1 qemu.go:259] 48.19
I0621 15:53:43.625377       1 qemu.go:259] 49.22
I0621 15:53:44.196425       1 qemu.go:259] 50.24
I0621 15:53:44.913283       1 qemu.go:259] 51.27
I0621 15:53:45.555167       1 qemu.go:259] 52.29
I0621 15:53:45.995953       1 qemu.go:259] 53.32
I0621 15:53:46.684023       1 qemu.go:259] 54.35
I0621 15:53:47.239301       1 qemu.go:259] 55.37
I0621 15:53:47.680432       1 qemu.go:259] 56.40
I0621 15:53:48.151811       1 qemu.go:259] 57.42
I0621 15:53:48.609325       1 qemu.go:259] 58.45
I0621 15:53:49.134820       1 qemu.go:259] 59.47
I0621 15:53:49.783383       1 qemu.go:259] 60.50
I0621 15:53:50.641073       1 qemu.go:259] 61.52
I0621 15:53:51.239390       1 qemu.go:259] 62.55
I0621 15:53:52.341603       1 qemu.go:259] 63.57
I0621 15:53:53.078089       1 qemu.go:259] 64.60
I0621 15:53:53.583893       1 qemu.go:259] 65.62
I0621 15:53:54.421801       1 qemu.go:259] 66.65
I0621 15:53:55.163149       1 qemu.go:259] 67.68
I0621 15:53:55.651398       1 qemu.go:259] 68.70
I0621 15:53:56.513095       1 qemu.go:259] 69.73
I0621 15:53:57.133327       1 qemu.go:259] 70.75
I0621 15:53:58.212208       1 qemu.go:259] 71.78
I0621 15:53:59.029290       1 qemu.go:259] 72.80
I0621 15:53:59.908148       1 qemu.go:259] 73.83
I0621 15:54:00.813045       1 qemu.go:259] 74.85
I0621 15:54:01.478054       1 qemu.go:259] 75.88
I0621 15:54:02.573762       1 qemu.go:259] 76.90
I0621 15:54:03.418874       1 qemu.go:259] 77.93
I0621 15:54:03.867969       1 qemu.go:259] 78.96
I0621 15:54:04.738503       1 qemu.go:259] 79.98
I0621 15:54:05.751908       1 qemu.go:259] 81.01
I0621 15:54:06.322398       1 qemu.go:259] 82.03
I0621 15:54:07.101107       1 qemu.go:259] 83.06
I0621 15:54:07.820464       1 qemu.go:259] 84.08
I0621 15:54:08.792171       1 qemu.go:259] 85.11
I0621 15:54:09.502224       1 qemu.go:259] 86.13
I0621 15:54:10.639224       1 qemu.go:259] 87.16
I0621 15:54:11.280215       1 qemu.go:259] 88.18
I0621 15:54:12.106907       1 qemu.go:259] 89.21
I0621 15:54:12.865499       1 qemu.go:259] 90.23
I0621 15:54:13.419300       1 qemu.go:259] 91.26
I0621 15:54:14.132548       1 qemu.go:259] 92.29
I0621 15:54:14.920819       1 qemu.go:259] 93.31
I0621 15:54:15.799639       1 qemu.go:259] 94.34
I0621 15:54:16.825905       1 qemu.go:259] 95.36
I0621 15:54:17.361960       1 qemu.go:259] 96.39
I0621 15:54:17.866380       1 qemu.go:259] 97.41
I0621 15:54:18.504615       1 qemu.go:259] 98.44
I0621 15:54:19.100155       1 qemu.go:259] 99.46
I0621 15:54:25.114255       1 data-processor.go:282] New phase: Resize
I0621 15:54:25.235164       1 data-processor.go:372] Expanding image size to: 8Gi
I0621 15:54:25.275969       1 data-processor.go:288] Validating image
I0621 15:54:25.284287       1 data-processor.go:282] New phase: Complete
I0621 15:54:25.284425       1 util.go:39] deleting file: /scratch/disk.img
I0621 15:54:25.368279       1 util.go:39] deleting file: /scratch/tmpimage
I0621 15:54:25.583508       1 importer.go:194] Import Complete
E0621 15:54:25.583543       1 importer.go:324] could not get file descriptor for fsync call: open /data/disk.img: no such file or directory

**Comment by alicefr** [comment]
I'd suggest you to open the issue under the [CDI](https://github.com/kubevirt/containerized-data-importer) repository. It seems to me that the importer pod cannot find the PVC directory. Could you please try to exec in the importer pod and do an `ls /data` ?
