### ISSUE TITLE
Some questions about arm builds

### ISSUE THREAD

**Issue by mzzgaopeng** [kubevirt/kubevirt#7974]
When we use the arm environment to compile and complete the use phase, it is found that the handler's initcontainer fails at startup

```
unsupported configuration: unable to find any emulator to server 'x86_64' architecture
```

It is found that the shell script started here is fixed to x86_64
cmd/virt-launcher/node-labeller/node-labeller.sh
```
virsh domcapabilities --machine q35 --arch x86_64 --virttype $VIRTTYPE > /var/lib/kubevirt-node-labeller/virsh_domcapabilities.xml

cp -r /usr/share/libvirt/cpu_map /var/lib/kubevirt-node-labeller

virsh domcapabilities --machine q35 --arch x86_64 --virttype $VIRTTYPE | virsh hypervisor-cpu-baseline --features /dev/stdin --machine q35 --arch x86_64 --virttype $VIRTTYPE > /var/lib/kubevirt-node-labeller/supported_features.xml
virsh capabilities > /var/lib/kubevirt-node-labeller/capabilities.xml
```

What is the reason for not adapting to the arm architecture here?
Is it possible to add different parameters to judge different schema types?

**Comment by zhlhahaha** [comment]
Hi, nodelabeller is only works on x86_64, please refer to the commit `72adfff47cd0d7207eb2cb69cf6f64dbe795b0ef`.
Would you like to share how you start your kubevirt cluster on Arm server? By the way, we only support kubevirt works on Arm64 rather than Arm32.

**Comment by zhlhahaha** [comment]
Ok, I will do it. By the way, if you want to try compile kubeVirt on Arm64 and run it, Here is a fast way.

```
# cd to kubevirt source code
$ wget https://github.com/kubevirt/kubevirtci/pull/784.patch
$ git am 784.patch
$ export KUBEVIRT_PROVIDER=kind-k8s-1.23
$ export KUBEVIRT_NUM_NODES=2
$ export KIND_NODE_IMAGE=kindest/node:v1.23.6
$ make cluster-up && make cluster-sync
```

**Comment by mzzgaopeng** [comment]
I built it in the following way

```
docker run -dp 5000:5000 --restart=always --name registry registry

BUILD_ARCH=aarch64

DOCKER_PREFIX=127.0.0.1:5000/kubevirt DOCKER_TAG=armfix make bazel-build-images

DOCKER_PREFIX=127.0.0.1:5000/kubevirt DOCKER_TAG=armfix make push

```
