### ISSUE TITLE
Bug: node verbosity does not affect virt-launcher

### ISSUE THREAD

**Issue by iholder101** [kubevirt/kubevirt#7993]
**What happened**:
Kubevirt CR exposes a [logVerbosity](https://kubevirt.io/api-reference/master/definitions.html#_v1_logverbosity) struct which includes a `nodeVerbosity` field. This field is of king `map[string]int` and it's purpose is to determine a log verbosity to all components that reside within some node.

Some components (e.g. `virt-launcher`) are not affected by this field.

**What you expected to happen**:
All component, like `virt-launcher`, to determine their verbosity level according to what's defined in Kubevirt CR's  `nodeVerbosity` field.

**How to reproduce it (as minimally and precisely as possible)**:
Set the above `nodeVerbosity` field to a high value, see that virt-launcher is not affected.

**Additional context**:
The main problem is that the verbosity level for virt-launcher is determined by an [environment variable](https://github.com/kubevirt/kubevirt/blob/v0.54.0/pkg/virt-controller/services/template.go#L1183). This is being set on virt-launcher Pod creation, hence before it's running, therefore we cannot know in advance to which node it will be scheduled to.

We should either find a way to fix this or deprecate this field alltogether.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.54.0
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by iholder101** [comment]
AFAIK this bug still exists
/remove-lifecycle stale

**Comment by victortoso** [comment]
/reopen

This is still a problem.
