### ISSUE TITLE
Ability to annotate any pod which exposes kubevirt metrics

### ISSUE THREAD

**Issue by digambar15** [kubevirt/kubevirt#7996]
We are able to fetch VMI metrics manually by adding scrape URL annotations to virt-handler pods.
Problem is, this is not an automated process as user intervention is needed everytime pod goes down/node goes down.
If we try adding annotations to virt-handler deamonsets, then it will get added but wipes out after every reconcile loop.
virt-handler deamonset is implemented as part of source code in controller and that reconcile runs after certain few sec/min.

We are using Azure Container Insights to scrape prometheus metrics from various components in our cluster including kubevirt.  Annotations are placed on pods so that Insights can identify pods that emit metrics.  We would like to place annotations on the virt-operator, virt-api, virt-controller, and virt-handler pods.  For the virt-handler, we tried adding annotations to the template spec in the virt-handler daemonset.  However, the reconciler wipes these out.  We are looking for a way to configure custom annotations to be put on the pod template spec of this daemonset.

There is no straight forward way out, we would want to expand the enhancement to include the ability to annotate any pod which exposes kubevirt metrics.

**Comment by xpivarc** [comment]
You can use https://github.com/kubevirt/api/blob/2850590b2880a2985a3f169f5432ebe79e56410e/core/v1/types.go#L1679 to modify Kubevirt components.

**Comment by digambar15** [comment]
Thanks @xpivarc . This is really helpful. I have applied custom components for virt-handler daemonsets. Do you know how it gets applied to virt-handler ds and pods respectively, asking here because I saw below annotation applied in kubevirt but didn't see it in daemonsets and pods.  

  Customize Components:
    Patches:
      Patch:          {"spec": {"template":{"metadata":{"annotations":{"prometheus.io/path":"/metrics","prometheus.io/port":"8443","prometheus.io/scheme":"https","prometheus.io/scrape":"true"}}}}}
      Resource Name:  virt-handler
      Resource Type:  Daemonsets
      Type:           strategic

**Comment by xpivarc** [comment]
> Thanks @xpivarc . This is really helpful. I have applied custom components for virt-handler daemonsets. Do you know how it gets applied to virt-handler ds and pods respectively, asking here because I saw below annotation applied in kubevirt but didn't see it in daemonsets and pods.
> 
> Customize Components: Patches: Patch: {"spec": {"template":{"metadata":{"annotations":{"prometheus.io/path":"/metrics","prometheus.io/port":"8443","prometheus.io/scheme":"https","prometheus.io/scrape":"true"}}}}} Resource Name: virt-handler Resource Type: Daemonsets Type: strategic

Do you mean it doesn't work?

**Comment by digambar15** [comment]
I applied below patch.yaml 
---
apiVersion: kubevirt.io/v1alpha3
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: nc-system
spec:
  certificateRotateStrategy: {}
  configuration: {}
  customizeComponents:
    patches:
    - resourceType: Daemonsets
      resourceName: virt-handler
      patch: '{"spec": {"template":{"metadata":{"annotations":{"prometheus.io/path":"/metrics","prometheus.io/port":"8443","prometheus.io/scheme":"https","prometheus.io/scrape":"true"}}}}}' 
      type: strategic

----

I got patched in kubevirt resources.

**Comment by xpivarc** [comment]
@digambar15 I see. Please try `Daemonsets` -> `Daemonset`

**Comment by digambar15** [comment]
Thanks @xpivarc! :)
