### ISSUE TITLE
Permit creating KVM domains

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#802]
Today all domains are run in emulation mode.

We need to be able to run them accelerated.

**Comment by fabiand** [comment]
IIUIC then we default to `qemu` and there is no VM API field to change this.

Further more this has implications on scheduling (less) but making sure that /dev/kvm get's into a container.

We could consider to use the kvm DP /cc @mpolednik

**Comment by rmohr** [comment]
#822 contains a now a preference for kvm domains. If it is run on a test-vm, nested virtualizastion will need to be enabled. If the cpu does not expose virtualization functionality it will fallback to emulation. #804 should not not be that critical anymore. But want to enforce the presence of /dev/kvm in the future.

**Comment by simon3z** [comment]
@fabiand @rmohr was this fixed? Is something missing to complete this?

**Comment by fabiand** [comment]
I'm closing this specific issue, as we can create kvm domains.

We can track future changes in separate issues.
