### ISSUE TITLE
virtctl is not console friendly

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#803]
I noticed that `virtctl console` does not respect EOL, i.e. in
`virtctl console testvm | grep -m1 login`

Here virtctl should quit if EOL is detected.

**Comment by davidvossel** [comment]
This probably has something to do with virtctl needing to put the terminal into raw mode when connected to the VM console. This is required to prevent things like 'ctrl-c' from breaking out of the console rather than being interpreted by the VM's terminal. 

I'm not sure we can achieve the behavior you're looking for. Is there really a use case for this ?

**Comment by simon3z** [comment]
@fabiand beginner/help-wanted?

**Comment by fabiand** [comment]
Automation is my use-case.

Launch a VM and interact with it using expect, or grepping for some output.

**Comment by rmohr** [comment]
I think that we can simply do the same what docker/kubectl exec does and introduce the "-it" flags. However, serial console is not ssh or another bash session. Will have to look into the details here of some of the automation use cases (expect scripts,...). Just introducing the flags alone would not help you in my opinion.

**Comment by davidvossel** [comment]
@fabiand is ssh an option for your automation?

**Comment by fabiand** [comment]
@davidvossel I think so *cough*ansible*cough* - at least in the vm world

@rmohr Yeah, I agree. It's just annoying, and btw with kubectl exec it's also annoying.

**Comment by davidvossel** [comment]
> I think so coughansiblecough - at least in the vm world

so, would (ssh + cloud-init for key injection) work for the automation use case? If so, can we close this?

**Comment by fabiand** [comment]
I wouldn#t say it's an replamcenet.

but I am fine in closing thi sbug for now.
