### ISSUE TITLE
DHCP server6 painc error

### ISSUE THREAD

**Issue by mzzgaopeng** [kubevirt/kubevirt#8034]
**What happened**:
virt-launcher panic

**What you expected to happen**:

After I created the virtual machine, restarted the vm, looked at the log of virt-lanuncher, and found the phenomenon of panic

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.
Occasionally

**Additional context**:
pkg/network/dhcp/serverv6/serverv6.go
```
func (h *DHCPv6Handler) ServeDHCPv6(conn net.PacketConn, peer net.Addr, m dhcpv6.DHCPv6) {
	log.Log.V(4).Info("DHCPv6 serving a new request")

	// TODO if we extend the server to support bridge binding, we need to filter out non-vm requests

	response, err := h.buildResponse(m)
	if err != nil {
		log.Log.V(4).Reason(err).Error("DHCPv6 failed building a response to the client")

	}

	if _, err := conn.WriteTo(response.ToBytes(), peer); err != nil {
		log.Log.V(4).Reason(err).Error("DHCPv6 failed sending a response to the client")
	}
}
```
if 	response, err := h.buildResponse(m),has error
will panic in this place：conn.WriteTo(response.ToBytes(), peer);

<img width="1717" alt="virt-launcher" src="https://user-images.githubusercontent.com/22125180/177113137-e5198412-6882-4a6c-b83b-ced14a138896.png">

**Environment**:
- KubeVirt version (use `virtctl version`): 0.46
- Kubernetes version (use `kubectl version`): 1.23
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Centos7.6
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by oshoval** [comment]
Hi 
Thanks for the report
Indeed the function miss error handing

Can you paste please the yaml of the VM you are using ?
I wonder if we can simulate it locally, to understand the root cause as well that the `buildResponse` fails

Thanks

**Comment by mzzgaopeng** [comment]
> > 
> 
> Our vm is a dual-stack virtual machine, and the yaml of the vm is the same. I am also reproducing what causes paninc. If I make progress, I will sync in time.



> Hi Thanks for the report Indeed the function miss error handing
> 
> Can you paste please the yaml of the VM you are using ? I wonder if we can simulate it locally, to understand the root cause as well that the `buildResponse` fails
> 
> Thanks

Our vm is a dual-stack virtual machine, and the yaml of the vm is the same. I am also reproducing what causes paninc.
If I make progress, I will sync in time.

**Comment by mzzgaopeng** [comment]
I seem to have found the cause of the problem. Our network environment is a layer-2 bridge network, which occurs when a virtual machine has an IPv6 address conflict under the same layer-2 network;
It seems that dhcpv6 responds to the problem in the same layer 2 network environment, for example: the dhcp of other virt-launcher corresponds to the dhcp request of this virtual machine;

**Comment by AlonaKaplan** [comment]
@mzzgaopeng thanks for reporting the bug.
Can you please share the network configuration of the 2 VMs involved (the VM with the crashing DHCPv6 server and the VM that sent the request).
At least the - spec.domain.devices.interfaces and spec.networks section from the VMs yamls.
And the `ip a` output from the VM's virt-launcher pod and from the VMs console.

DHCPv6 server should run only when a VM has masquerade binding. Does the crashing VM has masquerade binding?

**Comment by mzzgaopeng** [comment]
> 

We support bridge network mode by adjusting the code. not use masquerade mode.

**Comment by mzzgaopeng** [comment]
https://github.com/kubevirt/kubevirt/blob/main/pkg/network/dhcp/serverv6/serverv6.go#L76
On DHCPV4, the source mac is judged, but on DHCPV6, the source mac is not judged.

https://github.com/kubevirt/kubevirt/blob/main/pkg/network/dhcp/server/server.go#L190

I think here is the problem

**Comment by AlonaKaplan** [comment]
Yes, the DHCPv6 server is supposed to run on masquerade binding:) There you don't have l2 connectivity, so there is no need to check the MAC. The bridge that the DHCPv6 server is running on has only one port - the connection to the VM.
Why do you adjust the code? So that bridge binding will have a DHCPv6 server?
In this case, yes, you need to check the MAC or think of another way to filter out irrelevant DHCP requests.

**Comment by mzzgaopeng** [comment]
> Yes, the DHCPv6 server is supposed to run on masquerade binding:) There you don't have l2 connectivity, so there is no need to check the MAC. The bridge that the DHCPv6 server is running on has only one port - the connection to the VM. Why do you adjust the code? So that bridge binding will have a DHCPv6 server? In this case, yes, you need to check the MAC or think of another way to filter out irrelevant DHCP requests.

I am using a bridge network, which supports IPv6 at the same time. I encountered such a panic in IPv6dhcp, so I made some adjustments, referring to dhcpV4.
I think the follow-up community supports the bridge network model, here is what needs to be adjusted.

**Comment by AlonaKaplan** [comment]
kubevirt doesn't have DHCPv6 support for bridge binding. The virt-launcher run DHCv6 server only for masquerade.
So there are several options -
1. kubevirt has a bug and for some reason it is running a DHCPv6 server for bridge binding.
2. The cluster has a VM with masquerade binding and somehow it answers to DHCPv6 request of another VM with bridge binding. 
3. The code was changed to run a DHCPv6 server for bridge binding.

Which one of the options is the correct one? If 1 or 2 it would be helpful to get the information I"ve asked for in previous [comment](https://github.com/kubevirt/kubevirt/issues/8034#issuecomment-1177275662).

**Comment by EdDev** [comment]
@mzzgaopeng , issues opened against the project are expected to have been checked against the upstream version mentioned (e.g. 0.46 is this case).

We will fix the error handling, but cannot assist in solving a problem of a downstream solution.

You are welcome to propose the options to support DHCPv6 support for bridge binding to the project, I am sure other users will see benefit in this.

We are closing the issue for now. Please let us know if we misunderstood the situation and we can re-open this issue or you can open a new one.
