### ISSUE TITLE
Unable to see kubevirt metrics information in prometheus

### ISSUE THREAD

**Issue by knitanurag** [kubevirt/kubevirt#8044]
No clear information given in the doc to deploy and test monitoring for vm via kubevirt. 

**What happened**:
Unable to see the metrics and monitoring information for vm as well as for core components of the kubevirt.
Followed the doc given here : https://kubevirt.io/user-guide/operations/component_monitoring/

**What you expected to happen**:
I should be able to see kubevirt related metrics information via prometheus

**How to reproduce it (as minimally and precisely as possible)**:
1. Installed the prometheus with default namespace
![image](https://user-images.githubusercontent.com/13597410/177266851-9207c674-7e2f-40cb-89bd-d7ba6e73b190.png)

3. Downloaded and updated the kubevirt-cr.yml to support default namespace for prometheus
`apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  monitorNamespace: default
  monitorAccount: my-prometheus-operator-kub-prometheus
  configuration:
    developerConfiguration:
      featureGates: []
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
`
5. Installed kubevirt
6. Unable to see any kubevirt  kubevirt metrics

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.50.0
- Kubernetes version (use `kubectl version`): 1.18
- OS - Ubantu

**Comment by liyang516** [comment]
@knitanurag same problem, have you been resolve this problem?
