### ISSUE TITLE
I have some issues when I use KubeVirt Snapshot Restore API

### ISSUE THREAD

**Issue by muleimulei** [kubevirt/kubevirt#8046]
I can successfully create a vm, but I can only capture vm's configuration (such as its disk size).  Currently, I only can restore its configuration , but I can't restore its files by the snapshot.

when I use `kubectl get vm hello -o yaml`, the output is:
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    description: ""
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
    restore.kubevirt.io/lastRestoreUID: restore-hello-8472e5ae-1760-44e8-a2f1-56630d85ebf9
    tkestack.io/image-display-name: win16server
  creationTimestamp: "2022-07-05T00:12:52Z"
  generation: 5
  labels:
    kubevirt.io/domain: hello
  name: hello
  namespace: default
  resourceVersion: "29431648"
  uid: e6b91af2-3700-4677-b6cc-1ac60871e681
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: rootfs.hello
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 50Gi
        storageClassName: csi-cephfs-sc
        volumeMode: Filesystem
      source:
        pvc:
          name: win16img
          namespace: kube-public
  - metadata:
      creationTimestamp: null
      name: datavolume1.hello
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 50Gi
        storageClassName: csi-cephfs-sc
        volumeMode: Filesystem
      source:
        blank: {}
  running: false
  template:
    metadata:
      annotations:
        tkestack.io/image-display-name: win16server
      creationTimestamp: null
      labels:
        kubevirt.io/domain: hello
    spec:
      domain:
        cpu:
          cores: 1
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: rootfs
          - bootOrder: 2
            disk:
              bus: virtio
            name: datavolume1
          inputs:
          - bus: usb
            name: tablet
            type: tablet
          interfaces:
          - bridge: {}
            model: virtio
            name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 1G
      networks:
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: rootfs.hello
        name: rootfs
      - dataVolume:
          name: datavolume1.hello
        name: datavolume1
status:
  conditions:
  - lastProbeTime: "2022-07-05T00:23:53Z"
    lastTransitionTime: "2022-07-05T00:23:53Z"
    message: VMI does not exist
    reason: VMINotExists
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    message: cannot migrate VMI which does not use masquerade to connect to the pod
      network
    reason: InterfaceNotLiveMigratable
    status: "False"
    type: LiveMigratable
  printableStatus: Stopped
  volumeSnapshotStatuses:
  - enabled: false
    name: rootfs
    reason: 'No VolumeSnapshotClass: Volume snapshots are not configured for this
      StorageClass [csi-cephfs-sc] [rootfs]'
  - enabled: false
    name: datavolume1
    reason: 'No VolumeSnapshotClass: Volume snapshots are not configured for this
      StorageClass [csi-cephfs-sc] [datavolume1]'
```
**In the end on the above, it suggests me that `No VolumeSnapshotClass: Volume snapshots are not configured for this
      StorageClass [csi-cephfs-sc] [rootfs]`.**

**So How to configure ...,  Can someone help me? Please** 

At last, when I use `kubectl get volumesnapshotclass`, the output is
```
NAME                         DRIVER                DELETIONPOLICY   AGE
csi-cephfsplugin-snapclass   cephfs.csi.ceph.com   Delete           4d22h
```
when I use ```kubectl get sc```, the output is
```
NAME            PROVISIONER           RECLAIMPOLICY   VOLUMEBINDINGMODE   ALLOWVOLUMEEXPANSION   AGE
csi-cephfs-sc   cephfs.csi.ceph.com   Delete          Immediate           true                   39d
```

I am sure the ```provisioner property``` of ``` StorageClass``` matches the ```driver property``` of the ```VolumeSnapshotClass```.

**Comment by viveksinghggits** [comment]
Hi @muleimulei 
KubeVirt controller looks for VolumeSnapshotClass to be present in the `v1` version,  can you verify if the volume snapshot class is being served from v1 version?
https://github.com/kubevirt/user-guide/pull/552

**Comment by muleimulei** [comment]
Hi @[viveksinghggits](https://github.com/viveksinghggits)  
```
[root@node-2 mulei_dir]# kubectl get volumesnapshotclass -o yaml
apiVersion: v1
items:
- apiVersion: snapshot.storage.k8s.io/v1
  deletionPolicy: Delete
  driver: cephfs.csi.ceph.com
  kind: VolumeSnapshotClass
  metadata:
    annotations:
      kubectl.kubernetes.io/last-applied-configuration: |
        {"apiVersion":"snapshot.storage.k8s.io/v1","deletionPolicy":"Delete","driver":"cephfs.csi.ceph.com","kind":"VolumeSnapshotClass","metadata":{"annotations":{},"name":"csi-cephfsplugin-snapclass"},"parameters":{"clusterID":"05d7dd64-c075-4c86-9ed5-2773d1a56573","csi.storage.k8s.io/snapshotter-secret-name":"csi-cephfs-secret","csi.storage.k8s.io/snapshotter-secret-namespace":"tke"}}
    creationTimestamp: "2022-07-07T00:42:56Z"
    generation: 1
    name: csi-cephfsplugin-snapclass
    resourceVersion: "31008746"
    uid: c5a25f0c-6b9d-4953-ae4a-a15826f5b917
  parameters:
    clusterID: 05d7dd64-c075-4c86-9ed5-2773d1a56573
    csi.storage.k8s.io/snapshotter-secret-name: csi-cephfs-secret
    csi.storage.k8s.io/snapshotter-secret-namespace: tke
kind: List
metadata:
  resourceVersion: ""
  selfLink: ""
```

it's `v1 version`. Will it be related to the namespace? My KubeVirt controller is in `vm-manager` namespace , but my  volume snapshot controller is in `kube-system` namespace . I have no idea. Thanks for your reply.

**Comment by viveksinghggits** [comment]
I don't think snapshot-contrller being present is another namespace is going to be a problem.
I recommend you checking `virt-controller`'s logs.

**Comment by swq499809608** [comment]
1. Create vm is fail,  Error info .... 
Warning  FailedPvcNotFound  7m (x20 over 17m)  virtualmachine-controller  failed to render launch manifest: didn't find PVC 74v4-snap-os



2. Snap create is ok :

# kubectl  get pvc -n csi-ceph-rbd 
NAME               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
74v4               Bound    pvc-74a41d1b-d1a8-4d6c-b529-bef72243a3ca   38Gi       RWO            csi-rbd-sc     48m
74v4-snap-data     Bound    pvc-6c18b9bc-f545-49f4-88cc-8ceb95d0b904   100Gi      RWO            csi-rbd-sc     23m
74v4-snap-os       Bound    pvc-3f6fa67f-5449-435a-8e87-e8a3216b3efc   40Gi       RWO            csi-rbd-sc     24m

3. vm.yaml
[root@k8s-master-thallo-72-211-lf3 vv1]# cat 74v4-snap.yaml 
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: 74v4-snap
  namespace: k8s-vmi
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: 74v4-snap
    spec:
      terminationGracePeriodSeconds: 30
      domain:
        resources:
          requests:
            memory: 4096M
        devices:
          disks:
          - disk:
              bus: virtio
            name: 74v4-snap-os
          - disk:
              bus: virtio
            name: 74v4-snap-data
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - bridge: {}
            name: default
      networks:
        - name: default
          pod: {}
      volumes:
        - name: 74v4-snap-os
          persistentVolumeClaim:
            claimName: 74v4-snap-os
        - name: 74v4-snap-data
          persistentVolumeClaim:
            claimName: 74v4-snap-data
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              runcmd:
                - [ systemctl, restart, --no-block, salt-minion ]
