### ISSUE TITLE
VirtualMachinePresets are un-ordered

### ISSUE THREAD

**Issue by stu-gott** [kubevirt/kubevirt#805]
Currently, if a VirtualMachine resource matches multiple presets, KubeVirt does not impose any order to how they're applied. In cases where presets are orthogonal, this is a non-issue, but in cases where multiple presets mandate conflicting settings, the results are non-deterministic. It's not clear how big a problem this is because the feature is relatively new, and we don't yet have a clear picture of how presets will be used in the long run, but there are a couple of different strategies that we can use.

- Add a priority field to VirtualMachinePresets. This would offer users a clear and understandable way to mandate the order settings will be applied in.
- Simply dis-allow conflicts between presets, and raise an error if this occurs. If this approach is taken, we need to decide if the presets will be applied at all or if only the conflicting setting will be omitted.

Other possibilities that were previously discussed/rejected were:

- Use the name of the presets to order them. This idea was rejected because it's hard to control and can be un-intuitive.
- Alter the `Labels` field of VirtualMachines to impose strict ordering. This outright breaks a great many things so should be avoided.

**Comment by stu-gott** [comment]
Personally, I'm in favor of allowing presets to conflict with each other and resolving such a conflict using a priority field. This allows a use case of specifying a minimum system requirement (e.g. resource requirements), but allowing that to be overridden by more specific presets.

If we dis-allow preset conflicts altogether, then the above approach is not permissible, and would require using multiple presets.

/cc @rmohr, @davidvossel, @fabiand. Thoughts?

**Comment by davidvossel** [comment]
I recommend we reject preset conflicts.

If a non-theoretical use case emerges where users can not express their desired presets without conflicts, then we can add a priority field later on.

A priority field in this case would not be a change in default behavior, instead it would be an addition. Existing presets have a default priority after an update. Conflicts within a single priority are rejected. Users would have to explicitly give presets (that need the ability to override other presets) a higher priority to avoid rejection.

This lets us push users in the direction of not creating presets that conflict and see how that plays out.

**Comment by rmohr** [comment]
> Incidentally Kubernetes already has a precedent of priority fields in resources (for example when registering API versions--it's not always clear which handler should control any given REST endpoint).

Could you share an example or link?

**Comment by stu-gott** [comment]
Sorry, I should have provided context up front.

https://github.com/kubernetes/kubernetes/blob/master/cmd/kube-apiserver/app/aggregator.go#L209

https://github.com/kubernetes/kubernetes/pull/46800

https://github.com/kubernetes/kubernetes/issues/46322

**Comment by davidvossel** [comment]
> Users can already avoid the issue by not having conflicts--but if they do need to override something in a preset, why not give them a way to control it?

If a user wants to override the preset, they can in the VM Spec. I'm not convinced having presets that override presets is a necessary use-case yet.

In general, I'm always going to be in favor of the simplest approach until more complexity is justified. We can always add priorities in the future if we need them, however we can't take them away. 

Other than use cases we theorize, is there any precedent in a VM management platform for the (presets overriding presets) like behavior?

**Comment by rmohr** [comment]
Two main points why allowing conflicts right now is not a good idea from my side:

* Although the operator does not need to explicitly avoid conflicts in the presets he defines, he still needs to think about all the override possibilities, no matter if we allow him to write them with priorities or not (it just just less obvious at the end with priorities)
* The user (person or automated  process) who creates a vm has no reliable way to find out if a preset only got partially applied or not.

**Comment by stu-gott** [comment]
Decision point from today's community meeting: Presets should not be allowed to conflict with other Presets.
- If any conflicts occur between any Presets, no presets will be applied (they might depend on each other)
- If any conflicts occur and the VM's override, the presets still won't be applied (principle of least surprise)

We can implement explicit Preset prioritization at a future date if it turns out it's needed.

**Comment by rmohr** [comment]
I was surprised to see the following now implemented:
 * If a preset can't be applied, the vm gets to failed state (this means that I would have to choose my vm labels so that I don't by accident match a preset. My expectation for presets would be taht it applies something useful closed in iteself and if the user chooses something different it will just not be applied)
 * We don't check if a preset was already applied (no annotation check). This means that in the current implementation we would create a conflict with itself if we change an already applied image and repost such a vm.

**Comment by stu-gott** [comment]
@rmohr I don't understand what you mean by:
> My expectation for presets would be taht it applies something useful closed in iteself and if the user chooses something different it will just not be applied

The point of the failed state in this case is that if Presets failed altogether, the VM is almost certainly not in a healthy or expected state anymore. Especially with respect to Persistent Volumes.

> We don't check if a preset was already applied (no annotation check)
The overall VM won't fail or conflict in such a case because there is an annotation check. We use the `presets-applied` annotation to determine if presets were previously applied and thus skip the entire Preset process. My understanding was this was the intended design--that future modifications to a VM wouldn't cause unexpected behaviors.

**Comment by stu-gott** [comment]
https://github.com/kubevirt/kubevirt/pull/986 addresses the reason this was re-opened.

**Comment by itamarh** [comment]
@stu-gott #986 allow to exclude, not set order. which means i can't get multiple behaviors.
I don't know if we designed presets to inherit from each other, but ordering would allow me to define my default say, windows behavior in a preset to e1000, but also benefit from "high performance preset", which overrides it to virt-io, but not having to re-specify all other configs of any other preset which is applied to the vm?
