### ISSUE TITLE
docs/direct-pv-disks.md should be removed

### ISSUE THREAD

**Issue by crazytaxii** [kubevirt/kubevirt#8088]
**Description**:
The [disk schema](https://github.com/kubevirt/api/blob/v0.54.0/core/v1/schema.go#L543-L580) is totally different: `type` and `source` field are no longer existed. This document will miss lead others.

**What you expected**:
Remove docs/direct-pv-disks.md.

**URL**:
[docs/direct-pv-disks.md](https://github.com/kubevirt/kubevirt/blob/main/docs/direct-pv-disks.md)

**Comment by xpivarc** [comment]
Alternatively, we can reflect current reality there. Pinging author @fabiand
