### ISSUE TITLE
Can't get "virtctl vnc..." running on OSX

### ISSUE THREAD

**Issue by slintes** [kubevirt/kubevirt#812]
Hi,

I installed the kubevirt demo on a remote cluster. Everything seems to run fine, `virtctl console ...` works, but I can't get `virtctl vnc ...` running. A window is opening and showing these errors: first "Unknown graphic type for the guest vnc://127.0.0.1:55073", and after a click on `ok` "Couldn't create a session for this type: vnc".

For getting so far I installed the Spice OSX client (https://www.spice-space.org/osx-client.html), and added a script named `remote-viewer` to my PATH, which just calls the OSX binary with `/Applications/RemoteViewer.app/Contents/MacOS/RemoteViewer "$@"`.

Do I need to install more?

**Comment by fabiand** [comment]
Good question.

Virtctl is just setting up a proxy, and then relying on the presence of a VNC client to connect to the VM.
This probably does not work on Mac.

Patches are welcome - although we also discussed a different approach to actually just do the proxy functionaliyt in virtctl and then let the user cnnect the client to it. See #806

**Comment by slintes** [comment]
Got it working :) At least with manual steps:

- install the "Chicken" VNC viewer (https://sourceforge.net/projects/chicken/)
- have a script `remote-viewer` on your PATH, which opens Chicken
- it also shows an error message with the `vnc://127.0.0.1:12345` URL :/
- but you can use the `127.0.0.1:12345` part for manually connecting Chicken to the server, it just can't deal with the protocol part

Maybe it is an idea to try starting `remote-viewer`,  but when it fails (`exec: "remote-viewer": executable file not found in $PATH`) just print the URL?

**Comment by mlsorensen** [comment]
You can edit your remote-viewer script to strip out the vnc://

```
$ cat /usr/local/bin/remote-viewer
#!/bin/bash
HOSTPORT=${1//vnc:\/\/}
/Applications/Chicken.app/Contents/MacOS/Chicken $HOSTPORT
```

If a known VNC password were set in the libvirt XML it would be trivial for virtctl to just call 'open vnc://user:${pass}@localhost:${port} instead of remote-viewer when it detects GOOS == darwin, no Chicken necessary. The built-in VNC viewer requires a password to be provided. I'm not sure if remote-viewer accepts a vnc://user:pass@ URL.

**Comment by mlsorensen** [comment]
it looks like remote-viewer does not support vnc://user:pass@ URL format. Without setting a VNC password the built-in Mac VNC client won't connect, and it seems the various Linux VNC clients require a few extra hoops to utilize a VNC password. 

It would be nice to revisit VNC password and try to come up with a cross-platform compatibility, however I imagine this is pretty low priority. It seems the best short term solution for Mac compatibility without breaking Linux is to keep using a script like the one in my last comment and install a third party VNC client.

**Comment by xsgordon** [comment]
I believe we want to be consistent with kubectl, oc, etc. here and ensure that the client works on OS/X, even if it is lower priority in the immediate term.

**Comment by fabiand** [comment]
@mlsorensen sounds good to me for now.

We could actually raise an info in the end to highlight to install one of those.

**Comment by fabiand** [comment]
@mlsorensen do you eventually have a patch or s script for the approach mentioned in the comment above?

**Comment by mlsorensen** [comment]
Eventually :-). Right now we are just distributing virtctl with homebrew and and bundling the remote-viewer bash script with it. It's a short term band-aid but makes this a lower priority at the moment.

**Comment by fabiand** [comment]
Sounds pretty practical :)

Can you share the script itself, then we can see how to bundle it.

**Comment by slintes** [comment]
I'd like to revive the PR
