### ISSUE TITLE
delete kubevirt

### ISSUE THREAD

**Issue by guleng** [kubevirt/kubevirt#8131]
I tried to clean kubevirt according to this document http://kubevirt.io/user-guide/operations/updating_and_deletion/#deleting-kubevirt, but failed to clean it up, and only created the virt operator service when deploying again, but failed to create other services.
![image](https://user-images.githubusercontent.com/40238640/179966125-ba12c749-933e-4c15-8453-e662eeaed53f.png)
Is there a way to clean it up?

kubevirt version 0.55

There is also the ability to update the new version of the document to http://kubevirt.io/ Here? I think they are all old versions of documents.

**Comment by simonyangcj** [comment]
hi, guleng. It seems like the validation webhook not been delete yet. Simply run command `kubectl delete validatingwebhookconfigurations virt-operator-validator` will solve you problem :)

**Comment by guleng** [comment]
@simonyangcj  Thank you very much. I have deleted it, but there is still a lot of information about kubevirt in kubectl describe node. How to clean it up? This makes it impossible to create (virt launcher, virt API, virt controller) when I redeploy kubevirt. Only virt operator.
![image](https://user-images.githubusercontent.com/40238640/180117655-5aadf57a-bf35-471f-a764-2e13449df082.png)

**Comment by simonyangcj** [comment]
This is weird, normally virt-handler response for registry these device to kubelet over /var/lib/kubelet/device-plugins/kubelet.sock,I think you can try to restart the kubelet. Hope it help
