### ISSUE TITLE
[debugging] [supportability] Make log verbosity changes more natural

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#8155]
**Is your feature request related to a problem? Please describe**:

KubeVirt offers pretty nice support for dynamic log verbosity changing. However if one does not do that very often it always means looking up the documentation and editing the KubeVirt CR. This is cumbersome.

**Describe the solution you'd like**:

Let's add a nice command for changing log verbosity:

```
virtctl adm log-verbosity 3 --all
virtctl adm log-verbosity 3 --virt-handler --virt-controller
virtctl adm log-verbosity --reset
virtctl adm log-verbosity 2 --vmi <myvm>
```

**Describe alternatives you've considered**:

**Additional context**:

**Comment by xpivarc** [comment]
I like the `adm` part but I disagree with the "one needs to look up documentation". Our resources should be `desribe`-able and hopefully, the description should guide users.

**Comment by rmohr** [comment]
> Our resources should be `desribe`-able and hopefully, the description should guide users.

It never replaced a good simple commandline argument or good examples where I can copy-pase parts into my yamls. It is for sure better than nothing :)

**Comment by xpivarc** [comment]
/reopen
This would be a "good first issue".

**Comment by hrittikhere** [comment]
Can I get this assigned?

**Comment by hrittikhere** [comment]
I would like to work on this issue

**Comment by hshitomi** [comment]
Hi, Could you please assign me to this issue?
