### ISSUE TITLE
Make a convention for log verbosity levels

### ISSUE THREAD

**Issue by iholder101** [kubevirt/kubevirt#8164]
**Description**:
Today we have verbosity levels in Kubevirt. In Kubevirt CR it's possible to set the desired verbosity level for each component (e.g. `virt-handler`, `virt-controller`, etc).

It seems that there is no clear convention regarding what each verbosity level represents.

**What you expected**:
To have a document determining the different verbosity levels and their meaning.

Kubernetes uses something similar to:
```
0: No logs
1: Warnings
2: Debug
3: Errors
```

We can standardize that as a start. We should also introduce constants in-code and replace the literal values (`log.V(2)`) with constants (`log.V(DEBUG)`).

In the future, we might want to take a non-linear approach and let users specify exactly what they want to see. I'm imagining something like `withLibvirtLogs`, `withLiveMigrationPhases`, etc. But as a start we at least need to make a standard of the current position.

**Comment by victortoso** [comment]
I want to dive a little into KubeVirt logs  and I think working on this issue would help.  Is it fine for me to take it? @iholder101

**Comment by iholder101** [comment]
> I want to dive a little into KubeVirt logs and I think working on this issue would help. Is it fine for me to take it? @iholder101

Yes indeed! Thanks for doing so!
Feel free to ping me about anything :+1:

**Comment by victortoso** [comment]
Hi, finally got time to this!

>We can standardize that as a start. We should also introduce constants in-code and replace the literal values (log.V(2)) with constants (log.V(DEBUG)).

What is confusing to me is that we have both `Verbosity` and `Levels` (besides being structured!). Based on the [log filtering logic](https://github.com/kubevirt/kubevirt/blob/main/staging/src/kubevirt.io/client-go/log/log.go#L185) we should only use verbosity level for `Info Level` itself, while we might tweak/enable other log components based on how high is verbosity is. (k8s docs seems to say something similar about `-v command line option` [here](https://kubernetes.io/docs/concepts/cluster-administration/system-logs/#log-verbosity-level) plus this quote in JSON log format `v - verbosity (only for info and not for error messages, int)`)

So, I'll start with the following:

1. V() should only be used for Info messages as we display for >= WARNING levels anyway
2. Add some verbosity constants and changing the code to follow it
3. Add some documentation about above items

**Comment by EdDev** [comment]
Hi, nice initiative!

I would recommend to think of how to enforce it as well.
While this is cleaned up and organized, in parallel new such things can get in.
