### ISSUE TITLE
Add `virtctl expose`

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#818]
Today a user needs to know a VMs od name in order to expose it's port.

This is described here: https://github.com/kubevirt/user-guide/pull/38

A `virtctl expose` subcommand with flags similar to `kubectl expose` could improve the situation.

**Comment by simon3z** [comment]
@fabiand @vladikr anyone working on this?

**Comment by simon3z** [comment]
cc @yuvalif

**Comment by fabiand** [comment]
Gargh, not a dupe.
