### ISSUE TITLE
watchdog: BUG: soft lockup - CPU#X stuck for 23s

### ISSUE THREAD

**Issue by talcoh2x** [kubevirt/kubevirt#8194]
**What happened**:
start  0.48.1 I start to get watchdog: BUG: soft lockup sometimes directly after VM creation.
I did a couple of tests 0.47.1 works well and it starts to fail from 0.48.1 
my suspect is https://github.com/kubevirt/kubevirt/pull/6162
we run VMs with dual NUMA node so maybe we have "starvation" in such case ( I have 1T GB memory and ~500GB assigned to VM )  which block the CPU.

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
create a VM on KVM server with more than 750GB total RAM you should see it immediately

**Additional context**:

**Environment**:
tested on k8s 1.19, 1.20.15, 1.22.8 (same results)
KV version: 0.47.1  and below working 
KV version: 0.48.1 and above fail

**Comment by talcoh2x** [comment]
Spec:
  Affinity:
    Node Affinity:
      Required During Scheduling Ignored During Execution:
        Node Selector Terms:
          Match Expressions:
            Key:       habana.ai/cluster
            Operator:  In
            Values:
              cluster-staging
    Pod Anti Affinity:
      Required During Scheduling Ignored During Execution:
        Label Selector:
          Match Expressions:
            Key:       habana.ai/is-container
            Operator:  In
            Values:
              true
        Topology Key:  kubernetes.io/hostname
  Domain:
    Cpu:
      Cores:                    38
      Dedicated Cpu Placement:  true
      Model:                    host-passthrough
      Sockets:                  2
      Threads:                  2
    Devices:
      Block Multi Queue:  true
      Disks:
        Dedicated IO Thread:  true
        Disk:
          Bus:  virtio
        Name:   localdisk
        Disk:
          Bus:  virtio
        Name:   cloud-init
      Filesystems:
        Name:  disk0
        Virtiofs:
        Name:  disk1
        Virtiofs:
      Gpus:
        Device Name:  habana.ai/gaudi
        Name:         gpu0
        Device Name:  habana.ai/gaudi
        Name:         gpu1
        Device Name:  habana.ai/gaudi
        Name:         gpu2
        Device Name:  habana.ai/gaudi
        Name:         gpu3
        Device Name:  habana.ai/gaudi
        Name:         gpu4
        Device Name:  habana.ai/gaudi
        Name:         gpu5
        Device Name:  habana.ai/gaudi
        Name:         gpu6
        Device Name:  habana.ai/gaudi
        Name:         gpu7
      Interfaces:
        Name:  sriov-net
        Sriov:
        Name:  sriov-net1
        Sriov:
        Name:  sriov-net2
        Sriov:
        Name:  sriov-net3
        Sriov:
        Name:  sriov-net4
        Sriov:
      Network Interface Multiqueue:  true
    Features:
      Acpi:
        Enabled:  true
    Firmware:
      Uuid:             e58e152d-5375-55ca-a66d-5e8395f3dfee
    Io Threads Policy:  auto
    Machine:
      Type:  q35
    Memory:
      Guest:  480Gi
      Hugepages:
        Page Size:  2Mi
    Resources:
      Requests:
        Memory:  520Gi
  Networks:
    Multus:
      Network Name:  habana/sriov-net
    Name:            sriov-net
    Multus:
      Network Name:  habana/sriov-net-x5
    Name:            sriov-net1
    Multus:
      Network Name:  habana/sriov-net-x5
    Name:            sriov-net2
    Multus:
      Network Name:  habana/sriov-net-x5
    Name:            sriov-net3
    Multus:
      Network Name:  habana/sriov-net-x5
    Name:            sriov-net4

**Comment by usrbinkat** [comment]
Thank you for raising this issue.


As I understand from the related [community discussion](https://kubernetes.slack.com/archives/C8ED7RKFE/p1658745712500509) this may be a bug in the underlying lvm virtualization stack. Is this a bug you have tried to reproduce with KVM directly and without KubeVirt to identify if the bug is reproducible without KubeVirt?

**Comment by talcoh2x** [comment]
which BUG? BTW, KV working fine until 0.48 so maybe someone can check what can be the reason maybe new kernel params or something that was added. I suspect on: https://github.com/kubevirt/kubevirt/pull/6162

 on BM servers we dont have such issue at all.
