### ISSUE TITLE
Libvirt ListWatch should add reason to virtwrap.DomainStatus

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#82]
Currently we are only collecting the Domain state and store it in virtwrap.DomainStatus.

We should also add the reason why the state was entered by the VM. Of special interest are the states  

[virDomainShutdownReason](https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainShutdownReason) and [virDomainShutoffReason](https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainShutoffReason).

They should be translated to a go constant and stored in a new field `virtwrap.DomainStatus.Reason`.

Currently the state is determined in [cache.go#L36](https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-handler/virtwrap/cache/cache.go#L36]).

This is a prerequisite to #75.

**Comment by mpolednik** [comment]
On it.
