### ISSUE TITLE
Add ability to watch Kubevirt objects

### ISSUE THREAD

**Issue by iholder101** [kubevirt/kubevirt#8200]
Currently, Kubevirt client set does not support watch calls, e.g.:
```go
virtClient.Kubevirt(namespace).Watch(...)
```

Also, while some of our clients are auto-generated (e.g. [clone client](https://github.com/kubevirt/kubevirt/blob/v0.55.0/staging/src/kubevirt.io/client-go/generated/kubevirt/clientset/versioned/typed/clone/v1alpha1/virtualmachineclone.go)), the [Kubevirt client](https://github.com/kubevirt/kubevirt/blob/v0.55.0/staging/src/kubevirt.io/client-go/kubecli/kv.go) is not.

Unless there's a good reason for it, I guess it should be auto-generated.
If not, at least it should support the ability to watch the object.

**Advantages:**
The ability to watch Kubevirt will help us gain better ability to test Kubevirt. In [this PR](https://github.com/kubevirt/kubevirt/pull/8184), for example, I needed to consistently `.Get(...)` Kubevirt instead of watching it. In this specific case it the change can happen very quickly, so the polling is done frequently, which is wasteful.

This can speed up our tests suit in general. Many tests today are continuously fetching the Kubevirt resource to perform checks.

**Comment by davidvossel** [comment]
> Is there a reason why the kubevirt client is not auto-generated?

how would this impact some of our custom apis, like ssh, console, pause, etc...

> Is there a reason not to auto-generate it now?

as long as we maintain parity with the existing client, sounds great

**Comment by rmohr** [comment]
I found no good way to add our subresources since they are served on a separate subgroup since CRDs don't support custom subresources.

**Comment by xpivarc** [comment]
@iholder-redhat 
Adding the missing `Watch` makes sense. Do you intend to work on it?

**Comment by iholder-redhat** [comment]
> @iholder-redhat Adding the missing `Watch` makes sense. Do you intend to work on it?

@xpivarc 
Not in the near future as my plate is pretty full at the moment. If you would like to implement it - be my guest :)
If you don't want to work on it I'll do it once I find the time

**Comment by rmohr** [comment]
> This can speed up our tests suit in general. Many tests today are continuously fetching the Kubevirt resource to perform checks.

Having Watch calls for our clients sounds good to me.

I am however pretty happy with the Eventually calls. They are super-simple and reliable. I don't think we need to change this. Consider running 10 tests in parallel, they would  right now by default do 10 REST calls every second, in case they would all try to get the KubeVirt CR and wait for something there (which should not be the case). That are super-low request rates and are not a problem. :)

**Comment by iholder101** [comment]
> > This can speed up our tests suit in general. Many tests today are continuously fetching the Kubevirt resource to perform checks.
> 
> Having Watch calls for our clients sounds good to me.
> 
> I am however pretty happy with the Eventually calls. They are super-simple and reliable. I don't think we need to change this. Consider running 10 tests in parallel, they would right now by default do 10 REST calls every second, in case they would all try to get the KubeVirt CR and wait for something there (which should not be the case). That are super-low request rates and are not a problem. :)

Thanks @rmohr, I completely agree that it's far from being our top priority at the moment :)
Since this issue is probably going to rot anyways, I'll close it. We can always re-visit this in the future.

/close
