### ISSUE TITLE
Kubevirt on ARM64 Installation and  hybird kubevirt vms support?

### ISSUE THREAD

**Issue by thunderZH963** [kubevirt/kubevirt#8224]
https://github.com/kubevirt/kubevirt/issues/3558 and https://kubevirt.io/user-guide/operations/installation/#experimental-arm64-developer-builds help me to run virt-operator successfully. But, I still not know how to install or get virtctl (maybe binary file)?
And my cluster includes arm/x86 worker(nodes), how to support this  hybird  cluster?

**Comment by thunderZH963** [comment]
and "kubectl apply -f https://kubevirt.io/labs/manifests/vm.yaml", than, "console testvm" , blocked. why?

**Comment by thunderZH963** [comment]
> and "kubectl apply -f https://kubevirt.io/labs/manifests/vm.yaml", than, "console testvm" , blocked. why?

master is x86, so virtctl-amd64 is used to start vm. "kubectl get pods" shows that vm is scheduled to arm node and stay in running state. but "console" shows "The escape sequence is ^]" than blocked.

**Comment by thunderZH963** [comment]
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory')","pos":"libvirt.go:505","timestamp":"2022-08-01T04:33:31.430248Z"}
{"component":"virt-launcher","level":"info","msg":"libvirt version: 8.0.0, package: 2.module_el8.6.0+1087+b42c8331 (CentOS Buildsys \u003cbugs@centos.org\u003e, 2022-02-08-22:21:58, )","subcomponent":"libvirt","thread":"43","timestamp":"2022-08-01T04:33:31.469000Z"}
{"component":"virt-launcher","level":"info","msg":"hostname: testvm","subcomponent":"libvirt","thread":"43","timestamp":"2022-08-01T04:33:31.469000Z"}
{"component":"virt-launcher","level":"error","msg":"Cannot find 'dmidecode' in path: No such file or directory","pos":"virExec:636","subcomponent":"libvirt","thread":"43","timestamp":"2022-08-01T04:33:31.469000Z"}
{"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:513","timestamp":"2022-08-01T04:33:31.936456Z"}
{"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:510","timestamp":"2022-08-01T04:33:31.951675Z"}
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:74","timestamp":"2022-08-01T04:33:31.952524Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Executing PreStartHook on VMI pod environment","name":"testvm","namespace":"default","pos":"manager.go:512","timestamp":"2022-08-01T04:33:32.554189Z","uid":"f917a49e-afc5-4d73-b227-5fc1ef7f19d9"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Starting PreCloudInitIso hook","name":"testvm","namespace":"default","pos":"manager.go:533","timestamp":"2022-08-01T04:33:32.554379Z","uid":"f917a49e-afc5-4d73-b227-5fc1ef7f19d9"}
{"component":"virt-launcher","level":"info","msg":"Found nameservers in /etc/resolv.conf: \n`\u0000\n","pos":"network.go:289","timestamp":"2022-08-01T04:33:32.556087Z"}

**Comment by usrbinkat** [comment]
Thank you for raising this.

At this time, arm64 support is experimental. Hybrid/mixed arch cluster support is on the roadmap though so be sure to watch for that.

If you were asking about virtctl support, it is currently only built and published for amd64 architectures as well.

**Comment by zhlhahaha** [comment]
This comment may help you https://github.com/kubevirt/kubevirt/issues/8894#issuecomment-1340976972

**Comment by xpivarc** [comment]
/reopen
@thunderZH963 As for the console issue you might want to try vnc to see if the OS is stuck somewhere. Regarding the question of hybrid cluster support... we are still in the process to support ARM and there is already work to support multiarch clusters.

**Comment by lobshunter** [comment]
I would like to deploy kubevirt in hybird cluster too. I compared deployment manifests between amd64 and arm64, the only difference I found is the container image. So can I build multi-arch image to make it work? If not, is there any public materials I can follow the progress? Thanks.

**Comment by zhlhahaha** [comment]
> I would like to deploy kubevirt in hybird cluster too. I compared deployment manifests between amd64 and arm64, the only difference I found is the container image. So can I build multi-arch image to make it work? If not, is there any public materials I can follow the progress? Thanks.

You can try to apply this PR, 
https://github.com/kubevirt/kubevirt/pull/8989

To build multi-arch image, just run 
```
wget https://github.com/kubevirt/kubevirt/pull/8989.patch
git am 8989.patch
BUILD_ARCH=crossbuild-aarch64,x86_64 DOCKER_PREFIX=your_image_repository DOCKER_TAG=multiarch make bazel-push-images
```
