### ISSUE TITLE
oc patch offlinevm

### ISSUE THREAD

**Issue by vatsalparekh** [kubevirt/kubevirt#826]
I created a VM (without option to boot it on creation, so an offline vm) from ManageIQ.
And then I tried to do `oc patch ovms vparekh-test-321 -p '{"spec":{"running":true}}' --type=merge -n default`
It doesn't seem to be working, 
`oc get vm vparekh-test -n default` returns
`Error from server (NotFound): virtualmachines.kubevirt.io "vparekh-test" not found`

**Comment by vatsalparekh** [comment]
@pkliczewski

**Comment by stu-gott** [comment]
@vatsalparekh Could you post the output of `oc get ovms vparekh-test-321 -o yaml`?

Does a message along the lines of "Invalid controller spec, will not re-enqueue." appear in the virt-controller log after you create the offlinevirtualmachine?

/cc @petrkotas

**Comment by vatsalparekh** [comment]
@stu-gott 
```bash
[fedora@vparekh-openshift-latest ~]$ oc get ovms vparekh-test-321 -o yaml -n default
apiVersion: kubevirt.io/v1alpha1
kind: OfflineVirtualMachine
metadata:
  clusterName: ""
  creationTimestamp: 2018-03-19T10:19:46Z
  generation: 0
  name: vparekh-test-321
  namespace: default
  resourceVersion: "357066"
  selfLink: /apis/kubevirt.io/v1alpha1/namespaces/default/offlinevirtualmachines/vparekh-test-321
  uid: 0c347b60-2b5f-11e8-940d-fa163e9c0809
spec:
  running: true
  template:
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - disk:
              dev: vda
            name: registrydisk
            volumeName: registryvolume
          - disk:
              dev: vdb
            name: cloudinitdisk
            volumeName: cloudinitvolume
        machine:
          type: q35
        resources:
          requests:
            memory: 1024Mi
      volumes:
      - name: registryvolume
        registryDisk:
          image: kubevirt/fedora-cloud-registry-disk-demo:latest
      - cloudInitNoCloud:
          userDataBase64: I2Nsb3VkLWNvbmZpZwpwYXNzd29yZDogYXRvbWljCnNzaF9wd2F1dGg6IFRydWUKY2hwYXNzd2Q6IHsgZXhwaXJlOiBGYWxzZSB9Cg==
        name: cloudinitvolume
```

**Comment by stu-gott** [comment]
@vatsalparekh what I generally do is `kubectl --namespace kube-system get pods` and visually look for the correct one. Then follow that up with `kubectl --namespace kube-system logs <pod_name>`

Glancing at that spec, I believe it is being rejected. The Labels field is required. Unfortunately the logs aren't going to explicitly say this is the issue. See: https://github.com/kubevirt/kubevirt/pull/820

**Comment by pkliczewski** [comment]
I can confirm that it is not working for me as well when using `v0.3.0`

**Comment by rmohr** [comment]
> oc get vm vparekh-test -n default returns

@vatsalparekh Probably just a copy past error, but following your given example the vm you will have to look for is called `vparekh-test-321` and not `parekh-test`.

**Comment by petrkotas** [comment]
@vatsalparekh I confirm, you are missing the Labels. You can look at the `cluster/my-ovm.yaml` to see how it should look.

**Comment by rmohr** [comment]
@petrkotas are you sure about the labels? Afaik we are only using the name and no labels.

**Comment by petrkotas** [comment]
@rmohr I am not 100% sure. However, I remember the `metadata.labels` required to be present, otherwise it fail.

I will double check it, and write test for it. I believe we are missing test for missing labels.

**Comment by petrkotas** [comment]
@pkliczewski @vatsalparekh just occured to me. What openshift version are you running?

**Comment by vatsalparekh** [comment]
@petrkotas 3.9

**Comment by karmab** [comment]
i can confirm that spec/template/metadata/labels is required for the ovm to be processed

**Comment by fabiand** [comment]
@karmab are you saying this is fixing the issue for you?

**Comment by karmab** [comment]
yes

**Comment by rmohr** [comment]
@petrkotas seems like this validation is wong: https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-controller/watch/ovm.go#L138

We don't need labels on the vm.

**Comment by petrkotas** [comment]
@rmohr I see. Creating issue for it.

**Comment by rmohr** [comment]
@petrkotas this issue should be good enough.

**Comment by petrkotas** [comment]
@rmohr ack, good job.

**Comment by gouyang** [comment]
I can still see this issue on openshift 3.9, the vm is not found after patch ovm to `running`.

```
# oc apply -f my-ovm.yaml 
offlinevirtualmachine "my-vm" created
# oc patch ovm my-vm --type merge -p '{"spec":{"running":true}}'
offlinevirtualmachine "my-vm" patched
# oc get vm --all-namespaces
No resources found.
# oc get ovm my-vm -o yaml
apiVersion: kubevirt.io/v1alpha1
kind: OfflineVirtualMachine
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubevirt.io/v1alpha1","kind":"OfflineVirtualMachine","metadata":{"annotations":{},"labels":{"kubevirt.io/my":"label"},"name":"my-vm","namespace":"golden-images"},"spec":{"running":false,"template":{"metadata":{"labels":{"kubevirt.io/my":"label"}},"spec":{"domain":{"devices":{"disks":[{"disk":{"bus":"virtio"},"name":"registrydisk","volumeName":"registryvolume"},{"disk":{"bus":"virtio"},"name":"cloudinitdisk","volumeName":"cloudinitvolume"}]},"resources":{"requests":{"memory":"64M"}}},"volumes":[{"name":"registryvolume","registryDisk":{"image":"kubevirt/cirros-registry-disk-demo:latest"}},{"cloudInitNoCloud":{"userDataBase64":"SGkuXG4="},"name":"cloudinitvolume"}]}}}}
  clusterName: ""
  creationTimestamp: 2018-04-02T07:13:19Z
  generation: 0
  labels:
    kubevirt.io/my: label
  name: my-vm
  namespace: golden-images
  resourceVersion: "27147"
  selfLink: /apis/kubevirt.io/v1alpha1/namespaces/golden-images/offlinevirtualmachines/my-vm
  uid: 521903e6-3645-11e8-a0ab-44a842130afe
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/my: label
    spec:
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: registrydisk
            volumeName: registryvolume
          - disk:
              bus: virtio
            name: cloudinitdisk
            volumeName: cloudinitvolume
        resources:
          requests:
            memory: 64M
      volumes:
      - name: registryvolume
        registryDisk:
          image: kubevirt/cirros-registry-disk-demo:latest
      - cloudInitNoCloud:
          userDataBase64: SGkuXG4=
        name: cloudinitvolume
```

```
# oc version
oc v3.9.0-alpha.4+9ab7a71
kubernetes v1.9.1+a0ce1bc657
features: Basic-Auth GSSAPI Kerberos SPNEGO

Server 
openshift v3.9.0-alpha.4+9ab7a71
kubernetes v1.9.1+a0ce1bc657
```
