### ISSUE TITLE
Confusing Test Case

### ISSUE THREAD

**Issue by zhuchenwang** [kubevirt/kubevirt#8269]
Hi there,

I am trying to understand this [test case](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-handler/vm_test.go#L581). From my understanding, the scenario is that the domain doesn't exist and the VMI should be removed but not yet finalized.

By following the code, it think the logic would fall into this [case](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-handler/vm.go#L1690). However, since the VMI is not finalized, instead of processing the VM cleanup, the code below will process the VM update, which seems to be contradictory with the test case description.

Please let me know if I misunderstood anything.

Thanks in advance.

**Comment by jean-edouard** [comment]
The test was introduced 2 years ago by this PR: https://github.com/kubevirt/kubevirt/pull/3952
@davidvossel any chance you could shed some light on this? Thanks!

**Comment by davidvossel** [comment]
> I am trying to understand this [test case](https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-handler/vm_test.go#L581). From my understanding, the scenario is that the domain doesn't exist and the VMI should be removed but not yet finalized.

I think the testcase description might actually be a typo.

`should do final cleanup if vmi is being deleted and not finalized` should probably read `should not do final cleanup if vmi is being deleted and not finalized`

the goal of the test is to ensure that the local data related to the VMI is not removed unless the vmi reaches a finalized state (phase=Succeeded|Failed)

**Comment by zhuchenwang** [comment]
I see. That makes sense. Thank you for the clarification.
