### ISSUE TITLE
Why virt-api to be deployed in minion?

### ISSUE THREAD

**Issue by lixiaobing1** [kubevirt/kubevirt#8289]
Two nodes in cluster, one master, one minion, and two virt-apis, one deployed in master, why another virt-api deployed to minion? There is podAntiAffinity in virt-api yaml, is this normal?

**Comment by usrbinkat** [comment]
Thank you for reporting your issue.

My first guess would be to re-evaluate taint/tolleration config on the master nodes to ensure the noschedule taint is still present on the master where your virt-api scheduled.

**Comment by lixiaobing1** [comment]
> 



> Thank you for reporting your issue.
> 
> My first guess would be to re-evaluate taint/tolleration config on the master nodes to ensure the noschedule taint is still present on the master where your virt-api scheduled.

But there is also one virt-api deployed in master, and I think virt-api is used to receive request from out of cluster, it should it be deployed to master.

**Comment by xpivarc** [comment]
Hi @lixiaobing1, Virt-api (also controller) is deployed in pairs for availability, and with that comes that they should not run on the same node.

**Comment by lixiaobing1** [comment]
> Hi @lixiaobing1, Virt-api (also controller) is deployed in pairs for availability, and with that comes that they should not run on the same node.

But if virt-api is deployed in minion, can it receive request?
