### ISSUE TITLE
virtctl ssh and portforward are broken when vm name has a dot in it

### ISSUE THREAD

**Issue by roblabla** [kubevirt/kubevirt#8290]
**What happened**:
I have a VM that has dots in its name (it is named `vm-windows10-x64.roblabla-vm`). It lives in the default namespace. It is currently impossible to connect to it via ssh:

```
$ virtctl ssh vm-windows10-x64.roblabla-vm
You are using a client virtctl version that is different from the KubeVirt version running in the cluster
Client Version: v0.53.0
Server Version: v0.49.0
can't access VMI vm-macos12-x64: virtualmachineinstance.kubevirt.io "vm-macos12-x64" not found
```

Even when explicitly specifying the namespace, it still fails

```
$ virtctl ssh --namespace default vm-windows10-x64.roblabla-vm
You are using a client virtctl version that is different from the KubeVirt version running in the cluster
Client Version: v0.53.0
Server Version: v0.49.0
can't access VMI vm-macos12-x64: virtualmachineinstance.kubevirt.io "vm-macos12-x64" not found
```

What's super confusing is that `virtctl vnc` works totally fine here, as it doesn't have the very weird namespace behavior that `virtctl ssh` has.

**What you expected to happen**:
When explicitly specifying the namespace, I expect the dots to not be stripped from the VM name. Or otherwise, having *some way* of connecting to it.

**How to reproduce it (as minimally and precisely as possible)**:
- Create a vm with a dot in the name
- Try to `virtctl ssh` to it.

**Environment**:
- KubeVirt version (use `virtctl version`): (Server: 0.49.0, Client: 0.53.0)
- Kubernetes version (use `kubectl version`): (Server: 1.21.11, Client: 1.22.5)
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by roblabla** [comment]
Ah,yeah, portforward is also broken for the same reason. This means that whenever I try to ssh, I have to drop down to the `kubectl port-forward` command on the pod name instead.

**Comment by roblabla** [comment]
Also, as the code currently stands, it splits on `.` and assumes part[0] is vm name, part[1] is namespace, and part[2]+ is just... trashed?

AFAIK, a namespace cannot have a `.` (someone correct me if I'm wrong), so wouldn't it make more sense to assume `part.last()` is namespace? This would allow me to connect to ssh by doing `virtctl ssh vm-windows10-x64.roblabla-vm.default`

**Comment by roblabla** [comment]
/remove-lifecycle stale

This is still a problem.

**Comment by roblabla** [comment]
/remove-lifecycle stale

Bugs don't magically go away >_>

**Comment by roblabla** [comment]
/remove-lifecycle stale

Bugs don't magically go away >_>

**Comment by kubealex** [comment]
This is still an issue.
