### ISSUE TITLE
Hotplug of FileSystem PVCs on a host with btrfs

### ISSUE THREAD

**Issue by vasiliy-ul** [kubevirt/kubevirt#8297]
**What happened**:

Hotplug of `FileSystem` PVCs is currently broken on a host with `btrfs`. The mount fails and the code silently 'eats' the error, hence by default there are no error messages in the log and the volume gets stuck in the `AttachedToNode` status:

https://github.com/kubevirt/kubevirt/blob/595051e2d22bf7e520c13010aae9249b434053c5/pkg/virt-handler/hotplug-disk/mount.go#L539-L545

**What you expected to happen**:

`FileSystem` PVCs are successfully attached to a running VM.

**How to reproduce it (as minimally and precisely as possible)**:

I am able to reproduce the issue in the downstream CI with [rancher local path provisioner](https://github.com/rancher/local-path-provisioner) on a server with `btrfs`. The tests covering `hotplug` with `FilesySystem` PVCs fail. Also, `memory dump` tests fail since they rely on the same code.

**Additional context**:

My observations bellow.

Current implementation in `virt-handler` uses `findmnt` tool to locate the source for the mount: `findmnt -T /<PVC-NAME> -N <PID> -J` (here `PID` is the ID of the process running in the attachment pod). Assuming we have a PVC:

```yaml
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: local-pvc
spec:
  storageClassName: local
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
```

Then the command will produce the following results:

```
bash-4.4# findmnt -T /local-pvc -N 19272 -J 
{
   "filesystems": [
      {"target": "/local-pvc", "source": "/dev/sda2[/@/opt/local-path-provisioner/pvc-e316b528-46fd-43e8-a64a-ab0e0a54fcca_default_local-pvc]", "fstype": "btrfs", "options": "rw,relatime,space_cache,subvolid=262,subvol=/@/opt/local-path-provisioner/pvc-e316b528-46fd-43e8-a64a-ab0e0a54fcca_default_local-pvc"}
   ]
}
```

Here the `source` field looks like `/dev/sda2[/@/opt/local-path-provisioner/pvc-e316b528-46fd-43e8-a64a-ab0e0a54fcca_default_local-pvc]`. The part `/@/opt/local-path-provisioner/pvc-e316b528-46fd-43e8-a64a-ab0e0a54fcca_default_local-pvc` is extracted in `func (f *FindmntInfo) GetSourcePath() string`:

https://github.com/kubevirt/kubevirt/blob/595051e2d22bf7e520c13010aae9249b434053c5/pkg/virt-handler/hotplug-disk/findmnt.go#L84-L90

and then it is used as a source for the `bind mount`. The problem is that bind mount **does not recognize** the `btrfs subvolume` part `/@` and therefore it fails. The trivial solution with trimming the `/@` prefix will probably work for that particular case, but will not solve the problem in general when the source resides on a subvolume different from `/@`.

**Another observation**: I haven't dived into it deeply yet, but do we have btrfs support in the upstream container images (more precisely in `virt-handler`)? I tried to run bind mount manually and got the bellow error: 

```
bash-4.4# mount -o bind -t btrfs /proc/1/root/opt/local-path-provisioner/pvc-e316b528-46fd-43e8-a64a-ab0e0a54fcca_default_local-pvc mnt
mount: /mnt: wrong fs type, bad option, bad superblock on /proc/1/root/opt/local-path-provisioner/pvc-e316b528-46fd-43e8-a64a-ab0e0a54fcca_default_local-pvc, missing codepage or helper program, or other error.
```

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by vasiliy-ul** [comment]
@awels, @mhenriks FYI.

I will be off for a couple of weeks. If someone has ideas how to solve the issue, feel free to pick this.

**Comment by awels** [comment]
You analysis looks spot on. It is the definitely the `/@` that is the problem. Does it work correctly with regular k8s mounting the volume in a pod? If so we should probably look at what k8s is doing when mounting the volume and see what we can do better.

**Comment by awels** [comment]
As for btrfs not being supported in virt-handler, IIRC we do a chroot into the node filesystem before attempting the mount, and the node should have the needed support, so I don't think that should be an issue.
