### ISSUE TITLE
Do I use VirtualMachineInstance or VirtualMachine?

### ISSUE THREAD

**Issue by pmyjavec** [kubevirt/kubevirt#8308]
**Description**:
I'm confused between VirtualMachine and VirtualMachineInstance. The [Use KubeVirt ](https://kubevirt.io/labs/kubernetes/lab1.html) guide seems to expect users to deploy `https://kubevirt.io/labs/manifests/vm.yaml` which contains:

```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
```
However the API documentation doesn't seem to talk about VirutalMachine types, only VirtualMachineInstances: https://kubevirt.io/user-guide/virtual_machines/virtual_machine_instances/ 

Which one should be used, is there a difference? Thanks

**What you expected**:

Consistency between the lab and the API documentation.

**Comment by gccio** [comment]
virt-controller will create vmi with vm. and when virt machine shutdown, vmi will be removed, but vm is still exists. we can recreate vmi by vm.

**Comment by ormergi** [comment]
The best practice is to use `VirtualMachine`, its the upper abstraction layer and enables more functionalities such as stop/start, see https://kubevirt.io/user-guide/architecture/#virtualmachine.

As mentioned, under the hood, the `VirtualMachine` controller creates a corresponding `VirtualMachineInstance` once a `VirtualMachine` is set to start.
