### ISSUE TITLE
Windows VM can not be started due to incorrect disk permissions (permission denied)

### ISSUE THREAD

**Issue by duyanyan** [kubevirt/kubevirt#832]
Try to run a windows vm in a openshift env, pod became completed status and got the error inside the virt-launcher pod:
```
level=info timestamp=2018-03-21T09:39:46.426944Z pos=client.go:148 component=virt-launcher msg="Libvirt event 0 with reason 1 received"
level=info timestamp=2018-03-21T09:39:46.557111Z pos=client.go:131 component=virt-launcher msg="domain status: 3:11"
level=info timestamp=2018-03-21T09:39:46.558422Z pos=client.go:157 component=virt-launcher msg="processed event"
level=error timestamp=2018-03-21T09:39:46.638136Z pos=manager.go:167 component=virt-launcher namespace=myproject name=windows2012r2 kind= uid=aee3519e-2ceb-11e8-ad1f-28d2448d945c reason="virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2018-03-21T09:39:46.602526Z qemu-system-x86_64: -drive file=/var/run/kubevirt-private/vm-disks/server2012r2/disk.img,format=raw,if=none,id=drive-sata0-0-0: Could not open '/var/run/kubevirt-private/vm-disks/server2012r2/disk.img': Permission denied')" msg="Starting the VM failed."
level=error timestamp=2018-03-21T09:39:46.638241Z pos=server.go:59 component=virt-launcher namespace=myproject name=windows2012r2 kind= uid=aee3519e-2ceb-11e8-ad1f-28d2448d945c reason="virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2018-03-21T09:39:46.602526Z qemu-system-x86_64: -drive file=/var/run/kubevirt-private/vm-disks/server2012r2/disk.img,format=raw,if=none,id=drive-sata0-0-0: Could not open '/var/run/kubevirt-private/vm-disks/server2012r2/disk.img': Permission denied')" msg="Failed to sync vm"
level=info timestamp=2018-03-21T09:39:46.660485Z pos=client.go:148 component=virt-launcher msg="Libvirt event 0 with reason 1 received"
level=info timestamp=2018-03-21T09:39:46.673959Z pos=virt-launcher.go:196 component=virt-launcher msg="Timed out waiting for final delete notification."
level=info timestamp=2018-03-21T09:39:46.674024Z pos=virt-launcher.go:284 component=virt-launcher msg=Exiting...
```
```
# oc get pod -o wide -w
NAME                                READY     STATUS    RESTARTS   AGE       IP           NODE
virt-launcher-windows2012r2-ldfkj   0/1       Running   0          6s        172.17.0.7   localhost
virt-launcher-windows2012r2-ldfkj   1/1       Running   0         14s       172.17.0.7   localhost
virt-launcher-windows2012r2-ldfkj   0/1       Completed   0         48s       172.17.0.7   localhost
```
The image file mode in my nfs server is -rwx------
```
# ll disk.img 
-rwx------. 1 root root 6006587392 Mar 21 14:38 disk.img
```
If I change file mode to 777, then I won't met the permission error and pod could be started
```
# oc get pod -o wide -w
NAME                                READY     STATUS    RESTARTS   AGE       IP           NODE
virt-launcher-windows2012r2-w6mv8   0/1       Running   0          7s        172.17.0.7   localhost
virt-launcher-windows2012r2-w6mv8   1/1       Running   0         13s       172.17.0.7   localhost
```

**Comment by rmohr** [comment]
I wonder if we can/should provide a fix there, or make clear what permissions are needed to make the image accessible. For local created images (which the launcher owns it sets the permissions).

**Comment by fabiand** [comment]
At least libvirt provides a usefukl warning in these cases IIRC.

I also wonder if we can't fix this on our side somehow, or even in Kube.
After all it is not always predictive what UID a file will have on a volume, thus I#d expect that maybe kube has a mechanism to adjust/fake it.

**Comment by cynepco3hahue** [comment]
@duyanyan  I readed a little about NFS export under OpenShift and looks like they leave it on user responsibility to set correct user ID or group ID on container https://docs.openshift.com/container-platform/3.7/install_config/persistent_storage/persistent_storage_nfs.html#nfs-volume-security

@fabiand @rmohr From the other side we do not provide any option to set user ID or group ID on virt-launcher container, so it can be really an issue(but if we will set other that root user to container I do not sure a VM will start at all)

So I think we just need add some note to user-guide, that `disk.img` directory must be own by `root` or set permissions to `777` to `disk.img`

**Comment by fabiand** [comment]
@cynepco3hahue yes, I mostly agree, except that we don't need `777` `o=rw` should be enough.

Howeverm, the two things we can do:
- Raise relevant error in case that we detect that we can not read something
- Documentation for setting the right permissions

/cc @aglitke @copejon 
This is relevant for CDI

**Comment by simon3z** [comment]
@fabiand given that this issue is critical-urgent I think we should formalize the assignee.

**Comment by fabiand** [comment]
I think this issue is fixed.

@karmab @duyanyan can yuo confirm that this bug is fixed?

**Comment by karmab** [comment]
my take is that it is indeed fixed, but would be nice to have a document indicating which requirements are needed on the pv side
- permission
- ownership

**Comment by rmohr** [comment]
> So I think we just need add some note to user-guide, that disk.img directory must be own by root or set permissions to 777 to disk.img

Our VMs run as non-root with uid 107 (qemu user). In my opinion that would be the best to document.

**Comment by fabiand** [comment]
Thanks @karmab @rmohr 

Created a note in the user guide to document it.
