### ISSUE TITLE
Image uploading is not working with WaitForFirstConsumer

### ISSUE THREAD

**Issue by kvaps** [kubevirt/kubevirt#8320]
**What happened**:
Image uploading is not working with WaitForFirstConsumer

**What you expected to happen**:
virtctl will create Pod and PVC simultaneously

**How to reproduce it (as minimally and precisely as possible)**:
- Install [local-path-provisioner](https://github.com/rancher/local-path-provisioner)
- Try uploading image using virtctl:
  ```bash
  virtctl image-upload --image-path ~/Downloads/Win10_21H2_EnglishInternational_x64\(1\).iso  --pvc-name=iso-win10 --pvc-size=10G --insecure --wait-secs=240 --storage-class=localpath-system
  ```

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.55.0
- Kubernetes version (use `kubectl version`): v1.23.0
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by mhenriks** [comment]
Hi @kvaps, virtctl has a `--force-bind` to support immediately creating the upload pod.

**Comment by kvaps** [comment]
Got it, thanks. Seems not bug then
