### ISSUE TITLE
Remove ocp hack once console websocket is introduced

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#834]
#819 needs to be reverted then.

**Comment by fabiand** [comment]
This depends on a better solution in OCP. Nothing we can target right now.

**Comment by fabiand** [comment]
Setting to v1.1 for now, but we need to see how OCP evolves.

**Comment by fabiand** [comment]
@rmohr - We gave head's up to the console some time ago. So we are good now to remove this hack.

**Comment by michalskrivanek** [comment]
> We gave head's up to the console some time ago. So we are good now to remove this hack.

true, though the change has not been done yet AFAIK. It's supposedly fairly straightforward, but still I guess it should be synced on both sides

**Comment by fabiand** [comment]
We'll remove it for the next release - 0.7 - that also gives you some time
to adjust.

**Comment by mareklibra** [comment]
On Tue, Jun 19, 2018 at 5:01 PM michalskrivanek <notifications@github.com>
wrote:

> We gave head's up to the console some time ago. So we are good now to
> remove this hack.
>
> true, though the change has not been done yet AFAIK. It's supposedly
> fairly straightforward, but still I guess it should be synced on both sides
>
I would wait with the removal till implementation via API endpoint is
working properly.
Recently issue with websocket connection needs to be resolved, websocket
upgrade within handshake is failing on strict origin check (on server-side).

**Comment by fabiand** [comment]
On Thu, Jun 28, 2018 at 12:05 PM Marek Libra <notifications@github.com>
wrote:

> On Tue, Jun 19, 2018 at 5:01 PM michalskrivanek <notifications@github.com>
> wrote:
>
> > We gave head's up to the console some time ago. So we are good now to
> > remove this hack.
> >
> > true, though the change has not been done yet AFAIK. It's supposedly
> > fairly straightforward, but still I guess it should be synced on both
> sides
> >
> I would wait with the removal till implementation via API endpoint is
> working properly.
> Recently issue with websocket connection needs to be resolved, websocket
> upgrade within handshake is failing on strict origin check (on
> server-side).


Could you please provide a link to the issue tracking this? We should label
it accordingly.

**Comment by rmohr** [comment]
We need to find a solution for #1242.

**Comment by fabiand** [comment]
@rmohr what did your research reveal? is it a kube or kubevirt bug?

**Comment by fabiand** [comment]
We'll be dropping the patch .

I think web console now has the capability to call a custom command (because there is now a dedicated vm page with a console).

Thus now they can call what the hack does.
