### ISSUE TITLE
generate clientset/listers/informers code

### ISSUE THREAD

**Issue by nuczzz** [kubevirt/kubevirt#8343]
**Is your feature request related to a problem? Please describe**:

I want to manage kubevirt resources through my golang code(especially vmi resource), it means that  I will create/update/delete/get/list kubevirt resources. Informer is the most common method to reduce the pressure on apiserver, but I only find some clientset code in staging/src/kubevirt.io/client-go/generated/kubevert/clientset/versioned directory. I would like to have some clientset/lister/informer code for kubevirt resources.

**Describe the solution you'd like**:

Add some code to hack/generate.sh like this, and generate clientset/lister/informer code:
```
client-gen --clientset-name versioned \
    --input-base kubevirt.io/api \
    --input core/v1 \
    --output-base ${KUBEVIRT_DIR}/staging/src \
    --output-package ${CLIENT_GEN_BASE}/kubevirt/clientset \
    --go-header-file ${KUBEVIRT_DIR}/hack/boilerplate/boilerplate.go.txt \
    -v 10

lister-gen --input-dirs kubevirt.io/api/core/v1 \
    --output-base ${KUBEVIRT_DIR}/staging/src \
    --output-package ${CLIENT_GEN_BASE}/kubevirt/listers \
    --go-header-file ${KUBEVIRT_DIR}/hack/boilerplate/boilerplate.go.txt \
    -v 10

informer-gen --input-dirs kubevirt.io/api/core/v1 \
    --versioned-clientset-package ${CLIENT_GEN_BASE}/kubevirt/clientset/versioned \
    --listers-package ${CLIENT_GEN_BASE}/kubevirt/listers \
    --output-base ${KUBEVIRT_DIR}/staging/src \
    --output-package ${CLIENT_GEN_BASE}/kubevirt/informers \
    --go-header-file ${KUBEVIRT_DIR}/hack/boilerplate/boilerplate.go.txt \
    -v 10
```

**Comment by xpivarc** [comment]
Hi @nuczzz, There is kubevirt/api repository for this case. The recommendation is to generate these clients on your own from this repository.
