### ISSUE TITLE
passt - tracker of follow-ups

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#8371]
**Is your feature request related to a problem? Please describe**:
[passt](https://kubevirt.io/user-guide/virtual_machines/interfaces_and_networks/#passt) network binding was introduced to kubevirt.
However, it still has some missing functionality.

1. Currently, KubeVirt supports passt only as primary and single network. passt binary should support multiple networks, KubeVirt code has to be extended to add this support.
2. Libvirt doesn't support passt yet (TODO - add a tracker for libvirt support). Once this support will be added it will be possible to specify the NIC’s MAC/PCI/MTU  address.
3. Support migration. The current kubevirt implementation uses the passt default mode which gives the VM the same IP as the pod has. (The kuebvirt VM api should support giving the passt interface a stable IP)
It is possible tell passt to give the VM any other IP. Giving the VM a stable IP, migration should work out of the box.
4. Re-run the passt process in case it dies.
6. Verify that the number of free FDs is enough before running a passt VM.
7.  Memory overhead - we need to understand the memory consumption of passt and add it to our overhead calculations so we don't hit OOM when limits are in use.
8. Make sure the passt process is running *after* the service mesh is up and bound to all the ports it needs. Since the passt process  
 (in case no specific ports were specified) is binding to all the ports. If passt does it before the service mesh, the service mesh won't be able to bind to its reserved ports. 
The current kubevirt code may run passt before the service mesh is fully started and bound to all the ports it needs. As a workaround, to avoid flakes, Kubevirt excludes istio reserved ports from the passt ports list. However, for other service mesh, flakes may happen. We need to think what is the best way to avoid those fakes? Exclude the reserved ports of each service mesh from passt or maybe a more general solution. (BTW, according to at least the istio developers. We cannot assume all the reserved ports are bound on startup).
9. Remove `(allow process tmpfs_t (filesystem (mount)))` policy for `virt_launcher.cil`. The policy should be added by the passt rpms.
10. Allow binding to low ports https://github.com/kubevirt/kubevirt/issues/8569
11. Support IPv6. It should more or less work today. It has two gotchas: We do not test it. The VM gets the prefix of the Pod, but the suffix will be different due to the lack of RA configuration.

**Comment by xpivarc** [comment]
I would add that we need to remove the SELinux rule.

**Comment by AlonaKaplan** [comment]
> I would add that we need to remove the SELinux rule.

Correct, updated. Thanks!

**Comment by rhrazdil** [comment]
It's probably better to track https://github.com/kubevirt/kubevirt/issues/8745 in this issue, so that everything is at one place.
>Passt binding currently requires an overhead of 800Gi when a VMI doesn't explicitly specify ports, and thus the whole port range is forwarded.
An effort to optimize this is being tracked in https://bugs.passt.top/show_bug.cgi?id=20. We should update the 800Mi overhead when the optimizations make it to the passt release.
