### ISSUE TITLE
How to know the reason why virt-handler deletes vmi?

### ISSUE THREAD

**Issue by lixiaobing1** [kubevirt/kubevirt#8374]
When vm is stopped, vmi will be deleted, virt-handler will be notified to delete vmi, but how to know the reason to delete vmi, such as stop, normally remove...

**Comment by usrbinkat** [comment]
VMI only exists while VM is in a running state. when halting a VM the virt-launcher pod does not need to be running and so it will exit. The VMI will be created and scheduled again once the VM state is changed back to running.

This is normal and designed behavior.

**Comment by lixiaobing1** [comment]
ok, thx:)
