### ISSUE TITLE
x509: certificate is valid for virt-handler, virt-handler.kubevirt, virt-handler.kubevirt.svc, virt-handler.kubevirt.svc.cluster.local, not virt-api.kubevirt.svc

### ISSUE THREAD

**Issue by mmmlz** [kubevirt/kubevirt#8394]
源码安装的k8s v1.19集群，安装了calico 3.18，kubevirt0.35，使用kubevirt创建虚拟机时报错，报错信息如下：
Error from server (InternalError): error when creating "vmi.yaml": Internal error occurred: failed calling webhook "virtualmachineinstances-create-validator.kubevirt.io": Post "https://virt-api.kubevirt.svc:443/virtualmachineinstances-validate-create?timeout=30s": x509: certificate is valid for virt-handler, virt-handler.kubevirt, virt-handler.kubevirt.svc, virt-handler.kubevirt.svc.cluster.local, not virt-api.kubevirt.svc
请问该如何解决这个问题？

**Comment by xpivarc** [comment]
The Kubernetes and Kubevirt version is pretty old. Would be able to try newer versions?
