### ISSUE TITLE
Always report the pod IP in the primary interface status

### ISSUE THREAD

**Issue by AlonaKaplan** [kubevirt/kubevirt#8408]
**What happened**:
Currently, in bridge binding, if there is a guest agent report, it overrides the IP information of the interface, even if the ga report lacks for some reason the IP information.
It is known that to reach the VM primary interface, the Pod IP should be used. So it doesn't make sense to hide this info with the GA data (no matter what binding is used).
On the other hand, if the GA doesn't report an IP it may indicate the IP was removed from the VM. Which is important information.

Since a lot of discussions were already done on what it the best logic to calculate which IP should be presented for each binding and it seems that any option has pluses and minuses. I suggest to display both, the GA network data and the pod IP.

`kubectl get vmi` will show the PodIP. While the full status will have both.

[Related issue](https://github.com/kubevirt/kubevirt/issues/6857)

**Comment by EdDev** [comment]
If there is GA information about interfaces in general, we trust it completely.
That means, we consider it to be the actual state in the guest and therefore we reflect it.
(this mainly applies for bridge binding)

If the GA is reporting L2 information but not L3 one (e.g. IP addresses), and in reality there is L3 information in the guest, we have no way to determine which is the case. Therefore, it makes sense (to me) that we should assume the report is correct and consider the other case as a bug or wrong/unsupported operation.
I think it is more common for the info to reflect the real state over it to experience bugs, therefore, we should treat the common case.

>  I suggest to display both, the GA network data and the pod IP.

Isn't this the case today?
When observing the Pod, you will see its (originally) assigned IP, but when observing the VMI, you will see the actual IP as seen in the guest (in case GA is active).

Displaying two sources of information in the VMI status for the same interface seems problematic to me.
But the real problem I see is with what is considered "actual". I think that GA info is the one that has priority over anything else, even if it is not in sync with the Pod information. Providing other information seems to me as exposing assumptions, not reality.

**Comment by EdDev** [comment]
> If the GA is reporting L2 information but not L3 one (e.g. IP addresses), and in reality there is L3 information in the guest, we have no way to determine which is the case.

This also sounds a bit odd to me. The information about the interface (L2 or L3) is probably fetched in the same manner (using `netlink`) from the kernel, so having interface but no IP information is unlikely IMO.
If there is a real scenario like this, lets recreate it and see it is really behaving as assumed in this issue.

**Comment by AlonaKaplan** [comment]
> If there is a real scenario like this, lets recreate it and see it is really behaving as assumed in this issue.
https://github.com/kubevirt/kubevirt/issues/6857

**Comment by EdDev** [comment]
After chatting with @AlonaKaplan , I think we recognized the source of the gap in how we see the problem (or no problem).

The VMI interfaces status section can be interpreted in (at least) two ways:
- The interface data (in particular the IP address) is representing what a client **should use**, to access the VMI.
- The interface data is representing **the actual** interface state.

While one approach is taking the job of exposing to what IP to connect to, the other approach is adding to that the information about that IP being available at all.
In practice, if the guest has an IP on the relevant interface or not, is irrelevant to the first approach. For the second approach, the lack of the IP address is an indication that there is no real IP to access, therefore nothing is reported.

The current implementation has a mix of these approaches.
For masquerade binding, the "should use" approach is fully taken.
For bridge binding, the "actual" approach is taken.

I have hard time interpreting the interfaces status in any other way than the actual state.
At least we now know the source of the different approaches.
