### ISSUE TITLE
Support QEMU command line args in VM/VMI spec

### ISSUE THREAD

**Issue by yeahdongcn** [kubevirt/kubevirt#8420]
**Is your feature request related to a problem? Please describe**:
When adding a vGPU device (vfio-pci) to the existing Windows 10 VM (BIOS), the VM is not able to boot. `virsh list` shows the VM is in `running` state and there is nothing useful in logs.

QEMU args show extra `bus=pci.6,addr=0x1` appends to the device. I tried to boot the VM on my host using `qemu-system-x86_64` directly, and the same issue happened. Then I removed the `bus=pci.6,addr=0x1`, and the VM booted.

So I'm wondering whether there is a way to pass QEMU command line args in VM/VMI spec to workaround this issue.

**Describe the solution you'd like**:
A new field in VM/VMI spec to specify QEMU command line args.

**Describe alternatives you've considered**:
No.

**Additional context**:
No.

**Comment by alicefr** [comment]
@yeahdongcn this sounds to me like a libvirt bug or some wrong defaults on KubeVirt side when we generate the VM XML. You are not suppose to pass any direct QEMU command line.

**Comment by yeahdongcn** [comment]
@alicefr AFAIK, `libvirt` supports this in XML. It would be useful in debugging and workaround some issues.

**Comment by yeahdongcn** [comment]
Yeah, please share the example. Thanks.

**Comment by depeo** [comment]
Did you ever figure out how to do this? I have a similar gpu ssue and would also like to pass qemu some options,  to try to get it working.

**Comment by yeahdongcn** [comment]
KubeVirt doesn't provide this kind of option. I previously did `exec` into the `virt-launcher` container, using `virsh` to dump and edit the XML then started a new VM.

I wish @alicefr could provide us the `official` example. That would be more helpful.

**Comment by alicefr** [comment]
> KubeVirt doesn't provide this kind of option. I previously did `exec` into the `virt-launcher` container, using `virsh` to dump and edit the XML then started a new VM.
> 
> I wish @alicefr could provide us the `official` example. That would be more helpful.

Sorry, no time. It is a very busy period. However, you should be able to create your own following the examples we already have like: https://github.com/kubevirt/kubevirt/tree/main/cmd/example-hook-sidecar

**Comment by Gohoy** [comment]
Have you solve it ? I am sufferring from the same problem.

**Comment by victortoso** [comment]
Hi, sorry, I forgot to close this one.

As mentioned in https://github.com/kubevirt/kubevirt/pull/9166#issuecomment-1807887695 we now have straightforward way to add QEMU command line args using the `sidecar-shim` container image plus a ConfigMap with a script to add the changes. The is an open issue to do the user-guide documentation here https://github.com/kubevirt/user-guide/issues/726 but in the meanwhile the documention in [sidecar's README](https://github.com/kubevirt/kubevirt/blob/main/cmd/sidecars/README.md) is very helpful.

/close
