### ISSUE TITLE
Enable default Seccomp profile

### ISSUE THREAD

**Issue by xpivarc** [kubevirt/kubevirt#8424]
**Is your feature request related to a problem? Please describe**:
Let's make sure our providers are using the default Seccomp profile when an empty profile is set. This should ensure Kubevirt is compatible with it.

**Describe the solution you'd like**:

**Describe alternatives you've considered**:

**Additional context**:

**Comment by theVJagrawal** [comment]
Hello @xpivarc! Can I work on this one? Need to know bit more about on how to proceed.

**Comment by xpivarc** [comment]
Hi @theVJagrawal ,
Thanks for the initiative and I apologize for the late reply I was attending the conference and got a little bit behind with notifications...

I have recently opened https://github.com/kubevirt/kubevirt/pull/8561 where we see couple of issues and I am in the process of understanding what are our options.

Would you be interesting in any other task?
