### ISSUE TITLE
`virt-handler` is unable to create new mdev devices after first removing one of mediatedDevicesTypes then adding it back 

### ISSUE THREAD

**Issue by yeahdongcn** [kubevirt/kubevirt#8425]
I have the CR change described in https://github.com/kubevirt/kubevirt/pull/8422

```yaml
    mediatedDevicesConfiguration:
      nodeMediatedDeviceTypes:
      - mediatedDevicesTypes:
        - gpu-2001
        - gpu-2002
        nodeSelector:
          kubernetes.io/hostname: ubuntu
```

First I remove `gpu-2002` from the list, new mdev devices of `gpu-2001` are created (with my fix). Then I add `gpu-2002` back to the list.

**What happened**:
No new devices of `gpu-2002` are created (both 2 GPUs are used to create `gpu-2001`).

**What you expected to happen**:
New devices of `gpu-2002` can be created.

**How to reproduce it (as minimally and precisely as possible)**:
1. Prepare a K8s node with 2 GPUs with vfio-mdev cap
2. Update KubeVirt CR to provision 2 types of vGPU
3. Remove one type (with https://github.com/kubevirt/kubevirt/pull/8422 applied)
4. Add it back to the CR
5. Run `mdevctl list` to show the mdev devices

**Additional context**:
No.

**Environment**:
- KubeVirt version (use `virtctl version`): 
  Local build of https://github.com/kubevirt/kubevirt/pull/8422
  ```
  Client Version: version.Info{GitVersion:"v0.52.0", GitCommit:"836afc8c556206fc7715615ddb6516d76f4240db", GitTreeState:"clean", BuildDate:"2022-04-08T16:25:37Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}
  Server Version: version.Info{GitVersion:"v0.57.0-rc.0.27+1159620198ccc8-dirty", GitCommit:"1159620198ccc89376e876ccf2953f8b9a29f4f6", GitTreeState:"dirty", BuildDate:"2022-09-07T06:40:03Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
  ```
- Kubernetes version (use `kubectl version`):
  ```
  Client Version: v1.24.0
  Kustomize Version: v4.5.4
  Server Version: v1.23.4
  ```
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: model name: 12th Gen Intel(R) Core(TM) i5-12400 + MemTotal: 32427564 kB + GPU * 2
- OS (e.g. from /etc/os-release): Ubuntu 20.04.4 LTS (Focal Fossa)
- Kernel (e.g. `uname -a`): 5.4.0-42-generic
- Install tools: N/A
- Others: N/A

**Comment by alicefr** [comment]
@yeahdongcn this is a similar issue as https://github.com/kubevirt/kubevirt/issues/7084
/cc @vladikr

**Comment by yeahdongcn** [comment]
Yes, except the mdev devices are managed by `virt-handler`.

**Comment by yeahdongcn** [comment]
I may find a way to workaround this issue. You have to remove all `mediatedDevicesTypes` and wait for the mdev to be cleaned up, then add them back.
