### ISSUE TITLE
Unable to create a VM and delete kubevirt on a cluster with dpdk features.

### ISSUE THREAD

**Issue by nvinnakota10** [kubevirt/kubevirt#8438]
**What happened**:
I am trying to deploy kubevirt and create VMs on a dpdk setup for running pktgen traffic tests.

The VM creation is failing with the error: Error from server (InternalError): error when creating "vm.yaml": Internal error occurred: failed calling webhook "virtualmachines-mutator.kubevirt.io": failed to call webhook: Post "https://virt-api.kubevirt.svc:443/virtualmachines-mutate?timeout=10s": context deadline exceeded

Deletion of kubevirt is failing due to the error: Error from server (InternalError): Internal error occurred: failed calling webhook "kubevirt-validator.kubevirt.io": failed to call webhook: Post "https://kubevirt-operator-webhook.kubevirt.svc:443/kubevirt-validate-delete?timeout=10s": context deadline exceeded

The virt-api apiservices are in FailedDiscoveryCheck state as shown below:

[v1.subresources.kubevirt.io](http://v1.subresources.kubevirt.io/)                 kubevirt/virt-api               False (FailedDiscoveryCheck)   38h
[v1alpha3.subresources.kubevirt.io](http://v1alpha3.subresources.kubevirt.io/)           kubevirt/virt-api               False (FailedDiscoveryCheck)   38h

The virt-api pod logs shows TLS Handshake errors.
 
Attaching the virt-api pod logs
[virt-api.txt](https://github.com/kubevirt/kubevirt/files/9530794/virt-api.txt)

**What you expected to happen**:

The VMs should be created on kubevirt without any errors. The kubevirt can be deleted/updated and reinstalled any number of times.

**How to reproduce it (as minimally and precisely as possible)**:

Follow the steps mentioned in https://kubevirt.io/user-guide/operations/installation/#installing-kubevirt-on-kubernetes to install kubevirt.

Apply the vm spec for dpdk application.

Follow the steps to delete kubevirt.

**Additional context**:

The below error is shown when the command kubectl api-resources is used:
(error: unable to retrieve the complete list of server APIs: subresources.kubevirt.io/v1: the server is currently unable to handle the request, subresources.kubevirt.io/v1alpha3: the server is currently unable to handle the request)

**Environment**:
- KubeVirt version (use `virtctl version`): v0.48.0
- Kubernetes version (use `kubectl version`): v1.24.0
- VM or VMI specifications: Huge pages configured (2Mi/1024Mi)
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): ubuntu
- Kernel (e.g. `uname -a`): 5.4.0-89-generic
- Install tools: N/A
- Others: N/A

**Comment by usrbinkat** [comment]
The API pod errors sounds possibly like an issue with the health of the currently deployed kubevirt pods, the api pod error included below points at a possible culprit.

Can you post the status of all kubevirt pods and the vm yaml definition you are trying to apply as well?

```
{"component":"virt-api","contentLength":371,"level":"info","method":"GET","pos":"filter.go:46","proto":"HTTP/1.1","remoteAddress":"10.84.16.35","statusCode":200,"timestamp":"2022-09-07T20:23:23.233052Z","url":"/apis/subresources.kubevirt.io/v1/healthz","username":"-"}
{"component":"virt-api","level":"info","msg":"http: TLS handshake error from 10.84.16.29:58640: EOF\n","pos":"server.go:3119","timestamp":"2022-09-07T20:23:31.469062Z"}
```

**Comment by nvinnakota10** [comment]
Hi,

Please find the status and logs of the kubevirt pods fetched from a fresh setup in the same order.



ubuntu@root-k8s-dpdk-master:~$ kubectl get pods -n kubevirt -owide
NAME                               READY   STATUS    RESTARTS       AGE     IP            NODE                                        NOMINATED NODE   READINESS GATES
virt-api-7589df599d-dcmdv          1/1     Running   0              5h58m   10.244.1.14   root-k8s-dpdk-kubelet1.englab.juniper.net   <none>           <none>
virt-api-7589df599d-kd659          1/1     Running   0              5h58m   10.244.2.13   root-k8s-dpdk-kubelet2.englab.juniper.net   <none>           <none>
virt-controller-8579d8d67b-7bsxj   1/1     Running   1 (5h5m ago)   5h57m   10.244.2.14   root-k8s-dpdk-kubelet2.englab.juniper.net   <none>           <none>
virt-controller-8579d8d67b-wfpwb   1/1     Running   3 (5h7m ago)   5h57m   10.244.1.13   root-k8s-dpdk-kubelet1.englab.juniper.net   <none>           <none>
virt-handler-8jvjn                 1/1     Running   0              5h57m   10.244.0.11   root-k8s-dpdk-master.englab.juniper.net     <none>           <none>
virt-handler-f5l9j                 1/1     Running   0              5h57m   10.244.2.15   root-k8s-dpdk-kubelet2.englab.juniper.net   <none>           <none>
virt-handler-mfzsv                 1/1     Running   0              5h57m   10.244.1.15   root-k8s-dpdk-kubelet1.englab.juniper.net   <none>           <none>
virt-handler-xjvk8                 1/1     Running   0              5h57m   10.244.3.3    root-k8s-dpdk-kubelet3.englab.juniper.net   <none>           <none>
virt-operator-74d56f4dc6-4vrfc     1/1     Running   3 (5h7m ago)   6h      10.244.2.12   root-k8s-dpdk-kubelet2.englab.juniper.net   <none>           <none>
virt-operator-74d56f4dc6-wh6lt     1/1     Running   2 (5h5m ago)   6h      10.244.1.7    root-k8s-dpdk-kubelet1.englab.juniper.net   <none>           <none>

[api1.txt](https://github.com/kubevirt/kubevirt/files/9586275/api1.txt)
[api2.txt](https://github.com/kubevirt/kubevirt/files/9586276/api2.txt)
[controller1.txt](https://github.com/kubevirt/kubevirt/files/9586278/controller1.txt)
[controller2.txt](https://github.com/kubevirt/kubevirt/files/9586279/controller2.txt)
[handler1.txt](https://github.com/kubevirt/kubevirt/files/9586280/handler1.txt)
[handler2.txt](https://github.com/kubevirt/kubevirt/files/9586281/handler2.txt)
[handler3.txt](https://github.com/kubevirt/kubevirt/files/9586282/handler3.txt)
[handler4.txt](https://github.com/kubevirt/kubevirt/files/9586283/handler4.txt)
[op1.txt](https://github.com/kubevirt/kubevirt/files/9586284/op1.txt)
[op2.txt](https://github.com/kubevirt/kubevirt/files/9586285/op2.txt)

Please let me know if any further information is required.

Thanks

**Comment by nvinnakota10** [comment]
@usrbinkat, can I know if there is anything I can do to fix this issue. I am not sure what exactly is wrong. I am not able to create a VM and not able to delete kubevirt on the setup.

Thanks,
Vihari

**Comment by nvinnakota10** [comment]
@usrbinkat, I am still stuck with the issue.  Can you please help me fixing this. I would like to know if there is any observation that I missed form the logs and how to fix the issue.

**Comment by mkurimeti** [comment]
+1 , same issue I installed kubevirt v0.58.0 on Kubernetes cluster stuck with the error - failed calling webhook "virtualmachines-mutator.kubevirt.io" any update on this

**Comment by Sreelal-VU** [comment]
+1 : Internal error occurred: failed calling webhook "virtualmachines-mutator.kubevirt.io": failed to call webhook

**Comment by nvinnakota10** [comment]
The issue is seen because TCP traffic was dropping at the compute NIC, where the kubevirt is installed. It is due to our settings in the custom CNI.
