### ISSUE TITLE
KubeVirtComponentExceedsRequestedCPU/Memory are not working properly

### ISSUE THREAD

**Issue by chrisho** [kubevirt/kubevirt#8439]
**What happened**:
The alerts KubeVirtComponentExceedsRequestedCPU and KubeVirtComponentExceedsRequestedMemory are not working properly.

**What you expected to happen**:
The alerts are working properly.

**How to reproduce it (as minimally and precisely as possible)**:
After Install Kubevirt.

**Additional context**:
KubeVirtComponentExceedsRequestedCPU related issue:
`node_namespace_pod_container:container_cpu_usage_seconds_total:sum_rate` changed in kube-prometheus issue: https://github.com/prometheus-operator/kube-prometheus/issues/1056#issuecomment-934617638

KubeVirtComponentExceedsRequestedMemory error:
```
found duplicate series for the match group {pod="kube-vip-czcpp"} on the right hand-side of the operation: [{__name__="container_memory_working_set_bytes", endpoint="https-metrics", id="/kubepods/besteffort/pod18898f14-6d91-484c-a0ff-8724c36cf881/508c136c03021f72921a2a6a79b02bae3e7b7a4cde611c8fc1eb9afa4ce665b9", image="docker.io/rancher/pause:3.6", instance="192.168.31.161:10250", job="kubelet", metrics_path="/metrics/cadvisor", name="508c136c03021f72921a2a6a79b02bae3e7b7a4cde611c8fc1eb9afa4ce665b9", namespace="harvester-system", node="harvester-master", pod="kube-vip-czcpp", service="rancher-monitoring-kubelet"}, {__name__="container_memory_working_set_bytes", endpoint="https-metrics", id="/kubepods/besteffort/pod18898f14-6d91-484c-a0ff-8724c36cf881", instance="192.168.31.161:10250", job="kubelet", metrics_path="/metrics/cadvisor", namespace="harvester-system", node="harvester-master", pod="kube-vip-czcpp", service="rancher-monitoring-kubelet"}];many-to-many matching not allowed: matching labels must be unique on one side
```
promSQL:
```
((kube_pod_container_resource_requests{container=~"virt-controller|virt-api|virt-handler|virt-operator",namespace="harvester-system",resource="memory"}) - on(pod) group_left(node) container_memory_working_set_bytes{container="",namespace="harvester-system"}) < 0
```

It looks like it can be solved by adding the filter `container=~"virt-controller|virt-api|virt-handler|virt-operator"` to `container_memory_working_set_bytes`.

related issue: https://github.com/harvester/harvester/issues/2729

**Environment**:
- KubeVirt version (use `virtctl version`): 0.54.0
- Kubernetes version (use `kubectl version`): v1.22.12
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): SLE Micro
- Kernel (e.g. `uname -a`): 5.3.18-150300.59.90-default
- Install tools: N/A
- Others: 
prometheus:v2.28.1
prometheus-operator: v0.50.0

**Comment by w13915984028** [comment]
/reopen

the issue still happens, logged also in 
https://github.com/harvester/harvester/issues/3792,  
https://github.com/harvester/harvester/issues/3472

prometheus complains:
> level=warn ts=2023-04-19T08:56:37.628Z caller=manager.go:603 component="rule manager" group=kubevirt.rules msg="Evaluating rule failed" rule="alert: KubeVirtComponentExceedsRequestedMemory\nexpr: ((kube_pod_container_resource_requests{container=~"virt-controller|virt-api|virt-handler|virt-operator",namespace="harvester-system",resource="memory"})\n - on(pod) group_left(node) container_memory_working_set_bytes{container="",namespace="harvester-system"})\n < 0\nfor: 5m\nlabels:\n kubernetes_operator_component: kubevirt\n kubernetes_operator_part_of: kubevirt\n severity: warning\nannotations:\n description: Container {{ $labels.container }} in pod {{ $labels.pod }} memory usage\n exceeds the memory requested\n runbook_url: [https://kubevirt.io/monitoring/runbooks/KubeVirtComponentExceedsRequestedMemory\n](https://kubevirt.io/monitoring/runbooks/KubeVirtComponentExceedsRequestedMemory%5Cn) summary: The container is using more memory than what is defined in the containers\n resource requests\n" err="found duplicate series for the match group {pod="kube-vip-cloud-provider-0"} on the right hand-side of the operation: [{name="container_memory_working_set_bytes", endpoint="https-metrics", id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod3483397c_e5e4_4f1b_ae47_e8c70f65341c.slice/cri-containerd-cdaf78aac3bd426acc98a4704eb550da59ab7ac6c7a38e3b0d19149bc2df50f4.scope", image="docker.io/rancher/pause:3.6", instance="192.168.122.131:10250", job="kubelet", metrics_path="/metrics/cadvisor", name="cdaf78aac3bd426acc98a4704eb550da59ab7ac6c7a38e3b0d19149bc2df50f4", namespace="harvester-system", node="harv31", pod="kube-vip-cloud-provider-0", service="rancher-monitoring-kubelet"}, {name="container_memory_working_set_bytes", endpoint="https-metrics", id="/kubepods.slice/kubepods-besteffort.slice/kubepods-besteffort-pod3483397c_e5e4_4f1b_ae47_e8c70f65341c.slice", instance="192.168.122.131:10250", job="kubelet", metrics_path="/metrics/cadvisor", namespace="harvester-system", node="harv31", pod="kube-vip-cloud-provider-0", service="rancher-monitoring-kubelet"}];many-to-many matching not allowed: matching labels must be unique on one side"
