### ISSUE TITLE
deprecate vagrant cluster providers

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#844]
We need to move everyone over to the containerized providers. Direct usage of vagrant for development should be deprecated.

**Comment by stu-gott** [comment]
It looks like `docs/env-providers.md` and `docs/getting-started.md` are a bit out of date.

For the benefit of anybody wondering how to move away from Vagrant. We currently have two providers that can be set using the `PROVIDER` env var:

```bash
export PROVIDER=os-3.9.0-alpha.4
export PROVIDER=k8s-1.9.3
```

Depending on if you're looking to deploy an OpenShift or pure Kubernetes environment.

**Comment by fabiand** [comment]
@stu-gott please provide a RP to fix the docs.

Is there anything else that needs adjustment?

**Comment by yuvalif** [comment]
in hack/config-default.sh we have: ```kubeconfig=cluster/vagrant/.kubeconfig```
should we change that?

**Comment by rmohr** [comment]
@yuvalif good catch. We should just remove that line. Every provider overrides that with its own value. The "default" value is never used.

**Comment by fabiand** [comment]
Can this be closed @stu-gott ?

**Comment by fabiand** [comment]
It can.
