### ISSUE TITLE
Avoid creating static route to our default gateway

### ISSUE THREAD

**Issue by mlsorensen** [kubevirt/kubevirt#845]
I may have run into an issue related to [#830](https://github.com/kubevirt/kubevirt/pull/830). It seems I'm getting a static route to my gateway, and no default gateway.

Since this is merged I'll just create a new issue.

My lease looks like this:

> lease {
>   interface "eth0";
>   fixed-address 172.16.52.146;
>   option subnet-mask 255.255.255.255;
>   option routers 169.254.1.1;
>   option dhcp-lease-time 86313600;
>   option dhcp-message-type 5;
>   option domain-name-servers 192.168.0.10;
>   option dhcp-server-identifier 10.11.12.13;
>   option classless-static-routes 32.169.254.1.1 169.254.1.1;
>   renew 3 2019/05/01 23:04:52;
>   rebind 0 2020/08/16 23:48:11;
>   expire 6 2020/12/19 20:48:11;
> }

And results in routing table like this:

> [root@fedora ~]# ip route show
> 169.254.1.1 via 169.254.1.1 dev eth0 proto static

And I can't get anywhere. Maybe in the "// Filter out irrelevant routes" it should skip routes with destination IP of the gateway? Or does that defeat your purpose?

I ran some debugging and I'm getting a VIF route entry of Src=nil Dst.IP=169.254.1.1/32

If I do filter out the Dst == router route I'm back in business:

> [root@fedora ~]# ip route show
> default via 169.254.1.1 dev eth0

**Comment by vladikr** [comment]
Yes, I see that you both have the router IP in routers 169.254.1.1 and in the static routes.
I'm not sure how and why was this set in the pod, but I don't see a harm in filtering Dst == router from static routes.

However, in your example, you don't have any static routes, after you've filtering. I wonder if the filtered route caused the default gateway to not be set or perhaps it wasn't set because there were any static routes.

**Comment by vladikr** [comment]
I'm not sure that this additional route is very problematic 
```169.254.1.1 via 169.254.1.1 dev eth0 proto static```
I think that the lack of a default gateway is the problem. 

I've added the following that it still worked:
```
$ sudo ip r add 10.244.0.1/32 via 10.244.0.1
$ ip r
default via 10.244.0.1 dev eth0 
10.244.0.0/24 dev eth0  src 10.244.0.174 
10.244.0.0/16 via 10.244.0.1 dev eth0 
10.244.0.1 via 10.244.0.1 dev eth0 
$ ping google.com
PING google.com (172.217.2.174): 56 data bytes
64 bytes from 172.217.2.174: seq=0 ttl=52 time=17.615 ms
64 bytes from 172.217.2.174: seq=1 ttl=52 time=16.525 ms
64 bytes from 172.217.2.174: seq=2 ttl=52 time=14.861 ms
```

**Comment by mlsorensen** [comment]
When the gateway is in my lease file, as well as the classless-static-routes, yes, I don't get a gateway, only the static route. I'm not sure if this is strictly a dhclient behavior when the static route matches the gateway.

When manually adjusting things I also tried your test and noticed this:

```
[root@fedora ~]# ip route add 169.254.1.1 via 169.254.1.1 dev eth0 proto static
RTNETLINK answers: Network is unreachable

[root@fedora ~]# ip route show
default via 169.254.1.1 dev eth0
```

So there may also be something specifically related to the network plugins using link-local to do its thing.

At any rate if this route isn't necessary for the previous fix to work then perhaps it's ok to filter it out per pull #846 , as it seems to fix my problem and I'm not sure there is a need to have a static route to reach the default gateway.

**Comment by vladikr** [comment]
> At any rate if this route isn't necessary for the previous fix to work then perhaps it's ok to filter it out per pull #846 , as it seems to fix my problem and I'm not sure there is a need to have a static route to reach the default gateway.

Yes, I agree. This route doesn't seem to be necessary.

**Comment by rmohr** [comment]
To quote @karmab :

```
karimb:  hello folks
karimb:  after trying latest prerelease, i can confirm that network connectivity with several nodes works fine on openshift
karimb:  i do have an issue though, it seems that the vms lack a default route (which also implies dns doesnt work anymore, despite getting the nameservers from the pod )
```

He uses https://github.com/kubevirt/kubevirt/releases/tag/v0.4.0-alpha.2 which should contain al relevant fixes. This sounds like we still have an issue here. @karmab do you have more relevant info to share?

**Comment by karmab** [comment]
@rmohr additionally, note that manually adding the default gateway in the vm gave it 
- outside connectivity
- proper dns resolution ( within the cluster in particular)

**Comment by mlsorensen** [comment]
I'd try to help, but I don't have an Openshift installation to try this on.  

Per the code it seemed as though routes[0] was the default gateway, and this change is only filtering routes[1:] if it finds a static route for the gateway. 

I'm guessing what must happen on Openshift is that it creates a static route to define how to reach the gateway IP, and then defines the gateway IP as the default. Now that the static route is missing, the latter part fails with something like "Network is unreachable". Though karmab mentions it was possible to add the gateway, so I'm not sure what gives.

Here's an example of what I mean. If I start with a blank slate routing table, and assuming my gateway is not in the subnet of the IP my server has:

```
# blank table
[root@fedora-ssh ~]# ip route show
[root@fedora-ssh ~]#

# add default gateway that is not on my system's layer 2
[root@fedora-ssh ~]# ip route add default via 10.10.10.1 dev eth0
RTNETLINK answers: Network is unreachable

# add static route first, the kind of route being filtered out
[root@fedora-ssh ~]# ip route add 10.10.10.1 dev eth0
[root@fedora-ssh ~]# ip route add default via 10.10.10.1 dev eth0
[root@fedora-ssh ~]# ip route show
default via 10.10.10.1 dev eth0
10.10.10.1 dev eth0 scope link
```

Here's the thing, it seems dhclient does this without needing an explicit static route, adding a static route automatically for the "option routers". Reflecting the static route up from pod to VM should end up as a duplicate, and in my case seemed to actually break things.

I guess it would be helpful to see a dhclient lease file from an openshift instance that is not getting its gateway set with the current code, as well as a dump of the routes and the IP address it has. Would be nice to compare to one that works, too.

It's possible to tighten the filter down to only apply to link-local, however I don't like the idea of baking in workarounds for network-plugin specific idiosyncrasies. From what I can tell, filtering out the static route to gateway is the right thing to do, we just need to figure out why Openshift-hosted VMs don't get a gateway.

**Comment by cynepco3hahue** [comment]
@mlsorensen You can start OpenShift environment locally(you just need some amount of memory), just run:
```
export PROVIDER=os-3.9.0-alpha.4
export VAGRANT_NUM_NODES=1 # for multi-node environment
make cluster-up
```
We have some problem with connectivity between nodes, but this PR must fix it https://github.com/kubevirt/kubevirt/pull/867

**Comment by mlsorensen** [comment]
Thanks, I'll give it a shot.

**Comment by vladikr** [comment]
So far we've noticed that a cirros and windows VMs get a correct default gateway. However, Fedora fails to set a gw.

**Comment by vladikr** [comment]
Here is a lease file from the Fedora vm:
```
cat /var/lib/dhclient/dhclient--eth0.lease                                                                                                                |
default-duid "\000\004>\254R\327_\035M\232\250\370\024^z\252\0360";
lease {
  interface "eth0";
  fixed-address 10.130.0.36;
  option subnet-mask 255.255.254.0;
  option routers 10.130.0.1;
  option dhcp-lease-time 86313600;
  option dhcp-message-type 5;
  option domain-name-servers 10.19.138.73;
  option dhcp-server-identifier 10.11.12.13;
  option domain-search "vladik.svc.cluster.local.", "svc.cluster.local.", "cluster.local.", "cloud.lab.eng.bos.redhat.com.";
  option classless-static-routes 14.10.128 0.0.0.0,4.224 0.0.0.0;
  renew 2 2019/07/09 17:11:51;
  rebind 2 2020/08/25 21:51:47;
  expire 1 2020/12/28 18:51:47;
}
```
All routes were set except for the default gateway:

```
ip r                                                                                                                                                      |
10.128.0.0/14 dev eth0 proto static scope link 
10.130.0.0/23 dev eth0 proto kernel scope link src 10.130.0.36 
224.0.0.0/4 dev eth0 proto static scope link 
```

**Comment by mlsorensen** [comment]
One interesting thing, the issue I saw was also on Fedora, and filtering out the duplicate static route for default gateway effectively removed the classless-static-routes option. Maybe this is the same issue, and fedora's network setup just doesn't work right when classless static routes are provided.

**Comment by mlsorensen** [comment]
Ah:

"If the DHCP server returns both a Classless Static Routes option and
   a Router option, the DHCP client MUST ignore the Router option."

https://www.ietf.org/rfc/rfc3442.txt

So the addition of #830 effectively breaks "options router", if the DHCP client implements and adheres to rfc3442. This was probably my core issue, not as previously thought.

The routes could be moved to DHCP option 33 perhaps, or we may instead need to create the default route via classless-static-routes. Options router should probably still be provided for backward compatibility.

**Comment by vladikr** [comment]
@mlsorensen Thanks for looking into this!
I think you are right. According to [1] we should be able to set the default route using option 121
(Is it {0,defaultgateway} ?)

What do you see that is not working right on openshift?

[1] https://github.com/systemd/systemd/issues/7792#issuecomment-355301355

**Comment by mlsorensen** [comment]
Ah, I think FormClasslessStaticRoutes isn't accounting for the '0' case in RFC3442's table below, as the smallest mask it will currently return is 1.  Let me try that out...

```
Width of subnet mask     Number of significant octets
                     0                     0
                  1- 8                     1
                  9-16                     2
                 17-24                     3
                 25-32                     4
```

**Comment by mlsorensen** [comment]
Woohoo, success. I'll put together a pull request in a bit.

**Comment by mlsorensen** [comment]
OpenShift + fedora:
```
[fedora@fedora-ephemeral ~]$ ip route show
default via 10.129.0.1 dev eth0
10.128.0.0/14 dev eth0 proto static scope link
10.129.0.0/23 dev eth0 proto kernel scope link src 10.129.0.13
224.0.0.0/4 dev eth0 proto static scope link
[fedora@fedora-ephemeral ~]$ [  166.179394] random: crng init done


[fedora@fedora-ephemeral ~]$ ping google.com
ping google.com
PING google.com (172.217.6.78) 56(84) bytes of data.
64 bytes from sfo07s17-in-f78.1e100.net (172.217.6.78): icmp_seq=1 ttl=50 time=27.6 ms
```
OpenShift + Cirros:
```
$ ip route show
default via 10.128.0.1 dev eth0
10.128.0.0/23 dev eth0  src 10.128.0.31
10.128.0.0/14 dev eth0
224.0.0.0/4 dev eth0

$ ping google.com
ping google.com
PING google.com (172.217.2.14): 56 data bytes
64 bytes from 172.217.2.14: seq=0 ttl=51 time=39.185 ms
```

Vanilla Kubernetes  + Calico:
```
[fedora@fedora-ssh3 ~]$ ip route show
default via 169.254.1.1 dev eth0
169.254.1.1 dev eth0 scope link

[fedora@fedora-ssh3 ~]$ ping apple.com
PING apple.com (17.172.224.47) 56(84) bytes of data.
64 bytes from apple.com (17.172.224.47): icmp_seq=1 ttl=234 time=63.1 ms
```
