### ISSUE TITLE
KubeVirt windows VM is very slow when accessed through virtvnc

### ISSUE THREAD

**Issue by hanuunah** [kubevirt/kubevirt#8457]
Hello,

I have deployed Windows VM in Kubernetes cluster using Kubevirt and accessed through over browser using virtvnc
Its performance is not good and delayed streaming over the browser.

Could you please help on this matter.   

Thanks,
Hanumanthe

**Comment by chenxinlong** [comment]
Same problem haven't solved it yet, you can also check out this link : https://github.com/wavezhang/virtVNC/issues/4

**Comment by yeahdongcn** [comment]
How about switching to `VNC viewer`? BTW, I'm using `virtctl vnc` to do the proxy and `VNC viewer` works great.

**Comment by chenxinlong** [comment]
@yeahdongcn  Hi, any details about the `VNC viewer` you mentioned upon ?

**Comment by yeahdongcn** [comment]
https://www.realvnc.com/en/connect/download/viewer/

**Comment by hanuunah** [comment]
Thanks for the response.
I am particularly looking for clientless and accessing VM over browser solutions.

**Comment by chenxinlong** [comment]
* vnc server : `virtctl vnc <vmi> -n <namespace> --proxy-only --address=0.0.0.0`   
* vnc client(or vnc viewer) : using realVNC 

It's still very slow .  But when I change the "Picture quality" option to "Low" on realVNC , this problem has been significantly improved..
