### ISSUE TITLE
VMI got stuck in scheduling status due to the resource race condition

### ISSUE THREAD

**Issue by yangxiaoliang** [kubevirt/kubevirt#8487]
**What happened**:
Create VMs with some different time interval (say 30 seconds or 1 minute), sometimes two or more VMs will be scheduled to same node, but actually the node don't have enough resources to running so many VMs, so after the vm disk image is created or imported by the cdi importer pod, VMI will be got stuck in scheduling status due to no available resources.

The reason why kube-scheduler scheduled so many VMs to the node (more than the node's ability)  is because after the WaitForFirstConsumer temporary pod was deleted, the cpu/memory resources which consumed by temporary pod was released accordingly, then the kube-scheduler assessed the node was available to schedule more VMs. So when the VM virt-launcher pod was ready to start, there was already no resources left.

How to resolve this race condition issue, update kube-scheduler or kubevirt, I need your help, thanks very much~

**What you expected to happen**:
Don't release the cpu/memory resources after temporary pod is deleted;

or

Don't schedule additional VMs to a node if the node don't have additional ability to running more VMs;

**How to reproduce it (as minimally and precisely as possible)**:
Step 1: request to create 3 VMs at a time, and wait the temporary pod to exist;
Step 2: after the temporary pod is deleted, request to create another 3 new VMs at a time, and wait the new 3 temporary pod to be deleted;
Step 3: repeat step1 and step2, this will cased some VMI got stuck in scheduling status

**Additional context**:
Some error logs of `kubectl describe vmi `

```
Status:
  Active Pods:
    a5436b49-2470-4830-bf36-a8db9de410cd:
  Conditions:
    Last Probe Time:       <nil>
    Last Transition Time:  2022-09-19T01:53:36Z
    Message:               0/122 nodes are available: 1 node(s) had taints that the pod didn't tolerate, 1 node(s) has the same appkey pods more than toleration, 11 Insufficient memory, 47 node(s) had volume node affinity conflict, 5 node(s) were unschedulable, 57 node(s) didn't match node selector.
    Reason:                Unschedulable
    Status:                False
    Type:                  PodScheduled
  Guest OS Info:
  Phase:  Scheduling
  Phase Transition Timestamps:
    Phase:                       Scheduling
    Phase Transition Timestamp:  2022-09-19T01:53:38Z
  Qos Class:                     Burstable
Events:
  Type    Reason            Age                    From                       Message
  ----    ------            ----                   ----                       -------
  Normal  SuccessfulDelete  3m28s (x3 over 3m33s)  virtualmachine-controller  Deleted WaitForFirstConsumer temporary pod virt-launcher-vm-gh-talos-ci160-abc
  Normal  SuccessfulCreate  49s (x2 over 3m36s)    virtualmachine-controller  Created virtual machine pod virt-launcher-vm-gh-talos-ci160-abc
```

**Environment**:
- KubeVirt version (use `virtctl version`):  v0.43.0
- Kubernetes version (use `kubectl version`): 1.16
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by xpivarc** [comment]
Hi,
I don't think there is a way for us to address this issue. I think populators could do the job in the future. @mhenriks fyi

**Comment by yangxiaoliang** [comment]
> Hi, I don't think there is a way for us to address this issue. I think populators could do the job in the future. @mhenriks fyi

Hi @xpivarc , Is that a possible way to start another temporary pod along with WFFC temporary pod to occupy the node resources? then if the WaitForFirstConsumer temporary pod is deleted, the node resources would still be occupied, this will prevent kube-scheduler to schedule new VMs to this node. Do you have any suggestion ?

**Comment by mhenriks** [comment]
Yeah this is a difficult problem that should get solved with volume populators.

**Comment by yangxiaoliang** [comment]
> Yeah this is a difficult problem that should get solved with volume populators.

@mhenriks  How do you solve this problem in you product environment, any workaround or suggestion ? Do you update the kube-scheduler logic? And could you post some link or introduction on "volume populators" , thanks ~

**Comment by yangxiaoliang** [comment]
> Hi, I don't think there is a way for us to address this issue. I think populators could do the job in the future. @mhenriks fyi

Hi @mhenriks  @xpivarc , 

I am wondering if it's  possible to add an initContainer into the virt-launcher pod, then the initContainer conduct image pull and import to PVC instead of CDI importer pod ? Could you help to provide some comments?  Thanks a lot.

**Comment by xpivarc** [comment]
> > Hi, I don't think there is a way for us to address this issue. I think populators could do the job in the future. @mhenriks fyi
> 
> Hi @mhenriks @xpivarc ,
> 
> I am wondering if it's possible to add an initContainer into the virt-launcher pod, then the initContainer conduct image pull and import to PVC instead of CDI importer pod ? Could you help to provide some comments? Thanks a lot.

You could use a mutating webhook to achieve this.
