### ISSUE TITLE
How to expand vm's / directory of ubuntu?

### ISSUE THREAD

**Issue by joeevon** [kubevirt/kubevirt#8502]
yaml of vmi:
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  finalizers:
  - kubevirt.io/virtualMachineControllerFinalize
  - foregroundDeleteVirtualMachine
  generation: 12
  labels:
    kubevirt.io/nodeName: kcp02
  name: vm-wzymanualcreate
  namespace: wzy
  ownerReferences:
  - apiVersion: kubevirt.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachine
    name: vm-wzymanualcreate
    uid: e1db97d2-ac95-4149-9109-6a545344cb07
  resourceVersion: "13766977"
  uid: a0a56beb-82cb-4e2b-b635-59e1b2fd09a4
spec:
  domain:
    cpu:
      cores: 4
      model: host-model
    devices:
      disks:
      - disk:
          bus: virtio
        name: cloudinitdisk
      - bootOrder: 1
        disk:
          bus: virtio
        name: sysdisk
      interfaces:
      - bridge: {}
        name: default
    features:
      acpi:
        enabled: true
    firmware:
      uuid: 601e4df3-4dc6-587d-a8ed-8ad795808746
    machine:
      type: q35
    resources:
      requests:
        memory: 8Gi
  networks:
  - name: default
    pod: {}
  volumes:
  - cloudInitNoCloud:
      userDataBase64: JTIzY2xvdWQtY29uZmlnJTBBdXBkYXRlcyUzQSUwQSUyMCUyMG5ldHdvcmslM0ElMEElMjAlMjAlMjAlMjB3aGVuJTNBJTIwJTVCJTI3Ym9vdCUyNyU1RCUwQXRpbWV6b25lJTNBJTIwRXRjL1VUQyUwQXBhY2thZ2VzJTNBJTBBJTIwLSUyMGNsb3VkLWluaXQlMEFwYWNrYWdlX3VwZGF0ZSUzQSUyMHRydWUlMEFzc2hfcHdhdXRoJTNBJTIwdHJ1ZSUwQWRpc2FibGVfcm9vdCUzQSUyMGZhbHNlJTBBY2hwYXNzd2QlM0ElMjAlN0IlMjJsaXN0JTIyJTNBJTIycm9vdCUzQTEyMzQ1NiUyMiUyQ2V4cGlyZSUzQSUyMEZhbHNlJTdEJTBBcnVuY21kJTNBJTBBJTIwLSUyMHNlZCUyMC1pJTIwJTIyL1Blcm1pdFJvb3RMb2dpbi9zLyU1RS4qJTI0L1Blcm1pdFJvb3RMb2dpbiUyMHllcy9nJTIyJTIwL2V0Yy9zc2gvc3NoZF9jb25maWclMEElMjAtJTIwc3NoLWtleWdlbiUyMC1BJTBBJTIwLSUyMHN5c3RlbWN0bCUyMHJlc3RhcnQlMjBzc2hkLnNlcnZpY2UlMEE=
    name: cloudinitdisk
  - name: sysdisk
    persistentVolumeClaim:
      claimName: vol-1234567890

pvc:
![image](https://user-images.githubusercontent.com/12859282/191553444-09758ab9-3b6a-4617-806a-089c803bd2a1.png)

instance:
![image](https://user-images.githubusercontent.com/12859282/191553827-6fb0845b-5e98-4807-adb2-de35b9b68480.png)

as stated above, i create a datavolume which pvc storage is 60Gi, but when i login in to the instance, the / directory is only 4.8Gi.
How can i expand / to 60Gi? 
Thanks for your guidance!

**Comment by awels** [comment]
So CDI (and KubeVirt) only resize the virtual disks but not partitions on those disks. We don't do this because we don't know which partition (if there are multiple) you want to resize, and there is currently no mechanism for the user to specify.

We recommend the user manually resize the partition based on the guest OS. Most people use either a cloud init (or sysprep) to resize the appropriate partition during the first startup. I usually use gparted for any type of linux.

**Comment by joeevon** [comment]
thanks so much

**Comment by joeevon** [comment]
> So CDI (and KubeVirt) only resize the virtual disks but not partitions on those disks. We don't do this because we don't know which partition (if there are multiple) you want to resize, and there is currently no mechanism for the user to specify.
> 
> We recommend the user manually resize the partition based on the guest OS. Most people use either a cloud init (or sysprep) to resize the appropriate partition during the first startup. I usually use gparted for any type of linux.

thanks so much
