### ISSUE TITLE
cloudInitNoCloud not work, how can i ensure cloudInitNoCloud was correctly called?

### ISSUE THREAD

**Issue by joeevon** [kubevirt/kubevirt#8503]
vmi yaml:
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  finalizers:
  - kubevirt.io/virtualMachineControllerFinalize
  - foregroundDeleteVirtualMachine
  generation: 12
  labels:
    kubevirt.io/nodeName: kcp02
  name: vm-wzymanualcreate
  namespace: wzy
  ownerReferences:
  - apiVersion: kubevirt.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachine
    name: vm-wzymanualcreate
    uid: e1db97d2-ac95-4149-9109-6a545344cb07
  resourceVersion: "13766977"
  uid: a0a56beb-82cb-4e2b-b635-59e1b2fd09a4
spec:
  domain:
    cpu:
      cores: 4
      model: host-model
    devices:
      disks:
      - disk:
          bus: virtio
        name: cloudinitdisk
      - bootOrder: 1
        disk:
          bus: virtio
        name: sysdisk
      interfaces:
      - bridge: {}
        name: default
    features:
      acpi:
        enabled: true
    firmware:
      uuid: 601e4df3-4dc6-587d-a8ed-8ad795808746
    machine:
      type: q35
    resources:
      requests:
        memory: 8Gi
  networks:
  - name: default
    pod: {}
  volumes:
  - cloudInitNoCloud:
      userDataBase64: JTIzY2xvdWQtY29uZmlnJTBBdXBkYXRlcyUzQSUwQSUyMCUyMG5ldHdvcmslM0ElMEElMjAlMjAlMjAlMjB3aGVuJTNBJTIwJTVCJTI3Ym9vdCUyNyU1RCUwQXRpbWV6b25lJTNBJTIwRXRjL1VUQyUwQXBhY2thZ2VzJTNBJTBBJTIwLSUyMGNsb3VkLWluaXQlMEFwYWNrYWdlX3VwZGF0ZSUzQSUyMHRydWUlMEFzc2hfcHdhdXRoJTNBJTIwdHJ1ZSUwQWRpc2FibGVfcm9vdCUzQSUyMGZhbHNlJTBBY2hwYXNzd2QlM0ElMjAlN0IlMjJsaXN0JTIyJTNBJTIycm9vdCUzQTEyMzQ1NiUyMiUyQ2V4cGlyZSUzQSUyMEZhbHNlJTdEJTBBcnVuY21kJTNBJTBBJTIwLSUyMHNlZCUyMC1pJTIwJTIyL1Blcm1pdFJvb3RMb2dpbi9zLyU1RS4qJTI0L1Blcm1pdFJvb3RMb2dpbiUyMHllcy9nJTIyJTIwL2V0Yy9zc2gvc3NoZF9jb25maWclMEElMjAtJTIwc3NoLWtleWdlbiUyMC1BJTBBJTIwLSUyMHN5c3RlbWN0bCUyMHJlc3RhcnQlMjBzc2hkLnNlcnZpY2UlMEE=
    name: cloudinitdisk
  - name: sysdisk
    persistentVolumeClaim:
      claimName: vol-1234567890

------------------------------------------------------------

base64 decode of cloudInitNoCloud:
#cloud-config
updates:
  network:
    when: ['boot']
timezone: Etc/UTC
packages:
 - cloud-init
package_update: true
ssh_pwauth: true
disable_root: false
chpasswd: {"list":"root:123456",expire: False}
runcmd:
 - sed -i "/PermitRootLogin/s/^.*$/PermitRootLogin yes/g" /etc/ssh/sshd_config
 - ssh-keygen -A
 - systemctl restart sshd.service

--------------------------------------------------------------------

as stated above, i found cloudInitNoCloud in yaml no work, how can i ensure cloudInitNoCloud was correctly called?
Thanks for your guidance!

**Comment by awels** [comment]
Can you try cloud init with something simpler, I suspect there is bug/typo in the one you have. https://kubevirt.io/user-guide/virtual_machines/startup_scripts/ should have some simple examples that should work.

**Comment by joeevon** [comment]
> Can you try cloud init with something simpler, I suspect there is bug/typo in the one you have. https://kubevirt.io/user-guide/virtual_machines/startup_scripts/ should have some simple examples that should work.

thanks so much
