### ISSUE TITLE
How to expand system disk of windows?

### ISSUE THREAD

**Issue by joeevon** [kubevirt/kubevirt#8504]
vmi yaml:
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubesphere.io/creator: wangzy
    kubesphere.io/system: windows
  name: vm-manualwindows
  namespace: wzy
spec:
  running: true
  template:
    metadata:
      annotations:
        ovn.kubernetes.io/ip_address: 172.16.0.8
        ovn.kubernetes.io/logical_switch: subnet-1xf7a8i2ceebnnqejzjak
        ovn.kubernetes.io/mac_address: "00:00:00:03:42:07"
    spec:
      domain:
        cpu:
          cores: 8
        devices:
          disks:
          - disk:
              bus: virtio
            name: cloudinitdisk
          - cdrom:
              bus: sata
            name: virtiocontainerdisk
          - bootOrder: 1
            disk:
              bus: virtio
            name: sysdisk
          interfaces:
          - bridge: {}
            name: default
        firmware:
          bootloader:
            efi:
              secureBoot: false
        machine:
          type: q35
        resources:
          requests:
            memory: 16Gi
      networks:
      - name: default
        pod: {}
      volumes:
      - cloudInitNoCloud:
          userDataBase64: JTVCREVGQVVMVCU1RCUwQXVzZXJuYW1lJTNEQWRtaW5pc3RyYXRvciUwQWdyb3VwcyUzREFkbWluaXN0cmF0b3JzJTBBbmV0Ymlvc19ob3N0X25hbWVfY29tcGF0aWJpbGl0eSUzRGZhbHNlJTBBaW5qZWN0X3VzZXJfcGFzc3dvcmQlM0R0cnVlJTBBY29uZmlnX2RyaXZlX3Jhd19oaGQlM0R0cnVlJTBBY29uZmlnX2RyaXZlX2Nkcm9tJTNEdHJ1ZSUwQWNvbmZpZ19kcml2ZV92ZmF0JTNEdHJ1ZSUwQWJzZHRhcl9wYXRoJTNEQyUzQSU1Q1Byb2dyYW0lMjBGaWxlcyU1Q0Nsb3VkYmFzZSUyMFNvbHV0aW9ucyU1Q0Nsb3VkYmFzZS1Jbml0JTVDYmluJTVDYnNkdGFyLmV4ZSUwQW10b29sc19wYXRoJTNEQyUzQSU1Q1Byb2dyYW0lMjBGaWxlcyU1Q0Nsb3VkYmFzZSUyMFNvbHV0aW9ucyU1Q0Nsb3VkYmFzZS1Jbml0JTVDYmluJTVDJTBBdmVyYm9zZSUzRHRydWUlMEFkZWJ1ZyUzRHRydWUlMEFsb2dkaXIlM0RDJTNBJTVDUHJvZ3JhbSUyMEZpbGVzJTVDQ2xvdWRiYXNlJTIwU29sdXRpb25zJTVDQ2xvdWRiYXNlLUluaXQlNUNsb2clNUMlMEFsb2dmaWxlJTNEY2xvdWRiYXNlLWluaXQubG9nJTBBZGVmYXVsdF9sb2dfbGV2ZWxzJTNEY29tdHlwZXMlM0RJTkZPJTJDc3VkcyUzRElORk8lMkNpc284NjAxJTNEV0FSTiUyQ3JlcXVlc3RzJTNEV0FSTiUwQWxvZ2dpbmdfc2VyaWFsX3BvcnRfc2V0dGluZ3MlM0QlMEFtdHVfdXNlX2RoY3BfY29uZmlnJTNEdHJ1ZSUwQW50cF91c2VfZGhjcF9jb25maWclM0R0cnVlJTBBZmlyc3RfbG9nb25fYmVoYXZpb3VyJTNEbm8lMEFsb2NhbF9zY3JpcHRzX3BhdGglM0RDJTNBJTVDUHJvZ3JhbSUyMEZpbGVzJTVDQ2xvdWRiYXNlJTIwU29sdXRpb25zJTVDQ2xvdWRiYXNlLUluaXQlNUNMb2NhbFNjcmlwdHMlNUMlMEFjaGVja19sYXRlc3RfdmVyc2lvbiUzRGZhbHNlJTBBbWV0YWRhdGFfc2VydmljZXMlM0RjbG91ZGJhc2Vpbml0Lm1ldGFkYXRhLnNlcnZpY2VzLmh0dHBzZXJ2aWNlLkh0dHBTZXJ2aWNlJTBBcGx1Z2lucyUzRGNsb3VkYmFzZWluaXQucGx1Z2lucy5jb21tb24ubG9jYWxzY3JpcHRzLkxvY2FsU2NyaXB0c1BsdWdpbiUyQ2Nsb3VkYmFzZWluaXQucGx1Z2lucy5jb21tb24ubXR1Lk1UVVBsdWdpbiUyQ2Nsb3VkYmFzZWluaXQucGx1Z2lucy53aW5kb3dzLmNyZWF0ZXVzZXIuQ3JlYXRlVXNlclBsdWdpbiUyQ2Nsb3VkYmFzZWluaXQucGx1Z2lucy5jb21tb24uc2V0dXNlcnBhc3N3b3JkLlNldFVzZXJQYXNzd29yZFBsdWdpbiUyQ2Nsb3VkYmFzZWluaXQucGx1Z2lucy5jb21tb24uc3NocHVibGlja2V5cy5TZXRVc2VyU1NIUHVibGljS2V5c1BsdWdpbiUyQ2Nsb3VkYmFzZWluaXQucGx1Z2lucy53aW5kb3dzLnVwZGF0ZXMuV2luZG93c0F1dG9VcGRhdGVzUGx1Z2luJTJDY2xvdWRiYXNlaW5pdC5wbHVnaW5zLmNvbW1vbi5zZXRob3N0bmFtZS5TZXRIb3N0TmFtZVBsdWdpbiUyQ2Nsb3VkYmFzZWluaXQucGx1Z2lucy53aW5kb3dzLmV4dGVuZHZvbHVtZXMuRXh0ZW5kVm9sdW1lc1BsdWdpbiUyQ2Nsb3VkYmFzZWluaXQucGx1Z2lucy5jb21tb24udXNlcmRhdGEuVXNlckRhdGFQbHVnaW4lMkNjbG91ZGJhc2Vpbml0LnBsdWdpbnMud2luZG93cy53aW5ybWxpc3RlbmVyLkNvbmZpZ1dpblJNTGlzdGVuZXJQbHVnaW4lMkNjbG91ZGJhc2Vpbml0LnBsdWdpbnMud2luZG93cy53aW5ybWNlcnRpZmljYXRlYXV0aC5Db25maWdXaW5STUNlcnRpZmljYXRlQXV0aFBsdWdpbiUyQ2Nsb3VkYmFzZWluaXQucGx1Z2lucy53aW5kb3dzLmxpY2Vuc2luZy5XaW5kb3dzTGljZW5zaW5nUGx1Z2luJTJDY2xvdWRiYXNlaW5pdC5wbHVnaW5zLmNvbW1vbi5uZXR3b3JrY29uZmlnLk5ldHdvcmtDb25maWdQbHVnaW4lMEFhbGxvd19yZWJvb3QlM0RmYWxzZQ==
        name: cloudinitdisk
      - containerDisk:
          image: kubevirt/virtio-container-disk
          imagePullPolicy: IfNotPresent
        name: virtiocontainerdisk
      - name: sysdisk
        persistentVolumeClaim:
          claimName: vol-windows

-----------------------------------------------------------------------------------------------------------

pvc:
![image](https://user-images.githubusercontent.com/12859282/191561459-9f930605-8df0-4584-9d46-4d4bab02c8c4.png)

------------------------------------------------------------------------------------------------------------

instance:
![image](https://user-images.githubusercontent.com/12859282/191561612-91687d12-70e4-4953-9fff-54147b4c5e70.png)

![image](https://user-images.githubusercontent.com/12859282/191561728-d2356384-40d1-4b58-9053-549f27df7d81.png)

![image](https://user-images.githubusercontent.com/12859282/191561845-be2f181a-1bca-4f84-ba5b-4b8d83eabf54.png)

---------------------------------------------------------------------------------------------------------------

as stated above, i create a datavolume which pvc storage is 60Gi, but when i login in to the instance, the system disk is only 32Gi.
How can i automatic expand system disk to 60Gi?
Thanks for your guidance!

**Comment by coldzerofear** [comment]
use cloudbase-init

**Comment by coldzerofear** [comment]
install cloudbase-init

**Comment by awels** [comment]
So CDI (and KubeVirt) only resize the virtual disks but not partitions on those disks. We don't do this because we don't know which partition (if there are multiple) you want to resize, and there is currently no mechanism for the user to specify.

We recommend the user manually resize the partition based on the guest OS. Most people use either a cloud init (or sysprep) to resize the appropriate partition during the first startup.

**Comment by joeevon** [comment]
> So CDI (and KubeVirt) only resize the virtual disks but not partitions on those disks. We don't do this because we don't know which partition (if there are multiple) you want to resize, and there is currently no mechanism for the user to specify.
> 
> We recommend the user manually resize the partition based on the guest OS. Most people use either a cloud init (or sysprep) to resize the appropriate partition during the first startup.

thanks so much
