### ISSUE TITLE
How to decide/schedule in which physical machine to create VM ?

### ISSUE THREAD

**Issue by victory460** [kubevirt/kubevirt#8506]
This is a perfect project. I have some question following:

How to decide/schedule in which physical machine to create VM ? Which component to do it? virt-handler or virt-controller? where code or document about this？

**Comment by iholder-redhat** [comment]
Hey @victory460!

virt-controller is the component that creates virt-launcher Pod which actually runs the VM, so I suggest to refer to virt-controller's code to see how it schedules this pod. You can start with [renderLaunchManifest](https://github.com/kubevirt/kubevirt/blob/v0.57.1/pkg/virt-controller/services/template.go#L385) function which is used to create the virt-launcher Pod.

**Comment by chenxinlong** [comment]
A vm is a pod(virt-launcher) runs on kubernetes clusters, so I'd say kube-scheduler decides where the pod(vm) goes . 

The factor we can affect the schedule result is : 

1. The node selector property of the virtual machine instance CR 
2. The scheduler name of the virtual machine instance CR 
3. The affinity of the virtual machine instance CR 
4. ...

See codes below : 

https://github.com/kubevirt/kubevirt/blob/c7d77091bbf25125a6a4e4821f014d04de116d52/staging/src/kubevirt.io/api/core/v1/types.go#L79-L100
