### ISSUE TITLE
How to set clock offset to localtime ? 

### ISSUE THREAD

**Issue by chenxinlong** [kubevirt/kubevirt#8507]
Hi, 

There's a `localtime` option in libvirt clock offset (see [time keeping](https://libvirt.org/formatdomain.html#time-keeping) ). How to set the clock offset to `localtime` in libvirt domain xml ?  I've tried serveral composition of `spec.domain.clock` but it didn't work.

**Comment by dhiller** [comment]
/triage needs-information

Could you post you vm yaml here so that we know what you have configured?

**Comment by PiotrProkop** [comment]
I think the only options for clock `offset` Kubevirt supports are `utc` and `timezone`. Look here https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-launcher/virtwrap/converter/converter.go#L992

**Comment by chenxinlong** [comment]
@dhiller 

There should be four options for clock `offset` which is variable, timezone, utc and localtime(described in https://libvirt.org/formatdomain.html#time-keeping). But seems kubevirt does not support the localtime option as @PiotrProkop  metioned upon.

Is it how kubevirt designed ? Or it's a bug ?

**Comment by vladikr** [comment]
@chenxinlong this option simply wasn't exposed on our VMI API. Perhaps you can send a PR to add this, followed by an explanation for why is this required (I'd assume windows?).

**Comment by chenxinlong** [comment]
@vladikr  My requirement described in https://github.com/kubevirt/kubevirt/issues/8519 . 

> this option simply wasn't exposed on our VMI API. 

Why not exposed `localtime` option ? Is there any concerns ?

**Comment by chenxinlong** [comment]
@vladikr  

> I'd assume windows? 

Yes, windows guest treat rtc(real-time clock) as local time.  Besides, I think it's necessary to expose `localtime` offset option to satisfy variant requirements. 

Finally I used a workaround to let windows guest aware that rtc is utc which described in https://fishilico.github.io/generic-config/windows/utc-clock.html

**Comment by chenxinlong** [comment]
Also, I  can use hook sidecar to manipulate domain xml. But I think it's necessary to expose `localtime` clock offset to user.
