### ISSUE TITLE
keep virt-launcher timezone same with host os

### ISSUE THREAD

**Issue by chenxinlong** [kubevirt/kubevirt#8519]
```
guest os 
-----------------
virt-launcher(pod)
-----------------
host os 
```

Guest os runs on pod(which is utc as default) , pod runs on host os. For guest os , the host os is the virt-launcher pod.  What I expected is keep the timezone of guest os same with host os(the bottom layer) when a new vm is created.  So my solution is : 

1. Step1: Set the timezone of virt-launcher same with host os 
2. Step2: Set the domain xml `clock offset`of guest os  to `localtime`

But my problem is : 

1. For step1, I can't control the timezone of virt-launcher   
2. For step2, I can't found a way to set the `clock offset` to `localtime` by current VirtualMachine spec.

How to solve these 2 problem ? Or there's a better solution to fullfill my need ?

**Comment by vasiliy-ul** [comment]
There is some info in the user guide about setting the guest time: https://kubevirt.io/user-guide/virtual_machines/virtual_hardware/#guest-time

Might that help in solving your issue?
