### ISSUE TITLE
No connection on windows VM & associated virt-launcher pod 

### ISSUE THREAD

**Issue by anvarik** [kubevirt/kubevirt#8520]
**What happened**:
Followed [this guide](https://kubevirt.io/2020/KubeVirt-installing_Microsoft_Windows_from_an_iso.html) step by step, I managed to get the VM up and running. After setting it up and connecting to it with VNC I notice that though it doesn't have internet connection. When I go to the associated virt-launcher pod's compute container, I can't curl either. 

**What you expected to happen**:
Windows vm should have internet.

**How to reproduce it (as minimally and precisely as possible)**:
Followed the guide ( https://kubevirt.io/2020/KubeVirt-installing_Microsoft_Windows_from_an_iso.html ) on my minikube setup on WSL2, and upon completing it pod & vm had no connection.

**Additional context**:

**Environment**:
- KubeVirt version: v0.57.1
- Kubernetes version (use `kubectl version`): v1.24.0
- VM or VMI specifications: VM is 2012 R2 windows
- OS (e.g. from /etc/os-release): Windows WSL2
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by dhiller** [comment]
/triage needs-information

Could you post your vm yaml here so that we know what you have configured?

**Comment by anvarik** [comment]
Thanks for replying. This was due to the missing Network driver installation, I have blindly followed the guide in https://kubevirt.io/2020/KubeVirt-installing_Microsoft_Windows_from_an_iso.html and because it doesn't install the network driver there was no connection: `NetKVM\2k12R2\amd64`. Also moving to an actual cloud vendor helped, trying to make this work in a minikube environment is painful.
