### ISSUE TITLE
`virtctl memory-dump` results in an error

### ISSUE THREAD

**Issue by viveksinghggits** [kubevirt/kubevirt#8524]
**What happened**:
I was trying to get the memory dump of a VM, and ran below command to do that

```
./virtctl-v0.57.0-linux-amd64 memory-dump get rhel8-trusting-shaw --claim-name=memdump-pvc --create-claim
```

**What you expected to happen**:
I expected the memory dump to create created successfully. But got below output

```
PVC default/memdump-pvc created
You are using a client virtctl version that is different from the KubeVirt version running in the cluster
Client Version: v0.57.0
Server Version: v0.49.0-200-g328f5d8ca
error dumping vm memory, the server could not find the requested resource
```

**How to reproduce it (as minimally and precisely as possible)**:
Create  VM and try to run the above command. The CLI version and server version are mentioned in the above output.

**Additional context**:
I see the PVC that was created is in `Pending` state waiting for first consumer. If you think this is the problem, I can create the PVC first and then run the memory-dump command.

**Comment by viveksinghggits** [comment]
I tried to use the same version (`v0.49.0`) of CLI as to my server and it doesn't support `memory-dump` command.

**Comment by mhenriks** [comment]
@viveksinghggits yeah this is not in an OpenShift release yet

**Comment by viveksinghggits** [comment]
ok, thank you @mhenriks.
