### ISSUE TITLE
Support insert nic to vm and the nic doesn't need to bind cni

### ISSUE THREAD

**Issue by mayulin123456** [kubevirt/kubevirt#8533]
**Is your feature request related to a problem? Please describe**:
Recently, we want to insert kubevirt to Network Service Mesh(https://networkservicemesh.io/).
But we found an important problem. The problem is that kubevirt network is based on the cni and nsm(network service mesh) is independent of cni. So we request the feature. We want to insert the nic to vm and the nic doesn't need to bind cni. The nic can be bound to other pod network not cni. 

**Describe the solution you'd like**:
Maybe we can attach the network interface to vm and the network interface can be bound to other pod network not only cni. 

**Describe alternatives you've considered**:
Maybe if we can enter the pod to create nic and bridge manually. At present, if kubevirt can support it?

**Additional context**:
We think it is a big value thing. Because it is not only cni in k8s and may be have other network method. If the feature has been finished, the kubevirt will be further promoted.

**Comment by CL0Pinette** [comment]
Hello,
Is there any news about this ?
