### ISSUE TITLE
virt-handler stops working on versions greater than v0.55.0 on RHEL 8.6 nodes with selinux enforcing

### ISSUE THREAD

**Issue by shannonmitchell** [kubevirt/kubevirt#8544]
**What happened**:
We are running rke2 on RHEL8.6 with selinux set to enforcing.  After attempting to upgrade kubevirt, the virt-handler pods error out with the following virt-handler log failure:
```
...
"component":"virt-handler","level":"info","msg":"SELinux is reported as 'enforcing'","pos":"virt-handler.go:384","timestamp":"2022-09-29T18:18:24.591217Z"}
Error: error relabeling file /proc/self/fd/7 with label system_u:object_r:container_file_t:s0. Reason: operation not supported
Usage:
  virt-chroot selinux relabel [flags]

Examples:
virt-chroot selinux relabel <new-label> <file-path>

Flags:
  -h, --help          help for relabel
      --root string   safe root path which will be prepended to passed in files (default "/")

Global Flags:
      --cpu uint       cpu time in seconds for the process
      --memory uint    memory in bytes for the process
      --mount string   mount namespace to use
      --user string    switch to this targetUser to e.g. drop privileges

error relabeling file /proc/self/fd/7 with label system_u:object_r:container_file_t:s0. Reason: operation not supported
panic: error relabeling required files: error relabeling file root: /, relative: /dev/net/tun with label system_u:object_r:container_file_t:s0. Reason: exit status 1

goroutine 1 [running]:
main.(*virtHandlerApp).Run(0xc000306000)
	cmd/virt-handler/virt-handler.go:405 +0x2985
main.main()
	cmd/virt-handler/virt-handler.go:612 +0x54

```
After testing several versions, it looks like things work up to v0.55.0 and fail on v0.55.1 and above.  It looks like some changes were done to move to the golang.org.x/sys.unix for selinux labeling that might have broken things between those versions.  To verify, we set selinux to 'Permissive' on the kubernetes nodes and the virt-handler pods went into a 'running' state(but still displayed the error in the logs).

**What you expected to happen**:

virt-handler to start on versions greater than v0.55.0 on RHEL 8.6 based kubernetes nodes with selinux enabled.

**How to reproduce it (as minimally and precisely as possible)**:

Run kubernetes on RHEL 8.6 nodes with selinux enabled and run kubevirt greater than v0.55.0.

**Comment by xpivarc** [comment]
FYI @rmohr I believe we need to adjust https://github.com/kubevirt/kubevirt/pull/8198

**Comment by rmohr** [comment]
@xpivarc I think that

```
diff --git a/cmd/virt-chroot/selinux.go b/cmd/virt-chroot/selinux.go
index 4728e56..0166b3b 100644
--- a/cmd/virt-chroot/selinux.go
+++ b/cmd/virt-chroot/selinux.go
@@ -7,7 +7,6 @@
 	"os"
 	"path/filepath"
 
-	"github.com/opencontainers/selinux/go-selinux"
 	"github.com/spf13/cobra"
 	"golang.org/x/sys/unix"
 
@@ -67,10 +66,6 @@
 
 			defer fd.Close()
 			filePath := fd.SafePath()
-			currentFileLabel, err := selinux.FileLabel(filePath)
-			if err != nil {
-				return fmt.Errorf("could not retrieve label of file %s. Reason: %v", filePath, err)
-			}
 
 			writeableFD, err := os.OpenFile(filePath, os.O_APPEND|unix.S_IWRITE, os.ModePerm)
 			if err != nil {
@@ -78,6 +73,11 @@
 			}
 			defer writeableFD.Close()
 
+			currentFileLabel, err := getLabel(writeableFD)
+			if err != nil {
+				return fmt.Errorf("faild to get selinux label for file %v: %v", filePath, err)
+			}
+
 			if currentFileLabel != label {
 				if err := unix.Fsetxattr(int(writeableFD.Fd()), xattrNameSelinux, []byte(label), 0); err != nil {
 					return fmt.Errorf("error relabeling file %s from label %s to label %s. Reason: %v", filePath, currentFileLabel, label, err)
@@ -90,3 +90,22 @@
 	relabelCommad.Flags().StringVar(&root, "root", "/", "safe root path which will be prepended to passed in files")
 	return relabelCommad
 }
+
+func getLabel(file *os.File) (string, error) {
+	// let's first find out the actual buffer size
+	var buffer []byte
+	labelLength, err := unix.Fgetxattr(int(file.Fd()), xattrNameSelinux, buffer)
+	if err != nil {
+		return "", fmt.Errorf("error reading fgetxattr: %v", err)
+	}
+	// now ask with the needed size
+	buffer = make([]byte, labelLength)
+	labelLength, err = unix.Fgetxattr(int(file.Fd()), xattrNameSelinux, buffer)
+	if err != nil {
+		return "", fmt.Errorf("error reading fgetxattr: %v", err)
+	}
+	if labelLength > 0 && buffer[labelLength-1] == '\x00' {
+		labelLength = labelLength - 1
+	}
+	return string(buffer[:labelLength]), nil
+}
```

should fix it. Would you mind preparing a PR?

**Comment by rmohr** [comment]
What this does, is changing the code to only relabel if needed. The main issue is, that due to some bug somewhere, we don't read the correct label and think we need to change the label, while we don't. It looked to me more like a kernel change though. Since we only apply this relabel to work around a label bug, it should be fine. The label should nowadays be correct.

**Comment by rmohr** [comment]
/assign

Taking this for one of our engineers.

**Comment by xpivarc** [comment]
@rmohr I apologize for the late reply. I missed the notification. Thanks for taking this! I can't spot the difference between what our dependency does. Can you give me a hint?

**Comment by rmohr** [comment]
> @rmohr I apologize for the late reply. I missed the notification. Thanks for taking this! I can't spot the difference between what our dependency does. Can you give me a hint?

We right now open a file descriptor and then try to read the selinux label from it as if it were an ordinary file by taking the file descriptor path as filepath for `selinux.FileLabel`. This does not work on a small set of kernels (there seems to be a regression for some time, can't exactly say which kernels), but when using the filedescriptor with `unix.Fgetxattr`, reading the label always works.

With that change we correctly detect that we already have the right label, and we never try to write on these kernels.
