### ISSUE TITLE
DELETE doesn't return always return k8s.io.apimachinery.pkg.apis.meta.v1.Status like the OpenAPI spec says

### ISSUE THREAD

**Issue by rthallisey** [kubevirt/kubevirt#8547]
**What happened**:
The DELETE API call for a VMl can return 1 of 2 things:
1) k8s.io.apimachinery.pkg.apis.meta.v1.Status
2) v1alpha1.VirtualMachineInstancetype

To get 1), you have to edit the VMI and remove the finalizer, then delete the vmi. This is not how users normally delete VMIs.  Normally, the user will delete the vmi first, which returns 2).  This is because KubeVirt controls the VMI garbage collection, so a delete call from a client actually triggers an Update on the VMI, to add the DeletionTimestamp.

KubeVirt should have an opinion on which return type is used since there are two options.  Delete option 2, e.g. `$ kubectl delete vmi`, makes more sense since it's how users typically consume the API, which should return 1).  Having the correct value affects generated code, so any generated clients are likely the ignore the value in it's current state.

https://github.com/kubevirt/kubevirt/blob/main/api/openapi-spec/swagger.json#L1730

**Comment by larrydewey** [comment]
This may be a good option for the Hacktober fest? I am inclined to agree that option 2 does seem to make the most sense at first glance.

**Comment by rthallisey** [comment]
This is a good first issue.
