### ISSUE TITLE
can not rebinding GPU device to vfio because device with non-zero usage count

### ISSUE THREAD

**Issue by soulseen** [kubevirt/kubevirt#8549]
**What happened**:
I want to use the NVIDIA GPU device pass through mode with Kata Containers. but when I followed the [doc](https://github.com/kata-containers/kata-containers/blob/main/docs/use-cases/NVIDIA-GPU-passthrough-and-Kata.md#nvidia-gpu-pass-through-mode-with-kata-containers
) attempting to rebind the GPU to the VFIO-PCI driver, But it hangs on command 
```
echo -n "0000:8a:00.0" > /sys/bus/pci/devices/0000:8a:00.0/driver/unbind
``` 
run `dmesg -T -w` I get the log:
```
[Fri Sep 30 10:38:28 2022] NVRM: Attempting to remove device 0000:8a:00.0 with non-zero usage count!
```
so I think there is a process handle the device. run `ps -ef | grep nvidia`:
```
# ps -ef | grep nvidia
root      1123     2  0 10:05 ?        00:00:00 [nvidia-modeset/]
root      1124     2  0 10:05 ?        00:00:00 [nvidia-modeset/]
root     40008     2  0 10:52 ?        00:00:00 [irq/218-nvidia]
root     40009     2  0 10:52 ?        00:00:00 [nvidia]
root     40013     2  0 10:52 ?        00:00:00 [irq/219-nvidia]
root     40014     2  0 10:52 ?        00:00:00 [nvidia]
root     40016     2  0 10:52 ?        00:00:00 [irq/220-nvidia]
root     40017     2  0 10:52 ?        00:00:00 [nvidia]
root     40019     2  0 10:52 ?        00:00:00 [irq/221-nvidia]
root     40020     2  0 10:52 ?        00:00:00 [nvidia]
root     40022     2  0 10:52 ?        00:00:00 [irq/222-nvidia]
root     40023     2  0 10:52 ?        00:00:00 [nvidia]
root     40065     2  0 10:52 ?        00:00:00 [irq/223-nvidia]
root     40066     2  0 10:52 ?        00:00:00 [nvidia]
root     40118     2  0 10:52 ?        00:00:00 [irq/224-nvidia]
root     40119     2  0 10:52 ?        00:00:00 [nvidia]
root     40321 38145  0 10:52 pts/2    00:00:00 grep nvidia
```
then I stop the `kubelet` by command `systemctl stop kubeket`, above Nvidia processes are all closed, and unbind command execute success:
```
# dmesg -T
[Fri Sep 30 10:38:28 2022] NVRM: Attempting to remove device 0000:8a:00.0 with non-zero usage count!
[Fri Sep 30 10:50:52 2022] NVRM: Continuing with GPU removal for device 0000:8a:00.0
# ps -ef | grep nvidia
root      1123     2  0 10:05 ?        00:00:00 [nvidia-modeset/]
root      1124     2  0 10:05 ?        00:00:00 [nvidia-modeset/]
root     39579 38145  0 10:50 pts/2    00:00:00 grep nvidia
```

**What you expected to happen**:
unbinding the NVIDIA device success without stopping `kubelet`.
In addition, I have the following question:
1. what is the relationship between `kubevirt` and process `[irq/224-nvidia],[nvidia]`,
2. What exactly does process `[irq/224-nvidia] and [nvidia]` do?

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

1. run `lspci -nnD` get the Bus-Device-Function (BDF) for the GPU device on the host
2. unbinding the device from nvidia driver:
```
# echo $vendor_device > /sys/bus/pci/drivers/vfio-pci/new_id
# echo $NVIDIA_BDF > /sys/bus/pci/devices/$NVIDIA_BDF/driver/unbind          // hangs on unbinding
```
3. run `dmesg -T` get log:
```
[Fri Sep 30 10:38:28 2022] NVRM: Attempting to remove device 0000:8a:00.0 with non-zero usage count!
```
4. stop the `kubelet` by command `systemctl stop kubelet`, unbind action start work,
```
# systemctl stop kubelet
# dmesg -T
[Fri Sep 30 10:50:52 2022] NVRM: Continuing with GPU removal for device 0000:8a:00.0
# ps -ef | grep nvidia
root      1123     2  0 10:05 ?        00:00:00 [nvidia-modeset/]
root      1124     2  0 10:05 ?        00:00:00 [nvidia-modeset/]
root     39579 38145  0 10:50 pts/2    00:00:00 grep nvidia
```

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by soulseen** [comment]
related issue: https://github.com/kubernetes/kubernetes/issues/112795

**Comment by dhiller** [comment]
@soulseen from what I see you are [asking about Kata Containers, but this is KubeVirt.](https://github.com/kubevirt/kubevirt/blob/main/FAQ.md#whats-the-difference-between-kubevirt-and-kata-containers)

So I am not sure whether your document is even applicable here? Or are you saying that you are running Kata Containers inside a VM in KubeVirt?

I the latter case, we would need more information about the exact KubeVirt setup that you are using and also the vm.yaml to see how your VM is actually configured.
