### ISSUE TITLE
Is there a definition of VM YAML file?

### ISSUE THREAD

**Issue by alexxa** [kubevirt/kubevirt#855]
I see there are several examples of VM YAML files in ./cluster, but I can't find any definition of such YAML file, if there is any? 

I'm looking for smth like a [definition of a module.md file](https://github.com/fedora-modularity/libmodulemd/blob/master/spec.v2.yaml), with detailed explanation of every parameter, and I'd like this file to be placed next to VM YAML examples, for example as `vm_spec.yaml`. And in docs it can be like this [example](https://docs.fedoraproject.org/fedora-project/subprojects/fesco/en-US/making-modules/Storing_and_defining_sources.html#example), see every number is explained after the example. Or a page like for https://docs.docker.com/docker-cloud/apps/stack-yaml-reference/#image-required

**Comment by alexxa** [comment]
@fabiand yes, it's. Thanks. Is it referenced somewhere in this Git repo? I mean how users can find it?

**Comment by fabiand** [comment]
It is tricky to find, but there is an effort to rework the complete documentation - then it should be easier to find.

You can find it here:
https://github.com/kubevirt/ (api-reference)

**Comment by fabiand** [comment]
@scollier fyi the second last comment
