### ISSUE TITLE
How to retain ip of vm when it stop or restart?

### ISSUE THREAD

**Issue by joeevon** [kubevirt/kubevirt#8550]
**Is your feature request related to a problem? Please describe**:
A clear and concise description of what the problem is.
![image](https://user-images.githubusercontent.com/12859282/193225313-a1fbb462-a6f4-44e0-ac08-ea3ed91e38b9.png)

i have created a vm which ip is assigned 10.0.0.6

after i restarted the vm, it's ip has been occupied by other vm, it results in the orginal vm can not start up because ip is conflicted.

![image](https://user-images.githubusercontent.com/12859282/193225832-bc1c3e3b-398c-483a-9480-d2ea8e06fa9f.png)

**Describe the solution you'd like**:

how can i retain ip to the origin vm?

**Describe alternatives you've considered**:

**Additional context**:

**Comment by xpivarc** [comment]
/sig network
/reopen
/remove-lifecycle rotten

@EdDev this is repeating question(in all sort of flavors). Do we have some docs or general answers? (like this will most likely not work because of....)

**Comment by EdDev** [comment]
> @EdDev this is repeating question(in all sort of flavors). Do we have some docs or general answers? (like this will most likely not work because of....)

It is hard to generalize a note in the documentation about this.
IP reservation is up to the IP provider, which is in most cases is the network provider. When using a VM, an IP should be allocated from a reserved pool or a mechanism that can be controlled.
KubeVirt itself is not providing any such tooling for reserving network providers IP/s.

If we want to have VM/s reservations like this in a transparent manner, we will need to keep the pod (virt-launcher) as a placeholder (so the network provider will not release the IP for example). I guess it does not make sense and it will probably not work when there is a need to consider migrations.

**Comment by EdDev** [comment]
KubeVirt is not managing IP addresses, it relies on other components to do so.
As there are no plans to invest in this, I'm closing this request.

/close
