### ISSUE TITLE
Add `LiveMigrateIfPossible` eviction strategy

### ISSUE THREAD

**Issue by acardace** [kubevirt/kubevirt#8555]
**Describe the solution you'd like**:
Introduce a new eviction strategy called `LiveMigrateIfPossible` which would essentially behave like `LiveMigrate` but would not trigger any warning if the VMI is not live-migratable.

**Additional context**:
This idea was suggested by @rmohr while reviewing https://github.com/kubevirt/kubevirt/pull/7086 so that we can have a cluster-wide eviction strategy that will always try to live-migrate VMs on eviction but would not trigger any warning if a VM is not live-migratable.

**Comment by rmohr** [comment]
/assign

taking it for one of our engineers.
