### ISSUE TITLE
KubeVirt v1 GA Release

### ISSUE THREAD

**Issue by rthallisey** [kubevirt/kubevirt#8566]
This issue captures the requirements to release KubeVirt V1 as GA. 
When V1 GA is released it will be tagged as `v1.0.0`.

Post-v1 issues tracked in https://github.com/kubevirt/kubevirt/issues/10077

### Community
- [x] Reorganizing approver process - https://groups.google.com/g/kubevirt-dev/c/MeX_7QfMytc/m/qUx7AMhqAQAJ (@fabiand)
    - [x] ~https://github.com/kubevirt/kubevirt/pull/8858~
    - [x] https://github.com/kubevirt/kubevirt/pull/9453
- [x] V1 Contributor Guidelines (@rthallisey)
    - [x] https://github.com/kubevirt/kubevirt/pull/8588
- [x] API Graduation Guidelines - https://github.com/kubevirt/community/pull/160
- [x] V1 Scale and Performance metrics - https://github.com/kubevirt/kubevirt/pull/9989 (@alaypatel07)

### Features
- [x] Complete code refactors
- [x] Stabilize V1 interfaces and features - https://github.com/kubevirt/kubevirt/pull/3349

### Release Changes
- [x] Follow Kubernetes release cadence (4 months) - https://github.com/kubevirt/kubevirt/pull/8366
- [x] Release and support patterns - https://github.com/kubevirt/kubevirt/issues/6087
- [x] Release notes changes
    - [x] Documentation https://github.com/kubevirt/kubevirt/pull/8752 (@aburdenthehand)
- [x] SIG-release https://github.com/kubevirt/project-infra/pull/2666 (@dhiller)

**Comment by fabiand** [comment]
@rthallisey @aburdenthehand @davidvossel @vladikr @xpivarc please review https://github.com/kubevirt/kubevirt/pull/9982

**Comment by fabiand** [comment]
WRT https://github.com/kubevirt/community/pull/221 I wonder if we can do this async. To use
- api review process
- api backwards compatibility
- api deprecation policy (incl within stable apis)
- as founding topics for a to be founded sig-api

**Comment by fabiand** [comment]
@rthallisey can we remove some of the checkboxes from the description of this issue? I.e. the API discussions that need to take place.

**Comment by rthallisey** [comment]
@fabiand yes.  Created a Post v1 section.  I'll move those out into another issue after we close this.

**Comment by rthallisey** [comment]
Nice work everyone.  Today is v1 release day 🎉 !
