### ISSUE TITLE
network: passt requires unprivileged_port_start to be configured to 0 to ports 0-1023 to work

### ISSUE THREAD

**Issue by rhrazdil** [kubevirt/kubevirt#8569]
**What happened**:
Due to the following issues in Passt:
- https://bugs.passt.top/show_bug.cgi?id=15
- https://bugs.passt.top/show_bug.cgi?id=18

We need to configure the sysctl option `unprivileged_port_start` to 0, because only providing the `CAP_NET_BIND_SERVICE`
doesn't work.

This configuration is being introduced in PR https://github.com/kubevirt/kubevirt/pull/8516
And should be removed once the abovementioned issues in Passt are mitigated.

When the issue is fixed, we may remove the configuration setting the `unprivileged_port_start` to 0.

**Comment by maiqueb** [comment]
@rhrazdil should this issue be closed ?

**Comment by rhrazdil** [comment]
We can close this, thanks!
/close
