### ISSUE TITLE
DHCP server to use link local address?

### ISSUE THREAD

**Issue by mlsorensen** [kubevirt/kubevirt#857]
Currently the bridge IP used to serve DHCP to the VM is "10.11.12.13/24". Perhaps this isn't the final design, especially when one considers potential support for sidecars, but it might be better to assign a link local address to avoid potential conflicts with RFC1918 pod/service networks.  Replacing 10.11.12.13/24 with 169.254.100.10/32 seems to work, for example.

**Comment by fabiand** [comment]
I think this sounds like a really good idea.
After all I wondered his we can choose an IP to not hide certain public IPs.
A link local address did not come to my mind but is a very good suggestion.

+1

/cc @vladikr

**Comment by rmohr** [comment]
+1

**Comment by mlsorensen** [comment]
Sorry, didn't notice this got assigned.
