### ISSUE TITLE
virtctl not work by building it from source

### ISSUE THREAD

**Issue by gouyang** [kubevirt/kubevirt#858]
```
# go build -o virtctl .
# pwd
/root/go/src/kubevirt.io/kubevirt/cmd/virtctl
# ./virtctl console testvm --kubeconfig=/root/.kube/config  -n golden-images
Escape sequence is ^]
                     Can't connect to websocket (404): 404 page not found
```
```
# git log -n 1
commit 10b8cb03cd6f2cbd3bdab3735898e4d89251c216
Merge: 35390ff 39cafbc
Author: Stu Gott <stu-gott@users.noreply.github.com>
Date:   Thu Mar 29 17:31:43 2018 -0400

    Merge pull request #851 from vladikr/fix_bug_848
    
    dhcp: Stop adding default gateway to gateway-less routes
```

**Comment by fabiand** [comment]
Maybe related to the subresource merge?

**Comment by cynepco3hahue** [comment]
@gouyang Do you run multi-node environment? If yes, can you check where `virt-api` pod is running and check that you can ping node from master node by `tun` ip address?

**Comment by rmohr** [comment]
@gouyang your virtctl if newer than v0.3.0. Is your kubevirt cluster version equal or less than v0.3.0? If yes, then virtctl simply can't find the console subresource. Try to checkout the v0.3.0 tag and build virtcl from there then.

**Comment by gouyang** [comment]
it's not a multi-node environment, the `virt-api` pod is not running, the logs of the pod is
```
# oc logs -n kube-system virt-api-7c699c5555-mz8qf
unknown flag: --subresources-only
Usage of /virt-api:
      --alsologtostderr                  log to standard error as well as files
      --component string                 Default component for logs (default "virt-api")
      --kubeconfig string                absolute path to the kubeconfig file
      --listen string                    Address where to listen on (default "0.0.0.0")
      --log_backtrace_at traceLocation   when logging hits line file:N, emit a stack trace (default :0)
      --log_dir string                   If non-empty, write log files in this directory
      --logtostderr                      log to standard error instead of files
      --master string                    master url
      --port int                         Port to listen on (default 8183)
      --spice-proxy string               Spice proxy to use when spice access is requested
      --stderrthreshold severity         logs at or above this threshold go to stderr (default 2)
      --swagger-ui string                swagger-ui location (default "third_party/swagger-ui")
  -v, --v Level                          log level for V logs
      --vmodule moduleSpec               comma-separated list of pattern=N settings for file-filtered logging
unknown flag: --subresources-only
```

The kubevirt cluster is created via kubevirt-ansible, which is using the the kubevirt.yaml from master as well.

BTW, it works with virtctl-v0.4.0-alpha.2-linux-amd64, I forgot to mention it.

**Comment by gouyang** [comment]
checkout v0.3.0, and build virtctl from it works.

**Comment by rmohr** [comment]
@gouyang the hint that virt-api does not come up because of the missing flag explains the strange behaviour: You have `:latest` images from an older kubevirt version already on your nodes. The manifest tells kubernetes to not pull the images if they are already present. What you now see is a too old virt-api version which does not have the required flag. You can either change the PullPolicy in the manifest, or wipe out the old images from your nodes.

**Comment by gouyang** [comment]
@rmohr thanks, the pod is running after update `virt-api` image, and virtctl can connect to vm console successfully.
