### ISSUE TITLE
Add `kubevirt.io/ready` labels that would deprecate `kubevirt.io/schedulable` label

### ISSUE THREAD

**Issue by iholder101** [kubevirt/kubevirt#8583]
**What happened**:
The `kubevirt.io/schedulable` is misleading and confusing since it doesn't really indicate whether the node is schedulable, but rather incidates if virt-handler is completely ready (device plugins initialized and connected, and so forth).

**What you expected to happen**:
We shouldn't use a label that says "schedulable" that doesn't really indicate if the node's schedulable or not.

Instead, we can use a clearer label, such as `kubevirt.io/ready`.
Another possible approach is to find an elegant way to indicate whether virt-handler is fully ready.

**Additional context**:
For more info look the following PR: https://github.com/kubevirt/kubevirt/pull/8554
And especially the following comment: https://github.com/kubevirt/kubevirt/pull/8554#issuecomment-1272909490

**Comment by iholder101** [comment]
/reopen

New discussions about the issue in the following comments:
https://github.com/kubevirt/kubevirt/pull/9397#issuecomment-1476454885
https://github.com/kubevirt/kubevirt/pull/8554#issuecomment-1481289798

@prnaraya @stu-gott @rmohr 
Would you like to continue the discussion here?

**Comment by rmohr** [comment]
> New discussions about the issue in the following comments: [#9397 (comment)](https://github.com/kubevirt/kubevirt/pull/9397#issuecomment-1476454885) [#8554 (comment)](https://github.com/kubevirt/kubevirt/pull/8554#issuecomment-1481289798)
> 
> @prnaraya @stu-gott @rmohr Would you like to continue the discussion here?

I personally don't see an improvement with this name-change. Now someone could come in and say: Hey the `virtio-net` kernel module is not exposed. No VM can't be scheduled here. This node is NOT ready. Therefore I would vote for leaving it as is.
I see it mostly as an artificial problem. Especially given that this request does not seem to come from a significant amount of users which are confused by it. Just from some qe-testing attempts where some to me unclear correlations were tried to be made to test specific conditions? However if you find the support among some maintainers and you want to orchestrate the deprecation over the next 12 months, feel free to continue this.

**Comment by iholder101** [comment]
In https://github.com/kubevirt/kubevirt/pull/9397, a code review took place by some experienced Kubevirt developers. Not a single one of them thought that `schedulable` means "virt-handler pod is ready". If I weren't jumping in there, there's a good chance this PR would have been merged leading to inconsistencies regarding that label. To me, this is a proof that the naming is very confusing.

> Now someone could come in and say: Hey the virtio-net kernel module is not exposed. No VM can't be scheduled here. This node is NOT ready. Therefore I would vote for leaving it as is.

If in the situation you laid above no VM can be scheduled, I'd say that the following labels provide the most accurate and relevant information to the user:
```yaml
kubevirt.io/schedulable: "false"
kubevirt.io/virt-handler-ready: "true"
```

Simply having `schedulable: true` provides false information.

**Comment by rmohr** [comment]
> If in the situation you laid above no VM can be scheduled, I'd say that the following labels provide the most accurate and relevant information to the user:

Neither `ready` nor `schedulable` in an isolated fashion without explanation describe how far schedualbility or readiness goes.  I see  a similar amount of misunderstandability as well.

As said, if you get the support and feel like you need to change this, I have no interst in blocking this. I just want to point out that in all those years we had 1(?) narrow case where this was misunderstood. That does not sound to me that it is worth a change.
