### ISSUE TITLE
Fix build / install via `go install`

### ISSUE THREAD

**Issue by mbrancato** [kubevirt/kubevirt#8606]
**What happened**:
With go 1.18:

```
% go install github.com/kubevirt/kubevirt@v0.58.0
go: github.com/kubevirt/kubevirt@v0.58.0 (in github.com/kubevirt/kubevirt@v0.58.0):
	The go.mod file for the module providing named packages contains one or
	more replace directives. It must not contain directives that would cause
	it to be interpreted differently than if it were the main module.
```

**What you expected to happen**:
Build and install 

**How to reproduce it (as minimally and precisely as possible)**:
`go install github.com/kubevirt/kubevirt@v0.58.0`

**Additional context**:
The reason I'm trying to install this was is because there is no ARM64 version of `virtctl`.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.58.0
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): MacOS
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by usrbinkat** [comment]
Got the same error on macOS M1:
```
usrbinkat in 🌐 studio in ~ took 4s
❯ go install github.com/kubevirt/kubevirt@v0.58.0
go: github.com/kubevirt/kubevirt@v0.58.0 (in github.com/kubevirt/kubevirt@v0.58.0):
        The go.mod file for the module providing named packages contains one or
        more replace directives. It must not contain directives that would cause
        it to be interpreted differently than if it were the main module.

usrbinkat in 🌐 studio in ~
❯ go version
go version go1.19.2 darwin/arm64
```
