### ISSUE TITLE
Some problems about export feature

### ISSUE THREAD

**Issue by Longchuanzheng** [kubevirt/kubevirt#8618]
I am doing some tests on Export API. I have some problems and hope to get help.
I create a VirtualMachineExport for a pvc just like this example, and want to download data with it. 
```
apiVersion: export.kubevirt.io/v1alpha1
kind: VirtualMachineExport
metadata:
  name: example-export
spec:
  tokenSecretRef: example-token
  source:
    apiGroup: ""
    kind: PersistentVolumeClaim
    name: example-pvc
```
Problems as follows:
### q1. why my VirtualMachineExport only have Internal links, how to make it generate external links.
I create a VirtualMachineExport but it only have Internal links.
![image](https://user-images.githubusercontent.com/49519342/196355383-eac2623b-ad8f-4b12-838c-847e2feba910.png)

### q2.how to download.
2.1 I try to use `virtctl vmexport download` but it need external links  
![image](https://user-images.githubusercontent.com/49519342/196355930-335121c4-86c7-4692-9bf6-e597e978196a.png)

2.2 I want to download files form links without virtctl. Are there any recommended approachs.

**Comment by mhenriks** [comment]
Hi @Longchuanzheng yeah the documentation for export is a little too sparse right now.

The external links will be generated if there is an Ingress/Route resource referring to the `virt-exportproxy` service.

If you are using curl or similar to download the file, you should be able to simply copy the link, but make sure to specify `-H "x-kubevirt-export-token: <token value>"`.  

To avoid using `--insecure`, you can extract the appropriate cacert from  the export resource.

User guide for export may be helpful:  https://kubevirt.io/user-guide/operations/export_api/

**Comment by Longchuanzheng** [comment]
Hi @mhenriks , thank you for you advices. I would appreciate further details about it. I haven't read the code, so the problem may be basic.

I try to use curl to download the file.

```bash
curl -O -f --insecure -H "x-kubevirt-export-token: 1234567890ab" https://virt-export-example-export.default.svc/volumes/zal-upload-dv/disk.img
```
![image](https://user-images.githubusercontent.com/49519342/196841026-59e5d548-9325-49f1-892e-a7434f6b39b0.png)
but it seems we need to add something in /etc/hosts

![image](https://user-images.githubusercontent.com/49519342/196841075-197f7b57-31af-4068-bbf8-b28446a26bd3.png)


and now some error happen.

![image](https://user-images.githubusercontent.com/49519342/196841090-ee896565-e2f5-4cd3-ae0a-84b0e084fecc.png)



Firstly, if the host of the link can't be resolved, We need to edit the /etc/hosts every time when create a new export. 

Secondly, Can you give me some advices about how to download files with curl?

**Comment by mhenriks** [comment]
@Longchuanzheng you have to change the host part of the link when using `port-forward`.  For example:


Set up port forward

```
k  port-forward svc/virt-export-export-test 18443:443
```

To curl the `internal` link `https://virt-export-export-test.default.svc/volumes/volume1/disk.img.gz`

```
curl  --insecure https://localhost:18443/volumes/volume1/disk.img.gz -H "x-kubevirt-export-token: 5kvJ2j4KPl" > disk.img.gz
```

or (with query param)

```
curl  --insecure https://localhost:18443/volumes/volume1/disk.img.gz\?x-kubevirt-export-token\=5kvJ2j4KPl > disk.img.gz
```

**Comment by Longchuanzheng** [comment]
Hi @mhenriks, I set port-forward (I think edit svc to Nodeport type have the same effect) 

![image](https://user-images.githubusercontent.com/49519342/197741266-3df523cb-7279-4369-95ef-176750b3f844.png)

and download (> disk.img and -O have same effect)

![image](https://user-images.githubusercontent.com/49519342/197741282-890c88f6-c896-41b9-b950-abd4c0b57723.png)

The download seems complete but my raw image(about 20MB) is larger than the disk.img what is downloaded. So I want to confirm the export pod mount the target pvc correctly.

Firstly, I get the pod's uid 
![image](https://user-images.githubusercontent.com/49519342/197741377-22c57e49-c5fe-4710-a14d-06ce5dddd94d.png)

uid is bb40....

Then, I convert the disk to a qcow2 img and I think the pvc mount correctly. Therefore, I hold the point that some problems happen when we are downloading img.

![image](https://user-images.githubusercontent.com/49519342/197741420-3cb9c4f5-5f34-467f-8e40-7da48e1df3e7.png)

So I think I need more support.

**Comment by mhenriks** [comment]
@awels

**Comment by awels** [comment]
I think the problem is likely that you are not passing in the right token and you are getting the unauthorized page instead, your pictures are showing 283 bytes, which is about that size of that page. Can you do a verbose logging in curl by using -v and not writing the output anywhere.

**Comment by Longchuanzheng** [comment]
Hi @awels, we meet again.

I think i just follow the User guide to create a VMexport. 

token.yaml

```yaml
apiVersion: v1
kind: Secret
metadata:
  name: example-token
stringData:
  token: 1234567890ab
```

pvcexport.yaml

```yaml
apiVersion: export.kubevirt.io/v1alpha1
kind: VirtualMachineExport
metadata:
  name: example-export
spec:
  tokenSecretRef: example-token
  source:
    apiGroup: ""
    kind: PersistentVolumeClaim
    name: zal-upload-dv
```

![image](https://user-images.githubusercontent.com/49519342/199202494-023115ce-60e5-4fe2-9f83-64a1edb37973.png)


I think it create successfully.

```bash
[root@localhost export]# kubectl get vmexport example-export -o yaml
apiVersion: export.kubevirt.io/v1alpha1
kind: VirtualMachineExport
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"export.kubevirt.io/v1alpha1","kind":"VirtualMachineExport","metadata":{"annotations":{},"name":"example-export","namespace":"default"},"spec":{"source":{"apiGroup":"","kind":"PersistentVolumeClaim","name":"zal-upload-dv"},"tokenSecretRef":"example-token"}}
  creationTimestamp: "2022-11-01T08:46:17Z"
  generation: 3
  name: example-export
  namespace: default
  resourceVersion: "2443618"
  uid: d683d9e6-63e5-4129-ba1b-b765961f77e8
spec:
  source:
    apiGroup: ""
    kind: PersistentVolumeClaim
    name: zal-upload-dv
  tokenSecretRef: example-token
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2022-11-01T08:46:27Z"
    reason: PodReady
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2022-11-01T08:46:17Z"
    reason: PVCBound
    status: "True"
    type: PVCReady
  links:
    internal:
      cert: |-
        -----BEGIN CERTIFICATE-----
...
        -----END CERTIFICATE-----
      volumes:
      - formats:
        - format: raw
          url: https://virt-export-example-export.default.svc/volumes/zal-upload-dv/disk.img
        - format: gzip
          url: https://virt-export-example-export.default.svc/volumes/zal-upload-dv/disk.img.gz
        name: zal-upload-dv
  phase: Ready
  serviceName: virt-export-example-export
  tokenSecretRef: example-token

```

expose port 

![image](https://user-images.githubusercontent.com/49519342/199202636-85555d11-bba6-4c64-b15b-ef7fe4489267.png)

and download

```bash
[root@localhost export]# curl -v --insecure https://localhost:18443/volumes/zal-upload-dv/disk.img -H "x-kubevirt-export-token: 1234567890ab"
* About to connect() to localhost port 18443 (#0)
*   Trying ::1...
* Connected to localhost (::1) port 18443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
* skipping SSL peer certificate verification
* SSL connection using TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256
* Server certificate:
*       subject: CN=virt-export-example-export.default.pod.cluster.local
*       start date: Oct 25 21:39:38 2022 GMT
*       expire date: Nov 02 08:46:17 2022 GMT
*       common name: virt-export-example-export.default.pod.cluster.local
*       issuer: CN=export.kubevirt.io@1666733978
> GET /volumes/zal-upload-dv/disk.img HTTP/1.1
> User-Agent: curl/7.29.0
> Host: localhost:18443
> Accept: */*
> x-kubevirt-export-token: 1234567890ab
>
< HTTP/1.1 500 Internal Server Error
< Date: Tue, 01 Nov 2022 09:10:04 GMT
< Content-Length: 0
<
* Connection #0 to host localhost left intact
[root@localhost export]#
```

It seems I download a page earlier, but the response code is 500, meanwhile I can't find any logs in export-pod.

**Comment by Longchuanzheng** [comment]
In my opinion, this phenomenon due to the device's user and group can not be configured by fsgroup or other field in pod securitycontext. We can modify the configuration of CRI to set it by securityContext.
reference: 
https://github.com/kubevirt/kubevirt/pull/8804
https://github.com/kubevirt/containerized-data-importer/blob/main/doc/block_cri_ownership_config.md
https://kubernetes.io/blog/2021/11/09/non-root-containers-and-devices/

**Comment by papandadj** [comment]
> In my opinion, this phenomenon due to the device's user and group can not be configured by fsgroup or other field in pod securitycontext. We can modify the configuration of CRI to set it by securityContext. reference: #8804 https://github.com/kubevirt/containerized-data-importer/blob/main/doc/block_cri_ownership_config.md https://kubernetes.io/blog/2021/11/09/non-root-containers-and-devices/

Have you solved this problem?

**Comment by awels** [comment]
If you are using containerd then setting the information from the links should fix it.

**Comment by papandadj** [comment]
I use rke2 and docker runtime to install k8s. When I fix containerd config and restart containerd, not work for me. I will test weather it works correctly using containerd directly.

**Comment by Longchuanzheng** [comment]
> > In my opinion, this phenomenon due to the device's user and group can not be configured by fsgroup or other field in pod securitycontext. We can modify the configuration of CRI to set it by securityContext. reference: #8804 https://github.com/kubevirt/containerized-data-importer/blob/main/doc/block_cri_ownership_config.md https://kubernetes.io/blog/2021/11/09/non-root-containers-and-devices/
> 
> Have you solved this problem?
I haven't done a test but I think the method should work.
I would apppreciate if you share your outcome.

**Comment by papandadj** [comment]
> > > In my opinion, this phenomenon due to the device's user and group can not be configured by fsgroup or other field in pod securitycontext. We can modify the configuration of CRI to set it by securityContext. reference: #8804 https://github.com/kubevirt/containerized-data-importer/blob/main/doc/block_cri_ownership_config.md https://kubernetes.io/blog/2021/11/09/non-root-containers-and-devices/
> > 
> > 
> > Have you solved this problem?
> > I haven't done a test but I think the method should work.
> > I would apppreciate if you share your outcome.
After use k3s and contaienrd,I can download .img file

**Comment by liyang516** [comment]
> referring

@mhenriks how to create virt-exportproxy ingress? create it manually？Or it could be create through kubevirt-operator？

**Comment by liyang516** [comment]
> @Longchuanzheng you have to change the host part of the link when using `port-forward`. For example:
> 
> Set up port forward
> 
> ```
> k  port-forward svc/virt-export-export-test 18443:443
> ```
> 
> To curl the `internal` link `https://virt-export-export-test.default.svc/volumes/volume1/disk.img.gz`
> 
> ```
> curl  --insecure https://localhost:18443/volumes/volume1/disk.img.gz -H "x-kubevirt-export-token: 5kvJ2j4KPl" > disk.img.gz
> ```
> 
> or (with query param)
> 
> ```
> curl  --insecure https://localhost:18443/volumes/volume1/disk.img.gz\?x-kubevirt-export-token\=5kvJ2j4KPl > disk.img.gz
> ```

@mhenriks how to create virt-exportproxy ingress? create it manually？Or it could be create through kubevirt-operator？

**Comment by liyang516** [comment]
> Hi @Longchuanzheng yeah the documentation for export is a little too sparse right now.
> 
> The external links will be generated if there is an Ingress/Route resource referring to the `virt-exportproxy` service.
> 
> If you are using curl or similar to download the file, you should be able to simply copy the link, but make sure to specify `-H "x-kubevirt-export-token: <token value>"`.
> 
> To avoid using `--insecure`, you can extract the appropriate cacert from the export resource.
> 
> User guide for export may be helpful: https://kubevirt.io/user-guide/operations/export_api/

@mhenriks how to create virt-exportproxy ingress? create it manually？Or it could be create through kubevirt-operator？

**Comment by awels** [comment]
> > Hi @Longchuanzheng yeah the documentation for export is a little too sparse right now.
> > The external links will be generated if there is an Ingress/Route resource referring to the `virt-exportproxy` service.
> > If you are using curl or similar to download the file, you should be able to simply copy the link, but make sure to specify `-H "x-kubevirt-export-token: <token value>"`.
> > To avoid using `--insecure`, you can extract the appropriate cacert from the export resource.
> > User guide for export may be helpful: https://kubevirt.io/user-guide/operations/export_api/
> 
> @mhenriks how to create virt-exportproxy ingress? create it manually？Or it could be create through kubevirt-operator？

Creating an ingress is outside of the scope of the operator, the admin will have to do that manually. There are various examples on the internet on how to setup an ingress. I believe the nginx ingress controller example is pretty decent.

**Comment by d4rkfella** [comment]
Hey, i was just battling with the VMExport and why its not generating the external urls . I've created both an http route and the backend tls policy for validating the certifactes like this . 
```
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: virt-exportproxy-route
spec:
  hostnames: ["virt-exportproxy.example.com"]
  parentRefs:
    - name: internal
      namespace: envoy-gateway-system
      sectionName: https
  rules:
    - backendRefs:
        - name: virt-exportproxy
          port: 443
---
apiVersion: gateway.networking.k8s.io/v1
kind: BackendTLSPolicy
metadata:
  name: virt-exportproxy-backend-tls
spec:
  targetRefs:
    - group: ""
      kind: Service
      name: virt-exportproxy
  validation:
    hostname: virt-exportproxy.kubevirt.svc.cluster.local
    caCertificateRefs:
      - kind: ConfigMap
        name: kubevirt-ca
        group: ""
```
I was wondering, are HTTPRoutes supported ? If not is there a way to manually configure the VMExport resource so that it includes the external urls ?

**Comment by mhenriks** [comment]
@d4rkfella gateway API is not supported yet, please file an issue (or submit a PR to add the functionality if you are so inclined). Unfortunately, I don't think there is a way to manually configure the URLs

**Comment by d4rkfella** [comment]
> [@d4rkfella](https://github.com/d4rkfella) gateway API is not supported yet, please file an issue (or submit a PR to add the functionality if you are so inclined). Unfortunately, I don't think there is a way to manually configure the URLs

Thanks for the response. I'm not familiar with the kubevirt codebase, but i might give it a shot these days. For now i solved the issue by creating a dummy Ingress resource.
