### ISSUE TITLE
virtctl start/stop should PATCH the offline virtual machine instead of updating it with PUT

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#863]
In order to allow adding backward compatible fields to the api, we need to patch offline virtual machine instead of updating it. Otherwise updateable field values may disappear when using a cimpatible but older virtctl command + like mentioned by @davidvossel virtctl will not have to compete with controllers which may modify the ovm in parallel.

**Comment by davidvossel** [comment]
this would also fix the scenario where virtctl can fail to update because a controller updated the object between virtctl's get and put operations... This actually happened in our functional test suite last week.

**Comment by rmohr** [comment]
@petrkotas @stu-gott FYI

**Comment by slintes** [comment]
fixed by https://github.com/kubevirt/kubevirt/pull/1026
