### ISSUE TITLE
Can't add OpenApi for kubevirt

### ISSUE THREAD

**Issue by matthewei** [kubevirt/kubevirt#8630]
**What happened**:
when i add a type for kubevirt and i execut the command "make generage". i will return the following errors

> + /root/go/src/kubevirt.io/kubevirt/tools/openapispec/openapispec --dump-api-spec-path /root/go/src/kubevirt.io/kubevirt/api/openapi-spec/swagger.json
> panic: Failed to build swagger: cannot find model definition for kubevirt.io/api/core/v1.ResetPasswordOptions. If you added a new type, you may need to add +k8s:openapi-gen=true to the package or type and run code-gen again

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

> Step1 add one type for kubevirt (kubevirt.io/api/core/v1/types)
> Step2 execute "make generage" 
i will return some errors
> + /root/go/src/kubevirt.io/kubevirt/tools/openapispec/openapispec --dump-api-spec-path /root/go/src/kubevirt.io/kubevirt/api/openapi-spec/swagger.json
> panic: Failed to build swagger: cannot find model definition for kubevirt.io/api/core/v1.ResetPasswordOptions. If you added a new type, you may need to add +k8s:openapi-gen=true to the package or type and run code-gen again

**Environment**:
- KubeVirt version (use `virtctl version`): v0.58
- Kubernetes version (use `kubectl version`): v.23

**Comment by larrydewey** [comment]
This sounds like you have an annotation missing on the object which was added here. Some additional reproduction of this issue is definitely needed, but can you verify this annotation has been added?
