### ISSUE TITLE
k8s-1.25 - macvtap e2e tests failing

### ISSUE THREAD

**Issue by maiqueb** [kubevirt/kubevirt#8642]
**What happened**:
Macvtap tests fail on the k8s-1.25 network lane

**What you expected to happen**:
The tests should pass.

**How to reproduce it (as minimally and precisely as possible)**:
- start a kubevirt cluster w/ multus & macvtap deployed via CNAO
- run the macvtap e2e test suite.

**Additional context**:
This happens due to a bug in the device plugin registration order. 

**Environment**:
- Kubernetes version (use `kubectl version`): 1.25

**Comment by maiqueb** [comment]
Relevant PRs:
- [device-plugin-manager](https://github.com/kubevirt/device-plugin-manager/pull/21)
- [macvtap-cni](https://github.com/kubevirt/macvtap-cni/pull/82)
- CNAO - TBD

**Comment by maiqueb** [comment]
@brianmcarey I've seen the 1.25 lane pass in [this execution](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.25-sig-network/1583735069015543808); can we close this issue then ?

**Comment by maiqueb** [comment]
We can always re-open if this is still an issue.

**Comment by brianmcarey** [comment]
> @brianmcarey I've seen the 1.25 lane pass in [this execution](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.25-sig-network/1583735069015543808); can we close this issue then ?
> 
> **EDIT**: filter by lane type: https://prow.ci.kubevirt.io/?job=periodic-kubevirt-e2e-k8s-1.25-sig-network ; All of the executions passed successfully.

Yes it looks good now - thanks for taking care of that!
