### ISSUE TITLE
How to adjust resolution under vnc ? 

### ISSUE THREAD

**Issue by chenxinlong** [kubevirt/kubevirt#8643]
Since kubevirt hard code a `vga` video device with low vram(16MB) , so there's no way to to adjust resolution in windows vnc.

So I've tried 2 ways to fix this problem : 

### 1. raise vram 

raise `vram` from 16384 to 65536
```go
...
else {
    vram = 65536
    domain.Spec.Devices.Video = []api.Video{
        {
            Model: api.VideoModel{
                Type:  "vga",
                Heads: &heads,
                VRam:  &vram,
            },
        },
    }
}
```

After rebuild virt-launcher image, I ran a windows vm with newest virt-launcher image. According to the `virsh dumpxml <domain>` outputs I did change the vram to 65536.  But still, I can't change the resolution(800*600, and the resolution option is disabled)

### 2.  use qxl 

Try to use `qxl` but `vga` 
```go
vram = 65536
var vgamem uint = 16384
var ram uint = 65536
domain.Spec.Devices.Video = []api.Video{
    {
        Model: api.VideoModel{
            Type:   "qxl",
            Heads:  &heads,
            Ram:    &ram,
            VRam:   &vram,
            VGAMem: &vgamem,
        },
    },
}
```

This time, I can't even start this windows vm. Described info like below : 
```
Events:
  Type     Reason            Age                 From                       Message
  ----     ------            ----                ----                       -------
  Normal   SuccessfulCreate  2m5s                virtualmachine-controller  Created virtual machine pod virt-launcher-vm-ma7dfks6-8xvch
  Warning  SyncFailed        35s (x14 over 77s)  virt-handler               server error. command SyncVMI failed: "LibvirtError(Code=67, Domain=10, Message='unsupported configuration: domain configuration does not support video model 'qxl'')"
```

Is there any way to solve this problem ?

**Comment by larrydewey** [comment]
I am not sure if it is possible to adjust the resolution at this level. I will look into this further and see if it is possible, but my initial understanding is that it isn't possible.

**Comment by larrydewey** [comment]
@chenxinlong Unfortunately, that is what I am seeing, as well. I haven't found any way to do that via configuration.

**Comment by chenxinlong** [comment]
@larrydewey 

According to the [libvirt - video devices](https://libvirt.org/formatdomain.html#video-devices) : 
> Since 5.9.0 , the model element may also have an optional resolution sub-element. The resolution element has attributes x and y to set the minimum resolution for the video device. This sub-element is valid for model types "vga", "qxl", "bochs", "gop", and "virtio".

I've tried to add a `resolution` sub-element to vga video device model, and set x to 1920, y to 1080. Dumped domain xml as follow : 
```xml
<video>
    <model type='vga' vram='65536' heads='1' primary='yes'>
    <resolution x='1920' y='1080'/>
    </model>
    <alias name='video0'/>
    <address type='pci' domain='0x0000' bus='0x00' slot='0x01' function='0x0'/>
</video>
```

It does works on my ubuntu guest, but it doesn't works on my centos and windows guest.
