### ISSUE TITLE
How can I create a full clone？

### ISSUE THREAD

**Issue by use-epoll** [kubevirt/kubevirt#8659]
There are times when I don't want to create a link clone for a mirror,How can I create a full clone

**Comment by use-epoll** [comment]
Yes, I want to clone a VM and be a full image. Because there is a possibility that I will have to delete some snapshots from the snapshot chain.

**Comment by alicefr** [comment]
@use-epoll we rely on CSI for cloning and taking snapshots. You could use CDI for creating a clone of your image. Does these 2 docs [csi-cloning](https://github.com/kubevirt/containerized-data-importer/blob/main/doc/csi-cloning.md) and [efficient-cloning](https://github.com/kubevirt/containerized-data-importer/blob/main/doc/efficient-cloning.md) answer your question?

**Comment by use-epoll** [comment]
Sorry, maybe I didn't describe the problem clearly, I was trying to use smart-clone by default when I occasionally want to use host-assisted cloning. @alicefr
