### ISSUE TITLE
Get rid of SELinux denials when registry disks are used

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#866]
Currently - as described in #639 - the use of registry disks will cause SELinux denials.

We should understand why the denials are raised and should see if we can get rid of them.

**Comment by karmab** [comment]
nope, registry disks are the ones not getting selinux denials.
denials only occur when using pvc disks, although the relevant avc denials are not visible on the host.

**Comment by fabiand** [comment]
Thanks
