### ISSUE TITLE
Can vmi auto migrate to another node when node is not ready

### ISSUE THREAD

**Issue by chenxinlong** [kubevirt/kubevirt#8714]
Can vmi auto migrate to an healthy node when node is not ready ? 

As you can see, the node2 is on `NotReady` status, but vmis on node2 do not auto migrate to a healthy node(the feature gate `LiveMigration` is added).  
```
root@node1:~# kubectl get node -o wide
NAME    STATUS     ROLES                         AGE   VERSION   INTERNAL-IP     EXTERNAL-IP   OS-IMAGE             KERNEL-VERSION      CONTAINER-RUNTIME
node1   Ready      control-plane,master,worker   76d   v1.23.7   172.16.33.101   <none>        Ubuntu 20.04.4 LTS   5.4.0-125-generic   docker://20.10.8
node2   NotReady   worker                        63d   v1.23.7   172.16.33.102   <none>        Ubuntu 20.04.4 LTS   5.4.0-125-generic   docker://Unknown
```
```
root@node1:~# kubectl get vmi -n dev-test -o wide
NAMESPACE   NAME          AGE    PHASE     IP                NODENAME   READY   LIVE-MIGRATABLE   PAUSED
dev-test    vm-wd4kwrdq   15d    Failed    192.168.0.1       node2      False   False
root@node1:~# kubectl describe vmi vm-wd4kwrdq -n dev-test | grep -i -5 event
      Filesystem Overhead:  0
      Requests:
        Storage:    40Gi
      Volume Mode:  Block
    Target:         vdb
Events:
  Type    Reason            Age   From                       Message
  ----    ------            ----  ----                       -------
  Normal  NodeUnresponsive  27m   node-controller            virt-handler on node node2 is not responsive, marking VMI as failed
  Normal  SuccessfulDelete  27m   virtualmachine-controller  Deleted virtual machine pod virt-launcher-vm-wd4kwrdq-666jv
```

**Comment by usrbinkat** [comment]
It sounds that this request recommends introducing an automated "node drain" function triggered by a "notReady" status event?

If I am understanding that correctly it sounds likely to be better implemented by generic Kubevirt mechanism rather than a Kubevirt specific implemented feature.

**Comment by xpivarc** [comment]
> It sounds that this request recommends introducing an automated "node drain" function triggered by a "notReady" status event?
> 
> If I am understanding that correctly it sounds likely to be better implemented by generic Kubevirt mechanism rather than a Kubevirt specific implemented feature.

* generic Kubernetes mechanism

There are a few problems. Are we even able to live migrate if the node is not healthy? Probably not. The second question is how can Kubevirt be sure that the VMs are safely shutdown and that we will not run them on 2 nodes? There needs to be a manual or automatic process that will tell us this.
