### ISSUE TITLE
Only copy mode can be used when creating instances

### ISSUE THREAD

**Issue by use-epoll** [kubevirt/kubevirt#8715]
kubernetes version: v1.23.7
kubevirt: version v0.54.0
ceph version: quincy v17.2.5  a standalone ceph cluster deployed using cephadm
ceph-csi version: v3.7.2
When I create an instance the system image created will only use copy mode, it is a host-assisted clone and cannot use smart-clone
I have tried the following settings:
cdi.kubevirt.io/clone-strategy: snapshot  in  default SC
cloneStrategyOverride: snapshot    in cdi 
But none of them work.
I use the default storage class to create a system disk, and use that system disk to create a snapshot, and then use the snapshot to create a system disk that is available.  (Configuring on this k8s cluster)

Target: I want to use smart-clone mode

**Comment by akalenyu** [comment]
There are certain situations where we can't do smart clone and thus opt for host-assisted copy.
For example, if it's a cross-namespace clone with volume binding that is WFFC is one of them.
Would it be possible to look at your storage classes/data volume/PVC manifests?

**Comment by use-epoll** [comment]
storageClass
```
allowVolumeExpansion: true
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    cdi.kubevirt.io/clone-strategy: snapshot
    kubectl.kubernetes.io/last-applied-configuration: |
      {"allowVolumeExpansion":true,"apiVersion":"storage.k8s.io/v1","kind":"StorageClass","metadata":{"annotations":{"storageclass.beta.kubernetes.io/is-default-class":"true","storageclass.kubesphere.io/supported-access-modes":"[\"ReadWriteOnce\",\"ReadOnlyMany\",\"ReadWriteMany\"]"},"name":"csi-rbd-sc"},"mountOptions":["discard"],"parameters":{"clusterID":"ceph-cluster","csi.storage.k8s.io/controller-expand-secret-name":"csi-rbd-secret","csi.storage.k8s.io/controller-expand-secret-namespace":"kube-system","csi.storage.k8s.io/fstype":"ext4","csi.storage.k8s.io/node-stage-secret-name":"csi-rbd-secret","csi.storage.k8s.io/node-stage-secret-namespace":"kube-system","csi.storage.k8s.io/provisioner-secret-name":"csi-rbd-secret","csi.storage.k8s.io/provisioner-secret-namespace":"kube-system","imageFeatures":"layering","imageFormat":"2","mounter":"rbd-nbd","pool":"wangzypool"},"provisioner":"rbd.csi.ceph.com","reclaimPolicy":"Delete"}
    storageclass.beta.kubernetes.io/is-default-class: "true"
    storageclass.kubesphere.io/allow-clone: "true"
    storageclass.kubesphere.io/allow-snapshot: "true"
    storageclass.kubesphere.io/supported-access-modes: '["ReadWriteOnce","ReadOnlyMany","ReadWriteMany"]'
  creationTimestamp: "2022-11-01T07:46:34Z"
  name: csi-rbd-sc
  resourceVersion: "1314538"
  uid: 9a8112e9-efd7-4518-9e60-55a45fae44c3
parameters:
  clusterID: ceph-cluster
  csi.storage.k8s.io/controller-expand-secret-name: csi-rbd-secret
  csi.storage.k8s.io/controller-expand-secret-namespace: kube-system
  csi.storage.k8s.io/fstype: ext4
  csi.storage.k8s.io/node-stage-secret-name: csi-rbd-secret
  csi.storage.k8s.io/node-stage-secret-namespace: kube-system
  csi.storage.k8s.io/provisioner-secret-name: csi-rbd-secret
  csi.storage.k8s.io/provisioner-secret-namespace: kube-system
  imageFeatures: layering
  imageFormat: "2"
  mounter: rbd-nbd
  pool: rbdpool
provisioner: rbd.csi.ceph.com
reclaimPolicy: Delete
volumeBindingMode: Immediate

```

**Comment by use-epoll** [comment]
pvc of  OS  image   Ubuntu 20.04  format raw 
```
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    cdi.kubevirt.io/storage.condition.running: "false"
    cdi.kubevirt.io/storage.condition.running.message: Import Complete, Preallocation
      applied
    cdi.kubevirt.io/storage.condition.running.reason: Completed
    cdi.kubevirt.io/storage.contentType: kubevirt
    cdi.kubevirt.io/storage.import.endpoint: http://minio.kubesphere-system.svc:9000/kcp-img/ubuntu_focal_2004_agent0.2.3_deamon0.0.1_v3_64.raw?etag=7e815c8f98ef266ed453992065d1f081-293
    cdi.kubevirt.io/storage.import.importPodName: importer-img-5jrnf8rb
    cdi.kubevirt.io/storage.import.source: http
    cdi.kubevirt.io/storage.pod.phase: Succeeded
    cdi.kubevirt.io/storage.pod.restarts: "0"
    cdi.kubevirt.io/storage.preallocation: "true"
    cdi.kubevirt.io/storage.preallocation.requested: "false"
    kubesphere.io/creator: admin
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    virtualization.gpuhpc.com/disktype: img
    volume.beta.kubernetes.io/storage-provisioner: rbd.csi.ceph.com
    volume.kubernetes.io/storage-provisioner: rbd.csi.ceph.com
  creationTimestamp: "2022-11-02T02:50:00Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
  name: img-5jrnf8rb
  namespace: test
  ownerReferences:
  - apiVersion: cdi.kubevirt.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: DataVolume
    name: img-5jrnf8rb
    uid: 1a02d85b-a4c7-4ea9-8b2d-7ffd6f657ff1
  resourceVersion: "536629"
  uid: 164842ce-a572-4863-8624-4507bcb73746
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 6Gi
  storageClassName: csi-rbd-sc
  volumeMode: Block
  volumeName: pvc-164842ce-a572-4863-8624-4507bcb73746
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 6Gi

```

**Comment by use-epoll** [comment]
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  annotations:
    cdi.kubevirt.io/storage.clone.token: eyJhbGciOiJQUzI1NiJ9.eyJleHAiOjE2Njc0NjQyODksImlhdCI6MTY2NzQ2Mzk4OSwiaXNzIjoiY2RpLWFwaXNlcnZlciIsIm5hbWUiOiJpbWctNWpybmY4cmIiLCJuYW1lc3BhY2UiOiJ0ZXN0IiwibmJmIjoxNjY3NDYzOTg5LCJvcGVydGF0aW9uIjoiQ2xvbmUiLCJwYXJhbXMiOnsidGFyZ2V0TmFtZSI6ImRpc2steTRnaTN3aTAiLCJ0YXJnZXROYW1lc3BhY2UiOiJ0ZXN0In0sInJlc291cmNlIjp7Imdyb3VwIjoiIiwicmVzb3VyY2UiOiJwZXJzaXN0ZW50dm9sdW1lY2xhaW1zIiwidmVyc2lvbiI6InYxIn19.wdyUinPF7sV10b9OUGPhhmoMAa-3RpeAkHaoZn139sQNgVAjUC7n7LoWZdqDateL5fygVB2uy0lUtBUnlGlDihRSHOAvZdPnNmK_g6mdWqchf3CN9bN4sFUgZGI03TuHWstJoKeNqf3-FzWz5sVBXnQzAa32lkQR6fiKIwwHmkUunO01JQaqihwC3_uFt7Cpf2apODGkSeKuAFJDMsQxFEQEE0CeBa3Z3weNDxxaf0WTRZY0Bv_QvhzrXL09oH4BRo6-XJv28RuG5xBIqRwM7dQ7XLcZw2vL_OGL9bbxrj4KHZ4ikDJy6U8EQkRF2eeAoXU5EiGxG7LCJyw2p0XIcQ
    cdi.kubevirt.io/storage.condition.running: "false"
    cdi.kubevirt.io/storage.condition.running.message: Clone Complete
    cdi.kubevirt.io/storage.condition.running.reason: Completed
    cdi.kubevirt.io/storage.condition.source.running: "true"
    cdi.kubevirt.io/storage.condition.source.running.message: Clone Complete
    cdi.kubevirt.io/storage.condition.source.running.reason: Completed
    cdi.kubevirt.io/storage.extended.clone.token: eyJhbGciOiJQUzI1NiJ9.eyJleHAiOjE5ODI4MjM5OTIsImlhdCI6MTY2NzQ2Mzk5MiwiaXNzIjoiY2RpLWRlcGxveW1lbnQiLCJuYW1lIjoiaW1nLTVqcm5mOHJiIiwibmFtZXNwYWNlIjoidGVzdCIsIm5iZiI6MTY2NzQ2Mzk5Miwib3BlcnRhdGlvbiI6IkNsb25lIiwicGFyYW1zIjp7InRhcmdldE5hbWUiOiJkaXNrLXk0Z2kzd2kwIiwidGFyZ2V0TmFtZXNwYWNlIjoidGVzdCIsInVpZCI6IjE4NDY1OWRiLTI0ODMtNGYyOC05ZmZhLWY5NDczNzEwNWY0MSJ9LCJyZXNvdXJjZSI6eyJncm91cCI6IiIsInJlc291cmNlIjoicGVyc2lzdGVudHZvbHVtZWNsYWltcyIsInZlcnNpb24iOiJ2MSJ9fQ.WN2pBGy6fO3Vv8VR1apImVUXE1WOXkDZNkrGSj4kIsVoE1jfckxsuJJrsiPvE1uoJ3dZnu-aQtOmhP1EwlYL8db9y8m_H5_eOjAQc6IgLycFiNMB6CrqZp2KV4PB2uo7OtwRveJxRb5NRnyzw7z7TP_UwZhaqzqhDcuHB-bMi8cszwGB3dSSlNy5Pb9Q0hLpFMC1ov5bd5rlrzCH2JKMBkU96oqLC0JWXSrZhH-irlWgeVbstiuANhJGIwy9NlXpOANaWD8rK4-kzkVQpjHPNbXUIwukrE6Ak73Nmuwxg-Xzf3UxGaD3dI3jRsS67ruAVFpSHH6AKSQQpYEYqCx5dQ
    cdi.kubevirt.io/storage.pod.phase: Succeeded
    cdi.kubevirt.io/storage.pod.ready: "false"
    cdi.kubevirt.io/storage.pod.restarts: "0"
    cdi.kubevirt.io/storage.preallocation.requested: "false"
    cdi.kubevirt.io/storage.sourceClonePodName: 184659db-2483-4f28-9ffa-f94737105f41-source-pod
    cdi.kubevirt.io/storage.uploadPodName: cdi-upload-disk-y4gi3wi0
    cdi.kubevirt.io/uploadClientName: test/img-5jrnf8rb-test/disk-y4gi3wi0
    k8s.io/CloneOf: "true"
    k8s.io/CloneRequest: test/img-5jrnf8rb
    pv.kubernetes.io/bind-completed: "yes"
    pv.kubernetes.io/bound-by-controller: "yes"
    virtualization.study.com/disktype: system
    virtualization.study.com/ostype: linux
    volume.beta.kubernetes.io/storage-provisioner: rbd.csi.ceph.com
    volume.kubernetes.io/storage-provisioner: rbd.csi.ceph.com
  creationTimestamp: "2022-11-03T08:26:29Z"
  finalizers:
  - kubernetes.io/pvc-protection
  labels:
    app: containerized-data-importer
    app.kubernetes.io/component: storage
    app.kubernetes.io/managed-by: cdi-controller
  name: disk-y4gi3wi0
  namespace: test
  ownerReferences:
  - apiVersion: cdi.kubevirt.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: DataVolume
    name: disk-y4gi3wi0
    uid: b9daaa1f-100b-41ca-9f15-b13d9a5f2e59
  resourceVersion: "1316406"
  uid: 184659db-2483-4f28-9ffa-f94737105f41
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 40Gi
  storageClassName: csi-rbd-sc
  volumeMode: Block
  volumeName: pvc-184659db-2483-4f28-9ffa-f94737105f41
status:
  accessModes:
  - ReadWriteMany
  capacity:
    storage: 40Gi
  phase: Bound

**Comment by use-epoll** [comment]
DV of  sys-disk which clone from the OS img
```
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    cdi.kubevirt.io/cloneType: network
    cdi.kubevirt.io/storage.clone.token: eyJhbGciOiJQUzI1NiJ9.eyJleHAiOjE2Njc0NjQyODksImlhdCI6MTY2NzQ2Mzk4OSwiaXNzIjoiY2RpLWFwaXNlcnZlciIsIm5hbWUiOiJpbWctNWpybmY4cmIiLCJuYW1lc3BhY2UiOiJ0ZXN0IiwibmJmIjoxNjY3NDYzOTg5LCJvcGVydGF0aW9uIjoiQ2xvbmUiLCJwYXJhbXMiOnsidGFyZ2V0TmFtZSI6ImRpc2steTRnaTN3aTAiLCJ0YXJnZXROYW1lc3BhY2UiOiJ0ZXN0In0sInJlc291cmNlIjp7Imdyb3VwIjoiIiwicmVzb3VyY2UiOiJwZXJzaXN0ZW50dm9sdW1lY2xhaW1zIiwidmVyc2lvbiI6InYxIn19.wdyUinPF7sV10b9OUGPhhmoMAa-3RpeAkHaoZn139sQNgVAjUC7n7LoWZdqDateL5fygVB2uy0lUtBUnlGlDihRSHOAvZdPnNmK_g6mdWqchf3CN9bN4sFUgZGI03TuHWstJoKeNqf3-FzWz5sVBXnQzAa32lkQR6fiKIwwHmkUunO01JQaqihwC3_uFt7Cpf2apODGkSeKuAFJDMsQxFEQEE0CeBa3Z3weNDxxaf0WTRZY0Bv_QvhzrXL09oH4BRo6-XJv28RuG5xBIqRwM7dQ7XLcZw2vL_OGL9bbxrj4KHZ4ikDJy6U8EQkRF2eeAoXU5EiGxG7LCJyw2p0XIcQ
    virtualization.study.com/disktype: system
  creationTimestamp: "2022-11-03T08:26:29Z"
  generation: 96
  labels:
    virtualization.study.com/bootorder: "1"
  name: disk-y4gi3wi0
  namespace: test
  resourceVersion: "1316291"
  uid: b9daaa1f-100b-41ca-9f15-b13d9a5f2e59
spec:
  pvc:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 40Gi
    volumeMode: Block
  source:
    pvc:
      name: img-5jrnf8rb
      namespace: test
status:
  claimName: disk-y4gi3wi0
  conditions:
  - lastHeartbeatTime: "2022-11-03T08:26:41Z"
    lastTransitionTime: "2022-11-03T08:26:41Z"
    message: PVC disk-y4gi3wi0 Bound
    reason: Bound
    status: "True"
    type: Bound
  - lastHeartbeatTime: "2022-11-03T08:29:31Z"
    lastTransitionTime: "2022-11-03T08:29:31Z"
    status: "True"
    type: Ready
  - lastHeartbeatTime: "2022-11-03T08:28:59Z"
    lastTransitionTime: "2022-11-03T08:28:59Z"
    message: Clone Complete
    reason: Completed
    status: "False"
    type: Running
  phase: Succeeded
  progress: 100.0%

```

**Comment by akalenyu** [comment]
Hmm, is there a VolumeSnapshotClass that corresponds to the ceph provisioner (`rbd.csi.ceph.com`)?
(`VolumeSnapshotClass.Driver` == `StorageClass.Provisioner`)

**Comment by use-epoll** [comment]
This is the volumesnapshotClass 
```
apiVersion: snapshot.storage.k8s.io/v1beta1
deletionPolicy: Delete
driver: rbd.csi.ceph.com
kind: VolumeSnapshotClass
metadata:
  creationTimestamp: '2022-11-01T07:55:51Z'
  generation: 5
  managedFields:
    - apiVersion: snapshot.storage.k8s.io/v1
      fieldsType: FieldsV1
      fieldsV1:
        'f:deletionPolicy': {}
        'f:driver': {}
      manager: controller-manager
      operation: Update
      time: '2022-11-01T07:55:51Z'
    - apiVersion: snapshot.storage.k8s.io/v1beta1
      fieldsType: FieldsV1
      fieldsV1:
        'f:parameters':
          .: {}
          'f:clusterID': {}
          'f:csi.storage.k8s.io/snapshotter-secret-name': {}
          'f:csi.storage.k8s.io/snapshotter-secret-namespace': {}
      manager: Mozilla
      operation: Update
      time: '2022-11-02T09:04:30Z'
  name: csi-rbd-sc
  resourceVersion: '3582722'
  uid: c0955dd1-4dcd-493d-9531-a3578545754f
parameters:
  clusterID: 611009d2-55c8-11ed-b17d-5d3222853857
  csi.storage.k8s.io/snapshotter-secret-name: csi-rbd-secret
  csi.storage.k8s.io/snapshotter-secret-namespace: kube-system
```

**Comment by akalenyu** [comment]
I believe we don't support `apiVersion: snapshot.storage.k8s.io/v1beta1` for a while now (since 1.24 IIRC):
https://github.com/kubevirt/containerized-data-importer/pull/2235

Could you try recreating it with the `v1` API? AFAIK no major changes happened
