### ISSUE TITLE
[sig-performance] Increase in memory requirements causing failures in sig-performance tests

### ISSUE THREAD

**Issue by brianmcarey** [kubevirt/kubevirt#8749]
**What happened**:
The sig-performance presubmit and periodic lanes started to fail constantly from 10/28/2022[1].

This is due to VMIs failing to be scheduled because of insufficient memory on the nodes. Looking at one of the recent failures[2], it can be seen in the logs that one of the pods remains in `Pending` state:
```
kubevirt-test-default1   pod/virt-launcher-testvmi-clncc-kkjtj          0/2     Pending   0               5m7s    <none>           <none>   <none>           1/1
```
([source](https://storage.googleapis.com/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.22-sig-performance/1590247846043455488/artifacts/performance/k8s-reporter/1_overview.log))

When we check why the pod is in pending state, it can be seen that the pod has failed to be scheduled due to insufficient memroy on the nodes:
```
            "status": {
                "phase": "Pending",
                "conditions": [
                    {
                        "type": "PodScheduled",
                        "status": "False",
                        "lastProbeTime": null,
                        "lastTransitionTime": "2022-11-09T09:00:21Z",
                        "reason": "Unschedulable",
                        "message": "0/4 nodes are available: 4 Insufficient memory."
                    },
                    {
                        "type": "kubevirt.io/virtual-machine-unpaused",
                        "status": "True",
                        "lastProbeTime": "2022-11-09T09:00:21Z",
                        "lastTransitionTime": "2022-11-09T09:00:21Z",
                        "reason": "NotPaused",
                        "message": "the virtual machine is not paused"
                    }
                ],
                "qosClass": "Guaranteed"
            }
```
([source](https://storage.googleapis.com/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.22-sig-performance/1590247846043455488/artifacts/performance/k8s-reporter/1_pods.log))

The memory requirements of the prowjobs did not change so there must be a change in the memory required by kubevirt. 

In the mean time, there is a PR(https://github.com/kubevirt/project-infra/pull/2442) to increase the node memory for these prowjobs just so that the Performance SIG can be provided with some usable results. 

Increasing the memory of these jobs every so often is not very sustainable and an investigation into the memory usage should be carried out. 

[1] https://testgrid.k8s.io/kubevirt-periodics#periodic-kubevirt-e2e-k8s-1.22-sig-performance
[2[ https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/periodic-kubevirt-e2e-k8s-1.22-sig-performance/1590247846043455488

**What you expected to happen**:
sig-performance lanes pass successfully

**How to reproduce it (as minimally and precisely as possible)**:
Reproducible using the automated test lanes.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): latest main
- Kubernetes version (use `kubectl version`): 1.22

**Comment by brianmcarey** [comment]
These memory issues could be related to the following PR - https://github.com/kubevirt/kubevirt/pull/8613

**Comment by rthallisey** [comment]
Now that the performance gate runs against every PR, we should notice sooner when there's an issue so it can be reported.  I think that should be enough to close this.
/close
