### ISSUE TITLE
Simplify running parallel and serial tests wrt ginkgo 2

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#8776]
**Is your feature request related to a problem? Please describe**:
We have switched to Ginkgo v2 a while ago but we didn't update the e2e tests code to use it's support for running tests in serial mode.

**Describe the solution you'd like**:

## serial decorator
Ginkgo V2 has the decorator [Serial](https://onsi.github.io/ginkgo/MIGRATING_TO_V2#serial-decorator) that is designed for running tests in serial. We need to add those to every test that needs to get run in serial, so Ginkgo can take care of doing that.

## `functests.sh`
Handling of parallel and serial tests in functests.sh is redundant when the decorator is being used. So instead of needing to execute serial and parallel test runs each on it's own, we can now just add the Serial decorator to the serial tests and run everything at once.

## quick feedback of parallel test run

One drawback is that we currently lose the "feature" of parallel functests being run first and serial functests not being run if any of the parallel tests failed. This not intentionally brought it feature turns out to give a quick feedback with a broad enough coverage while at the same time being pretty fast.

We have been discussing options with the Ginkgo authors [here](https://github.com/onsi/ginkgo/issues/892#issuecomment-1314072099) and it turns out that we might be getting `CurrentSuiteReport()` which will enable us to relatively easy implement something similar inside the tests codebase, namely not executing Serial tests if any of the parallel has failed. Therefore the PRs have been split into two, one taking care of the Serial additions and the changes in checking and the other one tackling the changes in execution of the test suites. 

We also might use [Synchronized(Before|After)Suite](https://onsi.github.io/ginkgo/#parallel-suite-setup-and-cleanup-synchronizedbeforesuite-and-synchronizedaftersuite) to enable communication between processes so that failure on parallel processes can make running serial tests skip.

## One output stream
The [docs for parallel test support](https://onsi.github.io/ginkgo/#spec-parallelization) say that the test results will be captured in one output stream in Ginkgo 2. Thus our fiddling with the output filenames in the tests entry point is obsolete.

## `junit-merger` obsolete
We also don't need to merge test result files any more, since the results will all be written to the same file. Thus also the fuss around output file names was removed from tests_suite_test.go.

## `CurrentSpecReport().IsSerial`
Finally checks for tests being run in serial mode (example: tests/testsuite/kubevirtresource.go) have to use the provided CurrentSpecReport().IsSerial now.

## Resulting TODOs
 * [x] add SerialDecorator to serial tests -> https://github.com/kubevirt/kubevirt/pull/8770
 * [ ] get rid of all the parallel vs. serial shell code that we have in hack/functests.sh currently -> https://github.com/kubevirt/kubevirt/pull/8788,
 * [ ] remove the `KUBEVIRT_E2E_RUN_ALL_SUITES` from the jobconfigs in project-infra
 * [ ] adjust how tests are run in all other places, meaning the removal of the serial run and the merging of the junit files.
 * [ ] get rid of the junit-merger since it's obsolete
 * [ ] drop staging/src/kubevirt.io/client-go/reporter/reporter.go

**Describe alternatives you've considered**:
Leave everything like it is, but then we need to adapt junit-merger to handle edge cases (i.e. multiple failures of AfterSuite).

**Additional context**:
Supporting Google Groups Thread that running Ginkgo twice can be avoided: https://groups.google.com/g/kubernetes-sig-testing/c/66_fWRp1jlg/m/BSTKHXddAQAJ

**Comment by oshoval** [comment]
Once KUBEVIRT_E2E_RUN_ALL_SUITES is dropped
https://github.com/kubevirt/kubevirt/pull/8991 should be reverted please

**Comment by xpivarc** [comment]
/reopen
/remove-lifecycle rotten
I find this compelling if we can get the same behavior.
