### ISSUE TITLE
Add new metrics to evaluate & alert CPU usage for individual instances

### ISSUE THREAD

**Issue by SubhasmitaSw** [kubevirt/kubevirt#8786]
**Is your feature request related to a problem? Please describe**:

The present set of metrics does not allow us to know the CPU usage (%) of each instance. We want to get alerted If the usage goes beyond certain % e.g. 80%. 

**Describe the solution you'd like**:

Some set of alerts like - `kubevirt_vmi_vcpu_total` & `kubevirt_vmi_vcpu_current`

**Describe alternatives you've considered**:

What we have currently is `kubevirt_vmi_vcpu_seconds` which limits to 
`kubevirt_vmi_vcpu_seconds`{state="running"} -> giving result
`kubevirt_vmi_vcpu_seconds`{state!="running"} -> no result.

**Comment by coldy1992** [comment]
> **Is your feature request related to a problem? Please describe**:
> 
> The present set of metrics does not allow us to know the CPU usage (%) of each instance. We want to get alerted If the usage goes beyond certain % e.g. 80%.
> 
> **Describe the solution you'd like**:
> 
> Some set of alerts like - `kubevirt_vmi_vcpu_total` & `kubevirt_vmi_vcpu_current`
> 
> **Describe alternatives you've considered**:
> 
> What we have currently is `kubevirt_vmi_vcpu_seconds` which limits to `kubevirt_vmi_vcpu_seconds`{state="running"} -> giving result `kubevirt_vmi_vcpu_seconds`{state!="running"} -> no result.

hello，I have the same question. Have you solved it? Can you share the answer，thank you！

**Comment by SubhasmitaSw** [comment]
@coldy1992 Not yet, but we found a workaround to use a new grafana dashboard & prometheus metrics. You can checkout here: https://github.com/harvester/harvester-installer/blob/master/pkg/config/templates/rancherd-12-monitoring-dashboard.yaml#L99

**Comment by coldy1992** [comment]
@SubhasmitaSw Just returned to the company after the holiday... I got it，thank you very much！
