### ISSUE TITLE
FR：hot(un)plug cpu and/or memory

### ISSUE THREAD

**Issue by williamfpx** [kubevirt/kubevirt#8787]
**Is your feature request related to a problem? Please describe**:
A clear and concise description of what the problem is.
hot(un)plug  cpu and/or memory on a running vm

**Describe the solution you'd like**:
1. libvirt hot(un)plug cpu：https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainSetVcpusFlags
   In order to hot(un)plug cpu，we may make xml as follows:
![image](https://user-images.githubusercontent.com/16223972/201870504-4f26940b-e649-4971-833b-5d7e253d87fc.png)

2. libvirt hot(un)plug memory：https://libvirt.org/html/libvirt-libvirt-domain.html#virDomainAttachDeviceFlags
   At first，we make xml as follows when vm was created.
![image](https://user-images.githubusercontent.com/16223972/201871071-72914c96-46ac-45b0-9dd3-74bebb48e1c8.png)

  Then，hotplug memory by attaching device as follows，or hotunplug memory by detaching device
https://libvirt.org/formatdomain.html#memory-devices
![image](https://user-images.githubusercontent.com/16223972/201870619-8507a12c-188a-4a53-a1fe-5b7c09a2d696.png)

3. A new CRD object called VirtualMachineInstanceScaler was introduced，it describes cpu and memory of the new vm 
![image](https://user-images.githubusercontent.com/16223972/201870797-4839d661-b62e-4968-a22a-8ce726230e7f.png)

4. Add Scaler controller to handle VirtualMachineInstanceScaler object，it's simliar to VirtualMachineInstanceMigration except creating new virt-launcher pod by using new cpu and memory。After live-migration is completed，Scaler controller should change vm‘s cpu and memory by calling libvirt function(virDomainSetVcpusFlags and virDomainAttachDeviceFlags)。Finally，vm/vmi spec should be changed too.

**Describe alternatives you've considered**:

**Additional context**:

Disadvantage：
1. Another node with enough resource is needed in order to hot(un)plug cpu/memory，It can't finish on the same node because of reusing live-migration process。
2. Guest numa is not supported，only one guest numa cell is supported，because which cell will be selected to hotplug new cpu is unknown and can't be defined。

**Comment by maiqueb** [comment]
You could try to socialize this idea and get some early feedback on the KubeVirt weekly community calls. 

They're Wednesday, at 15.00 UTC. You can add it to your calendar with [this info](https://github.com/kubevirt/community/#socializing).

**Comment by kvaps** [comment]
According to @fabiand's [message](https://groups.google.com/g/kubevirt-dev/c/tiYct_5ezhg/m/yseVy6RjCAAJ), this feature requires implementation of https://github.com/kubernetes/kubernetes/pull/102884 first

**Comment by kvaps** [comment]
I just prepared a new design proposal for this feature, I invite you to discuss https://github.com/kubevirt/community/pull/212
Any suggestions are welcome 🙂
