### ISSUE TITLE
Connection failed between windows vm and node

### ISSUE THREAD

**Issue by duyanyan** [kubevirt/kubevirt#879]
In a Openshift env (just one node), create two vms, one is cirros, the other is a windows vm. Failed to ping IP of windows vm from node.
```
# oc get pod -o wide
NAME                                           READY     STATUS    RESTARTS   AGE       IP            NODE
virt-launcher-testvm-ephemeral-z4htc   2/2       Running   0          1h        172.17.0.10   localhost
virt-launcher-windows2012r2-zkth2      1/1       Running   0          35m       172.17.0.9    localhost

# oc get vm
NAME               AGE
testvm-ephemeral   1h
windows2012r2      35m
```
Ping the two vms from node: 
```
# ping -c 3 172.17.0.10
PING 172.17.0.10 (172.17.0.10) 56(84) bytes of data.
64 bytes from 172.17.0.10: icmp_seq=1 ttl=64 time=0.316 ms
64 bytes from 172.17.0.10: icmp_seq=2 ttl=64 time=0.521 ms
64 bytes from 172.17.0.10: icmp_seq=3 ttl=64 time=0.454 ms

--- 172.17.0.10 ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 2035ms
rtt min/avg/max/mdev = 0.316/0.430/0.521/0.087 ms

# ping -c 3 172.17.0.9
PING 172.17.0.9 (172.17.0.9) 56(84) bytes of data.

--- 172.17.0.9 ping statistics ---
3 packets transmitted, 0 received, 100% packet loss, time 2053ms
```

**Comment by rmohr** [comment]
Is that happening on `v0.4.0` or `v0.4.0-alpha.2`? In theory `v0.4.0` should contain #869 which should fix exactly that. @mlsorensen @vladikr FYI.

**Comment by duyanyan** [comment]
I could reproduce it even I use v0.4.0, but I use an old version kubevirt.yaml.in, since there is issue when use kubevirt-ansible to deploy it with latest kubevirt code (see https://github.com/kubevirt/kubevirt-ansible/issues/179), does that affect?
```
# docker images
REPOSITORY                                     TAG                 IMAGE ID            CREATED             SIZE
docker.io/kubevirt/virt-api                    v0.4.0              f7221b447112        2 days ago          276 MB
docker.io/kubevirt/virt-handler                v0.4.0              c5fc986a2f2f        2 days ago          272 MB
docker.io/kubevirt/virt-launcher               v0.4.0              692f0cd615f3        2 days ago          611 MB
docker.io/kubevirt/virt-controller             v0.4.0              17112c790a55        2 days ago          271 MB
```

**Comment by mlsorensen** [comment]
Can the IP and routing config on the windows VM be provided? What was the last known version where this worked with the windows PV being used?

**Comment by mlsorensen** [comment]
Ok, you got me. It looks like the DHCP routes, IP, gateway are all coming through per the previous patches.

I see the IP is not .9 for the windows VM  per the previous info, it’s .10. Is this just for to subsequent testing, do kubernetes and the VM agree on IP?

Has the VM connectivity been tested to see what works and doesn’t? Or is this only a host -> guest issue?

**Comment by duyanyan** [comment]
The issue caused by the windows firewall.
After disable the firewall in windows, the connection to win vm is working well
