### ISSUE TITLE
user password restores to secret defined data after restart vm

### ISSUE THREAD

**Issue by chenxinlong** [kubevirt/kubevirt#8813]
**What happened**:

Start a vm with user password stores in k8s secret : 
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: "2022-11-18T07:16:38Z"
  generation: 15
  name: vm-cgsyt1ej
  namespace: test
  resourceVersion: "2023889"
  uid: c0dca3cb-d4b4-451c-b3fa-cb77dd859d17
spec:
  runStrategy: RerunOnFailure
  template:
    metadata:
      creationTimestamp: null
    spec:
      accessCredentials:
      - userPassword:
          propagationMethod:
            qemuGuestAgent: {}
          source:
            secret:
              secretName: vm-1-pwd
      domain:
        # ...
```
Let say the initial username is "Administrator", the password is "123456".

Start this vm and change the password to "abcdefg" in the vnc.  After restart this vm, the password restores to the secret data "123456".

**What you expected to happen**:

What I expected is when I change the password by using vnc(or console/ssh), restart this vm the password do not restore to secret defined password.

**Comment by alicefr** [comment]
@chenxinlong kubevirt isn't able to distinguish if the secret is used by the administrator and then changed by the user. It always (re)sets it if it is present in the VM specification. 
Would be a possibility for you to change the k8s secret with the new password? If not, you could try to remove the secret from the VM specification, but I'm not sure is possible and even a good idea. 
Another way is avoiding the k8s secret and set an initial password using libguestfs-tools and [virt-customize](https://libguestfs.org/virt-customize.1.html), with for example the [tekton tasks](https://github.com/kubevirt/kubevirt-tekton-tasks/tree/main/tasks/disk-virt-customize) or [`virtctl guestfs`](https://github.com/kubevirt/kubevirt/blob/main/docs/guestfs.md)

**Comment by chenxinlong** [comment]
There's two scenario for password setting : 

1. initial password set
2. runtime password modify 

For the first scenario, seems kubevirt does not support Cloudbase-init on windows accoding to https://github.com/kubevirt/user-guide/issues/309 , so I'm looking for another way to solve this(maybe Sysprep), if there's a better way for initial password set on windows, please let me know. 

For the second scenario, like metioned upon, after modify the password on the guest, it will be restores to the secret defined password.  And there's no `chpwd` endpoint defined on the virt-api subresources, so I will execute `kubectl exec -it <vmi pod> -- virsh set-user-password 1 <user> <pwd>` directly.  Please let'me know if there's a better solution.

**Comment by chenxinlong** [comment]
thanks.
