### ISSUE TITLE
kubectl virt image-upload fails with no user-visible indication of why

### ISSUE THREAD

**Issue by mdbooth** [kubevirt/kubevirt#8818]
**What happened**:
I'm using the kubectl `virt` plugin, installed via krew (incidentally it's the latest available from krew, so the reported version disparity may be a separate issue):

```
> kc virt image-upload -n home-assistant pvc home-assistant-vm --image-path=./haos_ova-9.3.qcow2 --size 50G --storage-class rook-cephfs
PVC home-assistant/home-assistant-vm not found
PersistentVolumeClaim home-assistant/home-assistant-vm created
Waiting for PVC home-assistant-vm upload pod to be ready...
You are using a client virtctl version that is different from the KubeVirt version running in the cluster
Client Version: v0.57.1
Server Version: v0.58.0
timed out waiting for the condition
```

The timeout takes several minutes. During this time no events are created in either the target or `kubevirt` namespaces. AFAICT no pod is created anywhere, so I can't examine its status for environmental issues. There may be more information in the logs but these are not user-visible. As a user I'm now at a dead-end. All I know is: it didn't work.

**What you expected to happen**:
Success would have been ideal. However, given that the most likely reason for the failure is PEBKAC or an environmental issue I would expect:

Some indication in the output of `kubectl virt image-upload` of what it's *really* doing. Don't tell me it's waiting for a pod if it hasn't created the pod. If it has created the pod, tell me where.

An event, ideally in the target namespace, ideally referenced by the pod which ideally it would have created. i.e. I would know which pod is failing because the tool told me, and I can find out why from `kubectl describe pod`.

**How to reproduce it (as minimally and precisely as possible)**:
Most likely: do something wrong before running the above command. Unfortunately I can't tell you what that is, which is the subject of this issue.

**Additional context**:
I will go spelunking in log files anyway, but if I find the problem there this issue still stands: log files are not UI.

**Environment**:
- KubeVirt version (use `virtctl version`): 0.58.0
- Kubernetes version (use `kubectl version`): 1.25.3
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: Baremetal
- OS (e.g. from /etc/os-release): Fedora CoreOS
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by mdbooth** [comment]
The reason it failed was that I hadn't installed CDI. However, the bug stands: it should have told me it was attempting to connect to some endpoint which wasn't available, or that perhaps it had created some CR to manage the import (I haven't looked at the implementation). I could investigate the CR and notice that it has no associated controller.

**Comment by jsakil14** [comment]
> **What happened**: I'm using the kubectl `virt` plugin, installed via krew (incidentally it's the latest available from krew, so the reported version disparity may be a separate issue):
> 
> ```
> > kc virt image-upload -n home-assistant pvc home-assistant-vm --image-path=./haos_ova-9.3.qcow2 --size 50G --storage-class rook-cephfs
> PVC home-assistant/home-assistant-vm not found
> PersistentVolumeClaim home-assistant/home-assistant-vm created
> Waiting for PVC home-assistant-vm upload pod to be ready...
> You are using a client virtctl version that is different from the KubeVirt version running in the cluster
> Client Version: v0.57.1
> Server Version: v0.58.0
> timed out waiting for the condition
> ```
> 
> The timeout takes several minutes. During this time no events are created in either the target or `kubevirt` namespaces. AFAICT no pod is created anywhere, so I can't examine its status for environmental issues. There may be more information in the logs but these are not user-visible. As a user I'm now at a dead-end. All I know is: it didn't work.
> 
> **What you expected to happen**: Success would have been ideal. However, given that the most likely reason for the failure is PEBKAC or an environmental issue I would expect:
> 
> Some indication in the output of `kubectl virt image-upload` of what it's _really_ doing. Don't tell me it's waiting for a pod if it hasn't created the pod. If it has created the pod, tell me where.
> 
> An event, ideally in the target namespace, ideally referenced by the pod which ideally it would have created. i.e. I would know which pod is failing because the tool told me, and I can find out why from `kubectl describe pod`.
> 
> **How to reproduce it (as minimally and precisely as possible)**: Most likely: do something wrong before running the above command. Unfortunately I can't tell you what that is, which is the subject of this issue.
> 
> **Additional context**: I will go spelunking in log files anyway, but if I find the problem there this issue still stands: log files are not UI.
> 
> **Environment**:
> 
> * KubeVirt version (use `virtctl version`): 0.58.0
> * Kubernetes version (use `kubectl version`): 1.25.3
> * VM or VMI specifications: N/A
> * Cloud provider or hardware configuration: Baremetal
> * OS (e.g. from /etc/os-release): Fedora CoreOS
> * Kernel (e.g. `uname -a`): N/A
> * Install tools: N/A
> * Others: N/A

I have same client / server version mismatch , is it an issue or can be ignored?  Also , where is the image upload file located in ? Is it on the kubevirt host or on your local machine.
