### ISSUE TITLE
Request help Start windowS XPVM blue scree

### ISSUE THREAD

**Issue by maikoulin** [kubevirt/kubevirt#8831]
![image](https://user-images.githubusercontent.com/9984908/203483145-6924cc1d-a651-4368-8de9-33eb326658a5.png)

Kubernetes version  v1.22.12
kubevirt version 0.49.0-2
Kernel  5.3.18-150300.59.87

**Comment by xpivarc** [comment]
@dhiller You have played with windows previously. Would you know how to help here?

**Comment by vasiliy-ul** [comment]
@maikoulin, are you trying to use an existing image with a WinXP VM or to install a fresh system? Could you share your VM yaml? Also looking at `kubevirt version 0.49.0-2` I guess you are using Harvester?

**Comment by dhiller** [comment]
@maikoulin I've had same problems getting the 0X7B when I tried that.
I had success when moving an old VirtualBox image to KubeVirt. Here's what I did in a nutshell:

- Prepare the VM to be imported inside VirtualBox
- Convert the disk image to an importable format
- Import the image into kubevirt using cdi-uploadproxy
- Create the vm with the image

Regarding the first step: what helped me was running the converted `qcow` image with qemu beforehand:

Example:
```
$ qemu-system-x86_64 -netdev user,id=hostnet0 \
    -device virtio-net-pci,netdev=hostnet0 \
    -device ahci,id=ahci \
    -drive id=disk,file=/path/to/your/disk.qcow2,index=0,media=disk,format=qcow2,bus=0 \
    -vga cirrus -display gtk -device AC97 -audiodev alsa,id=alsa -usb
```

Here's the repo with all manifests, scripts and slides I used: https://github.com/dhiller/containerdays.io-2022

**Comment by hanqingwu** [comment]
I have some problem when i according this web try to set machine type  pc-i440fx-3.1
https://github.com/kubevirt/kubevirt/issues/2762
but I  get error:
`The request is invalid: spec.template.spec.domain.machine.type: spec.template.spec.domain.machine.type is not supported: pc-i440fx-3.1 (allowed values: [q35* pc-q35*])`

**Comment by hanqingwu** [comment]
after set machine type pc-i440fx-3.1, I got :
/usr/libexec/qemu-kvm' does not support machine type 'pc-i440fx-3.1'

**Comment by hanqingwu** [comment]
kubevirt  v1.0.0  qemu-kvm -machine help 
Supported machines are:
pc                   RHEL 7.6.0 PC (i440FX + PIIX, 1996) (alias of pc-i440fx-rhel7.6.0)
pc-i440fx-rhel7.6.0  RHEL 7.6.0 PC (i440FX + PIIX, 1996) (default) (deprecated)
q35                  RHEL-9.2.0 PC (Q35 + ICH9, 2009) (alias of pc-q35-rhel9.2.0)
pc-q35-rhel9.2.0     RHEL-9.2.0 PC (Q35 + ICH9, 2009)
pc-q35-rhel9.0.0     RHEL-9.0.0 PC (Q35 + ICH9, 2009)
pc-q35-rhel8.6.0     RHEL-8.6.0 PC (Q35 + ICH9, 2009) (deprecated)
pc-q35-rhel8.5.0     RHEL-8.5.0 PC (Q35 + ICH9, 2009) (deprecated)
pc-q35-rhel8.4.0     RHEL-8.4.0 PC (Q35 + ICH9, 2009) (deprecated)
pc-q35-rhel8.3.0     RHEL-8.3.0 PC (Q35 + ICH9, 2009) (deprecated)
pc-q35-rhel8.2.0     RHEL-8.2.0 PC (Q35 + ICH9, 2009) (deprecated)
pc-q35-rhel8.1.0     RHEL-8.1.0 PC (Q35 + ICH9, 2009) (deprecated)
pc-q35-rhel8.0.0     RHEL-8.0.0 PC (Q35 + ICH9, 2009) (deprecated)
pc-q35-rhel7.6.0     RHEL-7.6.0 PC (Q35 + ICH9, 2009) (deprecated)


So we should compile qemu-kvm  by myself  to support   pc-i440fx-3.1 .

**Comment by bighua** [comment]
> kubevirt v1.0.0 qemu-kvm -machine help Supported machines are: pc RHEL 7.6.0 PC (i440FX + PIIX, 1996) (alias of pc-i440fx-rhel7.6.0) pc-i440fx-rhel7.6.0 RHEL 7.6.0 PC (i440FX + PIIX, 1996) (default) (deprecated) q35 RHEL-9.2.0 PC (Q35 + ICH9, 2009) (alias of pc-q35-rhel9.2.0) pc-q35-rhel9.2.0 RHEL-9.2.0 PC (Q35 + ICH9, 2009) pc-q35-rhel9.0.0 RHEL-9.0.0 PC (Q35 + ICH9, 2009) pc-q35-rhel8.6.0 RHEL-8.6.0 PC (Q35 + ICH9, 2009) (deprecated) pc-q35-rhel8.5.0 RHEL-8.5.0 PC (Q35 + ICH9, 2009) (deprecated) pc-q35-rhel8.4.0 RHEL-8.4.0 PC (Q35 + ICH9, 2009) (deprecated) pc-q35-rhel8.3.0 RHEL-8.3.0 PC (Q35 + ICH9, 2009) (deprecated) pc-q35-rhel8.2.0 RHEL-8.2.0 PC (Q35 + ICH9, 2009) (deprecated) pc-q35-rhel8.1.0 RHEL-8.1.0 PC (Q35 + ICH9, 2009) (deprecated) pc-q35-rhel8.0.0 RHEL-8.0.0 PC (Q35 + ICH9, 2009) (deprecated) pc-q35-rhel7.6.0 RHEL-7.6.0 PC (Q35 + ICH9, 2009) (deprecated)
> 
> So we should compile qemu-kvm by myself to support pc-i440fx-3.1 .

have you resolved this problem? I encounter the same issue in version 1.5.1
