### ISSUE TITLE
virtctl scp from or to windows server failed

### ISSUE THREAD

**Issue by junfsir** [kubevirt/kubevirt#8832]
**What happened**:
Using virtctl scp command to copy file from windows server to linux or windows failed, and there is OpenSSH installed and running on windows server.
`# virtctl scp   administrator@win2k12r2-vmi:C:/users/administrator/desktop/filebeat-6.8.9.zip /tmp/
administrator@vmi/win2k12r2-vmi.openshift-cnv's password:
scp: 'C:/users/administrator/desktop/filebeat-6.8.9.zip': No such file or directory`
But it worked, when using virtctl port-forward and scp.

**What you expected to happen**:
Copy file successfully from remote windows server, while using virtctl scp.

**How to reproduce it (as minimally and precisely as possible)**:
Using virtctl scp to copy file from windows server directly.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.53.2-93-g1450e4176
- Kubernetes version (use `kubectl version`): v1.24.0+b62823b
- VM or VMI specifications: windows server 2012
- Cloud provider or hardware configuration: 96 Cores and 512G
- OS (e.g. from /etc/os-release): Red Hat Enterprise Linux CoreOS release 4.11
- Kernel (e.g. `uname -a`): 4.18.0-372.19.1.el8_6.x86_64

**Comment by rmohr** [comment]
Would you mind trying with an `ed25519` key instead of rsa? I have the suspicion that this may be related to something like https://github.com/golang/go/issues/56342.
