### ISSUE TITLE
Warning  FailedPvcNotFound  7m (x20 over 17m)  virtualmachine-controller  failed to render launch manifest: didn't find PVC 74v4-snap-os

### ISSUE THREAD

**Issue by swq499809608** [kubevirt/kubevirt#8860]
1. Create vm is fail,  Error info .... 
Warning  FailedPvcNotFound  7m (x20 over 17m)  virtualmachine-controller  failed to render launch manifest: didn't find PVC 74v4-snap-os

2. Snap create is ok :

kubectl  get pvc -n csi-ceph-rbd 
  NAME               STATUS   VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
  74v4               Bound    pvc-74a41d1b-d1a8-4d6c-b529-bef72243a3ca   38Gi       RWO            csi-rbd-sc     48m
  74v4-snap-data     Bound    pvc-6c18b9bc-f545-49f4-88cc-8ceb95d0b904   100Gi      RWO            csi-rbd-sc     23m
  74v4-snap-os       Bound    pvc-3f6fa67f-5449-435a-8e87-e8a3216b3efc   40Gi       RWO            csi-rbd-sc     24m

3. vm.yaml
[root@k8s-master-thallo-72-211-lf3 vv1]# cat 74v4-snap.yaml 
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: 74v4-snap
  namespace: k8s-vmi
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/vm: 74v4-snap
    spec:
      terminationGracePeriodSeconds: 30
      domain:
        resources:
          requests:
            memory: 4096M
        devices:
          disks:
          - disk:
              bus: virtio
            name: 74v4-snap-os
          - disk:
              bus: virtio
            name: 74v4-snap-data
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - bridge: {}
            name: default
      networks:
        - name: default
          pod: {}
      volumes:
        - name: 74v4-snap-os
          persistentVolumeClaim:
            claimName: 74v4-snap-os
        - name: 74v4-snap-data
          persistentVolumeClaim:
            claimName: 74v4-snap-data
        - name: cloudinitdisk
          cloudInitNoCloud:
            userData: |-
              runcmd:
                - [ systemctl, restart, --no-block, salt-minion ]

**Comment by usrbinkat** [comment]
Okay, first look it seems the PVC you have allocated is in the namespace csi-ceph-rbd as seen in your command `kubectl get pvc -n csi-ceph-rbd`, while the VM is in the namespace `k8s-vmi`.

Try again with the PVC and VM in the same namespace and see if you get further with that.
