### ISSUE TITLE
"Can't connect to websocket (404): 404 page not found"

### ISSUE THREAD

**Issue by johnhamelink** [kubevirt/kubevirt#887]
Hi there,

I'm trying to run the demo kubevirt inside a fresh instance of minikube 0.25.2, running kubernetes 1.9.4. All the commands run successfully, however when I try to connect with `virtctl vnc testvm` or `virtctl console testvm` I get a 404 error:

```
kubectl version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.6", GitCommit:"9f8ebd171479bec0ada837d7ee641dec2f8c6dd1", GitTreeState:"clean", BuildDate:"2018-03-21T15:21:50Z", GoVersion:"go1.9.3", Compiler:"gc", Platform:"darwin/amd64"}
Server Version: version.Info{Major:"", Minor:"", GitVersion:"v1.9.4", GitCommit:"bee2d1505c4fe820744d26d41ecd3fdd4a3d6546", GitTreeState:"clean", BuildDate:"2018-03-21T21:48:36Z", GoVersion:"go1.9.1", Compiler:"gc", Platform:"linux/amd64"}
```

```
minikube version
minikube version: v0.25.2
```

```
virtctl console testvm
Escape sequence is ^]
                     Can't connect to websocket (404): 404 page not found
```

**Comment by gouyang** [comment]
I have met the same issue in #858, the root cause is that the pod `virt-api` is not running and it's resolved it by update `virt-api` image, delete the old image and pull again.

**Comment by johnhamelink** [comment]
The docs all mention version 0.3.0 - Upgrading to version 0.4.0 fixed this issue for me. It'd be very useful if virtctl displayed the client & server versions, just like kubectl does!

**Comment by fabiand** [comment]
Thanks @johnhamelink good idea.
