### ISSUE TITLE
Add nodeSelector for newVMI test utility functions

### ISSUE THREAD

**Issue by pbxqdown** [kubevirt/kubevirt#8872]
newVMI test utility functions don't have nodeSelector specified. This means test VMI can be scheduled to any nodes. 

On large cluster with different host types, only specific type of node is allowed to run VMI on. 

 It would be good for test utility functions(E.g. `NewRandomVMIWithEphemeralDisk`) to have nodeSelector support.

**Comment by xpivarc** [comment]
Hi @pbxqdown ,
There is an ongoing effort to remove `NewRandomVMIWithEphemeralDisk` and replace it with a more flexible `libvmi` package.

Can you elaborate on why you want to limit the test suite to a subset of nodes?

**Comment by pbxqdown** [comment]
Using `limbmi` package in future would be good. Wondering which release would bring in this change.
Our zone has different host types. Some hosts have stricter security context applied and prohibit container-disk testVMI to schedule on.
