### ISSUE TITLE
Can not install windows 11

### ISSUE THREAD

**Issue by xiaocode** [kubevirt/kubevirt#8893]
**Description**:
I read the post: https://kubevirt.io/2022/KubeVirt-installing_Microsoft_Windows_11_from_an_iso.html , did everything in the post, but I can not "virtctl vnc" the VMI, I got something as follow:

```
{"component":"","level":"info","msg":"--proxy-only is set to false, listening on 127.0.0.1\n","pos":"vnc.go:116","timestamp":"2022-12-02T02:42:33.971555Z"}
{"component":"","level":"info","msg":"connection timeout: 1m0s","pos":"vnc.go:157","timestamp":"2022-12-02T02:42:33.972022Z"}
Error encountered: could not find remote-viewer or vncviewer binary in $PATH
```

And when I use command "virtctl console" the VMI, enter the "boot manager", I can boot from file, But it shows "Press any key to boot from CD or DVD.." then immediately back to the "boot manager"

**What you expected**:
Install windows 11 successful

**URL**:
 https://kubevirt.io/2022/KubeVirt-installing_Microsoft_Windows_11_from_an_iso.html

**Additional context**:
I can install other linux OS in the /examples.
I tried CDI upload *.iso to the PVC, but it can not be recognized, then I tried to upload *.iso to docker image as containerDisk, finally it can be recognized by the boot manager.

**Comment by rmohr** [comment]
@xiaocode in order to use VNC from the terminal you will have to install `remote-viewer`. The package is called on debian and fedora in both cases `virt-viewer`.

**Comment by xiaocode** [comment]
> 

Thanks a lot! It works!
