### ISSUE TITLE
Adding taints/tolerations for installing KubeVirt on ARM64 in multi-architecture cluster

### ISSUE THREAD

**Issue by shiny-zero** [kubevirt/kubevirt#8894]
We are running two separate node groups on AWS EKS, one is x86_64 and the other ARM64.

We want to install the ARM64 version of kubevirt so we can run virtual machines on AWS's a1 instances in the second node group.
Followed the instructions for the [experimental developer build](https://kubevirt.io/user-guide/operations/installation/#experimental-arm64-developer-builds) and added taints to my ARM64 nodes. The idea was to limit the installation of all resources to the nodes with architecture that supports them.

I was able to add `tolerations` and `affinity` to the kubevirt `Deployment` resource in the template, however once the `virt-operator` pods come up, the kubevirt `Job` resource still tries to create pods on the nodes with x86_64. Is there a way to fix this?

**Comment by zhlhahaha** [comment]
I think your are running a multi-arch kubernetes cluster. Maybe you can give this PR a try https://github.com/kubevirt/kubevirt/pull/8293, it used to solve the hybird cluster problem.
**But be caution**, the solution is still under discussion.
The propose is here: https://docs.google.com/document/d/1KYc3lsHHhri0gbCZTOGe5lz2dNJogRRwrXwN9Do9kT0/edit#
