### ISSUE TITLE
Add virtcl version command

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#891]
Add `virtcl version` command so that people have an easy way to see which virtctl and kubevirt version they use.

Output should be similar to

```
cluster/kubectl.sh version
Client Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T12:22:21Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"9", GitVersion:"v1.9.3", GitCommit:"d2835416544f298c919e2ead3be3d0864b52323b", GitTreeState:"clean", BuildDate:"2018-02-07T11:55:20Z", GoVersion:"go1.9.2", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by davidvossel** [comment]
we should also consider enumerating what KubeVirt features are present as well.

**Comment by SchSeba** [comment]
I was looking into this issue,I also check how kubernetes do it.

For the client they use a script in build time to push this variables to the compiled code with ldflags
For the server they again push data with ldflags into the api-server and have an api url /version. 
The returned data is unmarshal with the follow struct and displayed to the user.

```
type Info struct {
	Major        string `json:"major"`
	Minor        string `json:"minor"`
	GitVersion   string `json:"gitVersion"`
	GitCommit    string `json:"gitCommit"`
	GitTreeState string `json:"gitTreeState"`
	BuildDate    string `json:"buildDate"`
	GoVersion    string `json:"goVersion"`
	Compiler     string `json:"compiler"`
	Platform     string `json:"platform"`
}
```

Our virt-api is not expose outside the cluster so we need to create a resource for that.
I will like to know if this way is acceptable.

**Comment by davidvossel** [comment]
> Our virt-api is not expose outside the cluster so we need to create a resource for that.

I'm not sure I follow this. why would we need to expose virt-api outside of the cluster to retrieve versioning info?

**Comment by SchSeba** [comment]
In kubernetes they have a url /version to get all this data. 
We need something like this to get our data from the virt-api

**Comment by fabiand** [comment]
Sounds good @SchSeba can you file an issue to track the server side?

**Comment by SchSeba** [comment]
Can We close this issue? 
The feature was merged  :)
[Pull 1025](https://github.com/kubevirt/kubevirt/pull/1025)
