### ISSUE TITLE
Kubevirt Device Verification on Arm64

### ISSUE THREAD

**Issue by zhlhahaha** [kubevirt/kubevirt#8916]
Devices | Description | Status on Arm64
-- | -- | --
DisableHotplug |   | supported
Disks | sata/ virtio busmake | support virtio bus
Watchdog | i6300esb | not support
UseVirtioTransitional | virtio-transitional | supported
Interfaces | e1000/ virtio-net-device | support virtio-net-device
Inputs | tablet virtio/usb bus | support
AutoattachPodInterface | connect to /net/tun (devices.kubevirt.io/tun) | support
AutoattachGraphicsDevice | create a virtio-gpu device / vga device | support virtio-gpu
AutoattachMemBalloon | virtio-balloon-pci-non-transitional | support
AutoattachInputDevice | auto add tablet | support
Rng | virtio-rng-pci-non-transitional host:/dev/urandom | support
BlockMultiQueue | "driver":"virtio-blk-pci-non-transitional","num-queues":$cpu_number | support
NetworkInterfaceMultiQueue | -netdev tap,fds=21:23:24:25,vhost=on,vhostfds=26:27:28:29,id=hostua-default#fd number equals to queue number | supported
GPUs |   | not verified
Filesystems | virtiofs, vhost-user-fs-pci, need to enable featuregate: ExperimentalVirtiofsSupport | supported
ClientPassthrough | https://www.linaro.org/blog/kvm-pciemsi-passthrough-armarm64/on x86_64, iommu need to be enabled | not verified
Sound | ich9/ ac97 | not support
TPM | tpm-tis-devicehttps://qemu.readthedocs.io/en/latest/specs/tpm.html | supported
Sriov | vfio-pci | not verified

Summary: 
Watchdog device, Sound device are not supported on Arm64
Beyond them, secure boot is also not support on Arm64. 
SRIOV, GPU and ClientPassthrough still need to be verified.

**Comment by andreabolognani** [comment]
I forgot to mention that virtio-transitional support is really just intended for getting legacy operating systems such as RHEL 6 to run. Since aarch64 support in distros is still relatively new, I think it might be fair to assume that virtio-transitional will never need to be enabled on aarch64. Maybe we should reject such a configuration outright?

**Comment by zhlhahaha** [comment]
Hi, @andreabolognani  thanks for your reply.

> SR-IOV I think should work? I might be wrong here, but I can't think of anything that would prevent it from working on aarch64 off the top of my head.

Yes, you are right.

> The watchdog and sound devices implemented in QEMU seem to be all x86-specific, so I'm not surprised that doesn't work. Does KubeVirt report a nice error message when attempts to use them are made or do you get a less user-friendly one from libvirt or QEMU? Perhaps there's room for improvement here.

It is a good suggestion, currently, we do not have a nice error message for these devices.

> Note that there's some work happening on enabling Secure Boot on aarch64 via special stateless edk2 builds that come with the necessary certificates already enrolled. So we might be able to lift this limitation relatively soon :)

I see. I do not have experience with secure boot. Do I need to do some work on enabling it?

>  Since aarch64 support in distros is still relatively new, I think it might be fair to assume that virtio-transitional will never need to be enabled on aarch64. Maybe we should reject such a configuration outright?

Currently, virtio-pci-non-transitional is used by default on aarch64, unless users specify to use virtio-transitional. Do you mean we can add a filter to tell users not to use virtio-transitional on aarch64?

**Comment by andreabolognani** [comment]
> > Note that there's some work happening on enabling Secure Boot on aarch64 via special stateless edk2 builds that come with the necessary certificates already enrolled. So we might be able to lift this limitation relatively soon :)
> 
> I see. I do not have experience with secure boot. Do I need to do some work on enabling it?

The work at the firmware / libvirt level is not done yet, so it's too early to enable anything in KubeVirt. When the time comes, I think there's going to be some new XML but that should be fairly arch-independent, so it might very well be the case that no aarch64-specific work will be needed.

> > Since aarch64 support in distros is still relatively new, I think it might be fair to assume that virtio-transitional will never need to be enabled on aarch64. Maybe we should reject such a configuration outright?
> 
> Currently, virtio-pci-non-transitional is used by default on aarch64, unless users specify to use virtio-transitional. Do you mean we can add a filter to tell users not to use virtio-transitional on aarch64?

Thinking about it again, rejecting such a configuration might be too harsh. There's nothing inherently wrong about using virtio-transitional, it's just... Unnecessary. But since the default is to use non-transitional anyway, most people will never end up with a suboptimal configuration, so it's probably fine to leave things as they are right now :)

**Comment by gunine** [comment]
I verified that the SR-IOV works properly in ARM64. The mellanox connectX-5 (MT278000) has been tested. I plan to take sometime to verify Inte NIC (X710, E810) as well.

**Comment by zhlhahaha** [comment]
> I verified that the SR-IOV works properly in ARM64. The mellanox connectX-5 (MT278000) has been tested. I plan to take sometime to verify Inte NIC (X710, E810) as well. I also verified that multus CNI works properly in ARM64. Note that since the upstreamed SR-IOV CNI only supports up to multus-3.9, so need to maintain the version of cluster-network-addons-operator equal or lower than 0.80.0.

Thanks @gunine

**Comment by gunine** [comment]
I verified that GPU passthrough also works flawlessly in our ARM64 environment. The tested GPU model is Tesla T4 and RTX A6000. Note that the KubeVirt built-in device provide has been used for the passthrough, and the external provider provided by the GPU vendor has not been tested.

**Comment by alaypatel07** [comment]
- I was able to confirm SRIOV device plugin successfully assigning vrio nics to the VM.
- I was also able to confirm multuls bridged network works with two scenarios: 
   1) 2 VMIs landing on the same node.
   2) 2 VMIs landing on different node going trough vtep across IP network.

**Comment by lucheng0127** [comment]
Interface support on Arm64, can only support access interface by virtio-pci not support virtio-mmio.

**Comment by andreabolognani** [comment]
> Interface support on Arm64, can only support access interface by virtio-pci not support virtio-mmio.

That's true for all devices, not just interfaces. virtio-mmio is still supported at the libvirt level, but it hasn't been the default for several years now and it's generally not recommended to use it.

**Comment by lucheng0127** [comment]
> > Interface support on Arm64, can only support access interface by virtio-pci not support virtio-mmio.
> 
> That's true for all devices, not just interfaces. virtio-mmio is still supported at the libvirt level, but it hasn't been the default for several years now and it's generally not recommended to use it.

Maybe we can support it, cause some kernel not works well with virtio-pci,
if we try to boot a kernel, it can't get those devices.
So I'm not sure weather it will support this feature in the future.

**Comment by andreabolognani** [comment]
> Maybe we can support it, cause some kernel not works well with virtio-pci

Can you provide some examples?

As far as I know most aarch64 OS, including those that are not Linux, have been able to work with virtio-pci perfectly fine for years. At least those that target QEMU's virt machine type, i.e. a reasonably standardized hardware environment with support for PCI, ACPI, UEFI and so on.

I'm aware of things like Raspbian requiring use of alternative machine types, virtio-mmio and direct kernel boot... I believe KubeVirt is not aiming at supporting that sort of use case.

**Comment by lucheng0127** [comment]
> > Maybe we can support it, cause some kernel not works well with virtio-pci
> 
> Can you provide some examples?
> 
> As far as I know most aarch64 OS, including those that are not Linux, have been able to work with virtio-pci perfectly fine for years. At least those that target QEMU's virt machine type, i.e. a reasonably standardized hardware environment with support for PCI, ACPI, UEFI and so on.
> 
> I'm aware of things like Raspbian requiring use of alternative machine types, virtio-mmio and direct kernel boot... I believe KubeVirt is not aiming at supporting that sort of use case.

Yep, there are very few situation need virtio-mmio support, but i need to try it.
But if kubevirt support it is good to me, LOL
