### ISSUE TITLE
using initContainer to conduct image pull and import to PVC instead of CDI

### ISSUE THREAD

**Issue by yangxiaoliang** [kubevirt/kubevirt#8921]
**Is your feature request related to a problem? Please describe**:
We are using kubevirt and cdi to create VMs, but recently we hit some schedule issues which caused by the virt-launcher temporary pod as described at https://github.com/kubevirt/kubevirt/issues/6531 and  https://github.com/kubevirt/kubevirt/issues/8487.

As @awels and @rmohr discussed at this link: https://github.com/kubevirt/kubevirt/issues/6531 , just starts the virt-launcher pod normally, and waiting the image to be pulled and imported to the PV is a potential solution, but this solution requires the CSI driver to support the PV can be access by multiple pods on the same node in RWO mode. The CSI driver can meet the requirement in our product environments, but my concern is that in this situation although the cdi importer pod only consume a few mount of resources, in an extreme situations, it is possible that the importer pod can't be running due to no resources left on the PV node.

I am wondering if it's possible to add an initContainer into the virt-launcher pod, then the initContainer conduct image pull and import to PVC instead of CDI importer pod ? 

Could you help to provide some comments?  Correct me pls if I am wrong, thanks a lot.

**Describe the solution you'd like**:
Add an initContainer to the virt-launcher pod, then using the initContainer to conduct image pull and import to PVC instead of CDI importer pod.

**Describe alternatives you've considered**:

**Additional context**:

**Comment by mhenriks** [comment]
I think using init containers in this way would introduce a deep coupling between kubevirt and cdi that we've consciously been trying to avoid.  CDI doesn't know anything about VMs.  And how would virt-controller know how to construct the init container?

As mentioned in the referenced issues, we hope to remove/minimize the use of the "temp pod" by leveraging volume populators internally by the datavolume controller or externally by users creating PVCs with dataSourceRefs directly.
