### ISSUE TITLE
Support CRIO container runtime

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#897]
OpenShift will shift to use CRIO by default as it's container runtime.

We should ensure that KubeVirt is working as expected even with CRIO.

**Comment by fabiand** [comment]
@nellyc can we come up with a list of items we need to meet in order to be sure that we have a base level confidence in crio support?

**Comment by nellyc** [comment]
We will run full regression

**Comment by rmohr** [comment]
Can we close this issue? We run all tests against crio too. Or is there something specific which we should do right now in this repo? If not, I would close this one and create more specific issues once something comes up (e.g. like #920).

**Comment by fabiand** [comment]
Yes, closing sounds fine.
