### ISSUE TITLE
set handler param kubelet-pods-dir with operator

### ISSUE THREAD

**Issue by yuntianfeijing** [kubevirt/kubevirt#8998]
**Is your feature request related to a problem? Please describe**:
when my kubelet --root-dir param is not /var/lib/kubelet, i should set param kubelet-pods-dir and volume mount in handler, when i use operator, the handler DaemonSet will be auto update  by operator...

**Describe the solution you'd like**:

**Describe alternatives you've considered**:

**Additional context**:

**Comment by octonawish-akcodes** [comment]
I want to work on this

**Comment by qiutingjun** [comment]
@alicefr i'd like to work on this issue && we have the requirement and testing environment to work on this case.
