### ISSUE TITLE
Cannot reboot VM from inside VM

### ISSUE THREAD

**Issue by naveenbansalntnx** [kubevirt/kubevirt#8999]
**What happened**:
I am unable to reboot VM from inside the VM . It gets stuck at 
```
Starting Reboot...
[  149.275910] reboot: Restarting system
```

**What you expected to happen**:
Reboots successfully

**How to reproduce it (as minimally and precisely as possible)**:
Install a kubernetes cluster using [this](https://kubevirt.io/2019/KubeVirt_k8s_crio_from_scratch_installing_KubeVirt.html).
Also use this command 
```kubectl -n kubevirt patch kubevirt kubevirt --type=merge --patch '{"spec":{"configuration":{"developerConfiguration":{"useEmulation":true}}}}'```
This is same in case of minikube. 

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.58.0
- Kubernetes version (use `kubectl version`): v4.5.7
- VM or VMI specifications: centos VM
- Cloud provider or hardware configuration: Kubernets cluster is on EC2 (c5d.12x large)
- OS (e.g. from /etc/os-release): Amazon Linux 2
- Kernel (e.g. `uname -a`): N/A
- Install tools: kubeadm
- Others: N/A
```
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  creationTimestamp: 2018-07-04T15:03:08Z
  generation: 1
  labels:
    kubevirt.io/os: linux
  name: centos17
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: centos17
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - name: disk0
            disk: {}
          - cdrom:
              bus: sata
              readonly: true
            name: cloudinitdisk 
          interfaces:
          - macAddress:  xx:xx:xx:xx:xx:xx
            bridge: {}
            name: test1
        resources:
          requests:
            memory: 1024M
      networks:
      - name: test1
        pod: {}
      volumes:
      - name: disk0
        persistentVolumeClaim:
          claimName: centos
          claimName: centos
      - cloudInitNoCloud:
          networkData: |
            network:
              version: 1
              config:
                - type: physical
                  name: eth0
                  mac_address: 'xx:xx:xx:xx:xx:xx'
                  subnets:
                    - type: static
                      address: 10.0.150.141
                      netmask: 255.255.255.0
                      routes:
                        - gateway: 10.0.150.1
                          netmask: 0.0.0.0
                          network: 0.0.0.0
                        - gateway: 0.0.0.0
                          netmask: 255.255.255.0
                          network: 10.0.150.0
          userData: |
            #cloud-config
            hostname: centos
            ssh_pwauth: true
            password: footy/4u
            disable_root: true
        name: cloudinitdisk```

**Comment by vasiliy-ul** [comment]
I checked with `examples/vm-cisrros.yaml` and it actually reboots after a delay of ~50sec when emulation is enabled. Does it get completely stuck in your case?

Seems like the same issue: https://github.com/kubevirt/kubevirt/issues/6885

**Comment by naveenbansalntnx** [comment]
Yeah
I tried with centos-image.

**Comment by naveenbansalntnx** [comment]
Update : It's an issue with using emulation , if I use a separate instance which supports nested virtualisation , it works fine .
