### ISSUE TITLE
Implementation for `virtctl guest-agent qemu exec`

### ISSUE THREAD

**Issue by rthallisey** [kubevirt/kubevirt#9030]
https://github.com/kubevirt/community/pull/197

/assign @algor1th

**Comment by algor1th** [comment]
I learned about this issue at kubecon NA22 contribfest and would still like
to contribute

**Comment by rthallisey** [comment]
/remove-lifecycle stale

@algor1th any update on this?

**Comment by algor1th** [comment]
I have been working on this, I will have more time to continue next month. 
Currently I am not sure about how to write tests for the change. I would appreciate some pointers. Are there tests for similar functionality I can take inspiration from? How many tests are expected?

**Comment by rthallisey** [comment]
There's a bunch a test examples around using the guest-agent like https://github.com/kubevirt/kubevirt/blob/main/tests/credentials_test.go#L69.  You can create some similar tests and use virtctl guest-agent-exec to get the same result

**Comment by rthallisey** [comment]
@algor1th how are you progressing?

**Comment by algor1th** [comment]
Unfortunately, I do not have the time to work on it at the moment, or within the next months. I'm still interested and will keep an eye on the issue. Feel free to assign it to someone else though. Sorry.

**Comment by chkpwd** [comment]
/reopen
/remove-lifecycle rotten

Stumbled upon this while working on a similar issue as @rthallisey that required API access for `guest-agent qemu exec`. @algor1th are you able to pick this up again?

If not, I can have a crack at it.
