### ISSUE TITLE
Unexpected mdev removal in v0.59.0-alpha.2

### ISSUE THREAD

**Issue by yeahdongcn** [kubevirt/kubevirt#9037]
**What happened**:
We have an external device plugin for KubeVirt (previously we tested against v0.58.0 and everything works great), the KubeVirt CR configurations are configurated as follows:

```yaml
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
      - HostDevices
      - GPU
    permittedHostDevices:
      mediatedDevices:
      - externalResourceProvider: true
        mdevNameSelector: gpu-1g
        resourceName: domain.com/vgpu-1g
```

But after switching to the latest pre-release ([v0.59.0-alpha.2](https://github.com/kubevirt/kubevirt/releases/tag/v0.59.0-alpha.2)), the mdev instances created by our node provisioner are removed by `virt-handler`. Please see the logs:

```log
{"component":"virt-handler","level":"info","msg":"Successfully removed mdev 2343a48c-7cca-45f1-99ba-f482591dda42","pos":"common.go:168","timestamp":"2023-01-06T09:49:21.491612Z"}
{"component":"virt-handler","level":"warning","msg":"failed to remove mdev type: 2343a48c-7cca-45f1-99ba-f482591dda42","pos":"mediated_devices_types.go:269","timestamp":"2023-01-06T09:49:21.491716Z"}
{"component":"virt-handler","level":"info","msg":"Successfully removed mdev 592334de-1568-4b43-86cf-1f0580fdb559","pos":"common.go:168","timestamp":"2023-01-06T09:49:21.532028Z"}
{"component":"virt-handler","level":"warning","msg":"failed to remove mdev type: 592334de-1568-4b43-86cf-1f0580fdb559","pos":"mediated_devices_types.go:269","timestamp":"2023-01-06T09:49:21.532082Z"}
{"component":"virt-handler","level":"info","msg":"Successfully removed mdev 9e65262d-9b80-4667-be40-a3f79bf8a2b6","pos":"common.go:168","timestamp":"2023-01-06T09:49:21.570059Z"}
{"component":"virt-handler","level":"warning","msg":"failed to remove mdev type: 9e65262d-9b80-4667-be40-a3f79bf8a2b6","pos":"mediated_devices_types.go:269","timestamp":"2023-01-06T09:49:21.570106Z"}
{"component":"virt-handler","level":"info","msg":"Successfully removed mdev e1255b54-f06f-4f2b-91ba-2b261ffeb780","pos":"common.go:168","timestamp":"2023-01-06T09:49:21.600754Z"}
{"component":"virt-handler","level":"warning","msg":"failed to remove mdev type: e1255b54-f06f-4f2b-91ba-2b261ffeb780","pos":"mediated_devices_types.go:269","timestamp":"2023-01-06T09:49:21.600813Z"}
```

**What you expected to happen**:
`virt-handler` should not remove the mdev instances previously created.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.
1. A external device plugin (mdev) is running
2. KubeVirt CR is configurated to use the external device plugin
3. Create mdev instances on a certain node
4. Check the node resources (capacity and allocable), the resource number should not be zero
5. Check `virt-handler` logs, there should be no mdev instance removal logs

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.59.0-alpha.2
- Kubernetes version (use `kubectl version`): v1.23.9
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by jean-edouard** [comment]
@vladikr could you please have a look?

**Comment by jean-edouard** [comment]
@yeahdongcn could you please check if the KubeVirt CR was modified after the upgrade? Are the permitted devices still listed?

**Comment by yeahdongcn** [comment]
> @yeahdongcn could you please check if the KubeVirt CR was modified after the upgrade? Are the permitted devices still listed?

Yes. The above YAML snippet of KubeVirt spec is copied from `❯ kubectl edit kubevirt -n kubevirt`.

**Comment by jean-edouard** [comment]
I just tried to reproduce this, except that I did not use external plugin, for lack of access to the right hardware + plugin combo...
However, the issue did not reproduce, so I suspect this is limited to external plugin use-cases.
I will try to find the right setup to investigate this.

**Comment by yeahdongcn** [comment]
> I just tried to reproduce this, except that I did not use external plugin, for lack of access to the right hardware + plugin combo... However, the issue did not reproduce, so I suspect this is limited to external plugin use-cases. I will try to find the right setup to investigate this.

Thanks for looking into this issue. It looks this PR (https://github.com/kubevirt/kubevirt/pull/8481/) might be suspicious...
