### ISSUE TITLE
virtctl vnc is unhelpful

### ISSUE THREAD

**Issue by pkliczewski** [kubevirt/kubevirt#905]
When i run:

```bash
virtctl vnc <vmname>
```
I get:

> E0412  14:01:50.703176     567 vnc.go:103] exit status 1

I would like to understand why it is not working.

**Comment by pkliczewski** [comment]
I downloaded virtctl from [here](https://github.com/kubevirt/kubevirt/releases/download/v0.4.1/virtctl-v0.4.1-linux-amd64).

**Comment by karmab** [comment]
this seems to be the error reported from remote-viewer

**Comment by davidvossel** [comment]
I can make it more obvious that the string is coming from remote-viewer

**Comment by davidvossel** [comment]
#917 I made the log message more descriptive in order to indicate that the error is coming from remote-viewer.

@pkliczewski Are you still unable to connect to vnc? Do you have any idea why remote-viewer was failing?

**Comment by rmohr** [comment]
> #917 I made the log message more descriptive in order to indicate that the error is coming from remote-viewer.

I think that we should also not swallow stdout/stderr of remote-viewer. Especially if something goes wrong.

**Comment by pkliczewski** [comment]
@davidvossel I downloaded virtctl from [here](url) and run it like this:

> [root@master ~]# ./virtctl vnc win-2016
> E0418 11:26:53.397374   11139 vnc.go:103] exit status 1
> <it do not exit>

**Comment by fromanirh** [comment]
While trying to troubleshoot `virtctl vnc` I run in the same issues, so I added some fix to make it easier to understand what's wrong, and posted them in https://github.com/kubevirt/kubevirt/pull/934

**Comment by fabiand** [comment]
@fromanirh do you think this issue is resolved?

We actually had a person on slack which was affected by insufficient error messages :)

**Comment by fromanirh** [comment]
@fabiand I think so. My PR https://github.com/kubevirt/kubevirt/pull/934 was approved, I think we can set this issue resolved once the PR gets merged.

**Comment by rmohr** [comment]
@fromanirh merged. Can you open a PR on the user-guide and add a few comments to the `virtcl vnc` documentation about debugging?

**Comment by fromanirh** [comment]
@rmohr ack - and thanks for the merge

**Comment by fromanirh** [comment]
@rmohr @fabiand done: https://github.com/kubevirt/user-guide/pull/81
