### ISSUE TITLE
error adding volume, Unable to Add Volume because HotplugVolumes feature gate is not enabled.

### ISSUE THREAD

**Issue by digambar15** [kubevirt/kubevirt#9056]
**Got below error while adding volume to VM**
$ ./virtctl addvolume test-vm --volume-name=storage-dv --persist -n nc-system
error adding volume, Unable to Add Volume because HotplugVolumes feature gate is not enabled

**I also enabled featureGates in kubevirt resource.**
    configuration:
      developerConfiguration:
        featureGates:
        - LiveMigration

**Environment**:
- KubeVirt version (use `virtctl version`): Client Version: GitVersion:"v0.50.0"
- Kubernetes version (use `kubectl version`): GitVersion:"v1.22.2",
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by alicefr** [comment]
@digambar15 I don't quite understand why you label it as a bug. The hotplug feature lives behind the feature gate and the error message clearly tells you that the feature is off. You simply need to add an entry `HotplugVolumes` together with `LiveMigration` , and the it should work
