### ISSUE TITLE
Fail to start vmi with `failed to create ipv4 nat rules for vm error: Couldn't configure ip nat rules`

### ISSUE THREAD

**Issue by dharmit** [kubevirt/kubevirt#9059]
**What happened**:
I used [this quickstart guide](https://kubevirt.io/quickstart_minikube/) to start kubevirt on minikube with kvm2 driver. Trying to start a VM fails. I see following errors in virt-handler pod:
```
{"component":"virt-handler","level":"error","msg":"failed to create ipv4 nat rules for vm error: Couldn't configure ip nat rules","pos":"masquerade.go:146","reason":"Couldn't configure ip nat rules","timestamp":"2023-01-16T10:50:52.305993Z"}
{"component":"virt-handler","level":"error","msg":"failed to prepare pod networking","pos":"podnic.go:230","reason":"Couldn't configure ip nat rules","timestamp":"2023-01-16T10:50:52.306070Z"}
{"component":"virt-handler","kind":"","level":"error","msg":"Synchronizing the VirtualMachineInstance failed.","name":"testvm","namespace":"kubevirt","pos":"vm.go:1781","reason":"failed to configure vmi network: setup failed, err: failed plugging phase1 at nic 'eth0': Critical network error: Couldn't configure ip nat rules","timestamp":"2023-01-16T10:50:52.306217Z","uid":"e9b2eb0d-0e9e-4c85-941d-81692b135bc1"}
```

**What you expected to happen**:
VM to start

**How to reproduce it (as minimally and precisely as possible)**:
On Fedora 37, use the [quickstart guide](https://kubevirt.io/quickstart_minikube/) and ["Use KubeVirt" lab](https://kubevirt.io/labs/kubernetes/lab1.html) to create a VM.

**Additional context**:
virt-handler logs available on [this gist.](https://gist.github.com/dharmit/b96261ab7d1dca3bd796440b1ccfa861)

**Environment**:
- KubeVirt version (use `virtctl version`): v0.58.0
- Kubernetes version (use `kubectl version`): v1.25.3
- VM or VMI specifications: https://kubevirt.io/labs/manifests/vm.yaml
- Cloud provider or hardware configuration: Fedora Workstation
- OS (e.g. from /etc/os-release): Fedora 37
- Kernel (e.g. `uname -a`): 6.0.18-300.fc37.x86_64
- Install tools: N/A
- Others: N/A

**Comment by phoracek** [comment]
Looking at https://github.com/kubevirt/kubevirt/blob/main/pkg/network/infraconfigurators/masquerade.go#L230, it seems that nftables were not detected on the host. That is unexpected, since Fedora 37 (at least on my laptop) has nftables available.

Could you connect into the minikube VM and try running `sudo nft list ruleset`?

**Comment by dharmit** [comment]
> Could you connect into the minikube VM and try running `sudo nft list ruleset`?

I tried it on minikube spun up using both kvm2 and docker providers. Output is similar in both instances:
```sh
$ sudo nft list ruleset
sudo: nft: command not found
```

> since Fedora 37 (at least on my laptop) has nftables available.

Same here, it's available on the Fedora 37 host. I'm starting minikube with a simple `minikube start` command. Am I supposed to start it some other way? I'm wondering how existence of nftables on the Fedora host would make it available on the minikube vm as well, especially if I use kvm2 driver.

**Comment by phoracek** [comment]
I misunderstood - I thought that minikube was using Fedora 37.

I don't know what OS is used by minikube. One way to fix this would be to install nftables there. If it is possible.

**Comment by dharmit** [comment]
Changing the interface type from `masquerade` to `bridge` as pointed out in https://github.com/kubevirt/kubevirt.github.io/issues/859#issuecomment-1284261523 helped start the vm on minikube with kvm2 driver.

It's using the `docker0` bridge of minikube after starting up.
```sh
# inside minikube
$ ip addr show docker0
5: docker0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default
    link/ether 02:42:30:5e:fb:f0 brd ff:ff:ff:ff:ff:ff
    inet 172.17.0.1/16 brd 172.17.255.255 scope global docker0
       valid_lft forever preferred_lft forever
$ logout

# on fedora37 host
% kubectl get vmi
NAME     AGE     PHASE     IP           NODENAME   READY
testvm   2m58s   Running   172.17.0.9   minikube   True
```

/close
