### ISSUE TITLE
Missing search domains in windows vm (Windows does not support DHCP option 119) (not a bug)

### ISSUE THREAD

**Issue by karmab** [kubevirt/kubevirt#906]
when i deploy a windows vm, i note that my network config misses search domains (checking with ipconfig /all).
this is present on linux boxes on the same cluster.

**Comment by mlsorensen** [comment]
Are we sure windows DHCP client supports option 119?

**Comment by fabiand** [comment]
> In short, there is no way to assign a DNS suffix search list to a Windows client using DHCP.
> A DNS suffix search list can be assigned to domain-joined Windows machines via Group Policy by following the procedure in Configure the DNS Suffix Search List for a Disjoint Namespace.

Source: http://www.dell.com/support/article/de/de/debsdt1/sln291195/unable-to-configure-dns-suffix-search-list-via-dhcp?lang=en

Hum.

- Documentation for this
- Manual workaround
- Implementing Group Policies in KubeVirt - I think this is to stretched :)

**Comment by fabiand** [comment]
Summarizing the impact again:

- Windows guests are not able to lookup _cluster_ service (and other entities with a DNS entry) by their "short name" i.e. `myservice`. Instead they need to use the full fqdn: `myservice.default.svc.cluster` (IIRC)
- DNS resolution of the broader internet is not affected

**Comment by fabiand** [comment]
Side note - this problem is not specific to kubevirt, it applies to any windows guest.
Although it might affect guests on kubevirt more, as kubernetes is using DNS records extensively for service discovery.

**Comment by fabiand** [comment]
@karmab you can not resolve any service name into an ip?

**Comment by fabiand** [comment]
@duyanyan are you able to reproduce the issue @karmab is encountering?

**Comment by rmohr** [comment]
Are we sending option 015 right now? If we send e.g. svc.local there,  it should be picket up and fqdn should work for k8s services.

**Comment by vladikr** [comment]
> Are we sending option 015 right now?

Nope, we are sending a list via option 119 (RFC 3397) and it looks like windows doesn't support it at all...
However, I think option 015 is only intended to be a single domain name

**Comment by duyanyan** [comment]
Yes, I could reproduce it. when I check the vms, seems there are no search domain in both windows and cirros vm:
```
# ssh cirros@172.30.234.1
cirros@172.30.234.1's password: 
$ cat /etc/resolv.conf 
nameserver 172.30.0.1
$ ping http
ping: bad address 'http'
```
But exist inside a normal pod at the same cluster
```
# oc rsh hello-pod
/ # cat /etc/resolv.conf 
nameserver 172.30.0.1
search myproject.svc.cluster.local svc.cluster.local cluster.local nay.redhat.com redhat.com
options ndots:5
/ # ping http
PING http.myproject.svc.cluster.local (172.30.189.82) 56(84) bytes of data.
```

**Comment by mlsorensen** [comment]
Search domains work here on 0.4.0, with Cirros and Fedora images. First step might be to debug the dhcp client and what it’s getting. I have a tcpdump around here somewhere that will show the data as well...

**Comment by fabiand** [comment]
As stated higher above - Windows does not support option 119 (given in the dell source).

**Comment by fabiand** [comment]
@duyanyan Can you please check if DNS resolution of cluster services is working on windows at all 

My goal is to get an overview of what is working and what not today, in today#s state.

Please test:

1. Create a pod with nginx
2. Create a `mysvc` service for this pod
3. create another pod `testpod`
4. create a vm `testvm`
---
5. Test: Ping google.com from `testpod`
6. Test: Ping mysvc from `testpod`
7. Test: Ping mysvc.default.svc cluster.local from `testpod`
---
8. Test: Ping google.com from `testvm`
9. Test: Ping mysvc from `testvm`
10. Test: Ping mysvc.default from `testvm`
11. Test: Ping mysvc.default.svc from `testvm`
12. Test: Ping mysvc.default.svc.cluster from `testvm`
13. Test: Ping mysvc.default.svc cluster.local from `testvm`

**Comment by duyanyan** [comment]
Sorry for late reply @fabiand 
```
[root@dhcp-140-70 images]# oc get pod
NAME                                READY     STATUS    RESTARTS   AGE
hello-pod                           1/1       Running   0          25m
nginx                               1/1       Running   0          30m
virt-launcher-windows2012r2-4b9rx   1/1       Running   0          2d
# oc get svc
NAME      TYPE        CLUSTER-IP       EXTERNAL-IP   PORT(S)          AGE
mysvc     ClusterIP   172.30.74.193    <none>        22/TCP           16m
```
For  ```testpod```
```
/ # ping google.com
PING google.com (74.125.24.101) 56(84) bytes of data.
64 bytes from 74.125.24.101 (74.125.24.101): icmp_seq=1 ttl=37 time=75.6 ms
64 bytes from 74.125.24.101 (74.125.24.101): icmp_seq=2 ttl=37 time=75.6 ms
^C64 bytes from 74.125.24.101: icmp_seq=3 ttl=37 time=75.7 ms

--- google.com ping statistics ---
3 packets transmitted, 3 received, 0% packet loss, time 4305ms
rtt min/avg/max/mdev = 75.630/75.687/75.776/0.233 ms
/ # ping svc
^C
/ # ping mysvc
PING mysvc.myproject.svc.cluster.local (172.30.74.193) 56(84) bytes of data.
^C
--- mysvc.myproject.svc.cluster.local ping statistics ---
8 packets transmitted, 0 received, 100% packet loss, time 7192ms

/ # ping mysvc.myproject.svc.cluster.local
PING mysvc.myproject.svc.cluster.local (172.30.74.193) 56(84) bytes of data.
^C
--- mysvc.myproject.svc.cluster.local ping statistics ---
2 packets transmitted, 0 received, 100% packet loss, time 1026ms

```

For  ```windowsvm```
```
C:\Users\Administrator>ping google.com
Pinging google.com [74.125.24.102] with 32 bytes of data:
Reply from 74.125.24.102: bytes=32 time=75ms TTL=37
Reply from 74.125.24.102: bytes=32 time=76ms TTL=37
Reply from 74.125.24.102: bytes=32 time=76ms TTL=37
Reply from 74.125.24.102: bytes=32 time=76ms TTL=37

Ping statistics for 74.125.24.102:
    Packets: Sent = 4, Received = 4, Lost = 0 (0% loss),
Approximate round trip times in milli-seconds:
    Minimum = 75ms, Maximum = 76ms, Average = 75ms

C:\Users\Administrator>ping mysvc
Ping request could not find host mysvc. Please check the name and try again.
C:\Users\Administrator>ping mysvc.myproject
Ping request could not find host mysvc.myproject. Please check the name and try again.
C:\Users\Administrator>ping mysvc.myproject.svc
Ping request could not find host mysvc.myproject.svc. Please check the name and try again.
C:\Users\Administrator>ping mysvc.myproject.svc.cluster
Ping request could not find host mysvc.myproject.svc.cluster. Please check the name and try again.
C:\Users\Administrator>ping mysvc.myproject.svc.cluster.local
Pinging mysvc.myproject.svc.cluster.local [172.30.74.193] with 32 bytes of data:
Request timed out.
Request timed out.
Request timed out.
Request timed out.

Ping statistics for 172.30.74.193:
    Packets: Sent = 4, Received = 0, Lost = 4 (100% loss),
```

**Comment by karmab** [comment]
here s a screenshot of windows network configuration.
the dnserver listed is the node the vm is running on.
![image](https://user-images.githubusercontent.com/1840387/38796579-1f4d4c38-415c-11e8-9981-e2f77625a5a5.png)

for a fedora vm, the resolv.conf goes like this

```
search summit-demo.svc.cluster.local. svc.cluster.local. cluster.local. cloud.lab.eng.bos.redhat.com.
nameserver 10.19.139.32
```

**Comment by rmohr** [comment]
> C:\Users\Administrator>ping mysvc.myproject.svc.cluster.local
> Pinging mysvc.myproject.svc.cluster.local [172.30.74.193] with 32 bytes of data:

That looks like pinging the fqdn seems to work, perfect. So what we can do now is adding 015, then you could reach your service with two names:

 * mysvc.myproject.svc.cluster.local (fqdn)
 * mysvc.myproject.svc (without cluster-wide suffix)

@karmab it seems like I misunderstood the issue impact. I was under the impression that not even fqdns worked. It definitely makes sense to add the cluster-wide suffix via the 015 option (especially if we want to support multiple nics in different domains), but I think that is all we can do without going too deep into windows domain controllers.

**Comment by fabiand** [comment]
@rmohr For consistency I'd not use option 15, but rather ask windows users to use the full fqdn. 
@karmab As @rmohr mentiones, the DNS lookup works, just the ICMP/ping does not. This can actually be, as the SVC is getting  a cluster ip, which is effectively just an itpables rule to listen for a certain ip and a certain port. The only way to test this is to connect to the port of the service.

**Comment by fabiand** [comment]
A few things:

- DNS lookup works on Windows if the full FQDN is used, see comment https://github.com/kubevirt/kubevirt/issues/906#issuecomment-381462754
- ping to a service from a windows vm does not work also see https://github.com/kubevirt/kubevirt/issues/906#issuecomment-381462754
- DHCP option 15 could be used to add a suffix, but it would not completely resolve the problem

**Comment by rmohr** [comment]
> @rmohr For consistency I'd not use option 15, but rather ask windows users to use the full fqdn.

I think that especially for consistency we should support it. Since the suffix can vary between clusters, it is essential that I can prepare my vms in a cluster-independent way. It is not a complete deal breaker since I can still use cloud-init or ansible to inject a fqdn but still ...

**Comment by rmohr** [comment]
> @karmab As @rmohr mentiones, the DNS lookup works, just the ICMP/ping does not. This can actually be, as the SVC is getting a cluster ip, which is effectively just an itpables rule to listen for a certain ip and a certain port. The only way to test this is to connect to the port of the service.

Indeed it goes to the service and not to the vm. ICMP will not work there. Just explicitly opened tcp/udp ports on the service.

**Comment by fabiand** [comment]
Before the automation closes this, I'm going to close this :)

The previous comment mentions workarounds. There is nothing more be can do in an elegant fashion.
