### ISSUE TITLE
Introduce lock for kubevirtconfiguration callbacks

### ISSUE THREAD

**Issue by xpivarc** [kubevirt/kubevirt#9061]
**Is your feature request related to a problem? Please describe**:

**Describe the solution you'd like**:
See https://github.com/kubevirt/kubevirt/pull/9048#discussion_r1071300845

**Describe alternatives you've considered**:

**Additional context**:

**Comment by kgurazad** [comment]
hi there, i'd like to contribute to this issue as part of a class project at ut austin—would that be alright @xpivarc? thanks!

**Comment by xpivarc** [comment]
/assign @kgurazad 
All good, I am happy to review the PR.
