### ISSUE TITLE
Question: could Kubevirt add pod in Hostnetwork mode, and send virt CNI request for some special CNI?

### ISSUE THREAD

**Issue by lut777** [kubevirt/kubevirt#9065]
**Is your feature request related to a problem? Please describe**:
Tried to find but failed to find relative issue.

Networking in pod `virt-launcher` is pretty complicated including DHCP and bridge. It's not so efficient. Besides, networking should not be a part of Kubevirt which focuses in introducing KVM.

**Describe the solution you'd like**:

This solution is limited for the CNI which could handle rx/tx packets and DCHP server for KVM (e.g., ovs-based CNI, Cilium, and so on)
How about config `virt-launcher` pod as Hostnetworking? 
1. pod `virt-launcher` is deployed as Hostnetwork, and tapXXXX Is added in host node net ns.  
2. virt-controller sends a specific CNI request to CNI server in each Node.
3. CNI should bring tapXXXX under its control, e.g.,
    handle the data stream. Data stream from/to tapXXXX could be send to desired destination.
    let DHCP server answers request, so that KVM could get desired IP.
   ARP is respond by CNI.
4. virt-controller receive respond from CNI and ensure KVM is prepared (or not)

This solution could leave networking to CNI. 
While with host networking, net performance could be obviously better. 

**Describe alternatives you've considered**:

1. virt-launcher could be optionally deployed as hostnetworking, which is simple.
2. For the option above, virt-controller should have a processes like:  
    send a request to each node's CNI server that is compatible with the current CNI specification, but customized for Kube-virt.
    determine if the KVM is successfully established based on the response.

**Additional context**:
No.

**Comment by maiqueb** [comment]
We're thinking on a way to offset all the code from the kubevirt bindings to CNI ...

This will enable the broader community to innovate / experiment without requiring the KubeVirt maintainers to maintain that code.

I think your proposal could benefit from this.

Finally, would [macvtap-cni](https://github.com/kubevirt/macvtap-cni/) fit your needs ? Pod networking becomes a lot simpler with it. There's [this proposal](https://github.com/kubevirt/community/pull/186) to make macvtap a possibility for the pod network; iirc, this was also waiting for a way for us to offset the VM interface binding code from KubeVirt into CNI plugins.

**Comment by lut777** [comment]
Happy Chinese new year.
Macvtap is a good way, but the veth pair still has a performance penalty. I'm also not sure if DHCP server should be managed under kubevirt...
Is there an interesting group or something like that about this procedure offset from kubevirt into CNI? I'm curious about the ideas that are out there now

**Comment by xpivarc** [comment]
There is no special meeting for network SIG but you can join our weekly community meeting and raise the question there. Folks from network SIG are almost always present. [Calendar and other useful links](https://github.com/kubevirt/community)

**Comment by maiqueb** [comment]
> Happy Chinese new year. Macvtap is a good way, but the veth pair still has a performance penalty. I'm also not sure if DHCP server should be managed under kubevirt... Is there an interesting group or something like that about this procedure offset from kubevirt into CNI? I'm curious about the ideas that are out there now

Macvtap-cni does not invoke an IPAM plugin at all - thus, you won't have the DHCP server managed by kubevirt. 

You get an L2 connection to a physical network, and if there's a DHCP server there, you'll get an IP from it.

**Comment by lut777** [comment]
> > Happy Chinese new year. Macvtap is a good way, but the veth pair still has a performance penalty. I'm also not sure if DHCP server should be managed under kubevirt... Is there an interesting group or something like that about this procedure offset from kubevirt into CNI? I'm curious about the ideas that are out there now
> 
> Macvtap-cni does not invoke an IPAM plugin at all - thus, you won't have the DHCP server managed by kubevirt.
> 
> You get an L2 connection to a physical network, and if there's a DHCP server there, you'll get an IP from it.

Thank you for the explanation. I get it.

**Comment by kvaps** [comment]
Hey take a look on [this proposal](https://github.com/kubevirt/community/pull/186) I was solving the same performance issue you experienced with.

By connecting macvtap interface on veth, it makes handler to capture all the packets for specific MAC. It has almost the native veth prfomance but allows to connect VM to it.
