### ISSUE TITLE
Use network hotplug in virt-handler for dedicated migration networks

### ISSUE THREAD

**Issue by jean-edouard** [kubevirt/kubevirt#9075]
**Is your feature request related to a problem? Please describe**:
A dedicated migration network can be set in the KubeVirt CR, see [documentation](https://kubevirt.io/user-guide/operations/live_migration/#using-a-different-network-for-migrations).
Since the feature was implemented prior to multus hotplug support, changing the dedicated migration network triggers a restart of all virt-handlers.

**Describe the solution you'd like**:
As of CNAO v0.82.0, to which every test lane has been updated, network hotplug is now fully supported.
We should leverage that to avoid restarting all virt-handlers every time the dedicated migration network is changed.

**Describe alternatives you've considered**:
The way it is today works fine, it's just not ideal anymore.

**Additional context**:
This was discussed in https://github.com/kubevirt/kubevirt/pull/6852, which implements hotplug support for VMIs.

**Comment by maiqueb** [comment]
We're now shipping via CNAO both a version of multus deployed using thick-plugin, and a [controller](https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller) to reconcile the attachments on a pod.

IIUC, we just need to patch the `networks` annotations of the virt-handler pods to use the "new" network, and forget about the "old" network.

This would definitely be an improvement !
