### ISSUE TITLE
Improve website footer

### ISSUE THREAD

**Issue by Jainex17** [kubevirt/kubevirt#9088]
**Is your feature request related to a problem? Please describe**:
Footer looks so simple

**Describe the solution you'd like**:
Improve footer UI/UX

**Describe alternatives you've considered**:
If not want to change full footer we can change background color to navbar background color and footer text color white and logo text make white

**Additional context**:
![image](https://user-images.githubusercontent.com/81921291/214242385-53cf3760-02fa-44d9-8169-6baedadb2dc1.png)

**Comment by dhruvsethi227** [comment]
Hello, my name is Dhruv and I am a senior computer science student at UT Austin. My group and I were wondering if we could tackle this issue as part of our class assignment.

**Comment by xpivarc** [comment]
/assign @dhruvsethi227 
Feel free to work on this.
