### ISSUE TITLE
Missing resources in kubectl get/describe --help

### ISSUE THREAD

**Issue by alexxa** [kubevirt/kubevirt#909]
1) `kubectl get --help` doesn't list `vms, vmrs and ovms` as resources. 
2) `vms, vmrs, and ovms` are not listed in `kubectl describe --help` too.

I'm not familiar with KubeVirt and kubectl that much yet to say if anth else is missing, but I would appreciate it if `--help` was useful and complete.

**Comment by fabiand** [comment]
Closing this, as there is nothing we can do from the kubevirt side.
