### ISSUE TITLE
virt-operator unable to start due to multiple kubevirt custom resource detected

### ISSUE THREAD

**Issue by abdulari** [kubevirt/kubevirt#9098]
**What happened**:
kubectl virt unable to start/stop VM due to virt-operator error (More than one KubeVirt custom resource detected: 3)
user unable to delete kubevirt CRD in default namespace due to "TLS bad certificate" error

**What you expected to happen**:
virt-operator CRD monitoring happened on kubevirt namespace.
or, kubevirt CRD should only be applied to kubevirt namespace
Prometheus integration documentation should be fixed

**How to reproduce it (as minimally and precisely as possible)**:
apply kubevirt integration with prometheus-operator's example yaml.
notice that the namespace:kubevirt is missing. so it's deployed to default namespace.
https://kubevirt.io/user-guide/operations/component_monitoring/#integrating-with-the-prometheus-operator

**Additional context**:
n/a

**Environment**:
- KubeVirt version (use `virtctl version`): v0.52.0
- Kubernetes version (use `kubectl version`): v1.21.11+k3s1
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: self hosted. following kubevirt cloud provider config
- OS (e.g. from /etc/os-release): ubuntu 20.04
- Kernel (e.g. `uname -a`): 5.15.0-58-generic
- Install tools: k3s, multus
- Others: N/A

**Comment by usrbinkat** [comment]
I see you are running kubevirt version v0.52.0, can you share what version of Kubernetes you are running please?

**Comment by abdulari** [comment]
definitely. sorry, I guess i've missed it.
updating the original post.
