### ISSUE TITLE
Improve virt-handler when the vsock feature gate is enabled but no vsock device is available

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#9114]
**What happened**:

If the vsock feature gate is enabled, virt-handler will blindly try to start a vsock-grpc server. If the vsock device is not there it will periodically spam the logs that it could not start the service.

**What you expected to happen**:

Like the virt-handler device plugins it should only try to start the service if the vsock device is present and watch for it to appear.

**How to reproduce it (as minimally and precisely as possible)**:
Enable the vsock feature gate and ensure that vsock is not supported on a host. The virt-handler logs will be spammed with start retries.

**Additional context**:

Follow up of https://github.com/kubevirt/kubevirt/pull/9087#discussion_r1085760411

**Comment by shashankiswara0** [comment]
Hi, I'm a student at UT Austin and would like to work on this issue for my Virtualization course project. Could I be assigned to this issue?

**Comment by rmohr** [comment]
@shashankiswara0 happy if you take it :)
