### ISSUE TITLE
'make cluster-up' fails on mac

### ISSUE THREAD

**Issue by nellyc** [kubevirt/kubevirt#913]
make cluster-up failed with error on mac
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "process_linux.go:86: executing setns process caused \"exit status 21\"": unknown

Docker Version 18.03.0-ce-mac60 (23751)

more specifically this is the point of failure:
docker run --privileged --rm -v /var/run/docker.sock:/var/run/docker.sock kubevirtci/cli@sha256:b0023d1863338ef04fa0b8a8ee5956ae08616200d89ffd2e230668ea3deeaff4 run --reverse --nodes 1 --random-ports --background --prefix os-3.9.0-alpha.4 --registry-volume kubevirt_registry --base kubevirtci/os-3.9@sha256:c214267c1252e51f5ea845ac7868dbc219c63627e9f96ec30cc0a8e9e6e9fc0d
os-3.9.0-alpha.4-node01
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "process_linux.go:86: executing setns process caused \"exit status 21\"": unknown
5fdd4a296738818ab1bede54ab714ccf33c249995fadf4b9a8d6fc851348614b
5fdd4a296738818ab1bede54ab714ccf33c249995fadf4b9a8d6fc851348614b
73d33961853ad11b67597f3c94ba958a95c49bd01e3294a235258a5eaca269dd
73d33961853ad11b67597f3c94ba958a95c49bd01e3294a235258a5eaca269dd
4d02a709b78fe2d62428fb6c2f690fc2be3ca81b02e25fe8d13efeb8fe263d08
4d02a709b78fe2d62428fb6c2f690fc2be3ca81b02e25fe8d13efeb8fe263d08
os-3.9.0-alpha.4-node01

**Comment by rmohr** [comment]
@mpolednik if I remember correctly, you have a mac. Could you try to find out why 

```bash
PROVIDER=os-3.9.0-alpha.4
make cluster-up
```

fails on mac?

**Comment by gageorsburn** [comment]
It looks like it resides within the ci container at kubevirt/kubevirtci. I'm looking more into how that container works. I think it has something to do with being unable to create /dev/kvm instead container when it's on OSX but not entire sure yet. Will update when I discover more.

**Comment by gageorsburn** [comment]
/proc/misc on containers on OSX do not have an entry for kvm while containers on linux do. So I'm pretty sure this stems from the KVM dependency that OSX does not support.

**Comment by rmohr** [comment]
@gageorsburn the /dev/kvm related logic is here: https://github.com/kubevirt/kubevirtci/blob/master/base/scripts/vm.sh#L80.

Is intel haxm supported on mac? That might be a suitable alternative.

**Comment by gageorsburn** [comment]
@rmohr Yeah I had found that when I looked into it and determined that to be the root cause. I was not able to get Intel haxm working with qemu. 

I did come across https://github.com/geohot/kvm-kext but did not test it out.  Another thing that could be done is to look into OSX's hypervisor.framework, but I don't know how much value it will add, or we probably could just do without hardware acceleration for OSX.

**Comment by gaahrdner** [comment]
I just ran into this as well:

```
++ local 'params=--nodes 1 --memory 5120M --cpu 5 --random-ports --background --prefix k8s-1.10.4 --registry-volume kubevirt_registry kubevirtci/k8s-1.10.4@sha256:b60a61ca03a1a6c504481020709a04f65e4dd9c929a8bcad18821c5f80d1b2b6  --ocp-port 8443'
++ [[ '' =~ windows.* ]]
++ [[ '' =~ openshift.* ]]
++ echo --nodes 1 --memory 5120M --cpu 5 --random-ports --background --prefix k8s-1.10.4 --registry-volume kubevirt_registry kubevirtci/k8s-1.10.4@sha256:b60a61ca03a1a6c504481020709a04f65e4dd9c929a8bcad18821c5f80d1b2b6 --ocp-port 8443
+ docker run --privileged --net=host --rm -v /var/run/docker.sock:/var/run/docker.sock kubevirtci/gocli@sha256:df958c060ca8d90701a1b592400b33852029979ad6d5c1d9b79683033704b690 run --nodes 1 --memory 5120M --cpu 5 --random-ports --background --prefix k8s-1.10.4 --registry-volume kubevirt_registry kubevirtci/k8s-1.10.4@sha256:b60a61ca03a1a6c504481020709a04f65e4dd9c929a8bcad18821c5f80d1b2b6 --ocp-port 8443
Downloading ......
Downloading ......
OCI runtime exec failed: exec failed: container_linux.go:348: starting container process caused "process_linux.go:86: executing setns process caused \"exit status 21\"": unknown
OCI runtime exec failed: exec failed: cannot exec a container that has stopped: unknown
provisioning node node01 failed
make: *** [cluster-up] Error 1
```

**Comment by gageorsburn** [comment]
@gaahrdner Yup it's because there is no KVM support on OSX. The best workaround is to use the external provider to use an external kubernetes cluster.
