### ISSUE TITLE
testvm cannot be started

### ISSUE THREAD

**Issue by zulan88** [kubevirt/kubevirt#9146]
pod error log is
{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:86","timestamp":"2023-02-02T00:46:44.774258Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:89","timestamp":"2023-02-02T00:46:44.774374Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:497","timestamp":"2023-02-02T00:46:44.776202Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory')","pos":"libvirt.go:505","timestamp":"2023-02-02T00:46:44.776982Z"}
{"component":"virt-launcher","level":"error","msg":"failed to start virtqemud","pos":"libvirt_helper.go:277","reason":"fork/exec /usr/sbin/virtqemud: errno 0","timestamp":"2023-02-02T00:46:44.777499Z"}
panic: fork/exec /usr/sbin/virtqemud: errno 0

goroutine 73 [running]:
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/util.LibvirtWrapper.StartVirtquemud.func1()
	pkg/virt-launcher/virtwrap/util/libvirt_helper.go:278 +0x4ce
created by kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/util.LibvirtWrapper.StartVirtquemud
	pkg/virt-launcher/virtwrap/util/libvirt_helper.go:245 +0x65
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 12 with status 512","pos":"virt-launcher-monitor.go:124","timestamp":"2023-02-02T00:46:44.783167Z"}
{"component":"virt-launcher-monitor","level":"error","msg":"dirty virt-launcher shutdown: exit-code 2","pos":"virt-launcher-monitor.go:142","timestamp":"2023-02-02T00:46:44.783370Z"}

kubernetes: 1.23.8
os: centos7.9

**Comment by zulan88** [comment]
libvirtd is active

**Comment by zhhray** [comment]
@zulan88 hello，I also met the same problem as you. How did you solve it later?

**Comment by Gohoy** [comment]
i met the same problem 'dirty virt-launcher shutdown: exit-code 2'. Have you solve it?

**Comment by xpivarc** [comment]
@zhhray Do you use docker by any chance? Please open a new issue if the problem persist.

**Comment by 66545shiwo** [comment]
@zhhray me too,  did you solve it ?

**Comment by zhhray** [comment]
> @zhhray me too, did you solve it ?

@66545shiwo 
The runc version of your host is probably too low. Try upgrading it.

**Comment by 66545shiwo** [comment]
I found the solution：
Updata Cgroup Version from `v2` to `v1`. 
Check your Cgroup Version
---
```
# docker info | grep Cgroup
 Cgroup Driver: systemd
 Cgroup Version: 1
```
