### ISSUE TITLE
Should virt-launcher pod make sure that no presets are applied to it?

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#915]
We could add

```
podpreset.admission.kubernetes.io/exclude: "true"
```
to our virt-launcher pods. However, is it necessary?

**Comment by fabiand** [comment]
I wonder what kube does about their system critical pods.

**Comment by rmohr** [comment]
Hm, closing this: At least my thoughts are this: If one creates a preset which matches every pod (e.g. to create a log volume, ...) then it needs to be agnostic to the rest of the pod configuration in general. That seems to also align with the system pods, provided via daemon set in general too, since there is also no annotation.
