### ISSUE TITLE
Extend VM disk size on hostpath-provisioner CSI.

### ISSUE THREAD

**Issue by qkfrksvl** [kubevirt/kubevirt#9154]
Without distribute storage, the only option is that local storage such as local-path provisioner, host-path provisioner.
I have two question regarding these provisioner.

First,  is there any method to extend VM disk on hostpath-csi driver? it shows that increasing PVC size is only available with dynamic pvc when I tried. and also all of the PVC show the whole size of node disk. 

Second, is there any method to select the specific node with local-path provisioner when provisioning VM? 
the problem is that CDI pod was creating on wrong host.

**Comment by feitnomore** [comment]
Let me try to help you.  

1. Volume Expansion
To solve this, you should set the following on your `StorageClass`:
```
allowVolumeExpansion: true
```

You should also set the featuregate on your `Kubevirt` descriptor:
```
  configuration:
    developerConfiguration:
      featureGates:
      - ExpandDisks
```

2. Volume Provisioning
To solve this, you should set `HonorWaitForFirstConsumer` on your `CDI` descriptor:
```
  config:
    featureGates:
    - HonorWaitForFirstConsumer
```

You should also set the following on your `StorageClass`:
```
volumeBindingMode: WaitForFirstConsumer
```

Hope it helps.
