### ISSUE TITLE
Known Issue: Istio does not work on CentOS 9

### ISSUE THREAD

**Issue by phoracek** [kubevirt/kubevirt#9158]
**What happened**:

Due to https://github.com/istio/istio/issues/42485 Istio does not work on CentOS 9. The suspected cause of this issue is Istio's incompatibility with SELinux and nftables in the OS.

This problem prevents us from moving all of our testing to CentOS 9.

As a temporary workaround, sig-network tests were disabled on Kubernetes 1.26. We keep testing it on the older Kubernetes lanes.

**What you expected to happen**:

Once the Istio issue is resolved, https://github.com/kubevirt/project-infra/pull/2592 and https://github.com/kubevirt/kubevirt/pull/9157 should be reverted.

**Comment by EdDev** [comment]
We need to confirm if it is resolved or not with (latest) CentOS Stream 9.
For now, I think we are waiting for Istio releasing 1.18 (which is now a RC).

/remove-lifecycle stale
/sig network

**Comment by EdDev** [comment]
This issue should be resolved already.
We are currently skipping the Istio tests for one job, so I sent a PR to re-enable it: https://github.com/kubevirt/project-infra/pull/2863

There is still a need to confirm it indeed works (as we may also need to bump Istio itself).

**Comment by EdDev** [comment]
Istio tests on kubevirt/kubevirt are now running again on all supported lanes.

/close
