### ISSUE TITLE
Allow building outside of git repo

### ISSUE THREAD

**Issue by ben-skyportsystems** [kubevirt/kubevirt#918]
If I download a source tarball and try to build it, I quickly run up against this:
```
++ basename cmd/virt-controller
+ BIN_NAME=virt-controller
++ git describe --always --tags
fatal: Not a git repository (or any parent up to mount point /)
Stopping at filesystem boundary (GIT_DISCOVERY_ACROSS_FILESYSTEM not set).
+ ARCH_BASENAME=virt-controller-
+ finish
+ docker stop 247a6a54a4574e6be672e1d1312aa76b07bd38df4dfda3a9c5590dffe1025a8f
247a6a54a4574e6be672e1d1312aa76b07bd38df4dfda3a9c5590dffe1025a8f
+ docker rm -f 247a6a54a4574e6be672e1d1312aa76b07bd38df4dfda3a9c5590dffe1025a8f
247a6a54a4574e6be672e1d1312aa76b07bd38df4dfda3a9c5590dffe1025a8f
Makefile:15: recipe for target 'build' failed
make: *** [build] Error 128
```
This is from running **bash -x hack/buiild_go.sh**

As you can see, the script tries to derive the current version from a git tag, but if this isn't in a git repo in the first place, no such thing exists.  Relying on git tags for version information is shaky at best.  I'm not sure of the best way to approach this.  Old-school projects would make version info part of the autoconf info, or have a VERSION file or something like that, but maybe there's a more modern approach that I don't know about.

I'm happy to take this on if the project maintainers show a preference.

**Comment by rmohr** [comment]
> If I download a source tarball and try to build it, I quickly run up against this:

If you can't build from git, we can for sure help you to make the project compile from a tarball.

> Relying on git tags for version information is shaky at best.

I don't see why manually updated version infos should be more accurate. Normally people then have 500 different tarballs from 500 different commits which all show the same build version.

> Old-school projects would make version info part of the autoconf info, or have a VERSION file or something like that, but maybe there's a more modern approach that I don't know about.

Building from your version control is the modern approach. It is normally only problematic if you try to build packages via the official channels for e.g. fedora/centos/debian/..., which still insist on tarballs.

> I'm happy to take this on if the project maintainers show a preference.

 We can for instance check if we are inside a git repo. If not, fall back to an environment variable.

**Comment by rmohr** [comment]
>> I'm happy to take this on if the project maintainers show a preference.
> 
> We can for instance check if we are inside a git repo. If not, fall back to an environment variable.

Just falling back to "unknown" would also work for me.
