### ISSUE TITLE
Track VMI LastState in VirtualMachineStatus

### ISSUE THREAD

**Issue by lxs137** [kubevirt/kubevirt#9185]
**Is your feature request related to a problem? Please describe**:
VM has been crashed sometime. I want to figure out crash reason. 

**Describe the solution you'd like**:
Add new field **VMILastState** in VirtualMachineStatus, which similar to [LastState](https://kubernetes.io/docs/reference/generated/kubernetes-api/v1.26/#containerstate-v1-core) in PodStatus.

**Describe alternatives you've considered**:
WIP

**Additional context**:
WIP

**Comment by CSWYF3634076** [comment]
Hi, I am interested in this issue. If no one is assigned, can I be assigned

**Comment by alicefr** [comment]
@CSWYF3634076 feel free to take it. I'll assign to you

**Comment by sudo-NithishKarthik** [comment]
Is this being worked on? If not, shall I be assigned to this issue?

**Comment by CSWYF3634076** [comment]
> Is this being worked on? If not, shall I be assigned to this issue?

I am currently working on this issue

**Comment by CSWYF3634076** [comment]
> is this issue solved? can i work on this?

Not yet resolved, approximately 50% complete. My current solution is modeled after ContainerState

**Comment by xpivarc** [comment]
/open
Hey @lxs137 , what would we track here? Did you observe anything that would be valuable?

**Comment by lxs137** [comment]
@xpivarc 
Looks like @CSWYF3634076 is doing some work on this. 

Actually I have implement this feature in our internal fork, base on v0.50.0. But I am afraid I don't have too much time to port our internal work.

**Comment by lxs137** [comment]
@xpivarc 
Looks like @CSWYF3634076 is doing some work on this. 

Actually I have implement this feature in our internal fork, base on v0.50.0. But I am afraid I don't have too much time to port our internal work.
