### ISSUE TITLE
[enhancement] add dependency modification checks to makefile

### ISSUE THREAD

**Issue by yuvalif** [kubevirt/kubevirt#924]
otherwise, it misses the point of a makefile :-)
some examples:
- no need to execute `make build` if no source file was changed
- if cluster is up, don't try to bring it up again

**Comment by rmohr** [comment]
Great that you opened that. We only use make as a well-known entry-point.

> no need to execute make build if no source file was changed

We let golang decide what parts it needs to rebuild. In general we let go and docker do the optimizations.

> if cluster is up, don't try to bring it up again

Here you have a point. What it does right now, is trying to bring it up and fails immediately. Here we may want to simply not throw errors and continue.

**Comment by rmohr** [comment]
> the issue with make build is that the makefile (or script called from inside it) spawns the docker container, even if code was not modified.
> For example, on my machine it took 1:40 minutes to run make with no code changes

Could you try to update your build container to go 1.10 and report? Afaik caching should work much better there.

**Comment by rmohr** [comment]
Here is the file: https://github.com/kubevirt/kubevirt/blob/master/hack/docker-builder/Dockerfile

On the first build after a change there, it will rebuild the container, so the second invocation will be interesting.
