### ISSUE TITLE
MAC spoof filtering CNI is not working on CentOS 9

### ISSUE THREAD

**Issue by phoracek** [kubevirt/kubevirt#9245]
**What happened**:

The `VirtualMachineInstance using different types of interfaces. Security Should allow outbound communication from VM under test - only if original MAC address is unchanged expand_less` test is failing on CentOS 9. A VM using the MAC spoof filtering CNI fails to get pass the CNI stage, failing on `Error: Could not open file \"/tmp/spoofcheck-2771073163\": Permission denied\n\n\n'\n'"`.

**What you expected to happen**:
The issue should be addressed on the CNI.

**How to reproduce it (as minimally and precisely as possible)**:
Run the test mentioned above on CentOS 9.

**Additional context**:
The test should be temporarily disabled to allow us to test with CentOS 9. The bug is in the CNI, so we are not ignoring an issue with a core functionality of KubeVirt.

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by EdDev** [comment]
We need to confirm if it is resolved or not with (latest) CentOS Stream 9.
I have seen that Istio attempted to solve the same issue by using stdin instead of a temp file, something I did not see working in the past. I guess we should check again.

Ref: https://github.com/networkplumbing/go-nft/pull/51

/remove-lifecycle stale
/sig network
/assign

**Comment by EdDev** [comment]
> We need to confirm if it is resolved or not with (latest) CentOS Stream 9. I have seen that Istio attempted to solve the same issue by using stdin instead of a temp file, something I did not see working in the past. I guess we should check again.
> 
> Ref: [networkplumbing/go-nft#51](https://github.com/networkplumbing/go-nft/pull/51)

Tests confirmed it works now, with the older `/tmp` and the newer `stdin` option.
With https://github.com/kubevirt/kubevirt/pull/9282 merged, we can close this issue now.

/close
