### ISSUE TITLE
Not able to consume `kubevirt.io/kubevirt` in my project

### ISSUE THREAD

**Issue by viveksinghggits** [kubevirt/kubevirt#9252]
**What happened**:
I am planning to consume `kubevirt.io/kubevirt` in my project to interact with `ssh` package. But I am not successfully able to do so. Below is the issue that I get into when I try to do so

```
go: github.com/openshift/api@v0.0.0: reading github.com/openshift/api/go.mod at revision v0.0.0: unknown revision v0.0.0
```

**What you expected to happen**:
I expect the code to build successfully so that I can use ssh package.

**Additional context**:
One thing that I would like to highlight is, my project already has `github.com/openshift/api` and `github.com/openshift/client-go` direct dependencies.

And I have tried to include the replace statements with the versions that I have already been using for above dependencies but it still didn't work.

**Comment by viveksinghggits** [comment]
cc @mhenriks

**Comment by mhenriks** [comment]
hmmm, what versions of `kubevirt/clinet-go` and `openshift/api` are you using?

**Comment by viveksinghggits** [comment]
these are the version that I have currently

```
kubevirt.io/api v0.0.0-20220914144647-b82ad1cb4384
kubevirt.io/client-go v0.57.1
```

**Comment by mhenriks** [comment]
Are you using the same version of k8s libs as kubevirt (v0.23.5)?
