### ISSUE TITLE
Can we please build arm version also of the `virtctl` binary

### ISSUE THREAD

**Issue by viveksinghggits** [kubevirt/kubevirt#9253]
**Is your feature request related to a problem? Please describe**:
NO

**Comment by SAMZONG** [comment]
It's important to me

**Comment by xpivarc** [comment]
@zhlhahaha Do we officially build arm version? If not would you like to work on it?

**Comment by zhlhahaha** [comment]
> @zhlhahaha Do we officially build arm version? If not would you like to work on it?

I have opened an issue on how we can make officially build Arm version. Do you have some suggestion on it?
https://github.com/kubevirt/kubevirt/issues/9756

**Comment by zhlhahaha** [comment]
> @zhlhahaha Do we officially build arm version? If not would you like to work on it?

https://github.com/kubevirt/kubevirt/pull/9832
Arm64 version build will be released.
