### ISSUE TITLE
docs.kubevirt.io seems to be down

### ISSUE THREAD

**Issue by jniederm** [kubevirt/kubevirt#926]
```
$ curl https://docs.kubevirt.io
curl: (7) Failed to connect to docs.kubevirt.io port 443: Connection refused
```

**Comment by fabiand** [comment]
Should be fixed now, please try.

http://docs.kubevirt.io (should redirect to http://www.kubevirt.io/user-guide)

Or

`curl -L docs.kubevirt.io`

**Comment by fabiand** [comment]
Good hint. Thanks!
