### ISSUE TITLE
The hotplug volume pod killed more time would lead the iSCSI re-login

### ISSUE THREAD

**Issue by Vicente-Cheng** [kubevirt/kubevirt#9263]
**What happened**:
The VM with hotplug volume. If the hotplug volume pod `hp-volume-` is dead more than twice. The iSCSI connection on the host would logout/login. That makes the above hotplug volume not used anymore. If the user tries to access this device, that will trigger an IO error.

**What you expected to happen**:
The hotplug volume should normally work even if the `hp-volume-` pod is dead more than twice.

**How to reproduce it (as minimally and precisely as possible)**:
1. create one VM instance.
2. attach the hotplug volume.
3. manually delete the `hp-volume-xxx`.
4. manually delete the `hp-volume-xxx` (newly hp-volume- pod) again.
5. You could check the iSCSI connection will logout then login. Also, the disk on the VM should be also broken.

**Additional context**:
We found that because the global path is detached by kubelet when we delete `hp-volume-` pod first time.
Then when we delete the `hp-volume-` pod again. The kubelet would detach from the node directly. Then after the new `hp-volume- pod` comes back, attach it to the node again.
The brief flow is as follows:
```
hp-volume-aaa
  -> killed, then hp-volume-bbb creating
  -> kubelet try to detach but fail (because the volume is still mounted (global path), then new pod is coming back, everything is fine)
  -> umount global/staging path
hp-volume-bbb
  -> killed, then hp-volume-ccc creating
  -> kubelet try to detach from node and success (because now the global path is unmounted)
hp-volume-ccc
```

**Environment**:
- KubeVirt version (use `virtctl version`): 0.54.0
- Kubernetes version (use `kubectl version`): 1.24.7
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: Longhorn CSI
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by harshitgupta1337** [comment]
Hey folks. I am seeing a similar error, but this time with Filesystem volumes. PR #9269 only affects the behavior with respect to Block hotplug PVs.
When I delete the attachment pod, it is possible that the virt-controller doesn't find any active attachment pods and therefore sets the phase of the HP volumes to VolumeBound. 
https://github.com/kubevirt/kubevirt/blob/dcfb3ac8763588ae50e450ec28d59e2fadfc1cec/pkg/virt-controller/watch/vmi.go#L2150
This will cause virt-launcher to detach the disks backed by those volumes from the libvirt domain.
When the attachment pod is created again, the phase of HP volumes is set back to Attached/Mounted/Ready and I/O can resume.
What can we do to prevent virt-controller from noticing the absence of attachment pod ?

**Comment by innobead** [comment]
cc @Vicente-Cheng :point_up:
