### ISSUE TITLE
make cluster-sync fails with podman v4.4.0

### ISSUE THREAD

**Issue by victortoso** [kubevirt/kubevirt#9279]
**What happened**:
With podman 4.4.0, make cluster-sync fails with
```bash
Waiting for rsyncd to be ready.............................failed
@ERROR: chroot failed
rsync error: error starting client-server protocol (code 5) at main.c(1859) [sender=3.2.7]
make[1]: *** [Makefile:150: cluster-build] Error 5
```

Downgrading podman to 4.2.1 fixes the issue.

**What expected to happen**
`make cluster-sync` should work with podman 4.4.0

**How to reproduce it (as minimally and precisely as possible)**:
Using [rootful podman](https://github.com/kubevirt/kubevirtci/blob/main/PODMAN.md) with version 4.4.0, just `make cluster-up` and `make cluster-sync`

**Additional context**:
As pointed out by @brianmcarey , this seems to be the recent cap change in podman. See https://github.com/containers/podman/issues/17504

**Comment by oshoval** [comment]
Thanks @victortoso for reporting
