### ISSUE TITLE
testvm 网络不通

### ISSUE THREAD

**Issue by zulan88** [kubevirt/kubevirt#9283]
虚拟机中不能访问外部网络

VirtualMachine testvm
```
---
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
  name: VirtualMachine
  namespace: default
  resourceVersion: '6349639'
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
      labels:
        kubevirt.io/domain: testvm
        kubevirt.io/size: small
    spec:
      domain:
        devices:
          disks:
            - disk:
                bus: virtio
              name: containerdisk
            - disk:
                bus: virtio
              name: cloudinitdisk
          interfaces:
            - masquerade: {}
              name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 64M
      networks:
        - name: default
          pod: {}
      volumes:
        - containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
          name: containerdisk
        - cloudInitNoCloud:
            userDataBase64: SGkuXG4=
          name: cloudinitdisk
```

CNI配置

```
{
  "name": "cni0",
  "cniVersion":"0.3.1",
  "plugins":[
    {
      "datastore_type": "kubernetes",
      "nodename": "node158",
      "type": "calico",
      "log_level": "info",
      "log_file_path": "/var/log/calico/cni/cni.log",
      "ipam": {
        "type": "calico-ipam",
        "assign_ipv4": "true",
        "ipv4_pools": ["10.234.0.0/16"]
      },
      "container_settings": {
        "allow_ip_forwarding": true
      },
      "policy": {
        "type": "k8s"
      },
      "kubernetes": {
        "kubeconfig": "/etc/cni/net.d/calico-kubeconfig"
      }
    },
    {
      "type":"portmap",
      "capabilities": {
        "portMappings": true
      }
    },
    {
      "type":"bandwidth",
      "capabilities": {
        "bandwidth": true
      }
    }
  ]
}
```

pod virt-launcher-testvm-gct8r compute 日志
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"testvm","namespace":"default","pos":"server.go:191","timestamp":"2023-02-21T05:25:48.676649Z","uid":"76bd566e-c304-4258-bec4-99095d8bf883"}
{"component":"virt-launcher","kind":"","level":"warning","msg":"found no SR-IOV networks to PCI-Address mapping. fall back to resource address pool","name":"testvm","namespace":"default","pos":"hostdev.go:49","timestamp":"2023-02-21T05:30:48.673655Z","uid":"76bd566e-c304-4258-bec4-99095d8bf883"}

**Comment by usrbinkat** [comment]
# translated

虚拟机中不能访问外部网络 == The virtual machine cannot access the external network

**Comment by usrbinkat** [comment]
@zulan88 I understand there are networking problems, can you share an example of how you have tested this issue to observe the failure, as well as any other troubleshooting steps you've tried to overcome the problem? Do any other VMs have networking that is functioning properly in this cluster?

Kubernetes and Kubevirt versions would be helpful as well as any calico specific details that you may be able to provide.

**Comment by zulan88** [comment]
kubernetes:v1.23.8
kubevirt:v0.58.0
calico:v3.21.5
None of the VMS in the cluster can access the external network

an example of VirtualMachine testvm
Enter the virt-launcher container
bash-4.4# ip addr 
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
3: eth0@if29: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether 3e:a0:66:2e:c8:ec brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 10.234.52.241/32 scope global eth0
       valid_lft forever preferred_lft forever
4: k6t-eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc noqueue state UP group default 
    link/ether 02:00:00:00:00:00 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.1/24 brd 10.0.2.255 scope global k6t-eth0
       valid_lft forever preferred_lft forever
5: tap0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast master k6t-eth0 state UP group default qlen 1000
    link/ether e6:2f:36:2d:2a:0d brd ff:ff:ff:ff:ff:ff


Enter the VM testvm
$ ip addr
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: eth0: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1450 qdisc pfifo_fast qlen 1000
    link/ether 52:54:00:9c:b2:28 brd ff:ff:ff:ff:ff:ff
    inet 10.0.2.2/24 brd 10.0.2.255 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::5054:ff:fe9c:b228/64 scope link 
       valid_lft forever preferred_lft forever
$ route -n
Kernel IP routing table
Destination     Gateway         Genmask         Flags Metric Ref    Use Iface
0.0.0.0         10.0.2.1        0.0.0.0         UG    0      0        0 eth0
10.0.2.0        0.0.0.0         255.255.255.0   U     0      0        0 eth0
 
I'm not sure how to proceed

**Comment by qinqon** [comment]
We are also using calico at our CI so it should be fine, let's check if the proxy ARP thing from calico is not causing issues.

Can you show the ARP table at the guest VM with `arp  -an` ?

**Comment by zulan88** [comment]
$ arp -an
? (10.0.2.1) at 02:00:00:00:00:00 [ether]   on eth0
