### ISSUE TITLE
Downward metrics disks using the wrong path in the virt-launcher pod

### ISSUE THREAD

**Issue by 0xFelix** [kubevirt/kubevirt#9284]
**What happened**:
Downward metrics disks are stored under `/var/run/kubevirt-private/downwardapi-disks/vhmostmd0` inside the virt-launcher pod.

**What you expected to happen**:
Downward metrics disks should be stored under `/var/run/kubevirt-private/downwardmetric-disks/vhmostmd0` inside the virt-launcher pod.

**How to reproduce it (as minimally and precisely as possible)**:
Launch a VM with downward metrics enabled.

**Additional context**:
Probably only a copy/paste mistake, see:

https://github.com/kubevirt/kubevirt/blob/0e3a1719c34ca4a0e7eb5925fe0fa2317bc18f0a/pkg/config/config.go#L80

`DownwardAPIDisksDir` is used instead of `DownwardMetricDisksDir`.

**Environment**:
- KubeVirt version (use `virtctl version`): 0.58.1 / master
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by prakrit55** [comment]
hello there @0xFelix , how can we reproduce the issue, could u know me a bit I would like to contribute on the issue?

**Comment by 0xFelix** [comment]
Hi @prakrit55, you can create a VM with downward metrics enabled, then attach to the virt-launcher pod of the VM and have a look at its file system hierarchy. There is already an open PR trying to fix the issue, so it would be best to start from there: #9285

**Comment by jcanocan** [comment]
Hi @prakrit55 you can follow [these](https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#downwardmetrics) steps to setup the scenario. Then, if you login into the VM launcher pod with `cluster-up/kubectl.sh exec --stdin --tty launcher-pod -- /bin/bash` and go to `/var/run/downward-metri-disk/` you will note that the folder it's empty and the `vhostmd` file, where the downward metrics are written, is located in `downwardapi-disks` instead.

**Comment by prakrit55** [comment]
yes, I think the pr need reviews.
