### ISSUE TITLE
cloud-init api change breaks upgrade

### ISSUE THREAD

**Issue by alaypatel07** [kubevirt/kubevirt#9292]
**What happened**:
Attempting to upgrade kubevirt from v0.35 to v0.50, workloads started failing because of api field change.

This [change](https://github.com/kubevirt/kubevirt/commit/2420891759bbc576c729988101b6571a1995ee8b#diff-df80969248f844e11fb3100c4242de8379bc714a214eb9817e091a37c4e74ea5R83-R88) updates the hyphen cloud init field `instance-id`, `local-hostname`, delimited field to an underscore delimited field (snake case).

Upon upgrade the workloads started failing because it couldnt find `instance-id` and the omitempty json tag didnt populate the field

**What you expected to happen**:
VMIs workloads are expected to work with the same configuration as before even after upgrade

**How to reproduce it (as minimally and precisely as possible)**:
1. Run cloud init configdrive metadata with older kubevirt (v0.35)
2. upgrade kubevirt
3. try to create and boot up the same as step 1 vmi again.

**Additional context**:
Today the api fields have inconsistent [keys](https://github.com/kubevirt/kubevirt/blob/4de7e9773109226c1ecc9e4a0df9ed2f1f6b0cd5/pkg/cloud-init/cloud-init.go#L86-L97), the NoCloudMetada continues to have `-` delimited keys vs snake case in `ConfigDriveMetadata`.

It would be good to add additional fields `LegacyInstanceType` with `json:"instance-type,omitempty"` so that users can define their fields consistently and also the upgrades from older version of the API are not breaking.

**Comment by davidvossel** [comment]
@alaypatel07 I changed the ConfigDrive cloud init metadata to use underscores in the json output because that's the way these fields are interpreted by the ConfigDrive cloud-init DataSource.

So, the field `public_keys` is known by the ConfigDrive datasouce and results in the injection of those public keys into the guest. the field `public-keys` is not interpreted by the ConfigDrive datasource and is unknown. The [change](https://github.com/kubevirt/kubevirt/commit/2420891759bbc576c729988101b6571a1995ee8b#diff-df80969248f844e11fb3100c4242de8379bc714a214eb9817e091a37c4e74ea5R83-R88) you refer to was meant to align us with how cloud init worked.

**Comment by alaypatel07** [comment]
@davidvossel thanks a quick response and the explanation. We dont use the `public_keys` feature so I wasnt aware, but the `instance-id` field is what broke this upgrade. 
I had two questions for my own understanding:
1. Does cloud-init config drive also require `instance-id`, `local-hostname` are fields to be `instance_id` and `local_hostname`?
2. If they would you be open to adding LegacyInstanceID, LegacyInstanceType, LegacyLocalHostname fields to the metadata to make sure older vmi's work?

**Comment by rmohr** [comment]
> Does cloud-init config drive also require instance-id, local-hostname are fields to be instance_id and local_hostname?

I at least had the impression that it got picked up in the past. Considering your feedback, it seems like it worked for you with the old fields but not with the new ones? Is cloud-init itself failing or your payload on top which may parse these fields as well?

> 2\. If they would you be open to adding LegacyInstanceID, LegacyInstanceType, LegacyLocalHostname fields to the metadata to make sure older VMIs work?

If really cloud-init is failing now and not your workload I would say we definitely need a fix. Otherwise the Legacy* path would also be a viable option for me.

**Comment by alaypatel07** [comment]
@rmohr @davidvossel Apologies in not being clear in the original issue. 

> I at least had the impression that it got picked up in the past. 

Yes, it is getting picked up.

> Is cloud-init itself failing or your payload on top which may parse these fields as well?

cloud-init is working properly, but the VMI on  bootup, reads the cloud-init metadata and is in the critical path of a successful bootup.

When the upgrade happened, 
1. the VMIs using `cloudInitNoCloud` volume source continued to boot up successfully because the `instance-id` fields was present in the metadata file in the VMI and VMI was happy at boot-time.

```
# echo $logs | base64 -d
{"instance-id":"foo-bar","hostname":"minikube"}
```

2. The VMIs using `cloudInitConfigDrive` volume source failed because the older `instance-id` were missing and instead `instance_id` was present. The startup application found the field missing and was unable to boot up the VM.

```
# echo $logs | base64 -d
{"instance_id":"foo-bar","hostname":"minikube"}
```

In order for the VMI to work post upgrade, the application has workaround this by looking for both the fields.

I was wondering if we can add the fields to the [ConfigDriveMetadata](https://github.com/kubevirt/kubevirt/blob/main/pkg/cloud-init/cloud-init.go#L91) struct.
```
	// The following fields are added for backward compatibility so that upgrades go through without downtime and consistency with NoCloudMetadata
	LegacyInstanceTypeSnakeCase  string `json:"instance-type,omitempty"`
	LegacyInstanceIDSnakeCase    string `json:"instance-id,omitempty"`
	LegacyLocalHostnameSnakeCase string `json:"local-hostname,omitempty"`
```

resulting in 
```
# echo $logs | base64 -d
{"instance_id":"foo-bar","hostname":"minikube", "instance-id":"foo-bar"}
```

I realized the version skew of the upgrade is large, but I only make this request because I believe the support burden for this insignificant.  I would be happy to put up a PR for it.

**Comment by rmohr** [comment]
So just to summarize:

 * we did not break cloud-init with this, but
 * we broke applications which are reading this file as well
 
 It looks to me as well that the maintenance burden of this would be relatively small. I have no objectsion adding a backwadd compatibility fix for third-party applications. @davidvossel ?

**Comment by alaypatel07** [comment]
> So just to summarize:
> 
> we did not break cloud-init with this, but
> we broke applications which are reading this file as well

This is accurate. The VMI images in our stack are built with many install/post-install scripts which read the metadata json file that is populated by cloud-init. After the upgrade, it was observed that VMIs come up but because of these install/post-install scripts many applications were broken because of the missing `instance-id` field in the json. 

It is much harder to go look at each such script in the tenant codebase than to add the legacy fields back to  [ConfigDriveMetadata](https://github.com/kubevirt/kubevirt/blob/main/pkg/cloud-init/cloud-init.go#L91)

cc @rthallisey please keep me honest here if I am misstating anything.

**Comment by EdDev** [comment]
This issue has been discussed in the kubevirt community meeting on the 22nd of February and several voices raised that this is problematic.

The maintenance is not ending with code being added, but with the need to consider deprecated parts for (based on this proposal) indefinitely. While one may not seem much, such a policy will make it very hard to go forward and improve for the long run.
I am pretty sure we have deprecated several fields already and will continue to evolve like that in the future. If we will need to keep supporting everything for so long, we will have a maintenance problem.

I would expect to see multiple users effected by this before considering this as an exception.
Considering the original changed happened more than 20 versions ago, I think that is unlikely.

**Comment by alaypatel07** [comment]
> This issue has been discussed in the kubevirt community meeting on the 22nd of February and several voices raised that this is problematic.

> The maintenance is not ending with code being added, but with the need to consider deprecated parts for (based on this proposal) indefinitely. While one may not seem much, such a policy will make it very hard to go forward and improve for the long run.
> I am pretty sure we have deprecated several fields already and will continue to evolve like that in the future. If we will need to keep supporting everything for so long, we will have a maintenance problem.

@EdDev There are two problems with the current situation this solution will avoid:

1. If the application is using cloudInitMetadata source it will have to look for `_` fields, if the application is using noCloudMetadata source, it will have to look for `-` fields. So this is not just affecting backward compatibility, this is also affecting the fact that application needs to be aware of how they are configured.
2. the upgrades

While the upgrade case might be something that is just affecting us, the first case will affect everyone building images to read from cloud-config metadata which makes this enough to consider the fix IMHO
