### ISSUE TITLE
FOSSA check failing due License issues

### ISSUE THREAD

**Issue by victortoso** [kubevirt/kubevirt#9305]
**What happened**:
The `pull-kubevirt-fossa` test [is failing](https://app.fossa.com/projects/custom%2B13072%2Fgit%40github.com%3Akubevirt%2Fkubevirt.git/refs/branch/main/2023-02-22T11%3A09%3A33Z/preview) due `(2) Unlicensed Dependency` and `(4) Flagged by Policy`. 

Trying to see the exactly report gives back a `You're not permitted to view these issues.`

**What you expected to happen**:
Not sure. If there are known license issues that are not related to the PR, it should not fail for the PR. For license problems that we know, can't we add it to some ignore-list till it gets resolved?

**How to reproduce it (as minimally and precisely as possible)**:
https://github.com/kubevirt/kubevirt/pull/9166

**Comment by dhiller** [comment]
Obsolete, as of now check is working

https://github.com/kubevirt/kubevirt#fossa-status

/close
