### ISSUE TITLE
How to pass labels/annotations to install-strategy-upload jobs

### ISSUE THREAD

**Issue by anvarik** [kubevirt/kubevirt#9316]
**What happened**:
I tried to deploy kubevirt-operator to our azure cluster which has istio enabled. I noticed that a job `kubevirt-xxx-yyy` with container `install-strategy-upload ` was failing with:

```
{"component":"virt-operator","level":"info","msg":"Get \"https://10.0.0.1:443/api/v1/namespaces/openshift-monitoring\": dial tcp 10.0.0.1:443: connect: connection refused\n","pos":"application.go:181","times
│ tamp":"2023-02-24T01:03:50.880415Z"}
```
My guess is that it's due to istio, and want to disable istio for this and similar jobs spawn by operator/cr. But when I dig a little bit I noticed this job is [hard-coded](https://github.com/kubevirt/kubevirt/blob/d321bdd22543aee556301225489bb77b06a8300b/pkg/virt-operator/kubevirt.go#L707).

How can I pass/influence the annotations on similar jobs? 

**What you expected to happen**:
A way to pass annotations to operator/cr jobs

**Environment**:
- KubeVirt version (use `virtctl version`):  v0.59.0-rc.0
- Kubernetes version (use `kubectl version`): v1.24.6
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: Azure with cni drivers
- OS (e.g. from /etc/os-release): Ubuntu 20.04.4 LTS
- Kernel (e.g. `uname -a`): x86_64 GNU/Linux
- Install tools: N/A
- Others: N/A

**Comment by larrydewey** [comment]
Some discussion was had in Slack:

https://kubernetes.slack.com/archives/C0163DT0R8X/p1677089841634009

**Comment by usrbinkat** [comment]
Information that may also be helpful, is your monitoring stack / prometheus deployed to the 'monitoring' namespace? or another namespace by chance?

**Comment by anvarik** [comment]
It is under monitoring. I believe I have identified the problem with Istio and would like to disable it. However, instead of disabling it for the entire namespace or cluster, I am considering passing annotations or labels to disable it for such jobs spawned by Kubevirt. The challenge I'm facing is finding a way to pass these labels
