### ISSUE TITLE
De-/installation issues with Subresources

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#932]
The subresource APIServer is not getting cleaned up during removal when using the manifests, because it is getting created programatically.

Reproducer:

1. create kubevirt service with release yaml under namespace "A"
2. delete kubevirt service via release yaml
3. do "kubectl get apiservices v1alpha1.subresources.kubevirt.io -o yaml", should still see an apiservice registered to namespace "A"
4. create kubevirt service with release yaml under namespace "B"
5. do "kubectl get apiservices v1alpha1.subresources.kubevirt.io -o yaml", should still see an apiservice registered to namespace "A"

Reference: https://groups.google.com/d/msg/kubevirt-dev/jIkxC0726Mw/5UvGCoPtCwAJ

**Comment by rmohr** [comment]
Hm, we need to document on how to deprovision kubevirt. If kubevirt was deployed in the namespace  `kube-system`, then one needs to run

```
 # cluster/kubectl.sh delete all -n kube-system -l "kubevirt.io"
```

We make sure that everything in the manifest or what we generate contains the "kubevirt.io" label.

**Comment by rmohr** [comment]
Ok, forgot about some things. forget the one-liner. In general it is not a trivial process to deprovision kubernetes extensions. That is also related on how crds and finalizers work in k8s.
A special procedure needs to be followed, to not end up with blocked items. I will document it. In general just calling delete on the manifests will not be enough.

**Comment by rmohr** [comment]
> do "kubectl get apiservices v1alpha1.subresources.kubevirt.io -o yaml", should still see an apiservice registered to namespace "A"

@davidvossel can we make sure that virt-api updates the namespace if it differes from the current one?

**Comment by davidvossel** [comment]
> can we make sure that virt-api updates the namespace if it differes from the current one?

yeah, I have an idea. PR incoming

**Comment by fabiand** [comment]
@davidvossel how does #935 relate to this issue?

And what's the approach we want to take here?

**Comment by davidvossel** [comment]
@fabiand All #935 does is make it obvious if two kubevirt installations occur on the same cluster in separate namespaces. The second one will cause the virt-api component to fail to start rather than clobbering the fist one.

**Comment by mhenriks** [comment]
Logic to delete the subresources apiservice will be added to the Kubevirt operator in #1122.
