### ISSUE TITLE
error: unable to recognize "dataVolume.yaml": no matches for kind "DataVolume" in version "cdi.kubevirt.io/v1beta1"

### ISSUE THREAD

**Issue by denniedeng** [kubevirt/kubevirt#9321]
**What happened**:
in my k3s, i have deployed kubevirt-operator and kubevrit-cr.  in kubevirt-cr.yaml, i have added feature "- HotplugVolumes"

kubevirt-cr.yaml like this :
---
apiVersion: kubevirt.io/v1
kind: KubeVirt
metadata:
  name: kubevirt
  namespace: kubevirt
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
      - LiveMigration
      - DataVolumes 
      - HotplugVolumes 
  customizeComponents: {}
  imagePullPolicy: IfNotPresent
  workloadUpdateStrategy: {}
  infra:
    replicas: 1

when i create DataVolume, got the error:
error: unable to recognize "dataVolume.yaml": no matches for kind "DataVolume" in version "cdi.kubevirt.io/v1beta1"

this is my datavolume yaml:
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  name: example-blank-dv
spec:
  source:
    blank: {}
  pvc:
    accessModes:
      - ReadWriteOnce
    resources:
      requests:
        storage: 1Gi

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): 
Client Version: version.Info{GitVersion:"v0.58.1", GitCommit:"3951090bffaf56814889bcf44ec8db53a4e0b24e", GitTreeState:"clean", BuildDate:"2023-02-10T20:08:40Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.51.0", GitCommit:"a6a84d0388b12d8c812e19cb7cc88f5193e42bdf", GitTreeState:"clean", BuildDate:"2022-03-08T21:17:05Z", GoVersion:"go1.17.5", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`): 
Client Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.13+k3s1", GitCommit:"99eadcc10bce2527ae1ab0964b540a4f52a53504", GitTreeState:"clean", BuildDate:"2021-07-22T20:29:55Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"19", GitVersion:"v1.19.13+k3s1", GitCommit:"99eadcc10bce2527ae1ab0964b540a4f52a53504", GitTreeState:"clean", BuildDate:"2021-07-22T20:29:55Z", GoVersion:"go1.15.14", Compiler:"gc", Platform:"linux/amd64"}

- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release):  Centos7 
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by vasiliy-ul** [comment]
Hi @denniedeng,

> in my k3s, i have deployed kubevirt-operator and kubevrit-cr.

Have you also deployed CDI? https://kubevirt.io/user-guide/operations/containerized_data_importer/

**Comment by denniedeng** [comment]
when i upgraded my k3s to v1.25.6+k3s1 and install CDI,  this problem was solved. thanks.
