### ISSUE TITLE
Expose downwardMetrics to guests through virtio-serial channel

### ISSUE THREAD

**Issue by jcanocan** [kubevirt/kubevirt#9342]
**Is your feature request related to a problem? Please describe**:

DownwardMetrics are exposed to VMs through a block device. The steps to expose those metrics are described [here](https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#downwardmetrics). We will like to add the possibility to expose the downwardMetrics through a virtio-serial channel. Please note that the plan would be to allow users to select one or the other method, but not both at the same time.

The main reasons for this improvement are:

- To be more aligned with the [vhostmd](https://github.com/vhostmd/vhostmd) project.
- To satisfy the requirements for getting the [SAP certification](https://issues.redhat.com/browse/CNV-23050) on KubeVirt.
- To avoid potential sync problems with the vhostmd file. The downwardmetrics process writes a vhostmd file in the virt-launcher pod every [5 seconds](https://issues.redhat.com/browse/CNV-23050) and the guest is allowed to read the metrics in any time. Due to the fact that the vhostmd file [writing](https://github.com/kubevirt/kubevirt/blob/70be414cda62b935b80b07c068d592f64f1caf9c/pkg/downwardmetrics/vhostmd/disk.go#L158) function is not atomic and qemu is not informed of such shared usage, the guest could potentially read the file while the writing is not complete.

**Describe the solution you'd like**:

We need to expose a new API field for allowing user to configure downwardMetrics with a virtio serial. This could look like:

```yaml
[...]
spec:
  domain:
    devices:
      serials:
        - name: org.github.vhostmd.1
          downwardMetrics: {}
[...]
```
This configuration will create a new virtio-serial device.

**Describe alternatives you've considered**:

**Additional context**:

**Comment by rmohr** [comment]
> To satisfy the requirements for getting the [SAP certification](https://issues.redhat.com/browse/CNV-23050) on KubeVirt.

Copying from the CNV ticket:

> SAP have deprecated the disk-based metrics solution for new virtualization certifications because it collects the metrics of all VMs in a single file on the host and exposes it as a virtual disk to all VMs so that all VMs can see other VMs metrics (which may be regarded as an information leak or security risk).

This is not true in kubevirt. We don't use vhostmd and the block device only contains information for the single VM in question. I can understand that there were concerns based on how the block device was implemented in vhostmd, but we only expose a format-compatible block-device with information solely related to the current VMI.

**Comment by rmohr** [comment]
> To avoid potential sync problems with the vhostmd file. The downwardmetrics process writes a vhostmd file in the virt-launcher pod every [5 seconds](https://issues.redhat.com/browse/CNV-23050) and the guest is allowed to read the metrics in any time. Due to the fact that the vhostmd file [writing](https://github.com/kubevirt/kubevirt/blob/70be414cda62b935b80b07c068d592f64f1caf9c/pkg/downwardmetrics/vhostmd/disk.go#L158) function is not atomic and qemu is not informed of such shared usage, the guest could potentially read the file while the writing is not complete.

The block device contains a checksum and `vm-dump-metrics` can cope with that situation based on the checksum information. Like it was also possible in the past with vhostmd.

**Comment by rmohr** [comment]
> To be more aligned with the [vhostmd](https://github.com/vhostmd/vhostmd) project.

This looks to me like the only potential reason for a change. If the other way is deprecated and reading the block device via `vm-dump-metrics` is going to be removed we would have to change. But reading and writing over the serial devices is not really easier than the current way from a solution which does a custom-solution to read the information in the guest.

**Comment by germag** [comment]
> > To satisfy the requirements for getting the [SAP certification](https://issues.redhat.com/browse/CNV-23050) on KubeVirt.
> 
> Copying from the CNV ticket:
> 
> > SAP have deprecated the disk-based metrics solution for new virtualization certifications because it collects the metrics of all VMs in a single file on the host and exposes it as a virtual disk to all VMs so that all VMs can see other VMs metrics (which may be regarded as an information leak or security risk).
> 
> This is not true in kubevirt. We don't use vhostmd and the block device only contains information for the single VM in question. I can understand that there were concerns based on how the block device was implemented in vhostmd, but we only expose a format-compatible block-device with information solely related to the current VMI.
> 
> If SAP however insists on not ceritfying with block, despite a clarification on this front, it is probably a good reason to add it :)

In the end it boils down to this, SAP only wants to support virtio-serial

**Comment by rmohr** [comment]
> In the end it boils down to this, SAP only wants to support virtio-serial

Alright, sgtm then. The API draft in the issue looks pretty much ok as well.

**Comment by germag** [comment]
@rmohr I've few question, is there any other application, besides SAP, that wants to access the metrics?, and does it make sense to be able to define more than one serial to access the metrics?

Because, the vhostmd documentation says "The target name of a channel in a QEMU VM configuration must be
`org.github.vhostmd.1`" so maybe we can just use:
```yaml
[...]
spec:
  domain:
    devices:
      serials:
        - downwardMetrics: {}
[...]
```
and hard-code  `org.github.vhostmd.1`, wdyt?

**Comment by rmohr** [comment]
> @rmohr I've few question, is there any other application, besides SAP, that wants to access the metrics?, and does it make sense to be able to define more than one serial to access the metrics?

I don't know of any other than SAP. I also only added block because of SAP. We may be able to deprecate block.



> Because, the vhostmd documentation says "The target name of a channel in a QEMU VM configuration must be `org.github.vhostmd.1`" so maybe we can just use:
> 
> ```yaml
> [...]
> spec:
>   domain:
>     devices:
>       serials:
>         - downwardMetrics: {}
> [...]
> ```
> 
> and hard-code `org.github.vhostmd.1`, wdyt?

it is probably ok. I don't have an overview on existing serial use-cases right now, but it probably goes into that direction then, where for them the name matters:

```yaml
spec:
  domain:
    devices:
      serials:
        - downwardMetrics: {}
        - usecase2: {name: dfdfd, otherstuff }
        - usecase3: {name: xxx, otherstuff}
```

however, what we typically have, is a `name` property to all devices in the spec which are configurable, to make them clearly identifyable. That then allows consistent name mapping for logs inside and outside of the guest when we think about stuff like device-tagging and so forth. It may not be too relevant on serial devices though. @vladikr ?

**Comment by germag** [comment]
> > @rmohr I've few question, is there any other application, besides SAP, that wants to access the metrics?, and does it make sense to be able to define more than one serial to access the metrics?
> 
> I don't know of any other than SAP. I also only added block because of SAP. We may be able to deprecate block.

Ok, I think we can send a PR to add the serial support and a different one for the deprecation of the block sharing.

> 
> > Because, the vhostmd documentation says "The target name of a channel in a QEMU VM configuration must be `org.github.vhostmd.1`" so maybe we can just use:
> > ```yaml
> > [...]
> > spec:
> >   domain:
> >     devices:
> >       serials:
> >         - downwardMetrics: {}
> > [...]
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > and hard-code `org.github.vhostmd.1`, wdyt?
> 
> it is probably ok. I don't have an overview on existing serial use-cases right now, but it probably goes into that direction then, where for them the name matters:
> 
> ```yaml
> spec:
>   domain:
>     devices:
>       serials:
>         - downwardMetrics: {}
>         - usecase2: {name: dfdfd, otherstuff }
>         - usecase3: {name: xxx, otherstuff}
> ```
> 
> however, what we typically have, is a `name` property to all devices in the spec which are configurable, to make them clearly identifyable. That then allows consistent name mapping for logs inside and outside of the guest when we think about stuff like device-tagging and so forth. It may not be too relevant on serial devices though. @vladikr ?

As an alternative, we can add a `name` property, but it could be any arbitrary name instead of the device name (which will always be `org.github.vhostmd.1`), like:

```yaml
[...]
spec:
  domain:
    devices:
      serials:
        - name: metrics
          downwardMetrics: {}
[...]
```

if more than one serial downwardMetric is added, simply use one and ignore the rest

**Comment by germag** [comment]
One more thing, idk if the api should be 1:1 with libvirt, in that case shuld we use `channels` instead of `serials` ?

**Comment by rmohr** [comment]
> One more thing, idk if the api should be 1:1 with libvirt, in that case shuld we use channels instead of serials ?

Completely abstracting it away would be also  an option (given that there are no configuration choices for users involved). 

Like:

```yaml
spec:
  domain:
    devices:
      downwardMetrics: {}
```

**Comment by germag** [comment]
> > One more thing, idk if the api should be 1:1 with libvirt, in that case shuld we use channels instead of serials ?
> 
> Completely abstracting it away would be also an option (given that there are no configuration choices for users involved).
> 
> Like:
> 
> ```yaml
> spec:
>   domain:
>     devices:
>       downwardMetrics: {}
> ```

This is the option I like the most, it solves the `name` thing and doesn't interfere with a future use case.
Thanks

**Comment by jcanocan** [comment]
> > > One more thing, idk if the api should be 1:1 with libvirt, in that case shuld we use channels instead of serials ?
> > 
> > 
> > Completely abstracting it away would be also an option (given that there are no configuration choices for users involved).
> > Like:
> > ```yaml
> > spec:
> >   domain:
> >     devices:
> >       downwardMetrics: {}
> > ```
> 
> This is the option I like the most, it solves the `name` thing and doesn't interfere with a future use case. Thanks

I like this option too. It's simple and straightforward. Let's follow this path.
