### ISSUE TITLE
Virt-handler on kind fails with `invalid argument: the accel 'kvm' is not supported`

### ISSUE THREAD

**Issue by timstoop** [kubevirt/kubevirt#9346]
**What happened**:
When following the guide to get KubeVirt running in kind (https://kubevirt.io/quickstart_kind/), I run into the issue that virt-handler will not run. It fails with the error:
```
$ kubectl -n kubevirt logs virt-handler-4rbmc virt-launcher
error: failed to get emulator capabilities
error: invalid argument: the accel 'kvm' is not supported by '/usr/libexec/qemu-kvm' on this host
```

**What you expected to happen**:
I would expect it to run without an issue, as my machine supports KVM just fine, as far as I know.

**How to reproduce it (as minimally and precisely as possible)**:
I just followed the guide.

**Additional context**:
Both my machine and the kind container report that they can use KVM:
```
$ virt-host-validate qemu
  QEMU: Checking for hardware virtualization                                 : PASS
  QEMU: Checking if device /dev/kvm exists                                   : PASS
  QEMU: Checking if device /dev/kvm is accessible                            : PASS
...
$ docker exec -ti kind-control-plane virt-host-validate qemu
  QEMU: Checking for hardware virtualization                                 : PASS
  QEMU: Checking if device /dev/kvm exists                                   : PASS
  QEMU: Checking if device /dev/kvm is accessible                            : PASS
...
```

**Environment**:
- KubeVirt version (use `virtctl version`): v0.59.0
- Kubernetes version (use `kubectl version`): v1.25.3
- Kind version: v0.17.0
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Linux Mint 21.1 (Ubuntu Jammy)
- Kernel (e.g. `uname -a`): 5.19.0-32-generic
- Install tools: N/A
- Others: N/A

**Comment by timstoop** [comment]
This does not seem to be the AppArmor issue, as I see no reports about qemu in the AppArmor logs and the error message itself is different.

**Comment by oshoval** [comment]
Hi,
We don't support kind with kubevirt for version 1.24+
Please see https://github.com/kubernetes-sigs/kind/issues/2999
You can see the [kubevirtci](https://github.com/kubevirt/kubevirtci) provider that use kind 1.23 if it helps
as reference of what need to be mounted and done in order to use kubevirt.
Note that we are using it for now only for running SR-IOV tests U/S.

Thanks

**Comment by timstoop** [comment]
Ah, might be good to make the quickstart reflect that, then! Thanks.

**Comment by oshoval** [comment]
If it helps there is a WIP effort to use k3d based on 1.25.6 here
https://github.com/kubevirt/kubevirtci/pull/972
you just need to remove the SR-IOV calling

**Comment by timstoop** [comment]
Thanks, but I'm fine with just downgrading the kind cluster to 1.23 :-) It's just for testing kubevirt + clusterapi locally.

**Comment by timstoop** [comment]
For reference, sadly using the kind provided 1.23.13 images results in exactly the same issue. I'll start looking into k3d now.

**Comment by timstoop** [comment]
Another note, it was PEBKAC. I had a VirtualBox running which hijacked the CPU capabilities, so KVM Was unable to use it. Thanks for the assist, though!
