### ISSUE TITLE
enable monitor firstly ,  install proemtheus-operator secondly,  virt-operator will not create servicemonitor 

### ISSUE THREAD

**Issue by willzgli** [kubevirt/kubevirt#9356]
**What happened**:
If I install kubevirt with enabling vm monitor settings  firstly  (ref : https://kubevirt.io/user-guide/operations/component_monitoring/#integrating-with-the-prometheus-operator) , then install  proemtheus-operator , the servicemonitor  prometheus-kubevirt-rules and prometheusrule  prometheus-kubevirt-rules will not be created anymore.

**What you expected to happen**:

we can enable vm monitor settings firstly,  and  kubevirt-operator  creates the serviemontior and prometheusrule or not depends whether the proemtheus-operator has been installed.  The benifit is that  we don't need to update the CR  kubevirt again. Actually, cdi-operator has aready implement it. 

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Comment by rootdeep** [comment]
> Probably should be fixed by #8914

I  saw the commit, but it dosen't been merged into main. why?

**Comment by rootdeep** [comment]
@vasiliy-ul  @chrisho  How dose  pr #8914 work？I cherry-pick it  to v0.59.0, and have a test, but it dosen't create the servicemonit resoruce , only the virt-operator restarts.

**Comment by chrisho** [comment]
> @vasiliy-ul @chrisho How dose pr #8914 work？I cherry-pick it to v0.59.0, and have a test, but it dosen't create the servicemonitor resoruce in my case , only the virt-operator restarts, and the targetInstallStrategy not been recreated . Dose virt-operater need some special env or parameters?

The PR is to detect whether servicemonitor or prometheusrule has been applied to k8s, if applied that the virt-operator will restart, it does not create resources.

**Comment by rootdeep** [comment]
> > @vasiliy-ul @chrisho How dose pr #8914 work？I cherry-pick it to v0.59.0, and have a test, but it dosen't create the servicemonitor resoruce in my case , only the virt-operator restarts, and the targetInstallStrategy not been recreated . Dose virt-operater need some special env or parameters?
> 
> The PR is to detect whether servicemonitor or prometheusrule has been applied to k8s, if applied that the virt-operator will restart, it does not create resources.

@chrisho why virt-operator need to restart?

**Comment by rootdeep** [comment]
> > @vasiliy-ul @chrisho How dose pr #8914 work？I cherry-pick it to v0.59.0, and have a test, but it dosen't create the servicemonitor resoruce in my case , only the virt-operator restarts, and the targetInstallStrategy not been recreated . Dose virt-operater need some special env or parameters?
> 
> The PR is to detect whether servicemonitor or prometheusrule has been applied to k8s, if applied that the virt-operator will restart, it does not create resources.

@chrisho  why the virt-operato need to restart?

**Comment by chrisho** [comment]
> > > @vasiliy-ul @chrisho How dose pr #8914 work？I cherry-pick it to v0.59.0, and have a test, but it dosen't create the servicemonitor resoruce in my case , only the virt-operator restarts, and the targetInstallStrategy not been recreated . Dose virt-operater need some special env or parameters?
> > 
> > 
> > The PR is to detect whether servicemonitor or prometheusrule has been applied to k8s, if applied that the virt-operator will restart, it does not create resources.
> 
> @chrisho why the virt-operato need to restart?

Refer to https://github.com/kubevirt/kubevirt/issues/6551#issuecomment-1195972383

**Comment by rootdeep** [comment]
> > > > @vasiliy-ul @chrisho How dose pr #8914 work？I cherry-pick it to v0.59.0, and have a test, but it dosen't create the servicemonitor resoruce in my case , only the virt-operator restarts, and the targetInstallStrategy not been recreated . Dose virt-operater need some special env or parameters?
> > > 
> > > 
> > > The PR is to detect whether servicemonitor or prometheusrule has been applied to k8s, if applied that the virt-operator will restart, it does not create resources.
> > 
> > 
> > @chrisho why the virt-operato need to restart?
> 
> Refer to [#6551 (comment)](https://github.com/kubevirt/kubevirt/issues/6551#issuecomment-1195972383)

I have read #6551 serval times , but don't get the purpose for restarting virt-operator if  prometheus APIs come online. 
Restart virt-operator for what?

**Comment by willzgli** [comment]
@vasiliy-ul   In fact , #8194 fix a bug  about virt-operator, the bug is  creating  kubevirt yaml firstly without enabling monitor, and then installing the prometheus-operator  stack and  updating the yaml file  kubevirt to enabing monitor , if the virt-operator not restart, it will not create servicemontor and prometheusrule resource. It‘s different with my issue description. Base on #8194, I changed several lines of  code, it resolved my requirement.
