### ISSUE TITLE
Disk order is out of order with bus scsi type

### ISSUE THREAD

**Issue by qkfrksvl** [kubevirt/kubevirt#9361]
Kubevirt Version : 0.59.0 (also occurred in 0.58.0)

Hi, I'm trying to deploy VM with bus scsi and then found that out of order disk number.

Expected to like this.
sda: 40G
sdb: 100G
sdc: 150G 

however, What it actually looks like is this.
![image](https://user-images.githubusercontent.com/86870268/222776600-51de978e-02f2-4156-b012-828f137b555d.png)

In vmi volume status and libvirt domain xml looks like normal order.

![image](https://user-images.githubusercontent.com/86870268/222776904-0fb94328-62d1-46f8-9fad-9d4df5ca3e0b.png)
![image](https://user-images.githubusercontent.com/86870268/222776966-01cd2e4a-eb6d-4456-b3bc-d800e621e703.png)

I guest this problem arise because of index number in xml domain...

**Comment by qkfrksvl** [comment]
https://github.com/kubevirt/kubevirt/issues/5185

Same issue was reported.

**Comment by usrbinkat** [comment]
One thing that might help is using the "serial" spec for your disk definitions.
http://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#secret

**Comment by awels** [comment]
Copied this from the [libvirt documentation](https://libvirt.org/formatdomain.html#devices)
```
The target element controls the bus / device under which the disk is exposed to the guest OS. The dev attribute indicates the "logical" device name.
The actual device name specified is not guaranteed to map to the device name in the guest OS.
Treat it as a device ordering hint. The optional bus attribute specifies the type of disk device to emulate; possible values are driver specific, with typical values being "ide", "scsi", "virtio", "xen", "usb", "sata", or "sd" "sd" since 1.1.2 .
If omitted, the bus type is inferred from the style of the device name (e.g. a device named 'sda' will typically be exported using a SCSI bus).
The optional attribute tray indicates the tray status of the removable disks (i.e. CDROM or Floppy disk), the value can be either "open" or "closed", defaults to "closed".
NB, the value of tray could be updated while the domain is running. The optional attribute removable sets the removable flag for USB disks, and its value can be either "on" or "off", defaulting to "off".
The optional attribute rotation_rate sets the rotation rate of the storage for disks on a SCSI, IDE, or SATA bus. Values in the range 1025 to 65534 are used to indicate rotational media speed in revolutions per minute.
A value of one is used to indicate solid state, or otherwise non-rotational, storage. These values are not required to match the values of the underlying host storage.
Since 0.0.3; bus attribute since 0.4.3; tray attribute since 0.9.11; "usb" attribute value since after 0.4.4; "sata" attribute value since 0.9.7; "removable" attribute value since 1.1.3; "rotation_rate" attribute value since 7.3.0
```
Essentially there is no real correlation between the 'target' in the domain.xml and the device name inside a guest. If you properly want to identify a disk in the guest, you should use a serial or something like that, and then find the disk using the serial. The method for that will be different per guest. Also for windows for instance there won't be any mapping between the target and the drive letters.
