### ISSUE TITLE
Issue in the virt-launcher/virt-handler communication which emits unwanted warnings

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#937]
We seem to have a non-critical communication issue between virt-handler and virt-launcher which sometimes causes errors of the following form:

```
• Failure [241.647 seconds]
Windows VM
/root/go/src/kubevirt.io/kubevirt/tests/windows_test.go:58
  with kubectl command
  /root/go/src/kubevirt.io/kubevirt/tests/windows_test.go:225
    should succeed to start a vm [It]
    /root/go/src/kubevirt.io/kubevirt/tests/windows_test.go:241

    Unexpected Warning event recieved.
    Expected
        <string>: Warning
    not to equal
        <string>: Warning

    /root/go/src/kubevirt.io/kubevirt/tests/utils.go:219
------------------------------
STEP: Starting the vm via kubectl command
level=error timestamp=2018-04-19T22:16:14.744543Z pos=utils.go:215 component=tests reason="unexpected warning event recieved" msg="unknown error encountered sending command Launcher.Sync: reading body unexpected EOF"
```

As far as I could see the vms come up fine, but our checks don't expect a warning in normal flows.

**Comment by cynepco3hahue** [comment]
@davidvossel Do you know the reason for this errors? I can see it happens pretty often on windows tests, the question if it a real issue, or just issue with our tests utils(that we fail test because of wrong warning message)

**Comment by cynepco3hahue** [comment]
@davidvossel Thanks for the explanation, I hope it the single problem, because I also saw 
```
level=error timestamp=2018-05-01T12:38:29.025639Z pos=utils.go:222 component=tests reason="unexpected warning event recieved" msg="server error. command Launcher.Sync failed: virError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2018-05-01T12:38:28.435648Z qemu-system-x86_64: terminating on signal 15 from pid 39 (/usr/sbin/libvirtd)')"
```

**Comment by rmohr** [comment]
Another interesting one:

```
• Failure [180.478 seconds]
Storage
/root/go/src/kubevirt.io/kubevirt/tests/storage_test.go:39
  Starting a VM
  /root/go/src/kubevirt.io/kubevirt/tests/storage_test.go:119
    With an emptyDisk defined
    /root/go/src/kubevirt.io/kubevirt/tests/storage_test.go:173
      should create a writeable emptyDisk with the right capacity [It]
      /root/go/src/kubevirt.io/kubevirt/tests/storage_test.go:175

      Unexpected Warning event recieved.
      Expected
          <string>: Warning
      not to equal
          <string>: Warning

      /root/go/src/kubevirt.io/kubevirt/tests/utils.go:226
------------------------------
STEP: Starting a VM
STEP: Waiting until the VM will start
level=info timestamp=2018-05-03T08:59:18.239407Z pos=utils.go:224 component=tests msg="Created virtual machine pod virt-launcher-testvmzgck7-5dxpx"
level=info timestamp=2018-05-03T08:59:34.104361Z pos=utils.go:224 component=tests msg="Pod owner ship transfered to the node virt-launcher-testvmzgck7-5dxpx"
level=error timestamp=2018-05-03T08:59:37.331263Z pos=utils.go:222 component=tests reason="unexpected warning event recieved" msg="server error. command Launcher.Sync failed: virError(Code=42, Domain=10, Message='Domain not found: no domain with matching uuid '0bcaa681-040e-4018-b149-40e7438334d7' (kubevirt-test-default_testvmzgck7)')"
```

**Comment by rmohr** [comment]
> level=error timestamp=2018-05-03T08:59:52.804238Z pos=utils.go:222 component=tests reason="unexpected warning event recieved" msg="server error. command Launcher.Sync failed: virError(Code=0, Domain=0, Message='Missing error')"

ha, that is a neat one. That is libvirts ERROR_OK error. Basically no error. We probably reach it through somewhere in the code by accident.

**Comment by rmohr** [comment]
> ha, that is a neat one. That is libvirts ERROR_OK error. Basically no error. We probably reach it through somewhere in the code by accident, where we should return nil.

Could also be a libvirt-go bug. It normally only foes GetLastError(), when it thinks that there is an error.

**Comment by cynepco3hahue** [comment]
@rmohr @davidvossel Does it possible that we run `Sync` action, before `QEMU` process succeeded to start?

**Comment by davidvossel** [comment]
We have two types of errors here.

1. Libvirt errors are anything that has **virError** in the error string. Line the following

```server error. command Launcher.Sync failed: virError(Code=42, Domain=10, Message='Domain not found: no domain with matching uuid '0bcaa681-040e-4018-b149-40e7438334d7' (kubevirt-test-default_testvmzgck7)')```

2. Cmdserver errors between virt-handler and virt-launcher are the ones that look like this.

```unknown error encountered sending command Launcher.Sync: reading body unexpected EOF```

I think our first course of action to begin resolving these issues is to improve virt-launcher's initialization.  We need to add logic that ensures things like the cmdserver and libvirt are responsive **before** marking the pod as ready.

Closing those timing gaps may or may not resolve this issue, but it does let us rule out some possibilities so we can have a more focused effort.

**Comment by rmohr** [comment]
> I think our first course of action to begin resolving these issues is to improve virt-launcher's initialization. We need to add logic that ensures things like the cmdserver and libvirt are responsive before marking the pod as ready.

Are we sure that this EOF error is happening on vm-start and not shutdown?

**Comment by cynepco3hahue** [comment]
@rmohr under `processVmShutdown` we are doing `Ping` to cmd server, so I believe all EOF errors connected to a VM start

**Comment by davidvossel** [comment]
> Are we sure that this EOF error is happening on vm-start and not shutdown?

the error occurs in processVmUpdate, that's the only place sync is called.

**Comment by cynepco3hahue** [comment]
and another one :smile: 
```
virError(Code=38, Domain=10, Message='failed to connect to monitor socket: No such process')
```

**Comment by davidvossel** [comment]
for the libvirt errors, are we seeing any other patterns? Like does this occur on both the openshift and k8s providers?

**Comment by cynepco3hahue** [comment]
@davidvossel I saw it pretty often under windows tests

**Comment by cynepco3hahue** [comment]
This problem solved. We still have some issues with libvirt connection, but it does not relate to this issue.
