### ISSUE TITLE
Support NIC hot-unplug from running VMs

### ISSUE THREAD

**Issue by maiqueb** [kubevirt/kubevirt#9383]
**Is your feature request related to a problem? Please describe**:
Hot-unplug (remove) nics from running VMs is an industry standard available in multiple platforms, allowing the dynamic removal of L2 networks. 

This is useful when the workload (VM) cannot tolerate a restart when dettaching networks.

This would help bridge the gap between KubeVirt's feature set and what the user base expects from it.

**Describe the solution you'd like**:
A command issued via virtctl which would cause the interface to be detached from the domain, the existing pod networking infrastructure removed, and finally, the pod interface detached. 

**Describe alternatives you've considered**:
A "cold" unplug alternative would also be valuable; this wouldn't require the multus-dynamic-networks component, nor multus-v4.

**Additional context**:
This feature requires the ability of modifying the interfaces in a running pod. This is achieved via:
- [multus-v4](https://github.com/k8snetworkplumbingwg/multus-cni/blob/master/deployments/multus-daemonset-thick.yml)
- [multus-dynamic-networks-controller](https://github.com/k8snetworkplumbingwg/multus-dynamic-networks-controller)

**Comment by maiqueb** [comment]
/cc @ormergi 

I think this interests you.

**Comment by EdDev** [comment]
@maiqueb , the feature is in.
There are some low level leftovers which need treatment, but they are not user-facing related.

Unless there is a specific objection, we would like to close this issue in the following days.

**Comment by EdDev** [comment]
The hot-unplug feature has been merged already.
It will probably continue changing during its tech-preview period.

If there is a reason to keep this open, please re-open it.

/close
