### ISSUE TITLE
Cannot install Kubevirt on minikube cluster

### ISSUE THREAD

**Issue by itsaviral2609** [kubevirt/kubevirt#9456]
**What happened**:
While trying to deploy KubeVirt on minikube (WSL), Error 404 was being reported on the terminal window! Suspect a Broken Link! 

<img width="960" alt="2023-03-19 (1)" src="https://user-images.githubusercontent.com/96782675/226132573-cc70dfd8-2f0a-432d-b148-34fb50e5de3f.png">

**What you expected to happen**:

KubeVirt getting deployed on minikube and we are able to see deployments, services, daemonset etc deployed by KubeVirt

**Comment by Vikash993468** [comment]
@itsaviral2609  first you need to set the VERSION with this command  
export VERSION="v0.59.0"   
,then enter the create command

**Comment by shivangnayar-crypto** [comment]
kubectl create -f https://github.com/kubevirt/kubevirt/releases/latest/download/kubevirt-operator.yaml
kubectl create -f https://github.com/kubevirt/kubevirt/releases/latest/download/kubevirt-cr.yaml
you can use this it solved my problem i was facing the same issue

**Comment by itsaviral2609** [comment]
@shivangnayar-crypto @Vikash993468 Thanks for helping me out!
Going to close this one!
