### ISSUE TITLE
try to create opensuse vmi in kubevirt getting error like "failed to find a sourceFile in containerDisk containerdisk: failed to determine default image path <nil>: lstat /proc/1/root/run/containerd/io.containerd.runtime.v2.task/k8s.io/8c08ed3038b10898e8af8a3a72cac81484075fcf53203fef69684694848d8311/rootfs/disk: no such file or directory     Reason:                Synchronizing with the Domain failed."

### ISSUE THREAD

**Issue by ankurshukla2112** [kubevirt/kubevirt#9461]
Please find below yaml for creating opensuse vmi.

apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  name: susi-vm
spec:
  terminationGracePeriodSeconds: 30
  domain:
    resources:
      requests:
        memory: 1024M
    devices:
      disks:
      - name: containerdisk
        disk:
          bus: virtio
      - name: emptydisk
        disk:
          bus: virtio
      - disk:
          bus: virtio
        name: cloudinitdisk
  volumes:
  - name: containerdisk
    containerDisk:
      image: registry.suse.com/suse/sle15:15.1
  - name: emptydisk
    emptyDisk:
      capacity: "2Gi"
  - name: cloudinitdisk
    cloudInitNoCloud:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }

-----------------------------------------------------------------------------------

$kubectl describe vmi susi-vm

Name:         susi-vm
Namespace:    default
Labels:       kubevirt.io/nodeName=kubernetes-worker01
Annotations:  kubevirt.io/latest-observed-api-version: v1
              kubevirt.io/storage-observed-api-version: v1alpha3
API Version:  kubevirt.io/v1
Kind:         VirtualMachineInstance
Metadata:
  Creation Timestamp:  2023-03-20T12:41:31Z
  Finalizers:
    foregroundDeleteVirtualMachine
  Generation:  6
  Managed Fields:
    API Version:  kubevirt.io/v1
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:kubectl.kubernetes.io/last-applied-configuration:
      f:spec:
        .:
        f:domain:
          .:
          f:devices:
            .:
            f:disks:
          f:resources:
            .:
            f:requests:
              .:
              f:memory:
        f:terminationGracePeriodSeconds:
        f:volumes:
    Manager:      kubectl-client-side-apply
    Operation:    Update
    Time:         2023-03-20T12:41:31Z
    API Version:  kubevirt.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubevirt.io/latest-observed-api-version:
          f:kubevirt.io/storage-observed-api-version:
        f:labels:
          .:
          f:kubevirt.io/nodeName:
      f:status:
        f:activePods:
          .:
          f:2c11b735-49f4-4f82-ad9a-f1e6f86a0479:
        f:conditions:
        f:migrationMethod:
        f:migrationTransport:
        f:nodeName:
        f:phase:
        f:phaseTransitionTimestamps:
        f:qosClass:
        f:selinuxContext:
        f:volumeStatus:
    Manager:         Go-http-client
    Operation:       Update
    Time:            2023-03-20T12:41:35Z
  Resource Version:  2230074
  UID:               83cf48ba-cd6d-457b-aa65-00161312a49f
Spec:
  Domain:
    Cpu:
      Cores:    1
      Model:    host-model
      Sockets:  1
      Threads:  1
    Devices:
      Disks:
        Disk:
          Bus:  virtio
        Name:   containerdisk
        Disk:
          Bus:  virtio
        Name:   emptydisk
        Disk:
          Bus:  virtio
        Name:   cloudinitdisk
      Interfaces:
        Bridge:
        Name:  default
    Features:
      Acpi:
        Enabled:  true
    Firmware:
      Uuid:  c44784ae-1968-4259-bc28-4441697d71af
    Machine:
      Type:  q35
    Resources:
      Requests:
        Memory:  1024M
  Networks:
    Name:  default
    Pod:
  Termination Grace Period Seconds:  30
  Volumes:
    Container Disk:
      Image:              registry.suse.com/suse/sle15:15.1
      Image Pull Policy:  IfNotPresent
    Name:                 containerdisk
    Empty Disk:
      Capacity:  2Gi
    Name:        emptydisk
    Cloud Init No Cloud:
      User Data:  #cloud-config
password: fedora
chpasswd: { expire: False }
    Name:  cloudinitdisk
Status:
  Active Pods:
    2c11b735-49f4-4f82-ad9a-f1e6f86a0479:  kubernetes-worker01
  Conditions:
    Last Probe Time:       2023-03-20T12:41:31Z
    Last Transition Time:  2023-03-20T12:41:31Z
    Message:               Guest VM is not reported as running
    Reason:                GuestNotRunning
    Status:                False
    Type:                  Ready
    Last Probe Time:       <nil>
    Last Transition Time:  <nil>
    Message:               cannot migrate VMI which does not use masquerade to connect to the pod network
    Reason:                InterfaceNotLiveMigratable
    Status:                False
    Type:                  LiveMigratable
    Last Probe Time:       <nil>
    Last Transition Time:  2023-03-20T12:41:35Z
    Message:               failed to find a sourceFile in containerDisk containerdisk: failed to determine default image path <nil>: lstat /proc/1/root/run/containerd/io.containerd.runtime.v2.task/k8s.io/a3da40812902c48ac51e227f6ef68d3748c5b74131c131b13c2d3b8c236c2c98/rootfs/disk: no such file or directory
    Reason:                Synchronizing with the Domain failed.
    Status:                False
    Type:                  Synchronized
  Guest OS Info:
  Migration Method:     BlockMigration
  Migration Transport:  Unix
  Node Name:            kubernetes-worker01
  Phase:                Scheduled
  Phase Transition Timestamps:
    Phase:                       Pending
    Phase Transition Timestamp:  2023-03-20T12:41:31Z
    Phase:                       Scheduling
    Phase Transition Timestamp:  2023-03-20T12:41:31Z
    Phase:                       Scheduled
    Phase Transition Timestamp:  2023-03-20T12:41:35Z
  Qos Class:                     Burstable
  Runtime User:                  107
  Selinux Context:               none
  Volume Status:
    Name:    cloudinitdisk
    Target:
    Name:    containerdisk
    Target:
    Name:    emptydisk
    Target:
Events:
  Type     Reason            Age                From                       Message
  ----     ------            ----               ----                       -------
  Normal   SuccessfulCreate  22s                virtualmachine-controller  Created virtual machine pod virt-launcher-susi-vm-4rvxr
  Warning  SyncFailed        7s (x12 over 18s)  virt-handler               failed to find a sourceFile in containerDisk containerdisk: failed to determine default image path <nil>: lstat /proc/1/root/run/containerd/io.containerd.runtime.v2.task/k8s.io/a3da40812902c48ac51e227f6ef68d3748c5b74131c131b13c2d3b8c236c2c98/rootfs/disk: no such file or directory

**Comment by xpivarc** [comment]
/cc @vasiliy-ul 
Does the container image contain the VM image(raw or qcow?)?

**Comment by ankurshukla2112** [comment]
> @ankurshukla2112, `registry.suse.com/suse/sle15:15.1` is a regular SUSE-based container image. It is not a contaierdisk suitable for KubeVirt. I.e. it does not include a VM image.
> 
> To boot openSUSE VM in KubeVirt you can use https://en.opensuse.org/Portal:JeOS. You can download either TW or Leap image and create a containerdisk following the [user guide](https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#containerdisk-workflow-example).



HI @vasiliy-ul  can you provide url of opensuse image version 13.2

**Comment by vasiliy-ul** [comment]
@ankurshukla2112, 13.2 is a very old distro. I am not sure if there are cloud images available. You can still find an installation ISO somewhere around and run it with KubeVirt.
