### ISSUE TITLE
panic: fork/exec /usr/sbin/virtqemud: errno 0

### ISSUE THREAD

**Issue by kvaps** [kubevirt/kubevirt#9465]
**What happened**:

KubeVirt v0.59.0 enabled rootless mode by default. This makes my VMs unable to start:

```javascript
{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:86","timestamp":"2023-03-20T15:23:53.580575Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:89","timestamp":"2023-03-20T15:23:53.580605Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:496","timestamp":"2023-03-20T15:23:53.580998Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory')","pos":"libvirt.go:504","timestamp":"2023-03-20T15:23:53.581221Z"}
{"component":"virt-launcher","level":"error","msg":"failed to start virtqemud","pos":"libvirt_helper.go:250","reason":"fork/exec /usr/sbin/virtqemud: errno 0","timestamp":"2023-03-20T15:23:53.581307Z"}
panic: fork/exec /usr/sbin/virtqemud: errno 0

goroutine 8 [running]:
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/util.LibvirtWrapper.StartVirtquemud.func1()
	pkg/virt-launcher/virtwrap/util/libvirt_helper.go:251 +0x4ce
created by kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/util.LibvirtWrapper.StartVirtquemud
	pkg/virt-launcher/virtwrap/util/libvirt_helper.go:218 +0x65
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 12 with status 512","pos":"virt-launcher-monitor.go:124","timestamp":"2023-03-20T15:23:53.586064Z"}
{"component":"virt-launcher-monitor","level":"error","msg":"dirty virt-launcher shutdown: exit-code 2","pos":"virt-launcher-monitor.go:142","timestamp":"2023-03-20T15:23:53.586143Z"}
```

**What you expected to happen**:
VM able to start without errors

**How to reproduce it (as minimally and precisely as possible)**:

Not sure what is exactly wrong, I tried to compile version without patches and faced the same behavior.
- Install KubeVirt v0.59.0
- Make sure that `Root` feature gate is not enabled
- Create VM:
```yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: vm123
spec:
  running: true
  template:
    spec:
      domain:
        devices: {}
        machine:
          type: q35
        resources:
          requests:
            cpu: "4"
            memory: 2048M
```

**Additional context**:
When I enable `Root` feature gate everything starts working as it should

**Environment**:
- KubeVirt version: `v0.59.0-dirty`
- Kubernetes version: `v1.23.17`
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: bare metal cluster
- OS (e.g. from /etc/os-release): Ubuntu 22.04 LTS
- Kernel (e.g. `uname -a`): `5.15.0-25-generic`
- Install tools: deckhouse
- Others: N/A

**Comment by vasiliy-ul** [comment]
I think your k8s version `v1.23.17` is a bit old. AFAIK, `v0.59.0` has been tested on `1.2{4,5,6}`. Hm... do you have apparmor or selinux enabled on your host?

**Comment by shivangnayar-crypto** [comment]
The error message "Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory" indicates that the libvirt daemon is not running or is not accessible. This could be due to changes in the KubeVirt deployment or configuration, or due to changes in the underlying system configuration.
Check if the libvirt daemon is running and accessible by running the command "systemctl status libvirtd" or "virsh list

**Comment by aland-zhang** [comment]
I have the same problem， kubernetes ： 1.21  , apt-get install qemu-kvm libvirt-daemon-system libvirt-clients bridge-utils virt-manager    
systemctl status libvirtd show Active: active (running)

```
│ {"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:86","timestamp":"2023-03-24T08:08:13.165054Z"}                                                                                                                                                            │
│ {"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:89","timestamp":"2023-03-24T08:08:13.165149Z"}                                                                                                             │
│ {"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:496","timestamp":"2023-03-24T08:08:13.166548Z"}                                                                                                              │
│ {"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory')","pos":"libvirt.go:504","timestamp":"2023-03-24T08:08:13.167097Z"}                                   │
│ {"component":"virt-launcher","level":"error","msg":"failed to start virtqemud","pos":"libvirt_helper.go:250","reason":"fork/exec /usr/sbin/virtqemud: errno 0","timestamp":"2023-03-24T08:08:13.167587Z"}                                                                                                                    │
│ panic: fork/exec /usr/sbin/virtqemud: errno 0    


systemctl status libvirtd
● libvirtd.service - Virtualization daemon
     Loaded: loaded (/lib/systemd/system/libvirtd.service; enabled; vendor preset: enabled)
     Active: active (running) since Fri 2023-03-24 06:21:44 CST; 9h ago
TriggeredBy: ● libvirtd.socket
             ● libvirtd-admin.socket
             ● libvirtd-ro.socket
       Docs: man:libvirtd(8)
             https://libvirt.org
   Main PID: 1842 (libvirtd)
      Tasks: 19 (limit: 32768)
     Memory: 44.6M
     CGroup: /system.slice/libvirtd.service
             ├─1842 /usr/sbin/libvirtd
             ├─2098 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper
             └─2099 /usr/sbin/dnsmasq --conf-file=/var/lib/libvirt/dnsmasq/default.conf --leasefile-ro --dhcp-script=/usr/lib/libvirt/libvirt_leaseshelper

```

**Comment by vasiliy-ul** [comment]
The error about `/var/run/libvirt/virtqemud-sock` is not critical, as KubeVirt will try to re-connect. I think the fact that the socket is not there is the result of exec failure of `/usr/sbin/virtqemud` (since it's `virtqemud` who creates that socket). @aland-zhang , you do not need to install any qemu or libvirt packages on your host machine. KubeVirt containers already provide everything what is required in containers.

**Comment by vasiliy-ul** [comment]
I would try to run the virt-launcher container and exec  `/usr/sbin/virtqemud` manually from there. Smth like
```
# k run test -ti --restart=Never --image=quay.io/kubevirt/virt-launcher:v0.59.0 --command bash
If you don't see a command prompt, try pressing enter.
bash-5.1# /usr/sbin/virtqemud
...
```

**Comment by vasiliy-ul** [comment]
@kvaps, what container runtime are you using in your cluster? Is it docker? I am able to reproduce this error with docker, but it works well with containerd (also likely it works fine with cri-o since it is used in CI).

**Comment by xpivarc** [comment]
@vasiliy-ul Did you see any difference between docker and containerd? Can you check /proc/$/status?

**Comment by vasiliy-ul** [comment]
@xpivarc, what difference do you mean? Apart from this issue with launching a VM all seems the same.

> Can you check /proc/$/status?

What process to check?

**Comment by xpivarc** [comment]
> @xpivarc, what difference do you mean? Apart from this issue with launching a VM all seems the same.

Mainly capabilities of the process(parent or self if you are trying it from bash) and permissions on that binary.
 
> > Can you check /proc/$/status?
> 
> What process to check?

The process which tries to launch virtqemud.

**Comment by vasiliy-ul** [comment]
I checked `virt-launcher-monitor`. There is a diff in capabilities:
```diff
43,44c43,44
< CapPrm:	0000000000000400
< CapEff:	0000000000000400
---
> CapPrm:	0000000000000000
> CapEff:	0000000000000000
56,57c56,57
```
This is `cap_net_bind_service`. In case of docker, permitted and effective capabilities are zeroed.

[launcher-monitor-docker.txt](https://github.com/kubevirt/kubevirt/files/11110838/launcher-monitor-docker.txt)
[launcher-monitor-containerd.txt](https://github.com/kubevirt/kubevirt/files/11110839/launcher-monitor-containerd.txt)

**Comment by xpivarc** [comment]
@vasiliy-ul Thank you!
This is it. Now we need to verify if the Pod has the capability requested and if the monitor binary has the file capability(something like `getcap /usr/bin/virt-launcher-monitor`)

**Comment by vasiliy-ul** [comment]
```
bash-5.1$ getcap /usr/bin/virt-launcher-monitor
/usr/bin/virt-launcher-monitor cap_net_bind_service=ep
```

The pod does have this capability requested (not the pod, but `compute` container):

```yaml
    securityContext:
      allowPrivilegeEscalation: false
      capabilities:
        add:
        - NET_BIND_SERVICE
        drop:
        - ALL
      privileged: false
      runAsGroup: 107
      runAsNonRoot: true
      runAsUser: 107

```

In both cases, I used the same KubeVirt `v0.59.0`. So it's the case code, images, etc. For some reason, docker does not set the capabilities and seems to cause the issue. Also, as I mentioned in https://github.com/kubevirt/kubevirt/issues/9511#issuecomment-1489922851, there is a problem with devices permissions. E.g. `/dev/kvm` is not chown'ed.

**Comment by vasiliy-ul** [comment]
Hm... After poking around in the moby source code, found this interesting commit: https://github.com/moby/moby/commit/0d9a37d0c249e871af0e667317be3169054a989f. More precisely, this code snippet:

https://github.com/moby/moby/blob/7c93e4a09be1a11012ecba0dc612115cd4a79233/oci/oci.go#L30-L36.

> // Do not set Effective and Permitted capabilities for non-root users,
		// to match what execve does.

Comparing to containerd:

https://github.com/containerd/containerd/blob/988ee8ffef1e756039fe05539be3398e70ed3e0c/oci/spec_opts.go#L939-L949

**Comment by vasiliy-ul** [comment]
@xpivarc,

> In this case, the file capability is ignored(almost as if the runtime executed on a binary that does not have the capability set) but I can't imagine why it would be.

Take a look at https://github.com/moby/moby/issues/45491#issuecomment-1540933674

> **allowPrivilegeEscalation**: Controls whether a process can gain more privileges than its parent process. **This bool directly controls whether the no_new_privs flag gets set on the container process**.

> With **no_new_privs** set, execve() promises not to grant the privilege to do anything that could not have been done without the execve call. For example, the setuid and setgid bits will no longer change the uid or gid; **file capabilities will not add to the permitted set**, and LSMs will not relax constraints after execve.

It seems to me that, actually, docker handles that correctly. WDYT?

**Comment by xpivarc** [comment]
@k8scoder192 
Each user needs to update the docker to a fixed version. There is not much more Kubevirt can do at the moment (We do not ship CRI).
