### ISSUE TITLE
virt-api pod running into ImagePullBackOff while setting up kubevirt on minikube 

### ISSUE THREAD

**Issue by itsaviral2609** [kubevirt/kubevirt#9481]
**What happened**:

**Approach 1**

Following the official documentation approach in **minikube!**. coredns pod is always in the container creating status. 
> minikube start --driver=docker --cni=flannel

<img width="528" alt="2023-03-21 (3)" src="https://user-images.githubusercontent.com/96782675/226626616-ef49df7f-8b86-452d-9453-7b386c0b020a.png">

**Logs of coredns pod**

<img width="945" alt="2023-03-21 (4)" src="https://user-images.githubusercontent.com/96782675/226628167-5a7daaa2-d95d-4c91-a2bb-81b706740168.png">

Deploying **kubevirt** (kube-virt pod not getting created)

> kubectl create -f https://github.com/kubevirt/kubevirt/releases/latest/download/kubevirt-operator.yaml
> kubectl create -f https://github.com/kubevirt/kubevirt/releases/latest/download/kubevirt-cr.yaml

<img width="960" alt="2023-03-21 (5)" src="https://user-images.githubusercontent.com/96782675/226628584-09044730-0bf9-4766-961d-b7c2f7a4b388.png">

**logs of pod**

<img width="960" alt="2023-03-21 (6)" src="https://user-images.githubusercontent.com/96782675/226629783-040ab72a-c014-4bce-ab2e-924fadba3604.png">

**Approach-2: creating cni flannel pod by official github repo instead of passing as a flag in minikube start**

> minikube start --driver=docker  (coredns running status this time)

**cni flannel**
> kubectl apply -f https://github.com/flannel-io/flannel/releases/latest/download/kube-flannel.yml

**Deploying kubevirt**

> kubectl create -f https://github.com/kubevirt/kubevirt/releases/latest/download/kubevirt-operator.yaml
> kubectl create -f https://github.com/kubevirt/kubevirt/releases/latest/download/kubevirt-cr.yaml

**kube-api pod in ImagePullBackOff and logs of the pod**

<img width="960" alt="2023-03-21 (9)" src="https://user-images.githubusercontent.com/96782675/226632151-54507cd0-597a-4cee-8a5f-fb0ea3256016.png">

<img width="960" alt="2023-03-21 (10)" src="https://user-images.githubusercontent.com/96782675/226632312-56b22c8d-ca68-4e14-a9be-da78d6a458e9.png">

**What you expected to happen**:
kubevirt getting deployed on minikube!

**Additional context**:

Tried to set it up on WSL

**Comment by alicefr** [comment]
Why are you using the docker driver? The docker support should have been dropped in k8s for a while now. What you are experiencing there isn't related to kubevirt but to your cluster. I'd encourage you to log in to one of the nodes and try to manually pull the image. Using a CRI container engine, you could use `crictl pull`
