### ISSUE TITLE
vhost_vsock error in multi-node kind cluster

### ISSUE THREAD

**Issue by zhlhahaha** [kubevirt/kubevirt#9504]
**What happened**:
In order to run more e2e tests on Arm64 server in KubeVirt CICD pipeline, I am verifying multi-node kind cluster.
When starting a multi-node kind cluster, get following error message in virt-handler
```
{"component":"virt-handler","level":"error","msg":"Failed to bind to VSOCK port 1.","pos":"server.go:77","reason":"listen vsock host(2):1: bind: address already in use","timestamp":"2023-03-22T04:16:22.137612Z"}
```

**What you expected to happen**:
vsock server start succesfully.

**How to reproduce it (as minimally and precisely as possible)**:
```
export KUBEVIRT_PROVIDER=kind-1.23
export KUBEVIRT_NUM_NODES=3
make cluster-up
make cluster-sync
```

**Additional context**:
Vsock does not isoluated by network namespace in kernel, although there is a PR. https://lwn.net/Articles/809819/
However, in `cmd/virt-handler/virt-handler.go`, vsock hypervisor service would start in same port
https://github.com/kubevirt/kubevirt/blob/12475ab5713509bf8d7ef378964f9f2f7166a314/cmd/virt-handler/virt-handler.go#L319
So when we start multiple kubevirt worker node on same host, they will get conflict when trying to binding to same port.

I can come up with two possible solution:
1. start VSOCK server only when `clusterConfig.VSOCKEnabled` is true.
2. dynamic allocate port for VSOCK server.

**Comment by zhlhahaha** [comment]
ping: @rmohr

**Comment by rmohr** [comment]
> start VSOCK server only when clusterConfig.VSOCKEnabled is true.

I would suggest to disable the VSOCK feature gate in the tests for now. What exactly is the `clusterConfig`? Or are you saying that it even starts when the VSOCK featuregate is enabled?

> Vsock does not isoluated by network namespace in kernel, although there is a PR. https://lwn.net/Articles/809819/
However, in cmd/virt-handler/virt-handler.go, vsock hypervisor service would start in same port

Yes ,we have several security barriers in place, but we can not rely on namespaces to separate things in tests.

**Comment by rmohr** [comment]
> dynamic allocate port for VSOCK server.

That was a non-goal of the design. We want to have a well known port which guests can blindly connect to.

**Comment by zhlhahaha** [comment]
> I would suggest to disable the VSOCK feature gate in the tests for now. 

Do you means remove the VSOCK feature gate in testing setup?
https://github.com/kubevirt/kubevirt/blob/6516f58bf28ff2ac8891ad735cdd9b171e728b7c/tests/testsuite/kubevirtresource.go#L108

And add the feature gate only when running the tests in `vmi_vsock_test.go`.

> What exactly is the clusterConfig? Or are you saying that it even starts when the VSOCK featuregate is disabled?

Sorry, I misunderstand the code.

> Yes ,we have several security barriers in place, but we can not rely on namespaces to separate things in tests.

Yes, but we can only use namespace to separate things on Arm server as nested virtualization not works on it.

**Comment by rmohr** [comment]
> And add the feature gate only when running the tests in `vmi_vsock_test.go`.

For ARM parallel tests, yes.
