### ISSUE TITLE
Define videos capabilities, drivers and/or vram

### ISSUE THREAD

**Issue by benth42** [kubevirt/kubevirt#9521]
Hello,

I'm currently using and intensively testing kubevirt and cdi. Well, thank you, it works well.

Now I would like to configure the video sections of libvirt / qemu. 
The objectif is to provide some virtual workstation with acceptable (good enough) graphical performances without buying GPU/vGPU. 

If I'm not wrong, it seems to me to be atually hard coded here ? 
https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-launcher/virtwrap/converter/converter.go#L1716

In the api documentation I didn't see anything : 
https://kubevirt.io/api-reference/master/definitions.html

Thank you in advance.

Regards,

**Comment by alicefr** [comment]
@benth42 how would you like to configure the graphical option? Generally, we don't support all the libvirt option and yes certain are hardcoded or not configurable directly by the user (it depends on the use-case). For no-supported option, there is the possibility to develop a sidecar that set those options (check an example in https://github.com/kubevirt/kubevirt/tree/main/cmd/example-hook-sidecar)

**Comment by benth42** [comment]
Hello,

Sorry for my late reply.  And thank you to have take time to answer.

Changing the xml was not the only necessary thing. Their missing some packages to activate virtio video graphics devices. And more-over redhat seems to have stop to compile -gl extension of virtio graphics drivers according to https://bugzilla.redhat.com/show_bug.cgi?id=2149022

With software rendering a tiny better than with vga, but not really "fluid (?)" 

Well hope to try with nvidia vGPU in the next weeks. 

Thank you again.

Regards,
