### ISSUE TITLE
"virtctl version" not showing service version info

### ISSUE THREAD

**Issue by Vikash993468** [kubevirt/kubevirt#9525]
**What happened**:
`virtctl version` not showing server version info.

```
vikash@pop-os:~$ virtctl version
Client Version: version.Info{GitVersion:"v0.58.0", GitCommit:"6e41ae7787c1b48ac9a633c61a54444ea947242c", GitTreeState:"clean", BuildDate:"2022-10-13T00:33:22Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
the server could not find the requested resource
the server could not find the requested resource

```

**What you expected to happen**:
`virtctl version` should show server version along with client version info

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by sudharsanomprakash** [comment]
@Vikash993468 
Where are you trying to install virtctl? windows/mac/linux? 
You can download lib from https://github.com/kubevirt/kubevirt/releases/tag/v0.58.0
Have you set the execute permission? chmod +x virtctl
