### ISSUE TITLE
Add support for device passthrough

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#953]
We should add support for basic device passthrough of host devices.
Probably aligned with Kubernetes Device Plugins.

**Comment by slintes** [comment]
I'm wondering if this was solved by https://github.com/kubevirt/kubevirt/pull/1548 ?
@fabiand @mfranczy

**Comment by slintes** [comment]
I'm wondering if this was solved by https://github.com/kubevirt/kubevirt/pull/1548 ?
@fabiand @mfranczy

**Comment by fabiand** [comment]
No, #1548 only solves disk cache.

This issue is for device passthroug

**Comment by slintes** [comment]
ok, so this is still a thing

/remove-lifecycle rotten

**Comment by danielBelenky** [comment]
Hey, is this task still relevant? :thinking: Are we talking here on any arbitrary device that the users specify?

Can't this be achieved by specifying mounts to the virt-launcher pod and then to the VM itself?

**Comment by SchSeba** [comment]
Hey @danielBelenky I think I can answer this questions

> Hey, is this task still relevant? thinking Are we talking here on any arbitrary device that the users specify?

Yes we have two types of devices in this area.
1. network devices such as SR-IOV -> already implemented and supported in kubevirt.
2. Devices like GPU and other physical devices connected to the host.

> Can't this be achieved by specifying mounts to the virt-launcher pod and then to the VM itself?

From the kubernetes side you need some type of device plugin to allocate and release resources.

From kubevirt side we have the first part that is a resource spec

```golang
Resources ResourceRequirements `json:"resources,omitempty"`
```

but we still need to add the ability to pass this devices into the VM.

@fabiand anything else to add? :)

**Comment by fabiand** [comment]
In rought strokes it is as Sebastian said.

1. Scheduler awareness to schedule the VM to the right nodes
2. Device alllocation to get the device to the pod
3. Passthrough of the device using ibvirt

In theory 1 and 2 are covered by device plugins and 3 by kubevirt. but
there are devils along the road: Device allocation might be tricky
depending on the device, passthrough imght require many privileges.

Thus yes, but we'll only see the details once we get started :)

**Comment by danielBelenky** [comment]
Ok, I'd like to give this issue a try if this is not an urgent one. Just note that I won't be able to do 100% on it. Is that ok?

**Comment by booxter** [comment]
We should not necessarily need lots of privileges if we use e.g. VFIO and we pre-configure the devices on boot / deployment, so that we can avoid giving privileges to the launcher pod (the same plan we'd like to implement for SR-IOV).

**Comment by Queuecumber** [comment]
/reopen 
/remove-lifecycle rotten

Since there was activity on this as recently as March I assume you didn't mean to let this get closed, though you may want to decide which of this an #1852 you want to keep since they can probably be considered duplicates

**Comment by yichengliu58** [comment]
I'm confronting the same problem, I'm trying to passthrough block disk devices from the host machine to guest. So is there any plans for this feature ?

**Comment by fabiand** [comment]
That's already possible today using a local PV in block mode.

**Comment by Just-Insane** [comment]
Is it possible to pass non-GPU PCI devices to guests without SR-IOV? For example, SAS HBAs or USB controllers?

**Comment by vladikr** [comment]
> Is it possible to pass non-GPU PCI devices to guests without SR-IOV? For example, SAS HBAs or USB controllers?

In general, yes. Please take a look at #3937. Please let us know if this is not sufficient.

**Comment by Just-Insane** [comment]
Looks like that was just merged today. I suspect it will be a while before it makes it into a release?
