### ISSUE TITLE
Kindly help for volume mount in kubevirt  for vm

### ISSUE THREAD

**Issue by ankurshukla2112** [kubevirt/kubevirt#9531]
Hi Team, 
I have created  vm using kubevirt, i have used pv and pvc for volume mount but not able to see the volume in vm, kindly find below all those details.

-------------------------------------------

apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
            - name: vm-pv-storage
              disk: {}
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 64M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=
        - name: vm-pv-storage
          persistentVolumeClaim:
            claimName: vm-pv-claim

-------------------------------------------

used below yaml creation for pv and pvc :

kind: PersistentVolume
metadata:
  name: vm-pv-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 100Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: "/mnt"

---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vm-pv-claim
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 75Gi

------------------------------------------
environment :
kubernetes version -> 1.26.2
kubevirt version -> v0.59.0

**Comment by xpivarc** [comment]
"but not able to see the volume in vm", how do you check this?

**Comment by ankurshukla2112** [comment]
@xpivarc  after console the vm, that volume amount is not available.
using command $ df -h

and when i try to $ cd /mnt it's not working. 
do i need to use any mount command before checking the above commands?

**Comment by xpivarc** [comment]
So I guess you want to share the filesystem but you specified it as a disk. Follow https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#sharing-node-directories if you want to share the filesystem.

**Comment by ankurshukla2112** [comment]
@xpivarc  if i want to mount a disk in vm, what should i need to do?
