### ISSUE TITLE
Sharing host machine directories with vm

### ISSUE THREAD

**Issue by naveenrpp2017** [kubevirt/kubevirt#9533]
Hello,
       I am trying to create a VirtualMachine using Kubevirt and i want to share the host machine directory with VM, I have tried example given in "https://kubevirt.io/user-guide/virtual_machines/disks_and_volumes/#sharing-node-directories" under the topic **"Sharing Directories with VMs"** this was working fine.

But when i tried the sample example with Opensuse15.4 image the VM creation is happening and running successfully but the mount is not happening inside the vm and getting below error,
Error: mount: /mnt: unknown filesystem type 'virtiofs'

if this virtiofs is not supported in opensuse OS what FS i can use for it?
-------------------------------------------------------------------------------------------------------------------------------
used below yaml:

apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  labels:
    kubevirt.io/vm: hostpath-vm
  name: hostpath
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: hostpath
        kubevirt.io/vm: hostpath
    spec:
      domain:
        cpu:
          cores: 1
          sockets: 1
          threads: 1
        devices:
          filesystems:
            - name: vm-hostpath
              virtiofs: {}
          disks:
            - name: containerdisk
              disk:
                bus: virtio
          interfaces:
            - name: default
              masquerade: {}
          rng: {}
        resources:
          requests:
            memory: 1Gi
      networks:
        - name: default
          pod: {}
      terminationGracePeriodSeconds: 180
      volumes:
        - containerDisk:
            image: opensuse15:latest       #using image from my local registry
          name: containerdisk
        - name: vm-hostpath
          persistentVolumeClaim:
            claimName: hostpath-claim

-------------------------------------------------------------------------------------------------------------------------------
**Environment**:
- KubeVirt version (use `virtctl version`): v0.59.0
- Kubernetes version (use `kubectl version`): v1.26.2
- OS (e.g. from /etc/os-release): Ubuntu 22.04.2 LTS (Kubernetes-master)

**Comment by xpivarc** [comment]
The problem is that your Guest OS doesn't support virtiofs, please advise with the OS documentation.
@vasiliy-ul Maybe you can point out what version support virtiofs.
Note: Maybe we should bake this info into documentation.

**Comment by naveenrpp2017** [comment]
@xpivarc  Thanks for your Reply!
I guess the guest OS what you mentioned is about the OS which i am using in VM.
In that case i am using Opensuse15.4 OS
So if virtiofs filesystem is not supported for this OS is there any other filesystem available which i can use in my case?

**Comment by xpivarc** [comment]
No, you need the support of the Guest OS for virtiofs.

**Comment by vasiliy-ul** [comment]
@naveenrpp2017, run `sudo modprobe virtiofs` in the guest. After that, you can retry the mount
