### ISSUE TITLE
Guest VMs are not up, when Host VM OS is 22.04 and kernel 5.15

### ISSUE THREAD

**Issue by nvinnakota10** [kubevirt/kubevirt#9539]
**What happened**:
After upgrading the Host OS to ubuntu 22.04 and kernel 5.15.0-57-generic from ubuntu 20.04 and kernel 5.4.0-89-generic, We are seeing the Kubevirt images not up properly, due to which we are not able to login to the VMs.

We haven't seen the issue when the Host OS is ubuntu 20.04 and with kernel 5.4.0-89-generic.

ssh using the exposed Nodeport failed

virtctl console failed
-> If the guest vm is ubuntu, we are seeing softlock up issues.
-> If the guest VM is Centos, virtctl console is stuck with the message:
$ virtctl console vm-kernel-app-1 -n kubevirttest
Successfully connected to vm-kernel-app-1 console. The escape sequence is ^]

You were disconnected from the console. This has one of the following reasons:
 - another user connected to the console of the target vm
 - network issues
websocket: close 1006 (abnormal closure): unexpected EOF

**What you expected to happen**:

The guest VMs should be running and user should be able to get into the guest VMs without any issues.

User should be able to login to the kubevirt VMs without any issues, and virtctl console should show the below:

Successfully connected to vm-kernel-app-2 console. The escape sequence is ^]

CentOS Linux 7 (Core)
Kernel 3.10.0-957.12.2.el7.x86_64 on an x86_64

vm-kernel-app-2 login: 

**How to reproduce it (as minimally and precisely as possible)**:
Create Ubuntu 22.04 VM with kernel 5.15.0-57-generic,(issue seen on kernels 5.8+). 
Install k8s, kubevirt. 
Create VMs using kubevirt on the Ubuntu 22.04 VMs with kernel 5.15.

**Additional context**:
The kubernetes version and kubevirt remained the same. The issue is seen on kernels 5.8+.

The same VM spec worked on ubuntu 20.04, kernel: 5.4.0-89-generic. 
 

**Environment**:
- KubeVirt version (use `virtctl version`): 0.58
- Kubernetes version (use `kubectl version`): 1.25
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Ubuntu 22.04 (Host)/ Guest: Ubuntu 20.04
- Kernel (e.g. `uname -a`): Host: 5.15.0-57-generic
- Install tools: N/A
- Others: N/A

**Comment by alicefr** [comment]
@nvinnakota10 if you don't see the console, it might be that the VM hasn't booted. Could you please try to use `virtctl vnc <vm-name>`?  Can you also to look into virt-launcher log if there is something suspicious?

**Comment by nvinnakota10** [comment]
Hi @alicefr,  Yes, we are seeing the issue that the VM itself is not booted. 

Attaching the launcher pod logs. Both working and failed case. So far, I didn't see anything suspicious.
[launcher_pod_working_case.txt](https://github.com/kubevirt/kubevirt/files/11114573/launcher_pod_working_case.txt)
[launcher_pod.txt](https://github.com/kubevirt/kubevirt/files/11114574/launcher_pod.txt)

Both the guest kubevirt VMs are from the same image, they didn't have any change They were created on different hosts.

Like I mentioned, when I do the virtctl console <vm-name>, if the kubevirt guest VM is of Ubuntu we are seeing the below stack traces:

Successfully connected to vm-single-virtio console. The escape sequence is ^]


[  338.747039] watchdog: BUG: soft lockup - CPU#13 stuck for 22s! [systemd-udevd:248]
[  338.751321] Modules linked in: net_failover glue_helper failover libahci virtio_blk(+) virtio_scsi
[  338.755279] CPU: 13 PID: 248 Comm: systemd-udevd Tainted: G             L    5.4.0-122-generic #138-Ubuntu
[  338.763079] Hardware name: KubeVirt None/RHEL-AV, BIOS 1.15.0-1.module_el8.6.0+1087+b42c8331 04/01/2014
[  338.767391] RIP: 0010:smp_call_function_many+0x205/0x270
[  338.767391] Code: e8 10 5c 92 00 3b 05 ce c6 b0 01 89 c7 0f 83 9b fe ff ff 48 63 c7 48 8b 0b 48 03 0c c5 80 c9 04 85 8b 41 18 a8 01 74 0a f3 90 <8b> 51 18 83 e2 01 75 f6 eb c8 89 cf 48 c7 c2 a0 ba 84 85 4c 89 fe
[  338.783246] RSP: 0018:ffffa49ac06afab8 EFLAGS: 00000202 ORIG_RAX: ffffffffffffff13
[  338.783329] RAX: 0000000000000003 RBX: ffff954d7eb70d80 RCX: ffff954d7ea37420
[  338.791264] RDX: 0000000000000001 RSI: 0000000000000000 RDI: 0000000000000008
[  338.795154] RBP: ffffa49ac06afaf8 R08: ffff954d7e438cc8 R09: ffff954d7e438d18
[  338.799306] R10: ffff954d7e438cc8 R11: 0000000000000000 R12: ffffffff83c81720
[  338.799306] R13: ffff954d7eb6f740 R14: 0000000000000001 R15: 0000000000000010
[  338.807225] FS:  00007f1492e81880(0000) GS:ffff954d7eb40000(0000) knlGS:0000000000000000
[  338.811112] CS:  0010 DS: 0000 ES: 0000 CR0: 0000000080050033
[  338.815302] CR2: 000055612f896c28 CR3: 0000000035e56006 CR4: 0000000000360ee0
[  338.815302] Call Trace:
[  338.823230]  ? tlb_is_not_lazy+0x30/0x30
[  338.827100]  on_each_cpu+0x2d/0x60
[  338.827100]  flush_tlb_kernel_range+0x81/0x90
[  338.831298]  __purge_vmap_area_lazy+0x70/0x6d0
[  338.831298]  _vm_unmap_aliases+0xf5/0x130
[  338.831298]  vm_unmap_aliases+0x19/0x20
[  338.839270]  change_page_attr_set_clr+0xcf/0x200
[  338.843104]  set_memory_ro+0x29/0x30
[  338.843104]  ? 0xffffffffc040b000
[  338.847289]  frob_text.isra.0+0x23/0x30
[  338.847289]  module_enable_ro.part.0+0x67/0xd0
[  338.847289]  do_init_module+0x17e/0x240
[  338.855224]  load_module+0x11e6/0x1320
[  338.855224]  __do_sys_finit_module+0xbe/0x120
[  338.859097]  ? __do_sys_finit_module+0xbe/0x120
[  338.863290]  __x64_sys_finit_module+0x1a/0x20
[  338.863290]  do_syscall_64+0x57/0x190
[  338.863290]  entry_SYSCALL_64_after_hwframe+0x44/0xa9
[  338.871226] RIP: 0033:0x7f149340073d
[  338.871226] Code: 00 c3 66 2e 0f 1f 84 00 00 00 00 00 90 f3 0f 1e fa 48 89 f8 48 89 f7 48 89 d6 48 89 ca 4d 89 c2 4d 89 c8 4c 8b 4c 24 08 0f 05 <48> 3d 01 f0 ff ff 73 01 c3 48 8b 0d 23 37 0d 00 f7 d8 64 89 01 48
[  338.879295] RSP: 002b:00007ffca2786e68 EFLAGS: 00000246 ORIG_RAX: 0000000000000139
[  338.887228] RAX: ffffffffffffffda RBX: 000055612f8eaea0 RCX: 00007f149340073d
[  338.891101] RDX: 0000000000000000 RSI: 00007f14932e0ded RDI: 000000000000000c
[  338.895296] RBP: 0000000000020000 R08: 0000000000000000 R09: 000055612f8e75b8
[  338.903226] R10: 000000000000000c R11: 0000000000000246 R12: 00007f14932e0ded
[  338.907160] R13: 0000000000000000 R14: 000055612f8eeff0 R15: 000055612f8eaea0


-----------
This is the VM spec, we are using:

apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: vm-single-virtio
  namespace: kubevirttest
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: vm-single-virtio
        app: vm-single-virtio-app
    spec:
      nodeSelector:
        master: master
      terminationGracePeriodSeconds: 30
      domain:
        cpu:
          sockets: 1
          cores: 8
          threads: 2
          #dedicatedCpuPlacement: true
        memory:
          hugepages:
            pageSize: "1Gi"
        resources:
          requests:
            memory: "1Gi"
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            bridge: {}
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: svl-artifactory.juniper.net/atom-docker/dpdk-pktgen/vmdisks/pktgen:latest8
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=


We are using a ubuntu image loaded with some dpdk application compiled on it. We are kind of stuck on what the issue is. Can you please suggest if we can verify any requirement, that might be missing here.

Thanks.

**Comment by nvinnakota10** [comment]
@alicefr , @rmohr ,

The host is a kubevirt VM created on top of a BMS.

The BMS is ubuntu 20.04 with kernel 5.4.
When I create a host VM with ubuntu 20.04 and kernel 5.4, I am able to use nested virtualization and create a VM on top of the host VM.

However, if I create a host VM with ubuntu 22.04 and kernel 5.15 or ubuntu 20.04 and kernel 5.8+, I am seeing the issue where the guest VM will not boot. However, if I use software emulation, the guest VMs are able to boot if I use bridge interfaces.

Can you please help me with the issue.

**Comment by scydas** [comment]
I'm having the same problem.

**Comment by victortoso** [comment]
> I'm having the same problem.

This issue is more than a year old and was related to a specific kernel version. Would you mind opening a new bug describing what is going on, how to reproduce it, which versions you have running, etc.

**Comment by scydas** [comment]
https://github.com/kubevirt/kubevirt/issues/11920
