### ISSUE TITLE
golangci configuration contains deprecated/non-working linters

### ISSUE THREAD

**Issue by 0xFelix** [kubevirt/kubevirt#9541]
**What happened**:

Following warnings are shown during `make lint`:

```
WARN [linters context] bodyclose is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
WARN [linters context] noctx is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
WARN [linters context] rowserrcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
WARN [linters context] structcheck is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
WARN [linters context] unparam is disabled because of go1.18. You can track the evolution of the go1.18 support by following the https://github.com/golangci/golangci-lint/issues/2649.
```

**What you expected to happen**:

No warnings should be shown during `make lint`.

**How to reproduce it (as minimally and precisely as possible)**:

Run `make lint`.

**Additional context**:

A similar issue is tracked in https://github.com/kubevirt/containerdisks/issues/55.

**Environment**:
- KubeVirt version (use `virtctl version`): main
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by EdDev** [comment]
@0xFelix , I posted a PR to bump golangci and remove the unsupported linters.
