### ISSUE TITLE
Add yamllint to CI

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#955]
It happens that we are using yaml files.

For a better presentation - and showing good citizen ship - we should follow some standards. Yamllint can help us to stick to them.

But running yamllint today causes many errors and warnings, try:

```
 find . -name \*.yaml | xargs yamllint
```

This issue is about fixing those wanrings and adding yamllint to .travis.yml

**Comment by bhavin192** [comment]
I would like to work on this.

**Comment by fabiand** [comment]
That's cool! It's all yours :)

Do you need anything else to start?

**Comment by rmohr** [comment]
Can this also format our yaml files? 

I would welcome everything which formats yamls in an automated way. Travis can then simply check if they are unformatted and fail.

So if it involves autoformatting, then I am all for it. Just a check which then requires manual formatting of already valid things is a no-go for me.

Checking for syntax errors alone works for me to if there exists no reasonable formatter.

**Comment by bhavin192** [comment]
@rmohr sadly after searching a while found no yaml formatter 
@fabiand what should be maximum line-length for our yaml files ?

**Comment by fabiand** [comment]
@bhavin192 stock 80 characters

**Comment by fabiand** [comment]
@bhavin192 Try this formatter, it worked for me on some files: https://gist.github.com/ingydotnet/3920656

**Comment by bhavin192** [comment]
After searching more, found two ways to auto format the `yaml` files, one is [`pyaml`](https://github.com/mk-fg/pretty-yaml) and other is a [VSCode extension](https://marketplace.visualstudio.com/items?itemName=redhat.vscode-yaml). Both of these don't work on `.yaml.in` files, even `yamllint` fails to lint `.yaml.in` files.
For `yaml` files (files without go templates) VSCode extension works in better way.

**Comment by fabiand** [comment]
@bhavin192 heya! Just checking if there is something we can give a hand with?

**Comment by bhavin192** [comment]
@fabiand I was trying to find something which will do the work of formatting in automated way. YAML editor of OpenShift Origin does auto formatting, but it seems it uses same method as of the VSCode extension. Will do the formatting with the VSCode extension and add `yamllint` to CI

**Comment by bhavin192** [comment]
@fabiand @rmohr I'm almost done with formatting all the yaml and yaml.in files (with some manual work) we just have only one error at these lines 
https://github.com/kubevirt/kubevirt/blob/master/manifests/release/kubevirt.yaml.in#L512-L515

```sh
  514:1     error    syntax error: could not find expected ':'
```
Any idea what can be done for this?

**Comment by bhavin192** [comment]
Yes, it's possible to skip particular sections of YAML with comments, 
http://yamllint.readthedocs.io/en/stable/disable_with_comments.html

**Comment by rmohr** [comment]
@bhavin192 first thanks for investing your time.

As said in the beginning, I don't think that this task is useful:

 * Line length is really irrelevant in my eyes (especially a length of 80?), we are not going to print them (also pretty much any editor has syntax highlighting and softwrap)
 * Many of the linter warnings are about the indenting of arrays and dict entries and yamllint advertises a different formatting style than e.g. https://kubernetes.io/docs/
 * The files will be more and more generated (at the end they will all come from go structs), so no one will have to edit them by hand anyway. Working on moving the manifest over to go structs would be more helpful
 * If debugging on the yaml files, it is very likely that you will also have to look on the k8s objects from the cluster. These files will not keep the format. They will then simply look like when we serialize them from go structs in the first place. So it may be even more helpful to make sure that they always look like the apiserver would return them.

`showing good citizen ship` is nice, but I would prefer if we do that where it makes sense.  Although I find this task not useful, I could have lived with it if it would have been an absolute nobrainer (like e.g. using goimports or shfmt), but I think we can save you some time here.
