### ISSUE TITLE
Kubevirt VMI Creation with HostDisk is giving SyncFailed error

### ISSUE THREAD

**Issue by naveenrpp2017** [kubevirt/kubevirt#9550]
Hi,
   I am trying to create a kubevirt VMI with guest os ubuntu22.04 along with it trying to create a hostdisk volume. I am using the below yaml file for this.
=====================================================================================
metadata:
  name: testvmi-containerdisk
apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
spec:
  domain:
    resources:
      requests:
        memory: 105Gi
        cpu: 30
    devices:
      disks:
      - name: containerdisk
        disk: {}
      - name: cloudinitdisk
        disk:
          bus: virtio
      - name: rootdisk
        disk:
          bus: virtio
  volumes:
    - name: containerdisk
      containerDisk:
        image: quay.io/containerdisks/ubuntu:22.04
        imagePullPolicy: IfNotPresent
    - cloudInitNoCloud:
       userData: |-
         #cloud-config
         chpasswd:
           expire: false
         password: password
         user: fedora
      name: cloudinitdisk
    - name: rootdisk
      hostDisk:
       path: /mnt
       type: DiskOrCreate

=====================================================================================

While applying the above yaml file Virt-laucher is runnig fine below is the output when i describe virt-laucher pod:

Events:
  Type    Reason     Age   From               Message
  ----    ------     ----  ----               -------
  Normal  Scheduled  22s   default-scheduler  Successfully assigned default/virt-launcher-testvmi-containerdisk-8w8kf to kubernetes-worker01
  Normal  Pulled     21s   kubelet            Container image "quay.io/kubevirt/virt-launcher:v0.59.0" already present on machine
  Normal  Created    21s   kubelet            Created container container-disk-binary
  Normal  Started    21s   kubelet            Started container container-disk-binary
  Normal  Pulled     20s   kubelet            Container image "quay.io/containerdisks/ubuntu:22.04" already present on machine
  Normal  Created    20s   kubelet            Created container volumecontainerdisk-init
  Normal  Started    20s   kubelet            Started container volumecontainerdisk-init
  Normal  Pulled     19s   kubelet            Container image "quay.io/kubevirt/virt-launcher:v0.59.0" already present on machine
  Normal  Created    19s   kubelet            Created container compute
  Normal  Started    19s   kubelet            Started container compute
  Normal  Pulled     19s   kubelet            Container image "quay.io/containerdisks/ubuntu:22.04" already present on machine
  Normal  Created    19s   kubelet            Created container volumecontainerdisk
  Normal  Started    19s   kubelet            Started container volumecontainerdisk

But VMI is not going to running state and getting below error when i describe the VMI:

Events:
  Type     Reason            Age                    From                       Message
  ----     ------            ----                   ----                       -------
  Normal   SuccessfulCreate  4m48s                  virtualmachine-controller  Created virtual machine pod virt-launcher-testvmi-containerdisk-8w8kf
  Warning  SyncFailed        4m43s                  virt-handler               server error. command SyncVMI failed: "LibvirtError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2023-03-31T06:56:34.557449Z qemu-kvm: -blockdev {\"driver\":\"file\",\"filename\":\"/var/run/kubevirt-private/vmi-disks/rootdisk/mnt\",\"node-name\":\"libvirt-1-storage\",\"cache\":{\"direct\":false,\"no-flush\":false},\"auto-read-only\":true,\"discard\":\"unmap\"}: 'file' driver requires '/var/run/kubevirt-private/vmi-disks/rootdisk/mnt' to be a regular file')"
  Warning  SyncFailed        4m43s                  virt-handler               server error. command SyncVMI failed: "LibvirtError(Code=1, Domain=10, Message='internal error: process exited while connecting to monitor: 2023-03-31T06:56:34.926927Z qemu-kvm: -blockdev {\"driver\":\"file\",\"filename\":\"/var/run/kubevirt-private/vmi-disks/rootdisk/mnt\",\"node-name\":\"libvirt-1-storage\",\"cache\":{\"direct\":false,\"no-flush\":false},\"auto-read-only\":true,\"discard\":\"unmap\"}: 'file' driver requires '/var/run/kubevirt-private/vmi-disks/rootdisk/mnt' to be a regular file')"

======================================================================================
**Environment**:
- KubeVirt version (use `virtctl version`): v0.59.0
- Kubernetes version (use `kubectl version`):  v1.26.2
- VM or VMI specifications: ubuntu:22.04

**Comment by alicefr** [comment]
First, try to have a look to this [guide](https://github.com/kubevirt/user-guide/blob/main/docs/virtual_machines/disks_and_volumes.md#sharing-node-directories). Additionally, I think you need to run the VM with root, otherwise the pod doesn't have the permission to right into the host path directory. Either you find the permission manually on the node, or you can enable root VM with the feature gate `Root`
