### ISSUE TITLE
Running Virt-Handler container

### ISSUE THREAD

**Issue by Gre8t** [kubevirt/kubevirt#9561]
**Description**:
Following the README.md guide on launching a Virt-handler using Docker proved abortive. I ran into an issue that demanded a Pod IP before it can start. Error message 
`panic: no pod ip detected

goroutine 1 [running]:
main.(*virtHandlerApp).Run(0xc000493380)
	cmd/virt-handler/virt-handler.go:167 +0x26fb
main.main()
	cmd/virt-handler/virt-handler.go:488 +0x6e
`
**What you expected**:
The README.md should be able to guide anyone trying to contribute to KubeVirt for the first time. Either it is taken out or updated. 

**URL**:
[Link to Documentation](https://github.com/kubevirt/kubevirt/blob/main/cmd/virt-handler/README.md)

**Additional context**:
Attached is a screenshot of the error:
![image](https://user-images.githubusercontent.com/20660598/229348589-e821a726-4f7c-40b2-921f-56877dba3e5b.png)
After building the code, the same Pod IP error persisted. Decided to take a look at the image in dockerhub, I found out that the Image is 2 years old and in no way works according to this Doc.

**Comment by alicefr** [comment]
@Gre8t probably we should remove this doc. I find it hard launching virt-handler standalone without a Kubernetes cluster.
@stu-gott @fossedihelm you are the only contributors to [that file](https://github.com/kubevirt/kubevirt/commits/main/cmd/virt-handler/README.md) and it seems quite outdated. Should we simply remove it?

**Comment by Gre8t** [comment]
@alicefr I thought the same as well.

**Comment by fossedihelm** [comment]
@alicefr @Gre8t I agree. I should have done it when switching to `virtqemud`, but probably I missed it. At most it would certainly need to be updated.

**Comment by EdDev** [comment]
@fossedihelm , @alicefr , this issue is stale for some time now.
Can we just send a PR to remove the file or the specific content?

**Comment by fossedihelm** [comment]
@EdDev thanks for the remind! I will send a PR tomorrow if it fit for you
