### ISSUE TITLE
VM ReplicaSet and Selector

### ISSUE THREAD

**Issue by tripledes** [kubevirt/kubevirt#957]
Checking out the [code for the controller](https://github.com/kubevirt/kubevirt/blob/master/pkg/virt-controller/watch/replicaset.go#L162-L165), `selector` seems to be required while the [documentation](http://www.kubevirt.io/api-reference/master/definitions.html#_v1_vmreplicasetspec) says it's optional.

```golang
if rs.Spec.Template == nil || rs.Spec.Selector == nil || len(rs.Spec.Template.ObjectMeta.Labels) == 0 {
	logger.Error("Invalid controller spec, will not re-enqueue.")
	return nil
}
```

Found myself in the situation that the VMRS was created, but the VM was not starting and the controller was logging out the error on the snippet.

**Comment by rmohr** [comment]
@tripledes thanks for reporting. Sorry that you had to wait so long to get a response.

**Comment by tripledes** [comment]
@rmohr thanks! :ok_hand:
