### ISSUE TITLE
Phase transition metrics should include a corresponding node name

### ISSUE THREAD

**Issue by knopt** [kubevirt/kubevirt#9577]
**Is your feature request related to a problem? Please describe**:

`kubevirt_vmi_phase_transition_time_seconds` is a very useful metric, which can be used to monitor both time of phase transition of VMIs, as well as success rate of VMIs transitions from a each phase to the next expected phase (like `Scheduling` -> `Scheduled`).

However, to provide more granularity into monitoring, and troubleshooting failures and unexpected delays, the exposed metric `kubevirt_vmi_phase_transition_time_seconds` should have `node_name` label, which would inform, which node an VMI is assigned to. This information will be useful for instance for `Scheduled` and `Running` phases. However, for phases like `Created` `node_name` label does not make sense, as VMI does not have any node assigned yet. Hence, I propose the value of `node_name` label to be empty for such cases.

**Describe the solution you'd like**:

I'd like the following, existing definition:
```
	histogramVec := prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "kubevirt_vmi_phase_transition_time_seconds",
			Buckets: phaseTransitionTimeBuckets(),
		},
		[]string{
			// phase of the vmi
			"phase",
			// last phase of the vmi
			"last_phase",
		},
	)
```
to be changed to
```
	histogramVec := prometheus.NewHistogramVec(
		prometheus.HistogramOpts{
			Name:    "kubevirt_vmi_phase_transition_time_seconds",
			Buckets: phaseTransitionTimeBuckets(),
		},
		[]string{
			// phase of the vmi
			"phase",
			// last phase of the vmi
			"last_phase",
                       // corresponding node to the vmi
                       "node_name"
		},
	)
```

The informers used to update the metric already have the information about corresponding node name, so this enhancement does not need to extend any other logic.

**Describe alternatives you've considered**:

An alternative that provides similar user experience is creating a new metric, however it's arguable if it's actually necessary and wanted, as introduces unnecessary complexity into the metrics.

**Additional context**:

Once could claim that this is a breaking change, as users might rely on the particular definition of the metric. This is true, however fixes to the queries using the existing metric definition are very likely to be straightforward. Likely majority of queries using the metric, using the aggregations like `sum` might not need any changes at all

**Comment by knopt** [comment]
I'm happy to implement this improvement once we agree on the approach, thanks!

**Comment by knopt** [comment]
@davidvossel do you know who I could discuss this improvement with?

**Comment by rthallisey** [comment]
@knopt I think your proposal is going in the right direction.  It's worth taking this to a pull request

**Comment by knopt** [comment]
@xpivarc do you have any thoughts?

**Comment by knopt** [comment]
@xpivarc @sradco any thoughts on this?

**Comment by xpivarc** [comment]
Sounds good to me, I can see how this helps to identify "worse performing nodes"

**Comment by sradco** [comment]
Hi @knopt, this looks good to me.
