### ISSUE TITLE
Hot Add Feature

### ISSUE THREAD

**Issue by sudharsanomprakash** [kubevirt/kubevirt#9582]
**Is your feature request related to a problem? Please describe**:
Hot add feature isn't available. VM has to be manually rebooted after editing cpu and memory spec.

**Describe the solution you'd like**:
Scale UP VM's CPU and Memory without reboot of VM

**Describe alternatives you've considered**:
N/A

**Additional context**:
N/A

**Comment by alicefr** [comment]
Please, have a look to this [design proposal](https://github.com/kubevirt/community/pull/212)

**Comment by EdDev** [comment]
@sudharsanomprakash , @alicefr , can this issue be closed?
