### ISSUE TITLE
VM Migration didn't happen while network Interfaces are down

### ISSUE THREAD

**Issue by sudharsanomprakash** [kubevirt/kubevirt#9586]
**What happened**:
Using Multus with ovs bridge for VM's network interface. Everything works fine, but when both slave ports are down in a Host the VM migration wont happen. 

**What you expected to happen**:
Detect the Port Down and VM's should be migrated to another available Host.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy Multus with ovs using network-attachment-definitions
Deploy VM using above network
Login into Host and run, ip link set eno1 down ; ip link set eno2 down

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by xpivarc** [comment]
What solution does behave like this?

**Comment by sudharsanomprakash** [comment]
In past, I had oVirt that was configured with guest vlan's which was trucked on interface eth0 and eth1 (bonded&bridged) , when both the interfaces was made down on Host1. ovirt-engine identified that the interface is down and performed guest VM migration to Host2(healthy host).

Here in kubevirt, i was simulating same scenario with two worker node(node1 and node2). I have two worker nodes configure with guest vlan which is trucked on interface eth0 and eth1 (bonded&bridged) using ovs. I made both the interfaces down on node1 and expected the vm migration would occur, but didn't happen

I understand it is not apple to apple comparison, but I guess this very common scenario for both interfaces to go down.

**Comment by EdDev** [comment]
This seems to define an enhancement on when to trigger a migration.
Unlike oVirt, the network components on the host are not managed by kubevirt.

If you will like to suggest an enhancement, there is a need to generalize the requested feature and open an issue for enhancement.

/sig network

**Comment by EdDev** [comment]
This topic should be handled through an enhancement request which is well reasoned and generalized.

Closing this one for now.

/close
