### ISSUE TITLE
Can LiveMigration keep VMI IP unchanged

### ISSUE THREAD

**Issue by LLLLLBJ** [kubevirt/kubevirt#9589]
**Is your feature request related to a problem? Please describe**:
There are two virt-launcher pods running during live-migration doing, the two pods can not use the same IP with multus CNI ?

**Describe the solution you'd like**:

**Describe alternatives you've considered**:

**Additional context**:

**Comment by sudharsanomprakash** [comment]
Using Multus, the two virt-launcher pods cannot use the same IP address during the live migration.

But why you need to maintain same IP? 

Are you using internal pod IP space for VM's or external like vlan?

Can you post your VM definition?
