### ISSUE TITLE
Set 'causes' list for requests rejected by validation webhook

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#959]
UI's need the ability to identify exactly which fields were rejected. We can provide this information in the 'causes' field in the status object the webhook returns during rejection. 

Example:  POST of a VM spec that is invalid would get this JSON response.  The causes list should point to exactly what field caused the issue with a human readable message that applies to that field. 
```
{
  "kind": "Status",
  "apiVersion": "v1",
  "metadata": {},
  "status": "Failure",
  "message": "admission webhook \"virtualmachine-validator.kubevirt.io\" denied the request: spec.domain.devices.disks[1].volumeName testvolume not found.",
  "details": {
    "causes": [
      {
        "message": "testvolume not found",
        "field": spec.domain.devices.disks[1],
      },
    ]
  },
  "code": 422
}
```

**Comment by jniederm** [comment]
Hi, aforementioned format looks like a good start. My comments:

* `details.causes[0].field` is of type string, right?
*  `code` 422 relates to HTTP status codes and means "Unprocessable Entity", basically validation error, right?
* Does the document of kind `Status` describe single validation problem or the fact there is one or more validation problems in validated document? We'd need for the response to contain as much validation errors as possible. It would be very exhausting for users to iteratively fix issues one by one. And related question: What does the top level `message` property describe?
* I guess it can be helpful if the `cause` can contain more than one field reference. Some errors might be result of interdependent fields. Example from oVirt: VM has properties memory and maxMemory. Both can be in valid range however if `memory > maxMemory` it's a validation problem - [libvirt memory allocation][1].

[1]: https://libvirt.org/formatdomain.html#elementsMemoryAllocation

**Comment by davidvossel** [comment]
> details.causes[0].field is of type string, right?

correct

> code 422 relates to HTTP status codes and means "Unprocessable Entity", basically validation error, right?

yes, and only expect to get "causes" for invalid entries when http code is 422. 

> Does the document of kind Status describe single validation problem or the fact there is one or more validation problems in validated document? We'd need for the response to contain as much validation errors as possible. It would be very exhausting for users to iteratively fix issues one by one. 

Causes will be a list and will contain every validation issue encountered by our webhook. 

> And related question: What does the top level message property describe?

I use top level message as a global aggregate of all the errors.  Kubectl displays that message to the user.  It's not really useful for the UI right now. 

> I guess it can be helpful if the cause can contain more than one field reference. Some errors might be result of interdependent fields. Example from oVirt: VM has properties memory and maxMemory. Both can be in valid range however if memory > maxMemory it's a validation problem - libvirt memory allocation.

If this occurred, you'd likely get an error 'cause' for both memory and maxMemory.  The 'memory' error would say something like "memory can not be greater than maxMemory" and the 'maxMemory' errror would be the inverse of that.
