### ISSUE TITLE
Create VirtualMachine failed, the state of dv is blocked in CloneInProgress

### ISSUE THREAD

**Issue by zhangzhangzf** [kubevirt/kubevirt#9592]
**What happened**:
I create a new VM. It work well when my cdi verison is 1.45.0. Upgrade cdi to 1.56.0. Create a VM again, VM status block in Provisioning.
[root@VM-8-157-centos /home/zyh/vm]# kubectl get vm
NAME     AGE       STATUS              READY
hhh         21m       Provisioning       False

[root@VM-8-157-centos /home/zyh/vm]# kubectl get pvc |grep hhh
datavolume1.hhh      Bound         pvc-aa4deeff-c870-4c79-bb0f-83845eb28a2b   20Gi       RWX            csi-rbd-sc     21m
rootfs.hhh                 Bound         pvc-e5ddc20c-abaf-4185-802c-bf8b3df67a37   20Gi       RWX            csi-rbd-sc     21m

[root@VM-8-157-centos /home/zyh/vm]# kubectl get dv
NAME              PHASE                    PROGRESS   RESTARTS   AGE
rootfs.hhh       CloneInProgress           N/A             9               22m

[root@VM-8-157-centos ~]# kubectl logs  -n cdi cdi-deployment-56c95c4c-w8qqs
{"level":"debug","ts":1680946366.3799841,"logger":"controller.import-controller","msg":"reconciling Import PVCs","PVC":"default/rootfs.hhh"}
{"level":"debug","ts":1680946366.3800244,"logger":"controller.import-controller","msg":"PVC annotation not found, skipping pvc","PVC":"default/rootfs.hhh","annotation":"cdi.kubevirt.io/storage.import.endpoint"}

**What you expected to happen**:
VirtualMachine is running.

**Environment**:
- KubeVirt version (use `virtctl version`): v0.50.0
- CDI version: 1.56.0
- Kubernetes version (use `kubectl version`): v1.21.4

**Comment by sudharsanomprakash** [comment]
Can you describe the DV and PVC, post the events here?

**Comment by zhangzhangzf** [comment]
> Can you describe the DV and PVC, post the events here?

<img width="1462" alt="企业微信截图_9f917063-a132-46e0-b9f5-aacf377a3e23" src="https://user-images.githubusercontent.com/32992253/230756176-0c93ced7-ae6d-4705-b0f7-73aa2a5e1405.png">

**Comment by sudharsanomprakash** [comment]
Are you using volumeMode=block? 
Can you post your VM definition? 
what is the output you get when you run  `kubevirt describe dv rootfs.hhh`

**Comment by zhangzhangzf** [comment]
> Are you using volumeMode=block? Can you post your VM definition? what is the output you get when you run `kubevirt describe dv rootfs.hhh`

yes,volumeMode=block. Os image data source is PVC.
`[root@VM-8-157-centos /home/cdi]# kubectl get vm qwe -o yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    description: ""
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
    tkestack.io/image-display-name: Windows Server 2016 64位
  creationTimestamp: "2023-04-10T03:52:17Z"
  generation: 1
  labels:
    kubevirt.io/domain: qwe
  name: qwe
  namespace: default
  resourceVersion: "35009929"
  uid: c98da7e7-3156-4dbf-9b3c-2188c500210a
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: rootfs.qwe
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 20Gi
        storageClassName: csi-rbd-sc
        volumeMode: Block
      source:
        pvc:
          name: win-img
          namespace: kube-public
  - metadata:
      creationTimestamp: null
      name: datavolume1.qwe
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
        storageClassName: csi-rbd-sc
        volumeMode: Block
      source:
        blank: {}
  running: true
  template:
    metadata:
      annotations:
        tkestack.io/image-display-name: Windows Server 2016 64位
      creationTimestamp: null
      labels:
        kubevirt.io/domain: qwe
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: rootfs
          - bootOrder: 2
            disk:
              bus: virtio
            name: datavolume1
          inputs:
          - bus: usb
            name: tablet
            type: tablet
          interfaces:
          - bridge: {}
            model: virtio
            name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 4G
      networks:
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: rootfs.qwe
        name: rootfs
      - dataVolume:
          name: datavolume1.qwe
        name: datavolume1
status:
  conditions:
  - lastProbeTime: "2023-04-10T03:52:19Z"
    lastTransitionTime: "2023-04-10T03:52:19Z"
    message: VMI does not exist
    reason: VMINotExists
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-04-10T03:52:19Z"
    message: 'Error encountered while creating DataVolumes: Failed to create DataVolume:
      admission webhook "datavolume-validate.cdi.kubevirt.io" denied the request:  Destination
      PVC default/datavolume1.qwe already exists'
    reason: FailedCreate
    status: "True"
    type: Failure
  printableStatus: Provisioning
  volumeSnapshotStatuses:
  - enabled: true
    name: rootfs
  - enabled: false
    name: datavolume1
    reason: DV 'default/datavolume1.qwe' not found`
===============================================
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    cdi.kubevirt.io/cloneType: network
    cdi.kubevirt.io/storage.clone.token: eyJhbGciOiJQUzI1NiJ9.eyJleHAiOjE2ODEwOTkwMzcsImlhdCI6MTY4MTA5ODczNywiaXNzIjoiY2RpLWFwaXNlcnZlciIsIm5hbWUiOiJ3aW4taW1nIiwibmFtZXNwYWNlIjoia3ViZSdaWMiLCJuYmYiOjE2ODEwOTgMzcsIm9wZXJ0YXRpb24iOiJDbG9uZSIsInBhcmFtcyI6eyJ0YXJnZXROYW1lIjoicm9vdGZzLnF3ZSIsInRhcmdldE5hbWVzcGFjZSI6ImRlZmF1bHQifSwicmVzb3VyY2UiOnsiZ3JvdXAiOiIiLCJyZXNvdXJjZSI6InBlcnNpc3RlbnR2b2x1bWVjbGFpbXMiLCJ2ZXJzaW9uIjoidjEifX0.jDkMUpDz9j7wr4QTmq1q_Cxi-PTzdwxKuvBkdVDh9MWJTSdP1wXyDzBLMLjwA6czG-id_Hxk1lqoerV9nzFNPtKrXhZpQVfK2idgJB3yn6ZncvhPDL1BQlubym0pWAx2QPWFEeXQqvym_kyZV_E2FAkSy4ZbrmbmKunu1yMeL8h2hy0cXFnpEPfpUtUsTd4LYAMyTnvNCyVKiC5FzTu8OhMTfOQeT8RvcBNFOk8pybO5Yvpd021sWy7FkFB8YLh_Efc7vhGYvfdDgUbk5p64leIIrfi-wFqXxnGHPIB_xeWDNWm3QphfmkIhimAibV0jD-h0PFM7bmkC4pTAxvw
    cdi.kubevirt.io/storage.deleteAfterCompletion: "true"
  creationTimestamp: "2023-04-10T03:52:17Z"
  generation: 1299
  labels:
    kubevirt.io/created-by: c98da7e7-3156-4dbf-9b3c-2188c500210a
  name: rootfs.qwe
  namespace: default
  ownerReferences:
  - apiVersion: kubevirt.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachine
    name: qwe
    uid: c98da7e7-3156-4dbf-9b3c-2188c500210a
  resourceVersion: "35017871"
  uid: bf986f1c-0b40-464b-b3e1-6a46ba386766
spec:
  pvc:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 20Gi
    storageClassName: csi-rbd-sc
    volumeMode: Block
  source:
    pvc:
      name: win-img
      namespace: kube-public
status:
  claimName: rootfs.qwe
  conditions:
  - lastHeartbeatTime: "2023-04-10T03:52:18Z"
    lastTransitionTime: "2023-04-10T03:52:18Z"
    message: PVC rootfs.qwe Bound
    reason: Bound
    status: "True"
    type: Bound
  - lastHeartbeatTime: "2023-04-10T03:54:51Z"
    lastTransitionTime: "2023-04-10T03:52:18Z"
    reason: TransferRunning
    status: "False"
    type: Ready
  - lastHeartbeatTime: "2023-04-10T03:54:51Z"
    lastTransitionTime: "2023-04-10T03:54:51Z"
    reason: Pod is running
    status: "True"
    type: Running
  phase: CloneInProgress
  progress: N/A
  restartCount: 4

**Comment by zhangzhangzf** [comment]
> > Are you using volumeMode=block? Can you post your VM definition? what is the output you get when you run `kubevirt describe dv rootfs.hhh`
> The previous virtual machine was deleted, and a new virtual machine named qwe was created. The phenomenon is consistent. The system image that needs to clone data from PVC has always been in CloneInProgress state.
> yes,volumeMode=block. Os image data source is PVC. `[root@VM-8-157-centos /home/cdi]# kubectl get vm qwe -o yaml apiVersion: kubevirt.io/v1 kind: VirtualMachine metadata: annotations: description: "" kubevirt.io/latest-observed-api-version: v1 kubevirt.io/storage-observed-api-version: v1alpha3 tkestack.io/image-display-name: Windows Server 2016 64位 creationTimestamp: "2023-04-10T03:52:17Z" generation: 1 labels: kubevirt.io/domain: qwe name: qwe namespace: default resourceVersion: "35009929" uid: c98da7e7-3156-4dbf-9b3c-2188c500210a spec: dataVolumeTemplates:
> 
> * metadata:
>   creationTimestamp: null
>   name: rootfs.qwe
>   spec:
>   pvc:
>   accessModes:
>   - ReadWriteMany
>   resources:
>   requests:
>   storage: 20Gi
>   storageClassName: csi-rbd-sc
>   volumeMode: Block
>   source:
>   pvc:
>   name: win-img
>   namespace: kube-public
> * metadata:
>   creationTimestamp: null
>   name: datavolume1.qwe
>   spec:
>   pvc:
>   accessModes:
>   - ReadWriteMany
>   resources:
>   requests:
>   storage: 10Gi
>   storageClassName: csi-rbd-sc
>   volumeMode: Block
>   source:
>   blank: {}
>   running: true
>   template:
>   metadata:
>   annotations:
>   tkestack.io/image-display-name: Windows Server 2016 64位
>   creationTimestamp: null
>   labels:
>   kubevirt.io/domain: qwe
>   spec:
>   domain:
>   cpu:
>   cores: 4
>   devices:
>   disks:
>   - bootOrder: 1
>   disk:
>   bus: virtio
>   name: rootfs
>   - bootOrder: 2
>   disk:
>   bus: virtio
>   name: datavolume1
>   inputs:
>   - bus: usb
>   name: tablet
>   type: tablet
>   interfaces:
>   - bridge: {}
>   model: virtio
>   name: default
>   machine:
>   type: q35
>   resources:
>   requests:
>   memory: 4G
>   networks:
>   
>   * name: default
>     pod: {}
>     volumes:
>   * dataVolume:
>     name: rootfs.qwe
>     name: rootfs
>   * dataVolume:
>     name: datavolume1.qwe
>     name: datavolume1
>     status:
>     conditions:
> * lastProbeTime: "2023-04-10T03:52:19Z"
>   lastTransitionTime: "2023-04-10T03:52:19Z"
>   message: VMI does not exist
>   reason: VMINotExists
>   status: "False"
>   type: Ready
> * lastProbeTime: null
>   lastTransitionTime: "2023-04-10T03:52:19Z"
>   message: 'Error encountered while creating DataVolumes: Failed to create DataVolume:
>   admission webhook "datavolume-validate.cdi.kubevirt.io" denied the request:  Destination
>   PVC default/datavolume1.qwe already exists'
>   reason: FailedCreate
>   status: "True"
>   type: Failure
>   printableStatus: Provisioning
>   volumeSnapshotStatuses:
> * enabled: true
>   name: rootfs
> * enabled: false
>   name: datavolume1
>   reason: DV 'default/datavolume1.qwe' not found`
>   ===============================================
>   apiVersion: cdi.kubevirt.io/v1beta1
>   kind: DataVolume
>   metadata:
>   annotations:
>   cdi.kubevirt.io/cloneType: network
>   cdi.kubevirt.io/storage.clone.token: eyJhbGciOiJQUzI1NiJ9.eyJleHAiOjE2ODEwOTkwMzcsImlhdCI6MTY4MTA5ODczNywiaXNzIjoiY2RpLWFwaXNlcnZlciIsIm5hbWUiOiJ3aW4taW1nIiwibmFtZXNwYWNlIjoia3ViZSdaWMiLCJuYmYiOjE2ODEwOTgMzcsIm9wZXJ0YXRpb24iOiJDbG9uZSIsInBhcmFtcyI6eyJ0YXJnZXROYW1lIjoicm9vdGZzLnF3ZSIsInRhcmdldE5hbWVzcGFjZSI6ImRlZmF1bHQifSwicmVzb3VyY2UiOnsiZ3JvdXAiOiIiLCJyZXNvdXJjZSI6InBlcnNpc3RlbnR2b2x1bWVjbGFpbXMiLCJ2ZXJzaW9uIjoidjEifX0.jDkMUpDz9j7wr4QTmq1q_Cxi-PTzdwxKuvBkdVDh9MWJTSdP1wXyDzBLMLjwA6czG-id_Hxk1lqoerV9nzFNPtKrXhZpQVfK2idgJB3yn6ZncvhPDL1BQlubym0pWAx2QPWFEeXQqvym_kyZV_E2FAkSy4ZbrmbmKunu1yMeL8h2hy0cXFnpEPfpUtUsTd4LYAMyTnvNCyVKiC5FzTu8OhMTfOQeT8RvcBNFOk8pybO5Yvpd021sWy7FkFB8YLh_Efc7vhGYvfdDgUbk5p64leIIrfi-wFqXxnGHPIB_xeWDNWm3QphfmkIhimAibV0jD-h0PFM7bmkC4pTAxvw
>   cdi.kubevirt.io/storage.deleteAfterCompletion: "true"
>   creationTimestamp: "2023-04-10T03:52:17Z"
>   generation: 1299
>   labels:
>   kubevirt.io/created-by: c98da7e7-3156-4dbf-9b3c-2188c500210a
>   name: rootfs.qwe
>   namespace: default
>   ownerReferences:
> * apiVersion: kubevirt.io/v1
>   blockOwnerDeletion: true
>   controller: true
>   kind: VirtualMachine
>   name: qwe
>   uid: c98da7e7-3156-4dbf-9b3c-2188c500210a
>   resourceVersion: "35017871"
>   uid: bf986f1c-0b40-464b-b3e1-6a46ba386766
>   spec:
>   pvc:
>   accessModes:
>   
>   * ReadWriteMany
>     resources:
>     requests:
>     storage: 20Gi
>     storageClassName: csi-rbd-sc
>     volumeMode: Block
>     source:
>     pvc:
>     name: win-img
>     namespace: kube-public
>     status:
>     claimName: rootfs.qwe
>     conditions:
> * lastHeartbeatTime: "2023-04-10T03:52:18Z"
>   lastTransitionTime: "2023-04-10T03:52:18Z"
>   message: PVC rootfs.qwe Bound
>   reason: Bound
>   status: "True"
>   type: Bound
> * lastHeartbeatTime: "2023-04-10T03:54:51Z"
>   lastTransitionTime: "2023-04-10T03:52:18Z"
>   reason: TransferRunning
>   status: "False"
>   type: Ready
> * lastHeartbeatTime: "2023-04-10T03:54:51Z"
>   lastTransitionTime: "2023-04-10T03:54:51Z"
>   reason: Pod is running
>   status: "True"
>   type: Running
>   phase: CloneInProgress
>   progress: N/A
>   restartCount: 4

**Comment by zhangzhangzf** [comment]
> > > Are you using volumeMode=block? Can you post your VM definition? what is the output you get when you run `kubevirt describe dv rootfs.hhh`

> > > The previous virtual machine was deleted, and a new virtual machine named qwe was created. The phenomenon is consistent. The system image that needs to clone data from PVC has always been in CloneInProgress state.

> > > yes,volumeMode=block. Os image data source is PVC. `[root@VM-8-157-centos /home/cdi]# kubectl get vm qwe -o yaml apiVersion: kubevirt.io/v1 kind: VirtualMachine metadata: annotations: description: "" kubevirt.io/latest-observed-api-version: v1 kubevirt.io/storage-observed-api-version: v1alpha3 tkestack.io/image-display-name: Windows Server 2016 64位 creationTimestamp: "2023-04-10T03:52:17Z" generation: 1 labels: kubevirt.io/domain: qwe name: qwe namespace: default resourceVersion: "35009929" uid: c98da7e7-3156-4dbf-9b3c-2188c500210a spec: dataVolumeTemplates:
> > 
> > 
> > 
> > * metadata:
> >   creationTimestamp: null
> >   name: rootfs.qwe
> >   spec:
> >   pvc:
> >   accessModes:
> >   
> >   * ReadWriteMany
> >     resources:
> >     requests:
> >     storage: 20Gi
> >     storageClassName: csi-rbd-sc
> >     volumeMode: Block
> >     source:
> >     pvc:
> >     name: win-img
> >     namespace: kube-public
> > * metadata:
> >   creationTimestamp: null
> >   name: datavolume1.qwe
> >   spec:
> >   pvc:
> >   accessModes:
> >   
> >   * ReadWriteMany
> >     resources:
> >     requests:
> >     storage: 10Gi
> >     storageClassName: csi-rbd-sc
> >     volumeMode: Block
> >     source:
> >     blank: {}
> >     running: true
> >     template:
> >     metadata:
> >     annotations:
> >     tkestack.io/image-display-name: Windows Server 2016 64位
> >     creationTimestamp: null
> >     labels:
> >     kubevirt.io/domain: qwe
> >     spec:
> >     domain:
> >     cpu:
> >     cores: 4
> >     devices:
> >     disks:
> >   * bootOrder: 1
> >     disk:
> >     bus: virtio
> >     name: rootfs
> >   * bootOrder: 2
> >     disk:
> >     bus: virtio
> >     name: datavolume1
> >     inputs:
> >   * bus: usb
> >     name: tablet
> >     type: tablet
> >     interfaces:
> >   * bridge: {}
> >     model: virtio
> >     name: default
> >     machine:
> >     type: q35
> >     resources:
> >     requests:
> >     memory: 4G
> >     networks:
> >   
> >   
> >   * name: default
> >     pod: {}
> >     volumes:
> >   * dataVolume:
> >     name: rootfs.qwe
> >     name: rootfs
> >   * dataVolume:
> >     name: datavolume1.qwe
> >     name: datavolume1
> >     status:
> >     conditions:
> > * lastProbeTime: "2023-04-10T03:52:19Z"
> >   lastTransitionTime: "2023-04-10T03:52:19Z"
> >   message: VMI does not exist
> >   reason: VMINotExists
> >   status: "False"
> >   type: Ready
> > * lastProbeTime: null
> >   lastTransitionTime: "2023-04-10T03:52:19Z"
> >   message: 'Error encountered while creating DataVolumes: Failed to create DataVolume:
> >   admission webhook "datavolume-validate.cdi.kubevirt.io" denied the request:  Destination
> >   PVC default/datavolume1.qwe already exists'
> >   reason: FailedCreate
> >   status: "True"
> >   type: Failure
> >   printableStatus: Provisioning
> >   volumeSnapshotStatuses:
> > * enabled: true
> >   name: rootfs
> > * # enabled: false
> >   name: datavolume1
> >   reason: DV 'default/datavolume1.qwe' not found`
> >   apiVersion: cdi.kubevirt.io/v1beta1
> >   kind: DataVolume
> >   metadata:
> >   annotations:
> >   cdi.kubevirt.io/cloneType: network
> >   cdi.kubevirt.io/storage.clone.token: eyJhbGciOiJQUzI1NiJ9.eyJleHAiOjE2ODEwOTkwMzcsImlhdCI6MTY4MTA5ODczNywiaXNzIjoiY2RpLWFwaXNlcnZlciIsIm5hbWUiOiJ3aW4taW1nIiwibmFtZXNwYWNlIjoia3ViZSdaWMiLCJuYmYiOjE2ODEwOTgMzcsIm9wZXJ0YXRpb24iOiJDbG9uZSIsInBhcmFtcyI6eyJ0YXJnZXROYW1lIjoicm9vdGZzLnF3ZSIsInRhcmdldE5hbWVzcGFjZSI6ImRlZmF1bHQifSwicmVzb3VyY2UiOnsiZ3JvdXAiOiIiLCJyZXNvdXJjZSI6InBlcnNpc3RlbnR2b2x1bWVjbGFpbXMiLCJ2ZXJzaW9uIjoidjEifX0.jDkMUpDz9j7wr4QTmq1q_Cxi-PTzdwxKuvBkdVDh9MWJTSdP1wXyDzBLMLjwA6czG-id_Hxk1lqoerV9nzFNPtKrXhZpQVfK2idgJB3yn6ZncvhPDL1BQlubym0pWAx2QPWFEeXQqvym_kyZV_E2FAkSy4ZbrmbmKunu1yMeL8h2hy0cXFnpEPfpUtUsTd4LYAMyTnvNCyVKiC5FzTu8OhMTfOQeT8RvcBNFOk8pybO5Yvpd021sWy7FkFB8YLh_Efc7vhGYvfdDgUbk5p64leIIrfi-wFqXxnGHPIB_xeWDNWm3QphfmkIhimAibV0jD-h0PFM7bmkC4pTAxvw
> >   cdi.kubevirt.io/storage.deleteAfterCompletion: "true"
> >   creationTimestamp: "2023-04-10T03:52:17Z"
> >   generation: 1299
> >   labels:
> >   kubevirt.io/created-by: c98da7e7-3156-4dbf-9b3c-2188c500210a
> >   name: rootfs.qwe
> >   namespace: default
> >   ownerReferences:
> > * apiVersion: kubevirt.io/v1
> >   blockOwnerDeletion: true
> >   controller: true
> >   kind: VirtualMachine
> >   name: qwe
> >   uid: c98da7e7-3156-4dbf-9b3c-2188c500210a
> >   resourceVersion: "35017871"
> >   uid: bf986f1c-0b40-464b-b3e1-6a46ba386766
> >   spec:
> >   pvc:
> >   accessModes:
> >   
> >   * ReadWriteMany
> >     resources:
> >     requests:
> >     storage: 20Gi
> >     storageClassName: csi-rbd-sc
> >     volumeMode: Block
> >     source:
> >     pvc:
> >     name: win-img
> >     namespace: kube-public
> >     status:
> >     claimName: rootfs.qwe
> >     conditions:
> > * lastHeartbeatTime: "2023-04-10T03:52:18Z"
> >   lastTransitionTime: "2023-04-10T03:52:18Z"
> >   message: PVC rootfs.qwe Bound
> >   reason: Bound
> >   status: "True"
> >   type: Bound
> > * lastHeartbeatTime: "2023-04-10T03:54:51Z"
> >   lastTransitionTime: "2023-04-10T03:52:18Z"
> >   reason: TransferRunning
> >   status: "False"
> >   type: Ready
> > * lastHeartbeatTime: "2023-04-10T03:54:51Z"
> >   lastTransitionTime: "2023-04-10T03:54:51Z"
> >   reason: Pod is running
> >   status: "True"
> >   type: Running
> >   phase: CloneInProgress
> >   progress: N/A
> >   restartCount: 4

**Comment by zhangzhangzf** [comment]
> > > > Are you using volumeMode=block? Can you post your VM definition? what is the output you get when you run `kubevirt describe dv rootfs.hhh`
> 
> > > > The previous virtual machine was deleted, and a new virtual machine named qwe was created. The phenomenon is consistent. The OS image that needs to clone data from PVC has always been in CloneInProgress state.
> 
> > > > yes,volumeMode=block. OS image data source is PVC. 

`[root@VM-8-157-centos /home/cdi]# kubectl get vm qwe -o yaml
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    description: ""
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
    tkestack.io/image-display-name: Windows Server 2016 64位
  creationTimestamp: "2023-04-10T03:52:17Z"
  generation: 1
  labels:
    kubevirt.io/domain: qwe
  name: qwe
  namespace: default
  resourceVersion: "35009929"
  uid: c98da7e7-3156-4dbf-9b3c-2188c500210a
spec:
  dataVolumeTemplates:
  - metadata:
      creationTimestamp: null
      name: rootfs.qwe
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 20Gi
        storageClassName: csi-rbd-sc
        volumeMode: Block
      source:
        pvc:
          name: win-img
          namespace: kube-public
  - metadata:
      creationTimestamp: null
      name: datavolume1.qwe
    spec:
      pvc:
        accessModes:
        - ReadWriteMany
        resources:
          requests:
            storage: 10Gi
        storageClassName: csi-rbd-sc
        volumeMode: Block
      source:
        blank: {}
  running: true
  template:
    metadata:
      annotations:
        tkestack.io/image-display-name: Windows Server 2016 64位
      creationTimestamp: null
      labels:
        kubevirt.io/domain: qwe
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - bootOrder: 1
            disk:
              bus: virtio
            name: rootfs
          - bootOrder: 2
            disk:
              bus: virtio
            name: datavolume1
          inputs:
          - bus: usb
            name: tablet
            type: tablet
          interfaces:
          - bridge: {}
            model: virtio
            name: default
        machine:
          type: q35
        resources:
          requests:
            memory: 4G
      networks:
      - name: default
        pod: {}
      volumes:
      - dataVolume:
          name: rootfs.qwe
        name: rootfs
      - dataVolume:
          name: datavolume1.qwe
        name: datavolume1
status:
  conditions:
  - lastProbeTime: "2023-04-10T03:52:19Z"
    lastTransitionTime: "2023-04-10T03:52:19Z"
    message: VMI does not exist
    reason: VMINotExists
    status: "False"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-04-10T03:52:19Z"
    message: 'Error encountered while creating DataVolumes: Failed to create DataVolume:
      admission webhook "datavolume-validate.cdi.kubevirt.io" denied the request:  Destination
      PVC default/datavolume1.qwe already exists'
    reason: FailedCreate
    status: "True"
    type: Failure
  printableStatus: Provisioning
  volumeSnapshotStatuses:
  - enabled: true
    name: rootfs
  - enabled: false
    name: datavolume1
    reason: DV 'default/datavolume1.qwe' not found`

[root@VM-8-157-centos /home/cdi]# kubectl get dv rootfs.qwe  -o yaml
apiVersion: cdi.kubevirt.io/v1beta1
kind: DataVolume
metadata:
  annotations:
    cdi.kubevirt.io/cloneType: network
    cdi.kubevirt.io/storage.clone.token: eyJhbGciOiJQUzI1NiJ9.eyJleHAiOjE2ODEwOTkwMzcsImlhdCI6MTY4MTA5ODczNywiaXNzIjoiY2RpLWFwaXNlcnZlciIsIm5hbWUiOiJ3aW4taW1nIiwibmFtZXNwYWNlIjoia3ViZS1wdWJsaWMiLCJuYmYiOjE2ODEwOTg3MzcsIm9wZXJ0YXRpb24iOiJDbG9uZSIsInBhcmFtcyI6eyJ0YXJnZXROYW1lIjoicm9vdGZzLnF3ZSIsInRhcmdldE5hbWVzcGFjZSI6ImRlZmF1bHQifSwicmVzb3VyY2UiOnsiZ3JvdXAiOiIiLCJyZXNvdXJjZSI6InBlcnNpc3RlbnR2b2x1bWVjbGFpbXMiLCJ2ZXJzaW9uIjoidjEifX0.jDkMUpDz9j7wr4QTmq1q_Cxi-PTzdwxKuvBkdVDh9MWJTSdP1wXyDzBLMLjwA6czG-id_Hxk1lqoerV9nzFNPtKrXhZpQVfK2idgJB3yn6ZncvhPDL1BQlubym0pWAx2QPWFEeXQqvym_kyZV_E2FAkSy4ZbrmbmKunu1yMeL8h2hy0cXFnpEPfpUtUsTd4LYAMyTnvoJNCyVKiC5FzTu8OhMTfOQeT8RvcBNFOk8pybO5Yvpd021sWy7FkFB8YLh_Efc7vhGYvfdDgUbk5p64leIIrfi-wFqXxnGHPIB_xeWDNWm3QphfmkIhimAibV0jD-hv0PFM7bmkC4pTAxvw
    cdi.kubevirt.io/storage.deleteAfterCompletion: "true"
  creationTimestamp: "2023-04-10T03:52:17Z"
  generation: 1299
  labels:
    kubevirt.io/created-by: c98da7e7-3156-4dbf-9b3c-2188c500210a
  name: rootfs.qwe
  namespace: default
  ownerReferences:
  - apiVersion: kubevirt.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachine
    name: qwe
    uid: c98da7e7-3156-4dbf-9b3c-2188c500210a
  resourceVersion: "35017871"
  uid: bf986f1c-0b40-464b-b3e1-6a46ba386766
spec:
  pvc:
    accessModes:
    - ReadWriteMany
    resources:
      requests:
        storage: 20Gi
    storageClassName: csi-rbd-sc
    volumeMode: Block
  source:
    pvc:
      name: win-img
      namespace: kube-public
status:
  claimName: rootfs.qwe
  conditions:
  - lastHeartbeatTime: "2023-04-10T03:52:18Z"
    lastTransitionTime: "2023-04-10T03:52:18Z"
    message: PVC rootfs.qwe Bound
    reason: Bound
    status: "True"
    type: Bound
  - lastHeartbeatTime: "2023-04-10T03:54:51Z"
    lastTransitionTime: "2023-04-10T03:52:18Z"
    reason: TransferRunning
    status: "False"
    type: Ready
  - lastHeartbeatTime: "2023-04-10T03:54:51Z"
    lastTransitionTime: "2023-04-10T03:54:51Z"
    reason: Pod is running
    status: "True"
    type: Running
  phase: CloneInProgress
  progress: N/A
  restartCount: 4

**Comment by awels** [comment]
If your CRI is container-d, I suspect you are running into the same issue as this https://github.com/kubevirt/containerized-data-importer/issues/2638 essentially since 1.55 CDI is running rootless, and giving permission to write to a block device is slightly different. If you scroll down you will see what you need to modify to make it work. This is a k8s problem where there is no good way to express that you can access a block device.

**Comment by zhangzhangzf** [comment]
> If your CRI is container-d, I suspect you are running into the same issue as this [kubevirt/containerized-data-importer#2638](https://github.com/kubevirt/containerized-data-importer/issues/2638) essentially since 1.55 CDI is running rootless, and giving permission to write to a block device is slightly different. If you scroll down you will see what you need to modify to make it work. This is a k8s problem where there is no good way to express that you can access a block device.

Thank you for your attention to this issue. I followed the instructions to modify the configuration of Cotainerd, but the logs still show permission issues.

[root@VM-8-45-centos ~]# kubectl logs cdi-upload-rootfs.jhk
I0410 14:01:07.305707       1 uploadserver.go:74] Running server on 0.0.0.0:8443
I0410 14:01:14.839934       1 uploadserver.go:378] Content type header is "filesystem-clone"
I0410 14:01:14.840189       1 uploadserver.go:481] Untaring 11161042944 bytes to /dev/cdi-block-volume
E0410 14:01:14.840265       1 uploadserver.go:391] Saving stream failed: error unarchiving to /dev/cdi-block-volume: open /dev/cdi-block-volume: permission denied

**Comment by zhangzhangzf** [comment]
> 

My containerd config.

[plugins]
  [plugins."io.containerd.grpc.v1.cri"]
    device_ownership_from_security_context = true
    sandbox_image = "ccr.com/mages/pause:3.2"
    [plugins."io.containerd.grpc.v1.cri".cni]

**Comment by zhangzhangzf** [comment]
> Btw k8s-1.21 is really old, and will have many issues with both KubeVirt and CDI using APIs that are not available in 1.21. I suggest staying on an older version of KubeVirt or upgrading your k8s. What version of containerd are you running? For this to work you need at least 1.6

I get it. May I ask if there is a version mapping table between k8s, cdi, and kubevirt

**Comment by pauloalem** [comment]
@awels do you think we could add this to the projects documentation? 
Because of it, I was finally able to figure out an issue with CDI that I was having -> I was running a 1.23 cluster with 0.54 and volume clone pods would fail with a `0/8 nodes are available: 2 node(s) had volume node affinity conflict, 6 node(s) didn't match Pod's node affinity/selector.` 
I switched to 1.44.1 (had a small issue with 1.43.x and tested the next available) and it magically works for me.
Thank you.

**Comment by xpivarc** [comment]
@zhangzhangzf Did you restarted the containerd? 

@pauloalem I think it makes sense to enhance the documentation. Would you be interesting sending a PR?
