### ISSUE TITLE
Thank you for opening this issue.

### ISSUE THREAD

**Issue by swq499809608** [kubevirt/kubevirt#9597]
Thank you for opening this issue.

If I am understanding correctly, you are attempting to run on a non-standard kubelet path using the feature enabled in PR [#3427](https://github.com/kubevirt/kubevirt/pull/3427)?

If that is not working, can you provide more details on your environment per the template?

_Originally posted by @usrbinkat in https://github.com/kubevirt/kubevirt/issues/7895#issuecomment-1156562131_

**Comment by EdDev** [comment]
This issue is stake for a long time.

I'm closing it for now, if you'll like to proceed with it please re-open it with proper information in the description (see issue template).

/close
