### ISSUE TITLE
VM creation failed

### ISSUE THREAD

**Issue by ekambaramv** [kubevirt/kubevirt#9607]
**What happened**:
Unable to create VMI

**What you expected to happen**:
VM creation should happen normally

**How to reproduce it (as minimally and precisely as possible)**:
kubectl apply -f vm1.yaml

**Errort**:

Error from server (InternalError): error when creating "vm1.yaml": Internal error occurred: failed calling webhook "virtualmachineinstances-mutator.kubevirt.io": failed to call webhook: Post "https://virt-api.kubevirt.svc:443/virtualmachineinstances-mutate?timeout=10s": x509: certificate signed by unknown authority

**Environment**:
- KubeVirt version (use `virtctl version`): v0.59.0
- Kubernetes version (use `kubectl version`): v1.23.16
- VM or VMI specifications: 
============================================================
metadata:
  name: vm1
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
spec:
  domain:
    resources:
      requests:
        memory: 30Gi
        cpu: 20
    devices:
      disks:
      - name: containerdisk
        disk: {}
      - name: cloudinitdisk
        disk:
          bus: virtio
      - name: rootdisk
        disk:
          bus: virtio
      interfaces:
        - name: default
          masquerade: {}
  networks:
    - name: default
      pod: {}
  volumes:
    - name: containerdisk
      containerDisk:
        image: vmidisks/opensuse15:latest
        imagePullPolicy: IfNotPresent
    - cloudInitNoCloud:
       userData: |-
         #cloud-config
         chpasswd:
           expire: false
         password: password
         user: test
      name: cloudinitdisk
    - name: rootdisk
      hostDisk:
       capacity: 40Gi
       path: /tmp/data/disk.img
       type: DiskOrCreate
================================================================
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release):  Ubuntu 22.04 LTS
- Kernel (e.g. `uname -a`): 5.15.0-60-generic
- Install tools: N/A
- Others: N/A

**Comment by xpivarc** [comment]
These kinds of issues usually are transient. This might become an issue if the problem persists.
