### ISSUE TITLE
failed to bindmount containerDisk rootfs

### ISSUE THREAD

**Issue by GOVYANSONG** [kubevirt/kubevirt#9611]
**What happened**:
failed to bindmount containerDisk rootfs: Error: mount target invalid: failed opening pods for path root: /, relative: /var/lib/kubelet/pods/3ba69e5e-37b1-45f2-9b32-425436f4ce3c/volumes/kubernetes.io~empty-dir/container-disks/disk_0.img: not a directory

**What you expected to happen**:
VM should start and ready.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

Events:
  Type     Reason            Age                   From                       Message
  ----     ------            ----                  ----                       -------
  Normal   SuccessfulCreate  2m45s                 virtualmachine-controller  Created virtual machine pod virt-launcher-testvm-mj6jl
  Warning  SyncFailed        67s (x15 over 2m30s)  virt-handler               failed to bindmount containerDisk rootfs: Error: mount target invalid: failed opening pods for path root: /, relative: /var/lib/kubelet/pods/3ba69e5e-37b1-45f2-9b32-425436f4ce3c/volumes/kubernetes.io~empty-dir/container-disks/disk_0.img: not a directory
Usage:
  virt-chroot mount [flags]

Flags:
  -h, --help             help for mount
  -o, --options string   comma separated list of mount options
  -t, --type string      fstype

Global Flags:
      --cpu uint       cpu time in seconds for the process
      --memory uint    memory in bytes for the process
      --mount string   mount namespace to use
      --user string    switch to this targetUser to e.g. drop privileges

mount target invalid: failed opening pods for path root: /, relative: /var/lib/kubelet/pods/3ba69e5e-37b1-45f2-9b32-425436f4ce3c/volumes/kubernetes.io~empty-dir/container-disks/disk_0.img: not a directory
 : exit status 1

**Environment**:
- KubeVirt version (use `virtctl version`): 
Client Version: version.Info{GitVersion:"v0.57.1", GitCommit:"4c08bf090387743b2e2c8037c941102f11e6b031", GitTreeState:"clean", BuildDate:"2022-09-14T14:05:11Z", GoVersion:"go1.17.8", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{GitVersion:"v0.59.0", GitCommit:"78f5184d1794838c5fc5061f920273fb4e5283ed", GitTreeState:"clean", BuildDate:"2023-03-01T16:55:38Z", GoVersion:"go1.19.2", Compiler:"gc", Platform:"linux/amd64"}

- Kubernetes version (use `kubectl version`): 1.26
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Ubuntu 20.04
- Kernel (e.g. `uname -a`): Linux w-gaoyans-2 5.15.90.1-microsoft-standard-WSL2 #1 SMP Fri Jan 27 02:56:13 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: kubectl virt
- Others: N/A

**Comment by GOVYANSONG** [comment]
Just run ls -al and got permission denied on dir: /var/lib/kubelet/pods.

**Comment by GOVYANSONG** [comment]
I finally switched over to minikube on hyperv with nested virtualization. now working on host cluster. but failed on vcluster.

**Comment by astromechza** [comment]
I've also hit this error while running kubevirt with microk8s on an Ubuntu amd64 host. With and without Root feature gate. Have not been able to work around it yet but will keep trying.

**Comment by realexcel2021** [comment]
same issue on microk8s

**Comment by RaSerge** [comment]
bump!
have similar issue. 
We have kubespray installed k8s wit custom root dir path for kubelet and pods.
`mount target invalid: failed opening pods for path root: /, relative: /var/lib/kubelet/pods/972ab7dc-c1bb-4508-9be2-26329bd176f2/volumes/kubernetes.io~empty-dir/container-disks/disk_0.img: no such file or directory`

**Comment by iholder101** [comment]
This seems to be relevant.
@astromechza @realexcel2021 @RaSerge can you please provide more data? infra pods' logs, especially virt-handler's, would be a great start, and concrete reproduction steps would be appreciated.

/reopen

**Comment by Hamedmt** [comment]
Hi
I have the same issue with Microk8s.
This is the error from the handler:

> failed to bindmount containerDisk containerdisk: Error: mount target invalid: failed opening pods for path root: /, relative: /var/lib/kubelet/pods/593a6631-97f3-4bde-a111-b09a2a036d26/volumes/kubernetes.io~empty-dir/container-disks/disk_0.img: not a directory
Usage:
  virt-chroot mount [flags]

>Flags:
  -h, --help             help for mount
  -o, --options string   comma separated list of mount options
  -t, --type string      fstype

>Global Flags:
      --cpu uint       cpu time in seconds for the process
      --memory uint    memory in bytes for the process
      --mount string   mount namespace to use
      --user string    switch to this targetUser to e.g. drop privileges

>mount target invalid: failed opening pods for path root: /, relative: /var/lib/kubelet/pods/593a6631-97f3-4bde-a111-b09a2a036d26/volumes/kubernetes.io~empty-dir/container-disks/disk_0.img: not a directory
 : exit status 1

This is the logs from the launcher:

>{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:88","timestamp":"2025-03-28T04:34:34.063570Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:91","timestamp":"2025-03-28T04:34:34.063633Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:545","timestamp":"2025-03-28T04:34:34.063910Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory')","pos":"libvirt.go:553","timestamp":"2025-03-28T04:34:34.064699Z"}
{"component":"virt-launcher","level":"info","msg":"libvirt version: 10.5.0, package: 5.el9 (builder@centos.org, 2024-08-09-10:14:52, )","subcomponent":"libvirt","thread":"46","timestamp":"2025-03-28T04:34:34.099000Z"}
{"component":"virt-launcher","level":"info","msg":"hostname: testvm","subcomponent":"libvirt","thread":"46","timestamp":"2025-03-28T04:34:34.099000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get session bus connection: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory","pos":"virGDBusGetSessionBus:126","subcomponent":"libvirt","thread":"46","timestamp":"2025-03-28T04:34:34.099000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get system bus connection: Could not connect: No such file or directory","pos":"virGDBusGetSystemBus:99","subcomponent":"libvirt","thread":"46","timestamp":"2025-03-28T04:34:34.099000Z"}
{"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:561","timestamp":"2025-03-28T04:34:34.567177Z"}
{"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:563","timestamp":"2025-03-28T04:34:34.570340Z"}
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:75","timestamp":"2025-03-28T04:34:34.570582Z"}
panic: timed out waiting for domain to be defined
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 12 with status 512","pos":"virt-launcher-monitor.go:198","timestamp":"2025-03-28T04:38:41.579136Z"}
{"component":"virt-launcher-monitor","level":"error","msg":"dirty virt-launcher shutdown: exit-code 2","pos":"virt-launcher-monitor.go:216","timestamp":"2025-03-28T04:38:41.579233Z"}

There is another error in the handler as follows:

>{
  "component": "virt-handler",
  "kind": "",
  "level": "info",
  "msg": "Bind mounting container disk at root: /proc/1/root, relative: /var/snap/microk8s/common/run/containerd/io.containerd.runtime.v2.task/k8s.io/87f39bff821079af02500d3712c4f2c8b1ece18942a9d5a1ba4f82c6b1360a52/rootfs/disk/downloaded to root: /var/lib/kubelet/pods/593a6631-97f3-4bde-a111-b09a2a036d26/volumes/kubernetes.io~empty-dir/container-disks, relative: /disk_0.img",
  "name": "testvm",
  "namespace": "kubevirt-test",
  "pos": "mount.go:289",
  "timestamp": "2025-03-28T04:34:45.641192Z",
  "uid": "7ff8a5f8-10de-47f9-a739-19437d85d267"
}

As I checked, the file under
 "/var/snap/microk8s/common/run/containerd/io.containerd.runtime.v2.task/k8s.io/87f39bff821079af02500d3712c4f2c8b1ece18942a9d5a1ba4f82c6b1360a52/rootfs/disk/downloaded"
has been downloaded which is qcow2 file (which is expected), but the file under
"/var/lib/kubelet/pods/593a6631-97f3-4bde-a111-b09a2a036d26/volumes/kubernetes.io~empty-dir/container-disks/disk_0.img" 
is empty.


There was a problem with the groupID as well. The /dev/kvm was owned by root:kvm, whose kvm groupID was 108 on my machine. But the launcher was using groupID of 107. I dont know why groupID of 107 was fixed and it is not possible to define a securityContext.

**Comment by zedi-pramodh** [comment]
I am seeing same issue now with Kubevirt v1.5.2 which was not seen with kubevirt v1.1.0

describe on the vmi

    Last Transition Time:  2025-08-13T21:40:24Z
    Message:               error mounting kernel artifacts: failed to bindmount kernel-boot: Error: mount target invalid: failed opening kubelet for path root: /, relative: /var/lib/kubelet/pods/57acf895-292c-48eb-8390-86eb89878d06/volumes/kubernetes.io~empty-dir/container-disks/kernel-boot/kernel: no such file or directory
Usage:
  virt-chroot mount [flags]

Flags:
  -h, --help             help for mount
  -o, --options string   comma separated list of mount options
  -t, --type string      fstype

Global Flags:
      --cpu uint       cpu time in seconds for the process
      --memory uint    memory in bytes for the process
      --mount string   mount namespace to use
      --user string    switch to this targetUser to e.g. drop privileges

mount target invalid: failed opening kubelet for path root: /, relative: /var/lib/kubelet/pods/57acf895-292c-48eb-8390-86eb89878d06/volumes/kubernetes.io~empty-dir/container-disks/kernel-boot/kernel: no such file or directory
 : exit status 1
    Reason:  Synchronizing with the Domain failed.
    Status:  False
    Type:    Synchronized
  Current CPU Topology:
    Cores:  1
  Guest OS Info:
  Interfaces:
    Info Source:                     multus-status
    Name:                            net1
    Pod Interface Name:              pod6c270ef2f25
  Launcher Container Image Version:  quay.io/kubevirt/virt-launcher:v1.5.2
  Memory:
    Guest At Boot:      100Mi
    Guest Current:      100Mi
    Guest Requested:    100Mi
  Migration Method:     BlockMigration
  Migration Transport:  Unix
  Node Name:            wine-sjlab
  Phase:                Scheduled
  Phase Transition Timestamps:
    Phase:                       Pending
    Phase Transition Timestamp:  2025-08-13T21:40:16Z
    Phase:                       Scheduling
    Phase Transition Timestamp:  2025-08-13T21:40:16Z
    Phase:                       Scheduled
    Phase Transition Timestamp:  2025-08-13T21:40:24Z
  Qos Class:                     Burstable
  Runtime User:                  107
  Selinux Context:               none
  Volume Status:
    Name:  disk1
    Persistent Volume Claim Info:
      Access Modes:
        ReadWriteOnce
      Capacity:
        Storage:            18Mi
      Claim Name:           610b3eb3-2c73-4898-92b1-f5a1504bbe3f-pvc-0
      Filesystem Overhead:  0
      Requests:
        Storage:    18874368
      Volume Mode:  Block
    Target:         
Events:
  Type     Reason            Age    From                       Message
  ----     ------            ----   ----                       -------
  Normal   SuccessfulCreate  5m49s  virtualmachine-controller  Created virtual machine pod virt-launcher-pramod-cont-vm-054f0vlvmt-24g79
  Warning  SyncFailed        5m41s  virt-handler               error mounting kernel artifacts: failed to bindmount kernel-boot: Error: mount target invalid: failed opening kubelet for path root: /, relative: /var/lib/kubelet/pods/57acf895-292c-48eb-8390-86eb89878d06/volumes/kubernetes.io~empty-dir/container-disks/kernel-boot/kernel: no such file or directory
Usage:
  virt-chroot mount [flags]

Flags:
  -h, --help             help for mount
  -o, --options string   comma separated list of mount options
  -t, --type string      fstype

Global Flags:
      --cpu uint       cpu time in seconds for the process
      --memory uint    memory in bytes for the process
      --mount string   mount namespace to use
      --user string    switch to this targetUser to e.g. drop privileges

mount target invalid: failed opening kubelet for path root: /, relative: /var/lib/kubelet/pods/57acf895-292c-48eb-8390-86eb89878d06/volumes/kubernetes.io~empty-dir/container-disks/kernel-boot/kernel: no such file or directory
 : exit status 1
  Warning  SyncFailed  13s (x16 over 5m41s)  virt-handler  error mounting kernel artifacts: failed making the directory root: /, relative: /var/lib/kubelet/pods/57acf895-292c-48eb-8390-86eb89878d06/volumes/kubernetes.io~empty-dir/container-disks: file exists
