### ISSUE TITLE
pass through GPU，but kubevirt-gpu-device-plugin can't start

### ISSUE THREAD

**Issue by ninelinesevduk** [kubevirt/kubevirt#9617]
I use pass through mode,and have replaced the GPU card driver with vfio PCI, and enabled GPU and whitelist for kubevirt.But kubevirt-gpu-device-plugin can't start: no cuda-capable device is detected
![2](https://user-images.githubusercontent.com/3922582/231952510-60c941e6-2e2a-4e45-a2c8-c8b0fbade664.jpg)

![3](https://user-images.githubusercontent.com/3922582/231953018-9ae8de22-7930-434c-980f-13b7f5a43629.jpg)

![微信图片_20230414114922](https://user-images.githubusercontent.com/3922582/231937366-ca5ed848-f860-43ab-88b9-3bc8e533bfa5.jpg)

What should I do?

kubevirt-gpu-device-plugin：1.2.1
kubernetes：1.20
kubevirt：0.46

Also, I still have a few confusions:

Is there any sequence requirement between enabling the whitelist on kubevirt and installing the device plugin?
Does docker on the node need to use nvidia container runtime?

**Comment by ninelinesevduk** [comment]
> Have no idea about the error "no cuda-capable device is detected", but in the rigth case, all sub-devices of the GPU need to configure the VFIO-PCI driver. In your case, 02:00.0 has bound to vfio-pci, but 02:00.1 didn't, it will lead to some problem when allocate the GPU to the VM.

The reason is that DOCKER's container runtime is nvidia container runtime. When I replace it with runc, I'm done. In the pass-through model, the nvidia kubevirt gpu device plugin does not work with the nvidia container runtime

**Comment by vladikr** [comment]
@ninelinesevduk I would suggest asking this question in https://github.com/NVIDIA/kubevirt-gpu-device-plugin project - as this is where the nvidia device plugin being developed and maintained.
Would you like trying the same using the native kubevirt device plugin? [1] (without externalResourceProvider: true)

[1] https://kubevirt.io/user-guide/virtual_machines/host-devices/

**Comment by ninelinesevduk** [comment]
> @ninelinesevduk I would suggest asking this question in https://github.com/NVIDIA/kubevirt-gpu-device-plugin project - as this is where the nvidia device plugin is being developed and maintained. Would you like trying the same using the native kubevirt device plugin? [1] (without externalResourceProvider: true)
> 
> [1] https://kubevirt.io/user-guide/virtual_machines/host-devices/

thanks for your help

**Comment by ninelinesevduk** [comment]
@vladikr thanks for your helps
