### ISSUE TITLE
kubevirt vm not starting on vcluster

### ISSUE THREAD

**Issue by GOVYANSONG** [kubevirt/kubevirt#9618]
**What happened**:
I can successfully deploy vm demo on minikube cluster. but failed in vcluster. 

**What you expected to happen**:
I expect the vm demo to start and run in vcluster.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

logs from successful host instance and failed vcluster are attached. the difference is located around: 

{"component":"virt-launcher","kind":"","level":"info","msg":"Executing PreStartHook on VMI pod environment","name":"testvm","namespace":"vcvm","pos":"manager.go:531","timestamp":"2023-04-15T21:15:22.760831Z","uid":"e3a9fb70-273f-4498-8f16-30e1660a6fbe"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Starting PreCloudInitIso hook","name":"testvm","namespace":"vcvm","pos":"manager.go:552","timestamp":"2023-04-15T21:15:22.760942Z","uid":"e3a9fb70-273f-4498-8f16-30e1660a6fbe"}

**Environment**:
- KubeVirt version (use `virtctl version`): v0.34.2
- Kubernetes version (use `kubectl version`): "v1.26.3"
- VM or VMI specifications: (https://raw.githubusercontent.com/kubevirt/demo/master/manifests/vm.yaml)
- Cloud provider or hardware configuration: minikube on bare metal
- OS (e.g. from /etc/os-release): ubuntu 20.04 on hyperv
- Kernel (e.g. `uname -a`): 5.4.0-146-generic
- Install tools: virtctl
- Others: N/A

**Comment by GOVYANSONG** [comment]
logs from successful host instance:

{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:86","timestamp":"2023-04-15T21:15:20.912610Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:89","timestamp":"2023-04-15T21:15:20.912730Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:519","timestamp":"2023-04-15T21:15:20.913886Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory')","pos":"libvirt.go:527","timestamp":"2023-04-15T21:15:20.914419Z"}
{"component":"virt-launcher","level":"info","msg":"libvirt version: 9.0.0, package: 3.el9 (builder@centos.org, 2023-02-01-12:58:56, )","subcomponent":"libvirt","thread":"38","timestamp":"2023-04-15T21:15:20.929000Z"}
{"component":"virt-launcher","level":"info","msg":"hostname: testvm","subcomponent":"libvirt","thread":"38","timestamp":"2023-04-15T21:15:20.929000Z"}
{"component":"virt-launcher","level":"error","msg":"Unable to open /dev/kvm: Permission denied","pos":"virHostCPUGetCPUID:1422","subcomponent":"libvirt","thread":"38","timestamp":"2023-04-15T21:15:20.929000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get session bus connection: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory","pos":"virGDBusGetSessionBus:126","subcomponent":"libvirt","thread":"38","timestamp":"2023-04-15T21:15:20.929000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get system bus connection: Could not connect: No such file or directory","pos":"virGDBusGetSystemBus:99","subcomponent":"libvirt","thread":"38","timestamp":"2023-04-15T21:15:20.929000Z"}
{"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:535","timestamp":"2023-04-15T21:15:21.418435Z"}
{"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:537","timestamp":"2023-04-15T21:15:21.424911Z"}
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:75","timestamp":"2023-04-15T21:15:21.425563Z"}
**{"component":"virt-launcher","kind":"","level":"info","msg":"Executing PreStartHook on VMI pod environment","name":"testvm","namespace":"vcvm","pos":"manager.go:531","timestamp":"2023-04-15T21:15:22.760831Z","uid":"e3a9fb70-273f-4498-8f16-30e1660a6fbe"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Starting PreCloudInitIso hook","name":"testvm","namespace":"vcvm","pos":"manager.go:552","timestamp":"2023-04-15T21:15:22.760942Z","uid":"e3a9fb70-273f-4498-8f16-30e1660a6fbe"}**
{"component":"virt-launcher","level":"info","msg":"Found nameservers in /etc/resolv.conf: \n`\u0000\n","pos":"network.go:287","timestamp":"2023-04-15T21:15:22.762410Z"}
{"component":"virt-launcher","level":"info","msg":"Found search domains in /etc/resolv.conf: vcvm.svc.cluster.local svc.cluster.local cluster.local mshome.net","pos":"network.go:288","timestamp":"2023-04-15T21:15:22.763726Z"}
{"component":"virt-launcher","level":"info","msg":"Starting SingleClientDHCPServer","pos":"server.go:65","timestamp":"2023-04-15T21:15:22.764616Z"}
{"component":"virt-launcher","level":"info","msg":"Driver cache mode for /var/run/kubevirt-ephemeral-disks/disk-data/rootfs/disk.qcow2 set to none","pos":"converter.go:452","timestamp":"2023-04-15T21:15:22.815338Z"}
{"component":"virt-launcher","level":"info","msg":"Driver cache mode for /var/run/kubevirt-ephemeral-disks/cloud-init-data/vcvm/testvm/noCloud.iso set to none","pos":"converter.go:452","timestamp":"2023-04-15T21:15:22.824223Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Domain XML generated. Base64 dump PGRvbWFpbiB0eXBlPSJrdm0iIHhtbG5zOnFlbXU9Imh0dHA6Ly9saWJ2aXJ0Lm9yZy9zY2hlbWFzL2RvbWFpbi9xZW11LzEuMCI+Cgk8bmFtZT52Y3ZtX3Rlc3R2bTwvbmFtZT4KCTxtZW1vcnkgdW5pdD0iYiI+NjQwMDAwMDA8L21lbW9yeT4KCTxvcz4KCQk8dHlwZSBhcmNoPSJ4ODZfNjQiIG1hY2hpbmU9InEzNSI+aHZtPC90eXBlPgoJCTxzbWJpb3MgbW9kZT0ic3lzaW5mbyI+PC9zbWJpb3M+Cgk8L29zPgoJPHN5c2luZm8gdHlwZT0ic21iaW9zIj4KCQk8c3lzdGVtPgoJCQk8ZW50cnkgbmFtZT0idXVpZCI+NWE5ZmMxODEtOTU3ZS01YzMyLTllNWEtMmRlNWU5NjczNTMxPC9lbnRyeT4KCQkJPGVudHJ5IG5hbWU9Im1hbnVmYWN0dXJlciI+S3ViZVZpcnQ8L2VudHJ5PgoJCQk8ZW50cnkgbmFtZT0iZmFtaWx5Ij5LdWJlVmlydDwvZW50cnk+CgkJCTxlbnRyeSBuYW1lPSJwcm9kdWN0Ij5Ob25lPC9lbnRyeT4KCQkJPGVudHJ5IG5hbWU9InNrdSI+PC9lbnRyeT4KCQkJPGVudHJ5IG5hbWU9InZlcnNpb24iPjwvZW50cnk+CgkJPC9zeXN0ZW0+CgkJPGJpb3M+PC9iaW9zPgoJCTxiYXNlQm9hcmQ+PC9iYXNlQm9hcmQ+CgkJPGNoYXNzaXM+PC9jaGFzc2lzPgoJPC9zeXNpbmZvPgoJPGRldmljZXM+CgkJPGludGVyZmFjZSB0eXBlPSJldGhlcm5ldCI+CgkJCTxzb3VyY2U+PC9zb3VyY2U+CgkJCTx0YXJnZXQgZGV2PSJ0YXAwIiBtYW5hZ2VkPSJubyI+PC90YXJnZXQ+CgkJCTxtb2RlbCB0eXBlPSJ2aXJ0aW8tbm9uLXRyYW5zaXRpb25hbCI+PC9tb2RlbD4KCQkJPG10dSBzaXplPSIxNDUwIj48L210dT4KCQkJPGFsaWFzIG5hbWU9InVhLWRlZmF1bHQiPjwvYWxpYXM+CgkJCTxyb20gZW5hYmxlZD0ibm8iPjwvcm9tPgoJCTwvaW50ZXJmYWNlPgoJCTxjaGFubmVsIHR5cGU9InVuaXgiPgoJCQk8dGFyZ2V0IG5hbWU9Im9yZy5xZW11Lmd1ZXN0X2FnZW50LjAiIHR5cGU9InZpcnRpbyI+PC90YXJnZXQ+CgkJPC9jaGFubmVsPgoJCTxjb250cm9sbGVyIHR5cGU9InVzYiIgaW5kZXg9IjAiIG1vZGVsPSJub25lIj48L2NvbnRyb2xsZXI+CgkJPGNvbnRyb2xsZXIgdHlwZT0ic2NzaSIgaW5kZXg9IjAiIG1vZGVsPSJ2aXJ0aW8tbm9uLXRyYW5zaXRpb25hbCI+PC9jb250cm9sbGVyPgoJCTxjb250cm9sbGVyIHR5cGU9InZpcnRpby1zZXJpYWwiIGluZGV4PSIwIiBtb2RlbD0idmlydGlvLW5vbi10cmFuc2l0aW9uYWwiPjwvY29udHJvbGxlcj4KCQk8dmlkZW8+CgkJCTxtb2RlbCB0eXBlPSJ2Z2EiIGhlYWRzPSIxIiB2cmFtPSIxNjM4NCI+PC9tb2RlbD4KCQk8L3ZpZGVvPgoJCTxncmFwaGljcyB0eXBlPSJ2bmMiPgoJCQk8bGlzdGVuIHR5cGU9InNvY2tldCIgc29ja2V0PSIvdmFyL3J1bi9rdWJldmlydC1wcml2YXRlL2UzYTlmYjcwLTI3M2YtNDQ5OC04ZjE2LTMwZTE2NjBhNmZiZS92aXJ0LXZuYyI+PC9saXN0ZW4+CgkJPC9ncmFwaGljcz4KCQk8bWVtYmFsbG9vbiBtb2RlbD0idmlydGlvLW5vbi10cmFuc2l0aW9uYWwiPgoJCQk8c3RhdHMgcGVyaW9kPSIxMCI+PC9zdGF0cz4KCQk8L21lbWJhbGxvb24+CgkJPGRpc2sgZGV2aWNlPSJkaXNrIiB0eXBlPSJmaWxlIiBtb2RlbD0idmlydGlvLW5vbi10cmFuc2l0aW9uYWwiPgoJCQk8c291cmNlIGZpbGU9Ii92YXIvcnVuL2t1YmV2aXJ0LWVwaGVtZXJhbC1kaXNrcy9kaXNrLWRhdGEvcm9vdGZzL2Rpc2sucWNvdzIiPjwvc291cmNlPgoJCQk8dGFyZ2V0IGJ1cz0idmlydGlvIiBkZXY9InZkYSI+PC90YXJnZXQ+CgkJCTxkcml2ZXIgY2FjaGU9Im5vbmUiIGVycm9yX3BvbGljeT0ic3RvcCIgbmFtZT0icWVtdSIgdHlwZT0icWNvdzIiIGRpc2NhcmQ9InVubWFwIj48L2RyaXZlcj4KCQkJPGFsaWFzIG5hbWU9InVhLXJvb3RmcyI+PC9hbGlhcz4KCQkJPGJhY2tpbmdTdG9yZSB0eXBlPSJmaWxlIj4KCQkJCTxmb3JtYXQgdHlwZT0icWNvdzIiPjwvZm9ybWF0PgoJCQkJPHNvdXJjZSBmaWxlPSIvdmFyL3J1bi9rdWJldmlydC9jb250YWluZXItZGlza3MvZGlza18wLmltZyI+PC9zb3VyY2U+CgkJCTwvYmFja2luZ1N0b3JlPgoJCTwvZGlzaz4KCQk8ZGlzayBkZXZpY2U9ImRpc2siIHR5cGU9ImZpbGUiIG1vZGVsPSJ2aXJ0aW8tbm9uLXRyYW5zaXRpb25hbCI+CgkJCTxzb3VyY2UgZmlsZT0iL3Zhci9ydW4va3ViZXZpcnQtZXBoZW1lcmFsLWRpc2tzL2Nsb3VkLWluaXQtZGF0YS92Y3ZtL3Rlc3R2bS9ub0Nsb3VkLmlzbyI+PC9zb3VyY2U+CgkJCTx0YXJnZXQgYnVzPSJ2aXJ0aW8iIGRldj0idmRiIj48L3RhcmdldD4KCQkJPGRyaXZlciBjYWNoZT0ibm9uZSIgZXJyb3JfcG9saWN5PSJzdG9wIiBuYW1lPSJxZW11IiB0eXBlPSJyYXciIGRpc2NhcmQ9InVubWFwIj48L2RyaXZlcj4KCQkJPGFsaWFzIG5hbWU9InVhLWNsb3VkaW5pdCI+PC9hbGlhcz4KCQk8L2Rpc2s+CgkJPHNlcmlhbCB0eXBlPSJ1bml4Ij4KCQkJPHRhcmdldCBwb3J0PSIwIj48L3RhcmdldD4KCQkJPHNvdXJjZSBtb2RlPSJiaW5kIiBwYXRoPSIvdmFyL3J1bi9rdWJldmlydC1wcml2YXRlL2UzYTlmYjcwLTI3M2YtNDQ5OC04ZjE2LTMwZTE2NjBhNmZiZS92aXJ0LXNlcmlhbDAiPjwvc291cmNlPgoJCTwvc2VyaWFsPgoJCTxjb25zb2xlIHR5cGU9InB0eSI+CgkJCTx0YXJnZXQgdHlwZT0ic2VyaWFsIiBwb3J0PSIwIj48L3RhcmdldD4KCQk8L2NvbnNvbGU+Cgk8L2RldmljZXM+Cgk8bWV0YWRhdGE+CgkJPGt1YmV2aXJ0IHhtbG5zPSJodHRwOi8va3ViZXZpcnQuaW8iPgoJCQk8dWlkPjwvdWlkPgoJCTwva3ViZXZpcnQ+Cgk8L21ldGFkYXRhPgoJPGZlYXR1cmVzPgoJCTxhY3BpPjwvYWNwaT4KCTwvZmVhdHVyZXM+Cgk8Y3B1IG1vZGU9Imhvc3QtbW9kZWwiPgoJCTx0b3BvbG9neSBzb2NrZXRzPSIxIiBjb3Jlcz0iMSIgdGhyZWFkcz0iMSI+PC90b3BvbG9neT4KCTwvY3B1PgoJPHZjcHUgcGxhY2VtZW50PSJzdGF0aWMiPjE8L3ZjcHU+Cgk8aW90aHJlYWRzPjE8L2lvdGhyZWFkcz4KPC9kb21haW4+","name":"testvm","namespace":"vcvm","pos":"libvirt_helper.go:133","timestamp":"2023-04-15T21:15:22.831119Z","uid":"e3a9fb70-273f-4498-8f16-30e1660a6fbe"}
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 57 with status 0","pos":"virt-launcher-monitor.go:120","timestamp":"2023-04-15T21:15:22.875959Z"}
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 59 with status 0","pos":"virt-launcher-monitor.go:120","timestamp":"2023-04-15T21:15:23.017359Z"}
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 65 with status 0","pos":"virt-launcher-monitor.go:120","timestamp":"2023-04-15T21:15:23.238390Z"}
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 67 with status 0","pos":"virt-launcher-monitor.go:120","timestamp":"2023-04-15T21:15:23.275079Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Domain defined.","name":"testvm","namespace":"vcvm","pos":"manager.go:882","timestamp":"2023-04-15T21:15:23.508373Z","uid":"e3a9fb70-273f-4498-8f16-30e1660a6fbe"}
{"component":"virt-launcher","level":"info","msg":"DomainLifecycle event 0 with reason 0 received","pos":"client.go:463","timestamp":"2023-04-15T21:15:23.508566Z"}
{"component":"virt-launcher","level":"info","msg":"kubevirt domain status: Shutoff(5):Unknown(0)","pos":"client.go:295","timestamp":"2023-04-15T21:15:23.514736Z"}
{"component":"virt-launcher","level":"info","msg":"Successfully connected to domain notify socket at /var/run/kubevirt/domain-notify-pipe.sock","pos":"client.go:170","timestamp":"2023-04-15T21:15:23.518977Z"}
{"component":"virt-launcher","level":"info","msg":"Domain name event: vcvm_testvm","pos":"client.go:422","timestamp":"2023-04-15T21:15:23.527393Z"}
{"component":"virt-launcher","level":"info","msg":"Monitoring loop: rate 1s start timeout 4m45s","pos":"monitor.go:181","timestamp":"2023-04-15T21:15:23.528600Z"}
{"component":"virt-launcher","level":"info","msg":"generated nocloud iso file /var/run/kubevirt-ephemeral-disks/cloud-init-data/vcvm/testvm/noCloud.iso","pos":"cloud-init.go:675","timestamp":"2023-04-15T21:15:23.637566Z"}
{"component":"virt-launcher","level":"info","msg":"GuestAgentLifecycle event state 2 with reason 1 received","pos":"client.go:520","timestamp":"2023-04-15T21:15:23.759909Z"}
{"component":"virt-launcher","level":"info","msg":"kubevirt domain status: Paused(3):StartingUp(11)","pos":"client.go:295","timestamp":"2023-04-15T21:15:23.763059Z"}
{"component":"virt-launcher","level":"info","msg":"Domain name event: vcvm_testvm","pos":"client.go:422","timestamp":"2023-04-15T21:15:23.765276Z"}
{"component":"virt-launcher","level":"info","msg":"DomainLifecycle event 4 with reason 0 received","pos":"client.go:463","timestamp":"2023-04-15T21:15:24.234938Z"}
{"component":"virt-launcher","level":"info","msg":"DomainLifecycle event 2 with reason 0 received","pos":"client.go:463","timestamp":"2023-04-15T21:15:24.258030Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Domain started.","name":"testvm","namespace":"vcvm","pos":"manager.go:910","timestamp":"2023-04-15T21:15:24.269414Z","uid":"e3a9fb70-273f-4498-8f16-30e1660a6fbe"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"testvm","namespace":"vcvm","pos":"server.go:191","timestamp":"2023-04-15T21:15:24.270827Z","uid":"e3a9fb70-273f-4498-8f16-30e1660a6fbe"}
{"component":"virt-launcher","level":"info","msg":"kubevirt domain status: Running(1):Unknown(1)","pos":"client.go:295","timestamp":"2023-04-15T21:15:24.273237Z"}
{"component":"virt-launcher","level":"info","msg":"Domain name event: vcvm_testvm","pos":"client.go:422","timestamp":"2023-04-15T21:15:24.276545Z"}
{"component":"virt-launcher","level":"info","msg":"kubevirt domain status: Running(1):Unknown(1)","pos":"client.go:295","timestamp":"2023-04-15T21:15:24.278526Z"}
{"component":"virt-launcher","level":"info","msg":"Domain name event: vcvm_testvm","pos":"client.go:422","timestamp":"2023-04-15T21:15:24.281265Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"testvm","namespace":"vcvm","pos":"server.go:191","timestamp":"2023-04-15T21:15:24.412463Z","uid":"e3a9fb70-273f-4498-8f16-30e1660a6fbe"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"testvm","namespace":"vcvm","pos":"server.go:191","timestamp":"2023-04-15T21:15:24.503800Z","uid":"e3a9fb70-273f-4498-8f16-30e1660a6fbe"}
{"component":"virt-launcher","level":"info","msg":"Found PID for vcvm_testvm: 76","pos":"monitor.go:142","timestamp":"2023-04-15T21:15:24.529239Z"}
{"component":"virt-launcher","kind":"","level":"info","msg":"Synced vmi","name":"testvm","namespace":"vcvm","pos":"server.go:191","timestamp":"2023-04-15T21:15:24.582072Z","uid":"e3a9fb70-273f-4498-8f16-30e1660a6fbe"}

**Comment by GOVYANSONG** [comment]
logs from failed instance in vcluster: it seems that the startup process stuck.

{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:86","timestamp":"2023-04-15T21:26:21.549669Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:89","timestamp":"2023-04-15T21:26:21.549819Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:519","timestamp":"2023-04-15T21:26:21.552033Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory')","pos":"libvirt.go:527","timestamp":"2023-04-15T21:26:21.553860Z"}
{"component":"virt-launcher","level":"info","msg":"libvirt version: 9.0.0, package: 3.el9 (builder@centos.org, 2023-02-01-12:58:56, )","subcomponent":"libvirt","thread":"38","timestamp":"2023-04-15T21:26:21.602000Z"}
{"component":"virt-launcher","level":"info","msg":"hostname: testvm","subcomponent":"libvirt","thread":"38","timestamp":"2023-04-15T21:26:21.602000Z"}
{"component":"virt-launcher","level":"error","msg":"Unable to open /dev/kvm: Permission denied","pos":"virHostCPUGetCPUID:1422","subcomponent":"libvirt","thread":"38","timestamp":"2023-04-15T21:26:21.602000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get session bus connection: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory","pos":"virGDBusGetSessionBus:126","subcomponent":"libvirt","thread":"38","timestamp":"2023-04-15T21:26:21.603000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Unable to get system bus connection: Could not connect: No such file or directory","pos":"virGDBusGetSystemBus:99","subcomponent":"libvirt","thread":"38","timestamp":"2023-04-15T21:26:21.603000Z"}
{"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:535","timestamp":"2023-04-15T21:26:22.057647Z"}
{"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:537","timestamp":"2023-04-15T21:26:22.096529Z"}
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:75","timestamp":"2023-04-15T21:26:22.100494Z"}

**Comment by GOVYANSONG** [comment]
maybe related to this issue https://github.com/kubevirt/kubevirt/issues/8288

**Comment by GOVYANSONG** [comment]
On working instance (on host): this path exists: /var/run/kubevirt-ephemeral-disks/disk-data/rootfs/disk.qcow2
On non-working vcluster: this path is empty: /var/run/kubevirt-ephemeral-disks/container-disk-data

**Comment by brianmcarey** [comment]
/cc @xpivarc 

do we expect this to work in hyperv?

**Comment by xpivarc** [comment]
> maybe related to this issue #8288

Indeed.

>do we expect this to work in hyperv?
Sure why not as long as you have nested virt.
