### ISSUE TITLE
Support QCOW2 for hostDisk

### ISSUE THREAD

**Issue by lxm** [kubevirt/kubevirt#9624]
The qcow2 format can support backing file, and hostDisk support for qcow2 is useful when using local storage

**Comment by alicefr** [comment]
@lxm it is an old topic, please have a look to [this past issue](https://github.com/kubevirt/kubevirt/pull/8376)

**Comment by lxm** [comment]
> @lxm it is an old topic, please have a look to [this past issue](https://github.com/kubevirt/kubevirt/pull/8376)

When using hostDisk, want to use the backing file feature in the qcow2 format

**Comment by alicefr** [comment]
well, you won't be able to do clones or snapshots, for you will require a CSI plugin that supports qcow backend. Otherwise, you could use the ephemeral disk. This creates an ephemeral snapshot on top of a PVC (this PVC could reference your hostdisk). A more complicated scenario would require backing file tracking and management. That's one of the reasons why we don't directly support qcow and the default is raw.

**Comment by lxm** [comment]
> well, you won't be able to do clones or snapshots, for this you will require a CSI plugin that supports Qcow backend. Otherwise, you could use the ephemeral disk. This creates an ephemeral snapshot on top of a PVC (this PVC could reference your hostdisk). A more complicated scenario would require backing file tracking and management. That's one of the reasons why we don't directly support qcow and the default is raw.

ephemeral disk requires `raw`, backing file `disk.raw` was hard coded in the source.

**Comment by alicefr** [comment]
> > well, you won't be able to do clones or snapshots, for this you will require a CSI plugin that supports Qcow backend. Otherwise, you could use the ephemeral disk. This creates an ephemeral snapshot on top of a PVC (this PVC could reference your hostdisk). A more complicated scenario would require backing file tracking and management. That's one of the reasons why we don't directly support qcow and the default is raw.
> 
> ephemeral disk requires `raw`, backing file `disk.raw` was hard coded in the source.

Yes, the source will be raw but KubeVirt will create a qcow layer for you on top of the raw image.

**Comment by alicefr** [comment]
If you really require a CSI storage driver that support qcow2 format, then you need to use an ad-hoc CSI storage driver.
