### ISSUE TITLE
Enable QEMU logs.

### ISSUE THREAD

**Issue by zhangzhangzf** [kubevirt/kubevirt#9634]
**Is your feature request related to a problem? Please describe**:
I encountered an issue during the virtual machine running. I only saw a small number of qemu logs in /var/log/libvirt/qemu/. My requirement is log files for each running virtual machine.Enable the settings of qemu logs and see the running logs of qemu in the launcher pod logs.

**Comment by alicefr** [comment]
@zhangzhangzf We should definetly improve and document this. Could you please have a look to this pr: https://github.com/kubevirt/kubevirt/pull/7000 and see if you can retrieve more logs.

/cc @victortoso

**Comment by zhangzhangzf** [comment]
> 
Thank you for your attention to this issue. My Kubevirt version is 0.50.0, and it does not take effect according to the PR configuration. The logs of QEMU will still not be refreshed. Can I upgrade to the Kubevirt version to solve this problem?

**Comment by zhangzhangzf** [comment]
> @zhangzhangzf We should definetly improve and document this. Could you please have a look to this pr: #7000 and see if you can retrieve more logs.
> 
> /cc @victortoso @iholder101

Thank you for your attention to this issue. My Kubevirt version is 0.50.0, and it does not take effect according to the PR configuration. The logs of QEMU will still not be refreshed. Can I upgrade to the Kubevirt version to solve this problem?

**Comment by zhangzhangzf** [comment]
> @zhangzhangzf We should definetly improve and document this. Could you please have a look to this pr: #7000 and see if you can retrieve more logs.
> 
> /cc @victortoso @iholder101

If I edit kubevirt CR to increase the log level of the launcher to 8, I can see that the number of logs in the launcher pod has significantly increased, and I can also see some classes such as QEMU_ MONITOR_ RECV_ What I want to ask is whether the internal QEMU logs in the launcher pod have been redirected to the launcher pod, so /var/log/libvirt/QEMU/default_aaa.log the logs in the files in the launcher pod are no longer refreshed?

**Comment by iholder101** [comment]
> > @zhangzhangzf We should definetly improve and document this. Could you please have a look to this pr: #7000 and see if you can retrieve more logs.
> > /cc @victortoso @iholder101
> 
> Thank you for your attention to this issue. My Kubevirt version is 0.50.0, and it does not take effect according to the PR configuration. The logs of QEMU in launcher pod(/var/log/libvirt/qemu/default_aaa.log) will still not be refreshed. Can I upgrade to the Kubevirt version to solve this problem?

Did you try to do so on an already running VM?
IIRC, this annotation is only effective if you apply it before the VM starts
