### ISSUE TITLE
virt-handler callbacks might be declared too early

### ISSUE THREAD

**Issue by jean-edouard** [kubevirt/kubevirt#9641]
**What happened**:
A bug was found where the SELinux policy would get installed even if the feature gate that disables it was set.
The root cause was that the callback for it in virt-handler was created before the first cache refresh, and callbacks get called once on creation.
At that point, the feature gate was not found and the policy was installed.

The fix is as simple as moving the callback creation to after the first cache refresh:
https://github.com/kubevirt/kubevirt/pull/9639/files

This issue is to remind us to go through the other callbacks and make sure they don't potentially suffer the same problem:
https://github.com/kubevirt/kubevirt/blob/9ef8b517cc500643b2360c3391132ccd6129971a/cmd/virt-handler/virt-handler.go#L314-L318

**Comment by larrydewey** [comment]
This is definitely a good started issue for new individuals to work on. Let's keep this on the radar as something to patch.

**Comment by syedabrarali** [comment]
@alicefr I would like to pick this issue up, while I did clone the repo and wanted to go ahead and move the SELinux policy callback after the first cache refresh, I noticed that this was already implemented. Do you still want a PR on this to close the issue?
Please let me know on how I can contribute to this issue.
