### ISSUE TITLE
no kind "VirtualMachine"

### ISSUE THREAD

**Issue by astranero** [kubevirt/kubevirt#9642]
**What happened**:
So I set up ubuntu 22.04 vm and installed kvm and other necessary configuration to it. 
I downloaded docker to this VM.
Next, following the documentation I installed kubevirt 0.59 into minikube, and tried running testvm, which didn't start.
This is log error for my testvm Virtual Machine:
error: no kind "VirtualMachine" is registered for version "kubevirt.io/v1" in scheme "pkg/scheme/scheme.go:28"

**What you expected to happen**:
VirtualMachine testvm should have started, but it didn't.

**How to reproduce it (as minimally and precisely as possible)**:
Just install 

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): 0.59
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: 
https://kubevirt.io/labs/manifests/vm.yaml
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by larrydewey** [comment]
@astranero does the VM have nested virtualization enabled?

**Comment by astranero** [comment]
Yes, I think so.

I used this command for hyper-v to allow nested virtualization:

Set-VMProcessor -VMName <VMName> -ExposeVirtualizationExtensions $true

And I also installed kvm & libevirtd.
I checked that kvm is set correctly with kvm-ok, and also according to systemctl status libevirtd was also running correctly.

Am I missing something?


Lähetetty sovelluksesta Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Lähettäjä: Larry Dewey ***@***.***>
Lähetetty: Wednesday, April 26, 2023 5:24:25 PM
Vastaanottaja: kubevirt/kubevirt ***@***.***>
Kopio: Kozheen Taher Esa ***@***.***>; Mention ***@***.***>
Aihe: Re: [kubevirt/kubevirt] no kind "VirtualMachine" (Issue #9642)


@astranero<https://github.com/astranero> does the VM have nested virtualization enabled?

**Comment by sudharsanomprakash** [comment]
@astranero 
1. Run this command on your ubuntu host, `virt-host-validate qemu` and share the output
2. You have to install  libevirtd as will be managed by virt-handler for each vm pod.
3. what is output for `kubectl get -n kubevirt kubevirt kubevirt` and `kubectl get all -n kubevirt`

**Comment by sudharsanomprakash** [comment]
Can you check the status of emulation in your Kubevirt? 

kubectl describe -n kubevirt kubevirt kubevirt

spec:
  ...
    configuration:
      developerConfiguration:
        useEmulation: true

**Comment by astranero** [comment]
I have useEmulation status true, which I set by using command `kubectl -n kubevirt patch kubevirt kubevirt --type=merge –patch '{"spec":{"configuration":{"developerConfiguration":{"useEmulation":true}}}}' 
 `

**Comment by p-alik** [comment]
I've faced various `error: no kind` in a cluster prepared following [getting-started.md#compile-and-run-it](https://github.com/kubevirt/kubevirt/blob/main/docs/getting-started.md#compile-and-run-it) without emulation
```
$ kubectl --namespace kubevirt get kubevirt kubevirt --output jsonpath="{.spec.configuration}"
{"developerConfiguration":{}}
$ kubectl logs --namespace kubevirt kubevirt.kubevirt.io/kubevirt
error: no kind "KubeVirt" is registered for version "kubevirt.io/v1" in scheme "pkg/scheme/scheme.go:28"
```

* `error: no kind "VirtualMachine" is registered for version "kubevirt.io/v1" in scheme "pkg/scheme/scheme.go:28"`
* `error: no kind "DataVolume" is registered for version "cdi.kubevirt.io/v1beta1" in scheme "pkg/scheme/scheme.go:28"`, also observed in [containerized-data-importer/issues/2859](https://github.com/kubevirt/containerized-data-importer/issues/2859)

`error: no kind "VirtualMachine"` persists with emulation.
```
$ kubectl patch --namespace kubevirt kubevirts.kubevirt.io/kubevirt --type=merge --patch='{"spec":{"configuration":{"developerConfiguration":{"useEmulation":true}}}}'
kubevirt.kubevirt.io/kubevirt patched
$ kubectl delete --filename  vm1_pvc.yml 
virtualmachine.kubevirt.io "vm1" deleted
$ kubectl create --filename  vm1_pvc.yml 
virtualmachine.kubevirt.io/vm1 created
$ kubectl logs virtualmachine.kubevirt.io/vm1
error: no kind "VirtualMachine" is registered for version "kubevirt.io/v1" in scheme "pkg/scheme/scheme.go:28"
```

**Comment by xpivarc** [comment]
> I've faced various `error: no kind` in a cluster prepared following [getting-started.md#compile-and-run-it](https://github.com/kubevirt/kubevirt/blob/main/docs/getting-started.md#compile-and-run-it) without emulation
> 
> ```
> $ kubectl --namespace kubevirt get kubevirt kubevirt --output jsonpath="{.spec.configuration}"
> {"developerConfiguration":{}}
> $ kubectl logs --namespace kubevirt kubevirt.kubevirt.io/kubevirt
> error: no kind "KubeVirt" is registered for version "kubevirt.io/v1" in scheme "pkg/scheme/scheme.go:28"
> ```

`kubectl logs --namespace kubevirt kubevirt.kubevirt.io/kubevirt` should not work

> 
>     * `error: no kind "VirtualMachine" is registered for version "kubevirt.io/v1" in scheme "pkg/scheme/scheme.go:28"`
> 
>     * `error: no kind "DataVolume" is registered for version "cdi.kubevirt.io/v1beta1" in scheme "pkg/scheme/scheme.go:28"`, also observed in [containerized-data-importer/issues/2859](https://github.com/kubevirt/containerized-data-importer/issues/2859)
> 
> 
> `error: no kind "VirtualMachine"` persists with emulation.
> 
> ```
> $ kubectl patch --namespace kubevirt kubevirts.kubevirt.io/kubevirt --type=merge --patch='{"spec":{"configuration":{"developerConfiguration":{"useEmulation":true}}}}'
> kubevirt.kubevirt.io/kubevirt patched
> $ kubectl delete --filename  vm1_pvc.yml 
> virtualmachine.kubevirt.io "vm1" deleted
> $ kubectl create --filename  vm1_pvc.yml 
> virtualmachine.kubevirt.io/vm1 created
> $ kubectl logs virtualmachine.kubevirt.io/vm1
> error: no kind "VirtualMachine" is registered for version "kubevirt.io/v1" in scheme "pkg/scheme/scheme.go:28"
> ```

`kubectl logs virtualmachine.kubevirt.io/vm1` this will not work as well. Logs can be only shown for Pods. You need to find a associated Pod for the VM

**Comment by xpivarc** [comment]
Hi @astranero, Can you share how did you produce this error?

**Comment by astranero** [comment]
I will send solution as soon as I am on my computer for this error.

Lähetetty sovelluksesta Outlook for iOS<https://aka.ms/o0ukef>
________________________________
Lähettäjä: xpivarc ***@***.***>
Lähetetty: Wednesday, August 23, 2023 8:05:01 PM
Vastaanottaja: kubevirt/kubevirt ***@***.***>
Kopio: Kozheen Taher Esa ***@***.***>; Mention ***@***.***>
Aihe: Re: [kubevirt/kubevirt] no kind "VirtualMachine" (Issue #9642)


Hi @astranero<https://github.com/astranero>, Can you share how did you produce this error?
