### ISSUE TITLE
apiservices.apiregistration.k8s.io "v1.subresources.kubevirt.io" not found

### ISSUE THREAD

**Issue by willzhang** [kubevirt/kubevirt#9645]
**Description**:
the docs Deleting KubeVirt[¶](https://kubevirt.io/user-guide/operations/updating_and_deletion/#deleting-kubevirt) not work

```
$ export RELEASE=v0.17.0
$ kubectl delete -n kubevirt kubevirt kubevirt --wait=true # --wait=true should anyway be default
```
maybe this resource already deleted
```
# kubectl delete apiservices v1.subresources.kubevirt.io
Error from server (NotFound): apiservices.apiregistration.k8s.io "v1.subresources.kubevirt.io" not found
```

**What you expected**:
run delete success

**URL**:
Provide a link to the documentation.

**Additional context**:
Add any other context about the issue here.

**Comment by larrydewey** [comment]
@willzhang can you provide us with some more information about what version of Kubernetes you are running, operating system, etc? Also, can you provide any logs from the system when the error occurs?
