### ISSUE TITLE
Switch to root user in the launcher pod

### ISSUE THREAD

**Issue by zhangzhangzf** [kubevirt/kubevirt#9647]
I am using version 0.59.0 of Kubevirt. I would like to ask how to switch to the root user after logging in to the launcher pod. When I execute 'su root', I am prompted to enter a password. Where can I see the password? I switched to root to view the logs under/var/log/libvirt/qemu.

**Comment by rmohr** [comment]
@zhangzhangzf one core feature of 0.59 is that the pod is not running as root anymore. This improves security. If you want to act in behalf of root for e.g. debugging in the context of virt-launcher, you would have to ssh into the node directly or into the virt-handler pod on the node and use `nsenter` or tools like that.

**Comment by rmohr** [comment]
> I switched to root to view the logs under/var/log/libvirt/qemu.

The logs should be readable also without root, since we only have the qemu user in the pod and that user is writing the pods (or does the user only have write-only?).

**Comment by zhangzhangzf** [comment]
> > I switched to root to view the logs under/var/log/libvirt/qemu.
> 
> The logs should be readable also without root, since we only have the qemu user in the pod and that user is writing the pods (or does the user only have write-only?).

Thank you for your reply. Users cannot switch to /var/log/libvirt/qemu as qemu. My fundamental problem is that the logs in the /var/log/libvirt/qemu directory have not been refreshed, and when encountering qemu issues, I am unable to view the logs. How should I solve this problem?

**Comment by xpivarc** [comment]
@zhangzhangzf Can you check `/var/"run/libvirt/qemu/log/<something>`?

**Comment by zhangzhangzf** [comment]
> /var/"run/libvirt/qemu/log/<something

There is no directory named log under /var/run/libvirt/qemu/.

**Comment by rmohr** [comment]
> Thank you for your reply. Users cannot switch to /var/log/libvirt/qemu as qemu. My fundamental problem is that the logs in the /var/log/libvirt/qemu directory have not been refreshed, and when encountering qemu issues, I am unable to view the logs. How should I solve this problem?

You should see all qemu logs pipe to the virt-launcher log stream (`component=qemu`). Maybe you can share your `virt-launcher` logs and explain the issue you are facing?

**Comment by zhangzhangzf** [comment]
> 

You can view the logs of my launcher pod through this link. In the logs, only a few are related to qemu subcomponents. Please help me check if QEMU's logs have been correctly redirected.
https://talon-1251707795.cos.ap-nanjing.myqcloud.com/virt-launcher-vvictor-test3-mwd74.log

**Comment by xpivarc** [comment]
@zhangzhangzf In order to see more qemu logs one would need to increase verbosity or tweak a log filter.
