### ISSUE TITLE
VM's status should reference the underlying pod

### ISSUE THREAD

**Issue by davidvossel** [kubevirt/kubevirt#965]
UI's need a way to associate a VM with its active pod. We want the KubeVirt runtime to be in control over this association because it's possible in the future (once features like migrations are introduced) that we'll have multiple pods per a VM.  In that situation, we want the VM to only reference the currently active pod. 

This gives the UI a stable way to retrieve the active pod that will continue to work regardless of if VM's are backed by multiple pods in the future.

**Comment by rmohr** [comment]
Let us document for which use-cases this is important, and for which not. Right now I know about two cases where I would want someone to go through the VM abstraction:

 * metrics
 * getting to the pod if something goes wrong

I think for most cases, the vm should provide everything to be treated as the atomic base for virtualisation based actions. Things which would definitely go wrong:

 * Making assumptions about  the vm status via the pod status
 * Making assumptions about the specific pod structure
 * trying to contact  the vm through `exec` via the pod

**Comment by rmohr** [comment]
@yuvalif I think that you have a very good example here for something which we want to show on the vm too.

**Comment by rmohr** [comment]
@cynepco3hahue let's check if we are passing all of the conditions through right now regarding to scheduling issues. You added at least parts of it.

**Comment by rmohr** [comment]
/close

We pass through the schedulable condition and the ready condition now. That should be a good base set.

**Comment by rmohr** [comment]
/reopen
/remove-lifecycle rotten

we still may want to have a readable reference in the status.

**Comment by fabiand** [comment]
Would a simple `status.podName` be pargmatic enough?
