### ISSUE TITLE
If virtiofs filesystem VPCs are used, disk hotplug fails on validation

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#9653]
**What happened**:

Right now we only allow hot-plugging through our hotplug subresource. When this happens, the actual spec updates are done by our internal user. This triggers in turn additional validation logic:

```go
		if webhooks.IsKubeVirtServiceAccount(ar.Request.UserInfo.Username) {
			hotplugResponse := admitHotplug(newVMI.Spec.Volumes, oldVMI.Spec.Volumes, newVMI.Spec.Domain.Devices.Disks, oldVMI.Spec.Domain.Devices.Disks, oldVMI.Status.VolumeStatus, newVMI, admitter.ClusterConfig)
			if hotplugResponse != nil {
				return hotplugResponse
			}
		}
```

This additional validation check does not consider `spec.domain.devices.filesystems` and will fail because it thinks that one volume does not have a source volume defined:

```json
{"component":"virt-controller","level":"info","msg":"reenqueuing VirtualMachineInstance kubevirt-test-privileged2/testvmi-jv66c","pos":"vmi.go:306","reason":"admission webhook \"virtualmachineinstances-update-validator.kubevirt.io\" denied the request: number of disks (1) does not equal the number of volumes (2)","timestamp":"2023-04-22T18:55:14.513147Z"}
```	

This was discovered as a side-effect of a mistake in a PR.

 * Example job: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8293/pull-kubevirt-e2e-k8s-1.24-sig-compute/1649835730626678784
 * Example virt-controller log: https://storage.googleapis.com/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/8293/pull-kubevirt-e2e-k8s-1.24-sig-compute/1649835730626678784/artifacts/k8s-reporter-parallel/1/pods/1_kubevirt_virt-controller-7b6d7944fd-f4744-virt-controller.log

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Create a VMI with a virtiofs filesystem attached. Then try to hotplug a disk.
**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by rmohr** [comment]
@awels @vladikr FYI

**Comment by awels** [comment]
Yeah definitively a bug, should be a relatively simple fix, when enumerating the volumes, also include the filesystem section.

**Comment by Gentoli** [comment]
The validation also blocks force stop:
``` sh
bash-4.4 ~ $ virtctl stop windows-0adqro --grace-period 0 --force -n default
Error force stopping VirtualMachine, Internal error occurred: admission webhook "virtualmachineinstances-update-validator.kubevirt.io" denied the request: number of disks (2) does not equal the number of volumes (3)
```
