### ISSUE TITLE
Unable to setup vms,when starting it using virtctl the pod is running and than going in terminating phase 

### ISSUE THREAD

**Issue by ayuSH8033** [kubevirt/kubevirt#9664]
kubectl logs virt-launcher-testvm-d8s75 is giving
**{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:86","timestamp":"2023-04-24T23:36:20.237487Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:89","timestamp":"2023-04-24T23:36:20.237558Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:519","timestamp":"2023-04-24T23:36:20.238618Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/virtqemud-sock': No such file or directory')","pos":"libvirt.go:527","timestamp":"2023-04-24T23:36:20.238934Z"}
{"component":"virt-launcher","level":"error","msg":"failed to start virtqemud","pos":"libvirt_helper.go:250","reason":"fork/exec /usr/sbin/virtqemud: errno 0","timestamp":"2023-04-24T23:36:20.239471Z"}
panic: fork/exec /usr/sbin/virtqemud: errno 0

goroutine 19 [running]:
kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/util.LibvirtWrapper.StartVirtquemud.func1()
pkg/virt-launcher/virtwrap/util/libvirt_helper.go:251 +0x4ce
created by kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/util.LibvirtWrapper.StartVirtquemud
pkg/virt-launcher/virtwrap/util/libvirt_helper.go:218 +0x65
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 12 with status 512","pos":"virt-launcher-monitor.go:120","timestamp":"2023-04-24T23:36:20.244316Z"}
{"component":"virt-launcher-monitor","level":"error","msg":"dirty virt-launcher shutdown: exit-code 2","pos":"virt-launcher-monitor.go:138","timestamp":"2023-04-24T23:36:20.244506Z"}**
I have checked the libvrt daemon,its running perfectly fine,also restarted it multiple times but still no luck.Also triend uninstalling and re-installing kubevirt but issue is still not solved

**Comment by ayuSH8033** [comment]
As per official doc for setup on minikube it is supposed to have 7 pods running in kubevirt namespace but its showing only 6,replica set,daemon set and deployments are all running fine

**Comment by vasiliy-ul** [comment]
Looks similar to https://github.com/kubevirt/kubevirt/issues/9511. Try running minikube with containerd: `minikube start --container-runtime=containerd`

**Comment by ayuSH8033** [comment]
Tanks @vasiliy-ul  minikube start --container-runtime=containerd worked for me
