### ISSUE TITLE
Document KubeVirt building system

### ISSUE THREAD

**Issue by alicefr** [kubevirt/kubevirt#9666]
**Is your feature request related to a problem? Please describe**:
Newcomers are sometimes confused about how we build container images for KubeVirt. Providing documentation on how the build system work could help people to grasp KubeVirt building system.

The documentation should include:
* brief introduction of bazel and distroless images
* explanation of where the container images are defined (e.g BUILD.bazel)
* how we create the rpm tree and update it
* how the bazel-build-container is created and how you can manually run commands with bazel
* where are the images tarballs located in the bazel build container system and how we can load them locally with podman/docker in order to inspect the container filesystem

**Comment by Gre8t** [comment]
I can get it done

**Comment by Electronic-Waste** [comment]
Can you  assign it to me @alicefr ? I'm a newcomer of this community. I think I can provide a newcomer's insight to this issue while getting familiar with this tool. Also, I'm a k8s developer. You can look into my profile to check my competence.

**Comment by yitingdc** [comment]
any progress?

**Comment by alicefr** [comment]
> any progress?

In the end nobody finished this
