### ISSUE TITLE
non-elected virt-operator has kubevirt_workqueue_depth{name="virt-operator"} 1

### ISSUE THREAD

**Issue by jrcichra** [kubevirt/kubevirt#9675]
**What happened**:
While writing alerts to track the workqueue_depth of kubevirt controllers, I noticed that the non-elected virt-operator outputs `kubevirt_workqueue_depth{name="virt-operator"} 1`. 

**What you expected to happen**:
I would expect the workqueue of a virt-operator to be 0 unless it had acquired the lease and there is still work in its queue.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.
Download and apply `kubevirt-cr.yaml` and `kubevirt-operator.yaml` unmodified into a fresh cluster. Port forward port 8443 on both virt-operator pods and run `curl -s -k https://localhost:8443/metrics | grep depth`. If Kubevirt is fully deployed, the elected operator will have `kubevirt_workqueue_depth{name="virt-operator"} 0`, but the non-elected virt-operator will have kubevirt_workqueue_depth{name="virt-operator"} 1. You can see which virt-operator holds the lease by running `kubectl get endpoints -n kubevirt virt-operator -o yaml` and looking at the leader annotation.

**Additional context**:
This was discovered when building alerts on Kubevirt workqueue depths. Specifically an alert that validates the workqueue_depth across virt-operators was progressing towards 0.

**Environment**:
- KubeVirt version (use `virtctl version`): Both v0.59.0 and v1.0.0-alpha.0
- Kubernetes version (use `kubectl version`): 1.23.15
- VM or VMI specifications: Bare metal / Kubevirt within Kubevirt
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): Debian Bullseye
- Kernel (e.g. `uname -a`): 6.1.15
- Install tools: kubectl
- Others: N/A

**Comment by usrbinkat** [comment]
By chance, can you also look into this behavior on other controllers for a comparison? Possibly the virt controller as an example?

**Comment by jrcichra** [comment]
Sure, it looks like I hit a similar issue for virt-controller the other day when setting up VolumeSnapshots.
`kubectl get endpoints -n kubevirt virt-controller -o yaml` has `holderIdentity`: `virt-controller-55dd5f557d-mmvm4`.

If I look at the metrics, `sum by (pod) (kubevirt_workqueue_depth{kubernetes_namespace="kubevirt",name="virt-controller-snapshot-crd",pod_kubevirt_io="virt-controller"})` shows two results:

{pod="virt-controller-55dd5f557d-dq5nl"} | 2
{pod="virt-controller-55dd5f557d-mmvm4"} | 0

I need to dig into the KubeVirt code to see how this is implemented, but perhaps this is a bug in some common logic?
