### ISSUE TITLE
vm paused due to storage IOError

### ISSUE THREAD

**Issue by whsasf** [kubevirt/kubevirt#9704]
**What happened**:
vm continuous paused ,the state change between paused and running , but vm can not access. can see IOError fron vm log:

{"component":"virt-launcher","level":"info","msg":"kubevirt domain status: Paused(3):IOError(5)","pos":"client.go:289","timestamp":"2023-05-05T04:36:04.257222Z"}

the storage is  a  hDD(not SSD) on host, using pv and pvc . Do not know why IOError happened ?  should i use a SSD ? 

i can also find  'No VolumeSnapshotClass for gold' warning in virt-controller log ,does IOError has anything to do with it ? 

{"component":"virt-controller","level":"warning","msg":"No VolumeSnapshotClass for gold","pos":"snapshot.go:641","timestamp":"2023-05-05T04:42:35.303358Z"}

**What you expected to happen**:
should not have IOError

**Environment**:
- KubeVirt version (use `virtctl version`): 0.58.1
- Kubernetes version (use `kubectl version`): 1.23.17
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): ubuntu22.04
- Kernel (e.g. `uname -a`): 5.15.0-71-generic
- Install tools: N/A
- Others: N/A

**Comment by zhangzhangzf** [comment]
> **What happened**: vm continuous paused ,the state change between paused and running , but vm can not access. can see IOError fron vm log:
> 
> {"component":"virt-launcher","level":"info","msg":"kubevirt domain status: Paused(3):IOError(5)","pos":"client.go:289","timestamp":"2023-05-05T04:36:04.257222Z"}
> 
> the storage is a hDD(not SSD) on host, using pv and pvc . Do not know why IOError happened ? should i use a SSD ?
> 
> i can also find 'No VolumeSnapshotClass for gold' warning in virt-controller log ,does IOError has anything to do with it ?
> 
> {"component":"virt-controller","level":"warning","msg":"No VolumeSnapshotClass for gold","pos":"snapshot.go:641","timestamp":"2023-05-05T04:42:35.303358Z"}
> 
> **What you expected to happen**: should not have IOError
> 
> **Environment**:
> 
> * KubeVirt version (use `virtctl version`): 0.58.1
> * Kubernetes version (use `kubectl version`): 1.23.17
> * VM or VMI specifications: N/A
> * Cloud provider or hardware configuration: N/A
> * OS (e.g. from /etc/os-release): ubuntu22.04
> * Kernel (e.g. `uname -a`): 5.15.0-71-generic
> * Install tools: N/A
> * Others: N/A

What is the backend storage you are using.

**Comment by zhangzhangzf** [comment]
What is the backend storage you are using.

**Comment by chenxinlong** [comment]
Hi, did you solve this problem ? Currently I'm encountering the same problem.

**Comment by chenxinlong** [comment]
@zhangzhangzf  Hi, I'm encountering the same problem you can find in https://github.com/kubevirt/kubevirt/issues/9708 

I'm using `rbd.csi.ceph.com` as my sc provisioner.

**Comment by zhangzhangzf** [comment]
> @zhangzhangzf Hi, I'm encountering the same problem you can find in #9708
> 
> I'm using `rbd.csi.ceph.com` as my sc provisioner.

Add  parameter(cache: writeback) for every disk. I am very interested in how Ceph RBD triggers this issue, and I would like to discuss it in detail on WeChat(zhangzhangzf).

**Comment by zhangzhangzf** [comment]
加我微信zhangzhangzf



---Original---
From: ***@***.***&gt;
Date: Mon, May 8, 2023 21:38 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [kubevirt/kubevirt] vm paused due to storage IOError (Issue#9704)




 
@zhangzhangzf  Hi, I'm encountering the same problem you can find in #9708
 
I'm using rbd.csi.ceph.com as my sc provisioner.
