### ISSUE TITLE
kubevirt_vmi_cpu_affinity metric is enriched with an excessive amount of labels

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#9713]
**What happened**:

In https://github.com/kubevirt/kubevirt/pull/5191 the `kubevirt_vmi_cpu_affinity` metric got introduced. Given X pcpus and Y vcpus, there can be up to X*Y labels generated for a single VM. 

A concrete example: 192 pcore and 48 vcpu lead to 48*192 (9216!) labels. This is something which can not easily be digested by all kinds of metric pipelines.

**What you expected to happen**:

Let's see that we shrink or remove this. Since this is "just" a boolean map expressing CPU pinning layout, this looks like something which should not be exposed via core kubevirt via prometheus metrics.

Just doing this for explicit cpu pinning may be an option, but even then getting 50-100 labels would be the result which is probably still above an acceptable number of labels per metric, considering that VM labels and such are added as well and we want to leave room for user-specific labels. 

**How to reproduce it (as minimally and precisely as possible)**:

Starting a VM with a single vCPU without explicit pinning, has an affinity for all CPUs.

Here an example for a single vCPU on a 8-core machine:

```
# virsh vcpuinfo default_fedora
VCPU:           0
CPU:            4
State:          running
CPU time:       33.5s
CPU Affinity:   yyyyyyyy
```

Note the 8 `y`s.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by rmohr** [comment]
@sradco  FYI

**Comment by rmohr** [comment]
@dhiller @vladikr since you were tagged on the initial PR, any thoughts?

**Comment by sradco** [comment]
I think we shouldn't report the affinity map at all and only report for each VM the number of CPU affinity that it has.

**Comment by rmohr** [comment]
> I think we shouldn't report the affinity map at all and only report for each VM the number of CPU affinity that it has.

Thanks @sradco. The direction sounds good to me. Could you elaborate for me what `only report for each VM the number of CPU affinity that it has` exactly means?

**Comment by sradco** [comment]
Perhaps we can split this to 2 metrics. It will not be a full replacement, but can still be valueable.
- Aggregate the libvirt metric by VM.
- Aggregate the libvirt metric by CPU.

@rmohr WDYT?

**Comment by machadovilaca** [comment]
in my point of view options could be:

a) `kubevirt_vmi_cpu_affinity{pcore_count="12", vcpu_0="100000100011", vcpu_1="...}` - having a list of the CPU affinity where 1 is true and 0 false, reducing the number of labels to the number of vcpus + 1

b) `kubevirt_vmi_cpu_affinity{pcore_count="12", vcpu_0="4", vcpu_1="...}` - having the `true` count has the value of the label, still the same number of labels as a option a), but its easier for human readability of the number of affinities

c) `kubevirt_vmi_cpu_affinity{vcpu_count="4", pcore_count="12", affinities="4,12,0,2"}` - having a list of counts, where each value is the count of CPU affinities set to true of each vcpu, reducing the number of labels to 3

@sradco @rmohr

**Comment by sradco** [comment]
Option B makes sense to me. It is more readable, We can still identify vcpus that have a large number of affinities set to true with this option, detect CPU affinity misconfigurations, monitor CPU affinity changes over time and do capacity planning and resource allocation.

**Comment by machadovilaca** [comment]
as we discussed @sradco, current suggestion is:
having 3 metrics: `kubevirt_vmi_cpu_affinity`, `kubevirt_node_vcpu_count`, `kubevirt_node_pcores_count`

`kubevirt_vmi_cpu_affinity{affinities="4,12,0,2" ..., name="vmi-fedora", node="node01"} 18` - the value of the metric shows the total number of pCores affinities for a given VMI. The `affinities` label give more detail on how those affinities are distributed across the vCPUs.

`kubevirt_node_vcpu_count{node="node01", ..."} 4` - total number of vCPUs on a given node

`kubevirt_node_pcores_count{node="node01", ...} 12` - total number of pCores per vCPU on a given node.

---

We can also use `kube_node_status_capacity` that gives us `kubevirt_node_vcpu_count * kubevirt_node_pcores_count`, but maybe makes sense to have the individual counts

**Comment by sradco** [comment]
Yes
