### ISSUE TITLE
How to build kubevirt with containerd runtime, without docker and podman on linux.

### ISSUE THREAD

**Issue by Devin-Yue** [kubevirt/kubevirt#9718]
**Description**:
How to build Kubevirt with Containerd runtime, without Docker and Podman on Linux.

**What you expected**:
All the methods about how to compiler Kubevirt using source codes with different Runtimes on Linux should be included into the Getting Start Page.

**URL**:
[Provide a link to the documentation.](https://github.com/kubevirt/kubevirt/blob/release-0.59/docs/getting-started.md#getting-started)

**Additional context**:
Add any other context about the issue here.

**Comment by Devin-Yue** [comment]
In my setup, there is no docker and podman running. Only the containerd running , and the containerd installed using the binary file.
From the getting-start, I have no idea about how to build using source coeds.

**Comment by alicefr** [comment]
Is it now possible to build container images only using containerd? Not to my knowledge. If you only have containerd you can run containers but not build them.

**Comment by Devin-Yue** [comment]
OK, understood.
