### ISSUE TITLE
kubevirt migration for customized device

### ISSUE THREAD

**Issue by Yongbozzz** [kubevirt/kubevirt#9739]
We enabled vhost-blk device support in Kuebvirt ,costumer can use it like this :
          - disk:
              bus: virtio
            name: spdk-vhost-blk1
     . . .
      volumes:
      - name: spdk-vhost-blk1
        spdkVhostBlkDisk:
          capacity: 546G

Now we want to enable kubevirt migration function for vhost-blk device , could you please give me some reference ?

**Comment by alicefr** [comment]
@Yongbozzz for enabling vhost blk you mean you have a forked kubevirt version with the modifications, right?

**Comment by Yongbozzz** [comment]
yes, I forked v0.52.0 , the version might be a little bit out-of-time, have already solved my issue on v0.58.0, the migration for vhost-blk worked, I will close the issue
