### ISSUE TITLE
VM Export of FileSystem PVC fails due to permissions issue

### ISSUE THREAD

**Issue by kreeuwijk** [kubevirt/kubevirt#9742]
**What happened**:
When running vanilla Kubernetes with containerd and the `device_ownership_from_security_context` feature enabled, I can successfully export a PVC of mode `Block`. But if the PVC is of mode `FileSystem`, the permissions on the disk.img file prevent access by the export pod. If I shell into the `virt-export-<export-name>` pod, I can see:

```
bash-5.1$ ls -alh /export-volumes/restore-8e81ff89-c84b-4693-bc60-ad389d62aefe-disk-0/
total 9.6G
drwxrwsrwx 2   0   107 4.0K May 12 13:59 .
drwxr-xr-x 3   0  root 4.0K May 15 09:53 ..
-rw-rw---- 1 107   107  48G May 12 14:42 disk.img

bash-5.1$ id
uid=1001(nonroot-user) gid=1001 groups=1001,107
```

Even though the `virt-export-<export-name>` pod does receive `fsGroup=107` from the container, this seems to still not be enough to access the file, as you get a Permission Denied error when trying to access the file. The `device_ownership_from_security_context` feature will allow access to work for `/dev` devices, hence a Block mode PVC works fine. But I think the feature does nothing for FileSystem PVCs.

Likely, the pod needs to run as the `107` user in order to successfully be able to access the `disk.img` file from the FileSystem PVC.

**What you expected to happen**:
VM Export working normally on FileSystem PVCs.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create a VM with a dataVolume of type FileSystem and RWX access
2. Attempt to export the VM
3. Attempting to download the `dir/disk.img` file directly using curl will result in a 403 error
4. Attempting to download the `disk.tar.gz` file will cause an error to be logged in the `virt-export-<export-name>` pod, that tar was unable to compress `disk.img` due to insufficient permissions.

**Environment**:
- KubeVirt version (use `virtctl version`): 0.59.0
- Kubernetes version (use `kubectl version`): 1.26.3
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: Bare metal (Canonical MaaS)
- OS (e.g. from /etc/os-release): Ubuntu 22.04 LTS
- Kernel (e.g. `uname -a`): 5.15.0-71-generic
- Install tools: Cluster API

**Comment by kreeuwijk** [comment]
We are using Portworx Enterprise for storage.

That bug mentions the same request:

> Export pod should run as run as user 107.

> So I checked https://github.com/kubevirt/kubevirt/blob/main/cmd/virt-launcher/BUILD.bazel#L111-L118 against https://github.com/kubevirt/kubevirt/blob/main/cmd/virt-exportserver/BUILD.bazel#L32-L39 and it doesn't look like the virt-export server is running as 107, but 1001.

**Comment by akalenyu** [comment]
The bug is about storage which does not support fsGroup,
but, looking at your logs again, the fsGroup gets applied correctly
```
-rw-rw---- 1 107   107  48G May 12 14:42 disk.img

groups=1001,107
```
So `permission denied` should not occur...
Is it possible selinux/apparmor is the source for the permission denied err?
Could try scratching out this possibility by looking at `/var/log/audit/audit.log`

**Comment by kreeuwijk** [comment]
SELinux is disabled but Apparmor is running. I'll take a look.
