### ISSUE TITLE
Let our HA configuration scale automatically when masters are added or deleted

### ISSUE THREAD

**Issue by rmohr** [kubevirt/kubevirt#975]
Picking up https://github.com/kubevirt/kubevirt/issues/727#issuecomment-366983555 from @alezzandro.

We can make our HA setup scale automatically, if we do the following:

 * Use a DaemonSet
 * Give it the right toleration: `tolerations: [key: node-role.kubernetes.io/master]`
 * Add the right label selector by matching [node-role.kubernetes.io/master](https://github.com/kubernetes/kubernetes/blob/f542fe12837560d991218289e8297dac7362c7ba/cmd/kubeadm/app/constants/constants.go#L88)

**Comment by rmohr** [comment]
@cynepco3hahue FYI

**Comment by cynepco3hahue** [comment]
@rmohr I can easily change it to daemon set, but I less sure about additional `toleration` selector, because we can not control an environment where `virt-controller` will run, so we leave it on user responsibility to set correct toleartion on the node.

**Comment by rmohr** [comment]
@cynepco3hahue afaik these labels and taints are now standardized values which you can rely on.

**Comment by fabiand** [comment]
Is that really a good and recommended pattern to use a daemonset for this?

Maybe rather do vertical autoscaling?

**Comment by rmohr** [comment]
@fabiand yes daemonset, the background is that it is the most robust way. The daemonset can schedule on its own and you need less complex affinity and selector rules. Good for critical components.

**Comment by rmohr** [comment]
> I do see the obvious benefits, I just wonder about the not-so-obvious drawbacks.

Which are?

**Comment by fabiand** [comment]
> Which are?

That's what I wanted to brain storm. So far I did not see the pattern of having a daemonset as a measure to increase the high availabillity.

**Comment by cynepco3hahue** [comment]
We still need to check that OpenShift has the same labels and taints as k8s.

**Comment by cynepco3hahue** [comment]
@rmohr I check k8s-1.10.4 and I do not see any taints on the master node, so I think the single thing that we need to set on the daemon set is label selector `node-role.kubernetes.io/master`.

**Comment by rmohr** [comment]
@cynepco3hahue make sure that you just don't see them because we remove them: https://github.com/kubevirt/kubevirtci/blob/master/k8s/scripts/node01.sh#L8

**Comment by cynepco3hahue** [comment]
@rmohr Oh I see thanks for pointing me

**Comment by cynepco3hahue** [comment]
To summarize:
- change type from `Deployment` to `DaemonSet`
- add label selector to `DaemonSet` spec
```
spec:
  selector:
    matchLabels:
      name: node-role.kubernetes.io/master
```
- add toleration to pod spec
```
template:
   ...
    spec:
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
```

Above  true for both k8s and OpenShift.
After the change you will see `virt-controller` pod only on master node.

**Comment by ant31** [comment]
Sorry, I don't know anything about the project, so I have some naive question: 

1. Why does it has to run on master nodes? 
2. Is there an issue to run two virt-controller on the same node, a part from solving HA? 
e.g: it's an issue for LB that use hostNetwork, it's an issue for log shipper that would ship logs twice....
3. In which cases it must be scaled up ?

**Comment by rmohr** [comment]
Hi @ant31 

> Sorry, I don't know anything about the project, so I have some naive question:

That are sometimes the best ones.

> 
> 1. Why does it has to run on master nodes?

It does not have to run on master nodes. We can simply faster recover in case of e.g. a cluster-split.
This way we can ensure that virt-controller and virt-api already runs in the cluster-part which will recover.
If we don't do that, after kubernetes itself recovers in a cluster part, it will first have to start the kubevirt components again, pulling images (which may or may not work in case of emergencies), and then finally the kubevirt-related apis and controllers will recover.

So in the worst case we may not be able to recover at all (because we may not be able to pull images), in the average case we would recover slower.

We could for sure achieve similar things via other affinity and anti-affinity settings, but this one seems to be the best out-of-the-box setting which would work for most, since k8s itself relies on it.

> 2. Is there an issue to run two virt-controller on the same node, a part from solving HA?
>    e.g: it's an issue for LB that use hostNetwork, it's an issue for log shipper that would ship logs twice....

virt-controller does leader-election, so it will not harm kubevirt if they run on the same node, but we will not have the same benefits like described above.

> 3. In which cases it must be scaled up ?

virt-api may need to scale up together with the apiserver if a significant amount of users and controllers are operationg on vms. So here too, it does not hurt if we automatically scale with new apiserver instances by default. virt-api can scale horizontally, like the apiserver.

I hope that helps.

**Comment by rmohr** [comment]
What I forgot to mention: Our controller are tightly coupled to e.g. pods, including  finalizers. So the garbage collector of k8s and other components can continue their work faster in a normal fashion if our controllers and APIs are recovering fast.

**Comment by ant31** [comment]
Thank for the detailed answer. 

1. In some cases the user don't have access to master and scale master: most managed kubernetes don't provide access to the control plane (GKE, azure, openshift online?).  
Those user can't even run workload on nodes role=master. There's also cases where only cluster administrator can deploy on masters/kube-system and other teams are limited to one namespace.  

2. It assumes that api-master and virt-controller are scaling at exactly the same rate. 

I'm not saying that daemonset is necessarily bad but if it's a daemonset it should nodeSelect it's own label e.g:  `kubevirt-control-plane=true`. The downside is that user must label nodes and still requires some super-user powers. 

I'd use deployment with pod-anti-affinity rules, to distribute pods on different nodes for HA when possible, and use podPriorityClass (https://kubernetes.io/docs/concepts/configuration/pod-priority-preemption/) to re-schedule the pod in priority in case of outage and also protect it against eviction.

**Comment by rmohr** [comment]
> Thank for the detailed answer.
> 
> 1. In some cases the user don't have access to master and scale master: most managed kubernetes don't provide access to the control plane (GKE, azure, openshift online?).
>    Those user can't even run workload on nodes role=master. There's also cases where only cluster administrator can deploy on masters/kube-system and other teams are limited to one namespace.

Out of curiosity: They can't even schedule stuff on master nodes if they are cluster-admins and explicitly create pods with the corresponding tolerations?

Anyway, KubeVirt needs a bare-metal cluster. It does not run on these providers. KubeVirt is an add-on which needs to be installed by cluster-admins. Users can't install it on their own.

> 2. It assumes that api-master and virt-controller are scaling at exactly the same rate.

virt-api scales horizontally and should normally get less traffic than the k8s apiserver. So in most cases we should be fine if we scale with the k8s apiserver. virt-controller does not scale horizontally (like  the k8s controller-manager). There is always only one elected master active. By starting controllers on all master nodes, we have a passive controller ready-to-jump-in.

Overall it seems to me to be a good default option. If needed people can adjust the KubeVirt manifests based on their needs. They can also switch between `Deployment` and `DaemonSet` if they like.

> 
> I'm not saying that daemonset is necessarily bad but if it's a daemonset it should nodeSelect it's own label e.g: `kubevirt-control-plane=true`. The downside is that user must label nodes and still requires some super-user powers.

If the here suggested default based on `DaemonSet` really does not work for a significant amount of people, then we would probably be better off with what you suggest. It does not look like that to me, but I can be wrong.

**Comment by rmohr** [comment]
> There's also cases where only cluster administrator can deploy on masters/kube-system and other teams are limited to one namespace.

And to highlight that: KubeVirt can only be installed and run once on a whole cluster. It also comes with its own aggregated RBAC roles, ...

**Comment by fabiand** [comment]
The idea ot use Deployment with pod anti-affinity rules sounds charming to me.

It looks better controllable than the DaemonSet approach.

Just my 2ct

**Comment by fabiand** [comment]
DaemonSet sound pretty greedy to me, but increasing our controller scale
looks like a low-hanging fruit.

**Comment by rmohr** [comment]
/reopen
/remove-lifecycle rotten

We still need to improve here.
