### ISSUE TITLE
Release Arm64 image and binary

### ISSUE THREAD

**Issue by zhlhahaha** [kubevirt/kubevirt#9756]
According to the discuss in KubeVirt community meeting on 2023-02-15, we may need to do following things before we can have official Arm64 release:
- [x] the status of core features on the Arm64 platform
- [x] Enable conformance test on Arm64 platform
- [x] Support non-HT cores in the VMI API

**Comment by zhlhahaha** [comment]
Are there any other requirements before we can have an official Arm64 release?
ping: @rmohr @davidvossel @xpivarc @EdDev @rthallisey @andreabolognani @stu-gott @vladikr

**Comment by zhlhahaha** [comment]
**1. the status of core features on the Arm64 platform**
I have write down the documents of support list of core features on Arm64, it contains:
The PR https://github.com/kubevirt/user-guide/pull/682

- Supported and unsupported Devices on Arm64
- The status of all feature gates on Arm64
- Verified all pages under the subtitle “Operations” and “Virtual Machines” in  https://kubevirt.io/user-guide , and summarized the unsupported contents on Arm64.

**2. Enable conformance test on Arm64 platform**
As the image ‘fedora-with-test-tooling’ is used in the conformance tests,  I have submitted a patch series to build the multi-arch image.
https://github.com/kubevirt/kubevirtci/issues/1004 
Once we have the multi-arch image, I can try to enable the conformance tests.

**3. Support non-HT cores in the VMI API**
@rthallisey is working on this. I am also free to provide support.

**Comment by andreabolognani** [comment]
@rthallisey excellent! Have we actually published any multi-arch images yet? For alpha or beta releases, for example?

**Comment by rthallisey** [comment]
Looking at v1.0.0-beta.0 builds, I don't see the multi-arch manifest for the v1.0 alpha or beta tag.  I'm not familiar with the release tooling, but to get multi-arch manifests the tool would need to build like this:
```
BUILD_ARCH=aarch64,x86_64 make bazel-build-images
BUILD_ARCH=aarch64,x86_64 make bazel-push-images
```

**Comment by andreabolognani** [comment]
Okay so, making sure that the release process is actually producing multi-arch images is an item for the task list :)

**Comment by rthallisey** [comment]
Support non-HT cores in the VMI API - https://github.com/kubevirt/kubevirt/pull/9758

**Comment by zhlhahaha** [comment]
> Okay so, making sure that the release process is actually producing multi-arch images is an item for the task list :)

Yes, just as @rthallisey said, we have process to build multi-arch images. To make sure the publish multi-arch image process works well and stable, I can create a new periodic job to build and publish multi-arch images.

**Comment by rmohr** [comment]
> Looking at v1.0.0-beta.0 builds, I don't see the multi-arch manifest for the v1.0 alpha or beta tag. I'm not familiar with the release tooling, but to get multi-arch manifests the tool would need to build like this:
> 
> ```
> BUILD_ARCH=aarch64,x86_64 make bazel-build-images
> BUILD_ARCH=aarch64,x86_64 make bazel-push-images
> ```

I think to support that, we have to ensure that this job: https://github.com/kubevirt/project-infra/blob/eed6a1d124797cc48cc15c56cff1a4ebfb4107d7/github/ci/prow-deploy/files/jobs/kubevirt/kubevirt/kubevirt-postsubmits.yaml#L3 is run with that configuration. That should be possible by changing `automation/release.sh`. Then we should have multi-arch releases by default.

**Comment by zhlhahaha** [comment]
As we now have the following PRs merged, we well have multi-arch KubeVirt images and virtctl binary in release v1.0.0. Does my understand right?
https://github.com/kubevirt/kubevirt/pull/9828
https://github.com/kubevirt/kubevirt/pull/9832

**Comment by zhlhahaha** [comment]
By the way, I am not sure if it is too late, the following PR is import for Arm64 which allows cpu pinning works on Arm64 platform.
https://github.com/kubevirt/kubevirt/pull/9758

Additionally, I have prepared a comprehensive document providing a evaluation of the status of kubeVirt on Arm64.
https://github.com/kubevirt/user-guide/pull/682
