### ISSUE TITLE
When I use nat network interface, guest os can't be accessed

### ISSUE THREAD

**Issue by ninelinesevduk** [kubevirt/kubevirt#9759]
**What happened**:

When I use masquerade network interface, I start 2 vmis. The vmis start successfully, but there are the following exceptions:
1. Login either guest os, IP of another vmi's launcher pod cannot be pinged. However, IP of launcher pod corresponding to the current vmi can be pinged.
2. Login either guest os, other container's ip cannot be pinged.
3. virtcl ssh fail, connection refused.

In the launcher pod:
"cat /proc/sys/net/ipv4/ip_forward" get "1".

"iptables -L -t nat" get error:
iptables v1.8.4 (legacy): can't initialize iptables table nat': Permission denied (you must be root)
Perhaps iptables or your kernel needs to be upgraded.

**What you expected to happen**:

When I'm inside one guest os, I want to ping another guest os,and localhost, other container.
ssh guest os.

**Environment**:
kubernetes：1.20
kubevirt：0.46
CNI: Flannel, vxlan model 
OS (e.g. from /etc/os-release):CentOS 7.4.1708
Kernel (e.g. `uname -a`): 3.10.0-693.e17.x86_64

**Comment by ormergi** [comment]
Hi, @ninelinesevduk, if I understand correctly you cannot ping from a VM with masquerade dinging to any other container in the cluster.
Have you specified allowed ports in the VMI spec by chance?
Could you share the VMI yaml?

You can use this snippet Here is how to dump virt-launcher nat rules https://gist.github.com/ormergi/747b6699f8e6fc747e9b6d2e22922262

Please note that you use pretty old kernel and Kubevirt versions, if its possible for you I suggest at least upgrading Kubevirt to the latest release v0.59.0.
There were also fixes and improvements around networking in Kubevirt.

**Comment by EdDev** [comment]
> "iptables -L -t nat" get error: iptables v1.8.4 (legacy): can't initialize iptables table nat': Permission denied (you must be root) Perhaps iptables or your kernel needs to be upgraded.

`iptables` are no longer supported in recent releases.
We switched to `nft` only.

> **Environment**: kubernetes：1.20 kubevirt：0.46

Although we try to help when possible, we support one kubevirt release back. The one you ref referenced is way too old.

As @ormergi mentioned, please try to recreate the same with the latest release.

@ninelinesevduk , please update us if we should keep this open until you manage to feedback with the requested info.

/assign @ormergi 
/assign

**Comment by EdDev** [comment]
@ninelinesevduk , we have not received any new information.
Unless there will be an update in the following days, we intend to close the issue.

**Comment by EdDev** [comment]
There have been no information provided, closing this issue.
You are welcome to re-open it with the relevant data.

/close
