### ISSUE TITLE
when using headless service,there is no dns entry for VM

### ISSUE THREAD

**Issue by ninelinesevduk** [kubevirt/kubevirt#9760]
**What happened**:
when using headless service,there is no dns entry for VM.

![1](https://github.com/kubevirt/kubevirt/assets/3922582/7c1c4dff-c0ab-4952-bcf8-e382fc68100c)
![2](https://github.com/kubevirt/kubevirt/assets/3922582/8f06be95-1dde-4b37-8458-9eecb2e62322)
![3](https://github.com/kubevirt/kubevirt/assets/3922582/bdc6dc71-e722-41f2-b6a2-7cdbe58b20d2)

Please bear with the ugly photos.

The reason I want to use DNS is to resolve the IP of the virtual machine through the domain name. After all, the IP of the virtual machine will change.

**Environment**:
kubernetes：1.20
kubevirt：0.46
CNI: Flannel, vxlan model
OS (e.g. from /etc/os-release):CentOS 7.4.1708
Kernel (e.g. uname -a): 3.10.0-693.e17.x86_64

**Comment by xpivarc** [comment]
Hi @ninelinesevduk 
The kubevirt version seems little bit old. Can you try using newer version?
Also did you migrate the virtual machine or is this one freshly made?

**Comment by ninelinesevduk** [comment]
> Hi @ninelinesevduk The kubevirt version seems little bit old. Can you try using newer version? Also did you migrate the virtual machine or is this one freshly made?

The kubevirt version is a bit lower. The customer's k8s is version 1.20, and there seems to be a problem with the higher version kubevirt.
This one is freshly made.

**Comment by xpivarc** [comment]
fyi @EdDev 
Can you remember any bug related to this?

@ninelinesevduk can you provide `virt-launcher` pod yaml?

**Comment by ninelinesevduk** [comment]
@xpivarc the follows are yamls

**1. launcher.yaml**

apiVersion: v1
kind: Pod
metadata:
  annotations:
    kubevirt.io/domain: fedora-dns-bridge
    kubevirt.io/migrationTransportUnix: "true"
    post.hook.backup.velero.io/command: '["/usr/bin/virt-freezer", "--unfreeze", "--name", "fedora-dns-bridge", "--namespace", "default"]'
    post.hook.backup.velero.io/container: compute
    pre.hook.backup.velero.io/command: '["/usr/bin/virt-freezer", "--freeze", "--name", "fedora-dns-bridge", "--namespace", "default"]'
    pre.hook.backup.velero.io/container: compute
  creationTimestamp: "2023-05-18T09:43:48Z"
  generateName: virt-launcher-fedora-dns-bridge-
  labels:
    kubevirt.io: virt-launcher
    kubevirt.io/created-by: 79dcdb86-48ce-480a-89b0-600f63bbfcd7
    manager: kubelet
    operation: Update
    time: "2023-05-18T09:43:52Z"
  name: virt-launcher-fedora-dns-bridge-wt9m2
  namespace: default
  ownerReferences:
  - apiVersion: kubevirt.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachineInstance
    name: fedora-dns-bridge
    uid: 79dcdb86-48ce-480a-89b0-600f63bbfcd7
  resourceVersion: "12184896"
  uid: 795bf906-1d2f-42d8-93fd-0b28f18dbeee
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - slave3-gpu
  automountServiceAccountToken: false
  containers:
  - command:
    - /usr/bin/virt-launcher
    - --qemu-timeout
    - 240s
    - --name
    - fedora-dns-bridge
    - --uid
    - 79dcdb86-48ce-480a-89b0-600f63bbfcd7
    - --namespace
    - default
    - --kubevirt-share-dir
    - /var/run/kubevirt
    - --ephemeral-disk-dir
    - /var/run/kubevirt-ephemeral-disks
    - --container-disk-dir
    - /var/run/kubevirt/container-disks
    - --grace-period-seconds
    - "45"
    - --hook-sidecars
    - "0"
    - --ovmf-path
    - /usr/share/OVMF
    env:
    - name: VIRT_LAUNCHER_LOG_VERBOSITY
      value: "6"
    - name: LIBVIRT_DEBUG_LOGS
      value: "1"
    - name: VIRTIOFSD_DEBUG_LOGS
      value: "1"
    - name: POD_NAME
      valueFrom:
        fieldRef:
          apiVersion: v1
          fieldPath: metadata.name
    image: 32.13.0.2:5000/kube-system/virt-launcher:v0.46.0
    imagePullPolicy: IfNotPresent
    name: compute
    resources:
      limits:
        devices.kubevirt.io/kvm: "1"
        devices.kubevirt.io/tun: "1"
        devices.kubevirt.io/vhost-net: "1"
      requests:
        cpu: 100m
        devices.kubevirt.io/kvm: "1"
        devices.kubevirt.io/tun: "1"
        devices.kubevirt.io/vhost-net: "1"
        ephemeral-storage: 50M
        memory: "1204257920"
    securityContext:
      capabilities:
        add:
        - NET_BIND_SERVICE
        - SYS_NICE
        drop:
        - NET_RAW
      privileged: false
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/kubevirt-private
      name: private
    - mountPath: /var/run/kubevirt
      name: public
    - mountPath: /var/run/kubevirt-ephemeral-disks
      name: ephemeral-disks
    - mountPath: /var/run/kubevirt/container-disks
      mountPropagation: HostToContainer
      name: container-disks
    - mountPath: /var/run/kubevirt/hotplug-disks
      mountPropagation: HostToContainer
      name: hotplug-disks
    - mountPath: /var/run/libvirt
      name: libvirt-runtime
    - mountPath: /var/run/kubevirt/sockets
      name: sockets
  - args:
    - --copy-path
    - /var/run/kubevirt-ephemeral-disks/container-disk-data/79dcdb86-48ce-480a-89b0-600f63bbfcd7/disk_0
    command:
    - /usr/bin/container-disk
    image: 32.13.0.2:5000/kube-system/fedora-cloud-container-disk-demo
    imagePullPolicy: IfNotPresent
    name: volumecontainerdisk
    resources:
      limits:
        cpu: 100m
        memory: 40M
      requests:
        cpu: 10m
        ephemeral-storage: 50M
        memory: 1M
    securityContext:
      runAsNonRoot: true
      runAsUser: 107
      seLinuxOptions:
        level: s0
        type: virt_launcher.process
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/kubevirt-ephemeral-disks/container-disk-data/79dcdb86-48ce-480a-89b0-600f63bbfcd7
      name: container-disks
    - mountPath: /usr/bin
      name: virt-bin-share-dir
  dnsPolicy: ClusterFirst
  enableServiceLinks: false
  hostname: myvm
  initContainers:
  - command:
    - /usr/bin/cp
    - /usr/bin/container-disk
    - /init/usr/bin/container-disk
    image: 32.13.0.2:5000/kube-system/virt-launcher:v0.46.0
    imagePullPolicy: IfNotPresent
    name: container-disk-binary
    resources:
      limits:
        cpu: 100m
        memory: 40M
      requests:
        cpu: 10m
        memory: 1M
    securityContext:
      privileged: false
      runAsUser: 0
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /init/usr/bin
      name: virt-bin-share-dir
  - args:
    - --no-op
    command:
    - /usr/bin/container-disk
    image: 32.13.0.2:5000/kube-system/fedora-cloud-container-disk-demo
    imagePullPolicy: IfNotPresent
    name: volumecontainerdisk-init
    resources:
      limits:
        cpu: 100m
        memory: 40M
      requests:
        cpu: 10m
        ephemeral-storage: 50M
        memory: 1M
    securityContext:
      runAsNonRoot: true
      runAsUser: 107
    terminationMessagePath: /dev/termination-log
    terminationMessagePolicy: File
    volumeMounts:
    - mountPath: /var/run/kubevirt-ephemeral-disks/container-disk-data/79dcdb86-48ce-480a-89b0-600f63bbfcd7
      name: container-disks
    - mountPath: /usr/bin
      name: virt-bin-share-dir
  nodeName: slave3-gpu
  nodeSelector:
    kubevirt.io/schedulable: "true"
  restartPolicy: Never
  schedulerName: default-scheduler
  securityContext:
    runAsUser: 0
    seLinuxOptions:
      type: virt_launcher.process
  serviceAccount: default
  serviceAccountName: default
  subdomain: mysubdomain
  terminationGracePeriodSeconds: 60
  volumes:
  - emptyDir: {}
    name: private
  - emptyDir: {}
    name: public
  - emptyDir: {}
    name: sockets
  - emptyDir: {}
    name: virt-bin-share-dir
  - emptyDir: {}
    name: libvirt-runtime
  - emptyDir: {}
    name: ephemeral-disks
  - emptyDir: {}
    name: container-disks
  - emptyDir: {}
    name: hotplug-disks
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-05-18T09:43:51Z"
    status: "True"
    type: Initialized
  - lastProbeTime: null
    lastTransitionTime: "2023-05-18T09:43:52Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: "2023-05-18T09:43:52Z"
    status: "True"
    type: ContainersReady
  - lastProbeTime: null
    lastTransitionTime: "2023-05-18T09:43:48Z"
    status: "True"
    type: PodScheduled
  containerStatuses:
  - containerID: docker://372a6eaa35a0a91f0aea8355383160264c5c01d680f332c5d20e4082493880bb
    image: 32.13.0.2:5000/kube-system/virt-launcher:v0.46.0
    imageID: docker-pullable://32.13.0.2:5000/kube-system/virt-launcher@sha256:f6b59e8076dea6e677f3a2ced0b4a7be98559a81ed7ae1a16107fd43e2b099ed
    lastState: {}
    name: compute
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-05-18T09:43:51Z"
  - containerID: docker://1f9a3314ee8f3016d50a012e1c10ff5c8ee887bf1031348bc3a69e62e90569e1
    image: 32.13.0.2:5000/kube-system/fedora-cloud-container-disk-demo:latest
    imageID: docker-pullable://32.13.0.2:5000/kube-system/fedora-cloud-container-disk-demo@sha256:f7d8e6cc1a2872b9f551d90137cd3853f1074497a7397a3e64ff145923589ec6
    lastState: {}
    name: volumecontainerdisk
    ready: true
    restartCount: 0
    started: true
    state:
      running:
        startedAt: "2023-05-18T09:43:52Z"
  hostIP: 173.24.136.5
  initContainerStatuses:
  - containerID: docker://317a45290375ff2370ae2487a273ef4b513729c17ae146adf3ae968c1bd26089
    image: 32.13.0.2:5000/kube-system/virt-launcher:v0.46.0
    imageID: docker-pullable://32.13.0.2:5000/kube-system/virt-launcher@sha256:f6b59e8076dea6e677f3a2ced0b4a7be98559a81ed7ae1a16107fd43e2b099ed
    lastState: {}
    name: container-disk-binary
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://317a45290375ff2370ae2487a273ef4b513729c17ae146adf3ae968c1bd26089
        exitCode: 0
        finishedAt: "2023-05-18T09:43:49Z"
        reason: Completed
        startedAt: "2023-05-18T09:43:49Z"
  - containerID: docker://183ed8eba207cd1dd56946eb097b12f6d0e04a061770a4dc2f4400512ce5920b
    image: 32.13.0.2:5000/kube-system/fedora-cloud-container-disk-demo:latest
    imageID: docker-pullable://32.13.0.2:5000/kube-system/fedora-cloud-container-disk-demo@sha256:f7d8e6cc1a2872b9f551d90137cd3853f1074497a7397a3e64ff145923589ec6
    lastState: {}
    name: volumecontainerdisk-init
    ready: true
    restartCount: 0
    state:
      terminated:
        containerID: docker://183ed8eba207cd1dd56946eb097b12f6d0e04a061770a4dc2f4400512ce5920b
        exitCode: 0
        finishedAt: "2023-05-18T09:43:50Z"
        reason: Completed
        startedAt: "2023-05-18T09:43:50Z"
  phase: Running
  podIP: 31.13.48.51
  podIPs:
  - ip: 31.13.48.51
  qosClass: Burstable
  startTime: "2023-05-18T09:43:48Z"

**2. vmi.yaml**

apiVersion: kubevirt.io/v1
kind: VirtualMachineInstance
metadata:
  annotations:
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
  creationTimestamp: "2023-05-18T09:43:47Z"
  finalizers:
  - kubevirt.io/virtualMachineControllerFinalize
  - foregroundDeleteVirtualMachine
  generation: 8
  labels:
    kubevirt.io/nodeName: slave3-gpu
    manager: Go-http-client
    operation: Update
    time: "2023-05-18T09:43:54Z"
  name: fedora-dns-bridge
  namespace: default
  ownerReferences:
  - apiVersion: kubevirt.io/v1
    blockOwnerDeletion: true
    controller: true
    kind: VirtualMachine
    name: fedora-dns-bridge
    uid: 029860ac-68e5-4c7c-a43b-306eef6f863c
  resourceVersion: "12184917"
  uid: 79dcdb86-48ce-480a-89b0-600f63bbfcd7
spec:
  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/hostname
            operator: In
            values:
            - slave3-gpu
  domain:
    cpu:
      cores: 1
      sockets: 1
      threads: 1
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      interfaces:
      - bridge: {}
        name: default
      rng: {}
    features:
      acpi:
        enabled: true
    firmware:
      uuid: dd5eef3f-c85b-5c38-b170-9b0c913680b1
    machine:
      type: q35
    resources:
      requests:
        memory: 1024M
  hostname: myvm
  networks:
  - name: default
    pod: {}
  subdomain: mysubdomain
  volumes:
  - containerDisk:
      image: 32.13.0.2:5000/kube-system/fedora-cloud-container-disk-demo
      imagePullPolicy: IfNotPresent
    name: containerdisk
  - cloudInitConfigDrive:
      userData: |-
        #cloud-config
        password: fedora
        chpasswd: { expire: False }
    name: cloudinitdisk
status:
  activePods:
    795bf906-1d2f-42d8-93fd-0b28f18dbeee: slave3-gpu
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-05-18T09:43:52Z"
    status: "True"
    type: Ready
  - lastProbeTime: null
    lastTransitionTime: null
    message: cannot migrate VMI which does not use masquerade to connect to the pod
      network
    reason: InterfaceNotLiveMigratable
    status: "False"
    type: LiveMigratable
  guestOSInfo: {}
  interfaces:
  - ipAddress: 31.13.48.51
    ipAddresses:
    - 31.13.48.51
    mac: 02:42:1f:0d:30:33
    name: default
  launcherContainerImageVersion: 32.13.0.2:5000/kube-system/virt-launcher:v0.46.0
  migrationMethod: BlockMigration
  migrationTransport: Unix
  nodeName: slave3-gpu
  phase: Running
  phaseTransitionTimestamps:
  - phase: Pending
    phaseTransitionTimestamp: "2023-05-18T09:43:47Z"
  - phase: Scheduling
    phaseTransitionTimestamp: "2023-05-18T09:43:48Z"
  - phase: Scheduled
    phaseTransitionTimestamp: "2023-05-18T09:43:52Z"
  - phase: Running
    phaseTransitionTimestamp: "2023-05-18T09:43:54Z"
  qosClass: Burstable
  virtualMachineRevisionName: revision-start-vm-029860ac-68e5-4c7c-a43b-306eef6f863c-3
  volumeStatus:
  - name: cloudinitdisk
    target: vdb
  - name: containerdisk
    target: vda

**3. vm.yaml**

apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"apiVersion":"kubevirt.io/v1","kind":"VirtualMachine","metadata":{"annotations":{},"labels":{"expose":"me"},"name":"fedora-dns-bridge","namespace":"default"},"spec":{"running":true,"template":{"spec":{"affinity":{"nodeAffinity":{"requiredDuringSchedulingIgnoredDuringExecution":{"nodeSelectorTerms":[{"matchExpressions":[{"key":"kubernetes.io/hostname","operator":"In","values":["slave3-gpu"]}]}]}}},"domain":{"devices":{"disks":[{"disk":{"bus":"virtio"},"name":"containerdisk"},{"disk":{"bus":"virtio"},"name":"cloudinitdisk"}],"interfaces":[{"bridge":{},"name":"default"}],"rng":{}},"resources":{"requests":{"memory":"1024M"}}},"hostname":"myvm","networks":[{"name":"default","pod":{}}],"subdomain":"mysubdomain","volumes":[{"containerDisk":{"image":"32.13.0.2:5000/kube-system/fedora-cloud-container-disk-demo"},"name":"containerdisk"},{"cloudInitConfigDrive":{"userData":"#cloud-config\npassword: fedora\nchpasswd: { expire: False }"},"name":"cloudinitdisk"}]}}}}
    kubevirt.io/latest-observed-api-version: v1
    kubevirt.io/storage-observed-api-version: v1alpha3
  creationTimestamp: "2023-05-18T09:07:51Z"
  generation: 3
  labels:
    expose: me
    manager: Go-http-client
    operation: Update
    time: "2023-05-18T09:43:54Z"
  name: fedora-dns-bridge
  namespace: default
  resourceVersion: "12184919"
  uid: 029860ac-68e5-4c7c-a43b-306eef6f863c
spec:
  running: true
  template:
    metadata:
      creationTimestamp: null
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: kubernetes.io/hostname
                operator: In
                values:
                - slave3-gpu
      domain:
        devices:
          disks:
          - disk:
              bus: virtio
            name: containerdisk
          - disk:
              bus: virtio
            name: cloudinitdisk
          interfaces:
          - bridge: {}
            name: default
          rng: {}
        machine:
          type: q35
        resources:
          requests:
            memory: 1024M
      hostname: myvm
      networks:
      - name: default
        pod: {}
      subdomain: mysubdomain
      volumes:
      - containerDisk:
          image: 32.13.0.2:5000/kube-system/fedora-cloud-container-disk-demo
        name: containerdisk
      - cloudInitConfigDrive:
          userData: |-
            #cloud-config
            password: fedora
            chpasswd: { expire: False }
        name: cloudinitdisk
status:
  conditions:
  - lastProbeTime: null
    lastTransitionTime: "2023-05-18T09:43:52Z"
    status: "True"
    type: Ready
  created: true
  printableStatus: Running
  ready: true
  volumeSnapshotStatuses:
  - enabled: false
    name: containerdisk
    reason: Snapshot is not supported for this volumeSource type [containerdisk]
  - enabled: false
    name: cloudinitdisk
    reason: Snapshot is not supported for this volumeSource type [cloudinitdisk]

**Comment by xpivarc** [comment]
@ninelinesevduk Thank you! Now I can see the problem. You need to move the labels, used for the service selector, to the template part. After that, it should work. Please give it a try.

**Comment by ninelinesevduk** [comment]
@xpivarc This works!
Thank you!
I close this issue.
