### ISSUE TITLE
virt-launcher with Passt interface in Azure crashing

### ISSUE THREAD

**Issue by anvarik** [kubevirt/kubevirt#9771]
**What happened**:
I have deployed a VMI replicaset with `passt` interface. Beforehand added the `Passt` feature gate under Kubevirt CRD: 

```
spec:
  certificateRotateStrategy: {}
  configuration:
    developerConfiguration:
      featureGates:
      - Passt
```

After changing my interface to passt from masquerade pods keep restarting and crashing with following error:

```
8s          Warning   SyncFailed          virtualmachineinstance/kubevirt-vmirsg5ddl        unknown error encountered sending command SyncVMI: rpc error: code = Unavailable desc = transport is closing
8s          Warning   SyncFailed          virtualmachineinstance/kubevirt-vmirsg5ddl        failed to detect VMI pod: dial unix //pods/b8926a4c-a05b-41af-9bf4-a0e018194222/volumes/kubernetes.io~empty-dir/sockets/launcher-sock: connect: connection refused
```

**What you expected to happen**:
Passt interface to work.

**How to reproduce it (as minimally and precisely as possible)**:
Deploy a VMIRS in Azure with Azure CNI and enable passt.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): v0.59.0
- Kubernetes version (use `kubectl version`): 1.25.5
- VM or VMI specifications: template VMIRS yaml with kubevirt/cirros-container-disk-demo 
- Cloud provider or hardware configuration: Azure
- OS (e.g. from /etc/os-release): amd64 linux
- Kernel (e.g. `uname -a`): Linux kubevirt-vmirsbb48m 5.15.0-1037-azure #44-Ubuntu SMP Thu Apr 20 13:19:31 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: N/A
- Others: N/A

**Comment by EdDev** [comment]
There has been no response on this issue for some time now, therefore we are closing it.

Feel free to open a new issue with the relevant info.

/close
