### ISSUE TITLE
Unattach the pvcs after creating the vm 

### ISSUE THREAD

**Issue by khalilxg** [kubevirt/kubevirt#9774]
hello so im using kubevirt, i successfully created the vm win2k12, so im stucked in step everytime i start the vm it boots into the installation steps, during the installation there's the window saying 'this disk already has ubuntu ..." so successfully the installation was done, but the booting is alwayz targeting the installation media, on kubevirt they say "Once the Virtual Machine is created, the PVC with the ISO and the virtio drivers can be unattached from the Virtual Machine." so how to to it, knowing that i ediited the vm yaml lotta times and everytime i get errors !

this is the vm typical yaml:
 apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: win2k12-iso
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: win2k12-iso
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - bootOrder: 1
            cdrom:
              bus: sata
            name: cdromiso
          - disk:
              bus: virtio
            name: harddrive
          - cdrom:
              bus: sata
            name: virtiocontainerdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 8G
      volumes:
      - name: cdromiso
        persistentVolumeClaim:
          claimName: iso-win2k12
      - name: harddrive
        persistentVolumeClaim: 
          claimName: winhd
      - containerDisk:
          image: kubevirt/virtio-container-disk 
        name: virtiocontainerdisk

thank you

**Comment by alicefr** [comment]
@khalilxg You cannot follow this installation method as you declare the VMI in this way, it will always boot from the iso and retrigger the installation. There were similar questions in:
  - https://github.com/kubevirt/kubevirt/issues/9007
  - https://github.com/kubevirt/kubevirt/issues/7365

Please check the comments https://github.com/kubevirt/kubevirt/issues/9007#issuecomment-1378356504 and https://github.com/kubevirt/kubevirt/issues/7365#issuecomment-1067766956
