### ISSUE TITLE
unable to mount root fs

### ISSUE THREAD

**Issue by khalilxg** [kubevirt/kubevirt#9775]
**vm ubuntu not starting/booting**:

- kernel panic - not syncing: VFS: Unable to mout root fs on unkown-block(0.0)Hard [Disk]
- hardware name: kubevirt None/RHEL, BIOS 1.16.1-1.e19 04/01/2014
-cpu: 0 pid: 1 comm: swapper/0 not tainted 5.19.0-32-generic #33~22.04.1-Ubuntu 

**What you expected to happen**:
Ubuntu, after installation, launch successfully.

so i installed kubevirt on miniikube ontop of ubuntu22.04, all works fine, successfully installed ubuntu inside the vm, theni deleted the vm and tweaked the yaml to launch the vm from the instllation .. 

**Environment**:
- KubeVirt version (use `virtctl version`): `[v1.0.0-beta.0]`
- Kubernetes version (use `kubectl version`): v1.27.2
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): ubuntu 22.04
- Kernel (e.g. `uname -a`): Linux hostname 5.19.0-41-generic #42~22.04.1-Ubuntu SMP PREEMPT_DYNAMIC Tue Apr 18 17:40:00 UTC 2 x86_64 x86_64 x86_64 GNU/Linux
- Install tools: minikube
- Others: N/A

vminstallation.yaml`apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  name: win2k12-iso
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/domain: win2k12-iso
    spec:
      domain:
        cpu:
          cores: 4
        devices:
          disks:
          - bootOrder: 2
            cdrom:
              bus: sata
            name: cdromiso
          - disk:
              bus: virtio
            name: harddrive
          - cdrom:
              bus: sata
            name: virtiocontainerdisk
        machine:
          type: q35
        resources:
          requests:
            memory: 8G
      volumes:
      - name: harddrive
        persistentVolumeClaim: 
          claimName: winhd
      - name: cdromiso
        persistentVolumeClaim:
          claimName: iso-win2k12
      - containerDisk:
          image: kubevirt/virtio-container-disk
        name: virtiocontainerdisk
        `

vm after installation yaml `kubectl apply -f - <<EOF
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachine
metadata:
  generation: 1
  labels:
    kubevirt.io/os: ubuntu
  name: vm1
spec:
  running: true
  template:
    metadata:
      labels:
        kubevirt.io/domain: vm1
    spec:
      domain:
        cpu:
          cores: 2
        devices:
          disks:
          - disk:
              bus: virtio
            name: harddrive
        machine:
          type: q35
        resources:
          requests:
            memory: 4096M
      volumes:
      - name: harddrive
        persistentVolumeClaim:
          claimName: winhd
EOF
`

**Comment by alicefr** [comment]
@khalilxg You cannot follow this installation method as you declare the VMI in this way, it will always boot from the iso and retrigger the installation. There were similar questions in:
  - https://github.com/kubevirt/kubevirt/issues/9007
  - https://github.com/kubevirt/kubevirt/issues/7365

Please check the comments https://github.com/kubevirt/kubevirt/issues/9007#issuecomment-1378356504 and https://github.com/kubevirt/kubevirt/issues/7365#issuecomment-1067766956

**Comment by alicefr** [comment]
Can you please provide more information like the VM yaml you use?

**Comment by khalilxg** [comment]
@alicefr the vm yaml i use firstly to install the ubuntu iso is vminstallation.yaml, after installation i deleted the vm, and recreate a vm with yaml as in description vmafterinstallation.yaml to use the pvc that has has the ubuntu after installation
