### ISSUE TITLE
Need support for pod network as bridge interface for live migration

### ISSUE THREAD

**Issue by prtkdave** [kubevirt/kubevirt#9776]
**Is your feature request related to a problem? Please describe**:
A clear and concise description of what the problem is.

We can not use NAT and masquerade interfaces for VMs provisioning for internal security reasons. We need support for migration for bridge interfaces.

**Describe the solution you'd like**:

**Describe alternatives you've considered**:

**Additional context**:

**Comment by maiqueb** [comment]
AFAICT, this request requires a CNI plugin that implements sticky IPs afaict (same IP after migration).

Thus, it will be IMO hard to find a solution across the board that works independently of the CNI used.

**Comment by prtkdave** [comment]
@maiqueb thanks for your comment. Probably I will explain the use case once again if that helps.

**Use Case:** Performing Live Migration where Kubevirt VMs are already running with pod network as bridge interface type. 

**Issue**  We are not able to convert the interface to masquerade type and security will not approve masquerade for POD network type. We can apply sticky IP to VMs using CNI we are using. However, We are facing the error while migrating the VMs that Kubevirt does not support bridge interface type. 

Errors are as below:

_Error from server: error when creating "migration.yaml": admission webhook "migration-create-validator.kubevirt.io" denied the request: Cannot migrate VMI, Reason: InterfaceNotLiveMigratable, Message: cannot migrate VMI which does not use masquerade to connect to the pod network_

In our environment when we keep interface type as masquerade then VM migration works and we are able to preserve the IP address.

We need support from kubevirt to help us enable live migration for the bridge interface type. 

Please let us know if you need more information.

Thanks.

**Comment by ormergi** [comment]
@prtkdave could you elaborate more about your security concerns using masquerade binding?
FWIW you can specify the ports you want to allow traffic from/to, e.g.: the example at https://kubevirt.io/user-guide/virtual_machines/interfaces_and_networks/#masquerade

**Comment by prtkdave** [comment]
@maiqueb  thanks i will try kubevirt.io/allow-pod-bridge-network-live-migration this.

**Comment by ormergi** [comment]
@prtkdave  the `InterfaceNotLiveMigratable` flag will be available since v1.0.0 release, which was supposed to be released his week but was postponed (see kubevirt-dev  **[thread](https://groups.google.com/g/kubevirt-dev/c/FtWmEAbj_3Y)**)
You can test it with [v0.60.0 alpha](https://github.com/kubevirt/kubevirt/releases/tag/v0.60.0-alpha.0) or[ v1.0.0-beta](https://github.com/kubevirt/kubevirt/releases/tag/v1.0.0-beta.0) release.
