### ISSUE TITLE
when i follow Labs - KubeVirt quickstart with Minikube,i can't strart vm

### ISSUE THREAD

**Issue by ninelinesevduk** [kubevirt/kubevirt#9784]
**What happened**:

when i follow Labs - KubeVirt quickstart with Minikube,i can't strart vm.

The launcher pod' logs:
```
kubectl logs -c compute virt-launcher-daniu-r74x8 

{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:86","timestamp":"2023-05-24T06:51:03.800908Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:89","timestamp":"2023-05-24T06:51:03.821635Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:496","timestamp":"2023-05-24T06:51:03.871085Z"}
{"component":"virt-launcher","level":"error","msg":"failed to start virtqemud","pos":"libvirt_helper.go:250","reason":"fork/exec /usr/sbin/virtqemud: errno 0","timestamp":"2023-05-24T06:51:03.915213Z"}

panic: fork/exec /usr/sbin/virtqemud: errno 0

goroutine 34 [running]:

kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/util.LibvirtWrapper.StartVirtquemud.func1()
	pkg/virt-launcher/virtwrap/util/libvirt_helper.go:251 +0x4ce
	
created by kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/util.LibvirtWrapper.StartVirtquemud
	pkg/virt-launcher/virtwrap/util/libvirt_helper.go:218 +0x65
	
{"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 12 with status 512","pos":"virt-launcher-monitor.go:124","timestamp":"2023-05-24T06:51:04.737423Z"}
{"component":"virt-launcher-monitor","level":"error","msg":"dirty virt-launcher shutdown: exit-code 2","pos":"virt-launcher-monitor.go:142","timestamp":"2023-05-24T06:51:04.789044Z"}
``` 
if I enter the launcher container and execute "/usr/sbin/virtqemud -f /etc/libvirt/virtqemud.conf" manually, i get the error and exit the launcher:

```
bash-5.1$ /usr/sbin/virtqemud -f /etc/libvirt/virtqemud.conf
2023-05-25 06:30:41.684+0000: 50: info : libvirt version: 9.0.0, package: 3.el9 (builder@centos.org, 2023-02-01-12:58:56, )
2023-05-25 06:30:41.684+0000: 50: info : hostname: daniu
2023-05-25 06:30:41.684+0000: 50: error : virHostCPUGetCPUID:1422 : Unable to open /dev/kvm: Permission denied
2023-05-25 06:30:41.685+0000: 50: error : virGDBusGetSessionBus:126 : internal error: Unable to get session bus connection: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory
2023-05-25 06:30:41.685+0000: 50: error : virGDBusGetSystemBus:99 : internal error: Unable to get system bus connection: Could not connect: No such file or directory
command terminated with exit code 137
``` 

Please help me, thank you all.

**Environment**:
- Minikube version: v1.30.1
- Docker version: 20.10.12
- Kubernetes version (use `kubectl version`): v1.26.3
- KubeVirt version (use `virtctl version`): v0.59.0
- OS (e.g. from /etc/os-release): Ubuntu 20.04.3 LTS (Focal Fossa)
- Kernel (e.g. `uname -a`): Linux fh-081 5.15.0-71-generic  # 78~20.04.1-Ubuntu SMP Wed Apr 19 11:26:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

**Comment by ninelinesevduk** [comment]
> **What happened**:
> 
> when i follow Labs - KubeVirt quickstart with Minikube,i can't strart vm.
> 
> The launcher pod' logs:
> 
> ```
> kubectl logs -c compute virt-launcher-daniu-r74x8 
> 
> {"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:86","timestamp":"2023-05-24T06:51:03.800908Z"}
> {"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:89","timestamp":"2023-05-24T06:51:03.821635Z"}
> {"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu+unix:///session?socket=/var/run/libvirt/virtqemud-sock","pos":"libvirt.go:496","timestamp":"2023-05-24T06:51:03.871085Z"}
> {"component":"virt-launcher","level":"error","msg":"failed to start virtqemud","pos":"libvirt_helper.go:250","reason":"fork/exec /usr/sbin/virtqemud: errno 0","timestamp":"2023-05-24T06:51:03.915213Z"}
> 
> panic: fork/exec /usr/sbin/virtqemud: errno 0
> 
> goroutine 34 [running]:
> 
> kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/util.LibvirtWrapper.StartVirtquemud.func1()
> 	pkg/virt-launcher/virtwrap/util/libvirt_helper.go:251 +0x4ce
> 	
> created by kubevirt.io/kubevirt/pkg/virt-launcher/virtwrap/util.LibvirtWrapper.StartVirtquemud
> 	pkg/virt-launcher/virtwrap/util/libvirt_helper.go:218 +0x65
> 	
> {"component":"virt-launcher-monitor","level":"info","msg":"Reaped pid 12 with status 512","pos":"virt-launcher-monitor.go:124","timestamp":"2023-05-24T06:51:04.737423Z"}
> {"component":"virt-launcher-monitor","level":"error","msg":"dirty virt-launcher shutdown: exit-code 2","pos":"virt-launcher-monitor.go:142","timestamp":"2023-05-24T06:51:04.789044Z"}
> ```
> 
> if I enter the launcher container and execute "/usr/sbin/virtqemud -f /etc/libvirt/virtqemud.conf" manually, i get the error and exit the launcher:
> 
> ```
> bash-5.1$ /usr/sbin/virtqemud -f /etc/libvirt/virtqemud.conf
> 2023-05-25 06:30:41.684+0000: 50: info : libvirt version: 9.0.0, package: 3.el9 (builder@centos.org, 2023-02-01-12:58:56, )
> 2023-05-25 06:30:41.684+0000: 50: info : hostname: daniu
> 2023-05-25 06:30:41.684+0000: 50: error : virHostCPUGetCPUID:1422 : Unable to open /dev/kvm: Permission denied
> 2023-05-25 06:30:41.685+0000: 50: error : virGDBusGetSessionBus:126 : internal error: Unable to get session bus connection: Cannot spawn a message bus without a machine-id: Unable to load /var/lib/dbus/machine-id or /etc/machine-id: Failed to open file “/var/lib/dbus/machine-id”: No such file or directory
> 2023-05-25 06:30:41.685+0000: 50: error : virGDBusGetSystemBus:99 : internal error: Unable to get system bus connection: Could not connect: No such file or directory
> command terminated with exit code 137
> ```
> 
> Please help me, thank you all.
> 
> **Environment**:
> 
> * Minikube version: v1.30.1
> * Docker version: 20.10.12
> * Kubernetes version (use `kubectl version`): v1.26.3
> * KubeVirt version (use `virtctl version`): v0.59.0
> * OS (e.g. from /etc/os-release): Ubuntu 20.04.3 LTS (Focal Fossa)
> * Kernel (e.g. `uname -a`): Linux fh-081 5.15.0-71-generic  # 78~20.04.1-Ubuntu SMP Wed Apr 19 11:26:48 UTC 2023 x86_64 x86_64 x86_64 GNU/Linux

when i enable Root feature, every this is ok.
i close the issure

**Comment by bxhandhxb** [comment]
excuse me, i met the similar question.
i wonder how to enable Root feature.
thx !!

**Comment by jiridanek** [comment]
> Root feature

It's described here https://kubevirt.io/user-guide/operations/activating_feature_gates/

```
    spec:
      configuration:
        developerConfiguration:
          featureGates:
            - Root
```
