### ISSUE TITLE
Support flood on k6t-net bridge device by setting ageingTime to 0

### ISSUE THREAD

**Issue by chinglinwen** [kubevirt/kubevirt#9800]
**Is your feature request related to a problem? Please describe**:

We have a use case(mirror traffic) that needs to flood on k6s bridge to another network's vm, and by setting specific bridge

A picture worth thousand words
![image](https://github.com/kubevirt/kubevirt/assets/16344129/42aee348-cf6a-47fc-af98-089688a5b2ad)

**Describe the solution you'd like**:
Potential solution: set k6s bridge ageingTime=0, and passing what link to set ageingTime from vm.spec.vmi.annotation (with key,value ).

**Describe alternatives you've considered**:
Considered sidecar, but no permission to set ageingtime at sidecar ( since it's belong to virt-launcher pod, which doesn't have such permission to set network )

**Additional context**:

**Comment by EdDev** [comment]
We are starting to discuss ways to allow custom network bindings, where a well defined integration allows tweaks like the one you mentioned.

I will update this issue once we have some information available.

/sig network
/assign
