### ISSUE TITLE
Unable to build Kubevirt

### ISSUE THREAD

**Issue by jcanocan** [kubevirt/kubevirt#9806]
**What happened**:
I'm not able to build `make cluster-sync` Kubevirt. The `make cluster-sync` command throws the following error:

```bash
$ make cluster-sync
./hack/cluster-sync.sh
make[1]: Entering directory '/home/jcanocan/Repos/kubevirt-clean/kubevirt'
./hack/cluster-build.sh
selecting podman as container runtime
Building ...
go version go1.19.2 linux/amd64

go version go1.19.2 linux/amd64
fatal: detected dubious ownership in repository at '/root/go/src/kubevirt.io/kubevirt'
To add an exception for this directory, call:

	git config --global --add safe.directory /root/go/src/kubevirt.io/kubevirt
Regenerating sandbox
INFO: Analyzed target //:gazelle (0 packages loaded, 0 targets configured).
INFO: Found 1 target...
ERROR: <builtin>: BazelWorkspaceStatusAction stable-status.txt failed: Failed to determine workspace status: Process exited with status 1
hack/print-workspace-status.sh: line 36: KUBEVIRT_GIT_VERSION: unbound variable
Target //:gazelle failed to build
Use --verbose_failures to see the command lines of failed build steps.
INFO: Elapsed time: 0.107s, Critical Path: 0.01s
INFO: 1 process: 1 internal.
FAILED: Build did NOT complete successfully
FAILED: Build did NOT complete successfully
make[1]: *** [Makefile:150: cluster-build] Error 1
make[1]: Leaving directory '/home/jcanocan/Repos/kubevirt-clean/kubevirt'
make: *** [Makefile:159: cluster-sync] Error 2

```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
1. Clean clone the latest version of Kubevirt, e.g. https://github.com/kubevirt/kubevirt/commit/e145467d7527c7f6b7e2b94e62d22992c410f15d
2. Create a cluster `make cluster-up`.
3. Build the project `make cluster-sync`.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by lyarwood** [comment]
https://github.com/kubevirt/kubevirt/pull/9575/commits/860f8e42fe39da8770942fb1a75bdf36787cd179 is a possible hackaround to this and https://github.com/kubevirt/kubevirt/pull/9789 is a more complete fix in the builder image. Note however we'd also need to build, push and then bump the image before the latter works for everyone.

**Comment by jcanocan** [comment]
> [860f8e4](https://github.com/kubevirt/kubevirt/commit/860f8e42fe39da8770942fb1a75bdf36787cd179) is a possible hackaround to this and #9789 is a more complete fix in the builder image. Note however we'd also need to build, push and then bump the image before the latter works for everyone.

I can confirm the hackaround works fine. Many thanks @lyarwood for the workaround :-)

**Comment by alaypatel07** [comment]
For folks who are stumbling into and are not able to get the newer image for some reason can follow the below mentioned steps:
1.  Find the builder container
```docker ps | grep builder
6940f06149d6   quay.io/kubevirt/builder:2312220935-5cd924bf8    "/entrypoint.sh hack…"   4 minutes ago    Up 4 minutes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                kubevirt-bazel-server
````
2. exec into the builder containers and add the global directory
```
$ docker exec -it 6940f06149d6
"docker exec" requires at least 2 arguments.
See 'docker exec --help'.

Usage:  docker exec [OPTIONS] CONTAINER COMMAND [ARG...]

Run a command in a running container
[alayp@alaypfedora kubevirt]$ docker exec -it 6940f06149d6 sh
sh-5.1# git status
fatal: detected dubious ownership in repository at '/root/go/src/kubevirt.io/kubevirt'
To add an exception for this directory, call:

        git config --global --add safe.directory /root/go/src/kubevirt.io/kubevirt
sh-5.1# git config --global --add safe.directory /root/go/src/kubevirt.io/kubevirt
sh-5.1#
exit
```
3. Run `make cluster-sync` again

**Comment by jcanocan** [comment]
> For folks who are stumbling into and are not able to get the newer image for some reason can follow the below mentioned steps:
> 
>     1. Find the builder container
> 
> 
> ```
> 6940f06149d6   quay.io/kubevirt/builder:2312220935-5cd924bf8    "/entrypoint.sh hack…"   4 minutes ago    Up 4 minutes                                                                                                                                                                                                                                                                                                                                                                                                                                                                                kubevirt-bazel-server
> ```
> 
>     2. exec into the builder containers and add the global directory
> 
> 
> ```
> $ docker exec -it 6940f06149d6
> "docker exec" requires at least 2 arguments.
> See 'docker exec --help'.
> 
> Usage:  docker exec [OPTIONS] CONTAINER COMMAND [ARG...]
> 
> Run a command in a running container
> [alayp@alaypfedora kubevirt]$ docker exec -it 6940f06149d6 sh
> sh-5.1# git status
> fatal: detected dubious ownership in repository at '/root/go/src/kubevirt.io/kubevirt'
> To add an exception for this directory, call:
> 
>         git config --global --add safe.directory /root/go/src/kubevirt.io/kubevirt
> sh-5.1# git config --global --add safe.directory /root/go/src/kubevirt.io/kubevirt
> sh-5.1#
> exit
> ```
> 
>     3. Run `make cluster-sync` again

Great! Thanks for sharing the tip! :blush:
