### ISSUE TITLE
Disks created within `Filesystem` `PVCs` use the overall `Capacity` of the underlying `PV` instead of requested storage size of `PVC`

### ISSUE THREAD

**Issue by lyarwood** [kubevirt/kubevirt#9809]
**What happened**:

This might not be a bug and more of a design decision to avoid wasting space within `PVs` but I wanted to raise it either way.

I noticed $subject while using `PVs` maintained by the `local-volume-provisioner` within a `kubevirtci` deployed environment. At present we use it to create filesystem based `PVs` that share the same filesystem. As discussed in https://github.com/kubevirt/kubevirtci/issues/1014 this leads to a known short coming of the provisioner where the capacity of each `PV` is the size of the hosting filesystem. 

This becomes an issue for KubeVirt as we eventually create a disk within the `PV` using the overall `Capacity` of the `PV` as the size. In this scenario this obviously fails as the disk is also being used by the host OS amongst other things.

https://github.com/kubevirt/kubevirt/blob/e145467d7527c7f6b7e2b94e62d22992c410f15d/pkg/host-disk/host-disk.go#L272-L287

```
$ ./cluster-up/kubectl.sh apply -f - <<EOF
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
EOF
[..]
$ ./cluster-up/virtctl.sh create vm --volume-pvc=name:example,src:example-pvc --name example | ./cluster-up/kubectl.sh apply -f -
[..]
$ ./cluster-up/kubectl.sh get pvc/example-pvc -o json | jq .spec.volumeName
[..]
"local-pv-f44cc0e9"
$ ./cluster-up/kubectl.sh get pv/local-pv-f44cc0e9 -o json | jq .spec.capacity
[..]
{
  "storage": "34Gi"
}
$ ./cluster-up/kubectl.sh get vm/example -o json | jq .status.conditions[2]
[..]
{
  "lastProbeTime": null,
  "lastTransitionTime": "2023-05-26T14:39:37Z",
  "message": "preparing host-disks failed: unable to create /var/run/kubevirt-private/vmi-disks/example/disk.img, not enough space, demanded size 36507222016 B is bigger than available space 17550753792 B, also after taking 10 % toleration into account",
  "reason": "Synchronizing with the Domain failed.",
  "status": "False",
  "type": "Synchronized"
}
```

Reducing the overall `Capacity` of an example `PV` however causes the eventual disk to be created successfully but we still end up using the `Capacity` of the `PV` as the size of the disk instead of the size requested through the `PVC`:

```
$ ./cluster-up/kubectl.sh apply -f - <<EOF
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: example-pvc-2
spec:
  storageClassName: local
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
EOF
$ ./cluster-up/virtctl.sh create vm --volume-pvc=name:example,src:example-pvc-2 --name example-2 | ./cluster-up/kubectl.sh apply -f -
[..]
$ ./cluster-up/kubectl.sh get pvc/example-pvc-2 -o json | jq .spec.volumeName
[..]
"local-pv-3fb65ef2"
$ ./cluster-up/kubectl.sh get pv/local-pv-3fb65ef2 -o json | jq .spec.capacity
[..]
{
  "storage": "5Gi"
}
$ ./cluster-up/kubectl.sh exec -ti virt-launcher-example-2-b7spt bash
[..]
$ qemu-img info --force-share /var/run/kubevirt-private/vmi-disks/example/disk.img
image: /var/run/kubevirt-private/vmi-disks/example/disk.img
file format: raw
virtual size: 5 GiB (5368709120 bytes)
disk size: 4 KiB
Child node '/file':
    filename: /var/run/kubevirt-private/vmi-disks/example/disk.img
    protocol type: file
    file length: 5 GiB (5368709120 bytes)
    disk size: 4 KiB
```

**What you expected to happen**:

The size of an underlying disk created within a filesystem `PV` should match the requested size from the `PVC` and not the overall capacity of the `PV`.

**How to reproduce it (as minimally and precisely as possible)**:

See above.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by awels** [comment]
So this is by design, let me explain why this happens. The local storage 'provisioner' actually just maps some bind mounts to volumes, and thus essentially share the underlying filesystem. There is nothing stopping one from requesting a 1Mi PVC, and completely filling up the disk writing to the volume. So the returned PVs must return the potential total amount of space one can write, which is the total space of the filesystem. The kubevirt hpp does the same thing since there is nothing stopping one from writing more than requested.

I am trying to understand why you are using capacity to create disk images, or even why kubevirt is trying to create disk images. When CDI creates disk images it uses min(request size, capacity) to determine how big the disk should be.

**Comment by lyarwood** [comment]
> So this is by design, let me explain why this happens. The local storage 'provisioner' actually just maps some bind mounts to volumes, and thus essentially share the underlying filesystem. There is nothing stopping one from requesting a 1Mi PVC, and completely filling up the disk writing to the volume. So the returned PVs must return the potential total amount of space one can write, which is the total space of the filesystem. The kubevirt hpp does the same thing since there is nothing stopping one from writing more than requested.

Yeah understood, I still think moving to block device based PVs served from a single partitioned block device is going to be better for kubevirtci but I'll follow up in https://github.com/kubevirt/kubevirtci/issues/1014 once I'm back from PTO.

> I am trying to understand why you are using capacity to create disk images, or even why kubevirt is trying to create disk images. When CDI creates disk images it uses min(request size, capacity) to determine how big the disk should be.

TIL, that same approach should work fine here, I've posted a WIP change essentially doing that but I'll clean it up when I get back from PTO.
