### ISSUE TITLE
Can ssh work without a key pair?

### ISSUE THREAD

**Issue by rlewkowicz** [kubevirt/kubevirt#9827]
I can't tell if I'm doing something wrong, or if there's some connection problem. 

```
root@ce7788de34d3:/# virtctl ssh --namespace=ipsecgw --username=ubuntu ipsecgw01 -v 10 --local-ssh
{"component":"","level":"info","msg":"running: /usr/bin/ssh -o ProxyCommand=virtctl port-forward --stdio=true vmi/ipsecgw01.ipsecgw 22 ubuntu@vmi/ipsecgw01.ipsecgw","pos":"wrapped.go:31","timestamp":"2023-05-31T16:45:59.169419Z"}
websocket: close 1006 (abnormal closure): unexpected EOF
kex_exchange_identification: Connection closed by remote host
exit status 255
```
So I can't tell if it's dying because of the websocket or the key is failing. 

I can console with similar parameters

**Comment by alicefr** [comment]
@rlewkowicz if you can log with the console at least you could check if the key has been added correctly (including the permission). Then, try to check the systemd log for sshd and see if you can see there your attempts to log into the system. This should at least narrow down where the problems are.
