### ISSUE TITLE
API cannot list resources

### ISSUE THREAD

**Issue by uhthomas** [kubevirt/kubevirt#9829]
**What happened**:

The API pods aren't healthy.

```sh
❯ k -n kubevirt get po
NAME                           READY   STATUS    RESTARTS   AGE
virt-api-7d66f6984c-95ggf      0/1     Running   0          4h24m
virt-api-7d66f6984c-tl9hv      0/1     Running   0          4h24m
virt-operator-58d8974d-b5qx7   1/1     Running   0          4h30m
virt-operator-58d8974d-tvxbx   1/1     Running   0          4h30m
```

There are thousands of identical logs:

```sh
E0531 13:36:40.812372       1 reflector.go:123] pkg/virt-api/api.go:734: Failed to list *v1beta1.CustomResourceDefinition: the server could not find the
requested resource
```

**What you expected to happen**:

The API should work.

**How to reproduce it (as minimally and precisely as possible)**:

Install with the manifests from the release: https://github.com/kubevirt/kubevirt/releases/tag/v0.59.0.

**Additional context**:

https://github.com/uhthomas/automata/tree/20fec4ce1243c0bf21d33a258f345c3787b22a5c/k8s/unwind/kubevirt

**Environment**:
- KubeVirt version (use `virtctl version`): 0.59.0
- Kubernetes version (use `kubectl version`): 1.27.2
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by alicefr** [comment]
Are the KubeVirt CRDs installed(like Kubevirt, VirtualMachine, VirtualMachineInstances...)? Can you see them with `kubectl api-resources`?
