### ISSUE TITLE
hook sidecar for virt-launcher not exit when vm live migrated, prevent next time vm live migration

### ISSUE THREAD

**Issue by chinglinwen** [kubevirt/kubevirt#9838]
**What happened**:
Created VM with hook sidecar enabled, then do the migration, migration success, but the origin pod stuck at NotReady state
prevent next time migration

example pod output
```
default    virt-launcher-vfw-5xfj2                                           2/2     Running     0               149m    10.44.101.125     node2   <none>           1/1
default    virt-launcher-vfw-rjn2x                                           1/2     NotReady    0               4d23h   10.44.101.125     node1   <none>           1/1
```

```
virtctl migrate vfw
```

it has two errors
- can't execute migrate because, previous migrate not succeed (origin virt-launcher pod not completed, stuck at NotReady)
- deleted vmim resource, try again, virt-controller will report error too(because such pod exist )

```
kubevirt/virt-controller-66fdc48b76-vljmt[virt-controller]: {"component":"virt-controller","kind":"","level":"info","msg":"Waiting to schedule target pod for migration because there are already multiple pods running for vmi default/vfw","name":"kubevirt-migrate-vm-jlk2x","namespace":"default","pos":"migration.go:880","timestamp":"2023-05-31T11:11:11.861469Z","uid":"e2dddc65-2d04-4805-9c95-61455b5bf233"}
```

the NotReady is likely because the origin pod's hook sidecar container is not terminated (compute does )
when I manual nerdctl kill such container ( it completed immediately )

and I had observed there is no signal sent to hook sidecar container

the hook sidecar enabled vm, will have the issue of migration issue
1. first time(origin pod not ready)
2. second time, can't do the migration

**What you expected to happen**:
migration without error when hook-sidecar enabled for VM.

**How to reproduce it (as minimally and precisely as possible)**:
1. create vm with hook sidecar enabled
2. do the migration
3. observe the origin pod status ( should be Completed ), and the hook sidecar container should exit too with compute container terminated

**Additional context**:
the hook sidecar's code is about this code:  https://github.com/kubevirt/kubevirt/tree/main/cmd/example-hook-sidecar

I've added the following code to make sure it can receive the signal, but don't receive any in test.
```go
func main() {
    log.InitializeLogging("virtio-hook-sidecar")
 
    c := make(chan os.Signal, 2)
    signal.Notify(c, os.Interrupt,
        syscall.SIGHUP,
        syscall.SIGINT,
        syscall.SIGTERM,
        syscall.SIGQUIT)
    go func() {
        log.Log.Errorf("Listening signal in background")
        s := <-c
        log.Log.Errorf("Received terminating signal: %v, exiting now.", s)
        os.Exit(0) // second signal. Exit directly.
    }()
```

**Environment**:
- KubeVirt version (use `virtctl version`):  v0.59.0
- Kubernetes version (use `kubectl version`):  1.22.4
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration:  hardware
- OS (e.g. from /etc/os-release):  ubuntu-22.04
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by victortoso** [comment]
Seems a duplicate of https://github.com/kubevirt/kubevirt/issues/8395

**Comment by chinglinwen** [comment]
Yep, didn't find it before.
