### ISSUE TITLE
Rename VirtualMachine to VirtualMachineInstance and OfflineVirtualMachine to VirtualMachine

### ISSUE THREAD

**Issue by mlsorensen** [kubevirt/kubevirt#985]
Per [discussion](https://groups.google.com/d/topic/kubevirt-dev/hib474lSXwI/discussion), change OfflineVirtualMachine to StatefulVirtualMachine.

**Comment by itamarh** [comment]
Are we doing a version in which both are supported as OfflineVirtualMachine gets deprecated, or just switch?

**Comment by fabiand** [comment]
Yes, we intentionally stay a prerelease for now in order to have the freedom.

But we can/should do a few things to be friendly:

1. introduce warnings for a release or two (in events, inlogs, in docs, in release notes)
2. change the entity name

**Comment by rmohr** [comment]
We are in alpha. I would simply rename it.

**Comment by michalskrivanek** [comment]
I'd rather see OVM/VM as VirtualMachine/[Running|Active]VirtualMachine . For any management interface the OVM is the resource you're going to primarily work with.
In any case, if you change it then please do not change it again in few months:)

**Comment by rmohr** [comment]
> For any management interface the OVM is the resource you're going to primarily work with.

If you want the behaviour of a StatefulVirtualMachines, then yes. There is no reason or possibility to work with a StatefulVirtualMachine if you want a VirtualMachineReplicaSet, or possible future things like VirtualMachineStatefulSets, VirtualMachineJobs, VirtualMachineCronJob, ...

So a huge difference is, that what you are choosing as the owner of the VirtualMachine tells to a degree something about its purpose (and also what the cluster can do for you, so that you have to do less).

**Comment by michalskrivanek** [comment]
makes sense. so...we talked about the OVM being a case of a set with 1 replica before..so why don't we skip it completely and just use VirtualMachine[Stateful|Replica]Set with a semantic difference of replica 1 vs >1 and stateful/stateless? That was there is at least less objects to deal with

**Comment by mlsorensen** [comment]
That's a good point. I think the renaming is prudent simply because it's a simple change to something already in place. Just jumping straight to VirtualMachineStatefulSet would presumably require more effort, and in the meantime we allow OfflineVirtualMachine to become entrenched, and who knows how long it will ultimately stay around.

**Comment by fabiand** [comment]
Currently I tend to keep it, as one important story for KubeVirt is to allow importing leagcy VMs into Kubernetes.

In the classic use-case we we have two strong side: Individual machine management (ovirt, vmware) cloud management (openstack).

TO me it is important the we do our nbest to support these "themes" of virtualization. Having a dedicated entity which for one of the use-cases thus seems to be a good thing.

Just to share my thoughts.

**Comment by fabiand** [comment]
This is done.
