### ISSUE TITLE
Add support booting (of multiboot kernels) with a virtio-net/virtio-blk device

### ISSUE THREAD

**Issue by ansiwen** [kubevirt/kubevirt#989]
There are some small workloads, that would benefit from being managed by a orchestration framework like kubernetes, like unikernels for example. It would be nice to be able to directly start these kernels without wrapping them in an otherwise useless diskimage with bootloader. Also these workloads usually need a pure virtio-net (and/or virtio-blk) device. Currently the VM is started with an e1000 network device. It would be helpful to allow a kubevirt VM specification that results in the end in a command similar to this:

`qemu-system-x86_64 -cpu host -enable-kvm -m 128 -nodefaults -no-acpi -display none -serial stdio -device virtio-net,netdev=n0 -netdev tap,id=n0,ifname=tap100,script=no,downscript=no -device isa-debug-exit -kernel /foo/bar/unikernel.virtio`

**Comment by rmohr** [comment]
@ansiwen hi, 

> There are some small workloads, that would benefit from being managed by a orchestration framework like kubernetes, like unikernels for example.

sounds useful in general. How would you want to ship the kernel? Packed inside a container image like we do with the registry disk? Alongside disk images in pvcs? Maybe having an extra volume type? Did you have something in mind already?

> Currently the VM is started with an e1000 network device. It would be helpful to allow a kubevirt VM specification that results in the end in a command similar to this:

Yes we need to adress that soon. There are some issues piling up because we don't make it configurable.

**Comment by ansiwen** [comment]
@rmohr: I don't have a clear opinion yet, how to ship the kernel. Inside a container image sounds convenient, because it would be the same distribution as for normal containers. It feels a bit like "abuse" though. An alternative would be a generic URL to the image or a tar ball? Not sure if this is practical though. Does it make sense in some cases to use both a filesystem and a kernel separately? Then it might be useful to put it in the filesystem under a standardized name, or having a file like .multiboot_kernel that contains a link to the kernel image file. I'm just brainstorming. No idea what would be the best.

Regarding the network interface: I tried to put an "interfaces" array into the devices map in the OfflineVirtualMachine or VirtualMachinePreset spec, somthing like this:

```
devices:
  interfaces:
    - type: bridge
      model:
        type: virtio
      source:
        bridge: br1
```

but it seems to get ignored.

**Comment by fabiand** [comment]
For sure!

PRs are welcome - in what form soever :) As you know they can change over time - and become a greater good. Well, I'm probably exaggerating now ;)

Here is our contributor guide: https://github.com/kubevirt/kubevirt/blob/master/CONTRIBUTING.md

(Which might need an update)

**Comment by fabiand** [comment]
depends on https://github.com/kubevirt/kubevirt/issues/1067

**Comment by booxter** [comment]
For the record, latest kubevirt API supports specifying model for network interfaces: https://kubevirt.io/api-reference/master/definitions.html#_v1_interface (Note the model is on interfaces: level not bridge: level.)

@ansiwen Apart from model, is there anything else that is missing for your use case?

**Comment by fabiand** [comment]
virtio-net is supported.

Now, I wonder what needs to be done to support virtio-blk

@aglitke thoughts?

/remove-lifecycle rotten

**Comment by booxter** [comment]
We haven't heard from the author of the issue. `virtio-net` support is present. I am closing it. Feel free to reopen it if you are still interested in it.
