### ISSUE TITLE
PCI device assignments don't take into account IOMMU groups when selecting PCI devices for a VM.

### ISSUE THREAD

**Issue by mtaylor91** [kubevirt/kubevirt#9891]
**Is your feature request related to a problem? Please describe**:
I run kubevirt on a cluster with a machine with two identical GPUs (NVIDIA 2080TIs).  When booting my Windows and Ubuntu guests, I frequently (always?) find that the VGA adapter and audio device are assigned from separate cards, resulting in broken audio (no sound from guests - maybe it's going to the other card, but as I use audio over HDMI I can't very well tell my TV to use video from HDMI 1 and sound from HDMI 2).

**Describe the solution you'd like**:
Option 1: Prefer devices in the same IOMMU groups when assigning PCI devices to VMs.
Option 2: Allow specifying PCI address hints in addition to vendor/model IDs when specifying PCI devices.

**Describe alternatives you've considered**:
Currently as a hack I can work around it by unbinding one GPU from vfio-pci, booting the VM, then re-binding to vfio-pci and restarting virt-handler.

**Additional context**:
I'd be happy to help with implementing one of the proposed options if someone can point me in the right direction.

**Comment by mtaylor91** [comment]
I believe this is handled via device plugins, correct?

If so, would an implementation of GetPreferredAllocation be the right approach?

[This page](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/device-plugins/) seems to suggest that the device plugin can provide allocation hints to the kubernetes devicemanager.

> // GetPreferredAllocation returns a preferred set of devices to allocate
      // from a list of available ones. The resulting preferred allocation is not
      // guaranteed to be the allocation ultimately performed by the
      // devicemanager. It is only designed to help the devicemanager make a more
      // informed allocation decision when possible.
      rpc GetPreferredAllocation(PreferredAllocationRequest) returns (PreferredAllocationResponse) {}

**Comment by mtaylor91** [comment]
Fixed in https://github.com/kubevirt/kubevirt/pull/10356

**Comment by alicefr** [comment]
@mtaylor91 Option 2 has already been proposed in the past but refused because it requires the admin to know exactly which GPU is bound to which PCI address. 

About option 1, do you think is it desirable to always apply this preference? Or should be this configurable, like for example by specifying it in KubeVirt CR under the resource name?
