### ISSUE TITLE
virt image-upload times out at Waiting for PVC

### ISSUE THREAD

**Issue by abacusv81** [kubevirt/kubevirt#9904]
**What happened**:

I am trying kubvirt to migrate VMs and tried the Lab1 which worked fine, I am now trying to import image stored locally on the node. This is a single node kube cluster. I am unable to upload the image to use it for vm bringup. the virt image-upload is timing out.

kubectl get service cdi-uploadproxy -n cdi
```
NAME              TYPE        CLUSTER-IP      EXTERNAL-IP   PORT(S)   AGE
cdi-uploadproxy   ClusterIP   10.96.215.188   <none>        443/TCP   16h
```

```
kubectl virt image-upload --uploadproxy-url=https://10.96.215.188 --insecure  --pvc-name=cirros-upload --size=500Mi --image-path=$HOME/cirros-0.3.0-x86_64-disk.img --no-create
Flag --pvc-name has been deprecated, specify the name as the second argument instead.
Using existing PVC default/cirros-upload
Waiting for PVC cirros-upload upload pod to be ready...
You are using a client virtctl version that is different from the KubeVirt version running in the cluster
Client Version: v0.59.1
Server Version: v1.0.0-beta.0
timed out waiting for the condition
```

The CDI version is v1.56.0

I have gone through 
https://github.com/kubevirt/kubevirt/issues/2184 and doesnt seem to be the case as

CDI > 1.7
image is raw
and I also created additional PV for scratch 
```

kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM            STORAGECLASS   REASON   AGE
pv0001                                     5Gi        RWO            Retain           Available                                            18h
pv0002                                     5Gi        RWO            Retain           Available                                            3h19m
pv0003                                     500Mi      RWX            Retain           Available                                            3h16m
```

**What you expected to happen**:

Expectation is for the image-upload to succeed and PVC to be successfully created and able to bringup the image from this PVC.

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

Mentioned above. 

**Additional context**:
` kubectl logs cdi-uploadproxy-7bc4754484-6vnbv -n cdi
I0613 09:05:47.890955       1 uploadproxy.go:64] Note: increase the -v level in the api deployment for more detailed logging, eg. -v=2 or -v=3
W0613 09:05:47.891167       1 client_config.go:617] Neither --kubeconfig nor --master was specified.  Using the inClusterConfig.  This might not work.
I0613 09:05:47.994015       1 certwatcher.go:125] Updated current TLS certificate
I0613 09:05:47.995117       1 certwatcher.go:81] Starting certificate watcher
I0613 21:07:22.645136       1 certwatcher.go:136] certificate eventevent"/var/run/certs/cdi-uploadproxy-server-cert/tls.crt": REMOVE
I0613 21:07:22.645688       1 certwatcher.go:125] Updated current TLS certificate
I0613 21:07:22.645836       1 certwatcher.go:136] certificate eventevent"/var/run/certs/cdi-uploadproxy-server-cert/tls.key": REMOVE
I0613 21:07:22.646300       1 certwatcher.go:125] Updated current TLS certificate`

```

kubectl describe pod cdi-uploadproxy-7bc4754484-6vnbv -n cdi
Name:                 cdi-uploadproxy-7bc4754484-6vnbv
Namespace:            cdi
Priority:             1000000000
Priority Class Name:  kubevirt-cluster-critical
Service Account:      cdi-uploadproxy
Node:                 kind-control-plane/172.19.0.2
Start Time:           Tue, 13 Jun 2023 09:05:22 +0000
Labels:               app.kubernetes.io/component=storage
                      app.kubernetes.io/managed-by=cdi-operator
                      cdi.kubevirt.io=cdi-uploadproxy
                      operator.cdi.kubevirt.io/createVersion=v1.56.0
                      pod-template-hash=7bc4754484
Annotations:          <none>
Status:               Running
IP:                   10.244.0.16
IPs:
  IP:           10.244.0.16
Controlled By:  ReplicaSet/cdi-uploadproxy-7bc4754484
Containers:
  cdi-uploadproxy:
    Container ID:    containerd://23da25745aebdb62816280d5dc39cfb9dcecafc9b389d9b831e0f30832bcebb4
    Image:           quay.io/kubevirt/cdi-uploadproxy:v1.56.0
    Image ID:        quay.io/kubevirt/cdi-uploadproxy@sha256:4567f6d25c99b34916286fb659d36802f56c1352d4e8ea5b2d77dc2cd10d755c
    Port:            <none>
    Host Port:       <none>
    SeccompProfile:  RuntimeDefault
    Args:
      -v=1
    State:          Running
      Started:      Tue, 13 Jun 2023 09:05:47 +0000
    Ready:          True
    Restart Count:  0
    Requests:
      cpu:      10m
      memory:   150Mi
    Readiness:  http-get https://:8443/healthz delay=2s timeout=1s period=5s #success=1 #failure=3
    Environment:
      APISERVER_PUBLIC_KEY:  <set to the key 'id_rsa.pub' in secret 'cdi-api-signing-key'>  Optional: false
    Mounts:
      /var/run/certs/cdi-uploadproxy-server-cert from server-cert (ro)
      /var/run/certs/cdi-uploadserver-client-cert from client-cert (ro)
      /var/run/secrets/kubernetes.io/serviceaccount from kube-api-access-zgwwm (ro)
Conditions:
  Type              Status
  Initialized       True
  Ready             True
  ContainersReady   True
  PodScheduled      True
Volumes:
  server-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cdi-uploadproxy-server-cert
    Optional:    false
  client-cert:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  cdi-uploadserver-client-cert
    Optional:    false
  kube-api-access-zgwwm:
    Type:                    Projected (a volume that contains injected data from multiple sources)
    TokenExpirationSeconds:  3607
    ConfigMapName:           kube-root-ca.crt
    ConfigMapOptional:       <nil>
    DownwardAPI:             true
QoS Class:                   Burstable
Node-Selectors:              kubernetes.io/os=linux
Tolerations:                 CriticalAddonsOnly op=Exists
                             node.kubernetes.io/not-ready:NoExecute op=Exists for 300s
                             node.kubernetes.io/unreachable:NoExecute op=Exists for 300s
Events:                      <none>
```

**Environment**:
- KubeVirt version (use `virtctl version`): N/A 0.59.1
- Kubernetes version (use `kubectl version`): N/A v1.27.2
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A Running on VMs with nested virtualization enabled. 
- OS (e.g. from /etc/os-release): N/A Ubuntu 18.04.
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by awels** [comment]
So there are 2 pods involved here, the upload proxy which is running and the upload-server which you did not give information about. The upload-proxy proxies to the upload server which should be running in the namespace you are using. I see you are using both the `--pvc-name` and `--no-create` flags. This assumes you have already created the target PVC in the target namespace (it will create the scratch space pvc for you). Can you see if the upload server pod is running in the target namespace?

**Comment by abacusv81** [comment]
Thank you for the response. Here is what I have for the pods running in the namespace.
`kubectl get pod -n cdi
NAME                               READY   STATUS    RESTARTS   AGE
cdi-apiserver-787477cccb-hvl6w     1/1     Running   0          30h
cdi-deployment-7fd5bd8cbc-pxzns    1/1     Running   0          30h
cdi-operator-8fd9945c6-vp8gv       1/1     Running   0          30h
cdi-uploadproxy-7bc4754484-6vnbv   1/1     Running   0          30h`

**Comment by awels** [comment]
I am looking for the upload server in the namespace you are uploading to. Not the CDI installation namespace. I am assuming those are not the same. The name should be upload-server-xxxxx-yyyy with X and Y being random numbers and letters.

**Comment by abacusv81** [comment]
Could you point me to how this is spinned up. I dont see any documentation mentioning about upload-server. I am following this document for importing the image. 
https://kubevirt.io/user-guide/operations/containerized_data_importer/
and 
https://github.com/kubevirt/containerized-data-importer/blob/main/doc/upload.md
Not sure which part I am missing here

Also I could not created UploadToken as mentioned in the document there.
```
apiVersion: upload.cdi.kubevirt.io/v1beta1
kind: UploadTokenRequest
metadata:
  name: upload-datavolume
  namespace: default
spec:
  pvcName: upload-datavolume
```

```
kubectl apply -f secret.yaml
error: resource mapping not found for name: "upload-datavolume" namespace: "default" from "secret.yaml": no matches for kind "UploadTokenRequest" in version "upload.cdi.kubevirt.io/v1beta1"
ensure CRDs are installed first
```
Let me know what step is missing here to get the upload-server running?

**Comment by abacusv81** [comment]
@awls thanks for the clarification. For some reason PVCs are not getting bound to available PV. I will try fix this today. Meanwhile if you see something missing in the process please update. 
```

 kubectl virt image-upload dv new-upload-dv --uploadproxy-url=https://10.96.215.188 --insecure --size=500Mi --image-path=$HOME/cirros-0.3.0-x86_64-disk.img --access-mode ReadWriteOnce
PVC default/new-upload-dv not found
DataVolume default/new-upload-dv created
Waiting for PVC new-upload-dv upload pod to be ready...
You are using a client virtctl version that is different from the KubeVirt version running in the cluster
Client Version: v0.59.1
Server Version: v1.0.0-beta.0
cannot upload to DataVolume in WaitForFirstConsumer state, make sure the PVC is Bound

ubuntu@ip-:~$ kubectl get pvc
NAME                STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
new-upload-dv       Pending                                                                        standard       33s

ubuntu@ip-:~$ kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                 STORAGECLASS   REASON   AGE
mypv                                       5Gi        RWO            Retain           Bound       default/mycirrospvc   manual                  37h
pv0001                                     5Gi        RWO            Retain           Available                                                 2d13h
pv0002                                     5Gi        RWO            Retain           Available                                                 46h
pv0003                                     500Mi      RWX            Retain           Available                                                 46h
pvc-67b9f46c-c0b5-4a71-90f8-f6a3a37dde16   5Gi        RWO            Delete           Bound       default/fedora        standard                2d14h
pvc-7d514a77-3b79-4fbd-b131-e07fecfce48a   5Gi        RWO            Delete           Bound       default/cirros        standard                37h
```

**Comment by awels** [comment]
So in order for k8s to bind a PVC to a PV the following have to match:
- access modes
- volume mode
- pv capacity >= pvc request size
- storage class has to match (or both have no storage class)

Looking at what you posted the pvc has storage class 'standard' while the pvs do not. And thus they won't bind.

**Comment by abacusv81** [comment]
@awels thats what I thought but even after creating the pv with matching class, capacity, access mode I dont see it getting bound. 
```
ubuntu@ip-:~$ kubectl get pvc
NAME                STATUS    VOLUME                                     CAPACITY   ACCESS MODES   STORAGECLASS   AGE
cirros              Bound     pvc-7d514a77-3b79-4fbd-b131-e07fecfce48a   5Gi        RWO            standard       2d3h
cirros-upload       Pending                                                                        standard       3d3h
fedora              Bound     pvc-67b9f46c-c0b5-4a71-90f8-f6a3a37dde16   5Gi        RWO            standard       3d4h
mycirrospvc         Bound     mypv                                       5Gi        RWO            manual         2d3h
new-upload-dv       Pending                                                                        standard       13h
new-upload-pvc004   Pending                                                                        standard       13h
upload-datavolume   Pending                                                                        standard       3d3h

ubuntu@ip-:~$ kubectl virt image-upload dv new-upload-pvc004 --uploadproxy-url=https://10.96.215.188 --insecure --size=500Mi --image-path=$HOME/cirros-0.3.0-x86_64-disk.img --access-mode ReadWriteOnce
Using existing PVC default/new-upload-pvc004
You are using a client virtctl version that is different from the KubeVirt version running in the cluster
Client Version: v0.59.1
Server Version: v1.0.0-beta.0
cannot upload to DataVolume in WaitForFirstConsumer state, make sure the PVC is Bound

ubuntu@ip-:~$ kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                 STORAGECLASS   REASON   AGE
mypv                                       5Gi        RWO            Retain           Bound       default/mycirrospvc   manual                  2d3h
pv0001                                     5Gi        RWO            Retain           Available                                                 3d2h
pv0002                                     5Gi        RWO            Retain           Available                                                 2d12h
pv0003                                     500Mi      RWX            Retain           Available                                                 2d12h
pv0004                                     500Mi      RWO            Retain           Available                         standard                13h
pvc-67b9f46c-c0b5-4a71-90f8-f6a3a37dde16   5Gi        RWO            Delete           Bound       default/fedora        standard                3d4h
pvc-7d514a77-3b79-4fbd-b131-e07fecfce48a   5Gi        RWO            Delete           Bound       default/cirros        standard                2d3h
```

**Comment by awels** [comment]
I would check the request size of the PVC, we pad the request size a little bit to account for filesystem overhead.

**Comment by abacusv81** [comment]
@awels tried increasing the size too but with same issue. I think its nothing to image-upload in my opinion. I am unable to bind any pvc with the available PV with storage-class standard. storage class manual seem to work fine. However, virt image-upload doesnt recognize manual storage-class.

**Comment by awels** [comment]
does the storage class exist?

**Comment by abacusv81** [comment]
storage-class manual? It does. 

kubectl get pv
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                   STORAGECLASS   REASON   AGE
mypv                                       5Gi        RWO            Retain           Bound       default/mycirrospvc     manual                  2d3h
pv0001                                     5Gi        RWO            Retain           Available                                                   3d3h
pv0002                                     5Gi        RWO            Retain           Available                                                   2d12h
pv0003                                     500Mi      RWX            Retain           Available                                                   2d12h
pv0004                                     500Mi      RWO            Retain           Available                           standard                14h
pvc-67b9f46c-c0b5-4a71-90f8-f6a3a37dde16   5Gi        RWO            Delete           Bound       default/fedora          standard                3d4h
pvc-7d514a77-3b79-4fbd-b131-e07fecfce48a   5Gi        RWO            Delete           Bound       default/cirros          standard                2d4h
**task-pv-volume                             500Mi      RWO            Retain           Bound       default/test-pv-claim   manual                  3m56s**
upload-pv-volume                           500Mi      RWO            Retain           Available                           manual                  5s


```
kubectl virt image-upload dv upload-pv --uploadproxy-url=https://10.96.215.188 --insecure --size=500Mi --image-path=$HOME/cirros-0.3.0-x86_64-disk.img --access-mode ReadWriteOnce --storage-class manual
PVC default/upload-pv not found
You are using a client virtctl version that is different from the KubeVirt version running in the cluster
Client Version: v0.59.1
Server Version: v1.0.0-beta.0
storageclasses.storage.k8s.io "manual" not found
```

**Comment by abacusv81** [comment]
On the other hand kubevirt lab1 exercise seem to create PVC with storage class as standard. So standard does exist as well.
```
NAME                                       CAPACITY   ACCESS MODES   RECLAIM POLICY   STATUS      CLAIM                   STORAGECLASS   REASON   AGE
pvc-67b9f46c-c0b5-4a71-90f8-f6a3a37dde16   5Gi        RWO            Delete           Bound       default/fedora          standard                3d4h
pvc-7d514a77-3b79-4fbd-b131-e07fecfce48a   5Gi        RWO            Delete           Bound       default/cirros          standard                2d4h 
```

**Comment by awels** [comment]
The storage class should be whatever storage is provided with your k8s cluster. Are any of those storage classes the default storage class?

**Comment by abacusv81** [comment]
@awels   for the fact that cloudinitdisk  creates the PVC with standard SC successfully means its there. I could not create other storageClass on this cluster. I am thinking that this issue could be due to feature gate DataVolume not set. 

I re created a new 4 node cluster with portworx Storage class on it and I am able to create through cloudinitdisk with no issue creating PVC with dynamic pv provisioning. I had enabled DataVolume feature gate in this one. I still have the old cluster, I will try enabling the feature gate and see if that works.

**Comment by Gohoy** [comment]
virtctl  image-upload dv test-dv4 --access-mode=ReadWriteOnce --size=10Gi --image-path=
/home/gohoy/tmp/euler.qcow2  --uploadproxy-url=https://10.97.59.196 --insecure --no-create --wait-secs=240

Using existing PVC default/test-dv4
Waiting for PVC test-dv4 upload pod to be ready...
timed out waiting for the condition


I got a similar issue with two different versions: Kubernetes 1.23.1, KubeVirt 0.52.0, and CDI 1.49.0; as well as Kubernetes 1.27, KubeVirt 1.0, and CDI 1.56.1.

**Comment by moyunnie** [comment]
兄弟你解决了么 我也遇到了这问题
