### ISSUE TITLE
kubevirt release automation: push container manifests failed on 1.0-rc0 build

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#9908]
**What happened**:
Job [push-release-kubevirt-tag](https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-release-kubevirt-tag/1668693674222948352#1:build-log.txt%3A2350) failed on step `hack/push-container-manifest.sh`

Excerpt:
```
...
BUILD_ARCH=aarch64,x86_64 DOCKER_PREFIX=quay.io/kubevirt DOCKER_TAG=v1.0.0-rc.0 hack/push-container-manifest.sh
cat: /home/prow/go/src/github.com/kubevirt/kubevirt/_out/digests/aarch64/bazel-bin/push-conformance.digest: No such file or directory
push_pin
podman manifest create quay.io/kubevirt/conformance:v1.0.0-rc.0 --amend quay.io/kubevirt/conformance@ --amend quay.io/kubevirt/conformance@sha256:6df1bc5b5d0157ce268677fa640e495e2602c9c22f2107f97b544a10b210c3f1
Error: invalid reference format
Error: accepts 2 arg(s), received 1
...
```

/cc @davidvossel @rthallisey

**What you expected to happen**:
Job should succeed in creating the container manifests.

**How to reproduce it (as minimally and precisely as possible)**:
Rerun the job here: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-release-kubevirt-tag/1668693674222948352#1:build-log.txt%3A2350

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by dhiller** [comment]
From what I understand the missing file `/home/prow/go/src/github.com/kubevirt/kubevirt/_out/digests/aarch64/bazel-bin/push-conformance.digest` is causing the empty tag part on the section

```
... --amend quay.io/kubevirt/conformance@ ...
                                        ^^^
```

**Comment by 0xFelix** [comment]
This might be related to https://github.com/kubevirt/kubevirt/pull/9782

**Comment by rmohr** [comment]
@rthallisey @zhlhahaha maybe related to https://github.com/kubevirt/kubevirt/pull/9703?


I don't have access to my workstation ATM, so can't check myself.

**Comment by fossedihelm** [comment]
> @rthallisey @zhlhahaha maybe related to #9703?
> 
> I don't have access to my workstation ATM, so can't check myself.

I think this is correct, the aarch64 digests are placed under `/digests/crossbuild-aarch64/`, but then in `hack/push-container-manifest.sh` we look at `/digests/aarch64/`

**Comment by zhlhahaha** [comment]
> > @rthallisey @zhlhahaha maybe related to #9703?
> > I don't have access to my workstation ATM, so can't check myself.
> 
> I think this is correct, the aarch64 digests are placed under `/digests/crossbuild-aarch64/`, but then in `hack/push-container-manifest.sh` we look at `/digests/aarch64/`

Yes, you are right.

**Comment by dhiller** [comment]
@davidvossel  https://github.com/kubevirt/kubevirt/pull/9915 should fix this. We can try again after this is merged.

**Comment by dhiller** [comment]
I'll try to rerun the job after the merge

**Comment by dhiller** [comment]
Release is there: https://github.com/kubevirt/kubevirt/releases/tag/v1.0.0-rc.1

FYI @davidvossel @rthallisey @fabiand

**Comment by fossedihelm** [comment]
@dhiller are we safe with this error? https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-release-kubevirt-tag/1670721048800137216#1:build-log.txt%3A2354

**Comment by dhiller** [comment]
> @dhiller are we safe with this error? https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-release-kubevirt-tag/1670721048800137216#1:build-log.txt%3A2354

Thanks for spotting this, this actually was caused by a new image, I guess, whose repo wasn't yet public. Do you know whom we can contact to make sure?

**Comment by dhiller** [comment]
^^ @fossedihelm

**Comment by dhiller** [comment]
Image repo was https://quay.io/repository/kubevirt/libguestfs

**Comment by dhiller** [comment]
After I have made the repo public, I've triggered another release for `v1.0.0-rc.2`, job running here: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-release-kubevirt-tag/1670774930406379520

**Comment by fossedihelm** [comment]
> > @dhiller are we safe with this error? https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-release-kubevirt-tag/1670721048800137216#1:build-log.txt%3A2354
> 
> Thanks for spotting this, this actually was caused by a new image, I guess, whose repo wasn't yet public. Do you know whom we can contact to make sure?

@alicefr Maybe you can help us?

**Comment by alicefr** [comment]
@fossedihelm I'm not quite sure what is the issue here. I don't have the right to push images in quay. Have you created the manifest for libguestfs?

**Comment by dhiller** [comment]
> @fossedihelm I'm not quite sure what is the issue here. I don't have the right to push images in quay. Have you created the manifest for libguestfs?

@alicefr I was just asking what the libguestfs image was about, since I wasn't aware that it existed. I understand it is a new one, appearing first time for `v1.0`, correct?

**Comment by dhiller** [comment]
:confused: the last build got confused by the existing tag rc1 on k/k. I wiped all the tags and releases, starting now from `rc.0` again.

**Comment by dhiller** [comment]
There we go :crossed_fingers: 

https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-release-kubevirt-tag/1670800592932442112

**Comment by dhiller** [comment]
Seems like the build for libguestfs image is somehow broken. @alicefr can you help here? Please see https://quay.io/repository/kubevirt/libguestfs?tab=tags&tag=v1.0.0-rc.0

**Comment by alicefr** [comment]
@dhiller do you have somewhere any logs of the build?

**Comment by alicefr** [comment]
> > @fossedihelm I'm not quite sure what is the issue here. I don't have the right to push images in quay. Have you created the manifest for libguestfs?
> 
> @alicefr I was just asking what the libguestfs image was about, since I wasn't aware that it existed. I understand it is a new one, appearing first time for `v1.0`, correct?

No, actually, we have since 2021, so it has been a while now :). It is used by `virtctl guestfs` command

**Comment by alicefr** [comment]
@dhiller we have this one: https://quay.io/repository/kubevirt/libguestfs-tools . Maybe we changed the name?

**Comment by rmohr** [comment]
@dhiller I only see this in the build logs:

```
INFO: Build completed successfully, 7 total actions
2023/06/19 15:32:10 Successfully pushed Docker image to quay.io/kubevirt/libguestfs-tools:v1.0.0-rc.0-amd64
```

What exactly looks broken at the moment? I don't see `quay.io/kubevirt/libguestfs` anywhere in the build logs.

**Comment by rmohr** [comment]
I could imagine that during the multi-arch image creation that we somehow loose the `-tools` suffix on the  image ...

**Comment by fossedihelm** [comment]
@rmohr https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-release-kubevirt-tag/1670800592932442112#1:build-log.txt%3A2301 here we are trying to create manifest for `libguestfs` without "-tools"

> I could imagine that during the multi-arch image creation that we somehow loose the -tools suffix on the image ...

Same suspect

**Comment by rmohr** [comment]
> @rmohr https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-release-kubevirt-tag/1670800592932442112#1:build-log.txt%3A2301 here we are trying to create manifest for `libguestfs` without "-tools"
> 
> > I could imagine that during the multi-arch image creation that we somehow loose the -tools suffix on the image ...
> 
> Same suspect

Here, that should be it: https://github.com/kubevirt/kubevirt/blob/main/hack/push-container-manifest.sh#L31

We assume that the `.digest` file has the same name like the final container and that the push target name for bazel is `push={name}`. That is always true, except for libguestfs, where the push target name is `push-libguestfs`, the digest name is `push-libguestfs.digest`, but the actual image name is `libguestfs-tools`.

**Comment by alicefr** [comment]
> > @rmohr https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-release-kubevirt-tag/1670800592932442112#1:build-log.txt%3A2301 here we are trying to create manifest for `libguestfs` without "-tools"
> > > I could imagine that during the multi-arch image creation that we somehow loose the -tools suffix on the image ...
> > 
> > 
> > Same suspect
> 
> Here, that should be it: https://github.com/kubevirt/kubevirt/blob/main/hack/push-container-manifest.sh#L31
> 
> We assume that the `.digest` file has the same name like the final container and that the push target name for bazel is `push-{name}`. That is always true, except for libguestfs, where the push target name is `push-libguestfs`, the digest name is `push-libguestfs.digest`, but the actual image name is `libguestfs-tools`.

Nice catch @rmohr! Yes, definitely that's the problem. I'd suggest we add the `-tools` everywhere, in this way we don't need to mess up with the already published images

**Comment by rmohr** [comment]
> Nice catch @rmohr! Yes, definitely that's the problem. I'd suggest we add the `-tools` everywhere, in this way we don't need to mess up with the already published images

Sounds like a good plan. :+1:

**Comment by dhiller** [comment]
@xpivarc FYI

**Comment by dhiller** [comment]
/reopen

We need to wait until https://github.com/kubevirt/kubevirt/pull/9956 merges

**Comment by xpivarc** [comment]
/close
v1.0.0 is out :champagne:
