### ISSUE TITLE
Rework the `instancetype.kubevirt.io` `ShortNames`

### ISSUE THREAD

**Issue by lyarwood** [kubevirt/kubevirt#9926]
/area instancetype

**What happened**:

The current shortnames are a mess and should be reworked into something more uniform before `v1`:

```
$ git grep ShortNames pkg/virt-operator/resource/generate/components/crds.go | egrep -i '(instancetype|pref|vmcp)'
pkg/virt-operator/resource/generate/components/crds.go:                 ShortNames: []string{"vminstancetype", "vminstancetypes", "vmf", "vmfs"},
pkg/virt-operator/resource/generate/components/crds.go:                 ShortNames: []string{"vmclusterinstancetype", "vmclusterinstancetypes", "vmcf", "vmcfs"},
pkg/virt-operator/resource/generate/components/crds.go:                 ShortNames: []string{"vmpref", "vmprefs", "vmp", "vmps"},
pkg/virt-operator/resource/generate/components/crds.go:                 ShortNames: []string{"vmcp", "vmcps"},
```

**What you expected to happen**:

**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by xpivarc** [comment]
@lyarwood was this done?
