### ISSUE TITLE
Expose features gate to regular users

### ISSUE THREAD

**Issue by alicefr** [kubevirt/kubevirt#9934]
**Is your feature request related to a problem? Please describe**:
Create an option in kubevirt API to expose the feature gate enable in the cluster. In this way, regular users will be able to understand which feature they can use. 

**Additional context**:
Discussion in [mailing list](https://groups.google.com/g/kubevirt-dev/c/cXyMaOok5s0/m/UgbpTfOYAgAJ)

**Comment by aroramrinaal** [comment]
Hey @alicefr , 
I would like to work on this good-first-issue.
Could you give me just a little bit of context, so i can start working on the PR.

**Comment by alicefr** [comment]
@aroramrinaal Sure, you can find the discussion in the mailing list thread I put in the description. 

The idea is to have an API where KubeVirt could expose the enabled feature gate. Today, regular users cannot query KubeVirt CR, hence they discover that a feature isn't enabled only by submitting a VM that wants to use that feature.

As an example, try to use virtctl addVolume without the `HotplugVolumes` feature gate enabled.

Ideally, we could have an additional command in virtctl that can query this new endpoint in virt-api and get a list of fg enabled in the cluster. 

You can find the complete list of fg in https://github.com/kubevirt/kubevirt/blob/main/pkg/virt-config/feature-gates.go#L26 and you can take the [`version` endpoint](https://github.com/kubevirt/kubevirt/blob/main/staging/src/kubevirt.io/client-go/version/version.go) as an example of how to expose certain information.

**Comment by aroramrinaal** [comment]
Okay, I will give it a try for **sure!**

**Comment by aroramrinaal** [comment]
@alicefr , 
I want to know how we can expose the enabled feature gates in KubeVirt to regular users. Is there a way to create an API endpoint that provides access to the list of enabled feature gates within the cluster? I'm curious about the steps involved in implementing a handler function that filters out the enabled feature gates and presents a comprehensive list of available features. Additionally, it would be helpful to understand how we can define the API route and update the server configuration to allow regular users like me to easily query and access information about the enabled feature gates in KubeVirt.

**Comment by alicefr** [comment]
@aroramrinaal I mentioned the `version` endpoint because it is a simple example how to expose information listed in KubeVirt CR to regular users. I'd suggest you to have a look to the code and try to understand the flow.
