### ISSUE TITLE
"./cluster/kubectl.sh get vms" after cluster-sync claims "vms" resource is not supported

### ISSUE THREAD

**Issue by booxter** [kubevirt/kubevirt#994]
This happens once after cluster-sync; the second call to the same command always returns the correct result (no resources found).

```
[ihar@ws kubevirt]$ ./cluster/kubectl.sh get vms
the server doesn't have a resource type "vms"
[ihar@ws kubevirt]$ ./cluster/kubectl.sh get vms
No resources found.
```

**Comment by fabiand** [comment]
Could this be a timing issue?

I.e. does it also happen with a `sleep` or manual (human) sleep between the
two calls?

- fabian

**Comment by rmohr** [comment]
That is expected. It can take a few seconds until the kubernetes api server makes newly posted custom resource definitions available on the api. We could move our cluster-readiness check  from `automation/tests.sh` to `cluste/sync.sh`, to make it easier on the dev-side to see when everything is ready. @booxter would that help?

**Comment by booxter** [comment]
@rmohr I don't think that's a bootstrapping timing issue. I just put 5 minutes sleep between cluster-sync and kubectl commands, and the issue remains.

**Comment by rmohr** [comment]
interesting. And it is always the first call, right?

**Comment by booxter** [comment]
Yes, always the very first call only, and it's specific to kubevirt resources.

**Comment by booxter** [comment]
The issue seems to be related to short name (vms) used. If I instead call 'get virtualmachines', it works fine the first time and all consequent times regardless of whether I later use the shortened version.

**Comment by rmohr** [comment]
It seems to be a general caching issue in kubectl. Maybe worth filing a bug in kubernetes, if it does not already exist.

**Comment by fabiand** [comment]
@booxter could you please file a bug and crossreference this issue?

**Comment by booxter** [comment]
The issue is reported upstream at: https://github.com/kubernetes/kubernetes/issues/65517

**Comment by fabiand** [comment]
:+1:

**Comment by rmohr** [comment]
The issue still exists.

/remove-lifecycle stale
