### ISSUE TITLE
when runStrategy is Manual and vm is stopping then snapshot always failed  timeout

### ISSUE THREAD

**Issue by hanqingwu** [kubevirt/kubevirt#9944]
**What happened**:
when i set vm spec  runStrategy  manual  and  vm is stopping then snapshot failed 
**What you expected to happen**:
snapshot success
**How to reproduce it (as minimally and precisely as possible)**:
Steps to reproduce the behavior.
1. set vm spec runStrategy manual
2. make sure vm is stopped
3. set snapshot vm 

**Additional context**:
when vm running  , snapshot  success .

**Environment**:
- KubeVirt version (use `virtctl version`):   0.50.0

then I check the source code：
pkg/storage/snapshot/snapshot.go

func checkVMRunning(vm *kubevirtv1.VirtualMachine) (bool, error) {
	rs, err := vm.RunStrategy()
	if err != nil {
		return false, err
	}

	return rs != kubevirtv1.RunStrategyHalted, nil
}  

so , if  when runStrategy is Manual then  ,  this func  return  true (mean running) , actual  vm is stopped .

**Comment by hanqingwu** [comment]
so , i  should use  runStrategy Halted instead of  Manual ?

**Comment by aburdenthehand** [comment]
Thanks for raising this bug!
@mhenriks Are you able to help here?

**Comment by mhenriks** [comment]
yeah this is a bug
