### ISSUE TITLE
Impossible to execute a specific functional test

### ISSUE THREAD

**Issue by booxter** [kubevirt/kubevirt#995]
It seems there is no way to make 'make functest' execute a subset of test cases. Since the suite is very time consuming, we need a way to execute part of it. @vladikr told me he usually temporarily removes all unneeded test files while working on a particular test case but I think we should have something better.

**Comment by rmohr** [comment]
Changing 'It' to 'FIt' is enough Appending an F works for others too. Also, ginkgo supports regexp matching. Please read the Ginkgo manual for further details: https://onsi.github.io/ginkgo/

**Comment by rmohr** [comment]
@itamarh we do that already where appropriate. E.g. for Windows tests,...

**Comment by fabiand** [comment]
I talked with @nellyc about classifying tests, and on IRC @davidvossel had a similar idea.

The reasoning is prett ymuch as requested in this RFE: Our testsuite is large (GOOD!), but we might want to classify them into different tiers, this should speed up the testing for the lowest tier i.e. tier0, and i.e. tier0 could be a mandatory suite to pass before PRs can be merged.

IIRC then @lukas-bednar wanted to look into classiyfing the tests.

@lukas-bednar @nellyc any update from your side?

**Comment by cynepco3hahue** [comment]
@fabiand I already wrote `ast` parser for our tests - https://github.com/kubevirt/qe-tools/tree/master/pkg/polarion-generator, and had the idea to use it for tagging:
1) run `ast` parser and get only test names with a specific tag
2) generate `--focus=` parameter with names from the above section
3) run tests with `focus` parameter

The tool already supports `caseimportance` field
```
It("...", func(){
    // +polarion:caseimportance=critical
})
```
so we can use it to run tests by importance(sure first we will need to label each test case)
If we need, I can easily to add support for additional tags.

**Comment by rmohr** [comment]
> The reasoning is prett ymuch as requested in this RFE: Our testsuite is large (GOOD!), but we might want to classify them into different tiers, this should speed up the testing for the lowest tier i.e. tier0, and i.e. tier0 could be a mandatory suite to pass before PRs can be merged.

That is very disappointing. They should all pass and we are  workikng hard on improving that. We have some non-critical issues in the tests which make them still flaky and which are kind of self-healing, but still users would experience them too. If some tests are flaky, maintainers need to jump in, judge if the PR can still go in and initiate fixes for the tests.

Further instead of already right now thinking of not running all test we should improve the test speed. We can easily run three or four times as much tests in the same time like it is done right now.

Finally, since @nellyc and @lukas-bednar are mostly involved in running tests on already merged code, I would expect that they run them even more often, more randomized, ... to reveal even more issues + help working on resolving the issues, instead of thinking about not running all of them.

**Comment by nellyc** [comment]
for us, its not about not executing some tests, but about prioritizing the executions (tiered approach testing). We are going to execute all tests. 
As for PR testing you may reach a point where the tests are too time consuming, so having this criticality tag is not a bad idea in my opinion, of course, we dont have to use it right away

**Comment by booxter** [comment]
First, I don't suggest with this PR any changes to how we gate changes. I agree with @rmohr that the right approach is not ignoring test failures but prioritize them to have a suite that consistently passes.

The issue at stake here is only about helping engineers who iterate on test cases in development to avoid running time consuming (and irrelevant to their immediate goal) test cases. However optimized the suite is (even if we make it 10x quicker), there is value in being able to run just the case you are working on.

Thanks for the suggestion that I can replace "It" with "FIt". (An alternative I've heard that is somewhat similar is temporarily removing test files not immediately needed.) Indeed, a simple sed script should probably do the job, but I still find it a bit not developer friendly that I need to resort to this (and pollute my working environment with unnecessary changes).

I am new to golang practices, and what I am asking may be not as simple to achieve as I would expect it coming from Python background. But I would expect me to be able to pass a filename / filepath / regex via a envvar that would match against the whole suite to pick the necessary test cases to execute.

**Comment by rmohr** [comment]
> I am new to golang practices, and what I am asking may be not as simple to achieve as I would expect it coming from Python background. But I would expect me to be able to pass a filename / filepath / regex via a envvar that would match against the whole suite to pick the necessary test cases to execute.

You can: 

```bash
$ _out/tests/tests.test --help
  -ginkgo.focus string
    	If set, ginkgo will only run specs that match this regular expression.
```

To focus via a Makefile:

```bash
FUNC_TEST_ARGS='-ginkgo.fokus="whatever"' make functest
```

Hope that helps.

**Comment by booxter** [comment]
I was going to try it today and then document it somewhere for others' reference. (We probably need a TESTING document in the repo, what do you think?)

**Comment by rmohr** [comment]
> I was going to try it today and then document it somewhere for others' reference. (We probably need a TESTING document in the repo, what do you think?)

Sounds good. We currently have https://github.com/kubevirt/kubevirt/blob/master/docs/getting-started.md and https://github.com/kubevirt/kubevirt/blob/master/docs/debugging.md. You could either try to add it somehwere there, restructure these pages or add this testing document you mentioned.
