### ISSUE TITLE
Failed to create vmi！！！！

### ISSUE THREAD

**Issue by wenjunGU** [kubevirt/kubevirt#9951]
System version: CentOS7.8 
Kernel version:5.4.247-1.el7.elrepo.x86_64 
K8s version:1.18.3
Cdi Version:v1.56.0
Kubevirt version: v0.58.0
    After they were all created successfully, I started a vmi using the offhcial template, but I kept reporting errors. I tried to change all the versions again, but there was still an Error.Can you solve this? Help me 
Vm template yaml：
apiVersion: kubevirt.io/v1
kind: VirtualMachine
metadata:
  name: testvm
spec:
  running: false
  template:
    metadata:
      labels:
        kubevirt.io/size: small
        kubevirt.io/domain: testvm
    spec:
      domain:
        devices:
          disks:
            - name: containerdisk
              disk:
                bus: virtio
            - name: cloudinitdisk
              disk:
                bus: virtio
          interfaces:
          - name: default
            masquerade: {}
        resources:
          requests:
            memory: 4096M
      networks:
      - name: default
        pod: {}
      volumes:
        - name: containerdisk
          containerDisk:
            image: quay.io/kubevirt/cirros-container-disk-demo
        - name: cloudinitdisk
          cloudInitNoCloud:
            userDataBase64: SGkuXG4=

Error message：
{"component":"virt-launcher","level":"error","msg":"internal error: Child process (dmidecode -q -t 0,1,2,3,4,11,17) unexpected exit status 1: /dev/mem: No such file or directory","pos":"virCommandWait:2752","subcomponent":"libvirt","thread":"44","timestamp":"2023-06-20T08:23:39.053000Z"}

kubectl logs virt-launcher-testvm-25pt5
{"component":"virt-launcher","level":"info","msg":"Collected all requested hook sidecar sockets","pos":"manager.go:86","timestamp":"2023-06-20T09:41:25.597260Z"}
{"component":"virt-launcher","level":"info","msg":"Sorted all collected sidecar sockets per hook point based on their priority and name: map[]","pos":"manager.go:89","timestamp":"2023-06-20T09:41:25.600717Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon: qemu:///system","pos":"libvirt.go:497","timestamp":"2023-06-20T09:41:25.627598Z"}
{"component":"virt-launcher","level":"info","msg":"Connecting to libvirt daemon failed: virError(Code=38, Domain=7, Message='Failed to connect socket to '/var/run/libvirt/libvirt-sock': No such file or directory')","pos":"libvirt.go:505","timestamp":"2023-06-20T09:41:25.628055Z"}
{"component":"virt-launcher","level":"info","msg":"libvirt version: 8.0.0, package: 2.module_el8.6.0+1087+b42c8331 (CentOS Buildsys \u003cbugs@centos.org\u003e, 2022-02-08-22:20:52, )","subcomponent":"libvirt","thread":"43","timestamp":"2023-06-20T09:41:25.646000Z"}
{"component":"virt-launcher","level":"info","msg":"hostname: testvm","subcomponent":"libvirt","thread":"43","timestamp":"2023-06-20T09:41:25.646000Z"}
{"component":"virt-launcher","level":"error","msg":"internal error: Child process (dmidecode -q -t 0,1,2,3,4,11,17) unexpected exit status 1: /dev/mem: No such file or directory","pos":"virCommandWait:2752","subcomponent":"libvirt","thread":"43","timestamp":"2023-06-20T09:41:25.646000Z"}
{"component":"virt-launcher","level":"info","msg":"Connected to libvirt daemon","pos":"libvirt.go:513","timestamp":"2023-06-20T09:41:26.129059Z"}
{"component":"virt-launcher","level":"info","msg":"Registered libvirt event notify callback","pos":"client.go:510","timestamp":"2023-06-20T09:41:26.165576Z"}
{"component":"virt-launcher","level":"info","msg":"Marked as ready","pos":"virt-launcher.go:74","timestamp":"2023-06-20T09:41:26.165720Z"}

**Comment by aburdenthehand** [comment]
@JUNgege10 
I can't say what the specific problem is but your K8s version is very old - I think 1.18 finished support about 2 years ago.
I would recommend updating to a supported version.

**Comment by JUNgege10** [comment]
@aburdenthehand   True, but I upgraded to version 1.23.17 with the same error

**Comment by aburdenthehand** [comment]
I see some similarities between your bug and this one: https://github.com/kubevirt/kubevirt/issues/8429
@xpivarc what do you think?

**Comment by xpivarc** [comment]
Hi @wenjunGU ,
Would be able to provide virt-handler logs? Also is there any other entry in virt-launcher log?
