### ISSUE TITLE
Introduce `virtctl display`

### ISSUE THREAD

**Issue by fabiand** [kubevirt/kubevirt#996]
Today we need to either use `virtctl spice` or `virtctl vnc`.

In order to make it more convenient - and intention focused - it would be nice to just expose `virtctl display` (eventually witha flag to enforce a certain connection method), which auto-detects what options are available (vnc/spice) and choose the best option.

Th emain reason is that a user must not worry about the correct lower-level protocol to conncet to a virtual machine display.

**Comment by rmohr** [comment]
I am sceptical about this. It is something different to choose between spice, vnc, rdp, than choosing between  different shells **in** a container in the context of `kubectl exec`, compared to these protocols which need  client-side support to work properly. Further a lot of different flags may apply to different types.

**Comment by fabiand** [comment]
There is a difference between vnc, spice and rdp.

vnc and spice are part of the backend. rdp is a guest supported one.

The system can decide whether the VM offers vnc or spice, thus the client also knows about it and can make the right decision, without requiring the user to make a decision.

I was thinking along the lines of:

```bash
virtctl display testvm
virtctl display --vnc testvm
virtctl display --spice testvm
```

Actually, for the last two there is no reason, as if the vm is configured with spice or vnc, then the other will not work.

**Comment by rmohr** [comment]
> Actually, for the last two there is no reason, as if the vm is configured with spice or vnc, then the other will not work.

Technically there is no reason to not have both at the same time: https://bugzilla.redhat.com/show_bug.cgi?id=975751.

> There is a difference between vnc, spice and rdp.
> vnc and spice are part of the backend. rdp is a guest supported one.

So why making it for the built-in ones intransparent which one will be used? Further there may be different override-flags appropriate for different types and I would want to keep it consistent for all access types that they are explicit:

```
virtctl vnc
virtctl spice
virtctl ssh
virtctl winrm
virtctl console
virtctl scp
virtctl rdp
```

**Comment by fabiand** [comment]
Even if it's technical possible, I doubt that we want to permit to enable VNC and spice at the same time. (Further more the question is if both can be connected at the same time!)

In general we can pretty much take the decision off the user whenever we control something. This is true for all backend configurations.
We can not make the decision when it's a guest sided configuration.

With this in mind we can split your list:

Under our control:

```
vnc
spice
console
```

Not under our control:
```
ssh
winrm
scp
rdp
```

Thus for the latter we _need_ to keep it explicit, as we have no sane way to decide whether the guest has that feature enabled or not.
Because it is a guest feature I'd actually tend to say that we might move it to a dedicated verb, i.e.

```
virtctl guest rdp
virtctl guest winrm
virtctl guest ssh
virtctl guest scp
virtctl guest http
virtctl guest https
```

**Comment by rmohr** [comment]
I pretty much completely disagree but it is not important enough for me to spend more time on this.

**Comment by michalskrivanek** [comment]
> I doubt that we want to permit to enable VNC and spice at the same time.

we can, and it's actually quite helpful as it gives you more freedom to choose appropriate client.

**Comment by michalskrivanek** [comment]
I would agree with separation of "out of band" protocols vnc/spice/serial from guest protocols rdp/ssh/etc.
But I indeed do not believe we can make some automated choice

**Comment by rmohr** [comment]
> I would agree with separation of "out of band" protocols vnc/spice/serial from guest protocols rdp/ssh/etc.

I still don't see why I would always want to write an extra `guest` verb when I want to e.g. use `ssh`.

**Comment by michalskrivanek** [comment]
I think it would be helpful to clearly separate out-of-band consoles which always work from guest cooperation protocols. 
Not necessarily by additional verb. Maybe just a clarification in help string is enough.
Though if we'd ever add guest VNC (why not, it's the same as RDP) you would probably want to differentiate from qemu's VNC.

**Comment by rmohr** [comment]
If we have native `vnc` and `spice` guest-vnc and guest-spice would probably be the least used options. Therefore I would simply give them explicit more clunky names (e.g. `guest-vnc` or `guest-spice`) and keep the commandline short for the more-popular ones.

**Comment by fabiand** [comment]
> we can, and it's actually quite helpful as it gives you more freedom to choose appropriate client.

Good point. I was more thinking about using them at the same time :)

> I think it would be helpful to clearly separate out-of-band consoles which always work from guest cooperation protocols.
> Not necessarily by additional verb. Maybe just a clarification in help string is enough.

Yes ... Maybe - and in addition good error messages.

Still, there are so many verbs that would pop up which are guest specific that it's also not valueable.

I wonder if we could have verbs for the most prominent ones (ssh, rdp) and hide the others behind a guest verb?

**Comment by yuvalif** [comment]
if we add too many verbs it will clutter "help" and autocompletion. 

how about the following:
virctl vnc
virtctl spice
virtctl console
virtctl ssh
virtctl rdp

virtctl guest winrm
virtctl guest scp
virtctl guest http
virtctl guest https
virtctl guest vnc
virtctl guest spice

another option, would be to scope out the "guest xxx" options from this enhancement. maybe add them later if there is need?

**Comment by michalskrivanek** [comment]
> I wonder if we could have verbs for the most prominent ones (ssh, rdp) and hide the others behind a guest verb?

We should clearly separate out-of-band from guest protocols. SSH and RDP are still in-guest protocols, no matter how prominent they could be, and we should not mix them up with those which are independent on guest

**Comment by rmohr** [comment]
> if we add too many verbs it will clutter "help" and autocompletion.

That should really be the least of our problems. Did you ever run `kubectl --help`? It has a lot and it is still very informative. We can follow the same patterns and it kubectl also supports autocomplete. I never found it confusing.

**Comment by rmohr** [comment]
> We should clearly separate out-of-band from guest protocols. SSH and RDP are still in-guest protocols, no matter how prominent they could be, and we should not mix them up with those which are independent on guest

We can have list them as separate types in the help page. E.g. like `kubectl` does:

```
[...]
Advanced Commands:
  apply          Apply a configuration to a resource by filename or stdin
  patch          Update field(s) of a resource using strategic merge patch
  replace        Replace a resource by filename or stdin
  update         Replace a resource by filename or stdin
  convert        Convert config files between different API versions

Settings Commands:
  label          Update the labels on a resource
  annotate       Update the annotations on a resource
  completion     Output shell completion code for the specified shell (bash or zsh)

[...]
```

I really can't understand the issue. Also `kubectl` has commands like `proxy` or `port-forward` on the same command level although they are for completely separate things. Also there `port-forward` depends on the pod content and it is still not behind `kubectl pod port-forward` or something.

**Comment by michalskrivanek** [comment]
IIUC it doesn't depend on the actual POD content - or does it? The fact that you forward a port is something you set up in infra and let app talk to a port. Whether there is any useful service running on that port inside the container is irrelevant. With guest rdp/ssh you presume that it's running and ready. That's why I wouldn't mix it up with things which do not depend on whether anything is running in guest or not.

As I said before, separating them in documentation is fine

**Comment by yuvalif** [comment]
ok. trying to converge on the requirements. will add the following CLI verbs:
MUST:
```
virtctl vnc
virtctl spice
virtctl console
virtctl ssh
virtctl rdp
```
SHOULD (may split to a different issue):
```
virtctl winrm
virtctl scp
virtctl http
virtctl https
virtctl guest-vnc
virtctl guest-spice
```
these will be spread under two different documentation sections:
- host supported: vnc, spice, console
- requires guest support: ssh, rdp, winrm, scp, http, https, guest-vnc, guest-spice

**Comment by rmohr** [comment]
> virtctl http
> virtctl https

What are these for? I would prefer having a `port-forward` command instead if that is for forwarding ports.

**Comment by yuvalif** [comment]
not sure about priority, but this (or subset of it) is probably still needed.
