### ISSUE TITLE
Fixing Errors and Improving Clarity in CONTRIBUTING.md File.

### ISSUE THREAD

**Issue by aroramrinaal** [kubevirt/kubevirt#9961]
### Issue Description:
The current CONTRIBUTING.md file in the project repository contains several errors, typos, and unclear wording. This issue aims to address these issues and improve the overall quality and clarity of the CONTRIBUTING.md file. By doing so, we can enhance the onboarding experience for new contributors and ensure that the contributing guidelines are accurate and easy to understand.

### Proposed Changes:
https://github.com/kubevirt/kubevirt/blob/22ad8cca72e54dc760398f6556d3a7d03b0cb4ab/CONTRIBUTING.md?plain=1#L5
→ `* **Kubernetes** is a container orchestration system, and is used for running.` 

https://github.com/kubevirt/kubevirt/blob/22ad8cca72e54dc760398f6556d3a7d03b0cb4ab/CONTRIBUTING.md?plain=1#L10
→`"they have" should be "it has" `to maintain consistency with the singular noun "KubeVirt."

https://github.com/kubevirt/kubevirt/blob/22ad8cca72e54dc760398f6556d3a7d03b0cb4ab/CONTRIBUTING.md?plain=1#L17
→ `"shall" should be replaced with "will"` for better readability.

https://github.com/kubevirt/kubevirt/blob/22ad8cca72e54dc760398f6556d3a7d03b0cb4ab/CONTRIBUTING.md?plain=1#L48
→`"issues"` should not be capitalized

https://github.com/kubevirt/kubevirt/blob/22ad8cca72e54dc760398f6556d3a7d03b0cb4ab/CONTRIBUTING.md?plain=1#L81
→`by this act, expressing that they comply` to improve the sentence structure.

https://github.com/kubevirt/kubevirt/blob/22ad8cca72e54dc760398f6556d3a7d03b0cb4ab/CONTRIBUTING.md?plain=1#L116
→ `"Getting started" should be "Getting Started`" for consistency with the title casing.

https://github.com/kubevirt/kubevirt/blob/22ad8cca72e54dc760398f6556d3a7d03b0cb4ab/CONTRIBUTING.md?plain=1#L141
→`"A Golang BDD Testing Framework" should be "a Golang BDD Testing Framework"` as "a" should be lowercase.

### Expected Outcome:
By addressing these issues, we can ensure that the CONTRIBUTING.md file provides clear and accurate guidelines for contributors, fostering a more streamlined and efficient contribution process. This will ultimately contribute to the overall success and growth of the project.

**Comment by alicefr** [comment]
@aroramrinaal it is hard to review and apply the changes in an issue. Would you mind opening a PR with your proposed changes?
