### ISSUE TITLE
Some multi-arch images do not have a manifest

### ISSUE THREAD

**Issue by nunnatsa** [kubevirt/kubevirt#9964]
Some images are pushed to the image registry with arch aware tag (e.g. `v1.0.0-rc.0-amd64` or `v1.0.0-rc.0-arm64`), but there is no common manifest with the version tag for these images (e.g. `v1.0.0-rc.0`).

HCO is using two of these images: `libguestfs-tools` and `virtio-container-disk`, and is looking for the version tag. This is now blocks the bump of KubeVirt in HCO.

I think it's a blocker for release `v1.0.0`.

**Comment by nunnatsa** [comment]
/cc @stu-gott 
/cc @enp0s3
/cc @dhiller 
/cc @brianmcarey 
@fabiand

**Comment by fossedihelm** [comment]
Need to wait for https://github.com/kubevirt/kubevirt/pull/9983 to be merged
