### ISSUE TITLE
apidocs make target fails due to missing dependency

### ISSUE THREAD

**Issue by dhiller** [kubevirt/kubevirt#9966]
**What happened**:

`make apidocs` is missing a gradle dependency, thus the target fails to build.

```
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find ch.netzwerg:paleo-core:0.11.0.
     Searched in the following locations:
       - file:/root/.m2/repository/ch/netzwerg/paleo-core/0.11.0/paleo-core-0.11.0.pom
       - https://repo.maven.apache.org/maven2/ch/netzwerg/paleo-core/0.11.0/paleo-core-0.11.0.pom
       - https://dl.google.com/dl/android/maven2/ch/netzwerg/paleo-core/0.11.0/paleo-core-0.11.0.pom
       - https://jcenter.bintray.com/ch/netzwerg/paleo-core/0.11.0/paleo-core-0.11.0.pom
     Required by:
         project : > io.github.swagger2markup:swagger2markup-gradle-plugin:1.3.3 > io.github.swagger2markup:swagger2markup:1.3.3
   > Could not find nl.jworks.markdown_to_asciidoc:markdown_to_asciidoc:1.0.
     Searched in the following locations:
       - file:/root/.m2/repository/nl/jworks/markdown_to_asciidoc/markdown_to_asciidoc/1.0/markdown_to_asciidoc-1.0.pom
       - https://repo.maven.apache.org/maven2/nl/jworks/markdown_to_asciidoc/markdown_to_asciidoc/1.0/markdown_to_asciidoc-1.0.pom
       - https://dl.google.com/dl/android/maven2/nl/jworks/markdown_to_asciidoc/markdown_to_asciidoc/1.0/markdown_to_asciidoc-1.0.pom
       - https://jcenter.bintray.com/nl/jworks/markdown_to_asciidoc/markdown_to_asciidoc/1.0/markdown_to_asciidoc-1.0.pom
     Required by:
         project : > io.github.swagger2markup:swagger2markup-gradle-plugin:1.3.3 > io.github.swagger2markup:swagger2markup:1.3.3 > io.github.swagger2markup:markup-document-builder:1.1.2

```

See i.e. https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9943/pull-kubevirt-apidocs/1671874820150661120#1:build-log.txt%3A186

When trying to upgrade the dependency like this:

```diff
Index: hack/gen-swagger-doc/build.gradle
IDEA additional info:
Subsystem: com.intellij.openapi.diff.impl.patch.CharsetEP
<+>UTF-8
===================================================================
diff --git a/hack/gen-swagger-doc/build.gradle b/hack/gen-swagger-doc/build.gradle
--- a/hack/gen-swagger-doc/build.gradle	
+++ b/hack/gen-swagger-doc/build.gradle	
@@ -7,6 +7,11 @@
 
     dependencies {
         classpath "io.github.swagger2markup:swagger2markup-gradle-plugin:1.3.3"
+        constraints {
+            implementation('ch.netzwerg:paleo-core:0.12.0') {
+                because 'previous version is gone from mirror'
+            }
+        }
     }
 }
 
```

it seems like not only that exact dependency was deleted, but also all deps above that one.

Therefore we had to [disable the required lane `pull-kubevirt-apidocs`](https://github.com/kubevirt/project-infra/pull/2846).

**What you expected to happen**:
`make apidocs` should succeed.

**How to reproduce it (as minimally and precisely as possible)**:
Run locally:

$ make apidocs

or run

/test pull-kubevirt-apidocs

on any PR.

**Additional context**:

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by dhiller** [comment]
It is worth noting that the deleted dependency [contains a CVE](https://mvnrepository.com/artifact/ch.netzwerg/paleo-core/0.14.0) .

**Comment by dhiller** [comment]
Another impacted lane is [push-kubevirt-main](https://prow.ci.kubevirt.io/job-history/gs/kubevirt-prow/logs/push-kubevirt-main).

Example: https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/logs/push-kubevirt-main/1671853503338778624

**Comment by xpivarc** [comment]
This also impacts the release of v1 or any other minor release.

@dhiller Do we have an alias for the release team/folks interested in the release?

**Comment by dhiller** [comment]
@xpivarc not that I am aware of. It would make sense to create such a team.

**Comment by fossedihelm** [comment]
@xpivarc @dhiller Seems like `make apidocs` works now. I tested it in my local machine and also https://prow.ci.kubevirt.io/view/gs/kubevirt-prow/pr-logs/pull/kubevirt_kubevirt/9985/pull-kubevirt-apidocs/1674350982420500480 here.

**Comment by dhiller** [comment]
@fossedihelm thanks for the heads up. I would still rather see the gradle stuff replaced so that we don't trip over such a thing again.

/close
