### ISSUE TITLE
Nvidia vGPU, Windows / UEFI VM, dedicated domain xml configuration needed (X-PciMmio64Mb)

### ISSUE THREAD

**Issue by benth42** [kubevirt/kubevirt#9968]
Hello,

I'm currently testing nvidia vGPU with kubevirt as orchestrator and KVM as hypervisor. 

I have managed to get gpu operator working with last nvidia drivers series (15.2 software stack, driver series 525). 
Nvidia vGPU are available inside VM (nvidia-smi reports them on linux with the proper driver installed).

But for Windows VM and more largely booted with uefi I get an error code 12 after driver installation ... Well this a know issue and documented in nvidia drivers release notes.

To workaround a dedicated configuration of the libivirt domain XML is required. 
I hope we could do something about this needs.

https://docs.nvidia.com/grid/15.0/grid-vgpu-release-notes-generic-linux-kvm/index.html#bug-200719557-vgpu-graphics-driver-fails-to-load-linux-kvm-vm

Extract from the link above : 

--------------------------------------------------------
 _Declare the custom libvirt XML namespace that supports command-line pass through of QEMU arguments.
Declare this namesapce by modifying the start tag of the top-level domain element in the first line of the XML document._
```
<domain type='kvm' xmlns:qemu='http://libvirt.org/schemas/domain/qemu/1.0'>
```
_At the end of the XML document, between the </devices> end tag and the </domain> end tag, add the highlighted qemu elements.
These elements pass the QEMU arguments for mapping the required BAR resources into the VM._
```
</devices>
  <qemu:commandline>
    <qemu:arg value='-fw_cfg'/>
    <qemu:arg value='opt/ovmf/X-PciMmio64Mb,string=262144'/>
  </qemu:commandline>
</domain>
```
--------------------------------------------------------

Well for quick test purpose can you point me a place in the code to do this modification ? 
I was thinking about "pkg/virt-launcher/virtwrap/converter/converter.go" ? or a hook ? 

Thank you in advance

Regards,

**Comment by aburdenthehand** [comment]
@rthallisey Is this something you can help with?

**Comment by rthallisey** [comment]
`pkg/virt-launcher/virtwrap/converter/converter.go` is one of the places.  You would need to enable it on kubevirt's api too which would mean looking for some annotation on the vmi.   So you would need to wire up something that goes from the virt-api -> virt-controller -> virt-handler, then the last step would be location you posted.

**Comment by raultang** [comment]
@benth42 Have you resolve this finally? I met similar situation need edit QEMU arguments.

**Comment by benth42** [comment]
> @benth42 Did you resolve this finally? I met similar situation need edit QEMU arguments.

Not really ... run Linux VM or without uefi ...
