### ISSUE TITLE
MAC address change after VM reboot

### ISSUE THREAD

**Issue by remram44** [kubevirt/kubevirt#9993]
**What happened**:
After shutting down and starting a VM again, I am not able to SSH into the VM. It has no connectivity.

**What you expected to happen**:
A VM configured with cloud-init stays available across restarts.

**How to reproduce it (as minimally and precisely as possible)**:
1. Create VM
2. Stop VM with virtctl
3. Start VM with virtctl

**Additional context**:
This is because the VMI's MAC addresses are generated randomly every time. This causes the networkd or netplan configuration generated by cloud-init to no longer match the interfaces.

The MAC addresses should be persisted in a VM instead of re-generated in new VMIs.

This is an exact duplicate of issue #1251 which was closed anyway when the possibility to select a MAC address was added (which doesn't fix the issue).

**Environment**:
- KubeVirt version (use `virtctl version`): 0.59.1
- Kubernetes version (use `kubectl version`): 1.25.10
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by EdDev** [comment]
In order to have a consistent/persistent mac address, users have two options:
- Define the MAC address explicitly in the VM Spec for the relevant interface.
- Use KMP [1] to automate the MAC address assignment.

If you have tried to use one of these options and it still does not work for you, please feedback and include the manifest you used and versions.

[1] https://github.com/k8snetworkplumbingwg/kubemacpool

/assign EdDev

**Comment by remram44** [comment]
I don't need "collision-aware allocation", I don't have "multiple CNI plugins". I just need KubeVirt to not actively shoot itself in the foot...

Why not just make MAC address allocation deterministic? Or fill them in the VM fields rather than VMI?

I guess I can use an admission controller to patch the manifests that don't work with your software, but why not fix the bug?

**Comment by EdDev** [comment]
> I don't need "collision-aware allocation", I don't have "multiple CNI plugins". I just need KubeVirt to not actively shoot itself in the foot...

KMP has two goals, one to assign always a mac address to the VM manifest and the second to make it unique across the cluster.
If you need one of these, you can use it.
 
> Why not just make MAC address allocation deterministic? Or fill them in the VM fields rather than VMI?

You can, and in your case, you should do it.
But the assumption that everyone needs it is not accurate.
At the minimum, we do not force it upon users, it is left up to them to opt-in to this behavior.

As an operator, you can install KMP on the cluster and enforce this on the cluster users.

> I guess I can use an admission controller to patch the manifests that don't work with your software, but why not fix the bug?

Kubevirt has the VM object representing the "persisted" configuration of a Virtual Machine, and the VMI object as the running instance if it. When the VM is stopped, the VMI is gone, toghether with its volatile configuration.
If you are interested in preserving a configuration between boots, you need to define it explicitly in the VM manifest.
If you want the mac address to be persisted, you need to add it to the configuration or let someone do it.
KMP can do it for you, or you can do your own thing if you want.

If you have an enhancement proposal, you are welcome to post it, explaining why the current solutions are not a fit for you.

**Comment by remram44** [comment]
I don't think any user expect the MAC addresses to be "volatile configuration". In fact, cloud-init explicitly relies on this not being the case.

I agree that volatile configuration might go away, I don't agree with your assessment that this should be part of it, or that **"not every user" needs cloud-init to function out of the box**.

**Comment by EdDev** [comment]
Perhaps it will be useful to go one step back and ask: Why you cannot use KMP to resolve the issue you have?

**Comment by remram44** [comment]
Why not take the full step back, and ask: Why should I install additional software for functionality included in KubeVirt to actually function, like cloud-init?

Should software come with functionality that doesn't actually work without an additional component?

**Comment by EdDev** [comment]
The additional component solves the problem so no one saw a reason to invest in it further.
On some D/S deployments, KMP is an integral part of the solution and is deployed with it.

I think that reasoning for being all-inclusive with the solutions is not fitting that well with the K8S echosystem.
As an example, KubeVirt does not provide all network solutions itself, it depends on network providers, CNI plugins and node network management (k-nmstate) to operate.
It can work well without any additions for some scenarios, and will not work smooth for others.

If you do have a practical solution of how this can be done, it will be great to see a design proposal been sent for review. Contributions are always welcome.

**Comment by remram44** [comment]
> On some D/S deployments, KMP is an integral part of the solution and is deployed with it.

That is fine, however if this is your official position, I think it warrants a **big warning** in your documentation.

Consider for example how Kubernetes requires a network plugin to function (CNI). This is stated prominently in the [concepts > components](https://kubernetes.io/docs/concepts/overview/components/#network-plugins) section and the [cluster administration > cluster networking](https://kubernetes.io/docs/concepts/cluster-administration/networking/) section, in addition to the [extending kubernetes](https://kubernetes.io/docs/concepts/extend-kubernetes/compute-storage-net/network-plugins/) and [installing addons](https://kubernetes.io/docs/concepts/cluster-administration/addons/) sections. **This makes it clear that, while it's a plugin, it is required for proper operation.** It is impossible for users to miss this required component.

In contrast, you say users should depend on this, but your documentation don't mention kubemacpool once. It is not in your [architecture page](https://kubevirt.io/user-guide/architecture/), it is not in your quickstart documents, it is nowhere in your operations doc, it is not mentioned as a requirements in [your cloud-init](https://kubevirt.io/user-guide/virtual_machines/startup_scripts/#injecting-ssh-keys-with-cloud-inits-cloud-config) documentation. You have a [VM lifecycle](https://kubevirt.io/user-guide/virtual_machines/lifecycle/) that doesn't mention anything about MAC addresses being reset, only "running state", and users have no reason to suspect that it includes permanent hardware configuration like MAC addresses.

I think it is a bit dishonest to say that you are just doing the standard K8s ecosystem thing of depending on other components.

-----

> If you do have a practical solution of how this can be done, it will be great to see a design proposal been sent for review. Contributions are always welcome.

I have proposed two solutions here: fill in the MAC addresses on the VM object if not set, or make VM->VMI generation deterministic. You answered that this was out of scope for KubeVirt. This does not make me feel like contributions in this area are welcome at all, but rather that they would be rejected in favor of using kubemacpool.

If you are open to improvements but can't/won't do it yourself, that is perfectly fine, but that is not the impression I got from our conversation...

**Comment by EdDev** [comment]
It was not my intention to give an impression that suggestions for improvements and their contribution will not be welcome.
If you think you can contribute to add the mentioned functionality, I encourage you to post a design for review [here](https://github.com/kubevirt/community/tree/main/design-proposals).
Improvements to the documentation with warnings when appropriate is welcome as well.

> I have proposed two solutions here: fill in the MAC addresses on the VM object if not set,
> or make VM->VMI generation deterministic.

Yes, these are valid options, but as we know, the devil is in the details.

It is fair to say, that we may also look at this issue from different angles.
You wanting a simple integral solution that will solve the problem you encountered, and me wanting to ease maintenance. It may be surprising, but I am interested to see KMP gone and solve the same with a simpler mechanism, unfortunately the opportunity has not presented itself and no one had the priority to invest in this.

---

Back to the original issue, KubeVirt does not have an integral solution for automatic mac assignment,  it relies on clients that generate the VM manifest and specify a specific MAC address, or on services like KMP that are external and do it automatically.

Perhaps it is also worth noting that in some cases, having a duplicate consistent mac on the primary interface (the pod network) for all VM/s is a valid configuration. For example, with the masquerade binding, having the same MAC address for all running VM/s is not a problem, as all are hidden from the outside world through the NAT.

**Comment by EdDev** [comment]
As for now, there are no plans to solve this issue natively in the project. Our recommendation is to use KMP or alike.

Said that, if such a proposal will be contributed in a form of a design (and later as implementation), we will gladly consider it.

Please feel free to reopen this issue if needed.

/close

**Comment by pbasov** [comment]
I keep asking myself why am I even using kubevirt at this point. All I wanted is to connect a VM into an existing linux bridge and for it to get an IP address. For that I need:
- whereabouts
- kubemacpool
- create some NADs
- not screw up obscure VMI config with a billion options

It's such a bad experience it's insane.
