### ISSUE TITLE
The process of VirtualMachineSnapshot will get stuck if vmi.Freeze() || vmi.Unfreeze() || vmi.Frozen() return err

### ISSUE THREAD

**Issue by Longchuanzheng** [kubevirt/kubevirt#9998]
**What happened**:

VirtualMachineSnapshot will stuck when qga in vm can't handle request like freeze, due to updateVMSnapshotContent always return {0, err}. This will cause VirtualMachineSnapshot can't delete.
 
**What you expected to happen**:

VirtualMachineSnapshot can reflect error like source.Freeze()，as well as we can delete VirtualMachineSnapshot when these error occur.

**How to reproduce it (as minimally and precisely as possible)**:

Find a vm which can't handle request like freeze and create a VirtualMachineSnapshot for it

**Additional context**:

My programming skills let me only come to the improvement of adding event to VirtualMachineSnapshot and VirtualMachineSnapshotContent when errors occur. However, VirtualMachineSnapshot is still stuck and disable to delete.

**Environment**:
- KubeVirt version (use `virtctl version`): N/A
- Kubernetes version (use `kubectl version`): N/A
- VM or VMI specifications: N/A
- Cloud provider or hardware configuration: N/A
- OS (e.g. from /etc/os-release): N/A
- Kernel (e.g. `uname -a`): N/A
- Install tools: N/A
- Others: N/A

**Comment by mhenriks** [comment]
cc @mhenriks @ShellyKa13
